In [1]:
import pandas as pd

books = pd.read_csv("../data/books_with_categories.csv")

In [2]:
from transformers import pipeline

# classifier for Eckman 6: anger, disgust, fear, joy, neutral, sadness, surprise
classifier = pipeline("text-classification",
                      model="j-hartmann/emotion-english-distilroberta-base",
                      top_k = None,
                      device = "mps")
classifier("I love this!")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

[[{'label': 'joy', 'score': 0.9771687984466553},
  {'label': 'surprise', 'score': 0.008528684265911579},
  {'label': 'neutral', 'score': 0.005764600355178118},
  {'label': 'anger', 'score': 0.004419781267642975},
  {'label': 'sadness', 'score': 0.002092392183840275},
  {'label': 'disgust', 'score': 0.001611993182450533},
  {'label': 'fear', 'score': 0.0004138521908316761}]]

In [3]:
books["description"][0]

'Action! Adventure! Space Opera! Life hardly ever turns out the way we expect it to, and for Mykl d’Angelo, skipper and owner of the loderunner Pegasus, it had just taken a bad turn for terrible. Due a minor misunderstanding, his crew had stolen the ship’s only shuttle, leaving him and two others behind to crew the ailing ship on their own. As if that weren’t bad enough, just a few hours later the rickety old ship’s stardrive exploded in the middle of the middle of nowhere, killing Mykl’s two remaining crewmen. Marooned alone in deep space, Mykl d’Angelo counted his blessings, offered prayers to any gods who specialized in miracles, and prepared to await (A) seemingly unlikely rescue, or (B) a lingering death… Rescue takes place, but at a price – as the Antares, a cruiser dispatched to investigate the mysterious silence of a remote starbase crosses paths with a legendary and fearsome Corsair – a man whose name sent shivers down the spines of lesser mortals. Blachart… Blachart the Bloody.'

In [4]:
classifier(books["description"][0])
# not a very accurate classification

[[{'label': 'fear', 'score': 0.7806273102760315},
  {'label': 'sadness', 'score': 0.06796623766422272},
  {'label': 'disgust', 'score': 0.06335310637950897},
  {'label': 'anger', 'score': 0.03837128356099129},
  {'label': 'neutral', 'score': 0.027229905128479004},
  {'label': 'surprise', 'score': 0.02029595337808132},
  {'label': 'joy', 'score': 0.0021562527399510145}]]

In [5]:
# classify sentences individually
classifier(books["description"][0].split("."))

[[{'label': 'fear', 'score': 0.7942874431610107},
  {'label': 'disgust', 'score': 0.06771168857812881},
  {'label': 'sadness', 'score': 0.0398513525724411},
  {'label': 'surprise', 'score': 0.03223242983222008},
  {'label': 'neutral', 'score': 0.03175150230526924},
  {'label': 'anger', 'score': 0.02174588292837143},
  {'label': 'joy', 'score': 0.012419751845300198}],
 [{'label': 'anger', 'score': 0.4011019170284271},
  {'label': 'sadness', 'score': 0.3056371212005615},
  {'label': 'neutral', 'score': 0.18285048007965088},
  {'label': 'disgust', 'score': 0.08870737999677658},
  {'label': 'fear', 'score': 0.010378353297710419},
  {'label': 'surprise', 'score': 0.009017867036163807},
  {'label': 'joy', 'score': 0.0023069221060723066}],
 [{'label': 'surprise', 'score': 0.36239781975746155},
  {'label': 'sadness', 'score': 0.1643228530883789},
  {'label': 'anger', 'score': 0.15371713042259216},
  {'label': 'neutral', 'score': 0.12592284381389618},
  {'label': 'fear', 'score': 0.09634983539581299},
  {'label': 'disgust', 'score': 0.09465891867876053},
  {'label': 'joy', 'score': 0.0026305653154850006}],
 [{'label': 'fear', 'score': 0.9510065317153931},
  {'label': 'neutral', 'score': 0.019595088437199593},
  {'label': 'sadness', 'score': 0.009895997121930122},
  {'label': 'surprise', 'score': 0.006512307096272707},
  {'label': 'disgust', 'score': 0.005539236590266228},
  {'label': 'anger', 'score': 0.00472844485193491},
  {'label': 'joy', 'score': 0.0027223648503422737}],
 [{'label': 'neutral', 'score': 0.3328858017921448},
  {'label': 'sadness', 'score': 0.22474415600299835},
  {'label': 'disgust', 'score': 0.1949133574962616},
  {'label': 'fear', 'score': 0.10767051577568054},
  {'label': 'joy', 'score': 0.04958018660545349},
  {'label': 'surprise', 'score': 0.048743121325969696},
  {'label': 'anger', 'score': 0.04146284982562065}],
 [{'label': 'neutral', 'score': 0.5494773983955383},
  {'label': 'sadness', 'score': 0.11169008165597916},
  {'label': 'disgust', 'score': 0.10400652140378952},
  {'label': 'surprise', 'score': 0.07876541465520859},
  {'label': 'anger', 'score': 0.06413350999355316},
  {'label': 'fear', 'score': 0.05136270076036453},
  {'label': 'joy', 'score': 0.04056432843208313}]]

In [6]:
sentences = books["description"][0].split(".")
predictions = classifier(sentences)
sorted(predictions[0], key=lambda x: x["label"])
# take the sentence with the highest probability for each sentiment

[{'label': 'anger', 'score': 0.02174588292837143},
 {'label': 'disgust', 'score': 0.06771168857812881},
 {'label': 'fear', 'score': 0.7942874431610107},
 {'label': 'joy', 'score': 0.012419751845300198},
 {'label': 'neutral', 'score': 0.03175150230526924},
 {'label': 'sadness', 'score': 0.0398513525724411},
 {'label': 'surprise', 'score': 0.03223242983222008}]

In [7]:
import numpy as np

emotion_labels = ["anger", "disgust", "fear", "joy", "sadness", "surprise", "neutral"]
isbn = []
emotion_scores = {label: [] for label in emotion_labels}

# creates a dictionary for each description containing the maximumm probability for each emotion
def calculate_max_emotion_scores(predictions):
    per_emotion_scores = {label: [] for label in emotion_labels}
    for prediction in predictions:
        sorted_predictions = sorted(prediction, key=lambda x: x["label"])
        for index, label in enumerate(emotion_labels):
            per_emotion_scores[label].append(sorted_predictions[index]["score"])
    return {label: np.max(scores) for label, scores in per_emotion_scores.items()}

In [8]:
# test for the first 10 books
for i in range(10):
    isbn.append(books["isbn13"][i])
    sentences = books["description"][i].split(".")
    predictions = classifier(sentences)
    max_scores = calculate_max_emotion_scores(predictions)
    for label in emotion_labels:
        emotion_scores[label].append(max_scores[label])

In [9]:
emotion_scores

{'anger': [np.float64(0.4011019170284271),
  np.float64(0.39138707518577576),
  np.float64(0.8682214617729187),
  np.float64(0.15240122377872467),
  np.float64(0.33948376774787903),
  np.float64(0.06413350999355316),
  np.float64(0.06413350999355316),
  np.float64(0.04855480045080185),
  np.float64(0.06413350999355316),
  np.float64(0.9279194474220276)],
 'disgust': [np.float64(0.1949133574962616),
  np.float64(0.10400652140378952),
  np.float64(0.3810557723045349),
  np.float64(0.10400652140378952),
  np.float64(0.10400652140378952),
  np.float64(0.10400652140378952),
  np.float64(0.10400652140378952),
  np.float64(0.1865655928850174),
  np.float64(0.10400652140378952),
  np.float64(0.506156861782074)],
 'fear': [np.float64(0.9510065317153931),
  np.float64(0.05136270076036453),
  np.float64(0.9343246817588806),
  np.float64(0.7027426958084106),
  np.float64(0.6079992055892944),
  np.float64(0.05136270076036453),
  np.float64(0.18338298797607422),
  np.float64(0.06624423712491989),
  np.float64(0.05136270076036453),
  np.float64(0.9801434874534607)],
 'joy': [np.float64(0.04958018660545349),
  np.float64(0.3076813220977783),
  np.float64(0.27691903710365295),
  np.float64(0.04056432843208313),
  np.float64(0.25821465253829956),
  np.float64(0.10119491815567017),
  np.float64(0.04056432843208313),
  np.float64(0.00847670715302229),
  np.float64(0.4880104660987854),
  np.float64(0.20593427121639252)],
 'sadness': [np.float64(0.5494773983955383),
  np.float64(0.5494773983955383),
  np.float64(0.9379909634590149),
  np.float64(0.8745926022529602),
  np.float64(0.9442518949508667),
  np.float64(0.8306100368499756),
  np.float64(0.8447305560112),
  np.float64(0.4779946506023407),
  np.float64(0.5494773983955383),
  np.float64(0.8993163704872131)],
 'surprise': [np.float64(0.3056371212005615),
  np.float64(0.11169008165597916),
  np.float64(0.6406717300415039),
  np.float64(0.11169008165597916),
  np.float64(0.11169008165597916),
  np.float64(0.11169008165597916),
  np.float64(0.13160014152526855),
  np.float64(0.8599138855934143),
  np.float64(0.11169008165597916),
  np.float64(0.562334418296814)],
 'neutral': [np.float64(0.36239781975746155),
  np.float64(0.1503235250711441),
  np.float64(0.5318074822425842),
  np.float64(0.07876541465520859),
  np.float64(0.20335465669631958),
  np.float64(0.07876541465520859),
  np.float64(0.2898542582988739),
  np.float64(0.32595840096473694),
  np.float64(0.07876541465520859),
  np.float64(0.14394988119602203)]}

In [10]:
from tqdm import tqdm
import re

emotion_labels = ["anger", "disgust", "fear", "joy", "sadness", "surprise", "neutral"]
isbn = []
emotion_scores = {label: [] for label in emotion_labels}

for i in tqdm(range(len(books))):
    isbn.append(books["isbn13"][i])
    sentences = re.split(r'[.?!]+', books["description"][i])
    predictions = classifier(sentences)
    max_scores = calculate_max_emotion_scores(predictions)
    for label in emotion_labels:
        emotion_scores[label].append(max_scores[label])

  0%|          | 0/100629 [00:00<?, ?it/s]

  0%|          | 1/100629 [00:00<2:50:35,  9.83it/s]

  0%|          | 3/100629 [00:00<2:36:38, 10.71it/s]

  0%|          | 7/100629 [00:00<1:18:44, 21.30it/s]

  0%|          | 10/100629 [00:00<1:31:38, 18.30it/s]

  0%|          | 13/100629 [00:00<2:18:13, 12.13it/s]

  0%|          | 15/100629 [00:01<2:43:32, 10.25it/s]

  0%|          | 17/100629 [00:01<2:49:57,  9.87it/s]

  0%|          | 20/100629 [00:01<2:17:50, 12.16it/s]

  0%|          | 23/100629 [00:01<2:05:40, 13.34it/s]

  0%|          | 26/100629 [00:01<1:52:51, 14.86it/s]

  0%|          | 28/100629 [00:02<1:48:25, 15.47it/s]

  0%|          | 30/100629 [00:02<1:52:20, 14.92it/s]

  0%|          | 33/100629 [00:02<1:33:43, 17.89it/s]

  0%|          | 36/100629 [00:02<1:23:36, 20.05it/s]

  0%|          | 39/100629 [00:02<1:44:15, 16.08it/s]

  0%|          | 41/100629 [00:02<2:01:57, 13.75it/s]

  0%|          | 43/100629 [00:03<2:45:48, 10.11it/s]

  0%|          | 45/100629 [00:03<2:48:26,  9.95it/s]

  0%|          | 48/100629 [00:03<2:13:25, 12.56it/s]

  0%|          | 52/100629 [00:03<1:38:05, 17.09it/s]

  0%|          | 55/100629 [00:03<1:30:22, 18.55it/s]

  0%|          | 58/100629 [00:04<1:30:22, 18.55it/s]

  0%|          | 61/100629 [00:04<1:35:49, 17.49it/s]

  0%|          | 63/100629 [00:04<1:34:53, 17.66it/s]

  0%|          | 65/100629 [00:04<1:33:36, 17.91it/s]

  0%|          | 67/100629 [00:04<2:27:29, 11.36it/s]

  0%|          | 69/100629 [00:05<3:02:27,  9.19it/s]

  0%|          | 71/100629 [00:05<2:46:45, 10.05it/s]

  0%|          | 73/100629 [00:05<2:52:30,  9.71it/s]

  0%|          | 76/100629 [00:05<2:14:19, 12.48it/s]

  0%|          | 78/100629 [00:05<2:01:02, 13.85it/s]

  0%|          | 80/100629 [00:05<2:14:29, 12.46it/s]

  0%|          | 83/100629 [00:06<1:47:31, 15.59it/s]

  0%|          | 85/100629 [00:06<1:51:35, 15.02it/s]

  0%|          | 87/100629 [00:06<2:13:24, 12.56it/s]

  0%|          | 89/100629 [00:06<2:26:33, 11.43it/s]

  0%|          | 91/100629 [00:06<2:25:45, 11.50it/s]

  0%|          | 93/100629 [00:07<2:35:09, 10.80it/s]

  0%|          | 95/100629 [00:07<2:21:17, 11.86it/s]

  0%|          | 98/100629 [00:07<2:20:28, 11.93it/s]

  0%|          | 100/100629 [00:07<2:05:31, 13.35it/s]

  0%|          | 102/100629 [00:07<2:34:04, 10.87it/s]

  0%|          | 105/100629 [00:07<2:00:44, 13.88it/s]

  0%|          | 107/100629 [00:08<2:16:39, 12.26it/s]

  0%|          | 110/100629 [00:08<1:52:44, 14.86it/s]

  0%|          | 112/100629 [00:08<1:51:49, 14.98it/s]

  0%|          | 114/100629 [00:08<1:57:32, 14.25it/s]

  0%|          | 116/100629 [00:08<1:57:35, 14.25it/s]

  0%|          | 118/100629 [00:08<1:59:09, 14.06it/s]

  0%|          | 120/100629 [00:08<1:56:19, 14.40it/s]

  0%|          | 122/100629 [00:09<2:18:53, 12.06it/s]

  0%|          | 125/100629 [00:09<1:55:40, 14.48it/s]

  0%|          | 127/100629 [00:09<1:49:56, 15.23it/s]

  0%|          | 130/100629 [00:09<1:37:01, 17.26it/s]

  0%|          | 132/100629 [00:09<1:42:16, 16.38it/s]

  0%|          | 135/100629 [00:09<1:27:40, 19.10it/s]

  0%|          | 138/100629 [00:09<1:33:41, 17.88it/s]

  0%|          | 140/100629 [00:10<1:32:35, 18.09it/s]

  0%|          | 142/100629 [00:10<1:32:27, 18.11it/s]

  0%|          | 145/100629 [00:10<1:21:43, 20.49it/s]

  0%|          | 149/100629 [00:10<1:13:46, 22.70it/s]

  0%|          | 152/100629 [00:10<1:17:28, 21.62it/s]

  0%|          | 155/100629 [00:10<1:20:38, 20.77it/s]

  0%|          | 158/100629 [00:10<1:25:25, 19.60it/s]

  0%|          | 160/100629 [00:11<1:32:03, 18.19it/s]

  0%|          | 163/100629 [00:11<1:21:26, 20.56it/s]

  0%|          | 166/100629 [00:11<1:31:01, 18.40it/s]

  0%|          | 170/100629 [00:11<1:15:57, 22.04it/s]

  0%|          | 174/100629 [00:11<1:09:43, 24.01it/s]

  0%|          | 177/100629 [00:11<1:18:13, 21.40it/s]

  0%|          | 180/100629 [00:12<1:29:24, 18.72it/s]

  0%|          | 183/100629 [00:12<1:20:11, 20.88it/s]

  0%|          | 186/100629 [00:12<1:36:29, 17.35it/s]

  0%|          | 188/100629 [00:12<1:43:09, 16.23it/s]

  0%|          | 191/100629 [00:12<1:29:56, 18.61it/s]

  0%|          | 194/100629 [00:12<1:19:23, 21.09it/s]

  0%|          | 197/100629 [00:12<1:20:19, 20.84it/s]

  0%|          | 200/100629 [00:13<1:19:58, 20.93it/s]

  0%|          | 203/100629 [00:13<1:25:09, 19.65it/s]

  0%|          | 206/100629 [00:13<2:16:15, 12.28it/s]

  0%|          | 208/100629 [00:13<2:08:25, 13.03it/s]

  0%|          | 212/100629 [00:13<1:43:19, 16.20it/s]

  0%|          | 216/100629 [00:14<1:24:18, 19.85it/s]

  0%|          | 219/100629 [00:14<1:33:00, 17.99it/s]

  0%|          | 222/100629 [00:14<1:24:17, 19.85it/s]

  0%|          | 225/100629 [00:14<1:29:12, 18.76it/s]

  0%|          | 228/100629 [00:14<1:37:01, 17.25it/s]

  0%|          | 231/100629 [00:14<1:45:05, 15.92it/s]

  0%|          | 235/100629 [00:15<1:28:28, 18.91it/s]

  0%|          | 238/100629 [00:15<1:28:38, 18.88it/s]

  0%|          | 242/100629 [00:15<1:22:24, 20.30it/s]

  0%|          | 246/100629 [00:15<1:15:01, 22.30it/s]

  0%|          | 249/100629 [00:15<1:24:18, 19.84it/s]

  0%|          | 252/100629 [00:16<1:35:36, 17.50it/s]

  0%|          | 254/100629 [00:16<1:36:36, 17.32it/s]

  0%|          | 259/100629 [00:16<1:14:31, 22.45it/s]

  0%|          | 262/100629 [00:16<1:29:39, 18.66it/s]

  0%|          | 265/100629 [00:16<1:21:41, 20.48it/s]

  0%|          | 269/100629 [00:16<1:21:51, 20.43it/s]

  0%|          | 272/100629 [00:16<1:26:18, 19.38it/s]

  0%|          | 276/100629 [00:17<1:13:41, 22.70it/s]

  0%|          | 280/100629 [00:17<1:04:45, 25.83it/s]

  0%|          | 284/100629 [00:17<1:03:20, 26.40it/s]

  0%|          | 287/100629 [00:17<1:09:37, 24.02it/s]

  0%|          | 290/100629 [00:17<1:06:54, 24.99it/s]

  0%|          | 293/100629 [00:17<1:16:28, 21.87it/s]

  0%|          | 296/100629 [00:17<1:14:47, 22.36it/s]

  0%|          | 299/100629 [00:18<1:15:17, 22.21it/s]

  0%|          | 302/100629 [00:18<1:09:38, 24.01it/s]

  0%|          | 305/100629 [00:18<1:08:04, 24.56it/s]

  0%|          | 309/100629 [00:18<1:04:02, 26.11it/s]

  0%|          | 312/100629 [00:18<1:07:51, 24.64it/s]

  0%|          | 315/100629 [00:18<1:14:02, 22.58it/s]

  0%|          | 318/100629 [00:18<1:09:26, 24.07it/s]

  0%|          | 321/100629 [00:19<1:35:04, 17.59it/s]

  0%|          | 324/100629 [00:19<1:34:47, 17.64it/s]

  0%|          | 327/100629 [00:19<1:23:37, 19.99it/s]

  0%|          | 331/100629 [00:19<1:09:36, 24.01it/s]

  0%|          | 335/100629 [00:19<1:02:46, 26.62it/s]

  0%|          | 339/100629 [00:19<59:00, 28.33it/s]

  0%|          | 343/100629 [00:19<1:10:16, 23.78it/s]

  0%|          | 348/100629 [00:20<1:00:34, 27.59it/s]

  0%|          | 351/100629 [00:20<59:52, 27.92it/s]

  0%|          | 354/100629 [00:20<1:03:31, 26.31it/s]

  0%|          | 357/100629 [00:20<1:07:47, 24.65it/s]

  0%|          | 360/100629 [00:20<1:29:57, 18.58it/s]

  0%|          | 363/100629 [00:20<1:29:19, 18.71it/s]

  0%|          | 366/100629 [00:21<1:29:41, 18.63it/s]

  0%|          | 368/100629 [00:21<1:28:57, 18.78it/s]

  0%|          | 370/100629 [00:21<1:41:10, 16.52it/s]

  0%|          | 372/100629 [00:21<1:42:13, 16.35it/s]

  0%|          | 375/100629 [00:21<1:33:03, 17.95it/s]

  0%|          | 377/100629 [00:21<1:33:06, 17.94it/s]

  0%|          | 379/100629 [00:21<1:43:52, 16.09it/s]

  0%|          | 383/100629 [00:22<1:24:24, 19.79it/s]

  0%|          | 386/100629 [00:22<1:28:34, 18.86it/s]

  0%|          | 389/100629 [00:22<1:21:27, 20.51it/s]

  0%|          | 392/100629 [00:22<1:13:54, 22.61it/s]

  0%|          | 395/100629 [00:22<1:13:22, 22.77it/s]

  0%|          | 399/100629 [00:22<1:02:31, 26.72it/s]

  0%|          | 402/100629 [00:22<1:11:35, 23.33it/s]

  0%|          | 405/100629 [00:22<1:13:03, 22.86it/s]

  0%|          | 408/100629 [00:23<1:14:53, 22.30it/s]

  0%|          | 411/100629 [00:23<1:11:28, 23.37it/s]

  0%|          | 415/100629 [00:23<1:02:30, 26.72it/s]

  0%|          | 418/100629 [00:23<1:00:52, 27.43it/s]

  0%|          | 422/100629 [00:23<56:08, 29.74it/s]

  0%|          | 426/100629 [00:23<1:01:58, 26.95it/s]

  0%|          | 429/100629 [00:23<1:02:04, 26.91it/s]

  0%|          | 432/100629 [00:23<1:09:31, 24.02it/s]

  0%|          | 435/100629 [00:24<1:19:17, 21.06it/s]

  0%|          | 439/100629 [00:24<1:09:06, 24.17it/s]

  0%|          | 442/100629 [00:24<1:07:57, 24.57it/s]

  0%|          | 445/100629 [00:24<1:11:54, 23.22it/s]

  0%|          | 448/100629 [00:24<1:12:21, 23.08it/s]

  0%|          | 451/100629 [00:24<1:12:11, 23.13it/s]

  0%|          | 454/100629 [00:24<1:11:13, 23.44it/s]

  0%|          | 458/100629 [00:25<1:02:20, 26.78it/s]

  0%|          | 461/100629 [00:25<1:07:29, 24.74it/s]

  0%|          | 464/100629 [00:25<1:26:56, 19.20it/s]

  0%|          | 468/100629 [00:25<1:13:11, 22.81it/s]

  0%|          | 471/100629 [00:25<1:20:32, 20.73it/s]

  0%|          | 474/100629 [00:25<1:15:47, 22.02it/s]

  0%|          | 477/100629 [00:25<1:15:13, 22.19it/s]

  0%|          | 480/100629 [00:26<1:21:39, 20.44it/s]

  0%|          | 483/100629 [00:26<1:16:18, 21.87it/s]

  0%|          | 487/100629 [00:26<1:08:27, 24.38it/s]

  0%|          | 490/100629 [00:26<1:05:30, 25.48it/s]

  0%|          | 493/100629 [00:26<1:04:41, 25.80it/s]

  0%|          | 496/100629 [00:26<1:05:56, 25.31it/s]

  0%|          | 499/100629 [00:26<1:10:01, 23.83it/s]

  0%|          | 502/100629 [00:27<1:21:32, 20.46it/s]

  1%|          | 505/100629 [00:27<1:16:30, 21.81it/s]

  1%|          | 508/100629 [00:27<1:21:48, 20.40it/s]

  1%|          | 512/100629 [00:27<1:09:42, 23.94it/s]

  1%|          | 515/100629 [00:27<1:08:27, 24.37it/s]

  1%|          | 519/100629 [00:27<1:03:45, 26.17it/s]

  1%|          | 523/100629 [00:27<57:48, 28.86it/s]

  1%|          | 529/100629 [00:27<47:40, 34.99it/s]

  1%|          | 533/100629 [00:28<1:02:23, 26.74it/s]

  1%|          | 537/100629 [00:28<1:06:36, 25.04it/s]

  1%|          | 540/100629 [00:28<1:04:11, 25.98it/s]

  1%|          | 543/100629 [00:28<1:05:37, 25.42it/s]

  1%|          | 546/100629 [00:28<1:08:50, 24.23it/s]

  1%|          | 551/100629 [00:28<56:28, 29.54it/s]

  1%|          | 555/100629 [00:29<1:05:28, 25.47it/s]

  1%|          | 558/100629 [00:29<1:09:21, 24.05it/s]

  1%|          | 561/100629 [00:29<1:11:35, 23.29it/s]

  1%|          | 565/100629 [00:29<1:02:06, 26.85it/s]

  1%|          | 568/100629 [00:29<1:05:34, 25.43it/s]

  1%|          | 571/100629 [00:29<1:04:28, 25.86it/s]

  1%|          | 574/100629 [00:29<1:04:27, 25.87it/s]

  1%|          | 577/100629 [00:29<1:04:32, 25.84it/s]

  1%|          | 580/100629 [00:30<1:13:52, 22.57it/s]

  1%|          | 583/100629 [00:30<1:11:39, 23.27it/s]

  1%|          | 586/100629 [00:30<1:25:40, 19.46it/s]

  1%|          | 589/100629 [00:30<1:22:20, 20.25it/s]

  1%|          | 592/100629 [00:30<1:19:19, 21.02it/s]

  1%|          | 595/100629 [00:30<1:13:21, 22.73it/s]

  1%|          | 598/100629 [00:30<1:11:12, 23.41it/s]

  1%|          | 602/100629 [00:31<1:01:01, 27.32it/s]

  1%|          | 606/100629 [00:31<56:59, 29.25it/s]

  1%|          | 610/100629 [00:31<52:14, 31.91it/s]

  1%|          | 614/100629 [00:31<1:17:14, 21.58it/s]

  1%|          | 617/100629 [00:31<1:15:34, 22.06it/s]

  1%|          | 620/100629 [00:31<1:23:18, 20.01it/s]

  1%|          | 623/100629 [00:31<1:17:01, 21.64it/s]

  1%|          | 627/100629 [00:32<1:05:27, 25.46it/s]

  1%|          | 631/100629 [00:32<58:35, 28.45it/s]

  1%|          | 635/100629 [00:32<1:10:21, 23.69it/s]

  1%|          | 638/100629 [00:32<1:10:43, 23.57it/s]

  1%|          | 641/100629 [00:32<1:12:00, 23.14it/s]

  1%|          | 644/100629 [00:32<1:12:00, 23.14it/s]

  1%|          | 647/100629 [00:32<1:12:22, 23.02it/s]

  1%|          | 652/100629 [00:33<57:27, 29.00it/s]

  1%|          | 656/100629 [00:33<53:49, 30.95it/s]

  1%|          | 661/100629 [00:33<50:16, 33.14it/s]

  1%|          | 665/100629 [00:33<51:57, 32.07it/s]

  1%|          | 669/100629 [00:33<1:09:31, 23.96it/s]

  1%|          | 672/100629 [00:33<1:07:26, 24.70it/s]

  1%|          | 675/100629 [00:33<1:04:57, 25.64it/s]

  1%|          | 680/100629 [00:34<54:14, 30.71it/s]

  1%|          | 684/100629 [00:34<53:28, 31.15it/s]

  1%|          | 688/100629 [00:34<56:08, 29.67it/s]

  1%|          | 693/100629 [00:34<48:29, 34.35it/s]

  1%|          | 697/100629 [00:34<53:38, 31.05it/s]

  1%|          | 701/100629 [00:34<52:35, 31.66it/s]

  1%|          | 705/100629 [00:34<50:41, 32.86it/s]

  1%|          | 709/100629 [00:34<52:51, 31.51it/s]

  1%|          | 713/100629 [00:35<54:48, 30.38it/s]

  1%|          | 717/100629 [00:35<1:02:34, 26.61it/s]

  1%|          | 720/100629 [00:35<1:37:36, 17.06it/s]

  1%|          | 723/100629 [00:35<1:46:57, 15.57it/s]

  1%|          | 726/100629 [00:36<1:47:53, 15.43it/s]

  1%|          | 729/100629 [00:36<1:35:07, 17.50it/s]

  1%|          | 732/100629 [00:36<1:35:34, 17.42it/s]

  1%|          | 734/100629 [00:36<1:40:24, 16.58it/s]

  1%|          | 737/100629 [00:36<1:37:04, 17.15it/s]

  1%|          | 740/100629 [00:36<1:27:23, 19.05it/s]

  1%|          | 744/100629 [00:36<1:12:25, 22.99it/s]

  1%|          | 747/100629 [00:37<1:12:32, 22.95it/s]

  1%|          | 750/100629 [00:37<1:22:49, 20.10it/s]

  1%|          | 753/100629 [00:37<1:28:59, 18.70it/s]

  1%|          | 756/100629 [00:37<1:20:20, 20.72it/s]

  1%|          | 760/100629 [00:37<1:08:56, 24.15it/s]

  1%|          | 763/100629 [00:37<1:07:05, 24.81it/s]

  1%|          | 766/100629 [00:37<1:12:09, 23.07it/s]

  1%|          | 770/100629 [00:38<1:02:51, 26.48it/s]

  1%|          | 776/100629 [00:38<50:12, 33.15it/s]

  1%|          | 780/100629 [00:38<49:57, 33.31it/s]

  1%|          | 784/100629 [00:38<59:42, 27.87it/s]

  1%|          | 787/100629 [00:38<1:02:56, 26.44it/s]

  1%|          | 790/100629 [00:38<1:06:27, 25.04it/s]

  1%|          | 793/100629 [00:38<1:06:36, 24.98it/s]

  1%|          | 797/100629 [00:38<1:01:00, 27.27it/s]

  1%|          | 803/100629 [00:39<49:39, 33.50it/s]

  1%|          | 807/100629 [00:39<52:46, 31.53it/s]

  1%|          | 811/100629 [00:39<51:11, 32.50it/s]

  1%|          | 815/100629 [00:39<56:19, 29.53it/s]

  1%|          | 819/100629 [00:39<1:00:11, 27.64it/s]

  1%|          | 824/100629 [00:39<56:55, 29.22it/s]

  1%|          | 827/100629 [00:39<59:04, 28.16it/s]

  1%|          | 830/100629 [00:40<1:02:43, 26.52it/s]

  1%|          | 833/100629 [00:40<1:01:12, 27.17it/s]

  1%|          | 836/100629 [00:40<1:11:31, 23.25it/s]

  1%|          | 839/100629 [00:40<1:09:51, 23.81it/s]

  1%|          | 845/100629 [00:40<52:05, 31.93it/s]

  1%|          | 850/100629 [00:40<46:20, 35.89it/s]

  1%|          | 854/100629 [00:40<48:36, 34.20it/s]

  1%|          | 858/100629 [00:40<52:21, 31.76it/s]

  1%|          | 862/100629 [00:41<1:01:46, 26.92it/s]

  1%|          | 867/100629 [00:41<56:17, 29.54it/s]

  1%|          | 871/100629 [00:41<1:08:39, 24.22it/s]

  1%|          | 874/100629 [00:41<1:34:48, 17.54it/s]

  1%|          | 877/100629 [00:42<1:35:19, 17.44it/s]

  1%|          | 880/100629 [00:42<1:36:38, 17.20it/s]

  1%|          | 884/100629 [00:42<1:25:11, 19.52it/s]

  1%|          | 887/100629 [00:42<1:26:10, 19.29it/s]

  1%|          | 890/100629 [00:42<1:24:08, 19.75it/s]

  1%|          | 893/100629 [00:42<1:26:16, 19.27it/s]

  1%|          | 895/100629 [00:43<1:34:18, 17.63it/s]

  1%|          | 898/100629 [00:43<1:24:12, 19.74it/s]

  1%|          | 901/100629 [00:43<1:21:32, 20.38it/s]

  1%|          | 904/100629 [00:43<1:33:57, 17.69it/s]

  1%|          | 907/100629 [00:43<1:30:42, 18.32it/s]

  1%|          | 910/100629 [00:43<1:26:27, 19.22it/s]

  1%|          | 912/100629 [00:43<1:30:39, 18.33it/s]

  1%|          | 915/100629 [00:44<1:33:20, 17.80it/s]

  1%|          | 920/100629 [00:44<1:14:07, 22.42it/s]

  1%|          | 923/100629 [00:44<1:34:49, 17.52it/s]

  1%|          | 925/100629 [00:44<1:34:00, 17.68it/s]

  1%|          | 927/100629 [00:44<1:50:25, 15.05it/s]

  1%|          | 930/100629 [00:44<1:39:28, 16.70it/s]

  1%|          | 934/100629 [00:45<1:18:49, 21.08it/s]

  1%|          | 938/100629 [00:45<1:05:38, 25.31it/s]

  1%|          | 941/100629 [00:45<1:03:21, 26.23it/s]

  1%|          | 944/100629 [00:45<1:07:33, 24.59it/s]

  1%|          | 947/100629 [00:45<1:09:41, 23.84it/s]

  1%|          | 950/100629 [00:45<1:29:14, 18.61it/s]

  1%|          | 953/100629 [00:45<1:21:57, 20.27it/s]

  1%|          | 957/100629 [00:46<1:10:54, 23.43it/s]

  1%|          | 960/100629 [00:46<1:22:14, 20.20it/s]

  1%|          | 964/100629 [00:46<1:10:28, 23.57it/s]

  1%|          | 967/100629 [00:46<1:25:48, 19.36it/s]

  1%|          | 970/100629 [00:46<1:25:43, 19.38it/s]

  1%|          | 973/100629 [00:46<1:24:17, 19.70it/s]

  1%|          | 976/100629 [00:46<1:18:45, 21.09it/s]

  1%|          | 979/100629 [00:47<1:36:41, 17.18it/s]

  1%|          | 981/100629 [00:47<1:34:15, 17.62it/s]

  1%|          | 985/100629 [00:47<1:17:16, 21.49it/s]

  1%|          | 988/100629 [00:47<1:22:44, 20.07it/s]

  1%|          | 991/100629 [00:47<1:33:12, 17.82it/s]

  1%|          | 993/100629 [00:47<1:31:14, 18.20it/s]

  1%|          | 996/100629 [00:48<1:22:57, 20.02it/s]

  1%|          | 999/100629 [00:48<1:23:42, 19.84it/s]

  1%|          | 1002/100629 [00:48<1:39:43, 16.65it/s]

  1%|          | 1004/100629 [00:48<1:39:36, 16.67it/s]

  1%|          | 1006/100629 [00:48<1:37:37, 17.01it/s]

  1%|          | 1009/100629 [00:48<1:33:13, 17.81it/s]

  1%|          | 1011/100629 [00:48<1:35:56, 17.31it/s]

  1%|          | 1013/100629 [00:49<1:36:53, 17.14it/s]

  1%|          | 1015/100629 [00:49<1:39:15, 16.73it/s]

  1%|          | 1017/100629 [00:49<1:53:13, 14.66it/s]

  1%|          | 1019/100629 [00:49<1:54:06, 14.55it/s]

  1%|          | 1022/100629 [00:49<1:38:05, 16.92it/s]

  1%|          | 1025/100629 [00:49<1:24:16, 19.70it/s]

  1%|          | 1029/100629 [00:49<1:12:10, 23.00it/s]

  1%|          | 1033/100629 [00:50<1:20:06, 20.72it/s]

  1%|          | 1036/100629 [00:50<1:42:03, 16.26it/s]

  1%|          | 1040/100629 [00:50<1:30:01, 18.44it/s]

  1%|          | 1043/100629 [00:50<1:24:07, 19.73it/s]

  1%|          | 1048/100629 [00:50<1:07:34, 24.56it/s]

  1%|          | 1052/100629 [00:50<1:01:06, 27.16it/s]

  1%|          | 1055/100629 [00:51<1:05:24, 25.37it/s]

  1%|          | 1059/100629 [00:51<58:44, 28.25it/s]

  1%|          | 1063/100629 [00:51<55:09, 30.08it/s]

  1%|          | 1067/100629 [00:51<55:37, 29.83it/s]

  1%|          | 1072/100629 [00:51<57:06, 29.05it/s]

  1%|          | 1075/100629 [00:51<1:15:07, 22.09it/s]

  1%|          | 1078/100629 [00:52<1:17:34, 21.39it/s]

  1%|          | 1081/100629 [00:52<1:17:51, 21.31it/s]

  1%|          | 1084/100629 [00:52<1:17:46, 21.33it/s]

  1%|          | 1087/100629 [00:52<1:24:24, 19.66it/s]

  1%|          | 1091/100629 [00:52<1:18:10, 21.22it/s]

  1%|          | 1094/100629 [00:52<1:29:32, 18.53it/s]

  1%|          | 1096/100629 [00:53<1:34:12, 17.61it/s]

  1%|          | 1098/100629 [00:53<1:34:11, 17.61it/s]

  1%|          | 1101/100629 [00:53<1:38:04, 16.91it/s]

  1%|          | 1104/100629 [00:53<1:46:28, 15.58it/s]

  1%|          | 1107/100629 [00:53<1:32:48, 17.87it/s]

  1%|          | 1112/100629 [00:53<1:10:25, 23.55it/s]

  1%|          | 1115/100629 [00:53<1:15:11, 22.06it/s]

  1%|          | 1118/100629 [00:54<1:16:13, 21.76it/s]

  1%|          | 1122/100629 [00:54<1:07:55, 24.42it/s]

  1%|          | 1127/100629 [00:54<57:21, 28.91it/s]

  1%|          | 1131/100629 [00:54<1:01:27, 26.98it/s]

  1%|          | 1134/100629 [00:54<1:08:31, 24.20it/s]

  1%|          | 1137/100629 [00:54<1:10:59, 23.36it/s]

  1%|          | 1140/100629 [00:54<1:10:24, 23.55it/s]

  1%|          | 1144/100629 [00:55<1:00:42, 27.32it/s]

  1%|          | 1148/100629 [00:55<59:53, 27.68it/s]

  1%|          | 1151/100629 [00:55<1:09:01, 24.02it/s]

  1%|          | 1154/100629 [00:55<1:18:36, 21.09it/s]

  1%|          | 1157/100629 [00:55<1:23:15, 19.91it/s]

  1%|          | 1160/100629 [00:55<1:18:00, 21.25it/s]

  1%|          | 1165/100629 [00:55<1:05:02, 25.48it/s]

  1%|          | 1168/100629 [00:56<1:16:59, 21.53it/s]

  1%|          | 1171/100629 [00:56<1:20:34, 20.57it/s]

  1%|          | 1174/100629 [00:56<1:24:10, 19.69it/s]

  1%|          | 1178/100629 [00:56<1:14:15, 22.32it/s]

  1%|          | 1181/100629 [00:56<1:22:48, 20.01it/s]

  1%|          | 1184/100629 [00:56<1:19:41, 20.80it/s]

  1%|          | 1187/100629 [00:57<1:25:05, 19.48it/s]

  1%|          | 1190/100629 [00:57<1:31:48, 18.05it/s]

  1%|          | 1192/100629 [00:57<1:40:28, 16.50it/s]

  1%|          | 1195/100629 [00:57<1:30:42, 18.27it/s]

  1%|          | 1198/100629 [00:57<1:19:54, 20.74it/s]

  1%|          | 1202/100629 [00:57<1:08:04, 24.34it/s]

  1%|          | 1205/100629 [00:58<1:28:53, 18.64it/s]

  1%|          | 1208/100629 [00:58<1:21:03, 20.44it/s]

  1%|          | 1211/100629 [00:58<1:27:32, 18.93it/s]

  1%|          | 1214/100629 [00:58<1:43:38, 15.99it/s]

  1%|          | 1217/100629 [00:58<1:30:32, 18.30it/s]

  1%|          | 1221/100629 [00:58<1:16:08, 21.76it/s]

  1%|          | 1224/100629 [00:59<1:16:35, 21.63it/s]

  1%|          | 1228/100629 [00:59<1:12:45, 22.77it/s]

  1%|          | 1231/100629 [00:59<1:29:28, 18.51it/s]

  1%|          | 1235/100629 [00:59<1:16:46, 21.58it/s]

  1%|          | 1238/100629 [00:59<1:26:38, 19.12it/s]

  1%|          | 1241/100629 [00:59<1:23:54, 19.74it/s]

  1%|          | 1244/100629 [01:00<1:21:31, 20.32it/s]

  1%|          | 1247/100629 [01:00<1:16:13, 21.73it/s]

  1%|          | 1250/100629 [01:00<1:23:06, 19.93it/s]

  1%|          | 1253/100629 [01:00<1:22:30, 20.07it/s]

  1%|          | 1256/100629 [01:00<1:16:38, 21.61it/s]

  1%|▏         | 1259/100629 [01:00<1:15:22, 21.97it/s]

  1%|▏         | 1262/100629 [01:00<1:14:36, 22.20it/s]

  1%|▏         | 1265/100629 [01:00<1:10:23, 23.53it/s]

  1%|▏         | 1268/100629 [01:01<1:20:15, 20.63it/s]

  1%|▏         | 1271/100629 [01:01<1:20:35, 20.55it/s]

  1%|▏         | 1274/100629 [01:01<1:26:25, 19.16it/s]

  1%|▏         | 1276/100629 [01:01<1:32:18, 17.94it/s]

  1%|▏         | 1279/100629 [01:01<1:29:35, 18.48it/s]

  1%|▏         | 1282/100629 [01:01<1:25:12, 19.43it/s]

  1%|▏         | 1286/100629 [01:02<1:11:38, 23.11it/s]

  1%|▏         | 1289/100629 [01:02<1:16:51, 21.54it/s]

  1%|▏         | 1292/100629 [01:02<1:17:36, 21.33it/s]

  1%|▏         | 1295/100629 [01:02<1:20:26, 20.58it/s]

  1%|▏         | 1298/100629 [01:02<1:29:18, 18.54it/s]

  1%|▏         | 1301/100629 [01:02<1:23:26, 19.84it/s]

  1%|▏         | 1304/100629 [01:02<1:20:21, 20.60it/s]

  1%|▏         | 1307/100629 [01:03<1:20:25, 20.58it/s]

  1%|▏         | 1310/100629 [01:03<1:21:31, 20.31it/s]

  1%|▏         | 1313/100629 [01:03<1:13:38, 22.48it/s]

  1%|▏         | 1316/100629 [01:03<1:09:48, 23.71it/s]

  1%|▏         | 1319/100629 [01:03<1:18:42, 21.03it/s]

  1%|▏         | 1322/100629 [01:03<1:18:34, 21.06it/s]

  1%|▏         | 1325/100629 [01:03<1:31:31, 18.08it/s]

  1%|▏         | 1328/100629 [01:04<1:42:30, 16.15it/s]

  1%|▏         | 1330/100629 [01:04<1:39:07, 16.70it/s]

  1%|▏         | 1333/100629 [01:04<1:30:09, 18.36it/s]

  1%|▏         | 1335/100629 [01:04<1:39:18, 16.66it/s]

  1%|▏         | 1338/100629 [01:04<1:37:42, 16.94it/s]

  1%|▏         | 1341/100629 [01:04<1:29:42, 18.45it/s]

  1%|▏         | 1343/100629 [01:05<1:33:04, 17.78it/s]

  1%|▏         | 1348/100629 [01:05<1:07:58, 24.34it/s]

  1%|▏         | 1351/100629 [01:05<1:10:05, 23.61it/s]

  1%|▏         | 1354/100629 [01:05<1:08:47, 24.05it/s]

  1%|▏         | 1357/100629 [01:05<1:06:21, 24.94it/s]

  1%|▏         | 1361/100629 [01:05<1:01:20, 26.97it/s]

  1%|▏         | 1364/100629 [01:05<1:00:16, 27.45it/s]

  1%|▏         | 1367/100629 [01:05<1:05:30, 25.25it/s]

  1%|▏         | 1370/100629 [01:06<1:08:36, 24.11it/s]

  1%|▏         | 1373/100629 [01:06<1:13:08, 22.62it/s]

  1%|▏         | 1377/100629 [01:06<1:10:36, 23.43it/s]

  1%|▏         | 1380/100629 [01:06<1:08:17, 24.22it/s]

  1%|▏         | 1383/100629 [01:06<1:14:29, 22.20it/s]

  1%|▏         | 1386/100629 [01:06<1:19:03, 20.92it/s]

  1%|▏         | 1389/100629 [01:06<1:22:12, 20.12it/s]

  1%|▏         | 1392/100629 [01:07<1:16:52, 21.52it/s]

  1%|▏         | 1395/100629 [01:07<1:28:53, 18.61it/s]

  1%|▏         | 1399/100629 [01:07<1:14:39, 22.15it/s]

  1%|▏         | 1402/100629 [01:07<1:11:20, 23.18it/s]

  1%|▏         | 1405/100629 [01:07<1:10:46, 23.37it/s]

  1%|▏         | 1409/100629 [01:07<1:04:45, 25.53it/s]

  1%|▏         | 1412/100629 [01:07<1:02:19, 26.53it/s]

  1%|▏         | 1415/100629 [01:08<1:08:08, 24.26it/s]

  1%|▏         | 1418/100629 [01:08<1:10:11, 23.56it/s]

  1%|▏         | 1421/100629 [01:08<1:48:05, 15.30it/s]

  1%|▏         | 1423/100629 [01:08<1:44:20, 15.85it/s]

  1%|▏         | 1427/100629 [01:08<1:22:55, 19.94it/s]

  1%|▏         | 1430/100629 [01:08<1:20:51, 20.45it/s]

  1%|▏         | 1433/100629 [01:08<1:14:42, 22.13it/s]

  1%|▏         | 1436/100629 [01:09<1:16:25, 21.63it/s]

  1%|▏         | 1439/100629 [01:09<1:16:01, 21.74it/s]

  1%|▏         | 1443/100629 [01:09<1:04:50, 25.49it/s]

  1%|▏         | 1446/100629 [01:09<1:13:26, 22.51it/s]

  1%|▏         | 1450/100629 [01:09<1:07:12, 24.59it/s]

  1%|▏         | 1453/100629 [01:09<1:05:27, 25.25it/s]

  1%|▏         | 1457/100629 [01:09<58:11, 28.41it/s]

  1%|▏         | 1460/100629 [01:10<1:07:08, 24.61it/s]

  1%|▏         | 1463/100629 [01:10<1:05:35, 25.19it/s]

  1%|▏         | 1467/100629 [01:10<58:49, 28.10it/s]

  1%|▏         | 1472/100629 [01:10<54:38, 30.24it/s]

  1%|▏         | 1476/100629 [01:10<57:49, 28.58it/s]

  1%|▏         | 1479/100629 [01:10<1:09:20, 23.83it/s]

  1%|▏         | 1482/100629 [01:10<1:09:13, 23.87it/s]

  1%|▏         | 1485/100629 [01:11<1:06:40, 24.78it/s]

  1%|▏         | 1488/100629 [01:11<1:07:57, 24.31it/s]

  1%|▏         | 1491/100629 [01:11<1:09:43, 23.70it/s]

  1%|▏         | 1494/100629 [01:11<1:06:40, 24.78it/s]

  1%|▏         | 1498/100629 [01:11<1:04:47, 25.50it/s]

  1%|▏         | 1501/100629 [01:11<1:05:20, 25.29it/s]

  1%|▏         | 1504/100629 [01:11<1:05:12, 25.33it/s]

  1%|▏         | 1508/100629 [01:11<1:05:32, 25.20it/s]

  2%|▏         | 1511/100629 [01:12<1:14:18, 22.23it/s]

  2%|▏         | 1514/100629 [01:12<1:15:23, 21.91it/s]

  2%|▏         | 1518/100629 [01:12<1:11:10, 23.21it/s]

  2%|▏         | 1521/100629 [01:12<1:09:37, 23.73it/s]

  2%|▏         | 1526/100629 [01:12<1:01:34, 26.82it/s]

  2%|▏         | 1529/100629 [01:12<1:20:09, 20.60it/s]

  2%|▏         | 1532/100629 [01:13<1:24:38, 19.51it/s]

  2%|▏         | 1535/100629 [01:13<1:20:15, 20.58it/s]

  2%|▏         | 1538/100629 [01:13<1:15:22, 21.91it/s]

  2%|▏         | 1541/100629 [01:13<1:17:04, 21.43it/s]

  2%|▏         | 1544/100629 [01:13<1:16:51, 21.48it/s]

  2%|▏         | 1548/100629 [01:13<1:05:58, 25.03it/s]

  2%|▏         | 1551/100629 [01:13<1:13:01, 22.61it/s]

  2%|▏         | 1554/100629 [01:14<1:30:55, 18.16it/s]

  2%|▏         | 1557/100629 [01:14<1:26:17, 19.13it/s]

  2%|▏         | 1560/100629 [01:14<1:22:09, 20.10it/s]

  2%|▏         | 1564/100629 [01:14<1:13:12, 22.55it/s]

  2%|▏         | 1567/100629 [01:14<1:17:34, 21.28it/s]

  2%|▏         | 1570/100629 [01:14<1:11:53, 22.97it/s]

  2%|▏         | 1573/100629 [01:14<1:10:54, 23.28it/s]

  2%|▏         | 1576/100629 [01:15<1:09:22, 23.80it/s]

  2%|▏         | 1580/100629 [01:15<1:00:02, 27.49it/s]

  2%|▏         | 1583/100629 [01:15<1:02:59, 26.20it/s]

  2%|▏         | 1586/100629 [01:15<1:23:30, 19.77it/s]

  2%|▏         | 1589/100629 [01:15<1:17:24, 21.32it/s]

  2%|▏         | 1593/100629 [01:15<1:16:39, 21.53it/s]

  2%|▏         | 1596/100629 [01:15<1:14:12, 22.24it/s]

  2%|▏         | 1599/100629 [01:16<1:19:26, 20.78it/s]

  2%|▏         | 1602/100629 [01:16<1:20:25, 20.52it/s]

  2%|▏         | 1606/100629 [01:16<1:09:20, 23.80it/s]

  2%|▏         | 1609/100629 [01:16<1:21:52, 20.15it/s]

  2%|▏         | 1613/100629 [01:16<1:16:12, 21.66it/s]

  2%|▏         | 1617/100629 [01:16<1:06:03, 24.98it/s]

  2%|▏         | 1620/100629 [01:17<1:06:35, 24.78it/s]

  2%|▏         | 1624/100629 [01:17<1:08:59, 23.92it/s]

  2%|▏         | 1627/100629 [01:17<1:11:55, 22.94it/s]

  2%|▏         | 1630/100629 [01:17<1:11:30, 23.07it/s]

  2%|▏         | 1633/100629 [01:17<1:19:41, 20.70it/s]

  2%|▏         | 1636/100629 [01:17<1:32:53, 17.76it/s]

  2%|▏         | 1639/100629 [01:18<1:36:05, 17.17it/s]

  2%|▏         | 1642/100629 [01:18<1:25:59, 19.18it/s]

  2%|▏         | 1645/100629 [01:18<1:18:12, 21.09it/s]

  2%|▏         | 1649/100629 [01:18<1:11:10, 23.18it/s]

  2%|▏         | 1652/100629 [01:18<1:10:04, 23.54it/s]

  2%|▏         | 1655/100629 [01:18<1:14:55, 22.02it/s]

  2%|▏         | 1658/100629 [01:18<1:16:34, 21.54it/s]

  2%|▏         | 1661/100629 [01:18<1:13:27, 22.45it/s]

  2%|▏         | 1665/100629 [01:19<1:03:28, 25.99it/s]

  2%|▏         | 1668/100629 [01:19<1:03:00, 26.18it/s]

  2%|▏         | 1671/100629 [01:19<1:05:23, 25.22it/s]

  2%|▏         | 1674/100629 [01:19<1:03:25, 26.01it/s]

  2%|▏         | 1677/100629 [01:19<1:07:37, 24.39it/s]

  2%|▏         | 1680/100629 [01:19<1:07:19, 24.50it/s]

  2%|▏         | 1683/100629 [01:19<1:18:19, 21.05it/s]

  2%|▏         | 1686/100629 [01:20<1:27:22, 18.87it/s]

  2%|▏         | 1689/100629 [01:20<1:28:15, 18.68it/s]

  2%|▏         | 1694/100629 [01:20<1:10:34, 23.36it/s]

  2%|▏         | 1697/100629 [01:20<1:07:50, 24.31it/s]

  2%|▏         | 1702/100629 [01:20<58:32, 28.17it/s]

  2%|▏         | 1705/100629 [01:20<1:13:08, 22.54it/s]

  2%|▏         | 1708/100629 [01:20<1:09:03, 23.87it/s]

  2%|▏         | 1711/100629 [01:21<1:08:19, 24.13it/s]

  2%|▏         | 1714/100629 [01:21<1:11:04, 23.20it/s]

  2%|▏         | 1717/100629 [01:21<1:11:17, 23.12it/s]

  2%|▏         | 1721/100629 [01:21<1:00:44, 27.14it/s]

  2%|▏         | 1724/100629 [01:21<1:03:37, 25.91it/s]

  2%|▏         | 1727/100629 [01:21<1:11:31, 23.04it/s]

  2%|▏         | 1730/100629 [01:21<1:11:32, 23.04it/s]

  2%|▏         | 1734/100629 [01:22<1:10:14, 23.47it/s]

  2%|▏         | 1737/100629 [01:22<1:13:34, 22.40it/s]

  2%|▏         | 1740/100629 [01:22<1:20:50, 20.39it/s]

  2%|▏         | 1745/100629 [01:22<1:08:36, 24.02it/s]

  2%|▏         | 1748/100629 [01:22<1:14:20, 22.17it/s]

  2%|▏         | 1751/100629 [01:22<1:12:24, 22.76it/s]

  2%|▏         | 1756/100629 [01:22<1:00:33, 27.21it/s]

  2%|▏         | 1759/100629 [01:23<1:03:29, 25.96it/s]

  2%|▏         | 1763/100629 [01:23<57:10, 28.82it/s]

  2%|▏         | 1766/100629 [01:23<1:07:22, 24.45it/s]

  2%|▏         | 1769/100629 [01:23<1:04:26, 25.57it/s]

  2%|▏         | 1772/100629 [01:23<1:06:30, 24.77it/s]

  2%|▏         | 1777/100629 [01:23<56:41, 29.06it/s]

  2%|▏         | 1781/100629 [01:23<55:06, 29.89it/s]

  2%|▏         | 1785/100629 [01:24<1:04:41, 25.46it/s]

  2%|▏         | 1790/100629 [01:24<54:48, 30.06it/s]

  2%|▏         | 1794/100629 [01:24<51:07, 32.22it/s]

  2%|▏         | 1798/100629 [01:24<1:06:14, 24.86it/s]

  2%|▏         | 1801/100629 [01:24<1:07:52, 24.26it/s]

[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (565 > 512). Running this sequence through the model will result in indexing errors

  2%|▏         | 1804/100629 [01:24<1:10:46, 23.27it/s]

  2%|▏         | 1807/100629 [01:24<1:06:57, 24.60it/s]

  2%|▏         | 1810/100629 [01:25<1:13:34, 22.39it/s]

  2%|▏         | 1814/100629 [01:25<1:04:29, 25.54it/s]

  2%|▏         | 1817/100629 [01:25<1:07:11, 24.51it/s]

  2%|▏         | 1820/100629 [01:25<1:06:22, 24.81it/s]

  2%|▏         | 1825/100629 [01:25<55:29, 29.67it/s]

  2%|▏         | 1829/100629 [01:25<1:10:21, 23.41it/s]

  2%|▏         | 1832/100629 [01:25<1:20:59, 20.33it/s]

  2%|▏         | 1835/100629 [01:26<1:28:34, 18.59it/s]

  2%|▏         | 1838/100629 [01:26<1:21:37, 20.17it/s]

  2%|▏         | 1841/100629 [01:26<1:27:12, 18.88it/s]

  2%|▏         | 1844/100629 [01:26<1:29:56, 18.31it/s]

  2%|▏         | 1846/100629 [01:26<1:58:50, 13.85it/s]

  2%|▏         | 1848/100629 [01:27<1:52:29, 14.63it/s]

  2%|▏         | 1850/100629 [01:27<2:04:29, 13.22it/s]

  2%|▏         | 1852/100629 [01:27<2:04:05, 13.27it/s]

  2%|▏         | 1856/100629 [01:27<1:37:30, 16.88it/s]

  2%|▏         | 1859/100629 [01:27<1:28:23, 18.62it/s]

  2%|▏         | 1861/100629 [01:27<1:29:46, 18.34it/s]

  2%|▏         | 1863/100629 [01:27<1:34:41, 17.38it/s]

  2%|▏         | 1865/100629 [01:28<1:31:50, 17.92it/s]

  2%|▏         | 1870/100629 [01:28<1:04:53, 25.36it/s]

  2%|▏         | 1873/100629 [01:28<1:14:37, 22.05it/s]

  2%|▏         | 1876/100629 [01:28<1:10:49, 23.24it/s]

  2%|▏         | 1879/100629 [01:28<1:23:26, 19.73it/s]

  2%|▏         | 1883/100629 [01:28<1:09:25, 23.71it/s]

  2%|▏         | 1887/100629 [01:28<1:20:00, 20.57it/s]

  2%|▏         | 1890/100629 [01:29<1:51:56, 14.70it/s]

  2%|▏         | 1892/100629 [01:29<1:47:21, 15.33it/s]

  2%|▏         | 1894/100629 [01:29<1:51:29, 14.76it/s]

  2%|▏         | 1896/100629 [01:29<1:56:59, 14.07it/s]

  2%|▏         | 1898/100629 [01:29<1:48:09, 15.21it/s]

  2%|▏         | 1900/100629 [01:30<2:03:28, 13.33it/s]

  2%|▏         | 1902/100629 [01:30<2:02:45, 13.40it/s]

  2%|▏         | 1904/100629 [01:30<2:00:45, 13.63it/s]

  2%|▏         | 1907/100629 [01:30<1:46:31, 15.45it/s]

  2%|▏         | 1910/100629 [01:30<1:40:30, 16.37it/s]

  2%|▏         | 1912/100629 [01:30<1:40:29, 16.37it/s]

  2%|▏         | 1914/100629 [01:30<1:45:13, 15.64it/s]

  2%|▏         | 1916/100629 [01:31<2:08:01, 12.85it/s]

  2%|▏         | 1919/100629 [01:31<1:49:46, 14.99it/s]

  2%|▏         | 1921/100629 [01:31<1:43:50, 15.84it/s]

  2%|▏         | 1924/100629 [01:31<1:41:05, 16.27it/s]

  2%|▏         | 1928/100629 [01:31<1:24:50, 19.39it/s]

  2%|▏         | 1930/100629 [01:31<1:54:00, 14.43it/s]

  2%|▏         | 1932/100629 [01:32<1:54:01, 14.43it/s]

  2%|▏         | 1935/100629 [01:32<1:35:33, 17.21it/s]

  2%|▏         | 1938/100629 [01:32<1:27:43, 18.75it/s]

  2%|▏         | 1941/100629 [01:32<1:31:08, 18.05it/s]

  2%|▏         | 1946/100629 [01:32<1:12:39, 22.64it/s]

  2%|▏         | 1949/100629 [01:32<1:25:42, 19.19it/s]

  2%|▏         | 1952/100629 [01:33<1:30:58, 18.08it/s]

  2%|▏         | 1954/100629 [01:33<1:33:25, 17.60it/s]

  2%|▏         | 1957/100629 [01:33<1:25:15, 19.29it/s]

  2%|▏         | 1961/100629 [01:33<1:18:21, 20.99it/s]

  2%|▏         | 1965/100629 [01:33<1:06:33, 24.70it/s]

  2%|▏         | 1969/100629 [01:33<1:05:28, 25.11it/s]

  2%|▏         | 1972/100629 [01:33<1:05:50, 24.97it/s]

  2%|▏         | 1975/100629 [01:34<1:04:23, 25.54it/s]

  2%|▏         | 1978/100629 [01:34<1:23:59, 19.58it/s]

  2%|▏         | 1981/100629 [01:34<1:17:25, 21.23it/s]

  2%|▏         | 1984/100629 [01:34<1:12:52, 22.56it/s]

  2%|▏         | 1987/100629 [01:34<1:16:17, 21.55it/s]

  2%|▏         | 1990/100629 [01:34<1:23:48, 19.61it/s]

  2%|▏         | 1993/100629 [01:35<1:36:01, 17.12it/s]

  2%|▏         | 1997/100629 [01:35<1:22:15, 19.98it/s]

  2%|▏         | 2001/100629 [01:35<1:10:01, 23.48it/s]

  2%|▏         | 2006/100629 [01:35<1:01:03, 26.92it/s]

  2%|▏         | 2009/100629 [01:35<1:20:28, 20.43it/s]

  2%|▏         | 2012/100629 [01:35<1:28:30, 18.57it/s]

  2%|▏         | 2015/100629 [01:36<1:38:17, 16.72it/s]

  2%|▏         | 2017/100629 [01:36<1:54:14, 14.39it/s]

  2%|▏         | 2019/100629 [01:36<1:48:05, 15.21it/s]

  2%|▏         | 2021/100629 [01:36<1:49:27, 15.01it/s]

  2%|▏         | 2023/100629 [01:36<2:19:04, 11.82it/s]

  2%|▏         | 2026/100629 [01:37<2:00:41, 13.62it/s]

  2%|▏         | 2028/100629 [01:37<1:51:30, 14.74it/s]

  2%|▏         | 2030/100629 [01:37<1:44:22, 15.74it/s]

  2%|▏         | 2032/100629 [01:37<2:04:06, 13.24it/s]

  2%|▏         | 2034/100629 [01:37<1:54:43, 14.32it/s]

  2%|▏         | 2036/100629 [01:37<1:46:45, 15.39it/s]

  2%|▏         | 2038/100629 [01:37<1:42:08, 16.09it/s]

  2%|▏         | 2041/100629 [01:37<1:35:52, 17.14it/s]

  2%|▏         | 2043/100629 [01:38<1:33:34, 17.56it/s]

  2%|▏         | 2045/100629 [01:38<1:47:23, 15.30it/s]

  2%|▏         | 2049/100629 [01:38<1:21:13, 20.23it/s]

  2%|▏         | 2053/100629 [01:38<1:09:14, 23.73it/s]

  2%|▏         | 2056/100629 [01:38<1:23:09, 19.76it/s]

  2%|▏         | 2059/100629 [01:38<1:20:07, 20.50it/s]

  2%|▏         | 2062/100629 [01:38<1:14:27, 22.06it/s]

  2%|▏         | 2065/100629 [01:39<1:09:23, 23.67it/s]

  2%|▏         | 2070/100629 [01:39<1:10:21, 23.35it/s]

  2%|▏         | 2073/100629 [01:39<1:13:51, 22.24it/s]

  2%|▏         | 2076/100629 [01:39<1:09:39, 23.58it/s]

  2%|▏         | 2080/100629 [01:39<1:03:45, 25.76it/s]

  2%|▏         | 2084/100629 [01:39<57:46, 28.43it/s]

  2%|▏         | 2087/100629 [01:39<1:01:37, 26.65it/s]

  2%|▏         | 2090/100629 [01:40<1:20:15, 20.46it/s]

  2%|▏         | 2094/100629 [01:40<1:11:17, 23.04it/s]

  2%|▏         | 2097/100629 [01:40<1:10:48, 23.19it/s]

  2%|▏         | 2100/100629 [01:40<1:07:44, 24.24it/s]

  2%|▏         | 2103/100629 [01:40<1:18:14, 20.99it/s]

  2%|▏         | 2106/100629 [01:40<1:35:27, 17.20it/s]

  2%|▏         | 2108/100629 [01:41<1:40:57, 16.27it/s]

  2%|▏         | 2111/100629 [01:41<1:33:19, 17.60it/s]

  2%|▏         | 2114/100629 [01:41<1:26:57, 18.88it/s]

  2%|▏         | 2117/100629 [01:41<1:26:43, 18.93it/s]

  2%|▏         | 2119/100629 [01:41<1:43:42, 15.83it/s]

  2%|▏         | 2122/100629 [01:41<1:33:58, 17.47it/s]

  2%|▏         | 2124/100629 [01:41<1:32:39, 17.72it/s]

  2%|▏         | 2127/100629 [01:42<1:25:23, 19.22it/s]

  2%|▏         | 2129/100629 [01:42<1:31:15, 17.99it/s]

  2%|▏         | 2132/100629 [01:42<1:30:38, 18.11it/s]

  2%|▏         | 2136/100629 [01:42<1:15:02, 21.87it/s]

  2%|▏         | 2139/100629 [01:42<1:24:36, 19.40it/s]

  2%|▏         | 2142/100629 [01:42<1:16:52, 21.35it/s]

  2%|▏         | 2146/100629 [01:42<1:15:04, 21.86it/s]

  2%|▏         | 2149/100629 [01:43<1:15:50, 21.64it/s]

  2%|▏         | 2152/100629 [01:43<1:45:29, 15.56it/s]

  2%|▏         | 2156/100629 [01:43<1:31:46, 17.88it/s]

  2%|▏         | 2160/100629 [01:43<1:17:23, 21.21it/s]

  2%|▏         | 2163/100629 [01:43<1:15:51, 21.64it/s]

  2%|▏         | 2166/100629 [01:44<1:22:26, 19.91it/s]

  2%|▏         | 2171/100629 [01:44<1:15:46, 21.66it/s]

  2%|▏         | 2174/100629 [01:44<1:13:02, 22.47it/s]

  2%|▏         | 2177/100629 [01:44<1:10:30, 23.27it/s]

  2%|▏         | 2180/100629 [01:44<1:08:38, 23.91it/s]

  2%|▏         | 2183/100629 [01:44<1:04:44, 25.34it/s]

  2%|▏         | 2187/100629 [01:44<1:00:35, 27.08it/s]

  2%|▏         | 2190/100629 [01:44<1:03:29, 25.84it/s]

  2%|▏         | 2193/100629 [01:45<1:07:20, 24.36it/s]

  2%|▏         | 2196/100629 [01:45<1:17:22, 21.20it/s]

  2%|▏         | 2199/100629 [01:45<1:25:52, 19.10it/s]

  2%|▏         | 2202/100629 [01:45<1:22:22, 19.91it/s]

  2%|▏         | 2205/100629 [01:45<1:27:05, 18.84it/s]

  2%|▏         | 2208/100629 [01:45<1:24:26, 19.43it/s]

  2%|▏         | 2211/100629 [01:46<1:17:06, 21.27it/s]

  2%|▏         | 2214/100629 [01:46<1:14:36, 21.98it/s]

  2%|▏         | 2217/100629 [01:46<1:16:16, 21.50it/s]

  2%|▏         | 2221/100629 [01:46<1:08:59, 23.77it/s]

  2%|▏         | 2224/100629 [01:46<1:25:46, 19.12it/s]

  2%|▏         | 2227/100629 [01:46<1:30:21, 18.15it/s]

  2%|▏         | 2230/100629 [01:46<1:22:25, 19.90it/s]

  2%|▏         | 2233/100629 [01:47<1:29:32, 18.31it/s]

  2%|▏         | 2236/100629 [01:47<1:29:06, 18.40it/s]

  2%|▏         | 2239/100629 [01:47<1:33:50, 17.47it/s]

  2%|▏         | 2243/100629 [01:47<1:19:05, 20.73it/s]

  2%|▏         | 2246/100629 [01:47<1:16:02, 21.56it/s]

  2%|▏         | 2251/100629 [01:47<1:00:25, 27.13it/s]

  2%|▏         | 2254/100629 [01:48<1:05:26, 25.06it/s]

  2%|▏         | 2257/100629 [01:48<1:09:57, 23.44it/s]

  2%|▏         | 2260/100629 [01:48<1:17:32, 21.14it/s]

  2%|▏         | 2263/100629 [01:48<1:20:50, 20.28it/s]

  2%|▏         | 2266/100629 [01:48<1:29:26, 18.33it/s]

  2%|▏         | 2269/100629 [01:48<1:23:32, 19.62it/s]

  2%|▏         | 2273/100629 [01:48<1:12:25, 22.63it/s]

  2%|▏         | 2276/100629 [01:49<1:17:02, 21.28it/s]

  2%|▏         | 2279/100629 [01:49<1:15:22, 21.75it/s]

  2%|▏         | 2282/100629 [01:49<1:14:11, 22.09it/s]

  2%|▏         | 2285/100629 [01:49<1:29:50, 18.24it/s]

  2%|▏         | 2288/100629 [01:49<1:24:35, 19.38it/s]

  2%|▏         | 2291/100629 [01:49<1:22:29, 19.87it/s]

  2%|▏         | 2294/100629 [01:50<1:16:21, 21.46it/s]

  2%|▏         | 2297/100629 [01:50<1:14:29, 22.00it/s]

  2%|▏         | 2300/100629 [01:50<1:17:35, 21.12it/s]

  2%|▏         | 2304/100629 [01:50<1:06:26, 24.67it/s]

  2%|▏         | 2307/100629 [01:50<1:18:19, 20.92it/s]

  2%|▏         | 2310/100629 [01:50<1:18:32, 20.86it/s]

  2%|▏         | 2313/100629 [01:50<1:25:51, 19.09it/s]

  2%|▏         | 2316/100629 [01:51<1:31:12, 17.96it/s]

  2%|▏         | 2319/100629 [01:51<1:21:29, 20.11it/s]

  2%|▏         | 2322/100629 [01:51<1:21:02, 20.22it/s]

  2%|▏         | 2325/100629 [01:51<1:25:04, 19.26it/s]

  2%|▏         | 2328/100629 [01:51<1:19:27, 20.62it/s]

  2%|▏         | 2331/100629 [01:51<1:14:04, 22.12it/s]

  2%|▏         | 2334/100629 [01:51<1:09:26, 23.59it/s]

  2%|▏         | 2337/100629 [01:52<1:07:55, 24.12it/s]

  2%|▏         | 2340/100629 [01:52<1:05:46, 24.90it/s]

  2%|▏         | 2343/100629 [01:52<1:05:10, 25.13it/s]

  2%|▏         | 2346/100629 [01:52<1:10:03, 23.38it/s]

  2%|▏         | 2351/100629 [01:52<1:00:12, 27.21it/s]

  2%|▏         | 2354/100629 [01:52<59:48, 27.38it/s]

  2%|▏         | 2357/100629 [01:52<1:09:44, 23.49it/s]

  2%|▏         | 2361/100629 [01:52<1:05:38, 24.95it/s]

  2%|▏         | 2364/100629 [01:53<1:06:51, 24.49it/s]

  2%|▏         | 2367/100629 [01:53<1:15:38, 21.65it/s]

  2%|▏         | 2370/100629 [01:53<1:10:17, 23.30it/s]

  2%|▏         | 2373/100629 [01:53<1:18:48, 20.78it/s]

  2%|▏         | 2376/100629 [01:53<1:13:47, 22.19it/s]

  2%|▏         | 2379/100629 [01:53<1:21:47, 20.02it/s]

  2%|▏         | 2382/100629 [01:53<1:16:31, 21.40it/s]

  2%|▏         | 2385/100629 [01:54<1:22:01, 19.96it/s]

  2%|▏         | 2388/100629 [01:54<1:18:55, 20.75it/s]

  2%|▏         | 2391/100629 [01:54<1:13:11, 22.37it/s]

  2%|▏         | 2394/100629 [01:54<1:11:14, 22.98it/s]

  2%|▏         | 2398/100629 [01:54<1:03:31, 25.77it/s]

  2%|▏         | 2401/100629 [01:54<1:14:12, 22.06it/s]

  2%|▏         | 2404/100629 [01:54<1:12:30, 22.58it/s]

  2%|▏         | 2407/100629 [01:55<1:14:06, 22.09it/s]

  2%|▏         | 2410/100629 [01:55<1:11:28, 22.91it/s]

  2%|▏         | 2414/100629 [01:55<1:03:52, 25.63it/s]

  2%|▏         | 2417/100629 [01:55<1:06:44, 24.52it/s]

  2%|▏         | 2420/100629 [01:55<1:07:47, 24.15it/s]

  2%|▏         | 2423/100629 [01:55<1:16:11, 21.48it/s]

  2%|▏         | 2428/100629 [01:55<1:07:46, 24.15it/s]

  2%|▏         | 2431/100629 [01:56<1:08:04, 24.04it/s]

  2%|▏         | 2434/100629 [01:56<1:21:45, 20.02it/s]

  2%|▏         | 2437/100629 [01:56<1:18:26, 20.86it/s]

  2%|▏         | 2440/100629 [01:56<1:19:12, 20.66it/s]

  2%|▏         | 2443/100629 [01:56<1:17:01, 21.25it/s]

  2%|▏         | 2446/100629 [01:56<1:11:13, 22.98it/s]

  2%|▏         | 2450/100629 [01:56<1:02:24, 26.22it/s]

  2%|▏         | 2453/100629 [01:57<1:11:23, 22.92it/s]

  2%|▏         | 2456/100629 [01:57<1:35:52, 17.07it/s]

  2%|▏         | 2459/100629 [01:57<1:27:57, 18.60it/s]

  2%|▏         | 2463/100629 [01:57<1:11:55, 22.75it/s]

  2%|▏         | 2466/100629 [01:57<1:13:34, 22.24it/s]

  2%|▏         | 2471/100629 [01:57<58:17, 28.07it/s]

  2%|▏         | 2475/100629 [01:58<1:10:08, 23.32it/s]

  2%|▏         | 2480/100629 [01:58<1:02:33, 26.15it/s]

  2%|▏         | 2483/100629 [01:58<1:05:29, 24.98it/s]

  2%|▏         | 2486/100629 [01:58<1:15:25, 21.69it/s]

  2%|▏         | 2489/100629 [01:58<1:13:18, 22.31it/s]

  2%|▏         | 2492/100629 [01:58<1:16:25, 21.40it/s]

  2%|▏         | 2497/100629 [01:59<1:08:18, 23.94it/s]

  2%|▏         | 2500/100629 [01:59<1:20:33, 20.30it/s]

  2%|▏         | 2503/100629 [01:59<1:17:42, 21.04it/s]

  2%|▏         | 2506/100629 [01:59<1:22:23, 19.85it/s]

  2%|▏         | 2510/100629 [01:59<1:09:12, 23.63it/s]

  2%|▏         | 2514/100629 [01:59<1:02:45, 26.06it/s]

  3%|▎         | 2518/100629 [01:59<58:22, 28.01it/s]

  3%|▎         | 2523/100629 [02:00<55:01, 29.71it/s]

  3%|▎         | 2528/100629 [02:00<51:58, 31.46it/s]

  3%|▎         | 2532/100629 [02:00<54:25, 30.04it/s]

  3%|▎         | 2536/100629 [02:00<1:03:05, 25.91it/s]

  3%|▎         | 2540/100629 [02:00<1:05:21, 25.01it/s]

  3%|▎         | 2544/100629 [02:00<1:02:48, 26.03it/s]

  3%|▎         | 2547/100629 [02:01<1:11:39, 22.81it/s]

  3%|▎         | 2550/100629 [02:01<1:17:07, 21.19it/s]

  3%|▎         | 2553/100629 [02:01<1:22:38, 19.78it/s]

  3%|▎         | 2556/100629 [02:01<1:24:20, 19.38it/s]

  3%|▎         | 2558/100629 [02:01<1:30:27, 18.07it/s]

  3%|▎         | 2560/100629 [02:01<1:29:26, 18.27it/s]

  3%|▎         | 2564/100629 [02:02<1:37:31, 16.76it/s]

  3%|▎         | 2567/100629 [02:02<1:36:05, 17.01it/s]

  3%|▎         | 2570/100629 [02:02<1:28:01, 18.57it/s]

  3%|▎         | 2573/100629 [02:02<1:23:10, 19.65it/s]

  3%|▎         | 2576/100629 [02:02<1:19:31, 20.55it/s]

  3%|▎         | 2580/100629 [02:02<1:19:12, 20.63it/s]

  3%|▎         | 2584/100629 [02:02<1:11:57, 22.71it/s]

  3%|▎         | 2587/100629 [02:03<1:11:57, 22.71it/s]

  3%|▎         | 2591/100629 [02:03<1:09:09, 23.63it/s]

  3%|▎         | 2595/100629 [02:03<1:00:19, 27.08it/s]

  3%|▎         | 2598/100629 [02:03<1:15:23, 21.67it/s]

  3%|▎         | 2601/100629 [02:03<1:33:21, 17.50it/s]

  3%|▎         | 2604/100629 [02:04<1:45:03, 15.55it/s]

  3%|▎         | 2606/100629 [02:04<1:48:17, 15.09it/s]

  3%|▎         | 2610/100629 [02:04<1:27:11, 18.74it/s]

  3%|▎         | 2613/100629 [02:04<1:20:30, 20.29it/s]

  3%|▎         | 2617/100629 [02:04<1:09:39, 23.45it/s]

  3%|▎         | 2621/100629 [02:04<1:07:01, 24.37it/s]

  3%|▎         | 2624/100629 [02:04<1:07:28, 24.21it/s]

  3%|▎         | 2627/100629 [02:05<1:06:57, 24.39it/s]

  3%|▎         | 2630/100629 [02:05<1:10:54, 23.03it/s]

  3%|▎         | 2633/100629 [02:05<1:09:56, 23.35it/s]

  3%|▎         | 2636/100629 [02:05<1:18:52, 20.71it/s]

  3%|▎         | 2640/100629 [02:05<1:08:03, 23.99it/s]

  3%|▎         | 2643/100629 [02:05<1:07:10, 24.31it/s]

  3%|▎         | 2648/100629 [02:05<54:03, 30.21it/s]

  3%|▎         | 2652/100629 [02:05<58:42, 27.81it/s]

  3%|▎         | 2655/100629 [02:06<1:04:12, 25.43it/s]

  3%|▎         | 2658/100629 [02:06<1:18:40, 20.75it/s]

  3%|▎         | 2662/100629 [02:06<1:07:23, 24.23it/s]

  3%|▎         | 2667/100629 [02:06<56:20, 28.98it/s]

  3%|▎         | 2671/100629 [02:06<56:46, 28.76it/s]

  3%|▎         | 2675/100629 [02:06<1:04:21, 25.37it/s]

  3%|▎         | 2678/100629 [02:07<1:03:01, 25.90it/s]

  3%|▎         | 2681/100629 [02:07<1:15:25, 21.64it/s]

  3%|▎         | 2685/100629 [02:07<1:14:46, 21.83it/s]

  3%|▎         | 2688/100629 [02:07<1:24:07, 19.41it/s]

  3%|▎         | 2691/100629 [02:07<1:24:09, 19.39it/s]

  3%|▎         | 2696/100629 [02:07<1:05:15, 25.01it/s]

  3%|▎         | 2699/100629 [02:08<1:13:49, 22.11it/s]

  3%|▎         | 2702/100629 [02:08<1:13:18, 22.26it/s]

  3%|▎         | 2705/100629 [02:08<1:09:48, 23.38it/s]

  3%|▎         | 2708/100629 [02:08<1:10:38, 23.10it/s]

  3%|▎         | 2711/100629 [02:08<1:06:59, 24.36it/s]

  3%|▎         | 2714/100629 [02:08<1:04:55, 25.14it/s]

  3%|▎         | 2718/100629 [02:08<1:01:21, 26.60it/s]

  3%|▎         | 2722/100629 [02:08<54:37, 29.88it/s]

  3%|▎         | 2726/100629 [02:09<1:00:30, 26.97it/s]

  3%|▎         | 2729/100629 [02:09<1:01:43, 26.43it/s]

  3%|▎         | 2732/100629 [02:09<1:02:17, 26.19it/s]

  3%|▎         | 2735/100629 [02:09<1:09:17, 23.55it/s]

  3%|▎         | 2738/100629 [02:09<1:11:17, 22.89it/s]

  3%|▎         | 2741/100629 [02:09<1:07:45, 24.08it/s]

  3%|▎         | 2744/100629 [02:09<1:07:53, 24.03it/s]

  3%|▎         | 2747/100629 [02:10<1:16:37, 21.29it/s]

  3%|▎         | 2750/100629 [02:10<1:20:29, 20.27it/s]

  3%|▎         | 2753/100629 [02:10<1:19:47, 20.45it/s]

  3%|▎         | 2756/100629 [02:10<1:19:56, 20.40it/s]

  3%|▎         | 2760/100629 [02:10<1:07:29, 24.17it/s]

  3%|▎         | 2763/100629 [02:10<1:10:02, 23.29it/s]

  3%|▎         | 2766/100629 [02:10<1:13:32, 22.18it/s]

  3%|▎         | 2769/100629 [02:11<1:19:21, 20.55it/s]

  3%|▎         | 2772/100629 [02:11<1:21:19, 20.05it/s]

  3%|▎         | 2775/100629 [02:11<1:21:12, 20.08it/s]

  3%|▎         | 2778/100629 [02:11<1:16:06, 21.43it/s]

  3%|▎         | 2781/100629 [02:11<1:17:16, 21.10it/s]

  3%|▎         | 2784/100629 [02:11<1:22:17, 19.82it/s]

  3%|▎         | 2787/100629 [02:11<1:31:02, 17.91it/s]

  3%|▎         | 2789/100629 [02:12<1:31:10, 17.89it/s]

  3%|▎         | 2792/100629 [02:12<1:26:13, 18.91it/s]

  3%|▎         | 2796/100629 [02:12<1:25:28, 19.07it/s]

  3%|▎         | 2800/100629 [02:12<1:36:48, 16.84it/s]

  3%|▎         | 2803/100629 [02:12<1:28:01, 18.52it/s]

  3%|▎         | 2805/100629 [02:12<1:31:10, 17.88it/s]

  3%|▎         | 2808/100629 [02:13<1:22:03, 19.87it/s]

  3%|▎         | 2811/100629 [02:13<1:25:42, 19.02it/s]

  3%|▎         | 2814/100629 [02:13<1:24:05, 19.39it/s]

  3%|▎         | 2817/100629 [02:13<1:24:45, 19.23it/s]

  3%|▎         | 2819/100629 [02:13<1:28:55, 18.33it/s]

  3%|▎         | 2821/100629 [02:13<1:28:03, 18.51it/s]

  3%|▎         | 2824/100629 [02:13<1:18:10, 20.85it/s]

  3%|▎         | 2827/100629 [02:14<1:19:19, 20.55it/s]

  3%|▎         | 2830/100629 [02:14<1:20:56, 20.14it/s]

  3%|▎         | 2833/100629 [02:14<1:20:19, 20.29it/s]

  3%|▎         | 2836/100629 [02:14<1:18:47, 20.69it/s]

  3%|▎         | 2839/100629 [02:14<1:12:38, 22.44it/s]

  3%|▎         | 2842/100629 [02:14<1:19:39, 20.46it/s]

  3%|▎         | 2845/100629 [02:14<1:16:06, 21.42it/s]

  3%|▎         | 2848/100629 [02:15<1:10:28, 23.12it/s]

  3%|▎         | 2851/100629 [02:15<1:08:43, 23.71it/s]

  3%|▎         | 2854/100629 [02:15<1:15:29, 21.58it/s]

  3%|▎         | 2857/100629 [02:15<1:20:26, 20.26it/s]

  3%|▎         | 2860/100629 [02:15<1:19:44, 20.43it/s]

  3%|▎         | 2863/100629 [02:15<1:23:50, 19.43it/s]

  3%|▎         | 2865/100629 [02:16<1:46:33, 15.29it/s]

  3%|▎         | 2867/100629 [02:16<1:40:55, 16.14it/s]

  3%|▎         | 2869/100629 [02:16<1:39:51, 16.32it/s]

  3%|▎         | 2871/100629 [02:16<1:35:41, 17.03it/s]

  3%|▎         | 2874/100629 [02:16<1:23:35, 19.49it/s]

  3%|▎         | 2878/100629 [02:16<1:19:56, 20.38it/s]

  3%|▎         | 2881/100629 [02:16<1:28:55, 18.32it/s]

  3%|▎         | 2883/100629 [02:16<1:32:57, 17.53it/s]

  3%|▎         | 2887/100629 [02:17<1:14:48, 21.78it/s]

  3%|▎         | 2891/100629 [02:17<1:03:43, 25.56it/s]

  3%|▎         | 2894/100629 [02:17<1:13:49, 22.07it/s]

  3%|▎         | 2897/100629 [02:17<1:32:21, 17.63it/s]

  3%|▎         | 2900/100629 [02:17<1:36:14, 16.93it/s]

  3%|▎         | 2903/100629 [02:17<1:31:58, 17.71it/s]

  3%|▎         | 2905/100629 [02:18<1:34:54, 17.16it/s]

  3%|▎         | 2908/100629 [02:18<1:28:41, 18.36it/s]

  3%|▎         | 2910/100629 [02:18<1:28:32, 18.39it/s]

  3%|▎         | 2912/100629 [02:18<1:28:33, 18.39it/s]

  3%|▎         | 2917/100629 [02:18<1:02:32, 26.04it/s]

  3%|▎         | 2920/100629 [02:18<1:10:00, 23.26it/s]

  3%|▎         | 2924/100629 [02:18<1:02:57, 25.86it/s]

  3%|▎         | 2927/100629 [02:19<1:17:14, 21.08it/s]

  3%|▎         | 2930/100629 [02:19<1:30:21, 18.02it/s]

  3%|▎         | 2933/100629 [02:19<1:26:23, 18.85it/s]

  3%|▎         | 2936/100629 [02:19<1:43:14, 15.77it/s]

  3%|▎         | 2939/100629 [02:19<1:37:19, 16.73it/s]

  3%|▎         | 2941/100629 [02:20<1:42:25, 15.90it/s]

  3%|▎         | 2945/100629 [02:20<1:32:03, 17.69it/s]

  3%|▎         | 2947/100629 [02:20<1:45:55, 15.37it/s]

  3%|▎         | 2949/100629 [02:20<1:43:44, 15.69it/s]

  3%|▎         | 2951/100629 [02:20<1:40:57, 16.12it/s]

  3%|▎         | 2953/100629 [02:20<1:43:11, 15.78it/s]

  3%|▎         | 2955/100629 [02:20<1:52:22, 14.49it/s]

  3%|▎         | 2958/100629 [02:21<1:41:50, 15.99it/s]

  3%|▎         | 2962/100629 [02:21<1:22:51, 19.64it/s]

  3%|▎         | 2966/100629 [02:21<1:13:50, 22.04it/s]

  3%|▎         | 2971/100629 [02:21<1:00:54, 26.72it/s]

  3%|▎         | 2974/100629 [02:21<1:07:40, 24.05it/s]

  3%|▎         | 2978/100629 [02:21<1:00:38, 26.84it/s]

  3%|▎         | 2982/100629 [02:21<56:17, 28.91it/s]

  3%|▎         | 2985/100629 [02:21<55:47, 29.17it/s]

  3%|▎         | 2988/100629 [02:22<1:14:24, 21.87it/s]

  3%|▎         | 2991/100629 [02:22<1:09:32, 23.40it/s]

  3%|▎         | 2994/100629 [02:22<1:08:33, 23.74it/s]

  3%|▎         | 2998/100629 [02:22<1:00:12, 27.03it/s]

  3%|▎         | 3001/100629 [02:22<1:04:14, 25.33it/s]

  3%|▎         | 3006/100629 [02:22<57:50, 28.13it/s]

  3%|▎         | 3010/100629 [02:23<1:01:34, 26.42it/s]

  3%|▎         | 3013/100629 [02:23<1:27:13, 18.65it/s]

  3%|▎         | 3016/100629 [02:23<1:33:52, 17.33it/s]

  3%|▎         | 3018/100629 [02:23<1:36:20, 16.89it/s]

  3%|▎         | 3021/100629 [02:23<1:31:14, 17.83it/s]

  3%|▎         | 3023/100629 [02:23<1:40:41, 16.16it/s]

  3%|▎         | 3025/100629 [02:24<1:42:04, 15.94it/s]

  3%|▎         | 3028/100629 [02:24<1:35:36, 17.01it/s]

  3%|▎         | 3031/100629 [02:24<1:25:37, 19.00it/s]

  3%|▎         | 3033/100629 [02:24<1:25:00, 19.13it/s]

  3%|▎         | 3037/100629 [02:24<1:10:29, 23.08it/s]

  3%|▎         | 3040/100629 [02:24<1:14:15, 21.91it/s]

  3%|▎         | 3043/100629 [02:24<1:12:47, 22.34it/s]

  3%|▎         | 3046/100629 [02:24<1:11:02, 22.90it/s]

  3%|▎         | 3049/100629 [02:25<1:12:23, 22.47it/s]

  3%|▎         | 3052/100629 [02:25<1:16:08, 21.36it/s]

  3%|▎         | 3055/100629 [02:25<1:18:19, 20.76it/s]

  3%|▎         | 3060/100629 [02:25<1:07:38, 24.04it/s]

  3%|▎         | 3063/100629 [02:25<1:14:48, 21.74it/s]

  3%|▎         | 3066/100629 [02:25<1:19:35, 20.43it/s]

  3%|▎         | 3069/100629 [02:26<1:12:36, 22.39it/s]

  3%|▎         | 3072/100629 [02:26<1:27:31, 18.58it/s]

  3%|▎         | 3075/100629 [02:26<1:32:32, 17.57it/s]

  3%|▎         | 3078/100629 [02:26<1:30:05, 18.05it/s]

  3%|▎         | 3080/100629 [02:26<1:48:42, 14.95it/s]

  3%|▎         | 3083/100629 [02:26<1:35:47, 16.97it/s]

  3%|▎         | 3085/100629 [02:27<1:51:37, 14.56it/s]

  3%|▎         | 3087/100629 [02:27<1:56:17, 13.98it/s]

  3%|▎         | 3091/100629 [02:27<1:28:05, 18.46it/s]

  3%|▎         | 3094/100629 [02:27<1:25:56, 18.91it/s]

  3%|▎         | 3098/100629 [02:27<1:14:14, 21.89it/s]

  3%|▎         | 3101/100629 [02:27<1:25:24, 19.03it/s]

  3%|▎         | 3106/100629 [02:28<1:08:29, 23.73it/s]

  3%|▎         | 3109/100629 [02:28<1:07:53, 23.94it/s]

  3%|▎         | 3112/100629 [02:28<1:16:11, 21.33it/s]

  3%|▎         | 3115/100629 [02:28<1:20:56, 20.08it/s]

  3%|▎         | 3118/100629 [02:28<1:27:15, 18.63it/s]

  3%|▎         | 3122/100629 [02:28<1:13:50, 22.01it/s]

  3%|▎         | 3125/100629 [02:28<1:10:00, 23.21it/s]

  3%|▎         | 3128/100629 [02:29<1:20:51, 20.10it/s]

  3%|▎         | 3131/100629 [02:29<1:26:26, 18.80it/s]

  3%|▎         | 3134/100629 [02:29<1:29:21, 18.19it/s]

  3%|▎         | 3136/100629 [02:29<1:36:42, 16.80it/s]

  3%|▎         | 3139/100629 [02:29<1:27:55, 18.48it/s]

  3%|▎         | 3143/100629 [02:29<1:15:47, 21.44it/s]

  3%|▎         | 3146/100629 [02:30<1:23:35, 19.44it/s]

  3%|▎         | 3149/100629 [02:30<1:44:29, 15.55it/s]

  3%|▎         | 3151/100629 [02:30<1:40:20, 16.19it/s]

  3%|▎         | 3154/100629 [02:30<1:36:39, 16.81it/s]

  3%|▎         | 3158/100629 [02:30<1:19:11, 20.51it/s]

  3%|▎         | 3161/100629 [02:30<1:17:38, 20.92it/s]

  3%|▎         | 3165/100629 [02:31<1:09:25, 23.40it/s]

  3%|▎         | 3168/100629 [02:31<1:06:22, 24.47it/s]

  3%|▎         | 3171/100629 [02:31<1:03:25, 25.61it/s]

  3%|▎         | 3174/100629 [02:31<1:05:34, 24.77it/s]

  3%|▎         | 3177/100629 [02:31<1:14:12, 21.89it/s]

  3%|▎         | 3180/100629 [02:31<1:20:38, 20.14it/s]

  3%|▎         | 3183/100629 [02:31<1:13:31, 22.09it/s]

  3%|▎         | 3186/100629 [02:32<1:20:19, 20.22it/s]

  3%|▎         | 3189/100629 [02:32<1:30:56, 17.86it/s]

  3%|▎         | 3192/100629 [02:32<1:21:26, 19.94it/s]

  3%|▎         | 3195/100629 [02:32<1:19:18, 20.48it/s]

  3%|▎         | 3198/100629 [02:32<1:18:15, 20.75it/s]

  3%|▎         | 3201/100629 [02:32<1:23:25, 19.46it/s]

  3%|▎         | 3205/100629 [02:32<1:08:55, 23.56it/s]

  3%|▎         | 3208/100629 [02:33<1:06:50, 24.29it/s]

  3%|▎         | 3211/100629 [02:33<1:20:49, 20.09it/s]

  3%|▎         | 3215/100629 [02:33<1:10:47, 22.93it/s]

  3%|▎         | 3218/100629 [02:33<1:37:50, 16.59it/s]

  3%|▎         | 3221/100629 [02:33<1:27:28, 18.56it/s]

  3%|▎         | 3224/100629 [02:33<1:26:26, 18.78it/s]

  3%|▎         | 3227/100629 [02:34<1:28:45, 18.29it/s]

  3%|▎         | 3230/100629 [02:34<1:25:50, 18.91it/s]

  3%|▎         | 3233/100629 [02:34<1:24:20, 19.25it/s]

  3%|▎         | 3236/100629 [02:34<1:26:54, 18.68it/s]

  3%|▎         | 3238/100629 [02:34<1:48:03, 15.02it/s]

  3%|▎         | 3240/100629 [02:34<1:49:31, 14.82it/s]

  3%|▎         | 3242/100629 [02:35<1:44:17, 15.56it/s]

  3%|▎         | 3245/100629 [02:35<1:31:26, 17.75it/s]

  3%|▎         | 3247/100629 [02:35<1:32:08, 17.61it/s]

  3%|▎         | 3249/100629 [02:35<1:34:39, 17.15it/s]

  3%|▎         | 3252/100629 [02:35<1:23:29, 19.44it/s]

  3%|▎         | 3257/100629 [02:35<1:00:49, 26.68it/s]

  3%|▎         | 3260/100629 [02:35<1:16:10, 21.30it/s]

  3%|▎         | 3263/100629 [02:36<1:13:29, 22.08it/s]

  3%|▎         | 3268/100629 [02:36<1:05:47, 24.66it/s]

  3%|▎         | 3271/100629 [02:36<1:08:26, 23.71it/s]

  3%|▎         | 3274/100629 [02:36<1:10:26, 23.03it/s]

  3%|▎         | 3277/100629 [02:36<1:27:23, 18.57it/s]

  3%|▎         | 3281/100629 [02:36<1:19:04, 20.52it/s]

  3%|▎         | 3285/100629 [02:37<1:10:13, 23.10it/s]

  3%|▎         | 3289/100629 [02:37<1:05:00, 24.96it/s]

  3%|▎         | 3292/100629 [02:37<1:08:28, 23.69it/s]

  3%|▎         | 3296/100629 [02:37<1:03:25, 25.58it/s]

  3%|▎         | 3299/100629 [02:37<1:08:18, 23.75it/s]

  3%|▎         | 3302/100629 [02:37<1:05:23, 24.81it/s]

  3%|▎         | 3305/100629 [02:37<1:14:03, 21.90it/s]

  3%|▎         | 3308/100629 [02:37<1:10:11, 23.11it/s]

  3%|▎         | 3311/100629 [02:38<1:09:03, 23.49it/s]

  3%|▎         | 3314/100629 [02:38<1:14:06, 21.89it/s]

  3%|▎         | 3317/100629 [02:38<1:09:23, 23.37it/s]

  3%|▎         | 3320/100629 [02:38<1:15:28, 21.49it/s]

  3%|▎         | 3323/100629 [02:38<1:09:58, 23.18it/s]

  3%|▎         | 3326/100629 [02:38<1:11:56, 22.54it/s]

  3%|▎         | 3330/100629 [02:38<1:04:01, 25.33it/s]

  3%|▎         | 3333/100629 [02:39<1:06:34, 24.36it/s]

  3%|▎         | 3336/100629 [02:39<1:12:00, 22.52it/s]

  3%|▎         | 3339/100629 [02:39<1:11:43, 22.61it/s]

  3%|▎         | 3342/100629 [02:39<1:21:10, 19.97it/s]

  3%|▎         | 3347/100629 [02:39<1:10:07, 23.12it/s]

  3%|▎         | 3350/100629 [02:39<1:07:02, 24.18it/s]

  3%|▎         | 3354/100629 [02:39<1:11:32, 22.66it/s]

  3%|▎         | 3357/100629 [02:40<1:17:47, 20.84it/s]

  3%|▎         | 3360/100629 [02:40<1:12:19, 22.42it/s]

  3%|▎         | 3363/100629 [02:40<1:11:55, 22.54it/s]

  3%|▎         | 3367/100629 [02:40<1:05:24, 24.78it/s]

  3%|▎         | 3371/100629 [02:40<1:01:58, 26.16it/s]

  3%|▎         | 3374/100629 [02:40<1:01:23, 26.40it/s]

  3%|▎         | 3377/100629 [02:40<1:15:49, 21.37it/s]

  3%|▎         | 3380/100629 [02:41<1:10:40, 22.93it/s]

  3%|▎         | 3384/100629 [02:41<1:09:56, 23.17it/s]

  3%|▎         | 3387/100629 [02:41<1:46:40, 15.19it/s]

  3%|▎         | 3389/100629 [02:41<1:58:50, 13.64it/s]

  3%|▎         | 3391/100629 [02:41<1:54:01, 14.21it/s]

  3%|▎         | 3393/100629 [02:42<1:53:42, 14.25it/s]

  3%|▎         | 3397/100629 [02:42<1:25:02, 19.06it/s]

  3%|▎         | 3400/100629 [02:42<1:41:22, 15.98it/s]

  3%|▎         | 3402/100629 [02:42<1:47:05, 15.13it/s]

  3%|▎         | 3404/100629 [02:42<1:42:48, 15.76it/s]

  3%|▎         | 3407/100629 [02:42<1:26:30, 18.73it/s]

  3%|▎         | 3410/100629 [02:43<1:28:09, 18.38it/s]

  3%|▎         | 3413/100629 [02:43<1:18:31, 20.63it/s]

  3%|▎         | 3416/100629 [02:43<1:25:46, 18.89it/s]

  3%|▎         | 3419/100629 [02:43<1:40:06, 16.19it/s]

  3%|▎         | 3421/100629 [02:43<1:43:12, 15.70it/s]

  3%|▎         | 3423/100629 [02:43<1:42:02, 15.88it/s]

  3%|▎         | 3425/100629 [02:43<1:43:19, 15.68it/s]

  3%|▎         | 3429/100629 [02:44<1:25:40, 18.91it/s]

  3%|▎         | 3433/100629 [02:44<1:12:04, 22.48it/s]

  3%|▎         | 3436/100629 [02:44<1:10:37, 22.94it/s]

  3%|▎         | 3439/100629 [02:44<1:13:15, 22.11it/s]

  3%|▎         | 3442/100629 [02:44<1:11:13, 22.74it/s]

  3%|▎         | 3445/100629 [02:44<1:31:16, 17.75it/s]

  3%|▎         | 3447/100629 [02:44<1:29:41, 18.06it/s]

  3%|▎         | 3449/100629 [02:45<1:27:48, 18.44it/s]

  3%|▎         | 3452/100629 [02:45<1:18:34, 20.61it/s]

  3%|▎         | 3455/100629 [02:45<1:19:07, 20.47it/s]

  3%|▎         | 3458/100629 [02:45<1:13:59, 21.89it/s]

  3%|▎         | 3461/100629 [02:45<1:11:48, 22.55it/s]

  3%|▎         | 3464/100629 [02:45<1:13:27, 22.05it/s]

  3%|▎         | 3467/100629 [02:45<1:08:04, 23.79it/s]

  3%|▎         | 3470/100629 [02:45<1:07:47, 23.88it/s]

  3%|▎         | 3473/100629 [02:46<1:03:58, 25.31it/s]

  3%|▎         | 3476/100629 [02:46<1:10:24, 23.00it/s]

  3%|▎         | 3480/100629 [02:46<1:01:00, 26.54it/s]

  3%|▎         | 3483/100629 [02:46<1:11:56, 22.51it/s]

  3%|▎         | 3487/100629 [02:46<1:06:19, 24.41it/s]

  3%|▎         | 3490/100629 [02:46<1:12:08, 22.44it/s]

  3%|▎         | 3493/100629 [02:46<1:17:39, 20.85it/s]

  3%|▎         | 3497/100629 [02:47<1:10:48, 22.86it/s]

  3%|▎         | 3501/100629 [02:47<1:01:44, 26.22it/s]

  3%|▎         | 3504/100629 [02:47<1:05:33, 24.69it/s]

  3%|▎         | 3507/100629 [02:47<1:08:26, 23.65it/s]

  3%|▎         | 3510/100629 [02:47<1:16:25, 21.18it/s]

  3%|▎         | 3513/100629 [02:47<1:12:43, 22.26it/s]

  3%|▎         | 3516/100629 [02:47<1:15:07, 21.55it/s]

  3%|▎         | 3519/100629 [02:48<1:13:04, 22.15it/s]

  3%|▎         | 3522/100629 [02:48<1:20:20, 20.15it/s]

  4%|▎         | 3525/100629 [02:48<1:39:45, 16.22it/s]

  4%|▎         | 3527/100629 [02:48<1:49:24, 14.79it/s]

  4%|▎         | 3530/100629 [02:48<1:35:54, 16.87it/s]

  4%|▎         | 3533/100629 [02:49<1:39:27, 16.27it/s]

  4%|▎         | 3535/100629 [02:49<1:36:41, 16.74it/s]

  4%|▎         | 3538/100629 [02:49<1:24:29, 19.15it/s]

  4%|▎         | 3542/100629 [02:49<1:11:17, 22.70it/s]

  4%|▎         | 3545/100629 [02:49<1:19:16, 20.41it/s]

  4%|▎         | 3548/100629 [02:49<1:21:15, 19.91it/s]

  4%|▎         | 3551/100629 [02:49<1:17:28, 20.88it/s]

  4%|▎         | 3557/100629 [02:50<1:06:46, 24.23it/s]

  4%|▎         | 3561/100629 [02:50<1:05:01, 24.88it/s]

  4%|▎         | 3564/100629 [02:50<1:11:52, 22.51it/s]

  4%|▎         | 3567/100629 [02:50<1:17:26, 20.89it/s]

  4%|▎         | 3570/100629 [02:50<1:14:18, 21.77it/s]

  4%|▎         | 3573/100629 [02:50<1:12:53, 22.19it/s]

  4%|▎         | 3576/100629 [02:51<1:26:45, 18.65it/s]

  4%|▎         | 3581/100629 [02:51<1:08:59, 23.45it/s]

  4%|▎         | 3584/100629 [02:51<1:10:27, 22.95it/s]

  4%|▎         | 3587/100629 [02:51<1:11:02, 22.77it/s]

  4%|▎         | 3590/100629 [02:51<1:16:08, 21.24it/s]

  4%|▎         | 3594/100629 [02:51<1:04:59, 24.89it/s]

  4%|▎         | 3598/100629 [02:51<58:19, 27.73it/s]

  4%|▎         | 3601/100629 [02:51<1:06:05, 24.47it/s]

  4%|▎         | 3605/100629 [02:52<1:02:11, 26.00it/s]

  4%|▎         | 3608/100629 [02:52<1:12:14, 22.38it/s]

  4%|▎         | 3611/100629 [02:52<1:08:38, 23.56it/s]

  4%|▎         | 3614/100629 [02:52<1:10:55, 22.80it/s]

  4%|▎         | 3617/100629 [02:52<1:14:49, 21.61it/s]

  4%|▎         | 3620/100629 [02:52<1:13:57, 21.86it/s]

  4%|▎         | 3623/100629 [02:53<1:27:06, 18.56it/s]

  4%|▎         | 3626/100629 [02:53<1:18:04, 20.71it/s]

  4%|▎         | 3629/100629 [02:53<1:25:06, 19.00it/s]

  4%|▎         | 3632/100629 [02:53<1:26:06, 18.77it/s]

  4%|▎         | 3635/100629 [02:53<1:22:34, 19.58it/s]

  4%|▎         | 3638/100629 [02:53<1:17:50, 20.77it/s]

  4%|▎         | 3641/100629 [02:54<1:37:06, 16.65it/s]

  4%|▎         | 3644/100629 [02:54<1:26:32, 18.68it/s]

  4%|▎         | 3647/100629 [02:54<1:20:57, 19.96it/s]

  4%|▎         | 3650/100629 [02:54<1:28:44, 18.21it/s]

  4%|▎         | 3653/100629 [02:54<1:23:30, 19.36it/s]

  4%|▎         | 3657/100629 [02:54<1:17:36, 20.83it/s]

  4%|▎         | 3660/100629 [02:54<1:24:47, 19.06it/s]

  4%|▎         | 3662/100629 [02:55<1:30:27, 17.87it/s]

  4%|▎         | 3664/100629 [02:55<1:29:12, 18.12it/s]

  4%|▎         | 3667/100629 [02:55<1:20:41, 20.03it/s]

  4%|▎         | 3670/100629 [02:55<1:22:16, 19.64it/s]

  4%|▎         | 3673/100629 [02:55<1:27:11, 18.53it/s]

  4%|▎         | 3678/100629 [02:55<1:07:46, 23.84it/s]

  4%|▎         | 3681/100629 [02:55<1:06:01, 24.47it/s]

  4%|▎         | 3684/100629 [02:56<1:12:52, 22.17it/s]

  4%|▎         | 3687/100629 [02:56<1:31:12, 17.71it/s]

  4%|▎         | 3690/100629 [02:56<1:20:51, 19.98it/s]

  4%|▎         | 3693/100629 [02:56<1:24:21, 19.15it/s]

  4%|▎         | 3696/100629 [02:56<1:30:46, 17.80it/s]

  4%|▎         | 3700/100629 [02:56<1:15:39, 21.35it/s]

  4%|▎         | 3703/100629 [02:57<1:14:17, 21.75it/s]

  4%|▎         | 3706/100629 [02:57<1:21:09, 19.90it/s]

  4%|▎         | 3709/100629 [02:57<1:22:18, 19.63it/s]

  4%|▎         | 3712/100629 [02:57<1:43:07, 15.66it/s]

  4%|▎         | 3714/100629 [02:57<1:46:40, 15.14it/s]

  4%|▎         | 3716/100629 [02:58<1:56:56, 13.81it/s]

  4%|▎         | 3719/100629 [02:58<1:39:50, 16.18it/s]

  4%|▎         | 3722/100629 [02:58<1:28:14, 18.30it/s]

  4%|▎         | 3724/100629 [02:58<1:26:44, 18.62it/s]

  4%|▎         | 3727/100629 [02:58<1:27:03, 18.55it/s]

  4%|▎         | 3730/100629 [02:58<1:17:57, 20.71it/s]

  4%|▎         | 3733/100629 [02:58<1:13:32, 21.96it/s]

  4%|▎         | 3737/100629 [02:58<1:09:32, 23.22it/s]

  4%|▎         | 3740/100629 [02:59<1:05:16, 24.74it/s]

  4%|▎         | 3745/100629 [02:59<54:46, 29.47it/s]

  4%|▎         | 3749/100629 [02:59<1:13:36, 21.93it/s]

  4%|▎         | 3752/100629 [02:59<1:08:40, 23.51it/s]

  4%|▎         | 3755/100629 [02:59<1:12:59, 22.12it/s]

  4%|▎         | 3758/100629 [02:59<1:08:37, 23.53it/s]

  4%|▎         | 3761/100629 [02:59<1:18:35, 20.54it/s]

  4%|▎         | 3764/100629 [03:00<1:13:55, 21.84it/s]

  4%|▎         | 3767/100629 [03:00<1:13:31, 21.96it/s]

  4%|▎         | 3771/100629 [03:00<1:03:38, 25.37it/s]

  4%|▍         | 3774/100629 [03:00<1:04:12, 25.14it/s]

  4%|▍         | 3777/100629 [03:00<1:05:16, 24.73it/s]

  4%|▍         | 3780/100629 [03:00<1:05:19, 24.71it/s]

  4%|▍         | 3783/100629 [03:00<1:03:43, 25.33it/s]

  4%|▍         | 3787/100629 [03:00<1:03:44, 25.32it/s]

  4%|▍         | 3790/100629 [03:01<1:21:18, 19.85it/s]

  4%|▍         | 3793/100629 [03:01<1:15:44, 21.31it/s]

  4%|▍         | 3796/100629 [03:01<1:09:34, 23.20it/s]

  4%|▍         | 3799/100629 [03:01<1:16:31, 21.09it/s]

  4%|▍         | 3802/100629 [03:01<1:20:41, 20.00it/s]

  4%|▍         | 3805/100629 [03:01<1:17:32, 20.81it/s]

  4%|▍         | 3810/100629 [03:02<1:03:43, 25.32it/s]

  4%|▍         | 3817/100629 [03:02<46:30, 34.69it/s]

  4%|▍         | 3821/100629 [03:02<53:47, 30.00it/s]

  4%|▍         | 3825/100629 [03:02<58:42, 27.48it/s]

  4%|▍         | 3828/100629 [03:02<1:09:43, 23.14it/s]

  4%|▍         | 3831/100629 [03:02<1:16:39, 21.05it/s]

  4%|▍         | 3834/100629 [03:03<1:18:27, 20.56it/s]

  4%|▍         | 3837/100629 [03:03<1:28:59, 18.13it/s]

  4%|▍         | 3840/100629 [03:03<1:26:23, 18.67it/s]

  4%|▍         | 3843/100629 [03:03<1:25:53, 18.78it/s]

  4%|▍         | 3845/100629 [03:03<1:25:00, 18.98it/s]

  4%|▍         | 3847/100629 [03:03<1:24:54, 19.00it/s]

  4%|▍         | 3849/100629 [03:03<1:24:05, 19.18it/s]

  4%|▍         | 3852/100629 [03:04<1:19:55, 20.18it/s]

  4%|▍         | 3855/100629 [03:04<1:12:24, 22.28it/s]

  4%|▍         | 3858/100629 [03:04<1:09:55, 23.06it/s]

  4%|▍         | 3861/100629 [03:04<1:23:05, 19.41it/s]

  4%|▍         | 3864/100629 [03:04<1:36:05, 16.78it/s]

  4%|▍         | 3867/100629 [03:04<1:27:38, 18.40it/s]

  4%|▍         | 3870/100629 [03:04<1:19:06, 20.39it/s]

  4%|▍         | 3874/100629 [03:05<1:13:41, 21.89it/s]

  4%|▍         | 3878/100629 [03:05<1:11:37, 22.51it/s]

  4%|▍         | 3881/100629 [03:05<1:13:00, 22.09it/s]

  4%|▍         | 3884/100629 [03:05<1:07:39, 23.83it/s]

  4%|▍         | 3887/100629 [03:05<1:07:41, 23.82it/s]

  4%|▍         | 3891/100629 [03:05<59:18, 27.18it/s]

  4%|▍         | 3894/100629 [03:05<1:03:13, 25.50it/s]

  4%|▍         | 3897/100629 [03:05<1:01:31, 26.20it/s]

  4%|▍         | 3900/100629 [03:06<1:08:10, 23.65it/s]

  4%|▍         | 3903/100629 [03:06<1:16:16, 21.14it/s]

  4%|▍         | 3906/100629 [03:06<1:16:23, 21.10it/s]

  4%|▍         | 3909/100629 [03:06<1:21:17, 19.83it/s]

  4%|▍         | 3912/100629 [03:06<1:17:09, 20.89it/s]

  4%|▍         | 3915/100629 [03:06<1:18:15, 20.60it/s]

  4%|▍         | 3918/100629 [03:07<1:19:32, 20.27it/s]

  4%|▍         | 3921/100629 [03:07<1:21:54, 19.68it/s]

  4%|▍         | 3924/100629 [03:07<1:18:29, 20.53it/s]

  4%|▍         | 3927/100629 [03:07<1:22:16, 19.59it/s]

  4%|▍         | 3931/100629 [03:07<1:10:36, 22.82it/s]

  4%|▍         | 3934/100629 [03:07<1:11:14, 22.62it/s]

  4%|▍         | 3938/100629 [03:07<1:07:56, 23.72it/s]

  4%|▍         | 3941/100629 [03:08<1:11:58, 22.39it/s]

  4%|▍         | 3944/100629 [03:08<1:10:21, 22.90it/s]

  4%|▍         | 3947/100629 [03:08<1:08:55, 23.38it/s]

  4%|▍         | 3950/100629 [03:08<1:09:34, 23.16it/s]

  4%|▍         | 3953/100629 [03:08<1:09:33, 23.16it/s]

  4%|▍         | 3956/100629 [03:08<1:18:45, 20.46it/s]

  4%|▍         | 3959/100629 [03:08<1:15:19, 21.39it/s]

  4%|▍         | 3962/100629 [03:09<1:18:45, 20.46it/s]

  4%|▍         | 3966/100629 [03:09<1:06:35, 24.20it/s]

  4%|▍         | 3969/100629 [03:09<1:11:38, 22.48it/s]

  4%|▍         | 3972/100629 [03:09<1:16:50, 20.97it/s]

  4%|▍         | 3975/100629 [03:09<1:20:15, 20.07it/s]

  4%|▍         | 3978/100629 [03:09<1:23:06, 19.38it/s]

  4%|▍         | 3980/100629 [03:09<1:25:11, 18.91it/s]

  4%|▍         | 3983/100629 [03:10<1:24:34, 19.04it/s]

  4%|▍         | 3986/100629 [03:10<1:17:01, 20.91it/s]

  4%|▍         | 3989/100629 [03:10<1:21:16, 19.82it/s]

  4%|▍         | 3992/100629 [03:10<1:30:05, 17.88it/s]

  4%|▍         | 3995/100629 [03:10<1:19:11, 20.34it/s]

  4%|▍         | 3998/100629 [03:10<1:26:28, 18.62it/s]

  4%|▍         | 4001/100629 [03:11<1:31:03, 17.69it/s]

  4%|▍         | 4003/100629 [03:11<1:33:56, 17.14it/s]

  4%|▍         | 4005/100629 [03:11<1:36:20, 16.72it/s]

  4%|▍         | 4007/100629 [03:11<1:36:55, 16.62it/s]

  4%|▍         | 4009/100629 [03:11<1:33:25, 17.24it/s]

  4%|▍         | 4011/100629 [03:11<1:36:49, 16.63it/s]

  4%|▍         | 4013/100629 [03:11<1:34:55, 16.96it/s]

  4%|▍         | 4015/100629 [03:11<1:50:20, 14.59it/s]

  4%|▍         | 4018/100629 [03:12<1:40:22, 16.04it/s]

  4%|▍         | 4022/100629 [03:12<1:27:56, 18.31it/s]

  4%|▍         | 4025/100629 [03:12<1:19:39, 20.21it/s]

  4%|▍         | 4029/100629 [03:12<1:09:51, 23.05it/s]

  4%|▍         | 4032/100629 [03:12<1:10:54, 22.70it/s]

  4%|▍         | 4035/100629 [03:12<1:25:47, 18.77it/s]

  4%|▍         | 4038/100629 [03:13<1:27:12, 18.46it/s]

  4%|▍         | 4040/100629 [03:13<1:31:10, 17.66it/s]

  4%|▍         | 4043/100629 [03:13<1:23:43, 19.23it/s]

  4%|▍         | 4045/100629 [03:13<1:30:22, 17.81it/s]

  4%|▍         | 4048/100629 [03:13<1:24:49, 18.98it/s]

  4%|▍         | 4050/100629 [03:13<1:26:08, 18.69it/s]

  4%|▍         | 4053/100629 [03:13<1:23:31, 19.27it/s]

  4%|▍         | 4055/100629 [03:14<1:26:51, 18.53it/s]

  4%|▍         | 4059/100629 [03:14<1:10:57, 22.68it/s]

  4%|▍         | 4062/100629 [03:14<1:15:04, 21.44it/s]

  4%|▍         | 4065/100629 [03:14<1:16:04, 21.16it/s]

  4%|▍         | 4068/100629 [03:14<1:16:45, 20.97it/s]

  4%|▍         | 4071/100629 [03:14<1:12:27, 22.21it/s]

  4%|▍         | 4074/100629 [03:14<1:14:50, 21.50it/s]

  4%|▍         | 4077/100629 [03:15<1:20:52, 19.90it/s]

  4%|▍         | 4081/100629 [03:15<1:09:16, 23.23it/s]

  4%|▍         | 4084/100629 [03:15<1:18:26, 20.51it/s]

  4%|▍         | 4087/100629 [03:15<1:12:27, 22.21it/s]

  4%|▍         | 4090/100629 [03:15<1:18:45, 20.43it/s]

  4%|▍         | 4093/100629 [03:15<1:12:45, 22.11it/s]

  4%|▍         | 4096/100629 [03:15<1:13:38, 21.85it/s]

  4%|▍         | 4101/100629 [03:16<1:05:22, 24.61it/s]

  4%|▍         | 4104/100629 [03:16<1:05:15, 24.65it/s]

  4%|▍         | 4107/100629 [03:16<1:09:07, 23.27it/s]

  4%|▍         | 4110/100629 [03:16<1:13:46, 21.80it/s]

  4%|▍         | 4113/100629 [03:16<1:15:05, 21.42it/s]

  4%|▍         | 4116/100629 [03:16<1:09:04, 23.29it/s]

  4%|▍         | 4119/100629 [03:16<1:14:34, 21.57it/s]

  4%|▍         | 4123/100629 [03:17<1:05:36, 24.51it/s]

  4%|▍         | 4127/100629 [03:17<1:00:48, 26.45it/s]

  4%|▍         | 4130/100629 [03:17<1:15:33, 21.28it/s]

  4%|▍         | 4134/100629 [03:17<1:05:52, 24.41it/s]

  4%|▍         | 4137/100629 [03:17<1:16:03, 21.14it/s]

  4%|▍         | 4140/100629 [03:17<1:18:58, 20.36it/s]

  4%|▍         | 4143/100629 [03:17<1:16:15, 21.09it/s]

  4%|▍         | 4146/100629 [03:18<1:12:24, 22.21it/s]

  4%|▍         | 4149/100629 [03:18<1:10:21, 22.85it/s]

  4%|▍         | 4153/100629 [03:18<1:03:34, 25.29it/s]

  4%|▍         | 4158/100629 [03:18<53:52, 29.84it/s]

  4%|▍         | 4162/100629 [03:18<54:04, 29.73it/s]

  4%|▍         | 4166/100629 [03:18<59:13, 27.14it/s]

  4%|▍         | 4169/100629 [03:18<1:00:08, 26.73it/s]

  4%|▍         | 4172/100629 [03:19<1:15:27, 21.31it/s]

  4%|▍         | 4175/100629 [03:19<1:10:05, 22.93it/s]

  4%|▍         | 4179/100629 [03:19<1:06:32, 24.16it/s]

  4%|▍         | 4182/100629 [03:19<1:09:22, 23.17it/s]

  4%|▍         | 4185/100629 [03:19<1:15:29, 21.29it/s]

  4%|▍         | 4188/100629 [03:19<1:09:21, 23.17it/s]

  4%|▍         | 4192/100629 [03:19<59:49, 26.87it/s]

  4%|▍         | 4195/100629 [03:19<1:00:58, 26.36it/s]

  4%|▍         | 4199/100629 [03:20<1:00:17, 26.66it/s]

  4%|▍         | 4203/100629 [03:20<1:01:45, 26.02it/s]

  4%|▍         | 4206/100629 [03:20<1:07:48, 23.70it/s]

  4%|▍         | 4209/100629 [03:20<1:04:23, 24.95it/s]

  4%|▍         | 4212/100629 [03:20<1:03:08, 25.45it/s]

  4%|▍         | 4215/100629 [03:20<1:05:32, 24.52it/s]

  4%|▍         | 4218/100629 [03:20<1:08:20, 23.51it/s]

  4%|▍         | 4221/100629 [03:21<1:07:31, 23.79it/s]

  4%|▍         | 4224/100629 [03:21<1:05:37, 24.48it/s]

  4%|▍         | 4227/100629 [03:21<1:16:30, 21.00it/s]

  4%|▍         | 4231/100629 [03:21<1:10:44, 22.71it/s]

  4%|▍         | 4236/100629 [03:21<1:07:43, 23.72it/s]

  4%|▍         | 4239/100629 [03:21<1:05:40, 24.46it/s]

  4%|▍         | 4242/100629 [03:21<1:08:37, 23.41it/s]

  4%|▍         | 4245/100629 [03:22<1:08:59, 23.28it/s]

  4%|▍         | 4248/100629 [03:22<1:07:05, 23.94it/s]

  4%|▍         | 4251/100629 [03:22<1:09:23, 23.15it/s]

  4%|▍         | 4254/100629 [03:22<1:05:33, 24.50it/s]

  4%|▍         | 4258/100629 [03:22<1:00:13, 26.67it/s]

  4%|▍         | 4261/100629 [03:22<1:09:41, 23.05it/s]

  4%|▍         | 4264/100629 [03:22<1:12:55, 22.03it/s]

  4%|▍         | 4267/100629 [03:23<1:19:13, 20.27it/s]

  4%|▍         | 4270/100629 [03:23<1:19:36, 20.17it/s]

  4%|▍         | 4273/100629 [03:23<1:22:21, 19.50it/s]

  4%|▍         | 4276/100629 [03:23<1:20:52, 19.86it/s]

  4%|▍         | 4279/100629 [03:23<1:24:34, 18.99it/s]

  4%|▍         | 4281/100629 [03:23<1:25:32, 18.77it/s]

  4%|▍         | 4283/100629 [03:24<1:36:53, 16.57it/s]

  4%|▍         | 4286/100629 [03:24<1:26:45, 18.51it/s]

  4%|▍         | 4288/100629 [03:24<1:36:33, 16.63it/s]

  4%|▍         | 4292/100629 [03:24<1:21:24, 19.72it/s]

  4%|▍         | 4296/100629 [03:24<1:09:47, 23.00it/s]

  4%|▍         | 4299/100629 [03:24<1:12:57, 22.00it/s]

  4%|▍         | 4302/100629 [03:24<1:14:50, 21.45it/s]

  4%|▍         | 4305/100629 [03:25<1:20:42, 19.89it/s]

  4%|▍         | 4308/100629 [03:25<1:15:17, 21.32it/s]

  4%|▍         | 4311/100629 [03:25<1:15:27, 21.27it/s]

  4%|▍         | 4314/100629 [03:25<1:18:11, 20.53it/s]

  4%|▍         | 4317/100629 [03:25<1:15:15, 21.33it/s]

  4%|▍         | 4320/100629 [03:25<1:09:32, 23.08it/s]

  4%|▍         | 4324/100629 [03:25<1:00:27, 26.55it/s]

  4%|▍         | 4328/100629 [03:25<1:02:30, 25.68it/s]

  4%|▍         | 4332/100629 [03:26<55:57, 28.68it/s]

  4%|▍         | 4336/100629 [03:26<53:12, 30.16it/s]

  4%|▍         | 4340/100629 [03:26<56:41, 28.31it/s]

  4%|▍         | 4344/100629 [03:26<53:11, 30.17it/s]

  4%|▍         | 4348/100629 [03:26<53:18, 30.10it/s]

  4%|▍         | 4352/100629 [03:26<58:14, 27.55it/s]

  4%|▍         | 4356/100629 [03:26<55:57, 28.67it/s]

  4%|▍         | 4359/100629 [03:27<56:04, 28.61it/s]

  4%|▍         | 4362/100629 [03:27<59:50, 26.81it/s]

  4%|▍         | 4365/100629 [03:27<1:14:33, 21.52it/s]

  4%|▍         | 4368/100629 [03:27<1:19:13, 20.25it/s]

  4%|▍         | 4371/100629 [03:27<1:22:00, 19.56it/s]

  4%|▍         | 4374/100629 [03:27<1:29:05, 18.01it/s]

  4%|▍         | 4376/100629 [03:28<1:31:43, 17.49it/s]

  4%|▍         | 4378/100629 [03:28<1:31:52, 17.46it/s]

  4%|▍         | 4380/100629 [03:28<1:41:44, 15.77it/s]

  4%|▍         | 4382/100629 [03:28<1:38:03, 16.36it/s]

  4%|▍         | 4386/100629 [03:28<1:13:34, 21.80it/s]

  4%|▍         | 4389/100629 [03:28<1:09:52, 22.95it/s]

  4%|▍         | 4393/100629 [03:28<59:08, 27.12it/s]

  4%|▍         | 4396/100629 [03:28<1:04:09, 25.00it/s]

  4%|▍         | 4399/100629 [03:29<1:09:17, 23.15it/s]

  4%|▍         | 4402/100629 [03:29<1:08:36, 23.38it/s]

  4%|▍         | 4405/100629 [03:29<1:17:44, 20.63it/s]

  4%|▍         | 4408/100629 [03:29<1:19:43, 20.11it/s]

  4%|▍         | 4411/100629 [03:29<1:19:29, 20.17it/s]

  4%|▍         | 4414/100629 [03:29<1:26:55, 18.45it/s]

  4%|▍         | 4417/100629 [03:29<1:20:01, 20.04it/s]

  4%|▍         | 4420/100629 [03:30<1:23:46, 19.14it/s]

  4%|▍         | 4423/100629 [03:30<1:21:57, 19.56it/s]

  4%|▍         | 4427/100629 [03:30<1:08:01, 23.57it/s]

  4%|▍         | 4432/100629 [03:30<54:59, 29.15it/s]

  4%|▍         | 4436/100629 [03:30<54:14, 29.55it/s]

  4%|▍         | 4440/100629 [03:30<59:22, 27.00it/s]

  4%|▍         | 4443/100629 [03:30<1:02:37, 25.60it/s]

  4%|▍         | 4446/100629 [03:31<1:10:21, 22.78it/s]

  4%|▍         | 4449/100629 [03:31<1:21:35, 19.65it/s]

  4%|▍         | 4452/100629 [03:31<1:25:23, 18.77it/s]

  4%|▍         | 4455/100629 [03:31<1:17:12, 20.76it/s]

  4%|▍         | 4458/100629 [03:31<1:26:18, 18.57it/s]

  4%|▍         | 4461/100629 [03:31<1:26:24, 18.55it/s]

  4%|▍         | 4463/100629 [03:32<1:25:58, 18.64it/s]

  4%|▍         | 4467/100629 [03:32<1:09:50, 22.95it/s]

  4%|▍         | 4470/100629 [03:32<1:23:12, 19.26it/s]

  4%|▍         | 4473/100629 [03:32<1:17:28, 20.68it/s]

  4%|▍         | 4476/100629 [03:32<1:27:25, 18.33it/s]

  4%|▍         | 4479/100629 [03:32<1:20:42, 19.86it/s]

  4%|▍         | 4482/100629 [03:32<1:21:17, 19.71it/s]

  4%|▍         | 4485/100629 [03:33<1:24:28, 18.97it/s]

  4%|▍         | 4487/100629 [03:33<1:32:05, 17.40it/s]

  4%|▍         | 4489/100629 [03:33<1:35:11, 16.83it/s]

  4%|▍         | 4492/100629 [03:33<1:23:03, 19.29it/s]

  4%|▍         | 4497/100629 [03:33<1:05:14, 24.56it/s]

  4%|▍         | 4502/100629 [03:33<59:40, 26.85it/s]

  4%|▍         | 4505/100629 [03:34<1:14:30, 21.50it/s]

  4%|▍         | 4508/100629 [03:34<1:11:00, 22.56it/s]

  4%|▍         | 4511/100629 [03:34<1:12:21, 22.14it/s]

  4%|▍         | 4515/100629 [03:34<1:05:23, 24.50it/s]

  4%|▍         | 4518/100629 [03:34<1:03:27, 25.24it/s]

  4%|▍         | 4521/100629 [03:34<1:07:42, 23.66it/s]

  4%|▍         | 4524/100629 [03:34<1:23:50, 19.11it/s]

  4%|▍         | 4527/100629 [03:35<1:44:50, 15.28it/s]

  5%|▍         | 4530/100629 [03:35<1:30:30, 17.70it/s]

  5%|▍         | 4533/100629 [03:35<1:22:59, 19.30it/s]

  5%|▍         | 4537/100629 [03:35<1:15:03, 21.34it/s]

  5%|▍         | 4540/100629 [03:35<1:12:30, 22.08it/s]

  5%|▍         | 4543/100629 [03:35<1:09:08, 23.16it/s]

  5%|▍         | 4546/100629 [03:35<1:07:58, 23.56it/s]

  5%|▍         | 4551/100629 [03:36<55:54, 28.64it/s]

  5%|▍         | 4554/100629 [03:36<1:00:49, 26.32it/s]

  5%|▍         | 4557/100629 [03:36<1:00:57, 26.27it/s]

  5%|▍         | 4561/100629 [03:36<56:00, 28.59it/s]

  5%|▍         | 4564/100629 [03:36<55:37, 28.79it/s]

  5%|▍         | 4567/100629 [03:36<1:03:17, 25.30it/s]

  5%|▍         | 4571/100629 [03:36<57:12, 27.98it/s]

  5%|▍         | 4578/100629 [03:37<47:27, 33.73it/s]

  5%|▍         | 4582/100629 [03:37<1:01:39, 25.96it/s]

  5%|▍         | 4585/100629 [03:37<1:20:45, 19.82it/s]

  5%|▍         | 4589/100629 [03:37<1:13:41, 21.72it/s]

  5%|▍         | 4592/100629 [03:37<1:11:40, 22.33it/s]

  5%|▍         | 4595/100629 [03:37<1:20:03, 19.99it/s]

  5%|▍         | 4598/100629 [03:38<1:25:14, 18.78it/s]

  5%|▍         | 4601/100629 [03:38<1:38:16, 16.29it/s]

  5%|▍         | 4603/100629 [03:38<1:39:17, 16.12it/s]

  5%|▍         | 4606/100629 [03:38<1:28:28, 18.09it/s]

  5%|▍         | 4608/100629 [03:38<1:27:45, 18.24it/s]

  5%|▍         | 4611/100629 [03:38<1:21:22, 19.67it/s]

  5%|▍         | 4614/100629 [03:39<1:18:08, 20.48it/s]

  5%|▍         | 4617/100629 [03:39<1:21:16, 19.69it/s]

  5%|▍         | 4620/100629 [03:39<1:18:20, 20.42it/s]

  5%|▍         | 4623/100629 [03:39<1:22:24, 19.42it/s]

  5%|▍         | 4625/100629 [03:39<1:35:20, 16.78it/s]

  5%|▍         | 4627/100629 [03:39<1:39:48, 16.03it/s]

  5%|▍         | 4631/100629 [03:39<1:16:02, 21.04it/s]

  5%|▍         | 4634/100629 [03:40<1:14:07, 21.59it/s]

  5%|▍         | 4637/100629 [03:40<1:12:29, 22.07it/s]

  5%|▍         | 4640/100629 [03:40<1:11:13, 22.46it/s]

  5%|▍         | 4643/100629 [03:40<1:10:10, 22.80it/s]

  5%|▍         | 4646/100629 [03:40<1:14:36, 21.44it/s]

  5%|▍         | 4649/100629 [03:40<1:09:47, 22.92it/s]

  5%|▍         | 4652/100629 [03:40<1:14:25, 21.49it/s]

  5%|▍         | 4655/100629 [03:41<1:14:37, 21.43it/s]

  5%|▍         | 4658/100629 [03:41<1:15:31, 21.18it/s]

  5%|▍         | 4661/100629 [03:41<1:12:57, 21.93it/s]

  5%|▍         | 4664/100629 [03:41<1:10:07, 22.81it/s]

  5%|▍         | 4667/100629 [03:41<1:16:57, 20.78it/s]

  5%|▍         | 4670/100629 [03:41<1:38:44, 16.20it/s]

  5%|▍         | 4672/100629 [03:41<1:41:07, 15.81it/s]

  5%|▍         | 4676/100629 [03:42<1:20:32, 19.86it/s]

  5%|▍         | 4680/100629 [03:42<1:06:41, 23.98it/s]

  5%|▍         | 4684/100629 [03:42<57:52, 27.63it/s]

  5%|▍         | 4688/100629 [03:42<1:00:06, 26.60it/s]

  5%|▍         | 4691/100629 [03:42<1:09:15, 23.08it/s]

  5%|▍         | 4694/100629 [03:42<1:08:20, 23.40it/s]

  5%|▍         | 4698/100629 [03:42<1:00:59, 26.21it/s]

  5%|▍         | 4701/100629 [03:43<1:11:03, 22.50it/s]

  5%|▍         | 4704/100629 [03:43<1:12:35, 22.03it/s]

  5%|▍         | 4707/100629 [03:43<1:07:13, 23.78it/s]

  5%|▍         | 4711/100629 [03:43<1:02:06, 25.74it/s]

  5%|▍         | 4715/100629 [03:43<59:51, 26.71it/s]

  5%|▍         | 4718/100629 [03:43<59:02, 27.07it/s]

  5%|▍         | 4721/100629 [03:43<57:36, 27.74it/s]

  5%|▍         | 4724/100629 [03:43<1:03:28, 25.18it/s]

  5%|▍         | 4727/100629 [03:44<1:04:43, 24.70it/s]

  5%|▍         | 4730/100629 [03:44<1:10:26, 22.69it/s]

  5%|▍         | 4733/100629 [03:44<1:16:10, 20.98it/s]

  5%|▍         | 4738/100629 [03:44<1:07:15, 23.76it/s]

  5%|▍         | 4741/100629 [03:44<1:06:54, 23.88it/s]

  5%|▍         | 4744/100629 [03:44<1:08:46, 23.24it/s]

  5%|▍         | 4747/100629 [03:44<1:07:12, 23.78it/s]

  5%|▍         | 4750/100629 [03:45<1:03:14, 25.27it/s]

  5%|▍         | 4753/100629 [03:45<1:07:15, 23.76it/s]

  5%|▍         | 4756/100629 [03:45<1:08:15, 23.41it/s]

  5%|▍         | 4759/100629 [03:45<1:08:27, 23.34it/s]

  5%|▍         | 4763/100629 [03:45<1:01:04, 26.16it/s]

  5%|▍         | 4766/100629 [03:45<1:06:19, 24.09it/s]

  5%|▍         | 4769/100629 [03:45<1:17:48, 20.53it/s]

  5%|▍         | 4772/100629 [03:46<1:16:12, 20.97it/s]

  5%|▍         | 4775/100629 [03:46<1:13:54, 21.61it/s]

  5%|▍         | 4778/100629 [03:46<1:08:41, 23.26it/s]

  5%|▍         | 4782/100629 [03:46<1:02:55, 25.39it/s]

  5%|▍         | 4785/100629 [03:46<1:10:26, 22.68it/s]

  5%|▍         | 4788/100629 [03:46<1:10:42, 22.59it/s]

  5%|▍         | 4791/100629 [03:46<1:21:23, 19.63it/s]

  5%|▍         | 4794/100629 [03:47<1:16:15, 20.94it/s]

  5%|▍         | 4797/100629 [03:47<1:27:00, 18.36it/s]

  5%|▍         | 4799/100629 [03:47<1:31:19, 17.49it/s]

  5%|▍         | 4802/100629 [03:47<1:27:01, 18.35it/s]

  5%|▍         | 4805/100629 [03:47<1:22:30, 19.36it/s]

  5%|▍         | 4808/100629 [03:47<1:20:47, 19.77it/s]

  5%|▍         | 4811/100629 [03:48<1:27:42, 18.21it/s]

  5%|▍         | 4814/100629 [03:48<1:22:00, 19.47it/s]

  5%|▍         | 4817/100629 [03:48<1:37:07, 16.44it/s]

  5%|▍         | 4819/100629 [03:48<1:36:24, 16.56it/s]

  5%|▍         | 4821/100629 [03:48<1:33:40, 17.05it/s]

  5%|▍         | 4824/100629 [03:48<1:22:18, 19.40it/s]

  5%|▍         | 4827/100629 [03:48<1:16:16, 20.93it/s]

  5%|▍         | 4830/100629 [03:49<1:13:41, 21.67it/s]

  5%|▍         | 4834/100629 [03:49<1:04:22, 24.80it/s]

  5%|▍         | 4838/100629 [03:49<1:01:19, 26.04it/s]

  5%|▍         | 4841/100629 [03:49<1:06:51, 23.88it/s]

  5%|▍         | 4844/100629 [03:49<1:04:22, 24.80it/s]

  5%|▍         | 4847/100629 [03:49<1:09:58, 22.81it/s]

  5%|▍         | 4850/100629 [03:49<1:11:00, 22.48it/s]

  5%|▍         | 4853/100629 [03:49<1:10:34, 22.62it/s]

  5%|▍         | 4856/100629 [03:50<1:10:14, 22.72it/s]

  5%|▍         | 4859/100629 [03:50<1:14:38, 21.38it/s]

  5%|▍         | 4862/100629 [03:50<1:18:29, 20.33it/s]

  5%|▍         | 4866/100629 [03:50<1:05:04, 24.52it/s]

  5%|▍         | 4869/100629 [03:50<1:09:20, 23.02it/s]

  5%|▍         | 4872/100629 [03:50<1:10:51, 22.52it/s]

  5%|▍         | 4875/100629 [03:50<1:13:50, 21.61it/s]

  5%|▍         | 4878/100629 [03:51<1:10:00, 22.80it/s]

  5%|▍         | 4881/100629 [03:51<1:09:04, 23.10it/s]

  5%|▍         | 4884/100629 [03:51<1:19:34, 20.05it/s]

  5%|▍         | 4887/100629 [03:51<1:12:54, 21.89it/s]

  5%|▍         | 4890/100629 [03:51<1:15:31, 21.13it/s]

  5%|▍         | 4893/100629 [03:51<1:30:11, 17.69it/s]

  5%|▍         | 4897/100629 [03:51<1:13:45, 21.63it/s]

  5%|▍         | 4900/100629 [03:52<1:09:34, 22.93it/s]

  5%|▍         | 4903/100629 [03:52<1:09:58, 22.80it/s]

  5%|▍         | 4906/100629 [03:52<1:12:46, 21.92it/s]

  5%|▍         | 4909/100629 [03:52<1:07:49, 23.52it/s]

  5%|▍         | 4913/100629 [03:52<1:00:51, 26.21it/s]

  5%|▍         | 4916/100629 [03:52<1:00:39, 26.30it/s]

  5%|▍         | 4920/100629 [03:52<57:50, 27.58it/s]

  5%|▍         | 4924/100629 [03:52<52:49, 30.20it/s]

  5%|▍         | 4928/100629 [03:53<1:02:55, 25.35it/s]

  5%|▍         | 4931/100629 [03:53<1:05:00, 24.53it/s]

  5%|▍         | 4934/100629 [03:53<1:08:35, 23.25it/s]

  5%|▍         | 4939/100629 [03:53<59:15, 26.91it/s]

  5%|▍         | 4942/100629 [03:53<58:16, 27.37it/s]

  5%|▍         | 4945/100629 [03:53<57:19, 27.82it/s]

  5%|▍         | 4948/100629 [03:53<1:06:05, 24.13it/s]

  5%|▍         | 4951/100629 [03:54<1:05:32, 24.33it/s]

  5%|▍         | 4954/100629 [03:54<1:19:08, 20.15it/s]

  5%|▍         | 4957/100629 [03:54<1:22:22, 19.36it/s]

  5%|▍         | 4960/100629 [03:54<1:18:15, 20.38it/s]

  5%|▍         | 4963/100629 [03:54<1:22:27, 19.34it/s]

  5%|▍         | 4966/100629 [03:55<1:32:20, 17.27it/s]

  5%|▍         | 4969/100629 [03:55<1:27:59, 18.12it/s]

  5%|▍         | 4972/100629 [03:55<1:18:52, 20.21it/s]

  5%|▍         | 4975/100629 [03:55<1:13:15, 21.76it/s]

  5%|▍         | 4978/100629 [03:55<1:18:59, 20.18it/s]

  5%|▍         | 4981/100629 [03:55<1:22:27, 19.33it/s]

  5%|▍         | 4984/100629 [03:55<1:17:15, 20.63it/s]

  5%|▍         | 4987/100629 [03:55<1:15:14, 21.19it/s]

  5%|▍         | 4990/100629 [03:56<1:27:05, 18.30it/s]

  5%|▍         | 4994/100629 [03:56<1:13:28, 21.69it/s]

  5%|▍         | 4997/100629 [03:56<1:24:37, 18.83it/s]

  5%|▍         | 5000/100629 [03:56<1:37:39, 16.32it/s]

  5%|▍         | 5003/100629 [03:56<1:30:57, 17.52it/s]

  5%|▍         | 5005/100629 [03:57<1:30:05, 17.69it/s]

  5%|▍         | 5007/100629 [03:57<1:32:14, 17.28it/s]

  5%|▍         | 5009/100629 [03:57<1:29:16, 17.85it/s]

  5%|▍         | 5012/100629 [03:57<1:25:04, 18.73it/s]

  5%|▍         | 5014/100629 [03:57<1:34:36, 16.84it/s]

  5%|▍         | 5016/100629 [03:57<1:33:21, 17.07it/s]

  5%|▍         | 5019/100629 [03:57<1:30:14, 17.66it/s]

  5%|▍         | 5023/100629 [03:57<1:12:20, 22.03it/s]

  5%|▍         | 5026/100629 [03:58<1:31:19, 17.45it/s]

  5%|▍         | 5029/100629 [03:58<1:22:58, 19.20it/s]

  5%|▌         | 5032/100629 [03:58<1:23:27, 19.09it/s]

  5%|▌         | 5035/100629 [03:58<1:28:47, 17.94it/s]

  5%|▌         | 5038/100629 [03:58<1:18:05, 20.40it/s]

  5%|▌         | 5041/100629 [03:58<1:23:59, 18.97it/s]

  5%|▌         | 5044/100629 [03:59<1:21:26, 19.56it/s]

  5%|▌         | 5047/100629 [03:59<1:19:49, 19.96it/s]

  5%|▌         | 5050/100629 [03:59<1:13:20, 21.72it/s]

  5%|▌         | 5054/100629 [03:59<1:03:19, 25.16it/s]

  5%|▌         | 5057/100629 [03:59<1:15:50, 21.00it/s]

  5%|▌         | 5061/100629 [03:59<1:11:36, 22.25it/s]

  5%|▌         | 5064/100629 [03:59<1:18:06, 20.39it/s]

  5%|▌         | 5069/100629 [04:00<1:01:59, 25.69it/s]

  5%|▌         | 5072/100629 [04:00<1:01:12, 26.02it/s]

  5%|▌         | 5075/100629 [04:00<1:05:23, 24.36it/s]

  5%|▌         | 5078/100629 [04:00<1:03:20, 25.14it/s]

  5%|▌         | 5082/100629 [04:00<56:16, 28.30it/s]

  5%|▌         | 5085/100629 [04:00<1:00:19, 26.40it/s]

  5%|▌         | 5088/100629 [04:00<1:09:18, 22.97it/s]

  5%|▌         | 5091/100629 [04:00<1:05:52, 24.17it/s]

  5%|▌         | 5094/100629 [04:01<1:02:37, 25.42it/s]

  5%|▌         | 5097/100629 [04:01<1:05:21, 24.36it/s]

  5%|▌         | 5100/100629 [04:01<1:04:44, 24.59it/s]

  5%|▌         | 5103/100629 [04:01<1:18:20, 20.32it/s]

  5%|▌         | 5106/100629 [04:01<1:14:39, 21.32it/s]

  5%|▌         | 5109/100629 [04:01<1:14:37, 21.33it/s]

  5%|▌         | 5112/100629 [04:02<1:29:15, 17.84it/s]

  5%|▌         | 5114/100629 [04:02<1:45:15, 15.12it/s]

  5%|▌         | 5117/100629 [04:02<1:29:38, 17.76it/s]

  5%|▌         | 5121/100629 [04:02<1:11:32, 22.25it/s]

  5%|▌         | 5124/100629 [04:02<1:15:59, 20.95it/s]

  5%|▌         | 5127/100629 [04:02<1:21:47, 19.46it/s]

  5%|▌         | 5130/100629 [04:03<1:46:48, 14.90it/s]

  5%|▌         | 5133/100629 [04:03<1:38:54, 16.09it/s]

  5%|▌         | 5135/100629 [04:03<1:46:19, 14.97it/s]

  5%|▌         | 5137/100629 [04:03<1:40:00, 15.91it/s]

  5%|▌         | 5139/100629 [04:03<1:49:50, 14.49it/s]

  5%|▌         | 5142/100629 [04:03<1:33:39, 16.99it/s]

  5%|▌         | 5146/100629 [04:03<1:14:17, 21.42it/s]

  5%|▌         | 5149/100629 [04:04<1:12:33, 21.93it/s]

  5%|▌         | 5152/100629 [04:04<1:19:46, 19.95it/s]

  5%|▌         | 5155/100629 [04:04<1:17:25, 20.55it/s]

  5%|▌         | 5158/100629 [04:04<1:13:15, 21.72it/s]

  5%|▌         | 5161/100629 [04:04<1:16:42, 20.74it/s]

  5%|▌         | 5164/100629 [04:04<1:17:28, 20.54it/s]

  5%|▌         | 5167/100629 [04:05<1:25:20, 18.64it/s]

  5%|▌         | 5169/100629 [04:05<1:26:26, 18.40it/s]

  5%|▌         | 5173/100629 [04:05<1:09:51, 22.78it/s]

  5%|▌         | 5176/100629 [04:05<1:18:47, 20.19it/s]

  5%|▌         | 5181/100629 [04:05<1:10:49, 22.46it/s]

  5%|▌         | 5184/100629 [04:05<1:16:35, 20.77it/s]

  5%|▌         | 5187/100629 [04:05<1:20:39, 19.72it/s]

  5%|▌         | 5190/100629 [04:06<1:15:07, 21.17it/s]

  5%|▌         | 5193/100629 [04:06<1:16:35, 20.77it/s]

  5%|▌         | 5196/100629 [04:06<1:30:22, 17.60it/s]

  5%|▌         | 5198/100629 [04:06<1:31:09, 17.45it/s]

  5%|▌         | 5201/100629 [04:06<1:32:36, 17.17it/s]

  5%|▌         | 5203/100629 [04:06<1:39:10, 16.04it/s]

  5%|▌         | 5206/100629 [04:07<1:29:11, 17.83it/s]

  5%|▌         | 5208/100629 [04:07<1:39:57, 15.91it/s]

  5%|▌         | 5211/100629 [04:07<1:31:45, 17.33it/s]

  5%|▌         | 5216/100629 [04:07<1:09:20, 22.93it/s]

  5%|▌         | 5219/100629 [04:07<1:15:15, 21.13it/s]

  5%|▌         | 5223/100629 [04:07<1:11:48, 22.14it/s]

  5%|▌         | 5227/100629 [04:07<1:07:41, 23.49it/s]

  5%|▌         | 5230/100629 [04:08<1:09:46, 22.79it/s]

  5%|▌         | 5233/100629 [04:08<1:07:09, 23.67it/s]

  5%|▌         | 5236/100629 [04:08<1:16:16, 20.84it/s]

  5%|▌         | 5241/100629 [04:08<1:03:19, 25.11it/s]

  5%|▌         | 5244/100629 [04:08<1:03:15, 25.13it/s]

  5%|▌         | 5247/100629 [04:08<1:06:54, 23.76it/s]

  5%|▌         | 5250/100629 [04:09<1:17:00, 20.64it/s]

  5%|▌         | 5253/100629 [04:09<1:32:10, 17.24it/s]

  5%|▌         | 5257/100629 [04:09<1:22:18, 19.31it/s]

  5%|▌         | 5261/100629 [04:09<1:16:23, 20.81it/s]

  5%|▌         | 5264/100629 [04:09<1:27:33, 18.15it/s]

  5%|▌         | 5267/100629 [04:09<1:22:11, 19.34it/s]

  5%|▌         | 5270/100629 [04:10<1:28:34, 17.94it/s]

  5%|▌         | 5272/100629 [04:10<1:30:48, 17.50it/s]

  5%|▌         | 5274/100629 [04:10<1:37:26, 16.31it/s]

  5%|▌         | 5276/100629 [04:10<1:53:10, 14.04it/s]

  5%|▌         | 5280/100629 [04:10<1:31:01, 17.46it/s]

  5%|▌         | 5282/100629 [04:10<1:36:04, 16.54it/s]

  5%|▌         | 5285/100629 [04:11<1:30:45, 17.51it/s]

  5%|▌         | 5287/100629 [04:11<1:40:39, 15.79it/s]

  5%|▌         | 5289/100629 [04:11<1:36:50, 16.41it/s]

  5%|▌         | 5292/100629 [04:11<1:28:21, 17.98it/s]

  5%|▌         | 5294/100629 [04:11<1:27:13, 18.22it/s]

  5%|▌         | 5299/100629 [04:11<1:02:23, 25.47it/s]

  5%|▌         | 5302/100629 [04:11<1:08:28, 23.20it/s]

  5%|▌         | 5306/100629 [04:11<1:02:20, 25.48it/s]

  5%|▌         | 5311/100629 [04:12<52:09, 30.46it/s]

  5%|▌         | 5315/100629 [04:12<1:20:23, 19.76it/s]

  5%|▌         | 5318/100629 [04:12<1:17:25, 20.52it/s]

  5%|▌         | 5321/100629 [04:12<1:13:43, 21.55it/s]

  5%|▌         | 5324/100629 [04:12<1:18:11, 20.31it/s]

  5%|▌         | 5327/100629 [04:13<1:15:52, 20.94it/s]

  5%|▌         | 5330/100629 [04:13<1:36:28, 16.46it/s]

  5%|▌         | 5333/100629 [04:13<1:32:07, 17.24it/s]

  5%|▌         | 5336/100629 [04:13<1:25:57, 18.47it/s]

  5%|▌         | 5339/100629 [04:13<1:25:13, 18.63it/s]

  5%|▌         | 5343/100629 [04:13<1:13:35, 21.58it/s]

  5%|▌         | 5346/100629 [04:14<1:12:42, 21.84it/s]

  5%|▌         | 5349/100629 [04:14<1:20:08, 19.81it/s]

  5%|▌         | 5352/100629 [04:14<1:17:43, 20.43it/s]

  5%|▌         | 5356/100629 [04:14<1:05:27, 24.26it/s]

  5%|▌         | 5359/100629 [04:14<1:11:21, 22.25it/s]

  5%|▌         | 5362/100629 [04:14<1:16:45, 20.69it/s]

  5%|▌         | 5365/100629 [04:14<1:17:32, 20.48it/s]

  5%|▌         | 5368/100629 [04:15<1:10:46, 22.44it/s]

  5%|▌         | 5372/100629 [04:15<1:06:26, 23.90it/s]

  5%|▌         | 5375/100629 [04:15<1:03:08, 25.14it/s]

  5%|▌         | 5379/100629 [04:15<1:02:36, 25.36it/s]

  5%|▌         | 5382/100629 [04:15<1:13:14, 21.68it/s]

  5%|▌         | 5385/100629 [04:15<1:13:01, 21.74it/s]

  5%|▌         | 5388/100629 [04:15<1:11:11, 22.30it/s]

  5%|▌         | 5391/100629 [04:16<1:12:01, 22.04it/s]

  5%|▌         | 5394/100629 [04:16<1:19:34, 19.95it/s]

  5%|▌         | 5397/100629 [04:16<1:27:11, 18.20it/s]

  5%|▌         | 5400/100629 [04:16<1:20:12, 19.79it/s]

  5%|▌         | 5403/100629 [04:16<1:16:56, 20.63it/s]

  5%|▌         | 5406/100629 [04:16<1:25:14, 18.62it/s]

  5%|▌         | 5409/100629 [04:17<1:25:54, 18.47it/s]

  5%|▌         | 5412/100629 [04:17<1:21:40, 19.43it/s]

  5%|▌         | 5415/100629 [04:17<1:19:23, 19.99it/s]

  5%|▌         | 5418/100629 [04:17<1:16:19, 20.79it/s]

  5%|▌         | 5421/100629 [04:17<1:18:09, 20.30it/s]

  5%|▌         | 5424/100629 [04:17<1:23:51, 18.92it/s]

  5%|▌         | 5427/100629 [04:17<1:17:04, 20.59it/s]

  5%|▌         | 5430/100629 [04:18<1:18:35, 20.19it/s]

  5%|▌         | 5433/100629 [04:18<1:25:02, 18.66it/s]

  5%|▌         | 5436/100629 [04:18<1:22:17, 19.28it/s]

  5%|▌         | 5438/100629 [04:18<1:25:46, 18.50it/s]

  5%|▌         | 5440/100629 [04:18<1:59:07, 13.32it/s]

  5%|▌         | 5445/100629 [04:18<1:28:44, 17.88it/s]

  5%|▌         | 5449/100629 [04:19<1:16:05, 20.85it/s]

  5%|▌         | 5453/100629 [04:19<1:12:02, 22.02it/s]

  5%|▌         | 5456/100629 [04:19<1:23:43, 18.94it/s]

  5%|▌         | 5459/100629 [04:19<1:23:17, 19.04it/s]

  5%|▌         | 5462/100629 [04:19<1:16:30, 20.73it/s]

  5%|▌         | 5465/100629 [04:19<1:25:04, 18.64it/s]

  5%|▌         | 5468/100629 [04:20<1:26:21, 18.36it/s]

  5%|▌         | 5470/100629 [04:20<1:25:45, 18.49it/s]

  5%|▌         | 5473/100629 [04:20<1:28:42, 17.88it/s]

  5%|▌         | 5475/100629 [04:20<1:35:06, 16.67it/s]

  5%|▌         | 5477/100629 [04:20<1:37:43, 16.23it/s]

  5%|▌         | 5480/100629 [04:20<1:32:07, 17.21it/s]

  5%|▌         | 5483/100629 [04:20<1:25:53, 18.46it/s]

  5%|▌         | 5486/100629 [04:21<1:23:11, 19.06it/s]

  5%|▌         | 5488/100629 [04:21<1:22:51, 19.14it/s]

  5%|▌         | 5491/100629 [04:21<1:26:16, 18.38it/s]

  5%|▌         | 5495/100629 [04:21<1:10:02, 22.64it/s]

  5%|▌         | 5498/100629 [04:21<1:18:48, 20.12it/s]

  5%|▌         | 5502/100629 [04:21<1:05:05, 24.36it/s]

  5%|▌         | 5505/100629 [04:21<1:04:44, 24.49it/s]

  5%|▌         | 5508/100629 [04:22<1:18:49, 20.11it/s]

  5%|▌         | 5511/100629 [04:22<1:18:18, 20.24it/s]

  5%|▌         | 5514/100629 [04:22<1:22:09, 19.30it/s]

  5%|▌         | 5519/100629 [04:22<1:03:28, 24.97it/s]

  5%|▌         | 5522/100629 [04:22<1:04:51, 24.44it/s]

  5%|▌         | 5525/100629 [04:22<1:01:40, 25.70it/s]

  5%|▌         | 5528/100629 [04:22<1:11:13, 22.25it/s]

  5%|▌         | 5531/100629 [04:23<1:23:41, 18.94it/s]

  5%|▌         | 5534/100629 [04:23<1:29:09, 17.78it/s]

  6%|▌         | 5538/100629 [04:23<1:15:36, 20.96it/s]

  6%|▌         | 5541/100629 [04:23<1:15:25, 21.01it/s]

  6%|▌         | 5545/100629 [04:23<1:11:32, 22.15it/s]

  6%|▌         | 5548/100629 [04:23<1:11:39, 22.11it/s]

  6%|▌         | 5551/100629 [04:24<1:07:38, 23.43it/s]

  6%|▌         | 5554/100629 [04:24<1:24:06, 18.84it/s]

  6%|▌         | 5557/100629 [04:24<1:33:13, 17.00it/s]

  6%|▌         | 5562/100629 [04:24<1:12:11, 21.95it/s]

  6%|▌         | 5565/100629 [04:24<1:18:06, 20.28it/s]

  6%|▌         | 5569/100629 [04:24<1:09:58, 22.64it/s]

  6%|▌         | 5572/100629 [04:25<1:13:27, 21.57it/s]

  6%|▌         | 5575/100629 [04:25<1:10:36, 22.44it/s]

  6%|▌         | 5578/100629 [04:25<1:07:12, 23.57it/s]

  6%|▌         | 5582/100629 [04:25<1:04:46, 24.45it/s]

  6%|▌         | 5585/100629 [04:25<1:10:15, 22.55it/s]

  6%|▌         | 5588/100629 [04:25<1:14:12, 21.35it/s]

  6%|▌         | 5592/100629 [04:26<1:15:21, 21.02it/s]

  6%|▌         | 5595/100629 [04:26<1:21:12, 19.51it/s]

  6%|▌         | 5598/100629 [04:26<1:23:33, 18.96it/s]

  6%|▌         | 5601/100629 [04:26<1:17:31, 20.43it/s]

  6%|▌         | 5604/100629 [04:26<1:23:05, 19.06it/s]

  6%|▌         | 5606/100629 [04:26<1:24:30, 18.74it/s]

  6%|▌         | 5610/100629 [04:26<1:15:40, 20.93it/s]

  6%|▌         | 5613/100629 [04:27<1:20:54, 19.57it/s]

  6%|▌         | 5616/100629 [04:27<1:17:29, 20.44it/s]

  6%|▌         | 5619/100629 [04:27<1:19:33, 19.90it/s]

  6%|▌         | 5622/100629 [04:27<1:15:55, 20.86it/s]

  6%|▌         | 5625/100629 [04:27<1:18:00, 20.30it/s]

  6%|▌         | 5628/100629 [04:27<1:16:52, 20.60it/s]

  6%|▌         | 5631/100629 [04:28<1:20:26, 19.68it/s]

  6%|▌         | 5634/100629 [04:28<1:15:50, 20.87it/s]

  6%|▌         | 5637/100629 [04:28<1:18:36, 20.14it/s]

  6%|▌         | 5641/100629 [04:28<1:09:11, 22.88it/s]

  6%|▌         | 5644/100629 [04:28<1:10:02, 22.60it/s]

  6%|▌         | 5647/100629 [04:28<1:08:14, 23.20it/s]

  6%|▌         | 5651/100629 [04:28<1:08:42, 23.04it/s]

  6%|▌         | 5654/100629 [04:29<1:22:53, 19.10it/s]

  6%|▌         | 5657/100629 [04:29<1:20:50, 19.58it/s]

  6%|▌         | 5660/100629 [04:29<1:25:06, 18.60it/s]

  6%|▌         | 5664/100629 [04:29<1:15:55, 20.84it/s]

  6%|▌         | 5667/100629 [04:29<1:12:46, 21.75it/s]

  6%|▌         | 5671/100629 [04:29<1:05:51, 24.03it/s]

  6%|▌         | 5675/100629 [04:29<1:03:40, 24.86it/s]

  6%|▌         | 5678/100629 [04:30<1:06:59, 23.62it/s]

  6%|▌         | 5681/100629 [04:30<1:23:48, 18.88it/s]

  6%|▌         | 5685/100629 [04:30<1:19:12, 19.98it/s]

  6%|▌         | 5688/100629 [04:30<1:16:40, 20.64it/s]

  6%|▌         | 5691/100629 [04:30<1:22:35, 19.16it/s]

  6%|▌         | 5694/100629 [04:30<1:16:33, 20.67it/s]

  6%|▌         | 5697/100629 [04:31<1:21:39, 19.38it/s]

  6%|▌         | 5701/100629 [04:31<1:20:47, 19.58it/s]

  6%|▌         | 5704/100629 [04:31<1:18:59, 20.03it/s]

  6%|▌         | 5707/100629 [04:31<1:24:38, 18.69it/s]

  6%|▌         | 5709/100629 [04:31<1:24:33, 18.71it/s]

  6%|▌         | 5712/100629 [04:31<1:17:45, 20.35it/s]

  6%|▌         | 5715/100629 [04:32<1:20:15, 19.71it/s]

  6%|▌         | 5718/100629 [04:32<1:19:55, 19.79it/s]

  6%|▌         | 5721/100629 [04:32<1:18:34, 20.13it/s]

  6%|▌         | 5724/100629 [04:32<1:24:09, 18.79it/s]

  6%|▌         | 5726/100629 [04:32<1:25:25, 18.52it/s]

  6%|▌         | 5729/100629 [04:32<1:15:55, 20.83it/s]

  6%|▌         | 5732/100629 [04:32<1:21:37, 19.38it/s]

  6%|▌         | 5735/100629 [04:33<1:18:02, 20.27it/s]

  6%|▌         | 5739/100629 [04:33<1:13:06, 21.63it/s]

  6%|▌         | 5744/100629 [04:33<59:01, 26.79it/s]

  6%|▌         | 5748/100629 [04:33<1:01:13, 25.83it/s]

  6%|▌         | 5751/100629 [04:33<1:10:37, 22.39it/s]

  6%|▌         | 5755/100629 [04:33<1:03:19, 24.97it/s]

  6%|▌         | 5759/100629 [04:33<58:29, 27.03it/s]

  6%|▌         | 5762/100629 [04:34<1:12:57, 21.67it/s]

  6%|▌         | 5765/100629 [04:34<1:14:13, 21.30it/s]

  6%|▌         | 5768/100629 [04:34<1:13:49, 21.42it/s]

  6%|▌         | 5771/100629 [04:34<1:22:15, 19.22it/s]

  6%|▌         | 5774/100629 [04:34<1:15:05, 21.05it/s]

  6%|▌         | 5777/100629 [04:34<1:09:27, 22.76it/s]

  6%|▌         | 5781/100629 [04:34<1:02:24, 25.33it/s]

  6%|▌         | 5785/100629 [04:35<1:00:05, 26.31it/s]

  6%|▌         | 5788/100629 [04:35<1:01:09, 25.85it/s]

  6%|▌         | 5791/100629 [04:35<1:09:28, 22.75it/s]

  6%|▌         | 5794/100629 [04:35<1:07:04, 23.56it/s]

  6%|▌         | 5797/100629 [04:35<1:30:14, 17.51it/s]

  6%|▌         | 5800/100629 [04:36<1:32:01, 17.18it/s]

  6%|▌         | 5802/100629 [04:36<1:40:37, 15.71it/s]

  6%|▌         | 5804/100629 [04:36<1:36:55, 16.31it/s]

  6%|▌         | 5806/100629 [04:36<1:36:31, 16.37it/s]

  6%|▌         | 5809/100629 [04:36<1:24:12, 18.77it/s]

  6%|▌         | 5812/100629 [04:36<1:13:56, 21.37it/s]

  6%|▌         | 5816/100629 [04:36<1:11:01, 22.25it/s]

  6%|▌         | 5819/100629 [04:36<1:12:59, 21.65it/s]

  6%|▌         | 5823/100629 [04:37<1:07:36, 23.37it/s]

  6%|▌         | 5826/100629 [04:37<1:12:17, 21.86it/s]

  6%|▌         | 5831/100629 [04:37<1:00:42, 26.02it/s]

  6%|▌         | 5834/100629 [04:37<59:19, 26.63it/s]

  6%|▌         | 5838/100629 [04:37<57:46, 27.34it/s]

  6%|▌         | 5841/100629 [04:37<1:03:41, 24.80it/s]

  6%|▌         | 5844/100629 [04:38<1:19:15, 19.93it/s]

  6%|▌         | 5847/100629 [04:38<1:24:20, 18.73it/s]

  6%|▌         | 5850/100629 [04:38<1:15:25, 20.94it/s]

  6%|▌         | 5853/100629 [04:38<1:18:07, 20.22it/s]

  6%|▌         | 5856/100629 [04:38<1:13:12, 21.58it/s]

  6%|▌         | 5861/100629 [04:38<1:09:48, 22.62it/s]

  6%|▌         | 5864/100629 [04:38<1:07:24, 23.43it/s]

  6%|▌         | 5869/100629 [04:39<59:04, 26.73it/s]

  6%|▌         | 5873/100629 [04:39<53:21, 29.60it/s]

  6%|▌         | 5877/100629 [04:39<1:29:08, 17.71it/s]

  6%|▌         | 5881/100629 [04:39<1:20:34, 19.60it/s]

  6%|▌         | 5884/100629 [04:39<1:23:37, 18.88it/s]

  6%|▌         | 5887/100629 [04:40<1:41:53, 15.50it/s]

  6%|▌         | 5889/100629 [04:40<1:37:49, 16.14it/s]

  6%|▌         | 5892/100629 [04:40<1:26:11, 18.32it/s]

  6%|▌         | 5895/100629 [04:40<1:29:58, 17.55it/s]

  6%|▌         | 5899/100629 [04:40<1:17:04, 20.49it/s]

  6%|▌         | 5902/100629 [04:40<1:12:29, 21.78it/s]

  6%|▌         | 5905/100629 [04:41<1:21:29, 19.37it/s]

  6%|▌         | 5908/100629 [04:41<1:20:45, 19.55it/s]

  6%|▌         | 5911/100629 [04:41<1:20:58, 19.49it/s]

  6%|▌         | 5914/100629 [04:41<1:12:48, 21.68it/s]

  6%|▌         | 5918/100629 [04:41<1:04:27, 24.49it/s]

  6%|▌         | 5921/100629 [04:41<1:14:49, 21.10it/s]

  6%|▌         | 5924/100629 [04:41<1:22:06, 19.22it/s]

  6%|▌         | 5927/100629 [04:42<1:31:29, 17.25it/s]

  6%|▌         | 5929/100629 [04:42<2:23:41, 10.98it/s]

  6%|▌         | 5931/100629 [04:42<2:16:18, 11.58it/s]

  6%|▌         | 5933/100629 [04:42<2:11:25, 12.01it/s]

  6%|▌         | 5937/100629 [04:43<1:38:42, 15.99it/s]

  6%|▌         | 5939/100629 [04:43<1:38:14, 16.06it/s]

  6%|▌         | 5943/100629 [04:43<1:20:35, 19.58it/s]

  6%|▌         | 5946/100629 [04:43<1:18:29, 20.11it/s]

  6%|▌         | 5949/100629 [04:43<1:27:23, 18.06it/s]

  6%|▌         | 5953/100629 [04:43<1:16:42, 20.57it/s]

  6%|▌         | 5957/100629 [04:43<1:05:55, 23.93it/s]

  6%|▌         | 5960/100629 [04:44<1:09:53, 22.57it/s]

  6%|▌         | 5963/100629 [04:44<1:07:58, 23.21it/s]

  6%|▌         | 5966/100629 [04:44<1:28:23, 17.85it/s]

  6%|▌         | 5969/100629 [04:44<1:19:39, 19.80it/s]

  6%|▌         | 5976/100629 [04:44<54:20, 29.03it/s]

  6%|▌         | 5980/100629 [04:44<52:18, 30.15it/s]

  6%|▌         | 5984/100629 [04:44<50:36, 31.17it/s]

  6%|▌         | 5990/100629 [04:45<54:12, 29.10it/s]

  6%|▌         | 5994/100629 [04:45<55:34, 28.38it/s]

  6%|▌         | 5997/100629 [04:45<1:05:26, 24.10it/s]

  6%|▌         | 6001/100629 [04:45<59:25, 26.54it/s]

  6%|▌         | 6004/100629 [04:45<58:05, 27.15it/s]

  6%|▌         | 6007/100629 [04:45<1:16:28, 20.62it/s]

  6%|▌         | 6010/100629 [04:46<1:14:19, 21.22it/s]

  6%|▌         | 6013/100629 [04:46<1:28:55, 17.73it/s]

  6%|▌         | 6016/100629 [04:46<1:22:44, 19.06it/s]

  6%|▌         | 6019/100629 [04:46<1:17:10, 20.43it/s]

  6%|▌         | 6022/100629 [04:46<1:33:52, 16.80it/s]

  6%|▌         | 6024/100629 [04:46<1:41:16, 15.57it/s]

  6%|▌         | 6026/100629 [04:47<1:51:04, 14.19it/s]

  6%|▌         | 6028/100629 [04:47<2:00:40, 13.07it/s]

  6%|▌         | 6031/100629 [04:47<1:47:46, 14.63it/s]

  6%|▌         | 6033/100629 [04:47<1:42:35, 15.37it/s]

  6%|▌         | 6035/100629 [04:47<1:48:40, 14.51it/s]

  6%|▌         | 6037/100629 [04:47<1:48:46, 14.49it/s]

  6%|▌         | 6040/100629 [04:48<1:32:04, 17.12it/s]

  6%|▌         | 6043/100629 [04:48<1:21:45, 19.28it/s]

  6%|▌         | 6046/100629 [04:48<1:25:07, 18.52it/s]

  6%|▌         | 6050/100629 [04:48<1:11:40, 21.99it/s]

  6%|▌         | 6053/100629 [04:48<1:07:18, 23.42it/s]

  6%|▌         | 6056/100629 [04:48<1:11:14, 22.12it/s]

  6%|▌         | 6060/100629 [04:48<1:08:49, 22.90it/s]

  6%|▌         | 6063/100629 [04:49<1:22:47, 19.04it/s]

  6%|▌         | 6067/100629 [04:49<1:10:18, 22.42it/s]

  6%|▌         | 6070/100629 [04:49<1:05:51, 23.93it/s]

  6%|▌         | 6074/100629 [04:49<1:00:05, 26.23it/s]

  6%|▌         | 6077/100629 [04:49<1:05:35, 24.02it/s]

  6%|▌         | 6081/100629 [04:49<57:54, 27.21it/s]

  6%|▌         | 6084/100629 [04:49<1:04:37, 24.38it/s]

  6%|▌         | 6088/100629 [04:50<59:21, 26.54it/s]

  6%|▌         | 6092/100629 [04:50<55:08, 28.58it/s]

  6%|▌         | 6095/100629 [04:50<56:15, 28.00it/s]

  6%|▌         | 6098/100629 [04:50<59:09, 26.63it/s]

  6%|▌         | 6101/100629 [04:50<57:28, 27.41it/s]

  6%|▌         | 6104/100629 [04:50<1:05:47, 23.94it/s]

  6%|▌         | 6108/100629 [04:50<1:02:38, 25.15it/s]

  6%|▌         | 6111/100629 [04:50<1:07:40, 23.27it/s]

  6%|▌         | 6114/100629 [04:51<1:07:37, 23.30it/s]

  6%|▌         | 6117/100629 [04:51<1:13:38, 21.39it/s]

  6%|▌         | 6120/100629 [04:51<1:12:43, 21.66it/s]

  6%|▌         | 6123/100629 [04:51<1:10:05, 22.47it/s]

  6%|▌         | 6126/100629 [04:51<1:26:38, 18.18it/s]

  6%|▌         | 6129/100629 [04:51<1:21:39, 19.29it/s]

  6%|▌         | 6132/100629 [04:51<1:17:03, 20.44it/s]

  6%|▌         | 6135/100629 [04:52<1:18:29, 20.06it/s]

  6%|▌         | 6139/100629 [04:52<1:06:25, 23.71it/s]

  6%|▌         | 6142/100629 [04:52<1:13:08, 21.53it/s]

  6%|▌         | 6145/100629 [04:52<1:18:17, 20.11it/s]

  6%|▌         | 6149/100629 [04:52<1:06:38, 23.63it/s]

  6%|▌         | 6152/100629 [04:52<1:13:03, 21.55it/s]

  6%|▌         | 6155/100629 [04:52<1:08:17, 23.06it/s]

  6%|▌         | 6158/100629 [04:53<1:24:22, 18.66it/s]

  6%|▌         | 6162/100629 [04:53<1:17:23, 20.34it/s]

  6%|▌         | 6165/100629 [04:53<1:26:50, 18.13it/s]

  6%|▌         | 6167/100629 [04:53<1:27:01, 18.09it/s]

  6%|▌         | 6170/100629 [04:53<1:18:58, 19.93it/s]

  6%|▌         | 6173/100629 [04:54<1:33:14, 16.88it/s]

  6%|▌         | 6179/100629 [04:54<1:03:12, 24.90it/s]

  6%|▌         | 6182/100629 [04:54<1:10:07, 22.45it/s]

  6%|▌         | 6185/100629 [04:54<1:13:53, 21.30it/s]

  6%|▌         | 6188/100629 [04:54<1:15:16, 20.91it/s]

  6%|▌         | 6191/100629 [04:54<1:14:28, 21.13it/s]

  6%|▌         | 6194/100629 [04:54<1:13:47, 21.33it/s]

  6%|▌         | 6197/100629 [04:55<1:13:41, 21.36it/s]

  6%|▌         | 6200/100629 [04:55<1:13:00, 21.55it/s]

  6%|▌         | 6203/100629 [04:55<1:32:25, 17.03it/s]

  6%|▌         | 6209/100629 [04:55<1:07:51, 23.19it/s]

  6%|▌         | 6212/100629 [04:55<1:15:11, 20.93it/s]

  6%|▌         | 6215/100629 [04:55<1:16:08, 20.67it/s]

  6%|▌         | 6218/100629 [04:56<1:21:11, 19.38it/s]

  6%|▌         | 6221/100629 [04:56<1:14:16, 21.19it/s]

  6%|▌         | 6225/100629 [04:56<1:06:42, 23.58it/s]

  6%|▌         | 6228/100629 [04:56<1:07:38, 23.26it/s]

  6%|▌         | 6231/100629 [04:56<1:12:29, 21.70it/s]

  6%|▌         | 6235/100629 [04:56<1:15:43, 20.78it/s]

  6%|▌         | 6238/100629 [04:57<1:14:00, 21.26it/s]

  6%|▌         | 6241/100629 [04:57<1:28:09, 17.85it/s]

  6%|▌         | 6243/100629 [04:57<1:27:30, 17.98it/s]

  6%|▌         | 6247/100629 [04:57<1:09:32, 22.62it/s]

  6%|▌         | 6250/100629 [04:57<1:15:28, 20.84it/s]

  6%|▌         | 6253/100629 [04:57<1:17:18, 20.34it/s]

  6%|▌         | 6256/100629 [04:57<1:23:48, 18.77it/s]

  6%|▌         | 6258/100629 [04:58<1:22:50, 18.99it/s]

  6%|▌         | 6261/100629 [04:58<1:20:22, 19.57it/s]

  6%|▌         | 6264/100629 [04:58<1:17:43, 20.23it/s]

  6%|▌         | 6268/100629 [04:58<1:15:09, 20.93it/s]

  6%|▌         | 6271/100629 [04:58<1:14:21, 21.15it/s]

  6%|▌         | 6274/100629 [04:58<1:15:31, 20.82it/s]

  6%|▌         | 6277/100629 [04:59<1:21:52, 19.21it/s]

  6%|▌         | 6279/100629 [04:59<1:25:57, 18.29it/s]

  6%|▌         | 6283/100629 [04:59<1:16:14, 20.62it/s]

  6%|▌         | 6286/100629 [04:59<1:31:05, 17.26it/s]

  6%|▌         | 6289/100629 [04:59<1:26:48, 18.11it/s]

  6%|▋         | 6292/100629 [04:59<1:25:02, 18.49it/s]

  6%|▋         | 6295/100629 [04:59<1:17:38, 20.25it/s]

  6%|▋         | 6298/100629 [05:00<1:14:00, 21.24it/s]

  6%|▋         | 6301/100629 [05:00<1:18:10, 20.11it/s]

  6%|▋         | 6305/100629 [05:00<1:05:58, 23.83it/s]

  6%|▋         | 6308/100629 [05:00<1:10:22, 22.34it/s]

  6%|▋         | 6311/100629 [05:00<1:10:03, 22.44it/s]

  6%|▋         | 6314/100629 [05:00<1:20:56, 19.42it/s]

  6%|▋         | 6317/100629 [05:01<1:27:08, 18.04it/s]

  6%|▋         | 6320/100629 [05:01<1:25:15, 18.44it/s]

  6%|▋         | 6322/100629 [05:01<1:26:42, 18.13it/s]

  6%|▋         | 6325/100629 [05:01<1:17:41, 20.23it/s]

  6%|▋         | 6328/100629 [05:01<1:15:25, 20.84it/s]

  6%|▋         | 6331/100629 [05:01<1:10:14, 22.37it/s]

  6%|▋         | 6334/100629 [05:01<1:19:26, 19.78it/s]

  6%|▋         | 6337/100629 [05:02<1:18:06, 20.12it/s]

  6%|▋         | 6341/100629 [05:02<1:07:10, 23.39it/s]

  6%|▋         | 6344/100629 [05:02<1:09:25, 22.64it/s]

  6%|▋         | 6347/100629 [05:02<1:09:29, 22.61it/s]

  6%|▋         | 6350/100629 [05:02<1:11:57, 21.84it/s]

  6%|▋         | 6354/100629 [05:02<1:01:40, 25.48it/s]

  6%|▋         | 6357/100629 [05:02<1:03:24, 24.78it/s]

  6%|▋         | 6361/100629 [05:02<1:01:08, 25.70it/s]

  6%|▋         | 6364/100629 [05:03<1:03:08, 24.88it/s]

  6%|▋         | 6367/100629 [05:03<1:05:41, 23.92it/s]

  6%|▋         | 6370/100629 [05:03<1:13:34, 21.35it/s]

  6%|▋         | 6373/100629 [05:03<1:09:51, 22.49it/s]

  6%|▋         | 6376/100629 [05:03<1:32:23, 17.00it/s]

  6%|▋         | 6379/100629 [05:03<1:22:11, 19.11it/s]

  6%|▋         | 6382/100629 [05:04<1:20:04, 19.62it/s]

  6%|▋         | 6385/100629 [05:04<1:21:48, 19.20it/s]

  6%|▋         | 6388/100629 [05:04<1:20:06, 19.61it/s]

  6%|▋         | 6393/100629 [05:04<1:04:52, 24.21it/s]

  6%|▋         | 6396/100629 [05:04<1:09:08, 22.71it/s]

  6%|▋         | 6399/100629 [05:04<1:12:26, 21.68it/s]

  6%|▋         | 6402/100629 [05:04<1:11:21, 22.01it/s]

  6%|▋         | 6405/100629 [05:05<1:27:58, 17.85it/s]

  6%|▋         | 6409/100629 [05:05<1:20:50, 19.42it/s]

  6%|▋         | 6412/100629 [05:05<1:17:49, 20.18it/s]

  6%|▋         | 6415/100629 [05:05<1:21:39, 19.23it/s]

  6%|▋         | 6417/100629 [05:05<1:26:32, 18.15it/s]

  6%|▋         | 6419/100629 [05:05<1:31:15, 17.21it/s]

  6%|▋         | 6425/100629 [05:06<1:09:23, 22.63it/s]

  6%|▋         | 6428/100629 [05:06<1:15:34, 20.77it/s]

  6%|▋         | 6432/100629 [05:06<1:08:00, 23.09it/s]

  6%|▋         | 6435/100629 [05:06<1:18:54, 19.90it/s]

  6%|▋         | 6438/100629 [05:06<1:15:34, 20.77it/s]

  6%|▋         | 6441/100629 [05:06<1:15:15, 20.86it/s]

  6%|▋         | 6444/100629 [05:07<1:14:29, 21.07it/s]

  6%|▋         | 6447/100629 [05:07<1:12:18, 21.71it/s]

  6%|▋         | 6450/100629 [05:07<1:22:49, 18.95it/s]

  6%|▋         | 6453/100629 [05:07<1:17:14, 20.32it/s]

  6%|▋         | 6456/100629 [05:07<1:13:59, 21.21it/s]

  6%|▋         | 6459/100629 [05:07<1:16:55, 20.40it/s]

  6%|▋         | 6462/100629 [05:07<1:12:04, 21.78it/s]

  6%|▋         | 6465/100629 [05:08<1:21:04, 19.36it/s]

  6%|▋         | 6468/100629 [05:08<1:24:03, 18.67it/s]

  6%|▋         | 6472/100629 [05:08<1:08:47, 22.81it/s]

  6%|▋         | 6475/100629 [05:08<1:10:47, 22.16it/s]

  6%|▋         | 6478/100629 [05:08<1:06:02, 23.76it/s]

  6%|▋         | 6481/100629 [05:08<1:05:27, 23.97it/s]

  6%|▋         | 6484/100629 [05:09<1:29:47, 17.48it/s]

  6%|▋         | 6487/100629 [05:09<1:27:50, 17.86it/s]

  6%|▋         | 6490/100629 [05:09<1:22:07, 19.11it/s]

  6%|▋         | 6493/100629 [05:09<1:13:29, 21.35it/s]

  6%|▋         | 6497/100629 [05:09<1:02:18, 25.18it/s]

  6%|▋         | 6500/100629 [05:09<1:13:29, 21.35it/s]

  6%|▋         | 6503/100629 [05:09<1:25:34, 18.33it/s]

  6%|▋         | 6507/100629 [05:10<1:09:24, 22.60it/s]

  6%|▋         | 6510/100629 [05:10<1:11:53, 21.82it/s]

  6%|▋         | 6513/100629 [05:10<1:12:34, 21.61it/s]

  6%|▋         | 6516/100629 [05:10<1:13:57, 21.21it/s]

  6%|▋         | 6519/100629 [05:10<1:23:01, 18.89it/s]

  6%|▋         | 6522/100629 [05:10<1:20:44, 19.43it/s]

  6%|▋         | 6527/100629 [05:10<1:04:03, 24.48it/s]

  6%|▋         | 6530/100629 [05:11<1:14:18, 21.10it/s]

  6%|▋         | 6535/100629 [05:11<1:11:12, 22.02it/s]

  6%|▋         | 6538/100629 [05:11<1:22:08, 19.09it/s]

  7%|▋         | 6542/100629 [05:11<1:12:53, 21.51it/s]

  7%|▋         | 6545/100629 [05:11<1:21:24, 19.26it/s]

  7%|▋         | 6548/100629 [05:12<1:14:35, 21.02it/s]

  7%|▋         | 6551/100629 [05:12<1:08:42, 22.82it/s]

  7%|▋         | 6556/100629 [05:12<1:02:38, 25.03it/s]

  7%|▋         | 6559/100629 [05:12<1:12:01, 21.77it/s]

  7%|▋         | 6562/100629 [05:12<1:10:50, 22.13it/s]

  7%|▋         | 6565/100629 [05:12<1:08:01, 23.05it/s]

  7%|▋         | 6568/100629 [05:12<1:09:06, 22.68it/s]

  7%|▋         | 6571/100629 [05:13<1:12:03, 21.75it/s]

  7%|▋         | 6576/100629 [05:13<1:03:00, 24.88it/s]

  7%|▋         | 6579/100629 [05:13<1:04:02, 24.48it/s]

  7%|▋         | 6583/100629 [05:13<1:02:47, 24.96it/s]

  7%|▋         | 6587/100629 [05:13<1:00:09, 26.05it/s]

  7%|▋         | 6590/100629 [05:13<59:37, 26.28it/s]

  7%|▋         | 6594/100629 [05:13<56:21, 27.80it/s]

  7%|▋         | 6598/100629 [05:13<54:43, 28.64it/s]

  7%|▋         | 6601/100629 [05:14<1:08:47, 22.78it/s]

  7%|▋         | 6604/100629 [05:14<1:14:21, 21.08it/s]

  7%|▋         | 6607/100629 [05:14<1:16:03, 20.60it/s]

  7%|▋         | 6610/100629 [05:14<1:16:01, 20.61it/s]

  7%|▋         | 6615/100629 [05:14<58:41, 26.70it/s]

  7%|▋         | 6618/100629 [05:14<1:10:21, 22.27it/s]

  7%|▋         | 6621/100629 [05:15<1:15:21, 20.79it/s]

  7%|▋         | 6626/100629 [05:15<1:02:20, 25.13it/s]

  7%|▋         | 6629/100629 [05:15<1:00:07, 26.06it/s]

  7%|▋         | 6632/100629 [05:15<1:00:08, 26.05it/s]

  7%|▋         | 6635/100629 [05:15<58:22, 26.84it/s]

  7%|▋         | 6638/100629 [05:15<1:00:52, 25.73it/s]

  7%|▋         | 6641/100629 [05:15<1:04:34, 24.26it/s]

  7%|▋         | 6644/100629 [05:15<1:02:50, 24.93it/s]

  7%|▋         | 6647/100629 [05:16<1:00:30, 25.89it/s]

  7%|▋         | 6650/100629 [05:16<1:07:23, 23.24it/s]

  7%|▋         | 6653/100629 [05:16<1:08:13, 22.96it/s]

  7%|▋         | 6658/100629 [05:16<55:39, 28.14it/s]

  7%|▋         | 6661/100629 [05:16<1:03:35, 24.63it/s]

  7%|▋         | 6664/100629 [05:16<1:02:50, 24.92it/s]

  7%|▋         | 6667/100629 [05:16<1:03:26, 24.69it/s]

  7%|▋         | 6670/100629 [05:17<1:11:21, 21.94it/s]

  7%|▋         | 6674/100629 [05:17<1:06:02, 23.71it/s]

  7%|▋         | 6678/100629 [05:17<1:02:37, 25.00it/s]

  7%|▋         | 6681/100629 [05:17<1:08:04, 23.00it/s]

  7%|▋         | 6684/100629 [05:17<1:09:44, 22.45it/s]

  7%|▋         | 6687/100629 [05:17<1:17:04, 20.31it/s]

  7%|▋         | 6690/100629 [05:18<1:32:51, 16.86it/s]

  7%|▋         | 6693/100629 [05:18<1:36:01, 16.30it/s]

  7%|▋         | 6697/100629 [05:18<1:20:41, 19.40it/s]

  7%|▋         | 6700/100629 [05:18<1:21:06, 19.30it/s]

  7%|▋         | 6703/100629 [05:18<1:16:50, 20.37it/s]

  7%|▋         | 6706/100629 [05:18<1:26:06, 18.18it/s]

  7%|▋         | 6708/100629 [05:19<1:31:59, 17.02it/s]

  7%|▋         | 6711/100629 [05:19<1:31:39, 17.08it/s]

  7%|▋         | 6713/100629 [05:19<1:46:59, 14.63it/s]

  7%|▋         | 6716/100629 [05:19<1:35:19, 16.42it/s]

  7%|▋         | 6718/100629 [05:19<1:34:28, 16.57it/s]

  7%|▋         | 6721/100629 [05:19<1:20:48, 19.37it/s]

  7%|▋         | 6724/100629 [05:20<1:31:13, 17.16it/s]

  7%|▋         | 6727/100629 [05:20<1:21:37, 19.17it/s]

  7%|▋         | 6730/100629 [05:20<1:13:09, 21.39it/s]

  7%|▋         | 6733/100629 [05:20<1:27:17, 17.93it/s]

  7%|▋         | 6736/100629 [05:20<1:30:12, 17.35it/s]

  7%|▋         | 6739/100629 [05:20<1:32:50, 16.86it/s]

  7%|▋         | 6742/100629 [05:20<1:22:46, 18.90it/s]

  7%|▋         | 6745/100629 [05:21<1:14:26, 21.02it/s]

  7%|▋         | 6748/100629 [05:21<1:22:17, 19.02it/s]

  7%|▋         | 6751/100629 [05:21<1:20:21, 19.47it/s]

  7%|▋         | 6754/100629 [05:21<1:18:02, 20.05it/s]

  7%|▋         | 6757/100629 [05:21<1:20:26, 19.45it/s]

  7%|▋         | 6760/100629 [05:21<1:23:02, 18.84it/s]

  7%|▋         | 6764/100629 [05:22<1:07:40, 23.12it/s]

  7%|▋         | 6767/100629 [05:22<1:17:41, 20.14it/s]

  7%|▋         | 6772/100629 [05:22<1:01:03, 25.62it/s]

  7%|▋         | 6776/100629 [05:22<57:20, 27.28it/s]

  7%|▋         | 6779/100629 [05:22<1:05:48, 23.77it/s]

  7%|▋         | 6783/100629 [05:22<1:00:55, 25.67it/s]

  7%|▋         | 6786/100629 [05:22<59:40, 26.21it/s]

  7%|▋         | 6791/100629 [05:22<50:22, 31.05it/s]

  7%|▋         | 6797/100629 [05:23<48:14, 32.41it/s]

  7%|▋         | 6801/100629 [05:23<1:06:17, 23.59it/s]

  7%|▋         | 6804/100629 [05:23<1:11:37, 21.83it/s]

  7%|▋         | 6808/100629 [05:23<1:07:32, 23.15it/s]

  7%|▋         | 6813/100629 [05:23<1:00:37, 25.79it/s]

  7%|▋         | 6817/100629 [05:24<54:50, 28.51it/s]

  7%|▋         | 6821/100629 [05:24<52:06, 30.01it/s]

  7%|▋         | 6825/100629 [05:24<1:07:15, 23.24it/s]

  7%|▋         | 6828/100629 [05:24<1:20:51, 19.34it/s]

  7%|▋         | 6831/100629 [05:24<1:14:50, 20.89it/s]

  7%|▋         | 6834/100629 [05:24<1:09:36, 22.46it/s]

  7%|▋         | 6837/100629 [05:24<1:09:55, 22.36it/s]

  7%|▋         | 6840/100629 [05:25<1:16:05, 20.54it/s]

  7%|▋         | 6843/100629 [05:25<1:10:06, 22.30it/s]

  7%|▋         | 6846/100629 [05:25<1:40:10, 15.60it/s]

  7%|▋         | 6848/100629 [05:25<1:45:10, 14.86it/s]

  7%|▋         | 6851/100629 [05:25<1:34:31, 16.54it/s]

  7%|▋         | 6854/100629 [05:26<1:23:54, 18.63it/s]

  7%|▋         | 6857/100629 [05:26<1:31:05, 17.16it/s]

  7%|▋         | 6861/100629 [05:26<1:16:58, 20.30it/s]

  7%|▋         | 6864/100629 [05:26<1:11:50, 21.75it/s]

  7%|▋         | 6867/100629 [05:26<1:12:18, 21.61it/s]

  7%|▋         | 6870/100629 [05:26<1:13:37, 21.22it/s]

  7%|▋         | 6874/100629 [05:26<1:05:30, 23.86it/s]

  7%|▋         | 6877/100629 [05:27<1:09:11, 22.58it/s]

  7%|▋         | 6880/100629 [05:27<1:24:58, 18.39it/s]

  7%|▋         | 6883/100629 [05:27<1:17:20, 20.20it/s]

  7%|▋         | 6886/100629 [05:27<1:14:36, 20.94it/s]

  7%|▋         | 6889/100629 [05:27<1:22:17, 18.98it/s]

  7%|▋         | 6892/100629 [05:27<1:26:07, 18.14it/s]

  7%|▋         | 6895/100629 [05:28<1:25:23, 18.30it/s]

  7%|▋         | 6899/100629 [05:28<1:18:53, 19.80it/s]

  7%|▋         | 6903/100629 [05:28<1:12:04, 21.68it/s]

  7%|▋         | 6906/100629 [05:28<1:10:09, 22.26it/s]

  7%|▋         | 6909/100629 [05:28<1:13:32, 21.24it/s]

  7%|▋         | 6913/100629 [05:28<1:07:15, 23.22it/s]

  7%|▋         | 6917/100629 [05:28<58:00, 26.93it/s]

  7%|▋         | 6920/100629 [05:29<1:02:19, 25.06it/s]

  7%|▋         | 6923/100629 [05:29<1:15:24, 20.71it/s]

  7%|▋         | 6926/100629 [05:29<1:15:03, 20.81it/s]

  7%|▋         | 6929/100629 [05:29<1:15:43, 20.62it/s]

  7%|▋         | 6932/100629 [05:29<1:12:56, 21.41it/s]

  7%|▋         | 6935/100629 [05:29<1:15:50, 20.59it/s]

  7%|▋         | 6938/100629 [05:29<1:14:06, 21.07it/s]

  7%|▋         | 6941/100629 [05:30<1:13:59, 21.10it/s]

  7%|▋         | 6944/100629 [05:30<1:11:25, 21.86it/s]

  7%|▋         | 6947/100629 [05:30<1:15:09, 20.77it/s]

  7%|▋         | 6950/100629 [05:30<1:12:50, 21.44it/s]

  7%|▋         | 6953/100629 [05:30<1:14:32, 20.95it/s]

  7%|▋         | 6956/100629 [05:30<1:15:54, 20.57it/s]

  7%|▋         | 6960/100629 [05:30<1:07:10, 23.24it/s]

  7%|▋         | 6963/100629 [05:31<1:14:39, 20.91it/s]

  7%|▋         | 6966/100629 [05:31<1:16:24, 20.43it/s]

  7%|▋         | 6969/100629 [05:31<1:24:08, 18.55it/s]

  7%|▋         | 6972/100629 [05:31<1:16:29, 20.41it/s]

  7%|▋         | 6976/100629 [05:31<1:04:10, 24.32it/s]

  7%|▋         | 6979/100629 [05:31<1:09:50, 22.35it/s]

  7%|▋         | 6983/100629 [05:32<1:06:40, 23.41it/s]

  7%|▋         | 6986/100629 [05:32<1:10:11, 22.23it/s]

  7%|▋         | 6990/100629 [05:32<1:08:17, 22.85it/s]

  7%|▋         | 6993/100629 [05:32<1:05:39, 23.77it/s]

  7%|▋         | 6996/100629 [05:32<1:13:47, 21.15it/s]

  7%|▋         | 6999/100629 [05:32<1:12:15, 21.60it/s]

  7%|▋         | 7002/100629 [05:32<1:10:53, 22.01it/s]

  7%|▋         | 7005/100629 [05:33<1:06:50, 23.35it/s]

  7%|▋         | 7008/100629 [05:33<1:08:11, 22.88it/s]

  7%|▋         | 7011/100629 [05:33<1:15:52, 20.57it/s]

  7%|▋         | 7015/100629 [05:33<1:11:30, 21.82it/s]

  7%|▋         | 7018/100629 [05:33<1:07:48, 23.01it/s]

  7%|▋         | 7021/100629 [05:33<1:27:08, 17.90it/s]

  7%|▋         | 7023/100629 [05:33<1:25:26, 18.26it/s]

  7%|▋         | 7027/100629 [05:34<1:14:00, 21.08it/s]

  7%|▋         | 7030/100629 [05:34<1:11:33, 21.80it/s]

  7%|▋         | 7033/100629 [05:34<1:10:49, 22.02it/s]

  7%|▋         | 7036/100629 [05:34<1:19:58, 19.50it/s]

  7%|▋         | 7039/100629 [05:34<1:14:23, 20.97it/s]

  7%|▋         | 7042/100629 [05:34<1:10:04, 22.26it/s]

  7%|▋         | 7046/100629 [05:34<59:49, 26.07it/s]

  7%|▋         | 7049/100629 [05:35<1:17:13, 20.19it/s]

  7%|▋         | 7052/100629 [05:35<1:24:49, 18.38it/s]

  7%|▋         | 7056/100629 [05:35<1:12:13, 21.59it/s]

  7%|▋         | 7060/100629 [05:35<1:02:06, 25.11it/s]

  7%|▋         | 7063/100629 [05:35<1:04:41, 24.11it/s]

  7%|▋         | 7067/100629 [05:35<57:58, 26.89it/s]

  7%|▋         | 7070/100629 [05:35<1:02:31, 24.94it/s]

  7%|▋         | 7073/100629 [05:36<1:05:47, 23.70it/s]

  7%|▋         | 7076/100629 [05:36<1:14:28, 20.94it/s]

  7%|▋         | 7079/100629 [05:36<1:10:24, 22.15it/s]

  7%|▋         | 7083/100629 [05:36<1:09:14, 22.51it/s]

  7%|▋         | 7087/100629 [05:36<1:03:44, 24.46it/s]

  7%|▋         | 7090/100629 [05:36<1:03:23, 24.59it/s]

  7%|▋         | 7093/100629 [05:36<1:05:26, 23.82it/s]

  7%|▋         | 7096/100629 [05:37<1:08:10, 22.87it/s]

  7%|▋         | 7099/100629 [05:37<1:12:06, 21.62it/s]

  7%|▋         | 7102/100629 [05:37<1:08:22, 22.80it/s]

  7%|▋         | 7106/100629 [05:37<57:56, 26.90it/s]

  7%|▋         | 7109/100629 [05:37<1:05:20, 23.85it/s]

  7%|▋         | 7112/100629 [05:37<1:10:50, 22.00it/s]

  7%|▋         | 7115/100629 [05:37<1:14:51, 20.82it/s]

  7%|▋         | 7118/100629 [05:38<1:12:11, 21.59it/s]

  7%|▋         | 7121/100629 [05:38<1:13:51, 21.10it/s]

  7%|▋         | 7124/100629 [05:38<1:13:56, 21.08it/s]

  7%|▋         | 7127/100629 [05:38<1:17:17, 20.16it/s]

  7%|▋         | 7130/100629 [05:38<1:20:24, 19.38it/s]

  7%|▋         | 7133/100629 [05:38<1:18:19, 19.89it/s]

  7%|▋         | 7136/100629 [05:39<1:14:14, 20.99it/s]

  7%|▋         | 7139/100629 [05:39<1:20:01, 19.47it/s]

  7%|▋         | 7141/100629 [05:39<1:21:21, 19.15it/s]

  7%|▋         | 7144/100629 [05:39<1:26:35, 17.99it/s]

  7%|▋         | 7146/100629 [05:39<1:41:45, 15.31it/s]

  7%|▋         | 7150/100629 [05:39<1:23:57, 18.56it/s]

  7%|▋         | 7153/100629 [05:39<1:19:15, 19.65it/s]

  7%|▋         | 7156/100629 [05:40<1:12:54, 21.37it/s]

  7%|▋         | 7160/100629 [05:40<1:07:10, 23.19it/s]

  7%|▋         | 7164/100629 [05:40<1:01:43, 25.24it/s]

  7%|▋         | 7167/100629 [05:40<1:03:58, 24.35it/s]

  7%|▋         | 7170/100629 [05:40<1:01:03, 25.51it/s]

  7%|▋         | 7173/100629 [05:40<59:34, 26.15it/s]

  7%|▋         | 7176/100629 [05:40<1:08:35, 22.71it/s]

  7%|▋         | 7179/100629 [05:41<1:08:10, 22.85it/s]

  7%|▋         | 7182/100629 [05:41<1:16:30, 20.36it/s]

  7%|▋         | 7185/100629 [05:41<1:14:24, 20.93it/s]

  7%|▋         | 7188/100629 [05:41<1:08:24, 22.77it/s]

  7%|▋         | 7191/100629 [05:41<1:16:39, 20.32it/s]

  7%|▋         | 7196/100629 [05:41<1:00:16, 25.83it/s]

  7%|▋         | 7199/100629 [05:41<1:04:28, 24.15it/s]

  7%|▋         | 7202/100629 [05:42<1:04:22, 24.19it/s]

  7%|▋         | 7205/100629 [05:42<1:08:02, 22.88it/s]

  7%|▋         | 7208/100629 [05:42<1:04:17, 24.22it/s]

  7%|▋         | 7212/100629 [05:42<1:03:36, 24.48it/s]

  7%|▋         | 7215/100629 [05:42<1:11:12, 21.86it/s]

  7%|▋         | 7218/100629 [05:42<1:17:00, 20.22it/s]

  7%|▋         | 7221/100629 [05:42<1:19:31, 19.58it/s]

  7%|▋         | 7224/100629 [05:43<1:20:18, 19.39it/s]

  7%|▋         | 7226/100629 [05:43<1:24:35, 18.40it/s]

  7%|▋         | 7230/100629 [05:43<1:16:11, 20.43it/s]

  7%|▋         | 7233/100629 [05:43<1:14:01, 21.03it/s]

  7%|▋         | 7236/100629 [05:43<1:18:53, 19.73it/s]

  7%|▋         | 7239/100629 [05:43<1:14:17, 20.95it/s]

  7%|▋         | 7242/100629 [05:43<1:08:16, 22.80it/s]

  7%|▋         | 7245/100629 [05:44<1:16:23, 20.37it/s]

  7%|▋         | 7249/100629 [05:44<1:05:36, 23.72it/s]

  7%|▋         | 7253/100629 [05:44<1:01:02, 25.50it/s]

  7%|▋         | 7256/100629 [05:44<1:05:51, 23.63it/s]

  7%|▋         | 7259/100629 [05:44<1:04:32, 24.11it/s]

  7%|▋         | 7262/100629 [05:44<1:06:23, 23.44it/s]

  7%|▋         | 7265/100629 [05:45<1:33:30, 16.64it/s]

  7%|▋         | 7267/100629 [05:45<1:31:03, 17.09it/s]

  7%|▋         | 7270/100629 [05:45<1:54:11, 13.63it/s]

  7%|▋         | 7273/100629 [05:45<1:39:27, 15.64it/s]

  7%|▋         | 7276/100629 [05:45<1:25:11, 18.26it/s]

  7%|▋         | 7279/100629 [05:45<1:29:51, 17.31it/s]

  7%|▋         | 7283/100629 [05:46<1:21:06, 19.18it/s]

  7%|▋         | 7286/100629 [05:46<1:13:28, 21.17it/s]

  7%|▋         | 7289/100629 [05:46<1:11:36, 21.73it/s]

  7%|▋         | 7292/100629 [05:46<1:16:35, 20.31it/s]

  7%|▋         | 7295/100629 [05:46<1:19:11, 19.65it/s]

  7%|▋         | 7298/100629 [05:46<1:14:13, 20.96it/s]

  7%|▋         | 7302/100629 [05:46<1:10:32, 22.05it/s]

  7%|▋         | 7306/100629 [05:47<1:05:57, 23.58it/s]

  7%|▋         | 7310/100629 [05:47<58:01, 26.80it/s]

  7%|▋         | 7313/100629 [05:47<58:33, 26.56it/s]

  7%|▋         | 7316/100629 [05:47<1:13:25, 21.18it/s]

  7%|▋         | 7319/100629 [05:47<1:16:59, 20.20it/s]

  7%|▋         | 7322/100629 [05:47<1:33:04, 16.71it/s]

  7%|▋         | 7326/100629 [05:48<1:15:59, 20.46it/s]

  7%|▋         | 7330/100629 [05:48<1:10:51, 21.94it/s]

  7%|▋         | 7333/100629 [05:48<1:12:08, 21.56it/s]

  7%|▋         | 7336/100629 [05:48<1:10:02, 22.20it/s]

  7%|▋         | 7339/100629 [05:48<1:14:03, 20.99it/s]

  7%|▋         | 7342/100629 [05:48<1:14:53, 20.76it/s]

  7%|▋         | 7345/100629 [05:48<1:15:00, 20.73it/s]

  7%|▋         | 7348/100629 [05:49<1:13:50, 21.06it/s]

  7%|▋         | 7352/100629 [05:49<1:08:32, 22.68it/s]

  7%|▋         | 7355/100629 [05:49<1:09:44, 22.29it/s]

  7%|▋         | 7358/100629 [05:49<1:25:28, 18.19it/s]

  7%|▋         | 7360/100629 [05:49<1:47:16, 14.49it/s]

  7%|▋         | 7362/100629 [05:50<1:58:39, 13.10it/s]

  7%|▋         | 7365/100629 [05:50<1:48:34, 14.32it/s]

  7%|▋         | 7368/100629 [05:50<1:30:29, 17.18it/s]

  7%|▋         | 7370/100629 [05:50<1:34:04, 16.52it/s]

  7%|▋         | 7373/100629 [05:50<1:20:49, 19.23it/s]

  7%|▋         | 7376/100629 [05:50<1:23:45, 18.56it/s]

  7%|▋         | 7379/100629 [05:51<1:40:09, 15.52it/s]

  7%|▋         | 7381/100629 [05:51<1:38:53, 15.72it/s]

  7%|▋         | 7385/100629 [05:51<1:20:45, 19.24it/s]

  7%|▋         | 7388/100629 [05:51<1:24:43, 18.34it/s]

  7%|▋         | 7392/100629 [05:51<1:09:09, 22.47it/s]

  7%|▋         | 7395/100629 [05:51<1:19:16, 19.60it/s]

  7%|▋         | 7398/100629 [05:51<1:28:04, 17.64it/s]

  7%|▋         | 7400/100629 [05:52<1:31:22, 17.00it/s]

  7%|▋         | 7402/100629 [05:52<1:30:09, 17.24it/s]

  7%|▋         | 7404/100629 [05:52<1:31:48, 16.92it/s]

  7%|▋         | 7406/100629 [05:52<1:43:19, 15.04it/s]

  7%|▋         | 7409/100629 [05:52<1:27:32, 17.75it/s]

  7%|▋         | 7411/100629 [05:52<1:35:36, 16.25it/s]

  7%|▋         | 7413/100629 [05:52<1:39:50, 15.56it/s]

  7%|▋         | 7415/100629 [05:53<1:34:48, 16.39it/s]

  7%|▋         | 7417/100629 [05:53<1:42:11, 15.20it/s]

  7%|▋         | 7420/100629 [05:53<1:33:37, 16.59it/s]

  7%|▋         | 7422/100629 [05:53<2:04:40, 12.46it/s]

  7%|▋         | 7426/100629 [05:53<1:32:11, 16.85it/s]

  7%|▋         | 7429/100629 [05:53<1:20:34, 19.28it/s]

  7%|▋         | 7432/100629 [05:54<1:21:42, 19.01it/s]

  7%|▋         | 7435/100629 [05:54<1:18:44, 19.73it/s]

  7%|▋         | 7438/100629 [05:54<1:14:45, 20.77it/s]

  7%|▋         | 7441/100629 [05:54<1:21:30, 19.05it/s]

  7%|▋         | 7444/100629 [05:54<1:14:58, 20.72it/s]

  7%|▋         | 7447/100629 [05:54<1:18:51, 19.69it/s]

  7%|▋         | 7450/100629 [05:55<1:39:11, 15.66it/s]

  7%|▋         | 7454/100629 [05:55<1:20:17, 19.34it/s]

  7%|▋         | 7457/100629 [05:55<1:25:54, 18.08it/s]

  7%|▋         | 7460/100629 [05:55<1:27:13, 17.80it/s]

  7%|▋         | 7464/100629 [05:55<1:11:01, 21.86it/s]

  7%|▋         | 7467/100629 [05:55<1:16:23, 20.33it/s]

  7%|▋         | 7470/100629 [05:55<1:19:11, 19.60it/s]

  7%|▋         | 7473/100629 [05:56<1:20:07, 19.38it/s]

  7%|▋         | 7476/100629 [05:56<1:13:45, 21.05it/s]

  7%|▋         | 7479/100629 [05:56<1:15:15, 20.63it/s]

  7%|▋         | 7482/100629 [05:56<1:19:46, 19.46it/s]

  7%|▋         | 7485/100629 [05:56<1:23:13, 18.65it/s]

  7%|▋         | 7488/100629 [05:56<1:24:07, 18.45it/s]

  7%|▋         | 7492/100629 [05:57<1:10:28, 22.02it/s]

  7%|▋         | 7497/100629 [05:57<1:02:28, 24.85it/s]

  7%|▋         | 7502/100629 [05:57<53:09, 29.20it/s]

  7%|▋         | 7506/100629 [05:57<51:10, 30.33it/s]

  7%|▋         | 7511/100629 [05:57<44:58, 34.50it/s]

  7%|▋         | 7515/100629 [05:57<45:26, 34.16it/s]

  7%|▋         | 7519/100629 [05:57<53:34, 28.97it/s]

  7%|▋         | 7523/100629 [05:58<58:32, 26.51it/s]

  7%|▋         | 7526/100629 [05:58<1:00:24, 25.69it/s]

  7%|▋         | 7529/100629 [05:58<1:03:13, 24.54it/s]

  7%|▋         | 7532/100629 [05:58<1:09:35, 22.30it/s]

  7%|▋         | 7535/100629 [05:58<1:14:50, 20.73it/s]

  7%|▋         | 7538/100629 [05:58<1:13:18, 21.16it/s]

  7%|▋         | 7542/100629 [05:58<1:05:36, 23.65it/s]

  7%|▋         | 7545/100629 [05:59<1:07:45, 22.90it/s]

  8%|▊         | 7552/100629 [05:59<46:09, 33.60it/s]

  8%|▊         | 7556/100629 [05:59<55:55, 27.74it/s]

  8%|▊         | 7560/100629 [05:59<1:06:20, 23.38it/s]

  8%|▊         | 7563/100629 [05:59<1:08:01, 22.80it/s]

  8%|▊         | 7566/100629 [05:59<1:20:10, 19.35it/s]

  8%|▊         | 7569/100629 [06:00<1:14:54, 20.70it/s]

  8%|▊         | 7572/100629 [06:00<1:09:50, 22.21it/s]

  8%|▊         | 7575/100629 [06:00<1:16:57, 20.15it/s]

  8%|▊         | 7578/100629 [06:00<1:10:20, 22.05it/s]

  8%|▊         | 7582/100629 [06:00<1:03:15, 24.51it/s]

  8%|▊         | 7585/100629 [06:00<1:20:14, 19.32it/s]

  8%|▊         | 7588/100629 [06:01<1:29:39, 17.30it/s]

  8%|▊         | 7590/100629 [06:01<1:28:34, 17.51it/s]

  8%|▊         | 7592/100629 [06:01<1:29:33, 17.31it/s]

  8%|▊         | 7594/100629 [06:01<1:52:16, 13.81it/s]

  8%|▊         | 7597/100629 [06:01<1:36:31, 16.06it/s]

  8%|▊         | 7599/100629 [06:01<1:36:49, 16.01it/s]

  8%|▊         | 7603/100629 [06:01<1:16:15, 20.33it/s]

  8%|▊         | 7607/100629 [06:02<1:09:39, 22.26it/s]

  8%|▊         | 7611/100629 [06:02<1:07:02, 23.12it/s]

  8%|▊         | 7614/100629 [06:02<1:08:04, 22.77it/s]

  8%|▊         | 7617/100629 [06:02<1:18:05, 19.85it/s]

  8%|▊         | 7620/100629 [06:02<1:15:28, 20.54it/s]

  8%|▊         | 7623/100629 [06:02<1:12:37, 21.34it/s]

  8%|▊         | 7627/100629 [06:03<1:11:23, 21.71it/s]

  8%|▊         | 7631/100629 [06:03<1:03:10, 24.53it/s]

  8%|▊         | 7634/100629 [06:03<1:08:20, 22.68it/s]

  8%|▊         | 7637/100629 [06:03<1:04:34, 24.00it/s]

  8%|▊         | 7641/100629 [06:03<58:16, 26.59it/s]

  8%|▊         | 7644/100629 [06:03<1:06:03, 23.46it/s]

  8%|▊         | 7647/100629 [06:03<1:06:25, 23.33it/s]

  8%|▊         | 7650/100629 [06:03<1:08:49, 22.51it/s]

  8%|▊         | 7653/100629 [06:04<1:12:08, 21.48it/s]

  8%|▊         | 7656/100629 [06:04<1:21:52, 18.93it/s]

  8%|▊         | 7659/100629 [06:04<1:13:00, 21.22it/s]

  8%|▊         | 7662/100629 [06:04<1:19:37, 19.46it/s]

  8%|▊         | 7666/100629 [06:04<1:10:25, 22.00it/s]

  8%|▊         | 7669/100629 [06:04<1:12:57, 21.23it/s]

  8%|▊         | 7672/100629 [06:05<1:13:04, 21.20it/s]

  8%|▊         | 7676/100629 [06:05<1:03:05, 24.56it/s]

  8%|▊         | 7679/100629 [06:05<1:08:56, 22.47it/s]

  8%|▊         | 7682/100629 [06:05<1:04:45, 23.92it/s]

  8%|▊         | 7685/100629 [06:05<1:10:41, 21.91it/s]

  8%|▊         | 7688/100629 [06:05<1:08:16, 22.69it/s]

  8%|▊         | 7692/100629 [06:05<58:19, 26.56it/s]

  8%|▊         | 7695/100629 [06:05<1:03:05, 24.55it/s]

  8%|▊         | 7698/100629 [06:06<1:09:01, 22.44it/s]

  8%|▊         | 7701/100629 [06:06<1:06:38, 23.24it/s]

  8%|▊         | 7704/100629 [06:06<1:16:07, 20.34it/s]

  8%|▊         | 7707/100629 [06:06<1:15:27, 20.52it/s]

  8%|▊         | 7710/100629 [06:06<1:12:24, 21.39it/s]

  8%|▊         | 7713/100629 [06:06<1:18:17, 19.78it/s]

  8%|▊         | 7716/100629 [06:06<1:11:03, 21.79it/s]

  8%|▊         | 7720/100629 [06:07<1:01:11, 25.31it/s]

  8%|▊         | 7723/100629 [06:07<1:06:44, 23.20it/s]

  8%|▊         | 7727/100629 [06:07<58:31, 26.46it/s]

  8%|▊         | 7730/100629 [06:07<1:09:07, 22.40it/s]

  8%|▊         | 7733/100629 [06:07<1:15:49, 20.42it/s]

  8%|▊         | 7738/100629 [06:07<58:03, 26.67it/s]

  8%|▊         | 7742/100629 [06:08<1:06:16, 23.36it/s]

  8%|▊         | 7745/100629 [06:08<1:12:02, 21.49it/s]

  8%|▊         | 7748/100629 [06:08<1:21:52, 18.91it/s]

  8%|▊         | 7752/100629 [06:08<1:11:14, 21.73it/s]

  8%|▊         | 7755/100629 [06:08<1:18:14, 19.78it/s]

  8%|▊         | 7759/100629 [06:08<1:12:33, 21.33it/s]

  8%|▊         | 7762/100629 [06:09<1:10:06, 22.08it/s]

  8%|▊         | 7765/100629 [06:09<1:06:05, 23.42it/s]

  8%|▊         | 7768/100629 [06:09<1:07:55, 22.79it/s]

  8%|▊         | 7772/100629 [06:09<1:03:34, 24.35it/s]

  8%|▊         | 7775/100629 [06:09<1:06:34, 23.24it/s]

  8%|▊         | 7778/100629 [06:09<1:06:08, 23.39it/s]

  8%|▊         | 7781/100629 [06:09<1:05:01, 23.80it/s]

  8%|▊         | 7784/100629 [06:09<1:11:09, 21.75it/s]

  8%|▊         | 7787/100629 [06:10<1:18:57, 19.60it/s]

  8%|▊         | 7790/100629 [06:10<1:17:12, 20.04it/s]

  8%|▊         | 7793/100629 [06:10<1:16:27, 20.24it/s]

  8%|▊         | 7796/100629 [06:10<1:16:03, 20.34it/s]

  8%|▊         | 7799/100629 [06:10<1:25:04, 18.18it/s]

  8%|▊         | 7801/100629 [06:10<1:23:33, 18.52it/s]

  8%|▊         | 7803/100629 [06:11<1:28:25, 17.49it/s]

  8%|▊         | 7805/100629 [06:11<1:31:48, 16.85it/s]

  8%|▊         | 7808/100629 [06:11<1:25:54, 18.01it/s]

  8%|▊         | 7810/100629 [06:11<1:29:27, 17.29it/s]

  8%|▊         | 7813/100629 [06:11<1:22:40, 18.71it/s]

  8%|▊         | 7815/100629 [06:11<1:27:08, 17.75it/s]

  8%|▊         | 7818/100629 [06:11<1:29:02, 17.37it/s]

  8%|▊         | 7821/100629 [06:12<1:20:05, 19.31it/s]

  8%|▊         | 7824/100629 [06:12<1:17:39, 19.92it/s]

  8%|▊         | 7828/100629 [06:12<1:12:09, 21.43it/s]

  8%|▊         | 7831/100629 [06:12<1:18:52, 19.61it/s]

  8%|▊         | 7834/100629 [06:12<1:12:15, 21.40it/s]

  8%|▊         | 7837/100629 [06:12<1:14:16, 20.82it/s]

  8%|▊         | 7840/100629 [06:12<1:12:46, 21.25it/s]

  8%|▊         | 7844/100629 [06:13<1:06:06, 23.39it/s]

  8%|▊         | 7848/100629 [06:13<56:57, 27.15it/s]

  8%|▊         | 7851/100629 [06:13<57:41, 26.80it/s]

  8%|▊         | 7854/100629 [06:13<1:03:42, 24.27it/s]

  8%|▊         | 7858/100629 [06:13<55:55, 27.65it/s]

  8%|▊         | 7861/100629 [06:13<1:01:36, 25.10it/s]

  8%|▊         | 7866/100629 [06:13<59:51, 25.83it/s]

  8%|▊         | 7869/100629 [06:14<1:03:35, 24.31it/s]

  8%|▊         | 7872/100629 [06:14<1:02:46, 24.63it/s]

  8%|▊         | 7875/100629 [06:14<1:11:27, 21.63it/s]

  8%|▊         | 7878/100629 [06:14<1:07:20, 22.95it/s]

  8%|▊         | 7882/100629 [06:14<1:00:50, 25.40it/s]

  8%|▊         | 7885/100629 [06:14<1:05:59, 23.42it/s]

  8%|▊         | 7888/100629 [06:14<1:10:41, 21.86it/s]

  8%|▊         | 7891/100629 [06:14<1:05:49, 23.48it/s]

  8%|▊         | 7894/100629 [06:15<1:01:58, 24.94it/s]

  8%|▊         | 7897/100629 [06:15<1:08:25, 22.58it/s]

  8%|▊         | 7900/100629 [06:15<1:07:43, 22.82it/s]

  8%|▊         | 7903/100629 [06:15<1:12:55, 21.19it/s]

  8%|▊         | 7906/100629 [06:15<1:18:52, 19.59it/s]

  8%|▊         | 7909/100629 [06:15<1:16:45, 20.13it/s]

  8%|▊         | 7913/100629 [06:16<1:36:16, 16.05it/s]

  8%|▊         | 7916/100629 [06:16<1:31:54, 16.81it/s]

  8%|▊         | 7918/100629 [06:16<1:36:08, 16.07it/s]

  8%|▊         | 7920/100629 [06:16<1:33:46, 16.48it/s]

  8%|▊         | 7924/100629 [06:16<1:25:14, 18.13it/s]

  8%|▊         | 7927/100629 [06:16<1:18:29, 19.68it/s]

  8%|▊         | 7931/100629 [06:17<1:07:39, 22.83it/s]

  8%|▊         | 7935/100629 [06:17<59:16, 26.07it/s]

  8%|▊         | 7939/100629 [06:17<58:22, 26.47it/s]

  8%|▊         | 7943/100629 [06:17<1:02:56, 24.55it/s]

  8%|▊         | 7946/100629 [06:17<1:03:17, 24.40it/s]

  8%|▊         | 7949/100629 [06:17<1:01:26, 25.14it/s]

  8%|▊         | 7952/100629 [06:17<1:08:27, 22.56it/s]

  8%|▊         | 7955/100629 [06:17<1:04:41, 23.88it/s]

  8%|▊         | 7958/100629 [06:18<1:11:01, 21.75it/s]

  8%|▊         | 7961/100629 [06:18<1:06:19, 23.28it/s]

  8%|▊         | 7964/100629 [06:18<1:08:40, 22.49it/s]

  8%|▊         | 7968/100629 [06:18<1:02:53, 24.56it/s]

  8%|▊         | 7973/100629 [06:18<54:54, 28.13it/s]

  8%|▊         | 7976/100629 [06:18<56:43, 27.22it/s]

  8%|▊         | 7979/100629 [06:18<1:07:23, 22.91it/s]

  8%|▊         | 7983/100629 [06:19<1:00:21, 25.58it/s]

  8%|▊         | 7987/100629 [06:19<53:38, 28.78it/s]

  8%|▊         | 7991/100629 [06:19<1:06:09, 23.34it/s]

  8%|▊         | 7994/100629 [06:19<1:17:08, 20.02it/s]

  8%|▊         | 7997/100629 [06:19<1:19:43, 19.37it/s]

  8%|▊         | 8000/100629 [06:20<1:24:12, 18.33it/s]

  8%|▊         | 8002/100629 [06:20<1:33:59, 16.42it/s]

  8%|▊         | 8006/100629 [06:20<1:17:31, 19.91it/s]

  8%|▊         | 8009/100629 [06:20<1:15:36, 20.42it/s]

  8%|▊         | 8012/100629 [06:20<1:31:07, 16.94it/s]

  8%|▊         | 8016/100629 [06:20<1:14:24, 20.74it/s]

  8%|▊         | 8019/100629 [06:20<1:12:10, 21.39it/s]

  8%|▊         | 8022/100629 [06:21<1:13:48, 20.91it/s]

  8%|▊         | 8025/100629 [06:21<1:24:07, 18.35it/s]

  8%|▊         | 8028/100629 [06:21<1:21:51, 18.85it/s]

  8%|▊         | 8030/100629 [06:21<1:22:56, 18.61it/s]

  8%|▊         | 8036/100629 [06:21<1:00:01, 25.71it/s]

  8%|▊         | 8039/100629 [06:21<59:24, 25.98it/s]

  8%|▊         | 8043/100629 [06:21<1:02:14, 24.79it/s]

  8%|▊         | 8046/100629 [06:22<1:07:54, 22.73it/s]

  8%|▊         | 8049/100629 [06:22<1:10:31, 21.88it/s]

  8%|▊         | 8052/100629 [06:22<1:30:39, 17.02it/s]

  8%|▊         | 8054/100629 [06:22<1:36:15, 16.03it/s]

  8%|▊         | 8056/100629 [06:22<1:38:18, 15.70it/s]

  8%|▊         | 8058/100629 [06:22<1:33:46, 16.45it/s]

  8%|▊         | 8060/100629 [06:23<1:29:46, 17.18it/s]

  8%|▊         | 8062/100629 [06:23<1:33:53, 16.43it/s]

  8%|▊         | 8064/100629 [06:23<1:29:55, 17.16it/s]

  8%|▊         | 8066/100629 [06:23<1:37:00, 15.90it/s]

  8%|▊         | 8068/100629 [06:23<1:37:25, 15.83it/s]

  8%|▊         | 8071/100629 [06:23<1:30:32, 17.04it/s]

  8%|▊         | 8073/100629 [06:23<1:43:32, 14.90it/s]

  8%|▊         | 8075/100629 [06:24<1:44:29, 14.76it/s]

  8%|▊         | 8078/100629 [06:24<1:36:13, 16.03it/s]

  8%|▊         | 8081/100629 [06:24<1:26:45, 17.78it/s]

  8%|▊         | 8084/100629 [06:24<1:21:03, 19.03it/s]

  8%|▊         | 8087/100629 [06:24<1:11:56, 21.44it/s]

  8%|▊         | 8090/100629 [06:24<1:18:02, 19.76it/s]

  8%|▊         | 8093/100629 [06:24<1:22:38, 18.66it/s]

  8%|▊         | 8096/100629 [06:25<1:13:52, 20.88it/s]

  8%|▊         | 8099/100629 [06:25<1:12:45, 21.19it/s]

  8%|▊         | 8102/100629 [06:25<1:08:59, 22.35it/s]

  8%|▊         | 8105/100629 [06:25<1:08:09, 22.62it/s]

  8%|▊         | 8108/100629 [06:25<1:14:50, 20.60it/s]

  8%|▊         | 8111/100629 [06:25<1:17:06, 20.00it/s]

  8%|▊         | 8115/100629 [06:25<1:07:32, 22.83it/s]

  8%|▊         | 8118/100629 [06:26<1:04:44, 23.81it/s]

  8%|▊         | 8121/100629 [06:26<1:26:26, 17.84it/s]

  8%|▊         | 8124/100629 [06:26<1:22:24, 18.71it/s]

  8%|▊         | 8127/100629 [06:26<1:19:11, 19.47it/s]

  8%|▊         | 8130/100629 [06:26<1:18:21, 19.67it/s]

  8%|▊         | 8134/100629 [06:26<1:07:24, 22.87it/s]

  8%|▊         | 8137/100629 [06:27<1:11:35, 21.53it/s]

  8%|▊         | 8140/100629 [06:27<1:31:56, 16.77it/s]

  8%|▊         | 8143/100629 [06:27<1:26:39, 17.79it/s]

  8%|▊         | 8146/100629 [06:27<1:35:35, 16.12it/s]

  8%|▊         | 8151/100629 [06:27<1:12:07, 21.37it/s]

  8%|▊         | 8154/100629 [06:27<1:12:27, 21.27it/s]

  8%|▊         | 8157/100629 [06:28<1:07:07, 22.96it/s]

  8%|▊         | 8160/100629 [06:28<1:03:14, 24.37it/s]

  8%|▊         | 8164/100629 [06:28<1:00:16, 25.57it/s]

  8%|▊         | 8167/100629 [06:28<1:02:53, 24.50it/s]

  8%|▊         | 8170/100629 [06:28<1:03:48, 24.15it/s]

  8%|▊         | 8173/100629 [06:28<1:08:37, 22.45it/s]

  8%|▊         | 8176/100629 [06:28<1:05:40, 23.46it/s]

  8%|▊         | 8179/100629 [06:28<1:02:26, 24.68it/s]

  8%|▊         | 8182/100629 [06:29<1:01:59, 24.85it/s]

  8%|▊         | 8185/100629 [06:29<1:00:42, 25.38it/s]

  8%|▊         | 8188/100629 [06:29<1:13:21, 21.00it/s]

  8%|▊         | 8191/100629 [06:29<1:10:25, 21.87it/s]

  8%|▊         | 8194/100629 [06:29<1:15:33, 20.39it/s]

  8%|▊         | 8197/100629 [06:29<1:22:41, 18.63it/s]

  8%|▊         | 8199/100629 [06:29<1:25:07, 18.10it/s]

  8%|▊         | 8201/100629 [06:30<1:31:53, 16.76it/s]

  8%|▊         | 8204/100629 [06:30<1:31:40, 16.80it/s]

  8%|▊         | 8207/100629 [06:30<1:21:23, 18.92it/s]

  8%|▊         | 8210/100629 [06:30<1:22:46, 18.61it/s]

  8%|▊         | 8213/100629 [06:30<1:15:27, 20.41it/s]

  8%|▊         | 8217/100629 [06:30<1:05:59, 23.34it/s]

  8%|▊         | 8220/100629 [06:30<1:10:00, 22.00it/s]

  8%|▊         | 8223/100629 [06:31<1:09:00, 22.31it/s]

  8%|▊         | 8226/100629 [06:31<1:04:29, 23.88it/s]

  8%|▊         | 8230/100629 [06:31<55:32, 27.72it/s]

  8%|▊         | 8233/100629 [06:31<1:22:46, 18.60it/s]

  8%|▊         | 8237/100629 [06:31<1:11:36, 21.50it/s]

  8%|▊         | 8240/100629 [06:31<1:06:49, 23.05it/s]

  8%|▊         | 8243/100629 [06:31<1:06:58, 22.99it/s]

  8%|▊         | 8246/100629 [06:32<1:20:08, 19.21it/s]

  8%|▊         | 8250/100629 [06:32<1:14:03, 20.79it/s]

  8%|▊         | 8255/100629 [06:32<58:10, 26.47it/s]

  8%|▊         | 8258/100629 [06:32<1:06:51, 23.03it/s]

  8%|▊         | 8261/100629 [06:32<1:06:29, 23.16it/s]

  8%|▊         | 8264/100629 [06:32<1:07:33, 22.79it/s]

  8%|▊         | 8268/100629 [06:33<1:01:11, 25.15it/s]

  8%|▊         | 8273/100629 [06:33<52:41, 29.22it/s]

  8%|▊         | 8277/100629 [06:33<50:15, 30.63it/s]

  8%|▊         | 8281/100629 [06:33<58:32, 26.29it/s]

  8%|▊         | 8284/100629 [06:33<1:05:06, 23.64it/s]

  8%|▊         | 8287/100629 [06:33<1:08:37, 22.43it/s]

  8%|▊         | 8290/100629 [06:33<1:11:22, 21.56it/s]

  8%|▊         | 8293/100629 [06:34<1:33:21, 16.49it/s]

  8%|▊         | 8296/100629 [06:34<1:24:59, 18.11it/s]

  8%|▊         | 8299/100629 [06:34<1:25:36, 17.97it/s]

  8%|▊         | 8302/100629 [06:34<1:23:48, 18.36it/s]

  8%|▊         | 8305/100629 [06:34<1:15:36, 20.35it/s]

  8%|▊         | 8308/100629 [06:34<1:10:25, 21.85it/s]

  8%|▊         | 8311/100629 [06:35<1:05:51, 23.36it/s]

  8%|▊         | 8314/100629 [06:35<1:25:23, 18.02it/s]

  8%|▊         | 8317/100629 [06:35<1:26:53, 17.71it/s]

  8%|▊         | 8320/100629 [06:35<1:22:25, 18.67it/s]

  8%|▊         | 8323/100629 [06:35<1:17:32, 19.84it/s]

  8%|▊         | 8326/100629 [06:35<1:16:00, 20.24it/s]

  8%|▊         | 8330/100629 [06:35<1:02:47, 24.50it/s]

  8%|▊         | 8333/100629 [06:36<1:00:14, 25.53it/s]

  8%|▊         | 8336/100629 [06:36<1:01:13, 25.13it/s]

  8%|▊         | 8340/100629 [06:36<54:51, 28.04it/s]

  8%|▊         | 8343/100629 [06:36<1:00:24, 25.46it/s]

  8%|▊         | 8346/100629 [06:36<1:00:44, 25.32it/s]

  8%|▊         | 8349/100629 [06:36<1:04:37, 23.80it/s]

  8%|▊         | 8352/100629 [06:36<1:01:59, 24.81it/s]

  8%|▊         | 8355/100629 [06:36<1:04:05, 23.99it/s]

  8%|▊         | 8358/100629 [06:37<1:07:13, 22.87it/s]

  8%|▊         | 8361/100629 [06:37<1:06:12, 23.23it/s]

  8%|▊         | 8364/100629 [06:37<1:03:03, 24.39it/s]

  8%|▊         | 8367/100629 [06:37<1:08:13, 22.54it/s]

  8%|▊         | 8370/100629 [06:37<1:07:08, 22.90it/s]

  8%|▊         | 8374/100629 [06:37<58:01, 26.49it/s]

  8%|▊         | 8377/100629 [06:37<1:05:49, 23.36it/s]

  8%|▊         | 8380/100629 [06:38<1:06:07, 23.25it/s]

  8%|▊         | 8383/100629 [06:38<1:09:49, 22.02it/s]

  8%|▊         | 8387/100629 [06:38<58:45, 26.17it/s]

  8%|▊         | 8390/100629 [06:38<1:01:11, 25.12it/s]

  8%|▊         | 8393/100629 [06:38<1:14:17, 20.69it/s]

  8%|▊         | 8396/100629 [06:38<1:17:53, 19.74it/s]

  8%|▊         | 8399/100629 [06:38<1:15:41, 20.31it/s]

  8%|▊         | 8402/100629 [06:39<1:09:35, 22.09it/s]

  8%|▊         | 8405/100629 [06:39<1:08:36, 22.40it/s]

  8%|▊         | 8408/100629 [06:39<1:22:59, 18.52it/s]

  8%|▊         | 8411/100629 [06:39<1:31:29, 16.80it/s]

  8%|▊         | 8414/100629 [06:39<1:28:39, 17.34it/s]

  8%|▊         | 8417/100629 [06:39<1:19:12, 19.40it/s]

  8%|▊         | 8420/100629 [06:40<1:15:25, 20.38it/s]

  8%|▊         | 8423/100629 [06:40<1:15:16, 20.42it/s]

  8%|▊         | 8427/100629 [06:40<1:08:45, 22.35it/s]

  8%|▊         | 8431/100629 [06:40<58:33, 26.24it/s]

  8%|▊         | 8435/100629 [06:40<1:02:09, 24.72it/s]

  8%|▊         | 8438/100629 [06:40<1:01:23, 25.03it/s]

  8%|▊         | 8441/100629 [06:40<1:12:12, 21.28it/s]

  8%|▊         | 8444/100629 [06:41<1:07:17, 22.83it/s]

  8%|▊         | 8448/100629 [06:41<1:02:00, 24.77it/s]

  8%|▊         | 8451/100629 [06:41<1:08:56, 22.29it/s]

  8%|▊         | 8454/100629 [06:41<1:12:36, 21.16it/s]

  8%|▊         | 8458/100629 [06:41<1:04:50, 23.69it/s]

  8%|▊         | 8462/100629 [06:41<1:01:38, 24.92it/s]

  8%|▊         | 8465/100629 [06:42<1:16:52, 19.98it/s]

  8%|▊         | 8468/100629 [06:42<1:16:42, 20.02it/s]

  8%|▊         | 8471/100629 [06:42<1:13:06, 21.01it/s]

  8%|▊         | 8474/100629 [06:42<1:21:47, 18.78it/s]

  8%|▊         | 8477/100629 [06:42<1:14:55, 20.50it/s]

  8%|▊         | 8480/100629 [06:42<1:22:05, 18.71it/s]

  8%|▊         | 8483/100629 [06:42<1:17:21, 19.85it/s]

  8%|▊         | 8486/100629 [06:43<1:23:32, 18.38it/s]

  8%|▊         | 8490/100629 [06:43<1:19:37, 19.29it/s]

  8%|▊         | 8493/100629 [06:43<1:22:51, 18.53it/s]

  8%|▊         | 8496/100629 [06:43<1:14:37, 20.58it/s]

  8%|▊         | 8499/100629 [06:43<1:27:31, 17.55it/s]

  8%|▊         | 8501/100629 [06:43<1:32:10, 16.66it/s]

  8%|▊         | 8506/100629 [06:44<1:13:55, 20.77it/s]

  8%|▊         | 8509/100629 [06:44<1:08:42, 22.34it/s]

  8%|▊         | 8512/100629 [06:44<1:09:58, 21.94it/s]

  8%|▊         | 8515/100629 [06:44<1:18:23, 19.59it/s]

  8%|▊         | 8518/100629 [06:44<1:14:38, 20.57it/s]

  8%|▊         | 8522/100629 [06:44<1:12:02, 21.31it/s]

  8%|▊         | 8525/100629 [06:45<1:11:57, 21.33it/s]

  8%|▊         | 8528/100629 [06:45<1:14:15, 20.67it/s]

  8%|▊         | 8531/100629 [06:45<1:16:33, 20.05it/s]

  8%|▊         | 8534/100629 [06:45<1:12:49, 21.08it/s]

  8%|▊         | 8537/100629 [06:45<1:11:31, 21.46it/s]

  8%|▊         | 8540/100629 [06:45<1:21:59, 18.72it/s]

  8%|▊         | 8543/100629 [06:45<1:15:10, 20.42it/s]

  8%|▊         | 8547/100629 [06:46<1:02:43, 24.47it/s]

  8%|▊         | 8550/100629 [06:46<1:08:57, 22.26it/s]

  8%|▊         | 8553/100629 [06:46<1:10:00, 21.92it/s]

  9%|▊         | 8556/100629 [06:46<1:06:14, 23.17it/s]

  9%|▊         | 8559/100629 [06:46<1:10:33, 21.75it/s]

  9%|▊         | 8562/100629 [06:46<1:25:21, 17.98it/s]

  9%|▊         | 8564/100629 [06:46<1:34:06, 16.30it/s]

  9%|▊         | 8566/100629 [06:47<1:31:26, 16.78it/s]

  9%|▊         | 8568/100629 [06:47<1:33:39, 16.38it/s]

  9%|▊         | 8571/100629 [06:47<1:21:25, 18.84it/s]

  9%|▊         | 8575/100629 [06:47<1:13:45, 20.80it/s]

  9%|▊         | 8578/100629 [06:47<1:08:26, 22.41it/s]

  9%|▊         | 8582/100629 [06:47<1:06:13, 23.16it/s]

  9%|▊         | 8586/100629 [06:47<1:07:51, 22.61it/s]

  9%|▊         | 8589/100629 [06:48<1:08:14, 22.48it/s]

  9%|▊         | 8592/100629 [06:48<1:16:50, 19.96it/s]

  9%|▊         | 8595/100629 [06:48<1:18:48, 19.46it/s]

  9%|▊         | 8597/100629 [06:48<1:24:31, 18.15it/s]

  9%|▊         | 8600/100629 [06:48<1:15:35, 20.29it/s]

  9%|▊         | 8603/100629 [06:48<1:16:16, 20.11it/s]

  9%|▊         | 8606/100629 [06:49<1:14:29, 20.59it/s]

  9%|▊         | 8609/100629 [06:49<1:08:17, 22.46it/s]

  9%|▊         | 8612/100629 [06:49<1:04:15, 23.86it/s]

  9%|▊         | 8616/100629 [06:49<58:31, 26.20it/s]

  9%|▊         | 8620/100629 [06:49<1:00:47, 25.23it/s]

  9%|▊         | 8624/100629 [06:49<56:33, 27.11it/s]

  9%|▊         | 8627/100629 [06:49<1:02:03, 24.71it/s]

  9%|▊         | 8631/100629 [06:49<58:00, 26.43it/s]

  9%|▊         | 8634/100629 [06:50<1:04:46, 23.67it/s]

  9%|▊         | 8637/100629 [06:50<1:12:03, 21.28it/s]

  9%|▊         | 8641/100629 [06:50<1:03:57, 23.97it/s]

  9%|▊         | 8644/100629 [06:50<1:03:31, 24.13it/s]

  9%|▊         | 8647/100629 [06:50<1:01:46, 24.82it/s]

  9%|▊         | 8650/100629 [06:50<1:00:56, 25.15it/s]

  9%|▊         | 8653/100629 [06:50<1:17:35, 19.76it/s]

  9%|▊         | 8656/100629 [06:51<1:17:32, 19.77it/s]

  9%|▊         | 8660/100629 [06:51<1:17:18, 19.83it/s]

  9%|▊         | 8663/100629 [06:51<1:17:17, 19.83it/s]

  9%|▊         | 8667/100629 [06:51<1:09:49, 21.95it/s]

  9%|▊         | 8670/100629 [06:51<1:08:48, 22.27it/s]

  9%|▊         | 8673/100629 [06:51<1:06:03, 23.20it/s]

  9%|▊         | 8676/100629 [06:52<1:10:44, 21.67it/s]

  9%|▊         | 8679/100629 [06:52<1:14:04, 20.69it/s]

  9%|▊         | 8682/100629 [06:52<1:07:50, 22.59it/s]

  9%|▊         | 8685/100629 [06:52<1:08:16, 22.44it/s]

  9%|▊         | 8688/100629 [06:52<1:15:23, 20.32it/s]

  9%|▊         | 8691/100629 [06:52<1:24:31, 18.13it/s]

  9%|▊         | 8693/100629 [06:52<1:29:12, 17.18it/s]

  9%|▊         | 8696/100629 [06:53<1:17:05, 19.88it/s]

  9%|▊         | 8700/100629 [06:53<1:05:29, 23.39it/s]

  9%|▊         | 8705/100629 [06:53<55:08, 27.78it/s]

  9%|▊         | 8708/100629 [06:53<1:02:41, 24.44it/s]

  9%|▊         | 8711/100629 [06:53<1:02:54, 24.35it/s]

  9%|▊         | 8715/100629 [06:53<1:00:07, 25.48it/s]

  9%|▊         | 8718/100629 [06:53<1:11:44, 21.35it/s]

  9%|▊         | 8721/100629 [06:54<1:17:30, 19.76it/s]

  9%|▊         | 8726/100629 [06:54<1:03:05, 24.28it/s]

  9%|▊         | 8729/100629 [06:54<1:15:21, 20.33it/s]

  9%|▊         | 8732/100629 [06:54<1:09:10, 22.14it/s]

  9%|▊         | 8735/100629 [06:54<1:18:54, 19.41it/s]

  9%|▊         | 8738/100629 [06:54<1:18:22, 19.54it/s]

  9%|▊         | 8741/100629 [06:55<1:11:39, 21.37it/s]

  9%|▊         | 8744/100629 [06:55<1:11:05, 21.54it/s]

  9%|▊         | 8747/100629 [06:55<1:16:05, 20.13it/s]

  9%|▊         | 8750/100629 [06:55<1:20:09, 19.10it/s]

  9%|▊         | 8752/100629 [06:55<1:34:34, 16.19it/s]

  9%|▊         | 8754/100629 [06:55<1:48:19, 14.13it/s]

  9%|▊         | 8756/100629 [06:56<1:45:17, 14.54it/s]

  9%|▊         | 8759/100629 [06:56<1:32:51, 16.49it/s]

  9%|▊         | 8762/100629 [06:56<1:26:02, 17.80it/s]

  9%|▊         | 8765/100629 [06:56<1:30:16, 16.96it/s]

  9%|▊         | 8767/100629 [06:56<1:45:27, 14.52it/s]

  9%|▊         | 8769/100629 [06:56<1:45:15, 14.55it/s]

  9%|▊         | 8772/100629 [06:56<1:28:03, 17.39it/s]

  9%|▊         | 8774/100629 [06:57<1:25:25, 17.92it/s]

  9%|▊         | 8776/100629 [06:57<1:32:08, 16.61it/s]

  9%|▊         | 8778/100629 [06:57<1:33:43, 16.33it/s]

  9%|▊         | 8781/100629 [06:57<1:18:52, 19.41it/s]

  9%|▊         | 8784/100629 [06:57<1:14:17, 20.61it/s]

  9%|▊         | 8789/100629 [06:57<59:51, 25.57it/s]

  9%|▊         | 8792/100629 [06:57<1:04:27, 23.75it/s]

  9%|▊         | 8795/100629 [06:58<1:15:24, 20.30it/s]

  9%|▊         | 8800/100629 [06:58<1:01:08, 25.03it/s]

  9%|▊         | 8803/100629 [06:58<1:02:49, 24.36it/s]

  9%|▉         | 8807/100629 [06:58<1:02:46, 24.38it/s]

  9%|▉         | 8810/100629 [06:58<1:07:35, 22.64it/s]

  9%|▉         | 8813/100629 [06:58<1:03:56, 23.93it/s]

  9%|▉         | 8816/100629 [06:58<1:03:05, 24.25it/s]

  9%|▉         | 8819/100629 [06:59<1:14:06, 20.65it/s]

  9%|▉         | 8822/100629 [06:59<1:15:17, 20.32it/s]

  9%|▉         | 8825/100629 [06:59<1:31:01, 16.81it/s]

  9%|▉         | 8828/100629 [06:59<1:20:13, 19.07it/s]

  9%|▉         | 8831/100629 [06:59<1:17:42, 19.69it/s]

  9%|▉         | 8834/100629 [06:59<1:18:29, 19.49it/s]

  9%|▉         | 8837/100629 [07:00<1:17:10, 19.82it/s]

  9%|▉         | 8840/100629 [07:00<1:15:59, 20.13it/s]

  9%|▉         | 8843/100629 [07:00<1:28:41, 17.25it/s]

  9%|▉         | 8846/100629 [07:00<1:17:31, 19.73it/s]

  9%|▉         | 8849/100629 [07:00<1:12:33, 21.08it/s]

  9%|▉         | 8853/100629 [07:00<1:07:00, 22.83it/s]

  9%|▉         | 8856/100629 [07:00<1:05:29, 23.35it/s]

  9%|▉         | 8860/100629 [07:01<1:03:51, 23.95it/s]

  9%|▉         | 8863/100629 [07:01<1:10:26, 21.71it/s]

  9%|▉         | 8866/100629 [07:01<1:20:54, 18.90it/s]

  9%|▉         | 8868/100629 [07:01<1:28:17, 17.32it/s]

  9%|▉         | 8872/100629 [07:01<1:09:54, 21.88it/s]

  9%|▉         | 8875/100629 [07:01<1:24:51, 18.02it/s]

  9%|▉         | 8878/100629 [07:02<1:22:36, 18.51it/s]

  9%|▉         | 8881/100629 [07:02<1:42:06, 14.97it/s]

  9%|▉         | 8885/100629 [07:02<1:24:14, 18.15it/s]

  9%|▉         | 8888/100629 [07:02<1:17:17, 19.78it/s]

  9%|▉         | 8891/100629 [07:02<1:28:53, 17.20it/s]

  9%|▉         | 8896/100629 [07:03<1:10:43, 21.62it/s]

  9%|▉         | 8899/100629 [07:03<1:11:30, 21.38it/s]

  9%|▉         | 8903/100629 [07:03<1:02:40, 24.39it/s]

  9%|▉         | 8907/100629 [07:03<57:34, 26.55it/s]

  9%|▉         | 8912/100629 [07:03<49:49, 30.68it/s]

  9%|▉         | 8916/100629 [07:03<50:37, 30.19it/s]

  9%|▉         | 8920/100629 [07:03<1:08:43, 22.24it/s]

  9%|▉         | 8923/100629 [07:04<1:04:46, 23.60it/s]

  9%|▉         | 8927/100629 [07:04<59:10, 25.83it/s]

  9%|▉         | 8930/100629 [07:04<1:02:50, 24.32it/s]

  9%|▉         | 8934/100629 [07:04<57:53, 26.40it/s]

  9%|▉         | 8940/100629 [07:04<45:25, 33.64it/s]

  9%|▉         | 8944/100629 [07:04<57:42, 26.48it/s]

  9%|▉         | 8949/100629 [07:04<48:50, 31.28it/s]

  9%|▉         | 8953/100629 [07:05<1:04:57, 23.52it/s]

  9%|▉         | 8956/100629 [07:05<1:13:24, 20.81it/s]

  9%|▉         | 8959/100629 [07:05<1:11:26, 21.38it/s]

  9%|▉         | 8962/100629 [07:05<1:07:03, 22.78it/s]

  9%|▉         | 8965/100629 [07:05<1:18:24, 19.48it/s]

  9%|▉         | 8968/100629 [07:05<1:19:13, 19.28it/s]

  9%|▉         | 8971/100629 [07:06<1:19:30, 19.21it/s]

  9%|▉         | 8974/100629 [07:06<1:11:16, 21.43it/s]

  9%|▉         | 8977/100629 [07:06<1:09:26, 22.00it/s]

  9%|▉         | 8980/100629 [07:06<1:04:20, 23.74it/s]

  9%|▉         | 8983/100629 [07:06<1:08:13, 22.39it/s]

  9%|▉         | 8986/100629 [07:06<1:22:49, 18.44it/s]

  9%|▉         | 8990/100629 [07:06<1:07:40, 22.57it/s]

  9%|▉         | 8993/100629 [07:07<1:22:31, 18.51it/s]

  9%|▉         | 8996/100629 [07:07<1:40:38, 15.18it/s]

  9%|▉         | 8999/100629 [07:07<1:34:35, 16.14it/s]

  9%|▉         | 9001/100629 [07:07<1:34:11, 16.21it/s]

  9%|▉         | 9004/100629 [07:07<1:29:11, 17.12it/s]

  9%|▉         | 9008/100629 [07:08<1:13:59, 20.64it/s]

  9%|▉         | 9011/100629 [07:08<1:13:29, 20.78it/s]

  9%|▉         | 9014/100629 [07:08<1:17:33, 19.69it/s]

  9%|▉         | 9017/100629 [07:08<1:19:55, 19.10it/s]

  9%|▉         | 9020/100629 [07:08<1:15:21, 20.26it/s]

  9%|▉         | 9024/100629 [07:08<1:06:55, 22.81it/s]

  9%|▉         | 9027/100629 [07:09<1:21:18, 18.78it/s]

  9%|▉         | 9030/100629 [07:09<1:22:11, 18.58it/s]

  9%|▉         | 9032/100629 [07:09<1:25:11, 17.92it/s]

  9%|▉         | 9034/100629 [07:09<1:23:43, 18.23it/s]

  9%|▉         | 9036/100629 [07:09<1:44:28, 14.61it/s]

  9%|▉         | 9039/100629 [07:09<1:26:10, 17.71it/s]

  9%|▉         | 9043/100629 [07:09<1:11:15, 21.42it/s]

  9%|▉         | 9047/100629 [07:10<1:07:55, 22.47it/s]

  9%|▉         | 9050/100629 [07:10<1:04:30, 23.66it/s]

  9%|▉         | 9053/100629 [07:10<1:09:05, 22.09it/s]

  9%|▉         | 9056/100629 [07:10<1:26:38, 17.61it/s]

  9%|▉         | 9058/100629 [07:10<1:29:31, 17.05it/s]

  9%|▉         | 9060/100629 [07:10<1:29:39, 17.02it/s]

  9%|▉         | 9063/100629 [07:10<1:23:13, 18.34it/s]

  9%|▉         | 9065/100629 [07:11<1:24:27, 18.07it/s]

  9%|▉         | 9067/100629 [07:11<1:28:08, 17.31it/s]

  9%|▉         | 9070/100629 [07:11<1:19:16, 19.25it/s]

  9%|▉         | 9072/100629 [07:11<1:20:31, 18.95it/s]

  9%|▉         | 9075/100629 [07:11<1:25:03, 17.94it/s]

  9%|▉         | 9077/100629 [07:11<1:24:39, 18.02it/s]

  9%|▉         | 9079/100629 [07:11<1:31:15, 16.72it/s]

  9%|▉         | 9083/100629 [07:11<1:11:51, 21.24it/s]

  9%|▉         | 9086/100629 [07:12<1:13:02, 20.89it/s]

  9%|▉         | 9089/100629 [07:12<1:16:32, 19.93it/s]

  9%|▉         | 9092/100629 [07:12<1:23:05, 18.36it/s]

  9%|▉         | 9094/100629 [07:12<1:22:11, 18.56it/s]

  9%|▉         | 9097/100629 [07:12<1:13:40, 20.70it/s]

  9%|▉         | 9100/100629 [07:12<1:22:02, 18.59it/s]

  9%|▉         | 9105/100629 [07:13<1:06:17, 23.01it/s]

  9%|▉         | 9108/100629 [07:13<1:21:53, 18.63it/s]

  9%|▉         | 9112/100629 [07:13<1:09:55, 21.81it/s]

  9%|▉         | 9115/100629 [07:13<1:06:38, 22.89it/s]

  9%|▉         | 9118/100629 [07:13<1:06:46, 22.84it/s]

  9%|▉         | 9121/100629 [07:13<1:10:27, 21.65it/s]

  9%|▉         | 9124/100629 [07:13<1:05:10, 23.40it/s]

  9%|▉         | 9128/100629 [07:14<59:13, 25.75it/s]

  9%|▉         | 9131/100629 [07:14<1:03:54, 23.86it/s]

  9%|▉         | 9134/100629 [07:14<1:07:31, 22.58it/s]

  9%|▉         | 9138/100629 [07:14<59:58, 25.42it/s]

  9%|▉         | 9141/100629 [07:14<1:08:42, 22.19it/s]

  9%|▉         | 9145/100629 [07:14<1:22:11, 18.55it/s]

  9%|▉         | 9149/100629 [07:15<1:12:47, 20.95it/s]

  9%|▉         | 9152/100629 [07:15<1:13:24, 20.77it/s]

  9%|▉         | 9155/100629 [07:15<1:08:12, 22.35it/s]

  9%|▉         | 9158/100629 [07:15<1:06:32, 22.91it/s]

  9%|▉         | 9161/100629 [07:15<1:05:03, 23.43it/s]

  9%|▉         | 9164/100629 [07:15<1:16:39, 19.89it/s]

  9%|▉         | 9167/100629 [07:15<1:10:48, 21.53it/s]

  9%|▉         | 9171/100629 [07:15<1:03:18, 24.08it/s]

  9%|▉         | 9174/100629 [07:16<1:10:47, 21.53it/s]

  9%|▉         | 9177/100629 [07:16<1:25:03, 17.92it/s]

  9%|▉         | 9180/100629 [07:16<1:26:32, 17.61it/s]

  9%|▉         | 9182/100629 [07:16<1:26:05, 17.70it/s]

  9%|▉         | 9184/100629 [07:16<1:30:03, 16.92it/s]

  9%|▉         | 9187/100629 [07:17<1:39:31, 15.31it/s]

  9%|▉         | 9189/100629 [07:17<1:35:55, 15.89it/s]

  9%|▉         | 9192/100629 [07:17<1:22:14, 18.53it/s]

  9%|▉         | 9194/100629 [07:17<1:23:27, 18.26it/s]

  9%|▉         | 9196/100629 [07:17<1:26:04, 17.70it/s]

  9%|▉         | 9200/100629 [07:17<1:12:47, 20.93it/s]

  9%|▉         | 9203/100629 [07:17<1:14:32, 20.44it/s]

  9%|▉         | 9207/100629 [07:17<1:05:54, 23.12it/s]

  9%|▉         | 9210/100629 [07:18<1:07:02, 22.73it/s]

  9%|▉         | 9213/100629 [07:18<1:02:58, 24.19it/s]

  9%|▉         | 9216/100629 [07:18<1:00:13, 25.30it/s]

  9%|▉         | 9219/100629 [07:18<58:05, 26.23it/s]

  9%|▉         | 9222/100629 [07:18<1:01:36, 24.72it/s]

  9%|▉         | 9225/100629 [07:18<1:02:40, 24.31it/s]

  9%|▉         | 9228/100629 [07:18<1:05:41, 23.19it/s]

  9%|▉         | 9231/100629 [07:18<1:05:43, 23.18it/s]

  9%|▉         | 9234/100629 [07:19<1:01:30, 24.76it/s]

  9%|▉         | 9238/100629 [07:19<56:02, 27.18it/s]

  9%|▉         | 9241/100629 [07:19<1:07:57, 22.41it/s]

  9%|▉         | 9245/100629 [07:19<1:01:58, 24.57it/s]

  9%|▉         | 9248/100629 [07:19<1:07:56, 22.42it/s]

  9%|▉         | 9252/100629 [07:19<1:02:58, 24.18it/s]

  9%|▉         | 9255/100629 [07:19<1:04:26, 23.63it/s]

  9%|▉         | 9258/100629 [07:20<1:11:46, 21.22it/s]

  9%|▉         | 9261/100629 [07:20<1:16:36, 19.88it/s]

  9%|▉         | 9264/100629 [07:20<1:18:45, 19.34it/s]

  9%|▉         | 9266/100629 [07:20<1:23:56, 18.14it/s]

  9%|▉         | 9268/100629 [07:20<1:22:37, 18.43it/s]

  9%|▉         | 9270/100629 [07:20<1:29:16, 17.05it/s]

  9%|▉         | 9273/100629 [07:20<1:24:20, 18.05it/s]

  9%|▉         | 9275/100629 [07:21<1:22:27, 18.46it/s]

  9%|▉         | 9279/100629 [07:21<1:06:02, 23.05it/s]

  9%|▉         | 9282/100629 [07:21<1:17:04, 19.75it/s]

  9%|▉         | 9285/100629 [07:21<1:23:10, 18.30it/s]

  9%|▉         | 9288/100629 [07:21<1:26:34, 17.58it/s]

  9%|▉         | 9290/100629 [07:21<1:28:52, 17.13it/s]

  9%|▉         | 9292/100629 [07:22<1:29:03, 17.09it/s]

  9%|▉         | 9294/100629 [07:22<1:27:17, 17.44it/s]

  9%|▉         | 9296/100629 [07:22<1:44:49, 14.52it/s]

  9%|▉         | 9299/100629 [07:22<1:33:14, 16.32it/s]

  9%|▉         | 9302/100629 [07:22<1:23:49, 18.16it/s]

  9%|▉         | 9305/100629 [07:22<1:19:35, 19.12it/s]

  9%|▉         | 9307/100629 [07:22<1:24:10, 18.08it/s]

  9%|▉         | 9309/100629 [07:22<1:22:38, 18.42it/s]

  9%|▉         | 9312/100629 [07:23<1:20:15, 18.96it/s]

  9%|▉         | 9315/100629 [07:23<1:15:49, 20.07it/s]

  9%|▉         | 9318/100629 [07:23<1:07:53, 22.42it/s]

  9%|▉         | 9321/100629 [07:23<1:14:17, 20.48it/s]

  9%|▉         | 9324/100629 [07:23<1:07:34, 22.52it/s]

  9%|▉         | 9327/100629 [07:23<1:18:26, 19.40it/s]

  9%|▉         | 9332/100629 [07:23<1:01:50, 24.60it/s]

  9%|▉         | 9335/100629 [07:24<1:07:10, 22.65it/s]

  9%|▉         | 9338/100629 [07:24<1:06:13, 22.98it/s]

  9%|▉         | 9341/100629 [07:24<1:19:21, 19.17it/s]

  9%|▉         | 9344/100629 [07:24<1:23:04, 18.32it/s]

  9%|▉         | 9348/100629 [07:24<1:11:45, 21.20it/s]

  9%|▉         | 9351/100629 [07:24<1:09:18, 21.95it/s]

  9%|▉         | 9354/100629 [07:25<1:08:06, 22.34it/s]

  9%|▉         | 9357/100629 [07:25<1:27:34, 17.37it/s]

  9%|▉         | 9359/100629 [07:25<1:34:33, 16.09it/s]

  9%|▉         | 9362/100629 [07:25<1:22:58, 18.33it/s]

  9%|▉         | 9365/100629 [07:25<1:17:20, 19.67it/s]

  9%|▉         | 9368/100629 [07:25<1:10:20, 21.62it/s]

  9%|▉         | 9371/100629 [07:26<1:24:14, 18.05it/s]

  9%|▉         | 9374/100629 [07:26<1:20:19, 18.94it/s]

  9%|▉         | 9377/100629 [07:26<1:29:09, 17.06it/s]

  9%|▉         | 9379/100629 [07:26<1:28:38, 17.16it/s]

  9%|▉         | 9383/100629 [07:26<1:15:59, 20.01it/s]

  9%|▉         | 9386/100629 [07:26<1:10:26, 21.59it/s]

  9%|▉         | 9390/100629 [07:26<1:01:34, 24.70it/s]

  9%|▉         | 9393/100629 [07:27<1:11:13, 21.35it/s]

  9%|▉         | 9397/100629 [07:27<1:06:49, 22.75it/s]

  9%|▉         | 9401/100629 [07:27<1:04:41, 23.50it/s]

  9%|▉         | 9404/100629 [07:27<1:01:05, 24.89it/s]

  9%|▉         | 9407/100629 [07:27<1:11:45, 21.19it/s]

  9%|▉         | 9410/100629 [07:27<1:09:09, 21.98it/s]

  9%|▉         | 9414/100629 [07:27<58:35, 25.94it/s]

  9%|▉         | 9417/100629 [07:28<1:09:24, 21.90it/s]

  9%|▉         | 9420/100629 [07:28<1:06:13, 22.95it/s]

  9%|▉         | 9424/100629 [07:28<1:08:59, 22.03it/s]

  9%|▉         | 9427/100629 [07:28<1:18:34, 19.34it/s]

  9%|▉         | 9430/100629 [07:28<1:14:18, 20.45it/s]

  9%|▉         | 9433/100629 [07:28<1:10:37, 21.52it/s]

  9%|▉         | 9436/100629 [07:29<1:07:52, 22.39it/s]

  9%|▉         | 9439/100629 [07:29<1:02:57, 24.14it/s]

  9%|▉         | 9442/100629 [07:29<1:05:51, 23.08it/s]

  9%|▉         | 9445/100629 [07:29<1:06:44, 22.77it/s]

  9%|▉         | 9449/100629 [07:29<58:13, 26.10it/s]

  9%|▉         | 9452/100629 [07:29<1:02:06, 24.47it/s]

  9%|▉         | 9455/100629 [07:29<1:11:38, 21.21it/s]

  9%|▉         | 9458/100629 [07:30<1:21:47, 18.58it/s]

  9%|▉         | 9460/100629 [07:30<1:28:38, 17.14it/s]

  9%|▉         | 9464/100629 [07:30<1:12:57, 20.82it/s]

  9%|▉         | 9467/100629 [07:30<1:21:02, 18.75it/s]

  9%|▉         | 9470/100629 [07:30<1:15:05, 20.23it/s]

  9%|▉         | 9473/100629 [07:30<1:24:47, 17.92it/s]

  9%|▉         | 9475/100629 [07:30<1:27:08, 17.44it/s]

  9%|▉         | 9478/100629 [07:31<1:21:00, 18.75it/s]

  9%|▉         | 9481/100629 [07:31<1:22:00, 18.52it/s]

  9%|▉         | 9485/100629 [07:31<1:13:30, 20.67it/s]

  9%|▉         | 9490/100629 [07:31<1:17:19, 19.64it/s]

  9%|▉         | 9493/100629 [07:31<1:11:33, 21.23it/s]

  9%|▉         | 9496/100629 [07:32<1:18:41, 19.30it/s]

  9%|▉         | 9499/100629 [07:32<1:18:21, 19.38it/s]

  9%|▉         | 9502/100629 [07:32<1:22:04, 18.50it/s]

  9%|▉         | 9506/100629 [07:32<1:08:35, 22.14it/s]

  9%|▉         | 9509/100629 [07:32<1:11:03, 21.37it/s]

  9%|▉         | 9512/100629 [07:32<1:26:47, 17.50it/s]

  9%|▉         | 9515/100629 [07:33<1:22:27, 18.42it/s]

  9%|▉         | 9518/100629 [07:33<1:23:10, 18.26it/s]

  9%|▉         | 9520/100629 [07:33<1:25:43, 17.71it/s]

  9%|▉         | 9522/100629 [07:33<1:25:08, 17.84it/s]

  9%|▉         | 9525/100629 [07:33<1:19:30, 19.10it/s]

  9%|▉         | 9527/100629 [07:33<1:19:36, 19.07it/s]

  9%|▉         | 9531/100629 [07:33<1:04:18, 23.61it/s]

  9%|▉         | 9534/100629 [07:33<1:07:52, 22.37it/s]

  9%|▉         | 9537/100629 [07:34<1:03:59, 23.73it/s]

  9%|▉         | 9540/100629 [07:34<1:37:29, 15.57it/s]

  9%|▉         | 9542/100629 [07:34<1:33:53, 16.17it/s]

  9%|▉         | 9544/100629 [07:34<1:31:10, 16.65it/s]

  9%|▉         | 9546/100629 [07:34<1:34:47, 16.02it/s]

  9%|▉         | 9548/100629 [07:34<1:32:00, 16.50it/s]

  9%|▉         | 9550/100629 [07:35<1:46:07, 14.30it/s]

  9%|▉         | 9553/100629 [07:35<1:32:52, 16.34it/s]

  9%|▉         | 9557/100629 [07:35<1:11:36, 21.20it/s]

 10%|▉         | 9560/100629 [07:35<1:21:48, 18.55it/s]

 10%|▉         | 9564/100629 [07:35<1:06:59, 22.65it/s]

 10%|▉         | 9567/100629 [07:35<1:03:16, 23.99it/s]

 10%|▉         | 9570/100629 [07:35<1:03:02, 24.07it/s]

 10%|▉         | 9573/100629 [07:35<59:32, 25.49it/s]

 10%|▉         | 9576/100629 [07:36<1:14:20, 20.41it/s]

 10%|▉         | 9579/100629 [07:36<1:10:51, 21.42it/s]

 10%|▉         | 9582/100629 [07:36<1:15:51, 20.00it/s]

 10%|▉         | 9585/100629 [07:36<1:13:40, 20.59it/s]

 10%|▉         | 9588/100629 [07:36<1:25:33, 17.74it/s]

 10%|▉         | 9591/100629 [07:36<1:23:47, 18.11it/s]

 10%|▉         | 9593/100629 [07:37<1:28:41, 17.11it/s]

 10%|▉         | 9597/100629 [07:37<1:18:22, 19.36it/s]

 10%|▉         | 9603/100629 [07:37<55:01, 27.57it/s]

 10%|▉         | 9607/100629 [07:37<51:26, 29.49it/s]

 10%|▉         | 9611/100629 [07:37<55:26, 27.36it/s]

 10%|▉         | 9615/100629 [07:37<1:00:11, 25.20it/s]

 10%|▉         | 9619/100629 [07:38<1:01:23, 24.71it/s]

 10%|▉         | 9622/100629 [07:38<1:15:51, 19.99it/s]

 10%|▉         | 9626/100629 [07:38<1:08:14, 22.23it/s]

 10%|▉         | 9630/100629 [07:38<1:02:21, 24.32it/s]

 10%|▉         | 9633/100629 [07:38<1:02:50, 24.13it/s]

 10%|▉         | 9636/100629 [07:38<1:08:24, 22.17it/s]

 10%|▉         | 9643/100629 [07:39<56:56, 26.63it/s]

 10%|▉         | 9648/100629 [07:39<48:53, 31.01it/s]

 10%|▉         | 9652/100629 [07:39<53:22, 28.41it/s]

 10%|▉         | 9655/100629 [07:39<57:01, 26.59it/s]

 10%|▉         | 9658/100629 [07:39<1:05:47, 23.05it/s]

 10%|▉         | 9663/100629 [07:39<55:31, 27.31it/s]

 10%|▉         | 9666/100629 [07:39<1:07:36, 22.43it/s]

 10%|▉         | 9670/100629 [07:40<1:04:43, 23.42it/s]

 10%|▉         | 9673/100629 [07:40<1:13:42, 20.56it/s]

 10%|▉         | 9677/100629 [07:40<1:04:51, 23.37it/s]

 10%|▉         | 9680/100629 [07:40<1:06:52, 22.67it/s]

 10%|▉         | 9683/100629 [07:40<1:02:37, 24.20it/s]

 10%|▉         | 9686/100629 [07:40<1:07:35, 22.42it/s]

 10%|▉         | 9689/100629 [07:40<1:06:11, 22.90it/s]

 10%|▉         | 9692/100629 [07:41<1:05:35, 23.10it/s]

 10%|▉         | 9695/100629 [07:41<1:02:09, 24.38it/s]

 10%|▉         | 9698/100629 [07:41<1:03:28, 23.87it/s]

 10%|▉         | 9701/100629 [07:41<59:43, 25.37it/s]

 10%|▉         | 9704/100629 [07:41<1:00:39, 24.98it/s]

 10%|▉         | 9707/100629 [07:41<1:08:41, 22.06it/s]

 10%|▉         | 9710/100629 [07:41<1:08:36, 22.09it/s]

 10%|▉         | 9713/100629 [07:41<1:04:08, 23.62it/s]

 10%|▉         | 9716/100629 [07:42<1:09:31, 21.80it/s]

 10%|▉         | 9720/100629 [07:42<1:08:54, 21.99it/s]

 10%|▉         | 9723/100629 [07:42<1:08:36, 22.08it/s]

 10%|▉         | 9726/100629 [07:42<1:05:33, 23.11it/s]

 10%|▉         | 9729/100629 [07:42<1:07:50, 22.33it/s]

 10%|▉         | 9732/100629 [07:42<1:13:57, 20.48it/s]

 10%|▉         | 9735/100629 [07:43<1:18:25, 19.32it/s]

 10%|▉         | 9737/100629 [07:43<1:26:38, 17.48it/s]

 10%|▉         | 9740/100629 [07:43<1:16:03, 19.92it/s]

 10%|▉         | 9743/100629 [07:43<1:20:58, 18.71it/s]

 10%|▉         | 9745/100629 [07:43<1:26:30, 17.51it/s]

 10%|▉         | 9747/100629 [07:43<1:28:17, 17.16it/s]

 10%|▉         | 9750/100629 [07:43<1:19:45, 18.99it/s]

 10%|▉         | 9753/100629 [07:43<1:14:43, 20.27it/s]

 10%|▉         | 9756/100629 [07:44<1:17:34, 19.52it/s]

 10%|▉         | 9759/100629 [07:44<1:09:59, 21.64it/s]

 10%|▉         | 9762/100629 [07:44<1:07:42, 22.37it/s]

 10%|▉         | 9765/100629 [07:44<1:14:22, 20.36it/s]

 10%|▉         | 9768/100629 [07:44<1:08:58, 21.95it/s]

 10%|▉         | 9771/100629 [07:44<1:12:56, 20.76it/s]

 10%|▉         | 9774/100629 [07:44<1:06:58, 22.61it/s]

 10%|▉         | 9777/100629 [07:45<1:02:10, 24.35it/s]

 10%|▉         | 9780/100629 [07:45<1:00:43, 24.93it/s]

 10%|▉         | 9783/100629 [07:45<1:03:51, 23.71it/s]

 10%|▉         | 9786/100629 [07:45<1:08:21, 22.15it/s]

 10%|▉         | 9789/100629 [07:45<1:03:25, 23.87it/s]

 10%|▉         | 9792/100629 [07:45<1:06:12, 22.87it/s]

 10%|▉         | 9795/100629 [07:45<1:08:11, 22.20it/s]

 10%|▉         | 9798/100629 [07:45<1:06:02, 22.92it/s]

 10%|▉         | 9801/100629 [07:46<1:11:47, 21.08it/s]

 10%|▉         | 9804/100629 [07:46<1:17:01, 19.65it/s]

 10%|▉         | 9807/100629 [07:46<1:23:26, 18.14it/s]

 10%|▉         | 9811/100629 [07:46<1:07:35, 22.40it/s]

 10%|▉         | 9816/100629 [07:46<57:34, 26.29it/s]

 10%|▉         | 9819/100629 [07:46<59:11, 25.57it/s]

 10%|▉         | 9822/100629 [07:46<58:24, 25.91it/s]

 10%|▉         | 9825/100629 [07:47<1:24:06, 17.99it/s]

 10%|▉         | 9828/100629 [07:47<1:23:02, 18.23it/s]

 10%|▉         | 9832/100629 [07:47<1:12:46, 20.79it/s]

 10%|▉         | 9835/100629 [07:47<1:11:38, 21.12it/s]

 10%|▉         | 9838/100629 [07:47<1:07:10, 22.53it/s]

 10%|▉         | 9841/100629 [07:47<1:04:18, 23.53it/s]

 10%|▉         | 9844/100629 [07:48<1:20:35, 18.77it/s]

 10%|▉         | 9849/100629 [07:48<1:01:12, 24.72it/s]

 10%|▉         | 9852/100629 [07:48<2:04:23, 12.16it/s]

 10%|▉         | 9855/100629 [07:49<1:48:23, 13.96it/s]

 10%|▉         | 9858/100629 [07:49<1:37:48, 15.47it/s]

 10%|▉         | 9862/100629 [07:49<1:18:49, 19.19it/s]

 10%|▉         | 9865/100629 [07:49<1:12:23, 20.90it/s]

 10%|▉         | 9868/100629 [07:49<1:17:07, 19.61it/s]

 10%|▉         | 9871/100629 [07:49<1:15:03, 20.15it/s]

 10%|▉         | 9874/100629 [07:49<1:08:39, 22.03it/s]

 10%|▉         | 9877/100629 [07:49<1:09:07, 21.88it/s]

 10%|▉         | 9880/100629 [07:50<1:09:38, 21.72it/s]

 10%|▉         | 9884/100629 [07:50<1:00:49, 24.86it/s]

 10%|▉         | 9887/100629 [07:50<1:00:27, 25.01it/s]

 10%|▉         | 9890/100629 [07:50<1:01:56, 24.42it/s]

 10%|▉         | 9893/100629 [07:50<1:00:59, 24.80it/s]

 10%|▉         | 9897/100629 [07:50<56:23, 26.81it/s]

 10%|▉         | 9900/100629 [07:50<1:12:28, 20.86it/s]

 10%|▉         | 9903/100629 [07:51<1:15:51, 19.93it/s]

 10%|▉         | 9908/100629 [07:51<1:01:42, 24.51it/s]

 10%|▉         | 9911/100629 [07:51<1:10:50, 21.34it/s]

 10%|▉         | 9915/100629 [07:51<1:07:04, 22.54it/s]

 10%|▉         | 9918/100629 [07:51<1:14:26, 20.31it/s]

 10%|▉         | 9921/100629 [07:51<1:13:29, 20.57it/s]

 10%|▉         | 9924/100629 [07:52<1:19:52, 18.93it/s]

 10%|▉         | 9927/100629 [07:52<1:11:43, 21.08it/s]

 10%|▉         | 9930/100629 [07:52<1:07:33, 22.37it/s]

 10%|▉         | 9933/100629 [07:52<1:15:06, 20.13it/s]

 10%|▉         | 9936/100629 [07:52<1:13:58, 20.43it/s]

 10%|▉         | 9939/100629 [07:52<1:18:33, 19.24it/s]

 10%|▉         | 9942/100629 [07:52<1:11:35, 21.11it/s]

 10%|▉         | 9945/100629 [07:53<1:11:17, 21.20it/s]

 10%|▉         | 9948/100629 [07:53<1:06:36, 22.69it/s]

 10%|▉         | 9951/100629 [07:53<1:11:23, 21.17it/s]

 10%|▉         | 9954/100629 [07:53<1:13:08, 20.66it/s]

 10%|▉         | 9957/100629 [07:53<1:09:33, 21.72it/s]

 10%|▉         | 9960/100629 [07:53<1:06:52, 22.60it/s]

 10%|▉         | 9963/100629 [07:53<1:13:07, 20.67it/s]

 10%|▉         | 9967/100629 [07:54<1:03:03, 23.96it/s]

 10%|▉         | 9970/100629 [07:54<1:07:22, 22.43it/s]

 10%|▉         | 9973/100629 [07:54<1:09:54, 21.61it/s]

 10%|▉         | 9976/100629 [07:54<1:16:25, 19.77it/s]

 10%|▉         | 9979/100629 [07:54<1:10:21, 21.47it/s]

 10%|▉         | 9982/100629 [07:54<1:06:08, 22.84it/s]

 10%|▉         | 9985/100629 [07:54<1:04:57, 23.26it/s]

 10%|▉         | 9989/100629 [07:55<1:00:16, 25.06it/s]

 10%|▉         | 9992/100629 [07:55<1:00:05, 25.14it/s]

 10%|▉         | 9995/100629 [07:55<1:03:08, 23.92it/s]

 10%|▉         | 9998/100629 [07:55<1:11:19, 21.18it/s]

 10%|▉         | 10001/100629 [07:55<1:07:02, 22.53it/s]

 10%|▉         | 10004/100629 [07:55<1:11:00, 21.27it/s]

 10%|▉         | 10007/100629 [07:55<1:06:12, 22.81it/s]

 10%|▉         | 10011/100629 [07:55<59:41, 25.30it/s]

 10%|▉         | 10014/100629 [07:56<1:10:56, 21.29it/s]

 10%|▉         | 10017/100629 [07:56<1:10:27, 21.43it/s]

 10%|▉         | 10020/100629 [07:56<1:13:40, 20.50it/s]

 10%|▉         | 10023/100629 [07:56<1:10:09, 21.52it/s]

 10%|▉         | 10026/100629 [07:56<1:11:01, 21.26it/s]

 10%|▉         | 10029/100629 [07:56<1:10:36, 21.39it/s]

 10%|▉         | 10033/100629 [07:56<1:01:14, 24.65it/s]

 10%|▉         | 10036/100629 [07:57<1:02:21, 24.21it/s]

 10%|▉         | 10039/100629 [07:57<59:59, 25.17it/s]

 10%|▉         | 10042/100629 [07:57<59:00, 25.59it/s]

 10%|▉         | 10045/100629 [07:57<58:52, 25.64it/s]

 10%|▉         | 10050/100629 [07:57<50:11, 30.07it/s]

 10%|▉         | 10054/100629 [07:57<1:06:22, 22.74it/s]

 10%|▉         | 10057/100629 [07:57<1:05:12, 23.15it/s]

 10%|▉         | 10060/100629 [07:58<1:05:43, 22.96it/s]

 10%|█         | 10063/100629 [07:58<1:09:47, 21.63it/s]

 10%|█         | 10067/100629 [07:58<1:03:11, 23.88it/s]

 10%|█         | 10070/100629 [07:58<1:00:38, 24.89it/s]

 10%|█         | 10074/100629 [07:58<59:58, 25.17it/s]

 10%|█         | 10077/100629 [07:58<1:09:26, 21.73it/s]

 10%|█         | 10080/100629 [07:59<1:21:54, 18.42it/s]

 10%|█         | 10082/100629 [07:59<1:24:04, 17.95it/s]

 10%|█         | 10086/100629 [07:59<1:19:05, 19.08it/s]

 10%|█         | 10090/100629 [07:59<1:11:44, 21.03it/s]

 10%|█         | 10093/100629 [07:59<1:14:41, 20.20it/s]

 10%|█         | 10096/100629 [07:59<1:10:40, 21.35it/s]

 10%|█         | 10099/100629 [07:59<1:11:56, 20.97it/s]

 10%|█         | 10102/100629 [08:00<1:12:59, 20.67it/s]

 10%|█         | 10105/100629 [08:00<1:13:37, 20.49it/s]

 10%|█         | 10108/100629 [08:00<1:12:25, 20.83it/s]

 10%|█         | 10111/100629 [08:00<1:11:16, 21.17it/s]

 10%|█         | 10116/100629 [08:00<59:17, 25.44it/s]

 10%|█         | 10119/100629 [08:00<1:09:07, 21.83it/s]

 10%|█         | 10122/100629 [08:01<1:11:49, 21.00it/s]

 10%|█         | 10126/100629 [08:01<1:01:01, 24.72it/s]

 10%|█         | 10129/100629 [08:01<58:33, 25.75it/s]

 10%|█         | 10132/100629 [08:01<1:01:34, 24.49it/s]

 10%|█         | 10135/100629 [08:01<1:00:32, 24.91it/s]

 10%|█         | 10139/100629 [08:01<55:10, 27.33it/s]

 10%|█         | 10142/100629 [08:01<1:01:29, 24.52it/s]

 10%|█         | 10145/100629 [08:02<1:31:15, 16.52it/s]

 10%|█         | 10148/100629 [08:02<1:23:23, 18.08it/s]

 10%|█         | 10151/100629 [08:02<1:24:48, 17.78it/s]

 10%|█         | 10155/100629 [08:02<1:14:05, 20.35it/s]

 10%|█         | 10158/100629 [08:02<1:12:50, 20.70it/s]

 10%|█         | 10162/100629 [08:02<1:10:29, 21.39it/s]

 10%|█         | 10165/100629 [08:03<1:23:10, 18.13it/s]

 10%|█         | 10167/100629 [08:03<1:29:27, 16.85it/s]

 10%|█         | 10169/100629 [08:03<1:28:02, 17.13it/s]

 10%|█         | 10171/100629 [08:03<1:26:48, 17.37it/s]

 10%|█         | 10175/100629 [08:03<1:07:35, 22.30it/s]

 10%|█         | 10180/100629 [08:03<1:01:38, 24.46it/s]

 10%|█         | 10183/100629 [08:03<1:09:14, 21.77it/s]

 10%|█         | 10186/100629 [08:04<1:27:41, 17.19it/s]

 10%|█         | 10188/100629 [08:04<1:34:43, 15.91it/s]

 10%|█         | 10190/100629 [08:04<1:39:21, 15.17it/s]

 10%|█         | 10193/100629 [08:04<1:29:22, 16.86it/s]

 10%|█         | 10196/100629 [08:04<1:28:07, 17.10it/s]

 10%|█         | 10199/100629 [08:04<1:17:01, 19.57it/s]

 10%|█         | 10202/100629 [08:05<1:11:57, 20.94it/s]

 10%|█         | 10207/100629 [08:05<56:47, 26.54it/s]

 10%|█         | 10210/100629 [08:05<1:05:41, 22.94it/s]

 10%|█         | 10213/100629 [08:05<1:28:06, 17.10it/s]

 10%|█         | 10216/100629 [08:05<1:30:58, 16.56it/s]

 10%|█         | 10218/100629 [08:05<1:29:19, 16.87it/s]

 10%|█         | 10221/100629 [08:06<1:20:06, 18.81it/s]

 10%|█         | 10224/100629 [08:06<1:13:29, 20.50it/s]

 10%|█         | 10227/100629 [08:06<1:23:02, 18.14it/s]

 10%|█         | 10229/100629 [08:06<1:23:19, 18.08it/s]

 10%|█         | 10231/100629 [08:06<1:28:07, 17.10it/s]

 10%|█         | 10233/100629 [08:06<1:31:26, 16.48it/s]

 10%|█         | 10235/100629 [08:06<1:35:07, 15.84it/s]

 10%|█         | 10238/100629 [08:07<1:19:33, 18.94it/s]

 10%|█         | 10241/100629 [08:07<1:19:54, 18.85it/s]

 10%|█         | 10243/100629 [08:07<1:37:11, 15.50it/s]

 10%|█         | 10245/100629 [08:07<1:34:16, 15.98it/s]

 10%|█         | 10247/100629 [08:07<1:38:15, 15.33it/s]

 10%|█         | 10250/100629 [08:07<1:24:35, 17.81it/s]

 10%|█         | 10253/100629 [08:07<1:17:33, 19.42it/s]

 10%|█         | 10256/100629 [08:08<1:21:05, 18.58it/s]

 10%|█         | 10259/100629 [08:08<1:12:14, 20.85it/s]

 10%|█         | 10263/100629 [08:08<1:02:56, 23.93it/s]

 10%|█         | 10266/100629 [08:08<1:06:46, 22.56it/s]

 10%|█         | 10269/100629 [08:08<1:12:23, 20.81it/s]

 10%|█         | 10272/100629 [08:08<1:11:57, 20.93it/s]

 10%|█         | 10275/100629 [08:08<1:14:04, 20.33it/s]

 10%|█         | 10278/100629 [08:09<1:12:47, 20.69it/s]

 10%|█         | 10281/100629 [08:09<1:19:59, 18.83it/s]

 10%|█         | 10283/100629 [08:09<1:23:47, 17.97it/s]

 10%|█         | 10285/100629 [08:09<1:27:30, 17.21it/s]

 10%|█         | 10289/100629 [08:09<1:17:53, 19.33it/s]

 10%|█         | 10291/100629 [08:09<1:24:45, 17.76it/s]

 10%|█         | 10294/100629 [08:09<1:21:05, 18.56it/s]

 10%|█         | 10296/100629 [08:10<1:36:07, 15.66it/s]

 10%|█         | 10298/100629 [08:10<2:03:12, 12.22it/s]

 10%|█         | 10300/100629 [08:10<1:58:54, 12.66it/s]

 10%|█         | 10303/100629 [08:10<1:38:53, 15.22it/s]

 10%|█         | 10306/100629 [08:10<1:25:14, 17.66it/s]

 10%|█         | 10308/100629 [08:11<1:40:54, 14.92it/s]

 10%|█         | 10311/100629 [08:11<1:47:44, 13.97it/s]

 10%|█         | 10314/100629 [08:11<1:34:36, 15.91it/s]

 10%|█         | 10316/100629 [08:11<1:36:22, 15.62it/s]

 10%|█         | 10318/100629 [08:11<1:38:06, 15.34it/s]

 10%|█         | 10320/100629 [08:11<1:33:53, 16.03it/s]

 10%|█         | 10324/100629 [08:11<1:17:48, 19.34it/s]

 10%|█         | 10327/100629 [08:12<1:09:19, 21.71it/s]

 10%|█         | 10330/100629 [08:12<1:11:31, 21.04it/s]

 10%|█         | 10333/100629 [08:12<1:09:28, 21.66it/s]

 10%|█         | 10338/100629 [08:12<55:16, 27.22it/s]

 10%|█         | 10341/100629 [08:12<57:06, 26.35it/s]

 10%|█         | 10345/100629 [08:12<58:59, 25.51it/s]

 10%|█         | 10350/100629 [08:12<50:04, 30.05it/s]

 10%|█         | 10356/100629 [08:13<51:34, 29.18it/s]

 10%|█         | 10360/100629 [08:13<1:06:14, 22.71it/s]

 10%|█         | 10363/100629 [08:13<1:06:43, 22.55it/s]

 10%|█         | 10366/100629 [08:13<1:09:30, 21.64it/s]

 10%|█         | 10370/100629 [08:13<1:07:42, 22.22it/s]

 10%|█         | 10373/100629 [08:13<1:09:09, 21.75it/s]

 10%|█         | 10376/100629 [08:14<1:06:37, 22.58it/s]

 10%|█         | 10379/100629 [08:14<1:03:54, 23.54it/s]

 10%|█         | 10382/100629 [08:14<1:02:12, 24.18it/s]

 10%|█         | 10385/100629 [08:14<1:01:45, 24.35it/s]

 10%|█         | 10389/100629 [08:14<58:32, 25.69it/s]

 10%|█         | 10393/100629 [08:14<59:05, 25.45it/s]

 10%|█         | 10397/100629 [08:14<55:39, 27.02it/s]

 10%|█         | 10400/100629 [08:15<1:04:41, 23.25it/s]

 10%|█         | 10403/100629 [08:15<1:25:35, 17.57it/s]

 10%|█         | 10405/100629 [08:15<1:36:02, 15.66it/s]

 10%|█         | 10407/100629 [08:15<1:36:44, 15.54it/s]

 10%|█         | 10409/100629 [08:15<1:41:21, 14.83it/s]

 10%|█         | 10412/100629 [08:15<1:29:51, 16.73it/s]

 10%|█         | 10414/100629 [08:16<1:27:46, 17.13it/s]

 10%|█         | 10416/100629 [08:16<1:29:30, 16.80it/s]

 10%|█         | 10418/100629 [08:16<1:32:43, 16.22it/s]

 10%|█         | 10420/100629 [08:16<1:34:20, 15.94it/s]

 10%|█         | 10422/100629 [08:16<1:30:45, 16.56it/s]

 10%|█         | 10425/100629 [08:16<1:17:17, 19.45it/s]

 10%|█         | 10428/100629 [08:16<1:11:15, 21.10it/s]

 10%|█         | 10431/100629 [08:16<1:08:42, 21.88it/s]

 10%|█         | 10434/100629 [08:17<1:11:57, 20.89it/s]

 10%|█         | 10438/100629 [08:17<59:07, 25.42it/s]

 10%|█         | 10441/100629 [08:17<1:05:21, 23.00it/s]

 10%|█         | 10444/100629 [08:17<1:17:24, 19.42it/s]

 10%|█         | 10447/100629 [08:17<1:26:52, 17.30it/s]

 10%|█         | 10450/100629 [08:17<1:18:57, 19.04it/s]

 10%|█         | 10454/100629 [08:18<1:10:24, 21.35it/s]

 10%|█         | 10458/100629 [08:18<1:04:32, 23.28it/s]

 10%|█         | 10461/100629 [08:18<1:02:51, 23.91it/s]

 10%|█         | 10464/100629 [08:18<1:03:02, 23.84it/s]

 10%|█         | 10467/100629 [08:18<1:11:41, 20.96it/s]

 10%|█         | 10470/100629 [08:18<1:06:20, 22.65it/s]

 10%|█         | 10473/100629 [08:18<1:17:11, 19.47it/s]

 10%|█         | 10476/100629 [08:19<1:22:38, 18.18it/s]

 10%|█         | 10479/100629 [08:19<1:22:48, 18.14it/s]

 10%|█         | 10482/100629 [08:19<1:18:29, 19.14it/s]

 10%|█         | 10484/100629 [08:19<1:18:58, 19.02it/s]

 10%|█         | 10486/100629 [08:19<1:20:30, 18.66it/s]

 10%|█         | 10489/100629 [08:19<1:15:02, 20.02it/s]

 10%|█         | 10493/100629 [08:19<1:07:22, 22.30it/s]

 10%|█         | 10496/100629 [08:20<1:04:50, 23.17it/s]

 10%|█         | 10500/100629 [08:20<1:02:47, 23.92it/s]

 10%|█         | 10504/100629 [08:20<59:41, 25.16it/s]

 10%|█         | 10507/100629 [08:20<1:06:16, 22.67it/s]

 10%|█         | 10510/100629 [08:20<1:06:12, 22.69it/s]

 10%|█         | 10513/100629 [08:20<1:08:09, 22.03it/s]

 10%|█         | 10516/100629 [08:20<1:13:38, 20.40it/s]

 10%|█         | 10520/100629 [08:21<1:05:00, 23.10it/s]

 10%|█         | 10523/100629 [08:21<1:05:20, 22.99it/s]

 10%|█         | 10526/100629 [08:21<1:09:43, 21.54it/s]

 10%|█         | 10529/100629 [08:21<1:04:36, 23.24it/s]

 10%|█         | 10534/100629 [08:21<51:33, 29.12it/s]

 10%|█         | 10538/100629 [08:21<57:56, 25.91it/s]

 10%|█         | 10541/100629 [08:21<56:52, 26.40it/s]

 10%|█         | 10545/100629 [08:22<1:00:00, 25.02it/s]

 10%|█         | 10548/100629 [08:22<57:47, 25.98it/s]

 10%|█         | 10551/100629 [08:22<58:28, 25.67it/s]

 10%|█         | 10554/100629 [08:22<57:32, 26.09it/s]

 10%|█         | 10557/100629 [08:22<1:10:08, 21.40it/s]

 10%|█         | 10560/100629 [08:22<1:05:21, 22.97it/s]

 10%|█         | 10563/100629 [08:22<1:04:38, 23.22it/s]

 10%|█         | 10566/100629 [08:22<1:00:52, 24.65it/s]

 11%|█         | 10569/100629 [08:23<1:05:33, 22.89it/s]

 11%|█         | 10572/100629 [08:23<1:03:42, 23.56it/s]

 11%|█         | 10576/100629 [08:23<1:03:59, 23.45it/s]

 11%|█         | 10579/100629 [08:23<1:07:55, 22.09it/s]

 11%|█         | 10583/100629 [08:23<58:37, 25.60it/s]

 11%|█         | 10586/100629 [08:23<1:01:46, 24.29it/s]

 11%|█         | 10589/100629 [08:23<1:07:00, 22.39it/s]

 11%|█         | 10592/100629 [08:24<1:11:06, 21.11it/s]

 11%|█         | 10595/100629 [08:24<1:05:51, 22.78it/s]

 11%|█         | 10599/100629 [08:24<1:02:25, 24.04it/s]

 11%|█         | 10602/100629 [08:24<1:18:00, 19.23it/s]

 11%|█         | 10608/100629 [08:24<58:37, 25.59it/s]

 11%|█         | 10612/100629 [08:24<53:38, 27.97it/s]

 11%|█         | 10616/100629 [08:25<59:47, 25.09it/s]

 11%|█         | 10619/100629 [08:25<1:02:32, 23.99it/s]

 11%|█         | 10622/100629 [08:25<1:10:05, 21.40it/s]

 11%|█         | 10625/100629 [08:25<1:07:25, 22.25it/s]

 11%|█         | 10628/100629 [08:25<1:10:15, 21.35it/s]

 11%|█         | 10631/100629 [08:25<1:05:53, 22.76it/s]

 11%|█         | 10634/100629 [08:25<1:02:46, 23.89it/s]

 11%|█         | 10637/100629 [08:25<1:03:46, 23.52it/s]

 11%|█         | 10640/100629 [08:26<1:11:05, 21.10it/s]

 11%|█         | 10643/100629 [08:26<1:17:03, 19.46it/s]

 11%|█         | 10646/100629 [08:26<1:15:14, 19.93it/s]

 11%|█         | 10649/100629 [08:26<1:10:32, 21.26it/s]

 11%|█         | 10652/100629 [08:26<1:19:09, 18.95it/s]

 11%|█         | 10655/100629 [08:26<1:13:06, 20.51it/s]

 11%|█         | 10658/100629 [08:27<1:13:49, 20.31it/s]

 11%|█         | 10661/100629 [08:27<1:12:39, 20.64it/s]

 11%|█         | 10664/100629 [08:27<1:07:26, 22.23it/s]

 11%|█         | 10667/100629 [08:27<1:11:02, 21.10it/s]

 11%|█         | 10671/100629 [08:27<59:05, 25.37it/s]

 11%|█         | 10674/100629 [08:27<1:03:10, 23.73it/s]

 11%|█         | 10677/100629 [08:27<1:13:25, 20.42it/s]

 11%|█         | 10680/100629 [08:28<1:16:54, 19.49it/s]

 11%|█         | 10684/100629 [08:28<1:09:31, 21.56it/s]

 11%|█         | 10687/100629 [08:28<1:10:12, 21.35it/s]

 11%|█         | 10690/100629 [08:28<1:11:11, 21.06it/s]

 11%|█         | 10693/100629 [08:28<1:17:56, 19.23it/s]

 11%|█         | 10696/100629 [08:28<1:17:35, 19.32it/s]

 11%|█         | 10699/100629 [08:28<1:11:26, 20.98it/s]

 11%|█         | 10702/100629 [08:29<1:09:40, 21.51it/s]

 11%|█         | 10705/100629 [08:29<1:05:36, 22.85it/s]

 11%|█         | 10708/100629 [08:29<1:11:02, 21.10it/s]

 11%|█         | 10711/100629 [08:29<1:14:19, 20.16it/s]

 11%|█         | 10714/100629 [08:29<1:15:49, 19.76it/s]

 11%|█         | 10717/100629 [08:29<1:19:35, 18.83it/s]

 11%|█         | 10720/100629 [08:30<1:14:37, 20.08it/s]

 11%|█         | 10723/100629 [08:30<1:07:35, 22.17it/s]

 11%|█         | 10726/100629 [08:30<1:11:12, 21.04it/s]

 11%|█         | 10729/100629 [08:30<1:06:03, 22.68it/s]

 11%|█         | 10732/100629 [08:30<1:03:10, 23.72it/s]

 11%|█         | 10736/100629 [08:30<54:05, 27.70it/s]

 11%|█         | 10739/100629 [08:30<58:03, 25.81it/s]

 11%|█         | 10742/100629 [08:30<1:02:19, 24.04it/s]

 11%|█         | 10745/100629 [08:31<1:08:16, 21.94it/s]

 11%|█         | 10748/100629 [08:31<1:16:32, 19.57it/s]

 11%|█         | 10751/100629 [08:31<1:19:52, 18.75it/s]

 11%|█         | 10754/100629 [08:31<1:13:52, 20.28it/s]

 11%|█         | 10757/100629 [08:31<1:09:12, 21.64it/s]

 11%|█         | 10760/100629 [08:31<1:19:16, 18.89it/s]

 11%|█         | 10763/100629 [08:32<1:16:40, 19.53it/s]

 11%|█         | 10769/100629 [08:32<53:36, 27.94it/s]

 11%|█         | 10773/100629 [08:32<53:13, 28.13it/s]

 11%|█         | 10777/100629 [08:32<51:14, 29.23it/s]

 11%|█         | 10782/100629 [08:32<46:47, 32.01it/s]

 11%|█         | 10786/100629 [08:32<55:53, 26.79it/s]

 11%|█         | 10789/100629 [08:32<1:03:59, 23.40it/s]

 11%|█         | 10792/100629 [08:33<1:02:15, 24.05it/s]

 11%|█         | 10796/100629 [08:33<55:13, 27.11it/s]

 11%|█         | 10799/100629 [08:33<56:54, 26.31it/s]

 11%|█         | 10802/100629 [08:33<1:01:36, 24.30it/s]

 11%|█         | 10805/100629 [08:33<1:20:30, 18.59it/s]

 11%|█         | 10808/100629 [08:33<1:19:47, 18.76it/s]

 11%|█         | 10811/100629 [08:34<1:25:01, 17.61it/s]

 11%|█         | 10813/100629 [08:34<2:01:39, 12.30it/s]

 11%|█         | 10816/100629 [08:34<1:41:12, 14.79it/s]

 11%|█         | 10818/100629 [08:34<1:38:12, 15.24it/s]

 11%|█         | 10821/100629 [08:34<1:22:35, 18.12it/s]

 11%|█         | 10824/100629 [08:34<1:20:12, 18.66it/s]

 11%|█         | 10828/100629 [08:35<1:21:30, 18.36it/s]

 11%|█         | 10831/100629 [08:35<1:17:44, 19.25it/s]

 11%|█         | 10834/100629 [08:35<1:27:43, 17.06it/s]

 11%|█         | 10837/100629 [08:35<1:18:03, 19.17it/s]

 11%|█         | 10841/100629 [08:35<1:10:55, 21.10it/s]

 11%|█         | 10844/100629 [08:35<1:18:49, 18.98it/s]

 11%|█         | 10848/100629 [08:36<1:11:18, 20.98it/s]

 11%|█         | 10851/100629 [08:36<1:22:27, 18.15it/s]

 11%|█         | 10853/100629 [08:36<1:26:48, 17.23it/s]

 11%|█         | 10855/100629 [08:36<1:25:10, 17.57it/s]

 11%|█         | 10858/100629 [08:36<1:19:28, 18.83it/s]

 11%|█         | 10861/100629 [08:36<1:11:53, 20.81it/s]

 11%|█         | 10864/100629 [08:36<1:07:48, 22.07it/s]

 11%|█         | 10867/100629 [08:37<1:33:52, 15.94it/s]

 11%|█         | 10870/100629 [08:37<1:25:51, 17.42it/s]

 11%|█         | 10873/100629 [08:37<1:16:09, 19.64it/s]

 11%|█         | 10876/100629 [08:37<1:27:35, 17.08it/s]

 11%|█         | 10879/100629 [08:37<1:22:28, 18.13it/s]

 11%|█         | 10881/100629 [08:37<1:23:13, 17.97it/s]

 11%|█         | 10883/100629 [08:38<1:21:40, 18.31it/s]

 11%|█         | 10887/100629 [08:38<1:04:26, 23.21it/s]

 11%|█         | 10890/100629 [08:38<1:08:16, 21.91it/s]

 11%|█         | 10893/100629 [08:38<1:07:21, 22.20it/s]

 11%|█         | 10896/100629 [08:38<1:04:18, 23.25it/s]

 11%|█         | 10899/100629 [08:38<1:10:06, 21.33it/s]

 11%|█         | 10902/100629 [08:38<1:32:24, 16.18it/s]

 11%|█         | 10904/100629 [08:39<1:43:13, 14.49it/s]

 11%|█         | 10906/100629 [08:39<1:37:21, 15.36it/s]

 11%|█         | 10910/100629 [08:39<1:15:09, 19.89it/s]

 11%|█         | 10914/100629 [08:39<1:01:57, 24.13it/s]

 11%|█         | 10917/100629 [08:39<1:10:02, 21.35it/s]

 11%|█         | 10921/100629 [08:39<1:04:26, 23.20it/s]

 11%|█         | 10924/100629 [08:39<1:03:59, 23.36it/s]

 11%|█         | 10927/100629 [08:40<1:02:18, 23.99it/s]

 11%|█         | 10931/100629 [08:40<55:40, 26.85it/s]

 11%|█         | 10935/100629 [08:40<53:22, 28.01it/s]

 11%|█         | 10938/100629 [08:40<58:46, 25.43it/s]

 11%|█         | 10941/100629 [08:40<1:04:46, 23.08it/s]

 11%|█         | 10944/100629 [08:40<1:01:53, 24.15it/s]

 11%|█         | 10947/100629 [08:41<1:23:33, 17.89it/s]

 11%|█         | 10950/100629 [08:41<1:21:00, 18.45it/s]

 11%|█         | 10953/100629 [08:41<1:14:33, 20.05it/s]

 11%|█         | 10956/100629 [08:41<1:07:31, 22.13it/s]

 11%|█         | 10959/100629 [08:41<1:18:14, 19.10it/s]

 11%|█         | 10962/100629 [08:41<1:12:28, 20.62it/s]

 11%|█         | 10965/100629 [08:41<1:21:43, 18.28it/s]

 11%|█         | 10968/100629 [08:42<1:20:22, 18.59it/s]

 11%|█         | 10972/100629 [08:42<1:08:26, 21.83it/s]

 11%|█         | 10975/100629 [08:42<1:20:16, 18.61it/s]

 11%|█         | 10978/100629 [08:42<1:20:24, 18.58it/s]

 11%|█         | 10981/100629 [08:42<1:14:24, 20.08it/s]

 11%|█         | 10984/100629 [08:42<1:14:23, 20.08it/s]

 11%|█         | 10987/100629 [08:43<1:18:06, 19.13it/s]

 11%|█         | 10990/100629 [08:43<1:13:41, 20.27it/s]

 11%|█         | 10993/100629 [08:43<1:14:34, 20.03it/s]

 11%|█         | 10996/100629 [08:43<1:10:21, 21.23it/s]

 11%|█         | 10999/100629 [08:43<1:17:34, 19.26it/s]

 11%|█         | 11002/100629 [08:43<1:10:23, 21.22it/s]

 11%|█         | 11005/100629 [08:43<1:05:21, 22.86it/s]

 11%|█         | 11008/100629 [08:43<1:02:59, 23.71it/s]

 11%|█         | 11012/100629 [08:44<56:08, 26.61it/s]

 11%|█         | 11015/100629 [08:44<1:01:53, 24.13it/s]

 11%|█         | 11018/100629 [08:44<1:11:00, 21.03it/s]

 11%|█         | 11021/100629 [08:44<1:08:21, 21.85it/s]

 11%|█         | 11025/100629 [08:44<59:42, 25.01it/s]

 11%|█         | 11028/100629 [08:44<58:18, 25.61it/s]

 11%|█         | 11031/100629 [08:44<56:48, 26.29it/s]

 11%|█         | 11034/100629 [08:44<55:03, 27.12it/s]

 11%|█         | 11037/100629 [08:45<1:01:14, 24.38it/s]

 11%|█         | 11040/100629 [08:45<1:01:01, 24.47it/s]

 11%|█         | 11044/100629 [08:45<58:32, 25.50it/s]

 11%|█         | 11047/100629 [08:45<1:12:24, 20.62it/s]

 11%|█         | 11050/100629 [08:45<1:08:36, 21.76it/s]

 11%|█         | 11057/100629 [08:45<46:22, 32.19it/s]

 11%|█         | 11061/100629 [08:45<48:36, 30.71it/s]

 11%|█         | 11065/100629 [08:46<53:45, 27.77it/s]

 11%|█         | 11069/100629 [08:46<1:01:11, 24.39it/s]

 11%|█         | 11072/100629 [08:46<1:06:55, 22.30it/s]

 11%|█         | 11075/100629 [08:46<1:05:03, 22.94it/s]

 11%|█         | 11079/100629 [08:46<56:26, 26.44it/s]

 11%|█         | 11083/100629 [08:46<54:04, 27.60it/s]

 11%|█         | 11087/100629 [08:47<52:01, 28.69it/s]

 11%|█         | 11090/100629 [08:47<57:23, 26.00it/s]

 11%|█         | 11093/100629 [08:47<1:03:04, 23.66it/s]

 11%|█         | 11096/100629 [08:47<1:07:04, 22.25it/s]

 11%|█         | 11099/100629 [08:47<1:03:13, 23.60it/s]

 11%|█         | 11102/100629 [08:47<1:12:37, 20.55it/s]

 11%|█         | 11105/100629 [08:47<1:11:11, 20.96it/s]

 11%|█         | 11108/100629 [08:48<1:12:01, 20.71it/s]

 11%|█         | 11111/100629 [08:48<1:10:55, 21.04it/s]

 11%|█         | 11114/100629 [08:48<1:09:37, 21.43it/s]

 11%|█         | 11117/100629 [08:48<1:14:45, 19.96it/s]

 11%|█         | 11120/100629 [08:48<1:32:02, 16.21it/s]

 11%|█         | 11122/100629 [08:48<1:37:40, 15.27it/s]

 11%|█         | 11124/100629 [08:49<1:40:53, 14.78it/s]

 11%|█         | 11126/100629 [08:49<1:41:59, 14.63it/s]

 11%|█         | 11129/100629 [08:49<1:27:53, 16.97it/s]

 11%|█         | 11132/100629 [08:49<1:21:53, 18.22it/s]

 11%|█         | 11134/100629 [08:49<1:30:11, 16.54it/s]

 11%|█         | 11137/100629 [08:49<1:22:28, 18.08it/s]

 11%|█         | 11139/100629 [08:49<1:38:55, 15.08it/s]

 11%|█         | 11141/100629 [08:50<1:41:11, 14.74it/s]

 11%|█         | 11143/100629 [08:50<1:43:18, 14.44it/s]

 11%|█         | 11145/100629 [08:50<1:41:49, 14.65it/s]

 11%|█         | 11147/100629 [08:50<1:49:27, 13.62it/s]

 11%|█         | 11149/100629 [08:50<1:45:56, 14.08it/s]

 11%|█         | 11152/100629 [08:50<1:27:56, 16.96it/s]

 11%|█         | 11155/100629 [08:50<1:17:22, 19.27it/s]

 11%|█         | 11158/100629 [08:51<1:09:11, 21.55it/s]

 11%|█         | 11161/100629 [08:51<1:09:14, 21.53it/s]

 11%|█         | 11164/100629 [08:51<1:12:17, 20.63it/s]

 11%|█         | 11168/100629 [08:51<1:04:03, 23.28it/s]

 11%|█         | 11172/100629 [08:51<1:00:00, 24.85it/s]

 11%|█         | 11175/100629 [08:51<1:08:35, 21.73it/s]

 11%|█         | 11178/100629 [08:52<1:16:50, 19.40it/s]

 11%|█         | 11181/100629 [08:52<1:10:16, 21.22it/s]

 11%|█         | 11184/100629 [08:52<1:16:24, 19.51it/s]

 11%|█         | 11187/100629 [08:52<1:15:26, 19.76it/s]

 11%|█         | 11190/100629 [08:52<1:19:08, 18.83it/s]

 11%|█         | 11192/100629 [08:52<1:22:32, 18.06it/s]

 11%|█         | 11195/100629 [08:52<1:17:30, 19.23it/s]

 11%|█         | 11199/100629 [08:53<1:07:58, 21.93it/s]

 11%|█         | 11202/100629 [08:53<1:28:11, 16.90it/s]

 11%|█         | 11205/100629 [08:53<1:17:50, 19.15it/s]

 11%|█         | 11208/100629 [08:53<1:16:41, 19.43it/s]

 11%|█         | 11212/100629 [08:53<1:04:02, 23.27it/s]

 11%|█         | 11215/100629 [08:53<1:12:28, 20.56it/s]

 11%|█         | 11218/100629 [08:54<1:20:28, 18.52it/s]

 11%|█         | 11221/100629 [08:55<4:41:53,  5.29it/s]

 11%|█         | 11224/100629 [08:55<3:36:44,  6.88it/s]

 11%|█         | 11226/100629 [08:55<3:06:33,  7.99it/s]

 11%|█         | 11229/100629 [08:56<2:37:18,  9.47it/s]

 11%|█         | 11236/100629 [08:56<1:30:05, 16.54it/s]

 11%|█         | 11240/100629 [08:56<1:19:49, 18.66it/s]

 11%|█         | 11243/100629 [08:56<1:13:06, 20.38it/s]

 11%|█         | 11246/100629 [08:56<1:18:26, 18.99it/s]

 11%|█         | 11249/100629 [08:56<1:23:22, 17.87it/s]

 11%|█         | 11252/100629 [08:56<1:20:06, 18.60it/s]

 11%|█         | 11255/100629 [08:57<1:18:57, 18.86it/s]

 11%|█         | 11258/100629 [08:57<1:14:25, 20.01it/s]

 11%|█         | 11261/100629 [08:57<1:24:27, 17.64it/s]

 11%|█         | 11264/100629 [08:57<1:23:54, 17.75it/s]

 11%|█         | 11266/100629 [08:57<1:32:24, 16.12it/s]

 11%|█         | 11268/100629 [08:57<1:32:09, 16.16it/s]

 11%|█         | 11271/100629 [08:58<1:20:00, 18.61it/s]

 11%|█         | 11275/100629 [08:58<1:04:52, 22.95it/s]

 11%|█         | 11278/100629 [08:58<1:04:32, 23.07it/s]

 11%|█         | 11281/100629 [08:58<1:04:31, 23.08it/s]

 11%|█         | 11284/100629 [08:58<1:20:28, 18.50it/s]

 11%|█         | 11287/100629 [08:58<1:18:40, 18.93it/s]

 11%|█         | 11290/100629 [08:58<1:27:39, 16.98it/s]

 11%|█         | 11294/100629 [08:59<1:12:58, 20.40it/s]

 11%|█         | 11298/100629 [08:59<1:05:01, 22.90it/s]

 11%|█         | 11302/100629 [08:59<1:00:37, 24.56it/s]

 11%|█         | 11306/100629 [08:59<55:45, 26.70it/s]

 11%|█         | 11309/100629 [08:59<1:00:00, 24.81it/s]

 11%|█         | 11312/100629 [08:59<57:17, 25.98it/s]

 11%|█         | 11315/100629 [08:59<1:06:34, 22.36it/s]

 11%|█         | 11318/100629 [09:00<1:14:57, 19.86it/s]

 11%|█▏        | 11321/100629 [09:00<1:24:18, 17.65it/s]

 11%|█▏        | 11324/100629 [09:00<1:19:44, 18.67it/s]

 11%|█▏        | 11327/100629 [09:00<1:16:18, 19.50it/s]

 11%|█▏        | 11330/100629 [09:00<1:12:08, 20.63it/s]

 11%|█▏        | 11334/100629 [09:00<1:02:33, 23.79it/s]

 11%|█▏        | 11337/100629 [09:00<1:02:01, 23.99it/s]

 11%|█▏        | 11341/100629 [09:01<58:58, 25.23it/s]

 11%|█▏        | 11344/100629 [09:01<1:01:35, 24.16it/s]

 11%|█▏        | 11347/100629 [09:01<1:00:34, 24.56it/s]

 11%|█▏        | 11350/100629 [09:01<1:06:53, 22.25it/s]

 11%|█▏        | 11353/100629 [09:01<1:04:30, 23.07it/s]

 11%|█▏        | 11356/100629 [09:01<1:13:01, 20.37it/s]

 11%|█▏        | 11359/100629 [09:01<1:10:31, 21.09it/s]

 11%|█▏        | 11362/100629 [09:02<1:11:03, 20.94it/s]

 11%|█▏        | 11365/100629 [09:02<1:12:31, 20.51it/s]

 11%|█▏        | 11370/100629 [09:02<57:02, 26.08it/s]

 11%|█▏        | 11373/100629 [09:02<58:41, 25.35it/s]

 11%|█▏        | 11377/100629 [09:02<56:25, 26.36it/s]

 11%|█▏        | 11380/100629 [09:02<58:35, 25.38it/s]

 11%|█▏        | 11383/100629 [09:03<1:11:15, 20.87it/s]

 11%|█▏        | 11386/100629 [09:03<1:07:27, 22.05it/s]

 11%|█▏        | 11390/100629 [09:03<1:01:00, 24.38it/s]

 11%|█▏        | 11394/100629 [09:03<1:00:20, 24.65it/s]

 11%|█▏        | 11397/100629 [09:03<58:10, 25.57it/s]

 11%|█▏        | 11400/100629 [09:03<1:03:01, 23.60it/s]

 11%|█▏        | 11403/100629 [09:03<1:02:51, 23.66it/s]

 11%|█▏        | 11406/100629 [09:04<1:17:02, 19.30it/s]

 11%|█▏        | 11409/100629 [09:04<1:17:14, 19.25it/s]

 11%|█▏        | 11412/100629 [09:04<1:17:11, 19.26it/s]

 11%|█▏        | 11415/100629 [09:04<1:17:31, 19.18it/s]

 11%|█▏        | 11417/100629 [09:04<1:17:13, 19.25it/s]

 11%|█▏        | 11420/100629 [09:04<1:13:52, 20.13it/s]

 11%|█▏        | 11423/100629 [09:04<1:11:37, 20.76it/s]

 11%|█▏        | 11426/100629 [09:04<1:06:48, 22.26it/s]

 11%|█▏        | 11429/100629 [09:05<1:25:38, 17.36it/s]

 11%|█▏        | 11432/100629 [09:05<1:20:09, 18.55it/s]

 11%|█▏        | 11435/100629 [09:05<1:12:26, 20.52it/s]

 11%|█▏        | 11438/100629 [09:05<1:08:46, 21.62it/s]

 11%|█▏        | 11441/100629 [09:05<1:09:48, 21.29it/s]

 11%|█▏        | 11444/100629 [09:05<1:07:17, 22.09it/s]

 11%|█▏        | 11447/100629 [09:06<1:15:46, 19.61it/s]

 11%|█▏        | 11450/100629 [09:06<1:08:49, 21.60it/s]

 11%|█▏        | 11453/100629 [09:06<1:07:56, 21.88it/s]

 11%|█▏        | 11456/100629 [09:06<1:03:39, 23.35it/s]

 11%|█▏        | 11460/100629 [09:06<1:00:13, 24.68it/s]

 11%|█▏        | 11463/100629 [09:06<1:00:15, 24.66it/s]

 11%|█▏        | 11467/100629 [09:06<56:42, 26.20it/s]

 11%|█▏        | 11470/100629 [09:06<58:59, 25.19it/s]

 11%|█▏        | 11473/100629 [09:07<59:19, 25.05it/s]

 11%|█▏        | 11477/100629 [09:07<57:45, 25.72it/s]

 11%|█▏        | 11481/100629 [09:07<1:02:46, 23.67it/s]

 11%|█▏        | 11485/100629 [09:07<57:52, 25.67it/s]

 11%|█▏        | 11488/100629 [09:07<58:52, 25.24it/s]

 11%|█▏        | 11492/100629 [09:07<56:10, 26.44it/s]

 11%|█▏        | 11495/100629 [09:07<54:46, 27.12it/s]

 11%|█▏        | 11498/100629 [09:08<1:03:28, 23.41it/s]

 11%|█▏        | 11501/100629 [09:08<1:10:41, 21.01it/s]

 11%|█▏        | 11504/100629 [09:08<1:09:25, 21.40it/s]

 11%|█▏        | 11507/100629 [09:08<1:11:38, 20.73it/s]

 11%|█▏        | 11510/100629 [09:08<1:11:54, 20.65it/s]

 11%|█▏        | 11513/100629 [09:08<1:21:45, 18.17it/s]

 11%|█▏        | 11516/100629 [09:09<1:17:02, 19.28it/s]

 11%|█▏        | 11519/100629 [09:09<1:08:59, 21.53it/s]

 11%|█▏        | 11522/100629 [09:09<1:07:45, 21.92it/s]

 11%|█▏        | 11526/100629 [09:09<1:01:22, 24.20it/s]

 11%|█▏        | 11529/100629 [09:09<1:04:21, 23.08it/s]

 11%|█▏        | 11532/100629 [09:09<1:10:57, 20.93it/s]

 11%|█▏        | 11536/100629 [09:09<1:01:25, 24.18it/s]

 11%|█▏        | 11539/100629 [09:10<1:02:23, 23.80it/s]

 11%|█▏        | 11542/100629 [09:10<1:07:04, 22.14it/s]

 11%|█▏        | 11545/100629 [09:10<1:25:16, 17.41it/s]

 11%|█▏        | 11548/100629 [09:10<1:24:50, 17.50it/s]

 11%|█▏        | 11550/100629 [09:10<1:37:38, 15.20it/s]

 11%|█▏        | 11553/100629 [09:10<1:26:50, 17.09it/s]

 11%|█▏        | 11556/100629 [09:11<1:19:32, 18.66it/s]

 11%|█▏        | 11559/100629 [09:11<1:15:34, 19.64it/s]

 11%|█▏        | 11562/100629 [09:11<1:07:52, 21.87it/s]

 11%|█▏        | 11565/100629 [09:11<1:38:47, 15.03it/s]

 11%|█▏        | 11568/100629 [09:11<1:40:40, 14.75it/s]

 11%|█▏        | 11571/100629 [09:11<1:28:02, 16.86it/s]

 12%|█▏        | 11574/100629 [09:12<1:16:50, 19.32it/s]

 12%|█▏        | 11577/100629 [09:12<1:09:39, 21.31it/s]

 12%|█▏        | 11581/100629 [09:12<1:02:36, 23.71it/s]

 12%|█▏        | 11584/100629 [09:12<1:03:03, 23.54it/s]

 12%|█▏        | 11587/100629 [09:12<1:02:48, 23.63it/s]

 12%|█▏        | 11590/100629 [09:12<1:14:02, 20.04it/s]

 12%|█▏        | 11593/100629 [09:12<1:11:15, 20.82it/s]

 12%|█▏        | 11596/100629 [09:13<1:16:20, 19.44it/s]

 12%|█▏        | 11599/100629 [09:13<1:14:20, 19.96it/s]

 12%|█▏        | 11602/100629 [09:13<1:22:01, 18.09it/s]

 12%|█▏        | 11604/100629 [09:13<1:23:02, 17.87it/s]

 12%|█▏        | 11607/100629 [09:13<1:14:03, 20.04it/s]

 12%|█▏        | 11610/100629 [09:13<1:20:55, 18.33it/s]

 12%|█▏        | 11612/100629 [09:13<1:27:54, 16.88it/s]

 12%|█▏        | 11615/100629 [09:14<1:23:57, 17.67it/s]

 12%|█▏        | 11619/100629 [09:14<1:06:14, 22.40it/s]

 12%|█▏        | 11622/100629 [09:14<1:10:48, 20.95it/s]

 12%|█▏        | 11625/100629 [09:14<1:11:14, 20.82it/s]

 12%|█▏        | 11628/100629 [09:14<1:05:18, 22.72it/s]

 12%|█▏        | 11631/100629 [09:14<1:06:49, 22.20it/s]

 12%|█▏        | 11635/100629 [09:14<1:00:59, 24.32it/s]

 12%|█▏        | 11638/100629 [09:15<1:03:10, 23.48it/s]

 12%|█▏        | 11641/100629 [09:15<1:10:41, 20.98it/s]

 12%|█▏        | 11644/100629 [09:15<1:13:30, 20.17it/s]

 12%|█▏        | 11647/100629 [09:15<1:17:48, 19.06it/s]

 12%|█▏        | 11650/100629 [09:15<1:24:31, 17.55it/s]

 12%|█▏        | 11652/100629 [09:15<1:22:33, 17.96it/s]

 12%|█▏        | 11654/100629 [09:16<1:21:20, 18.23it/s]

 12%|█▏        | 11656/100629 [09:16<1:54:36, 12.94it/s]

 12%|█▏        | 11658/100629 [09:16<1:48:28, 13.67it/s]

 12%|█▏        | 11660/100629 [09:16<1:43:53, 14.27it/s]

 12%|█▏        | 11663/100629 [09:16<1:26:26, 17.15it/s]

 12%|█▏        | 11666/100629 [09:16<1:17:44, 19.07it/s]

 12%|█▏        | 11669/100629 [09:16<1:11:38, 20.70it/s]

 12%|█▏        | 11672/100629 [09:17<1:19:34, 18.63it/s]

 12%|█▏        | 11676/100629 [09:17<1:06:30, 22.29it/s]

 12%|█▏        | 11679/100629 [09:17<1:07:36, 21.93it/s]

 12%|█▏        | 11682/100629 [09:17<1:08:42, 21.57it/s]

 12%|█▏        | 11685/100629 [09:17<1:17:02, 19.24it/s]

 12%|█▏        | 11688/100629 [09:17<1:22:27, 17.98it/s]

 12%|█▏        | 11693/100629 [09:18<1:07:43, 21.89it/s]

 12%|█▏        | 11696/100629 [09:18<1:03:56, 23.18it/s]

 12%|█▏        | 11699/100629 [09:18<1:05:58, 22.47it/s]

 12%|█▏        | 11702/100629 [09:18<1:12:56, 20.32it/s]

 12%|█▏        | 11705/100629 [09:18<1:10:35, 20.99it/s]

 12%|█▏        | 11708/100629 [09:18<1:05:08, 22.75it/s]

 12%|█▏        | 11711/100629 [09:18<1:02:57, 23.54it/s]

 12%|█▏        | 11715/100629 [09:18<57:46, 25.65it/s]

 12%|█▏        | 11718/100629 [09:19<1:04:58, 22.81it/s]

 12%|█▏        | 11721/100629 [09:19<1:02:42, 23.63it/s]

 12%|█▏        | 11725/100629 [09:19<1:05:23, 22.66it/s]

 12%|█▏        | 11729/100629 [09:19<57:03, 25.97it/s]

 12%|█▏        | 11732/100629 [09:19<1:01:43, 24.00it/s]

 12%|█▏        | 11735/100629 [09:19<1:03:40, 23.27it/s]

 12%|█▏        | 11738/100629 [09:19<59:57, 24.71it/s]

 12%|█▏        | 11741/100629 [09:20<1:00:16, 24.58it/s]

 12%|█▏        | 11744/100629 [09:20<1:08:51, 21.52it/s]

 12%|█▏        | 11747/100629 [09:20<1:24:45, 17.48it/s]

 12%|█▏        | 11749/100629 [09:20<1:26:54, 17.04it/s]

 12%|█▏        | 11752/100629 [09:20<1:20:30, 18.40it/s]

 12%|█▏        | 11756/100629 [09:20<1:16:32, 19.35it/s]

 12%|█▏        | 11758/100629 [09:21<1:17:44, 19.05it/s]

 12%|█▏        | 11760/100629 [09:21<1:24:24, 17.55it/s]

 12%|█▏        | 11763/100629 [09:21<1:27:20, 16.96it/s]

 12%|█▏        | 11766/100629 [09:21<1:19:39, 18.59it/s]

 12%|█▏        | 11768/100629 [09:21<1:22:51, 17.87it/s]

 12%|█▏        | 11773/100629 [09:21<1:01:25, 24.11it/s]

 12%|█▏        | 11776/100629 [09:21<1:04:13, 23.06it/s]

 12%|█▏        | 11779/100629 [09:22<1:11:03, 20.84it/s]

 12%|█▏        | 11782/100629 [09:22<1:13:03, 20.27it/s]

 12%|█▏        | 11785/100629 [09:22<1:11:44, 20.64it/s]

 12%|█▏        | 11788/100629 [09:22<1:06:39, 22.21it/s]

 12%|█▏        | 11791/100629 [09:22<1:16:55, 19.25it/s]

 12%|█▏        | 11794/100629 [09:22<1:28:38, 16.70it/s]

 12%|█▏        | 11796/100629 [09:23<1:29:41, 16.51it/s]

 12%|█▏        | 11799/100629 [09:23<1:24:56, 17.43it/s]

 12%|█▏        | 11802/100629 [09:23<1:15:14, 19.67it/s]

 12%|█▏        | 11805/100629 [09:23<1:21:19, 18.20it/s]

 12%|█▏        | 11807/100629 [09:23<1:26:02, 17.20it/s]

 12%|█▏        | 11810/100629 [09:23<1:18:50, 18.78it/s]

 12%|█▏        | 11813/100629 [09:23<1:11:00, 20.85it/s]

 12%|█▏        | 11816/100629 [09:24<1:07:38, 21.88it/s]

 12%|█▏        | 11819/100629 [09:24<1:11:47, 20.62it/s]

 12%|█▏        | 11822/100629 [09:24<1:06:26, 22.28it/s]

 12%|█▏        | 11825/100629 [09:24<1:06:39, 22.20it/s]

 12%|█▏        | 11829/100629 [09:24<1:06:18, 22.32it/s]

 12%|█▏        | 11832/100629 [09:24<1:13:14, 20.21it/s]

 12%|█▏        | 11836/100629 [09:24<1:04:07, 23.08it/s]

 12%|█▏        | 11839/100629 [09:25<1:05:08, 22.71it/s]

 12%|█▏        | 11843/100629 [09:25<59:50, 24.73it/s]

 12%|█▏        | 11846/100629 [09:25<1:15:29, 19.60it/s]

 12%|█▏        | 11849/100629 [09:25<1:13:00, 20.27it/s]

 12%|█▏        | 11854/100629 [09:25<57:06, 25.91it/s]

 12%|█▏        | 11858/100629 [09:25<53:43, 27.54it/s]

 12%|█▏        | 11861/100629 [09:25<57:43, 25.63it/s]

 12%|█▏        | 11864/100629 [09:26<56:24, 26.22it/s]

 12%|█▏        | 11867/100629 [09:26<1:01:57, 23.87it/s]

 12%|█▏        | 11870/100629 [09:26<1:09:43, 21.22it/s]

 12%|█▏        | 11873/100629 [09:26<1:28:54, 16.64it/s]

 12%|█▏        | 11875/100629 [09:26<1:31:21, 16.19it/s]

 12%|█▏        | 11878/100629 [09:26<1:19:31, 18.60it/s]

 12%|█▏        | 11881/100629 [09:27<1:25:48, 17.24it/s]

 12%|█▏        | 11883/100629 [09:27<1:29:20, 16.55it/s]

 12%|█▏        | 11885/100629 [09:27<1:38:59, 14.94it/s]

 12%|█▏        | 11888/100629 [09:27<1:29:50, 16.46it/s]

 12%|█▏        | 11890/100629 [09:27<1:40:13, 14.76it/s]

 12%|█▏        | 11893/100629 [09:27<1:26:14, 17.15it/s]

 12%|█▏        | 11895/100629 [09:28<1:27:12, 16.96it/s]

 12%|█▏        | 11897/100629 [09:28<1:36:29, 15.33it/s]

 12%|█▏        | 11900/100629 [09:28<1:24:36, 17.48it/s]

 12%|█▏        | 11903/100629 [09:28<1:28:04, 16.79it/s]

 12%|█▏        | 11906/100629 [09:28<1:25:05, 17.38it/s]

 12%|█▏        | 11908/100629 [09:28<1:32:01, 16.07it/s]

 12%|█▏        | 11910/100629 [09:28<1:30:24, 16.35it/s]

 12%|█▏        | 11913/100629 [09:29<1:23:09, 17.78it/s]

 12%|█▏        | 11915/100629 [09:29<1:40:50, 14.66it/s]

 12%|█▏        | 11918/100629 [09:29<1:25:42, 17.25it/s]

 12%|█▏        | 11921/100629 [09:29<1:16:38, 19.29it/s]

 12%|█▏        | 11924/100629 [09:29<1:16:03, 19.44it/s]

 12%|█▏        | 11927/100629 [09:29<1:24:06, 17.58it/s]

 12%|█▏        | 11930/100629 [09:30<1:29:07, 16.59it/s]

 12%|█▏        | 11934/100629 [09:30<1:29:19, 16.55it/s]

 12%|█▏        | 11937/100629 [09:30<1:28:39, 16.67it/s]

 12%|█▏        | 11939/100629 [09:30<1:29:51, 16.45it/s]

 12%|█▏        | 11944/100629 [09:30<1:05:33, 22.54it/s]

 12%|█▏        | 11947/100629 [09:30<1:03:21, 23.33it/s]

 12%|█▏        | 11950/100629 [09:31<1:12:00, 20.53it/s]

 12%|█▏        | 11953/100629 [09:31<1:05:51, 22.44it/s]

 12%|█▏        | 11956/100629 [09:31<1:07:46, 21.80it/s]

 12%|█▏        | 11959/100629 [09:31<1:08:36, 21.54it/s]

 12%|█▏        | 11962/100629 [09:31<1:06:47, 22.13it/s]

 12%|█▏        | 11965/100629 [09:31<1:11:16, 20.74it/s]

 12%|█▏        | 11968/100629 [09:31<1:06:45, 22.14it/s]

 12%|█▏        | 11973/100629 [09:31<56:14, 26.27it/s]

 12%|█▏        | 11977/100629 [09:32<53:25, 27.66it/s]

 12%|█▏        | 11980/100629 [09:32<58:14, 25.37it/s]

 12%|█▏        | 11983/100629 [09:32<1:02:19, 23.70it/s]

 12%|█▏        | 11986/100629 [09:32<1:08:31, 21.56it/s]

 12%|█▏        | 11989/100629 [09:32<1:10:26, 20.97it/s]

 12%|█▏        | 11992/100629 [09:32<1:25:07, 17.35it/s]

 12%|█▏        | 11994/100629 [09:33<1:28:29, 16.69it/s]

 12%|█▏        | 11996/100629 [09:33<1:27:50, 16.82it/s]

 12%|█▏        | 11998/100629 [09:33<1:47:33, 13.73it/s]

 12%|█▏        | 12000/100629 [09:33<2:00:40, 12.24it/s]

 12%|█▏        | 12002/100629 [09:33<1:51:27, 13.25it/s]

 12%|█▏        | 12005/100629 [09:33<1:36:36, 15.29it/s]

 12%|█▏        | 12008/100629 [09:34<1:24:55, 17.39it/s]

 12%|█▏        | 12010/100629 [09:34<1:29:31, 16.50it/s]

 12%|█▏        | 12012/100629 [09:34<1:32:12, 16.02it/s]

 12%|█▏        | 12015/100629 [09:34<1:21:55, 18.03it/s]

 12%|█▏        | 12018/100629 [09:34<1:18:03, 18.92it/s]

 12%|█▏        | 12023/100629 [09:34<1:01:00, 24.20it/s]

 12%|█▏        | 12027/100629 [09:34<56:53, 25.96it/s]

 12%|█▏        | 12030/100629 [09:35<1:08:42, 21.49it/s]

 12%|█▏        | 12033/100629 [09:35<1:03:51, 23.12it/s]

 12%|█▏        | 12036/100629 [09:35<1:11:46, 20.57it/s]

 12%|█▏        | 12041/100629 [09:35<59:54, 24.65it/s]

 12%|█▏        | 12044/100629 [09:35<1:01:24, 24.04it/s]

 12%|█▏        | 12048/100629 [09:35<55:52, 26.42it/s]

 12%|█▏        | 12051/100629 [09:35<1:00:46, 24.29it/s]

 12%|█▏        | 12054/100629 [09:36<1:00:26, 24.42it/s]

 12%|█▏        | 12057/100629 [09:36<1:12:06, 20.47it/s]

 12%|█▏        | 12060/100629 [09:36<1:16:05, 19.40it/s]

 12%|█▏        | 12063/100629 [09:36<1:20:50, 18.26it/s]

 12%|█▏        | 12065/100629 [09:36<1:21:32, 18.10it/s]

 12%|█▏        | 12068/100629 [09:36<1:15:33, 19.54it/s]

 12%|█▏        | 12072/100629 [09:36<1:08:08, 21.66it/s]

 12%|█▏        | 12075/100629 [09:37<1:05:33, 22.51it/s]

 12%|█▏        | 12078/100629 [09:37<1:01:28, 24.01it/s]

 12%|█▏        | 12081/100629 [09:37<58:56, 25.04it/s]

 12%|█▏        | 12085/100629 [09:37<58:13, 25.34it/s]

 12%|█▏        | 12088/100629 [09:37<56:17, 26.22it/s]

 12%|█▏        | 12092/100629 [09:37<52:14, 28.24it/s]

 12%|█▏        | 12096/100629 [09:37<49:32, 29.79it/s]

 12%|█▏        | 12100/100629 [09:38<1:03:18, 23.31it/s]

 12%|█▏        | 12103/100629 [09:38<1:03:58, 23.06it/s]

 12%|█▏        | 12108/100629 [09:38<53:15, 27.70it/s]

 12%|█▏        | 12111/100629 [09:38<52:53, 27.90it/s]

 12%|█▏        | 12114/100629 [09:38<58:45, 25.11it/s]

 12%|█▏        | 12117/100629 [09:38<1:00:36, 24.34it/s]

 12%|█▏        | 12120/100629 [09:38<1:01:11, 24.11it/s]

 12%|█▏        | 12123/100629 [09:39<1:05:02, 22.68it/s]

 12%|█▏        | 12128/100629 [09:39<51:02, 28.90it/s]

 12%|█▏        | 12132/100629 [09:39<1:00:31, 24.37it/s]

 12%|█▏        | 12135/100629 [09:39<1:04:48, 22.76it/s]

 12%|█▏        | 12138/100629 [09:39<1:06:52, 22.05it/s]

 12%|█▏        | 12141/100629 [09:39<1:24:38, 17.43it/s]

 12%|█▏        | 12144/100629 [09:40<1:19:36, 18.52it/s]

 12%|█▏        | 12147/100629 [09:40<1:28:16, 16.71it/s]

 12%|█▏        | 12149/100629 [09:40<1:42:13, 14.43it/s]

 12%|█▏        | 12152/100629 [09:40<1:26:38, 17.02it/s]

 12%|█▏        | 12155/100629 [09:40<1:17:24, 19.05it/s]

 12%|█▏        | 12158/100629 [09:40<1:14:22, 19.82it/s]

 12%|█▏        | 12161/100629 [09:40<1:08:58, 21.38it/s]

 12%|█▏        | 12164/100629 [09:41<1:05:05, 22.65it/s]

 12%|█▏        | 12167/100629 [09:41<1:02:06, 23.74it/s]

 12%|█▏        | 12170/100629 [09:41<1:19:35, 18.52it/s]

 12%|█▏        | 12173/100629 [09:41<1:16:28, 19.28it/s]

 12%|█▏        | 12176/100629 [09:41<1:23:00, 17.76it/s]

 12%|█▏        | 12180/100629 [09:41<1:13:16, 20.12it/s]

 12%|█▏        | 12183/100629 [09:42<1:09:59, 21.06it/s]

 12%|█▏        | 12186/100629 [09:42<1:11:55, 20.49it/s]

 12%|█▏        | 12190/100629 [09:42<1:31:24, 16.13it/s]

 12%|█▏        | 12193/100629 [09:42<1:20:49, 18.24it/s]

 12%|█▏        | 12196/100629 [09:42<1:20:21, 18.34it/s]

 12%|█▏        | 12199/100629 [09:42<1:13:17, 20.11it/s]

 12%|█▏        | 12203/100629 [09:43<1:10:35, 20.88it/s]

 12%|█▏        | 12207/100629 [09:43<1:01:53, 23.81it/s]

 12%|█▏        | 12210/100629 [09:43<1:05:31, 22.49it/s]

 12%|█▏        | 12213/100629 [09:43<1:30:18, 16.32it/s]

 12%|█▏        | 12216/100629 [09:43<1:28:49, 16.59it/s]

 12%|█▏        | 12218/100629 [09:43<1:29:16, 16.50it/s]

 12%|█▏        | 12222/100629 [09:44<1:11:16, 20.67it/s]

 12%|█▏        | 12226/100629 [09:44<1:03:35, 23.17it/s]

 12%|█▏        | 12229/100629 [09:44<1:11:16, 20.67it/s]

 12%|█▏        | 12235/100629 [09:44<53:41, 27.44it/s]

 12%|█▏        | 12238/100629 [09:44<1:09:37, 21.16it/s]

 12%|█▏        | 12243/100629 [09:44<59:19, 24.83it/s]

 12%|█▏        | 12246/100629 [09:45<59:56, 24.58it/s]

 12%|█▏        | 12249/100629 [09:45<1:05:07, 22.62it/s]

 12%|█▏        | 12252/100629 [09:45<1:07:48, 21.72it/s]

 12%|█▏        | 12255/100629 [09:45<1:13:25, 20.06it/s]

 12%|█▏        | 12258/100629 [09:45<1:07:17, 21.89it/s]

 12%|█▏        | 12261/100629 [09:45<1:12:39, 20.27it/s]

 12%|█▏        | 12265/100629 [09:45<1:03:34, 23.16it/s]

 12%|█▏        | 12268/100629 [09:46<1:15:33, 19.49it/s]

 12%|█▏        | 12271/100629 [09:46<1:10:45, 20.81it/s]

 12%|█▏        | 12274/100629 [09:46<1:06:12, 22.24it/s]

 12%|█▏        | 12278/100629 [09:46<58:30, 25.17it/s]

 12%|█▏        | 12281/100629 [09:46<1:01:35, 23.91it/s]

 12%|█▏        | 12285/100629 [09:46<57:53, 25.43it/s]

 12%|█▏        | 12288/100629 [09:46<1:04:21, 22.88it/s]

 12%|█▏        | 12291/100629 [09:47<1:02:10, 23.68it/s]

 12%|█▏        | 12295/100629 [09:47<1:01:28, 23.95it/s]

 12%|█▏        | 12298/100629 [09:47<1:01:24, 23.97it/s]

 12%|█▏        | 12301/100629 [09:47<1:00:14, 24.44it/s]

 12%|█▏        | 12304/100629 [09:47<1:03:11, 23.30it/s]

 12%|█▏        | 12307/100629 [09:47<1:01:59, 23.75it/s]

 12%|█▏        | 12310/100629 [09:48<1:18:17, 18.80it/s]

 12%|█▏        | 12313/100629 [09:48<1:10:11, 20.97it/s]

 12%|█▏        | 12316/100629 [09:48<1:22:07, 17.92it/s]

 12%|█▏        | 12319/100629 [09:48<1:21:16, 18.11it/s]

 12%|█▏        | 12321/100629 [09:48<1:21:17, 18.11it/s]

 12%|█▏        | 12323/100629 [09:48<1:24:28, 17.42it/s]

 12%|█▏        | 12325/100629 [09:48<1:32:07, 15.97it/s]

 12%|█▏        | 12328/100629 [09:49<1:24:45, 17.36it/s]

 12%|█▏        | 12330/100629 [09:49<1:25:45, 17.16it/s]

 12%|█▏        | 12333/100629 [09:49<1:20:21, 18.31it/s]

 12%|█▏        | 12335/100629 [09:49<1:18:43, 18.69it/s]

 12%|█▏        | 12337/100629 [09:49<1:22:32, 17.83it/s]

 12%|█▏        | 12339/100629 [09:49<1:21:49, 17.98it/s]

 12%|█▏        | 12343/100629 [09:49<1:10:59, 20.73it/s]

 12%|█▏        | 12346/100629 [09:49<1:05:16, 22.54it/s]

 12%|█▏        | 12349/100629 [09:50<1:15:36, 19.46it/s]

 12%|█▏        | 12353/100629 [09:50<1:05:05, 22.60it/s]

 12%|█▏        | 12357/100629 [09:50<1:03:10, 23.29it/s]

 12%|█▏        | 12360/100629 [09:50<1:06:45, 22.04it/s]

 12%|█▏        | 12364/100629 [09:50<1:06:13, 22.22it/s]

 12%|█▏        | 12367/100629 [09:50<1:03:01, 23.34it/s]

 12%|█▏        | 12370/100629 [09:50<1:07:50, 21.68it/s]

 12%|█▏        | 12373/100629 [09:51<1:05:12, 22.56it/s]

 12%|█▏        | 12376/100629 [09:51<1:12:28, 20.29it/s]

 12%|█▏        | 12379/100629 [09:51<1:08:17, 21.54it/s]

 12%|█▏        | 12383/100629 [09:51<1:00:43, 24.22it/s]

 12%|█▏        | 12387/100629 [09:51<59:11, 24.84it/s]

 12%|█▏        | 12390/100629 [09:51<1:00:50, 24.17it/s]

 12%|█▏        | 12393/100629 [09:52<1:07:28, 21.79it/s]

 12%|█▏        | 12397/100629 [09:52<57:35, 25.54it/s]

 12%|█▏        | 12400/100629 [09:52<58:25, 25.17it/s]

 12%|█▏        | 12406/100629 [09:52<54:02, 27.20it/s]

 12%|█▏        | 12409/100629 [09:52<1:02:26, 23.55it/s]

 12%|█▏        | 12412/100629 [09:52<1:05:57, 22.29it/s]

 12%|█▏        | 12416/100629 [09:52<57:17, 25.66it/s]

 12%|█▏        | 12419/100629 [09:53<58:48, 25.00it/s]

 12%|█▏        | 12422/100629 [09:53<1:00:58, 24.11it/s]

 12%|█▏        | 12425/100629 [09:53<58:32, 25.11it/s]

 12%|█▏        | 12428/100629 [09:53<1:01:32, 23.88it/s]

 12%|█▏        | 12431/100629 [09:53<1:09:39, 21.10it/s]

 12%|█▏        | 12434/100629 [09:53<1:16:44, 19.16it/s]

 12%|█▏        | 12437/100629 [09:53<1:14:59, 19.60it/s]

 12%|█▏        | 12440/100629 [09:54<1:12:03, 20.40it/s]

 12%|█▏        | 12443/100629 [09:54<1:08:14, 21.54it/s]

 12%|█▏        | 12446/100629 [09:54<1:22:07, 17.90it/s]

 12%|█▏        | 12450/100629 [09:54<1:28:51, 16.54it/s]

 12%|█▏        | 12454/100629 [09:54<1:11:46, 20.48it/s]

 12%|█▏        | 12457/100629 [09:54<1:13:46, 19.92it/s]

 12%|█▏        | 12460/100629 [09:55<1:14:20, 19.77it/s]

 12%|█▏        | 12463/100629 [09:55<1:08:04, 21.58it/s]

 12%|█▏        | 12466/100629 [09:55<1:08:50, 21.35it/s]

 12%|█▏        | 12469/100629 [09:55<1:13:13, 20.07it/s]

 12%|█▏        | 12472/100629 [09:55<1:07:53, 21.64it/s]

 12%|█▏        | 12475/100629 [09:55<1:18:29, 18.72it/s]

 12%|█▏        | 12478/100629 [09:55<1:14:44, 19.66it/s]

 12%|█▏        | 12481/100629 [09:56<1:23:47, 17.53it/s]

 12%|█▏        | 12484/100629 [09:56<1:27:13, 16.84it/s]

 12%|█▏        | 12487/100629 [09:56<1:25:27, 17.19it/s]

 12%|█▏        | 12490/100629 [09:56<1:14:33, 19.70it/s]

 12%|█▏        | 12495/100629 [09:56<1:02:10, 23.62it/s]

 12%|█▏        | 12498/100629 [09:56<1:05:06, 22.56it/s]

 12%|█▏        | 12501/100629 [09:57<1:04:10, 22.89it/s]

 12%|█▏        | 12504/100629 [09:57<1:05:09, 22.54it/s]

 12%|█▏        | 12507/100629 [09:57<1:09:39, 21.09it/s]

 12%|█▏        | 12510/100629 [09:57<1:10:34, 20.81it/s]

 12%|█▏        | 12513/100629 [09:57<1:10:37, 20.80it/s]

 12%|█▏        | 12516/100629 [09:57<1:08:28, 21.45it/s]

 12%|█▏        | 12519/100629 [09:57<1:16:22, 19.23it/s]

 12%|█▏        | 12521/100629 [09:58<1:16:46, 19.13it/s]

 12%|█▏        | 12525/100629 [09:58<1:04:11, 22.87it/s]

 12%|█▏        | 12529/100629 [09:58<57:28, 25.55it/s]

 12%|█▏        | 12532/100629 [09:58<1:13:55, 19.86it/s]

 12%|█▏        | 12536/100629 [09:58<1:02:09, 23.62it/s]

 12%|█▏        | 12539/100629 [09:58<59:38, 24.62it/s]

 12%|█▏        | 12542/100629 [09:58<58:58, 24.89it/s]

 12%|█▏        | 12546/100629 [09:59<56:50, 25.82it/s]

 12%|█▏        | 12549/100629 [09:59<1:13:29, 19.98it/s]

 12%|█▏        | 12552/100629 [09:59<1:17:29, 18.94it/s]

 12%|█▏        | 12555/100629 [09:59<1:20:20, 18.27it/s]

 12%|█▏        | 12557/100629 [09:59<1:21:31, 18.00it/s]

 12%|█▏        | 12560/100629 [09:59<1:21:11, 18.08it/s]

 12%|█▏        | 12562/100629 [10:00<1:23:15, 17.63it/s]

 12%|█▏        | 12564/100629 [10:00<1:22:10, 17.86it/s]

 12%|█▏        | 12567/100629 [10:00<1:12:42, 20.19it/s]

 12%|█▏        | 12570/100629 [10:00<1:20:21, 18.26it/s]

 12%|█▏        | 12573/100629 [10:00<1:18:28, 18.70it/s]

 12%|█▏        | 12575/100629 [10:00<1:25:28, 17.17it/s]

 12%|█▏        | 12577/100629 [10:00<1:23:27, 17.58it/s]

 13%|█▎        | 12581/100629 [10:01<1:11:55, 20.40it/s]

 13%|█▎        | 12584/100629 [10:01<1:09:16, 21.18it/s]

 13%|█▎        | 12587/100629 [10:01<1:12:27, 20.25it/s]

 13%|█▎        | 12590/100629 [10:01<1:14:03, 19.81it/s]

 13%|█▎        | 12592/100629 [10:01<1:22:53, 17.70it/s]

 13%|█▎        | 12594/100629 [10:01<1:25:20, 17.19it/s]

 13%|█▎        | 12597/100629 [10:01<1:18:17, 18.74it/s]

 13%|█▎        | 12599/100629 [10:02<1:19:01, 18.57it/s]

 13%|█▎        | 12601/100629 [10:02<1:35:33, 15.35it/s]

 13%|█▎        | 12603/100629 [10:02<1:29:46, 16.34it/s]

 13%|█▎        | 12607/100629 [10:02<1:11:21, 20.56it/s]

 13%|█▎        | 12610/100629 [10:02<1:10:15, 20.88it/s]

 13%|█▎        | 12613/100629 [10:02<1:11:34, 20.49it/s]

 13%|█▎        | 12616/100629 [10:02<1:27:54, 16.69it/s]

 13%|█▎        | 12618/100629 [10:03<1:27:07, 16.84it/s]

 13%|█▎        | 12621/100629 [10:03<1:19:42, 18.40it/s]

 13%|█▎        | 12623/100629 [10:03<1:18:32, 18.67it/s]

 13%|█▎        | 12625/100629 [10:03<1:22:47, 17.72it/s]

 13%|█▎        | 12628/100629 [10:03<1:11:01, 20.65it/s]

 13%|█▎        | 12631/100629 [10:03<1:13:33, 19.94it/s]

 13%|█▎        | 12635/100629 [10:03<1:07:11, 21.83it/s]

 13%|█▎        | 12638/100629 [10:03<1:03:09, 23.22it/s]

 13%|█▎        | 12642/100629 [10:04<57:22, 25.56it/s]

 13%|█▎        | 12646/100629 [10:04<57:59, 25.29it/s]

 13%|█▎        | 12649/100629 [10:04<1:02:37, 23.41it/s]

 13%|█▎        | 12652/100629 [10:04<59:34, 24.61it/s]

 13%|█▎        | 12655/100629 [10:04<1:02:22, 23.51it/s]

 13%|█▎        | 12658/100629 [10:04<1:04:43, 22.65it/s]

 13%|█▎        | 12661/100629 [10:05<1:10:16, 20.86it/s]

 13%|█▎        | 12666/100629 [10:05<58:00, 25.28it/s]

 13%|█▎        | 12669/100629 [10:05<57:59, 25.28it/s]

 13%|█▎        | 12672/100629 [10:05<1:00:44, 24.13it/s]

 13%|█▎        | 12675/100629 [10:05<1:02:35, 23.42it/s]

 13%|█▎        | 12678/100629 [10:05<1:08:22, 21.44it/s]

 13%|█▎        | 12681/100629 [10:05<1:19:52, 18.35it/s]

 13%|█▎        | 12684/100629 [10:06<1:14:24, 19.70it/s]

 13%|█▎        | 12687/100629 [10:06<1:15:07, 19.51it/s]

 13%|█▎        | 12692/100629 [10:06<56:23, 25.99it/s]

 13%|█▎        | 12696/100629 [10:06<56:52, 25.77it/s]

 13%|█▎        | 12699/100629 [10:06<1:08:29, 21.40it/s]

 13%|█▎        | 12703/100629 [10:06<59:41, 24.55it/s]

 13%|█▎        | 12708/100629 [10:06<54:41, 26.79it/s]

 13%|█▎        | 12711/100629 [10:07<55:11, 26.55it/s]

 13%|█▎        | 12714/100629 [10:07<59:20, 24.69it/s]

 13%|█▎        | 12717/100629 [10:07<58:59, 24.84it/s]

 13%|█▎        | 12720/100629 [10:07<1:02:00, 23.63it/s]

 13%|█▎        | 12723/100629 [10:07<59:39, 24.56it/s]

 13%|█▎        | 12726/100629 [10:07<58:41, 24.96it/s]

 13%|█▎        | 12729/100629 [10:07<59:20, 24.69it/s]

 13%|█▎        | 12733/100629 [10:07<58:05, 25.22it/s]

 13%|█▎        | 12736/100629 [10:08<1:03:20, 23.13it/s]

 13%|█▎        | 12739/100629 [10:08<1:16:53, 19.05it/s]

 13%|█▎        | 12742/100629 [10:08<1:09:27, 21.09it/s]

 13%|█▎        | 12745/100629 [10:08<1:13:53, 19.82it/s]

 13%|█▎        | 12748/100629 [10:08<1:10:18, 20.83it/s]

 13%|█▎        | 12752/100629 [10:08<1:00:57, 24.03it/s]

 13%|█▎        | 12755/100629 [10:09<1:00:55, 24.04it/s]

 13%|█▎        | 12758/100629 [10:09<59:32, 24.59it/s]

 13%|█▎        | 12761/100629 [10:09<1:00:02, 24.39it/s]

 13%|█▎        | 12764/100629 [10:09<1:10:06, 20.89it/s]

 13%|█▎        | 12767/100629 [10:09<1:07:32, 21.68it/s]

 13%|█▎        | 12770/100629 [10:09<1:05:33, 22.33it/s]

 13%|█▎        | 12773/100629 [10:09<1:13:44, 19.86it/s]

 13%|█▎        | 12776/100629 [10:10<1:19:10, 18.49it/s]

 13%|█▎        | 12780/100629 [10:10<1:10:54, 20.65it/s]

 13%|█▎        | 12783/100629 [10:10<1:15:32, 19.38it/s]

 13%|█▎        | 12786/100629 [10:10<1:14:12, 19.73it/s]

 13%|█▎        | 12790/100629 [10:10<1:02:22, 23.47it/s]

 13%|█▎        | 12793/100629 [10:10<1:06:52, 21.89it/s]

 13%|█▎        | 12797/100629 [10:11<1:10:07, 20.87it/s]

 13%|█▎        | 12801/100629 [10:11<1:03:03, 23.21it/s]

 13%|█▎        | 12805/100629 [10:11<58:43, 24.93it/s]

 13%|█▎        | 12808/100629 [10:11<1:19:02, 18.52it/s]

 13%|█▎        | 12811/100629 [10:11<1:16:07, 19.23it/s]

 13%|█▎        | 12814/100629 [10:11<1:19:13, 18.47it/s]

 13%|█▎        | 12817/100629 [10:12<1:11:34, 20.45it/s]

 13%|█▎        | 12820/100629 [10:12<1:10:37, 20.72it/s]

 13%|█▎        | 12823/100629 [10:12<1:21:12, 18.02it/s]

 13%|█▎        | 12827/100629 [10:12<1:05:46, 22.25it/s]

 13%|█▎        | 12831/100629 [10:12<58:07, 25.18it/s]

 13%|█▎        | 12834/100629 [10:12<1:12:46, 20.11it/s]

 13%|█▎        | 12837/100629 [10:12<1:10:08, 20.86it/s]

 13%|█▎        | 12840/100629 [10:13<1:06:54, 21.87it/s]

 13%|█▎        | 12843/100629 [10:13<1:05:34, 22.31it/s]

 13%|█▎        | 12848/100629 [10:13<57:26, 25.47it/s]

 13%|█▎        | 12852/100629 [10:13<59:09, 24.73it/s]

 13%|█▎        | 12855/100629 [10:13<1:07:14, 21.76it/s]

 13%|█▎        | 12858/100629 [10:13<1:08:26, 21.38it/s]

 13%|█▎        | 12861/100629 [10:13<1:05:01, 22.50it/s]

 13%|█▎        | 12864/100629 [10:14<1:02:15, 23.50it/s]

 13%|█▎        | 12867/100629 [10:14<59:25, 24.62it/s]

 13%|█▎        | 12870/100629 [10:14<57:14, 25.55it/s]

 13%|█▎        | 12873/100629 [10:14<1:18:59, 18.52it/s]

 13%|█▎        | 12876/100629 [10:14<1:18:18, 18.68it/s]

 13%|█▎        | 12879/100629 [10:14<1:13:10, 19.99it/s]

 13%|█▎        | 12882/100629 [10:14<1:11:28, 20.46it/s]

 13%|█▎        | 12885/100629 [10:15<1:08:25, 21.37it/s]

 13%|█▎        | 12888/100629 [10:15<1:10:27, 20.75it/s]

 13%|█▎        | 12891/100629 [10:15<1:05:58, 22.16it/s]

 13%|█▎        | 12894/100629 [10:15<1:18:09, 18.71it/s]

 13%|█▎        | 12898/100629 [10:15<1:06:02, 22.14it/s]

 13%|█▎        | 12901/100629 [10:15<1:11:07, 20.56it/s]

 13%|█▎        | 12904/100629 [10:16<1:04:51, 22.54it/s]

 13%|█▎        | 12907/100629 [10:16<1:02:47, 23.28it/s]

 13%|█▎        | 12911/100629 [10:16<56:47, 25.74it/s]

 13%|█▎        | 12914/100629 [10:16<59:15, 24.67it/s]

 13%|█▎        | 12917/100629 [10:16<1:22:05, 17.81it/s]

 13%|█▎        | 12921/100629 [10:16<1:13:44, 19.82it/s]

 13%|█▎        | 12924/100629 [10:17<1:20:22, 18.19it/s]

 13%|█▎        | 12927/100629 [10:17<1:17:00, 18.98it/s]

 13%|█▎        | 12930/100629 [10:17<1:09:22, 21.07it/s]

 13%|█▎        | 12933/100629 [10:17<1:19:35, 18.36it/s]

 13%|█▎        | 12936/100629 [10:17<1:11:25, 20.46it/s]

 13%|█▎        | 12939/100629 [10:17<1:05:17, 22.38it/s]

 13%|█▎        | 12942/100629 [10:17<1:03:45, 22.92it/s]

 13%|█▎        | 12945/100629 [10:18<1:14:06, 19.72it/s]

 13%|█▎        | 12948/100629 [10:18<1:25:09, 17.16it/s]

 13%|█▎        | 12950/100629 [10:18<1:31:10, 16.03it/s]

 13%|█▎        | 12952/100629 [10:18<1:35:23, 15.32it/s]

 13%|█▎        | 12956/100629 [10:18<1:14:20, 19.66it/s]

 13%|█▎        | 12959/100629 [10:18<1:13:11, 19.96it/s]

 13%|█▎        | 12963/100629 [10:19<1:11:25, 20.46it/s]

 13%|█▎        | 12966/100629 [10:19<1:12:40, 20.10it/s]

 13%|█▎        | 12969/100629 [10:19<1:06:39, 21.92it/s]

 13%|█▎        | 12972/100629 [10:19<1:08:29, 21.33it/s]

 13%|█▎        | 12975/100629 [10:19<1:08:15, 21.40it/s]

 13%|█▎        | 12979/100629 [10:19<59:44, 24.45it/s]

 13%|█▎        | 12982/100629 [10:19<1:07:44, 21.56it/s]

 13%|█▎        | 12985/100629 [10:20<1:22:29, 17.71it/s]

 13%|█▎        | 12987/100629 [10:20<1:28:29, 16.51it/s]

 13%|█▎        | 12989/100629 [10:20<1:29:27, 16.33it/s]

 13%|█▎        | 12992/100629 [10:20<1:21:12, 17.99it/s]

 13%|█▎        | 12995/100629 [10:20<1:22:17, 17.75it/s]

 13%|█▎        | 12998/100629 [10:20<1:24:58, 17.19it/s]

 13%|█▎        | 13000/100629 [10:21<1:28:09, 16.57it/s]

 13%|█▎        | 13002/100629 [10:21<1:33:00, 15.70it/s]

 13%|█▎        | 13008/100629 [10:21<1:03:01, 23.17it/s]

 13%|█▎        | 13011/100629 [10:21<1:15:38, 19.31it/s]

 13%|█▎        | 13014/100629 [10:21<1:16:21, 19.12it/s]

 13%|█▎        | 13018/100629 [10:21<1:05:39, 22.24it/s]

 13%|█▎        | 13024/100629 [10:21<48:40, 30.00it/s]

 13%|█▎        | 13028/100629 [10:22<48:57, 29.82it/s]

 13%|█▎        | 13032/100629 [10:22<50:30, 28.91it/s]

 13%|█▎        | 13036/100629 [10:22<56:43, 25.74it/s]

 13%|█▎        | 13039/100629 [10:22<1:02:07, 23.50it/s]

 13%|█▎        | 13042/100629 [10:22<1:04:28, 22.64it/s]

 13%|█▎        | 13046/100629 [10:22<55:34, 26.26it/s]

 13%|█▎        | 13049/100629 [10:22<58:52, 24.79it/s]

 13%|█▎        | 13052/100629 [10:23<1:06:15, 22.03it/s]

 13%|█▎        | 13055/100629 [10:23<1:03:55, 22.83it/s]

 13%|█▎        | 13059/100629 [10:23<56:49, 25.69it/s]

 13%|█▎        | 13062/100629 [10:23<55:41, 26.20it/s]

 13%|█▎        | 13065/100629 [10:23<1:03:39, 22.92it/s]

 13%|█▎        | 13068/100629 [10:23<1:15:08, 19.42it/s]

 13%|█▎        | 13071/100629 [10:24<1:20:54, 18.04it/s]

 13%|█▎        | 13074/100629 [10:24<1:12:23, 20.16it/s]

 13%|█▎        | 13077/100629 [10:24<1:38:54, 14.75it/s]

 13%|█▎        | 13080/100629 [10:24<1:26:50, 16.80it/s]

 13%|█▎        | 13083/100629 [10:24<1:21:43, 17.85it/s]

 13%|█▎        | 13087/100629 [10:24<1:07:01, 21.77it/s]

 13%|█▎        | 13090/100629 [10:25<1:13:10, 19.94it/s]

 13%|█▎        | 13093/100629 [10:25<1:09:33, 20.98it/s]

 13%|█▎        | 13096/100629 [10:25<1:04:02, 22.78it/s]

 13%|█▎        | 13099/100629 [10:25<1:07:39, 21.56it/s]

 13%|█▎        | 13103/100629 [10:25<1:00:55, 23.94it/s]

 13%|█▎        | 13106/100629 [10:25<1:05:31, 22.26it/s]

 13%|█▎        | 13110/100629 [10:25<55:54, 26.09it/s]

 13%|█▎        | 13115/100629 [10:26<52:42, 27.67it/s]

 13%|█▎        | 13118/100629 [10:26<1:09:25, 21.01it/s]

 13%|█▎        | 13121/100629 [10:26<1:09:39, 20.94it/s]

 13%|█▎        | 13124/100629 [10:26<1:07:44, 21.53it/s]

 13%|█▎        | 13127/100629 [10:26<1:11:08, 20.50it/s]

 13%|█▎        | 13130/100629 [10:26<1:13:17, 19.90it/s]

 13%|█▎        | 13133/100629 [10:27<1:13:33, 19.82it/s]

 13%|█▎        | 13137/100629 [10:27<1:04:10, 22.72it/s]

 13%|█▎        | 13140/100629 [10:27<1:12:45, 20.04it/s]

 13%|█▎        | 13143/100629 [10:27<1:18:22, 18.60it/s]

 13%|█▎        | 13146/100629 [10:27<1:09:53, 20.86it/s]

 13%|█▎        | 13149/100629 [10:27<1:16:39, 19.02it/s]

 13%|█▎        | 13152/100629 [10:27<1:17:01, 18.93it/s]

 13%|█▎        | 13155/100629 [10:28<1:13:56, 19.72it/s]

 13%|█▎        | 13158/100629 [10:28<1:12:43, 20.05it/s]

 13%|█▎        | 13161/100629 [10:28<1:10:54, 20.56it/s]

 13%|█▎        | 13165/100629 [10:28<1:05:08, 22.38it/s]

 13%|█▎        | 13168/100629 [10:28<1:00:47, 23.98it/s]

 13%|█▎        | 13171/100629 [10:28<1:09:42, 20.91it/s]

 13%|█▎        | 13174/100629 [10:28<1:08:58, 21.13it/s]

 13%|█▎        | 13177/100629 [10:29<1:22:32, 17.66it/s]

 13%|█▎        | 13180/100629 [10:29<1:13:08, 19.93it/s]

 13%|█▎        | 13183/100629 [10:29<1:21:26, 17.90it/s]

 13%|█▎        | 13185/100629 [10:29<1:27:29, 16.66it/s]

 13%|█▎        | 13187/100629 [10:29<1:34:08, 15.48it/s]

 13%|█▎        | 13190/100629 [10:29<1:25:54, 16.96it/s]

 13%|█▎        | 13193/100629 [10:30<1:16:06, 19.15it/s]

 13%|█▎        | 13196/100629 [10:30<1:17:52, 18.71it/s]

 13%|█▎        | 13198/100629 [10:30<1:25:54, 16.96it/s]

 13%|█▎        | 13201/100629 [10:30<1:18:36, 18.54it/s]

 13%|█▎        | 13204/100629 [10:30<1:16:09, 19.13it/s]

 13%|█▎        | 13206/100629 [10:30<1:23:02, 17.55it/s]

 13%|█▎        | 13209/100629 [10:30<1:16:04, 19.15it/s]

 13%|█▎        | 13213/100629 [10:31<1:10:06, 20.78it/s]

 13%|█▎        | 13216/100629 [10:31<1:07:05, 21.72it/s]

 13%|█▎        | 13219/100629 [10:31<1:01:55, 23.52it/s]

 13%|█▎        | 13222/100629 [10:31<1:04:26, 22.61it/s]

 13%|█▎        | 13225/100629 [10:31<1:21:01, 17.98it/s]

 13%|█▎        | 13228/100629 [10:31<1:14:11, 19.63it/s]

 13%|█▎        | 13233/100629 [10:31<56:00, 26.00it/s]

 13%|█▎        | 13236/100629 [10:32<57:09, 25.48it/s]

 13%|█▎        | 13239/100629 [10:32<1:00:54, 23.91it/s]

 13%|█▎        | 13242/100629 [10:32<1:09:41, 20.90it/s]

 13%|█▎        | 13245/100629 [10:32<1:07:34, 21.55it/s]

 13%|█▎        | 13248/100629 [10:32<1:05:06, 22.37it/s]

 13%|█▎        | 13252/100629 [10:32<58:21, 24.96it/s]

 13%|█▎        | 13255/100629 [10:32<59:09, 24.62it/s]

 13%|█▎        | 13258/100629 [10:33<1:02:29, 23.30it/s]

 13%|█▎        | 13261/100629 [10:33<1:04:55, 22.43it/s]

 13%|█▎        | 13264/100629 [10:33<1:11:53, 20.26it/s]

 13%|█▎        | 13267/100629 [10:33<1:26:37, 16.81it/s]

 13%|█▎        | 13269/100629 [10:33<1:24:39, 17.20it/s]

 13%|█▎        | 13271/100629 [10:33<1:31:05, 15.98it/s]

 13%|█▎        | 13274/100629 [10:34<1:26:47, 16.77it/s]

 13%|█▎        | 13278/100629 [10:34<1:12:43, 20.02it/s]

 13%|█▎        | 13281/100629 [10:34<1:18:06, 18.64it/s]

 13%|█▎        | 13284/100629 [10:34<1:12:04, 20.20it/s]

 13%|█▎        | 13287/100629 [10:34<1:18:24, 18.57it/s]

 13%|█▎        | 13289/100629 [10:34<1:18:21, 18.58it/s]

 13%|█▎        | 13291/100629 [10:34<1:22:15, 17.70it/s]

 13%|█▎        | 13293/100629 [10:35<1:23:29, 17.44it/s]

 13%|█▎        | 13296/100629 [10:35<1:12:21, 20.12it/s]

 13%|█▎        | 13299/100629 [10:35<1:13:08, 19.90it/s]

 13%|█▎        | 13302/100629 [10:35<1:10:32, 20.63it/s]

 13%|█▎        | 13307/100629 [10:35<53:53, 27.00it/s]

 13%|█▎        | 13310/100629 [10:35<55:54, 26.03it/s]

 13%|█▎        | 13313/100629 [10:35<1:03:45, 22.82it/s]

 13%|█▎        | 13317/100629 [10:36<1:05:02, 22.37it/s]

 13%|█▎        | 13320/100629 [10:36<1:14:47, 19.46it/s]

 13%|█▎        | 13323/100629 [10:36<1:13:41, 19.75it/s]

 13%|█▎        | 13326/100629 [10:36<1:15:15, 19.33it/s]

 13%|█▎        | 13329/100629 [10:36<1:16:12, 19.09it/s]

 13%|█▎        | 13333/100629 [10:36<1:07:46, 21.47it/s]

 13%|█▎        | 13336/100629 [10:36<1:02:49, 23.16it/s]

 13%|█▎        | 13339/100629 [10:37<1:12:05, 20.18it/s]

 13%|█▎        | 13344/100629 [10:37<56:25, 25.78it/s]

 13%|█▎        | 13349/100629 [10:37<50:17, 28.93it/s]

 13%|█▎        | 13353/100629 [10:37<1:05:41, 22.14it/s]

 13%|█▎        | 13356/100629 [10:37<1:08:50, 21.13it/s]

 13%|█▎        | 13359/100629 [10:38<1:14:18, 19.57it/s]

 13%|█▎        | 13362/100629 [10:38<1:07:37, 21.51it/s]

 13%|█▎        | 13365/100629 [10:38<1:14:28, 19.53it/s]

 13%|█▎        | 13368/100629 [10:38<1:18:54, 18.43it/s]

 13%|█▎        | 13370/100629 [10:38<1:37:34, 14.91it/s]

 13%|█▎        | 13372/100629 [10:38<1:32:39, 15.70it/s]

 13%|█▎        | 13374/100629 [10:39<1:46:22, 13.67it/s]

 13%|█▎        | 13376/100629 [10:39<1:45:59, 13.72it/s]

 13%|█▎        | 13379/100629 [10:39<1:29:17, 16.29it/s]

 13%|█▎        | 13382/100629 [10:39<1:19:40, 18.25it/s]

 13%|█▎        | 13384/100629 [10:39<1:26:25, 16.83it/s]

 13%|█▎        | 13386/100629 [10:39<1:28:25, 16.45it/s]

 13%|█▎        | 13388/100629 [10:39<1:27:32, 16.61it/s]

 13%|█▎        | 13390/100629 [10:40<1:28:46, 16.38it/s]

 13%|█▎        | 13392/100629 [10:40<1:25:56, 16.92it/s]

 13%|█▎        | 13395/100629 [10:40<1:12:17, 20.11it/s]

 13%|█▎        | 13398/100629 [10:40<1:16:17, 19.05it/s]

 13%|█▎        | 13400/100629 [10:40<1:17:59, 18.64it/s]

 13%|█▎        | 13402/100629 [10:40<1:17:34, 18.74it/s]

 13%|█▎        | 13406/100629 [10:40<1:06:47, 21.77it/s]

 13%|█▎        | 13409/100629 [10:40<1:10:30, 20.62it/s]

 13%|█▎        | 13412/100629 [10:41<1:18:22, 18.55it/s]

 13%|█▎        | 13415/100629 [10:41<1:16:23, 19.03it/s]

 13%|█▎        | 13417/100629 [10:41<1:15:59, 19.13it/s]

 13%|█▎        | 13420/100629 [10:41<1:14:46, 19.44it/s]

 13%|█▎        | 13423/100629 [10:41<1:06:36, 21.82it/s]

 13%|█▎        | 13426/100629 [10:41<1:13:11, 19.86it/s]

 13%|█▎        | 13429/100629 [10:41<1:11:39, 20.28it/s]

 13%|█▎        | 13432/100629 [10:42<1:10:30, 20.61it/s]

 13%|█▎        | 13435/100629 [10:42<1:14:23, 19.54it/s]

 13%|█▎        | 13438/100629 [10:42<1:09:20, 20.96it/s]

 13%|█▎        | 13441/100629 [10:42<1:11:57, 20.20it/s]

 13%|█▎        | 13444/100629 [10:42<1:11:27, 20.34it/s]

 13%|█▎        | 13447/100629 [10:42<1:06:00, 22.01it/s]

 13%|█▎        | 13450/100629 [10:42<1:03:36, 22.85it/s]

 13%|█▎        | 13453/100629 [10:43<1:05:19, 22.24it/s]

 13%|█▎        | 13456/100629 [10:43<1:16:25, 19.01it/s]

 13%|█▎        | 13460/100629 [10:43<1:03:21, 22.93it/s]

 13%|█▎        | 13463/100629 [10:43<1:32:37, 15.68it/s]

 13%|█▎        | 13465/100629 [10:43<1:29:57, 16.15it/s]

 13%|█▎        | 13467/100629 [10:43<1:27:43, 16.56it/s]

 13%|█▎        | 13470/100629 [10:44<1:25:30, 16.99it/s]

 13%|█▎        | 13472/100629 [10:44<1:35:39, 15.18it/s]

 13%|█▎        | 13477/100629 [10:44<1:09:25, 20.92it/s]

 13%|█▎        | 13480/100629 [10:44<1:05:29, 22.18it/s]

 13%|█▎        | 13483/100629 [10:44<1:05:00, 22.34it/s]

 13%|█▎        | 13486/100629 [10:44<1:05:04, 22.32it/s]

 13%|█▎        | 13489/100629 [10:44<1:00:29, 24.01it/s]

 13%|█▎        | 13493/100629 [10:45<54:42, 26.55it/s]

 13%|█▎        | 13496/100629 [10:45<1:02:02, 23.41it/s]

 13%|█▎        | 13499/100629 [10:45<1:14:03, 19.61it/s]

 13%|█▎        | 13502/100629 [10:45<1:29:59, 16.14it/s]

 13%|█▎        | 13504/100629 [10:45<1:33:05, 15.60it/s]

 13%|█▎        | 13507/100629 [10:45<1:20:31, 18.03it/s]

 13%|█▎        | 13512/100629 [10:46<59:29, 24.41it/s]

 13%|█▎        | 13515/100629 [10:46<1:11:52, 20.20it/s]

 13%|█▎        | 13518/100629 [10:46<1:12:07, 20.13it/s]

 13%|█▎        | 13521/100629 [10:46<1:25:16, 17.03it/s]

 13%|█▎        | 13523/100629 [10:46<1:29:06, 16.29it/s]

 13%|█▎        | 13525/100629 [10:46<1:36:28, 15.05it/s]

 13%|█▎        | 13528/100629 [10:47<1:30:48, 15.99it/s]

 13%|█▎        | 13531/100629 [10:47<1:17:32, 18.72it/s]

 13%|█▎        | 13534/100629 [10:47<1:23:39, 17.35it/s]

 13%|█▎        | 13536/100629 [10:47<1:24:44, 17.13it/s]

 13%|█▎        | 13538/100629 [10:47<1:38:26, 14.74it/s]

 13%|█▎        | 13541/100629 [10:47<1:29:48, 16.16it/s]

 13%|█▎        | 13543/100629 [10:48<1:35:50, 15.14it/s]

 13%|█▎        | 13546/100629 [10:48<1:20:57, 17.93it/s]

 13%|█▎        | 13548/100629 [10:48<1:22:42, 17.55it/s]

 13%|█▎        | 13550/100629 [10:48<1:28:27, 16.41it/s]

 13%|█▎        | 13553/100629 [10:48<1:14:53, 19.38it/s]

 13%|█▎        | 13556/100629 [10:48<1:15:12, 19.30it/s]

 13%|█▎        | 13559/100629 [10:48<1:09:34, 20.86it/s]

 13%|█▎        | 13562/100629 [10:48<1:09:07, 20.99it/s]

 13%|█▎        | 13565/100629 [10:49<1:06:21, 21.87it/s]

 13%|█▎        | 13568/100629 [10:49<1:15:47, 19.14it/s]

 13%|█▎        | 13571/100629 [10:49<1:24:19, 17.21it/s]

 13%|█▎        | 13573/100629 [10:49<1:29:57, 16.13it/s]

 13%|█▎        | 13577/100629 [10:49<1:18:12, 18.55it/s]

 13%|█▎        | 13580/100629 [10:49<1:22:26, 17.60it/s]

 13%|█▎        | 13582/100629 [10:50<1:30:49, 15.97it/s]

 13%|█▎        | 13584/100629 [10:50<1:32:19, 15.71it/s]

 14%|█▎        | 13586/100629 [10:50<1:31:40, 15.82it/s]

 14%|█▎        | 13588/100629 [10:50<1:33:55, 15.45it/s]

 14%|█▎        | 13590/100629 [10:50<1:30:14, 16.07it/s]

 14%|█▎        | 13592/100629 [10:50<1:25:55, 16.88it/s]

 14%|█▎        | 13594/100629 [10:50<1:26:15, 16.82it/s]

 14%|█▎        | 13598/100629 [10:51<1:07:10, 21.59it/s]

 14%|█▎        | 13601/100629 [10:51<1:12:00, 20.14it/s]

 14%|█▎        | 13604/100629 [10:51<1:10:19, 20.62it/s]

 14%|█▎        | 13607/100629 [10:51<1:07:29, 21.49it/s]

 14%|█▎        | 13610/100629 [10:51<1:28:58, 16.30it/s]

 14%|█▎        | 13612/100629 [10:51<1:30:15, 16.07it/s]

 14%|█▎        | 13614/100629 [10:51<1:26:33, 16.76it/s]

 14%|█▎        | 13616/100629 [10:52<1:27:38, 16.55it/s]

 14%|█▎        | 13619/100629 [10:52<1:28:08, 16.45it/s]

 14%|█▎        | 13622/100629 [10:52<1:34:49, 15.29it/s]

 14%|█▎        | 13624/100629 [10:52<1:33:42, 15.48it/s]

 14%|█▎        | 13627/100629 [10:52<1:20:07, 18.10it/s]

 14%|█▎        | 13630/100629 [10:52<1:11:16, 20.34it/s]

 14%|█▎        | 13633/100629 [10:52<1:08:44, 21.09it/s]

 14%|█▎        | 13637/100629 [10:53<57:01, 25.42it/s]

 14%|█▎        | 13640/100629 [10:53<56:17, 25.76it/s]

 14%|█▎        | 13643/100629 [10:53<1:07:33, 21.46it/s]

 14%|█▎        | 13646/100629 [10:53<1:04:25, 22.51it/s]

 14%|█▎        | 13649/100629 [10:53<1:06:49, 21.69it/s]

 14%|█▎        | 13652/100629 [10:53<1:02:07, 23.33it/s]

 14%|█▎        | 13655/100629 [10:53<1:09:19, 20.91it/s]

 14%|█▎        | 13658/100629 [10:54<1:03:04, 22.98it/s]

 14%|█▎        | 13662/100629 [10:54<1:01:44, 23.48it/s]

 14%|█▎        | 13666/100629 [10:54<55:58, 25.89it/s]

 14%|█▎        | 13669/100629 [10:54<57:23, 25.25it/s]

 14%|█▎        | 13673/100629 [10:54<51:20, 28.23it/s]

 14%|█▎        | 13677/100629 [10:54<50:39, 28.61it/s]

 14%|█▎        | 13680/100629 [10:54<59:11, 24.49it/s]

 14%|█▎        | 13684/100629 [10:54<54:04, 26.80it/s]

 14%|█▎        | 13687/100629 [10:55<55:17, 26.21it/s]

 14%|█▎        | 13690/100629 [10:55<55:24, 26.15it/s]

 14%|█▎        | 13693/100629 [10:55<1:08:26, 21.17it/s]

 14%|█▎        | 13698/100629 [10:55<1:05:11, 22.22it/s]

 14%|█▎        | 13701/100629 [10:55<1:06:02, 21.94it/s]

 14%|█▎        | 13704/100629 [10:55<1:05:14, 22.20it/s]

 14%|█▎        | 13708/100629 [10:56<58:40, 24.69it/s]

 14%|█▎        | 13711/100629 [10:56<1:01:12, 23.66it/s]

 14%|█▎        | 13714/100629 [10:56<1:07:56, 21.32it/s]

 14%|█▎        | 13717/100629 [10:56<1:07:36, 21.43it/s]

 14%|█▎        | 13720/100629 [10:56<1:15:37, 19.15it/s]

 14%|█▎        | 13723/100629 [10:56<1:16:20, 18.97it/s]

 14%|█▎        | 13725/100629 [10:56<1:18:46, 18.39it/s]

 14%|█▎        | 13727/100629 [10:57<1:31:52, 15.76it/s]

 14%|█▎        | 13730/100629 [10:57<1:22:36, 17.53it/s]

 14%|█▎        | 13733/100629 [10:57<1:15:41, 19.14it/s]

 14%|█▎        | 13735/100629 [10:57<1:16:33, 18.92it/s]

 14%|█▎        | 13737/100629 [10:57<1:19:43, 18.17it/s]

 14%|█▎        | 13739/100629 [10:57<1:20:46, 17.93it/s]

 14%|█▎        | 13741/100629 [10:57<1:23:46, 17.29it/s]

 14%|█▎        | 13744/100629 [10:58<1:15:17, 19.23it/s]

 14%|█▎        | 13746/100629 [10:58<1:18:27, 18.46it/s]

 14%|█▎        | 13749/100629 [10:58<1:11:36, 20.22it/s]

 14%|█▎        | 13753/100629 [10:58<1:05:05, 22.25it/s]

 14%|█▎        | 13756/100629 [10:58<1:20:29, 17.99it/s]

 14%|█▎        | 13759/100629 [10:58<1:13:05, 19.81it/s]

 14%|█▎        | 13762/100629 [10:58<1:12:44, 19.90it/s]

 14%|█▎        | 13765/100629 [10:59<1:08:59, 20.99it/s]

 14%|█▎        | 13768/100629 [10:59<1:13:05, 19.81it/s]

 14%|█▎        | 13771/100629 [10:59<1:13:31, 19.69it/s]

 14%|█▎        | 13774/100629 [10:59<1:08:00, 21.29it/s]

 14%|█▎        | 13777/100629 [10:59<1:10:55, 20.41it/s]

 14%|█▎        | 13780/100629 [10:59<1:23:24, 17.36it/s]

 14%|█▎        | 13783/100629 [11:00<1:17:23, 18.70it/s]

 14%|█▎        | 13786/100629 [11:00<1:11:59, 20.11it/s]

 14%|█▎        | 13789/100629 [11:00<1:05:51, 21.98it/s]

 14%|█▎        | 13792/100629 [11:00<1:08:07, 21.24it/s]

 14%|█▎        | 13795/100629 [11:00<1:02:11, 23.27it/s]

 14%|█▎        | 13798/100629 [11:00<59:50, 24.18it/s]

 14%|█▎        | 13802/100629 [11:00<51:56, 27.86it/s]

 14%|█▎        | 13806/100629 [11:00<50:05, 28.88it/s]

 14%|█▎        | 13809/100629 [11:00<51:07, 28.31it/s]

 14%|█▎        | 13812/100629 [11:01<1:04:58, 22.27it/s]

 14%|█▎        | 13815/100629 [11:01<1:03:50, 22.66it/s]

 14%|█▎        | 13818/100629 [11:01<1:23:53, 17.25it/s]

 14%|█▎        | 13821/100629 [11:01<1:23:40, 17.29it/s]

 14%|█▎        | 13825/100629 [11:01<1:06:55, 21.62it/s]

 14%|█▎        | 13829/100629 [11:01<1:01:28, 23.53it/s]

 14%|█▎        | 13833/100629 [11:02<56:09, 25.76it/s]

 14%|█▍        | 13837/100629 [11:02<52:08, 27.74it/s]

 14%|█▍        | 13841/100629 [11:02<53:10, 27.21it/s]

 14%|█▍        | 13844/100629 [11:02<1:02:25, 23.17it/s]

 14%|█▍        | 13847/100629 [11:02<1:02:11, 23.26it/s]

 14%|█▍        | 13850/100629 [11:02<58:26, 24.75it/s]

 14%|█▍        | 13853/100629 [11:02<57:21, 25.22it/s]

 14%|█▍        | 13856/100629 [11:03<1:06:01, 21.90it/s]

 14%|█▍        | 13859/100629 [11:03<1:02:25, 23.17it/s]

 14%|█▍        | 13862/100629 [11:03<1:01:15, 23.61it/s]

 14%|█▍        | 13865/100629 [11:03<59:22, 24.36it/s]

 14%|█▍        | 13868/100629 [11:03<58:35, 24.68it/s]

 14%|█▍        | 13871/100629 [11:03<1:01:00, 23.70it/s]

 14%|█▍        | 13874/100629 [11:03<58:56, 24.53it/s]

 14%|█▍        | 13878/100629 [11:03<51:48, 27.90it/s]

 14%|█▍        | 13881/100629 [11:04<52:10, 27.71it/s]

 14%|█▍        | 13885/100629 [11:04<46:56, 30.80it/s]

 14%|█▍        | 13889/100629 [11:04<49:11, 29.38it/s]

 14%|█▍        | 13893/100629 [11:04<1:05:12, 22.17it/s]

 14%|█▍        | 13896/100629 [11:04<1:06:03, 21.88it/s]

 14%|█▍        | 13899/100629 [11:04<1:09:30, 20.80it/s]

 14%|█▍        | 13902/100629 [11:05<1:09:27, 20.81it/s]

 14%|█▍        | 13905/100629 [11:05<1:10:51, 20.40it/s]

 14%|█▍        | 13909/100629 [11:05<1:01:08, 23.64it/s]

 14%|█▍        | 13912/100629 [11:05<1:10:07, 20.61it/s]

 14%|█▍        | 13915/100629 [11:05<1:18:33, 18.40it/s]

 14%|█▍        | 13917/100629 [11:05<1:19:26, 18.19it/s]

 14%|█▍        | 13920/100629 [11:05<1:14:48, 19.32it/s]

 14%|█▍        | 13925/100629 [11:06<1:00:13, 24.00it/s]

 14%|█▍        | 13928/100629 [11:06<1:04:51, 22.28it/s]

 14%|█▍        | 13931/100629 [11:06<1:09:21, 20.83it/s]

 14%|█▍        | 13934/100629 [11:06<1:09:24, 20.82it/s]

 14%|█▍        | 13937/100629 [11:06<1:07:12, 21.50it/s]

 14%|█▍        | 13940/100629 [11:06<1:05:15, 22.14it/s]

 14%|█▍        | 13943/100629 [11:06<1:11:33, 20.19it/s]

 14%|█▍        | 13946/100629 [11:07<1:05:39, 22.00it/s]

 14%|█▍        | 13949/100629 [11:07<1:00:28, 23.89it/s]

 14%|█▍        | 13952/100629 [11:07<1:16:59, 18.76it/s]

 14%|█▍        | 13955/100629 [11:07<1:26:30, 16.70it/s]

 14%|█▍        | 13958/100629 [11:07<1:26:51, 16.63it/s]

 14%|█▍        | 13960/100629 [11:07<1:28:10, 16.38it/s]

 14%|█▍        | 13963/100629 [11:08<1:26:18, 16.73it/s]

 14%|█▍        | 13966/100629 [11:08<1:17:51, 18.55it/s]

 14%|█▍        | 13969/100629 [11:08<1:09:04, 20.91it/s]

 14%|█▍        | 13972/100629 [11:08<1:09:21, 20.83it/s]

 14%|█▍        | 13975/100629 [11:08<1:05:30, 22.05it/s]

 14%|█▍        | 13978/100629 [11:08<1:22:56, 17.41it/s]

 14%|█▍        | 13981/100629 [11:09<1:16:18, 18.93it/s]

 14%|█▍        | 13984/100629 [11:09<1:08:12, 21.17it/s]

 14%|█▍        | 13989/100629 [11:09<58:55, 24.50it/s]

 14%|█▍        | 13992/100629 [11:09<1:01:04, 23.64it/s]

 14%|█▍        | 13996/100629 [11:09<57:24, 25.15it/s]

 14%|█▍        | 13999/100629 [11:09<1:05:34, 22.02it/s]

 14%|█▍        | 14002/100629 [11:09<1:05:34, 22.02it/s]

 14%|█▍        | 14005/100629 [11:09<1:01:10, 23.60it/s]

 14%|█▍        | 14010/100629 [11:10<56:14, 25.67it/s]

 14%|█▍        | 14013/100629 [11:10<59:43, 24.17it/s]

 14%|█▍        | 14016/100629 [11:10<1:01:25, 23.50it/s]

 14%|█▍        | 14019/100629 [11:10<1:02:32, 23.08it/s]

 14%|█▍        | 14023/100629 [11:10<56:19, 25.62it/s]

 14%|█▍        | 14026/100629 [11:10<1:18:54, 18.29it/s]

 14%|█▍        | 14029/100629 [11:11<1:14:46, 19.30it/s]

 14%|█▍        | 14033/100629 [11:11<1:11:14, 20.26it/s]

 14%|█▍        | 14036/100629 [11:11<1:08:37, 21.03it/s]

 14%|█▍        | 14039/100629 [11:11<1:12:08, 20.01it/s]

 14%|█▍        | 14042/100629 [11:11<1:17:24, 18.64it/s]

 14%|█▍        | 14044/100629 [11:11<1:19:38, 18.12it/s]

 14%|█▍        | 14046/100629 [11:12<1:29:40, 16.09it/s]

 14%|█▍        | 14050/100629 [11:12<1:17:36, 18.59it/s]

 14%|█▍        | 14053/100629 [11:12<1:10:27, 20.48it/s]

 14%|█▍        | 14056/100629 [11:12<1:05:26, 22.05it/s]

 14%|█▍        | 14059/100629 [11:12<1:01:52, 23.32it/s]

 14%|█▍        | 14062/100629 [11:12<58:27, 24.68it/s]

 14%|█▍        | 14065/100629 [11:12<1:21:38, 17.67it/s]

 14%|█▍        | 14069/100629 [11:13<1:07:34, 21.35it/s]

 14%|█▍        | 14072/100629 [11:13<1:03:45, 22.63it/s]

 14%|█▍        | 14076/100629 [11:13<54:35, 26.42it/s]

 14%|█▍        | 14079/100629 [11:13<1:01:09, 23.58it/s]

 14%|█▍        | 14082/100629 [11:13<59:35, 24.21it/s]

 14%|█▍        | 14085/100629 [11:13<1:01:17, 23.53it/s]

 14%|█▍        | 14088/100629 [11:13<1:09:06, 20.87it/s]

 14%|█▍        | 14091/100629 [11:14<1:23:31, 17.27it/s]

 14%|█▍        | 14094/100629 [11:14<1:15:18, 19.15it/s]

 14%|█▍        | 14097/100629 [11:14<1:11:47, 20.09it/s]

 14%|█▍        | 14100/100629 [11:14<1:19:32, 18.13it/s]

 14%|█▍        | 14103/100629 [11:14<1:15:14, 19.17it/s]

 14%|█▍        | 14106/100629 [11:14<1:07:20, 21.41it/s]

 14%|█▍        | 14109/100629 [11:14<1:05:43, 21.94it/s]

 14%|█▍        | 14112/100629 [11:15<1:12:04, 20.01it/s]

 14%|█▍        | 14115/100629 [11:15<1:14:42, 19.30it/s]

 14%|█▍        | 14118/100629 [11:15<1:08:05, 21.18it/s]

 14%|█▍        | 14121/100629 [11:15<1:12:58, 19.76it/s]

 14%|█▍        | 14124/100629 [11:15<1:20:32, 17.90it/s]

 14%|█▍        | 14127/100629 [11:15<1:12:18, 19.94it/s]

 14%|█▍        | 14130/100629 [11:16<1:20:16, 17.96it/s]

 14%|█▍        | 14133/100629 [11:16<1:14:28, 19.36it/s]

 14%|█▍        | 14136/100629 [11:16<1:14:41, 19.30it/s]

 14%|█▍        | 14139/100629 [11:16<1:13:17, 19.67it/s]

 14%|█▍        | 14142/100629 [11:16<1:15:43, 19.04it/s]

 14%|█▍        | 14145/100629 [11:16<1:10:39, 20.40it/s]

 14%|█▍        | 14148/100629 [11:16<1:08:29, 21.04it/s]

 14%|█▍        | 14151/100629 [11:17<1:12:49, 19.79it/s]

 14%|█▍        | 14154/100629 [11:17<1:23:50, 17.19it/s]

 14%|█▍        | 14158/100629 [11:17<1:07:03, 21.49it/s]

 14%|█▍        | 14161/100629 [11:17<1:05:37, 21.96it/s]

 14%|█▍        | 14165/100629 [11:17<1:01:20, 23.49it/s]

 14%|█▍        | 14168/100629 [11:17<59:34, 24.19it/s]

 14%|█▍        | 14172/100629 [11:18<1:03:37, 22.64it/s]

 14%|█▍        | 14175/100629 [11:18<1:10:34, 20.42it/s]

 14%|█▍        | 14178/100629 [11:18<1:05:43, 21.92it/s]

 14%|█▍        | 14181/100629 [11:18<1:08:58, 20.89it/s]

 14%|█▍        | 14185/100629 [11:18<58:23, 24.67it/s]

 14%|█▍        | 14188/100629 [11:18<1:05:59, 21.83it/s]

 14%|█▍        | 14191/100629 [11:18<1:05:50, 21.88it/s]

 14%|█▍        | 14194/100629 [11:19<1:18:03, 18.45it/s]

 14%|█▍        | 14197/100629 [11:19<1:11:17, 20.21it/s]

 14%|█▍        | 14200/100629 [11:19<1:09:55, 20.60it/s]

 14%|█▍        | 14203/100629 [11:19<1:12:53, 19.76it/s]

 14%|█▍        | 14206/100629 [11:19<1:08:37, 20.99it/s]

 14%|█▍        | 14209/100629 [11:20<1:31:20, 15.77it/s]

 14%|█▍        | 14212/100629 [11:20<1:27:16, 16.50it/s]

 14%|█▍        | 14214/100629 [11:20<1:31:18, 15.77it/s]

 14%|█▍        | 14218/100629 [11:20<1:11:16, 20.21it/s]

 14%|█▍        | 14221/100629 [11:20<1:06:07, 21.78it/s]

 14%|█▍        | 14224/100629 [11:20<1:13:57, 19.47it/s]

 14%|█▍        | 14227/100629 [11:20<1:20:00, 18.00it/s]

 14%|█▍        | 14230/100629 [11:21<1:13:20, 19.63it/s]

 14%|█▍        | 14233/100629 [11:21<1:11:34, 20.12it/s]

 14%|█▍        | 14236/100629 [11:21<1:09:32, 20.70it/s]

 14%|█▍        | 14239/100629 [11:21<1:19:59, 18.00it/s]

 14%|█▍        | 14243/100629 [11:21<1:08:39, 20.97it/s]

 14%|█▍        | 14246/100629 [11:21<1:03:28, 22.68it/s]

 14%|█▍        | 14249/100629 [11:21<1:07:49, 21.23it/s]

 14%|█▍        | 14252/100629 [11:22<1:08:44, 20.94it/s]

 14%|█▍        | 14255/100629 [11:22<1:03:33, 22.65it/s]

 14%|█▍        | 14258/100629 [11:22<1:05:18, 22.04it/s]

 14%|█▍        | 14261/100629 [11:22<1:03:43, 22.59it/s]

 14%|█▍        | 14264/100629 [11:22<1:03:34, 22.64it/s]

 14%|█▍        | 14267/100629 [11:22<1:01:08, 23.54it/s]

 14%|█▍        | 14270/100629 [11:22<1:09:48, 20.62it/s]

 14%|█▍        | 14273/100629 [11:23<1:07:48, 21.23it/s]

 14%|█▍        | 14276/100629 [11:23<1:07:42, 21.25it/s]

 14%|█▍        | 14279/100629 [11:23<1:02:55, 22.87it/s]

 14%|█▍        | 14284/100629 [11:23<49:44, 28.93it/s]

 14%|█▍        | 14288/100629 [11:23<49:23, 29.14it/s]

 14%|█▍        | 14292/100629 [11:23<58:53, 24.43it/s]

 14%|█▍        | 14296/100629 [11:23<53:41, 26.80it/s]

 14%|█▍        | 14299/100629 [11:23<53:41, 26.80it/s]

 14%|█▍        | 14302/100629 [11:24<52:23, 27.46it/s]

 14%|█▍        | 14306/100629 [11:24<51:22, 28.00it/s]

 14%|█▍        | 14309/100629 [11:24<52:14, 27.54it/s]

 14%|█▍        | 14312/100629 [11:24<53:25, 26.93it/s]

 14%|█▍        | 14317/100629 [11:24<54:09, 26.56it/s]

 14%|█▍        | 14320/100629 [11:24<57:03, 25.21it/s]

 14%|█▍        | 14323/100629 [11:24<57:07, 25.18it/s]

 14%|█▍        | 14326/100629 [11:25<58:48, 24.46it/s]

 14%|█▍        | 14329/100629 [11:25<1:01:21, 23.44it/s]

 14%|█▍        | 14332/100629 [11:25<58:24, 24.62it/s]

 14%|█▍        | 14335/100629 [11:25<1:04:54, 22.16it/s]

 14%|█▍        | 14338/100629 [11:25<1:01:11, 23.50it/s]

 14%|█▍        | 14341/100629 [11:25<1:00:10, 23.90it/s]

 14%|█▍        | 14345/100629 [11:25<55:21, 25.98it/s]

 14%|█▍        | 14348/100629 [11:25<59:51, 24.02it/s]

 14%|█▍        | 14352/100629 [11:26<55:05, 26.10it/s]

 14%|█▍        | 14355/100629 [11:26<55:00, 26.14it/s]

 14%|█▍        | 14358/100629 [11:26<1:06:44, 21.54it/s]

 14%|█▍        | 14361/100629 [11:26<1:04:01, 22.46it/s]

 14%|█▍        | 14364/100629 [11:26<1:12:06, 19.94it/s]

 14%|█▍        | 14367/100629 [11:26<1:09:05, 20.81it/s]

 14%|█▍        | 14370/100629 [11:26<1:08:09, 21.09it/s]

 14%|█▍        | 14373/100629 [11:27<1:03:06, 22.78it/s]

 14%|█▍        | 14376/100629 [11:27<1:14:59, 19.17it/s]

 14%|█▍        | 14380/100629 [11:27<1:02:39, 22.94it/s]

 14%|█▍        | 14383/100629 [11:27<1:00:05, 23.92it/s]

 14%|█▍        | 14386/100629 [11:27<1:10:23, 20.42it/s]

 14%|█▍        | 14389/100629 [11:27<1:23:17, 17.26it/s]

 14%|█▍        | 14391/100629 [11:28<1:25:28, 16.82it/s]

 14%|█▍        | 14393/100629 [11:28<1:22:32, 17.41it/s]

 14%|█▍        | 14397/100629 [11:28<1:04:27, 22.30it/s]

 14%|█▍        | 14400/100629 [11:28<1:05:36, 21.90it/s]

 14%|█▍        | 14403/100629 [11:28<1:02:04, 23.15it/s]

 14%|█▍        | 14406/100629 [11:28<1:01:52, 23.22it/s]

 14%|█▍        | 14409/100629 [11:28<1:14:03, 19.40it/s]

 14%|█▍        | 14412/100629 [11:29<1:18:58, 18.20it/s]

 14%|█▍        | 14414/100629 [11:29<1:17:27, 18.55it/s]

 14%|█▍        | 14417/100629 [11:29<1:12:22, 19.85it/s]

 14%|█▍        | 14421/100629 [11:29<59:54, 23.98it/s]

 14%|█▍        | 14424/100629 [11:29<1:11:31, 20.09it/s]

 14%|█▍        | 14427/100629 [11:29<1:07:19, 21.34it/s]

 14%|█▍        | 14431/100629 [11:29<1:00:12, 23.86it/s]

 14%|█▍        | 14434/100629 [11:30<1:05:10, 22.04it/s]

 14%|█▍        | 14437/100629 [11:30<1:03:36, 22.58it/s]

 14%|█▍        | 14440/100629 [11:30<1:11:19, 20.14it/s]

 14%|█▍        | 14443/100629 [11:30<1:15:47, 18.95it/s]

 14%|█▍        | 14446/100629 [11:30<1:08:51, 20.86it/s]

 14%|█▍        | 14449/100629 [11:30<1:03:20, 22.68it/s]

 14%|█▍        | 14453/100629 [11:30<53:58, 26.61it/s]

 14%|█▍        | 14456/100629 [11:30<55:10, 26.03it/s]

 14%|█▍        | 14459/100629 [11:31<56:53, 25.24it/s]

 14%|█▍        | 14462/100629 [11:31<56:57, 25.21it/s]

 14%|█▍        | 14465/100629 [11:31<1:05:46, 21.84it/s]

 14%|█▍        | 14468/100629 [11:31<1:03:36, 22.57it/s]

 14%|█▍        | 14471/100629 [11:31<1:06:13, 21.68it/s]

 14%|█▍        | 14474/100629 [11:31<1:12:20, 19.85it/s]

 14%|█▍        | 14477/100629 [11:31<1:07:28, 21.28it/s]

 14%|█▍        | 14480/100629 [11:32<1:03:03, 22.77it/s]

 14%|█▍        | 14483/100629 [11:32<1:16:34, 18.75it/s]

 14%|█▍        | 14486/100629 [11:32<1:26:31, 16.59it/s]

 14%|█▍        | 14488/100629 [11:32<1:25:17, 16.83it/s]

 14%|█▍        | 14491/100629 [11:32<1:13:26, 19.55it/s]

 14%|█▍        | 14494/100629 [11:32<1:11:05, 20.19it/s]

 14%|█▍        | 14498/100629 [11:33<59:43, 24.03it/s]

 14%|█▍        | 14501/100629 [11:33<1:03:10, 22.72it/s]

 14%|█▍        | 14504/100629 [11:33<1:01:57, 23.17it/s]

 14%|█▍        | 14507/100629 [11:33<1:06:12, 21.68it/s]

 14%|█▍        | 14510/100629 [11:33<1:09:57, 20.52it/s]

 14%|█▍        | 14513/100629 [11:33<1:06:32, 21.57it/s]

 14%|█▍        | 14516/100629 [11:33<1:04:05, 22.40it/s]

 14%|█▍        | 14519/100629 [11:34<1:05:47, 21.81it/s]

 14%|█▍        | 14522/100629 [11:34<1:05:44, 21.83it/s]

 14%|█▍        | 14525/100629 [11:34<1:03:07, 22.73it/s]

 14%|█▍        | 14528/100629 [11:34<1:00:14, 23.82it/s]

 14%|█▍        | 14532/100629 [11:34<51:44, 27.74it/s]

 14%|█▍        | 14535/100629 [11:34<57:18, 25.04it/s]

 14%|█▍        | 14538/100629 [11:34<1:07:21, 21.30it/s]

 14%|█▍        | 14542/100629 [11:34<1:01:25, 23.36it/s]

 14%|█▍        | 14545/100629 [11:35<1:02:32, 22.94it/s]

 14%|█▍        | 14548/100629 [11:35<1:05:57, 21.75it/s]

 14%|█▍        | 14551/100629 [11:35<1:08:15, 21.02it/s]

 14%|█▍        | 14554/100629 [11:35<1:15:05, 19.11it/s]

 14%|█▍        | 14556/100629 [11:35<1:18:00, 18.39it/s]

 14%|█▍        | 14560/100629 [11:35<1:02:35, 22.92it/s]

 14%|█▍        | 14563/100629 [11:36<1:17:00, 18.63it/s]

 14%|█▍        | 14566/100629 [11:36<1:13:22, 19.55it/s]

 14%|█▍        | 14569/100629 [11:36<1:09:05, 20.76it/s]

 14%|█▍        | 14572/100629 [11:36<1:14:09, 19.34it/s]

 14%|█▍        | 14575/100629 [11:36<1:12:39, 19.74it/s]

 14%|█▍        | 14578/100629 [11:36<1:10:44, 20.27it/s]

 14%|█▍        | 14581/100629 [11:36<1:08:39, 20.89it/s]

 14%|█▍        | 14584/100629 [11:37<1:04:46, 22.14it/s]

 14%|█▍        | 14587/100629 [11:37<1:02:29, 22.94it/s]

 14%|█▍        | 14590/100629 [11:37<1:12:58, 19.65it/s]

 15%|█▍        | 14593/100629 [11:37<1:09:33, 20.61it/s]

 15%|█▍        | 14596/100629 [11:37<1:31:54, 15.60it/s]

 15%|█▍        | 14598/100629 [11:37<1:28:03, 16.28it/s]

 15%|█▍        | 14600/100629 [11:37<1:24:43, 16.92it/s]

 15%|█▍        | 14602/100629 [11:38<1:28:44, 16.16it/s]

 15%|█▍        | 14605/100629 [11:38<1:17:02, 18.61it/s]

 15%|█▍        | 14607/100629 [11:38<1:18:45, 18.20it/s]

 15%|█▍        | 14610/100629 [11:38<1:15:52, 18.90it/s]

 15%|█▍        | 14613/100629 [11:38<1:08:56, 20.80it/s]

 15%|█▍        | 14617/100629 [11:38<58:33, 24.48it/s]

 15%|█▍        | 14620/100629 [11:38<58:04, 24.68it/s]

 15%|█▍        | 14624/100629 [11:39<55:39, 25.75it/s]

 15%|█▍        | 14627/100629 [11:39<1:03:23, 22.61it/s]

 15%|█▍        | 14630/100629 [11:39<1:18:48, 18.19it/s]

 15%|█▍        | 14632/100629 [11:39<1:23:57, 17.07it/s]

 15%|█▍        | 14634/100629 [11:39<1:22:21, 17.40it/s]

 15%|█▍        | 14636/100629 [11:39<1:21:03, 17.68it/s]

 15%|█▍        | 14641/100629 [11:39<1:04:12, 22.32it/s]

 15%|█▍        | 14645/100629 [11:40<55:15, 25.93it/s]

 15%|█▍        | 14648/100629 [11:40<56:08, 25.52it/s]

 15%|█▍        | 14651/100629 [11:40<59:48, 23.96it/s]

 15%|█▍        | 14655/100629 [11:40<1:01:10, 23.42it/s]

 15%|█▍        | 14658/100629 [11:40<57:46, 24.80it/s]

 15%|█▍        | 14661/100629 [11:40<1:08:43, 20.85it/s]

 15%|█▍        | 14664/100629 [11:40<1:11:36, 20.01it/s]

 15%|█▍        | 14667/100629 [11:41<1:10:49, 20.23it/s]

 15%|█▍        | 14670/100629 [11:41<1:11:42, 19.98it/s]

 15%|█▍        | 14673/100629 [11:41<1:10:16, 20.38it/s]

 15%|█▍        | 14676/100629 [11:41<1:05:18, 21.93it/s]

 15%|█▍        | 14679/100629 [11:41<1:07:02, 21.37it/s]

 15%|█▍        | 14685/100629 [11:41<51:19, 27.91it/s]

 15%|█▍        | 14688/100629 [11:41<55:59, 25.58it/s]

 15%|█▍        | 14691/100629 [11:42<1:02:33, 22.89it/s]

 15%|█▍        | 14695/100629 [11:42<53:57, 26.54it/s]

 15%|█▍        | 14698/100629 [11:42<55:08, 25.97it/s]

 15%|█▍        | 14702/100629 [11:42<51:36, 27.75it/s]

 15%|█▍        | 14706/100629 [11:42<47:17, 30.28it/s]

 15%|█▍        | 14710/100629 [11:42<1:06:04, 21.67it/s]

 15%|█▍        | 14713/100629 [11:43<1:05:21, 21.91it/s]

 15%|█▍        | 14716/100629 [11:43<1:03:13, 22.65it/s]

 15%|█▍        | 14721/100629 [11:43<55:50, 25.64it/s]

 15%|█▍        | 14726/100629 [11:43<49:57, 28.65it/s]

 15%|█▍        | 14729/100629 [11:43<53:41, 26.66it/s]

 15%|█▍        | 14732/100629 [11:43<55:51, 25.63it/s]

 15%|█▍        | 14735/100629 [11:43<59:14, 24.17it/s]

 15%|█▍        | 14738/100629 [11:43<58:07, 24.63it/s]

 15%|█▍        | 14741/100629 [11:44<1:04:02, 22.35it/s]

 15%|█▍        | 14744/100629 [11:44<1:06:47, 21.43it/s]

 15%|█▍        | 14747/100629 [11:44<1:09:48, 20.50it/s]

 15%|█▍        | 14750/100629 [11:44<1:08:12, 20.98it/s]

 15%|█▍        | 14754/100629 [11:44<1:01:45, 23.18it/s]

 15%|█▍        | 14757/100629 [11:44<1:02:04, 23.06it/s]

 15%|█▍        | 14760/100629 [11:44<1:03:07, 22.67it/s]

 15%|█▍        | 14763/100629 [11:45<1:04:27, 22.20it/s]

 15%|█▍        | 14766/100629 [11:45<1:05:37, 21.80it/s]

 15%|█▍        | 14769/100629 [11:45<1:05:16, 21.92it/s]

 15%|█▍        | 14773/100629 [11:45<1:03:55, 22.38it/s]

 15%|█▍        | 14776/100629 [11:45<1:15:41, 18.91it/s]

 15%|█▍        | 14779/100629 [11:45<1:12:06, 19.84it/s]

 15%|█▍        | 14782/100629 [11:46<1:11:49, 19.92it/s]

 15%|█▍        | 14785/100629 [11:46<1:08:42, 20.83it/s]

 15%|█▍        | 14788/100629 [11:46<1:33:33, 15.29it/s]

 15%|█▍        | 14790/100629 [11:46<1:28:55, 16.09it/s]

 15%|█▍        | 14792/100629 [11:46<1:28:47, 16.11it/s]

 15%|█▍        | 14795/100629 [11:46<1:16:30, 18.70it/s]

 15%|█▍        | 14798/100629 [11:47<1:13:12, 19.54it/s]

 15%|█▍        | 14801/100629 [11:47<1:11:05, 20.12it/s]

 15%|█▍        | 14804/100629 [11:47<1:09:50, 20.48it/s]

 15%|█▍        | 14808/100629 [11:47<1:13:41, 19.41it/s]

 15%|█▍        | 14813/100629 [11:47<1:02:44, 22.79it/s]

 15%|█▍        | 14816/100629 [11:47<1:08:04, 21.01it/s]

 15%|█▍        | 14819/100629 [11:48<1:15:01, 19.06it/s]

 15%|█▍        | 14821/100629 [11:48<1:15:46, 18.87it/s]

 15%|█▍        | 14823/100629 [11:48<1:16:10, 18.77it/s]

 15%|█▍        | 14827/100629 [11:48<1:03:17, 22.59it/s]

 15%|█▍        | 14830/100629 [11:48<1:17:49, 18.37it/s]

 15%|█▍        | 14833/100629 [11:48<1:20:56, 17.67it/s]

 15%|█▍        | 14835/100629 [11:48<1:26:57, 16.44it/s]

 15%|█▍        | 14837/100629 [11:49<1:26:33, 16.52it/s]

 15%|█▍        | 14839/100629 [11:49<1:26:55, 16.45it/s]

 15%|█▍        | 14841/100629 [11:49<1:42:57, 13.89it/s]

 15%|█▍        | 14844/100629 [11:49<1:28:30, 16.15it/s]

 15%|█▍        | 14846/100629 [11:49<1:34:17, 15.16it/s]

 15%|█▍        | 14848/100629 [11:49<1:34:47, 15.08it/s]

 15%|█▍        | 14851/100629 [11:49<1:26:27, 16.54it/s]

 15%|█▍        | 14853/100629 [11:50<1:30:50, 15.74it/s]

 15%|█▍        | 14856/100629 [11:50<1:32:30, 15.45it/s]

 15%|█▍        | 14859/100629 [11:50<1:22:39, 17.29it/s]

 15%|█▍        | 14863/100629 [11:50<1:05:47, 21.73it/s]

 15%|█▍        | 14866/100629 [11:50<1:04:09, 22.28it/s]

 15%|█▍        | 14869/100629 [11:50<1:00:41, 23.55it/s]

 15%|█▍        | 14872/100629 [11:50<1:04:50, 22.04it/s]

 15%|█▍        | 14875/100629 [11:51<1:10:03, 20.40it/s]

 15%|█▍        | 14878/100629 [11:51<1:04:18, 22.23it/s]

 15%|█▍        | 14881/100629 [11:51<1:08:47, 20.77it/s]

 15%|█▍        | 14884/100629 [11:51<1:17:37, 18.41it/s]

 15%|█▍        | 14886/100629 [11:51<1:35:11, 15.01it/s]

 15%|█▍        | 14890/100629 [11:51<1:19:42, 17.93it/s]

 15%|█▍        | 14893/100629 [11:52<1:13:56, 19.32it/s]

 15%|█▍        | 14896/100629 [11:52<1:13:22, 19.47it/s]

 15%|█▍        | 14899/100629 [11:52<1:58:41, 12.04it/s]

 15%|█▍        | 14903/100629 [11:52<1:29:45, 15.92it/s]

 15%|█▍        | 14907/100629 [11:52<1:12:29, 19.71it/s]

 15%|█▍        | 14910/100629 [11:53<1:07:58, 21.02it/s]

 15%|█▍        | 14913/100629 [11:53<1:06:41, 21.42it/s]

 15%|█▍        | 14917/100629 [11:53<57:31, 24.83it/s]

 15%|█▍        | 14920/100629 [11:53<1:01:22, 23.28it/s]

 15%|█▍        | 14923/100629 [11:53<1:00:39, 23.55it/s]

 15%|█▍        | 14926/100629 [11:53<57:18, 24.93it/s]

 15%|█▍        | 14929/100629 [11:53<55:36, 25.69it/s]

 15%|█▍        | 14932/100629 [11:53<1:01:28, 23.23it/s]

 15%|█▍        | 14935/100629 [11:54<1:06:51, 21.36it/s]

 15%|█▍        | 14940/100629 [11:54<53:17, 26.80it/s]

 15%|█▍        | 14943/100629 [11:54<56:07, 25.44it/s]

 15%|█▍        | 14947/100629 [11:54<51:00, 27.99it/s]

 15%|█▍        | 14950/100629 [11:54<1:10:28, 20.26it/s]

 15%|█▍        | 14953/100629 [11:54<1:11:49, 19.88it/s]

 15%|█▍        | 14956/100629 [11:55<1:27:42, 16.28it/s]

 15%|█▍        | 14960/100629 [11:55<1:13:23, 19.45it/s]

 15%|█▍        | 14963/100629 [11:55<1:16:22, 18.70it/s]

 15%|█▍        | 14966/100629 [11:55<1:29:32, 15.94it/s]

 15%|█▍        | 14968/100629 [11:55<1:30:13, 15.82it/s]

 15%|█▍        | 14971/100629 [11:56<1:23:24, 17.11it/s]

 15%|█▍        | 14973/100629 [11:56<1:24:38, 16.87it/s]

 15%|█▍        | 14975/100629 [11:56<1:32:48, 15.38it/s]

 15%|█▍        | 14979/100629 [11:56<1:12:02, 19.81it/s]

 15%|█▍        | 14982/100629 [11:56<1:23:52, 17.02it/s]

 15%|█▍        | 14985/100629 [11:56<1:16:52, 18.57it/s]

 15%|█▍        | 14988/100629 [11:56<1:16:26, 18.67it/s]

 15%|█▍        | 14991/100629 [11:57<1:18:02, 18.29it/s]

 15%|█▍        | 14995/100629 [11:57<1:17:54, 18.32it/s]

 15%|█▍        | 14997/100629 [11:57<1:20:00, 17.84it/s]

 15%|█▍        | 15000/100629 [11:57<1:15:05, 19.01it/s]

 15%|█▍        | 15002/100629 [11:57<1:16:14, 18.72it/s]

 15%|█▍        | 15004/100629 [11:57<1:17:01, 18.53it/s]

 15%|█▍        | 15007/100629 [11:57<1:15:44, 18.84it/s]

 15%|█▍        | 15009/100629 [11:58<1:18:25, 18.20it/s]

 15%|█▍        | 15012/100629 [11:58<1:18:02, 18.28it/s]

 15%|█▍        | 15016/100629 [11:58<1:04:50, 22.01it/s]

 15%|█▍        | 15019/100629 [11:58<1:00:43, 23.50it/s]

 15%|█▍        | 15022/100629 [11:58<1:02:57, 22.66it/s]

 15%|█▍        | 15025/100629 [11:58<1:05:45, 21.69it/s]

 15%|█▍        | 15031/100629 [11:58<49:11, 29.01it/s]

 15%|█▍        | 15034/100629 [11:59<53:54, 26.47it/s]

 15%|█▍        | 15037/100629 [11:59<1:07:47, 21.04it/s]

 15%|█▍        | 15040/100629 [11:59<1:11:39, 19.91it/s]

 15%|█▍        | 15043/100629 [11:59<1:25:49, 16.62it/s]

 15%|█▍        | 15045/100629 [11:59<1:29:37, 15.92it/s]

 15%|█▍        | 15049/100629 [11:59<1:11:03, 20.07it/s]

 15%|█▍        | 15052/100629 [12:00<1:07:38, 21.09it/s]

 15%|█▍        | 15055/100629 [12:00<1:02:36, 22.78it/s]

 15%|█▍        | 15058/100629 [12:00<1:13:14, 19.47it/s]

 15%|█▍        | 15061/100629 [12:00<1:17:44, 18.35it/s]

 15%|█▍        | 15063/100629 [12:00<1:25:49, 16.62it/s]

 15%|█▍        | 15067/100629 [12:00<1:11:41, 19.89it/s]

 15%|█▍        | 15070/100629 [12:01<1:09:20, 20.56it/s]

 15%|█▍        | 15073/100629 [12:01<1:06:22, 21.48it/s]

 15%|█▍        | 15076/100629 [12:01<1:03:10, 22.57it/s]

 15%|█▍        | 15079/100629 [12:01<1:00:20, 23.63it/s]

 15%|█▍        | 15083/100629 [12:01<1:02:32, 22.80it/s]

 15%|█▍        | 15086/100629 [12:01<1:01:23, 23.22it/s]

 15%|█▍        | 15089/100629 [12:01<1:07:58, 20.97it/s]

 15%|█▍        | 15092/100629 [12:02<1:16:46, 18.57it/s]

 15%|█▌        | 15096/100629 [12:02<1:05:32, 21.75it/s]

 15%|█▌        | 15099/100629 [12:02<1:10:12, 20.30it/s]

 15%|█▌        | 15103/100629 [12:02<1:05:59, 21.60it/s]

 15%|█▌        | 15107/100629 [12:02<1:02:39, 22.75it/s]

 15%|█▌        | 15111/100629 [12:02<56:04, 25.42it/s]

 15%|█▌        | 15114/100629 [12:02<1:02:32, 22.79it/s]

 15%|█▌        | 15117/100629 [12:03<1:09:29, 20.51it/s]

 15%|█▌        | 15120/100629 [12:03<1:19:17, 17.98it/s]

 15%|█▌        | 15124/100629 [12:03<1:09:46, 20.42it/s]

 15%|█▌        | 15127/100629 [12:03<1:13:04, 19.50it/s]

 15%|█▌        | 15130/100629 [12:03<1:10:06, 20.33it/s]

 15%|█▌        | 15133/100629 [12:04<1:11:27, 19.94it/s]

 15%|█▌        | 15136/100629 [12:04<1:09:53, 20.39it/s]

 15%|█▌        | 15140/100629 [12:04<58:53, 24.19it/s]

 15%|█▌        | 15143/100629 [12:04<1:00:10, 23.68it/s]

 15%|█▌        | 15146/100629 [12:04<57:09, 24.93it/s]

 15%|█▌        | 15149/100629 [12:04<1:17:04, 18.48it/s]

 15%|█▌        | 15152/100629 [12:04<1:12:21, 19.69it/s]

 15%|█▌        | 15155/100629 [12:04<1:05:06, 21.88it/s]

 15%|█▌        | 15158/100629 [12:05<1:10:46, 20.13it/s]

 15%|█▌        | 15162/100629 [12:05<59:02, 24.13it/s]

 15%|█▌        | 15165/100629 [12:05<58:43, 24.25it/s]

 15%|█▌        | 15168/100629 [12:05<1:20:55, 17.60it/s]

 15%|█▌        | 15171/100629 [12:05<1:12:32, 19.63it/s]

 15%|█▌        | 15174/100629 [12:05<1:12:59, 19.51it/s]

 15%|█▌        | 15177/100629 [12:06<1:12:32, 19.63it/s]

 15%|█▌        | 15180/100629 [12:06<1:16:17, 18.67it/s]

 15%|█▌        | 15183/100629 [12:06<1:13:56, 19.26it/s]

 15%|█▌        | 15186/100629 [12:06<1:11:23, 19.95it/s]

 15%|█▌        | 15189/100629 [12:06<1:07:23, 21.13it/s]

 15%|█▌        | 15192/100629 [12:06<1:13:08, 19.47it/s]

 15%|█▌        | 15195/100629 [12:07<1:23:04, 17.14it/s]

 15%|█▌        | 15198/100629 [12:07<1:15:59, 18.74it/s]

 15%|█▌        | 15201/100629 [12:07<1:10:21, 20.23it/s]

 15%|█▌        | 15205/100629 [12:07<1:08:20, 20.83it/s]

 15%|█▌        | 15208/100629 [12:07<1:21:53, 17.38it/s]

 15%|█▌        | 15211/100629 [12:07<1:12:11, 19.72it/s]

 15%|█▌        | 15215/100629 [12:08<1:14:29, 19.11it/s]

 15%|█▌        | 15218/100629 [12:08<1:12:51, 19.54it/s]

 15%|█▌        | 15222/100629 [12:08<1:04:34, 22.04it/s]

 15%|█▌        | 15225/100629 [12:08<1:04:04, 22.22it/s]

 15%|█▌        | 15228/100629 [12:08<1:02:55, 22.62it/s]

 15%|█▌        | 15231/100629 [12:08<1:08:04, 20.91it/s]

 15%|█▌        | 15234/100629 [12:08<1:10:13, 20.27it/s]

 15%|█▌        | 15237/100629 [12:09<1:13:46, 19.29it/s]

 15%|█▌        | 15241/100629 [12:09<1:09:43, 20.41it/s]

 15%|█▌        | 15244/100629 [12:09<1:06:06, 21.53it/s]

 15%|█▌        | 15247/100629 [12:09<1:02:37, 22.72it/s]

 15%|█▌        | 15250/100629 [12:09<59:26, 23.94it/s]

 15%|█▌        | 15253/100629 [12:09<1:13:04, 19.47it/s]

 15%|█▌        | 15257/100629 [12:09<1:03:43, 22.33it/s]

 15%|█▌        | 15260/100629 [12:10<1:08:56, 20.64it/s]

 15%|█▌        | 15263/100629 [12:10<1:11:20, 19.94it/s]

 15%|█▌        | 15266/100629 [12:10<1:17:43, 18.31it/s]

 15%|█▌        | 15272/100629 [12:10<57:25, 24.77it/s]

 15%|█▌        | 15276/100629 [12:10<50:58, 27.91it/s]

 15%|█▌        | 15280/100629 [12:10<56:36, 25.13it/s]

 15%|█▌        | 15285/100629 [12:11<50:30, 28.16it/s]

 15%|█▌        | 15289/100629 [12:11<1:01:18, 23.20it/s]

 15%|█▌        | 15292/100629 [12:11<59:25, 23.94it/s]

 15%|█▌        | 15296/100629 [12:11<55:51, 25.46it/s]

 15%|█▌        | 15299/100629 [12:11<54:34, 26.06it/s]

 15%|█▌        | 15302/100629 [12:11<1:08:09, 20.86it/s]

 15%|█▌        | 15305/100629 [12:12<1:12:22, 19.65it/s]

 15%|█▌        | 15311/100629 [12:12<55:42, 25.53it/s]

 15%|█▌        | 15314/100629 [12:12<55:06, 25.81it/s]

 15%|█▌        | 15317/100629 [12:12<59:49, 23.77it/s]

 15%|█▌        | 15320/100629 [12:12<1:16:17, 18.63it/s]

 15%|█▌        | 15323/100629 [12:12<1:13:09, 19.43it/s]

 15%|█▌        | 15328/100629 [12:13<1:02:42, 22.67it/s]

 15%|█▌        | 15331/100629 [12:13<1:12:44, 19.54it/s]

 15%|█▌        | 15334/100629 [12:13<1:07:08, 21.17it/s]

 15%|█▌        | 15337/100629 [12:13<1:09:59, 20.31it/s]

 15%|█▌        | 15340/100629 [12:13<1:14:48, 19.00it/s]

 15%|█▌        | 15344/100629 [12:13<1:07:17, 21.12it/s]

 15%|█▌        | 15347/100629 [12:14<1:04:38, 21.99it/s]

 15%|█▌        | 15350/100629 [12:14<1:07:18, 21.12it/s]

 15%|█▌        | 15353/100629 [12:14<1:10:01, 20.30it/s]

 15%|█▌        | 15358/100629 [12:14<1:01:03, 23.27it/s]

 15%|█▌        | 15361/100629 [12:14<1:11:41, 19.82it/s]

 15%|█▌        | 15366/100629 [12:14<57:53, 24.55it/s]

 15%|█▌        | 15369/100629 [12:15<1:01:43, 23.02it/s]

 15%|█▌        | 15372/100629 [12:15<1:04:08, 22.15it/s]

 15%|█▌        | 15375/100629 [12:15<1:03:49, 22.27it/s]

 15%|█▌        | 15378/100629 [12:15<1:13:38, 19.29it/s]

 15%|█▌        | 15381/100629 [12:15<1:08:57, 20.60it/s]

 15%|█▌        | 15384/100629 [12:15<1:10:06, 20.27it/s]

 15%|█▌        | 15387/100629 [12:15<1:11:27, 19.88it/s]

 15%|█▌        | 15390/100629 [12:16<1:05:29, 21.69it/s]

 15%|█▌        | 15393/100629 [12:16<1:01:13, 23.20it/s]

 15%|█▌        | 15397/100629 [12:16<53:41, 26.46it/s]

 15%|█▌        | 15401/100629 [12:16<52:03, 27.29it/s]

 15%|█▌        | 15404/100629 [12:16<51:34, 27.54it/s]

 15%|█▌        | 15407/100629 [12:16<1:04:17, 22.09it/s]

 15%|█▌        | 15410/100629 [12:16<1:09:14, 20.51it/s]

 15%|█▌        | 15413/100629 [12:16<1:03:30, 22.37it/s]

 15%|█▌        | 15416/100629 [12:17<1:11:44, 19.80it/s]

 15%|█▌        | 15419/100629 [12:17<1:10:49, 20.05it/s]

 15%|█▌        | 15422/100629 [12:17<1:11:30, 19.86it/s]

 15%|█▌        | 15425/100629 [12:17<1:26:10, 16.48it/s]

 15%|█▌        | 15427/100629 [12:17<1:40:40, 14.11it/s]

 15%|█▌        | 15431/100629 [12:18<1:26:04, 16.50it/s]

 15%|█▌        | 15433/100629 [12:18<1:26:18, 16.45it/s]

 15%|█▌        | 15437/100629 [12:18<1:11:14, 19.93it/s]

 15%|█▌        | 15440/100629 [12:18<1:20:40, 17.60it/s]

 15%|█▌        | 15444/100629 [12:18<1:04:40, 21.95it/s]

 15%|█▌        | 15447/100629 [12:18<1:05:00, 21.84it/s]

 15%|█▌        | 15450/100629 [12:19<1:11:15, 19.92it/s]

 15%|█▌        | 15453/100629 [12:19<1:13:33, 19.30it/s]

 15%|█▌        | 15456/100629 [12:19<1:09:57, 20.29it/s]

 15%|█▌        | 15459/100629 [12:19<1:13:55, 19.20it/s]

 15%|█▌        | 15462/100629 [12:19<1:13:18, 19.36it/s]

 15%|█▌        | 15464/100629 [12:19<1:20:24, 17.65it/s]

 15%|█▌        | 15467/100629 [12:19<1:20:18, 17.67it/s]

 15%|█▌        | 15470/100629 [12:20<1:17:10, 18.39it/s]

 15%|█▌        | 15473/100629 [12:20<1:09:50, 20.32it/s]

 15%|█▌        | 15476/100629 [12:20<1:03:08, 22.48it/s]

 15%|█▌        | 15480/100629 [12:20<58:46, 24.14it/s]

 15%|█▌        | 15484/100629 [12:20<54:47, 25.90it/s]

 15%|█▌        | 15488/100629 [12:20<48:36, 29.20it/s]

 15%|█▌        | 15492/100629 [12:20<56:07, 25.28it/s]

 15%|█▌        | 15495/100629 [12:21<1:02:13, 22.80it/s]

 15%|█▌        | 15498/100629 [12:21<1:10:17, 20.19it/s]

 15%|█▌        | 15501/100629 [12:21<1:14:43, 18.99it/s]

 15%|█▌        | 15504/100629 [12:21<1:07:19, 21.07it/s]

 15%|█▌        | 15507/100629 [12:21<1:10:37, 20.09it/s]

 15%|█▌        | 15510/100629 [12:21<1:06:55, 21.20it/s]

 15%|█▌        | 15513/100629 [12:21<1:04:39, 21.94it/s]

 15%|█▌        | 15516/100629 [12:22<1:21:32, 17.40it/s]

 15%|█▌        | 15518/100629 [12:22<1:29:12, 15.90it/s]

 15%|█▌        | 15520/100629 [12:22<1:25:10, 16.65it/s]

 15%|█▌        | 15522/100629 [12:22<1:37:40, 14.52it/s]

 15%|█▌        | 15526/100629 [12:22<1:24:54, 16.71it/s]

 15%|█▌        | 15529/100629 [12:23<1:22:02, 17.29it/s]

 15%|█▌        | 15532/100629 [12:23<1:12:56, 19.45it/s]

 15%|█▌        | 15535/100629 [12:23<1:13:09, 19.39it/s]

 15%|█▌        | 15539/100629 [12:23<1:01:47, 22.95it/s]

 15%|█▌        | 15542/100629 [12:23<58:55, 24.07it/s]

 15%|█▌        | 15545/100629 [12:23<1:06:00, 21.48it/s]

 15%|█▌        | 15548/100629 [12:23<1:10:50, 20.01it/s]

 15%|█▌        | 15554/100629 [12:23<50:44, 27.94it/s]

 15%|█▌        | 15558/100629 [12:24<50:07, 28.29it/s]

 15%|█▌        | 15562/100629 [12:24<58:18, 24.31it/s]

 15%|█▌        | 15565/100629 [12:24<1:09:03, 20.53it/s]

 15%|█▌        | 15568/100629 [12:24<1:04:09, 22.10it/s]

 15%|█▌        | 15571/100629 [12:24<1:05:59, 21.48it/s]

 15%|█▌        | 15574/100629 [12:24<1:05:59, 21.48it/s]

 15%|█▌        | 15578/100629 [12:25<58:53, 24.07it/s]

 15%|█▌        | 15581/100629 [12:25<1:02:24, 22.71it/s]

 15%|█▌        | 15584/100629 [12:25<1:00:21, 23.48it/s]

 15%|█▌        | 15588/100629 [12:25<57:21, 24.71it/s]

 15%|█▌        | 15591/100629 [12:25<58:40, 24.15it/s]

 15%|█▌        | 15594/100629 [12:25<59:23, 23.86it/s]

 15%|█▌        | 15597/100629 [12:26<1:13:29, 19.28it/s]

 16%|█▌        | 15600/100629 [12:26<1:15:05, 18.87it/s]

 16%|█▌        | 15603/100629 [12:26<1:07:43, 20.93it/s]

 16%|█▌        | 15606/100629 [12:26<1:11:12, 19.90it/s]

 16%|█▌        | 15609/100629 [12:26<1:08:59, 20.54it/s]

 16%|█▌        | 15612/100629 [12:26<1:08:37, 20.65it/s]

 16%|█▌        | 15615/100629 [12:26<1:10:42, 20.04it/s]

 16%|█▌        | 15618/100629 [12:27<1:08:10, 20.78it/s]

 16%|█▌        | 15621/100629 [12:27<1:13:43, 19.22it/s]

 16%|█▌        | 15623/100629 [12:27<1:20:47, 17.54it/s]

 16%|█▌        | 15625/100629 [12:27<1:24:14, 16.82it/s]

 16%|█▌        | 15627/100629 [12:27<1:26:28, 16.38it/s]

 16%|█▌        | 15629/100629 [12:27<1:22:53, 17.09it/s]

 16%|█▌        | 15631/100629 [12:27<1:30:00, 15.74it/s]

 16%|█▌        | 15634/100629 [12:28<1:20:38, 17.57it/s]

 16%|█▌        | 15638/100629 [12:28<1:08:50, 20.58it/s]

 16%|█▌        | 15642/100629 [12:28<59:11, 23.93it/s]

 16%|█▌        | 15645/100629 [12:28<1:04:29, 21.96it/s]

 16%|█▌        | 15648/100629 [12:28<1:01:02, 23.20it/s]

 16%|█▌        | 15651/100629 [12:28<57:20, 24.70it/s]

 16%|█▌        | 15655/100629 [12:28<50:57, 27.79it/s]

 16%|█▌        | 15659/100629 [12:28<46:47, 30.27it/s]

 16%|█▌        | 15663/100629 [12:29<47:01, 30.12it/s]

 16%|█▌        | 15667/100629 [12:29<50:29, 28.05it/s]

 16%|█▌        | 15672/100629 [12:29<44:16, 31.98it/s]

 16%|█▌        | 15676/100629 [12:29<46:58, 30.14it/s]

 16%|█▌        | 15680/100629 [12:29<57:40, 24.55it/s]

 16%|█▌        | 15683/100629 [12:29<1:00:22, 23.45it/s]

 16%|█▌        | 15686/100629 [12:29<58:34, 24.17it/s]

 16%|█▌        | 15690/100629 [12:30<53:29, 26.47it/s]

 16%|█▌        | 15694/100629 [12:30<50:38, 27.96it/s]

 16%|█▌        | 15697/100629 [12:30<54:52, 25.80it/s]

 16%|█▌        | 15700/100629 [12:30<55:39, 25.43it/s]

 16%|█▌        | 15704/100629 [12:30<52:05, 27.17it/s]

 16%|█▌        | 15707/100629 [12:30<56:24, 25.09it/s]

 16%|█▌        | 15710/100629 [12:30<54:30, 25.97it/s]

 16%|█▌        | 15714/100629 [12:30<55:16, 25.60it/s]

 16%|█▌        | 15717/100629 [12:31<57:31, 24.60it/s]

 16%|█▌        | 15720/100629 [12:31<1:07:59, 20.81it/s]

 16%|█▌        | 15723/100629 [12:31<1:13:01, 19.38it/s]

 16%|█▌        | 15726/100629 [12:31<1:10:24, 20.10it/s]

 16%|█▌        | 15729/100629 [12:31<1:09:40, 20.31it/s]

 16%|█▌        | 15732/100629 [12:32<1:29:57, 15.73it/s]

 16%|█▌        | 15734/100629 [12:32<1:27:42, 16.13it/s]

 16%|█▌        | 15737/100629 [12:32<1:27:04, 16.25it/s]

 16%|█▌        | 15741/100629 [12:32<1:14:31, 18.99it/s]

 16%|█▌        | 15744/100629 [12:32<1:22:47, 17.09it/s]

 16%|█▌        | 15746/100629 [12:32<1:25:49, 16.48it/s]

 16%|█▌        | 15748/100629 [12:32<1:23:51, 16.87it/s]

 16%|█▌        | 15751/100629 [12:33<1:14:05, 19.09it/s]

 16%|█▌        | 15753/100629 [12:33<1:13:32, 19.24it/s]

 16%|█▌        | 15757/100629 [12:33<1:02:20, 22.69it/s]

 16%|█▌        | 15760/100629 [12:33<59:51, 23.63it/s]

 16%|█▌        | 15765/100629 [12:33<55:54, 25.30it/s]

 16%|█▌        | 15768/100629 [12:33<1:09:10, 20.44it/s]

 16%|█▌        | 15771/100629 [12:34<1:13:26, 19.26it/s]

 16%|█▌        | 15775/100629 [12:34<1:11:24, 19.80it/s]

 16%|█▌        | 15778/100629 [12:34<1:16:38, 18.45it/s]

 16%|█▌        | 15781/100629 [12:34<1:15:09, 18.82it/s]

 16%|█▌        | 15786/100629 [12:34<1:00:58, 23.19it/s]

 16%|█▌        | 15789/100629 [12:34<1:08:03, 20.77it/s]

 16%|█▌        | 15792/100629 [12:35<1:04:09, 22.04it/s]

 16%|█▌        | 15796/100629 [12:35<59:18, 23.84it/s]

 16%|█▌        | 15799/100629 [12:35<1:00:34, 23.34it/s]

 16%|█▌        | 15802/100629 [12:35<58:31, 24.15it/s]

 16%|█▌        | 15805/100629 [12:35<1:04:55, 21.78it/s]

 16%|█▌        | 15808/100629 [12:35<1:07:06, 21.07it/s]

 16%|█▌        | 15811/100629 [12:35<1:18:42, 17.96it/s]

 16%|█▌        | 15813/100629 [12:36<1:20:43, 17.51it/s]

 16%|█▌        | 15815/100629 [12:36<1:20:49, 17.49it/s]

 16%|█▌        | 15817/100629 [12:36<1:20:21, 17.59it/s]

 16%|█▌        | 15821/100629 [12:36<1:11:10, 19.86it/s]

 16%|█▌        | 15824/100629 [12:36<1:07:45, 20.86it/s]

 16%|█▌        | 15827/100629 [12:36<1:04:00, 22.08it/s]

 16%|█▌        | 15830/100629 [12:36<1:00:20, 23.42it/s]

 16%|█▌        | 15833/100629 [12:36<1:00:26, 23.38it/s]

 16%|█▌        | 15836/100629 [12:37<1:10:54, 19.93it/s]

 16%|█▌        | 15839/100629 [12:37<1:20:10, 17.63it/s]

 16%|█▌        | 15841/100629 [12:37<1:29:54, 15.72it/s]

 16%|█▌        | 15844/100629 [12:37<1:26:30, 16.34it/s]

 16%|█▌        | 15846/100629 [12:37<1:29:47, 15.74it/s]

 16%|█▌        | 15848/100629 [12:37<1:25:49, 16.46it/s]

 16%|█▌        | 15852/100629 [12:38<1:05:06, 21.70it/s]

 16%|█▌        | 15855/100629 [12:38<1:00:49, 23.23it/s]

 16%|█▌        | 15858/100629 [12:38<1:08:19, 20.68it/s]

 16%|█▌        | 15861/100629 [12:38<1:02:34, 22.58it/s]

 16%|█▌        | 15864/100629 [12:38<1:06:57, 21.10it/s]

 16%|█▌        | 15868/100629 [12:38<1:00:39, 23.29it/s]

 16%|█▌        | 15871/100629 [12:38<57:12, 24.69it/s]

 16%|█▌        | 15874/100629 [12:38<56:36, 24.95it/s]

 16%|█▌        | 15877/100629 [12:39<54:25, 25.96it/s]

 16%|█▌        | 15881/100629 [12:39<51:39, 27.34it/s]

 16%|█▌        | 15884/100629 [12:39<1:07:31, 20.92it/s]

 16%|█▌        | 15887/100629 [12:39<1:14:27, 18.97it/s]

 16%|█▌        | 15890/100629 [12:39<1:20:57, 17.44it/s]

 16%|█▌        | 15893/100629 [12:39<1:16:32, 18.45it/s]

 16%|█▌        | 15895/100629 [12:40<1:17:24, 18.24it/s]

 16%|█▌        | 15898/100629 [12:40<1:15:19, 18.75it/s]

 16%|█▌        | 15900/100629 [12:40<1:15:21, 18.74it/s]

 16%|█▌        | 15904/100629 [12:40<1:01:28, 22.97it/s]

 16%|█▌        | 15908/100629 [12:40<57:53, 24.39it/s]

 16%|█▌        | 15911/100629 [12:40<59:00, 23.93it/s]

 16%|█▌        | 15914/100629 [12:40<57:50, 24.41it/s]

 16%|█▌        | 15917/100629 [12:40<54:48, 25.76it/s]

 16%|█▌        | 15921/100629 [12:41<49:59, 28.24it/s]

 16%|█▌        | 15924/100629 [12:41<52:28, 26.90it/s]

 16%|█▌        | 15928/100629 [12:41<49:55, 28.28it/s]

 16%|█▌        | 15931/100629 [12:41<1:02:47, 22.48it/s]

 16%|█▌        | 15934/100629 [12:41<1:02:45, 22.49it/s]

 16%|█▌        | 15937/100629 [12:41<1:01:40, 22.89it/s]

 16%|█▌        | 15940/100629 [12:41<58:27, 24.15it/s]

 16%|█▌        | 15943/100629 [12:42<1:01:20, 23.01it/s]

 16%|█▌        | 15946/100629 [12:42<1:03:12, 22.33it/s]

 16%|█▌        | 15949/100629 [12:42<1:02:38, 22.53it/s]

 16%|█▌        | 15952/100629 [12:42<59:10, 23.85it/s]

 16%|█▌        | 15955/100629 [12:42<1:16:29, 18.45it/s]

 16%|█▌        | 15958/100629 [12:42<1:13:17, 19.25it/s]

 16%|█▌        | 15961/100629 [12:42<1:13:51, 19.10it/s]

 16%|█▌        | 15964/100629 [12:43<1:21:19, 17.35it/s]

 16%|█▌        | 15966/100629 [12:43<1:29:13, 15.81it/s]

 16%|█▌        | 15971/100629 [12:43<1:15:55, 18.58it/s]

 16%|█▌        | 15973/100629 [12:43<1:15:48, 18.61it/s]

 16%|█▌        | 15975/100629 [12:43<1:16:55, 18.34it/s]

 16%|█▌        | 15978/100629 [12:43<1:13:52, 19.10it/s]

 16%|█▌        | 15981/100629 [12:44<1:07:09, 21.01it/s]

 16%|█▌        | 15984/100629 [12:44<1:17:24, 18.22it/s]

 16%|█▌        | 15986/100629 [12:44<1:47:39, 13.10it/s]

 16%|█▌        | 15989/100629 [12:44<1:29:23, 15.78it/s]

 16%|█▌        | 15991/100629 [12:44<1:25:13, 16.55it/s]

 16%|█▌        | 15995/100629 [12:44<1:07:41, 20.84it/s]

 16%|█▌        | 15998/100629 [12:45<1:18:45, 17.91it/s]

 16%|█▌        | 16001/100629 [12:45<1:18:26, 17.98it/s]

 16%|█▌        | 16005/100629 [12:45<1:05:48, 21.43it/s]

 16%|█▌        | 16008/100629 [12:45<1:23:05, 16.98it/s]

 16%|█▌        | 16012/100629 [12:45<1:08:31, 20.58it/s]

 16%|█▌        | 16016/100629 [12:45<1:00:50, 23.18it/s]

 16%|█▌        | 16020/100629 [12:46<54:37, 25.82it/s]

 16%|█▌        | 16023/100629 [12:46<56:33, 24.93it/s]

 16%|█▌        | 16026/100629 [12:46<1:07:17, 20.96it/s]

 16%|█▌        | 16029/100629 [12:46<1:15:52, 18.58it/s]

 16%|█▌        | 16032/100629 [12:46<1:08:06, 20.70it/s]

 16%|█▌        | 16036/100629 [12:46<58:05, 24.27it/s]

 16%|█▌        | 16041/100629 [12:46<50:36, 27.86it/s]

 16%|█▌        | 16044/100629 [12:47<55:31, 25.39it/s]

 16%|█▌        | 16047/100629 [12:47<1:04:40, 21.80it/s]

 16%|█▌        | 16050/100629 [12:47<1:03:40, 22.14it/s]

 16%|█▌        | 16056/100629 [12:47<1:02:05, 22.70it/s]

 16%|█▌        | 16059/100629 [12:47<1:00:40, 23.23it/s]

 16%|█▌        | 16062/100629 [12:47<1:08:18, 20.64it/s]

 16%|█▌        | 16065/100629 [12:48<1:08:58, 20.43it/s]

 16%|█▌        | 16068/100629 [12:48<1:03:42, 22.12it/s]

 16%|█▌        | 16071/100629 [12:48<1:03:54, 22.05it/s]

 16%|█▌        | 16075/100629 [12:48<1:02:30, 22.54it/s]

 16%|█▌        | 16078/100629 [12:48<1:04:19, 21.90it/s]

 16%|█▌        | 16081/100629 [12:48<1:05:58, 21.36it/s]

 16%|█▌        | 16084/100629 [12:49<1:09:44, 20.20it/s]

 16%|█▌        | 16087/100629 [12:49<1:23:37, 16.85it/s]

 16%|█▌        | 16090/100629 [12:49<1:14:33, 18.90it/s]

 16%|█▌        | 16093/100629 [12:49<1:19:19, 17.76it/s]

 16%|█▌        | 16098/100629 [12:49<1:04:15, 21.93it/s]

 16%|█▌        | 16101/100629 [12:49<1:05:25, 21.53it/s]

 16%|█▌        | 16104/100629 [12:49<1:01:15, 23.00it/s]

 16%|█▌        | 16107/100629 [12:50<1:00:20, 23.34it/s]

 16%|█▌        | 16110/100629 [12:50<1:08:06, 20.68it/s]

 16%|█▌        | 16114/100629 [12:50<59:34, 23.65it/s]

 16%|█▌        | 16118/100629 [12:50<55:00, 25.61it/s]

 16%|█▌        | 16121/100629 [12:50<58:13, 24.19it/s]

 16%|█▌        | 16124/100629 [12:50<1:12:53, 19.32it/s]

 16%|█▌        | 16127/100629 [12:51<1:09:40, 20.21it/s]

 16%|█▌        | 16131/100629 [12:51<1:09:19, 20.31it/s]

 16%|█▌        | 16134/100629 [12:51<1:10:36, 19.94it/s]

 16%|█▌        | 16137/100629 [12:51<1:06:50, 21.07it/s]

 16%|█▌        | 16140/100629 [12:51<1:13:23, 19.18it/s]

 16%|█▌        | 16143/100629 [12:51<1:07:26, 20.88it/s]

 16%|█▌        | 16146/100629 [12:52<1:21:01, 17.38it/s]

 16%|█▌        | 16148/100629 [12:52<1:19:14, 17.77it/s]

 16%|█▌        | 16150/100629 [12:52<1:20:09, 17.56it/s]

 16%|█▌        | 16152/100629 [12:52<1:29:22, 15.75it/s]

 16%|█▌        | 16156/100629 [12:52<1:15:05, 18.75it/s]

 16%|█▌        | 16161/100629 [12:52<55:59, 25.14it/s]

 16%|█▌        | 16167/100629 [12:52<45:46, 30.76it/s]

 16%|█▌        | 16171/100629 [12:52<46:00, 30.59it/s]

 16%|█▌        | 16175/100629 [12:53<49:53, 28.21it/s]

 16%|█▌        | 16179/100629 [12:53<45:59, 30.61it/s]

 16%|█▌        | 16183/100629 [12:53<49:45, 28.28it/s]

 16%|█▌        | 16186/100629 [12:53<52:11, 26.96it/s]

 16%|█▌        | 16189/100629 [12:53<52:42, 26.70it/s]

 16%|█▌        | 16194/100629 [12:53<49:45, 28.28it/s]

 16%|█▌        | 16197/100629 [12:53<49:55, 28.19it/s]

 16%|█▌        | 16202/100629 [12:54<49:09, 28.62it/s]

 16%|█▌        | 16205/100629 [12:54<1:01:33, 22.86it/s]

 16%|█▌        | 16208/100629 [12:54<1:00:13, 23.36it/s]

 16%|█▌        | 16211/100629 [12:54<57:01, 24.68it/s]

 16%|█▌        | 16214/100629 [12:54<1:04:00, 21.98it/s]

 16%|█▌        | 16218/100629 [12:54<55:18, 25.44it/s]

 16%|█▌        | 16222/100629 [12:54<48:42, 28.89it/s]

 16%|█▌        | 16226/100629 [12:55<1:08:14, 20.62it/s]

 16%|█▌        | 16229/100629 [12:55<1:07:03, 20.98it/s]

 16%|█▌        | 16232/100629 [12:55<1:02:34, 22.48it/s]

 16%|█▌        | 16236/100629 [12:55<56:42, 24.80it/s]

 16%|█▌        | 16239/100629 [12:55<59:21, 23.69it/s]

 16%|█▌        | 16242/100629 [12:55<1:00:36, 23.21it/s]

 16%|█▌        | 16247/100629 [12:56<50:57, 27.60it/s]

 16%|█▌        | 16250/100629 [12:56<56:18, 24.97it/s]

 16%|█▌        | 16253/100629 [12:56<1:03:46, 22.05it/s]

 16%|█▌        | 16256/100629 [12:56<1:20:37, 17.44it/s]

 16%|█▌        | 16258/100629 [12:56<1:22:48, 16.98it/s]

 16%|█▌        | 16261/100629 [12:56<1:15:59, 18.51it/s]

 16%|█▌        | 16263/100629 [12:57<1:31:24, 15.38it/s]

 16%|█▌        | 16265/100629 [12:57<1:30:00, 15.62it/s]

 16%|█▌        | 16268/100629 [12:57<1:43:55, 13.53it/s]

 16%|█▌        | 16272/100629 [12:57<1:21:05, 17.34it/s]

 16%|█▌        | 16274/100629 [12:57<1:22:45, 16.99it/s]

 16%|█▌        | 16276/100629 [12:57<1:22:38, 17.01it/s]

 16%|█▌        | 16278/100629 [12:58<1:25:55, 16.36it/s]

 16%|█▌        | 16281/100629 [12:58<1:13:20, 19.17it/s]

 16%|█▌        | 16284/100629 [12:58<1:10:01, 20.08it/s]

 16%|█▌        | 16287/100629 [12:58<1:20:43, 17.41it/s]

 16%|█▌        | 16289/100629 [12:58<1:22:23, 17.06it/s]

 16%|█▌        | 16293/100629 [12:58<1:05:35, 21.43it/s]

 16%|█▌        | 16296/100629 [12:58<1:02:44, 22.40it/s]

 16%|█▌        | 16300/100629 [12:58<57:59, 24.24it/s]

 16%|█▌        | 16303/100629 [12:59<55:53, 25.14it/s]

 16%|█▌        | 16306/100629 [12:59<1:08:11, 20.61it/s]

 16%|█▌        | 16309/100629 [12:59<1:03:31, 22.12it/s]

 16%|█▌        | 16312/100629 [12:59<1:16:16, 18.42it/s]

 16%|█▌        | 16315/100629 [12:59<1:37:16, 14.45it/s]

 16%|█▌        | 16317/100629 [13:00<1:34:01, 14.95it/s]

 16%|█▌        | 16320/100629 [13:00<1:22:23, 17.05it/s]

 16%|█▌        | 16322/100629 [13:00<1:33:25, 15.04it/s]

 16%|█▌        | 16326/100629 [13:00<1:11:45, 19.58it/s]

 16%|█▌        | 16329/100629 [13:00<1:09:31, 20.21it/s]

 16%|█▌        | 16332/100629 [13:00<1:03:31, 22.11it/s]

 16%|█▌        | 16335/100629 [13:00<1:04:56, 21.63it/s]

 16%|█▌        | 16338/100629 [13:01<1:13:29, 19.12it/s]

 16%|█▌        | 16341/100629 [13:01<1:17:54, 18.03it/s]

 16%|█▌        | 16343/100629 [13:01<1:17:16, 18.18it/s]

 16%|█▌        | 16345/100629 [13:01<1:18:36, 17.87it/s]

 16%|█▌        | 16347/100629 [13:01<1:29:35, 15.68it/s]

 16%|█▌        | 16349/100629 [13:01<1:24:45, 16.57it/s]

 16%|█▌        | 16352/100629 [13:01<1:25:28, 16.43it/s]

 16%|█▋        | 16355/100629 [13:02<1:19:06, 17.75it/s]

 16%|█▋        | 16358/100629 [13:02<1:10:20, 19.97it/s]

 16%|█▋        | 16361/100629 [13:02<1:12:31, 19.36it/s]

 16%|█▋        | 16365/100629 [13:02<1:03:25, 22.14it/s]

 16%|█▋        | 16368/100629 [13:02<1:09:25, 20.23it/s]

 16%|█▋        | 16371/100629 [13:02<1:03:10, 22.23it/s]

 16%|█▋        | 16374/100629 [13:02<1:00:05, 23.37it/s]

 16%|█▋        | 16377/100629 [13:03<1:02:13, 22.56it/s]

 16%|█▋        | 16380/100629 [13:03<1:08:31, 20.49it/s]

 16%|█▋        | 16384/100629 [13:03<58:29, 24.00it/s]

 16%|█▋        | 16387/100629 [13:03<55:26, 25.33it/s]

 16%|█▋        | 16391/100629 [13:03<56:52, 24.69it/s]

 16%|█▋        | 16394/100629 [13:03<56:05, 25.03it/s]

 16%|█▋        | 16397/100629 [13:03<1:01:51, 22.70it/s]

 16%|█▋        | 16400/100629 [13:04<1:02:22, 22.50it/s]

 16%|█▋        | 16403/100629 [13:04<1:14:43, 18.79it/s]

 16%|█▋        | 16406/100629 [13:04<1:12:09, 19.45it/s]

 16%|█▋        | 16409/100629 [13:04<1:13:54, 18.99it/s]

 16%|█▋        | 16411/100629 [13:04<1:13:06, 19.20it/s]

 16%|█▋        | 16414/100629 [13:04<1:10:10, 20.00it/s]

 16%|█▋        | 16417/100629 [13:04<1:12:46, 19.28it/s]

 16%|█▋        | 16419/100629 [13:05<1:21:19, 17.26it/s]

 16%|█▋        | 16422/100629 [13:05<1:24:11, 16.67it/s]

 16%|█▋        | 16424/100629 [13:05<1:20:54, 17.34it/s]

 16%|█▋        | 16427/100629 [13:05<1:10:43, 19.84it/s]

 16%|█▋        | 16430/100629 [13:05<1:11:33, 19.61it/s]

 16%|█▋        | 16433/100629 [13:05<1:10:24, 19.93it/s]

 16%|█▋        | 16436/100629 [13:06<1:17:07, 18.19it/s]

 16%|█▋        | 16438/100629 [13:06<1:24:24, 16.62it/s]

 16%|█▋        | 16440/100629 [13:06<1:28:59, 15.77it/s]

 16%|█▋        | 16444/100629 [13:06<1:11:17, 19.68it/s]

 16%|█▋        | 16447/100629 [13:06<1:14:34, 18.82it/s]

 16%|█▋        | 16450/100629 [13:06<1:15:23, 18.61it/s]

 16%|█▋        | 16452/100629 [13:06<1:22:18, 17.04it/s]

 16%|█▋        | 16454/100629 [13:07<1:21:33, 17.20it/s]

 16%|█▋        | 16456/100629 [13:07<1:19:06, 17.73it/s]

 16%|█▋        | 16461/100629 [13:07<1:04:18, 21.81it/s]

 16%|█▋        | 16465/100629 [13:07<1:05:40, 21.36it/s]

 16%|█▋        | 16468/100629 [13:07<1:05:15, 21.49it/s]

 16%|█▋        | 16471/100629 [13:07<1:00:11, 23.30it/s]

 16%|█▋        | 16474/100629 [13:07<59:58, 23.39it/s]

 16%|█▋        | 16477/100629 [13:08<59:27, 23.59it/s]

 16%|█▋        | 16480/100629 [13:08<1:03:36, 22.05it/s]

 16%|█▋        | 16483/100629 [13:08<1:07:57, 20.63it/s]

 16%|█▋        | 16486/100629 [13:08<1:04:31, 21.73it/s]

 16%|█▋        | 16489/100629 [13:08<1:05:35, 21.38it/s]

 16%|█▋        | 16492/100629 [13:08<1:08:14, 20.55it/s]

 16%|█▋        | 16495/100629 [13:08<1:06:50, 20.98it/s]

 16%|█▋        | 16498/100629 [13:09<1:05:20, 21.46it/s]

 16%|█▋        | 16501/100629 [13:09<1:04:32, 21.73it/s]

 16%|█▋        | 16504/100629 [13:09<1:07:57, 20.63it/s]

 16%|█▋        | 16508/100629 [13:09<1:04:31, 21.73it/s]

 16%|█▋        | 16511/100629 [13:09<1:06:03, 21.22it/s]

 16%|█▋        | 16514/100629 [13:09<1:04:35, 21.71it/s]

 16%|█▋        | 16517/100629 [13:09<1:03:13, 22.17it/s]

 16%|█▋        | 16521/100629 [13:10<54:17, 25.82it/s]

 16%|█▋        | 16524/100629 [13:10<59:34, 23.53it/s]

 16%|█▋        | 16527/100629 [13:10<1:01:06, 22.94it/s]

 16%|█▋        | 16530/100629 [13:10<1:09:34, 20.14it/s]

 16%|█▋        | 16533/100629 [13:10<1:03:06, 22.21it/s]

 16%|█▋        | 16537/100629 [13:10<1:04:39, 21.68it/s]

 16%|█▋        | 16541/100629 [13:10<1:01:22, 22.83it/s]

 16%|█▋        | 16544/100629 [13:11<59:48, 23.43it/s]

 16%|█▋        | 16547/100629 [13:11<1:15:04, 18.67it/s]

 16%|█▋        | 16550/100629 [13:11<1:20:53, 17.33it/s]

 16%|█▋        | 16552/100629 [13:11<1:25:44, 16.34it/s]

 16%|█▋        | 16554/100629 [13:11<1:32:53, 15.08it/s]

 16%|█▋        | 16558/100629 [13:11<1:11:34, 19.58it/s]

 16%|█▋        | 16561/100629 [13:12<1:21:48, 17.13it/s]

 16%|█▋        | 16564/100629 [13:12<1:13:19, 19.11it/s]

 16%|█▋        | 16567/100629 [13:12<1:18:02, 17.95it/s]

 16%|█▋        | 16569/100629 [13:12<1:20:10, 17.47it/s]

 16%|█▋        | 16573/100629 [13:12<1:06:20, 21.12it/s]

 16%|█▋        | 16576/100629 [13:12<1:10:26, 19.89it/s]

 16%|█▋        | 16580/100629 [13:13<1:00:04, 23.32it/s]

 16%|█▋        | 16584/100629 [13:13<52:45, 26.55it/s]

 16%|█▋        | 16588/100629 [13:13<48:41, 28.77it/s]

 16%|█▋        | 16592/100629 [13:13<1:08:06, 20.57it/s]

 16%|█▋        | 16595/100629 [13:13<1:10:03, 19.99it/s]

 16%|█▋        | 16599/100629 [13:13<59:48, 23.42it/s]

 16%|█▋        | 16603/100629 [13:13<56:13, 24.91it/s]

 17%|█▋        | 16606/100629 [13:14<1:03:02, 22.21it/s]

 17%|█▋        | 16612/100629 [13:14<49:56, 28.04it/s]

 17%|█▋        | 16616/100629 [13:14<56:24, 24.82it/s]

 17%|█▋        | 16619/100629 [13:14<1:01:56, 22.60it/s]

 17%|█▋        | 16623/100629 [13:14<55:46, 25.11it/s]

 17%|█▋        | 16626/100629 [13:14<54:08, 25.86it/s]

 17%|█▋        | 16629/100629 [13:15<57:16, 24.44it/s]

 17%|█▋        | 16632/100629 [13:15<55:35, 25.18it/s]

 17%|█▋        | 16635/100629 [13:15<1:07:33, 20.72it/s]

 17%|█▋        | 16639/100629 [13:15<1:03:33, 22.03it/s]

 17%|█▋        | 16642/100629 [13:15<1:06:00, 21.21it/s]

 17%|█▋        | 16645/100629 [13:15<1:08:58, 20.29it/s]

 17%|█▋        | 16649/100629 [13:15<58:06, 24.09it/s]

 17%|█▋        | 16652/100629 [13:16<57:41, 24.26it/s]

 17%|█▋        | 16655/100629 [13:16<1:08:08, 20.54it/s]

 17%|█▋        | 16659/100629 [13:16<58:53, 23.76it/s]

 17%|█▋        | 16662/100629 [13:16<1:13:27, 19.05it/s]

 17%|█▋        | 16665/100629 [13:16<1:32:00, 15.21it/s]

 17%|█▋        | 16668/100629 [13:17<1:19:37, 17.58it/s]

 17%|█▋        | 16671/100629 [13:17<1:12:29, 19.30it/s]

 17%|█▋        | 16674/100629 [13:17<1:13:46, 18.97it/s]

 17%|█▋        | 16678/100629 [13:17<1:10:20, 19.89it/s]

 17%|█▋        | 16681/100629 [13:17<1:06:40, 20.98it/s]

 17%|█▋        | 16684/100629 [13:17<1:09:24, 20.16it/s]

 17%|█▋        | 16688/100629 [13:17<1:00:34, 23.09it/s]

 17%|█▋        | 16692/100629 [13:18<56:50, 24.61it/s]

 17%|█▋        | 16695/100629 [13:18<55:48, 25.07it/s]

 17%|█▋        | 16698/100629 [13:18<55:55, 25.01it/s]

 17%|█▋        | 16701/100629 [13:18<1:15:57, 18.42it/s]

 17%|█▋        | 16704/100629 [13:18<1:10:45, 19.77it/s]

 17%|█▋        | 16707/100629 [13:18<1:06:21, 21.08it/s]

 17%|█▋        | 16710/100629 [13:18<1:08:24, 20.45it/s]

 17%|█▋        | 16713/100629 [13:19<1:09:11, 20.21it/s]

 17%|█▋        | 16717/100629 [13:19<1:03:00, 22.19it/s]

 17%|█▋        | 16720/100629 [13:19<1:03:32, 22.01it/s]

 17%|█▋        | 16723/100629 [13:19<1:05:52, 21.23it/s]

 17%|█▋        | 16726/100629 [13:19<1:08:37, 20.38it/s]

 17%|█▋        | 16729/100629 [13:19<1:10:32, 19.82it/s]

 17%|█▋        | 16732/100629 [13:20<1:23:15, 16.79it/s]

 17%|█▋        | 16735/100629 [13:20<1:21:23, 17.18it/s]

 17%|█▋        | 16738/100629 [13:20<1:16:42, 18.23it/s]

 17%|█▋        | 16740/100629 [13:20<1:22:29, 16.95it/s]

 17%|█▋        | 16742/100629 [13:20<1:19:51, 17.51it/s]

 17%|█▋        | 16744/100629 [13:20<1:29:29, 15.62it/s]

 17%|█▋        | 16746/100629 [13:20<1:26:38, 16.14it/s]

 17%|█▋        | 16748/100629 [13:21<1:29:12, 15.67it/s]

 17%|█▋        | 16752/100629 [13:21<1:14:48, 18.69it/s]

 17%|█▋        | 16754/100629 [13:21<1:18:19, 17.85it/s]

 17%|█▋        | 16759/100629 [13:21<1:04:33, 21.65it/s]

 17%|█▋        | 16762/100629 [13:21<1:01:08, 22.86it/s]

 17%|█▋        | 16765/100629 [13:21<1:09:38, 20.07it/s]

 17%|█▋        | 16769/100629 [13:21<59:49, 23.36it/s]

 17%|█▋        | 16773/100629 [13:22<52:33, 26.59it/s]

 17%|█▋        | 16776/100629 [13:22<54:10, 25.80it/s]

 17%|█▋        | 16779/100629 [13:22<1:12:45, 19.21it/s]

 17%|█▋        | 16782/100629 [13:22<1:15:19, 18.55it/s]

 17%|█▋        | 16786/100629 [13:22<1:03:50, 21.89it/s]

 17%|█▋        | 16791/100629 [13:22<52:12, 26.77it/s]

 17%|█▋        | 16795/100629 [13:23<49:32, 28.20it/s]

 17%|█▋        | 16799/100629 [13:23<52:59, 26.36it/s]

 17%|█▋        | 16802/100629 [13:23<59:46, 23.37it/s]

 17%|█▋        | 16806/100629 [13:23<55:34, 25.14it/s]

 17%|█▋        | 16809/100629 [13:23<54:31, 25.62it/s]

 17%|█▋        | 16812/100629 [13:23<56:58, 24.52it/s]

 17%|█▋        | 16816/100629 [13:23<54:54, 25.44it/s]

 17%|█▋        | 16819/100629 [13:24<1:04:29, 21.66it/s]

 17%|█▋        | 16822/100629 [13:24<1:04:36, 21.62it/s]

 17%|█▋        | 16825/100629 [13:24<1:13:28, 19.01it/s]

 17%|█▋        | 16828/100629 [13:24<1:19:42, 17.52it/s]

 17%|█▋        | 16830/100629 [13:24<1:23:56, 16.64it/s]

 17%|█▋        | 16832/100629 [13:24<1:22:11, 16.99it/s]

 17%|█▋        | 16835/100629 [13:25<1:14:10, 18.83it/s]

 17%|█▋        | 16839/100629 [13:25<1:02:42, 22.27it/s]

 17%|█▋        | 16843/100629 [13:25<54:42, 25.53it/s]

 17%|█▋        | 16846/100629 [13:25<54:31, 25.61it/s]

 17%|█▋        | 16849/100629 [13:25<55:59, 24.94it/s]

 17%|█▋        | 16852/100629 [13:25<1:06:45, 20.92it/s]

 17%|█▋        | 16855/100629 [13:25<1:13:24, 19.02it/s]

 17%|█▋        | 16858/100629 [13:26<1:07:38, 20.64it/s]

 17%|█▋        | 16862/100629 [13:26<59:21, 23.52it/s]

 17%|█▋        | 16865/100629 [13:26<1:02:47, 22.23it/s]

 17%|█▋        | 16868/100629 [13:26<59:34, 23.43it/s]

 17%|█▋        | 16871/100629 [13:26<1:06:27, 21.01it/s]

 17%|█▋        | 16874/100629 [13:26<1:04:51, 21.53it/s]

 17%|█▋        | 16877/100629 [13:26<1:03:29, 21.98it/s]

 17%|█▋        | 16882/100629 [13:26<50:25, 27.68it/s]

 17%|█▋        | 16885/100629 [13:27<55:07, 25.32it/s]

 17%|█▋        | 16888/100629 [13:27<53:43, 25.98it/s]

 17%|█▋        | 16891/100629 [13:27<57:23, 24.32it/s]

 17%|█▋        | 16894/100629 [13:27<1:01:47, 22.58it/s]

 17%|█▋        | 16897/100629 [13:27<1:07:44, 20.60it/s]

 17%|█▋        | 16900/100629 [13:27<1:07:02, 20.81it/s]

 17%|█▋        | 16903/100629 [13:27<1:03:29, 21.98it/s]

 17%|█▋        | 16906/100629 [13:28<1:03:32, 21.96it/s]

 17%|█▋        | 16909/100629 [13:28<1:21:10, 17.19it/s]

 17%|█▋        | 16911/100629 [13:28<1:24:58, 16.42it/s]

 17%|█▋        | 16915/100629 [13:28<1:08:26, 20.39it/s]

 17%|█▋        | 16918/100629 [13:28<1:04:56, 21.49it/s]

 17%|█▋        | 16921/100629 [13:28<1:00:10, 23.18it/s]

 17%|█▋        | 16924/100629 [13:28<1:00:13, 23.16it/s]

 17%|█▋        | 16927/100629 [13:29<1:24:29, 16.51it/s]

 17%|█▋        | 16930/100629 [13:29<1:23:55, 16.62it/s]

 17%|█▋        | 16932/100629 [13:29<1:21:26, 17.13it/s]

 17%|█▋        | 16935/100629 [13:29<1:15:55, 18.37it/s]

 17%|█▋        | 16940/100629 [13:29<1:00:18, 23.13it/s]

 17%|█▋        | 16943/100629 [13:29<1:02:12, 22.42it/s]

 17%|█▋        | 16946/100629 [13:30<1:07:19, 20.72it/s]

 17%|█▋        | 16949/100629 [13:30<1:08:29, 20.36it/s]

 17%|█▋        | 16952/100629 [13:30<1:03:05, 22.11it/s]

 17%|█▋        | 16955/100629 [13:30<1:06:55, 20.84it/s]

 17%|█▋        | 16958/100629 [13:30<1:04:10, 21.73it/s]

 17%|█▋        | 16961/100629 [13:30<1:01:01, 22.85it/s]

 17%|█▋        | 16965/100629 [13:31<1:02:34, 22.28it/s]

 17%|█▋        | 16968/100629 [13:31<1:02:01, 22.48it/s]

 17%|█▋        | 16971/100629 [13:31<1:00:08, 23.19it/s]

 17%|█▋        | 16976/100629 [13:31<50:48, 27.44it/s]

 17%|█▋        | 16979/100629 [13:31<52:08, 26.74it/s]

 17%|█▋        | 16982/100629 [13:31<56:51, 24.52it/s]

 17%|█▋        | 16985/100629 [13:31<1:01:40, 22.60it/s]

 17%|█▋        | 16988/100629 [13:31<1:04:35, 21.58it/s]

 17%|█▋        | 16991/100629 [13:32<1:04:58, 21.46it/s]

 17%|█▋        | 16994/100629 [13:32<1:01:34, 22.64it/s]

 17%|█▋        | 16997/100629 [13:32<57:25, 24.27it/s]

 17%|█▋        | 17000/100629 [13:32<58:18, 23.90it/s]

 17%|█▋        | 17004/100629 [13:32<52:13, 26.69it/s]

 17%|█▋        | 17008/100629 [13:32<47:02, 29.63it/s]

 17%|█▋        | 17012/100629 [13:32<57:06, 24.41it/s]

 17%|█▋        | 17016/100629 [13:33<52:38, 26.47it/s]

 17%|█▋        | 17019/100629 [13:33<55:34, 25.08it/s]

 17%|█▋        | 17022/100629 [13:33<55:35, 25.07it/s]

 17%|█▋        | 17026/100629 [13:33<50:55, 27.36it/s]

 17%|█▋        | 17029/100629 [13:33<1:04:49, 21.49it/s]

 17%|█▋        | 17033/100629 [13:33<1:03:06, 22.08it/s]

 17%|█▋        | 17036/100629 [13:33<1:02:11, 22.40it/s]

 17%|█▋        | 17040/100629 [13:34<55:15, 25.21it/s]

 17%|█▋        | 17043/100629 [13:34<1:02:55, 22.14it/s]

 17%|█▋        | 17046/100629 [13:34<1:01:27, 22.67it/s]

 17%|█▋        | 17049/100629 [13:34<59:38, 23.35it/s]

 17%|█▋        | 17052/100629 [13:34<56:17, 24.74it/s]

 17%|█▋        | 17055/100629 [13:34<1:00:46, 22.92it/s]

 17%|█▋        | 17058/100629 [13:34<1:02:19, 22.35it/s]

 17%|█▋        | 17061/100629 [13:35<1:19:05, 17.61it/s]

 17%|█▋        | 17064/100629 [13:35<1:13:23, 18.98it/s]

 17%|█▋        | 17069/100629 [13:35<54:50, 25.39it/s]

 17%|█▋        | 17072/100629 [13:35<55:06, 25.27it/s]

 17%|█▋        | 17075/100629 [13:35<53:46, 25.89it/s]

 17%|█▋        | 17078/100629 [13:35<53:01, 26.26it/s]

 17%|█▋        | 17081/100629 [13:35<1:02:56, 22.13it/s]

 17%|█▋        | 17085/100629 [13:36<59:38, 23.35it/s]

 17%|█▋        | 17088/100629 [13:36<58:25, 23.83it/s]

 17%|█▋        | 17091/100629 [13:36<1:02:21, 22.33it/s]

 17%|█▋        | 17094/100629 [13:36<1:00:19, 23.08it/s]

 17%|█▋        | 17098/100629 [13:36<52:05, 26.72it/s]

 17%|█▋        | 17101/100629 [13:36<58:59, 23.60it/s]

 17%|█▋        | 17104/100629 [13:36<1:07:41, 20.56it/s]

 17%|█▋        | 17108/100629 [13:37<58:05, 23.96it/s]

 17%|█▋        | 17112/100629 [13:37<52:45, 26.38it/s]

 17%|█▋        | 17115/100629 [13:37<1:02:59, 22.09it/s]

 17%|█▋        | 17118/100629 [13:37<1:05:57, 21.10it/s]

 17%|█▋        | 17123/100629 [13:37<56:58, 24.43it/s]

 17%|█▋        | 17126/100629 [13:37<55:15, 25.19it/s]

 17%|█▋        | 17129/100629 [13:37<57:25, 24.23it/s]

 17%|█▋        | 17134/100629 [13:38<48:39, 28.60it/s]

 17%|█▋        | 17137/100629 [13:38<50:54, 27.33it/s]

 17%|█▋        | 17140/100629 [13:38<51:08, 27.21it/s]

 17%|█▋        | 17143/100629 [13:38<1:03:25, 21.94it/s]

 17%|█▋        | 17146/100629 [13:38<1:03:23, 21.95it/s]

 17%|█▋        | 17149/100629 [13:38<1:02:45, 22.17it/s]

 17%|█▋        | 17152/100629 [13:38<1:09:38, 19.98it/s]

 17%|█▋        | 17155/100629 [13:39<1:03:59, 21.74it/s]

 17%|█▋        | 17158/100629 [13:39<1:04:21, 21.62it/s]

 17%|█▋        | 17162/100629 [13:39<59:59, 23.19it/s]

 17%|█▋        | 17165/100629 [13:39<1:00:34, 22.96it/s]

 17%|█▋        | 17168/100629 [13:39<1:07:34, 20.58it/s]

 17%|█▋        | 17171/100629 [13:39<1:01:56, 22.45it/s]

 17%|█▋        | 17174/100629 [13:39<1:07:55, 20.48it/s]

 17%|█▋        | 17177/100629 [13:40<1:09:07, 20.12it/s]

 17%|█▋        | 17181/100629 [13:40<58:25, 23.81it/s]

 17%|█▋        | 17184/100629 [13:40<1:11:51, 19.35it/s]

 17%|█▋        | 17187/100629 [13:40<1:30:59, 15.28it/s]

 17%|█▋        | 17189/100629 [13:40<1:30:53, 15.30it/s]

 17%|█▋        | 17192/100629 [13:40<1:19:51, 17.41it/s]

 17%|█▋        | 17195/100629 [13:41<1:11:31, 19.44it/s]

 17%|█▋        | 17198/100629 [13:41<1:05:31, 21.22it/s]

 17%|█▋        | 17201/100629 [13:41<1:04:28, 21.57it/s]

 17%|█▋        | 17204/100629 [13:41<1:11:58, 19.32it/s]

 17%|█▋        | 17207/100629 [13:41<1:04:52, 21.43it/s]

 17%|█▋        | 17210/100629 [13:41<1:10:45, 19.65it/s]

 17%|█▋        | 17213/100629 [13:41<1:09:38, 19.96it/s]

 17%|█▋        | 17216/100629 [13:42<1:10:44, 19.65it/s]

 17%|█▋        | 17220/100629 [13:42<1:00:54, 22.83it/s]

 17%|█▋        | 17224/100629 [13:42<53:14, 26.11it/s]

 17%|█▋        | 17227/100629 [13:42<1:02:29, 22.24it/s]

 17%|█▋        | 17230/100629 [13:42<1:02:12, 22.34it/s]

 17%|█▋        | 17233/100629 [13:42<1:10:02, 19.84it/s]

 17%|█▋        | 17236/100629 [13:43<1:19:08, 17.56it/s]

 17%|█▋        | 17239/100629 [13:43<1:12:06, 19.28it/s]

 17%|█▋        | 17242/100629 [13:43<1:15:11, 18.48it/s]

 17%|█▋        | 17244/100629 [13:43<1:14:36, 18.63it/s]

 17%|█▋        | 17246/100629 [13:43<1:21:02, 17.15it/s]

 17%|█▋        | 17250/100629 [13:43<1:11:23, 19.47it/s]

 17%|█▋        | 17253/100629 [13:43<1:11:58, 19.31it/s]

 17%|█▋        | 17255/100629 [13:44<1:11:40, 19.39it/s]

 17%|█▋        | 17259/100629 [13:44<58:52, 23.60it/s]

 17%|█▋        | 17262/100629 [13:44<1:01:44, 22.50it/s]

 17%|█▋        | 17265/100629 [13:44<1:07:49, 20.49it/s]

 17%|█▋        | 17268/100629 [13:44<1:06:14, 20.98it/s]

 17%|█▋        | 17271/100629 [13:44<1:12:56, 19.05it/s]

 17%|█▋        | 17273/100629 [13:44<1:15:36, 18.37it/s]

 17%|█▋        | 17275/100629 [13:45<1:15:31, 18.39it/s]

 17%|█▋        | 17277/100629 [13:45<1:14:02, 18.76it/s]

 17%|█▋        | 17279/100629 [13:45<1:18:20, 17.73it/s]

 17%|█▋        | 17282/100629 [13:45<1:06:59, 20.73it/s]

 17%|█▋        | 17286/100629 [13:45<55:43, 24.93it/s]

 17%|█▋        | 17289/100629 [13:45<56:59, 24.37it/s]

 17%|█▋        | 17292/100629 [13:45<1:01:33, 22.57it/s]

 17%|█▋        | 17295/100629 [13:45<1:11:32, 19.41it/s]

 17%|█▋        | 17298/100629 [13:46<1:11:48, 19.34it/s]

 17%|█▋        | 17302/100629 [13:46<1:19:52, 17.39it/s]

 17%|█▋        | 17305/100629 [13:46<1:12:33, 19.14it/s]

 17%|█▋        | 17308/100629 [13:46<1:20:44, 17.20it/s]

 17%|█▋        | 17312/100629 [13:46<1:04:51, 21.41it/s]

 17%|█▋        | 17315/100629 [13:46<1:03:36, 21.83it/s]

 17%|█▋        | 17318/100629 [13:47<1:08:54, 20.15it/s]

 17%|█▋        | 17321/100629 [13:47<1:08:06, 20.39it/s]

 17%|█▋        | 17324/100629 [13:47<1:04:45, 21.44it/s]

 17%|█▋        | 17328/100629 [13:47<55:12, 25.15it/s]

 17%|█▋        | 17331/100629 [13:47<1:00:35, 22.91it/s]

 17%|█▋        | 17334/100629 [13:47<57:46, 24.03it/s]

 17%|█▋        | 17337/100629 [13:47<1:01:36, 22.53it/s]

 17%|█▋        | 17340/100629 [13:48<1:03:12, 21.96it/s]

 17%|█▋        | 17344/100629 [13:48<1:05:59, 21.03it/s]

 17%|█▋        | 17347/100629 [13:48<1:06:33, 20.85it/s]

 17%|█▋        | 17350/100629 [13:48<1:17:36, 17.89it/s]

 17%|█▋        | 17352/100629 [13:48<1:16:59, 18.03it/s]

 17%|█▋        | 17355/100629 [13:48<1:10:25, 19.71it/s]

 17%|█▋        | 17358/100629 [13:49<1:24:36, 16.40it/s]

 17%|█▋        | 17360/100629 [13:49<1:29:30, 15.50it/s]

 17%|█▋        | 17363/100629 [13:49<1:33:16, 14.88it/s]

 17%|█▋        | 17365/100629 [13:49<1:29:24, 15.52it/s]

 17%|█▋        | 17367/100629 [13:49<1:25:33, 16.22it/s]

 17%|█▋        | 17370/100629 [13:49<1:14:24, 18.65it/s]

 17%|█▋        | 17374/100629 [13:50<1:01:16, 22.64it/s]

 17%|█▋        | 17377/100629 [13:50<1:05:15, 21.26it/s]

 17%|█▋        | 17380/100629 [13:50<1:00:33, 22.91it/s]

 17%|█▋        | 17384/100629 [13:50<52:01, 26.67it/s]

 17%|█▋        | 17387/100629 [13:50<1:00:31, 22.92it/s]

 17%|█▋        | 17393/100629 [13:50<47:20, 29.30it/s]

 17%|█▋        | 17397/100629 [13:50<51:26, 26.96it/s]

 17%|█▋        | 17400/100629 [13:51<59:12, 23.43it/s]

 17%|█▋        | 17403/100629 [13:51<56:24, 24.59it/s]

 17%|█▋        | 17407/100629 [13:51<49:45, 27.88it/s]

 17%|█▋        | 17412/100629 [13:51<49:51, 27.81it/s]

 17%|█▋        | 17415/100629 [13:51<59:04, 23.48it/s]

 17%|█▋        | 17419/100629 [13:51<56:28, 24.56it/s]

 17%|█▋        | 17422/100629 [13:51<1:06:06, 20.98it/s]

 17%|█▋        | 17426/100629 [13:52<57:34, 24.08it/s]

 17%|█▋        | 17429/100629 [13:52<1:01:23, 22.59it/s]

 17%|█▋        | 17433/100629 [13:52<54:22, 25.50it/s]

 17%|█▋        | 17436/100629 [13:52<53:17, 26.02it/s]

 17%|█▋        | 17439/100629 [13:52<56:04, 24.73it/s]

 17%|█▋        | 17442/100629 [13:52<1:00:50, 22.79it/s]

 17%|█▋        | 17445/100629 [13:52<57:25, 24.14it/s]

 17%|█▋        | 17449/100629 [13:53<55:05, 25.16it/s]

 17%|█▋        | 17452/100629 [13:53<52:53, 26.21it/s]

 17%|█▋        | 17456/100629 [13:53<55:11, 25.12it/s]

 17%|█▋        | 17460/100629 [13:53<50:18, 27.56it/s]

 17%|█▋        | 17464/100629 [13:53<45:41, 30.33it/s]

 17%|█▋        | 17468/100629 [13:53<58:04, 23.86it/s]

 17%|█▋        | 17471/100629 [13:53<58:36, 23.65it/s]

 17%|█▋        | 17474/100629 [13:54<1:10:09, 19.76it/s]

 17%|█▋        | 17477/100629 [13:54<1:05:49, 21.05it/s]

 17%|█▋        | 17480/100629 [13:54<1:03:53, 21.69it/s]

 17%|█▋        | 17483/100629 [13:54<1:04:09, 21.60it/s]

 17%|█▋        | 17487/100629 [13:54<55:28, 24.98it/s]

 17%|█▋        | 17490/100629 [13:54<54:17, 25.52it/s]

 17%|█▋        | 17493/100629 [13:54<58:28, 23.69it/s]

 17%|█▋        | 17497/100629 [13:54<51:27, 26.93it/s]

 17%|█▋        | 17501/100629 [13:55<46:55, 29.53it/s]

 17%|█▋        | 17505/100629 [13:55<49:02, 28.25it/s]

 17%|█▋        | 17508/100629 [13:55<54:46, 25.29it/s]

 17%|█▋        | 17511/100629 [13:55<57:00, 24.30it/s]

 17%|█▋        | 17514/100629 [13:55<1:05:52, 21.03it/s]

 17%|█▋        | 17517/100629 [13:55<1:07:01, 20.67it/s]

 17%|█▋        | 17520/100629 [13:56<1:06:28, 20.84it/s]

 17%|█▋        | 17523/100629 [13:56<1:01:53, 22.38it/s]

 17%|█▋        | 17526/100629 [13:56<58:25, 23.71it/s]

 17%|█▋        | 17529/100629 [13:56<1:00:34, 22.87it/s]

 17%|█▋        | 17532/100629 [13:56<1:02:17, 22.23it/s]

 17%|█▋        | 17535/100629 [13:56<1:00:15, 22.98it/s]

 17%|█▋        | 17538/100629 [13:56<1:09:00, 20.07it/s]

 17%|█▋        | 17541/100629 [13:56<1:09:17, 19.99it/s]

 17%|█▋        | 17544/100629 [13:57<1:12:22, 19.13it/s]

 17%|█▋        | 17546/100629 [13:57<1:12:51, 19.01it/s]

 17%|█▋        | 17549/100629 [13:57<1:07:05, 20.64it/s]

 17%|█▋        | 17552/100629 [13:57<1:12:59, 18.97it/s]

 17%|█▋        | 17556/100629 [13:57<1:06:18, 20.88it/s]

 17%|█▋        | 17559/100629 [13:58<1:25:35, 16.18it/s]

 17%|█▋        | 17561/100629 [13:58<1:28:30, 15.64it/s]

 17%|█▋        | 17565/100629 [13:58<1:14:28, 18.59it/s]

 17%|█▋        | 17569/100629 [13:58<1:05:51, 21.02it/s]

 17%|█▋        | 17572/100629 [13:58<1:09:19, 19.97it/s]

 17%|█▋        | 17575/100629 [13:58<1:05:25, 21.16it/s]

 17%|█▋        | 17578/100629 [13:58<1:05:23, 21.17it/s]

 17%|█▋        | 17581/100629 [13:59<1:00:44, 22.79it/s]

 17%|█▋        | 17584/100629 [13:59<1:04:58, 21.30it/s]

 17%|█▋        | 17587/100629 [13:59<1:01:07, 22.64it/s]

 17%|█▋        | 17590/100629 [13:59<1:20:02, 17.29it/s]

 17%|█▋        | 17592/100629 [13:59<1:17:39, 17.82it/s]

 17%|█▋        | 17594/100629 [13:59<1:20:02, 17.29it/s]

 17%|█▋        | 17596/100629 [13:59<1:37:37, 14.18it/s]

 17%|█▋        | 17599/100629 [14:00<1:29:17, 15.50it/s]

 17%|█▋        | 17602/100629 [14:00<1:17:08, 17.94it/s]

 17%|█▋        | 17605/100629 [14:00<1:10:24, 19.65it/s]

 17%|█▋        | 17608/100629 [14:00<1:10:07, 19.73it/s]

 18%|█▊        | 17611/100629 [14:00<1:10:42, 19.57it/s]

 18%|█▊        | 17614/100629 [14:00<1:05:57, 20.97it/s]

 18%|█▊        | 17617/100629 [14:00<1:02:20, 22.19it/s]

 18%|█▊        | 17621/100629 [14:01<59:27, 23.27it/s]

 18%|█▊        | 17624/100629 [14:01<1:04:34, 21.42it/s]

 18%|█▊        | 17627/100629 [14:01<1:03:01, 21.95it/s]

 18%|█▊        | 17631/100629 [14:01<58:33, 23.63it/s]

 18%|█▊        | 17635/100629 [14:01<50:34, 27.35it/s]

 18%|█▊        | 17638/100629 [14:01<50:58, 27.13it/s]

 18%|█▊        | 17641/100629 [14:01<52:54, 26.14it/s]

 18%|█▊        | 17644/100629 [14:02<1:03:20, 21.84it/s]

 18%|█▊        | 17649/100629 [14:02<56:35, 24.44it/s]

 18%|█▊        | 17653/100629 [14:02<53:58, 25.62it/s]

 18%|█▊        | 17656/100629 [14:02<58:05, 23.80it/s]

 18%|█▊        | 17659/100629 [14:02<55:51, 24.76it/s]

 18%|█▊        | 17662/100629 [14:02<1:08:13, 20.27it/s]

 18%|█▊        | 17665/100629 [14:02<1:05:57, 20.96it/s]

 18%|█▊        | 17668/100629 [14:03<1:12:45, 19.00it/s]

 18%|█▊        | 17671/100629 [14:03<1:08:23, 20.22it/s]

 18%|█▊        | 17675/100629 [14:03<58:23, 23.67it/s]

 18%|█▊        | 17679/100629 [14:03<55:59, 24.69it/s]

 18%|█▊        | 17683/100629 [14:03<54:31, 25.35it/s]

 18%|█▊        | 17686/100629 [14:03<55:43, 24.81it/s]

 18%|█▊        | 17690/100629 [14:03<49:12, 28.09it/s]

 18%|█▊        | 17693/100629 [14:04<52:34, 26.29it/s]

 18%|█▊        | 17697/100629 [14:04<52:48, 26.18it/s]

 18%|█▊        | 17701/100629 [14:04<49:53, 27.71it/s]

 18%|█▊        | 17705/100629 [14:04<53:17, 25.94it/s]

 18%|█▊        | 17708/100629 [14:04<57:08, 24.18it/s]

 18%|█▊        | 17713/100629 [14:04<46:44, 29.56it/s]

 18%|█▊        | 17717/100629 [14:04<50:36, 27.30it/s]

 18%|█▊        | 17720/100629 [14:05<55:29, 24.90it/s]

 18%|█▊        | 17724/100629 [14:05<50:34, 27.32it/s]

 18%|█▊        | 17727/100629 [14:05<1:08:26, 20.19it/s]

 18%|█▊        | 17730/100629 [14:05<1:05:35, 21.06it/s]

 18%|█▊        | 17733/100629 [14:05<1:08:49, 20.08it/s]

 18%|█▊        | 17736/100629 [14:05<1:03:26, 21.77it/s]

 18%|█▊        | 17739/100629 [14:06<1:00:28, 22.84it/s]

 18%|█▊        | 17744/100629 [14:06<51:33, 26.79it/s]

 18%|█▊        | 17747/100629 [14:06<1:05:21, 21.14it/s]

 18%|█▊        | 17750/100629 [14:06<1:09:07, 19.98it/s]

 18%|█▊        | 17754/100629 [14:06<58:47, 23.50it/s]

 18%|█▊        | 17757/100629 [14:06<1:09:30, 19.87it/s]

 18%|█▊        | 17760/100629 [14:06<1:04:19, 21.47it/s]

 18%|█▊        | 17763/100629 [14:07<1:04:38, 21.37it/s]

 18%|█▊        | 17766/100629 [14:07<1:04:07, 21.54it/s]

 18%|█▊        | 17769/100629 [14:07<59:44, 23.11it/s]

 18%|█▊        | 17772/100629 [14:07<1:00:36, 22.78it/s]

 18%|█▊        | 17775/100629 [14:07<58:40, 23.54it/s]

 18%|█▊        | 17778/100629 [14:07<57:21, 24.07it/s]

 18%|█▊        | 17782/100629 [14:07<50:43, 27.22it/s]

 18%|█▊        | 17785/100629 [14:07<51:34, 26.77it/s]

 18%|█▊        | 17788/100629 [14:08<56:40, 24.36it/s]

 18%|█▊        | 17791/100629 [14:08<58:44, 23.50it/s]

 18%|█▊        | 17794/100629 [14:08<1:14:26, 18.54it/s]

 18%|█▊        | 17797/100629 [14:08<1:13:20, 18.82it/s]

 18%|█▊        | 17801/100629 [14:08<1:02:43, 22.01it/s]

 18%|█▊        | 17804/100629 [14:09<1:23:48, 16.47it/s]

 18%|█▊        | 17806/100629 [14:09<1:31:52, 15.02it/s]

 18%|█▊        | 17808/100629 [14:09<1:37:26, 14.17it/s]

 18%|█▊        | 17812/100629 [14:09<1:14:43, 18.47it/s]

 18%|█▊        | 17815/100629 [14:09<1:21:49, 16.87it/s]

 18%|█▊        | 17819/100629 [14:09<1:10:54, 19.46it/s]

 18%|█▊        | 17822/100629 [14:10<1:09:30, 19.86it/s]

 18%|█▊        | 17825/100629 [14:10<1:08:21, 20.19it/s]

 18%|█▊        | 17828/100629 [14:10<1:07:40, 20.39it/s]

 18%|█▊        | 17831/100629 [14:10<1:09:48, 19.77it/s]

 18%|█▊        | 17834/100629 [14:10<1:05:30, 21.07it/s]

 18%|█▊        | 17837/100629 [14:10<1:00:02, 22.98it/s]

 18%|█▊        | 17840/100629 [14:10<1:17:18, 17.85it/s]

 18%|█▊        | 17843/100629 [14:11<1:20:23, 17.16it/s]

 18%|█▊        | 17847/100629 [14:11<1:08:39, 20.10it/s]

 18%|█▊        | 17850/100629 [14:11<1:12:17, 19.09it/s]

 18%|█▊        | 17853/100629 [14:11<1:13:18, 18.82it/s]

 18%|█▊        | 17855/100629 [14:11<1:21:05, 17.01it/s]

 18%|█▊        | 17858/100629 [14:11<1:17:53, 17.71it/s]

 18%|█▊        | 17861/100629 [14:12<1:13:20, 18.81it/s]

 18%|█▊        | 17863/100629 [14:12<1:15:22, 18.30it/s]

 18%|█▊        | 17868/100629 [14:12<56:42, 24.32it/s]

 18%|█▊        | 17871/100629 [14:12<56:53, 24.24it/s]

 18%|█▊        | 17874/100629 [14:12<1:00:56, 22.63it/s]

 18%|█▊        | 17877/100629 [14:12<1:03:01, 21.89it/s]

 18%|█▊        | 17881/100629 [14:12<53:51, 25.61it/s]

 18%|█▊        | 17884/100629 [14:13<2:13:05, 10.36it/s]

 18%|█▊        | 17888/100629 [14:13<1:43:04, 13.38it/s]

 18%|█▊        | 17891/100629 [14:13<1:34:42, 14.56it/s]

 18%|█▊        | 17894/100629 [14:14<1:27:45, 15.71it/s]

 18%|█▊        | 17897/100629 [14:14<1:37:20, 14.17it/s]

 18%|█▊        | 17900/100629 [14:14<1:26:57, 15.86it/s]

 18%|█▊        | 17903/100629 [14:14<1:15:39, 18.22it/s]

 18%|█▊        | 17907/100629 [14:14<1:02:12, 22.16it/s]

 18%|█▊        | 17910/100629 [14:14<59:23, 23.21it/s]

 18%|█▊        | 17913/100629 [14:14<1:02:59, 21.89it/s]

 18%|█▊        | 17916/100629 [14:15<59:05, 23.33it/s]

 18%|█▊        | 17919/100629 [14:15<1:02:10, 22.17it/s]

 18%|█▊        | 17922/100629 [14:15<1:14:46, 18.43it/s]

 18%|█▊        | 17925/100629 [14:15<1:20:15, 17.17it/s]

 18%|█▊        | 17928/100629 [14:15<1:24:58, 16.22it/s]

 18%|█▊        | 17931/100629 [14:16<1:28:44, 15.53it/s]

 18%|█▊        | 17934/100629 [14:16<1:18:10, 17.63it/s]

 18%|█▊        | 17936/100629 [14:16<1:18:56, 17.46it/s]

 18%|█▊        | 17938/100629 [14:16<1:26:41, 15.90it/s]

 18%|█▊        | 17940/100629 [14:16<1:27:17, 15.79it/s]

 18%|█▊        | 17942/100629 [14:16<1:49:07, 12.63it/s]

 18%|█▊        | 17945/100629 [14:16<1:33:47, 14.69it/s]

 18%|█▊        | 17948/100629 [14:17<1:17:30, 17.78it/s]

 18%|█▊        | 17951/100629 [14:17<1:08:31, 20.11it/s]

 18%|█▊        | 17954/100629 [14:17<1:11:03, 19.39it/s]

 18%|█▊        | 17957/100629 [14:17<1:03:11, 21.81it/s]

 18%|█▊        | 17960/100629 [14:17<1:02:18, 22.11it/s]

 18%|█▊        | 17963/100629 [14:17<1:15:11, 18.33it/s]

 18%|█▊        | 17967/100629 [14:17<1:04:04, 21.50it/s]

 18%|█▊        | 17970/100629 [14:18<1:19:10, 17.40it/s]

 18%|█▊        | 17972/100629 [14:18<1:18:59, 17.44it/s]

 18%|█▊        | 17975/100629 [14:18<1:18:56, 17.45it/s]

 18%|█▊        | 17979/100629 [14:18<1:06:41, 20.66it/s]

 18%|█▊        | 17982/100629 [14:18<1:04:08, 21.47it/s]

 18%|█▊        | 17985/100629 [14:18<1:01:42, 22.32it/s]

 18%|█▊        | 17988/100629 [14:18<57:28, 23.96it/s]

 18%|█▊        | 17991/100629 [14:19<58:43, 23.46it/s]

 18%|█▊        | 17994/100629 [14:19<1:00:58, 22.59it/s]

 18%|█▊        | 17998/100629 [14:19<55:16, 24.92it/s]

 18%|█▊        | 18002/100629 [14:19<49:56, 27.58it/s]

 18%|█▊        | 18005/100629 [14:19<1:01:11, 22.51it/s]

 18%|█▊        | 18010/100629 [14:19<48:58, 28.11it/s]

 18%|█▊        | 18014/100629 [14:20<1:00:44, 22.67it/s]

 18%|█▊        | 18018/100629 [14:20<1:05:35, 20.99it/s]

 18%|█▊        | 18022/100629 [14:20<56:23, 24.41it/s]

 18%|█▊        | 18025/100629 [14:20<57:26, 23.97it/s]

 18%|█▊        | 18028/100629 [14:20<55:07, 24.97it/s]

 18%|█▊        | 18031/100629 [14:20<57:26, 23.97it/s]

 18%|█▊        | 18034/100629 [14:20<1:05:03, 21.16it/s]

 18%|█▊        | 18037/100629 [14:21<1:05:55, 20.88it/s]

 18%|█▊        | 18040/100629 [14:21<1:20:52, 17.02it/s]

 18%|█▊        | 18044/100629 [14:21<1:11:31, 19.24it/s]

 18%|█▊        | 18047/100629 [14:21<1:06:37, 20.66it/s]

 18%|█▊        | 18050/100629 [14:21<1:06:28, 20.71it/s]

 18%|█▊        | 18053/100629 [14:21<1:06:24, 20.73it/s]

 18%|█▊        | 18056/100629 [14:22<1:13:58, 18.61it/s]

 18%|█▊        | 18059/100629 [14:22<1:06:07, 20.81it/s]

 18%|█▊        | 18062/100629 [14:22<1:01:58, 22.21it/s]

 18%|█▊        | 18066/100629 [14:22<57:10, 24.07it/s]

 18%|█▊        | 18070/100629 [14:22<53:20, 25.80it/s]

 18%|█▊        | 18073/100629 [14:22<54:58, 25.03it/s]

 18%|█▊        | 18076/100629 [14:22<53:03, 25.93it/s]

 18%|█▊        | 18079/100629 [14:22<55:04, 24.98it/s]

 18%|█▊        | 18084/100629 [14:23<45:56, 29.95it/s]

 18%|█▊        | 18088/100629 [14:23<52:43, 26.09it/s]

 18%|█▊        | 18091/100629 [14:23<57:27, 23.94it/s]

 18%|█▊        | 18094/100629 [14:23<1:06:26, 20.70it/s]

 18%|█▊        | 18097/100629 [14:23<1:08:07, 20.19it/s]

 18%|█▊        | 18102/100629 [14:23<57:26, 23.94it/s]

 18%|█▊        | 18105/100629 [14:24<1:00:27, 22.75it/s]

 18%|█▊        | 18108/100629 [14:24<1:06:07, 20.80it/s]

 18%|█▊        | 18111/100629 [14:24<1:12:41, 18.92it/s]

 18%|█▊        | 18113/100629 [14:24<1:16:15, 18.03it/s]

 18%|█▊        | 18116/100629 [14:24<1:13:12, 18.79it/s]

 18%|█▊        | 18119/100629 [14:24<1:11:20, 19.27it/s]

 18%|█▊        | 18121/100629 [14:25<1:12:52, 18.87it/s]

 18%|█▊        | 18123/100629 [14:25<1:17:42, 17.70it/s]

 18%|█▊        | 18125/100629 [14:25<1:20:47, 17.02it/s]

 18%|█▊        | 18127/100629 [14:25<1:29:29, 15.37it/s]

 18%|█▊        | 18130/100629 [14:25<1:16:09, 18.06it/s]

 18%|█▊        | 18133/100629 [14:25<1:14:37, 18.42it/s]

 18%|█▊        | 18136/100629 [14:25<1:07:41, 20.31it/s]

 18%|█▊        | 18140/100629 [14:26<1:05:52, 20.87it/s]

 18%|█▊        | 18143/100629 [14:26<1:04:27, 21.33it/s]

 18%|█▊        | 18146/100629 [14:26<59:21, 23.16it/s]

 18%|█▊        | 18149/100629 [14:26<59:22, 23.15it/s]

 18%|█▊        | 18152/100629 [14:26<58:37, 23.45it/s]

 18%|█▊        | 18155/100629 [14:26<1:07:42, 20.30it/s]

 18%|█▊        | 18158/100629 [14:26<1:04:26, 21.33it/s]

 18%|█▊        | 18161/100629 [14:26<1:04:09, 21.42it/s]

 18%|█▊        | 18164/100629 [14:27<1:10:53, 19.39it/s]

 18%|█▊        | 18167/100629 [14:27<1:17:03, 17.84it/s]

 18%|█▊        | 18169/100629 [14:27<1:18:36, 17.48it/s]

 18%|█▊        | 18172/100629 [14:27<1:12:55, 18.84it/s]

 18%|█▊        | 18176/100629 [14:27<1:03:31, 21.63it/s]

 18%|█▊        | 18179/100629 [14:27<1:05:34, 20.96it/s]

 18%|█▊        | 18182/100629 [14:28<1:15:56, 18.09it/s]

 18%|█▊        | 18186/100629 [14:28<1:11:40, 19.17it/s]

 18%|█▊        | 18188/100629 [14:28<1:16:20, 18.00it/s]

 18%|█▊        | 18194/100629 [14:28<59:54, 22.93it/s]

 18%|█▊        | 18197/100629 [14:28<57:49, 23.76it/s]

 18%|█▊        | 18200/100629 [14:28<1:02:03, 22.14it/s]

 18%|█▊        | 18203/100629 [14:29<58:00, 23.68it/s]

 18%|█▊        | 18206/100629 [14:29<1:08:23, 20.09it/s]

 18%|█▊        | 18209/100629 [14:29<1:21:09, 16.93it/s]

 18%|█▊        | 18211/100629 [14:29<1:32:57, 14.78it/s]

 18%|█▊        | 18213/100629 [14:29<1:41:00, 13.60it/s]

 18%|█▊        | 18215/100629 [14:29<1:37:54, 14.03it/s]

 18%|█▊        | 18218/100629 [14:30<1:23:33, 16.44it/s]

 18%|█▊        | 18220/100629 [14:30<1:24:06, 16.33it/s]

 18%|█▊        | 18223/100629 [14:30<1:11:07, 19.31it/s]

 18%|█▊        | 18227/100629 [14:30<59:54, 22.92it/s]

 18%|█▊        | 18231/100629 [14:30<54:27, 25.22it/s]

 18%|█▊        | 18234/100629 [14:30<52:15, 26.27it/s]

 18%|█▊        | 18237/100629 [14:30<51:03, 26.89it/s]

 18%|█▊        | 18240/100629 [14:31<1:04:59, 21.13it/s]

 18%|█▊        | 18243/100629 [14:31<1:06:55, 20.52it/s]

 18%|█▊        | 18246/100629 [14:31<1:14:27, 18.44it/s]

 18%|█▊        | 18249/100629 [14:31<1:09:08, 19.86it/s]

 18%|█▊        | 18252/100629 [14:31<1:12:33, 18.92it/s]

 18%|█▊        | 18255/100629 [14:31<1:04:46, 21.19it/s]

 18%|█▊        | 18258/100629 [14:31<1:00:55, 22.53it/s]

 18%|█▊        | 18261/100629 [14:32<1:02:34, 21.94it/s]

 18%|█▊        | 18264/100629 [14:32<1:03:18, 21.68it/s]

 18%|█▊        | 18267/100629 [14:32<59:35, 23.03it/s]

 18%|█▊        | 18270/100629 [14:32<1:03:09, 21.73it/s]

 18%|█▊        | 18274/100629 [14:32<1:04:02, 21.44it/s]

 18%|█▊        | 18278/100629 [14:32<58:06, 23.62it/s]

 18%|█▊        | 18281/100629 [14:33<1:11:23, 19.23it/s]

 18%|█▊        | 18284/100629 [14:33<1:06:42, 20.57it/s]

 18%|█▊        | 18287/100629 [14:33<1:09:44, 19.68it/s]

 18%|█▊        | 18290/100629 [14:33<1:08:35, 20.01it/s]

 18%|█▊        | 18293/100629 [14:33<1:16:19, 17.98it/s]

 18%|█▊        | 18296/100629 [14:33<1:15:12, 18.25it/s]

 18%|█▊        | 18298/100629 [14:33<1:21:11, 16.90it/s]

 18%|█▊        | 18301/100629 [14:34<1:11:30, 19.19it/s]

 18%|█▊        | 18304/100629 [14:34<1:12:07, 19.02it/s]

 18%|█▊        | 18306/100629 [14:34<1:30:57, 15.09it/s]

 18%|█▊        | 18309/100629 [14:34<1:21:59, 16.73it/s]

 18%|█▊        | 18313/100629 [14:34<1:07:55, 20.20it/s]

 18%|█▊        | 18316/100629 [14:34<1:01:40, 22.25it/s]

 18%|█▊        | 18319/100629 [14:35<1:35:50, 14.31it/s]

 18%|█▊        | 18322/100629 [14:35<1:25:43, 16.00it/s]

 18%|█▊        | 18325/100629 [14:35<1:23:35, 16.41it/s]

 18%|█▊        | 18328/100629 [14:35<1:26:52, 15.79it/s]

 18%|█▊        | 18331/100629 [14:35<1:22:20, 16.66it/s]

 18%|█▊        | 18334/100629 [14:36<1:14:54, 18.31it/s]

 18%|█▊        | 18338/100629 [14:36<1:00:47, 22.56it/s]

 18%|█▊        | 18341/100629 [14:36<58:25, 23.48it/s]

 18%|█▊        | 18344/100629 [14:36<1:01:18, 22.37it/s]

 18%|█▊        | 18347/100629 [14:36<1:13:59, 18.53it/s]

 18%|█▊        | 18350/100629 [14:36<1:09:08, 19.83it/s]

 18%|█▊        | 18353/100629 [14:36<1:10:55, 19.33it/s]

 18%|█▊        | 18356/100629 [14:37<1:04:23, 21.30it/s]

 18%|█▊        | 18360/100629 [14:37<1:00:06, 22.81it/s]

 18%|█▊        | 18363/100629 [14:37<59:41, 22.97it/s]

 18%|█▊        | 18366/100629 [14:37<57:27, 23.86it/s]

 18%|█▊        | 18369/100629 [14:37<59:18, 23.12it/s]

 18%|█▊        | 18372/100629 [14:37<58:19, 23.51it/s]

 18%|█▊        | 18376/100629 [14:37<50:23, 27.21it/s]

 18%|█▊        | 18379/100629 [14:37<56:55, 24.08it/s]

 18%|█▊        | 18382/100629 [14:38<1:02:14, 22.02it/s]

 18%|█▊        | 18386/100629 [14:38<56:30, 24.26it/s]

 18%|█▊        | 18389/100629 [14:38<56:29, 24.26it/s]

 18%|█▊        | 18392/100629 [14:38<1:02:13, 22.03it/s]

 18%|█▊        | 18395/100629 [14:38<1:02:42, 21.86it/s]

 18%|█▊        | 18398/100629 [14:38<1:00:14, 22.75it/s]

 18%|█▊        | 18401/100629 [14:39<1:15:24, 18.18it/s]

 18%|█▊        | 18405/100629 [14:39<1:01:12, 22.39it/s]

 18%|█▊        | 18410/100629 [14:39<49:51, 27.48it/s]

 18%|█▊        | 18414/100629 [14:39<58:31, 23.42it/s]

 18%|█▊        | 18417/100629 [14:39<59:45, 22.93it/s]

 18%|█▊        | 18420/100629 [14:39<1:05:54, 20.79it/s]

 18%|█▊        | 18423/100629 [14:39<1:02:55, 21.77it/s]

 18%|█▊        | 18426/100629 [14:40<1:01:31, 22.27it/s]

 18%|█▊        | 18430/100629 [14:40<54:34, 25.11it/s]

 18%|█▊        | 18433/100629 [14:40<1:12:17, 18.95it/s]

 18%|█▊        | 18436/100629 [14:40<1:12:18, 18.94it/s]

 18%|█▊        | 18440/100629 [14:40<1:03:04, 21.72it/s]

 18%|█▊        | 18443/100629 [14:40<1:07:54, 20.17it/s]

 18%|█▊        | 18448/100629 [14:41<55:29, 24.69it/s]

 18%|█▊        | 18451/100629 [14:41<56:36, 24.20it/s]

 18%|█▊        | 18455/100629 [14:41<54:00, 25.36it/s]

 18%|█▊        | 18458/100629 [14:41<1:00:28, 22.65it/s]

 18%|█▊        | 18461/100629 [14:41<58:07, 23.56it/s]

 18%|█▊        | 18465/100629 [14:41<51:47, 26.44it/s]

 18%|█▊        | 18468/100629 [14:41<53:14, 25.72it/s]

 18%|█▊        | 18471/100629 [14:41<52:20, 26.16it/s]

 18%|█▊        | 18474/100629 [14:42<54:29, 25.13it/s]

 18%|█▊        | 18477/100629 [14:42<59:12, 23.13it/s]

 18%|█▊        | 18480/100629 [14:42<1:00:15, 22.72it/s]

 18%|█▊        | 18483/100629 [14:42<1:00:20, 22.69it/s]

 18%|█▊        | 18486/100629 [14:42<58:51, 23.26it/s]

 18%|█▊        | 18489/100629 [14:42<58:26, 23.43it/s]

 18%|█▊        | 18492/100629 [14:42<1:08:17, 20.05it/s]

 18%|█▊        | 18495/100629 [14:43<1:18:09, 17.51it/s]

 18%|█▊        | 18498/100629 [14:43<1:11:43, 19.09it/s]

 18%|█▊        | 18501/100629 [14:43<1:15:34, 18.11it/s]

 18%|█▊        | 18504/100629 [14:43<1:07:58, 20.14it/s]

 18%|█▊        | 18507/100629 [14:43<1:15:44, 18.07it/s]

 18%|█▊        | 18509/100629 [14:43<1:14:35, 18.35it/s]

 18%|█▊        | 18511/100629 [14:44<1:18:34, 17.42it/s]

 18%|█▊        | 18514/100629 [14:44<1:09:52, 19.58it/s]

 18%|█▊        | 18517/100629 [14:44<1:07:13, 20.36it/s]

 18%|█▊        | 18520/100629 [14:44<1:07:42, 20.21it/s]

 18%|█▊        | 18523/100629 [14:44<1:33:40, 14.61it/s]

 18%|█▊        | 18526/100629 [14:44<1:18:58, 17.33it/s]

 18%|█▊        | 18529/100629 [14:45<1:16:24, 17.91it/s]

 18%|█▊        | 18532/100629 [14:45<1:12:08, 18.97it/s]

 18%|█▊        | 18535/100629 [14:45<1:09:37, 19.65it/s]

 18%|█▊        | 18538/100629 [14:45<1:15:55, 18.02it/s]

 18%|█▊        | 18540/100629 [14:45<1:14:32, 18.35it/s]

 18%|█▊        | 18542/100629 [14:45<1:13:11, 18.69it/s]

 18%|█▊        | 18544/100629 [14:45<1:24:51, 16.12it/s]

 18%|█▊        | 18548/100629 [14:45<1:07:45, 20.19it/s]

 18%|█▊        | 18551/100629 [14:46<1:15:54, 18.02it/s]

 18%|█▊        | 18555/100629 [14:46<1:05:34, 20.86it/s]

 18%|█▊        | 18558/100629 [14:46<1:20:51, 16.92it/s]

 18%|█▊        | 18562/100629 [14:46<1:10:41, 19.35it/s]

 18%|█▊        | 18565/100629 [14:46<1:08:01, 20.11it/s]

 18%|█▊        | 18568/100629 [14:47<1:24:40, 16.15it/s]

 18%|█▊        | 18570/100629 [14:47<1:29:42, 15.25it/s]

 18%|█▊        | 18573/100629 [14:47<1:24:42, 16.14it/s]

 18%|█▊        | 18576/100629 [14:47<1:23:00, 16.48it/s]

 18%|█▊        | 18579/100629 [14:47<1:19:38, 17.17it/s]

 18%|█▊        | 18581/100629 [14:47<1:20:47, 16.92it/s]

 18%|█▊        | 18584/100629 [14:48<1:19:35, 17.18it/s]

 18%|█▊        | 18587/100629 [14:48<1:09:11, 19.76it/s]

 18%|█▊        | 18590/100629 [14:48<1:04:53, 21.07it/s]

 18%|█▊        | 18593/100629 [14:48<59:27, 22.99it/s]

 18%|█▊        | 18596/100629 [14:48<1:07:29, 20.26it/s]

 18%|█▊        | 18599/100629 [14:48<1:09:48, 19.58it/s]

 18%|█▊        | 18602/100629 [14:48<1:10:22, 19.43it/s]

 18%|█▊        | 18605/100629 [14:49<1:12:24, 18.88it/s]

 18%|█▊        | 18607/100629 [14:49<1:41:23, 13.48it/s]

 18%|█▊        | 18609/100629 [14:49<1:42:43, 13.31it/s]

 18%|█▊        | 18611/100629 [14:49<1:41:07, 13.52it/s]

 18%|█▊        | 18615/100629 [14:49<1:14:10, 18.43it/s]

 19%|█▊        | 18618/100629 [14:50<1:16:43, 17.82it/s]

 19%|█▊        | 18621/100629 [14:50<1:13:07, 18.69it/s]

 19%|█▊        | 18624/100629 [14:50<1:06:06, 20.67it/s]

 19%|█▊        | 18627/100629 [14:50<1:09:44, 19.60it/s]

 19%|█▊        | 18630/100629 [14:50<1:02:59, 21.69it/s]

 19%|█▊        | 18633/100629 [14:50<1:10:18, 19.44it/s]

 19%|█▊        | 18637/100629 [14:50<58:22, 23.41it/s]

 19%|█▊        | 18640/100629 [14:50<58:04, 23.53it/s]

 19%|█▊        | 18645/100629 [14:51<46:38, 29.29it/s]

 19%|█▊        | 18649/100629 [14:51<50:40, 26.96it/s]

 19%|█▊        | 18652/100629 [14:51<53:09, 25.70it/s]

 19%|█▊        | 18655/100629 [14:51<57:17, 23.85it/s]

 19%|█▊        | 18658/100629 [14:51<1:07:23, 20.27it/s]

 19%|█▊        | 18661/100629 [14:51<1:02:22, 21.90it/s]

 19%|█▊        | 18664/100629 [14:52<1:07:56, 20.10it/s]

 19%|█▊        | 18667/100629 [14:52<1:09:11, 19.74it/s]

 19%|█▊        | 18671/100629 [14:52<57:00, 23.96it/s]

 19%|█▊        | 18674/100629 [14:52<55:52, 24.44it/s]

 19%|█▊        | 18677/100629 [14:52<1:00:15, 22.67it/s]

 19%|█▊        | 18680/100629 [14:52<1:11:18, 19.15it/s]

 19%|█▊        | 18683/100629 [14:52<1:17:21, 17.66it/s]

 19%|█▊        | 18685/100629 [14:53<1:26:59, 15.70it/s]

 19%|█▊        | 18688/100629 [14:53<1:21:06, 16.84it/s]

 19%|█▊        | 18692/100629 [14:53<1:06:57, 20.40it/s]

 19%|█▊        | 18695/100629 [14:53<1:03:50, 21.39it/s]

 19%|█▊        | 18698/100629 [14:53<1:05:35, 20.82it/s]

 19%|█▊        | 18701/100629 [14:53<1:16:59, 17.73it/s]

 19%|█▊        | 18703/100629 [14:54<1:42:40, 13.30it/s]

 19%|█▊        | 18707/100629 [14:54<1:23:51, 16.28it/s]

 19%|█▊        | 18711/100629 [14:54<1:10:37, 19.33it/s]

 19%|█▊        | 18714/100629 [14:54<1:06:25, 20.56it/s]

 19%|█▊        | 18717/100629 [14:54<1:06:20, 20.58it/s]

 19%|█▊        | 18720/100629 [14:54<1:01:33, 22.18it/s]

 19%|█▊        | 18723/100629 [14:55<1:01:24, 22.23it/s]

 19%|█▊        | 18726/100629 [14:55<1:12:18, 18.88it/s]

 19%|█▊        | 18729/100629 [14:55<1:22:44, 16.50it/s]

 19%|█▊        | 18731/100629 [14:55<1:21:57, 16.65it/s]

 19%|█▊        | 18734/100629 [14:55<1:17:02, 17.72it/s]

 19%|█▊        | 18738/100629 [14:55<1:12:08, 18.92it/s]

 19%|█▊        | 18740/100629 [14:56<1:11:56, 18.97it/s]

 19%|█▊        | 18743/100629 [14:56<1:09:54, 19.52it/s]

 19%|█▊        | 18747/100629 [14:56<57:15, 23.83it/s]

 19%|█▊        | 18750/100629 [14:56<57:47, 23.62it/s]

 19%|█▊        | 18753/100629 [14:56<59:29, 22.94it/s]

 19%|█▊        | 18756/100629 [14:56<1:00:43, 22.47it/s]

 19%|█▊        | 18759/100629 [14:56<1:04:01, 21.31it/s]

 19%|█▊        | 18762/100629 [14:56<1:01:28, 22.20it/s]

 19%|█▊        | 18765/100629 [14:57<1:04:32, 21.14it/s]

 19%|█▊        | 18769/100629 [14:57<54:05, 25.22it/s]

 19%|█▊        | 18773/100629 [14:57<54:30, 25.03it/s]

 19%|█▊        | 18776/100629 [14:57<58:36, 23.28it/s]

 19%|█▊        | 18779/100629 [14:57<1:02:12, 21.93it/s]

 19%|█▊        | 18782/100629 [14:57<1:02:07, 21.96it/s]

 19%|█▊        | 18785/100629 [14:58<1:14:35, 18.29it/s]

 19%|█▊        | 18790/100629 [14:58<1:00:40, 22.48it/s]

 19%|█▊        | 18793/100629 [14:58<57:33, 23.70it/s]

 19%|█▊        | 18796/100629 [14:58<1:15:42, 18.01it/s]

 19%|█▊        | 18800/100629 [14:58<1:03:04, 21.62it/s]

 19%|█▊        | 18805/100629 [14:58<49:45, 27.41it/s]

 19%|█▊        | 18809/100629 [14:58<52:15, 26.10it/s]

 19%|█▊        | 18812/100629 [14:59<55:49, 24.43it/s]

 19%|█▊        | 18815/100629 [14:59<1:03:48, 21.37it/s]

 19%|█▊        | 18818/100629 [14:59<59:19, 22.98it/s]

 19%|█▊        | 18821/100629 [14:59<1:01:08, 22.30it/s]

 19%|█▊        | 18824/100629 [14:59<1:00:39, 22.48it/s]

 19%|█▊        | 18827/100629 [14:59<1:01:59, 21.99it/s]

 19%|█▊        | 18831/100629 [14:59<53:19, 25.57it/s]

 19%|█▊        | 18834/100629 [15:00<58:12, 23.42it/s]

 19%|█▊        | 18837/100629 [15:00<1:09:11, 19.70it/s]

 19%|█▊        | 18841/100629 [15:00<57:28, 23.72it/s]

 19%|█▊        | 18844/100629 [15:00<57:00, 23.91it/s]

 19%|█▊        | 18847/100629 [15:00<57:14, 23.81it/s]

 19%|█▊        | 18850/100629 [15:00<1:00:13, 22.63it/s]

 19%|█▊        | 18853/100629 [15:00<57:10, 23.84it/s]

 19%|█▊        | 18857/100629 [15:01<51:18, 26.56it/s]

 19%|█▊        | 18860/100629 [15:01<51:29, 26.46it/s]

 19%|█▊        | 18863/100629 [15:01<1:02:34, 21.78it/s]

 19%|█▊        | 18866/100629 [15:01<1:10:38, 19.29it/s]

 19%|█▉        | 18869/100629 [15:01<1:21:38, 16.69it/s]

 19%|█▉        | 18873/100629 [15:01<1:09:17, 19.66it/s]

 19%|█▉        | 18876/100629 [15:02<1:03:49, 21.35it/s]

 19%|█▉        | 18879/100629 [15:02<1:11:15, 19.12it/s]

 19%|█▉        | 18882/100629 [15:02<1:09:54, 19.49it/s]

 19%|█▉        | 18885/100629 [15:02<1:03:41, 21.39it/s]

 19%|█▉        | 18888/100629 [15:02<1:07:51, 20.08it/s]

 19%|█▉        | 18891/100629 [15:02<1:03:38, 21.41it/s]

 19%|█▉        | 18894/100629 [15:02<1:04:33, 21.10it/s]

 19%|█▉        | 18897/100629 [15:03<1:03:40, 21.39it/s]

 19%|█▉        | 18900/100629 [15:03<1:02:06, 21.93it/s]

 19%|█▉        | 18903/100629 [15:03<1:06:00, 20.64it/s]

 19%|█▉        | 18906/100629 [15:03<1:06:48, 20.39it/s]

 19%|█▉        | 18909/100629 [15:03<1:06:08, 20.59it/s]

 19%|█▉        | 18912/100629 [15:03<1:04:48, 21.01it/s]

 19%|█▉        | 18915/100629 [15:03<1:06:36, 20.45it/s]

 19%|█▉        | 18918/100629 [15:04<1:19:43, 17.08it/s]

 19%|█▉        | 18922/100629 [15:04<1:09:20, 19.64it/s]

 19%|█▉        | 18926/100629 [15:04<1:04:23, 21.15it/s]

 19%|█▉        | 18929/100629 [15:04<1:00:56, 22.34it/s]

 19%|█▉        | 18934/100629 [15:04<53:20, 25.53it/s]

 19%|█▉        | 18937/100629 [15:04<53:38, 25.38it/s]

 19%|█▉        | 18940/100629 [15:05<55:09, 24.68it/s]

 19%|█▉        | 18943/100629 [15:05<58:54, 23.11it/s]

 19%|█▉        | 18947/100629 [15:05<51:03, 26.66it/s]

 19%|█▉        | 18950/100629 [15:05<58:21, 23.32it/s]

 19%|█▉        | 18953/100629 [15:05<55:43, 24.43it/s]

 19%|█▉        | 18957/100629 [15:05<50:07, 27.15it/s]

 19%|█▉        | 18960/100629 [15:05<53:23, 25.49it/s]

 19%|█▉        | 18964/100629 [15:05<48:51, 27.86it/s]

 19%|█▉        | 18967/100629 [15:06<58:04, 23.44it/s]

 19%|█▉        | 18970/100629 [15:06<56:13, 24.21it/s]

 19%|█▉        | 18973/100629 [15:06<58:01, 23.46it/s]

 19%|█▉        | 18976/100629 [15:06<58:04, 23.43it/s]

 19%|█▉        | 18979/100629 [15:06<59:21, 22.92it/s]

 19%|█▉        | 18982/100629 [15:06<1:04:04, 21.24it/s]

 19%|█▉        | 18985/100629 [15:06<1:03:32, 21.42it/s]

 19%|█▉        | 18988/100629 [15:07<1:11:05, 19.14it/s]

 19%|█▉        | 18990/100629 [15:07<1:13:10, 18.59it/s]

 19%|█▉        | 18993/100629 [15:07<1:10:50, 19.21it/s]

 19%|█▉        | 18995/100629 [15:07<1:11:42, 18.97it/s]

 19%|█▉        | 18998/100629 [15:07<1:06:15, 20.53it/s]

 19%|█▉        | 19001/100629 [15:07<1:17:57, 17.45it/s]

 19%|█▉        | 19004/100629 [15:08<1:20:08, 16.97it/s]

 19%|█▉        | 19006/100629 [15:08<1:24:39, 16.07it/s]

 19%|█▉        | 19008/100629 [15:08<1:29:54, 15.13it/s]

 19%|█▉        | 19011/100629 [15:08<1:27:13, 15.60it/s]

 19%|█▉        | 19014/100629 [15:08<1:13:59, 18.38it/s]

 19%|█▉        | 19017/100629 [15:08<1:05:27, 20.78it/s]

 19%|█▉        | 19020/100629 [15:08<1:17:26, 17.56it/s]

 19%|█▉        | 19023/100629 [15:09<1:17:19, 17.59it/s]

 19%|█▉        | 19026/100629 [15:09<1:19:31, 17.10it/s]

 19%|█▉        | 19029/100629 [15:09<1:14:27, 18.27it/s]

 19%|█▉        | 19031/100629 [15:09<1:14:20, 18.29it/s]

 19%|█▉        | 19033/100629 [15:09<1:15:35, 17.99it/s]

 19%|█▉        | 19037/100629 [15:09<1:07:51, 20.04it/s]

 19%|█▉        | 19040/100629 [15:09<1:02:48, 21.65it/s]

 19%|█▉        | 19043/100629 [15:10<59:17, 22.94it/s]

 19%|█▉        | 19046/100629 [15:10<1:16:01, 17.89it/s]

 19%|█▉        | 19049/100629 [15:10<1:07:51, 20.04it/s]

 19%|█▉        | 19053/100629 [15:10<58:37, 23.19it/s]

 19%|█▉        | 19056/100629 [15:10<55:10, 24.64it/s]

 19%|█▉        | 19059/100629 [15:10<1:08:23, 19.88it/s]

 19%|█▉        | 19062/100629 [15:11<1:10:37, 19.25it/s]

 19%|█▉        | 19065/100629 [15:11<1:10:27, 19.29it/s]

 19%|█▉        | 19068/100629 [15:11<1:10:41, 19.23it/s]

 19%|█▉        | 19071/100629 [15:11<1:04:09, 21.19it/s]

 19%|█▉        | 19074/100629 [15:11<1:06:15, 20.52it/s]

 19%|█▉        | 19077/100629 [15:11<1:17:49, 17.47it/s]

 19%|█▉        | 19080/100629 [15:12<1:12:14, 18.81it/s]

 19%|█▉        | 19084/100629 [15:12<1:08:50, 19.74it/s]

 19%|█▉        | 19087/100629 [15:12<1:14:49, 18.16it/s]

 19%|█▉        | 19089/100629 [15:12<1:21:39, 16.64it/s]

 19%|█▉        | 19092/100629 [15:12<1:18:58, 17.21it/s]

 19%|█▉        | 19095/100629 [15:12<1:14:27, 18.25it/s]

 19%|█▉        | 19098/100629 [15:12<1:09:52, 19.45it/s]

 19%|█▉        | 19101/100629 [15:13<1:05:00, 20.90it/s]

 19%|█▉        | 19105/100629 [15:13<53:55, 25.20it/s]

 19%|█▉        | 19109/100629 [15:13<48:20, 28.10it/s]

 19%|█▉        | 19112/100629 [15:13<55:03, 24.68it/s]

 19%|█▉        | 19115/100629 [15:13<1:00:14, 22.55it/s]

 19%|█▉        | 19118/100629 [15:13<1:13:30, 18.48it/s]

 19%|█▉        | 19121/100629 [15:14<1:15:38, 17.96it/s]

 19%|█▉        | 19125/100629 [15:14<1:07:55, 20.00it/s]

 19%|█▉        | 19128/100629 [15:14<1:10:06, 19.37it/s]

 19%|█▉        | 19131/100629 [15:14<1:16:11, 17.83it/s]

 19%|█▉        | 19133/100629 [15:14<1:17:18, 17.57it/s]

 19%|█▉        | 19137/100629 [15:14<1:04:16, 21.13it/s]

 19%|█▉        | 19141/100629 [15:14<58:33, 23.20it/s]

 19%|█▉        | 19144/100629 [15:15<1:08:29, 19.83it/s]

 19%|█▉        | 19147/100629 [15:15<1:08:53, 19.71it/s]

 19%|█▉        | 19152/100629 [15:15<56:52, 23.87it/s]

 19%|█▉        | 19155/100629 [15:15<55:01, 24.68it/s]

 19%|█▉        | 19159/100629 [15:15<52:32, 25.84it/s]

 19%|█▉        | 19163/100629 [15:15<50:28, 26.90it/s]

 19%|█▉        | 19166/100629 [15:16<1:02:54, 21.58it/s]

 19%|█▉        | 19169/100629 [15:16<1:05:02, 20.88it/s]

 19%|█▉        | 19172/100629 [15:16<1:16:04, 17.85it/s]

 19%|█▉        | 19174/100629 [15:16<1:22:12, 16.51it/s]

 19%|█▉        | 19177/100629 [15:16<1:11:44, 18.92it/s]

 19%|█▉        | 19180/100629 [15:16<1:11:25, 19.00it/s]

 19%|█▉        | 19183/100629 [15:17<1:14:21, 18.26it/s]

 19%|█▉        | 19185/100629 [15:17<1:20:33, 16.85it/s]

 19%|█▉        | 19188/100629 [15:17<1:15:35, 17.96it/s]

 19%|█▉        | 19191/100629 [15:17<1:12:44, 18.66it/s]

 19%|█▉        | 19193/100629 [15:17<1:19:49, 17.00it/s]

 19%|█▉        | 19195/100629 [15:17<1:30:17, 15.03it/s]

 19%|█▉        | 19198/100629 [15:17<1:19:30, 17.07it/s]

 19%|█▉        | 19202/100629 [15:18<1:02:15, 21.80it/s]

 19%|█▉        | 19205/100629 [15:18<1:04:44, 20.96it/s]

 19%|█▉        | 19208/100629 [15:18<59:54, 22.65it/s]

 19%|█▉        | 19212/100629 [15:18<51:22, 26.41it/s]

 19%|█▉        | 19216/100629 [15:18<47:05, 28.81it/s]

 19%|█▉        | 19221/100629 [15:18<46:25, 29.23it/s]

 19%|█▉        | 19225/100629 [15:18<46:39, 29.07it/s]

 19%|█▉        | 19230/100629 [15:18<40:57, 33.13it/s]

 19%|█▉        | 19234/100629 [15:19<47:18, 28.67it/s]

 19%|█▉        | 19239/100629 [15:19<43:53, 30.91it/s]

 19%|█▉        | 19244/100629 [15:19<44:04, 30.78it/s]

 19%|█▉        | 19248/100629 [15:19<54:18, 24.98it/s]

 19%|█▉        | 19251/100629 [15:19<59:59, 22.61it/s]

 19%|█▉        | 19255/100629 [15:20<55:59, 24.22it/s]

 19%|█▉        | 19258/100629 [15:20<1:00:53, 22.27it/s]

 19%|█▉        | 19261/100629 [15:20<1:02:09, 21.82it/s]

 19%|█▉        | 19264/100629 [15:20<1:06:44, 20.32it/s]

 19%|█▉        | 19267/100629 [15:20<1:05:08, 20.82it/s]

 19%|█▉        | 19270/100629 [15:20<59:31, 22.78it/s]

 19%|█▉        | 19273/100629 [15:20<1:10:02, 19.36it/s]

 19%|█▉        | 19276/100629 [15:21<1:09:16, 19.57it/s]

 19%|█▉        | 19279/100629 [15:21<1:07:31, 20.08it/s]

 19%|█▉        | 19282/100629 [15:21<1:21:51, 16.56it/s]

 19%|█▉        | 19284/100629 [15:21<1:19:41, 17.01it/s]

 19%|█▉        | 19287/100629 [15:21<1:17:13, 17.55it/s]

 19%|█▉        | 19289/100629 [15:21<1:23:36, 16.22it/s]

 19%|█▉        | 19292/100629 [15:22<1:14:57, 18.09it/s]

 19%|█▉        | 19295/100629 [15:22<1:12:56, 18.59it/s]

 19%|█▉        | 19298/100629 [15:22<1:11:21, 18.99it/s]

 19%|█▉        | 19301/100629 [15:22<1:08:00, 19.93it/s]

 19%|█▉        | 19304/100629 [15:22<1:05:56, 20.55it/s]

 19%|█▉        | 19307/100629 [15:22<1:03:31, 21.34it/s]

 19%|█▉        | 19310/100629 [15:22<1:09:46, 19.42it/s]

 19%|█▉        | 19312/100629 [15:23<1:12:11, 18.78it/s]

 19%|█▉        | 19315/100629 [15:23<1:08:50, 19.69it/s]

 19%|█▉        | 19318/100629 [15:23<1:01:46, 21.94it/s]

 19%|█▉        | 19323/100629 [15:23<49:25, 27.42it/s]

 19%|█▉        | 19326/100629 [15:23<48:21, 28.02it/s]

 19%|█▉        | 19329/100629 [15:23<48:03, 28.20it/s]

 19%|█▉        | 19333/100629 [15:23<47:08, 28.74it/s]

 19%|█▉        | 19337/100629 [15:23<44:20, 30.56it/s]

 19%|█▉        | 19341/100629 [15:24<47:32, 28.50it/s]

 19%|█▉        | 19344/100629 [15:24<51:14, 26.44it/s]

 19%|█▉        | 19347/100629 [15:24<54:14, 24.97it/s]

 19%|█▉        | 19350/100629 [15:24<1:02:33, 21.65it/s]

 19%|█▉        | 19354/100629 [15:24<56:29, 23.98it/s]

 19%|█▉        | 19357/100629 [15:24<1:00:46, 22.29it/s]

 19%|█▉        | 19360/100629 [15:24<1:05:37, 20.64it/s]

 19%|█▉        | 19363/100629 [15:25<1:04:09, 21.11it/s]

 19%|█▉        | 19366/100629 [15:25<1:08:09, 19.87it/s]

 19%|█▉        | 19369/100629 [15:25<1:12:03, 18.79it/s]

 19%|█▉        | 19371/100629 [15:25<1:22:27, 16.42it/s]

 19%|█▉        | 19377/100629 [15:25<56:33, 23.94it/s]

 19%|█▉        | 19380/100629 [15:25<1:03:24, 21.36it/s]

 19%|█▉        | 19383/100629 [15:26<1:01:07, 22.15it/s]

 19%|█▉        | 19387/100629 [15:26<54:58, 24.63it/s]

 19%|█▉        | 19391/100629 [15:26<49:49, 27.18it/s]

 19%|█▉        | 19394/100629 [15:26<51:00, 26.54it/s]

 19%|█▉        | 19397/100629 [15:26<51:56, 26.06it/s]

 19%|█▉        | 19401/100629 [15:26<46:21, 29.20it/s]

 19%|█▉        | 19405/100629 [15:26<50:19, 26.90it/s]

 19%|█▉        | 19408/100629 [15:26<57:05, 23.71it/s]

 19%|█▉        | 19411/100629 [15:27<56:28, 23.97it/s]

 19%|█▉        | 19414/100629 [15:27<58:51, 23.00it/s]

 19%|█▉        | 19417/100629 [15:27<1:02:17, 21.73it/s]

 19%|█▉        | 19420/100629 [15:27<1:08:15, 19.83it/s]

 19%|█▉        | 19423/100629 [15:27<1:14:10, 18.25it/s]

 19%|█▉        | 19426/100629 [15:27<1:10:46, 19.12it/s]

 19%|█▉        | 19428/100629 [15:28<1:12:43, 18.61it/s]

 19%|█▉        | 19430/100629 [15:28<1:13:11, 18.49it/s]

 19%|█▉        | 19433/100629 [15:28<1:09:31, 19.46it/s]

 19%|█▉        | 19436/100629 [15:28<1:06:17, 20.41it/s]

 19%|█▉        | 19439/100629 [15:28<1:09:05, 19.58it/s]

 19%|█▉        | 19442/100629 [15:28<1:02:45, 21.56it/s]

 19%|█▉        | 19445/100629 [15:28<1:01:07, 22.13it/s]

 19%|█▉        | 19448/100629 [15:28<57:28, 23.54it/s]

 19%|█▉        | 19451/100629 [15:29<57:40, 23.46it/s]

 19%|█▉        | 19454/100629 [15:29<57:50, 23.39it/s]

 19%|█▉        | 19457/100629 [15:29<1:02:28, 21.65it/s]

 19%|█▉        | 19460/100629 [15:29<1:00:02, 22.53it/s]

 19%|█▉        | 19463/100629 [15:29<1:07:48, 19.95it/s]

 19%|█▉        | 19466/100629 [15:29<1:10:50, 19.09it/s]

 19%|█▉        | 19468/100629 [15:29<1:15:02, 18.02it/s]

 19%|█▉        | 19470/100629 [15:30<1:13:59, 18.28it/s]

 19%|█▉        | 19472/100629 [15:30<1:16:04, 17.78it/s]

 19%|█▉        | 19475/100629 [15:30<1:06:15, 20.41it/s]

 19%|█▉        | 19478/100629 [15:30<1:03:30, 21.30it/s]

 19%|█▉        | 19481/100629 [15:30<1:06:46, 20.25it/s]

 19%|█▉        | 19484/100629 [15:30<1:00:54, 22.21it/s]

 19%|█▉        | 19487/100629 [15:30<58:08, 23.26it/s]

 19%|█▉        | 19490/100629 [15:31<1:15:50, 17.83it/s]

 19%|█▉        | 19493/100629 [15:31<1:15:40, 17.87it/s]

 19%|█▉        | 19495/100629 [15:31<1:16:53, 17.59it/s]

 19%|█▉        | 19500/100629 [15:31<58:38, 23.05it/s]

 19%|█▉        | 19503/100629 [15:31<57:25, 23.54it/s]

 19%|█▉        | 19506/100629 [15:31<56:32, 23.91it/s]

 19%|█▉        | 19509/100629 [15:31<56:01, 24.13it/s]

 19%|█▉        | 19512/100629 [15:32<59:24, 22.76it/s]

 19%|█▉        | 19515/100629 [15:32<1:01:58, 21.82it/s]

 19%|█▉        | 19519/100629 [15:32<54:52, 24.63it/s]

 19%|█▉        | 19522/100629 [15:32<54:06, 24.98it/s]

 19%|█▉        | 19525/100629 [15:32<56:29, 23.93it/s]

 19%|█▉        | 19529/100629 [15:32<49:44, 27.17it/s]

 19%|█▉        | 19532/100629 [15:32<58:08, 23.25it/s]

 19%|█▉        | 19535/100629 [15:33<1:06:58, 20.18it/s]

 19%|█▉        | 19539/100629 [15:33<58:48, 22.98it/s]

 19%|█▉        | 19542/100629 [15:33<1:06:31, 20.32it/s]

 19%|█▉        | 19545/100629 [15:33<1:06:37, 20.28it/s]

 19%|█▉        | 19548/100629 [15:33<1:08:13, 19.81it/s]

 19%|█▉        | 19551/100629 [15:33<1:13:37, 18.35it/s]

 19%|█▉        | 19554/100629 [15:33<1:09:11, 19.53it/s]

 19%|█▉        | 19557/100629 [15:34<1:16:30, 17.66it/s]

 19%|█▉        | 19560/100629 [15:34<1:21:57, 16.49it/s]

 19%|█▉        | 19563/100629 [15:34<1:13:53, 18.28it/s]

 19%|█▉        | 19566/100629 [15:34<1:05:51, 20.51it/s]

 19%|█▉        | 19569/100629 [15:34<1:02:06, 21.75it/s]

 19%|█▉        | 19572/100629 [15:34<1:11:56, 18.78it/s]

 19%|█▉        | 19575/100629 [15:35<1:18:37, 17.18it/s]

 19%|█▉        | 19579/100629 [15:35<1:09:14, 19.51it/s]

 19%|█▉        | 19582/100629 [15:35<1:10:42, 19.10it/s]

 19%|█▉        | 19586/100629 [15:35<1:03:45, 21.19it/s]

 19%|█▉        | 19589/100629 [15:35<1:02:11, 21.72it/s]

 19%|█▉        | 19592/100629 [15:35<1:09:48, 19.35it/s]

 19%|█▉        | 19596/100629 [15:36<1:01:33, 21.94it/s]

 19%|█▉        | 19599/100629 [15:36<57:06, 23.65it/s]

 19%|█▉        | 19602/100629 [15:36<1:01:00, 22.13it/s]

 19%|█▉        | 19605/100629 [15:36<1:00:06, 22.46it/s]

 19%|█▉        | 19608/100629 [15:36<1:22:09, 16.44it/s]

 19%|█▉        | 19610/100629 [15:37<1:37:35, 13.84it/s]

 19%|█▉        | 19612/100629 [15:37<1:30:52, 14.86it/s]

 19%|█▉        | 19615/100629 [15:37<1:19:44, 16.93it/s]

 19%|█▉        | 19619/100629 [15:37<1:06:04, 20.43it/s]

 19%|█▉        | 19622/100629 [15:37<1:03:18, 21.33it/s]

 20%|█▉        | 19625/100629 [15:37<1:00:39, 22.26it/s]

 20%|█▉        | 19629/100629 [15:37<59:47, 22.58it/s]

 20%|█▉        | 19632/100629 [15:38<1:07:58, 19.86it/s]

 20%|█▉        | 19635/100629 [15:38<1:15:12, 17.95it/s]

 20%|█▉        | 19637/100629 [15:38<1:19:45, 16.92it/s]

 20%|█▉        | 19640/100629 [15:38<1:11:17, 18.93it/s]

 20%|█▉        | 19643/100629 [15:38<1:06:25, 20.32it/s]

 20%|█▉        | 19646/100629 [15:38<1:15:36, 17.85it/s]

 20%|█▉        | 19648/100629 [15:38<1:18:33, 17.18it/s]

 20%|█▉        | 19651/100629 [15:39<1:14:59, 18.00it/s]

 20%|█▉        | 19653/100629 [15:39<1:26:48, 15.55it/s]

 20%|█▉        | 19656/100629 [15:39<1:29:42, 15.04it/s]

 20%|█▉        | 19658/100629 [15:39<1:27:31, 15.42it/s]

 20%|█▉        | 19660/100629 [15:39<1:29:02, 15.15it/s]

 20%|█▉        | 19663/100629 [15:39<1:15:54, 17.78it/s]

 20%|█▉        | 19666/100629 [15:40<1:11:11, 18.95it/s]

 20%|█▉        | 19670/100629 [15:40<1:00:21, 22.35it/s]

 20%|█▉        | 19675/100629 [15:40<59:23, 22.72it/s]

 20%|█▉        | 19678/100629 [15:40<56:08, 24.03it/s]

 20%|█▉        | 19681/100629 [15:40<55:15, 24.42it/s]

 20%|█▉        | 19684/100629 [15:40<1:03:58, 21.09it/s]

 20%|█▉        | 19687/100629 [15:40<1:04:52, 20.79it/s]

 20%|█▉        | 19690/100629 [15:41<1:25:20, 15.81it/s]

 20%|█▉        | 19692/100629 [15:41<1:21:47, 16.49it/s]

 20%|█▉        | 19695/100629 [15:41<1:11:17, 18.92it/s]

 20%|█▉        | 19699/100629 [15:41<1:00:36, 22.26it/s]

 20%|█▉        | 19702/100629 [15:41<1:16:59, 17.52it/s]

 20%|█▉        | 19706/100629 [15:41<1:09:47, 19.32it/s]

 20%|█▉        | 19709/100629 [15:42<1:10:13, 19.21it/s]

 20%|█▉        | 19712/100629 [15:42<1:03:46, 21.15it/s]

 20%|█▉        | 19715/100629 [15:42<1:10:08, 19.23it/s]

 20%|█▉        | 19718/100629 [15:42<1:12:39, 18.56it/s]

 20%|█▉        | 19720/100629 [15:42<1:23:59, 16.06it/s]

 20%|█▉        | 19723/100629 [15:42<1:14:35, 18.08it/s]

 20%|█▉        | 19725/100629 [15:43<1:20:24, 16.77it/s]

 20%|█▉        | 19727/100629 [15:43<1:23:45, 16.10it/s]

 20%|█▉        | 19729/100629 [15:43<1:21:19, 16.58it/s]

 20%|█▉        | 19732/100629 [15:43<1:16:48, 17.55it/s]

 20%|█▉        | 19735/100629 [15:43<1:10:40, 19.08it/s]

 20%|█▉        | 19739/100629 [15:43<57:52, 23.29it/s]

 20%|█▉        | 19742/100629 [15:43<54:57, 24.53it/s]

 20%|█▉        | 19745/100629 [15:43<57:40, 23.37it/s]

 20%|█▉        | 19748/100629 [15:44<57:30, 23.44it/s]

 20%|█▉        | 19751/100629 [15:44<55:07, 24.46it/s]

 20%|█▉        | 19754/100629 [15:44<59:19, 22.72it/s]

 20%|█▉        | 19757/100629 [15:44<1:11:39, 18.81it/s]

 20%|█▉        | 19760/100629 [15:44<1:16:30, 17.62it/s]

 20%|█▉        | 19762/100629 [15:44<1:21:25, 16.55it/s]

 20%|█▉        | 19764/100629 [15:45<1:21:59, 16.44it/s]

 20%|█▉        | 19766/100629 [15:45<1:19:39, 16.92it/s]

 20%|█▉        | 19768/100629 [15:45<1:17:51, 17.31it/s]

 20%|█▉        | 19770/100629 [15:45<1:17:24, 17.41it/s]

 20%|█▉        | 19773/100629 [15:45<1:12:28, 18.59it/s]

 20%|█▉        | 19776/100629 [15:45<1:05:33, 20.56it/s]

 20%|█▉        | 19779/100629 [15:45<59:55, 22.49it/s]

 20%|█▉        | 19783/100629 [15:45<53:27, 25.21it/s]

 20%|█▉        | 19787/100629 [15:45<48:08, 27.99it/s]

 20%|█▉        | 19791/100629 [15:46<45:06, 29.86it/s]

 20%|█▉        | 19795/100629 [15:46<48:36, 27.71it/s]

 20%|█▉        | 19798/100629 [15:46<48:46, 27.62it/s]

 20%|█▉        | 19801/100629 [15:46<1:02:41, 21.49it/s]

 20%|█▉        | 19804/100629 [15:46<1:09:52, 19.28it/s]

 20%|█▉        | 19808/100629 [15:46<1:01:04, 22.06it/s]

 20%|█▉        | 19811/100629 [15:47<57:42, 23.34it/s]

 20%|█▉        | 19814/100629 [15:47<1:01:54, 21.76it/s]

 20%|█▉        | 19817/100629 [15:47<1:01:19, 21.96it/s]

 20%|█▉        | 19820/100629 [15:47<1:10:03, 19.22it/s]

 20%|█▉        | 19823/100629 [15:47<1:10:19, 19.15it/s]

 20%|█▉        | 19825/100629 [15:47<1:20:26, 16.74it/s]

 20%|█▉        | 19827/100629 [15:47<1:18:59, 17.05it/s]

 20%|█▉        | 19829/100629 [15:48<1:32:21, 14.58it/s]

 20%|█▉        | 19831/100629 [15:48<1:27:32, 15.38it/s]

 20%|█▉        | 19834/100629 [15:48<1:13:07, 18.42it/s]

 20%|█▉        | 19838/100629 [15:48<1:11:56, 18.72it/s]

 20%|█▉        | 19841/100629 [15:48<1:03:57, 21.05it/s]

 20%|█▉        | 19844/100629 [15:48<1:09:00, 19.51it/s]

 20%|█▉        | 19848/100629 [15:49<59:28, 22.64it/s]

 20%|█▉        | 19851/100629 [15:49<1:01:14, 21.99it/s]

 20%|█▉        | 19854/100629 [15:49<59:12, 22.74it/s]

 20%|█▉        | 19857/100629 [15:49<1:05:40, 20.50it/s]

 20%|█▉        | 19860/100629 [15:49<1:06:46, 20.16it/s]

 20%|█▉        | 19863/100629 [15:49<1:00:19, 22.31it/s]

 20%|█▉        | 19866/100629 [15:49<1:04:53, 20.74it/s]

 20%|█▉        | 19869/100629 [15:50<1:02:42, 21.47it/s]

 20%|█▉        | 19872/100629 [15:50<1:06:07, 20.36it/s]

 20%|█▉        | 19875/100629 [15:50<1:00:40, 22.18it/s]

 20%|█▉        | 19878/100629 [15:50<56:43, 23.73it/s]

 20%|█▉        | 19882/100629 [15:50<53:13, 25.29it/s]

 20%|█▉        | 19885/100629 [15:50<1:02:09, 21.65it/s]

 20%|█▉        | 19888/100629 [15:50<1:06:48, 20.14it/s]

 20%|█▉        | 19891/100629 [15:51<1:02:06, 21.67it/s]

 20%|█▉        | 19894/100629 [15:51<1:02:29, 21.53it/s]

 20%|█▉        | 19898/100629 [15:51<52:57, 25.40it/s]

 20%|█▉        | 19901/100629 [15:51<1:00:06, 22.39it/s]

 20%|█▉        | 19904/100629 [15:51<1:08:47, 19.56it/s]

 20%|█▉        | 19907/100629 [15:51<1:04:31, 20.85it/s]

 20%|█▉        | 19911/100629 [15:51<59:22, 22.66it/s]

 20%|█▉        | 19914/100629 [15:52<56:38, 23.75it/s]

 20%|█▉        | 19917/100629 [15:52<55:45, 24.12it/s]

 20%|█▉        | 19921/100629 [15:52<51:59, 25.87it/s]

 20%|█▉        | 19924/100629 [15:52<1:08:09, 19.74it/s]

 20%|█▉        | 19927/100629 [15:52<1:08:24, 19.66it/s]

 20%|█▉        | 19930/100629 [15:52<1:14:20, 18.09it/s]

 20%|█▉        | 19934/100629 [15:52<1:02:18, 21.59it/s]

 20%|█▉        | 19937/100629 [15:53<1:11:47, 18.73it/s]

 20%|█▉        | 19941/100629 [15:53<59:25, 22.63it/s]

 20%|█▉        | 19944/100629 [15:53<1:08:19, 19.68it/s]

 20%|█▉        | 19947/100629 [15:53<1:03:22, 21.22it/s]

 20%|█▉        | 19950/100629 [15:53<1:04:30, 20.84it/s]

 20%|█▉        | 19954/100629 [15:53<55:04, 24.41it/s]

 20%|█▉        | 19957/100629 [15:54<55:24, 24.26it/s]

 20%|█▉        | 19960/100629 [15:54<1:02:22, 21.55it/s]

 20%|█▉        | 19963/100629 [15:54<1:02:14, 21.60it/s]

 20%|█▉        | 19966/100629 [15:54<1:06:08, 20.33it/s]

 20%|█▉        | 19970/100629 [15:54<1:04:42, 20.77it/s]

 20%|█▉        | 19973/100629 [15:54<1:04:58, 20.69it/s]

 20%|█▉        | 19976/100629 [15:54<1:04:39, 20.79it/s]

 20%|█▉        | 19979/100629 [15:55<1:00:00, 22.40it/s]

 20%|█▉        | 19982/100629 [15:55<1:15:22, 17.83it/s]

 20%|█▉        | 19986/100629 [15:55<1:03:35, 21.14it/s]

 20%|█▉        | 19989/100629 [15:55<59:33, 22.56it/s]

 20%|█▉        | 19992/100629 [15:55<1:01:11, 21.96it/s]

 20%|█▉        | 19995/100629 [15:55<1:00:33, 22.19it/s]

 20%|█▉        | 20000/100629 [15:56<53:12, 25.25it/s]

 20%|█▉        | 20003/100629 [15:56<1:04:17, 20.90it/s]

 20%|█▉        | 20006/100629 [15:56<1:06:06, 20.33it/s]

 20%|█▉        | 20009/100629 [15:56<1:08:47, 19.53it/s]

 20%|█▉        | 20013/100629 [15:56<59:03, 22.75it/s]

 20%|█▉        | 20017/100629 [15:56<51:05, 26.30it/s]

 20%|█▉        | 20020/100629 [15:56<56:16, 23.87it/s]

 20%|█▉        | 20023/100629 [15:57<57:24, 23.40it/s]

 20%|█▉        | 20026/100629 [15:57<56:02, 23.97it/s]

 20%|█▉        | 20029/100629 [15:57<56:45, 23.67it/s]

 20%|█▉        | 20032/100629 [15:57<55:43, 24.11it/s]

 20%|█▉        | 20035/100629 [15:57<59:10, 22.70it/s]

 20%|█▉        | 20038/100629 [15:57<1:03:38, 21.11it/s]

 20%|█▉        | 20041/100629 [15:57<59:13, 22.68it/s]

 20%|█▉        | 20044/100629 [15:57<55:39, 24.13it/s]

 20%|█▉        | 20047/100629 [15:58<53:16, 25.21it/s]

 20%|█▉        | 20051/100629 [15:58<59:18, 22.64it/s]

 20%|█▉        | 20054/100629 [15:58<59:15, 22.66it/s]

 20%|█▉        | 20057/100629 [15:58<58:19, 23.02it/s]

 20%|█▉        | 20061/100629 [15:58<54:59, 24.42it/s]

 20%|█▉        | 20065/100629 [15:58<55:49, 24.05it/s]

 20%|█▉        | 20068/100629 [15:58<55:37, 24.14it/s]

 20%|█▉        | 20071/100629 [15:59<1:00:21, 22.25it/s]

 20%|█▉        | 20074/100629 [15:59<1:09:11, 19.40it/s]

 20%|█▉        | 20078/100629 [15:59<56:54, 23.59it/s]

 20%|█▉        | 20081/100629 [15:59<56:16, 23.86it/s]

 20%|█▉        | 20084/100629 [15:59<58:37, 22.90it/s]

 20%|█▉        | 20088/100629 [15:59<52:42, 25.47it/s]

 20%|█▉        | 20091/100629 [16:00<1:00:16, 22.27it/s]

 20%|█▉        | 20094/100629 [16:00<1:00:44, 22.10it/s]

 20%|█▉        | 20097/100629 [16:00<59:25, 22.59it/s]

 20%|█▉        | 20100/100629 [16:00<55:36, 24.14it/s]

 20%|█▉        | 20104/100629 [16:00<1:05:04, 20.63it/s]

 20%|█▉        | 20107/100629 [16:00<1:12:49, 18.43it/s]

 20%|█▉        | 20110/100629 [16:01<1:16:22, 17.57it/s]

 20%|█▉        | 20112/100629 [16:01<1:22:25, 16.28it/s]

 20%|█▉        | 20115/100629 [16:01<1:12:28, 18.51it/s]

 20%|█▉        | 20118/100629 [16:01<1:07:40, 19.83it/s]

 20%|█▉        | 20122/100629 [16:01<56:00, 23.95it/s]

 20%|█▉        | 20125/100629 [16:01<56:18, 23.82it/s]

 20%|██        | 20128/100629 [16:01<56:49, 23.61it/s]

 20%|██        | 20131/100629 [16:01<1:03:30, 21.12it/s]

 20%|██        | 20135/100629 [16:02<1:00:39, 22.12it/s]

 20%|██        | 20138/100629 [16:02<1:12:48, 18.43it/s]

 20%|██        | 20141/100629 [16:02<1:05:37, 20.44it/s]

 20%|██        | 20145/100629 [16:02<54:44, 24.51it/s]

 20%|██        | 20148/100629 [16:02<56:29, 23.74it/s]

 20%|██        | 20151/100629 [16:02<57:22, 23.38it/s]

 20%|██        | 20154/100629 [16:03<1:02:38, 21.41it/s]

 20%|██        | 20157/100629 [16:03<1:03:48, 21.02it/s]

 20%|██        | 20160/100629 [16:03<1:10:24, 19.05it/s]

 20%|██        | 20162/100629 [16:03<1:11:32, 18.75it/s]

 20%|██        | 20165/100629 [16:03<1:10:32, 19.01it/s]

 20%|██        | 20169/100629 [16:03<1:01:14, 21.90it/s]

 20%|██        | 20172/100629 [16:03<57:00, 23.52it/s]

 20%|██        | 20176/100629 [16:03<50:19, 26.64it/s]

 20%|██        | 20179/100629 [16:04<59:37, 22.49it/s]

 20%|██        | 20182/100629 [16:04<1:06:04, 20.29it/s]

 20%|██        | 20185/100629 [16:04<1:16:45, 17.47it/s]

 20%|██        | 20187/100629 [16:04<1:14:46, 17.93it/s]

 20%|██        | 20189/100629 [16:04<1:19:07, 16.94it/s]

 20%|██        | 20192/100629 [16:04<1:14:16, 18.05it/s]

 20%|██        | 20195/100629 [16:05<1:08:56, 19.44it/s]

 20%|██        | 20198/100629 [16:05<1:14:20, 18.03it/s]

 20%|██        | 20201/100629 [16:05<1:06:18, 20.22it/s]

 20%|██        | 20205/100629 [16:05<56:36, 23.68it/s]

 20%|██        | 20210/100629 [16:05<47:17, 28.34it/s]

 20%|██        | 20214/100629 [16:05<47:59, 27.93it/s]

 20%|██        | 20217/100629 [16:05<47:52, 27.99it/s]

 20%|██        | 20221/100629 [16:06<48:12, 27.80it/s]

 20%|██        | 20224/100629 [16:06<49:13, 27.22it/s]

 20%|██        | 20227/100629 [16:06<49:40, 26.98it/s]

 20%|██        | 20230/100629 [16:06<1:00:29, 22.15it/s]

 20%|██        | 20234/100629 [16:06<55:03, 24.34it/s]

 20%|██        | 20238/100629 [16:06<1:00:52, 22.01it/s]

 20%|██        | 20241/100629 [16:06<56:49, 23.58it/s]

 20%|██        | 20244/100629 [16:07<59:52, 22.38it/s]

 20%|██        | 20247/100629 [16:07<1:02:55, 21.29it/s]

 20%|██        | 20250/100629 [16:07<1:06:55, 20.02it/s]

 20%|██        | 20253/100629 [16:07<1:10:06, 19.11it/s]

 20%|██        | 20257/100629 [16:07<57:49, 23.16it/s]

 20%|██        | 20260/100629 [16:07<56:14, 23.82it/s]

 20%|██        | 20263/100629 [16:08<1:04:55, 20.63it/s]

 20%|██        | 20266/100629 [16:08<1:08:34, 19.53it/s]

 20%|██        | 20269/100629 [16:08<1:12:31, 18.47it/s]

 20%|██        | 20272/100629 [16:08<1:05:39, 20.40it/s]

 20%|██        | 20276/100629 [16:08<58:30, 22.89it/s]

 20%|██        | 20279/100629 [16:08<58:39, 22.83it/s]

 20%|██        | 20282/100629 [16:08<1:01:31, 21.77it/s]

 20%|██        | 20285/100629 [16:08<56:40, 23.63it/s]

 20%|██        | 20289/100629 [16:09<50:10, 26.68it/s]

 20%|██        | 20293/100629 [16:09<48:23, 27.67it/s]

 20%|██        | 20296/100629 [16:09<58:50, 22.76it/s]

 20%|██        | 20300/100629 [16:09<53:16, 25.13it/s]

 20%|██        | 20303/100629 [16:09<55:06, 24.29it/s]

 20%|██        | 20306/100629 [16:09<1:00:43, 22.05it/s]

 20%|██        | 20309/100629 [16:10<1:18:40, 17.01it/s]

 20%|██        | 20311/100629 [16:10<1:19:49, 16.77it/s]

 20%|██        | 20314/100629 [16:10<1:10:44, 18.92it/s]

 20%|██        | 20317/100629 [16:10<1:06:20, 20.18it/s]

 20%|██        | 20320/100629 [16:10<1:06:26, 20.15it/s]

 20%|██        | 20323/100629 [16:10<1:05:24, 20.46it/s]

 20%|██        | 20326/100629 [16:10<1:01:32, 21.75it/s]

 20%|██        | 20329/100629 [16:11<59:45, 22.40it/s]

 20%|██        | 20333/100629 [16:11<53:12, 25.15it/s]

 20%|██        | 20336/100629 [16:11<1:04:05, 20.88it/s]

 20%|██        | 20339/100629 [16:11<1:10:06, 19.09it/s]

 20%|██        | 20342/100629 [16:11<1:13:45, 18.14it/s]

 20%|██        | 20344/100629 [16:11<1:16:02, 17.60it/s]

 20%|██        | 20346/100629 [16:12<1:20:48, 16.56it/s]

 20%|██        | 20348/100629 [16:12<1:18:16, 17.09it/s]

 20%|██        | 20351/100629 [16:12<1:07:50, 19.72it/s]

 20%|██        | 20354/100629 [16:12<1:16:29, 17.49it/s]

 20%|██        | 20356/100629 [16:12<1:23:53, 15.95it/s]

 20%|██        | 20358/100629 [16:12<1:22:49, 16.15it/s]

 20%|██        | 20362/100629 [16:12<1:07:40, 19.77it/s]

 20%|██        | 20365/100629 [16:12<1:02:26, 21.43it/s]

 20%|██        | 20368/100629 [16:13<57:09, 23.40it/s]

 20%|██        | 20372/100629 [16:13<57:03, 23.44it/s]

 20%|██        | 20375/100629 [16:13<1:00:59, 21.93it/s]

 20%|██        | 20378/100629 [16:13<59:18, 22.55it/s]

 20%|██        | 20381/100629 [16:13<59:54, 22.33it/s]

 20%|██        | 20384/100629 [16:13<1:01:16, 21.83it/s]

 20%|██        | 20387/100629 [16:13<1:00:02, 22.28it/s]

 20%|██        | 20390/100629 [16:14<1:00:31, 22.10it/s]

 20%|██        | 20396/100629 [16:14<44:23, 30.12it/s]

 20%|██        | 20401/100629 [16:14<40:49, 32.76it/s]

 20%|██        | 20405/100629 [16:14<49:26, 27.04it/s]

 20%|██        | 20408/100629 [16:14<49:20, 27.09it/s]

 20%|██        | 20411/100629 [16:14<50:12, 26.63it/s]

 20%|██        | 20414/100629 [16:14<53:34, 24.96it/s]

 20%|██        | 20417/100629 [16:15<55:46, 23.97it/s]

 20%|██        | 20420/100629 [16:15<1:03:28, 21.06it/s]

 20%|██        | 20423/100629 [16:15<1:08:43, 19.45it/s]

 20%|██        | 20426/100629 [16:15<1:11:21, 18.73it/s]

 20%|██        | 20428/100629 [16:15<1:18:06, 17.11it/s]

 20%|██        | 20431/100629 [16:15<1:08:10, 19.61it/s]

 20%|██        | 20434/100629 [16:16<1:08:06, 19.62it/s]

 20%|██        | 20437/100629 [16:16<1:10:05, 19.07it/s]

 20%|██        | 20440/100629 [16:16<1:07:52, 19.69it/s]

 20%|██        | 20443/100629 [16:16<1:08:03, 19.63it/s]

 20%|██        | 20445/100629 [16:16<1:09:55, 19.11it/s]

 20%|██        | 20447/100629 [16:16<1:16:17, 17.52it/s]

 20%|██        | 20450/100629 [16:16<1:10:40, 18.91it/s]

 20%|██        | 20452/100629 [16:16<1:12:52, 18.34it/s]

 20%|██        | 20454/100629 [16:17<1:23:00, 16.10it/s]

 20%|██        | 20458/100629 [16:17<1:02:27, 21.39it/s]

 20%|██        | 20461/100629 [16:17<1:07:43, 19.73it/s]

 20%|██        | 20464/100629 [16:17<1:02:26, 21.39it/s]

 20%|██        | 20467/100629 [16:17<1:10:51, 18.86it/s]

 20%|██        | 20470/100629 [16:17<1:05:10, 20.50it/s]

 20%|██        | 20474/100629 [16:17<55:52, 23.91it/s]

 20%|██        | 20477/100629 [16:18<1:04:38, 20.66it/s]

 20%|██        | 20482/100629 [16:18<1:00:42, 22.00it/s]

 20%|██        | 20485/100629 [16:18<1:03:17, 21.10it/s]

 20%|██        | 20488/100629 [16:18<1:04:40, 20.65it/s]

 20%|██        | 20491/100629 [16:18<1:17:13, 17.29it/s]

 20%|██        | 20495/100629 [16:19<1:04:16, 20.78it/s]

 20%|██        | 20498/100629 [16:19<1:06:27, 20.10it/s]

 20%|██        | 20502/100629 [16:19<55:48, 23.93it/s]

 20%|██        | 20505/100629 [16:19<59:53, 22.30it/s]

 20%|██        | 20508/100629 [16:19<1:01:14, 21.80it/s]

 20%|██        | 20511/100629 [16:19<1:00:48, 21.96it/s]

 20%|██        | 20514/100629 [16:19<59:03, 22.61it/s]

 20%|██        | 20517/100629 [16:20<59:26, 22.46it/s]

 20%|██        | 20520/100629 [16:20<1:05:57, 20.24it/s]

 20%|██        | 20523/100629 [16:20<1:02:37, 21.32it/s]

 20%|██        | 20526/100629 [16:20<1:03:36, 20.99it/s]

 20%|██        | 20530/100629 [16:20<54:01, 24.71it/s]

 20%|██        | 20533/100629 [16:20<58:25, 22.85it/s]

 20%|██        | 20536/100629 [16:20<58:47, 22.71it/s]

 20%|██        | 20539/100629 [16:21<1:07:46, 19.70it/s]

 20%|██        | 20542/100629 [16:21<1:05:30, 20.37it/s]

 20%|██        | 20546/100629 [16:21<54:13, 24.62it/s]

 20%|██        | 20549/100629 [16:21<1:11:28, 18.67it/s]

 20%|██        | 20552/100629 [16:21<1:07:40, 19.72it/s]

 20%|██        | 20555/100629 [16:21<1:14:27, 17.92it/s]

 20%|██        | 20558/100629 [16:22<1:10:30, 18.93it/s]

 20%|██        | 20561/100629 [16:22<1:12:51, 18.32it/s]

 20%|██        | 20565/100629 [16:22<1:01:18, 21.76it/s]

 20%|██        | 20568/100629 [16:22<1:02:38, 21.30it/s]

 20%|██        | 20571/100629 [16:22<1:19:20, 16.82it/s]

 20%|██        | 20574/100629 [16:22<1:09:30, 19.19it/s]

 20%|██        | 20577/100629 [16:22<1:04:23, 20.72it/s]

 20%|██        | 20580/100629 [16:23<1:06:11, 20.16it/s]

 20%|██        | 20583/100629 [16:23<1:03:34, 20.98it/s]

 20%|██        | 20586/100629 [16:23<1:08:17, 19.53it/s]

 20%|██        | 20589/100629 [16:23<1:02:11, 21.45it/s]

 20%|██        | 20592/100629 [16:23<57:32, 23.18it/s]

 20%|██        | 20595/100629 [16:23<1:04:31, 20.68it/s]

 20%|██        | 20598/100629 [16:24<1:05:32, 20.35it/s]

 20%|██        | 20601/100629 [16:24<1:09:27, 19.20it/s]

 20%|██        | 20605/100629 [16:24<1:04:06, 20.81it/s]

 20%|██        | 20608/100629 [16:24<1:16:03, 17.53it/s]

 20%|██        | 20610/100629 [16:24<1:16:32, 17.42it/s]

 20%|██        | 20612/100629 [16:24<1:21:22, 16.39it/s]

 20%|██        | 20615/100629 [16:24<1:13:18, 18.19it/s]

 20%|██        | 20617/100629 [16:25<1:11:45, 18.58it/s]

 20%|██        | 20621/100629 [16:25<1:05:45, 20.28it/s]

 20%|██        | 20624/100629 [16:25<1:12:21, 18.43it/s]

 20%|██        | 20626/100629 [16:25<1:11:38, 18.61it/s]

 20%|██        | 20628/100629 [16:25<1:20:41, 16.52it/s]

 21%|██        | 20632/100629 [16:25<1:10:24, 18.94it/s]

 21%|██        | 20634/100629 [16:26<1:12:51, 18.30it/s]

 21%|██        | 20639/100629 [16:26<1:06:09, 20.15it/s]

 21%|██        | 20642/100629 [16:26<1:01:58, 21.51it/s]

 21%|██        | 20645/100629 [16:26<1:06:19, 20.10it/s]

 21%|██        | 20649/100629 [16:26<1:02:59, 21.16it/s]

 21%|██        | 20652/100629 [16:26<59:47, 22.29it/s]

 21%|██        | 20655/100629 [16:26<1:07:35, 19.72it/s]

 21%|██        | 20658/100629 [16:27<1:16:31, 17.42it/s]

 21%|██        | 20660/100629 [16:27<1:16:03, 17.52it/s]

 21%|██        | 20664/100629 [16:27<1:04:44, 20.58it/s]

 21%|██        | 20667/100629 [16:27<1:11:49, 18.56it/s]

 21%|██        | 20669/100629 [16:27<1:18:19, 17.02it/s]

 21%|██        | 20672/100629 [16:27<1:07:49, 19.65it/s]

 21%|██        | 20675/100629 [16:28<1:11:34, 18.62it/s]

 21%|██        | 20677/100629 [16:28<1:13:03, 18.24it/s]

 21%|██        | 20680/100629 [16:28<1:05:48, 20.25it/s]

 21%|██        | 20683/100629 [16:28<1:05:38, 20.30it/s]

 21%|██        | 20687/100629 [16:28<1:18:03, 17.07it/s]

 21%|██        | 20690/100629 [16:28<1:14:34, 17.86it/s]

 21%|██        | 20692/100629 [16:29<1:13:25, 18.14it/s]

 21%|██        | 20695/100629 [16:29<1:08:57, 19.32it/s]

 21%|██        | 20698/100629 [16:29<1:06:20, 20.08it/s]

 21%|██        | 20701/100629 [16:29<1:12:55, 18.27it/s]

 21%|██        | 20705/100629 [16:29<1:09:03, 19.29it/s]

 21%|██        | 20708/100629 [16:29<1:10:28, 18.90it/s]

 21%|██        | 20710/100629 [16:29<1:15:35, 17.62it/s]

 21%|██        | 20713/100629 [16:30<1:09:58, 19.03it/s]

 21%|██        | 20716/100629 [16:30<1:06:50, 19.92it/s]

 21%|██        | 20719/100629 [16:30<1:19:39, 16.72it/s]

 21%|██        | 20722/100629 [16:30<1:12:22, 18.40it/s]

 21%|██        | 20725/100629 [16:30<1:13:22, 18.15it/s]

 21%|██        | 20728/100629 [16:30<1:06:13, 20.11it/s]

 21%|██        | 20731/100629 [16:31<59:53, 22.23it/s]

 21%|██        | 20734/100629 [16:31<1:00:36, 21.97it/s]

 21%|██        | 20737/100629 [16:31<1:00:53, 21.87it/s]

 21%|██        | 20741/100629 [16:31<56:29, 23.57it/s]

 21%|██        | 20744/100629 [16:31<53:40, 24.81it/s]

 21%|██        | 20747/100629 [16:31<1:01:00, 21.82it/s]

 21%|██        | 20750/100629 [16:31<1:01:43, 21.57it/s]

 21%|██        | 20753/100629 [16:32<1:04:17, 20.71it/s]

 21%|██        | 20759/100629 [16:32<53:02, 25.10it/s]

 21%|██        | 20762/100629 [16:32<56:41, 23.48it/s]

 21%|██        | 20765/100629 [16:32<53:56, 24.68it/s]

 21%|██        | 20768/100629 [16:32<1:00:33, 21.98it/s]

 21%|██        | 20772/100629 [16:32<57:01, 23.34it/s]

 21%|██        | 20776/100629 [16:32<49:42, 26.77it/s]

 21%|██        | 20779/100629 [16:32<48:55, 27.21it/s]

 21%|██        | 20783/100629 [16:33<47:39, 27.92it/s]

 21%|██        | 20786/100629 [16:33<50:53, 26.15it/s]

 21%|██        | 20790/100629 [16:33<46:47, 28.44it/s]

 21%|██        | 20794/100629 [16:33<44:45, 29.73it/s]

 21%|██        | 20798/100629 [16:33<55:18, 24.06it/s]

 21%|██        | 20801/100629 [16:33<55:39, 23.90it/s]

 21%|██        | 20804/100629 [16:34<1:02:31, 21.28it/s]

 21%|██        | 20807/100629 [16:34<1:07:30, 19.70it/s]

 21%|██        | 20810/100629 [16:34<1:04:35, 20.59it/s]

 21%|██        | 20813/100629 [16:34<1:09:30, 19.14it/s]

 21%|██        | 20815/100629 [16:34<1:12:43, 18.29it/s]

 21%|██        | 20818/100629 [16:34<1:16:23, 17.41it/s]

 21%|██        | 20820/100629 [16:35<1:29:33, 14.85it/s]

 21%|██        | 20822/100629 [16:35<1:25:21, 15.58it/s]

 21%|██        | 20824/100629 [16:35<1:31:50, 14.48it/s]

 21%|██        | 20828/100629 [16:35<1:14:12, 17.92it/s]

 21%|██        | 20830/100629 [16:35<1:14:43, 17.80it/s]

 21%|██        | 20832/100629 [16:35<1:17:29, 17.16it/s]

 21%|██        | 20836/100629 [16:35<1:03:55, 20.81it/s]

 21%|██        | 20840/100629 [16:35<53:20, 24.93it/s]

 21%|██        | 20844/100629 [16:36<50:11, 26.50it/s]

 21%|██        | 20847/100629 [16:36<55:52, 23.80it/s]

 21%|██        | 20850/100629 [16:36<54:15, 24.51it/s]

 21%|██        | 20853/100629 [16:36<57:27, 23.14it/s]

 21%|██        | 20856/100629 [16:36<1:00:11, 22.09it/s]

 21%|██        | 20859/100629 [16:36<56:40, 23.46it/s]

 21%|██        | 20862/100629 [16:36<1:02:59, 21.11it/s]

 21%|██        | 20865/100629 [16:37<1:00:18, 22.04it/s]

 21%|██        | 20868/100629 [16:37<1:02:32, 21.25it/s]

 21%|██        | 20871/100629 [16:37<1:01:20, 21.67it/s]

 21%|██        | 20874/100629 [16:37<1:07:05, 19.81it/s]

 21%|██        | 20877/100629 [16:37<1:07:09, 19.79it/s]

 21%|██        | 20881/100629 [16:38<1:24:55, 15.65it/s]

 21%|██        | 20883/100629 [16:38<1:26:16, 15.40it/s]

 21%|██        | 20886/100629 [16:38<1:14:09, 17.92it/s]

 21%|██        | 20889/100629 [16:38<1:09:36, 19.09it/s]

 21%|██        | 20893/100629 [16:38<56:38, 23.46it/s]

 21%|██        | 20897/100629 [16:38<50:24, 26.36it/s]

 21%|██        | 20900/100629 [16:38<51:23, 25.85it/s]

 21%|██        | 20903/100629 [16:38<59:26, 22.35it/s]

 21%|██        | 20907/100629 [16:39<55:28, 23.95it/s]

 21%|██        | 20911/100629 [16:39<52:11, 25.46it/s]

 21%|██        | 20915/100629 [16:39<47:39, 27.87it/s]

 21%|██        | 20919/100629 [16:39<44:02, 30.17it/s]

 21%|██        | 20923/100629 [16:39<44:53, 29.59it/s]

 21%|██        | 20927/100629 [16:39<55:15, 24.04it/s]

 21%|██        | 20930/100629 [16:40<1:01:55, 21.45it/s]

 21%|██        | 20933/100629 [16:40<1:04:29, 20.59it/s]

 21%|██        | 20936/100629 [16:40<1:02:02, 21.41it/s]

 21%|██        | 20939/100629 [16:40<59:22, 22.37it/s]

 21%|██        | 20942/100629 [16:40<59:21, 22.38it/s]

 21%|██        | 20946/100629 [16:40<56:40, 23.43it/s]

 21%|██        | 20949/100629 [16:40<1:01:28, 21.60it/s]

 21%|██        | 20952/100629 [16:41<1:06:02, 20.11it/s]

 21%|██        | 20955/100629 [16:41<1:11:13, 18.64it/s]

 21%|██        | 20959/100629 [16:41<1:06:27, 19.98it/s]

 21%|██        | 20962/100629 [16:41<1:06:12, 20.06it/s]

 21%|██        | 20965/100629 [16:41<1:03:37, 20.87it/s]

 21%|██        | 20968/100629 [16:42<1:38:39, 13.46it/s]

 21%|██        | 20970/100629 [16:42<1:35:17, 13.93it/s]

 21%|██        | 20973/100629 [16:42<1:30:37, 14.65it/s]

 21%|██        | 20977/100629 [16:42<1:10:36, 18.80it/s]

 21%|██        | 20980/100629 [16:42<1:09:11, 19.18it/s]

 21%|██        | 20983/100629 [16:42<1:03:05, 21.04it/s]

 21%|██        | 20986/100629 [16:42<59:10, 22.43it/s]

 21%|██        | 20990/100629 [16:43<58:33, 22.67it/s]

 21%|██        | 20993/100629 [16:43<1:03:48, 20.80it/s]

 21%|██        | 20999/100629 [16:43<46:33, 28.51it/s]

 21%|██        | 21003/100629 [16:43<48:06, 27.58it/s]

 21%|██        | 21007/100629 [16:43<46:50, 28.33it/s]

 21%|██        | 21010/100629 [16:43<56:59, 23.28it/s]

 21%|██        | 21014/100629 [16:43<50:23, 26.33it/s]

 21%|██        | 21017/100629 [16:44<52:18, 25.37it/s]

 21%|██        | 21020/100629 [16:44<58:53, 22.53it/s]

 21%|██        | 21023/100629 [16:44<1:03:45, 20.81it/s]

 21%|██        | 21026/100629 [16:44<1:02:33, 21.21it/s]

 21%|██        | 21029/100629 [16:44<1:00:38, 21.88it/s]

 21%|██        | 21032/100629 [16:44<1:03:04, 21.03it/s]

 21%|██        | 21036/100629 [16:44<55:29, 23.90it/s]

 21%|██        | 21039/100629 [16:45<59:47, 22.19it/s]

 21%|██        | 21043/100629 [16:45<53:32, 24.78it/s]

 21%|██        | 21047/100629 [16:45<49:30, 26.79it/s]

 21%|██        | 21050/100629 [16:45<51:31, 25.74it/s]

 21%|██        | 21053/100629 [16:45<53:23, 24.84it/s]

 21%|██        | 21056/100629 [16:45<1:01:23, 21.60it/s]

 21%|██        | 21059/100629 [16:46<1:10:05, 18.92it/s]

 21%|██        | 21062/100629 [16:46<1:06:25, 19.96it/s]

 21%|██        | 21065/100629 [16:46<1:01:43, 21.48it/s]

 21%|██        | 21068/100629 [16:46<57:41, 22.98it/s]

 21%|██        | 21071/100629 [16:46<1:07:53, 19.53it/s]

 21%|██        | 21074/100629 [16:46<1:32:25, 14.35it/s]

 21%|██        | 21077/100629 [16:47<1:22:56, 15.98it/s]

 21%|██        | 21080/100629 [16:47<1:16:39, 17.29it/s]

 21%|██        | 21082/100629 [16:47<1:15:45, 17.50it/s]

 21%|██        | 21084/100629 [16:47<1:19:42, 16.63it/s]

 21%|██        | 21086/100629 [16:47<1:33:17, 14.21it/s]

 21%|██        | 21090/100629 [16:47<1:15:26, 17.57it/s]

 21%|██        | 21092/100629 [16:47<1:19:32, 16.67it/s]

 21%|██        | 21096/100629 [16:48<1:06:23, 19.96it/s]

 21%|██        | 21099/100629 [16:48<1:12:01, 18.40it/s]

 21%|██        | 21102/100629 [16:48<1:06:30, 19.93it/s]

 21%|██        | 21105/100629 [16:48<1:04:44, 20.47it/s]

 21%|██        | 21110/100629 [16:48<52:49, 25.09it/s]

 21%|██        | 21113/100629 [16:48<53:35, 24.73it/s]

 21%|██        | 21116/100629 [16:49<1:02:03, 21.36it/s]

 21%|██        | 21119/100629 [16:49<58:57, 22.48it/s]

 21%|██        | 21122/100629 [16:49<59:07, 22.41it/s]

 21%|██        | 21125/100629 [16:49<58:58, 22.47it/s]

 21%|██        | 21128/100629 [16:49<1:02:25, 21.23it/s]

 21%|██        | 21131/100629 [16:49<57:37, 23.00it/s]

 21%|██        | 21134/100629 [16:49<1:06:46, 19.84it/s]

 21%|██        | 21137/100629 [16:49<1:01:13, 21.64it/s]

 21%|██        | 21140/100629 [16:50<1:04:39, 20.49it/s]

 21%|██        | 21144/100629 [16:50<55:18, 23.95it/s]

 21%|██        | 21147/100629 [16:50<55:09, 24.02it/s]

 21%|██        | 21150/100629 [16:50<54:53, 24.13it/s]

 21%|██        | 21153/100629 [16:50<57:20, 23.10it/s]

 21%|██        | 21157/100629 [16:50<53:36, 24.71it/s]

 21%|██        | 21160/100629 [16:50<57:50, 22.90it/s]

 21%|██        | 21163/100629 [16:51<1:00:02, 22.06it/s]

 21%|██        | 21166/100629 [16:51<1:05:27, 20.23it/s]

 21%|██        | 21169/100629 [16:51<1:11:45, 18.46it/s]

 21%|██        | 21171/100629 [16:51<1:13:04, 18.12it/s]

 21%|██        | 21173/100629 [16:51<1:14:49, 17.70it/s]

 21%|██        | 21175/100629 [16:51<1:24:34, 15.66it/s]

 21%|██        | 21178/100629 [16:52<1:18:18, 16.91it/s]

 21%|██        | 21183/100629 [16:52<58:59, 22.44it/s]

 21%|██        | 21186/100629 [16:52<57:22, 23.07it/s]

 21%|██        | 21190/100629 [16:52<53:41, 24.66it/s]

 21%|██        | 21193/100629 [16:52<56:51, 23.28it/s]

 21%|██        | 21196/100629 [16:52<1:04:17, 20.59it/s]

 21%|██        | 21199/100629 [16:52<1:13:28, 18.02it/s]

 21%|██        | 21203/100629 [16:53<1:09:31, 19.04it/s]

 21%|██        | 21205/100629 [16:53<1:12:41, 18.21it/s]

 21%|██        | 21208/100629 [16:53<1:06:06, 20.02it/s]

 21%|██        | 21212/100629 [16:53<59:09, 22.38it/s]

 21%|██        | 21215/100629 [16:53<1:07:15, 19.68it/s]

 21%|██        | 21219/100629 [16:53<58:53, 22.47it/s]

 21%|██        | 21222/100629 [16:54<1:04:59, 20.36it/s]

 21%|██        | 21226/100629 [16:54<57:22, 23.07it/s]

 21%|██        | 21229/100629 [16:54<1:01:57, 21.36it/s]

 21%|██        | 21232/100629 [16:54<1:05:17, 20.26it/s]

 21%|██        | 21235/100629 [16:54<1:02:09, 21.29it/s]

 21%|██        | 21240/100629 [16:54<50:55, 25.98it/s]

 21%|██        | 21244/100629 [16:54<47:32, 27.83it/s]

 21%|██        | 21247/100629 [16:55<47:33, 27.81it/s]

 21%|██        | 21251/100629 [16:55<52:07, 25.38it/s]

 21%|██        | 21255/100629 [16:55<49:04, 26.96it/s]

 21%|██        | 21258/100629 [16:55<53:08, 24.89it/s]

 21%|██        | 21261/100629 [16:55<1:00:20, 21.92it/s]

 21%|██        | 21264/100629 [16:55<59:44, 22.14it/s]

 21%|██        | 21268/100629 [16:55<50:45, 26.06it/s]

 21%|██        | 21271/100629 [16:56<54:15, 24.37it/s]

 21%|██        | 21274/100629 [16:56<1:06:28, 19.89it/s]

 21%|██        | 21277/100629 [16:56<1:05:45, 20.11it/s]

 21%|██        | 21280/100629 [16:56<1:03:04, 20.97it/s]

 21%|██        | 21283/100629 [16:56<58:36, 22.57it/s]

 21%|██        | 21286/100629 [16:56<1:09:25, 19.05it/s]

 21%|██        | 21291/100629 [16:57<54:24, 24.30it/s]

 21%|██        | 21294/100629 [16:57<53:39, 24.64it/s]

 21%|██        | 21298/100629 [16:57<47:01, 28.12it/s]

 21%|██        | 21302/100629 [16:57<1:00:06, 22.00it/s]

 21%|██        | 21305/100629 [16:57<57:07, 23.14it/s]

 21%|██        | 21309/100629 [16:57<50:55, 25.96it/s]

 21%|██        | 21312/100629 [16:57<53:16, 24.82it/s]

 21%|██        | 21315/100629 [16:58<1:35:41, 13.81it/s]

 21%|██        | 21318/100629 [16:58<1:24:20, 15.67it/s]

 21%|██        | 21321/100629 [16:58<1:18:54, 16.75it/s]

 21%|██        | 21324/100629 [16:58<1:12:34, 18.21it/s]

 21%|██        | 21328/100629 [16:58<1:00:57, 21.68it/s]

 21%|██        | 21331/100629 [16:59<1:05:30, 20.18it/s]

 21%|██        | 21337/100629 [16:59<49:30, 26.69it/s]

 21%|██        | 21340/100629 [16:59<48:53, 27.03it/s]

 21%|██        | 21343/100629 [16:59<49:47, 26.54it/s]

 21%|██        | 21346/100629 [16:59<53:16, 24.80it/s]

 21%|██        | 21349/100629 [16:59<50:58, 25.92it/s]

 21%|██        | 21352/100629 [16:59<59:24, 22.24it/s]

 21%|██        | 21355/100629 [16:59<1:01:08, 21.61it/s]

 21%|██        | 21358/100629 [17:00<58:14, 22.68it/s]

 21%|██        | 21361/100629 [17:00<1:02:00, 21.31it/s]

 21%|██        | 21364/100629 [17:00<1:34:40, 13.95it/s]

 21%|██        | 21367/100629 [17:00<1:19:57, 16.52it/s]

 21%|██        | 21371/100629 [17:00<1:03:52, 20.68it/s]

 21%|██        | 21374/100629 [17:00<1:05:13, 20.25it/s]

 21%|██        | 21377/100629 [17:01<1:02:13, 21.23it/s]

 21%|██        | 21380/100629 [17:01<57:29, 22.98it/s]

 21%|██        | 21383/100629 [17:01<1:09:31, 19.00it/s]

 21%|██▏       | 21386/100629 [17:01<1:06:01, 20.00it/s]

 21%|██▏       | 21389/100629 [17:01<1:08:00, 19.42it/s]

 21%|██▏       | 21392/100629 [17:01<1:03:45, 20.71it/s]

 21%|██▏       | 21395/100629 [17:02<1:03:07, 20.92it/s]

 21%|██▏       | 21398/100629 [17:02<1:06:17, 19.92it/s]

 21%|██▏       | 21401/100629 [17:02<1:00:35, 21.79it/s]

 21%|██▏       | 21404/100629 [17:02<58:59, 22.38it/s]

 21%|██▏       | 21407/100629 [17:02<1:05:29, 20.16it/s]

 21%|██▏       | 21410/100629 [17:02<1:12:32, 18.20it/s]

 21%|██▏       | 21414/100629 [17:02<1:05:13, 20.24it/s]

 21%|██▏       | 21417/100629 [17:03<1:27:13, 15.13it/s]

 21%|██▏       | 21419/100629 [17:03<1:33:31, 14.12it/s]

 21%|██▏       | 21421/100629 [17:03<1:38:48, 13.36it/s]

 21%|██▏       | 21424/100629 [17:03<1:27:36, 15.07it/s]

 21%|██▏       | 21426/100629 [17:03<1:28:23, 14.93it/s]

 21%|██▏       | 21429/100629 [17:04<1:15:13, 17.55it/s]

 21%|██▏       | 21433/100629 [17:04<1:01:20, 21.52it/s]

 21%|██▏       | 21436/100629 [17:04<1:03:48, 20.68it/s]

 21%|██▏       | 21439/100629 [17:04<1:12:25, 18.22it/s]

 21%|██▏       | 21441/100629 [17:04<1:18:06, 16.90it/s]

 21%|██▏       | 21445/100629 [17:04<1:05:20, 20.20it/s]

 21%|██▏       | 21450/100629 [17:04<56:40, 23.28it/s]

 21%|██▏       | 21454/100629 [17:05<53:18, 24.75it/s]

 21%|██▏       | 21459/100629 [17:05<46:57, 28.10it/s]

 21%|██▏       | 21462/100629 [17:05<54:17, 24.31it/s]

 21%|██▏       | 21465/100629 [17:05<52:51, 24.96it/s]

 21%|██▏       | 21468/100629 [17:05<51:51, 25.44it/s]

 21%|██▏       | 21471/100629 [17:05<1:07:48, 19.45it/s]

 21%|██▏       | 21474/100629 [17:06<1:05:58, 19.99it/s]

 21%|██▏       | 21477/100629 [17:06<1:02:59, 20.94it/s]

 21%|██▏       | 21481/100629 [17:06<1:02:52, 20.98it/s]

 21%|██▏       | 21484/100629 [17:06<1:07:25, 19.57it/s]

 21%|██▏       | 21487/100629 [17:06<1:26:12, 15.30it/s]

 21%|██▏       | 21491/100629 [17:06<1:13:22, 17.97it/s]

 21%|██▏       | 21494/100629 [17:07<1:14:43, 17.65it/s]

 21%|██▏       | 21497/100629 [17:07<1:08:27, 19.26it/s]

 21%|██▏       | 21500/100629 [17:07<1:04:35, 20.42it/s]

 21%|██▏       | 21503/100629 [17:07<1:11:00, 18.57it/s]

 21%|██▏       | 21506/100629 [17:07<1:08:36, 19.22it/s]

 21%|██▏       | 21509/100629 [17:07<1:09:21, 19.01it/s]

 21%|██▏       | 21512/100629 [17:08<1:10:01, 18.83it/s]

 21%|██▏       | 21514/100629 [17:08<1:11:15, 18.50it/s]

 21%|██▏       | 21516/100629 [17:08<1:11:53, 18.34it/s]

 21%|██▏       | 21518/100629 [17:08<1:20:09, 16.45it/s]

 21%|██▏       | 21521/100629 [17:08<1:12:17, 18.24it/s]

 21%|██▏       | 21523/100629 [17:08<1:17:57, 16.91it/s]

 21%|██▏       | 21526/100629 [17:08<1:16:39, 17.20it/s]

 21%|██▏       | 21529/100629 [17:09<1:13:30, 17.93it/s]

 21%|██▏       | 21531/100629 [17:09<1:14:33, 17.68it/s]

 21%|██▏       | 21534/100629 [17:09<1:08:39, 19.20it/s]

 21%|██▏       | 21538/100629 [17:09<55:36, 23.70it/s]

 21%|██▏       | 21541/100629 [17:09<1:00:39, 21.73it/s]

 21%|██▏       | 21544/100629 [17:09<59:52, 22.01it/s]

 21%|██▏       | 21547/100629 [17:09<1:14:10, 17.77it/s]

 21%|██▏       | 21550/100629 [17:10<1:09:32, 18.95it/s]

 21%|██▏       | 21553/100629 [17:10<1:02:34, 21.06it/s]

 21%|██▏       | 21556/100629 [17:10<58:48, 22.41it/s]

 21%|██▏       | 21559/100629 [17:10<58:51, 22.39it/s]

 21%|██▏       | 21562/100629 [17:10<56:38, 23.26it/s]

 21%|██▏       | 21565/100629 [17:10<1:14:58, 17.58it/s]

 21%|██▏       | 21569/100629 [17:10<1:02:21, 21.13it/s]

 21%|██▏       | 21572/100629 [17:11<1:00:03, 21.94it/s]

 21%|██▏       | 21576/100629 [17:11<54:30, 24.17it/s]

 21%|██▏       | 21579/100629 [17:11<1:00:31, 21.77it/s]

 21%|██▏       | 21583/100629 [17:11<57:54, 22.75it/s]

 21%|██▏       | 21586/100629 [17:11<55:54, 23.56it/s]

 21%|██▏       | 21589/100629 [17:11<1:05:43, 20.04it/s]

 21%|██▏       | 21592/100629 [17:12<1:06:27, 19.82it/s]

 21%|██▏       | 21596/100629 [17:12<58:07, 22.66it/s]

 21%|██▏       | 21599/100629 [17:12<1:00:57, 21.61it/s]

 21%|██▏       | 21602/100629 [17:12<58:41, 22.44it/s]

 21%|██▏       | 21605/100629 [17:12<59:56, 21.97it/s]

 21%|██▏       | 21608/100629 [17:12<57:29, 22.91it/s]

 21%|██▏       | 21611/100629 [17:12<1:09:20, 18.99it/s]

 21%|██▏       | 21614/100629 [17:13<1:13:57, 17.81it/s]

 21%|██▏       | 21617/100629 [17:13<1:09:56, 18.83it/s]

 21%|██▏       | 21620/100629 [17:13<1:04:59, 20.26it/s]

 21%|██▏       | 21624/100629 [17:13<59:44, 22.04it/s]

 21%|██▏       | 21627/100629 [17:13<1:02:01, 21.23it/s]

 21%|██▏       | 21630/100629 [17:13<1:02:30, 21.06it/s]

 21%|██▏       | 21633/100629 [17:13<1:05:24, 20.13it/s]

 22%|██▏       | 21636/100629 [17:14<1:02:36, 21.03it/s]

 22%|██▏       | 21639/100629 [17:14<58:54, 22.35it/s]

 22%|██▏       | 21643/100629 [17:14<1:02:31, 21.06it/s]

 22%|██▏       | 21647/100629 [17:14<54:49, 24.01it/s]

 22%|██▏       | 21650/100629 [17:14<59:16, 22.21it/s]

 22%|██▏       | 21653/100629 [17:14<57:03, 23.07it/s]

 22%|██▏       | 21656/100629 [17:14<54:29, 24.15it/s]

 22%|██▏       | 21659/100629 [17:15<1:05:40, 20.04it/s]

 22%|██▏       | 21662/100629 [17:15<1:01:36, 21.36it/s]

 22%|██▏       | 21665/100629 [17:15<1:03:33, 20.70it/s]

 22%|██▏       | 21668/100629 [17:15<1:01:08, 21.52it/s]

 22%|██▏       | 21671/100629 [17:15<57:10, 23.02it/s]

 22%|██▏       | 21674/100629 [17:15<58:02, 22.67it/s]

 22%|██▏       | 21677/100629 [17:15<59:52, 21.98it/s]

 22%|██▏       | 21680/100629 [17:16<1:05:02, 20.23it/s]

 22%|██▏       | 21683/100629 [17:16<1:01:03, 21.55it/s]

 22%|██▏       | 21686/100629 [17:16<1:02:24, 21.08it/s]

 22%|██▏       | 21689/100629 [17:16<1:00:12, 21.85it/s]

 22%|██▏       | 21692/100629 [17:16<1:18:46, 16.70it/s]

 22%|██▏       | 21695/100629 [17:16<1:09:38, 18.89it/s]

 22%|██▏       | 21698/100629 [17:17<1:08:04, 19.32it/s]

 22%|██▏       | 21701/100629 [17:17<1:02:06, 21.18it/s]

 22%|██▏       | 21704/100629 [17:17<1:05:02, 20.22it/s]

 22%|██▏       | 21707/100629 [17:17<1:03:17, 20.78it/s]

 22%|██▏       | 21710/100629 [17:17<58:16, 22.57it/s]

 22%|██▏       | 21713/100629 [17:17<1:02:40, 20.98it/s]

 22%|██▏       | 21716/100629 [17:17<1:01:07, 21.52it/s]

 22%|██▏       | 21719/100629 [17:17<59:12, 22.21it/s]

 22%|██▏       | 21722/100629 [17:18<1:20:47, 16.28it/s]

 22%|██▏       | 21727/100629 [17:18<59:06, 22.25it/s]

 22%|██▏       | 21730/100629 [17:18<1:17:29, 16.97it/s]

 22%|██▏       | 21733/100629 [17:18<1:12:56, 18.03it/s]

 22%|██▏       | 21736/100629 [17:18<1:10:17, 18.71it/s]

 22%|██▏       | 21739/100629 [17:19<1:12:52, 18.04it/s]

 22%|██▏       | 21742/100629 [17:19<1:11:14, 18.46it/s]

 22%|██▏       | 21746/100629 [17:19<59:20, 22.15it/s]

 22%|██▏       | 21750/100629 [17:19<50:44, 25.91it/s]

 22%|██▏       | 21754/100629 [17:19<51:08, 25.70it/s]

 22%|██▏       | 21757/100629 [17:19<58:40, 22.40it/s]

 22%|██▏       | 21761/100629 [17:20<56:12, 23.38it/s]

 22%|██▏       | 21764/100629 [17:20<1:01:58, 21.21it/s]

 22%|██▏       | 21767/100629 [17:20<58:03, 22.64it/s]

 22%|██▏       | 21770/100629 [17:20<1:02:17, 21.10it/s]

 22%|██▏       | 21773/100629 [17:20<1:04:45, 20.30it/s]

 22%|██▏       | 21776/100629 [17:20<59:27, 22.11it/s]

 22%|██▏       | 21779/100629 [17:20<55:17, 23.77it/s]

 22%|██▏       | 21782/100629 [17:20<56:13, 23.37it/s]

 22%|██▏       | 21787/100629 [17:21<47:17, 27.79it/s]

 22%|██▏       | 21790/100629 [17:21<52:32, 25.01it/s]

 22%|██▏       | 21794/100629 [17:21<54:04, 24.30it/s]

 22%|██▏       | 21797/100629 [17:21<59:50, 21.96it/s]

 22%|██▏       | 21800/100629 [17:21<1:02:10, 21.13it/s]

 22%|██▏       | 21803/100629 [17:21<1:04:34, 20.35it/s]

 22%|██▏       | 21807/100629 [17:22<54:03, 24.30it/s]

 22%|██▏       | 21810/100629 [17:22<53:09, 24.71it/s]

 22%|██▏       | 21814/100629 [17:22<51:24, 25.55it/s]

 22%|██▏       | 21817/100629 [17:22<1:05:11, 20.15it/s]

 22%|██▏       | 21820/100629 [17:22<1:06:51, 19.64it/s]

 22%|██▏       | 21824/100629 [17:22<56:20, 23.31it/s]

 22%|██▏       | 21827/100629 [17:22<1:00:07, 21.85it/s]

 22%|██▏       | 21830/100629 [17:23<56:47, 23.13it/s]

 22%|██▏       | 21834/100629 [17:23<51:26, 25.53it/s]

 22%|██▏       | 21837/100629 [17:23<53:43, 24.44it/s]

 22%|██▏       | 21840/100629 [17:23<52:44, 24.90it/s]

 22%|██▏       | 21843/100629 [17:23<51:16, 25.61it/s]

 22%|██▏       | 21846/100629 [17:23<54:01, 24.31it/s]

 22%|██▏       | 21849/100629 [17:23<52:11, 25.16it/s]

 22%|██▏       | 21852/100629 [17:23<54:01, 24.30it/s]

 22%|██▏       | 21855/100629 [17:24<55:50, 23.51it/s]

 22%|██▏       | 21858/100629 [17:24<54:04, 24.28it/s]

 22%|██▏       | 21861/100629 [17:24<54:30, 24.09it/s]

 22%|██▏       | 21864/100629 [17:24<56:12, 23.36it/s]

 22%|██▏       | 21867/100629 [17:24<54:11, 24.22it/s]

 22%|██▏       | 21870/100629 [17:24<58:11, 22.56it/s]

 22%|██▏       | 21873/100629 [17:24<1:00:05, 21.84it/s]

 22%|██▏       | 21876/100629 [17:25<1:05:19, 20.09it/s]

 22%|██▏       | 21880/100629 [17:25<57:31, 22.81it/s]

 22%|██▏       | 21883/100629 [17:25<1:04:12, 20.44it/s]

 22%|██▏       | 21886/100629 [17:25<1:08:34, 19.14it/s]

 22%|██▏       | 21890/100629 [17:25<58:11, 22.55it/s]

 22%|██▏       | 21894/100629 [17:25<53:48, 24.39it/s]

 22%|██▏       | 21897/100629 [17:25<54:48, 23.94it/s]

 22%|██▏       | 21900/100629 [17:26<1:03:46, 20.58it/s]

 22%|██▏       | 21904/100629 [17:26<55:10, 23.78it/s]

 22%|██▏       | 21908/100629 [17:26<56:43, 23.13it/s]

 22%|██▏       | 21911/100629 [17:26<54:03, 24.27it/s]

 22%|██▏       | 21914/100629 [17:26<1:03:14, 20.74it/s]

 22%|██▏       | 21917/100629 [17:26<1:03:22, 20.70it/s]

 22%|██▏       | 21921/100629 [17:27<53:45, 24.40it/s]

 22%|██▏       | 21924/100629 [17:27<55:19, 23.71it/s]

 22%|██▏       | 21928/100629 [17:27<55:37, 23.58it/s]

 22%|██▏       | 21933/100629 [17:27<48:42, 26.93it/s]

 22%|██▏       | 21936/100629 [17:27<55:36, 23.59it/s]

 22%|██▏       | 21939/100629 [17:27<54:37, 24.01it/s]

 22%|██▏       | 21942/100629 [17:27<56:44, 23.11it/s]

 22%|██▏       | 21945/100629 [17:28<55:05, 23.80it/s]

 22%|██▏       | 21948/100629 [17:28<59:38, 21.99it/s]

 22%|██▏       | 21951/100629 [17:28<56:37, 23.16it/s]

 22%|██▏       | 21954/100629 [17:28<1:08:16, 19.21it/s]

 22%|██▏       | 21957/100629 [17:28<1:16:08, 17.22it/s]

 22%|██▏       | 21962/100629 [17:28<1:00:16, 21.75it/s]

 22%|██▏       | 21965/100629 [17:29<1:03:58, 20.49it/s]

 22%|██▏       | 21968/100629 [17:29<1:16:33, 17.12it/s]

 22%|██▏       | 21971/100629 [17:29<1:18:43, 16.65it/s]

 22%|██▏       | 21974/100629 [17:29<1:11:43, 18.28it/s]

 22%|██▏       | 21977/100629 [17:29<1:05:46, 19.93it/s]

 22%|██▏       | 21980/100629 [17:29<1:16:37, 17.11it/s]

 22%|██▏       | 21983/100629 [17:30<1:22:38, 15.86it/s]

 22%|██▏       | 21987/100629 [17:30<1:13:09, 17.92it/s]

 22%|██▏       | 21990/100629 [17:30<1:08:50, 19.04it/s]

 22%|██▏       | 21993/100629 [17:30<1:13:41, 17.78it/s]

 22%|██▏       | 21997/100629 [17:30<1:21:55, 16.00it/s]

 22%|██▏       | 22001/100629 [17:31<1:10:19, 18.63it/s]

 22%|██▏       | 22004/100629 [17:31<1:09:02, 18.98it/s]

 22%|██▏       | 22007/100629 [17:31<1:04:11, 20.41it/s]

 22%|██▏       | 22010/100629 [17:31<1:03:23, 20.67it/s]

 22%|██▏       | 22013/100629 [17:31<1:20:46, 16.22it/s]

 22%|██▏       | 22017/100629 [17:31<1:09:16, 18.91it/s]

 22%|██▏       | 22021/100629 [17:32<59:27, 22.03it/s]

 22%|██▏       | 22024/100629 [17:32<57:16, 22.88it/s]

 22%|██▏       | 22027/100629 [17:32<1:00:18, 21.72it/s]

 22%|██▏       | 22030/100629 [17:32<58:53, 22.24it/s]

 22%|██▏       | 22033/100629 [17:32<56:13, 23.30it/s]

 22%|██▏       | 22036/100629 [17:32<59:59, 21.83it/s]

 22%|██▏       | 22039/100629 [17:32<58:19, 22.46it/s]

 22%|██▏       | 22042/100629 [17:33<58:23, 22.43it/s]

 22%|██▏       | 22045/100629 [17:33<54:06, 24.21it/s]

 22%|██▏       | 22048/100629 [17:33<1:01:27, 21.31it/s]

 22%|██▏       | 22051/100629 [17:33<56:45, 23.07it/s]

 22%|██▏       | 22055/100629 [17:33<49:23, 26.51it/s]

 22%|██▏       | 22058/100629 [17:33<56:58, 22.99it/s]

 22%|██▏       | 22061/100629 [17:33<1:01:50, 21.17it/s]

 22%|██▏       | 22064/100629 [17:34<1:05:00, 20.14it/s]

 22%|██▏       | 22067/100629 [17:34<1:12:18, 18.11it/s]

 22%|██▏       | 22071/100629 [17:34<1:02:03, 21.10it/s]

 22%|██▏       | 22074/100629 [17:34<1:06:38, 19.65it/s]

 22%|██▏       | 22077/100629 [17:34<1:18:28, 16.68it/s]

 22%|██▏       | 22079/100629 [17:34<1:17:38, 16.86it/s]

 22%|██▏       | 22082/100629 [17:35<1:13:00, 17.93it/s]

 22%|██▏       | 22085/100629 [17:35<1:09:46, 18.76it/s]

 22%|██▏       | 22089/100629 [17:35<1:02:51, 20.82it/s]

 22%|██▏       | 22092/100629 [17:35<1:07:52, 19.28it/s]

 22%|██▏       | 22094/100629 [17:35<1:21:33, 16.05it/s]

 22%|██▏       | 22096/100629 [17:35<1:33:28, 14.00it/s]

 22%|██▏       | 22098/100629 [17:36<1:27:25, 14.97it/s]

 22%|██▏       | 22101/100629 [17:36<1:20:15, 16.31it/s]

 22%|██▏       | 22105/100629 [17:36<1:02:34, 20.92it/s]

 22%|██▏       | 22108/100629 [17:36<1:01:26, 21.30it/s]

 22%|██▏       | 22111/100629 [17:36<1:01:34, 21.25it/s]

 22%|██▏       | 22114/100629 [17:36<1:08:00, 19.24it/s]

 22%|██▏       | 22118/100629 [17:36<1:00:53, 21.49it/s]

 22%|██▏       | 22121/100629 [17:37<1:00:12, 21.73it/s]

 22%|██▏       | 22124/100629 [17:37<57:37, 22.70it/s]

 22%|██▏       | 22128/100629 [17:37<57:28, 22.76it/s]

 22%|██▏       | 22131/100629 [17:37<1:05:39, 19.93it/s]

 22%|██▏       | 22134/100629 [17:37<1:13:57, 17.69it/s]

 22%|██▏       | 22136/100629 [17:37<1:15:25, 17.35it/s]

 22%|██▏       | 22139/100629 [17:38<1:10:26, 18.57it/s]

 22%|██▏       | 22143/100629 [17:38<59:26, 22.01it/s]

 22%|██▏       | 22147/100629 [17:38<50:23, 25.96it/s]

 22%|██▏       | 22150/100629 [17:38<54:37, 23.94it/s]

 22%|██▏       | 22153/100629 [17:38<53:46, 24.32it/s]

 22%|██▏       | 22156/100629 [17:38<51:52, 25.21it/s]

 22%|██▏       | 22159/100629 [17:38<49:51, 26.23it/s]

 22%|██▏       | 22163/100629 [17:38<46:54, 27.87it/s]

 22%|██▏       | 22166/100629 [17:39<50:24, 25.94it/s]

 22%|██▏       | 22169/100629 [17:39<50:11, 26.06it/s]

 22%|██▏       | 22172/100629 [17:39<49:27, 26.44it/s]

 22%|██▏       | 22175/100629 [17:39<57:28, 22.75it/s]

 22%|██▏       | 22178/100629 [17:39<1:08:42, 19.03it/s]

 22%|██▏       | 22181/100629 [17:39<1:03:48, 20.49it/s]

 22%|██▏       | 22185/100629 [17:39<1:02:13, 21.01it/s]

 22%|██▏       | 22188/100629 [17:40<1:01:35, 21.23it/s]

 22%|██▏       | 22191/100629 [17:40<1:01:30, 21.26it/s]

 22%|██▏       | 22194/100629 [17:40<1:03:40, 20.53it/s]

 22%|██▏       | 22197/100629 [17:40<1:00:48, 21.50it/s]

 22%|██▏       | 22200/100629 [17:40<1:05:45, 19.88it/s]

 22%|██▏       | 22203/100629 [17:40<1:06:23, 19.69it/s]

 22%|██▏       | 22206/100629 [17:40<1:04:39, 20.21it/s]

 22%|██▏       | 22209/100629 [17:41<59:52, 21.83it/s]

 22%|██▏       | 22213/100629 [17:41<50:19, 25.97it/s]

 22%|██▏       | 22216/100629 [17:41<49:28, 26.41it/s]

 22%|██▏       | 22219/100629 [17:41<52:48, 24.75it/s]

 22%|██▏       | 22223/100629 [17:41<47:07, 27.73it/s]

 22%|██▏       | 22226/100629 [17:41<51:27, 25.39it/s]

 22%|██▏       | 22230/100629 [17:41<50:48, 25.72it/s]

 22%|██▏       | 22233/100629 [17:42<58:32, 22.32it/s]

 22%|██▏       | 22237/100629 [17:42<54:15, 24.08it/s]

 22%|██▏       | 22241/100629 [17:42<50:09, 26.05it/s]

 22%|██▏       | 22246/100629 [17:42<43:40, 29.92it/s]

 22%|██▏       | 22250/100629 [17:42<46:17, 28.22it/s]

 22%|██▏       | 22254/100629 [17:42<47:10, 27.69it/s]

 22%|██▏       | 22258/100629 [17:42<43:36, 29.95it/s]

 22%|██▏       | 22262/100629 [17:43<50:56, 25.64it/s]

 22%|██▏       | 22266/100629 [17:43<46:41, 27.97it/s]

 22%|██▏       | 22269/100629 [17:43<50:03, 26.09it/s]

 22%|██▏       | 22272/100629 [17:43<55:39, 23.47it/s]

 22%|██▏       | 22275/100629 [17:43<1:13:25, 17.79it/s]

 22%|██▏       | 22278/100629 [17:43<1:14:28, 17.53it/s]

 22%|██▏       | 22280/100629 [17:44<1:12:57, 17.90it/s]

 22%|██▏       | 22283/100629 [17:44<1:09:12, 18.87it/s]

 22%|██▏       | 22289/100629 [17:44<57:14, 22.81it/s]

 22%|██▏       | 22292/100629 [17:44<55:28, 23.54it/s]

 22%|██▏       | 22295/100629 [17:44<1:06:18, 19.69it/s]

 22%|██▏       | 22298/100629 [17:44<1:00:34, 21.55it/s]

 22%|██▏       | 22301/100629 [17:45<1:12:41, 17.96it/s]

 22%|██▏       | 22304/100629 [17:45<1:04:25, 20.26it/s]

 22%|██▏       | 22307/100629 [17:45<1:03:16, 20.63it/s]

 22%|██▏       | 22310/100629 [17:45<1:01:03, 21.38it/s]

 22%|██▏       | 22313/100629 [17:45<56:37, 23.05it/s]

 22%|██▏       | 22316/100629 [17:45<1:02:02, 21.04it/s]

 22%|██▏       | 22319/100629 [17:45<1:02:34, 20.86it/s]

 22%|██▏       | 22322/100629 [17:45<1:03:28, 20.56it/s]

 22%|██▏       | 22325/100629 [17:46<1:11:28, 18.26it/s]

 22%|██▏       | 22327/100629 [17:46<1:14:48, 17.44it/s]

 22%|██▏       | 22331/100629 [17:46<1:04:02, 20.37it/s]

 22%|██▏       | 22334/100629 [17:46<1:01:23, 21.25it/s]

 22%|██▏       | 22338/100629 [17:46<53:37, 24.33it/s]

 22%|██▏       | 22341/100629 [17:46<1:01:51, 21.09it/s]

 22%|██▏       | 22344/100629 [17:47<59:07, 22.07it/s]

 22%|██▏       | 22347/100629 [17:47<57:01, 22.88it/s]

 22%|██▏       | 22350/100629 [17:47<54:43, 23.84it/s]

 22%|██▏       | 22353/100629 [17:47<52:29, 24.85it/s]

 22%|██▏       | 22357/100629 [17:47<45:40, 28.56it/s]

 22%|██▏       | 22360/100629 [17:47<50:46, 25.69it/s]

 22%|██▏       | 22363/100629 [17:47<54:29, 23.93it/s]

 22%|██▏       | 22366/100629 [17:47<55:24, 23.54it/s]

 22%|██▏       | 22369/100629 [17:48<55:18, 23.58it/s]

 22%|██▏       | 22372/100629 [17:48<56:40, 23.02it/s]

 22%|██▏       | 22375/100629 [17:48<1:04:13, 20.31it/s]

 22%|██▏       | 22378/100629 [17:48<1:12:22, 18.02it/s]

 22%|██▏       | 22381/100629 [17:48<1:05:18, 19.97it/s]

 22%|██▏       | 22384/100629 [17:48<1:07:53, 19.21it/s]

 22%|██▏       | 22387/100629 [17:48<1:01:43, 21.13it/s]

 22%|██▏       | 22391/100629 [17:49<1:00:56, 21.40it/s]

 22%|██▏       | 22394/100629 [17:49<1:00:58, 21.38it/s]

 22%|██▏       | 22397/100629 [17:49<1:00:05, 21.70it/s]

 22%|██▏       | 22401/100629 [17:49<57:23, 22.72it/s]

 22%|██▏       | 22404/100629 [17:49<54:14, 24.04it/s]

 22%|██▏       | 22407/100629 [17:49<54:31, 23.91it/s]

 22%|██▏       | 22410/100629 [17:49<56:12, 23.20it/s]

 22%|██▏       | 22413/100629 [17:50<55:01, 23.69it/s]

 22%|██▏       | 22417/100629 [17:50<53:11, 24.50it/s]

 22%|██▏       | 22421/100629 [17:50<50:38, 25.74it/s]

 22%|██▏       | 22425/100629 [17:50<46:03, 28.30it/s]

 22%|██▏       | 22428/100629 [17:50<49:52, 26.13it/s]

 22%|██▏       | 22434/100629 [17:50<39:46, 32.77it/s]

 22%|██▏       | 22438/100629 [17:50<50:53, 25.61it/s]

 22%|██▏       | 22441/100629 [17:51<55:32, 23.46it/s]

 22%|██▏       | 22444/100629 [17:51<1:02:13, 20.94it/s]

 22%|██▏       | 22447/100629 [17:51<1:10:32, 18.47it/s]

 22%|██▏       | 22449/100629 [17:51<1:17:48, 16.75it/s]

 22%|██▏       | 22452/100629 [17:51<1:11:52, 18.13it/s]

 22%|██▏       | 22457/100629 [17:51<57:05, 22.82it/s]

 22%|██▏       | 22460/100629 [17:52<1:02:18, 20.91it/s]

 22%|██▏       | 22463/100629 [17:52<58:02, 22.45it/s]

 22%|██▏       | 22466/100629 [17:52<1:02:16, 20.92it/s]

 22%|██▏       | 22469/100629 [17:52<1:08:50, 18.92it/s]

 22%|██▏       | 22472/100629 [17:52<1:02:38, 20.80it/s]

 22%|██▏       | 22475/100629 [17:52<1:01:46, 21.09it/s]

 22%|██▏       | 22479/100629 [17:52<51:50, 25.12it/s]

 22%|██▏       | 22482/100629 [17:53<59:28, 21.90it/s]

 22%|██▏       | 22485/100629 [17:53<1:03:22, 20.55it/s]

 22%|██▏       | 22488/100629 [17:53<1:12:53, 17.87it/s]

 22%|██▏       | 22490/100629 [17:53<1:13:12, 17.79it/s]

 22%|██▏       | 22494/100629 [17:53<58:01, 22.44it/s]

 22%|██▏       | 22497/100629 [17:53<59:14, 21.98it/s]

 22%|██▏       | 22500/100629 [17:54<57:36, 22.60it/s]

 22%|██▏       | 22503/100629 [17:54<1:15:25, 17.26it/s]

 22%|██▏       | 22506/100629 [17:54<1:08:50, 18.91it/s]

 22%|██▏       | 22509/100629 [17:54<1:10:27, 18.48it/s]

 22%|██▏       | 22512/100629 [17:54<1:06:40, 19.53it/s]

 22%|██▏       | 22515/100629 [17:54<1:12:51, 17.87it/s]

 22%|██▏       | 22518/100629 [17:55<1:07:32, 19.27it/s]

 22%|██▏       | 22521/100629 [17:55<1:02:13, 20.92it/s]

 22%|██▏       | 22526/100629 [17:55<51:24, 25.32it/s]

 22%|██▏       | 22529/100629 [17:55<56:42, 22.96it/s]

 22%|██▏       | 22532/100629 [17:55<1:02:23, 20.86it/s]

 22%|██▏       | 22535/100629 [17:55<59:12, 21.98it/s]

 22%|██▏       | 22538/100629 [17:55<59:14, 21.97it/s]

 22%|██▏       | 22541/100629 [17:56<55:11, 23.58it/s]

 22%|██▏       | 22544/100629 [17:56<58:49, 22.13it/s]

 22%|██▏       | 22548/100629 [17:56<51:22, 25.33it/s]

 22%|██▏       | 22551/100629 [17:56<49:37, 26.23it/s]

 22%|██▏       | 22554/100629 [17:56<1:16:56, 16.91it/s]

 22%|██▏       | 22557/100629 [17:56<1:09:19, 18.77it/s]

 22%|██▏       | 22560/100629 [17:56<1:05:39, 19.82it/s]

 22%|██▏       | 22563/100629 [17:57<1:01:05, 21.30it/s]

 22%|██▏       | 22566/100629 [17:57<57:29, 22.63it/s]

 22%|██▏       | 22570/100629 [17:57<59:02, 22.04it/s]

 22%|██▏       | 22573/100629 [17:57<58:31, 22.23it/s]

 22%|██▏       | 22576/100629 [17:57<1:00:53, 21.36it/s]

 22%|██▏       | 22579/100629 [17:57<1:01:58, 20.99it/s]

 22%|██▏       | 22582/100629 [17:57<1:00:05, 21.65it/s]

 22%|██▏       | 22585/100629 [17:58<56:59, 22.82it/s]

 22%|██▏       | 22588/100629 [17:58<57:19, 22.69it/s]

 22%|██▏       | 22591/100629 [17:58<59:03, 22.02it/s]

 22%|██▏       | 22594/100629 [17:58<1:06:42, 19.50it/s]

 22%|██▏       | 22599/100629 [17:58<54:44, 23.75it/s]

 22%|██▏       | 22602/100629 [17:58<57:12, 22.74it/s]

 22%|██▏       | 22606/100629 [17:58<49:08, 26.46it/s]

 22%|██▏       | 22609/100629 [17:59<54:50, 23.71it/s]

 22%|██▏       | 22612/100629 [17:59<57:44, 22.52it/s]

 22%|██▏       | 22615/100629 [17:59<53:59, 24.08it/s]

 22%|██▏       | 22618/100629 [17:59<1:02:18, 20.87it/s]

 22%|██▏       | 22621/100629 [17:59<1:21:23, 15.97it/s]

 22%|██▏       | 22624/100629 [17:59<1:10:32, 18.43it/s]

 22%|██▏       | 22627/100629 [18:00<1:15:17, 17.27it/s]

 22%|██▏       | 22629/100629 [18:00<1:14:21, 17.48it/s]

 22%|██▏       | 22631/100629 [18:00<1:20:10, 16.21it/s]

 22%|██▏       | 22634/100629 [18:00<1:14:50, 17.37it/s]

 22%|██▏       | 22636/100629 [18:00<1:20:04, 16.23it/s]

 22%|██▏       | 22638/100629 [18:00<1:17:59, 16.67it/s]

 22%|██▏       | 22640/100629 [18:00<1:29:31, 14.52it/s]

 23%|██▎       | 22645/100629 [18:01<1:05:22, 19.88it/s]

 23%|██▎       | 22650/100629 [18:01<50:15, 25.86it/s]

 23%|██▎       | 22653/100629 [18:01<51:33, 25.20it/s]

 23%|██▎       | 22657/100629 [18:01<49:30, 26.24it/s]

 23%|██▎       | 22660/100629 [18:01<50:06, 25.94it/s]

 23%|██▎       | 22664/100629 [18:01<46:53, 27.71it/s]

 23%|██▎       | 22668/100629 [18:01<50:15, 25.85it/s]

 23%|██▎       | 22671/100629 [18:02<1:04:06, 20.27it/s]

 23%|██▎       | 22674/100629 [18:02<1:00:11, 21.59it/s]

 23%|██▎       | 22677/100629 [18:02<1:05:45, 19.76it/s]

 23%|██▎       | 22680/100629 [18:02<1:10:47, 18.35it/s]

 23%|██▎       | 22683/100629 [18:02<1:13:39, 17.64it/s]

 23%|██▎       | 22685/100629 [18:02<1:12:01, 18.04it/s]

 23%|██▎       | 22688/100629 [18:03<1:09:47, 18.61it/s]

 23%|██▎       | 22691/100629 [18:03<1:07:56, 19.12it/s]

 23%|██▎       | 22694/100629 [18:03<1:01:05, 21.26it/s]

 23%|██▎       | 22697/100629 [18:03<1:01:04, 21.27it/s]

 23%|██▎       | 22700/100629 [18:03<56:38, 22.93it/s]

 23%|██▎       | 22704/100629 [18:03<1:03:01, 20.61it/s]

 23%|██▎       | 22707/100629 [18:04<1:06:31, 19.52it/s]

 23%|██▎       | 22710/100629 [18:04<1:05:27, 19.84it/s]

 23%|██▎       | 22713/100629 [18:04<1:07:07, 19.35it/s]

 23%|██▎       | 22715/100629 [18:04<1:15:10, 17.27it/s]

 23%|██▎       | 22717/100629 [18:04<1:20:56, 16.04it/s]

 23%|██▎       | 22719/100629 [18:04<1:30:04, 14.42it/s]

 23%|██▎       | 22721/100629 [18:04<1:34:17, 13.77it/s]

 23%|██▎       | 22725/100629 [18:05<1:12:27, 17.92it/s]

 23%|██▎       | 22728/100629 [18:05<1:12:56, 17.80it/s]

 23%|██▎       | 22731/100629 [18:05<1:08:35, 18.93it/s]

 23%|██▎       | 22733/100629 [18:05<1:10:09, 18.50it/s]

 23%|██▎       | 22735/100629 [18:05<1:39:26, 13.05it/s]

 23%|██▎       | 22738/100629 [18:05<1:24:55, 15.29it/s]

 23%|██▎       | 22740/100629 [18:06<1:20:36, 16.10it/s]

 23%|██▎       | 22745/100629 [18:06<59:23, 21.85it/s]

 23%|██▎       | 22748/100629 [18:06<1:10:29, 18.41it/s]

 23%|██▎       | 22751/100629 [18:06<1:10:36, 18.38it/s]

 23%|██▎       | 22755/100629 [18:06<1:08:55, 18.83it/s]

 23%|██▎       | 22757/100629 [18:06<1:12:29, 17.90it/s]

 23%|██▎       | 22761/100629 [18:07<59:15, 21.90it/s]

 23%|██▎       | 22765/100629 [18:07<50:35, 25.65it/s]

 23%|██▎       | 22768/100629 [18:07<49:10, 26.39it/s]

 23%|██▎       | 22771/100629 [18:07<49:12, 26.37it/s]

 23%|██▎       | 22774/100629 [18:07<52:51, 24.55it/s]

 23%|██▎       | 22778/100629 [18:07<46:55, 27.65it/s]

 23%|██▎       | 22783/100629 [18:07<43:30, 29.82it/s]

 23%|██▎       | 22787/100629 [18:07<40:32, 32.01it/s]

 23%|██▎       | 22791/100629 [18:08<47:59, 27.04it/s]

 23%|██▎       | 22794/100629 [18:08<48:35, 26.70it/s]

 23%|██▎       | 22797/100629 [18:08<48:44, 26.61it/s]

 23%|██▎       | 22800/100629 [18:08<48:16, 26.87it/s]

 23%|██▎       | 22803/100629 [18:08<50:43, 25.57it/s]

 23%|██▎       | 22806/100629 [18:08<1:02:49, 20.65it/s]

 23%|██▎       | 22809/100629 [18:08<1:04:26, 20.13it/s]

 23%|██▎       | 22812/100629 [18:09<1:06:42, 19.44it/s]

 23%|██▎       | 22815/100629 [18:09<1:08:37, 18.90it/s]

 23%|██▎       | 22817/100629 [18:09<1:13:09, 17.73it/s]

 23%|██▎       | 22819/100629 [18:09<1:13:05, 17.74it/s]

 23%|██▎       | 22822/100629 [18:09<1:18:40, 16.48it/s]

 23%|██▎       | 22825/100629 [18:09<1:07:30, 19.21it/s]

 23%|██▎       | 22828/100629 [18:10<1:14:00, 17.52it/s]

 23%|██▎       | 22833/100629 [18:10<1:01:30, 21.08it/s]

 23%|██▎       | 22836/100629 [18:10<58:19, 22.23it/s]

 23%|██▎       | 22839/100629 [18:10<54:24, 23.83it/s]

 23%|██▎       | 22842/100629 [18:10<59:37, 21.74it/s]

 23%|██▎       | 22845/100629 [18:10<58:39, 22.10it/s]

 23%|██▎       | 22848/100629 [18:10<57:36, 22.50it/s]

 23%|██▎       | 22851/100629 [18:11<1:02:39, 20.69it/s]

 23%|██▎       | 22854/100629 [18:11<1:00:47, 21.33it/s]

 23%|██▎       | 22857/100629 [18:11<57:46, 22.44it/s]

 23%|██▎       | 22860/100629 [18:11<1:02:50, 20.63it/s]

 23%|██▎       | 22864/100629 [18:11<55:31, 23.34it/s]

 23%|██▎       | 22868/100629 [18:11<52:01, 24.91it/s]

 23%|██▎       | 22871/100629 [18:11<1:00:08, 21.55it/s]

 23%|██▎       | 22876/100629 [18:12<50:09, 25.83it/s]

 23%|██▎       | 22880/100629 [18:12<46:04, 28.12it/s]

 23%|██▎       | 22883/100629 [18:12<49:17, 26.29it/s]

 23%|██▎       | 22886/100629 [18:12<54:08, 23.93it/s]

 23%|██▎       | 22889/100629 [18:12<1:13:05, 17.73it/s]

 23%|██▎       | 22892/100629 [18:13<1:37:02, 13.35it/s]

 23%|██▎       | 22896/100629 [18:13<1:14:39, 17.35it/s]

 23%|██▎       | 22899/100629 [18:13<1:11:27, 18.13it/s]

 23%|██▎       | 22904/100629 [18:13<1:00:57, 21.25it/s]

 23%|██▎       | 22907/100629 [18:13<58:40, 22.08it/s]

 23%|██▎       | 22910/100629 [18:13<59:06, 21.91it/s]

 23%|██▎       | 22913/100629 [18:13<59:43, 21.69it/s]

 23%|██▎       | 22916/100629 [18:14<1:14:32, 17.38it/s]

 23%|██▎       | 22921/100629 [18:14<57:43, 22.44it/s]

 23%|██▎       | 22924/100629 [18:14<57:08, 22.66it/s]

 23%|██▎       | 22927/100629 [18:14<59:40, 21.70it/s]

 23%|██▎       | 22930/100629 [18:14<59:16, 21.84it/s]

 23%|██▎       | 22934/100629 [18:14<52:15, 24.78it/s]

 23%|██▎       | 22937/100629 [18:15<1:09:28, 18.64it/s]

 23%|██▎       | 22941/100629 [18:15<58:38, 22.08it/s]

 23%|██▎       | 22944/100629 [18:15<1:12:55, 17.76it/s]

 23%|██▎       | 22947/100629 [18:15<1:05:14, 19.85it/s]

 23%|██▎       | 22950/100629 [18:15<1:02:24, 20.74it/s]

 23%|██▎       | 22953/100629 [18:15<57:41, 22.44it/s]

 23%|██▎       | 22956/100629 [18:15<53:51, 24.04it/s]

 23%|██▎       | 22960/100629 [18:16<46:50, 27.64it/s]

 23%|██▎       | 22963/100629 [18:16<55:04, 23.50it/s]

 23%|██▎       | 22966/100629 [18:16<52:10, 24.81it/s]

 23%|██▎       | 22969/100629 [18:16<55:51, 23.17it/s]

 23%|██▎       | 22973/100629 [18:16<49:58, 25.89it/s]

 23%|██▎       | 22976/100629 [18:16<53:42, 24.10it/s]

 23%|██▎       | 22980/100629 [18:16<46:29, 27.84it/s]

 23%|██▎       | 22983/100629 [18:17<1:01:02, 21.20it/s]

 23%|██▎       | 22986/100629 [18:17<1:01:39, 20.99it/s]

 23%|██▎       | 22989/100629 [18:17<59:08, 21.88it/s]

 23%|██▎       | 22992/100629 [18:17<56:09, 23.04it/s]

 23%|██▎       | 22995/100629 [18:17<1:04:06, 20.18it/s]

 23%|██▎       | 22998/100629 [18:17<1:03:12, 20.47it/s]

 23%|██▎       | 23002/100629 [18:17<55:19, 23.39it/s]

 23%|██▎       | 23005/100629 [18:18<1:02:36, 20.66it/s]

 23%|██▎       | 23008/100629 [18:18<1:06:03, 19.59it/s]

 23%|██▎       | 23011/100629 [18:18<1:02:21, 20.74it/s]

 23%|██▎       | 23014/100629 [18:18<1:03:17, 20.44it/s]

 23%|██▎       | 23017/100629 [18:18<58:53, 21.96it/s]

 23%|██▎       | 23021/100629 [18:18<52:55, 24.44it/s]

 23%|██▎       | 23025/100629 [18:18<54:26, 23.76it/s]

 23%|██▎       | 23028/100629 [18:19<53:27, 24.19it/s]

 23%|██▎       | 23031/100629 [18:19<1:02:23, 20.73it/s]

 23%|██▎       | 23034/100629 [18:19<1:02:08, 20.81it/s]

 23%|██▎       | 23037/100629 [18:19<57:31, 22.48it/s]

 23%|██▎       | 23040/100629 [18:19<59:36, 21.69it/s]

 23%|██▎       | 23043/100629 [18:19<59:45, 21.64it/s]

 23%|██▎       | 23046/100629 [18:19<1:00:39, 21.32it/s]

 23%|██▎       | 23049/100629 [18:20<1:03:47, 20.27it/s]

 23%|██▎       | 23052/100629 [18:20<1:06:57, 19.31it/s]

 23%|██▎       | 23055/100629 [18:20<59:59, 21.55it/s]

 23%|██▎       | 23059/100629 [18:20<51:18, 25.20it/s]

 23%|██▎       | 23062/100629 [18:20<52:00, 24.86it/s]

 23%|██▎       | 23065/100629 [18:20<58:11, 22.22it/s]

 23%|██▎       | 23068/100629 [18:20<56:27, 22.89it/s]

 23%|██▎       | 23071/100629 [18:21<1:00:44, 21.28it/s]

 23%|██▎       | 23074/100629 [18:21<59:25, 21.75it/s]

 23%|██▎       | 23077/100629 [18:21<1:00:52, 21.23it/s]

 23%|██▎       | 23080/100629 [18:21<1:18:48, 16.40it/s]

 23%|██▎       | 23082/100629 [18:21<1:16:36, 16.87it/s]

 23%|██▎       | 23084/100629 [18:21<1:14:54, 17.25it/s]

 23%|██▎       | 23087/100629 [18:22<1:17:36, 16.65it/s]

 23%|██▎       | 23089/100629 [18:22<1:15:52, 17.03it/s]

 23%|██▎       | 23092/100629 [18:22<1:07:46, 19.07it/s]

 23%|██▎       | 23096/100629 [18:22<56:09, 23.01it/s]

 23%|██▎       | 23099/100629 [18:22<55:24, 23.32it/s]

 23%|██▎       | 23102/100629 [18:22<53:25, 24.18it/s]

 23%|██▎       | 23105/100629 [18:22<52:58, 24.39it/s]

 23%|██▎       | 23108/100629 [18:22<51:38, 25.02it/s]

 23%|██▎       | 23111/100629 [18:23<1:00:15, 21.44it/s]

 23%|██▎       | 23115/100629 [18:23<55:05, 23.45it/s]

 23%|██▎       | 23118/100629 [18:23<56:26, 22.89it/s]

 23%|██▎       | 23121/100629 [18:23<1:05:37, 19.69it/s]

 23%|██▎       | 23124/100629 [18:23<1:05:06, 19.84it/s]

 23%|██▎       | 23127/100629 [18:23<1:10:40, 18.28it/s]

 23%|██▎       | 23131/100629 [18:24<1:03:29, 20.34it/s]

 23%|██▎       | 23134/100629 [18:24<1:01:42, 20.93it/s]

 23%|██▎       | 23137/100629 [18:24<1:01:24, 21.03it/s]

 23%|██▎       | 23142/100629 [18:24<50:46, 25.44it/s]

 23%|██▎       | 23145/100629 [18:24<54:53, 23.53it/s]

 23%|██▎       | 23148/100629 [18:24<55:50, 23.12it/s]

 23%|██▎       | 23151/100629 [18:24<58:45, 21.98it/s]

 23%|██▎       | 23155/100629 [18:25<59:32, 21.68it/s]

 23%|██▎       | 23158/100629 [18:25<1:03:16, 20.40it/s]

 23%|██▎       | 23161/100629 [18:25<1:03:33, 20.31it/s]

 23%|██▎       | 23164/100629 [18:25<1:17:27, 16.67it/s]

 23%|██▎       | 23167/100629 [18:25<1:10:40, 18.27it/s]

 23%|██▎       | 23169/100629 [18:25<1:13:41, 17.52it/s]

 23%|██▎       | 23171/100629 [18:26<1:16:35, 16.86it/s]

 23%|██▎       | 23174/100629 [18:26<1:16:47, 16.81it/s]

 23%|██▎       | 23176/100629 [18:26<1:17:28, 16.66it/s]

 23%|██▎       | 23178/100629 [18:26<1:18:13, 16.50it/s]

 23%|██▎       | 23180/100629 [18:26<1:26:01, 15.01it/s]

 23%|██▎       | 23182/100629 [18:26<1:21:51, 15.77it/s]

 23%|██▎       | 23186/100629 [18:26<1:05:49, 19.61it/s]

 23%|██▎       | 23189/100629 [18:27<59:00, 21.87it/s]

 23%|██▎       | 23193/100629 [18:27<1:02:22, 20.69it/s]

 23%|██▎       | 23196/100629 [18:27<1:07:46, 19.04it/s]

 23%|██▎       | 23198/100629 [18:27<1:08:51, 18.74it/s]

 23%|██▎       | 23201/100629 [18:27<1:13:05, 17.66it/s]

 23%|██▎       | 23203/100629 [18:27<1:23:25, 15.47it/s]

 23%|██▎       | 23207/100629 [18:28<1:10:15, 18.37it/s]

 23%|██▎       | 23210/100629 [18:28<1:10:26, 18.32it/s]

 23%|██▎       | 23212/100629 [18:28<1:09:21, 18.60it/s]

 23%|██▎       | 23214/100629 [18:28<1:08:15, 18.90it/s]

 23%|██▎       | 23216/100629 [18:28<1:10:06, 18.40it/s]

 23%|██▎       | 23218/100629 [18:28<1:11:00, 18.17it/s]

 23%|██▎       | 23221/100629 [18:28<1:01:01, 21.14it/s]

 23%|██▎       | 23224/100629 [18:28<59:10, 21.80it/s]

 23%|██▎       | 23227/100629 [18:29<1:04:00, 20.16it/s]

 23%|██▎       | 23231/100629 [18:29<52:39, 24.49it/s]

 23%|██▎       | 23234/100629 [18:29<53:19, 24.19it/s]

 23%|██▎       | 23237/100629 [18:29<52:51, 24.40it/s]

 23%|██▎       | 23240/100629 [18:29<1:05:05, 19.81it/s]

 23%|██▎       | 23243/100629 [18:29<1:04:25, 20.02it/s]

 23%|██▎       | 23246/100629 [18:29<58:52, 21.91it/s]

 23%|██▎       | 23249/100629 [18:30<1:08:28, 18.84it/s]

 23%|██▎       | 23252/100629 [18:30<1:17:18, 16.68it/s]

 23%|██▎       | 23255/100629 [18:30<1:11:43, 17.98it/s]

 23%|██▎       | 23258/100629 [18:30<1:06:32, 19.38it/s]

 23%|██▎       | 23262/100629 [18:30<58:49, 21.92it/s]

 23%|██▎       | 23265/100629 [18:30<57:54, 22.27it/s]

 23%|██▎       | 23268/100629 [18:31<1:03:02, 20.45it/s]

 23%|██▎       | 23271/100629 [18:31<1:13:41, 17.49it/s]

 23%|██▎       | 23273/100629 [18:31<1:13:30, 17.54it/s]

 23%|██▎       | 23275/100629 [18:31<1:14:29, 17.31it/s]

 23%|██▎       | 23277/100629 [18:32<4:05:16,  5.26it/s]

 23%|██▎       | 23280/100629 [18:32<2:58:10,  7.24it/s]

 23%|██▎       | 23283/100629 [18:32<2:18:00,  9.34it/s]

 23%|██▎       | 23286/100629 [18:33<1:58:48, 10.85it/s]

 23%|██▎       | 23290/100629 [18:33<1:27:21, 14.76it/s]

 23%|██▎       | 23293/100629 [18:33<1:18:56, 16.33it/s]

 23%|██▎       | 23296/100629 [18:33<1:13:11, 17.61it/s]

 23%|██▎       | 23299/100629 [18:33<1:12:11, 17.85it/s]

 23%|██▎       | 23302/100629 [18:33<1:19:53, 16.13it/s]

 23%|██▎       | 23306/100629 [18:34<1:03:00, 20.45it/s]

 23%|██▎       | 23312/100629 [18:34<45:57, 28.04it/s]

 23%|██▎       | 23316/100629 [18:34<44:41, 28.83it/s]

 23%|██▎       | 23320/100629 [18:34<50:37, 25.45it/s]

 23%|██▎       | 23325/100629 [18:34<46:40, 27.61it/s]

 23%|██▎       | 23330/100629 [18:34<42:29, 30.31it/s]

 23%|██▎       | 23334/100629 [18:34<51:04, 25.22it/s]

 23%|██▎       | 23337/100629 [18:35<51:05, 25.21it/s]

 23%|██▎       | 23340/100629 [18:35<50:52, 25.32it/s]

 23%|██▎       | 23343/100629 [18:35<1:01:31, 20.94it/s]

 23%|██▎       | 23349/100629 [18:35<49:51, 25.83it/s]

 23%|██▎       | 23352/100629 [18:35<57:23, 22.44it/s]

 23%|██▎       | 23355/100629 [18:35<55:18, 23.29it/s]

 23%|██▎       | 23358/100629 [18:35<52:55, 24.33it/s]

 23%|██▎       | 23361/100629 [18:36<55:31, 23.20it/s]

 23%|██▎       | 23365/100629 [18:36<50:44, 25.38it/s]

 23%|██▎       | 23368/100629 [18:36<49:57, 25.77it/s]

 23%|██▎       | 23371/100629 [18:36<49:16, 26.13it/s]

 23%|██▎       | 23374/100629 [18:36<1:05:54, 19.53it/s]

 23%|██▎       | 23377/100629 [18:36<1:05:31, 19.65it/s]

 23%|██▎       | 23380/100629 [18:37<1:05:43, 19.59it/s]

 23%|██▎       | 23385/100629 [18:37<52:16, 24.63it/s]

 23%|██▎       | 23388/100629 [18:37<54:25, 23.65it/s]

 23%|██▎       | 23391/100629 [18:37<53:20, 24.14it/s]

 23%|██▎       | 23394/100629 [18:37<52:25, 24.55it/s]

 23%|██▎       | 23397/100629 [18:37<57:07, 22.53it/s]

 23%|██▎       | 23400/100629 [18:37<56:26, 22.81it/s]

 23%|██▎       | 23403/100629 [18:37<58:31, 21.99it/s]

 23%|██▎       | 23406/100629 [18:38<57:30, 22.38it/s]

 23%|██▎       | 23409/100629 [18:38<58:01, 22.18it/s]

 23%|██▎       | 23412/100629 [18:38<1:00:19, 21.33it/s]

 23%|██▎       | 23415/100629 [18:38<55:50, 23.05it/s]

 23%|██▎       | 23418/100629 [18:38<52:36, 24.46it/s]

 23%|██▎       | 23421/100629 [18:38<57:37, 22.33it/s]

 23%|██▎       | 23424/100629 [18:38<56:20, 22.84it/s]

 23%|██▎       | 23427/100629 [18:39<59:04, 21.78it/s]

 23%|██▎       | 23430/100629 [18:39<56:44, 22.68it/s]

 23%|██▎       | 23433/100629 [18:39<1:03:55, 20.13it/s]

 23%|██▎       | 23436/100629 [18:39<1:10:53, 18.15it/s]

 23%|██▎       | 23439/100629 [18:39<1:06:21, 19.39it/s]

 23%|██▎       | 23442/100629 [18:39<1:06:51, 19.24it/s]

 23%|██▎       | 23446/100629 [18:39<55:23, 23.22it/s]

 23%|██▎       | 23450/100629 [18:40<55:33, 23.15it/s]

 23%|██▎       | 23453/100629 [18:40<1:09:47, 18.43it/s]

 23%|██▎       | 23457/100629 [18:40<59:36, 21.58it/s]

 23%|██▎       | 23460/100629 [18:40<1:00:20, 21.32it/s]

 23%|██▎       | 23464/100629 [18:40<54:01, 23.80it/s]

 23%|██▎       | 23467/100629 [18:40<53:10, 24.18it/s]

 23%|██▎       | 23470/100629 [18:41<57:31, 22.36it/s]

 23%|██▎       | 23473/100629 [18:41<59:55, 21.46it/s]

 23%|██▎       | 23476/100629 [18:41<58:21, 22.03it/s]

 23%|██▎       | 23480/100629 [18:41<59:04, 21.76it/s]

 23%|██▎       | 23483/100629 [18:41<57:47, 22.25it/s]

 23%|██▎       | 23486/100629 [18:41<57:26, 22.39it/s]

 23%|██▎       | 23489/100629 [18:41<59:31, 21.60it/s]

 23%|██▎       | 23492/100629 [18:42<1:01:09, 21.02it/s]

 23%|██▎       | 23495/100629 [18:42<59:04, 21.76it/s]

 23%|██▎       | 23498/100629 [18:42<54:51, 23.43it/s]

 23%|██▎       | 23502/100629 [18:42<48:59, 26.24it/s]

 23%|██▎       | 23505/100629 [18:42<47:36, 27.00it/s]

 23%|██▎       | 23508/100629 [18:42<56:29, 22.75it/s]

 23%|██▎       | 23511/100629 [18:42<1:01:25, 20.93it/s]

 23%|██▎       | 23514/100629 [18:43<1:08:12, 18.84it/s]

 23%|██▎       | 23517/100629 [18:43<1:13:31, 17.48it/s]

 23%|██▎       | 23519/100629 [18:43<1:12:49, 17.65it/s]

 23%|██▎       | 23521/100629 [18:43<1:12:50, 17.64it/s]

 23%|██▎       | 23523/100629 [18:43<1:17:52, 16.50it/s]

 23%|██▎       | 23525/100629 [18:43<1:14:32, 17.24it/s]

 23%|██▎       | 23528/100629 [18:43<1:16:53, 16.71it/s]

 23%|██▎       | 23531/100629 [18:44<1:12:09, 17.81it/s]

 23%|██▎       | 23533/100629 [18:44<1:20:27, 15.97it/s]

 23%|██▎       | 23536/100629 [18:44<1:15:35, 17.00it/s]

 23%|██▎       | 23538/100629 [18:44<1:13:20, 17.52it/s]

 23%|██▎       | 23540/100629 [18:44<1:13:03, 17.59it/s]

 23%|██▎       | 23542/100629 [18:44<1:11:32, 17.96it/s]

 23%|██▎       | 23545/100629 [18:44<1:01:15, 20.97it/s]

 23%|██▎       | 23548/100629 [18:44<59:23, 21.63it/s]

 23%|██▎       | 23551/100629 [18:45<1:01:24, 20.92it/s]

 23%|██▎       | 23556/100629 [18:45<52:00, 24.70it/s]

 23%|██▎       | 23560/100629 [18:45<1:00:47, 21.13it/s]

 23%|██▎       | 23563/100629 [18:45<1:00:26, 21.25it/s]

 23%|██▎       | 23566/100629 [18:45<1:00:31, 21.22it/s]

 23%|██▎       | 23569/100629 [18:45<58:46, 21.85it/s]

 23%|██▎       | 23572/100629 [18:46<57:12, 22.45it/s]

 23%|██▎       | 23575/100629 [18:46<56:07, 22.88it/s]

 23%|██▎       | 23578/100629 [18:46<1:01:13, 20.97it/s]

 23%|██▎       | 23581/100629 [18:46<56:42, 22.64it/s]

 23%|██▎       | 23584/100629 [18:46<58:30, 21.95it/s]

 23%|██▎       | 23587/100629 [18:46<1:04:08, 20.02it/s]

 23%|██▎       | 23590/100629 [18:46<1:05:14, 19.68it/s]

 23%|██▎       | 23594/100629 [18:47<56:15, 22.82it/s]

 23%|██▎       | 23599/100629 [18:47<44:48, 28.65it/s]

 23%|██▎       | 23603/100629 [18:47<45:36, 28.15it/s]

 23%|██▎       | 23606/100629 [18:47<50:45, 25.29it/s]

 23%|██▎       | 23609/100629 [18:47<51:04, 25.14it/s]

 23%|██▎       | 23612/100629 [18:47<58:11, 22.06it/s]

 23%|██▎       | 23615/100629 [18:47<1:04:21, 19.94it/s]

 23%|██▎       | 23618/100629 [18:48<59:08, 21.70it/s]

 23%|██▎       | 23621/100629 [18:48<1:03:15, 20.29it/s]

 23%|██▎       | 23624/100629 [18:48<1:00:23, 21.25it/s]

 23%|██▎       | 23627/100629 [18:48<1:03:04, 20.35it/s]

 23%|██▎       | 23631/100629 [18:48<52:01, 24.67it/s]

 23%|██▎       | 23634/100629 [18:48<54:47, 23.42it/s]

 23%|██▎       | 23637/100629 [18:48<54:49, 23.40it/s]

 23%|██▎       | 23640/100629 [18:49<1:03:33, 20.19it/s]

 23%|██▎       | 23643/100629 [18:49<1:11:35, 17.92it/s]

 23%|██▎       | 23646/100629 [18:49<1:10:46, 18.13it/s]

 24%|██▎       | 23651/100629 [18:49<54:07, 23.71it/s]

 24%|██▎       | 23654/100629 [18:49<53:24, 24.02it/s]

 24%|██▎       | 23657/100629 [18:49<55:07, 23.28it/s]

 24%|██▎       | 23660/100629 [18:49<52:19, 24.51it/s]

 24%|██▎       | 23663/100629 [18:50<55:16, 23.21it/s]

 24%|██▎       | 23666/100629 [18:50<56:12, 22.82it/s]

 24%|██▎       | 23669/100629 [18:50<57:32, 22.29it/s]

 24%|██▎       | 23672/100629 [18:50<1:00:33, 21.18it/s]

 24%|██▎       | 23676/100629 [18:50<56:23, 22.75it/s]

 24%|██▎       | 23680/100629 [18:50<49:16, 26.03it/s]

 24%|██▎       | 23684/100629 [18:50<44:07, 29.06it/s]

 24%|██▎       | 23689/100629 [18:51<40:48, 31.42it/s]

 24%|██▎       | 23693/100629 [18:51<57:01, 22.49it/s]

 24%|██▎       | 23697/100629 [18:51<51:17, 25.00it/s]

 24%|██▎       | 23700/100629 [18:51<50:32, 25.37it/s]

 24%|██▎       | 23703/100629 [18:51<51:25, 24.93it/s]

 24%|██▎       | 23706/100629 [18:51<52:13, 24.55it/s]

 24%|██▎       | 23709/100629 [18:52<1:01:35, 20.81it/s]

 24%|██▎       | 23712/100629 [18:52<1:08:12, 18.79it/s]

 24%|██▎       | 23715/100629 [18:52<1:08:30, 18.71it/s]

 24%|██▎       | 23719/100629 [18:52<58:56, 21.75it/s]

 24%|██▎       | 23722/100629 [18:52<1:06:04, 19.40it/s]

 24%|██▎       | 23725/100629 [18:52<1:09:38, 18.41it/s]

 24%|██▎       | 23728/100629 [18:53<1:08:46, 18.64it/s]

 24%|██▎       | 23731/100629 [18:53<1:12:21, 17.71it/s]

 24%|██▎       | 23734/100629 [18:53<1:05:40, 19.51it/s]

 24%|██▎       | 23737/100629 [18:53<1:10:20, 18.22it/s]

 24%|██▎       | 23739/100629 [18:53<1:12:00, 17.80it/s]

 24%|██▎       | 23742/100629 [18:53<1:07:08, 19.08it/s]

 24%|██▎       | 23744/100629 [18:53<1:16:25, 16.77it/s]

 24%|██▎       | 23747/100629 [18:54<1:11:53, 17.82it/s]

 24%|██▎       | 23750/100629 [18:54<1:05:04, 19.69it/s]

 24%|██▎       | 23754/100629 [18:54<54:36, 23.46it/s]

 24%|██▎       | 23757/100629 [18:54<1:03:44, 20.10it/s]

 24%|██▎       | 23760/100629 [18:54<58:26, 21.92it/s]

 24%|██▎       | 23763/100629 [18:54<1:07:03, 19.11it/s]

 24%|██▎       | 23766/100629 [18:55<1:12:42, 17.62it/s]

 24%|██▎       | 23768/100629 [18:55<1:14:14, 17.26it/s]

 24%|██▎       | 23771/100629 [18:55<1:05:57, 19.42it/s]

 24%|██▎       | 23775/100629 [18:55<54:19, 23.58it/s]

 24%|██▎       | 23778/100629 [18:55<51:49, 24.72it/s]

 24%|██▎       | 23781/100629 [18:55<57:22, 22.32it/s]

 24%|██▎       | 23785/100629 [18:55<55:24, 23.11it/s]

 24%|██▎       | 23788/100629 [18:56<1:01:41, 20.76it/s]

 24%|██▎       | 23792/100629 [18:56<55:02, 23.27it/s]

 24%|██▎       | 23795/100629 [18:56<54:11, 23.63it/s]

 24%|██▎       | 23799/100629 [18:56<49:54, 25.65it/s]

 24%|██▎       | 23802/100629 [18:56<59:45, 21.43it/s]

 24%|██▎       | 23806/100629 [18:56<56:56, 22.48it/s]

 24%|██▎       | 23809/100629 [18:56<1:02:50, 20.37it/s]

 24%|██▎       | 23812/100629 [18:57<1:09:32, 18.41it/s]

 24%|██▎       | 23814/100629 [18:57<1:10:06, 18.26it/s]

 24%|██▎       | 23817/100629 [18:57<1:07:01, 19.10it/s]

 24%|██▎       | 23820/100629 [18:57<1:02:41, 20.42it/s]

 24%|██▎       | 23823/100629 [18:57<1:11:39, 17.87it/s]

 24%|██▎       | 23826/100629 [18:57<1:09:47, 18.34it/s]

 24%|██▎       | 23828/100629 [18:58<1:15:12, 17.02it/s]

 24%|██▎       | 23830/100629 [18:58<1:16:41, 16.69it/s]

 24%|██▎       | 23832/100629 [18:58<1:35:13, 13.44it/s]

 24%|██▎       | 23834/100629 [18:58<1:28:05, 14.53it/s]

 24%|██▎       | 23837/100629 [18:58<1:17:27, 16.52it/s]

 24%|██▎       | 23841/100629 [18:58<1:11:07, 17.99it/s]

 24%|██▎       | 23843/100629 [18:59<1:13:13, 17.48it/s]

 24%|██▎       | 23846/100629 [18:59<1:08:18, 18.73it/s]

 24%|██▎       | 23848/100629 [18:59<1:16:12, 16.79it/s]

 24%|██▎       | 23851/100629 [18:59<1:06:02, 19.38it/s]

 24%|██▎       | 23854/100629 [18:59<1:00:52, 21.02it/s]

 24%|██▎       | 23857/100629 [18:59<1:01:35, 20.77it/s]

 24%|██▎       | 23860/100629 [18:59<59:54, 21.36it/s]

 24%|██▎       | 23863/100629 [18:59<58:20, 21.93it/s]

 24%|██▎       | 23866/100629 [19:00<55:17, 23.14it/s]

 24%|██▎       | 23870/100629 [19:00<49:43, 25.73it/s]

 24%|██▎       | 23873/100629 [19:00<52:45, 24.25it/s]

 24%|██▎       | 23876/100629 [19:00<51:07, 25.02it/s]

 24%|██▎       | 23879/100629 [19:00<55:48, 22.92it/s]

 24%|██▎       | 23882/100629 [19:00<52:31, 24.35it/s]

 24%|██▎       | 23885/100629 [19:00<1:00:07, 21.28it/s]

 24%|██▎       | 23891/100629 [19:01<46:05, 27.75it/s]

 24%|██▎       | 23895/100629 [19:01<47:23, 26.99it/s]

 24%|██▎       | 23898/100629 [19:01<50:45, 25.19it/s]

 24%|██▍       | 23901/100629 [19:01<48:53, 26.16it/s]

 24%|██▍       | 23907/100629 [19:01<38:54, 32.86it/s]

 24%|██▍       | 23911/100629 [19:01<38:58, 32.80it/s]

 24%|██▍       | 23915/100629 [19:01<38:57, 32.82it/s]

 24%|██▍       | 23919/100629 [19:01<39:50, 32.10it/s]

 24%|██▍       | 23923/100629 [19:02<45:07, 28.33it/s]

 24%|██▍       | 23926/100629 [19:02<53:45, 23.78it/s]

 24%|██▍       | 23929/100629 [19:02<56:31, 22.62it/s]

 24%|██▍       | 23932/100629 [19:02<54:02, 23.66it/s]

 24%|██▍       | 23935/100629 [19:02<1:05:44, 19.44it/s]

 24%|██▍       | 23938/100629 [19:02<1:10:03, 18.24it/s]

 24%|██▍       | 23941/100629 [19:03<1:07:05, 19.05it/s]

 24%|██▍       | 23944/100629 [19:03<1:12:36, 17.60it/s]

 24%|██▍       | 23947/100629 [19:03<1:06:30, 19.22it/s]

 24%|██▍       | 23950/100629 [19:03<1:18:25, 16.29it/s]

 24%|██▍       | 23953/100629 [19:03<1:15:30, 16.92it/s]

 24%|██▍       | 23955/100629 [19:03<1:13:20, 17.42it/s]

 24%|██▍       | 23957/100629 [19:04<1:12:42, 17.57it/s]

 24%|██▍       | 23960/100629 [19:04<1:10:08, 18.22it/s]

 24%|██▍       | 23962/100629 [19:04<1:18:14, 16.33it/s]

 24%|██▍       | 23964/100629 [19:04<1:15:33, 16.91it/s]

 24%|██▍       | 23966/100629 [19:04<1:14:15, 17.21it/s]

 24%|██▍       | 23968/100629 [19:04<1:14:02, 17.26it/s]

 24%|██▍       | 23972/100629 [19:04<1:11:41, 17.82it/s]

 24%|██▍       | 23974/100629 [19:05<1:19:56, 15.98it/s]

 24%|██▍       | 23978/100629 [19:05<1:02:45, 20.36it/s]

 24%|██▍       | 23981/100629 [19:05<1:02:50, 20.33it/s]

 24%|██▍       | 23984/100629 [19:05<1:05:25, 19.52it/s]

 24%|██▍       | 23987/100629 [19:05<1:04:57, 19.67it/s]

 24%|██▍       | 23990/100629 [19:05<1:08:22, 18.68it/s]

 24%|██▍       | 23993/100629 [19:05<1:05:59, 19.35it/s]

 24%|██▍       | 23995/100629 [19:06<1:07:55, 18.80it/s]

 24%|██▍       | 23997/100629 [19:06<1:07:56, 18.80it/s]

 24%|██▍       | 23999/100629 [19:06<1:07:25, 18.94it/s]

 24%|██▍       | 24002/100629 [19:06<1:06:11, 19.29it/s]

 24%|██▍       | 24005/100629 [19:06<1:00:09, 21.23it/s]

 24%|██▍       | 24008/100629 [19:06<57:01, 22.39it/s]

 24%|██▍       | 24012/100629 [19:06<56:26, 22.62it/s]

 24%|██▍       | 24015/100629 [19:07<57:33, 22.19it/s]

 24%|██▍       | 24018/100629 [19:07<1:03:53, 19.98it/s]

 24%|██▍       | 24021/100629 [19:07<1:02:29, 20.43it/s]

 24%|██▍       | 24024/100629 [19:07<1:03:40, 20.05it/s]

 24%|██▍       | 24028/100629 [19:07<58:04, 21.98it/s]

 24%|██▍       | 24031/100629 [19:07<57:31, 22.20it/s]

 24%|██▍       | 24034/100629 [19:07<55:54, 22.83it/s]

 24%|██▍       | 24037/100629 [19:08<1:10:05, 18.21it/s]

 24%|██▍       | 24041/100629 [19:08<1:03:03, 20.24it/s]

 24%|██▍       | 24044/100629 [19:08<1:01:51, 20.63it/s]

 24%|██▍       | 24047/100629 [19:08<1:00:20, 21.15it/s]

 24%|██▍       | 24050/100629 [19:08<1:06:12, 19.28it/s]

 24%|██▍       | 24054/100629 [19:08<1:01:13, 20.84it/s]

 24%|██▍       | 24057/100629 [19:09<1:02:19, 20.48it/s]

 24%|██▍       | 24061/100629 [19:09<55:48, 22.86it/s]

 24%|██▍       | 24064/100629 [19:09<55:56, 22.81it/s]

 24%|██▍       | 24067/100629 [19:09<52:32, 24.28it/s]

 24%|██▍       | 24072/100629 [19:09<43:08, 29.57it/s]

 24%|██▍       | 24076/100629 [19:09<44:50, 28.46it/s]

 24%|██▍       | 24079/100629 [19:09<50:13, 25.41it/s]

 24%|██▍       | 24082/100629 [19:09<49:02, 26.02it/s]

 24%|██▍       | 24085/100629 [19:10<51:16, 24.88it/s]

 24%|██▍       | 24089/100629 [19:10<49:18, 25.87it/s]

 24%|██▍       | 24092/100629 [19:10<1:05:02, 19.61it/s]

 24%|██▍       | 24095/100629 [19:10<1:01:02, 20.90it/s]

 24%|██▍       | 24098/100629 [19:10<1:00:43, 21.00it/s]

 24%|██▍       | 24101/100629 [19:10<59:11, 21.55it/s]

 24%|██▍       | 24105/100629 [19:11<53:14, 23.96it/s]

 24%|██▍       | 24108/100629 [19:11<58:35, 21.76it/s]

 24%|██▍       | 24111/100629 [19:11<1:07:14, 18.97it/s]

 24%|██▍       | 24114/100629 [19:11<1:08:47, 18.54it/s]

 24%|██▍       | 24117/100629 [19:11<1:05:25, 19.49it/s]

 24%|██▍       | 24121/100629 [19:11<53:28, 23.84it/s]

 24%|██▍       | 24124/100629 [19:12<1:01:27, 20.75it/s]

 24%|██▍       | 24127/100629 [19:12<1:10:56, 17.98it/s]

 24%|██▍       | 24130/100629 [19:12<1:04:29, 19.77it/s]

 24%|██▍       | 24133/100629 [19:12<1:04:53, 19.65it/s]

 24%|██▍       | 24136/100629 [19:12<59:50, 21.31it/s]

 24%|██▍       | 24139/100629 [19:12<55:16, 23.06it/s]

 24%|██▍       | 24142/100629 [19:12<56:36, 22.52it/s]

 24%|██▍       | 24146/100629 [19:13<55:22, 23.02it/s]

 24%|██▍       | 24149/100629 [19:13<1:00:50, 20.95it/s]

 24%|██▍       | 24152/100629 [19:13<1:06:41, 19.11it/s]

 24%|██▍       | 24156/100629 [19:13<57:51, 22.03it/s]

 24%|██▍       | 24159/100629 [19:13<59:07, 21.55it/s]

 24%|██▍       | 24162/100629 [19:13<59:20, 21.47it/s]

 24%|██▍       | 24165/100629 [19:13<1:04:38, 19.72it/s]

 24%|██▍       | 24169/100629 [19:14<56:44, 22.46it/s]

 24%|██▍       | 24173/100629 [19:14<53:01, 24.03it/s]

 24%|██▍       | 24177/100629 [19:14<49:19, 25.83it/s]

 24%|██▍       | 24180/100629 [19:14<53:27, 23.84it/s]

 24%|██▍       | 24183/100629 [19:14<57:09, 22.29it/s]

 24%|██▍       | 24186/100629 [19:14<55:51, 22.81it/s]

 24%|██▍       | 24189/100629 [19:14<59:11, 21.53it/s]

 24%|██▍       | 24192/100629 [19:15<1:05:25, 19.47it/s]

 24%|██▍       | 24195/100629 [19:15<1:05:18, 19.51it/s]

 24%|██▍       | 24197/100629 [19:15<1:07:02, 19.00it/s]

 24%|██▍       | 24200/100629 [19:15<1:01:59, 20.55it/s]

 24%|██▍       | 24203/100629 [19:15<1:00:38, 21.01it/s]

 24%|██▍       | 24206/100629 [19:15<1:00:02, 21.21it/s]

 24%|██▍       | 24210/100629 [19:15<51:11, 24.88it/s]

 24%|██▍       | 24214/100629 [19:16<47:51, 26.61it/s]

 24%|██▍       | 24218/100629 [19:16<47:59, 26.53it/s]

 24%|██▍       | 24221/100629 [19:16<54:12, 23.49it/s]

 24%|██▍       | 24224/100629 [19:16<51:52, 24.55it/s]

 24%|██▍       | 24228/100629 [19:16<49:35, 25.67it/s]

 24%|██▍       | 24231/100629 [19:16<49:00, 25.98it/s]

 24%|██▍       | 24234/100629 [19:16<49:04, 25.94it/s]

 24%|██▍       | 24237/100629 [19:17<50:12, 25.36it/s]

 24%|██▍       | 24241/100629 [19:17<47:11, 26.97it/s]

 24%|██▍       | 24244/100629 [19:17<1:00:48, 20.94it/s]

 24%|██▍       | 24247/100629 [19:17<59:41, 21.33it/s]

 24%|██▍       | 24250/100629 [19:17<1:01:01, 20.86it/s]

 24%|██▍       | 24253/100629 [19:17<1:00:53, 20.91it/s]

 24%|██▍       | 24257/100629 [19:17<52:51, 24.08it/s]

 24%|██▍       | 24262/100629 [19:18<42:55, 29.66it/s]

 24%|██▍       | 24266/100629 [19:18<52:11, 24.38it/s]

 24%|██▍       | 24271/100629 [19:18<48:00, 26.51it/s]

 24%|██▍       | 24274/100629 [19:18<48:21, 26.31it/s]

 24%|██▍       | 24277/100629 [19:18<54:43, 23.25it/s]

 24%|██▍       | 24280/100629 [19:18<1:08:02, 18.70it/s]

 24%|██▍       | 24283/100629 [19:19<1:03:20, 20.09it/s]

 24%|██▍       | 24286/100629 [19:19<1:02:43, 20.28it/s]

 24%|██▍       | 24289/100629 [19:19<1:00:19, 21.09it/s]

 24%|██▍       | 24292/100629 [19:19<1:13:36, 17.28it/s]

 24%|██▍       | 24294/100629 [19:19<1:13:58, 17.20it/s]

 24%|██▍       | 24297/100629 [19:20<1:31:55, 13.84it/s]

 24%|██▍       | 24299/100629 [19:20<1:27:17, 14.57it/s]

 24%|██▍       | 24301/100629 [19:20<1:22:11, 15.48it/s]

 24%|██▍       | 24304/100629 [19:20<1:11:09, 17.88it/s]

 24%|██▍       | 24307/100629 [19:20<1:06:39, 19.08it/s]

 24%|██▍       | 24310/100629 [19:20<1:08:19, 18.62it/s]

 24%|██▍       | 24312/100629 [19:20<1:20:40, 15.77it/s]

 24%|██▍       | 24315/100629 [19:20<1:12:53, 17.45it/s]

 24%|██▍       | 24318/100629 [19:21<1:13:35, 17.28it/s]

 24%|██▍       | 24323/100629 [19:21<1:01:19, 20.74it/s]

 24%|██▍       | 24326/100629 [19:21<1:01:52, 20.55it/s]

 24%|██▍       | 24329/100629 [19:21<1:06:14, 19.20it/s]

 24%|██▍       | 24331/100629 [19:21<1:12:36, 17.51it/s]

 24%|██▍       | 24335/100629 [19:21<1:02:51, 20.23it/s]

 24%|██▍       | 24340/100629 [19:22<49:25, 25.73it/s]

 24%|██▍       | 24343/100629 [19:22<54:42, 23.24it/s]

 24%|██▍       | 24346/100629 [19:22<51:48, 24.54it/s]

 24%|██▍       | 24350/100629 [19:22<50:08, 25.35it/s]

 24%|██▍       | 24353/100629 [19:22<1:03:28, 20.03it/s]

 24%|██▍       | 24356/100629 [19:22<58:28, 21.74it/s]

 24%|██▍       | 24360/100629 [19:22<49:22, 25.74it/s]

 24%|██▍       | 24363/100629 [19:23<1:00:06, 21.15it/s]

 24%|██▍       | 24366/100629 [19:23<59:47, 21.26it/s]

 24%|██▍       | 24369/100629 [19:23<57:06, 22.25it/s]

 24%|██▍       | 24372/100629 [19:23<56:29, 22.50it/s]

 24%|██▍       | 24375/100629 [19:23<57:54, 21.95it/s]

 24%|██▍       | 24378/100629 [19:23<1:08:21, 18.59it/s]

 24%|██▍       | 24382/100629 [19:24<58:12, 21.83it/s]

 24%|██▍       | 24385/100629 [19:24<57:36, 22.06it/s]

 24%|██▍       | 24388/100629 [19:24<1:03:49, 19.91it/s]

 24%|██▍       | 24391/100629 [19:24<1:07:54, 18.71it/s]

 24%|██▍       | 24394/100629 [19:24<1:02:54, 20.20it/s]

 24%|██▍       | 24397/100629 [19:24<1:01:47, 20.56it/s]

 24%|██▍       | 24400/100629 [19:24<1:03:42, 19.94it/s]

 24%|██▍       | 24403/100629 [19:25<1:08:06, 18.66it/s]

 24%|██▍       | 24405/100629 [19:25<1:12:04, 17.63it/s]

 24%|██▍       | 24408/100629 [19:25<1:04:17, 19.76it/s]

 24%|██▍       | 24411/100629 [19:25<58:55, 21.56it/s]

 24%|██▍       | 24414/100629 [19:25<59:56, 21.19it/s]

 24%|██▍       | 24417/100629 [19:25<58:50, 21.59it/s]

 24%|██▍       | 24420/100629 [19:25<55:23, 22.93it/s]

 24%|██▍       | 24423/100629 [19:26<59:56, 21.19it/s]

 24%|██▍       | 24426/100629 [19:26<58:14, 21.81it/s]

 24%|██▍       | 24429/100629 [19:26<56:11, 22.60it/s]

 24%|██▍       | 24433/100629 [19:26<56:44, 22.38it/s]

 24%|██▍       | 24436/100629 [19:26<58:18, 21.78it/s]

 24%|██▍       | 24439/100629 [19:26<59:45, 21.25it/s]

 24%|██▍       | 24442/100629 [19:26<59:35, 21.31it/s]

 24%|██▍       | 24445/100629 [19:27<1:00:34, 20.96it/s]

 24%|██▍       | 24448/100629 [19:27<1:01:02, 20.80it/s]

 24%|██▍       | 24451/100629 [19:27<59:06, 21.48it/s]

 24%|██▍       | 24454/100629 [19:27<1:09:16, 18.33it/s]

 24%|██▍       | 24457/100629 [19:27<1:09:44, 18.20it/s]

 24%|██▍       | 24460/100629 [19:27<1:04:25, 19.71it/s]

 24%|██▍       | 24463/100629 [19:28<1:04:42, 19.62it/s]

 24%|██▍       | 24467/100629 [19:28<54:19, 23.37it/s]

 24%|██▍       | 24471/100629 [19:28<50:04, 25.35it/s]

 24%|██▍       | 24476/100629 [19:28<44:37, 28.44it/s]

 24%|██▍       | 24479/100629 [19:28<54:11, 23.42it/s]

 24%|██▍       | 24482/100629 [19:28<1:04:14, 19.75it/s]

 24%|██▍       | 24487/100629 [19:28<53:28, 23.73it/s]

 24%|██▍       | 24490/100629 [19:29<51:05, 24.84it/s]

 24%|██▍       | 24493/100629 [19:29<56:56, 22.28it/s]

 24%|██▍       | 24496/100629 [19:29<55:30, 22.86it/s]

 24%|██▍       | 24499/100629 [19:29<1:04:12, 19.76it/s]

 24%|██▍       | 24502/100629 [19:29<1:05:50, 19.27it/s]

 24%|██▍       | 24505/100629 [19:29<1:04:03, 19.80it/s]

 24%|██▍       | 24508/100629 [19:30<1:01:59, 20.47it/s]

 24%|██▍       | 24511/100629 [19:30<58:24, 21.72it/s]

 24%|██▍       | 24514/100629 [19:30<56:17, 22.53it/s]

 24%|██▍       | 24518/100629 [19:30<49:44, 25.50it/s]

 24%|██▍       | 24521/100629 [19:30<49:58, 25.38it/s]

 24%|██▍       | 24524/100629 [19:30<58:51, 21.55it/s]

 24%|██▍       | 24527/100629 [19:30<1:01:41, 20.56it/s]

 24%|██▍       | 24530/100629 [19:31<1:12:35, 17.47it/s]

 24%|██▍       | 24533/100629 [19:31<1:06:46, 18.99it/s]

 24%|██▍       | 24536/100629 [19:31<1:07:29, 18.79it/s]

 24%|██▍       | 24538/100629 [19:31<1:15:25, 16.81it/s]

 24%|██▍       | 24540/100629 [19:31<1:17:04, 16.45it/s]

 24%|██▍       | 24543/100629 [19:31<1:10:06, 18.09it/s]

 24%|██▍       | 24545/100629 [19:31<1:13:48, 17.18it/s]

 24%|██▍       | 24548/100629 [19:32<1:03:02, 20.11it/s]

 24%|██▍       | 24551/100629 [19:32<1:00:18, 21.03it/s]

 24%|██▍       | 24554/100629 [19:32<1:04:59, 19.51it/s]

 24%|██▍       | 24557/100629 [19:32<1:06:53, 18.95it/s]

 24%|██▍       | 24562/100629 [19:32<51:50, 24.46it/s]

 24%|██▍       | 24565/100629 [19:32<51:52, 24.44it/s]

 24%|██▍       | 24568/100629 [19:32<57:00, 22.24it/s]

 24%|██▍       | 24572/100629 [19:33<51:19, 24.70it/s]

 24%|██▍       | 24575/100629 [19:33<54:41, 23.18it/s]

 24%|██▍       | 24579/100629 [19:33<47:44, 26.55it/s]

 24%|██▍       | 24582/100629 [19:33<53:19, 23.77it/s]

 24%|██▍       | 24585/100629 [19:33<53:16, 23.79it/s]

 24%|██▍       | 24589/100629 [19:33<57:53, 21.89it/s]

 24%|██▍       | 24592/100629 [19:33<56:19, 22.50it/s]

 24%|██▍       | 24595/100629 [19:34<56:22, 22.48it/s]

 24%|██▍       | 24598/100629 [19:34<53:11, 23.82it/s]

 24%|██▍       | 24601/100629 [19:34<57:22, 22.09it/s]

 24%|██▍       | 24604/100629 [19:34<54:38, 23.19it/s]

 24%|██▍       | 24610/100629 [19:34<45:37, 27.77it/s]

 24%|██▍       | 24614/100629 [19:34<47:04, 26.91it/s]

 24%|██▍       | 24617/100629 [19:34<53:47, 23.55it/s]

 24%|██▍       | 24620/100629 [19:35<52:25, 24.16it/s]

 24%|██▍       | 24624/100629 [19:35<50:47, 24.94it/s]

 24%|██▍       | 24628/100629 [19:35<46:33, 27.21it/s]

 24%|██▍       | 24631/100629 [19:35<55:11, 22.95it/s]

 24%|██▍       | 24634/100629 [19:35<57:20, 22.09it/s]

 24%|██▍       | 24637/100629 [19:35<54:31, 23.23it/s]

 24%|██▍       | 24640/100629 [19:35<51:06, 24.78it/s]

 24%|██▍       | 24643/100629 [19:36<50:47, 24.94it/s]

 24%|██▍       | 24647/100629 [19:36<45:31, 27.81it/s]

 24%|██▍       | 24650/100629 [19:36<46:10, 27.42it/s]

 24%|██▍       | 24654/100629 [19:36<45:12, 28.01it/s]

 25%|██▍       | 24657/100629 [19:36<51:30, 24.58it/s]

 25%|██▍       | 24660/100629 [19:36<49:30, 25.57it/s]

 25%|██▍       | 24663/100629 [19:36<47:59, 26.38it/s]

 25%|██▍       | 24666/100629 [19:36<53:16, 23.77it/s]

 25%|██▍       | 24669/100629 [19:37<1:03:06, 20.06it/s]

 25%|██▍       | 24672/100629 [19:37<57:46, 21.91it/s]

 25%|██▍       | 24675/100629 [19:37<1:09:12, 18.29it/s]

 25%|██▍       | 24678/100629 [19:37<1:09:12, 18.29it/s]

 25%|██▍       | 24681/100629 [19:37<1:03:07, 20.05it/s]

 25%|██▍       | 24686/100629 [19:37<50:55, 24.86it/s]

 25%|██▍       | 24689/100629 [19:38<1:06:34, 19.01it/s]

 25%|██▍       | 24692/100629 [19:38<1:04:32, 19.61it/s]

 25%|██▍       | 24695/100629 [19:38<58:38, 21.58it/s]

 25%|██▍       | 24698/100629 [19:38<55:29, 22.81it/s]

 25%|██▍       | 24701/100629 [19:38<58:23, 21.67it/s]

 25%|██▍       | 24705/100629 [19:38<53:09, 23.80it/s]

 25%|██▍       | 24708/100629 [19:38<57:09, 22.14it/s]

 25%|██▍       | 24711/100629 [19:39<1:03:31, 19.92it/s]

 25%|██▍       | 24714/100629 [19:39<1:00:41, 20.85it/s]

 25%|██▍       | 24719/100629 [19:39<1:09:07, 18.30it/s]

 25%|██▍       | 24722/100629 [19:39<1:06:10, 19.12it/s]

 25%|██▍       | 24725/100629 [19:39<1:08:42, 18.41it/s]

 25%|██▍       | 24727/100629 [19:39<1:08:09, 18.56it/s]

 25%|██▍       | 24730/100629 [19:40<1:03:37, 19.88it/s]

 25%|██▍       | 24735/100629 [19:40<48:43, 25.96it/s]

 25%|██▍       | 24738/100629 [19:40<51:01, 24.79it/s]

 25%|██▍       | 24741/100629 [19:40<54:13, 23.33it/s]

 25%|██▍       | 24745/100629 [19:40<49:32, 25.53it/s]

 25%|██▍       | 24748/100629 [19:40<48:06, 26.29it/s]

 25%|██▍       | 24751/100629 [19:40<46:49, 27.01it/s]

 25%|██▍       | 24754/100629 [19:40<50:08, 25.22it/s]

 25%|██▍       | 24758/100629 [19:41<48:07, 26.27it/s]

 25%|██▍       | 24761/100629 [19:41<53:13, 23.75it/s]

 25%|██▍       | 24764/100629 [19:41<50:34, 25.00it/s]

 25%|██▍       | 24767/100629 [19:41<58:17, 21.69it/s]

 25%|██▍       | 24773/100629 [19:41<44:08, 28.65it/s]

 25%|██▍       | 24777/100629 [19:41<49:50, 25.37it/s]

 25%|██▍       | 24780/100629 [19:42<52:07, 24.25it/s]

 25%|██▍       | 24783/100629 [19:42<51:28, 24.55it/s]

 25%|██▍       | 24786/100629 [19:42<53:42, 23.53it/s]

 25%|██▍       | 24789/100629 [19:42<56:35, 22.33it/s]

 25%|██▍       | 24793/100629 [19:42<58:07, 21.74it/s]

 25%|██▍       | 24796/100629 [19:43<1:25:33, 14.77it/s]

 25%|██▍       | 24799/100629 [19:43<1:18:07, 16.18it/s]

 25%|██▍       | 24802/100629 [19:43<1:08:37, 18.42it/s]

 25%|██▍       | 24805/100629 [19:43<1:06:01, 19.14it/s]

 25%|██▍       | 24808/100629 [19:43<1:11:25, 17.69it/s]

 25%|██▍       | 24811/100629 [19:43<1:10:32, 17.91it/s]

 25%|██▍       | 24814/100629 [19:43<1:04:27, 19.60it/s]

 25%|██▍       | 24817/100629 [19:44<1:06:56, 18.87it/s]

 25%|██▍       | 24819/100629 [19:44<1:08:21, 18.48it/s]

 25%|██▍       | 24823/100629 [19:44<58:18, 21.67it/s]

 25%|██▍       | 24826/100629 [19:44<59:29, 21.23it/s]

 25%|██▍       | 24831/100629 [19:44<48:14, 26.19it/s]

 25%|██▍       | 24834/100629 [19:44<51:48, 24.38it/s]

 25%|██▍       | 24837/100629 [19:44<52:49, 23.91it/s]

 25%|██▍       | 24840/100629 [19:45<54:19, 23.25it/s]

 25%|██▍       | 24843/100629 [19:45<59:20, 21.28it/s]

 25%|██▍       | 24846/100629 [19:45<55:08, 22.90it/s]

 25%|██▍       | 24849/100629 [19:45<53:49, 23.47it/s]

 25%|██▍       | 24852/100629 [19:45<50:56, 24.79it/s]

 25%|██▍       | 24855/100629 [19:45<54:38, 23.11it/s]

 25%|██▍       | 24858/100629 [19:45<51:12, 24.66it/s]

 25%|██▍       | 24861/100629 [19:46<1:05:13, 19.36it/s]

 25%|██▍       | 24864/100629 [19:46<1:03:23, 19.92it/s]

 25%|██▍       | 24867/100629 [19:46<1:02:34, 20.18it/s]

 25%|██▍       | 24873/100629 [19:46<44:17, 28.51it/s]

 25%|██▍       | 24877/100629 [19:46<41:34, 30.37it/s]

 25%|██▍       | 24881/100629 [19:46<47:42, 26.47it/s]

 25%|██▍       | 24884/100629 [19:46<50:01, 25.24it/s]

 25%|██▍       | 24888/100629 [19:46<45:51, 27.53it/s]

 25%|██▍       | 24891/100629 [19:47<52:02, 24.26it/s]

 25%|██▍       | 24894/100629 [19:47<51:24, 24.55it/s]

 25%|██▍       | 24897/100629 [19:47<54:07, 23.32it/s]

 25%|██▍       | 24900/100629 [19:47<51:03, 24.72it/s]

 25%|██▍       | 24904/100629 [19:47<50:57, 24.77it/s]

 25%|██▍       | 24908/100629 [19:47<46:25, 27.19it/s]

 25%|██▍       | 24912/100629 [19:47<46:46, 26.98it/s]

 25%|██▍       | 24917/100629 [19:48<41:59, 30.05it/s]

 25%|██▍       | 24921/100629 [19:48<55:53, 22.58it/s]

 25%|██▍       | 24924/100629 [19:48<52:59, 23.81it/s]

 25%|██▍       | 24927/100629 [19:48<50:22, 25.05it/s]

 25%|██▍       | 24930/100629 [19:48<56:12, 22.45it/s]

 25%|██▍       | 24933/100629 [19:48<52:40, 23.95it/s]

 25%|██▍       | 24936/100629 [19:48<53:30, 23.58it/s]

 25%|██▍       | 24939/100629 [19:49<57:56, 21.77it/s]

 25%|██▍       | 24942/100629 [19:49<1:00:28, 20.86it/s]

 25%|██▍       | 24945/100629 [19:49<58:55, 21.41it/s]

 25%|██▍       | 24948/100629 [19:49<1:19:24, 15.89it/s]

 25%|██▍       | 24951/100629 [19:49<1:16:16, 16.53it/s]

 25%|██▍       | 24954/100629 [19:50<1:13:50, 17.08it/s]

 25%|██▍       | 24957/100629 [19:50<1:12:21, 17.43it/s]

 25%|██▍       | 24960/100629 [19:50<1:09:38, 18.11it/s]

 25%|██▍       | 24963/100629 [19:50<1:02:25, 20.20it/s]

 25%|██▍       | 24966/100629 [19:50<56:30, 22.31it/s]

 25%|██▍       | 24969/100629 [19:50<59:51, 21.07it/s]

 25%|██▍       | 24972/100629 [19:50<1:00:38, 20.79it/s]

 25%|██▍       | 24976/100629 [19:51<53:44, 23.46it/s]

 25%|██▍       | 24980/100629 [19:51<47:45, 26.40it/s]

 25%|██▍       | 24983/100629 [19:51<55:32, 22.70it/s]

 25%|██▍       | 24986/100629 [19:51<57:27, 21.94it/s]

 25%|██▍       | 24989/100629 [19:51<1:07:11, 18.76it/s]

 25%|██▍       | 24992/100629 [19:51<1:20:35, 15.64it/s]

 25%|██▍       | 24995/100629 [19:52<1:11:05, 17.73it/s]

 25%|██▍       | 24999/100629 [19:52<1:00:25, 20.86it/s]

 25%|██▍       | 25002/100629 [19:52<1:07:30, 18.67it/s]

 25%|██▍       | 25005/100629 [19:52<1:07:40, 18.62it/s]

 25%|██▍       | 25009/100629 [19:52<57:55, 21.76it/s]

 25%|██▍       | 25012/100629 [19:52<58:33, 21.52it/s]

 25%|██▍       | 25016/100629 [19:52<51:31, 24.45it/s]

 25%|██▍       | 25020/100629 [19:53<47:09, 26.72it/s]

 25%|██▍       | 25023/100629 [19:53<55:15, 22.80it/s]

 25%|██▍       | 25026/100629 [19:53<54:03, 23.31it/s]

 25%|██▍       | 25029/100629 [19:53<56:45, 22.20it/s]

 25%|██▍       | 25032/100629 [19:53<1:02:21, 20.20it/s]

 25%|██▍       | 25035/100629 [19:53<1:01:41, 20.42it/s]

 25%|██▍       | 25039/100629 [19:54<59:20, 21.23it/s]

 25%|██▍       | 25042/100629 [19:54<1:05:41, 19.18it/s]

 25%|██▍       | 25046/100629 [19:54<56:02, 22.48it/s]

 25%|██▍       | 25049/100629 [19:54<53:36, 23.49it/s]

 25%|██▍       | 25052/100629 [19:54<55:58, 22.50it/s]

 25%|██▍       | 25055/100629 [19:54<57:55, 21.74it/s]

 25%|██▍       | 25059/100629 [19:54<57:39, 21.84it/s]

 25%|██▍       | 25062/100629 [19:55<1:04:57, 19.39it/s]

 25%|██▍       | 25065/100629 [19:55<1:03:25, 19.86it/s]

 25%|██▍       | 25068/100629 [19:55<1:09:26, 18.14it/s]

 25%|██▍       | 25073/100629 [19:55<59:16, 21.25it/s]

 25%|██▍       | 25076/100629 [19:55<55:00, 22.89it/s]

 25%|██▍       | 25079/100629 [19:55<58:56, 21.36it/s]

 25%|██▍       | 25082/100629 [19:56<58:59, 21.35it/s]

 25%|██▍       | 25085/100629 [19:56<55:03, 22.87it/s]

 25%|██▍       | 25088/100629 [19:56<55:28, 22.70it/s]

 25%|██▍       | 25091/100629 [19:56<56:43, 22.20it/s]

 25%|██▍       | 25094/100629 [19:56<53:55, 23.35it/s]

 25%|██▍       | 25097/100629 [19:56<59:10, 21.27it/s]

 25%|██▍       | 25102/100629 [19:56<48:41, 25.85it/s]

 25%|██▍       | 25105/100629 [19:57<56:35, 22.24it/s]

 25%|██▍       | 25108/100629 [19:57<57:17, 21.97it/s]

 25%|██▍       | 25112/100629 [19:57<53:22, 23.58it/s]

 25%|██▍       | 25115/100629 [19:57<50:27, 24.95it/s]

 25%|██▍       | 25118/100629 [19:57<51:33, 24.41it/s]

 25%|██▍       | 25121/100629 [19:57<53:04, 23.71it/s]

 25%|██▍       | 25124/100629 [19:57<52:10, 24.12it/s]

 25%|██▍       | 25127/100629 [19:57<55:55, 22.50it/s]

 25%|██▍       | 25131/100629 [19:58<48:54, 25.73it/s]

 25%|██▍       | 25136/100629 [19:58<45:20, 27.75it/s]

 25%|██▍       | 25139/100629 [19:58<48:42, 25.83it/s]

 25%|██▍       | 25143/100629 [19:58<48:14, 26.08it/s]

 25%|██▍       | 25146/100629 [19:58<48:01, 26.20it/s]

 25%|██▍       | 25150/100629 [19:58<43:06, 29.18it/s]

 25%|██▍       | 25154/100629 [19:58<44:11, 28.46it/s]

 25%|██▌       | 25158/100629 [19:59<41:20, 30.43it/s]

 25%|██▌       | 25162/100629 [19:59<44:19, 28.38it/s]

 25%|██▌       | 25165/100629 [19:59<47:09, 26.67it/s]

 25%|██▌       | 25168/100629 [19:59<55:58, 22.47it/s]

 25%|██▌       | 25172/100629 [19:59<51:34, 24.38it/s]

 25%|██▌       | 25175/100629 [19:59<55:31, 22.65it/s]

 25%|██▌       | 25178/100629 [19:59<1:02:36, 20.09it/s]

 25%|██▌       | 25181/100629 [20:00<1:04:50, 19.39it/s]

 25%|██▌       | 25184/100629 [20:00<1:05:56, 19.07it/s]

 25%|██▌       | 25187/100629 [20:00<1:00:45, 20.70it/s]

 25%|██▌       | 25190/100629 [20:00<57:14, 21.97it/s]

 25%|██▌       | 25193/100629 [20:00<57:47, 21.76it/s]

 25%|██▌       | 25196/100629 [20:00<57:41, 21.79it/s]

 25%|██▌       | 25199/100629 [20:00<55:07, 22.81it/s]

 25%|██▌       | 25202/100629 [20:01<51:50, 24.25it/s]

 25%|██▌       | 25205/100629 [20:01<1:01:03, 20.59it/s]

 25%|██▌       | 25209/100629 [20:01<51:24, 24.45it/s]

 25%|██▌       | 25212/100629 [20:01<50:33, 24.86it/s]

 25%|██▌       | 25215/100629 [20:01<1:00:55, 20.63it/s]

 25%|██▌       | 25219/100629 [20:01<52:14, 24.06it/s]

 25%|██▌       | 25222/100629 [20:01<51:08, 24.58it/s]

 25%|██▌       | 25225/100629 [20:02<51:39, 24.33it/s]

 25%|██▌       | 25228/100629 [20:02<49:19, 25.47it/s]

 25%|██▌       | 25231/100629 [20:02<53:16, 23.59it/s]

 25%|██▌       | 25235/100629 [20:02<53:13, 23.61it/s]

 25%|██▌       | 25238/100629 [20:02<54:02, 23.25it/s]

 25%|██▌       | 25241/100629 [20:02<56:55, 22.07it/s]

 25%|██▌       | 25244/100629 [20:02<53:16, 23.58it/s]

 25%|██▌       | 25247/100629 [20:03<54:57, 22.86it/s]

 25%|██▌       | 25250/100629 [20:03<51:07, 24.57it/s]

 25%|██▌       | 25254/100629 [20:03<46:45, 26.87it/s]

 25%|██▌       | 25257/100629 [20:03<54:00, 23.26it/s]

 25%|██▌       | 25260/100629 [20:03<1:11:23, 17.59it/s]

 25%|██▌       | 25263/100629 [20:03<1:04:27, 19.49it/s]

 25%|██▌       | 25267/100629 [20:03<54:50, 22.90it/s]

 25%|██▌       | 25270/100629 [20:04<56:30, 22.23it/s]

 25%|██▌       | 25273/100629 [20:04<1:01:05, 20.56it/s]

 25%|██▌       | 25276/100629 [20:04<59:29, 21.11it/s]

 25%|██▌       | 25279/100629 [20:04<58:45, 21.37it/s]

 25%|██▌       | 25282/100629 [20:04<1:01:36, 20.39it/s]

 25%|██▌       | 25285/100629 [20:04<58:49, 21.35it/s]

 25%|██▌       | 25288/100629 [20:04<54:49, 22.90it/s]

 25%|██▌       | 25291/100629 [20:05<55:05, 22.79it/s]

 25%|██▌       | 25294/100629 [20:05<51:52, 24.20it/s]

 25%|██▌       | 25297/100629 [20:05<56:44, 22.13it/s]

 25%|██▌       | 25300/100629 [20:05<1:08:44, 18.26it/s]

 25%|██▌       | 25303/100629 [20:05<1:04:59, 19.32it/s]

 25%|██▌       | 25306/100629 [20:05<1:06:33, 18.86it/s]

 25%|██▌       | 25308/100629 [20:05<1:06:22, 18.91it/s]

 25%|██▌       | 25310/100629 [20:06<1:08:37, 18.29it/s]

 25%|██▌       | 25312/100629 [20:06<1:09:25, 18.08it/s]

 25%|██▌       | 25314/100629 [20:06<1:10:00, 17.93it/s]

 25%|██▌       | 25316/100629 [20:06<1:30:49, 13.82it/s]

 25%|██▌       | 25318/100629 [20:06<1:24:41, 14.82it/s]

 25%|██▌       | 25321/100629 [20:06<1:14:58, 16.74it/s]

 25%|██▌       | 25323/100629 [20:06<1:14:22, 16.88it/s]

 25%|██▌       | 25325/100629 [20:06<1:12:45, 17.25it/s]

 25%|██▌       | 25328/100629 [20:07<1:04:52, 19.35it/s]

 25%|██▌       | 25331/100629 [20:07<58:45, 21.36it/s]

 25%|██▌       | 25334/100629 [20:07<1:13:32, 17.07it/s]

 25%|██▌       | 25337/100629 [20:07<1:16:37, 16.38it/s]

 25%|██▌       | 25340/100629 [20:07<1:05:52, 19.05it/s]

 25%|██▌       | 25343/100629 [20:07<1:03:26, 19.78it/s]

 25%|██▌       | 25347/100629 [20:08<52:07, 24.07it/s]

 25%|██▌       | 25350/100629 [20:08<58:50, 21.32it/s]

 25%|██▌       | 25353/100629 [20:08<58:07, 21.59it/s]

 25%|██▌       | 25356/100629 [20:08<1:00:56, 20.59it/s]

 25%|██▌       | 25359/100629 [20:08<1:00:45, 20.65it/s]

 25%|██▌       | 25362/100629 [20:08<1:01:27, 20.41it/s]

 25%|██▌       | 25365/100629 [20:08<1:05:19, 19.20it/s]

 25%|██▌       | 25368/100629 [20:09<1:04:02, 19.58it/s]

 25%|██▌       | 25371/100629 [20:09<59:19, 21.14it/s]

 25%|██▌       | 25375/100629 [20:09<56:43, 22.11it/s]

 25%|██▌       | 25378/100629 [20:09<52:53, 23.71it/s]

 25%|██▌       | 25381/100629 [20:09<51:10, 24.51it/s]

 25%|██▌       | 25384/100629 [20:09<57:51, 21.68it/s]

 25%|██▌       | 25387/100629 [20:09<56:20, 22.26it/s]

 25%|██▌       | 25390/100629 [20:10<56:41, 22.12it/s]

 25%|██▌       | 25393/100629 [20:10<1:01:50, 20.27it/s]

 25%|██▌       | 25396/100629 [20:10<1:00:53, 20.59it/s]

 25%|██▌       | 25399/100629 [20:10<1:07:40, 18.53it/s]

 25%|██▌       | 25402/100629 [20:10<1:03:37, 19.71it/s]

 25%|██▌       | 25405/100629 [20:10<1:07:12, 18.65it/s]

 25%|██▌       | 25408/100629 [20:11<1:07:17, 18.63it/s]

 25%|██▌       | 25410/100629 [20:11<1:12:35, 17.27it/s]

 25%|██▌       | 25412/100629 [20:11<1:16:30, 16.38it/s]

 25%|██▌       | 25414/100629 [20:11<1:13:31, 17.05it/s]

 25%|██▌       | 25416/100629 [20:11<1:15:03, 16.70it/s]

 25%|██▌       | 25420/100629 [20:11<56:37, 22.13it/s]

 25%|██▌       | 25423/100629 [20:11<59:03, 21.23it/s]

 25%|██▌       | 25426/100629 [20:11<1:00:53, 20.59it/s]

 25%|██▌       | 25429/100629 [20:12<57:20, 21.86it/s]

 25%|██▌       | 25432/100629 [20:12<1:06:14, 18.92it/s]

 25%|██▌       | 25436/100629 [20:12<1:02:12, 20.15it/s]

 25%|██▌       | 25439/100629 [20:12<56:43, 22.09it/s]

 25%|██▌       | 25442/100629 [20:12<59:12, 21.17it/s]

 25%|██▌       | 25445/100629 [20:12<59:25, 21.09it/s]

 25%|██▌       | 25448/100629 [20:13<1:00:28, 20.72it/s]

 25%|██▌       | 25451/100629 [20:13<1:03:23, 19.77it/s]

 25%|██▌       | 25454/100629 [20:13<1:05:16, 19.20it/s]

 25%|██▌       | 25456/100629 [20:13<1:10:46, 17.70it/s]

 25%|██▌       | 25458/100629 [20:13<1:18:58, 15.87it/s]

 25%|██▌       | 25462/100629 [20:13<1:03:36, 19.70it/s]

 25%|██▌       | 25466/100629 [20:13<56:43, 22.09it/s]

 25%|██▌       | 25469/100629 [20:14<58:56, 21.25it/s]

 25%|██▌       | 25472/100629 [20:14<58:52, 21.28it/s]

 25%|██▌       | 25476/100629 [20:14<54:20, 23.05it/s]

 25%|██▌       | 25479/100629 [20:14<56:00, 22.36it/s]

 25%|██▌       | 25482/100629 [20:14<1:07:43, 18.49it/s]

 25%|██▌       | 25484/100629 [20:14<1:06:47, 18.75it/s]

 25%|██▌       | 25487/100629 [20:14<59:37, 21.00it/s]

 25%|██▌       | 25490/100629 [20:15<1:10:31, 17.76it/s]

 25%|██▌       | 25493/100629 [20:15<1:04:15, 19.49it/s]

 25%|██▌       | 25496/100629 [20:15<1:05:17, 19.18it/s]

 25%|██▌       | 25499/100629 [20:15<1:01:50, 20.25it/s]

 25%|██▌       | 25502/100629 [20:15<56:17, 22.24it/s]

 25%|██▌       | 25505/100629 [20:15<59:39, 20.98it/s]

 25%|██▌       | 25508/100629 [20:16<1:05:41, 19.06it/s]

 25%|██▌       | 25511/100629 [20:16<1:05:44, 19.04it/s]

 25%|██▌       | 25515/100629 [20:16<56:41, 22.09it/s]

 25%|██▌       | 25518/100629 [20:16<57:54, 21.62it/s]

 25%|██▌       | 25521/100629 [20:16<56:22, 22.21it/s]

 25%|██▌       | 25524/100629 [20:16<1:21:56, 15.28it/s]

 25%|██▌       | 25526/100629 [20:17<1:22:24, 15.19it/s]

 25%|██▌       | 25529/100629 [20:17<1:13:57, 16.92it/s]

 25%|██▌       | 25533/100629 [20:17<1:00:38, 20.64it/s]

 25%|██▌       | 25536/100629 [20:17<1:12:01, 17.38it/s]

 25%|██▌       | 25538/100629 [20:17<1:16:51, 16.28it/s]

 25%|██▌       | 25541/100629 [20:17<1:07:24, 18.56it/s]

 25%|██▌       | 25545/100629 [20:17<55:28, 22.56it/s]

 25%|██▌       | 25548/100629 [20:18<59:07, 21.16it/s]

 25%|██▌       | 25551/100629 [20:18<58:57, 21.22it/s]

 25%|██▌       | 25554/100629 [20:18<56:19, 22.22it/s]

 25%|██▌       | 25557/100629 [20:18<56:43, 22.06it/s]

 25%|██▌       | 25560/100629 [20:18<54:33, 22.93it/s]

 25%|██▌       | 25563/100629 [20:18<57:19, 21.82it/s]

 25%|██▌       | 25566/100629 [20:18<1:01:28, 20.35it/s]

 25%|██▌       | 25569/100629 [20:19<55:38, 22.49it/s]

 25%|██▌       | 25572/100629 [20:19<54:37, 22.90it/s]

 25%|██▌       | 25575/100629 [20:19<58:58, 21.21it/s]

 25%|██▌       | 25578/100629 [20:19<1:08:23, 18.29it/s]

 25%|██▌       | 25581/100629 [20:19<1:07:44, 18.46it/s]

 25%|██▌       | 25583/100629 [20:19<1:07:12, 18.61it/s]

 25%|██▌       | 25585/100629 [20:20<1:27:09, 14.35it/s]

 25%|██▌       | 25587/100629 [20:20<1:24:21, 14.83it/s]

 25%|██▌       | 25589/100629 [20:20<1:34:24, 13.25it/s]

 25%|██▌       | 25592/100629 [20:20<1:25:21, 14.65it/s]

 25%|██▌       | 25596/100629 [20:20<1:19:54, 15.65it/s]

 25%|██▌       | 25599/100629 [20:20<1:10:15, 17.80it/s]

 25%|██▌       | 25601/100629 [20:21<1:12:29, 17.25it/s]

 25%|██▌       | 25604/100629 [20:21<1:10:13, 17.81it/s]

 25%|██▌       | 25606/100629 [20:21<1:10:34, 17.72it/s]

 25%|██▌       | 25608/100629 [20:21<1:11:27, 17.50it/s]

 25%|██▌       | 25610/100629 [20:21<1:15:36, 16.54it/s]

 25%|██▌       | 25616/100629 [20:21<53:33, 23.34it/s]

 25%|██▌       | 25619/100629 [20:21<51:51, 24.11it/s]

 25%|██▌       | 25622/100629 [20:22<54:44, 22.84it/s]

 25%|██▌       | 25625/100629 [20:22<52:29, 23.82it/s]

 25%|██▌       | 25628/100629 [20:22<51:45, 24.15it/s]

 25%|██▌       | 25631/100629 [20:22<55:09, 22.66it/s]

 25%|██▌       | 25634/100629 [20:22<1:13:01, 17.12it/s]

 25%|██▌       | 25636/100629 [20:22<1:13:38, 16.97it/s]

 25%|██▌       | 25639/100629 [20:22<1:03:37, 19.65it/s]

 25%|██▌       | 25642/100629 [20:23<58:12, 21.47it/s]

 25%|██▌       | 25645/100629 [20:23<58:20, 21.42it/s]

 25%|██▌       | 25649/100629 [20:23<59:35, 20.97it/s]

 25%|██▌       | 25652/100629 [20:23<57:01, 21.92it/s]

 25%|██▌       | 25655/100629 [20:23<54:58, 22.73it/s]

 25%|██▌       | 25658/100629 [20:23<51:28, 24.28it/s]

 26%|██▌       | 25661/100629 [20:23<54:12, 23.05it/s]

 26%|██▌       | 25664/100629 [20:24<1:07:07, 18.61it/s]

 26%|██▌       | 25667/100629 [20:24<1:03:20, 19.73it/s]

 26%|██▌       | 25670/100629 [20:24<1:00:19, 20.71it/s]

 26%|██▌       | 25673/100629 [20:24<1:01:26, 20.33it/s]

 26%|██▌       | 25676/100629 [20:24<1:00:29, 20.65it/s]

 26%|██▌       | 25679/100629 [20:24<55:04, 22.68it/s]

 26%|██▌       | 25682/100629 [20:24<55:01, 22.70it/s]

 26%|██▌       | 25685/100629 [20:24<55:18, 22.58it/s]

 26%|██▌       | 25688/100629 [20:25<53:25, 23.38it/s]

 26%|██▌       | 25691/100629 [20:25<56:30, 22.10it/s]

 26%|██▌       | 25694/100629 [20:25<55:10, 22.64it/s]

 26%|██▌       | 25697/100629 [20:25<59:16, 21.07it/s]

 26%|██▌       | 25700/100629 [20:25<57:48, 21.60it/s]

 26%|██▌       | 25704/100629 [20:25<51:27, 24.27it/s]

 26%|██▌       | 25707/100629 [20:25<50:59, 24.49it/s]

 26%|██▌       | 25710/100629 [20:26<56:40, 22.03it/s]

 26%|██▌       | 25713/100629 [20:26<56:41, 22.02it/s]

 26%|██▌       | 25716/100629 [20:26<59:24, 21.02it/s]

 26%|██▌       | 25719/100629 [20:26<1:08:03, 18.35it/s]

 26%|██▌       | 25722/100629 [20:26<1:00:37, 20.59it/s]

 26%|██▌       | 25725/100629 [20:26<58:26, 21.36it/s]

 26%|██▌       | 25730/100629 [20:26<46:58, 26.58it/s]

 26%|██▌       | 25734/100629 [20:27<48:06, 25.94it/s]

 26%|██▌       | 25737/100629 [20:27<51:50, 24.07it/s]

 26%|██▌       | 25741/100629 [20:27<48:29, 25.74it/s]

 26%|██▌       | 25745/100629 [20:27<44:28, 28.06it/s]

 26%|██▌       | 25748/100629 [20:27<47:54, 26.05it/s]

 26%|██▌       | 25752/100629 [20:27<44:24, 28.10it/s]

 26%|██▌       | 25755/100629 [20:27<45:01, 27.71it/s]

 26%|██▌       | 25758/100629 [20:28<48:24, 25.78it/s]

 26%|██▌       | 25761/100629 [20:28<53:58, 23.12it/s]

 26%|██▌       | 25764/100629 [20:28<51:23, 24.28it/s]

 26%|██▌       | 25767/100629 [20:28<55:55, 22.31it/s]

 26%|██▌       | 25770/100629 [20:28<52:50, 23.61it/s]

 26%|██▌       | 25774/100629 [20:28<53:42, 23.23it/s]

 26%|██▌       | 25777/100629 [20:28<1:01:22, 20.32it/s]

 26%|██▌       | 25780/100629 [20:29<56:22, 22.13it/s]

 26%|██▌       | 25783/100629 [20:29<52:23, 23.81it/s]

 26%|██▌       | 25786/100629 [20:29<58:51, 21.19it/s]

 26%|██▌       | 25789/100629 [20:29<58:26, 21.34it/s]

 26%|██▌       | 25792/100629 [20:29<58:26, 21.34it/s]

 26%|██▌       | 25795/100629 [20:29<59:16, 21.04it/s]

 26%|██▌       | 25798/100629 [20:29<1:06:37, 18.72it/s]

 26%|██▌       | 25800/100629 [20:30<1:14:32, 16.73it/s]

 26%|██▌       | 25804/100629 [20:30<1:02:33, 19.94it/s]

 26%|██▌       | 25807/100629 [20:30<1:00:08, 20.74it/s]

 26%|██▌       | 25810/100629 [20:30<1:03:07, 19.75it/s]

 26%|██▌       | 25813/100629 [20:30<1:06:15, 18.82it/s]

 26%|██▌       | 25816/100629 [20:30<1:03:16, 19.70it/s]

 26%|██▌       | 25819/100629 [20:31<1:01:33, 20.25it/s]

 26%|██▌       | 25822/100629 [20:31<1:01:17, 20.34it/s]

 26%|██▌       | 25826/100629 [20:31<1:00:35, 20.58it/s]

 26%|██▌       | 25829/100629 [20:31<1:10:31, 17.68it/s]

 26%|██▌       | 25831/100629 [20:31<1:11:50, 17.35it/s]

 26%|██▌       | 25833/100629 [20:31<1:12:42, 17.15it/s]

 26%|██▌       | 25835/100629 [20:32<1:33:57, 13.27it/s]

 26%|██▌       | 25839/100629 [20:32<1:11:40, 17.39it/s]

 26%|██▌       | 25841/100629 [20:32<1:13:51, 16.88it/s]

 26%|██▌       | 25843/100629 [20:32<1:18:45, 15.82it/s]

 26%|██▌       | 25845/100629 [20:32<1:15:26, 16.52it/s]

 26%|██▌       | 25848/100629 [20:32<1:16:53, 16.21it/s]

 26%|██▌       | 25853/100629 [20:32<59:27, 20.96it/s]

 26%|██▌       | 25856/100629 [20:33<1:01:54, 20.13it/s]

 26%|██▌       | 25860/100629 [20:33<53:11, 23.43it/s]

 26%|██▌       | 25866/100629 [20:33<45:18, 27.50it/s]

 26%|██▌       | 25870/100629 [20:33<41:16, 30.19it/s]

 26%|██▌       | 25874/100629 [20:33<43:37, 28.56it/s]

 26%|██▌       | 25877/100629 [20:33<56:02, 22.23it/s]

 26%|██▌       | 25880/100629 [20:34<1:00:35, 20.56it/s]

 26%|██▌       | 25883/100629 [20:34<1:02:28, 19.94it/s]

 26%|██▌       | 25886/100629 [20:34<59:57, 20.78it/s]

 26%|██▌       | 25889/100629 [20:34<1:06:31, 18.73it/s]

 26%|██▌       | 25891/100629 [20:34<1:06:11, 18.82it/s]

 26%|██▌       | 25895/100629 [20:34<1:02:01, 20.08it/s]

 26%|██▌       | 25898/100629 [20:35<1:09:35, 17.90it/s]

 26%|██▌       | 25901/100629 [20:35<1:05:13, 19.09it/s]

 26%|██▌       | 25905/100629 [20:35<56:19, 22.11it/s]

 26%|██▌       | 25909/100629 [20:35<49:19, 25.25it/s]

 26%|██▌       | 25912/100629 [20:35<58:10, 21.40it/s]

 26%|██▌       | 25915/100629 [20:35<57:29, 21.66it/s]

 26%|██▌       | 25919/100629 [20:35<55:33, 22.41it/s]

 26%|██▌       | 25922/100629 [20:36<55:56, 22.26it/s]

 26%|██▌       | 25925/100629 [20:36<54:56, 22.66it/s]

 26%|██▌       | 25928/100629 [20:36<53:21, 23.33it/s]

 26%|██▌       | 25931/100629 [20:36<57:22, 21.70it/s]

 26%|██▌       | 25936/100629 [20:36<53:43, 23.17it/s]

 26%|██▌       | 25941/100629 [20:36<51:47, 24.03it/s]

 26%|██▌       | 25944/100629 [20:37<54:14, 22.95it/s]

 26%|██▌       | 25947/100629 [20:37<55:55, 22.26it/s]

 26%|██▌       | 25950/100629 [20:37<53:11, 23.40it/s]

 26%|██▌       | 25954/100629 [20:37<48:44, 25.54it/s]

 26%|██▌       | 25957/100629 [20:37<53:22, 23.32it/s]

 26%|██▌       | 25960/100629 [20:37<51:39, 24.09it/s]

 26%|██▌       | 25963/100629 [20:37<1:00:10, 20.68it/s]

 26%|██▌       | 25966/100629 [20:38<1:06:07, 18.82it/s]

 26%|██▌       | 25968/100629 [20:38<1:06:06, 18.82it/s]

 26%|██▌       | 25970/100629 [20:38<1:10:04, 17.76it/s]

 26%|██▌       | 25973/100629 [20:38<1:03:04, 19.73it/s]

 26%|██▌       | 25976/100629 [20:38<57:44, 21.55it/s]

 26%|██▌       | 25979/100629 [20:38<56:20, 22.08it/s]

 26%|██▌       | 25982/100629 [20:38<59:59, 20.74it/s]

 26%|██▌       | 25985/100629 [20:38<54:22, 22.88it/s]

 26%|██▌       | 25988/100629 [20:39<1:01:56, 20.08it/s]

 26%|██▌       | 25991/100629 [20:39<1:00:34, 20.53it/s]

 26%|██▌       | 25994/100629 [20:39<56:46, 21.91it/s]

 26%|██▌       | 25998/100629 [20:39<47:33, 26.16it/s]

 26%|██▌       | 26001/100629 [20:39<47:34, 26.14it/s]

 26%|██▌       | 26004/100629 [20:39<48:08, 25.84it/s]

 26%|██▌       | 26007/100629 [20:39<48:50, 25.47it/s]

 26%|██▌       | 26010/100629 [20:39<49:03, 25.35it/s]

 26%|██▌       | 26013/100629 [20:40<1:12:55, 17.05it/s]

 26%|██▌       | 26018/100629 [20:40<57:38, 21.57it/s]

 26%|██▌       | 26021/100629 [20:40<1:01:10, 20.33it/s]

 26%|██▌       | 26025/100629 [20:40<54:53, 22.65it/s]

 26%|██▌       | 26029/100629 [20:40<51:26, 24.17it/s]

 26%|██▌       | 26032/100629 [20:40<52:31, 23.67it/s]

 26%|██▌       | 26037/100629 [20:41<44:32, 27.91it/s]

 26%|██▌       | 26040/100629 [20:41<52:45, 23.56it/s]

 26%|██▌       | 26043/100629 [20:41<1:04:56, 19.14it/s]

 26%|██▌       | 26047/100629 [20:41<54:21, 22.86it/s]

 26%|██▌       | 26050/100629 [20:41<56:29, 22.00it/s]

 26%|██▌       | 26053/100629 [20:41<59:49, 20.78it/s]

 26%|██▌       | 26056/100629 [20:42<1:05:18, 19.03it/s]

 26%|██▌       | 26059/100629 [20:42<1:07:16, 18.47it/s]

 26%|██▌       | 26061/100629 [20:42<1:17:59, 15.93it/s]

 26%|██▌       | 26063/100629 [20:42<1:16:16, 16.29it/s]

 26%|██▌       | 26066/100629 [20:42<1:17:55, 15.95it/s]

 26%|██▌       | 26069/100629 [20:42<1:10:20, 17.67it/s]

 26%|██▌       | 26071/100629 [20:43<1:16:03, 16.34it/s]

 26%|██▌       | 26073/100629 [20:43<1:26:23, 14.38it/s]

 26%|██▌       | 26075/100629 [20:43<1:37:02, 12.81it/s]

 26%|██▌       | 26077/100629 [20:43<1:32:01, 13.50it/s]

 26%|██▌       | 26079/100629 [20:43<1:24:58, 14.62it/s]

 26%|██▌       | 26081/100629 [20:43<1:26:23, 14.38it/s]

 26%|██▌       | 26085/100629 [20:44<1:09:29, 17.88it/s]

 26%|██▌       | 26089/100629 [20:44<57:10, 21.73it/s]

 26%|██▌       | 26092/100629 [20:44<54:47, 22.67it/s]

 26%|██▌       | 26095/100629 [20:44<57:41, 21.53it/s]

 26%|██▌       | 26098/100629 [20:44<52:51, 23.50it/s]

 26%|██▌       | 26101/100629 [20:44<53:02, 23.42it/s]

 26%|██▌       | 26104/100629 [20:44<57:16, 21.68it/s]

 26%|██▌       | 26107/100629 [20:44<56:36, 21.94it/s]

 26%|██▌       | 26111/100629 [20:45<52:20, 23.73it/s]

 26%|██▌       | 26115/100629 [20:45<46:59, 26.43it/s]

 26%|██▌       | 26118/100629 [20:45<54:16, 22.88it/s]

 26%|██▌       | 26121/100629 [20:45<1:03:11, 19.65it/s]

 26%|██▌       | 26124/100629 [20:45<1:00:29, 20.53it/s]

 26%|██▌       | 26127/100629 [20:45<1:08:39, 18.08it/s]

 26%|██▌       | 26129/100629 [20:46<1:07:19, 18.44it/s]

 26%|██▌       | 26132/100629 [20:46<59:18, 20.93it/s]

 26%|██▌       | 26135/100629 [20:46<1:01:40, 20.13it/s]

 26%|██▌       | 26139/100629 [20:46<54:05, 22.95it/s]

 26%|██▌       | 26142/100629 [20:46<55:53, 22.21it/s]

 26%|██▌       | 26145/100629 [20:46<54:58, 22.58it/s]

 26%|██▌       | 26148/100629 [20:46<56:21, 22.02it/s]

 26%|██▌       | 26151/100629 [20:47<1:02:57, 19.72it/s]

 26%|██▌       | 26154/100629 [20:47<59:06, 21.00it/s]

 26%|██▌       | 26157/100629 [20:47<59:15, 20.95it/s]

 26%|██▌       | 26163/100629 [20:47<43:15, 28.69it/s]

 26%|██▌       | 26167/100629 [20:47<54:00, 22.98it/s]

 26%|██▌       | 26170/100629 [20:47<54:03, 22.96it/s]

 26%|██▌       | 26173/100629 [20:48<1:04:55, 19.11it/s]

 26%|██▌       | 26177/100629 [20:48<58:10, 21.33it/s]

 26%|██▌       | 26180/100629 [20:48<55:30, 22.36it/s]

 26%|██▌       | 26183/100629 [20:48<55:55, 22.19it/s]

 26%|██▌       | 26186/100629 [20:48<52:57, 23.42it/s]

 26%|██▌       | 26189/100629 [20:48<1:05:36, 18.91it/s]

 26%|██▌       | 26192/100629 [20:48<1:06:02, 18.79it/s]

 26%|██▌       | 26195/100629 [20:49<1:06:02, 18.78it/s]

 26%|██▌       | 26199/100629 [20:49<1:02:20, 19.90it/s]

 26%|██▌       | 26203/100629 [20:49<55:08, 22.49it/s]

 26%|██▌       | 26206/100629 [20:49<52:40, 23.55it/s]

 26%|██▌       | 26210/100629 [20:49<50:35, 24.52it/s]

 26%|██▌       | 26215/100629 [20:49<41:06, 30.17it/s]

 26%|██▌       | 26221/100629 [20:49<34:21, 36.09it/s]

 26%|██▌       | 26225/100629 [20:50<34:46, 35.67it/s]

 26%|██▌       | 26229/100629 [20:50<39:29, 31.40it/s]

 26%|██▌       | 26233/100629 [20:50<47:50, 25.92it/s]

 26%|██▌       | 26236/100629 [20:50<53:01, 23.38it/s]

 26%|██▌       | 26239/100629 [20:50<51:32, 24.06it/s]

 26%|██▌       | 26242/100629 [20:50<53:11, 23.31it/s]

 26%|██▌       | 26245/100629 [20:50<52:32, 23.60it/s]

 26%|██▌       | 26248/100629 [20:51<51:52, 23.90it/s]

 26%|██▌       | 26251/100629 [20:51<1:03:20, 19.57it/s]

 26%|██▌       | 26254/100629 [20:51<1:00:48, 20.38it/s]

 26%|██▌       | 26258/100629 [20:51<50:37, 24.48it/s]

 26%|██▌       | 26261/100629 [20:51<49:14, 25.17it/s]

 26%|██▌       | 26264/100629 [20:51<51:54, 23.88it/s]

 26%|██▌       | 26267/100629 [20:51<51:46, 23.94it/s]

 26%|██▌       | 26270/100629 [20:52<58:31, 21.18it/s]

 26%|██▌       | 26273/100629 [20:52<1:01:32, 20.14it/s]

 26%|██▌       | 26276/100629 [20:52<58:12, 21.29it/s]

 26%|██▌       | 26279/100629 [20:52<58:29, 21.19it/s]

 26%|██▌       | 26282/100629 [20:52<1:04:51, 19.11it/s]

 26%|██▌       | 26284/100629 [20:52<1:07:19, 18.40it/s]

 26%|██▌       | 26287/100629 [20:53<1:03:28, 19.52it/s]

 26%|██▌       | 26289/100629 [20:53<1:08:38, 18.05it/s]

 26%|██▌       | 26292/100629 [20:53<1:04:09, 19.31it/s]

 26%|██▌       | 26294/100629 [20:53<1:04:06, 19.32it/s]

 26%|██▌       | 26298/100629 [20:53<51:55, 23.86it/s]

 26%|██▌       | 26301/100629 [20:53<54:06, 22.89it/s]

 26%|██▌       | 26304/100629 [20:53<57:31, 21.53it/s]

 26%|██▌       | 26307/100629 [20:53<1:04:59, 19.06it/s]

 26%|██▌       | 26309/100629 [20:54<1:07:05, 18.46it/s]

 26%|██▌       | 26312/100629 [20:54<59:57, 20.66it/s]

 26%|██▌       | 26316/100629 [20:54<49:49, 24.86it/s]

 26%|██▌       | 26319/100629 [20:54<47:25, 26.12it/s]

 26%|██▌       | 26322/100629 [20:54<57:30, 21.54it/s]

 26%|██▌       | 26325/100629 [20:54<1:08:27, 18.09it/s]

 26%|██▌       | 26329/100629 [20:55<1:02:56, 19.68it/s]

 26%|██▌       | 26333/100629 [20:55<53:05, 23.32it/s]

 26%|██▌       | 26336/100629 [20:55<52:16, 23.68it/s]

 26%|██▌       | 26339/100629 [20:55<53:04, 23.33it/s]

 26%|██▌       | 26342/100629 [20:55<57:06, 21.68it/s]

 26%|██▌       | 26345/100629 [20:55<1:01:03, 20.28it/s]

 26%|██▌       | 26348/100629 [20:55<57:15, 21.62it/s]

 26%|██▌       | 26351/100629 [20:56<1:07:44, 18.28it/s]

 26%|██▌       | 26355/100629 [20:56<59:42, 20.73it/s]

 26%|██▌       | 26358/100629 [20:56<1:00:20, 20.51it/s]

 26%|██▌       | 26361/100629 [20:56<56:07, 22.05it/s]

 26%|██▌       | 26365/100629 [20:56<53:08, 23.29it/s]

 26%|██▌       | 26368/100629 [20:56<58:05, 21.31it/s]

 26%|██▌       | 26371/100629 [20:56<57:49, 21.40it/s]

 26%|██▌       | 26374/100629 [20:57<1:01:57, 19.97it/s]

 26%|██▌       | 26377/100629 [20:57<58:34, 21.13it/s]

 26%|██▌       | 26380/100629 [20:57<57:44, 21.43it/s]

 26%|██▌       | 26383/100629 [20:57<1:01:12, 20.22it/s]

 26%|██▌       | 26388/100629 [20:57<53:19, 23.20it/s]

 26%|██▌       | 26391/100629 [20:57<54:18, 22.78it/s]

 26%|██▌       | 26394/100629 [20:58<59:05, 20.94it/s]

 26%|██▌       | 26397/100629 [20:58<1:00:40, 20.39it/s]

 26%|██▌       | 26400/100629 [20:58<57:00, 21.70it/s]

 26%|██▌       | 26404/100629 [20:58<49:14, 25.12it/s]

 26%|██▌       | 26407/100629 [20:58<50:22, 24.56it/s]

 26%|██▌       | 26410/100629 [20:58<52:21, 23.63it/s]

 26%|██▌       | 26413/100629 [20:58<52:47, 23.43it/s]

 26%|██▋       | 26416/100629 [20:58<51:53, 23.83it/s]

 26%|██▋       | 26420/100629 [20:59<54:34, 22.66it/s]

 26%|██▋       | 26423/100629 [20:59<58:13, 21.24it/s]

 26%|██▋       | 26427/100629 [20:59<51:19, 24.09it/s]

 26%|██▋       | 26430/100629 [20:59<52:15, 23.66it/s]

 26%|██▋       | 26433/100629 [20:59<1:05:25, 18.90it/s]

 26%|██▋       | 26436/100629 [20:59<59:17, 20.85it/s]

 26%|██▋       | 26440/100629 [21:00<52:35, 23.51it/s]

 26%|██▋       | 26443/100629 [21:00<58:45, 21.04it/s]

 26%|██▋       | 26446/100629 [21:00<1:11:46, 17.22it/s]

 26%|██▋       | 26449/100629 [21:00<1:03:31, 19.46it/s]

 26%|██▋       | 26452/100629 [21:00<1:04:43, 19.10it/s]

 26%|██▋       | 26455/100629 [21:00<1:08:31, 18.04it/s]

 26%|██▋       | 26457/100629 [21:01<1:15:51, 16.30it/s]

 26%|██▋       | 26461/100629 [21:01<58:39, 21.08it/s]

 26%|██▋       | 26464/100629 [21:01<1:10:31, 17.53it/s]

 26%|██▋       | 26467/100629 [21:01<1:06:48, 18.50it/s]

 26%|██▋       | 26470/100629 [21:01<1:04:22, 19.20it/s]

 26%|██▋       | 26474/100629 [21:01<58:36, 21.09it/s]

 26%|██▋       | 26477/100629 [21:02<1:00:40, 20.37it/s]

 26%|██▋       | 26480/100629 [21:02<58:46, 21.03it/s]

 26%|██▋       | 26483/100629 [21:02<58:21, 21.17it/s]

 26%|██▋       | 26486/100629 [21:02<1:02:35, 19.74it/s]

 26%|██▋       | 26490/100629 [21:02<59:33, 20.75it/s]

 26%|██▋       | 26494/100629 [21:02<52:47, 23.41it/s]

 26%|██▋       | 26497/100629 [21:02<59:52, 20.63it/s]

 26%|██▋       | 26500/100629 [21:03<58:43, 21.04it/s]

 26%|██▋       | 26503/100629 [21:03<54:05, 22.84it/s]

 26%|██▋       | 26506/100629 [21:03<58:26, 21.14it/s]

 26%|██▋       | 26509/100629 [21:03<57:36, 21.44it/s]

 26%|██▋       | 26512/100629 [21:03<1:07:56, 18.18it/s]

 26%|██▋       | 26515/100629 [21:03<1:04:44, 19.08it/s]

 26%|██▋       | 26518/100629 [21:04<1:08:07, 18.13it/s]

 26%|██▋       | 26521/100629 [21:04<1:01:37, 20.04it/s]

 26%|██▋       | 26524/100629 [21:04<1:00:29, 20.42it/s]

 26%|██▋       | 26527/100629 [21:04<55:39, 22.19it/s]

 26%|██▋       | 26530/100629 [21:04<1:01:02, 20.23it/s]

 26%|██▋       | 26533/100629 [21:04<58:33, 21.09it/s]

 26%|██▋       | 26536/100629 [21:04<56:37, 21.81it/s]

 26%|██▋       | 26540/100629 [21:04<50:28, 24.47it/s]

 26%|██▋       | 26543/100629 [21:05<53:26, 23.10it/s]

 26%|██▋       | 26546/100629 [21:05<50:35, 24.41it/s]

 26%|██▋       | 26549/100629 [21:05<58:47, 21.00it/s]

 26%|██▋       | 26553/100629 [21:05<51:18, 24.06it/s]

 26%|██▋       | 26557/100629 [21:05<50:30, 24.44it/s]

 26%|██▋       | 26560/100629 [21:05<49:45, 24.81it/s]

 26%|██▋       | 26563/100629 [21:05<50:26, 24.48it/s]

 26%|██▋       | 26566/100629 [21:06<53:46, 22.95it/s]

 26%|██▋       | 26569/100629 [21:06<51:01, 24.19it/s]

 26%|██▋       | 26572/100629 [21:06<53:15, 23.17it/s]

 26%|██▋       | 26575/100629 [21:06<1:04:23, 19.17it/s]

 26%|██▋       | 26578/100629 [21:06<1:08:35, 17.99it/s]

 26%|██▋       | 26580/100629 [21:06<1:09:51, 17.67it/s]

 26%|██▋       | 26584/100629 [21:07<59:27, 20.76it/s]

 26%|██▋       | 26588/100629 [21:07<51:43, 23.86it/s]

 26%|██▋       | 26591/100629 [21:07<52:26, 23.53it/s]

 26%|██▋       | 26594/100629 [21:07<51:17, 24.06it/s]

 26%|██▋       | 26597/100629 [21:07<50:18, 24.52it/s]

 26%|██▋       | 26600/100629 [21:07<56:13, 21.94it/s]

 26%|██▋       | 26605/100629 [21:07<44:45, 27.57it/s]

 26%|██▋       | 26608/100629 [21:07<50:31, 24.41it/s]

 26%|██▋       | 26613/100629 [21:08<50:39, 24.35it/s]

 26%|██▋       | 26616/100629 [21:08<56:27, 21.85it/s]

 26%|██▋       | 26619/100629 [21:08<54:41, 22.56it/s]

 26%|██▋       | 26623/100629 [21:08<50:10, 24.58it/s]

 26%|██▋       | 26626/100629 [21:08<59:31, 20.72it/s]

 26%|██▋       | 26629/100629 [21:08<1:01:57, 19.91it/s]

 26%|██▋       | 26632/100629 [21:09<59:29, 20.73it/s]

 26%|██▋       | 26635/100629 [21:09<59:26, 20.74it/s]

 26%|██▋       | 26638/100629 [21:09<1:02:17, 19.80it/s]

 26%|██▋       | 26641/100629 [21:09<1:03:00, 19.57it/s]

 26%|██▋       | 26646/100629 [21:09<51:37, 23.89it/s]

 26%|██▋       | 26649/100629 [21:09<54:02, 22.81it/s]

 26%|██▋       | 26652/100629 [21:09<51:39, 23.87it/s]

 26%|██▋       | 26655/100629 [21:10<57:01, 21.62it/s]

 26%|██▋       | 26658/100629 [21:10<54:26, 22.65it/s]

 26%|██▋       | 26661/100629 [21:10<1:00:34, 20.35it/s]

 26%|██▋       | 26664/100629 [21:10<1:28:49, 13.88it/s]

 27%|██▋       | 26667/100629 [21:11<1:26:04, 14.32it/s]

 27%|██▋       | 26670/100629 [21:11<1:16:25, 16.13it/s]

 27%|██▋       | 26674/100629 [21:11<1:02:20, 19.77it/s]

 27%|██▋       | 26677/100629 [21:11<1:12:23, 17.03it/s]

 27%|██▋       | 26679/100629 [21:11<1:12:48, 16.93it/s]

 27%|██▋       | 26681/100629 [21:11<1:15:39, 16.29it/s]

 27%|██▋       | 26683/100629 [21:11<1:15:57, 16.23it/s]

 27%|██▋       | 26685/100629 [21:12<1:13:33, 16.76it/s]

 27%|██▋       | 26687/100629 [21:12<1:13:46, 16.70it/s]

 27%|██▋       | 26689/100629 [21:12<1:31:08, 13.52it/s]

 27%|██▋       | 26691/100629 [21:12<1:25:45, 14.37it/s]

 27%|██▋       | 26694/100629 [21:12<1:10:53, 17.38it/s]

 27%|██▋       | 26697/100629 [21:12<1:14:07, 16.62it/s]

 27%|██▋       | 26700/100629 [21:12<1:03:44, 19.33it/s]

 27%|██▋       | 26704/100629 [21:13<58:07, 21.20it/s]

 27%|██▋       | 26707/100629 [21:13<56:03, 21.98it/s]

 27%|██▋       | 26710/100629 [21:13<1:01:14, 20.12it/s]

 27%|██▋       | 26713/100629 [21:13<1:18:26, 15.70it/s]

 27%|██▋       | 26715/100629 [21:13<1:20:31, 15.30it/s]

 27%|██▋       | 26717/100629 [21:13<1:24:25, 14.59it/s]

 27%|██▋       | 26719/100629 [21:14<1:18:44, 15.64it/s]

 27%|██▋       | 26723/100629 [21:14<59:30, 20.70it/s]

 27%|██▋       | 26726/100629 [21:14<1:07:57, 18.12it/s]

 27%|██▋       | 26729/100629 [21:14<1:07:40, 18.20it/s]

 27%|██▋       | 26731/100629 [21:14<1:23:37, 14.73it/s]

 27%|██▋       | 26733/100629 [21:14<1:24:10, 14.63it/s]

 27%|██▋       | 26736/100629 [21:15<1:15:30, 16.31it/s]

 27%|██▋       | 26739/100629 [21:15<1:09:57, 17.61it/s]

 27%|██▋       | 26741/100629 [21:15<1:13:54, 16.66it/s]

 27%|██▋       | 26744/100629 [21:15<1:05:00, 18.94it/s]

 27%|██▋       | 26746/100629 [21:15<1:04:52, 18.98it/s]

 27%|██▋       | 26750/100629 [21:15<51:04, 24.11it/s]

 27%|██▋       | 26753/100629 [21:15<48:06, 25.59it/s]

 27%|██▋       | 26758/100629 [21:15<49:38, 24.80it/s]

 27%|██▋       | 26761/100629 [21:16<52:22, 23.51it/s]

 27%|██▋       | 26764/100629 [21:16<52:17, 23.54it/s]

 27%|██▋       | 26767/100629 [21:16<52:09, 23.60it/s]

 27%|██▋       | 26771/100629 [21:16<49:18, 24.97it/s]

 27%|██▋       | 26774/100629 [21:16<48:30, 25.37it/s]

 27%|██▋       | 26777/100629 [21:16<56:44, 21.69it/s]

 27%|██▋       | 26780/100629 [21:16<1:02:43, 19.62it/s]

 27%|██▋       | 26783/100629 [21:17<1:05:04, 18.92it/s]

 27%|██▋       | 26786/100629 [21:17<1:02:33, 19.67it/s]

 27%|██▋       | 26789/100629 [21:17<1:00:13, 20.44it/s]

 27%|██▋       | 26792/100629 [21:17<59:20, 20.74it/s]

 27%|██▋       | 26795/100629 [21:17<1:01:17, 20.08it/s]

 27%|██▋       | 26799/100629 [21:17<51:53, 23.72it/s]

 27%|██▋       | 26804/100629 [21:17<43:04, 28.56it/s]

 27%|██▋       | 26808/100629 [21:18<45:31, 27.03it/s]

 27%|██▋       | 26811/100629 [21:18<47:57, 25.66it/s]

 27%|██▋       | 26814/100629 [21:18<50:24, 24.40it/s]

 27%|██▋       | 26817/100629 [21:18<49:45, 24.73it/s]

 27%|██▋       | 26820/100629 [21:18<52:27, 23.45it/s]

 27%|██▋       | 26823/100629 [21:18<54:39, 22.50it/s]

 27%|██▋       | 26827/100629 [21:18<47:41, 25.79it/s]

 27%|██▋       | 26830/100629 [21:19<54:57, 22.38it/s]

 27%|██▋       | 26833/100629 [21:19<51:35, 23.84it/s]

 27%|██▋       | 26836/100629 [21:19<53:29, 22.99it/s]

 27%|██▋       | 26839/100629 [21:19<50:21, 24.43it/s]

 27%|██▋       | 26842/100629 [21:19<56:39, 21.70it/s]

 27%|██▋       | 26845/100629 [21:19<1:02:07, 19.80it/s]

 27%|██▋       | 26848/100629 [21:19<56:08, 21.90it/s]

 27%|██▋       | 26852/100629 [21:20<51:59, 23.65it/s]

 27%|██▋       | 26855/100629 [21:20<51:34, 23.84it/s]

 27%|██▋       | 26858/100629 [21:20<53:02, 23.18it/s]

 27%|██▋       | 26863/100629 [21:20<49:31, 24.83it/s]

 27%|██▋       | 26868/100629 [21:20<46:48, 26.26it/s]

 27%|██▋       | 26872/100629 [21:20<46:14, 26.58it/s]

 27%|██▋       | 26875/100629 [21:20<48:03, 25.57it/s]

 27%|██▋       | 26878/100629 [21:21<56:13, 21.86it/s]

 27%|██▋       | 26881/100629 [21:21<55:57, 21.96it/s]

 27%|██▋       | 26884/100629 [21:21<56:42, 21.67it/s]

 27%|██▋       | 26887/100629 [21:21<1:00:02, 20.47it/s]

 27%|██▋       | 26890/100629 [21:21<58:37, 20.96it/s]

 27%|██▋       | 26893/100629 [21:21<54:56, 22.37it/s]

 27%|██▋       | 26896/100629 [21:21<55:44, 22.05it/s]

 27%|██▋       | 26899/100629 [21:22<52:20, 23.48it/s]

 27%|██▋       | 26902/100629 [21:22<50:47, 24.20it/s]

 27%|██▋       | 26905/100629 [21:22<48:15, 25.46it/s]

 27%|██▋       | 26908/100629 [21:22<55:54, 21.98it/s]

 27%|██▋       | 26911/100629 [21:22<1:09:14, 17.74it/s]

 27%|██▋       | 26914/100629 [21:22<1:06:44, 18.41it/s]

 27%|██▋       | 26916/100629 [21:22<1:07:16, 18.26it/s]

 27%|██▋       | 26920/100629 [21:23<57:20, 21.42it/s]

 27%|██▋       | 26923/100629 [21:23<57:23, 21.40it/s]

 27%|██▋       | 26926/100629 [21:23<58:29, 21.00it/s]

 27%|██▋       | 26930/100629 [21:23<56:00, 21.93it/s]

 27%|██▋       | 26933/100629 [21:23<1:02:12, 19.75it/s]

 27%|██▋       | 26936/100629 [21:24<1:20:36, 15.24it/s]

 27%|██▋       | 26940/100629 [21:24<1:07:25, 18.22it/s]

 27%|██▋       | 26943/100629 [21:24<1:02:49, 19.55it/s]

 27%|██▋       | 26946/100629 [21:24<1:09:36, 17.64it/s]

 27%|██▋       | 26949/100629 [21:24<1:03:18, 19.40it/s]

 27%|██▋       | 26953/100629 [21:24<58:54, 20.85it/s]

 27%|██▋       | 26956/100629 [21:25<1:02:11, 19.74it/s]

 27%|██▋       | 26959/100629 [21:25<1:07:57, 18.07it/s]

 27%|██▋       | 26961/100629 [21:25<1:10:26, 17.43it/s]

 27%|██▋       | 26965/100629 [21:25<58:41, 20.92it/s]

 27%|██▋       | 26968/100629 [21:25<58:40, 20.93it/s]

 27%|██▋       | 26972/100629 [21:25<49:46, 24.67it/s]

 27%|██▋       | 26975/100629 [21:25<51:07, 24.01it/s]

 27%|██▋       | 26978/100629 [21:25<51:48, 23.70it/s]

 27%|██▋       | 26981/100629 [21:26<1:07:05, 18.30it/s]

 27%|██▋       | 26984/100629 [21:26<1:08:59, 17.79it/s]

 27%|██▋       | 26987/100629 [21:26<1:08:27, 17.93it/s]

 27%|██▋       | 26989/100629 [21:26<1:06:58, 18.33it/s]

 27%|██▋       | 26991/100629 [21:26<1:10:09, 17.49it/s]

 27%|██▋       | 26994/100629 [21:27<1:12:17, 16.98it/s]

 27%|██▋       | 26998/100629 [21:27<58:33, 20.96it/s]

 27%|██▋       | 27001/100629 [21:27<58:23, 21.02it/s]

 27%|██▋       | 27004/100629 [21:27<1:03:20, 19.37it/s]

 27%|██▋       | 27007/100629 [21:27<59:49, 20.51it/s]

 27%|██▋       | 27010/100629 [21:27<55:28, 22.12it/s]

 27%|██▋       | 27013/100629 [21:27<53:29, 22.94it/s]

 27%|██▋       | 27016/100629 [21:27<55:11, 22.23it/s]

 27%|██▋       | 27019/100629 [21:28<53:50, 22.79it/s]

 27%|██▋       | 27022/100629 [21:28<53:22, 22.98it/s]

 27%|██▋       | 27025/100629 [21:28<51:20, 23.90it/s]

 27%|██▋       | 27028/100629 [21:28<53:30, 22.92it/s]

 27%|██▋       | 27031/100629 [21:28<1:00:34, 20.25it/s]

 27%|██▋       | 27034/100629 [21:28<57:16, 21.41it/s]

 27%|██▋       | 27039/100629 [21:28<45:18, 27.07it/s]

 27%|██▋       | 27043/100629 [21:29<46:49, 26.19it/s]

 27%|██▋       | 27046/100629 [21:29<48:30, 25.29it/s]

 27%|██▋       | 27050/100629 [21:29<44:49, 27.35it/s]

 27%|██▋       | 27053/100629 [21:29<44:40, 27.45it/s]

 27%|██▋       | 27056/100629 [21:29<49:41, 24.67it/s]

 27%|██▋       | 27060/100629 [21:29<43:19, 28.30it/s]

 27%|██▋       | 27064/100629 [21:29<45:16, 27.08it/s]

 27%|██▋       | 27068/100629 [21:29<41:04, 29.85it/s]

 27%|██▋       | 27072/100629 [21:30<55:34, 22.06it/s]

 27%|██▋       | 27077/100629 [21:30<49:53, 24.57it/s]

 27%|██▋       | 27080/100629 [21:30<49:59, 24.52it/s]

 27%|██▋       | 27083/100629 [21:30<48:56, 25.05it/s]

 27%|██▋       | 27087/100629 [21:30<43:45, 28.01it/s]

 27%|██▋       | 27090/100629 [21:30<49:58, 24.53it/s]

 27%|██▋       | 27094/100629 [21:31<46:49, 26.18it/s]

 27%|██▋       | 27097/100629 [21:31<46:31, 26.34it/s]

 27%|██▋       | 27100/100629 [21:31<56:04, 21.85it/s]

 27%|██▋       | 27103/100629 [21:31<1:03:35, 19.27it/s]

 27%|██▋       | 27106/100629 [21:31<1:00:56, 20.11it/s]

 27%|██▋       | 27110/100629 [21:31<54:55, 22.31it/s]

 27%|██▋       | 27114/100629 [21:31<49:01, 24.99it/s]

 27%|██▋       | 27117/100629 [21:32<49:50, 24.58it/s]

 27%|██▋       | 27121/100629 [21:32<45:35, 26.87it/s]

 27%|██▋       | 27124/100629 [21:32<53:37, 22.85it/s]

 27%|██▋       | 27127/100629 [21:32<54:33, 22.45it/s]

 27%|██▋       | 27130/100629 [21:32<52:57, 23.13it/s]

 27%|██▋       | 27134/100629 [21:32<45:36, 26.86it/s]

 27%|██▋       | 27138/100629 [21:32<44:35, 27.47it/s]

 27%|██▋       | 27141/100629 [21:33<50:04, 24.46it/s]

 27%|██▋       | 27144/100629 [21:33<54:02, 22.67it/s]

 27%|██▋       | 27148/100629 [21:33<49:35, 24.69it/s]

 27%|██▋       | 27151/100629 [21:33<1:14:20, 16.47it/s]

 27%|██▋       | 27154/100629 [21:33<1:12:14, 16.95it/s]

 27%|██▋       | 27157/100629 [21:33<1:04:29, 18.99it/s]

 27%|██▋       | 27161/100629 [21:34<59:16, 20.66it/s]

 27%|██▋       | 27165/100629 [21:34<59:35, 20.55it/s]

 27%|██▋       | 27168/100629 [21:34<1:06:25, 18.43it/s]

 27%|██▋       | 27173/100629 [21:34<52:01, 23.53it/s]

 27%|██▋       | 27176/100629 [21:34<50:32, 24.22it/s]

 27%|██▋       | 27179/100629 [21:34<51:35, 23.72it/s]

 27%|██▋       | 27182/100629 [21:35<58:49, 20.81it/s]

 27%|██▋       | 27185/100629 [21:35<59:06, 20.71it/s]

 27%|██▋       | 27188/100629 [21:35<59:25, 20.60it/s]

 27%|██▋       | 27191/100629 [21:35<1:06:09, 18.50it/s]

 27%|██▋       | 27194/100629 [21:35<1:05:15, 18.76it/s]

 27%|██▋       | 27196/100629 [21:35<1:05:29, 18.69it/s]

 27%|██▋       | 27200/100629 [21:35<58:40, 20.86it/s]

 27%|██▋       | 27203/100629 [21:36<53:39, 22.81it/s]

 27%|██▋       | 27206/100629 [21:36<54:11, 22.58it/s]

 27%|██▋       | 27209/100629 [21:36<57:05, 21.44it/s]

 27%|██▋       | 27212/100629 [21:36<53:01, 23.08it/s]

 27%|██▋       | 27215/100629 [21:36<1:06:22, 18.43it/s]

 27%|██▋       | 27219/100629 [21:36<1:00:43, 20.15it/s]

 27%|██▋       | 27223/100629 [21:37<55:56, 21.87it/s]

 27%|██▋       | 27226/100629 [21:37<1:00:33, 20.20it/s]

 27%|██▋       | 27229/100629 [21:37<1:06:17, 18.45it/s]

 27%|██▋       | 27231/100629 [21:37<1:07:00, 18.25it/s]

 27%|██▋       | 27234/100629 [21:37<1:05:46, 18.60it/s]

 27%|██▋       | 27236/100629 [21:37<1:11:36, 17.08it/s]

 27%|██▋       | 27238/100629 [21:37<1:10:04, 17.46it/s]

 27%|██▋       | 27240/100629 [21:38<1:13:55, 16.55it/s]

 27%|██▋       | 27242/100629 [21:38<1:25:35, 14.29it/s]

 27%|██▋       | 27244/100629 [21:38<1:24:23, 14.49it/s]

 27%|██▋       | 27246/100629 [21:38<1:32:49, 13.18it/s]

 27%|██▋       | 27248/100629 [21:38<1:28:10, 13.87it/s]

 27%|██▋       | 27253/100629 [21:38<57:58, 21.10it/s]

 27%|██▋       | 27257/100629 [21:38<50:44, 24.10it/s]

 27%|██▋       | 27261/100629 [21:39<45:35, 26.82it/s]

 27%|██▋       | 27264/100629 [21:39<46:26, 26.33it/s]

 27%|██▋       | 27267/100629 [21:39<49:40, 24.62it/s]

 27%|██▋       | 27270/100629 [21:39<51:32, 23.72it/s]

 27%|██▋       | 27273/100629 [21:39<55:45, 21.92it/s]

 27%|██▋       | 27276/100629 [21:39<52:57, 23.09it/s]

 27%|██▋       | 27279/100629 [21:39<53:58, 22.65it/s]

 27%|██▋       | 27282/100629 [21:40<1:00:49, 20.10it/s]

 27%|██▋       | 27285/100629 [21:40<1:00:24, 20.23it/s]

 27%|██▋       | 27288/100629 [21:40<54:53, 22.27it/s]

 27%|██▋       | 27292/100629 [21:40<52:40, 23.20it/s]

 27%|██▋       | 27296/100629 [21:40<48:28, 25.22it/s]

 27%|██▋       | 27300/100629 [21:40<44:15, 27.62it/s]

 27%|██▋       | 27304/100629 [21:40<43:33, 28.06it/s]

 27%|██▋       | 27307/100629 [21:41<46:06, 26.51it/s]

 27%|██▋       | 27310/100629 [21:41<45:20, 26.95it/s]

 27%|██▋       | 27313/100629 [21:41<48:46, 25.05it/s]

 27%|██▋       | 27316/100629 [21:41<46:52, 26.07it/s]

 27%|██▋       | 27319/100629 [21:41<51:07, 23.90it/s]

 27%|██▋       | 27322/100629 [21:41<56:04, 21.79it/s]

 27%|██▋       | 27325/100629 [21:41<53:34, 22.81it/s]

 27%|██▋       | 27328/100629 [21:41<57:25, 21.28it/s]

 27%|██▋       | 27331/100629 [21:42<54:04, 22.59it/s]

 27%|██▋       | 27334/100629 [21:42<1:00:45, 20.11it/s]

 27%|██▋       | 27338/100629 [21:42<54:07, 22.57it/s]

 27%|██▋       | 27342/100629 [21:42<49:49, 24.52it/s]

 27%|██▋       | 27345/100629 [21:42<56:26, 21.64it/s]

 27%|██▋       | 27349/100629 [21:42<51:27, 23.74it/s]

 27%|██▋       | 27354/100629 [21:42<44:21, 27.53it/s]

 27%|██▋       | 27357/100629 [21:43<43:37, 28.00it/s]

 27%|██▋       | 27360/100629 [21:43<59:23, 20.56it/s]

 27%|██▋       | 27363/100629 [21:43<1:10:14, 17.38it/s]

 27%|██▋       | 27366/100629 [21:43<1:06:22, 18.39it/s]

 27%|██▋       | 27369/100629 [21:43<1:10:46, 17.25it/s]

 27%|██▋       | 27372/100629 [21:44<1:02:46, 19.45it/s]

 27%|██▋       | 27376/100629 [21:44<53:20, 22.89it/s]

 27%|██▋       | 27379/100629 [21:44<57:10, 21.35it/s]

 27%|██▋       | 27382/100629 [21:44<1:06:49, 18.27it/s]

 27%|██▋       | 27385/100629 [21:44<1:09:41, 17.52it/s]

 27%|██▋       | 27389/100629 [21:44<56:44, 21.51it/s]

 27%|██▋       | 27392/100629 [21:44<52:48, 23.12it/s]

 27%|██▋       | 27395/100629 [21:45<55:13, 22.10it/s]

 27%|██▋       | 27398/100629 [21:45<55:16, 22.08it/s]

 27%|██▋       | 27401/100629 [21:45<54:31, 22.39it/s]

 27%|██▋       | 27404/100629 [21:45<53:59, 22.60it/s]

 27%|██▋       | 27407/100629 [21:45<57:52, 21.09it/s]

 27%|██▋       | 27410/100629 [21:45<1:04:40, 18.87it/s]

 27%|██▋       | 27413/100629 [21:45<1:00:38, 20.12it/s]

 27%|██▋       | 27416/100629 [21:46<55:20, 22.05it/s]

 27%|██▋       | 27419/100629 [21:46<1:12:34, 16.81it/s]

 27%|██▋       | 27421/100629 [21:46<1:12:07, 16.92it/s]

 27%|██▋       | 27423/100629 [21:46<1:12:17, 16.88it/s]

 27%|██▋       | 27426/100629 [21:46<1:02:30, 19.52it/s]

 27%|██▋       | 27430/100629 [21:46<52:00, 23.46it/s]

 27%|██▋       | 27434/100629 [21:46<47:10, 25.86it/s]

 27%|██▋       | 27439/100629 [21:47<44:41, 27.29it/s]

 27%|██▋       | 27442/100629 [21:47<45:45, 26.65it/s]

 27%|██▋       | 27447/100629 [21:47<38:13, 31.91it/s]

 27%|██▋       | 27451/100629 [21:47<1:02:53, 19.39it/s]

 27%|██▋       | 27454/100629 [21:47<59:53, 20.37it/s]

 27%|██▋       | 27458/100629 [21:47<52:32, 23.21it/s]

 27%|██▋       | 27461/100629 [21:48<54:09, 22.52it/s]

 27%|██▋       | 27465/100629 [21:48<47:35, 25.62it/s]

 27%|██▋       | 27468/100629 [21:48<50:05, 24.34it/s]

 27%|██▋       | 27473/100629 [21:48<46:13, 26.38it/s]

 27%|██▋       | 27476/100629 [21:48<47:33, 25.63it/s]

 27%|██▋       | 27479/100629 [21:48<50:52, 23.97it/s]

 27%|██▋       | 27483/100629 [21:48<46:55, 25.98it/s]

 27%|██▋       | 27487/100629 [21:49<44:07, 27.62it/s]

 27%|██▋       | 27490/100629 [21:49<56:20, 21.63it/s]

 27%|██▋       | 27493/100629 [21:49<58:53, 20.70it/s]

 27%|██▋       | 27497/100629 [21:49<52:03, 23.41it/s]

 27%|██▋       | 27500/100629 [21:49<1:07:20, 18.10it/s]

 27%|██▋       | 27503/100629 [21:49<1:01:58, 19.66it/s]

 27%|██▋       | 27506/100629 [21:50<59:47, 20.38it/s]

 27%|██▋       | 27510/100629 [21:50<56:37, 21.52it/s]

 27%|██▋       | 27513/100629 [21:50<1:02:53, 19.38it/s]

 27%|██▋       | 27516/100629 [21:50<1:05:57, 18.48it/s]

 27%|██▋       | 27520/100629 [21:50<59:24, 20.51it/s]

 27%|██▋       | 27523/100629 [21:50<1:02:53, 19.37it/s]

 27%|██▋       | 27525/100629 [21:51<1:04:35, 18.86it/s]

 27%|██▋       | 27529/100629 [21:51<53:16, 22.87it/s]

 27%|██▋       | 27532/100629 [21:51<58:46, 20.73it/s]

 27%|██▋       | 27535/100629 [21:51<54:02, 22.54it/s]

 27%|██▋       | 27539/100629 [21:51<48:19, 25.21it/s]

 27%|██▋       | 27542/100629 [21:51<52:42, 23.11it/s]

 27%|██▋       | 27546/100629 [21:51<46:43, 26.07it/s]

 27%|██▋       | 27549/100629 [21:52<54:30, 22.34it/s]

 27%|██▋       | 27553/100629 [21:52<49:13, 24.74it/s]

 27%|██▋       | 27556/100629 [21:52<47:14, 25.78it/s]

 27%|██▋       | 27559/100629 [21:52<1:03:07, 19.29it/s]

 27%|██▋       | 27562/100629 [21:52<58:40, 20.75it/s]

 27%|██▋       | 27566/100629 [21:52<56:19, 21.62it/s]

 27%|██▋       | 27569/100629 [21:53<1:05:43, 18.53it/s]

 27%|██▋       | 27572/100629 [21:53<1:02:28, 19.49it/s]

 27%|██▋       | 27576/100629 [21:53<56:30, 21.55it/s]

 27%|██▋       | 27579/100629 [21:53<53:19, 22.83it/s]

 27%|██▋       | 27582/100629 [21:53<50:55, 23.90it/s]

 27%|██▋       | 27587/100629 [21:53<40:25, 30.12it/s]

 27%|██▋       | 27592/100629 [21:53<38:33, 31.57it/s]

 27%|██▋       | 27597/100629 [21:53<34:21, 35.42it/s]

 27%|██▋       | 27601/100629 [21:54<38:52, 31.31it/s]

 27%|██▋       | 27605/100629 [21:54<46:45, 26.03it/s]

 27%|██▋       | 27608/100629 [21:54<52:45, 23.07it/s]

 27%|██▋       | 27611/100629 [21:54<57:12, 21.27it/s]

 27%|██▋       | 27615/100629 [21:54<50:43, 23.99it/s]

 27%|██▋       | 27618/100629 [21:54<54:25, 22.36it/s]

 27%|██▋       | 27621/100629 [21:55<51:39, 23.56it/s]

 27%|██▋       | 27624/100629 [21:55<57:39, 21.10it/s]

 27%|██▋       | 27628/100629 [21:55<52:26, 23.20it/s]

 27%|██▋       | 27631/100629 [21:55<50:29, 24.10it/s]

 27%|██▋       | 27634/100629 [21:55<1:06:21, 18.33it/s]

 27%|██▋       | 27638/100629 [21:55<1:01:01, 19.93it/s]

 27%|██▋       | 27641/100629 [21:56<1:12:49, 16.70it/s]

 27%|██▋       | 27643/100629 [21:56<1:11:06, 17.11it/s]

 27%|██▋       | 27645/100629 [21:56<1:10:11, 17.33it/s]

 27%|██▋       | 27649/100629 [21:56<57:30, 21.15it/s]

 27%|██▋       | 27652/100629 [21:56<56:40, 21.46it/s]

 27%|██▋       | 27655/100629 [21:56<58:17, 20.87it/s]

 27%|██▋       | 27658/100629 [21:56<53:17, 22.82it/s]

 27%|██▋       | 27661/100629 [21:57<52:38, 23.11it/s]

 27%|██▋       | 27664/100629 [21:57<55:09, 22.05it/s]

 27%|██▋       | 27667/100629 [21:57<57:43, 21.07it/s]

 27%|██▋       | 27670/100629 [21:57<53:41, 22.65it/s]

 28%|██▊       | 27673/100629 [21:57<51:48, 23.47it/s]

 28%|██▊       | 27676/100629 [21:57<1:03:26, 19.17it/s]

 28%|██▊       | 27679/100629 [21:57<1:00:06, 20.23it/s]

 28%|██▊       | 27682/100629 [21:58<1:05:25, 18.58it/s]

 28%|██▊       | 27686/100629 [21:58<1:01:41, 19.71it/s]

 28%|██▊       | 27689/100629 [21:58<1:04:22, 18.88it/s]

 28%|██▊       | 27691/100629 [21:58<1:03:49, 19.05it/s]

 28%|██▊       | 27694/100629 [21:58<58:51, 20.65it/s]

 28%|██▊       | 27698/100629 [21:58<54:38, 22.25it/s]

 28%|██▊       | 27702/100629 [21:59<1:09:20, 17.53it/s]

 28%|██▊       | 27705/100629 [21:59<1:04:05, 18.97it/s]

 28%|██▊       | 27708/100629 [21:59<1:25:29, 14.21it/s]

 28%|██▊       | 27712/100629 [21:59<1:09:50, 17.40it/s]

 28%|██▊       | 27715/100629 [21:59<1:13:09, 16.61it/s]

 28%|██▊       | 27717/100629 [22:00<1:26:38, 14.03it/s]

 28%|██▊       | 27719/100629 [22:00<1:31:03, 13.35it/s]

 28%|██▊       | 27721/100629 [22:00<1:34:36, 12.84it/s]

 28%|██▊       | 27725/100629 [22:00<1:14:04, 16.40it/s]

 28%|██▊       | 27728/100629 [22:00<1:12:04, 16.86it/s]

 28%|██▊       | 27730/100629 [22:00<1:11:22, 17.02it/s]

 28%|██▊       | 27732/100629 [22:01<1:16:40, 15.85it/s]

 28%|██▊       | 27735/100629 [22:01<1:06:42, 18.21it/s]

 28%|██▊       | 27737/100629 [22:01<1:11:11, 17.06it/s]

 28%|██▊       | 27740/100629 [22:01<1:01:54, 19.63it/s]

 28%|██▊       | 27743/100629 [22:01<1:04:27, 18.84it/s]

 28%|██▊       | 27746/100629 [22:01<1:03:16, 19.20it/s]

 28%|██▊       | 27749/100629 [22:01<1:02:47, 19.35it/s]

 28%|██▊       | 27751/100629 [22:02<1:04:40, 18.78it/s]

 28%|██▊       | 27754/100629 [22:02<57:44, 21.03it/s]

 28%|██▊       | 27757/100629 [22:02<1:09:22, 17.51it/s]

 28%|██▊       | 27760/100629 [22:02<1:08:48, 17.65it/s]

 28%|██▊       | 27763/100629 [22:02<1:00:38, 20.03it/s]

 28%|██▊       | 27766/100629 [22:02<57:16, 21.20it/s]

 28%|██▊       | 27769/100629 [22:02<53:50, 22.55it/s]

 28%|██▊       | 27772/100629 [22:03<51:30, 23.58it/s]

 28%|██▊       | 27775/100629 [22:03<53:22, 22.75it/s]

 28%|██▊       | 27778/100629 [22:03<56:29, 21.49it/s]

 28%|██▊       | 27781/100629 [22:03<59:29, 20.41it/s]

 28%|██▊       | 27785/100629 [22:03<48:52, 24.84it/s]

 28%|██▊       | 27788/100629 [22:03<54:06, 22.44it/s]

 28%|██▊       | 27791/100629 [22:03<53:20, 22.76it/s]

 28%|██▊       | 27794/100629 [22:04<54:04, 22.45it/s]

 28%|██▊       | 27797/100629 [22:04<56:41, 21.41it/s]

 28%|██▊       | 27800/100629 [22:04<55:20, 21.93it/s]

 28%|██▊       | 27803/100629 [22:04<59:04, 20.55it/s]

 28%|██▊       | 27806/100629 [22:04<1:12:33, 16.73it/s]

 28%|██▊       | 27808/100629 [22:04<1:17:40, 15.63it/s]

 28%|██▊       | 27812/100629 [22:05<1:03:14, 19.19it/s]

 28%|██▊       | 27815/100629 [22:05<59:25, 20.42it/s]

 28%|██▊       | 27818/100629 [22:05<1:00:31, 20.05it/s]

 28%|██▊       | 27821/100629 [22:05<1:13:46, 16.45it/s]

 28%|██▊       | 27823/100629 [22:05<1:11:22, 17.00it/s]

 28%|██▊       | 27825/100629 [22:05<1:24:49, 14.30it/s]

 28%|██▊       | 27828/100629 [22:06<1:12:32, 16.73it/s]

 28%|██▊       | 27834/100629 [22:06<50:10, 24.18it/s]

 28%|██▊       | 27837/100629 [22:06<56:49, 21.35it/s]

 28%|██▊       | 27841/100629 [22:06<51:58, 23.34it/s]

 28%|██▊       | 27844/100629 [22:06<1:06:43, 18.18it/s]

 28%|██▊       | 27848/100629 [22:06<55:46, 21.75it/s]

 28%|██▊       | 27851/100629 [22:07<55:31, 21.85it/s]

 28%|██▊       | 27854/100629 [22:07<52:45, 22.99it/s]

 28%|██▊       | 27857/100629 [22:07<50:12, 24.16it/s]

 28%|██▊       | 27860/100629 [22:07<52:56, 22.91it/s]

 28%|██▊       | 27863/100629 [22:07<56:00, 21.65it/s]

 28%|██▊       | 27866/100629 [22:07<52:31, 23.09it/s]

 28%|██▊       | 27869/100629 [22:07<1:02:42, 19.34it/s]

 28%|██▊       | 27872/100629 [22:07<59:00, 20.55it/s]

 28%|██▊       | 27875/100629 [22:08<54:18, 22.33it/s]

 28%|██▊       | 27878/100629 [22:08<54:42, 22.16it/s]

 28%|██▊       | 27883/100629 [22:08<49:06, 24.69it/s]

 28%|██▊       | 27887/100629 [22:08<49:33, 24.47it/s]

 28%|██▊       | 27890/100629 [22:08<52:47, 22.97it/s]

 28%|██▊       | 27893/100629 [22:08<1:00:40, 19.98it/s]

 28%|██▊       | 27896/100629 [22:09<1:22:48, 14.64it/s]

 28%|██▊       | 27898/100629 [22:09<1:23:35, 14.50it/s]

 28%|██▊       | 27900/100629 [22:09<1:19:25, 15.26it/s]

 28%|██▊       | 27903/100629 [22:09<1:10:04, 17.30it/s]

 28%|██▊       | 27905/100629 [22:09<1:09:27, 17.45it/s]

 28%|██▊       | 27910/100629 [22:09<50:24, 24.04it/s]

 28%|██▊       | 27913/100629 [22:09<48:07, 25.18it/s]

 28%|██▊       | 27916/100629 [22:10<47:14, 25.65it/s]

 28%|██▊       | 27920/100629 [22:10<46:33, 26.03it/s]

 28%|██▊       | 27923/100629 [22:10<44:59, 26.93it/s]

 28%|██▊       | 27926/100629 [22:10<46:22, 26.13it/s]

 28%|██▊       | 27929/100629 [22:10<50:35, 23.95it/s]

 28%|██▊       | 27932/100629 [22:10<57:04, 21.23it/s]

 28%|██▊       | 27935/100629 [22:11<1:10:07, 17.28it/s]

 28%|██▊       | 27937/100629 [22:11<1:22:20, 14.71it/s]

 28%|██▊       | 27940/100629 [22:11<1:15:43, 16.00it/s]

 28%|██▊       | 27944/100629 [22:11<1:00:52, 19.90it/s]

 28%|██▊       | 27947/100629 [22:11<55:45, 21.72it/s]

 28%|██▊       | 27950/100629 [22:11<55:21, 21.88it/s]

 28%|██▊       | 27953/100629 [22:11<55:01, 22.01it/s]

 28%|██▊       | 27956/100629 [22:12<1:03:24, 19.10it/s]

 28%|██▊       | 27959/100629 [22:12<58:35, 20.67it/s]

 28%|██▊       | 27962/100629 [22:12<53:21, 22.70it/s]

 28%|██▊       | 27966/100629 [22:12<51:56, 23.32it/s]

 28%|██▊       | 27969/100629 [22:12<51:58, 23.30it/s]

 28%|██▊       | 27973/100629 [22:12<54:25, 22.25it/s]

 28%|██▊       | 27977/100629 [22:12<48:36, 24.91it/s]

 28%|██▊       | 27981/100629 [22:13<48:41, 24.87it/s]

 28%|██▊       | 27984/100629 [22:13<52:19, 23.14it/s]

 28%|██▊       | 27987/100629 [22:13<51:29, 23.51it/s]

 28%|██▊       | 27991/100629 [22:13<46:20, 26.13it/s]

 28%|██▊       | 27996/100629 [22:13<43:24, 27.89it/s]

 28%|██▊       | 27999/100629 [22:13<49:35, 24.41it/s]

 28%|██▊       | 28002/100629 [22:14<56:17, 21.50it/s]

 28%|██▊       | 28005/100629 [22:14<56:06, 21.57it/s]

 28%|██▊       | 28008/100629 [22:14<54:26, 22.23it/s]

 28%|██▊       | 28011/100629 [22:14<54:09, 22.35it/s]

 28%|██▊       | 28014/100629 [22:14<54:35, 22.17it/s]

 28%|██▊       | 28017/100629 [22:14<53:37, 22.57it/s]

 28%|██▊       | 28020/100629 [22:14<54:35, 22.17it/s]

 28%|██▊       | 28023/100629 [22:14<51:32, 23.48it/s]

 28%|██▊       | 28026/100629 [22:15<56:36, 21.38it/s]

 28%|██▊       | 28029/100629 [22:15<55:08, 21.94it/s]

 28%|██▊       | 28033/100629 [22:15<47:07, 25.67it/s]

 28%|██▊       | 28036/100629 [22:15<52:37, 22.99it/s]

 28%|██▊       | 28039/100629 [22:15<49:30, 24.44it/s]

 28%|██▊       | 28042/100629 [22:15<57:20, 21.10it/s]

 28%|██▊       | 28047/100629 [22:15<45:13, 26.75it/s]

 28%|██▊       | 28050/100629 [22:16<44:54, 26.93it/s]

 28%|██▊       | 28053/100629 [22:16<44:59, 26.88it/s]

 28%|██▊       | 28056/100629 [22:16<53:57, 22.42it/s]

 28%|██▊       | 28060/100629 [22:16<46:32, 25.99it/s]

 28%|██▊       | 28063/100629 [22:16<44:55, 26.92it/s]

 28%|██▊       | 28066/100629 [22:16<47:58, 25.20it/s]

 28%|██▊       | 28071/100629 [22:16<40:19, 29.99it/s]

 28%|██▊       | 28075/100629 [22:17<50:35, 23.90it/s]

 28%|██▊       | 28078/100629 [22:17<49:22, 24.49it/s]

 28%|██▊       | 28081/100629 [22:17<53:48, 22.47it/s]

 28%|██▊       | 28084/100629 [22:17<53:05, 22.78it/s]

 28%|██▊       | 28087/100629 [22:17<1:01:55, 19.53it/s]

 28%|██▊       | 28090/100629 [22:17<56:20, 21.46it/s]

 28%|██▊       | 28094/100629 [22:17<49:28, 24.43it/s]

 28%|██▊       | 28099/100629 [22:18<43:13, 27.96it/s]

 28%|██▊       | 28102/100629 [22:18<46:02, 26.25it/s]

 28%|██▊       | 28106/100629 [22:18<44:22, 27.24it/s]

 28%|██▊       | 28111/100629 [22:18<38:49, 31.12it/s]

 28%|██▊       | 28115/100629 [22:18<49:41, 24.32it/s]

 28%|██▊       | 28120/100629 [22:18<45:14, 26.71it/s]

 28%|██▊       | 28123/100629 [22:19<1:01:38, 19.61it/s]

 28%|██▊       | 28126/100629 [22:19<1:00:30, 19.97it/s]

 28%|██▊       | 28129/100629 [22:19<56:13, 21.49it/s]

 28%|██▊       | 28132/100629 [22:19<53:54, 22.41it/s]

 28%|██▊       | 28135/100629 [22:19<1:00:16, 20.05it/s]

 28%|██▊       | 28138/100629 [22:19<1:00:28, 19.98it/s]

 28%|██▊       | 28142/100629 [22:19<55:44, 21.67it/s]

 28%|██▊       | 28145/100629 [22:20<1:05:33, 18.43it/s]

 28%|██▊       | 28147/100629 [22:20<1:04:39, 18.68it/s]

 28%|██▊       | 28150/100629 [22:20<1:03:22, 19.06it/s]

 28%|██▊       | 28152/100629 [22:20<1:32:55, 13.00it/s]

 28%|██▊       | 28154/100629 [22:20<1:25:45, 14.09it/s]

 28%|██▊       | 28157/100629 [22:21<1:15:35, 15.98it/s]

 28%|██▊       | 28160/100629 [22:21<1:06:28, 18.17it/s]

 28%|██▊       | 28163/100629 [22:21<58:33, 20.62it/s]

 28%|██▊       | 28167/100629 [22:21<48:54, 24.69it/s]

 28%|██▊       | 28170/100629 [22:21<49:39, 24.32it/s]

 28%|██▊       | 28173/100629 [22:21<56:54, 21.22it/s]

 28%|██▊       | 28177/100629 [22:21<48:54, 24.69it/s]

 28%|██▊       | 28180/100629 [22:22<1:22:27, 14.64it/s]

 28%|██▊       | 28183/100629 [22:22<1:17:23, 15.60it/s]

 28%|██▊       | 28186/100629 [22:22<1:22:25, 14.65it/s]

 28%|██▊       | 28188/100629 [22:22<1:23:27, 14.47it/s]

 28%|██▊       | 28191/100629 [22:22<1:12:38, 16.62it/s]

 28%|██▊       | 28194/100629 [22:22<1:03:01, 19.15it/s]

 28%|██▊       | 28197/100629 [22:23<56:07, 21.51it/s]

 28%|██▊       | 28200/100629 [22:23<52:49, 22.85it/s]

 28%|██▊       | 28203/100629 [22:23<54:24, 22.18it/s]

 28%|██▊       | 28209/100629 [22:23<42:44, 28.24it/s]

 28%|██▊       | 28212/100629 [22:23<42:17, 28.54it/s]

 28%|██▊       | 28215/100629 [22:23<44:54, 26.87it/s]

 28%|██▊       | 28218/100629 [22:23<48:49, 24.71it/s]

 28%|██▊       | 28221/100629 [22:24<53:28, 22.57it/s]

 28%|██▊       | 28224/100629 [22:24<56:34, 21.33it/s]

 28%|██▊       | 28227/100629 [22:24<1:00:51, 19.83it/s]

 28%|██▊       | 28231/100629 [22:24<56:44, 21.26it/s]

 28%|██▊       | 28234/100629 [22:24<57:48, 20.87it/s]

 28%|██▊       | 28237/100629 [22:24<59:20, 20.33it/s]

 28%|██▊       | 28240/100629 [22:24<55:25, 21.77it/s]

 28%|██▊       | 28245/100629 [22:25<45:16, 26.65it/s]

 28%|██▊       | 28248/100629 [22:25<45:42, 26.39it/s]

 28%|██▊       | 28251/100629 [22:25<47:02, 25.64it/s]

 28%|██▊       | 28254/100629 [22:25<46:22, 26.01it/s]

 28%|██▊       | 28257/100629 [22:25<49:02, 24.59it/s]

 28%|██▊       | 28260/100629 [22:25<47:59, 25.13it/s]

 28%|██▊       | 28263/100629 [22:25<52:03, 23.17it/s]

 28%|██▊       | 28267/100629 [22:25<48:47, 24.72it/s]

 28%|██▊       | 28270/100629 [22:26<50:11, 24.03it/s]

 28%|██▊       | 28273/100629 [22:26<1:13:17, 16.45it/s]

 28%|██▊       | 28276/100629 [22:26<1:11:38, 16.83it/s]

 28%|██▊       | 28279/100629 [22:26<1:02:59, 19.14it/s]

 28%|██▊       | 28283/100629 [22:26<57:25, 21.00it/s]

 28%|██▊       | 28286/100629 [22:27<1:07:12, 17.94it/s]

 28%|██▊       | 28289/100629 [22:27<1:07:53, 17.76it/s]

 28%|██▊       | 28291/100629 [22:27<1:09:17, 17.40it/s]

 28%|██▊       | 28293/100629 [22:27<1:21:57, 14.71it/s]

 28%|██▊       | 28297/100629 [22:27<1:05:06, 18.51it/s]

 28%|██▊       | 28301/100629 [22:27<54:03, 22.30it/s]

 28%|██▊       | 28305/100629 [22:27<52:12, 23.09it/s]

 28%|██▊       | 28308/100629 [22:28<59:18, 20.32it/s]

 28%|██▊       | 28311/100629 [22:28<59:38, 20.21it/s]

 28%|██▊       | 28315/100629 [22:28<51:55, 23.21it/s]

 28%|██▊       | 28318/100629 [22:28<1:01:11, 19.69it/s]

 28%|██▊       | 28322/100629 [22:28<51:28, 23.41it/s]

 28%|██▊       | 28325/100629 [22:28<54:46, 22.00it/s]

 28%|██▊       | 28328/100629 [22:29<1:01:14, 19.68it/s]

 28%|██▊       | 28331/100629 [22:29<1:12:58, 16.51it/s]

 28%|██▊       | 28334/100629 [22:29<1:04:37, 18.64it/s]

 28%|██▊       | 28337/100629 [22:29<57:55, 20.80it/s]

 28%|██▊       | 28341/100629 [22:29<48:55, 24.63it/s]

 28%|██▊       | 28344/100629 [22:29<46:36, 25.85it/s]

 28%|██▊       | 28347/100629 [22:29<48:08, 25.02it/s]

 28%|██▊       | 28352/100629 [22:30<41:22, 29.12it/s]

 28%|██▊       | 28356/100629 [22:30<43:07, 27.93it/s]

 28%|██▊       | 28360/100629 [22:30<40:03, 30.07it/s]

 28%|██▊       | 28364/100629 [22:30<46:37, 25.83it/s]

 28%|██▊       | 28367/100629 [22:30<46:10, 26.08it/s]

 28%|██▊       | 28370/100629 [22:30<48:40, 24.74it/s]

 28%|██▊       | 28374/100629 [22:30<48:16, 24.95it/s]

 28%|██▊       | 28377/100629 [22:31<52:37, 22.88it/s]

 28%|██▊       | 28380/100629 [22:31<1:01:56, 19.44it/s]

 28%|██▊       | 28383/100629 [22:31<1:01:37, 19.54it/s]

 28%|██▊       | 28387/100629 [22:31<56:28, 21.32it/s]

 28%|██▊       | 28390/100629 [22:31<1:01:27, 19.59it/s]

 28%|██▊       | 28393/100629 [22:31<1:02:57, 19.12it/s]

 28%|██▊       | 28395/100629 [22:32<1:08:26, 17.59it/s]

 28%|██▊       | 28398/100629 [22:32<1:02:36, 19.23it/s]

 28%|██▊       | 28402/100629 [22:32<57:51, 20.81it/s]

 28%|██▊       | 28405/100629 [22:32<59:51, 20.11it/s]

 28%|██▊       | 28409/100629 [22:32<51:20, 23.44it/s]

 28%|██▊       | 28412/100629 [22:32<49:56, 24.10it/s]

 28%|██▊       | 28415/100629 [22:32<48:19, 24.90it/s]

 28%|██▊       | 28418/100629 [22:33<48:55, 24.60it/s]

 28%|██▊       | 28421/100629 [22:33<53:40, 22.42it/s]

 28%|██▊       | 28424/100629 [22:33<54:05, 22.25it/s]

 28%|██▊       | 28427/100629 [22:33<50:31, 23.82it/s]

 28%|██▊       | 28430/100629 [22:33<57:36, 20.89it/s]

 28%|██▊       | 28435/100629 [22:33<55:25, 21.71it/s]

 28%|██▊       | 28438/100629 [22:33<51:28, 23.37it/s]

 28%|██▊       | 28442/100629 [22:34<49:11, 24.46it/s]

 28%|██▊       | 28445/100629 [22:34<47:43, 25.20it/s]

 28%|██▊       | 28449/100629 [22:34<46:10, 26.05it/s]

 28%|██▊       | 28452/100629 [22:34<48:22, 24.87it/s]

 28%|██▊       | 28455/100629 [22:34<50:11, 23.96it/s]

 28%|██▊       | 28458/100629 [22:34<55:51, 21.53it/s]

 28%|██▊       | 28461/100629 [22:34<59:52, 20.09it/s]

 28%|██▊       | 28464/100629 [22:35<1:04:30, 18.65it/s]

 28%|██▊       | 28468/100629 [22:35<52:18, 22.99it/s]

 28%|██▊       | 28471/100629 [22:35<1:00:43, 19.80it/s]

 28%|██▊       | 28475/100629 [22:35<53:26, 22.50it/s]

 28%|██▊       | 28478/100629 [22:35<1:02:34, 19.22it/s]

 28%|██▊       | 28483/100629 [22:35<49:38, 24.22it/s]

 28%|██▊       | 28486/100629 [22:36<1:00:16, 19.95it/s]

 28%|██▊       | 28489/100629 [22:36<58:26, 20.57it/s]

 28%|██▊       | 28493/100629 [22:36<54:39, 21.99it/s]

 28%|██▊       | 28496/100629 [22:36<51:03, 23.55it/s]

 28%|██▊       | 28500/100629 [22:36<46:42, 25.74it/s]

 28%|██▊       | 28503/100629 [22:36<46:40, 25.75it/s]

 28%|██▊       | 28506/100629 [22:37<56:59, 21.09it/s]

 28%|██▊       | 28509/100629 [22:37<59:41, 20.13it/s]

 28%|██▊       | 28512/100629 [22:37<1:02:17, 19.29it/s]

 28%|██▊       | 28516/100629 [22:37<56:12, 21.38it/s]

 28%|██▊       | 28519/100629 [22:37<52:49, 22.75it/s]

 28%|██▊       | 28522/100629 [22:37<50:33, 23.77it/s]

 28%|██▊       | 28525/100629 [22:37<51:52, 23.17it/s]

 28%|██▊       | 28528/100629 [22:38<50:46, 23.67it/s]

 28%|██▊       | 28532/100629 [22:38<49:21, 24.35it/s]

 28%|██▊       | 28535/100629 [22:38<50:57, 23.58it/s]

 28%|██▊       | 28538/100629 [22:38<50:01, 24.02it/s]

 28%|██▊       | 28541/100629 [22:38<52:14, 23.00it/s]

 28%|██▊       | 28544/100629 [22:38<57:02, 21.06it/s]

 28%|██▊       | 28547/100629 [22:38<54:24, 22.08it/s]

 28%|██▊       | 28550/100629 [22:39<57:12, 21.00it/s]

 28%|██▊       | 28553/100629 [22:39<58:52, 20.41it/s]

 28%|██▊       | 28556/100629 [22:39<55:04, 21.81it/s]

 28%|██▊       | 28559/100629 [22:39<52:43, 22.79it/s]

 28%|██▊       | 28562/100629 [22:39<49:56, 24.05it/s]

 28%|██▊       | 28565/100629 [22:39<50:20, 23.86it/s]

 28%|██▊       | 28569/100629 [22:39<49:41, 24.17it/s]

 28%|██▊       | 28572/100629 [22:39<51:10, 23.47it/s]

 28%|██▊       | 28575/100629 [22:40<52:44, 22.77it/s]

 28%|██▊       | 28578/100629 [22:40<59:03, 20.33it/s]

 28%|██▊       | 28582/100629 [22:40<49:09, 24.42it/s]

 28%|██▊       | 28585/100629 [22:40<1:18:25, 15.31it/s]

 28%|██▊       | 28588/100629 [22:40<1:10:28, 17.04it/s]

 28%|██▊       | 28591/100629 [22:41<1:16:40, 15.66it/s]

 28%|██▊       | 28594/100629 [22:41<1:06:30, 18.05it/s]

 28%|██▊       | 28597/100629 [22:41<1:07:21, 17.82it/s]

 28%|██▊       | 28600/100629 [22:41<1:10:05, 17.13it/s]

 28%|██▊       | 28603/100629 [22:41<1:14:54, 16.03it/s]

 28%|██▊       | 28606/100629 [22:41<1:11:50, 16.71it/s]

 28%|██▊       | 28609/100629 [22:42<1:06:04, 18.16it/s]

 28%|██▊       | 28612/100629 [22:42<1:03:25, 18.93it/s]

 28%|██▊       | 28615/100629 [22:42<1:00:14, 19.92it/s]

 28%|██▊       | 28619/100629 [22:42<55:40, 21.56it/s]

 28%|██▊       | 28623/100629 [22:42<52:47, 22.73it/s]

 28%|██▊       | 28626/100629 [22:42<54:52, 21.87it/s]

 28%|██▊       | 28629/100629 [22:42<57:05, 21.02it/s]

 28%|██▊       | 28632/100629 [22:43<55:57, 21.44it/s]

 28%|██▊       | 28635/100629 [22:43<55:27, 21.63it/s]

 28%|██▊       | 28638/100629 [22:43<1:00:37, 19.79it/s]

 28%|██▊       | 28641/100629 [22:43<59:35, 20.14it/s]

 28%|██▊       | 28644/100629 [22:43<54:15, 22.11it/s]

 28%|██▊       | 28647/100629 [22:43<54:58, 21.82it/s]

 28%|██▊       | 28651/100629 [22:44<1:08:37, 17.48it/s]

 28%|██▊       | 28655/100629 [22:44<59:44, 20.08it/s]

 28%|██▊       | 28658/100629 [22:44<59:08, 20.28it/s]

 28%|██▊       | 28661/100629 [22:44<54:05, 22.18it/s]

 28%|██▊       | 28664/100629 [22:44<51:38, 23.23it/s]

 28%|██▊       | 28668/100629 [22:44<46:14, 25.94it/s]

 28%|██▊       | 28672/100629 [22:44<44:37, 26.87it/s]

 28%|██▊       | 28676/100629 [22:45<46:31, 25.78it/s]

 28%|██▊       | 28679/100629 [22:45<53:59, 22.21it/s]

 29%|██▊       | 28682/100629 [22:45<55:29, 21.61it/s]

 29%|██▊       | 28685/100629 [22:45<1:05:27, 18.32it/s]

 29%|██▊       | 28688/100629 [22:45<1:00:08, 19.94it/s]

 29%|██▊       | 28691/100629 [22:45<1:06:26, 18.04it/s]

 29%|██▊       | 28695/100629 [22:46<59:07, 20.28it/s]

 29%|██▊       | 28699/100629 [22:46<51:07, 23.45it/s]

 29%|██▊       | 28702/100629 [22:46<58:25, 20.52it/s]

 29%|██▊       | 28705/100629 [22:46<53:25, 22.44it/s]

 29%|██▊       | 28709/100629 [22:46<51:26, 23.30it/s]

 29%|██▊       | 28712/100629 [22:46<52:17, 22.92it/s]

 29%|██▊       | 28715/100629 [22:46<53:59, 22.20it/s]

 29%|██▊       | 28719/100629 [22:47<53:29, 22.41it/s]

 29%|██▊       | 28722/100629 [22:47<50:18, 23.82it/s]

 29%|██▊       | 28725/100629 [22:47<51:18, 23.36it/s]

 29%|██▊       | 28728/100629 [22:47<49:53, 24.02it/s]

 29%|██▊       | 28731/100629 [22:47<53:12, 22.52it/s]

 29%|██▊       | 28734/100629 [22:47<53:42, 22.31it/s]

 29%|██▊       | 28737/100629 [22:47<49:56, 23.99it/s]

 29%|██▊       | 28740/100629 [22:48<52:46, 22.71it/s]

 29%|██▊       | 28744/100629 [22:48<49:39, 24.13it/s]

 29%|██▊       | 28747/100629 [22:48<54:13, 22.10it/s]

 29%|██▊       | 28751/100629 [22:48<47:52, 25.02it/s]

 29%|██▊       | 28755/100629 [22:48<45:42, 26.21it/s]

 29%|██▊       | 28758/100629 [22:48<49:43, 24.09it/s]

 29%|██▊       | 28762/100629 [22:48<44:36, 26.85it/s]

 29%|██▊       | 28765/100629 [22:49<54:00, 22.18it/s]

 29%|██▊       | 28768/100629 [22:49<53:48, 22.26it/s]

 29%|██▊       | 28771/100629 [22:49<1:06:13, 18.08it/s]

 29%|██▊       | 28774/100629 [22:49<1:07:58, 17.62it/s]

 29%|██▊       | 28777/100629 [22:49<1:05:14, 18.36it/s]

 29%|██▊       | 28780/100629 [22:49<1:06:22, 18.04it/s]

 29%|██▊       | 28782/100629 [22:50<1:07:04, 17.85it/s]

 29%|██▊       | 28784/100629 [22:50<1:14:00, 16.18it/s]

 29%|██▊       | 28786/100629 [22:50<1:15:05, 15.94it/s]

 29%|██▊       | 28788/100629 [22:50<1:18:47, 15.20it/s]

 29%|██▊       | 28790/100629 [22:50<1:22:51, 14.45it/s]

 29%|██▊       | 28793/100629 [22:50<1:09:16, 17.28it/s]

 29%|██▊       | 28795/100629 [22:50<1:12:22, 16.54it/s]

 29%|██▊       | 28799/100629 [22:51<1:01:31, 19.46it/s]

 29%|██▊       | 28803/100629 [22:51<58:35, 20.43it/s]

 29%|██▊       | 28806/100629 [22:51<57:40, 20.76it/s]

 29%|██▊       | 28809/100629 [22:51<55:00, 21.76it/s]

 29%|██▊       | 28812/100629 [22:51<1:05:08, 18.37it/s]

 29%|██▊       | 28814/100629 [22:51<1:10:27, 16.99it/s]

 29%|██▊       | 28817/100629 [22:52<1:10:50, 16.90it/s]

 29%|██▊       | 28820/100629 [22:52<1:05:14, 18.34it/s]

 29%|██▊       | 28825/100629 [22:52<49:02, 24.40it/s]

 29%|██▊       | 28828/100629 [22:52<56:53, 21.03it/s]

 29%|██▊       | 28831/100629 [22:52<57:09, 20.94it/s]

 29%|██▊       | 28834/100629 [22:52<1:02:53, 19.02it/s]

 29%|██▊       | 28838/100629 [22:52<54:59, 21.76it/s]

 29%|██▊       | 28841/100629 [22:53<1:03:00, 18.99it/s]

 29%|██▊       | 28844/100629 [22:53<1:03:14, 18.92it/s]

 29%|██▊       | 28848/100629 [22:53<1:00:23, 19.81it/s]

 29%|██▊       | 28851/100629 [22:53<1:06:30, 17.99it/s]

 29%|██▊       | 28854/100629 [22:53<1:02:46, 19.05it/s]

 29%|██▊       | 28857/100629 [22:53<56:41, 21.10it/s]

 29%|██▊       | 28861/100629 [22:54<49:12, 24.31it/s]

 29%|██▊       | 28867/100629 [22:54<37:37, 31.79it/s]

 29%|██▊       | 28871/100629 [22:54<35:51, 33.34it/s]

 29%|██▊       | 28875/100629 [22:54<47:33, 25.15it/s]

 29%|██▊       | 28879/100629 [22:54<43:06, 27.74it/s]

 29%|██▊       | 28883/100629 [22:54<40:14, 29.72it/s]

 29%|██▊       | 28887/100629 [22:55<47:34, 25.13it/s]

 29%|██▊       | 28892/100629 [22:55<41:17, 28.96it/s]

 29%|██▊       | 28896/100629 [22:55<40:26, 29.56it/s]

 29%|██▊       | 28900/100629 [22:55<42:27, 28.15it/s]

 29%|██▊       | 28903/100629 [22:55<42:50, 27.90it/s]

 29%|██▊       | 28906/100629 [22:55<52:17, 22.86it/s]

 29%|██▊       | 28909/100629 [22:55<52:41, 22.69it/s]

 29%|██▊       | 28912/100629 [22:55<50:05, 23.86it/s]

 29%|██▊       | 28915/100629 [22:56<54:38, 21.88it/s]

 29%|██▊       | 28918/100629 [22:56<57:08, 20.91it/s]

 29%|██▊       | 28921/100629 [22:56<54:51, 21.79it/s]

 29%|██▊       | 28924/100629 [22:56<1:06:20, 18.01it/s]

 29%|██▊       | 28927/100629 [22:56<1:07:28, 17.71it/s]

 29%|██▊       | 28929/100629 [22:56<1:08:14, 17.51it/s]

 29%|██▉       | 28933/100629 [22:57<54:48, 21.80it/s]

 29%|██▉       | 28936/100629 [22:57<58:07, 20.56it/s]

 29%|██▉       | 28939/100629 [22:57<58:29, 20.43it/s]

 29%|██▉       | 28942/100629 [22:57<54:50, 21.78it/s]

 29%|██▉       | 28945/100629 [22:57<58:30, 20.42it/s]

 29%|██▉       | 28949/100629 [22:57<51:24, 23.24it/s]

 29%|██▉       | 28952/100629 [22:57<57:07, 20.91it/s]

 29%|██▉       | 28955/100629 [22:58<54:57, 21.73it/s]

 29%|██▉       | 28959/100629 [22:58<48:10, 24.80it/s]

 29%|██▉       | 28962/100629 [22:58<51:50, 23.04it/s]

 29%|██▉       | 28965/100629 [22:58<58:29, 20.42it/s]

 29%|██▉       | 28968/100629 [22:58<59:44, 19.99it/s]

 29%|██▉       | 28971/100629 [22:58<1:02:52, 19.00it/s]

 29%|██▉       | 28974/100629 [22:59<56:17, 21.21it/s]

 29%|██▉       | 28977/100629 [22:59<52:49, 22.61it/s]

 29%|██▉       | 28980/100629 [22:59<50:34, 23.61it/s]

 29%|██▉       | 28983/100629 [22:59<54:36, 21.86it/s]

 29%|██▉       | 28986/100629 [22:59<57:54, 20.62it/s]

 29%|██▉       | 28989/100629 [22:59<1:07:13, 17.76it/s]

 29%|██▉       | 28991/100629 [22:59<1:05:55, 18.11it/s]

 29%|██▉       | 28994/100629 [22:59<57:58, 20.59it/s]

 29%|██▉       | 28997/100629 [23:00<1:04:46, 18.43it/s]

 29%|██▉       | 29001/100629 [23:00<56:27, 21.14it/s]

 29%|██▉       | 29004/100629 [23:00<59:34, 20.04it/s]

 29%|██▉       | 29007/100629 [23:00<1:05:04, 18.34it/s]

 29%|██▉       | 29009/100629 [23:00<1:08:58, 17.30it/s]

 29%|██▉       | 29012/100629 [23:00<1:00:37, 19.69it/s]

 29%|██▉       | 29015/100629 [23:01<55:41, 21.43it/s]

 29%|██▉       | 29018/100629 [23:01<53:20, 22.38it/s]

 29%|██▉       | 29021/100629 [23:01<51:01, 23.39it/s]

 29%|██▉       | 29024/100629 [23:01<48:32, 24.59it/s]

 29%|██▉       | 29027/100629 [23:01<51:06, 23.35it/s]

 29%|██▉       | 29030/100629 [23:01<55:48, 21.38it/s]

 29%|██▉       | 29034/100629 [23:01<49:47, 23.97it/s]

 29%|██▉       | 29037/100629 [23:02<53:53, 22.14it/s]

 29%|██▉       | 29041/100629 [23:02<48:44, 24.48it/s]

 29%|██▉       | 29044/100629 [23:02<50:58, 23.40it/s]

 29%|██▉       | 29048/100629 [23:02<48:02, 24.83it/s]

 29%|██▉       | 29051/100629 [23:02<51:21, 23.23it/s]

 29%|██▉       | 29055/100629 [23:02<47:00, 25.38it/s]

 29%|██▉       | 29058/100629 [23:02<50:06, 23.81it/s]

 29%|██▉       | 29062/100629 [23:02<46:07, 25.86it/s]

 29%|██▉       | 29065/100629 [23:03<50:08, 23.79it/s]

 29%|██▉       | 29068/100629 [23:03<1:04:54, 18.38it/s]

 29%|██▉       | 29071/100629 [23:03<1:06:47, 17.86it/s]

 29%|██▉       | 29075/100629 [23:03<1:00:51, 19.59it/s]

 29%|██▉       | 29078/100629 [23:03<55:20, 21.55it/s]

 29%|██▉       | 29081/100629 [23:03<53:48, 22.16it/s]

 29%|██▉       | 29084/100629 [23:04<55:14, 21.59it/s]

 29%|██▉       | 29087/100629 [23:04<55:07, 21.63it/s]

 29%|██▉       | 29090/100629 [23:04<51:24, 23.20it/s]

 29%|██▉       | 29093/100629 [23:04<57:45, 20.64it/s]

 29%|██▉       | 29096/100629 [23:04<58:48, 20.28it/s]

 29%|██▉       | 29099/100629 [23:04<58:02, 20.54it/s]

 29%|██▉       | 29102/100629 [23:05<1:07:56, 17.55it/s]

 29%|██▉       | 29106/100629 [23:05<54:45, 21.77it/s]

 29%|██▉       | 29109/100629 [23:05<1:02:40, 19.02it/s]

 29%|██▉       | 29112/100629 [23:05<1:07:04, 17.77it/s]

 29%|██▉       | 29114/100629 [23:05<1:06:02, 18.05it/s]

 29%|██▉       | 29117/100629 [23:05<1:07:17, 17.71it/s]

 29%|██▉       | 29120/100629 [23:05<1:01:49, 19.28it/s]

 29%|██▉       | 29123/100629 [23:06<1:07:20, 17.70it/s]

 29%|██▉       | 29126/100629 [23:06<1:02:32, 19.06it/s]

 29%|██▉       | 29129/100629 [23:06<1:00:08, 19.81it/s]

 29%|██▉       | 29132/100629 [23:06<54:35, 21.83it/s]

 29%|██▉       | 29136/100629 [23:06<46:13, 25.78it/s]

 29%|██▉       | 29139/100629 [23:06<54:26, 21.88it/s]

 29%|██▉       | 29143/100629 [23:07<51:24, 23.17it/s]

 29%|██▉       | 29147/100629 [23:07<46:51, 25.42it/s]

 29%|██▉       | 29150/100629 [23:07<52:41, 22.61it/s]

 29%|██▉       | 29153/100629 [23:07<50:48, 23.44it/s]

 29%|██▉       | 29157/100629 [23:07<46:49, 25.44it/s]

 29%|██▉       | 29160/100629 [23:07<51:16, 23.23it/s]

 29%|██▉       | 29163/100629 [23:07<48:52, 24.37it/s]

 29%|██▉       | 29166/100629 [23:08<56:13, 21.19it/s]

 29%|██▉       | 29169/100629 [23:08<54:18, 21.93it/s]

 29%|██▉       | 29173/100629 [23:08<49:37, 24.00it/s]

 29%|██▉       | 29176/100629 [23:08<50:44, 23.47it/s]

 29%|██▉       | 29179/100629 [23:08<49:47, 23.92it/s]

 29%|██▉       | 29182/100629 [23:08<50:31, 23.56it/s]

 29%|██▉       | 29185/100629 [23:08<54:29, 21.85it/s]

 29%|██▉       | 29188/100629 [23:09<1:06:27, 17.91it/s]

 29%|██▉       | 29190/100629 [23:09<1:11:22, 16.68it/s]

 29%|██▉       | 29193/100629 [23:09<1:04:27, 18.47it/s]

 29%|██▉       | 29196/100629 [23:09<1:03:03, 18.88it/s]

 29%|██▉       | 29200/100629 [23:09<54:14, 21.95it/s]

 29%|██▉       | 29203/100629 [23:09<52:33, 22.65it/s]

 29%|██▉       | 29206/100629 [23:09<52:26, 22.70it/s]

 29%|██▉       | 29209/100629 [23:10<1:02:32, 19.03it/s]

 29%|██▉       | 29212/100629 [23:10<1:03:31, 18.74it/s]

 29%|██▉       | 29214/100629 [23:10<1:07:26, 17.65it/s]

 29%|██▉       | 29216/100629 [23:10<1:11:16, 16.70it/s]

 29%|██▉       | 29219/100629 [23:10<1:04:54, 18.34it/s]

 29%|██▉       | 29222/100629 [23:10<59:32, 19.99it/s]

 29%|██▉       | 29225/100629 [23:11<1:16:31, 15.55it/s]

 29%|██▉       | 29229/100629 [23:11<1:06:59, 17.76it/s]

 29%|██▉       | 29231/100629 [23:11<1:06:17, 17.95it/s]

 29%|██▉       | 29233/100629 [23:11<1:12:01, 16.52it/s]

 29%|██▉       | 29235/100629 [23:11<1:15:17, 15.81it/s]

 29%|██▉       | 29239/100629 [23:11<1:01:27, 19.36it/s]

 29%|██▉       | 29241/100629 [23:11<1:01:59, 19.20it/s]

 29%|██▉       | 29245/100629 [23:12<53:12, 22.36it/s]

 29%|██▉       | 29250/100629 [23:12<46:17, 25.70it/s]

 29%|██▉       | 29254/100629 [23:12<40:58, 29.03it/s]

 29%|██▉       | 29257/100629 [23:12<41:55, 28.37it/s]

 29%|██▉       | 29260/100629 [23:12<59:11, 20.10it/s]

 29%|██▉       | 29263/100629 [23:12<1:09:30, 17.11it/s]

 29%|██▉       | 29266/100629 [23:13<1:07:37, 17.59it/s]

 29%|██▉       | 29268/100629 [23:13<1:16:22, 15.57it/s]

 29%|██▉       | 29273/100629 [23:13<56:36, 21.01it/s]

 29%|██▉       | 29276/100629 [23:13<1:03:25, 18.75it/s]

 29%|██▉       | 29279/100629 [23:13<58:05, 20.47it/s]

 29%|██▉       | 29282/100629 [23:13<58:08, 20.45it/s]

 29%|██▉       | 29285/100629 [23:13<56:57, 20.87it/s]

 29%|██▉       | 29288/100629 [23:14<57:50, 20.56it/s]

 29%|██▉       | 29291/100629 [23:14<1:06:11, 17.96it/s]

 29%|██▉       | 29294/100629 [23:14<1:02:01, 19.17it/s]

 29%|██▉       | 29297/100629 [23:14<1:01:34, 19.31it/s]

 29%|██▉       | 29300/100629 [23:14<55:15, 21.51it/s]

 29%|██▉       | 29304/100629 [23:14<49:08, 24.19it/s]

 29%|██▉       | 29307/100629 [23:15<58:33, 20.30it/s]

 29%|██▉       | 29310/100629 [23:15<1:00:54, 19.52it/s]

 29%|██▉       | 29313/100629 [23:15<1:06:44, 17.81it/s]

 29%|██▉       | 29317/100629 [23:15<56:08, 21.17it/s]

 29%|██▉       | 29320/100629 [23:15<55:52, 21.27it/s]

 29%|██▉       | 29323/100629 [23:15<57:28, 20.68it/s]

 29%|██▉       | 29326/100629 [23:16<57:31, 20.66it/s]

 29%|██▉       | 29329/100629 [23:16<52:27, 22.65it/s]

 29%|██▉       | 29332/100629 [23:16<1:01:53, 19.20it/s]

 29%|██▉       | 29335/100629 [23:16<1:09:38, 17.06it/s]

 29%|██▉       | 29338/100629 [23:16<1:06:28, 17.87it/s]

 29%|██▉       | 29342/100629 [23:16<54:03, 21.98it/s]

 29%|██▉       | 29345/100629 [23:16<52:05, 22.80it/s]

 29%|██▉       | 29348/100629 [23:17<57:33, 20.64it/s]

 29%|██▉       | 29351/100629 [23:17<54:06, 21.96it/s]

 29%|██▉       | 29354/100629 [23:17<53:25, 22.24it/s]

 29%|██▉       | 29357/100629 [23:17<58:17, 20.38it/s]

 29%|██▉       | 29360/100629 [23:17<55:25, 21.43it/s]

 29%|██▉       | 29363/100629 [23:17<1:02:51, 18.89it/s]

 29%|██▉       | 29366/100629 [23:18<1:06:22, 17.89it/s]

 29%|██▉       | 29369/100629 [23:18<1:04:27, 18.43it/s]

 29%|██▉       | 29371/100629 [23:18<1:09:35, 17.07it/s]

 29%|██▉       | 29374/100629 [23:18<1:10:34, 16.83it/s]

 29%|██▉       | 29379/100629 [23:18<51:25, 23.10it/s]

 29%|██▉       | 29382/100629 [23:18<48:31, 24.47it/s]

 29%|██▉       | 29387/100629 [23:18<42:29, 27.94it/s]

 29%|██▉       | 29390/100629 [23:19<42:41, 27.82it/s]

 29%|██▉       | 29395/100629 [23:19<37:20, 31.79it/s]

 29%|██▉       | 29399/100629 [23:19<36:14, 32.76it/s]

 29%|██▉       | 29403/100629 [23:19<38:40, 30.70it/s]

 29%|██▉       | 29407/100629 [23:19<41:20, 28.71it/s]

 29%|██▉       | 29410/100629 [23:19<43:56, 27.02it/s]

 29%|██▉       | 29415/100629 [23:19<38:33, 30.78it/s]

 29%|██▉       | 29421/100629 [23:19<31:57, 37.14it/s]

 29%|██▉       | 29425/100629 [23:20<35:22, 33.54it/s]

 29%|██▉       | 29429/100629 [23:20<41:16, 28.75it/s]

 29%|██▉       | 29433/100629 [23:20<43:13, 27.46it/s]

 29%|██▉       | 29436/100629 [23:20<44:31, 26.65it/s]

 29%|██▉       | 29440/100629 [23:20<43:29, 27.28it/s]

 29%|██▉       | 29444/100629 [23:20<39:17, 30.20it/s]

 29%|██▉       | 29448/100629 [23:20<44:50, 26.46it/s]

 29%|██▉       | 29451/100629 [23:21<45:02, 26.33it/s]

 29%|██▉       | 29454/100629 [23:21<49:18, 24.06it/s]

 29%|██▉       | 29457/100629 [23:21<50:46, 23.36it/s]

 29%|██▉       | 29460/100629 [23:21<1:01:50, 19.18it/s]

 29%|██▉       | 29463/100629 [23:21<1:02:02, 19.12it/s]

 29%|██▉       | 29466/100629 [23:21<57:27, 20.64it/s]

 29%|██▉       | 29469/100629 [23:22<59:57, 19.78it/s]

 29%|██▉       | 29474/100629 [23:22<45:36, 26.01it/s]

 29%|██▉       | 29477/100629 [23:22<50:56, 23.28it/s]

 29%|██▉       | 29480/100629 [23:22<1:11:06, 16.68it/s]

 29%|██▉       | 29486/100629 [23:22<53:29, 22.17it/s]

 29%|██▉       | 29489/100629 [23:22<50:34, 23.44it/s]

 29%|██▉       | 29492/100629 [23:23<50:08, 23.64it/s]

 29%|██▉       | 29496/100629 [23:23<49:53, 23.76it/s]

 29%|██▉       | 29499/100629 [23:23<51:09, 23.17it/s]

 29%|██▉       | 29502/100629 [23:23<52:47, 22.45it/s]

 29%|██▉       | 29505/100629 [23:23<51:39, 22.94it/s]

 29%|██▉       | 29508/100629 [23:23<53:01, 22.36it/s]

 29%|██▉       | 29511/100629 [23:23<50:10, 23.63it/s]

 29%|██▉       | 29514/100629 [23:24<57:48, 20.50it/s]

 29%|██▉       | 29517/100629 [23:24<58:47, 20.16it/s]

 29%|██▉       | 29521/100629 [23:24<51:32, 23.00it/s]

 29%|██▉       | 29524/100629 [23:24<48:59, 24.19it/s]

 29%|██▉       | 29529/100629 [23:24<41:05, 28.83it/s]

 29%|██▉       | 29532/100629 [23:24<44:46, 26.47it/s]

 29%|██▉       | 29535/100629 [23:24<52:35, 22.53it/s]

 29%|██▉       | 29538/100629 [23:24<50:37, 23.41it/s]

 29%|██▉       | 29541/100629 [23:25<48:34, 24.39it/s]

 29%|██▉       | 29544/100629 [23:25<56:15, 21.06it/s]

 29%|██▉       | 29547/100629 [23:25<56:38, 20.92it/s]

 29%|██▉       | 29550/100629 [23:25<51:50, 22.85it/s]

 29%|██▉       | 29555/100629 [23:25<43:40, 27.12it/s]

 29%|██▉       | 29559/100629 [23:25<47:17, 25.05it/s]

 29%|██▉       | 29562/100629 [23:25<48:21, 24.49it/s]

 29%|██▉       | 29565/100629 [23:26<50:39, 23.38it/s]

 29%|██▉       | 29568/100629 [23:26<1:02:14, 19.03it/s]

 29%|██▉       | 29571/100629 [23:26<1:06:15, 17.87it/s]

 29%|██▉       | 29574/100629 [23:26<1:00:36, 19.54it/s]

 29%|██▉       | 29577/100629 [23:26<55:59, 21.15it/s]

 29%|██▉       | 29580/100629 [23:26<58:53, 20.11it/s]

 29%|██▉       | 29583/100629 [23:27<59:59, 19.74it/s]

 29%|██▉       | 29586/100629 [23:27<1:12:17, 16.38it/s]

 29%|██▉       | 29589/100629 [23:27<1:04:52, 18.25it/s]

 29%|██▉       | 29592/100629 [23:27<1:00:52, 19.45it/s]

 29%|██▉       | 29595/100629 [23:27<54:36, 21.68it/s]

 29%|██▉       | 29598/100629 [23:27<59:18, 19.96it/s]

 29%|██▉       | 29602/100629 [23:28<49:49, 23.76it/s]

 29%|██▉       | 29605/100629 [23:28<56:30, 20.95it/s]

 29%|██▉       | 29608/100629 [23:28<52:33, 22.52it/s]

 29%|██▉       | 29611/100629 [23:28<51:29, 22.98it/s]

 29%|██▉       | 29614/100629 [23:28<1:00:02, 19.71it/s]

 29%|██▉       | 29617/100629 [23:28<1:05:57, 17.94it/s]

 29%|██▉       | 29619/100629 [23:28<1:05:50, 17.97it/s]

 29%|██▉       | 29622/100629 [23:29<58:23, 20.27it/s]

 29%|██▉       | 29625/100629 [23:29<57:33, 20.56it/s]

 29%|██▉       | 29628/100629 [23:29<59:57, 19.73it/s]

 29%|██▉       | 29631/100629 [23:29<56:11, 21.06it/s]

 29%|██▉       | 29634/100629 [23:29<1:03:15, 18.71it/s]

 29%|██▉       | 29637/100629 [23:29<57:02, 20.74it/s]

 29%|██▉       | 29640/100629 [23:29<59:26, 19.90it/s]

 29%|██▉       | 29644/100629 [23:30<54:09, 21.85it/s]

 29%|██▉       | 29647/100629 [23:30<54:03, 21.88it/s]

 29%|██▉       | 29650/100629 [23:30<1:01:10, 19.34it/s]

 29%|██▉       | 29654/100629 [23:30<51:08, 23.13it/s]

 29%|██▉       | 29657/100629 [23:30<50:30, 23.42it/s]

 29%|██▉       | 29660/100629 [23:30<49:18, 23.99it/s]

 29%|██▉       | 29664/100629 [23:30<46:44, 25.30it/s]

 29%|██▉       | 29667/100629 [23:31<54:42, 21.62it/s]

 29%|██▉       | 29670/100629 [23:31<54:55, 21.53it/s]

 29%|██▉       | 29673/100629 [23:31<57:51, 20.44it/s]

 29%|██▉       | 29676/100629 [23:31<54:26, 21.72it/s]

 29%|██▉       | 29679/100629 [23:31<51:16, 23.06it/s]

 29%|██▉       | 29682/100629 [23:31<59:29, 19.87it/s]

 29%|██▉       | 29685/100629 [23:31<54:21, 21.75it/s]

 30%|██▉       | 29688/100629 [23:32<51:39, 22.89it/s]

 30%|██▉       | 29692/100629 [23:32<45:31, 25.97it/s]

 30%|██▉       | 29695/100629 [23:32<44:19, 26.67it/s]

 30%|██▉       | 29698/100629 [23:32<49:55, 23.68it/s]

 30%|██▉       | 29701/100629 [23:32<51:53, 22.78it/s]

 30%|██▉       | 29704/100629 [23:32<48:24, 24.42it/s]

 30%|██▉       | 29707/100629 [23:32<48:11, 24.53it/s]

 30%|██▉       | 29711/100629 [23:32<43:56, 26.90it/s]

 30%|██▉       | 29714/100629 [23:33<42:45, 27.64it/s]

 30%|██▉       | 29717/100629 [23:33<44:47, 26.38it/s]

 30%|██▉       | 29721/100629 [23:33<40:01, 29.52it/s]

 30%|██▉       | 29725/100629 [23:33<43:05, 27.42it/s]

 30%|██▉       | 29728/100629 [23:33<47:36, 24.82it/s]

 30%|██▉       | 29731/100629 [23:33<50:57, 23.19it/s]

 30%|██▉       | 29736/100629 [23:33<45:42, 25.85it/s]

 30%|██▉       | 29739/100629 [23:34<48:36, 24.30it/s]

 30%|██▉       | 29742/100629 [23:34<58:06, 20.33it/s]

 30%|██▉       | 29745/100629 [23:34<54:40, 21.61it/s]

 30%|██▉       | 29748/100629 [23:34<50:28, 23.41it/s]

 30%|██▉       | 29752/100629 [23:34<1:01:24, 19.23it/s]

 30%|██▉       | 29755/100629 [23:35<1:07:41, 17.45it/s]

 30%|██▉       | 29760/100629 [23:35<51:06, 23.11it/s]

 30%|██▉       | 29764/100629 [23:35<44:43, 26.40it/s]

 30%|██▉       | 29768/100629 [23:35<50:14, 23.51it/s]

 30%|██▉       | 29771/100629 [23:35<47:39, 24.78it/s]

 30%|██▉       | 29775/100629 [23:35<44:38, 26.45it/s]

 30%|██▉       | 29778/100629 [23:35<49:38, 23.79it/s]

 30%|██▉       | 29781/100629 [23:35<47:19, 24.95it/s]

 30%|██▉       | 29784/100629 [23:36<48:36, 24.29it/s]

 30%|██▉       | 29787/100629 [23:36<47:54, 24.65it/s]

 30%|██▉       | 29790/100629 [23:36<48:17, 24.45it/s]

 30%|██▉       | 29793/100629 [23:36<49:16, 23.96it/s]

 30%|██▉       | 29796/100629 [23:36<51:30, 22.92it/s]

 30%|██▉       | 29799/100629 [23:36<55:10, 21.39it/s]

 30%|██▉       | 29802/100629 [23:36<53:00, 22.27it/s]

 30%|██▉       | 29805/100629 [23:37<1:00:35, 19.48it/s]

 30%|██▉       | 29808/100629 [23:37<1:14:46, 15.78it/s]

 30%|██▉       | 29810/100629 [23:37<1:20:16, 14.70it/s]

 30%|██▉       | 29812/100629 [23:37<1:26:49, 13.59it/s]

 30%|██▉       | 29815/100629 [23:37<1:24:34, 13.95it/s]

 30%|██▉       | 29818/100629 [23:38<1:16:34, 15.41it/s]

 30%|██▉       | 29822/100629 [23:38<58:59, 20.01it/s]

 30%|██▉       | 29825/100629 [23:38<54:42, 21.57it/s]

 30%|██▉       | 29828/100629 [23:38<1:03:01, 18.72it/s]

 30%|██▉       | 29831/100629 [23:38<1:01:39, 19.14it/s]

 30%|██▉       | 29834/100629 [23:38<58:09, 20.29it/s]

 30%|██▉       | 29837/100629 [23:38<1:02:52, 18.77it/s]

 30%|██▉       | 29839/100629 [23:39<1:02:44, 18.81it/s]

 30%|██▉       | 29842/100629 [23:39<57:05, 20.66it/s]

 30%|██▉       | 29845/100629 [23:39<1:15:51, 15.55it/s]

 30%|██▉       | 29848/100629 [23:39<1:08:42, 17.17it/s]

 30%|██▉       | 29850/100629 [23:39<1:06:56, 17.62it/s]

 30%|██▉       | 29852/100629 [23:39<1:21:18, 14.51it/s]

 30%|██▉       | 29854/100629 [23:40<1:47:04, 11.02it/s]

 30%|██▉       | 29856/100629 [23:40<1:37:30, 12.10it/s]

 30%|██▉       | 29858/100629 [23:40<1:28:45, 13.29it/s]

 30%|██▉       | 29862/100629 [23:40<1:06:20, 17.78it/s]

 30%|██▉       | 29865/100629 [23:40<1:01:10, 19.28it/s]

 30%|██▉       | 29868/100629 [23:40<55:12, 21.36it/s]

 30%|██▉       | 29871/100629 [23:40<58:03, 20.32it/s]

 30%|██▉       | 29874/100629 [23:41<56:11, 20.99it/s]

 30%|██▉       | 29878/100629 [23:41<49:20, 23.90it/s]

 30%|██▉       | 29881/100629 [23:41<55:59, 21.06it/s]

 30%|██▉       | 29884/100629 [23:41<57:05, 20.65it/s]

 30%|██▉       | 29888/100629 [23:41<47:49, 24.65it/s]

 30%|██▉       | 29891/100629 [23:41<55:51, 21.10it/s]

 30%|██▉       | 29894/100629 [23:41<53:34, 22.01it/s]

 30%|██▉       | 29897/100629 [23:42<53:45, 21.93it/s]

 30%|██▉       | 29900/100629 [23:42<58:00, 20.32it/s]

 30%|██▉       | 29903/100629 [23:42<56:22, 20.91it/s]

 30%|██▉       | 29907/100629 [23:42<51:03, 23.09it/s]

 30%|██▉       | 29910/100629 [23:42<50:27, 23.36it/s]

 30%|██▉       | 29913/100629 [23:42<54:35, 21.59it/s]

 30%|██▉       | 29916/100629 [23:42<50:47, 23.21it/s]

 30%|██▉       | 29919/100629 [23:43<53:39, 21.96it/s]

 30%|██▉       | 29923/100629 [23:43<45:03, 26.16it/s]

 30%|██▉       | 29926/100629 [23:43<48:07, 24.48it/s]

 30%|██▉       | 29929/100629 [23:43<50:42, 23.24it/s]

 30%|██▉       | 29932/100629 [23:43<1:15:38, 15.58it/s]

 30%|██▉       | 29934/100629 [23:44<1:42:35, 11.49it/s]

 30%|██▉       | 29937/100629 [23:44<1:25:25, 13.79it/s]

 30%|██▉       | 29940/100629 [23:44<1:11:10, 16.55it/s]

 30%|██▉       | 29943/100629 [23:44<1:03:57, 18.42it/s]

 30%|██▉       | 29947/100629 [23:44<53:44, 21.92it/s]

 30%|██▉       | 29950/100629 [23:44<1:00:50, 19.36it/s]

 30%|██▉       | 29953/100629 [23:44<55:30, 21.22it/s]

 30%|██▉       | 29957/100629 [23:45<46:34, 25.29it/s]

 30%|██▉       | 29960/100629 [23:45<45:55, 25.65it/s]

 30%|██▉       | 29963/100629 [23:45<56:42, 20.77it/s]

 30%|██▉       | 29966/100629 [23:45<52:59, 22.22it/s]

 30%|██▉       | 29969/100629 [23:45<54:44, 21.51it/s]

 30%|██▉       | 29972/100629 [23:45<50:22, 23.37it/s]

 30%|██▉       | 29975/100629 [23:45<47:10, 24.96it/s]

 30%|██▉       | 29978/100629 [23:45<45:01, 26.15it/s]

 30%|██▉       | 29981/100629 [23:46<46:42, 25.21it/s]

 30%|██▉       | 29984/100629 [23:46<49:53, 23.60it/s]

 30%|██▉       | 29987/100629 [23:46<53:40, 21.94it/s]

 30%|██▉       | 29990/100629 [23:46<56:39, 20.78it/s]

 30%|██▉       | 29993/100629 [23:46<58:13, 20.22it/s]

 30%|██▉       | 29996/100629 [23:46<1:01:34, 19.12it/s]

 30%|██▉       | 29998/100629 [23:47<1:04:36, 18.22it/s]

 30%|██▉       | 30000/100629 [23:47<1:07:21, 17.47it/s]

 30%|██▉       | 30003/100629 [23:47<1:05:53, 17.86it/s]

 30%|██▉       | 30005/100629 [23:47<1:05:09, 18.06it/s]

 30%|██▉       | 30009/100629 [23:47<52:03, 22.61it/s]

 30%|██▉       | 30012/100629 [23:47<55:36, 21.17it/s]

 30%|██▉       | 30015/100629 [23:47<51:15, 22.96it/s]

 30%|██▉       | 30018/100629 [23:47<50:42, 23.21it/s]

 30%|██▉       | 30021/100629 [23:48<51:14, 22.96it/s]

 30%|██▉       | 30025/100629 [23:48<44:42, 26.32it/s]

 30%|██▉       | 30028/100629 [23:48<45:21, 25.94it/s]

 30%|██▉       | 30031/100629 [23:48<51:30, 22.85it/s]

 30%|██▉       | 30035/100629 [23:48<45:24, 25.91it/s]

 30%|██▉       | 30038/100629 [23:48<55:59, 21.01it/s]

 30%|██▉       | 30041/100629 [23:48<53:23, 22.04it/s]

 30%|██▉       | 30045/100629 [23:49<49:04, 23.97it/s]

 30%|██▉       | 30048/100629 [23:49<47:33, 24.73it/s]

 30%|██▉       | 30051/100629 [23:49<47:22, 24.83it/s]

 30%|██▉       | 30054/100629 [23:49<52:15, 22.51it/s]

 30%|██▉       | 30059/100629 [23:49<41:26, 28.39it/s]

 30%|██▉       | 30063/100629 [23:49<41:50, 28.11it/s]

 30%|██▉       | 30066/100629 [23:49<43:42, 26.90it/s]

 30%|██▉       | 30069/100629 [23:50<50:23, 23.34it/s]

 30%|██▉       | 30072/100629 [23:50<49:12, 23.90it/s]

 30%|██▉       | 30076/100629 [23:50<45:22, 25.91it/s]

 30%|██▉       | 30079/100629 [23:50<49:38, 23.69it/s]

 30%|██▉       | 30082/100629 [23:50<50:23, 23.33it/s]

 30%|██▉       | 30085/100629 [23:50<1:15:19, 15.61it/s]

 30%|██▉       | 30089/100629 [23:51<59:23, 19.80it/s]

 30%|██▉       | 30092/100629 [23:51<1:03:28, 18.52it/s]

 30%|██▉       | 30095/100629 [23:51<1:04:48, 18.14it/s]

 30%|██▉       | 30099/100629 [23:51<1:02:04, 18.94it/s]

 30%|██▉       | 30102/100629 [23:51<59:08, 19.87it/s]

 30%|██▉       | 30105/100629 [23:51<1:00:26, 19.45it/s]

 30%|██▉       | 30108/100629 [23:52<1:00:55, 19.29it/s]

 30%|██▉       | 30111/100629 [23:52<1:01:39, 19.06it/s]

 30%|██▉       | 30114/100629 [23:52<55:06, 21.32it/s]

 30%|██▉       | 30118/100629 [23:52<48:41, 24.14it/s]

 30%|██▉       | 30121/100629 [23:52<53:12, 22.08it/s]

 30%|██▉       | 30124/100629 [23:52<53:26, 21.99it/s]

 30%|██▉       | 30127/100629 [23:52<1:04:00, 18.36it/s]

 30%|██▉       | 30129/100629 [23:53<1:03:22, 18.54it/s]

 30%|██▉       | 30133/100629 [23:53<55:03, 21.34it/s]

 30%|██▉       | 30136/100629 [23:53<50:32, 23.25it/s]

 30%|██▉       | 30139/100629 [23:53<47:38, 24.66it/s]

 30%|██▉       | 30142/100629 [23:53<48:08, 24.40it/s]

 30%|██▉       | 30145/100629 [23:53<51:12, 22.94it/s]

 30%|██▉       | 30148/100629 [23:53<1:01:16, 19.17it/s]

 30%|██▉       | 30152/100629 [23:54<51:47, 22.68it/s]

 30%|██▉       | 30156/100629 [23:54<48:36, 24.16it/s]

 30%|██▉       | 30159/100629 [23:54<53:16, 22.05it/s]

 30%|██▉       | 30162/100629 [23:54<53:08, 22.10it/s]

 30%|██▉       | 30165/100629 [23:54<1:00:14, 19.49it/s]

 30%|██▉       | 30169/100629 [23:54<54:38, 21.49it/s]

 30%|██▉       | 30172/100629 [23:55<1:10:53, 16.56it/s]

 30%|██▉       | 30174/100629 [23:55<1:15:49, 15.49it/s]

 30%|██▉       | 30176/100629 [23:55<1:20:35, 14.57it/s]

 30%|██▉       | 30180/100629 [23:55<1:00:35, 19.38it/s]

 30%|██▉       | 30183/100629 [23:55<55:09, 21.29it/s]

 30%|██▉       | 30186/100629 [23:55<52:13, 22.48it/s]

 30%|███       | 30189/100629 [23:55<1:00:26, 19.42it/s]

 30%|███       | 30192/100629 [23:56<59:53, 19.60it/s]

 30%|███       | 30195/100629 [23:56<58:28, 20.07it/s]

 30%|███       | 30198/100629 [23:56<1:06:46, 17.58it/s]

 30%|███       | 30200/100629 [23:56<1:06:21, 17.69it/s]

 30%|███       | 30203/100629 [23:56<58:17, 20.14it/s]

 30%|███       | 30206/100629 [23:57<1:19:56, 14.68it/s]

 30%|███       | 30208/100629 [23:57<1:16:02, 15.43it/s]

 30%|███       | 30211/100629 [23:57<1:09:36, 16.86it/s]

 30%|███       | 30214/100629 [23:57<1:04:27, 18.20it/s]

 30%|███       | 30216/100629 [23:57<1:04:31, 18.19it/s]

 30%|███       | 30219/100629 [23:57<1:00:03, 19.54it/s]

 30%|███       | 30222/100629 [23:57<55:52, 21.00it/s]

 30%|███       | 30225/100629 [23:57<52:25, 22.38it/s]

 30%|███       | 30228/100629 [23:57<49:01, 23.94it/s]

 30%|███       | 30231/100629 [23:58<48:16, 24.31it/s]

 30%|███       | 30235/100629 [23:58<43:50, 26.76it/s]

 30%|███       | 30238/100629 [23:58<52:44, 22.25it/s]

 30%|███       | 30241/100629 [23:58<1:00:50, 19.28it/s]

 30%|███       | 30244/100629 [23:58<55:07, 21.28it/s]

 30%|███       | 30247/100629 [23:58<57:27, 20.42it/s]

 30%|███       | 30251/100629 [23:59<49:15, 23.81it/s]

 30%|███       | 30254/100629 [23:59<48:40, 24.10it/s]

 30%|███       | 30257/100629 [23:59<47:36, 24.64it/s]

 30%|███       | 30260/100629 [23:59<51:05, 22.95it/s]

 30%|███       | 30264/100629 [23:59<45:47, 25.61it/s]

 30%|███       | 30267/100629 [23:59<50:34, 23.18it/s]

 30%|███       | 30270/100629 [23:59<1:03:34, 18.44it/s]

 30%|███       | 30273/100629 [24:00<1:02:17, 18.83it/s]

 30%|███       | 30276/100629 [24:00<55:37, 21.08it/s]

 30%|███       | 30279/100629 [24:00<1:05:03, 18.02it/s]

 30%|███       | 30282/100629 [24:00<1:10:29, 16.63it/s]

 30%|███       | 30285/100629 [24:00<1:08:52, 17.02it/s]

 30%|███       | 30287/100629 [24:00<1:07:08, 17.46it/s]

 30%|███       | 30290/100629 [24:01<1:01:19, 19.12it/s]

 30%|███       | 30293/100629 [24:01<1:09:06, 16.96it/s]

 30%|███       | 30295/100629 [24:01<1:08:33, 17.10it/s]

 30%|███       | 30297/100629 [24:01<1:25:57, 13.64it/s]

 30%|███       | 30299/100629 [24:01<1:22:03, 14.29it/s]

 30%|███       | 30302/100629 [24:01<1:20:29, 14.56it/s]

 30%|███       | 30305/100629 [24:02<1:07:37, 17.33it/s]

 30%|███       | 30308/100629 [24:02<59:43, 19.62it/s]

 30%|███       | 30312/100629 [24:02<48:35, 24.12it/s]

 30%|███       | 30315/100629 [24:02<57:35, 20.35it/s]

 30%|███       | 30318/100629 [24:02<52:43, 22.22it/s]

 30%|███       | 30322/100629 [24:02<45:30, 25.75it/s]

 30%|███       | 30327/100629 [24:02<41:03, 28.54it/s]

 30%|███       | 30330/100629 [24:02<43:51, 26.71it/s]

 30%|███       | 30333/100629 [24:03<46:05, 25.42it/s]

 30%|███       | 30337/100629 [24:03<41:41, 28.10it/s]

 30%|███       | 30341/100629 [24:03<41:46, 28.04it/s]

 30%|███       | 30344/100629 [24:03<47:17, 24.77it/s]

 30%|███       | 30347/100629 [24:03<45:11, 25.92it/s]

 30%|███       | 30351/100629 [24:03<43:30, 26.92it/s]

 30%|███       | 30354/100629 [24:04<1:05:09, 17.98it/s]

 30%|███       | 30357/100629 [24:04<1:08:33, 17.08it/s]

 30%|███       | 30360/100629 [24:04<1:01:36, 19.01it/s]

 30%|███       | 30363/100629 [24:04<58:47, 19.92it/s]

 30%|███       | 30366/100629 [24:04<1:02:39, 18.69it/s]

 30%|███       | 30369/100629 [24:04<1:07:55, 17.24it/s]

 30%|███       | 30372/100629 [24:04<1:00:44, 19.28it/s]

 30%|███       | 30375/100629 [24:05<59:57, 19.53it/s]

 30%|███       | 30378/100629 [24:05<57:17, 20.44it/s]

 30%|███       | 30381/100629 [24:05<1:00:40, 19.30it/s]

 30%|███       | 30384/100629 [24:05<58:05, 20.15it/s]

 30%|███       | 30387/100629 [24:05<1:11:30, 16.37it/s]

 30%|███       | 30389/100629 [24:05<1:11:27, 16.38it/s]

 30%|███       | 30391/100629 [24:06<1:09:43, 16.79it/s]

 30%|███       | 30393/100629 [24:06<1:27:15, 13.41it/s]

 30%|███       | 30396/100629 [24:06<1:13:33, 15.91it/s]

 30%|███       | 30398/100629 [24:06<1:19:18, 14.76it/s]

 30%|███       | 30400/100629 [24:06<1:18:13, 14.96it/s]

 30%|███       | 30402/100629 [24:06<1:13:18, 15.97it/s]

 30%|███       | 30405/100629 [24:06<1:02:16, 18.80it/s]

 30%|███       | 30408/100629 [24:07<1:00:13, 19.43it/s]

 30%|███       | 30411/100629 [24:07<1:07:15, 17.40it/s]

 30%|███       | 30414/100629 [24:07<59:01, 19.83it/s]

 30%|███       | 30417/100629 [24:07<1:13:18, 15.96it/s]

 30%|███       | 30420/100629 [24:07<1:08:56, 16.97it/s]

 30%|███       | 30422/100629 [24:07<1:11:20, 16.40it/s]

 30%|███       | 30425/100629 [24:08<1:06:34, 17.58it/s]

 30%|███       | 30427/100629 [24:08<1:08:07, 17.18it/s]

 30%|███       | 30430/100629 [24:08<58:21, 20.05it/s]

 30%|███       | 30433/100629 [24:08<57:01, 20.52it/s]

 30%|███       | 30436/100629 [24:08<53:14, 21.97it/s]

 30%|███       | 30439/100629 [24:08<52:08, 22.44it/s]

 30%|███       | 30443/100629 [24:08<50:20, 23.23it/s]

 30%|███       | 30446/100629 [24:08<47:45, 24.50it/s]

 30%|███       | 30449/100629 [24:09<48:05, 24.32it/s]

 30%|███       | 30452/100629 [24:09<1:01:52, 18.91it/s]

 30%|███       | 30455/100629 [24:09<1:01:55, 18.89it/s]

 30%|███       | 30459/100629 [24:09<56:14, 20.79it/s]

 30%|███       | 30462/100629 [24:09<1:00:24, 19.36it/s]

 30%|███       | 30465/100629 [24:09<56:52, 20.56it/s]

 30%|███       | 30468/100629 [24:10<57:40, 20.28it/s]

 30%|███       | 30471/100629 [24:10<1:00:00, 19.49it/s]

 30%|███       | 30474/100629 [24:10<54:06, 21.61it/s]

 30%|███       | 30478/100629 [24:10<46:46, 25.00it/s]

 30%|███       | 30481/100629 [24:10<50:50, 23.00it/s]

 30%|███       | 30484/100629 [24:10<49:16, 23.73it/s]

 30%|███       | 30487/100629 [24:10<49:42, 23.52it/s]

 30%|███       | 30490/100629 [24:11<46:49, 24.96it/s]

 30%|███       | 30494/100629 [24:11<43:51, 26.65it/s]

 30%|███       | 30497/100629 [24:11<45:58, 25.42it/s]

 30%|███       | 30500/100629 [24:11<45:34, 25.65it/s]

 30%|███       | 30504/100629 [24:11<42:56, 27.22it/s]

 30%|███       | 30507/100629 [24:11<49:02, 23.83it/s]

 30%|███       | 30510/100629 [24:11<57:14, 20.42it/s]

 30%|███       | 30513/100629 [24:12<55:27, 21.07it/s]

 30%|███       | 30517/100629 [24:12<55:27, 21.07it/s]

 30%|███       | 30520/100629 [24:12<57:08, 20.45it/s]

 30%|███       | 30524/100629 [24:12<48:12, 24.24it/s]

 30%|███       | 30527/100629 [24:12<54:17, 21.52it/s]

 30%|███       | 30530/100629 [24:12<51:07, 22.85it/s]

 30%|███       | 30533/100629 [24:12<51:48, 22.55it/s]

 30%|███       | 30536/100629 [24:13<50:05, 23.32it/s]

 30%|███       | 30539/100629 [24:13<50:47, 23.00it/s]

 30%|███       | 30542/100629 [24:13<54:40, 21.37it/s]

 30%|███       | 30545/100629 [24:13<51:25, 22.71it/s]

 30%|███       | 30549/100629 [24:13<46:43, 24.99it/s]

 30%|███       | 30552/100629 [24:13<1:10:29, 16.57it/s]

 30%|███       | 30555/100629 [24:14<1:01:55, 18.86it/s]

 30%|███       | 30559/100629 [24:14<53:15, 21.93it/s]

 30%|███       | 30562/100629 [24:14<50:32, 23.10it/s]

 30%|███       | 30565/100629 [24:14<48:15, 24.20it/s]

 30%|███       | 30569/100629 [24:14<45:48, 25.49it/s]

 30%|███       | 30572/100629 [24:14<47:14, 24.71it/s]

 30%|███       | 30575/100629 [24:14<53:22, 21.88it/s]

 30%|███       | 30578/100629 [24:14<54:24, 21.46it/s]

 30%|███       | 30581/100629 [24:15<50:01, 23.34it/s]

 30%|███       | 30584/100629 [24:15<53:15, 21.92it/s]

 30%|███       | 30587/100629 [24:15<49:29, 23.59it/s]

 30%|███       | 30592/100629 [24:15<39:58, 29.21it/s]

 30%|███       | 30596/100629 [24:15<42:02, 27.76it/s]

 30%|███       | 30599/100629 [24:15<51:30, 22.66it/s]

 30%|███       | 30602/100629 [24:15<52:58, 22.03it/s]

 30%|███       | 30605/100629 [24:16<53:41, 21.74it/s]

 30%|███       | 30608/100629 [24:16<56:42, 20.58it/s]

 30%|███       | 30613/100629 [24:16<44:59, 25.93it/s]

 30%|███       | 30616/100629 [24:16<53:49, 21.68it/s]

 30%|███       | 30620/100629 [24:16<55:33, 21.00it/s]

 30%|███       | 30624/100629 [24:16<52:05, 22.40it/s]

 30%|███       | 30627/100629 [24:17<50:40, 23.02it/s]

 30%|███       | 30630/100629 [24:17<1:14:30, 15.66it/s]

 30%|███       | 30634/100629 [24:17<1:04:04, 18.21it/s]

 30%|███       | 30637/100629 [24:17<1:08:03, 17.14it/s]

 30%|███       | 30640/100629 [24:17<1:05:50, 17.71it/s]

 30%|███       | 30642/100629 [24:18<1:07:19, 17.33it/s]

 30%|███       | 30644/100629 [24:18<1:05:41, 17.76it/s]

 30%|███       | 30646/100629 [24:18<1:11:11, 16.38it/s]

 30%|███       | 30649/100629 [24:18<1:02:12, 18.75it/s]

 30%|███       | 30652/100629 [24:18<57:34, 20.26it/s]

 30%|███       | 30655/100629 [24:18<55:18, 21.08it/s]

 30%|███       | 30658/100629 [24:18<52:37, 22.16it/s]

 30%|███       | 30662/100629 [24:18<49:04, 23.76it/s]

 30%|███       | 30666/100629 [24:19<49:56, 23.35it/s]

 30%|███       | 30669/100629 [24:19<58:43, 19.86it/s]

 30%|███       | 30672/100629 [24:19<53:32, 21.78it/s]

 30%|███       | 30675/100629 [24:19<54:02, 21.58it/s]

 30%|███       | 30679/100629 [24:19<45:39, 25.53it/s]

 30%|███       | 30682/100629 [24:19<50:49, 22.94it/s]

 30%|███       | 30685/100629 [24:19<53:42, 21.70it/s]

 30%|███       | 30688/100629 [24:20<53:23, 21.83it/s]

 30%|███       | 30691/100629 [24:20<53:54, 21.62it/s]

 31%|███       | 30694/100629 [24:20<1:06:06, 17.63it/s]

 31%|███       | 30696/100629 [24:20<1:05:49, 17.71it/s]

 31%|███       | 30700/100629 [24:20<52:39, 22.13it/s]

 31%|███       | 30703/100629 [24:20<51:57, 22.43it/s]

 31%|███       | 30706/100629 [24:20<48:15, 24.15it/s]

 31%|███       | 30709/100629 [24:21<48:13, 24.16it/s]

 31%|███       | 30712/100629 [24:21<51:50, 22.48it/s]

 31%|███       | 30715/100629 [24:21<1:00:04, 19.40it/s]

 31%|███       | 30719/100629 [24:21<52:43, 22.10it/s]

 31%|███       | 30722/100629 [24:21<51:31, 22.61it/s]

 31%|███       | 30726/100629 [24:21<44:57, 25.92it/s]

 31%|███       | 30730/100629 [24:21<41:23, 28.15it/s]

 31%|███       | 30734/100629 [24:22<37:37, 30.96it/s]

 31%|███       | 30738/100629 [24:22<36:55, 31.54it/s]

 31%|███       | 30742/100629 [24:22<34:37, 33.64it/s]

 31%|███       | 30746/100629 [24:22<40:19, 28.88it/s]

 31%|███       | 30750/100629 [24:22<42:15, 27.56it/s]

 31%|███       | 30753/100629 [24:22<45:18, 25.71it/s]

 31%|███       | 30756/100629 [24:22<45:40, 25.50it/s]

 31%|███       | 30759/100629 [24:23<50:39, 22.98it/s]

 31%|███       | 30762/100629 [24:23<50:37, 23.00it/s]

 31%|███       | 30765/100629 [24:23<1:02:45, 18.55it/s]

 31%|███       | 30768/100629 [24:23<1:00:13, 19.33it/s]

 31%|███       | 30771/100629 [24:23<54:37, 21.31it/s]

 31%|███       | 30774/100629 [24:23<59:41, 19.50it/s]

 31%|███       | 30777/100629 [24:23<55:11, 21.09it/s]

 31%|███       | 30781/100629 [24:24<48:13, 24.14it/s]

 31%|███       | 30784/100629 [24:24<1:01:10, 19.03it/s]

 31%|███       | 30787/100629 [24:24<58:09, 20.01it/s]

 31%|███       | 30791/100629 [24:24<55:26, 21.00it/s]

 31%|███       | 30794/100629 [24:24<53:36, 21.71it/s]

 31%|███       | 30798/100629 [24:24<47:14, 24.63it/s]

 31%|███       | 30801/100629 [24:25<51:12, 22.73it/s]

 31%|███       | 30804/100629 [24:25<1:11:14, 16.33it/s]

 31%|███       | 30810/100629 [24:25<49:31, 23.50it/s]

 31%|███       | 30813/100629 [24:25<54:46, 21.24it/s]

 31%|███       | 30816/100629 [24:25<54:16, 21.44it/s]

 31%|███       | 30819/100629 [24:25<1:00:20, 19.28it/s]

 31%|███       | 30822/100629 [24:26<56:56, 20.43it/s]

 31%|███       | 30825/100629 [24:26<55:07, 21.10it/s]

 31%|███       | 30828/100629 [24:26<52:35, 22.12it/s]

 31%|███       | 30831/100629 [24:26<49:11, 23.65it/s]

 31%|███       | 30835/100629 [24:26<43:09, 26.95it/s]

 31%|███       | 30838/100629 [24:26<45:16, 25.69it/s]

 31%|███       | 30841/100629 [24:26<53:46, 21.63it/s]

 31%|███       | 30844/100629 [24:26<50:07, 23.21it/s]

 31%|███       | 30847/100629 [24:27<55:49, 20.83it/s]

 31%|███       | 30850/100629 [24:27<59:07, 19.67it/s]

 31%|███       | 30853/100629 [24:27<1:00:26, 19.24it/s]

 31%|███       | 30856/100629 [24:27<1:01:15, 18.99it/s]

 31%|███       | 30858/100629 [24:27<1:09:19, 16.78it/s]

 31%|███       | 30862/100629 [24:27<58:03, 20.03it/s]

 31%|███       | 30865/100629 [24:28<54:42, 21.25it/s]

 31%|███       | 30868/100629 [24:28<1:07:09, 17.31it/s]

 31%|███       | 30870/100629 [24:28<1:07:38, 17.19it/s]

 31%|███       | 30872/100629 [24:28<1:06:16, 17.54it/s]

 31%|███       | 30877/100629 [24:28<51:28, 22.58it/s]

 31%|███       | 30880/100629 [24:28<55:17, 21.02it/s]

 31%|███       | 30883/100629 [24:28<50:36, 22.97it/s]

 31%|███       | 30887/100629 [24:29<44:12, 26.29it/s]

 31%|███       | 30890/100629 [24:29<53:00, 21.92it/s]

 31%|███       | 30894/100629 [24:29<45:24, 25.59it/s]

 31%|███       | 30897/100629 [24:29<46:04, 25.23it/s]

 31%|███       | 30900/100629 [24:29<55:36, 20.90it/s]

 31%|███       | 30903/100629 [24:29<1:07:38, 17.18it/s]

 31%|███       | 30906/100629 [24:30<1:00:16, 19.28it/s]

 31%|███       | 30909/100629 [24:30<56:53, 20.43it/s]

 31%|███       | 30912/100629 [24:30<1:09:30, 16.72it/s]

 31%|███       | 30917/100629 [24:30<53:50, 21.58it/s]

 31%|███       | 30920/100629 [24:30<51:32, 22.54it/s]

 31%|███       | 30925/100629 [24:30<48:23, 24.00it/s]

 31%|███       | 30928/100629 [24:31<48:34, 23.92it/s]

 31%|███       | 30931/100629 [24:31<51:15, 22.67it/s]

 31%|███       | 30934/100629 [24:31<58:40, 19.80it/s]

 31%|███       | 30937/100629 [24:31<54:48, 21.19it/s]

 31%|███       | 30941/100629 [24:31<47:50, 24.28it/s]

 31%|███       | 30944/100629 [24:31<1:00:54, 19.07it/s]

 31%|███       | 30947/100629 [24:32<1:06:43, 17.40it/s]

 31%|███       | 30950/100629 [24:32<1:04:16, 18.07it/s]

 31%|███       | 30953/100629 [24:32<58:45, 19.76it/s]

 31%|███       | 30956/100629 [24:32<1:11:02, 16.34it/s]

 31%|███       | 30958/100629 [24:32<1:12:09, 16.09it/s]

 31%|███       | 30960/100629 [24:32<1:10:58, 16.36it/s]

 31%|███       | 30963/100629 [24:32<1:02:10, 18.68it/s]

 31%|███       | 30965/100629 [24:33<1:05:31, 17.72it/s]

 31%|███       | 30967/100629 [24:33<1:15:09, 15.45it/s]

 31%|███       | 30970/100629 [24:33<1:11:30, 16.24it/s]

 31%|███       | 30973/100629 [24:33<1:05:01, 17.86it/s]

 31%|███       | 30975/100629 [24:33<1:12:59, 15.91it/s]

 31%|███       | 30977/100629 [24:33<1:23:12, 13.95it/s]

 31%|███       | 30980/100629 [24:34<1:09:09, 16.79it/s]

 31%|███       | 30982/100629 [24:34<1:06:27, 17.47it/s]

 31%|███       | 30984/100629 [24:34<1:04:35, 17.97it/s]

 31%|███       | 30986/100629 [24:34<1:04:57, 17.87it/s]

 31%|███       | 30990/100629 [24:34<50:01, 23.20it/s]

 31%|███       | 30993/100629 [24:34<51:18, 22.62it/s]

 31%|███       | 30997/100629 [24:34<43:41, 26.56it/s]

 31%|███       | 31000/100629 [24:34<44:10, 26.27it/s]

 31%|███       | 31003/100629 [24:35<47:14, 24.57it/s]

 31%|███       | 31008/100629 [24:35<41:59, 27.63it/s]

 31%|███       | 31012/100629 [24:35<46:46, 24.81it/s]

 31%|███       | 31015/100629 [24:35<48:21, 24.00it/s]

 31%|███       | 31018/100629 [24:35<51:53, 22.36it/s]

 31%|███       | 31022/100629 [24:35<47:22, 24.49it/s]

 31%|███       | 31026/100629 [24:35<42:20, 27.39it/s]

 31%|███       | 31029/100629 [24:36<45:29, 25.50it/s]

 31%|███       | 31033/100629 [24:36<40:31, 28.62it/s]

 31%|███       | 31036/100629 [24:36<46:50, 24.77it/s]

 31%|███       | 31039/100629 [24:36<51:06, 22.69it/s]

 31%|███       | 31042/100629 [24:36<49:45, 23.31it/s]

 31%|███       | 31046/100629 [24:36<48:11, 24.06it/s]

 31%|███       | 31049/100629 [24:36<46:27, 24.96it/s]

 31%|███       | 31052/100629 [24:36<46:14, 25.08it/s]

 31%|███       | 31055/100629 [24:37<45:36, 25.42it/s]

 31%|███       | 31058/100629 [24:37<45:09, 25.68it/s]

 31%|███       | 31061/100629 [24:37<54:08, 21.41it/s]

 31%|███       | 31064/100629 [24:37<1:00:53, 19.04it/s]

 31%|███       | 31067/100629 [24:37<54:57, 21.09it/s]

 31%|███       | 31071/100629 [24:37<45:47, 25.32it/s]

 31%|███       | 31075/100629 [24:37<42:34, 27.23it/s]

 31%|███       | 31078/100629 [24:38<1:02:20, 18.59it/s]

 31%|███       | 31081/100629 [24:38<1:02:07, 18.66it/s]

 31%|███       | 31084/100629 [24:38<1:03:30, 18.25it/s]

 31%|███       | 31087/100629 [24:38<1:01:46, 18.76it/s]

 31%|███       | 31090/100629 [24:38<1:10:06, 16.53it/s]

 31%|███       | 31093/100629 [24:39<1:07:40, 17.13it/s]

 31%|███       | 31095/100629 [24:39<1:09:10, 16.75it/s]

 31%|███       | 31099/100629 [24:39<1:00:00, 19.31it/s]

 31%|███       | 31101/100629 [24:39<1:04:35, 17.94it/s]

 31%|███       | 31103/100629 [24:39<1:07:12, 17.24it/s]

 31%|███       | 31105/100629 [24:39<1:07:23, 17.20it/s]

 31%|███       | 31107/100629 [24:39<1:12:51, 15.90it/s]

 31%|███       | 31110/100629 [24:40<1:00:41, 19.09it/s]

 31%|███       | 31113/100629 [24:40<1:00:33, 19.13it/s]

 31%|███       | 31115/100629 [24:40<1:05:26, 17.71it/s]

 31%|███       | 31118/100629 [24:40<59:19, 19.53it/s]

 31%|███       | 31122/100629 [24:40<50:09, 23.09it/s]

 31%|███       | 31125/100629 [24:40<1:00:20, 19.20it/s]

 31%|███       | 31128/100629 [24:40<1:00:18, 19.21it/s]

 31%|███       | 31132/100629 [24:41<49:13, 23.53it/s]

 31%|███       | 31136/100629 [24:41<44:01, 26.30it/s]

 31%|███       | 31139/100629 [24:41<53:56, 21.47it/s]

 31%|███       | 31142/100629 [24:41<1:06:13, 17.49it/s]

 31%|███       | 31145/100629 [24:41<1:00:26, 19.16it/s]

 31%|███       | 31148/100629 [24:41<54:45, 21.15it/s]

 31%|███       | 31151/100629 [24:41<51:54, 22.31it/s]

 31%|███       | 31154/100629 [24:42<57:56, 19.98it/s]

 31%|███       | 31157/100629 [24:42<1:04:02, 18.08it/s]

 31%|███       | 31159/100629 [24:42<1:07:04, 17.26it/s]

 31%|███       | 31161/100629 [24:42<1:05:35, 17.65it/s]

 31%|███       | 31163/100629 [24:42<1:04:40, 17.90it/s]

 31%|███       | 31168/100629 [24:42<47:01, 24.62it/s]

 31%|███       | 31171/100629 [24:42<51:55, 22.29it/s]

 31%|███       | 31175/100629 [24:43<53:37, 21.58it/s]

 31%|███       | 31178/100629 [24:43<55:07, 21.00it/s]

 31%|███       | 31181/100629 [24:43<55:17, 20.94it/s]

 31%|███       | 31185/100629 [24:43<47:42, 24.26it/s]

 31%|███       | 31188/100629 [24:43<46:04, 25.12it/s]

 31%|███       | 31191/100629 [24:43<44:57, 25.74it/s]

 31%|███       | 31194/100629 [24:44<1:01:44, 18.74it/s]

 31%|███       | 31197/100629 [24:44<56:36, 20.44it/s]

 31%|███       | 31201/100629 [24:44<47:05, 24.57it/s]

 31%|███       | 31205/100629 [24:44<45:29, 25.43it/s]

 31%|███       | 31208/100629 [24:44<49:42, 23.27it/s]

 31%|███       | 31211/100629 [24:44<50:11, 23.05it/s]

 31%|███       | 31214/100629 [24:44<50:03, 23.11it/s]

 31%|███       | 31217/100629 [24:44<48:39, 23.77it/s]

 31%|███       | 31220/100629 [24:45<51:26, 22.49it/s]

 31%|███       | 31223/100629 [24:45<50:38, 22.84it/s]

 31%|███       | 31227/100629 [24:45<43:51, 26.38it/s]

 31%|███       | 31230/100629 [24:45<45:51, 25.22it/s]

 31%|███       | 31235/100629 [24:45<37:18, 31.00it/s]

 31%|███       | 31239/100629 [24:45<51:27, 22.48it/s]

 31%|███       | 31242/100629 [24:46<51:50, 22.30it/s]

 31%|███       | 31246/100629 [24:46<47:06, 24.55it/s]

 31%|███       | 31249/100629 [24:46<47:45, 24.22it/s]

 31%|███       | 31252/100629 [24:46<46:13, 25.02it/s]

 31%|███       | 31256/100629 [24:46<41:52, 27.61it/s]

 31%|███       | 31259/100629 [24:46<51:58, 22.25it/s]

 31%|███       | 31262/100629 [24:46<1:00:25, 19.13it/s]

 31%|███       | 31265/100629 [24:47<1:07:52, 17.03it/s]

 31%|███       | 31268/100629 [24:47<1:02:40, 18.44it/s]

 31%|███       | 31271/100629 [24:47<1:04:12, 18.00it/s]

 31%|███       | 31274/100629 [24:47<57:11, 20.21it/s]

 31%|███       | 31277/100629 [24:47<56:43, 20.38it/s]

 31%|███       | 31280/100629 [24:47<57:00, 20.28it/s]

 31%|███       | 31283/100629 [24:48<56:34, 20.43it/s]

 31%|███       | 31286/100629 [24:48<54:57, 21.03it/s]

 31%|███       | 31289/100629 [24:48<57:33, 20.08it/s]

 31%|███       | 31292/100629 [24:48<1:01:13, 18.87it/s]

 31%|███       | 31295/100629 [24:48<1:01:42, 18.73it/s]

 31%|███       | 31300/100629 [24:48<51:12, 22.57it/s]

 31%|███       | 31303/100629 [24:48<51:30, 22.43it/s]

 31%|███       | 31306/100629 [24:49<48:50, 23.65it/s]

 31%|███       | 31309/100629 [24:49<52:13, 22.12it/s]

 31%|███       | 31312/100629 [24:49<55:05, 20.97it/s]

 31%|███       | 31315/100629 [24:49<1:01:29, 18.79it/s]

 31%|███       | 31317/100629 [24:49<1:01:38, 18.74it/s]

 31%|███       | 31320/100629 [24:49<55:55, 20.66it/s]

 31%|███       | 31323/100629 [24:50<1:02:24, 18.51it/s]

 31%|███       | 31326/100629 [24:50<55:50, 20.69it/s]

 31%|███       | 31329/100629 [24:50<56:55, 20.29it/s]

 31%|███       | 31332/100629 [24:50<1:03:49, 18.09it/s]

 31%|███       | 31335/100629 [24:50<57:37, 20.04it/s]

 31%|███       | 31338/100629 [24:50<1:06:17, 17.42it/s]

 31%|███       | 31342/100629 [24:51<1:02:36, 18.44it/s]

 31%|███       | 31345/100629 [24:51<57:43, 20.00it/s]

 31%|███       | 31349/100629 [24:51<48:52, 23.63it/s]

 31%|███       | 31352/100629 [24:51<52:15, 22.10it/s]

 31%|███       | 31355/100629 [24:51<57:31, 20.07it/s]

 31%|███       | 31360/100629 [24:51<44:39, 25.85it/s]

 31%|███       | 31364/100629 [24:51<42:25, 27.21it/s]

 31%|███       | 31368/100629 [24:52<46:37, 24.76it/s]

 31%|███       | 31372/100629 [24:52<44:51, 25.73it/s]

 31%|███       | 31375/100629 [24:52<1:08:23, 16.88it/s]

 31%|███       | 31379/100629 [24:52<59:59, 19.24it/s]

 31%|███       | 31382/100629 [24:52<1:01:16, 18.83it/s]

 31%|███       | 31385/100629 [24:53<1:07:01, 17.22it/s]

 31%|███       | 31388/100629 [24:53<1:01:43, 18.69it/s]

 31%|███       | 31391/100629 [24:53<55:43, 20.71it/s]

 31%|███       | 31394/100629 [24:53<55:55, 20.63it/s]

 31%|███       | 31398/100629 [24:53<47:58, 24.05it/s]

 31%|███       | 31401/100629 [24:53<1:09:17, 16.65it/s]

 31%|███       | 31406/100629 [24:54<58:45, 19.64it/s]

 31%|███       | 31410/100629 [24:54<50:09, 23.00it/s]

 31%|███       | 31413/100629 [24:54<51:43, 22.30it/s]

 31%|███       | 31416/100629 [24:54<51:30, 22.39it/s]

 31%|███       | 31419/100629 [24:54<55:26, 20.81it/s]

 31%|███       | 31422/100629 [24:54<56:43, 20.34it/s]

 31%|███       | 31426/100629 [24:54<47:33, 24.25it/s]

 31%|███       | 31430/100629 [24:54<42:29, 27.14it/s]

 31%|███       | 31433/100629 [24:55<47:37, 24.22it/s]

 31%|███       | 31437/100629 [24:55<42:26, 27.17it/s]

 31%|███       | 31440/100629 [24:55<46:28, 24.81it/s]

 31%|███       | 31444/100629 [24:55<43:24, 26.57it/s]

 31%|███▏      | 31447/100629 [24:55<50:09, 22.99it/s]

 31%|███▏      | 31450/100629 [24:55<1:02:27, 18.46it/s]

 31%|███▏      | 31454/100629 [24:56<57:21, 20.10it/s]

 31%|███▏      | 31457/100629 [24:56<59:28, 19.38it/s]

 31%|███▏      | 31460/100629 [24:56<57:10, 20.16it/s]

 31%|███▏      | 31463/100629 [24:56<58:59, 19.54it/s]

 31%|███▏      | 31466/100629 [24:56<53:49, 21.41it/s]

 31%|███▏      | 31469/100629 [24:56<57:07, 20.18it/s]

 31%|███▏      | 31472/100629 [24:57<59:31, 19.36it/s]

 31%|███▏      | 31475/100629 [24:57<55:06, 20.91it/s]

 31%|███▏      | 31478/100629 [24:57<58:02, 19.86it/s]

 31%|███▏      | 31481/100629 [24:57<1:02:00, 18.59it/s]

 31%|███▏      | 31483/100629 [24:57<1:02:39, 18.39it/s]

 31%|███▏      | 31486/100629 [24:57<1:00:30, 19.04it/s]

 31%|███▏      | 31489/100629 [24:57<1:00:27, 19.06it/s]

 31%|███▏      | 31492/100629 [24:58<56:06, 20.54it/s]

 31%|███▏      | 31495/100629 [24:58<56:48, 20.29it/s]

 31%|███▏      | 31498/100629 [24:58<57:00, 20.21it/s]

 31%|███▏      | 31503/100629 [24:58<45:00, 25.59it/s]

 31%|███▏      | 31507/100629 [24:58<39:51, 28.90it/s]

 31%|███▏      | 31511/100629 [24:58<42:26, 27.14it/s]

 31%|███▏      | 31514/100629 [24:58<43:08, 26.70it/s]

 31%|███▏      | 31519/100629 [24:59<39:05, 29.46it/s]

 31%|███▏      | 31522/100629 [24:59<41:22, 27.83it/s]

 31%|███▏      | 31525/100629 [24:59<46:14, 24.91it/s]

 31%|███▏      | 31528/100629 [24:59<45:52, 25.10it/s]

 31%|███▏      | 31531/100629 [24:59<46:12, 24.92it/s]

 31%|███▏      | 31534/100629 [24:59<45:53, 25.09it/s]

 31%|███▏      | 31537/100629 [24:59<47:57, 24.01it/s]

 31%|███▏      | 31540/100629 [24:59<45:23, 25.37it/s]

 31%|███▏      | 31544/100629 [24:59<39:51, 28.89it/s]

 31%|███▏      | 31548/100629 [25:00<40:19, 28.55it/s]

 31%|███▏      | 31551/100629 [25:00<51:08, 22.51it/s]

 31%|███▏      | 31554/100629 [25:00<54:08, 21.26it/s]

 31%|███▏      | 31557/100629 [25:00<1:03:32, 18.12it/s]

 31%|███▏      | 31559/100629 [25:00<1:14:30, 15.45it/s]

 31%|███▏      | 31562/100629 [25:01<1:07:22, 17.09it/s]

 31%|███▏      | 31564/100629 [25:01<1:09:55, 16.46it/s]

 31%|███▏      | 31568/100629 [25:01<56:05, 20.52it/s]

 31%|███▏      | 31571/100629 [25:01<51:18, 22.43it/s]

 31%|███▏      | 31574/100629 [25:01<51:37, 22.29it/s]

 31%|███▏      | 31578/100629 [25:01<48:12, 23.88it/s]

 31%|███▏      | 31581/100629 [25:01<49:07, 23.42it/s]

 31%|███▏      | 31584/100629 [25:01<47:45, 24.10it/s]

 31%|███▏      | 31588/100629 [25:02<47:09, 24.40it/s]

 31%|███▏      | 31591/100629 [25:02<46:25, 24.78it/s]

 31%|███▏      | 31594/100629 [25:02<54:51, 20.97it/s]

 31%|███▏      | 31597/100629 [25:02<51:12, 22.47it/s]

 31%|███▏      | 31600/100629 [25:02<51:15, 22.45it/s]

 31%|███▏      | 31603/100629 [25:02<52:49, 21.78it/s]

 31%|███▏      | 31606/100629 [25:02<49:45, 23.12it/s]

 31%|███▏      | 31609/100629 [25:03<1:02:09, 18.50it/s]

 31%|███▏      | 31612/100629 [25:03<57:44, 19.92it/s]

 31%|███▏      | 31615/100629 [25:03<52:08, 22.06it/s]

 31%|███▏      | 31618/100629 [25:03<55:00, 20.91it/s]

 31%|███▏      | 31621/100629 [25:03<51:28, 22.34it/s]

 31%|███▏      | 31624/100629 [25:03<49:27, 23.25it/s]

 31%|███▏      | 31628/100629 [25:03<44:06, 26.07it/s]

 31%|███▏      | 31631/100629 [25:04<47:58, 23.97it/s]

 31%|███▏      | 31634/100629 [25:04<56:01, 20.52it/s]

 31%|███▏      | 31639/100629 [25:04<44:33, 25.81it/s]

 31%|███▏      | 31642/100629 [25:04<49:11, 23.37it/s]

 31%|███▏      | 31647/100629 [25:04<43:23, 26.50it/s]

 31%|███▏      | 31650/100629 [25:04<50:32, 22.75it/s]

 31%|███▏      | 31653/100629 [25:05<52:03, 22.08it/s]

 31%|███▏      | 31657/100629 [25:05<48:57, 23.48it/s]

 31%|███▏      | 31660/100629 [25:05<48:27, 23.72it/s]

 31%|███▏      | 31663/100629 [25:05<51:39, 22.25it/s]

 31%|███▏      | 31667/100629 [25:05<44:55, 25.58it/s]

 31%|███▏      | 31670/100629 [25:05<51:22, 22.37it/s]

 31%|███▏      | 31673/100629 [25:05<51:50, 22.17it/s]

 31%|███▏      | 31676/100629 [25:06<51:57, 22.12it/s]

 31%|███▏      | 31680/100629 [25:06<48:59, 23.46it/s]

 31%|███▏      | 31683/100629 [25:06<50:33, 22.73it/s]

 31%|███▏      | 31686/100629 [25:06<49:18, 23.31it/s]

 31%|███▏      | 31692/100629 [25:06<37:42, 30.47it/s]

 31%|███▏      | 31696/100629 [25:06<51:42, 22.22it/s]

 32%|███▏      | 31699/100629 [25:07<52:30, 21.88it/s]

 32%|███▏      | 31703/100629 [25:07<48:12, 23.83it/s]

 32%|███▏      | 31706/100629 [25:07<56:10, 20.45it/s]

 32%|███▏      | 31709/100629 [25:07<53:58, 21.28it/s]

 32%|███▏      | 31713/100629 [25:07<47:15, 24.31it/s]

 32%|███▏      | 31716/100629 [25:07<55:25, 20.72it/s]

 32%|███▏      | 31719/100629 [25:07<54:16, 21.16it/s]

 32%|███▏      | 31722/100629 [25:08<1:00:07, 19.10it/s]

 32%|███▏      | 31725/100629 [25:08<57:42, 19.90it/s]

 32%|███▏      | 31728/100629 [25:08<1:01:09, 18.78it/s]

 32%|███▏      | 31730/100629 [25:08<1:01:02, 18.81it/s]

 32%|███▏      | 31732/100629 [25:08<1:04:31, 17.80it/s]

 32%|███▏      | 31734/100629 [25:08<1:07:20, 17.05it/s]

 32%|███▏      | 31738/100629 [25:08<53:21, 21.52it/s]

 32%|███▏      | 31741/100629 [25:09<57:25, 20.00it/s]

 32%|███▏      | 31744/100629 [25:09<52:12, 21.99it/s]

 32%|███▏      | 31747/100629 [25:09<1:00:48, 18.88it/s]

 32%|███▏      | 31750/100629 [25:09<54:29, 21.06it/s]

 32%|███▏      | 31753/100629 [25:09<52:49, 21.73it/s]

 32%|███▏      | 31757/100629 [25:09<48:44, 23.55it/s]

 32%|███▏      | 31762/100629 [25:09<41:27, 27.68it/s]

 32%|███▏      | 31765/100629 [25:10<44:15, 25.94it/s]

 32%|███▏      | 31768/100629 [25:10<46:35, 24.64it/s]

 32%|███▏      | 31772/100629 [25:10<50:07, 22.90it/s]

 32%|███▏      | 31775/100629 [25:10<53:13, 21.56it/s]

 32%|███▏      | 31778/100629 [25:10<49:15, 23.30it/s]

 32%|███▏      | 31782/100629 [25:10<43:52, 26.15it/s]

 32%|███▏      | 31785/100629 [25:10<46:05, 24.89it/s]

 32%|███▏      | 31788/100629 [25:11<52:44, 21.76it/s]

 32%|███▏      | 31791/100629 [25:11<48:40, 23.57it/s]

 32%|███▏      | 31794/100629 [25:11<47:07, 24.35it/s]

 32%|███▏      | 31797/100629 [25:11<45:40, 25.11it/s]

 32%|███▏      | 31801/100629 [25:11<41:19, 27.76it/s]

 32%|███▏      | 31804/100629 [25:11<45:11, 25.38it/s]

 32%|███▏      | 31807/100629 [25:11<46:31, 24.65it/s]

 32%|███▏      | 31811/100629 [25:11<41:33, 27.60it/s]

 32%|███▏      | 31814/100629 [25:12<50:06, 22.89it/s]

 32%|███▏      | 31818/100629 [25:12<42:51, 26.76it/s]

 32%|███▏      | 31821/100629 [25:12<44:41, 25.66it/s]

 32%|███▏      | 31826/100629 [25:12<38:27, 29.82it/s]

 32%|███▏      | 31830/100629 [25:12<39:25, 29.09it/s]

 32%|███▏      | 31834/100629 [25:12<44:51, 25.56it/s]

 32%|███▏      | 31837/100629 [25:12<43:16, 26.50it/s]

 32%|███▏      | 31840/100629 [25:13<47:45, 24.01it/s]

 32%|███▏      | 31843/100629 [25:13<50:16, 22.81it/s]

 32%|███▏      | 31846/100629 [25:13<47:40, 24.05it/s]

 32%|███▏      | 31849/100629 [25:13<50:04, 22.89it/s]

 32%|███▏      | 31853/100629 [25:13<46:48, 24.49it/s]

 32%|███▏      | 31856/100629 [25:13<48:59, 23.39it/s]

 32%|███▏      | 31860/100629 [25:13<42:59, 26.66it/s]

 32%|███▏      | 31863/100629 [25:14<43:58, 26.06it/s]

 32%|███▏      | 31866/100629 [25:14<44:48, 25.58it/s]

 32%|███▏      | 31869/100629 [25:14<48:07, 23.81it/s]

 32%|███▏      | 31873/100629 [25:14<43:26, 26.38it/s]

 32%|███▏      | 31876/100629 [25:14<47:39, 24.04it/s]

 32%|███▏      | 31879/100629 [25:14<47:21, 24.19it/s]

 32%|███▏      | 31882/100629 [25:14<59:36, 19.22it/s]

 32%|███▏      | 31885/100629 [25:15<59:16, 19.33it/s]

 32%|███▏      | 31888/100629 [25:15<1:02:58, 18.19it/s]

 32%|███▏      | 31891/100629 [25:15<56:38, 20.23it/s]

 32%|███▏      | 31894/100629 [25:15<58:03, 19.73it/s]

 32%|███▏      | 31897/100629 [25:15<1:02:46, 18.25it/s]

 32%|███▏      | 31900/100629 [25:15<58:51, 19.46it/s]

 32%|███▏      | 31904/100629 [25:15<48:29, 23.62it/s]

 32%|███▏      | 31907/100629 [25:16<54:22, 21.06it/s]

 32%|███▏      | 31910/100629 [25:16<1:11:46, 15.96it/s]

 32%|███▏      | 31912/100629 [25:16<1:09:29, 16.48it/s]

 32%|███▏      | 31916/100629 [25:16<58:17, 19.64it/s]

 32%|███▏      | 31919/100629 [25:16<1:07:48, 16.89it/s]

 32%|███▏      | 31921/100629 [25:17<1:07:04, 17.07it/s]

 32%|███▏      | 31927/100629 [25:17<45:34, 25.12it/s]

 32%|███▏      | 31931/100629 [25:17<45:43, 25.04it/s]

 32%|███▏      | 31934/100629 [25:17<49:35, 23.09it/s]

 32%|███▏      | 31937/100629 [25:17<50:34, 22.64it/s]

 32%|███▏      | 31942/100629 [25:17<39:59, 28.63it/s]

 32%|███▏      | 31946/100629 [25:17<44:22, 25.80it/s]

 32%|███▏      | 31950/100629 [25:18<44:08, 25.93it/s]

 32%|███▏      | 31954/100629 [25:18<45:15, 25.29it/s]

 32%|███▏      | 31957/100629 [25:18<46:46, 24.47it/s]

 32%|███▏      | 31960/100629 [25:18<50:37, 22.61it/s]

 32%|███▏      | 31963/100629 [25:18<52:54, 21.63it/s]

 32%|███▏      | 31966/100629 [25:18<53:09, 21.53it/s]

 32%|███▏      | 31969/100629 [25:18<53:47, 21.27it/s]

 32%|███▏      | 31972/100629 [25:19<57:37, 19.85it/s]

 32%|███▏      | 31975/100629 [25:19<1:00:08, 19.03it/s]

 32%|███▏      | 31977/100629 [25:19<59:39, 19.18it/s]

 32%|███▏      | 31979/100629 [25:19<1:03:43, 17.95it/s]

 32%|███▏      | 31983/100629 [25:19<55:33, 20.59it/s]

 32%|███▏      | 31986/100629 [25:19<58:23, 19.59it/s]

 32%|███▏      | 31990/100629 [25:20<51:40, 22.13it/s]

 32%|███▏      | 31993/100629 [25:20<49:58, 22.89it/s]

 32%|███▏      | 31997/100629 [25:20<50:33, 22.63it/s]

 32%|███▏      | 32000/100629 [25:20<55:51, 20.48it/s]

 32%|███▏      | 32003/100629 [25:20<52:48, 21.66it/s]

 32%|███▏      | 32006/100629 [25:20<1:01:48, 18.51it/s]

 32%|███▏      | 32009/100629 [25:20<56:12, 20.35it/s]

 32%|███▏      | 32012/100629 [25:21<58:23, 19.58it/s]

 32%|███▏      | 32016/100629 [25:21<49:42, 23.00it/s]

 32%|███▏      | 32020/100629 [25:21<43:43, 26.15it/s]

 32%|███▏      | 32023/100629 [25:21<53:57, 21.19it/s]

 32%|███▏      | 32026/100629 [25:21<52:46, 21.67it/s]

 32%|███▏      | 32029/100629 [25:21<59:28, 19.22it/s]

 32%|███▏      | 32033/100629 [25:21<50:02, 22.84it/s]

 32%|███▏      | 32036/100629 [25:22<51:56, 22.01it/s]

 32%|███▏      | 32039/100629 [25:22<50:03, 22.84it/s]

 32%|███▏      | 32042/100629 [25:22<51:21, 22.26it/s]

 32%|███▏      | 32045/100629 [25:22<53:30, 21.36it/s]

 32%|███▏      | 32048/100629 [25:22<55:42, 20.52it/s]

 32%|███▏      | 32051/100629 [25:22<54:23, 21.01it/s]

 32%|███▏      | 32054/100629 [25:22<51:20, 22.26it/s]

 32%|███▏      | 32057/100629 [25:23<50:55, 22.44it/s]

 32%|███▏      | 32060/100629 [25:23<53:33, 21.34it/s]

 32%|███▏      | 32063/100629 [25:23<55:08, 20.72it/s]

 32%|███▏      | 32066/100629 [25:23<58:44, 19.45it/s]

 32%|███▏      | 32068/100629 [25:23<1:01:21, 18.62it/s]

 32%|███▏      | 32071/100629 [25:23<57:51, 19.75it/s]

 32%|███▏      | 32073/100629 [25:23<1:01:19, 18.63it/s]

 32%|███▏      | 32075/100629 [25:24<1:08:56, 16.57it/s]

 32%|███▏      | 32077/100629 [25:24<1:18:07, 14.62it/s]

 32%|███▏      | 32080/100629 [25:24<1:07:20, 16.96it/s]

 32%|███▏      | 32084/100629 [25:24<1:05:17, 17.50it/s]

 32%|███▏      | 32088/100629 [25:24<58:29, 19.53it/s]

 32%|███▏      | 32090/100629 [25:24<1:00:42, 18.82it/s]

 32%|███▏      | 32092/100629 [25:25<59:56, 19.06it/s]

 32%|███▏      | 32095/100629 [25:25<59:31, 19.19it/s]

 32%|███▏      | 32097/100629 [25:25<59:25, 19.22it/s]

 32%|███▏      | 32100/100629 [25:25<1:05:02, 17.56it/s]

 32%|███▏      | 32102/100629 [25:25<1:04:35, 17.68it/s]

 32%|███▏      | 32105/100629 [25:25<1:05:43, 17.38it/s]

 32%|███▏      | 32107/100629 [25:25<1:09:35, 16.41it/s]

 32%|███▏      | 32109/100629 [25:26<1:11:19, 16.01it/s]

 32%|███▏      | 32111/100629 [25:26<1:10:33, 16.19it/s]

 32%|███▏      | 32113/100629 [25:26<1:14:45, 15.28it/s]

 32%|███▏      | 32115/100629 [25:26<1:12:14, 15.81it/s]

 32%|███▏      | 32117/100629 [25:26<1:09:38, 16.40it/s]

 32%|███▏      | 32120/100629 [25:26<59:05, 19.32it/s]

 32%|███▏      | 32122/100629 [25:26<1:05:27, 17.44it/s]

 32%|███▏      | 32124/100629 [25:26<1:07:33, 16.90it/s]

 32%|███▏      | 32126/100629 [25:27<1:09:16, 16.48it/s]

 32%|███▏      | 32129/100629 [25:27<1:04:46, 17.63it/s]

 32%|███▏      | 32132/100629 [25:27<56:08, 20.33it/s]

 32%|███▏      | 32135/100629 [25:27<51:42, 22.08it/s]

 32%|███▏      | 32139/100629 [25:27<51:58, 21.96it/s]

 32%|███▏      | 32142/100629 [25:27<52:51, 21.60it/s]

 32%|███▏      | 32145/100629 [25:27<53:54, 21.17it/s]

 32%|███▏      | 32148/100629 [25:28<53:40, 21.26it/s]

 32%|███▏      | 32151/100629 [25:28<53:57, 21.15it/s]

 32%|███▏      | 32154/100629 [25:28<57:00, 20.02it/s]

 32%|███▏      | 32157/100629 [25:28<1:00:11, 18.96it/s]

 32%|███▏      | 32160/100629 [25:28<57:33, 19.82it/s]

 32%|███▏      | 32164/100629 [25:28<50:48, 22.46it/s]

 32%|███▏      | 32167/100629 [25:28<48:00, 23.77it/s]

 32%|███▏      | 32171/100629 [25:29<44:21, 25.72it/s]

 32%|███▏      | 32174/100629 [25:29<44:21, 25.72it/s]

 32%|███▏      | 32178/100629 [25:29<43:39, 26.13it/s]

 32%|███▏      | 32182/100629 [25:29<40:04, 28.46it/s]

 32%|███▏      | 32185/100629 [25:29<54:48, 20.81it/s]

 32%|███▏      | 32188/100629 [25:29<51:16, 22.25it/s]

 32%|███▏      | 32192/100629 [25:29<46:22, 24.60it/s]

 32%|███▏      | 32195/100629 [25:30<47:19, 24.10it/s]

 32%|███▏      | 32200/100629 [25:30<40:18, 28.29it/s]

 32%|███▏      | 32203/100629 [25:30<43:38, 26.13it/s]

 32%|███▏      | 32206/100629 [25:30<45:51, 24.87it/s]

 32%|███▏      | 32209/100629 [25:30<50:03, 22.78it/s]

 32%|███▏      | 32213/100629 [25:30<45:35, 25.01it/s]

 32%|███▏      | 32216/100629 [25:30<49:27, 23.05it/s]

 32%|███▏      | 32219/100629 [25:31<49:58, 22.81it/s]

 32%|███▏      | 32222/100629 [25:31<55:54, 20.39it/s]

 32%|███▏      | 32226/100629 [25:31<47:46, 23.86it/s]

 32%|███▏      | 32229/100629 [25:31<45:40, 24.96it/s]

 32%|███▏      | 32232/100629 [25:31<44:46, 25.46it/s]

 32%|███▏      | 32235/100629 [25:31<50:30, 22.57it/s]

 32%|███▏      | 32238/100629 [25:31<52:05, 21.88it/s]

 32%|███▏      | 32241/100629 [25:32<54:40, 20.85it/s]

 32%|███▏      | 32244/100629 [25:32<54:08, 21.05it/s]

 32%|███▏      | 32247/100629 [25:32<55:35, 20.50it/s]

 32%|███▏      | 32251/100629 [25:32<47:08, 24.18it/s]

 32%|███▏      | 32254/100629 [25:32<45:05, 25.27it/s]

 32%|███▏      | 32257/100629 [25:32<1:02:07, 18.34it/s]

 32%|███▏      | 32260/100629 [25:33<1:03:08, 18.05it/s]

 32%|███▏      | 32263/100629 [25:33<1:02:39, 18.18it/s]

 32%|███▏      | 32266/100629 [25:33<58:17, 19.55it/s]

 32%|███▏      | 32269/100629 [25:33<54:36, 20.86it/s]

 32%|███▏      | 32272/100629 [25:33<53:31, 21.29it/s]

 32%|███▏      | 32275/100629 [25:33<50:49, 22.41it/s]

 32%|███▏      | 32278/100629 [25:33<48:39, 23.41it/s]

 32%|███▏      | 32283/100629 [25:33<38:31, 29.56it/s]

 32%|███▏      | 32287/100629 [25:34<39:00, 29.20it/s]

 32%|███▏      | 32291/100629 [25:34<41:34, 27.40it/s]

 32%|███▏      | 32294/100629 [25:34<46:35, 24.44it/s]

 32%|███▏      | 32297/100629 [25:34<49:20, 23.08it/s]

 32%|███▏      | 32300/100629 [25:34<50:25, 22.58it/s]

 32%|███▏      | 32303/100629 [25:34<53:54, 21.12it/s]

 32%|███▏      | 32306/100629 [25:34<55:37, 20.47it/s]

 32%|███▏      | 32309/100629 [25:35<52:36, 21.64it/s]

 32%|███▏      | 32316/100629 [25:35<41:17, 27.58it/s]

 32%|███▏      | 32319/100629 [25:35<44:22, 25.66it/s]

 32%|███▏      | 32323/100629 [25:35<39:50, 28.57it/s]

 32%|███▏      | 32326/100629 [25:35<50:17, 22.64it/s]

 32%|███▏      | 32329/100629 [25:35<53:25, 21.30it/s]

 32%|███▏      | 32332/100629 [25:36<52:23, 21.73it/s]

 32%|███▏      | 32335/100629 [25:36<49:31, 22.98it/s]

 32%|███▏      | 32338/100629 [25:36<50:49, 22.39it/s]

 32%|███▏      | 32341/100629 [25:36<50:39, 22.46it/s]

 32%|███▏      | 32344/100629 [25:36<52:54, 21.51it/s]

 32%|███▏      | 32347/100629 [25:36<51:16, 22.19it/s]

 32%|███▏      | 32351/100629 [25:36<43:32, 26.13it/s]

 32%|███▏      | 32354/100629 [25:36<46:16, 24.59it/s]

 32%|███▏      | 32358/100629 [25:37<40:32, 28.07it/s]

 32%|███▏      | 32362/100629 [25:37<41:30, 27.41it/s]

 32%|███▏      | 32366/100629 [25:37<40:42, 27.94it/s]

 32%|███▏      | 32369/100629 [25:37<46:40, 24.37it/s]

 32%|███▏      | 32372/100629 [25:37<51:22, 22.15it/s]

 32%|███▏      | 32375/100629 [25:37<50:58, 22.31it/s]

 32%|███▏      | 32378/100629 [25:38<59:26, 19.14it/s]

 32%|███▏      | 32382/100629 [25:38<51:45, 21.98it/s]

 32%|███▏      | 32385/100629 [25:38<59:00, 19.27it/s]

 32%|███▏      | 32388/100629 [25:38<1:00:17, 18.87it/s]

 32%|███▏      | 32391/100629 [25:38<1:02:47, 18.11it/s]

 32%|███▏      | 32393/100629 [25:38<1:02:52, 18.09it/s]

 32%|███▏      | 32395/100629 [25:38<1:05:17, 17.42it/s]

 32%|███▏      | 32398/100629 [25:39<1:01:37, 18.45it/s]

 32%|███▏      | 32400/100629 [25:39<1:00:47, 18.70it/s]

 32%|███▏      | 32403/100629 [25:39<56:52, 19.99it/s]

 32%|███▏      | 32406/100629 [25:39<1:03:28, 17.91it/s]

 32%|███▏      | 32410/100629 [25:39<59:46, 19.02it/s]

 32%|███▏      | 32412/100629 [25:39<1:06:53, 17.00it/s]

 32%|███▏      | 32416/100629 [25:40<1:01:25, 18.51it/s]

 32%|███▏      | 32418/100629 [25:40<1:03:30, 17.90it/s]

 32%|███▏      | 32421/100629 [25:40<55:49, 20.36it/s]

 32%|███▏      | 32424/100629 [25:40<57:10, 19.88it/s]

 32%|███▏      | 32428/100629 [25:40<49:32, 22.94it/s]

 32%|███▏      | 32432/100629 [25:40<47:48, 23.77it/s]

 32%|███▏      | 32435/100629 [25:41<1:02:04, 18.31it/s]

 32%|███▏      | 32438/100629 [25:41<57:52, 19.64it/s]

 32%|███▏      | 32441/100629 [25:41<1:04:00, 17.76it/s]

 32%|███▏      | 32443/100629 [25:41<1:13:36, 15.44it/s]

 32%|███▏      | 32447/100629 [25:41<1:02:53, 18.07it/s]

 32%|███▏      | 32449/100629 [25:41<1:07:47, 16.76it/s]

 32%|███▏      | 32451/100629 [25:41<1:05:54, 17.24it/s]

 32%|███▏      | 32453/100629 [25:42<1:05:10, 17.43it/s]

 32%|███▏      | 32456/100629 [25:42<58:59, 19.26it/s]

 32%|███▏      | 32459/100629 [25:42<55:05, 20.62it/s]

 32%|███▏      | 32462/100629 [25:42<51:34, 22.03it/s]

 32%|███▏      | 32465/100629 [25:42<56:02, 20.27it/s]

 32%|███▏      | 32468/100629 [25:42<52:14, 21.74it/s]

 32%|███▏      | 32471/100629 [25:42<48:23, 23.47it/s]

 32%|███▏      | 32475/100629 [25:42<43:21, 26.20it/s]

 32%|███▏      | 32479/100629 [25:43<40:21, 28.15it/s]

 32%|███▏      | 32482/100629 [25:43<39:41, 28.62it/s]

 32%|███▏      | 32488/100629 [25:43<35:12, 32.25it/s]

 32%|███▏      | 32492/100629 [25:43<37:01, 30.67it/s]

 32%|███▏      | 32496/100629 [25:43<42:42, 26.59it/s]

 32%|███▏      | 32502/100629 [25:43<35:17, 32.17it/s]

 32%|███▏      | 32506/100629 [25:44<50:29, 22.49it/s]

 32%|███▏      | 32509/100629 [25:44<50:24, 22.52it/s]

 32%|███▏      | 32512/100629 [25:44<48:07, 23.59it/s]

 32%|███▏      | 32515/100629 [25:44<46:45, 24.28it/s]

 32%|███▏      | 32520/100629 [25:44<40:27, 28.06it/s]

 32%|███▏      | 32523/100629 [25:44<45:48, 24.78it/s]

 32%|███▏      | 32526/100629 [25:45<56:44, 20.00it/s]

 32%|███▏      | 32529/100629 [25:45<56:00, 20.26it/s]

 32%|███▏      | 32532/100629 [25:45<52:22, 21.67it/s]

 32%|███▏      | 32535/100629 [25:45<50:00, 22.69it/s]

 32%|███▏      | 32538/100629 [25:45<54:09, 20.95it/s]

 32%|███▏      | 32541/100629 [25:45<55:12, 20.56it/s]

 32%|███▏      | 32544/100629 [25:45<58:15, 19.48it/s]

 32%|███▏      | 32547/100629 [25:46<57:52, 19.61it/s]

 32%|███▏      | 32550/100629 [25:46<53:50, 21.08it/s]

 32%|███▏      | 32553/100629 [25:46<51:42, 21.94it/s]

 32%|███▏      | 32556/100629 [25:46<57:02, 19.89it/s]

 32%|███▏      | 32559/100629 [25:46<54:13, 20.92it/s]

 32%|███▏      | 32562/100629 [25:46<51:27, 22.05it/s]

 32%|███▏      | 32565/100629 [25:46<55:28, 20.45it/s]

 32%|███▏      | 32569/100629 [25:46<46:14, 24.53it/s]

 32%|███▏      | 32572/100629 [25:47<52:45, 21.50it/s]

 32%|███▏      | 32575/100629 [25:47<50:57, 22.26it/s]

 32%|███▏      | 32578/100629 [25:47<52:26, 21.63it/s]

 32%|███▏      | 32581/100629 [25:47<54:35, 20.78it/s]

 32%|███▏      | 32584/100629 [25:47<55:36, 20.39it/s]

 32%|███▏      | 32587/100629 [25:47<54:30, 20.80it/s]

 32%|███▏      | 32590/100629 [25:48<56:48, 19.96it/s]

 32%|███▏      | 32593/100629 [25:48<52:21, 21.66it/s]

 32%|███▏      | 32597/100629 [25:48<43:40, 25.97it/s]

 32%|███▏      | 32600/100629 [25:48<49:06, 23.09it/s]

 32%|███▏      | 32603/100629 [25:48<46:34, 24.34it/s]

 32%|███▏      | 32606/100629 [25:48<48:22, 23.43it/s]

 32%|███▏      | 32609/100629 [25:48<46:30, 24.38it/s]

 32%|███▏      | 32613/100629 [25:48<44:15, 25.61it/s]

 32%|███▏      | 32616/100629 [25:49<46:57, 24.14it/s]

 32%|███▏      | 32619/100629 [25:49<54:56, 20.63it/s]

 32%|███▏      | 32622/100629 [25:49<1:02:56, 18.01it/s]

 32%|███▏      | 32624/100629 [25:49<1:04:36, 17.54it/s]

 32%|███▏      | 32626/100629 [25:49<1:07:57, 16.68it/s]

 32%|███▏      | 32628/100629 [25:49<1:07:16, 16.84it/s]

 32%|███▏      | 32631/100629 [25:49<1:00:25, 18.76it/s]

 32%|███▏      | 32633/100629 [25:50<1:01:34, 18.40it/s]

 32%|███▏      | 32636/100629 [25:50<57:13, 19.81it/s]

 32%|███▏      | 32640/100629 [25:50<53:23, 21.23it/s]

 32%|███▏      | 32644/100629 [25:50<44:47, 25.29it/s]

 32%|███▏      | 32647/100629 [25:50<48:01, 23.59it/s]

 32%|███▏      | 32650/100629 [25:50<47:47, 23.70it/s]

 32%|███▏      | 32653/100629 [25:50<49:08, 23.06it/s]

 32%|███▏      | 32656/100629 [25:51<52:54, 21.41it/s]

 32%|███▏      | 32659/100629 [25:51<53:38, 21.12it/s]

 32%|███▏      | 32663/100629 [25:51<50:58, 22.22it/s]

 32%|███▏      | 32666/100629 [25:51<57:57, 19.54it/s]

 32%|███▏      | 32669/100629 [25:51<53:11, 21.29it/s]

 32%|███▏      | 32673/100629 [25:51<45:33, 24.86it/s]

 32%|███▏      | 32676/100629 [25:51<46:53, 24.15it/s]

 32%|███▏      | 32679/100629 [25:52<47:48, 23.69it/s]

 32%|███▏      | 32682/100629 [25:52<46:27, 24.38it/s]

 32%|███▏      | 32685/100629 [25:52<44:44, 25.31it/s]

 32%|███▏      | 32688/100629 [25:52<53:15, 21.26it/s]

 32%|███▏      | 32691/100629 [25:52<1:02:38, 18.08it/s]

 32%|███▏      | 32693/100629 [25:52<1:05:29, 17.29it/s]

 32%|███▏      | 32695/100629 [25:52<1:08:04, 16.63it/s]

 32%|███▏      | 32699/100629 [25:53<55:40, 20.33it/s]

 32%|███▏      | 32702/100629 [25:53<51:04, 22.17it/s]

 33%|███▎      | 32705/100629 [25:53<49:05, 23.06it/s]

 33%|███▎      | 32708/100629 [25:53<46:54, 24.13it/s]

 33%|███▎      | 32711/100629 [25:53<47:15, 23.96it/s]

 33%|███▎      | 32714/100629 [25:53<47:28, 23.84it/s]

 33%|███▎      | 32717/100629 [25:53<51:14, 22.09it/s]

 33%|███▎      | 32720/100629 [25:53<49:15, 22.98it/s]

 33%|███▎      | 32723/100629 [25:54<50:36, 22.36it/s]

 33%|███▎      | 32726/100629 [25:54<55:19, 20.46it/s]

 33%|███▎      | 32729/100629 [25:54<53:05, 21.32it/s]

 33%|███▎      | 32732/100629 [25:54<56:52, 19.90it/s]

 33%|███▎      | 32735/100629 [25:54<51:18, 22.05it/s]

 33%|███▎      | 32739/100629 [25:54<45:10, 25.04it/s]

 33%|███▎      | 32742/100629 [25:54<48:51, 23.16it/s]

 33%|███▎      | 32745/100629 [25:55<45:40, 24.77it/s]

 33%|███▎      | 32748/100629 [25:55<49:05, 23.05it/s]

 33%|███▎      | 32752/100629 [25:55<44:37, 25.35it/s]

 33%|███▎      | 32756/100629 [25:55<46:21, 24.40it/s]

 33%|███▎      | 32760/100629 [25:55<44:12, 25.59it/s]

 33%|███▎      | 32763/100629 [25:55<49:28, 22.86it/s]

 33%|███▎      | 32766/100629 [25:55<48:37, 23.26it/s]

 33%|███▎      | 32769/100629 [25:56<49:19, 22.93it/s]

 33%|███▎      | 32772/100629 [25:56<55:27, 20.39it/s]

 33%|███▎      | 32775/100629 [25:56<52:59, 21.34it/s]

 33%|███▎      | 32779/100629 [25:56<45:22, 24.92it/s]

 33%|███▎      | 32782/100629 [25:56<45:07, 25.06it/s]

 33%|███▎      | 32785/100629 [25:56<51:07, 22.12it/s]

 33%|███▎      | 32788/100629 [25:57<58:52, 19.20it/s]

 33%|███▎      | 32791/100629 [25:57<54:16, 20.83it/s]

 33%|███▎      | 32794/100629 [25:57<56:17, 20.08it/s]

 33%|███▎      | 32797/100629 [25:57<50:52, 22.22it/s]

 33%|███▎      | 32800/100629 [25:57<54:09, 20.87it/s]

 33%|███▎      | 32803/100629 [25:57<1:00:44, 18.61it/s]

 33%|███▎      | 32809/100629 [25:57<46:29, 24.31it/s]

 33%|███▎      | 32813/100629 [25:58<49:10, 22.98it/s]

 33%|███▎      | 32816/100629 [25:58<51:08, 22.10it/s]

 33%|███▎      | 32820/100629 [25:58<47:09, 23.96it/s]

 33%|███▎      | 32823/100629 [25:58<50:59, 22.17it/s]

 33%|███▎      | 32826/100629 [25:58<51:46, 21.82it/s]

 33%|███▎      | 32830/100629 [25:58<43:57, 25.71it/s]

 33%|███▎      | 32833/100629 [25:59<54:59, 20.55it/s]

 33%|███▎      | 32836/100629 [25:59<56:45, 19.90it/s]

 33%|███▎      | 32839/100629 [25:59<57:58, 19.49it/s]

 33%|███▎      | 32842/100629 [25:59<57:24, 19.68it/s]

 33%|███▎      | 32845/100629 [25:59<54:10, 20.85it/s]

 33%|███▎      | 32848/100629 [25:59<56:11, 20.10it/s]

 33%|███▎      | 32851/100629 [25:59<51:04, 22.12it/s]

 33%|███▎      | 32854/100629 [26:00<50:46, 22.25it/s]

 33%|███▎      | 32857/100629 [26:00<56:13, 20.09it/s]

 33%|███▎      | 32860/100629 [26:00<53:58, 20.92it/s]

 33%|███▎      | 32863/100629 [26:00<57:05, 19.79it/s]

 33%|███▎      | 32866/100629 [26:00<56:43, 19.91it/s]

 33%|███▎      | 32869/100629 [26:00<52:09, 21.65it/s]

 33%|███▎      | 32873/100629 [26:00<45:01, 25.08it/s]

 33%|███▎      | 32876/100629 [26:01<51:00, 22.13it/s]

 33%|███▎      | 32879/100629 [26:01<50:22, 22.41it/s]

 33%|███▎      | 32882/100629 [26:01<58:58, 19.14it/s]

 33%|███▎      | 32885/100629 [26:01<55:45, 20.25it/s]

 33%|███▎      | 32888/100629 [26:01<57:17, 19.71it/s]

 33%|███▎      | 32891/100629 [26:01<1:03:44, 17.71it/s]

 33%|███▎      | 32893/100629 [26:02<1:10:42, 15.96it/s]

 33%|███▎      | 32895/100629 [26:02<1:09:31, 16.24it/s]

 33%|███▎      | 32897/100629 [26:02<1:09:18, 16.29it/s]

 33%|███▎      | 32899/100629 [26:02<1:19:33, 14.19it/s]

 33%|███▎      | 32901/100629 [26:02<1:14:25, 15.17it/s]

 33%|███▎      | 32905/100629 [26:02<57:50, 19.51it/s]

 33%|███▎      | 32908/100629 [26:02<1:00:21, 18.70it/s]

 33%|███▎      | 32910/100629 [26:03<1:00:04, 18.79it/s]

 33%|███▎      | 32913/100629 [26:03<53:06, 21.25it/s]

 33%|███▎      | 32916/100629 [26:03<1:00:49, 18.55it/s]

 33%|███▎      | 32919/100629 [26:03<55:23, 20.37it/s]

 33%|███▎      | 32923/100629 [26:03<52:34, 21.46it/s]

 33%|███▎      | 32927/100629 [26:03<49:07, 22.97it/s]

 33%|███▎      | 32930/100629 [26:03<48:00, 23.50it/s]

 33%|███▎      | 32933/100629 [26:04<52:13, 21.61it/s]

 33%|███▎      | 32937/100629 [26:04<47:58, 23.51it/s]

 33%|███▎      | 32941/100629 [26:04<45:07, 25.00it/s]

 33%|███▎      | 32944/100629 [26:04<53:30, 21.08it/s]

 33%|███▎      | 32947/100629 [26:04<1:03:29, 17.77it/s]

 33%|███▎      | 32952/100629 [26:04<49:35, 22.74it/s]

 33%|███▎      | 32955/100629 [26:05<48:59, 23.02it/s]

 33%|███▎      | 32958/100629 [26:05<51:22, 21.96it/s]

 33%|███▎      | 32962/100629 [26:05<46:37, 24.19it/s]

 33%|███▎      | 32965/100629 [26:05<45:28, 24.80it/s]

 33%|███▎      | 32968/100629 [26:05<45:45, 24.64it/s]

 33%|███▎      | 32971/100629 [26:05<51:54, 21.72it/s]

 33%|███▎      | 32974/100629 [26:05<1:01:18, 18.39it/s]

 33%|███▎      | 32976/100629 [26:06<1:05:50, 17.13it/s]

 33%|███▎      | 32978/100629 [26:06<1:08:32, 16.45it/s]

 33%|███▎      | 32982/100629 [26:06<57:30, 19.60it/s]

 33%|███▎      | 32985/100629 [26:06<59:57, 18.80it/s]

 33%|███▎      | 32988/100629 [26:06<53:40, 21.01it/s]

 33%|███▎      | 32991/100629 [26:06<59:06, 19.07it/s]

 33%|███▎      | 32994/100629 [26:07<1:11:59, 15.66it/s]

 33%|███▎      | 32998/100629 [26:07<1:00:01, 18.78it/s]

 33%|███▎      | 33001/100629 [26:07<58:55, 19.13it/s]

 33%|███▎      | 33004/100629 [26:07<1:02:13, 18.11it/s]

 33%|███▎      | 33008/100629 [26:07<57:45, 19.51it/s]

 33%|███▎      | 33011/100629 [26:07<1:01:54, 18.20it/s]

 33%|███▎      | 33014/100629 [26:08<55:57, 20.14it/s]

 33%|███▎      | 33017/100629 [26:08<57:51, 19.48it/s]

 33%|███▎      | 33020/100629 [26:08<55:59, 20.13it/s]

 33%|███▎      | 33023/100629 [26:08<1:01:31, 18.32it/s]

 33%|███▎      | 33027/100629 [26:08<57:56, 19.45it/s]

 33%|███▎      | 33031/100629 [26:08<51:29, 21.88it/s]

 33%|███▎      | 33035/100629 [26:09<49:50, 22.60it/s]

 33%|███▎      | 33039/100629 [26:09<45:31, 24.75it/s]

 33%|███▎      | 33042/100629 [26:09<50:09, 22.46it/s]

 33%|███▎      | 33045/100629 [26:09<58:01, 19.41it/s]

 33%|███▎      | 33048/100629 [26:09<57:32, 19.57it/s]

 33%|███▎      | 33051/100629 [26:09<59:36, 18.89it/s]

 33%|███▎      | 33055/100629 [26:10<55:17, 20.37it/s]

 33%|███▎      | 33058/100629 [26:10<1:03:49, 17.65it/s]

 33%|███▎      | 33062/100629 [26:10<57:46, 19.49it/s]

 33%|███▎      | 33065/100629 [26:10<56:03, 20.09it/s]

 33%|███▎      | 33069/100629 [26:10<54:38, 20.61it/s]

 33%|███▎      | 33072/100629 [26:10<55:04, 20.45it/s]

 33%|███▎      | 33075/100629 [26:11<53:16, 21.13it/s]

 33%|███▎      | 33079/100629 [26:11<46:04, 24.43it/s]

 33%|███▎      | 33084/100629 [26:11<42:18, 26.61it/s]

 33%|███▎      | 33087/100629 [26:11<47:03, 23.92it/s]

 33%|███▎      | 33090/100629 [26:11<49:37, 22.69it/s]

 33%|███▎      | 33093/100629 [26:11<50:18, 22.38it/s]

 33%|███▎      | 33096/100629 [26:11<53:05, 21.20it/s]

 33%|███▎      | 33099/100629 [26:12<52:05, 21.61it/s]

 33%|███▎      | 33102/100629 [26:12<52:12, 21.56it/s]

 33%|███▎      | 33105/100629 [26:12<48:01, 23.44it/s]

 33%|███▎      | 33108/100629 [26:12<49:36, 22.69it/s]

 33%|███▎      | 33111/100629 [26:12<53:21, 21.09it/s]

 33%|███▎      | 33116/100629 [26:12<46:36, 24.14it/s]

 33%|███▎      | 33119/100629 [26:12<45:22, 24.79it/s]

 33%|███▎      | 33123/100629 [26:13<43:13, 26.03it/s]

 33%|███▎      | 33126/100629 [26:13<51:27, 21.86it/s]

 33%|███▎      | 33130/100629 [26:13<49:46, 22.60it/s]

 33%|███▎      | 33133/100629 [26:13<46:46, 24.05it/s]

 33%|███▎      | 33137/100629 [26:13<41:39, 27.00it/s]

 33%|███▎      | 33142/100629 [26:13<35:54, 31.32it/s]

 33%|███▎      | 33146/100629 [26:13<40:35, 27.71it/s]

 33%|███▎      | 33149/100629 [26:14<46:40, 24.10it/s]

 33%|███▎      | 33152/100629 [26:14<47:19, 23.76it/s]

 33%|███▎      | 33156/100629 [26:14<41:22, 27.18it/s]

 33%|███▎      | 33159/100629 [26:14<45:08, 24.91it/s]

 33%|███▎      | 33162/100629 [26:14<50:05, 22.45it/s]

 33%|███▎      | 33165/100629 [26:14<50:43, 22.16it/s]

 33%|███▎      | 33168/100629 [26:14<48:16, 23.29it/s]

 33%|███▎      | 33171/100629 [26:15<48:47, 23.04it/s]

 33%|███▎      | 33174/100629 [26:15<46:11, 24.33it/s]

 33%|███▎      | 33177/100629 [26:15<50:54, 22.08it/s]

 33%|███▎      | 33180/100629 [26:15<55:37, 20.21it/s]

 33%|███▎      | 33183/100629 [26:15<50:14, 22.37it/s]

 33%|███▎      | 33186/100629 [26:15<52:54, 21.24it/s]

 33%|███▎      | 33189/100629 [26:15<52:22, 21.46it/s]

 33%|███▎      | 33192/100629 [26:16<52:14, 21.51it/s]

 33%|███▎      | 33195/100629 [26:16<51:49, 21.68it/s]

 33%|███▎      | 33199/100629 [26:16<44:44, 25.11it/s]

 33%|███▎      | 33202/100629 [26:16<48:16, 23.28it/s]

 33%|███▎      | 33205/100629 [26:16<48:48, 23.02it/s]

 33%|███▎      | 33208/100629 [26:16<48:46, 23.04it/s]

 33%|███▎      | 33211/100629 [26:16<53:39, 20.94it/s]

 33%|███▎      | 33214/100629 [26:17<49:01, 22.92it/s]

 33%|███▎      | 33217/100629 [26:17<59:54, 18.75it/s]

 33%|███▎      | 33220/100629 [26:17<1:00:05, 18.70it/s]

 33%|███▎      | 33223/100629 [26:17<55:36, 20.20it/s]

 33%|███▎      | 33226/100629 [26:17<54:25, 20.64it/s]

 33%|███▎      | 33229/100629 [26:17<54:01, 20.80it/s]

 33%|███▎      | 33232/100629 [26:17<50:43, 22.14it/s]

 33%|███▎      | 33236/100629 [26:18<48:14, 23.28it/s]

 33%|███▎      | 33240/100629 [26:18<43:44, 25.67it/s]

 33%|███▎      | 33243/100629 [26:18<50:35, 22.20it/s]

 33%|███▎      | 33247/100629 [26:18<47:39, 23.56it/s]

 33%|███▎      | 33250/100629 [26:18<45:41, 24.57it/s]

 33%|███▎      | 33253/100629 [26:18<50:17, 22.33it/s]

 33%|███▎      | 33256/100629 [26:18<54:09, 20.74it/s]

 33%|███▎      | 33259/100629 [26:19<52:29, 21.39it/s]

 33%|███▎      | 33262/100629 [26:19<56:41, 19.80it/s]

 33%|███▎      | 33265/100629 [26:19<57:19, 19.58it/s]

 33%|███▎      | 33268/100629 [26:19<58:53, 19.06it/s]

 33%|███▎      | 33271/100629 [26:19<53:17, 21.06it/s]

 33%|███▎      | 33274/100629 [26:19<1:01:24, 18.28it/s]

 33%|███▎      | 33276/100629 [26:20<1:02:39, 17.92it/s]

 33%|███▎      | 33279/100629 [26:20<54:49, 20.47it/s]

 33%|███▎      | 33282/100629 [26:20<1:04:31, 17.40it/s]

 33%|███▎      | 33285/100629 [26:20<1:00:53, 18.43it/s]

 33%|███▎      | 33288/100629 [26:20<59:21, 18.91it/s]

 33%|███▎      | 33293/100629 [26:20<45:46, 24.52it/s]

 33%|███▎      | 33296/100629 [26:20<52:58, 21.18it/s]

 33%|███▎      | 33300/100629 [26:21<47:53, 23.43it/s]

 33%|███▎      | 33303/100629 [26:21<49:14, 22.78it/s]

 33%|███▎      | 33306/100629 [26:21<49:33, 22.64it/s]

 33%|███▎      | 33309/100629 [26:21<47:22, 23.68it/s]

 33%|███▎      | 33312/100629 [26:21<44:38, 25.13it/s]

 33%|███▎      | 33317/100629 [26:21<36:08, 31.04it/s]

 33%|███▎      | 33321/100629 [26:21<44:05, 25.44it/s]

 33%|███▎      | 33324/100629 [26:22<50:36, 22.16it/s]

 33%|███▎      | 33327/100629 [26:22<51:30, 21.78it/s]

 33%|███▎      | 33330/100629 [26:22<53:34, 20.93it/s]

 33%|███▎      | 33333/100629 [26:22<51:29, 21.78it/s]

 33%|███▎      | 33337/100629 [26:22<45:49, 24.48it/s]

 33%|███▎      | 33340/100629 [26:22<47:00, 23.86it/s]

 33%|███▎      | 33343/100629 [26:22<47:57, 23.38it/s]

 33%|███▎      | 33346/100629 [26:23<51:27, 21.79it/s]

 33%|███▎      | 33350/100629 [26:23<49:27, 22.67it/s]

 33%|███▎      | 33353/100629 [26:23<1:01:24, 18.26it/s]

 33%|███▎      | 33355/100629 [26:23<1:05:19, 17.16it/s]

 33%|███▎      | 33359/100629 [26:23<52:39, 21.29it/s]

 33%|███▎      | 33362/100629 [26:23<56:14, 19.93it/s]

 33%|███▎      | 33365/100629 [26:24<1:12:37, 15.44it/s]

 33%|███▎      | 33368/100629 [26:24<1:06:07, 16.95it/s]

 33%|███▎      | 33371/100629 [26:24<1:03:33, 17.64it/s]

 33%|███▎      | 33373/100629 [26:24<1:09:03, 16.23it/s]

 33%|███▎      | 33376/100629 [26:24<1:03:49, 17.56it/s]

 33%|███▎      | 33379/100629 [26:24<55:56, 20.03it/s]

 33%|███▎      | 33382/100629 [26:25<55:48, 20.08it/s]

 33%|███▎      | 33385/100629 [26:25<55:46, 20.09it/s]

 33%|███▎      | 33388/100629 [26:25<58:18, 19.22it/s]

 33%|███▎      | 33392/100629 [26:25<55:33, 20.17it/s]

 33%|███▎      | 33395/100629 [26:25<56:36, 19.80it/s]

 33%|███▎      | 33398/100629 [26:25<52:05, 21.51it/s]

 33%|███▎      | 33403/100629 [26:26<45:50, 24.45it/s]

 33%|███▎      | 33406/100629 [26:26<53:13, 21.05it/s]

 33%|███▎      | 33410/100629 [26:26<49:41, 22.54it/s]

 33%|███▎      | 33413/100629 [26:26<47:09, 23.76it/s]

 33%|███▎      | 33417/100629 [26:26<44:49, 24.99it/s]

 33%|███▎      | 33420/100629 [26:26<46:14, 24.22it/s]

 33%|███▎      | 33423/100629 [26:26<48:26, 23.12it/s]

 33%|███▎      | 33426/100629 [26:27<48:32, 23.07it/s]

 33%|███▎      | 33429/100629 [26:27<50:14, 22.29it/s]

 33%|███▎      | 33432/100629 [26:27<59:27, 18.83it/s]

 33%|███▎      | 33434/100629 [26:27<1:06:29, 16.84it/s]

 33%|███▎      | 33436/100629 [26:27<1:06:34, 16.82it/s]

 33%|███▎      | 33438/100629 [26:27<1:14:52, 14.96it/s]

 33%|███▎      | 33442/100629 [26:27<56:34, 19.79it/s]

 33%|███▎      | 33445/100629 [26:28<59:13, 18.91it/s]

 33%|███▎      | 33448/100629 [26:28<59:09, 18.93it/s]

 33%|███▎      | 33450/100629 [26:28<1:02:43, 17.85it/s]

 33%|███▎      | 33452/100629 [26:28<1:01:40, 18.15it/s]

 33%|███▎      | 33456/100629 [26:28<49:45, 22.50it/s]

 33%|███▎      | 33459/100629 [26:28<49:21, 22.68it/s]

 33%|███▎      | 33462/100629 [26:28<53:57, 20.75it/s]

 33%|███▎      | 33466/100629 [26:29<44:27, 25.18it/s]

 33%|███▎      | 33469/100629 [26:29<48:56, 22.87it/s]

 33%|███▎      | 33472/100629 [26:29<45:44, 24.47it/s]

 33%|███▎      | 33476/100629 [26:29<42:28, 26.35it/s]

 33%|███▎      | 33480/100629 [26:29<38:57, 28.73it/s]

 33%|███▎      | 33484/100629 [26:29<42:00, 26.63it/s]

 33%|███▎      | 33490/100629 [26:29<34:03, 32.86it/s]

 33%|███▎      | 33494/100629 [26:30<51:21, 21.79it/s]

 33%|███▎      | 33497/100629 [26:30<52:16, 21.41it/s]

 33%|███▎      | 33500/100629 [26:30<50:39, 22.08it/s]

 33%|███▎      | 33504/100629 [26:30<50:56, 21.96it/s]

 33%|███▎      | 33507/100629 [26:30<1:01:03, 18.32it/s]

 33%|███▎      | 33511/100629 [26:31<52:43, 21.22it/s]

 33%|███▎      | 33514/100629 [26:31<55:13, 20.25it/s]

 33%|███▎      | 33517/100629 [26:31<56:27, 19.81it/s]

 33%|███▎      | 33521/100629 [26:31<47:23, 23.60it/s]

 33%|███▎      | 33524/100629 [26:31<50:00, 22.36it/s]

 33%|███▎      | 33527/100629 [26:31<53:01, 21.09it/s]

 33%|███▎      | 33530/100629 [26:31<55:07, 20.29it/s]

 33%|███▎      | 33533/100629 [26:32<53:16, 20.99it/s]

 33%|███▎      | 33539/100629 [26:32<41:56, 26.66it/s]

 33%|███▎      | 33542/100629 [26:32<44:42, 25.01it/s]

 33%|███▎      | 33546/100629 [26:32<47:07, 23.73it/s]

 33%|███▎      | 33549/100629 [26:32<56:57, 19.63it/s]

 33%|███▎      | 33552/100629 [26:32<59:45, 18.71it/s]

 33%|███▎      | 33555/100629 [26:33<54:20, 20.57it/s]

 33%|███▎      | 33558/100629 [26:33<49:48, 22.45it/s]

 33%|███▎      | 33561/100629 [26:33<51:25, 21.73it/s]

 33%|███▎      | 33564/100629 [26:33<53:11, 21.02it/s]

 33%|███▎      | 33567/100629 [26:33<54:20, 20.57it/s]

 33%|███▎      | 33571/100629 [26:33<47:08, 23.71it/s]

 33%|███▎      | 33575/100629 [26:33<47:59, 23.28it/s]

 33%|███▎      | 33578/100629 [26:34<49:04, 22.77it/s]

 33%|███▎      | 33581/100629 [26:34<49:20, 22.65it/s]

 33%|███▎      | 33584/100629 [26:34<51:15, 21.80it/s]

 33%|███▎      | 33587/100629 [26:34<48:44, 22.93it/s]

 33%|███▎      | 33591/100629 [26:34<44:36, 25.05it/s]

 33%|███▎      | 33595/100629 [26:34<42:43, 26.15it/s]

 33%|███▎      | 33598/100629 [26:34<43:35, 25.63it/s]

 33%|███▎      | 33601/100629 [26:35<1:02:38, 17.83it/s]

 33%|███▎      | 33604/100629 [26:35<1:05:51, 16.96it/s]

 33%|███▎      | 33606/100629 [26:35<1:05:33, 17.04it/s]

 33%|███▎      | 33609/100629 [26:35<1:06:20, 16.84it/s]

 33%|███▎      | 33612/100629 [26:35<1:00:01, 18.61it/s]

 33%|███▎      | 33616/100629 [26:35<51:29, 21.69it/s]

 33%|███▎      | 33620/100629 [26:36<45:49, 24.37it/s]

 33%|███▎      | 33623/100629 [26:36<44:47, 24.93it/s]

 33%|███▎      | 33626/100629 [26:36<49:30, 22.56it/s]

 33%|███▎      | 33629/100629 [26:36<55:00, 20.30it/s]

 33%|███▎      | 33632/100629 [26:36<1:16:14, 14.65it/s]

 33%|███▎      | 33635/100629 [26:36<1:06:56, 16.68it/s]

 33%|███▎      | 33639/100629 [26:37<53:47, 20.75it/s]

 33%|███▎      | 33642/100629 [26:37<56:49, 19.65it/s]

 33%|███▎      | 33645/100629 [26:37<1:01:28, 18.16it/s]

 33%|███▎      | 33648/100629 [26:37<1:00:08, 18.56it/s]

 33%|███▎      | 33652/100629 [26:37<52:18, 21.34it/s]

 33%|███▎      | 33655/100629 [26:37<48:38, 22.95it/s]

 33%|███▎      | 33659/100629 [26:38<46:36, 23.95it/s]

 33%|███▎      | 33662/100629 [26:38<45:26, 24.56it/s]

 33%|███▎      | 33666/100629 [26:38<43:03, 25.92it/s]

 33%|███▎      | 33669/100629 [26:38<47:37, 23.44it/s]

 33%|███▎      | 33673/100629 [26:38<44:40, 24.98it/s]

 33%|███▎      | 33676/100629 [26:38<46:46, 23.86it/s]

 33%|███▎      | 33679/100629 [26:38<46:07, 24.19it/s]

 33%|███▎      | 33683/100629 [26:38<42:55, 26.00it/s]

 33%|███▎      | 33686/100629 [26:39<48:58, 22.78it/s]

 33%|███▎      | 33689/100629 [26:39<53:38, 20.80it/s]

 33%|███▎      | 33692/100629 [26:39<49:58, 22.33it/s]

 33%|███▎      | 33695/100629 [26:39<46:59, 23.74it/s]

 33%|███▎      | 33698/100629 [26:39<48:02, 23.22it/s]

 33%|███▎      | 33701/100629 [26:39<51:03, 21.85it/s]

 33%|███▎      | 33705/100629 [26:39<45:44, 24.39it/s]

 33%|███▎      | 33708/100629 [26:40<55:40, 20.03it/s]

 34%|███▎      | 33712/100629 [26:40<46:29, 23.99it/s]

 34%|███▎      | 33716/100629 [26:40<45:56, 24.27it/s]

 34%|███▎      | 33719/100629 [26:40<44:09, 25.25it/s]

 34%|███▎      | 33722/100629 [26:40<48:15, 23.11it/s]

 34%|███▎      | 33726/100629 [26:40<42:32, 26.21it/s]

 34%|███▎      | 33729/100629 [26:40<41:10, 27.08it/s]

 34%|███▎      | 33732/100629 [26:41<41:52, 26.63it/s]

 34%|███▎      | 33735/100629 [26:41<43:54, 25.39it/s]

 34%|███▎      | 33738/100629 [26:41<51:51, 21.50it/s]

 34%|███▎      | 33741/100629 [26:41<53:32, 20.82it/s]

 34%|███▎      | 33745/100629 [26:41<47:10, 23.63it/s]

 34%|███▎      | 33748/100629 [26:41<56:44, 19.64it/s]

 34%|███▎      | 33751/100629 [26:42<1:14:44, 14.91it/s]

 34%|███▎      | 33753/100629 [26:42<1:17:14, 14.43it/s]

 34%|███▎      | 33755/100629 [26:42<1:13:52, 15.09it/s]

 34%|███▎      | 33758/100629 [26:42<1:05:52, 16.92it/s]

 34%|███▎      | 33760/100629 [26:42<1:03:45, 17.48it/s]

 34%|███▎      | 33762/100629 [26:42<1:05:51, 16.92it/s]

 34%|███▎      | 33765/100629 [26:42<55:56, 19.92it/s]

 34%|███▎      | 33770/100629 [26:43<45:17, 24.61it/s]

 34%|███▎      | 33773/100629 [26:43<45:10, 24.67it/s]

 34%|███▎      | 33776/100629 [26:43<52:58, 21.04it/s]

 34%|███▎      | 33779/100629 [26:43<48:41, 22.88it/s]

 34%|███▎      | 33782/100629 [26:43<50:54, 21.88it/s]

 34%|███▎      | 33785/100629 [26:43<57:26, 19.39it/s]

 34%|███▎      | 33788/100629 [26:43<54:27, 20.46it/s]

 34%|███▎      | 33793/100629 [26:44<44:44, 24.90it/s]

 34%|███▎      | 33797/100629 [26:44<40:36, 27.43it/s]

 34%|███▎      | 33800/100629 [26:44<47:03, 23.67it/s]

 34%|███▎      | 33803/100629 [26:44<45:05, 24.70it/s]

 34%|███▎      | 33807/100629 [26:44<40:03, 27.80it/s]

 34%|███▎      | 33810/100629 [26:44<44:48, 24.85it/s]

 34%|███▎      | 33813/100629 [26:44<45:16, 24.60it/s]

 34%|███▎      | 33816/100629 [26:45<49:56, 22.30it/s]

 34%|███▎      | 33819/100629 [26:45<56:24, 19.74it/s]

 34%|███▎      | 33822/100629 [26:45<56:39, 19.65it/s]

 34%|███▎      | 33825/100629 [26:45<52:41, 21.13it/s]

 34%|███▎      | 33828/100629 [26:45<51:37, 21.56it/s]

 34%|███▎      | 33831/100629 [26:45<56:46, 19.61it/s]

 34%|███▎      | 33835/100629 [26:45<52:14, 21.31it/s]

 34%|███▎      | 33838/100629 [26:46<55:48, 19.95it/s]

 34%|███▎      | 33841/100629 [26:46<56:01, 19.87it/s]

 34%|███▎      | 33845/100629 [26:46<47:21, 23.50it/s]

 34%|███▎      | 33848/100629 [26:46<59:24, 18.74it/s]

 34%|███▎      | 33851/100629 [26:46<58:21, 19.07it/s]

 34%|███▎      | 33854/100629 [26:46<55:24, 20.09it/s]

 34%|███▎      | 33857/100629 [26:47<56:26, 19.72it/s]

 34%|███▎      | 33860/100629 [26:47<54:25, 20.45it/s]

 34%|███▎      | 33863/100629 [26:47<50:23, 22.09it/s]

 34%|███▎      | 33866/100629 [26:47<48:30, 22.94it/s]

 34%|███▎      | 33869/100629 [26:47<52:30, 21.19it/s]

 34%|███▎      | 33873/100629 [26:47<45:23, 24.51it/s]

 34%|███▎      | 33876/100629 [26:47<44:22, 25.07it/s]

 34%|███▎      | 33880/100629 [26:47<41:14, 26.97it/s]

 34%|███▎      | 33883/100629 [26:48<41:08, 27.04it/s]

 34%|███▎      | 33886/100629 [26:48<44:52, 24.79it/s]

 34%|███▎      | 33889/100629 [26:48<53:22, 20.84it/s]

 34%|███▎      | 33892/100629 [26:48<50:45, 21.91it/s]

 34%|███▎      | 33897/100629 [26:48<44:04, 25.24it/s]

 34%|███▎      | 33900/100629 [26:48<49:22, 22.52it/s]

 34%|███▎      | 33903/100629 [26:49<1:03:36, 17.48it/s]

 34%|███▎      | 33905/100629 [26:49<1:17:39, 14.32it/s]

 34%|███▎      | 33907/100629 [26:49<1:13:36, 15.11it/s]

 34%|███▎      | 33909/100629 [26:49<1:11:38, 15.52it/s]

 34%|███▎      | 33913/100629 [26:49<59:23, 18.72it/s]

 34%|███▎      | 33916/100629 [26:49<54:46, 20.30it/s]

 34%|███▎      | 33919/100629 [26:50<54:13, 20.51it/s]

 34%|███▎      | 33923/100629 [26:50<50:37, 21.96it/s]

 34%|███▎      | 33926/100629 [26:50<47:44, 23.29it/s]

 34%|███▎      | 33929/100629 [26:50<52:33, 21.15it/s]

 34%|███▎      | 33932/100629 [26:50<51:43, 21.49it/s]

 34%|███▎      | 33935/100629 [26:50<53:12, 20.89it/s]

 34%|███▎      | 33938/100629 [26:50<56:53, 19.54it/s]

 34%|███▎      | 33940/100629 [26:51<57:20, 19.38it/s]

 34%|███▎      | 33943/100629 [26:51<51:57, 21.39it/s]

 34%|███▎      | 33946/100629 [26:51<1:06:43, 16.66it/s]

 34%|███▎      | 33950/100629 [26:51<53:23, 20.81it/s]

 34%|███▎      | 33953/100629 [26:51<58:32, 18.98it/s]

 34%|███▎      | 33956/100629 [26:51<56:24, 19.70it/s]

 34%|███▎      | 33959/100629 [26:52<1:02:13, 17.86it/s]

 34%|███▎      | 33962/100629 [26:52<1:06:12, 16.78it/s]

 34%|███▍      | 33966/100629 [26:52<53:59, 20.58it/s]

 34%|███▍      | 33970/100629 [26:52<45:53, 24.21it/s]

 34%|███▍      | 33974/100629 [26:52<42:35, 26.08it/s]

 34%|███▍      | 33978/100629 [26:52<39:10, 28.35it/s]

 34%|███▍      | 33982/100629 [26:52<36:11, 30.69it/s]

 34%|███▍      | 33986/100629 [26:52<33:36, 33.05it/s]

 34%|███▍      | 33990/100629 [26:53<41:35, 26.71it/s]

 34%|███▍      | 33994/100629 [26:53<40:03, 27.72it/s]

 34%|███▍      | 33998/100629 [26:53<39:06, 28.40it/s]

 34%|███▍      | 34003/100629 [26:53<34:02, 32.63it/s]

 34%|███▍      | 34007/100629 [26:53<50:32, 21.97it/s]

 34%|███▍      | 34010/100629 [26:54<48:53, 22.71it/s]

 34%|███▍      | 34013/100629 [26:54<50:28, 21.99it/s]

 34%|███▍      | 34016/100629 [26:54<46:55, 23.66it/s]

 34%|███▍      | 34019/100629 [26:54<46:07, 24.07it/s]

 34%|███▍      | 34022/100629 [26:54<53:19, 20.82it/s]

 34%|███▍      | 34026/100629 [26:54<46:29, 23.88it/s]

 34%|███▍      | 34029/100629 [26:54<59:25, 18.68it/s]

 34%|███▍      | 34032/100629 [26:55<53:25, 20.77it/s]

 34%|███▍      | 34035/100629 [26:55<1:02:50, 17.66it/s]

 34%|███▍      | 34038/100629 [26:55<59:13, 18.74it/s]

 34%|███▍      | 34041/100629 [26:55<1:00:00, 18.49it/s]

 34%|███▍      | 34044/100629 [26:55<56:51, 19.52it/s]

 34%|███▍      | 34047/100629 [26:55<53:56, 20.57it/s]

 34%|███▍      | 34050/100629 [26:55<53:43, 20.65it/s]

 34%|███▍      | 34053/100629 [26:56<55:22, 20.04it/s]

 34%|███▍      | 34056/100629 [26:56<54:09, 20.49it/s]

 34%|███▍      | 34059/100629 [26:56<52:58, 20.95it/s]

 34%|███▍      | 34062/100629 [26:56<55:50, 19.87it/s]

 34%|███▍      | 34065/100629 [26:56<1:05:43, 16.88it/s]

 34%|███▍      | 34068/100629 [26:56<1:01:33, 18.02it/s]

 34%|███▍      | 34072/100629 [26:57<59:28, 18.65it/s]

 34%|███▍      | 34076/100629 [26:57<49:40, 22.33it/s]

 34%|███▍      | 34080/100629 [26:57<44:15, 25.06it/s]

 34%|███▍      | 34084/100629 [26:57<43:29, 25.50it/s]

 34%|███▍      | 34087/100629 [26:57<54:31, 20.34it/s]

 34%|███▍      | 34090/100629 [26:57<57:56, 19.14it/s]

 34%|███▍      | 34094/100629 [26:58<51:51, 21.38it/s]

 34%|███▍      | 34097/100629 [26:58<49:26, 22.43it/s]

 34%|███▍      | 34100/100629 [26:58<48:54, 22.67it/s]

 34%|███▍      | 34103/100629 [26:58<46:20, 23.92it/s]

 34%|███▍      | 34106/100629 [26:58<45:09, 24.55it/s]

 34%|███▍      | 34110/100629 [26:58<40:12, 27.57it/s]

 34%|███▍      | 34113/100629 [26:58<42:33, 26.05it/s]

 34%|███▍      | 34117/100629 [26:58<39:20, 28.18it/s]

 34%|███▍      | 34120/100629 [26:59<43:34, 25.43it/s]

 34%|███▍      | 34123/100629 [26:59<43:34, 25.44it/s]

 34%|███▍      | 34126/100629 [26:59<44:52, 24.70it/s]

 34%|███▍      | 34130/100629 [26:59<42:44, 25.93it/s]

 34%|███▍      | 34134/100629 [26:59<39:37, 27.96it/s]

 34%|███▍      | 34137/100629 [26:59<48:07, 23.02it/s]

 34%|███▍      | 34140/100629 [27:00<1:00:05, 18.44it/s]

 34%|███▍      | 34143/100629 [27:00<55:04, 20.12it/s]

 34%|███▍      | 34146/100629 [27:00<50:29, 21.94it/s]

 34%|███▍      | 34149/100629 [27:00<49:38, 22.32it/s]

 34%|███▍      | 34152/100629 [27:00<49:00, 22.61it/s]

 34%|███▍      | 34155/100629 [27:00<1:02:03, 17.85it/s]

 34%|███▍      | 34158/100629 [27:00<1:03:53, 17.34it/s]

 34%|███▍      | 34163/100629 [27:01<48:00, 23.07it/s]

 34%|███▍      | 34168/100629 [27:01<40:02, 27.66it/s]

 34%|███▍      | 34172/100629 [27:01<44:15, 25.03it/s]

 34%|███▍      | 34175/100629 [27:01<46:37, 23.76it/s]

 34%|███▍      | 34178/100629 [27:01<44:32, 24.86it/s]

 34%|███▍      | 34182/100629 [27:01<43:18, 25.57it/s]

 34%|███▍      | 34185/100629 [27:01<50:13, 22.05it/s]

 34%|███▍      | 34190/100629 [27:02<42:50, 25.85it/s]

 34%|███▍      | 34193/100629 [27:02<48:24, 22.87it/s]

 34%|███▍      | 34196/100629 [27:02<51:32, 21.48it/s]

 34%|███▍      | 34199/100629 [27:02<57:34, 19.23it/s]

 34%|███▍      | 34202/100629 [27:02<56:17, 19.67it/s]

 34%|███▍      | 34205/100629 [27:02<54:29, 20.31it/s]

 34%|███▍      | 34208/100629 [27:03<50:15, 22.03it/s]

 34%|███▍      | 34211/100629 [27:03<48:59, 22.59it/s]

 34%|███▍      | 34214/100629 [27:03<1:08:22, 16.19it/s]

 34%|███▍      | 34218/100629 [27:03<55:16, 20.02it/s]

 34%|███▍      | 34221/100629 [27:03<53:10, 20.82it/s]

 34%|███▍      | 34225/100629 [27:03<46:13, 23.94it/s]

 34%|███▍      | 34228/100629 [27:04<51:11, 21.62it/s]

 34%|███▍      | 34232/100629 [27:04<48:33, 22.79it/s]

 34%|███▍      | 34235/100629 [27:04<49:51, 22.19it/s]

 34%|███▍      | 34239/100629 [27:04<45:30, 24.32it/s]

 34%|███▍      | 34243/100629 [27:04<39:56, 27.70it/s]

 34%|███▍      | 34246/100629 [27:04<45:42, 24.21it/s]

 34%|███▍      | 34249/100629 [27:04<45:05, 24.54it/s]

 34%|███▍      | 34252/100629 [27:05<51:21, 21.54it/s]

 34%|███▍      | 34255/100629 [27:05<53:40, 20.61it/s]

 34%|███▍      | 34258/100629 [27:05<51:21, 21.54it/s]

 34%|███▍      | 34263/100629 [27:05<42:59, 25.73it/s]

 34%|███▍      | 34268/100629 [27:05<40:34, 27.26it/s]

 34%|███▍      | 34271/100629 [27:05<41:48, 26.45it/s]

 34%|███▍      | 34275/100629 [27:05<44:00, 25.13it/s]

 34%|███▍      | 34278/100629 [27:06<42:17, 26.15it/s]

 34%|███▍      | 34281/100629 [27:06<43:33, 25.38it/s]

 34%|███▍      | 34285/100629 [27:06<42:23, 26.09it/s]

 34%|███▍      | 34288/100629 [27:06<43:42, 25.30it/s]

 34%|███▍      | 34291/100629 [27:06<48:17, 22.90it/s]

 34%|███▍      | 34294/100629 [27:06<49:51, 22.18it/s]

 34%|███▍      | 34297/100629 [27:06<46:30, 23.77it/s]

 34%|███▍      | 34301/100629 [27:06<40:40, 27.18it/s]

 34%|███▍      | 34304/100629 [27:07<53:26, 20.68it/s]

 34%|███▍      | 34307/100629 [27:07<56:18, 19.63it/s]

 34%|███▍      | 34310/100629 [27:07<1:05:40, 16.83it/s]

 34%|███▍      | 34313/100629 [27:07<1:00:25, 18.29it/s]

 34%|███▍      | 34318/100629 [27:07<46:46, 23.63it/s]

 34%|███▍      | 34321/100629 [27:08<52:35, 21.01it/s]

 34%|███▍      | 34324/100629 [27:08<53:15, 20.75it/s]

 34%|███▍      | 34327/100629 [27:08<56:41, 19.49it/s]

 34%|███▍      | 34330/100629 [27:08<53:43, 20.56it/s]

 34%|███▍      | 34333/100629 [27:08<50:10, 22.02it/s]

 34%|███▍      | 34336/100629 [27:08<56:33, 19.54it/s]

 34%|███▍      | 34339/100629 [27:08<52:33, 21.02it/s]

 34%|███▍      | 34342/100629 [27:09<1:03:16, 17.46it/s]

 34%|███▍      | 34344/100629 [27:09<1:02:23, 17.71it/s]

 34%|███▍      | 34348/100629 [27:09<49:28, 22.33it/s]

 34%|███▍      | 34351/100629 [27:09<47:08, 23.43it/s]

 34%|███▍      | 34354/100629 [27:09<49:10, 22.46it/s]

 34%|███▍      | 34357/100629 [27:09<48:42, 22.68it/s]

 34%|███▍      | 34360/100629 [27:09<59:42, 18.50it/s]

 34%|███▍      | 34363/100629 [27:10<53:10, 20.77it/s]

 34%|███▍      | 34367/100629 [27:10<46:44, 23.62it/s]

 34%|███▍      | 34370/100629 [27:10<58:13, 18.97it/s]

 34%|███▍      | 34373/100629 [27:10<1:01:31, 17.95it/s]

 34%|███▍      | 34376/100629 [27:10<56:04, 19.69it/s]

 34%|███▍      | 34379/100629 [27:10<55:48, 19.79it/s]

 34%|███▍      | 34382/100629 [27:11<1:09:52, 15.80it/s]

 34%|███▍      | 34385/100629 [27:11<1:00:45, 18.17it/s]

 34%|███▍      | 34388/100629 [27:11<59:27, 18.57it/s]

 34%|███▍      | 34391/100629 [27:11<54:53, 20.11it/s]

 34%|███▍      | 34394/100629 [27:11<59:29, 18.56it/s]

 34%|███▍      | 34398/100629 [27:11<55:41, 19.82it/s]

 34%|███▍      | 34401/100629 [27:12<56:15, 19.62it/s]

 34%|███▍      | 34404/100629 [27:12<1:01:38, 17.91it/s]

 34%|███▍      | 34407/100629 [27:12<58:32, 18.85it/s]

 34%|███▍      | 34409/100629 [27:12<1:00:17, 18.30it/s]

 34%|███▍      | 34411/100629 [27:12<59:10, 18.65it/s]

 34%|███▍      | 34413/100629 [27:12<1:02:28, 17.66it/s]

 34%|███▍      | 34416/100629 [27:12<1:00:28, 18.25it/s]

 34%|███▍      | 34418/100629 [27:13<59:35, 18.52it/s]

 34%|███▍      | 34420/100629 [27:13<59:04, 18.68it/s]

 34%|███▍      | 34423/100629 [27:13<56:24, 19.56it/s]

 34%|███▍      | 34427/100629 [27:13<47:25, 23.26it/s]

 34%|███▍      | 34430/100629 [27:13<1:02:23, 17.68it/s]

 34%|███▍      | 34433/100629 [27:13<58:01, 19.01it/s]

 34%|███▍      | 34436/100629 [27:14<1:01:15, 18.01it/s]

 34%|███▍      | 34438/100629 [27:14<1:04:45, 17.04it/s]

 34%|███▍      | 34441/100629 [27:14<57:57, 19.03it/s]

 34%|███▍      | 34444/100629 [27:14<56:51, 19.40it/s]

 34%|███▍      | 34447/100629 [27:14<1:08:57, 15.99it/s]

 34%|███▍      | 34451/100629 [27:14<1:01:54, 17.82it/s]

 34%|███▍      | 34453/100629 [27:14<1:04:07, 17.20it/s]

 34%|███▍      | 34456/100629 [27:15<1:00:07, 18.34it/s]

 34%|███▍      | 34458/100629 [27:15<59:19, 18.59it/s]

 34%|███▍      | 34461/100629 [27:15<1:03:15, 17.43it/s]

 34%|███▍      | 34464/100629 [27:15<57:18, 19.24it/s]

 34%|███▍      | 34467/100629 [27:15<51:04, 21.59it/s]

 34%|███▍      | 34470/100629 [27:15<50:14, 21.95it/s]

 34%|███▍      | 34475/100629 [27:15<39:38, 27.82it/s]

 34%|███▍      | 34479/100629 [27:16<37:41, 29.25it/s]

 34%|███▍      | 34483/100629 [27:16<40:45, 27.04it/s]

 34%|███▍      | 34488/100629 [27:16<35:24, 31.14it/s]

 34%|███▍      | 34492/100629 [27:16<37:18, 29.55it/s]

 34%|███▍      | 34496/100629 [27:16<36:54, 29.86it/s]

 34%|███▍      | 34500/100629 [27:16<34:31, 31.93it/s]

 34%|███▍      | 34504/100629 [27:16<41:26, 26.59it/s]

 34%|███▍      | 34507/100629 [27:17<43:33, 25.30it/s]

 34%|███▍      | 34510/100629 [27:17<48:05, 22.91it/s]

 34%|███▍      | 34513/100629 [27:17<48:36, 22.67it/s]

 34%|███▍      | 34516/100629 [27:17<53:55, 20.43it/s]

 34%|███▍      | 34520/100629 [27:17<47:03, 23.41it/s]

 34%|███▍      | 34523/100629 [27:17<46:30, 23.69it/s]

 34%|███▍      | 34526/100629 [27:18<1:01:29, 17.91it/s]

 34%|███▍      | 34529/100629 [27:18<59:12, 18.60it/s]

 34%|███▍      | 34533/100629 [27:18<53:00, 20.78it/s]

 34%|███▍      | 34536/100629 [27:18<49:55, 22.06it/s]

 34%|███▍      | 34539/100629 [27:18<46:33, 23.66it/s]

 34%|███▍      | 34542/100629 [27:18<47:25, 23.23it/s]

 34%|███▍      | 34545/100629 [27:18<48:46, 22.58it/s]

 34%|███▍      | 34548/100629 [27:18<49:19, 22.33it/s]

 34%|███▍      | 34551/100629 [27:19<50:37, 21.76it/s]

 34%|███▍      | 34554/100629 [27:19<49:42, 22.15it/s]

 34%|███▍      | 34557/100629 [27:19<48:34, 22.67it/s]

 34%|███▍      | 34560/100629 [27:19<51:20, 21.45it/s]

 34%|███▍      | 34564/100629 [27:19<42:52, 25.68it/s]

 34%|███▍      | 34567/100629 [27:19<50:21, 21.86it/s]

 34%|███▍      | 34570/100629 [27:19<50:17, 21.89it/s]

 34%|███▍      | 34575/100629 [27:20<41:22, 26.61it/s]

 34%|███▍      | 34578/100629 [27:20<40:42, 27.04it/s]

 34%|███▍      | 34583/100629 [27:20<35:40, 30.86it/s]

 34%|███▍      | 34587/100629 [27:20<43:34, 25.26it/s]

 34%|███▍      | 34590/100629 [27:20<46:26, 23.70it/s]

 34%|███▍      | 34593/100629 [27:20<47:59, 22.93it/s]

 34%|███▍      | 34596/100629 [27:20<49:00, 22.45it/s]

 34%|███▍      | 34599/100629 [27:21<47:49, 23.01it/s]

 34%|███▍      | 34602/100629 [27:21<47:03, 23.39it/s]

 34%|███▍      | 34605/100629 [27:21<46:44, 23.54it/s]

 34%|███▍      | 34608/100629 [27:21<1:02:51, 17.51it/s]

 34%|███▍      | 34611/100629 [27:21<1:18:25, 14.03it/s]

 34%|███▍      | 34613/100629 [27:22<1:19:41, 13.81it/s]

 34%|███▍      | 34617/100629 [27:22<1:05:53, 16.70it/s]

 34%|███▍      | 34619/100629 [27:22<1:04:18, 17.11it/s]

 34%|███▍      | 34622/100629 [27:22<55:42, 19.75it/s]

 34%|███▍      | 34625/100629 [27:22<54:45, 20.09it/s]

 34%|███▍      | 34628/100629 [27:22<54:23, 20.22it/s]

 34%|███▍      | 34631/100629 [27:22<51:20, 21.43it/s]

 34%|███▍      | 34634/100629 [27:23<49:37, 22.17it/s]

 34%|███▍      | 34637/100629 [27:23<46:10, 23.82it/s]

 34%|███▍      | 34641/100629 [27:23<39:41, 27.71it/s]

 34%|███▍      | 34644/100629 [27:23<42:35, 25.82it/s]

 34%|███▍      | 34647/100629 [27:23<43:47, 25.11it/s]

 34%|███▍      | 34651/100629 [27:23<42:48, 25.69it/s]

 34%|███▍      | 34654/100629 [27:23<45:11, 24.33it/s]

 34%|███▍      | 34657/100629 [27:23<45:39, 24.08it/s]

 34%|███▍      | 34660/100629 [27:24<46:26, 23.67it/s]

 34%|███▍      | 34663/100629 [27:24<49:09, 22.36it/s]

 34%|███▍      | 34666/100629 [27:24<57:45, 19.03it/s]

 34%|███▍      | 34669/100629 [27:24<52:18, 21.02it/s]

 34%|███▍      | 34672/100629 [27:24<50:55, 21.58it/s]

 34%|███▍      | 34675/100629 [27:24<53:35, 20.51it/s]

 34%|███▍      | 34680/100629 [27:25<51:59, 21.14it/s]

 34%|███▍      | 34683/100629 [27:25<50:05, 21.94it/s]

 34%|███▍      | 34687/100629 [27:25<47:29, 23.15it/s]

 34%|███▍      | 34691/100629 [27:25<45:13, 24.30it/s]

 34%|███▍      | 34694/100629 [27:25<57:24, 19.14it/s]

 34%|███▍      | 34697/100629 [27:25<55:00, 19.98it/s]

 34%|███▍      | 34700/100629 [27:25<56:34, 19.42it/s]

 34%|███▍      | 34703/100629 [27:26<55:09, 19.92it/s]

 34%|███▍      | 34706/100629 [27:26<51:36, 21.29it/s]

 34%|███▍      | 34710/100629 [27:26<43:48, 25.08it/s]

 34%|███▍      | 34713/100629 [27:26<51:02, 21.52it/s]

 34%|███▍      | 34716/100629 [27:26<50:59, 21.54it/s]

 35%|███▍      | 34719/100629 [27:26<51:00, 21.53it/s]

 35%|███▍      | 34723/100629 [27:27<50:30, 21.75it/s]

 35%|███▍      | 34726/100629 [27:27<53:18, 20.60it/s]

 35%|███▍      | 34729/100629 [27:27<1:01:28, 17.87it/s]

 35%|███▍      | 34731/100629 [27:27<1:00:51, 18.04it/s]

 35%|███▍      | 34734/100629 [27:27<55:02, 19.95it/s]

 35%|███▍      | 34737/100629 [27:27<57:11, 19.20it/s]

 35%|███▍      | 34739/100629 [27:27<59:21, 18.50it/s]

 35%|███▍      | 34742/100629 [27:28<54:35, 20.11it/s]

 35%|███▍      | 34745/100629 [27:28<54:06, 20.29it/s]

 35%|███▍      | 34748/100629 [27:28<58:01, 18.92it/s]

 35%|███▍      | 34751/100629 [27:28<56:05, 19.57it/s]

 35%|███▍      | 34753/100629 [27:28<1:00:23, 18.18it/s]

 35%|███▍      | 34756/100629 [27:28<55:55, 19.63it/s]

 35%|███▍      | 34759/100629 [27:28<52:43, 20.82it/s]

 35%|███▍      | 34764/100629 [27:29<47:16, 23.22it/s]

 35%|███▍      | 34767/100629 [27:29<1:05:51, 16.67it/s]

 35%|███▍      | 34770/100629 [27:29<59:38, 18.41it/s]

 35%|███▍      | 34773/100629 [27:29<1:03:54, 17.18it/s]

 35%|███▍      | 34775/100629 [27:29<1:10:03, 15.66it/s]

 35%|███▍      | 34779/100629 [27:30<1:00:09, 18.24it/s]

 35%|███▍      | 34782/100629 [27:30<54:56, 19.97it/s]

 35%|███▍      | 34786/100629 [27:30<47:02, 23.33it/s]

 35%|███▍      | 34789/100629 [27:30<50:25, 21.76it/s]

 35%|███▍      | 34792/100629 [27:30<53:19, 20.58it/s]

 35%|███▍      | 34796/100629 [27:30<44:46, 24.50it/s]

 35%|███▍      | 34800/100629 [27:30<42:45, 25.66it/s]

 35%|███▍      | 34803/100629 [27:30<41:44, 26.28it/s]

 35%|███▍      | 34806/100629 [27:31<1:11:02, 15.44it/s]

 35%|███▍      | 34809/100629 [27:31<1:06:54, 16.40it/s]

 35%|███▍      | 34812/100629 [27:31<59:16, 18.51it/s]

 35%|███▍      | 34815/100629 [27:31<1:01:47, 17.75it/s]

 35%|███▍      | 34818/100629 [27:31<1:01:52, 17.73it/s]

 35%|███▍      | 34821/100629 [27:32<57:27, 19.09it/s]

 35%|███▍      | 34826/100629 [27:32<47:24, 23.14it/s]

 35%|███▍      | 34829/100629 [27:32<54:46, 20.02it/s]

 35%|███▍      | 34832/100629 [27:32<52:02, 21.07it/s]

 35%|███▍      | 34835/100629 [27:32<57:50, 18.96it/s]

 35%|███▍      | 34838/100629 [27:32<53:24, 20.53it/s]

 35%|███▍      | 34841/100629 [27:33<53:37, 20.45it/s]

 35%|███▍      | 34844/100629 [27:33<49:05, 22.33it/s]

 35%|███▍      | 34847/100629 [27:33<1:02:22, 17.58it/s]

 35%|███▍      | 34850/100629 [27:33<1:01:34, 17.80it/s]

 35%|███▍      | 34853/100629 [27:33<55:12, 19.86it/s]

 35%|███▍      | 34856/100629 [27:33<1:04:44, 16.93it/s]

 35%|███▍      | 34858/100629 [27:34<1:04:00, 17.13it/s]

 35%|███▍      | 34860/100629 [27:34<1:06:29, 16.49it/s]

 35%|███▍      | 34862/100629 [27:34<1:04:41, 16.94it/s]

 35%|███▍      | 34864/100629 [27:34<1:08:58, 15.89it/s]

 35%|███▍      | 34868/100629 [27:34<52:39, 20.82it/s]

 35%|███▍      | 34872/100629 [27:34<44:09, 24.82it/s]

 35%|███▍      | 34876/100629 [27:34<46:15, 23.69it/s]

 35%|███▍      | 34880/100629 [27:34<44:12, 24.79it/s]

 35%|███▍      | 34883/100629 [27:35<47:58, 22.84it/s]

 35%|███▍      | 34886/100629 [27:35<50:41, 21.62it/s]

 35%|███▍      | 34890/100629 [27:35<47:50, 22.90it/s]

 35%|███▍      | 34893/100629 [27:35<53:06, 20.63it/s]

 35%|███▍      | 34896/100629 [27:35<1:01:39, 17.77it/s]

 35%|███▍      | 34898/100629 [27:35<1:00:23, 18.14it/s]

 35%|███▍      | 34900/100629 [27:36<1:00:23, 18.14it/s]

 35%|███▍      | 34904/100629 [27:36<49:05, 22.31it/s]

 35%|███▍      | 34908/100629 [27:36<44:59, 24.34it/s]

 35%|███▍      | 34911/100629 [27:36<48:40, 22.50it/s]

 35%|███▍      | 34916/100629 [27:36<40:09, 27.28it/s]

 35%|███▍      | 34919/100629 [27:36<50:51, 21.53it/s]

 35%|███▍      | 34922/100629 [27:36<50:07, 21.84it/s]

 35%|███▍      | 34925/100629 [27:37<47:03, 23.27it/s]

 35%|███▍      | 34928/100629 [27:37<48:46, 22.45it/s]

 35%|███▍      | 34931/100629 [27:37<48:17, 22.68it/s]

 35%|███▍      | 34934/100629 [27:37<50:56, 21.49it/s]

 35%|███▍      | 34937/100629 [27:37<53:25, 20.50it/s]

 35%|███▍      | 34940/100629 [27:37<1:02:48, 17.43it/s]

 35%|███▍      | 34943/100629 [27:38<55:45, 19.63it/s]

 35%|███▍      | 34946/100629 [27:38<1:05:15, 16.78it/s]

 35%|███▍      | 34950/100629 [27:38<51:45, 21.15it/s]

 35%|███▍      | 34953/100629 [27:38<1:05:32, 16.70it/s]

 35%|███▍      | 34958/100629 [27:38<50:36, 21.63it/s]

 35%|███▍      | 34961/100629 [27:38<53:11, 20.58it/s]

 35%|███▍      | 34964/100629 [27:39<57:14, 19.12it/s]

 35%|███▍      | 34967/100629 [27:39<58:02, 18.85it/s]

 35%|███▍      | 34971/100629 [27:39<48:48, 22.42it/s]

 35%|███▍      | 34975/100629 [27:39<45:09, 24.23it/s]

 35%|███▍      | 34978/100629 [27:39<51:01, 21.44it/s]

 35%|███▍      | 34983/100629 [27:39<40:07, 27.27it/s]

 35%|███▍      | 34987/100629 [27:39<39:51, 27.45it/s]

 35%|███▍      | 34991/100629 [27:40<39:58, 27.36it/s]

 35%|███▍      | 34994/100629 [27:40<44:20, 24.67it/s]

 35%|███▍      | 34999/100629 [27:40<38:12, 28.63it/s]

 35%|███▍      | 35004/100629 [27:40<38:15, 28.59it/s]

 35%|███▍      | 35008/100629 [27:40<38:31, 28.39it/s]

 35%|███▍      | 35011/100629 [27:40<41:21, 26.44it/s]

 35%|███▍      | 35014/100629 [27:40<41:14, 26.52it/s]

 35%|███▍      | 35017/100629 [27:41<41:04, 26.62it/s]

 35%|███▍      | 35020/100629 [27:41<48:23, 22.59it/s]

 35%|███▍      | 35023/100629 [27:41<47:02, 23.24it/s]

 35%|███▍      | 35027/100629 [27:41<44:58, 24.31it/s]

 35%|███▍      | 35033/100629 [27:41<40:03, 27.29it/s]

 35%|███▍      | 35036/100629 [27:41<49:01, 22.30it/s]

 35%|███▍      | 35039/100629 [27:42<49:46, 21.96it/s]

 35%|███▍      | 35042/100629 [27:42<50:50, 21.50it/s]

 35%|███▍      | 35045/100629 [27:42<49:20, 22.15it/s]

 35%|███▍      | 35048/100629 [27:42<50:17, 21.74it/s]

 35%|███▍      | 35051/100629 [27:42<57:42, 18.94it/s]

 35%|███▍      | 35053/100629 [27:42<58:57, 18.54it/s]

 35%|███▍      | 35055/100629 [27:43<1:07:31, 16.19it/s]

 35%|███▍      | 35057/100629 [27:43<1:06:35, 16.41it/s]

 35%|███▍      | 35060/100629 [27:43<57:26, 19.03it/s]

 35%|███▍      | 35062/100629 [27:43<57:53, 18.88it/s]

 35%|███▍      | 35066/100629 [27:43<45:28, 24.03it/s]

 35%|███▍      | 35069/100629 [27:43<44:31, 24.54it/s]

 35%|███▍      | 35072/100629 [27:43<47:55, 22.80it/s]

 35%|███▍      | 35075/100629 [27:43<53:55, 20.26it/s]

 35%|███▍      | 35079/100629 [27:44<50:06, 21.81it/s]

 35%|███▍      | 35082/100629 [27:44<52:06, 20.97it/s]

 35%|███▍      | 35086/100629 [27:44<48:09, 22.68it/s]

 35%|███▍      | 35089/100629 [27:44<51:39, 21.15it/s]

 35%|███▍      | 35092/100629 [27:44<48:49, 22.37it/s]

 35%|███▍      | 35095/100629 [27:44<47:07, 23.18it/s]

 35%|███▍      | 35098/100629 [27:44<45:14, 24.14it/s]

 35%|███▍      | 35101/100629 [27:44<44:07, 24.75it/s]

 35%|███▍      | 35105/100629 [27:45<44:03, 24.79it/s]

 35%|███▍      | 35108/100629 [27:45<44:19, 24.63it/s]

 35%|███▍      | 35111/100629 [27:45<42:35, 25.64it/s]

 35%|███▍      | 35115/100629 [27:45<39:54, 27.36it/s]

 35%|███▍      | 35118/100629 [27:45<52:21, 20.85it/s]

 35%|███▍      | 35121/100629 [27:45<49:38, 21.99it/s]

 35%|███▍      | 35124/100629 [27:46<50:24, 21.66it/s]

 35%|███▍      | 35128/100629 [27:46<48:46, 22.38it/s]

 35%|███▍      | 35131/100629 [27:46<50:14, 21.73it/s]

 35%|███▍      | 35134/100629 [27:46<46:53, 23.28it/s]

 35%|███▍      | 35137/100629 [27:46<50:19, 21.69it/s]

 35%|███▍      | 35140/100629 [27:46<46:53, 23.28it/s]

 35%|███▍      | 35143/100629 [27:46<55:00, 19.84it/s]

 35%|███▍      | 35146/100629 [27:47<54:35, 19.99it/s]

 35%|███▍      | 35149/100629 [27:47<54:06, 20.17it/s]

 35%|███▍      | 35152/100629 [27:47<57:36, 18.94it/s]

 35%|███▍      | 35156/100629 [27:47<48:50, 22.34it/s]

 35%|███▍      | 35159/100629 [27:47<55:07, 19.79it/s]

 35%|███▍      | 35162/100629 [27:47<1:02:31, 17.45it/s]

 35%|███▍      | 35164/100629 [27:48<1:07:46, 16.10it/s]

 35%|███▍      | 35167/100629 [27:48<1:10:19, 15.52it/s]

 35%|███▍      | 35172/100629 [27:48<53:56, 20.23it/s]

 35%|███▍      | 35176/100629 [27:48<51:29, 21.19it/s]

 35%|███▍      | 35179/100629 [27:48<49:43, 21.94it/s]

 35%|███▍      | 35182/100629 [27:48<49:30, 22.03it/s]

 35%|███▍      | 35185/100629 [27:48<46:37, 23.39it/s]

 35%|███▍      | 35188/100629 [27:49<49:53, 21.86it/s]

 35%|███▍      | 35191/100629 [27:49<52:45, 20.67it/s]

 35%|███▍      | 35194/100629 [27:49<54:52, 19.87it/s]

 35%|███▍      | 35197/100629 [27:49<50:36, 21.55it/s]

 35%|███▍      | 35200/100629 [27:49<51:10, 21.31it/s]

 35%|███▍      | 35203/100629 [27:49<50:29, 21.60it/s]

 35%|███▍      | 35206/100629 [27:50<1:03:35, 17.15it/s]

 35%|███▍      | 35208/100629 [27:50<1:02:23, 17.48it/s]

 35%|███▍      | 35211/100629 [27:50<54:12, 20.11it/s]

 35%|███▍      | 35214/100629 [27:50<50:41, 21.51it/s]

 35%|███▍      | 35217/100629 [27:50<50:10, 21.73it/s]

 35%|███▍      | 35220/100629 [27:50<47:34, 22.91it/s]

 35%|███▌      | 35223/100629 [27:50<51:43, 21.08it/s]

 35%|███▌      | 35226/100629 [27:51<52:47, 20.65it/s]

 35%|███▌      | 35229/100629 [27:51<55:13, 19.74it/s]

 35%|███▌      | 35233/100629 [27:51<48:43, 22.37it/s]

 35%|███▌      | 35236/100629 [27:51<48:33, 22.45it/s]

 35%|███▌      | 35239/100629 [27:51<51:34, 21.13it/s]

 35%|███▌      | 35243/100629 [27:51<44:43, 24.37it/s]

 35%|███▌      | 35246/100629 [27:51<47:36, 22.89it/s]

 35%|███▌      | 35249/100629 [27:52<50:33, 21.55it/s]

 35%|███▌      | 35252/100629 [27:52<52:07, 20.91it/s]

 35%|███▌      | 35255/100629 [27:52<48:44, 22.35it/s]

 35%|███▌      | 35258/100629 [27:52<57:26, 18.97it/s]

 35%|███▌      | 35261/100629 [27:52<55:14, 19.72it/s]

 35%|███▌      | 35264/100629 [27:52<1:05:44, 16.57it/s]

 35%|███▌      | 35267/100629 [27:53<1:01:01, 17.85it/s]

 35%|███▌      | 35270/100629 [27:53<55:08, 19.76it/s]

 35%|███▌      | 35274/100629 [27:53<47:23, 22.98it/s]

 35%|███▌      | 35277/100629 [27:53<49:16, 22.11it/s]

 35%|███▌      | 35280/100629 [27:53<55:40, 19.57it/s]

 35%|███▌      | 35284/100629 [27:53<46:41, 23.33it/s]

 35%|███▌      | 35287/100629 [27:53<43:57, 24.78it/s]

 35%|███▌      | 35291/100629 [27:53<42:02, 25.91it/s]

 35%|███▌      | 35294/100629 [27:54<42:23, 25.69it/s]

 35%|███▌      | 35297/100629 [27:54<52:46, 20.63it/s]

 35%|███▌      | 35301/100629 [27:54<45:10, 24.10it/s]

 35%|███▌      | 35304/100629 [27:54<48:20, 22.52it/s]

 35%|███▌      | 35307/100629 [27:54<52:28, 20.75it/s]

 35%|███▌      | 35310/100629 [27:54<54:27, 19.99it/s]

 35%|███▌      | 35313/100629 [27:55<58:21, 18.65it/s]

 35%|███▌      | 35316/100629 [27:55<54:41, 19.90it/s]

 35%|███▌      | 35319/100629 [27:55<57:35, 18.90it/s]

 35%|███▌      | 35322/100629 [27:55<54:24, 20.01it/s]

 35%|███▌      | 35325/100629 [27:55<52:51, 20.59it/s]

 35%|███▌      | 35328/100629 [27:55<49:36, 21.94it/s]

 35%|███▌      | 35331/100629 [27:55<48:32, 22.42it/s]

 35%|███▌      | 35334/100629 [27:56<45:25, 23.96it/s]

 35%|███▌      | 35337/100629 [27:56<50:33, 21.52it/s]

 35%|███▌      | 35341/100629 [27:56<43:53, 24.79it/s]

 35%|███▌      | 35345/100629 [27:56<46:17, 23.51it/s]

 35%|███▌      | 35348/100629 [27:56<50:42, 21.46it/s]

 35%|███▌      | 35351/100629 [27:56<49:50, 21.83it/s]

 35%|███▌      | 35354/100629 [27:57<56:23, 19.29it/s]

 35%|███▌      | 35357/100629 [27:57<58:41, 18.54it/s]

 35%|███▌      | 35361/100629 [27:57<47:35, 22.86it/s]

 35%|███▌      | 35364/100629 [27:57<48:43, 22.33it/s]

 35%|███▌      | 35367/100629 [27:57<48:36, 22.37it/s]

 35%|███▌      | 35370/100629 [27:57<46:57, 23.16it/s]

 35%|███▌      | 35373/100629 [27:57<58:01, 18.74it/s]

 35%|███▌      | 35376/100629 [27:58<58:47, 18.50it/s]

 35%|███▌      | 35378/100629 [27:58<58:40, 18.54it/s]

 35%|███▌      | 35380/100629 [27:58<1:02:09, 17.49it/s]

 35%|███▌      | 35382/100629 [27:58<1:10:07, 15.51it/s]

 35%|███▌      | 35385/100629 [27:58<1:06:19, 16.39it/s]

 35%|███▌      | 35387/100629 [27:58<1:06:53, 16.25it/s]

 35%|███▌      | 35390/100629 [27:58<57:19, 18.97it/s]

 35%|███▌      | 35392/100629 [27:59<1:03:36, 17.09it/s]

 35%|███▌      | 35394/100629 [27:59<1:02:26, 17.41it/s]

 35%|███▌      | 35397/100629 [27:59<55:09, 19.71it/s]

 35%|███▌      | 35400/100629 [27:59<1:10:43, 15.37it/s]

 35%|███▌      | 35402/100629 [27:59<1:09:30, 15.64it/s]

 35%|███▌      | 35406/100629 [27:59<52:24, 20.74it/s]

 35%|███▌      | 35409/100629 [27:59<55:17, 19.66it/s]

 35%|███▌      | 35412/100629 [28:00<1:01:41, 17.62it/s]

 35%|███▌      | 35414/100629 [28:00<1:02:39, 17.35it/s]

 35%|███▌      | 35416/100629 [28:00<1:05:27, 16.60it/s]

 35%|███▌      | 35419/100629 [28:00<56:31, 19.23it/s]

 35%|███▌      | 35422/100629 [28:00<56:01, 19.40it/s]

 35%|███▌      | 35425/100629 [28:00<56:47, 19.14it/s]

 35%|███▌      | 35429/100629 [28:01<57:11, 19.00it/s]

 35%|███▌      | 35431/100629 [28:01<59:55, 18.14it/s]

 35%|███▌      | 35433/100629 [28:01<1:00:50, 17.86it/s]

 35%|███▌      | 35436/100629 [28:01<55:54, 19.43it/s]

 35%|███▌      | 35438/100629 [28:01<1:04:34, 16.83it/s]

 35%|███▌      | 35441/100629 [28:01<57:40, 18.84it/s]

 35%|███▌      | 35444/100629 [28:01<59:24, 18.29it/s]

 35%|███▌      | 35446/100629 [28:02<1:00:46, 17.87it/s]

 35%|███▌      | 35448/100629 [28:02<1:07:15, 16.15it/s]

 35%|███▌      | 35450/100629 [28:02<1:04:51, 16.75it/s]

 35%|███▌      | 35454/100629 [28:02<52:01, 20.88it/s]

 35%|███▌      | 35457/100629 [28:02<51:19, 21.16it/s]

 35%|███▌      | 35460/100629 [28:02<59:00, 18.41it/s]

 35%|███▌      | 35462/100629 [28:02<1:03:39, 17.06it/s]

 35%|███▌      | 35464/100629 [28:03<1:03:56, 16.98it/s]

 35%|███▌      | 35466/100629 [28:03<1:02:24, 17.40it/s]

 35%|███▌      | 35469/100629 [28:03<1:01:44, 17.59it/s]

 35%|███▌      | 35471/100629 [28:03<1:05:56, 16.47it/s]

 35%|███▌      | 35473/100629 [28:03<1:02:55, 17.26it/s]

 35%|███▌      | 35476/100629 [28:03<55:24, 19.60it/s]

 35%|███▌      | 35479/100629 [28:03<49:57, 21.74it/s]

 35%|███▌      | 35482/100629 [28:03<50:14, 21.61it/s]

 35%|███▌      | 35485/100629 [28:04<45:47, 23.71it/s]

 35%|███▌      | 35489/100629 [28:04<47:02, 23.08it/s]

 35%|███▌      | 35492/100629 [28:04<52:45, 20.58it/s]

 35%|███▌      | 35495/100629 [28:04<50:23, 21.54it/s]

 35%|███▌      | 35498/100629 [28:04<51:15, 21.18it/s]

 35%|███▌      | 35501/100629 [28:04<58:35, 18.53it/s]

 35%|███▌      | 35506/100629 [28:05<48:16, 22.48it/s]

 35%|███▌      | 35509/100629 [28:05<49:28, 21.94it/s]

 35%|███▌      | 35512/100629 [28:05<51:00, 21.28it/s]

 35%|███▌      | 35515/100629 [28:05<51:41, 20.99it/s]

 35%|███▌      | 35518/100629 [28:05<49:47, 21.79it/s]

 35%|███▌      | 35523/100629 [28:05<43:53, 24.72it/s]

 35%|███▌      | 35526/100629 [28:05<43:45, 24.80it/s]

 35%|███▌      | 35529/100629 [28:05<44:00, 24.66it/s]

 35%|███▌      | 35532/100629 [28:06<43:44, 24.80it/s]

 35%|███▌      | 35535/100629 [28:06<46:25, 23.37it/s]

 35%|███▌      | 35538/100629 [28:06<46:45, 23.20it/s]

 35%|███▌      | 35541/100629 [28:06<43:53, 24.72it/s]

 35%|███▌      | 35544/100629 [28:06<46:44, 23.20it/s]

 35%|███▌      | 35547/100629 [28:06<47:00, 23.08it/s]

 35%|███▌      | 35550/100629 [28:06<53:47, 20.16it/s]

 35%|███▌      | 35556/100629 [28:07<41:20, 26.23it/s]

 35%|███▌      | 35559/100629 [28:07<44:47, 24.21it/s]

 35%|███▌      | 35562/100629 [28:07<45:51, 23.65it/s]

 35%|███▌      | 35565/100629 [28:07<48:21, 22.43it/s]

 35%|███▌      | 35568/100629 [28:07<51:38, 21.00it/s]

 35%|███▌      | 35571/100629 [28:07<52:08, 20.80it/s]

 35%|███▌      | 35574/100629 [28:08<58:23, 18.57it/s]

 35%|███▌      | 35576/100629 [28:08<1:06:27, 16.32it/s]

 35%|███▌      | 35580/100629 [28:08<54:27, 19.91it/s]

 35%|███▌      | 35584/100629 [28:08<49:56, 21.71it/s]

 35%|███▌      | 35588/100629 [28:08<47:08, 22.99it/s]

 35%|███▌      | 35591/100629 [28:08<47:57, 22.60it/s]

 35%|███▌      | 35594/100629 [28:08<49:29, 21.90it/s]

 35%|███▌      | 35597/100629 [28:09<52:24, 20.68it/s]

 35%|███▌      | 35601/100629 [28:09<44:14, 24.50it/s]

 35%|███▌      | 35605/100629 [28:09<40:14, 26.93it/s]

 35%|███▌      | 35608/100629 [28:09<45:07, 24.01it/s]

 35%|███▌      | 35611/100629 [28:09<48:45, 22.22it/s]

 35%|███▌      | 35614/100629 [28:09<52:00, 20.84it/s]

 35%|███▌      | 35617/100629 [28:09<50:10, 21.60it/s]

 35%|███▌      | 35620/100629 [28:10<47:27, 22.83it/s]

 35%|███▌      | 35624/100629 [28:10<44:43, 24.23it/s]

 35%|███▌      | 35627/100629 [28:10<45:13, 23.96it/s]

 35%|███▌      | 35630/100629 [28:10<44:01, 24.61it/s]

 35%|███▌      | 35633/100629 [28:10<55:57, 19.36it/s]

 35%|███▌      | 35636/100629 [28:10<1:05:46, 16.47it/s]

 35%|███▌      | 35640/100629 [28:11<55:18, 19.58it/s]

 35%|███▌      | 35643/100629 [28:11<57:48, 18.74it/s]

 35%|███▌      | 35646/100629 [28:11<54:26, 19.89it/s]

 35%|███▌      | 35649/100629 [28:11<51:14, 21.13it/s]

 35%|███▌      | 35652/100629 [28:11<52:19, 20.70it/s]

 35%|███▌      | 35656/100629 [28:11<46:50, 23.12it/s]

 35%|███▌      | 35659/100629 [28:12<59:10, 18.30it/s]

 35%|███▌      | 35664/100629 [28:12<52:37, 20.57it/s]

 35%|███▌      | 35667/100629 [28:12<57:24, 18.86it/s]

 35%|███▌      | 35671/100629 [28:12<50:27, 21.46it/s]

 35%|███▌      | 35674/100629 [28:12<54:55, 19.71it/s]

 35%|███▌      | 35677/100629 [28:12<56:18, 19.22it/s]

 35%|███▌      | 35679/100629 [28:13<57:24, 18.86it/s]

 35%|███▌      | 35681/100629 [28:13<1:04:43, 16.72it/s]

 35%|███▌      | 35684/100629 [28:13<58:29, 18.51it/s]

 35%|███▌      | 35686/100629 [28:13<58:29, 18.50it/s]

 35%|███▌      | 35689/100629 [28:13<51:57, 20.83it/s]

 35%|███▌      | 35692/100629 [28:13<49:21, 21.92it/s]

 35%|███▌      | 35695/100629 [28:13<45:22, 23.85it/s]

 35%|███▌      | 35698/100629 [28:13<49:04, 22.05it/s]

 35%|███▌      | 35701/100629 [28:14<55:34, 19.47it/s]

 35%|███▌      | 35704/100629 [28:14<50:03, 21.62it/s]

 35%|███▌      | 35707/100629 [28:14<57:23, 18.86it/s]

 35%|███▌      | 35711/100629 [28:14<53:26, 20.25it/s]

 35%|███▌      | 35714/100629 [28:14<1:03:57, 16.91it/s]

 35%|███▌      | 35717/100629 [28:15<1:00:07, 17.99it/s]

 35%|███▌      | 35719/100629 [28:15<1:00:06, 18.00it/s]

 35%|███▌      | 35722/100629 [28:15<56:13, 19.24it/s]

 36%|███▌      | 35725/100629 [28:15<53:02, 20.39it/s]

 36%|███▌      | 35728/100629 [28:15<49:37, 21.79it/s]

 36%|███▌      | 35731/100629 [28:15<55:02, 19.65it/s]

 36%|███▌      | 35734/100629 [28:15<57:45, 18.72it/s]

 36%|███▌      | 35737/100629 [28:16<55:15, 19.57it/s]

 36%|███▌      | 35740/100629 [28:16<53:05, 20.37it/s]

 36%|███▌      | 35744/100629 [28:16<46:15, 23.38it/s]

 36%|███▌      | 35747/100629 [28:16<48:21, 22.36it/s]

 36%|███▌      | 35750/100629 [28:16<52:16, 20.69it/s]

 36%|███▌      | 35754/100629 [28:16<43:40, 24.76it/s]

 36%|███▌      | 35757/100629 [28:16<42:40, 25.33it/s]

 36%|███▌      | 35760/100629 [28:16<45:18, 23.86it/s]

 36%|███▌      | 35763/100629 [28:17<48:52, 22.12it/s]

 36%|███▌      | 35766/100629 [28:17<45:27, 23.78it/s]

 36%|███▌      | 35769/100629 [28:17<48:27, 22.31it/s]

 36%|███▌      | 35774/100629 [28:17<40:19, 26.81it/s]

 36%|███▌      | 35777/100629 [28:17<45:25, 23.79it/s]

 36%|███▌      | 35780/100629 [28:17<47:40, 22.67it/s]

 36%|███▌      | 35783/100629 [28:18<54:54, 19.68it/s]

 36%|███▌      | 35787/100629 [28:18<48:55, 22.09it/s]

 36%|███▌      | 35790/100629 [28:18<48:29, 22.28it/s]

 36%|███▌      | 35793/100629 [28:18<48:43, 22.18it/s]

 36%|███▌      | 35796/100629 [28:18<51:51, 20.84it/s]

 36%|███▌      | 35799/100629 [28:18<52:21, 20.64it/s]

 36%|███▌      | 35802/100629 [28:18<54:02, 20.00it/s]

 36%|███▌      | 35806/100629 [28:19<46:01, 23.47it/s]

 36%|███▌      | 35809/100629 [28:19<46:08, 23.42it/s]

 36%|███▌      | 35812/100629 [28:19<47:19, 22.83it/s]

 36%|███▌      | 35816/100629 [28:19<47:20, 22.82it/s]

 36%|███▌      | 35820/100629 [28:19<43:25, 24.88it/s]

 36%|███▌      | 35824/100629 [28:19<42:38, 25.33it/s]

 36%|███▌      | 35828/100629 [28:19<42:54, 25.17it/s]

 36%|███▌      | 35831/100629 [28:20<58:23, 18.50it/s]

 36%|███▌      | 35834/100629 [28:20<57:19, 18.84it/s]

 36%|███▌      | 35837/100629 [28:20<54:45, 19.72it/s]

 36%|███▌      | 35841/100629 [28:20<52:27, 20.58it/s]

 36%|███▌      | 35844/100629 [28:20<53:36, 20.14it/s]

 36%|███▌      | 35847/100629 [28:20<55:17, 19.53it/s]

 36%|███▌      | 35850/100629 [28:21<1:01:09, 17.65it/s]

 36%|███▌      | 35854/100629 [28:21<52:47, 20.45it/s]

 36%|███▌      | 35857/100629 [28:21<51:56, 20.78it/s]

 36%|███▌      | 35860/100629 [28:21<59:55, 18.01it/s]

 36%|███▌      | 35863/100629 [28:21<1:05:28, 16.48it/s]

 36%|███▌      | 35866/100629 [28:22<57:34, 18.75it/s]

 36%|███▌      | 35869/100629 [28:22<58:04, 18.59it/s]

 36%|███▌      | 35872/100629 [28:22<55:38, 19.40it/s]

 36%|███▌      | 35875/100629 [28:22<55:00, 19.62it/s]

 36%|███▌      | 35880/100629 [28:22<41:43, 25.86it/s]

 36%|███▌      | 35883/100629 [28:22<46:59, 22.96it/s]

 36%|███▌      | 35888/100629 [28:22<40:04, 26.93it/s]

 36%|███▌      | 35891/100629 [28:23<48:13, 22.37it/s]

 36%|███▌      | 35894/100629 [28:23<51:17, 21.03it/s]

 36%|███▌      | 35898/100629 [28:23<44:30, 24.24it/s]

 36%|███▌      | 35901/100629 [28:23<46:17, 23.30it/s]

 36%|███▌      | 35904/100629 [28:23<45:41, 23.61it/s]

 36%|███▌      | 35907/100629 [28:23<43:05, 25.03it/s]

 36%|███▌      | 35910/100629 [28:23<50:31, 21.35it/s]

 36%|███▌      | 35913/100629 [28:24<57:04, 18.90it/s]

 36%|███▌      | 35916/100629 [28:24<1:10:10, 15.37it/s]

 36%|███▌      | 35919/100629 [28:24<1:05:28, 16.47it/s]

 36%|███▌      | 35922/100629 [28:24<59:03, 18.26it/s]

 36%|███▌      | 35925/100629 [28:24<56:01, 19.25it/s]

 36%|███▌      | 35928/100629 [28:24<52:53, 20.39it/s]

 36%|███▌      | 35931/100629 [28:25<56:45, 19.00it/s]

 36%|███▌      | 35935/100629 [28:25<52:40, 20.47it/s]

 36%|███▌      | 35938/100629 [28:25<51:40, 20.86it/s]

 36%|███▌      | 35941/100629 [28:25<57:02, 18.90it/s]

 36%|███▌      | 35943/100629 [28:25<59:17, 18.18it/s]

 36%|███▌      | 35946/100629 [28:25<52:27, 20.55it/s]

 36%|███▌      | 35949/100629 [28:25<47:36, 22.64it/s]

 36%|███▌      | 35952/100629 [28:26<44:16, 24.35it/s]

 36%|███▌      | 35955/100629 [28:26<43:00, 25.07it/s]

 36%|███▌      | 35958/100629 [28:26<48:30, 22.22it/s]

 36%|███▌      | 35961/100629 [28:26<50:38, 21.29it/s]

 36%|███▌      | 35966/100629 [28:26<40:50, 26.39it/s]

 36%|███▌      | 35969/100629 [28:26<44:53, 24.00it/s]

 36%|███▌      | 35972/100629 [28:26<45:38, 23.61it/s]

 36%|███▌      | 35975/100629 [28:27<52:15, 20.62it/s]

 36%|███▌      | 35978/100629 [28:27<54:56, 19.61it/s]

 36%|███▌      | 35983/100629 [28:27<43:44, 24.63it/s]

 36%|███▌      | 35986/100629 [28:27<42:27, 25.37it/s]

 36%|███▌      | 35989/100629 [28:27<46:44, 23.05it/s]

 36%|███▌      | 35992/100629 [28:27<44:14, 24.35it/s]

 36%|███▌      | 35997/100629 [28:27<35:33, 30.29it/s]

 36%|███▌      | 36002/100629 [28:28<32:07, 33.53it/s]

 36%|███▌      | 36006/100629 [28:28<41:29, 25.96it/s]

 36%|███▌      | 36009/100629 [28:28<50:24, 21.36it/s]

 36%|███▌      | 36012/100629 [28:28<47:49, 22.52it/s]

 36%|███▌      | 36015/100629 [28:28<49:28, 21.77it/s]

 36%|███▌      | 36018/100629 [28:28<46:11, 23.31it/s]

 36%|███▌      | 36021/100629 [28:28<45:05, 23.88it/s]

 36%|███▌      | 36024/100629 [28:29<48:39, 22.13it/s]

 36%|███▌      | 36027/100629 [28:29<52:41, 20.43it/s]

 36%|███▌      | 36030/100629 [28:29<1:04:22, 16.72it/s]

 36%|███▌      | 36032/100629 [28:29<1:06:26, 16.20it/s]

 36%|███▌      | 36036/100629 [28:29<54:25, 19.78it/s]

 36%|███▌      | 36039/100629 [28:29<57:04, 18.86it/s]

 36%|███▌      | 36042/100629 [28:30<54:02, 19.92it/s]

 36%|███▌      | 36045/100629 [28:30<51:48, 20.78it/s]

 36%|███▌      | 36048/100629 [28:30<48:04, 22.39it/s]

 36%|███▌      | 36051/100629 [28:30<47:59, 22.43it/s]

 36%|███▌      | 36054/100629 [28:30<45:32, 23.63it/s]

 36%|███▌      | 36059/100629 [28:30<37:33, 28.65it/s]

 36%|███▌      | 36064/100629 [28:30<35:30, 30.31it/s]

 36%|███▌      | 36068/100629 [28:31<38:38, 27.84it/s]

 36%|███▌      | 36071/100629 [28:31<39:34, 27.19it/s]

 36%|███▌      | 36074/100629 [28:31<45:56, 23.42it/s]

 36%|███▌      | 36077/100629 [28:31<55:19, 19.45it/s]

 36%|███▌      | 36080/100629 [28:31<52:13, 20.60it/s]

 36%|███▌      | 36083/100629 [28:31<56:21, 19.09it/s]

 36%|███▌      | 36086/100629 [28:32<1:08:14, 15.76it/s]

 36%|███▌      | 36088/100629 [28:32<1:07:42, 15.89it/s]

 36%|███▌      | 36090/100629 [28:32<1:07:38, 15.90it/s]

 36%|███▌      | 36092/100629 [28:32<1:15:51, 14.18it/s]

 36%|███▌      | 36094/100629 [28:32<1:10:28, 15.26it/s]

 36%|███▌      | 36096/100629 [28:32<1:08:11, 15.77it/s]

 36%|███▌      | 36099/100629 [28:32<58:37, 18.35it/s]

 36%|███▌      | 36102/100629 [28:33<54:18, 19.80it/s]

 36%|███▌      | 36105/100629 [28:33<57:41, 18.64it/s]

 36%|███▌      | 36109/100629 [28:33<51:39, 20.81it/s]

 36%|███▌      | 36112/100629 [28:33<47:33, 22.61it/s]

 36%|███▌      | 36116/100629 [28:33<44:35, 24.11it/s]

 36%|███▌      | 36119/100629 [28:33<45:23, 23.69it/s]

 36%|███▌      | 36122/100629 [28:33<48:41, 22.08it/s]

 36%|███▌      | 36125/100629 [28:34<45:56, 23.40it/s]

 36%|███▌      | 36128/100629 [28:34<52:14, 20.58it/s]

 36%|███▌      | 36131/100629 [28:34<52:11, 20.60it/s]

 36%|███▌      | 36134/100629 [28:34<51:18, 20.95it/s]

 36%|███▌      | 36137/100629 [28:34<53:22, 20.14it/s]

 36%|███▌      | 36140/100629 [28:34<52:44, 20.38it/s]

 36%|███▌      | 36143/100629 [28:35<1:00:42, 17.71it/s]

 36%|███▌      | 36146/100629 [28:35<55:39, 19.31it/s]

 36%|███▌      | 36149/100629 [28:35<57:25, 18.71it/s]

 36%|███▌      | 36152/100629 [28:35<51:27, 20.88it/s]

 36%|███▌      | 36155/100629 [28:35<47:59, 22.39it/s]

 36%|███▌      | 36158/100629 [28:35<47:19, 22.71it/s]

 36%|███▌      | 36161/100629 [28:35<44:32, 24.13it/s]

 36%|███▌      | 36164/100629 [28:35<45:11, 23.78it/s]

 36%|███▌      | 36167/100629 [28:36<44:23, 24.21it/s]

 36%|███▌      | 36171/100629 [28:36<44:00, 24.42it/s]

 36%|███▌      | 36174/100629 [28:36<45:03, 23.84it/s]

 36%|███▌      | 36177/100629 [28:36<49:35, 21.66it/s]

 36%|███▌      | 36180/100629 [28:36<48:59, 21.92it/s]

 36%|███▌      | 36183/100629 [28:36<45:55, 23.38it/s]

 36%|███▌      | 36186/100629 [28:36<43:10, 24.88it/s]

 36%|███▌      | 36190/100629 [28:36<41:43, 25.74it/s]

 36%|███▌      | 36193/100629 [28:37<47:46, 22.48it/s]

 36%|███▌      | 36196/100629 [28:37<46:12, 23.24it/s]

 36%|███▌      | 36199/100629 [28:37<45:18, 23.70it/s]

 36%|███▌      | 36202/100629 [28:37<43:36, 24.62it/s]

 36%|███▌      | 36205/100629 [28:37<44:46, 23.98it/s]

 36%|███▌      | 36208/100629 [28:37<45:51, 23.42it/s]

 36%|███▌      | 36211/100629 [28:37<45:00, 23.86it/s]

 36%|███▌      | 36215/100629 [28:38<41:50, 25.66it/s]

 36%|███▌      | 36218/100629 [28:38<41:41, 25.75it/s]

 36%|███▌      | 36221/100629 [28:38<41:01, 26.17it/s]

 36%|███▌      | 36224/100629 [28:38<49:07, 21.85it/s]

 36%|███▌      | 36228/100629 [28:38<43:48, 24.50it/s]

 36%|███▌      | 36231/100629 [28:38<50:27, 21.27it/s]

 36%|███▌      | 36234/100629 [28:38<57:13, 18.75it/s]

 36%|███▌      | 36238/100629 [28:39<49:14, 21.80it/s]

 36%|███▌      | 36241/100629 [28:39<48:55, 21.93it/s]

 36%|███▌      | 36244/100629 [28:39<1:00:00, 17.88it/s]

 36%|███▌      | 36247/100629 [28:39<1:05:09, 16.47it/s]

 36%|███▌      | 36251/100629 [28:39<51:41, 20.76it/s]

 36%|███▌      | 36254/100629 [28:39<55:55, 19.18it/s]

 36%|███▌      | 36257/100629 [28:40<55:51, 19.21it/s]

 36%|███▌      | 36261/100629 [28:40<49:38, 21.61it/s]

 36%|███▌      | 36264/100629 [28:40<52:48, 20.32it/s]

 36%|███▌      | 36267/100629 [28:40<50:11, 21.37it/s]

 36%|███▌      | 36270/100629 [28:40<51:14, 20.93it/s]

 36%|███▌      | 36273/100629 [28:40<49:12, 21.80it/s]

 36%|███▌      | 36276/100629 [28:40<47:11, 22.73it/s]

 36%|███▌      | 36280/100629 [28:41<40:51, 26.25it/s]

 36%|███▌      | 36283/100629 [28:41<42:52, 25.01it/s]

 36%|███▌      | 36286/100629 [28:41<46:13, 23.20it/s]

 36%|███▌      | 36289/100629 [28:41<46:24, 23.11it/s]

 36%|███▌      | 36292/100629 [28:41<49:34, 21.63it/s]

 36%|███▌      | 36295/100629 [28:41<56:21, 19.03it/s]

 36%|███▌      | 36298/100629 [28:41<50:34, 21.20it/s]

 36%|███▌      | 36301/100629 [28:42<49:23, 21.70it/s]

 36%|███▌      | 36304/100629 [28:42<49:18, 21.74it/s]

 36%|███▌      | 36307/100629 [28:42<53:58, 19.86it/s]

 36%|███▌      | 36311/100629 [28:42<44:44, 23.96it/s]

 36%|███▌      | 36314/100629 [28:42<51:47, 20.69it/s]

 36%|███▌      | 36317/100629 [28:42<57:23, 18.68it/s]

 36%|███▌      | 36320/100629 [28:43<1:01:07, 17.53it/s]

 36%|███▌      | 36322/100629 [28:43<1:04:32, 16.61it/s]

 36%|███▌      | 36326/100629 [28:43<51:16, 20.90it/s]

 36%|███▌      | 36329/100629 [28:43<56:27, 18.98it/s]

 36%|███▌      | 36333/100629 [28:43<52:32, 20.39it/s]

 36%|███▌      | 36336/100629 [28:43<52:06, 20.56it/s]

 36%|███▌      | 36339/100629 [28:43<47:38, 22.49it/s]

 36%|███▌      | 36342/100629 [28:44<50:34, 21.18it/s]

 36%|███▌      | 36345/100629 [28:44<51:13, 20.91it/s]

 36%|███▌      | 36348/100629 [28:44<47:00, 22.79it/s]

 36%|███▌      | 36351/100629 [28:44<45:26, 23.57it/s]

 36%|███▌      | 36355/100629 [28:44<40:41, 26.33it/s]

 36%|███▌      | 36358/100629 [28:44<41:59, 25.51it/s]

 36%|███▌      | 36362/100629 [28:44<39:58, 26.80it/s]

 36%|███▌      | 36365/100629 [28:45<42:23, 25.26it/s]

 36%|███▌      | 36369/100629 [28:45<39:45, 26.94it/s]

 36%|███▌      | 36372/100629 [28:45<39:49, 26.90it/s]

 36%|███▌      | 36375/100629 [28:45<53:32, 20.00it/s]

 36%|███▌      | 36378/100629 [28:45<52:16, 20.49it/s]

 36%|███▌      | 36382/100629 [28:45<43:59, 24.34it/s]

 36%|███▌      | 36385/100629 [28:45<48:44, 21.97it/s]

 36%|███▌      | 36388/100629 [28:46<46:34, 22.99it/s]

 36%|███▌      | 36391/100629 [28:46<46:27, 23.04it/s]

 36%|███▌      | 36395/100629 [28:46<43:54, 24.38it/s]

 36%|███▌      | 36399/100629 [28:46<38:54, 27.51it/s]

 36%|███▌      | 36402/100629 [28:46<50:14, 21.31it/s]

 36%|███▌      | 36405/100629 [28:46<48:56, 21.87it/s]

 36%|███▌      | 36408/100629 [28:46<50:16, 21.29it/s]

 36%|███▌      | 36411/100629 [28:47<50:25, 21.23it/s]

 36%|███▌      | 36414/100629 [28:47<48:53, 21.89it/s]

 36%|███▌      | 36417/100629 [28:47<57:48, 18.51it/s]

 36%|███▌      | 36420/100629 [28:47<56:22, 18.98it/s]

 36%|███▌      | 36422/100629 [28:47<1:01:22, 17.44it/s]

 36%|███▌      | 36424/100629 [28:47<1:02:22, 17.16it/s]

 36%|███▌      | 36426/100629 [28:47<1:04:44, 16.53it/s]

 36%|███▌      | 36429/100629 [28:48<1:05:12, 16.41it/s]

 36%|███▌      | 36433/100629 [28:48<52:05, 20.54it/s]

 36%|███▌      | 36436/100629 [28:48<50:03, 21.38it/s]

 36%|███▌      | 36439/100629 [28:48<46:20, 23.09it/s]

 36%|███▌      | 36445/100629 [28:48<36:22, 29.41it/s]

 36%|███▌      | 36449/100629 [28:48<34:00, 31.45it/s]

 36%|███▌      | 36453/100629 [28:49<42:00, 25.46it/s]

 36%|███▌      | 36456/100629 [28:49<50:17, 21.27it/s]

 36%|███▌      | 36459/100629 [28:49<47:31, 22.50it/s]

 36%|███▌      | 36462/100629 [28:49<54:04, 19.78it/s]

 36%|███▌      | 36465/100629 [28:49<50:55, 21.00it/s]

 36%|███▌      | 36468/100629 [28:49<1:03:41, 16.79it/s]

 36%|███▌      | 36470/100629 [28:50<1:03:35, 16.81it/s]

 36%|███▌      | 36472/100629 [28:50<1:21:57, 13.05it/s]

 36%|███▌      | 36475/100629 [28:50<1:09:23, 15.41it/s]

 36%|███▌      | 36477/100629 [28:50<1:13:53, 14.47it/s]

 36%|███▋      | 36480/100629 [28:50<1:00:56, 17.55it/s]

 36%|███▋      | 36483/100629 [28:50<53:22, 20.03it/s]

 36%|███▋      | 36486/100629 [28:50<57:09, 18.70it/s]

 36%|███▋      | 36489/100629 [28:51<59:06, 18.09it/s]

 36%|███▋      | 36492/100629 [28:51<52:38, 20.30it/s]

 36%|███▋      | 36495/100629 [28:51<1:01:25, 17.40it/s]

 36%|███▋      | 36498/100629 [28:51<57:38, 18.54it/s]

 36%|███▋      | 36501/100629 [28:51<54:47, 19.51it/s]

 36%|███▋      | 36504/100629 [28:51<51:14, 20.86it/s]

 36%|███▋      | 36507/100629 [28:52<50:10, 21.30it/s]

 36%|███▋      | 36510/100629 [28:52<49:27, 21.61it/s]

 36%|███▋      | 36513/100629 [28:52<50:34, 21.13it/s]

 36%|███▋      | 36517/100629 [28:52<44:46, 23.87it/s]

 36%|███▋      | 36520/100629 [28:52<43:06, 24.79it/s]

 36%|███▋      | 36523/100629 [28:52<42:53, 24.91it/s]

 36%|███▋      | 36526/100629 [28:52<43:49, 24.38it/s]

 36%|███▋      | 36530/100629 [28:52<43:12, 24.73it/s]

 36%|███▋      | 36533/100629 [28:53<47:31, 22.48it/s]

 36%|███▋      | 36536/100629 [28:53<54:07, 19.74it/s]

 36%|███▋      | 36539/100629 [28:53<50:23, 21.19it/s]

 36%|███▋      | 36542/100629 [28:53<48:56, 21.82it/s]

 36%|███▋      | 36546/100629 [28:53<43:04, 24.80it/s]

 36%|███▋      | 36549/100629 [28:53<42:20, 25.22it/s]

 36%|███▋      | 36552/100629 [28:53<40:34, 26.32it/s]

 36%|███▋      | 36555/100629 [28:54<44:45, 23.86it/s]

 36%|███▋      | 36558/100629 [28:54<42:56, 24.86it/s]

 36%|███▋      | 36561/100629 [28:54<46:03, 23.18it/s]

 36%|███▋      | 36564/100629 [28:54<44:34, 23.96it/s]

 36%|███▋      | 36567/100629 [28:54<49:56, 21.38it/s]

 36%|███▋      | 36570/100629 [28:54<53:16, 20.04it/s]

 36%|███▋      | 36575/100629 [28:54<42:32, 25.10it/s]

 36%|███▋      | 36578/100629 [28:55<49:15, 21.67it/s]

 36%|███▋      | 36581/100629 [28:55<1:09:32, 15.35it/s]

 36%|███▋      | 36584/100629 [28:55<1:03:50, 16.72it/s]

 36%|███▋      | 36587/100629 [28:55<58:13, 18.33it/s]

 36%|███▋      | 36590/100629 [28:55<56:52, 18.76it/s]

 36%|███▋      | 36593/100629 [28:55<50:51, 20.98it/s]

 36%|███▋      | 36597/100629 [28:56<55:55, 19.08it/s]

 36%|███▋      | 36600/100629 [28:56<53:15, 20.04it/s]

 36%|███▋      | 36603/100629 [28:56<54:15, 19.67it/s]

 36%|███▋      | 36606/100629 [28:56<49:08, 21.72it/s]

 36%|███▋      | 36609/100629 [28:56<48:57, 21.79it/s]

 36%|███▋      | 36612/100629 [28:56<47:13, 22.60it/s]

 36%|███▋      | 36615/100629 [28:57<58:24, 18.27it/s]

 36%|███▋      | 36618/100629 [28:57<53:15, 20.03it/s]

 36%|███▋      | 36621/100629 [28:57<51:45, 20.61it/s]

 36%|███▋      | 36624/100629 [28:57<51:37, 20.67it/s]

 36%|███▋      | 36627/100629 [28:57<55:27, 19.23it/s]

 36%|███▋      | 36630/100629 [28:57<51:45, 20.61it/s]

 36%|███▋      | 36633/100629 [28:58<1:03:56, 16.68it/s]

 36%|███▋      | 36636/100629 [28:58<56:11, 18.98it/s]

 36%|███▋      | 36640/100629 [28:58<51:11, 20.83it/s]

 36%|███▋      | 36643/100629 [28:58<54:19, 19.63it/s]

 36%|███▋      | 36646/100629 [28:58<55:36, 19.18it/s]

 36%|███▋      | 36649/100629 [28:58<56:59, 18.71it/s]

 36%|███▋      | 36652/100629 [28:58<54:49, 19.45it/s]

 36%|███▋      | 36654/100629 [28:59<1:00:48, 17.54it/s]

 36%|███▋      | 36657/100629 [28:59<56:53, 18.74it/s]

 36%|███▋      | 36660/100629 [28:59<57:00, 18.70it/s]

 36%|███▋      | 36662/100629 [28:59<59:04, 18.04it/s]

 36%|███▋      | 36664/100629 [28:59<1:03:00, 16.92it/s]

 36%|███▋      | 36666/100629 [28:59<1:11:46, 14.85it/s]

 36%|███▋      | 36670/100629 [29:00<59:39, 17.87it/s]

 36%|███▋      | 36672/100629 [29:00<59:29, 17.92it/s]

 36%|███▋      | 36675/100629 [29:00<51:31, 20.69it/s]

 36%|███▋      | 36678/100629 [29:00<49:29, 21.53it/s]

 36%|███▋      | 36681/100629 [29:00<51:57, 20.51it/s]

 36%|███▋      | 36685/100629 [29:00<46:39, 22.84it/s]

 36%|███▋      | 36688/100629 [29:00<44:50, 23.76it/s]

 36%|███▋      | 36691/100629 [29:00<44:50, 23.77it/s]

 36%|███▋      | 36694/100629 [29:01<47:05, 22.62it/s]

 36%|███▋      | 36697/100629 [29:01<49:15, 21.63it/s]

 36%|███▋      | 36700/100629 [29:01<47:40, 22.35it/s]

 36%|███▋      | 36704/100629 [29:01<40:54, 26.04it/s]

 36%|███▋      | 36707/100629 [29:01<42:23, 25.13it/s]

 36%|███▋      | 36711/100629 [29:01<42:40, 24.96it/s]

 36%|███▋      | 36714/100629 [29:01<42:23, 25.13it/s]

 36%|███▋      | 36718/100629 [29:01<39:21, 27.07it/s]

 36%|███▋      | 36721/100629 [29:02<43:34, 24.44it/s]

 36%|███▋      | 36724/100629 [29:02<42:23, 25.12it/s]

 36%|███▋      | 36727/100629 [29:02<42:29, 25.07it/s]

 37%|███▋      | 36732/100629 [29:02<40:03, 26.58it/s]

 37%|███▋      | 36735/100629 [29:02<45:13, 23.55it/s]

 37%|███▋      | 36738/100629 [29:02<46:44, 22.78it/s]

 37%|███▋      | 36741/100629 [29:02<48:10, 22.10it/s]

 37%|███▋      | 36744/100629 [29:03<46:32, 22.88it/s]

 37%|███▋      | 36747/100629 [29:03<44:35, 23.87it/s]

 37%|███▋      | 36750/100629 [29:03<46:21, 22.96it/s]

 37%|███▋      | 36753/100629 [29:03<49:20, 21.57it/s]

 37%|███▋      | 36757/100629 [29:03<46:20, 22.97it/s]

 37%|███▋      | 36760/100629 [29:03<49:56, 21.32it/s]

 37%|███▋      | 36763/100629 [29:04<56:29, 18.84it/s]

 37%|███▋      | 36765/100629 [29:04<1:03:57, 16.64it/s]

 37%|███▋      | 36768/100629 [29:04<55:16, 19.25it/s]

 37%|███▋      | 36771/100629 [29:04<52:04, 20.44it/s]

 37%|███▋      | 36774/100629 [29:04<53:32, 19.88it/s]

 37%|███▋      | 36777/100629 [29:04<58:14, 18.27it/s]

 37%|███▋      | 36781/100629 [29:04<52:37, 20.22it/s]

 37%|███▋      | 36784/100629 [29:05<1:01:15, 17.37it/s]

 37%|███▋      | 36788/100629 [29:05<51:05, 20.83it/s]

 37%|███▋      | 36792/100629 [29:05<44:36, 23.85it/s]

 37%|███▋      | 36795/100629 [29:05<52:48, 20.14it/s]

 37%|███▋      | 36798/100629 [29:05<52:44, 20.17it/s]

 37%|███▋      | 36801/100629 [29:05<52:00, 20.45it/s]

 37%|███▋      | 36805/100629 [29:06<45:56, 23.16it/s]

 37%|███▋      | 36808/100629 [29:06<49:46, 21.37it/s]

 37%|███▋      | 36813/100629 [29:06<40:36, 26.19it/s]

 37%|███▋      | 36817/100629 [29:06<36:32, 29.10it/s]

 37%|███▋      | 36821/100629 [29:06<44:01, 24.16it/s]

 37%|███▋      | 36824/100629 [29:06<50:05, 21.23it/s]

 37%|███▋      | 36827/100629 [29:07<51:35, 20.61it/s]

 37%|███▋      | 36830/100629 [29:07<52:36, 20.21it/s]

 37%|███▋      | 36833/100629 [29:07<51:46, 20.54it/s]

 37%|███▋      | 36836/100629 [29:07<1:11:08, 14.95it/s]

 37%|███▋      | 36838/100629 [29:07<1:11:04, 14.96it/s]

 37%|███▋      | 36840/100629 [29:07<1:07:57, 15.64it/s]

 37%|███▋      | 36842/100629 [29:08<1:18:10, 13.60it/s]

 37%|███▋      | 36844/100629 [29:08<1:11:35, 14.85it/s]

 37%|███▋      | 36848/100629 [29:08<54:26, 19.53it/s]

 37%|███▋      | 36851/100629 [29:08<57:32, 18.47it/s]

 37%|███▋      | 36854/100629 [29:08<56:23, 18.85it/s]

 37%|███▋      | 36856/100629 [29:08<1:06:59, 15.86it/s]

 37%|███▋      | 36858/100629 [29:08<1:04:52, 16.38it/s]

 37%|███▋      | 36860/100629 [29:09<1:06:02, 16.09it/s]

 37%|███▋      | 36862/100629 [29:09<1:10:50, 15.00it/s]

 37%|███▋      | 36865/100629 [29:09<1:03:52, 16.64it/s]

 37%|███▋      | 36867/100629 [29:09<1:21:00, 13.12it/s]

 37%|███▋      | 36870/100629 [29:09<1:06:51, 15.90it/s]

 37%|███▋      | 36872/100629 [29:09<1:04:03, 16.59it/s]

 37%|███▋      | 36875/100629 [29:10<57:42, 18.41it/s]

 37%|███▋      | 36878/100629 [29:10<50:25, 21.07it/s]

 37%|███▋      | 36881/100629 [29:10<51:10, 20.76it/s]

 37%|███▋      | 36884/100629 [29:10<50:33, 21.01it/s]

 37%|███▋      | 36888/100629 [29:10<42:43, 24.87it/s]

 37%|███▋      | 36891/100629 [29:10<41:20, 25.70it/s]

 37%|███▋      | 36894/100629 [29:10<42:02, 25.27it/s]

 37%|███▋      | 36897/100629 [29:10<44:01, 24.12it/s]

 37%|███▋      | 36900/100629 [29:11<46:51, 22.67it/s]

 37%|███▋      | 36903/100629 [29:11<48:19, 21.98it/s]

 37%|███▋      | 36906/100629 [29:11<50:04, 21.21it/s]

 37%|███▋      | 36909/100629 [29:11<51:04, 20.79it/s]

 37%|███▋      | 36912/100629 [29:11<53:35, 19.81it/s]

 37%|███▋      | 36915/100629 [29:11<49:21, 21.51it/s]

 37%|███▋      | 36919/100629 [29:11<42:12, 25.15it/s]

 37%|███▋      | 36922/100629 [29:12<43:51, 24.21it/s]

 37%|███▋      | 36925/100629 [29:12<54:35, 19.45it/s]

 37%|███▋      | 36929/100629 [29:12<49:49, 21.31it/s]

 37%|███▋      | 36932/100629 [29:12<56:19, 18.85it/s]

 37%|███▋      | 36936/100629 [29:12<46:52, 22.65it/s]

 37%|███▋      | 36939/100629 [29:12<53:48, 19.72it/s]

 37%|███▋      | 36942/100629 [29:13<56:36, 18.75it/s]

 37%|███▋      | 36945/100629 [29:13<53:57, 19.67it/s]

 37%|███▋      | 36949/100629 [29:13<50:17, 21.10it/s]

 37%|███▋      | 36952/100629 [29:13<47:26, 22.37it/s]

 37%|███▋      | 36955/100629 [29:13<51:05, 20.77it/s]

 37%|███▋      | 36958/100629 [29:13<52:36, 20.17it/s]

 37%|███▋      | 36961/100629 [29:13<49:48, 21.30it/s]

 37%|███▋      | 36964/100629 [29:14<52:21, 20.27it/s]

 37%|███▋      | 36969/100629 [29:14<41:05, 25.82it/s]

 37%|███▋      | 36973/100629 [29:14<43:59, 24.11it/s]

 37%|███▋      | 36976/100629 [29:14<50:28, 21.02it/s]

 37%|███▋      | 36980/100629 [29:14<44:02, 24.08it/s]

 37%|███▋      | 36983/100629 [29:14<45:23, 23.37it/s]

 37%|███▋      | 36986/100629 [29:15<49:54, 21.26it/s]

 37%|███▋      | 36989/100629 [29:15<49:10, 21.57it/s]

 37%|███▋      | 36992/100629 [29:15<47:03, 22.54it/s]

 37%|███▋      | 36995/100629 [29:15<51:05, 20.76it/s]

 37%|███▋      | 36998/100629 [29:15<47:49, 22.17it/s]

 37%|███▋      | 37002/100629 [29:15<45:57, 23.07it/s]

 37%|███▋      | 37005/100629 [29:15<52:20, 20.26it/s]

 37%|███▋      | 37008/100629 [29:16<51:07, 20.74it/s]

 37%|███▋      | 37012/100629 [29:16<47:31, 22.31it/s]

 37%|███▋      | 37015/100629 [29:16<44:33, 23.80it/s]

 37%|███▋      | 37018/100629 [29:16<45:51, 23.12it/s]

 37%|███▋      | 37021/100629 [29:16<47:32, 22.30it/s]

 37%|███▋      | 37024/100629 [29:16<53:07, 19.95it/s]

 37%|███▋      | 37028/100629 [29:16<44:16, 23.94it/s]

 37%|███▋      | 37032/100629 [29:17<41:22, 25.62it/s]

 37%|███▋      | 37035/100629 [29:17<47:06, 22.50it/s]

 37%|███▋      | 37040/100629 [29:17<41:47, 25.36it/s]

 37%|███▋      | 37043/100629 [29:17<52:36, 20.15it/s]

 37%|███▋      | 37048/100629 [29:17<46:52, 22.61it/s]

 37%|███▋      | 37051/100629 [29:17<48:11, 21.99it/s]

 37%|███▋      | 37054/100629 [29:18<50:25, 21.02it/s]

 37%|███▋      | 37057/100629 [29:18<48:32, 21.83it/s]

 37%|███▋      | 37062/100629 [29:18<41:04, 25.79it/s]

 37%|███▋      | 37065/100629 [29:18<44:31, 23.80it/s]

 37%|███▋      | 37068/100629 [29:18<45:34, 23.25it/s]

 37%|███▋      | 37071/100629 [29:18<51:09, 20.70it/s]

 37%|███▋      | 37074/100629 [29:19<50:55, 20.80it/s]

 37%|███▋      | 37077/100629 [29:19<53:53, 19.65it/s]

 37%|███▋      | 37080/100629 [29:19<59:21, 17.84it/s]

 37%|███▋      | 37083/100629 [29:19<56:40, 18.69it/s]

 37%|███▋      | 37085/100629 [29:19<1:00:57, 17.38it/s]

 37%|███▋      | 37088/100629 [29:19<54:51, 19.30it/s]

 37%|███▋      | 37090/100629 [29:19<58:54, 17.98it/s]

 37%|███▋      | 37092/100629 [29:20<58:21, 18.14it/s]

 37%|███▋      | 37095/100629 [29:20<58:35, 18.07it/s]

 37%|███▋      | 37098/100629 [29:20<54:54, 19.28it/s]

 37%|███▋      | 37101/100629 [29:20<52:24, 20.20it/s]

 37%|███▋      | 37104/100629 [29:20<57:52, 18.29it/s]

 37%|███▋      | 37106/100629 [29:20<1:00:26, 17.51it/s]

 37%|███▋      | 37112/100629 [29:20<44:25, 23.83it/s]

 37%|███▋      | 37115/100629 [29:21<45:28, 23.28it/s]

 37%|███▋      | 37119/100629 [29:21<42:45, 24.76it/s]

 37%|███▋      | 37122/100629 [29:21<46:29, 22.77it/s]

 37%|███▋      | 37125/100629 [29:21<49:24, 21.42it/s]

 37%|███▋      | 37128/100629 [29:21<52:20, 20.22it/s]

 37%|███▋      | 37131/100629 [29:21<50:16, 21.05it/s]

 37%|███▋      | 37135/100629 [29:21<44:42, 23.67it/s]

 37%|███▋      | 37138/100629 [29:22<43:12, 24.49it/s]

 37%|███▋      | 37141/100629 [29:22<45:45, 23.13it/s]

 37%|███▋      | 37145/100629 [29:22<41:00, 25.80it/s]

 37%|███▋      | 37148/100629 [29:22<42:53, 24.67it/s]

 37%|███▋      | 37151/100629 [29:22<52:30, 20.15it/s]

 37%|███▋      | 37156/100629 [29:22<52:46, 20.04it/s]

 37%|███▋      | 37159/100629 [29:23<52:35, 20.12it/s]

 37%|███▋      | 37162/100629 [29:23<48:12, 21.94it/s]

 37%|███▋      | 37165/100629 [29:23<50:26, 20.97it/s]

 37%|███▋      | 37168/100629 [29:23<49:25, 21.40it/s]

 37%|███▋      | 37171/100629 [29:23<50:37, 20.89it/s]

 37%|███▋      | 37174/100629 [29:23<46:47, 22.60it/s]

 37%|███▋      | 37177/100629 [29:23<50:44, 20.84it/s]

 37%|███▋      | 37181/100629 [29:24<51:26, 20.56it/s]

 37%|███▋      | 37185/100629 [29:24<45:40, 23.15it/s]

 37%|███▋      | 37188/100629 [29:24<43:17, 24.43it/s]

 37%|███▋      | 37191/100629 [29:24<43:48, 24.14it/s]

 37%|███▋      | 37194/100629 [29:24<51:06, 20.69it/s]

 37%|███▋      | 37197/100629 [29:24<50:20, 21.00it/s]

 37%|███▋      | 37200/100629 [29:24<48:48, 21.66it/s]

 37%|███▋      | 37203/100629 [29:25<53:51, 19.63it/s]

 37%|███▋      | 37206/100629 [29:25<51:36, 20.48it/s]

 37%|███▋      | 37210/100629 [29:25<43:20, 24.39it/s]

 37%|███▋      | 37213/100629 [29:25<50:29, 20.93it/s]

 37%|███▋      | 37216/100629 [29:25<50:39, 20.86it/s]

 37%|███▋      | 37219/100629 [29:25<56:53, 18.57it/s]

 37%|███▋      | 37222/100629 [29:26<51:41, 20.45it/s]

 37%|███▋      | 37225/100629 [29:26<47:51, 22.08it/s]

 37%|███▋      | 37228/100629 [29:26<47:21, 22.32it/s]

 37%|███▋      | 37231/100629 [29:26<48:03, 21.99it/s]

 37%|███▋      | 37234/100629 [29:26<55:31, 19.03it/s]

 37%|███▋      | 37237/100629 [29:26<53:04, 19.91it/s]

 37%|███▋      | 37240/100629 [29:26<50:30, 20.92it/s]

 37%|███▋      | 37244/100629 [29:27<44:26, 23.77it/s]

 37%|███▋      | 37247/100629 [29:27<43:07, 24.49it/s]

 37%|███▋      | 37250/100629 [29:27<49:55, 21.16it/s]

 37%|███▋      | 37253/100629 [29:27<54:53, 19.24it/s]

 37%|███▋      | 37256/100629 [29:27<53:34, 19.72it/s]

 37%|███▋      | 37259/100629 [29:27<51:28, 20.52it/s]

 37%|███▋      | 37264/100629 [29:27<40:59, 25.76it/s]

 37%|███▋      | 37268/100629 [29:28<36:30, 28.93it/s]

 37%|███▋      | 37272/100629 [29:28<39:34, 26.68it/s]

 37%|███▋      | 37275/100629 [29:28<44:06, 23.94it/s]

 37%|███▋      | 37278/100629 [29:28<46:16, 22.82it/s]

 37%|███▋      | 37281/100629 [29:28<53:20, 19.80it/s]

 37%|███▋      | 37284/100629 [29:28<49:34, 21.30it/s]

 37%|███▋      | 37287/100629 [29:29<57:05, 18.49it/s]

 37%|███▋      | 37290/100629 [29:29<52:40, 20.04it/s]

 37%|███▋      | 37294/100629 [29:29<59:50, 17.64it/s]

 37%|███▋      | 37296/100629 [29:29<59:17, 17.80it/s]

 37%|███▋      | 37299/100629 [29:29<52:07, 20.25it/s]

 37%|███▋      | 37302/100629 [29:29<48:04, 21.96it/s]

 37%|███▋      | 37305/100629 [29:29<48:14, 21.88it/s]

 37%|███▋      | 37308/100629 [29:30<51:14, 20.60it/s]

 37%|███▋      | 37312/100629 [29:30<42:59, 24.55it/s]

 37%|███▋      | 37315/100629 [29:30<44:52, 23.52it/s]

 37%|███▋      | 37318/100629 [29:30<44:06, 23.92it/s]

 37%|███▋      | 37321/100629 [29:30<1:00:42, 17.38it/s]

 37%|███▋      | 37324/100629 [29:30<1:02:51, 16.79it/s]

 37%|███▋      | 37326/100629 [29:31<1:02:15, 16.95it/s]

 37%|███▋      | 37328/100629 [29:31<1:02:11, 16.96it/s]

 37%|███▋      | 37331/100629 [29:31<57:20, 18.40it/s]

 37%|███▋      | 37333/100629 [29:31<59:23, 17.76it/s]

 37%|███▋      | 37336/100629 [29:31<56:16, 18.74it/s]

 37%|███▋      | 37338/100629 [29:31<56:23, 18.71it/s]

 37%|███▋      | 37340/100629 [29:31<1:01:55, 17.03it/s]

 37%|███▋      | 37344/100629 [29:31<48:18, 21.83it/s]

 37%|███▋      | 37347/100629 [29:32<53:55, 19.56it/s]

 37%|███▋      | 37350/100629 [29:32<1:08:58, 15.29it/s]

 37%|███▋      | 37353/100629 [29:32<1:04:14, 16.41it/s]

 37%|███▋      | 37357/100629 [29:32<53:49, 19.59it/s]

 37%|███▋      | 37360/100629 [29:32<49:52, 21.15it/s]

 37%|███▋      | 37363/100629 [29:33<1:02:53, 16.77it/s]

 37%|███▋      | 37366/100629 [29:33<56:03, 18.81it/s]

 37%|███▋      | 37369/100629 [29:33<1:03:01, 16.73it/s]

 37%|███▋      | 37371/100629 [29:33<1:04:10, 16.43it/s]

 37%|███▋      | 37375/100629 [29:33<56:42, 18.59it/s]

 37%|███▋      | 37379/100629 [29:33<50:13, 20.99it/s]

 37%|███▋      | 37382/100629 [29:34<53:48, 19.59it/s]

 37%|███▋      | 37385/100629 [29:34<50:08, 21.02it/s]

 37%|███▋      | 37388/100629 [29:34<49:44, 21.19it/s]

 37%|███▋      | 37391/100629 [29:34<48:24, 21.77it/s]

 37%|███▋      | 37395/100629 [29:34<42:53, 24.57it/s]

 37%|███▋      | 37398/100629 [29:34<45:56, 22.94it/s]

 37%|███▋      | 37401/100629 [29:34<52:08, 20.21it/s]

 37%|███▋      | 37404/100629 [29:35<50:04, 21.04it/s]

 37%|███▋      | 37407/100629 [29:35<45:47, 23.01it/s]

 37%|███▋      | 37410/100629 [29:35<47:34, 22.15it/s]

 37%|███▋      | 37413/100629 [29:35<51:25, 20.49it/s]

 37%|███▋      | 37416/100629 [29:35<47:10, 22.33it/s]

 37%|███▋      | 37419/100629 [29:35<54:24, 19.36it/s]

 37%|███▋      | 37422/100629 [29:35<51:51, 20.32it/s]

 37%|███▋      | 37425/100629 [29:36<50:35, 20.82it/s]

 37%|███▋      | 37428/100629 [29:36<45:58, 22.91it/s]

 37%|███▋      | 37431/100629 [29:36<47:00, 22.41it/s]

 37%|███▋      | 37434/100629 [29:36<43:49, 24.03it/s]

 37%|███▋      | 37437/100629 [29:36<47:07, 22.35it/s]

 37%|███▋      | 37441/100629 [29:36<42:39, 24.69it/s]

 37%|███▋      | 37444/100629 [29:36<40:48, 25.81it/s]

 37%|███▋      | 37447/100629 [29:36<39:40, 26.55it/s]

 37%|███▋      | 37450/100629 [29:36<39:25, 26.71it/s]

 37%|███▋      | 37454/100629 [29:37<37:31, 28.06it/s]

 37%|███▋      | 37457/100629 [29:37<41:35, 25.32it/s]

 37%|███▋      | 37461/100629 [29:37<39:42, 26.51it/s]

 37%|███▋      | 37464/100629 [29:37<44:36, 23.60it/s]

 37%|███▋      | 37467/100629 [29:37<49:29, 21.27it/s]

 37%|███▋      | 37470/100629 [29:37<51:21, 20.50it/s]

 37%|███▋      | 37473/100629 [29:38<47:57, 21.94it/s]

 37%|███▋      | 37476/100629 [29:38<50:19, 20.91it/s]

 37%|███▋      | 37479/100629 [29:38<51:36, 20.40it/s]

 37%|███▋      | 37482/100629 [29:38<50:02, 21.03it/s]

 37%|███▋      | 37486/100629 [29:38<46:59, 22.40it/s]

 37%|███▋      | 37489/100629 [29:38<50:33, 20.82it/s]

 37%|███▋      | 37492/100629 [29:38<46:19, 22.71it/s]

 37%|███▋      | 37495/100629 [29:39<46:43, 22.52it/s]

 37%|███▋      | 37498/100629 [29:39<45:05, 23.34it/s]

 37%|███▋      | 37501/100629 [29:39<46:47, 22.49it/s]

 37%|███▋      | 37504/100629 [29:39<44:21, 23.72it/s]

 37%|███▋      | 37507/100629 [29:39<45:21, 23.19it/s]

 37%|███▋      | 37511/100629 [29:39<40:19, 26.09it/s]

 37%|███▋      | 37514/100629 [29:39<39:37, 26.55it/s]

 37%|███▋      | 37517/100629 [29:39<43:49, 24.00it/s]

 37%|███▋      | 37520/100629 [29:40<51:19, 20.49it/s]

 37%|███▋      | 37523/100629 [29:40<51:11, 20.55it/s]

 37%|███▋      | 37526/100629 [29:40<51:42, 20.34it/s]

 37%|███▋      | 37529/100629 [29:40<48:08, 21.84it/s]

 37%|███▋      | 37532/100629 [29:40<47:07, 22.32it/s]

 37%|███▋      | 37535/100629 [29:40<50:15, 20.92it/s]

 37%|███▋      | 37538/100629 [29:40<48:47, 21.55it/s]

 37%|███▋      | 37541/100629 [29:41<52:20, 20.09it/s]

 37%|███▋      | 37544/100629 [29:41<51:31, 20.41it/s]

 37%|███▋      | 37547/100629 [29:41<49:09, 21.39it/s]

 37%|███▋      | 37550/100629 [29:41<51:47, 20.30it/s]

 37%|███▋      | 37553/100629 [29:41<57:42, 18.21it/s]

 37%|███▋      | 37555/100629 [29:41<1:07:36, 15.55it/s]

 37%|███▋      | 37557/100629 [29:42<1:06:02, 15.92it/s]

 37%|███▋      | 37559/100629 [29:42<1:03:03, 16.67it/s]

 37%|███▋      | 37562/100629 [29:42<55:08, 19.06it/s]

 37%|███▋      | 37565/100629 [29:42<51:02, 20.60it/s]

 37%|███▋      | 37569/100629 [29:42<46:45, 22.48it/s]

 37%|███▋      | 37572/100629 [29:42<47:31, 22.11it/s]

 37%|███▋      | 37575/100629 [29:42<49:42, 21.14it/s]

 37%|███▋      | 37578/100629 [29:43<56:19, 18.66it/s]

 37%|███▋      | 37581/100629 [29:43<56:29, 18.60it/s]

 37%|███▋      | 37583/100629 [29:43<57:02, 18.42it/s]

 37%|███▋      | 37585/100629 [29:43<1:02:29, 16.82it/s]

 37%|███▋      | 37588/100629 [29:43<58:23, 17.99it/s]

 37%|███▋      | 37590/100629 [29:43<57:46, 18.18it/s]

 37%|███▋      | 37592/100629 [29:43<57:40, 18.21it/s]

 37%|███▋      | 37594/100629 [29:43<58:05, 18.08it/s]

 37%|███▋      | 37596/100629 [29:44<57:49, 18.17it/s]

 37%|███▋      | 37598/100629 [29:44<56:31, 18.59it/s]

 37%|███▋      | 37601/100629 [29:44<51:08, 20.54it/s]

 37%|███▋      | 37604/100629 [29:44<49:51, 21.07it/s]

 37%|███▋      | 37609/100629 [29:44<53:14, 19.73it/s]

 37%|███▋      | 37612/100629 [29:44<50:23, 20.84it/s]

 37%|███▋      | 37615/100629 [29:44<50:51, 20.65it/s]

 37%|███▋      | 37618/100629 [29:45<58:43, 17.89it/s]

 37%|███▋      | 37621/100629 [29:45<58:56, 17.82it/s]

 37%|███▋      | 37625/100629 [29:45<49:16, 21.31it/s]

 37%|███▋      | 37628/100629 [29:45<59:49, 17.55it/s]

 37%|███▋      | 37630/100629 [29:45<1:01:33, 17.06it/s]

 37%|███▋      | 37633/100629 [29:45<53:37, 19.58it/s]

 37%|███▋      | 37636/100629 [29:46<53:19, 19.69it/s]

 37%|███▋      | 37639/100629 [29:46<53:23, 19.66it/s]

 37%|███▋      | 37642/100629 [29:46<50:52, 20.63it/s]

 37%|███▋      | 37645/100629 [29:46<52:30, 19.99it/s]

 37%|███▋      | 37649/100629 [29:46<50:04, 20.96it/s]

 37%|███▋      | 37652/100629 [29:46<49:05, 21.38it/s]

 37%|███▋      | 37655/100629 [29:47<49:40, 21.13it/s]

 37%|███▋      | 37660/100629 [29:47<40:18, 26.04it/s]

 37%|███▋      | 37664/100629 [29:47<38:06, 27.54it/s]

 37%|███▋      | 37667/100629 [29:47<38:29, 27.27it/s]

 37%|███▋      | 37670/100629 [29:47<39:21, 26.66it/s]

 37%|███▋      | 37673/100629 [29:47<44:34, 23.54it/s]

 37%|███▋      | 37676/100629 [29:47<44:42, 23.47it/s]

 37%|███▋      | 37680/100629 [29:47<41:25, 25.32it/s]

 37%|███▋      | 37684/100629 [29:48<39:03, 26.86it/s]

 37%|███▋      | 37687/100629 [29:48<39:29, 26.57it/s]

 37%|███▋      | 37690/100629 [29:48<46:22, 22.62it/s]

 37%|███▋      | 37694/100629 [29:48<42:40, 24.58it/s]

 37%|███▋      | 37697/100629 [29:48<44:31, 23.55it/s]

 37%|███▋      | 37700/100629 [29:48<44:06, 23.78it/s]

 37%|███▋      | 37704/100629 [29:48<44:46, 23.43it/s]

 37%|███▋      | 37707/100629 [29:49<48:17, 21.71it/s]

 37%|███▋      | 37710/100629 [29:49<56:26, 18.58it/s]

 37%|███▋      | 37715/100629 [29:49<45:30, 23.04it/s]

 37%|███▋      | 37718/100629 [29:49<44:25, 23.60it/s]

 37%|███▋      | 37721/100629 [29:49<42:47, 24.50it/s]

 37%|███▋      | 37724/100629 [29:49<44:19, 23.65it/s]

 37%|███▋      | 37727/100629 [29:49<43:02, 24.36it/s]

 37%|███▋      | 37730/100629 [29:50<41:35, 25.20it/s]

 37%|███▋      | 37733/100629 [29:50<39:40, 26.42it/s]

 38%|███▊      | 37736/100629 [29:50<45:08, 23.22it/s]

 38%|███▊      | 37740/100629 [29:50<49:09, 21.32it/s]

 38%|███▊      | 37743/100629 [29:50<56:39, 18.50it/s]

 38%|███▊      | 37747/100629 [29:50<54:59, 19.06it/s]

 38%|███▊      | 37750/100629 [29:51<52:34, 19.94it/s]

 38%|███▊      | 37753/100629 [29:51<49:58, 20.97it/s]

 38%|███▊      | 37756/100629 [29:51<56:56, 18.40it/s]

 38%|███▊      | 37759/100629 [29:51<55:50, 18.77it/s]

 38%|███▊      | 37762/100629 [29:51<52:53, 19.81it/s]

 38%|███▊      | 37765/100629 [29:51<53:33, 19.56it/s]

 38%|███▊      | 37768/100629 [29:51<50:57, 20.56it/s]

 38%|███▊      | 37772/100629 [29:52<47:07, 22.23it/s]

 38%|███▊      | 37775/100629 [29:52<44:54, 23.33it/s]

 38%|███▊      | 37778/100629 [29:52<46:56, 22.31it/s]

 38%|███▊      | 37781/100629 [29:52<47:35, 22.01it/s]

 38%|███▊      | 37784/100629 [29:52<44:05, 23.76it/s]

 38%|███▊      | 37787/100629 [29:52<46:09, 22.69it/s]

 38%|███▊      | 37790/100629 [29:53<53:43, 19.49it/s]

 38%|███▊      | 37793/100629 [29:53<49:11, 21.29it/s]

 38%|███▊      | 37796/100629 [29:53<45:25, 23.05it/s]

 38%|███▊      | 37799/100629 [29:53<47:56, 21.85it/s]

 38%|███▊      | 37802/100629 [29:53<45:57, 22.78it/s]

 38%|███▊      | 37805/100629 [29:53<51:54, 20.17it/s]

 38%|███▊      | 37808/100629 [29:53<52:31, 19.93it/s]

 38%|███▊      | 37811/100629 [29:54<58:57, 17.76it/s]

 38%|███▊      | 37814/100629 [29:54<55:44, 18.78it/s]

 38%|███▊      | 37817/100629 [29:54<49:37, 21.10it/s]

 38%|███▊      | 37820/100629 [29:54<56:05, 18.66it/s]

 38%|███▊      | 37823/100629 [29:54<59:28, 17.60it/s]

 38%|███▊      | 37826/100629 [29:54<57:32, 18.19it/s]

 38%|███▊      | 37829/100629 [29:55<57:45, 18.12it/s]

 38%|███▊      | 37832/100629 [29:55<52:08, 20.07it/s]

 38%|███▊      | 37836/100629 [29:55<44:50, 23.34it/s]

 38%|███▊      | 37839/100629 [29:55<55:31, 18.85it/s]

 38%|███▊      | 37842/100629 [29:55<1:00:39, 17.25it/s]

 38%|███▊      | 37846/100629 [29:55<51:56, 20.14it/s]

 38%|███▊      | 37849/100629 [29:55<49:03, 21.33it/s]

 38%|███▊      | 37852/100629 [29:56<51:09, 20.45it/s]

 38%|███▊      | 37855/100629 [29:56<50:47, 20.60it/s]

 38%|███▊      | 37858/100629 [29:56<48:03, 21.77it/s]

 38%|███▊      | 37861/100629 [29:56<53:12, 19.66it/s]

 38%|███▊      | 37865/100629 [29:56<45:34, 22.95it/s]

 38%|███▊      | 37869/100629 [29:56<40:49, 25.62it/s]

 38%|███▊      | 37873/100629 [29:56<38:00, 27.52it/s]

 38%|███▊      | 37876/100629 [29:57<41:15, 25.35it/s]

 38%|███▊      | 37880/100629 [29:57<39:58, 26.16it/s]

 38%|███▊      | 37883/100629 [29:57<46:03, 22.70it/s]

 38%|███▊      | 37886/100629 [29:57<45:02, 23.22it/s]

 38%|███▊      | 37889/100629 [29:57<44:31, 23.48it/s]

 38%|███▊      | 37892/100629 [29:57<43:23, 24.10it/s]

 38%|███▊      | 37895/100629 [29:57<41:41, 25.08it/s]

 38%|███▊      | 37899/100629 [29:58<42:23, 24.67it/s]

 38%|███▊      | 37902/100629 [29:58<55:33, 18.81it/s]

 38%|███▊      | 37905/100629 [29:58<50:24, 20.74it/s]

 38%|███▊      | 37908/100629 [29:58<55:08, 18.96it/s]

 38%|███▊      | 37911/100629 [29:58<50:19, 20.77it/s]

 38%|███▊      | 37917/100629 [29:58<43:36, 23.97it/s]

 38%|███▊      | 37921/100629 [29:59<43:21, 24.11it/s]

 38%|███▊      | 37924/100629 [29:59<47:06, 22.18it/s]

 38%|███▊      | 37927/100629 [29:59<45:20, 23.05it/s]

 38%|███▊      | 37930/100629 [29:59<51:48, 20.17it/s]

 38%|███▊      | 37933/100629 [29:59<48:42, 21.45it/s]

 38%|███▊      | 37936/100629 [29:59<51:27, 20.31it/s]

 38%|███▊      | 37940/100629 [29:59<45:19, 23.05it/s]

 38%|███▊      | 37943/100629 [30:00<54:24, 19.20it/s]

 38%|███▊      | 37946/100629 [30:00<56:44, 18.41it/s]

 38%|███▊      | 37951/100629 [30:00<46:35, 22.42it/s]

 38%|███▊      | 37954/100629 [30:00<48:51, 21.38it/s]

 38%|███▊      | 37959/100629 [30:00<39:43, 26.29it/s]

 38%|███▊      | 37963/100629 [30:01<45:27, 22.98it/s]

 38%|███▊      | 37966/100629 [30:01<47:36, 21.94it/s]

 38%|███▊      | 37969/100629 [30:01<48:56, 21.34it/s]

 38%|███▊      | 37972/100629 [30:01<46:50, 22.29it/s]

 38%|███▊      | 37975/100629 [30:01<45:03, 23.18it/s]

 38%|███▊      | 37978/100629 [30:01<47:54, 21.79it/s]

 38%|███▊      | 37981/100629 [30:01<49:02, 21.29it/s]

 38%|███▊      | 37984/100629 [30:01<45:37, 22.88it/s]

 38%|███▊      | 37987/100629 [30:02<1:03:15, 16.51it/s]

 38%|███▊      | 37992/100629 [30:02<53:13, 19.62it/s]

 38%|███▊      | 37995/100629 [30:02<52:11, 20.00it/s]

 38%|███▊      | 37998/100629 [30:02<49:16, 21.19it/s]

 38%|███▊      | 38003/100629 [30:02<38:26, 27.15it/s]

 38%|███▊      | 38007/100629 [30:03<41:31, 25.13it/s]

 38%|███▊      | 38010/100629 [30:03<41:57, 24.87it/s]

 38%|███▊      | 38013/100629 [30:03<45:17, 23.04it/s]

 38%|███▊      | 38016/100629 [30:03<50:14, 20.77it/s]

 38%|███▊      | 38019/100629 [30:03<46:06, 22.63it/s]

 38%|███▊      | 38022/100629 [30:03<55:04, 18.94it/s]

 38%|███▊      | 38025/100629 [30:03<56:50, 18.36it/s]

 38%|███▊      | 38027/100629 [30:04<1:00:57, 17.11it/s]

 38%|███▊      | 38030/100629 [30:04<1:00:11, 17.33it/s]

 38%|███▊      | 38032/100629 [30:04<59:09, 17.64it/s]

 38%|███▊      | 38035/100629 [30:04<54:22, 19.18it/s]

 38%|███▊      | 38037/100629 [30:04<57:02, 18.29it/s]

 38%|███▊      | 38040/100629 [30:04<50:00, 20.86it/s]

 38%|███▊      | 38043/100629 [30:04<54:45, 19.05it/s]

 38%|███▊      | 38047/100629 [30:05<46:38, 22.36it/s]

 38%|███▊      | 38052/100629 [30:05<36:33, 28.53it/s]

 38%|███▊      | 38056/100629 [30:05<35:14, 29.59it/s]

 38%|███▊      | 38060/100629 [30:05<38:01, 27.43it/s]

 38%|███▊      | 38064/100629 [30:05<38:25, 27.14it/s]

 38%|███▊      | 38067/100629 [30:05<41:01, 25.41it/s]

 38%|███▊      | 38070/100629 [30:05<45:14, 23.04it/s]

 38%|███▊      | 38073/100629 [30:06<53:48, 19.37it/s]

 38%|███▊      | 38076/100629 [30:06<54:48, 19.02it/s]

 38%|███▊      | 38080/100629 [30:06<47:25, 21.98it/s]

 38%|███▊      | 38083/100629 [30:06<51:25, 20.27it/s]

 38%|███▊      | 38086/100629 [30:06<48:40, 21.42it/s]

 38%|███▊      | 38089/100629 [30:06<52:37, 19.80it/s]

 38%|███▊      | 38092/100629 [30:07<49:43, 20.96it/s]

 38%|███▊      | 38095/100629 [30:07<57:00, 18.28it/s]

 38%|███▊      | 38098/100629 [30:07<55:36, 18.74it/s]

 38%|███▊      | 38101/100629 [30:07<52:02, 20.03it/s]

 38%|███▊      | 38104/100629 [30:07<50:03, 20.82it/s]

 38%|███▊      | 38107/100629 [30:07<1:02:04, 16.79it/s]

 38%|███▊      | 38110/100629 [30:08<57:19, 18.18it/s]

 38%|███▊      | 38114/100629 [30:08<49:45, 20.94it/s]

 38%|███▊      | 38117/100629 [30:08<55:01, 18.93it/s]

 38%|███▊      | 38120/100629 [30:08<54:32, 19.10it/s]

 38%|███▊      | 38123/100629 [30:08<55:07, 18.90it/s]

 38%|███▊      | 38125/100629 [30:08<55:52, 18.64it/s]

 38%|███▊      | 38128/100629 [30:08<51:24, 20.26it/s]

 38%|███▊      | 38131/100629 [30:09<49:20, 21.11it/s]

 38%|███▊      | 38134/100629 [30:09<52:40, 19.77it/s]

 38%|███▊      | 38137/100629 [30:09<49:50, 20.90it/s]

 38%|███▊      | 38140/100629 [30:09<49:22, 21.10it/s]

 38%|███▊      | 38143/100629 [30:09<46:20, 22.47it/s]

 38%|███▊      | 38146/100629 [30:09<46:42, 22.30it/s]

 38%|███▊      | 38149/100629 [30:09<54:30, 19.10it/s]

 38%|███▊      | 38152/100629 [30:10<51:33, 20.20it/s]

 38%|███▊      | 38156/100629 [30:10<45:03, 23.11it/s]

 38%|███▊      | 38159/100629 [30:10<46:45, 22.27it/s]

 38%|███▊      | 38162/100629 [30:10<49:52, 20.87it/s]

 38%|███▊      | 38165/100629 [30:10<49:31, 21.02it/s]

 38%|███▊      | 38168/100629 [30:10<49:45, 20.92it/s]

 38%|███▊      | 38171/100629 [30:10<47:25, 21.95it/s]

 38%|███▊      | 38174/100629 [30:11<46:36, 22.33it/s]

 38%|███▊      | 38177/100629 [30:11<47:59, 21.69it/s]

 38%|███▊      | 38180/100629 [30:11<50:11, 20.73it/s]

 38%|███▊      | 38183/100629 [30:11<51:23, 20.25it/s]

 38%|███▊      | 38186/100629 [30:11<47:34, 21.88it/s]

 38%|███▊      | 38189/100629 [30:11<46:56, 22.17it/s]

 38%|███▊      | 38192/100629 [30:11<46:31, 22.37it/s]

 38%|███▊      | 38195/100629 [30:12<47:59, 21.68it/s]

 38%|███▊      | 38198/100629 [30:12<48:39, 21.38it/s]

 38%|███▊      | 38201/100629 [30:12<49:04, 21.20it/s]

 38%|███▊      | 38205/100629 [30:12<50:25, 20.63it/s]

 38%|███▊      | 38208/100629 [30:12<46:49, 22.22it/s]

 38%|███▊      | 38211/100629 [30:12<51:09, 20.33it/s]

 38%|███▊      | 38214/100629 [30:13<52:58, 19.63it/s]

 38%|███▊      | 38217/100629 [30:13<51:03, 20.37it/s]

 38%|███▊      | 38220/100629 [30:13<55:30, 18.74it/s]

 38%|███▊      | 38224/100629 [30:13<48:37, 21.39it/s]

 38%|███▊      | 38227/100629 [30:13<48:26, 21.47it/s]

 38%|███▊      | 38230/100629 [30:13<47:53, 21.72it/s]

 38%|███▊      | 38233/100629 [30:13<45:37, 22.79it/s]

 38%|███▊      | 38236/100629 [30:14<53:33, 19.42it/s]

 38%|███▊      | 38239/100629 [30:14<53:40, 19.37it/s]

 38%|███▊      | 38242/100629 [30:14<52:47, 19.70it/s]

 38%|███▊      | 38246/100629 [30:14<43:10, 24.08it/s]

 38%|███▊      | 38249/100629 [30:14<44:46, 23.22it/s]

 38%|███▊      | 38253/100629 [30:14<42:29, 24.47it/s]

 38%|███▊      | 38256/100629 [30:14<43:21, 23.97it/s]

 38%|███▊      | 38259/100629 [30:15<42:42, 24.34it/s]

 38%|███▊      | 38262/100629 [30:15<43:36, 23.83it/s]

 38%|███▊      | 38265/100629 [30:15<46:18, 22.45it/s]

 38%|███▊      | 38268/100629 [30:15<45:34, 22.81it/s]

 38%|███▊      | 38271/100629 [30:15<43:33, 23.86it/s]

 38%|███▊      | 38274/100629 [30:15<42:47, 24.28it/s]

 38%|███▊      | 38278/100629 [30:15<38:11, 27.21it/s]

 38%|███▊      | 38282/100629 [30:15<35:24, 29.35it/s]

 38%|███▊      | 38285/100629 [30:16<45:02, 23.07it/s]

 38%|███▊      | 38288/100629 [30:16<59:28, 17.47it/s]

 38%|███▊      | 38291/100629 [30:16<58:03, 17.90it/s]

 38%|███▊      | 38294/100629 [30:16<53:22, 19.46it/s]

 38%|███▊      | 38297/100629 [30:16<56:40, 18.33it/s]

 38%|███▊      | 38300/100629 [30:16<52:21, 19.84it/s]

 38%|███▊      | 38303/100629 [30:17<59:05, 17.58it/s]

 38%|███▊      | 38307/100629 [30:17<51:21, 20.22it/s]

 38%|███▊      | 38310/100629 [30:17<47:05, 22.05it/s]

 38%|███▊      | 38313/100629 [30:17<48:27, 21.44it/s]

 38%|███▊      | 38316/100629 [30:17<1:06:28, 15.62it/s]

 38%|███▊      | 38319/100629 [30:18<58:43, 17.68it/s]

 38%|███▊      | 38323/100629 [30:18<48:38, 21.35it/s]

 38%|███▊      | 38326/100629 [30:18<46:13, 22.46it/s]

 38%|███▊      | 38329/100629 [30:18<50:48, 20.44it/s]

 38%|███▊      | 38332/100629 [30:18<49:48, 20.85it/s]

 38%|███▊      | 38335/100629 [30:18<48:37, 21.35it/s]

 38%|███▊      | 38338/100629 [30:18<49:48, 20.85it/s]

 38%|███▊      | 38342/100629 [30:19<48:44, 21.30it/s]

 38%|███▊      | 38345/100629 [30:19<47:09, 22.01it/s]

 38%|███▊      | 38348/100629 [30:19<49:55, 20.79it/s]

 38%|███▊      | 38351/100629 [30:19<48:47, 21.27it/s]

 38%|███▊      | 38356/100629 [30:19<39:26, 26.31it/s]

 38%|███▊      | 38359/100629 [30:19<40:56, 25.35it/s]

 38%|███▊      | 38362/100629 [30:19<47:30, 21.84it/s]

 38%|███▊      | 38365/100629 [30:20<1:11:47, 14.45it/s]

 38%|███▊      | 38368/100629 [30:20<1:06:00, 15.72it/s]

 38%|███▊      | 38370/100629 [30:20<1:07:57, 15.27it/s]

 38%|███▊      | 38372/100629 [30:20<1:04:55, 15.98it/s]

 38%|███▊      | 38374/100629 [30:20<1:03:40, 16.29it/s]

 38%|███▊      | 38376/100629 [30:20<1:00:51, 17.05it/s]

 38%|███▊      | 38378/100629 [30:21<1:03:50, 16.25it/s]

 38%|███▊      | 38381/100629 [30:21<54:31, 19.02it/s]

 38%|███▊      | 38384/100629 [30:21<49:19, 21.03it/s]

 38%|███▊      | 38387/100629 [30:21<54:18, 19.10it/s]

 38%|███▊      | 38390/100629 [30:21<53:38, 19.34it/s]

 38%|███▊      | 38393/100629 [30:21<51:16, 20.23it/s]

 38%|███▊      | 38401/100629 [30:21<35:48, 28.97it/s]

 38%|███▊      | 38404/100629 [30:22<37:02, 28.00it/s]

 38%|███▊      | 38407/100629 [30:22<37:28, 27.68it/s]

 38%|███▊      | 38410/100629 [30:22<41:32, 24.96it/s]

 38%|███▊      | 38415/100629 [30:22<35:46, 28.98it/s]

 38%|███▊      | 38418/100629 [30:22<38:37, 26.84it/s]

 38%|███▊      | 38421/100629 [30:22<48:15, 21.48it/s]

 38%|███▊      | 38424/100629 [30:22<48:15, 21.48it/s]

 38%|███▊      | 38427/100629 [30:23<50:41, 20.45it/s]

 38%|███▊      | 38431/100629 [30:23<44:38, 23.22it/s]

 38%|███▊      | 38434/100629 [30:23<47:30, 21.82it/s]

 38%|███▊      | 38437/100629 [30:23<43:57, 23.58it/s]

 38%|███▊      | 38440/100629 [30:23<42:48, 24.21it/s]

 38%|███▊      | 38443/100629 [30:23<43:30, 23.82it/s]

 38%|███▊      | 38446/100629 [30:23<41:33, 24.94it/s]

 38%|███▊      | 38449/100629 [30:23<44:08, 23.47it/s]

 38%|███▊      | 38452/100629 [30:24<42:22, 24.45it/s]

 38%|███▊      | 38455/100629 [30:24<46:51, 22.11it/s]

 38%|███▊      | 38458/100629 [30:24<50:36, 20.48it/s]

 38%|███▊      | 38462/100629 [30:24<44:13, 23.43it/s]

 38%|███▊      | 38465/100629 [30:24<45:13, 22.91it/s]

 38%|███▊      | 38469/100629 [30:24<43:09, 24.01it/s]

 38%|███▊      | 38472/100629 [30:25<58:54, 17.59it/s]

 38%|███▊      | 38475/100629 [30:25<1:11:07, 14.56it/s]

 38%|███▊      | 38478/100629 [30:25<1:03:00, 16.44it/s]

 38%|███▊      | 38481/100629 [30:25<1:00:40, 17.07it/s]

 38%|███▊      | 38484/100629 [30:25<57:34, 17.99it/s]

 38%|███▊      | 38486/100629 [30:25<1:00:08, 17.22it/s]

 38%|███▊      | 38489/100629 [30:26<52:12, 19.84it/s]

 38%|███▊      | 38492/100629 [30:26<51:35, 20.07it/s]

 38%|███▊      | 38495/100629 [30:26<49:51, 20.77it/s]

 38%|███▊      | 38498/100629 [30:26<49:34, 20.89it/s]

 38%|███▊      | 38501/100629 [30:26<1:02:37, 16.54it/s]

 38%|███▊      | 38504/100629 [30:26<59:35, 17.38it/s]

 38%|███▊      | 38508/100629 [30:27<53:16, 19.43it/s]

 38%|███▊      | 38511/100629 [30:27<57:22, 18.04it/s]

 38%|███▊      | 38515/100629 [30:27<48:50, 21.19it/s]

 38%|███▊      | 38518/100629 [30:27<48:13, 21.47it/s]

 38%|███▊      | 38521/100629 [30:27<53:08, 19.48it/s]

 38%|███▊      | 38525/100629 [30:27<46:28, 22.27it/s]

 38%|███▊      | 38529/100629 [30:27<41:02, 25.21it/s]

 38%|███▊      | 38532/100629 [30:28<41:48, 24.76it/s]

 38%|███▊      | 38535/100629 [30:28<44:20, 23.34it/s]

 38%|███▊      | 38538/100629 [30:28<1:08:19, 15.15it/s]

 38%|███▊      | 38542/100629 [30:28<58:39, 17.64it/s]

 38%|███▊      | 38545/100629 [30:28<57:51, 17.88it/s]

 38%|███▊      | 38548/100629 [30:29<1:02:52, 16.45it/s]

 38%|███▊      | 38551/100629 [30:29<56:17, 18.38it/s]

 38%|███▊      | 38554/100629 [30:29<55:20, 18.69it/s]

 38%|███▊      | 38557/100629 [30:29<58:11, 17.78it/s]

 38%|███▊      | 38559/100629 [30:29<1:00:40, 17.05it/s]

 38%|███▊      | 38561/100629 [30:29<1:04:44, 15.98it/s]

 38%|███▊      | 38563/100629 [30:30<1:03:48, 16.21it/s]

 38%|███▊      | 38565/100629 [30:30<1:07:05, 15.42it/s]

 38%|███▊      | 38568/100629 [30:30<1:03:59, 16.16it/s]

 38%|███▊      | 38570/100629 [30:30<1:05:55, 15.69it/s]

 38%|███▊      | 38574/100629 [30:30<53:20, 19.39it/s]

 38%|███▊      | 38578/100629 [30:30<46:37, 22.18it/s]

 38%|███▊      | 38581/100629 [30:31<55:27, 18.65it/s]

 38%|███▊      | 38583/100629 [30:31<59:21, 17.42it/s]

 38%|███▊      | 38585/100629 [30:31<1:00:35, 17.07it/s]

 38%|███▊      | 38587/100629 [30:31<1:00:12, 17.17it/s]

 38%|███▊      | 38589/100629 [30:31<1:06:26, 15.56it/s]

 38%|███▊      | 38592/100629 [30:31<1:01:26, 16.83it/s]

 38%|███▊      | 38596/100629 [30:31<50:47, 20.35it/s]

 38%|███▊      | 38599/100629 [30:31<48:43, 21.22it/s]

 38%|███▊      | 38602/100629 [30:32<45:26, 22.75it/s]

 38%|███▊      | 38605/100629 [30:32<44:51, 23.05it/s]

 38%|███▊      | 38609/100629 [30:32<40:26, 25.56it/s]

 38%|███▊      | 38612/100629 [30:32<48:41, 21.22it/s]

 38%|███▊      | 38615/100629 [30:32<46:52, 22.05it/s]

 38%|███▊      | 38618/100629 [30:32<49:28, 20.89it/s]

 38%|███▊      | 38621/100629 [30:32<46:59, 21.99it/s]

 38%|███▊      | 38624/100629 [30:33<49:46, 20.76it/s]

 38%|███▊      | 38627/100629 [30:33<48:13, 21.43it/s]

 38%|███▊      | 38630/100629 [30:33<48:48, 21.17it/s]

 38%|███▊      | 38635/100629 [30:33<43:08, 23.95it/s]

 38%|███▊      | 38638/100629 [30:33<43:10, 23.93it/s]

 38%|███▊      | 38641/100629 [30:33<44:42, 23.11it/s]

 38%|███▊      | 38644/100629 [30:33<49:41, 20.79it/s]

 38%|███▊      | 38647/100629 [30:34<50:09, 20.60it/s]

 38%|███▊      | 38650/100629 [30:34<52:08, 19.81it/s]

 38%|███▊      | 38653/100629 [30:34<50:26, 20.48it/s]

 38%|███▊      | 38656/100629 [30:34<52:18, 19.75it/s]

 38%|███▊      | 38659/100629 [30:34<48:59, 21.08it/s]

 38%|███▊      | 38663/100629 [30:34<45:57, 22.47it/s]

 38%|███▊      | 38667/100629 [30:35<42:34, 24.25it/s]

 38%|███▊      | 38670/100629 [30:35<44:56, 22.98it/s]

 38%|███▊      | 38673/100629 [30:35<44:12, 23.36it/s]

 38%|███▊      | 38676/100629 [30:35<50:00, 20.65it/s]

 38%|███▊      | 38679/100629 [30:35<46:21, 22.27it/s]

 38%|███▊      | 38682/100629 [30:35<56:11, 18.37it/s]

 38%|███▊      | 38686/100629 [30:35<48:15, 21.39it/s]

 38%|███▊      | 38689/100629 [30:36<50:44, 20.35it/s]

 38%|███▊      | 38692/100629 [30:36<48:17, 21.38it/s]

 38%|███▊      | 38695/100629 [30:36<46:11, 22.35it/s]

 38%|███▊      | 38700/100629 [30:36<37:32, 27.49it/s]

 38%|███▊      | 38703/100629 [30:36<42:18, 24.39it/s]

 38%|███▊      | 38706/100629 [30:36<42:03, 24.54it/s]

 38%|███▊      | 38709/100629 [30:36<43:51, 23.53it/s]

 38%|███▊      | 38712/100629 [30:37<51:48, 19.92it/s]

 38%|███▊      | 38715/100629 [30:37<49:52, 20.69it/s]

 38%|███▊      | 38718/100629 [30:37<49:30, 20.84it/s]

 38%|███▊      | 38721/100629 [30:37<47:22, 21.78it/s]

 38%|███▊      | 38724/100629 [30:37<44:22, 23.25it/s]

 38%|███▊      | 38727/100629 [30:37<43:10, 23.90it/s]

 38%|███▊      | 38730/100629 [30:37<46:35, 22.15it/s]

 38%|███▊      | 38733/100629 [30:38<51:14, 20.13it/s]

 38%|███▊      | 38736/100629 [30:38<48:19, 21.34it/s]

 38%|███▊      | 38739/100629 [30:38<46:28, 22.19it/s]

 38%|███▊      | 38742/100629 [30:38<47:48, 21.57it/s]

 39%|███▊      | 38745/100629 [30:38<48:38, 21.20it/s]

 39%|███▊      | 38748/100629 [30:38<48:36, 21.22it/s]

 39%|███▊      | 38751/100629 [30:38<52:43, 19.56it/s]

 39%|███▊      | 38754/100629 [30:39<49:09, 20.98it/s]

 39%|███▊      | 38757/100629 [30:39<49:25, 20.86it/s]

 39%|███▊      | 38760/100629 [30:39<53:40, 19.21it/s]

 39%|███▊      | 38762/100629 [30:39<56:40, 18.19it/s]

 39%|███▊      | 38765/100629 [30:39<56:54, 18.12it/s]

 39%|███▊      | 38768/100629 [30:39<56:13, 18.33it/s]

 39%|███▊      | 38772/100629 [30:40<50:46, 20.30it/s]

 39%|███▊      | 38775/100629 [30:40<53:46, 19.17it/s]

 39%|███▊      | 38778/100629 [30:40<54:54, 18.78it/s]

 39%|███▊      | 38781/100629 [30:40<49:46, 20.71it/s]

 39%|███▊      | 38785/100629 [30:40<41:30, 24.83it/s]

 39%|███▊      | 38788/100629 [30:40<39:45, 25.92it/s]

 39%|███▊      | 38792/100629 [30:40<38:36, 26.70it/s]

 39%|███▊      | 38796/100629 [30:41<42:29, 24.25it/s]

 39%|███▊      | 38799/100629 [30:41<41:36, 24.77it/s]

 39%|███▊      | 38802/100629 [30:41<41:49, 24.64it/s]

 39%|███▊      | 38805/100629 [30:41<58:14, 17.69it/s]

 39%|███▊      | 38808/100629 [30:41<53:35, 19.23it/s]

 39%|███▊      | 38811/100629 [30:41<58:53, 17.49it/s]

 39%|███▊      | 38814/100629 [30:41<54:03, 19.06it/s]

 39%|███▊      | 38817/100629 [30:42<57:43, 17.85it/s]

 39%|███▊      | 38819/100629 [30:42<1:03:17, 16.28it/s]

 39%|███▊      | 38821/100629 [30:42<1:03:42, 16.17it/s]

 39%|███▊      | 38823/100629 [30:42<1:02:52, 16.38it/s]

 39%|███▊      | 38826/100629 [30:42<57:27, 17.93it/s]

 39%|███▊      | 38829/100629 [30:42<51:32, 19.98it/s]

 39%|███▊      | 38832/100629 [30:42<51:31, 19.99it/s]

 39%|███▊      | 38835/100629 [30:43<50:07, 20.55it/s]

 39%|███▊      | 38838/100629 [30:43<51:36, 19.96it/s]

 39%|███▊      | 38841/100629 [30:43<59:01, 17.44it/s]

 39%|███▊      | 38843/100629 [30:43<57:44, 17.83it/s]

 39%|███▊      | 38845/100629 [30:43<59:04, 17.43it/s]

 39%|███▊      | 38847/100629 [30:43<59:09, 17.41it/s]

 39%|███▊      | 38851/100629 [30:44<54:05, 19.03it/s]

 39%|███▊      | 38854/100629 [30:44<55:46, 18.46it/s]

 39%|███▊      | 38856/100629 [30:44<59:17, 17.36it/s]

 39%|███▊      | 38859/100629 [30:44<55:25, 18.58it/s]

 39%|███▊      | 38862/100629 [30:44<52:19, 19.67it/s]

 39%|███▊      | 38865/100629 [30:44<50:56, 20.21it/s]

 39%|███▊      | 38868/100629 [30:44<1:00:25, 17.03it/s]

 39%|███▊      | 38871/100629 [30:45<1:00:58, 16.88it/s]

 39%|███▊      | 38874/100629 [30:45<57:13, 17.99it/s]

 39%|███▊      | 38878/100629 [30:45<48:01, 21.43it/s]

 39%|███▊      | 38881/100629 [30:45<1:04:31, 15.95it/s]

 39%|███▊      | 38884/100629 [30:45<57:58, 17.75it/s]

 39%|███▊      | 38890/100629 [30:45<40:14, 25.57it/s]

 39%|███▊      | 38894/100629 [30:46<39:09, 26.28it/s]

 39%|███▊      | 38898/100629 [30:46<43:48, 23.48it/s]

 39%|███▊      | 38901/100629 [30:46<46:36, 22.08it/s]

 39%|███▊      | 38905/100629 [30:46<43:07, 23.86it/s]

 39%|███▊      | 38908/100629 [30:46<41:50, 24.59it/s]

 39%|███▊      | 38912/100629 [30:46<39:40, 25.93it/s]

 39%|███▊      | 38916/100629 [30:46<35:23, 29.06it/s]

 39%|███▊      | 38920/100629 [30:47<36:29, 28.19it/s]

 39%|███▊      | 38924/100629 [30:47<35:09, 29.25it/s]

 39%|███▊      | 38928/100629 [30:47<43:41, 23.54it/s]

 39%|███▊      | 38931/100629 [30:47<42:17, 24.32it/s]

 39%|███▊      | 38934/100629 [30:47<44:55, 22.89it/s]

 39%|███▊      | 38937/100629 [30:47<43:28, 23.65it/s]

 39%|███▊      | 38940/100629 [30:48<48:02, 21.40it/s]

 39%|███▊      | 38943/100629 [30:48<45:06, 22.79it/s]

 39%|███▊      | 38946/100629 [30:48<49:33, 20.74it/s]

 39%|███▊      | 38949/100629 [30:48<48:05, 21.38it/s]

 39%|███▊      | 38952/100629 [30:48<49:59, 20.56it/s]

 39%|███▊      | 38955/100629 [30:48<47:09, 21.79it/s]

 39%|███▊      | 38958/100629 [30:48<50:19, 20.42it/s]

 39%|███▊      | 38961/100629 [30:49<49:18, 20.85it/s]

 39%|███▊      | 38966/100629 [30:49<44:57, 22.86it/s]

 39%|███▊      | 38969/100629 [30:49<44:51, 22.91it/s]

 39%|███▊      | 38972/100629 [30:49<43:29, 23.63it/s]

 39%|███▊      | 38975/100629 [30:49<47:13, 21.76it/s]

 39%|███▊      | 38978/100629 [30:49<53:27, 19.22it/s]

 39%|███▊      | 38980/100629 [30:49<56:03, 18.33it/s]

 39%|███▊      | 38983/100629 [30:50<53:42, 19.13it/s]

 39%|███▊      | 38985/100629 [30:50<53:48, 19.09it/s]

 39%|███▊      | 38989/100629 [30:50<44:22, 23.15it/s]

 39%|███▊      | 38992/100629 [30:50<50:04, 20.52it/s]

 39%|███▉      | 38995/100629 [30:50<49:07, 20.91it/s]

 39%|███▉      | 38998/100629 [30:50<49:54, 20.58it/s]

 39%|███▉      | 39001/100629 [30:50<45:42, 22.47it/s]

 39%|███▉      | 39005/100629 [30:51<40:19, 25.47it/s]

 39%|███▉      | 39009/100629 [30:51<37:40, 27.27it/s]

 39%|███▉      | 39012/100629 [30:51<38:13, 26.86it/s]

 39%|███▉      | 39015/100629 [30:51<38:22, 26.76it/s]

 39%|███▉      | 39018/100629 [30:51<44:08, 23.26it/s]

 39%|███▉      | 39021/100629 [30:51<41:25, 24.78it/s]

 39%|███▉      | 39025/100629 [30:51<38:19, 26.79it/s]

 39%|███▉      | 39029/100629 [30:51<36:06, 28.43it/s]

 39%|███▉      | 39032/100629 [30:52<37:32, 27.35it/s]

 39%|███▉      | 39035/100629 [30:52<42:21, 24.24it/s]

 39%|███▉      | 39038/100629 [30:52<40:15, 25.50it/s]

 39%|███▉      | 39041/100629 [30:52<44:15, 23.19it/s]

 39%|███▉      | 39044/100629 [30:52<41:21, 24.82it/s]

 39%|███▉      | 39047/100629 [30:52<44:57, 22.83it/s]

 39%|███▉      | 39051/100629 [30:52<38:40, 26.54it/s]

 39%|███▉      | 39055/100629 [30:52<38:56, 26.35it/s]

 39%|███▉      | 39058/100629 [30:53<41:46, 24.56it/s]

 39%|███▉      | 39061/100629 [30:53<53:57, 19.02it/s]

 39%|███▉      | 39064/100629 [30:53<49:57, 20.54it/s]

 39%|███▉      | 39068/100629 [30:53<44:02, 23.30it/s]

 39%|███▉      | 39071/100629 [30:53<49:55, 20.55it/s]

 39%|███▉      | 39074/100629 [30:53<50:55, 20.14it/s]

 39%|███▉      | 39077/100629 [30:54<46:55, 21.86it/s]

 39%|███▉      | 39080/100629 [30:54<50:57, 20.13it/s]

 39%|███▉      | 39083/100629 [30:54<51:03, 20.09it/s]

 39%|███▉      | 39086/100629 [30:54<48:37, 21.09it/s]

 39%|███▉      | 39089/100629 [30:54<46:18, 22.15it/s]

 39%|███▉      | 39092/100629 [30:54<46:30, 22.05it/s]

 39%|███▉      | 39095/100629 [30:54<44:53, 22.85it/s]

 39%|███▉      | 39099/100629 [30:55<43:07, 23.78it/s]

 39%|███▉      | 39102/100629 [30:55<41:28, 24.73it/s]

 39%|███▉      | 39105/100629 [30:55<44:03, 23.27it/s]

 39%|███▉      | 39108/100629 [30:55<43:58, 23.32it/s]

 39%|███▉      | 39111/100629 [30:55<50:08, 20.45it/s]

 39%|███▉      | 39115/100629 [30:55<43:32, 23.55it/s]

 39%|███▉      | 39118/100629 [30:56<1:03:32, 16.13it/s]

 39%|███▉      | 39122/100629 [30:56<52:15, 19.62it/s]

 39%|███▉      | 39125/100629 [30:56<50:09, 20.44it/s]

 39%|███▉      | 39128/100629 [30:56<50:07, 20.45it/s]

 39%|███▉      | 39131/100629 [30:56<49:58, 20.51it/s]

 39%|███▉      | 39134/100629 [30:56<50:48, 20.17it/s]

 39%|███▉      | 39137/100629 [30:56<47:15, 21.69it/s]

 39%|███▉      | 39140/100629 [30:57<47:38, 21.51it/s]

 39%|███▉      | 39143/100629 [30:57<46:38, 21.97it/s]

 39%|███▉      | 39147/100629 [30:57<43:40, 23.46it/s]

 39%|███▉      | 39151/100629 [30:57<41:22, 24.77it/s]

 39%|███▉      | 39154/100629 [30:57<42:56, 23.86it/s]

 39%|███▉      | 39157/100629 [30:57<43:25, 23.60it/s]

 39%|███▉      | 39160/100629 [30:57<44:07, 23.21it/s]

 39%|███▉      | 39163/100629 [30:58<43:13, 23.70it/s]

 39%|███▉      | 39166/100629 [30:58<40:57, 25.01it/s]

 39%|███▉      | 39170/100629 [30:58<38:16, 26.77it/s]

 39%|███▉      | 39173/100629 [30:58<44:05, 23.23it/s]

 39%|███▉      | 39178/100629 [30:58<35:17, 29.02it/s]

 39%|███▉      | 39182/100629 [30:58<38:18, 26.73it/s]

 39%|███▉      | 39185/100629 [30:58<41:38, 24.59it/s]

 39%|███▉      | 39188/100629 [30:59<46:22, 22.08it/s]

 39%|███▉      | 39192/100629 [30:59<43:46, 23.39it/s]

 39%|███▉      | 39196/100629 [30:59<42:46, 23.94it/s]

 39%|███▉      | 39199/100629 [30:59<45:48, 22.35it/s]

 39%|███▉      | 39202/100629 [30:59<56:08, 18.23it/s]

 39%|███▉      | 39205/100629 [30:59<51:22, 19.93it/s]

 39%|███▉      | 39208/100629 [30:59<48:13, 21.23it/s]

 39%|███▉      | 39211/100629 [31:00<59:01, 17.34it/s]

 39%|███▉      | 39213/100629 [31:00<1:02:17, 16.43it/s]

 39%|███▉      | 39218/100629 [31:00<49:43, 20.58it/s]

 39%|███▉      | 39222/100629 [31:00<44:42, 22.89it/s]

 39%|███▉      | 39225/100629 [31:00<51:50, 19.74it/s]

 39%|███▉      | 39228/100629 [31:00<47:38, 21.48it/s]

 39%|███▉      | 39232/100629 [31:01<41:07, 24.88it/s]

 39%|███▉      | 39236/100629 [31:01<40:16, 25.41it/s]

 39%|███▉      | 39239/100629 [31:01<40:42, 25.13it/s]

 39%|███▉      | 39242/100629 [31:01<43:52, 23.32it/s]

 39%|███▉      | 39246/100629 [31:01<37:56, 26.96it/s]

 39%|███▉      | 39249/100629 [31:01<40:10, 25.46it/s]

 39%|███▉      | 39252/100629 [31:01<40:22, 25.34it/s]

 39%|███▉      | 39256/100629 [31:02<37:46, 27.08it/s]

 39%|███▉      | 39259/100629 [31:02<40:23, 25.32it/s]

 39%|███▉      | 39263/100629 [31:02<42:16, 24.20it/s]

 39%|███▉      | 39266/100629 [31:02<49:46, 20.55it/s]

 39%|███▉      | 39269/100629 [31:02<46:15, 22.11it/s]

 39%|███▉      | 39272/100629 [31:02<46:50, 21.83it/s]

 39%|███▉      | 39276/100629 [31:02<40:31, 25.23it/s]

 39%|███▉      | 39279/100629 [31:03<40:44, 25.09it/s]

 39%|███▉      | 39282/100629 [31:03<51:25, 19.88it/s]

 39%|███▉      | 39285/100629 [31:03<52:37, 19.43it/s]

 39%|███▉      | 39288/100629 [31:03<54:42, 18.68it/s]

 39%|███▉      | 39291/100629 [31:03<54:07, 18.89it/s]

 39%|███▉      | 39294/100629 [31:03<50:32, 20.23it/s]

 39%|███▉      | 39298/100629 [31:04<44:32, 22.95it/s]

 39%|███▉      | 39301/100629 [31:04<43:52, 23.30it/s]

 39%|███▉      | 39304/100629 [31:04<47:17, 21.61it/s]

 39%|███▉      | 39307/100629 [31:04<45:41, 22.37it/s]

 39%|███▉      | 39310/100629 [31:04<48:46, 20.95it/s]

 39%|███▉      | 39313/100629 [31:04<54:15, 18.83it/s]

 39%|███▉      | 39317/100629 [31:04<45:52, 22.27it/s]

 39%|███▉      | 39320/100629 [31:05<50:03, 20.41it/s]

 39%|███▉      | 39323/100629 [31:05<47:53, 21.33it/s]

 39%|███▉      | 39326/100629 [31:05<49:55, 20.47it/s]

 39%|███▉      | 39330/100629 [31:05<45:55, 22.25it/s]

 39%|███▉      | 39333/100629 [31:05<58:59, 17.32it/s]

 39%|███▉      | 39338/100629 [31:05<48:57, 20.87it/s]

 39%|███▉      | 39341/100629 [31:06<53:26, 19.11it/s]

 39%|███▉      | 39345/100629 [31:06<45:25, 22.49it/s]

 39%|███▉      | 39348/100629 [31:06<47:21, 21.56it/s]

 39%|███▉      | 39351/100629 [31:06<1:04:46, 15.77it/s]

 39%|███▉      | 39353/100629 [31:06<1:08:36, 14.89it/s]

 39%|███▉      | 39357/100629 [31:07<52:50, 19.33it/s]

 39%|███▉      | 39360/100629 [31:07<55:52, 18.28it/s]

 39%|███▉      | 39363/100629 [31:07<55:41, 18.33it/s]

 39%|███▉      | 39366/100629 [31:07<55:59, 18.24it/s]

 39%|███▉      | 39368/100629 [31:07<56:51, 17.96it/s]

 39%|███▉      | 39371/100629 [31:07<50:27, 20.24it/s]

 39%|███▉      | 39375/100629 [31:07<53:54, 18.94it/s]

 39%|███▉      | 39378/100629 [31:08<55:36, 18.36it/s]

 39%|███▉      | 39380/100629 [31:08<57:04, 17.89it/s]

 39%|███▉      | 39384/100629 [31:08<45:39, 22.35it/s]

 39%|███▉      | 39387/100629 [31:08<52:56, 19.28it/s]

 39%|███▉      | 39390/100629 [31:08<48:24, 21.09it/s]

 39%|███▉      | 39393/100629 [31:08<56:15, 18.14it/s]

 39%|███▉      | 39396/100629 [31:09<1:00:33, 16.85it/s]

 39%|███▉      | 39400/100629 [31:09<50:57, 20.03it/s]

 39%|███▉      | 39403/100629 [31:09<49:36, 20.57it/s]

 39%|███▉      | 39406/100629 [31:09<55:16, 18.46it/s]

 39%|███▉      | 39410/100629 [31:09<45:35, 22.38it/s]

 39%|███▉      | 39413/100629 [31:09<51:15, 19.91it/s]

 39%|███▉      | 39416/100629 [31:10<51:39, 19.75it/s]

 39%|███▉      | 39420/100629 [31:10<45:38, 22.35it/s]

 39%|███▉      | 39426/100629 [31:10<33:30, 30.44it/s]

 39%|███▉      | 39431/100629 [31:10<30:33, 33.37it/s]

 39%|███▉      | 39435/100629 [31:10<31:54, 31.97it/s]

 39%|███▉      | 39439/100629 [31:10<31:07, 32.76it/s]

 39%|███▉      | 39443/100629 [31:10<35:30, 28.71it/s]

 39%|███▉      | 39447/100629 [31:11<37:48, 26.97it/s]

 39%|███▉      | 39450/100629 [31:11<55:33, 18.35it/s]

 39%|███▉      | 39453/100629 [31:11<1:00:36, 16.82it/s]

 39%|███▉      | 39456/100629 [31:11<54:44, 18.63it/s]

 39%|███▉      | 39459/100629 [31:11<53:40, 19.00it/s]

 39%|███▉      | 39462/100629 [31:12<52:43, 19.34it/s]

 39%|███▉      | 39465/100629 [31:12<53:27, 19.07it/s]

 39%|███▉      | 39469/100629 [31:12<46:45, 21.80it/s]

 39%|███▉      | 39472/100629 [31:12<48:41, 20.93it/s]

 39%|███▉      | 39475/100629 [31:12<46:30, 21.92it/s]

 39%|███▉      | 39479/100629 [31:12<43:08, 23.63it/s]

 39%|███▉      | 39483/100629 [31:12<38:44, 26.31it/s]

 39%|███▉      | 39486/100629 [31:12<41:20, 24.65it/s]

 39%|███▉      | 39490/100629 [31:13<39:53, 25.54it/s]

 39%|███▉      | 39494/100629 [31:13<36:48, 27.69it/s]

 39%|███▉      | 39497/100629 [31:13<38:54, 26.19it/s]

 39%|███▉      | 39501/100629 [31:13<35:22, 28.80it/s]

 39%|███▉      | 39504/100629 [31:13<35:34, 28.64it/s]

 39%|███▉      | 39508/100629 [31:13<38:03, 26.77it/s]

 39%|███▉      | 39511/100629 [31:13<41:14, 24.70it/s]

 39%|███▉      | 39514/100629 [31:14<47:50, 21.29it/s]

 39%|███▉      | 39517/100629 [31:14<46:41, 21.81it/s]

 39%|███▉      | 39520/100629 [31:14<48:20, 21.07it/s]

 39%|███▉      | 39524/100629 [31:14<41:12, 24.71it/s]

 39%|███▉      | 39527/100629 [31:14<44:01, 23.13it/s]

 39%|███▉      | 39530/100629 [31:14<43:45, 23.27it/s]

 39%|███▉      | 39533/100629 [31:14<49:54, 20.41it/s]

 39%|███▉      | 39536/100629 [31:15<56:17, 18.09it/s]

 39%|███▉      | 39539/100629 [31:15<50:56, 19.99it/s]

 39%|███▉      | 39542/100629 [31:15<47:00, 21.66it/s]

 39%|███▉      | 39545/100629 [31:15<50:22, 20.21it/s]

 39%|███▉      | 39548/100629 [31:15<46:18, 21.99it/s]

 39%|███▉      | 39553/100629 [31:15<38:40, 26.32it/s]

 39%|███▉      | 39556/100629 [31:15<38:54, 26.16it/s]

 39%|███▉      | 39561/100629 [31:16<31:51, 31.95it/s]

 39%|███▉      | 39565/100629 [31:16<41:21, 24.61it/s]

 39%|███▉      | 39568/100629 [31:16<40:46, 24.95it/s]

 39%|███▉      | 39571/100629 [31:16<41:31, 24.50it/s]

 39%|███▉      | 39574/100629 [31:16<46:11, 22.03it/s]

 39%|███▉      | 39577/100629 [31:16<44:21, 22.94it/s]

 39%|███▉      | 39580/100629 [31:17<48:33, 20.95it/s]

 39%|███▉      | 39583/100629 [31:17<44:30, 22.86it/s]

 39%|███▉      | 39586/100629 [31:17<47:21, 21.48it/s]

 39%|███▉      | 39589/100629 [31:17<43:28, 23.40it/s]

 39%|███▉      | 39592/100629 [31:17<46:39, 21.80it/s]

 39%|███▉      | 39595/100629 [31:17<50:58, 19.95it/s]

 39%|███▉      | 39598/100629 [31:17<51:54, 19.60it/s]

 39%|███▉      | 39601/100629 [31:18<56:58, 17.85it/s]

 39%|███▉      | 39603/100629 [31:18<57:47, 17.60it/s]

 39%|███▉      | 39606/100629 [31:18<51:54, 19.60it/s]

 39%|███▉      | 39609/100629 [31:18<50:30, 20.13it/s]

 39%|███▉      | 39614/100629 [31:18<42:05, 24.16it/s]

 39%|███▉      | 39617/100629 [31:18<47:00, 21.63it/s]

 39%|███▉      | 39621/100629 [31:18<40:47, 24.93it/s]

 39%|███▉      | 39624/100629 [31:19<44:23, 22.91it/s]

 39%|███▉      | 39627/100629 [31:19<49:07, 20.69it/s]

 39%|███▉      | 39630/100629 [31:19<49:43, 20.45it/s]

 39%|███▉      | 39633/100629 [31:19<47:57, 21.20it/s]

 39%|███▉      | 39636/100629 [31:19<54:26, 18.67it/s]

 39%|███▉      | 39639/100629 [31:19<48:44, 20.86it/s]

 39%|███▉      | 39642/100629 [31:19<48:27, 20.97it/s]

 39%|███▉      | 39645/100629 [31:20<51:06, 19.89it/s]

 39%|███▉      | 39648/100629 [31:20<47:13, 21.52it/s]

 39%|███▉      | 39651/100629 [31:20<45:28, 22.35it/s]

 39%|███▉      | 39654/100629 [31:20<50:41, 20.05it/s]

 39%|███▉      | 39657/100629 [31:20<49:47, 20.41it/s]

 39%|███▉      | 39660/100629 [31:20<48:49, 20.81it/s]

 39%|███▉      | 39663/100629 [31:21<51:53, 19.58it/s]

 39%|███▉      | 39666/100629 [31:21<48:54, 20.78it/s]

 39%|███▉      | 39669/100629 [31:21<45:59, 22.09it/s]

 39%|███▉      | 39673/100629 [31:21<39:53, 25.47it/s]

 39%|███▉      | 39676/100629 [31:21<43:07, 23.55it/s]

 39%|███▉      | 39679/100629 [31:21<44:32, 22.80it/s]

 39%|███▉      | 39683/100629 [31:21<44:53, 22.62it/s]

 39%|███▉      | 39686/100629 [31:22<52:19, 19.41it/s]

 39%|███▉      | 39689/100629 [31:22<48:22, 20.99it/s]

 39%|███▉      | 39692/100629 [31:22<46:45, 21.72it/s]

 39%|███▉      | 39695/100629 [31:22<45:47, 22.18it/s]

 39%|███▉      | 39698/100629 [31:22<46:51, 21.67it/s]

 39%|███▉      | 39701/100629 [31:22<53:03, 19.14it/s]

 39%|███▉      | 39704/100629 [31:22<50:11, 20.23it/s]

 39%|███▉      | 39707/100629 [31:22<46:28, 21.85it/s]

 39%|███▉      | 39710/100629 [31:23<43:35, 23.29it/s]

 39%|███▉      | 39714/100629 [31:23<39:07, 25.95it/s]

 39%|███▉      | 39717/100629 [31:23<40:25, 25.11it/s]

 39%|███▉      | 39720/100629 [31:23<48:16, 21.03it/s]

 39%|███▉      | 39723/100629 [31:23<53:20, 19.03it/s]

 39%|███▉      | 39726/100629 [31:23<51:05, 19.87it/s]

 39%|███▉      | 39729/100629 [31:24<48:31, 20.92it/s]

 39%|███▉      | 39732/100629 [31:24<47:48, 21.23it/s]

 39%|███▉      | 39736/100629 [31:24<42:03, 24.13it/s]

 39%|███▉      | 39741/100629 [31:24<41:09, 24.66it/s]

 39%|███▉      | 39744/100629 [31:24<43:22, 23.39it/s]

 39%|███▉      | 39747/100629 [31:24<43:01, 23.58it/s]

 40%|███▉      | 39751/100629 [31:24<41:19, 24.55it/s]

 40%|███▉      | 39754/100629 [31:25<41:51, 24.24it/s]

 40%|███▉      | 39757/100629 [31:25<54:18, 18.68it/s]

 40%|███▉      | 39760/100629 [31:25<1:02:57, 16.12it/s]

 40%|███▉      | 39763/100629 [31:25<56:14, 18.04it/s]

 40%|███▉      | 39766/100629 [31:25<56:49, 17.85it/s]

 40%|███▉      | 39769/100629 [31:25<56:24, 17.98it/s]

 40%|███▉      | 39772/100629 [31:26<51:42, 19.62it/s]

 40%|███▉      | 39775/100629 [31:26<54:57, 18.45it/s]

 40%|███▉      | 39778/100629 [31:26<50:04, 20.25it/s]

 40%|███▉      | 39782/100629 [31:26<42:33, 23.83it/s]

 40%|███▉      | 39785/100629 [31:26<46:19, 21.89it/s]

 40%|███▉      | 39788/100629 [31:26<46:16, 21.91it/s]

 40%|███▉      | 39793/100629 [31:26<37:39, 26.92it/s]

 40%|███▉      | 39797/100629 [31:27<38:37, 26.25it/s]

 40%|███▉      | 39800/100629 [31:27<42:18, 23.96it/s]

 40%|███▉      | 39803/100629 [31:27<44:17, 22.89it/s]

 40%|███▉      | 39806/100629 [31:27<48:00, 21.12it/s]

 40%|███▉      | 39809/100629 [31:27<59:22, 17.07it/s]

 40%|███▉      | 39812/100629 [31:27<54:02, 18.76it/s]

 40%|███▉      | 39815/100629 [31:28<1:27:14, 11.62it/s]

 40%|███▉      | 39818/100629 [31:28<1:14:52, 13.54it/s]

 40%|███▉      | 39820/100629 [31:28<1:10:07, 14.45it/s]

 40%|███▉      | 39822/100629 [31:28<1:10:56, 14.29it/s]

 40%|███▉      | 39825/100629 [31:28<1:02:00, 16.34it/s]

 40%|███▉      | 39827/100629 [31:29<1:09:00, 14.69it/s]

 40%|███▉      | 39829/100629 [31:29<1:09:50, 14.51it/s]

 40%|███▉      | 39831/100629 [31:29<1:06:14, 15.30it/s]

 40%|███▉      | 39834/100629 [31:29<56:22, 17.97it/s]

 40%|███▉      | 39837/100629 [31:29<56:44, 17.85it/s]

 40%|███▉      | 39839/100629 [31:29<56:05, 18.06it/s]

 40%|███▉      | 39842/100629 [31:29<50:09, 20.20it/s]

 40%|███▉      | 39845/100629 [31:30<50:51, 19.92it/s]

 40%|███▉      | 39848/100629 [31:30<1:01:18, 16.52it/s]

 40%|███▉      | 39850/100629 [31:30<1:14:18, 13.63it/s]

 40%|███▉      | 39853/100629 [31:30<1:03:42, 15.90it/s]

 40%|███▉      | 39855/100629 [31:30<1:00:54, 16.63it/s]

 40%|███▉      | 39859/100629 [31:30<50:46, 19.95it/s]

 40%|███▉      | 39862/100629 [31:31<52:32, 19.27it/s]

 40%|███▉      | 39865/100629 [31:31<49:47, 20.34it/s]

 40%|███▉      | 39868/100629 [31:31<52:20, 19.35it/s]

 40%|███▉      | 39871/100629 [31:31<57:23, 17.65it/s]

 40%|███▉      | 39874/100629 [31:31<52:29, 19.29it/s]

 40%|███▉      | 39878/100629 [31:31<49:52, 20.30it/s]

 40%|███▉      | 39881/100629 [31:32<58:38, 17.27it/s]

 40%|███▉      | 39885/100629 [31:32<47:20, 21.38it/s]

 40%|███▉      | 39889/100629 [31:32<41:36, 24.33it/s]

 40%|███▉      | 39893/100629 [31:32<41:55, 24.15it/s]

 40%|███▉      | 39896/100629 [31:32<46:29, 21.77it/s]

 40%|███▉      | 39901/100629 [31:32<36:50, 27.48it/s]

 40%|███▉      | 39905/100629 [31:32<35:44, 28.31it/s]

 40%|███▉      | 39909/100629 [31:33<35:48, 28.27it/s]

 40%|███▉      | 39912/100629 [31:33<39:38, 25.53it/s]

 40%|███▉      | 39915/100629 [31:33<43:29, 23.27it/s]

 40%|███▉      | 39918/100629 [31:33<47:59, 21.08it/s]

 40%|███▉      | 39921/100629 [31:33<46:54, 21.57it/s]

 40%|███▉      | 39924/100629 [31:33<47:20, 21.37it/s]

 40%|███▉      | 39927/100629 [31:34<52:05, 19.42it/s]

 40%|███▉      | 39930/100629 [31:34<48:46, 20.74it/s]

 40%|███▉      | 39933/100629 [31:34<46:26, 21.78it/s]

 40%|███▉      | 39937/100629 [31:34<40:56, 24.71it/s]

 40%|███▉      | 39941/100629 [31:34<36:42, 27.56it/s]

 40%|███▉      | 39944/100629 [31:34<39:36, 25.53it/s]

 40%|███▉      | 39947/100629 [31:34<44:25, 22.77it/s]

 40%|███▉      | 39950/100629 [31:34<45:57, 22.01it/s]

 40%|███▉      | 39953/100629 [31:35<43:12, 23.41it/s]

 40%|███▉      | 39956/100629 [31:35<46:58, 21.53it/s]

 40%|███▉      | 39960/100629 [31:35<44:16, 22.84it/s]

 40%|███▉      | 39963/100629 [31:35<44:13, 22.86it/s]

 40%|███▉      | 39966/100629 [31:35<57:56, 17.45it/s]

 40%|███▉      | 39969/100629 [31:35<58:38, 17.24it/s]

 40%|███▉      | 39971/100629 [31:36<1:01:16, 16.50it/s]

 40%|███▉      | 39974/100629 [31:36<54:24, 18.58it/s]

 40%|███▉      | 39977/100629 [31:36<51:13, 19.73it/s]

 40%|███▉      | 39980/100629 [31:36<47:11, 21.42it/s]

 40%|███▉      | 39983/100629 [31:36<44:42, 22.61it/s]

 40%|███▉      | 39987/100629 [31:36<42:14, 23.93it/s]

 40%|███▉      | 39990/100629 [31:36<47:04, 21.47it/s]

 40%|███▉      | 39993/100629 [31:37<45:33, 22.18it/s]

 40%|███▉      | 39997/100629 [31:37<40:06, 25.19it/s]

 40%|███▉      | 40000/100629 [31:37<46:15, 21.84it/s]

 40%|███▉      | 40003/100629 [31:37<45:09, 22.38it/s]

 40%|███▉      | 40006/100629 [31:37<42:52, 23.56it/s]

 40%|███▉      | 40009/100629 [31:37<45:54, 22.01it/s]

 40%|███▉      | 40013/100629 [31:37<44:30, 22.70it/s]

 40%|███▉      | 40017/100629 [31:38<42:39, 23.68it/s]

 40%|███▉      | 40020/100629 [31:38<42:25, 23.81it/s]

 40%|███▉      | 40023/100629 [31:38<42:59, 23.49it/s]

 40%|███▉      | 40026/100629 [31:38<44:23, 22.76it/s]

 40%|███▉      | 40029/100629 [31:38<41:44, 24.19it/s]

 40%|███▉      | 40032/100629 [31:38<41:46, 24.18it/s]

 40%|███▉      | 40035/100629 [31:38<43:21, 23.30it/s]

 40%|███▉      | 40040/100629 [31:38<38:01, 26.56it/s]

 40%|███▉      | 40043/100629 [31:39<44:13, 22.83it/s]

 40%|███▉      | 40046/100629 [31:39<41:38, 24.25it/s]

 40%|███▉      | 40050/100629 [31:39<37:38, 26.82it/s]

 40%|███▉      | 40053/100629 [31:39<44:30, 22.69it/s]

 40%|███▉      | 40056/100629 [31:39<45:32, 22.16it/s]

 40%|███▉      | 40060/100629 [31:39<41:13, 24.48it/s]

 40%|███▉      | 40063/100629 [31:39<40:47, 24.74it/s]

 40%|███▉      | 40066/100629 [31:40<39:38, 25.47it/s]

 40%|███▉      | 40070/100629 [31:40<34:47, 29.01it/s]

 40%|███▉      | 40074/100629 [31:40<32:44, 30.82it/s]

 40%|███▉      | 40078/100629 [31:40<34:01, 29.66it/s]

 40%|███▉      | 40082/100629 [31:40<42:45, 23.60it/s]

 40%|███▉      | 40085/100629 [31:40<44:19, 22.76it/s]

 40%|███▉      | 40088/100629 [31:40<44:06, 22.88it/s]

 40%|███▉      | 40091/100629 [31:41<42:40, 23.64it/s]

 40%|███▉      | 40094/100629 [31:41<43:45, 23.05it/s]

 40%|███▉      | 40097/100629 [31:41<43:55, 22.97it/s]

 40%|███▉      | 40100/100629 [31:41<46:36, 21.65it/s]

 40%|███▉      | 40103/100629 [31:41<43:11, 23.35it/s]

 40%|███▉      | 40107/100629 [31:41<38:10, 26.43it/s]

 40%|███▉      | 40111/100629 [31:41<36:19, 27.76it/s]

 40%|███▉      | 40114/100629 [31:41<36:57, 27.29it/s]

 40%|███▉      | 40117/100629 [31:42<41:47, 24.13it/s]

 40%|███▉      | 40121/100629 [31:42<38:45, 26.02it/s]

 40%|███▉      | 40124/100629 [31:42<41:32, 24.28it/s]

 40%|███▉      | 40127/100629 [31:42<44:49, 22.49it/s]

 40%|███▉      | 40130/100629 [31:42<45:02, 22.39it/s]

 40%|███▉      | 40133/100629 [31:42<47:03, 21.43it/s]

 40%|███▉      | 40136/100629 [31:43<47:01, 21.44it/s]

 40%|███▉      | 40139/100629 [31:43<46:28, 21.69it/s]

 40%|███▉      | 40142/100629 [31:43<45:54, 21.96it/s]

 40%|███▉      | 40145/100629 [31:43<44:43, 22.54it/s]

 40%|███▉      | 40148/100629 [31:43<55:24, 18.19it/s]

 40%|███▉      | 40152/100629 [31:43<45:45, 22.03it/s]

 40%|███▉      | 40156/100629 [31:43<40:16, 25.03it/s]

 40%|███▉      | 40159/100629 [31:44<43:40, 23.08it/s]

 40%|███▉      | 40162/100629 [31:44<43:22, 23.24it/s]

 40%|███▉      | 40165/100629 [31:44<43:57, 22.92it/s]

 40%|███▉      | 40168/100629 [31:44<45:44, 22.03it/s]

 40%|███▉      | 40171/100629 [31:44<45:34, 22.11it/s]

 40%|███▉      | 40175/100629 [31:44<39:33, 25.47it/s]

 40%|███▉      | 40179/100629 [31:44<36:13, 27.81it/s]

 40%|███▉      | 40182/100629 [31:44<39:16, 25.65it/s]

 40%|███▉      | 40185/100629 [31:45<43:41, 23.05it/s]

 40%|███▉      | 40188/100629 [31:45<44:32, 22.62it/s]

 40%|███▉      | 40192/100629 [31:45<40:31, 24.85it/s]

 40%|███▉      | 40196/100629 [31:45<37:32, 26.83it/s]

 40%|███▉      | 40199/100629 [31:45<41:46, 24.11it/s]

 40%|███▉      | 40202/100629 [31:45<42:36, 23.63it/s]

 40%|███▉      | 40207/100629 [31:45<40:19, 24.98it/s]

 40%|███▉      | 40210/100629 [31:46<40:44, 24.72it/s]

 40%|███▉      | 40213/100629 [31:46<47:49, 21.06it/s]

 40%|███▉      | 40216/100629 [31:46<44:45, 22.50it/s]

 40%|███▉      | 40219/100629 [31:46<43:58, 22.89it/s]

 40%|███▉      | 40222/100629 [31:46<42:49, 23.51it/s]

 40%|███▉      | 40225/100629 [31:46<42:03, 23.93it/s]

 40%|███▉      | 40228/100629 [31:46<42:47, 23.52it/s]

 40%|███▉      | 40233/100629 [31:47<35:47, 28.12it/s]

 40%|███▉      | 40236/100629 [31:47<40:20, 24.95it/s]

 40%|███▉      | 40239/100629 [31:47<48:48, 20.62it/s]

 40%|███▉      | 40242/100629 [31:47<47:06, 21.36it/s]

 40%|███▉      | 40245/100629 [31:47<52:21, 19.22it/s]

 40%|███▉      | 40248/100629 [31:47<49:40, 20.26it/s]

 40%|███▉      | 40251/100629 [31:48<1:01:30, 16.36it/s]

 40%|████      | 40253/100629 [31:48<1:14:29, 13.51it/s]

 40%|████      | 40256/100629 [31:48<1:08:24, 14.71it/s]

 40%|████      | 40259/100629 [31:48<1:01:38, 16.32it/s]

 40%|████      | 40262/100629 [31:48<1:01:18, 16.41it/s]

 40%|████      | 40264/100629 [31:49<1:18:13, 12.86it/s]

 40%|████      | 40266/100629 [31:49<1:14:00, 13.59it/s]

 40%|████      | 40271/100629 [31:49<55:02, 18.27it/s]

 40%|████      | 40274/100629 [31:49<51:56, 19.37it/s]

 40%|████      | 40277/100629 [31:49<57:17, 17.56it/s]

 40%|████      | 40280/100629 [31:49<54:56, 18.31it/s]

 40%|████      | 40282/100629 [31:50<55:35, 18.09it/s]

 40%|████      | 40284/100629 [31:50<55:35, 18.09it/s]

 40%|████      | 40287/100629 [31:50<50:35, 19.88it/s]

 40%|████      | 40290/100629 [31:50<45:08, 22.28it/s]

 40%|████      | 40293/100629 [31:50<56:28, 17.80it/s]

 40%|████      | 40296/100629 [31:50<49:21, 20.37it/s]

 40%|████      | 40299/100629 [31:50<58:48, 17.10it/s]

 40%|████      | 40301/100629 [31:51<1:01:12, 16.43it/s]

 40%|████      | 40303/100629 [31:51<1:18:46, 12.76it/s]

 40%|████      | 40305/100629 [31:51<1:13:59, 13.59it/s]

 40%|████      | 40308/100629 [31:51<59:56, 16.77it/s]

 40%|████      | 40312/100629 [31:51<1:02:04, 16.20it/s]

 40%|████      | 40315/100629 [31:51<54:14, 18.54it/s]

 40%|████      | 40318/100629 [31:52<50:20, 19.97it/s]

 40%|████      | 40321/100629 [31:52<56:00, 17.95it/s]

 40%|████      | 40324/100629 [31:52<50:23, 19.95it/s]

 40%|████      | 40327/100629 [31:52<50:05, 20.06it/s]

 40%|████      | 40330/100629 [31:52<49:59, 20.10it/s]

 40%|████      | 40333/100629 [31:52<49:46, 20.19it/s]

 40%|████      | 40336/100629 [31:52<46:30, 21.61it/s]

 40%|████      | 40339/100629 [31:53<43:12, 23.25it/s]

 40%|████      | 40342/100629 [31:53<41:33, 24.18it/s]

 40%|████      | 40345/100629 [31:53<47:59, 20.94it/s]

 40%|████      | 40348/100629 [31:53<49:58, 20.10it/s]

 40%|████      | 40351/100629 [31:53<53:10, 18.89it/s]

 40%|████      | 40353/100629 [31:53<1:02:06, 16.18it/s]

 40%|████      | 40355/100629 [31:54<1:11:06, 14.13it/s]

 40%|████      | 40357/100629 [31:54<1:09:40, 14.42it/s]

 40%|████      | 40359/100629 [31:54<1:08:25, 14.68it/s]

 40%|████      | 40363/100629 [31:54<50:40, 19.82it/s]

 40%|████      | 40366/100629 [31:54<49:20, 20.36it/s]

 40%|████      | 40369/100629 [31:54<46:37, 21.54it/s]

 40%|████      | 40373/100629 [31:54<39:06, 25.68it/s]

 40%|████      | 40376/100629 [31:54<38:57, 25.78it/s]

 40%|████      | 40380/100629 [31:55<35:04, 28.63it/s]

 40%|████      | 40383/100629 [31:55<35:24, 28.36it/s]

 40%|████      | 40386/100629 [31:55<38:09, 26.31it/s]

 40%|████      | 40391/100629 [31:55<37:24, 26.84it/s]

 40%|████      | 40394/100629 [31:55<37:23, 26.84it/s]

 40%|████      | 40397/100629 [31:55<39:02, 25.71it/s]

 40%|████      | 40403/100629 [31:55<30:30, 32.91it/s]

 40%|████      | 40407/100629 [31:55<31:56, 31.43it/s]

 40%|████      | 40411/100629 [31:56<34:20, 29.23it/s]

 40%|████      | 40414/100629 [31:56<35:01, 28.66it/s]

 40%|████      | 40417/100629 [31:56<43:34, 23.03it/s]

 40%|████      | 40421/100629 [31:56<40:10, 24.97it/s]

 40%|████      | 40425/100629 [31:56<49:55, 20.10it/s]

 40%|████      | 40428/100629 [31:56<48:51, 20.54it/s]

 40%|████      | 40432/100629 [31:57<42:25, 23.65it/s]

 40%|████      | 40436/100629 [31:57<40:04, 25.03it/s]

 40%|████      | 40439/100629 [31:57<43:49, 22.89it/s]

 40%|████      | 40442/100629 [31:57<43:46, 22.92it/s]

 40%|████      | 40445/100629 [31:57<53:39, 18.69it/s]

 40%|████      | 40448/100629 [31:57<52:07, 19.24it/s]

 40%|████      | 40451/100629 [31:58<50:36, 19.82it/s]

 40%|████      | 40454/100629 [31:58<51:09, 19.61it/s]

 40%|████      | 40457/100629 [31:58<50:50, 19.73it/s]

 40%|████      | 40460/100629 [31:58<55:26, 18.09it/s]

 40%|████      | 40463/100629 [31:58<52:09, 19.22it/s]

 40%|████      | 40465/100629 [31:58<53:09, 18.86it/s]

 40%|████      | 40468/100629 [31:58<47:23, 21.16it/s]

 40%|████      | 40471/100629 [31:59<54:34, 18.37it/s]

 40%|████      | 40475/100629 [31:59<48:23, 20.72it/s]

 40%|████      | 40478/100629 [31:59<46:21, 21.63it/s]

 40%|████      | 40481/100629 [31:59<42:47, 23.43it/s]

 40%|████      | 40484/100629 [31:59<50:39, 19.79it/s]

 40%|████      | 40487/100629 [31:59<51:10, 19.59it/s]

 40%|████      | 40490/100629 [31:59<49:07, 20.40it/s]

 40%|████      | 40493/100629 [32:00<47:36, 21.05it/s]

 40%|████      | 40496/100629 [32:00<53:49, 18.62it/s]

 40%|████      | 40498/100629 [32:00<53:28, 18.74it/s]

 40%|████      | 40501/100629 [32:00<47:30, 21.09it/s]

 40%|████      | 40504/100629 [32:00<47:51, 20.94it/s]

 40%|████      | 40507/100629 [32:00<46:42, 21.46it/s]

 40%|████      | 40510/100629 [32:01<52:09, 19.21it/s]

 40%|████      | 40514/100629 [32:01<46:09, 21.70it/s]

 40%|████      | 40517/100629 [32:01<48:33, 20.63it/s]

 40%|████      | 40520/100629 [32:01<49:38, 20.18it/s]

 40%|████      | 40523/100629 [32:01<55:34, 18.03it/s]

 40%|████      | 40525/100629 [32:01<57:24, 17.45it/s]

 40%|████      | 40527/100629 [32:01<1:00:18, 16.61it/s]

 40%|████      | 40531/100629 [32:02<58:46, 17.04it/s]

 40%|████      | 40533/100629 [32:02<57:11, 17.51it/s]

 40%|████      | 40535/100629 [32:02<57:23, 17.45it/s]

 40%|████      | 40538/100629 [32:02<50:35, 19.80it/s]

 40%|████      | 40541/100629 [32:02<46:25, 21.57it/s]

 40%|████      | 40544/100629 [32:02<52:59, 18.89it/s]

 40%|████      | 40547/100629 [32:02<48:23, 20.69it/s]

 40%|████      | 40550/100629 [32:03<47:32, 21.06it/s]

 40%|████      | 40553/100629 [32:03<49:41, 20.15it/s]

 40%|████      | 40557/100629 [32:03<41:53, 23.90it/s]

 40%|████      | 40560/100629 [32:03<43:23, 23.07it/s]

 40%|████      | 40563/100629 [32:03<41:38, 24.05it/s]

 40%|████      | 40566/100629 [32:03<43:17, 23.12it/s]

 40%|████      | 40569/100629 [32:03<40:55, 24.46it/s]

 40%|████      | 40573/100629 [32:03<36:52, 27.14it/s]

 40%|████      | 40576/100629 [32:04<36:17, 27.58it/s]

 40%|████      | 40579/100629 [32:04<56:57, 17.57it/s]

 40%|████      | 40582/100629 [32:04<51:18, 19.51it/s]

 40%|████      | 40585/100629 [32:04<49:58, 20.02it/s]

 40%|████      | 40588/100629 [32:04<57:46, 17.32it/s]

 40%|████      | 40592/100629 [32:05<47:51, 20.91it/s]

 40%|████      | 40596/100629 [32:05<40:09, 24.92it/s]

 40%|████      | 40599/100629 [32:05<41:07, 24.33it/s]

 40%|████      | 40602/100629 [32:05<39:27, 25.35it/s]

 40%|████      | 40605/100629 [32:05<40:53, 24.46it/s]

 40%|████      | 40608/100629 [32:05<42:25, 23.58it/s]

 40%|████      | 40612/100629 [32:05<37:47, 26.47it/s]

 40%|████      | 40615/100629 [32:05<40:18, 24.81it/s]

 40%|████      | 40620/100629 [32:05<33:48, 29.58it/s]

 40%|████      | 40624/100629 [32:06<34:18, 29.16it/s]

 40%|████      | 40627/100629 [32:06<34:39, 28.85it/s]

 40%|████      | 40631/100629 [32:06<37:59, 26.32it/s]

 40%|████      | 40634/100629 [32:06<38:39, 25.87it/s]

 40%|████      | 40637/100629 [32:06<41:03, 24.35it/s]

 40%|████      | 40640/100629 [32:06<40:16, 24.83it/s]

 40%|████      | 40643/100629 [32:06<39:50, 25.09it/s]

 40%|████      | 40646/100629 [32:07<43:23, 23.04it/s]

 40%|████      | 40649/100629 [32:07<48:52, 20.45it/s]

 40%|████      | 40652/100629 [32:07<49:49, 20.06it/s]

 40%|████      | 40655/100629 [32:07<52:04, 19.19it/s]

 40%|████      | 40657/100629 [32:07<1:01:25, 16.27it/s]

 40%|████      | 40660/100629 [32:07<56:22, 17.73it/s]

 40%|████      | 40663/100629 [32:08<51:24, 19.44it/s]

 40%|████      | 40666/100629 [32:08<48:42, 20.52it/s]

 40%|████      | 40669/100629 [32:08<48:00, 20.82it/s]

 40%|████      | 40674/100629 [32:08<37:35, 26.58it/s]

 40%|████      | 40677/100629 [32:08<41:39, 23.99it/s]

 40%|████      | 40680/100629 [32:08<50:37, 19.73it/s]

 40%|████      | 40683/100629 [32:08<47:12, 21.17it/s]

 40%|████      | 40686/100629 [32:09<47:09, 21.18it/s]

 40%|████      | 40689/100629 [32:09<46:02, 21.70it/s]

 40%|████      | 40694/100629 [32:09<45:15, 22.07it/s]

 40%|████      | 40697/100629 [32:09<42:32, 23.48it/s]

 40%|████      | 40700/100629 [32:09<46:02, 21.69it/s]

 40%|████      | 40703/100629 [32:09<45:33, 21.92it/s]

 40%|████      | 40706/100629 [32:09<43:53, 22.75it/s]

 40%|████      | 40709/100629 [32:10<41:04, 24.32it/s]

 40%|████      | 40712/100629 [32:10<46:29, 21.48it/s]

 40%|████      | 40715/100629 [32:10<55:24, 18.02it/s]

 40%|████      | 40718/100629 [32:10<49:38, 20.11it/s]

 40%|████      | 40722/100629 [32:10<42:13, 23.64it/s]

 40%|████      | 40725/100629 [32:10<40:38, 24.57it/s]

 40%|████      | 40728/100629 [32:10<38:33, 25.89it/s]

 40%|████      | 40731/100629 [32:11<47:11, 21.16it/s]

 40%|████      | 40734/100629 [32:11<51:13, 19.49it/s]

 40%|████      | 40737/100629 [32:11<49:47, 20.05it/s]

 40%|████      | 40741/100629 [32:11<42:02, 23.74it/s]

 40%|████      | 40745/100629 [32:11<36:20, 27.47it/s]

 40%|████      | 40748/100629 [32:11<42:28, 23.50it/s]

 40%|████      | 40751/100629 [32:11<45:47, 21.79it/s]

 40%|████      | 40754/100629 [32:12<45:21, 22.00it/s]

 41%|████      | 40757/100629 [32:12<45:51, 21.76it/s]

 41%|████      | 40760/100629 [32:12<48:32, 20.55it/s]

 41%|████      | 40763/100629 [32:12<44:40, 22.33it/s]

 41%|████      | 40766/100629 [32:12<45:42, 21.83it/s]

 41%|████      | 40769/100629 [32:12<54:59, 18.14it/s]

 41%|████      | 40771/100629 [32:13<57:11, 17.44it/s]

 41%|████      | 40773/100629 [32:13<59:02, 16.90it/s]

 41%|████      | 40775/100629 [32:13<57:16, 17.42it/s]

 41%|████      | 40778/100629 [32:13<53:23, 18.69it/s]

 41%|████      | 40781/100629 [32:13<57:35, 17.32it/s]

 41%|████      | 40784/100629 [32:13<56:17, 17.72it/s]

 41%|████      | 40787/100629 [32:13<51:57, 19.19it/s]

 41%|████      | 40789/100629 [32:13<51:56, 19.20it/s]

 41%|████      | 40791/100629 [32:14<55:38, 17.92it/s]

 41%|████      | 40795/100629 [32:14<46:01, 21.67it/s]

 41%|████      | 40799/100629 [32:14<40:55, 24.36it/s]

 41%|████      | 40802/100629 [32:14<40:56, 24.36it/s]

 41%|████      | 40805/100629 [32:14<42:10, 23.64it/s]

 41%|████      | 40809/100629 [32:14<38:29, 25.90it/s]

 41%|████      | 40812/100629 [32:14<45:47, 21.77it/s]

 41%|████      | 40816/100629 [32:15<42:31, 23.44it/s]

 41%|████      | 40820/100629 [32:15<42:09, 23.64it/s]

 41%|████      | 40823/100629 [32:15<41:28, 24.03it/s]

 41%|████      | 40826/100629 [32:15<48:10, 20.69it/s]

 41%|████      | 40829/100629 [32:15<52:32, 18.97it/s]

 41%|████      | 40831/100629 [32:15<54:12, 18.39it/s]

 41%|████      | 40834/100629 [32:16<54:52, 18.16it/s]

 41%|████      | 40836/100629 [32:16<56:02, 17.78it/s]

 41%|████      | 40839/100629 [32:16<53:16, 18.70it/s]

 41%|████      | 40842/100629 [32:16<49:43, 20.04it/s]

 41%|████      | 40845/100629 [32:16<45:54, 21.70it/s]

 41%|████      | 40848/100629 [32:16<45:18, 21.99it/s]

 41%|████      | 40851/100629 [32:16<47:32, 20.96it/s]

 41%|████      | 40854/100629 [32:16<44:23, 22.45it/s]

 41%|████      | 40857/100629 [32:17<53:09, 18.74it/s]

 41%|████      | 40860/100629 [32:17<55:14, 18.03it/s]

 41%|████      | 40864/100629 [32:17<48:34, 20.51it/s]

 41%|████      | 40867/100629 [32:17<46:14, 21.54it/s]

 41%|████      | 40870/100629 [32:17<51:47, 19.23it/s]

 41%|████      | 40873/100629 [32:18<52:49, 18.85it/s]

 41%|████      | 40876/100629 [32:18<48:34, 20.51it/s]

 41%|████      | 40879/100629 [32:18<51:54, 19.18it/s]

 41%|████      | 40882/100629 [32:18<49:52, 19.96it/s]

 41%|████      | 40885/100629 [32:18<45:21, 21.96it/s]

 41%|████      | 40888/100629 [32:18<43:14, 23.02it/s]

 41%|████      | 40892/100629 [32:18<37:45, 26.36it/s]

 41%|████      | 40897/100629 [32:18<31:20, 31.77it/s]

 41%|████      | 40901/100629 [32:19<38:11, 26.06it/s]

 41%|████      | 40904/100629 [32:19<38:54, 25.58it/s]

 41%|████      | 40908/100629 [32:19<35:18, 28.19it/s]

 41%|████      | 40911/100629 [32:19<37:39, 26.42it/s]

 41%|████      | 40914/100629 [32:19<40:17, 24.70it/s]

 41%|████      | 40917/100629 [32:19<39:07, 25.44it/s]

 41%|████      | 40920/100629 [32:19<44:30, 22.36it/s]

 41%|████      | 40923/100629 [32:20<42:37, 23.34it/s]

 41%|████      | 40926/100629 [32:20<54:27, 18.27it/s]

 41%|████      | 40929/100629 [32:20<49:58, 19.91it/s]

 41%|████      | 40934/100629 [32:20<43:16, 22.99it/s]

 41%|████      | 40937/100629 [32:20<41:48, 23.79it/s]

 41%|████      | 40940/100629 [32:20<42:12, 23.57it/s]

 41%|████      | 40943/100629 [32:20<47:35, 20.91it/s]

 41%|████      | 40946/100629 [32:21<45:36, 21.81it/s]

 41%|████      | 40949/100629 [32:21<45:22, 21.92it/s]

 41%|████      | 40952/100629 [32:21<58:46, 16.92it/s]

 41%|████      | 40955/100629 [32:21<56:53, 17.48it/s]

 41%|████      | 40957/100629 [32:21<55:40, 17.86it/s]

 41%|████      | 40959/100629 [32:21<56:41, 17.54it/s]

 41%|████      | 40961/100629 [32:22<1:01:46, 16.10it/s]

 41%|████      | 40964/100629 [32:22<52:27, 18.96it/s]

 41%|████      | 40967/100629 [32:22<49:44, 19.99it/s]

 41%|████      | 40970/100629 [32:22<50:25, 19.72it/s]

 41%|████      | 40973/100629 [32:22<48:57, 20.31it/s]

 41%|████      | 40976/100629 [32:22<46:57, 21.17it/s]

 41%|████      | 40979/100629 [32:22<42:52, 23.18it/s]

 41%|████      | 40982/100629 [32:22<46:35, 21.34it/s]

 41%|████      | 40985/100629 [32:23<49:26, 20.10it/s]

 41%|████      | 40988/100629 [32:23<46:22, 21.44it/s]

 41%|████      | 40992/100629 [32:23<42:02, 23.64it/s]

 41%|████      | 40998/100629 [32:23<32:10, 30.88it/s]

 41%|████      | 41002/100629 [32:23<40:35, 24.48it/s]

 41%|████      | 41005/100629 [32:23<40:47, 24.36it/s]

 41%|████      | 41008/100629 [32:24<44:44, 22.21it/s]

 41%|████      | 41011/100629 [32:24<44:17, 22.43it/s]

 41%|████      | 41014/100629 [32:24<49:12, 20.19it/s]

 41%|████      | 41017/100629 [32:24<45:47, 21.70it/s]

 41%|████      | 41020/100629 [32:24<44:25, 22.36it/s]

 41%|████      | 41025/100629 [32:24<35:52, 27.69it/s]

 41%|████      | 41028/100629 [32:24<39:35, 25.09it/s]

 41%|████      | 41031/100629 [32:24<37:52, 26.23it/s]

 41%|████      | 41034/100629 [32:25<40:30, 24.52it/s]

 41%|████      | 41037/100629 [32:25<41:40, 23.84it/s]

 41%|████      | 41040/100629 [32:25<45:28, 21.84it/s]

 41%|████      | 41043/100629 [32:25<43:00, 23.09it/s]

 41%|████      | 41046/100629 [32:25<40:11, 24.71it/s]

 41%|████      | 41049/100629 [32:25<43:52, 22.63it/s]

 41%|████      | 41052/100629 [32:25<41:49, 23.74it/s]

 41%|████      | 41055/100629 [32:26<41:00, 24.21it/s]

 41%|████      | 41058/100629 [32:26<39:41, 25.02it/s]

 41%|████      | 41062/100629 [32:26<34:57, 28.40it/s]

 41%|████      | 41065/100629 [32:26<41:13, 24.08it/s]

 41%|████      | 41068/100629 [32:26<46:24, 21.39it/s]

 41%|████      | 41071/100629 [32:26<50:35, 19.62it/s]

 41%|████      | 41074/100629 [32:26<46:03, 21.55it/s]

 41%|████      | 41077/100629 [32:27<44:21, 22.38it/s]

 41%|████      | 41080/100629 [32:27<47:41, 20.81it/s]

 41%|████      | 41083/100629 [32:27<49:40, 19.98it/s]

 41%|████      | 41086/100629 [32:27<46:53, 21.16it/s]

 41%|████      | 41089/100629 [32:27<49:15, 20.15it/s]

 41%|████      | 41092/100629 [32:27<50:18, 19.72it/s]

 41%|████      | 41095/100629 [32:27<47:29, 20.90it/s]

 41%|████      | 41098/100629 [32:28<43:45, 22.68it/s]

 41%|████      | 41102/100629 [32:28<37:49, 26.23it/s]

 41%|████      | 41105/100629 [32:28<42:04, 23.58it/s]

 41%|████      | 41109/100629 [32:28<41:32, 23.88it/s]

 41%|████      | 41113/100629 [32:28<37:37, 26.36it/s]

 41%|████      | 41116/100629 [32:28<37:57, 26.14it/s]

 41%|████      | 41119/100629 [32:28<40:43, 24.36it/s]

 41%|████      | 41122/100629 [32:28<43:39, 22.71it/s]

 41%|████      | 41125/100629 [32:29<45:10, 21.95it/s]

 41%|████      | 41128/100629 [32:29<50:56, 19.47it/s]

 41%|████      | 41132/100629 [32:29<42:00, 23.60it/s]

 41%|████      | 41136/100629 [32:29<36:57, 26.83it/s]

 41%|████      | 41139/100629 [32:29<40:54, 24.23it/s]

 41%|████      | 41143/100629 [32:29<36:17, 27.31it/s]

 41%|████      | 41146/100629 [32:29<39:03, 25.38it/s]

 41%|████      | 41149/100629 [32:30<42:19, 23.42it/s]

 41%|████      | 41153/100629 [32:30<37:25, 26.49it/s]

 41%|████      | 41156/100629 [32:30<37:27, 26.46it/s]

 41%|████      | 41159/100629 [32:30<42:35, 23.27it/s]

 41%|████      | 41163/100629 [32:30<37:36, 26.35it/s]

 41%|████      | 41166/100629 [32:30<38:47, 25.55it/s]

 41%|████      | 41169/100629 [32:30<47:05, 21.04it/s]

 41%|████      | 41172/100629 [32:31<49:44, 19.92it/s]

 41%|████      | 41176/100629 [32:31<46:34, 21.27it/s]

 41%|████      | 41179/100629 [32:31<45:29, 21.78it/s]

 41%|████      | 41182/100629 [32:31<47:28, 20.87it/s]

 41%|████      | 41186/100629 [32:31<43:11, 22.94it/s]

 41%|████      | 41189/100629 [32:31<42:13, 23.46it/s]

 41%|████      | 41192/100629 [32:31<44:10, 22.42it/s]

 41%|████      | 41195/100629 [32:32<45:05, 21.97it/s]

 41%|████      | 41198/100629 [32:32<45:41, 21.68it/s]

 41%|████      | 41203/100629 [32:32<40:49, 24.26it/s]

 41%|████      | 41206/100629 [32:32<43:06, 22.98it/s]

 41%|████      | 41209/100629 [32:32<46:02, 21.51it/s]

 41%|████      | 41212/100629 [32:32<51:30, 19.23it/s]

 41%|████      | 41215/100629 [32:33<47:35, 20.81it/s]

 41%|████      | 41219/100629 [32:33<46:52, 21.13it/s]

 41%|████      | 41222/100629 [32:33<1:00:47, 16.29it/s]

 41%|████      | 41224/100629 [32:33<1:03:22, 15.62it/s]

 41%|████      | 41227/100629 [32:33<55:58, 17.69it/s]

 41%|████      | 41229/100629 [32:33<58:17, 16.98it/s]

 41%|████      | 41231/100629 [32:34<56:16, 17.59it/s]

 41%|████      | 41233/100629 [32:34<56:23, 17.55it/s]

 41%|████      | 41237/100629 [32:34<49:24, 20.03it/s]

 41%|████      | 41241/100629 [32:34<44:55, 22.03it/s]

 41%|████      | 41244/100629 [32:34<48:36, 20.36it/s]

 41%|████      | 41247/100629 [32:34<51:48, 19.10it/s]

 41%|████      | 41249/100629 [32:35<59:50, 16.54it/s]

 41%|████      | 41252/100629 [32:35<54:10, 18.27it/s]

 41%|████      | 41254/100629 [32:35<1:14:35, 13.27it/s]

 41%|████      | 41257/100629 [32:35<1:03:04, 15.69it/s]

 41%|████      | 41260/100629 [32:35<54:57, 18.00it/s]

 41%|████      | 41263/100629 [32:35<1:04:15, 15.40it/s]

 41%|████      | 41267/100629 [32:36<56:18, 17.57it/s]

 41%|████      | 41269/100629 [32:36<59:17, 16.69it/s]

 41%|████      | 41271/100629 [32:36<58:13, 16.99it/s]

 41%|████      | 41273/100629 [32:36<1:02:28, 15.84it/s]

 41%|████      | 41276/100629 [32:36<54:41, 18.09it/s]

 41%|████      | 41279/100629 [32:36<53:20, 18.54it/s]

 41%|████      | 41282/100629 [32:36<52:24, 18.87it/s]

 41%|████      | 41284/100629 [32:37<53:27, 18.50it/s]

 41%|████      | 41289/100629 [32:37<44:21, 22.29it/s]

 41%|████      | 41292/100629 [32:37<46:35, 21.22it/s]

 41%|████      | 41295/100629 [32:37<46:19, 21.35it/s]

 41%|████      | 41298/100629 [32:37<43:56, 22.50it/s]

 41%|████      | 41302/100629 [32:37<40:32, 24.39it/s]

 41%|████      | 41305/100629 [32:38<53:45, 18.39it/s]

 41%|████      | 41309/100629 [32:38<45:52, 21.55it/s]

 41%|████      | 41313/100629 [32:38<44:46, 22.08it/s]

 41%|████      | 41316/100629 [32:38<53:35, 18.45it/s]

 41%|████      | 41320/100629 [32:38<52:10, 18.94it/s]

 41%|████      | 41323/100629 [32:38<47:55, 20.62it/s]

 41%|████      | 41326/100629 [32:39<51:01, 19.37it/s]

 41%|████      | 41329/100629 [32:39<47:27, 20.83it/s]

 41%|████      | 41332/100629 [32:39<48:13, 20.50it/s]

 41%|████      | 41335/100629 [32:39<44:53, 22.02it/s]

 41%|████      | 41339/100629 [32:39<38:08, 25.91it/s]

 41%|████      | 41342/100629 [32:39<37:58, 26.01it/s]

 41%|████      | 41346/100629 [32:39<33:29, 29.50it/s]

 41%|████      | 41351/100629 [32:39<29:12, 33.82it/s]

 41%|████      | 41355/100629 [32:40<31:51, 31.01it/s]

 41%|████      | 41359/100629 [32:40<31:41, 31.16it/s]

 41%|████      | 41363/100629 [32:40<32:39, 30.25it/s]

 41%|████      | 41367/100629 [32:40<30:48, 32.06it/s]

 41%|████      | 41371/100629 [32:40<29:10, 33.85it/s]

 41%|████      | 41375/100629 [32:40<40:06, 24.63it/s]

 41%|████      | 41378/100629 [32:40<40:51, 24.17it/s]

 41%|████      | 41381/100629 [32:41<54:53, 17.99it/s]

 41%|████      | 41387/100629 [32:41<40:12, 24.55it/s]

 41%|████      | 41392/100629 [32:41<34:42, 28.44it/s]

 41%|████      | 41396/100629 [32:41<37:49, 26.10it/s]

 41%|████      | 41399/100629 [32:41<42:50, 23.04it/s]

 41%|████      | 41402/100629 [32:42<47:41, 20.70it/s]

 41%|████      | 41406/100629 [32:42<43:48, 22.53it/s]

 41%|████      | 41409/100629 [32:42<43:20, 22.77it/s]

 41%|████      | 41412/100629 [32:42<43:15, 22.82it/s]

 41%|████      | 41415/100629 [32:42<46:55, 21.03it/s]

 41%|████      | 41418/100629 [32:42<46:56, 21.02it/s]

 41%|████      | 41421/100629 [32:42<59:58, 16.45it/s]

 41%|████      | 41424/100629 [32:43<56:26, 17.48it/s]

 41%|████      | 41428/100629 [32:43<45:54, 21.49it/s]

 41%|████      | 41431/100629 [32:43<45:37, 21.63it/s]

 41%|████      | 41434/100629 [32:43<48:38, 20.29it/s]

 41%|████      | 41437/100629 [32:43<46:51, 21.05it/s]

 41%|████      | 41440/100629 [32:43<42:49, 23.03it/s]

 41%|████      | 41443/100629 [32:43<42:34, 23.17it/s]

 41%|████      | 41447/100629 [32:44<37:53, 26.03it/s]

 41%|████      | 41450/100629 [32:44<42:29, 23.21it/s]

 41%|████      | 41453/100629 [32:44<45:12, 21.81it/s]

 41%|████      | 41456/100629 [32:44<50:22, 19.58it/s]

 41%|████      | 41460/100629 [32:44<41:19, 23.86it/s]

 41%|████      | 41463/100629 [32:44<41:51, 23.56it/s]

 41%|████      | 41466/100629 [32:44<40:08, 24.56it/s]

 41%|████      | 41470/100629 [32:45<38:13, 25.79it/s]

 41%|████      | 41473/100629 [32:45<42:02, 23.45it/s]

 41%|████      | 41477/100629 [32:45<37:28, 26.31it/s]

 41%|████      | 41480/100629 [32:45<40:09, 24.55it/s]

 41%|████      | 41483/100629 [32:45<41:50, 23.56it/s]

 41%|████      | 41486/100629 [32:45<43:21, 22.73it/s]

 41%|████      | 41489/100629 [32:45<43:59, 22.41it/s]

 41%|████      | 41492/100629 [32:46<43:39, 22.58it/s]

 41%|████      | 41496/100629 [32:46<39:22, 25.03it/s]

 41%|████      | 41500/100629 [32:46<34:45, 28.35it/s]

 41%|████      | 41504/100629 [32:46<31:37, 31.15it/s]

 41%|████      | 41508/100629 [32:46<36:56, 26.67it/s]

 41%|████▏     | 41511/100629 [32:46<37:48, 26.06it/s]

 41%|████▏     | 41514/100629 [32:46<38:49, 25.38it/s]

 41%|████▏     | 41518/100629 [32:46<35:29, 27.75it/s]

 41%|████▏     | 41521/100629 [32:47<46:03, 21.39it/s]

 41%|████▏     | 41524/100629 [32:47<51:08, 19.26it/s]

 41%|████▏     | 41527/100629 [32:47<49:34, 19.87it/s]

 41%|████▏     | 41530/100629 [32:47<50:41, 19.43it/s]

 41%|████▏     | 41533/100629 [32:47<46:09, 21.34it/s]

 41%|████▏     | 41537/100629 [32:47<38:34, 25.53it/s]

 41%|████▏     | 41540/100629 [32:47<38:35, 25.52it/s]

 41%|████▏     | 41543/100629 [32:48<43:47, 22.49it/s]

 41%|████▏     | 41547/100629 [32:48<38:31, 25.56it/s]

 41%|████▏     | 41550/100629 [32:48<42:36, 23.11it/s]

 41%|████▏     | 41554/100629 [32:48<36:56, 26.65it/s]

 41%|████▏     | 41557/100629 [32:48<47:20, 20.79it/s]

 41%|████▏     | 41560/100629 [32:48<56:41, 17.37it/s]

 41%|████▏     | 41563/100629 [32:49<57:31, 17.11it/s]

 41%|████▏     | 41565/100629 [32:49<58:45, 16.75it/s]

 41%|████▏     | 41567/100629 [32:49<57:19, 17.17it/s]

 41%|████▏     | 41570/100629 [32:49<52:39, 18.70it/s]

 41%|████▏     | 41572/100629 [32:49<52:34, 18.72it/s]

 41%|████▏     | 41575/100629 [32:49<46:17, 21.26it/s]

 41%|████▏     | 41578/100629 [32:49<44:38, 22.05it/s]

 41%|████▏     | 41581/100629 [32:50<46:02, 21.38it/s]

 41%|████▏     | 41584/100629 [32:50<42:04, 23.39it/s]

 41%|████▏     | 41589/100629 [32:50<33:26, 29.42it/s]

 41%|████▏     | 41593/100629 [32:50<37:35, 26.18it/s]

 41%|████▏     | 41596/100629 [32:50<45:54, 21.44it/s]

 41%|████▏     | 41599/100629 [32:50<47:04, 20.90it/s]

 41%|████▏     | 41603/100629 [32:50<44:02, 22.34it/s]

 41%|████▏     | 41606/100629 [32:51<44:38, 22.04it/s]

 41%|████▏     | 41609/100629 [32:51<42:22, 23.21it/s]

 41%|████▏     | 41612/100629 [32:51<41:33, 23.66it/s]

 41%|████▏     | 41615/100629 [32:51<46:02, 21.36it/s]

 41%|████▏     | 41618/100629 [32:51<54:28, 18.06it/s]

 41%|████▏     | 41620/100629 [32:51<58:10, 16.90it/s]

 41%|████▏     | 41622/100629 [32:52<1:14:58, 13.12it/s]

 41%|████▏     | 41626/100629 [32:52<56:34, 17.38it/s]

 41%|████▏     | 41629/100629 [32:52<51:01, 19.27it/s]

 41%|████▏     | 41632/100629 [32:52<51:55, 18.93it/s]

 41%|████▏     | 41636/100629 [32:52<47:34, 20.67it/s]

 41%|████▏     | 41639/100629 [32:52<58:24, 16.83it/s]

 41%|████▏     | 41642/100629 [32:53<54:41, 17.97it/s]

 41%|████▏     | 41645/100629 [32:53<50:00, 19.65it/s]

 41%|████▏     | 41648/100629 [32:53<51:12, 19.19it/s]

 41%|████▏     | 41651/100629 [32:53<52:50, 18.60it/s]

 41%|████▏     | 41655/100629 [32:53<45:45, 21.48it/s]

 41%|████▏     | 41659/100629 [32:53<42:58, 22.87it/s]

 41%|████▏     | 41662/100629 [32:54<46:17, 21.23it/s]

 41%|████▏     | 41665/100629 [32:54<53:10, 18.48it/s]

 41%|████▏     | 41669/100629 [32:54<43:23, 22.65it/s]

 41%|████▏     | 41672/100629 [32:54<44:33, 22.05it/s]

 41%|████▏     | 41675/100629 [32:54<46:48, 20.99it/s]

 41%|████▏     | 41679/100629 [32:54<40:22, 24.34it/s]

 41%|████▏     | 41683/100629 [32:54<38:04, 25.80it/s]

 41%|████▏     | 41687/100629 [32:55<38:05, 25.79it/s]

 41%|████▏     | 41690/100629 [32:55<48:28, 20.26it/s]

 41%|████▏     | 41693/100629 [32:55<55:36, 17.66it/s]

 41%|████▏     | 41696/100629 [32:55<58:13, 16.87it/s]

 41%|████▏     | 41698/100629 [32:55<58:46, 16.71it/s]

 41%|████▏     | 41701/100629 [32:55<53:11, 18.46it/s]

 41%|████▏     | 41703/100629 [32:56<54:56, 17.88it/s]

 41%|████▏     | 41705/100629 [32:56<59:00, 16.64it/s]

 41%|████▏     | 41708/100629 [32:56<50:44, 19.35it/s]

 41%|████▏     | 41712/100629 [32:56<44:15, 22.18it/s]

 41%|████▏     | 41717/100629 [32:56<34:32, 28.43it/s]

 41%|████▏     | 41721/100629 [32:56<34:18, 28.61it/s]

 41%|████▏     | 41724/100629 [32:56<36:40, 26.77it/s]

 41%|████▏     | 41727/100629 [32:56<36:37, 26.81it/s]

 41%|████▏     | 41730/100629 [32:57<46:33, 21.09it/s]

 41%|████▏     | 41733/100629 [32:57<49:36, 19.79it/s]

 41%|████▏     | 41736/100629 [32:57<48:56, 20.06it/s]

 41%|████▏     | 41739/100629 [32:57<46:42, 21.01it/s]

 41%|████▏     | 41742/100629 [32:57<51:30, 19.05it/s]

 41%|████▏     | 41745/100629 [32:58<1:01:16, 16.02it/s]

 41%|████▏     | 41749/100629 [32:58<48:31, 20.22it/s]

 41%|████▏     | 41752/100629 [32:58<53:48, 18.23it/s]

 41%|████▏     | 41756/100629 [32:58<45:27, 21.59it/s]

 41%|████▏     | 41759/100629 [32:58<49:13, 19.93it/s]

 42%|████▏     | 41762/100629 [32:58<48:17, 20.32it/s]

 42%|████▏     | 41765/100629 [32:59<49:16, 19.91it/s]

 42%|████▏     | 41768/100629 [32:59<51:06, 19.20it/s]

 42%|████▏     | 41771/100629 [32:59<46:22, 21.15it/s]

 42%|████▏     | 41774/100629 [32:59<48:09, 20.37it/s]

 42%|████▏     | 41777/100629 [32:59<53:50, 18.22it/s]

 42%|████▏     | 41780/100629 [32:59<50:34, 19.39it/s]

 42%|████▏     | 41783/100629 [32:59<48:03, 20.41it/s]

 42%|████▏     | 41786/100629 [33:00<50:30, 19.42it/s]

 42%|████▏     | 41789/100629 [33:00<58:08, 16.87it/s]

 42%|████▏     | 41791/100629 [33:00<58:00, 16.90it/s]

 42%|████▏     | 41794/100629 [33:00<52:39, 18.62it/s]

 42%|████▏     | 41797/100629 [33:00<46:23, 21.14it/s]

 42%|████▏     | 41800/100629 [33:00<42:52, 22.87it/s]

 42%|████▏     | 41805/100629 [33:00<35:37, 27.52it/s]

 42%|████▏     | 41808/100629 [33:01<41:59, 23.35it/s]

 42%|████▏     | 41812/100629 [33:01<37:09, 26.38it/s]

 42%|████▏     | 41817/100629 [33:01<32:09, 30.48it/s]

 42%|████▏     | 41821/100629 [33:01<32:35, 30.07it/s]

 42%|████▏     | 41825/100629 [33:01<30:27, 32.18it/s]

 42%|████▏     | 41829/100629 [33:01<36:05, 27.15it/s]

 42%|████▏     | 41832/100629 [33:01<39:25, 24.86it/s]

 42%|████▏     | 41836/100629 [33:02<35:33, 27.56it/s]

 42%|████▏     | 41839/100629 [33:02<35:29, 27.61it/s]

 42%|████▏     | 41842/100629 [33:02<41:22, 23.68it/s]

 42%|████▏     | 41845/100629 [33:02<44:55, 21.81it/s]

 42%|████▏     | 41848/100629 [33:02<51:04, 19.18it/s]

 42%|████▏     | 41851/100629 [33:02<51:38, 18.97it/s]

 42%|████▏     | 41853/100629 [33:02<51:07, 19.16it/s]

 42%|████▏     | 41855/100629 [33:03<56:19, 17.39it/s]

 42%|████▏     | 41858/100629 [33:03<51:20, 19.08it/s]

 42%|████▏     | 41861/100629 [33:03<46:20, 21.14it/s]

 42%|████▏     | 41864/100629 [33:03<45:53, 21.34it/s]

 42%|████▏     | 41867/100629 [33:03<48:00, 20.40it/s]

 42%|████▏     | 41871/100629 [33:03<42:49, 22.87it/s]

 42%|████▏     | 41874/100629 [33:03<47:56, 20.42it/s]

 42%|████▏     | 41878/100629 [33:04<41:06, 23.82it/s]

 42%|████▏     | 41881/100629 [33:04<47:34, 20.58it/s]

 42%|████▏     | 41884/100629 [33:04<56:00, 17.48it/s]

 42%|████▏     | 41887/100629 [33:04<50:53, 19.24it/s]

 42%|████▏     | 41890/100629 [33:04<48:51, 20.04it/s]

 42%|████▏     | 41893/100629 [33:04<50:46, 19.28it/s]

 42%|████▏     | 41896/100629 [33:05<47:17, 20.70it/s]

 42%|████▏     | 41899/100629 [33:05<50:37, 19.34it/s]

 42%|████▏     | 41904/100629 [33:05<43:59, 22.25it/s]

 42%|████▏     | 41907/100629 [33:05<46:55, 20.86it/s]

 42%|████▏     | 41911/100629 [33:05<44:19, 22.08it/s]

 42%|████▏     | 41914/100629 [33:05<44:23, 22.05it/s]

 42%|████▏     | 41917/100629 [33:05<41:34, 23.54it/s]

 42%|████▏     | 41920/100629 [33:06<40:28, 24.17it/s]

 42%|████▏     | 41923/100629 [33:06<46:49, 20.90it/s]

 42%|████▏     | 41926/100629 [33:06<43:02, 22.73it/s]

 42%|████▏     | 41929/100629 [33:06<42:16, 23.14it/s]

 42%|████▏     | 41932/100629 [33:06<51:56, 18.84it/s]

 42%|████▏     | 41935/100629 [33:06<47:33, 20.57it/s]

 42%|████▏     | 41938/100629 [33:06<45:44, 21.39it/s]

 42%|████▏     | 41941/100629 [33:07<48:32, 20.15it/s]

 42%|████▏     | 41944/100629 [33:07<45:16, 21.61it/s]

 42%|████▏     | 41947/100629 [33:07<44:39, 21.90it/s]

 42%|████▏     | 41950/100629 [33:07<43:33, 22.45it/s]

 42%|████▏     | 41954/100629 [33:07<40:29, 24.15it/s]

 42%|████▏     | 41957/100629 [33:07<42:10, 23.19it/s]

 42%|████▏     | 41960/100629 [33:07<44:46, 21.84it/s]

 42%|████▏     | 41963/100629 [33:08<42:54, 22.79it/s]

 42%|████▏     | 41967/100629 [33:08<37:42, 25.92it/s]

 42%|████▏     | 41970/100629 [33:08<43:24, 22.53it/s]

 42%|████▏     | 41973/100629 [33:08<42:01, 23.26it/s]

 42%|████▏     | 41977/100629 [33:08<37:50, 25.83it/s]

 42%|████▏     | 41980/100629 [33:08<38:15, 25.55it/s]

 42%|████▏     | 41983/100629 [33:08<42:23, 23.06it/s]

 42%|████▏     | 41987/100629 [33:09<38:34, 25.34it/s]

 42%|████▏     | 41990/100629 [33:09<41:55, 23.31it/s]

 42%|████▏     | 41993/100629 [33:09<43:20, 22.55it/s]

 42%|████▏     | 41996/100629 [33:09<41:55, 23.31it/s]

 42%|████▏     | 41999/100629 [33:09<46:53, 20.84it/s]

 42%|████▏     | 42002/100629 [33:09<49:54, 19.58it/s]

 42%|████▏     | 42007/100629 [33:09<39:57, 24.45it/s]

 42%|████▏     | 42010/100629 [33:10<48:54, 19.98it/s]

 42%|████▏     | 42014/100629 [33:10<43:23, 22.51it/s]

 42%|████▏     | 42017/100629 [33:10<48:59, 19.94it/s]

 42%|████▏     | 42020/100629 [33:10<50:11, 19.46it/s]

 42%|████▏     | 42023/100629 [33:10<47:00, 20.78it/s]

 42%|████▏     | 42026/100629 [33:11<55:10, 17.70it/s]

 42%|████▏     | 42029/100629 [33:11<51:54, 18.82it/s]

 42%|████▏     | 42032/100629 [33:11<58:08, 16.80it/s]

 42%|████▏     | 42034/100629 [33:11<56:31, 17.28it/s]

 42%|████▏     | 42037/100629 [33:11<53:04, 18.40it/s]

 42%|████▏     | 42040/100629 [33:11<47:12, 20.69it/s]

 42%|████▏     | 42043/100629 [33:11<48:00, 20.34it/s]

 42%|████▏     | 42046/100629 [33:11<46:25, 21.03it/s]

 42%|████▏     | 42049/100629 [33:12<43:41, 22.35it/s]

 42%|████▏     | 42052/100629 [33:12<44:44, 21.82it/s]

 42%|████▏     | 42056/100629 [33:12<38:31, 25.34it/s]

 42%|████▏     | 42059/100629 [33:12<38:40, 25.24it/s]

 42%|████▏     | 42062/100629 [33:12<39:55, 24.45it/s]

 42%|████▏     | 42065/100629 [33:12<41:14, 23.67it/s]

 42%|████▏     | 42069/100629 [33:12<36:21, 26.84it/s]

 42%|████▏     | 42072/100629 [33:13<54:10, 18.02it/s]

 42%|████▏     | 42075/100629 [33:13<49:14, 19.82it/s]

 42%|████▏     | 42078/100629 [33:13<51:50, 18.83it/s]

 42%|████▏     | 42081/100629 [33:13<51:45, 18.85it/s]

 42%|████▏     | 42084/100629 [33:13<56:56, 17.14it/s]

 42%|████▏     | 42086/100629 [33:13<58:53, 16.57it/s]

 42%|████▏     | 42090/100629 [33:14<48:47, 20.00it/s]

 42%|████▏     | 42093/100629 [33:14<45:42, 21.35it/s]

 42%|████▏     | 42096/100629 [33:14<45:43, 21.34it/s]

 42%|████▏     | 42100/100629 [33:14<44:26, 21.95it/s]

 42%|████▏     | 42103/100629 [33:14<43:41, 22.32it/s]

 42%|████▏     | 42106/100629 [33:14<46:00, 21.20it/s]

 42%|████▏     | 42109/100629 [33:14<47:09, 20.68it/s]

 42%|████▏     | 42114/100629 [33:15<38:45, 25.16it/s]

 42%|████▏     | 42118/100629 [33:15<35:59, 27.09it/s]

 42%|████▏     | 42121/100629 [33:15<50:28, 19.32it/s]

 42%|████▏     | 42127/100629 [33:15<38:12, 25.51it/s]

 42%|████▏     | 42130/100629 [33:15<40:16, 24.21it/s]

 42%|████▏     | 42135/100629 [33:15<34:15, 28.46it/s]

 42%|████▏     | 42139/100629 [33:16<42:48, 22.77it/s]

 42%|████▏     | 42142/100629 [33:16<40:30, 24.06it/s]

 42%|████▏     | 42145/100629 [33:16<45:37, 21.36it/s]

 42%|████▏     | 42150/100629 [33:16<40:54, 23.83it/s]

 42%|████▏     | 42153/100629 [33:16<44:12, 22.05it/s]

 42%|████▏     | 42156/100629 [33:16<46:24, 21.00it/s]

 42%|████▏     | 42159/100629 [33:17<47:42, 20.43it/s]

 42%|████▏     | 42162/100629 [33:17<49:37, 19.64it/s]

 42%|████▏     | 42165/100629 [33:17<52:05, 18.70it/s]

 42%|████▏     | 42167/100629 [33:17<54:42, 17.81it/s]

 42%|████▏     | 42170/100629 [33:17<55:50, 17.45it/s]

 42%|████▏     | 42173/100629 [33:17<51:52, 18.78it/s]

 42%|████▏     | 42176/100629 [33:18<54:47, 17.78it/s]

 42%|████▏     | 42179/100629 [33:18<56:23, 17.28it/s]

 42%|████▏     | 42181/100629 [33:18<1:03:50, 15.26it/s]

 42%|████▏     | 42184/100629 [33:18<57:07, 17.05it/s]

 42%|████▏     | 42186/100629 [33:18<1:07:55, 14.34it/s]

 42%|████▏     | 42189/100629 [33:18<58:33, 16.63it/s]

 42%|████▏     | 42191/100629 [33:19<56:49, 17.14it/s]

 42%|████▏     | 42194/100629 [33:19<50:23, 19.33it/s]

 42%|████▏     | 42197/100629 [33:19<44:56, 21.67it/s]

 42%|████▏     | 42201/100629 [33:19<37:21, 26.07it/s]

 42%|████▏     | 42204/100629 [33:19<40:08, 24.26it/s]

 42%|████▏     | 42207/100629 [33:19<50:23, 19.32it/s]

 42%|████▏     | 42210/100629 [33:19<57:14, 17.01it/s]

 42%|████▏     | 42212/100629 [33:20<55:41, 17.48it/s]

 42%|████▏     | 42215/100629 [33:20<50:34, 19.25it/s]

 42%|████▏     | 42218/100629 [33:20<52:15, 18.63it/s]

 42%|████▏     | 42220/100629 [33:20<55:17, 17.61it/s]

 42%|████▏     | 42223/100629 [33:20<47:47, 20.37it/s]

 42%|████▏     | 42226/100629 [33:20<43:19, 22.47it/s]

 42%|████▏     | 42229/100629 [33:20<42:53, 22.70it/s]

 42%|████▏     | 42232/100629 [33:21<52:32, 18.53it/s]

 42%|████▏     | 42235/100629 [33:21<50:50, 19.14it/s]

 42%|████▏     | 42238/100629 [33:21<55:01, 17.69it/s]

 42%|████▏     | 42240/100629 [33:21<1:05:03, 14.96it/s]

 42%|████▏     | 42242/100629 [33:21<1:03:04, 15.43it/s]

 42%|████▏     | 42246/100629 [33:21<47:57, 20.29it/s]

 42%|████▏     | 42249/100629 [33:22<50:32, 19.25it/s]

 42%|████▏     | 42252/100629 [33:22<54:28, 17.86it/s]

 42%|████▏     | 42254/100629 [33:22<55:44, 17.45it/s]

 42%|████▏     | 42256/100629 [33:22<55:24, 17.56it/s]

 42%|████▏     | 42258/100629 [33:22<1:08:58, 14.11it/s]

 42%|████▏     | 42260/100629 [33:22<1:04:50, 15.00it/s]

 42%|████▏     | 42265/100629 [33:22<49:10, 19.78it/s]

 42%|████▏     | 42269/100629 [33:23<40:18, 24.13it/s]

 42%|████▏     | 42272/100629 [33:23<39:20, 24.72it/s]

 42%|████▏     | 42275/100629 [33:23<45:19, 21.45it/s]

 42%|████▏     | 42280/100629 [33:23<38:27, 25.28it/s]

 42%|████▏     | 42285/100629 [33:23<32:15, 30.14it/s]

 42%|████▏     | 42289/100629 [33:23<33:37, 28.91it/s]

 42%|████▏     | 42293/100629 [33:23<37:05, 26.21it/s]

 42%|████▏     | 42296/100629 [33:24<38:36, 25.18it/s]

 42%|████▏     | 42299/100629 [33:24<40:30, 24.00it/s]

 42%|████▏     | 42302/100629 [33:24<39:35, 24.55it/s]

 42%|████▏     | 42305/100629 [33:24<45:07, 21.55it/s]

 42%|████▏     | 42308/100629 [33:24<46:10, 21.05it/s]

 42%|████▏     | 42311/100629 [33:24<45:16, 21.47it/s]

 42%|████▏     | 42314/100629 [33:25<51:18, 18.94it/s]

 42%|████▏     | 42317/100629 [33:25<46:21, 20.96it/s]

 42%|████▏     | 42321/100629 [33:25<42:02, 23.11it/s]

 42%|████▏     | 42325/100629 [33:25<37:57, 25.60it/s]

 42%|████▏     | 42328/100629 [33:25<41:48, 23.24it/s]

 42%|████▏     | 42331/100629 [33:25<40:35, 23.93it/s]

 42%|████▏     | 42335/100629 [33:25<38:10, 25.45it/s]

 42%|████▏     | 42338/100629 [33:25<41:37, 23.34it/s]

 42%|████▏     | 42341/100629 [33:26<44:08, 22.01it/s]

 42%|████▏     | 42344/100629 [33:26<44:16, 21.94it/s]

 42%|████▏     | 42347/100629 [33:26<43:08, 22.51it/s]

 42%|████▏     | 42350/100629 [33:26<42:50, 22.67it/s]

 42%|████▏     | 42353/100629 [33:26<45:38, 21.28it/s]

 42%|████▏     | 42356/100629 [33:26<45:53, 21.16it/s]

 42%|████▏     | 42359/100629 [33:27<53:20, 18.21it/s]

 42%|████▏     | 42361/100629 [33:27<53:11, 18.26it/s]

 42%|████▏     | 42365/100629 [33:27<43:55, 22.10it/s]

 42%|████▏     | 42368/100629 [33:27<40:41, 23.86it/s]

 42%|████▏     | 42371/100629 [33:27<43:47, 22.17it/s]

 42%|████▏     | 42374/100629 [33:27<40:52, 23.75it/s]

 42%|████▏     | 42377/100629 [33:27<44:26, 21.85it/s]

 42%|████▏     | 42380/100629 [33:27<48:51, 19.87it/s]

 42%|████▏     | 42383/100629 [33:28<1:00:25, 16.07it/s]

 42%|████▏     | 42386/100629 [33:28<52:20, 18.54it/s]

 42%|████▏     | 42389/100629 [33:28<48:43, 19.92it/s]

 42%|████▏     | 42392/100629 [33:28<48:18, 20.09it/s]

 42%|████▏     | 42395/100629 [33:28<55:23, 17.52it/s]

 42%|████▏     | 42398/100629 [33:28<51:09, 18.97it/s]

 42%|████▏     | 42402/100629 [33:29<41:29, 23.39it/s]

 42%|████▏     | 42405/100629 [33:29<44:52, 21.62it/s]

 42%|████▏     | 42408/100629 [33:29<49:17, 19.68it/s]

 42%|████▏     | 42411/100629 [33:29<53:37, 18.09it/s]

 42%|████▏     | 42414/100629 [33:29<51:07, 18.98it/s]

 42%|████▏     | 42419/100629 [33:29<39:55, 24.30it/s]

 42%|████▏     | 42423/100629 [33:30<39:49, 24.36it/s]

 42%|████▏     | 42426/100629 [33:30<43:14, 22.43it/s]

 42%|████▏     | 42430/100629 [33:30<37:09, 26.11it/s]

 42%|████▏     | 42433/100629 [33:30<50:51, 19.07it/s]

 42%|████▏     | 42436/100629 [33:30<47:18, 20.50it/s]

 42%|████▏     | 42439/100629 [33:30<55:37, 17.44it/s]

 42%|████▏     | 42442/100629 [33:31<52:26, 18.49it/s]

 42%|████▏     | 42445/100629 [33:31<48:54, 19.83it/s]

 42%|████▏     | 42448/100629 [33:31<46:37, 20.79it/s]

 42%|████▏     | 42451/100629 [33:31<47:29, 20.41it/s]

 42%|████▏     | 42454/100629 [33:31<45:29, 21.31it/s]

 42%|████▏     | 42457/100629 [33:31<50:10, 19.32it/s]

 42%|████▏     | 42460/100629 [33:31<51:16, 18.91it/s]

 42%|████▏     | 42462/100629 [33:32<53:35, 18.09it/s]

 42%|████▏     | 42464/100629 [33:32<55:54, 17.34it/s]

 42%|████▏     | 42467/100629 [33:32<52:04, 18.62it/s]

 42%|████▏     | 42471/100629 [33:32<44:06, 21.97it/s]

 42%|████▏     | 42474/100629 [33:32<41:48, 23.18it/s]

 42%|████▏     | 42477/100629 [33:32<41:10, 23.54it/s]

 42%|████▏     | 42480/100629 [33:32<45:13, 21.43it/s]

 42%|████▏     | 42483/100629 [33:33<45:31, 21.29it/s]

 42%|████▏     | 42486/100629 [33:33<42:15, 22.93it/s]

 42%|████▏     | 42489/100629 [33:33<45:17, 21.39it/s]

 42%|████▏     | 42492/100629 [33:33<42:57, 22.55it/s]

 42%|████▏     | 42495/100629 [33:33<45:07, 21.47it/s]

 42%|████▏     | 42500/100629 [33:33<38:43, 25.02it/s]

 42%|████▏     | 42503/100629 [33:33<43:13, 22.41it/s]

 42%|████▏     | 42506/100629 [33:34<43:08, 22.46it/s]

 42%|████▏     | 42509/100629 [33:34<44:25, 21.80it/s]

 42%|████▏     | 42512/100629 [33:34<47:58, 20.19it/s]

 42%|████▏     | 42515/100629 [33:34<44:40, 21.68it/s]

 42%|████▏     | 42518/100629 [33:34<42:04, 23.01it/s]

 42%|████▏     | 42521/100629 [33:34<44:34, 21.73it/s]

 42%|████▏     | 42524/100629 [33:34<46:33, 20.80it/s]

 42%|████▏     | 42527/100629 [33:35<45:03, 21.49it/s]

 42%|████▏     | 42530/100629 [33:35<50:49, 19.05it/s]

 42%|████▏     | 42532/100629 [33:35<58:55, 16.43it/s]

 42%|████▏     | 42536/100629 [33:35<48:58, 19.77it/s]

 42%|████▏     | 42540/100629 [33:35<41:29, 23.34it/s]

 42%|████▏     | 42543/100629 [33:35<46:17, 20.91it/s]

 42%|████▏     | 42546/100629 [33:35<42:53, 22.57it/s]

 42%|████▏     | 42549/100629 [33:36<45:45, 21.15it/s]

 42%|████▏     | 42552/100629 [33:36<46:02, 21.02it/s]

 42%|████▏     | 42555/100629 [33:36<50:02, 19.34it/s]

 42%|████▏     | 42559/100629 [33:36<42:10, 22.95it/s]

 42%|████▏     | 42562/100629 [33:36<47:53, 20.20it/s]

 42%|████▏     | 42565/100629 [33:36<46:29, 20.82it/s]

 42%|████▏     | 42569/100629 [33:37<40:18, 24.00it/s]

 42%|████▏     | 42572/100629 [33:37<38:37, 25.05it/s]

 42%|████▏     | 42575/100629 [33:37<38:23, 25.20it/s]

 42%|████▏     | 42578/100629 [33:37<51:08, 18.92it/s]

 42%|████▏     | 42582/100629 [33:37<45:45, 21.15it/s]

 42%|████▏     | 42585/100629 [33:37<45:19, 21.35it/s]

 42%|████▏     | 42588/100629 [33:38<52:57, 18.26it/s]

 42%|████▏     | 42591/100629 [33:38<49:13, 19.65it/s]

 42%|████▏     | 42594/100629 [33:38<52:34, 18.40it/s]

 42%|████▏     | 42596/100629 [33:38<55:40, 17.37it/s]

 42%|████▏     | 42599/100629 [33:38<52:52, 18.29it/s]

 42%|████▏     | 42602/100629 [33:38<55:00, 17.58it/s]

 42%|████▏     | 42605/100629 [33:39<59:03, 16.38it/s]

 42%|████▏     | 42607/100629 [33:39<59:17, 16.31it/s]

 42%|████▏     | 42609/100629 [33:39<1:01:57, 15.61it/s]

 42%|████▏     | 42612/100629 [33:39<51:47, 18.67it/s]

 42%|████▏     | 42614/100629 [33:39<56:51, 17.00it/s]

 42%|████▏     | 42616/100629 [33:39<55:05, 17.55it/s]

 42%|████▏     | 42618/100629 [33:39<56:05, 17.23it/s]

 42%|████▏     | 42620/100629 [33:39<1:00:31, 15.97it/s]

 42%|████▏     | 42624/100629 [33:40<55:24, 17.45it/s]

 42%|████▏     | 42628/100629 [33:40<47:16, 20.45it/s]

 42%|████▏     | 42631/100629 [33:40<43:18, 22.32it/s]

 42%|████▏     | 42634/100629 [33:40<43:40, 22.13it/s]

 42%|████▏     | 42638/100629 [33:40<36:49, 26.25it/s]

 42%|████▏     | 42642/100629 [33:40<36:03, 26.81it/s]

 42%|████▏     | 42645/100629 [33:40<42:05, 22.96it/s]

 42%|████▏     | 42648/100629 [33:41<41:47, 23.12it/s]

 42%|████▏     | 42652/100629 [33:41<36:18, 26.61it/s]

 42%|████▏     | 42655/100629 [33:41<37:44, 25.60it/s]

 42%|████▏     | 42659/100629 [33:41<34:55, 27.67it/s]

 42%|████▏     | 42662/100629 [33:41<38:19, 25.21it/s]

 42%|████▏     | 42665/100629 [33:41<38:01, 25.41it/s]

 42%|████▏     | 42668/100629 [33:41<44:55, 21.51it/s]

 42%|████▏     | 42671/100629 [33:41<43:45, 22.07it/s]

 42%|████▏     | 42674/100629 [33:42<50:21, 19.18it/s]

 42%|████▏     | 42677/100629 [33:42<47:20, 20.40it/s]

 42%|████▏     | 42680/100629 [33:42<47:53, 20.17it/s]

 42%|████▏     | 42683/100629 [33:42<51:20, 18.81it/s]

 42%|████▏     | 42687/100629 [33:42<44:45, 21.57it/s]

 42%|████▏     | 42690/100629 [33:42<43:23, 22.25it/s]

 42%|████▏     | 42693/100629 [33:43<45:31, 21.21it/s]

 42%|████▏     | 42696/100629 [33:43<43:12, 22.35it/s]

 42%|████▏     | 42699/100629 [33:43<40:22, 23.91it/s]

 42%|████▏     | 42703/100629 [33:43<40:19, 23.94it/s]

 42%|████▏     | 42706/100629 [33:43<39:17, 24.57it/s]

 42%|████▏     | 42709/100629 [33:43<46:36, 20.71it/s]

 42%|████▏     | 42712/100629 [33:43<45:12, 21.35it/s]

 42%|████▏     | 42715/100629 [33:44<47:08, 20.48it/s]

 42%|████▏     | 42719/100629 [33:44<40:51, 23.62it/s]

 42%|████▏     | 42722/100629 [33:44<39:02, 24.72it/s]

 42%|████▏     | 42725/100629 [33:44<47:36, 20.27it/s]

 42%|████▏     | 42728/100629 [33:44<47:41, 20.23it/s]

 42%|████▏     | 42731/100629 [33:44<46:42, 20.66it/s]

 42%|████▏     | 42735/100629 [33:44<40:09, 24.03it/s]

 42%|████▏     | 42738/100629 [33:45<41:19, 23.35it/s]

 42%|████▏     | 42741/100629 [33:45<42:45, 22.56it/s]

 42%|████▏     | 42744/100629 [33:45<41:29, 23.25it/s]

 42%|████▏     | 42747/100629 [33:45<45:38, 21.14it/s]

 42%|████▏     | 42750/100629 [33:45<49:41, 19.41it/s]

 42%|████▏     | 42753/100629 [33:45<50:48, 18.99it/s]

 42%|████▏     | 42756/100629 [33:45<50:09, 19.23it/s]

 42%|████▏     | 42758/100629 [33:46<49:51, 19.34it/s]

 42%|████▏     | 42760/100629 [33:46<51:03, 18.89it/s]

 42%|████▏     | 42763/100629 [33:46<50:04, 19.26it/s]

 42%|████▏     | 42766/100629 [33:46<49:32, 19.47it/s]

 43%|████▎     | 42769/100629 [33:46<47:13, 20.42it/s]

 43%|████▎     | 42772/100629 [33:46<49:44, 19.38it/s]

 43%|████▎     | 42776/100629 [33:46<42:40, 22.60it/s]

 43%|████▎     | 42779/100629 [33:47<43:47, 22.01it/s]

 43%|████▎     | 42782/100629 [33:47<50:38, 19.04it/s]

 43%|████▎     | 42784/100629 [33:47<53:55, 17.88it/s]

 43%|████▎     | 42787/100629 [33:47<49:39, 19.42it/s]

 43%|████▎     | 42790/100629 [33:47<55:45, 17.29it/s]

 43%|████▎     | 42792/100629 [33:47<58:22, 16.51it/s]

 43%|████▎     | 42796/100629 [33:48<47:05, 20.47it/s]

 43%|████▎     | 42799/100629 [33:48<49:32, 19.45it/s]

 43%|████▎     | 42802/100629 [33:48<49:16, 19.56it/s]

 43%|████▎     | 42805/100629 [33:48<48:32, 19.85it/s]

 43%|████▎     | 42808/100629 [33:48<51:10, 18.83it/s]

 43%|████▎     | 42810/100629 [33:48<57:23, 16.79it/s]

 43%|████▎     | 42812/100629 [33:48<57:10, 16.86it/s]

 43%|████▎     | 42814/100629 [33:49<57:05, 16.88it/s]

 43%|████▎     | 42817/100629 [33:49<54:16, 17.76it/s]

 43%|████▎     | 42819/100629 [33:49<55:38, 17.32it/s]

 43%|████▎     | 42821/100629 [33:49<53:46, 17.92it/s]

 43%|████▎     | 42823/100629 [33:49<59:40, 16.14it/s]

 43%|████▎     | 42828/100629 [33:49<45:52, 21.00it/s]

 43%|████▎     | 42831/100629 [33:49<52:22, 18.39it/s]

 43%|████▎     | 42833/100629 [33:50<55:44, 17.28it/s]

 43%|████▎     | 42837/100629 [33:50<45:29, 21.17it/s]

 43%|████▎     | 42842/100629 [33:50<39:34, 24.34it/s]

 43%|████▎     | 42845/100629 [33:50<50:33, 19.05it/s]

 43%|████▎     | 42848/100629 [33:50<47:18, 20.36it/s]

 43%|████▎     | 42851/100629 [33:50<50:17, 19.15it/s]

 43%|████▎     | 42854/100629 [33:51<48:37, 19.81it/s]

 43%|████▎     | 42857/100629 [33:51<52:59, 18.17it/s]

 43%|████▎     | 42859/100629 [33:51<57:37, 16.71it/s]

 43%|████▎     | 42861/100629 [33:51<1:00:45, 15.85it/s]

 43%|████▎     | 42863/100629 [33:51<58:33, 16.44it/s]

 43%|████▎     | 42866/100629 [33:51<50:06, 19.21it/s]

 43%|████▎     | 42869/100629 [33:51<50:30, 19.06it/s]

 43%|████▎     | 42873/100629 [33:52<51:27, 18.70it/s]

 43%|████▎     | 42876/100629 [33:52<50:44, 18.97it/s]

 43%|████▎     | 42879/100629 [33:52<50:16, 19.14it/s]

 43%|████▎     | 42882/100629 [33:52<49:18, 19.52it/s]

 43%|████▎     | 42888/100629 [33:52<35:56, 26.77it/s]

 43%|████▎     | 42891/100629 [33:52<36:57, 26.03it/s]

 43%|████▎     | 42894/100629 [33:53<36:39, 26.25it/s]

 43%|████▎     | 42898/100629 [33:53<33:22, 28.82it/s]

 43%|████▎     | 42901/100629 [33:53<38:16, 25.14it/s]

 43%|████▎     | 42904/100629 [33:53<41:05, 23.42it/s]

 43%|████▎     | 42907/100629 [33:53<41:26, 23.22it/s]

 43%|████▎     | 42910/100629 [33:53<52:40, 18.26it/s]

 43%|████▎     | 42913/100629 [33:53<52:24, 18.36it/s]

 43%|████▎     | 42918/100629 [33:54<44:08, 21.79it/s]

 43%|████▎     | 42921/100629 [33:54<44:28, 21.62it/s]

 43%|████▎     | 42924/100629 [33:54<43:30, 22.11it/s]

 43%|████▎     | 42928/100629 [33:54<40:42, 23.63it/s]

 43%|████▎     | 42931/100629 [33:54<40:40, 23.64it/s]

 43%|████▎     | 42934/100629 [33:54<43:39, 22.02it/s]

 43%|████▎     | 42937/100629 [33:55<44:25, 21.64it/s]

 43%|████▎     | 42940/100629 [33:55<44:42, 21.50it/s]

 43%|████▎     | 42943/100629 [33:55<42:30, 22.62it/s]

 43%|████▎     | 42946/100629 [33:55<42:46, 22.48it/s]

 43%|████▎     | 42950/100629 [33:55<39:20, 24.43it/s]

 43%|████▎     | 42953/100629 [33:55<40:15, 23.88it/s]

 43%|████▎     | 42958/100629 [33:55<35:14, 27.27it/s]

 43%|████▎     | 42961/100629 [33:55<36:27, 26.36it/s]

 43%|████▎     | 42965/100629 [33:56<33:31, 28.67it/s]

 43%|████▎     | 42968/100629 [33:56<33:28, 28.71it/s]

 43%|████▎     | 42971/100629 [33:56<35:17, 27.23it/s]

 43%|████▎     | 42974/100629 [33:56<41:03, 23.40it/s]

 43%|████▎     | 42977/100629 [33:56<39:36, 24.26it/s]

 43%|████▎     | 42980/100629 [33:56<38:02, 25.26it/s]

 43%|████▎     | 42983/100629 [33:56<45:05, 21.30it/s]

 43%|████▎     | 42987/100629 [33:56<37:40, 25.50it/s]

 43%|████▎     | 42991/100629 [33:57<39:04, 24.58it/s]

 43%|████▎     | 42994/100629 [33:57<39:39, 24.22it/s]

 43%|████▎     | 42997/100629 [33:57<47:09, 20.37it/s]

 43%|████▎     | 43000/100629 [33:57<50:39, 18.96it/s]

 43%|████▎     | 43003/100629 [33:57<49:54, 19.24it/s]

 43%|████▎     | 43006/100629 [33:57<46:28, 20.66it/s]

 43%|████▎     | 43009/100629 [33:58<47:22, 20.27it/s]

 43%|████▎     | 43012/100629 [33:58<45:04, 21.30it/s]

 43%|████▎     | 43016/100629 [33:58<42:26, 22.63it/s]

 43%|████▎     | 43019/100629 [33:58<43:23, 22.13it/s]

 43%|████▎     | 43022/100629 [33:58<48:50, 19.66it/s]

 43%|████▎     | 43025/100629 [33:58<50:19, 19.08it/s]

 43%|████▎     | 43028/100629 [33:59<48:49, 19.66it/s]

 43%|████▎     | 43032/100629 [33:59<41:13, 23.29it/s]

 43%|████▎     | 43035/100629 [33:59<49:04, 19.56it/s]

 43%|████▎     | 43038/100629 [33:59<48:16, 19.88it/s]

 43%|████▎     | 43041/100629 [33:59<52:04, 18.43it/s]

 43%|████▎     | 43043/100629 [33:59<54:02, 17.76it/s]

 43%|████▎     | 43046/100629 [33:59<47:19, 20.28it/s]

 43%|████▎     | 43049/100629 [34:00<54:25, 17.63it/s]

 43%|████▎     | 43051/100629 [34:00<56:43, 16.92it/s]

 43%|████▎     | 43054/100629 [34:00<51:40, 18.57it/s]

 43%|████▎     | 43057/100629 [34:00<50:21, 19.05it/s]

 43%|████▎     | 43059/100629 [34:00<52:19, 18.34it/s]

 43%|████▎     | 43062/100629 [34:00<52:22, 18.32it/s]

 43%|████▎     | 43066/100629 [34:00<43:21, 22.13it/s]

 43%|████▎     | 43070/100629 [34:01<45:37, 21.02it/s]

 43%|████▎     | 43073/100629 [34:01<43:12, 22.20it/s]

 43%|████▎     | 43076/100629 [34:01<47:59, 19.99it/s]

 43%|████▎     | 43080/100629 [34:01<40:07, 23.90it/s]

 43%|████▎     | 43083/100629 [34:01<38:41, 24.79it/s]

 43%|████▎     | 43086/100629 [34:01<37:07, 25.84it/s]

 43%|████▎     | 43089/100629 [34:02<56:20, 17.02it/s]

 43%|████▎     | 43092/100629 [34:02<49:58, 19.19it/s]

 43%|████▎     | 43095/100629 [34:02<45:43, 20.97it/s]

 43%|████▎     | 43098/100629 [34:02<47:07, 20.34it/s]

 43%|████▎     | 43101/100629 [34:02<49:59, 19.18it/s]

 43%|████▎     | 43104/100629 [34:02<46:20, 20.69it/s]

 43%|████▎     | 43109/100629 [34:03<44:45, 21.42it/s]

 43%|████▎     | 43112/100629 [34:03<51:12, 18.72it/s]

 43%|████▎     | 43115/100629 [34:03<49:09, 19.50it/s]

 43%|████▎     | 43118/100629 [34:03<49:43, 19.28it/s]

 43%|████▎     | 43121/100629 [34:03<53:46, 17.83it/s]

 43%|████▎     | 43125/100629 [34:03<45:34, 21.03it/s]

 43%|████▎     | 43128/100629 [34:04<45:59, 20.83it/s]

 43%|████▎     | 43131/100629 [34:04<55:41, 17.21it/s]

 43%|████▎     | 43135/100629 [34:04<49:02, 19.54it/s]

 43%|████▎     | 43138/100629 [34:04<49:30, 19.35it/s]

 43%|████▎     | 43141/100629 [34:04<48:51, 19.61it/s]

 43%|████▎     | 43144/100629 [34:04<51:32, 18.59it/s]

 43%|████▎     | 43146/100629 [34:05<53:04, 18.05it/s]

 43%|████▎     | 43150/100629 [34:05<45:07, 21.23it/s]

 43%|████▎     | 43153/100629 [34:05<42:37, 22.48it/s]

 43%|████▎     | 43157/100629 [34:05<37:42, 25.40it/s]

 43%|████▎     | 43162/100629 [34:05<32:00, 29.92it/s]

 43%|████▎     | 43166/100629 [34:05<38:21, 24.96it/s]

 43%|████▎     | 43171/100629 [34:05<37:14, 25.72it/s]

 43%|████▎     | 43174/100629 [34:06<37:23, 25.61it/s]

 43%|████▎     | 43177/100629 [34:06<37:28, 25.56it/s]

 43%|████▎     | 43180/100629 [34:06<38:00, 25.19it/s]

 43%|████▎     | 43184/100629 [34:06<35:39, 26.85it/s]

 43%|████▎     | 43187/100629 [34:06<41:11, 23.24it/s]

 43%|████▎     | 43190/100629 [34:06<39:16, 24.37it/s]

 43%|████▎     | 43193/100629 [34:06<39:50, 24.02it/s]

 43%|████▎     | 43196/100629 [34:06<37:36, 25.46it/s]

 43%|████▎     | 43199/100629 [34:07<40:57, 23.37it/s]

 43%|████▎     | 43202/100629 [34:07<48:12, 19.86it/s]

 43%|████▎     | 43206/100629 [34:07<41:06, 23.28it/s]

 43%|████▎     | 43209/100629 [34:07<41:13, 23.21it/s]

 43%|████▎     | 43212/100629 [34:07<41:03, 23.31it/s]

 43%|████▎     | 43215/100629 [34:07<41:38, 22.98it/s]

 43%|████▎     | 43218/100629 [34:07<39:29, 24.23it/s]

 43%|████▎     | 43221/100629 [34:08<37:54, 25.24it/s]

 43%|████▎     | 43224/100629 [34:08<46:20, 20.65it/s]

 43%|████▎     | 43229/100629 [34:08<39:05, 24.47it/s]

 43%|████▎     | 43234/100629 [34:08<33:49, 28.29it/s]

 43%|████▎     | 43237/100629 [34:08<34:38, 27.61it/s]

 43%|████▎     | 43240/100629 [34:08<33:57, 28.16it/s]

 43%|████▎     | 43243/100629 [34:08<46:36, 20.52it/s]

 43%|████▎     | 43246/100629 [34:09<54:21, 17.59it/s]

 43%|████▎     | 43249/100629 [34:09<59:00, 16.21it/s]

 43%|████▎     | 43252/100629 [34:09<54:56, 17.40it/s]

 43%|████▎     | 43254/100629 [34:09<59:32, 16.06it/s]

 43%|████▎     | 43259/100629 [34:09<43:59, 21.74it/s]

 43%|████▎     | 43262/100629 [34:09<41:57, 22.78it/s]

 43%|████▎     | 43266/100629 [34:10<39:49, 24.01it/s]

 43%|████▎     | 43269/100629 [34:10<43:55, 21.77it/s]

 43%|████▎     | 43272/100629 [34:10<46:20, 20.63it/s]

 43%|████▎     | 43275/100629 [34:10<53:49, 17.76it/s]

 43%|████▎     | 43278/100629 [34:10<52:28, 18.21it/s]

 43%|████▎     | 43280/100629 [34:10<51:35, 18.53it/s]

 43%|████▎     | 43282/100629 [34:11<54:14, 17.62it/s]

 43%|████▎     | 43285/100629 [34:11<47:46, 20.01it/s]

 43%|████▎     | 43289/100629 [34:11<41:46, 22.88it/s]

 43%|████▎     | 43292/100629 [34:11<45:31, 20.99it/s]

 43%|████▎     | 43296/100629 [34:11<37:57, 25.17it/s]

 43%|████▎     | 43299/100629 [34:11<43:55, 21.75it/s]

 43%|████▎     | 43302/100629 [34:11<41:18, 23.13it/s]

 43%|████▎     | 43305/100629 [34:12<45:09, 21.16it/s]

 43%|████▎     | 43309/100629 [34:12<39:18, 24.30it/s]

 43%|████▎     | 43312/100629 [34:12<37:16, 25.63it/s]

 43%|████▎     | 43316/100629 [34:12<34:13, 27.91it/s]

 43%|████▎     | 43319/100629 [34:12<38:44, 24.65it/s]

 43%|████▎     | 43323/100629 [34:12<36:29, 26.17it/s]

 43%|████▎     | 43326/100629 [34:12<44:41, 21.37it/s]

 43%|████▎     | 43330/100629 [34:13<40:54, 23.35it/s]

 43%|████▎     | 43333/100629 [34:13<40:37, 23.50it/s]

 43%|████▎     | 43337/100629 [34:13<38:01, 25.11it/s]

 43%|████▎     | 43340/100629 [34:13<39:16, 24.31it/s]

 43%|████▎     | 43343/100629 [34:13<42:30, 22.46it/s]

 43%|████▎     | 43346/100629 [34:13<41:16, 23.13it/s]

 43%|████▎     | 43349/100629 [34:13<38:51, 24.57it/s]

 43%|████▎     | 43352/100629 [34:13<40:45, 23.42it/s]

 43%|████▎     | 43355/100629 [34:14<39:52, 23.94it/s]

 43%|████▎     | 43358/100629 [34:14<43:11, 22.10it/s]

 43%|████▎     | 43362/100629 [34:14<39:14, 24.32it/s]

 43%|████▎     | 43365/100629 [34:14<46:18, 20.61it/s]

 43%|████▎     | 43368/100629 [34:14<47:47, 19.97it/s]

 43%|████▎     | 43371/100629 [34:14<43:48, 21.78it/s]

 43%|████▎     | 43375/100629 [34:14<37:55, 25.16it/s]

 43%|████▎     | 43378/100629 [34:15<40:23, 23.62it/s]

 43%|████▎     | 43381/100629 [34:15<46:25, 20.56it/s]

 43%|████▎     | 43385/100629 [34:15<39:39, 24.06it/s]

 43%|████▎     | 43388/100629 [34:15<41:11, 23.16it/s]

 43%|████▎     | 43391/100629 [34:15<40:34, 23.52it/s]

 43%|████▎     | 43394/100629 [34:15<46:44, 20.41it/s]

 43%|████▎     | 43397/100629 [34:16<47:38, 20.02it/s]

 43%|████▎     | 43401/100629 [34:16<40:07, 23.77it/s]

 43%|████▎     | 43404/100629 [34:16<38:30, 24.77it/s]

 43%|████▎     | 43407/100629 [34:16<38:32, 24.74it/s]

 43%|████▎     | 43410/100629 [34:16<40:45, 23.40it/s]

 43%|████▎     | 43413/100629 [34:16<49:06, 19.42it/s]

 43%|████▎     | 43416/100629 [34:17<1:01:35, 15.48it/s]

 43%|████▎     | 43420/100629 [34:17<1:01:15, 15.57it/s]

 43%|████▎     | 43423/100629 [34:17<54:32, 17.48it/s]

 43%|████▎     | 43426/100629 [34:17<49:11, 19.38it/s]

 43%|████▎     | 43429/100629 [34:17<52:49, 18.05it/s]

 43%|████▎     | 43431/100629 [34:17<55:00, 17.33it/s]

 43%|████▎     | 43435/100629 [34:17<44:31, 21.41it/s]

 43%|████▎     | 43438/100629 [34:18<43:13, 22.06it/s]

 43%|████▎     | 43441/100629 [34:18<40:05, 23.78it/s]

 43%|████▎     | 43444/100629 [34:18<49:16, 19.34it/s]

 43%|████▎     | 43449/100629 [34:18<38:45, 24.59it/s]

 43%|████▎     | 43453/100629 [34:18<42:40, 22.33it/s]

 43%|████▎     | 43456/100629 [34:19<53:58, 17.65it/s]

 43%|████▎     | 43461/100629 [34:19<47:05, 20.23it/s]

 43%|████▎     | 43464/100629 [34:19<1:03:41, 14.96it/s]

 43%|████▎     | 43467/100629 [34:19<1:00:34, 15.73it/s]

 43%|████▎     | 43469/100629 [34:19<58:12, 16.37it/s]

 43%|████▎     | 43472/100629 [34:19<56:32, 16.85it/s]

 43%|████▎     | 43474/100629 [34:20<54:53, 17.35it/s]

 43%|████▎     | 43477/100629 [34:20<48:41, 19.56it/s]

 43%|████▎     | 43480/100629 [34:20<57:30, 16.56it/s]

 43%|████▎     | 43485/100629 [34:20<45:31, 20.92it/s]

 43%|████▎     | 43488/100629 [34:20<45:44, 20.82it/s]

 43%|████▎     | 43491/100629 [34:20<44:01, 21.63it/s]

 43%|████▎     | 43494/100629 [34:21<44:50, 21.23it/s]

 43%|████▎     | 43497/100629 [34:21<44:17, 21.50it/s]

 43%|████▎     | 43500/100629 [34:21<43:16, 22.00it/s]

 43%|████▎     | 43503/100629 [34:21<57:03, 16.69it/s]

 43%|████▎     | 43506/100629 [34:21<49:34, 19.21it/s]

 43%|████▎     | 43509/100629 [34:21<47:09, 20.19it/s]

 43%|████▎     | 43512/100629 [34:22<54:04, 17.60it/s]

 43%|████▎     | 43514/100629 [34:22<55:12, 17.24it/s]

 43%|████▎     | 43517/100629 [34:22<52:49, 18.02it/s]

 43%|████▎     | 43519/100629 [34:22<54:34, 17.44it/s]

 43%|████▎     | 43522/100629 [34:22<47:52, 19.88it/s]

 43%|████▎     | 43525/100629 [34:22<47:40, 19.96it/s]

 43%|████▎     | 43528/100629 [34:22<46:26, 20.49it/s]

 43%|████▎     | 43532/100629 [34:22<37:58, 25.05it/s]

 43%|████▎     | 43535/100629 [34:23<40:57, 23.23it/s]

 43%|████▎     | 43538/100629 [34:23<45:17, 21.01it/s]

 43%|████▎     | 43541/100629 [34:23<41:48, 22.76it/s]

 43%|████▎     | 43544/100629 [34:23<43:51, 21.69it/s]

 43%|████▎     | 43547/100629 [34:23<47:04, 20.21it/s]

 43%|████▎     | 43550/100629 [34:23<58:06, 16.37it/s]

 43%|████▎     | 43552/100629 [34:24<1:01:28, 15.47it/s]

 43%|████▎     | 43554/100629 [34:24<1:06:58, 14.20it/s]

 43%|████▎     | 43558/100629 [34:24<56:22, 16.87it/s]

 43%|████▎     | 43561/100629 [34:24<49:51, 19.08it/s]

 43%|████▎     | 43565/100629 [34:24<43:13, 22.00it/s]

 43%|████▎     | 43568/100629 [34:24<41:40, 22.82it/s]

 43%|████▎     | 43571/100629 [34:24<43:02, 22.09it/s]

 43%|████▎     | 43574/100629 [34:25<50:00, 19.01it/s]

 43%|████▎     | 43578/100629 [34:25<42:12, 22.53it/s]

 43%|████▎     | 43582/100629 [34:25<36:49, 25.82it/s]

 43%|████▎     | 43585/100629 [34:25<36:05, 26.35it/s]

 43%|████▎     | 43589/100629 [34:25<31:58, 29.73it/s]

 43%|████▎     | 43593/100629 [34:25<41:48, 22.74it/s]

 43%|████▎     | 43596/100629 [34:25<40:45, 23.32it/s]

 43%|████▎     | 43602/100629 [34:26<30:28, 31.19it/s]

 43%|████▎     | 43606/100629 [34:26<28:37, 33.21it/s]

 43%|████▎     | 43610/100629 [34:26<31:49, 29.86it/s]

 43%|████▎     | 43614/100629 [34:26<37:49, 25.12it/s]

 43%|████▎     | 43617/100629 [34:26<40:36, 23.39it/s]

 43%|████▎     | 43620/100629 [34:27<56:05, 16.94it/s]

 43%|████▎     | 43623/100629 [34:27<54:04, 17.57it/s]

 43%|████▎     | 43626/100629 [34:27<51:15, 18.54it/s]

 43%|████▎     | 43629/100629 [34:27<49:40, 19.12it/s]

 43%|████▎     | 43632/100629 [34:27<47:47, 19.88it/s]

 43%|████▎     | 43635/100629 [34:27<51:23, 18.48it/s]

 43%|████▎     | 43639/100629 [34:27<42:05, 22.56it/s]

 43%|████▎     | 43642/100629 [34:28<39:20, 24.15it/s]

 43%|████▎     | 43646/100629 [34:28<41:50, 22.70it/s]

 43%|████▎     | 43649/100629 [34:28<43:53, 21.64it/s]

 43%|████▎     | 43652/100629 [34:28<42:51, 22.15it/s]

 43%|████▎     | 43655/100629 [34:28<43:29, 21.83it/s]

 43%|████▎     | 43659/100629 [34:28<40:58, 23.17it/s]

 43%|████▎     | 43664/100629 [34:28<36:38, 25.91it/s]

 43%|████▎     | 43667/100629 [34:29<38:58, 24.36it/s]

 43%|████▎     | 43670/100629 [34:29<37:59, 24.99it/s]

 43%|████▎     | 43675/100629 [34:29<32:54, 28.84it/s]

 43%|████▎     | 43678/100629 [34:29<42:01, 22.58it/s]

 43%|████▎     | 43681/100629 [34:29<45:04, 21.06it/s]

 43%|████▎     | 43684/100629 [34:29<41:59, 22.60it/s]

 43%|████▎     | 43687/100629 [34:30<45:45, 20.74it/s]

 43%|████▎     | 43691/100629 [34:30<43:33, 21.79it/s]

 43%|████▎     | 43694/100629 [34:30<45:05, 21.04it/s]

 43%|████▎     | 43697/100629 [34:30<46:37, 20.35it/s]

 43%|████▎     | 43701/100629 [34:30<39:26, 24.06it/s]

 43%|████▎     | 43704/100629 [34:30<40:04, 23.68it/s]

 43%|████▎     | 43709/100629 [34:30<34:55, 27.16it/s]

 43%|████▎     | 43712/100629 [34:31<36:04, 26.30it/s]

 43%|████▎     | 43715/100629 [34:31<35:07, 27.01it/s]

 43%|████▎     | 43718/100629 [34:31<34:46, 27.27it/s]

 43%|████▎     | 43722/100629 [34:31<32:00, 29.63it/s]

 43%|████▎     | 43726/100629 [34:31<31:33, 30.05it/s]

 43%|████▎     | 43730/100629 [34:31<30:11, 31.42it/s]

 43%|████▎     | 43734/100629 [34:31<33:32, 28.27it/s]

 43%|████▎     | 43739/100629 [34:31<29:24, 32.24it/s]

 43%|████▎     | 43743/100629 [34:32<36:55, 25.68it/s]

 43%|████▎     | 43746/100629 [34:32<39:11, 24.19it/s]

 43%|████▎     | 43750/100629 [34:32<35:03, 27.04it/s]

 43%|████▎     | 43753/100629 [34:32<34:54, 27.15it/s]

 43%|████▎     | 43756/100629 [34:32<36:26, 26.01it/s]

 43%|████▎     | 43759/100629 [34:32<35:59, 26.33it/s]

 43%|████▎     | 43762/100629 [34:32<41:51, 22.65it/s]

 43%|████▎     | 43765/100629 [34:33<42:12, 22.45it/s]

 43%|████▎     | 43768/100629 [34:33<52:52, 17.92it/s]

 43%|████▎     | 43770/100629 [34:33<52:05, 18.19it/s]

 44%|████▎     | 43774/100629 [34:33<43:42, 21.68it/s]

 44%|████▎     | 43777/100629 [34:33<43:25, 21.82it/s]

 44%|████▎     | 43780/100629 [34:33<46:04, 20.56it/s]

 44%|████▎     | 43784/100629 [34:33<40:10, 23.58it/s]

 44%|████▎     | 43787/100629 [34:34<41:50, 22.65it/s]

 44%|████▎     | 43790/100629 [34:34<50:31, 18.75it/s]

 44%|████▎     | 43793/100629 [34:34<48:14, 19.63it/s]

 44%|████▎     | 43796/100629 [34:34<48:45, 19.43it/s]

 44%|████▎     | 43800/100629 [34:34<41:58, 22.56it/s]

 44%|████▎     | 43803/100629 [34:34<47:32, 19.92it/s]

 44%|████▎     | 43807/100629 [34:35<41:01, 23.09it/s]

 44%|████▎     | 43810/100629 [34:35<41:11, 22.99it/s]

 44%|████▎     | 43813/100629 [34:35<40:28, 23.39it/s]

 44%|████▎     | 43817/100629 [34:35<40:54, 23.15it/s]

 44%|████▎     | 43820/100629 [34:35<40:53, 23.15it/s]

 44%|████▎     | 43823/100629 [34:35<42:27, 22.30it/s]

 44%|████▎     | 43826/100629 [34:35<41:12, 22.97it/s]

 44%|████▎     | 43829/100629 [34:35<39:55, 23.71it/s]

 44%|████▎     | 43832/100629 [34:36<40:16, 23.50it/s]

 44%|████▎     | 43835/100629 [34:36<43:23, 21.81it/s]

 44%|████▎     | 43838/100629 [34:36<41:20, 22.89it/s]

 44%|████▎     | 43841/100629 [34:36<38:46, 24.41it/s]

 44%|████▎     | 43844/100629 [34:36<49:15, 19.21it/s]

 44%|████▎     | 43847/100629 [34:36<45:33, 20.77it/s]

 44%|████▎     | 43850/100629 [34:37<56:01, 16.89it/s]

 44%|████▎     | 43854/100629 [34:37<48:23, 19.55it/s]

 44%|████▎     | 43857/100629 [34:37<46:57, 20.15it/s]

 44%|████▎     | 43860/100629 [34:37<48:03, 19.69it/s]

 44%|████▎     | 43863/100629 [34:37<47:00, 20.13it/s]

 44%|████▎     | 43866/100629 [34:37<55:03, 17.18it/s]

 44%|████▎     | 43870/100629 [34:38<43:53, 21.56it/s]

 44%|████▎     | 43876/100629 [34:38<34:39, 27.29it/s]

 44%|████▎     | 43879/100629 [34:38<38:46, 24.39it/s]

 44%|████▎     | 43882/100629 [34:38<38:53, 24.32it/s]

 44%|████▎     | 43885/100629 [34:38<37:43, 25.07it/s]

 44%|████▎     | 43888/100629 [34:38<41:38, 22.71it/s]

 44%|████▎     | 43891/100629 [34:38<45:05, 20.97it/s]

 44%|████▎     | 43894/100629 [34:39<46:20, 20.41it/s]

 44%|████▎     | 43897/100629 [34:39<50:19, 18.79it/s]

 44%|████▎     | 43899/100629 [34:39<52:18, 18.08it/s]

 44%|████▎     | 43901/100629 [34:39<52:25, 18.03it/s]

 44%|████▎     | 43904/100629 [34:39<49:25, 19.13it/s]

 44%|████▎     | 43907/100629 [34:39<50:05, 18.87it/s]

 44%|████▎     | 43913/100629 [34:39<36:05, 26.20it/s]

 44%|████▎     | 43916/100629 [34:40<35:16, 26.79it/s]

 44%|████▎     | 43920/100629 [34:40<36:30, 25.89it/s]

 44%|████▎     | 43923/100629 [34:40<38:22, 24.63it/s]

 44%|████▎     | 43926/100629 [34:40<40:44, 23.20it/s]

 44%|████▎     | 43929/100629 [34:40<39:33, 23.88it/s]

 44%|████▎     | 43933/100629 [34:40<37:27, 25.23it/s]

 44%|████▎     | 43936/100629 [34:40<42:18, 22.34it/s]

 44%|████▎     | 43939/100629 [34:41<56:56, 16.59it/s]

 44%|████▎     | 43942/100629 [34:41<52:58, 17.83it/s]

 44%|████▎     | 43945/100629 [34:41<50:27, 18.72it/s]

 44%|████▎     | 43949/100629 [34:41<41:57, 22.51it/s]

 44%|████▎     | 43953/100629 [34:41<37:57, 24.88it/s]

 44%|████▎     | 43957/100629 [34:41<35:06, 26.90it/s]

 44%|████▎     | 43960/100629 [34:42<39:25, 23.95it/s]

 44%|████▎     | 43963/100629 [34:42<42:31, 22.20it/s]

 44%|████▎     | 43968/100629 [34:42<36:01, 26.21it/s]

 44%|████▎     | 43972/100629 [34:42<37:47, 24.99it/s]

 44%|████▎     | 43975/100629 [34:42<50:38, 18.64it/s]

 44%|████▎     | 43978/100629 [34:42<51:51, 18.20it/s]

 44%|████▎     | 43981/100629 [34:43<51:40, 18.27it/s]

 44%|████▎     | 43984/100629 [34:43<47:31, 19.86it/s]

 44%|████▎     | 43987/100629 [34:43<52:17, 18.05it/s]

 44%|████▎     | 43990/100629 [34:43<52:27, 17.99it/s]

 44%|████▎     | 43993/100629 [34:43<46:44, 20.20it/s]

 44%|████▎     | 43996/100629 [34:44<1:01:35, 15.33it/s]

 44%|████▎     | 43998/100629 [34:44<59:33, 15.85it/s]

 44%|████▎     | 44000/100629 [34:44<1:03:42, 14.81it/s]

 44%|████▎     | 44006/100629 [34:44<43:41, 21.60it/s]

 44%|████▎     | 44009/100629 [34:44<46:48, 20.16it/s]

 44%|████▎     | 44012/100629 [34:44<43:55, 21.48it/s]

 44%|████▎     | 44015/100629 [34:44<41:21, 22.81it/s]

 44%|████▎     | 44018/100629 [34:44<38:51, 24.28it/s]

 44%|████▎     | 44021/100629 [34:45<38:01, 24.81it/s]

 44%|████▎     | 44024/100629 [34:45<58:00, 16.26it/s]

 44%|████▍     | 44027/100629 [34:45<1:02:00, 15.21it/s]

 44%|████▍     | 44029/100629 [34:45<1:00:46, 15.52it/s]

 44%|████▍     | 44032/100629 [34:45<57:06, 16.52it/s]

 44%|████▍     | 44035/100629 [34:46<52:04, 18.11it/s]

 44%|████▍     | 44038/100629 [34:46<48:28, 19.46it/s]

 44%|████▍     | 44041/100629 [34:46<46:19, 20.36it/s]

 44%|████▍     | 44044/100629 [34:46<46:45, 20.17it/s]

 44%|████▍     | 44047/100629 [34:46<52:05, 18.10it/s]

 44%|████▍     | 44050/100629 [34:46<51:00, 18.49it/s]

 44%|████▍     | 44055/100629 [34:46<39:30, 23.86it/s]

 44%|████▍     | 44062/100629 [34:47<29:04, 32.43it/s]

 44%|████▍     | 44066/100629 [34:47<28:02, 33.62it/s]

 44%|████▍     | 44070/100629 [34:47<32:08, 29.33it/s]

 44%|████▍     | 44074/100629 [34:47<36:29, 25.83it/s]

 44%|████▍     | 44077/100629 [34:47<36:18, 25.96it/s]

 44%|████▍     | 44080/100629 [34:47<35:17, 26.70it/s]

 44%|████▍     | 44083/100629 [34:47<35:41, 26.41it/s]

 44%|████▍     | 44086/100629 [34:47<35:04, 26.86it/s]

 44%|████▍     | 44090/100629 [34:48<31:56, 29.50it/s]

 44%|████▍     | 44094/100629 [34:48<36:23, 25.89it/s]

 44%|████▍     | 44098/100629 [34:48<32:49, 28.71it/s]

 44%|████▍     | 44102/100629 [34:48<33:02, 28.51it/s]

 44%|████▍     | 44105/100629 [34:48<33:41, 27.96it/s]

 44%|████▍     | 44108/100629 [34:48<37:53, 24.87it/s]

 44%|████▍     | 44111/100629 [34:49<45:54, 20.52it/s]

 44%|████▍     | 44114/100629 [34:49<46:15, 20.36it/s]

 44%|████▍     | 44118/100629 [34:49<39:22, 23.92it/s]

 44%|████▍     | 44121/100629 [34:49<41:47, 22.54it/s]

 44%|████▍     | 44124/100629 [34:49<39:43, 23.70it/s]

 44%|████▍     | 44127/100629 [34:49<41:17, 22.81it/s]

 44%|████▍     | 44130/100629 [34:49<41:21, 22.77it/s]

 44%|████▍     | 44134/100629 [34:49<37:53, 24.85it/s]

 44%|████▍     | 44137/100629 [34:50<44:56, 20.95it/s]

 44%|████▍     | 44142/100629 [34:50<37:47, 24.92it/s]

 44%|████▍     | 44147/100629 [34:50<31:38, 29.75it/s]

 44%|████▍     | 44151/100629 [34:50<36:24, 25.86it/s]

 44%|████▍     | 44154/100629 [34:50<39:30, 23.83it/s]

 44%|████▍     | 44157/100629 [34:50<44:01, 21.38it/s]

 44%|████▍     | 44160/100629 [34:51<55:01, 17.10it/s]

 44%|████▍     | 44163/100629 [34:51<49:50, 18.88it/s]

 44%|████▍     | 44166/100629 [34:51<49:13, 19.12it/s]

 44%|████▍     | 44170/100629 [34:51<44:02, 21.36it/s]

 44%|████▍     | 44173/100629 [34:51<42:21, 22.21it/s]

 44%|████▍     | 44176/100629 [34:51<44:22, 21.20it/s]

 44%|████▍     | 44179/100629 [34:52<47:54, 19.64it/s]

 44%|████▍     | 44182/100629 [34:52<45:32, 20.66it/s]

 44%|████▍     | 44185/100629 [34:52<43:00, 21.87it/s]

 44%|████▍     | 44188/100629 [34:52<45:43, 20.57it/s]

 44%|████▍     | 44192/100629 [34:52<39:09, 24.02it/s]

 44%|████▍     | 44195/100629 [34:52<40:03, 23.48it/s]

 44%|████▍     | 44198/100629 [34:52<38:57, 24.14it/s]

 44%|████▍     | 44201/100629 [34:53<39:36, 23.75it/s]

 44%|████▍     | 44205/100629 [34:53<37:44, 24.92it/s]

 44%|████▍     | 44208/100629 [34:53<40:49, 23.03it/s]

 44%|████▍     | 44211/100629 [34:53<40:19, 23.32it/s]

 44%|████▍     | 44214/100629 [34:53<48:51, 19.25it/s]

 44%|████▍     | 44217/100629 [34:53<46:57, 20.02it/s]

 44%|████▍     | 44220/100629 [34:53<42:31, 22.11it/s]

 44%|████▍     | 44224/100629 [34:54<36:38, 25.66it/s]

 44%|████▍     | 44227/100629 [34:54<39:49, 23.60it/s]

 44%|████▍     | 44230/100629 [34:54<38:29, 24.42it/s]

 44%|████▍     | 44233/100629 [34:54<41:00, 22.92it/s]

 44%|████▍     | 44236/100629 [34:54<51:27, 18.27it/s]

 44%|████▍     | 44239/100629 [34:54<57:43, 16.28it/s]

 44%|████▍     | 44242/100629 [34:55<50:26, 18.63it/s]

 44%|████▍     | 44246/100629 [34:55<44:44, 21.00it/s]

 44%|████▍     | 44249/100629 [34:55<50:58, 18.44it/s]

 44%|████▍     | 44252/100629 [34:55<54:07, 17.36it/s]

 44%|████▍     | 44256/100629 [34:55<44:38, 21.04it/s]

 44%|████▍     | 44260/100629 [34:55<40:06, 23.42it/s]

 44%|████▍     | 44263/100629 [34:55<39:03, 24.05it/s]

 44%|████▍     | 44266/100629 [34:56<39:26, 23.82it/s]

 44%|████▍     | 44270/100629 [34:56<35:43, 26.29it/s]

 44%|████▍     | 44274/100629 [34:56<35:05, 26.77it/s]

 44%|████▍     | 44278/100629 [34:56<31:38, 29.69it/s]

 44%|████▍     | 44282/100629 [34:56<30:12, 31.09it/s]

 44%|████▍     | 44286/100629 [34:56<36:17, 25.87it/s]

 44%|████▍     | 44289/100629 [34:57<47:38, 19.71it/s]

 44%|████▍     | 44292/100629 [34:57<46:36, 20.15it/s]

 44%|████▍     | 44296/100629 [34:57<40:01, 23.45it/s]

 44%|████▍     | 44299/100629 [34:57<39:00, 24.07it/s]

 44%|████▍     | 44302/100629 [34:57<40:28, 23.19it/s]

 44%|████▍     | 44305/100629 [34:57<39:58, 23.49it/s]

 44%|████▍     | 44308/100629 [34:57<40:00, 23.46it/s]

 44%|████▍     | 44311/100629 [34:57<41:13, 22.77it/s]

 44%|████▍     | 44314/100629 [34:58<42:45, 21.95it/s]

 44%|████▍     | 44317/100629 [34:58<44:06, 21.28it/s]

 44%|████▍     | 44320/100629 [34:58<46:25, 20.21it/s]

 44%|████▍     | 44323/100629 [34:58<44:09, 21.25it/s]

 44%|████▍     | 44326/100629 [34:58<45:19, 20.71it/s]

 44%|████▍     | 44329/100629 [34:58<56:43, 16.54it/s]

 44%|████▍     | 44332/100629 [34:59<51:07, 18.35it/s]

 44%|████▍     | 44335/100629 [34:59<49:26, 18.97it/s]

 44%|████▍     | 44338/100629 [34:59<47:46, 19.64it/s]

 44%|████▍     | 44341/100629 [34:59<47:05, 19.92it/s]

 44%|████▍     | 44344/100629 [34:59<44:53, 20.89it/s]

 44%|████▍     | 44347/100629 [34:59<44:39, 21.01it/s]

 44%|████▍     | 44350/100629 [35:00<56:10, 16.70it/s]

 44%|████▍     | 44352/100629 [35:00<55:07, 17.02it/s]

 44%|████▍     | 44357/100629 [35:00<45:20, 20.68it/s]

 44%|████▍     | 44360/100629 [35:00<42:49, 21.90it/s]

 44%|████▍     | 44363/100629 [35:00<51:11, 18.32it/s]

 44%|████▍     | 44365/100629 [35:00<52:56, 17.71it/s]

 44%|████▍     | 44367/100629 [35:00<56:30, 16.60it/s]

 44%|████▍     | 44371/100629 [35:01<44:26, 21.10it/s]

 44%|████▍     | 44374/100629 [35:01<47:49, 19.60it/s]

 44%|████▍     | 44377/100629 [35:01<51:42, 18.13it/s]

 44%|████▍     | 44379/100629 [35:01<58:15, 16.09it/s]

 44%|████▍     | 44382/100629 [35:01<55:21, 16.93it/s]

 44%|████▍     | 44384/100629 [35:01<57:29, 16.31it/s]

 44%|████▍     | 44387/100629 [35:02<57:24, 16.33it/s]

 44%|████▍     | 44389/100629 [35:02<56:02, 16.72it/s]

 44%|████▍     | 44392/100629 [35:02<55:17, 16.95it/s]

 44%|████▍     | 44395/100629 [35:02<49:16, 19.02it/s]

 44%|████▍     | 44397/100629 [35:02<53:21, 17.56it/s]

 44%|████▍     | 44402/100629 [35:02<39:19, 23.83it/s]

 44%|████▍     | 44405/100629 [35:02<37:42, 24.85it/s]

 44%|████▍     | 44410/100629 [35:02<30:52, 30.34it/s]

 44%|████▍     | 44414/100629 [35:03<31:36, 29.64it/s]

 44%|████▍     | 44418/100629 [35:03<40:04, 23.38it/s]

 44%|████▍     | 44421/100629 [35:03<38:10, 24.54it/s]

 44%|████▍     | 44424/100629 [35:03<43:34, 21.50it/s]

 44%|████▍     | 44428/100629 [35:03<41:03, 22.82it/s]

 44%|████▍     | 44431/100629 [35:04<47:50, 19.58it/s]

 44%|████▍     | 44434/100629 [35:04<47:46, 19.61it/s]

 44%|████▍     | 44437/100629 [35:04<46:27, 20.16it/s]

 44%|████▍     | 44440/100629 [35:04<42:29, 22.04it/s]

 44%|████▍     | 44443/100629 [35:04<44:45, 20.92it/s]

 44%|████▍     | 44447/100629 [35:04<40:18, 23.23it/s]

 44%|████▍     | 44450/100629 [35:04<46:45, 20.02it/s]

 44%|████▍     | 44453/100629 [35:05<1:05:55, 14.20it/s]

 44%|████▍     | 44456/100629 [35:05<1:02:48, 14.91it/s]

 44%|████▍     | 44459/100629 [35:05<56:14, 16.65it/s]

 44%|████▍     | 44462/100629 [35:05<49:27, 18.93it/s]

 44%|████▍     | 44465/100629 [35:05<45:14, 20.69it/s]

 44%|████▍     | 44468/100629 [35:06<56:36, 16.54it/s]

 44%|████▍     | 44471/100629 [35:06<49:42, 18.83it/s]

 44%|████▍     | 44474/100629 [35:06<54:20, 17.22it/s]

 44%|████▍     | 44478/100629 [35:06<46:08, 20.28it/s]

 44%|████▍     | 44482/100629 [35:06<42:00, 22.28it/s]

 44%|████▍     | 44485/100629 [35:06<47:12, 19.82it/s]

 44%|████▍     | 44488/100629 [35:06<43:07, 21.69it/s]

 44%|████▍     | 44492/100629 [35:07<38:20, 24.40it/s]

 44%|████▍     | 44495/100629 [35:07<37:49, 24.74it/s]

 44%|████▍     | 44499/100629 [35:07<35:16, 26.52it/s]

 44%|████▍     | 44503/100629 [35:07<31:46, 29.44it/s]

 44%|████▍     | 44507/100629 [35:07<38:00, 24.61it/s]

 44%|████▍     | 44511/100629 [35:07<35:41, 26.21it/s]

 44%|████▍     | 44515/100629 [35:07<33:40, 27.77it/s]

 44%|████▍     | 44518/100629 [35:08<37:52, 24.69it/s]

 44%|████▍     | 44521/100629 [35:08<38:46, 24.12it/s]

 44%|████▍     | 44524/100629 [35:08<41:01, 22.79it/s]

 44%|████▍     | 44529/100629 [35:08<32:42, 28.58it/s]

 44%|████▍     | 44533/100629 [35:08<31:14, 29.93it/s]

 44%|████▍     | 44537/100629 [35:08<38:52, 24.05it/s]

 44%|████▍     | 44542/100629 [35:08<32:21, 28.89it/s]

 44%|████▍     | 44546/100629 [35:09<36:23, 25.68it/s]

 44%|████▍     | 44549/100629 [35:09<35:26, 26.38it/s]

 44%|████▍     | 44554/100629 [35:09<31:31, 29.64it/s]

 44%|████▍     | 44558/100629 [35:09<31:46, 29.41it/s]

 44%|████▍     | 44562/100629 [35:09<43:16, 21.60it/s]

 44%|████▍     | 44565/100629 [35:09<43:05, 21.68it/s]

 44%|████▍     | 44568/100629 [35:10<43:11, 21.63it/s]

 44%|████▍     | 44571/100629 [35:10<49:33, 18.86it/s]

 44%|████▍     | 44574/100629 [35:10<44:43, 20.89it/s]

 44%|████▍     | 44577/100629 [35:10<42:38, 21.90it/s]

 44%|████▍     | 44580/100629 [35:10<41:58, 22.25it/s]

 44%|████▍     | 44583/100629 [35:10<53:53, 17.33it/s]

 44%|████▍     | 44587/100629 [35:11<44:03, 21.20it/s]

 44%|████▍     | 44590/100629 [35:11<49:18, 18.94it/s]

 44%|████▍     | 44593/100629 [35:11<44:18, 21.08it/s]

 44%|████▍     | 44596/100629 [35:11<44:54, 20.79it/s]

 44%|████▍     | 44599/100629 [35:11<44:44, 20.87it/s]

 44%|████▍     | 44602/100629 [35:11<43:31, 21.45it/s]

 44%|████▍     | 44605/100629 [35:11<47:54, 19.49it/s]

 44%|████▍     | 44608/100629 [35:12<47:59, 19.46it/s]

 44%|████▍     | 44611/100629 [35:12<43:55, 21.25it/s]

 44%|████▍     | 44615/100629 [35:12<41:25, 22.54it/s]

 44%|████▍     | 44618/100629 [35:12<42:51, 21.78it/s]

 44%|████▍     | 44622/100629 [35:12<39:27, 23.65it/s]

 44%|████▍     | 44625/100629 [35:12<39:53, 23.39it/s]

 44%|████▍     | 44628/100629 [35:13<47:58, 19.45it/s]

 44%|████▍     | 44631/100629 [35:13<48:16, 19.33it/s]

 44%|████▍     | 44634/100629 [35:13<49:56, 18.68it/s]

 44%|████▍     | 44636/100629 [35:13<57:50, 16.13it/s]

 44%|████▍     | 44640/100629 [35:13<46:40, 19.99it/s]

 44%|████▍     | 44643/100629 [35:13<46:17, 20.16it/s]

 44%|████▍     | 44646/100629 [35:13<45:16, 20.61it/s]

 44%|████▍     | 44649/100629 [35:14<43:30, 21.44it/s]

 44%|████▍     | 44652/100629 [35:14<42:59, 21.70it/s]

 44%|████▍     | 44655/100629 [35:14<58:52, 15.84it/s]

 44%|████▍     | 44658/100629 [35:14<54:17, 17.18it/s]

 44%|████▍     | 44661/100629 [35:14<48:34, 19.20it/s]

 44%|████▍     | 44664/100629 [35:14<45:29, 20.50it/s]

 44%|████▍     | 44667/100629 [35:15<41:58, 22.22it/s]

 44%|████▍     | 44670/100629 [35:15<43:04, 21.65it/s]

 44%|████▍     | 44673/100629 [35:15<44:27, 20.98it/s]

 44%|████▍     | 44677/100629 [35:15<38:32, 24.20it/s]

 44%|████▍     | 44680/100629 [35:15<40:21, 23.11it/s]

 44%|████▍     | 44683/100629 [35:15<38:31, 24.21it/s]

 44%|████▍     | 44689/100629 [35:15<32:37, 28.57it/s]

 44%|████▍     | 44692/100629 [35:16<37:39, 24.76it/s]

 44%|████▍     | 44695/100629 [35:16<38:29, 24.22it/s]

 44%|████▍     | 44698/100629 [35:16<38:10, 24.42it/s]

 44%|████▍     | 44701/100629 [35:16<39:30, 23.60it/s]

 44%|████▍     | 44704/100629 [35:16<38:56, 23.94it/s]

 44%|████▍     | 44707/100629 [35:16<37:49, 24.64it/s]

 44%|████▍     | 44711/100629 [35:16<33:22, 27.92it/s]

 44%|████▍     | 44714/100629 [35:16<38:36, 24.14it/s]

 44%|████▍     | 44718/100629 [35:17<33:23, 27.91it/s]

 44%|████▍     | 44721/100629 [35:17<49:14, 18.92it/s]

 44%|████▍     | 44724/100629 [35:17<45:14, 20.60it/s]

 44%|████▍     | 44727/100629 [35:17<52:08, 17.87it/s]

 44%|████▍     | 44730/100629 [35:17<52:19, 17.81it/s]

 44%|████▍     | 44734/100629 [35:17<43:52, 21.24it/s]

 44%|████▍     | 44737/100629 [35:18<46:14, 20.14it/s]

 44%|████▍     | 44740/100629 [35:18<45:39, 20.40it/s]

 44%|████▍     | 44743/100629 [35:18<41:41, 22.34it/s]

 44%|████▍     | 44746/100629 [35:18<39:58, 23.30it/s]

 44%|████▍     | 44749/100629 [35:18<47:47, 19.49it/s]

 44%|████▍     | 44753/100629 [35:18<40:47, 22.83it/s]

 44%|████▍     | 44756/100629 [35:18<45:30, 20.47it/s]

 44%|████▍     | 44759/100629 [35:19<46:31, 20.02it/s]

 44%|████▍     | 44762/100629 [35:19<43:16, 21.52it/s]

 44%|████▍     | 44765/100629 [35:19<43:24, 21.45it/s]

 44%|████▍     | 44768/100629 [35:19<44:20, 21.00it/s]

 44%|████▍     | 44771/100629 [35:19<46:07, 20.18it/s]

 44%|████▍     | 44774/100629 [35:19<43:03, 21.62it/s]

 44%|████▍     | 44778/100629 [35:19<37:02, 25.13it/s]

 45%|████▍     | 44781/100629 [35:20<36:57, 25.19it/s]

 45%|████▍     | 44784/100629 [35:20<52:18, 17.80it/s]

 45%|████▍     | 44787/100629 [35:20<51:31, 18.06it/s]

 45%|████▍     | 44790/100629 [35:20<56:56, 16.35it/s]

 45%|████▍     | 44792/100629 [35:20<54:53, 16.95it/s]

 45%|████▍     | 44794/100629 [35:20<56:04, 16.60it/s]

 45%|████▍     | 44799/100629 [35:21<45:53, 20.28it/s]

 45%|████▍     | 44803/100629 [35:21<40:40, 22.88it/s]

 45%|████▍     | 44808/100629 [35:21<33:07, 28.08it/s]

 45%|████▍     | 44811/100629 [35:21<35:23, 26.29it/s]

 45%|████▍     | 44814/100629 [35:21<41:28, 22.42it/s]

 45%|████▍     | 44818/100629 [35:21<36:54, 25.21it/s]

 45%|████▍     | 44821/100629 [35:22<40:45, 22.82it/s]

 45%|████▍     | 44824/100629 [35:22<41:07, 22.62it/s]

 45%|████▍     | 44827/100629 [35:22<42:10, 22.05it/s]

 45%|████▍     | 44831/100629 [35:22<38:18, 24.27it/s]

 45%|████▍     | 44834/100629 [35:22<43:57, 21.16it/s]

 45%|████▍     | 44840/100629 [35:22<37:28, 24.81it/s]

 45%|████▍     | 44843/100629 [35:23<44:55, 20.70it/s]

 45%|████▍     | 44846/100629 [35:23<42:34, 21.83it/s]

 45%|████▍     | 44849/100629 [35:23<47:13, 19.68it/s]

 45%|████▍     | 44852/100629 [35:23<50:36, 18.37it/s]

 45%|████▍     | 44854/100629 [35:23<53:14, 17.46it/s]

 45%|████▍     | 44858/100629 [35:23<43:08, 21.55it/s]

 45%|████▍     | 44861/100629 [35:23<45:28, 20.44it/s]

 45%|████▍     | 44864/100629 [35:24<46:43, 19.89it/s]

 45%|████▍     | 44867/100629 [35:24<44:55, 20.69it/s]

 45%|████▍     | 44870/100629 [35:24<47:09, 19.70it/s]

 45%|████▍     | 44873/100629 [35:24<43:16, 21.48it/s]

 45%|████▍     | 44876/100629 [35:24<40:40, 22.84it/s]

 45%|████▍     | 44879/100629 [35:24<42:02, 22.10it/s]

 45%|████▍     | 44882/100629 [35:24<39:54, 23.28it/s]

 45%|████▍     | 44886/100629 [35:25<40:53, 22.72it/s]

 45%|████▍     | 44889/100629 [35:25<48:24, 19.19it/s]

 45%|████▍     | 44892/100629 [35:25<45:59, 20.20it/s]

 45%|████▍     | 44896/100629 [35:25<1:00:45, 15.29it/s]

 45%|████▍     | 44900/100629 [35:25<48:49, 19.02it/s]

 45%|████▍     | 44903/100629 [35:26<52:00, 17.86it/s]

 45%|████▍     | 44906/100629 [35:26<52:06, 17.82it/s]

 45%|████▍     | 44909/100629 [35:26<52:36, 17.65it/s]

 45%|████▍     | 44913/100629 [35:26<48:17, 19.23it/s]

 45%|████▍     | 44916/100629 [35:26<1:01:15, 15.16it/s]

 45%|████▍     | 44918/100629 [35:27<58:55, 15.76it/s]

 45%|████▍     | 44920/100629 [35:27<1:03:50, 14.54it/s]

 45%|████▍     | 44922/100629 [35:27<1:10:12, 13.22it/s]

 45%|████▍     | 44925/100629 [35:27<1:01:07, 15.19it/s]

 45%|████▍     | 44927/100629 [35:27<58:11, 15.95it/s]

 45%|████▍     | 44931/100629 [35:27<46:26, 19.99it/s]

 45%|████▍     | 44934/100629 [35:27<51:49, 17.91it/s]

 45%|████▍     | 44936/100629 [35:28<1:03:15, 14.67it/s]

 45%|████▍     | 44939/100629 [35:28<53:37, 17.31it/s]

 45%|████▍     | 44942/100629 [35:28<49:11, 18.87it/s]

 45%|████▍     | 44945/100629 [35:28<47:43, 19.45it/s]

 45%|████▍     | 44950/100629 [35:28<37:46, 24.56it/s]

 45%|████▍     | 44953/100629 [35:28<36:14, 25.61it/s]

 45%|████▍     | 44957/100629 [35:28<32:05, 28.91it/s]

 45%|████▍     | 44961/100629 [35:29<32:51, 28.24it/s]

 45%|████▍     | 44964/100629 [35:29<36:24, 25.48it/s]

 45%|████▍     | 44967/100629 [35:29<36:57, 25.10it/s]

 45%|████▍     | 44971/100629 [35:29<34:04, 27.23it/s]

 45%|████▍     | 44974/100629 [35:29<44:30, 20.84it/s]

 45%|████▍     | 44977/100629 [35:29<44:03, 21.05it/s]

 45%|████▍     | 44980/100629 [35:29<42:08, 22.01it/s]

 45%|████▍     | 44983/100629 [35:30<50:28, 18.37it/s]

 45%|████▍     | 44986/100629 [35:30<49:31, 18.72it/s]

 45%|████▍     | 44989/100629 [35:30<45:00, 20.61it/s]

 45%|████▍     | 44992/100629 [35:30<45:32, 20.36it/s]

 45%|████▍     | 44996/100629 [35:30<44:55, 20.64it/s]

 45%|████▍     | 44999/100629 [35:30<42:41, 21.71it/s]

 45%|████▍     | 45002/100629 [35:31<41:19, 22.43it/s]

 45%|████▍     | 45005/100629 [35:31<38:24, 24.14it/s]

 45%|████▍     | 45008/100629 [35:31<39:56, 23.21it/s]

 45%|████▍     | 45011/100629 [35:31<40:46, 22.73it/s]

 45%|████▍     | 45014/100629 [35:31<39:52, 23.24it/s]

 45%|████▍     | 45017/100629 [35:31<45:58, 20.16it/s]

 45%|████▍     | 45020/100629 [35:31<45:48, 20.23it/s]

 45%|████▍     | 45024/100629 [35:31<38:14, 24.24it/s]

 45%|████▍     | 45027/100629 [35:32<46:56, 19.74it/s]

 45%|████▍     | 45030/100629 [35:32<46:49, 19.79it/s]

 45%|████▍     | 45033/100629 [35:32<47:48, 19.38it/s]

 45%|████▍     | 45036/100629 [35:32<46:46, 19.81it/s]

 45%|████▍     | 45039/100629 [35:32<47:03, 19.69it/s]

 45%|████▍     | 45042/100629 [35:32<43:02, 21.53it/s]

 45%|████▍     | 45045/100629 [35:33<41:58, 22.07it/s]

 45%|████▍     | 45048/100629 [35:33<49:55, 18.55it/s]

 45%|████▍     | 45051/100629 [35:33<47:44, 19.40it/s]

 45%|████▍     | 45055/100629 [35:33<42:07, 21.99it/s]

 45%|████▍     | 45058/100629 [35:33<43:20, 21.37it/s]

 45%|████▍     | 45061/100629 [35:33<43:23, 21.34it/s]

 45%|████▍     | 45065/100629 [35:33<37:35, 24.64it/s]

 45%|████▍     | 45069/100629 [35:34<33:16, 27.83it/s]

 45%|████▍     | 45074/100629 [35:34<30:22, 30.49it/s]

 45%|████▍     | 45078/100629 [35:34<35:31, 26.06it/s]

 45%|████▍     | 45081/100629 [35:34<35:05, 26.38it/s]

 45%|████▍     | 45085/100629 [35:34<33:55, 27.28it/s]

 45%|████▍     | 45088/100629 [35:34<36:30, 25.36it/s]

 45%|████▍     | 45092/100629 [35:34<35:45, 25.89it/s]

 45%|████▍     | 45095/100629 [35:35<42:56, 21.55it/s]

 45%|████▍     | 45098/100629 [35:35<52:02, 17.79it/s]

 45%|████▍     | 45100/100629 [35:35<51:49, 17.86it/s]

 45%|████▍     | 45102/100629 [35:35<54:37, 16.94it/s]

 45%|████▍     | 45106/100629 [35:35<44:08, 20.96it/s]

 45%|████▍     | 45110/100629 [35:35<37:18, 24.81it/s]

 45%|████▍     | 45113/100629 [35:36<42:13, 21.92it/s]

 45%|████▍     | 45116/100629 [35:36<48:47, 18.96it/s]

 45%|████▍     | 45120/100629 [35:36<43:45, 21.15it/s]

 45%|████▍     | 45123/100629 [35:36<40:28, 22.86it/s]

 45%|████▍     | 45126/100629 [35:36<39:31, 23.41it/s]

 45%|████▍     | 45129/100629 [35:36<40:25, 22.88it/s]

 45%|████▍     | 45133/100629 [35:36<35:27, 26.08it/s]

 45%|████▍     | 45136/100629 [35:37<36:48, 25.13it/s]

 45%|████▍     | 45139/100629 [35:37<41:02, 22.53it/s]

 45%|████▍     | 45142/100629 [35:37<45:15, 20.43it/s]

 45%|████▍     | 45146/100629 [35:37<39:08, 23.63it/s]

 45%|████▍     | 45150/100629 [35:37<33:50, 27.32it/s]

 45%|████▍     | 45153/100629 [35:37<34:10, 27.06it/s]

 45%|████▍     | 45156/100629 [35:37<37:54, 24.39it/s]

 45%|████▍     | 45159/100629 [35:38<39:06, 23.64it/s]

 45%|████▍     | 45162/100629 [35:38<43:26, 21.28it/s]

 45%|████▍     | 45166/100629 [35:38<39:48, 23.22it/s]

 45%|████▍     | 45169/100629 [35:38<40:48, 22.65it/s]

 45%|████▍     | 45172/100629 [35:38<40:44, 22.69it/s]

 45%|████▍     | 45175/100629 [35:38<38:23, 24.07it/s]

 45%|████▍     | 45179/100629 [35:38<34:09, 27.06it/s]

 45%|████▍     | 45182/100629 [35:38<36:58, 24.99it/s]

 45%|████▍     | 45185/100629 [35:39<40:06, 23.04it/s]

 45%|████▍     | 45188/100629 [35:39<41:28, 22.28it/s]

 45%|████▍     | 45191/100629 [35:39<39:44, 23.25it/s]

 45%|████▍     | 45194/100629 [35:39<39:20, 23.48it/s]

 45%|████▍     | 45198/100629 [35:39<36:47, 25.11it/s]

 45%|████▍     | 45201/100629 [35:39<41:56, 22.02it/s]

 45%|████▍     | 45205/100629 [35:39<39:06, 23.62it/s]

 45%|████▍     | 45208/100629 [35:40<41:21, 22.33it/s]

 45%|████▍     | 45211/100629 [35:40<39:29, 23.39it/s]

 45%|████▍     | 45214/100629 [35:40<38:20, 24.09it/s]

 45%|████▍     | 45217/100629 [35:40<59:21, 15.56it/s]

 45%|████▍     | 45220/100629 [35:40<53:43, 17.19it/s]

 45%|████▍     | 45224/100629 [35:41<47:22, 19.49it/s]

 45%|████▍     | 45227/100629 [35:41<46:57, 19.66it/s]

 45%|████▍     | 45230/100629 [35:41<45:20, 20.36it/s]

 45%|████▍     | 45233/100629 [35:41<49:57, 18.48it/s]

 45%|████▍     | 45235/100629 [35:41<53:38, 17.21it/s]

 45%|████▍     | 45238/100629 [35:41<52:57, 17.43it/s]

 45%|████▍     | 45242/100629 [35:41<44:27, 20.76it/s]

 45%|████▍     | 45245/100629 [35:42<42:55, 21.50it/s]

 45%|████▍     | 45248/100629 [35:42<41:33, 22.21it/s]

 45%|████▍     | 45251/100629 [35:42<43:25, 21.25it/s]

 45%|████▍     | 45254/100629 [35:42<44:08, 20.91it/s]

 45%|████▍     | 45257/100629 [35:42<46:43, 19.75it/s]

 45%|████▍     | 45261/100629 [35:42<42:35, 21.66it/s]

 45%|████▍     | 45264/100629 [35:42<39:37, 23.28it/s]

 45%|████▍     | 45268/100629 [35:43<37:00, 24.93it/s]

 45%|████▍     | 45271/100629 [35:43<47:03, 19.60it/s]

 45%|████▍     | 45275/100629 [35:43<42:17, 21.81it/s]

 45%|████▍     | 45278/100629 [35:43<39:59, 23.06it/s]

 45%|████▍     | 45281/100629 [35:43<45:20, 20.34it/s]

 45%|████▌     | 45284/100629 [35:43<44:40, 20.65it/s]

 45%|████▌     | 45287/100629 [35:44<42:53, 21.51it/s]

 45%|████▌     | 45290/100629 [35:44<45:27, 20.29it/s]

 45%|████▌     | 45293/100629 [35:44<43:10, 21.36it/s]

 45%|████▌     | 45296/100629 [35:44<41:29, 22.22it/s]

 45%|████▌     | 45299/100629 [35:44<41:47, 22.07it/s]

 45%|████▌     | 45302/100629 [35:44<40:34, 22.73it/s]

 45%|████▌     | 45305/100629 [35:45<1:07:11, 13.72it/s]

 45%|████▌     | 45307/100629 [35:45<1:08:53, 13.38it/s]

 45%|████▌     | 45310/100629 [35:45<1:00:39, 15.20it/s]

 45%|████▌     | 45313/100629 [35:45<55:38, 16.57it/s]

 45%|████▌     | 45318/100629 [35:45<42:11, 21.85it/s]

 45%|████▌     | 45321/100629 [35:45<41:59, 21.95it/s]

 45%|████▌     | 45324/100629 [35:45<41:07, 22.41it/s]

 45%|████▌     | 45327/100629 [35:46<41:04, 22.44it/s]

 45%|████▌     | 45330/100629 [35:46<39:02, 23.61it/s]

 45%|████▌     | 45333/100629 [35:46<40:42, 22.64it/s]

 45%|████▌     | 45337/100629 [35:46<38:33, 23.89it/s]

 45%|████▌     | 45340/100629 [35:46<44:02, 20.93it/s]

 45%|████▌     | 45343/100629 [35:46<40:58, 22.49it/s]

 45%|████▌     | 45346/100629 [35:46<39:01, 23.61it/s]

 45%|████▌     | 45349/100629 [35:47<43:32, 21.16it/s]

 45%|████▌     | 45352/100629 [35:47<51:43, 17.81it/s]

 45%|████▌     | 45355/100629 [35:47<46:22, 19.87it/s]

 45%|████▌     | 45358/100629 [35:47<44:19, 20.78it/s]

 45%|████▌     | 45361/100629 [35:47<45:13, 20.37it/s]

 45%|████▌     | 45364/100629 [35:47<40:57, 22.49it/s]

 45%|████▌     | 45367/100629 [35:47<39:40, 23.21it/s]

 45%|████▌     | 45373/100629 [35:48<29:15, 31.48it/s]

 45%|████▌     | 45377/100629 [35:48<32:53, 28.00it/s]

 45%|████▌     | 45380/100629 [35:48<33:45, 27.27it/s]

 45%|████▌     | 45383/100629 [35:48<34:30, 26.69it/s]

 45%|████▌     | 45386/100629 [35:48<39:16, 23.44it/s]

 45%|████▌     | 45389/100629 [35:48<37:04, 24.83it/s]

 45%|████▌     | 45392/100629 [35:48<38:26, 23.94it/s]

 45%|████▌     | 45397/100629 [35:49<34:46, 26.47it/s]

 45%|████▌     | 45400/100629 [35:49<34:02, 27.04it/s]

 45%|████▌     | 45403/100629 [35:49<37:43, 24.40it/s]

 45%|████▌     | 45406/100629 [35:49<40:30, 22.72it/s]

 45%|████▌     | 45409/100629 [35:49<45:53, 20.05it/s]

 45%|████▌     | 45412/100629 [35:49<47:36, 19.33it/s]

 45%|████▌     | 45414/100629 [35:49<52:29, 17.53it/s]

 45%|████▌     | 45417/100629 [35:50<48:33, 18.95it/s]

 45%|████▌     | 45420/100629 [35:50<46:11, 19.92it/s]

 45%|████▌     | 45423/100629 [35:50<52:10, 17.63it/s]

 45%|████▌     | 45426/100629 [35:50<50:36, 18.18it/s]

 45%|████▌     | 45428/100629 [35:50<51:34, 17.84it/s]

 45%|████▌     | 45430/100629 [35:50<53:05, 17.33it/s]

 45%|████▌     | 45432/100629 [35:50<54:08, 16.99it/s]

 45%|████▌     | 45434/100629 [35:51<56:56, 16.16it/s]

 45%|████▌     | 45437/100629 [35:51<50:03, 18.38it/s]

 45%|████▌     | 45439/100629 [35:51<53:56, 17.05it/s]

 45%|████▌     | 45441/100629 [35:51<53:49, 17.09it/s]

 45%|████▌     | 45443/100629 [35:51<54:33, 16.86it/s]

 45%|████▌     | 45446/100629 [35:51<45:47, 20.08it/s]

 45%|████▌     | 45449/100629 [35:51<42:00, 21.90it/s]

 45%|████▌     | 45452/100629 [35:51<41:06, 22.37it/s]

 45%|████▌     | 45455/100629 [35:52<38:14, 24.04it/s]

 45%|████▌     | 45458/100629 [35:52<37:37, 24.44it/s]

 45%|████▌     | 45462/100629 [35:52<37:46, 24.35it/s]

 45%|████▌     | 45465/100629 [35:52<38:55, 23.62it/s]

 45%|████▌     | 45468/100629 [35:52<40:57, 22.44it/s]

 45%|████▌     | 45471/100629 [35:52<42:51, 21.45it/s]

 45%|████▌     | 45474/100629 [35:52<41:37, 22.08it/s]

 45%|████▌     | 45477/100629 [35:53<42:31, 21.62it/s]

 45%|████▌     | 45480/100629 [35:53<45:13, 20.32it/s]

 45%|████▌     | 45483/100629 [35:53<43:46, 20.99it/s]

 45%|████▌     | 45487/100629 [35:53<38:49, 23.67it/s]

 45%|████▌     | 45490/100629 [35:53<48:07, 19.10it/s]

 45%|████▌     | 45493/100629 [35:53<43:29, 21.13it/s]

 45%|████▌     | 45496/100629 [35:53<42:03, 21.85it/s]

 45%|████▌     | 45499/100629 [35:54<42:04, 21.84it/s]

 45%|████▌     | 45502/100629 [35:54<43:26, 21.15it/s]

 45%|████▌     | 45505/100629 [35:54<39:44, 23.12it/s]

 45%|████▌     | 45509/100629 [35:54<37:25, 24.55it/s]

 45%|████▌     | 45512/100629 [35:54<41:16, 22.25it/s]

 45%|████▌     | 45515/100629 [35:54<41:34, 22.09it/s]

 45%|████▌     | 45518/100629 [35:54<38:38, 23.77it/s]

 45%|████▌     | 45523/100629 [35:55<37:01, 24.80it/s]

 45%|████▌     | 45526/100629 [35:55<48:23, 18.98it/s]

 45%|████▌     | 45529/100629 [35:55<46:59, 19.54it/s]

 45%|████▌     | 45532/100629 [35:55<46:23, 19.80it/s]

 45%|████▌     | 45535/100629 [35:55<42:46, 21.47it/s]

 45%|████▌     | 45540/100629 [35:55<39:39, 23.15it/s]

 45%|████▌     | 45543/100629 [35:56<38:55, 23.58it/s]

 45%|████▌     | 45547/100629 [35:56<37:24, 24.54it/s]

 45%|████▌     | 45550/100629 [35:56<42:05, 21.81it/s]

 45%|████▌     | 45553/100629 [35:56<41:56, 21.89it/s]

 45%|████▌     | 45558/100629 [35:56<39:26, 23.27it/s]

 45%|████▌     | 45561/100629 [35:56<38:07, 24.08it/s]

 45%|████▌     | 45565/100629 [35:56<36:46, 24.95it/s]

 45%|████▌     | 45568/100629 [35:57<44:22, 20.68it/s]

 45%|████▌     | 45571/100629 [35:57<46:42, 19.65it/s]

 45%|████▌     | 45575/100629 [35:57<40:52, 22.45it/s]

 45%|████▌     | 45578/100629 [35:57<44:45, 20.50it/s]

 45%|████▌     | 45581/100629 [35:57<42:10, 21.76it/s]

 45%|████▌     | 45584/100629 [35:57<38:54, 23.58it/s]

 45%|████▌     | 45587/100629 [35:58<38:32, 23.81it/s]

 45%|████▌     | 45591/100629 [35:58<34:19, 26.72it/s]

 45%|████▌     | 45594/100629 [35:58<36:14, 25.31it/s]

 45%|████▌     | 45597/100629 [35:58<36:16, 25.29it/s]

 45%|████▌     | 45601/100629 [35:58<32:36, 28.13it/s]

 45%|████▌     | 45604/100629 [35:58<33:19, 27.52it/s]

 45%|████▌     | 45607/100629 [35:58<35:54, 25.54it/s]

 45%|████▌     | 45610/100629 [35:58<37:50, 24.23it/s]

 45%|████▌     | 45613/100629 [35:58<37:01, 24.76it/s]

 45%|████▌     | 45616/100629 [35:59<37:35, 24.39it/s]

 45%|████▌     | 45620/100629 [35:59<34:47, 26.36it/s]

 45%|████▌     | 45623/100629 [35:59<37:21, 24.54it/s]

 45%|████▌     | 45626/100629 [35:59<42:16, 21.68it/s]

 45%|████▌     | 45629/100629 [35:59<43:58, 20.84it/s]

 45%|████▌     | 45632/100629 [35:59<42:40, 21.48it/s]

 45%|████▌     | 45635/100629 [35:59<39:11, 23.39it/s]

 45%|████▌     | 45638/100629 [36:00<43:29, 21.07it/s]

 45%|████▌     | 45641/100629 [36:00<41:08, 22.27it/s]

 45%|████▌     | 45644/100629 [36:00<40:30, 22.62it/s]

 45%|████▌     | 45647/100629 [36:00<39:59, 22.91it/s]

 45%|████▌     | 45650/100629 [36:00<44:56, 20.39it/s]

 45%|████▌     | 45654/100629 [36:00<41:09, 22.26it/s]

 45%|████▌     | 45657/100629 [36:01<46:28, 19.72it/s]

 45%|████▌     | 45661/100629 [36:01<44:22, 20.64it/s]

 45%|████▌     | 45664/100629 [36:01<42:51, 21.37it/s]

 45%|████▌     | 45668/100629 [36:01<38:02, 24.08it/s]

 45%|████▌     | 45671/100629 [36:01<36:29, 25.10it/s]

 45%|████▌     | 45674/100629 [36:01<40:04, 22.85it/s]

 45%|████▌     | 45677/100629 [36:01<40:08, 22.82it/s]

 45%|████▌     | 45680/100629 [36:01<39:54, 22.95it/s]

 45%|████▌     | 45683/100629 [36:02<49:28, 18.51it/s]

 45%|████▌     | 45686/100629 [36:02<47:15, 19.37it/s]

 45%|████▌     | 45689/100629 [36:02<42:28, 21.56it/s]

 45%|████▌     | 45692/100629 [36:02<46:40, 19.62it/s]

 45%|████▌     | 45695/100629 [36:02<44:09, 20.73it/s]

 45%|████▌     | 45698/100629 [36:02<41:53, 21.85it/s]

 45%|████▌     | 45701/100629 [36:03<41:05, 22.28it/s]

 45%|████▌     | 45705/100629 [36:03<34:59, 26.16it/s]

 45%|████▌     | 45709/100629 [36:03<31:10, 29.36it/s]

 45%|████▌     | 45713/100629 [36:03<35:08, 26.04it/s]

 45%|████▌     | 45716/100629 [36:03<42:02, 21.77it/s]

 45%|████▌     | 45719/100629 [36:04<1:05:05, 14.06it/s]

 45%|████▌     | 45724/100629 [36:04<48:07, 19.01it/s]

 45%|████▌     | 45727/100629 [36:04<55:20, 16.53it/s]

 45%|████▌     | 45730/100629 [36:04<53:31, 17.09it/s]

 45%|████▌     | 45733/100629 [36:04<53:52, 16.98it/s]

 45%|████▌     | 45736/100629 [36:04<48:22, 18.91it/s]

 45%|████▌     | 45739/100629 [36:05<51:20, 17.82it/s]

 45%|████▌     | 45741/100629 [36:05<50:25, 18.14it/s]

 45%|████▌     | 45744/100629 [36:05<49:09, 18.61it/s]

 45%|████▌     | 45747/100629 [36:05<44:37, 20.49it/s]

 45%|████▌     | 45750/100629 [36:05<42:58, 21.28it/s]

 45%|████▌     | 45753/100629 [36:05<40:57, 22.33it/s]

 45%|████▌     | 45756/100629 [36:05<39:39, 23.06it/s]

 45%|████▌     | 45761/100629 [36:05<34:01, 26.87it/s]

 45%|████▌     | 45764/100629 [36:06<45:44, 19.99it/s]

 45%|████▌     | 45767/100629 [36:06<41:58, 21.79it/s]

 45%|████▌     | 45770/100629 [36:06<52:03, 17.57it/s]

 45%|████▌     | 45773/100629 [36:06<48:42, 18.77it/s]

 45%|████▌     | 45776/100629 [36:06<51:09, 17.87it/s]

 45%|████▌     | 45778/100629 [36:07<55:49, 16.38it/s]

 45%|████▌     | 45780/100629 [36:07<58:37, 15.59it/s]

 45%|████▌     | 45783/100629 [36:07<53:06, 17.21it/s]

 45%|████▌     | 45786/100629 [36:07<50:18, 18.17it/s]

 46%|████▌     | 45788/100629 [36:07<51:31, 17.74it/s]

 46%|████▌     | 45790/100629 [36:07<50:12, 18.20it/s]

 46%|████▌     | 45792/100629 [36:07<57:00, 16.03it/s]

 46%|████▌     | 45795/100629 [36:08<51:43, 17.67it/s]

 46%|████▌     | 45797/100629 [36:08<51:28, 17.76it/s]

 46%|████▌     | 45800/100629 [36:08<48:27, 18.86it/s]

 46%|████▌     | 45803/100629 [36:08<45:35, 20.04it/s]

 46%|████▌     | 45806/100629 [36:08<45:30, 20.07it/s]

 46%|████▌     | 45809/100629 [36:08<44:44, 20.42it/s]

 46%|████▌     | 45812/100629 [36:08<47:30, 19.23it/s]

 46%|████▌     | 45814/100629 [36:08<49:15, 18.55it/s]

 46%|████▌     | 45816/100629 [36:09<49:35, 18.42it/s]

 46%|████▌     | 45819/100629 [36:09<45:48, 19.94it/s]

 46%|████▌     | 45821/100629 [36:09<48:40, 18.77it/s]

 46%|████▌     | 45824/100629 [36:09<45:36, 20.02it/s]

 46%|████▌     | 45827/100629 [36:09<46:23, 19.69it/s]

 46%|████▌     | 45829/100629 [36:09<49:12, 18.56it/s]

 46%|████▌     | 45831/100629 [36:09<51:10, 17.85it/s]

 46%|████▌     | 45836/100629 [36:10<41:18, 22.11it/s]

 46%|████▌     | 45840/100629 [36:10<35:36, 25.65it/s]

 46%|████▌     | 45845/100629 [36:10<32:28, 28.12it/s]

 46%|████▌     | 45848/100629 [36:10<38:10, 23.92it/s]

 46%|████▌     | 45851/100629 [36:10<36:16, 25.17it/s]

 46%|████▌     | 45854/100629 [36:10<38:06, 23.96it/s]

 46%|████▌     | 45857/100629 [36:10<42:42, 21.37it/s]

 46%|████▌     | 45860/100629 [36:11<41:44, 21.86it/s]

 46%|████▌     | 45863/100629 [36:11<48:00, 19.02it/s]

 46%|████▌     | 45866/100629 [36:11<44:53, 20.33it/s]

 46%|████▌     | 45869/100629 [36:11<41:44, 21.87it/s]

 46%|████▌     | 45872/100629 [36:11<41:16, 22.11it/s]

 46%|████▌     | 45875/100629 [36:11<39:33, 23.07it/s]

 46%|████▌     | 45879/100629 [36:11<36:46, 24.81it/s]

 46%|████▌     | 45882/100629 [36:12<40:12, 22.69it/s]

 46%|████▌     | 45885/100629 [36:12<44:54, 20.32it/s]

 46%|████▌     | 45888/100629 [36:12<46:48, 19.49it/s]

 46%|████▌     | 45892/100629 [36:12<38:57, 23.42it/s]

 46%|████▌     | 45895/100629 [36:12<39:10, 23.29it/s]

 46%|████▌     | 45898/100629 [36:12<37:16, 24.47it/s]

 46%|████▌     | 45901/100629 [36:12<41:00, 22.24it/s]

 46%|████▌     | 45904/100629 [36:13<39:00, 23.38it/s]

 46%|████▌     | 45908/100629 [36:13<33:43, 27.04it/s]

 46%|████▌     | 45911/100629 [36:13<35:39, 25.57it/s]

 46%|████▌     | 45914/100629 [36:13<36:10, 25.21it/s]

 46%|████▌     | 45917/100629 [36:13<37:18, 24.45it/s]

 46%|████▌     | 45920/100629 [36:13<42:30, 21.45it/s]

 46%|████▌     | 45923/100629 [36:13<44:12, 20.62it/s]

 46%|████▌     | 45926/100629 [36:14<45:32, 20.02it/s]

 46%|████▌     | 45929/100629 [36:14<47:43, 19.10it/s]

 46%|████▌     | 45932/100629 [36:14<43:01, 21.19it/s]

 46%|████▌     | 45935/100629 [36:14<41:23, 22.03it/s]

 46%|████▌     | 45938/100629 [36:14<46:28, 19.61it/s]

 46%|████▌     | 45943/100629 [36:14<38:23, 23.74it/s]

 46%|████▌     | 45947/100629 [36:14<35:54, 25.39it/s]

 46%|████▌     | 45951/100629 [36:15<34:20, 26.54it/s]

 46%|████▌     | 45954/100629 [36:15<34:26, 26.46it/s]

 46%|████▌     | 45957/100629 [36:15<36:28, 24.98it/s]

 46%|████▌     | 45961/100629 [36:15<34:47, 26.19it/s]

 46%|████▌     | 45964/100629 [36:15<38:51, 23.45it/s]

 46%|████▌     | 45967/100629 [36:15<41:50, 21.78it/s]

 46%|████▌     | 45970/100629 [36:15<46:18, 19.67it/s]

 46%|████▌     | 45973/100629 [36:16<1:06:45, 13.65it/s]

 46%|████▌     | 45976/100629 [36:16<56:35, 16.10it/s]

 46%|████▌     | 45979/100629 [36:16<49:51, 18.27it/s]

 46%|████▌     | 45982/100629 [36:16<53:48, 16.93it/s]

 46%|████▌     | 45984/100629 [36:16<55:09, 16.51it/s]

 46%|████▌     | 45988/100629 [36:16<44:09, 20.62it/s]

 46%|████▌     | 45992/100629 [36:17<37:42, 24.15it/s]

 46%|████▌     | 45995/100629 [36:17<44:30, 20.46it/s]

 46%|████▌     | 45999/100629 [36:17<39:52, 22.83it/s]

 46%|████▌     | 46002/100629 [36:17<37:50, 24.06it/s]

 46%|████▌     | 46005/100629 [36:17<43:47, 20.79it/s]

 46%|████▌     | 46008/100629 [36:17<48:50, 18.64it/s]

 46%|████▌     | 46012/100629 [36:18<40:00, 22.76it/s]

 46%|████▌     | 46015/100629 [36:18<44:25, 20.49it/s]

 46%|████▌     | 46018/100629 [36:18<42:59, 21.17it/s]

 46%|████▌     | 46022/100629 [36:18<38:29, 23.65it/s]

 46%|████▌     | 46026/100629 [36:18<35:53, 25.35it/s]

 46%|████▌     | 46030/100629 [36:18<34:01, 26.75it/s]

 46%|████▌     | 46033/100629 [36:18<33:53, 26.85it/s]

 46%|████▌     | 46036/100629 [36:19<35:17, 25.78it/s]

 46%|████▌     | 46039/100629 [36:19<38:55, 23.38it/s]

 46%|████▌     | 46042/100629 [36:19<36:44, 24.76it/s]

 46%|████▌     | 46046/100629 [36:19<36:36, 24.85it/s]

 46%|████▌     | 46049/100629 [36:19<36:53, 24.66it/s]

 46%|████▌     | 46052/100629 [36:19<36:19, 25.04it/s]

 46%|████▌     | 46055/100629 [36:19<39:10, 23.22it/s]

 46%|████▌     | 46058/100629 [36:19<38:21, 23.72it/s]

 46%|████▌     | 46062/100629 [36:20<36:54, 24.64it/s]

 46%|████▌     | 46065/100629 [36:20<43:09, 21.07it/s]

 46%|████▌     | 46068/100629 [36:20<39:40, 22.92it/s]

 46%|████▌     | 46071/100629 [36:20<38:00, 23.92it/s]

 46%|████▌     | 46076/100629 [36:20<30:01, 30.28it/s]

 46%|████▌     | 46080/100629 [36:20<46:20, 19.62it/s]

 46%|████▌     | 46083/100629 [36:21<45:47, 19.86it/s]

 46%|████▌     | 46086/100629 [36:21<45:09, 20.13it/s]

 46%|████▌     | 46089/100629 [36:21<42:35, 21.34it/s]

 46%|████▌     | 46092/100629 [36:21<39:27, 23.03it/s]

 46%|████▌     | 46097/100629 [36:21<31:17, 29.04it/s]

 46%|████▌     | 46101/100629 [36:21<38:06, 23.85it/s]

 46%|████▌     | 46104/100629 [36:21<37:22, 24.32it/s]

 46%|████▌     | 46108/100629 [36:22<33:33, 27.08it/s]

 46%|████▌     | 46111/100629 [36:22<35:39, 25.48it/s]

 46%|████▌     | 46114/100629 [36:22<38:00, 23.90it/s]

 46%|████▌     | 46117/100629 [36:22<39:53, 22.77it/s]

 46%|████▌     | 46120/100629 [36:22<43:10, 21.04it/s]

 46%|████▌     | 46124/100629 [36:22<36:44, 24.73it/s]

 46%|████▌     | 46128/100629 [36:22<42:32, 21.35it/s]

 46%|████▌     | 46131/100629 [36:23<45:13, 20.08it/s]

 46%|████▌     | 46135/100629 [36:23<38:13, 23.76it/s]

 46%|████▌     | 46138/100629 [36:23<37:40, 24.11it/s]

 46%|████▌     | 46141/100629 [36:23<38:18, 23.70it/s]

 46%|████▌     | 46144/100629 [36:23<52:40, 17.24it/s]

 46%|████▌     | 46148/100629 [36:23<43:21, 20.94it/s]

 46%|████▌     | 46151/100629 [36:24<45:12, 20.08it/s]

 46%|████▌     | 46156/100629 [36:24<37:16, 24.35it/s]

 46%|████▌     | 46159/100629 [36:24<42:37, 21.30it/s]

 46%|████▌     | 46162/100629 [36:24<40:14, 22.56it/s]

 46%|████▌     | 46165/100629 [36:24<37:54, 23.95it/s]

 46%|████▌     | 46168/100629 [36:24<39:04, 23.23it/s]

 46%|████▌     | 46171/100629 [36:25<53:27, 16.98it/s]

 46%|████▌     | 46174/100629 [36:25<47:50, 18.97it/s]

 46%|████▌     | 46177/100629 [36:25<45:32, 19.93it/s]

 46%|████▌     | 46180/100629 [36:25<52:19, 17.34it/s]

 46%|████▌     | 46184/100629 [36:25<42:48, 21.20it/s]

 46%|████▌     | 46187/100629 [36:25<41:59, 21.61it/s]

 46%|████▌     | 46190/100629 [36:25<41:34, 21.83it/s]

 46%|████▌     | 46193/100629 [36:26<40:26, 22.43it/s]

 46%|████▌     | 46196/100629 [36:26<38:53, 23.33it/s]

 46%|████▌     | 46199/100629 [36:26<38:51, 23.34it/s]

 46%|████▌     | 46203/100629 [36:26<33:47, 26.85it/s]

 46%|████▌     | 46206/100629 [36:26<35:29, 25.55it/s]

 46%|████▌     | 46210/100629 [36:26<31:10, 29.10it/s]

 46%|████▌     | 46214/100629 [36:26<29:52, 30.35it/s]

 46%|████▌     | 46218/100629 [36:26<29:47, 30.45it/s]

 46%|████▌     | 46222/100629 [36:27<34:09, 26.54it/s]

 46%|████▌     | 46225/100629 [36:27<33:23, 27.16it/s]

 46%|████▌     | 46228/100629 [36:27<43:06, 21.03it/s]

 46%|████▌     | 46231/100629 [36:27<42:31, 21.32it/s]

 46%|████▌     | 46234/100629 [36:27<43:18, 20.93it/s]

 46%|████▌     | 46237/100629 [36:27<50:39, 17.90it/s]

 46%|████▌     | 46241/100629 [36:28<45:52, 19.76it/s]

 46%|████▌     | 46244/100629 [36:28<47:37, 19.03it/s]

 46%|████▌     | 46246/100629 [36:28<55:02, 16.47it/s]

 46%|████▌     | 46251/100629 [36:28<42:06, 21.52it/s]

 46%|████▌     | 46254/100629 [36:28<50:18, 18.01it/s]

 46%|████▌     | 46258/100629 [36:29<57:33, 15.74it/s]

 46%|████▌     | 46260/100629 [36:29<57:24, 15.78it/s]

 46%|████▌     | 46264/100629 [36:29<52:09, 17.37it/s]

 46%|████▌     | 46266/100629 [36:29<55:10, 16.42it/s]

 46%|████▌     | 46268/100629 [36:29<54:32, 16.61it/s]

 46%|████▌     | 46270/100629 [36:29<56:10, 16.13it/s]

 46%|████▌     | 46273/100629 [36:29<47:16, 19.17it/s]

 46%|████▌     | 46276/100629 [36:30<50:17, 18.01it/s]

 46%|████▌     | 46280/100629 [36:30<40:06, 22.58it/s]

 46%|████▌     | 46283/100629 [36:30<41:17, 21.93it/s]

 46%|████▌     | 46286/100629 [36:30<40:15, 22.49it/s]

 46%|████▌     | 46289/100629 [36:30<48:09, 18.81it/s]

 46%|████▌     | 46292/100629 [36:30<42:51, 21.13it/s]

 46%|████▌     | 46296/100629 [36:30<36:45, 24.64it/s]

 46%|████▌     | 46299/100629 [36:31<41:21, 21.90it/s]

 46%|████▌     | 46302/100629 [36:31<38:19, 23.63it/s]

 46%|████▌     | 46306/100629 [36:31<33:16, 27.22it/s]

 46%|████▌     | 46309/100629 [36:31<36:22, 24.88it/s]

 46%|████▌     | 46312/100629 [36:31<35:31, 25.48it/s]

 46%|████▌     | 46316/100629 [36:31<32:26, 27.91it/s]

 46%|████▌     | 46319/100629 [36:31<36:53, 24.54it/s]

 46%|████▌     | 46322/100629 [36:32<37:04, 24.41it/s]

 46%|████▌     | 46325/100629 [36:32<39:27, 22.94it/s]

 46%|████▌     | 46328/100629 [36:32<37:40, 24.02it/s]

 46%|████▌     | 46331/100629 [36:32<39:58, 22.63it/s]

 46%|████▌     | 46334/100629 [36:32<38:09, 23.71it/s]

 46%|████▌     | 46337/100629 [36:32<43:31, 20.79it/s]

 46%|████▌     | 46340/100629 [36:33<56:02, 16.15it/s]

 46%|████▌     | 46344/100629 [36:33<52:58, 17.08it/s]

 46%|████▌     | 46346/100629 [36:33<51:46, 17.48it/s]

 46%|████▌     | 46349/100629 [36:33<46:53, 19.29it/s]

 46%|████▌     | 46352/100629 [36:33<44:19, 20.41it/s]

 46%|████▌     | 46355/100629 [36:33<51:28, 17.57it/s]

 46%|████▌     | 46357/100629 [36:33<51:19, 17.63it/s]

 46%|████▌     | 46361/100629 [36:34<41:05, 22.01it/s]

 46%|████▌     | 46365/100629 [36:34<39:32, 22.88it/s]

 46%|████▌     | 46369/100629 [36:34<34:48, 25.98it/s]

 46%|████▌     | 46372/100629 [36:34<39:50, 22.70it/s]

 46%|████▌     | 46375/100629 [36:34<39:54, 22.65it/s]

 46%|████▌     | 46379/100629 [36:34<35:27, 25.50it/s]

 46%|████▌     | 46382/100629 [36:34<35:03, 25.79it/s]

 46%|████▌     | 46385/100629 [36:34<33:53, 26.67it/s]

 46%|████▌     | 46388/100629 [36:35<38:19, 23.59it/s]

 46%|████▌     | 46391/100629 [36:35<38:23, 23.54it/s]

 46%|████▌     | 46394/100629 [36:35<37:43, 23.96it/s]

 46%|████▌     | 46397/100629 [36:35<48:33, 18.62it/s]

 46%|████▌     | 46400/100629 [36:35<43:21, 20.85it/s]

 46%|████▌     | 46403/100629 [36:35<46:23, 19.48it/s]

 46%|████▌     | 46406/100629 [36:36<51:24, 17.58it/s]

 46%|████▌     | 46408/100629 [36:36<52:45, 17.13it/s]

 46%|████▌     | 46412/100629 [36:36<41:29, 21.77it/s]

 46%|████▌     | 46415/100629 [36:36<40:19, 22.40it/s]

 46%|████▌     | 46418/100629 [36:36<42:44, 21.14it/s]

 46%|████▌     | 46421/100629 [36:36<41:37, 21.70it/s]

 46%|████▌     | 46424/100629 [36:36<42:39, 21.18it/s]

 46%|████▌     | 46427/100629 [36:36<39:46, 22.71it/s]

 46%|████▌     | 46430/100629 [36:37<38:12, 23.64it/s]

 46%|████▌     | 46433/100629 [36:37<41:36, 21.71it/s]

 46%|████▌     | 46437/100629 [36:37<36:10, 24.96it/s]

 46%|████▌     | 46440/100629 [36:37<34:54, 25.88it/s]

 46%|████▌     | 46444/100629 [36:37<32:19, 27.94it/s]

 46%|████▌     | 46447/100629 [36:37<43:37, 20.70it/s]

 46%|████▌     | 46450/100629 [36:38<43:16, 20.87it/s]

 46%|████▌     | 46453/100629 [36:38<43:39, 20.68it/s]

 46%|████▌     | 46458/100629 [36:38<36:28, 24.75it/s]

 46%|████▌     | 46461/100629 [36:38<36:39, 24.63it/s]

 46%|████▌     | 46464/100629 [36:38<45:13, 19.96it/s]

 46%|████▌     | 46467/100629 [36:38<41:35, 21.70it/s]

 46%|████▌     | 46470/100629 [36:38<43:38, 20.68it/s]

 46%|████▌     | 46473/100629 [36:39<42:57, 21.01it/s]

 46%|████▌     | 46476/100629 [36:39<46:49, 19.28it/s]

 46%|████▌     | 46479/100629 [36:39<52:33, 17.17it/s]

 46%|████▌     | 46481/100629 [36:39<51:42, 17.45it/s]

 46%|████▌     | 46483/100629 [36:39<52:59, 17.03it/s]

 46%|████▌     | 46486/100629 [36:39<51:14, 17.61it/s]

 46%|████▌     | 46488/100629 [36:39<50:59, 17.70it/s]

 46%|████▌     | 46490/100629 [36:40<53:30, 16.86it/s]

 46%|████▌     | 46493/100629 [36:40<50:29, 17.87it/s]

 46%|████▌     | 46495/100629 [36:40<55:53, 16.14it/s]

 46%|████▌     | 46498/100629 [36:40<51:11, 17.62it/s]

 46%|████▌     | 46501/100629 [36:40<47:02, 19.18it/s]

 46%|████▌     | 46503/100629 [36:40<52:31, 17.18it/s]

 46%|████▌     | 46507/100629 [36:40<44:58, 20.06it/s]

 46%|████▌     | 46510/100629 [36:41<41:10, 21.91it/s]

 46%|████▌     | 46513/100629 [36:41<41:20, 21.82it/s]

 46%|████▌     | 46517/100629 [36:41<38:57, 23.15it/s]

 46%|████▌     | 46520/100629 [36:41<47:44, 18.89it/s]

 46%|████▌     | 46523/100629 [36:41<48:44, 18.50it/s]

 46%|████▌     | 46525/100629 [36:41<57:33, 15.67it/s]

 46%|████▌     | 46528/100629 [36:42<52:01, 17.33it/s]

 46%|████▌     | 46531/100629 [36:42<45:58, 19.61it/s]

 46%|████▌     | 46535/100629 [36:42<39:57, 22.56it/s]

 46%|████▌     | 46538/100629 [36:42<42:13, 21.35it/s]

 46%|████▋     | 46541/100629 [36:42<45:24, 19.85it/s]

 46%|████▋     | 46544/100629 [36:42<47:54, 18.81it/s]

 46%|████▋     | 46549/100629 [36:42<36:02, 25.01it/s]

 46%|████▋     | 46552/100629 [36:43<42:14, 21.34it/s]

 46%|████▋     | 46555/100629 [36:43<45:15, 19.92it/s]

 46%|████▋     | 46558/100629 [36:43<48:20, 18.64it/s]

 46%|████▋     | 46561/100629 [36:43<46:57, 19.19it/s]

 46%|████▋     | 46566/100629 [36:43<37:00, 24.34it/s]

 46%|████▋     | 46569/100629 [36:43<35:17, 25.53it/s]

 46%|████▋     | 46573/100629 [36:44<36:59, 24.35it/s]

 46%|████▋     | 46576/100629 [36:44<47:01, 19.16it/s]

 46%|████▋     | 46579/100629 [36:44<50:48, 17.73it/s]

 46%|████▋     | 46582/100629 [36:44<46:48, 19.24it/s]

 46%|████▋     | 46586/100629 [36:44<42:46, 21.06it/s]

 46%|████▋     | 46590/100629 [36:44<37:44, 23.87it/s]

 46%|████▋     | 46593/100629 [36:45<44:20, 20.31it/s]

 46%|████▋     | 46597/100629 [36:45<39:09, 23.00it/s]

 46%|████▋     | 46601/100629 [36:45<34:08, 26.38it/s]

 46%|████▋     | 46605/100629 [36:45<35:54, 25.07it/s]

 46%|████▋     | 46608/100629 [36:45<36:18, 24.80it/s]

 46%|████▋     | 46612/100629 [36:45<35:26, 25.40it/s]

 46%|████▋     | 46618/100629 [36:45<29:35, 30.42it/s]

 46%|████▋     | 46622/100629 [36:46<27:38, 32.56it/s]

 46%|████▋     | 46627/100629 [36:46<25:01, 35.98it/s]

 46%|████▋     | 46631/100629 [36:46<32:07, 28.02it/s]

 46%|████▋     | 46635/100629 [36:46<34:19, 26.22it/s]

 46%|████▋     | 46639/100629 [36:46<32:48, 27.43it/s]

 46%|████▋     | 46643/100629 [36:46<31:27, 28.59it/s]

 46%|████▋     | 46647/100629 [36:47<32:36, 27.59it/s]

 46%|████▋     | 46650/100629 [36:47<36:25, 24.70it/s]

 46%|████▋     | 46654/100629 [36:47<33:24, 26.93it/s]

 46%|████▋     | 46658/100629 [36:47<30:52, 29.14it/s]

 46%|████▋     | 46662/100629 [36:47<30:14, 29.74it/s]

 46%|████▋     | 46666/100629 [36:47<33:27, 26.88it/s]

 46%|████▋     | 46669/100629 [36:47<39:03, 23.03it/s]

 46%|████▋     | 46672/100629 [36:48<45:30, 19.76it/s]

 46%|████▋     | 46675/100629 [36:48<45:06, 19.94it/s]

 46%|████▋     | 46679/100629 [36:48<41:07, 21.87it/s]

 46%|████▋     | 46682/100629 [36:48<48:59, 18.35it/s]

 46%|████▋     | 46684/100629 [36:48<49:21, 18.21it/s]

 46%|████▋     | 46686/100629 [36:48<52:39, 17.07it/s]

 46%|████▋     | 46688/100629 [36:49<1:12:09, 12.46it/s]

 46%|████▋     | 46690/100629 [36:49<1:09:47, 12.88it/s]

 46%|████▋     | 46693/100629 [36:49<58:20, 15.41it/s]

 46%|████▋     | 46696/100629 [36:49<49:42, 18.08it/s]

 46%|████▋     | 46699/100629 [36:49<44:45, 20.08it/s]

 46%|████▋     | 46702/100629 [36:49<47:17, 19.00it/s]

 46%|████▋     | 46706/100629 [36:49<39:56, 22.50it/s]

 46%|████▋     | 46709/100629 [36:50<38:05, 23.59it/s]

 46%|████▋     | 46712/100629 [36:50<47:30, 18.91it/s]

 46%|████▋     | 46715/100629 [36:50<43:05, 20.85it/s]

 46%|████▋     | 46718/100629 [36:50<48:01, 18.71it/s]

 46%|████▋     | 46722/100629 [36:50<41:43, 21.53it/s]

 46%|████▋     | 46726/100629 [36:50<35:17, 25.46it/s]

 46%|████▋     | 46731/100629 [36:51<33:28, 26.83it/s]

 46%|████▋     | 46734/100629 [36:51<33:46, 26.60it/s]

 46%|████▋     | 46738/100629 [36:51<34:10, 26.28it/s]

 46%|████▋     | 46741/100629 [36:51<35:37, 25.22it/s]

 46%|████▋     | 46744/100629 [36:51<45:21, 19.80it/s]

 46%|████▋     | 46748/100629 [36:51<38:37, 23.25it/s]

 46%|████▋     | 46751/100629 [36:51<38:24, 23.38it/s]

 46%|████▋     | 46756/100629 [36:52<30:36, 29.34it/s]

 46%|████▋     | 46760/100629 [36:52<32:18, 27.78it/s]

 46%|████▋     | 46764/100629 [36:52<39:00, 23.02it/s]

 46%|████▋     | 46767/100629 [36:52<43:09, 20.80it/s]

 46%|████▋     | 46773/100629 [36:52<34:09, 26.28it/s]

 46%|████▋     | 46776/100629 [36:52<36:55, 24.31it/s]

 46%|████▋     | 46779/100629 [36:53<40:49, 21.98it/s]

 46%|████▋     | 46782/100629 [36:53<38:50, 23.10it/s]

 46%|████▋     | 46785/100629 [36:53<47:37, 18.84it/s]

 46%|████▋     | 46789/100629 [36:53<39:20, 22.81it/s]

 46%|████▋     | 46792/100629 [36:53<48:12, 18.61it/s]

 47%|████▋     | 46795/100629 [36:53<43:52, 20.45it/s]

 47%|████▋     | 46798/100629 [36:54<40:41, 22.04it/s]

 47%|████▋     | 46802/100629 [36:54<39:18, 22.82it/s]

 47%|████▋     | 46805/100629 [36:54<38:25, 23.35it/s]

 47%|████▋     | 46808/100629 [36:54<46:50, 19.15it/s]

 47%|████▋     | 46811/100629 [36:54<46:50, 19.15it/s]

 47%|████▋     | 46814/100629 [36:54<45:59, 19.50it/s]

 47%|████▋     | 46817/100629 [36:55<47:51, 18.74it/s]

 47%|████▋     | 46820/100629 [36:55<46:30, 19.29it/s]

 47%|████▋     | 46824/100629 [36:55<40:27, 22.16it/s]

 47%|████▋     | 46828/100629 [36:55<35:02, 25.59it/s]

 47%|████▋     | 46831/100629 [36:55<35:43, 25.10it/s]

 47%|████▋     | 46834/100629 [36:55<34:43, 25.82it/s]

 47%|████▋     | 46837/100629 [36:55<33:33, 26.71it/s]

 47%|████▋     | 46840/100629 [36:55<32:42, 27.40it/s]

 47%|████▋     | 46843/100629 [36:55<34:42, 25.83it/s]

 47%|████▋     | 46846/100629 [36:56<38:32, 23.26it/s]

 47%|████▋     | 46849/100629 [36:56<36:53, 24.30it/s]

 47%|████▋     | 46852/100629 [36:56<42:50, 20.92it/s]

 47%|████▋     | 46855/100629 [36:56<41:40, 21.50it/s]

 47%|████▋     | 46858/100629 [36:56<39:15, 22.82it/s]

 47%|████▋     | 46861/100629 [36:56<40:36, 22.07it/s]

 47%|████▋     | 46864/100629 [36:56<42:46, 20.95it/s]

 47%|████▋     | 46867/100629 [36:57<39:50, 22.49it/s]

 47%|████▋     | 46870/100629 [36:57<42:40, 21.00it/s]

 47%|████▋     | 46873/100629 [36:57<44:31, 20.12it/s]

 47%|████▋     | 46877/100629 [36:57<39:45, 22.53it/s]

 47%|████▋     | 46880/100629 [36:57<48:28, 18.48it/s]

 47%|████▋     | 46882/100629 [36:57<52:42, 16.99it/s]

 47%|████▋     | 46885/100629 [36:58<51:11, 17.50it/s]

 47%|████▋     | 46887/100629 [36:58<51:13, 17.48it/s]

 47%|████▋     | 46890/100629 [36:58<49:47, 17.99it/s]

 47%|████▋     | 46892/100629 [36:58<49:23, 18.13it/s]

 47%|████▋     | 46895/100629 [36:58<43:26, 20.62it/s]

 47%|████▋     | 46898/100629 [36:58<39:32, 22.64it/s]

 47%|████▋     | 46903/100629 [36:58<35:32, 25.20it/s]

 47%|████▋     | 46908/100629 [36:58<30:13, 29.62it/s]

 47%|████▋     | 46912/100629 [36:59<31:40, 28.27it/s]

 47%|████▋     | 46916/100629 [36:59<29:58, 29.87it/s]

 47%|████▋     | 46921/100629 [36:59<29:46, 30.06it/s]

 47%|████▋     | 46925/100629 [36:59<38:23, 23.31it/s]

 47%|████▋     | 46928/100629 [36:59<37:28, 23.88it/s]

 47%|████▋     | 46931/100629 [36:59<39:41, 22.55it/s]

 47%|████▋     | 46934/100629 [37:00<39:44, 22.52it/s]

 47%|████▋     | 46937/100629 [37:00<37:15, 24.02it/s]

 47%|████▋     | 46940/100629 [37:00<36:57, 24.21it/s]

 47%|████▋     | 46944/100629 [37:00<34:19, 26.07it/s]

 47%|████▋     | 46947/100629 [37:00<35:11, 25.42it/s]

 47%|████▋     | 46950/100629 [37:00<35:53, 24.93it/s]

 47%|████▋     | 46954/100629 [37:00<39:39, 22.56it/s]

 47%|████▋     | 46957/100629 [37:01<41:15, 21.68it/s]

 47%|████▋     | 46960/100629 [37:01<42:19, 21.13it/s]

 47%|████▋     | 46963/100629 [37:01<47:36, 18.79it/s]

 47%|████▋     | 46966/100629 [37:01<43:57, 20.35it/s]

 47%|████▋     | 46969/100629 [37:01<47:07, 18.98it/s]

 47%|████▋     | 46973/100629 [37:01<39:09, 22.84it/s]

 47%|████▋     | 46976/100629 [37:01<41:10, 21.72it/s]

 47%|████▋     | 46979/100629 [37:02<44:30, 20.09it/s]

 47%|████▋     | 46982/100629 [37:02<52:08, 17.15it/s]

 47%|████▋     | 46984/100629 [37:02<51:51, 17.24it/s]

 47%|████▋     | 46987/100629 [37:02<45:56, 19.46it/s]

 47%|████▋     | 46990/100629 [37:02<42:24, 21.08it/s]

 47%|████▋     | 46994/100629 [37:02<37:24, 23.89it/s]

 47%|████▋     | 46997/100629 [37:03<40:20, 22.15it/s]

 47%|████▋     | 47003/100629 [37:03<32:47, 27.26it/s]

 47%|████▋     | 47006/100629 [37:03<35:36, 25.09it/s]

 47%|████▋     | 47011/100629 [37:03<31:12, 28.63it/s]

 47%|████▋     | 47014/100629 [37:03<36:29, 24.49it/s]

 47%|████▋     | 47017/100629 [37:03<43:07, 20.72it/s]

 47%|████▋     | 47020/100629 [37:03<40:56, 21.82it/s]

 47%|████▋     | 47023/100629 [37:04<39:56, 22.37it/s]

 47%|████▋     | 47026/100629 [37:04<42:31, 21.01it/s]

 47%|████▋     | 47029/100629 [37:04<48:53, 18.27it/s]

 47%|████▋     | 47032/100629 [37:04<44:47, 19.95it/s]

 47%|████▋     | 47036/100629 [37:04<40:10, 22.23it/s]

 47%|████▋     | 47039/100629 [37:04<39:21, 22.69it/s]

 47%|████▋     | 47042/100629 [37:05<43:03, 20.74it/s]

 47%|████▋     | 47045/100629 [37:05<46:12, 19.33it/s]

 47%|████▋     | 47050/100629 [37:05<38:29, 23.20it/s]

 47%|████▋     | 47053/100629 [37:05<42:38, 20.94it/s]

 47%|████▋     | 47056/100629 [37:05<40:56, 21.80it/s]

 47%|████▋     | 47060/100629 [37:05<37:08, 24.04it/s]

 47%|████▋     | 47063/100629 [37:06<42:21, 21.08it/s]

 47%|████▋     | 47066/100629 [37:06<43:49, 20.37it/s]

 47%|████▋     | 47069/100629 [37:06<41:53, 21.31it/s]

 47%|████▋     | 47072/100629 [37:06<42:34, 20.96it/s]

 47%|████▋     | 47075/100629 [37:06<41:03, 21.74it/s]

 47%|████▋     | 47079/100629 [37:06<38:08, 23.40it/s]

 47%|████▋     | 47082/100629 [37:06<43:29, 20.52it/s]

 47%|████▋     | 47085/100629 [37:07<49:13, 18.13it/s]

 47%|████▋     | 47089/100629 [37:07<41:16, 21.62it/s]

 47%|████▋     | 47092/100629 [37:07<42:16, 21.11it/s]

 47%|████▋     | 47096/100629 [37:07<43:48, 20.37it/s]

 47%|████▋     | 47099/100629 [37:07<40:36, 21.97it/s]

 47%|████▋     | 47102/100629 [37:07<45:39, 19.54it/s]

 47%|████▋     | 47105/100629 [37:08<46:31, 19.17it/s]

 47%|████▋     | 47109/100629 [37:08<38:10, 23.36it/s]

 47%|████▋     | 47112/100629 [37:08<37:52, 23.55it/s]

 47%|████▋     | 47115/100629 [37:08<42:10, 21.15it/s]

 47%|████▋     | 47118/100629 [37:08<45:43, 19.51it/s]

 47%|████▋     | 47121/100629 [37:08<44:04, 20.24it/s]

 47%|████▋     | 47124/100629 [37:09<53:51, 16.56it/s]

 47%|████▋     | 47126/100629 [37:09<57:53, 15.40it/s]

 47%|████▋     | 47128/100629 [37:09<58:17, 15.30it/s]

 47%|████▋     | 47130/100629 [37:09<1:01:16, 14.55it/s]

 47%|████▋     | 47132/100629 [37:09<1:02:06, 14.36it/s]

 47%|████▋     | 47134/100629 [37:09<57:49, 15.42it/s]

 47%|████▋     | 47136/100629 [37:09<57:34, 15.49it/s]

 47%|████▋     | 47138/100629 [37:10<1:04:19, 13.86it/s]

 47%|████▋     | 47141/100629 [37:10<52:44, 16.90it/s]

 47%|████▋     | 47143/100629 [37:10<59:37, 14.95it/s]

 47%|████▋     | 47147/100629 [37:10<45:00, 19.81it/s]

 47%|████▋     | 47150/100629 [37:10<45:10, 19.73it/s]

 47%|████▋     | 47153/100629 [37:10<46:19, 19.24it/s]

 47%|████▋     | 47156/100629 [37:10<46:31, 19.15it/s]

 47%|████▋     | 47160/100629 [37:11<46:52, 19.01it/s]

 47%|████▋     | 47163/100629 [37:11<47:20, 18.82it/s]

 47%|████▋     | 47167/100629 [37:11<41:50, 21.29it/s]

 47%|████▋     | 47170/100629 [37:11<39:13, 22.71it/s]

 47%|████▋     | 47173/100629 [37:11<38:40, 23.04it/s]

 47%|████▋     | 47176/100629 [37:11<41:42, 21.36it/s]

 47%|████▋     | 47179/100629 [37:12<41:02, 21.71it/s]

 47%|████▋     | 47182/100629 [37:12<41:06, 21.67it/s]

 47%|████▋     | 47185/100629 [37:12<57:16, 15.55it/s]

 47%|████▋     | 47189/100629 [37:12<45:05, 19.75it/s]

 47%|████▋     | 47192/100629 [37:12<44:21, 20.07it/s]

 47%|████▋     | 47195/100629 [37:12<43:31, 20.46it/s]

 47%|████▋     | 47198/100629 [37:13<44:25, 20.04it/s]

 47%|████▋     | 47202/100629 [37:13<39:05, 22.78it/s]

 47%|████▋     | 47205/100629 [37:13<36:45, 24.22it/s]

 47%|████▋     | 47208/100629 [37:13<35:12, 25.29it/s]

 47%|████▋     | 47211/100629 [37:13<35:45, 24.90it/s]

 47%|████▋     | 47215/100629 [37:13<33:11, 26.82it/s]

 47%|████▋     | 47218/100629 [37:13<37:41, 23.62it/s]

 47%|████▋     | 47222/100629 [37:13<35:38, 24.98it/s]

 47%|████▋     | 47225/100629 [37:14<39:04, 22.77it/s]

 47%|████▋     | 47228/100629 [37:14<44:22, 20.06it/s]

 47%|████▋     | 47231/100629 [37:14<40:23, 22.04it/s]

 47%|████▋     | 47234/100629 [37:14<40:04, 22.20it/s]

 47%|████▋     | 47237/100629 [37:14<38:09, 23.32it/s]

 47%|████▋     | 47240/100629 [37:14<37:55, 23.46it/s]

 47%|████▋     | 47243/100629 [37:14<39:36, 22.46it/s]

 47%|████▋     | 47246/100629 [37:15<45:59, 19.35it/s]

 47%|████▋     | 47249/100629 [37:15<54:38, 16.28it/s]

 47%|████▋     | 47251/100629 [37:15<52:28, 16.95it/s]

 47%|████▋     | 47253/100629 [37:15<52:05, 17.08it/s]

 47%|████▋     | 47256/100629 [37:15<45:08, 19.71it/s]

 47%|████▋     | 47259/100629 [37:15<40:06, 22.18it/s]

 47%|████▋     | 47262/100629 [37:15<41:26, 21.47it/s]

 47%|████▋     | 47265/100629 [37:16<47:07, 18.87it/s]

 47%|████▋     | 47268/100629 [37:16<43:57, 20.23it/s]

 47%|████▋     | 47271/100629 [37:16<47:06, 18.88it/s]

 47%|████▋     | 47274/100629 [37:16<43:15, 20.56it/s]

 47%|████▋     | 47277/100629 [37:16<44:32, 19.96it/s]

 47%|████▋     | 47280/100629 [37:16<45:58, 19.34it/s]

 47%|████▋     | 47283/100629 [37:16<41:20, 21.51it/s]

 47%|████▋     | 47287/100629 [37:17<35:54, 24.75it/s]

 47%|████▋     | 47290/100629 [37:17<34:22, 25.87it/s]

 47%|████▋     | 47293/100629 [37:17<36:19, 24.47it/s]

 47%|████▋     | 47296/100629 [37:17<43:05, 20.63it/s]

 47%|████▋     | 47300/100629 [37:17<36:56, 24.06it/s]

 47%|████▋     | 47303/100629 [37:17<36:17, 24.49it/s]

 47%|████▋     | 47306/100629 [37:17<39:57, 22.24it/s]

 47%|████▋     | 47310/100629 [37:18<40:24, 21.99it/s]

 47%|████▋     | 47313/100629 [37:18<40:16, 22.06it/s]

 47%|████▋     | 47316/100629 [37:18<42:04, 21.12it/s]

 47%|████▋     | 47319/100629 [37:18<39:13, 22.65it/s]

 47%|████▋     | 47322/100629 [37:18<40:11, 22.11it/s]

 47%|████▋     | 47326/100629 [37:18<34:32, 25.72it/s]

 47%|████▋     | 47329/100629 [37:19<43:09, 20.58it/s]

 47%|████▋     | 47332/100629 [37:19<43:11, 20.57it/s]

 47%|████▋     | 47335/100629 [37:19<43:54, 20.23it/s]

 47%|████▋     | 47338/100629 [37:19<46:23, 19.14it/s]

 47%|████▋     | 47341/100629 [37:19<54:08, 16.40it/s]

 47%|████▋     | 47344/100629 [37:19<50:55, 17.44it/s]

 47%|████▋     | 47349/100629 [37:20<41:56, 21.17it/s]

 47%|████▋     | 47354/100629 [37:20<34:05, 26.05it/s]

 47%|████▋     | 47357/100629 [37:20<33:50, 26.24it/s]

 47%|████▋     | 47361/100629 [37:20<33:55, 26.17it/s]

 47%|████▋     | 47366/100629 [37:20<35:30, 24.99it/s]

 47%|████▋     | 47371/100629 [37:20<33:21, 26.61it/s]

 47%|████▋     | 47374/100629 [37:20<38:38, 22.97it/s]

 47%|████▋     | 47377/100629 [37:21<38:17, 23.18it/s]

 47%|████▋     | 47380/100629 [37:21<37:35, 23.61it/s]

 47%|████▋     | 47383/100629 [37:21<45:57, 19.31it/s]

 47%|████▋     | 47386/100629 [37:21<45:10, 19.64it/s]

 47%|████▋     | 47389/100629 [37:21<43:42, 20.30it/s]

 47%|████▋     | 47392/100629 [37:21<50:08, 17.69it/s]

 47%|████▋     | 47395/100629 [37:22<44:08, 20.10it/s]

 47%|████▋     | 47398/100629 [37:22<45:32, 19.48it/s]

 47%|████▋     | 47402/100629 [37:22<39:15, 22.59it/s]

 47%|████▋     | 47405/100629 [37:22<36:39, 24.20it/s]

 47%|████▋     | 47408/100629 [37:22<38:46, 22.88it/s]

 47%|████▋     | 47411/100629 [37:22<39:22, 22.53it/s]

 47%|████▋     | 47414/100629 [37:22<43:35, 20.35it/s]

 47%|████▋     | 47417/100629 [37:23<42:03, 21.09it/s]

 47%|████▋     | 47420/100629 [37:23<41:38, 21.30it/s]

 47%|████▋     | 47423/100629 [37:23<41:20, 21.45it/s]

 47%|████▋     | 47427/100629 [37:23<40:33, 21.86it/s]

 47%|████▋     | 47430/100629 [37:23<39:20, 22.54it/s]

 47%|████▋     | 47433/100629 [37:23<42:01, 21.10it/s]

 47%|████▋     | 47436/100629 [37:23<38:30, 23.02it/s]

 47%|████▋     | 47439/100629 [37:24<36:39, 24.18it/s]

 47%|████▋     | 47442/100629 [37:24<37:39, 23.54it/s]

 47%|████▋     | 47445/100629 [37:24<45:59, 19.28it/s]

 47%|████▋     | 47448/100629 [37:24<42:24, 20.90it/s]

 47%|████▋     | 47451/100629 [37:24<41:53, 21.16it/s]

 47%|████▋     | 47454/100629 [37:24<55:41, 15.92it/s]

 47%|████▋     | 47456/100629 [37:25<54:01, 16.41it/s]

 47%|████▋     | 47458/100629 [37:25<52:43, 16.81it/s]

 47%|████▋     | 47462/100629 [37:25<43:38, 20.31it/s]

 47%|████▋     | 47465/100629 [37:25<39:32, 22.41it/s]

 47%|████▋     | 47468/100629 [37:25<37:22, 23.71it/s]

 47%|████▋     | 47471/100629 [37:25<39:23, 22.49it/s]

 47%|████▋     | 47474/100629 [37:25<44:52, 19.74it/s]

 47%|████▋     | 47477/100629 [37:25<40:50, 21.69it/s]

 47%|████▋     | 47480/100629 [37:26<41:34, 21.30it/s]

 47%|████▋     | 47483/100629 [37:26<40:19, 21.97it/s]

 47%|████▋     | 47487/100629 [37:26<34:17, 25.83it/s]

 47%|████▋     | 47490/100629 [37:26<40:47, 21.71it/s]

 47%|████▋     | 47493/100629 [37:26<39:28, 22.43it/s]

 47%|████▋     | 47497/100629 [37:26<35:54, 24.66it/s]

 47%|████▋     | 47500/100629 [37:26<38:29, 23.01it/s]

 47%|████▋     | 47504/100629 [37:27<39:08, 22.62it/s]

 47%|████▋     | 47507/100629 [37:27<40:18, 21.97it/s]

 47%|████▋     | 47510/100629 [37:27<44:49, 19.75it/s]

 47%|████▋     | 47513/100629 [37:27<42:54, 20.63it/s]

 47%|████▋     | 47516/100629 [37:27<44:26, 19.92it/s]

 47%|████▋     | 47519/100629 [37:27<43:40, 20.27it/s]

 47%|████▋     | 47523/100629 [37:28<38:09, 23.19it/s]

 47%|████▋     | 47526/100629 [37:28<40:48, 21.69it/s]

 47%|████▋     | 47529/100629 [37:28<40:18, 21.95it/s]

 47%|████▋     | 47533/100629 [37:28<37:08, 23.83it/s]

 47%|████▋     | 47536/100629 [37:28<44:37, 19.83it/s]

 47%|████▋     | 47540/100629 [37:28<44:36, 19.84it/s]

 47%|████▋     | 47543/100629 [37:29<46:19, 19.10it/s]

 47%|████▋     | 47546/100629 [37:29<42:34, 20.78it/s]

 47%|████▋     | 47549/100629 [37:29<49:38, 17.82it/s]

 47%|████▋     | 47551/100629 [37:29<52:48, 16.75it/s]

 47%|████▋     | 47556/100629 [37:29<42:54, 20.62it/s]

 47%|████▋     | 47559/100629 [37:29<53:26, 16.55it/s]

 47%|████▋     | 47561/100629 [37:30<55:51, 15.83it/s]

 47%|████▋     | 47563/100629 [37:30<55:07, 16.05it/s]

 47%|████▋     | 47566/100629 [37:30<47:27, 18.64it/s]

 47%|████▋     | 47571/100629 [37:30<36:48, 24.03it/s]

 47%|████▋     | 47574/100629 [37:30<42:48, 20.66it/s]

 47%|████▋     | 47577/100629 [37:30<42:29, 20.81it/s]

 47%|████▋     | 47582/100629 [37:30<35:43, 24.75it/s]

 47%|████▋     | 47585/100629 [37:31<41:23, 21.35it/s]

 47%|████▋     | 47589/100629 [37:31<38:37, 22.89it/s]

 47%|████▋     | 47592/100629 [37:31<42:24, 20.84it/s]

 47%|████▋     | 47595/100629 [37:31<39:23, 22.44it/s]

 47%|████▋     | 47598/100629 [37:31<46:42, 18.93it/s]

 47%|████▋     | 47601/100629 [37:31<41:58, 21.05it/s]

 47%|████▋     | 47604/100629 [37:32<46:18, 19.08it/s]

 47%|████▋     | 47607/100629 [37:32<42:37, 20.73it/s]

 47%|████▋     | 47611/100629 [37:32<35:32, 24.86it/s]

 47%|████▋     | 47614/100629 [37:32<34:33, 25.57it/s]

 47%|████▋     | 47617/100629 [37:32<34:19, 25.74it/s]

 47%|████▋     | 47620/100629 [37:32<36:47, 24.01it/s]

 47%|████▋     | 47623/100629 [37:32<34:51, 25.34it/s]

 47%|████▋     | 47626/100629 [37:32<40:03, 22.05it/s]

 47%|████▋     | 47629/100629 [37:33<40:06, 22.02it/s]

 47%|████▋     | 47633/100629 [37:33<35:31, 24.86it/s]

 47%|████▋     | 47636/100629 [37:33<42:49, 20.63it/s]

 47%|████▋     | 47639/100629 [37:33<41:28, 21.30it/s]

 47%|████▋     | 47644/100629 [37:33<37:03, 23.83it/s]

 47%|████▋     | 47647/100629 [37:33<37:14, 23.71it/s]

 47%|████▋     | 47651/100629 [37:34<34:00, 25.96it/s]

 47%|████▋     | 47654/100629 [37:34<37:33, 23.51it/s]

 47%|████▋     | 47657/100629 [37:34<38:44, 22.79it/s]

 47%|████▋     | 47661/100629 [37:34<35:29, 24.87it/s]

 47%|████▋     | 47665/100629 [37:34<35:27, 24.89it/s]

 47%|████▋     | 47668/100629 [37:34<40:40, 21.70it/s]

 47%|████▋     | 47671/100629 [37:35<54:08, 16.30it/s]

 47%|████▋     | 47674/100629 [37:35<51:36, 17.10it/s]

 47%|████▋     | 47678/100629 [37:35<47:45, 18.48it/s]

 47%|████▋     | 47683/100629 [37:35<37:21, 23.62it/s]

 47%|████▋     | 47686/100629 [37:35<35:44, 24.68it/s]

 47%|████▋     | 47689/100629 [37:35<35:25, 24.91it/s]

 47%|████▋     | 47692/100629 [37:35<37:32, 23.51it/s]

 47%|████▋     | 47695/100629 [37:36<40:35, 21.73it/s]

 47%|████▋     | 47698/100629 [37:36<44:00, 20.05it/s]

 47%|████▋     | 47701/100629 [37:36<40:03, 22.02it/s]

 47%|████▋     | 47704/100629 [37:36<39:00, 22.61it/s]

 47%|████▋     | 47707/100629 [37:36<44:55, 19.63it/s]

 47%|████▋     | 47710/100629 [37:36<40:30, 21.77it/s]

 47%|████▋     | 47713/100629 [37:36<42:03, 20.97it/s]

 47%|████▋     | 47717/100629 [37:37<36:10, 24.37it/s]

 47%|████▋     | 47720/100629 [37:37<41:25, 21.29it/s]

 47%|████▋     | 47723/100629 [37:37<39:50, 22.13it/s]

 47%|████▋     | 47727/100629 [37:37<35:01, 25.18it/s]

 47%|████▋     | 47730/100629 [37:37<36:57, 23.85it/s]

 47%|████▋     | 47734/100629 [37:37<37:10, 23.72it/s]

 47%|████▋     | 47737/100629 [37:38<45:32, 19.36it/s]

 47%|████▋     | 47740/100629 [37:38<50:01, 17.62it/s]

 47%|████▋     | 47744/100629 [37:38<40:56, 21.53it/s]

 47%|████▋     | 47748/100629 [37:38<40:04, 22.00it/s]

 47%|████▋     | 47751/100629 [37:38<41:36, 21.18it/s]

 47%|████▋     | 47754/100629 [37:38<41:57, 21.00it/s]

 47%|████▋     | 47757/100629 [37:38<41:53, 21.03it/s]

 47%|████▋     | 47760/100629 [37:39<43:47, 20.12it/s]

 47%|████▋     | 47763/100629 [37:39<44:30, 19.80it/s]

 47%|████▋     | 47766/100629 [37:39<41:23, 21.28it/s]

 47%|████▋     | 47769/100629 [37:39<43:15, 20.37it/s]

 47%|████▋     | 47773/100629 [37:39<35:54, 24.53it/s]

 47%|████▋     | 47776/100629 [37:39<34:18, 25.68it/s]

 47%|████▋     | 47780/100629 [37:39<35:25, 24.86it/s]

 47%|████▋     | 47783/100629 [37:40<35:31, 24.79it/s]

 47%|████▋     | 47786/100629 [37:40<36:25, 24.18it/s]

 47%|████▋     | 47789/100629 [37:40<38:53, 22.65it/s]

 47%|████▋     | 47792/100629 [37:40<47:37, 18.49it/s]

 47%|████▋     | 47795/100629 [37:40<44:01, 20.00it/s]

 48%|████▊     | 47800/100629 [37:40<36:34, 24.07it/s]

 48%|████▊     | 47804/100629 [37:41<34:34, 25.46it/s]

 48%|████▊     | 47807/100629 [37:41<35:27, 24.83it/s]

 48%|████▊     | 47810/100629 [37:41<38:49, 22.67it/s]

 48%|████▊     | 47813/100629 [37:41<38:20, 22.96it/s]

 48%|████▊     | 47816/100629 [37:41<36:19, 24.23it/s]

 48%|████▊     | 47819/100629 [37:41<38:49, 22.67it/s]

 48%|████▊     | 47822/100629 [37:41<38:14, 23.01it/s]

 48%|████▊     | 47825/100629 [37:41<38:26, 22.89it/s]

 48%|████▊     | 47828/100629 [37:42<37:57, 23.18it/s]

 48%|████▊     | 47833/100629 [37:42<31:56, 27.55it/s]

 48%|████▊     | 47836/100629 [37:42<32:36, 26.98it/s]

 48%|████▊     | 47839/100629 [37:42<32:51, 26.77it/s]

 48%|████▊     | 47842/100629 [37:42<38:17, 22.98it/s]

 48%|████▊     | 47846/100629 [37:42<34:50, 25.24it/s]

 48%|████▊     | 47849/100629 [37:42<42:23, 20.75it/s]

 48%|████▊     | 47852/100629 [37:43<39:40, 22.17it/s]

 48%|████▊     | 47855/100629 [37:43<37:25, 23.51it/s]

 48%|████▊     | 47858/100629 [37:43<37:34, 23.41it/s]

 48%|████▊     | 47861/100629 [37:43<35:39, 24.66it/s]

 48%|████▊     | 47864/100629 [37:43<38:27, 22.86it/s]

 48%|████▊     | 47867/100629 [37:43<39:26, 22.29it/s]

 48%|████▊     | 47870/100629 [37:43<40:57, 21.47it/s]

 48%|████▊     | 47873/100629 [37:43<38:03, 23.10it/s]

 48%|████▊     | 47876/100629 [37:44<46:16, 19.00it/s]

 48%|████▊     | 47879/100629 [37:44<42:59, 20.45it/s]

 48%|████▊     | 47882/100629 [37:44<42:37, 20.63it/s]

 48%|████▊     | 47885/100629 [37:44<45:26, 19.34it/s]

 48%|████▊     | 47888/100629 [37:44<41:04, 21.40it/s]

 48%|████▊     | 47891/100629 [37:45<54:39, 16.08it/s]

 48%|████▊     | 47893/100629 [37:45<1:01:25, 14.31it/s]

 48%|████▊     | 47896/100629 [37:45<57:41, 15.23it/s]

 48%|████▊     | 47898/100629 [37:45<55:48, 15.75it/s]

 48%|████▊     | 47901/100629 [37:45<47:22, 18.55it/s]

 48%|████▊     | 47904/100629 [37:45<46:23, 18.94it/s]

 48%|████▊     | 47907/100629 [37:45<42:12, 20.82it/s]

 48%|████▊     | 47910/100629 [37:46<40:59, 21.43it/s]

 48%|████▊     | 47913/100629 [37:46<39:46, 22.09it/s]

 48%|████▊     | 47916/100629 [37:46<37:52, 23.20it/s]

 48%|████▊     | 47920/100629 [37:46<32:41, 26.87it/s]

 48%|████▊     | 47923/100629 [37:46<42:57, 20.45it/s]

 48%|████▊     | 47926/100629 [37:46<47:52, 18.34it/s]

 48%|████▊     | 47929/100629 [37:46<50:45, 17.31it/s]

 48%|████▊     | 47933/100629 [37:47<41:34, 21.13it/s]

 48%|████▊     | 47936/100629 [37:47<44:08, 19.90it/s]

 48%|████▊     | 47939/100629 [37:47<44:21, 19.80it/s]

 48%|████▊     | 47942/100629 [37:47<46:46, 18.77it/s]

 48%|████▊     | 47944/100629 [37:47<49:01, 17.91it/s]

 48%|████▊     | 47947/100629 [37:47<53:07, 16.53it/s]

 48%|████▊     | 47949/100629 [37:48<51:50, 16.94it/s]

 48%|████▊     | 47951/100629 [37:48<51:35, 17.02it/s]

 48%|████▊     | 47955/100629 [37:48<49:31, 17.73it/s]

 48%|████▊     | 47957/100629 [37:48<1:03:48, 13.76it/s]

 48%|████▊     | 47960/100629 [37:48<56:26, 15.55it/s]

 48%|████▊     | 47962/100629 [37:48<54:37, 16.07it/s]

 48%|████▊     | 47966/100629 [37:49<42:03, 20.86it/s]

 48%|████▊     | 47969/100629 [37:49<43:53, 19.99it/s]

 48%|████▊     | 47972/100629 [37:49<43:33, 20.15it/s]

 48%|████▊     | 47975/100629 [37:49<45:10, 19.42it/s]

 48%|████▊     | 47979/100629 [37:49<37:22, 23.48it/s]

 48%|████▊     | 47983/100629 [37:49<35:10, 24.95it/s]

 48%|████▊     | 47986/100629 [37:49<36:29, 24.04it/s]

 48%|████▊     | 47989/100629 [37:50<41:55, 20.92it/s]

 48%|████▊     | 47992/100629 [37:50<47:06, 18.62it/s]

 48%|████▊     | 47995/100629 [37:50<42:33, 20.61it/s]

 48%|████▊     | 47998/100629 [37:50<39:00, 22.49it/s]

 48%|████▊     | 48001/100629 [37:50<38:16, 22.92it/s]

 48%|████▊     | 48005/100629 [37:50<36:18, 24.16it/s]

 48%|████▊     | 48008/100629 [37:50<36:48, 23.83it/s]

 48%|████▊     | 48011/100629 [37:51<38:57, 22.51it/s]

 48%|████▊     | 48014/100629 [37:51<42:46, 20.50it/s]

 48%|████▊     | 48017/100629 [37:51<40:15, 21.78it/s]

 48%|████▊     | 48020/100629 [37:51<39:02, 22.46it/s]

 48%|████▊     | 48023/100629 [37:51<58:46, 14.92it/s]

 48%|████▊     | 48025/100629 [37:51<59:02, 14.85it/s]

 48%|████▊     | 48027/100629 [37:52<58:25, 15.01it/s]

 48%|████▊     | 48031/100629 [37:52<45:32, 19.25it/s]

 48%|████▊     | 48035/100629 [37:52<41:17, 21.23it/s]

 48%|████▊     | 48038/100629 [37:52<45:30, 19.26it/s]

 48%|████▊     | 48041/100629 [37:52<50:13, 17.45it/s]

 48%|████▊     | 48043/100629 [37:52<50:57, 17.20it/s]

 48%|████▊     | 48046/100629 [37:53<49:11, 17.82it/s]

 48%|████▊     | 48048/100629 [37:53<48:50, 17.94it/s]

 48%|████▊     | 48051/100629 [37:53<43:59, 19.92it/s]

 48%|████▊     | 48054/100629 [37:53<40:10, 21.81it/s]

 48%|████▊     | 48057/100629 [37:53<40:00, 21.90it/s]

 48%|████▊     | 48060/100629 [37:53<41:35, 21.07it/s]

 48%|████▊     | 48063/100629 [37:53<41:00, 21.36it/s]

 48%|████▊     | 48066/100629 [37:53<38:07, 22.98it/s]

 48%|████▊     | 48069/100629 [37:54<40:36, 21.57it/s]

 48%|████▊     | 48072/100629 [37:54<39:35, 22.13it/s]

 48%|████▊     | 48075/100629 [37:54<38:44, 22.61it/s]

 48%|████▊     | 48079/100629 [37:54<33:13, 26.36it/s]

 48%|████▊     | 48083/100629 [37:54<30:04, 29.12it/s]

 48%|████▊     | 48086/100629 [37:54<31:24, 27.88it/s]

 48%|████▊     | 48091/100629 [37:54<28:27, 30.76it/s]

 48%|████▊     | 48095/100629 [37:54<26:51, 32.59it/s]

 48%|████▊     | 48099/100629 [37:55<34:09, 25.63it/s]

 48%|████▊     | 48102/100629 [37:55<39:08, 22.37it/s]

 48%|████▊     | 48105/100629 [37:55<40:14, 21.75it/s]

 48%|████▊     | 48109/100629 [37:55<36:00, 24.31it/s]

 48%|████▊     | 48112/100629 [37:55<40:36, 21.55it/s]

 48%|████▊     | 48117/100629 [37:55<34:40, 25.24it/s]

 48%|████▊     | 48120/100629 [37:56<42:03, 20.81it/s]

 48%|████▊     | 48123/100629 [37:56<45:41, 19.15it/s]

 48%|████▊     | 48126/100629 [37:56<43:43, 20.01it/s]

 48%|████▊     | 48131/100629 [37:56<33:56, 25.78it/s]

 48%|████▊     | 48134/100629 [37:56<34:01, 25.71it/s]

 48%|████▊     | 48137/100629 [37:56<43:53, 19.93it/s]

 48%|████▊     | 48140/100629 [37:57<43:05, 20.30it/s]

 48%|████▊     | 48144/100629 [37:57<37:01, 23.63it/s]

 48%|████▊     | 48147/100629 [37:57<46:36, 18.77it/s]

 48%|████▊     | 48150/100629 [37:57<44:19, 19.73it/s]

 48%|████▊     | 48153/100629 [37:57<42:07, 20.76it/s]

 48%|████▊     | 48158/100629 [37:57<32:43, 26.73it/s]

 48%|████▊     | 48161/100629 [37:58<38:51, 22.50it/s]

 48%|████▊     | 48165/100629 [37:58<35:03, 24.94it/s]

 48%|████▊     | 48168/100629 [37:58<36:17, 24.10it/s]

 48%|████▊     | 48172/100629 [37:58<32:45, 26.68it/s]

 48%|████▊     | 48176/100629 [37:58<32:17, 27.08it/s]

 48%|████▊     | 48181/100629 [37:58<29:31, 29.61it/s]

 48%|████▊     | 48185/100629 [37:58<34:37, 25.25it/s]

 48%|████▊     | 48188/100629 [37:59<37:39, 23.21it/s]

 48%|████▊     | 48191/100629 [37:59<40:10, 21.75it/s]

 48%|████▊     | 48194/100629 [37:59<41:24, 21.11it/s]

 48%|████▊     | 48197/100629 [37:59<40:09, 21.76it/s]

 48%|████▊     | 48200/100629 [37:59<40:37, 21.51it/s]

 48%|████▊     | 48203/100629 [37:59<38:38, 22.62it/s]

 48%|████▊     | 48206/100629 [37:59<41:32, 21.03it/s]

 48%|████▊     | 48209/100629 [38:00<43:28, 20.10it/s]

 48%|████▊     | 48212/100629 [38:00<39:45, 21.97it/s]

 48%|████▊     | 48216/100629 [38:00<37:23, 23.36it/s]

 48%|████▊     | 48219/100629 [38:00<39:23, 22.18it/s]

 48%|████▊     | 48223/100629 [38:00<34:39, 25.21it/s]

 48%|████▊     | 48226/100629 [38:00<39:08, 22.32it/s]

 48%|████▊     | 48229/100629 [38:00<38:56, 22.42it/s]

 48%|████▊     | 48232/100629 [38:01<36:50, 23.70it/s]

 48%|████▊     | 48235/100629 [38:01<38:01, 22.96it/s]

 48%|████▊     | 48238/100629 [38:01<37:45, 23.12it/s]

 48%|████▊     | 48241/100629 [38:01<37:59, 22.98it/s]

 48%|████▊     | 48244/100629 [38:01<35:46, 24.40it/s]

 48%|████▊     | 48248/100629 [38:01<31:04, 28.10it/s]

 48%|████▊     | 48252/100629 [38:01<28:02, 31.13it/s]

 48%|████▊     | 48256/100629 [38:01<28:25, 30.70it/s]

 48%|████▊     | 48260/100629 [38:02<32:21, 26.97it/s]

 48%|████▊     | 48263/100629 [38:02<34:08, 25.57it/s]

 48%|████▊     | 48266/100629 [38:02<33:04, 26.39it/s]

 48%|████▊     | 48269/100629 [38:02<36:18, 24.04it/s]

 48%|████▊     | 48272/100629 [38:02<43:13, 20.19it/s]

 48%|████▊     | 48275/100629 [38:02<40:23, 21.60it/s]

 48%|████▊     | 48278/100629 [38:02<42:59, 20.30it/s]

 48%|████▊     | 48283/100629 [38:03<38:32, 22.64it/s]

 48%|████▊     | 48286/100629 [38:03<42:13, 20.66it/s]

 48%|████▊     | 48289/100629 [38:03<42:54, 20.33it/s]

 48%|████▊     | 48292/100629 [38:03<39:41, 21.98it/s]

 48%|████▊     | 48296/100629 [38:03<36:11, 24.10it/s]

 48%|████▊     | 48300/100629 [38:03<32:08, 27.13it/s]

 48%|████▊     | 48304/100629 [38:03<30:30, 28.58it/s]

 48%|████▊     | 48307/100629 [38:04<30:11, 28.89it/s]

 48%|████▊     | 48310/100629 [38:04<31:39, 27.54it/s]

 48%|████▊     | 48315/100629 [38:04<26:12, 33.27it/s]

 48%|████▊     | 48319/100629 [38:04<35:44, 24.39it/s]

 48%|████▊     | 48323/100629 [38:04<33:14, 26.22it/s]

 48%|████▊     | 48327/100629 [38:04<32:21, 26.94it/s]

 48%|████▊     | 48330/100629 [38:04<34:16, 25.43it/s]

 48%|████▊     | 48333/100629 [38:05<39:46, 21.92it/s]

 48%|████▊     | 48336/100629 [38:05<56:20, 15.47it/s]

 48%|████▊     | 48339/100629 [38:05<49:45, 17.51it/s]

 48%|████▊     | 48342/100629 [38:05<51:07, 17.04it/s]

 48%|████▊     | 48344/100629 [38:05<51:07, 17.05it/s]

 48%|████▊     | 48348/100629 [38:06<41:29, 21.00it/s]

 48%|████▊     | 48351/100629 [38:06<40:49, 21.35it/s]

 48%|████▊     | 48355/100629 [38:06<40:14, 21.65it/s]

 48%|████▊     | 48358/100629 [38:06<47:21, 18.40it/s]

 48%|████▊     | 48362/100629 [38:06<40:48, 21.35it/s]

 48%|████▊     | 48367/100629 [38:06<35:48, 24.32it/s]

 48%|████▊     | 48370/100629 [38:07<40:03, 21.74it/s]

 48%|████▊     | 48373/100629 [38:07<41:39, 20.91it/s]

 48%|████▊     | 48376/100629 [38:07<41:54, 20.78it/s]

 48%|████▊     | 48379/100629 [38:07<48:19, 18.02it/s]

 48%|████▊     | 48381/100629 [38:07<50:55, 17.10it/s]

 48%|████▊     | 48383/100629 [38:07<52:03, 16.73it/s]

 48%|████▊     | 48386/100629 [38:07<50:18, 17.31it/s]

 48%|████▊     | 48388/100629 [38:08<49:53, 17.45it/s]

 48%|████▊     | 48391/100629 [38:08<47:44, 18.23it/s]

 48%|████▊     | 48395/100629 [38:08<40:47, 21.35it/s]

 48%|████▊     | 48398/100629 [38:08<40:00, 21.76it/s]

 48%|████▊     | 48401/100629 [38:08<43:08, 20.17it/s]

 48%|████▊     | 48404/100629 [38:08<40:13, 21.64it/s]

 48%|████▊     | 48408/100629 [38:08<37:06, 23.46it/s]

 48%|████▊     | 48411/100629 [38:09<39:13, 22.18it/s]

 48%|████▊     | 48414/100629 [38:09<38:39, 22.51it/s]

 48%|████▊     | 48417/100629 [38:09<44:24, 19.60it/s]

 48%|████▊     | 48420/100629 [38:09<40:04, 21.71it/s]

 48%|████▊     | 48423/100629 [38:09<1:00:35, 14.36it/s]

 48%|████▊     | 48425/100629 [38:10<57:21, 15.17it/s]

 48%|████▊     | 48428/100629 [38:10<52:30, 16.57it/s]

 48%|████▊     | 48430/100629 [38:10<55:18, 15.73it/s]

 48%|████▊     | 48433/100629 [38:10<48:53, 17.80it/s]

 48%|████▊     | 48435/100629 [38:10<1:05:35, 13.26it/s]

 48%|████▊     | 48438/100629 [38:10<55:58, 15.54it/s]

 48%|████▊     | 48442/100629 [38:10<44:30, 19.54it/s]

 48%|████▊     | 48445/100629 [38:11<54:10, 16.05it/s]

 48%|████▊     | 48447/100629 [38:11<54:39, 15.91it/s]

 48%|████▊     | 48449/100629 [38:11<1:02:41, 13.87it/s]

 48%|████▊     | 48453/100629 [38:11<48:08, 18.07it/s]

 48%|████▊     | 48456/100629 [38:11<43:32, 19.97it/s]

 48%|████▊     | 48460/100629 [38:11<35:54, 24.22it/s]

 48%|████▊     | 48463/100629 [38:12<34:47, 24.99it/s]

 48%|████▊     | 48466/100629 [38:12<40:04, 21.69it/s]

 48%|████▊     | 48471/100629 [38:12<36:18, 23.95it/s]

 48%|████▊     | 48474/100629 [38:12<35:49, 24.26it/s]

 48%|████▊     | 48477/100629 [38:12<37:48, 22.99it/s]

 48%|████▊     | 48480/100629 [38:12<35:48, 24.27it/s]

 48%|████▊     | 48483/100629 [38:12<41:56, 20.72it/s]

 48%|████▊     | 48488/100629 [38:13<34:03, 25.52it/s]

 48%|████▊     | 48491/100629 [38:13<36:31, 23.79it/s]

 48%|████▊     | 48495/100629 [38:13<36:55, 23.53it/s]

 48%|████▊     | 48498/100629 [38:13<40:22, 21.52it/s]

 48%|████▊     | 48501/100629 [38:13<37:31, 23.15it/s]

 48%|████▊     | 48505/100629 [38:13<32:49, 26.46it/s]

 48%|████▊     | 48508/100629 [38:13<32:16, 26.92it/s]

 48%|████▊     | 48511/100629 [38:14<34:25, 25.24it/s]

 48%|████▊     | 48514/100629 [38:14<38:23, 22.63it/s]

 48%|████▊     | 48517/100629 [38:14<39:30, 21.98it/s]

 48%|████▊     | 48520/100629 [38:14<38:15, 22.70it/s]

 48%|████▊     | 48523/100629 [38:14<40:20, 21.53it/s]

 48%|████▊     | 48526/100629 [38:14<41:53, 20.73it/s]

 48%|████▊     | 48529/100629 [38:14<45:02, 19.28it/s]

 48%|████▊     | 48532/100629 [38:15<44:27, 19.53it/s]

 48%|████▊     | 48537/100629 [38:15<35:25, 24.51it/s]

 48%|████▊     | 48540/100629 [38:15<38:24, 22.60it/s]

 48%|████▊     | 48543/100629 [38:15<39:04, 22.22it/s]

 48%|████▊     | 48547/100629 [38:15<35:20, 24.56it/s]

 48%|████▊     | 48550/100629 [38:15<34:23, 25.24it/s]

 48%|████▊     | 48554/100629 [38:15<32:50, 26.43it/s]

 48%|████▊     | 48557/100629 [38:16<39:22, 22.04it/s]

 48%|████▊     | 48560/100629 [38:16<46:16, 18.75it/s]

 48%|████▊     | 48563/100629 [38:16<45:22, 19.13it/s]

 48%|████▊     | 48566/100629 [38:16<43:07, 20.12it/s]

 48%|████▊     | 48569/100629 [38:16<43:57, 19.74it/s]

 48%|████▊     | 48572/100629 [38:16<42:22, 20.47it/s]

 48%|████▊     | 48575/100629 [38:17<48:43, 17.81it/s]

 48%|████▊     | 48577/100629 [38:17<51:45, 16.76it/s]

 48%|████▊     | 48579/100629 [38:17<54:00, 16.06it/s]

 48%|████▊     | 48583/100629 [38:17<44:23, 19.54it/s]

 48%|████▊     | 48586/100629 [38:17<43:46, 19.82it/s]

 48%|████▊     | 48589/100629 [38:17<47:13, 18.36it/s]

 48%|████▊     | 48592/100629 [38:17<41:53, 20.70it/s]

 48%|████▊     | 48595/100629 [38:18<40:11, 21.58it/s]

 48%|████▊     | 48598/100629 [38:18<39:03, 22.21it/s]

 48%|████▊     | 48601/100629 [38:18<40:16, 21.53it/s]

 48%|████▊     | 48605/100629 [38:18<33:34, 25.83it/s]

 48%|████▊     | 48610/100629 [38:18<29:28, 29.41it/s]

 48%|████▊     | 48614/100629 [38:18<27:09, 31.93it/s]

 48%|████▊     | 48619/100629 [38:18<26:36, 32.58it/s]

 48%|████▊     | 48623/100629 [38:19<29:02, 29.84it/s]

 48%|████▊     | 48627/100629 [38:19<30:33, 28.36it/s]

 48%|████▊     | 48630/100629 [38:19<30:09, 28.73it/s]

 48%|████▊     | 48633/100629 [38:19<30:10, 28.71it/s]

 48%|████▊     | 48636/100629 [38:19<37:38, 23.02it/s]

 48%|████▊     | 48639/100629 [38:19<43:05, 20.11it/s]

 48%|████▊     | 48642/100629 [38:20<47:06, 18.39it/s]

 48%|████▊     | 48644/100629 [38:20<47:49, 18.12it/s]

 48%|████▊     | 48647/100629 [38:20<42:15, 20.50it/s]

 48%|████▊     | 48650/100629 [38:20<43:00, 20.14it/s]

 48%|████▊     | 48653/100629 [38:20<38:44, 22.36it/s]

 48%|████▊     | 48656/100629 [38:20<36:12, 23.92it/s]

 48%|████▊     | 48659/100629 [38:20<44:49, 19.32it/s]

 48%|████▊     | 48663/100629 [38:20<39:45, 21.78it/s]

 48%|████▊     | 48666/100629 [38:21<1:00:59, 14.20it/s]

 48%|████▊     | 48668/100629 [38:21<1:00:41, 14.27it/s]

 48%|████▊     | 48670/100629 [38:21<57:45, 15.00it/s]

 48%|████▊     | 48673/100629 [38:21<52:40, 16.44it/s]

 48%|████▊     | 48676/100629 [38:21<47:34, 18.20it/s]

 48%|████▊     | 48679/100629 [38:21<43:26, 19.93it/s]

 48%|████▊     | 48682/100629 [38:22<1:00:21, 14.34it/s]

 48%|████▊     | 48685/100629 [38:22<50:54, 17.01it/s]

 48%|████▊     | 48688/100629 [38:22<47:49, 18.10it/s]

 48%|████▊     | 48691/100629 [38:22<51:14, 16.89it/s]

 48%|████▊     | 48694/100629 [38:22<47:38, 18.17it/s]

 48%|████▊     | 48697/100629 [38:23<42:31, 20.36it/s]

 48%|████▊     | 48700/100629 [38:23<44:23, 19.50it/s]

 48%|████▊     | 48704/100629 [38:23<39:29, 21.91it/s]

 48%|████▊     | 48707/100629 [38:23<39:41, 21.80it/s]

 48%|████▊     | 48710/100629 [38:23<41:49, 20.69it/s]

 48%|████▊     | 48713/100629 [38:23<49:31, 17.47it/s]

 48%|████▊     | 48715/100629 [38:23<50:10, 17.25it/s]

 48%|████▊     | 48719/100629 [38:24<41:22, 20.91it/s]

 48%|████▊     | 48722/100629 [38:24<37:58, 22.78it/s]

 48%|████▊     | 48725/100629 [38:24<40:30, 21.35it/s]

 48%|████▊     | 48728/100629 [38:24<38:57, 22.21it/s]

 48%|████▊     | 48731/100629 [38:24<43:19, 19.96it/s]

 48%|████▊     | 48734/100629 [38:24<42:49, 20.19it/s]

 48%|████▊     | 48737/100629 [38:24<40:38, 21.28it/s]

 48%|████▊     | 48740/100629 [38:25<37:45, 22.91it/s]

 48%|████▊     | 48743/100629 [38:25<38:08, 22.67it/s]

 48%|████▊     | 48747/100629 [38:25<32:39, 26.48it/s]

 48%|████▊     | 48750/100629 [38:25<35:09, 24.60it/s]

 48%|████▊     | 48753/100629 [38:25<36:40, 23.57it/s]

 48%|████▊     | 48758/100629 [38:25<30:05, 28.73it/s]

 48%|████▊     | 48761/100629 [38:25<33:17, 25.97it/s]

 48%|████▊     | 48766/100629 [38:25<28:38, 30.18it/s]

 48%|████▊     | 48770/100629 [38:26<35:02, 24.66it/s]

 48%|████▊     | 48774/100629 [38:26<33:02, 26.16it/s]

 48%|████▊     | 48777/100629 [38:26<35:11, 24.56it/s]

 48%|████▊     | 48780/100629 [38:26<42:34, 20.29it/s]

 48%|████▊     | 48783/100629 [38:26<44:30, 19.41it/s]

 48%|████▊     | 48786/100629 [38:27<43:19, 19.94it/s]

 48%|████▊     | 48790/100629 [38:27<38:42, 22.32it/s]

 48%|████▊     | 48793/100629 [38:27<41:12, 20.97it/s]

 48%|████▊     | 48796/100629 [38:27<42:28, 20.34it/s]

 48%|████▊     | 48799/100629 [38:27<39:02, 22.13it/s]

 48%|████▊     | 48802/100629 [38:27<37:46, 22.87it/s]

 48%|████▊     | 48805/100629 [38:27<35:57, 24.02it/s]

 49%|████▊     | 48808/100629 [38:27<37:01, 23.33it/s]

 49%|████▊     | 48811/100629 [38:28<36:45, 23.49it/s]

 49%|████▊     | 48814/100629 [38:28<40:10, 21.49it/s]

 49%|████▊     | 48817/100629 [38:28<56:57, 15.16it/s]

 49%|████▊     | 48820/100629 [38:28<54:11, 15.93it/s]

 49%|████▊     | 48823/100629 [38:28<54:57, 15.71it/s]

 49%|████▊     | 48826/100629 [38:29<48:52, 17.67it/s]

 49%|████▊     | 48830/100629 [38:29<39:39, 21.77it/s]

 49%|████▊     | 48834/100629 [38:29<35:10, 24.54it/s]

 49%|████▊     | 48837/100629 [38:29<34:43, 24.85it/s]

 49%|████▊     | 48840/100629 [38:29<37:04, 23.28it/s]

 49%|████▊     | 48843/100629 [38:29<36:25, 23.70it/s]

 49%|████▊     | 48848/100629 [38:29<36:16, 23.80it/s]

 49%|████▊     | 48852/100629 [38:30<32:24, 26.63it/s]

 49%|████▊     | 48855/100629 [38:30<41:22, 20.86it/s]

 49%|████▊     | 48858/100629 [38:30<49:22, 17.47it/s]

 49%|████▊     | 48860/100629 [38:30<58:25, 14.77it/s]

 49%|████▊     | 48862/100629 [38:30<56:38, 15.23it/s]

 49%|████▊     | 48864/100629 [38:30<57:13, 15.08it/s]

 49%|████▊     | 48866/100629 [38:31<1:01:39, 13.99it/s]

 49%|████▊     | 48869/100629 [38:31<53:48, 16.03it/s]

 49%|████▊     | 48872/100629 [38:31<48:45, 17.69it/s]

 49%|████▊     | 48874/100629 [38:31<49:15, 17.51it/s]

 49%|████▊     | 48876/100629 [38:31<50:33, 17.06it/s]

 49%|████▊     | 48879/100629 [38:31<45:09, 19.10it/s]

 49%|████▊     | 48883/100629 [38:31<36:33, 23.59it/s]

 49%|████▊     | 48886/100629 [38:32<45:09, 19.10it/s]

 49%|████▊     | 48889/100629 [38:32<42:02, 20.51it/s]

 49%|████▊     | 48892/100629 [38:32<38:58, 22.13it/s]

 49%|████▊     | 48895/100629 [38:32<36:02, 23.92it/s]

 49%|████▊     | 48898/100629 [38:32<36:26, 23.66it/s]

 49%|████▊     | 48901/100629 [38:32<34:29, 24.99it/s]

 49%|████▊     | 48904/100629 [38:32<33:39, 25.61it/s]

 49%|████▊     | 48910/100629 [38:32<25:27, 33.86it/s]

 49%|████▊     | 48914/100629 [38:33<28:12, 30.56it/s]

 49%|████▊     | 48918/100629 [38:33<29:11, 29.52it/s]

 49%|████▊     | 48922/100629 [38:33<29:59, 28.74it/s]

 49%|████▊     | 48925/100629 [38:33<33:43, 25.55it/s]

 49%|████▊     | 48928/100629 [38:33<33:10, 25.98it/s]

 49%|████▊     | 48932/100629 [38:33<30:45, 28.02it/s]

 49%|████▊     | 48935/100629 [38:33<32:17, 26.68it/s]

 49%|████▊     | 48938/100629 [38:33<31:59, 26.93it/s]

 49%|████▊     | 48941/100629 [38:34<34:26, 25.01it/s]

 49%|████▊     | 48944/100629 [38:34<34:20, 25.09it/s]

 49%|████▊     | 48947/100629 [38:34<34:29, 24.98it/s]

 49%|████▊     | 48950/100629 [38:34<36:05, 23.86it/s]

 49%|████▊     | 48953/100629 [38:34<34:43, 24.80it/s]

 49%|████▊     | 48956/100629 [38:34<33:06, 26.01it/s]

 49%|████▊     | 48959/100629 [38:34<34:36, 24.89it/s]

 49%|████▊     | 48962/100629 [38:34<35:47, 24.05it/s]

 49%|████▊     | 48965/100629 [38:35<40:57, 21.02it/s]

 49%|████▊     | 48968/100629 [38:35<42:22, 20.32it/s]

 49%|████▊     | 48971/100629 [38:35<43:07, 19.96it/s]

 49%|████▊     | 48974/100629 [38:35<40:22, 21.33it/s]

 49%|████▊     | 48977/100629 [38:35<37:13, 23.13it/s]

 49%|████▊     | 48980/100629 [38:35<36:50, 23.37it/s]

 49%|████▊     | 48983/100629 [38:35<38:57, 22.10it/s]

 49%|████▊     | 48986/100629 [38:36<39:09, 21.98it/s]

 49%|████▊     | 48989/100629 [38:36<39:30, 21.79it/s]

 49%|████▊     | 48992/100629 [38:36<40:34, 21.21it/s]

 49%|████▊     | 48995/100629 [38:36<44:27, 19.35it/s]

 49%|████▊     | 48998/100629 [38:36<40:58, 21.00it/s]

 49%|████▊     | 49001/100629 [38:36<41:59, 20.49it/s]

 49%|████▊     | 49004/100629 [38:37<42:10, 20.40it/s]

 49%|████▊     | 49008/100629 [38:37<36:01, 23.88it/s]

 49%|████▊     | 49011/100629 [38:37<38:22, 22.42it/s]

 49%|████▊     | 49014/100629 [38:37<39:35, 21.73it/s]

 49%|████▊     | 49017/100629 [38:37<43:39, 19.71it/s]

 49%|████▊     | 49020/100629 [38:37<41:04, 20.94it/s]

 49%|████▊     | 49023/100629 [38:37<38:57, 22.08it/s]

 49%|████▊     | 49026/100629 [38:38<44:09, 19.47it/s]

 49%|████▊     | 49029/100629 [38:38<39:56, 21.53it/s]

 49%|████▊     | 49032/100629 [38:38<39:38, 21.69it/s]

 49%|████▊     | 49035/100629 [38:38<36:47, 23.37it/s]

 49%|████▊     | 49038/100629 [38:38<38:03, 22.60it/s]

 49%|████▊     | 49041/100629 [38:38<39:43, 21.64it/s]

 49%|████▊     | 49044/100629 [38:38<39:46, 21.62it/s]

 49%|████▊     | 49047/100629 [38:38<39:50, 21.58it/s]

 49%|████▊     | 49052/100629 [38:39<35:22, 24.30it/s]

 49%|████▊     | 49055/100629 [38:39<34:16, 25.08it/s]

 49%|████▉     | 49058/100629 [38:39<36:56, 23.27it/s]

 49%|████▉     | 49061/100629 [38:39<41:00, 20.96it/s]

 49%|████▉     | 49064/100629 [38:39<41:52, 20.53it/s]

 49%|████▉     | 49067/100629 [38:39<46:16, 18.57it/s]

 49%|████▉     | 49071/100629 [38:40<39:05, 21.98it/s]

 49%|████▉     | 49077/100629 [38:40<28:59, 29.64it/s]

 49%|████▉     | 49081/100629 [38:40<30:43, 27.96it/s]

 49%|████▉     | 49085/100629 [38:40<34:25, 24.95it/s]

 49%|████▉     | 49088/100629 [38:40<33:10, 25.89it/s]

 49%|████▉     | 49092/100629 [38:40<30:38, 28.04it/s]

 49%|████▉     | 49096/100629 [38:40<28:24, 30.23it/s]

 49%|████▉     | 49100/100629 [38:41<30:50, 27.84it/s]

 49%|████▉     | 49104/100629 [38:41<28:01, 30.65it/s]

 49%|████▉     | 49108/100629 [38:41<30:52, 27.81it/s]

 49%|████▉     | 49112/100629 [38:41<32:09, 26.70it/s]

 49%|████▉     | 49116/100629 [38:41<29:43, 28.88it/s]

 49%|████▉     | 49120/100629 [38:41<30:45, 27.92it/s]

 49%|████▉     | 49123/100629 [38:41<30:16, 28.36it/s]

 49%|████▉     | 49126/100629 [38:41<31:37, 27.14it/s]

 49%|████▉     | 49130/100629 [38:42<29:25, 29.16it/s]

 49%|████▉     | 49133/100629 [38:42<30:34, 28.07it/s]

 49%|████▉     | 49136/100629 [38:42<32:19, 26.55it/s]

 49%|████▉     | 49140/100629 [38:42<28:38, 29.96it/s]

 49%|████▉     | 49144/100629 [38:42<35:57, 23.87it/s]

 49%|████▉     | 49147/100629 [38:42<37:51, 22.67it/s]

 49%|████▉     | 49150/100629 [38:42<36:47, 23.32it/s]

 49%|████▉     | 49153/100629 [38:43<35:24, 24.23it/s]

 49%|████▉     | 49156/100629 [38:43<41:45, 20.55it/s]

 49%|████▉     | 49159/100629 [38:43<41:59, 20.42it/s]

 49%|████▉     | 49162/100629 [38:43<47:57, 17.89it/s]

 49%|████▉     | 49167/100629 [38:43<37:42, 22.74it/s]

 49%|████▉     | 49170/100629 [38:43<40:06, 21.39it/s]

 49%|████▉     | 49173/100629 [38:44<40:12, 21.33it/s]

 49%|████▉     | 49176/100629 [38:44<39:44, 21.58it/s]

 49%|████▉     | 49180/100629 [38:44<35:28, 24.17it/s]

 49%|████▉     | 49183/100629 [38:44<41:49, 20.50it/s]

 49%|████▉     | 49187/100629 [38:44<35:03, 24.45it/s]

 49%|████▉     | 49191/100629 [38:44<32:30, 26.37it/s]

 49%|████▉     | 49194/100629 [38:44<32:02, 26.76it/s]

 49%|████▉     | 49197/100629 [38:45<37:01, 23.16it/s]

 49%|████▉     | 49200/100629 [38:45<48:13, 17.78it/s]

 49%|████▉     | 49203/100629 [38:45<44:37, 19.21it/s]

 49%|████▉     | 49206/100629 [38:45<42:38, 20.10it/s]

 49%|████▉     | 49209/100629 [38:45<41:09, 20.82it/s]

 49%|████▉     | 49212/100629 [38:45<44:56, 19.07it/s]

 49%|████▉     | 49215/100629 [38:46<47:49, 17.92it/s]

 49%|████▉     | 49218/100629 [38:46<43:29, 19.70it/s]

 49%|████▉     | 49221/100629 [38:46<48:31, 17.66it/s]

 49%|████▉     | 49225/100629 [38:46<42:29, 20.16it/s]

 49%|████▉     | 49228/100629 [38:46<45:30, 18.82it/s]

 49%|████▉     | 49230/100629 [38:46<50:41, 16.90it/s]

 49%|████▉     | 49232/100629 [38:47<49:38, 17.26it/s]

 49%|████▉     | 49234/100629 [38:47<55:17, 15.49it/s]

 49%|████▉     | 49236/100629 [38:47<57:16, 14.95it/s]

 49%|████▉     | 49238/100629 [38:47<58:18, 14.69it/s]

 49%|████▉     | 49240/100629 [38:47<56:16, 15.22it/s]

 49%|████▉     | 49242/100629 [38:47<1:00:23, 14.18it/s]

 49%|████▉     | 49246/100629 [38:47<45:15, 18.92it/s]

 49%|████▉     | 49248/100629 [38:47<44:48, 19.11it/s]

 49%|████▉     | 49250/100629 [38:48<50:09, 17.07it/s]

 49%|████▉     | 49254/100629 [38:48<42:28, 20.16it/s]

 49%|████▉     | 49258/100629 [38:48<35:36, 24.05it/s]

 49%|████▉     | 49263/100629 [38:48<30:12, 28.34it/s]

 49%|████▉     | 49266/100629 [38:48<35:10, 24.34it/s]

 49%|████▉     | 49269/100629 [38:48<35:45, 23.94it/s]

 49%|████▉     | 49272/100629 [38:48<35:23, 24.19it/s]

 49%|████▉     | 49276/100629 [38:49<30:41, 27.89it/s]

 49%|████▉     | 49279/100629 [38:49<37:43, 22.69it/s]

 49%|████▉     | 49282/100629 [38:49<39:17, 21.78it/s]

 49%|████▉     | 49287/100629 [38:49<31:24, 27.25it/s]

 49%|████▉     | 49290/100629 [38:49<36:37, 23.36it/s]

 49%|████▉     | 49293/100629 [38:49<38:28, 22.23it/s]

 49%|████▉     | 49296/100629 [38:50<38:48, 22.05it/s]

 49%|████▉     | 49299/100629 [38:50<44:32, 19.21it/s]

 49%|████▉     | 49302/100629 [38:50<47:26, 18.03it/s]

 49%|████▉     | 49305/100629 [38:50<49:00, 17.45it/s]

 49%|████▉     | 49308/100629 [38:50<47:37, 17.96it/s]

 49%|████▉     | 49311/100629 [38:50<51:36, 16.57it/s]

 49%|████▉     | 49313/100629 [38:51<54:34, 15.67it/s]

 49%|████▉     | 49317/100629 [38:51<44:07, 19.38it/s]

 49%|████▉     | 49320/100629 [38:51<40:49, 20.94it/s]

 49%|████▉     | 49323/100629 [38:51<41:11, 20.76it/s]

 49%|████▉     | 49326/100629 [38:51<44:38, 19.15it/s]

 49%|████▉     | 49328/100629 [38:51<45:39, 18.73it/s]

 49%|████▉     | 49331/100629 [38:51<47:04, 18.16it/s]

 49%|████▉     | 49335/100629 [38:52<43:50, 19.50it/s]

 49%|████▉     | 49337/100629 [38:52<45:23, 18.83it/s]

 49%|████▉     | 49339/100629 [38:52<46:43, 18.29it/s]

 49%|████▉     | 49342/100629 [38:52<44:51, 19.06it/s]

 49%|████▉     | 49344/100629 [38:52<46:49, 18.25it/s]

 49%|████▉     | 49347/100629 [38:52<41:36, 20.54it/s]

 49%|████▉     | 49351/100629 [38:52<35:25, 24.13it/s]

 49%|████▉     | 49355/100629 [38:53<31:25, 27.20it/s]

 49%|████▉     | 49358/100629 [38:53<33:23, 25.59it/s]

 49%|████▉     | 49361/100629 [38:53<37:01, 23.08it/s]

 49%|████▉     | 49364/100629 [38:53<35:57, 23.77it/s]

 49%|████▉     | 49368/100629 [38:53<32:21, 26.40it/s]

 49%|████▉     | 49371/100629 [38:53<33:12, 25.72it/s]

 49%|████▉     | 49374/100629 [38:53<34:07, 25.03it/s]

 49%|████▉     | 49377/100629 [38:53<38:10, 22.38it/s]

 49%|████▉     | 49380/100629 [38:54<35:36, 23.99it/s]

 49%|████▉     | 49383/100629 [38:54<35:27, 24.09it/s]

 49%|████▉     | 49386/100629 [38:54<36:00, 23.72it/s]

 49%|████▉     | 49389/100629 [38:54<43:14, 19.75it/s]

 49%|████▉     | 49392/100629 [38:54<44:18, 19.27it/s]

 49%|████▉     | 49397/100629 [38:54<34:09, 24.99it/s]

 49%|████▉     | 49400/100629 [38:54<33:33, 25.44it/s]

 49%|████▉     | 49403/100629 [38:55<35:32, 24.02it/s]

 49%|████▉     | 49406/100629 [38:55<41:07, 20.76it/s]

 49%|████▉     | 49409/100629 [38:55<39:33, 21.58it/s]

 49%|████▉     | 49413/100629 [38:55<35:50, 23.81it/s]

 49%|████▉     | 49416/100629 [38:55<38:46, 22.02it/s]

 49%|████▉     | 49420/100629 [38:55<35:00, 24.38it/s]

 49%|████▉     | 49423/100629 [38:55<37:10, 22.95it/s]

 49%|████▉     | 49426/100629 [38:56<36:15, 23.53it/s]

 49%|████▉     | 49429/100629 [38:56<36:04, 23.66it/s]

 49%|████▉     | 49432/100629 [38:56<36:20, 23.48it/s]

 49%|████▉     | 49436/100629 [38:56<32:00, 26.66it/s]

 49%|████▉     | 49439/100629 [38:56<33:06, 25.77it/s]

 49%|████▉     | 49442/100629 [38:56<37:51, 22.53it/s]

 49%|████▉     | 49445/100629 [38:56<39:46, 21.45it/s]

 49%|████▉     | 49450/100629 [38:57<32:24, 26.32it/s]

 49%|████▉     | 49453/100629 [38:57<34:28, 24.75it/s]

 49%|████▉     | 49456/100629 [38:57<41:19, 20.64it/s]

 49%|████▉     | 49459/100629 [38:57<41:44, 20.43it/s]

 49%|████▉     | 49462/100629 [38:57<43:42, 19.51it/s]

 49%|████▉     | 49466/100629 [38:57<37:50, 22.53it/s]

 49%|████▉     | 49469/100629 [38:57<37:09, 22.95it/s]

 49%|████▉     | 49472/100629 [38:58<41:43, 20.43it/s]

 49%|████▉     | 49475/100629 [38:58<38:27, 22.17it/s]

 49%|████▉     | 49478/100629 [38:58<41:17, 20.64it/s]

 49%|████▉     | 49481/100629 [38:58<45:28, 18.75it/s]

 49%|████▉     | 49484/100629 [38:58<44:46, 19.03it/s]

 49%|████▉     | 49488/100629 [38:58<39:24, 21.63it/s]

 49%|████▉     | 49491/100629 [38:59<40:06, 21.25it/s]

 49%|████▉     | 49494/100629 [38:59<45:41, 18.65it/s]

 49%|████▉     | 49496/100629 [38:59<45:18, 18.81it/s]

 49%|████▉     | 49499/100629 [38:59<40:24, 21.09it/s]

 49%|████▉     | 49503/100629 [38:59<34:13, 24.90it/s]

 49%|████▉     | 49507/100629 [38:59<33:45, 25.24it/s]

 49%|████▉     | 49510/100629 [38:59<36:48, 23.15it/s]

 49%|████▉     | 49513/100629 [39:00<38:15, 22.26it/s]

 49%|████▉     | 49516/100629 [39:00<36:59, 23.03it/s]

 49%|████▉     | 49519/100629 [39:00<36:41, 23.22it/s]

 49%|████▉     | 49522/100629 [39:00<38:55, 21.88it/s]

 49%|████▉     | 49526/100629 [39:00<36:12, 23.52it/s]

 49%|████▉     | 49530/100629 [39:00<33:03, 25.76it/s]

 49%|████▉     | 49533/100629 [39:00<32:34, 26.14it/s]

 49%|████▉     | 49536/100629 [39:00<33:23, 25.51it/s]

 49%|████▉     | 49540/100629 [39:01<31:58, 26.64it/s]

 49%|████▉     | 49543/100629 [39:01<37:21, 22.79it/s]

 49%|████▉     | 49548/100629 [39:01<32:09, 26.47it/s]

 49%|████▉     | 49551/100629 [39:01<39:40, 21.46it/s]

 49%|████▉     | 49554/100629 [39:01<40:05, 21.24it/s]

 49%|████▉     | 49557/100629 [39:01<40:15, 21.15it/s]

 49%|████▉     | 49561/100629 [39:02<35:15, 24.14it/s]

 49%|████▉     | 49564/100629 [39:02<39:01, 21.81it/s]

 49%|████▉     | 49567/100629 [39:02<41:16, 20.62it/s]

 49%|████▉     | 49570/100629 [39:02<38:29, 22.11it/s]

 49%|████▉     | 49573/100629 [39:02<38:15, 22.24it/s]

 49%|████▉     | 49576/100629 [39:02<42:35, 19.98it/s]

 49%|████▉     | 49579/100629 [39:03<43:26, 19.58it/s]

 49%|████▉     | 49583/100629 [39:03<37:08, 22.91it/s]

 49%|████▉     | 49586/100629 [39:03<37:03, 22.96it/s]

 49%|████▉     | 49589/100629 [39:03<45:02, 18.89it/s]

 49%|████▉     | 49593/100629 [39:03<39:40, 21.44it/s]

 49%|████▉     | 49596/100629 [39:03<41:09, 20.67it/s]

 49%|████▉     | 49599/100629 [39:03<39:39, 21.45it/s]

 49%|████▉     | 49602/100629 [39:04<39:10, 21.71it/s]

 49%|████▉     | 49605/100629 [39:04<41:11, 20.65it/s]

 49%|████▉     | 49608/100629 [39:04<39:19, 21.63it/s]

 49%|████▉     | 49611/100629 [39:04<47:13, 18.01it/s]

 49%|████▉     | 49613/100629 [39:04<49:44, 17.09it/s]

 49%|████▉     | 49617/100629 [39:04<39:58, 21.27it/s]

 49%|████▉     | 49620/100629 [39:05<46:26, 18.30it/s]

 49%|████▉     | 49625/100629 [39:05<38:57, 21.82it/s]

 49%|████▉     | 49628/100629 [39:05<43:32, 19.53it/s]

 49%|████▉     | 49631/100629 [39:05<41:06, 20.68it/s]

 49%|████▉     | 49634/100629 [39:05<39:44, 21.39it/s]

 49%|████▉     | 49637/100629 [39:05<39:20, 21.60it/s]

 49%|████▉     | 49640/100629 [39:06<46:36, 18.23it/s]

 49%|████▉     | 49642/100629 [39:06<47:28, 17.90it/s]

 49%|████▉     | 49644/100629 [39:06<47:38, 17.84it/s]

 49%|████▉     | 49647/100629 [39:06<42:17, 20.09it/s]

 49%|████▉     | 49650/100629 [39:06<39:55, 21.28it/s]

 49%|████▉     | 49653/100629 [39:06<43:44, 19.43it/s]

 49%|████▉     | 49656/100629 [39:06<45:26, 18.70it/s]

 49%|████▉     | 49659/100629 [39:06<40:58, 20.73it/s]

 49%|████▉     | 49662/100629 [39:07<38:27, 22.09it/s]

 49%|████▉     | 49665/100629 [39:07<47:05, 18.04it/s]

 49%|████▉     | 49667/100629 [39:07<48:38, 17.46it/s]

 49%|████▉     | 49670/100629 [39:07<51:53, 16.37it/s]

 49%|████▉     | 49672/100629 [39:07<52:08, 16.29it/s]

 49%|████▉     | 49675/100629 [39:07<50:23, 16.85it/s]

 49%|████▉     | 49679/100629 [39:08<44:36, 19.04it/s]

 49%|████▉     | 49682/100629 [39:08<43:08, 19.68it/s]

 49%|████▉     | 49685/100629 [39:08<44:22, 19.14it/s]

 49%|████▉     | 49688/100629 [39:08<44:03, 19.27it/s]

 49%|████▉     | 49690/100629 [39:08<43:42, 19.43it/s]

 49%|████▉     | 49692/100629 [39:08<43:37, 19.46it/s]

 49%|████▉     | 49695/100629 [39:08<42:34, 19.94it/s]

 49%|████▉     | 49698/100629 [39:09<39:44, 21.36it/s]

 49%|████▉     | 49701/100629 [39:09<36:50, 23.04it/s]

 49%|████▉     | 49706/100629 [39:09<28:22, 29.90it/s]

 49%|████▉     | 49710/100629 [39:09<33:38, 25.22it/s]

 49%|████▉     | 49713/100629 [39:09<33:25, 25.38it/s]

 49%|████▉     | 49719/100629 [39:09<27:55, 30.38it/s]

 49%|████▉     | 49723/100629 [39:09<27:57, 30.34it/s]

 49%|████▉     | 49727/100629 [39:10<33:47, 25.11it/s]

 49%|████▉     | 49730/100629 [39:10<34:09, 24.84it/s]

 49%|████▉     | 49733/100629 [39:10<35:07, 24.15it/s]

 49%|████▉     | 49736/100629 [39:10<34:03, 24.90it/s]

 49%|████▉     | 49739/100629 [39:10<39:11, 21.65it/s]

 49%|████▉     | 49742/100629 [39:10<41:04, 20.65it/s]

 49%|████▉     | 49745/100629 [39:10<47:00, 18.04it/s]

 49%|████▉     | 49748/100629 [39:11<43:18, 19.58it/s]

 49%|████▉     | 49751/100629 [39:11<58:34, 14.48it/s]

 49%|████▉     | 49753/100629 [39:11<58:07, 14.59it/s]

 49%|████▉     | 49755/100629 [39:11<55:07, 15.38it/s]

 49%|████▉     | 49758/100629 [39:11<49:13, 17.22it/s]

 49%|████▉     | 49761/100629 [39:11<43:54, 19.31it/s]

 49%|████▉     | 49764/100629 [39:12<40:07, 21.13it/s]

 49%|████▉     | 49767/100629 [39:12<45:37, 18.58it/s]

 49%|████▉     | 49770/100629 [39:12<44:54, 18.87it/s]

 49%|████▉     | 49773/100629 [39:12<43:54, 19.30it/s]

 49%|████▉     | 49777/100629 [39:12<37:39, 22.51it/s]

 49%|████▉     | 49780/100629 [39:12<42:49, 19.79it/s]

 49%|████▉     | 49783/100629 [39:13<44:32, 19.03it/s]

 49%|████▉     | 49787/100629 [39:13<38:55, 21.77it/s]

 49%|████▉     | 49790/100629 [39:13<38:16, 22.13it/s]

 49%|████▉     | 49793/100629 [39:13<41:40, 20.33it/s]

 49%|████▉     | 49797/100629 [39:13<37:16, 22.73it/s]

 49%|████▉     | 49800/100629 [39:13<38:24, 22.06it/s]

 49%|████▉     | 49803/100629 [39:13<37:19, 22.70it/s]

 49%|████▉     | 49806/100629 [39:14<36:19, 23.32it/s]

 49%|████▉     | 49809/100629 [39:14<37:30, 22.58it/s]

 50%|████▉     | 49813/100629 [39:14<34:43, 24.39it/s]

 50%|████▉     | 49818/100629 [39:14<28:53, 29.31it/s]

 50%|████▉     | 49822/100629 [39:14<34:01, 24.88it/s]

 50%|████▉     | 49825/100629 [39:14<41:29, 20.41it/s]

 50%|████▉     | 49828/100629 [39:15<41:00, 20.64it/s]

 50%|████▉     | 49831/100629 [39:15<39:21, 21.51it/s]

 50%|████▉     | 49834/100629 [39:15<36:42, 23.07it/s]

 50%|████▉     | 49839/100629 [39:15<33:04, 25.60it/s]

 50%|████▉     | 49842/100629 [39:15<32:10, 26.31it/s]

 50%|████▉     | 49845/100629 [39:15<35:21, 23.94it/s]

 50%|████▉     | 49849/100629 [39:15<32:27, 26.07it/s]

 50%|████▉     | 49852/100629 [39:15<37:02, 22.84it/s]

 50%|████▉     | 49856/100629 [39:16<35:39, 23.73it/s]

 50%|████▉     | 49859/100629 [39:16<43:08, 19.61it/s]

 50%|████▉     | 49863/100629 [39:16<37:55, 22.31it/s]

 50%|████▉     | 49867/100629 [39:16<34:59, 24.18it/s]

 50%|████▉     | 49870/100629 [39:16<34:47, 24.31it/s]

 50%|████▉     | 49873/100629 [39:16<38:59, 21.69it/s]

 50%|████▉     | 49876/100629 [39:17<38:56, 21.72it/s]

 50%|████▉     | 49879/100629 [39:17<39:44, 21.28it/s]

 50%|████▉     | 49883/100629 [39:17<34:53, 24.25it/s]

 50%|████▉     | 49886/100629 [39:17<33:55, 24.93it/s]

 50%|████▉     | 49890/100629 [39:17<32:54, 25.70it/s]

 50%|████▉     | 49893/100629 [39:17<32:13, 26.24it/s]

 50%|████▉     | 49896/100629 [39:17<31:13, 27.08it/s]

 50%|████▉     | 49899/100629 [39:17<33:11, 25.47it/s]

 50%|████▉     | 49903/100629 [39:18<29:02, 29.11it/s]

 50%|████▉     | 49907/100629 [39:18<30:35, 27.63it/s]

 50%|████▉     | 49910/100629 [39:18<30:04, 28.11it/s]

 50%|████▉     | 49913/100629 [39:18<35:24, 23.87it/s]

 50%|████▉     | 49916/100629 [39:18<37:42, 22.41it/s]

 50%|████▉     | 49919/100629 [39:18<38:54, 21.72it/s]

 50%|████▉     | 49922/100629 [39:18<40:03, 21.10it/s]

 50%|████▉     | 49925/100629 [39:19<36:50, 22.94it/s]

 50%|████▉     | 49928/100629 [39:19<41:33, 20.33it/s]

 50%|████▉     | 49931/100629 [39:19<40:19, 20.95it/s]

 50%|████▉     | 49934/100629 [39:19<49:07, 17.20it/s]

 50%|████▉     | 49936/100629 [39:19<49:32, 17.06it/s]

 50%|████▉     | 49939/100629 [39:19<45:31, 18.56it/s]

 50%|████▉     | 49941/100629 [39:19<49:56, 16.92it/s]

 50%|████▉     | 49944/100629 [39:20<43:44, 19.31it/s]

 50%|████▉     | 49947/100629 [39:20<40:35, 20.81it/s]

 50%|████▉     | 49950/100629 [39:20<38:47, 21.77it/s]

 50%|████▉     | 49953/100629 [39:20<40:16, 20.97it/s]

 50%|████▉     | 49956/100629 [39:20<48:24, 17.44it/s]

 50%|████▉     | 49959/100629 [39:20<44:17, 19.06it/s]

 50%|████▉     | 49962/100629 [39:20<40:12, 21.00it/s]

 50%|████▉     | 49966/100629 [39:21<33:18, 25.35it/s]

 50%|████▉     | 49969/100629 [39:21<35:11, 23.99it/s]

 50%|████▉     | 49974/100629 [39:21<29:27, 28.66it/s]

 50%|████▉     | 49979/100629 [39:21<25:44, 32.80it/s]

 50%|████▉     | 49983/100629 [39:21<33:16, 25.37it/s]

 50%|████▉     | 49986/100629 [39:21<38:18, 22.04it/s]

 50%|████▉     | 49989/100629 [39:22<40:03, 21.07it/s]

 50%|████▉     | 49992/100629 [39:22<45:07, 18.71it/s]

 50%|████▉     | 49995/100629 [39:22<41:04, 20.54it/s]

 50%|████▉     | 49998/100629 [39:22<44:10, 19.11it/s]

 50%|████▉     | 50001/100629 [39:22<53:00, 15.92it/s]

 50%|████▉     | 50004/100629 [39:22<51:15, 16.46it/s]

 50%|████▉     | 50007/100629 [39:23<45:17, 18.63it/s]

 50%|████▉     | 50010/100629 [39:23<43:31, 19.38it/s]

 50%|████▉     | 50013/100629 [39:23<46:34, 18.11it/s]

 50%|████▉     | 50015/100629 [39:23<46:00, 18.34it/s]

 50%|████▉     | 50017/100629 [39:23<46:15, 18.23it/s]

 50%|████▉     | 50020/100629 [39:23<41:29, 20.33it/s]

 50%|████▉     | 50023/100629 [39:23<38:43, 21.78it/s]

 50%|████▉     | 50026/100629 [39:24<38:11, 22.09it/s]

 50%|████▉     | 50029/100629 [39:24<36:39, 23.00it/s]

 50%|████▉     | 50032/100629 [39:24<35:41, 23.62it/s]

 50%|████▉     | 50035/100629 [39:24<59:27, 14.18it/s]

 50%|████▉     | 50037/100629 [39:24<57:49, 14.58it/s]

 50%|████▉     | 50039/100629 [39:24<56:11, 15.01it/s]

 50%|████▉     | 50043/100629 [39:25<43:39, 19.31it/s]

 50%|████▉     | 50047/100629 [39:25<40:04, 21.03it/s]

 50%|████▉     | 50051/100629 [39:25<34:25, 24.49it/s]

 50%|████▉     | 50055/100629 [39:25<32:28, 25.96it/s]

 50%|████▉     | 50058/100629 [39:25<32:29, 25.93it/s]

 50%|████▉     | 50061/100629 [39:25<34:15, 24.60it/s]

 50%|████▉     | 50064/100629 [39:25<40:16, 20.92it/s]

 50%|████▉     | 50067/100629 [39:25<37:25, 22.52it/s]

 50%|████▉     | 50070/100629 [39:26<36:52, 22.85it/s]

 50%|████▉     | 50073/100629 [39:26<38:05, 22.12it/s]

 50%|████▉     | 50078/100629 [39:26<34:31, 24.40it/s]

 50%|████▉     | 50082/100629 [39:26<31:42, 26.57it/s]

 50%|████▉     | 50086/100629 [39:26<29:41, 28.37it/s]

 50%|████▉     | 50089/100629 [39:26<35:32, 23.70it/s]

 50%|████▉     | 50092/100629 [39:27<40:56, 20.58it/s]

 50%|████▉     | 50095/100629 [39:27<45:57, 18.33it/s]

 50%|████▉     | 50099/100629 [39:27<40:28, 20.80it/s]

 50%|████▉     | 50102/100629 [39:27<40:38, 20.72it/s]

 50%|████▉     | 50106/100629 [39:27<38:44, 21.73it/s]

 50%|████▉     | 50109/100629 [39:27<43:12, 19.48it/s]

 50%|████▉     | 50113/100629 [39:28<36:42, 22.93it/s]

 50%|████▉     | 50118/100629 [39:28<32:23, 25.99it/s]

 50%|████▉     | 50121/100629 [39:28<32:56, 25.56it/s]

 50%|████▉     | 50124/100629 [39:28<33:46, 24.92it/s]

 50%|████▉     | 50127/100629 [39:28<41:08, 20.46it/s]

 50%|████▉     | 50130/100629 [39:28<39:25, 21.35it/s]

 50%|████▉     | 50135/100629 [39:28<31:17, 26.89it/s]

 50%|████▉     | 50138/100629 [39:29<31:19, 26.86it/s]

 50%|████▉     | 50141/100629 [39:29<34:25, 24.44it/s]

 50%|████▉     | 50144/100629 [39:29<35:53, 23.44it/s]

 50%|████▉     | 50147/100629 [39:29<37:50, 22.24it/s]

 50%|████▉     | 50151/100629 [39:29<33:03, 25.45it/s]

 50%|████▉     | 50154/100629 [39:29<35:01, 24.02it/s]

 50%|████▉     | 50157/100629 [39:29<41:39, 20.20it/s]

 50%|████▉     | 50160/100629 [39:30<39:54, 21.07it/s]

 50%|████▉     | 50163/100629 [39:30<40:49, 20.61it/s]

 50%|████▉     | 50166/100629 [39:30<37:37, 22.35it/s]

 50%|████▉     | 50169/100629 [39:30<40:23, 20.83it/s]

 50%|████▉     | 50172/100629 [39:30<45:59, 18.28it/s]

 50%|████▉     | 50176/100629 [39:30<38:59, 21.57it/s]

 50%|████▉     | 50179/100629 [39:30<39:11, 21.45it/s]

 50%|████▉     | 50182/100629 [39:31<37:23, 22.49it/s]

 50%|████▉     | 50185/100629 [39:31<37:01, 22.70it/s]

 50%|████▉     | 50188/100629 [39:31<46:08, 18.22it/s]

 50%|████▉     | 50191/100629 [39:31<45:15, 18.57it/s]

 50%|████▉     | 50193/100629 [39:31<45:03, 18.65it/s]

 50%|████▉     | 50195/100629 [39:31<45:37, 18.42it/s]

 50%|████▉     | 50198/100629 [39:31<46:16, 18.16it/s]

 50%|████▉     | 50202/100629 [39:32<38:12, 22.00it/s]

 50%|████▉     | 50205/100629 [39:32<39:46, 21.13it/s]

 50%|████▉     | 50208/100629 [39:32<42:22, 19.83it/s]

 50%|████▉     | 50212/100629 [39:32<38:04, 22.07it/s]

 50%|████▉     | 50216/100629 [39:32<32:38, 25.75it/s]

 50%|████▉     | 50219/100629 [39:32<36:19, 23.13it/s]

 50%|████▉     | 50223/100629 [39:33<34:26, 24.39it/s]

 50%|████▉     | 50226/100629 [39:33<44:33, 18.85it/s]

 50%|████▉     | 50229/100629 [39:33<46:17, 18.15it/s]

 50%|████▉     | 50232/100629 [39:33<45:53, 18.30it/s]

 50%|████▉     | 50235/100629 [39:33<41:39, 20.16it/s]

 50%|████▉     | 50238/100629 [39:33<39:22, 21.33it/s]

 50%|████▉     | 50241/100629 [39:34<42:35, 19.72it/s]

 50%|████▉     | 50244/100629 [39:34<41:07, 20.42it/s]

 50%|████▉     | 50248/100629 [39:34<36:25, 23.05it/s]

 50%|████▉     | 50251/100629 [39:34<35:57, 23.35it/s]

 50%|████▉     | 50254/100629 [39:34<34:10, 24.56it/s]

 50%|████▉     | 50258/100629 [39:34<30:04, 27.91it/s]

 50%|████▉     | 50262/100629 [39:34<32:30, 25.83it/s]

 50%|████▉     | 50265/100629 [39:34<35:43, 23.50it/s]

 50%|████▉     | 50268/100629 [39:35<36:31, 22.98it/s]

 50%|████▉     | 50272/100629 [39:35<34:57, 24.01it/s]

 50%|████▉     | 50275/100629 [39:35<39:01, 21.51it/s]

 50%|████▉     | 50278/100629 [39:35<37:53, 22.15it/s]

 50%|████▉     | 50282/100629 [39:35<32:38, 25.71it/s]

 50%|████▉     | 50285/100629 [39:35<38:35, 21.75it/s]

 50%|████▉     | 50288/100629 [39:35<36:01, 23.30it/s]

 50%|████▉     | 50291/100629 [39:36<34:36, 24.24it/s]

 50%|████▉     | 50295/100629 [39:36<30:53, 27.16it/s]

 50%|████▉     | 50300/100629 [39:36<27:26, 30.58it/s]

 50%|████▉     | 50306/100629 [39:36<22:59, 36.48it/s]

 50%|████▉     | 50310/100629 [39:36<23:16, 36.03it/s]

 50%|████▉     | 50314/100629 [39:36<28:48, 29.11it/s]

 50%|█████     | 50318/100629 [39:36<30:23, 27.59it/s]

 50%|█████     | 50321/100629 [39:37<31:15, 26.83it/s]

 50%|█████     | 50324/100629 [39:37<36:28, 22.99it/s]

 50%|█████     | 50327/100629 [39:37<40:10, 20.86it/s]

 50%|█████     | 50330/100629 [39:37<37:03, 22.62it/s]

 50%|█████     | 50333/100629 [39:37<39:02, 21.47it/s]

 50%|█████     | 50336/100629 [39:37<43:58, 19.06it/s]

 50%|█████     | 50339/100629 [39:38<43:59, 19.05it/s]

 50%|█████     | 50341/100629 [39:38<44:23, 18.88it/s]

 50%|█████     | 50343/100629 [39:38<51:46, 16.19it/s]

 50%|█████     | 50345/100629 [39:38<55:17, 15.16it/s]

 50%|█████     | 50348/100629 [39:38<45:52, 18.26it/s]

 50%|█████     | 50352/100629 [39:38<37:30, 22.34it/s]

 50%|█████     | 50356/100629 [39:38<33:07, 25.29it/s]

 50%|█████     | 50360/100629 [39:38<31:05, 26.95it/s]

 50%|█████     | 50363/100629 [39:39<31:43, 26.41it/s]

 50%|█████     | 50366/100629 [39:39<34:57, 23.96it/s]

 50%|█████     | 50369/100629 [39:39<39:20, 21.29it/s]

 50%|█████     | 50372/100629 [39:39<42:56, 19.51it/s]

 50%|█████     | 50375/100629 [39:39<44:14, 18.93it/s]

 50%|█████     | 50380/100629 [39:39<37:07, 22.56it/s]

 50%|█████     | 50383/100629 [39:40<38:47, 21.59it/s]

 50%|█████     | 50386/100629 [39:40<38:29, 21.76it/s]

 50%|█████     | 50389/100629 [39:40<40:06, 20.88it/s]

 50%|█████     | 50392/100629 [39:40<44:17, 18.90it/s]

 50%|█████     | 50395/100629 [39:40<40:58, 20.43it/s]

 50%|█████     | 50398/100629 [39:40<42:09, 19.86it/s]

 50%|█████     | 50401/100629 [39:41<50:17, 16.65it/s]

 50%|█████     | 50405/100629 [39:41<40:36, 20.62it/s]

 50%|█████     | 50408/100629 [39:41<43:45, 19.13it/s]

 50%|█████     | 50411/100629 [39:41<45:06, 18.56it/s]

 50%|█████     | 50414/100629 [39:41<42:26, 19.72it/s]

 50%|█████     | 50417/100629 [39:41<41:36, 20.11it/s]

 50%|█████     | 50420/100629 [39:42<44:23, 18.85it/s]

 50%|█████     | 50422/100629 [39:42<43:53, 19.06it/s]

 50%|█████     | 50425/100629 [39:42<38:59, 21.46it/s]

 50%|█████     | 50428/100629 [39:42<38:55, 21.49it/s]

 50%|█████     | 50431/100629 [39:42<47:35, 17.58it/s]

 50%|█████     | 50433/100629 [39:42<53:31, 15.63it/s]

 50%|█████     | 50436/100629 [39:42<45:36, 18.34it/s]

 50%|█████     | 50439/100629 [39:42<40:10, 20.82it/s]

 50%|█████     | 50442/100629 [39:43<44:09, 18.94it/s]

 50%|█████     | 50445/100629 [39:43<44:24, 18.83it/s]

 50%|█████     | 50448/100629 [39:43<41:59, 19.92it/s]

 50%|█████     | 50451/100629 [39:43<56:56, 14.69it/s]

 50%|█████     | 50453/100629 [39:43<54:19, 15.39it/s]

 50%|█████     | 50455/100629 [39:44<51:42, 16.17it/s]

 50%|█████     | 50460/100629 [39:44<39:39, 21.08it/s]

 50%|█████     | 50464/100629 [39:44<34:44, 24.07it/s]

 50%|█████     | 50467/100629 [39:44<39:09, 21.35it/s]

 50%|█████     | 50470/100629 [39:44<38:32, 21.69it/s]

 50%|█████     | 50473/100629 [39:44<39:17, 21.27it/s]

 50%|█████     | 50477/100629 [39:44<39:39, 21.07it/s]

 50%|█████     | 50480/100629 [39:45<38:22, 21.78it/s]

 50%|█████     | 50483/100629 [39:45<38:07, 21.92it/s]

 50%|█████     | 50486/100629 [39:45<38:32, 21.68it/s]

 50%|█████     | 50489/100629 [39:45<42:02, 19.88it/s]

 50%|█████     | 50492/100629 [39:45<43:01, 19.42it/s]

 50%|█████     | 50497/100629 [39:45<36:36, 22.83it/s]

 50%|█████     | 50500/100629 [39:46<40:21, 20.70it/s]

 50%|█████     | 50504/100629 [39:46<35:13, 23.71it/s]

 50%|█████     | 50509/100629 [39:46<31:19, 26.67it/s]

 50%|█████     | 50512/100629 [39:46<34:04, 24.52it/s]

 50%|█████     | 50515/100629 [39:46<39:00, 21.41it/s]

 50%|█████     | 50518/100629 [39:46<40:54, 20.42it/s]

 50%|█████     | 50521/100629 [39:47<46:12, 18.07it/s]

 50%|█████     | 50524/100629 [39:47<42:19, 19.73it/s]

 50%|█████     | 50527/100629 [39:47<44:28, 18.77it/s]

 50%|█████     | 50529/100629 [39:47<46:02, 18.13it/s]

 50%|█████     | 50532/100629 [39:47<46:01, 18.14it/s]

 50%|█████     | 50535/100629 [39:47<40:43, 20.50it/s]

 50%|█████     | 50539/100629 [39:47<33:34, 24.87it/s]

 50%|█████     | 50542/100629 [39:47<34:28, 24.22it/s]

 50%|█████     | 50545/100629 [39:48<33:25, 24.97it/s]

 50%|█████     | 50548/100629 [39:48<34:20, 24.30it/s]

 50%|█████     | 50551/100629 [39:48<34:28, 24.20it/s]

 50%|█████     | 50554/100629 [39:48<34:45, 24.01it/s]

 50%|█████     | 50558/100629 [39:48<33:37, 24.82it/s]

 50%|█████     | 50561/100629 [39:48<32:11, 25.92it/s]

 50%|█████     | 50564/100629 [39:48<35:20, 23.61it/s]

 50%|█████     | 50567/100629 [39:49<44:28, 18.76it/s]

 50%|█████     | 50570/100629 [39:49<43:39, 19.11it/s]

 50%|█████     | 50573/100629 [39:49<40:51, 20.41it/s]

 50%|█████     | 50576/100629 [39:49<38:45, 21.53it/s]

 50%|█████     | 50579/100629 [39:49<42:19, 19.71it/s]

 50%|█████     | 50582/100629 [39:49<39:59, 20.85it/s]

 50%|█████     | 50585/100629 [39:49<43:53, 19.00it/s]

 50%|█████     | 50587/100629 [39:50<45:12, 18.45it/s]

 50%|█████     | 50590/100629 [39:50<42:36, 19.57it/s]

 50%|█████     | 50593/100629 [39:50<49:34, 16.82it/s]

 50%|█████     | 50595/100629 [39:50<50:57, 16.37it/s]

 50%|█████     | 50598/100629 [39:50<47:35, 17.52it/s]

 50%|█████     | 50601/100629 [39:50<42:45, 19.50it/s]

 50%|█████     | 50604/100629 [39:51<43:03, 19.36it/s]

 50%|█████     | 50608/100629 [39:51<40:39, 20.51it/s]

 50%|█████     | 50611/100629 [39:51<54:31, 15.29it/s]

 50%|█████     | 50613/100629 [39:51<54:55, 15.18it/s]

 50%|█████     | 50618/100629 [39:51<40:40, 20.49it/s]

 50%|█████     | 50621/100629 [39:51<39:20, 21.18it/s]

 50%|█████     | 50626/100629 [39:52<31:23, 26.54it/s]

 50%|█████     | 50629/100629 [39:52<34:51, 23.90it/s]

 50%|█████     | 50632/100629 [39:52<38:12, 21.81it/s]

 50%|█████     | 50635/100629 [39:52<43:03, 19.35it/s]

 50%|█████     | 50638/100629 [39:52<38:49, 21.46it/s]

 50%|█████     | 50641/100629 [39:52<36:18, 22.94it/s]

 50%|█████     | 50644/100629 [39:52<35:51, 23.24it/s]

 50%|█████     | 50647/100629 [39:53<39:02, 21.34it/s]

 50%|█████     | 50650/100629 [39:53<40:01, 20.82it/s]

 50%|█████     | 50653/100629 [39:53<43:34, 19.12it/s]

 50%|█████     | 50656/100629 [39:53<42:19, 19.68it/s]

 50%|█████     | 50662/100629 [39:53<31:19, 26.58it/s]

 50%|█████     | 50665/100629 [39:53<32:03, 25.98it/s]

 50%|█████     | 50668/100629 [39:53<34:26, 24.18it/s]

 50%|█████     | 50671/100629 [39:54<35:02, 23.76it/s]

 50%|█████     | 50674/100629 [39:54<35:18, 23.58it/s]

 50%|█████     | 50677/100629 [39:54<33:10, 25.10it/s]

 50%|█████     | 50680/100629 [39:54<35:26, 23.49it/s]

 50%|█████     | 50683/100629 [39:54<36:08, 23.03it/s]

 50%|█████     | 50686/100629 [39:54<40:53, 20.36it/s]

 50%|█████     | 50689/100629 [39:54<43:55, 18.95it/s]

 50%|█████     | 50691/100629 [39:55<48:41, 17.09it/s]

 50%|█████     | 50693/100629 [39:55<50:17, 16.55it/s]

 50%|█████     | 50695/100629 [39:55<52:15, 15.93it/s]

 50%|█████     | 50699/100629 [39:55<41:47, 19.91it/s]

 50%|█████     | 50702/100629 [39:55<41:29, 20.06it/s]

 50%|█████     | 50705/100629 [39:55<38:25, 21.65it/s]

 50%|█████     | 50708/100629 [39:55<39:38, 20.98it/s]

 50%|█████     | 50711/100629 [39:56<43:21, 19.19it/s]

 50%|█████     | 50713/100629 [39:56<44:24, 18.74it/s]

 50%|█████     | 50715/100629 [39:56<45:51, 18.14it/s]

 50%|█████     | 50717/100629 [39:56<45:48, 18.16it/s]

 50%|█████     | 50720/100629 [39:56<48:19, 17.21it/s]

 50%|█████     | 50722/100629 [39:56<51:13, 16.24it/s]

 50%|█████     | 50724/100629 [39:56<49:13, 16.90it/s]

 50%|█████     | 50727/100629 [39:57<44:53, 18.53it/s]

 50%|█████     | 50730/100629 [39:57<39:42, 20.95it/s]

 50%|█████     | 50733/100629 [39:57<39:11, 21.22it/s]

 50%|█████     | 50736/100629 [39:57<41:37, 19.97it/s]

 50%|█████     | 50739/100629 [39:57<37:38, 22.09it/s]

 50%|█████     | 50743/100629 [39:57<33:51, 24.55it/s]

 50%|█████     | 50746/100629 [39:57<36:16, 22.92it/s]

 50%|█████     | 50749/100629 [39:58<39:57, 20.81it/s]

 50%|█████     | 50752/100629 [39:58<40:11, 20.68it/s]

 50%|█████     | 50755/100629 [39:58<45:07, 18.42it/s]

 50%|█████     | 50758/100629 [39:58<44:17, 18.77it/s]

 50%|█████     | 50761/100629 [39:58<40:10, 20.68it/s]

 50%|█████     | 50764/100629 [39:58<47:16, 17.58it/s]

 50%|█████     | 50766/100629 [39:59<49:25, 16.82it/s]

 50%|█████     | 50770/100629 [39:59<39:56, 20.80it/s]

 50%|█████     | 50774/100629 [39:59<34:01, 24.42it/s]

 50%|█████     | 50777/100629 [39:59<33:58, 24.45it/s]

 50%|█████     | 50780/100629 [39:59<33:32, 24.77it/s]

 50%|█████     | 50783/100629 [39:59<35:17, 23.54it/s]

 50%|█████     | 50787/100629 [39:59<33:26, 24.85it/s]

 50%|█████     | 50790/100629 [39:59<33:26, 24.84it/s]

 50%|█████     | 50793/100629 [40:00<36:04, 23.03it/s]

 50%|█████     | 50796/100629 [40:00<37:24, 22.20it/s]

 50%|█████     | 50799/100629 [40:00<35:43, 23.25it/s]

 50%|█████     | 50802/100629 [40:00<38:29, 21.58it/s]

 50%|█████     | 50806/100629 [40:00<32:15, 25.75it/s]

 50%|█████     | 50809/100629 [40:00<35:51, 23.15it/s]

 50%|█████     | 50812/100629 [40:00<41:25, 20.04it/s]

 50%|█████     | 50815/100629 [40:01<39:31, 21.00it/s]

 51%|█████     | 50818/100629 [40:01<36:11, 22.94it/s]

 51%|█████     | 50822/100629 [40:01<31:16, 26.55it/s]

 51%|█████     | 50825/100629 [40:01<34:07, 24.32it/s]

 51%|█████     | 50828/100629 [40:01<39:01, 21.27it/s]

 51%|█████     | 50831/100629 [40:01<43:47, 18.95it/s]

 51%|█████     | 50835/100629 [40:01<37:43, 22.00it/s]

 51%|█████     | 50838/100629 [40:02<35:10, 23.59it/s]

 51%|█████     | 50841/100629 [40:02<36:00, 23.04it/s]

 51%|█████     | 50844/100629 [40:02<41:55, 19.79it/s]

 51%|█████     | 50847/100629 [40:02<41:27, 20.01it/s]

 51%|█████     | 50850/100629 [40:02<43:51, 18.91it/s]

 51%|█████     | 50853/100629 [40:02<39:29, 21.01it/s]

 51%|█████     | 50856/100629 [40:02<36:40, 22.62it/s]

 51%|█████     | 50860/100629 [40:03<34:26, 24.08it/s]

 51%|█████     | 50863/100629 [40:03<34:32, 24.01it/s]

 51%|█████     | 50866/100629 [40:03<33:01, 25.11it/s]

 51%|█████     | 50869/100629 [40:03<34:28, 24.06it/s]

 51%|█████     | 50872/100629 [40:03<37:54, 21.88it/s]

 51%|█████     | 50875/100629 [40:03<36:46, 22.55it/s]

 51%|█████     | 50878/100629 [40:03<36:38, 22.63it/s]

 51%|█████     | 50881/100629 [40:03<35:34, 23.31it/s]

 51%|█████     | 50884/100629 [40:04<35:49, 23.15it/s]

 51%|█████     | 50887/100629 [40:04<37:40, 22.00it/s]

 51%|█████     | 50890/100629 [40:04<39:58, 20.73it/s]

 51%|█████     | 50893/100629 [40:04<40:32, 20.45it/s]

 51%|█████     | 50897/100629 [40:04<36:55, 22.45it/s]

 51%|█████     | 50900/100629 [40:04<41:42, 19.87it/s]

 51%|█████     | 50903/100629 [40:05<40:08, 20.64it/s]

 51%|█████     | 50907/100629 [40:05<37:30, 22.09it/s]

 51%|█████     | 50910/100629 [40:05<41:16, 20.08it/s]

 51%|█████     | 50913/100629 [40:05<39:21, 21.05it/s]

 51%|█████     | 50916/100629 [40:05<37:12, 22.27it/s]

 51%|█████     | 50919/100629 [40:05<38:15, 21.65it/s]

 51%|█████     | 50922/100629 [40:05<35:17, 23.48it/s]

 51%|█████     | 50925/100629 [40:06<36:42, 22.57it/s]

 51%|█████     | 50928/100629 [40:06<45:51, 18.06it/s]

 51%|█████     | 50930/100629 [40:06<47:44, 17.35it/s]

 51%|█████     | 50932/100629 [40:06<51:01, 16.23it/s]

 51%|█████     | 50935/100629 [40:06<45:44, 18.10it/s]

 51%|█████     | 50937/100629 [40:06<49:23, 16.77it/s]

 51%|█████     | 50940/100629 [40:06<44:18, 18.69it/s]

 51%|█████     | 50943/100629 [40:07<42:39, 19.41it/s]

 51%|█████     | 50945/100629 [40:07<45:12, 18.31it/s]

 51%|█████     | 50948/100629 [40:07<40:37, 20.38it/s]

 51%|█████     | 50952/100629 [40:07<35:04, 23.60it/s]

 51%|█████     | 50957/100629 [40:07<29:58, 27.61it/s]

 51%|█████     | 50962/100629 [40:07<25:37, 32.30it/s]

 51%|█████     | 50966/100629 [40:07<26:50, 30.83it/s]

 51%|█████     | 50970/100629 [40:08<26:59, 30.66it/s]

 51%|█████     | 50974/100629 [40:08<32:33, 25.42it/s]

 51%|█████     | 50978/100629 [40:08<34:57, 23.67it/s]

 51%|█████     | 50982/100629 [40:08<33:28, 24.72it/s]

 51%|█████     | 50985/100629 [40:08<33:50, 24.45it/s]

 51%|█████     | 50989/100629 [40:08<29:51, 27.70it/s]

 51%|█████     | 50993/100629 [40:08<30:41, 26.95it/s]

 51%|█████     | 50996/100629 [40:09<30:13, 27.37it/s]

 51%|█████     | 50999/100629 [40:09<31:03, 26.63it/s]

 51%|█████     | 51003/100629 [40:09<28:37, 28.89it/s]

 51%|█████     | 51006/100629 [40:09<28:45, 28.77it/s]

 51%|█████     | 51009/100629 [40:09<32:24, 25.52it/s]

 51%|█████     | 51012/100629 [40:09<34:33, 23.93it/s]

 51%|█████     | 51015/100629 [40:09<37:50, 21.85it/s]

 51%|█████     | 51018/100629 [40:10<37:14, 22.20it/s]

 51%|█████     | 51022/100629 [40:10<31:44, 26.04it/s]

 51%|█████     | 51025/100629 [40:10<34:44, 23.79it/s]

 51%|█████     | 51029/100629 [40:10<30:49, 26.82it/s]

 51%|█████     | 51032/100629 [40:10<38:43, 21.35it/s]

 51%|█████     | 51035/100629 [40:10<45:07, 18.31it/s]

 51%|█████     | 51038/100629 [40:10<40:08, 20.59it/s]

 51%|█████     | 51041/100629 [40:11<37:28, 22.05it/s]

 51%|█████     | 51044/100629 [40:11<37:29, 22.04it/s]

 51%|█████     | 51047/100629 [40:11<35:18, 23.41it/s]

 51%|█████     | 51050/100629 [40:11<35:05, 23.54it/s]

 51%|█████     | 51055/100629 [40:11<30:48, 26.82it/s]

 51%|█████     | 51058/100629 [40:11<33:45, 24.47it/s]

 51%|█████     | 51061/100629 [40:11<41:36, 19.85it/s]

 51%|█████     | 51064/100629 [40:12<44:57, 18.38it/s]

 51%|█████     | 51067/100629 [40:12<40:14, 20.53it/s]

 51%|█████     | 51070/100629 [40:12<40:11, 20.55it/s]

 51%|█████     | 51073/100629 [40:12<38:55, 21.22it/s]

 51%|█████     | 51077/100629 [40:12<36:39, 22.53it/s]

 51%|█████     | 51080/100629 [40:12<38:07, 21.66it/s]

 51%|█████     | 51083/100629 [40:13<46:04, 17.92it/s]

 51%|█████     | 51085/100629 [40:13<50:19, 16.41it/s]

 51%|█████     | 51087/100629 [40:13<49:25, 16.71it/s]

 51%|█████     | 51091/100629 [40:13<45:03, 18.32it/s]

 51%|█████     | 51094/100629 [40:13<41:11, 20.04it/s]

 51%|█████     | 51097/100629 [40:13<42:36, 19.38it/s]

 51%|█████     | 51100/100629 [40:13<42:46, 19.30it/s]

 51%|█████     | 51103/100629 [40:14<45:48, 18.02it/s]

 51%|█████     | 51106/100629 [40:14<42:16, 19.53it/s]

 51%|█████     | 51109/100629 [40:14<45:47, 18.03it/s]

 51%|█████     | 51111/100629 [40:14<46:08, 17.88it/s]

 51%|█████     | 51113/100629 [40:14<48:16, 17.09it/s]

 51%|█████     | 51117/100629 [40:14<39:56, 20.66it/s]

 51%|█████     | 51120/100629 [40:15<40:59, 20.13it/s]

 51%|█████     | 51124/100629 [40:15<34:18, 24.05it/s]

 51%|█████     | 51127/100629 [40:15<38:02, 21.69it/s]

 51%|█████     | 51130/100629 [40:15<38:44, 21.29it/s]

 51%|█████     | 51133/100629 [40:15<37:42, 21.88it/s]

 51%|█████     | 51136/100629 [40:15<54:30, 15.13it/s]

 51%|█████     | 51138/100629 [40:16<53:40, 15.37it/s]

 51%|█████     | 51140/100629 [40:16<50:51, 16.22it/s]

 51%|█████     | 51143/100629 [40:16<45:57, 17.95it/s]

 51%|█████     | 51146/100629 [40:16<41:19, 19.95it/s]

 51%|█████     | 51149/100629 [40:16<51:47, 15.92it/s]

 51%|█████     | 51152/100629 [40:16<45:25, 18.15it/s]

 51%|█████     | 51155/100629 [40:16<43:13, 19.07it/s]

 51%|█████     | 51158/100629 [40:17<49:36, 16.62it/s]

 51%|█████     | 51162/100629 [40:17<39:48, 20.71it/s]

 51%|█████     | 51165/100629 [40:17<40:23, 20.41it/s]

 51%|█████     | 51168/100629 [40:17<48:11, 17.11it/s]

 51%|█████     | 51172/100629 [40:17<40:32, 20.33it/s]

 51%|█████     | 51175/100629 [40:17<42:54, 19.21it/s]

 51%|█████     | 51178/100629 [40:18<40:35, 20.30it/s]

 51%|█████     | 51181/100629 [40:18<37:46, 21.82it/s]

 51%|█████     | 51184/100629 [40:18<37:32, 21.95it/s]

 51%|█████     | 51187/100629 [40:18<39:33, 20.83it/s]

 51%|█████     | 51190/100629 [40:18<37:22, 22.05it/s]

 51%|█████     | 51193/100629 [40:18<37:13, 22.13it/s]

 51%|█████     | 51196/100629 [40:18<38:36, 21.33it/s]

 51%|█████     | 51199/100629 [40:19<40:49, 20.18it/s]

 51%|█████     | 51202/100629 [40:19<38:15, 21.53it/s]

 51%|█████     | 51205/100629 [40:19<38:37, 21.33it/s]

 51%|█████     | 51208/100629 [40:19<37:50, 21.77it/s]

 51%|█████     | 51211/100629 [40:19<40:40, 20.25it/s]

 51%|█████     | 51215/100629 [40:19<36:15, 22.71it/s]

 51%|█████     | 51218/100629 [40:19<35:34, 23.15it/s]

 51%|█████     | 51221/100629 [40:20<43:50, 18.78it/s]

 51%|█████     | 51224/100629 [40:20<42:49, 19.23it/s]

 51%|█████     | 51227/100629 [40:20<48:07, 17.11it/s]

 51%|█████     | 51231/100629 [40:20<40:49, 20.17it/s]

 51%|█████     | 51234/100629 [40:20<39:29, 20.85it/s]

 51%|█████     | 51237/100629 [40:20<39:17, 20.95it/s]

 51%|█████     | 51240/100629 [40:21<43:32, 18.90it/s]

 51%|█████     | 51243/100629 [40:21<42:11, 19.51it/s]

 51%|█████     | 51247/100629 [40:21<37:52, 21.73it/s]

 51%|█████     | 51253/100629 [40:21<30:25, 27.04it/s]

 51%|█████     | 51258/100629 [40:21<27:58, 29.41it/s]

 51%|█████     | 51261/100629 [40:21<35:08, 23.41it/s]

 51%|█████     | 51266/100629 [40:22<31:00, 26.53it/s]

 51%|█████     | 51269/100629 [40:22<31:12, 26.36it/s]

 51%|█████     | 51272/100629 [40:22<35:02, 23.48it/s]

 51%|█████     | 51275/100629 [40:22<42:26, 19.38it/s]

 51%|█████     | 51278/100629 [40:22<46:27, 17.70it/s]

 51%|█████     | 51281/100629 [40:22<43:12, 19.04it/s]

 51%|█████     | 51284/100629 [40:23<42:54, 19.17it/s]

 51%|█████     | 51287/100629 [40:23<43:47, 18.78it/s]

 51%|█████     | 51291/100629 [40:23<36:06, 22.78it/s]

 51%|█████     | 51295/100629 [40:23<33:39, 24.43it/s]

 51%|█████     | 51298/100629 [40:23<41:41, 19.72it/s]

 51%|█████     | 51301/100629 [40:23<40:31, 20.29it/s]

 51%|█████     | 51304/100629 [40:24<46:21, 17.73it/s]

 51%|█████     | 51307/100629 [40:24<42:40, 19.27it/s]

 51%|█████     | 51310/100629 [40:24<54:34, 15.06it/s]

 51%|█████     | 51313/100629 [40:24<47:06, 17.45it/s]

 51%|█████     | 51316/100629 [40:24<44:34, 18.44it/s]

 51%|█████     | 51319/100629 [40:24<41:28, 19.81it/s]

 51%|█████     | 51322/100629 [40:25<52:09, 15.75it/s]

 51%|█████     | 51324/100629 [40:25<51:52, 15.84it/s]

 51%|█████     | 51326/100629 [40:25<52:28, 15.66it/s]

 51%|█████     | 51328/100629 [40:25<54:52, 14.97it/s]

 51%|█████     | 51332/100629 [40:25<41:54, 19.61it/s]

 51%|█████     | 51335/100629 [40:25<41:52, 19.62it/s]

 51%|█████     | 51339/100629 [40:25<34:14, 23.99it/s]

 51%|█████     | 51342/100629 [40:26<42:31, 19.32it/s]

 51%|█████     | 51345/100629 [40:26<40:46, 20.14it/s]

 51%|█████     | 51348/100629 [40:26<52:36, 15.61it/s]

 51%|█████     | 51351/100629 [40:26<54:06, 15.18it/s]

 51%|█████     | 51355/100629 [40:26<44:01, 18.65it/s]

 51%|█████     | 51358/100629 [40:27<44:55, 18.28it/s]

 51%|█████     | 51362/100629 [40:27<36:35, 22.44it/s]

 51%|█████     | 51365/100629 [40:27<38:58, 21.06it/s]

 51%|█████     | 51368/100629 [40:27<41:02, 20.01it/s]

 51%|█████     | 51372/100629 [40:27<34:20, 23.90it/s]

 51%|█████     | 51375/100629 [40:27<34:55, 23.51it/s]

 51%|█████     | 51379/100629 [40:27<31:11, 26.32it/s]

 51%|█████     | 51384/100629 [40:28<27:00, 30.38it/s]

 51%|█████     | 51388/100629 [40:28<34:18, 23.92it/s]

 51%|█████     | 51391/100629 [40:28<33:27, 24.53it/s]

 51%|█████     | 51394/100629 [40:28<34:26, 23.82it/s]

 51%|█████     | 51397/100629 [40:28<35:00, 23.44it/s]

 51%|█████     | 51400/100629 [40:28<33:30, 24.49it/s]

 51%|█████     | 51403/100629 [40:28<41:26, 19.80it/s]

 51%|█████     | 51406/100629 [40:29<38:50, 21.12it/s]

 51%|█████     | 51412/100629 [40:29<28:38, 28.64it/s]

 51%|█████     | 51416/100629 [40:29<30:01, 27.32it/s]

 51%|█████     | 51420/100629 [40:29<30:43, 26.69it/s]

 51%|█████     | 51423/100629 [40:29<36:06, 22.72it/s]

 51%|█████     | 51426/100629 [40:29<34:23, 23.84it/s]

 51%|█████     | 51431/100629 [40:29<28:19, 28.95it/s]

 51%|█████     | 51435/100629 [40:30<31:41, 25.87it/s]

 51%|█████     | 51438/100629 [40:30<36:37, 22.38it/s]

 51%|█████     | 51441/100629 [40:30<40:10, 20.40it/s]

 51%|█████     | 51445/100629 [40:30<33:57, 24.14it/s]

 51%|█████     | 51448/100629 [40:30<35:46, 22.91it/s]

 51%|█████     | 51451/100629 [40:30<36:20, 22.55it/s]

 51%|█████     | 51454/100629 [40:31<37:41, 21.74it/s]

 51%|█████     | 51457/100629 [40:31<36:15, 22.60it/s]

 51%|█████     | 51461/100629 [40:31<30:50, 26.57it/s]

 51%|█████     | 51464/100629 [40:31<33:05, 24.76it/s]

 51%|█████     | 51467/100629 [40:31<33:39, 24.34it/s]

 51%|█████     | 51470/100629 [40:31<32:31, 25.19it/s]

 51%|█████     | 51473/100629 [40:31<33:58, 24.12it/s]

 51%|█████     | 51477/100629 [40:31<33:58, 24.11it/s]

 51%|█████     | 51480/100629 [40:32<34:50, 23.51it/s]

 51%|█████     | 51484/100629 [40:32<29:56, 27.36it/s]

 51%|█████     | 51487/100629 [40:32<29:51, 27.43it/s]

 51%|█████     | 51491/100629 [40:32<31:22, 26.10it/s]

 51%|█████     | 51494/100629 [40:32<34:11, 23.95it/s]

 51%|█████     | 51498/100629 [40:32<31:05, 26.33it/s]

 51%|█████     | 51501/100629 [40:32<35:53, 22.82it/s]

 51%|█████     | 51504/100629 [40:33<35:03, 23.36it/s]

 51%|█████     | 51507/100629 [40:33<35:12, 23.25it/s]

 51%|█████     | 51510/100629 [40:33<37:30, 21.83it/s]

 51%|█████     | 51513/100629 [40:33<38:11, 21.44it/s]

 51%|█████     | 51516/100629 [40:33<37:50, 21.63it/s]

 51%|█████     | 51519/100629 [40:33<37:14, 21.98it/s]

 51%|█████     | 51523/100629 [40:33<36:57, 22.14it/s]

 51%|█████     | 51528/100629 [40:34<31:06, 26.31it/s]

 51%|█████     | 51531/100629 [40:34<32:27, 25.21it/s]

 51%|█████     | 51534/100629 [40:34<32:05, 25.50it/s]

 51%|█████     | 51538/100629 [40:34<30:33, 26.77it/s]

 51%|█████     | 51542/100629 [40:34<30:47, 26.57it/s]

 51%|█████     | 51546/100629 [40:34<29:59, 27.27it/s]

 51%|█████     | 51549/100629 [40:34<32:30, 25.16it/s]

 51%|█████     | 51553/100629 [40:35<30:09, 27.12it/s]

 51%|█████     | 51556/100629 [40:35<35:13, 23.22it/s]

 51%|█████     | 51559/100629 [40:35<33:19, 24.54it/s]

 51%|█████     | 51563/100629 [40:35<32:24, 25.23it/s]

 51%|█████     | 51567/100629 [40:35<31:49, 25.70it/s]

 51%|█████     | 51571/100629 [40:35<28:59, 28.20it/s]

 51%|█████▏    | 51575/100629 [40:35<31:31, 25.94it/s]

 51%|█████▏    | 51578/100629 [40:35<31:15, 26.16it/s]

 51%|█████▏    | 51581/100629 [40:36<40:38, 20.11it/s]

 51%|█████▏    | 51585/100629 [40:36<36:14, 22.56it/s]

 51%|█████▏    | 51589/100629 [40:36<32:26, 25.20it/s]

 51%|█████▏    | 51594/100629 [40:36<27:02, 30.22it/s]

 51%|█████▏    | 51598/100629 [40:36<30:03, 27.19it/s]

 51%|█████▏    | 51601/100629 [40:36<30:37, 26.68it/s]

 51%|█████▏    | 51604/100629 [40:37<32:00, 25.53it/s]

 51%|█████▏    | 51607/100629 [40:37<33:41, 24.25it/s]

 51%|█████▏    | 51610/100629 [40:37<33:56, 24.07it/s]

 51%|█████▏    | 51613/100629 [40:37<35:59, 22.70it/s]

 51%|█████▏    | 51616/100629 [40:37<33:39, 24.27it/s]

 51%|█████▏    | 51619/100629 [40:37<35:13, 23.19it/s]

 51%|█████▏    | 51622/100629 [40:37<35:01, 23.32it/s]

 51%|█████▏    | 51625/100629 [40:37<36:50, 22.17it/s]

 51%|█████▏    | 51628/100629 [40:38<38:06, 21.43it/s]

 51%|█████▏    | 51631/100629 [40:38<41:03, 19.89it/s]

 51%|█████▏    | 51634/100629 [40:38<46:22, 17.61it/s]

 51%|█████▏    | 51637/100629 [40:38<44:18, 18.43it/s]

 51%|█████▏    | 51639/100629 [40:38<46:37, 17.51it/s]

 51%|█████▏    | 51641/100629 [40:38<45:21, 18.00it/s]

 51%|█████▏    | 51644/100629 [40:39<39:59, 20.42it/s]

 51%|█████▏    | 51647/100629 [40:39<39:39, 20.59it/s]

 51%|█████▏    | 51651/100629 [40:39<35:46, 22.82it/s]

 51%|█████▏    | 51654/100629 [40:39<35:47, 22.81it/s]

 51%|█████▏    | 51657/100629 [40:39<35:48, 22.79it/s]

 51%|█████▏    | 51660/100629 [40:39<43:05, 18.94it/s]

 51%|█████▏    | 51663/100629 [40:39<45:49, 17.81it/s]

 51%|█████▏    | 51665/100629 [40:40<46:42, 17.47it/s]

 51%|█████▏    | 51667/100629 [40:40<48:38, 16.78it/s]

 51%|█████▏    | 51670/100629 [40:40<45:50, 17.80it/s]

 51%|█████▏    | 51672/100629 [40:40<45:01, 18.12it/s]

 51%|█████▏    | 51676/100629 [40:40<35:19, 23.10it/s]

 51%|█████▏    | 51680/100629 [40:40<32:18, 25.26it/s]

 51%|█████▏    | 51683/100629 [40:40<34:59, 23.32it/s]

 51%|█████▏    | 51686/100629 [40:41<39:41, 20.56it/s]

 51%|█████▏    | 51689/100629 [40:41<37:31, 21.74it/s]

 51%|█████▏    | 51692/100629 [40:41<48:18, 16.88it/s]

 51%|█████▏    | 51694/100629 [40:41<46:51, 17.41it/s]

 51%|█████▏    | 51696/100629 [40:41<48:31, 16.81it/s]

 51%|█████▏    | 51700/100629 [40:41<42:15, 19.29it/s]

 51%|█████▏    | 51703/100629 [40:42<45:10, 18.05it/s]

 51%|█████▏    | 51705/100629 [40:42<46:07, 17.68it/s]

 51%|█████▏    | 51709/100629 [40:42<44:03, 18.50it/s]

 51%|█████▏    | 51712/100629 [40:42<41:36, 19.59it/s]

 51%|█████▏    | 51714/100629 [40:42<43:00, 18.96it/s]

 51%|█████▏    | 51717/100629 [40:42<43:40, 18.66it/s]

 51%|█████▏    | 51719/100629 [40:42<48:05, 16.95it/s]

 51%|█████▏    | 51721/100629 [40:43<49:55, 16.33it/s]

 51%|█████▏    | 51723/100629 [40:43<51:38, 15.79it/s]

 51%|█████▏    | 51725/100629 [40:43<48:58, 16.64it/s]

 51%|█████▏    | 51727/100629 [40:43<47:58, 16.99it/s]

 51%|█████▏    | 51729/100629 [40:43<46:30, 17.52it/s]

 51%|█████▏    | 51732/100629 [40:43<43:17, 18.82it/s]

 51%|█████▏    | 51734/100629 [40:43<45:31, 17.90it/s]

 51%|█████▏    | 51736/100629 [40:43<46:36, 17.48it/s]

 51%|█████▏    | 51738/100629 [40:44<48:52, 16.67it/s]

 51%|█████▏    | 51740/100629 [40:44<47:38, 17.11it/s]

 51%|█████▏    | 51743/100629 [40:44<41:45, 19.51it/s]

 51%|█████▏    | 51747/100629 [40:44<33:10, 24.56it/s]

 51%|█████▏    | 51750/100629 [40:44<40:57, 19.89it/s]

 51%|█████▏    | 51753/100629 [40:44<39:59, 20.37it/s]

 51%|█████▏    | 51756/100629 [40:44<39:00, 20.88it/s]

 51%|█████▏    | 51759/100629 [40:45<37:22, 21.79it/s]

 51%|█████▏    | 51763/100629 [40:45<35:45, 22.78it/s]

 51%|█████▏    | 51766/100629 [40:45<33:42, 24.16it/s]

 51%|█████▏    | 51769/100629 [40:45<31:50, 25.57it/s]

 51%|█████▏    | 51774/100629 [40:45<27:49, 29.26it/s]

 51%|█████▏    | 51778/100629 [40:45<28:07, 28.94it/s]

 51%|█████▏    | 51783/100629 [40:45<25:24, 32.04it/s]

 51%|█████▏    | 51787/100629 [40:45<25:09, 32.35it/s]

 51%|█████▏    | 51791/100629 [40:46<33:06, 24.59it/s]

 51%|█████▏    | 51795/100629 [40:46<31:48, 25.58it/s]

 51%|█████▏    | 51798/100629 [40:46<32:03, 25.38it/s]

 51%|█████▏    | 51801/100629 [40:46<36:41, 22.18it/s]

 51%|█████▏    | 51804/100629 [40:46<34:56, 23.29it/s]

 51%|█████▏    | 51807/100629 [40:46<34:05, 23.87it/s]

 51%|█████▏    | 51810/100629 [40:46<35:12, 23.11it/s]

 51%|█████▏    | 51813/100629 [40:47<36:19, 22.40it/s]

 51%|█████▏    | 51816/100629 [40:47<39:46, 20.45it/s]

 51%|█████▏    | 51820/100629 [40:47<41:15, 19.72it/s]

 51%|█████▏    | 51823/100629 [40:47<42:58, 18.92it/s]

 52%|█████▏    | 51826/100629 [40:47<40:30, 20.08it/s]

 52%|█████▏    | 51830/100629 [40:47<35:44, 22.76it/s]

 52%|█████▏    | 51833/100629 [40:48<37:20, 21.78it/s]

 52%|█████▏    | 51836/100629 [40:48<47:45, 17.03it/s]

 52%|█████▏    | 51839/100629 [40:48<42:38, 19.07it/s]

 52%|█████▏    | 51843/100629 [40:48<36:27, 22.30it/s]

 52%|█████▏    | 51847/100629 [40:48<31:43, 25.63it/s]

 52%|█████▏    | 51850/100629 [40:48<35:52, 22.66it/s]

 52%|█████▏    | 51854/100629 [40:49<32:09, 25.28it/s]

 52%|█████▏    | 51857/100629 [40:49<34:06, 23.83it/s]

 52%|█████▏    | 51860/100629 [40:49<33:01, 24.62it/s]

 52%|█████▏    | 51863/100629 [40:49<34:06, 23.83it/s]

 52%|█████▏    | 51866/100629 [40:49<34:37, 23.48it/s]

 52%|█████▏    | 51870/100629 [40:49<31:52, 25.49it/s]

 52%|█████▏    | 51873/100629 [40:49<38:03, 21.35it/s]

 52%|█████▏    | 51876/100629 [40:50<38:02, 21.36it/s]

 52%|█████▏    | 51879/100629 [40:50<41:00, 19.81it/s]

 52%|█████▏    | 51883/100629 [40:50<34:36, 23.47it/s]

 52%|█████▏    | 51886/100629 [40:50<32:39, 24.88it/s]

 52%|█████▏    | 51889/100629 [40:50<39:22, 20.63it/s]

 52%|█████▏    | 51894/100629 [40:50<30:26, 26.68it/s]

 52%|█████▏    | 51898/100629 [40:51<39:55, 20.34it/s]

 52%|█████▏    | 51901/100629 [40:51<42:42, 19.01it/s]

 52%|█████▏    | 51904/100629 [40:51<46:44, 17.38it/s]

 52%|█████▏    | 51907/100629 [40:51<43:16, 18.76it/s]

 52%|█████▏    | 51910/100629 [40:51<41:24, 19.61it/s]

 52%|█████▏    | 51913/100629 [40:51<47:39, 17.04it/s]

 52%|█████▏    | 51916/100629 [40:52<42:56, 18.91it/s]

 52%|█████▏    | 51919/100629 [40:52<40:09, 20.21it/s]

 52%|█████▏    | 51922/100629 [40:52<42:35, 19.06it/s]

 52%|█████▏    | 51926/100629 [40:52<38:12, 21.25it/s]

 52%|█████▏    | 51929/100629 [40:52<45:47, 17.72it/s]

 52%|█████▏    | 51931/100629 [40:52<46:18, 17.53it/s]

 52%|█████▏    | 51934/100629 [40:52<40:35, 20.00it/s]

 52%|█████▏    | 51937/100629 [40:53<42:05, 19.28it/s]

 52%|█████▏    | 51941/100629 [40:53<36:53, 22.00it/s]

 52%|█████▏    | 51945/100629 [40:53<33:58, 23.88it/s]

 52%|█████▏    | 51948/100629 [40:53<34:27, 23.55it/s]

 52%|█████▏    | 51951/100629 [40:53<36:27, 22.26it/s]

 52%|█████▏    | 51954/100629 [40:53<36:49, 22.03it/s]

 52%|█████▏    | 51957/100629 [40:53<36:06, 22.46it/s]

 52%|█████▏    | 51960/100629 [40:54<45:01, 18.02it/s]

 52%|█████▏    | 51963/100629 [40:54<41:28, 19.56it/s]

 52%|█████▏    | 51967/100629 [40:54<36:20, 22.32it/s]

 52%|█████▏    | 51971/100629 [40:54<31:31, 25.73it/s]

 52%|█████▏    | 51974/100629 [40:54<34:02, 23.82it/s]

 52%|█████▏    | 51977/100629 [40:54<35:59, 22.52it/s]

 52%|█████▏    | 51980/100629 [40:54<34:12, 23.70it/s]

 52%|█████▏    | 51983/100629 [40:55<36:16, 22.35it/s]

 52%|█████▏    | 51986/100629 [40:55<36:55, 21.96it/s]

 52%|█████▏    | 51991/100629 [40:55<35:01, 23.15it/s]

 52%|█████▏    | 51994/100629 [40:55<40:26, 20.04it/s]

 52%|█████▏    | 51999/100629 [40:55<34:42, 23.35it/s]

 52%|█████▏    | 52002/100629 [40:56<38:43, 20.93it/s]

 52%|█████▏    | 52005/100629 [40:56<38:01, 21.31it/s]

 52%|█████▏    | 52008/100629 [40:56<36:30, 22.20it/s]

 52%|█████▏    | 52011/100629 [40:56<34:20, 23.59it/s]

 52%|█████▏    | 52014/100629 [40:56<36:45, 22.05it/s]

 52%|█████▏    | 52017/100629 [40:56<35:25, 22.87it/s]

 52%|█████▏    | 52021/100629 [40:56<31:10, 25.99it/s]

 52%|█████▏    | 52024/100629 [40:56<31:58, 25.33it/s]

 52%|█████▏    | 52027/100629 [40:57<38:09, 21.23it/s]

 52%|█████▏    | 52030/100629 [40:57<44:11, 18.33it/s]

 52%|█████▏    | 52034/100629 [40:57<53:07, 15.25it/s]

 52%|█████▏    | 52037/100629 [40:57<47:29, 17.05it/s]

 52%|█████▏    | 52042/100629 [40:57<35:13, 22.99it/s]

 52%|█████▏    | 52045/100629 [40:57<33:20, 24.29it/s]

 52%|█████▏    | 52048/100629 [40:58<32:06, 25.21it/s]

 52%|█████▏    | 52051/100629 [40:58<38:33, 21.00it/s]

 52%|█████▏    | 52054/100629 [40:58<38:07, 21.23it/s]

 52%|█████▏    | 52058/100629 [40:58<32:02, 25.27it/s]

 52%|█████▏    | 52061/100629 [40:58<30:48, 26.27it/s]

 52%|█████▏    | 52064/100629 [40:58<31:43, 25.52it/s]

 52%|█████▏    | 52067/100629 [40:59<45:35, 17.75it/s]

 52%|█████▏    | 52070/100629 [40:59<40:18, 20.08it/s]

 52%|█████▏    | 52073/100629 [40:59<38:09, 21.21it/s]

 52%|█████▏    | 52077/100629 [40:59<33:57, 23.83it/s]

 52%|█████▏    | 52080/100629 [40:59<35:26, 22.83it/s]

 52%|█████▏    | 52083/100629 [40:59<37:58, 21.31it/s]

 52%|█████▏    | 52086/100629 [40:59<39:32, 20.46it/s]

 52%|█████▏    | 52089/100629 [41:00<44:00, 18.39it/s]

 52%|█████▏    | 52092/100629 [41:00<41:04, 19.70it/s]

 52%|█████▏    | 52095/100629 [41:00<39:33, 20.45it/s]

 52%|█████▏    | 52098/100629 [41:00<38:04, 21.24it/s]

 52%|█████▏    | 52101/100629 [41:00<35:25, 22.83it/s]

 52%|█████▏    | 52104/100629 [41:00<40:26, 20.00it/s]

 52%|█████▏    | 52107/100629 [41:00<39:41, 20.37it/s]

 52%|█████▏    | 52110/100629 [41:01<39:53, 20.27it/s]

 52%|█████▏    | 52113/100629 [41:01<36:16, 22.29it/s]

 52%|█████▏    | 52116/100629 [41:01<37:52, 21.35it/s]

 52%|█████▏    | 52119/100629 [41:01<40:48, 19.81it/s]

 52%|█████▏    | 52122/100629 [41:01<43:58, 18.38it/s]

 52%|█████▏    | 52124/100629 [41:01<43:23, 18.63it/s]

 52%|█████▏    | 52126/100629 [41:01<44:31, 18.16it/s]

 52%|█████▏    | 52129/100629 [41:02<44:30, 18.16it/s]

 52%|█████▏    | 52132/100629 [41:02<40:45, 19.83it/s]

 52%|█████▏    | 52135/100629 [41:02<43:50, 18.44it/s]

 52%|█████▏    | 52138/100629 [41:02<39:17, 20.57it/s]

 52%|█████▏    | 52141/100629 [41:02<38:16, 21.12it/s]

 52%|█████▏    | 52144/100629 [41:02<36:16, 22.28it/s]

 52%|█████▏    | 52147/100629 [41:02<39:20, 20.54it/s]

 52%|█████▏    | 52150/100629 [41:03<43:31, 18.57it/s]

 52%|█████▏    | 52152/100629 [41:03<46:34, 17.35it/s]

 52%|█████▏    | 52156/100629 [41:03<38:32, 20.96it/s]

 52%|█████▏    | 52159/100629 [41:03<43:32, 18.56it/s]

 52%|█████▏    | 52162/100629 [41:03<39:31, 20.44it/s]

 52%|█████▏    | 52165/100629 [41:03<37:10, 21.73it/s]

 52%|█████▏    | 52169/100629 [41:03<34:05, 23.69it/s]

 52%|█████▏    | 52174/100629 [41:04<27:41, 29.17it/s]

 52%|█████▏    | 52178/100629 [41:04<29:35, 27.29it/s]

 52%|█████▏    | 52182/100629 [41:04<29:13, 27.64it/s]

 52%|█████▏    | 52186/100629 [41:04<26:33, 30.40it/s]

 52%|█████▏    | 52190/100629 [41:04<27:16, 29.59it/s]

 52%|█████▏    | 52194/100629 [41:04<25:59, 31.05it/s]

 52%|█████▏    | 52198/100629 [41:04<27:18, 29.56it/s]

 52%|█████▏    | 52202/100629 [41:04<25:13, 32.00it/s]

 52%|█████▏    | 52206/100629 [41:05<28:00, 28.82it/s]

 52%|█████▏    | 52210/100629 [41:05<34:13, 23.57it/s]

 52%|█████▏    | 52213/100629 [41:05<38:51, 20.77it/s]

 52%|█████▏    | 52216/100629 [41:05<40:06, 20.11it/s]

 52%|█████▏    | 52219/100629 [41:05<39:07, 20.62it/s]

 52%|█████▏    | 52222/100629 [41:06<39:57, 20.19it/s]

 52%|█████▏    | 52226/100629 [41:06<34:24, 23.45it/s]

 52%|█████▏    | 52229/100629 [41:06<33:02, 24.41it/s]

 52%|█████▏    | 52233/100629 [41:06<31:30, 25.60it/s]

 52%|█████▏    | 52236/100629 [41:06<34:56, 23.09it/s]

 52%|█████▏    | 52239/100629 [41:06<33:27, 24.11it/s]

 52%|█████▏    | 52243/100629 [41:06<34:49, 23.15it/s]

 52%|█████▏    | 52246/100629 [41:07<40:24, 19.95it/s]

 52%|█████▏    | 52249/100629 [41:07<38:06, 21.16it/s]

 52%|█████▏    | 52252/100629 [41:07<41:58, 19.21it/s]

 52%|█████▏    | 52255/100629 [41:07<39:17, 20.52it/s]

 52%|█████▏    | 52258/100629 [41:07<41:00, 19.66it/s]

 52%|█████▏    | 52261/100629 [41:07<40:03, 20.13it/s]

 52%|█████▏    | 52266/100629 [41:07<31:21, 25.70it/s]

 52%|█████▏    | 52270/100629 [41:08<28:42, 28.08it/s]

 52%|█████▏    | 52273/100629 [41:08<30:48, 26.16it/s]

 52%|█████▏    | 52276/100629 [41:08<34:16, 23.51it/s]

 52%|█████▏    | 52279/100629 [41:08<35:53, 22.45it/s]

 52%|█████▏    | 52283/100629 [41:08<31:40, 25.44it/s]

 52%|█████▏    | 52287/100629 [41:08<32:09, 25.05it/s]

 52%|█████▏    | 52290/100629 [41:08<33:07, 24.32it/s]

 52%|█████▏    | 52293/100629 [41:09<35:26, 22.74it/s]

 52%|█████▏    | 52296/100629 [41:09<36:40, 21.97it/s]

 52%|█████▏    | 52300/100629 [41:09<33:47, 23.84it/s]

 52%|█████▏    | 52303/100629 [41:09<33:49, 23.82it/s]

 52%|█████▏    | 52306/100629 [41:09<32:09, 25.05it/s]

 52%|█████▏    | 52309/100629 [41:09<32:43, 24.61it/s]

 52%|█████▏    | 52312/100629 [41:09<32:10, 25.03it/s]

 52%|█████▏    | 52315/100629 [41:10<40:55, 19.68it/s]

 52%|█████▏    | 52318/100629 [41:10<49:23, 16.30it/s]

 52%|█████▏    | 52322/100629 [41:10<40:55, 19.67it/s]

 52%|█████▏    | 52325/100629 [41:10<40:20, 19.95it/s]

 52%|█████▏    | 52328/100629 [41:10<36:48, 21.87it/s]

 52%|█████▏    | 52331/100629 [41:10<35:24, 22.73it/s]

 52%|█████▏    | 52335/100629 [41:10<31:16, 25.74it/s]

 52%|█████▏    | 52339/100629 [41:11<29:43, 27.07it/s]

 52%|█████▏    | 52344/100629 [41:11<25:24, 31.68it/s]

 52%|█████▏    | 52348/100629 [41:11<25:44, 31.25it/s]

 52%|█████▏    | 52352/100629 [41:11<28:13, 28.50it/s]

 52%|█████▏    | 52355/100629 [41:11<28:47, 27.94it/s]

 52%|█████▏    | 52358/100629 [41:11<35:11, 22.87it/s]

 52%|█████▏    | 52362/100629 [41:11<31:43, 25.36it/s]

 52%|█████▏    | 52365/100629 [41:12<33:55, 23.71it/s]

 52%|█████▏    | 52369/100629 [41:12<34:22, 23.39it/s]

 52%|█████▏    | 52373/100629 [41:12<32:11, 24.99it/s]

 52%|█████▏    | 52376/100629 [41:12<31:57, 25.16it/s]

 52%|█████▏    | 52379/100629 [41:12<31:11, 25.78it/s]

 52%|█████▏    | 52382/100629 [41:12<37:19, 21.54it/s]

 52%|█████▏    | 52385/100629 [41:12<34:45, 23.14it/s]

 52%|█████▏    | 52388/100629 [41:13<35:38, 22.56it/s]

 52%|█████▏    | 52391/100629 [41:13<34:01, 23.63it/s]

 52%|█████▏    | 52395/100629 [41:13<29:16, 27.46it/s]

 52%|█████▏    | 52399/100629 [41:13<29:37, 27.13it/s]

 52%|█████▏    | 52402/100629 [41:13<34:54, 23.02it/s]

 52%|█████▏    | 52405/100629 [41:13<36:21, 22.11it/s]

 52%|█████▏    | 52408/100629 [41:13<40:32, 19.82it/s]

 52%|█████▏    | 52411/100629 [41:14<47:58, 16.75it/s]

 52%|█████▏    | 52413/100629 [41:14<46:38, 17.23it/s]

 52%|█████▏    | 52416/100629 [41:14<44:24, 18.10it/s]

 52%|█████▏    | 52418/100629 [41:14<46:47, 17.17it/s]

 52%|█████▏    | 52422/100629 [41:14<38:12, 21.03it/s]

 52%|█████▏    | 52426/100629 [41:14<38:21, 20.95it/s]

 52%|█████▏    | 52429/100629 [41:15<35:45, 22.47it/s]

 52%|█████▏    | 52432/100629 [41:15<38:33, 20.83it/s]

 52%|█████▏    | 52435/100629 [41:15<38:40, 20.77it/s]

 52%|█████▏    | 52439/100629 [41:15<32:11, 24.95it/s]

 52%|█████▏    | 52442/100629 [41:15<34:14, 23.46it/s]

 52%|█████▏    | 52445/100629 [41:15<39:02, 20.57it/s]

 52%|█████▏    | 52448/100629 [41:15<39:09, 20.51it/s]

 52%|█████▏    | 52451/100629 [41:16<38:54, 20.64it/s]

 52%|█████▏    | 52454/100629 [41:16<36:07, 22.23it/s]

 52%|█████▏    | 52457/100629 [41:16<55:04, 14.58it/s]

 52%|█████▏    | 52460/100629 [41:16<51:24, 15.62it/s]

 52%|█████▏    | 52463/100629 [41:16<51:14, 15.67it/s]

 52%|█████▏    | 52466/100629 [41:17<44:20, 18.10it/s]

 52%|█████▏    | 52469/100629 [41:17<39:46, 20.18it/s]

 52%|█████▏    | 52472/100629 [41:17<46:42, 17.18it/s]

 52%|█████▏    | 52474/100629 [41:17<49:03, 16.36it/s]

 52%|█████▏    | 52477/100629 [41:17<44:01, 18.23it/s]

 52%|█████▏    | 52480/100629 [41:17<41:58, 19.12it/s]

 52%|█████▏    | 52483/100629 [41:17<40:50, 19.64it/s]

 52%|█████▏    | 52486/100629 [41:18<41:28, 19.35it/s]

 52%|█████▏    | 52489/100629 [41:18<41:01, 19.56it/s]

 52%|█████▏    | 52494/100629 [41:18<31:31, 25.45it/s]

 52%|█████▏    | 52497/100629 [41:18<30:33, 26.26it/s]

 52%|█████▏    | 52500/100629 [41:18<30:30, 26.30it/s]

 52%|█████▏    | 52503/100629 [41:18<34:39, 23.14it/s]

 52%|█████▏    | 52506/100629 [41:18<33:31, 23.92it/s]

 52%|█████▏    | 52509/100629 [41:19<38:34, 20.79it/s]

 52%|█████▏    | 52513/100629 [41:19<34:24, 23.31it/s]

 52%|█████▏    | 52518/100629 [41:19<29:22, 27.30it/s]

 52%|█████▏    | 52521/100629 [41:19<37:24, 21.43it/s]

 52%|█████▏    | 52525/100629 [41:19<34:14, 23.42it/s]

 52%|█████▏    | 52528/100629 [41:19<41:38, 19.25it/s]

 52%|█████▏    | 52531/100629 [41:20<39:32, 20.28it/s]

 52%|█████▏    | 52534/100629 [41:20<53:56, 14.86it/s]

 52%|█████▏    | 52536/100629 [41:20<52:27, 15.28it/s]

 52%|█████▏    | 52539/100629 [41:20<46:12, 17.35it/s]

 52%|█████▏    | 52541/100629 [41:20<46:35, 17.20it/s]

 52%|█████▏    | 52544/100629 [41:20<43:24, 18.46it/s]

 52%|█████▏    | 52548/100629 [41:20<35:29, 22.58it/s]

 52%|█████▏    | 52551/100629 [41:21<40:59, 19.55it/s]

 52%|█████▏    | 52555/100629 [41:21<40:49, 19.63it/s]

 52%|█████▏    | 52558/100629 [41:21<40:12, 19.93it/s]

 52%|█████▏    | 52561/100629 [41:21<43:04, 18.60it/s]

 52%|█████▏    | 52563/100629 [41:21<43:06, 18.59it/s]

 52%|█████▏    | 52565/100629 [41:21<43:55, 18.24it/s]

 52%|█████▏    | 52569/100629 [41:22<37:05, 21.59it/s]

 52%|█████▏    | 52572/100629 [41:22<37:06, 21.58it/s]

 52%|█████▏    | 52575/100629 [41:22<36:55, 21.69it/s]

 52%|█████▏    | 52578/100629 [41:22<37:32, 21.34it/s]

 52%|█████▏    | 52582/100629 [41:22<35:24, 22.61it/s]

 52%|█████▏    | 52585/100629 [41:22<34:40, 23.09it/s]

 52%|█████▏    | 52588/100629 [41:22<32:29, 24.65it/s]

 52%|█████▏    | 52591/100629 [41:23<34:38, 23.11it/s]

 52%|█████▏    | 52594/100629 [41:23<33:01, 24.24it/s]

 52%|█████▏    | 52599/100629 [41:23<28:30, 28.09it/s]

 52%|█████▏    | 52602/100629 [41:23<34:30, 23.19it/s]

 52%|█████▏    | 52605/100629 [41:23<39:49, 20.10it/s]

 52%|█████▏    | 52608/100629 [41:23<39:59, 20.01it/s]

 52%|█████▏    | 52611/100629 [41:24<44:51, 17.84it/s]

 52%|█████▏    | 52614/100629 [41:24<39:41, 20.16it/s]

 52%|█████▏    | 52617/100629 [41:24<37:25, 21.38it/s]

 52%|█████▏    | 52622/100629 [41:24<33:48, 23.67it/s]

 52%|█████▏    | 52625/100629 [41:24<32:05, 24.93it/s]

 52%|█████▏    | 52629/100629 [41:24<28:46, 27.80it/s]

 52%|█████▏    | 52632/100629 [41:24<28:14, 28.32it/s]

 52%|█████▏    | 52637/100629 [41:24<24:48, 32.24it/s]

 52%|█████▏    | 52641/100629 [41:25<29:45, 26.88it/s]

 52%|█████▏    | 52644/100629 [41:25<29:04, 27.50it/s]

 52%|█████▏    | 52647/100629 [41:25<34:50, 22.95it/s]

 52%|█████▏    | 52650/100629 [41:25<38:03, 21.02it/s]

 52%|█████▏    | 52654/100629 [41:25<36:35, 21.85it/s]

 52%|█████▏    | 52657/100629 [41:25<41:43, 19.17it/s]

 52%|█████▏    | 52660/100629 [41:26<42:20, 18.88it/s]

 52%|█████▏    | 52663/100629 [41:26<38:12, 20.92it/s]

 52%|█████▏    | 52666/100629 [41:26<41:43, 19.16it/s]

 52%|█████▏    | 52670/100629 [41:26<36:58, 21.62it/s]

 52%|█████▏    | 52673/100629 [41:26<39:40, 20.14it/s]

 52%|█████▏    | 52676/100629 [41:26<41:31, 19.25it/s]

 52%|█████▏    | 52678/100629 [41:26<42:27, 18.82it/s]

 52%|█████▏    | 52681/100629 [41:27<39:28, 20.24it/s]

 52%|█████▏    | 52684/100629 [41:27<39:49, 20.07it/s]

 52%|█████▏    | 52687/100629 [41:27<39:09, 20.41it/s]

 52%|█████▏    | 52690/100629 [41:27<35:51, 22.29it/s]

 52%|█████▏    | 52693/100629 [41:27<34:17, 23.29it/s]

 52%|█████▏    | 52696/100629 [41:27<32:55, 24.27it/s]

 52%|█████▏    | 52699/100629 [41:27<33:20, 23.95it/s]

 52%|█████▏    | 52702/100629 [41:27<32:55, 24.26it/s]

 52%|█████▏    | 52705/100629 [41:28<35:16, 22.64it/s]

 52%|█████▏    | 52710/100629 [41:28<29:21, 27.21it/s]

 52%|█████▏    | 52713/100629 [41:28<31:32, 25.32it/s]

 52%|█████▏    | 52716/100629 [41:28<37:11, 21.47it/s]

 52%|█████▏    | 52719/100629 [41:28<41:30, 19.24it/s]

 52%|█████▏    | 52722/100629 [41:28<38:59, 20.48it/s]

 52%|█████▏    | 52725/100629 [41:29<44:33, 17.92it/s]

 52%|█████▏    | 52727/100629 [41:29<44:19, 18.01it/s]

 52%|█████▏    | 52731/100629 [41:29<36:08, 22.09it/s]

 52%|█████▏    | 52734/100629 [41:29<40:26, 19.74it/s]

 52%|█████▏    | 52737/100629 [41:29<44:55, 17.76it/s]

 52%|█████▏    | 52740/100629 [41:29<43:47, 18.23it/s]

 52%|█████▏    | 52743/100629 [41:30<39:53, 20.01it/s]

 52%|█████▏    | 52747/100629 [41:30<34:14, 23.31it/s]

 52%|█████▏    | 52750/100629 [41:30<32:53, 24.26it/s]

 52%|█████▏    | 52753/100629 [41:30<34:17, 23.27it/s]

 52%|█████▏    | 52756/100629 [41:30<40:10, 19.86it/s]

 52%|█████▏    | 52759/100629 [41:30<39:21, 20.27it/s]

 52%|█████▏    | 52763/100629 [41:30<34:32, 23.10it/s]

 52%|█████▏    | 52767/100629 [41:31<31:09, 25.60it/s]

 52%|█████▏    | 52770/100629 [41:31<35:00, 22.79it/s]

 52%|█████▏    | 52773/100629 [41:31<38:38, 20.64it/s]

 52%|█████▏    | 52776/100629 [41:31<38:31, 20.70it/s]

 52%|█████▏    | 52780/100629 [41:31<33:21, 23.91it/s]

 52%|█████▏    | 52783/100629 [41:31<36:42, 21.72it/s]

 52%|█████▏    | 52786/100629 [41:31<38:17, 20.82it/s]

 52%|█████▏    | 52789/100629 [41:32<37:56, 21.01it/s]

 52%|█████▏    | 52792/100629 [41:32<43:46, 18.21it/s]

 52%|█████▏    | 52796/100629 [41:32<36:05, 22.09it/s]

 52%|█████▏    | 52799/100629 [41:32<35:14, 22.62it/s]

 52%|█████▏    | 52803/100629 [41:32<33:51, 23.54it/s]

 52%|█████▏    | 52806/100629 [41:32<37:11, 21.43it/s]

 52%|█████▏    | 52809/100629 [41:33<39:48, 20.02it/s]

 52%|█████▏    | 52812/100629 [41:33<40:51, 19.51it/s]

 52%|█████▏    | 52815/100629 [41:33<40:38, 19.61it/s]

 52%|█████▏    | 52817/100629 [41:33<45:56, 17.34it/s]

 52%|█████▏    | 52820/100629 [41:33<43:17, 18.40it/s]

 52%|█████▏    | 52823/100629 [41:33<43:12, 18.44it/s]

 52%|█████▏    | 52827/100629 [41:33<35:24, 22.50it/s]

 52%|█████▏    | 52830/100629 [41:34<35:45, 22.28it/s]

 53%|█████▎    | 52833/100629 [41:34<38:34, 20.65it/s]

 53%|█████▎    | 52836/100629 [41:34<37:45, 21.09it/s]

 53%|█████▎    | 52839/100629 [41:34<42:22, 18.80it/s]

 53%|█████▎    | 52842/100629 [41:34<44:58, 17.71it/s]

 53%|█████▎    | 52845/100629 [41:34<39:48, 20.00it/s]

 53%|█████▎    | 52848/100629 [41:35<36:40, 21.72it/s]

 53%|█████▎    | 52852/100629 [41:35<32:12, 24.72it/s]

 53%|█████▎    | 52855/100629 [41:35<33:30, 23.77it/s]

 53%|█████▎    | 52858/100629 [41:35<32:21, 24.60it/s]

 53%|█████▎    | 52861/100629 [41:35<41:59, 18.96it/s]

 53%|█████▎    | 52865/100629 [41:35<34:26, 23.12it/s]

 53%|█████▎    | 52868/100629 [41:35<37:45, 21.08it/s]

 53%|█████▎    | 52874/100629 [41:36<28:34, 27.86it/s]

 53%|█████▎    | 52878/100629 [41:36<32:23, 24.58it/s]

 53%|█████▎    | 52881/100629 [41:36<38:02, 20.92it/s]

 53%|█████▎    | 52884/100629 [41:36<36:58, 21.52it/s]

 53%|█████▎    | 52887/100629 [41:36<39:29, 20.15it/s]

 53%|█████▎    | 52891/100629 [41:36<33:14, 23.94it/s]

 53%|█████▎    | 52894/100629 [41:36<31:29, 25.26it/s]

 53%|█████▎    | 52897/100629 [41:37<31:11, 25.51it/s]

 53%|█████▎    | 52900/100629 [41:37<35:16, 22.55it/s]

 53%|█████▎    | 52903/100629 [41:37<34:59, 22.74it/s]

 53%|█████▎    | 52906/100629 [41:37<38:45, 20.52it/s]

 53%|█████▎    | 52909/100629 [41:37<45:56, 17.31it/s]

 53%|█████▎    | 52911/100629 [41:37<45:41, 17.41it/s]

 53%|█████▎    | 52915/100629 [41:38<40:14, 19.76it/s]

 53%|█████▎    | 52919/100629 [41:38<35:49, 22.20it/s]

 53%|█████▎    | 52922/100629 [41:38<35:59, 22.09it/s]

 53%|█████▎    | 52925/100629 [41:38<36:36, 21.71it/s]

 53%|█████▎    | 52929/100629 [41:38<36:26, 21.81it/s]

 53%|█████▎    | 52932/100629 [41:38<38:37, 20.58it/s]

 53%|█████▎    | 52935/100629 [41:38<37:56, 20.95it/s]

 53%|█████▎    | 52938/100629 [41:39<39:48, 19.97it/s]

 53%|█████▎    | 52941/100629 [41:39<41:30, 19.15it/s]

 53%|█████▎    | 52944/100629 [41:39<38:21, 20.72it/s]

 53%|█████▎    | 52947/100629 [41:39<38:05, 20.87it/s]

 53%|█████▎    | 52950/100629 [41:39<39:49, 19.95it/s]

 53%|█████▎    | 52953/100629 [41:39<41:04, 19.34it/s]

 53%|█████▎    | 52956/100629 [41:40<40:38, 19.55it/s]

 53%|█████▎    | 52958/100629 [41:40<42:13, 18.82it/s]

 53%|█████▎    | 52960/100629 [41:40<41:58, 18.93it/s]

 53%|█████▎    | 52963/100629 [41:40<38:43, 20.51it/s]

 53%|█████▎    | 52966/100629 [41:40<35:34, 22.33it/s]

 53%|█████▎    | 52969/100629 [41:40<38:41, 20.53it/s]

 53%|█████▎    | 52973/100629 [41:40<36:27, 21.79it/s]

 53%|█████▎    | 52976/100629 [41:41<38:34, 20.59it/s]

 53%|█████▎    | 52979/100629 [41:41<37:18, 21.28it/s]

 53%|█████▎    | 52982/100629 [41:41<40:29, 19.61it/s]

 53%|█████▎    | 52987/100629 [41:41<32:24, 24.50it/s]

 53%|█████▎    | 52990/100629 [41:41<40:19, 19.69it/s]

 53%|█████▎    | 52993/100629 [41:41<43:49, 18.12it/s]

 53%|█████▎    | 52996/100629 [41:42<40:56, 19.39it/s]

 53%|█████▎    | 52999/100629 [41:42<38:35, 20.57it/s]

 53%|█████▎    | 53002/100629 [41:42<37:51, 20.96it/s]

 53%|█████▎    | 53007/100629 [41:42<29:18, 27.08it/s]

 53%|█████▎    | 53011/100629 [41:42<29:55, 26.53it/s]

 53%|█████▎    | 53014/100629 [41:42<35:28, 22.37it/s]

 53%|█████▎    | 53019/100629 [41:42<29:28, 26.92it/s]

 53%|█████▎    | 53022/100629 [41:42<30:25, 26.08it/s]

 53%|█████▎    | 53025/100629 [41:43<36:26, 21.78it/s]

 53%|█████▎    | 53028/100629 [41:43<34:09, 23.22it/s]

 53%|█████▎    | 53031/100629 [41:43<36:14, 21.89it/s]

 53%|█████▎    | 53034/100629 [41:43<36:33, 21.70it/s]

 53%|█████▎    | 53037/100629 [41:43<36:14, 21.89it/s]

 53%|█████▎    | 53040/100629 [41:43<36:23, 21.79it/s]

 53%|█████▎    | 53044/100629 [41:43<31:14, 25.39it/s]

 53%|█████▎    | 53048/100629 [41:44<32:14, 24.59it/s]

 53%|█████▎    | 53051/100629 [41:44<32:45, 24.21it/s]

 53%|█████▎    | 53054/100629 [41:44<35:36, 22.27it/s]

 53%|█████▎    | 53057/100629 [41:44<39:28, 20.08it/s]

 53%|█████▎    | 53061/100629 [41:44<33:21, 23.77it/s]

 53%|█████▎    | 53064/100629 [41:44<34:25, 23.03it/s]

 53%|█████▎    | 53068/100629 [41:44<30:00, 26.41it/s]

 53%|█████▎    | 53071/100629 [41:45<35:43, 22.19it/s]

 53%|█████▎    | 53074/100629 [41:45<38:39, 20.50it/s]

 53%|█████▎    | 53077/100629 [41:45<43:23, 18.26it/s]

 53%|█████▎    | 53079/100629 [41:45<43:51, 18.07it/s]

 53%|█████▎    | 53083/100629 [41:45<35:54, 22.07it/s]

 53%|█████▎    | 53086/100629 [41:45<34:37, 22.89it/s]

 53%|█████▎    | 53091/100629 [41:46<29:17, 27.05it/s]

 53%|█████▎    | 53094/100629 [41:46<31:31, 25.13it/s]

 53%|█████▎    | 53097/100629 [41:46<30:26, 26.03it/s]

 53%|█████▎    | 53101/100629 [41:46<28:54, 27.40it/s]

 53%|█████▎    | 53104/100629 [41:46<28:47, 27.51it/s]

 53%|█████▎    | 53107/100629 [41:46<30:54, 25.63it/s]

 53%|█████▎    | 53110/100629 [41:46<30:36, 25.88it/s]

 53%|█████▎    | 53113/100629 [41:46<33:38, 23.54it/s]

 53%|█████▎    | 53116/100629 [41:47<34:05, 23.23it/s]

 53%|█████▎    | 53119/100629 [41:47<35:43, 22.17it/s]

 53%|█████▎    | 53123/100629 [41:47<33:44, 23.46it/s]

 53%|█████▎    | 53126/100629 [41:47<32:53, 24.07it/s]

 53%|█████▎    | 53130/100629 [41:47<28:39, 27.62it/s]

 53%|█████▎    | 53133/100629 [41:47<34:06, 23.21it/s]

 53%|█████▎    | 53136/100629 [41:47<33:08, 23.89it/s]

 53%|█████▎    | 53139/100629 [41:48<39:38, 19.97it/s]

 53%|█████▎    | 53142/100629 [41:48<39:32, 20.01it/s]

 53%|█████▎    | 53145/100629 [41:48<40:20, 19.62it/s]

 53%|█████▎    | 53148/100629 [41:48<38:55, 20.33it/s]

 53%|█████▎    | 53151/100629 [41:48<37:53, 20.88it/s]

 53%|█████▎    | 53154/100629 [41:48<40:55, 19.33it/s]

 53%|█████▎    | 53156/100629 [41:49<43:01, 18.39it/s]

 53%|█████▎    | 53160/100629 [41:49<36:55, 21.43it/s]

 53%|█████▎    | 53165/100629 [41:49<33:41, 23.48it/s]

 53%|█████▎    | 53168/100629 [41:49<38:31, 20.53it/s]

 53%|█████▎    | 53172/100629 [41:49<34:02, 23.24it/s]

 53%|█████▎    | 53175/100629 [41:49<33:33, 23.57it/s]

 53%|█████▎    | 53178/100629 [41:49<32:27, 24.36it/s]

 53%|█████▎    | 53181/100629 [41:50<39:42, 19.91it/s]

 53%|█████▎    | 53185/100629 [41:50<36:02, 21.94it/s]

 53%|█████▎    | 53188/100629 [41:50<37:53, 20.86it/s]

 53%|█████▎    | 53191/100629 [41:50<34:57, 22.62it/s]

 53%|█████▎    | 53194/100629 [41:50<33:41, 23.46it/s]

 53%|█████▎    | 53197/100629 [41:50<35:41, 22.15it/s]

 53%|█████▎    | 53200/100629 [41:50<38:54, 20.31it/s]

 53%|█████▎    | 53203/100629 [41:51<39:53, 19.81it/s]

 53%|█████▎    | 53207/100629 [41:51<32:55, 24.01it/s]

 53%|█████▎    | 53210/100629 [41:51<32:38, 24.21it/s]

 53%|█████▎    | 53215/100629 [41:51<31:39, 24.96it/s]

 53%|█████▎    | 53219/100629 [41:51<31:37, 24.98it/s]

 53%|█████▎    | 53222/100629 [41:51<33:46, 23.39it/s]

 53%|█████▎    | 53225/100629 [41:52<39:07, 20.19it/s]

 53%|█████▎    | 53229/100629 [41:52<34:12, 23.10it/s]

 53%|█████▎    | 53232/100629 [41:52<33:13, 23.77it/s]

 53%|█████▎    | 53235/100629 [41:52<35:09, 22.46it/s]

 53%|█████▎    | 53238/100629 [41:52<36:52, 21.42it/s]

 53%|█████▎    | 53241/100629 [41:52<37:04, 21.30it/s]

 53%|█████▎    | 53244/100629 [41:52<35:14, 22.41it/s]

 53%|█████▎    | 53247/100629 [41:52<33:15, 23.75it/s]

 53%|█████▎    | 53250/100629 [41:53<36:54, 21.39it/s]

 53%|█████▎    | 53253/100629 [41:53<35:24, 22.29it/s]

 53%|█████▎    | 53257/100629 [41:53<32:22, 24.38it/s]

 53%|█████▎    | 53260/100629 [41:53<30:54, 25.54it/s]

 53%|█████▎    | 53263/100629 [41:53<33:20, 23.67it/s]

 53%|█████▎    | 53267/100629 [41:53<29:04, 27.15it/s]

 53%|█████▎    | 53270/100629 [41:53<30:42, 25.71it/s]

 53%|█████▎    | 53273/100629 [41:54<31:50, 24.79it/s]

 53%|█████▎    | 53276/100629 [41:54<34:32, 22.85it/s]

 53%|█████▎    | 53279/100629 [41:54<34:47, 22.68it/s]

 53%|█████▎    | 53282/100629 [41:54<34:46, 22.69it/s]

 53%|█████▎    | 53285/100629 [41:54<36:13, 21.78it/s]

 53%|█████▎    | 53288/100629 [41:54<39:21, 20.05it/s]

 53%|█████▎    | 53291/100629 [41:55<48:14, 16.36it/s]

 53%|█████▎    | 53294/100629 [41:55<47:37, 16.57it/s]

 53%|█████▎    | 53297/100629 [41:55<41:49, 18.86it/s]

 53%|█████▎    | 53301/100629 [41:55<37:38, 20.96it/s]

 53%|█████▎    | 53304/100629 [41:55<34:28, 22.88it/s]

 53%|█████▎    | 53307/100629 [41:55<47:20, 16.66it/s]

 53%|█████▎    | 53312/100629 [41:56<38:10, 20.65it/s]

 53%|█████▎    | 53315/100629 [41:56<36:48, 21.43it/s]

 53%|█████▎    | 53318/100629 [41:56<35:56, 21.94it/s]

 53%|█████▎    | 53322/100629 [41:56<30:52, 25.54it/s]

 53%|█████▎    | 53326/100629 [41:56<27:39, 28.50it/s]

 53%|█████▎    | 53330/100629 [41:56<32:25, 24.31it/s]

 53%|█████▎    | 53333/100629 [41:56<39:09, 20.13it/s]

 53%|█████▎    | 53336/100629 [41:57<38:20, 20.56it/s]

 53%|█████▎    | 53339/100629 [41:57<41:15, 19.10it/s]

 53%|█████▎    | 53342/100629 [41:57<37:02, 21.28it/s]

 53%|█████▎    | 53345/100629 [41:57<39:31, 19.94it/s]

 53%|█████▎    | 53348/100629 [41:57<40:05, 19.66it/s]

 53%|█████▎    | 53351/100629 [41:57<47:38, 16.54it/s]

 53%|█████▎    | 53353/100629 [41:58<53:57, 14.60it/s]

 53%|█████▎    | 53355/100629 [41:58<57:36, 13.68it/s]

 53%|█████▎    | 53357/100629 [41:58<57:10, 13.78it/s]

 53%|█████▎    | 53361/100629 [41:58<43:45, 18.00it/s]

 53%|█████▎    | 53365/100629 [41:58<36:01, 21.87it/s]

 53%|█████▎    | 53368/100629 [41:58<36:37, 21.50it/s]

 53%|█████▎    | 53371/100629 [41:59<36:49, 21.39it/s]

 53%|█████▎    | 53374/100629 [41:59<38:40, 20.36it/s]

 53%|█████▎    | 53377/100629 [41:59<39:50, 19.76it/s]

 53%|█████▎    | 53382/100629 [41:59<32:29, 24.24it/s]

 53%|█████▎    | 53385/100629 [41:59<41:19, 19.05it/s]

 53%|█████▎    | 53388/100629 [41:59<42:10, 18.67it/s]

 53%|█████▎    | 53391/100629 [42:00<41:16, 19.08it/s]

 53%|█████▎    | 53394/100629 [42:00<42:00, 18.74it/s]

 53%|█████▎    | 53397/100629 [42:00<49:02, 16.05it/s]

 53%|█████▎    | 53400/100629 [42:00<43:05, 18.26it/s]

 53%|█████▎    | 53403/100629 [42:00<44:23, 17.73it/s]

 53%|█████▎    | 53406/100629 [42:00<43:40, 18.02it/s]

 53%|█████▎    | 53410/100629 [42:01<38:42, 20.33it/s]

 53%|█████▎    | 53413/100629 [42:01<42:21, 18.58it/s]

 53%|█████▎    | 53415/100629 [42:01<44:52, 17.54it/s]

 53%|█████▎    | 53418/100629 [42:01<44:37, 17.63it/s]

 53%|█████▎    | 53421/100629 [42:01<43:15, 18.19it/s]

 53%|█████▎    | 53424/100629 [42:01<39:21, 19.99it/s]

 53%|█████▎    | 53427/100629 [42:01<37:51, 20.78it/s]

 53%|█████▎    | 53431/100629 [42:02<34:31, 22.78it/s]

 53%|█████▎    | 53434/100629 [42:02<39:25, 19.95it/s]

 53%|█████▎    | 53437/100629 [42:02<36:57, 21.28it/s]

 53%|█████▎    | 53440/100629 [42:02<37:16, 21.10it/s]

 53%|█████▎    | 53445/100629 [42:02<29:31, 26.64it/s]

 53%|█████▎    | 53450/100629 [42:02<26:57, 29.17it/s]

 53%|█████▎    | 53454/100629 [42:03<29:10, 26.94it/s]

 53%|█████▎    | 53458/100629 [42:03<28:15, 27.82it/s]

 53%|█████▎    | 53462/100629 [42:03<32:12, 24.40it/s]

 53%|█████▎    | 53468/100629 [42:03<25:05, 31.33it/s]

 53%|█████▎    | 53472/100629 [42:03<28:26, 27.63it/s]

 53%|█████▎    | 53476/100629 [42:03<29:39, 26.50it/s]

 53%|█████▎    | 53479/100629 [42:04<35:28, 22.15it/s]

 53%|█████▎    | 53482/100629 [42:04<35:49, 21.94it/s]

 53%|█████▎    | 53485/100629 [42:04<38:21, 20.48it/s]

 53%|█████▎    | 53488/100629 [42:04<38:54, 20.19it/s]

 53%|█████▎    | 53491/100629 [42:04<42:44, 18.38it/s]

 53%|█████▎    | 53494/100629 [42:04<39:31, 19.87it/s]

 53%|█████▎    | 53497/100629 [42:04<36:23, 21.58it/s]

 53%|█████▎    | 53502/100629 [42:05<28:53, 27.19it/s]

 53%|█████▎    | 53505/100629 [42:05<33:42, 23.31it/s]

 53%|█████▎    | 53508/100629 [42:05<37:11, 21.11it/s]

 53%|█████▎    | 53511/100629 [42:05<35:42, 21.99it/s]

 53%|█████▎    | 53514/100629 [42:05<42:31, 18.46it/s]

 53%|█████▎    | 53517/100629 [42:05<38:53, 20.19it/s]

 53%|█████▎    | 53520/100629 [42:06<41:20, 18.99it/s]

 53%|█████▎    | 53524/100629 [42:06<35:45, 21.96it/s]

 53%|█████▎    | 53527/100629 [42:06<36:57, 21.24it/s]

 53%|█████▎    | 53532/100629 [42:06<31:21, 25.03it/s]

 53%|█████▎    | 53536/100629 [42:06<29:11, 26.88it/s]

 53%|█████▎    | 53539/100629 [42:06<31:48, 24.67it/s]

 53%|█████▎    | 53542/100629 [42:06<37:10, 21.11it/s]

 53%|█████▎    | 53545/100629 [42:07<37:48, 20.75it/s]

 53%|█████▎    | 53548/100629 [42:07<39:21, 19.93it/s]

 53%|█████▎    | 53551/100629 [42:07<38:53, 20.18it/s]

 53%|█████▎    | 53554/100629 [42:07<41:11, 19.05it/s]

 53%|█████▎    | 53556/100629 [42:07<43:52, 17.88it/s]

 53%|█████▎    | 53560/100629 [42:07<37:12, 21.09it/s]

 53%|█████▎    | 53563/100629 [42:08<38:00, 20.64it/s]

 53%|█████▎    | 53566/100629 [42:08<38:31, 20.36it/s]

 53%|█████▎    | 53570/100629 [42:08<32:27, 24.17it/s]

 53%|█████▎    | 53573/100629 [42:08<32:38, 24.03it/s]

 53%|█████▎    | 53576/100629 [42:08<31:55, 24.57it/s]

 53%|█████▎    | 53579/100629 [42:08<32:35, 24.06it/s]

 53%|█████▎    | 53582/100629 [42:08<37:31, 20.89it/s]

 53%|█████▎    | 53585/100629 [42:08<36:15, 21.63it/s]

 53%|█████▎    | 53588/100629 [42:09<35:20, 22.19it/s]

 53%|█████▎    | 53591/100629 [42:09<33:42, 23.26it/s]

 53%|█████▎    | 53594/100629 [42:09<32:43, 23.95it/s]

 53%|█████▎    | 53598/100629 [42:09<33:41, 23.26it/s]

 53%|█████▎    | 53602/100629 [42:09<31:06, 25.19it/s]

 53%|█████▎    | 53605/100629 [42:09<39:49, 19.68it/s]

 53%|█████▎    | 53608/100629 [42:09<36:05, 21.72it/s]

 53%|█████▎    | 53611/100629 [42:10<44:58, 17.42it/s]

 53%|█████▎    | 53615/100629 [42:10<36:39, 21.38it/s]

 53%|█████▎    | 53618/100629 [42:10<35:43, 21.94it/s]

 53%|█████▎    | 53621/100629 [42:10<34:19, 22.83it/s]

 53%|█████▎    | 53624/100629 [42:10<37:33, 20.86it/s]

 53%|█████▎    | 53627/100629 [42:10<40:25, 19.38it/s]

 53%|█████▎    | 53630/100629 [42:11<39:29, 19.84it/s]

 53%|█████▎    | 53633/100629 [42:11<36:18, 21.57it/s]

 53%|█████▎    | 53637/100629 [42:11<32:11, 24.33it/s]

 53%|█████▎    | 53640/100629 [42:11<38:10, 20.52it/s]

 53%|█████▎    | 53643/100629 [42:11<36:19, 21.56it/s]

 53%|█████▎    | 53646/100629 [42:11<35:50, 21.85it/s]

 53%|█████▎    | 53649/100629 [42:11<34:44, 22.54it/s]

 53%|█████▎    | 53653/100629 [42:12<33:18, 23.50it/s]

 53%|█████▎    | 53656/100629 [42:12<34:59, 22.37it/s]

 53%|█████▎    | 53659/100629 [42:12<35:07, 22.29it/s]

 53%|█████▎    | 53662/100629 [42:12<33:46, 23.18it/s]

 53%|█████▎    | 53665/100629 [42:12<35:07, 22.28it/s]

 53%|█████▎    | 53668/100629 [42:12<32:57, 23.75it/s]

 53%|█████▎    | 53671/100629 [42:12<33:48, 23.14it/s]

 53%|█████▎    | 53674/100629 [42:13<34:02, 22.99it/s]

 53%|█████▎    | 53678/100629 [42:13<33:05, 23.65it/s]

 53%|█████▎    | 53682/100629 [42:13<29:13, 26.77it/s]

 53%|█████▎    | 53685/100629 [42:13<30:53, 25.33it/s]

 53%|█████▎    | 53688/100629 [42:13<36:02, 21.71it/s]

 53%|█████▎    | 53691/100629 [42:13<35:39, 21.94it/s]

 53%|█████▎    | 53694/100629 [42:13<38:07, 20.51it/s]

 53%|█████▎    | 53697/100629 [42:14<35:45, 21.87it/s]

 53%|█████▎    | 53700/100629 [42:14<37:36, 20.79it/s]

 53%|█████▎    | 53703/100629 [42:14<37:13, 21.01it/s]

 53%|█████▎    | 53706/100629 [42:14<39:39, 19.72it/s]

 53%|█████▎    | 53711/100629 [42:14<32:40, 23.93it/s]

 53%|█████▎    | 53714/100629 [42:14<37:49, 20.67it/s]

 53%|█████▎    | 53717/100629 [42:14<35:08, 22.25it/s]

 53%|█████▎    | 53721/100629 [42:15<32:51, 23.80it/s]

 53%|█████▎    | 53724/100629 [42:15<33:51, 23.09it/s]

 53%|█████▎    | 53727/100629 [42:15<37:20, 20.93it/s]

 53%|█████▎    | 53731/100629 [42:15<31:12, 25.05it/s]

 53%|█████▎    | 53734/100629 [42:15<31:49, 24.56it/s]

 53%|█████▎    | 53737/100629 [42:15<30:47, 25.38it/s]

 53%|█████▎    | 53740/100629 [42:15<36:09, 21.61it/s]

 53%|█████▎    | 53743/100629 [42:16<49:22, 15.83it/s]

 53%|█████▎    | 53745/100629 [42:16<49:49, 15.68it/s]

 53%|█████▎    | 53748/100629 [42:16<43:35, 17.92it/s]

 53%|█████▎    | 53751/100629 [42:16<40:38, 19.23it/s]

 53%|█████▎    | 53754/100629 [42:16<45:02, 17.34it/s]

 53%|█████▎    | 53757/100629 [42:16<40:42, 19.19it/s]

 53%|█████▎    | 53760/100629 [42:17<36:41, 21.29it/s]

 53%|█████▎    | 53763/100629 [42:17<37:52, 20.63it/s]

 53%|█████▎    | 53766/100629 [42:17<41:01, 19.04it/s]

 53%|█████▎    | 53769/100629 [42:17<40:03, 19.50it/s]

 53%|█████▎    | 53772/100629 [42:17<37:19, 20.93it/s]

 53%|█████▎    | 53775/100629 [42:17<34:54, 22.37it/s]

 53%|█████▎    | 53778/100629 [42:17<37:46, 20.67it/s]

 53%|█████▎    | 53781/100629 [42:18<36:47, 21.23it/s]

 53%|█████▎    | 53784/100629 [42:18<37:12, 20.99it/s]

 53%|█████▎    | 53787/100629 [42:18<34:48, 22.43it/s]

 53%|█████▎    | 53790/100629 [42:18<40:15, 19.39it/s]

 53%|█████▎    | 53793/100629 [42:18<42:47, 18.24it/s]

 53%|█████▎    | 53795/100629 [42:18<46:13, 16.88it/s]

 53%|█████▎    | 53798/100629 [42:19<41:31, 18.80it/s]

 53%|█████▎    | 53800/100629 [42:19<44:17, 17.62it/s]

 53%|█████▎    | 53804/100629 [42:19<35:38, 21.90it/s]

 53%|█████▎    | 53808/100629 [42:19<30:12, 25.84it/s]

 53%|█████▎    | 53812/100629 [42:19<31:49, 24.52it/s]

 53%|█████▎    | 53815/100629 [42:19<35:36, 21.91it/s]

 53%|█████▎    | 53819/100629 [42:19<32:16, 24.18it/s]

 53%|█████▎    | 53822/100629 [42:20<34:15, 22.77it/s]

 53%|█████▎    | 53825/100629 [42:20<37:20, 20.89it/s]

 53%|█████▎    | 53828/100629 [42:20<37:40, 20.70it/s]

 53%|█████▎    | 53831/100629 [42:20<38:58, 20.01it/s]

 53%|█████▎    | 53834/100629 [42:20<36:12, 21.54it/s]

 54%|█████▎    | 53838/100629 [42:20<32:26, 24.04it/s]

 54%|█████▎    | 53841/100629 [42:20<34:21, 22.70it/s]

 54%|█████▎    | 53844/100629 [42:21<41:12, 18.92it/s]

 54%|█████▎    | 53850/100629 [42:21<30:27, 25.60it/s]

 54%|█████▎    | 53853/100629 [42:21<30:33, 25.51it/s]

 54%|█████▎    | 53857/100629 [42:21<29:27, 26.46it/s]

 54%|█████▎    | 53860/100629 [42:21<31:10, 25.00it/s]

 54%|█████▎    | 53863/100629 [42:21<31:38, 24.64it/s]

 54%|█████▎    | 53869/100629 [42:21<23:57, 32.53it/s]

 54%|█████▎    | 53873/100629 [42:22<27:27, 28.38it/s]

 54%|█████▎    | 53877/100629 [42:22<27:07, 28.73it/s]

 54%|█████▎    | 53881/100629 [42:22<26:57, 28.89it/s]

 54%|█████▎    | 53885/100629 [42:22<29:33, 26.35it/s]

 54%|█████▎    | 53888/100629 [42:22<31:06, 25.05it/s]

 54%|█████▎    | 53891/100629 [42:22<36:51, 21.14it/s]

 54%|█████▎    | 53894/100629 [42:23<39:35, 19.67it/s]

 54%|█████▎    | 53897/100629 [42:23<38:22, 20.30it/s]

 54%|█████▎    | 53900/100629 [42:23<40:33, 19.20it/s]

 54%|█████▎    | 53902/100629 [42:23<42:18, 18.41it/s]

 54%|█████▎    | 53904/100629 [42:23<42:06, 18.49it/s]

 54%|█████▎    | 53908/100629 [42:23<34:21, 22.67it/s]

 54%|█████▎    | 53911/100629 [42:23<34:49, 22.36it/s]

 54%|█████▎    | 53914/100629 [42:24<36:33, 21.30it/s]

 54%|█████▎    | 53917/100629 [42:24<35:39, 21.83it/s]

 54%|█████▎    | 53920/100629 [42:24<32:46, 23.76it/s]

 54%|█████▎    | 53923/100629 [42:24<34:47, 22.37it/s]

 54%|█████▎    | 53927/100629 [42:24<34:31, 22.55it/s]

 54%|█████▎    | 53930/100629 [42:24<35:42, 21.79it/s]

 54%|█████▎    | 53934/100629 [42:24<30:20, 25.66it/s]

 54%|█████▎    | 53937/100629 [42:24<33:15, 23.40it/s]

 54%|█████▎    | 53940/100629 [42:25<38:42, 20.10it/s]

 54%|█████▎    | 53943/100629 [42:25<42:44, 18.20it/s]

 54%|█████▎    | 53946/100629 [42:25<43:46, 17.78it/s]

 54%|█████▎    | 53949/100629 [42:25<42:47, 18.18it/s]

 54%|█████▎    | 53953/100629 [42:25<36:44, 21.17it/s]

 54%|█████▎    | 53956/100629 [42:26<38:39, 20.12it/s]

 54%|█████▎    | 53959/100629 [42:26<37:54, 20.52it/s]

 54%|█████▎    | 53962/100629 [42:26<34:42, 22.41it/s]

 54%|█████▎    | 53965/100629 [42:26<34:13, 22.72it/s]

 54%|█████▎    | 53968/100629 [42:26<31:50, 24.42it/s]

 54%|█████▎    | 53972/100629 [42:26<30:40, 25.35it/s]

 54%|█████▎    | 53975/100629 [42:26<31:21, 24.79it/s]

 54%|█████▎    | 53978/100629 [42:26<35:09, 22.11it/s]

 54%|█████▎    | 53981/100629 [42:27<37:10, 20.92it/s]

 54%|█████▎    | 53984/100629 [42:27<37:31, 20.72it/s]

 54%|█████▎    | 53987/100629 [42:27<34:37, 22.45it/s]

 54%|█████▎    | 53990/100629 [42:27<32:28, 23.94it/s]

 54%|█████▎    | 53993/100629 [42:27<34:31, 22.52it/s]

 54%|█████▎    | 53996/100629 [42:27<39:51, 19.50it/s]

 54%|█████▎    | 53999/100629 [42:27<38:38, 20.12it/s]

 54%|█████▎    | 54002/100629 [42:28<43:28, 17.88it/s]

 54%|█████▎    | 54004/100629 [42:28<1:00:45, 12.79it/s]

 54%|█████▎    | 54007/100629 [42:28<49:45, 15.62it/s]

 54%|█████▎    | 54010/100629 [42:28<42:48, 18.15it/s]

 54%|█████▎    | 54013/100629 [42:28<42:04, 18.47it/s]

 54%|█████▎    | 54016/100629 [42:29<45:36, 17.03it/s]

 54%|█████▎    | 54021/100629 [42:29<35:50, 21.68it/s]

 54%|█████▎    | 54024/100629 [42:29<36:48, 21.11it/s]

 54%|█████▎    | 54027/100629 [42:29<37:11, 20.89it/s]

 54%|█████▎    | 54030/100629 [42:29<36:55, 21.03it/s]

 54%|█████▎    | 54033/100629 [42:29<41:10, 18.86it/s]

 54%|█████▎    | 54038/100629 [42:29<30:45, 25.25it/s]

 54%|█████▎    | 54041/100629 [42:30<36:30, 21.27it/s]

 54%|█████▎    | 54046/100629 [42:30<29:38, 26.19it/s]

 54%|█████▎    | 54050/100629 [42:30<30:19, 25.60it/s]

 54%|█████▎    | 54053/100629 [42:30<37:02, 20.96it/s]

 54%|█████▎    | 54056/100629 [42:30<38:22, 20.22it/s]

 54%|█████▎    | 54059/100629 [42:31<48:10, 16.11it/s]

 54%|█████▎    | 54062/100629 [42:31<44:14, 17.55it/s]

 54%|█████▎    | 54066/100629 [42:31<37:40, 20.60it/s]

 54%|█████▎    | 54069/100629 [42:31<39:34, 19.61it/s]

 54%|█████▎    | 54072/100629 [42:31<40:35, 19.11it/s]

 54%|█████▎    | 54075/100629 [42:31<50:37, 15.33it/s]

 54%|█████▎    | 54078/100629 [42:32<46:04, 16.84it/s]

 54%|█████▎    | 54084/100629 [42:32<34:11, 22.68it/s]

 54%|█████▎    | 54087/100629 [42:32<33:27, 23.19it/s]

 54%|█████▍    | 54090/100629 [42:32<36:35, 21.20it/s]

 54%|█████▍    | 54093/100629 [42:32<34:16, 22.63it/s]

 54%|█████▍    | 54097/100629 [42:32<31:56, 24.28it/s]

 54%|█████▍    | 54101/100629 [42:32<29:32, 26.25it/s]

 54%|█████▍    | 54104/100629 [42:33<28:54, 26.82it/s]

 54%|█████▍    | 54107/100629 [42:33<33:46, 22.96it/s]

 54%|█████▍    | 54110/100629 [42:33<33:47, 22.94it/s]

 54%|█████▍    | 54113/100629 [42:33<38:30, 20.14it/s]

 54%|█████▍    | 54116/100629 [42:33<35:18, 21.95it/s]

 54%|█████▍    | 54119/100629 [42:33<33:18, 23.27it/s]

 54%|█████▍    | 54123/100629 [42:33<30:26, 25.46it/s]

 54%|█████▍    | 54126/100629 [42:34<30:52, 25.10it/s]

 54%|█████▍    | 54129/100629 [42:34<33:05, 23.43it/s]

 54%|█████▍    | 54132/100629 [42:34<32:28, 23.86it/s]

 54%|█████▍    | 54136/100629 [42:34<29:14, 26.50it/s]

 54%|█████▍    | 54139/100629 [42:34<30:30, 25.39it/s]

 54%|█████▍    | 54142/100629 [42:34<31:55, 24.26it/s]

 54%|█████▍    | 54145/100629 [42:35<47:15, 16.40it/s]

 54%|█████▍    | 54148/100629 [42:35<44:16, 17.49it/s]

 54%|█████▍    | 54151/100629 [42:35<41:36, 18.62it/s]

 54%|█████▍    | 54154/100629 [42:35<42:16, 18.32it/s]

 54%|█████▍    | 54156/100629 [42:35<45:39, 16.96it/s]

 54%|█████▍    | 54159/100629 [42:35<45:02, 17.20it/s]

 54%|█████▍    | 54162/100629 [42:35<41:09, 18.82it/s]

 54%|█████▍    | 54166/100629 [42:36<33:05, 23.40it/s]

 54%|█████▍    | 54169/100629 [42:36<33:16, 23.27it/s]

 54%|█████▍    | 54172/100629 [42:36<35:37, 21.74it/s]

 54%|█████▍    | 54175/100629 [42:36<35:14, 21.97it/s]

 54%|█████▍    | 54178/100629 [42:36<37:07, 20.86it/s]

 54%|█████▍    | 54182/100629 [42:36<31:12, 24.81it/s]

 54%|█████▍    | 54186/100629 [42:36<28:22, 27.28it/s]

 54%|█████▍    | 54189/100629 [42:37<39:31, 19.58it/s]

 54%|█████▍    | 54192/100629 [42:37<37:33, 20.61it/s]

 54%|█████▍    | 54195/100629 [42:37<36:01, 21.49it/s]

 54%|█████▍    | 54199/100629 [42:37<30:19, 25.51it/s]

 54%|█████▍    | 54202/100629 [42:37<31:03, 24.92it/s]

 54%|█████▍    | 54205/100629 [42:37<33:47, 22.89it/s]

 54%|█████▍    | 54208/100629 [42:37<42:19, 18.28it/s]

 54%|█████▍    | 54211/100629 [42:38<46:39, 16.58it/s]

 54%|█████▍    | 54214/100629 [42:38<42:05, 18.38it/s]

 54%|█████▍    | 54218/100629 [42:38<35:05, 22.04it/s]

 54%|█████▍    | 54222/100629 [42:38<35:09, 22.00it/s]

 54%|█████▍    | 54226/100629 [42:38<30:21, 25.47it/s]

 54%|█████▍    | 54229/100629 [42:38<30:41, 25.19it/s]

 54%|█████▍    | 54232/100629 [42:39<37:29, 20.63it/s]

 54%|█████▍    | 54235/100629 [42:39<41:14, 18.75it/s]

 54%|█████▍    | 54240/100629 [42:39<32:17, 23.95it/s]

 54%|█████▍    | 54244/100629 [42:39<32:46, 23.58it/s]

 54%|█████▍    | 54247/100629 [42:39<38:20, 20.16it/s]

 54%|█████▍    | 54251/100629 [42:39<34:51, 22.18it/s]

 54%|█████▍    | 54254/100629 [42:40<34:33, 22.36it/s]

 54%|█████▍    | 54257/100629 [42:40<37:09, 20.80it/s]

 54%|█████▍    | 54260/100629 [42:40<38:29, 20.07it/s]

 54%|█████▍    | 54263/100629 [42:40<48:51, 15.81it/s]

 54%|█████▍    | 54265/100629 [42:40<46:46, 16.52it/s]

 54%|█████▍    | 54268/100629 [42:40<43:21, 17.82it/s]

 54%|█████▍    | 54270/100629 [42:41<42:42, 18.09it/s]

 54%|█████▍    | 54273/100629 [42:41<40:43, 18.97it/s]

 54%|█████▍    | 54276/100629 [42:41<39:21, 19.63it/s]

 54%|█████▍    | 54280/100629 [42:41<35:50, 21.56it/s]

 54%|█████▍    | 54283/100629 [42:41<40:55, 18.88it/s]

 54%|█████▍    | 54285/100629 [42:41<42:09, 18.32it/s]

 54%|█████▍    | 54289/100629 [42:41<34:53, 22.14it/s]

 54%|█████▍    | 54293/100629 [42:42<30:26, 25.37it/s]

 54%|█████▍    | 54296/100629 [42:42<34:48, 22.19it/s]

 54%|█████▍    | 54299/100629 [42:42<37:20, 20.67it/s]

 54%|█████▍    | 54302/100629 [42:42<36:58, 20.88it/s]

 54%|█████▍    | 54305/100629 [42:42<34:42, 22.24it/s]

 54%|█████▍    | 54308/100629 [42:42<44:03, 17.52it/s]

 54%|█████▍    | 54310/100629 [42:42<43:00, 17.95it/s]

 54%|█████▍    | 54313/100629 [42:43<38:25, 20.09it/s]

 54%|█████▍    | 54318/100629 [42:43<30:00, 25.72it/s]

 54%|█████▍    | 54321/100629 [42:43<36:24, 21.20it/s]

 54%|█████▍    | 54324/100629 [42:43<37:28, 20.59it/s]

 54%|█████▍    | 54327/100629 [42:43<42:23, 18.20it/s]

 54%|█████▍    | 54330/100629 [42:43<39:44, 19.41it/s]

 54%|█████▍    | 54334/100629 [42:44<36:12, 21.31it/s]

 54%|█████▍    | 54337/100629 [42:44<36:52, 20.92it/s]

 54%|█████▍    | 54340/100629 [42:44<33:49, 22.80it/s]

 54%|█████▍    | 54344/100629 [42:44<29:49, 25.87it/s]

 54%|█████▍    | 54347/100629 [42:44<30:06, 25.62it/s]

 54%|█████▍    | 54350/100629 [42:44<33:34, 22.98it/s]

 54%|█████▍    | 54353/100629 [42:44<35:30, 21.73it/s]

 54%|█████▍    | 54356/100629 [42:45<43:40, 17.66it/s]

 54%|█████▍    | 54358/100629 [42:45<48:11, 16.00it/s]

 54%|█████▍    | 54360/100629 [42:45<47:01, 16.40it/s]

 54%|█████▍    | 54364/100629 [42:45<36:06, 21.36it/s]

 54%|█████▍    | 54367/100629 [42:45<37:21, 20.64it/s]

 54%|█████▍    | 54370/100629 [42:45<34:09, 22.57it/s]

 54%|█████▍    | 54373/100629 [42:45<32:56, 23.40it/s]

 54%|█████▍    | 54376/100629 [42:46<33:29, 23.01it/s]

 54%|█████▍    | 54379/100629 [42:46<35:31, 21.70it/s]

 54%|█████▍    | 54382/100629 [42:46<35:57, 21.44it/s]

 54%|█████▍    | 54385/100629 [42:46<39:19, 19.60it/s]

 54%|█████▍    | 54388/100629 [42:46<41:07, 18.74it/s]

 54%|█████▍    | 54391/100629 [42:46<36:51, 20.91it/s]

 54%|█████▍    | 54394/100629 [42:47<40:19, 19.11it/s]

 54%|█████▍    | 54397/100629 [42:47<41:07, 18.74it/s]

 54%|█████▍    | 54399/100629 [42:47<40:51, 18.86it/s]

 54%|█████▍    | 54402/100629 [42:47<36:35, 21.06it/s]

 54%|█████▍    | 54405/100629 [42:47<40:14, 19.15it/s]

 54%|█████▍    | 54409/100629 [42:47<33:18, 23.13it/s]

 54%|█████▍    | 54412/100629 [42:47<37:37, 20.47it/s]

 54%|█████▍    | 54415/100629 [42:48<37:16, 20.67it/s]

 54%|█████▍    | 54418/100629 [42:48<37:17, 20.66it/s]

 54%|█████▍    | 54422/100629 [42:48<30:59, 24.85it/s]

 54%|█████▍    | 54427/100629 [42:48<26:51, 28.67it/s]

 54%|█████▍    | 54431/100629 [42:48<28:50, 26.69it/s]

 54%|█████▍    | 54434/100629 [42:48<30:59, 24.84it/s]

 54%|█████▍    | 54437/100629 [42:48<32:51, 23.43it/s]

 54%|█████▍    | 54440/100629 [42:48<30:58, 24.85it/s]

 54%|█████▍    | 54443/100629 [42:49<30:02, 25.62it/s]

 54%|█████▍    | 54446/100629 [42:49<29:11, 26.37it/s]

 54%|█████▍    | 54449/100629 [42:49<38:24, 20.04it/s]

 54%|█████▍    | 54452/100629 [42:49<42:34, 18.08it/s]

 54%|█████▍    | 54455/100629 [42:49<45:20, 16.97it/s]

 54%|█████▍    | 54458/100629 [42:49<41:17, 18.64it/s]

 54%|█████▍    | 54461/100629 [42:50<38:04, 20.21it/s]

 54%|█████▍    | 54464/100629 [42:50<36:45, 20.93it/s]

 54%|█████▍    | 54467/100629 [42:50<37:55, 20.28it/s]

 54%|█████▍    | 54470/100629 [42:50<39:00, 19.72it/s]

 54%|█████▍    | 54473/100629 [42:50<35:46, 21.50it/s]

 54%|█████▍    | 54476/100629 [42:50<34:25, 22.34it/s]

 54%|█████▍    | 54479/100629 [42:50<38:36, 19.93it/s]

 54%|█████▍    | 54482/100629 [42:51<35:25, 21.71it/s]

 54%|█████▍    | 54485/100629 [42:51<36:32, 21.05it/s]

 54%|█████▍    | 54488/100629 [42:51<35:25, 21.71it/s]

 54%|█████▍    | 54493/100629 [42:51<28:16, 27.20it/s]

 54%|█████▍    | 54496/100629 [42:51<31:17, 24.56it/s]

 54%|█████▍    | 54499/100629 [42:51<30:30, 25.20it/s]

 54%|█████▍    | 54503/100629 [42:51<28:29, 26.98it/s]

 54%|█████▍    | 54507/100629 [42:52<29:47, 25.80it/s]

 54%|█████▍    | 54510/100629 [42:52<30:24, 25.28it/s]

 54%|█████▍    | 54513/100629 [42:52<32:20, 23.76it/s]

 54%|█████▍    | 54516/100629 [42:52<33:02, 23.26it/s]

 54%|█████▍    | 54521/100629 [42:52<27:31, 27.92it/s]

 54%|█████▍    | 54525/100629 [42:52<27:07, 28.32it/s]

 54%|█████▍    | 54529/100629 [42:52<29:18, 26.22it/s]

 54%|█████▍    | 54532/100629 [42:53<31:43, 24.21it/s]

 54%|█████▍    | 54535/100629 [42:53<33:06, 23.20it/s]

 54%|█████▍    | 54539/100629 [42:53<30:52, 24.88it/s]

 54%|█████▍    | 54542/100629 [42:53<42:39, 18.01it/s]

 54%|█████▍    | 54546/100629 [42:53<37:28, 20.50it/s]

 54%|█████▍    | 54549/100629 [42:53<45:58, 16.71it/s]

 54%|█████▍    | 54551/100629 [42:54<45:27, 16.89it/s]

 54%|█████▍    | 54554/100629 [42:54<43:42, 17.57it/s]

 54%|█████▍    | 54556/100629 [42:54<43:30, 17.65it/s]

 54%|█████▍    | 54559/100629 [42:54<41:00, 18.72it/s]

 54%|█████▍    | 54563/100629 [42:54<35:18, 21.75it/s]

 54%|█████▍    | 54566/100629 [42:54<36:51, 20.83it/s]

 54%|█████▍    | 54569/100629 [42:54<36:24, 21.09it/s]

 54%|█████▍    | 54572/100629 [42:55<40:36, 18.90it/s]

 54%|█████▍    | 54575/100629 [42:55<39:33, 19.41it/s]

 54%|█████▍    | 54578/100629 [42:55<45:29, 16.87it/s]

 54%|█████▍    | 54581/100629 [42:55<43:14, 17.75it/s]

 54%|█████▍    | 54584/100629 [42:55<42:08, 18.21it/s]

 54%|█████▍    | 54587/100629 [42:55<41:18, 18.58it/s]

 54%|█████▍    | 54590/100629 [42:56<37:50, 20.28it/s]

 54%|█████▍    | 54593/100629 [42:56<36:58, 20.75it/s]

 54%|█████▍    | 54596/100629 [42:56<38:27, 19.95it/s]

 54%|█████▍    | 54599/100629 [42:56<36:41, 20.91it/s]

 54%|█████▍    | 54602/100629 [42:56<52:17, 14.67it/s]

 54%|█████▍    | 54604/100629 [42:56<50:03, 15.32it/s]

 54%|█████▍    | 54606/100629 [42:57<47:18, 16.21it/s]

 54%|█████▍    | 54608/100629 [42:57<57:03, 13.44it/s]

 54%|█████▍    | 54610/100629 [42:57<59:13, 12.95it/s]

 54%|█████▍    | 54613/100629 [42:57<49:02, 15.64it/s]

 54%|█████▍    | 54616/100629 [42:57<54:38, 14.03it/s]

 54%|█████▍    | 54620/100629 [42:58<46:44, 16.41it/s]

 54%|█████▍    | 54624/100629 [42:58<37:45, 20.31it/s]

 54%|█████▍    | 54627/100629 [42:58<39:44, 19.29it/s]

 54%|█████▍    | 54630/100629 [42:58<45:24, 16.89it/s]

 54%|█████▍    | 54633/100629 [42:58<40:38, 18.86it/s]

 54%|█████▍    | 54637/100629 [42:58<37:02, 20.69it/s]

 54%|█████▍    | 54641/100629 [42:58<31:17, 24.50it/s]

 54%|█████▍    | 54644/100629 [42:59<40:58, 18.70it/s]

 54%|█████▍    | 54648/100629 [42:59<33:40, 22.76it/s]

 54%|█████▍    | 54651/100629 [42:59<32:25, 23.63it/s]

 54%|█████▍    | 54654/100629 [42:59<32:16, 23.74it/s]

 54%|█████▍    | 54658/100629 [42:59<33:22, 22.96it/s]

 54%|█████▍    | 54661/100629 [42:59<33:02, 23.18it/s]

 54%|█████▍    | 54664/100629 [43:00<42:04, 18.21it/s]

 54%|█████▍    | 54668/100629 [43:00<38:28, 19.91it/s]

 54%|█████▍    | 54671/100629 [43:00<35:16, 21.71it/s]

 54%|█████▍    | 54674/100629 [43:00<35:54, 21.33it/s]

 54%|█████▍    | 54677/100629 [43:00<36:38, 20.90it/s]

 54%|█████▍    | 54680/100629 [43:00<33:42, 22.72it/s]

 54%|█████▍    | 54683/100629 [43:00<35:43, 21.43it/s]

 54%|█████▍    | 54686/100629 [43:01<34:54, 21.93it/s]

 54%|█████▍    | 54689/100629 [43:01<36:52, 20.76it/s]

 54%|█████▍    | 54693/100629 [43:01<34:15, 22.35it/s]

 54%|█████▍    | 54696/100629 [43:01<32:57, 23.23it/s]

 54%|█████▍    | 54699/100629 [43:01<30:56, 24.74it/s]

 54%|█████▍    | 54702/100629 [43:01<33:03, 23.16it/s]

 54%|█████▍    | 54705/100629 [43:01<31:37, 24.20it/s]

 54%|█████▍    | 54708/100629 [43:01<31:06, 24.60it/s]

 54%|█████▍    | 54711/100629 [43:02<34:59, 21.87it/s]

 54%|█████▍    | 54714/100629 [43:02<33:49, 22.62it/s]

 54%|█████▍    | 54717/100629 [43:02<39:13, 19.51it/s]

 54%|█████▍    | 54720/100629 [43:02<38:20, 19.95it/s]

 54%|█████▍    | 54723/100629 [43:02<35:45, 21.40it/s]

 54%|█████▍    | 54726/100629 [43:02<34:50, 21.96it/s]

 54%|█████▍    | 54729/100629 [43:02<34:09, 22.40it/s]

 54%|█████▍    | 54732/100629 [43:03<36:08, 21.16it/s]

 54%|█████▍    | 54735/100629 [43:03<37:46, 20.24it/s]

 54%|█████▍    | 54738/100629 [43:03<35:15, 21.69it/s]

 54%|█████▍    | 54741/100629 [43:03<35:37, 21.47it/s]

 54%|█████▍    | 54744/100629 [43:03<41:29, 18.43it/s]

 54%|█████▍    | 54747/100629 [43:03<40:17, 18.98it/s]

 54%|█████▍    | 54750/100629 [43:04<37:49, 20.22it/s]

 54%|█████▍    | 54753/100629 [43:04<38:54, 19.65it/s]

 54%|█████▍    | 54757/100629 [43:04<35:55, 21.28it/s]

 54%|█████▍    | 54760/100629 [43:04<33:06, 23.09it/s]

 54%|█████▍    | 54763/100629 [43:04<36:18, 21.05it/s]

 54%|█████▍    | 54766/100629 [43:04<33:55, 22.53it/s]

 54%|█████▍    | 54771/100629 [43:04<28:53, 26.45it/s]

 54%|█████▍    | 54776/100629 [43:05<25:12, 30.32it/s]

 54%|█████▍    | 54780/100629 [43:05<26:10, 29.20it/s]

 54%|█████▍    | 54783/100629 [43:05<32:39, 23.40it/s]

 54%|█████▍    | 54787/100629 [43:05<30:28, 25.07it/s]

 54%|█████▍    | 54790/100629 [43:05<34:53, 21.89it/s]

 54%|█████▍    | 54793/100629 [43:05<34:03, 22.43it/s]

 54%|█████▍    | 54796/100629 [43:05<34:24, 22.20it/s]

 54%|█████▍    | 54799/100629 [43:06<37:27, 20.39it/s]

 54%|█████▍    | 54802/100629 [43:06<38:22, 19.90it/s]

 54%|█████▍    | 54805/100629 [43:06<38:58, 19.60it/s]

 54%|█████▍    | 54811/100629 [43:06<29:15, 26.11it/s]

 54%|█████▍    | 54814/100629 [43:06<28:57, 26.36it/s]

 54%|█████▍    | 54817/100629 [43:06<31:19, 24.37it/s]

 54%|█████▍    | 54821/100629 [43:06<28:06, 27.16it/s]

 54%|█████▍    | 54824/100629 [43:07<30:51, 24.74it/s]

 54%|█████▍    | 54827/100629 [43:07<32:01, 23.83it/s]

 54%|█████▍    | 54830/100629 [43:07<34:38, 22.03it/s]

 54%|█████▍    | 54833/100629 [43:07<32:36, 23.41it/s]

 54%|█████▍    | 54836/100629 [43:07<35:05, 21.75it/s]

 54%|█████▍    | 54839/100629 [43:07<37:52, 20.15it/s]

 54%|█████▍    | 54842/100629 [43:07<35:05, 21.74it/s]

 55%|█████▍    | 54846/100629 [43:08<31:50, 23.97it/s]

 55%|█████▍    | 54849/100629 [43:08<32:54, 23.19it/s]

 55%|█████▍    | 54853/100629 [43:08<30:48, 24.76it/s]

 55%|█████▍    | 54856/100629 [43:08<30:14, 25.23it/s]

 55%|█████▍    | 54859/100629 [43:08<30:35, 24.93it/s]

 55%|█████▍    | 54863/100629 [43:08<28:10, 27.07it/s]

 55%|█████▍    | 54866/100629 [43:08<33:22, 22.86it/s]

 55%|█████▍    | 54869/100629 [43:09<43:46, 17.42it/s]

 55%|█████▍    | 54872/100629 [43:09<44:08, 17.28it/s]

 55%|█████▍    | 54875/100629 [43:09<42:34, 17.91it/s]

 55%|█████▍    | 54877/100629 [43:09<43:34, 17.50it/s]

 55%|█████▍    | 54880/100629 [43:09<41:00, 18.60it/s]

 55%|█████▍    | 54883/100629 [43:09<37:05, 20.55it/s]

 55%|█████▍    | 54886/100629 [43:10<33:49, 22.54it/s]

 55%|█████▍    | 54889/100629 [43:10<32:26, 23.50it/s]

 55%|█████▍    | 54893/100629 [43:10<28:59, 26.30it/s]

 55%|█████▍    | 54896/100629 [43:10<28:51, 26.41it/s]

 55%|█████▍    | 54899/100629 [43:10<31:35, 24.13it/s]

 55%|█████▍    | 54902/100629 [43:10<32:42, 23.30it/s]

 55%|█████▍    | 54905/100629 [43:10<36:33, 20.84it/s]

 55%|█████▍    | 54908/100629 [43:11<36:41, 20.77it/s]

 55%|█████▍    | 54911/100629 [43:11<35:39, 21.36it/s]

 55%|█████▍    | 54916/100629 [43:11<27:48, 27.39it/s]

 55%|█████▍    | 54919/100629 [43:11<30:41, 24.82it/s]

 55%|█████▍    | 54923/100629 [43:11<28:02, 27.17it/s]

 55%|█████▍    | 54926/100629 [43:11<29:07, 26.15it/s]

 55%|█████▍    | 54929/100629 [43:11<31:14, 24.38it/s]

 55%|█████▍    | 54932/100629 [43:12<39:43, 19.17it/s]

 55%|█████▍    | 54935/100629 [43:12<40:24, 18.85it/s]

 55%|█████▍    | 54938/100629 [43:12<43:02, 17.69it/s]

 55%|█████▍    | 54940/100629 [43:12<43:48, 17.38it/s]

 55%|█████▍    | 54942/100629 [43:12<47:00, 16.20it/s]

 55%|█████▍    | 54945/100629 [43:12<40:13, 18.93it/s]

 55%|█████▍    | 54948/100629 [43:12<36:09, 21.06it/s]

 55%|█████▍    | 54953/100629 [43:12<27:26, 27.74it/s]

 55%|█████▍    | 54956/100629 [43:13<27:08, 28.04it/s]

 55%|█████▍    | 54959/100629 [43:13<29:29, 25.81it/s]

 55%|█████▍    | 54962/100629 [43:13<33:58, 22.40it/s]

 55%|█████▍    | 54965/100629 [43:13<50:28, 15.08it/s]

 55%|█████▍    | 54968/100629 [43:13<47:09, 16.14it/s]

 55%|█████▍    | 54971/100629 [43:14<42:25, 17.94it/s]

 55%|█████▍    | 54974/100629 [43:14<41:31, 18.32it/s]

 55%|█████▍    | 54978/100629 [43:14<39:43, 19.15it/s]

 55%|█████▍    | 54982/100629 [43:14<36:07, 21.06it/s]

 55%|█████▍    | 54985/100629 [43:14<38:59, 19.51it/s]

 55%|█████▍    | 54989/100629 [43:14<32:40, 23.28it/s]

 55%|█████▍    | 54992/100629 [43:14<32:19, 23.54it/s]

 55%|█████▍    | 54995/100629 [43:15<33:19, 22.82it/s]

 55%|█████▍    | 54998/100629 [43:15<35:45, 21.27it/s]

 55%|█████▍    | 55001/100629 [43:15<38:48, 19.59it/s]

 55%|█████▍    | 55004/100629 [43:15<41:46, 18.20it/s]

 55%|█████▍    | 55007/100629 [43:15<39:39, 19.18it/s]

 55%|█████▍    | 55010/100629 [43:15<39:04, 19.46it/s]

 55%|█████▍    | 55013/100629 [43:16<35:12, 21.59it/s]

 55%|█████▍    | 55018/100629 [43:16<27:45, 27.38it/s]

 55%|█████▍    | 55022/100629 [43:16<27:14, 27.90it/s]

 55%|█████▍    | 55026/100629 [43:16<25:50, 29.42it/s]

 55%|█████▍    | 55030/100629 [43:16<33:12, 22.89it/s]

 55%|█████▍    | 55034/100629 [43:16<29:39, 25.62it/s]

 55%|█████▍    | 55037/100629 [43:16<29:23, 25.85it/s]

 55%|█████▍    | 55040/100629 [43:17<31:57, 23.78it/s]

 55%|█████▍    | 55043/100629 [43:17<31:01, 24.49it/s]

 55%|█████▍    | 55046/100629 [43:17<30:39, 24.78it/s]

 55%|█████▍    | 55049/100629 [43:17<33:03, 22.97it/s]

 55%|█████▍    | 55052/100629 [43:17<32:20, 23.49it/s]

 55%|█████▍    | 55056/100629 [43:17<28:51, 26.32it/s]

 55%|█████▍    | 55059/100629 [43:17<30:56, 24.55it/s]

 55%|█████▍    | 55063/100629 [43:17<30:53, 24.59it/s]

 55%|█████▍    | 55066/100629 [43:18<30:47, 24.66it/s]

 55%|█████▍    | 55069/100629 [43:18<31:21, 24.21it/s]

 55%|█████▍    | 55073/100629 [43:18<28:14, 26.88it/s]

 55%|█████▍    | 55076/100629 [43:18<29:26, 25.79it/s]

 55%|█████▍    | 55079/100629 [43:18<28:57, 26.21it/s]

 55%|█████▍    | 55082/100629 [43:18<29:43, 25.53it/s]

 55%|█████▍    | 55085/100629 [43:18<33:49, 22.44it/s]

 55%|█████▍    | 55088/100629 [43:19<35:02, 21.66it/s]

 55%|█████▍    | 55091/100629 [43:19<37:28, 20.25it/s]

 55%|█████▍    | 55094/100629 [43:19<39:19, 19.30it/s]

 55%|█████▍    | 55097/100629 [43:19<35:44, 21.23it/s]

 55%|█████▍    | 55100/100629 [43:19<36:43, 20.66it/s]

 55%|█████▍    | 55103/100629 [43:19<33:52, 22.40it/s]

 55%|█████▍    | 55106/100629 [43:19<34:37, 21.91it/s]

 55%|█████▍    | 55109/100629 [43:20<32:49, 23.11it/s]

 55%|█████▍    | 55112/100629 [43:20<35:26, 21.40it/s]

 55%|█████▍    | 55115/100629 [43:20<34:29, 21.99it/s]

 55%|█████▍    | 55120/100629 [43:20<30:09, 25.15it/s]

 55%|█████▍    | 55123/100629 [43:20<40:12, 18.86it/s]

 55%|█████▍    | 55127/100629 [43:20<36:49, 20.60it/s]

 55%|█████▍    | 55131/100629 [43:21<32:13, 23.53it/s]

 55%|█████▍    | 55135/100629 [43:21<29:34, 25.64it/s]

 55%|█████▍    | 55139/100629 [43:21<26:28, 28.65it/s]

 55%|█████▍    | 55143/100629 [43:21<25:34, 29.63it/s]

 55%|█████▍    | 55147/100629 [43:21<26:25, 28.69it/s]

 55%|█████▍    | 55152/100629 [43:21<24:35, 30.83it/s]

 55%|█████▍    | 55156/100629 [43:21<27:51, 27.21it/s]

 55%|█████▍    | 55159/100629 [43:21<29:17, 25.87it/s]

 55%|█████▍    | 55162/100629 [43:22<31:13, 24.26it/s]

 55%|█████▍    | 55165/100629 [43:22<33:38, 22.53it/s]

 55%|█████▍    | 55168/100629 [43:22<36:39, 20.67it/s]

 55%|█████▍    | 55171/100629 [43:22<36:07, 20.97it/s]

 55%|█████▍    | 55174/100629 [43:22<36:25, 20.80it/s]

 55%|█████▍    | 55178/100629 [43:22<33:14, 22.79it/s]

 55%|█████▍    | 55181/100629 [43:23<38:34, 19.64it/s]

 55%|█████▍    | 55184/100629 [43:23<35:33, 21.30it/s]

 55%|█████▍    | 55188/100629 [43:23<31:04, 24.38it/s]

 55%|█████▍    | 55191/100629 [43:23<36:30, 20.75it/s]

 55%|█████▍    | 55194/100629 [43:23<36:31, 20.73it/s]

 55%|█████▍    | 55197/100629 [43:23<36:21, 20.83it/s]

 55%|█████▍    | 55200/100629 [43:23<35:34, 21.28it/s]

 55%|█████▍    | 55203/100629 [43:24<36:33, 20.71it/s]

 55%|█████▍    | 55206/100629 [43:24<38:26, 19.69it/s]

 55%|█████▍    | 55209/100629 [43:24<43:56, 17.23it/s]

 55%|█████▍    | 55213/100629 [43:24<38:06, 19.86it/s]

 55%|█████▍    | 55216/100629 [43:24<40:10, 18.84it/s]

 55%|█████▍    | 55222/100629 [43:24<30:48, 24.56it/s]

 55%|█████▍    | 55225/100629 [43:25<34:47, 21.75it/s]

 55%|█████▍    | 55229/100629 [43:25<32:08, 23.54it/s]

 55%|█████▍    | 55232/100629 [43:25<35:10, 21.52it/s]

 55%|█████▍    | 55235/100629 [43:25<34:10, 22.13it/s]

 55%|█████▍    | 55238/100629 [43:25<34:21, 22.02it/s]

 55%|█████▍    | 55242/100629 [43:25<30:28, 24.82it/s]

 55%|█████▍    | 55246/100629 [43:26<29:57, 25.25it/s]

 55%|█████▍    | 55249/100629 [43:26<29:53, 25.30it/s]

 55%|█████▍    | 55252/100629 [43:26<41:12, 18.35it/s]

 55%|█████▍    | 55256/100629 [43:26<33:46, 22.39it/s]

 55%|█████▍    | 55259/100629 [43:26<34:08, 22.15it/s]

 55%|█████▍    | 55262/100629 [43:26<33:27, 22.60it/s]

 55%|█████▍    | 55265/100629 [43:26<36:14, 20.86it/s]

 55%|█████▍    | 55268/100629 [43:27<33:09, 22.81it/s]

 55%|█████▍    | 55271/100629 [43:27<36:28, 20.73it/s]

 55%|█████▍    | 55274/100629 [43:27<35:00, 21.59it/s]

 55%|█████▍    | 55277/100629 [43:27<35:18, 21.40it/s]

 55%|█████▍    | 55280/100629 [43:27<37:25, 20.19it/s]

 55%|█████▍    | 55285/100629 [43:27<31:46, 23.79it/s]

 55%|█████▍    | 55289/100629 [43:27<28:24, 26.60it/s]

 55%|█████▍    | 55292/100629 [43:28<37:14, 20.29it/s]

 55%|█████▍    | 55295/100629 [43:28<36:18, 20.81it/s]

 55%|█████▍    | 55298/100629 [43:28<38:42, 19.52it/s]

 55%|█████▍    | 55301/100629 [43:28<36:46, 20.55it/s]

 55%|█████▍    | 55304/100629 [43:28<40:31, 18.64it/s]

 55%|█████▍    | 55307/100629 [43:28<38:29, 19.62it/s]

 55%|█████▍    | 55310/100629 [43:29<40:22, 18.71it/s]

 55%|█████▍    | 55312/100629 [43:29<40:19, 18.73it/s]

 55%|█████▍    | 55314/100629 [43:29<40:57, 18.44it/s]

 55%|█████▍    | 55316/100629 [43:29<40:29, 18.65it/s]

 55%|█████▍    | 55319/100629 [43:29<36:25, 20.73it/s]

 55%|█████▍    | 55322/100629 [43:29<42:39, 17.70it/s]

 55%|█████▍    | 55326/100629 [43:29<35:15, 21.41it/s]

 55%|█████▍    | 55329/100629 [43:30<34:08, 22.12it/s]

 55%|█████▍    | 55332/100629 [43:30<37:50, 19.95it/s]

 55%|█████▍    | 55335/100629 [43:30<34:46, 21.70it/s]

 55%|█████▍    | 55338/100629 [43:30<34:22, 21.96it/s]

 55%|█████▍    | 55341/100629 [43:30<33:45, 22.36it/s]

 55%|█████▍    | 55344/100629 [43:30<36:04, 20.92it/s]

 55%|█████▌    | 55348/100629 [43:30<31:09, 24.22it/s]

 55%|█████▌    | 55351/100629 [43:31<36:01, 20.95it/s]

 55%|█████▌    | 55355/100629 [43:31<33:46, 22.34it/s]

 55%|█████▌    | 55358/100629 [43:31<33:12, 22.73it/s]

 55%|█████▌    | 55361/100629 [43:31<46:31, 16.22it/s]

 55%|█████▌    | 55363/100629 [43:31<51:32, 14.64it/s]

 55%|█████▌    | 55367/100629 [43:31<39:57, 18.88it/s]

 55%|█████▌    | 55370/100629 [43:32<44:22, 17.00it/s]

 55%|█████▌    | 55372/100629 [43:32<42:58, 17.55it/s]

 55%|█████▌    | 55374/100629 [43:32<43:05, 17.51it/s]

 55%|█████▌    | 55377/100629 [43:32<38:29, 19.60it/s]

 55%|█████▌    | 55380/100629 [43:32<41:13, 18.29it/s]

 55%|█████▌    | 55383/100629 [43:32<37:02, 20.36it/s]

 55%|█████▌    | 55387/100629 [43:32<30:27, 24.75it/s]

 55%|█████▌    | 55390/100629 [43:33<34:55, 21.59it/s]

 55%|█████▌    | 55393/100629 [43:33<34:38, 21.77it/s]

 55%|█████▌    | 55396/100629 [43:33<34:19, 21.96it/s]

 55%|█████▌    | 55399/100629 [43:33<33:19, 22.62it/s]

 55%|█████▌    | 55403/100629 [43:33<28:11, 26.74it/s]

 55%|█████▌    | 55406/100629 [43:33<37:09, 20.29it/s]

 55%|█████▌    | 55409/100629 [43:34<41:49, 18.02it/s]

 55%|█████▌    | 55412/100629 [43:34<45:33, 16.54it/s]

 55%|█████▌    | 55415/100629 [43:34<44:16, 17.02it/s]

 55%|█████▌    | 55418/100629 [43:34<41:32, 18.14it/s]

 55%|█████▌    | 55420/100629 [43:34<44:57, 16.76it/s]

 55%|█████▌    | 55422/100629 [43:34<43:20, 17.38it/s]

 55%|█████▌    | 55424/100629 [43:34<44:46, 16.83it/s]

 55%|█████▌    | 55426/100629 [43:35<45:37, 16.51it/s]

 55%|█████▌    | 55428/100629 [43:35<44:33, 16.91it/s]

 55%|█████▌    | 55431/100629 [43:35<42:12, 17.85it/s]

 55%|█████▌    | 55433/100629 [43:35<49:57, 15.08it/s]

 55%|█████▌    | 55436/100629 [43:35<44:34, 16.90it/s]

 55%|█████▌    | 55439/100629 [43:35<38:59, 19.31it/s]

 55%|█████▌    | 55442/100629 [43:35<36:09, 20.83it/s]

 55%|█████▌    | 55445/100629 [43:36<34:53, 21.59it/s]

 55%|█████▌    | 55449/100629 [43:36<32:09, 23.42it/s]

 55%|█████▌    | 55452/100629 [43:36<30:25, 24.75it/s]

 55%|█████▌    | 55455/100629 [43:36<32:47, 22.97it/s]

 55%|█████▌    | 55458/100629 [43:36<35:44, 21.06it/s]

 55%|█████▌    | 55462/100629 [43:36<34:17, 21.95it/s]

 55%|█████▌    | 55465/100629 [43:36<34:39, 21.72it/s]

 55%|█████▌    | 55468/100629 [43:37<34:07, 22.06it/s]

 55%|█████▌    | 55472/100629 [43:37<33:04, 22.75it/s]

 55%|█████▌    | 55476/100629 [43:37<32:45, 22.97it/s]

 55%|█████▌    | 55479/100629 [43:37<35:08, 21.42it/s]

 55%|█████▌    | 55482/100629 [43:37<39:45, 18.92it/s]

 55%|█████▌    | 55487/100629 [43:37<34:40, 21.70it/s]

 55%|█████▌    | 55493/100629 [43:38<27:17, 27.56it/s]

 55%|█████▌    | 55497/100629 [43:38<25:55, 29.01it/s]

 55%|█████▌    | 55501/100629 [43:38<27:31, 27.32it/s]

 55%|█████▌    | 55504/100629 [43:38<31:16, 24.05it/s]

 55%|█████▌    | 55507/100629 [43:38<29:45, 25.27it/s]

 55%|█████▌    | 55510/100629 [43:38<31:01, 24.24it/s]

 55%|█████▌    | 55513/100629 [43:38<36:08, 20.80it/s]

 55%|█████▌    | 55516/100629 [43:39<40:34, 18.53it/s]

 55%|█████▌    | 55519/100629 [43:39<37:16, 20.17it/s]

 55%|█████▌    | 55522/100629 [43:39<37:53, 19.84it/s]

 55%|█████▌    | 55525/100629 [43:39<35:36, 21.11it/s]

 55%|█████▌    | 55528/100629 [43:39<39:16, 19.14it/s]

 55%|█████▌    | 55531/100629 [43:39<40:05, 18.75it/s]

 55%|█████▌    | 55533/100629 [43:40<42:02, 17.88it/s]

 55%|█████▌    | 55535/100629 [43:40<42:53, 17.52it/s]

 55%|█████▌    | 55538/100629 [43:40<37:57, 19.80it/s]

 55%|█████▌    | 55541/100629 [43:40<36:51, 20.39it/s]

 55%|█████▌    | 55544/100629 [43:40<36:51, 20.39it/s]

 55%|█████▌    | 55547/100629 [43:40<38:04, 19.74it/s]

 55%|█████▌    | 55549/100629 [43:40<44:54, 16.73it/s]

 55%|█████▌    | 55551/100629 [43:41<44:25, 16.91it/s]

 55%|█████▌    | 55554/100629 [43:41<38:09, 19.69it/s]

 55%|█████▌    | 55558/100629 [43:41<31:21, 23.96it/s]

 55%|█████▌    | 55561/100629 [43:41<30:59, 24.23it/s]

 55%|█████▌    | 55564/100629 [43:41<30:30, 24.62it/s]

 55%|█████▌    | 55567/100629 [43:41<29:48, 25.19it/s]

 55%|█████▌    | 55570/100629 [43:41<31:57, 23.50it/s]

 55%|█████▌    | 55574/100629 [43:41<28:00, 26.82it/s]

 55%|█████▌    | 55577/100629 [43:42<34:05, 22.02it/s]

 55%|█████▌    | 55580/100629 [43:42<37:10, 20.20it/s]

 55%|█████▌    | 55583/100629 [43:42<37:30, 20.01it/s]

 55%|█████▌    | 55587/100629 [43:42<32:47, 22.89it/s]

 55%|█████▌    | 55590/100629 [43:42<34:48, 21.57it/s]

 55%|█████▌    | 55593/100629 [43:42<33:07, 22.66it/s]

 55%|█████▌    | 55596/100629 [43:42<31:21, 23.93it/s]

 55%|█████▌    | 55599/100629 [43:43<37:19, 20.11it/s]

 55%|█████▌    | 55603/100629 [43:43<31:52, 23.55it/s]

 55%|█████▌    | 55606/100629 [43:43<38:26, 19.52it/s]

 55%|█████▌    | 55610/100629 [43:43<34:21, 21.83it/s]

 55%|█████▌    | 55613/100629 [43:43<35:28, 21.15it/s]

 55%|█████▌    | 55616/100629 [43:43<36:44, 20.42it/s]

 55%|█████▌    | 55619/100629 [43:44<42:55, 17.48it/s]

 55%|█████▌    | 55621/100629 [43:44<43:52, 17.09it/s]

 55%|█████▌    | 55624/100629 [43:44<39:12, 19.13it/s]

 55%|█████▌    | 55628/100629 [43:44<32:24, 23.14it/s]

 55%|█████▌    | 55633/100629 [43:44<26:00, 28.83it/s]

 55%|█████▌    | 55637/100629 [43:44<26:31, 28.26it/s]

 55%|█████▌    | 55640/100629 [43:44<31:34, 23.75it/s]

 55%|█████▌    | 55645/100629 [43:45<27:20, 27.42it/s]

 55%|█████▌    | 55648/100629 [43:45<28:44, 26.08it/s]

 55%|█████▌    | 55652/100629 [43:45<25:47, 29.06it/s]

 55%|█████▌    | 55656/100629 [43:45<27:04, 27.69it/s]

 55%|█████▌    | 55660/100629 [43:45<24:59, 29.98it/s]

 55%|█████▌    | 55664/100629 [43:45<31:55, 23.48it/s]

 55%|█████▌    | 55667/100629 [43:46<33:19, 22.49it/s]

 55%|█████▌    | 55670/100629 [43:46<35:09, 21.32it/s]

 55%|█████▌    | 55673/100629 [43:46<37:06, 20.20it/s]

 55%|█████▌    | 55676/100629 [43:46<37:40, 19.89it/s]

 55%|█████▌    | 55679/100629 [43:46<34:36, 21.65it/s]

 55%|█████▌    | 55682/100629 [43:46<41:34, 18.02it/s]

 55%|█████▌    | 55686/100629 [43:46<35:12, 21.27it/s]

 55%|█████▌    | 55689/100629 [43:47<35:26, 21.14it/s]

 55%|█████▌    | 55693/100629 [43:47<31:22, 23.87it/s]

 55%|█████▌    | 55696/100629 [43:47<32:46, 22.85it/s]

 55%|█████▌    | 55699/100629 [43:47<41:22, 18.10it/s]

 55%|█████▌    | 55702/100629 [43:47<40:14, 18.61it/s]

 55%|█████▌    | 55705/100629 [43:47<39:36, 18.90it/s]

 55%|█████▌    | 55708/100629 [43:48<37:54, 19.75it/s]

 55%|█████▌    | 55711/100629 [43:48<37:38, 19.89it/s]

 55%|█████▌    | 55714/100629 [43:48<37:08, 20.15it/s]

 55%|█████▌    | 55718/100629 [43:48<33:55, 22.06it/s]

 55%|█████▌    | 55722/100629 [43:48<31:21, 23.87it/s]

 55%|█████▌    | 55725/100629 [43:48<31:52, 23.48it/s]

 55%|█████▌    | 55729/100629 [43:48<28:51, 25.94it/s]

 55%|█████▌    | 55732/100629 [43:49<33:35, 22.27it/s]

 55%|█████▌    | 55735/100629 [43:49<35:20, 21.18it/s]

 55%|█████▌    | 55738/100629 [43:49<33:47, 22.14it/s]

 55%|█████▌    | 55741/100629 [43:49<33:54, 22.06it/s]

 55%|█████▌    | 55744/100629 [43:49<36:15, 20.64it/s]

 55%|█████▌    | 55747/100629 [43:49<35:44, 20.93it/s]

 55%|█████▌    | 55750/100629 [43:49<34:10, 21.89it/s]

 55%|█████▌    | 55753/100629 [43:50<32:35, 22.95it/s]

 55%|█████▌    | 55756/100629 [43:50<36:53, 20.28it/s]

 55%|█████▌    | 55759/100629 [43:50<38:19, 19.51it/s]

 55%|█████▌    | 55762/100629 [43:50<39:43, 18.83it/s]

 55%|█████▌    | 55764/100629 [43:50<46:53, 15.95it/s]

 55%|█████▌    | 55766/100629 [43:50<48:14, 15.50it/s]

 55%|█████▌    | 55768/100629 [43:51<45:47, 16.33it/s]

 55%|█████▌    | 55770/100629 [43:51<47:01, 15.90it/s]

 55%|█████▌    | 55772/100629 [43:51<44:36, 16.76it/s]

 55%|█████▌    | 55775/100629 [43:51<38:03, 19.64it/s]

 55%|█████▌    | 55778/100629 [43:51<42:13, 17.71it/s]

 55%|█████▌    | 55781/100629 [43:51<37:56, 19.70it/s]

 55%|█████▌    | 55784/100629 [43:51<46:21, 16.12it/s]

 55%|█████▌    | 55786/100629 [43:52<46:49, 15.96it/s]

 55%|█████▌    | 55788/100629 [43:52<45:54, 16.28it/s]

 55%|█████▌    | 55790/100629 [43:52<44:41, 16.72it/s]

 55%|█████▌    | 55794/100629 [43:52<35:24, 21.10it/s]

 55%|█████▌    | 55797/100629 [43:52<36:27, 20.50it/s]

 55%|█████▌    | 55800/100629 [43:52<34:42, 21.52it/s]

 55%|█████▌    | 55803/100629 [43:52<33:37, 22.22it/s]

 55%|█████▌    | 55806/100629 [43:53<39:59, 18.68it/s]

 55%|█████▌    | 55810/100629 [43:53<33:30, 22.29it/s]

 55%|█████▌    | 55813/100629 [43:53<32:43, 22.82it/s]

 55%|█████▌    | 55816/100629 [43:53<38:11, 19.55it/s]

 55%|█████▌    | 55819/100629 [43:53<37:56, 19.69it/s]

 55%|█████▌    | 55822/100629 [43:53<40:19, 18.52it/s]

 55%|█████▌    | 55825/100629 [43:53<36:35, 20.40it/s]

 55%|█████▌    | 55829/100629 [43:54<30:41, 24.32it/s]

 55%|█████▌    | 55832/100629 [43:54<32:48, 22.76it/s]

 55%|█████▌    | 55835/100629 [43:54<31:37, 23.61it/s]

 55%|█████▌    | 55838/100629 [43:54<34:24, 21.70it/s]

 55%|█████▌    | 55842/100629 [43:54<29:01, 25.72it/s]

 55%|█████▌    | 55846/100629 [43:54<27:16, 27.36it/s]

 56%|█████▌    | 55850/100629 [43:54<26:37, 28.03it/s]

 56%|█████▌    | 55853/100629 [43:54<26:54, 27.73it/s]

 56%|█████▌    | 55857/100629 [43:55<25:47, 28.94it/s]

 56%|█████▌    | 55861/100629 [43:55<25:00, 29.83it/s]

 56%|█████▌    | 55865/100629 [43:55<33:36, 22.20it/s]

 56%|█████▌    | 55868/100629 [43:55<32:48, 22.74it/s]

 56%|█████▌    | 55871/100629 [43:55<33:42, 22.13it/s]

 56%|█████▌    | 55874/100629 [43:55<32:58, 22.62it/s]

 56%|█████▌    | 55877/100629 [43:56<35:38, 20.92it/s]

 56%|█████▌    | 55880/100629 [43:56<35:26, 21.05it/s]

 56%|█████▌    | 55883/100629 [43:56<33:32, 22.23it/s]

 56%|█████▌    | 55886/100629 [43:56<31:10, 23.92it/s]

 56%|█████▌    | 55889/100629 [43:56<34:20, 21.71it/s]

 56%|█████▌    | 55892/100629 [43:56<34:07, 21.85it/s]

 56%|█████▌    | 55896/100629 [43:56<29:30, 25.27it/s]

 56%|█████▌    | 55899/100629 [43:56<31:19, 23.80it/s]

 56%|█████▌    | 55902/100629 [43:57<32:27, 22.97it/s]

 56%|█████▌    | 55905/100629 [43:57<38:59, 19.11it/s]

 56%|█████▌    | 55908/100629 [43:57<36:57, 20.17it/s]

 56%|█████▌    | 55911/100629 [43:57<33:26, 22.29it/s]

 56%|█████▌    | 55914/100629 [43:57<30:58, 24.06it/s]

 56%|█████▌    | 55917/100629 [43:57<29:42, 25.09it/s]

 56%|█████▌    | 55920/100629 [43:57<32:17, 23.08it/s]

 56%|█████▌    | 55925/100629 [43:58<27:14, 27.34it/s]

 56%|█████▌    | 55928/100629 [43:58<34:47, 21.41it/s]

 56%|█████▌    | 55931/100629 [43:58<37:19, 19.96it/s]

 56%|█████▌    | 55936/100629 [43:58<31:13, 23.86it/s]

 56%|█████▌    | 55939/100629 [43:58<31:38, 23.53it/s]

 56%|█████▌    | 55942/100629 [43:58<32:28, 22.93it/s]

 56%|█████▌    | 55945/100629 [43:59<32:33, 22.88it/s]

 56%|█████▌    | 55948/100629 [43:59<32:04, 23.21it/s]

 56%|█████▌    | 55951/100629 [43:59<35:47, 20.80it/s]

 56%|█████▌    | 55955/100629 [43:59<30:50, 24.14it/s]

 56%|█████▌    | 55958/100629 [43:59<37:24, 19.90it/s]

 56%|█████▌    | 55961/100629 [43:59<36:37, 20.32it/s]

 56%|█████▌    | 55964/100629 [43:59<37:16, 19.97it/s]

 56%|█████▌    | 55967/100629 [44:00<38:36, 19.28it/s]

 56%|█████▌    | 55971/100629 [44:00<35:39, 20.87it/s]

 56%|█████▌    | 55974/100629 [44:00<35:34, 20.92it/s]

 56%|█████▌    | 55977/100629 [44:00<33:56, 21.93it/s]

 56%|█████▌    | 55980/100629 [44:00<36:08, 20.59it/s]

 56%|█████▌    | 55983/100629 [44:00<36:56, 20.14it/s]

 56%|█████▌    | 55987/100629 [44:01<30:33, 24.35it/s]

 56%|█████▌    | 55991/100629 [44:01<28:19, 26.26it/s]

 56%|█████▌    | 55994/100629 [44:01<31:59, 23.25it/s]

 56%|█████▌    | 55997/100629 [44:01<35:48, 20.77it/s]

 56%|█████▌    | 56001/100629 [44:01<31:35, 23.55it/s]

 56%|█████▌    | 56004/100629 [44:01<31:35, 23.54it/s]

 56%|█████▌    | 56009/100629 [44:01<25:50, 28.78it/s]

 56%|█████▌    | 56013/100629 [44:02<28:49, 25.79it/s]

 56%|█████▌    | 56016/100629 [44:02<35:01, 21.23it/s]

 56%|█████▌    | 56021/100629 [44:02<29:47, 24.96it/s]

 56%|█████▌    | 56025/100629 [44:02<27:30, 27.03it/s]

 56%|█████▌    | 56028/100629 [44:02<28:42, 25.90it/s]

 56%|█████▌    | 56031/100629 [44:02<28:57, 25.66it/s]

 56%|█████▌    | 56035/100629 [44:02<28:05, 26.45it/s]

 56%|█████▌    | 56038/100629 [44:03<32:55, 22.58it/s]

 56%|█████▌    | 56041/100629 [44:03<34:41, 21.42it/s]

 56%|█████▌    | 56044/100629 [44:03<41:38, 17.84it/s]

 56%|█████▌    | 56046/100629 [44:03<48:09, 15.43it/s]

 56%|█████▌    | 56049/100629 [44:03<44:06, 16.84it/s]

 56%|█████▌    | 56052/100629 [44:03<38:12, 19.45it/s]

 56%|█████▌    | 56055/100629 [44:04<36:28, 20.36it/s]

 56%|█████▌    | 56058/100629 [44:04<35:07, 21.15it/s]

 56%|█████▌    | 56061/100629 [44:04<34:23, 21.59it/s]

 56%|█████▌    | 56064/100629 [44:04<31:50, 23.32it/s]

 56%|█████▌    | 56067/100629 [44:04<31:10, 23.82it/s]

 56%|█████▌    | 56073/100629 [44:04<23:47, 31.20it/s]

 56%|█████▌    | 56077/100629 [44:04<24:56, 29.77it/s]

 56%|█████▌    | 56081/100629 [44:05<29:54, 24.83it/s]

 56%|█████▌    | 56084/100629 [44:05<29:04, 25.54it/s]

 56%|█████▌    | 56087/100629 [44:05<39:48, 18.65it/s]

 56%|█████▌    | 56090/100629 [44:05<37:08, 19.99it/s]

 56%|█████▌    | 56093/100629 [44:05<35:46, 20.75it/s]

 56%|█████▌    | 56096/100629 [44:05<40:28, 18.34it/s]

 56%|█████▌    | 56099/100629 [44:06<44:52, 16.54it/s]

 56%|█████▌    | 56102/100629 [44:06<40:08, 18.49it/s]

 56%|█████▌    | 56105/100629 [44:06<40:52, 18.16it/s]

 56%|█████▌    | 56107/100629 [44:06<42:15, 17.56it/s]

 56%|█████▌    | 56109/100629 [44:06<44:19, 16.74it/s]

 56%|█████▌    | 56111/100629 [44:06<46:07, 16.09it/s]

 56%|█████▌    | 56113/100629 [44:06<46:15, 16.04it/s]

 56%|█████▌    | 56115/100629 [44:07<56:02, 13.24it/s]

 56%|█████▌    | 56117/100629 [44:07<54:36, 13.58it/s]

 56%|█████▌    | 56119/100629 [44:07<58:15, 12.73it/s]

 56%|█████▌    | 56123/100629 [44:07<45:59, 16.13it/s]

 56%|█████▌    | 56127/100629 [44:07<36:08, 20.52it/s]

 56%|█████▌    | 56130/100629 [44:07<40:20, 18.38it/s]

 56%|█████▌    | 56133/100629 [44:08<36:08, 20.52it/s]

 56%|█████▌    | 56136/100629 [44:08<35:00, 21.18it/s]

 56%|█████▌    | 56139/100629 [44:08<35:23, 20.95it/s]

 56%|█████▌    | 56142/100629 [44:08<35:18, 21.00it/s]

 56%|█████▌    | 56145/100629 [44:08<33:56, 21.84it/s]

 56%|█████▌    | 56148/100629 [44:08<37:49, 19.60it/s]

 56%|█████▌    | 56151/100629 [44:09<41:14, 17.97it/s]

 56%|█████▌    | 56154/100629 [44:09<38:50, 19.09it/s]

 56%|█████▌    | 56157/100629 [44:09<37:39, 19.68it/s]

 56%|█████▌    | 56160/100629 [44:09<46:26, 15.96it/s]

 56%|█████▌    | 56162/100629 [44:09<46:36, 15.90it/s]

 56%|█████▌    | 56166/100629 [44:09<37:42, 19.65it/s]

 56%|█████▌    | 56169/100629 [44:09<39:58, 18.54it/s]

 56%|█████▌    | 56173/100629 [44:10<33:25, 22.17it/s]

 56%|█████▌    | 56176/100629 [44:10<33:20, 22.22it/s]

 56%|█████▌    | 56179/100629 [44:10<35:42, 20.75it/s]

 56%|█████▌    | 56184/100629 [44:10<37:11, 19.91it/s]

 56%|█████▌    | 56187/100629 [44:10<34:33, 21.44it/s]

 56%|█████▌    | 56190/100629 [44:10<34:37, 21.39it/s]

 56%|█████▌    | 56194/100629 [44:11<30:30, 24.27it/s]

 56%|█████▌    | 56197/100629 [44:11<31:38, 23.40it/s]

 56%|█████▌    | 56200/100629 [44:11<35:54, 20.62it/s]

 56%|█████▌    | 56203/100629 [44:11<42:05, 17.59it/s]

 56%|█████▌    | 56206/100629 [44:11<38:36, 19.18it/s]

 56%|█████▌    | 56209/100629 [44:11<34:54, 21.21it/s]

 56%|█████▌    | 56213/100629 [44:11<29:23, 25.19it/s]

 56%|█████▌    | 56217/100629 [44:12<28:16, 26.18it/s]

 56%|█████▌    | 56220/100629 [44:12<29:37, 24.98it/s]

 56%|█████▌    | 56223/100629 [44:12<28:28, 25.99it/s]

 56%|█████▌    | 56226/100629 [44:12<37:32, 19.72it/s]

 56%|█████▌    | 56229/100629 [44:12<41:08, 17.98it/s]

 56%|█████▌    | 56232/100629 [44:12<41:40, 17.75it/s]

 56%|█████▌    | 56235/100629 [44:13<36:47, 20.11it/s]

 56%|█████▌    | 56240/100629 [44:13<33:09, 22.32it/s]

 56%|█████▌    | 56243/100629 [44:13<35:39, 20.74it/s]

 56%|█████▌    | 56246/100629 [44:13<32:56, 22.45it/s]

 56%|█████▌    | 56249/100629 [44:13<34:55, 21.17it/s]

 56%|█████▌    | 56253/100629 [44:13<30:11, 24.50it/s]

 56%|█████▌    | 56257/100629 [44:13<30:10, 24.51it/s]

 56%|█████▌    | 56260/100629 [44:14<32:39, 22.64it/s]

 56%|█████▌    | 56263/100629 [44:14<36:08, 20.46it/s]

 56%|█████▌    | 56266/100629 [44:14<39:40, 18.64it/s]

 56%|█████▌    | 56269/100629 [44:14<35:46, 20.67it/s]

 56%|█████▌    | 56272/100629 [44:14<32:53, 22.48it/s]

 56%|█████▌    | 56277/100629 [44:14<26:27, 27.94it/s]

 56%|█████▌    | 56281/100629 [44:15<28:36, 25.84it/s]

 56%|█████▌    | 56284/100629 [44:15<34:10, 21.62it/s]

 56%|█████▌    | 56287/100629 [44:15<37:05, 19.92it/s]

 56%|█████▌    | 56290/100629 [44:15<40:02, 18.46it/s]

 56%|█████▌    | 56293/100629 [44:15<38:51, 19.01it/s]

 56%|█████▌    | 56295/100629 [44:15<38:47, 19.05it/s]

 56%|█████▌    | 56297/100629 [44:15<39:52, 18.53it/s]

 56%|█████▌    | 56300/100629 [44:16<36:31, 20.23it/s]

 56%|█████▌    | 56303/100629 [44:16<42:03, 17.56it/s]

 56%|█████▌    | 56305/100629 [44:16<41:01, 18.01it/s]

 56%|█████▌    | 56308/100629 [44:16<35:55, 20.56it/s]

 56%|█████▌    | 56311/100629 [44:16<42:32, 17.36it/s]

 56%|█████▌    | 56315/100629 [44:16<33:36, 21.97it/s]

 56%|█████▌    | 56318/100629 [44:16<31:57, 23.11it/s]

 56%|█████▌    | 56321/100629 [44:17<30:55, 23.88it/s]

 56%|█████▌    | 56324/100629 [44:17<30:18, 24.37it/s]

 56%|█████▌    | 56328/100629 [44:17<28:50, 25.60it/s]

 56%|█████▌    | 56331/100629 [44:17<30:02, 24.58it/s]

 56%|█████▌    | 56334/100629 [44:17<30:30, 24.19it/s]

 56%|█████▌    | 56337/100629 [44:17<31:55, 23.12it/s]

 56%|█████▌    | 56340/100629 [44:17<30:39, 24.08it/s]

 56%|█████▌    | 56344/100629 [44:17<28:40, 25.74it/s]

 56%|█████▌    | 56347/100629 [44:18<28:53, 25.55it/s]

 56%|█████▌    | 56350/100629 [44:18<35:14, 20.94it/s]

 56%|█████▌    | 56354/100629 [44:18<30:02, 24.57it/s]

 56%|█████▌    | 56357/100629 [44:18<33:54, 21.76it/s]

 56%|█████▌    | 56360/100629 [44:18<32:42, 22.56it/s]

 56%|█████▌    | 56363/100629 [44:18<32:37, 22.62it/s]

 56%|█████▌    | 56367/100629 [44:18<29:28, 25.03it/s]

 56%|█████▌    | 56370/100629 [44:19<28:13, 26.14it/s]

 56%|█████▌    | 56375/100629 [44:19<24:56, 29.57it/s]

 56%|█████▌    | 56378/100629 [44:19<31:10, 23.65it/s]

 56%|█████▌    | 56381/100629 [44:19<30:35, 24.11it/s]

 56%|█████▌    | 56384/100629 [44:19<31:03, 23.74it/s]

 56%|█████▌    | 56387/100629 [44:19<33:07, 22.26it/s]

 56%|█████▌    | 56390/100629 [44:19<31:34, 23.36it/s]

 56%|█████▌    | 56394/100629 [44:20<29:36, 24.90it/s]

 56%|█████▌    | 56398/100629 [44:20<28:13, 26.13it/s]

 56%|█████▌    | 56401/100629 [44:20<32:30, 22.68it/s]

 56%|█████▌    | 56404/100629 [44:20<35:59, 20.48it/s]

 56%|█████▌    | 56407/100629 [44:20<37:31, 19.64it/s]

 56%|█████▌    | 56412/100629 [44:20<31:22, 23.49it/s]

 56%|█████▌    | 56415/100629 [44:21<32:29, 22.68it/s]

 56%|█████▌    | 56420/100629 [44:21<26:10, 28.16it/s]

 56%|█████▌    | 56424/100629 [44:21<25:42, 28.65it/s]

 56%|█████▌    | 56428/100629 [44:21<25:58, 28.37it/s]

 56%|█████▌    | 56431/100629 [44:21<32:33, 22.62it/s]

 56%|█████▌    | 56435/100629 [44:21<31:26, 23.43it/s]

 56%|█████▌    | 56438/100629 [44:21<34:39, 21.25it/s]

 56%|█████▌    | 56441/100629 [44:22<37:00, 19.90it/s]

 56%|█████▌    | 56444/100629 [44:22<34:13, 21.52it/s]

 56%|█████▌    | 56447/100629 [44:22<45:53, 16.05it/s]

 56%|█████▌    | 56450/100629 [44:22<40:23, 18.23it/s]

 56%|█████▌    | 56453/100629 [44:22<36:59, 19.90it/s]

 56%|█████▌    | 56456/100629 [44:22<34:03, 21.62it/s]

 56%|█████▌    | 56459/100629 [44:23<35:51, 20.53it/s]

 56%|█████▌    | 56462/100629 [44:23<36:46, 20.02it/s]

 56%|█████▌    | 56465/100629 [44:23<40:03, 18.37it/s]

 56%|█████▌    | 56467/100629 [44:23<41:40, 17.66it/s]

 56%|█████▌    | 56469/100629 [44:23<44:38, 16.48it/s]

 56%|█████▌    | 56472/100629 [44:23<38:31, 19.10it/s]

 56%|█████▌    | 56475/100629 [44:24<43:01, 17.11it/s]

 56%|█████▌    | 56477/100629 [44:24<41:55, 17.55it/s]

 56%|█████▌    | 56481/100629 [44:24<33:41, 21.84it/s]

 56%|█████▌    | 56484/100629 [44:24<31:08, 23.63it/s]

 56%|█████▌    | 56487/100629 [44:24<32:31, 22.63it/s]

 56%|█████▌    | 56490/100629 [44:24<36:24, 20.21it/s]

 56%|█████▌    | 56494/100629 [44:24<33:33, 21.91it/s]

 56%|█████▌    | 56497/100629 [44:25<35:38, 20.64it/s]

 56%|█████▌    | 56500/100629 [44:25<36:25, 20.19it/s]

 56%|█████▌    | 56503/100629 [44:25<34:02, 21.61it/s]

 56%|█████▌    | 56507/100629 [44:25<31:41, 23.20it/s]

 56%|█████▌    | 56510/100629 [44:25<34:09, 21.53it/s]

 56%|█████▌    | 56513/100629 [44:25<33:06, 22.21it/s]

 56%|█████▌    | 56516/100629 [44:25<34:59, 21.01it/s]

 56%|█████▌    | 56519/100629 [44:26<34:00, 21.61it/s]

 56%|█████▌    | 56522/100629 [44:26<40:12, 18.28it/s]

 56%|█████▌    | 56526/100629 [44:26<34:29, 21.31it/s]

 56%|█████▌    | 56529/100629 [44:26<33:29, 21.94it/s]

 56%|█████▌    | 56532/100629 [44:26<33:08, 22.18it/s]

 56%|█████▌    | 56535/100629 [44:26<37:01, 19.85it/s]

 56%|█████▌    | 56538/100629 [44:26<38:35, 19.04it/s]

 56%|█████▌    | 56540/100629 [44:27<39:49, 18.45it/s]

 56%|█████▌    | 56544/100629 [44:27<32:06, 22.88it/s]

 56%|█████▌    | 56548/100629 [44:27<27:52, 26.35it/s]

 56%|█████▌    | 56551/100629 [44:27<28:45, 25.54it/s]

 56%|█████▌    | 56554/100629 [44:27<29:06, 25.24it/s]

 56%|█████▌    | 56557/100629 [44:27<35:55, 20.44it/s]

 56%|█████▌    | 56561/100629 [44:27<32:30, 22.59it/s]

 56%|█████▌    | 56564/100629 [44:28<31:07, 23.59it/s]

 56%|█████▌    | 56568/100629 [44:28<28:36, 25.67it/s]

 56%|█████▌    | 56572/100629 [44:28<28:12, 26.04it/s]

 56%|█████▌    | 56575/100629 [44:28<29:50, 24.60it/s]

 56%|█████▌    | 56578/100629 [44:28<29:25, 24.95it/s]

 56%|█████▌    | 56581/100629 [44:28<29:05, 25.24it/s]

 56%|█████▌    | 56584/100629 [44:28<34:55, 21.02it/s]

 56%|█████▌    | 56587/100629 [44:29<33:20, 22.01it/s]

 56%|█████▌    | 56591/100629 [44:29<28:24, 25.84it/s]

 56%|█████▌    | 56594/100629 [44:29<27:46, 26.42it/s]

 56%|█████▌    | 56597/100629 [44:29<31:43, 23.13it/s]

 56%|█████▌    | 56600/100629 [44:29<35:00, 20.96it/s]

 56%|█████▌    | 56603/100629 [44:29<35:37, 20.60it/s]

 56%|█████▋    | 56606/100629 [44:29<33:35, 21.84it/s]

 56%|█████▋    | 56610/100629 [44:30<32:32, 22.55it/s]

 56%|█████▋    | 56613/100629 [44:30<35:11, 20.84it/s]

 56%|█████▋    | 56616/100629 [44:30<34:28, 21.28it/s]

 56%|█████▋    | 56619/100629 [44:30<35:15, 20.80it/s]

 56%|█████▋    | 56622/100629 [44:30<33:40, 21.78it/s]

 56%|█████▋    | 56625/100629 [44:30<33:04, 22.18it/s]

 56%|█████▋    | 56629/100629 [44:30<28:42, 25.54it/s]

 56%|█████▋    | 56632/100629 [44:30<27:33, 26.60it/s]

 56%|█████▋    | 56635/100629 [44:31<30:51, 23.76it/s]

 56%|█████▋    | 56639/100629 [44:31<29:39, 24.72it/s]

 56%|█████▋    | 56642/100629 [44:31<30:53, 23.74it/s]

 56%|█████▋    | 56645/100629 [44:31<34:05, 21.50it/s]

 56%|█████▋    | 56648/100629 [44:31<34:13, 21.41it/s]

 56%|█████▋    | 56651/100629 [44:31<36:20, 20.17it/s]

 56%|█████▋    | 56654/100629 [44:32<38:51, 18.86it/s]

 56%|█████▋    | 56658/100629 [44:32<33:40, 21.76it/s]

 56%|█████▋    | 56661/100629 [44:32<35:55, 20.40it/s]

 56%|█████▋    | 56664/100629 [44:32<34:00, 21.55it/s]

 56%|█████▋    | 56667/100629 [44:32<37:33, 19.51it/s]

 56%|█████▋    | 56670/100629 [44:32<39:15, 18.67it/s]

 56%|█████▋    | 56672/100629 [44:32<40:17, 18.19it/s]

 56%|█████▋    | 56675/100629 [44:33<36:38, 20.00it/s]

 56%|█████▋    | 56678/100629 [44:33<35:32, 20.61it/s]

 56%|█████▋    | 56681/100629 [44:33<33:26, 21.90it/s]

 56%|█████▋    | 56684/100629 [44:33<36:22, 20.14it/s]

 56%|█████▋    | 56687/100629 [44:33<36:20, 20.15it/s]

 56%|█████▋    | 56690/100629 [44:33<35:20, 20.72it/s]

 56%|█████▋    | 56694/100629 [44:33<31:16, 23.42it/s]

 56%|█████▋    | 56697/100629 [44:34<38:12, 19.16it/s]

 56%|█████▋    | 56700/100629 [44:34<40:53, 17.91it/s]

 56%|█████▋    | 56702/100629 [44:34<41:03, 17.83it/s]

 56%|█████▋    | 56706/100629 [44:34<36:03, 20.30it/s]

 56%|█████▋    | 56709/100629 [44:34<42:53, 17.06it/s]

 56%|█████▋    | 56712/100629 [44:34<37:30, 19.51it/s]

 56%|█████▋    | 56715/100629 [44:35<35:43, 20.48it/s]

 56%|█████▋    | 56718/100629 [44:35<46:08, 15.86it/s]

 56%|█████▋    | 56722/100629 [44:35<41:14, 17.75it/s]

 56%|█████▋    | 56725/100629 [44:35<39:25, 18.56it/s]

 56%|█████▋    | 56729/100629 [44:35<34:20, 21.30it/s]

 56%|█████▋    | 56732/100629 [44:36<36:05, 20.27it/s]

 56%|█████▋    | 56735/100629 [44:36<38:21, 19.07it/s]

 56%|█████▋    | 56738/100629 [44:36<34:59, 20.91it/s]

 56%|█████▋    | 56744/100629 [44:36<25:44, 28.42it/s]

 56%|█████▋    | 56748/100629 [44:36<27:29, 26.61it/s]

 56%|█████▋    | 56751/100629 [44:36<27:15, 26.83it/s]

 56%|█████▋    | 56754/100629 [44:36<29:09, 25.07it/s]

 56%|█████▋    | 56757/100629 [44:36<30:17, 24.14it/s]

 56%|█████▋    | 56761/100629 [44:37<29:07, 25.10it/s]

 56%|█████▋    | 56765/100629 [44:37<29:08, 25.08it/s]

 56%|█████▋    | 56768/100629 [44:37<33:13, 22.00it/s]

 56%|█████▋    | 56771/100629 [44:37<36:25, 20.06it/s]

 56%|█████▋    | 56774/100629 [44:37<35:45, 20.44it/s]

 56%|█████▋    | 56777/100629 [44:37<38:07, 19.17it/s]

 56%|█████▋    | 56779/100629 [44:38<40:47, 17.92it/s]

 56%|█████▋    | 56781/100629 [44:38<43:14, 16.90it/s]

 56%|█████▋    | 56785/100629 [44:38<33:44, 21.65it/s]

 56%|█████▋    | 56789/100629 [44:38<30:36, 23.88it/s]

 56%|█████▋    | 56792/100629 [44:38<33:25, 21.86it/s]

 56%|█████▋    | 56795/100629 [44:38<35:10, 20.77it/s]

 56%|█████▋    | 56798/100629 [44:38<35:59, 20.30it/s]

 56%|█████▋    | 56801/100629 [44:39<34:50, 20.97it/s]

 56%|█████▋    | 56806/100629 [44:39<30:14, 24.15it/s]

 56%|█████▋    | 56809/100629 [44:39<37:10, 19.65it/s]

 56%|█████▋    | 56812/100629 [44:39<40:58, 17.82it/s]

 56%|█████▋    | 56815/100629 [44:39<36:33, 19.98it/s]

 56%|█████▋    | 56818/100629 [44:39<33:46, 21.62it/s]

 56%|█████▋    | 56822/100629 [44:40<29:54, 24.41it/s]

 56%|█████▋    | 56825/100629 [44:40<34:42, 21.04it/s]

 56%|█████▋    | 56828/100629 [44:40<32:28, 22.48it/s]

 56%|█████▋    | 56832/100629 [44:40<31:49, 22.94it/s]

 56%|█████▋    | 56835/100629 [44:40<30:56, 23.59it/s]

 56%|█████▋    | 56838/100629 [44:40<35:18, 20.67it/s]

 56%|█████▋    | 56841/100629 [44:41<36:55, 19.77it/s]

 56%|█████▋    | 56844/100629 [44:41<42:25, 17.20it/s]

 56%|█████▋    | 56848/100629 [44:41<34:28, 21.16it/s]

 56%|█████▋    | 56851/100629 [44:41<32:12, 22.65it/s]

 56%|█████▋    | 56854/100629 [44:41<34:47, 20.97it/s]

 57%|█████▋    | 56857/100629 [44:41<34:26, 21.19it/s]

 57%|█████▋    | 56862/100629 [44:41<27:40, 26.36it/s]

 57%|█████▋    | 56865/100629 [44:42<29:11, 24.99it/s]

 57%|█████▋    | 56868/100629 [44:42<33:02, 22.07it/s]

 57%|█████▋    | 56872/100629 [44:42<34:21, 21.23it/s]

 57%|█████▋    | 56875/100629 [44:42<35:59, 20.26it/s]

 57%|█████▋    | 56878/100629 [44:42<33:12, 21.96it/s]

 57%|█████▋    | 56881/100629 [44:42<35:06, 20.77it/s]

 57%|█████▋    | 56884/100629 [44:43<36:24, 20.03it/s]

 57%|█████▋    | 56887/100629 [44:43<36:15, 20.11it/s]

 57%|█████▋    | 56890/100629 [44:43<37:53, 19.24it/s]

 57%|█████▋    | 56892/100629 [44:43<45:35, 15.99it/s]

 57%|█████▋    | 56894/100629 [44:43<49:56, 14.59it/s]

 57%|█████▋    | 56898/100629 [44:43<37:29, 19.44it/s]

 57%|█████▋    | 56901/100629 [44:43<34:52, 20.90it/s]

 57%|█████▋    | 56905/100629 [44:44<30:04, 24.24it/s]

 57%|█████▋    | 56908/100629 [44:44<31:42, 22.98it/s]

 57%|█████▋    | 56912/100629 [44:44<31:12, 23.35it/s]

 57%|█████▋    | 56915/100629 [44:44<33:04, 22.03it/s]

 57%|█████▋    | 56918/100629 [44:44<32:33, 22.38it/s]

 57%|█████▋    | 56921/100629 [44:44<35:29, 20.52it/s]

 57%|█████▋    | 56924/100629 [44:44<32:36, 22.34it/s]

 57%|█████▋    | 56927/100629 [44:45<31:17, 23.27it/s]

 57%|█████▋    | 56930/100629 [44:45<34:04, 21.37it/s]

 57%|█████▋    | 56933/100629 [44:45<39:19, 18.52it/s]

 57%|█████▋    | 56935/100629 [44:45<42:35, 17.10it/s]

 57%|█████▋    | 56938/100629 [44:45<39:23, 18.48it/s]

 57%|█████▋    | 56940/100629 [44:45<40:31, 17.97it/s]

 57%|█████▋    | 56944/100629 [44:45<33:12, 21.93it/s]

 57%|█████▋    | 56947/100629 [44:46<36:58, 19.69it/s]

 57%|█████▋    | 56951/100629 [44:46<30:30, 23.86it/s]

 57%|█████▋    | 56954/100629 [44:46<29:18, 24.84it/s]

 57%|█████▋    | 56957/100629 [44:46<37:47, 19.26it/s]

 57%|█████▋    | 56960/100629 [44:46<36:07, 20.14it/s]

 57%|█████▋    | 56963/100629 [44:46<34:40, 20.98it/s]

 57%|█████▋    | 56966/100629 [44:46<32:43, 22.24it/s]

 57%|█████▋    | 56969/100629 [44:47<34:29, 21.09it/s]

 57%|█████▋    | 56975/100629 [44:47<28:36, 25.43it/s]

 57%|█████▋    | 56979/100629 [44:47<27:24, 26.55it/s]

 57%|█████▋    | 56983/100629 [44:47<25:04, 29.01it/s]

 57%|█████▋    | 56987/100629 [44:47<26:14, 27.72it/s]

 57%|█████▋    | 56990/100629 [44:47<32:20, 22.48it/s]

 57%|█████▋    | 56994/100629 [44:48<28:55, 25.15it/s]

 57%|█████▋    | 56997/100629 [44:48<30:03, 24.19it/s]

 57%|█████▋    | 57000/100629 [44:48<33:44, 21.55it/s]

 57%|█████▋    | 57003/100629 [44:48<37:22, 19.46it/s]

 57%|█████▋    | 57006/100629 [44:48<38:08, 19.07it/s]

 57%|█████▋    | 57010/100629 [44:48<35:01, 20.76it/s]

 57%|█████▋    | 57013/100629 [44:49<34:14, 21.23it/s]

 57%|█████▋    | 57016/100629 [44:49<31:32, 23.05it/s]

 57%|█████▋    | 57019/100629 [44:49<31:32, 23.05it/s]

 57%|█████▋    | 57022/100629 [44:49<32:44, 22.20it/s]

 57%|█████▋    | 57025/100629 [44:49<31:25, 23.13it/s]

 57%|█████▋    | 57028/100629 [44:49<37:39, 19.30it/s]

 57%|█████▋    | 57031/100629 [44:49<36:10, 20.08it/s]

 57%|█████▋    | 57034/100629 [44:49<34:46, 20.89it/s]

 57%|█████▋    | 57037/100629 [44:50<34:41, 20.94it/s]

 57%|█████▋    | 57040/100629 [44:50<32:19, 22.47it/s]

 57%|█████▋    | 57044/100629 [44:50<30:25, 23.87it/s]

 57%|█████▋    | 57047/100629 [44:50<38:00, 19.11it/s]

 57%|█████▋    | 57050/100629 [44:50<36:54, 19.68it/s]

 57%|█████▋    | 57053/100629 [44:50<33:40, 21.56it/s]

 57%|█████▋    | 57057/100629 [44:51<30:16, 23.99it/s]

 57%|█████▋    | 57060/100629 [44:51<30:50, 23.55it/s]

 57%|█████▋    | 57063/100629 [44:51<31:51, 22.79it/s]

 57%|█████▋    | 57066/100629 [44:51<34:38, 20.96it/s]

 57%|█████▋    | 57069/100629 [44:51<34:28, 21.06it/s]

 57%|█████▋    | 57072/100629 [44:51<36:51, 19.70it/s]

 57%|█████▋    | 57076/100629 [44:51<31:11, 23.27it/s]

 57%|█████▋    | 57079/100629 [44:52<33:31, 21.65it/s]

 57%|█████▋    | 57082/100629 [44:52<30:52, 23.51it/s]

 57%|█████▋    | 57085/100629 [44:52<32:27, 22.36it/s]

 57%|█████▋    | 57088/100629 [44:52<30:27, 23.82it/s]

 57%|█████▋    | 57091/100629 [44:52<37:17, 19.45it/s]

 57%|█████▋    | 57094/100629 [44:52<35:15, 20.58it/s]

 57%|█████▋    | 57097/100629 [44:52<32:52, 22.07it/s]

 57%|█████▋    | 57102/100629 [44:53<27:08, 26.73it/s]

 57%|█████▋    | 57105/100629 [44:53<28:34, 25.39it/s]

 57%|█████▋    | 57108/100629 [44:53<27:22, 26.50it/s]

 57%|█████▋    | 57111/100629 [44:53<28:54, 25.10it/s]

 57%|█████▋    | 57114/100629 [44:53<32:22, 22.40it/s]

 57%|█████▋    | 57117/100629 [44:53<33:37, 21.57it/s]

 57%|█████▋    | 57120/100629 [44:53<31:09, 23.27it/s]

 57%|█████▋    | 57124/100629 [44:53<28:06, 25.80it/s]

 57%|█████▋    | 57127/100629 [44:54<30:53, 23.47it/s]

 57%|█████▋    | 57130/100629 [44:54<29:15, 24.78it/s]

 57%|█████▋    | 57133/100629 [44:54<33:44, 21.48it/s]

 57%|█████▋    | 57137/100629 [44:54<29:14, 24.79it/s]

 57%|█████▋    | 57142/100629 [44:54<28:19, 25.59it/s]

 57%|█████▋    | 57145/100629 [44:54<29:33, 24.51it/s]

 57%|█████▋    | 57149/100629 [44:54<27:07, 26.71it/s]

 57%|█████▋    | 57154/100629 [44:55<22:39, 31.97it/s]

 57%|█████▋    | 57158/100629 [44:55<25:47, 28.09it/s]

 57%|█████▋    | 57162/100629 [44:55<25:09, 28.79it/s]

 57%|█████▋    | 57166/100629 [44:55<33:22, 21.71it/s]

 57%|█████▋    | 57169/100629 [44:55<35:39, 20.31it/s]

 57%|█████▋    | 57172/100629 [44:56<38:08, 18.99it/s]

 57%|█████▋    | 57175/100629 [44:56<36:07, 20.05it/s]

 57%|█████▋    | 57178/100629 [44:56<38:52, 18.63it/s]

 57%|█████▋    | 57180/100629 [44:56<41:52, 17.29it/s]

 57%|█████▋    | 57183/100629 [44:56<38:42, 18.70it/s]

 57%|█████▋    | 57186/100629 [44:56<34:42, 20.86it/s]

 57%|█████▋    | 57190/100629 [44:56<32:14, 22.46it/s]

 57%|█████▋    | 57193/100629 [44:57<33:45, 21.45it/s]

 57%|█████▋    | 57197/100629 [44:57<32:16, 22.42it/s]

 57%|█████▋    | 57201/100629 [44:57<32:51, 22.03it/s]

 57%|█████▋    | 57204/100629 [44:57<32:45, 22.09it/s]

 57%|█████▋    | 57207/100629 [44:57<30:29, 23.74it/s]

 57%|█████▋    | 57211/100629 [44:57<26:57, 26.84it/s]

 57%|█████▋    | 57215/100629 [44:57<26:01, 27.81it/s]

 57%|█████▋    | 57218/100629 [44:58<31:26, 23.01it/s]

 57%|█████▋    | 57223/100629 [44:58<25:47, 28.05it/s]

 57%|█████▋    | 57227/100629 [44:58<24:58, 28.96it/s]

 57%|█████▋    | 57231/100629 [44:58<24:16, 29.80it/s]

 57%|█████▋    | 57235/100629 [44:58<29:50, 24.24it/s]

 57%|█████▋    | 57238/100629 [44:58<33:13, 21.77it/s]

 57%|█████▋    | 57241/100629 [44:59<38:43, 18.68it/s]

 57%|█████▋    | 57244/100629 [44:59<35:10, 20.56it/s]

 57%|█████▋    | 57247/100629 [44:59<37:20, 19.36it/s]

 57%|█████▋    | 57250/100629 [44:59<34:02, 21.24it/s]

 57%|█████▋    | 57253/100629 [44:59<40:27, 17.87it/s]

 57%|█████▋    | 57256/100629 [44:59<43:59, 16.43it/s]

 57%|█████▋    | 57259/100629 [45:00<43:05, 16.77it/s]

 57%|█████▋    | 57263/100629 [45:00<39:19, 18.38it/s]

 57%|█████▋    | 57265/100629 [45:00<40:44, 17.74it/s]

 57%|█████▋    | 57267/100629 [45:00<1:06:57, 10.79it/s]

 57%|█████▋    | 57269/100629 [45:00<1:02:09, 11.63it/s]

 57%|█████▋    | 57272/100629 [45:01<51:38, 13.99it/s]

 57%|█████▋    | 57275/100629 [45:01<45:08, 16.01it/s]

 57%|█████▋    | 57277/100629 [45:01<44:33, 16.22it/s]

 57%|█████▋    | 57280/100629 [45:01<44:11, 16.35it/s]

 57%|█████▋    | 57284/100629 [45:01<36:46, 19.64it/s]

 57%|█████▋    | 57287/100629 [45:01<33:23, 21.64it/s]

 57%|█████▋    | 57291/100629 [45:01<28:18, 25.51it/s]

 57%|█████▋    | 57294/100629 [45:02<30:12, 23.91it/s]

 57%|█████▋    | 57297/100629 [45:02<37:47, 19.11it/s]

 57%|█████▋    | 57301/100629 [45:02<31:08, 23.19it/s]

 57%|█████▋    | 57305/100629 [45:02<29:49, 24.22it/s]

 57%|█████▋    | 57308/100629 [45:02<32:27, 22.25it/s]

 57%|█████▋    | 57311/100629 [45:02<31:33, 22.88it/s]

 57%|█████▋    | 57315/100629 [45:02<29:11, 24.73it/s]

 57%|█████▋    | 57319/100629 [45:03<26:28, 27.26it/s]

 57%|█████▋    | 57325/100629 [45:03<21:18, 33.86it/s]

 57%|█████▋    | 57329/100629 [45:03<20:30, 35.19it/s]

 57%|█████▋    | 57334/100629 [45:03<22:17, 32.36it/s]

 57%|█████▋    | 57338/100629 [45:03<24:50, 29.04it/s]

 57%|█████▋    | 57342/100629 [45:03<23:23, 30.83it/s]

 57%|█████▋    | 57346/100629 [45:03<26:21, 27.37it/s]

 57%|█████▋    | 57349/100629 [45:04<25:58, 27.78it/s]

 57%|█████▋    | 57352/100629 [45:04<30:06, 23.96it/s]

 57%|█████▋    | 57355/100629 [45:04<31:56, 22.58it/s]

 57%|█████▋    | 57358/100629 [45:04<33:59, 21.21it/s]

 57%|█████▋    | 57361/100629 [45:04<31:17, 23.04it/s]

 57%|█████▋    | 57364/100629 [45:04<35:01, 20.58it/s]

 57%|█████▋    | 57367/100629 [45:04<38:53, 18.54it/s]

 57%|█████▋    | 57369/100629 [45:05<41:31, 17.36it/s]

 57%|█████▋    | 57371/100629 [45:05<43:23, 16.62it/s]

 57%|█████▋    | 57373/100629 [45:05<52:46, 13.66it/s]

 57%|█████▋    | 57375/100629 [45:05<48:23, 14.90it/s]

 57%|█████▋    | 57379/100629 [45:05<36:07, 19.95it/s]

 57%|█████▋    | 57382/100629 [45:05<42:40, 16.89it/s]

 57%|█████▋    | 57386/100629 [45:06<35:47, 20.13it/s]

 57%|█████▋    | 57390/100629 [45:06<32:17, 22.31it/s]

 57%|█████▋    | 57393/100629 [45:06<30:03, 23.98it/s]

 57%|█████▋    | 57396/100629 [45:06<28:52, 24.95it/s]

 57%|█████▋    | 57399/100629 [45:06<32:41, 22.04it/s]

 57%|█████▋    | 57402/100629 [45:06<31:41, 22.73it/s]

 57%|█████▋    | 57405/100629 [45:06<30:15, 23.81it/s]

 57%|█████▋    | 57408/100629 [45:06<32:16, 22.32it/s]

 57%|█████▋    | 57411/100629 [45:07<32:21, 22.26it/s]

 57%|█████▋    | 57414/100629 [45:07<33:07, 21.75it/s]

 57%|█████▋    | 57417/100629 [45:07<31:34, 22.81it/s]

 57%|█████▋    | 57420/100629 [45:07<36:19, 19.83it/s]

 57%|█████▋    | 57423/100629 [45:07<33:52, 21.26it/s]

 57%|█████▋    | 57426/100629 [45:07<34:59, 20.58it/s]

 57%|█████▋    | 57429/100629 [45:08<34:22, 20.94it/s]

 57%|█████▋    | 57433/100629 [45:08<30:24, 23.67it/s]

 57%|█████▋    | 57436/100629 [45:08<34:09, 21.07it/s]

 57%|█████▋    | 57439/100629 [45:08<37:15, 19.32it/s]

 57%|█████▋    | 57442/100629 [45:08<33:57, 21.20it/s]

 57%|█████▋    | 57447/100629 [45:08<26:16, 27.38it/s]

 57%|█████▋    | 57450/100629 [45:08<28:29, 25.25it/s]

 57%|█████▋    | 57454/100629 [45:08<25:19, 28.41it/s]

 57%|█████▋    | 57458/100629 [45:09<24:52, 28.92it/s]

 57%|█████▋    | 57462/100629 [45:09<29:02, 24.77it/s]

 57%|█████▋    | 57465/100629 [45:09<29:52, 24.08it/s]

 57%|█████▋    | 57468/100629 [45:09<29:53, 24.06it/s]

 57%|█████▋    | 57471/100629 [45:09<37:19, 19.27it/s]

 57%|█████▋    | 57474/100629 [45:09<34:27, 20.87it/s]

 57%|█████▋    | 57478/100629 [45:10<30:08, 23.86it/s]

 57%|█████▋    | 57482/100629 [45:10<26:21, 27.29it/s]

 57%|█████▋    | 57485/100629 [45:10<29:20, 24.51it/s]

 57%|█████▋    | 57490/100629 [45:10<25:22, 28.33it/s]

 57%|█████▋    | 57493/100629 [45:10<26:00, 27.65it/s]

 57%|█████▋    | 57496/100629 [45:10<26:49, 26.80it/s]

 57%|█████▋    | 57499/100629 [45:10<31:08, 23.08it/s]

 57%|█████▋    | 57503/100629 [45:11<32:01, 22.44it/s]

 57%|█████▋    | 57506/100629 [45:11<36:46, 19.55it/s]

 57%|█████▋    | 57509/100629 [45:11<38:08, 18.85it/s]

 57%|█████▋    | 57512/100629 [45:11<35:38, 20.16it/s]

 57%|█████▋    | 57515/100629 [45:11<37:20, 19.24it/s]

 57%|█████▋    | 57519/100629 [45:11<30:36, 23.47it/s]

 57%|█████▋    | 57522/100629 [45:11<30:33, 23.51it/s]

 57%|█████▋    | 57525/100629 [45:12<29:35, 24.27it/s]

 57%|█████▋    | 57528/100629 [45:12<33:17, 21.58it/s]

 57%|█████▋    | 57531/100629 [45:12<30:51, 23.28it/s]

 57%|█████▋    | 57534/100629 [45:12<31:12, 23.01it/s]

 57%|█████▋    | 57537/100629 [45:12<31:02, 23.14it/s]

 57%|█████▋    | 57540/100629 [45:12<35:38, 20.15it/s]

 57%|█████▋    | 57545/100629 [45:12<29:44, 24.15it/s]

 57%|█████▋    | 57548/100629 [45:13<33:37, 21.36it/s]

 57%|█████▋    | 57551/100629 [45:13<32:52, 21.83it/s]

 57%|█████▋    | 57554/100629 [45:13<39:50, 18.02it/s]

 57%|█████▋    | 57556/100629 [45:13<43:37, 16.45it/s]

 57%|█████▋    | 57558/100629 [45:13<42:00, 17.09it/s]

 57%|█████▋    | 57561/100629 [45:13<36:26, 19.70it/s]

 57%|█████▋    | 57564/100629 [45:14<38:31, 18.63it/s]

 57%|█████▋    | 57568/100629 [45:14<33:29, 21.43it/s]

 57%|█████▋    | 57571/100629 [45:14<33:53, 21.17it/s]

 57%|█████▋    | 57574/100629 [45:14<36:51, 19.46it/s]

 57%|█████▋    | 57578/100629 [45:14<34:54, 20.56it/s]

 57%|█████▋    | 57581/100629 [45:14<35:12, 20.37it/s]

 57%|█████▋    | 57584/100629 [45:14<35:14, 20.36it/s]

 57%|█████▋    | 57587/100629 [45:15<35:44, 20.07it/s]

 57%|█████▋    | 57590/100629 [45:15<38:04, 18.84it/s]

 57%|█████▋    | 57593/100629 [45:15<35:38, 20.12it/s]

 57%|█████▋    | 57597/100629 [45:15<31:44, 22.60it/s]

 57%|█████▋    | 57600/100629 [45:15<35:28, 20.22it/s]

 57%|█████▋    | 57603/100629 [45:16<44:06, 16.26it/s]

 57%|█████▋    | 57605/100629 [45:16<44:51, 15.99it/s]

 57%|█████▋    | 57608/100629 [45:16<40:12, 17.83it/s]

 57%|█████▋    | 57611/100629 [45:16<38:20, 18.70it/s]

 57%|█████▋    | 57614/100629 [45:16<36:48, 19.47it/s]

 57%|█████▋    | 57617/100629 [45:16<35:04, 20.44it/s]

 57%|█████▋    | 57620/100629 [45:16<38:11, 18.77it/s]

 57%|█████▋    | 57622/100629 [45:17<42:47, 16.75it/s]

 57%|█████▋    | 57624/100629 [45:17<41:25, 17.30it/s]

 57%|█████▋    | 57627/100629 [45:17<36:14, 19.78it/s]

 57%|█████▋    | 57630/100629 [45:17<51:06, 14.02it/s]

 57%|█████▋    | 57632/100629 [45:17<52:13, 13.72it/s]

 57%|█████▋    | 57634/100629 [45:17<52:02, 13.77it/s]

 57%|█████▋    | 57637/100629 [45:18<43:42, 16.39it/s]

 57%|█████▋    | 57640/100629 [45:18<39:28, 18.15it/s]

 57%|█████▋    | 57642/100629 [45:18<40:04, 17.88it/s]

 57%|█████▋    | 57645/100629 [45:18<35:26, 20.21it/s]

 57%|█████▋    | 57648/100629 [45:18<38:19, 18.69it/s]

 57%|█████▋    | 57653/100629 [45:18<30:02, 23.85it/s]

 57%|█████▋    | 57656/100629 [45:19<39:29, 18.13it/s]

 57%|█████▋    | 57659/100629 [45:19<37:17, 19.21it/s]

 57%|█████▋    | 57662/100629 [45:19<40:37, 17.63it/s]

 57%|█████▋    | 57664/100629 [45:19<41:49, 17.12it/s]

 57%|█████▋    | 57666/100629 [45:19<46:30, 15.40it/s]

 57%|█████▋    | 57669/100629 [45:19<47:55, 14.94it/s]

 57%|█████▋    | 57673/100629 [45:19<37:37, 19.03it/s]

 57%|█████▋    | 57676/100629 [45:20<39:29, 18.13it/s]

 57%|█████▋    | 57678/100629 [45:20<39:36, 18.07it/s]

 57%|█████▋    | 57680/100629 [45:20<46:56, 15.25it/s]

 57%|█████▋    | 57683/100629 [45:20<42:48, 16.72it/s]

 57%|█████▋    | 57686/100629 [45:20<41:02, 17.44it/s]

 57%|█████▋    | 57689/100629 [45:20<36:26, 19.64it/s]

 57%|█████▋    | 57693/100629 [45:21<33:22, 21.44it/s]

 57%|█████▋    | 57696/100629 [45:21<43:56, 16.28it/s]

 57%|█████▋    | 57700/100629 [45:21<36:13, 19.75it/s]

 57%|█████▋    | 57703/100629 [45:21<35:52, 19.94it/s]

 57%|█████▋    | 57706/100629 [45:21<39:36, 18.06it/s]

 57%|█████▋    | 57709/100629 [45:21<36:24, 19.65it/s]

 57%|█████▋    | 57713/100629 [45:22<30:44, 23.26it/s]

 57%|█████▋    | 57718/100629 [45:22<24:43, 28.93it/s]

 57%|█████▋    | 57722/100629 [45:22<26:37, 26.86it/s]

 57%|█████▋    | 57725/100629 [45:22<27:08, 26.34it/s]

 57%|█████▋    | 57728/100629 [45:22<28:44, 24.87it/s]

 57%|█████▋    | 57731/100629 [45:22<28:43, 24.89it/s]

 57%|█████▋    | 57734/100629 [45:22<28:43, 24.88it/s]

 57%|█████▋    | 57737/100629 [45:22<30:45, 23.25it/s]

 57%|█████▋    | 57741/100629 [45:23<26:39, 26.82it/s]

 57%|█████▋    | 57744/100629 [45:23<28:14, 25.31it/s]

 57%|█████▋    | 57747/100629 [45:23<35:44, 19.99it/s]

 57%|█████▋    | 57750/100629 [45:23<34:15, 20.86it/s]

 57%|█████▋    | 57753/100629 [45:23<38:26, 18.59it/s]

 57%|█████▋    | 57756/100629 [45:23<39:21, 18.16it/s]

 57%|█████▋    | 57760/100629 [45:24<33:10, 21.53it/s]

 57%|█████▋    | 57763/100629 [45:24<37:41, 18.96it/s]

 57%|█████▋    | 57766/100629 [45:24<34:19, 20.81it/s]

 57%|█████▋    | 57769/100629 [45:24<39:10, 18.24it/s]

 57%|█████▋    | 57772/100629 [45:24<36:03, 19.81it/s]

 57%|█████▋    | 57775/100629 [45:24<33:42, 21.19it/s]

 57%|█████▋    | 57778/100629 [45:25<37:38, 18.97it/s]

 57%|█████▋    | 57782/100629 [45:25<36:56, 19.33it/s]

 57%|█████▋    | 57785/100629 [45:25<33:30, 21.31it/s]

 57%|█████▋    | 57788/100629 [45:25<34:10, 20.89it/s]

 57%|█████▋    | 57791/100629 [45:25<39:45, 17.96it/s]

 57%|█████▋    | 57793/100629 [45:25<42:03, 16.98it/s]

 57%|█████▋    | 57796/100629 [45:26<39:03, 18.28it/s]

 57%|█████▋    | 57800/100629 [45:26<31:32, 22.63it/s]

 57%|█████▋    | 57803/100629 [45:26<32:39, 21.86it/s]

 57%|█████▋    | 57806/100629 [45:26<34:21, 20.78it/s]

 57%|█████▋    | 57809/100629 [45:26<35:33, 20.07it/s]

 57%|█████▋    | 57812/100629 [45:26<38:22, 18.59it/s]

 57%|█████▋    | 57814/100629 [45:26<38:10, 18.69it/s]

 57%|█████▋    | 57816/100629 [45:27<40:57, 17.42it/s]

 57%|█████▋    | 57818/100629 [45:27<40:42, 17.53it/s]

 57%|█████▋    | 57821/100629 [45:27<36:45, 19.41it/s]

 57%|█████▋    | 57824/100629 [45:27<38:38, 18.46it/s]

 57%|█████▋    | 57826/100629 [45:27<43:11, 16.52it/s]

 57%|█████▋    | 57829/100629 [45:27<39:03, 18.26it/s]

 57%|█████▋    | 57833/100629 [45:27<30:50, 23.13it/s]

 57%|█████▋    | 57836/100629 [45:27<31:48, 22.43it/s]

 57%|█████▋    | 57839/100629 [45:28<33:06, 21.54it/s]

 57%|█████▋    | 57843/100629 [45:28<28:04, 25.40it/s]

 57%|█████▋    | 57846/100629 [45:28<28:22, 25.13it/s]

 57%|█████▋    | 57850/100629 [45:28<25:44, 27.70it/s]

 57%|█████▋    | 57853/100629 [45:28<27:17, 26.13it/s]

 57%|█████▋    | 57856/100629 [45:28<27:34, 25.85it/s]

 57%|█████▋    | 57859/100629 [45:28<28:25, 25.08it/s]

 58%|█████▊    | 57862/100629 [45:28<29:51, 23.88it/s]

 58%|█████▊    | 57865/100629 [45:29<33:15, 21.43it/s]

 58%|█████▊    | 57868/100629 [45:29<33:23, 21.35it/s]

 58%|█████▊    | 57871/100629 [45:29<34:44, 20.51it/s]

 58%|█████▊    | 57875/100629 [45:29<28:40, 24.85it/s]

 58%|█████▊    | 57878/100629 [45:29<31:38, 22.51it/s]

 58%|█████▊    | 57882/100629 [45:29<29:52, 23.84it/s]

 58%|█████▊    | 57885/100629 [45:30<29:47, 23.92it/s]

 58%|█████▊    | 57888/100629 [45:30<32:21, 22.01it/s]

 58%|█████▊    | 57891/100629 [45:30<29:59, 23.75it/s]

 58%|█████▊    | 57894/100629 [45:30<34:54, 20.40it/s]

 58%|█████▊    | 57897/100629 [45:30<36:59, 19.25it/s]

 58%|█████▊    | 57900/100629 [45:30<37:08, 19.17it/s]

 58%|█████▊    | 57904/100629 [45:30<30:47, 23.12it/s]

 58%|█████▊    | 57909/100629 [45:31<26:37, 26.75it/s]

 58%|█████▊    | 57913/100629 [45:31<25:09, 28.30it/s]

 58%|█████▊    | 57916/100629 [45:31<26:11, 27.17it/s]

 58%|█████▊    | 57919/100629 [45:31<26:19, 27.04it/s]

 58%|█████▊    | 57922/100629 [45:31<30:35, 23.27it/s]

 58%|█████▊    | 57925/100629 [45:31<40:13, 17.69it/s]

 58%|█████▊    | 57929/100629 [45:31<33:00, 21.56it/s]

 58%|█████▊    | 57932/100629 [45:32<31:01, 22.94it/s]

 58%|█████▊    | 57935/100629 [45:32<39:53, 17.84it/s]

 58%|█████▊    | 57938/100629 [45:32<40:32, 17.55it/s]

 58%|█████▊    | 57941/100629 [45:32<38:55, 18.28it/s]

 58%|█████▊    | 57944/100629 [45:32<39:59, 17.79it/s]

 58%|█████▊    | 57946/100629 [45:32<39:03, 18.21it/s]

 58%|█████▊    | 57949/100629 [45:33<41:41, 17.06it/s]

 58%|█████▊    | 57952/100629 [45:33<37:27, 18.99it/s]

 58%|█████▊    | 57955/100629 [45:33<46:16, 15.37it/s]

 58%|█████▊    | 57957/100629 [45:33<46:20, 15.35it/s]

 58%|█████▊    | 57961/100629 [45:33<37:14, 19.10it/s]

 58%|█████▊    | 57964/100629 [45:34<39:14, 18.12it/s]

 58%|█████▊    | 57967/100629 [45:34<37:13, 19.10it/s]

 58%|█████▊    | 57970/100629 [45:34<40:10, 17.70it/s]

 58%|█████▊    | 57973/100629 [45:34<37:35, 18.91it/s]

 58%|█████▊    | 57977/100629 [45:34<33:25, 21.26it/s]

 58%|█████▊    | 57981/100629 [45:34<29:05, 24.44it/s]

 58%|█████▊    | 57984/100629 [45:34<29:10, 24.36it/s]

 58%|█████▊    | 57987/100629 [45:35<30:38, 23.19it/s]

 58%|█████▊    | 57990/100629 [45:35<33:26, 21.26it/s]

 58%|█████▊    | 57993/100629 [45:35<30:38, 23.20it/s]

 58%|█████▊    | 57996/100629 [45:35<34:19, 20.70it/s]

 58%|█████▊    | 58000/100629 [45:35<30:11, 23.53it/s]

 58%|█████▊    | 58004/100629 [45:35<27:40, 25.67it/s]

 58%|█████▊    | 58007/100629 [45:35<31:55, 22.26it/s]

 58%|█████▊    | 58010/100629 [45:36<43:29, 16.33it/s]

 58%|█████▊    | 58013/100629 [45:36<41:38, 17.05it/s]

 58%|█████▊    | 58017/100629 [45:36<38:52, 18.27it/s]

 58%|█████▊    | 58019/100629 [45:36<44:23, 16.00it/s]

 58%|█████▊    | 58022/100629 [45:36<39:04, 18.18it/s]

 58%|█████▊    | 58024/100629 [45:37<41:51, 16.97it/s]

 58%|█████▊    | 58027/100629 [45:37<38:29, 18.45it/s]

 58%|█████▊    | 58031/100629 [45:37<32:05, 22.12it/s]

 58%|█████▊    | 58034/100629 [45:37<29:45, 23.85it/s]

 58%|█████▊    | 58037/100629 [45:37<34:02, 20.85it/s]

 58%|█████▊    | 58041/100629 [45:37<31:58, 22.20it/s]

 58%|█████▊    | 58044/100629 [45:37<35:25, 20.04it/s]

 58%|█████▊    | 58047/100629 [45:38<41:20, 17.17it/s]

 58%|█████▊    | 58049/100629 [45:38<41:34, 17.07it/s]

 58%|█████▊    | 58052/100629 [45:38<40:12, 17.65it/s]

 58%|█████▊    | 58054/100629 [45:38<41:52, 16.95it/s]

 58%|█████▊    | 58057/100629 [45:38<42:20, 16.76it/s]

 58%|█████▊    | 58061/100629 [45:38<35:49, 19.80it/s]

 58%|█████▊    | 58064/100629 [45:39<34:34, 20.52it/s]

 58%|█████▊    | 58067/100629 [45:39<38:46, 18.29it/s]

 58%|█████▊    | 58069/100629 [45:39<41:27, 17.11it/s]

 58%|█████▊    | 58072/100629 [45:39<37:31, 18.90it/s]

 58%|█████▊    | 58075/100629 [45:39<39:24, 18.00it/s]

 58%|█████▊    | 58079/100629 [45:39<34:32, 20.53it/s]

 58%|█████▊    | 58083/100629 [45:39<31:54, 22.22it/s]

 58%|█████▊    | 58086/100629 [45:40<30:06, 23.55it/s]

 58%|█████▊    | 58089/100629 [45:40<30:41, 23.10it/s]

 58%|█████▊    | 58092/100629 [45:40<32:26, 21.85it/s]

 58%|█████▊    | 58095/100629 [45:40<33:27, 21.19it/s]

 58%|█████▊    | 58100/100629 [45:40<27:01, 26.22it/s]

 58%|█████▊    | 58103/100629 [45:40<29:35, 23.95it/s]

 58%|█████▊    | 58106/100629 [45:40<30:24, 23.31it/s]

 58%|█████▊    | 58109/100629 [45:41<31:31, 22.47it/s]

 58%|█████▊    | 58112/100629 [45:41<32:32, 21.78it/s]

 58%|█████▊    | 58116/100629 [45:41<27:30, 25.75it/s]

 58%|█████▊    | 58119/100629 [45:41<31:34, 22.44it/s]

 58%|█████▊    | 58122/100629 [45:41<48:50, 14.51it/s]

 58%|█████▊    | 58124/100629 [45:42<51:48, 13.67it/s]

 58%|█████▊    | 58126/100629 [45:42<52:26, 13.51it/s]

 58%|█████▊    | 58128/100629 [45:42<51:45, 13.69it/s]

 58%|█████▊    | 58130/100629 [45:42<50:22, 14.06it/s]

 58%|█████▊    | 58135/100629 [45:42<35:32, 19.93it/s]

 58%|█████▊    | 58138/100629 [45:42<36:19, 19.49it/s]

 58%|█████▊    | 58141/100629 [45:43<44:15, 16.00it/s]

 58%|█████▊    | 58144/100629 [45:43<38:21, 18.46it/s]

 58%|█████▊    | 58147/100629 [45:43<53:00, 13.36it/s]

 58%|█████▊    | 58150/100629 [45:43<46:53, 15.10it/s]

 58%|█████▊    | 58152/100629 [45:43<46:15, 15.30it/s]

 58%|█████▊    | 58155/100629 [45:43<44:30, 15.90it/s]

 58%|█████▊    | 58159/100629 [45:44<35:00, 20.22it/s]

 58%|█████▊    | 58162/100629 [45:44<38:12, 18.52it/s]

 58%|█████▊    | 58165/100629 [45:44<46:18, 15.28it/s]

 58%|█████▊    | 58168/100629 [45:44<44:07, 16.04it/s]

 58%|█████▊    | 58171/100629 [45:44<40:58, 17.27it/s]

 58%|█████▊    | 58175/100629 [45:45<34:22, 20.58it/s]

 58%|█████▊    | 58178/100629 [45:45<31:31, 22.44it/s]

 58%|█████▊    | 58181/100629 [45:45<36:30, 19.38it/s]

 58%|█████▊    | 58184/100629 [45:45<36:06, 19.59it/s]

 58%|█████▊    | 58188/100629 [45:45<32:17, 21.91it/s]

 58%|█████▊    | 58191/100629 [45:45<31:08, 22.72it/s]

 58%|█████▊    | 58194/100629 [45:45<32:19, 21.88it/s]

 58%|█████▊    | 58197/100629 [45:46<36:38, 19.30it/s]

 58%|█████▊    | 58200/100629 [45:46<36:55, 19.15it/s]

 58%|█████▊    | 58202/100629 [45:46<36:35, 19.33it/s]

 58%|█████▊    | 58205/100629 [45:46<34:32, 20.47it/s]

 58%|█████▊    | 58208/100629 [45:46<32:43, 21.61it/s]

 58%|█████▊    | 58211/100629 [45:46<30:22, 23.27it/s]

 58%|█████▊    | 58214/100629 [45:46<32:48, 21.55it/s]

 58%|█████▊    | 58217/100629 [45:47<34:54, 20.25it/s]

 58%|█████▊    | 58221/100629 [45:47<30:08, 23.45it/s]

 58%|█████▊    | 58225/100629 [45:47<26:31, 26.64it/s]

 58%|█████▊    | 58229/100629 [45:47<27:52, 25.35it/s]

 58%|█████▊    | 58232/100629 [45:47<27:21, 25.83it/s]

 58%|█████▊    | 58235/100629 [45:47<31:24, 22.49it/s]

 58%|█████▊    | 58238/100629 [45:47<30:10, 23.42it/s]

 58%|█████▊    | 58241/100629 [45:47<30:05, 23.48it/s]

 58%|█████▊    | 58244/100629 [45:48<29:52, 23.64it/s]

 58%|█████▊    | 58247/100629 [45:48<34:26, 20.51it/s]

 58%|█████▊    | 58250/100629 [45:48<34:38, 20.39it/s]

 58%|█████▊    | 58253/100629 [45:48<31:28, 22.44it/s]

 58%|█████▊    | 58256/100629 [45:48<32:05, 22.00it/s]

 58%|█████▊    | 58259/100629 [45:48<33:52, 20.85it/s]

 58%|█████▊    | 58263/100629 [45:48<29:54, 23.61it/s]

 58%|█████▊    | 58266/100629 [45:49<31:13, 22.62it/s]

 58%|█████▊    | 58269/100629 [45:49<31:15, 22.59it/s]

 58%|█████▊    | 58272/100629 [45:49<33:44, 20.93it/s]

 58%|█████▊    | 58275/100629 [45:49<34:57, 20.19it/s]

 58%|█████▊    | 58278/100629 [45:49<32:16, 21.87it/s]

 58%|█████▊    | 58282/100629 [45:50<40:29, 17.43it/s]

 58%|█████▊    | 58285/100629 [45:50<37:46, 18.68it/s]

 58%|█████▊    | 58289/100629 [45:50<31:56, 22.10it/s]

 58%|█████▊    | 58292/100629 [45:50<31:02, 22.74it/s]

 58%|█████▊    | 58295/100629 [45:50<31:52, 22.14it/s]

 58%|█████▊    | 58298/100629 [45:50<32:21, 21.80it/s]

 58%|█████▊    | 58303/100629 [45:50<26:05, 27.04it/s]

 58%|█████▊    | 58306/100629 [45:50<28:16, 24.95it/s]

 58%|█████▊    | 58310/100629 [45:51<28:36, 24.66it/s]

 58%|█████▊    | 58313/100629 [45:51<31:32, 22.36it/s]

 58%|█████▊    | 58316/100629 [45:51<31:32, 22.35it/s]

 58%|█████▊    | 58319/100629 [45:51<36:17, 19.43it/s]

 58%|█████▊    | 58322/100629 [45:51<43:08, 16.34it/s]

 58%|█████▊    | 58325/100629 [45:51<39:58, 17.64it/s]

 58%|█████▊    | 58328/100629 [45:52<39:18, 17.94it/s]

 58%|█████▊    | 58331/100629 [45:52<36:16, 19.43it/s]

 58%|█████▊    | 58334/100629 [45:52<45:48, 15.39it/s]

 58%|█████▊    | 58336/100629 [45:52<46:26, 15.18it/s]

 58%|█████▊    | 58338/100629 [45:52<45:03, 15.65it/s]

 58%|█████▊    | 58342/100629 [45:52<38:48, 18.16it/s]

 58%|█████▊    | 58346/100629 [45:53<32:02, 21.99it/s]

 58%|█████▊    | 58349/100629 [45:53<32:47, 21.48it/s]

 58%|█████▊    | 58352/100629 [45:53<37:09, 18.97it/s]

 58%|█████▊    | 58355/100629 [45:53<35:07, 20.06it/s]

 58%|█████▊    | 58359/100629 [45:53<30:28, 23.12it/s]

 58%|█████▊    | 58362/100629 [45:53<31:28, 22.39it/s]

 58%|█████▊    | 58365/100629 [45:53<30:08, 23.37it/s]

 58%|█████▊    | 58368/100629 [45:54<43:48, 16.08it/s]

 58%|█████▊    | 58370/100629 [45:54<42:16, 16.66it/s]

 58%|█████▊    | 58376/100629 [45:54<29:03, 24.23it/s]

 58%|█████▊    | 58379/100629 [45:54<29:34, 23.81it/s]

 58%|█████▊    | 58382/100629 [45:54<30:31, 23.07it/s]

 58%|█████▊    | 58385/100629 [45:54<32:40, 21.55it/s]

 58%|█████▊    | 58388/100629 [45:55<33:05, 21.27it/s]

 58%|█████▊    | 58391/100629 [45:55<31:47, 22.14it/s]

 58%|█████▊    | 58394/100629 [45:55<30:49, 22.84it/s]

 58%|█████▊    | 58397/100629 [45:55<29:51, 23.57it/s]

 58%|█████▊    | 58400/100629 [45:55<32:37, 21.57it/s]

 58%|█████▊    | 58403/100629 [45:55<31:24, 22.40it/s]

 58%|█████▊    | 58406/100629 [45:55<34:08, 20.61it/s]

 58%|█████▊    | 58409/100629 [45:56<35:50, 19.63it/s]

 58%|█████▊    | 58412/100629 [45:56<36:26, 19.30it/s]

 58%|█████▊    | 58416/100629 [45:56<30:47, 22.84it/s]

 58%|█████▊    | 58422/100629 [45:56<23:38, 29.75it/s]

 58%|█████▊    | 58426/100629 [45:56<21:56, 32.05it/s]

 58%|█████▊    | 58430/100629 [45:56<29:08, 24.13it/s]

 58%|█████▊    | 58433/100629 [45:56<28:54, 24.33it/s]

 58%|█████▊    | 58436/100629 [45:57<28:33, 24.62it/s]

 58%|█████▊    | 58439/100629 [45:57<31:03, 22.64it/s]

 58%|█████▊    | 58442/100629 [45:57<29:29, 23.85it/s]

 58%|█████▊    | 58445/100629 [45:57<27:53, 25.21it/s]

 58%|█████▊    | 58449/100629 [45:57<24:23, 28.83it/s]

 58%|█████▊    | 58454/100629 [45:57<23:11, 30.31it/s]

 58%|█████▊    | 58458/100629 [45:57<25:34, 27.48it/s]

 58%|█████▊    | 58461/100629 [45:58<25:58, 27.06it/s]

 58%|█████▊    | 58464/100629 [45:58<29:01, 24.22it/s]

 58%|█████▊    | 58469/100629 [45:58<25:00, 28.09it/s]

 58%|█████▊    | 58472/100629 [45:58<25:49, 27.21it/s]

 58%|█████▊    | 58475/100629 [45:58<29:18, 23.98it/s]

 58%|█████▊    | 58478/100629 [45:58<30:35, 22.97it/s]

 58%|█████▊    | 58481/100629 [45:59<38:09, 18.41it/s]

 58%|█████▊    | 58484/100629 [45:59<37:34, 18.69it/s]

 58%|█████▊    | 58487/100629 [45:59<34:37, 20.28it/s]

 58%|█████▊    | 58490/100629 [45:59<39:37, 17.73it/s]

 58%|█████▊    | 58492/100629 [45:59<43:23, 16.18it/s]

 58%|█████▊    | 58495/100629 [45:59<39:18, 17.86it/s]

 58%|█████▊    | 58497/100629 [45:59<41:43, 16.83it/s]

 58%|█████▊    | 58499/100629 [46:00<45:02, 15.59it/s]

 58%|█████▊    | 58501/100629 [46:00<46:26, 15.12it/s]

 58%|█████▊    | 58503/100629 [46:00<47:37, 14.74it/s]

 58%|█████▊    | 58506/100629 [46:00<43:50, 16.01it/s]

 58%|█████▊    | 58509/100629 [46:00<42:22, 16.57it/s]

 58%|█████▊    | 58512/100629 [46:00<36:43, 19.11it/s]

 58%|█████▊    | 58515/100629 [46:00<35:32, 19.75it/s]

 58%|█████▊    | 58518/100629 [46:01<35:33, 19.73it/s]

 58%|█████▊    | 58521/100629 [46:01<31:58, 21.95it/s]

 58%|█████▊    | 58524/100629 [46:01<38:10, 18.39it/s]

 58%|█████▊    | 58527/100629 [46:01<38:45, 18.11it/s]

 58%|█████▊    | 58530/100629 [46:01<37:34, 18.67it/s]

 58%|█████▊    | 58533/100629 [46:01<39:47, 17.64it/s]

 58%|█████▊    | 58536/100629 [46:02<35:07, 19.97it/s]

 58%|█████▊    | 58539/100629 [46:02<43:48, 16.01it/s]

 58%|█████▊    | 58541/100629 [46:02<45:07, 15.54it/s]

 58%|█████▊    | 58544/100629 [46:02<41:10, 17.04it/s]

 58%|█████▊    | 58548/100629 [46:02<35:56, 19.51it/s]

 58%|█████▊    | 58551/100629 [46:03<42:28, 16.51it/s]

 58%|█████▊    | 58554/100629 [46:03<37:21, 18.77it/s]

 58%|█████▊    | 58557/100629 [46:03<35:28, 19.77it/s]

 58%|█████▊    | 58560/100629 [46:03<39:38, 17.68it/s]

 58%|█████▊    | 58563/100629 [46:03<39:06, 17.92it/s]

 58%|█████▊    | 58567/100629 [46:03<33:34, 20.88it/s]

 58%|█████▊    | 58570/100629 [46:03<30:56, 22.66it/s]

 58%|█████▊    | 58573/100629 [46:03<29:44, 23.56it/s]

 58%|█████▊    | 58576/100629 [46:04<29:04, 24.11it/s]

 58%|█████▊    | 58579/100629 [46:04<32:57, 21.27it/s]

 58%|█████▊    | 58582/100629 [46:04<31:34, 22.20it/s]

 58%|█████▊    | 58585/100629 [46:04<32:25, 21.61it/s]

 58%|█████▊    | 58588/100629 [46:04<37:04, 18.90it/s]

 58%|█████▊    | 58591/100629 [46:04<37:45, 18.56it/s]

 58%|█████▊    | 58593/100629 [46:05<37:33, 18.65it/s]

 58%|█████▊    | 58596/100629 [46:05<33:22, 20.99it/s]

 58%|█████▊    | 58599/100629 [46:05<34:27, 20.33it/s]

 58%|█████▊    | 58602/100629 [46:05<40:15, 17.40it/s]

 58%|█████▊    | 58604/100629 [46:05<44:30, 15.74it/s]

 58%|█████▊    | 58607/100629 [46:05<39:30, 17.73it/s]

 58%|█████▊    | 58610/100629 [46:05<36:57, 18.95it/s]

 58%|█████▊    | 58613/100629 [46:06<33:12, 21.09it/s]

 58%|█████▊    | 58617/100629 [46:06<30:37, 22.87it/s]

 58%|█████▊    | 58620/100629 [46:06<29:32, 23.70it/s]

 58%|█████▊    | 58623/100629 [46:06<29:54, 23.41it/s]

 58%|█████▊    | 58626/100629 [46:06<30:09, 23.22it/s]

 58%|█████▊    | 58630/100629 [46:06<25:57, 26.96it/s]

 58%|█████▊    | 58634/100629 [46:06<25:51, 27.07it/s]

 58%|█████▊    | 58637/100629 [46:06<26:47, 26.12it/s]

 58%|█████▊    | 58640/100629 [46:07<31:44, 22.05it/s]

 58%|█████▊    | 58643/100629 [46:07<33:34, 20.84it/s]

 58%|█████▊    | 58646/100629 [46:07<34:36, 20.22it/s]

 58%|█████▊    | 58649/100629 [46:07<36:53, 18.96it/s]

 58%|█████▊    | 58652/100629 [46:07<35:28, 19.72it/s]

 58%|█████▊    | 58655/100629 [46:07<32:52, 21.27it/s]

 58%|█████▊    | 58658/100629 [46:08<33:32, 20.86it/s]

 58%|█████▊    | 58662/100629 [46:08<29:42, 23.54it/s]

 58%|█████▊    | 58665/100629 [46:08<30:33, 22.89it/s]

 58%|█████▊    | 58668/100629 [46:08<32:22, 21.61it/s]

 58%|█████▊    | 58671/100629 [46:08<30:44, 22.75it/s]

 58%|█████▊    | 58675/100629 [46:08<27:14, 25.67it/s]

 58%|█████▊    | 58678/100629 [46:08<29:58, 23.33it/s]

 58%|█████▊    | 58684/100629 [46:08<22:33, 30.98it/s]

 58%|█████▊    | 58688/100629 [46:09<24:51, 28.12it/s]

 58%|█████▊    | 58691/100629 [46:09<28:03, 24.92it/s]

 58%|█████▊    | 58696/100629 [46:09<24:20, 28.71it/s]

 58%|█████▊    | 58700/100629 [46:09<29:01, 24.08it/s]

 58%|█████▊    | 58703/100629 [46:09<30:16, 23.08it/s]

 58%|█████▊    | 58706/100629 [46:09<30:12, 23.13it/s]

 58%|█████▊    | 58709/100629 [46:10<31:06, 22.46it/s]

 58%|█████▊    | 58713/100629 [46:10<27:46, 25.15it/s]

 58%|█████▊    | 58716/100629 [46:10<30:00, 23.28it/s]

 58%|█████▊    | 58719/100629 [46:10<28:59, 24.10it/s]

 58%|█████▊    | 58722/100629 [46:10<31:41, 22.04it/s]

 58%|█████▊    | 58725/100629 [46:10<34:46, 20.09it/s]

 58%|█████▊    | 58728/100629 [46:10<32:53, 21.23it/s]

 58%|█████▊    | 58731/100629 [46:11<33:56, 20.57it/s]

 58%|█████▊    | 58734/100629 [46:11<36:55, 18.91it/s]

 58%|█████▊    | 58737/100629 [46:11<33:04, 21.11it/s]

 58%|█████▊    | 58740/100629 [46:11<32:39, 21.38it/s]

 58%|█████▊    | 58743/100629 [46:11<38:12, 18.27it/s]

 58%|█████▊    | 58745/100629 [46:11<38:49, 17.98it/s]

 58%|█████▊    | 58747/100629 [46:12<39:31, 17.66it/s]

 58%|█████▊    | 58749/100629 [46:12<43:50, 15.92it/s]

 58%|█████▊    | 58752/100629 [46:12<39:10, 17.81it/s]

 58%|█████▊    | 58756/100629 [46:12<30:32, 22.85it/s]

 58%|█████▊    | 58759/100629 [46:12<33:39, 20.73it/s]

 58%|█████▊    | 58762/100629 [46:12<36:22, 19.18it/s]

 58%|█████▊    | 58765/100629 [46:12<33:02, 21.12it/s]

 58%|█████▊    | 58768/100629 [46:13<32:04, 21.76it/s]

 58%|█████▊    | 58771/100629 [46:13<38:49, 17.97it/s]

 58%|█████▊    | 58774/100629 [46:13<37:29, 18.61it/s]

 58%|█████▊    | 58777/100629 [46:13<34:19, 20.32it/s]

 58%|█████▊    | 58780/100629 [46:13<37:12, 18.75it/s]

 58%|█████▊    | 58782/100629 [46:13<37:05, 18.80it/s]

 58%|█████▊    | 58785/100629 [46:13<36:05, 19.33it/s]

 58%|█████▊    | 58787/100629 [46:14<36:07, 19.30it/s]

 58%|█████▊    | 58790/100629 [46:14<35:22, 19.71it/s]

 58%|█████▊    | 58792/100629 [46:14<37:30, 18.59it/s]

 58%|█████▊    | 58794/100629 [46:14<37:26, 18.62it/s]

 58%|█████▊    | 58797/100629 [46:14<32:28, 21.47it/s]

 58%|█████▊    | 58800/100629 [46:14<31:39, 22.02it/s]

 58%|█████▊    | 58803/100629 [46:14<31:48, 21.91it/s]

 58%|█████▊    | 58806/100629 [46:14<29:44, 23.44it/s]

 58%|█████▊    | 58809/100629 [46:15<38:51, 17.94it/s]

 58%|█████▊    | 58812/100629 [46:15<40:36, 17.16it/s]

 58%|█████▊    | 58815/100629 [46:15<40:22, 17.26it/s]

 58%|█████▊    | 58818/100629 [46:15<38:11, 18.25it/s]

 58%|█████▊    | 58821/100629 [46:15<35:50, 19.44it/s]

 58%|█████▊    | 58825/100629 [46:15<32:14, 21.61it/s]

 58%|█████▊    | 58828/100629 [46:16<32:11, 21.64it/s]

 58%|█████▊    | 58831/100629 [46:16<31:53, 21.85it/s]

 58%|█████▊    | 58834/100629 [46:16<32:32, 21.41it/s]

 58%|█████▊    | 58837/100629 [46:16<31:44, 21.95it/s]

 58%|█████▊    | 58840/100629 [46:16<35:21, 19.70it/s]

 58%|█████▊    | 58844/100629 [46:16<31:33, 22.07it/s]

 58%|█████▊    | 58847/100629 [46:17<36:46, 18.94it/s]

 58%|█████▊    | 58849/100629 [46:17<37:26, 18.60it/s]

 58%|█████▊    | 58854/100629 [46:17<32:09, 21.65it/s]

 58%|█████▊    | 58857/100629 [46:17<35:27, 19.63it/s]

 58%|█████▊    | 58860/100629 [46:17<32:06, 21.68it/s]

 58%|█████▊    | 58863/100629 [46:17<36:16, 19.19it/s]

 58%|█████▊    | 58866/100629 [46:17<34:30, 20.17it/s]

 59%|█████▊    | 58869/100629 [46:18<33:23, 20.84it/s]

 59%|█████▊    | 58873/100629 [46:18<30:16, 22.98it/s]

 59%|█████▊    | 58876/100629 [46:18<31:20, 22.21it/s]

 59%|█████▊    | 58879/100629 [46:18<33:37, 20.70it/s]

 59%|█████▊    | 58882/100629 [46:18<32:51, 21.17it/s]

 59%|█████▊    | 58885/100629 [46:18<37:33, 18.52it/s]

 59%|█████▊    | 58888/100629 [46:19<36:15, 19.19it/s]

 59%|█████▊    | 58891/100629 [46:19<34:24, 20.22it/s]

 59%|█████▊    | 58894/100629 [46:19<35:05, 19.82it/s]

 59%|█████▊    | 58897/100629 [46:19<33:03, 21.04it/s]

 59%|█████▊    | 58900/100629 [46:19<33:23, 20.82it/s]

 59%|█████▊    | 58904/100629 [46:19<27:41, 25.12it/s]

 59%|█████▊    | 58907/100629 [46:19<26:57, 25.79it/s]

 59%|█████▊    | 58910/100629 [46:19<29:16, 23.75it/s]

 59%|█████▊    | 58913/100629 [46:20<28:22, 24.51it/s]

 59%|█████▊    | 58917/100629 [46:20<25:43, 27.03it/s]

 59%|█████▊    | 58920/100629 [46:20<25:55, 26.82it/s]

 59%|█████▊    | 58923/100629 [46:20<31:36, 21.99it/s]

 59%|█████▊    | 58927/100629 [46:20<27:57, 24.86it/s]

 59%|█████▊    | 58932/100629 [46:20<23:56, 29.02it/s]

 59%|█████▊    | 58936/100629 [46:20<23:09, 30.00it/s]

 59%|█████▊    | 58940/100629 [46:21<27:00, 25.72it/s]

 59%|█████▊    | 58943/100629 [46:21<26:09, 26.55it/s]

 59%|█████▊    | 58946/100629 [46:21<30:26, 22.82it/s]

 59%|█████▊    | 58949/100629 [46:21<28:59, 23.96it/s]

 59%|█████▊    | 58953/100629 [46:21<28:51, 24.08it/s]

 59%|█████▊    | 58956/100629 [46:21<28:57, 23.98it/s]

 59%|█████▊    | 58959/100629 [46:21<30:18, 22.91it/s]

 59%|█████▊    | 58962/100629 [46:22<35:21, 19.64it/s]

 59%|█████▊    | 58966/100629 [46:22<29:41, 23.38it/s]

 59%|█████▊    | 58969/100629 [46:22<31:26, 22.08it/s]

 59%|█████▊    | 58972/100629 [46:22<36:05, 19.24it/s]

 59%|█████▊    | 58976/100629 [46:22<30:43, 22.60it/s]

 59%|█████▊    | 58979/100629 [46:22<30:01, 23.12it/s]

 59%|█████▊    | 58982/100629 [46:22<30:16, 22.93it/s]

 59%|█████▊    | 58985/100629 [46:23<29:46, 23.31it/s]

 59%|█████▊    | 58988/100629 [46:23<33:43, 20.58it/s]

 59%|█████▊    | 58991/100629 [46:23<35:08, 19.75it/s]

 59%|█████▊    | 58994/100629 [46:23<32:44, 21.19it/s]

 59%|█████▊    | 58997/100629 [46:23<33:17, 20.84it/s]

 59%|█████▊    | 59000/100629 [46:23<30:52, 22.47it/s]

 59%|█████▊    | 59003/100629 [46:23<30:16, 22.91it/s]

 59%|█████▊    | 59006/100629 [46:24<28:13, 24.57it/s]

 59%|█████▊    | 59009/100629 [46:24<28:55, 23.98it/s]

 59%|█████▊    | 59012/100629 [46:24<34:44, 19.96it/s]

 59%|█████▊    | 59015/100629 [46:24<46:51, 14.80it/s]

 59%|█████▊    | 59020/100629 [46:24<35:22, 19.60it/s]

 59%|█████▊    | 59023/100629 [46:25<35:26, 19.56it/s]

 59%|█████▊    | 59026/100629 [46:25<36:59, 18.75it/s]

 59%|█████▊    | 59029/100629 [46:25<33:33, 20.66it/s]

 59%|█████▊    | 59032/100629 [46:25<40:21, 17.18it/s]

 59%|█████▊    | 59035/100629 [46:25<40:29, 17.12it/s]

 59%|█████▊    | 59037/100629 [46:25<40:43, 17.02it/s]

 59%|█████▊    | 59039/100629 [46:25<43:59, 15.76it/s]

 59%|█████▊    | 59041/100629 [46:26<42:14, 16.41it/s]

 59%|█████▊    | 59044/100629 [46:26<37:46, 18.35it/s]

 59%|█████▊    | 59047/100629 [46:26<33:51, 20.47it/s]

 59%|█████▊    | 59051/100629 [46:26<29:51, 23.21it/s]

 59%|█████▊    | 59054/100629 [46:26<34:49, 19.90it/s]

 59%|█████▊    | 59057/100629 [46:26<32:10, 21.53it/s]

 59%|█████▊    | 59060/100629 [46:26<30:54, 22.41it/s]

 59%|█████▊    | 59063/100629 [46:27<35:11, 19.69it/s]

 59%|█████▊    | 59066/100629 [46:27<32:49, 21.10it/s]

 59%|█████▊    | 59069/100629 [46:27<30:55, 22.40it/s]

 59%|█████▊    | 59072/100629 [46:27<30:54, 22.41it/s]

 59%|█████▊    | 59075/100629 [46:27<31:39, 21.88it/s]

 59%|█████▊    | 59080/100629 [46:27<28:08, 24.61it/s]

 59%|█████▊    | 59083/100629 [46:27<28:32, 24.26it/s]

 59%|█████▊    | 59086/100629 [46:28<30:24, 22.77it/s]

 59%|█████▊    | 59089/100629 [46:28<28:21, 24.41it/s]

 59%|█████▊    | 59092/100629 [46:28<33:34, 20.62it/s]

 59%|█████▊    | 59095/100629 [46:28<34:17, 20.19it/s]

 59%|█████▊    | 59098/100629 [46:28<35:39, 19.41it/s]

 59%|█████▊    | 59101/100629 [46:28<34:49, 19.87it/s]

 59%|█████▊    | 59104/100629 [46:29<35:56, 19.26it/s]

 59%|█████▊    | 59107/100629 [46:29<32:33, 21.26it/s]

 59%|█████▊    | 59110/100629 [46:29<32:35, 21.23it/s]

 59%|█████▊    | 59113/100629 [46:29<33:08, 20.87it/s]

 59%|█████▊    | 59117/100629 [46:29<28:42, 24.10it/s]

 59%|█████▉    | 59120/100629 [46:29<36:18, 19.05it/s]

 59%|█████▉    | 59123/100629 [46:29<32:50, 21.07it/s]

 59%|█████▉    | 59127/100629 [46:30<31:22, 22.04it/s]

 59%|█████▉    | 59130/100629 [46:30<31:28, 21.98it/s]

 59%|█████▉    | 59133/100629 [46:30<33:37, 20.57it/s]

 59%|█████▉    | 59136/100629 [46:30<32:40, 21.17it/s]

 59%|█████▉    | 59140/100629 [46:30<27:14, 25.38it/s]

 59%|█████▉    | 59143/100629 [46:30<28:56, 23.88it/s]

 59%|█████▉    | 59146/100629 [46:30<32:11, 21.48it/s]

 59%|█████▉    | 59149/100629 [46:31<31:55, 21.65it/s]

 59%|█████▉    | 59152/100629 [46:31<35:16, 19.60it/s]

 59%|█████▉    | 59155/100629 [46:31<35:35, 19.42it/s]

 59%|█████▉    | 59158/100629 [46:31<38:50, 17.79it/s]

 59%|█████▉    | 59160/100629 [46:31<38:33, 17.93it/s]

 59%|█████▉    | 59162/100629 [46:31<38:10, 18.10it/s]

 59%|█████▉    | 59166/100629 [46:31<30:40, 22.53it/s]

 59%|█████▉    | 59169/100629 [46:32<31:30, 21.93it/s]

 59%|█████▉    | 59174/100629 [46:32<26:07, 26.44it/s]

 59%|█████▉    | 59177/100629 [46:32<27:17, 25.31it/s]

 59%|█████▉    | 59180/100629 [46:32<29:47, 23.19it/s]

 59%|█████▉    | 59183/100629 [46:32<33:12, 20.81it/s]

 59%|█████▉    | 59187/100629 [46:32<29:52, 23.13it/s]

 59%|█████▉    | 59190/100629 [46:32<33:39, 20.52it/s]

 59%|█████▉    | 59194/100629 [46:33<29:09, 23.68it/s]

 59%|█████▉    | 59197/100629 [46:33<30:55, 22.33it/s]

 59%|█████▉    | 59202/100629 [46:33<27:29, 25.12it/s]

 59%|█████▉    | 59205/100629 [46:33<28:23, 24.32it/s]

 59%|█████▉    | 59209/100629 [46:33<27:59, 24.66it/s]

 59%|█████▉    | 59212/100629 [46:33<31:28, 21.93it/s]

 59%|█████▉    | 59215/100629 [46:34<29:21, 23.51it/s]

 59%|█████▉    | 59218/100629 [46:34<32:41, 21.11it/s]

 59%|█████▉    | 59222/100629 [46:34<28:58, 23.81it/s]

 59%|█████▉    | 59225/100629 [46:34<29:08, 23.68it/s]

 59%|█████▉    | 59228/100629 [46:34<34:19, 20.10it/s]

 59%|█████▉    | 59231/100629 [46:34<37:40, 18.31it/s]

 59%|█████▉    | 59233/100629 [46:34<38:54, 17.73it/s]

 59%|█████▉    | 59235/100629 [46:35<43:49, 15.74it/s]

 59%|█████▉    | 59238/100629 [46:35<37:47, 18.26it/s]

 59%|█████▉    | 59240/100629 [46:35<38:32, 17.90it/s]

 59%|█████▉    | 59244/100629 [46:35<29:52, 23.09it/s]

 59%|█████▉    | 59247/100629 [46:35<29:20, 23.51it/s]

 59%|█████▉    | 59250/100629 [46:35<29:20, 23.51it/s]

 59%|█████▉    | 59253/100629 [46:35<34:24, 20.04it/s]

 59%|█████▉    | 59256/100629 [46:36<36:02, 19.13it/s]

 59%|█████▉    | 59259/100629 [46:36<40:32, 17.00it/s]

 59%|█████▉    | 59262/100629 [46:36<35:30, 19.42it/s]

 59%|█████▉    | 59265/100629 [46:36<36:34, 18.85it/s]

 59%|█████▉    | 59269/100629 [46:36<31:01, 22.22it/s]

 59%|█████▉    | 59272/100629 [46:36<35:37, 19.35it/s]

 59%|█████▉    | 59275/100629 [46:37<35:02, 19.67it/s]

 59%|█████▉    | 59278/100629 [46:37<33:14, 20.73it/s]

 59%|█████▉    | 59281/100629 [46:37<34:27, 20.00it/s]

 59%|█████▉    | 59284/100629 [46:37<40:09, 17.16it/s]

 59%|█████▉    | 59286/100629 [46:37<41:22, 16.66it/s]

 59%|█████▉    | 59288/100629 [46:37<41:01, 16.79it/s]

 59%|█████▉    | 59290/100629 [46:37<39:39, 17.37it/s]

 59%|█████▉    | 59295/100629 [46:38<31:52, 21.62it/s]

 59%|█████▉    | 59298/100629 [46:38<31:59, 21.53it/s]

 59%|█████▉    | 59301/100629 [46:38<37:25, 18.41it/s]

 59%|█████▉    | 59304/100629 [46:38<34:46, 19.80it/s]

 59%|█████▉    | 59307/100629 [46:38<35:39, 19.32it/s]

 59%|█████▉    | 59311/100629 [46:38<33:46, 20.39it/s]

 59%|█████▉    | 59315/100629 [46:39<28:21, 24.27it/s]

 59%|█████▉    | 59318/100629 [46:39<28:40, 24.02it/s]

 59%|█████▉    | 59321/100629 [46:39<27:25, 25.10it/s]

 59%|█████▉    | 59324/100629 [46:39<29:47, 23.11it/s]

 59%|█████▉    | 59327/100629 [46:39<34:03, 20.21it/s]

 59%|█████▉    | 59330/100629 [46:39<38:48, 17.73it/s]

 59%|█████▉    | 59332/100629 [46:39<39:59, 17.21it/s]

 59%|█████▉    | 59335/100629 [46:40<37:56, 18.14it/s]

 59%|█████▉    | 59339/100629 [46:40<31:16, 22.01it/s]

 59%|█████▉    | 59342/100629 [46:40<32:25, 21.22it/s]

 59%|█████▉    | 59345/100629 [46:40<30:10, 22.81it/s]

 59%|█████▉    | 59348/100629 [46:40<31:56, 21.54it/s]

 59%|█████▉    | 59351/100629 [46:40<29:49, 23.07it/s]

 59%|█████▉    | 59354/100629 [46:40<33:32, 20.51it/s]

 59%|█████▉    | 59357/100629 [46:41<37:35, 18.29it/s]

 59%|█████▉    | 59359/100629 [46:41<38:28, 17.87it/s]

 59%|█████▉    | 59362/100629 [46:41<34:31, 19.92it/s]

 59%|█████▉    | 59365/100629 [46:41<31:35, 21.77it/s]

 59%|█████▉    | 59368/100629 [46:41<30:27, 22.58it/s]

 59%|█████▉    | 59371/100629 [46:41<33:41, 20.41it/s]

 59%|█████▉    | 59374/100629 [46:41<30:50, 22.29it/s]

 59%|█████▉    | 59378/100629 [46:42<27:54, 24.64it/s]

 59%|█████▉    | 59381/100629 [46:42<26:31, 25.92it/s]

 59%|█████▉    | 59384/100629 [46:42<29:30, 23.29it/s]

 59%|█████▉    | 59387/100629 [46:42<32:23, 21.22it/s]

 59%|█████▉    | 59390/100629 [46:42<31:46, 21.63it/s]

 59%|█████▉    | 59393/100629 [46:42<30:10, 22.78it/s]

 59%|█████▉    | 59396/100629 [46:42<30:54, 22.24it/s]

 59%|█████▉    | 59399/100629 [46:43<31:14, 21.99it/s]

 59%|█████▉    | 59402/100629 [46:43<31:23, 21.89it/s]

 59%|█████▉    | 59405/100629 [46:43<31:19, 21.93it/s]

 59%|█████▉    | 59408/100629 [46:43<34:17, 20.04it/s]

 59%|█████▉    | 59411/100629 [46:43<34:23, 19.97it/s]

 59%|█████▉    | 59414/100629 [46:43<33:55, 20.24it/s]

 59%|█████▉    | 59417/100629 [46:43<35:43, 19.22it/s]

 59%|█████▉    | 59419/100629 [46:44<41:04, 16.72it/s]

 59%|█████▉    | 59422/100629 [46:44<37:34, 18.28it/s]

 59%|█████▉    | 59426/100629 [46:44<32:16, 21.27it/s]

 59%|█████▉    | 59429/100629 [46:44<34:11, 20.09it/s]

 59%|█████▉    | 59432/100629 [46:44<34:14, 20.05it/s]

 59%|█████▉    | 59435/100629 [46:44<31:03, 22.11it/s]

 59%|█████▉    | 59438/100629 [46:44<30:36, 22.43it/s]

 59%|█████▉    | 59441/100629 [46:45<31:48, 21.59it/s]

 59%|█████▉    | 59444/100629 [46:45<35:09, 19.53it/s]

 59%|█████▉    | 59447/100629 [46:45<35:49, 19.15it/s]

 59%|█████▉    | 59450/100629 [46:45<35:19, 19.43it/s]

 59%|█████▉    | 59452/100629 [46:45<49:16, 13.93it/s]

 59%|█████▉    | 59454/100629 [46:45<46:13, 14.85it/s]

 59%|█████▉    | 59458/100629 [46:46<38:12, 17.96it/s]

 59%|█████▉    | 59461/100629 [46:46<37:23, 18.35it/s]

 59%|█████▉    | 59463/100629 [46:46<36:45, 18.67it/s]

 59%|█████▉    | 59467/100629 [46:46<36:03, 19.02it/s]

 59%|█████▉    | 59469/100629 [46:46<38:36, 17.77it/s]

 59%|█████▉    | 59473/100629 [46:46<32:51, 20.88it/s]

 59%|█████▉    | 59476/100629 [46:46<31:19, 21.89it/s]

 59%|█████▉    | 59480/100629 [46:47<27:49, 24.64it/s]

 59%|█████▉    | 59483/100629 [46:47<29:45, 23.04it/s]

 59%|█████▉    | 59486/100629 [46:47<39:03, 17.56it/s]

 59%|█████▉    | 59489/100629 [46:47<37:25, 18.32it/s]

 59%|█████▉    | 59492/100629 [46:47<36:17, 18.89it/s]

 59%|█████▉    | 59495/100629 [46:48<44:57, 15.25it/s]

 59%|█████▉    | 59498/100629 [46:48<38:47, 17.67it/s]

 59%|█████▉    | 59501/100629 [46:48<40:43, 16.83it/s]

 59%|█████▉    | 59505/100629 [46:48<33:09, 20.67it/s]

 59%|█████▉    | 59508/100629 [46:48<33:09, 20.66it/s]

 59%|█████▉    | 59511/100629 [46:48<36:07, 18.97it/s]

 59%|█████▉    | 59515/100629 [46:48<29:43, 23.05it/s]

 59%|█████▉    | 59518/100629 [46:49<30:02, 22.80it/s]

 59%|█████▉    | 59521/100629 [46:49<28:28, 24.07it/s]

 59%|█████▉    | 59524/100629 [46:49<30:52, 22.19it/s]

 59%|█████▉    | 59527/100629 [46:49<31:53, 21.48it/s]

 59%|█████▉    | 59530/100629 [46:49<32:23, 21.15it/s]

 59%|█████▉    | 59534/100629 [46:49<27:21, 25.04it/s]

 59%|█████▉    | 59537/100629 [46:49<27:27, 24.94it/s]

 59%|█████▉    | 59540/100629 [46:50<30:58, 22.11it/s]

 59%|█████▉    | 59544/100629 [46:50<28:15, 24.23it/s]

 59%|█████▉    | 59547/100629 [46:50<29:00, 23.61it/s]

 59%|█████▉    | 59550/100629 [46:50<27:46, 24.65it/s]

 59%|█████▉    | 59554/100629 [46:50<25:05, 27.28it/s]

 59%|█████▉    | 59559/100629 [46:50<20:58, 32.64it/s]

 59%|█████▉    | 59563/100629 [46:50<23:14, 29.44it/s]

 59%|█████▉    | 59567/100629 [46:51<25:59, 26.33it/s]

 59%|█████▉    | 59572/100629 [46:51<22:49, 29.99it/s]

 59%|█████▉    | 59576/100629 [46:51<26:29, 25.82it/s]

 59%|█████▉    | 59579/100629 [46:51<26:54, 25.42it/s]

 59%|█████▉    | 59582/100629 [46:51<31:21, 21.82it/s]

 59%|█████▉    | 59585/100629 [46:51<31:26, 21.75it/s]

 59%|█████▉    | 59588/100629 [46:51<29:10, 23.44it/s]

 59%|█████▉    | 59591/100629 [46:52<31:36, 21.64it/s]

 59%|█████▉    | 59594/100629 [46:52<32:44, 20.89it/s]

 59%|█████▉    | 59597/100629 [46:52<34:30, 19.82it/s]

 59%|█████▉    | 59600/100629 [46:52<38:45, 17.64it/s]

 59%|█████▉    | 59602/100629 [46:52<38:41, 17.68it/s]

 59%|█████▉    | 59605/100629 [46:52<36:12, 18.88it/s]

 59%|█████▉    | 59607/100629 [46:53<39:29, 17.31it/s]

 59%|█████▉    | 59612/100629 [46:53<29:00, 23.57it/s]

 59%|█████▉    | 59615/100629 [46:53<29:11, 23.42it/s]

 59%|█████▉    | 59619/100629 [46:53<26:20, 25.94it/s]

 59%|█████▉    | 59624/100629 [46:53<24:47, 27.57it/s]

 59%|█████▉    | 59627/100629 [46:53<26:22, 25.91it/s]

 59%|█████▉    | 59630/100629 [46:53<27:23, 24.94it/s]

 59%|█████▉    | 59633/100629 [46:53<28:26, 24.02it/s]

 59%|█████▉    | 59638/100629 [46:54<25:12, 27.10it/s]

 59%|█████▉    | 59641/100629 [46:54<26:46, 25.51it/s]

 59%|█████▉    | 59644/100629 [46:54<28:33, 23.92it/s]

 59%|█████▉    | 59647/100629 [46:54<32:18, 21.14it/s]

 59%|█████▉    | 59650/100629 [46:54<30:33, 22.35it/s]

 59%|█████▉    | 59653/100629 [46:54<31:47, 21.48it/s]

 59%|█████▉    | 59656/100629 [46:55<31:52, 21.43it/s]

 59%|█████▉    | 59660/100629 [46:55<28:59, 23.55it/s]

 59%|█████▉    | 59663/100629 [46:55<27:52, 24.49it/s]

 59%|█████▉    | 59666/100629 [46:55<28:36, 23.87it/s]

 59%|█████▉    | 59669/100629 [46:55<27:26, 24.88it/s]

 59%|█████▉    | 59672/100629 [46:55<31:27, 21.70it/s]

 59%|█████▉    | 59675/100629 [46:55<34:41, 19.68it/s]

 59%|█████▉    | 59678/100629 [46:56<38:01, 17.95it/s]

 59%|█████▉    | 59682/100629 [46:56<34:59, 19.51it/s]

 59%|█████▉    | 59685/100629 [46:56<33:23, 20.44it/s]

 59%|█████▉    | 59688/100629 [46:56<33:37, 20.29it/s]

 59%|█████▉    | 59691/100629 [46:56<34:18, 19.88it/s]

 59%|█████▉    | 59694/100629 [46:56<32:31, 20.98it/s]

 59%|█████▉    | 59699/100629 [46:56<27:44, 24.60it/s]

 59%|█████▉    | 59702/100629 [46:57<30:53, 22.08it/s]

 59%|█████▉    | 59705/100629 [46:57<28:50, 23.65it/s]

 59%|█████▉    | 59709/100629 [46:57<28:17, 24.11it/s]

 59%|█████▉    | 59712/100629 [46:57<31:03, 21.96it/s]

 59%|█████▉    | 59716/100629 [46:57<27:41, 24.63it/s]

 59%|█████▉    | 59720/100629 [46:57<24:20, 28.01it/s]

 59%|█████▉    | 59723/100629 [46:57<24:27, 27.88it/s]

 59%|█████▉    | 59727/100629 [46:58<22:52, 29.80it/s]

 59%|█████▉    | 59731/100629 [46:58<26:45, 25.47it/s]

 59%|█████▉    | 59734/100629 [46:58<27:19, 24.95it/s]

 59%|█████▉    | 59737/100629 [46:58<30:17, 22.50it/s]

 59%|█████▉    | 59740/100629 [46:58<34:11, 19.93it/s]

 59%|█████▉    | 59746/100629 [46:58<26:56, 25.29it/s]

 59%|█████▉    | 59749/100629 [46:58<26:27, 25.75it/s]

 59%|█████▉    | 59752/100629 [46:59<25:41, 26.51it/s]

 59%|█████▉    | 59755/100629 [46:59<26:54, 25.31it/s]

 59%|█████▉    | 59759/100629 [46:59<27:40, 24.61it/s]

 59%|█████▉    | 59763/100629 [46:59<24:51, 27.40it/s]

 59%|█████▉    | 59767/100629 [46:59<24:25, 27.88it/s]

 59%|█████▉    | 59770/100629 [46:59<25:00, 27.24it/s]

 59%|█████▉    | 59774/100629 [46:59<22:49, 29.83it/s]

 59%|█████▉    | 59778/100629 [47:00<26:36, 25.60it/s]

 59%|█████▉    | 59782/100629 [47:00<24:03, 28.29it/s]

 59%|█████▉    | 59786/100629 [47:00<33:12, 20.50it/s]

 59%|█████▉    | 59790/100629 [47:00<30:45, 22.13it/s]

 59%|█████▉    | 59793/100629 [47:00<35:43, 19.05it/s]

 59%|█████▉    | 59797/100629 [47:00<30:27, 22.34it/s]

 59%|█████▉    | 59800/100629 [47:01<31:09, 21.84it/s]

 59%|█████▉    | 59803/100629 [47:01<34:02, 19.99it/s]

 59%|█████▉    | 59806/100629 [47:01<33:09, 20.51it/s]

 59%|█████▉    | 59810/100629 [47:01<32:17, 21.07it/s]

 59%|█████▉    | 59813/100629 [47:01<31:10, 21.83it/s]

 59%|█████▉    | 59816/100629 [47:01<31:52, 21.34it/s]

 59%|█████▉    | 59819/100629 [47:02<30:58, 21.95it/s]

 59%|█████▉    | 59822/100629 [47:02<34:08, 19.92it/s]

 59%|█████▉    | 59825/100629 [47:02<37:13, 18.27it/s]

 59%|█████▉    | 59828/100629 [47:02<34:43, 19.59it/s]

 59%|█████▉    | 59831/100629 [47:02<34:34, 19.66it/s]

 59%|█████▉    | 59834/100629 [47:02<35:40, 19.06it/s]

 59%|█████▉    | 59837/100629 [47:03<38:36, 17.61it/s]

 59%|█████▉    | 59839/100629 [47:03<38:35, 17.61it/s]

 59%|█████▉    | 59841/100629 [47:03<49:22, 13.77it/s]

 59%|█████▉    | 59845/100629 [47:03<40:53, 16.62it/s]

 59%|█████▉    | 59847/100629 [47:03<39:44, 17.10it/s]

 59%|█████▉    | 59850/100629 [47:03<34:51, 19.50it/s]

 59%|█████▉    | 59853/100629 [47:03<33:11, 20.47it/s]

 59%|█████▉    | 59857/100629 [47:04<28:22, 23.94it/s]

 59%|█████▉    | 59860/100629 [47:04<31:18, 21.70it/s]

 59%|█████▉    | 59863/100629 [47:04<32:26, 20.95it/s]

 59%|█████▉    | 59866/100629 [47:04<32:07, 21.15it/s]

 59%|█████▉    | 59869/100629 [47:04<32:57, 20.61it/s]

 59%|█████▉    | 59872/100629 [47:04<32:32, 20.87it/s]

 60%|█████▉    | 59876/100629 [47:04<30:13, 22.47it/s]

 60%|█████▉    | 59879/100629 [47:05<34:45, 19.54it/s]

 60%|█████▉    | 59882/100629 [47:05<37:48, 17.96it/s]

 60%|█████▉    | 59886/100629 [47:05<31:29, 21.56it/s]

 60%|█████▉    | 59889/100629 [47:05<30:55, 21.96it/s]

 60%|█████▉    | 59892/100629 [47:05<33:39, 20.17it/s]

 60%|█████▉    | 59895/100629 [47:05<36:48, 18.44it/s]

 60%|█████▉    | 59897/100629 [47:06<37:38, 18.03it/s]

 60%|█████▉    | 59899/100629 [47:06<42:24, 16.01it/s]

 60%|█████▉    | 59902/100629 [47:06<37:37, 18.04it/s]

 60%|█████▉    | 59905/100629 [47:06<36:28, 18.61it/s]

 60%|█████▉    | 59909/100629 [47:06<35:11, 19.29it/s]

 60%|█████▉    | 59911/100629 [47:06<35:01, 19.38it/s]

 60%|█████▉    | 59913/100629 [47:06<37:58, 17.87it/s]

 60%|█████▉    | 59915/100629 [47:07<39:31, 17.17it/s]

 60%|█████▉    | 59920/100629 [47:07<29:04, 23.33it/s]

 60%|█████▉    | 59923/100629 [47:07<28:47, 23.57it/s]

 60%|█████▉    | 59926/100629 [47:07<29:08, 23.28it/s]

 60%|█████▉    | 59930/100629 [47:07<26:00, 26.07it/s]

 60%|█████▉    | 59934/100629 [47:07<24:34, 27.60it/s]

 60%|█████▉    | 59938/100629 [47:07<22:57, 29.55it/s]

 60%|█████▉    | 59941/100629 [47:08<28:23, 23.88it/s]

 60%|█████▉    | 59944/100629 [47:08<34:40, 19.55it/s]

 60%|█████▉    | 59947/100629 [47:08<31:42, 21.39it/s]

 60%|█████▉    | 59950/100629 [47:08<37:55, 17.88it/s]

 60%|█████▉    | 59953/100629 [47:08<37:44, 17.96it/s]

 60%|█████▉    | 59957/100629 [47:08<33:03, 20.51it/s]

 60%|█████▉    | 59960/100629 [47:09<32:58, 20.55it/s]

 60%|█████▉    | 59963/100629 [47:09<34:31, 19.63it/s]

 60%|█████▉    | 59966/100629 [47:09<36:14, 18.70it/s]

 60%|█████▉    | 59969/100629 [47:09<36:06, 18.77it/s]

 60%|█████▉    | 59973/100629 [47:09<29:49, 22.72it/s]

 60%|█████▉    | 59976/100629 [47:09<29:05, 23.30it/s]

 60%|█████▉    | 59979/100629 [47:09<28:13, 24.01it/s]

 60%|█████▉    | 59982/100629 [47:10<30:36, 22.13it/s]

 60%|█████▉    | 59986/100629 [47:10<27:22, 24.74it/s]

 60%|█████▉    | 59989/100629 [47:10<31:27, 21.53it/s]

 60%|█████▉    | 59992/100629 [47:10<30:57, 21.88it/s]

 60%|█████▉    | 59995/100629 [47:10<32:48, 20.64it/s]

 60%|█████▉    | 59998/100629 [47:10<35:16, 19.20it/s]

 60%|█████▉    | 60000/100629 [47:11<36:54, 18.35it/s]

 60%|█████▉    | 60002/100629 [47:11<36:57, 18.32it/s]

 60%|█████▉    | 60006/100629 [47:11<30:42, 22.05it/s]

 60%|█████▉    | 60009/100629 [47:11<31:28, 21.50it/s]

 60%|█████▉    | 60012/100629 [47:11<29:38, 22.84it/s]

 60%|█████▉    | 60015/100629 [47:11<32:16, 20.97it/s]

 60%|█████▉    | 60018/100629 [47:11<41:06, 16.46it/s]

 60%|█████▉    | 60022/100629 [47:12<34:24, 19.67it/s]

 60%|█████▉    | 60025/100629 [47:12<37:36, 17.99it/s]

 60%|█████▉    | 60028/100629 [47:12<35:43, 18.94it/s]

 60%|█████▉    | 60031/100629 [47:12<38:14, 17.69it/s]

 60%|█████▉    | 60034/100629 [47:12<34:59, 19.34it/s]

 60%|█████▉    | 60037/100629 [47:12<31:26, 21.52it/s]

 60%|█████▉    | 60040/100629 [47:12<29:56, 22.59it/s]

 60%|█████▉    | 60043/100629 [47:13<27:45, 24.37it/s]

 60%|█████▉    | 60047/100629 [47:13<24:50, 27.22it/s]

 60%|█████▉    | 60050/100629 [47:13<25:15, 26.77it/s]

 60%|█████▉    | 60053/100629 [47:13<26:12, 25.81it/s]

 60%|█████▉    | 60056/100629 [47:13<26:16, 25.73it/s]

 60%|█████▉    | 60059/100629 [47:13<31:12, 21.66it/s]

 60%|█████▉    | 60062/100629 [47:13<37:30, 18.03it/s]

 60%|█████▉    | 60065/100629 [47:14<38:43, 17.46it/s]

 60%|█████▉    | 60067/100629 [47:14<38:03, 17.76it/s]

 60%|█████▉    | 60070/100629 [47:14<34:35, 19.54it/s]

 60%|█████▉    | 60073/100629 [47:14<37:04, 18.23it/s]

 60%|█████▉    | 60075/100629 [47:14<37:01, 18.25it/s]

 60%|█████▉    | 60078/100629 [47:14<36:21, 18.59it/s]

 60%|█████▉    | 60082/100629 [47:14<32:08, 21.02it/s]

 60%|█████▉    | 60085/100629 [47:15<35:36, 18.97it/s]

 60%|█████▉    | 60087/100629 [47:15<38:08, 17.71it/s]

 60%|█████▉    | 60089/100629 [47:15<38:18, 17.64it/s]

 60%|█████▉    | 60091/100629 [47:15<37:35, 17.97it/s]

 60%|█████▉    | 60094/100629 [47:15<33:32, 20.15it/s]

 60%|█████▉    | 60098/100629 [47:15<28:42, 23.52it/s]

 60%|█████▉    | 60101/100629 [47:15<28:04, 24.06it/s]

 60%|█████▉    | 60106/100629 [47:16<25:27, 26.53it/s]

 60%|█████▉    | 60109/100629 [47:16<26:46, 25.22it/s]

 60%|█████▉    | 60112/100629 [47:16<26:05, 25.88it/s]

 60%|█████▉    | 60115/100629 [47:16<30:51, 21.88it/s]

 60%|█████▉    | 60118/100629 [47:16<34:05, 19.80it/s]

 60%|█████▉    | 60121/100629 [47:16<33:55, 19.90it/s]

 60%|█████▉    | 60124/100629 [47:16<31:51, 21.19it/s]

 60%|█████▉    | 60127/100629 [47:17<29:11, 23.13it/s]

 60%|█████▉    | 60131/100629 [47:17<26:53, 25.10it/s]

 60%|█████▉    | 60134/100629 [47:17<29:33, 22.84it/s]

 60%|█████▉    | 60137/100629 [47:17<27:54, 24.18it/s]

 60%|█████▉    | 60140/100629 [47:17<26:42, 25.26it/s]

 60%|█████▉    | 60143/100629 [47:17<28:26, 23.72it/s]

 60%|█████▉    | 60146/100629 [47:17<33:09, 20.35it/s]

 60%|█████▉    | 60149/100629 [47:18<37:02, 18.21it/s]

 60%|█████▉    | 60152/100629 [47:18<33:55, 19.88it/s]

 60%|█████▉    | 60155/100629 [47:18<34:59, 19.28it/s]

 60%|█████▉    | 60158/100629 [47:18<37:59, 17.76it/s]

 60%|█████▉    | 60160/100629 [47:18<41:34, 16.23it/s]

 60%|█████▉    | 60162/100629 [47:18<42:11, 15.98it/s]

 60%|█████▉    | 60166/100629 [47:19<33:52, 19.91it/s]

 60%|█████▉    | 60170/100629 [47:19<30:39, 22.00it/s]

 60%|█████▉    | 60173/100629 [47:19<33:11, 20.31it/s]

 60%|█████▉    | 60177/100629 [47:19<28:48, 23.40it/s]

 60%|█████▉    | 60181/100629 [47:19<26:28, 25.46it/s]

 60%|█████▉    | 60184/100629 [47:19<30:21, 22.21it/s]

 60%|█████▉    | 60187/100629 [47:19<29:09, 23.12it/s]

 60%|█████▉    | 60191/100629 [47:20<25:32, 26.39it/s]

 60%|█████▉    | 60195/100629 [47:20<27:34, 24.43it/s]

 60%|█████▉    | 60198/100629 [47:20<27:01, 24.94it/s]

 60%|█████▉    | 60201/100629 [47:20<35:07, 19.18it/s]

 60%|█████▉    | 60204/100629 [47:20<31:39, 21.28it/s]

 60%|█████▉    | 60207/100629 [47:20<32:52, 20.49it/s]

 60%|█████▉    | 60210/100629 [47:21<36:46, 18.32it/s]

 60%|█████▉    | 60213/100629 [47:21<37:20, 18.04it/s]

 60%|█████▉    | 60215/100629 [47:21<37:34, 17.93it/s]

 60%|█████▉    | 60217/100629 [47:21<39:14, 17.17it/s]

 60%|█████▉    | 60219/100629 [47:21<41:03, 16.40it/s]

 60%|█████▉    | 60223/100629 [47:21<34:23, 19.58it/s]

 60%|█████▉    | 60225/100629 [47:21<42:16, 15.93it/s]

 60%|█████▉    | 60227/100629 [47:22<45:12, 14.90it/s]

 60%|█████▉    | 60231/100629 [47:22<38:10, 17.64it/s]

 60%|█████▉    | 60234/100629 [47:22<34:55, 19.28it/s]

 60%|█████▉    | 60237/100629 [47:22<31:39, 21.26it/s]

 60%|█████▉    | 60240/100629 [47:22<31:22, 21.46it/s]

 60%|█████▉    | 60243/100629 [47:22<39:08, 17.19it/s]

 60%|█████▉    | 60246/100629 [47:23<34:50, 19.32it/s]

 60%|█████▉    | 60250/100629 [47:23<29:05, 23.13it/s]

 60%|█████▉    | 60253/100629 [47:23<30:04, 22.37it/s]

 60%|█████▉    | 60256/100629 [47:23<33:37, 20.02it/s]

 60%|█████▉    | 60260/100629 [47:23<30:03, 22.39it/s]

 60%|█████▉    | 60263/100629 [47:23<29:41, 22.66it/s]

 60%|█████▉    | 60267/100629 [47:23<27:28, 24.48it/s]

 60%|█████▉    | 60270/100629 [47:24<33:15, 20.23it/s]

 60%|█████▉    | 60274/100629 [47:24<27:53, 24.12it/s]

 60%|█████▉    | 60278/100629 [47:24<26:59, 24.92it/s]

 60%|█████▉    | 60282/100629 [47:24<27:55, 24.08it/s]

 60%|█████▉    | 60285/100629 [47:24<28:28, 23.62it/s]

 60%|█████▉    | 60289/100629 [47:24<24:53, 27.01it/s]

 60%|█████▉    | 60294/100629 [47:24<23:43, 28.33it/s]

 60%|█████▉    | 60298/100629 [47:25<22:02, 30.50it/s]

 60%|█████▉    | 60302/100629 [47:25<21:20, 31.48it/s]

 60%|█████▉    | 60306/100629 [47:25<26:14, 25.61it/s]

 60%|█████▉    | 60309/100629 [47:25<28:30, 23.57it/s]

 60%|█████▉    | 60312/100629 [47:25<31:48, 21.13it/s]

 60%|█████▉    | 60315/100629 [47:25<30:27, 22.06it/s]

 60%|█████▉    | 60318/100629 [47:25<31:26, 21.37it/s]

 60%|█████▉    | 60321/100629 [47:26<48:07, 13.96it/s]

 60%|█████▉    | 60323/100629 [47:26<49:29, 13.58it/s]

 60%|█████▉    | 60326/100629 [47:26<43:07, 15.57it/s]

 60%|█████▉    | 60329/100629 [47:26<38:16, 17.55it/s]

 60%|█████▉    | 60332/100629 [47:26<36:16, 18.51it/s]

 60%|█████▉    | 60335/100629 [47:27<37:56, 17.70it/s]

 60%|█████▉    | 60338/100629 [47:27<34:57, 19.21it/s]

 60%|█████▉    | 60341/100629 [47:27<32:05, 20.93it/s]

 60%|█████▉    | 60344/100629 [47:27<32:53, 20.41it/s]

 60%|█████▉    | 60347/100629 [47:27<35:03, 19.15it/s]

 60%|█████▉    | 60352/100629 [47:27<27:30, 24.40it/s]

 60%|█████▉    | 60355/100629 [47:28<31:02, 21.63it/s]

 60%|█████▉    | 60358/100629 [47:28<30:46, 21.81it/s]

 60%|█████▉    | 60361/100629 [47:28<42:01, 15.97it/s]

 60%|█████▉    | 60365/100629 [47:28<34:47, 19.29it/s]

 60%|█████▉    | 60368/100629 [47:28<39:46, 16.87it/s]

 60%|█████▉    | 60371/100629 [47:28<37:52, 17.72it/s]

 60%|█████▉    | 60373/100629 [47:29<37:01, 18.12it/s]

 60%|█████▉    | 60376/100629 [47:29<33:31, 20.01it/s]

 60%|██████    | 60380/100629 [47:29<29:33, 22.69it/s]

 60%|██████    | 60383/100629 [47:29<29:08, 23.02it/s]

 60%|██████    | 60386/100629 [47:29<37:14, 18.01it/s]

 60%|██████    | 60389/100629 [47:29<36:41, 18.27it/s]

 60%|██████    | 60392/100629 [47:29<32:50, 20.42it/s]

 60%|██████    | 60396/100629 [47:30<27:30, 24.38it/s]

 60%|██████    | 60399/100629 [47:30<38:49, 17.27it/s]

 60%|██████    | 60405/100629 [47:30<27:25, 24.45it/s]

 60%|██████    | 60409/100629 [47:30<35:40, 18.79it/s]

 60%|██████    | 60412/100629 [47:30<32:39, 20.52it/s]

 60%|██████    | 60415/100629 [47:31<34:25, 19.47it/s]

 60%|██████    | 60418/100629 [47:31<32:27, 20.64it/s]

 60%|██████    | 60421/100629 [47:31<30:00, 22.33it/s]

 60%|██████    | 60424/100629 [47:31<28:40, 23.37it/s]

 60%|██████    | 60427/100629 [47:31<31:27, 21.30it/s]

 60%|██████    | 60431/100629 [47:31<27:01, 24.79it/s]

 60%|██████    | 60435/100629 [47:31<25:15, 26.52it/s]

 60%|██████    | 60438/100629 [47:32<27:05, 24.72it/s]

 60%|██████    | 60441/100629 [47:32<31:19, 21.38it/s]

 60%|██████    | 60445/100629 [47:32<27:13, 24.59it/s]

 60%|██████    | 60448/100629 [47:32<28:27, 23.54it/s]

 60%|██████    | 60451/100629 [47:32<35:08, 19.05it/s]

 60%|██████    | 60454/100629 [47:32<32:15, 20.76it/s]

 60%|██████    | 60457/100629 [47:32<35:06, 19.07it/s]

 60%|██████    | 60460/100629 [47:33<33:54, 19.74it/s]

 60%|██████    | 60463/100629 [47:33<31:52, 21.00it/s]

 60%|██████    | 60468/100629 [47:33<26:33, 25.20it/s]

 60%|██████    | 60471/100629 [47:33<27:46, 24.10it/s]

 60%|██████    | 60475/100629 [47:33<27:13, 24.58it/s]

 60%|██████    | 60478/100629 [47:33<32:17, 20.73it/s]

 60%|██████    | 60483/100629 [47:34<27:06, 24.68it/s]

 60%|██████    | 60486/100629 [47:34<26:59, 24.78it/s]

 60%|██████    | 60489/100629 [47:34<27:06, 24.68it/s]

 60%|██████    | 60492/100629 [47:34<30:43, 21.77it/s]

 60%|██████    | 60495/100629 [47:34<33:26, 20.01it/s]

 60%|██████    | 60499/100629 [47:34<27:39, 24.18it/s]

 60%|██████    | 60502/100629 [47:34<26:46, 24.98it/s]

 60%|██████    | 60505/100629 [47:34<26:56, 24.82it/s]

 60%|██████    | 60508/100629 [47:35<30:54, 21.64it/s]

 60%|██████    | 60511/100629 [47:35<30:24, 21.99it/s]

 60%|██████    | 60514/100629 [47:35<32:56, 20.30it/s]

 60%|██████    | 60517/100629 [47:35<30:05, 22.21it/s]

 60%|██████    | 60520/100629 [47:35<30:35, 21.85it/s]

 60%|██████    | 60523/100629 [47:35<28:28, 23.47it/s]

 60%|██████    | 60526/100629 [47:35<28:02, 23.83it/s]

 60%|██████    | 60530/100629 [47:36<26:27, 25.26it/s]

 60%|██████    | 60533/100629 [47:36<35:56, 18.59it/s]

 60%|██████    | 60536/100629 [47:36<36:24, 18.35it/s]

 60%|██████    | 60539/100629 [47:36<38:41, 17.27it/s]

 60%|██████    | 60542/100629 [47:36<35:53, 18.61it/s]

 60%|██████    | 60545/100629 [47:36<32:43, 20.42it/s]

 60%|██████    | 60548/100629 [47:37<44:13, 15.10it/s]

 60%|██████    | 60551/100629 [47:37<40:24, 16.53it/s]

 60%|██████    | 60554/100629 [47:37<38:54, 17.17it/s]

 60%|██████    | 60556/100629 [47:37<37:47, 17.67it/s]

 60%|██████    | 60561/100629 [47:37<27:28, 24.30it/s]

 60%|██████    | 60565/100629 [47:37<27:44, 24.07it/s]

 60%|██████    | 60568/100629 [47:38<31:20, 21.30it/s]

 60%|██████    | 60571/100629 [47:38<32:36, 20.47it/s]

 60%|██████    | 60575/100629 [47:38<31:32, 21.16it/s]

 60%|██████    | 60578/100629 [47:38<29:05, 22.94it/s]

 60%|██████    | 60581/100629 [47:38<41:12, 16.20it/s]

 60%|██████    | 60583/100629 [47:39<39:53, 16.73it/s]

 60%|██████    | 60585/100629 [47:39<41:19, 16.15it/s]

 60%|██████    | 60587/100629 [47:39<41:04, 16.25it/s]

 60%|██████    | 60589/100629 [47:39<40:06, 16.64it/s]

 60%|██████    | 60592/100629 [47:39<35:29, 18.80it/s]

 60%|██████    | 60595/100629 [47:39<35:00, 19.06it/s]

 60%|██████    | 60599/100629 [47:39<30:38, 21.77it/s]

 60%|██████    | 60602/100629 [47:40<36:51, 18.10it/s]

 60%|██████    | 60605/100629 [47:40<37:49, 17.64it/s]

 60%|██████    | 60607/100629 [47:40<37:13, 17.92it/s]

 60%|██████    | 60609/100629 [47:40<36:31, 18.26it/s]

 60%|██████    | 60611/100629 [47:40<36:04, 18.49it/s]

 60%|██████    | 60613/100629 [47:40<38:13, 17.45it/s]

 60%|██████    | 60615/100629 [47:40<43:39, 15.27it/s]

 60%|██████    | 60618/100629 [47:40<38:29, 17.33it/s]

 60%|██████    | 60620/100629 [47:41<37:20, 17.86it/s]

 60%|██████    | 60624/100629 [47:41<34:20, 19.41it/s]

 60%|██████    | 60626/100629 [47:41<41:58, 15.89it/s]

 60%|██████    | 60629/100629 [47:41<37:47, 17.64it/s]

 60%|██████    | 60633/100629 [47:41<31:08, 21.41it/s]

 60%|██████    | 60636/100629 [47:41<31:38, 21.06it/s]

 60%|██████    | 60639/100629 [47:42<32:27, 20.54it/s]

 60%|██████    | 60642/100629 [47:42<31:31, 21.14it/s]

 60%|██████    | 60645/100629 [47:42<33:08, 20.11it/s]

 60%|██████    | 60648/100629 [47:42<35:06, 18.98it/s]

 60%|██████    | 60651/100629 [47:42<33:22, 19.96it/s]

 60%|██████    | 60654/100629 [47:42<31:54, 20.88it/s]

 60%|██████    | 60657/100629 [47:42<32:17, 20.63it/s]

 60%|██████    | 60661/100629 [47:43<29:25, 22.64it/s]

 60%|██████    | 60664/100629 [47:43<37:27, 17.78it/s]

 60%|██████    | 60667/100629 [47:43<38:23, 17.35it/s]

 60%|██████    | 60670/100629 [47:43<34:35, 19.25it/s]

 60%|██████    | 60673/100629 [47:43<33:18, 19.99it/s]

 60%|██████    | 60676/100629 [47:43<37:09, 17.92it/s]

 60%|██████    | 60679/100629 [47:44<35:07, 18.96it/s]

 60%|██████    | 60682/100629 [47:44<34:29, 19.30it/s]

 60%|██████    | 60685/100629 [47:44<34:13, 19.46it/s]

 60%|██████    | 60688/100629 [47:44<32:23, 20.56it/s]

 60%|██████    | 60692/100629 [47:44<34:44, 19.16it/s]

 60%|██████    | 60695/100629 [47:44<32:56, 20.20it/s]

 60%|██████    | 60698/100629 [47:45<31:39, 21.02it/s]

 60%|██████    | 60701/100629 [47:45<33:46, 19.71it/s]

 60%|██████    | 60704/100629 [47:45<30:27, 21.85it/s]

 60%|██████    | 60707/100629 [47:45<28:16, 23.53it/s]

 60%|██████    | 60710/100629 [47:45<31:30, 21.11it/s]

 60%|██████    | 60713/100629 [47:45<31:36, 21.04it/s]

 60%|██████    | 60716/100629 [47:45<31:27, 21.15it/s]

 60%|██████    | 60719/100629 [47:46<31:41, 20.99it/s]

 60%|██████    | 60722/100629 [47:46<32:14, 20.62it/s]

 60%|██████    | 60725/100629 [47:46<32:32, 20.44it/s]

 60%|██████    | 60728/100629 [47:46<30:02, 22.14it/s]

 60%|██████    | 60731/100629 [47:46<32:04, 20.73it/s]

 60%|██████    | 60734/100629 [47:46<33:07, 20.07it/s]

 60%|██████    | 60737/100629 [47:46<33:37, 19.78it/s]

 60%|██████    | 60740/100629 [47:47<35:06, 18.94it/s]

 60%|██████    | 60743/100629 [47:47<31:16, 21.25it/s]

 60%|██████    | 60746/100629 [47:47<30:28, 21.81it/s]

 60%|██████    | 60749/100629 [47:47<35:11, 18.89it/s]

 60%|██████    | 60752/100629 [47:47<36:38, 18.13it/s]

 60%|██████    | 60755/100629 [47:47<35:13, 18.87it/s]

 60%|██████    | 60757/100629 [47:47<36:56, 17.99it/s]

 60%|██████    | 60760/100629 [47:48<32:38, 20.36it/s]

 60%|██████    | 60763/100629 [47:48<34:18, 19.36it/s]

 60%|██████    | 60766/100629 [47:48<33:34, 19.79it/s]

 60%|██████    | 60769/100629 [47:48<37:51, 17.55it/s]

 60%|██████    | 60772/100629 [47:48<33:18, 19.94it/s]

 60%|██████    | 60775/100629 [47:48<34:38, 19.17it/s]

 60%|██████    | 60778/100629 [47:48<32:07, 20.68it/s]

 60%|██████    | 60784/100629 [47:49<26:22, 25.18it/s]

 60%|██████    | 60787/100629 [47:49<26:32, 25.02it/s]

 60%|██████    | 60790/100629 [47:49<27:02, 24.55it/s]

 60%|██████    | 60793/100629 [47:49<32:38, 20.34it/s]

 60%|██████    | 60796/100629 [47:49<31:06, 21.34it/s]

 60%|██████    | 60800/100629 [47:49<26:14, 25.29it/s]

 60%|██████    | 60803/100629 [47:50<29:31, 22.48it/s]

 60%|██████    | 60806/100629 [47:50<28:51, 23.00it/s]

 60%|██████    | 60809/100629 [47:50<29:01, 22.86it/s]

 60%|██████    | 60812/100629 [47:50<29:16, 22.67it/s]

 60%|██████    | 60815/100629 [47:50<28:15, 23.48it/s]

 60%|██████    | 60818/100629 [47:50<31:22, 21.15it/s]

 60%|██████    | 60821/100629 [47:50<32:25, 20.46it/s]

 60%|██████    | 60824/100629 [47:51<31:21, 21.15it/s]

 60%|██████    | 60827/100629 [47:51<36:03, 18.40it/s]

 60%|██████    | 60829/100629 [47:51<35:32, 18.67it/s]

 60%|██████    | 60831/100629 [47:51<35:02, 18.93it/s]

 60%|██████    | 60833/100629 [47:51<43:45, 15.16it/s]

 60%|██████    | 60837/100629 [47:51<35:24, 18.73it/s]

 60%|██████    | 60840/100629 [47:51<33:06, 20.03it/s]

 60%|██████    | 60843/100629 [47:52<31:19, 21.17it/s]

 60%|██████    | 60847/100629 [47:52<27:01, 24.54it/s]

 60%|██████    | 60850/100629 [47:52<27:23, 24.20it/s]

 60%|██████    | 60853/100629 [47:52<26:29, 25.03it/s]

 60%|██████    | 60856/100629 [47:52<27:23, 24.20it/s]

 60%|██████    | 60859/100629 [47:52<26:29, 25.02it/s]

 60%|██████    | 60862/100629 [47:52<32:52, 20.17it/s]

 60%|██████    | 60865/100629 [47:52<31:42, 20.90it/s]

 60%|██████    | 60870/100629 [47:53<31:27, 21.06it/s]

 60%|██████    | 60873/100629 [47:53<29:17, 22.63it/s]

 60%|██████    | 60876/100629 [47:53<29:13, 22.67it/s]

 60%|██████    | 60880/100629 [47:53<28:58, 22.86it/s]

 61%|██████    | 60883/100629 [47:53<29:49, 22.21it/s]

 61%|██████    | 60888/100629 [47:53<24:37, 26.89it/s]

 61%|██████    | 60891/100629 [47:54<30:37, 21.63it/s]

 61%|██████    | 60894/100629 [47:54<34:45, 19.05it/s]

 61%|██████    | 60897/100629 [47:54<35:14, 18.79it/s]

 61%|██████    | 60900/100629 [47:54<32:48, 20.18it/s]

 61%|██████    | 60903/100629 [47:54<36:34, 18.11it/s]

 61%|██████    | 60907/100629 [47:54<31:46, 20.84it/s]

 61%|██████    | 60910/100629 [47:55<32:28, 20.38it/s]

 61%|██████    | 60913/100629 [47:55<33:27, 19.79it/s]

 61%|██████    | 60917/100629 [47:55<30:54, 21.42it/s]

 61%|██████    | 60920/100629 [47:55<32:21, 20.45it/s]

 61%|██████    | 60923/100629 [47:55<29:51, 22.17it/s]

 61%|██████    | 60926/100629 [47:55<37:13, 17.77it/s]

 61%|██████    | 60928/100629 [47:56<38:16, 17.29it/s]

 61%|██████    | 60930/100629 [47:56<39:00, 16.96it/s]

 61%|██████    | 60933/100629 [47:56<36:17, 18.23it/s]

 61%|██████    | 60937/100629 [47:56<36:19, 18.21it/s]

 61%|██████    | 60940/100629 [47:56<37:23, 17.69it/s]

 61%|██████    | 60943/100629 [47:56<33:26, 19.78it/s]

 61%|██████    | 60947/100629 [47:56<29:45, 22.22it/s]

 61%|██████    | 60950/100629 [47:57<38:28, 17.19it/s]

 61%|██████    | 60952/100629 [47:57<38:03, 17.38it/s]

 61%|██████    | 60955/100629 [47:57<35:07, 18.82it/s]

 61%|██████    | 60958/100629 [47:57<37:17, 17.73it/s]

 61%|██████    | 60961/100629 [47:57<34:51, 18.97it/s]

 61%|██████    | 60963/100629 [47:57<35:08, 18.82it/s]

 61%|██████    | 60965/100629 [47:58<39:16, 16.84it/s]

 61%|██████    | 60969/100629 [47:58<30:30, 21.66it/s]

 61%|██████    | 60972/100629 [47:58<1:11:06,  9.29it/s]

 61%|██████    | 60974/100629 [47:59<1:06:56,  9.87it/s]

 61%|██████    | 60976/100629 [47:59<1:00:36, 10.91it/s]

 61%|██████    | 60978/100629 [47:59<1:04:42, 10.21it/s]

 61%|██████    | 60980/100629 [47:59<57:41, 11.46it/s]

 61%|██████    | 60982/100629 [47:59<54:26, 12.14it/s]

 61%|██████    | 60986/100629 [47:59<38:06, 17.34it/s]

 61%|██████    | 60989/100629 [47:59<34:58, 18.89it/s]

 61%|██████    | 60992/100629 [48:00<40:03, 16.49it/s]

 61%|██████    | 60996/100629 [48:00<31:58, 20.66it/s]

 61%|██████    | 60999/100629 [48:00<30:05, 21.95it/s]

 61%|██████    | 61002/100629 [48:00<28:55, 22.83it/s]

 61%|██████    | 61005/100629 [48:00<30:46, 21.45it/s]

 61%|██████    | 61008/100629 [48:00<28:51, 22.89it/s]

 61%|██████    | 61012/100629 [48:00<24:30, 26.94it/s]

 61%|██████    | 61017/100629 [48:01<21:18, 30.99it/s]

 61%|██████    | 61021/100629 [48:01<20:34, 32.09it/s]

 61%|██████    | 61025/100629 [48:01<24:11, 27.29it/s]

 61%|██████    | 61028/100629 [48:01<24:49, 26.59it/s]

 61%|██████    | 61031/100629 [48:01<26:22, 25.02it/s]

 61%|██████    | 61034/100629 [48:01<27:57, 23.60it/s]

 61%|██████    | 61037/100629 [48:01<26:35, 24.82it/s]

 61%|██████    | 61040/100629 [48:01<27:27, 24.03it/s]

 61%|██████    | 61043/100629 [48:02<25:52, 25.49it/s]

 61%|██████    | 61046/100629 [48:02<27:52, 23.66it/s]

 61%|██████    | 61050/100629 [48:02<24:54, 26.49it/s]

 61%|██████    | 61053/100629 [48:02<26:22, 25.00it/s]

 61%|██████    | 61056/100629 [48:02<28:00, 23.55it/s]

 61%|██████    | 61059/100629 [48:02<33:41, 19.57it/s]

 61%|██████    | 61062/100629 [48:03<33:18, 19.80it/s]

 61%|██████    | 61065/100629 [48:03<37:57, 17.37it/s]

 61%|██████    | 61068/100629 [48:03<35:37, 18.50it/s]

 61%|██████    | 61071/100629 [48:03<31:47, 20.74it/s]

 61%|██████    | 61074/100629 [48:03<30:15, 21.79it/s]

 61%|██████    | 61077/100629 [48:03<34:14, 19.25it/s]

 61%|██████    | 61080/100629 [48:03<34:03, 19.35it/s]

 61%|██████    | 61084/100629 [48:04<30:31, 21.59it/s]

 61%|██████    | 61087/100629 [48:04<30:26, 21.64it/s]

 61%|██████    | 61090/100629 [48:04<34:40, 19.01it/s]

 61%|██████    | 61092/100629 [48:04<36:06, 18.25it/s]

 61%|██████    | 61095/100629 [48:04<38:00, 17.34it/s]

 61%|██████    | 61097/100629 [48:04<37:51, 17.41it/s]

 61%|██████    | 61100/100629 [48:04<34:08, 19.30it/s]

 61%|██████    | 61103/100629 [48:05<31:27, 20.94it/s]

 61%|██████    | 61106/100629 [48:05<34:07, 19.31it/s]

 61%|██████    | 61109/100629 [48:05<31:22, 20.99it/s]

 61%|██████    | 61112/100629 [48:05<44:28, 14.81it/s]

 61%|██████    | 61116/100629 [48:05<38:21, 17.17it/s]

 61%|██████    | 61119/100629 [48:06<34:03, 19.33it/s]

 61%|██████    | 61122/100629 [48:06<32:48, 20.07it/s]

 61%|██████    | 61125/100629 [48:06<36:40, 17.95it/s]

 61%|██████    | 61129/100629 [48:06<31:28, 20.92it/s]

 61%|██████    | 61132/100629 [48:06<29:14, 22.52it/s]

 61%|██████    | 61136/100629 [48:06<26:12, 25.11it/s]

 61%|██████    | 61139/100629 [48:06<29:41, 22.16it/s]

 61%|██████    | 61142/100629 [48:07<27:39, 23.79it/s]

 61%|██████    | 61145/100629 [48:07<30:57, 21.26it/s]

 61%|██████    | 61148/100629 [48:07<30:52, 21.31it/s]

 61%|██████    | 61151/100629 [48:07<34:03, 19.32it/s]

 61%|██████    | 61154/100629 [48:07<31:13, 21.06it/s]

 61%|██████    | 61158/100629 [48:07<32:04, 20.51it/s]

 61%|██████    | 61162/100629 [48:07<28:18, 23.24it/s]

 61%|██████    | 61165/100629 [48:08<32:11, 20.43it/s]

 61%|██████    | 61168/100629 [48:08<31:28, 20.90it/s]

 61%|██████    | 61172/100629 [48:08<26:32, 24.77it/s]

 61%|██████    | 61175/100629 [48:08<28:35, 22.99it/s]

 61%|██████    | 61178/100629 [48:08<35:27, 18.54it/s]

 61%|██████    | 61181/100629 [48:08<35:26, 18.55it/s]

 61%|██████    | 61184/100629 [48:09<32:38, 20.14it/s]

 61%|██████    | 61187/100629 [48:09<33:15, 19.77it/s]

 61%|██████    | 61190/100629 [48:09<33:19, 19.73it/s]

 61%|██████    | 61193/100629 [48:09<31:07, 21.11it/s]

 61%|██████    | 61196/100629 [48:09<32:18, 20.34it/s]

 61%|██████    | 61199/100629 [48:09<32:32, 20.19it/s]

 61%|██████    | 61202/100629 [48:09<31:19, 20.97it/s]

 61%|██████    | 61206/100629 [48:10<28:18, 23.21it/s]

 61%|██████    | 61210/100629 [48:10<26:27, 24.82it/s]

 61%|██████    | 61213/100629 [48:10<28:19, 23.19it/s]

 61%|██████    | 61217/100629 [48:10<27:29, 23.89it/s]

 61%|██████    | 61220/100629 [48:10<32:29, 20.22it/s]

 61%|██████    | 61223/100629 [48:10<29:34, 22.21it/s]

 61%|██████    | 61226/100629 [48:11<36:37, 17.93it/s]

 61%|██████    | 61229/100629 [48:11<33:07, 19.82it/s]

 61%|██████    | 61232/100629 [48:11<47:34, 13.80it/s]

 61%|██████    | 61234/100629 [48:11<45:42, 14.36it/s]

 61%|██████    | 61237/100629 [48:11<38:24, 17.10it/s]

 61%|██████    | 61240/100629 [48:11<33:42, 19.47it/s]

 61%|██████    | 61243/100629 [48:12<34:56, 18.78it/s]

 61%|██████    | 61246/100629 [48:12<35:42, 18.38it/s]

 61%|██████    | 61249/100629 [48:12<31:50, 20.61it/s]

 61%|██████    | 61253/100629 [48:12<26:41, 24.59it/s]

 61%|██████    | 61256/100629 [48:12<30:01, 21.85it/s]

 61%|██████    | 61259/100629 [48:12<35:56, 18.25it/s]

 61%|██████    | 61262/100629 [48:12<32:59, 19.88it/s]

 61%|██████    | 61265/100629 [48:13<37:27, 17.51it/s]

 61%|██████    | 61267/100629 [48:13<40:58, 16.01it/s]

 61%|██████    | 61270/100629 [48:13<38:49, 16.90it/s]

 61%|██████    | 61272/100629 [48:13<40:41, 16.12it/s]

 61%|██████    | 61274/100629 [48:13<39:11, 16.74it/s]

 61%|██████    | 61278/100629 [48:13<29:47, 22.01it/s]

 61%|██████    | 61281/100629 [48:13<28:18, 23.17it/s]

 61%|██████    | 61284/100629 [48:14<29:00, 22.60it/s]

 61%|██████    | 61287/100629 [48:14<31:00, 21.15it/s]

 61%|██████    | 61290/100629 [48:14<34:29, 19.01it/s]

 61%|██████    | 61295/100629 [48:14<27:30, 23.83it/s]

 61%|██████    | 61298/100629 [48:14<31:55, 20.54it/s]

 61%|██████    | 61302/100629 [48:14<28:12, 23.24it/s]

 61%|██████    | 61305/100629 [48:15<30:39, 21.38it/s]

 61%|██████    | 61308/100629 [48:15<32:30, 20.16it/s]

 61%|██████    | 61312/100629 [48:15<28:21, 23.11it/s]

 61%|██████    | 61316/100629 [48:15<24:34, 26.66it/s]

 61%|██████    | 61319/100629 [48:15<28:54, 22.66it/s]

 61%|██████    | 61322/100629 [48:15<29:37, 22.12it/s]

 61%|██████    | 61327/100629 [48:16<26:38, 24.59it/s]

 61%|██████    | 61331/100629 [48:16<25:30, 25.67it/s]

 61%|██████    | 61334/100629 [48:16<27:15, 24.03it/s]

 61%|██████    | 61337/100629 [48:16<27:46, 23.58it/s]

 61%|██████    | 61340/100629 [48:16<28:16, 23.16it/s]

 61%|██████    | 61343/100629 [48:16<29:42, 22.04it/s]

 61%|██████    | 61346/100629 [48:16<29:19, 22.32it/s]

 61%|██████    | 61349/100629 [48:17<31:46, 20.60it/s]

 61%|██████    | 61352/100629 [48:17<31:23, 20.86it/s]

 61%|██████    | 61355/100629 [48:17<35:50, 18.26it/s]

 61%|██████    | 61357/100629 [48:17<35:48, 18.28it/s]

 61%|██████    | 61359/100629 [48:17<35:47, 18.28it/s]

 61%|██████    | 61362/100629 [48:17<32:13, 20.31it/s]

 61%|██████    | 61365/100629 [48:17<37:10, 17.61it/s]

 61%|██████    | 61368/100629 [48:18<34:34, 18.92it/s]

 61%|██████    | 61373/100629 [48:18<25:56, 25.22it/s]

 61%|██████    | 61376/100629 [48:18<29:57, 21.83it/s]

 61%|██████    | 61381/100629 [48:18<25:35, 25.56it/s]

 61%|██████    | 61384/100629 [48:18<27:37, 23.67it/s]

 61%|██████    | 61387/100629 [48:18<27:19, 23.93it/s]

 61%|██████    | 61390/100629 [48:18<26:07, 25.03it/s]

 61%|██████    | 61395/100629 [48:19<23:54, 27.35it/s]

 61%|██████    | 61398/100629 [48:19<24:00, 27.23it/s]

 61%|██████    | 61402/100629 [48:19<22:22, 29.22it/s]

 61%|██████    | 61405/100629 [48:19<23:24, 27.93it/s]

 61%|██████    | 61412/100629 [48:19<17:12, 37.98it/s]

 61%|██████    | 61416/100629 [48:19<19:59, 32.70it/s]

 61%|██████    | 61420/100629 [48:19<20:24, 32.01it/s]

 61%|██████    | 61424/100629 [48:19<21:55, 29.81it/s]

 61%|██████    | 61428/100629 [48:20<22:46, 28.69it/s]

 61%|██████    | 61431/100629 [48:20<23:56, 27.28it/s]

 61%|██████    | 61434/100629 [48:20<26:12, 24.93it/s]

 61%|██████    | 61437/100629 [48:20<26:58, 24.22it/s]

 61%|██████    | 61440/100629 [48:20<31:59, 20.42it/s]

 61%|██████    | 61443/100629 [48:20<33:40, 19.40it/s]

 61%|██████    | 61446/100629 [48:21<33:35, 19.44it/s]

 61%|██████    | 61449/100629 [48:21<32:27, 20.12it/s]

 61%|██████    | 61452/100629 [48:21<29:28, 22.15it/s]

 61%|██████    | 61455/100629 [48:21<30:22, 21.49it/s]

 61%|██████    | 61459/100629 [48:21<27:51, 23.43it/s]

 61%|██████    | 61462/100629 [48:21<28:23, 22.99it/s]

 61%|██████    | 61465/100629 [48:21<29:00, 22.50it/s]

 61%|██████    | 61468/100629 [48:22<30:13, 21.59it/s]

 61%|██████    | 61471/100629 [48:22<35:57, 18.15it/s]

 61%|██████    | 61476/100629 [48:22<28:02, 23.27it/s]

 61%|██████    | 61479/100629 [48:22<28:50, 22.63it/s]

 61%|██████    | 61482/100629 [48:22<30:54, 21.11it/s]

 61%|██████    | 61485/100629 [48:22<32:04, 20.34it/s]

 61%|██████    | 61489/100629 [48:22<27:27, 23.76it/s]

 61%|██████    | 61494/100629 [48:23<25:31, 25.55it/s]

 61%|██████    | 61497/100629 [48:23<31:22, 20.79it/s]

 61%|██████    | 61500/100629 [48:23<32:28, 20.08it/s]

 61%|██████    | 61503/100629 [48:23<32:17, 20.20it/s]

 61%|██████    | 61506/100629 [48:23<32:04, 20.33it/s]

 61%|██████    | 61510/100629 [48:23<28:32, 22.84it/s]

 61%|██████    | 61513/100629 [48:24<28:29, 22.88it/s]

 61%|██████    | 61516/100629 [48:24<30:10, 21.60it/s]

 61%|██████    | 61519/100629 [48:24<30:11, 21.59it/s]

 61%|██████    | 61522/100629 [48:24<33:40, 19.35it/s]

 61%|██████    | 61524/100629 [48:24<37:08, 17.55it/s]

 61%|██████    | 61527/100629 [48:24<36:00, 18.10it/s]

 61%|██████    | 61530/100629 [48:25<32:15, 20.20it/s]

 61%|██████    | 61533/100629 [48:25<30:21, 21.47it/s]

 61%|██████    | 61536/100629 [48:25<33:02, 19.72it/s]

 61%|██████    | 61539/100629 [48:25<32:21, 20.14it/s]

 61%|██████    | 61542/100629 [48:25<38:28, 16.93it/s]

 61%|██████    | 61545/100629 [48:25<34:34, 18.84it/s]

 61%|██████    | 61548/100629 [48:25<33:04, 19.69it/s]

 61%|██████    | 61552/100629 [48:26<28:58, 22.48it/s]

 61%|██████    | 61555/100629 [48:26<30:18, 21.49it/s]

 61%|██████    | 61558/100629 [48:26<29:51, 21.81it/s]

 61%|██████    | 61561/100629 [48:26<31:11, 20.88it/s]

 61%|██████    | 61564/100629 [48:26<42:33, 15.30it/s]

 61%|██████    | 61567/100629 [48:26<38:12, 17.04it/s]

 61%|██████    | 61569/100629 [48:27<40:21, 16.13it/s]

 61%|██████    | 61572/100629 [48:27<37:53, 17.18it/s]

 61%|██████    | 61574/100629 [48:27<39:19, 16.55it/s]

 61%|██████    | 61576/100629 [48:27<38:21, 16.97it/s]

 61%|██████    | 61579/100629 [48:27<34:47, 18.71it/s]

 61%|██████    | 61582/100629 [48:27<30:34, 21.29it/s]

 61%|██████    | 61585/100629 [48:27<31:37, 20.57it/s]

 61%|██████    | 61588/100629 [48:28<30:49, 21.11it/s]

 61%|██████    | 61591/100629 [48:28<28:12, 23.07it/s]

 61%|██████    | 61594/100629 [48:28<36:25, 17.86it/s]

 61%|██████    | 61597/100629 [48:28<34:43, 18.74it/s]

 61%|██████    | 61601/100629 [48:28<30:24, 21.39it/s]

 61%|██████    | 61605/100629 [48:28<31:06, 20.91it/s]

 61%|██████    | 61608/100629 [48:28<28:57, 22.45it/s]

 61%|██████    | 61611/100629 [48:29<34:34, 18.81it/s]

 61%|██████    | 61615/100629 [48:29<29:47, 21.83it/s]

 61%|██████    | 61618/100629 [48:29<29:15, 22.22it/s]

 61%|██████    | 61621/100629 [48:29<28:29, 22.82it/s]

 61%|██████    | 61624/100629 [48:29<26:35, 24.45it/s]

 61%|██████    | 61627/100629 [48:29<27:42, 23.45it/s]

 61%|██████    | 61630/100629 [48:29<26:43, 24.33it/s]

 61%|██████    | 61633/100629 [48:30<27:49, 23.36it/s]

 61%|██████▏   | 61637/100629 [48:30<24:08, 26.92it/s]

 61%|██████▏   | 61640/100629 [48:30<27:04, 24.00it/s]

 61%|██████▏   | 61643/100629 [48:30<31:53, 20.38it/s]

 61%|██████▏   | 61646/100629 [48:30<31:13, 20.81it/s]

 61%|██████▏   | 61649/100629 [48:30<33:45, 19.24it/s]

 61%|██████▏   | 61652/100629 [48:31<32:17, 20.12it/s]

 61%|██████▏   | 61655/100629 [48:31<30:26, 21.34it/s]

 61%|██████▏   | 61658/100629 [48:31<29:48, 21.79it/s]

 61%|██████▏   | 61661/100629 [48:31<31:05, 20.89it/s]

 61%|██████▏   | 61664/100629 [48:31<31:36, 20.54it/s]

 61%|██████▏   | 61668/100629 [48:31<26:30, 24.50it/s]

 61%|██████▏   | 61671/100629 [48:31<28:41, 22.62it/s]

 61%|██████▏   | 61674/100629 [48:32<30:24, 21.35it/s]

 61%|██████▏   | 61677/100629 [48:32<31:47, 20.42it/s]

 61%|██████▏   | 61680/100629 [48:32<37:57, 17.10it/s]

 61%|██████▏   | 61683/100629 [48:32<35:58, 18.04it/s]

 61%|██████▏   | 61685/100629 [48:32<36:25, 17.82it/s]

 61%|██████▏   | 61688/100629 [48:32<35:12, 18.43it/s]

 61%|██████▏   | 61690/100629 [48:32<37:12, 17.44it/s]

 61%|██████▏   | 61693/100629 [48:33<33:03, 19.63it/s]

 61%|██████▏   | 61696/100629 [48:33<31:58, 20.30it/s]

 61%|██████▏   | 61700/100629 [48:33<28:18, 22.92it/s]

 61%|██████▏   | 61703/100629 [48:33<34:12, 18.97it/s]

 61%|██████▏   | 61706/100629 [48:33<31:41, 20.47it/s]

 61%|██████▏   | 61709/100629 [48:33<31:34, 20.55it/s]

 61%|██████▏   | 61712/100629 [48:34<33:45, 19.21it/s]

 61%|██████▏   | 61715/100629 [48:34<30:52, 21.01it/s]

 61%|██████▏   | 61718/100629 [48:34<39:49, 16.29it/s]

 61%|██████▏   | 61721/100629 [48:34<36:09, 17.93it/s]

 61%|██████▏   | 61724/100629 [48:34<35:39, 18.19it/s]

 61%|██████▏   | 61727/100629 [48:34<34:01, 19.05it/s]

 61%|██████▏   | 61730/100629 [48:35<35:13, 18.41it/s]

 61%|██████▏   | 61733/100629 [48:35<31:23, 20.65it/s]

 61%|██████▏   | 61736/100629 [48:35<32:29, 19.95it/s]

 61%|██████▏   | 61740/100629 [48:35<29:46, 21.77it/s]

 61%|██████▏   | 61744/100629 [48:35<29:34, 21.91it/s]

 61%|██████▏   | 61747/100629 [48:35<29:39, 21.85it/s]

 61%|██████▏   | 61750/100629 [48:35<29:43, 21.80it/s]

 61%|██████▏   | 61753/100629 [48:36<30:56, 20.95it/s]

 61%|██████▏   | 61757/100629 [48:36<27:57, 23.17it/s]

 61%|██████▏   | 61760/100629 [48:36<30:35, 21.17it/s]

 61%|██████▏   | 61763/100629 [48:36<31:50, 20.34it/s]

 61%|██████▏   | 61767/100629 [48:36<28:04, 23.07it/s]

 61%|██████▏   | 61770/100629 [48:36<28:37, 22.63it/s]

 61%|██████▏   | 61773/100629 [48:36<27:02, 23.95it/s]

 61%|██████▏   | 61777/100629 [48:37<23:35, 27.46it/s]

 61%|██████▏   | 61780/100629 [48:37<25:18, 25.58it/s]

 61%|██████▏   | 61783/100629 [48:37<30:12, 21.44it/s]

 61%|██████▏   | 61786/100629 [48:37<28:15, 22.91it/s]

 61%|██████▏   | 61790/100629 [48:37<26:22, 24.54it/s]

 61%|██████▏   | 61794/100629 [48:37<23:55, 27.05it/s]

 61%|██████▏   | 61797/100629 [48:37<27:40, 23.39it/s]

 61%|██████▏   | 61800/100629 [48:37<26:08, 24.75it/s]

 61%|██████▏   | 61803/100629 [48:38<28:48, 22.46it/s]

 61%|██████▏   | 61807/100629 [48:38<31:11, 20.74it/s]

 61%|██████▏   | 61810/100629 [48:38<30:55, 20.92it/s]

 61%|██████▏   | 61814/100629 [48:38<26:50, 24.10it/s]

 61%|██████▏   | 61817/100629 [48:38<29:53, 21.63it/s]

 61%|██████▏   | 61820/100629 [48:38<29:26, 21.97it/s]

 61%|██████▏   | 61823/100629 [48:39<28:28, 22.71it/s]

 61%|██████▏   | 61826/100629 [48:39<26:59, 23.96it/s]

 61%|██████▏   | 61829/100629 [48:39<28:28, 22.71it/s]

 61%|██████▏   | 61832/100629 [48:39<32:03, 20.17it/s]

 61%|██████▏   | 61835/100629 [48:39<30:44, 21.03it/s]

 61%|██████▏   | 61838/100629 [48:39<28:09, 22.96it/s]

 61%|██████▏   | 61841/100629 [48:39<27:33, 23.45it/s]

 61%|██████▏   | 61844/100629 [48:39<27:39, 23.37it/s]

 61%|██████▏   | 61848/100629 [48:40<25:29, 25.35it/s]

 61%|██████▏   | 61851/100629 [48:40<25:40, 25.17it/s]

 61%|██████▏   | 61854/100629 [48:40<30:55, 20.90it/s]

 61%|██████▏   | 61857/100629 [48:40<29:48, 21.68it/s]

 61%|██████▏   | 61861/100629 [48:40<25:23, 25.45it/s]

 61%|██████▏   | 61864/100629 [48:40<28:16, 22.86it/s]

 61%|██████▏   | 61867/100629 [48:41<31:38, 20.41it/s]

 61%|██████▏   | 61870/100629 [48:41<31:04, 20.79it/s]

 61%|██████▏   | 61873/100629 [48:41<32:02, 20.16it/s]

 61%|██████▏   | 61876/100629 [48:41<31:11, 20.71it/s]

 61%|██████▏   | 61879/100629 [48:41<31:52, 20.26it/s]

 61%|██████▏   | 61882/100629 [48:41<28:53, 22.35it/s]

 61%|██████▏   | 61885/100629 [48:41<32:38, 19.79it/s]

 62%|██████▏   | 61888/100629 [48:42<33:03, 19.53it/s]

 62%|██████▏   | 61891/100629 [48:42<32:36, 19.80it/s]

 62%|██████▏   | 61894/100629 [48:42<34:17, 18.83it/s]

 62%|██████▏   | 61897/100629 [48:42<32:37, 19.78it/s]

 62%|██████▏   | 61901/100629 [48:42<28:38, 22.54it/s]

 62%|██████▏   | 61904/100629 [48:42<36:23, 17.74it/s]

 62%|██████▏   | 61906/100629 [48:43<37:52, 17.04it/s]

 62%|██████▏   | 61909/100629 [48:43<35:36, 18.12it/s]

 62%|██████▏   | 61912/100629 [48:43<34:05, 18.93it/s]

 62%|██████▏   | 61914/100629 [48:43<33:50, 19.07it/s]

 62%|██████▏   | 61917/100629 [48:43<32:48, 19.67it/s]

 62%|██████▏   | 61920/100629 [48:43<32:42, 19.73it/s]

 62%|██████▏   | 61923/100629 [48:43<30:50, 20.92it/s]

 62%|██████▏   | 61926/100629 [48:44<30:42, 21.00it/s]

 62%|██████▏   | 61930/100629 [48:44<25:57, 24.84it/s]

 62%|██████▏   | 61934/100629 [48:44<24:37, 26.18it/s]

 62%|██████▏   | 61937/100629 [48:44<26:23, 24.43it/s]

 62%|██████▏   | 61940/100629 [48:44<34:05, 18.91it/s]

 62%|██████▏   | 61943/100629 [48:44<30:55, 20.85it/s]

 62%|██████▏   | 61946/100629 [48:44<33:09, 19.44it/s]

 62%|██████▏   | 61949/100629 [48:45<32:02, 20.12it/s]

 62%|██████▏   | 61953/100629 [48:45<28:57, 22.26it/s]

 62%|██████▏   | 61957/100629 [48:45<25:50, 24.95it/s]

 62%|██████▏   | 61961/100629 [48:45<24:12, 26.61it/s]

 62%|██████▏   | 61964/100629 [48:45<24:02, 26.81it/s]

 62%|██████▏   | 61967/100629 [48:45<26:54, 23.94it/s]

 62%|██████▏   | 61970/100629 [48:45<27:27, 23.46it/s]

 62%|██████▏   | 61973/100629 [48:45<26:06, 24.68it/s]

 62%|██████▏   | 61976/100629 [48:46<26:40, 24.14it/s]

 62%|██████▏   | 61979/100629 [48:46<32:28, 19.84it/s]

 62%|██████▏   | 61983/100629 [48:46<28:59, 22.22it/s]

 62%|██████▏   | 61987/100629 [48:46<29:00, 22.21it/s]

 62%|██████▏   | 61991/100629 [48:46<24:49, 25.94it/s]

 62%|██████▏   | 61994/100629 [48:46<24:45, 26.01it/s]

 62%|██████▏   | 61997/100629 [48:47<27:17, 23.60it/s]

 62%|██████▏   | 62000/100629 [48:47<29:18, 21.97it/s]

 62%|██████▏   | 62003/100629 [48:47<29:41, 21.68it/s]

 62%|██████▏   | 62006/100629 [48:47<29:45, 21.63it/s]

 62%|██████▏   | 62009/100629 [48:47<34:55, 18.43it/s]

 62%|██████▏   | 62012/100629 [48:47<32:53, 19.57it/s]

 62%|██████▏   | 62015/100629 [48:47<33:01, 19.49it/s]

 62%|██████▏   | 62018/100629 [48:48<34:31, 18.64it/s]

 62%|██████▏   | 62020/100629 [48:48<39:51, 16.15it/s]

 62%|██████▏   | 62022/100629 [48:48<41:06, 15.65it/s]

 62%|██████▏   | 62025/100629 [48:48<35:17, 18.23it/s]

 62%|██████▏   | 62029/100629 [48:48<34:12, 18.81it/s]

 62%|██████▏   | 62032/100629 [48:48<31:25, 20.47it/s]

 62%|██████▏   | 62036/100629 [48:49<26:07, 24.62it/s]

 62%|██████▏   | 62039/100629 [48:49<29:29, 21.81it/s]

 62%|██████▏   | 62042/100629 [48:49<29:46, 21.60it/s]

 62%|██████▏   | 62047/100629 [48:49<24:33, 26.19it/s]

 62%|██████▏   | 62050/100629 [48:49<25:46, 24.95it/s]

 62%|██████▏   | 62054/100629 [48:49<23:56, 26.85it/s]

 62%|██████▏   | 62057/100629 [48:49<28:40, 22.41it/s]

 62%|██████▏   | 62061/100629 [48:50<24:30, 26.23it/s]

 62%|██████▏   | 62064/100629 [48:50<24:05, 26.68it/s]

 62%|██████▏   | 62068/100629 [48:50<22:27, 28.62it/s]

 62%|██████▏   | 62071/100629 [48:50<22:39, 28.35it/s]

 62%|██████▏   | 62074/100629 [48:50<26:19, 24.40it/s]

 62%|██████▏   | 62077/100629 [48:50<25:47, 24.91it/s]

 62%|██████▏   | 62081/100629 [48:50<22:27, 28.60it/s]

 62%|██████▏   | 62085/100629 [48:50<22:45, 28.22it/s]

 62%|██████▏   | 62088/100629 [48:51<24:45, 25.94it/s]

 62%|██████▏   | 62091/100629 [48:51<28:44, 22.35it/s]

 62%|██████▏   | 62094/100629 [48:51<28:14, 22.74it/s]

 62%|██████▏   | 62097/100629 [48:51<29:21, 21.88it/s]

 62%|██████▏   | 62100/100629 [48:51<33:18, 19.28it/s]

 62%|██████▏   | 62104/100629 [48:51<31:39, 20.28it/s]

 62%|██████▏   | 62107/100629 [48:52<31:17, 20.51it/s]

 62%|██████▏   | 62110/100629 [48:52<32:15, 19.90it/s]

 62%|██████▏   | 62113/100629 [48:52<45:27, 14.12it/s]

 62%|██████▏   | 62116/100629 [48:52<39:02, 16.44it/s]

 62%|██████▏   | 62120/100629 [48:52<35:04, 18.30it/s]

 62%|██████▏   | 62123/100629 [48:52<34:01, 18.86it/s]

 62%|██████▏   | 62126/100629 [48:53<32:52, 19.52it/s]

 62%|██████▏   | 62130/100629 [48:53<32:13, 19.91it/s]

 62%|██████▏   | 62133/100629 [48:53<29:34, 21.69it/s]

 62%|██████▏   | 62136/100629 [48:53<29:32, 21.72it/s]

 62%|██████▏   | 62139/100629 [48:53<30:08, 21.29it/s]

 62%|██████▏   | 62142/100629 [48:53<27:41, 23.17it/s]

 62%|██████▏   | 62146/100629 [48:53<24:46, 25.89it/s]

 62%|██████▏   | 62149/100629 [48:54<25:39, 25.00it/s]

 62%|██████▏   | 62152/100629 [48:54<26:07, 24.55it/s]

 62%|██████▏   | 62155/100629 [48:54<37:52, 16.93it/s]

 62%|██████▏   | 62158/100629 [48:54<34:02, 18.83it/s]

 62%|██████▏   | 62162/100629 [48:54<27:47, 23.07it/s]

 62%|██████▏   | 62165/100629 [48:54<28:15, 22.69it/s]

 62%|██████▏   | 62168/100629 [48:54<28:27, 22.53it/s]

 62%|██████▏   | 62171/100629 [48:55<28:05, 22.82it/s]

 62%|██████▏   | 62174/100629 [48:55<30:44, 20.85it/s]

 62%|██████▏   | 62178/100629 [48:55<26:35, 24.09it/s]

 62%|██████▏   | 62182/100629 [48:55<23:30, 27.25it/s]

 62%|██████▏   | 62185/100629 [48:55<24:48, 25.83it/s]

 62%|██████▏   | 62188/100629 [48:55<28:21, 22.59it/s]

 62%|██████▏   | 62191/100629 [48:55<29:48, 21.49it/s]

 62%|██████▏   | 62194/100629 [48:56<29:34, 21.66it/s]

 62%|██████▏   | 62197/100629 [48:56<28:16, 22.65it/s]

 62%|██████▏   | 62200/100629 [48:56<31:38, 20.24it/s]

 62%|██████▏   | 62204/100629 [48:56<26:16, 24.37it/s]

 62%|██████▏   | 62207/100629 [48:56<25:10, 25.44it/s]

 62%|██████▏   | 62210/100629 [48:56<25:31, 25.08it/s]

 62%|██████▏   | 62213/100629 [48:56<24:58, 25.64it/s]

 62%|██████▏   | 62217/100629 [48:57<24:32, 26.09it/s]

 62%|██████▏   | 62220/100629 [48:57<24:12, 26.45it/s]

 62%|██████▏   | 62223/100629 [48:57<23:36, 27.12it/s]

 62%|██████▏   | 62226/100629 [48:57<24:29, 26.14it/s]

 62%|██████▏   | 62229/100629 [48:57<27:46, 23.05it/s]

 62%|██████▏   | 62232/100629 [48:57<25:57, 24.65it/s]

 62%|██████▏   | 62236/100629 [48:57<24:33, 26.06it/s]

 62%|██████▏   | 62239/100629 [48:57<23:54, 26.77it/s]

 62%|██████▏   | 62242/100629 [48:58<32:46, 19.52it/s]

 62%|██████▏   | 62245/100629 [48:58<32:15, 19.83it/s]

 62%|██████▏   | 62248/100629 [48:58<33:40, 19.00it/s]

 62%|██████▏   | 62251/100629 [48:58<31:50, 20.09it/s]

 62%|██████▏   | 62255/100629 [48:58<28:18, 22.60it/s]

 62%|██████▏   | 62258/100629 [48:58<29:44, 21.50it/s]

 62%|██████▏   | 62261/100629 [48:58<29:36, 21.60it/s]

 62%|██████▏   | 62264/100629 [48:59<31:25, 20.35it/s]

 62%|██████▏   | 62268/100629 [48:59<26:16, 24.34it/s]

 62%|██████▏   | 62271/100629 [48:59<30:48, 20.75it/s]

 62%|██████▏   | 62274/100629 [48:59<30:13, 21.15it/s]

 62%|██████▏   | 62277/100629 [48:59<32:04, 19.93it/s]

 62%|██████▏   | 62280/100629 [48:59<30:16, 21.12it/s]

 62%|██████▏   | 62283/100629 [49:00<37:14, 17.16it/s]

 62%|██████▏   | 62287/100629 [49:00<37:38, 16.98it/s]

 62%|██████▏   | 62289/100629 [49:00<36:58, 17.29it/s]

 62%|██████▏   | 62291/100629 [49:00<39:52, 16.03it/s]

 62%|██████▏   | 62295/100629 [49:00<31:27, 20.31it/s]

 62%|██████▏   | 62298/100629 [49:00<31:08, 20.52it/s]

 62%|██████▏   | 62302/100629 [49:01<31:07, 20.53it/s]

 62%|██████▏   | 62305/100629 [49:01<32:07, 19.89it/s]

 62%|██████▏   | 62308/100629 [49:01<31:51, 20.05it/s]

 62%|██████▏   | 62311/100629 [49:01<31:02, 20.58it/s]

 62%|██████▏   | 62314/100629 [49:01<28:48, 22.17it/s]

 62%|██████▏   | 62318/100629 [49:01<25:56, 24.61it/s]

 62%|██████▏   | 62322/100629 [49:01<23:46, 26.85it/s]

 62%|██████▏   | 62325/100629 [49:02<28:56, 22.06it/s]

 62%|██████▏   | 62328/100629 [49:02<29:43, 21.48it/s]

 62%|██████▏   | 62331/100629 [49:02<31:32, 20.24it/s]

 62%|██████▏   | 62335/100629 [49:02<27:49, 22.94it/s]

 62%|██████▏   | 62338/100629 [49:02<31:16, 20.41it/s]

 62%|██████▏   | 62341/100629 [49:02<30:23, 20.99it/s]

 62%|██████▏   | 62345/100629 [49:03<25:58, 24.57it/s]

 62%|██████▏   | 62348/100629 [49:03<27:19, 23.35it/s]

 62%|██████▏   | 62351/100629 [49:03<26:20, 24.22it/s]

 62%|██████▏   | 62354/100629 [49:03<26:36, 23.98it/s]

 62%|██████▏   | 62358/100629 [49:03<24:22, 26.16it/s]

 62%|██████▏   | 62363/100629 [49:03<20:58, 30.41it/s]

 62%|██████▏   | 62367/100629 [49:03<27:48, 22.93it/s]

 62%|██████▏   | 62370/100629 [49:04<36:34, 17.43it/s]

 62%|██████▏   | 62373/100629 [49:04<38:05, 16.74it/s]

 62%|██████▏   | 62376/100629 [49:04<35:36, 17.90it/s]

 62%|██████▏   | 62380/100629 [49:04<30:01, 21.23it/s]

 62%|██████▏   | 62383/100629 [49:04<31:25, 20.28it/s]

 62%|██████▏   | 62386/100629 [49:04<31:04, 20.52it/s]

 62%|██████▏   | 62390/100629 [49:05<28:03, 22.71it/s]

 62%|██████▏   | 62393/100629 [49:05<32:38, 19.53it/s]

 62%|██████▏   | 62396/100629 [49:05<33:12, 19.19it/s]

 62%|██████▏   | 62400/100629 [49:05<31:22, 20.30it/s]

 62%|██████▏   | 62403/100629 [49:05<35:00, 18.20it/s]

 62%|██████▏   | 62405/100629 [49:05<34:48, 18.31it/s]

 62%|██████▏   | 62408/100629 [49:06<30:54, 20.61it/s]

 62%|██████▏   | 62411/100629 [49:06<28:31, 22.33it/s]

 62%|██████▏   | 62416/100629 [49:06<24:08, 26.38it/s]

 62%|██████▏   | 62420/100629 [49:06<26:08, 24.36it/s]

 62%|██████▏   | 62425/100629 [49:06<21:58, 28.99it/s]

 62%|██████▏   | 62429/100629 [49:06<21:45, 29.26it/s]

 62%|██████▏   | 62433/100629 [49:07<27:52, 22.83it/s]

 62%|██████▏   | 62436/100629 [49:07<31:21, 20.30it/s]

 62%|██████▏   | 62440/100629 [49:07<27:47, 22.91it/s]

 62%|██████▏   | 62443/100629 [49:07<29:18, 21.72it/s]

 62%|██████▏   | 62446/100629 [49:07<34:35, 18.40it/s]

 62%|██████▏   | 62450/100629 [49:07<29:11, 21.80it/s]

 62%|██████▏   | 62453/100629 [49:08<34:14, 18.58it/s]

 62%|██████▏   | 62456/100629 [49:08<33:42, 18.87it/s]

 62%|██████▏   | 62459/100629 [49:08<32:37, 19.50it/s]

 62%|██████▏   | 62462/100629 [49:08<32:51, 19.36it/s]

 62%|██████▏   | 62466/100629 [49:08<27:49, 22.86it/s]

 62%|██████▏   | 62469/100629 [49:08<31:27, 20.22it/s]

 62%|██████▏   | 62473/100629 [49:08<26:46, 23.76it/s]

 62%|██████▏   | 62477/100629 [49:09<24:39, 25.78it/s]

 62%|██████▏   | 62481/100629 [49:09<23:46, 26.74it/s]

 62%|██████▏   | 62485/100629 [49:09<22:44, 27.95it/s]

 62%|██████▏   | 62489/100629 [49:09<20:58, 30.31it/s]

 62%|██████▏   | 62493/100629 [49:09<21:49, 29.13it/s]

 62%|██████▏   | 62497/100629 [49:09<23:53, 26.60it/s]

 62%|██████▏   | 62500/100629 [49:09<27:24, 23.18it/s]

 62%|██████▏   | 62503/100629 [49:10<31:31, 20.16it/s]

 62%|██████▏   | 62506/100629 [49:10<32:55, 19.30it/s]

 62%|██████▏   | 62510/100629 [49:10<28:30, 22.28it/s]

 62%|██████▏   | 62513/100629 [49:10<28:33, 22.25it/s]

 62%|██████▏   | 62516/100629 [49:10<32:24, 19.60it/s]

 62%|██████▏   | 62520/100629 [49:10<30:25, 20.88it/s]

 62%|██████▏   | 62523/100629 [49:11<31:27, 20.19it/s]

 62%|██████▏   | 62526/100629 [49:11<30:55, 20.53it/s]

 62%|██████▏   | 62529/100629 [49:11<29:51, 21.27it/s]

 62%|██████▏   | 62533/100629 [49:11<25:23, 25.00it/s]

 62%|██████▏   | 62536/100629 [49:11<30:39, 20.70it/s]

 62%|██████▏   | 62539/100629 [49:11<33:28, 18.96it/s]

 62%|██████▏   | 62542/100629 [49:12<40:04, 15.84it/s]

 62%|██████▏   | 62544/100629 [49:12<38:57, 16.29it/s]

 62%|██████▏   | 62546/100629 [49:12<37:35, 16.89it/s]

 62%|██████▏   | 62549/100629 [49:12<33:51, 18.75it/s]

 62%|██████▏   | 62552/100629 [49:12<31:55, 19.88it/s]

 62%|██████▏   | 62555/100629 [49:12<31:30, 20.14it/s]

 62%|██████▏   | 62559/100629 [49:12<28:47, 22.04it/s]

 62%|██████▏   | 62562/100629 [49:13<32:09, 19.73it/s]

 62%|██████▏   | 62565/100629 [49:13<39:14, 16.16it/s]

 62%|██████▏   | 62568/100629 [49:13<36:13, 17.51it/s]

 62%|██████▏   | 62571/100629 [49:13<32:17, 19.65it/s]

 62%|██████▏   | 62574/100629 [49:13<33:17, 19.05it/s]

 62%|██████▏   | 62577/100629 [49:13<30:31, 20.78it/s]

 62%|██████▏   | 62580/100629 [49:14<32:45, 19.35it/s]

 62%|██████▏   | 62583/100629 [49:14<30:15, 20.96it/s]

 62%|██████▏   | 62586/100629 [49:14<30:37, 20.70it/s]

 62%|██████▏   | 62591/100629 [49:14<24:28, 25.90it/s]

 62%|██████▏   | 62594/100629 [49:14<25:00, 25.35it/s]

 62%|██████▏   | 62597/100629 [49:14<30:41, 20.66it/s]

 62%|██████▏   | 62601/100629 [49:15<28:10, 22.50it/s]

 62%|██████▏   | 62604/100629 [49:15<28:20, 22.37it/s]

 62%|██████▏   | 62607/100629 [49:15<28:51, 21.96it/s]

 62%|██████▏   | 62610/100629 [49:15<28:57, 21.89it/s]

 62%|██████▏   | 62614/100629 [49:15<27:34, 22.97it/s]

 62%|██████▏   | 62617/100629 [49:15<32:12, 19.67it/s]

 62%|██████▏   | 62620/100629 [49:16<38:38, 16.40it/s]

 62%|██████▏   | 62623/100629 [49:16<34:59, 18.10it/s]

 62%|██████▏   | 62626/100629 [49:16<31:44, 19.95it/s]

 62%|██████▏   | 62630/100629 [49:16<28:05, 22.55it/s]

 62%|██████▏   | 62634/100629 [49:16<23:58, 26.42it/s]

 62%|██████▏   | 62637/100629 [49:16<31:32, 20.07it/s]

 62%|██████▏   | 62640/100629 [49:16<29:20, 21.57it/s]

 62%|██████▏   | 62643/100629 [49:17<29:29, 21.46it/s]

 62%|██████▏   | 62646/100629 [49:17<27:55, 22.67it/s]

 62%|██████▏   | 62649/100629 [49:17<27:26, 23.07it/s]

 62%|██████▏   | 62652/100629 [49:17<33:47, 18.73it/s]

 62%|██████▏   | 62655/100629 [49:17<37:40, 16.80it/s]

 62%|██████▏   | 62658/100629 [49:17<33:23, 18.95it/s]

 62%|██████▏   | 62661/100629 [49:17<31:39, 19.99it/s]

 62%|██████▏   | 62664/100629 [49:18<29:44, 21.27it/s]

 62%|██████▏   | 62667/100629 [49:18<33:32, 18.86it/s]

 62%|██████▏   | 62670/100629 [49:18<33:32, 18.86it/s]

 62%|██████▏   | 62672/100629 [49:18<36:38, 17.26it/s]

 62%|██████▏   | 62674/100629 [49:18<35:56, 17.60it/s]

 62%|██████▏   | 62676/100629 [49:18<35:18, 17.92it/s]

 62%|██████▏   | 62678/100629 [49:18<34:31, 18.32it/s]

 62%|██████▏   | 62680/100629 [49:19<33:59, 18.61it/s]

 62%|██████▏   | 62682/100629 [49:19<35:37, 17.75it/s]

 62%|██████▏   | 62685/100629 [49:19<32:49, 19.27it/s]

 62%|██████▏   | 62687/100629 [49:19<42:36, 14.84it/s]

 62%|██████▏   | 62689/100629 [49:19<40:53, 15.46it/s]

 62%|██████▏   | 62692/100629 [49:19<36:20, 17.40it/s]

 62%|██████▏   | 62695/100629 [49:19<31:29, 20.07it/s]

 62%|██████▏   | 62698/100629 [49:20<36:18, 17.42it/s]

 62%|██████▏   | 62700/100629 [49:20<37:56, 16.66it/s]

 62%|██████▏   | 62703/100629 [49:20<32:13, 19.61it/s]

 62%|██████▏   | 62706/100629 [49:20<29:54, 21.13it/s]

 62%|██████▏   | 62710/100629 [49:20<25:57, 24.34it/s]

 62%|██████▏   | 62713/100629 [49:20<27:02, 23.37it/s]

 62%|██████▏   | 62716/100629 [49:20<30:20, 20.83it/s]

 62%|██████▏   | 62719/100629 [49:21<34:45, 18.17it/s]

 62%|██████▏   | 62722/100629 [49:21<32:39, 19.34it/s]

 62%|██████▏   | 62725/100629 [49:21<31:53, 19.81it/s]

 62%|██████▏   | 62728/100629 [49:21<28:58, 21.80it/s]

 62%|██████▏   | 62731/100629 [49:21<28:05, 22.48it/s]

 62%|██████▏   | 62735/100629 [49:21<27:48, 22.71it/s]

 62%|██████▏   | 62738/100629 [49:21<26:37, 23.72it/s]

 62%|██████▏   | 62741/100629 [49:22<26:49, 23.55it/s]

 62%|██████▏   | 62745/100629 [49:22<27:34, 22.89it/s]

 62%|██████▏   | 62748/100629 [49:22<26:19, 23.98it/s]

 62%|██████▏   | 62751/100629 [49:22<31:03, 20.33it/s]

 62%|██████▏   | 62756/100629 [49:22<25:42, 24.55it/s]

 62%|██████▏   | 62759/100629 [49:22<25:12, 25.04it/s]

 62%|██████▏   | 62763/100629 [49:22<22:35, 27.94it/s]

 62%|██████▏   | 62768/100629 [49:23<22:34, 27.95it/s]

 62%|██████▏   | 62775/100629 [49:23<18:01, 35.00it/s]

 62%|██████▏   | 62779/100629 [49:23<19:31, 32.32it/s]

 62%|██████▏   | 62783/100629 [49:23<24:06, 26.17it/s]

 62%|██████▏   | 62786/100629 [49:23<24:47, 25.45it/s]

 62%|██████▏   | 62789/100629 [49:23<24:09, 26.10it/s]

 62%|██████▏   | 62792/100629 [49:23<23:45, 26.55it/s]

 62%|██████▏   | 62795/100629 [49:24<26:50, 23.49it/s]

 62%|██████▏   | 62799/100629 [49:24<24:58, 25.24it/s]

 62%|██████▏   | 62802/100629 [49:24<24:13, 26.02it/s]

 62%|██████▏   | 62805/100629 [49:24<26:59, 23.35it/s]

 62%|██████▏   | 62808/100629 [49:24<37:37, 16.76it/s]

 62%|██████▏   | 62811/100629 [49:24<33:11, 18.99it/s]

 62%|██████▏   | 62814/100629 [49:25<34:24, 18.31it/s]

 62%|██████▏   | 62817/100629 [49:25<36:12, 17.41it/s]

 62%|██████▏   | 62819/100629 [49:25<42:27, 14.84it/s]

 62%|██████▏   | 62821/100629 [49:25<42:27, 14.84it/s]

 62%|██████▏   | 62823/100629 [49:25<40:13, 15.66it/s]

 62%|██████▏   | 62826/100629 [49:25<39:02, 16.14it/s]

 62%|██████▏   | 62828/100629 [49:26<37:54, 16.62it/s]

 62%|██████▏   | 62830/100629 [49:26<42:29, 14.83it/s]

 62%|██████▏   | 62833/100629 [49:26<35:18, 17.84it/s]

 62%|██████▏   | 62835/100629 [49:26<40:42, 15.47it/s]

 62%|██████▏   | 62837/100629 [49:26<39:32, 15.93it/s]

 62%|██████▏   | 62840/100629 [49:26<34:49, 18.09it/s]

 62%|██████▏   | 62842/100629 [49:26<34:03, 18.49it/s]

 62%|██████▏   | 62847/100629 [49:26<27:21, 23.02it/s]

 62%|██████▏   | 62850/100629 [49:27<28:40, 21.96it/s]

 62%|██████▏   | 62853/100629 [49:27<27:00, 23.31it/s]

 62%|██████▏   | 62858/100629 [49:27<22:31, 27.95it/s]

 62%|██████▏   | 62861/100629 [49:27<25:07, 25.05it/s]

 62%|██████▏   | 62864/100629 [49:27<24:18, 25.89it/s]

 62%|██████▏   | 62867/100629 [49:27<26:11, 24.02it/s]

 62%|██████▏   | 62870/100629 [49:28<33:29, 18.79it/s]

 62%|██████▏   | 62873/100629 [49:28<32:21, 19.44it/s]

 62%|██████▏   | 62876/100629 [49:28<36:31, 17.23it/s]

 62%|██████▏   | 62879/100629 [49:28<35:51, 17.54it/s]

 62%|██████▏   | 62881/100629 [49:28<40:58, 15.35it/s]

 62%|██████▏   | 62884/100629 [49:28<35:06, 17.92it/s]

 62%|██████▏   | 62887/100629 [49:28<32:49, 19.16it/s]

 62%|██████▏   | 62890/100629 [49:29<34:51, 18.04it/s]

 62%|██████▏   | 62892/100629 [49:29<36:36, 17.18it/s]

 63%|██████▎   | 62894/100629 [49:29<36:12, 17.37it/s]

 63%|██████▎   | 62897/100629 [49:29<32:33, 19.32it/s]

 63%|██████▎   | 62899/100629 [49:29<40:30, 15.52it/s]

 63%|██████▎   | 62902/100629 [49:29<34:02, 18.47it/s]

 63%|██████▎   | 62905/100629 [49:29<30:20, 20.73it/s]

 63%|██████▎   | 62909/100629 [49:30<26:05, 24.09it/s]

 63%|██████▎   | 62912/100629 [49:30<31:12, 20.14it/s]

 63%|██████▎   | 62915/100629 [49:30<30:13, 20.79it/s]

 63%|██████▎   | 62918/100629 [49:30<29:18, 21.44it/s]

 63%|██████▎   | 62921/100629 [49:30<27:49, 22.59it/s]

 63%|██████▎   | 62924/100629 [49:30<29:35, 21.24it/s]

 63%|██████▎   | 62927/100629 [49:30<28:22, 22.15it/s]

 63%|██████▎   | 62933/100629 [49:31<22:06, 28.41it/s]

 63%|██████▎   | 62936/100629 [49:31<22:39, 27.72it/s]

 63%|██████▎   | 62940/100629 [49:31<20:35, 30.49it/s]

 63%|██████▎   | 62944/100629 [49:31<26:13, 23.95it/s]

 63%|██████▎   | 62947/100629 [49:31<26:20, 23.85it/s]

 63%|██████▎   | 62950/100629 [49:31<26:42, 23.52it/s]

 63%|██████▎   | 62953/100629 [49:31<26:27, 23.74it/s]

 63%|██████▎   | 62956/100629 [49:32<28:19, 22.17it/s]

 63%|██████▎   | 62959/100629 [49:32<27:00, 23.25it/s]

 63%|██████▎   | 62962/100629 [49:32<26:19, 23.84it/s]

 63%|██████▎   | 62966/100629 [49:32<23:17, 26.95it/s]

 63%|██████▎   | 62969/100629 [49:32<25:39, 24.46it/s]

 63%|██████▎   | 62972/100629 [49:32<27:05, 23.16it/s]

 63%|██████▎   | 62975/100629 [49:33<41:44, 15.03it/s]

 63%|██████▎   | 62978/100629 [49:33<37:36, 16.69it/s]

 63%|██████▎   | 62982/100629 [49:33<32:55, 19.06it/s]

 63%|██████▎   | 62985/100629 [49:33<31:03, 20.20it/s]

 63%|██████▎   | 62988/100629 [49:33<35:40, 17.59it/s]

 63%|██████▎   | 62992/100629 [49:33<29:35, 21.20it/s]

 63%|██████▎   | 62995/100629 [49:34<38:41, 16.21it/s]

 63%|██████▎   | 62998/100629 [49:34<39:12, 15.99it/s]

 63%|██████▎   | 63000/100629 [49:34<40:59, 15.30it/s]

 63%|██████▎   | 63004/100629 [49:34<36:40, 17.10it/s]

 63%|██████▎   | 63006/100629 [49:34<36:15, 17.30it/s]

 63%|██████▎   | 63009/100629 [49:34<32:58, 19.01it/s]

 63%|██████▎   | 63012/100629 [49:35<30:38, 20.46it/s]

 63%|██████▎   | 63015/100629 [49:35<31:27, 19.93it/s]

 63%|██████▎   | 63018/100629 [49:35<29:41, 21.11it/s]

 63%|██████▎   | 63021/100629 [49:35<30:50, 20.33it/s]

 63%|██████▎   | 63024/100629 [49:35<30:01, 20.87it/s]

 63%|██████▎   | 63027/100629 [49:35<30:14, 20.73it/s]

 63%|██████▎   | 63030/100629 [49:35<33:28, 18.72it/s]

 63%|██████▎   | 63033/100629 [49:36<29:46, 21.04it/s]

 63%|██████▎   | 63037/100629 [49:36<28:23, 22.07it/s]

 63%|██████▎   | 63040/100629 [49:36<32:21, 19.36it/s]

 63%|██████▎   | 63043/100629 [49:36<30:38, 20.44it/s]

 63%|██████▎   | 63046/100629 [49:36<29:04, 21.54it/s]

 63%|██████▎   | 63049/100629 [49:36<29:49, 21.00it/s]

 63%|██████▎   | 63052/100629 [49:36<30:57, 20.22it/s]

 63%|██████▎   | 63056/100629 [49:37<25:31, 24.53it/s]

 63%|██████▎   | 63059/100629 [49:37<31:06, 20.13it/s]

 63%|██████▎   | 63062/100629 [49:37<37:39, 16.63it/s]

 63%|██████▎   | 63064/100629 [49:37<41:39, 15.03it/s]

 63%|██████▎   | 63067/100629 [49:37<35:44, 17.52it/s]

 63%|██████▎   | 63070/100629 [49:37<33:00, 18.97it/s]

 63%|██████▎   | 63073/100629 [49:38<34:30, 18.14it/s]

 63%|██████▎   | 63078/100629 [49:38<26:32, 23.58it/s]

 63%|██████▎   | 63081/100629 [49:38<32:42, 19.13it/s]

 63%|██████▎   | 63085/100629 [49:38<31:26, 19.90it/s]

 63%|██████▎   | 63088/100629 [49:38<34:36, 18.08it/s]

 63%|██████▎   | 63090/100629 [49:39<35:21, 17.70it/s]

 63%|██████▎   | 63093/100629 [49:39<32:41, 19.13it/s]

 63%|██████▎   | 63096/100629 [49:39<35:11, 17.78it/s]

 63%|██████▎   | 63098/100629 [49:39<36:00, 17.37it/s]

 63%|██████▎   | 63100/100629 [49:39<37:47, 16.55it/s]

 63%|██████▎   | 63103/100629 [49:39<32:32, 19.22it/s]

 63%|██████▎   | 63106/100629 [49:40<43:38, 14.33it/s]

 63%|██████▎   | 63108/100629 [49:40<41:41, 15.00it/s]

 63%|██████▎   | 63110/100629 [49:40<45:49, 13.64it/s]

 63%|██████▎   | 63115/100629 [49:40<32:10, 19.43it/s]

 63%|██████▎   | 63119/100629 [49:40<33:06, 18.88it/s]

 63%|██████▎   | 63122/100629 [49:40<30:46, 20.31it/s]

 63%|██████▎   | 63126/100629 [49:40<25:35, 24.42it/s]

 63%|██████▎   | 63129/100629 [49:41<27:57, 22.35it/s]

 63%|██████▎   | 63132/100629 [49:41<28:14, 22.12it/s]

 63%|██████▎   | 63135/100629 [49:41<34:18, 18.21it/s]

 63%|██████▎   | 63138/100629 [49:41<35:38, 17.53it/s]

 63%|██████▎   | 63140/100629 [49:41<35:40, 17.52it/s]

 63%|██████▎   | 63143/100629 [49:41<31:25, 19.88it/s]

 63%|██████▎   | 63146/100629 [49:42<32:43, 19.09it/s]

 63%|██████▎   | 63151/100629 [49:42<26:11, 23.85it/s]

 63%|██████▎   | 63154/100629 [49:42<29:13, 21.37it/s]

 63%|██████▎   | 63160/100629 [49:42<25:27, 24.53it/s]

 63%|██████▎   | 63163/100629 [49:42<26:00, 24.01it/s]

 63%|██████▎   | 63167/100629 [49:42<25:11, 24.78it/s]

 63%|██████▎   | 63170/100629 [49:43<25:54, 24.10it/s]

 63%|██████▎   | 63173/100629 [49:43<25:43, 24.27it/s]

 63%|██████▎   | 63176/100629 [49:43<25:04, 24.89it/s]

 63%|██████▎   | 63179/100629 [49:43<29:50, 20.91it/s]

 63%|██████▎   | 63182/100629 [49:43<30:04, 20.76it/s]

 63%|██████▎   | 63185/100629 [49:43<30:56, 20.16it/s]

 63%|██████▎   | 63188/100629 [49:44<38:58, 16.01it/s]

 63%|██████▎   | 63192/100629 [49:44<34:10, 18.26it/s]

 63%|██████▎   | 63195/100629 [49:44<33:23, 18.68it/s]

 63%|██████▎   | 63198/100629 [49:44<29:59, 20.80it/s]

 63%|██████▎   | 63201/100629 [49:44<32:07, 19.41it/s]

 63%|██████▎   | 63205/100629 [49:44<29:31, 21.12it/s]

 63%|██████▎   | 63209/100629 [49:44<28:21, 21.99it/s]

 63%|██████▎   | 63212/100629 [49:45<31:44, 19.65it/s]

 63%|██████▎   | 63215/100629 [49:45<30:29, 20.45it/s]

 63%|██████▎   | 63218/100629 [49:45<27:47, 22.44it/s]

 63%|██████▎   | 63221/100629 [49:45<27:37, 22.57it/s]

 63%|██████▎   | 63224/100629 [49:45<27:20, 22.80it/s]

 63%|██████▎   | 63227/100629 [49:45<30:29, 20.45it/s]

 63%|██████▎   | 63230/100629 [49:45<29:01, 21.48it/s]

 63%|██████▎   | 63234/100629 [49:46<26:49, 23.23it/s]

 63%|██████▎   | 63237/100629 [49:46<30:43, 20.28it/s]

 63%|██████▎   | 63240/100629 [49:46<32:04, 19.43it/s]

 63%|██████▎   | 63243/100629 [49:46<29:39, 21.01it/s]

 63%|██████▎   | 63246/100629 [49:46<30:10, 20.65it/s]

 63%|██████▎   | 63251/100629 [49:46<26:14, 23.73it/s]

 63%|██████▎   | 63254/100629 [49:47<26:36, 23.41it/s]

 63%|██████▎   | 63258/100629 [49:47<24:55, 24.99it/s]

 63%|██████▎   | 63262/100629 [49:47<23:45, 26.21it/s]

 63%|██████▎   | 63265/100629 [49:47<23:35, 26.39it/s]

 63%|██████▎   | 63268/100629 [49:47<25:38, 24.29it/s]

 63%|██████▎   | 63271/100629 [49:47<26:25, 23.57it/s]

 63%|██████▎   | 63275/100629 [49:47<24:18, 25.61it/s]

 63%|██████▎   | 63278/100629 [49:47<26:36, 23.39it/s]

 63%|██████▎   | 63283/100629 [49:48<21:06, 29.49it/s]

 63%|██████▎   | 63287/100629 [49:48<22:53, 27.19it/s]

 63%|██████▎   | 63290/100629 [49:48<25:18, 24.59it/s]

 63%|██████▎   | 63293/100629 [49:48<28:33, 21.79it/s]

 63%|██████▎   | 63296/100629 [49:48<31:32, 19.73it/s]

 63%|██████▎   | 63299/100629 [49:48<29:13, 21.29it/s]

 63%|██████▎   | 63302/100629 [49:49<28:37, 21.73it/s]

 63%|██████▎   | 63305/100629 [49:49<32:06, 19.38it/s]

 63%|██████▎   | 63308/100629 [49:49<31:13, 19.93it/s]

 63%|██████▎   | 63311/100629 [49:49<33:24, 18.61it/s]

 63%|██████▎   | 63314/100629 [49:49<30:03, 20.69it/s]

 63%|██████▎   | 63317/100629 [49:49<36:08, 17.21it/s]

 63%|██████▎   | 63322/100629 [49:50<27:24, 22.68it/s]

 63%|██████▎   | 63325/100629 [49:50<30:01, 20.71it/s]

 63%|██████▎   | 63328/100629 [49:50<27:57, 22.23it/s]

 63%|██████▎   | 63331/100629 [49:50<31:28, 19.75it/s]

 63%|██████▎   | 63335/100629 [49:50<28:30, 21.80it/s]

 63%|██████▎   | 63338/100629 [49:50<30:21, 20.47it/s]

 63%|██████▎   | 63341/100629 [49:51<33:01, 18.82it/s]

 63%|██████▎   | 63344/100629 [49:51<31:03, 20.00it/s]

 63%|██████▎   | 63347/100629 [49:51<28:30, 21.80it/s]

 63%|██████▎   | 63352/100629 [49:51<22:32, 27.56it/s]

 63%|██████▎   | 63355/100629 [49:51<23:26, 26.50it/s]

 63%|██████▎   | 63358/100629 [49:51<32:03, 19.37it/s]

 63%|██████▎   | 63362/100629 [49:51<31:57, 19.44it/s]

 63%|██████▎   | 63365/100629 [49:52<29:23, 21.14it/s]

 63%|██████▎   | 63368/100629 [49:52<28:44, 21.61it/s]

 63%|██████▎   | 63372/100629 [49:52<24:55, 24.91it/s]

 63%|██████▎   | 63375/100629 [49:52<26:09, 23.74it/s]

 63%|██████▎   | 63378/100629 [49:52<30:23, 20.43it/s]

 63%|██████▎   | 63381/100629 [49:52<32:13, 19.27it/s]

 63%|██████▎   | 63384/100629 [49:53<38:55, 15.95it/s]

 63%|██████▎   | 63387/100629 [49:53<34:52, 17.80it/s]

 63%|██████▎   | 63390/100629 [49:53<31:32, 19.68it/s]

 63%|██████▎   | 63393/100629 [49:53<32:46, 18.94it/s]

 63%|██████▎   | 63396/100629 [49:53<30:58, 20.03it/s]

 63%|██████▎   | 63399/100629 [49:53<31:25, 19.75it/s]

 63%|██████▎   | 63402/100629 [49:53<29:01, 21.38it/s]

 63%|██████▎   | 63405/100629 [49:54<30:22, 20.43it/s]

 63%|██████▎   | 63408/100629 [49:54<31:51, 19.47it/s]

 63%|██████▎   | 63411/100629 [49:54<32:03, 19.35it/s]

 63%|██████▎   | 63416/100629 [49:54<23:59, 25.85it/s]

 63%|██████▎   | 63419/100629 [49:54<29:31, 21.00it/s]

 63%|██████▎   | 63423/100629 [49:54<26:46, 23.16it/s]

 63%|██████▎   | 63426/100629 [49:55<32:53, 18.85it/s]

 63%|██████▎   | 63429/100629 [49:55<34:30, 17.96it/s]

 63%|██████▎   | 63431/100629 [49:55<37:08, 16.69it/s]

 63%|██████▎   | 63433/100629 [49:55<36:58, 16.76it/s]

 63%|██████▎   | 63436/100629 [49:55<34:47, 17.82it/s]

 63%|██████▎   | 63438/100629 [49:55<38:26, 16.13it/s]

 63%|██████▎   | 63442/100629 [49:56<33:35, 18.45it/s]

 63%|██████▎   | 63444/100629 [49:56<39:45, 15.59it/s]

 63%|██████▎   | 63446/100629 [49:56<40:40, 15.24it/s]

 63%|██████▎   | 63448/100629 [49:56<40:49, 15.18it/s]

 63%|██████▎   | 63452/100629 [49:56<31:26, 19.70it/s]

 63%|██████▎   | 63457/100629 [49:56<26:04, 23.76it/s]

 63%|██████▎   | 63460/100629 [49:56<28:20, 21.86it/s]

 63%|██████▎   | 63463/100629 [49:57<28:42, 21.57it/s]

 63%|██████▎   | 63469/100629 [49:57<21:33, 28.74it/s]

 63%|██████▎   | 63474/100629 [49:57<18:36, 33.28it/s]

 63%|██████▎   | 63478/100629 [49:57<22:44, 27.23it/s]

 63%|██████▎   | 63483/100629 [49:57<19:59, 30.96it/s]

 63%|██████▎   | 63487/100629 [49:57<19:50, 31.21it/s]

 63%|██████▎   | 63491/100629 [49:58<24:50, 24.91it/s]

 63%|██████▎   | 63495/100629 [49:58<23:45, 26.05it/s]

 63%|██████▎   | 63498/100629 [49:58<23:37, 26.19it/s]

 63%|██████▎   | 63501/100629 [49:58<27:41, 22.35it/s]

 63%|██████▎   | 63504/100629 [49:58<31:35, 19.59it/s]

 63%|██████▎   | 63507/100629 [49:58<31:35, 19.59it/s]

 63%|██████▎   | 63510/100629 [49:58<31:25, 19.69it/s]

 63%|██████▎   | 63513/100629 [49:59<31:51, 19.42it/s]

 63%|██████▎   | 63516/100629 [49:59<33:05, 18.70it/s]

 63%|██████▎   | 63518/100629 [49:59<33:31, 18.45it/s]

 63%|██████▎   | 63520/100629 [49:59<35:37, 17.36it/s]

 63%|██████▎   | 63523/100629 [49:59<33:12, 18.62it/s]

 63%|██████▎   | 63526/100629 [49:59<31:14, 19.79it/s]

 63%|██████▎   | 63528/100629 [49:59<33:11, 18.63it/s]

 63%|██████▎   | 63531/100629 [50:00<30:44, 20.11it/s]

 63%|██████▎   | 63534/100629 [50:00<28:26, 21.73it/s]

 63%|██████▎   | 63537/100629 [50:00<28:37, 21.60it/s]

 63%|██████▎   | 63540/100629 [50:00<27:01, 22.87it/s]

 63%|██████▎   | 63543/100629 [50:00<26:46, 23.09it/s]

 63%|██████▎   | 63546/100629 [50:00<30:26, 20.30it/s]

 63%|██████▎   | 63550/100629 [50:00<26:00, 23.76it/s]

 63%|██████▎   | 63553/100629 [50:01<29:23, 21.02it/s]

 63%|██████▎   | 63556/100629 [50:01<32:48, 18.83it/s]

 63%|██████▎   | 63559/100629 [50:01<32:08, 19.23it/s]

 63%|██████▎   | 63562/100629 [50:01<31:32, 19.59it/s]

 63%|██████▎   | 63565/100629 [50:01<32:39, 18.91it/s]

 63%|██████▎   | 63567/100629 [50:01<37:18, 16.55it/s]

 63%|██████▎   | 63570/100629 [50:02<33:52, 18.23it/s]

 63%|██████▎   | 63574/100629 [50:02<28:03, 22.01it/s]

 63%|██████▎   | 63577/100629 [50:02<30:40, 20.13it/s]

 63%|██████▎   | 63580/100629 [50:02<28:51, 21.39it/s]

 63%|██████▎   | 63583/100629 [50:02<27:11, 22.71it/s]

 63%|██████▎   | 63587/100629 [50:02<23:58, 25.75it/s]

 63%|██████▎   | 63591/100629 [50:02<21:07, 29.22it/s]

 63%|██████▎   | 63595/100629 [50:02<24:16, 25.43it/s]

 63%|██████▎   | 63598/100629 [50:03<23:19, 26.45it/s]

 63%|██████▎   | 63601/100629 [50:03<22:37, 27.27it/s]

 63%|██████▎   | 63604/100629 [50:03<23:04, 26.74it/s]

 63%|██████▎   | 63608/100629 [50:03<20:40, 29.84it/s]

 63%|██████▎   | 63612/100629 [50:03<23:22, 26.40it/s]

 63%|██████▎   | 63615/100629 [50:03<24:51, 24.82it/s]

 63%|██████▎   | 63618/100629 [50:03<25:41, 24.01it/s]

 63%|██████▎   | 63621/100629 [50:04<31:11, 19.77it/s]

 63%|██████▎   | 63624/100629 [50:04<31:06, 19.83it/s]

 63%|██████▎   | 63627/100629 [50:04<30:17, 20.35it/s]

 63%|██████▎   | 63630/100629 [50:04<28:47, 21.41it/s]

 63%|██████▎   | 63633/100629 [50:04<29:21, 21.01it/s]

 63%|██████▎   | 63637/100629 [50:04<28:54, 21.32it/s]

 63%|██████▎   | 63640/100629 [50:04<29:31, 20.88it/s]

 63%|██████▎   | 63643/100629 [50:05<30:01, 20.53it/s]

 63%|██████▎   | 63646/100629 [50:05<28:27, 21.66it/s]

 63%|██████▎   | 63650/100629 [50:05<26:27, 23.30it/s]

 63%|██████▎   | 63653/100629 [50:05<27:02, 22.79it/s]

 63%|██████▎   | 63656/100629 [50:05<26:20, 23.39it/s]

 63%|██████▎   | 63659/100629 [50:05<25:03, 24.58it/s]

 63%|██████▎   | 63663/100629 [50:05<22:09, 27.80it/s]

 63%|██████▎   | 63667/100629 [50:06<21:10, 29.09it/s]

 63%|██████▎   | 63670/100629 [50:06<22:31, 27.35it/s]

 63%|██████▎   | 63673/100629 [50:06<22:12, 27.74it/s]

 63%|██████▎   | 63676/100629 [50:06<22:59, 26.79it/s]

 63%|██████▎   | 63679/100629 [50:06<25:21, 24.28it/s]

 63%|██████▎   | 63682/100629 [50:06<26:22, 23.34it/s]

 63%|██████▎   | 63685/100629 [50:06<25:13, 24.41it/s]

 63%|██████▎   | 63688/100629 [50:06<27:22, 22.50it/s]

 63%|██████▎   | 63691/100629 [50:07<31:34, 19.50it/s]

 63%|██████▎   | 63694/100629 [50:07<31:33, 19.51it/s]

 63%|██████▎   | 63697/100629 [50:07<31:10, 19.75it/s]

 63%|██████▎   | 63700/100629 [50:07<32:03, 19.20it/s]

 63%|██████▎   | 63702/100629 [50:07<42:05, 14.62it/s]

 63%|██████▎   | 63704/100629 [50:07<42:20, 14.53it/s]

 63%|██████▎   | 63707/100629 [50:08<37:24, 16.45it/s]

 63%|██████▎   | 63709/100629 [50:08<38:49, 15.85it/s]

 63%|██████▎   | 63712/100629 [50:08<33:45, 18.23it/s]

 63%|██████▎   | 63714/100629 [50:08<34:09, 18.01it/s]

 63%|██████▎   | 63716/100629 [50:08<35:07, 17.52it/s]

 63%|██████▎   | 63718/100629 [50:08<37:11, 16.54it/s]

 63%|██████▎   | 63721/100629 [50:08<35:02, 17.55it/s]

 63%|██████▎   | 63723/100629 [50:09<35:08, 17.50it/s]

 63%|██████▎   | 63725/100629 [50:09<34:29, 17.84it/s]

 63%|██████▎   | 63727/100629 [50:09<35:55, 17.12it/s]

 63%|██████▎   | 63729/100629 [50:09<40:51, 15.05it/s]

 63%|██████▎   | 63732/100629 [50:09<38:22, 16.02it/s]

 63%|██████▎   | 63734/100629 [50:09<46:53, 13.11it/s]

 63%|██████▎   | 63736/100629 [50:09<42:56, 14.32it/s]

 63%|██████▎   | 63739/100629 [50:10<39:27, 15.58it/s]

 63%|██████▎   | 63741/100629 [50:10<39:25, 15.60it/s]

 63%|██████▎   | 63743/100629 [50:10<37:07, 16.56it/s]

 63%|██████▎   | 63745/100629 [50:10<42:29, 14.46it/s]

 63%|██████▎   | 63748/100629 [50:10<41:23, 14.85it/s]

 63%|██████▎   | 63750/100629 [50:10<38:57, 15.78it/s]

 63%|██████▎   | 63753/100629 [50:10<33:47, 18.19it/s]

 63%|██████▎   | 63755/100629 [50:11<36:06, 17.02it/s]

 63%|██████▎   | 63759/100629 [50:11<29:33, 20.79it/s]

 63%|██████▎   | 63762/100629 [50:11<28:37, 21.47it/s]

 63%|██████▎   | 63765/100629 [50:11<34:20, 17.89it/s]

 63%|██████▎   | 63769/100629 [50:11<30:50, 19.92it/s]

 63%|██████▎   | 63772/100629 [50:11<34:19, 17.90it/s]

 63%|██████▎   | 63774/100629 [50:12<35:09, 17.47it/s]

 63%|██████▎   | 63776/100629 [50:12<35:06, 17.50it/s]

 63%|██████▎   | 63780/100629 [50:12<31:54, 19.24it/s]

 63%|██████▎   | 63783/100629 [50:12<28:34, 21.49it/s]

 63%|██████▎   | 63786/100629 [50:12<29:57, 20.50it/s]

 63%|██████▎   | 63789/100629 [50:12<28:11, 21.78it/s]

 63%|██████▎   | 63792/100629 [50:12<32:09, 19.09it/s]

 63%|██████▎   | 63795/100629 [50:13<29:27, 20.84it/s]

 63%|██████▎   | 63798/100629 [50:13<31:08, 19.71it/s]

 63%|██████▎   | 63801/100629 [50:13<33:28, 18.33it/s]

 63%|██████▎   | 63805/100629 [50:13<26:56, 22.78it/s]

 63%|██████▎   | 63808/100629 [50:13<32:32, 18.86it/s]

 63%|██████▎   | 63813/100629 [50:13<24:32, 25.01it/s]

 63%|██████▎   | 63818/100629 [50:13<20:07, 30.48it/s]

 63%|██████▎   | 63822/100629 [50:14<21:32, 28.48it/s]

 63%|██████▎   | 63826/100629 [50:14<22:43, 26.99it/s]

 63%|██████▎   | 63829/100629 [50:14<22:55, 26.75it/s]

 63%|██████▎   | 63832/100629 [50:14<23:16, 26.35it/s]

 63%|██████▎   | 63835/100629 [50:14<23:35, 25.99it/s]

 63%|██████▎   | 63838/100629 [50:14<27:39, 22.17it/s]

 63%|██████▎   | 63841/100629 [50:14<26:01, 23.56it/s]

 63%|██████▎   | 63844/100629 [50:15<29:58, 20.45it/s]

 63%|██████▎   | 63847/100629 [50:15<31:55, 19.20it/s]

 63%|██████▎   | 63850/100629 [50:15<30:10, 20.32it/s]

 63%|██████▎   | 63853/100629 [50:15<35:14, 17.39it/s]

 63%|██████▎   | 63856/100629 [50:15<31:13, 19.63it/s]

 63%|██████▎   | 63859/100629 [50:15<30:08, 20.33it/s]

 63%|██████▎   | 63862/100629 [50:16<27:42, 22.12it/s]

 63%|██████▎   | 63865/100629 [50:16<27:37, 22.19it/s]

 63%|██████▎   | 63868/100629 [50:16<28:24, 21.57it/s]

 63%|██████▎   | 63872/100629 [50:16<24:02, 25.48it/s]

 63%|██████▎   | 63875/100629 [50:16<24:52, 24.63it/s]

 63%|██████▎   | 63878/100629 [50:16<23:51, 25.68it/s]

 63%|██████▎   | 63881/100629 [50:16<24:09, 25.36it/s]

 63%|██████▎   | 63884/100629 [50:16<27:59, 21.88it/s]

 63%|██████▎   | 63887/100629 [50:17<29:29, 20.77it/s]

 63%|██████▎   | 63890/100629 [50:17<27:50, 22.00it/s]

 63%|██████▎   | 63893/100629 [50:17<25:37, 23.89it/s]

 63%|██████▎   | 63896/100629 [50:17<27:52, 21.97it/s]

 64%|██████▎   | 63902/100629 [50:17<24:46, 24.71it/s]

 64%|██████▎   | 63906/100629 [50:17<22:25, 27.30it/s]

 64%|██████▎   | 63910/100629 [50:17<21:39, 28.25it/s]

 64%|██████▎   | 63914/100629 [50:18<22:31, 27.17it/s]

 64%|██████▎   | 63917/100629 [50:18<25:06, 24.37it/s]

 64%|██████▎   | 63920/100629 [50:18<26:20, 23.22it/s]

 64%|██████▎   | 63923/100629 [50:18<30:26, 20.09it/s]

 64%|██████▎   | 63926/100629 [50:18<34:42, 17.62it/s]

 64%|██████▎   | 63928/100629 [50:18<34:09, 17.90it/s]

 64%|██████▎   | 63932/100629 [50:19<29:03, 21.05it/s]

 64%|██████▎   | 63936/100629 [50:19<24:52, 24.59it/s]

 64%|██████▎   | 63939/100629 [50:19<27:06, 22.56it/s]

 64%|██████▎   | 63942/100629 [50:19<26:16, 23.27it/s]

 64%|██████▎   | 63946/100629 [50:19<23:57, 25.52it/s]

 64%|██████▎   | 63949/100629 [50:19<26:52, 22.75it/s]

 64%|██████▎   | 63952/100629 [50:19<25:32, 23.94it/s]

 64%|██████▎   | 63956/100629 [50:19<23:37, 25.88it/s]

 64%|██████▎   | 63959/100629 [50:20<22:58, 26.61it/s]

 64%|██████▎   | 63962/100629 [50:20<23:38, 25.85it/s]

 64%|██████▎   | 63965/100629 [50:20<25:34, 23.90it/s]

 64%|██████▎   | 63968/100629 [50:20<25:01, 24.41it/s]

 64%|██████▎   | 63971/100629 [50:20<24:06, 25.35it/s]

 64%|██████▎   | 63974/100629 [50:20<27:21, 22.33it/s]

 64%|██████▎   | 63977/100629 [50:20<27:16, 22.40it/s]

 64%|██████▎   | 63980/100629 [50:21<29:55, 20.41it/s]

 64%|██████▎   | 63983/100629 [50:21<32:26, 18.83it/s]

 64%|██████▎   | 63987/100629 [50:21<27:35, 22.14it/s]

 64%|██████▎   | 63990/100629 [50:21<26:27, 23.08it/s]

 64%|██████▎   | 63993/100629 [50:21<24:49, 24.60it/s]

 64%|██████▎   | 63996/100629 [50:21<24:02, 25.39it/s]

 64%|██████▎   | 63999/100629 [50:21<26:14, 23.27it/s]

 64%|██████▎   | 64003/100629 [50:21<22:46, 26.80it/s]

 64%|██████▎   | 64006/100629 [50:22<23:15, 26.24it/s]

 64%|██████▎   | 64009/100629 [50:22<23:41, 25.76it/s]

 64%|██████▎   | 64012/100629 [50:22<26:26, 23.08it/s]

 64%|██████▎   | 64015/100629 [50:22<33:20, 18.30it/s]

 64%|██████▎   | 64018/100629 [50:22<30:30, 20.01it/s]

 64%|██████▎   | 64022/100629 [50:22<26:57, 22.63it/s]

 64%|██████▎   | 64026/100629 [50:23<31:08, 19.59it/s]

 64%|██████▎   | 64030/100629 [50:23<30:29, 20.00it/s]

 64%|██████▎   | 64034/100629 [50:23<26:14, 23.24it/s]

 64%|██████▎   | 64037/100629 [50:23<26:11, 23.29it/s]

 64%|██████▎   | 64040/100629 [50:23<27:47, 21.94it/s]

 64%|██████▎   | 64043/100629 [50:23<27:29, 22.18it/s]

 64%|██████▎   | 64046/100629 [50:24<27:48, 21.92it/s]

 64%|██████▎   | 64049/100629 [50:24<32:47, 18.60it/s]

 64%|██████▎   | 64051/100629 [50:24<37:32, 16.24it/s]

 64%|██████▎   | 64054/100629 [50:24<33:27, 18.22it/s]

 64%|██████▎   | 64059/100629 [50:24<25:57, 23.48it/s]

 64%|██████▎   | 64062/100629 [50:24<27:25, 22.22it/s]

 64%|██████▎   | 64065/100629 [50:24<29:14, 20.84it/s]

 64%|██████▎   | 64069/100629 [50:25<25:12, 24.17it/s]

 64%|██████▎   | 64072/100629 [50:25<29:10, 20.89it/s]

 64%|██████▎   | 64075/100629 [50:25<31:24, 19.40it/s]

 64%|██████▎   | 64078/100629 [50:25<31:36, 19.27it/s]

 64%|██████▎   | 64081/100629 [50:25<32:05, 18.98it/s]

 64%|██████▎   | 64084/100629 [50:25<29:34, 20.59it/s]

 64%|██████▎   | 64087/100629 [50:26<36:00, 16.92it/s]

 64%|██████▎   | 64089/100629 [50:26<42:05, 14.47it/s]

 64%|██████▎   | 64091/100629 [50:26<43:53, 13.87it/s]

 64%|██████▎   | 64093/100629 [50:26<47:03, 12.94it/s]

 64%|██████▎   | 64095/100629 [50:26<44:23, 13.72it/s]

 64%|██████▎   | 64097/100629 [50:27<45:57, 13.25it/s]

 64%|██████▎   | 64100/100629 [50:27<39:32, 15.40it/s]

 64%|██████▎   | 64103/100629 [50:27<32:59, 18.45it/s]

 64%|██████▎   | 64106/100629 [50:27<32:46, 18.57it/s]

 64%|██████▎   | 64108/100629 [50:27<33:08, 18.37it/s]

 64%|██████▎   | 64111/100629 [50:27<30:08, 20.20it/s]

 64%|██████▎   | 64115/100629 [50:27<25:47, 23.59it/s]

 64%|██████▎   | 64118/100629 [50:28<33:34, 18.13it/s]

 64%|██████▎   | 64121/100629 [50:28<32:10, 18.91it/s]

 64%|██████▎   | 64124/100629 [50:28<32:57, 18.46it/s]

 64%|██████▎   | 64127/100629 [50:28<31:30, 19.31it/s]

 64%|██████▎   | 64130/100629 [50:28<29:06, 20.89it/s]

 64%|██████▎   | 64134/100629 [50:28<24:54, 24.43it/s]

 64%|██████▎   | 64137/100629 [50:28<24:10, 25.16it/s]

 64%|██████▎   | 64142/100629 [50:28<21:37, 28.12it/s]

 64%|██████▎   | 64145/100629 [50:29<24:07, 25.20it/s]

 64%|██████▎   | 64149/100629 [50:29<24:57, 24.35it/s]

 64%|██████▍   | 64152/100629 [50:29<26:25, 23.00it/s]

 64%|██████▍   | 64155/100629 [50:29<25:05, 24.23it/s]

 64%|██████▍   | 64158/100629 [50:29<30:28, 19.95it/s]

 64%|██████▍   | 64161/100629 [50:29<31:44, 19.15it/s]

 64%|██████▍   | 64164/100629 [50:30<34:14, 17.75it/s]

 64%|██████▍   | 64168/100629 [50:30<28:29, 21.32it/s]

 64%|██████▍   | 64171/100629 [50:30<28:31, 21.30it/s]

 64%|██████▍   | 64174/100629 [50:30<33:56, 17.90it/s]

 64%|██████▍   | 64176/100629 [50:30<35:43, 17.00it/s]

 64%|██████▍   | 64178/100629 [50:30<38:28, 15.79it/s]

 64%|██████▍   | 64181/100629 [50:31<35:21, 17.18it/s]

 64%|██████▍   | 64184/100629 [50:31<33:22, 18.20it/s]

 64%|██████▍   | 64188/100629 [50:31<28:03, 21.65it/s]

 64%|██████▍   | 64191/100629 [50:31<30:29, 19.92it/s]

 64%|██████▍   | 64194/100629 [50:31<29:20, 20.69it/s]

 64%|██████▍   | 64197/100629 [50:31<27:32, 22.05it/s]

 64%|██████▍   | 64200/100629 [50:31<27:18, 22.24it/s]

 64%|██████▍   | 64204/100629 [50:32<23:24, 25.94it/s]

 64%|██████▍   | 64207/100629 [50:32<26:51, 22.61it/s]

 64%|██████▍   | 64210/100629 [50:32<26:05, 23.27it/s]

 64%|██████▍   | 64214/100629 [50:32<23:05, 26.29it/s]

 64%|██████▍   | 64217/100629 [50:32<28:52, 21.02it/s]

 64%|██████▍   | 64220/100629 [50:32<26:48, 22.63it/s]

 64%|██████▍   | 64223/100629 [50:32<30:29, 19.89it/s]

 64%|██████▍   | 64226/100629 [50:33<31:23, 19.33it/s]

 64%|██████▍   | 64229/100629 [50:33<29:05, 20.85it/s]

 64%|██████▍   | 64232/100629 [50:33<31:13, 19.43it/s]

 64%|██████▍   | 64235/100629 [50:33<33:19, 18.20it/s]

 64%|██████▍   | 64237/100629 [50:33<32:50, 18.47it/s]

 64%|██████▍   | 64240/100629 [50:33<28:55, 20.97it/s]

 64%|██████▍   | 64243/100629 [50:33<27:05, 22.39it/s]

 64%|██████▍   | 64246/100629 [50:34<24:58, 24.27it/s]

 64%|██████▍   | 64250/100629 [50:34<23:52, 25.40it/s]

 64%|██████▍   | 64254/100629 [50:34<20:51, 29.07it/s]

 64%|██████▍   | 64258/100629 [50:34<24:08, 25.10it/s]

 64%|██████▍   | 64261/100629 [50:34<25:53, 23.41it/s]

 64%|██████▍   | 64264/100629 [50:34<28:15, 21.45it/s]

 64%|██████▍   | 64269/100629 [50:34<22:32, 26.89it/s]

 64%|██████▍   | 64275/100629 [50:35<17:58, 33.71it/s]

 64%|██████▍   | 64279/100629 [50:35<19:51, 30.51it/s]

 64%|██████▍   | 64283/100629 [50:35<24:10, 25.06it/s]

 64%|██████▍   | 64286/100629 [50:35<29:57, 20.22it/s]

 64%|██████▍   | 64289/100629 [50:35<30:53, 19.60it/s]

 64%|██████▍   | 64292/100629 [50:35<29:29, 20.54it/s]

 64%|██████▍   | 64295/100629 [50:36<33:44, 17.94it/s]

 64%|██████▍   | 64298/100629 [50:36<34:17, 17.66it/s]

 64%|██████▍   | 64301/100629 [50:36<32:11, 18.81it/s]

 64%|██████▍   | 64304/100629 [50:36<30:15, 20.00it/s]

 64%|██████▍   | 64307/100629 [50:36<29:36, 20.45it/s]

 64%|██████▍   | 64310/100629 [50:36<28:45, 21.04it/s]

 64%|██████▍   | 64313/100629 [50:37<31:08, 19.44it/s]

 64%|██████▍   | 64316/100629 [50:37<30:46, 19.67it/s]

 64%|██████▍   | 64319/100629 [50:37<32:43, 18.50it/s]

 64%|██████▍   | 64322/100629 [50:37<30:23, 19.91it/s]

 64%|██████▍   | 64325/100629 [50:37<28:12, 21.45it/s]

 64%|██████▍   | 64328/100629 [50:37<29:52, 20.25it/s]

 64%|██████▍   | 64331/100629 [50:37<29:18, 20.64it/s]

 64%|██████▍   | 64335/100629 [50:38<26:19, 22.97it/s]

 64%|██████▍   | 64338/100629 [50:38<30:53, 19.58it/s]

 64%|██████▍   | 64341/100629 [50:38<34:41, 17.43it/s]

 64%|██████▍   | 64343/100629 [50:38<38:16, 15.80it/s]

 64%|██████▍   | 64346/100629 [50:38<32:49, 18.42it/s]

 64%|██████▍   | 64351/100629 [50:38<25:49, 23.42it/s]

 64%|██████▍   | 64354/100629 [50:39<25:31, 23.69it/s]

 64%|██████▍   | 64358/100629 [50:39<22:48, 26.50it/s]

 64%|██████▍   | 64361/100629 [50:39<24:00, 25.18it/s]

 64%|██████▍   | 64364/100629 [50:39<26:23, 22.90it/s]

 64%|██████▍   | 64368/100629 [50:39<23:18, 25.92it/s]

 64%|██████▍   | 64371/100629 [50:39<24:27, 24.71it/s]

 64%|██████▍   | 64374/100629 [50:39<24:46, 24.39it/s]

 64%|██████▍   | 64378/100629 [50:39<22:07, 27.32it/s]

 64%|██████▍   | 64381/100629 [50:40<24:13, 24.94it/s]

 64%|██████▍   | 64384/100629 [50:40<28:06, 21.49it/s]

 64%|██████▍   | 64388/100629 [50:40<23:39, 25.53it/s]

 64%|██████▍   | 64392/100629 [50:40<20:50, 28.98it/s]

 64%|██████▍   | 64396/100629 [50:40<26:11, 23.06it/s]

 64%|██████▍   | 64400/100629 [50:40<24:07, 25.02it/s]

 64%|██████▍   | 64403/100629 [50:41<25:57, 23.25it/s]

 64%|██████▍   | 64407/100629 [50:41<23:58, 25.18it/s]

 64%|██████▍   | 64410/100629 [50:41<23:59, 25.16it/s]

 64%|██████▍   | 64413/100629 [50:41<26:04, 23.15it/s]

 64%|██████▍   | 64416/100629 [50:41<26:44, 22.57it/s]

 64%|██████▍   | 64419/100629 [50:41<25:02, 24.09it/s]

 64%|██████▍   | 64422/100629 [50:42<36:57, 16.33it/s]

 64%|██████▍   | 64425/100629 [50:42<37:44, 15.99it/s]

 64%|██████▍   | 64428/100629 [50:42<37:54, 15.92it/s]

 64%|██████▍   | 64430/100629 [50:42<39:44, 15.18it/s]

 64%|██████▍   | 64433/100629 [50:42<39:42, 15.19it/s]

 64%|██████▍   | 64436/100629 [50:42<35:06, 17.18it/s]

 64%|██████▍   | 64439/100629 [50:43<1:09:29,  8.68it/s]

 64%|██████▍   | 64443/100629 [50:43<49:52, 12.09it/s]

 64%|██████▍   | 64446/100629 [50:43<46:16, 13.03it/s]

 64%|██████▍   | 64448/100629 [50:44<43:24, 13.89it/s]

 64%|██████▍   | 64451/100629 [50:44<38:30, 15.66it/s]

 64%|██████▍   | 64454/100629 [50:44<35:22, 17.05it/s]

 64%|██████▍   | 64457/100629 [50:44<35:27, 17.00it/s]

 64%|██████▍   | 64460/100629 [50:44<31:24, 19.19it/s]

 64%|██████▍   | 64463/100629 [50:44<29:02, 20.75it/s]

 64%|██████▍   | 64466/100629 [50:44<26:58, 22.35it/s]

 64%|██████▍   | 64469/100629 [50:45<33:36, 17.93it/s]

 64%|██████▍   | 64472/100629 [50:45<36:20, 16.58it/s]

 64%|██████▍   | 64475/100629 [50:45<31:50, 18.93it/s]

 64%|██████▍   | 64478/100629 [50:45<31:23, 19.19it/s]

 64%|██████▍   | 64481/100629 [50:45<30:02, 20.05it/s]

 64%|██████▍   | 64484/100629 [50:45<29:25, 20.48it/s]

 64%|██████▍   | 64487/100629 [50:46<34:55, 17.24it/s]

 64%|██████▍   | 64493/100629 [50:46<24:45, 24.32it/s]

 64%|██████▍   | 64496/100629 [50:46<24:16, 24.82it/s]

 64%|██████▍   | 64499/100629 [50:46<25:18, 23.79it/s]

 64%|██████▍   | 64503/100629 [50:46<22:53, 26.30it/s]

 64%|██████▍   | 64506/100629 [50:46<24:22, 24.70it/s]

 64%|██████▍   | 64509/100629 [50:46<25:08, 23.94it/s]

 64%|██████▍   | 64514/100629 [50:46<21:34, 27.90it/s]

 64%|██████▍   | 64517/100629 [50:47<23:16, 25.86it/s]

 64%|██████▍   | 64521/100629 [50:47<21:42, 27.72it/s]

 64%|██████▍   | 64525/100629 [50:47<20:36, 29.20it/s]

 64%|██████▍   | 64530/100629 [50:47<17:45, 33.89it/s]

 64%|██████▍   | 64535/100629 [50:47<15:51, 37.92it/s]

 64%|██████▍   | 64539/100629 [50:47<23:18, 25.81it/s]

 64%|██████▍   | 64543/100629 [50:47<21:07, 28.47it/s]

 64%|██████▍   | 64547/100629 [50:48<23:26, 25.65it/s]

 64%|██████▍   | 64550/100629 [50:48<27:03, 22.23it/s]

 64%|██████▍   | 64553/100629 [50:48<29:10, 20.60it/s]

 64%|██████▍   | 64556/100629 [50:48<34:27, 17.45it/s]

 64%|██████▍   | 64559/100629 [50:48<31:32, 19.06it/s]

 64%|██████▍   | 64562/100629 [50:48<29:11, 20.60it/s]

 64%|██████▍   | 64565/100629 [50:49<30:51, 19.48it/s]

 64%|██████▍   | 64568/100629 [50:49<30:31, 19.69it/s]

 64%|██████▍   | 64571/100629 [50:49<27:30, 21.85it/s]

 64%|██████▍   | 64574/100629 [50:49<25:32, 23.52it/s]

 64%|██████▍   | 64577/100629 [50:49<24:48, 24.22it/s]

 64%|██████▍   | 64580/100629 [50:49<35:14, 17.05it/s]

 64%|██████▍   | 64583/100629 [50:50<31:00, 19.37it/s]

 64%|██████▍   | 64586/100629 [50:50<31:41, 18.95it/s]

 64%|██████▍   | 64589/100629 [50:50<30:45, 19.53it/s]

 64%|██████▍   | 64592/100629 [50:50<37:20, 16.08it/s]

 64%|██████▍   | 64597/100629 [50:50<28:17, 21.23it/s]

 64%|██████▍   | 64600/100629 [50:50<27:41, 21.69it/s]

 64%|██████▍   | 64604/100629 [50:50<23:31, 25.52it/s]

 64%|██████▍   | 64607/100629 [50:51<29:35, 20.28it/s]

 64%|██████▍   | 64610/100629 [50:51<30:05, 19.95it/s]

 64%|██████▍   | 64614/100629 [50:51<26:43, 22.45it/s]

 64%|██████▍   | 64617/100629 [50:51<25:58, 23.10it/s]

 64%|██████▍   | 64620/100629 [50:51<25:45, 23.29it/s]

 64%|██████▍   | 64623/100629 [50:51<25:01, 23.99it/s]

 64%|██████▍   | 64626/100629 [50:52<29:21, 20.44it/s]

 64%|██████▍   | 64629/100629 [50:52<27:27, 21.85it/s]

 64%|██████▍   | 64634/100629 [50:52<24:47, 24.20it/s]

 64%|██████▍   | 64637/100629 [50:52<26:41, 22.47it/s]

 64%|██████▍   | 64640/100629 [50:52<28:35, 20.97it/s]

 64%|██████▍   | 64643/100629 [50:52<27:04, 22.15it/s]

 64%|██████▍   | 64648/100629 [50:52<21:15, 28.20it/s]

 64%|██████▍   | 64652/100629 [50:53<24:56, 24.04it/s]

 64%|██████▍   | 64656/100629 [50:53<23:59, 24.99it/s]

 64%|██████▍   | 64659/100629 [50:53<24:46, 24.21it/s]

 64%|██████▍   | 64662/100629 [50:53<23:36, 25.39it/s]

 64%|██████▍   | 64665/100629 [50:53<29:40, 20.20it/s]

 64%|██████▍   | 64668/100629 [50:53<29:11, 20.53it/s]

 64%|██████▍   | 64672/100629 [50:54<27:17, 21.96it/s]

 64%|██████▍   | 64675/100629 [50:54<30:45, 19.48it/s]

 64%|██████▍   | 64680/100629 [50:54<28:04, 21.34it/s]

 64%|██████▍   | 64683/100629 [50:54<29:03, 20.61it/s]

 64%|██████▍   | 64686/100629 [50:54<29:52, 20.05it/s]

 64%|██████▍   | 64689/100629 [50:54<30:39, 19.54it/s]

 64%|██████▍   | 64691/100629 [50:55<31:41, 18.90it/s]

 64%|██████▍   | 64693/100629 [50:55<32:20, 18.52it/s]

 64%|██████▍   | 64697/100629 [50:55<28:15, 21.20it/s]

 64%|██████▍   | 64701/100629 [50:55<24:29, 24.45it/s]

 64%|██████▍   | 64704/100629 [50:55<23:18, 25.69it/s]

 64%|██████▍   | 64707/100629 [50:55<24:15, 24.69it/s]

 64%|██████▍   | 64710/100629 [50:55<24:11, 24.74it/s]

 64%|██████▍   | 64713/100629 [50:55<26:17, 22.77it/s]

 64%|██████▍   | 64716/100629 [50:56<30:31, 19.61it/s]

 64%|██████▍   | 64719/100629 [50:56<38:08, 15.69it/s]

 64%|██████▍   | 64722/100629 [50:56<34:50, 17.18it/s]

 64%|██████▍   | 64727/100629 [50:56<25:35, 23.38it/s]

 64%|██████▍   | 64730/100629 [50:56<29:09, 20.52it/s]

 64%|██████▍   | 64733/100629 [50:57<36:05, 16.57it/s]

 64%|██████▍   | 64736/100629 [50:57<34:45, 17.21it/s]

 64%|██████▍   | 64739/100629 [50:57<31:00, 19.29it/s]

 64%|██████▍   | 64743/100629 [50:57<27:59, 21.36it/s]

 64%|██████▍   | 64748/100629 [50:57<22:59, 26.01it/s]

 64%|██████▍   | 64751/100629 [50:57<23:45, 25.18it/s]

 64%|██████▍   | 64754/100629 [50:57<24:01, 24.89it/s]

 64%|██████▍   | 64757/100629 [50:58<26:14, 22.78it/s]

 64%|██████▍   | 64760/100629 [50:58<26:05, 22.92it/s]

 64%|██████▍   | 64763/100629 [50:58<27:06, 22.05it/s]

 64%|██████▍   | 64766/100629 [50:58<27:11, 21.98it/s]

 64%|██████▍   | 64769/100629 [50:58<25:54, 23.08it/s]

 64%|██████▍   | 64772/100629 [50:58<25:48, 23.16it/s]

 64%|██████▍   | 64775/100629 [50:58<24:56, 23.95it/s]

 64%|██████▍   | 64780/100629 [50:58<20:01, 29.83it/s]

 64%|██████▍   | 64784/100629 [50:59<24:57, 23.94it/s]

 64%|██████▍   | 64787/100629 [50:59<29:49, 20.03it/s]

 64%|██████▍   | 64790/100629 [50:59<30:09, 19.80it/s]

 64%|██████▍   | 64793/100629 [50:59<40:37, 14.70it/s]

 64%|██████▍   | 64796/100629 [51:00<37:28, 15.94it/s]

 64%|██████▍   | 64801/100629 [51:00<28:35, 20.89it/s]

 64%|██████▍   | 64804/100629 [51:00<27:10, 21.98it/s]

 64%|██████▍   | 64807/100629 [51:00<29:26, 20.28it/s]

 64%|██████▍   | 64810/100629 [51:00<30:33, 19.54it/s]

 64%|██████▍   | 64813/100629 [51:00<34:02, 17.54it/s]

 64%|██████▍   | 64815/100629 [51:00<36:02, 16.56it/s]

 64%|██████▍   | 64817/100629 [51:01<35:22, 16.87it/s]

 64%|██████▍   | 64820/100629 [51:01<30:15, 19.72it/s]

 64%|██████▍   | 64825/100629 [51:01<22:11, 26.89it/s]

 64%|██████▍   | 64828/100629 [51:01<24:06, 24.75it/s]

 64%|██████▍   | 64831/100629 [51:01<25:46, 23.14it/s]

 64%|██████▍   | 64834/100629 [51:01<25:16, 23.60it/s]

 64%|██████▍   | 64837/100629 [51:01<29:21, 20.32it/s]

 64%|██████▍   | 64840/100629 [51:02<29:00, 20.56it/s]

 64%|██████▍   | 64843/100629 [51:02<26:59, 22.10it/s]

 64%|██████▍   | 64846/100629 [51:02<24:55, 23.93it/s]

 64%|██████▍   | 64849/100629 [51:02<23:44, 25.12it/s]

 64%|██████▍   | 64854/100629 [51:02<21:05, 28.26it/s]

 64%|██████▍   | 64859/100629 [51:02<20:00, 29.79it/s]

 64%|██████▍   | 64862/100629 [51:02<21:23, 27.86it/s]

 64%|██████▍   | 64865/100629 [51:02<23:24, 25.46it/s]

 64%|██████▍   | 64868/100629 [51:03<23:32, 25.32it/s]

 64%|██████▍   | 64871/100629 [51:03<24:01, 24.80it/s]

 64%|██████▍   | 64875/100629 [51:03<21:42, 27.44it/s]

 64%|██████▍   | 64880/100629 [51:03<24:13, 24.60it/s]

 64%|██████▍   | 64883/100629 [51:03<29:26, 20.24it/s]

 64%|██████▍   | 64886/100629 [51:03<31:19, 19.02it/s]

 64%|██████▍   | 64889/100629 [51:04<29:14, 20.37it/s]

 64%|██████▍   | 64892/100629 [51:04<27:15, 21.84it/s]

 64%|██████▍   | 64895/100629 [51:04<27:57, 21.30it/s]

 64%|██████▍   | 64898/100629 [51:04<29:24, 20.25it/s]

 64%|██████▍   | 64901/100629 [51:04<27:06, 21.96it/s]

 64%|██████▍   | 64904/100629 [51:04<26:27, 22.50it/s]

 65%|██████▍   | 64907/100629 [51:04<25:48, 23.07it/s]

 65%|██████▍   | 64910/100629 [51:05<25:42, 23.16it/s]

 65%|██████▍   | 64913/100629 [51:05<25:09, 23.66it/s]

 65%|██████▍   | 64916/100629 [51:05<33:38, 17.69it/s]

 65%|██████▍   | 64919/100629 [51:05<33:18, 17.87it/s]

 65%|██████▍   | 64922/100629 [51:05<33:01, 18.02it/s]

 65%|██████▍   | 64924/100629 [51:05<32:53, 18.09it/s]

 65%|██████▍   | 64926/100629 [51:05<33:30, 17.76it/s]

 65%|██████▍   | 64929/100629 [51:06<30:23, 19.58it/s]

 65%|██████▍   | 64934/100629 [51:06<23:46, 25.02it/s]

 65%|██████▍   | 64937/100629 [51:06<24:55, 23.87it/s]

 65%|██████▍   | 64940/100629 [51:06<29:48, 19.95it/s]

 65%|██████▍   | 64943/100629 [51:06<27:58, 21.26it/s]

 65%|██████▍   | 64946/100629 [51:06<28:12, 21.08it/s]

 65%|██████▍   | 64949/100629 [51:07<31:59, 18.59it/s]

 65%|██████▍   | 64952/100629 [51:07<28:45, 20.68it/s]

 65%|██████▍   | 64955/100629 [51:07<29:12, 20.35it/s]

 65%|██████▍   | 64958/100629 [51:07<27:32, 21.59it/s]

 65%|██████▍   | 64962/100629 [51:07<24:46, 23.99it/s]

 65%|██████▍   | 64966/100629 [51:07<21:44, 27.33it/s]

 65%|██████▍   | 64970/100629 [51:07<22:09, 26.83it/s]

 65%|██████▍   | 64973/100629 [51:08<27:01, 22.00it/s]

 65%|██████▍   | 64976/100629 [51:08<25:34, 23.23it/s]

 65%|██████▍   | 64979/100629 [51:08<29:09, 20.37it/s]

 65%|██████▍   | 64982/100629 [51:08<30:53, 19.23it/s]

 65%|██████▍   | 64985/100629 [51:08<30:48, 19.28it/s]

 65%|██████▍   | 64988/100629 [51:08<28:12, 21.06it/s]

 65%|██████▍   | 64991/100629 [51:08<27:43, 21.43it/s]

 65%|██████▍   | 64994/100629 [51:09<27:46, 21.38it/s]

 65%|██████▍   | 64997/100629 [51:09<28:12, 21.06it/s]

 65%|██████▍   | 65000/100629 [51:09<26:40, 22.26it/s]

 65%|██████▍   | 65003/100629 [51:09<27:29, 21.59it/s]

 65%|██████▍   | 65006/100629 [51:09<26:18, 22.57it/s]

 65%|██████▍   | 65009/100629 [51:09<26:31, 22.38it/s]

 65%|██████▍   | 65013/100629 [51:09<26:35, 22.32it/s]

 65%|██████▍   | 65016/100629 [51:10<37:31, 15.82it/s]

 65%|██████▍   | 65018/100629 [51:10<36:24, 16.30it/s]

 65%|██████▍   | 65020/100629 [51:10<35:07, 16.90it/s]

 65%|██████▍   | 65022/100629 [51:10<35:07, 16.89it/s]

 65%|██████▍   | 65025/100629 [51:10<31:26, 18.87it/s]

 65%|██████▍   | 65027/100629 [51:10<33:19, 17.80it/s]

 65%|██████▍   | 65030/100629 [51:10<29:47, 19.92it/s]

 65%|██████▍   | 65033/100629 [51:11<27:51, 21.30it/s]

 65%|██████▍   | 65036/100629 [51:11<30:21, 19.54it/s]

 65%|██████▍   | 65039/100629 [51:11<32:31, 18.24it/s]

 65%|██████▍   | 65041/100629 [51:11<32:19, 18.35it/s]

 65%|██████▍   | 65044/100629 [51:11<28:44, 20.63it/s]

 65%|██████▍   | 65047/100629 [51:11<27:53, 21.26it/s]

 65%|██████▍   | 65050/100629 [51:11<26:12, 22.63it/s]

 65%|██████▍   | 65053/100629 [51:11<25:07, 23.60it/s]

 65%|██████▍   | 65058/100629 [51:12<20:52, 28.41it/s]

 65%|██████▍   | 65061/100629 [51:12<21:54, 27.05it/s]

 65%|██████▍   | 65065/100629 [51:12<20:06, 29.48it/s]

 65%|██████▍   | 65068/100629 [51:12<24:09, 24.54it/s]

 65%|██████▍   | 65072/100629 [51:12<21:01, 28.19it/s]

 65%|██████▍   | 65076/100629 [51:12<26:23, 22.45it/s]

 65%|██████▍   | 65079/100629 [51:13<30:44, 19.27it/s]

 65%|██████▍   | 65082/100629 [51:13<28:39, 20.67it/s]

 65%|██████▍   | 65085/100629 [51:13<30:30, 19.42it/s]

 65%|██████▍   | 65088/100629 [51:13<31:24, 18.86it/s]

 65%|██████▍   | 65091/100629 [51:13<29:31, 20.06it/s]

 65%|██████▍   | 65094/100629 [51:13<32:43, 18.10it/s]

 65%|██████▍   | 65098/100629 [51:14<29:51, 19.83it/s]

 65%|██████▍   | 65101/100629 [51:14<27:25, 21.59it/s]

 65%|██████▍   | 65104/100629 [51:14<37:45, 15.68it/s]

 65%|██████▍   | 65106/100629 [51:14<37:41, 15.71it/s]

 65%|██████▍   | 65108/100629 [51:14<38:06, 15.54it/s]

 65%|██████▍   | 65111/100629 [51:14<33:10, 17.84it/s]

 65%|██████▍   | 65114/100629 [51:15<33:02, 17.91it/s]

 65%|██████▍   | 65119/100629 [51:15<25:18, 23.39it/s]

 65%|██████▍   | 65122/100629 [51:15<33:16, 17.79it/s]

 65%|██████▍   | 65125/100629 [51:15<33:58, 17.42it/s]

 65%|██████▍   | 65129/100629 [51:15<29:26, 20.09it/s]

 65%|██████▍   | 65132/100629 [51:15<31:42, 18.65it/s]

 65%|██████▍   | 65135/100629 [51:16<28:29, 20.76it/s]

 65%|██████▍   | 65138/100629 [51:16<30:32, 19.37it/s]

 65%|██████▍   | 65141/100629 [51:16<30:46, 19.22it/s]

 65%|██████▍   | 65144/100629 [51:16<28:57, 20.42it/s]

 65%|██████▍   | 65147/100629 [51:16<30:38, 19.29it/s]

 65%|██████▍   | 65151/100629 [51:16<26:35, 22.24it/s]

 65%|██████▍   | 65154/100629 [51:17<28:51, 20.49it/s]

 65%|██████▍   | 65157/100629 [51:17<27:20, 21.62it/s]

 65%|██████▍   | 65160/100629 [51:17<28:52, 20.48it/s]

 65%|██████▍   | 65165/100629 [51:17<24:23, 24.23it/s]

 65%|██████▍   | 65168/100629 [51:17<24:59, 23.64it/s]

 65%|██████▍   | 65173/100629 [51:17<21:02, 28.08it/s]

 65%|██████▍   | 65176/100629 [51:17<20:57, 28.18it/s]

 65%|██████▍   | 65179/100629 [51:17<23:46, 24.86it/s]

 65%|██████▍   | 65182/100629 [51:18<24:55, 23.71it/s]

 65%|██████▍   | 65186/100629 [51:18<22:08, 26.68it/s]

 65%|██████▍   | 65189/100629 [51:18<22:50, 25.86it/s]

 65%|██████▍   | 65192/100629 [51:18<22:51, 25.83it/s]

 65%|██████▍   | 65195/100629 [51:18<22:03, 26.76it/s]

 65%|██████▍   | 65198/100629 [51:18<22:39, 26.07it/s]

 65%|██████▍   | 65201/100629 [51:18<30:05, 19.62it/s]

 65%|██████▍   | 65204/100629 [51:19<30:47, 19.17it/s]

 65%|██████▍   | 65207/100629 [51:19<30:50, 19.14it/s]

 65%|██████▍   | 65210/100629 [51:19<30:15, 19.51it/s]

 65%|██████▍   | 65213/100629 [51:19<28:18, 20.85it/s]

 65%|██████▍   | 65216/100629 [51:19<27:30, 21.46it/s]

 65%|██████▍   | 65219/100629 [51:19<25:36, 23.05it/s]

 65%|██████▍   | 65223/100629 [51:19<26:05, 22.61it/s]

 65%|██████▍   | 65227/100629 [51:20<23:17, 25.34it/s]

 65%|██████▍   | 65231/100629 [51:20<21:57, 26.87it/s]

 65%|██████▍   | 65235/100629 [51:20<21:25, 27.53it/s]

 65%|██████▍   | 65238/100629 [51:20<25:29, 23.14it/s]

 65%|██████▍   | 65241/100629 [51:20<27:57, 21.10it/s]

 65%|██████▍   | 65244/100629 [51:20<27:43, 21.27it/s]

 65%|██████▍   | 65247/100629 [51:20<26:46, 22.03it/s]

 65%|██████▍   | 65250/100629 [51:21<30:24, 19.39it/s]

 65%|██████▍   | 65253/100629 [51:21<27:34, 21.39it/s]

 65%|██████▍   | 65256/100629 [51:21<32:07, 18.35it/s]

 65%|██████▍   | 65259/100629 [51:21<30:33, 19.29it/s]

 65%|██████▍   | 65265/100629 [51:21<22:50, 25.80it/s]

 65%|██████▍   | 65268/100629 [51:22<29:27, 20.01it/s]

 65%|██████▍   | 65271/100629 [51:22<28:41, 20.54it/s]

 65%|██████▍   | 65274/100629 [51:22<30:54, 19.07it/s]

 65%|██████▍   | 65278/100629 [51:22<27:25, 21.48it/s]

 65%|██████▍   | 65281/100629 [51:22<26:45, 22.02it/s]

 65%|██████▍   | 65284/100629 [51:22<27:02, 21.79it/s]

 65%|██████▍   | 65288/100629 [51:22<25:05, 23.47it/s]

 65%|██████▍   | 65291/100629 [51:23<26:20, 22.35it/s]

 65%|██████▍   | 65294/100629 [51:23<26:49, 21.96it/s]

 65%|██████▍   | 65297/100629 [51:23<30:22, 19.39it/s]

 65%|██████▍   | 65300/100629 [51:23<28:34, 20.61it/s]

 65%|██████▍   | 65303/100629 [51:23<27:22, 21.51it/s]

 65%|██████▍   | 65306/100629 [51:23<29:35, 19.89it/s]

 65%|██████▍   | 65309/100629 [51:23<29:54, 19.68it/s]

 65%|██████▍   | 65312/100629 [51:24<31:33, 18.65it/s]

 65%|██████▍   | 65314/100629 [51:24<34:00, 17.31it/s]

 65%|██████▍   | 65317/100629 [51:24<31:06, 18.91it/s]

 65%|██████▍   | 65319/100629 [51:24<31:09, 18.89it/s]

 65%|██████▍   | 65322/100629 [51:24<30:16, 19.43it/s]

 65%|██████▍   | 65324/100629 [51:24<35:48, 16.43it/s]

 65%|██████▍   | 65327/100629 [51:24<30:58, 19.00it/s]

 65%|██████▍   | 65330/100629 [51:25<28:07, 20.92it/s]

 65%|██████▍   | 65335/100629 [51:25<22:56, 25.64it/s]

 65%|██████▍   | 65338/100629 [51:25<25:01, 23.50it/s]

 65%|██████▍   | 65341/100629 [51:25<26:09, 22.48it/s]

 65%|██████▍   | 65346/100629 [51:25<21:34, 27.25it/s]

 65%|██████▍   | 65349/100629 [51:25<26:25, 22.25it/s]

 65%|██████▍   | 65352/100629 [51:25<25:54, 22.69it/s]

 65%|██████▍   | 65356/100629 [51:26<22:46, 25.82it/s]

 65%|██████▍   | 65359/100629 [51:26<24:43, 23.77it/s]

 65%|██████▍   | 65362/100629 [51:26<23:45, 24.73it/s]

 65%|██████▍   | 65365/100629 [51:26<24:32, 23.94it/s]

 65%|██████▍   | 65369/100629 [51:26<21:15, 27.65it/s]

 65%|██████▍   | 65372/100629 [51:26<24:31, 23.96it/s]

 65%|██████▍   | 65375/100629 [51:26<24:40, 23.81it/s]

 65%|██████▍   | 65378/100629 [51:27<25:22, 23.15it/s]

 65%|██████▍   | 65382/100629 [51:27<22:39, 25.93it/s]

 65%|██████▍   | 65385/100629 [51:27<22:29, 26.12it/s]

 65%|██████▍   | 65388/100629 [51:27<26:07, 22.49it/s]

 65%|██████▍   | 65391/100629 [51:27<30:04, 19.53it/s]

 65%|██████▍   | 65395/100629 [51:27<26:26, 22.21it/s]

 65%|██████▍   | 65398/100629 [51:27<28:40, 20.48it/s]

 65%|██████▍   | 65401/100629 [51:28<29:33, 19.86it/s]

 65%|██████▍   | 65404/100629 [51:28<28:23, 20.68it/s]

 65%|██████▍   | 65407/100629 [51:28<27:46, 21.14it/s]

 65%|██████▌   | 65410/100629 [51:28<26:39, 22.01it/s]

 65%|██████▌   | 65413/100629 [51:28<24:46, 23.69it/s]

 65%|██████▌   | 65417/100629 [51:28<24:51, 23.61it/s]

 65%|██████▌   | 65420/100629 [51:28<26:04, 22.51it/s]

 65%|██████▌   | 65423/100629 [51:29<25:29, 23.02it/s]

 65%|██████▌   | 65426/100629 [51:29<30:14, 19.40it/s]

 65%|██████▌   | 65429/100629 [51:29<29:06, 20.16it/s]

 65%|██████▌   | 65432/100629 [51:29<34:54, 16.81it/s]

 65%|██████▌   | 65435/100629 [51:29<32:19, 18.15it/s]

 65%|██████▌   | 65440/100629 [51:29<27:47, 21.10it/s]

 65%|██████▌   | 65443/100629 [51:30<27:20, 21.45it/s]

 65%|██████▌   | 65446/100629 [51:30<29:29, 19.89it/s]

 65%|██████▌   | 65449/100629 [51:30<30:45, 19.06it/s]

 65%|██████▌   | 65451/100629 [51:30<31:15, 18.75it/s]

 65%|██████▌   | 65453/100629 [51:30<34:18, 17.09it/s]

 65%|██████▌   | 65458/100629 [51:30<25:42, 22.80it/s]

 65%|██████▌   | 65461/100629 [51:31<29:12, 20.06it/s]

 65%|██████▌   | 65464/100629 [51:31<35:56, 16.31it/s]

 65%|██████▌   | 65466/100629 [51:31<37:17, 15.72it/s]

 65%|██████▌   | 65468/100629 [51:31<37:00, 15.83it/s]

 65%|██████▌   | 65470/100629 [51:31<38:35, 15.18it/s]

 65%|██████▌   | 65472/100629 [51:31<40:19, 14.53it/s]

 65%|██████▌   | 65474/100629 [51:32<42:14, 13.87it/s]

 65%|██████▌   | 65478/100629 [51:32<32:09, 18.22it/s]

 65%|██████▌   | 65480/100629 [51:32<33:40, 17.39it/s]

 65%|██████▌   | 65482/100629 [51:32<34:08, 17.16it/s]

 65%|██████▌   | 65484/100629 [51:32<41:05, 14.26it/s]

 65%|██████▌   | 65486/100629 [51:32<38:53, 15.06it/s]

 65%|██████▌   | 65489/100629 [51:32<32:37, 17.95it/s]

 65%|██████▌   | 65492/100629 [51:32<28:51, 20.29it/s]

 65%|██████▌   | 65498/100629 [51:33<19:23, 30.19it/s]

 65%|██████▌   | 65503/100629 [51:33<17:16, 33.89it/s]

 65%|██████▌   | 65507/100629 [51:33<18:30, 31.62it/s]

 65%|██████▌   | 65512/100629 [51:33<17:45, 32.95it/s]

 65%|██████▌   | 65516/100629 [51:33<19:39, 29.76it/s]

 65%|██████▌   | 65520/100629 [51:33<22:08, 26.43it/s]

 65%|██████▌   | 65523/100629 [51:34<25:12, 23.21it/s]

 65%|██████▌   | 65526/100629 [51:34<23:57, 24.42it/s]

 65%|██████▌   | 65529/100629 [51:34<25:28, 22.97it/s]

 65%|██████▌   | 65533/100629 [51:34<25:35, 22.86it/s]

 65%|██████▌   | 65536/100629 [51:34<26:13, 22.30it/s]

 65%|██████▌   | 65539/100629 [51:34<24:36, 23.77it/s]

 65%|██████▌   | 65542/100629 [51:34<26:09, 22.35it/s]

 65%|██████▌   | 65545/100629 [51:35<27:42, 21.10it/s]

 65%|██████▌   | 65548/100629 [51:35<27:18, 21.41it/s]

 65%|██████▌   | 65551/100629 [51:35<29:33, 19.78it/s]

 65%|██████▌   | 65554/100629 [51:35<31:21, 18.65it/s]

 65%|██████▌   | 65557/100629 [51:35<30:48, 18.97it/s]

 65%|██████▌   | 65561/100629 [51:35<26:12, 22.30it/s]

 65%|██████▌   | 65565/100629 [51:35<22:27, 26.02it/s]

 65%|██████▌   | 65568/100629 [51:36<22:50, 25.59it/s]

 65%|██████▌   | 65571/100629 [51:36<29:48, 19.60it/s]

 65%|██████▌   | 65574/100629 [51:36<32:12, 18.14it/s]

 65%|██████▌   | 65577/100629 [51:36<29:30, 19.80it/s]

 65%|██████▌   | 65580/100629 [51:36<28:37, 20.40it/s]

 65%|██████▌   | 65583/100629 [51:36<30:21, 19.24it/s]

 65%|██████▌   | 65586/100629 [51:37<27:43, 21.06it/s]

 65%|██████▌   | 65591/100629 [51:37<22:40, 25.75it/s]

 65%|██████▌   | 65594/100629 [51:37<24:21, 23.97it/s]

 65%|██████▌   | 65597/100629 [51:37<27:48, 21.00it/s]

 65%|██████▌   | 65600/100629 [51:37<28:23, 20.57it/s]

 65%|██████▌   | 65603/100629 [51:37<30:07, 19.38it/s]

 65%|██████▌   | 65606/100629 [51:37<28:08, 20.75it/s]

 65%|██████▌   | 65609/100629 [51:38<26:05, 22.37it/s]

 65%|██████▌   | 65613/100629 [51:38<25:24, 22.97it/s]

 65%|██████▌   | 65616/100629 [51:38<23:58, 24.33it/s]

 65%|██████▌   | 65619/100629 [51:38<23:30, 24.82it/s]

 65%|██████▌   | 65622/100629 [51:38<24:02, 24.27it/s]

 65%|██████▌   | 65626/100629 [51:38<22:57, 25.41it/s]

 65%|██████▌   | 65629/100629 [51:38<26:55, 21.67it/s]

 65%|██████▌   | 65632/100629 [51:39<27:07, 21.50it/s]

 65%|██████▌   | 65635/100629 [51:39<29:21, 19.86it/s]

 65%|██████▌   | 65638/100629 [51:39<29:33, 19.74it/s]

 65%|██████▌   | 65641/100629 [51:39<32:06, 18.16it/s]

 65%|██████▌   | 65644/100629 [51:39<30:07, 19.36it/s]

 65%|██████▌   | 65646/100629 [51:39<32:26, 17.98it/s]

 65%|██████▌   | 65648/100629 [51:39<33:27, 17.42it/s]

 65%|██████▌   | 65652/100629 [51:40<26:26, 22.05it/s]

 65%|██████▌   | 65655/100629 [51:40<26:43, 21.81it/s]

 65%|██████▌   | 65659/100629 [51:40<23:52, 24.41it/s]

 65%|██████▌   | 65662/100629 [51:40<27:52, 20.91it/s]

 65%|██████▌   | 65665/100629 [51:40<27:26, 21.23it/s]

 65%|██████▌   | 65671/100629 [51:40<22:08, 26.32it/s]

 65%|██████▌   | 65674/100629 [51:40<22:25, 25.99it/s]

 65%|██████▌   | 65677/100629 [51:41<26:35, 21.90it/s]

 65%|██████▌   | 65680/100629 [51:41<26:01, 22.38it/s]

 65%|██████▌   | 65683/100629 [51:41<25:25, 22.91it/s]

 65%|██████▌   | 65686/100629 [51:41<24:26, 23.82it/s]

 65%|██████▌   | 65690/100629 [51:41<25:58, 22.42it/s]

 65%|██████▌   | 65693/100629 [51:41<25:26, 22.88it/s]

 65%|██████▌   | 65696/100629 [51:41<24:28, 23.79it/s]

 65%|██████▌   | 65699/100629 [51:42<26:12, 22.21it/s]

 65%|██████▌   | 65702/100629 [51:42<27:00, 21.55it/s]

 65%|██████▌   | 65705/100629 [51:42<28:48, 20.20it/s]

 65%|██████▌   | 65708/100629 [51:42<29:51, 19.49it/s]

 65%|██████▌   | 65710/100629 [51:42<30:15, 19.24it/s]

 65%|██████▌   | 65713/100629 [51:42<27:27, 21.19it/s]

 65%|██████▌   | 65716/100629 [51:42<27:52, 20.88it/s]

 65%|██████▌   | 65719/100629 [51:43<25:31, 22.80it/s]

 65%|██████▌   | 65724/100629 [51:43<20:30, 28.37it/s]

 65%|██████▌   | 65727/100629 [51:43<20:44, 28.05it/s]

 65%|██████▌   | 65730/100629 [51:43<23:36, 24.64it/s]

 65%|██████▌   | 65734/100629 [51:43<21:00, 27.69it/s]

 65%|██████▌   | 65737/100629 [51:43<29:33, 19.67it/s]

 65%|██████▌   | 65740/100629 [51:43<27:23, 21.23it/s]

 65%|██████▌   | 65743/100629 [51:44<27:09, 21.41it/s]

 65%|██████▌   | 65746/100629 [51:44<33:12, 17.51it/s]

 65%|██████▌   | 65750/100629 [51:44<27:22, 21.23it/s]

 65%|██████▌   | 65753/100629 [51:44<27:15, 21.33it/s]

 65%|██████▌   | 65756/100629 [51:44<26:36, 21.85it/s]

 65%|██████▌   | 65759/100629 [51:44<28:00, 20.75it/s]

 65%|██████▌   | 65764/100629 [51:44<21:33, 26.96it/s]

 65%|██████▌   | 65767/100629 [51:45<26:03, 22.30it/s]

 65%|██████▌   | 65770/100629 [51:45<25:04, 23.18it/s]

 65%|██████▌   | 65773/100629 [51:45<25:31, 22.75it/s]

 65%|██████▌   | 65776/100629 [51:45<25:34, 22.71it/s]

 65%|██████▌   | 65779/100629 [51:45<31:11, 18.62it/s]

 65%|██████▌   | 65782/100629 [51:45<27:53, 20.82it/s]

 65%|██████▌   | 65785/100629 [51:46<33:36, 17.28it/s]

 65%|██████▌   | 65789/100629 [51:46<28:40, 20.25it/s]

 65%|██████▌   | 65792/100629 [51:46<30:32, 19.01it/s]

 65%|██████▌   | 65796/100629 [51:46<26:13, 22.14it/s]

 65%|██████▌   | 65799/100629 [51:46<27:08, 21.39it/s]

 65%|██████▌   | 65802/100629 [51:46<25:05, 23.14it/s]

 65%|██████▌   | 65805/100629 [51:47<27:16, 21.28it/s]

 65%|██████▌   | 65808/100629 [51:47<28:01, 20.70it/s]

 65%|██████▌   | 65811/100629 [51:47<27:00, 21.49it/s]

 65%|██████▌   | 65814/100629 [51:47<33:15, 17.45it/s]

 65%|██████▌   | 65816/100629 [51:47<36:15, 16.00it/s]

 65%|██████▌   | 65818/100629 [51:47<37:08, 15.62it/s]

 65%|██████▌   | 65820/100629 [51:47<36:14, 16.01it/s]

 65%|██████▌   | 65823/100629 [51:48<30:56, 18.75it/s]

 65%|██████▌   | 65826/100629 [51:48<31:14, 18.57it/s]

 65%|██████▌   | 65829/100629 [51:48<27:47, 20.87it/s]

 65%|██████▌   | 65832/100629 [51:48<26:44, 21.69it/s]

 65%|██████▌   | 65837/100629 [51:48<20:18, 28.55it/s]

 65%|██████▌   | 65841/100629 [51:48<22:01, 26.32it/s]

 65%|██████▌   | 65844/100629 [51:48<22:59, 25.22it/s]

 65%|██████▌   | 65847/100629 [51:49<25:07, 23.07it/s]

 65%|██████▌   | 65850/100629 [51:49<28:05, 20.63it/s]

 65%|██████▌   | 65854/100629 [51:49<24:30, 23.65it/s]

 65%|██████▌   | 65857/100629 [51:49<28:46, 20.14it/s]

 65%|██████▌   | 65860/100629 [51:49<26:23, 21.96it/s]

 65%|██████▌   | 65863/100629 [51:49<27:56, 20.74it/s]

 65%|██████▌   | 65866/100629 [51:50<31:22, 18.46it/s]

 65%|██████▌   | 65868/100629 [51:50<32:02, 18.08it/s]

 65%|██████▌   | 65871/100629 [51:50<28:21, 20.43it/s]

 65%|██████▌   | 65874/100629 [51:50<26:38, 21.74it/s]

 65%|██████▌   | 65877/100629 [51:50<26:45, 21.65it/s]

 65%|██████▌   | 65880/100629 [51:50<29:36, 19.56it/s]

 65%|██████▌   | 65884/100629 [51:50<25:17, 22.90it/s]

 65%|██████▌   | 65887/100629 [51:50<24:48, 23.34it/s]

 65%|██████▌   | 65890/100629 [51:51<26:59, 21.45it/s]

 65%|██████▌   | 65893/100629 [51:51<29:21, 19.72it/s]

 65%|██████▌   | 65896/100629 [51:51<28:50, 20.07it/s]

 65%|██████▌   | 65900/100629 [51:51<24:59, 23.15it/s]

 65%|██████▌   | 65903/100629 [51:51<24:46, 23.35it/s]

 65%|██████▌   | 65906/100629 [51:51<24:34, 23.55it/s]

 65%|██████▌   | 65909/100629 [51:51<27:02, 21.40it/s]

 66%|██████▌   | 65912/100629 [51:52<25:20, 22.83it/s]

 66%|██████▌   | 65916/100629 [51:52<22:27, 25.76it/s]

 66%|██████▌   | 65919/100629 [51:52<25:37, 22.57it/s]

 66%|██████▌   | 65923/100629 [51:52<24:52, 23.26it/s]

 66%|██████▌   | 65926/100629 [51:52<28:14, 20.49it/s]

 66%|██████▌   | 65929/100629 [51:52<28:34, 20.24it/s]

 66%|██████▌   | 65933/100629 [51:53<25:52, 22.35it/s]

 66%|██████▌   | 65937/100629 [51:53<24:01, 24.06it/s]

 66%|██████▌   | 65940/100629 [51:53<27:35, 20.96it/s]

 66%|██████▌   | 65943/100629 [51:53<30:37, 18.88it/s]

 66%|██████▌   | 65946/100629 [51:53<27:31, 21.00it/s]

 66%|██████▌   | 65949/100629 [51:53<25:41, 22.49it/s]

 66%|██████▌   | 65952/100629 [51:53<25:32, 22.63it/s]

 66%|██████▌   | 65955/100629 [51:54<31:27, 18.37it/s]

 66%|██████▌   | 65958/100629 [51:54<33:50, 17.08it/s]

 66%|██████▌   | 65962/100629 [51:54<28:11, 20.49it/s]

 66%|██████▌   | 65966/100629 [51:54<24:59, 23.11it/s]

 66%|██████▌   | 65969/100629 [51:54<29:02, 19.89it/s]

 66%|██████▌   | 65972/100629 [51:55<30:43, 18.80it/s]

 66%|██████▌   | 65975/100629 [51:55<29:25, 19.63it/s]

 66%|██████▌   | 65978/100629 [51:55<27:12, 21.23it/s]

 66%|██████▌   | 65981/100629 [51:55<28:27, 20.29it/s]

 66%|██████▌   | 65984/100629 [51:55<26:39, 21.66it/s]

 66%|██████▌   | 65987/100629 [51:55<30:04, 19.19it/s]

 66%|██████▌   | 65990/100629 [51:55<27:31, 20.97it/s]

 66%|██████▌   | 65994/100629 [51:55<24:29, 23.57it/s]

 66%|██████▌   | 65997/100629 [51:56<23:49, 24.23it/s]

 66%|██████▌   | 66001/100629 [51:56<22:22, 25.80it/s]

 66%|██████▌   | 66005/100629 [51:56<21:16, 27.13it/s]

 66%|██████▌   | 66008/100629 [51:56<23:40, 24.37it/s]

 66%|██████▌   | 66014/100629 [51:56<19:43, 29.24it/s]

 66%|██████▌   | 66017/100629 [51:56<21:58, 26.24it/s]

 66%|██████▌   | 66020/100629 [51:56<21:28, 26.87it/s]

 66%|██████▌   | 66023/100629 [51:57<21:50, 26.40it/s]

 66%|██████▌   | 66027/100629 [51:57<21:15, 27.13it/s]

 66%|██████▌   | 66030/100629 [51:57<21:50, 26.41it/s]

 66%|██████▌   | 66034/100629 [51:57<19:59, 28.85it/s]

 66%|██████▌   | 66040/100629 [51:57<17:01, 33.86it/s]

 66%|██████▌   | 66044/100629 [51:57<19:22, 29.74it/s]

 66%|██████▌   | 66048/100629 [51:58<24:26, 23.58it/s]

 66%|██████▌   | 66051/100629 [51:58<23:46, 24.23it/s]

 66%|██████▌   | 66054/100629 [51:58<23:19, 24.71it/s]

 66%|██████▌   | 66058/100629 [51:58<22:37, 25.47it/s]

 66%|██████▌   | 66061/100629 [51:58<25:57, 22.19it/s]

 66%|██████▌   | 66064/100629 [51:58<26:00, 22.16it/s]

 66%|██████▌   | 66067/100629 [51:58<27:41, 20.80it/s]

 66%|██████▌   | 66070/100629 [51:58<26:47, 21.50it/s]

 66%|██████▌   | 66073/100629 [51:59<28:04, 20.51it/s]

 66%|██████▌   | 66076/100629 [51:59<28:18, 20.35it/s]

 66%|██████▌   | 66079/100629 [51:59<30:14, 19.04it/s]

 66%|██████▌   | 66083/100629 [51:59<27:27, 20.97it/s]

 66%|██████▌   | 66086/100629 [51:59<27:49, 20.69it/s]

 66%|██████▌   | 66089/100629 [51:59<27:23, 21.01it/s]

 66%|██████▌   | 66092/100629 [52:00<26:28, 21.74it/s]

 66%|██████▌   | 66095/100629 [52:00<30:26, 18.90it/s]

 66%|██████▌   | 66100/100629 [52:00<26:10, 21.98it/s]

 66%|██████▌   | 66103/100629 [52:00<27:58, 20.57it/s]

 66%|██████▌   | 66106/100629 [52:00<34:37, 16.62it/s]

 66%|██████▌   | 66109/100629 [52:00<30:32, 18.84it/s]

 66%|██████▌   | 66112/100629 [52:01<30:00, 19.17it/s]

 66%|██████▌   | 66117/100629 [52:01<24:24, 23.56it/s]

 66%|██████▌   | 66120/100629 [52:01<25:17, 22.75it/s]

 66%|██████▌   | 66124/100629 [52:01<22:18, 25.79it/s]

 66%|██████▌   | 66127/100629 [52:01<27:18, 21.05it/s]

 66%|██████▌   | 66131/100629 [52:01<25:14, 22.78it/s]

 66%|██████▌   | 66134/100629 [52:02<27:17, 21.06it/s]

 66%|██████▌   | 66137/100629 [52:02<26:09, 21.97it/s]

 66%|██████▌   | 66140/100629 [52:02<31:17, 18.37it/s]

 66%|██████▌   | 66143/100629 [52:02<31:46, 18.09it/s]

 66%|██████▌   | 66145/100629 [52:02<34:25, 16.69it/s]

 66%|██████▌   | 66147/100629 [52:02<33:19, 17.24it/s]

 66%|██████▌   | 66150/100629 [52:02<28:53, 19.89it/s]

 66%|██████▌   | 66153/100629 [52:03<39:02, 14.72it/s]

 66%|██████▌   | 66156/100629 [52:03<33:09, 17.32it/s]

 66%|██████▌   | 66159/100629 [52:03<34:00, 16.89it/s]

 66%|██████▌   | 66161/100629 [52:03<34:30, 16.65it/s]

 66%|██████▌   | 66163/100629 [52:03<34:38, 16.58it/s]

 66%|██████▌   | 66165/100629 [52:03<34:56, 16.44it/s]

 66%|██████▌   | 66168/100629 [52:04<30:17, 18.96it/s]

 66%|██████▌   | 66171/100629 [52:04<28:24, 20.22it/s]

 66%|██████▌   | 66174/100629 [52:04<30:40, 18.72it/s]

 66%|██████▌   | 66176/100629 [52:04<32:10, 17.85it/s]

 66%|██████▌   | 66178/100629 [52:04<33:11, 17.30it/s]

 66%|██████▌   | 66182/100629 [52:04<27:18, 21.02it/s]

 66%|██████▌   | 66185/100629 [52:04<29:53, 19.20it/s]

 66%|██████▌   | 66188/100629 [52:05<27:40, 20.74it/s]

 66%|██████▌   | 66194/100629 [52:05<19:23, 29.60it/s]

 66%|██████▌   | 66198/100629 [52:05<26:58, 21.28it/s]

 66%|██████▌   | 66201/100629 [52:05<28:36, 20.06it/s]

 66%|██████▌   | 66204/100629 [52:05<29:33, 19.41it/s]

 66%|██████▌   | 66207/100629 [52:05<29:18, 19.57it/s]

 66%|██████▌   | 66211/100629 [52:06<25:28, 22.52it/s]

 66%|██████▌   | 66215/100629 [52:06<23:26, 24.47it/s]

 66%|██████▌   | 66218/100629 [52:06<26:38, 21.53it/s]

 66%|██████▌   | 66221/100629 [52:06<35:14, 16.27it/s]

 66%|██████▌   | 66224/100629 [52:06<32:34, 17.60it/s]

 66%|██████▌   | 66227/100629 [52:06<29:36, 19.36it/s]

 66%|██████▌   | 66230/100629 [52:07<29:23, 19.51it/s]

 66%|██████▌   | 66233/100629 [52:07<30:49, 18.59it/s]

 66%|██████▌   | 66235/100629 [52:07<31:09, 18.39it/s]

 66%|██████▌   | 66238/100629 [52:07<31:25, 18.24it/s]

 66%|██████▌   | 66242/100629 [52:07<27:56, 20.51it/s]

 66%|██████▌   | 66245/100629 [52:07<26:47, 21.39it/s]

 66%|██████▌   | 66248/100629 [52:07<26:09, 21.91it/s]

 66%|██████▌   | 66251/100629 [52:08<28:17, 20.25it/s]

 66%|██████▌   | 66254/100629 [52:08<31:37, 18.12it/s]

 66%|██████▌   | 66257/100629 [52:08<28:10, 20.33it/s]

 66%|██████▌   | 66260/100629 [52:08<28:03, 20.42it/s]

 66%|██████▌   | 66264/100629 [52:08<25:07, 22.80it/s]

 66%|██████▌   | 66267/100629 [52:08<25:27, 22.49it/s]

 66%|██████▌   | 66270/100629 [52:09<24:56, 22.96it/s]

 66%|██████▌   | 66273/100629 [52:09<30:22, 18.86it/s]

 66%|██████▌   | 66276/100629 [52:09<28:42, 19.94it/s]

 66%|██████▌   | 66279/100629 [52:09<28:34, 20.03it/s]

 66%|██████▌   | 66282/100629 [52:09<27:19, 20.94it/s]

 66%|██████▌   | 66285/100629 [52:09<28:51, 19.84it/s]

 66%|██████▌   | 66288/100629 [52:09<27:47, 20.60it/s]

 66%|██████▌   | 66291/100629 [52:10<33:41, 16.99it/s]

 66%|██████▌   | 66294/100629 [52:10<32:09, 17.79it/s]

 66%|██████▌   | 66297/100629 [52:10<31:21, 18.25it/s]

 66%|██████▌   | 66299/100629 [52:10<36:25, 15.70it/s]

 66%|██████▌   | 66302/100629 [52:10<35:52, 15.95it/s]

 66%|██████▌   | 66304/100629 [52:11<39:47, 14.37it/s]

 66%|██████▌   | 66307/100629 [52:11<37:43, 15.16it/s]

 66%|██████▌   | 66310/100629 [52:11<31:58, 17.89it/s]

 66%|██████▌   | 66313/100629 [52:11<28:24, 20.14it/s]

 66%|██████▌   | 66317/100629 [52:11<23:10, 24.67it/s]

 66%|██████▌   | 66320/100629 [52:11<27:12, 21.02it/s]

 66%|██████▌   | 66323/100629 [52:11<29:39, 19.28it/s]

 66%|██████▌   | 66327/100629 [52:12<28:14, 20.24it/s]

 66%|██████▌   | 66331/100629 [52:12<24:50, 23.01it/s]

 66%|██████▌   | 66335/100629 [52:12<22:40, 25.21it/s]

 66%|██████▌   | 66338/100629 [52:12<21:45, 26.27it/s]

 66%|██████▌   | 66342/100629 [52:12<19:37, 29.11it/s]

 66%|██████▌   | 66346/100629 [52:12<22:50, 25.02it/s]

 66%|██████▌   | 66349/100629 [52:12<22:56, 24.91it/s]

 66%|██████▌   | 66352/100629 [52:13<21:55, 26.05it/s]

 66%|██████▌   | 66355/100629 [52:13<22:58, 24.87it/s]

 66%|██████▌   | 66358/100629 [52:13<24:12, 23.59it/s]

 66%|██████▌   | 66361/100629 [52:13<23:46, 24.02it/s]

 66%|██████▌   | 66365/100629 [52:13<23:28, 24.32it/s]

 66%|██████▌   | 66368/100629 [52:13<24:23, 23.42it/s]

 66%|██████▌   | 66371/100629 [52:13<25:32, 22.35it/s]

 66%|██████▌   | 66374/100629 [52:14<26:57, 21.18it/s]

 66%|██████▌   | 66377/100629 [52:14<25:53, 22.05it/s]

 66%|██████▌   | 66380/100629 [52:14<29:00, 19.68it/s]

 66%|██████▌   | 66384/100629 [52:14<26:44, 21.35it/s]

 66%|██████▌   | 66387/100629 [52:14<37:06, 15.38it/s]

 66%|██████▌   | 66389/100629 [52:14<36:04, 15.82it/s]

 66%|██████▌   | 66392/100629 [52:15<32:31, 17.55it/s]

 66%|██████▌   | 66395/100629 [52:15<30:39, 18.61it/s]

 66%|██████▌   | 66398/100629 [52:15<35:51, 15.91it/s]

 66%|██████▌   | 66402/100629 [52:15<29:58, 19.03it/s]

 66%|██████▌   | 66405/100629 [52:15<32:04, 17.78it/s]

 66%|██████▌   | 66409/100629 [52:15<27:09, 21.00it/s]

 66%|██████▌   | 66412/100629 [52:16<28:54, 19.73it/s]

 66%|██████▌   | 66415/100629 [52:16<26:25, 21.58it/s]

 66%|██████▌   | 66419/100629 [52:16<23:11, 24.59it/s]

 66%|██████▌   | 66422/100629 [52:16<24:51, 22.94it/s]

 66%|██████▌   | 66425/100629 [52:16<30:38, 18.60it/s]

 66%|██████▌   | 66428/100629 [52:16<29:45, 19.15it/s]

 66%|██████▌   | 66432/100629 [52:16<25:08, 22.68it/s]

 66%|██████▌   | 66435/100629 [52:17<26:11, 21.76it/s]

 66%|██████▌   | 66438/100629 [52:17<30:01, 18.98it/s]

 66%|██████▌   | 66442/100629 [52:17<25:20, 22.48it/s]

 66%|██████▌   | 66445/100629 [52:17<26:38, 21.38it/s]

 66%|██████▌   | 66448/100629 [52:17<25:08, 22.66it/s]

 66%|██████▌   | 66451/100629 [52:17<25:10, 22.63it/s]

 66%|██████▌   | 66454/100629 [52:18<26:43, 21.31it/s]

 66%|██████▌   | 66457/100629 [52:18<27:45, 20.52it/s]

 66%|██████▌   | 66460/100629 [52:18<26:07, 21.79it/s]

 66%|██████▌   | 66463/100629 [52:18<24:34, 23.17it/s]

 66%|██████▌   | 66466/100629 [52:18<27:38, 20.60it/s]

 66%|██████▌   | 66470/100629 [52:18<23:04, 24.67it/s]

 66%|██████▌   | 66473/100629 [52:18<22:18, 25.51it/s]

 66%|██████▌   | 66476/100629 [52:18<22:44, 25.03it/s]

 66%|██████▌   | 66479/100629 [52:19<23:23, 24.34it/s]

 66%|██████▌   | 66483/100629 [52:19<20:28, 27.80it/s]

 66%|██████▌   | 66486/100629 [52:19<25:03, 22.70it/s]

 66%|██████▌   | 66490/100629 [52:19<22:18, 25.50it/s]

 66%|██████▌   | 66493/100629 [52:19<23:17, 24.43it/s]

 66%|██████▌   | 66497/100629 [52:19<22:49, 24.92it/s]

 66%|██████▌   | 66500/100629 [52:19<22:21, 25.45it/s]

 66%|██████▌   | 66504/100629 [52:20<19:43, 28.83it/s]

 66%|██████▌   | 66508/100629 [52:20<19:48, 28.71it/s]

 66%|██████▌   | 66511/100629 [52:20<20:31, 27.69it/s]

 66%|██████▌   | 66514/100629 [52:20<21:23, 26.57it/s]

 66%|██████▌   | 66518/100629 [52:20<20:59, 27.09it/s]

 66%|██████▌   | 66522/100629 [52:20<20:23, 27.89it/s]

 66%|██████▌   | 66525/100629 [52:20<22:02, 25.78it/s]

 66%|██████▌   | 66529/100629 [52:20<19:37, 28.97it/s]

 66%|██████▌   | 66533/100629 [52:21<20:37, 27.55it/s]

 66%|██████▌   | 66536/100629 [52:21<22:21, 25.42it/s]

 66%|██████▌   | 66539/100629 [52:21<22:29, 25.26it/s]

 66%|██████▌   | 66542/100629 [52:21<21:37, 26.28it/s]

 66%|██████▌   | 66545/100629 [52:21<23:01, 24.67it/s]

 66%|██████▌   | 66548/100629 [52:21<28:56, 19.63it/s]

 66%|██████▌   | 66553/100629 [52:21<23:44, 23.92it/s]

 66%|██████▌   | 66556/100629 [52:22<24:26, 23.23it/s]

 66%|██████▌   | 66559/100629 [52:22<24:32, 23.14it/s]

 66%|██████▌   | 66562/100629 [52:22<25:45, 22.05it/s]

 66%|██████▌   | 66566/100629 [52:22<23:23, 24.27it/s]

 66%|██████▌   | 66569/100629 [52:22<24:49, 22.87it/s]

 66%|██████▌   | 66572/100629 [52:22<25:48, 22.00it/s]

 66%|██████▌   | 66575/100629 [52:23<32:32, 17.44it/s]

 66%|██████▌   | 66579/100629 [52:23<27:59, 20.27it/s]

 66%|██████▌   | 66582/100629 [52:23<28:14, 20.09it/s]

 66%|██████▌   | 66586/100629 [52:23<25:53, 21.92it/s]

 66%|██████▌   | 66589/100629 [52:23<30:14, 18.76it/s]

 66%|██████▌   | 66592/100629 [52:23<27:12, 20.85it/s]

 66%|██████▌   | 66596/100629 [52:23<23:22, 24.26it/s]

 66%|██████▌   | 66599/100629 [52:24<22:36, 25.08it/s]

 66%|██████▌   | 66602/100629 [52:24<21:36, 26.25it/s]

 66%|██████▌   | 66607/100629 [52:24<17:53, 31.70it/s]

 66%|██████▌   | 66611/100629 [52:24<18:06, 31.32it/s]

 66%|██████▌   | 66615/100629 [52:24<19:22, 29.25it/s]

 66%|██████▌   | 66619/100629 [52:24<23:53, 23.73it/s]

 66%|██████▌   | 66622/100629 [52:24<27:02, 20.96it/s]

 66%|██████▌   | 66625/100629 [52:25<26:11, 21.63it/s]

 66%|██████▌   | 66628/100629 [52:25<26:06, 21.70it/s]

 66%|██████▌   | 66631/100629 [52:25<25:59, 21.80it/s]

 66%|██████▌   | 66634/100629 [52:25<27:09, 20.87it/s]

 66%|██████▌   | 66637/100629 [52:25<29:03, 19.49it/s]

 66%|██████▌   | 66640/100629 [52:25<31:30, 17.98it/s]

 66%|██████▌   | 66644/100629 [52:26<26:24, 21.45it/s]

 66%|██████▌   | 66647/100629 [52:26<28:17, 20.02it/s]

 66%|██████▌   | 66650/100629 [52:26<27:52, 20.31it/s]

 66%|██████▌   | 66653/100629 [52:26<26:50, 21.09it/s]

 66%|██████▌   | 66657/100629 [52:26<31:30, 17.97it/s]

 66%|██████▌   | 66659/100629 [52:26<34:15, 16.53it/s]

 66%|██████▌   | 66661/100629 [52:27<35:54, 15.77it/s]

 66%|██████▌   | 66665/100629 [52:27<32:46, 17.27it/s]

 66%|██████▋   | 66668/100629 [52:27<29:42, 19.05it/s]

 66%|██████▋   | 66671/100629 [52:27<29:59, 18.87it/s]

 66%|██████▋   | 66674/100629 [52:27<31:36, 17.91it/s]

 66%|██████▋   | 66677/100629 [52:27<28:26, 19.90it/s]

 66%|██████▋   | 66681/100629 [52:27<25:05, 22.55it/s]

 66%|██████▋   | 66685/100629 [52:28<21:29, 26.32it/s]

 66%|██████▋   | 66689/100629 [52:28<20:38, 27.40it/s]

 66%|██████▋   | 66693/100629 [52:28<20:31, 27.56it/s]

 66%|██████▋   | 66696/100629 [52:28<20:23, 27.74it/s]

 66%|██████▋   | 66699/100629 [52:28<23:04, 24.50it/s]

 66%|██████▋   | 66702/100629 [52:28<26:23, 21.43it/s]

 66%|██████▋   | 66705/100629 [52:28<26:18, 21.50it/s]

 66%|██████▋   | 66708/100629 [52:29<24:50, 22.75it/s]

 66%|██████▋   | 66711/100629 [52:29<28:11, 20.06it/s]

 66%|██████▋   | 66715/100629 [52:29<25:25, 22.23it/s]

 66%|██████▋   | 66718/100629 [52:29<23:53, 23.65it/s]

 66%|██████▋   | 66721/100629 [52:29<27:14, 20.74it/s]

 66%|██████▋   | 66724/100629 [52:29<25:20, 22.30it/s]

 66%|██████▋   | 66727/100629 [52:29<25:20, 22.29it/s]

 66%|██████▋   | 66730/100629 [52:30<25:20, 22.30it/s]

 66%|██████▋   | 66733/100629 [52:30<26:25, 21.37it/s]

 66%|██████▋   | 66736/100629 [52:30<24:40, 22.89it/s]

 66%|██████▋   | 66739/100629 [52:30<23:56, 23.60it/s]

 66%|██████▋   | 66743/100629 [52:30<22:42, 24.88it/s]

 66%|██████▋   | 66746/100629 [52:30<24:40, 22.89it/s]

 66%|██████▋   | 66749/100629 [52:30<26:11, 21.56it/s]

 66%|██████▋   | 66752/100629 [52:31<29:38, 19.05it/s]

 66%|██████▋   | 66754/100629 [52:31<32:01, 17.63it/s]

 66%|██████▋   | 66756/100629 [52:31<31:17, 18.04it/s]

 66%|██████▋   | 66759/100629 [52:31<27:44, 20.35it/s]

 66%|██████▋   | 66762/100629 [52:31<28:38, 19.70it/s]

 66%|██████▋   | 66765/100629 [52:31<28:32, 19.77it/s]

 66%|██████▋   | 66768/100629 [52:31<28:18, 19.93it/s]

 66%|██████▋   | 66771/100629 [52:32<26:08, 21.59it/s]

 66%|██████▋   | 66774/100629 [52:32<24:10, 23.34it/s]

 66%|██████▋   | 66777/100629 [52:32<25:04, 22.50it/s]

 66%|██████▋   | 66781/100629 [52:32<22:24, 25.18it/s]

 66%|██████▋   | 66784/100629 [52:32<24:31, 23.00it/s]

 66%|██████▋   | 66787/100629 [52:32<24:22, 23.15it/s]

 66%|██████▋   | 66790/100629 [52:32<25:30, 22.10it/s]

 66%|██████▋   | 66793/100629 [52:33<28:13, 19.98it/s]

 66%|██████▋   | 66796/100629 [52:33<30:15, 18.63it/s]

 66%|██████▋   | 66799/100629 [52:33<29:52, 18.87it/s]

 66%|██████▋   | 66803/100629 [52:33<28:53, 19.52it/s]

 66%|██████▋   | 66805/100629 [52:33<28:57, 19.47it/s]

 66%|██████▋   | 66807/100629 [52:33<35:39, 15.81it/s]

 66%|██████▋   | 66811/100629 [52:34<29:17, 19.25it/s]

 66%|██████▋   | 66816/100629 [52:34<22:33, 24.98it/s]

 66%|██████▋   | 66820/100629 [52:34<23:37, 23.85it/s]

 66%|██████▋   | 66824/100629 [52:34<21:38, 26.04it/s]

 66%|██████▋   | 66827/100629 [52:34<24:09, 23.32it/s]

 66%|██████▋   | 66830/100629 [52:34<24:22, 23.11it/s]

 66%|██████▋   | 66833/100629 [52:34<27:14, 20.68it/s]

 66%|██████▋   | 66837/100629 [52:35<25:19, 22.24it/s]

 66%|██████▋   | 66840/100629 [52:35<24:13, 23.24it/s]

 66%|██████▋   | 66843/100629 [52:35<28:38, 19.66it/s]

 66%|██████▋   | 66846/100629 [52:35<27:44, 20.30it/s]

 66%|██████▋   | 66849/100629 [52:35<33:20, 16.89it/s]

 66%|██████▋   | 66851/100629 [52:35<33:40, 16.72it/s]

 66%|██████▋   | 66853/100629 [52:36<32:25, 17.37it/s]

 66%|██████▋   | 66856/100629 [52:36<28:07, 20.01it/s]

 66%|██████▋   | 66859/100629 [52:36<30:15, 18.60it/s]

 66%|██████▋   | 66862/100629 [52:36<29:33, 19.04it/s]

 66%|██████▋   | 66866/100629 [52:36<25:38, 21.95it/s]

 66%|██████▋   | 66869/100629 [52:36<25:23, 22.16it/s]

 66%|██████▋   | 66872/100629 [52:36<26:35, 21.15it/s]

 66%|██████▋   | 66878/100629 [52:37<19:53, 28.28it/s]

 66%|██████▋   | 66881/100629 [52:37<22:12, 25.32it/s]

 66%|██████▋   | 66884/100629 [52:37<21:54, 25.66it/s]

 66%|██████▋   | 66888/100629 [52:37<21:27, 26.21it/s]

 66%|██████▋   | 66891/100629 [52:37<22:56, 24.51it/s]

 66%|██████▋   | 66894/100629 [52:37<22:39, 24.81it/s]

 66%|██████▋   | 66897/100629 [52:37<26:34, 21.15it/s]

 66%|██████▋   | 66900/100629 [52:38<24:54, 22.57it/s]

 66%|██████▋   | 66903/100629 [52:38<28:31, 19.71it/s]

 66%|██████▋   | 66906/100629 [52:38<27:48, 20.21it/s]

 66%|██████▋   | 66909/100629 [52:38<26:45, 21.00it/s]

 66%|██████▋   | 66913/100629 [52:38<22:27, 25.03it/s]

 66%|██████▋   | 66917/100629 [52:38<22:23, 25.09it/s]

 67%|██████▋   | 66920/100629 [52:38<21:51, 25.71it/s]

 67%|██████▋   | 66923/100629 [52:39<23:42, 23.70it/s]

 67%|██████▋   | 66928/100629 [52:39<19:31, 28.77it/s]

 67%|██████▋   | 66931/100629 [52:39<24:07, 23.28it/s]

 67%|██████▋   | 66934/100629 [52:39<26:33, 21.15it/s]

 67%|██████▋   | 66937/100629 [52:39<25:06, 22.36it/s]

 67%|██████▋   | 66940/100629 [52:39<24:59, 22.47it/s]

 67%|██████▋   | 66945/100629 [52:39<22:05, 25.40it/s]

 67%|██████▋   | 66948/100629 [52:40<24:54, 22.53it/s]

 67%|██████▋   | 66952/100629 [52:40<21:34, 26.01it/s]

 67%|██████▋   | 66956/100629 [52:40<20:37, 27.21it/s]

 67%|██████▋   | 66959/100629 [52:40<22:40, 24.76it/s]

 67%|██████▋   | 66962/100629 [52:40<23:47, 23.59it/s]

 67%|██████▋   | 66965/100629 [52:40<23:33, 23.82it/s]

 67%|██████▋   | 66968/100629 [52:40<24:15, 23.12it/s]

 67%|██████▋   | 66972/100629 [52:41<21:43, 25.82it/s]

 67%|██████▋   | 66975/100629 [52:41<21:32, 26.03it/s]

 67%|██████▋   | 66978/100629 [52:41<23:43, 23.65it/s]

 67%|██████▋   | 66981/100629 [52:41<23:35, 23.77it/s]

 67%|██████▋   | 66985/100629 [52:41<20:31, 27.31it/s]

 67%|██████▋   | 66990/100629 [52:41<18:45, 29.89it/s]

 67%|██████▋   | 66994/100629 [52:41<20:26, 27.43it/s]

 67%|██████▋   | 66997/100629 [52:42<23:29, 23.87it/s]

 67%|██████▋   | 67000/100629 [52:42<24:26, 22.94it/s]

 67%|██████▋   | 67003/100629 [52:42<26:29, 21.16it/s]

 67%|██████▋   | 67007/100629 [52:42<22:31, 24.88it/s]

 67%|██████▋   | 67010/100629 [52:42<24:56, 22.46it/s]

 67%|██████▋   | 67013/100629 [52:42<25:49, 21.69it/s]

 67%|██████▋   | 67016/100629 [52:42<24:25, 22.94it/s]

 67%|██████▋   | 67019/100629 [52:43<27:29, 20.37it/s]

 67%|██████▋   | 67023/100629 [52:43<23:31, 23.81it/s]

 67%|██████▋   | 67027/100629 [52:43<21:38, 25.88it/s]

 67%|██████▋   | 67030/100629 [52:43<26:06, 21.44it/s]

 67%|██████▋   | 67033/100629 [52:43<24:39, 22.71it/s]

 67%|██████▋   | 67036/100629 [52:43<30:37, 18.28it/s]

 67%|██████▋   | 67039/100629 [52:43<29:20, 19.07it/s]

 67%|██████▋   | 67042/100629 [52:44<26:45, 20.92it/s]

 67%|██████▋   | 67045/100629 [52:44<24:47, 22.57it/s]

 67%|██████▋   | 67048/100629 [52:44<23:36, 23.71it/s]

 67%|██████▋   | 67052/100629 [52:44<30:04, 18.60it/s]

 67%|██████▋   | 67055/100629 [52:44<28:12, 19.84it/s]

 67%|██████▋   | 67059/100629 [52:44<26:56, 20.77it/s]

 67%|██████▋   | 67062/100629 [52:45<28:30, 19.63it/s]

 67%|██████▋   | 67065/100629 [52:45<25:51, 21.63it/s]

 67%|██████▋   | 67070/100629 [52:45<21:36, 25.88it/s]

 67%|██████▋   | 67073/100629 [52:45<24:15, 23.06it/s]

 67%|██████▋   | 67076/100629 [52:45<24:58, 22.39it/s]

 67%|██████▋   | 67079/100629 [52:45<27:12, 20.55it/s]

 67%|██████▋   | 67082/100629 [52:45<27:04, 20.66it/s]

 67%|██████▋   | 67086/100629 [52:46<23:34, 23.71it/s]

 67%|██████▋   | 67089/100629 [52:46<23:48, 23.47it/s]

 67%|██████▋   | 67092/100629 [52:46<23:23, 23.90it/s]

 67%|██████▋   | 67095/100629 [52:46<26:28, 21.12it/s]

 67%|██████▋   | 67098/100629 [52:46<24:55, 22.42it/s]

 67%|██████▋   | 67101/100629 [52:46<26:07, 21.39it/s]

 67%|██████▋   | 67104/100629 [52:46<28:52, 19.35it/s]

 67%|██████▋   | 67107/100629 [52:47<28:30, 19.60it/s]

 67%|██████▋   | 67110/100629 [52:47<26:05, 21.41it/s]

 67%|██████▋   | 67113/100629 [52:47<28:44, 19.44it/s]

 67%|██████▋   | 67117/100629 [52:47<23:41, 23.57it/s]

 67%|██████▋   | 67120/100629 [52:47<26:41, 20.93it/s]

 67%|██████▋   | 67123/100629 [52:47<27:47, 20.09it/s]

 67%|██████▋   | 67126/100629 [52:48<26:10, 21.33it/s]

 67%|██████▋   | 67129/100629 [52:48<26:47, 20.84it/s]

 67%|██████▋   | 67132/100629 [52:48<30:57, 18.04it/s]

 67%|██████▋   | 67136/100629 [52:48<30:27, 18.32it/s]

 67%|██████▋   | 67139/100629 [52:48<29:23, 18.99it/s]

 67%|██████▋   | 67141/100629 [52:48<34:43, 16.07it/s]

 67%|██████▋   | 67143/100629 [52:49<38:02, 14.67it/s]

 67%|██████▋   | 67146/100629 [52:49<34:03, 16.38it/s]

 67%|██████▋   | 67149/100629 [52:49<29:11, 19.11it/s]

 67%|██████▋   | 67152/100629 [52:49<27:00, 20.66it/s]

 67%|██████▋   | 67155/100629 [52:49<31:09, 17.90it/s]

 67%|██████▋   | 67157/100629 [52:49<31:39, 17.62it/s]

 67%|██████▋   | 67160/100629 [52:49<27:33, 20.24it/s]

 67%|██████▋   | 67163/100629 [52:50<26:30, 21.04it/s]

 67%|██████▋   | 67166/100629 [52:50<27:10, 20.52it/s]

 67%|██████▋   | 67169/100629 [52:50<25:41, 21.71it/s]

 67%|██████▋   | 67172/100629 [52:50<25:13, 22.11it/s]

 67%|██████▋   | 67176/100629 [52:50<22:28, 24.80it/s]

 67%|██████▋   | 67179/100629 [52:50<22:36, 24.66it/s]

 67%|██████▋   | 67182/100629 [52:50<25:49, 21.59it/s]

 67%|██████▋   | 67186/100629 [52:50<22:39, 24.59it/s]

 67%|██████▋   | 67189/100629 [52:51<25:39, 21.72it/s]

 67%|██████▋   | 67192/100629 [52:51<24:06, 23.12it/s]

 67%|██████▋   | 67196/100629 [52:51<23:42, 23.50it/s]

 67%|██████▋   | 67199/100629 [52:51<25:15, 22.06it/s]

 67%|██████▋   | 67203/100629 [52:51<21:52, 25.47it/s]

 67%|██████▋   | 67207/100629 [52:51<20:40, 26.95it/s]

 67%|██████▋   | 67210/100629 [52:52<23:33, 23.64it/s]

 67%|██████▋   | 67213/100629 [52:52<25:13, 22.08it/s]

 67%|██████▋   | 67216/100629 [52:52<24:06, 23.10it/s]

 67%|██████▋   | 67220/100629 [52:52<20:38, 26.97it/s]

 67%|██████▋   | 67223/100629 [52:52<27:16, 20.41it/s]

 67%|██████▋   | 67226/100629 [52:52<29:13, 19.05it/s]

 67%|██████▋   | 67229/100629 [52:52<28:23, 19.61it/s]

 67%|██████▋   | 67232/100629 [52:53<27:04, 20.55it/s]

 67%|██████▋   | 67235/100629 [52:53<26:20, 21.13it/s]

 67%|██████▋   | 67238/100629 [52:53<28:20, 19.63it/s]

 67%|██████▋   | 67241/100629 [52:53<29:44, 18.71it/s]

 67%|██████▋   | 67244/100629 [52:53<27:46, 20.04it/s]

 67%|██████▋   | 67248/100629 [52:53<23:17, 23.88it/s]

 67%|██████▋   | 67251/100629 [52:53<24:40, 22.54it/s]

 67%|██████▋   | 67256/100629 [52:54<19:16, 28.86it/s]

 67%|██████▋   | 67260/100629 [52:54<21:41, 25.64it/s]

 67%|██████▋   | 67263/100629 [52:54<22:40, 24.53it/s]

 67%|██████▋   | 67268/100629 [52:54<20:51, 26.66it/s]

 67%|██████▋   | 67271/100629 [52:54<23:08, 24.03it/s]

 67%|██████▋   | 67274/100629 [52:54<27:46, 20.02it/s]

 67%|██████▋   | 67277/100629 [52:55<28:40, 19.38it/s]

 67%|██████▋   | 67280/100629 [52:55<31:33, 17.62it/s]

 67%|██████▋   | 67283/100629 [52:55<27:55, 19.91it/s]

 67%|██████▋   | 67286/100629 [52:55<25:55, 21.44it/s]

 67%|██████▋   | 67289/100629 [52:55<26:53, 20.66it/s]

 67%|██████▋   | 67292/100629 [52:55<25:00, 22.21it/s]

 67%|██████▋   | 67295/100629 [52:55<23:25, 23.71it/s]

 67%|██████▋   | 67298/100629 [52:56<24:35, 22.59it/s]

 67%|██████▋   | 67301/100629 [52:56<24:59, 22.23it/s]

 67%|██████▋   | 67304/100629 [52:56<28:17, 19.63it/s]

 67%|██████▋   | 67308/100629 [52:56<25:19, 21.93it/s]

 67%|██████▋   | 67311/100629 [52:56<27:05, 20.49it/s]

 67%|██████▋   | 67314/100629 [52:56<26:42, 20.78it/s]

 67%|██████▋   | 67318/100629 [52:57<25:14, 22.00it/s]

 67%|██████▋   | 67321/100629 [52:57<24:18, 22.84it/s]

 67%|██████▋   | 67324/100629 [52:57<24:57, 22.25it/s]

 67%|██████▋   | 67327/100629 [52:57<26:08, 21.23it/s]

 67%|██████▋   | 67331/100629 [52:57<24:24, 22.74it/s]

 67%|██████▋   | 67334/100629 [52:57<26:27, 20.97it/s]

 67%|██████▋   | 67339/100629 [52:57<21:15, 26.10it/s]

 67%|██████▋   | 67342/100629 [52:58<27:13, 20.38it/s]

 67%|██████▋   | 67346/100629 [52:58<24:39, 22.50it/s]

 67%|██████▋   | 67349/100629 [52:58<23:49, 23.28it/s]

 67%|██████▋   | 67352/100629 [52:58<25:15, 21.96it/s]

 67%|██████▋   | 67355/100629 [52:58<27:11, 20.39it/s]

 67%|██████▋   | 67358/100629 [52:58<27:25, 20.22it/s]

 67%|██████▋   | 67361/100629 [52:58<26:19, 21.06it/s]

 67%|██████▋   | 67365/100629 [52:59<25:18, 21.90it/s]

 67%|██████▋   | 67368/100629 [52:59<25:43, 21.55it/s]

 67%|██████▋   | 67373/100629 [52:59<22:37, 24.50it/s]

 67%|██████▋   | 67377/100629 [52:59<21:18, 26.02it/s]

 67%|██████▋   | 67380/100629 [52:59<26:00, 21.30it/s]

 67%|██████▋   | 67383/100629 [52:59<25:37, 21.62it/s]

 67%|██████▋   | 67387/100629 [53:00<22:54, 24.19it/s]

 67%|██████▋   | 67391/100629 [53:00<21:49, 25.38it/s]

 67%|██████▋   | 67394/100629 [53:00<23:55, 23.15it/s]

 67%|██████▋   | 67397/100629 [53:00<23:07, 23.95it/s]

 67%|██████▋   | 67400/100629 [53:00<24:48, 22.33it/s]

 67%|██████▋   | 67403/100629 [53:00<25:31, 21.69it/s]

 67%|██████▋   | 67407/100629 [53:00<23:12, 23.86it/s]

 67%|██████▋   | 67410/100629 [53:01<22:25, 24.69it/s]

 67%|██████▋   | 67414/100629 [53:01<19:49, 27.91it/s]

 67%|██████▋   | 67417/100629 [53:01<21:37, 25.61it/s]

 67%|██████▋   | 67420/100629 [53:01<22:58, 24.09it/s]

 67%|██████▋   | 67423/100629 [53:01<28:10, 19.64it/s]

 67%|██████▋   | 67426/100629 [53:01<26:32, 20.85it/s]

 67%|██████▋   | 67429/100629 [53:01<29:15, 18.91it/s]

 67%|██████▋   | 67432/100629 [53:02<30:59, 17.85it/s]

 67%|██████▋   | 67437/100629 [53:02<24:46, 22.33it/s]

 67%|██████▋   | 67440/100629 [53:02<28:31, 19.39it/s]

 67%|██████▋   | 67443/100629 [53:02<29:15, 18.90it/s]

 67%|██████▋   | 67446/100629 [53:02<27:05, 20.41it/s]

 67%|██████▋   | 67450/100629 [53:02<22:41, 24.37it/s]

 67%|██████▋   | 67454/100629 [53:03<20:14, 27.31it/s]

 67%|██████▋   | 67458/100629 [53:03<18:33, 29.80it/s]

 67%|██████▋   | 67462/100629 [53:03<21:29, 25.73it/s]

 67%|██████▋   | 67465/100629 [53:03<24:50, 22.25it/s]

 67%|██████▋   | 67468/100629 [53:03<25:12, 21.93it/s]

 67%|██████▋   | 67472/100629 [53:03<22:42, 24.34it/s]

 67%|██████▋   | 67476/100629 [53:03<22:55, 24.11it/s]

 67%|██████▋   | 67479/100629 [53:04<22:39, 24.38it/s]

 67%|██████▋   | 67482/100629 [53:04<24:52, 22.20it/s]

 67%|██████▋   | 67485/100629 [53:04<24:46, 22.29it/s]

 67%|██████▋   | 67488/100629 [53:04<26:20, 20.97it/s]

 67%|██████▋   | 67491/100629 [53:04<26:44, 20.65it/s]

 67%|██████▋   | 67494/100629 [53:04<24:40, 22.38it/s]

 67%|██████▋   | 67498/100629 [53:04<22:57, 24.06it/s]

 67%|██████▋   | 67502/100629 [53:05<20:52, 26.44it/s]

 67%|██████▋   | 67506/100629 [53:05<20:00, 27.58it/s]

 67%|██████▋   | 67509/100629 [53:05<26:57, 20.47it/s]

 67%|██████▋   | 67513/100629 [53:05<24:44, 22.31it/s]

 67%|██████▋   | 67516/100629 [53:05<25:10, 21.92it/s]

 67%|██████▋   | 67519/100629 [53:05<28:27, 19.39it/s]

 67%|██████▋   | 67522/100629 [53:06<27:36, 19.99it/s]

 67%|██████▋   | 67525/100629 [53:06<27:18, 20.20it/s]

 67%|██████▋   | 67530/100629 [53:06<21:59, 25.09it/s]

 67%|██████▋   | 67533/100629 [53:06<27:36, 19.98it/s]

 67%|██████▋   | 67538/100629 [53:06<23:27, 23.52it/s]

 67%|██████▋   | 67541/100629 [53:06<24:14, 22.76it/s]

 67%|██████▋   | 67545/100629 [53:07<21:41, 25.43it/s]

 67%|██████▋   | 67548/100629 [53:07<22:41, 24.29it/s]

 67%|██████▋   | 67551/100629 [53:07<23:03, 23.91it/s]

 67%|██████▋   | 67554/100629 [53:07<22:10, 24.85it/s]

 67%|██████▋   | 67557/100629 [53:07<21:50, 25.23it/s]

 67%|██████▋   | 67560/100629 [53:07<22:58, 23.99it/s]

 67%|██████▋   | 67563/100629 [53:07<22:15, 24.77it/s]

 67%|██████▋   | 67566/100629 [53:07<24:00, 22.95it/s]

 67%|██████▋   | 67570/100629 [53:08<20:43, 26.59it/s]

 67%|██████▋   | 67573/100629 [53:08<20:16, 27.18it/s]

 67%|██████▋   | 67576/100629 [53:08<20:08, 27.34it/s]

 67%|██████▋   | 67580/100629 [53:08<20:11, 27.28it/s]

 67%|██████▋   | 67583/100629 [53:08<28:41, 19.20it/s]

 67%|██████▋   | 67586/100629 [53:08<26:28, 20.81it/s]

 67%|██████▋   | 67589/100629 [53:08<25:03, 21.98it/s]

 67%|██████▋   | 67592/100629 [53:09<28:15, 19.48it/s]

 67%|██████▋   | 67595/100629 [53:09<25:40, 21.44it/s]

 67%|██████▋   | 67598/100629 [53:09<24:58, 22.04it/s]

 67%|██████▋   | 67601/100629 [53:09<25:32, 21.56it/s]

 67%|██████▋   | 67605/100629 [53:09<21:29, 25.61it/s]

 67%|██████▋   | 67610/100629 [53:09<17:25, 31.59it/s]

 67%|██████▋   | 67614/100629 [53:09<17:59, 30.57it/s]

 67%|██████▋   | 67618/100629 [53:09<17:59, 30.59it/s]

 67%|██████▋   | 67622/100629 [53:10<22:22, 24.58it/s]

 67%|██████▋   | 67625/100629 [53:10<26:28, 20.77it/s]

 67%|██████▋   | 67628/100629 [53:10<28:05, 19.58it/s]

 67%|██████▋   | 67631/100629 [53:10<28:25, 19.35it/s]

 67%|██████▋   | 67634/100629 [53:10<31:52, 17.25it/s]

 67%|██████▋   | 67636/100629 [53:11<32:29, 16.92it/s]

 67%|██████▋   | 67638/100629 [53:11<34:00, 16.17it/s]

 67%|██████▋   | 67640/100629 [53:11<33:57, 16.19it/s]

 67%|██████▋   | 67642/100629 [53:11<36:08, 15.21it/s]

 67%|██████▋   | 67645/100629 [53:11<30:59, 17.74it/s]

 67%|██████▋   | 67649/100629 [53:11<26:59, 20.36it/s]

 67%|██████▋   | 67652/100629 [53:11<25:44, 21.36it/s]

 67%|██████▋   | 67656/100629 [53:12<22:46, 24.14it/s]

 67%|██████▋   | 67659/100629 [53:12<24:58, 22.00it/s]

 67%|██████▋   | 67662/100629 [53:12<26:11, 20.98it/s]

 67%|██████▋   | 67666/100629 [53:12<22:19, 24.61it/s]

 67%|██████▋   | 67669/100629 [53:12<24:10, 22.73it/s]

 67%|██████▋   | 67673/100629 [53:12<22:27, 24.46it/s]

 67%|██████▋   | 67677/100629 [53:12<22:31, 24.38it/s]

 67%|██████▋   | 67680/100629 [53:13<22:42, 24.19it/s]

 67%|██████▋   | 67683/100629 [53:13<30:40, 17.90it/s]

 67%|██████▋   | 67686/100629 [53:13<29:53, 18.36it/s]

 67%|██████▋   | 67689/100629 [53:13<32:15, 17.02it/s]

 67%|██████▋   | 67691/100629 [53:13<33:12, 16.53it/s]

 67%|██████▋   | 67694/100629 [53:13<30:26, 18.03it/s]

 67%|██████▋   | 67698/100629 [53:14<26:12, 20.94it/s]

 67%|██████▋   | 67701/100629 [53:14<29:10, 18.81it/s]

 67%|██████▋   | 67704/100629 [53:14<27:07, 20.23it/s]

 67%|██████▋   | 67708/100629 [53:14<23:25, 23.43it/s]

 67%|██████▋   | 67711/100629 [53:14<22:49, 24.04it/s]

 67%|██████▋   | 67714/100629 [53:14<23:00, 23.84it/s]

 67%|██████▋   | 67717/100629 [53:14<24:53, 22.04it/s]

 67%|██████▋   | 67721/100629 [53:15<23:12, 23.64it/s]

 67%|██████▋   | 67724/100629 [53:15<22:04, 24.84it/s]

 67%|██████▋   | 67727/100629 [53:15<21:50, 25.10it/s]

 67%|██████▋   | 67730/100629 [53:15<26:22, 20.79it/s]

 67%|██████▋   | 67733/100629 [53:15<24:27, 22.42it/s]

 67%|██████▋   | 67736/100629 [53:15<30:22, 18.05it/s]

 67%|██████▋   | 67739/100629 [53:16<29:52, 18.35it/s]

 67%|██████▋   | 67742/100629 [53:16<30:10, 18.16it/s]

 67%|██████▋   | 67746/100629 [53:16<27:07, 20.20it/s]

 67%|██████▋   | 67749/100629 [53:16<26:30, 20.68it/s]

 67%|██████▋   | 67752/100629 [53:16<28:12, 19.43it/s]

 67%|██████▋   | 67756/100629 [53:16<26:30, 20.67it/s]

 67%|██████▋   | 67761/100629 [53:17<22:55, 23.90it/s]

 67%|██████▋   | 67764/100629 [53:17<26:18, 20.82it/s]

 67%|██████▋   | 67767/100629 [53:17<25:32, 21.44it/s]

 67%|██████▋   | 67770/100629 [53:17<24:12, 22.62it/s]

 67%|██████▋   | 67773/100629 [53:17<25:19, 21.63it/s]

 67%|██████▋   | 67776/100629 [53:17<24:09, 22.67it/s]

 67%|██████▋   | 67780/100629 [53:17<22:36, 24.21it/s]

 67%|██████▋   | 67783/100629 [53:17<21:58, 24.91it/s]

 67%|██████▋   | 67786/100629 [53:18<21:57, 24.93it/s]

 67%|██████▋   | 67789/100629 [53:18<22:11, 24.67it/s]

 67%|██████▋   | 67792/100629 [53:18<24:36, 22.24it/s]

 67%|██████▋   | 67795/100629 [53:18<24:10, 22.64it/s]

 67%|██████▋   | 67798/100629 [53:18<25:46, 21.23it/s]

 67%|██████▋   | 67801/100629 [53:18<24:34, 22.27it/s]

 67%|██████▋   | 67804/100629 [53:19<29:35, 18.48it/s]

 67%|██████▋   | 67806/100629 [53:19<36:44, 14.89it/s]

 67%|██████▋   | 67808/100629 [53:19<34:54, 15.67it/s]

 67%|██████▋   | 67810/100629 [53:19<33:01, 16.56it/s]

 67%|██████▋   | 67812/100629 [53:19<32:49, 16.66it/s]

 67%|██████▋   | 67814/100629 [53:19<32:13, 16.98it/s]

 67%|██████▋   | 67817/100629 [53:19<27:38, 19.79it/s]

 67%|██████▋   | 67820/100629 [53:19<26:58, 20.27it/s]

 67%|██████▋   | 67823/100629 [53:20<26:08, 20.92it/s]

 67%|██████▋   | 67826/100629 [53:20<26:31, 20.62it/s]

 67%|██████▋   | 67830/100629 [53:20<23:44, 23.02it/s]

 67%|██████▋   | 67834/100629 [53:20<23:04, 23.68it/s]

 67%|██████▋   | 67837/100629 [53:20<25:04, 21.79it/s]

 67%|██████▋   | 67840/100629 [53:21<34:14, 15.96it/s]

 67%|██████▋   | 67842/100629 [53:21<33:13, 16.45it/s]

 67%|██████▋   | 67844/100629 [53:21<34:38, 15.78it/s]

 67%|██████▋   | 67848/100629 [53:21<26:41, 20.47it/s]

 67%|██████▋   | 67851/100629 [53:21<34:02, 16.05it/s]

 67%|██████▋   | 67854/100629 [53:21<31:03, 17.59it/s]

 67%|██████▋   | 67858/100629 [53:21<26:42, 20.45it/s]

 67%|██████▋   | 67861/100629 [53:22<24:27, 22.33it/s]

 67%|██████▋   | 67865/100629 [53:22<20:55, 26.09it/s]

 67%|██████▋   | 67868/100629 [53:22<21:26, 25.47it/s]

 67%|██████▋   | 67872/100629 [53:22<20:02, 27.25it/s]

 67%|██████▋   | 67877/100629 [53:22<18:40, 29.24it/s]

 67%|██████▋   | 67880/100629 [53:22<18:40, 29.23it/s]

 67%|██████▋   | 67883/100629 [53:22<19:32, 27.93it/s]

 67%|██████▋   | 67887/100629 [53:22<21:00, 25.99it/s]

 67%|██████▋   | 67890/100629 [53:23<22:20, 24.42it/s]

 67%|██████▋   | 67893/100629 [53:23<27:37, 19.75it/s]

 67%|██████▋   | 67897/100629 [53:23<26:03, 20.93it/s]

 67%|██████▋   | 67900/100629 [53:23<27:12, 20.05it/s]

 67%|██████▋   | 67903/100629 [53:23<29:23, 18.55it/s]

 67%|██████▋   | 67905/100629 [53:24<32:52, 16.59it/s]

 67%|██████▋   | 67908/100629 [53:24<30:57, 17.62it/s]

 67%|██████▋   | 67912/100629 [53:24<26:45, 20.38it/s]

 67%|██████▋   | 67915/100629 [53:24<27:06, 20.11it/s]

 67%|██████▋   | 67919/100629 [53:24<25:02, 21.77it/s]

 67%|██████▋   | 67923/100629 [53:24<23:26, 23.25it/s]

 68%|██████▊   | 67927/100629 [53:24<21:41, 25.13it/s]

 68%|██████▊   | 67930/100629 [53:25<23:01, 23.66it/s]

 68%|██████▊   | 67933/100629 [53:25<23:57, 22.74it/s]

 68%|██████▊   | 67936/100629 [53:25<24:30, 22.23it/s]

 68%|██████▊   | 67939/100629 [53:25<24:01, 22.68it/s]

 68%|██████▊   | 67942/100629 [53:25<24:16, 22.45it/s]

 68%|██████▊   | 67945/100629 [53:25<24:45, 22.01it/s]

 68%|██████▊   | 67949/100629 [53:25<21:48, 24.97it/s]

 68%|██████▊   | 67952/100629 [53:26<23:40, 23.01it/s]

 68%|██████▊   | 67955/100629 [53:26<28:07, 19.36it/s]

 68%|██████▊   | 67958/100629 [53:26<28:35, 19.05it/s]

 68%|██████▊   | 67962/100629 [53:26<24:47, 21.96it/s]

 68%|██████▊   | 67965/100629 [53:26<24:17, 22.41it/s]

 68%|██████▊   | 67968/100629 [53:26<23:55, 22.75it/s]

 68%|██████▊   | 67971/100629 [53:26<26:47, 20.31it/s]

 68%|██████▊   | 67974/100629 [53:27<27:47, 19.58it/s]

 68%|██████▊   | 67978/100629 [53:27<24:35, 22.13it/s]

 68%|██████▊   | 67981/100629 [53:27<30:20, 17.93it/s]

 68%|██████▊   | 67983/100629 [53:27<30:21, 17.92it/s]

 68%|██████▊   | 67987/100629 [53:27<26:14, 20.74it/s]

 68%|██████▊   | 67990/100629 [53:27<24:52, 21.87it/s]

 68%|██████▊   | 67995/100629 [53:28<21:21, 25.47it/s]

 68%|██████▊   | 67998/100629 [53:28<22:07, 24.58it/s]

 68%|██████▊   | 68001/100629 [53:28<21:29, 25.31it/s]

 68%|██████▊   | 68005/100629 [53:28<20:16, 26.81it/s]

 68%|██████▊   | 68008/100629 [53:28<19:58, 27.21it/s]

 68%|██████▊   | 68011/100629 [53:28<20:15, 26.83it/s]

 68%|██████▊   | 68014/100629 [53:28<25:25, 21.38it/s]

 68%|██████▊   | 68017/100629 [53:29<26:41, 20.36it/s]

 68%|██████▊   | 68020/100629 [53:29<25:50, 21.03it/s]

 68%|██████▊   | 68023/100629 [53:29<27:41, 19.63it/s]

 68%|██████▊   | 68026/100629 [53:29<25:12, 21.55it/s]

 68%|██████▊   | 68032/100629 [53:29<18:36, 29.20it/s]

 68%|██████▊   | 68036/100629 [53:29<19:45, 27.49it/s]

 68%|██████▊   | 68039/100629 [53:29<20:35, 26.39it/s]

 68%|██████▊   | 68043/100629 [53:29<18:22, 29.55it/s]

 68%|██████▊   | 68047/100629 [53:30<17:01, 31.89it/s]

 68%|██████▊   | 68051/100629 [53:30<20:46, 26.13it/s]

 68%|██████▊   | 68054/100629 [53:30<20:56, 25.93it/s]

 68%|██████▊   | 68057/100629 [53:30<22:35, 24.04it/s]

 68%|██████▊   | 68060/100629 [53:30<23:10, 23.42it/s]

 68%|██████▊   | 68063/100629 [53:30<22:46, 23.84it/s]

 68%|██████▊   | 68066/100629 [53:30<24:08, 22.48it/s]

 68%|██████▊   | 68069/100629 [53:31<23:28, 23.12it/s]

 68%|██████▊   | 68072/100629 [53:31<25:14, 21.49it/s]

 68%|██████▊   | 68075/100629 [53:31<24:17, 22.34it/s]

 68%|██████▊   | 68079/100629 [53:31<20:58, 25.86it/s]

 68%|██████▊   | 68082/100629 [53:31<23:46, 22.81it/s]

 68%|██████▊   | 68085/100629 [53:31<22:10, 24.46it/s]

 68%|██████▊   | 68089/100629 [53:31<20:09, 26.91it/s]

 68%|██████▊   | 68093/100629 [53:32<20:51, 25.99it/s]

 68%|██████▊   | 68096/100629 [53:32<22:12, 24.42it/s]

 68%|██████▊   | 68099/100629 [53:32<27:33, 19.67it/s]

 68%|██████▊   | 68102/100629 [53:32<28:59, 18.70it/s]

 68%|██████▊   | 68104/100629 [53:32<28:53, 18.76it/s]

 68%|██████▊   | 68107/100629 [53:32<25:50, 20.97it/s]

 68%|██████▊   | 68110/100629 [53:32<26:21, 20.56it/s]

 68%|██████▊   | 68113/100629 [53:33<29:06, 18.62it/s]

 68%|██████▊   | 68116/100629 [53:33<28:39, 18.90it/s]

 68%|██████▊   | 68119/100629 [53:33<26:14, 20.65it/s]

 68%|██████▊   | 68122/100629 [53:33<27:48, 19.48it/s]

 68%|██████▊   | 68125/100629 [53:33<32:09, 16.85it/s]

 68%|██████▊   | 68127/100629 [53:33<31:37, 17.13it/s]

 68%|██████▊   | 68131/100629 [53:34<27:43, 19.53it/s]

 68%|██████▊   | 68134/100629 [53:34<25:46, 21.01it/s]

 68%|██████▊   | 68137/100629 [53:34<28:09, 19.24it/s]

 68%|██████▊   | 68141/100629 [53:34<24:35, 22.02it/s]

 68%|██████▊   | 68144/100629 [53:34<23:41, 22.86it/s]

 68%|██████▊   | 68147/100629 [53:34<28:22, 19.08it/s]

 68%|██████▊   | 68150/100629 [53:35<33:12, 16.30it/s]

 68%|██████▊   | 68154/100629 [53:35<28:10, 19.21it/s]

 68%|██████▊   | 68158/100629 [53:35<25:02, 21.61it/s]

 68%|██████▊   | 68162/100629 [53:35<23:18, 23.21it/s]

 68%|██████▊   | 68165/100629 [53:35<26:39, 20.30it/s]

 68%|██████▊   | 68168/100629 [53:35<27:24, 19.74it/s]

 68%|██████▊   | 68171/100629 [53:36<26:00, 20.80it/s]

 68%|██████▊   | 68174/100629 [53:36<29:52, 18.11it/s]

 68%|██████▊   | 68176/100629 [53:36<33:33, 16.12it/s]

 68%|██████▊   | 68179/100629 [53:36<29:37, 18.25it/s]

 68%|██████▊   | 68182/100629 [53:36<26:37, 20.31it/s]

 68%|██████▊   | 68185/100629 [53:36<27:01, 20.01it/s]

 68%|██████▊   | 68189/100629 [53:36<22:32, 23.98it/s]

 68%|██████▊   | 68194/100629 [53:37<19:29, 27.75it/s]

 68%|██████▊   | 68198/100629 [53:37<20:22, 26.53it/s]

 68%|██████▊   | 68202/100629 [53:37<18:30, 29.21it/s]

 68%|██████▊   | 68206/100629 [53:37<17:59, 30.03it/s]

 68%|██████▊   | 68210/100629 [53:37<17:12, 31.39it/s]

 68%|██████▊   | 68214/100629 [53:37<18:04, 29.90it/s]

 68%|██████▊   | 68218/100629 [53:37<19:34, 27.59it/s]

 68%|██████▊   | 68223/100629 [53:38<19:56, 27.09it/s]

 68%|██████▊   | 68226/100629 [53:38<19:30, 27.69it/s]

 68%|██████▊   | 68230/100629 [53:38<19:43, 27.38it/s]

 68%|██████▊   | 68233/100629 [53:38<20:04, 26.91it/s]

 68%|██████▊   | 68236/100629 [53:38<20:08, 26.81it/s]

 68%|██████▊   | 68239/100629 [53:38<22:32, 23.95it/s]

 68%|██████▊   | 68242/100629 [53:38<23:05, 23.37it/s]

 68%|██████▊   | 68245/100629 [53:39<25:18, 21.33it/s]

 68%|██████▊   | 68248/100629 [53:39<25:10, 21.44it/s]

 68%|██████▊   | 68251/100629 [53:39<27:07, 19.90it/s]

 68%|██████▊   | 68255/100629 [53:39<22:32, 23.93it/s]

 68%|██████▊   | 68258/100629 [53:39<22:18, 24.18it/s]

 68%|██████▊   | 68261/100629 [53:39<23:55, 22.55it/s]

 68%|██████▊   | 68264/100629 [53:39<24:03, 22.41it/s]

 68%|██████▊   | 68267/100629 [53:40<27:19, 19.74it/s]

 68%|██████▊   | 68270/100629 [53:40<25:04, 21.51it/s]

 68%|██████▊   | 68273/100629 [53:40<25:44, 20.95it/s]

 68%|██████▊   | 68276/100629 [53:40<24:18, 22.18it/s]

 68%|██████▊   | 68279/100629 [53:40<25:34, 21.09it/s]

 68%|██████▊   | 68282/100629 [53:40<25:24, 21.22it/s]

 68%|██████▊   | 68285/100629 [53:40<26:42, 20.18it/s]

 68%|██████▊   | 68288/100629 [53:41<26:13, 20.55it/s]

 68%|██████▊   | 68291/100629 [53:41<26:24, 20.41it/s]

 68%|██████▊   | 68294/100629 [53:41<30:47, 17.50it/s]

 68%|██████▊   | 68296/100629 [53:41<36:56, 14.59it/s]

 68%|██████▊   | 68300/100629 [53:41<30:01, 17.95it/s]

 68%|██████▊   | 68302/100629 [53:41<31:08, 17.30it/s]

 68%|██████▊   | 68305/100629 [53:42<28:30, 18.90it/s]

 68%|██████▊   | 68308/100629 [53:42<28:45, 18.73it/s]

 68%|██████▊   | 68312/100629 [53:42<24:31, 21.96it/s]

 68%|██████▊   | 68315/100629 [53:42<22:52, 23.55it/s]

 68%|██████▊   | 68318/100629 [53:42<26:09, 20.59it/s]

 68%|██████▊   | 68321/100629 [53:42<24:30, 21.97it/s]

 68%|██████▊   | 68324/100629 [53:42<23:46, 22.65it/s]

 68%|██████▊   | 68327/100629 [53:42<24:16, 22.18it/s]

 68%|██████▊   | 68330/100629 [53:43<22:40, 23.74it/s]

 68%|██████▊   | 68333/100629 [53:43<23:37, 22.78it/s]

 68%|██████▊   | 68338/100629 [53:43<21:08, 25.45it/s]

 68%|██████▊   | 68341/100629 [53:43<21:48, 24.68it/s]

 68%|██████▊   | 68344/100629 [53:43<21:27, 25.07it/s]

 68%|██████▊   | 68347/100629 [53:43<21:07, 25.48it/s]

 68%|██████▊   | 68350/100629 [53:43<21:01, 25.60it/s]

 68%|██████▊   | 68353/100629 [53:43<20:32, 26.18it/s]

 68%|██████▊   | 68358/100629 [53:44<19:29, 27.59it/s]

 68%|██████▊   | 68361/100629 [53:44<20:28, 26.26it/s]

 68%|██████▊   | 68364/100629 [53:44<22:51, 23.53it/s]

 68%|██████▊   | 68369/100629 [53:44<18:45, 28.67it/s]

 68%|██████▊   | 68372/100629 [53:44<22:51, 23.52it/s]

 68%|██████▊   | 68375/100629 [53:44<22:26, 23.95it/s]

 68%|██████▊   | 68379/100629 [53:45<21:53, 24.56it/s]

 68%|██████▊   | 68383/100629 [53:45<21:46, 24.69it/s]

 68%|██████▊   | 68386/100629 [53:45<24:54, 21.57it/s]

 68%|██████▊   | 68389/100629 [53:45<24:17, 22.12it/s]

 68%|██████▊   | 68392/100629 [53:45<27:14, 19.72it/s]

 68%|██████▊   | 68395/100629 [53:45<28:24, 18.91it/s]

 68%|██████▊   | 68397/100629 [53:46<35:42, 15.04it/s]

 68%|██████▊   | 68399/100629 [53:46<34:22, 15.62it/s]

 68%|██████▊   | 68402/100629 [53:46<30:07, 17.83it/s]

 68%|██████▊   | 68404/100629 [53:46<29:22, 18.28it/s]

 68%|██████▊   | 68407/100629 [53:46<26:45, 20.07it/s]

 68%|██████▊   | 68410/100629 [53:46<32:51, 16.35it/s]

 68%|██████▊   | 68412/100629 [53:46<35:23, 15.17it/s]

 68%|██████▊   | 68416/100629 [53:47<33:34, 15.99it/s]

 68%|██████▊   | 68418/100629 [53:47<33:18, 16.12it/s]

 68%|██████▊   | 68421/100629 [53:47<30:17, 17.72it/s]

 68%|██████▊   | 68424/100629 [53:47<27:11, 19.74it/s]

 68%|██████▊   | 68427/100629 [53:47<25:06, 21.37it/s]

 68%|██████▊   | 68430/100629 [53:47<27:18, 19.65it/s]

 68%|██████▊   | 68433/100629 [53:48<30:24, 17.65it/s]

 68%|██████▊   | 68436/100629 [53:48<28:42, 18.69it/s]

 68%|██████▊   | 68438/100629 [53:48<29:15, 18.34it/s]

 68%|██████▊   | 68441/100629 [53:48<28:01, 19.14it/s]

 68%|██████▊   | 68444/100629 [53:48<26:02, 20.60it/s]

 68%|██████▊   | 68447/100629 [53:48<29:11, 18.37it/s]

 68%|██████▊   | 68450/100629 [53:48<25:59, 20.64it/s]

 68%|██████▊   | 68453/100629 [53:49<24:17, 22.08it/s]

 68%|██████▊   | 68456/100629 [53:49<23:35, 22.73it/s]

 68%|██████▊   | 68459/100629 [53:49<30:08, 17.79it/s]

 68%|██████▊   | 68462/100629 [53:49<27:23, 19.57it/s]

 68%|██████▊   | 68466/100629 [53:49<23:40, 22.63it/s]

 68%|██████▊   | 68469/100629 [53:49<24:49, 21.59it/s]

 68%|██████▊   | 68472/100629 [53:49<25:09, 21.31it/s]

 68%|██████▊   | 68475/100629 [53:50<27:35, 19.43it/s]

 68%|██████▊   | 68478/100629 [53:50<28:06, 19.07it/s]

 68%|██████▊   | 68480/100629 [53:50<30:47, 17.40it/s]

 68%|██████▊   | 68482/100629 [53:50<32:44, 16.36it/s]

 68%|██████▊   | 68485/100629 [53:50<30:21, 17.65it/s]

 68%|██████▊   | 68489/100629 [53:50<25:18, 21.17it/s]

 68%|██████▊   | 68492/100629 [53:51<25:17, 21.17it/s]

 68%|██████▊   | 68497/100629 [53:51<20:44, 25.82it/s]

 68%|██████▊   | 68501/100629 [53:51<19:49, 27.02it/s]

 68%|██████▊   | 68504/100629 [53:51<20:33, 26.05it/s]

 68%|██████▊   | 68507/100629 [53:51<20:46, 25.76it/s]

 68%|██████▊   | 68510/100629 [53:51<25:30, 20.99it/s]

 68%|██████▊   | 68513/100629 [53:51<23:26, 22.83it/s]

 68%|██████▊   | 68517/100629 [53:51<21:28, 24.92it/s]

 68%|██████▊   | 68520/100629 [53:52<24:43, 21.65it/s]

 68%|██████▊   | 68524/100629 [53:52<21:40, 24.69it/s]

 68%|██████▊   | 68527/100629 [53:52<22:46, 23.49it/s]

 68%|██████▊   | 68533/100629 [53:52<17:15, 31.01it/s]

 68%|██████▊   | 68537/100629 [53:52<17:16, 30.96it/s]

 68%|██████▊   | 68541/100629 [53:52<21:17, 25.12it/s]

 68%|██████▊   | 68544/100629 [53:53<23:37, 22.63it/s]

 68%|██████▊   | 68547/100629 [53:53<25:29, 20.98it/s]

 68%|██████▊   | 68550/100629 [53:53<24:14, 22.05it/s]

 68%|██████▊   | 68553/100629 [53:53<28:01, 19.08it/s]

 68%|██████▊   | 68556/100629 [53:53<31:13, 17.12it/s]

 68%|██████▊   | 68560/100629 [53:53<28:45, 18.58it/s]

 68%|██████▊   | 68562/100629 [53:54<28:48, 18.55it/s]

 68%|██████▊   | 68564/100629 [53:54<30:07, 17.74it/s]

 68%|██████▊   | 68568/100629 [53:54<24:00, 22.26it/s]

 68%|██████▊   | 68571/100629 [53:54<23:51, 22.40it/s]

 68%|██████▊   | 68574/100629 [53:54<24:55, 21.43it/s]

 68%|██████▊   | 68577/100629 [53:54<26:21, 20.27it/s]

 68%|██████▊   | 68580/100629 [53:54<28:11, 18.95it/s]

 68%|██████▊   | 68584/100629 [53:55<24:54, 21.44it/s]

 68%|██████▊   | 68587/100629 [53:55<28:43, 18.59it/s]

 68%|██████▊   | 68590/100629 [53:55<26:32, 20.12it/s]

 68%|██████▊   | 68593/100629 [53:55<24:08, 22.11it/s]

 68%|██████▊   | 68596/100629 [53:55<22:23, 23.85it/s]

 68%|██████▊   | 68599/100629 [53:55<23:18, 22.90it/s]

 68%|██████▊   | 68602/100629 [53:55<23:29, 22.71it/s]

 68%|██████▊   | 68607/100629 [53:56<19:10, 27.82it/s]

 68%|██████▊   | 68610/100629 [53:56<24:08, 22.10it/s]

 68%|██████▊   | 68613/100629 [53:56<23:16, 22.93it/s]

 68%|██████▊   | 68616/100629 [53:56<25:17, 21.10it/s]

 68%|██████▊   | 68620/100629 [53:56<23:59, 22.23it/s]

 68%|██████▊   | 68623/100629 [53:56<25:49, 20.66it/s]

 68%|██████▊   | 68627/100629 [53:56<21:42, 24.57it/s]

 68%|██████▊   | 68630/100629 [53:57<20:42, 25.76it/s]

 68%|██████▊   | 68634/100629 [53:57<18:47, 28.38it/s]

 68%|██████▊   | 68637/100629 [53:57<22:52, 23.31it/s]

 68%|██████▊   | 68640/100629 [53:57<22:12, 24.00it/s]

 68%|██████▊   | 68643/100629 [53:57<23:58, 22.23it/s]

 68%|██████▊   | 68646/100629 [53:57<22:29, 23.70it/s]

 68%|██████▊   | 68649/100629 [53:57<21:21, 24.96it/s]

 68%|██████▊   | 68653/100629 [53:58<19:59, 26.65it/s]

 68%|██████▊   | 68656/100629 [53:58<21:02, 25.33it/s]

 68%|██████▊   | 68659/100629 [53:58<22:41, 23.47it/s]

 68%|██████▊   | 68662/100629 [53:58<24:46, 21.51it/s]

 68%|██████▊   | 68668/100629 [53:58<19:12, 27.74it/s]

 68%|██████▊   | 68672/100629 [53:58<17:38, 30.20it/s]

 68%|██████▊   | 68676/100629 [53:58<23:48, 22.37it/s]

 68%|██████▊   | 68679/100629 [53:59<24:57, 21.33it/s]

 68%|██████▊   | 68683/100629 [53:59<22:33, 23.60it/s]

 68%|██████▊   | 68686/100629 [53:59<22:48, 23.35it/s]

 68%|██████▊   | 68689/100629 [53:59<22:35, 23.57it/s]

 68%|██████▊   | 68692/100629 [53:59<23:13, 22.93it/s]

 68%|██████▊   | 68695/100629 [53:59<21:52, 24.33it/s]

 68%|██████▊   | 68699/100629 [53:59<19:43, 26.99it/s]

 68%|██████▊   | 68702/100629 [54:00<25:09, 21.15it/s]

 68%|██████▊   | 68705/100629 [54:00<25:00, 21.28it/s]

 68%|██████▊   | 68708/100629 [54:00<24:46, 21.47it/s]

 68%|██████▊   | 68711/100629 [54:00<23:51, 22.29it/s]

 68%|██████▊   | 68714/100629 [54:00<22:06, 24.06it/s]

 68%|██████▊   | 68717/100629 [54:00<21:48, 24.39it/s]

 68%|██████▊   | 68721/100629 [54:00<20:58, 25.35it/s]

 68%|██████▊   | 68724/100629 [54:00<20:43, 25.66it/s]

 68%|██████▊   | 68727/100629 [54:01<20:14, 26.28it/s]

 68%|██████▊   | 68731/100629 [54:01<18:58, 28.02it/s]

 68%|██████▊   | 68734/100629 [54:01<21:58, 24.19it/s]

 68%|██████▊   | 68737/100629 [54:01<21:39, 24.53it/s]

 68%|██████▊   | 68740/100629 [54:01<24:45, 21.47it/s]

 68%|██████▊   | 68743/100629 [54:01<26:18, 20.20it/s]

 68%|██████▊   | 68746/100629 [54:01<24:06, 22.04it/s]

 68%|██████▊   | 68749/100629 [54:02<24:45, 21.46it/s]

 68%|██████▊   | 68752/100629 [54:02<23:39, 22.45it/s]

 68%|██████▊   | 68755/100629 [54:02<22:58, 23.12it/s]

 68%|██████▊   | 68758/100629 [54:02<23:26, 22.66it/s]

 68%|██████▊   | 68761/100629 [54:02<23:50, 22.27it/s]

 68%|██████▊   | 68764/100629 [54:02<23:15, 22.83it/s]

 68%|██████▊   | 68767/100629 [54:02<26:03, 20.37it/s]

 68%|██████▊   | 68770/100629 [54:03<29:44, 17.85it/s]

 68%|██████▊   | 68772/100629 [54:03<32:32, 16.31it/s]

 68%|██████▊   | 68774/100629 [54:03<33:32, 15.83it/s]

 68%|██████▊   | 68778/100629 [54:03<27:38, 19.20it/s]

 68%|██████▊   | 68780/100629 [54:03<27:31, 19.29it/s]

 68%|██████▊   | 68782/100629 [54:03<29:49, 17.80it/s]

 68%|██████▊   | 68784/100629 [54:03<31:50, 16.67it/s]

 68%|██████▊   | 68786/100629 [54:04<38:07, 13.92it/s]

 68%|██████▊   | 68788/100629 [54:04<39:09, 13.55it/s]

 68%|██████▊   | 68791/100629 [54:04<36:43, 14.45it/s]

 68%|██████▊   | 68795/100629 [54:04<27:09, 19.54it/s]

 68%|██████▊   | 68798/100629 [54:04<24:48, 21.38it/s]

 68%|██████▊   | 68802/100629 [54:05<41:21, 12.83it/s]

 68%|██████▊   | 68805/100629 [54:05<34:58, 15.17it/s]

 68%|██████▊   | 68808/100629 [54:05<38:27, 13.79it/s]

 68%|██████▊   | 68810/100629 [54:05<37:49, 14.02it/s]

 68%|██████▊   | 68813/100629 [54:05<34:12, 15.50it/s]

 68%|██████▊   | 68815/100629 [54:06<35:09, 15.08it/s]

 68%|██████▊   | 68817/100629 [54:06<35:55, 14.76it/s]

 68%|██████▊   | 68820/100629 [54:06<31:57, 16.59it/s]

 68%|██████▊   | 68822/100629 [54:06<32:08, 16.50it/s]

 68%|██████▊   | 68824/100629 [54:06<32:17, 16.41it/s]

 68%|██████▊   | 68827/100629 [54:06<29:02, 18.25it/s]

 68%|██████▊   | 68829/100629 [54:06<35:35, 14.89it/s]

 68%|██████▊   | 68832/100629 [54:07<33:07, 15.99it/s]

 68%|██████▊   | 68834/100629 [54:07<34:20, 15.43it/s]

 68%|██████▊   | 68837/100629 [54:07<30:13, 17.53it/s]

 68%|██████▊   | 68840/100629 [54:07<28:26, 18.63it/s]

 68%|██████▊   | 68844/100629 [54:07<27:03, 19.58it/s]

 68%|██████▊   | 68847/100629 [54:07<25:40, 20.63it/s]

 68%|██████▊   | 68850/100629 [54:08<26:42, 19.84it/s]

 68%|██████▊   | 68854/100629 [54:08<22:48, 23.22it/s]

 68%|██████▊   | 68858/100629 [54:08<22:38, 23.38it/s]

 68%|██████▊   | 68862/100629 [54:08<22:52, 23.15it/s]

 68%|██████▊   | 68867/100629 [54:08<18:25, 28.74it/s]

 68%|██████▊   | 68871/100629 [54:08<17:09, 30.85it/s]

 68%|██████▊   | 68875/100629 [54:08<16:41, 31.72it/s]

 68%|██████▊   | 68880/100629 [54:08<16:14, 32.57it/s]

 68%|██████▊   | 68884/100629 [54:09<18:00, 29.38it/s]

 68%|██████▊   | 68888/100629 [54:09<18:45, 28.21it/s]

 68%|██████▊   | 68891/100629 [54:09<22:02, 23.99it/s]

 68%|██████▊   | 68896/100629 [54:09<19:55, 26.55it/s]

 68%|██████▊   | 68899/100629 [54:09<27:21, 19.33it/s]

 68%|██████▊   | 68902/100629 [54:10<27:42, 19.09it/s]

 68%|██████▊   | 68905/100629 [54:10<25:12, 20.98it/s]

 68%|██████▊   | 68909/100629 [54:10<26:45, 19.76it/s]

 68%|██████▊   | 68912/100629 [54:10<26:24, 20.01it/s]

 68%|██████▊   | 68915/100629 [54:10<30:30, 17.32it/s]

 68%|██████▊   | 68919/100629 [54:10<26:35, 19.88it/s]

 68%|██████▊   | 68922/100629 [54:11<25:33, 20.67it/s]

 68%|██████▊   | 68925/100629 [54:11<29:38, 17.83it/s]

 68%|██████▊   | 68927/100629 [54:11<29:21, 18.00it/s]

 68%|██████▊   | 68930/100629 [54:11<28:57, 18.25it/s]

 69%|██████▊   | 68933/100629 [54:11<27:36, 19.13it/s]

 69%|██████▊   | 68936/100629 [54:11<25:00, 21.13it/s]

 69%|██████▊   | 68939/100629 [54:11<24:55, 21.18it/s]

 69%|██████▊   | 68943/100629 [54:12<21:12, 24.90it/s]

 69%|██████▊   | 68946/100629 [54:12<23:42, 22.28it/s]

 69%|██████▊   | 68950/100629 [54:12<21:27, 24.61it/s]

 69%|██████▊   | 68953/100629 [54:12<28:20, 18.63it/s]

 69%|██████▊   | 68957/100629 [54:12<23:15, 22.70it/s]

 69%|██████▊   | 68960/100629 [54:12<26:48, 19.69it/s]

 69%|██████▊   | 68964/100629 [54:13<22:36, 23.35it/s]

 69%|██████▊   | 68967/100629 [54:13<21:20, 24.73it/s]

 69%|██████▊   | 68970/100629 [54:13<24:02, 21.95it/s]

 69%|██████▊   | 68973/100629 [54:13<23:40, 22.28it/s]

 69%|██████▊   | 68976/100629 [54:13<24:50, 21.24it/s]

 69%|██████▊   | 68979/100629 [54:13<25:32, 20.66it/s]

 69%|██████▊   | 68983/100629 [54:13<21:13, 24.85it/s]

 69%|██████▊   | 68986/100629 [54:14<24:22, 21.63it/s]

 69%|██████▊   | 68989/100629 [54:14<26:38, 19.80it/s]

 69%|██████▊   | 68992/100629 [54:14<26:44, 19.71it/s]

 69%|██████▊   | 68995/100629 [54:14<26:00, 20.27it/s]

 69%|██████▊   | 68999/100629 [54:14<22:34, 23.35it/s]

 69%|██████▊   | 69003/100629 [54:14<23:04, 22.84it/s]

 69%|██████▊   | 69007/100629 [54:14<21:28, 24.54it/s]

 69%|██████▊   | 69011/100629 [54:15<19:10, 27.48it/s]

 69%|██████▊   | 69015/100629 [54:15<19:34, 26.92it/s]

 69%|██████▊   | 69018/100629 [54:15<27:02, 19.48it/s]

 69%|██████▊   | 69021/100629 [54:15<27:56, 18.86it/s]

 69%|██████▊   | 69024/100629 [54:15<25:43, 20.48it/s]

 69%|██████▊   | 69027/100629 [54:15<24:23, 21.59it/s]

 69%|██████▊   | 69030/100629 [54:16<25:59, 20.26it/s]

 69%|██████▊   | 69033/100629 [54:16<29:01, 18.14it/s]

 69%|██████▊   | 69035/100629 [54:16<29:25, 17.90it/s]

 69%|██████▊   | 69037/100629 [54:16<29:25, 17.89it/s]

 69%|██████▊   | 69040/100629 [54:16<28:21, 18.56it/s]

 69%|██████▊   | 69044/100629 [54:16<22:56, 22.94it/s]

 69%|██████▊   | 69047/100629 [54:16<22:38, 23.24it/s]

 69%|██████▊   | 69050/100629 [54:17<22:47, 23.10it/s]

 69%|██████▊   | 69054/100629 [54:17<19:49, 26.54it/s]

 69%|██████▊   | 69057/100629 [54:17<19:45, 26.63it/s]

 69%|██████▊   | 69060/100629 [54:17<26:53, 19.57it/s]

 69%|██████▊   | 69063/100629 [54:17<25:43, 20.45it/s]

 69%|██████▊   | 69066/100629 [54:17<28:35, 18.40it/s]

 69%|██████▊   | 69069/100629 [54:17<26:19, 19.98it/s]

 69%|██████▊   | 69073/100629 [54:18<22:03, 23.84it/s]

 69%|██████▊   | 69076/100629 [54:18<23:35, 22.29it/s]

 69%|██████▊   | 69079/100629 [54:18<27:56, 18.82it/s]

 69%|██████▊   | 69082/100629 [54:18<25:53, 20.31it/s]

 69%|██████▊   | 69085/100629 [54:18<27:48, 18.91it/s]

 69%|██████▊   | 69088/100629 [54:18<27:17, 19.26it/s]

 69%|██████▊   | 69091/100629 [54:19<25:20, 20.75it/s]

 69%|██████▊   | 69094/100629 [54:19<29:41, 17.70it/s]

 69%|██████▊   | 69096/100629 [54:19<31:30, 16.68it/s]

 69%|██████▊   | 69099/100629 [54:19<28:57, 18.15it/s]

 69%|██████▊   | 69102/100629 [54:19<27:37, 19.02it/s]

 69%|██████▊   | 69104/100629 [54:19<28:11, 18.64it/s]

 69%|██████▊   | 69106/100629 [54:19<31:32, 16.66it/s]

 69%|██████▊   | 69108/100629 [54:20<32:32, 16.14it/s]

 69%|██████▊   | 69112/100629 [54:20<27:12, 19.31it/s]

 69%|██████▊   | 69115/100629 [54:20<26:09, 20.08it/s]

 69%|██████▊   | 69118/100629 [54:20<25:23, 20.68it/s]

 69%|██████▊   | 69121/100629 [54:20<34:18, 15.30it/s]

 69%|██████▊   | 69124/100629 [54:20<29:29, 17.81it/s]

 69%|██████▊   | 69127/100629 [54:21<31:06, 16.88it/s]

 69%|██████▊   | 69129/100629 [54:21<34:11, 15.35it/s]

 69%|██████▊   | 69132/100629 [54:21<33:28, 15.68it/s]

 69%|██████▊   | 69134/100629 [54:21<33:38, 15.60it/s]

 69%|██████▊   | 69137/100629 [54:21<35:26, 14.81it/s]

 69%|██████▊   | 69139/100629 [54:21<33:24, 15.71it/s]

 69%|██████▊   | 69142/100629 [54:22<28:41, 18.29it/s]

 69%|██████▊   | 69144/100629 [54:22<30:37, 17.14it/s]

 69%|██████▊   | 69146/100629 [54:22<31:15, 16.79it/s]

 69%|██████▊   | 69149/100629 [54:22<32:25, 16.18it/s]

 69%|██████▊   | 69154/100629 [54:22<25:04, 20.93it/s]

 69%|██████▊   | 69157/100629 [54:22<23:55, 21.92it/s]

 69%|██████▊   | 69161/100629 [54:22<23:22, 22.44it/s]

 69%|██████▊   | 69165/100629 [54:23<20:49, 25.18it/s]

 69%|██████▊   | 69169/100629 [54:23<19:34, 26.78it/s]

 69%|██████▊   | 69172/100629 [54:23<19:10, 27.34it/s]

 69%|██████▊   | 69175/100629 [54:23<20:29, 25.59it/s]

 69%|██████▊   | 69178/100629 [54:23<22:51, 22.93it/s]

 69%|██████▊   | 69181/100629 [54:23<28:38, 18.30it/s]

 69%|██████▉   | 69184/100629 [54:24<29:00, 18.06it/s]

 69%|██████▉   | 69187/100629 [54:24<26:44, 19.59it/s]

 69%|██████▉   | 69191/100629 [54:24<22:41, 23.09it/s]

 69%|██████▉   | 69194/100629 [54:24<24:37, 21.28it/s]

 69%|██████▉   | 69197/100629 [54:24<24:31, 21.36it/s]

 69%|██████▉   | 69201/100629 [54:24<20:44, 25.26it/s]

 69%|██████▉   | 69204/100629 [54:24<24:09, 21.69it/s]

 69%|██████▉   | 69207/100629 [54:25<35:35, 14.71it/s]

 69%|██████▉   | 69211/100629 [54:25<29:03, 18.02it/s]

 69%|██████▉   | 69214/100629 [54:25<34:18, 15.26it/s]

 69%|██████▉   | 69217/100629 [54:25<30:55, 16.93it/s]

 69%|██████▉   | 69222/100629 [54:25<25:28, 20.54it/s]

 69%|██████▉   | 69225/100629 [54:26<27:23, 19.11it/s]

 69%|██████▉   | 69228/100629 [54:26<28:22, 18.45it/s]

 69%|██████▉   | 69231/100629 [54:26<27:46, 18.84it/s]

 69%|██████▉   | 69233/100629 [54:26<28:12, 18.55it/s]

 69%|██████▉   | 69235/100629 [54:26<28:25, 18.41it/s]

 69%|██████▉   | 69238/100629 [54:26<25:58, 20.14it/s]

 69%|██████▉   | 69241/100629 [54:26<26:56, 19.42it/s]

 69%|██████▉   | 69243/100629 [54:27<26:53, 19.45it/s]

 69%|██████▉   | 69247/100629 [54:27<23:57, 21.83it/s]

 69%|██████▉   | 69252/100629 [54:27<18:39, 28.03it/s]

 69%|██████▉   | 69256/100629 [54:27<18:10, 28.78it/s]

 69%|██████▉   | 69259/100629 [54:27<20:20, 25.71it/s]

 69%|██████▉   | 69262/100629 [54:27<20:08, 25.96it/s]

 69%|██████▉   | 69265/100629 [54:27<21:32, 24.27it/s]

 69%|██████▉   | 69270/100629 [54:28<20:00, 26.12it/s]

 69%|██████▉   | 69274/100629 [54:28<18:49, 27.75it/s]

 69%|██████▉   | 69277/100629 [54:28<25:32, 20.46it/s]

 69%|██████▉   | 69280/100629 [54:28<28:40, 18.23it/s]

 69%|██████▉   | 69283/100629 [54:28<31:37, 16.52it/s]

 69%|██████▉   | 69286/100629 [54:28<27:41, 18.87it/s]

 69%|██████▉   | 69290/100629 [54:29<24:46, 21.08it/s]

 69%|██████▉   | 69294/100629 [54:29<21:54, 23.84it/s]

 69%|██████▉   | 69298/100629 [54:29<21:05, 24.75it/s]

 69%|██████▉   | 69302/100629 [54:29<20:37, 25.32it/s]

 69%|██████▉   | 69305/100629 [54:29<20:17, 25.73it/s]

 69%|██████▉   | 69308/100629 [54:29<21:06, 24.74it/s]

 69%|██████▉   | 69311/100629 [54:29<24:01, 21.73it/s]

 69%|██████▉   | 69314/100629 [54:30<24:10, 21.59it/s]

 69%|██████▉   | 69317/100629 [54:30<22:55, 22.76it/s]

 69%|██████▉   | 69320/100629 [54:30<22:10, 23.53it/s]

 69%|██████▉   | 69324/100629 [54:30<19:58, 26.12it/s]

 69%|██████▉   | 69327/100629 [54:30<19:48, 26.33it/s]

 69%|██████▉   | 69330/100629 [54:30<21:16, 24.52it/s]

 69%|██████▉   | 69333/100629 [54:30<24:26, 21.34it/s]

 69%|██████▉   | 69336/100629 [54:31<22:42, 22.98it/s]

 69%|██████▉   | 69339/100629 [54:31<22:08, 23.55it/s]

 69%|██████▉   | 69342/100629 [54:31<23:51, 21.86it/s]

 69%|██████▉   | 69346/100629 [54:31<22:18, 23.37it/s]

 69%|██████▉   | 69350/100629 [54:31<19:26, 26.82it/s]

 69%|██████▉   | 69353/100629 [54:31<21:59, 23.71it/s]

 69%|██████▉   | 69357/100629 [54:31<20:59, 24.83it/s]

 69%|██████▉   | 69361/100629 [54:31<19:27, 26.78it/s]

 69%|██████▉   | 69364/100629 [54:32<20:59, 24.82it/s]

 69%|██████▉   | 69368/100629 [54:32<21:28, 24.26it/s]

 69%|██████▉   | 69372/100629 [54:32<22:02, 23.63it/s]

 69%|██████▉   | 69375/100629 [54:32<25:21, 20.54it/s]

 69%|██████▉   | 69379/100629 [54:32<21:58, 23.70it/s]

 69%|██████▉   | 69382/100629 [54:32<22:25, 23.22it/s]

 69%|██████▉   | 69386/100629 [54:33<20:52, 24.95it/s]

 69%|██████▉   | 69389/100629 [54:33<22:36, 23.04it/s]

 69%|██████▉   | 69392/100629 [54:33<26:09, 19.90it/s]

 69%|██████▉   | 69396/100629 [54:33<22:11, 23.46it/s]

 69%|██████▉   | 69400/100629 [54:33<19:51, 26.21it/s]

 69%|██████▉   | 69403/100629 [54:33<25:22, 20.50it/s]

 69%|██████▉   | 69406/100629 [54:34<30:57, 16.81it/s]

 69%|██████▉   | 69410/100629 [54:34<25:27, 20.44it/s]

 69%|██████▉   | 69413/100629 [54:34<26:40, 19.50it/s]

 69%|██████▉   | 69416/100629 [54:34<25:22, 20.50it/s]

 69%|██████▉   | 69419/100629 [54:34<31:38, 16.44it/s]

 69%|██████▉   | 69422/100629 [54:34<28:15, 18.40it/s]

 69%|██████▉   | 69425/100629 [54:35<27:46, 18.73it/s]

 69%|██████▉   | 69428/100629 [54:35<25:28, 20.42it/s]

 69%|██████▉   | 69431/100629 [54:35<26:04, 19.94it/s]

 69%|██████▉   | 69434/100629 [54:35<25:38, 20.28it/s]

 69%|██████▉   | 69437/100629 [54:35<24:35, 21.14it/s]

 69%|██████▉   | 69441/100629 [54:35<21:32, 24.13it/s]

 69%|██████▉   | 69444/100629 [54:35<22:41, 22.91it/s]

 69%|██████▉   | 69448/100629 [54:36<22:04, 23.55it/s]

 69%|██████▉   | 69451/100629 [54:36<29:18, 17.73it/s]

 69%|██████▉   | 69454/100629 [54:36<26:47, 19.40it/s]

 69%|██████▉   | 69458/100629 [54:36<23:51, 21.78it/s]

 69%|██████▉   | 69461/100629 [54:36<26:56, 19.28it/s]

 69%|██████▉   | 69464/100629 [54:36<25:24, 20.44it/s]

 69%|██████▉   | 69467/100629 [54:37<25:19, 20.51it/s]

 69%|██████▉   | 69470/100629 [54:37<26:57, 19.27it/s]

 69%|██████▉   | 69473/100629 [54:37<29:24, 17.65it/s]

 69%|██████▉   | 69475/100629 [54:37<35:45, 14.52it/s]

 69%|██████▉   | 69477/100629 [54:37<34:11, 15.19it/s]

 69%|██████▉   | 69480/100629 [54:37<32:08, 16.16it/s]

 69%|██████▉   | 69482/100629 [54:38<32:41, 15.88it/s]

 69%|██████▉   | 69485/100629 [54:38<29:18, 17.71it/s]

 69%|██████▉   | 69491/100629 [54:38<25:22, 20.46it/s]

 69%|██████▉   | 69494/100629 [54:38<25:07, 20.65it/s]

 69%|██████▉   | 69497/100629 [54:38<24:09, 21.48it/s]

 69%|██████▉   | 69500/100629 [54:38<24:53, 20.85it/s]

 69%|██████▉   | 69503/100629 [54:39<23:13, 22.33it/s]

 69%|██████▉   | 69506/100629 [54:39<23:17, 22.28it/s]

 69%|██████▉   | 69511/100629 [54:39<19:56, 26.00it/s]

 69%|██████▉   | 69515/100629 [54:39<19:20, 26.82it/s]

 69%|██████▉   | 69518/100629 [54:39<20:26, 25.36it/s]

 69%|██████▉   | 69521/100629 [54:39<20:19, 25.50it/s]

 69%|██████▉   | 69525/100629 [54:39<19:12, 26.99it/s]

 69%|██████▉   | 69530/100629 [54:39<17:02, 30.40it/s]

 69%|██████▉   | 69534/100629 [54:40<20:38, 25.11it/s]

 69%|██████▉   | 69538/100629 [54:40<20:02, 25.86it/s]

 69%|██████▉   | 69541/100629 [54:40<22:00, 23.54it/s]

 69%|██████▉   | 69544/100629 [54:40<22:20, 23.18it/s]

 69%|██████▉   | 69548/100629 [54:40<20:14, 25.60it/s]

 69%|██████▉   | 69551/100629 [54:40<23:04, 22.45it/s]

 69%|██████▉   | 69554/100629 [54:41<23:07, 22.40it/s]

 69%|██████▉   | 69557/100629 [54:41<21:36, 23.97it/s]

 69%|██████▉   | 69560/100629 [54:41<23:27, 22.08it/s]

 69%|██████▉   | 69563/100629 [54:41<22:56, 22.57it/s]

 69%|██████▉   | 69566/100629 [54:41<28:18, 18.29it/s]

 69%|██████▉   | 69570/100629 [54:41<23:40, 21.86it/s]

 69%|██████▉   | 69573/100629 [54:41<24:41, 20.97it/s]

 69%|██████▉   | 69577/100629 [54:42<20:38, 25.08it/s]

 69%|██████▉   | 69581/100629 [54:42<18:58, 27.28it/s]

 69%|██████▉   | 69584/100629 [54:42<19:41, 26.28it/s]

 69%|██████▉   | 69587/100629 [54:42<23:04, 22.43it/s]

 69%|██████▉   | 69590/100629 [54:42<23:03, 22.43it/s]

 69%|██████▉   | 69593/100629 [54:42<25:33, 20.24it/s]

 69%|██████▉   | 69596/100629 [54:42<23:10, 22.32it/s]

 69%|██████▉   | 69599/100629 [54:43<23:53, 21.65it/s]

 69%|██████▉   | 69604/100629 [54:43<20:46, 24.88it/s]

 69%|██████▉   | 69609/100629 [54:43<17:48, 29.04it/s]

 69%|██████▉   | 69613/100629 [54:43<18:09, 28.46it/s]

 69%|██████▉   | 69616/100629 [54:43<20:22, 25.38it/s]

 69%|██████▉   | 69620/100629 [54:43<19:09, 26.97it/s]

 69%|██████▉   | 69623/100629 [54:43<23:03, 22.41it/s]

 69%|██████▉   | 69627/100629 [54:44<20:11, 25.58it/s]

 69%|██████▉   | 69630/100629 [54:44<22:06, 23.37it/s]

 69%|██████▉   | 69633/100629 [54:44<23:08, 22.33it/s]

 69%|██████▉   | 69637/100629 [54:44<22:59, 22.47it/s]

 69%|██████▉   | 69640/100629 [54:44<22:27, 22.99it/s]

 69%|██████▉   | 69643/100629 [54:44<21:49, 23.67it/s]

 69%|██████▉   | 69646/100629 [54:45<25:20, 20.37it/s]

 69%|██████▉   | 69650/100629 [54:45<21:19, 24.21it/s]

 69%|██████▉   | 69653/100629 [54:45<21:36, 23.89it/s]

 69%|██████▉   | 69656/100629 [54:45<25:05, 20.58it/s]

 69%|██████▉   | 69660/100629 [54:45<23:53, 21.61it/s]

 69%|██████▉   | 69663/100629 [54:45<25:45, 20.04it/s]

 69%|██████▉   | 69667/100629 [54:45<22:57, 22.47it/s]

 69%|██████▉   | 69671/100629 [54:46<21:19, 24.20it/s]

 69%|██████▉   | 69674/100629 [54:46<27:43, 18.61it/s]

 69%|██████▉   | 69678/100629 [54:46<23:49, 21.66it/s]

 69%|██████▉   | 69681/100629 [54:46<23:52, 21.61it/s]

 69%|██████▉   | 69684/100629 [54:46<25:54, 19.91it/s]

 69%|██████▉   | 69687/100629 [54:46<25:39, 20.09it/s]

 69%|██████▉   | 69690/100629 [54:47<23:37, 21.83it/s]

 69%|██████▉   | 69693/100629 [54:47<24:54, 20.70it/s]

 69%|██████▉   | 69696/100629 [54:47<27:16, 18.91it/s]

 69%|██████▉   | 69699/100629 [54:47<25:14, 20.42it/s]

 69%|██████▉   | 69702/100629 [54:47<24:07, 21.36it/s]

 69%|██████▉   | 69705/100629 [54:47<24:08, 21.35it/s]

 69%|██████▉   | 69708/100629 [54:47<26:54, 19.15it/s]

 69%|██████▉   | 69712/100629 [54:48<24:36, 20.94it/s]

 69%|██████▉   | 69715/100629 [54:48<23:43, 21.72it/s]

 69%|██████▉   | 69718/100629 [54:48<25:16, 20.38it/s]

 69%|██████▉   | 69721/100629 [54:48<27:45, 18.56it/s]

 69%|██████▉   | 69724/100629 [54:48<25:06, 20.51it/s]

 69%|██████▉   | 69727/100629 [54:49<32:23, 15.90it/s]

 69%|██████▉   | 69729/100629 [54:49<31:44, 16.23it/s]

 69%|██████▉   | 69732/100629 [54:49<27:37, 18.64it/s]

 69%|██████▉   | 69735/100629 [54:49<27:43, 18.57it/s]

 69%|██████▉   | 69738/100629 [54:49<28:44, 17.91it/s]

 69%|██████▉   | 69740/100629 [54:49<31:03, 16.58it/s]

 69%|██████▉   | 69743/100629 [54:49<31:27, 16.37it/s]

 69%|██████▉   | 69746/100629 [54:50<29:49, 17.26it/s]

 69%|██████▉   | 69748/100629 [54:50<34:47, 14.80it/s]

 69%|██████▉   | 69750/100629 [54:50<37:11, 13.84it/s]

 69%|██████▉   | 69753/100629 [54:50<33:29, 15.37it/s]

 69%|██████▉   | 69756/100629 [54:50<29:56, 17.18it/s]

 69%|██████▉   | 69759/100629 [54:50<26:12, 19.63it/s]

 69%|██████▉   | 69762/100629 [54:51<25:43, 20.00it/s]

 69%|██████▉   | 69765/100629 [54:51<26:47, 19.20it/s]

 69%|██████▉   | 69768/100629 [54:51<27:40, 18.58it/s]

 69%|██████▉   | 69770/100629 [54:51<28:08, 18.28it/s]

 69%|██████▉   | 69773/100629 [54:51<26:32, 19.37it/s]

 69%|██████▉   | 69775/100629 [54:51<33:26, 15.37it/s]

 69%|██████▉   | 69778/100629 [54:51<29:39, 17.33it/s]

 69%|██████▉   | 69781/100629 [54:52<32:38, 15.75it/s]

 69%|██████▉   | 69785/100629 [54:52<27:28, 18.71it/s]

 69%|██████▉   | 69787/100629 [54:52<29:23, 17.49it/s]

 69%|██████▉   | 69789/100629 [54:52<35:55, 14.31it/s]

 69%|██████▉   | 69793/100629 [54:52<26:45, 19.21it/s]

 69%|██████▉   | 69797/100629 [54:52<24:53, 20.64it/s]

 69%|██████▉   | 69800/100629 [54:53<27:40, 18.57it/s]

 69%|██████▉   | 69803/100629 [54:53<24:38, 20.84it/s]

 69%|██████▉   | 69806/100629 [54:53<28:56, 17.75it/s]

 69%|██████▉   | 69809/100629 [54:53<28:25, 18.07it/s]

 69%|██████▉   | 69811/100629 [54:53<29:42, 17.29it/s]

 69%|██████▉   | 69813/100629 [54:53<34:54, 14.71it/s]

 69%|██████▉   | 69815/100629 [54:54<40:57, 12.54it/s]

 69%|██████▉   | 69819/100629 [54:54<32:20, 15.87it/s]

 69%|██████▉   | 69822/100629 [54:54<28:51, 17.79it/s]

 69%|██████▉   | 69825/100629 [54:54<30:27, 16.85it/s]

 69%|██████▉   | 69827/100629 [54:54<30:28, 16.84it/s]

 69%|██████▉   | 69831/100629 [54:54<24:18, 21.12it/s]

 69%|██████▉   | 69834/100629 [54:55<24:36, 20.85it/s]

 69%|██████▉   | 69837/100629 [54:55<22:37, 22.68it/s]

 69%|██████▉   | 69841/100629 [54:55<21:28, 23.89it/s]

 69%|██████▉   | 69846/100629 [54:55<18:55, 27.12it/s]

 69%|██████▉   | 69849/100629 [54:55<20:17, 25.28it/s]

 69%|██████▉   | 69854/100629 [54:55<16:38, 30.83it/s]

 69%|██████▉   | 69858/100629 [54:55<18:27, 27.78it/s]

 69%|██████▉   | 69862/100629 [54:56<18:27, 27.78it/s]

 69%|██████▉   | 69865/100629 [54:56<20:58, 24.44it/s]

 69%|██████▉   | 69869/100629 [54:56<19:17, 26.56it/s]

 69%|██████▉   | 69872/100629 [54:56<18:57, 27.04it/s]

 69%|██████▉   | 69877/100629 [54:56<16:27, 31.15it/s]

 69%|██████▉   | 69881/100629 [54:56<19:19, 26.53it/s]

 69%|██████▉   | 69884/100629 [54:56<19:48, 25.86it/s]

 69%|██████▉   | 69887/100629 [54:57<20:22, 25.15it/s]

 69%|██████▉   | 69890/100629 [54:57<20:16, 25.26it/s]

 69%|██████▉   | 69893/100629 [54:57<22:26, 22.82it/s]

 69%|██████▉   | 69897/100629 [54:57<21:37, 23.69it/s]

 69%|██████▉   | 69900/100629 [54:57<20:51, 24.54it/s]

 69%|██████▉   | 69903/100629 [54:57<19:50, 25.81it/s]

 69%|██████▉   | 69906/100629 [54:57<22:20, 22.92it/s]

 69%|██████▉   | 69909/100629 [54:57<22:58, 22.28it/s]

 69%|██████▉   | 69912/100629 [54:58<21:38, 23.66it/s]

 69%|██████▉   | 69915/100629 [54:58<21:03, 24.31it/s]

 69%|██████▉   | 69918/100629 [54:58<21:14, 24.10it/s]

 69%|██████▉   | 69921/100629 [54:58<20:27, 25.02it/s]

 69%|██████▉   | 69924/100629 [54:58<20:28, 25.00it/s]

 69%|██████▉   | 69927/100629 [54:58<20:55, 24.45it/s]

 69%|██████▉   | 69930/100629 [54:58<22:57, 22.28it/s]

 69%|██████▉   | 69933/100629 [54:58<23:14, 22.00it/s]

 70%|██████▉   | 69938/100629 [54:59<19:53, 25.71it/s]

 70%|██████▉   | 69941/100629 [54:59<22:14, 23.00it/s]

 70%|██████▉   | 69945/100629 [54:59<20:27, 25.00it/s]

 70%|██████▉   | 69948/100629 [54:59<20:42, 24.70it/s]

 70%|██████▉   | 69951/100629 [54:59<21:35, 23.68it/s]

 70%|██████▉   | 69954/100629 [54:59<23:11, 22.04it/s]

 70%|██████▉   | 69958/100629 [55:00<22:10, 23.05it/s]

 70%|██████▉   | 69961/100629 [55:00<21:01, 24.32it/s]

 70%|██████▉   | 69965/100629 [55:00<21:25, 23.86it/s]

 70%|██████▉   | 69968/100629 [55:00<21:27, 23.81it/s]

 70%|██████▉   | 69972/100629 [55:00<19:25, 26.31it/s]

 70%|██████▉   | 69975/100629 [55:00<20:07, 25.38it/s]

 70%|██████▉   | 69979/100629 [55:00<18:57, 26.94it/s]

 70%|██████▉   | 69982/100629 [55:00<19:57, 25.58it/s]

 70%|██████▉   | 69985/100629 [55:01<19:49, 25.75it/s]

 70%|██████▉   | 69990/100629 [55:01<18:31, 27.56it/s]

 70%|██████▉   | 69993/100629 [55:01<21:42, 23.52it/s]

 70%|██████▉   | 69996/100629 [55:01<28:09, 18.13it/s]

 70%|██████▉   | 69999/100629 [55:01<26:22, 19.36it/s]

 70%|██████▉   | 70002/100629 [55:01<27:57, 18.26it/s]

 70%|██████▉   | 70004/100629 [55:02<29:19, 17.40it/s]

 70%|██████▉   | 70007/100629 [55:02<25:42, 19.86it/s]

 70%|██████▉   | 70010/100629 [55:02<23:40, 21.56it/s]

 70%|██████▉   | 70013/100629 [55:02<24:40, 20.68it/s]

 70%|██████▉   | 70016/100629 [55:02<28:22, 17.98it/s]

 70%|██████▉   | 70020/100629 [55:02<24:32, 20.79it/s]

 70%|██████▉   | 70023/100629 [55:03<26:04, 19.56it/s]

 70%|██████▉   | 70026/100629 [55:03<26:56, 18.93it/s]

 70%|██████▉   | 70029/100629 [55:03<27:09, 18.78it/s]

 70%|██████▉   | 70032/100629 [55:03<27:37, 18.46it/s]

 70%|██████▉   | 70034/100629 [55:03<28:54, 17.64it/s]

 70%|██████▉   | 70036/100629 [55:03<31:06, 16.39it/s]

 70%|██████▉   | 70038/100629 [55:03<29:56, 17.02it/s]

 70%|██████▉   | 70040/100629 [55:04<29:17, 17.40it/s]

 70%|██████▉   | 70043/100629 [55:04<26:08, 19.51it/s]

 70%|██████▉   | 70048/100629 [55:04<21:54, 23.27it/s]

 70%|██████▉   | 70051/100629 [55:04<23:34, 21.62it/s]

 70%|██████▉   | 70054/100629 [55:04<24:16, 20.99it/s]

 70%|██████▉   | 70057/100629 [55:04<25:26, 20.03it/s]

 70%|██████▉   | 70061/100629 [55:04<22:45, 22.39it/s]

 70%|██████▉   | 70064/100629 [55:05<31:13, 16.32it/s]

 70%|██████▉   | 70066/100629 [55:05<31:17, 16.27it/s]

 70%|██████▉   | 70068/100629 [55:05<33:48, 15.06it/s]

 70%|██████▉   | 70070/100629 [55:05<34:25, 14.79it/s]

 70%|██████▉   | 70073/100629 [55:05<32:47, 15.53it/s]

 70%|██████▉   | 70076/100629 [55:05<29:08, 17.48it/s]

 70%|██████▉   | 70078/100629 [55:06<31:00, 16.42it/s]

 70%|██████▉   | 70080/100629 [55:06<33:10, 15.34it/s]

 70%|██████▉   | 70082/100629 [55:06<32:29, 15.67it/s]

 70%|██████▉   | 70085/100629 [55:06<30:48, 16.52it/s]

 70%|██████▉   | 70088/100629 [55:06<30:38, 16.62it/s]

 70%|██████▉   | 70090/100629 [55:06<30:23, 16.75it/s]

 70%|██████▉   | 70092/100629 [55:07<34:57, 14.56it/s]

 70%|██████▉   | 70094/100629 [55:07<32:38, 15.59it/s]

 70%|██████▉   | 70098/100629 [55:07<24:04, 21.14it/s]

 70%|██████▉   | 70101/100629 [55:07<26:12, 19.42it/s]

 70%|██████▉   | 70104/100629 [55:07<26:31, 19.18it/s]

 70%|██████▉   | 70107/100629 [55:07<27:51, 18.26it/s]

 70%|██████▉   | 70110/100629 [55:07<27:08, 18.74it/s]

 70%|██████▉   | 70112/100629 [55:08<30:18, 16.78it/s]

 70%|██████▉   | 70114/100629 [55:08<32:01, 15.88it/s]

 70%|██████▉   | 70116/100629 [55:08<32:58, 15.42it/s]

 70%|██████▉   | 70120/100629 [55:08<25:35, 19.87it/s]

 70%|██████▉   | 70123/100629 [55:08<26:20, 19.30it/s]

 70%|██████▉   | 70125/100629 [55:08<30:34, 16.63it/s]

 70%|██████▉   | 70128/100629 [55:09<28:33, 17.80it/s]

 70%|██████▉   | 70130/100629 [55:09<29:09, 17.43it/s]

 70%|██████▉   | 70133/100629 [55:09<30:01, 16.93it/s]

 70%|██████▉   | 70135/100629 [55:09<29:20, 17.33it/s]

 70%|██████▉   | 70137/100629 [55:09<29:57, 16.96it/s]

 70%|██████▉   | 70141/100629 [55:09<22:44, 22.35it/s]

 70%|██████▉   | 70144/100629 [55:09<22:14, 22.84it/s]

 70%|██████▉   | 70147/100629 [55:09<21:36, 23.51it/s]

 70%|██████▉   | 70150/100629 [55:09<20:26, 24.84it/s]

 70%|██████▉   | 70154/100629 [55:10<18:01, 28.18it/s]

 70%|██████▉   | 70157/100629 [55:10<18:50, 26.95it/s]

 70%|██████▉   | 70160/100629 [55:10<19:21, 26.24it/s]

 70%|██████▉   | 70164/100629 [55:10<21:40, 23.43it/s]

 70%|██████▉   | 70167/100629 [55:10<25:24, 19.98it/s]

 70%|██████▉   | 70170/100629 [55:10<25:22, 20.00it/s]

 70%|██████▉   | 70173/100629 [55:11<28:27, 17.84it/s]

 70%|██████▉   | 70177/100629 [55:11<23:33, 21.54it/s]

 70%|██████▉   | 70180/100629 [55:11<23:39, 21.46it/s]

 70%|██████▉   | 70183/100629 [55:11<23:41, 21.41it/s]

 70%|██████▉   | 70186/100629 [55:11<22:37, 22.43it/s]

 70%|██████▉   | 70189/100629 [55:11<23:54, 21.22it/s]

 70%|██████▉   | 70192/100629 [55:11<22:30, 22.54it/s]

 70%|██████▉   | 70195/100629 [55:12<26:05, 19.44it/s]

 70%|██████▉   | 70199/100629 [55:12<22:57, 22.08it/s]

 70%|██████▉   | 70203/100629 [55:12<22:38, 22.40it/s]

 70%|██████▉   | 70206/100629 [55:12<23:30, 21.57it/s]

 70%|██████▉   | 70211/100629 [55:12<18:31, 27.37it/s]

 70%|██████▉   | 70214/100629 [55:12<21:03, 24.08it/s]

 70%|██████▉   | 70218/100629 [55:13<21:55, 23.12it/s]

 70%|██████▉   | 70221/100629 [55:13<21:37, 23.43it/s]

 70%|██████▉   | 70226/100629 [55:13<17:26, 29.06it/s]

 70%|██████▉   | 70230/100629 [55:13<18:56, 26.75it/s]

 70%|██████▉   | 70233/100629 [55:13<20:38, 24.54it/s]

 70%|██████▉   | 70237/100629 [55:13<19:21, 26.17it/s]

 70%|██████▉   | 70240/100629 [55:13<19:22, 26.14it/s]

 70%|██████▉   | 70243/100629 [55:13<19:28, 26.01it/s]

 70%|██████▉   | 70246/100629 [55:14<23:00, 22.00it/s]

 70%|██████▉   | 70249/100629 [55:14<23:53, 21.20it/s]

 70%|██████▉   | 70252/100629 [55:14<22:57, 22.06it/s]

 70%|██████▉   | 70255/100629 [55:14<24:30, 20.65it/s]

 70%|██████▉   | 70258/100629 [55:14<22:31, 22.47it/s]

 70%|██████▉   | 70261/100629 [55:14<24:50, 20.38it/s]

 70%|██████▉   | 70264/100629 [55:15<24:26, 20.71it/s]

 70%|██████▉   | 70267/100629 [55:15<22:52, 22.12it/s]

 70%|██████▉   | 70272/100629 [55:15<20:59, 24.10it/s]

 70%|██████▉   | 70276/100629 [55:15<20:08, 25.11it/s]

 70%|██████▉   | 70279/100629 [55:15<21:17, 23.76it/s]

 70%|██████▉   | 70282/100629 [55:15<22:08, 22.84it/s]

 70%|██████▉   | 70285/100629 [55:15<23:55, 21.13it/s]

 70%|██████▉   | 70289/100629 [55:16<22:42, 22.26it/s]

 70%|██████▉   | 70292/100629 [55:16<24:31, 20.62it/s]

 70%|██████▉   | 70295/100629 [55:16<22:52, 22.11it/s]

 70%|██████▉   | 70298/100629 [55:16<21:46, 23.22it/s]

 70%|██████▉   | 70301/100629 [55:16<21:58, 23.00it/s]

 70%|██████▉   | 70304/100629 [55:16<24:04, 20.99it/s]

 70%|██████▉   | 70307/100629 [55:16<23:44, 21.28it/s]

 70%|██████▉   | 70310/100629 [55:17<23:21, 21.63it/s]

 70%|██████▉   | 70313/100629 [55:17<29:26, 17.17it/s]

 70%|██████▉   | 70315/100629 [55:17<30:41, 16.46it/s]

 70%|██████▉   | 70319/100629 [55:17<25:15, 20.00it/s]

 70%|██████▉   | 70322/100629 [55:17<26:39, 18.95it/s]

 70%|██████▉   | 70325/100629 [55:17<25:26, 19.86it/s]

 70%|██████▉   | 70328/100629 [55:18<24:34, 20.55it/s]

 70%|██████▉   | 70331/100629 [55:18<27:43, 18.21it/s]

 70%|██████▉   | 70335/100629 [55:18<24:30, 20.59it/s]

 70%|██████▉   | 70338/100629 [55:18<23:26, 21.54it/s]

 70%|██████▉   | 70341/100629 [55:18<26:38, 18.95it/s]

 70%|██████▉   | 70345/100629 [55:18<21:44, 23.21it/s]

 70%|██████▉   | 70348/100629 [55:18<21:08, 23.88it/s]

 70%|██████▉   | 70351/100629 [55:19<23:56, 21.07it/s]

 70%|██████▉   | 70354/100629 [55:19<24:40, 20.44it/s]

 70%|██████▉   | 70357/100629 [55:19<24:06, 20.92it/s]

 70%|██████▉   | 70360/100629 [55:19<24:24, 20.66it/s]

 70%|██████▉   | 70363/100629 [55:19<23:36, 21.36it/s]

 70%|██████▉   | 70366/100629 [55:19<26:17, 19.18it/s]

 70%|██████▉   | 70368/100629 [55:20<26:38, 18.93it/s]

 70%|██████▉   | 70371/100629 [55:20<25:15, 19.96it/s]

 70%|██████▉   | 70374/100629 [55:20<23:59, 21.02it/s]

 70%|██████▉   | 70377/100629 [55:20<22:19, 22.59it/s]

 70%|██████▉   | 70380/100629 [55:20<21:26, 23.51it/s]

 70%|██████▉   | 70383/100629 [55:20<21:02, 23.96it/s]

 70%|██████▉   | 70387/100629 [55:20<18:30, 27.23it/s]

 70%|██████▉   | 70390/100629 [55:20<18:03, 27.90it/s]

 70%|██████▉   | 70395/100629 [55:20<17:21, 29.04it/s]

 70%|██████▉   | 70398/100629 [55:21<19:31, 25.81it/s]

 70%|██████▉   | 70401/100629 [55:21<24:22, 20.68it/s]

 70%|██████▉   | 70404/100629 [55:21<26:33, 18.97it/s]

 70%|██████▉   | 70407/100629 [55:21<24:23, 20.66it/s]

 70%|██████▉   | 70410/100629 [55:21<23:40, 21.28it/s]

 70%|██████▉   | 70413/100629 [55:21<24:17, 20.73it/s]

 70%|██████▉   | 70418/100629 [55:22<19:17, 26.09it/s]

 70%|██████▉   | 70421/100629 [55:22<19:38, 25.63it/s]

 70%|██████▉   | 70424/100629 [55:22<22:56, 21.94it/s]

 70%|██████▉   | 70427/100629 [55:22<22:48, 22.08it/s]

 70%|██████▉   | 70430/100629 [55:22<29:40, 16.96it/s]

 70%|██████▉   | 70433/100629 [55:22<28:38, 17.57it/s]

 70%|██████▉   | 70435/100629 [55:23<29:09, 17.26it/s]

 70%|██████▉   | 70437/100629 [55:23<29:51, 16.85it/s]

 70%|███████   | 70441/100629 [55:23<23:29, 21.42it/s]

 70%|███████   | 70444/100629 [55:23<25:07, 20.03it/s]

 70%|███████   | 70447/100629 [55:23<24:10, 20.81it/s]

 70%|███████   | 70450/100629 [55:23<22:44, 22.12it/s]

 70%|███████   | 70453/100629 [55:23<21:31, 23.37it/s]

 70%|███████   | 70456/100629 [55:23<20:17, 24.79it/s]

 70%|███████   | 70459/100629 [55:24<22:09, 22.69it/s]

 70%|███████   | 70463/100629 [55:24<19:18, 26.04it/s]

 70%|███████   | 70466/100629 [55:24<21:25, 23.46it/s]

 70%|███████   | 70471/100629 [55:24<19:44, 25.45it/s]

 70%|███████   | 70476/100629 [55:24<16:14, 30.96it/s]

 70%|███████   | 70480/100629 [55:24<23:13, 21.64it/s]

 70%|███████   | 70483/100629 [55:25<21:54, 22.93it/s]

 70%|███████   | 70486/100629 [55:25<21:45, 23.10it/s]

 70%|███████   | 70491/100629 [55:25<19:04, 26.33it/s]

 70%|███████   | 70494/100629 [55:25<19:59, 25.12it/s]

 70%|███████   | 70497/100629 [55:25<21:25, 23.45it/s]

 70%|███████   | 70500/100629 [55:25<22:06, 22.72it/s]

 70%|███████   | 70503/100629 [55:25<23:26, 21.43it/s]

 70%|███████   | 70506/100629 [55:26<26:40, 18.82it/s]

 70%|███████   | 70508/100629 [55:26<33:50, 14.84it/s]

 70%|███████   | 70510/100629 [55:26<33:57, 14.79it/s]

 70%|███████   | 70512/100629 [55:26<38:09, 13.15it/s]

 70%|███████   | 70515/100629 [55:26<31:34, 15.89it/s]

 70%|███████   | 70517/100629 [55:27<35:11, 14.26it/s]

 70%|███████   | 70519/100629 [55:27<32:40, 15.36it/s]

 70%|███████   | 70522/100629 [55:27<26:57, 18.61it/s]

 70%|███████   | 70525/100629 [55:27<24:04, 20.84it/s]

 70%|███████   | 70528/100629 [55:27<27:09, 18.47it/s]

 70%|███████   | 70531/100629 [55:27<29:51, 16.80it/s]

 70%|███████   | 70533/100629 [55:27<28:52, 17.37it/s]

 70%|███████   | 70535/100629 [55:28<31:42, 15.82it/s]

 70%|███████   | 70539/100629 [55:28<25:22, 19.76it/s]

 70%|███████   | 70542/100629 [55:28<24:56, 20.11it/s]

 70%|███████   | 70545/100629 [55:28<23:04, 21.73it/s]

 70%|███████   | 70549/100629 [55:28<19:20, 25.92it/s]

 70%|███████   | 70552/100629 [55:28<18:52, 26.56it/s]

 70%|███████   | 70555/100629 [55:28<18:57, 26.44it/s]

 70%|███████   | 70558/100629 [55:28<19:28, 25.73it/s]

 70%|███████   | 70561/100629 [55:29<22:22, 22.40it/s]

 70%|███████   | 70564/100629 [55:29<24:52, 20.14it/s]

 70%|███████   | 70568/100629 [55:29<21:06, 23.74it/s]

 70%|███████   | 70571/100629 [55:29<22:24, 22.35it/s]

 70%|███████   | 70574/100629 [55:29<24:28, 20.47it/s]

 70%|███████   | 70577/100629 [55:29<23:05, 21.70it/s]

 70%|███████   | 70581/100629 [55:29<20:51, 24.02it/s]

 70%|███████   | 70585/100629 [55:30<24:08, 20.75it/s]

 70%|███████   | 70588/100629 [55:30<26:04, 19.20it/s]

 70%|███████   | 70592/100629 [55:30<24:23, 20.52it/s]

 70%|███████   | 70597/100629 [55:30<20:16, 24.69it/s]

 70%|███████   | 70600/100629 [55:30<22:53, 21.87it/s]

 70%|███████   | 70604/100629 [55:30<21:51, 22.89it/s]

 70%|███████   | 70607/100629 [55:31<21:23, 23.40it/s]

 70%|███████   | 70610/100629 [55:31<26:44, 18.71it/s]

 70%|███████   | 70613/100629 [55:31<25:53, 19.32it/s]

 70%|███████   | 70616/100629 [55:31<23:50, 20.98it/s]

 70%|███████   | 70619/100629 [55:31<23:06, 21.64it/s]

 70%|███████   | 70622/100629 [55:31<21:14, 23.54it/s]

 70%|███████   | 70626/100629 [55:31<19:52, 25.15it/s]

 70%|███████   | 70630/100629 [55:32<17:56, 27.87it/s]

 70%|███████   | 70633/100629 [55:32<20:57, 23.86it/s]

 70%|███████   | 70636/100629 [55:32<21:41, 23.05it/s]

 70%|███████   | 70639/100629 [55:32<21:33, 23.19it/s]

 70%|███████   | 70642/100629 [55:32<20:47, 24.04it/s]

 70%|███████   | 70645/100629 [55:32<21:32, 23.20it/s]

 70%|███████   | 70648/100629 [55:32<20:57, 23.85it/s]

 70%|███████   | 70651/100629 [55:33<19:58, 25.02it/s]

 70%|███████   | 70654/100629 [55:33<20:21, 24.53it/s]

 70%|███████   | 70657/100629 [55:33<23:52, 20.93it/s]

 70%|███████   | 70660/100629 [55:33<21:48, 22.91it/s]

 70%|███████   | 70663/100629 [55:33<22:01, 22.68it/s]

 70%|███████   | 70666/100629 [55:33<21:52, 22.83it/s]

 70%|███████   | 70669/100629 [55:33<22:35, 22.10it/s]

 70%|███████   | 70672/100629 [55:33<21:47, 22.91it/s]

 70%|███████   | 70675/100629 [55:34<21:15, 23.48it/s]

 70%|███████   | 70679/100629 [55:34<20:37, 24.20it/s]

 70%|███████   | 70682/100629 [55:34<23:35, 21.16it/s]

 70%|███████   | 70685/100629 [55:34<24:47, 20.13it/s]

 70%|███████   | 70688/100629 [55:34<24:27, 20.40it/s]

 70%|███████   | 70691/100629 [55:34<22:23, 22.28it/s]

 70%|███████   | 70695/100629 [55:34<19:18, 25.83it/s]

 70%|███████   | 70698/100629 [55:35<20:56, 23.83it/s]

 70%|███████   | 70701/100629 [55:35<24:43, 20.17it/s]

 70%|███████   | 70704/100629 [55:35<26:08, 19.08it/s]

 70%|███████   | 70707/100629 [55:35<30:26, 16.38it/s]

 70%|███████   | 70710/100629 [55:35<27:44, 17.97it/s]

 70%|███████   | 70713/100629 [55:35<25:32, 19.52it/s]

 70%|███████   | 70716/100629 [55:36<29:17, 17.02it/s]

 70%|███████   | 70718/100629 [55:36<30:04, 16.58it/s]

 70%|███████   | 70721/100629 [55:36<29:19, 17.00it/s]

 70%|███████   | 70723/100629 [55:36<31:42, 15.72it/s]

 70%|███████   | 70725/100629 [55:36<32:14, 15.46it/s]

 70%|███████   | 70728/100629 [55:36<27:01, 18.45it/s]

 70%|███████   | 70731/100629 [55:37<25:48, 19.31it/s]

 70%|███████   | 70734/100629 [55:37<28:44, 17.33it/s]

 70%|███████   | 70736/100629 [55:37<31:00, 16.07it/s]

 70%|███████   | 70738/100629 [55:37<29:39, 16.80it/s]

 70%|███████   | 70740/100629 [55:37<31:43, 15.70it/s]

 70%|███████   | 70743/100629 [55:37<27:05, 18.39it/s]

 70%|███████   | 70748/100629 [55:37<20:58, 23.75it/s]

 70%|███████   | 70751/100629 [55:38<22:09, 22.46it/s]

 70%|███████   | 70755/100629 [55:38<19:15, 25.84it/s]

 70%|███████   | 70759/100629 [55:38<17:30, 28.43it/s]

 70%|███████   | 70762/100629 [55:38<21:12, 23.47it/s]

 70%|███████   | 70765/100629 [55:38<22:03, 22.56it/s]

 70%|███████   | 70768/100629 [55:38<21:03, 23.63it/s]

 70%|███████   | 70771/100629 [55:38<24:02, 20.70it/s]

 70%|███████   | 70774/100629 [55:39<25:24, 19.58it/s]

 70%|███████   | 70777/100629 [55:39<27:59, 17.78it/s]

 70%|███████   | 70780/100629 [55:39<27:10, 18.31it/s]

 70%|███████   | 70783/100629 [55:39<24:10, 20.57it/s]

 70%|███████   | 70786/100629 [55:39<24:14, 20.52it/s]

 70%|███████   | 70789/100629 [55:39<28:40, 17.35it/s]

 70%|███████   | 70792/100629 [55:40<26:10, 19.00it/s]

 70%|███████   | 70795/100629 [55:40<24:26, 20.35it/s]

 70%|███████   | 70798/100629 [55:40<23:31, 21.13it/s]

 70%|███████   | 70801/100629 [55:40<31:21, 15.85it/s]

 70%|███████   | 70804/100629 [55:40<29:32, 16.83it/s]

 70%|███████   | 70810/100629 [55:40<20:37, 24.09it/s]

 70%|███████   | 70813/100629 [55:41<19:54, 24.96it/s]

 70%|███████   | 70817/100629 [55:41<18:17, 27.17it/s]

 70%|███████   | 70820/100629 [55:41<18:55, 26.24it/s]

 70%|███████   | 70823/100629 [55:41<19:37, 25.30it/s]

 70%|███████   | 70828/100629 [55:41<16:04, 30.91it/s]

 70%|███████   | 70832/100629 [55:41<16:55, 29.33it/s]

 70%|███████   | 70836/100629 [55:41<18:03, 27.50it/s]

 70%|███████   | 70839/100629 [55:41<19:21, 25.66it/s]

 70%|███████   | 70842/100629 [55:42<21:42, 22.87it/s]

 70%|███████   | 70845/100629 [55:42<23:21, 21.25it/s]

 70%|███████   | 70849/100629 [55:42<19:55, 24.91it/s]

 70%|███████   | 70853/100629 [55:42<20:20, 24.40it/s]

 70%|███████   | 70856/100629 [55:42<22:51, 21.70it/s]

 70%|███████   | 70859/100629 [55:42<21:43, 22.84it/s]

 70%|███████   | 70862/100629 [55:42<20:20, 24.40it/s]

 70%|███████   | 70865/100629 [55:43<22:07, 22.43it/s]

 70%|███████   | 70869/100629 [55:43<22:54, 21.66it/s]

 70%|███████   | 70874/100629 [55:43<19:59, 24.81it/s]

 70%|███████   | 70878/100629 [55:43<17:55, 27.66it/s]

 70%|███████   | 70881/100629 [55:43<18:00, 27.53it/s]

 70%|███████   | 70884/100629 [55:43<21:40, 22.87it/s]

 70%|███████   | 70887/100629 [55:44<23:31, 21.07it/s]

 70%|███████   | 70890/100629 [55:44<22:10, 22.35it/s]

 70%|███████   | 70894/100629 [55:44<23:44, 20.88it/s]

 70%|███████   | 70898/100629 [55:44<22:17, 22.23it/s]

 70%|███████   | 70901/100629 [55:44<23:40, 20.93it/s]

 70%|███████   | 70904/100629 [55:44<25:16, 19.60it/s]

 70%|███████   | 70907/100629 [55:45<25:23, 19.51it/s]

 70%|███████   | 70911/100629 [55:45<21:17, 23.26it/s]

 70%|███████   | 70914/100629 [55:45<23:40, 20.91it/s]

 70%|███████   | 70918/100629 [55:45<21:36, 22.91it/s]

 70%|███████   | 70921/100629 [55:45<24:03, 20.58it/s]

 70%|███████   | 70924/100629 [55:45<26:58, 18.36it/s]

 70%|███████   | 70927/100629 [55:45<24:15, 20.40it/s]

 70%|███████   | 70931/100629 [55:46<22:00, 22.49it/s]

 70%|███████   | 70934/100629 [55:46<21:45, 22.74it/s]

 70%|███████   | 70937/100629 [55:46<25:40, 19.28it/s]

 70%|███████   | 70940/100629 [55:46<28:14, 17.52it/s]

 70%|███████   | 70943/100629 [55:46<25:58, 19.04it/s]

 71%|███████   | 70947/100629 [55:46<21:51, 22.63it/s]

 71%|███████   | 70950/100629 [55:47<22:18, 22.17it/s]

 71%|███████   | 70953/100629 [55:47<21:12, 23.32it/s]

 71%|███████   | 70956/100629 [55:47<23:07, 21.39it/s]

 71%|███████   | 70960/100629 [55:47<23:10, 21.33it/s]

 71%|███████   | 70964/100629 [55:47<21:21, 23.14it/s]

 71%|███████   | 70967/100629 [55:47<26:00, 19.01it/s]

 71%|███████   | 70970/100629 [55:48<25:59, 19.02it/s]

 71%|███████   | 70973/100629 [55:48<26:55, 18.35it/s]

 71%|███████   | 70976/100629 [55:48<25:56, 19.06it/s]

 71%|███████   | 70978/100629 [55:48<27:22, 18.05it/s]

 71%|███████   | 70981/100629 [55:48<25:03, 19.72it/s]

 71%|███████   | 70984/100629 [55:48<28:45, 17.18it/s]

 71%|███████   | 70987/100629 [55:49<29:02, 17.01it/s]

 71%|███████   | 70991/100629 [55:49<25:38, 19.27it/s]

 71%|███████   | 70994/100629 [55:49<24:05, 20.51it/s]

 71%|███████   | 70997/100629 [55:49<23:11, 21.29it/s]

 71%|███████   | 71000/100629 [55:49<27:34, 17.91it/s]

 71%|███████   | 71003/100629 [55:49<25:00, 19.74it/s]

 71%|███████   | 71006/100629 [55:49<23:29, 21.01it/s]

 71%|███████   | 71010/100629 [55:50<20:58, 23.54it/s]

 71%|███████   | 71013/100629 [55:50<20:30, 24.07it/s]

 71%|███████   | 71016/100629 [55:50<19:36, 25.17it/s]

 71%|███████   | 71019/100629 [55:50<20:29, 24.09it/s]

 71%|███████   | 71022/100629 [55:50<21:18, 23.17it/s]

 71%|███████   | 71025/100629 [55:50<20:09, 24.48it/s]

 71%|███████   | 71029/100629 [55:50<20:33, 24.00it/s]

 71%|███████   | 71032/100629 [55:51<23:40, 20.83it/s]

 71%|███████   | 71035/100629 [55:51<23:35, 20.90it/s]

 71%|███████   | 71038/100629 [55:51<22:29, 21.92it/s]

 71%|███████   | 71044/100629 [55:51<17:17, 28.52it/s]

 71%|███████   | 71047/100629 [55:51<18:24, 26.79it/s]

 71%|███████   | 71050/100629 [55:51<19:37, 25.12it/s]

 71%|███████   | 71053/100629 [55:51<22:55, 21.50it/s]

 71%|███████   | 71056/100629 [55:52<21:55, 22.47it/s]

 71%|███████   | 71059/100629 [55:52<22:28, 21.92it/s]

 71%|███████   | 71062/100629 [55:52<20:54, 23.58it/s]

 71%|███████   | 71065/100629 [55:52<23:11, 21.25it/s]

 71%|███████   | 71068/100629 [55:52<24:31, 20.08it/s]

 71%|███████   | 71072/100629 [55:52<22:11, 22.20it/s]

 71%|███████   | 71075/100629 [55:52<24:35, 20.03it/s]

 71%|███████   | 71078/100629 [55:53<23:30, 20.96it/s]

 71%|███████   | 71082/100629 [55:53<20:31, 24.00it/s]

 71%|███████   | 71085/100629 [55:53<24:58, 19.71it/s]

 71%|███████   | 71088/100629 [55:53<25:12, 19.53it/s]

 71%|███████   | 71091/100629 [55:53<23:54, 20.59it/s]

 71%|███████   | 71095/100629 [55:53<20:06, 24.47it/s]

 71%|███████   | 71099/100629 [55:53<17:54, 27.49it/s]

 71%|███████   | 71102/100629 [55:54<19:26, 25.32it/s]

 71%|███████   | 71105/100629 [55:54<25:34, 19.24it/s]

 71%|███████   | 71108/100629 [55:54<24:21, 20.19it/s]

 71%|███████   | 71111/100629 [55:54<24:28, 20.11it/s]

 71%|███████   | 71115/100629 [55:54<24:30, 20.07it/s]

 71%|███████   | 71120/100629 [55:54<20:43, 23.73it/s]

 71%|███████   | 71123/100629 [55:55<22:59, 21.39it/s]

 71%|███████   | 71126/100629 [55:55<26:09, 18.80it/s]

 71%|███████   | 71128/100629 [55:55<26:44, 18.38it/s]

 71%|███████   | 71130/100629 [55:55<26:43, 18.40it/s]

 71%|███████   | 71135/100629 [55:55<24:48, 19.81it/s]

 71%|███████   | 71137/100629 [55:55<26:47, 18.34it/s]

 71%|███████   | 71140/100629 [55:56<26:24, 18.61it/s]

 71%|███████   | 71143/100629 [55:56<24:16, 20.25it/s]

 71%|███████   | 71146/100629 [55:56<23:12, 21.18it/s]

 71%|███████   | 71149/100629 [55:56<22:33, 21.78it/s]

 71%|███████   | 71153/100629 [55:56<19:54, 24.67it/s]

 71%|███████   | 71156/100629 [55:56<19:20, 25.40it/s]

 71%|███████   | 71159/100629 [55:56<19:01, 25.82it/s]

 71%|███████   | 71162/100629 [55:57<22:47, 21.54it/s]

 71%|███████   | 71165/100629 [55:57<21:11, 23.17it/s]

 71%|███████   | 71168/100629 [55:57<22:19, 22.00it/s]

 71%|███████   | 71171/100629 [55:57<22:25, 21.89it/s]

 71%|███████   | 71174/100629 [55:57<23:16, 21.10it/s]

 71%|███████   | 71178/100629 [55:57<21:01, 23.34it/s]

 71%|███████   | 71182/100629 [55:57<18:53, 25.98it/s]

 71%|███████   | 71185/100629 [55:57<19:06, 25.68it/s]

 71%|███████   | 71188/100629 [55:58<21:12, 23.13it/s]

 71%|███████   | 71191/100629 [55:58<21:30, 22.81it/s]

 71%|███████   | 71195/100629 [55:58<18:16, 26.85it/s]

 71%|███████   | 71198/100629 [55:58<20:27, 23.97it/s]

 71%|███████   | 71201/100629 [55:58<26:23, 18.59it/s]

 71%|███████   | 71204/100629 [55:58<24:27, 20.06it/s]

 71%|███████   | 71207/100629 [55:59<29:20, 16.72it/s]

 71%|███████   | 71210/100629 [55:59<27:20, 17.93it/s]

 71%|███████   | 71212/100629 [55:59<32:28, 15.10it/s]

 71%|███████   | 71214/100629 [55:59<35:13, 13.92it/s]

 71%|███████   | 71216/100629 [55:59<33:47, 14.51it/s]

 71%|███████   | 71218/100629 [55:59<33:14, 14.75it/s]

 71%|███████   | 71220/100629 [56:00<36:22, 13.48it/s]

 71%|███████   | 71222/100629 [56:00<35:17, 13.89it/s]

 71%|███████   | 71225/100629 [56:00<31:18, 15.66it/s]

 71%|███████   | 71228/100629 [56:00<26:52, 18.23it/s]

 71%|███████   | 71230/100629 [56:00<28:42, 17.06it/s]

 71%|███████   | 71233/100629 [56:00<25:23, 19.29it/s]

 71%|███████   | 71236/100629 [56:00<24:33, 19.95it/s]

 71%|███████   | 71240/100629 [56:01<21:21, 22.93it/s]

 71%|███████   | 71243/100629 [56:01<22:35, 21.69it/s]

 71%|███████   | 71246/100629 [56:01<24:29, 20.00it/s]

 71%|███████   | 71249/100629 [56:01<22:32, 21.72it/s]

 71%|███████   | 71252/100629 [56:01<28:24, 17.24it/s]

 71%|███████   | 71254/100629 [56:01<29:37, 16.52it/s]

 71%|███████   | 71256/100629 [56:01<29:13, 16.75it/s]

 71%|███████   | 71258/100629 [56:02<28:44, 17.03it/s]

 71%|███████   | 71260/100629 [56:02<28:12, 17.35it/s]

 71%|███████   | 71263/100629 [56:02<25:03, 19.54it/s]

 71%|███████   | 71266/100629 [56:02<23:49, 20.54it/s]

 71%|███████   | 71269/100629 [56:02<22:20, 21.90it/s]

 71%|███████   | 71272/100629 [56:02<25:50, 18.93it/s]

 71%|███████   | 71274/100629 [56:02<29:07, 16.80it/s]

 71%|███████   | 71278/100629 [56:03<24:49, 19.70it/s]

 71%|███████   | 71281/100629 [56:03<22:50, 21.41it/s]

 71%|███████   | 71285/100629 [56:03<21:12, 23.05it/s]

 71%|███████   | 71288/100629 [56:03<21:06, 23.16it/s]

 71%|███████   | 71291/100629 [56:03<21:33, 22.67it/s]

 71%|███████   | 71294/100629 [56:03<21:18, 22.95it/s]

 71%|███████   | 71299/100629 [56:03<18:43, 26.10it/s]

 71%|███████   | 71302/100629 [56:04<20:41, 23.62it/s]

 71%|███████   | 71305/100629 [56:04<20:21, 24.01it/s]

 71%|███████   | 71308/100629 [56:04<20:23, 23.96it/s]

 71%|███████   | 71312/100629 [56:04<18:51, 25.90it/s]

 71%|███████   | 71315/100629 [56:04<23:26, 20.83it/s]

 71%|███████   | 71318/100629 [56:04<22:41, 21.53it/s]

 71%|███████   | 71322/100629 [56:04<22:24, 21.80it/s]

 71%|███████   | 71325/100629 [56:05<22:18, 21.89it/s]

 71%|███████   | 71328/100629 [56:05<24:07, 20.24it/s]

 71%|███████   | 71331/100629 [56:05<27:26, 17.80it/s]

 71%|███████   | 71333/100629 [56:05<27:44, 17.61it/s]

 71%|███████   | 71336/100629 [56:05<26:47, 18.23it/s]

 71%|███████   | 71339/100629 [56:05<24:59, 19.53it/s]

 71%|███████   | 71342/100629 [56:06<24:18, 20.08it/s]

 71%|███████   | 71345/100629 [56:06<24:46, 19.70it/s]

 71%|███████   | 71348/100629 [56:06<22:51, 21.35it/s]

 71%|███████   | 71351/100629 [56:06<21:18, 22.91it/s]

 71%|███████   | 71354/100629 [56:06<23:21, 20.89it/s]

 71%|███████   | 71357/100629 [56:06<23:59, 20.33it/s]

 71%|███████   | 71360/100629 [56:06<24:18, 20.07it/s]

 71%|███████   | 71363/100629 [56:07<26:41, 18.27it/s]

 71%|███████   | 71366/100629 [56:07<23:58, 20.35it/s]

 71%|███████   | 71369/100629 [56:07<24:33, 19.86it/s]

 71%|███████   | 71372/100629 [56:07<22:30, 21.66it/s]

 71%|███████   | 71375/100629 [56:07<23:57, 20.35it/s]

 71%|███████   | 71378/100629 [56:07<27:44, 17.57it/s]

 71%|███████   | 71380/100629 [56:07<27:05, 18.00it/s]

 71%|███████   | 71382/100629 [56:08<28:33, 17.07it/s]

 71%|███████   | 71384/100629 [56:08<28:27, 17.12it/s]

 71%|███████   | 71386/100629 [56:08<29:44, 16.39it/s]

 71%|███████   | 71389/100629 [56:08<27:33, 17.69it/s]

 71%|███████   | 71391/100629 [56:08<28:03, 17.37it/s]

 71%|███████   | 71393/100629 [56:08<30:23, 16.03it/s]

 71%|███████   | 71396/100629 [56:08<28:13, 17.26it/s]

 71%|███████   | 71398/100629 [56:09<29:45, 16.37it/s]

 71%|███████   | 71400/100629 [56:09<29:49, 16.33it/s]

 71%|███████   | 71405/100629 [56:09<21:41, 22.46it/s]

 71%|███████   | 71408/100629 [56:09<25:49, 18.86it/s]

 71%|███████   | 71411/100629 [56:09<23:27, 20.76it/s]

 71%|███████   | 71414/100629 [56:10<53:22,  9.12it/s]

 71%|███████   | 71418/100629 [56:10<39:51, 12.21it/s]

 71%|███████   | 71421/100629 [56:10<37:31, 12.97it/s]

 71%|███████   | 71423/100629 [56:10<35:15, 13.81it/s]

 71%|███████   | 71427/100629 [56:10<27:27, 17.73it/s]

 71%|███████   | 71430/100629 [56:11<24:20, 20.00it/s]

 71%|███████   | 71433/100629 [56:11<25:52, 18.81it/s]

 71%|███████   | 71436/100629 [56:11<27:01, 18.00it/s]

 71%|███████   | 71439/100629 [56:11<28:59, 16.78it/s]

 71%|███████   | 71441/100629 [56:11<28:22, 17.14it/s]

 71%|███████   | 71443/100629 [56:11<31:15, 15.56it/s]

 71%|███████   | 71447/100629 [56:12<24:02, 20.23it/s]

 71%|███████   | 71451/100629 [56:12<20:42, 23.48it/s]

 71%|███████   | 71454/100629 [56:12<23:52, 20.37it/s]

 71%|███████   | 71457/100629 [56:12<26:18, 18.49it/s]

 71%|███████   | 71461/100629 [56:12<21:42, 22.39it/s]

 71%|███████   | 71464/100629 [56:12<20:54, 23.25it/s]

 71%|███████   | 71468/100629 [56:12<21:00, 23.14it/s]

 71%|███████   | 71471/100629 [56:13<20:05, 24.18it/s]

 71%|███████   | 71475/100629 [56:13<19:42, 24.65it/s]

 71%|███████   | 71478/100629 [56:13<19:58, 24.32it/s]

 71%|███████   | 71481/100629 [56:13<23:24, 20.76it/s]

 71%|███████   | 71484/100629 [56:13<23:00, 21.12it/s]

 71%|███████   | 71488/100629 [56:13<19:15, 25.23it/s]

 71%|███████   | 71492/100629 [56:13<18:17, 26.56it/s]

 71%|███████   | 71496/100629 [56:14<18:38, 26.05it/s]

 71%|███████   | 71500/100629 [56:14<18:14, 26.62it/s]

 71%|███████   | 71503/100629 [56:14<19:34, 24.81it/s]

 71%|███████   | 71506/100629 [56:14<18:50, 25.77it/s]

 71%|███████   | 71509/100629 [56:14<21:15, 22.84it/s]

 71%|███████   | 71513/100629 [56:14<19:35, 24.78it/s]

 71%|███████   | 71516/100629 [56:14<20:07, 24.12it/s]

 71%|███████   | 71519/100629 [56:15<22:04, 21.97it/s]

 71%|███████   | 71522/100629 [56:15<22:02, 22.01it/s]

 71%|███████   | 71525/100629 [56:15<24:37, 19.70it/s]

 71%|███████   | 71528/100629 [56:15<28:27, 17.04it/s]

 71%|███████   | 71530/100629 [56:15<32:45, 14.81it/s]

 71%|███████   | 71535/100629 [56:15<23:06, 20.98it/s]

 71%|███████   | 71538/100629 [56:16<23:38, 20.51it/s]

 71%|███████   | 71541/100629 [56:16<25:34, 18.95it/s]

 71%|███████   | 71546/100629 [56:16<19:19, 25.09it/s]

 71%|███████   | 71549/100629 [56:16<20:27, 23.69it/s]

 71%|███████   | 71552/100629 [56:16<21:26, 22.60it/s]

 71%|███████   | 71555/100629 [56:16<22:11, 21.83it/s]

 71%|███████   | 71558/100629 [56:16<22:42, 21.33it/s]

 71%|███████   | 71561/100629 [56:17<28:40, 16.89it/s]

 71%|███████   | 71563/100629 [56:17<28:18, 17.11it/s]

 71%|███████   | 71568/100629 [56:17<20:47, 23.30it/s]

 71%|███████   | 71571/100629 [56:17<20:45, 23.33it/s]

 71%|███████   | 71575/100629 [56:17<18:50, 25.70it/s]

 71%|███████   | 71578/100629 [56:18<25:25, 19.04it/s]

 71%|███████   | 71581/100629 [56:18<24:01, 20.16it/s]

 71%|███████   | 71584/100629 [56:18<23:15, 20.81it/s]

 71%|███████   | 71587/100629 [56:18<22:26, 21.57it/s]

 71%|███████   | 71590/100629 [56:18<21:46, 22.23it/s]

 71%|███████   | 71593/100629 [56:18<23:15, 20.81it/s]

 71%|███████   | 71597/100629 [56:18<21:25, 22.59it/s]

 71%|███████   | 71602/100629 [56:18<17:15, 28.04it/s]

 71%|███████   | 71605/100629 [56:19<17:39, 27.40it/s]

 71%|███████   | 71608/100629 [56:19<21:29, 22.50it/s]

 71%|███████   | 71612/100629 [56:19<22:01, 21.96it/s]

 71%|███████   | 71615/100629 [56:19<21:38, 22.35it/s]

 71%|███████   | 71618/100629 [56:19<22:50, 21.16it/s]

 71%|███████   | 71621/100629 [56:19<24:53, 19.43it/s]

 71%|███████   | 71625/100629 [56:20<24:01, 20.12it/s]

 71%|███████   | 71628/100629 [56:20<22:34, 21.41it/s]

 71%|███████   | 71631/100629 [56:20<23:56, 20.19it/s]

 71%|███████   | 71636/100629 [56:20<20:48, 23.22it/s]

 71%|███████   | 71640/100629 [56:20<21:16, 22.72it/s]

 71%|███████   | 71644/100629 [56:20<19:13, 25.13it/s]

 71%|███████   | 71647/100629 [56:20<19:07, 25.26it/s]

 71%|███████   | 71650/100629 [56:21<21:20, 22.64it/s]

 71%|███████   | 71654/100629 [56:21<20:01, 24.11it/s]

 71%|███████   | 71658/100629 [56:21<18:22, 26.27it/s]

 71%|███████   | 71661/100629 [56:21<20:26, 23.61it/s]

 71%|███████   | 71664/100629 [56:21<20:40, 23.36it/s]

 71%|███████   | 71667/100629 [56:21<21:14, 22.73it/s]

 71%|███████   | 71670/100629 [56:22<21:04, 22.90it/s]

 71%|███████   | 71673/100629 [56:22<23:36, 20.44it/s]

 71%|███████   | 71676/100629 [56:22<22:42, 21.24it/s]

 71%|███████   | 71679/100629 [56:22<28:15, 17.07it/s]

 71%|███████   | 71682/100629 [56:22<25:13, 19.13it/s]

 71%|███████   | 71685/100629 [56:22<24:45, 19.48it/s]

 71%|███████   | 71688/100629 [56:23<28:03, 17.19it/s]

 71%|███████   | 71690/100629 [56:23<30:21, 15.89it/s]

 71%|███████   | 71692/100629 [56:23<32:45, 14.72it/s]

 71%|███████   | 71696/100629 [56:23<24:36, 19.59it/s]

 71%|███████▏  | 71699/100629 [56:23<23:24, 20.59it/s]

 71%|███████▏  | 71703/100629 [56:23<29:03, 16.60it/s]

 71%|███████▏  | 71705/100629 [56:24<33:50, 14.25it/s]

 71%|███████▏  | 71707/100629 [56:24<32:41, 14.75it/s]

 71%|███████▏  | 71712/100629 [56:24<23:02, 20.91it/s]

 71%|███████▏  | 71715/100629 [56:24<22:06, 21.80it/s]

 71%|███████▏  | 71718/100629 [56:24<23:22, 20.62it/s]

 71%|███████▏  | 71721/100629 [56:24<25:11, 19.12it/s]

 71%|███████▏  | 71724/100629 [56:25<27:07, 17.76it/s]

 71%|███████▏  | 71726/100629 [56:25<27:58, 17.22it/s]

 71%|███████▏  | 71728/100629 [56:25<27:57, 17.23it/s]

 71%|███████▏  | 71731/100629 [56:25<25:33, 18.85it/s]

 71%|███████▏  | 71734/100629 [56:25<22:42, 21.21it/s]

 71%|███████▏  | 71737/100629 [56:25<21:20, 22.57it/s]

 71%|███████▏  | 71740/100629 [56:25<21:12, 22.70it/s]

 71%|███████▏  | 71743/100629 [56:25<21:15, 22.65it/s]

 71%|███████▏  | 71746/100629 [56:26<21:26, 22.46it/s]

 71%|███████▏  | 71749/100629 [56:26<20:29, 23.49it/s]

 71%|███████▏  | 71752/100629 [56:26<20:30, 23.47it/s]

 71%|███████▏  | 71755/100629 [56:26<22:43, 21.17it/s]

 71%|███████▏  | 71759/100629 [56:26<22:34, 21.32it/s]

 71%|███████▏  | 71762/100629 [56:26<24:02, 20.02it/s]

 71%|███████▏  | 71766/100629 [56:26<21:43, 22.15it/s]

 71%|███████▏  | 71769/100629 [56:27<20:10, 23.85it/s]

 71%|███████▏  | 71772/100629 [56:27<20:08, 23.89it/s]

 71%|███████▏  | 71775/100629 [56:27<21:05, 22.81it/s]

 71%|███████▏  | 71778/100629 [56:27<25:49, 18.62it/s]

 71%|███████▏  | 71781/100629 [56:27<30:31, 15.75it/s]

 71%|███████▏  | 71785/100629 [56:27<24:48, 19.38it/s]

 71%|███████▏  | 71788/100629 [56:28<25:25, 18.90it/s]

 71%|███████▏  | 71791/100629 [56:28<24:36, 19.53it/s]

 71%|███████▏  | 71794/100629 [56:28<27:16, 17.61it/s]

 71%|███████▏  | 71797/100629 [56:28<25:07, 19.13it/s]

 71%|███████▏  | 71801/100629 [56:28<20:57, 22.93it/s]

 71%|███████▏  | 71804/100629 [56:28<21:00, 22.87it/s]

 71%|███████▏  | 71808/100629 [56:28<19:17, 24.90it/s]

 71%|███████▏  | 71812/100629 [56:29<17:07, 28.06it/s]

 71%|███████▏  | 71815/100629 [56:29<18:01, 26.64it/s]

 71%|███████▏  | 71819/100629 [56:29<18:18, 26.22it/s]

 71%|███████▏  | 71822/100629 [56:29<19:32, 24.56it/s]

 71%|███████▏  | 71825/100629 [56:29<20:06, 23.87it/s]

 71%|███████▏  | 71828/100629 [56:29<21:50, 21.97it/s]

 71%|███████▏  | 71831/100629 [56:29<20:49, 23.05it/s]

 71%|███████▏  | 71834/100629 [56:30<23:20, 20.56it/s]

 71%|███████▏  | 71838/100629 [56:30<20:04, 23.90it/s]

 71%|███████▏  | 71842/100629 [56:30<18:58, 25.28it/s]

 71%|███████▏  | 71846/100629 [56:30<19:21, 24.78it/s]

 71%|███████▏  | 71849/100629 [56:30<20:08, 23.82it/s]

 71%|███████▏  | 71852/100629 [56:30<19:59, 24.00it/s]

 71%|███████▏  | 71856/100629 [56:30<18:49, 25.48it/s]

 71%|███████▏  | 71859/100629 [56:31<19:08, 25.05it/s]

 71%|███████▏  | 71862/100629 [56:31<18:51, 25.43it/s]

 71%|███████▏  | 71865/100629 [56:31<22:09, 21.63it/s]

 71%|███████▏  | 71868/100629 [56:31<22:08, 21.65it/s]

 71%|███████▏  | 71872/100629 [56:31<19:24, 24.70it/s]

 71%|███████▏  | 71875/100629 [56:31<20:52, 22.96it/s]

 71%|███████▏  | 71878/100629 [56:31<20:46, 23.06it/s]

 71%|███████▏  | 71882/100629 [56:32<19:46, 24.23it/s]

 71%|███████▏  | 71885/100629 [56:32<19:00, 25.20it/s]

 71%|███████▏  | 71888/100629 [56:32<20:23, 23.50it/s]

 71%|███████▏  | 71891/100629 [56:32<24:07, 19.86it/s]

 71%|███████▏  | 71895/100629 [56:32<21:27, 22.32it/s]

 71%|███████▏  | 71898/100629 [56:32<21:56, 21.83it/s]

 71%|███████▏  | 71901/100629 [56:32<22:15, 21.51it/s]

 71%|███████▏  | 71906/100629 [56:33<18:31, 25.84it/s]

 71%|███████▏  | 71909/100629 [56:33<20:13, 23.67it/s]

 71%|███████▏  | 71912/100629 [56:33<19:38, 24.36it/s]

 71%|███████▏  | 71916/100629 [56:33<18:01, 26.55it/s]

 71%|███████▏  | 71919/100629 [56:33<17:41, 27.04it/s]

 71%|███████▏  | 71922/100629 [56:33<17:43, 27.01it/s]

 71%|███████▏  | 71925/100629 [56:33<18:01, 26.55it/s]

 71%|███████▏  | 71928/100629 [56:34<21:20, 22.41it/s]

 71%|███████▏  | 71931/100629 [56:34<20:13, 23.65it/s]

 71%|███████▏  | 71934/100629 [56:34<22:14, 21.51it/s]

 71%|███████▏  | 71937/100629 [56:34<24:28, 19.54it/s]

 71%|███████▏  | 71940/100629 [56:34<24:20, 19.64it/s]

 71%|███████▏  | 71943/100629 [56:34<23:58, 19.94it/s]

 71%|███████▏  | 71948/100629 [56:34<19:29, 24.52it/s]

 72%|███████▏  | 71951/100629 [56:35<20:02, 23.86it/s]

 72%|███████▏  | 71954/100629 [56:35<19:47, 24.15it/s]

 72%|███████▏  | 71957/100629 [56:35<22:02, 21.69it/s]

 72%|███████▏  | 71960/100629 [56:35<22:41, 21.06it/s]

 72%|███████▏  | 71964/100629 [56:35<21:24, 22.32it/s]

 72%|███████▏  | 71968/100629 [56:35<20:15, 23.58it/s]

 72%|███████▏  | 71971/100629 [56:35<21:49, 21.89it/s]

 72%|███████▏  | 71974/100629 [56:36<22:44, 21.01it/s]

 72%|███████▏  | 71977/100629 [56:36<23:20, 20.46it/s]

 72%|███████▏  | 71980/100629 [56:36<22:20, 21.38it/s]

 72%|███████▏  | 71983/100629 [56:36<20:43, 23.05it/s]

 72%|███████▏  | 71986/100629 [56:36<21:51, 21.84it/s]

 72%|███████▏  | 71989/100629 [56:36<21:46, 21.91it/s]

 72%|███████▏  | 71992/100629 [56:36<20:18, 23.50it/s]

 72%|███████▏  | 71995/100629 [56:37<23:05, 20.66it/s]

 72%|███████▏  | 71998/100629 [56:37<27:27, 17.38it/s]

 72%|███████▏  | 72001/100629 [56:37<24:17, 19.64it/s]

 72%|███████▏  | 72004/100629 [56:37<25:57, 18.38it/s]

 72%|███████▏  | 72008/100629 [56:37<21:47, 21.89it/s]

 72%|███████▏  | 72011/100629 [56:37<21:26, 22.25it/s]

 72%|███████▏  | 72015/100629 [56:38<19:28, 24.48it/s]

 72%|███████▏  | 72018/100629 [56:38<21:59, 21.68it/s]

 72%|███████▏  | 72021/100629 [56:38<23:58, 19.89it/s]

 72%|███████▏  | 72024/100629 [56:38<21:45, 21.92it/s]

 72%|███████▏  | 72027/100629 [56:38<21:06, 22.58it/s]

 72%|███████▏  | 72030/100629 [56:38<20:25, 23.34it/s]

 72%|███████▏  | 72033/100629 [56:38<19:30, 24.42it/s]

 72%|███████▏  | 72036/100629 [56:38<21:31, 22.14it/s]

 72%|███████▏  | 72039/100629 [56:39<24:11, 19.70it/s]

 72%|███████▏  | 72042/100629 [56:39<26:06, 18.25it/s]

 72%|███████▏  | 72044/100629 [56:39<30:20, 15.70it/s]

 72%|███████▏  | 72046/100629 [56:39<30:25, 15.66it/s]

 72%|███████▏  | 72049/100629 [56:39<26:55, 17.69it/s]

 72%|███████▏  | 72051/100629 [56:40<31:03, 15.34it/s]

 72%|███████▏  | 72055/100629 [56:40<26:08, 18.22it/s]

 72%|███████▏  | 72058/100629 [56:40<23:36, 20.17it/s]

 72%|███████▏  | 72061/100629 [56:40<25:23, 18.75it/s]

 72%|███████▏  | 72064/100629 [56:40<24:13, 19.65it/s]

 72%|███████▏  | 72067/100629 [56:40<27:16, 17.45it/s]

 72%|███████▏  | 72069/100629 [56:40<28:03, 16.96it/s]

 72%|███████▏  | 72073/100629 [56:41<23:42, 20.08it/s]

 72%|███████▏  | 72076/100629 [56:41<21:25, 22.22it/s]

 72%|███████▏  | 72081/100629 [56:41<19:38, 24.22it/s]

 72%|███████▏  | 72084/100629 [56:41<24:52, 19.12it/s]

 72%|███████▏  | 72087/100629 [56:41<24:08, 19.71it/s]

 72%|███████▏  | 72090/100629 [56:41<23:39, 20.10it/s]

 72%|███████▏  | 72093/100629 [56:42<23:04, 20.61it/s]

 72%|███████▏  | 72096/100629 [56:42<26:25, 18.00it/s]

 72%|███████▏  | 72098/100629 [56:42<26:18, 18.07it/s]

 72%|███████▏  | 72101/100629 [56:42<23:41, 20.07it/s]

 72%|███████▏  | 72105/100629 [56:42<23:19, 20.38it/s]

 72%|███████▏  | 72109/100629 [56:42<24:03, 19.76it/s]

 72%|███████▏  | 72112/100629 [56:43<22:56, 20.71it/s]

 72%|███████▏  | 72115/100629 [56:43<21:52, 21.73it/s]

 72%|███████▏  | 72121/100629 [56:43<16:18, 29.15it/s]

 72%|███████▏  | 72125/100629 [56:43<16:08, 29.44it/s]

 72%|███████▏  | 72129/100629 [56:43<19:58, 23.78it/s]

 72%|███████▏  | 72132/100629 [56:43<24:19, 19.52it/s]

 72%|███████▏  | 72136/100629 [56:43<21:00, 22.61it/s]

 72%|███████▏  | 72139/100629 [56:44<24:03, 19.74it/s]

 72%|███████▏  | 72144/100629 [56:44<19:36, 24.20it/s]

 72%|███████▏  | 72148/100629 [56:44<18:11, 26.08it/s]

 72%|███████▏  | 72152/100629 [56:44<17:02, 27.86it/s]

 72%|███████▏  | 72156/100629 [56:44<20:21, 23.30it/s]

 72%|███████▏  | 72159/100629 [56:44<19:50, 23.92it/s]

 72%|███████▏  | 72162/100629 [56:45<25:02, 18.95it/s]

 72%|███████▏  | 72165/100629 [56:45<23:20, 20.32it/s]

 72%|███████▏  | 72168/100629 [56:45<23:56, 19.82it/s]

 72%|███████▏  | 72172/100629 [56:45<21:10, 22.41it/s]

 72%|███████▏  | 72176/100629 [56:45<20:49, 22.77it/s]

 72%|███████▏  | 72179/100629 [56:45<22:16, 21.29it/s]

 72%|███████▏  | 72182/100629 [56:46<21:02, 22.53it/s]

 72%|███████▏  | 72185/100629 [56:46<20:13, 23.45it/s]

 72%|███████▏  | 72189/100629 [56:46<18:21, 25.83it/s]

 72%|███████▏  | 72192/100629 [56:46<19:27, 24.36it/s]

 72%|███████▏  | 72195/100629 [56:46<18:59, 24.96it/s]

 72%|███████▏  | 72198/100629 [56:46<19:31, 24.27it/s]

 72%|███████▏  | 72201/100629 [56:46<20:47, 22.79it/s]

 72%|███████▏  | 72206/100629 [56:46<16:21, 28.95it/s]

 72%|███████▏  | 72210/100629 [56:47<16:07, 29.36it/s]

 72%|███████▏  | 72214/100629 [56:47<16:56, 27.96it/s]

 72%|███████▏  | 72217/100629 [56:47<19:20, 24.49it/s]

 72%|███████▏  | 72220/100629 [56:47<18:25, 25.69it/s]

 72%|███████▏  | 72223/100629 [56:47<19:15, 24.58it/s]

 72%|███████▏  | 72227/100629 [56:47<17:32, 26.99it/s]

 72%|███████▏  | 72230/100629 [56:47<20:30, 23.07it/s]

 72%|███████▏  | 72233/100629 [56:48<21:23, 22.13it/s]

 72%|███████▏  | 72236/100629 [56:48<26:23, 17.93it/s]

 72%|███████▏  | 72239/100629 [56:48<24:35, 19.24it/s]

 72%|███████▏  | 72242/100629 [56:48<24:09, 19.58it/s]

 72%|███████▏  | 72245/100629 [56:48<25:25, 18.61it/s]

 72%|███████▏  | 72250/100629 [56:48<19:46, 23.92it/s]

 72%|███████▏  | 72255/100629 [56:49<16:40, 28.37it/s]

 72%|███████▏  | 72259/100629 [56:49<17:38, 26.80it/s]

 72%|███████▏  | 72262/100629 [56:49<21:30, 21.98it/s]

 72%|███████▏  | 72265/100629 [56:49<21:06, 22.39it/s]

 72%|███████▏  | 72268/100629 [56:49<25:56, 18.22it/s]

 72%|███████▏  | 72272/100629 [56:49<21:29, 21.99it/s]

 72%|███████▏  | 72275/100629 [56:50<23:22, 20.22it/s]

 72%|███████▏  | 72278/100629 [56:50<21:52, 21.60it/s]

 72%|███████▏  | 72281/100629 [56:50<23:45, 19.89it/s]

 72%|███████▏  | 72284/100629 [56:50<22:55, 20.60it/s]

 72%|███████▏  | 72287/100629 [56:50<21:00, 22.49it/s]

 72%|███████▏  | 72290/100629 [56:50<23:27, 20.13it/s]

 72%|███████▏  | 72293/100629 [56:50<22:50, 20.67it/s]

 72%|███████▏  | 72296/100629 [56:51<23:21, 20.21it/s]

 72%|███████▏  | 72299/100629 [56:51<21:24, 22.06it/s]

 72%|███████▏  | 72302/100629 [56:51<23:28, 20.11it/s]

 72%|███████▏  | 72305/100629 [56:51<25:14, 18.70it/s]

 72%|███████▏  | 72307/100629 [56:51<25:22, 18.60it/s]

 72%|███████▏  | 72309/100629 [56:51<30:10, 15.64it/s]

 72%|███████▏  | 72312/100629 [56:51<25:49, 18.28it/s]

 72%|███████▏  | 72314/100629 [56:52<30:02, 15.71it/s]

 72%|███████▏  | 72317/100629 [56:52<27:17, 17.29it/s]

 72%|███████▏  | 72319/100629 [56:52<28:00, 16.85it/s]

 72%|███████▏  | 72321/100629 [56:52<28:47, 16.39it/s]

 72%|███████▏  | 72323/100629 [56:52<29:34, 15.95it/s]

 72%|███████▏  | 72326/100629 [56:52<26:35, 17.74it/s]

 72%|███████▏  | 72328/100629 [56:52<27:25, 17.20it/s]

 72%|███████▏  | 72331/100629 [56:53<25:25, 18.55it/s]

 72%|███████▏  | 72333/100629 [56:53<25:42, 18.34it/s]

 72%|███████▏  | 72337/100629 [56:53<23:10, 20.34it/s]

 72%|███████▏  | 72340/100629 [56:53<21:04, 22.37it/s]

 72%|███████▏  | 72343/100629 [56:53<22:10, 21.26it/s]

 72%|███████▏  | 72346/100629 [56:53<20:55, 22.52it/s]

 72%|███████▏  | 72349/100629 [56:53<21:08, 22.29it/s]

 72%|███████▏  | 72352/100629 [56:54<24:59, 18.85it/s]

 72%|███████▏  | 72356/100629 [56:54<21:44, 21.68it/s]

 72%|███████▏  | 72360/100629 [56:54<18:33, 25.38it/s]

 72%|███████▏  | 72363/100629 [56:54<19:25, 24.26it/s]

 72%|███████▏  | 72366/100629 [56:54<21:20, 22.07it/s]

 72%|███████▏  | 72369/100629 [56:54<21:32, 21.86it/s]

 72%|███████▏  | 72372/100629 [56:54<24:19, 19.37it/s]

 72%|███████▏  | 72376/100629 [56:55<20:18, 23.18it/s]

 72%|███████▏  | 72379/100629 [56:55<20:57, 22.46it/s]

 72%|███████▏  | 72383/100629 [56:55<19:06, 24.63it/s]

 72%|███████▏  | 72386/100629 [56:55<20:50, 22.59it/s]

 72%|███████▏  | 72389/100629 [56:55<22:31, 20.90it/s]

 72%|███████▏  | 72392/100629 [56:55<28:42, 16.39it/s]

 72%|███████▏  | 72395/100629 [56:56<25:37, 18.37it/s]

 72%|███████▏  | 72399/100629 [56:56<25:06, 18.73it/s]

 72%|███████▏  | 72402/100629 [56:56<23:24, 20.10it/s]

 72%|███████▏  | 72405/100629 [56:56<23:28, 20.04it/s]

 72%|███████▏  | 72408/100629 [56:56<24:31, 19.18it/s]

 72%|███████▏  | 72411/100629 [56:56<25:41, 18.30it/s]

 72%|███████▏  | 72415/100629 [56:57<21:45, 21.60it/s]

 72%|███████▏  | 72418/100629 [56:57<22:30, 20.89it/s]

 72%|███████▏  | 72421/100629 [56:57<21:26, 21.92it/s]

 72%|███████▏  | 72424/100629 [56:57<20:14, 23.22it/s]

 72%|███████▏  | 72428/100629 [56:57<18:05, 25.99it/s]

 72%|███████▏  | 72431/100629 [56:57<18:45, 25.05it/s]

 72%|███████▏  | 72434/100629 [56:57<19:38, 23.92it/s]

 72%|███████▏  | 72437/100629 [56:58<23:02, 20.39it/s]

 72%|███████▏  | 72440/100629 [56:58<22:52, 20.54it/s]

 72%|███████▏  | 72443/100629 [56:58<21:52, 21.47it/s]

 72%|███████▏  | 72446/100629 [56:58<20:49, 22.56it/s]

 72%|███████▏  | 72450/100629 [56:58<18:52, 24.87it/s]

 72%|███████▏  | 72453/100629 [56:58<21:29, 21.85it/s]

 72%|███████▏  | 72456/100629 [56:58<20:14, 23.20it/s]

 72%|███████▏  | 72459/100629 [56:58<21:02, 22.32it/s]

 72%|███████▏  | 72462/100629 [56:59<20:07, 23.32it/s]

 72%|███████▏  | 72466/100629 [56:59<19:25, 24.17it/s]

 72%|███████▏  | 72469/100629 [56:59<20:20, 23.08it/s]

 72%|███████▏  | 72472/100629 [56:59<23:09, 20.27it/s]

 72%|███████▏  | 72475/100629 [56:59<23:01, 20.38it/s]

 72%|███████▏  | 72478/100629 [56:59<21:08, 22.20it/s]

 72%|███████▏  | 72481/100629 [57:00<25:28, 18.42it/s]

 72%|███████▏  | 72484/100629 [57:00<23:42, 19.79it/s]

 72%|███████▏  | 72487/100629 [57:00<27:03, 17.33it/s]

 72%|███████▏  | 72490/100629 [57:00<24:34, 19.09it/s]

 72%|███████▏  | 72493/100629 [57:00<23:18, 20.11it/s]

 72%|███████▏  | 72496/100629 [57:00<23:54, 19.61it/s]

 72%|███████▏  | 72499/100629 [57:00<21:42, 21.60it/s]

 72%|███████▏  | 72502/100629 [57:01<20:33, 22.80it/s]

 72%|███████▏  | 72505/100629 [57:01<22:10, 21.13it/s]

 72%|███████▏  | 72508/100629 [57:01<25:17, 18.54it/s]

 72%|███████▏  | 72511/100629 [57:01<23:09, 20.23it/s]

 72%|███████▏  | 72515/100629 [57:01<19:10, 24.44it/s]

 72%|███████▏  | 72518/100629 [57:01<19:32, 23.98it/s]

 72%|███████▏  | 72521/100629 [57:01<18:45, 24.98it/s]

 72%|███████▏  | 72524/100629 [57:02<20:59, 22.31it/s]

 72%|███████▏  | 72527/100629 [57:02<21:51, 21.42it/s]

 72%|███████▏  | 72530/100629 [57:02<25:43, 18.20it/s]

 72%|███████▏  | 72534/100629 [57:02<22:04, 21.22it/s]

 72%|███████▏  | 72537/100629 [57:02<30:17, 15.45it/s]

 72%|███████▏  | 72540/100629 [57:03<26:52, 17.41it/s]

 72%|███████▏  | 72543/100629 [57:03<26:43, 17.51it/s]

 72%|███████▏  | 72545/100629 [57:03<26:11, 17.87it/s]

 72%|███████▏  | 72549/100629 [57:03<23:27, 19.95it/s]

 72%|███████▏  | 72553/100629 [57:03<20:28, 22.85it/s]

 72%|███████▏  | 72556/100629 [57:03<21:23, 21.87it/s]

 72%|███████▏  | 72559/100629 [57:03<21:49, 21.43it/s]

 72%|███████▏  | 72562/100629 [57:03<20:12, 23.14it/s]

 72%|███████▏  | 72565/100629 [57:04<21:43, 21.54it/s]

 72%|███████▏  | 72570/100629 [57:04<17:28, 26.76it/s]

 72%|███████▏  | 72573/100629 [57:04<17:37, 26.54it/s]

 72%|███████▏  | 72576/100629 [57:04<21:39, 21.59it/s]

 72%|███████▏  | 72579/100629 [57:04<22:20, 20.93it/s]

 72%|███████▏  | 72583/100629 [57:04<18:39, 25.05it/s]

 72%|███████▏  | 72586/100629 [57:05<25:05, 18.63it/s]

 72%|███████▏  | 72589/100629 [57:05<25:38, 18.23it/s]

 72%|███████▏  | 72593/100629 [57:05<21:10, 22.07it/s]

 72%|███████▏  | 72596/100629 [57:05<20:21, 22.94it/s]

 72%|███████▏  | 72599/100629 [57:05<21:53, 21.34it/s]

 72%|███████▏  | 72604/100629 [57:05<18:17, 25.53it/s]

 72%|███████▏  | 72607/100629 [57:05<18:21, 25.45it/s]

 72%|███████▏  | 72610/100629 [57:06<19:11, 24.34it/s]

 72%|███████▏  | 72613/100629 [57:06<18:49, 24.79it/s]

 72%|███████▏  | 72616/100629 [57:06<19:41, 23.72it/s]

 72%|███████▏  | 72619/100629 [57:06<20:13, 23.08it/s]

 72%|███████▏  | 72623/100629 [57:06<19:50, 23.52it/s]

 72%|███████▏  | 72626/100629 [57:06<21:33, 21.64it/s]

 72%|███████▏  | 72629/100629 [57:07<26:52, 17.37it/s]

 72%|███████▏  | 72631/100629 [57:07<28:57, 16.12it/s]

 72%|███████▏  | 72634/100629 [57:07<27:24, 17.03it/s]

 72%|███████▏  | 72637/100629 [57:07<23:55, 19.50it/s]

 72%|███████▏  | 72640/100629 [57:07<28:28, 16.38it/s]

 72%|███████▏  | 72642/100629 [57:07<27:30, 16.96it/s]

 72%|███████▏  | 72645/100629 [57:07<24:08, 19.32it/s]

 72%|███████▏  | 72648/100629 [57:08<24:27, 19.07it/s]

 72%|███████▏  | 72651/100629 [57:08<33:49, 13.79it/s]

 72%|███████▏  | 72654/100629 [57:08<30:01, 15.53it/s]

 72%|███████▏  | 72657/100629 [57:08<28:15, 16.50it/s]

 72%|███████▏  | 72660/100629 [57:08<24:44, 18.85it/s]

 72%|███████▏  | 72663/100629 [57:08<22:23, 20.81it/s]

 72%|███████▏  | 72666/100629 [57:09<24:47, 18.80it/s]

 72%|███████▏  | 72669/100629 [57:09<29:23, 15.86it/s]

 72%|███████▏  | 72672/100629 [57:09<29:07, 16.00it/s]

 72%|███████▏  | 72674/100629 [57:09<29:09, 15.98it/s]

 72%|███████▏  | 72677/100629 [57:09<28:18, 16.46it/s]

 72%|███████▏  | 72679/100629 [57:10<28:08, 16.55it/s]

 72%|███████▏  | 72681/100629 [57:10<28:00, 16.63it/s]

 72%|███████▏  | 72684/100629 [57:10<26:34, 17.53it/s]

 72%|███████▏  | 72686/100629 [57:10<33:03, 14.09it/s]

 72%|███████▏  | 72691/100629 [57:10<23:16, 20.00it/s]

 72%|███████▏  | 72694/100629 [57:10<29:57, 15.54it/s]

 72%|███████▏  | 72696/100629 [57:11<30:04, 15.48it/s]

 72%|███████▏  | 72698/100629 [57:11<29:44, 15.65it/s]

 72%|███████▏  | 72701/100629 [57:11<25:22, 18.35it/s]

 72%|███████▏  | 72704/100629 [57:11<23:50, 19.52it/s]

 72%|███████▏  | 72708/100629 [57:11<19:22, 24.02it/s]

 72%|███████▏  | 72711/100629 [57:11<18:22, 25.32it/s]

 72%|███████▏  | 72715/100629 [57:11<17:42, 26.27it/s]

 72%|███████▏  | 72718/100629 [57:11<19:30, 23.84it/s]

 72%|███████▏  | 72721/100629 [57:12<21:59, 21.16it/s]

 72%|███████▏  | 72724/100629 [57:12<23:48, 19.53it/s]

 72%|███████▏  | 72728/100629 [57:12<20:10, 23.04it/s]

 72%|███████▏  | 72731/100629 [57:12<19:39, 23.65it/s]

 72%|███████▏  | 72734/100629 [57:12<19:37, 23.70it/s]

 72%|███████▏  | 72737/100629 [57:12<20:35, 22.58it/s]

 72%|███████▏  | 72740/100629 [57:12<22:27, 20.70it/s]

 72%|███████▏  | 72743/100629 [57:13<23:11, 20.04it/s]

 72%|███████▏  | 72747/100629 [57:13<19:47, 23.48it/s]

 72%|███████▏  | 72750/100629 [57:13<20:28, 22.69it/s]

 72%|███████▏  | 72753/100629 [57:13<20:47, 22.35it/s]

 72%|███████▏  | 72757/100629 [57:13<18:15, 25.45it/s]

 72%|███████▏  | 72761/100629 [57:13<19:05, 24.33it/s]

 72%|███████▏  | 72764/100629 [57:14<21:03, 22.06it/s]

 72%|███████▏  | 72767/100629 [57:14<20:57, 22.16it/s]

 72%|███████▏  | 72770/100629 [57:14<21:39, 21.43it/s]

 72%|███████▏  | 72773/100629 [57:14<22:32, 20.60it/s]

 72%|███████▏  | 72776/100629 [57:14<22:58, 20.21it/s]

 72%|███████▏  | 72780/100629 [57:14<19:39, 23.61it/s]

 72%|███████▏  | 72783/100629 [57:15<30:08, 15.39it/s]

 72%|███████▏  | 72785/100629 [57:15<30:04, 15.43it/s]

 72%|███████▏  | 72787/100629 [57:15<30:02, 15.45it/s]

 72%|███████▏  | 72790/100629 [57:15<27:12, 17.06it/s]

 72%|███████▏  | 72793/100629 [57:15<25:41, 18.05it/s]

 72%|███████▏  | 72796/100629 [57:15<22:37, 20.50it/s]

 72%|███████▏  | 72799/100629 [57:15<22:27, 20.65it/s]

 72%|███████▏  | 72802/100629 [57:16<22:30, 20.60it/s]

 72%|███████▏  | 72805/100629 [57:16<21:03, 22.03it/s]

 72%|███████▏  | 72809/100629 [57:16<19:39, 23.60it/s]

 72%|███████▏  | 72812/100629 [57:16<18:39, 24.84it/s]

 72%|███████▏  | 72815/100629 [57:16<21:09, 21.90it/s]

 72%|███████▏  | 72819/100629 [57:16<18:05, 25.62it/s]

 72%|███████▏  | 72822/100629 [57:16<19:16, 24.05it/s]

 72%|███████▏  | 72826/100629 [57:16<17:13, 26.91it/s]

 72%|███████▏  | 72829/100629 [57:17<19:47, 23.41it/s]

 72%|███████▏  | 72832/100629 [57:17<22:52, 20.25it/s]

 72%|███████▏  | 72835/100629 [57:17<21:09, 21.90it/s]

 72%|███████▏  | 72838/100629 [57:17<21:47, 21.25it/s]

 72%|███████▏  | 72841/100629 [57:17<20:43, 22.36it/s]

 72%|███████▏  | 72845/100629 [57:17<17:34, 26.36it/s]

 72%|███████▏  | 72848/100629 [57:17<18:09, 25.49it/s]

 72%|███████▏  | 72851/100629 [57:18<22:04, 20.98it/s]

 72%|███████▏  | 72854/100629 [57:18<20:41, 22.37it/s]

 72%|███████▏  | 72857/100629 [57:18<19:52, 23.28it/s]

 72%|███████▏  | 72861/100629 [57:18<17:33, 26.35it/s]

 72%|███████▏  | 72865/100629 [57:18<15:38, 29.59it/s]

 72%|███████▏  | 72869/100629 [57:18<18:35, 24.89it/s]

 72%|███████▏  | 72872/100629 [57:18<18:12, 25.40it/s]

 72%|███████▏  | 72875/100629 [57:19<20:24, 22.66it/s]

 72%|███████▏  | 72878/100629 [57:19<21:32, 21.47it/s]

 72%|███████▏  | 72881/100629 [57:19<23:36, 19.59it/s]

 72%|███████▏  | 72884/100629 [57:19<25:49, 17.91it/s]

 72%|███████▏  | 72887/100629 [57:19<25:19, 18.26it/s]

 72%|███████▏  | 72889/100629 [57:19<27:03, 17.09it/s]

 72%|███████▏  | 72891/100629 [57:20<26:08, 17.68it/s]

 72%|███████▏  | 72894/100629 [57:20<25:30, 18.12it/s]

 72%|███████▏  | 72896/100629 [57:20<29:25, 15.71it/s]

 72%|███████▏  | 72901/100629 [57:20<21:27, 21.53it/s]

 72%|███████▏  | 72904/100629 [57:20<21:19, 21.66it/s]

 72%|███████▏  | 72907/100629 [57:20<21:10, 21.83it/s]

 72%|███████▏  | 72911/100629 [57:20<19:01, 24.28it/s]

 72%|███████▏  | 72914/100629 [57:21<28:20, 16.30it/s]

 72%|███████▏  | 72917/100629 [57:21<27:02, 17.08it/s]

 72%|███████▏  | 72921/100629 [57:21<21:46, 21.20it/s]

 72%|███████▏  | 72925/100629 [57:21<20:33, 22.46it/s]

 72%|███████▏  | 72928/100629 [57:21<22:29, 20.53it/s]

 72%|███████▏  | 72931/100629 [57:22<23:53, 19.32it/s]

 72%|███████▏  | 72934/100629 [57:22<22:51, 20.19it/s]

 72%|███████▏  | 72938/100629 [57:22<20:12, 22.84it/s]

 72%|███████▏  | 72941/100629 [57:22<22:44, 20.30it/s]

 72%|███████▏  | 72944/100629 [57:22<22:13, 20.77it/s]

 72%|███████▏  | 72948/100629 [57:22<19:55, 23.15it/s]

 72%|███████▏  | 72951/100629 [57:22<20:36, 22.39it/s]

 72%|███████▏  | 72954/100629 [57:23<19:29, 23.66it/s]

 73%|███████▎  | 72957/100629 [57:23<20:47, 22.18it/s]

 73%|███████▎  | 72961/100629 [57:23<18:04, 25.51it/s]

 73%|███████▎  | 72966/100629 [57:23<15:05, 30.54it/s]

 73%|███████▎  | 72970/100629 [57:23<17:27, 26.40it/s]

 73%|███████▎  | 72973/100629 [57:23<18:01, 25.58it/s]

 73%|███████▎  | 72976/100629 [57:23<17:30, 26.32it/s]

 73%|███████▎  | 72979/100629 [57:23<17:12, 26.77it/s]

 73%|███████▎  | 72982/100629 [57:24<17:23, 26.50it/s]

 73%|███████▎  | 72985/100629 [57:24<20:07, 22.89it/s]

 73%|███████▎  | 72988/100629 [57:24<20:50, 22.11it/s]

 73%|███████▎  | 72991/100629 [57:24<19:30, 23.62it/s]

 73%|███████▎  | 72995/100629 [57:24<21:36, 21.31it/s]

 73%|███████▎  | 72998/100629 [57:24<22:03, 20.88it/s]

 73%|███████▎  | 73001/100629 [57:25<23:30, 19.59it/s]

 73%|███████▎  | 73004/100629 [57:25<23:45, 19.39it/s]

 73%|███████▎  | 73009/100629 [57:25<21:14, 21.67it/s]

 73%|███████▎  | 73013/100629 [57:25<19:07, 24.07it/s]

 73%|███████▎  | 73016/100629 [57:25<22:30, 20.45it/s]

 73%|███████▎  | 73019/100629 [57:25<20:35, 22.34it/s]

 73%|███████▎  | 73022/100629 [57:25<20:56, 21.97it/s]

 73%|███████▎  | 73025/100629 [57:26<20:48, 22.10it/s]

 73%|███████▎  | 73028/100629 [57:26<20:36, 22.33it/s]

 73%|███████▎  | 73031/100629 [57:26<19:37, 23.43it/s]

 73%|███████▎  | 73034/100629 [57:26<28:11, 16.31it/s]

 73%|███████▎  | 73036/100629 [57:26<27:16, 16.86it/s]

 73%|███████▎  | 73039/100629 [57:26<28:01, 16.41it/s]

 73%|███████▎  | 73043/100629 [57:27<24:23, 18.86it/s]

 73%|███████▎  | 73046/100629 [57:27<23:05, 19.91it/s]

 73%|███████▎  | 73049/100629 [57:27<22:33, 20.38it/s]

 73%|███████▎  | 73052/100629 [57:27<26:18, 17.47it/s]

 73%|███████▎  | 73056/100629 [57:27<23:10, 19.83it/s]

 73%|███████▎  | 73060/100629 [57:27<21:57, 20.93it/s]

 73%|███████▎  | 73063/100629 [57:28<21:22, 21.50it/s]

 73%|███████▎  | 73067/100629 [57:28<19:20, 23.76it/s]

 73%|███████▎  | 73070/100629 [57:28<18:26, 24.90it/s]

 73%|███████▎  | 73073/100629 [57:28<22:02, 20.84it/s]

 73%|███████▎  | 73078/100629 [57:28<17:25, 26.35it/s]

 73%|███████▎  | 73083/100629 [57:28<16:24, 27.98it/s]

 73%|███████▎  | 73086/100629 [57:28<19:06, 24.03it/s]

 73%|███████▎  | 73089/100629 [57:29<20:22, 22.53it/s]

 73%|███████▎  | 73092/100629 [57:29<21:22, 21.47it/s]

 73%|███████▎  | 73095/100629 [57:29<20:40, 22.20it/s]

 73%|███████▎  | 73099/100629 [57:29<19:11, 23.90it/s]

 73%|███████▎  | 73102/100629 [57:29<21:11, 21.64it/s]

 73%|███████▎  | 73105/100629 [57:29<22:41, 20.22it/s]

 73%|███████▎  | 73108/100629 [57:30<22:20, 20.52it/s]

 73%|███████▎  | 73111/100629 [57:30<20:28, 22.40it/s]

 73%|███████▎  | 73114/100629 [57:30<21:26, 21.39it/s]

 73%|███████▎  | 73118/100629 [57:30<19:56, 23.00it/s]

 73%|███████▎  | 73122/100629 [57:30<18:47, 24.40it/s]

 73%|███████▎  | 73125/100629 [57:30<20:04, 22.83it/s]

 73%|███████▎  | 73128/100629 [57:30<19:49, 23.12it/s]

 73%|███████▎  | 73132/100629 [57:30<17:30, 26.17it/s]

 73%|███████▎  | 73137/100629 [57:31<15:19, 29.90it/s]

 73%|███████▎  | 73141/100629 [57:31<16:47, 27.29it/s]

 73%|███████▎  | 73144/100629 [57:31<17:04, 26.81it/s]

 73%|███████▎  | 73147/100629 [57:31<22:10, 20.66it/s]

 73%|███████▎  | 73150/100629 [57:31<24:27, 18.72it/s]

 73%|███████▎  | 73153/100629 [57:32<25:27, 17.99it/s]

 73%|███████▎  | 73155/100629 [57:32<27:13, 16.82it/s]

 73%|███████▎  | 73157/100629 [57:32<27:35, 16.59it/s]

 73%|███████▎  | 73159/100629 [57:32<26:27, 17.31it/s]

 73%|███████▎  | 73161/100629 [57:32<26:50, 17.05it/s]

 73%|███████▎  | 73164/100629 [57:32<25:19, 18.08it/s]

 73%|███████▎  | 73167/100629 [57:32<24:46, 18.48it/s]

 73%|███████▎  | 73169/100629 [57:32<24:30, 18.67it/s]

 73%|███████▎  | 73173/100629 [57:33<20:40, 22.13it/s]

 73%|███████▎  | 73176/100629 [57:33<24:03, 19.02it/s]

 73%|███████▎  | 73179/100629 [57:33<22:34, 20.26it/s]

 73%|███████▎  | 73184/100629 [57:33<17:09, 26.66it/s]

 73%|███████▎  | 73188/100629 [57:33<17:14, 26.54it/s]

 73%|███████▎  | 73192/100629 [57:33<16:12, 28.20it/s]

 73%|███████▎  | 73196/100629 [57:33<17:13, 26.54it/s]

 73%|███████▎  | 73199/100629 [57:34<17:17, 26.45it/s]

 73%|███████▎  | 73203/100629 [57:34<15:42, 29.11it/s]

 73%|███████▎  | 73207/100629 [57:34<15:01, 30.43it/s]

 73%|███████▎  | 73211/100629 [57:34<16:15, 28.10it/s]

 73%|███████▎  | 73214/100629 [57:34<18:34, 24.59it/s]

 73%|███████▎  | 73217/100629 [57:34<20:02, 22.79it/s]

 73%|███████▎  | 73220/100629 [57:34<20:03, 22.78it/s]

 73%|███████▎  | 73225/100629 [57:35<17:42, 25.78it/s]

 73%|███████▎  | 73228/100629 [57:35<20:28, 22.30it/s]

 73%|███████▎  | 73231/100629 [57:35<21:05, 21.65it/s]

 73%|███████▎  | 73234/100629 [57:35<21:47, 20.95it/s]

 73%|███████▎  | 73237/100629 [57:35<19:58, 22.86it/s]

 73%|███████▎  | 73240/100629 [57:35<21:02, 21.70it/s]

 73%|███████▎  | 73244/100629 [57:36<21:19, 21.41it/s]

 73%|███████▎  | 73248/100629 [57:36<18:47, 24.29it/s]

 73%|███████▎  | 73252/100629 [57:36<16:29, 27.67it/s]

 73%|███████▎  | 73256/100629 [57:36<16:10, 28.21it/s]

 73%|███████▎  | 73260/100629 [57:36<14:42, 31.01it/s]

 73%|███████▎  | 73264/100629 [57:36<16:06, 28.31it/s]

 73%|███████▎  | 73267/100629 [57:36<18:19, 24.89it/s]

 73%|███████▎  | 73270/100629 [57:37<21:20, 21.36it/s]

 73%|███████▎  | 73273/100629 [57:37<19:56, 22.87it/s]

 73%|███████▎  | 73276/100629 [57:37<22:16, 20.46it/s]

 73%|███████▎  | 73279/100629 [57:37<24:02, 18.96it/s]

 73%|███████▎  | 73282/100629 [57:37<22:52, 19.92it/s]

 73%|███████▎  | 73285/100629 [57:37<21:40, 21.02it/s]

 73%|███████▎  | 73288/100629 [57:37<21:07, 21.57it/s]

 73%|███████▎  | 73291/100629 [57:37<19:37, 23.21it/s]

 73%|███████▎  | 73294/100629 [57:38<19:34, 23.27it/s]

 73%|███████▎  | 73297/100629 [57:38<27:19, 16.67it/s]

 73%|███████▎  | 73301/100629 [57:38<24:11, 18.83it/s]

 73%|███████▎  | 73304/100629 [57:38<22:34, 20.18it/s]

 73%|███████▎  | 73307/100629 [57:38<22:13, 20.49it/s]

 73%|███████▎  | 73310/100629 [57:38<21:56, 20.75it/s]

 73%|███████▎  | 73314/100629 [57:39<19:20, 23.53it/s]

 73%|███████▎  | 73317/100629 [57:39<20:01, 22.72it/s]

 73%|███████▎  | 73320/100629 [57:39<21:52, 20.80it/s]

 73%|███████▎  | 73323/100629 [57:39<24:36, 18.49it/s]

 73%|███████▎  | 73326/100629 [57:39<23:24, 19.44it/s]

 73%|███████▎  | 73329/100629 [57:39<21:55, 20.76it/s]

 73%|███████▎  | 73332/100629 [57:40<23:00, 19.78it/s]

 73%|███████▎  | 73335/100629 [57:40<22:00, 20.68it/s]

 73%|███████▎  | 73338/100629 [57:40<25:17, 17.99it/s]

 73%|███████▎  | 73341/100629 [57:40<23:33, 19.30it/s]

 73%|███████▎  | 73344/100629 [57:40<24:00, 18.95it/s]

 73%|███████▎  | 73346/100629 [57:40<29:01, 15.66it/s]

 73%|███████▎  | 73350/100629 [57:41<23:40, 19.20it/s]

 73%|███████▎  | 73353/100629 [57:41<21:15, 21.39it/s]

 73%|███████▎  | 73356/100629 [57:41<23:46, 19.12it/s]

 73%|███████▎  | 73361/100629 [57:41<18:11, 24.99it/s]

 73%|███████▎  | 73364/100629 [57:41<19:07, 23.76it/s]

 73%|███████▎  | 73369/100629 [57:41<15:58, 28.43it/s]

 73%|███████▎  | 73373/100629 [57:41<15:52, 28.62it/s]

 73%|███████▎  | 73377/100629 [57:42<17:03, 26.64it/s]

 73%|███████▎  | 73380/100629 [57:42<17:49, 25.49it/s]

 73%|███████▎  | 73384/100629 [57:42<17:18, 26.24it/s]

 73%|███████▎  | 73387/100629 [57:42<18:41, 24.28it/s]

 73%|███████▎  | 73391/100629 [57:42<16:52, 26.90it/s]

 73%|███████▎  | 73394/100629 [57:42<18:30, 24.53it/s]

 73%|███████▎  | 73397/100629 [57:42<22:44, 19.96it/s]

 73%|███████▎  | 73400/100629 [57:43<21:29, 21.11it/s]

 73%|███████▎  | 73403/100629 [57:43<20:30, 22.13it/s]

 73%|███████▎  | 73406/100629 [57:43<19:25, 23.36it/s]

 73%|███████▎  | 73410/100629 [57:43<17:35, 25.78it/s]

 73%|███████▎  | 73413/100629 [57:43<17:49, 25.46it/s]

 73%|███████▎  | 73417/100629 [57:43<16:29, 27.49it/s]

 73%|███████▎  | 73420/100629 [57:43<17:34, 25.79it/s]

 73%|███████▎  | 73425/100629 [57:43<14:24, 31.48it/s]

 73%|███████▎  | 73429/100629 [57:44<15:57, 28.41it/s]

 73%|███████▎  | 73432/100629 [57:44<20:29, 22.12it/s]

 73%|███████▎  | 73436/100629 [57:44<18:20, 24.71it/s]

 73%|███████▎  | 73439/100629 [57:44<19:23, 23.37it/s]

 73%|███████▎  | 73442/100629 [57:44<18:55, 23.93it/s]

 73%|███████▎  | 73445/100629 [57:44<19:04, 23.76it/s]

 73%|███████▎  | 73448/100629 [57:44<19:51, 22.81it/s]

 73%|███████▎  | 73451/100629 [57:45<18:52, 24.00it/s]

 73%|███████▎  | 73454/100629 [57:45<17:54, 25.28it/s]

 73%|███████▎  | 73458/100629 [57:45<17:53, 25.32it/s]

 73%|███████▎  | 73462/100629 [57:45<17:01, 26.59it/s]

 73%|███████▎  | 73465/100629 [57:45<17:00, 26.62it/s]

 73%|███████▎  | 73468/100629 [57:45<20:53, 21.66it/s]

 73%|███████▎  | 73471/100629 [57:45<22:41, 19.95it/s]

 73%|███████▎  | 73474/100629 [57:46<21:50, 20.73it/s]

 73%|███████▎  | 73477/100629 [57:46<21:33, 20.99it/s]

 73%|███████▎  | 73480/100629 [57:46<21:18, 21.24it/s]

 73%|███████▎  | 73484/100629 [57:46<18:34, 24.35it/s]

 73%|███████▎  | 73487/100629 [57:46<21:33, 20.98it/s]

 73%|███████▎  | 73490/100629 [57:46<21:22, 21.16it/s]

 73%|███████▎  | 73493/100629 [57:46<20:11, 22.40it/s]

 73%|███████▎  | 73496/100629 [57:47<22:02, 20.52it/s]

 73%|███████▎  | 73499/100629 [57:47<22:12, 20.35it/s]

 73%|███████▎  | 73502/100629 [57:47<20:53, 21.64it/s]

 73%|███████▎  | 73505/100629 [57:47<24:35, 18.38it/s]

 73%|███████▎  | 73509/100629 [57:47<19:48, 22.83it/s]

 73%|███████▎  | 73512/100629 [57:47<18:36, 24.29it/s]

 73%|███████▎  | 73515/100629 [57:47<21:03, 21.47it/s]

 73%|███████▎  | 73518/100629 [57:48<19:42, 22.94it/s]

 73%|███████▎  | 73521/100629 [57:48<20:01, 22.56it/s]

 73%|███████▎  | 73524/100629 [57:48<24:47, 18.22it/s]

 73%|███████▎  | 73527/100629 [57:48<22:23, 20.18it/s]

 73%|███████▎  | 73530/100629 [57:48<24:59, 18.08it/s]

 73%|███████▎  | 73534/100629 [57:48<20:05, 22.47it/s]

 73%|███████▎  | 73537/100629 [57:49<22:59, 19.64it/s]

 73%|███████▎  | 73540/100629 [57:49<25:41, 17.57it/s]

 73%|███████▎  | 73543/100629 [57:49<23:33, 19.16it/s]

 73%|███████▎  | 73546/100629 [57:49<25:34, 17.65it/s]

 73%|███████▎  | 73549/100629 [57:49<22:41, 19.88it/s]

 73%|███████▎  | 73552/100629 [57:49<22:17, 20.24it/s]

 73%|███████▎  | 73555/100629 [57:50<22:02, 20.47it/s]

 73%|███████▎  | 73558/100629 [57:50<21:35, 20.89it/s]

 73%|███████▎  | 73561/100629 [57:50<26:09, 17.25it/s]

 73%|███████▎  | 73563/100629 [57:50<25:40, 17.56it/s]

 73%|███████▎  | 73565/100629 [57:50<25:02, 18.01it/s]

 73%|███████▎  | 73567/100629 [57:50<27:36, 16.34it/s]

 73%|███████▎  | 73569/100629 [57:50<27:59, 16.11it/s]

 73%|███████▎  | 73572/100629 [57:51<23:55, 18.85it/s]

 73%|███████▎  | 73574/100629 [57:51<27:47, 16.22it/s]

 73%|███████▎  | 73576/100629 [57:51<29:03, 15.51it/s]

 73%|███████▎  | 73579/100629 [57:51<26:22, 17.09it/s]

 73%|███████▎  | 73581/100629 [57:51<25:50, 17.44it/s]

 73%|███████▎  | 73583/100629 [57:51<27:27, 16.41it/s]

 73%|███████▎  | 73585/100629 [57:51<27:43, 16.26it/s]

 73%|███████▎  | 73589/100629 [57:51<21:13, 21.24it/s]

 73%|███████▎  | 73592/100629 [57:52<20:04, 22.45it/s]

 73%|███████▎  | 73596/100629 [57:52<18:38, 24.16it/s]

 73%|███████▎  | 73599/100629 [57:52<21:14, 21.21it/s]

 73%|███████▎  | 73602/100629 [57:52<21:04, 21.38it/s]

 73%|███████▎  | 73605/100629 [57:52<24:42, 18.23it/s]

 73%|███████▎  | 73607/100629 [57:52<25:24, 17.72it/s]

 73%|███████▎  | 73610/100629 [57:52<22:13, 20.27it/s]

 73%|███████▎  | 73613/100629 [57:53<20:37, 21.84it/s]

 73%|███████▎  | 73617/100629 [57:53<18:36, 24.19it/s]

 73%|███████▎  | 73621/100629 [57:53<18:54, 23.81it/s]

 73%|███████▎  | 73624/100629 [57:53<21:34, 20.86it/s]

 73%|███████▎  | 73627/100629 [57:53<24:11, 18.60it/s]

 73%|███████▎  | 73630/100629 [57:53<21:49, 20.62it/s]

 73%|███████▎  | 73633/100629 [57:54<20:54, 21.52it/s]

 73%|███████▎  | 73636/100629 [57:54<20:40, 21.76it/s]

 73%|███████▎  | 73640/100629 [57:54<19:01, 23.63it/s]

 73%|███████▎  | 73643/100629 [57:54<24:19, 18.50it/s]

 73%|███████▎  | 73646/100629 [57:54<31:53, 14.10it/s]

 73%|███████▎  | 73652/100629 [57:55<22:25, 20.05it/s]

 73%|███████▎  | 73655/100629 [57:55<25:30, 17.63it/s]

 73%|███████▎  | 73659/100629 [57:55<21:12, 21.19it/s]

 73%|███████▎  | 73662/100629 [57:55<20:19, 22.12it/s]

 73%|███████▎  | 73665/100629 [57:55<19:40, 22.85it/s]

 73%|███████▎  | 73668/100629 [57:55<19:28, 23.08it/s]

 73%|███████▎  | 73672/100629 [57:55<16:48, 26.73it/s]

 73%|███████▎  | 73676/100629 [57:55<15:27, 29.05it/s]

 73%|███████▎  | 73680/100629 [57:56<15:33, 28.86it/s]

 73%|███████▎  | 73684/100629 [57:56<16:07, 27.86it/s]

 73%|███████▎  | 73688/100629 [57:56<15:08, 29.65it/s]

 73%|███████▎  | 73692/100629 [57:56<17:04, 26.29it/s]

 73%|███████▎  | 73696/100629 [57:56<15:42, 28.56it/s]

 73%|███████▎  | 73700/100629 [57:56<18:07, 24.76it/s]

 73%|███████▎  | 73703/100629 [57:57<19:55, 22.52it/s]

 73%|███████▎  | 73706/100629 [57:57<20:24, 21.99it/s]

 73%|███████▎  | 73710/100629 [57:57<17:37, 25.45it/s]

 73%|███████▎  | 73713/100629 [57:57<17:08, 26.17it/s]

 73%|███████▎  | 73716/100629 [57:57<18:42, 23.97it/s]

 73%|███████▎  | 73721/100629 [57:57<14:55, 30.04it/s]

 73%|███████▎  | 73725/100629 [57:57<14:37, 30.67it/s]

 73%|███████▎  | 73729/100629 [57:58<17:04, 26.26it/s]

 73%|███████▎  | 73732/100629 [57:58<18:48, 23.84it/s]

 73%|███████▎  | 73735/100629 [57:58<18:59, 23.60it/s]

 73%|███████▎  | 73738/100629 [57:58<18:26, 24.30it/s]

 73%|███████▎  | 73741/100629 [57:58<19:29, 23.00it/s]

 73%|███████▎  | 73744/100629 [57:58<22:46, 19.67it/s]

 73%|███████▎  | 73747/100629 [57:58<23:07, 19.38it/s]

 73%|███████▎  | 73750/100629 [57:59<21:58, 20.39it/s]

 73%|███████▎  | 73753/100629 [57:59<25:31, 17.55it/s]

 73%|███████▎  | 73756/100629 [57:59<24:01, 18.64it/s]

 73%|███████▎  | 73758/100629 [57:59<25:11, 17.78it/s]

 73%|███████▎  | 73760/100629 [57:59<26:25, 16.94it/s]

 73%|███████▎  | 73763/100629 [57:59<25:15, 17.72it/s]

 73%|███████▎  | 73766/100629 [58:00<23:58, 18.68it/s]

 73%|███████▎  | 73769/100629 [58:00<23:20, 19.18it/s]

 73%|███████▎  | 73771/100629 [58:00<24:59, 17.91it/s]

 73%|███████▎  | 73773/100629 [58:00<24:41, 18.12it/s]

 73%|███████▎  | 73776/100629 [58:00<22:38, 19.77it/s]

 73%|███████▎  | 73778/100629 [58:00<24:50, 18.02it/s]

 73%|███████▎  | 73781/100629 [58:00<22:22, 20.00it/s]

 73%|███████▎  | 73786/100629 [58:00<17:14, 25.96it/s]

 73%|███████▎  | 73789/100629 [58:01<17:41, 25.27it/s]

 73%|███████▎  | 73792/100629 [58:01<17:49, 25.09it/s]

 73%|███████▎  | 73795/100629 [58:01<19:29, 22.95it/s]

 73%|███████▎  | 73798/100629 [58:01<20:37, 21.68it/s]

 73%|███████▎  | 73801/100629 [58:01<20:34, 21.73it/s]

 73%|███████▎  | 73804/100629 [58:01<19:35, 22.81it/s]

 73%|███████▎  | 73807/100629 [58:01<19:05, 23.41it/s]

 73%|███████▎  | 73810/100629 [58:02<22:57, 19.46it/s]

 73%|███████▎  | 73813/100629 [58:02<22:13, 20.11it/s]

 73%|███████▎  | 73816/100629 [58:02<20:51, 21.43it/s]

 73%|███████▎  | 73819/100629 [58:02<21:10, 21.11it/s]

 73%|███████▎  | 73822/100629 [58:02<19:33, 22.85it/s]

 73%|███████▎  | 73825/100629 [58:02<20:52, 21.40it/s]

 73%|███████▎  | 73829/100629 [58:02<17:48, 25.08it/s]

 73%|███████▎  | 73832/100629 [58:02<19:10, 23.29it/s]

 73%|███████▎  | 73835/100629 [58:03<18:08, 24.62it/s]

 73%|███████▎  | 73838/100629 [58:03<17:47, 25.10it/s]

 73%|███████▎  | 73841/100629 [58:03<20:02, 22.27it/s]

 73%|███████▎  | 73844/100629 [58:03<19:37, 22.75it/s]

 73%|███████▎  | 73847/100629 [58:03<18:18, 24.38it/s]

 73%|███████▎  | 73850/100629 [58:03<21:14, 21.01it/s]

 73%|███████▎  | 73853/100629 [58:03<23:11, 19.25it/s]

 73%|███████▎  | 73856/100629 [58:04<21:01, 21.23it/s]

 73%|███████▎  | 73859/100629 [58:04<20:25, 21.84it/s]

 73%|███████▎  | 73862/100629 [58:04<20:40, 21.57it/s]

 73%|███████▎  | 73865/100629 [58:04<21:48, 20.46it/s]

 73%|███████▎  | 73869/100629 [58:04<18:44, 23.79it/s]

 73%|███████▎  | 73872/100629 [58:04<18:13, 24.47it/s]

 73%|███████▎  | 73876/100629 [58:04<15:50, 28.15it/s]

 73%|███████▎  | 73880/100629 [58:04<14:41, 30.33it/s]

 73%|███████▎  | 73884/100629 [58:05<17:45, 25.10it/s]

 73%|███████▎  | 73887/100629 [58:05<22:24, 19.89it/s]

 73%|███████▎  | 73890/100629 [58:05<22:55, 19.44it/s]

 73%|███████▎  | 73895/100629 [58:05<18:53, 23.59it/s]

 73%|███████▎  | 73898/100629 [58:05<19:31, 22.82it/s]

 73%|███████▎  | 73902/100629 [58:06<21:39, 20.56it/s]

 73%|███████▎  | 73905/100629 [58:06<20:24, 21.83it/s]

 73%|███████▎  | 73908/100629 [58:06<22:12, 20.05it/s]

 73%|███████▎  | 73911/100629 [58:06<22:49, 19.51it/s]

 73%|███████▎  | 73914/100629 [58:06<24:50, 17.92it/s]

 73%|███████▎  | 73916/100629 [58:06<26:15, 16.95it/s]

 73%|███████▎  | 73918/100629 [58:07<33:21, 13.35it/s]

 73%|███████▎  | 73921/100629 [58:07<28:32, 15.60it/s]

 73%|███████▎  | 73923/100629 [58:07<27:06, 16.42it/s]

 73%|███████▎  | 73925/100629 [58:07<26:45, 16.63it/s]

 73%|███████▎  | 73928/100629 [58:07<23:32, 18.91it/s]

 73%|███████▎  | 73932/100629 [58:07<23:46, 18.72it/s]

 73%|███████▎  | 73935/100629 [58:07<22:05, 20.14it/s]

 73%|███████▎  | 73938/100629 [58:08<22:44, 19.56it/s]

 73%|███████▎  | 73941/100629 [58:08<24:29, 18.16it/s]

 73%|███████▎  | 73944/100629 [58:08<21:36, 20.58it/s]

 73%|███████▎  | 73947/100629 [58:08<20:07, 22.10it/s]

 73%|███████▎  | 73951/100629 [58:08<18:32, 23.99it/s]

 73%|███████▎  | 73954/100629 [58:09<26:44, 16.62it/s]

 73%|███████▎  | 73957/100629 [58:09<25:14, 17.61it/s]

 73%|███████▎  | 73962/100629 [58:09<24:12, 18.36it/s]

 74%|███████▎  | 73965/100629 [58:09<26:50, 16.56it/s]

 74%|███████▎  | 73968/100629 [58:09<24:26, 18.18it/s]

 74%|███████▎  | 73971/100629 [58:10<28:53, 15.38it/s]

 74%|███████▎  | 73975/100629 [58:10<24:56, 17.81it/s]

 74%|███████▎  | 73978/100629 [58:10<22:51, 19.44it/s]

 74%|███████▎  | 73982/100629 [58:10<19:17, 23.03it/s]

 74%|███████▎  | 73985/100629 [58:10<19:30, 22.77it/s]

 74%|███████▎  | 73988/100629 [58:10<19:39, 22.58it/s]

 74%|███████▎  | 73994/100629 [58:10<14:53, 29.82it/s]

 74%|███████▎  | 73999/100629 [58:10<13:51, 32.04it/s]

 74%|███████▎  | 74003/100629 [58:11<14:41, 30.22it/s]

 74%|███████▎  | 74007/100629 [58:11<16:40, 26.61it/s]

 74%|███████▎  | 74010/100629 [58:11<17:48, 24.92it/s]

 74%|███████▎  | 74013/100629 [58:11<18:04, 24.55it/s]

 74%|███████▎  | 74017/100629 [58:11<15:52, 27.93it/s]

 74%|███████▎  | 74020/100629 [58:11<15:36, 28.41it/s]

 74%|███████▎  | 74023/100629 [58:11<17:56, 24.72it/s]

 74%|███████▎  | 74026/100629 [58:12<19:40, 22.53it/s]

 74%|███████▎  | 74029/100629 [58:12<20:07, 22.02it/s]

 74%|███████▎  | 74032/100629 [58:12<22:03, 20.09it/s]

 74%|███████▎  | 74035/100629 [58:12<22:43, 19.50it/s]

 74%|███████▎  | 74039/100629 [58:12<18:39, 23.75it/s]

 74%|███████▎  | 74042/100629 [58:12<21:42, 20.41it/s]

 74%|███████▎  | 74045/100629 [58:13<21:12, 20.89it/s]

 74%|███████▎  | 74048/100629 [58:13<19:23, 22.85it/s]

 74%|███████▎  | 74051/100629 [58:13<18:13, 24.30it/s]

 74%|███████▎  | 74054/100629 [58:13<18:00, 24.59it/s]

 74%|███████▎  | 74057/100629 [58:13<18:37, 23.78it/s]

 74%|███████▎  | 74061/100629 [58:13<16:47, 26.36it/s]

 74%|███████▎  | 74065/100629 [58:13<15:38, 28.30it/s]

 74%|███████▎  | 74070/100629 [58:13<13:23, 33.05it/s]

 74%|███████▎  | 74075/100629 [58:13<13:28, 32.85it/s]

 74%|███████▎  | 74079/100629 [58:14<14:40, 30.14it/s]

 74%|███████▎  | 74083/100629 [58:14<19:14, 23.00it/s]

 74%|███████▎  | 74087/100629 [58:14<19:03, 23.20it/s]

 74%|███████▎  | 74090/100629 [58:14<19:31, 22.65it/s]

 74%|███████▎  | 74093/100629 [58:14<19:38, 22.52it/s]

 74%|███████▎  | 74096/100629 [58:14<18:32, 23.84it/s]

 74%|███████▎  | 74099/100629 [58:15<20:08, 21.94it/s]

 74%|███████▎  | 74102/100629 [58:15<20:48, 21.25it/s]

 74%|███████▎  | 74105/100629 [58:15<19:44, 22.40it/s]

 74%|███████▎  | 74108/100629 [58:15<18:20, 24.10it/s]

 74%|███████▎  | 74111/100629 [58:15<20:48, 21.24it/s]

 74%|███████▎  | 74114/100629 [58:15<25:25, 17.38it/s]

 74%|███████▎  | 74116/100629 [58:16<28:22, 15.58it/s]

 74%|███████▎  | 74120/100629 [58:16<23:00, 19.20it/s]

 74%|███████▎  | 74123/100629 [58:16<21:24, 20.64it/s]

 74%|███████▎  | 74126/100629 [58:16<19:59, 22.10it/s]

 74%|███████▎  | 74129/100629 [58:16<20:36, 21.42it/s]

 74%|███████▎  | 74132/100629 [58:16<19:27, 22.70it/s]

 74%|███████▎  | 74136/100629 [58:16<18:44, 23.57it/s]

 74%|███████▎  | 74139/100629 [58:17<21:28, 20.55it/s]

 74%|███████▎  | 74142/100629 [58:17<19:37, 22.50it/s]

 74%|███████▎  | 74145/100629 [58:17<21:58, 20.08it/s]

 74%|███████▎  | 74148/100629 [58:17<22:13, 19.86it/s]

 74%|███████▎  | 74151/100629 [58:17<21:29, 20.53it/s]

 74%|███████▎  | 74154/100629 [58:17<20:52, 21.13it/s]

 74%|███████▎  | 74157/100629 [58:17<21:41, 20.35it/s]

 74%|███████▎  | 74160/100629 [58:18<25:16, 17.45it/s]

 74%|███████▎  | 74162/100629 [58:18<24:57, 17.67it/s]

 74%|███████▎  | 74165/100629 [58:18<22:36, 19.51it/s]

 74%|███████▎  | 74168/100629 [58:18<23:48, 18.52it/s]

 74%|███████▎  | 74170/100629 [58:18<25:55, 17.01it/s]

 74%|███████▎  | 74174/100629 [58:18<21:16, 20.73it/s]

 74%|███████▎  | 74177/100629 [58:18<19:57, 22.08it/s]

 74%|███████▎  | 74180/100629 [58:19<18:36, 23.69it/s]

 74%|███████▎  | 74183/100629 [58:19<19:43, 22.34it/s]

 74%|███████▎  | 74186/100629 [58:19<19:35, 22.49it/s]

 74%|███████▎  | 74189/100629 [58:19<20:31, 21.47it/s]

 74%|███████▎  | 74192/100629 [58:19<21:45, 20.25it/s]

 74%|███████▎  | 74196/100629 [58:19<19:37, 22.44it/s]

 74%|███████▎  | 74199/100629 [58:19<18:45, 23.48it/s]

 74%|███████▎  | 74202/100629 [58:20<17:44, 24.84it/s]

 74%|███████▎  | 74205/100629 [58:20<19:19, 22.79it/s]

 74%|███████▎  | 74208/100629 [58:20<18:37, 23.64it/s]

 74%|███████▎  | 74212/100629 [58:20<16:37, 26.48it/s]

 74%|███████▍  | 74215/100629 [58:20<18:52, 23.31it/s]

 74%|███████▍  | 74219/100629 [58:20<17:34, 25.05it/s]

 74%|███████▍  | 74222/100629 [58:20<18:57, 23.21it/s]

 74%|███████▍  | 74225/100629 [58:21<20:11, 21.79it/s]

 74%|███████▍  | 74228/100629 [58:21<18:59, 23.18it/s]

 74%|███████▍  | 74232/100629 [58:21<17:40, 24.89it/s]

 74%|███████▍  | 74235/100629 [58:21<18:03, 24.36it/s]

 74%|███████▍  | 74238/100629 [58:21<19:18, 22.79it/s]

 74%|███████▍  | 74241/100629 [58:21<19:19, 22.76it/s]

 74%|███████▍  | 74244/100629 [58:21<19:50, 22.16it/s]

 74%|███████▍  | 74247/100629 [58:21<18:28, 23.81it/s]

 74%|███████▍  | 74250/100629 [58:22<17:56, 24.51it/s]

 74%|███████▍  | 74253/100629 [58:22<17:46, 24.74it/s]

 74%|███████▍  | 74256/100629 [58:22<17:53, 24.57it/s]

 74%|███████▍  | 74261/100629 [58:22<15:22, 28.60it/s]

 74%|███████▍  | 74264/100629 [58:22<18:32, 23.71it/s]

 74%|███████▍  | 74267/100629 [58:22<17:39, 24.87it/s]

 74%|███████▍  | 74270/100629 [58:22<18:49, 23.33it/s]

 74%|███████▍  | 74273/100629 [58:23<18:39, 23.54it/s]

 74%|███████▍  | 74276/100629 [58:23<19:47, 22.20it/s]

 74%|███████▍  | 74279/100629 [58:23<18:27, 23.80it/s]

 74%|███████▍  | 74282/100629 [58:23<23:28, 18.71it/s]

 74%|███████▍  | 74285/100629 [58:23<27:22, 16.04it/s]

 74%|███████▍  | 74289/100629 [58:23<22:36, 19.41it/s]

 74%|███████▍  | 74292/100629 [58:24<21:09, 20.74it/s]

 74%|███████▍  | 74295/100629 [58:24<21:11, 20.71it/s]

 74%|███████▍  | 74298/100629 [58:24<19:33, 22.45it/s]

 74%|███████▍  | 74302/100629 [58:24<17:18, 25.35it/s]

 74%|███████▍  | 74305/100629 [58:24<17:40, 24.82it/s]

 74%|███████▍  | 74308/100629 [58:24<16:51, 26.02it/s]

 74%|███████▍  | 74312/100629 [58:24<14:49, 29.57it/s]

 74%|███████▍  | 74316/100629 [58:24<16:11, 27.08it/s]

 74%|███████▍  | 74319/100629 [58:25<16:43, 26.22it/s]

 74%|███████▍  | 74322/100629 [58:25<16:37, 26.37it/s]

 74%|███████▍  | 74325/100629 [58:25<20:44, 21.14it/s]

 74%|███████▍  | 74330/100629 [58:25<16:44, 26.18it/s]

 74%|███████▍  | 74333/100629 [58:25<20:03, 21.85it/s]

 74%|███████▍  | 74337/100629 [58:25<17:49, 24.59it/s]

 74%|███████▍  | 74340/100629 [58:25<17:17, 25.33it/s]

 74%|███████▍  | 74343/100629 [58:26<20:53, 20.97it/s]

 74%|███████▍  | 74346/100629 [58:26<24:30, 17.87it/s]

 74%|███████▍  | 74349/100629 [58:26<24:20, 18.00it/s]

 74%|███████▍  | 74353/100629 [58:26<20:00, 21.89it/s]

 74%|███████▍  | 74357/100629 [58:26<19:45, 22.15it/s]

 74%|███████▍  | 74360/100629 [58:26<19:22, 22.60it/s]

 74%|███████▍  | 74364/100629 [58:27<18:36, 23.52it/s]

 74%|███████▍  | 74367/100629 [58:27<19:53, 22.01it/s]

 74%|███████▍  | 74371/100629 [58:27<19:11, 22.80it/s]

 74%|███████▍  | 74374/100629 [58:27<18:10, 24.08it/s]

 74%|███████▍  | 74377/100629 [58:27<19:33, 22.37it/s]

 74%|███████▍  | 74380/100629 [58:27<19:14, 22.74it/s]

 74%|███████▍  | 74384/100629 [58:27<18:02, 24.25it/s]

 74%|███████▍  | 74387/100629 [58:28<17:54, 24.42it/s]

 74%|███████▍  | 74390/100629 [58:28<18:02, 24.24it/s]

 74%|███████▍  | 74393/100629 [58:28<17:58, 24.33it/s]

 74%|███████▍  | 74396/100629 [58:28<21:01, 20.80it/s]

 74%|███████▍  | 74399/100629 [58:28<19:52, 22.00it/s]

 74%|███████▍  | 74402/100629 [58:28<20:35, 21.22it/s]

 74%|███████▍  | 74405/100629 [58:28<22:19, 19.58it/s]

 74%|███████▍  | 74408/100629 [58:29<22:02, 19.83it/s]

 74%|███████▍  | 74411/100629 [58:29<21:22, 20.45it/s]

 74%|███████▍  | 74415/100629 [58:29<18:38, 23.43it/s]

 74%|███████▍  | 74418/100629 [58:29<21:32, 20.28it/s]

 74%|███████▍  | 74421/100629 [58:29<19:41, 22.18it/s]

 74%|███████▍  | 74424/100629 [58:29<21:35, 20.22it/s]

 74%|███████▍  | 74428/100629 [58:30<21:31, 20.28it/s]

 74%|███████▍  | 74431/100629 [58:30<20:01, 21.81it/s]

 74%|███████▍  | 74434/100629 [58:30<19:32, 22.34it/s]

 74%|███████▍  | 74437/100629 [58:30<21:05, 20.70it/s]

 74%|███████▍  | 74440/100629 [58:30<21:04, 20.72it/s]

 74%|███████▍  | 74443/100629 [58:30<19:40, 22.18it/s]

 74%|███████▍  | 74446/100629 [58:30<19:15, 22.67it/s]

 74%|███████▍  | 74449/100629 [58:31<20:43, 21.06it/s]

 74%|███████▍  | 74454/100629 [58:31<16:21, 26.66it/s]

 74%|███████▍  | 74457/100629 [58:31<18:28, 23.61it/s]

 74%|███████▍  | 74460/100629 [58:31<19:00, 22.95it/s]

 74%|███████▍  | 74463/100629 [58:31<18:23, 23.72it/s]

 74%|███████▍  | 74466/100629 [58:31<18:00, 24.22it/s]

 74%|███████▍  | 74469/100629 [58:31<17:25, 25.02it/s]

 74%|███████▍  | 74472/100629 [58:31<17:47, 24.50it/s]

 74%|███████▍  | 74475/100629 [58:32<20:19, 21.45it/s]

 74%|███████▍  | 74479/100629 [58:32<17:23, 25.05it/s]

 74%|███████▍  | 74482/100629 [58:32<18:07, 24.04it/s]

 74%|███████▍  | 74485/100629 [58:32<17:54, 24.33it/s]

 74%|███████▍  | 74489/100629 [58:32<19:18, 22.55it/s]

 74%|███████▍  | 74492/100629 [58:32<19:13, 22.66it/s]

 74%|███████▍  | 74495/100629 [58:33<24:23, 17.85it/s]

 74%|███████▍  | 74500/100629 [58:33<18:08, 24.01it/s]

 74%|███████▍  | 74503/100629 [58:33<19:59, 21.79it/s]

 74%|███████▍  | 74506/100629 [58:33<22:20, 19.49it/s]

 74%|███████▍  | 74509/100629 [58:33<22:27, 19.38it/s]

 74%|███████▍  | 74512/100629 [58:33<21:00, 20.71it/s]

 74%|███████▍  | 74515/100629 [58:33<20:42, 21.01it/s]

 74%|███████▍  | 74518/100629 [58:34<20:14, 21.49it/s]

 74%|███████▍  | 74521/100629 [58:34<22:52, 19.02it/s]

 74%|███████▍  | 74524/100629 [58:34<21:33, 20.18it/s]

 74%|███████▍  | 74527/100629 [58:34<31:59, 13.60it/s]

 74%|███████▍  | 74529/100629 [58:34<30:12, 14.40it/s]

 74%|███████▍  | 74531/100629 [58:35<28:46, 15.11it/s]

 74%|███████▍  | 74534/100629 [58:35<24:48, 17.53it/s]

 74%|███████▍  | 74536/100629 [58:35<25:08, 17.30it/s]

 74%|███████▍  | 74539/100629 [58:35<21:43, 20.02it/s]

 74%|███████▍  | 74543/100629 [58:35<19:11, 22.65it/s]

 74%|███████▍  | 74546/100629 [58:35<21:24, 20.31it/s]

 74%|███████▍  | 74550/100629 [58:35<17:40, 24.60it/s]

 74%|███████▍  | 74553/100629 [58:35<17:51, 24.34it/s]

 74%|███████▍  | 74556/100629 [58:36<18:17, 23.75it/s]

 74%|███████▍  | 74560/100629 [58:36<18:03, 24.06it/s]

 74%|███████▍  | 74563/100629 [58:36<19:00, 22.85it/s]

 74%|███████▍  | 74567/100629 [58:36<18:01, 24.09it/s]

 74%|███████▍  | 74570/100629 [58:36<17:07, 25.37it/s]

 74%|███████▍  | 74573/100629 [58:36<24:01, 18.07it/s]

 74%|███████▍  | 74576/100629 [58:37<24:22, 17.81it/s]

 74%|███████▍  | 74579/100629 [58:37<25:11, 17.23it/s]

 74%|███████▍  | 74584/100629 [58:37<20:09, 21.53it/s]

 74%|███████▍  | 74587/100629 [58:37<26:02, 16.67it/s]

 74%|███████▍  | 74590/100629 [58:37<24:28, 17.74it/s]

 74%|███████▍  | 74593/100629 [58:37<22:14, 19.51it/s]

 74%|███████▍  | 74596/100629 [58:38<25:23, 17.09it/s]

 74%|███████▍  | 74598/100629 [58:38<24:38, 17.60it/s]

 74%|███████▍  | 74601/100629 [58:38<24:29, 17.71it/s]

 74%|███████▍  | 74605/100629 [58:38<20:24, 21.25it/s]

 74%|███████▍  | 74608/100629 [58:38<21:00, 20.64it/s]

 74%|███████▍  | 74612/100629 [58:38<17:51, 24.28it/s]

 74%|███████▍  | 74618/100629 [58:38<13:21, 32.45it/s]

 74%|███████▍  | 74622/100629 [58:39<16:35, 26.13it/s]

 74%|███████▍  | 74626/100629 [58:39<15:07, 28.67it/s]

 74%|███████▍  | 74631/100629 [58:39<14:33, 29.77it/s]

 74%|███████▍  | 74635/100629 [58:39<16:23, 26.42it/s]

 74%|███████▍  | 74638/100629 [58:39<18:04, 23.97it/s]

 74%|███████▍  | 74641/100629 [58:39<17:12, 25.17it/s]

 74%|███████▍  | 74644/100629 [58:40<18:36, 23.28it/s]

 74%|███████▍  | 74647/100629 [58:40<21:03, 20.57it/s]

 74%|███████▍  | 74650/100629 [58:40<21:39, 19.99it/s]

 74%|███████▍  | 74653/100629 [58:40<22:25, 19.31it/s]

 74%|███████▍  | 74656/100629 [58:40<20:19, 21.30it/s]

 74%|███████▍  | 74659/100629 [58:40<18:41, 23.16it/s]

 74%|███████▍  | 74662/100629 [58:40<20:47, 20.81it/s]

 74%|███████▍  | 74665/100629 [58:41<21:01, 20.58it/s]

 74%|███████▍  | 74669/100629 [58:41<17:39, 24.50it/s]

 74%|███████▍  | 74672/100629 [58:41<17:56, 24.10it/s]

 74%|███████▍  | 74675/100629 [58:41<17:27, 24.78it/s]

 74%|███████▍  | 74678/100629 [58:41<19:22, 22.32it/s]

 74%|███████▍  | 74682/100629 [58:41<18:00, 24.01it/s]

 74%|███████▍  | 74686/100629 [58:41<16:06, 26.83it/s]

 74%|███████▍  | 74689/100629 [58:42<18:19, 23.60it/s]

 74%|███████▍  | 74692/100629 [58:42<22:20, 19.35it/s]

 74%|███████▍  | 74695/100629 [58:42<20:31, 21.06it/s]

 74%|███████▍  | 74698/100629 [58:42<22:21, 19.32it/s]

 74%|███████▍  | 74701/100629 [58:42<20:26, 21.15it/s]

 74%|███████▍  | 74704/100629 [58:42<20:12, 21.38it/s]

 74%|███████▍  | 74707/100629 [58:42<18:57, 22.79it/s]

 74%|███████▍  | 74710/100629 [58:43<20:36, 20.96it/s]

 74%|███████▍  | 74713/100629 [58:43<19:59, 21.60it/s]

 74%|███████▍  | 74716/100629 [58:43<23:05, 18.71it/s]

 74%|███████▍  | 74718/100629 [58:43<25:22, 17.02it/s]

 74%|███████▍  | 74720/100629 [58:43<24:27, 17.65it/s]

 74%|███████▍  | 74722/100629 [58:43<26:25, 16.34it/s]

 74%|███████▍  | 74725/100629 [58:43<23:08, 18.66it/s]

 74%|███████▍  | 74729/100629 [58:44<20:16, 21.29it/s]

 74%|███████▍  | 74732/100629 [58:44<23:46, 18.15it/s]

 74%|███████▍  | 74737/100629 [58:44<17:35, 24.53it/s]

 74%|███████▍  | 74742/100629 [58:44<15:44, 27.40it/s]

 74%|███████▍  | 74746/100629 [58:44<15:02, 28.67it/s]

 74%|███████▍  | 74751/100629 [58:44<13:05, 32.92it/s]

 74%|███████▍  | 74755/100629 [58:45<14:32, 29.66it/s]

 74%|███████▍  | 74759/100629 [58:45<17:11, 25.09it/s]

 74%|███████▍  | 74762/100629 [58:45<19:00, 22.67it/s]

 74%|███████▍  | 74765/100629 [58:45<18:00, 23.93it/s]

 74%|███████▍  | 74768/100629 [58:45<19:24, 22.21it/s]

 74%|███████▍  | 74771/100629 [58:45<20:39, 20.86it/s]

 74%|███████▍  | 74776/100629 [58:45<16:18, 26.41it/s]

 74%|███████▍  | 74780/100629 [58:46<15:20, 28.07it/s]

 74%|███████▍  | 74783/100629 [58:46<16:54, 25.47it/s]

 74%|███████▍  | 74786/100629 [58:46<19:09, 22.48it/s]

 74%|███████▍  | 74789/100629 [58:46<20:19, 21.19it/s]

 74%|███████▍  | 74792/100629 [58:46<19:29, 22.09it/s]

 74%|███████▍  | 74795/100629 [58:46<24:03, 17.90it/s]

 74%|███████▍  | 74798/100629 [58:47<22:09, 19.43it/s]

 74%|███████▍  | 74801/100629 [58:47<24:43, 17.41it/s]

 74%|███████▍  | 74804/100629 [58:47<25:25, 16.93it/s]

 74%|███████▍  | 74807/100629 [58:47<22:58, 18.73it/s]

 74%|███████▍  | 74810/100629 [58:47<21:18, 20.19it/s]

 74%|███████▍  | 74813/100629 [58:47<19:58, 21.53it/s]

 74%|███████▍  | 74816/100629 [58:48<22:43, 18.93it/s]

 74%|███████▍  | 74819/100629 [58:48<22:13, 19.35it/s]

 74%|███████▍  | 74823/100629 [58:48<19:40, 21.86it/s]

 74%|███████▍  | 74826/100629 [58:48<20:47, 20.69it/s]

 74%|███████▍  | 74829/100629 [58:48<22:52, 18.80it/s]

 74%|███████▍  | 74831/100629 [58:48<30:15, 14.21it/s]

 74%|███████▍  | 74835/100629 [58:49<25:13, 17.04it/s]

 74%|███████▍  | 74838/100629 [58:49<22:05, 19.46it/s]

 74%|███████▍  | 74841/100629 [58:49<20:26, 21.02it/s]

 74%|███████▍  | 74844/100629 [58:49<22:28, 19.12it/s]

 74%|███████▍  | 74847/100629 [58:49<20:22, 21.09it/s]

 74%|███████▍  | 74850/100629 [58:49<20:58, 20.48it/s]

 74%|███████▍  | 74853/100629 [58:49<21:55, 19.59it/s]

 74%|███████▍  | 74856/100629 [58:50<23:29, 18.28it/s]

 74%|███████▍  | 74861/100629 [58:50<20:06, 21.37it/s]

 74%|███████▍  | 74864/100629 [58:50<19:31, 22.00it/s]

 74%|███████▍  | 74867/100629 [58:50<21:01, 20.43it/s]

 74%|███████▍  | 74870/100629 [58:50<19:57, 21.52it/s]

 74%|███████▍  | 74873/100629 [58:50<22:16, 19.27it/s]

 74%|███████▍  | 74876/100629 [58:51<25:45, 16.66it/s]

 74%|███████▍  | 74878/100629 [58:51<24:55, 17.22it/s]

 74%|███████▍  | 74882/100629 [58:51<20:37, 20.80it/s]

 74%|███████▍  | 74885/100629 [58:51<19:07, 22.44it/s]

 74%|███████▍  | 74888/100629 [58:51<19:20, 22.18it/s]

 74%|███████▍  | 74892/100629 [58:51<16:51, 25.45it/s]

 74%|███████▍  | 74895/100629 [58:51<17:02, 25.17it/s]

 74%|███████▍  | 74900/100629 [58:51<14:43, 29.11it/s]

 74%|███████▍  | 74904/100629 [58:52<13:37, 31.49it/s]

 74%|███████▍  | 74908/100629 [58:52<12:46, 33.57it/s]

 74%|███████▍  | 74914/100629 [58:52<11:18, 37.93it/s]

 74%|███████▍  | 74918/100629 [58:52<14:35, 29.37it/s]

 74%|███████▍  | 74922/100629 [58:52<14:36, 29.32it/s]

 74%|███████▍  | 74926/100629 [58:52<17:18, 24.74it/s]

 74%|███████▍  | 74929/100629 [58:53<20:01, 21.38it/s]

 74%|███████▍  | 74933/100629 [58:53<17:57, 23.84it/s]

 74%|███████▍  | 74936/100629 [58:53<18:26, 23.23it/s]

 74%|███████▍  | 74939/100629 [58:53<17:32, 24.41it/s]

 74%|███████▍  | 74943/100629 [58:53<16:33, 25.86it/s]

 74%|███████▍  | 74946/100629 [58:53<16:00, 26.75it/s]

 74%|███████▍  | 74949/100629 [58:53<18:20, 23.33it/s]

 74%|███████▍  | 74952/100629 [58:54<17:31, 24.41it/s]

 74%|███████▍  | 74956/100629 [58:54<16:08, 26.52it/s]

 74%|███████▍  | 74959/100629 [58:54<18:17, 23.38it/s]

 74%|███████▍  | 74962/100629 [58:54<20:39, 20.71it/s]

 74%|███████▍  | 74965/100629 [58:54<20:15, 21.12it/s]

 74%|███████▍  | 74968/100629 [58:54<23:56, 17.87it/s]

 75%|███████▍  | 74971/100629 [58:54<21:48, 19.61it/s]

 75%|███████▍  | 74974/100629 [58:55<20:10, 21.19it/s]

 75%|███████▍  | 74977/100629 [58:55<23:13, 18.41it/s]

 75%|███████▍  | 74980/100629 [58:55<23:15, 18.38it/s]

 75%|███████▍  | 74983/100629 [58:55<24:06, 17.73it/s]

 75%|███████▍  | 74985/100629 [58:55<25:16, 16.91it/s]

 75%|███████▍  | 74988/100629 [58:55<24:00, 17.80it/s]

 75%|███████▍  | 74990/100629 [58:56<23:38, 18.07it/s]

 75%|███████▍  | 74994/100629 [58:56<21:17, 20.06it/s]

 75%|███████▍  | 74997/100629 [58:56<20:45, 20.57it/s]

 75%|███████▍  | 75000/100629 [58:56<22:16, 19.18it/s]

 75%|███████▍  | 75003/100629 [58:56<22:29, 18.99it/s]

 75%|███████▍  | 75005/100629 [58:56<22:45, 18.76it/s]

 75%|███████▍  | 75009/100629 [58:56<18:51, 22.64it/s]

 75%|███████▍  | 75012/100629 [58:57<23:08, 18.45it/s]

 75%|███████▍  | 75015/100629 [58:57<25:06, 17.01it/s]

 75%|███████▍  | 75017/100629 [58:57<30:15, 14.11it/s]

 75%|███████▍  | 75021/100629 [58:57<23:44, 17.97it/s]

 75%|███████▍  | 75024/100629 [58:57<26:22, 16.18it/s]

 75%|███████▍  | 75029/100629 [58:58<20:31, 20.78it/s]

 75%|███████▍  | 75032/100629 [58:58<22:45, 18.74it/s]

 75%|███████▍  | 75035/100629 [58:58<21:48, 19.56it/s]

 75%|███████▍  | 75038/100629 [58:58<21:05, 20.21it/s]

 75%|███████▍  | 75042/100629 [58:58<19:02, 22.39it/s]

 75%|███████▍  | 75045/100629 [58:58<18:29, 23.06it/s]

 75%|███████▍  | 75049/100629 [58:58<17:58, 23.72it/s]

 75%|███████▍  | 75052/100629 [58:59<18:42, 22.78it/s]

 75%|███████▍  | 75055/100629 [58:59<20:23, 20.91it/s]

 75%|███████▍  | 75058/100629 [58:59<21:16, 20.03it/s]

 75%|███████▍  | 75062/100629 [58:59<18:22, 23.20it/s]

 75%|███████▍  | 75065/100629 [58:59<22:21, 19.06it/s]

 75%|███████▍  | 75068/100629 [58:59<20:51, 20.43it/s]

 75%|███████▍  | 75071/100629 [59:00<20:32, 20.74it/s]

 75%|███████▍  | 75075/100629 [59:00<17:24, 24.47it/s]

 75%|███████▍  | 75078/100629 [59:00<17:50, 23.87it/s]

 75%|███████▍  | 75082/100629 [59:00<16:29, 25.83it/s]

 75%|███████▍  | 75085/100629 [59:00<17:36, 24.17it/s]

 75%|███████▍  | 75088/100629 [59:00<17:34, 24.22it/s]

 75%|███████▍  | 75092/100629 [59:00<16:03, 26.50it/s]

 75%|███████▍  | 75096/100629 [59:00<15:29, 27.46it/s]

 75%|███████▍  | 75099/100629 [59:01<19:35, 21.72it/s]

 75%|███████▍  | 75102/100629 [59:01<21:45, 19.56it/s]

 75%|███████▍  | 75105/100629 [59:01<20:27, 20.79it/s]

 75%|███████▍  | 75109/100629 [59:01<20:48, 20.43it/s]

 75%|███████▍  | 75112/100629 [59:01<22:11, 19.17it/s]

 75%|███████▍  | 75115/100629 [59:02<23:13, 18.31it/s]

 75%|███████▍  | 75118/100629 [59:02<21:35, 19.69it/s]

 75%|███████▍  | 75121/100629 [59:02<19:56, 21.31it/s]

 75%|███████▍  | 75124/100629 [59:02<18:44, 22.68it/s]

 75%|███████▍  | 75127/100629 [59:02<19:33, 21.74it/s]

 75%|███████▍  | 75131/100629 [59:02<17:56, 23.69it/s]

 75%|███████▍  | 75134/100629 [59:02<18:56, 22.43it/s]

 75%|███████▍  | 75137/100629 [59:03<21:00, 20.22it/s]

 75%|███████▍  | 75140/100629 [59:03<25:23, 16.73it/s]

 75%|███████▍  | 75142/100629 [59:03<26:22, 16.11it/s]

 75%|███████▍  | 75145/100629 [59:03<22:43, 18.70it/s]

 75%|███████▍  | 75148/100629 [59:03<21:47, 19.49it/s]

 75%|███████▍  | 75151/100629 [59:03<22:40, 18.73it/s]

 75%|███████▍  | 75154/100629 [59:03<20:55, 20.29it/s]

 75%|███████▍  | 75158/100629 [59:04<18:01, 23.56it/s]

 75%|███████▍  | 75161/100629 [59:04<19:49, 21.42it/s]

 75%|███████▍  | 75164/100629 [59:04<19:31, 21.73it/s]

 75%|███████▍  | 75167/100629 [59:04<23:06, 18.36it/s]

 75%|███████▍  | 75169/100629 [59:04<26:10, 16.21it/s]

 75%|███████▍  | 75172/100629 [59:04<23:20, 18.18it/s]

 75%|███████▍  | 75175/100629 [59:05<25:16, 16.78it/s]

 75%|███████▍  | 75177/100629 [59:05<25:44, 16.48it/s]

 75%|███████▍  | 75181/100629 [59:05<20:45, 20.42it/s]

 75%|███████▍  | 75184/100629 [59:05<19:42, 21.52it/s]

 75%|███████▍  | 75187/100629 [59:05<18:45, 22.60it/s]

 75%|███████▍  | 75191/100629 [59:05<16:13, 26.13it/s]

 75%|███████▍  | 75194/100629 [59:05<17:11, 24.66it/s]

 75%|███████▍  | 75197/100629 [59:06<19:40, 21.54it/s]

 75%|███████▍  | 75200/100629 [59:06<19:46, 21.43it/s]

 75%|███████▍  | 75205/100629 [59:06<15:24, 27.50it/s]

 75%|███████▍  | 75208/100629 [59:06<16:26, 25.77it/s]

 75%|███████▍  | 75211/100629 [59:06<16:39, 25.44it/s]

 75%|███████▍  | 75214/100629 [59:06<17:03, 24.83it/s]

 75%|███████▍  | 75217/100629 [59:06<16:57, 24.98it/s]

 75%|███████▍  | 75220/100629 [59:07<18:50, 22.47it/s]

 75%|███████▍  | 75223/100629 [59:07<17:38, 24.00it/s]

 75%|███████▍  | 75228/100629 [59:07<15:01, 28.18it/s]

 75%|███████▍  | 75231/100629 [59:07<16:09, 26.20it/s]

 75%|███████▍  | 75235/100629 [59:07<15:59, 26.46it/s]

 75%|███████▍  | 75238/100629 [59:07<17:18, 24.46it/s]

 75%|███████▍  | 75242/100629 [59:07<16:47, 25.21it/s]

 75%|███████▍  | 75247/100629 [59:07<13:49, 30.61it/s]

 75%|███████▍  | 75251/100629 [59:08<16:35, 25.49it/s]

 75%|███████▍  | 75254/100629 [59:08<17:43, 23.85it/s]

 75%|███████▍  | 75257/100629 [59:08<19:21, 21.85it/s]

 75%|███████▍  | 75260/100629 [59:08<19:52, 21.28it/s]

 75%|███████▍  | 75264/100629 [59:08<18:13, 23.20it/s]

 75%|███████▍  | 75267/100629 [59:09<23:27, 18.02it/s]

 75%|███████▍  | 75270/100629 [59:09<25:44, 16.42it/s]

 75%|███████▍  | 75274/100629 [59:09<22:52, 18.47it/s]

 75%|███████▍  | 75277/100629 [59:09<21:28, 19.68it/s]

 75%|███████▍  | 75280/100629 [59:09<22:07, 19.10it/s]

 75%|███████▍  | 75283/100629 [59:09<20:08, 20.98it/s]

 75%|███████▍  | 75286/100629 [59:09<19:01, 22.20it/s]

 75%|███████▍  | 75289/100629 [59:10<17:57, 23.52it/s]

 75%|███████▍  | 75292/100629 [59:10<18:06, 23.31it/s]

 75%|███████▍  | 75296/100629 [59:10<17:22, 24.30it/s]

 75%|███████▍  | 75299/100629 [59:10<16:33, 25.49it/s]

 75%|███████▍  | 75302/100629 [59:10<16:06, 26.21it/s]

 75%|███████▍  | 75305/100629 [59:10<18:15, 23.12it/s]

 75%|███████▍  | 75308/100629 [59:10<22:36, 18.67it/s]

 75%|███████▍  | 75311/100629 [59:11<24:39, 17.11it/s]

 75%|███████▍  | 75313/100629 [59:11<24:07, 17.49it/s]

 75%|███████▍  | 75316/100629 [59:11<21:17, 19.81it/s]

 75%|███████▍  | 75319/100629 [59:11<21:42, 19.43it/s]

 75%|███████▍  | 75323/100629 [59:11<18:05, 23.31it/s]

 75%|███████▍  | 75326/100629 [59:11<18:54, 22.30it/s]

 75%|███████▍  | 75329/100629 [59:11<19:34, 21.54it/s]

 75%|███████▍  | 75333/100629 [59:12<17:00, 24.78it/s]

 75%|███████▍  | 75336/100629 [59:12<17:44, 23.76it/s]

 75%|███████▍  | 75339/100629 [59:12<16:57, 24.86it/s]

 75%|███████▍  | 75342/100629 [59:12<19:27, 21.65it/s]

 75%|███████▍  | 75345/100629 [59:12<22:56, 18.37it/s]

 75%|███████▍  | 75348/100629 [59:12<23:50, 17.68it/s]

 75%|███████▍  | 75351/100629 [59:13<21:35, 19.51it/s]

 75%|███████▍  | 75354/100629 [59:13<20:16, 20.78it/s]

 75%|███████▍  | 75357/100629 [59:13<18:53, 22.29it/s]

 75%|███████▍  | 75361/100629 [59:13<17:02, 24.71it/s]

 75%|███████▍  | 75364/100629 [59:13<17:44, 23.73it/s]

 75%|███████▍  | 75367/100629 [59:13<18:18, 23.00it/s]

 75%|███████▍  | 75370/100629 [59:13<19:32, 21.55it/s]

 75%|███████▍  | 75373/100629 [59:13<18:17, 23.00it/s]

 75%|███████▍  | 75376/100629 [59:14<19:19, 21.77it/s]

 75%|███████▍  | 75379/100629 [59:14<18:51, 22.33it/s]

 75%|███████▍  | 75382/100629 [59:14<22:25, 18.77it/s]

 75%|███████▍  | 75385/100629 [59:14<20:26, 20.57it/s]

 75%|███████▍  | 75388/100629 [59:14<20:50, 20.19it/s]

 75%|███████▍  | 75391/100629 [59:14<20:13, 20.80it/s]

 75%|███████▍  | 75394/100629 [59:14<20:04, 20.95it/s]

 75%|███████▍  | 75397/100629 [59:15<18:40, 22.53it/s]

 75%|███████▍  | 75400/100629 [59:15<18:04, 23.25it/s]

 75%|███████▍  | 75403/100629 [59:15<16:53, 24.89it/s]

 75%|███████▍  | 75406/100629 [59:15<18:13, 23.06it/s]

 75%|███████▍  | 75409/100629 [59:15<17:08, 24.52it/s]

 75%|███████▍  | 75413/100629 [59:15<15:32, 27.03it/s]

 75%|███████▍  | 75416/100629 [59:15<17:33, 23.93it/s]

 75%|███████▍  | 75419/100629 [59:15<16:37, 25.28it/s]

 75%|███████▍  | 75422/100629 [59:16<17:51, 23.52it/s]

 75%|███████▍  | 75425/100629 [59:16<17:13, 24.38it/s]

 75%|███████▍  | 75429/100629 [59:16<17:19, 24.25it/s]

 75%|███████▍  | 75433/100629 [59:16<15:31, 27.04it/s]

 75%|███████▍  | 75436/100629 [59:16<16:59, 24.71it/s]

 75%|███████▍  | 75439/100629 [59:16<16:19, 25.72it/s]

 75%|███████▍  | 75442/100629 [59:16<18:59, 22.11it/s]

 75%|███████▍  | 75445/100629 [59:17<18:48, 22.32it/s]

 75%|███████▍  | 75448/100629 [59:17<22:59, 18.25it/s]

 75%|███████▍  | 75451/100629 [59:17<24:22, 17.21it/s]

 75%|███████▍  | 75454/100629 [59:17<21:29, 19.52it/s]

 75%|███████▍  | 75457/100629 [59:17<20:49, 20.14it/s]

 75%|███████▍  | 75460/100629 [59:17<19:41, 21.30it/s]

 75%|███████▍  | 75463/100629 [59:18<22:32, 18.61it/s]

 75%|███████▍  | 75466/100629 [59:18<23:02, 18.20it/s]

 75%|███████▍  | 75468/100629 [59:18<24:29, 17.12it/s]

 75%|███████▍  | 75471/100629 [59:18<21:24, 19.58it/s]

 75%|███████▌  | 75475/100629 [59:18<19:21, 21.66it/s]

 75%|███████▌  | 75478/100629 [59:18<19:15, 21.76it/s]

 75%|███████▌  | 75481/100629 [59:18<17:43, 23.65it/s]

 75%|███████▌  | 75484/100629 [59:19<17:52, 23.44it/s]

 75%|███████▌  | 75487/100629 [59:19<21:31, 19.47it/s]

 75%|███████▌  | 75490/100629 [59:19<20:45, 20.18it/s]

 75%|███████▌  | 75493/100629 [59:19<21:42, 19.29it/s]

 75%|███████▌  | 75496/100629 [59:19<21:26, 19.53it/s]

 75%|███████▌  | 75500/100629 [59:19<17:57, 23.32it/s]

 75%|███████▌  | 75503/100629 [59:20<21:56, 19.09it/s]

 75%|███████▌  | 75506/100629 [59:20<21:59, 19.04it/s]

 75%|███████▌  | 75509/100629 [59:20<22:04, 18.97it/s]

 75%|███████▌  | 75512/100629 [59:20<24:10, 17.32it/s]

 75%|███████▌  | 75516/100629 [59:20<21:39, 19.33it/s]

 75%|███████▌  | 75519/100629 [59:20<24:04, 17.39it/s]

 75%|███████▌  | 75523/100629 [59:21<19:37, 21.32it/s]

 75%|███████▌  | 75526/100629 [59:21<20:44, 20.18it/s]

 75%|███████▌  | 75529/100629 [59:21<20:12, 20.71it/s]

 75%|███████▌  | 75532/100629 [59:21<23:55, 17.48it/s]

 75%|███████▌  | 75534/100629 [59:21<23:25, 17.86it/s]

 75%|███████▌  | 75538/100629 [59:21<18:58, 22.03it/s]

 75%|███████▌  | 75541/100629 [59:21<18:58, 22.03it/s]

 75%|███████▌  | 75545/100629 [59:22<16:11, 25.83it/s]

 75%|███████▌  | 75548/100629 [59:22<18:12, 22.96it/s]

 75%|███████▌  | 75551/100629 [59:22<20:04, 20.83it/s]

 75%|███████▌  | 75554/100629 [59:22<19:09, 21.80it/s]

 75%|███████▌  | 75557/100629 [59:22<20:47, 20.10it/s]

 75%|███████▌  | 75560/100629 [59:22<19:15, 21.70it/s]

 75%|███████▌  | 75563/100629 [59:23<22:14, 18.78it/s]

 75%|███████▌  | 75566/100629 [59:23<21:03, 19.84it/s]

 75%|███████▌  | 75569/100629 [59:23<20:25, 20.45it/s]

 75%|███████▌  | 75572/100629 [59:23<23:30, 17.76it/s]

 75%|███████▌  | 75574/100629 [59:23<23:47, 17.55it/s]

 75%|███████▌  | 75577/100629 [59:23<23:20, 17.89it/s]

 75%|███████▌  | 75581/100629 [59:23<19:17, 21.64it/s]

 75%|███████▌  | 75584/100629 [59:24<20:35, 20.27it/s]

 75%|███████▌  | 75587/100629 [59:24<21:29, 19.41it/s]

 75%|███████▌  | 75590/100629 [59:24<21:18, 19.58it/s]

 75%|███████▌  | 75594/100629 [59:24<18:19, 22.77it/s]

 75%|███████▌  | 75597/100629 [59:24<20:45, 20.10it/s]

 75%|███████▌  | 75600/100629 [59:24<23:12, 17.97it/s]

 75%|███████▌  | 75603/100629 [59:25<20:47, 20.06it/s]

 75%|███████▌  | 75606/100629 [59:25<22:05, 18.88it/s]

 75%|███████▌  | 75609/100629 [59:25<19:56, 20.91it/s]

 75%|███████▌  | 75612/100629 [59:25<19:23, 21.50it/s]

 75%|███████▌  | 75616/100629 [59:25<17:06, 24.37it/s]

 75%|███████▌  | 75620/100629 [59:25<17:27, 23.89it/s]

 75%|███████▌  | 75623/100629 [59:25<17:54, 23.28it/s]

 75%|███████▌  | 75626/100629 [59:26<18:28, 22.56it/s]

 75%|███████▌  | 75629/100629 [59:26<17:35, 23.68it/s]

 75%|███████▌  | 75632/100629 [59:26<18:33, 22.45it/s]

 75%|███████▌  | 75636/100629 [59:26<16:08, 25.81it/s]

 75%|███████▌  | 75639/100629 [59:26<17:25, 23.90it/s]

 75%|███████▌  | 75642/100629 [59:26<20:55, 19.90it/s]

 75%|███████▌  | 75645/100629 [59:26<19:23, 21.48it/s]

 75%|███████▌  | 75648/100629 [59:27<19:04, 21.82it/s]

 75%|███████▌  | 75651/100629 [59:27<19:57, 20.87it/s]

 75%|███████▌  | 75655/100629 [59:27<16:37, 25.05it/s]

 75%|███████▌  | 75658/100629 [59:27<16:52, 24.67it/s]

 75%|███████▌  | 75663/100629 [59:27<13:31, 30.77it/s]

 75%|███████▌  | 75667/100629 [59:27<16:32, 25.16it/s]

 75%|███████▌  | 75670/100629 [59:27<18:28, 22.51it/s]

 75%|███████▌  | 75673/100629 [59:28<19:09, 21.70it/s]

 75%|███████▌  | 75677/100629 [59:28<16:27, 25.26it/s]

 75%|███████▌  | 75680/100629 [59:28<16:15, 25.57it/s]

 75%|███████▌  | 75683/100629 [59:28<16:54, 24.58it/s]

 75%|███████▌  | 75686/100629 [59:28<24:23, 17.05it/s]

 75%|███████▌  | 75689/100629 [59:28<23:06, 17.99it/s]

 75%|███████▌  | 75692/100629 [59:28<21:59, 18.90it/s]

 75%|███████▌  | 75695/100629 [59:29<19:53, 20.89it/s]

 75%|███████▌  | 75698/100629 [59:29<20:44, 20.04it/s]

 75%|███████▌  | 75701/100629 [59:29<19:40, 21.12it/s]

 75%|███████▌  | 75704/100629 [59:29<22:12, 18.71it/s]

 75%|███████▌  | 75707/100629 [59:29<23:09, 17.94it/s]

 75%|███████▌  | 75709/100629 [59:29<23:41, 17.53it/s]

 75%|███████▌  | 75713/100629 [59:30<21:06, 19.67it/s]

 75%|███████▌  | 75716/100629 [59:30<20:52, 19.90it/s]

 75%|███████▌  | 75720/100629 [59:30<18:41, 22.21it/s]

 75%|███████▌  | 75723/100629 [59:30<20:04, 20.68it/s]

 75%|███████▌  | 75727/100629 [59:30<17:23, 23.86it/s]

 75%|███████▌  | 75730/100629 [59:30<17:20, 23.92it/s]

 75%|███████▌  | 75733/100629 [59:30<16:25, 25.26it/s]

 75%|███████▌  | 75738/100629 [59:30<13:50, 29.98it/s]

 75%|███████▌  | 75742/100629 [59:31<18:14, 22.74it/s]

 75%|███████▌  | 75745/100629 [59:31<20:43, 20.01it/s]

 75%|███████▌  | 75750/100629 [59:31<16:22, 25.31it/s]

 75%|███████▌  | 75754/100629 [59:31<15:34, 26.63it/s]

 75%|███████▌  | 75757/100629 [59:31<17:10, 24.13it/s]

 75%|███████▌  | 75760/100629 [59:31<17:11, 24.11it/s]

 75%|███████▌  | 75763/100629 [59:32<21:58, 18.86it/s]

 75%|███████▌  | 75766/100629 [59:32<20:04, 20.64it/s]

 75%|███████▌  | 75769/100629 [59:32<26:10, 15.83it/s]

 75%|███████▌  | 75771/100629 [59:32<25:14, 16.41it/s]

 75%|███████▌  | 75774/100629 [59:32<23:36, 17.55it/s]

 75%|███████▌  | 75777/100629 [59:33<20:52, 19.84it/s]

 75%|███████▌  | 75780/100629 [59:33<27:50, 14.87it/s]

 75%|███████▌  | 75783/100629 [59:33<24:24, 16.96it/s]

 75%|███████▌  | 75786/100629 [59:33<25:56, 15.96it/s]

 75%|███████▌  | 75788/100629 [59:33<26:34, 15.58it/s]

 75%|███████▌  | 75790/100629 [59:33<27:17, 15.17it/s]

 75%|███████▌  | 75793/100629 [59:34<28:12, 14.67it/s]

 75%|███████▌  | 75795/100629 [59:34<31:46, 13.02it/s]

 75%|███████▌  | 75798/100629 [59:34<26:18, 15.73it/s]

 75%|███████▌  | 75800/100629 [59:34<27:22, 15.11it/s]

 75%|███████▌  | 75805/100629 [59:34<19:44, 20.95it/s]

 75%|███████▌  | 75808/100629 [59:34<22:23, 18.47it/s]

 75%|███████▌  | 75811/100629 [59:35<23:02, 17.95it/s]

 75%|███████▌  | 75813/100629 [59:35<23:31, 17.58it/s]

 75%|███████▌  | 75817/100629 [59:35<21:51, 18.92it/s]

 75%|███████▌  | 75819/100629 [59:35<25:28, 16.23it/s]

 75%|███████▌  | 75821/100629 [59:35<26:06, 15.84it/s]

 75%|███████▌  | 75823/100629 [59:35<29:48, 13.87it/s]

 75%|███████▌  | 75826/100629 [59:36<27:42, 14.92it/s]

 75%|███████▌  | 75829/100629 [59:36<23:54, 17.28it/s]

 75%|███████▌  | 75832/100629 [59:36<26:44, 15.45it/s]

 75%|███████▌  | 75834/100629 [59:36<30:20, 13.62it/s]

 75%|███████▌  | 75836/100629 [59:36<30:30, 13.55it/s]

 75%|███████▌  | 75838/100629 [59:37<32:24, 12.75it/s]

 75%|███████▌  | 75841/100629 [59:37<26:56, 15.33it/s]

 75%|███████▌  | 75843/100629 [59:37<27:43, 14.90it/s]

 75%|███████▌  | 75846/100629 [59:37<23:45, 17.39it/s]

 75%|███████▌  | 75849/100629 [59:37<22:15, 18.55it/s]

 75%|███████▌  | 75851/100629 [59:37<23:38, 17.46it/s]

 75%|███████▌  | 75853/100629 [59:37<24:19, 16.98it/s]

 75%|███████▌  | 75856/100629 [59:37<20:51, 19.80it/s]

 75%|███████▌  | 75861/100629 [59:38<16:30, 25.01it/s]

 75%|███████▌  | 75864/100629 [59:38<15:49, 26.08it/s]

 75%|███████▌  | 75868/100629 [59:38<15:15, 27.04it/s]

 75%|███████▌  | 75871/100629 [59:38<19:24, 21.26it/s]

 75%|███████▌  | 75874/100629 [59:38<21:36, 19.09it/s]

 75%|███████▌  | 75877/100629 [59:38<20:03, 20.56it/s]

 75%|███████▌  | 75881/100629 [59:38<17:16, 23.87it/s]

 75%|███████▌  | 75884/100629 [59:39<17:42, 23.30it/s]

 75%|███████▌  | 75887/100629 [59:39<20:18, 20.30it/s]

 75%|███████▌  | 75892/100629 [59:39<17:22, 23.72it/s]

 75%|███████▌  | 75895/100629 [59:39<16:27, 25.04it/s]

 75%|███████▌  | 75899/100629 [59:39<14:50, 27.77it/s]

 75%|███████▌  | 75902/100629 [59:39<17:19, 23.78it/s]

 75%|███████▌  | 75906/100629 [59:39<15:17, 26.93it/s]

 75%|███████▌  | 75909/100629 [59:40<16:24, 25.10it/s]

 75%|███████▌  | 75912/100629 [59:40<16:25, 25.09it/s]

 75%|███████▌  | 75915/100629 [59:40<17:42, 23.25it/s]

 75%|███████▌  | 75918/100629 [59:40<20:49, 19.78it/s]

 75%|███████▌  | 75921/100629 [59:40<22:11, 18.56it/s]

 75%|███████▌  | 75924/100629 [59:40<21:17, 19.34it/s]

 75%|███████▌  | 75927/100629 [59:41<21:57, 18.75it/s]

 75%|███████▌  | 75930/100629 [59:41<19:58, 20.60it/s]

 75%|███████▌  | 75933/100629 [59:41<22:15, 18.49it/s]

 75%|███████▌  | 75937/100629 [59:41<18:03, 22.79it/s]

 75%|███████▌  | 75940/100629 [59:41<20:57, 19.63it/s]

 75%|███████▌  | 75943/100629 [59:41<21:27, 19.18it/s]

 75%|███████▌  | 75948/100629 [59:42<20:07, 20.44it/s]

 75%|███████▌  | 75952/100629 [59:42<19:10, 21.44it/s]

 75%|███████▌  | 75955/100629 [59:42<21:50, 18.82it/s]

 75%|███████▌  | 75957/100629 [59:42<23:17, 17.66it/s]

 75%|███████▌  | 75960/100629 [59:42<21:00, 19.58it/s]

 75%|███████▌  | 75963/100629 [59:42<19:16, 21.34it/s]

 75%|███████▌  | 75966/100629 [59:42<18:26, 22.28it/s]

 75%|███████▌  | 75969/100629 [59:43<17:21, 23.67it/s]

 75%|███████▌  | 75972/100629 [59:43<19:10, 21.43it/s]

 76%|███████▌  | 75975/100629 [59:43<19:02, 21.57it/s]

 76%|███████▌  | 75979/100629 [59:43<17:14, 23.83it/s]

 76%|███████▌  | 75984/100629 [59:43<14:50, 27.67it/s]

 76%|███████▌  | 75988/100629 [59:43<13:57, 29.43it/s]

 76%|███████▌  | 75993/100629 [59:43<12:22, 33.19it/s]

 76%|███████▌  | 75997/100629 [59:44<12:43, 32.27it/s]

 76%|███████▌  | 76001/100629 [59:44<14:33, 28.19it/s]

 76%|███████▌  | 76004/100629 [59:44<16:42, 24.57it/s]

 76%|███████▌  | 76007/100629 [59:44<16:20, 25.12it/s]

 76%|███████▌  | 76010/100629 [59:44<19:42, 20.82it/s]

 76%|███████▌  | 76013/100629 [59:44<20:37, 19.90it/s]

 76%|███████▌  | 76016/100629 [59:44<18:54, 21.69it/s]

 76%|███████▌  | 76019/100629 [59:45<17:56, 22.86it/s]

 76%|███████▌  | 76022/100629 [59:45<20:14, 20.27it/s]

 76%|███████▌  | 76025/100629 [59:45<19:49, 20.68it/s]

 76%|███████▌  | 76028/100629 [59:45<19:32, 20.99it/s]

 76%|███████▌  | 76031/100629 [59:45<19:04, 21.50it/s]

 76%|███████▌  | 76034/100629 [59:45<20:03, 20.43it/s]

 76%|███████▌  | 76037/100629 [59:46<21:57, 18.67it/s]

 76%|███████▌  | 76041/100629 [59:46<18:59, 21.57it/s]

 76%|███████▌  | 76044/100629 [59:46<26:11, 15.65it/s]

 76%|███████▌  | 76047/100629 [59:46<24:46, 16.54it/s]

 76%|███████▌  | 76049/100629 [59:46<28:00, 14.63it/s]

 76%|███████▌  | 76052/100629 [59:47<24:59, 16.39it/s]

 76%|███████▌  | 76054/100629 [59:47<25:14, 16.22it/s]

 76%|███████▌  | 76056/100629 [59:47<27:19, 14.99it/s]

 76%|███████▌  | 76058/100629 [59:47<26:00, 15.74it/s]

 76%|███████▌  | 76062/100629 [59:47<19:36, 20.88it/s]

 76%|███████▌  | 76065/100629 [59:47<17:53, 22.88it/s]

 76%|███████▌  | 76068/100629 [59:47<16:54, 24.22it/s]

 76%|███████▌  | 76072/100629 [59:47<14:39, 27.91it/s]

 76%|███████▌  | 76075/100629 [59:48<18:09, 22.54it/s]

 76%|███████▌  | 76078/100629 [59:48<18:37, 21.98it/s]

 76%|███████▌  | 76082/100629 [59:48<17:09, 23.84it/s]

 76%|███████▌  | 76085/100629 [59:48<16:28, 24.83it/s]

 76%|███████▌  | 76088/100629 [59:48<16:50, 24.28it/s]

 76%|███████▌  | 76092/100629 [59:48<15:43, 26.02it/s]

 76%|███████▌  | 76095/100629 [59:48<18:16, 22.38it/s]

 76%|███████▌  | 76099/100629 [59:49<17:58, 22.74it/s]

 76%|███████▌  | 76102/100629 [59:49<18:52, 21.66it/s]

 76%|███████▌  | 76105/100629 [59:49<19:30, 20.95it/s]

 76%|███████▌  | 76108/100629 [59:49<23:12, 17.61it/s]

 76%|███████▌  | 76113/100629 [59:49<17:35, 23.24it/s]

 76%|███████▌  | 76116/100629 [59:49<18:41, 21.86it/s]

 76%|███████▌  | 76120/100629 [59:49<16:40, 24.49it/s]

 76%|███████▌  | 76124/100629 [59:50<15:53, 25.70it/s]

 76%|███████▌  | 76128/100629 [59:50<16:04, 25.40it/s]

 76%|███████▌  | 76131/100629 [59:50<17:53, 22.81it/s]

 76%|███████▌  | 76135/100629 [59:50<15:41, 26.03it/s]

 76%|███████▌  | 76138/100629 [59:50<16:04, 25.39it/s]

 76%|███████▌  | 76141/100629 [59:50<17:06, 23.86it/s]

 76%|███████▌  | 76144/100629 [59:50<17:47, 22.95it/s]

 76%|███████▌  | 76147/100629 [59:51<18:48, 21.70it/s]

 76%|███████▌  | 76150/100629 [59:51<18:59, 21.48it/s]

 76%|███████▌  | 76153/100629 [59:51<23:30, 17.35it/s]

 76%|███████▌  | 76158/100629 [59:51<18:30, 22.04it/s]

 76%|███████▌  | 76161/100629 [59:51<19:28, 20.94it/s]

 76%|███████▌  | 76164/100629 [59:51<17:57, 22.70it/s]

 76%|███████▌  | 76167/100629 [59:52<18:30, 22.03it/s]

 76%|███████▌  | 76170/100629 [59:52<19:04, 21.37it/s]

 76%|███████▌  | 76174/100629 [59:52<16:05, 25.32it/s]

 76%|███████▌  | 76177/100629 [59:52<17:55, 22.73it/s]

 76%|███████▌  | 76180/100629 [59:52<19:13, 21.20it/s]

 76%|███████▌  | 76183/100629 [59:52<18:13, 22.36it/s]

 76%|███████▌  | 76187/100629 [59:52<17:18, 23.53it/s]

 76%|███████▌  | 76191/100629 [59:53<16:04, 25.33it/s]

 76%|███████▌  | 76195/100629 [59:53<16:20, 24.93it/s]

 76%|███████▌  | 76198/100629 [59:53<17:56, 22.69it/s]

 76%|███████▌  | 76203/100629 [59:53<15:10, 26.84it/s]

 76%|███████▌  | 76206/100629 [59:53<15:10, 26.81it/s]

 76%|███████▌  | 76209/100629 [59:53<17:40, 23.04it/s]

 76%|███████▌  | 76212/100629 [59:54<19:11, 21.20it/s]

 76%|███████▌  | 76215/100629 [59:54<19:25, 20.95it/s]

 76%|███████▌  | 76218/100629 [59:54<20:45, 19.60it/s]

 76%|███████▌  | 76221/100629 [59:54<24:31, 16.59it/s]

 76%|███████▌  | 76223/100629 [59:54<25:40, 15.84it/s]

 76%|███████▌  | 76227/100629 [59:54<20:03, 20.28it/s]

 76%|███████▌  | 76230/100629 [59:55<22:12, 18.31it/s]

 76%|███████▌  | 76233/100629 [59:55<20:59, 19.37it/s]

 76%|███████▌  | 76236/100629 [59:55<20:44, 19.59it/s]

 76%|███████▌  | 76239/100629 [59:55<21:27, 18.94it/s]

 76%|███████▌  | 76241/100629 [59:55<21:57, 18.52it/s]

 76%|███████▌  | 76243/100629 [59:55<23:29, 17.30it/s]

 76%|███████▌  | 76245/100629 [59:55<22:47, 17.83it/s]

 76%|███████▌  | 76247/100629 [59:55<22:45, 17.85it/s]

 76%|███████▌  | 76252/100629 [59:56<18:34, 21.87it/s]

 76%|███████▌  | 76255/100629 [59:56<19:30, 20.82it/s]

 76%|███████▌  | 76258/100629 [59:56<18:17, 22.20it/s]

 76%|███████▌  | 76261/100629 [59:56<17:00, 23.87it/s]

 76%|███████▌  | 76264/100629 [59:56<17:11, 23.61it/s]

 76%|███████▌  | 76267/100629 [59:56<19:07, 21.23it/s]

 76%|███████▌  | 76272/100629 [59:56<17:01, 23.85it/s]

 76%|███████▌  | 76275/100629 [59:57<16:30, 24.58it/s]

 76%|███████▌  | 76278/100629 [59:57<18:26, 22.00it/s]

 76%|███████▌  | 76281/100629 [59:57<17:29, 23.20it/s]

 76%|███████▌  | 76284/100629 [59:57<18:39, 21.75it/s]

 76%|███████▌  | 76287/100629 [59:57<19:20, 20.98it/s]

 76%|███████▌  | 76292/100629 [59:57<15:52, 25.55it/s]

 76%|███████▌  | 76295/100629 [59:58<19:05, 21.25it/s]

 76%|███████▌  | 76298/100629 [59:58<17:50, 22.73it/s]

 76%|███████▌  | 76301/100629 [59:58<17:22, 23.34it/s]

 76%|███████▌  | 76304/100629 [59:58<20:37, 19.66it/s]

 76%|███████▌  | 76307/100629 [59:58<18:56, 21.40it/s]

 76%|███████▌  | 76310/100629 [59:58<17:47, 22.78it/s]

 76%|███████▌  | 76313/100629 [59:58<19:16, 21.02it/s]

 76%|███████▌  | 76316/100629 [59:59<18:41, 21.68it/s]

 76%|███████▌  | 76319/100629 [59:59<18:05, 22.40it/s]

 76%|███████▌  | 76322/100629 [59:59<18:44, 21.62it/s]

 76%|███████▌  | 76325/100629 [59:59<21:07, 19.17it/s]

 76%|███████▌  | 76328/100629 [59:59<22:58, 17.63it/s]

 76%|███████▌  | 76331/100629 [59:59<22:07, 18.30it/s]

 76%|███████▌  | 76334/100629 [59:59<21:05, 19.20it/s]

 76%|███████▌  | 76336/100629 [1:00:00<21:43, 18.63it/s]

 76%|███████▌  | 76339/100629 [1:00:00<19:35, 20.66it/s]

 76%|███████▌  | 76342/100629 [1:00:00<18:58, 21.33it/s]

 76%|███████▌  | 76347/100629 [1:00:00<15:28, 26.15it/s]

 76%|███████▌  | 76350/100629 [1:00:00<19:39, 20.58it/s]

 76%|███████▌  | 76353/100629 [1:00:00<18:55, 21.37it/s]

 76%|███████▌  | 76356/100629 [1:00:01<26:59, 14.99it/s]

 76%|███████▌  | 76358/100629 [1:00:01<28:14, 14.32it/s]

 76%|███████▌  | 76361/100629 [1:00:01<26:22, 15.33it/s]

 76%|███████▌  | 76364/100629 [1:00:01<23:24, 17.27it/s]

 76%|███████▌  | 76367/100629 [1:00:01<20:43, 19.51it/s]

 76%|███████▌  | 76371/100629 [1:00:01<17:18, 23.36it/s]

 76%|███████▌  | 76374/100629 [1:00:02<19:48, 20.42it/s]

 76%|███████▌  | 76377/100629 [1:00:02<20:18, 19.90it/s]

 76%|███████▌  | 76380/100629 [1:00:02<18:46, 21.52it/s]

 76%|███████▌  | 76383/100629 [1:00:02<19:20, 20.89it/s]

 76%|███████▌  | 76387/100629 [1:00:02<18:23, 21.96it/s]

 76%|███████▌  | 76390/100629 [1:00:02<20:55, 19.31it/s]

 76%|███████▌  | 76393/100629 [1:00:03<21:26, 18.84it/s]

 76%|███████▌  | 76395/100629 [1:00:03<24:04, 16.78it/s]

 76%|███████▌  | 76397/100629 [1:00:03<30:12, 13.37it/s]

 76%|███████▌  | 76399/100629 [1:00:03<30:12, 13.37it/s]

 76%|███████▌  | 76402/100629 [1:00:03<24:54, 16.21it/s]

 76%|███████▌  | 76404/100629 [1:00:03<24:15, 16.64it/s]

 76%|███████▌  | 76408/100629 [1:00:03<19:18, 20.90it/s]

 76%|███████▌  | 76411/100629 [1:00:04<19:46, 20.41it/s]

 76%|███████▌  | 76415/100629 [1:00:04<16:40, 24.19it/s]

 76%|███████▌  | 76419/100629 [1:00:04<15:01, 26.84it/s]

 76%|███████▌  | 76422/100629 [1:00:04<16:35, 24.32it/s]

 76%|███████▌  | 76427/100629 [1:00:04<14:10, 28.45it/s]

 76%|███████▌  | 76431/100629 [1:00:04<14:27, 27.91it/s]

 76%|███████▌  | 76434/100629 [1:00:04<15:34, 25.90it/s]

 76%|███████▌  | 76437/100629 [1:00:04<15:23, 26.19it/s]

 76%|███████▌  | 76440/100629 [1:00:05<16:57, 23.77it/s]

 76%|███████▌  | 76443/100629 [1:00:05<18:15, 22.08it/s]

 76%|███████▌  | 76446/100629 [1:00:05<17:57, 22.43it/s]

 76%|███████▌  | 76449/100629 [1:00:05<18:04, 22.30it/s]

 76%|███████▌  | 76452/100629 [1:00:05<18:20, 21.97it/s]

 76%|███████▌  | 76455/100629 [1:00:05<17:53, 22.53it/s]

 76%|███████▌  | 76458/100629 [1:00:06<19:42, 20.45it/s]

 76%|███████▌  | 76461/100629 [1:00:06<21:20, 18.88it/s]

 76%|███████▌  | 76463/100629 [1:00:06<23:36, 17.06it/s]

 76%|███████▌  | 76468/100629 [1:00:06<18:32, 21.72it/s]

 76%|███████▌  | 76471/100629 [1:00:06<18:26, 21.84it/s]

 76%|███████▌  | 76474/100629 [1:00:06<18:05, 22.26it/s]

 76%|███████▌  | 76478/100629 [1:00:06<16:36, 24.23it/s]

 76%|███████▌  | 76482/100629 [1:00:07<17:23, 23.14it/s]

 76%|███████▌  | 76485/100629 [1:00:07<17:59, 22.37it/s]

 76%|███████▌  | 76488/100629 [1:00:07<18:39, 21.57it/s]

 76%|███████▌  | 76491/100629 [1:00:07<17:59, 22.36it/s]

 76%|███████▌  | 76494/100629 [1:00:07<20:11, 19.92it/s]

 76%|███████▌  | 76497/100629 [1:00:07<20:20, 19.78it/s]

 76%|███████▌  | 76500/100629 [1:00:07<18:38, 21.57it/s]

 76%|███████▌  | 76503/100629 [1:00:08<23:41, 16.97it/s]

 76%|███████▌  | 76508/100629 [1:00:08<19:15, 20.88it/s]

 76%|███████▌  | 76511/100629 [1:00:08<20:39, 19.46it/s]

 76%|███████▌  | 76514/100629 [1:00:08<21:12, 18.95it/s]

 76%|███████▌  | 76516/100629 [1:00:08<24:03, 16.71it/s]

 76%|███████▌  | 76518/100629 [1:00:09<23:15, 17.27it/s]

 76%|███████▌  | 76520/100629 [1:00:09<22:56, 17.52it/s]

 76%|███████▌  | 76524/100629 [1:00:09<18:55, 21.23it/s]

 76%|███████▌  | 76527/100629 [1:00:09<18:45, 21.41it/s]

 76%|███████▌  | 76530/100629 [1:00:09<21:03, 19.07it/s]

 76%|███████▌  | 76533/100629 [1:00:09<19:33, 20.53it/s]

 76%|███████▌  | 76536/100629 [1:00:09<19:26, 20.65it/s]

 76%|███████▌  | 76540/100629 [1:00:10<18:44, 21.43it/s]

 76%|███████▌  | 76543/100629 [1:00:10<20:10, 19.89it/s]

 76%|███████▌  | 76546/100629 [1:00:10<21:10, 18.95it/s]

 76%|███████▌  | 76549/100629 [1:00:10<19:18, 20.79it/s]

 76%|███████▌  | 76552/100629 [1:00:10<19:41, 20.37it/s]

 76%|███████▌  | 76555/100629 [1:00:10<18:08, 22.12it/s]

 76%|███████▌  | 76558/100629 [1:00:10<19:18, 20.77it/s]

 76%|███████▌  | 76561/100629 [1:00:11<17:35, 22.81it/s]

 76%|███████▌  | 76564/100629 [1:00:11<17:23, 23.07it/s]

 76%|███████▌  | 76567/100629 [1:00:11<19:50, 20.20it/s]

 76%|███████▌  | 76570/100629 [1:00:11<19:02, 21.06it/s]

 76%|███████▌  | 76575/100629 [1:00:11<15:11, 26.39it/s]

 76%|███████▌  | 76578/100629 [1:00:11<17:07, 23.41it/s]

 76%|███████▌  | 76581/100629 [1:00:11<17:36, 22.76it/s]

 76%|███████▌  | 76585/100629 [1:00:12<16:10, 24.79it/s]

 76%|███████▌  | 76588/100629 [1:00:12<18:24, 21.77it/s]

 76%|███████▌  | 76592/100629 [1:00:12<16:54, 23.69it/s]

 76%|███████▌  | 76595/100629 [1:00:12<18:47, 21.32it/s]

 76%|███████▌  | 76598/100629 [1:00:12<17:18, 23.15it/s]

 76%|███████▌  | 76601/100629 [1:00:12<16:17, 24.58it/s]

 76%|███████▌  | 76604/100629 [1:00:12<15:42, 25.49it/s]

 76%|███████▌  | 76607/100629 [1:00:13<17:38, 22.69it/s]

 76%|███████▌  | 76610/100629 [1:00:13<16:30, 24.24it/s]

 76%|███████▌  | 76613/100629 [1:00:13<16:33, 24.18it/s]

 76%|███████▌  | 76616/100629 [1:00:13<16:32, 24.19it/s]

 76%|███████▌  | 76619/100629 [1:00:13<18:03, 22.15it/s]

 76%|███████▌  | 76622/100629 [1:00:13<21:49, 18.34it/s]

 76%|███████▌  | 76624/100629 [1:00:13<21:53, 18.27it/s]

 76%|███████▌  | 76628/100629 [1:00:14<19:23, 20.62it/s]

 76%|███████▌  | 76631/100629 [1:00:14<18:39, 21.43it/s]

 76%|███████▌  | 76634/100629 [1:00:14<19:58, 20.03it/s]

 76%|███████▌  | 76637/100629 [1:00:14<22:37, 17.68it/s]

 76%|███████▌  | 76640/100629 [1:00:14<19:57, 20.03it/s]

 76%|███████▌  | 76643/100629 [1:00:14<18:32, 21.56it/s]

 76%|███████▌  | 76646/100629 [1:00:14<17:48, 22.44it/s]

 76%|███████▌  | 76649/100629 [1:00:15<16:47, 23.80it/s]

 76%|███████▌  | 76652/100629 [1:00:15<18:33, 21.54it/s]

 76%|███████▌  | 76655/100629 [1:00:15<20:32, 19.46it/s]

 76%|███████▌  | 76658/100629 [1:00:15<19:54, 20.06it/s]

 76%|███████▌  | 76661/100629 [1:00:15<20:55, 19.08it/s]

 76%|███████▌  | 76663/100629 [1:00:15<21:02, 18.98it/s]

 76%|███████▌  | 76667/100629 [1:00:15<17:22, 23.00it/s]

 76%|███████▌  | 76670/100629 [1:00:16<16:57, 23.55it/s]

 76%|███████▌  | 76673/100629 [1:00:16<15:59, 24.96it/s]

 76%|███████▌  | 76676/100629 [1:00:16<19:49, 20.13it/s]

 76%|███████▌  | 76679/100629 [1:00:16<18:29, 21.59it/s]

 76%|███████▌  | 76682/100629 [1:00:16<18:35, 21.47it/s]

 76%|███████▌  | 76686/100629 [1:00:16<16:43, 23.87it/s]

 76%|███████▌  | 76689/100629 [1:00:16<17:49, 22.38it/s]

 76%|███████▌  | 76692/100629 [1:00:17<17:17, 23.08it/s]

 76%|███████▌  | 76696/100629 [1:00:17<15:45, 25.31it/s]

 76%|███████▌  | 76699/100629 [1:00:17<16:14, 24.57it/s]

 76%|███████▌  | 76702/100629 [1:00:17<17:02, 23.41it/s]

 76%|███████▌  | 76707/100629 [1:00:17<15:03, 26.48it/s]

 76%|███████▌  | 76710/100629 [1:00:17<16:17, 24.46it/s]

 76%|███████▌  | 76714/100629 [1:00:17<14:20, 27.81it/s]

 76%|███████▌  | 76717/100629 [1:00:17<15:23, 25.88it/s]

 76%|███████▌  | 76721/100629 [1:00:18<14:09, 28.15it/s]

 76%|███████▌  | 76725/100629 [1:00:18<12:56, 30.78it/s]

 76%|███████▌  | 76729/100629 [1:00:18<13:49, 28.83it/s]

 76%|███████▋  | 76732/100629 [1:00:18<13:59, 28.46it/s]

 76%|███████▋  | 76735/100629 [1:00:18<15:21, 25.93it/s]

 76%|███████▋  | 76739/100629 [1:00:18<14:37, 27.22it/s]

 76%|███████▋  | 76742/100629 [1:00:18<16:50, 23.64it/s]

 76%|███████▋  | 76745/100629 [1:00:19<17:35, 22.63it/s]

 76%|███████▋  | 76749/100629 [1:00:19<16:10, 24.60it/s]

 76%|███████▋  | 76752/100629 [1:00:19<18:30, 21.49it/s]

 76%|███████▋  | 76755/100629 [1:00:19<18:54, 21.05it/s]

 76%|███████▋  | 76758/100629 [1:00:19<18:02, 22.06it/s]

 76%|███████▋  | 76761/100629 [1:00:19<17:20, 22.94it/s]

 76%|███████▋  | 76764/100629 [1:00:19<17:34, 22.64it/s]

 76%|███████▋  | 76767/100629 [1:00:20<17:10, 23.16it/s]

 76%|███████▋  | 76770/100629 [1:00:20<18:18, 21.72it/s]

 76%|███████▋  | 76773/100629 [1:00:20<17:51, 22.25it/s]

 76%|███████▋  | 76776/100629 [1:00:20<20:56, 18.98it/s]

 76%|███████▋  | 76779/100629 [1:00:20<22:27, 17.70it/s]

 76%|███████▋  | 76782/100629 [1:00:20<20:13, 19.66it/s]

 76%|███████▋  | 76785/100629 [1:00:20<19:18, 20.58it/s]

 76%|███████▋  | 76788/100629 [1:00:21<18:35, 21.37it/s]

 76%|███████▋  | 76791/100629 [1:00:21<20:45, 19.14it/s]

 76%|███████▋  | 76794/100629 [1:00:21<19:11, 20.70it/s]

 76%|███████▋  | 76798/100629 [1:00:21<16:48, 23.63it/s]

 76%|███████▋  | 76801/100629 [1:00:21<16:51, 23.56it/s]

 76%|███████▋  | 76804/100629 [1:00:21<18:02, 22.01it/s]

 76%|███████▋  | 76808/100629 [1:00:21<15:29, 25.63it/s]

 76%|███████▋  | 76811/100629 [1:00:22<16:54, 23.47it/s]

 76%|███████▋  | 76814/100629 [1:00:22<18:25, 21.54it/s]

 76%|███████▋  | 76817/100629 [1:00:22<33:33, 11.83it/s]

 76%|███████▋  | 76820/100629 [1:00:22<28:34, 13.89it/s]

 76%|███████▋  | 76824/100629 [1:00:23<21:58, 18.05it/s]

 76%|███████▋  | 76828/100629 [1:00:23<18:44, 21.16it/s]

 76%|███████▋  | 76831/100629 [1:00:23<17:27, 22.71it/s]

 76%|███████▋  | 76834/100629 [1:00:23<18:47, 21.11it/s]

 76%|███████▋  | 76837/100629 [1:00:23<20:12, 19.62it/s]

 76%|███████▋  | 76840/100629 [1:00:23<18:52, 21.01it/s]

 76%|███████▋  | 76843/100629 [1:00:23<20:08, 19.69it/s]

 76%|███████▋  | 76847/100629 [1:00:24<17:54, 22.12it/s]

 76%|███████▋  | 76850/100629 [1:00:24<20:18, 19.52it/s]

 76%|███████▋  | 76853/100629 [1:00:24<21:56, 18.06it/s]

 76%|███████▋  | 76856/100629 [1:00:24<19:41, 20.13it/s]

 76%|███████▋  | 76859/100629 [1:00:24<20:50, 19.01it/s]

 76%|███████▋  | 76862/100629 [1:00:24<18:50, 21.02it/s]

 76%|███████▋  | 76865/100629 [1:00:25<21:12, 18.68it/s]

 76%|███████▋  | 76869/100629 [1:00:25<17:54, 22.12it/s]

 76%|███████▋  | 76872/100629 [1:00:25<17:34, 22.53it/s]

 76%|███████▋  | 76875/100629 [1:00:25<18:51, 21.00it/s]

 76%|███████▋  | 76878/100629 [1:00:25<18:16, 21.66it/s]

 76%|███████▋  | 76882/100629 [1:00:25<15:36, 25.35it/s]

 76%|███████▋  | 76885/100629 [1:00:25<16:45, 23.63it/s]

 76%|███████▋  | 76888/100629 [1:00:25<16:29, 23.99it/s]

 76%|███████▋  | 76891/100629 [1:00:26<18:52, 20.97it/s]

 76%|███████▋  | 76894/100629 [1:00:26<19:37, 20.16it/s]

 76%|███████▋  | 76897/100629 [1:00:26<17:53, 22.10it/s]

 76%|███████▋  | 76901/100629 [1:00:26<16:36, 23.82it/s]

 76%|███████▋  | 76904/100629 [1:00:26<17:54, 22.09it/s]

 76%|███████▋  | 76907/100629 [1:00:26<17:49, 22.18it/s]

 76%|███████▋  | 76910/100629 [1:00:26<17:08, 23.05it/s]

 76%|███████▋  | 76913/100629 [1:00:27<19:26, 20.33it/s]

 76%|███████▋  | 76916/100629 [1:00:27<18:51, 20.95it/s]

 76%|███████▋  | 76920/100629 [1:00:27<16:02, 24.63it/s]

 76%|███████▋  | 76923/100629 [1:00:27<15:53, 24.85it/s]

 76%|███████▋  | 76927/100629 [1:00:27<15:24, 25.65it/s]

 76%|███████▋  | 76930/100629 [1:00:27<16:03, 24.60it/s]

 76%|███████▋  | 76933/100629 [1:00:27<18:32, 21.29it/s]

 76%|███████▋  | 76936/100629 [1:00:28<18:24, 21.45it/s]

 76%|███████▋  | 76939/100629 [1:00:28<18:51, 20.93it/s]

 76%|███████▋  | 76942/100629 [1:00:28<22:02, 17.91it/s]

 76%|███████▋  | 76944/100629 [1:00:28<23:06, 17.09it/s]

 76%|███████▋  | 76947/100629 [1:00:28<22:07, 17.84it/s]

 76%|███████▋  | 76949/100629 [1:00:28<22:46, 17.32it/s]

 76%|███████▋  | 76951/100629 [1:00:29<22:04, 17.88it/s]

 76%|███████▋  | 76954/100629 [1:00:29<19:33, 20.18it/s]

 76%|███████▋  | 76957/100629 [1:00:29<20:08, 19.59it/s]

 76%|███████▋  | 76960/100629 [1:00:29<20:48, 18.96it/s]

 76%|███████▋  | 76963/100629 [1:00:29<19:22, 20.36it/s]

 76%|███████▋  | 76966/100629 [1:00:29<20:02, 19.68it/s]

 76%|███████▋  | 76969/100629 [1:00:29<19:46, 19.95it/s]

 76%|███████▋  | 76972/100629 [1:00:30<19:59, 19.72it/s]

 76%|███████▋  | 76976/100629 [1:00:30<16:27, 23.96it/s]

 76%|███████▋  | 76981/100629 [1:00:30<16:20, 24.11it/s]

 77%|███████▋  | 76984/100629 [1:00:30<17:10, 22.95it/s]

 77%|███████▋  | 76988/100629 [1:00:30<14:47, 26.63it/s]

 77%|███████▋  | 76991/100629 [1:00:30<15:38, 25.20it/s]

 77%|███████▋  | 76996/100629 [1:00:30<15:52, 24.81it/s]

 77%|███████▋  | 76999/100629 [1:00:31<20:05, 19.61it/s]

 77%|███████▋  | 77002/100629 [1:00:31<23:22, 16.85it/s]

 77%|███████▋  | 77005/100629 [1:00:31<21:35, 18.24it/s]

 77%|███████▋  | 77008/100629 [1:00:31<19:48, 19.87it/s]

 77%|███████▋  | 77012/100629 [1:00:31<17:27, 22.55it/s]

 77%|███████▋  | 77016/100629 [1:00:31<15:34, 25.27it/s]

 77%|███████▋  | 77020/100629 [1:00:32<13:58, 28.15it/s]

 77%|███████▋  | 77024/100629 [1:00:32<16:40, 23.59it/s]

 77%|███████▋  | 77027/100629 [1:00:32<19:38, 20.02it/s]

 77%|███████▋  | 77030/100629 [1:00:32<20:07, 19.54it/s]

 77%|███████▋  | 77033/100629 [1:00:32<21:00, 18.71it/s]

 77%|███████▋  | 77039/100629 [1:00:32<15:07, 26.00it/s]

 77%|███████▋  | 77042/100629 [1:00:33<15:48, 24.88it/s]

 77%|███████▋  | 77047/100629 [1:00:33<14:32, 27.03it/s]

 77%|███████▋  | 77050/100629 [1:00:33<16:39, 23.59it/s]

 77%|███████▋  | 77054/100629 [1:00:33<18:57, 20.73it/s]

 77%|███████▋  | 77057/100629 [1:00:33<19:59, 19.65it/s]

 77%|███████▋  | 77060/100629 [1:00:33<19:03, 20.61it/s]

 77%|███████▋  | 77063/100629 [1:00:34<19:54, 19.73it/s]

 77%|███████▋  | 77066/100629 [1:00:34<19:25, 20.22it/s]

 77%|███████▋  | 77069/100629 [1:00:34<17:58, 21.85it/s]

 77%|███████▋  | 77072/100629 [1:00:34<19:20, 20.31it/s]

 77%|███████▋  | 77076/100629 [1:00:34<16:20, 24.03it/s]

 77%|███████▋  | 77080/100629 [1:00:34<14:37, 26.84it/s]

 77%|███████▋  | 77083/100629 [1:00:35<19:32, 20.09it/s]

 77%|███████▋  | 77086/100629 [1:00:35<20:17, 19.34it/s]

 77%|███████▋  | 77090/100629 [1:00:35<17:51, 21.96it/s]

 77%|███████▋  | 77093/100629 [1:00:35<17:07, 22.92it/s]

 77%|███████▋  | 77096/100629 [1:00:35<16:49, 23.31it/s]

 77%|███████▋  | 77101/100629 [1:00:35<13:44, 28.55it/s]

 77%|███████▋  | 77105/100629 [1:00:35<15:59, 24.51it/s]

 77%|███████▋  | 77108/100629 [1:00:36<17:28, 22.43it/s]

 77%|███████▋  | 77111/100629 [1:00:36<19:03, 20.58it/s]

 77%|███████▋  | 77114/100629 [1:00:36<20:35, 19.03it/s]

 77%|███████▋  | 77117/100629 [1:00:36<21:35, 18.15it/s]

 77%|███████▋  | 77119/100629 [1:00:36<24:04, 16.27it/s]

 77%|███████▋  | 77122/100629 [1:00:36<22:02, 17.77it/s]

 77%|███████▋  | 77124/100629 [1:00:37<26:17, 14.90it/s]

 77%|███████▋  | 77126/100629 [1:00:37<26:11, 14.95it/s]

 77%|███████▋  | 77128/100629 [1:00:37<26:06, 15.01it/s]

 77%|███████▋  | 77131/100629 [1:00:37<23:56, 16.36it/s]

 77%|███████▋  | 77133/100629 [1:00:37<22:51, 17.14it/s]

 77%|███████▋  | 77135/100629 [1:00:37<23:12, 16.87it/s]

 77%|███████▋  | 77139/100629 [1:00:37<18:24, 21.27it/s]

 77%|███████▋  | 77143/100629 [1:00:38<15:06, 25.90it/s]

 77%|███████▋  | 77146/100629 [1:00:38<14:58, 26.14it/s]

 77%|███████▋  | 77149/100629 [1:00:38<15:28, 25.30it/s]

 77%|███████▋  | 77152/100629 [1:00:38<15:58, 24.50it/s]

 77%|███████▋  | 77155/100629 [1:00:38<19:56, 19.61it/s]

 77%|███████▋  | 77158/100629 [1:00:38<19:34, 19.99it/s]

 77%|███████▋  | 77161/100629 [1:00:38<20:19, 19.24it/s]

 77%|███████▋  | 77164/100629 [1:00:39<20:07, 19.43it/s]

 77%|███████▋  | 77167/100629 [1:00:39<18:38, 20.98it/s]

 77%|███████▋  | 77170/100629 [1:00:39<19:48, 19.74it/s]

 77%|███████▋  | 77174/100629 [1:00:39<16:36, 23.53it/s]

 77%|███████▋  | 77177/100629 [1:00:39<16:03, 24.33it/s]

 77%|███████▋  | 77180/100629 [1:00:39<16:45, 23.32it/s]

 77%|███████▋  | 77183/100629 [1:00:39<16:19, 23.93it/s]

 77%|███████▋  | 77186/100629 [1:00:40<20:09, 19.38it/s]

 77%|███████▋  | 77189/100629 [1:00:40<23:44, 16.46it/s]

 77%|███████▋  | 77192/100629 [1:00:40<22:27, 17.40it/s]

 77%|███████▋  | 77195/100629 [1:00:40<20:08, 19.39it/s]

 77%|███████▋  | 77198/100629 [1:00:40<18:57, 20.61it/s]

 77%|███████▋  | 77201/100629 [1:00:40<17:14, 22.65it/s]

 77%|███████▋  | 77205/100629 [1:00:40<14:32, 26.84it/s]

 77%|███████▋  | 77208/100629 [1:00:41<14:33, 26.82it/s]

 77%|███████▋  | 77211/100629 [1:00:41<14:57, 26.08it/s]

 77%|███████▋  | 77214/100629 [1:00:41<14:54, 26.18it/s]

 77%|███████▋  | 77218/100629 [1:00:41<14:58, 26.06it/s]

 77%|███████▋  | 77221/100629 [1:00:41<15:10, 25.70it/s]

 77%|███████▋  | 77225/100629 [1:00:41<14:38, 26.63it/s]

 77%|███████▋  | 77228/100629 [1:00:41<14:49, 26.32it/s]

 77%|███████▋  | 77232/100629 [1:00:41<13:54, 28.04it/s]

 77%|███████▋  | 77235/100629 [1:00:42<15:38, 24.93it/s]

 77%|███████▋  | 77238/100629 [1:00:42<15:36, 24.97it/s]

 77%|███████▋  | 77241/100629 [1:00:42<21:13, 18.36it/s]

 77%|███████▋  | 77246/100629 [1:00:42<16:37, 23.44it/s]

 77%|███████▋  | 77249/100629 [1:00:42<16:35, 23.50it/s]

 77%|███████▋  | 77252/100629 [1:00:42<18:52, 20.64it/s]

 77%|███████▋  | 77256/100629 [1:00:43<17:18, 22.52it/s]

 77%|███████▋  | 77259/100629 [1:00:43<17:57, 21.69it/s]

 77%|███████▋  | 77262/100629 [1:00:43<18:16, 21.31it/s]

 77%|███████▋  | 77265/100629 [1:00:43<20:18, 19.17it/s]

 77%|███████▋  | 77268/100629 [1:00:43<20:34, 18.92it/s]

 77%|███████▋  | 77270/100629 [1:00:43<22:17, 17.46it/s]

 77%|███████▋  | 77273/100629 [1:00:43<20:35, 18.90it/s]

 77%|███████▋  | 77276/100629 [1:00:44<19:52, 19.58it/s]

 77%|███████▋  | 77278/100629 [1:00:44<22:55, 16.98it/s]

 77%|███████▋  | 77280/100629 [1:00:44<22:58, 16.94it/s]

 77%|███████▋  | 77282/100629 [1:00:44<24:59, 15.57it/s]

 77%|███████▋  | 77285/100629 [1:00:44<24:09, 16.10it/s]

 77%|███████▋  | 77288/100629 [1:00:44<21:36, 18.01it/s]

 77%|███████▋  | 77292/100629 [1:00:44<17:20, 22.42it/s]

 77%|███████▋  | 77297/100629 [1:00:45<14:53, 26.11it/s]

 77%|███████▋  | 77300/100629 [1:00:45<15:10, 25.61it/s]

 77%|███████▋  | 77303/100629 [1:00:45<14:46, 26.30it/s]

 77%|███████▋  | 77306/100629 [1:00:45<16:03, 24.20it/s]

 77%|███████▋  | 77309/100629 [1:00:45<16:47, 23.14it/s]

 77%|███████▋  | 77312/100629 [1:00:45<15:50, 24.53it/s]

 77%|███████▋  | 77315/100629 [1:00:45<15:25, 25.18it/s]

 77%|███████▋  | 77319/100629 [1:00:46<16:28, 23.58it/s]

 77%|███████▋  | 77322/100629 [1:00:46<18:08, 21.41it/s]

 77%|███████▋  | 77326/100629 [1:00:46<17:36, 22.06it/s]

 77%|███████▋  | 77331/100629 [1:00:46<14:58, 25.92it/s]

 77%|███████▋  | 77334/100629 [1:00:46<14:59, 25.89it/s]

 77%|███████▋  | 77339/100629 [1:00:46<12:52, 30.16it/s]

 77%|███████▋  | 77343/100629 [1:00:46<12:53, 30.10it/s]

 77%|███████▋  | 77347/100629 [1:00:47<13:52, 27.98it/s]

 77%|███████▋  | 77350/100629 [1:00:47<15:23, 25.22it/s]

 77%|███████▋  | 77354/100629 [1:00:47<13:41, 28.33it/s]

 77%|███████▋  | 77357/100629 [1:00:47<15:35, 24.87it/s]

 77%|███████▋  | 77360/100629 [1:00:47<15:27, 25.08it/s]

 77%|███████▋  | 77363/100629 [1:00:47<18:13, 21.28it/s]

 77%|███████▋  | 77367/100629 [1:00:47<16:06, 24.06it/s]

 77%|███████▋  | 77370/100629 [1:00:48<16:05, 24.09it/s]

 77%|███████▋  | 77373/100629 [1:00:48<17:34, 22.06it/s]

 77%|███████▋  | 77377/100629 [1:00:48<15:19, 25.27it/s]

 77%|███████▋  | 77380/100629 [1:00:48<15:56, 24.31it/s]

 77%|███████▋  | 77383/100629 [1:00:48<18:53, 20.51it/s]

 77%|███████▋  | 77386/100629 [1:00:48<18:52, 20.53it/s]

 77%|███████▋  | 77389/100629 [1:00:48<18:30, 20.93it/s]

 77%|███████▋  | 77392/100629 [1:00:49<20:09, 19.21it/s]

 77%|███████▋  | 77395/100629 [1:00:49<22:31, 17.20it/s]

 77%|███████▋  | 77398/100629 [1:00:49<20:07, 19.23it/s]

 77%|███████▋  | 77402/100629 [1:00:49<18:13, 21.25it/s]

 77%|███████▋  | 77405/100629 [1:00:49<17:29, 22.14it/s]

 77%|███████▋  | 77409/100629 [1:00:49<15:39, 24.70it/s]

 77%|███████▋  | 77413/100629 [1:00:50<14:34, 26.55it/s]

 77%|███████▋  | 77417/100629 [1:00:50<15:23, 25.14it/s]

 77%|███████▋  | 77420/100629 [1:00:50<17:22, 22.25it/s]

 77%|███████▋  | 77424/100629 [1:00:50<14:53, 25.97it/s]

 77%|███████▋  | 77427/100629 [1:00:50<16:39, 23.22it/s]

 77%|███████▋  | 77430/100629 [1:00:50<17:31, 22.05it/s]

 77%|███████▋  | 77433/100629 [1:00:50<19:15, 20.07it/s]

 77%|███████▋  | 77436/100629 [1:00:51<18:54, 20.44it/s]

 77%|███████▋  | 77439/100629 [1:00:51<18:57, 20.38it/s]

 77%|███████▋  | 77442/100629 [1:00:51<18:46, 20.59it/s]

 77%|███████▋  | 77445/100629 [1:00:51<18:46, 20.57it/s]

 77%|███████▋  | 77448/100629 [1:00:51<17:31, 22.05it/s]

 77%|███████▋  | 77451/100629 [1:00:51<16:39, 23.19it/s]

 77%|███████▋  | 77455/100629 [1:00:51<17:03, 22.63it/s]

 77%|███████▋  | 77459/100629 [1:00:52<15:13, 25.36it/s]

 77%|███████▋  | 77463/100629 [1:00:52<13:47, 28.00it/s]

 77%|███████▋  | 77466/100629 [1:00:52<13:37, 28.32it/s]

 77%|███████▋  | 77469/100629 [1:00:52<14:41, 26.29it/s]

 77%|███████▋  | 77472/100629 [1:00:52<15:05, 25.57it/s]

 77%|███████▋  | 77475/100629 [1:00:52<17:13, 22.40it/s]

 77%|███████▋  | 77478/100629 [1:00:52<16:45, 23.02it/s]

 77%|███████▋  | 77483/100629 [1:00:52<13:32, 28.48it/s]

 77%|███████▋  | 77486/100629 [1:00:53<15:20, 25.13it/s]

 77%|███████▋  | 77489/100629 [1:00:53<15:36, 24.72it/s]

 77%|███████▋  | 77492/100629 [1:00:53<15:16, 25.24it/s]

 77%|███████▋  | 77495/100629 [1:00:53<15:14, 25.30it/s]

 77%|███████▋  | 77498/100629 [1:00:53<15:44, 24.49it/s]

 77%|███████▋  | 77502/100629 [1:00:53<15:04, 25.58it/s]

 77%|███████▋  | 77506/100629 [1:00:53<14:17, 26.96it/s]

 77%|███████▋  | 77509/100629 [1:00:54<14:53, 25.89it/s]

 77%|███████▋  | 77512/100629 [1:00:54<20:17, 18.98it/s]

 77%|███████▋  | 77515/100629 [1:00:54<19:58, 19.29it/s]

 77%|███████▋  | 77518/100629 [1:00:54<21:07, 18.24it/s]

 77%|███████▋  | 77521/100629 [1:00:54<20:17, 18.98it/s]

 77%|███████▋  | 77524/100629 [1:00:54<18:26, 20.88it/s]

 77%|███████▋  | 77527/100629 [1:00:55<19:23, 19.85it/s]

 77%|███████▋  | 77530/100629 [1:00:55<19:50, 19.41it/s]

 77%|███████▋  | 77534/100629 [1:00:55<17:32, 21.94it/s]

 77%|███████▋  | 77537/100629 [1:00:55<17:22, 22.16it/s]

 77%|███████▋  | 77540/100629 [1:00:55<20:13, 19.02it/s]

 77%|███████▋  | 77544/100629 [1:00:55<16:54, 22.76it/s]

 77%|███████▋  | 77547/100629 [1:00:56<24:13, 15.88it/s]

 77%|███████▋  | 77549/100629 [1:00:56<29:25, 13.08it/s]

 77%|███████▋  | 77551/100629 [1:00:56<30:16, 12.71it/s]

 77%|███████▋  | 77555/100629 [1:00:56<23:46, 16.17it/s]

 77%|███████▋  | 77558/100629 [1:00:56<20:36, 18.66it/s]

 77%|███████▋  | 77561/100629 [1:00:57<22:23, 17.17it/s]

 77%|███████▋  | 77564/100629 [1:00:57<19:51, 19.36it/s]

 77%|███████▋  | 77567/100629 [1:00:57<19:11, 20.03it/s]

 77%|███████▋  | 77570/100629 [1:00:57<19:59, 19.23it/s]

 77%|███████▋  | 77573/100629 [1:00:57<22:12, 17.30it/s]

 77%|███████▋  | 77575/100629 [1:00:57<22:45, 16.88it/s]

 77%|███████▋  | 77578/100629 [1:00:57<20:01, 19.18it/s]

 77%|███████▋  | 77581/100629 [1:00:58<20:39, 18.59it/s]

 77%|███████▋  | 77583/100629 [1:00:58<23:08, 16.60it/s]

 77%|███████▋  | 77586/100629 [1:00:58<21:59, 17.47it/s]

 77%|███████▋  | 77588/100629 [1:00:58<21:50, 17.58it/s]

 77%|███████▋  | 77590/100629 [1:00:58<23:39, 16.23it/s]

 77%|███████▋  | 77593/100629 [1:00:58<21:00, 18.27it/s]

 77%|███████▋  | 77595/100629 [1:00:58<21:32, 17.83it/s]

 77%|███████▋  | 77598/100629 [1:00:59<20:35, 18.64it/s]

 77%|███████▋  | 77601/100629 [1:00:59<21:25, 17.91it/s]

 77%|███████▋  | 77603/100629 [1:00:59<21:06, 18.18it/s]

 77%|███████▋  | 77605/100629 [1:00:59<20:57, 18.30it/s]

 77%|███████▋  | 77608/100629 [1:00:59<19:04, 20.11it/s]

 77%|███████▋  | 77611/100629 [1:00:59<24:14, 15.82it/s]

 77%|███████▋  | 77613/100629 [1:01:00<25:51, 14.83it/s]

 77%|███████▋  | 77616/100629 [1:01:00<21:27, 17.88it/s]

 77%|███████▋  | 77619/100629 [1:01:00<25:36, 14.98it/s]

 77%|███████▋  | 77622/100629 [1:01:00<21:30, 17.82it/s]

 77%|███████▋  | 77626/100629 [1:01:00<17:31, 21.89it/s]

 77%|███████▋  | 77630/100629 [1:01:00<14:56, 25.66it/s]

 77%|███████▋  | 77633/100629 [1:01:00<15:28, 24.76it/s]

 77%|███████▋  | 77636/100629 [1:01:00<15:46, 24.30it/s]

 77%|███████▋  | 77640/100629 [1:01:01<15:10, 25.25it/s]

 77%|███████▋  | 77643/100629 [1:01:01<15:00, 25.53it/s]

 77%|███████▋  | 77650/100629 [1:01:01<11:44, 32.64it/s]

 77%|███████▋  | 77654/100629 [1:01:01<12:50, 29.83it/s]

 77%|███████▋  | 77658/100629 [1:01:01<14:11, 26.97it/s]

 77%|███████▋  | 77661/100629 [1:01:01<16:05, 23.80it/s]

 77%|███████▋  | 77664/100629 [1:01:02<17:46, 21.53it/s]

 77%|███████▋  | 77667/100629 [1:01:02<18:04, 21.18it/s]

 77%|███████▋  | 77670/100629 [1:01:02<17:15, 22.18it/s]

 77%|███████▋  | 77673/100629 [1:01:02<17:42, 21.61it/s]

 77%|███████▋  | 77677/100629 [1:01:02<17:20, 22.05it/s]

 77%|███████▋  | 77680/100629 [1:01:02<16:21, 23.39it/s]

 77%|███████▋  | 77683/100629 [1:01:02<19:50, 19.27it/s]

 77%|███████▋  | 77686/100629 [1:01:03<18:26, 20.74it/s]

 77%|███████▋  | 77689/100629 [1:01:03<17:38, 21.67it/s]

 77%|███████▋  | 77692/100629 [1:01:03<20:10, 18.95it/s]

 77%|███████▋  | 77695/100629 [1:01:03<18:09, 21.05it/s]

 77%|███████▋  | 77698/100629 [1:01:03<18:10, 21.03it/s]

 77%|███████▋  | 77702/100629 [1:01:03<15:35, 24.51it/s]

 77%|███████▋  | 77705/100629 [1:01:03<15:23, 24.82it/s]

 77%|███████▋  | 77708/100629 [1:01:04<17:17, 22.10it/s]

 77%|███████▋  | 77711/100629 [1:01:04<16:47, 22.75it/s]

 77%|███████▋  | 77714/100629 [1:01:04<18:39, 20.47it/s]

 77%|███████▋  | 77717/100629 [1:01:04<19:37, 19.45it/s]

 77%|███████▋  | 77720/100629 [1:01:04<20:44, 18.41it/s]

 77%|███████▋  | 77722/100629 [1:01:04<21:27, 17.79it/s]

 77%|███████▋  | 77725/100629 [1:01:04<18:51, 20.24it/s]

 77%|███████▋  | 77728/100629 [1:01:05<19:23, 19.69it/s]

 77%|███████▋  | 77731/100629 [1:01:05<18:43, 20.38it/s]

 77%|███████▋  | 77734/100629 [1:01:05<18:35, 20.52it/s]

 77%|███████▋  | 77737/100629 [1:01:05<21:06, 18.07it/s]

 77%|███████▋  | 77740/100629 [1:01:05<19:05, 19.97it/s]

 77%|███████▋  | 77743/100629 [1:01:05<21:45, 17.53it/s]

 77%|███████▋  | 77746/100629 [1:01:06<20:19, 18.77it/s]

 77%|███████▋  | 77748/100629 [1:01:06<23:48, 16.02it/s]

 77%|███████▋  | 77751/100629 [1:01:06<23:02, 16.55it/s]

 77%|███████▋  | 77754/100629 [1:01:06<22:13, 17.16it/s]

 77%|███████▋  | 77759/100629 [1:01:06<18:01, 21.15it/s]

 77%|███████▋  | 77762/100629 [1:01:06<17:47, 21.41it/s]

 77%|███████▋  | 77765/100629 [1:01:07<17:04, 22.32it/s]

 77%|███████▋  | 77768/100629 [1:01:07<17:52, 21.31it/s]

 77%|███████▋  | 77771/100629 [1:01:07<21:45, 17.50it/s]

 77%|███████▋  | 77774/100629 [1:01:07<21:03, 18.09it/s]

 77%|███████▋  | 77777/100629 [1:01:07<19:23, 19.63it/s]

 77%|███████▋  | 77780/100629 [1:01:07<22:21, 17.03it/s]

 77%|███████▋  | 77784/100629 [1:01:08<19:14, 19.79it/s]

 77%|███████▋  | 77787/100629 [1:01:08<18:34, 20.50it/s]

 77%|███████▋  | 77790/100629 [1:01:08<22:05, 17.23it/s]

 77%|███████▋  | 77793/100629 [1:01:08<21:15, 17.90it/s]

 77%|███████▋  | 77796/100629 [1:01:08<19:57, 19.07it/s]

 77%|███████▋  | 77799/100629 [1:01:08<19:37, 19.39it/s]

 77%|███████▋  | 77802/100629 [1:01:09<19:11, 19.82it/s]

 77%|███████▋  | 77805/100629 [1:01:09<19:24, 19.59it/s]

 77%|███████▋  | 77810/100629 [1:01:09<16:00, 23.75it/s]

 77%|███████▋  | 77814/100629 [1:01:09<14:31, 26.19it/s]

 77%|███████▋  | 77817/100629 [1:01:09<14:06, 26.94it/s]

 77%|███████▋  | 77820/100629 [1:01:09<15:04, 25.22it/s]

 77%|███████▋  | 77823/100629 [1:01:09<15:36, 24.36it/s]

 77%|███████▋  | 77827/100629 [1:01:09<13:45, 27.61it/s]

 77%|███████▋  | 77830/100629 [1:01:10<17:54, 21.22it/s]

 77%|███████▋  | 77834/100629 [1:01:10<15:34, 24.40it/s]

 77%|███████▋  | 77838/100629 [1:01:10<14:36, 26.00it/s]

 77%|███████▋  | 77841/100629 [1:01:10<17:30, 21.69it/s]

 77%|███████▋  | 77844/100629 [1:01:10<17:56, 21.16it/s]

 77%|███████▋  | 77848/100629 [1:01:10<17:36, 21.56it/s]

 77%|███████▋  | 77851/100629 [1:01:11<16:21, 23.20it/s]

 77%|███████▋  | 77855/100629 [1:01:11<15:10, 25.01it/s]

 77%|███████▋  | 77858/100629 [1:01:11<17:05, 22.21it/s]

 77%|███████▋  | 77862/100629 [1:01:11<17:39, 21.48it/s]

 77%|███████▋  | 77865/100629 [1:01:11<18:38, 20.35it/s]

 77%|███████▋  | 77868/100629 [1:01:11<17:26, 21.74it/s]

 77%|███████▋  | 77871/100629 [1:01:12<18:34, 20.43it/s]

 77%|███████▋  | 77874/100629 [1:01:12<18:07, 20.92it/s]

 77%|███████▋  | 77877/100629 [1:01:12<17:40, 21.45it/s]

 77%|███████▋  | 77880/100629 [1:01:12<17:43, 21.40it/s]

 77%|███████▋  | 77883/100629 [1:01:12<22:43, 16.68it/s]

 77%|███████▋  | 77886/100629 [1:01:12<20:43, 18.29it/s]

 77%|███████▋  | 77889/100629 [1:01:12<18:59, 19.95it/s]

 77%|███████▋  | 77892/100629 [1:01:13<19:19, 19.61it/s]

 77%|███████▋  | 77896/100629 [1:01:13<16:16, 23.27it/s]

 77%|███████▋  | 77899/100629 [1:01:13<17:21, 21.83it/s]

 77%|███████▋  | 77902/100629 [1:01:13<17:15, 21.95it/s]

 77%|███████▋  | 77906/100629 [1:01:13<16:39, 22.73it/s]

 77%|███████▋  | 77909/100629 [1:01:13<17:32, 21.58it/s]

 77%|███████▋  | 77912/100629 [1:01:13<16:46, 22.57it/s]

 77%|███████▋  | 77915/100629 [1:01:14<17:32, 21.58it/s]

 77%|███████▋  | 77918/100629 [1:01:14<16:49, 22.51it/s]

 77%|███████▋  | 77921/100629 [1:01:14<17:15, 21.93it/s]

 77%|███████▋  | 77925/100629 [1:01:14<15:09, 24.97it/s]

 77%|███████▋  | 77928/100629 [1:01:14<17:23, 21.75it/s]

 77%|███████▋  | 77932/100629 [1:01:14<16:10, 23.39it/s]

 77%|███████▋  | 77936/100629 [1:01:15<16:37, 22.76it/s]

 77%|███████▋  | 77939/100629 [1:01:15<16:54, 22.36it/s]

 77%|███████▋  | 77942/100629 [1:01:15<16:53, 22.38it/s]

 77%|███████▋  | 77945/100629 [1:01:15<19:13, 19.67it/s]

 77%|███████▋  | 77948/100629 [1:01:15<18:45, 20.16it/s]

 77%|███████▋  | 77951/100629 [1:01:15<21:28, 17.59it/s]

 77%|███████▋  | 77954/100629 [1:01:15<20:12, 18.70it/s]

 77%|███████▋  | 77957/100629 [1:01:16<18:27, 20.48it/s]

 77%|███████▋  | 77961/100629 [1:01:16<16:18, 23.16it/s]

 77%|███████▋  | 77964/100629 [1:01:16<16:01, 23.58it/s]

 77%|███████▋  | 77969/100629 [1:01:16<13:12, 28.59it/s]

 77%|███████▋  | 77972/100629 [1:01:16<13:18, 28.38it/s]

 77%|███████▋  | 77975/100629 [1:01:16<14:49, 25.48it/s]

 77%|███████▋  | 77978/100629 [1:01:16<15:27, 24.43it/s]

 77%|███████▋  | 77981/100629 [1:01:17<17:02, 22.15it/s]

 77%|███████▋  | 77984/100629 [1:01:17<17:32, 21.52it/s]

 77%|███████▋  | 77987/100629 [1:01:17<17:08, 22.02it/s]

 78%|███████▊  | 77990/100629 [1:01:17<17:32, 21.51it/s]

 78%|███████▊  | 77993/100629 [1:01:17<18:28, 20.42it/s]

 78%|███████▊  | 77996/100629 [1:01:17<20:03, 18.80it/s]

 78%|███████▊  | 78000/100629 [1:01:17<18:00, 20.95it/s]

 78%|███████▊  | 78004/100629 [1:01:18<15:38, 24.11it/s]

 78%|███████▊  | 78007/100629 [1:01:18<16:33, 22.76it/s]

 78%|███████▊  | 78010/100629 [1:01:18<15:39, 24.07it/s]

 78%|███████▊  | 78013/100629 [1:01:18<15:17, 24.66it/s]

 78%|███████▊  | 78016/100629 [1:01:18<16:48, 22.42it/s]

 78%|███████▊  | 78019/100629 [1:01:18<18:44, 20.10it/s]

 78%|███████▊  | 78022/100629 [1:01:19<20:42, 18.20it/s]

 78%|███████▊  | 78026/100629 [1:01:19<18:05, 20.82it/s]

 78%|███████▊  | 78029/100629 [1:01:19<19:39, 19.16it/s]

 78%|███████▊  | 78033/100629 [1:01:19<17:18, 21.76it/s]

 78%|███████▊  | 78036/100629 [1:01:19<16:18, 23.08it/s]

 78%|███████▊  | 78039/100629 [1:01:19<16:14, 23.17it/s]

 78%|███████▊  | 78042/100629 [1:01:19<18:19, 20.54it/s]

 78%|███████▊  | 78045/100629 [1:01:20<19:19, 19.47it/s]

 78%|███████▊  | 78049/100629 [1:01:20<16:46, 22.44it/s]

 78%|███████▊  | 78054/100629 [1:01:20<14:43, 25.57it/s]

 78%|███████▊  | 78059/100629 [1:01:20<13:03, 28.79it/s]

 78%|███████▊  | 78062/100629 [1:01:20<13:30, 27.86it/s]

 78%|███████▊  | 78065/100629 [1:01:20<13:40, 27.50it/s]

 78%|███████▊  | 78068/100629 [1:01:20<16:19, 23.03it/s]

 78%|███████▊  | 78071/100629 [1:01:21<16:19, 23.04it/s]

 78%|███████▊  | 78075/100629 [1:01:21<15:00, 25.05it/s]

 78%|███████▊  | 78078/100629 [1:01:21<15:32, 24.18it/s]

 78%|███████▊  | 78081/100629 [1:01:21<20:50, 18.03it/s]

 78%|███████▊  | 78084/100629 [1:01:21<18:35, 20.21it/s]

 78%|███████▊  | 78087/100629 [1:01:21<16:57, 22.16it/s]

 78%|███████▊  | 78090/100629 [1:01:21<18:18, 20.53it/s]

 78%|███████▊  | 78094/100629 [1:01:22<15:57, 23.53it/s]

 78%|███████▊  | 78097/100629 [1:01:22<18:07, 20.71it/s]

 78%|███████▊  | 78102/100629 [1:01:22<15:10, 24.75it/s]

 78%|███████▊  | 78105/100629 [1:01:22<16:42, 22.48it/s]

 78%|███████▊  | 78108/100629 [1:01:22<15:55, 23.56it/s]

 78%|███████▊  | 78111/100629 [1:01:22<17:12, 21.80it/s]

 78%|███████▊  | 78115/100629 [1:01:23<18:30, 20.28it/s]

 78%|███████▊  | 78118/100629 [1:01:23<17:10, 21.85it/s]

 78%|███████▊  | 78121/100629 [1:01:23<17:35, 21.33it/s]

 78%|███████▊  | 78124/100629 [1:01:23<17:46, 21.11it/s]

 78%|███████▊  | 78127/100629 [1:01:23<19:44, 18.99it/s]

 78%|███████▊  | 78130/100629 [1:01:23<18:19, 20.45it/s]

 78%|███████▊  | 78133/100629 [1:01:24<19:48, 18.93it/s]

 78%|███████▊  | 78136/100629 [1:01:24<19:37, 19.09it/s]

 78%|███████▊  | 78138/100629 [1:01:24<20:46, 18.04it/s]

 78%|███████▊  | 78143/100629 [1:01:24<16:00, 23.41it/s]

 78%|███████▊  | 78146/100629 [1:01:24<16:58, 22.07it/s]

 78%|███████▊  | 78149/100629 [1:01:24<15:48, 23.70it/s]

 78%|███████▊  | 78152/100629 [1:01:24<16:48, 22.30it/s]

 78%|███████▊  | 78155/100629 [1:01:24<16:28, 22.74it/s]

 78%|███████▊  | 78159/100629 [1:01:25<14:41, 25.48it/s]

 78%|███████▊  | 78162/100629 [1:01:25<15:53, 23.57it/s]

 78%|███████▊  | 78165/100629 [1:01:25<18:35, 20.15it/s]

 78%|███████▊  | 78169/100629 [1:01:25<15:26, 24.25it/s]

 78%|███████▊  | 78172/100629 [1:01:25<16:41, 22.43it/s]

 78%|███████▊  | 78175/100629 [1:01:25<16:11, 23.11it/s]

 78%|███████▊  | 78178/100629 [1:01:25<17:03, 21.94it/s]

 78%|███████▊  | 78181/100629 [1:01:26<17:27, 21.43it/s]

 78%|███████▊  | 78184/100629 [1:01:26<18:23, 20.34it/s]

 78%|███████▊  | 78187/100629 [1:01:26<31:30, 11.87it/s]

 78%|███████▊  | 78191/100629 [1:01:26<25:11, 14.84it/s]

 78%|███████▊  | 78196/100629 [1:01:27<18:47, 19.90it/s]

 78%|███████▊  | 78199/100629 [1:01:27<18:02, 20.72it/s]

 78%|███████▊  | 78203/100629 [1:01:27<16:02, 23.29it/s]

 78%|███████▊  | 78207/100629 [1:01:27<14:19, 26.10it/s]

 78%|███████▊  | 78210/100629 [1:01:27<15:01, 24.88it/s]

 78%|███████▊  | 78214/100629 [1:01:27<13:16, 28.14it/s]

 78%|███████▊  | 78218/100629 [1:01:27<15:05, 24.76it/s]

 78%|███████▊  | 78221/100629 [1:01:28<18:37, 20.06it/s]

 78%|███████▊  | 78224/100629 [1:01:28<18:28, 20.21it/s]

 78%|███████▊  | 78227/100629 [1:01:28<17:50, 20.92it/s]

 78%|███████▊  | 78230/100629 [1:01:28<17:34, 21.24it/s]

 78%|███████▊  | 78233/100629 [1:01:28<20:45, 17.99it/s]

 78%|███████▊  | 78235/100629 [1:01:28<21:09, 17.64it/s]

 78%|███████▊  | 78238/100629 [1:01:29<20:36, 18.11it/s]

 78%|███████▊  | 78241/100629 [1:01:29<20:15, 18.43it/s]

 78%|███████▊  | 78243/100629 [1:01:29<22:54, 16.28it/s]

 78%|███████▊  | 78245/100629 [1:01:29<23:30, 15.87it/s]

 78%|███████▊  | 78250/100629 [1:01:29<18:18, 20.38it/s]

 78%|███████▊  | 78255/100629 [1:01:29<14:26, 25.83it/s]

 78%|███████▊  | 78259/100629 [1:01:29<14:01, 26.58it/s]

 78%|███████▊  | 78262/100629 [1:01:30<14:07, 26.39it/s]

 78%|███████▊  | 78266/100629 [1:01:30<13:49, 26.98it/s]

 78%|███████▊  | 78269/100629 [1:01:30<17:10, 21.70it/s]

 78%|███████▊  | 78272/100629 [1:01:30<18:49, 19.79it/s]

 78%|███████▊  | 78275/100629 [1:01:30<19:35, 19.01it/s]

 78%|███████▊  | 78278/100629 [1:01:30<17:35, 21.18it/s]

 78%|███████▊  | 78281/100629 [1:01:30<16:57, 21.97it/s]

 78%|███████▊  | 78285/100629 [1:01:31<16:52, 22.07it/s]

 78%|███████▊  | 78289/100629 [1:01:31<15:11, 24.50it/s]

 78%|███████▊  | 78292/100629 [1:01:31<15:40, 23.74it/s]

 78%|███████▊  | 78295/100629 [1:01:31<16:25, 22.66it/s]

 78%|███████▊  | 78298/100629 [1:01:31<18:24, 20.23it/s]

 78%|███████▊  | 78301/100629 [1:01:32<21:50, 17.04it/s]

 78%|███████▊  | 78306/100629 [1:01:32<17:18, 21.49it/s]

 78%|███████▊  | 78309/100629 [1:01:32<16:32, 22.49it/s]

 78%|███████▊  | 78312/100629 [1:01:32<16:18, 22.80it/s]

 78%|███████▊  | 78315/100629 [1:01:32<15:25, 24.10it/s]

 78%|███████▊  | 78318/100629 [1:01:32<18:14, 20.39it/s]

 78%|███████▊  | 78321/100629 [1:01:32<19:07, 19.43it/s]

 78%|███████▊  | 78324/100629 [1:01:33<19:29, 19.07it/s]

 78%|███████▊  | 78327/100629 [1:01:33<18:12, 20.42it/s]

 78%|███████▊  | 78330/100629 [1:01:33<20:27, 18.17it/s]

 78%|███████▊  | 78333/100629 [1:01:33<19:09, 19.39it/s]

 78%|███████▊  | 78336/100629 [1:01:33<18:25, 20.17it/s]

 78%|███████▊  | 78339/100629 [1:01:33<18:01, 20.60it/s]

 78%|███████▊  | 78343/100629 [1:01:33<15:09, 24.51it/s]

 78%|███████▊  | 78346/100629 [1:01:33<14:44, 25.19it/s]

 78%|███████▊  | 78349/100629 [1:01:34<15:04, 24.62it/s]

 78%|███████▊  | 78352/100629 [1:01:34<15:21, 24.17it/s]

 78%|███████▊  | 78355/100629 [1:01:34<16:10, 22.96it/s]

 78%|███████▊  | 78358/100629 [1:01:34<20:25, 18.17it/s]

 78%|███████▊  | 78361/100629 [1:01:34<19:19, 19.20it/s]

 78%|███████▊  | 78365/100629 [1:01:34<17:00, 21.83it/s]

 78%|███████▊  | 78368/100629 [1:01:35<15:48, 23.48it/s]

 78%|███████▊  | 78371/100629 [1:01:35<15:35, 23.78it/s]

 78%|███████▊  | 78374/100629 [1:01:35<18:23, 20.17it/s]

 78%|███████▊  | 78377/100629 [1:01:35<19:01, 19.49it/s]

 78%|███████▊  | 78382/100629 [1:01:35<15:15, 24.30it/s]

 78%|███████▊  | 78385/100629 [1:01:35<15:13, 24.34it/s]

 78%|███████▊  | 78388/100629 [1:01:35<17:30, 21.17it/s]

 78%|███████▊  | 78391/100629 [1:01:36<17:01, 21.77it/s]

 78%|███████▊  | 78395/100629 [1:01:36<14:45, 25.11it/s]

 78%|███████▊  | 78398/100629 [1:01:36<15:19, 24.17it/s]

 78%|███████▊  | 78401/100629 [1:01:36<17:54, 20.69it/s]

 78%|███████▊  | 78404/100629 [1:01:36<16:30, 22.43it/s]

 78%|███████▊  | 78407/100629 [1:01:36<20:28, 18.09it/s]

 78%|███████▊  | 78411/100629 [1:01:37<18:24, 20.12it/s]

 78%|███████▊  | 78414/100629 [1:01:37<20:50, 17.76it/s]

 78%|███████▊  | 78417/100629 [1:01:37<19:34, 18.90it/s]

 78%|███████▊  | 78420/100629 [1:01:37<21:12, 17.45it/s]

 78%|███████▊  | 78424/100629 [1:01:37<17:46, 20.82it/s]

 78%|███████▊  | 78427/100629 [1:01:37<16:36, 22.28it/s]

 78%|███████▊  | 78430/100629 [1:01:38<18:00, 20.55it/s]

 78%|███████▊  | 78433/100629 [1:01:38<17:28, 21.18it/s]

 78%|███████▊  | 78436/100629 [1:01:38<17:06, 21.63it/s]

 78%|███████▊  | 78439/100629 [1:01:38<16:15, 22.74it/s]

 78%|███████▊  | 78442/100629 [1:01:38<16:47, 22.03it/s]

 78%|███████▊  | 78445/100629 [1:01:38<18:24, 20.08it/s]

 78%|███████▊  | 78448/100629 [1:01:38<18:56, 19.51it/s]

 78%|███████▊  | 78451/100629 [1:01:39<17:36, 20.98it/s]

 78%|███████▊  | 78454/100629 [1:01:39<23:08, 15.97it/s]

 78%|███████▊  | 78457/100629 [1:01:39<20:12, 18.29it/s]

 78%|███████▊  | 78460/100629 [1:01:39<23:29, 15.73it/s]

 78%|███████▊  | 78463/100629 [1:01:39<23:37, 15.63it/s]

 78%|███████▊  | 78465/100629 [1:01:39<22:49, 16.18it/s]

 78%|███████▊  | 78467/100629 [1:01:40<23:18, 15.84it/s]

 78%|███████▊  | 78469/100629 [1:01:40<23:53, 15.46it/s]

 78%|███████▊  | 78472/100629 [1:01:40<20:57, 17.62it/s]

 78%|███████▊  | 78474/100629 [1:01:40<25:29, 14.48it/s]

 78%|███████▊  | 78478/100629 [1:01:40<22:09, 16.66it/s]

 78%|███████▊  | 78482/100629 [1:01:40<18:53, 19.55it/s]

 78%|███████▊  | 78485/100629 [1:01:41<17:48, 20.73it/s]

 78%|███████▊  | 78488/100629 [1:01:41<19:45, 18.68it/s]

 78%|███████▊  | 78490/100629 [1:01:41<20:57, 17.61it/s]

 78%|███████▊  | 78495/100629 [1:01:41<16:46, 21.99it/s]

 78%|███████▊  | 78498/100629 [1:01:41<18:00, 20.48it/s]

 78%|███████▊  | 78501/100629 [1:01:41<17:41, 20.85it/s]

 78%|███████▊  | 78505/100629 [1:01:41<16:31, 22.31it/s]

 78%|███████▊  | 78508/100629 [1:01:42<17:15, 21.36it/s]

 78%|███████▊  | 78511/100629 [1:01:42<17:34, 20.97it/s]

 78%|███████▊  | 78514/100629 [1:01:42<19:16, 19.12it/s]

 78%|███████▊  | 78516/100629 [1:01:42<21:21, 17.26it/s]

 78%|███████▊  | 78518/100629 [1:01:42<22:28, 16.40it/s]

 78%|███████▊  | 78521/100629 [1:01:42<19:48, 18.61it/s]

 78%|███████▊  | 78525/100629 [1:01:43<18:32, 19.86it/s]

 78%|███████▊  | 78529/100629 [1:01:43<15:32, 23.71it/s]

 78%|███████▊  | 78533/100629 [1:01:43<13:38, 26.99it/s]

 78%|███████▊  | 78537/100629 [1:01:43<12:21, 29.79it/s]

 78%|███████▊  | 78541/100629 [1:01:43<15:28, 23.80it/s]

 78%|███████▊  | 78547/100629 [1:01:43<11:47, 31.22it/s]

 78%|███████▊  | 78551/100629 [1:01:43<13:13, 27.83it/s]

 78%|███████▊  | 78555/100629 [1:01:44<12:55, 28.46it/s]

 78%|███████▊  | 78559/100629 [1:01:44<14:54, 24.69it/s]

 78%|███████▊  | 78562/100629 [1:01:44<18:27, 19.92it/s]

 78%|███████▊  | 78565/100629 [1:01:44<18:27, 19.93it/s]

 78%|███████▊  | 78568/100629 [1:01:44<17:34, 20.92it/s]

 78%|███████▊  | 78571/100629 [1:01:44<16:40, 22.04it/s]

 78%|███████▊  | 78574/100629 [1:01:45<15:34, 23.61it/s]

 78%|███████▊  | 78577/100629 [1:01:45<17:17, 21.25it/s]

 78%|███████▊  | 78580/100629 [1:01:45<18:07, 20.28it/s]

 78%|███████▊  | 78583/100629 [1:01:45<20:10, 18.22it/s]

 78%|███████▊  | 78587/100629 [1:01:45<17:37, 20.84it/s]

 78%|███████▊  | 78590/100629 [1:01:45<16:48, 21.85it/s]

 78%|███████▊  | 78593/100629 [1:01:45<17:33, 20.91it/s]

 78%|███████▊  | 78597/100629 [1:01:46<16:48, 21.85it/s]

 78%|███████▊  | 78602/100629 [1:01:46<13:10, 27.85it/s]

 78%|███████▊  | 78606/100629 [1:01:46<15:19, 23.96it/s]

 78%|███████▊  | 78609/100629 [1:01:46<15:34, 23.57it/s]

 78%|███████▊  | 78612/100629 [1:01:46<14:49, 24.74it/s]

 78%|███████▊  | 78616/100629 [1:01:46<13:04, 28.04it/s]

 78%|███████▊  | 78620/100629 [1:01:46<12:09, 30.15it/s]

 78%|███████▊  | 78624/100629 [1:01:47<12:38, 29.00it/s]

 78%|███████▊  | 78628/100629 [1:01:47<12:15, 29.92it/s]

 78%|███████▊  | 78632/100629 [1:01:47<12:24, 29.56it/s]

 78%|███████▊  | 78636/100629 [1:01:47<11:28, 31.95it/s]

 78%|███████▊  | 78640/100629 [1:01:47<15:41, 23.35it/s]

 78%|███████▊  | 78643/100629 [1:01:47<15:44, 23.28it/s]

 78%|███████▊  | 78646/100629 [1:01:47<16:02, 22.84it/s]

 78%|███████▊  | 78649/100629 [1:01:48<16:40, 21.97it/s]

 78%|███████▊  | 78652/100629 [1:01:48<16:19, 22.43it/s]

 78%|███████▊  | 78655/100629 [1:01:48<16:23, 22.33it/s]

 78%|███████▊  | 78658/100629 [1:01:48<16:19, 22.43it/s]

 78%|███████▊  | 78661/100629 [1:01:48<16:26, 22.28it/s]

 78%|███████▊  | 78664/100629 [1:01:48<17:00, 21.53it/s]

 78%|███████▊  | 78667/100629 [1:01:48<17:52, 20.48it/s]

 78%|███████▊  | 78671/100629 [1:01:49<17:57, 20.39it/s]

 78%|███████▊  | 78675/100629 [1:01:49<16:11, 22.59it/s]

 78%|███████▊  | 78678/100629 [1:01:49<15:34, 23.48it/s]

 78%|███████▊  | 78681/100629 [1:01:49<16:33, 22.08it/s]

 78%|███████▊  | 78685/100629 [1:01:49<16:46, 21.80it/s]

 78%|███████▊  | 78688/100629 [1:01:49<15:42, 23.28it/s]

 78%|███████▊  | 78691/100629 [1:01:50<15:28, 23.63it/s]

 78%|███████▊  | 78696/100629 [1:01:50<12:39, 28.88it/s]

 78%|███████▊  | 78699/100629 [1:01:50<13:38, 26.80it/s]

 78%|███████▊  | 78705/100629 [1:01:50<11:47, 30.98it/s]

 78%|███████▊  | 78709/100629 [1:01:50<12:40, 28.82it/s]

 78%|███████▊  | 78712/100629 [1:01:50<13:28, 27.10it/s]

 78%|███████▊  | 78715/100629 [1:01:50<16:00, 22.81it/s]

 78%|███████▊  | 78718/100629 [1:01:51<15:55, 22.94it/s]

 78%|███████▊  | 78721/100629 [1:01:51<17:49, 20.48it/s]

 78%|███████▊  | 78724/100629 [1:01:51<20:53, 17.48it/s]

 78%|███████▊  | 78727/100629 [1:01:51<19:08, 19.06it/s]

 78%|███████▊  | 78730/100629 [1:01:51<18:42, 19.52it/s]

 78%|███████▊  | 78733/100629 [1:01:51<19:58, 18.28it/s]

 78%|███████▊  | 78736/100629 [1:01:52<21:29, 16.98it/s]

 78%|███████▊  | 78738/100629 [1:01:52<22:21, 16.31it/s]

 78%|███████▊  | 78743/100629 [1:01:52<16:08, 22.59it/s]

 78%|███████▊  | 78747/100629 [1:01:52<16:09, 22.56it/s]

 78%|███████▊  | 78750/100629 [1:01:52<15:54, 22.93it/s]

 78%|███████▊  | 78753/100629 [1:01:52<15:39, 23.29it/s]

 78%|███████▊  | 78757/100629 [1:01:52<16:17, 22.38it/s]

 78%|███████▊  | 78760/100629 [1:01:53<18:18, 19.91it/s]

 78%|███████▊  | 78763/100629 [1:01:53<20:04, 18.16it/s]

 78%|███████▊  | 78765/100629 [1:01:53<22:11, 16.42it/s]

 78%|███████▊  | 78769/100629 [1:01:53<17:40, 20.61it/s]

 78%|███████▊  | 78772/100629 [1:01:53<17:12, 21.17it/s]

 78%|███████▊  | 78775/100629 [1:01:53<16:14, 22.42it/s]

 78%|███████▊  | 78778/100629 [1:01:54<15:13, 23.92it/s]

 78%|███████▊  | 78781/100629 [1:01:54<15:33, 23.42it/s]

 78%|███████▊  | 78784/100629 [1:01:54<15:04, 24.16it/s]

 78%|███████▊  | 78789/100629 [1:01:54<14:11, 25.65it/s]

 78%|███████▊  | 78793/100629 [1:01:54<15:09, 24.02it/s]

 78%|███████▊  | 78796/100629 [1:01:54<15:44, 23.12it/s]

 78%|███████▊  | 78799/100629 [1:01:54<14:47, 24.59it/s]

 78%|███████▊  | 78802/100629 [1:01:55<16:10, 22.48it/s]

 78%|███████▊  | 78805/100629 [1:01:55<22:38, 16.06it/s]

 78%|███████▊  | 78807/100629 [1:01:55<24:16, 14.98it/s]

 78%|███████▊  | 78811/100629 [1:01:55<21:02, 17.29it/s]

 78%|███████▊  | 78813/100629 [1:01:55<22:52, 15.90it/s]

 78%|███████▊  | 78817/100629 [1:01:55<17:41, 20.55it/s]

 78%|███████▊  | 78822/100629 [1:01:56<14:21, 25.31it/s]

 78%|███████▊  | 78825/100629 [1:01:56<14:21, 25.30it/s]

 78%|███████▊  | 78828/100629 [1:01:56<16:56, 21.44it/s]

 78%|███████▊  | 78831/100629 [1:01:56<15:39, 23.20it/s]

 78%|███████▊  | 78834/100629 [1:01:56<15:48, 22.98it/s]

 78%|███████▊  | 78838/100629 [1:01:56<15:09, 23.95it/s]

 78%|███████▊  | 78842/100629 [1:01:56<14:13, 25.54it/s]

 78%|███████▊  | 78845/100629 [1:01:57<15:01, 24.15it/s]

 78%|███████▊  | 78850/100629 [1:01:57<12:43, 28.52it/s]

 78%|███████▊  | 78853/100629 [1:01:57<13:17, 27.30it/s]

 78%|███████▊  | 78857/100629 [1:01:57<13:07, 27.66it/s]

 78%|███████▊  | 78860/100629 [1:01:57<13:19, 27.22it/s]

 78%|███████▊  | 78863/100629 [1:01:57<13:48, 26.26it/s]

 78%|███████▊  | 78866/100629 [1:01:57<14:52, 24.39it/s]

 78%|███████▊  | 78869/100629 [1:01:57<14:45, 24.59it/s]

 78%|███████▊  | 78872/100629 [1:01:58<15:04, 24.06it/s]

 78%|███████▊  | 78875/100629 [1:01:58<14:23, 25.19it/s]

 78%|███████▊  | 78879/100629 [1:01:58<15:01, 24.13it/s]

 78%|███████▊  | 78882/100629 [1:01:58<17:14, 21.01it/s]

 78%|███████▊  | 78885/100629 [1:01:58<18:17, 19.81it/s]

 78%|███████▊  | 78888/100629 [1:01:58<19:00, 19.06it/s]

 78%|███████▊  | 78891/100629 [1:01:59<18:47, 19.29it/s]

 78%|███████▊  | 78894/100629 [1:01:59<16:59, 21.33it/s]

 78%|███████▊  | 78897/100629 [1:01:59<16:09, 22.41it/s]

 78%|███████▊  | 78900/100629 [1:01:59<18:09, 19.94it/s]

 78%|███████▊  | 78903/100629 [1:01:59<18:33, 19.51it/s]

 78%|███████▊  | 78906/100629 [1:01:59<21:59, 16.46it/s]

 78%|███████▊  | 78909/100629 [1:02:00<19:41, 18.38it/s]

 78%|███████▊  | 78912/100629 [1:02:00<19:31, 18.54it/s]

 78%|███████▊  | 78915/100629 [1:02:00<17:48, 20.33it/s]

 78%|███████▊  | 78919/100629 [1:02:00<15:10, 23.84it/s]

 78%|███████▊  | 78922/100629 [1:02:00<14:53, 24.30it/s]

 78%|███████▊  | 78925/100629 [1:02:00<16:49, 21.51it/s]

 78%|███████▊  | 78928/100629 [1:02:00<17:45, 20.37it/s]

 78%|███████▊  | 78931/100629 [1:02:01<18:22, 19.69it/s]

 78%|███████▊  | 78934/100629 [1:02:01<19:36, 18.44it/s]

 78%|███████▊  | 78937/100629 [1:02:01<18:33, 19.49it/s]

 78%|███████▊  | 78941/100629 [1:02:01<17:01, 21.23it/s]

 78%|███████▊  | 78946/100629 [1:02:01<13:53, 26.00it/s]

 78%|███████▊  | 78949/100629 [1:02:01<14:54, 24.24it/s]

 78%|███████▊  | 78952/100629 [1:02:01<14:32, 24.84it/s]

 78%|███████▊  | 78955/100629 [1:02:02<14:15, 25.33it/s]

 78%|███████▊  | 78958/100629 [1:02:02<14:24, 25.07it/s]

 78%|███████▊  | 78961/100629 [1:02:02<15:37, 23.12it/s]

 78%|███████▊  | 78964/100629 [1:02:02<15:04, 23.94it/s]

 78%|███████▊  | 78967/100629 [1:02:02<20:47, 17.37it/s]

 78%|███████▊  | 78970/100629 [1:02:02<20:25, 17.68it/s]

 78%|███████▊  | 78972/100629 [1:02:02<20:18, 17.77it/s]

 78%|███████▊  | 78976/100629 [1:02:03<17:10, 21.02it/s]

 78%|███████▊  | 78979/100629 [1:02:03<17:21, 20.80it/s]

 78%|███████▊  | 78982/100629 [1:02:03<16:06, 22.40it/s]

 78%|███████▊  | 78985/100629 [1:02:03<19:07, 18.86it/s]

 78%|███████▊  | 78988/100629 [1:02:03<19:27, 18.54it/s]

 78%|███████▊  | 78990/100629 [1:02:03<19:41, 18.32it/s]

 78%|███████▊  | 78992/100629 [1:02:03<20:38, 17.48it/s]

 79%|███████▊  | 78994/100629 [1:02:04<19:59, 18.03it/s]

 79%|███████▊  | 78998/100629 [1:02:04<17:52, 20.17it/s]

 79%|███████▊  | 79001/100629 [1:02:04<17:12, 20.96it/s]

 79%|███████▊  | 79004/100629 [1:02:04<17:28, 20.62it/s]

 79%|███████▊  | 79007/100629 [1:02:04<17:18, 20.81it/s]

 79%|███████▊  | 79010/100629 [1:02:04<19:39, 18.34it/s]

 79%|███████▊  | 79012/100629 [1:02:05<23:50, 15.11it/s]

 79%|███████▊  | 79014/100629 [1:02:05<25:11, 14.30it/s]

 79%|███████▊  | 79017/100629 [1:02:05<26:03, 13.82it/s]

 79%|███████▊  | 79019/100629 [1:02:05<27:41, 13.01it/s]

 79%|███████▊  | 79022/100629 [1:02:05<24:36, 14.63it/s]

 79%|███████▊  | 79025/100629 [1:02:05<21:11, 16.99it/s]

 79%|███████▊  | 79027/100629 [1:02:06<21:53, 16.44it/s]

 79%|███████▊  | 79029/100629 [1:02:06<21:14, 16.95it/s]

 79%|███████▊  | 79032/100629 [1:02:06<18:15, 19.71it/s]

 79%|███████▊  | 79035/100629 [1:02:06<17:55, 20.07it/s]

 79%|███████▊  | 79038/100629 [1:02:06<19:55, 18.06it/s]

 79%|███████▊  | 79041/100629 [1:02:06<18:39, 19.28it/s]

 79%|███████▊  | 79044/100629 [1:02:06<18:13, 19.74it/s]

 79%|███████▊  | 79048/100629 [1:02:07<16:26, 21.87it/s]

 79%|███████▊  | 79051/100629 [1:02:07<15:27, 23.27it/s]

 79%|███████▊  | 79054/100629 [1:02:07<18:00, 19.96it/s]

 79%|███████▊  | 79057/100629 [1:02:07<18:49, 19.10it/s]

 79%|███████▊  | 79060/100629 [1:02:07<17:26, 20.60it/s]

 79%|███████▊  | 79063/100629 [1:02:07<22:50, 15.74it/s]

 79%|███████▊  | 79067/100629 [1:02:08<18:14, 19.69it/s]

 79%|███████▊  | 79070/100629 [1:02:08<16:53, 21.26it/s]

 79%|███████▊  | 79073/100629 [1:02:08<17:09, 20.93it/s]

 79%|███████▊  | 79076/100629 [1:02:08<23:40, 15.17it/s]

 79%|███████▊  | 79078/100629 [1:02:08<26:26, 13.58it/s]

 79%|███████▊  | 79081/100629 [1:02:09<23:12, 15.47it/s]

 79%|███████▊  | 79083/100629 [1:02:09<23:01, 15.60it/s]

 79%|███████▊  | 79088/100629 [1:02:09<17:29, 20.53it/s]

 79%|███████▊  | 79091/100629 [1:02:09<18:34, 19.32it/s]

 79%|███████▊  | 79094/100629 [1:02:09<19:38, 18.27it/s]

 79%|███████▊  | 79098/100629 [1:02:09<17:18, 20.73it/s]

 79%|███████▊  | 79101/100629 [1:02:09<16:38, 21.56it/s]

 79%|███████▊  | 79105/100629 [1:02:10<14:15, 25.17it/s]

 79%|███████▊  | 79109/100629 [1:02:10<13:26, 26.67it/s]

 79%|███████▊  | 79113/100629 [1:02:10<12:46, 28.07it/s]

 79%|███████▊  | 79116/100629 [1:02:10<13:55, 25.74it/s]

 79%|███████▊  | 79119/100629 [1:02:10<16:00, 22.39it/s]

 79%|███████▊  | 79122/100629 [1:02:10<23:19, 15.37it/s]

 79%|███████▊  | 79124/100629 [1:02:11<24:19, 14.74it/s]

 79%|███████▊  | 79127/100629 [1:02:11<21:08, 16.96it/s]

 79%|███████▊  | 79132/100629 [1:02:11<15:41, 22.84it/s]

 79%|███████▊  | 79135/100629 [1:02:11<17:03, 20.99it/s]

 79%|███████▊  | 79138/100629 [1:02:11<16:24, 21.84it/s]

 79%|███████▊  | 79141/100629 [1:02:11<15:27, 23.17it/s]

 79%|███████▊  | 79144/100629 [1:02:11<17:00, 21.05it/s]

 79%|███████▊  | 79147/100629 [1:02:12<19:08, 18.71it/s]

 79%|███████▊  | 79150/100629 [1:02:12<24:21, 14.70it/s]

 79%|███████▊  | 79155/100629 [1:02:12<18:30, 19.34it/s]

 79%|███████▊  | 79158/100629 [1:02:12<21:20, 16.77it/s]

 79%|███████▊  | 79160/100629 [1:02:12<20:53, 17.13it/s]

 79%|███████▊  | 79162/100629 [1:02:13<21:40, 16.51it/s]

 79%|███████▊  | 79166/100629 [1:02:13<17:06, 20.90it/s]

 79%|███████▊  | 79169/100629 [1:02:13<16:34, 21.58it/s]

 79%|███████▊  | 79173/100629 [1:02:13<14:17, 25.01it/s]

 79%|███████▊  | 79177/100629 [1:02:13<13:01, 27.46it/s]

 79%|███████▊  | 79180/100629 [1:02:13<14:07, 25.31it/s]

 79%|███████▊  | 79183/100629 [1:02:13<14:17, 25.00it/s]

 79%|███████▊  | 79186/100629 [1:02:13<14:19, 24.95it/s]

 79%|███████▊  | 79189/100629 [1:02:14<14:33, 24.54it/s]

 79%|███████▊  | 79192/100629 [1:02:14<14:51, 24.03it/s]

 79%|███████▊  | 79195/100629 [1:02:14<15:20, 23.29it/s]

 79%|███████▊  | 79198/100629 [1:02:14<17:21, 20.57it/s]

 79%|███████▊  | 79201/100629 [1:02:14<19:22, 18.44it/s]

 79%|███████▊  | 79204/100629 [1:02:14<17:49, 20.04it/s]

 79%|███████▊  | 79207/100629 [1:02:15<21:08, 16.89it/s]

 79%|███████▊  | 79210/100629 [1:02:15<18:30, 19.29it/s]

 79%|███████▊  | 79214/100629 [1:02:15<15:47, 22.61it/s]

 79%|███████▊  | 79217/100629 [1:02:15<16:13, 22.00it/s]

 79%|███████▊  | 79220/100629 [1:02:15<18:48, 18.97it/s]

 79%|███████▊  | 79223/100629 [1:02:15<17:42, 20.15it/s]

 79%|███████▊  | 79226/100629 [1:02:15<17:42, 20.15it/s]

 79%|███████▊  | 79229/100629 [1:02:16<16:46, 21.27it/s]

 79%|███████▊  | 79233/100629 [1:02:16<15:45, 22.62it/s]

 79%|███████▊  | 79236/100629 [1:02:16<15:33, 22.91it/s]

 79%|███████▊  | 79239/100629 [1:02:16<15:32, 22.94it/s]

 79%|███████▊  | 79242/100629 [1:02:16<15:48, 22.55it/s]

 79%|███████▊  | 79245/100629 [1:02:16<15:08, 23.55it/s]

 79%|███████▉  | 79249/100629 [1:02:16<13:48, 25.82it/s]

 79%|███████▉  | 79252/100629 [1:02:17<16:53, 21.08it/s]

 79%|███████▉  | 79255/100629 [1:02:17<15:35, 22.85it/s]

 79%|███████▉  | 79259/100629 [1:02:17<16:15, 21.90it/s]

 79%|███████▉  | 79262/100629 [1:02:17<15:49, 22.51it/s]

 79%|███████▉  | 79265/100629 [1:02:17<16:05, 22.12it/s]

 79%|███████▉  | 79268/100629 [1:02:17<16:44, 21.26it/s]

 79%|███████▉  | 79271/100629 [1:02:17<16:46, 21.23it/s]

 79%|███████▉  | 79274/100629 [1:02:18<17:23, 20.46it/s]

 79%|███████▉  | 79277/100629 [1:02:18<19:51, 17.92it/s]

 79%|███████▉  | 79279/100629 [1:02:18<21:42, 16.39it/s]

 79%|███████▉  | 79282/100629 [1:02:18<19:19, 18.42it/s]

 79%|███████▉  | 79284/100629 [1:02:18<18:58, 18.74it/s]

 79%|███████▉  | 79286/100629 [1:02:18<21:51, 16.27it/s]

 79%|███████▉  | 79290/100629 [1:02:19<18:05, 19.67it/s]

 79%|███████▉  | 79293/100629 [1:02:19<16:15, 21.87it/s]

 79%|███████▉  | 79297/100629 [1:02:19<13:58, 25.44it/s]

 79%|███████▉  | 79300/100629 [1:02:19<16:39, 21.34it/s]

 79%|███████▉  | 79303/100629 [1:02:19<16:04, 22.11it/s]

 79%|███████▉  | 79306/100629 [1:02:19<15:31, 22.90it/s]

 79%|███████▉  | 79309/100629 [1:02:19<15:44, 22.58it/s]

 79%|███████▉  | 79312/100629 [1:02:19<15:22, 23.12it/s]

 79%|███████▉  | 79315/100629 [1:02:20<16:17, 21.80it/s]

 79%|███████▉  | 79319/100629 [1:02:20<14:07, 25.15it/s]

 79%|███████▉  | 79322/100629 [1:02:20<15:28, 22.94it/s]

 79%|███████▉  | 79325/100629 [1:02:20<15:28, 22.95it/s]

 79%|███████▉  | 79328/100629 [1:02:20<16:46, 21.16it/s]

 79%|███████▉  | 79331/100629 [1:02:20<17:05, 20.77it/s]

 79%|███████▉  | 79334/100629 [1:02:20<16:16, 21.81it/s]

 79%|███████▉  | 79337/100629 [1:02:21<17:14, 20.58it/s]

 79%|███████▉  | 79341/100629 [1:02:21<15:29, 22.91it/s]

 79%|███████▉  | 79344/100629 [1:02:21<14:49, 23.92it/s]

 79%|███████▉  | 79347/100629 [1:02:21<15:28, 22.93it/s]

 79%|███████▉  | 79350/100629 [1:02:21<20:07, 17.62it/s]

 79%|███████▉  | 79353/100629 [1:02:21<19:24, 18.27it/s]

 79%|███████▉  | 79355/100629 [1:02:22<20:22, 17.40it/s]

 79%|███████▉  | 79358/100629 [1:02:22<18:38, 19.01it/s]

 79%|███████▉  | 79360/100629 [1:02:22<18:42, 18.94it/s]

 79%|███████▉  | 79362/100629 [1:02:22<19:45, 17.95it/s]

 79%|███████▉  | 79364/100629 [1:02:22<19:14, 18.42it/s]

 79%|███████▉  | 79366/100629 [1:02:22<20:02, 17.68it/s]

 79%|███████▉  | 79371/100629 [1:02:22<15:16, 23.19it/s]

 79%|███████▉  | 79374/100629 [1:02:22<14:22, 24.64it/s]

 79%|███████▉  | 79377/100629 [1:02:23<15:30, 22.83it/s]

 79%|███████▉  | 79380/100629 [1:02:23<18:39, 18.98it/s]

 79%|███████▉  | 79383/100629 [1:02:23<17:01, 20.81it/s]

 79%|███████▉  | 79386/100629 [1:02:23<20:35, 17.20it/s]

 79%|███████▉  | 79389/100629 [1:02:23<18:23, 19.24it/s]

 79%|███████▉  | 79392/100629 [1:02:23<18:39, 18.97it/s]

 79%|███████▉  | 79395/100629 [1:02:24<16:42, 21.17it/s]

 79%|███████▉  | 79399/100629 [1:02:24<17:43, 19.96it/s]

 79%|███████▉  | 79402/100629 [1:02:24<20:17, 17.44it/s]

 79%|███████▉  | 79405/100629 [1:02:24<17:58, 19.68it/s]

 79%|███████▉  | 79408/100629 [1:02:24<18:55, 18.69it/s]

 79%|███████▉  | 79412/100629 [1:02:24<16:07, 21.92it/s]

 79%|███████▉  | 79415/100629 [1:02:24<15:09, 23.32it/s]

 79%|███████▉  | 79418/100629 [1:02:25<17:06, 20.67it/s]

 79%|███████▉  | 79424/100629 [1:02:25<12:23, 28.51it/s]

 79%|███████▉  | 79428/100629 [1:02:25<14:49, 23.83it/s]

 79%|███████▉  | 79433/100629 [1:02:25<13:23, 26.37it/s]

 79%|███████▉  | 79436/100629 [1:02:25<14:49, 23.82it/s]

 79%|███████▉  | 79439/100629 [1:02:25<15:08, 23.32it/s]

 79%|███████▉  | 79443/100629 [1:02:26<14:10, 24.90it/s]

 79%|███████▉  | 79446/100629 [1:02:26<13:34, 26.00it/s]

 79%|███████▉  | 79449/100629 [1:02:26<14:19, 24.65it/s]

 79%|███████▉  | 79452/100629 [1:02:26<15:16, 23.10it/s]

 79%|███████▉  | 79456/100629 [1:02:26<13:57, 25.29it/s]

 79%|███████▉  | 79459/100629 [1:02:26<13:59, 25.21it/s]

 79%|███████▉  | 79462/100629 [1:02:26<15:27, 22.82it/s]

 79%|███████▉  | 79465/100629 [1:02:27<14:57, 23.59it/s]

 79%|███████▉  | 79468/100629 [1:02:27<14:12, 24.84it/s]

 79%|███████▉  | 79471/100629 [1:02:27<15:35, 22.61it/s]

 79%|███████▉  | 79474/100629 [1:02:27<16:42, 21.11it/s]

 79%|███████▉  | 79477/100629 [1:02:27<17:16, 20.40it/s]

 79%|███████▉  | 79481/100629 [1:02:27<14:45, 23.89it/s]

 79%|███████▉  | 79484/100629 [1:02:27<15:24, 22.87it/s]

 79%|███████▉  | 79487/100629 [1:02:27<14:50, 23.73it/s]

 79%|███████▉  | 79490/100629 [1:02:28<14:43, 23.93it/s]

 79%|███████▉  | 79494/100629 [1:02:28<13:42, 25.69it/s]

 79%|███████▉  | 79497/100629 [1:02:28<13:57, 25.22it/s]

 79%|███████▉  | 79500/100629 [1:02:28<16:06, 21.85it/s]

 79%|███████▉  | 79503/100629 [1:02:28<16:40, 21.11it/s]

 79%|███████▉  | 79506/100629 [1:02:28<17:22, 20.26it/s]

 79%|███████▉  | 79509/100629 [1:02:29<17:33, 20.05it/s]

 79%|███████▉  | 79512/100629 [1:02:29<19:36, 17.95it/s]

 79%|███████▉  | 79514/100629 [1:02:29<21:07, 16.66it/s]

 79%|███████▉  | 79516/100629 [1:02:29<20:22, 17.26it/s]

 79%|███████▉  | 79519/100629 [1:02:29<19:18, 18.23it/s]

 79%|███████▉  | 79523/100629 [1:02:29<21:02, 16.72it/s]

 79%|███████▉  | 79526/100629 [1:02:30<19:45, 17.80it/s]

 79%|███████▉  | 79529/100629 [1:02:30<17:43, 19.85it/s]

 79%|███████▉  | 79532/100629 [1:02:30<17:58, 19.56it/s]

 79%|███████▉  | 79535/100629 [1:02:30<19:10, 18.33it/s]

 79%|███████▉  | 79539/100629 [1:02:30<15:33, 22.59it/s]

 79%|███████▉  | 79542/100629 [1:02:30<16:11, 21.70it/s]

 79%|███████▉  | 79545/100629 [1:02:30<16:17, 21.58it/s]

 79%|███████▉  | 79548/100629 [1:02:31<16:42, 21.02it/s]

 79%|███████▉  | 79552/100629 [1:02:31<14:12, 24.73it/s]

 79%|███████▉  | 79555/100629 [1:02:31<14:40, 23.92it/s]

 79%|███████▉  | 79558/100629 [1:02:31<15:34, 22.54it/s]

 79%|███████▉  | 79561/100629 [1:02:31<15:23, 22.82it/s]

 79%|███████▉  | 79564/100629 [1:02:31<17:54, 19.61it/s]

 79%|███████▉  | 79567/100629 [1:02:31<17:19, 20.25it/s]

 79%|███████▉  | 79570/100629 [1:02:32<18:10, 19.32it/s]

 79%|███████▉  | 79573/100629 [1:02:32<18:08, 19.35it/s]

 79%|███████▉  | 79577/100629 [1:02:32<16:03, 21.85it/s]

 79%|███████▉  | 79580/100629 [1:02:32<15:08, 23.17it/s]

 79%|███████▉  | 79583/100629 [1:02:32<15:16, 22.97it/s]

 79%|███████▉  | 79586/100629 [1:02:32<15:48, 22.17it/s]

 79%|███████▉  | 79589/100629 [1:02:32<17:03, 20.55it/s]

 79%|███████▉  | 79592/100629 [1:02:33<19:37, 17.87it/s]

 79%|███████▉  | 79594/100629 [1:02:33<19:47, 17.72it/s]

 79%|███████▉  | 79598/100629 [1:02:33<16:57, 20.66it/s]

 79%|███████▉  | 79601/100629 [1:02:33<16:05, 21.77it/s]

 79%|███████▉  | 79606/100629 [1:02:33<14:15, 24.58it/s]

 79%|███████▉  | 79609/100629 [1:02:33<13:48, 25.37it/s]

 79%|███████▉  | 79612/100629 [1:02:33<14:26, 24.27it/s]

 79%|███████▉  | 79616/100629 [1:02:34<12:53, 27.16it/s]

 79%|███████▉  | 79619/100629 [1:02:34<18:23, 19.04it/s]

 79%|███████▉  | 79622/100629 [1:02:34<18:31, 18.89it/s]

 79%|███████▉  | 79625/100629 [1:02:34<20:04, 17.44it/s]

 79%|███████▉  | 79629/100629 [1:02:34<16:20, 21.43it/s]

 79%|███████▉  | 79632/100629 [1:02:34<16:54, 20.70it/s]

 79%|███████▉  | 79635/100629 [1:02:35<15:37, 22.39it/s]

 79%|███████▉  | 79638/100629 [1:02:35<14:34, 24.00it/s]

 79%|███████▉  | 79641/100629 [1:02:35<15:56, 21.93it/s]

 79%|███████▉  | 79645/100629 [1:02:35<14:33, 24.03it/s]

 79%|███████▉  | 79649/100629 [1:02:35<13:05, 26.72it/s]

 79%|███████▉  | 79652/100629 [1:02:35<13:34, 25.75it/s]

 79%|███████▉  | 79656/100629 [1:02:35<14:00, 24.96it/s]

 79%|███████▉  | 79659/100629 [1:02:36<16:27, 21.23it/s]

 79%|███████▉  | 79662/100629 [1:02:36<16:59, 20.56it/s]

 79%|███████▉  | 79665/100629 [1:02:36<15:52, 22.00it/s]

 79%|███████▉  | 79668/100629 [1:02:36<15:22, 22.72it/s]

 79%|███████▉  | 79671/100629 [1:02:36<17:48, 19.62it/s]

 79%|███████▉  | 79674/100629 [1:02:36<17:06, 20.41it/s]

 79%|███████▉  | 79677/100629 [1:02:37<19:08, 18.24it/s]

 79%|███████▉  | 79679/100629 [1:02:37<20:41, 16.88it/s]

 79%|███████▉  | 79681/100629 [1:02:37<23:48, 14.67it/s]

 79%|███████▉  | 79684/100629 [1:02:37<19:57, 17.49it/s]

 79%|███████▉  | 79687/100629 [1:02:37<19:13, 18.15it/s]

 79%|███████▉  | 79689/100629 [1:02:37<20:02, 17.42it/s]

 79%|███████▉  | 79692/100629 [1:02:37<17:45, 19.65it/s]

 79%|███████▉  | 79695/100629 [1:02:38<19:44, 17.67it/s]

 79%|███████▉  | 79698/100629 [1:02:38<19:19, 18.05it/s]

 79%|███████▉  | 79701/100629 [1:02:38<17:43, 19.67it/s]

 79%|███████▉  | 79704/100629 [1:02:38<20:21, 17.13it/s]

 79%|███████▉  | 79707/100629 [1:02:38<18:01, 19.35it/s]

 79%|███████▉  | 79710/100629 [1:02:38<19:44, 17.66it/s]

 79%|███████▉  | 79713/100629 [1:02:39<18:41, 18.65it/s]

 79%|███████▉  | 79716/100629 [1:02:39<18:17, 19.05it/s]

 79%|███████▉  | 79719/100629 [1:02:39<17:33, 19.86it/s]

 79%|███████▉  | 79722/100629 [1:02:39<18:09, 19.18it/s]

 79%|███████▉  | 79724/100629 [1:02:39<21:24, 16.27it/s]

 79%|███████▉  | 79727/100629 [1:02:39<19:13, 18.12it/s]

 79%|███████▉  | 79733/100629 [1:02:39<13:02, 26.71it/s]

 79%|███████▉  | 79736/100629 [1:02:40<12:56, 26.92it/s]

 79%|███████▉  | 79741/100629 [1:02:40<11:06, 31.32it/s]

 79%|███████▉  | 79745/100629 [1:02:40<13:49, 25.19it/s]

 79%|███████▉  | 79748/100629 [1:02:40<14:25, 24.12it/s]

 79%|███████▉  | 79751/100629 [1:02:40<13:46, 25.27it/s]

 79%|███████▉  | 79754/100629 [1:02:40<14:23, 24.16it/s]

 79%|███████▉  | 79757/100629 [1:02:40<13:54, 25.00it/s]

 79%|███████▉  | 79761/100629 [1:02:40<12:44, 27.31it/s]

 79%|███████▉  | 79764/100629 [1:02:41<15:29, 22.45it/s]

 79%|███████▉  | 79767/100629 [1:02:41<17:15, 20.14it/s]

 79%|███████▉  | 79770/100629 [1:02:41<16:02, 21.67it/s]

 79%|███████▉  | 79774/100629 [1:02:41<16:04, 21.63it/s]

 79%|███████▉  | 79777/100629 [1:02:41<15:23, 22.59it/s]

 79%|███████▉  | 79782/100629 [1:02:41<12:06, 28.71it/s]

 79%|███████▉  | 79786/100629 [1:02:42<12:09, 28.59it/s]

 79%|███████▉  | 79790/100629 [1:02:42<12:54, 26.89it/s]

 79%|███████▉  | 79793/100629 [1:02:42<12:52, 26.97it/s]

 79%|███████▉  | 79796/100629 [1:02:42<13:00, 26.70it/s]

 79%|███████▉  | 79799/100629 [1:02:42<12:50, 27.05it/s]

 79%|███████▉  | 79802/100629 [1:02:43<26:26, 13.13it/s]

 79%|███████▉  | 79805/100629 [1:02:43<24:48, 13.99it/s]

 79%|███████▉  | 79807/100629 [1:02:43<23:49, 14.57it/s]

 79%|███████▉  | 79812/100629 [1:02:43<17:27, 19.87it/s]

 79%|███████▉  | 79815/100629 [1:02:43<16:45, 20.71it/s]

 79%|███████▉  | 79818/100629 [1:02:43<17:06, 20.27it/s]

 79%|███████▉  | 79821/100629 [1:02:43<17:46, 19.52it/s]

 79%|███████▉  | 79825/100629 [1:02:44<14:40, 23.63it/s]

 79%|███████▉  | 79828/100629 [1:02:44<14:44, 23.52it/s]

 79%|███████▉  | 79832/100629 [1:02:44<12:59, 26.67it/s]

 79%|███████▉  | 79836/100629 [1:02:44<14:05, 24.60it/s]

 79%|███████▉  | 79840/100629 [1:02:44<14:14, 24.32it/s]

 79%|███████▉  | 79843/100629 [1:02:44<15:55, 21.76it/s]

 79%|███████▉  | 79846/100629 [1:02:44<16:32, 20.94it/s]

 79%|███████▉  | 79849/100629 [1:02:45<18:03, 19.17it/s]

 79%|███████▉  | 79851/100629 [1:02:45<20:57, 16.52it/s]

 79%|███████▉  | 79854/100629 [1:02:45<18:37, 18.59it/s]

 79%|███████▉  | 79858/100629 [1:02:45<17:48, 19.44it/s]

 79%|███████▉  | 79861/100629 [1:02:45<17:15, 20.05it/s]

 79%|███████▉  | 79864/100629 [1:02:45<18:15, 18.95it/s]

 79%|███████▉  | 79869/100629 [1:02:46<14:44, 23.48it/s]

 79%|███████▉  | 79872/100629 [1:02:46<14:37, 23.64it/s]

 79%|███████▉  | 79875/100629 [1:02:46<15:37, 22.13it/s]

 79%|███████▉  | 79878/100629 [1:02:46<16:35, 20.84it/s]

 79%|███████▉  | 79881/100629 [1:02:46<15:48, 21.87it/s]

 79%|███████▉  | 79884/100629 [1:02:46<14:53, 23.22it/s]

 79%|███████▉  | 79888/100629 [1:02:46<12:52, 26.84it/s]

 79%|███████▉  | 79892/100629 [1:02:47<13:10, 26.24it/s]

 79%|███████▉  | 79896/100629 [1:02:47<12:01, 28.72it/s]

 79%|███████▉  | 79901/100629 [1:02:47<11:04, 31.18it/s]

 79%|███████▉  | 79905/100629 [1:02:47<13:29, 25.59it/s]

 79%|███████▉  | 79908/100629 [1:02:47<14:29, 23.83it/s]

 79%|███████▉  | 79911/100629 [1:02:47<15:38, 22.07it/s]

 79%|███████▉  | 79914/100629 [1:02:48<16:38, 20.75it/s]

 79%|███████▉  | 79917/100629 [1:02:48<16:16, 21.21it/s]

 79%|███████▉  | 79920/100629 [1:02:48<17:35, 19.62it/s]

 79%|███████▉  | 79924/100629 [1:02:48<16:05, 21.45it/s]

 79%|███████▉  | 79927/100629 [1:02:48<16:01, 21.52it/s]

 79%|███████▉  | 79930/100629 [1:02:48<15:12, 22.67it/s]

 79%|███████▉  | 79933/100629 [1:02:48<15:06, 22.83it/s]

 79%|███████▉  | 79937/100629 [1:02:49<13:49, 24.94it/s]

 79%|███████▉  | 79941/100629 [1:02:49<12:59, 26.55it/s]

 79%|███████▉  | 79944/100629 [1:02:49<14:56, 23.06it/s]

 79%|███████▉  | 79947/100629 [1:02:49<14:57, 23.06it/s]

 79%|███████▉  | 79953/100629 [1:02:49<12:17, 28.04it/s]

 79%|███████▉  | 79958/100629 [1:02:49<11:31, 29.87it/s]

 79%|███████▉  | 79961/100629 [1:02:49<11:44, 29.34it/s]

 79%|███████▉  | 79964/100629 [1:02:49<12:05, 28.47it/s]

 79%|███████▉  | 79967/100629 [1:02:50<13:32, 25.42it/s]

 79%|███████▉  | 79970/100629 [1:02:50<15:56, 21.60it/s]

 79%|███████▉  | 79973/100629 [1:02:50<15:11, 22.67it/s]

 79%|███████▉  | 79976/100629 [1:02:50<16:26, 20.94it/s]

 79%|███████▉  | 79979/100629 [1:02:50<16:47, 20.50it/s]

 79%|███████▉  | 79982/100629 [1:02:50<16:12, 21.23it/s]

 79%|███████▉  | 79986/100629 [1:02:51<14:12, 24.21it/s]

 79%|███████▉  | 79989/100629 [1:02:51<14:24, 23.88it/s]

 79%|███████▉  | 79992/100629 [1:02:51<17:13, 19.96it/s]

 79%|███████▉  | 79995/100629 [1:02:51<16:29, 20.86it/s]

 79%|███████▉  | 79998/100629 [1:02:51<17:13, 19.97it/s]

 80%|███████▉  | 80002/100629 [1:02:51<15:47, 21.77it/s]

 80%|███████▉  | 80007/100629 [1:02:51<13:06, 26.22it/s]

 80%|███████▉  | 80010/100629 [1:02:52<14:04, 24.42it/s]

 80%|███████▉  | 80013/100629 [1:02:52<16:20, 21.03it/s]

 80%|███████▉  | 80016/100629 [1:02:52<17:19, 19.83it/s]

 80%|███████▉  | 80019/100629 [1:02:52<17:14, 19.93it/s]

 80%|███████▉  | 80022/100629 [1:02:52<19:59, 17.18it/s]

 80%|███████▉  | 80024/100629 [1:02:52<19:24, 17.69it/s]

 80%|███████▉  | 80026/100629 [1:02:53<21:20, 16.09it/s]

 80%|███████▉  | 80029/100629 [1:02:53<18:13, 18.84it/s]

 80%|███████▉  | 80033/100629 [1:02:53<14:52, 23.07it/s]

 80%|███████▉  | 80036/100629 [1:02:53<15:31, 22.10it/s]

 80%|███████▉  | 80040/100629 [1:02:53<13:15, 25.87it/s]

 80%|███████▉  | 80044/100629 [1:02:53<12:15, 27.99it/s]

 80%|███████▉  | 80047/100629 [1:02:53<12:04, 28.39it/s]

 80%|███████▉  | 80051/100629 [1:02:53<11:42, 29.29it/s]

 80%|███████▉  | 80054/100629 [1:02:54<13:07, 26.14it/s]

 80%|███████▉  | 80060/100629 [1:02:54<11:16, 30.42it/s]

 80%|███████▉  | 80064/100629 [1:02:54<13:08, 26.08it/s]

 80%|███████▉  | 80067/100629 [1:02:54<14:07, 24.27it/s]

 80%|███████▉  | 80070/100629 [1:02:54<14:46, 23.19it/s]

 80%|███████▉  | 80075/100629 [1:02:54<12:31, 27.36it/s]

 80%|███████▉  | 80078/100629 [1:02:55<13:56, 24.56it/s]

 80%|███████▉  | 80083/100629 [1:02:55<11:36, 29.50it/s]

 80%|███████▉  | 80087/100629 [1:02:55<12:49, 26.68it/s]

 80%|███████▉  | 80090/100629 [1:02:55<13:52, 24.67it/s]

 80%|███████▉  | 80093/100629 [1:02:55<14:09, 24.18it/s]

 80%|███████▉  | 80096/100629 [1:02:55<16:12, 21.12it/s]

 80%|███████▉  | 80101/100629 [1:02:55<13:31, 25.31it/s]

 80%|███████▉  | 80104/100629 [1:02:56<14:39, 23.34it/s]

 80%|███████▉  | 80107/100629 [1:02:56<14:34, 23.47it/s]

 80%|███████▉  | 80110/100629 [1:02:56<15:01, 22.76it/s]

 80%|███████▉  | 80113/100629 [1:02:56<15:01, 22.76it/s]

 80%|███████▉  | 80116/100629 [1:02:56<14:36, 23.40it/s]

 80%|███████▉  | 80119/100629 [1:02:56<14:56, 22.89it/s]

 80%|███████▉  | 80122/100629 [1:02:56<14:44, 23.19it/s]

 80%|███████▉  | 80125/100629 [1:02:57<18:32, 18.43it/s]

 80%|███████▉  | 80128/100629 [1:02:57<16:26, 20.78it/s]

 80%|███████▉  | 80131/100629 [1:02:57<17:27, 19.56it/s]

 80%|███████▉  | 80134/100629 [1:02:57<17:04, 20.01it/s]

 80%|███████▉  | 80138/100629 [1:02:57<15:01, 22.73it/s]

 80%|███████▉  | 80141/100629 [1:02:57<15:17, 22.33it/s]

 80%|███████▉  | 80144/100629 [1:02:57<14:53, 22.92it/s]

 80%|███████▉  | 80149/100629 [1:02:58<12:44, 26.78it/s]

 80%|███████▉  | 80152/100629 [1:02:58<12:57, 26.34it/s]

 80%|███████▉  | 80155/100629 [1:02:58<14:45, 23.11it/s]

 80%|███████▉  | 80158/100629 [1:02:58<14:53, 22.91it/s]

 80%|███████▉  | 80161/100629 [1:02:58<14:22, 23.72it/s]

 80%|███████▉  | 80164/100629 [1:02:58<15:30, 21.99it/s]

 80%|███████▉  | 80167/100629 [1:02:58<14:41, 23.22it/s]

 80%|███████▉  | 80170/100629 [1:02:59<15:55, 21.40it/s]

 80%|███████▉  | 80173/100629 [1:02:59<15:39, 21.78it/s]

 80%|███████▉  | 80176/100629 [1:02:59<16:27, 20.72it/s]

 80%|███████▉  | 80179/100629 [1:02:59<17:12, 19.81it/s]

 80%|███████▉  | 80183/100629 [1:02:59<16:42, 20.40it/s]

 80%|███████▉  | 80186/100629 [1:02:59<15:35, 21.86it/s]

 80%|███████▉  | 80190/100629 [1:02:59<14:01, 24.27it/s]

 80%|███████▉  | 80194/100629 [1:03:00<13:47, 24.71it/s]

 80%|███████▉  | 80197/100629 [1:03:00<16:47, 20.28it/s]

 80%|███████▉  | 80200/100629 [1:03:00<15:47, 21.57it/s]

 80%|███████▉  | 80203/100629 [1:03:00<15:14, 22.34it/s]

 80%|███████▉  | 80206/100629 [1:03:00<15:06, 22.53it/s]

 80%|███████▉  | 80209/100629 [1:03:00<15:42, 21.66it/s]

 80%|███████▉  | 80212/100629 [1:03:00<16:17, 20.89it/s]

 80%|███████▉  | 80215/100629 [1:03:01<16:03, 21.19it/s]

 80%|███████▉  | 80218/100629 [1:03:01<16:19, 20.83it/s]

 80%|███████▉  | 80222/100629 [1:03:01<13:32, 25.13it/s]

 80%|███████▉  | 80226/100629 [1:03:01<12:28, 27.27it/s]

 80%|███████▉  | 80229/100629 [1:03:01<14:23, 23.62it/s]

 80%|███████▉  | 80232/100629 [1:03:01<15:16, 22.25it/s]

 80%|███████▉  | 80236/100629 [1:03:01<12:57, 26.21it/s]

 80%|███████▉  | 80239/100629 [1:03:02<13:21, 25.45it/s]

 80%|███████▉  | 80243/100629 [1:03:02<14:04, 24.15it/s]

 80%|███████▉  | 80248/100629 [1:03:02<12:17, 27.64it/s]

 80%|███████▉  | 80251/100629 [1:03:02<13:36, 24.96it/s]

 80%|███████▉  | 80254/100629 [1:03:02<13:59, 24.28it/s]

 80%|███████▉  | 80258/100629 [1:03:02<14:15, 23.80it/s]

 80%|███████▉  | 80261/100629 [1:03:03<15:00, 22.61it/s]

 80%|███████▉  | 80265/100629 [1:03:03<13:47, 24.61it/s]

 80%|███████▉  | 80268/100629 [1:03:03<16:30, 20.56it/s]

 80%|███████▉  | 80271/100629 [1:03:03<16:23, 20.71it/s]

 80%|███████▉  | 80274/100629 [1:03:03<15:35, 21.77it/s]

 80%|███████▉  | 80277/100629 [1:03:03<19:53, 17.06it/s]

 80%|███████▉  | 80279/100629 [1:03:04<21:01, 16.14it/s]

 80%|███████▉  | 80284/100629 [1:03:04<15:18, 22.16it/s]

 80%|███████▉  | 80287/100629 [1:03:04<15:44, 21.54it/s]

 80%|███████▉  | 80291/100629 [1:03:04<14:47, 22.92it/s]

 80%|███████▉  | 80294/100629 [1:03:04<14:29, 23.39it/s]

 80%|███████▉  | 80297/100629 [1:03:04<15:11, 22.31it/s]

 80%|███████▉  | 80300/100629 [1:03:04<16:45, 20.21it/s]

 80%|███████▉  | 80303/100629 [1:03:05<16:42, 20.28it/s]

 80%|███████▉  | 80307/100629 [1:03:05<14:23, 23.53it/s]

 80%|███████▉  | 80310/100629 [1:03:05<13:57, 24.27it/s]

 80%|███████▉  | 80313/100629 [1:03:05<14:14, 23.77it/s]

 80%|███████▉  | 80316/100629 [1:03:05<14:45, 22.95it/s]

 80%|███████▉  | 80319/100629 [1:03:05<15:08, 22.35it/s]

 80%|███████▉  | 80322/100629 [1:03:05<15:00, 22.56it/s]

 80%|███████▉  | 80325/100629 [1:03:06<16:30, 20.49it/s]

 80%|███████▉  | 80328/100629 [1:03:06<15:18, 22.10it/s]

 80%|███████▉  | 80333/100629 [1:03:06<11:47, 28.68it/s]

 80%|███████▉  | 80337/100629 [1:03:06<11:45, 28.77it/s]

 80%|███████▉  | 80341/100629 [1:03:06<13:08, 25.74it/s]

 80%|███████▉  | 80345/100629 [1:03:06<11:50, 28.53it/s]

 80%|███████▉  | 80349/100629 [1:03:06<13:59, 24.16it/s]

 80%|███████▉  | 80353/100629 [1:03:07<13:33, 24.92it/s]

 80%|███████▉  | 80356/100629 [1:03:07<15:06, 22.37it/s]

 80%|███████▉  | 80361/100629 [1:03:07<13:01, 25.94it/s]

 80%|███████▉  | 80364/100629 [1:03:07<15:55, 21.22it/s]

 80%|███████▉  | 80369/100629 [1:03:07<13:10, 25.64it/s]

 80%|███████▉  | 80372/100629 [1:03:07<14:42, 22.95it/s]

 80%|███████▉  | 80375/100629 [1:03:08<17:57, 18.81it/s]

 80%|███████▉  | 80378/100629 [1:03:08<17:26, 19.35it/s]

 80%|███████▉  | 80381/100629 [1:03:08<16:31, 20.42it/s]

 80%|███████▉  | 80384/100629 [1:03:08<20:50, 16.19it/s]

 80%|███████▉  | 80386/100629 [1:03:08<21:21, 15.80it/s]

 80%|███████▉  | 80390/100629 [1:03:08<16:30, 20.43it/s]

 80%|███████▉  | 80393/100629 [1:03:09<15:33, 21.69it/s]

 80%|███████▉  | 80396/100629 [1:03:09<14:39, 22.99it/s]

 80%|███████▉  | 80399/100629 [1:03:09<13:40, 24.66it/s]

 80%|███████▉  | 80402/100629 [1:03:09<13:22, 25.21it/s]

 80%|███████▉  | 80407/100629 [1:03:09<10:45, 31.33it/s]

 80%|███████▉  | 80411/100629 [1:03:09<11:20, 29.73it/s]

 80%|███████▉  | 80415/100629 [1:03:09<14:56, 22.54it/s]

 80%|███████▉  | 80418/100629 [1:03:10<15:05, 22.31it/s]

 80%|███████▉  | 80421/100629 [1:03:10<15:38, 21.53it/s]

 80%|███████▉  | 80426/100629 [1:03:10<12:41, 26.53it/s]

 80%|███████▉  | 80430/100629 [1:03:10<12:06, 27.79it/s]

 80%|███████▉  | 80433/100629 [1:03:10<14:06, 23.86it/s]

 80%|███████▉  | 80436/100629 [1:03:10<15:22, 21.89it/s]

 80%|███████▉  | 80439/100629 [1:03:10<16:23, 20.53it/s]

 80%|███████▉  | 80442/100629 [1:03:11<17:14, 19.51it/s]

 80%|███████▉  | 80445/100629 [1:03:11<17:05, 19.67it/s]

 80%|███████▉  | 80449/100629 [1:03:11<15:43, 21.39it/s]

 80%|███████▉  | 80453/100629 [1:03:11<13:24, 25.08it/s]

 80%|███████▉  | 80456/100629 [1:03:11<13:38, 24.63it/s]

 80%|███████▉  | 80459/100629 [1:03:11<13:50, 24.29it/s]

 80%|███████▉  | 80462/100629 [1:03:12<17:52, 18.81it/s]

 80%|███████▉  | 80465/100629 [1:03:12<18:09, 18.51it/s]

 80%|███████▉  | 80468/100629 [1:03:12<19:40, 17.07it/s]

 80%|███████▉  | 80470/100629 [1:03:12<19:22, 17.35it/s]

 80%|███████▉  | 80473/100629 [1:03:12<17:48, 18.86it/s]

 80%|███████▉  | 80476/100629 [1:03:12<17:03, 19.69it/s]

 80%|███████▉  | 80479/100629 [1:03:12<16:19, 20.57it/s]

 80%|███████▉  | 80482/100629 [1:03:13<16:34, 20.25it/s]

 80%|███████▉  | 80485/100629 [1:03:13<15:59, 21.00it/s]

 80%|███████▉  | 80489/100629 [1:03:13<16:52, 19.89it/s]

 80%|███████▉  | 80494/100629 [1:03:13<13:35, 24.68it/s]

 80%|███████▉  | 80499/100629 [1:03:13<11:44, 28.55it/s]

 80%|███████▉  | 80503/100629 [1:03:13<11:09, 30.07it/s]

 80%|████████  | 80507/100629 [1:03:13<11:51, 28.29it/s]

 80%|████████  | 80510/100629 [1:03:14<12:46, 26.25it/s]

 80%|████████  | 80513/100629 [1:03:14<14:47, 22.68it/s]

 80%|████████  | 80516/100629 [1:03:14<13:49, 24.23it/s]

 80%|████████  | 80519/100629 [1:03:14<17:40, 18.96it/s]

 80%|████████  | 80522/100629 [1:03:14<17:32, 19.10it/s]

 80%|████████  | 80525/100629 [1:03:14<19:06, 17.54it/s]

 80%|████████  | 80527/100629 [1:03:15<22:48, 14.69it/s]

 80%|████████  | 80529/100629 [1:03:15<24:09, 13.86it/s]

 80%|████████  | 80531/100629 [1:03:15<23:07, 14.49it/s]

 80%|████████  | 80535/100629 [1:03:15<17:51, 18.76it/s]

 80%|████████  | 80538/100629 [1:03:15<17:11, 19.48it/s]

 80%|████████  | 80541/100629 [1:03:15<16:23, 20.44it/s]

 80%|████████  | 80546/100629 [1:03:15<12:33, 26.64it/s]

 80%|████████  | 80549/100629 [1:03:16<12:34, 26.61it/s]

 80%|████████  | 80553/100629 [1:03:16<11:52, 28.18it/s]

 80%|████████  | 80556/100629 [1:03:16<12:23, 26.98it/s]

 80%|████████  | 80559/100629 [1:03:16<13:06, 25.53it/s]

 80%|████████  | 80562/100629 [1:03:16<14:18, 23.38it/s]

 80%|████████  | 80565/100629 [1:03:16<13:33, 24.65it/s]

 80%|████████  | 80568/100629 [1:03:16<14:57, 22.35it/s]

 80%|████████  | 80571/100629 [1:03:17<13:57, 23.95it/s]

 80%|████████  | 80574/100629 [1:03:17<15:19, 21.82it/s]

 80%|████████  | 80577/100629 [1:03:17<15:10, 22.03it/s]

 80%|████████  | 80580/100629 [1:03:17<16:00, 20.87it/s]

 80%|████████  | 80583/100629 [1:03:17<19:22, 17.25it/s]

 80%|████████  | 80585/100629 [1:03:17<19:20, 17.27it/s]

 80%|████████  | 80588/100629 [1:03:17<17:19, 19.28it/s]

 80%|████████  | 80591/100629 [1:03:18<17:49, 18.73it/s]

 80%|████████  | 80594/100629 [1:03:18<17:32, 19.03it/s]

 80%|████████  | 80596/100629 [1:03:18<19:43, 16.93it/s]

 80%|████████  | 80600/100629 [1:03:18<17:06, 19.51it/s]

 80%|████████  | 80603/100629 [1:03:18<15:44, 21.21it/s]

 80%|████████  | 80606/100629 [1:03:18<16:07, 20.70it/s]

 80%|████████  | 80609/100629 [1:03:18<15:14, 21.89it/s]

 80%|████████  | 80613/100629 [1:03:19<13:23, 24.91it/s]

 80%|████████  | 80617/100629 [1:03:19<11:43, 28.46it/s]

 80%|████████  | 80620/100629 [1:03:19<11:55, 27.95it/s]

 80%|████████  | 80624/100629 [1:03:19<10:51, 30.72it/s]

 80%|████████  | 80629/100629 [1:03:19<09:43, 34.27it/s]

 80%|████████  | 80633/100629 [1:03:19<10:11, 32.72it/s]

 80%|████████  | 80637/100629 [1:03:19<11:34, 28.79it/s]

 80%|████████  | 80641/100629 [1:03:19<11:52, 28.04it/s]

 80%|████████  | 80644/100629 [1:03:20<12:40, 26.26it/s]

 80%|████████  | 80647/100629 [1:03:20<12:29, 26.67it/s]

 80%|████████  | 80651/100629 [1:03:20<14:34, 22.84it/s]

 80%|████████  | 80656/100629 [1:03:20<12:46, 26.06it/s]

 80%|████████  | 80659/100629 [1:03:20<14:59, 22.19it/s]

 80%|████████  | 80662/100629 [1:03:20<15:20, 21.69it/s]

 80%|████████  | 80665/100629 [1:03:21<14:40, 22.67it/s]

 80%|████████  | 80668/100629 [1:03:21<17:20, 19.19it/s]

 80%|████████  | 80671/100629 [1:03:21<17:43, 18.76it/s]

 80%|████████  | 80674/100629 [1:03:21<16:19, 20.38it/s]

 80%|████████  | 80677/100629 [1:03:21<17:05, 19.45it/s]

 80%|████████  | 80680/100629 [1:03:21<15:37, 21.29it/s]

 80%|████████  | 80683/100629 [1:03:21<15:26, 21.54it/s]

 80%|████████  | 80687/100629 [1:03:22<14:33, 22.82it/s]

 80%|████████  | 80690/100629 [1:03:22<14:32, 22.86it/s]

 80%|████████  | 80693/100629 [1:03:22<14:16, 23.27it/s]

 80%|████████  | 80696/100629 [1:03:22<13:36, 24.41it/s]

 80%|████████  | 80699/100629 [1:03:22<16:22, 20.28it/s]

 80%|████████  | 80702/100629 [1:03:22<17:37, 18.84it/s]

 80%|████████  | 80706/100629 [1:03:23<16:43, 19.86it/s]

 80%|████████  | 80710/100629 [1:03:23<14:43, 22.55it/s]

 80%|████████  | 80713/100629 [1:03:23<14:59, 22.15it/s]

 80%|████████  | 80717/100629 [1:03:23<14:12, 23.35it/s]

 80%|████████  | 80720/100629 [1:03:23<13:47, 24.05it/s]

 80%|████████  | 80724/100629 [1:03:23<12:55, 25.65it/s]

 80%|████████  | 80727/100629 [1:03:23<15:19, 21.65it/s]

 80%|████████  | 80730/100629 [1:03:24<15:38, 21.21it/s]

 80%|████████  | 80733/100629 [1:03:24<18:12, 18.21it/s]

 80%|████████  | 80735/100629 [1:03:24<18:13, 18.19it/s]

 80%|████████  | 80739/100629 [1:03:24<14:50, 22.32it/s]

 80%|████████  | 80742/100629 [1:03:24<15:17, 21.68it/s]

 80%|████████  | 80745/100629 [1:03:24<19:08, 17.31it/s]

 80%|████████  | 80749/100629 [1:03:25<15:37, 21.21it/s]

 80%|████████  | 80752/100629 [1:03:25<15:07, 21.91it/s]

 80%|████████  | 80757/100629 [1:03:25<12:59, 25.49it/s]

 80%|████████  | 80760/100629 [1:03:25<13:43, 24.11it/s]

 80%|████████  | 80763/100629 [1:03:25<13:36, 24.34it/s]

 80%|████████  | 80767/100629 [1:03:25<15:06, 21.90it/s]

 80%|████████  | 80771/100629 [1:03:25<13:18, 24.87it/s]

 80%|████████  | 80774/100629 [1:03:26<13:46, 24.01it/s]

 80%|████████  | 80777/100629 [1:03:26<13:50, 23.90it/s]

 80%|████████  | 80780/100629 [1:03:26<13:14, 24.99it/s]

 80%|████████  | 80783/100629 [1:03:26<13:07, 25.20it/s]

 80%|████████  | 80786/100629 [1:03:26<13:06, 25.23it/s]

 80%|████████  | 80789/100629 [1:03:26<14:51, 22.26it/s]

 80%|████████  | 80792/100629 [1:03:26<14:27, 22.86it/s]

 80%|████████  | 80796/100629 [1:03:26<12:46, 25.86it/s]

 80%|████████  | 80799/100629 [1:03:27<14:13, 23.24it/s]

 80%|████████  | 80802/100629 [1:03:27<17:39, 18.70it/s]

 80%|████████  | 80805/100629 [1:03:27<17:57, 18.39it/s]

 80%|████████  | 80808/100629 [1:03:27<17:06, 19.30it/s]

 80%|████████  | 80811/100629 [1:03:27<18:00, 18.34it/s]

 80%|████████  | 80813/100629 [1:03:27<18:43, 17.64it/s]

 80%|████████  | 80816/100629 [1:03:28<19:02, 17.34it/s]

 80%|████████  | 80818/100629 [1:03:28<18:35, 17.76it/s]

 80%|████████  | 80820/100629 [1:03:28<18:17, 18.06it/s]

 80%|████████  | 80823/100629 [1:03:28<17:49, 18.52it/s]

 80%|████████  | 80826/100629 [1:03:28<16:15, 20.30it/s]

 80%|████████  | 80829/100629 [1:03:28<14:47, 22.32it/s]

 80%|████████  | 80833/100629 [1:03:28<12:46, 25.81it/s]

 80%|████████  | 80836/100629 [1:03:29<14:13, 23.18it/s]

 80%|████████  | 80839/100629 [1:03:29<16:25, 20.09it/s]

 80%|████████  | 80842/100629 [1:03:29<15:52, 20.78it/s]

 80%|████████  | 80845/100629 [1:03:29<18:03, 18.25it/s]

 80%|████████  | 80848/100629 [1:03:29<16:41, 19.75it/s]

 80%|████████  | 80851/100629 [1:03:29<18:54, 17.43it/s]

 80%|████████  | 80853/100629 [1:03:30<18:47, 17.53it/s]

 80%|████████  | 80856/100629 [1:03:30<17:43, 18.59it/s]

 80%|████████  | 80858/100629 [1:03:30<17:32, 18.79it/s]

 80%|████████  | 80861/100629 [1:03:30<16:23, 20.10it/s]

 80%|████████  | 80864/100629 [1:03:30<16:33, 19.90it/s]

 80%|████████  | 80867/100629 [1:03:30<15:07, 21.78it/s]

 80%|████████  | 80870/100629 [1:03:30<16:05, 20.47it/s]

 80%|████████  | 80873/100629 [1:03:30<14:36, 22.55it/s]

 80%|████████  | 80876/100629 [1:03:31<14:50, 22.18it/s]

 80%|████████  | 80879/100629 [1:03:31<15:22, 21.40it/s]

 80%|████████  | 80882/100629 [1:03:31<17:07, 19.21it/s]

 80%|████████  | 80885/100629 [1:03:31<19:14, 17.10it/s]

 80%|████████  | 80888/100629 [1:03:31<18:09, 18.12it/s]

 80%|████████  | 80892/100629 [1:03:31<14:48, 22.21it/s]

 80%|████████  | 80895/100629 [1:03:32<14:31, 22.64it/s]

 80%|████████  | 80898/100629 [1:03:32<17:56, 18.33it/s]

 80%|████████  | 80901/100629 [1:03:32<18:33, 17.72it/s]

 80%|████████  | 80904/100629 [1:03:32<17:27, 18.83it/s]

 80%|████████  | 80909/100629 [1:03:32<13:55, 23.61it/s]

 80%|████████  | 80912/100629 [1:03:32<14:13, 23.11it/s]

 80%|████████  | 80915/100629 [1:03:32<13:40, 24.01it/s]

 80%|████████  | 80920/100629 [1:03:33<11:07, 29.53it/s]

 80%|████████  | 80925/100629 [1:03:33<09:30, 34.51it/s]

 80%|████████  | 80929/100629 [1:03:33<13:10, 24.93it/s]

 80%|████████  | 80934/100629 [1:03:33<11:02, 29.72it/s]

 80%|████████  | 80938/100629 [1:03:33<12:13, 26.84it/s]

 80%|████████  | 80942/100629 [1:03:33<12:38, 25.95it/s]

 80%|████████  | 80945/100629 [1:03:34<14:50, 22.11it/s]

 80%|████████  | 80949/100629 [1:03:34<13:04, 25.08it/s]

 80%|████████  | 80952/100629 [1:03:34<14:08, 23.19it/s]

 80%|████████  | 80955/100629 [1:03:34<14:21, 22.84it/s]

 80%|████████  | 80958/100629 [1:03:34<14:16, 22.97it/s]

 80%|████████  | 80961/100629 [1:03:34<14:44, 22.23it/s]

 80%|████████  | 80964/100629 [1:03:34<15:27, 21.20it/s]

 80%|████████  | 80967/100629 [1:03:35<17:21, 18.88it/s]

 80%|████████  | 80970/100629 [1:03:35<16:33, 19.79it/s]

 80%|████████  | 80973/100629 [1:03:35<16:56, 19.33it/s]

 80%|████████  | 80975/100629 [1:03:35<17:00, 19.26it/s]

 80%|████████  | 80980/100629 [1:03:35<12:36, 25.96it/s]

 80%|████████  | 80983/100629 [1:03:35<14:59, 21.84it/s]

 80%|████████  | 80987/100629 [1:03:36<14:07, 23.17it/s]

 80%|████████  | 80991/100629 [1:03:36<12:33, 26.06it/s]

 80%|████████  | 80995/100629 [1:03:36<11:52, 27.56it/s]

 80%|████████  | 80998/100629 [1:03:36<12:04, 27.09it/s]

 80%|████████  | 81001/100629 [1:03:36<12:23, 26.38it/s]

 80%|████████  | 81004/100629 [1:03:36<12:24, 26.36it/s]

 81%|████████  | 81007/100629 [1:03:36<12:54, 25.34it/s]

 81%|████████  | 81010/100629 [1:03:36<12:31, 26.10it/s]

 81%|████████  | 81013/100629 [1:03:36<12:56, 25.25it/s]

 81%|████████  | 81016/100629 [1:03:37<13:30, 24.19it/s]

 81%|████████  | 81020/100629 [1:03:37<11:40, 27.99it/s]

 81%|████████  | 81023/100629 [1:03:37<12:52, 25.39it/s]

 81%|████████  | 81026/100629 [1:03:37<16:56, 19.28it/s]

 81%|████████  | 81029/100629 [1:03:37<15:48, 20.66it/s]

 81%|████████  | 81032/100629 [1:03:37<16:03, 20.35it/s]

 81%|████████  | 81036/100629 [1:03:38<14:41, 22.24it/s]

 81%|████████  | 81040/100629 [1:03:38<13:53, 23.51it/s]

 81%|████████  | 81043/100629 [1:03:38<14:45, 22.13it/s]

 81%|████████  | 81046/100629 [1:03:38<14:28, 22.55it/s]

 81%|████████  | 81049/100629 [1:03:38<15:35, 20.92it/s]

 81%|████████  | 81053/100629 [1:03:38<14:08, 23.08it/s]

 81%|████████  | 81057/100629 [1:03:38<13:42, 23.79it/s]

 81%|████████  | 81060/100629 [1:03:39<14:42, 22.18it/s]

 81%|████████  | 81064/100629 [1:03:39<13:09, 24.79it/s]

 81%|████████  | 81067/100629 [1:03:39<12:45, 25.56it/s]

 81%|████████  | 81072/100629 [1:03:39<10:52, 29.95it/s]

 81%|████████  | 81076/100629 [1:03:39<11:04, 29.43it/s]

 81%|████████  | 81080/100629 [1:03:39<11:03, 29.47it/s]

 81%|████████  | 81084/100629 [1:03:39<10:25, 31.24it/s]

 81%|████████  | 81088/100629 [1:03:39<10:57, 29.71it/s]

 81%|████████  | 81092/100629 [1:03:40<13:22, 24.34it/s]

 81%|████████  | 81095/100629 [1:03:40<14:54, 21.84it/s]

 81%|████████  | 81098/100629 [1:03:40<13:52, 23.47it/s]

 81%|████████  | 81102/100629 [1:03:40<13:13, 24.62it/s]

 81%|████████  | 81106/100629 [1:03:40<11:50, 27.49it/s]

 81%|████████  | 81109/100629 [1:03:40<12:17, 26.46it/s]

 81%|████████  | 81112/100629 [1:03:40<12:49, 25.35it/s]

 81%|████████  | 81115/100629 [1:03:41<14:15, 22.80it/s]

 81%|████████  | 81118/100629 [1:03:41<15:55, 20.43it/s]

 81%|████████  | 81121/100629 [1:03:41<16:45, 19.40it/s]

 81%|████████  | 81124/100629 [1:03:41<20:03, 16.21it/s]

 81%|████████  | 81128/100629 [1:03:41<16:05, 20.19it/s]

 81%|████████  | 81131/100629 [1:03:42<15:00, 21.65it/s]

 81%|████████  | 81134/100629 [1:03:42<17:21, 18.72it/s]

 81%|████████  | 81138/100629 [1:03:42<15:15, 21.29it/s]

 81%|████████  | 81141/100629 [1:03:42<15:01, 21.63it/s]

 81%|████████  | 81144/100629 [1:03:42<18:19, 17.72it/s]

 81%|████████  | 81146/100629 [1:03:42<18:03, 17.98it/s]

 81%|████████  | 81149/100629 [1:03:42<17:07, 18.96it/s]

 81%|████████  | 81152/100629 [1:03:43<16:56, 19.15it/s]

 81%|████████  | 81155/100629 [1:03:43<16:05, 20.17it/s]

 81%|████████  | 81158/100629 [1:03:43<15:26, 21.02it/s]

 81%|████████  | 81161/100629 [1:03:43<16:06, 20.14it/s]

 81%|████████  | 81165/100629 [1:03:43<14:14, 22.78it/s]

 81%|████████  | 81168/100629 [1:03:43<14:40, 22.10it/s]

 81%|████████  | 81171/100629 [1:03:44<17:22, 18.66it/s]

 81%|████████  | 81173/100629 [1:03:44<17:21, 18.68it/s]

 81%|████████  | 81175/100629 [1:03:44<18:19, 17.69it/s]

 81%|████████  | 81177/100629 [1:03:44<22:18, 14.54it/s]

 81%|████████  | 81179/100629 [1:03:44<22:11, 14.61it/s]

 81%|████████  | 81181/100629 [1:03:44<21:04, 15.37it/s]

 81%|████████  | 81183/100629 [1:03:44<19:50, 16.33it/s]

 81%|████████  | 81188/100629 [1:03:45<14:37, 22.15it/s]

 81%|████████  | 81191/100629 [1:03:45<17:44, 18.26it/s]

 81%|████████  | 81194/100629 [1:03:45<16:36, 19.50it/s]

 81%|████████  | 81197/100629 [1:03:45<15:21, 21.08it/s]

 81%|████████  | 81200/100629 [1:03:45<16:49, 19.25it/s]

 81%|████████  | 81203/100629 [1:03:45<15:45, 20.54it/s]

 81%|████████  | 81207/100629 [1:03:45<13:07, 24.66it/s]

 81%|████████  | 81211/100629 [1:03:46<11:58, 27.01it/s]

 81%|████████  | 81214/100629 [1:03:46<13:49, 23.42it/s]

 81%|████████  | 81218/100629 [1:03:46<12:33, 25.77it/s]

 81%|████████  | 81221/100629 [1:03:46<12:46, 25.31it/s]

 81%|████████  | 81224/100629 [1:03:46<13:12, 24.47it/s]

 81%|████████  | 81227/100629 [1:03:46<16:03, 20.14it/s]

 81%|████████  | 81230/100629 [1:03:46<16:04, 20.12it/s]

 81%|████████  | 81233/100629 [1:03:47<15:44, 20.54it/s]

 81%|████████  | 81236/100629 [1:03:47<14:19, 22.57it/s]

 81%|████████  | 81240/100629 [1:03:47<12:08, 26.63it/s]

 81%|████████  | 81243/100629 [1:03:47<12:56, 24.95it/s]

 81%|████████  | 81247/100629 [1:03:47<11:54, 27.13it/s]

 81%|████████  | 81250/100629 [1:03:47<12:06, 26.69it/s]

 81%|████████  | 81253/100629 [1:03:47<12:30, 25.81it/s]

 81%|████████  | 81256/100629 [1:03:47<14:39, 22.02it/s]

 81%|████████  | 81259/100629 [1:03:48<14:24, 22.41it/s]

 81%|████████  | 81262/100629 [1:03:48<17:02, 18.94it/s]

 81%|████████  | 81265/100629 [1:03:48<15:18, 21.09it/s]

 81%|████████  | 81271/100629 [1:03:48<13:47, 23.39it/s]

 81%|████████  | 81274/100629 [1:03:48<13:15, 24.34it/s]

 81%|████████  | 81277/100629 [1:03:48<14:26, 22.34it/s]

 81%|████████  | 81280/100629 [1:03:49<16:51, 19.12it/s]

 81%|████████  | 81283/100629 [1:03:49<17:25, 18.50it/s]

 81%|████████  | 81285/100629 [1:03:49<18:29, 17.44it/s]

 81%|████████  | 81287/100629 [1:03:49<18:33, 17.37it/s]

 81%|████████  | 81290/100629 [1:03:49<17:14, 18.70it/s]

 81%|████████  | 81292/100629 [1:03:49<17:43, 18.19it/s]

 81%|████████  | 81295/100629 [1:03:49<15:33, 20.71it/s]

 81%|████████  | 81298/100629 [1:03:50<14:43, 21.89it/s]

 81%|████████  | 81301/100629 [1:03:50<15:08, 21.26it/s]

 81%|████████  | 81304/100629 [1:03:50<14:44, 21.86it/s]

 81%|████████  | 81307/100629 [1:03:50<17:11, 18.73it/s]

 81%|████████  | 81309/100629 [1:03:50<18:19, 17.57it/s]

 81%|████████  | 81312/100629 [1:03:50<18:12, 17.68it/s]

 81%|████████  | 81315/100629 [1:03:50<16:42, 19.27it/s]

 81%|████████  | 81317/100629 [1:03:51<17:20, 18.56it/s]

 81%|████████  | 81320/100629 [1:03:51<15:13, 21.15it/s]

 81%|████████  | 81323/100629 [1:03:51<13:51, 23.22it/s]

 81%|████████  | 81326/100629 [1:03:51<14:23, 22.36it/s]

 81%|████████  | 81329/100629 [1:03:51<14:09, 22.71it/s]

 81%|████████  | 81332/100629 [1:03:51<13:38, 23.57it/s]

 81%|████████  | 81335/100629 [1:03:51<13:30, 23.81it/s]

 81%|████████  | 81340/100629 [1:03:51<11:15, 28.58it/s]

 81%|████████  | 81343/100629 [1:03:52<14:06, 22.79it/s]

 81%|████████  | 81346/100629 [1:03:52<13:38, 23.56it/s]

 81%|████████  | 81349/100629 [1:03:52<17:08, 18.75it/s]

 81%|████████  | 81352/100629 [1:03:52<16:37, 19.32it/s]

 81%|████████  | 81356/100629 [1:03:52<14:05, 22.81it/s]

 81%|████████  | 81359/100629 [1:03:52<15:03, 21.32it/s]

 81%|████████  | 81362/100629 [1:03:53<13:52, 23.14it/s]

 81%|████████  | 81366/100629 [1:03:53<11:58, 26.82it/s]

 81%|████████  | 81369/100629 [1:03:53<13:37, 23.55it/s]

 81%|████████  | 81372/100629 [1:03:53<12:58, 24.75it/s]

 81%|████████  | 81376/100629 [1:03:53<11:41, 27.43it/s]

 81%|████████  | 81379/100629 [1:03:53<12:29, 25.70it/s]

 81%|████████  | 81382/100629 [1:03:53<12:38, 25.37it/s]

 81%|████████  | 81385/100629 [1:03:53<14:00, 22.90it/s]

 81%|████████  | 81388/100629 [1:03:54<13:46, 23.27it/s]

 81%|████████  | 81391/100629 [1:03:54<14:12, 22.57it/s]

 81%|████████  | 81394/100629 [1:03:54<17:28, 18.34it/s]

 81%|████████  | 81396/100629 [1:03:54<20:16, 15.81it/s]

 81%|████████  | 81400/100629 [1:03:54<15:56, 20.10it/s]

 81%|████████  | 81403/100629 [1:03:54<15:22, 20.84it/s]

 81%|████████  | 81406/100629 [1:03:55<15:14, 21.02it/s]

 81%|████████  | 81411/100629 [1:03:55<12:46, 25.06it/s]

 81%|████████  | 81414/100629 [1:03:55<13:16, 24.14it/s]

 81%|████████  | 81417/100629 [1:03:55<14:41, 21.80it/s]

 81%|████████  | 81421/100629 [1:03:55<12:40, 25.25it/s]

 81%|████████  | 81424/100629 [1:03:55<12:52, 24.87it/s]

 81%|████████  | 81429/100629 [1:03:55<11:06, 28.80it/s]

 81%|████████  | 81432/100629 [1:03:55<11:03, 28.95it/s]

 81%|████████  | 81435/100629 [1:03:56<11:45, 27.21it/s]

 81%|████████  | 81438/100629 [1:03:56<11:38, 27.49it/s]

 81%|████████  | 81441/100629 [1:03:56<13:04, 24.47it/s]

 81%|████████  | 81444/100629 [1:03:56<12:36, 25.36it/s]

 81%|████████  | 81448/100629 [1:03:56<11:59, 26.65it/s]

 81%|████████  | 81451/100629 [1:03:56<12:49, 24.91it/s]

 81%|████████  | 81454/100629 [1:03:56<13:25, 23.81it/s]

 81%|████████  | 81457/100629 [1:03:57<14:28, 22.06it/s]

 81%|████████  | 81461/100629 [1:03:57<12:50, 24.86it/s]

 81%|████████  | 81464/100629 [1:03:57<12:36, 25.33it/s]

 81%|████████  | 81467/100629 [1:03:57<14:05, 22.66it/s]

 81%|████████  | 81470/100629 [1:03:57<13:40, 23.35it/s]

 81%|████████  | 81474/100629 [1:03:57<12:49, 24.88it/s]

 81%|████████  | 81478/100629 [1:03:57<12:18, 25.95it/s]

 81%|████████  | 81482/100629 [1:03:57<12:11, 26.18it/s]

 81%|████████  | 81485/100629 [1:03:58<12:41, 25.13it/s]

 81%|████████  | 81488/100629 [1:03:58<13:57, 22.85it/s]

 81%|████████  | 81491/100629 [1:03:58<13:57, 22.85it/s]

 81%|████████  | 81494/100629 [1:03:58<14:35, 21.85it/s]

 81%|████████  | 81497/100629 [1:03:58<14:35, 21.85it/s]

 81%|████████  | 81500/100629 [1:03:58<14:59, 21.26it/s]

 81%|████████  | 81503/100629 [1:03:58<14:17, 22.30it/s]

 81%|████████  | 81506/100629 [1:03:59<15:09, 21.03it/s]

 81%|████████  | 81509/100629 [1:03:59<14:32, 21.92it/s]

 81%|████████  | 81512/100629 [1:03:59<14:11, 22.44it/s]

 81%|████████  | 81515/100629 [1:03:59<13:26, 23.70it/s]

 81%|████████  | 81518/100629 [1:03:59<14:50, 21.47it/s]

 81%|████████  | 81521/100629 [1:03:59<16:46, 18.99it/s]

 81%|████████  | 81523/100629 [1:04:00<18:34, 17.15it/s]

 81%|████████  | 81527/100629 [1:04:00<15:20, 20.76it/s]

 81%|████████  | 81530/100629 [1:04:00<14:14, 22.34it/s]

 81%|████████  | 81533/100629 [1:04:00<15:18, 20.78it/s]

 81%|████████  | 81536/100629 [1:04:00<17:25, 18.26it/s]

 81%|████████  | 81539/100629 [1:04:00<15:31, 20.49it/s]

 81%|████████  | 81544/100629 [1:04:00<13:01, 24.43it/s]

 81%|████████  | 81547/100629 [1:04:01<14:13, 22.37it/s]

 81%|████████  | 81550/100629 [1:04:01<14:37, 21.75it/s]

 81%|████████  | 81554/100629 [1:04:01<12:45, 24.91it/s]

 81%|████████  | 81558/100629 [1:04:01<11:21, 27.98it/s]

 81%|████████  | 81561/100629 [1:04:01<15:03, 21.10it/s]

 81%|████████  | 81564/100629 [1:04:01<13:54, 22.86it/s]

 81%|████████  | 81567/100629 [1:04:01<14:32, 21.84it/s]

 81%|████████  | 81571/100629 [1:04:02<15:04, 21.08it/s]

 81%|████████  | 81575/100629 [1:04:02<13:51, 22.92it/s]

 81%|████████  | 81578/100629 [1:04:02<18:14, 17.41it/s]

 81%|████████  | 81582/100629 [1:04:02<15:18, 20.73it/s]

 81%|████████  | 81586/100629 [1:04:02<13:38, 23.28it/s]

 81%|████████  | 81589/100629 [1:04:02<13:41, 23.18it/s]

 81%|████████  | 81592/100629 [1:04:03<14:02, 22.60it/s]

 81%|████████  | 81595/100629 [1:04:03<13:47, 23.01it/s]

 81%|████████  | 81601/100629 [1:04:03<11:44, 27.00it/s]

 81%|████████  | 81604/100629 [1:04:03<12:57, 24.46it/s]

 81%|████████  | 81607/100629 [1:04:03<12:28, 25.40it/s]

 81%|████████  | 81611/100629 [1:04:03<12:16, 25.81it/s]

 81%|████████  | 81615/100629 [1:04:03<12:08, 26.11it/s]

 81%|████████  | 81619/100629 [1:04:04<10:49, 29.26it/s]

 81%|████████  | 81623/100629 [1:04:04<10:43, 29.53it/s]

 81%|████████  | 81627/100629 [1:04:04<10:58, 28.88it/s]

 81%|████████  | 81630/100629 [1:04:04<11:46, 26.89it/s]

 81%|████████  | 81634/100629 [1:04:04<10:32, 30.02it/s]

 81%|████████  | 81638/100629 [1:04:04<11:56, 26.49it/s]

 81%|████████  | 81641/100629 [1:04:04<14:16, 22.18it/s]

 81%|████████  | 81644/100629 [1:04:05<18:46, 16.85it/s]

 81%|████████  | 81648/100629 [1:04:05<16:51, 18.76it/s]

 81%|████████  | 81651/100629 [1:04:05<17:24, 18.17it/s]

 81%|████████  | 81653/100629 [1:04:05<17:55, 17.64it/s]

 81%|████████  | 81656/100629 [1:04:05<15:59, 19.77it/s]

 81%|████████  | 81660/100629 [1:04:05<13:58, 22.63it/s]

 81%|████████  | 81663/100629 [1:04:06<21:03, 15.01it/s]

 81%|████████  | 81665/100629 [1:04:06<20:42, 15.26it/s]

 81%|████████  | 81669/100629 [1:04:06<15:56, 19.82it/s]

 81%|████████  | 81673/100629 [1:04:06<16:49, 18.77it/s]

 81%|████████  | 81677/100629 [1:04:06<16:22, 19.30it/s]

 81%|████████  | 81680/100629 [1:04:07<16:20, 19.33it/s]

 81%|████████  | 81683/100629 [1:04:07<17:31, 18.02it/s]

 81%|████████  | 81686/100629 [1:04:07<16:09, 19.54it/s]

 81%|████████  | 81689/100629 [1:04:07<20:58, 15.05it/s]

 81%|████████  | 81691/100629 [1:04:07<22:55, 13.77it/s]

 81%|████████  | 81694/100629 [1:04:08<19:41, 16.03it/s]

 81%|████████  | 81697/100629 [1:04:08<17:22, 18.17it/s]

 81%|████████  | 81700/100629 [1:04:08<20:11, 15.62it/s]

 81%|████████  | 81702/100629 [1:04:08<19:28, 16.20it/s]

 81%|████████  | 81704/100629 [1:04:08<19:44, 15.98it/s]

 81%|████████  | 81707/100629 [1:04:08<16:36, 18.99it/s]

 81%|████████  | 81710/100629 [1:04:09<22:24, 14.08it/s]

 81%|████████  | 81713/100629 [1:04:09<18:59, 16.60it/s]

 81%|████████  | 81716/100629 [1:04:09<18:41, 16.87it/s]

 81%|████████  | 81718/100629 [1:04:09<18:25, 17.10it/s]

 81%|████████  | 81720/100629 [1:04:09<19:05, 16.51it/s]

 81%|████████  | 81722/100629 [1:04:09<19:38, 16.05it/s]

 81%|████████  | 81725/100629 [1:04:09<17:26, 18.06it/s]

 81%|████████  | 81729/100629 [1:04:10<14:03, 22.41it/s]

 81%|████████  | 81732/100629 [1:04:10<14:29, 21.73it/s]

 81%|████████  | 81737/100629 [1:04:10<11:04, 28.45it/s]

 81%|████████  | 81741/100629 [1:04:10<11:07, 28.29it/s]

 81%|████████  | 81744/100629 [1:04:10<13:16, 23.70it/s]

 81%|████████  | 81747/100629 [1:04:10<13:22, 23.53it/s]

 81%|████████  | 81750/100629 [1:04:10<16:07, 19.51it/s]

 81%|████████  | 81755/100629 [1:04:11<13:09, 23.91it/s]

 81%|████████  | 81759/100629 [1:04:11<12:23, 25.38it/s]

 81%|████████▏ | 81762/100629 [1:04:11<13:16, 23.69it/s]

 81%|████████▏ | 81765/100629 [1:04:11<13:13, 23.76it/s]

 81%|████████▏ | 81768/100629 [1:04:11<12:35, 24.96it/s]

 81%|████████▏ | 81771/100629 [1:04:11<12:14, 25.67it/s]

 81%|████████▏ | 81775/100629 [1:04:11<10:49, 29.01it/s]

 81%|████████▏ | 81778/100629 [1:04:11<12:39, 24.82it/s]

 81%|████████▏ | 81781/100629 [1:04:12<13:03, 24.07it/s]

 81%|████████▏ | 81785/100629 [1:04:12<12:02, 26.09it/s]

 81%|████████▏ | 81789/100629 [1:04:12<12:58, 24.21it/s]

 81%|████████▏ | 81792/100629 [1:04:12<14:40, 21.38it/s]

 81%|████████▏ | 81795/100629 [1:04:12<14:05, 22.28it/s]

 81%|████████▏ | 81798/100629 [1:04:12<15:05, 20.79it/s]

 81%|████████▏ | 81802/100629 [1:04:13<14:35, 21.51it/s]

 81%|████████▏ | 81805/100629 [1:04:13<15:23, 20.38it/s]

 81%|████████▏ | 81808/100629 [1:04:13<14:03, 22.32it/s]

 81%|████████▏ | 81811/100629 [1:04:13<14:56, 21.00it/s]

 81%|████████▏ | 81814/100629 [1:04:13<14:35, 21.48it/s]

 81%|████████▏ | 81817/100629 [1:04:13<14:06, 22.23it/s]

 81%|████████▏ | 81820/100629 [1:04:13<13:08, 23.84it/s]

 81%|████████▏ | 81823/100629 [1:04:14<13:48, 22.70it/s]

 81%|████████▏ | 81828/100629 [1:04:14<11:11, 28.00it/s]

 81%|████████▏ | 81832/100629 [1:04:14<10:52, 28.81it/s]

 81%|████████▏ | 81836/100629 [1:04:14<11:28, 27.28it/s]

 81%|████████▏ | 81839/100629 [1:04:14<13:32, 23.13it/s]

 81%|████████▏ | 81842/100629 [1:04:14<14:04, 22.23it/s]

 81%|████████▏ | 81846/100629 [1:04:14<12:27, 25.13it/s]

 81%|████████▏ | 81849/100629 [1:04:15<15:25, 20.29it/s]

 81%|████████▏ | 81852/100629 [1:04:15<15:54, 19.66it/s]

 81%|████████▏ | 81855/100629 [1:04:15<14:46, 21.17it/s]

 81%|████████▏ | 81858/100629 [1:04:15<20:15, 15.44it/s]

 81%|████████▏ | 81860/100629 [1:04:15<20:48, 15.04it/s]

 81%|████████▏ | 81862/100629 [1:04:15<19:52, 15.74it/s]

 81%|████████▏ | 81865/100629 [1:04:16<17:01, 18.37it/s]

 81%|████████▏ | 81870/100629 [1:04:16<12:22, 25.27it/s]

 81%|████████▏ | 81873/100629 [1:04:16<12:21, 25.30it/s]

 81%|████████▏ | 81876/100629 [1:04:16<12:08, 25.74it/s]

 81%|████████▏ | 81879/100629 [1:04:16<11:56, 26.17it/s]

 81%|████████▏ | 81882/100629 [1:04:16<12:54, 24.20it/s]

 81%|████████▏ | 81885/100629 [1:04:16<14:34, 21.44it/s]

 81%|████████▏ | 81888/100629 [1:04:16<14:33, 21.46it/s]

 81%|████████▏ | 81891/100629 [1:04:17<13:26, 23.22it/s]

 81%|████████▏ | 81894/100629 [1:04:17<13:29, 23.15it/s]

 81%|████████▏ | 81897/100629 [1:04:17<14:03, 22.20it/s]

 81%|████████▏ | 81901/100629 [1:04:17<12:06, 25.77it/s]

 81%|████████▏ | 81904/100629 [1:04:17<13:52, 22.49it/s]

 81%|████████▏ | 81907/100629 [1:04:17<16:07, 19.34it/s]

 81%|████████▏ | 81910/100629 [1:04:18<15:22, 20.28it/s]

 81%|████████▏ | 81913/100629 [1:04:18<14:59, 20.81it/s]

 81%|████████▏ | 81916/100629 [1:04:18<14:36, 21.34it/s]

 81%|████████▏ | 81919/100629 [1:04:18<14:46, 21.11it/s]

 81%|████████▏ | 81922/100629 [1:04:18<14:04, 22.14it/s]

 81%|████████▏ | 81925/100629 [1:04:18<14:57, 20.85it/s]

 81%|████████▏ | 81928/100629 [1:04:18<15:32, 20.06it/s]

 81%|████████▏ | 81931/100629 [1:04:19<16:14, 19.18it/s]

 81%|████████▏ | 81934/100629 [1:04:19<14:47, 21.07it/s]

 81%|████████▏ | 81939/100629 [1:04:19<12:11, 25.53it/s]

 81%|████████▏ | 81943/100629 [1:04:19<12:40, 24.57it/s]

 81%|████████▏ | 81946/100629 [1:04:19<13:03, 23.85it/s]

 81%|████████▏ | 81949/100629 [1:04:19<16:31, 18.84it/s]

 81%|████████▏ | 81953/100629 [1:04:19<13:48, 22.54it/s]

 81%|████████▏ | 81957/100629 [1:04:20<12:55, 24.07it/s]

 81%|████████▏ | 81960/100629 [1:04:20<15:46, 19.73it/s]

 81%|████████▏ | 81963/100629 [1:04:20<15:32, 20.01it/s]

 81%|████████▏ | 81966/100629 [1:04:20<14:19, 21.72it/s]

 81%|████████▏ | 81970/100629 [1:04:20<13:10, 23.60it/s]

 81%|████████▏ | 81973/100629 [1:04:20<15:52, 19.58it/s]

 81%|████████▏ | 81976/100629 [1:04:21<17:51, 17.40it/s]

 81%|████████▏ | 81979/100629 [1:04:21<15:59, 19.44it/s]

 81%|████████▏ | 81985/100629 [1:04:21<11:18, 27.50it/s]

 81%|████████▏ | 81989/100629 [1:04:21<10:14, 30.31it/s]

 81%|████████▏ | 81994/100629 [1:04:21<10:34, 29.36it/s]

 81%|████████▏ | 81998/100629 [1:04:21<12:48, 24.24it/s]

 81%|████████▏ | 82001/100629 [1:04:22<15:36, 19.89it/s]

 81%|████████▏ | 82004/100629 [1:04:22<16:22, 18.95it/s]

 81%|████████▏ | 82007/100629 [1:04:22<15:36, 19.89it/s]

 81%|████████▏ | 82010/100629 [1:04:22<16:08, 19.23it/s]

 82%|████████▏ | 82013/100629 [1:04:22<15:37, 19.86it/s]

 82%|████████▏ | 82016/100629 [1:04:22<17:02, 18.20it/s]

 82%|████████▏ | 82018/100629 [1:04:23<17:13, 18.00it/s]

 82%|████████▏ | 82020/100629 [1:04:23<17:13, 18.00it/s]

 82%|████████▏ | 82023/100629 [1:04:23<15:45, 19.67it/s]

 82%|████████▏ | 82027/100629 [1:04:23<16:04, 19.29it/s]

 82%|████████▏ | 82030/100629 [1:04:23<15:56, 19.44it/s]

 82%|████████▏ | 82032/100629 [1:04:23<17:43, 17.49it/s]

 82%|████████▏ | 82037/100629 [1:04:23<13:43, 22.58it/s]

 82%|████████▏ | 82040/100629 [1:04:24<14:05, 21.98it/s]

 82%|████████▏ | 82044/100629 [1:04:24<12:12, 25.36it/s]

 82%|████████▏ | 82049/100629 [1:04:24<10:40, 29.02it/s]

 82%|████████▏ | 82052/100629 [1:04:24<12:23, 24.98it/s]

 82%|████████▏ | 82056/100629 [1:04:24<11:32, 26.82it/s]

 82%|████████▏ | 82059/100629 [1:04:24<11:21, 27.25it/s]

 82%|████████▏ | 82063/100629 [1:04:24<10:27, 29.61it/s]

 82%|████████▏ | 82067/100629 [1:04:25<12:28, 24.79it/s]

 82%|████████▏ | 82070/100629 [1:04:25<13:47, 22.42it/s]

 82%|████████▏ | 82073/100629 [1:04:25<14:35, 21.20it/s]

 82%|████████▏ | 82076/100629 [1:04:25<14:58, 20.64it/s]

 82%|████████▏ | 82079/100629 [1:04:25<14:36, 21.17it/s]

 82%|████████▏ | 82082/100629 [1:04:25<13:52, 22.27it/s]

 82%|████████▏ | 82085/100629 [1:04:25<14:40, 21.05it/s]

 82%|████████▏ | 82088/100629 [1:04:26<13:54, 22.21it/s]

 82%|████████▏ | 82091/100629 [1:04:26<14:45, 20.94it/s]

 82%|████████▏ | 82094/100629 [1:04:26<16:11, 19.07it/s]

 82%|████████▏ | 82097/100629 [1:04:26<15:09, 20.38it/s]

 82%|████████▏ | 82100/100629 [1:04:26<15:39, 19.73it/s]

 82%|████████▏ | 82103/100629 [1:04:26<16:10, 19.09it/s]

 82%|████████▏ | 82106/100629 [1:04:27<14:50, 20.80it/s]

 82%|████████▏ | 82109/100629 [1:04:27<15:00, 20.57it/s]

 82%|████████▏ | 82112/100629 [1:04:27<14:15, 21.66it/s]

 82%|████████▏ | 82117/100629 [1:04:27<11:56, 25.84it/s]

 82%|████████▏ | 82120/100629 [1:04:27<13:29, 22.87it/s]

 82%|████████▏ | 82123/100629 [1:04:27<17:44, 17.38it/s]

 82%|████████▏ | 82125/100629 [1:04:28<18:30, 16.66it/s]

 82%|████████▏ | 82128/100629 [1:04:28<16:26, 18.75it/s]

 82%|████████▏ | 82131/100629 [1:04:28<16:15, 18.97it/s]

 82%|████████▏ | 82134/100629 [1:04:28<14:28, 21.29it/s]

 82%|████████▏ | 82137/100629 [1:04:28<14:27, 21.31it/s]

 82%|████████▏ | 82140/100629 [1:04:28<15:26, 19.96it/s]

 82%|████████▏ | 82143/100629 [1:04:28<15:29, 19.89it/s]

 82%|████████▏ | 82146/100629 [1:04:28<14:02, 21.95it/s]

 82%|████████▏ | 82149/100629 [1:04:29<12:58, 23.73it/s]

 82%|████████▏ | 82153/100629 [1:04:29<11:45, 26.20it/s]

 82%|████████▏ | 82157/100629 [1:04:29<10:43, 28.73it/s]

 82%|████████▏ | 82161/100629 [1:04:29<09:55, 31.03it/s]

 82%|████████▏ | 82165/100629 [1:04:29<10:30, 29.30it/s]

 82%|████████▏ | 82169/100629 [1:04:29<11:24, 26.97it/s]

 82%|████████▏ | 82172/100629 [1:04:29<11:25, 26.93it/s]

 82%|████████▏ | 82177/100629 [1:04:29<09:29, 32.38it/s]

 82%|████████▏ | 82181/100629 [1:04:30<10:29, 29.30it/s]

 82%|████████▏ | 82185/100629 [1:04:30<10:14, 29.99it/s]

 82%|████████▏ | 82189/100629 [1:04:30<10:24, 29.55it/s]

 82%|████████▏ | 82193/100629 [1:04:30<13:15, 23.19it/s]

 82%|████████▏ | 82196/100629 [1:04:30<12:55, 23.77it/s]

 82%|████████▏ | 82199/100629 [1:04:30<15:08, 20.30it/s]

 82%|████████▏ | 82204/100629 [1:04:31<12:19, 24.92it/s]

 82%|████████▏ | 82207/100629 [1:04:31<11:57, 25.68it/s]

 82%|████████▏ | 82210/100629 [1:04:31<18:32, 16.55it/s]

 82%|████████▏ | 82213/100629 [1:04:31<16:39, 18.43it/s]

 82%|████████▏ | 82216/100629 [1:04:31<16:52, 18.19it/s]

 82%|████████▏ | 82220/100629 [1:04:31<14:10, 21.65it/s]

 82%|████████▏ | 82223/100629 [1:04:32<14:53, 20.59it/s]

 82%|████████▏ | 82226/100629 [1:04:32<14:33, 21.07it/s]

 82%|████████▏ | 82229/100629 [1:04:32<15:00, 20.44it/s]

 82%|████████▏ | 82232/100629 [1:04:32<14:39, 20.91it/s]

 82%|████████▏ | 82235/100629 [1:04:32<14:10, 21.63it/s]

 82%|████████▏ | 82239/100629 [1:04:32<12:51, 23.82it/s]

 82%|████████▏ | 82242/100629 [1:04:32<13:01, 23.52it/s]

 82%|████████▏ | 82245/100629 [1:04:33<13:07, 23.35it/s]

 82%|████████▏ | 82248/100629 [1:04:33<12:17, 24.92it/s]

 82%|████████▏ | 82251/100629 [1:04:33<12:48, 23.90it/s]

 82%|████████▏ | 82254/100629 [1:04:33<15:42, 19.49it/s]

 82%|████████▏ | 82257/100629 [1:04:33<17:01, 17.99it/s]

 82%|████████▏ | 82262/100629 [1:04:33<14:34, 21.00it/s]

 82%|████████▏ | 82265/100629 [1:04:34<16:25, 18.63it/s]

 82%|████████▏ | 82267/100629 [1:04:34<16:35, 18.45it/s]

 82%|████████▏ | 82271/100629 [1:04:34<14:37, 20.93it/s]

 82%|████████▏ | 82275/100629 [1:04:34<12:17, 24.87it/s]

 82%|████████▏ | 82278/100629 [1:04:34<12:47, 23.90it/s]

 82%|████████▏ | 82282/100629 [1:04:34<12:00, 25.46it/s]

 82%|████████▏ | 82285/100629 [1:04:34<11:34, 26.43it/s]

 82%|████████▏ | 82289/100629 [1:04:35<11:15, 27.16it/s]

 82%|████████▏ | 82293/100629 [1:04:35<12:07, 25.21it/s]

 82%|████████▏ | 82298/100629 [1:04:35<10:47, 28.33it/s]

 82%|████████▏ | 82301/100629 [1:04:35<12:17, 24.86it/s]

 82%|████████▏ | 82305/100629 [1:04:35<11:06, 27.50it/s]

 82%|████████▏ | 82310/100629 [1:04:35<09:35, 31.85it/s]

 82%|████████▏ | 82314/100629 [1:04:35<11:01, 27.70it/s]

 82%|████████▏ | 82317/100629 [1:04:36<11:37, 26.25it/s]

 82%|████████▏ | 82320/100629 [1:04:36<12:04, 25.27it/s]

 82%|████████▏ | 82323/100629 [1:04:36<12:17, 24.82it/s]

 82%|████████▏ | 82326/100629 [1:04:36<15:16, 19.98it/s]

 82%|████████▏ | 82329/100629 [1:04:36<14:33, 20.95it/s]

 82%|████████▏ | 82332/100629 [1:04:36<14:00, 21.76it/s]

 82%|████████▏ | 82335/100629 [1:04:36<13:21, 22.82it/s]

 82%|████████▏ | 82338/100629 [1:04:37<13:47, 22.09it/s]

 82%|████████▏ | 82341/100629 [1:04:37<13:26, 22.66it/s]

 82%|████████▏ | 82345/100629 [1:04:37<11:36, 26.24it/s]

 82%|████████▏ | 82348/100629 [1:04:37<11:23, 26.76it/s]

 82%|████████▏ | 82351/100629 [1:04:37<12:07, 25.12it/s]

 82%|████████▏ | 82354/100629 [1:04:37<13:20, 22.82it/s]

 82%|████████▏ | 82358/100629 [1:04:37<12:40, 24.04it/s]

 82%|████████▏ | 82361/100629 [1:04:38<13:22, 22.77it/s]

 82%|████████▏ | 82364/100629 [1:04:38<13:09, 23.13it/s]

 82%|████████▏ | 82367/100629 [1:04:38<14:00, 21.74it/s]

 82%|████████▏ | 82371/100629 [1:04:38<12:53, 23.59it/s]

 82%|████████▏ | 82374/100629 [1:04:38<12:43, 23.92it/s]

 82%|████████▏ | 82377/100629 [1:04:38<14:55, 20.38it/s]

 82%|████████▏ | 82380/100629 [1:04:38<15:02, 20.21it/s]

 82%|████████▏ | 82384/100629 [1:04:39<12:38, 24.04it/s]

 82%|████████▏ | 82387/100629 [1:04:39<12:19, 24.67it/s]

 82%|████████▏ | 82390/100629 [1:04:39<12:22, 24.58it/s]

 82%|████████▏ | 82394/100629 [1:04:39<10:49, 28.09it/s]

 82%|████████▏ | 82397/100629 [1:04:39<11:44, 25.87it/s]

 82%|████████▏ | 82401/100629 [1:04:39<11:21, 26.74it/s]

 82%|████████▏ | 82404/100629 [1:04:39<12:16, 24.74it/s]

 82%|████████▏ | 82407/100629 [1:04:39<11:42, 25.93it/s]

 82%|████████▏ | 82410/100629 [1:04:40<12:28, 24.35it/s]

 82%|████████▏ | 82413/100629 [1:04:40<13:12, 22.98it/s]

 82%|████████▏ | 82416/100629 [1:04:40<13:31, 22.44it/s]

 82%|████████▏ | 82419/100629 [1:04:40<16:21, 18.55it/s]

 82%|████████▏ | 82421/100629 [1:04:40<16:28, 18.42it/s]

 82%|████████▏ | 82423/100629 [1:04:40<18:43, 16.21it/s]

 82%|████████▏ | 82426/100629 [1:04:40<16:24, 18.50it/s]

 82%|████████▏ | 82429/100629 [1:04:41<15:26, 19.64it/s]

 82%|████████▏ | 82434/100629 [1:04:41<12:04, 25.10it/s]

 82%|████████▏ | 82437/100629 [1:04:41<11:42, 25.91it/s]

 82%|████████▏ | 82440/100629 [1:04:41<11:20, 26.73it/s]

 82%|████████▏ | 82443/100629 [1:04:41<13:32, 22.38it/s]

 82%|████████▏ | 82446/100629 [1:04:41<13:07, 23.10it/s]

 82%|████████▏ | 82449/100629 [1:04:41<16:48, 18.02it/s]

 82%|████████▏ | 82452/100629 [1:04:42<15:26, 19.61it/s]

 82%|████████▏ | 82457/100629 [1:04:42<13:25, 22.57it/s]

 82%|████████▏ | 82461/100629 [1:04:42<13:41, 22.11it/s]

 82%|████████▏ | 82465/100629 [1:04:42<12:27, 24.29it/s]

 82%|████████▏ | 82469/100629 [1:04:42<11:32, 26.23it/s]

 82%|████████▏ | 82472/100629 [1:04:42<12:20, 24.53it/s]

 82%|████████▏ | 82475/100629 [1:04:43<13:24, 22.57it/s]

 82%|████████▏ | 82478/100629 [1:04:43<14:31, 20.83it/s]

 82%|████████▏ | 82481/100629 [1:04:43<14:34, 20.76it/s]

 82%|████████▏ | 82485/100629 [1:04:43<12:46, 23.67it/s]

 82%|████████▏ | 82488/100629 [1:04:43<13:59, 21.62it/s]

 82%|████████▏ | 82491/100629 [1:04:43<14:39, 20.62it/s]

 82%|████████▏ | 82494/100629 [1:04:43<15:35, 19.39it/s]

 82%|████████▏ | 82496/100629 [1:04:44<16:37, 18.18it/s]

 82%|████████▏ | 82498/100629 [1:04:44<21:25, 14.11it/s]

 82%|████████▏ | 82500/100629 [1:04:44<25:13, 11.98it/s]

 82%|████████▏ | 82503/100629 [1:04:44<21:35, 13.99it/s]

 82%|████████▏ | 82507/100629 [1:04:44<17:12, 17.55it/s]

 82%|████████▏ | 82509/100629 [1:04:45<17:48, 16.96it/s]

 82%|████████▏ | 82513/100629 [1:04:45<17:01, 17.73it/s]

 82%|████████▏ | 82516/100629 [1:04:45<16:05, 18.75it/s]

 82%|████████▏ | 82519/100629 [1:04:45<19:27, 15.51it/s]

 82%|████████▏ | 82522/100629 [1:04:45<17:07, 17.63it/s]

 82%|████████▏ | 82525/100629 [1:04:45<16:16, 18.54it/s]

 82%|████████▏ | 82528/100629 [1:04:46<15:16, 19.75it/s]

 82%|████████▏ | 82531/100629 [1:04:46<19:03, 15.83it/s]

 82%|████████▏ | 82534/100629 [1:04:46<17:23, 17.33it/s]

 82%|████████▏ | 82536/100629 [1:04:46<18:50, 16.00it/s]

 82%|████████▏ | 82539/100629 [1:04:46<16:50, 17.90it/s]

 82%|████████▏ | 82541/100629 [1:04:46<19:54, 15.14it/s]

 82%|████████▏ | 82545/100629 [1:04:47<15:11, 19.84it/s]

 82%|████████▏ | 82548/100629 [1:04:47<16:37, 18.12it/s]

 82%|████████▏ | 82551/100629 [1:04:47<16:05, 18.72it/s]

 82%|████████▏ | 82554/100629 [1:04:47<15:53, 18.96it/s]

 82%|████████▏ | 82557/100629 [1:04:47<17:47, 16.92it/s]

 82%|████████▏ | 82560/100629 [1:04:47<16:26, 18.32it/s]

 82%|████████▏ | 82564/100629 [1:04:47<13:18, 22.61it/s]

 82%|████████▏ | 82567/100629 [1:04:48<14:18, 21.04it/s]

 82%|████████▏ | 82570/100629 [1:04:48<14:22, 20.93it/s]

 82%|████████▏ | 82573/100629 [1:04:48<15:01, 20.03it/s]

 82%|████████▏ | 82576/100629 [1:04:48<14:23, 20.91it/s]

 82%|████████▏ | 82580/100629 [1:04:48<11:57, 25.16it/s]

 82%|████████▏ | 82584/100629 [1:04:48<10:48, 27.83it/s]

 82%|████████▏ | 82588/100629 [1:04:48<09:48, 30.65it/s]

 82%|████████▏ | 82592/100629 [1:04:49<10:53, 27.59it/s]

 82%|████████▏ | 82596/100629 [1:04:49<10:40, 28.17it/s]

 82%|████████▏ | 82599/100629 [1:04:49<12:22, 24.29it/s]

 82%|████████▏ | 82603/100629 [1:04:49<12:43, 23.60it/s]

 82%|████████▏ | 82606/100629 [1:04:49<14:33, 20.63it/s]

 82%|████████▏ | 82609/100629 [1:04:49<13:47, 21.77it/s]

 82%|████████▏ | 82612/100629 [1:04:50<14:05, 21.31it/s]

 82%|████████▏ | 82615/100629 [1:04:50<15:58, 18.79it/s]

 82%|████████▏ | 82617/100629 [1:04:50<15:59, 18.77it/s]

 82%|████████▏ | 82620/100629 [1:04:50<17:33, 17.10it/s]

 82%|████████▏ | 82622/100629 [1:04:50<17:14, 17.41it/s]

 82%|████████▏ | 82624/100629 [1:04:50<17:04, 17.58it/s]

 82%|████████▏ | 82627/100629 [1:04:51<18:19, 16.37it/s]

 82%|████████▏ | 82631/100629 [1:04:51<15:48, 18.97it/s]

 82%|████████▏ | 82634/100629 [1:04:51<14:30, 20.66it/s]

 82%|████████▏ | 82637/100629 [1:04:51<14:49, 20.23it/s]

 82%|████████▏ | 82640/100629 [1:04:51<18:10, 16.50it/s]

 82%|████████▏ | 82643/100629 [1:04:51<16:01, 18.71it/s]

 82%|████████▏ | 82646/100629 [1:04:51<16:16, 18.42it/s]

 82%|████████▏ | 82650/100629 [1:04:52<13:39, 21.95it/s]

 82%|████████▏ | 82653/100629 [1:04:52<13:25, 22.32it/s]

 82%|████████▏ | 82656/100629 [1:04:52<14:25, 20.77it/s]

 82%|████████▏ | 82659/100629 [1:04:52<16:05, 18.62it/s]

 82%|████████▏ | 82662/100629 [1:04:52<15:09, 19.76it/s]

 82%|████████▏ | 82665/100629 [1:04:52<15:04, 19.85it/s]

 82%|████████▏ | 82668/100629 [1:04:53<14:55, 20.06it/s]

 82%|████████▏ | 82671/100629 [1:04:53<13:35, 22.03it/s]

 82%|████████▏ | 82674/100629 [1:04:53<13:23, 22.36it/s]

 82%|████████▏ | 82677/100629 [1:04:53<15:03, 19.86it/s]

 82%|████████▏ | 82680/100629 [1:04:53<16:18, 18.34it/s]

 82%|████████▏ | 82683/100629 [1:04:53<14:57, 19.99it/s]

 82%|████████▏ | 82686/100629 [1:04:53<17:03, 17.53it/s]

 82%|████████▏ | 82688/100629 [1:04:54<17:26, 17.15it/s]

 82%|████████▏ | 82693/100629 [1:04:54<12:40, 23.60it/s]

 82%|████████▏ | 82696/100629 [1:04:54<14:30, 20.61it/s]

 82%|████████▏ | 82699/100629 [1:04:54<14:35, 20.47it/s]

 82%|████████▏ | 82702/100629 [1:04:54<14:15, 20.95it/s]

 82%|████████▏ | 82705/100629 [1:04:54<14:01, 21.30it/s]

 82%|████████▏ | 82711/100629 [1:04:54<11:29, 25.98it/s]

 82%|████████▏ | 82714/100629 [1:04:55<11:39, 25.60it/s]

 82%|████████▏ | 82717/100629 [1:04:55<11:49, 25.25it/s]

 82%|████████▏ | 82720/100629 [1:04:55<12:09, 24.54it/s]

 82%|████████▏ | 82723/100629 [1:04:55<12:49, 23.27it/s]

 82%|████████▏ | 82726/100629 [1:04:55<12:48, 23.29it/s]

 82%|████████▏ | 82729/100629 [1:04:55<13:35, 21.95it/s]

 82%|████████▏ | 82732/100629 [1:04:55<13:04, 22.81it/s]

 82%|████████▏ | 82735/100629 [1:04:56<13:52, 21.51it/s]

 82%|████████▏ | 82738/100629 [1:04:56<14:01, 21.26it/s]

 82%|████████▏ | 82741/100629 [1:04:56<14:57, 19.93it/s]

 82%|████████▏ | 82744/100629 [1:04:56<16:15, 18.34it/s]

 82%|████████▏ | 82746/100629 [1:04:56<17:39, 16.87it/s]

 82%|████████▏ | 82748/100629 [1:04:56<17:14, 17.29it/s]

 82%|████████▏ | 82753/100629 [1:04:57<14:03, 21.20it/s]

 82%|████████▏ | 82756/100629 [1:04:57<15:55, 18.70it/s]

 82%|████████▏ | 82760/100629 [1:04:57<13:04, 22.77it/s]

 82%|████████▏ | 82763/100629 [1:04:57<13:09, 22.64it/s]

 82%|████████▏ | 82766/100629 [1:04:57<15:13, 19.55it/s]

 82%|████████▏ | 82769/100629 [1:04:57<14:11, 20.98it/s]

 82%|████████▏ | 82772/100629 [1:04:57<13:47, 21.58it/s]

 82%|████████▏ | 82775/100629 [1:04:58<19:11, 15.51it/s]

 82%|████████▏ | 82778/100629 [1:04:58<16:35, 17.93it/s]

 82%|████████▏ | 82781/100629 [1:04:58<19:58, 14.89it/s]

 82%|████████▏ | 82783/100629 [1:04:58<19:04, 15.59it/s]

 82%|████████▏ | 82786/100629 [1:04:58<17:47, 16.71it/s]

 82%|████████▏ | 82790/100629 [1:04:59<14:33, 20.43it/s]

 82%|████████▏ | 82794/100629 [1:04:59<12:52, 23.09it/s]

 82%|████████▏ | 82797/100629 [1:04:59<15:36, 19.05it/s]

 82%|████████▏ | 82800/100629 [1:04:59<15:23, 19.31it/s]

 82%|████████▏ | 82803/100629 [1:04:59<15:53, 18.69it/s]

 82%|████████▏ | 82805/100629 [1:04:59<15:40, 18.94it/s]

 82%|████████▏ | 82808/100629 [1:04:59<14:00, 21.21it/s]

 82%|████████▏ | 82811/100629 [1:05:00<13:54, 21.36it/s]

 82%|████████▏ | 82814/100629 [1:05:00<15:43, 18.87it/s]

 82%|████████▏ | 82817/100629 [1:05:00<14:12, 20.88it/s]

 82%|████████▏ | 82820/100629 [1:05:00<16:06, 18.43it/s]

 82%|████████▏ | 82822/100629 [1:05:00<21:49, 13.59it/s]

 82%|████████▏ | 82824/100629 [1:05:00<20:45, 14.30it/s]

 82%|████████▏ | 82828/100629 [1:05:01<15:52, 18.69it/s]

 82%|████████▏ | 82831/100629 [1:05:01<15:41, 18.90it/s]

 82%|████████▏ | 82834/100629 [1:05:01<17:27, 16.99it/s]

 82%|████████▏ | 82836/100629 [1:05:01<18:19, 16.18it/s]

 82%|████████▏ | 82839/100629 [1:05:01<16:10, 18.34it/s]

 82%|████████▏ | 82843/100629 [1:05:01<14:03, 21.09it/s]

 82%|████████▏ | 82846/100629 [1:05:02<15:25, 19.21it/s]

 82%|████████▏ | 82850/100629 [1:05:02<13:18, 22.26it/s]

 82%|████████▏ | 82853/100629 [1:05:02<16:49, 17.61it/s]

 82%|████████▏ | 82855/100629 [1:05:02<17:47, 16.65it/s]

 82%|████████▏ | 82857/100629 [1:05:02<17:40, 16.76it/s]

 82%|████████▏ | 82861/100629 [1:05:02<15:23, 19.24it/s]

 82%|████████▏ | 82865/100629 [1:05:02<13:10, 22.49it/s]

 82%|████████▏ | 82871/100629 [1:05:03<10:12, 29.00it/s]

 82%|████████▏ | 82875/100629 [1:05:03<11:26, 25.85it/s]

 82%|████████▏ | 82878/100629 [1:05:03<11:17, 26.21it/s]

 82%|████████▏ | 82882/100629 [1:05:03<11:04, 26.72it/s]

 82%|████████▏ | 82886/100629 [1:05:03<10:29, 28.19it/s]

 82%|████████▏ | 82890/100629 [1:05:03<10:58, 26.95it/s]

 82%|████████▏ | 82893/100629 [1:05:03<10:45, 27.46it/s]

 82%|████████▏ | 82897/100629 [1:05:04<11:22, 25.98it/s]

 82%|████████▏ | 82901/100629 [1:05:04<12:11, 24.24it/s]

 82%|████████▏ | 82904/100629 [1:05:04<12:39, 23.34it/s]

 82%|████████▏ | 82907/100629 [1:05:04<13:35, 21.72it/s]

 82%|████████▏ | 82910/100629 [1:05:04<15:23, 19.18it/s]

 82%|████████▏ | 82913/100629 [1:05:04<14:00, 21.09it/s]

 82%|████████▏ | 82917/100629 [1:05:05<12:29, 23.62it/s]

 82%|████████▏ | 82920/100629 [1:05:05<14:12, 20.77it/s]

 82%|████████▏ | 82923/100629 [1:05:05<13:21, 22.09it/s]

 82%|████████▏ | 82926/100629 [1:05:05<12:53, 22.89it/s]

 82%|████████▏ | 82929/100629 [1:05:05<15:40, 18.81it/s]

 82%|████████▏ | 82932/100629 [1:05:05<14:48, 19.92it/s]

 82%|████████▏ | 82935/100629 [1:05:05<14:37, 20.17it/s]

 82%|████████▏ | 82938/100629 [1:05:06<14:58, 19.69it/s]

 82%|████████▏ | 82941/100629 [1:05:06<14:32, 20.28it/s]

 82%|████████▏ | 82944/100629 [1:05:06<14:22, 20.51it/s]

 82%|████████▏ | 82947/100629 [1:05:06<14:54, 19.77it/s]

 82%|████████▏ | 82950/100629 [1:05:06<15:05, 19.53it/s]

 82%|████████▏ | 82952/100629 [1:05:06<15:56, 18.49it/s]

 82%|████████▏ | 82954/100629 [1:05:07<16:35, 17.75it/s]

 82%|████████▏ | 82959/100629 [1:05:07<11:50, 24.88it/s]

 82%|████████▏ | 82962/100629 [1:05:07<14:38, 20.10it/s]

 82%|████████▏ | 82965/100629 [1:05:07<16:51, 17.46it/s]

 82%|████████▏ | 82967/100629 [1:05:07<17:20, 16.97it/s]

 82%|████████▏ | 82969/100629 [1:05:07<16:57, 17.35it/s]

 82%|████████▏ | 82971/100629 [1:05:07<18:24, 15.98it/s]

 82%|████████▏ | 82974/100629 [1:05:08<17:04, 17.23it/s]

 82%|████████▏ | 82976/100629 [1:05:08<18:23, 15.99it/s]

 82%|████████▏ | 82978/100629 [1:05:08<20:35, 14.29it/s]

 82%|████████▏ | 82981/100629 [1:05:08<17:15, 17.04it/s]

 82%|████████▏ | 82983/100629 [1:05:08<16:48, 17.50it/s]

 82%|████████▏ | 82987/100629 [1:05:08<13:27, 21.86it/s]

 82%|████████▏ | 82990/100629 [1:05:08<13:01, 22.56it/s]

 82%|████████▏ | 82994/100629 [1:05:09<11:03, 26.60it/s]

 82%|████████▏ | 82997/100629 [1:05:09<13:32, 21.71it/s]

 82%|████████▏ | 83000/100629 [1:05:09<13:40, 21.48it/s]

 82%|████████▏ | 83004/100629 [1:05:09<12:02, 24.40it/s]

 82%|████████▏ | 83007/100629 [1:05:09<13:02, 22.52it/s]

 82%|████████▏ | 83010/100629 [1:05:09<14:54, 19.69it/s]

 82%|████████▏ | 83013/100629 [1:05:10<15:43, 18.68it/s]

 82%|████████▏ | 83015/100629 [1:05:10<15:49, 18.56it/s]

 83%|████████▎ | 83019/100629 [1:05:10<13:30, 21.72it/s]

 83%|████████▎ | 83022/100629 [1:05:10<13:25, 21.86it/s]

 83%|████████▎ | 83025/100629 [1:05:10<12:27, 23.56it/s]

 83%|████████▎ | 83029/100629 [1:05:10<12:03, 24.33it/s]

 83%|████████▎ | 83032/100629 [1:05:10<12:06, 24.22it/s]

 83%|████████▎ | 83036/100629 [1:05:10<11:22, 25.78it/s]

 83%|████████▎ | 83040/100629 [1:05:11<11:31, 25.44it/s]

 83%|████████▎ | 83043/100629 [1:05:11<12:13, 23.97it/s]

 83%|████████▎ | 83046/100629 [1:05:11<12:36, 23.24it/s]

 83%|████████▎ | 83050/100629 [1:05:11<10:53, 26.89it/s]

 83%|████████▎ | 83053/100629 [1:05:11<11:55, 24.55it/s]

 83%|████████▎ | 83057/100629 [1:05:11<11:15, 26.02it/s]

 83%|████████▎ | 83061/100629 [1:05:11<10:22, 28.24it/s]

 83%|████████▎ | 83064/100629 [1:05:11<10:30, 27.86it/s]

 83%|████████▎ | 83067/100629 [1:05:12<10:27, 27.97it/s]

 83%|████████▎ | 83070/100629 [1:05:12<10:38, 27.50it/s]

 83%|████████▎ | 83074/100629 [1:05:12<10:57, 26.70it/s]

 83%|████████▎ | 83077/100629 [1:05:12<11:09, 26.22it/s]

 83%|████████▎ | 83080/100629 [1:05:12<11:05, 26.35it/s]

 83%|████████▎ | 83083/100629 [1:05:12<10:47, 27.08it/s]

 83%|████████▎ | 83087/100629 [1:05:12<12:27, 23.48it/s]

 83%|████████▎ | 83090/100629 [1:05:13<14:36, 20.01it/s]

 83%|████████▎ | 83093/100629 [1:05:13<14:29, 20.18it/s]

 83%|████████▎ | 83096/100629 [1:05:13<14:36, 19.99it/s]

 83%|████████▎ | 83099/100629 [1:05:13<15:43, 18.58it/s]

 83%|████████▎ | 83101/100629 [1:05:13<17:38, 16.56it/s]

 83%|████████▎ | 83103/100629 [1:05:13<17:44, 16.46it/s]

 83%|████████▎ | 83105/100629 [1:05:14<17:32, 16.65it/s]

 83%|████████▎ | 83108/100629 [1:05:14<14:53, 19.60it/s]

 83%|████████▎ | 83112/100629 [1:05:14<11:54, 24.52it/s]

 83%|████████▎ | 83115/100629 [1:05:14<15:07, 19.29it/s]

 83%|████████▎ | 83118/100629 [1:05:14<14:47, 19.73it/s]

 83%|████████▎ | 83121/100629 [1:05:14<13:37, 21.42it/s]

 83%|████████▎ | 83124/100629 [1:05:14<13:24, 21.77it/s]

 83%|████████▎ | 83127/100629 [1:05:15<13:52, 21.02it/s]

 83%|████████▎ | 83130/100629 [1:05:15<14:03, 20.74it/s]

 83%|████████▎ | 83134/100629 [1:05:15<11:45, 24.79it/s]

 83%|████████▎ | 83137/100629 [1:05:15<12:27, 23.41it/s]

 83%|████████▎ | 83140/100629 [1:05:15<15:04, 19.33it/s]

 83%|████████▎ | 83143/100629 [1:05:15<13:40, 21.31it/s]

 83%|████████▎ | 83146/100629 [1:05:15<13:46, 21.14it/s]

 83%|████████▎ | 83149/100629 [1:05:16<16:02, 18.16it/s]

 83%|████████▎ | 83151/100629 [1:05:16<18:28, 15.77it/s]

 83%|████████▎ | 83154/100629 [1:05:16<16:57, 17.17it/s]

 83%|████████▎ | 83157/100629 [1:05:16<16:33, 17.58it/s]

 83%|████████▎ | 83161/100629 [1:05:16<13:12, 22.03it/s]

 83%|████████▎ | 83165/100629 [1:05:16<11:58, 24.30it/s]

 83%|████████▎ | 83168/100629 [1:05:17<13:48, 21.07it/s]

 83%|████████▎ | 83171/100629 [1:05:17<13:57, 20.85it/s]

 83%|████████▎ | 83174/100629 [1:05:17<14:23, 20.21it/s]

 83%|████████▎ | 83177/100629 [1:05:17<13:12, 22.01it/s]

 83%|████████▎ | 83182/100629 [1:05:17<11:02, 26.35it/s]

 83%|████████▎ | 83185/100629 [1:05:17<11:10, 26.03it/s]

 83%|████████▎ | 83188/100629 [1:05:17<12:56, 22.47it/s]

 83%|████████▎ | 83191/100629 [1:05:18<14:01, 20.73it/s]

 83%|████████▎ | 83195/100629 [1:05:18<12:00, 24.21it/s]

 83%|████████▎ | 83198/100629 [1:05:18<11:50, 24.53it/s]

 83%|████████▎ | 83202/100629 [1:05:18<10:33, 27.52it/s]

 83%|████████▎ | 83205/100629 [1:05:18<11:06, 26.13it/s]

 83%|████████▎ | 83208/100629 [1:05:18<11:23, 25.48it/s]

 83%|████████▎ | 83211/100629 [1:05:18<11:16, 25.76it/s]

 83%|████████▎ | 83214/100629 [1:05:18<12:22, 23.44it/s]

 83%|████████▎ | 83217/100629 [1:05:19<14:26, 20.09it/s]

 83%|████████▎ | 83220/100629 [1:05:19<14:34, 19.92it/s]

 83%|████████▎ | 83223/100629 [1:05:19<13:07, 22.10it/s]

 83%|████████▎ | 83226/100629 [1:05:19<12:33, 23.11it/s]

 83%|████████▎ | 83230/100629 [1:05:19<11:38, 24.91it/s]

 83%|████████▎ | 83233/100629 [1:05:19<13:14, 21.89it/s]

 83%|████████▎ | 83236/100629 [1:05:19<12:56, 22.41it/s]

 83%|████████▎ | 83241/100629 [1:05:20<11:24, 25.40it/s]

 83%|████████▎ | 83244/100629 [1:05:20<12:30, 23.15it/s]

 83%|████████▎ | 83247/100629 [1:05:20<13:20, 21.72it/s]

 83%|████████▎ | 83251/100629 [1:05:20<12:47, 22.65it/s]

 83%|████████▎ | 83255/100629 [1:05:20<11:46, 24.59it/s]

 83%|████████▎ | 83260/100629 [1:05:20<10:26, 27.71it/s]

 83%|████████▎ | 83263/100629 [1:05:20<10:53, 26.58it/s]

 83%|████████▎ | 83266/100629 [1:05:21<11:39, 24.83it/s]

 83%|████████▎ | 83269/100629 [1:05:21<12:52, 22.47it/s]

 83%|████████▎ | 83272/100629 [1:05:21<12:35, 22.98it/s]

 83%|████████▎ | 83275/100629 [1:05:21<12:01, 24.07it/s]

 83%|████████▎ | 83278/100629 [1:05:21<11:38, 24.84it/s]

 83%|████████▎ | 83281/100629 [1:05:21<12:39, 22.84it/s]

 83%|████████▎ | 83284/100629 [1:05:21<12:01, 24.03it/s]

 83%|████████▎ | 83287/100629 [1:05:22<13:59, 20.65it/s]

 83%|████████▎ | 83290/100629 [1:05:22<14:26, 20.02it/s]

 83%|████████▎ | 83294/100629 [1:05:22<12:31, 23.07it/s]

 83%|████████▎ | 83297/100629 [1:05:22<13:28, 21.44it/s]

 83%|████████▎ | 83301/100629 [1:05:22<12:07, 23.83it/s]

 83%|████████▎ | 83304/100629 [1:05:22<11:42, 24.67it/s]

 83%|████████▎ | 83307/100629 [1:05:22<12:00, 24.04it/s]

 83%|████████▎ | 83310/100629 [1:05:23<14:22, 20.08it/s]

 83%|████████▎ | 83313/100629 [1:05:23<14:06, 20.46it/s]

 83%|████████▎ | 83316/100629 [1:05:23<14:28, 19.92it/s]

 83%|████████▎ | 83319/100629 [1:05:23<13:06, 22.00it/s]

 83%|████████▎ | 83322/100629 [1:05:23<12:12, 23.63it/s]

 83%|████████▎ | 83325/100629 [1:05:23<11:41, 24.66it/s]

 83%|████████▎ | 83328/100629 [1:05:23<11:25, 25.23it/s]

 83%|████████▎ | 83331/100629 [1:05:23<10:55, 26.40it/s]

 83%|████████▎ | 83334/100629 [1:05:24<12:27, 23.13it/s]

 83%|████████▎ | 83337/100629 [1:05:24<12:43, 22.66it/s]

 83%|████████▎ | 83340/100629 [1:05:24<19:45, 14.59it/s]

 83%|████████▎ | 83344/100629 [1:05:24<16:05, 17.91it/s]

 83%|████████▎ | 83347/100629 [1:05:24<15:11, 18.96it/s]

 83%|████████▎ | 83350/100629 [1:05:25<14:12, 20.27it/s]

 83%|████████▎ | 83353/100629 [1:05:25<14:58, 19.22it/s]

 83%|████████▎ | 83356/100629 [1:05:25<13:50, 20.80it/s]

 83%|████████▎ | 83359/100629 [1:05:25<13:13, 21.76it/s]

 83%|████████▎ | 83362/100629 [1:05:25<12:56, 22.24it/s]

 83%|████████▎ | 83365/100629 [1:05:25<12:57, 22.21it/s]

 83%|████████▎ | 83368/100629 [1:05:25<13:01, 22.10it/s]

 83%|████████▎ | 83371/100629 [1:05:26<15:31, 18.54it/s]

 83%|████████▎ | 83373/100629 [1:05:26<15:47, 18.22it/s]

 83%|████████▎ | 83375/100629 [1:05:26<21:44, 13.22it/s]

 83%|████████▎ | 83379/100629 [1:05:26<15:53, 18.10it/s]

 83%|████████▎ | 83382/100629 [1:05:26<15:59, 17.98it/s]

 83%|████████▎ | 83385/100629 [1:05:27<20:07, 14.28it/s]

 83%|████████▎ | 83387/100629 [1:05:27<19:48, 14.51it/s]

 83%|████████▎ | 83391/100629 [1:05:27<16:14, 17.69it/s]

 83%|████████▎ | 83393/100629 [1:05:27<16:47, 17.11it/s]

 83%|████████▎ | 83397/100629 [1:05:27<14:16, 20.13it/s]

 83%|████████▎ | 83401/100629 [1:05:27<13:47, 20.81it/s]

 83%|████████▎ | 83404/100629 [1:05:28<15:48, 18.16it/s]

 83%|████████▎ | 83406/100629 [1:05:28<15:40, 18.32it/s]

 83%|████████▎ | 83409/100629 [1:05:28<13:47, 20.80it/s]

 83%|████████▎ | 83412/100629 [1:05:28<14:37, 19.61it/s]

 83%|████████▎ | 83415/100629 [1:05:28<14:34, 19.68it/s]

 83%|████████▎ | 83418/100629 [1:05:28<14:22, 19.94it/s]

 83%|████████▎ | 83421/100629 [1:05:28<13:30, 21.23it/s]

 83%|████████▎ | 83425/100629 [1:05:28<12:05, 23.71it/s]

 83%|████████▎ | 83430/100629 [1:05:29<10:49, 26.48it/s]

 83%|████████▎ | 83435/100629 [1:05:29<10:24, 27.55it/s]

 83%|████████▎ | 83438/100629 [1:05:29<10:31, 27.21it/s]

 83%|████████▎ | 83441/100629 [1:05:29<11:42, 24.47it/s]

 83%|████████▎ | 83444/100629 [1:05:29<11:50, 24.17it/s]

 83%|████████▎ | 83447/100629 [1:05:29<14:19, 20.00it/s]

 83%|████████▎ | 83450/100629 [1:05:30<14:20, 19.96it/s]

 83%|████████▎ | 83453/100629 [1:05:30<13:14, 21.61it/s]

 83%|████████▎ | 83456/100629 [1:05:30<12:15, 23.35it/s]

 83%|████████▎ | 83459/100629 [1:05:30<12:18, 23.25it/s]

 83%|████████▎ | 83462/100629 [1:05:30<14:18, 20.00it/s]

 83%|████████▎ | 83465/100629 [1:05:30<14:27, 19.80it/s]

 83%|████████▎ | 83468/100629 [1:05:30<13:25, 21.31it/s]

 83%|████████▎ | 83472/100629 [1:05:30<11:14, 25.42it/s]

 83%|████████▎ | 83476/100629 [1:05:31<10:05, 28.31it/s]

 83%|████████▎ | 83479/100629 [1:05:31<11:21, 25.17it/s]

 83%|████████▎ | 83482/100629 [1:05:31<12:26, 22.96it/s]

 83%|████████▎ | 83485/100629 [1:05:31<13:48, 20.70it/s]

 83%|████████▎ | 83489/100629 [1:05:31<12:12, 23.38it/s]

 83%|████████▎ | 83492/100629 [1:05:31<12:17, 23.25it/s]

 83%|████████▎ | 83496/100629 [1:05:31<11:02, 25.87it/s]

 83%|████████▎ | 83499/100629 [1:05:32<11:07, 25.67it/s]

 83%|████████▎ | 83502/100629 [1:05:32<10:51, 26.30it/s]

 83%|████████▎ | 83505/100629 [1:05:32<10:29, 27.20it/s]

 83%|████████▎ | 83508/100629 [1:05:32<13:10, 21.65it/s]

 83%|████████▎ | 83511/100629 [1:05:32<14:31, 19.65it/s]

 83%|████████▎ | 83515/100629 [1:05:32<12:36, 22.63it/s]

 83%|████████▎ | 83519/100629 [1:05:32<11:43, 24.33it/s]

 83%|████████▎ | 83522/100629 [1:05:33<11:09, 25.54it/s]

 83%|████████▎ | 83525/100629 [1:05:33<12:00, 23.73it/s]

 83%|████████▎ | 83528/100629 [1:05:33<11:34, 24.61it/s]

 83%|████████▎ | 83531/100629 [1:05:33<15:20, 18.57it/s]

 83%|████████▎ | 83534/100629 [1:05:33<14:17, 19.93it/s]

 83%|████████▎ | 83538/100629 [1:05:33<12:59, 21.92it/s]

 83%|████████▎ | 83541/100629 [1:05:33<12:09, 23.44it/s]

 83%|████████▎ | 83544/100629 [1:05:34<15:23, 18.49it/s]

 83%|████████▎ | 83547/100629 [1:05:34<15:49, 18.00it/s]

 83%|████████▎ | 83550/100629 [1:05:34<15:09, 18.78it/s]

 83%|████████▎ | 83553/100629 [1:05:34<14:30, 19.61it/s]

 83%|████████▎ | 83556/100629 [1:05:34<14:13, 19.99it/s]

 83%|████████▎ | 83559/100629 [1:05:34<14:01, 20.28it/s]

 83%|████████▎ | 83562/100629 [1:05:35<13:12, 21.54it/s]

 83%|████████▎ | 83565/100629 [1:05:35<13:26, 21.15it/s]

 83%|████████▎ | 83568/100629 [1:05:35<12:21, 23.00it/s]

 83%|████████▎ | 83571/100629 [1:05:35<12:03, 23.56it/s]

 83%|████████▎ | 83574/100629 [1:05:35<13:37, 20.86it/s]

 83%|████████▎ | 83579/100629 [1:05:35<10:36, 26.77it/s]

 83%|████████▎ | 83582/100629 [1:05:35<12:31, 22.67it/s]

 83%|████████▎ | 83585/100629 [1:05:36<14:22, 19.77it/s]

 83%|████████▎ | 83588/100629 [1:05:36<14:18, 19.86it/s]

 83%|████████▎ | 83591/100629 [1:05:36<13:01, 21.81it/s]

 83%|████████▎ | 83594/100629 [1:05:36<12:00, 23.65it/s]

 83%|████████▎ | 83597/100629 [1:05:36<12:11, 23.28it/s]

 83%|████████▎ | 83600/100629 [1:05:36<13:27, 21.09it/s]

 83%|████████▎ | 83603/100629 [1:05:37<17:17, 16.41it/s]

 83%|████████▎ | 83606/100629 [1:05:37<15:25, 18.40it/s]

 83%|████████▎ | 83609/100629 [1:05:37<17:58, 15.78it/s]

 83%|████████▎ | 83611/100629 [1:05:37<22:09, 12.80it/s]

 83%|████████▎ | 83613/100629 [1:05:37<20:39, 13.73it/s]

 83%|████████▎ | 83615/100629 [1:05:37<19:04, 14.87it/s]

 83%|████████▎ | 83617/100629 [1:05:38<19:04, 14.86it/s]

 83%|████████▎ | 83619/100629 [1:05:38<18:29, 15.33it/s]

 83%|████████▎ | 83621/100629 [1:05:38<17:48, 15.92it/s]

 83%|████████▎ | 83623/100629 [1:05:38<17:36, 16.10it/s]

 83%|████████▎ | 83625/100629 [1:05:38<17:46, 15.94it/s]

 83%|████████▎ | 83627/100629 [1:05:38<19:54, 14.23it/s]

 83%|████████▎ | 83629/100629 [1:05:38<19:20, 14.65it/s]

 83%|████████▎ | 83631/100629 [1:05:38<18:14, 15.52it/s]

 83%|████████▎ | 83634/100629 [1:05:39<15:25, 18.36it/s]

 83%|████████▎ | 83637/100629 [1:05:39<14:16, 19.85it/s]

 83%|████████▎ | 83640/100629 [1:05:39<14:25, 19.63it/s]

 83%|████████▎ | 83642/100629 [1:05:39<16:30, 17.16it/s]

 83%|████████▎ | 83644/100629 [1:05:39<16:28, 17.18it/s]

 83%|████████▎ | 83647/100629 [1:05:39<16:00, 17.67it/s]

 83%|████████▎ | 83649/100629 [1:05:39<18:24, 15.38it/s]

 83%|████████▎ | 83651/100629 [1:05:40<23:13, 12.19it/s]

 83%|████████▎ | 83655/100629 [1:05:40<17:11, 16.45it/s]

 83%|████████▎ | 83657/100629 [1:05:40<17:04, 16.57it/s]

 83%|████████▎ | 83660/100629 [1:05:40<14:31, 19.48it/s]

 83%|████████▎ | 83663/100629 [1:05:40<17:45, 15.92it/s]

 83%|████████▎ | 83666/100629 [1:05:40<15:55, 17.76it/s]

 83%|████████▎ | 83669/100629 [1:05:41<15:08, 18.67it/s]

 83%|████████▎ | 83673/100629 [1:05:41<14:40, 19.26it/s]

 83%|████████▎ | 83676/100629 [1:05:41<14:08, 19.97it/s]

 83%|████████▎ | 83680/100629 [1:05:41<11:39, 24.24it/s]

 83%|████████▎ | 83683/100629 [1:05:41<11:39, 24.21it/s]

 83%|████████▎ | 83688/100629 [1:05:41<09:44, 29.00it/s]

 83%|████████▎ | 83692/100629 [1:05:41<10:56, 25.82it/s]

 83%|████████▎ | 83695/100629 [1:05:42<10:41, 26.41it/s]

 83%|████████▎ | 83699/100629 [1:05:42<10:53, 25.93it/s]

 83%|████████▎ | 83702/100629 [1:05:42<11:59, 23.54it/s]

 83%|████████▎ | 83705/100629 [1:05:42<11:31, 24.49it/s]

 83%|████████▎ | 83708/100629 [1:05:42<12:39, 22.27it/s]

 83%|████████▎ | 83711/100629 [1:05:42<12:42, 22.20it/s]

 83%|████████▎ | 83715/100629 [1:05:42<11:39, 24.18it/s]

 83%|████████▎ | 83718/100629 [1:05:43<12:33, 22.44it/s]

 83%|████████▎ | 83722/100629 [1:05:43<12:38, 22.28it/s]

 83%|████████▎ | 83725/100629 [1:05:43<13:44, 20.51it/s]

 83%|████████▎ | 83728/100629 [1:05:43<14:13, 19.80it/s]

 83%|████████▎ | 83731/100629 [1:05:43<14:45, 19.09it/s]

 83%|████████▎ | 83734/100629 [1:05:43<13:26, 20.96it/s]

 83%|████████▎ | 83737/100629 [1:05:44<17:00, 16.55it/s]

 83%|████████▎ | 83741/100629 [1:05:44<13:52, 20.29it/s]

 83%|████████▎ | 83745/100629 [1:05:44<11:56, 23.56it/s]

 83%|████████▎ | 83748/100629 [1:05:44<12:55, 21.76it/s]

 83%|████████▎ | 83751/100629 [1:05:44<12:59, 21.64it/s]

 83%|████████▎ | 83754/100629 [1:05:44<14:03, 20.00it/s]

 83%|████████▎ | 83757/100629 [1:05:45<14:11, 19.82it/s]

 83%|████████▎ | 83760/100629 [1:05:45<15:04, 18.64it/s]

 83%|████████▎ | 83763/100629 [1:05:45<14:45, 19.04it/s]

 83%|████████▎ | 83765/100629 [1:05:45<15:17, 18.38it/s]

 83%|████████▎ | 83770/100629 [1:05:45<12:46, 22.00it/s]

 83%|████████▎ | 83773/100629 [1:05:45<14:31, 19.33it/s]

 83%|████████▎ | 83775/100629 [1:05:45<14:56, 18.79it/s]

 83%|████████▎ | 83777/100629 [1:05:46<17:23, 16.14it/s]

 83%|████████▎ | 83780/100629 [1:05:46<16:15, 17.28it/s]

 83%|████████▎ | 83782/100629 [1:05:46<16:31, 16.99it/s]

 83%|████████▎ | 83785/100629 [1:05:46<15:36, 17.98it/s]

 83%|████████▎ | 83789/100629 [1:05:46<13:34, 20.68it/s]

 83%|████████▎ | 83792/100629 [1:05:46<14:15, 19.69it/s]

 83%|████████▎ | 83795/100629 [1:05:47<13:39, 20.53it/s]

 83%|████████▎ | 83798/100629 [1:05:47<15:37, 17.95it/s]

 83%|████████▎ | 83800/100629 [1:05:47<16:17, 17.22it/s]

 83%|████████▎ | 83804/100629 [1:05:47<13:23, 20.94it/s]

 83%|████████▎ | 83807/100629 [1:05:47<13:50, 20.26it/s]

 83%|████████▎ | 83811/100629 [1:05:47<12:49, 21.86it/s]

 83%|████████▎ | 83814/100629 [1:05:47<12:29, 22.45it/s]

 83%|████████▎ | 83817/100629 [1:05:48<14:38, 19.15it/s]

 83%|████████▎ | 83821/100629 [1:05:48<12:45, 21.96it/s]

 83%|████████▎ | 83824/100629 [1:05:48<16:21, 17.12it/s]

 83%|████████▎ | 83828/100629 [1:05:48<13:40, 20.47it/s]

 83%|████████▎ | 83831/100629 [1:05:48<13:21, 20.97it/s]

 83%|████████▎ | 83835/100629 [1:05:48<12:05, 23.14it/s]

 83%|████████▎ | 83838/100629 [1:05:49<12:00, 23.31it/s]

 83%|████████▎ | 83842/100629 [1:05:49<11:20, 24.68it/s]

 83%|████████▎ | 83846/100629 [1:05:49<10:16, 27.22it/s]

 83%|████████▎ | 83849/100629 [1:05:49<11:39, 23.99it/s]

 83%|████████▎ | 83852/100629 [1:05:49<11:47, 23.72it/s]

 83%|████████▎ | 83855/100629 [1:05:49<12:28, 22.40it/s]

 83%|████████▎ | 83858/100629 [1:05:49<13:03, 21.42it/s]

 83%|████████▎ | 83861/100629 [1:05:50<12:04, 23.16it/s]

 83%|████████▎ | 83864/100629 [1:05:50<11:34, 24.13it/s]

 83%|████████▎ | 83867/100629 [1:05:50<11:45, 23.77it/s]

 83%|████████▎ | 83870/100629 [1:05:50<11:13, 24.88it/s]

 83%|████████▎ | 83874/100629 [1:05:50<09:42, 28.76it/s]

 83%|████████▎ | 83877/100629 [1:05:50<11:22, 24.54it/s]

 83%|████████▎ | 83881/100629 [1:05:50<10:16, 27.18it/s]

 83%|████████▎ | 83884/100629 [1:05:51<14:14, 19.59it/s]

 83%|████████▎ | 83887/100629 [1:05:51<13:46, 20.25it/s]

 83%|████████▎ | 83890/100629 [1:05:51<14:06, 19.77it/s]

 83%|████████▎ | 83893/100629 [1:05:51<13:01, 21.43it/s]

 83%|████████▎ | 83896/100629 [1:05:51<12:59, 21.47it/s]

 83%|████████▎ | 83899/100629 [1:05:51<14:24, 19.35it/s]

 83%|████████▎ | 83902/100629 [1:05:51<13:56, 19.99it/s]

 83%|████████▎ | 83905/100629 [1:05:52<12:59, 21.45it/s]

 83%|████████▎ | 83908/100629 [1:05:52<13:42, 20.32it/s]

 83%|████████▎ | 83911/100629 [1:05:52<14:50, 18.77it/s]

 83%|████████▎ | 83913/100629 [1:05:52<14:58, 18.61it/s]

 83%|████████▎ | 83915/100629 [1:05:52<15:16, 18.24it/s]

 83%|████████▎ | 83917/100629 [1:05:52<15:41, 17.75it/s]

 83%|████████▎ | 83921/100629 [1:05:52<12:18, 22.61it/s]

 83%|████████▎ | 83924/100629 [1:05:53<13:20, 20.86it/s]

 83%|████████▎ | 83927/100629 [1:05:53<13:21, 20.84it/s]

 83%|████████▎ | 83930/100629 [1:05:53<12:13, 22.78it/s]

 83%|████████▎ | 83933/100629 [1:05:53<12:50, 21.67it/s]

 83%|████████▎ | 83937/100629 [1:05:53<12:32, 22.19it/s]

 83%|████████▎ | 83940/100629 [1:05:53<12:56, 21.49it/s]

 83%|████████▎ | 83944/100629 [1:05:54<15:43, 17.68it/s]

 83%|████████▎ | 83946/100629 [1:05:54<15:53, 17.50it/s]

 83%|████████▎ | 83949/100629 [1:05:54<15:07, 18.37it/s]

 83%|████████▎ | 83952/100629 [1:05:54<13:30, 20.58it/s]

 83%|████████▎ | 83956/100629 [1:05:54<11:34, 24.00it/s]

 83%|████████▎ | 83959/100629 [1:05:54<13:49, 20.09it/s]

 83%|████████▎ | 83963/100629 [1:05:54<11:28, 24.21it/s]

 83%|████████▎ | 83967/100629 [1:05:54<10:00, 27.76it/s]

 83%|████████▎ | 83971/100629 [1:05:55<10:16, 27.04it/s]

 83%|████████▎ | 83975/100629 [1:05:55<09:14, 30.06it/s]

 83%|████████▎ | 83979/100629 [1:05:55<08:50, 31.40it/s]

 83%|████████▎ | 83983/100629 [1:05:55<09:13, 30.05it/s]

 83%|████████▎ | 83987/100629 [1:05:55<09:12, 30.14it/s]

 83%|████████▎ | 83991/100629 [1:05:55<08:56, 31.02it/s]

 83%|████████▎ | 83995/100629 [1:05:55<10:39, 26.02it/s]

 83%|████████▎ | 83998/100629 [1:05:56<10:41, 25.92it/s]

 83%|████████▎ | 84001/100629 [1:05:56<11:51, 23.37it/s]

 83%|████████▎ | 84005/100629 [1:05:56<12:10, 22.77it/s]

 83%|████████▎ | 84009/100629 [1:05:56<10:45, 25.75it/s]

 83%|████████▎ | 84012/100629 [1:05:56<10:42, 25.86it/s]

 83%|████████▎ | 84015/100629 [1:05:56<10:24, 26.59it/s]

 83%|████████▎ | 84019/100629 [1:05:56<10:06, 27.38it/s]

 83%|████████▎ | 84022/100629 [1:05:57<10:42, 25.84it/s]

 83%|████████▎ | 84025/100629 [1:05:57<12:42, 21.79it/s]

 84%|████████▎ | 84028/100629 [1:05:57<13:32, 20.44it/s]

 84%|████████▎ | 84032/100629 [1:05:57<11:47, 23.44it/s]

 84%|████████▎ | 84036/100629 [1:05:57<10:20, 26.73it/s]

 84%|████████▎ | 84039/100629 [1:05:57<10:30, 26.32it/s]

 84%|████████▎ | 84043/100629 [1:05:57<09:52, 27.97it/s]

 84%|████████▎ | 84046/100629 [1:05:57<10:08, 27.24it/s]

 84%|████████▎ | 84049/100629 [1:05:58<11:43, 23.56it/s]

 84%|████████▎ | 84052/100629 [1:05:58<11:05, 24.90it/s]

 84%|████████▎ | 84055/100629 [1:05:58<12:49, 21.54it/s]

 84%|████████▎ | 84058/100629 [1:05:58<12:15, 22.53it/s]

 84%|████████▎ | 84063/100629 [1:05:58<10:19, 26.76it/s]

 84%|████████▎ | 84066/100629 [1:05:58<13:33, 20.37it/s]

 84%|████████▎ | 84069/100629 [1:05:59<15:08, 18.24it/s]

 84%|████████▎ | 84072/100629 [1:05:59<13:38, 20.24it/s]

 84%|████████▎ | 84075/100629 [1:05:59<12:38, 21.83it/s]

 84%|████████▎ | 84078/100629 [1:05:59<11:48, 23.37it/s]

 84%|████████▎ | 84081/100629 [1:05:59<11:34, 23.81it/s]

 84%|████████▎ | 84086/100629 [1:05:59<09:48, 28.10it/s]

 84%|████████▎ | 84090/100629 [1:05:59<09:06, 30.24it/s]

 84%|████████▎ | 84094/100629 [1:06:00<10:28, 26.31it/s]

 84%|████████▎ | 84100/100629 [1:06:00<08:52, 31.04it/s]

 84%|████████▎ | 84104/100629 [1:06:00<11:19, 24.31it/s]

 84%|████████▎ | 84107/100629 [1:06:00<11:29, 23.97it/s]

 84%|████████▎ | 84111/100629 [1:06:00<11:05, 24.82it/s]

 84%|████████▎ | 84114/100629 [1:06:00<12:07, 22.71it/s]

 84%|████████▎ | 84117/100629 [1:06:00<11:26, 24.04it/s]

 84%|████████▎ | 84120/100629 [1:06:01<10:56, 25.16it/s]

 84%|████████▎ | 84123/100629 [1:06:01<13:28, 20.43it/s]

 84%|████████▎ | 84126/100629 [1:06:01<12:42, 21.64it/s]

 84%|████████▎ | 84129/100629 [1:06:01<12:54, 21.31it/s]

 84%|████████▎ | 84134/100629 [1:06:01<10:49, 25.39it/s]

 84%|████████▎ | 84137/100629 [1:06:01<11:43, 23.45it/s]

 84%|████████▎ | 84140/100629 [1:06:02<12:08, 22.62it/s]

 84%|████████▎ | 84143/100629 [1:06:02<13:00, 21.12it/s]

 84%|████████▎ | 84147/100629 [1:06:02<12:14, 22.45it/s]

 84%|████████▎ | 84150/100629 [1:06:02<13:12, 20.80it/s]

 84%|████████▎ | 84153/100629 [1:06:02<12:42, 21.62it/s]

 84%|████████▎ | 84156/100629 [1:06:02<11:53, 23.10it/s]

 84%|████████▎ | 84159/100629 [1:06:02<12:26, 22.07it/s]

 84%|████████▎ | 84162/100629 [1:06:03<13:47, 19.90it/s]

 84%|████████▎ | 84165/100629 [1:06:03<15:18, 17.93it/s]

 84%|████████▎ | 84167/100629 [1:06:03<15:36, 17.57it/s]

 84%|████████▎ | 84172/100629 [1:06:03<11:35, 23.65it/s]

 84%|████████▎ | 84175/100629 [1:06:03<11:03, 24.81it/s]

 84%|████████▎ | 84178/100629 [1:06:03<11:11, 24.50it/s]

 84%|████████▎ | 84181/100629 [1:06:03<12:26, 22.03it/s]

 84%|████████▎ | 84184/100629 [1:06:04<13:40, 20.03it/s]

 84%|████████▎ | 84188/100629 [1:06:04<12:12, 22.46it/s]

 84%|████████▎ | 84191/100629 [1:06:04<12:20, 22.21it/s]

 84%|████████▎ | 84194/100629 [1:06:04<14:34, 18.80it/s]

 84%|████████▎ | 84197/100629 [1:06:04<14:12, 19.26it/s]

 84%|████████▎ | 84200/100629 [1:06:05<16:50, 16.25it/s]

 84%|████████▎ | 84204/100629 [1:06:05<14:36, 18.75it/s]

 84%|████████▎ | 84208/100629 [1:06:05<12:53, 21.24it/s]

 84%|████████▎ | 84211/100629 [1:06:05<14:17, 19.15it/s]

 84%|████████▎ | 84214/100629 [1:06:05<14:21, 19.06it/s]

 84%|████████▎ | 84217/100629 [1:06:05<14:13, 19.22it/s]

 84%|████████▎ | 84220/100629 [1:06:05<13:09, 20.78it/s]

 84%|████████▎ | 84224/100629 [1:06:06<11:22, 24.05it/s]

 84%|████████▎ | 84227/100629 [1:06:06<11:51, 23.06it/s]

 84%|████████▎ | 84231/100629 [1:06:06<10:23, 26.32it/s]

 84%|████████▎ | 84234/100629 [1:06:06<11:32, 23.69it/s]

 84%|████████▎ | 84238/100629 [1:06:06<11:28, 23.79it/s]

 84%|████████▎ | 84242/100629 [1:06:06<10:35, 25.79it/s]

 84%|████████▎ | 84247/100629 [1:06:06<09:31, 28.67it/s]

 84%|████████▎ | 84250/100629 [1:06:07<09:29, 28.77it/s]

 84%|████████▎ | 84253/100629 [1:06:07<12:20, 22.10it/s]

 84%|████████▎ | 84256/100629 [1:06:07<11:51, 23.02it/s]

 84%|████████▎ | 84259/100629 [1:06:07<11:59, 22.75it/s]

 84%|████████▎ | 84262/100629 [1:06:07<12:40, 21.52it/s]

 84%|████████▎ | 84265/100629 [1:06:07<11:58, 22.78it/s]

 84%|████████▎ | 84268/100629 [1:06:07<11:48, 23.08it/s]

 84%|████████▎ | 84271/100629 [1:06:08<13:32, 20.13it/s]

 84%|████████▎ | 84274/100629 [1:06:08<15:21, 17.75it/s]

 84%|████████▍ | 84277/100629 [1:06:08<15:02, 18.11it/s]

 84%|████████▍ | 84279/100629 [1:06:08<14:46, 18.45it/s]

 84%|████████▍ | 84281/100629 [1:06:08<15:36, 17.45it/s]

 84%|████████▍ | 84285/100629 [1:06:08<12:59, 20.97it/s]

 84%|████████▍ | 84288/100629 [1:06:08<12:55, 21.07it/s]

 84%|████████▍ | 84291/100629 [1:06:09<12:27, 21.86it/s]

 84%|████████▍ | 84295/100629 [1:06:09<11:00, 24.72it/s]

 84%|████████▍ | 84298/100629 [1:06:09<10:36, 25.64it/s]

 84%|████████▍ | 84301/100629 [1:06:09<10:15, 26.54it/s]

 84%|████████▍ | 84304/100629 [1:06:09<12:28, 21.82it/s]

 84%|████████▍ | 84307/100629 [1:06:09<13:09, 20.67it/s]

 84%|████████▍ | 84310/100629 [1:06:09<13:17, 20.47it/s]

 84%|████████▍ | 84313/100629 [1:06:10<12:33, 21.66it/s]

 84%|████████▍ | 84316/100629 [1:06:10<15:02, 18.07it/s]

 84%|████████▍ | 84319/100629 [1:06:10<13:29, 20.15it/s]

 84%|████████▍ | 84322/100629 [1:06:10<12:57, 20.97it/s]

 84%|████████▍ | 84325/100629 [1:06:10<12:31, 21.69it/s]

 84%|████████▍ | 84328/100629 [1:06:10<13:25, 20.23it/s]

 84%|████████▍ | 84331/100629 [1:06:11<14:58, 18.14it/s]

 84%|████████▍ | 84334/100629 [1:06:11<13:47, 19.69it/s]

 84%|████████▍ | 84337/100629 [1:06:11<14:37, 18.57it/s]

 84%|████████▍ | 84340/100629 [1:06:11<15:06, 17.96it/s]

 84%|████████▍ | 84343/100629 [1:06:11<13:28, 20.15it/s]

 84%|████████▍ | 84346/100629 [1:06:11<15:34, 17.42it/s]

 84%|████████▍ | 84349/100629 [1:06:11<14:06, 19.24it/s]

 84%|████████▍ | 84352/100629 [1:06:12<13:06, 20.69it/s]

 84%|████████▍ | 84355/100629 [1:06:12<12:09, 22.30it/s]

 84%|████████▍ | 84358/100629 [1:06:12<11:53, 22.79it/s]

 84%|████████▍ | 84361/100629 [1:06:12<12:25, 21.81it/s]

 84%|████████▍ | 84364/100629 [1:06:12<11:29, 23.57it/s]

 84%|████████▍ | 84367/100629 [1:06:12<11:03, 24.50it/s]

 84%|████████▍ | 84370/100629 [1:06:12<11:34, 23.43it/s]

 84%|████████▍ | 84373/100629 [1:06:12<11:46, 23.02it/s]

 84%|████████▍ | 84376/100629 [1:06:13<12:13, 22.17it/s]

 84%|████████▍ | 84379/100629 [1:06:13<14:21, 18.86it/s]

 84%|████████▍ | 84383/100629 [1:06:13<12:15, 22.10it/s]

 84%|████████▍ | 84386/100629 [1:06:13<12:56, 20.93it/s]

 84%|████████▍ | 84391/100629 [1:06:13<10:21, 26.13it/s]

 84%|████████▍ | 84394/100629 [1:06:13<10:22, 26.08it/s]

 84%|████████▍ | 84397/100629 [1:06:13<10:59, 24.63it/s]

 84%|████████▍ | 84401/100629 [1:06:14<10:14, 26.42it/s]

 84%|████████▍ | 84404/100629 [1:06:14<10:59, 24.59it/s]

 84%|████████▍ | 84407/100629 [1:06:14<14:39, 18.44it/s]

 84%|████████▍ | 84410/100629 [1:06:14<13:50, 19.53it/s]

 84%|████████▍ | 84413/100629 [1:06:14<14:13, 19.00it/s]

 84%|████████▍ | 84416/100629 [1:06:14<13:46, 19.62it/s]

 84%|████████▍ | 84419/100629 [1:06:15<14:11, 19.04it/s]

 84%|████████▍ | 84422/100629 [1:06:15<14:56, 18.07it/s]

 84%|████████▍ | 84426/100629 [1:06:15<12:16, 21.99it/s]

 84%|████████▍ | 84429/100629 [1:06:15<11:43, 23.03it/s]

 84%|████████▍ | 84432/100629 [1:06:15<12:28, 21.64it/s]

 84%|████████▍ | 84435/100629 [1:06:15<13:41, 19.71it/s]

 84%|████████▍ | 84438/100629 [1:06:16<13:14, 20.37it/s]

 84%|████████▍ | 84441/100629 [1:06:16<13:42, 19.68it/s]

 84%|████████▍ | 84444/100629 [1:06:16<13:48, 19.53it/s]

 84%|████████▍ | 84446/100629 [1:06:16<15:26, 17.47it/s]

 84%|████████▍ | 84448/100629 [1:06:16<15:14, 17.69it/s]

 84%|████████▍ | 84451/100629 [1:06:16<14:13, 18.95it/s]

 84%|████████▍ | 84455/100629 [1:06:16<12:37, 21.37it/s]

 84%|████████▍ | 84458/100629 [1:06:17<13:22, 20.14it/s]

 84%|████████▍ | 84462/100629 [1:06:17<12:05, 22.29it/s]

 84%|████████▍ | 84465/100629 [1:06:17<13:35, 19.81it/s]

 84%|████████▍ | 84468/100629 [1:06:17<14:51, 18.13it/s]

 84%|████████▍ | 84471/100629 [1:06:17<14:24, 18.69it/s]

 84%|████████▍ | 84474/100629 [1:06:17<13:04, 20.60it/s]

 84%|████████▍ | 84477/100629 [1:06:17<12:19, 21.84it/s]

 84%|████████▍ | 84480/100629 [1:06:18<13:15, 20.30it/s]

 84%|████████▍ | 84483/100629 [1:06:18<12:11, 22.08it/s]

 84%|████████▍ | 84486/100629 [1:06:18<12:22, 21.75it/s]

 84%|████████▍ | 84489/100629 [1:06:18<14:31, 18.52it/s]

 84%|████████▍ | 84492/100629 [1:06:18<13:03, 20.58it/s]

 84%|████████▍ | 84497/100629 [1:06:18<11:19, 23.74it/s]

 84%|████████▍ | 84501/100629 [1:06:19<10:20, 26.00it/s]

 84%|████████▍ | 84505/100629 [1:06:19<10:33, 25.47it/s]

 84%|████████▍ | 84508/100629 [1:06:19<10:09, 26.44it/s]

 84%|████████▍ | 84512/100629 [1:06:19<09:21, 28.73it/s]

 84%|████████▍ | 84517/100629 [1:06:19<08:38, 31.08it/s]

 84%|████████▍ | 84521/100629 [1:06:19<12:12, 21.98it/s]

 84%|████████▍ | 84524/100629 [1:06:20<15:10, 17.69it/s]

 84%|████████▍ | 84527/100629 [1:06:20<14:31, 18.48it/s]

 84%|████████▍ | 84531/100629 [1:06:20<12:51, 20.86it/s]

 84%|████████▍ | 84534/100629 [1:06:20<12:48, 20.94it/s]

 84%|████████▍ | 84537/100629 [1:06:20<14:23, 18.63it/s]

 84%|████████▍ | 84540/100629 [1:06:20<13:48, 19.43it/s]

 84%|████████▍ | 84543/100629 [1:06:21<13:26, 19.94it/s]

 84%|████████▍ | 84546/100629 [1:06:21<13:55, 19.25it/s]

 84%|████████▍ | 84550/100629 [1:06:21<11:21, 23.59it/s]

 84%|████████▍ | 84553/100629 [1:06:21<12:11, 21.97it/s]

 84%|████████▍ | 84556/100629 [1:06:21<13:48, 19.41it/s]

 84%|████████▍ | 84559/100629 [1:06:21<14:32, 18.42it/s]

 84%|████████▍ | 84563/100629 [1:06:21<11:54, 22.49it/s]

 84%|████████▍ | 84566/100629 [1:06:22<15:16, 17.53it/s]

 84%|████████▍ | 84570/100629 [1:06:22<12:55, 20.71it/s]

 84%|████████▍ | 84574/100629 [1:06:22<11:02, 24.22it/s]

 84%|████████▍ | 84579/100629 [1:06:22<09:44, 27.47it/s]

 84%|████████▍ | 84583/100629 [1:06:22<08:53, 30.05it/s]

 84%|████████▍ | 84587/100629 [1:06:22<08:21, 31.99it/s]

 84%|████████▍ | 84591/100629 [1:06:22<09:02, 29.55it/s]

 84%|████████▍ | 84595/100629 [1:06:23<11:04, 24.12it/s]

 84%|████████▍ | 84598/100629 [1:06:23<12:16, 21.76it/s]

 84%|████████▍ | 84601/100629 [1:06:23<12:10, 21.94it/s]

 84%|████████▍ | 84604/100629 [1:06:23<12:01, 22.20it/s]

 84%|████████▍ | 84608/100629 [1:06:23<11:35, 23.04it/s]

 84%|████████▍ | 84612/100629 [1:06:23<10:44, 24.85it/s]

 84%|████████▍ | 84615/100629 [1:06:24<12:26, 21.44it/s]

 84%|████████▍ | 84618/100629 [1:06:24<12:15, 21.78it/s]

 84%|████████▍ | 84622/100629 [1:06:24<10:56, 24.37it/s]

 84%|████████▍ | 84626/100629 [1:06:24<10:31, 25.36it/s]

 84%|████████▍ | 84629/100629 [1:06:24<10:30, 25.39it/s]

 84%|████████▍ | 84633/100629 [1:06:24<09:51, 27.06it/s]

 84%|████████▍ | 84636/100629 [1:06:24<10:27, 25.49it/s]

 84%|████████▍ | 84639/100629 [1:06:25<10:54, 24.44it/s]

 84%|████████▍ | 84642/100629 [1:06:25<10:51, 24.52it/s]

 84%|████████▍ | 84645/100629 [1:06:25<10:51, 24.52it/s]

 84%|████████▍ | 84648/100629 [1:06:25<10:19, 25.78it/s]

 84%|████████▍ | 84651/100629 [1:06:25<13:34, 19.62it/s]

 84%|████████▍ | 84655/100629 [1:06:25<12:01, 22.13it/s]

 84%|████████▍ | 84658/100629 [1:06:25<13:00, 20.47it/s]

 84%|████████▍ | 84663/100629 [1:06:26<11:11, 23.79it/s]

 84%|████████▍ | 84666/100629 [1:06:26<11:36, 22.93it/s]

 84%|████████▍ | 84669/100629 [1:06:26<11:22, 23.39it/s]

 84%|████████▍ | 84672/100629 [1:06:26<12:57, 20.52it/s]

 84%|████████▍ | 84675/100629 [1:06:26<12:34, 21.15it/s]

 84%|████████▍ | 84678/100629 [1:06:26<12:01, 22.11it/s]

 84%|████████▍ | 84681/100629 [1:06:26<12:07, 21.93it/s]

 84%|████████▍ | 84685/100629 [1:06:27<10:40, 24.87it/s]

 84%|████████▍ | 84688/100629 [1:06:27<11:44, 22.64it/s]

 84%|████████▍ | 84692/100629 [1:06:27<10:57, 24.23it/s]

 84%|████████▍ | 84695/100629 [1:06:27<11:09, 23.79it/s]

 84%|████████▍ | 84698/100629 [1:06:27<12:02, 22.05it/s]

 84%|████████▍ | 84701/100629 [1:06:27<15:27, 17.17it/s]

 84%|████████▍ | 84703/100629 [1:06:28<15:38, 16.97it/s]

 84%|████████▍ | 84705/100629 [1:06:28<15:36, 17.00it/s]

 84%|████████▍ | 84707/100629 [1:06:28<17:21, 15.29it/s]

 84%|████████▍ | 84709/100629 [1:06:28<18:21, 14.46it/s]

 84%|████████▍ | 84711/100629 [1:06:28<19:48, 13.40it/s]

 84%|████████▍ | 84713/100629 [1:06:28<18:13, 14.55it/s]

 84%|████████▍ | 84716/100629 [1:06:28<16:00, 16.57it/s]

 84%|████████▍ | 84719/100629 [1:06:29<13:37, 19.47it/s]

 84%|████████▍ | 84722/100629 [1:06:29<12:29, 21.23it/s]

 84%|████████▍ | 84725/100629 [1:06:29<13:05, 20.25it/s]

 84%|████████▍ | 84728/100629 [1:06:29<12:05, 21.91it/s]

 84%|████████▍ | 84731/100629 [1:06:29<15:17, 17.34it/s]

 84%|████████▍ | 84734/100629 [1:06:29<14:07, 18.74it/s]

 84%|████████▍ | 84737/100629 [1:06:30<17:25, 15.20it/s]

 84%|████████▍ | 84739/100629 [1:06:30<16:34, 15.98it/s]

 84%|████████▍ | 84742/100629 [1:06:30<14:09, 18.70it/s]

 84%|████████▍ | 84745/100629 [1:06:30<12:49, 20.64it/s]

 84%|████████▍ | 84748/100629 [1:06:30<11:59, 22.08it/s]

 84%|████████▍ | 84751/100629 [1:06:30<12:46, 20.70it/s]

 84%|████████▍ | 84754/100629 [1:06:30<16:04, 16.46it/s]

 84%|████████▍ | 84757/100629 [1:06:31<13:59, 18.90it/s]

 84%|████████▍ | 84762/100629 [1:06:31<10:54, 24.24it/s]

 84%|████████▍ | 84765/100629 [1:06:31<10:35, 24.95it/s]

 84%|████████▍ | 84770/100629 [1:06:31<09:01, 29.30it/s]

 84%|████████▍ | 84774/100629 [1:06:31<09:48, 26.94it/s]

 84%|████████▍ | 84777/100629 [1:06:31<11:10, 23.65it/s]

 84%|████████▍ | 84780/100629 [1:06:31<12:16, 21.51it/s]

 84%|████████▍ | 84783/100629 [1:06:32<11:49, 22.33it/s]

 84%|████████▍ | 84786/100629 [1:06:32<12:08, 21.73it/s]

 84%|████████▍ | 84789/100629 [1:06:32<11:36, 22.73it/s]

 84%|████████▍ | 84792/100629 [1:06:32<10:51, 24.32it/s]

 84%|████████▍ | 84795/100629 [1:06:32<13:32, 19.50it/s]

 84%|████████▍ | 84798/100629 [1:06:32<12:31, 21.05it/s]

 84%|████████▍ | 84802/100629 [1:06:32<10:30, 25.09it/s]

 84%|████████▍ | 84805/100629 [1:06:33<12:38, 20.86it/s]

 84%|████████▍ | 84808/100629 [1:06:33<11:43, 22.48it/s]

 84%|████████▍ | 84811/100629 [1:06:33<11:20, 23.23it/s]

 84%|████████▍ | 84814/100629 [1:06:33<11:48, 22.32it/s]

 84%|████████▍ | 84817/100629 [1:06:33<12:47, 20.60it/s]

 84%|████████▍ | 84820/100629 [1:06:33<12:20, 21.36it/s]

 84%|████████▍ | 84824/100629 [1:06:33<11:17, 23.33it/s]

 84%|████████▍ | 84827/100629 [1:06:34<10:53, 24.18it/s]

 84%|████████▍ | 84830/100629 [1:06:34<12:49, 20.53it/s]

 84%|████████▍ | 84833/100629 [1:06:34<12:56, 20.34it/s]

 84%|████████▍ | 84836/100629 [1:06:34<15:09, 17.37it/s]

 84%|████████▍ | 84838/100629 [1:06:34<15:14, 17.26it/s]

 84%|████████▍ | 84841/100629 [1:06:34<15:38, 16.83it/s]

 84%|████████▍ | 84844/100629 [1:06:35<15:02, 17.49it/s]

 84%|████████▍ | 84846/100629 [1:06:35<14:44, 17.85it/s]

 84%|████████▍ | 84849/100629 [1:06:35<14:59, 17.54it/s]

 84%|████████▍ | 84852/100629 [1:06:35<13:21, 19.67it/s]

 84%|████████▍ | 84855/100629 [1:06:35<14:06, 18.63it/s]

 84%|████████▍ | 84857/100629 [1:06:35<14:21, 18.30it/s]

 84%|████████▍ | 84859/100629 [1:06:35<15:46, 16.67it/s]

 84%|████████▍ | 84861/100629 [1:06:36<17:00, 15.46it/s]

 84%|████████▍ | 84864/100629 [1:06:36<14:35, 18.01it/s]

 84%|████████▍ | 84866/100629 [1:06:36<14:42, 17.86it/s]

 84%|████████▍ | 84868/100629 [1:06:36<15:02, 17.47it/s]

 84%|████████▍ | 84870/100629 [1:06:36<15:53, 16.52it/s]

 84%|████████▍ | 84872/100629 [1:06:36<17:30, 15.00it/s]

 84%|████████▍ | 84874/100629 [1:06:36<16:50, 15.59it/s]

 84%|████████▍ | 84878/100629 [1:06:37<13:07, 20.00it/s]

 84%|████████▍ | 84882/100629 [1:06:37<10:34, 24.81it/s]

 84%|████████▍ | 84885/100629 [1:06:37<12:14, 21.44it/s]

 84%|████████▍ | 84888/100629 [1:06:37<12:24, 21.15it/s]

 84%|████████▍ | 84891/100629 [1:06:37<14:40, 17.88it/s]

 84%|████████▍ | 84895/100629 [1:06:37<13:58, 18.76it/s]

 84%|████████▍ | 84899/100629 [1:06:38<12:18, 21.30it/s]

 84%|████████▍ | 84903/100629 [1:06:38<10:33, 24.81it/s]

 84%|████████▍ | 84906/100629 [1:06:38<10:47, 24.28it/s]

 84%|████████▍ | 84909/100629 [1:06:38<12:29, 20.97it/s]

 84%|████████▍ | 84912/100629 [1:06:38<11:51, 22.08it/s]

 84%|████████▍ | 84915/100629 [1:06:38<12:33, 20.85it/s]

 84%|████████▍ | 84918/100629 [1:06:38<12:00, 21.81it/s]

 84%|████████▍ | 84921/100629 [1:06:38<11:10, 23.44it/s]

 84%|████████▍ | 84924/100629 [1:06:39<11:14, 23.29it/s]

 84%|████████▍ | 84927/100629 [1:06:39<11:00, 23.78it/s]

 84%|████████▍ | 84930/100629 [1:06:39<12:06, 21.61it/s]

 84%|████████▍ | 84933/100629 [1:06:39<12:31, 20.89it/s]

 84%|████████▍ | 84936/100629 [1:06:39<12:05, 21.64it/s]

 84%|████████▍ | 84939/100629 [1:06:39<11:49, 22.10it/s]

 84%|████████▍ | 84942/100629 [1:06:39<11:03, 23.64it/s]

 84%|████████▍ | 84946/100629 [1:06:40<10:35, 24.68it/s]

 84%|████████▍ | 84949/100629 [1:06:40<10:15, 25.48it/s]

 84%|████████▍ | 84952/100629 [1:06:40<12:44, 20.50it/s]

 84%|████████▍ | 84956/100629 [1:06:40<11:11, 23.35it/s]

 84%|████████▍ | 84959/100629 [1:06:40<11:34, 22.56it/s]

 84%|████████▍ | 84962/100629 [1:06:40<15:37, 16.72it/s]

 84%|████████▍ | 84964/100629 [1:06:41<15:25, 16.93it/s]

 84%|████████▍ | 84966/100629 [1:06:41<15:13, 17.15it/s]

 84%|████████▍ | 84971/100629 [1:06:41<12:03, 21.65it/s]

 84%|████████▍ | 84974/100629 [1:06:41<11:45, 22.18it/s]

 84%|████████▍ | 84977/100629 [1:06:41<10:58, 23.77it/s]

 84%|████████▍ | 84980/100629 [1:06:41<10:45, 24.23it/s]

 84%|████████▍ | 84983/100629 [1:06:41<10:52, 23.99it/s]

 84%|████████▍ | 84986/100629 [1:06:41<11:32, 22.58it/s]

 84%|████████▍ | 84989/100629 [1:06:42<12:43, 20.48it/s]

 84%|████████▍ | 84992/100629 [1:06:42<11:51, 21.99it/s]

 84%|████████▍ | 84997/100629 [1:06:42<09:46, 26.64it/s]

 84%|████████▍ | 85000/100629 [1:06:42<10:39, 24.45it/s]

 84%|████████▍ | 85004/100629 [1:06:42<09:52, 26.37it/s]

 84%|████████▍ | 85007/100629 [1:06:42<11:47, 22.07it/s]

 84%|████████▍ | 85010/100629 [1:06:42<12:23, 21.01it/s]

 84%|████████▍ | 85013/100629 [1:06:43<12:53, 20.19it/s]

 84%|████████▍ | 85017/100629 [1:06:43<11:11, 23.24it/s]

 84%|████████▍ | 85020/100629 [1:06:43<11:27, 22.71it/s]

 84%|████████▍ | 85023/100629 [1:06:43<11:46, 22.09it/s]

 84%|████████▍ | 85026/100629 [1:06:43<12:28, 20.86it/s]

 84%|████████▍ | 85030/100629 [1:06:43<11:13, 23.17it/s]

 85%|████████▍ | 85034/100629 [1:06:43<09:50, 26.42it/s]

 85%|████████▍ | 85037/100629 [1:06:44<09:48, 26.51it/s]

 85%|████████▍ | 85040/100629 [1:06:44<11:39, 22.30it/s]

 85%|████████▍ | 85044/100629 [1:06:44<10:35, 24.54it/s]

 85%|████████▍ | 85047/100629 [1:06:44<11:31, 22.54it/s]

 85%|████████▍ | 85050/100629 [1:06:44<11:36, 22.36it/s]

 85%|████████▍ | 85054/100629 [1:06:44<10:02, 25.84it/s]

 85%|████████▍ | 85058/100629 [1:06:44<09:41, 26.78it/s]

 85%|████████▍ | 85061/100629 [1:06:45<11:27, 22.64it/s]

 85%|████████▍ | 85064/100629 [1:06:45<10:55, 23.74it/s]

 85%|████████▍ | 85067/100629 [1:06:45<12:30, 20.74it/s]

 85%|████████▍ | 85070/100629 [1:06:45<13:09, 19.72it/s]

 85%|████████▍ | 85073/100629 [1:06:45<14:41, 17.65it/s]

 85%|████████▍ | 85077/100629 [1:06:45<11:52, 21.82it/s]

 85%|████████▍ | 85080/100629 [1:06:46<11:38, 22.26it/s]

 85%|████████▍ | 85083/100629 [1:06:46<15:02, 17.22it/s]

 85%|████████▍ | 85087/100629 [1:06:46<12:34, 20.60it/s]

 85%|████████▍ | 85090/100629 [1:06:46<12:38, 20.47it/s]

 85%|████████▍ | 85093/100629 [1:06:46<13:39, 18.95it/s]

 85%|████████▍ | 85096/100629 [1:06:46<12:15, 21.13it/s]

 85%|████████▍ | 85099/100629 [1:06:47<11:22, 22.77it/s]

 85%|████████▍ | 85103/100629 [1:06:47<10:07, 25.57it/s]

 85%|████████▍ | 85106/100629 [1:06:47<11:32, 22.43it/s]

 85%|████████▍ | 85109/100629 [1:06:47<12:07, 21.34it/s]

 85%|████████▍ | 85112/100629 [1:06:47<12:20, 20.96it/s]

 85%|████████▍ | 85115/100629 [1:06:47<11:58, 21.59it/s]

 85%|████████▍ | 85118/100629 [1:06:47<11:36, 22.28it/s]

 85%|████████▍ | 85121/100629 [1:06:48<11:40, 22.13it/s]

 85%|████████▍ | 85125/100629 [1:06:48<10:12, 25.33it/s]

 85%|████████▍ | 85128/100629 [1:06:48<11:26, 22.57it/s]

 85%|████████▍ | 85131/100629 [1:06:48<12:08, 21.28it/s]

 85%|████████▍ | 85134/100629 [1:06:48<11:35, 22.27it/s]

 85%|████████▍ | 85137/100629 [1:06:48<11:33, 22.33it/s]

 85%|████████▍ | 85140/100629 [1:06:48<12:59, 19.87it/s]

 85%|████████▍ | 85143/100629 [1:06:49<14:07, 18.27it/s]

 85%|████████▍ | 85145/100629 [1:06:49<14:11, 18.18it/s]

 85%|████████▍ | 85148/100629 [1:06:49<13:29, 19.12it/s]

 85%|████████▍ | 85151/100629 [1:06:49<12:26, 20.75it/s]

 85%|████████▍ | 85154/100629 [1:06:49<12:20, 20.90it/s]

 85%|████████▍ | 85159/100629 [1:06:49<09:20, 27.62it/s]

 85%|████████▍ | 85162/100629 [1:06:49<09:57, 25.88it/s]

 85%|████████▍ | 85165/100629 [1:06:49<09:45, 26.43it/s]

 85%|████████▍ | 85168/100629 [1:06:50<09:35, 26.86it/s]

 85%|████████▍ | 85172/100629 [1:06:50<09:59, 25.78it/s]

 85%|████████▍ | 85177/100629 [1:06:50<08:26, 30.50it/s]

 85%|████████▍ | 85181/100629 [1:06:50<09:45, 26.38it/s]

 85%|████████▍ | 85184/100629 [1:06:50<11:00, 23.40it/s]

 85%|████████▍ | 85188/100629 [1:06:50<09:48, 26.22it/s]

 85%|████████▍ | 85191/100629 [1:06:50<09:56, 25.88it/s]

 85%|████████▍ | 85194/100629 [1:06:51<12:05, 21.28it/s]

 85%|████████▍ | 85197/100629 [1:06:51<11:07, 23.11it/s]

 85%|████████▍ | 85200/100629 [1:06:51<12:07, 21.20it/s]

 85%|████████▍ | 85203/100629 [1:06:51<11:17, 22.76it/s]

 85%|████████▍ | 85206/100629 [1:06:51<11:36, 22.15it/s]

 85%|████████▍ | 85209/100629 [1:06:51<12:35, 20.40it/s]

 85%|████████▍ | 85212/100629 [1:06:52<17:01, 15.09it/s]

 85%|████████▍ | 85215/100629 [1:06:52<14:42, 17.47it/s]

 85%|████████▍ | 85218/100629 [1:06:52<13:59, 18.36it/s]

 85%|████████▍ | 85222/100629 [1:06:52<12:07, 21.18it/s]

 85%|████████▍ | 85225/100629 [1:06:52<13:23, 19.18it/s]

 85%|████████▍ | 85228/100629 [1:06:52<12:55, 19.85it/s]

 85%|████████▍ | 85232/100629 [1:06:53<11:29, 22.35it/s]

 85%|████████▍ | 85235/100629 [1:06:53<12:13, 21.00it/s]

 85%|████████▍ | 85239/100629 [1:06:53<10:23, 24.69it/s]

 85%|████████▍ | 85242/100629 [1:06:53<12:06, 21.17it/s]

 85%|████████▍ | 85245/100629 [1:06:53<15:17, 16.77it/s]

 85%|████████▍ | 85248/100629 [1:06:53<14:14, 17.99it/s]

 85%|████████▍ | 85251/100629 [1:06:54<14:01, 18.27it/s]

 85%|████████▍ | 85253/100629 [1:06:54<14:53, 17.20it/s]

 85%|████████▍ | 85257/100629 [1:06:54<11:39, 21.97it/s]

 85%|████████▍ | 85260/100629 [1:06:54<12:48, 19.99it/s]

 85%|████████▍ | 85263/100629 [1:06:54<11:55, 21.47it/s]

 85%|████████▍ | 85266/100629 [1:06:54<11:24, 22.44it/s]

 85%|████████▍ | 85269/100629 [1:06:54<12:32, 20.42it/s]

 85%|████████▍ | 85272/100629 [1:06:55<15:48, 16.19it/s]

 85%|████████▍ | 85274/100629 [1:06:55<16:19, 15.68it/s]

 85%|████████▍ | 85277/100629 [1:06:55<16:42, 15.31it/s]

 85%|████████▍ | 85280/100629 [1:06:55<14:22, 17.79it/s]

 85%|████████▍ | 85283/100629 [1:06:55<13:46, 18.56it/s]

 85%|████████▍ | 85285/100629 [1:06:55<14:01, 18.23it/s]

 85%|████████▍ | 85287/100629 [1:06:56<13:52, 18.43it/s]

 85%|████████▍ | 85290/100629 [1:06:56<21:30, 11.88it/s]

 85%|████████▍ | 85292/100629 [1:06:56<20:49, 12.28it/s]

 85%|████████▍ | 85295/100629 [1:06:56<17:39, 14.47it/s]

 85%|████████▍ | 85297/100629 [1:06:56<17:12, 14.85it/s]

 85%|████████▍ | 85302/100629 [1:06:56<12:00, 21.28it/s]

 85%|████████▍ | 85305/100629 [1:06:57<11:07, 22.95it/s]

 85%|████████▍ | 85309/100629 [1:06:57<09:57, 25.63it/s]

 85%|████████▍ | 85314/100629 [1:06:57<08:32, 29.90it/s]

 85%|████████▍ | 85318/100629 [1:06:57<10:09, 25.11it/s]

 85%|████████▍ | 85323/100629 [1:06:57<08:26, 30.21it/s]

 85%|████████▍ | 85327/100629 [1:06:57<09:01, 28.25it/s]

 85%|████████▍ | 85331/100629 [1:06:57<09:25, 27.04it/s]

 85%|████████▍ | 85334/100629 [1:06:58<11:35, 21.98it/s]

 85%|████████▍ | 85337/100629 [1:06:58<12:08, 20.99it/s]

 85%|████████▍ | 85340/100629 [1:06:58<13:37, 18.70it/s]

 85%|████████▍ | 85343/100629 [1:06:58<15:09, 16.81it/s]

 85%|████████▍ | 85346/100629 [1:06:58<13:44, 18.54it/s]

 85%|████████▍ | 85349/100629 [1:06:59<12:20, 20.63it/s]

 85%|████████▍ | 85352/100629 [1:06:59<11:26, 22.27it/s]

 85%|████████▍ | 85355/100629 [1:06:59<11:22, 22.39it/s]

 85%|████████▍ | 85358/100629 [1:06:59<13:40, 18.62it/s]

 85%|████████▍ | 85361/100629 [1:06:59<15:11, 16.76it/s]

 85%|████████▍ | 85365/100629 [1:06:59<12:41, 20.04it/s]

 85%|████████▍ | 85368/100629 [1:06:59<12:26, 20.44it/s]

 85%|████████▍ | 85371/100629 [1:07:00<12:45, 19.92it/s]

 85%|████████▍ | 85374/100629 [1:07:00<13:21, 19.04it/s]

 85%|████████▍ | 85376/100629 [1:07:00<15:32, 16.36it/s]

 85%|████████▍ | 85379/100629 [1:07:00<13:26, 18.92it/s]

 85%|████████▍ | 85383/100629 [1:07:00<10:57, 23.19it/s]

 85%|████████▍ | 85386/100629 [1:07:00<11:05, 22.90it/s]

 85%|████████▍ | 85389/100629 [1:07:01<12:51, 19.74it/s]

 85%|████████▍ | 85393/100629 [1:07:01<11:02, 22.99it/s]

 85%|████████▍ | 85396/100629 [1:07:01<11:46, 21.56it/s]

 85%|████████▍ | 85399/100629 [1:07:01<13:17, 19.10it/s]

 85%|████████▍ | 85402/100629 [1:07:01<12:57, 19.59it/s]

 85%|████████▍ | 85405/100629 [1:07:01<12:33, 20.21it/s]

 85%|████████▍ | 85408/100629 [1:07:01<12:48, 19.80it/s]

 85%|████████▍ | 85411/100629 [1:07:02<12:56, 19.60it/s]

 85%|████████▍ | 85415/100629 [1:07:02<12:14, 20.72it/s]

 85%|████████▍ | 85418/100629 [1:07:02<13:22, 18.96it/s]

 85%|████████▍ | 85420/100629 [1:07:02<14:06, 17.96it/s]

 85%|████████▍ | 85422/100629 [1:07:02<15:38, 16.20it/s]

 85%|████████▍ | 85424/100629 [1:07:02<18:25, 13.75it/s]

 85%|████████▍ | 85427/100629 [1:07:03<16:02, 15.79it/s]

 85%|████████▍ | 85429/100629 [1:07:03<15:49, 16.01it/s]

 85%|████████▍ | 85431/100629 [1:07:03<15:20, 16.51it/s]

 85%|████████▍ | 85436/100629 [1:07:03<12:10, 20.80it/s]

 85%|████████▍ | 85440/100629 [1:07:03<10:17, 24.58it/s]

 85%|████████▍ | 85443/100629 [1:07:03<11:24, 22.19it/s]

 85%|████████▍ | 85446/100629 [1:07:03<10:46, 23.49it/s]

 85%|████████▍ | 85449/100629 [1:07:04<15:34, 16.24it/s]

 85%|████████▍ | 85451/100629 [1:07:04<15:41, 16.12it/s]

 85%|████████▍ | 85453/100629 [1:07:04<16:03, 15.76it/s]

 85%|████████▍ | 85456/100629 [1:07:04<14:00, 18.04it/s]

 85%|████████▍ | 85458/100629 [1:07:04<16:06, 15.70it/s]

 85%|████████▍ | 85461/100629 [1:07:04<15:18, 16.51it/s]

 85%|████████▍ | 85464/100629 [1:07:05<13:41, 18.45it/s]

 85%|████████▍ | 85466/100629 [1:07:05<13:36, 18.58it/s]

 85%|████████▍ | 85469/100629 [1:07:05<13:18, 18.98it/s]

 85%|████████▍ | 85471/100629 [1:07:05<14:01, 18.01it/s]

 85%|████████▍ | 85476/100629 [1:07:05<10:57, 23.04it/s]

 85%|████████▍ | 85479/100629 [1:07:05<10:53, 23.18it/s]

 85%|████████▍ | 85482/100629 [1:07:05<12:19, 20.49it/s]

 85%|████████▍ | 85485/100629 [1:07:06<12:32, 20.12it/s]

 85%|████████▍ | 85488/100629 [1:07:06<12:13, 20.64it/s]

 85%|████████▍ | 85492/100629 [1:07:06<11:11, 22.53it/s]

 85%|████████▍ | 85496/100629 [1:07:06<10:41, 23.57it/s]

 85%|████████▍ | 85499/100629 [1:07:06<14:35, 17.29it/s]

 85%|████████▍ | 85501/100629 [1:07:06<14:38, 17.22it/s]

 85%|████████▍ | 85503/100629 [1:07:07<14:17, 17.63it/s]

 85%|████████▍ | 85506/100629 [1:07:07<12:30, 20.15it/s]

 85%|████████▍ | 85509/100629 [1:07:07<12:27, 20.22it/s]

 85%|████████▍ | 85512/100629 [1:07:07<13:38, 18.47it/s]

 85%|████████▍ | 85514/100629 [1:07:07<14:22, 17.52it/s]

 85%|████████▍ | 85516/100629 [1:07:07<15:04, 16.71it/s]

 85%|████████▍ | 85518/100629 [1:07:07<17:27, 14.43it/s]

 85%|████████▍ | 85522/100629 [1:07:08<14:11, 17.73it/s]

 85%|████████▍ | 85524/100629 [1:07:08<15:33, 16.19it/s]

 85%|████████▍ | 85526/100629 [1:07:08<15:03, 16.72it/s]

 85%|████████▍ | 85530/100629 [1:07:08<13:12, 19.04it/s]

 85%|████████▍ | 85533/100629 [1:07:08<12:58, 19.40it/s]

 85%|████████▌ | 85535/100629 [1:07:08<14:01, 17.94it/s]

 85%|████████▌ | 85539/100629 [1:07:08<11:20, 22.19it/s]

 85%|████████▌ | 85542/100629 [1:07:09<12:41, 19.81it/s]

 85%|████████▌ | 85545/100629 [1:07:09<18:00, 13.96it/s]

 85%|████████▌ | 85547/100629 [1:07:09<17:20, 14.50it/s]

 85%|████████▌ | 85549/100629 [1:07:09<17:04, 14.72it/s]

 85%|████████▌ | 85553/100629 [1:07:09<12:43, 19.74it/s]

 85%|████████▌ | 85556/100629 [1:07:10<12:37, 19.91it/s]

 85%|████████▌ | 85559/100629 [1:07:10<11:43, 21.43it/s]

 85%|████████▌ | 85562/100629 [1:07:10<11:37, 21.60it/s]

 85%|████████▌ | 85566/100629 [1:07:10<11:17, 22.22it/s]

 85%|████████▌ | 85570/100629 [1:07:10<12:01, 20.87it/s]

 85%|████████▌ | 85573/100629 [1:07:10<11:34, 21.69it/s]

 85%|████████▌ | 85576/100629 [1:07:10<11:56, 21.00it/s]

 85%|████████▌ | 85579/100629 [1:07:11<12:01, 20.86it/s]

 85%|████████▌ | 85582/100629 [1:07:11<12:35, 19.92it/s]

 85%|████████▌ | 85586/100629 [1:07:11<13:24, 18.70it/s]

 85%|████████▌ | 85591/100629 [1:07:11<10:28, 23.91it/s]

 85%|████████▌ | 85595/100629 [1:07:11<09:29, 26.42it/s]

 85%|████████▌ | 85598/100629 [1:07:11<10:37, 23.59it/s]

 85%|████████▌ | 85601/100629 [1:07:12<10:38, 23.55it/s]

 85%|████████▌ | 85604/100629 [1:07:12<10:13, 24.50it/s]

 85%|████████▌ | 85607/100629 [1:07:12<10:15, 24.41it/s]

 85%|████████▌ | 85611/100629 [1:07:12<09:19, 26.86it/s]

 85%|████████▌ | 85615/100629 [1:07:12<08:59, 27.81it/s]

 85%|████████▌ | 85618/100629 [1:07:12<10:11, 24.55it/s]

 85%|████████▌ | 85621/100629 [1:07:12<10:04, 24.83it/s]

 85%|████████▌ | 85624/100629 [1:07:12<11:12, 22.30it/s]

 85%|████████▌ | 85627/100629 [1:07:13<10:52, 22.97it/s]

 85%|████████▌ | 85631/100629 [1:07:13<10:30, 23.77it/s]

 85%|████████▌ | 85634/100629 [1:07:13<12:10, 20.53it/s]

 85%|████████▌ | 85637/100629 [1:07:13<13:04, 19.10it/s]

 85%|████████▌ | 85640/100629 [1:07:13<12:27, 20.04it/s]

 85%|████████▌ | 85643/100629 [1:07:13<11:30, 21.70it/s]

 85%|████████▌ | 85646/100629 [1:07:13<11:46, 21.20it/s]

 85%|████████▌ | 85649/100629 [1:07:14<13:09, 18.98it/s]

 85%|████████▌ | 85653/100629 [1:07:14<12:00, 20.78it/s]

 85%|████████▌ | 85656/100629 [1:07:14<11:30, 21.69it/s]

 85%|████████▌ | 85659/100629 [1:07:14<10:48, 23.09it/s]

 85%|████████▌ | 85662/100629 [1:07:14<11:47, 21.14it/s]

 85%|████████▌ | 85665/100629 [1:07:14<11:58, 20.83it/s]

 85%|████████▌ | 85668/100629 [1:07:15<13:45, 18.13it/s]

 85%|████████▌ | 85672/100629 [1:07:15<12:01, 20.73it/s]

 85%|████████▌ | 85675/100629 [1:07:15<11:10, 22.30it/s]

 85%|████████▌ | 85678/100629 [1:07:15<11:15, 22.14it/s]

 85%|████████▌ | 85682/100629 [1:07:15<09:45, 25.54it/s]

 85%|████████▌ | 85686/100629 [1:07:15<10:08, 24.55it/s]

 85%|████████▌ | 85689/100629 [1:07:15<11:27, 21.72it/s]

 85%|████████▌ | 85692/100629 [1:07:16<11:14, 22.14it/s]

 85%|████████▌ | 85695/100629 [1:07:16<10:49, 23.01it/s]

 85%|████████▌ | 85698/100629 [1:07:16<12:07, 20.51it/s]

 85%|████████▌ | 85701/100629 [1:07:16<13:30, 18.41it/s]

 85%|████████▌ | 85704/100629 [1:07:16<12:48, 19.43it/s]

 85%|████████▌ | 85708/100629 [1:07:16<11:49, 21.02it/s]

 85%|████████▌ | 85711/100629 [1:07:17<11:54, 20.89it/s]

 85%|████████▌ | 85714/100629 [1:07:17<12:41, 19.58it/s]

 85%|████████▌ | 85716/100629 [1:07:17<13:08, 18.91it/s]

 85%|████████▌ | 85719/100629 [1:07:17<12:05, 20.56it/s]

 85%|████████▌ | 85722/100629 [1:07:17<11:35, 21.43it/s]

 85%|████████▌ | 85725/100629 [1:07:17<12:23, 20.03it/s]

 85%|████████▌ | 85728/100629 [1:07:17<11:10, 22.22it/s]

 85%|████████▌ | 85731/100629 [1:07:18<11:26, 21.70it/s]

 85%|████████▌ | 85734/100629 [1:07:18<10:44, 23.10it/s]

 85%|████████▌ | 85737/100629 [1:07:18<10:54, 22.75it/s]

 85%|████████▌ | 85740/100629 [1:07:18<11:04, 22.42it/s]

 85%|████████▌ | 85743/100629 [1:07:18<12:19, 20.12it/s]

 85%|████████▌ | 85746/100629 [1:07:18<11:16, 21.99it/s]

 85%|████████▌ | 85749/100629 [1:07:18<12:46, 19.41it/s]

 85%|████████▌ | 85752/100629 [1:07:19<11:49, 20.96it/s]

 85%|████████▌ | 85755/100629 [1:07:19<12:09, 20.40it/s]

 85%|████████▌ | 85758/100629 [1:07:19<12:36, 19.67it/s]

 85%|████████▌ | 85761/100629 [1:07:19<11:59, 20.66it/s]

 85%|████████▌ | 85765/100629 [1:07:19<11:54, 20.81it/s]

 85%|████████▌ | 85768/100629 [1:07:19<11:09, 22.19it/s]

 85%|████████▌ | 85771/100629 [1:07:19<11:09, 22.19it/s]

 85%|████████▌ | 85774/100629 [1:07:20<10:47, 22.95it/s]

 85%|████████▌ | 85778/100629 [1:07:20<09:24, 26.33it/s]

 85%|████████▌ | 85781/100629 [1:07:20<12:39, 19.56it/s]

 85%|████████▌ | 85785/100629 [1:07:20<10:33, 23.45it/s]

 85%|████████▌ | 85788/100629 [1:07:20<10:34, 23.38it/s]

 85%|████████▌ | 85791/100629 [1:07:20<12:00, 20.60it/s]

 85%|████████▌ | 85794/100629 [1:07:20<12:43, 19.44it/s]

 85%|████████▌ | 85797/100629 [1:07:21<11:49, 20.92it/s]

 85%|████████▌ | 85800/100629 [1:07:21<10:47, 22.88it/s]

 85%|████████▌ | 85803/100629 [1:07:21<12:34, 19.65it/s]

 85%|████████▌ | 85806/100629 [1:07:21<16:00, 15.43it/s]

 85%|████████▌ | 85810/100629 [1:07:21<15:15, 16.19it/s]

 85%|████████▌ | 85812/100629 [1:07:22<15:21, 16.08it/s]

 85%|████████▌ | 85816/100629 [1:07:22<12:16, 20.10it/s]

 85%|████████▌ | 85819/100629 [1:07:22<15:41, 15.73it/s]

 85%|████████▌ | 85821/100629 [1:07:22<14:59, 16.47it/s]

 85%|████████▌ | 85823/100629 [1:07:22<15:24, 16.02it/s]

 85%|████████▌ | 85825/100629 [1:07:22<15:49, 15.59it/s]

 85%|████████▌ | 85828/100629 [1:07:23<15:01, 16.41it/s]

 85%|████████▌ | 85831/100629 [1:07:23<13:32, 18.20it/s]

 85%|████████▌ | 85833/100629 [1:07:23<14:28, 17.04it/s]

 85%|████████▌ | 85835/100629 [1:07:23<16:06, 15.31it/s]

 85%|████████▌ | 85839/100629 [1:07:23<12:35, 19.58it/s]

 85%|████████▌ | 85842/100629 [1:07:23<12:43, 19.38it/s]

 85%|████████▌ | 85845/100629 [1:07:23<12:08, 20.30it/s]

 85%|████████▌ | 85849/100629 [1:07:23<10:42, 23.02it/s]

 85%|████████▌ | 85853/100629 [1:07:24<09:12, 26.73it/s]

 85%|████████▌ | 85857/100629 [1:07:24<08:54, 27.66it/s]

 85%|████████▌ | 85862/100629 [1:07:24<07:28, 32.94it/s]

 85%|████████▌ | 85867/100629 [1:07:24<08:02, 30.63it/s]

 85%|████████▌ | 85871/100629 [1:07:24<09:14, 26.61it/s]

 85%|████████▌ | 85874/100629 [1:07:24<10:24, 23.63it/s]

 85%|████████▌ | 85878/100629 [1:07:25<09:43, 25.29it/s]

 85%|████████▌ | 85881/100629 [1:07:25<10:03, 24.45it/s]

 85%|████████▌ | 85884/100629 [1:07:25<10:56, 22.45it/s]

 85%|████████▌ | 85887/100629 [1:07:25<10:48, 22.75it/s]

 85%|████████▌ | 85890/100629 [1:07:25<11:44, 20.92it/s]

 85%|████████▌ | 85894/100629 [1:07:25<10:42, 22.92it/s]

 85%|████████▌ | 85897/100629 [1:07:25<10:25, 23.55it/s]

 85%|████████▌ | 85900/100629 [1:07:26<11:10, 21.95it/s]

 85%|████████▌ | 85903/100629 [1:07:26<10:52, 22.57it/s]

 85%|████████▌ | 85906/100629 [1:07:26<11:15, 21.80it/s]

 85%|████████▌ | 85909/100629 [1:07:26<11:17, 21.72it/s]

 85%|████████▌ | 85912/100629 [1:07:26<10:47, 22.73it/s]

 85%|████████▌ | 85916/100629 [1:07:26<10:17, 23.81it/s]

 85%|████████▌ | 85919/100629 [1:07:26<11:41, 20.98it/s]

 85%|████████▌ | 85923/100629 [1:07:27<10:09, 24.14it/s]

 85%|████████▌ | 85926/100629 [1:07:27<09:53, 24.77it/s]

 85%|████████▌ | 85929/100629 [1:07:27<10:57, 22.34it/s]

 85%|████████▌ | 85932/100629 [1:07:27<12:54, 18.97it/s]

 85%|████████▌ | 85936/100629 [1:07:27<11:28, 21.33it/s]

 85%|████████▌ | 85939/100629 [1:07:27<14:48, 16.54it/s]

 85%|████████▌ | 85944/100629 [1:07:28<11:04, 22.10it/s]

 85%|████████▌ | 85947/100629 [1:07:28<11:58, 20.43it/s]

 85%|████████▌ | 85950/100629 [1:07:28<11:08, 21.96it/s]

 85%|████████▌ | 85954/100629 [1:07:28<10:13, 23.92it/s]

 85%|████████▌ | 85957/100629 [1:07:28<10:29, 23.30it/s]

 85%|████████▌ | 85960/100629 [1:07:28<10:31, 23.24it/s]

 85%|████████▌ | 85963/100629 [1:07:28<10:15, 23.83it/s]

 85%|████████▌ | 85966/100629 [1:07:29<12:06, 20.19it/s]

 85%|████████▌ | 85969/100629 [1:07:29<11:36, 21.04it/s]

 85%|████████▌ | 85972/100629 [1:07:29<11:32, 21.16it/s]

 85%|████████▌ | 85976/100629 [1:07:29<10:28, 23.31it/s]

 85%|████████▌ | 85979/100629 [1:07:29<11:31, 21.17it/s]

 85%|████████▌ | 85982/100629 [1:07:29<12:12, 20.00it/s]

 85%|████████▌ | 85985/100629 [1:07:29<11:44, 20.77it/s]

 85%|████████▌ | 85988/100629 [1:07:30<12:50, 19.01it/s]

 85%|████████▌ | 85991/100629 [1:07:30<12:55, 18.89it/s]

 85%|████████▌ | 85995/100629 [1:07:30<11:44, 20.78it/s]

 85%|████████▌ | 85999/100629 [1:07:30<11:05, 21.99it/s]

 85%|████████▌ | 86002/100629 [1:07:30<13:01, 18.71it/s]

 85%|████████▌ | 86005/100629 [1:07:31<12:25, 19.60it/s]

 85%|████████▌ | 86008/100629 [1:07:31<11:27, 21.25it/s]

 85%|████████▌ | 86011/100629 [1:07:31<11:23, 21.37it/s]

 85%|████████▌ | 86014/100629 [1:07:31<10:44, 22.69it/s]

 85%|████████▌ | 86018/100629 [1:07:31<10:02, 24.23it/s]

 85%|████████▌ | 86021/100629 [1:07:31<10:23, 23.44it/s]

 85%|████████▌ | 86024/100629 [1:07:31<13:18, 18.28it/s]

 85%|████████▌ | 86027/100629 [1:07:32<13:01, 18.69it/s]

 85%|████████▌ | 86030/100629 [1:07:32<16:21, 14.87it/s]

 85%|████████▌ | 86032/100629 [1:07:32<17:07, 14.20it/s]

 85%|████████▌ | 86035/100629 [1:07:32<16:07, 15.09it/s]

 85%|████████▌ | 86037/100629 [1:07:32<16:46, 14.50it/s]

 86%|████████▌ | 86039/100629 [1:07:32<15:43, 15.46it/s]

 86%|████████▌ | 86041/100629 [1:07:33<15:14, 15.96it/s]

 86%|████████▌ | 86043/100629 [1:07:33<14:51, 16.37it/s]

 86%|████████▌ | 86045/100629 [1:07:33<14:12, 17.10it/s]

 86%|████████▌ | 86049/100629 [1:07:33<10:52, 22.35it/s]

 86%|████████▌ | 86052/100629 [1:07:33<12:29, 19.44it/s]

 86%|████████▌ | 86055/100629 [1:07:33<12:28, 19.47it/s]

 86%|████████▌ | 86058/100629 [1:07:33<12:25, 19.55it/s]

 86%|████████▌ | 86061/100629 [1:07:34<13:46, 17.62it/s]

 86%|████████▌ | 86064/100629 [1:07:34<14:56, 16.25it/s]

 86%|████████▌ | 86067/100629 [1:07:34<13:10, 18.41it/s]

 86%|████████▌ | 86069/100629 [1:07:34<13:14, 18.33it/s]

 86%|████████▌ | 86072/100629 [1:07:34<12:55, 18.78it/s]

 86%|████████▌ | 86075/100629 [1:07:34<11:58, 20.26it/s]

 86%|████████▌ | 86080/100629 [1:07:34<08:58, 27.02it/s]

 86%|████████▌ | 86083/100629 [1:07:35<10:04, 24.05it/s]

 86%|████████▌ | 86086/100629 [1:07:35<10:19, 23.48it/s]

 86%|████████▌ | 86091/100629 [1:07:35<08:48, 27.48it/s]

 86%|████████▌ | 86094/100629 [1:07:35<10:24, 23.28it/s]

 86%|████████▌ | 86097/100629 [1:07:35<10:27, 23.17it/s]

 86%|████████▌ | 86101/100629 [1:07:35<09:22, 25.82it/s]

 86%|████████▌ | 86104/100629 [1:07:35<09:10, 26.39it/s]

 86%|████████▌ | 86107/100629 [1:07:36<08:56, 27.08it/s]

 86%|████████▌ | 86110/100629 [1:07:36<09:36, 25.18it/s]

 86%|████████▌ | 86114/100629 [1:07:36<09:01, 26.80it/s]

 86%|████████▌ | 86117/100629 [1:07:36<09:33, 25.30it/s]

 86%|████████▌ | 86120/100629 [1:07:36<10:14, 23.62it/s]

 86%|████████▌ | 86123/100629 [1:07:36<10:57, 22.07it/s]

 86%|████████▌ | 86126/100629 [1:07:36<11:06, 21.75it/s]

 86%|████████▌ | 86129/100629 [1:07:37<11:49, 20.44it/s]

 86%|████████▌ | 86132/100629 [1:07:37<16:00, 15.09it/s]

 86%|████████▌ | 86136/100629 [1:07:37<13:03, 18.50it/s]

 86%|████████▌ | 86139/100629 [1:07:37<12:58, 18.61it/s]

 86%|████████▌ | 86142/100629 [1:07:37<12:14, 19.72it/s]

 86%|████████▌ | 86146/100629 [1:07:37<10:18, 23.41it/s]

 86%|████████▌ | 86149/100629 [1:07:38<11:37, 20.76it/s]

 86%|████████▌ | 86152/100629 [1:07:38<11:24, 21.15it/s]

 86%|████████▌ | 86155/100629 [1:07:38<10:32, 22.89it/s]

 86%|████████▌ | 86158/100629 [1:07:38<10:40, 22.58it/s]

 86%|████████▌ | 86161/100629 [1:07:38<10:34, 22.79it/s]

 86%|████████▌ | 86164/100629 [1:07:38<11:02, 21.82it/s]

 86%|████████▌ | 86167/100629 [1:07:38<11:27, 21.03it/s]

 86%|████████▌ | 86170/100629 [1:07:39<11:28, 21.01it/s]

 86%|████████▌ | 86173/100629 [1:07:39<11:47, 20.43it/s]

 86%|████████▌ | 86177/100629 [1:07:39<09:56, 24.23it/s]

 86%|████████▌ | 86180/100629 [1:07:39<11:05, 21.72it/s]

 86%|████████▌ | 86183/100629 [1:07:39<10:33, 22.81it/s]

 86%|████████▌ | 86187/100629 [1:07:39<09:15, 26.01it/s]

 86%|████████▌ | 86191/100629 [1:07:39<09:36, 25.04it/s]

 86%|████████▌ | 86194/100629 [1:07:40<10:35, 22.72it/s]

 86%|████████▌ | 86197/100629 [1:07:40<11:45, 20.45it/s]

 86%|████████▌ | 86200/100629 [1:07:40<12:41, 18.96it/s]

 86%|████████▌ | 86203/100629 [1:07:40<11:32, 20.84it/s]

 86%|████████▌ | 86206/100629 [1:07:40<11:35, 20.73it/s]

 86%|████████▌ | 86209/100629 [1:07:40<11:22, 21.12it/s]

 86%|████████▌ | 86212/100629 [1:07:40<10:24, 23.08it/s]

 86%|████████▌ | 86215/100629 [1:07:41<10:45, 22.32it/s]

 86%|████████▌ | 86219/100629 [1:07:41<10:43, 22.39it/s]

 86%|████████▌ | 86222/100629 [1:07:41<11:08, 21.55it/s]

 86%|████████▌ | 86227/100629 [1:07:41<09:01, 26.58it/s]

 86%|████████▌ | 86230/100629 [1:07:41<09:36, 24.99it/s]

 86%|████████▌ | 86234/100629 [1:07:41<08:50, 27.16it/s]

 86%|████████▌ | 86237/100629 [1:07:41<10:57, 21.89it/s]

 86%|████████▌ | 86242/100629 [1:07:42<09:50, 24.38it/s]

 86%|████████▌ | 86245/100629 [1:07:42<09:54, 24.19it/s]

 86%|████████▌ | 86248/100629 [1:07:42<10:03, 23.82it/s]

 86%|████████▌ | 86251/100629 [1:07:42<11:39, 20.54it/s]

 86%|████████▌ | 86255/100629 [1:07:42<10:05, 23.74it/s]

 86%|████████▌ | 86258/100629 [1:07:42<10:43, 22.32it/s]

 86%|████████▌ | 86261/100629 [1:07:43<10:32, 22.72it/s]

 86%|████████▌ | 86264/100629 [1:07:43<11:38, 20.56it/s]

 86%|████████▌ | 86267/100629 [1:07:43<10:44, 22.28it/s]

 86%|████████▌ | 86272/100629 [1:07:43<08:24, 28.46it/s]

 86%|████████▌ | 86276/100629 [1:07:43<08:23, 28.52it/s]

 86%|████████▌ | 86280/100629 [1:07:43<09:07, 26.21it/s]

 86%|████████▌ | 86283/100629 [1:07:43<12:05, 19.78it/s]

 86%|████████▌ | 86286/100629 [1:07:44<12:49, 18.64it/s]

 86%|████████▌ | 86289/100629 [1:07:44<13:34, 17.61it/s]

 86%|████████▌ | 86293/100629 [1:07:44<12:46, 18.69it/s]

 86%|████████▌ | 86296/100629 [1:07:44<12:59, 18.38it/s]

 86%|████████▌ | 86298/100629 [1:07:44<14:34, 16.39it/s]

 86%|████████▌ | 86300/100629 [1:07:45<14:51, 16.08it/s]

 86%|████████▌ | 86304/100629 [1:07:45<12:05, 19.73it/s]

 86%|████████▌ | 86307/100629 [1:07:45<12:10, 19.61it/s]

 86%|████████▌ | 86310/100629 [1:07:45<11:56, 19.99it/s]

 86%|████████▌ | 86313/100629 [1:07:45<12:50, 18.57it/s]

 86%|████████▌ | 86315/100629 [1:07:45<13:33, 17.59it/s]

 86%|████████▌ | 86317/100629 [1:07:45<13:47, 17.29it/s]

 86%|████████▌ | 86319/100629 [1:07:46<13:46, 17.32it/s]

 86%|████████▌ | 86322/100629 [1:07:46<12:24, 19.21it/s]

 86%|████████▌ | 86325/100629 [1:07:46<14:09, 16.83it/s]

 86%|████████▌ | 86327/100629 [1:07:46<13:43, 17.36it/s]

 86%|████████▌ | 86330/100629 [1:07:46<12:14, 19.46it/s]

 86%|████████▌ | 86333/100629 [1:07:46<13:35, 17.53it/s]

 86%|████████▌ | 86337/100629 [1:07:46<11:11, 21.30it/s]

 86%|████████▌ | 86340/100629 [1:07:47<10:59, 21.68it/s]

 86%|████████▌ | 86343/100629 [1:07:47<10:39, 22.35it/s]

 86%|████████▌ | 86347/100629 [1:07:47<10:05, 23.57it/s]

 86%|████████▌ | 86351/100629 [1:07:47<08:46, 27.12it/s]

 86%|████████▌ | 86354/100629 [1:07:47<09:48, 24.24it/s]

 86%|████████▌ | 86357/100629 [1:07:47<09:43, 24.47it/s]

 86%|████████▌ | 86360/100629 [1:07:47<10:38, 22.34it/s]

 86%|████████▌ | 86364/100629 [1:07:48<09:37, 24.68it/s]

 86%|████████▌ | 86367/100629 [1:07:48<11:07, 21.37it/s]

 86%|████████▌ | 86370/100629 [1:07:48<12:24, 19.16it/s]

 86%|████████▌ | 86373/100629 [1:07:48<12:15, 19.37it/s]

 86%|████████▌ | 86376/100629 [1:07:48<12:35, 18.85it/s]

 86%|████████▌ | 86379/100629 [1:07:48<11:29, 20.66it/s]

 86%|████████▌ | 86382/100629 [1:07:48<11:20, 20.92it/s]

 86%|████████▌ | 86388/100629 [1:07:49<08:38, 27.46it/s]

 86%|████████▌ | 86392/100629 [1:07:49<08:30, 27.87it/s]

 86%|████████▌ | 86395/100629 [1:07:49<09:11, 25.81it/s]

 86%|████████▌ | 86401/100629 [1:07:49<07:39, 30.98it/s]

 86%|████████▌ | 86405/100629 [1:07:49<08:33, 27.70it/s]

 86%|████████▌ | 86408/100629 [1:07:49<08:28, 27.94it/s]

 86%|████████▌ | 86411/100629 [1:07:49<08:30, 27.84it/s]

 86%|████████▌ | 86414/100629 [1:07:50<08:44, 27.08it/s]

 86%|████████▌ | 86417/100629 [1:07:50<11:00, 21.52it/s]

 86%|████████▌ | 86420/100629 [1:07:50<11:22, 20.81it/s]

 86%|████████▌ | 86424/100629 [1:07:50<09:59, 23.69it/s]

 86%|████████▌ | 86427/100629 [1:07:50<11:49, 20.01it/s]

 86%|████████▌ | 86430/100629 [1:07:50<11:40, 20.27it/s]

 86%|████████▌ | 86433/100629 [1:07:51<13:23, 17.67it/s]

 86%|████████▌ | 86435/100629 [1:07:51<13:17, 17.79it/s]

 86%|████████▌ | 86438/100629 [1:07:51<12:33, 18.82it/s]

 86%|████████▌ | 86440/100629 [1:07:51<12:25, 19.02it/s]

 86%|████████▌ | 86443/100629 [1:07:51<10:57, 21.57it/s]

 86%|████████▌ | 86446/100629 [1:07:51<10:34, 22.36it/s]

 86%|████████▌ | 86449/100629 [1:07:51<10:48, 21.88it/s]

 86%|████████▌ | 86452/100629 [1:07:52<11:41, 20.22it/s]

 86%|████████▌ | 86455/100629 [1:07:52<11:38, 20.30it/s]

 86%|████████▌ | 86458/100629 [1:07:52<11:30, 20.53it/s]

 86%|████████▌ | 86461/100629 [1:07:52<10:24, 22.67it/s]

 86%|████████▌ | 86464/100629 [1:07:52<09:51, 23.95it/s]

 86%|████████▌ | 86467/100629 [1:07:52<09:37, 24.51it/s]

 86%|████████▌ | 86470/100629 [1:07:52<11:17, 20.91it/s]

 86%|████████▌ | 86473/100629 [1:07:52<11:15, 20.96it/s]

 86%|████████▌ | 86476/100629 [1:07:53<11:18, 20.87it/s]

 86%|████████▌ | 86479/100629 [1:07:53<11:10, 21.10it/s]

 86%|████████▌ | 86482/100629 [1:07:53<11:48, 19.97it/s]

 86%|████████▌ | 86486/100629 [1:07:53<09:52, 23.86it/s]

 86%|████████▌ | 86489/100629 [1:07:53<09:42, 24.26it/s]

 86%|████████▌ | 86492/100629 [1:07:53<09:57, 23.66it/s]

 86%|████████▌ | 86495/100629 [1:07:53<10:07, 23.28it/s]

 86%|████████▌ | 86500/100629 [1:07:54<09:05, 25.90it/s]

 86%|████████▌ | 86503/100629 [1:07:54<09:34, 24.58it/s]

 86%|████████▌ | 86506/100629 [1:07:54<09:13, 25.53it/s]

 86%|████████▌ | 86510/100629 [1:07:54<08:29, 27.69it/s]

 86%|████████▌ | 86514/100629 [1:07:54<08:07, 28.95it/s]

 86%|████████▌ | 86517/100629 [1:07:54<09:06, 25.84it/s]

 86%|████████▌ | 86520/100629 [1:07:54<10:45, 21.86it/s]

 86%|████████▌ | 86523/100629 [1:07:55<10:18, 22.82it/s]

 86%|████████▌ | 86526/100629 [1:07:55<10:45, 21.84it/s]

 86%|████████▌ | 86530/100629 [1:07:55<09:47, 23.99it/s]

 86%|████████▌ | 86533/100629 [1:07:55<10:21, 22.69it/s]

 86%|████████▌ | 86536/100629 [1:07:55<10:38, 22.08it/s]

 86%|████████▌ | 86539/100629 [1:07:55<10:46, 21.80it/s]

 86%|████████▌ | 86542/100629 [1:07:55<12:09, 19.31it/s]

 86%|████████▌ | 86545/100629 [1:07:56<10:56, 21.44it/s]

 86%|████████▌ | 86548/100629 [1:07:56<10:03, 23.33it/s]

 86%|████████▌ | 86551/100629 [1:07:56<09:46, 23.99it/s]

 86%|████████▌ | 86554/100629 [1:07:56<12:04, 19.43it/s]

 86%|████████▌ | 86557/100629 [1:07:56<11:27, 20.46it/s]

 86%|████████▌ | 86560/100629 [1:07:56<11:56, 19.64it/s]

 86%|████████▌ | 86563/100629 [1:07:56<12:29, 18.78it/s]

 86%|████████▌ | 86566/100629 [1:07:57<11:10, 20.99it/s]

 86%|████████▌ | 86569/100629 [1:07:57<11:05, 21.14it/s]

 86%|████████▌ | 86572/100629 [1:07:57<12:16, 19.08it/s]

 86%|████████▌ | 86575/100629 [1:07:57<12:51, 18.21it/s]

 86%|████████▌ | 86577/100629 [1:07:57<13:36, 17.22it/s]

 86%|████████▌ | 86580/100629 [1:07:57<12:08, 19.29it/s]

 86%|████████▌ | 86583/100629 [1:07:58<12:59, 18.02it/s]

 86%|████████▌ | 86586/100629 [1:07:58<13:20, 17.54it/s]

 86%|████████▌ | 86588/100629 [1:07:58<13:45, 17.01it/s]

 86%|████████▌ | 86590/100629 [1:07:58<14:17, 16.37it/s]

 86%|████████▌ | 86592/100629 [1:07:58<16:24, 14.26it/s]

 86%|████████▌ | 86596/100629 [1:07:58<12:31, 18.67it/s]

 86%|████████▌ | 86598/100629 [1:07:58<12:44, 18.36it/s]

 86%|████████▌ | 86601/100629 [1:07:59<11:47, 19.83it/s]

 86%|████████▌ | 86604/100629 [1:07:59<14:31, 16.10it/s]

 86%|████████▌ | 86608/100629 [1:07:59<11:15, 20.76it/s]

 86%|████████▌ | 86611/100629 [1:07:59<13:14, 17.64it/s]

 86%|████████▌ | 86614/100629 [1:07:59<12:19, 18.95it/s]

 86%|████████▌ | 86618/100629 [1:07:59<12:12, 19.14it/s]

 86%|████████▌ | 86621/100629 [1:08:00<11:14, 20.76it/s]

 86%|████████▌ | 86624/100629 [1:08:00<10:26, 22.34it/s]

 86%|████████▌ | 86627/100629 [1:08:00<12:06, 19.27it/s]

 86%|████████▌ | 86630/100629 [1:08:00<11:57, 19.51it/s]

 86%|████████▌ | 86633/100629 [1:08:00<12:13, 19.08it/s]

 86%|████████▌ | 86636/100629 [1:08:00<12:35, 18.53it/s]

 86%|████████▌ | 86638/100629 [1:08:01<13:53, 16.78it/s]

 86%|████████▌ | 86641/100629 [1:08:01<12:48, 18.20it/s]

 86%|████████▌ | 86643/100629 [1:08:01<13:38, 17.08it/s]

 86%|████████▌ | 86645/100629 [1:08:01<13:21, 17.45it/s]

 86%|████████▌ | 86647/100629 [1:08:01<13:47, 16.90it/s]

 86%|████████▌ | 86650/100629 [1:08:01<12:26, 18.72it/s]

 86%|████████▌ | 86653/100629 [1:08:01<11:42, 19.88it/s]

 86%|████████▌ | 86658/100629 [1:08:01<09:35, 24.29it/s]

 86%|████████▌ | 86665/100629 [1:08:02<06:38, 35.08it/s]

 86%|████████▌ | 86669/100629 [1:08:02<08:05, 28.77it/s]

 86%|████████▌ | 86673/100629 [1:08:02<09:04, 25.65it/s]

 86%|████████▌ | 86676/100629 [1:08:02<11:00, 21.14it/s]

 86%|████████▌ | 86679/100629 [1:08:02<11:07, 20.89it/s]

 86%|████████▌ | 86682/100629 [1:08:03<11:37, 19.99it/s]

 86%|████████▌ | 86685/100629 [1:08:03<10:53, 21.35it/s]

 86%|████████▌ | 86688/100629 [1:08:03<11:03, 21.00it/s]

 86%|████████▌ | 86691/100629 [1:08:03<10:47, 21.52it/s]

 86%|████████▌ | 86694/100629 [1:08:03<13:10, 17.62it/s]

 86%|████████▌ | 86696/100629 [1:08:03<13:00, 17.85it/s]

 86%|████████▌ | 86699/100629 [1:08:03<12:44, 18.22it/s]

 86%|████████▌ | 86701/100629 [1:08:04<13:13, 17.55it/s]

 86%|████████▌ | 86705/100629 [1:08:04<10:23, 22.33it/s]

 86%|████████▌ | 86708/100629 [1:08:04<10:02, 23.09it/s]

 86%|████████▌ | 86711/100629 [1:08:04<12:00, 19.33it/s]

 86%|████████▌ | 86714/100629 [1:08:04<13:12, 17.56it/s]

 86%|████████▌ | 86716/100629 [1:08:04<13:27, 17.24it/s]

 86%|████████▌ | 86718/100629 [1:08:04<14:35, 15.89it/s]

 86%|████████▌ | 86722/100629 [1:08:05<12:25, 18.66it/s]

 86%|████████▌ | 86725/100629 [1:08:05<11:10, 20.74it/s]

 86%|████████▌ | 86728/100629 [1:08:05<11:59, 19.33it/s]

 86%|████████▌ | 86731/100629 [1:08:05<12:16, 18.86it/s]

 86%|████████▌ | 86735/100629 [1:08:05<10:40, 21.68it/s]

 86%|████████▌ | 86738/100629 [1:08:05<10:06, 22.89it/s]

 86%|████████▌ | 86741/100629 [1:08:05<09:32, 24.27it/s]

 86%|████████▌ | 86744/100629 [1:08:06<10:16, 22.53it/s]

 86%|████████▌ | 86747/100629 [1:08:06<10:55, 21.17it/s]

 86%|████████▌ | 86750/100629 [1:08:06<11:15, 20.56it/s]

 86%|████████▌ | 86753/100629 [1:08:06<12:33, 18.43it/s]

 86%|████████▌ | 86756/100629 [1:08:06<11:57, 19.35it/s]

 86%|████████▌ | 86759/100629 [1:08:06<12:11, 18.95it/s]

 86%|████████▌ | 86761/100629 [1:08:07<15:01, 15.39it/s]

 86%|████████▌ | 86763/100629 [1:08:07<15:40, 14.74it/s]

 86%|████████▌ | 86766/100629 [1:08:07<13:00, 17.77it/s]

 86%|████████▌ | 86769/100629 [1:08:07<12:30, 18.48it/s]

 86%|████████▌ | 86772/100629 [1:08:07<11:59, 19.26it/s]

 86%|████████▌ | 86775/100629 [1:08:07<12:24, 18.60it/s]

 86%|████████▌ | 86778/100629 [1:08:07<11:59, 19.24it/s]

 86%|████████▌ | 86781/100629 [1:08:08<11:13, 20.55it/s]

 86%|████████▌ | 86785/100629 [1:08:08<10:11, 22.66it/s]

 86%|████████▌ | 86789/100629 [1:08:08<09:15, 24.91it/s]

 86%|████████▌ | 86792/100629 [1:08:08<10:14, 22.50it/s]

 86%|████████▋ | 86795/100629 [1:08:08<11:00, 20.95it/s]

 86%|████████▋ | 86799/100629 [1:08:08<10:22, 22.20it/s]

 86%|████████▋ | 86802/100629 [1:08:09<10:15, 22.47it/s]

 86%|████████▋ | 86805/100629 [1:08:09<13:18, 17.32it/s]

 86%|████████▋ | 86808/100629 [1:08:09<11:57, 19.28it/s]

 86%|████████▋ | 86811/100629 [1:08:09<11:07, 20.71it/s]

 86%|████████▋ | 86815/100629 [1:08:09<10:19, 22.29it/s]

 86%|████████▋ | 86818/100629 [1:08:09<10:13, 22.52it/s]

 86%|████████▋ | 86823/100629 [1:08:09<08:13, 28.00it/s]

 86%|████████▋ | 86826/100629 [1:08:10<08:27, 27.18it/s]

 86%|████████▋ | 86829/100629 [1:08:10<09:58, 23.07it/s]

 86%|████████▋ | 86833/100629 [1:08:10<09:01, 25.49it/s]

 86%|████████▋ | 86837/100629 [1:08:10<08:15, 27.84it/s]

 86%|████████▋ | 86840/100629 [1:08:10<08:06, 28.32it/s]

 86%|████████▋ | 86843/100629 [1:08:10<10:14, 22.44it/s]

 86%|████████▋ | 86846/100629 [1:08:10<11:50, 19.40it/s]

 86%|████████▋ | 86849/100629 [1:08:11<11:09, 20.58it/s]

 86%|████████▋ | 86853/100629 [1:08:11<09:24, 24.40it/s]

 86%|████████▋ | 86856/100629 [1:08:11<09:51, 23.28it/s]

 86%|████████▋ | 86859/100629 [1:08:11<12:04, 19.00it/s]

 86%|████████▋ | 86864/100629 [1:08:11<10:14, 22.38it/s]

 86%|████████▋ | 86867/100629 [1:08:11<10:39, 21.53it/s]

 86%|████████▋ | 86870/100629 [1:08:12<10:04, 22.75it/s]

 86%|████████▋ | 86874/100629 [1:08:12<09:04, 25.27it/s]

 86%|████████▋ | 86877/100629 [1:08:12<10:36, 21.59it/s]

 86%|████████▋ | 86880/100629 [1:08:12<10:20, 22.17it/s]

 86%|████████▋ | 86883/100629 [1:08:12<11:57, 19.16it/s]

 86%|████████▋ | 86886/100629 [1:08:12<11:33, 19.82it/s]

 86%|████████▋ | 86889/100629 [1:08:13<13:57, 16.40it/s]

 86%|████████▋ | 86891/100629 [1:08:13<14:58, 15.29it/s]

 86%|████████▋ | 86893/100629 [1:08:13<14:49, 15.44it/s]

 86%|████████▋ | 86895/100629 [1:08:13<17:26, 13.13it/s]

 86%|████████▋ | 86901/100629 [1:08:13<11:11, 20.43it/s]

 86%|████████▋ | 86904/100629 [1:08:13<10:46, 21.24it/s]

 86%|████████▋ | 86907/100629 [1:08:14<11:01, 20.74it/s]

 86%|████████▋ | 86911/100629 [1:08:14<10:11, 22.45it/s]

 86%|████████▋ | 86914/100629 [1:08:14<10:14, 22.33it/s]

 86%|████████▋ | 86917/100629 [1:08:14<09:53, 23.08it/s]

 86%|████████▋ | 86921/100629 [1:08:14<10:55, 20.92it/s]

 86%|████████▋ | 86924/100629 [1:08:14<10:18, 22.18it/s]

 86%|████████▋ | 86927/100629 [1:08:14<11:20, 20.12it/s]

 86%|████████▋ | 86932/100629 [1:08:15<09:52, 23.13it/s]

 86%|████████▋ | 86935/100629 [1:08:15<09:57, 22.92it/s]

 86%|████████▋ | 86938/100629 [1:08:15<13:27, 16.96it/s]

 86%|████████▋ | 86941/100629 [1:08:15<12:41, 17.98it/s]

 86%|████████▋ | 86944/100629 [1:08:15<12:06, 18.84it/s]

 86%|████████▋ | 86947/100629 [1:08:16<12:34, 18.13it/s]

 86%|████████▋ | 86952/100629 [1:08:16<09:51, 23.13it/s]

 86%|████████▋ | 86955/100629 [1:08:16<11:00, 20.71it/s]

 86%|████████▋ | 86958/100629 [1:08:16<12:34, 18.12it/s]

 86%|████████▋ | 86961/100629 [1:08:16<11:38, 19.57it/s]

 86%|████████▋ | 86964/100629 [1:08:16<11:50, 19.25it/s]

 86%|████████▋ | 86968/100629 [1:08:16<10:23, 21.90it/s]

 86%|████████▋ | 86971/100629 [1:08:17<10:12, 22.32it/s]

 86%|████████▋ | 86974/100629 [1:08:17<11:18, 20.14it/s]

 86%|████████▋ | 86977/100629 [1:08:17<11:08, 20.42it/s]

 86%|████████▋ | 86980/100629 [1:08:17<11:19, 20.10it/s]

 86%|████████▋ | 86983/100629 [1:08:17<10:46, 21.12it/s]

 86%|████████▋ | 86986/100629 [1:08:17<10:23, 21.87it/s]

 86%|████████▋ | 86989/100629 [1:08:17<10:42, 21.23it/s]

 86%|████████▋ | 86992/100629 [1:08:18<10:56, 20.78it/s]

 86%|████████▋ | 86996/100629 [1:08:18<09:43, 23.35it/s]

 86%|████████▋ | 87000/100629 [1:08:18<09:10, 24.74it/s]

 86%|████████▋ | 87003/100629 [1:08:18<10:18, 22.03it/s]

 86%|████████▋ | 87006/100629 [1:08:18<09:52, 22.99it/s]

 86%|████████▋ | 87009/100629 [1:08:18<11:05, 20.47it/s]

 86%|████████▋ | 87012/100629 [1:08:19<10:50, 20.93it/s]

 86%|████████▋ | 87016/100629 [1:08:19<10:23, 21.82it/s]

 86%|████████▋ | 87019/100629 [1:08:19<10:09, 22.32it/s]

 86%|████████▋ | 87023/100629 [1:08:19<09:32, 23.77it/s]

 86%|████████▋ | 87026/100629 [1:08:19<09:51, 23.00it/s]

 86%|████████▋ | 87029/100629 [1:08:19<10:27, 21.67it/s]

 86%|████████▋ | 87032/100629 [1:08:19<10:28, 21.65it/s]

 86%|████████▋ | 87036/100629 [1:08:20<08:51, 25.59it/s]

 86%|████████▋ | 87039/100629 [1:08:20<08:47, 25.74it/s]

 86%|████████▋ | 87042/100629 [1:08:20<08:44, 25.93it/s]

 87%|████████▋ | 87045/100629 [1:08:20<09:47, 23.10it/s]

 87%|████████▋ | 87048/100629 [1:08:20<09:32, 23.71it/s]

 87%|████████▋ | 87051/100629 [1:08:20<10:12, 22.16it/s]

 87%|████████▋ | 87054/100629 [1:08:20<10:45, 21.03it/s]

 87%|████████▋ | 87057/100629 [1:08:21<11:30, 19.67it/s]

 87%|████████▋ | 87061/100629 [1:08:21<09:53, 22.86it/s]

 87%|████████▋ | 87064/100629 [1:08:21<09:24, 24.01it/s]

 87%|████████▋ | 87068/100629 [1:08:21<08:52, 25.47it/s]

 87%|████████▋ | 87073/100629 [1:08:21<07:50, 28.80it/s]

 87%|████████▋ | 87076/100629 [1:08:21<08:33, 26.37it/s]

 87%|████████▋ | 87080/100629 [1:08:21<08:22, 26.99it/s]

 87%|████████▋ | 87084/100629 [1:08:21<08:38, 26.11it/s]

 87%|████████▋ | 87088/100629 [1:08:22<07:54, 28.51it/s]

 87%|████████▋ | 87091/100629 [1:08:22<09:40, 23.32it/s]

 87%|████████▋ | 87094/100629 [1:08:22<10:38, 21.20it/s]

 87%|████████▋ | 87097/100629 [1:08:22<10:50, 20.79it/s]

 87%|████████▋ | 87100/100629 [1:08:22<11:51, 19.01it/s]

 87%|████████▋ | 87102/100629 [1:08:22<12:22, 18.21it/s]

 87%|████████▋ | 87106/100629 [1:08:23<10:40, 21.12it/s]

 87%|████████▋ | 87109/100629 [1:08:23<10:20, 21.79it/s]

 87%|████████▋ | 87112/100629 [1:08:23<10:31, 21.41it/s]

 87%|████████▋ | 87115/100629 [1:08:23<10:41, 21.05it/s]

 87%|████████▋ | 87118/100629 [1:08:23<11:28, 19.61it/s]

 87%|████████▋ | 87120/100629 [1:08:23<12:39, 17.78it/s]

 87%|████████▋ | 87122/100629 [1:08:23<13:13, 17.03it/s]

 87%|████████▋ | 87124/100629 [1:08:24<13:09, 17.11it/s]

 87%|████████▋ | 87126/100629 [1:08:24<12:45, 17.64it/s]

 87%|████████▋ | 87128/100629 [1:08:24<18:33, 12.12it/s]

 87%|████████▋ | 87130/100629 [1:08:24<17:07, 13.14it/s]

 87%|████████▋ | 87133/100629 [1:08:24<13:52, 16.22it/s]

 87%|████████▋ | 87136/100629 [1:08:24<12:41, 17.71it/s]

 87%|████████▋ | 87139/100629 [1:08:24<11:33, 19.45it/s]

 87%|████████▋ | 87142/100629 [1:08:25<11:45, 19.11it/s]

 87%|████████▋ | 87146/100629 [1:08:25<11:05, 20.25it/s]

 87%|████████▋ | 87150/100629 [1:08:25<09:44, 23.05it/s]

 87%|████████▋ | 87153/100629 [1:08:25<11:21, 19.77it/s]

 87%|████████▋ | 87156/100629 [1:08:25<10:27, 21.47it/s]

 87%|████████▋ | 87159/100629 [1:08:25<10:07, 22.17it/s]

 87%|████████▋ | 87162/100629 [1:08:26<11:16, 19.91it/s]

 87%|████████▋ | 87166/100629 [1:08:26<09:23, 23.87it/s]

 87%|████████▋ | 87169/100629 [1:08:26<11:18, 19.84it/s]

 87%|████████▋ | 87172/100629 [1:08:26<11:32, 19.44it/s]

 87%|████████▋ | 87177/100629 [1:08:26<10:05, 22.23it/s]

 87%|████████▋ | 87180/100629 [1:08:26<10:10, 22.04it/s]

 87%|████████▋ | 87183/100629 [1:08:27<11:54, 18.83it/s]

 87%|████████▋ | 87188/100629 [1:08:27<09:43, 23.03it/s]

 87%|████████▋ | 87191/100629 [1:08:27<10:09, 22.05it/s]

 87%|████████▋ | 87194/100629 [1:08:27<09:28, 23.62it/s]

 87%|████████▋ | 87197/100629 [1:08:27<09:10, 24.38it/s]

 87%|████████▋ | 87200/100629 [1:08:27<09:17, 24.10it/s]

 87%|████████▋ | 87203/100629 [1:08:27<09:38, 23.20it/s]

 87%|████████▋ | 87206/100629 [1:08:28<09:46, 22.87it/s]

 87%|████████▋ | 87209/100629 [1:08:28<10:22, 21.57it/s]

 87%|████████▋ | 87214/100629 [1:08:28<08:53, 25.12it/s]

 87%|████████▋ | 87217/100629 [1:08:28<10:34, 21.14it/s]

 87%|████████▋ | 87221/100629 [1:08:28<10:07, 22.06it/s]

 87%|████████▋ | 87224/100629 [1:08:28<09:27, 23.63it/s]

 87%|████████▋ | 87227/100629 [1:08:28<10:21, 21.57it/s]

 87%|████████▋ | 87230/100629 [1:08:29<10:41, 20.90it/s]

 87%|████████▋ | 87233/100629 [1:08:29<11:21, 19.64it/s]

 87%|████████▋ | 87237/100629 [1:08:29<10:04, 22.14it/s]

 87%|████████▋ | 87242/100629 [1:08:29<08:50, 25.22it/s]

 87%|████████▋ | 87245/100629 [1:08:29<09:33, 23.35it/s]

 87%|████████▋ | 87248/100629 [1:08:29<09:17, 24.00it/s]

 87%|████████▋ | 87251/100629 [1:08:30<10:31, 21.17it/s]

 87%|████████▋ | 87255/100629 [1:08:30<09:32, 23.37it/s]

 87%|████████▋ | 87258/100629 [1:08:30<09:15, 24.08it/s]

 87%|████████▋ | 87261/100629 [1:08:30<10:15, 21.73it/s]

 87%|████████▋ | 87264/100629 [1:08:30<09:55, 22.45it/s]

 87%|████████▋ | 87267/100629 [1:08:30<11:39, 19.11it/s]

 87%|████████▋ | 87270/100629 [1:08:30<11:06, 20.04it/s]

 87%|████████▋ | 87273/100629 [1:08:31<11:52, 18.75it/s]

 87%|████████▋ | 87275/100629 [1:08:31<15:24, 14.44it/s]

 87%|████████▋ | 87280/100629 [1:08:31<12:06, 18.37it/s]

 87%|████████▋ | 87282/100629 [1:08:31<12:28, 17.84it/s]

 87%|████████▋ | 87285/100629 [1:08:31<11:17, 19.68it/s]

 87%|████████▋ | 87288/100629 [1:08:31<11:28, 19.39it/s]

 87%|████████▋ | 87291/100629 [1:08:32<10:58, 20.27it/s]

 87%|████████▋ | 87296/100629 [1:08:32<08:37, 25.76it/s]

 87%|████████▋ | 87299/100629 [1:08:32<08:33, 25.98it/s]

 87%|████████▋ | 87302/100629 [1:08:32<10:32, 21.06it/s]

 87%|████████▋ | 87307/100629 [1:08:32<08:16, 26.85it/s]

 87%|████████▋ | 87311/100629 [1:08:32<07:33, 29.39it/s]

 87%|████████▋ | 87315/100629 [1:08:32<08:32, 25.97it/s]

 87%|████████▋ | 87318/100629 [1:08:33<09:18, 23.82it/s]

 87%|████████▋ | 87321/100629 [1:08:33<09:38, 23.01it/s]

 87%|████████▋ | 87325/100629 [1:08:33<08:39, 25.63it/s]

 87%|████████▋ | 87328/100629 [1:08:33<09:07, 24.31it/s]

 87%|████████▋ | 87331/100629 [1:08:33<10:35, 20.92it/s]

 87%|████████▋ | 87335/100629 [1:08:33<09:20, 23.71it/s]

 87%|████████▋ | 87338/100629 [1:08:33<09:39, 22.94it/s]

 87%|████████▋ | 87341/100629 [1:08:34<10:41, 20.71it/s]

 87%|████████▋ | 87344/100629 [1:08:34<10:33, 20.97it/s]

 87%|████████▋ | 87347/100629 [1:08:34<10:37, 20.83it/s]

 87%|████████▋ | 87350/100629 [1:08:34<11:33, 19.14it/s]

 87%|████████▋ | 87353/100629 [1:08:34<10:45, 20.56it/s]

 87%|████████▋ | 87356/100629 [1:08:34<10:24, 21.26it/s]

 87%|████████▋ | 87359/100629 [1:08:34<09:45, 22.67it/s]

 87%|████████▋ | 87363/100629 [1:08:35<09:36, 23.01it/s]

 87%|████████▋ | 87366/100629 [1:08:35<11:40, 18.93it/s]

 87%|████████▋ | 87369/100629 [1:08:35<11:27, 19.30it/s]

 87%|████████▋ | 87372/100629 [1:08:35<10:54, 20.26it/s]

 87%|████████▋ | 87375/100629 [1:08:35<10:14, 21.56it/s]

 87%|████████▋ | 87379/100629 [1:08:35<09:58, 22.13it/s]

 87%|████████▋ | 87382/100629 [1:08:36<11:07, 19.84it/s]

 87%|████████▋ | 87385/100629 [1:08:36<10:36, 20.81it/s]

 87%|████████▋ | 87388/100629 [1:08:36<11:07, 19.84it/s]

 87%|████████▋ | 87391/100629 [1:08:36<10:43, 20.59it/s]

 87%|████████▋ | 87394/100629 [1:08:36<10:59, 20.08it/s]

 87%|████████▋ | 87397/100629 [1:08:36<10:19, 21.35it/s]

 87%|████████▋ | 87400/100629 [1:08:36<09:56, 22.18it/s]

 87%|████████▋ | 87403/100629 [1:08:37<09:39, 22.81it/s]

 87%|████████▋ | 87407/100629 [1:08:37<08:38, 25.48it/s]

 87%|████████▋ | 87410/100629 [1:08:37<09:16, 23.77it/s]

 87%|████████▋ | 87413/100629 [1:08:37<10:27, 21.06it/s]

 87%|████████▋ | 87416/100629 [1:08:37<10:28, 21.02it/s]

 87%|████████▋ | 87420/100629 [1:08:37<08:58, 24.55it/s]

 87%|████████▋ | 87423/100629 [1:08:37<10:12, 21.55it/s]

 87%|████████▋ | 87426/100629 [1:08:38<11:50, 18.58it/s]

 87%|████████▋ | 87429/100629 [1:08:38<12:31, 17.57it/s]

 87%|████████▋ | 87431/100629 [1:08:38<13:15, 16.59it/s]

 87%|████████▋ | 87434/100629 [1:08:38<12:08, 18.11it/s]

 87%|████████▋ | 87436/100629 [1:08:38<12:48, 17.17it/s]

 87%|████████▋ | 87438/100629 [1:08:38<12:53, 17.04it/s]

 87%|████████▋ | 87441/100629 [1:08:39<12:35, 17.45it/s]

 87%|████████▋ | 87443/100629 [1:08:39<12:42, 17.29it/s]

 87%|████████▋ | 87446/100629 [1:08:39<11:40, 18.82it/s]

 87%|████████▋ | 87449/100629 [1:08:39<11:00, 19.95it/s]

 87%|████████▋ | 87452/100629 [1:08:39<11:26, 19.20it/s]

 87%|████████▋ | 87455/100629 [1:08:39<10:11, 21.56it/s]

 87%|████████▋ | 87459/100629 [1:08:39<08:35, 25.57it/s]

 87%|████████▋ | 87462/100629 [1:08:40<09:12, 23.83it/s]

 87%|████████▋ | 87465/100629 [1:08:40<10:07, 21.66it/s]

 87%|████████▋ | 87468/100629 [1:08:40<10:20, 21.22it/s]

 87%|████████▋ | 87471/100629 [1:08:40<10:13, 21.46it/s]

 87%|████████▋ | 87474/100629 [1:08:40<10:14, 21.41it/s]

 87%|████████▋ | 87477/100629 [1:08:40<11:32, 19.00it/s]

 87%|████████▋ | 87481/100629 [1:08:41<11:20, 19.31it/s]

 87%|████████▋ | 87484/100629 [1:08:41<10:35, 20.67it/s]

 87%|████████▋ | 87487/100629 [1:08:41<10:38, 20.58it/s]

 87%|████████▋ | 87490/100629 [1:08:41<15:21, 14.26it/s]

 87%|████████▋ | 87493/100629 [1:08:41<13:40, 16.01it/s]

 87%|████████▋ | 87495/100629 [1:08:41<15:17, 14.31it/s]

 87%|████████▋ | 87498/100629 [1:08:42<13:25, 16.30it/s]

 87%|████████▋ | 87501/100629 [1:08:42<12:08, 18.03it/s]

 87%|████████▋ | 87504/100629 [1:08:42<10:39, 20.53it/s]

 87%|████████▋ | 87507/100629 [1:08:42<11:45, 18.61it/s]

 87%|████████▋ | 87510/100629 [1:08:42<12:06, 18.06it/s]

 87%|████████▋ | 87512/100629 [1:08:42<12:03, 18.14it/s]

 87%|████████▋ | 87515/100629 [1:08:42<10:55, 20.02it/s]

 87%|████████▋ | 87518/100629 [1:08:43<11:46, 18.57it/s]

 87%|████████▋ | 87521/100629 [1:08:43<10:40, 20.46it/s]

 87%|████████▋ | 87524/100629 [1:08:43<10:07, 21.57it/s]

 87%|████████▋ | 87527/100629 [1:08:43<10:09, 21.50it/s]

 87%|████████▋ | 87531/100629 [1:08:43<09:47, 22.30it/s]

 87%|████████▋ | 87534/100629 [1:08:43<10:02, 21.74it/s]

 87%|████████▋ | 87537/100629 [1:08:43<11:10, 19.54it/s]

 87%|████████▋ | 87540/100629 [1:08:44<12:23, 17.61it/s]

 87%|████████▋ | 87542/100629 [1:08:44<13:48, 15.80it/s]

 87%|████████▋ | 87544/100629 [1:08:44<14:38, 14.90it/s]

 87%|████████▋ | 87548/100629 [1:08:44<11:05, 19.66it/s]

 87%|████████▋ | 87551/100629 [1:08:44<10:10, 21.41it/s]

 87%|████████▋ | 87554/100629 [1:08:44<10:12, 21.34it/s]

 87%|████████▋ | 87557/100629 [1:08:45<09:39, 22.55it/s]

 87%|████████▋ | 87561/100629 [1:08:45<09:31, 22.85it/s]

 87%|████████▋ | 87564/100629 [1:08:45<09:05, 23.95it/s]

 87%|████████▋ | 87567/100629 [1:08:45<08:55, 24.41it/s]

 87%|████████▋ | 87570/100629 [1:08:45<09:09, 23.77it/s]

 87%|████████▋ | 87573/100629 [1:08:45<09:31, 22.85it/s]

 87%|████████▋ | 87576/100629 [1:08:45<10:05, 21.54it/s]

 87%|████████▋ | 87580/100629 [1:08:46<09:35, 22.69it/s]

 87%|████████▋ | 87583/100629 [1:08:46<08:57, 24.26it/s]

 87%|████████▋ | 87586/100629 [1:08:46<09:37, 22.58it/s]

 87%|████████▋ | 87591/100629 [1:08:46<09:46, 22.24it/s]

 87%|████████▋ | 87594/100629 [1:08:46<10:28, 20.74it/s]

 87%|████████▋ | 87597/100629 [1:08:46<10:33, 20.59it/s]

 87%|████████▋ | 87601/100629 [1:08:46<08:53, 24.43it/s]

 87%|████████▋ | 87604/100629 [1:08:47<08:28, 25.61it/s]

 87%|████████▋ | 87607/100629 [1:08:47<08:28, 25.60it/s]

 87%|████████▋ | 87610/100629 [1:08:47<08:42, 24.91it/s]

 87%|████████▋ | 87613/100629 [1:08:47<08:51, 24.48it/s]

 87%|████████▋ | 87618/100629 [1:08:47<08:33, 25.31it/s]

 87%|████████▋ | 87621/100629 [1:08:47<08:54, 24.33it/s]

 87%|████████▋ | 87624/100629 [1:08:47<08:48, 24.61it/s]

 87%|████████▋ | 87628/100629 [1:08:47<07:42, 28.14it/s]

 87%|████████▋ | 87631/100629 [1:08:48<07:42, 28.08it/s]

 87%|████████▋ | 87634/100629 [1:08:48<09:33, 22.67it/s]

 87%|████████▋ | 87637/100629 [1:08:48<09:07, 23.74it/s]

 87%|████████▋ | 87640/100629 [1:08:48<09:22, 23.07it/s]

 87%|████████▋ | 87644/100629 [1:08:48<09:24, 23.02it/s]

 87%|████████▋ | 87647/100629 [1:08:48<09:55, 21.78it/s]

 87%|████████▋ | 87650/100629 [1:08:48<09:51, 21.93it/s]

 87%|████████▋ | 87654/100629 [1:08:49<08:39, 24.97it/s]

 87%|████████▋ | 87657/100629 [1:08:49<10:02, 21.53it/s]

 87%|████████▋ | 87660/100629 [1:08:49<10:17, 21.00it/s]

 87%|████████▋ | 87663/100629 [1:08:49<10:54, 19.82it/s]

 87%|████████▋ | 87666/100629 [1:08:49<11:13, 19.25it/s]

 87%|████████▋ | 87668/100629 [1:08:49<12:07, 17.82it/s]

 87%|████████▋ | 87671/100629 [1:08:50<11:28, 18.81it/s]

 87%|████████▋ | 87674/100629 [1:08:50<11:16, 19.15it/s]

 87%|████████▋ | 87676/100629 [1:08:50<11:46, 18.33it/s]

 87%|████████▋ | 87678/100629 [1:08:50<12:23, 17.41it/s]

 87%|████████▋ | 87680/100629 [1:08:50<12:39, 17.06it/s]

 87%|████████▋ | 87683/100629 [1:08:50<12:18, 17.53it/s]

 87%|████████▋ | 87686/100629 [1:08:50<11:10, 19.30it/s]

 87%|████████▋ | 87688/100629 [1:08:51<14:46, 14.60it/s]

 87%|████████▋ | 87690/100629 [1:08:51<15:04, 14.30it/s]

 87%|████████▋ | 87692/100629 [1:08:51<15:31, 13.88it/s]

 87%|████████▋ | 87694/100629 [1:08:51<14:14, 15.15it/s]

 87%|████████▋ | 87696/100629 [1:08:51<14:08, 15.25it/s]

 87%|████████▋ | 87699/100629 [1:08:51<12:33, 17.15it/s]

 87%|████████▋ | 87701/100629 [1:08:51<14:51, 14.51it/s]

 87%|████████▋ | 87704/100629 [1:08:52<12:35, 17.10it/s]

 87%|████████▋ | 87706/100629 [1:08:52<12:23, 17.39it/s]

 87%|████████▋ | 87709/100629 [1:08:52<12:30, 17.22it/s]

 87%|████████▋ | 87713/100629 [1:08:52<10:17, 20.91it/s]

 87%|████████▋ | 87716/100629 [1:08:52<11:21, 18.95it/s]

 87%|████████▋ | 87719/100629 [1:08:52<10:34, 20.36it/s]

 87%|████████▋ | 87722/100629 [1:08:52<10:30, 20.46it/s]

 87%|████████▋ | 87725/100629 [1:08:53<11:41, 18.40it/s]

 87%|████████▋ | 87728/100629 [1:08:53<10:29, 20.50it/s]

 87%|████████▋ | 87733/100629 [1:08:53<08:25, 25.53it/s]

 87%|████████▋ | 87736/100629 [1:08:53<09:53, 21.71it/s]

 87%|████████▋ | 87739/100629 [1:08:53<09:13, 23.28it/s]

 87%|████████▋ | 87742/100629 [1:08:53<10:27, 20.52it/s]

 87%|████████▋ | 87745/100629 [1:08:54<10:40, 20.11it/s]

 87%|████████▋ | 87750/100629 [1:08:54<08:36, 24.91it/s]

 87%|████████▋ | 87753/100629 [1:08:54<08:22, 25.60it/s]

 87%|████████▋ | 87758/100629 [1:08:54<07:13, 29.70it/s]

 87%|████████▋ | 87762/100629 [1:08:54<08:07, 26.38it/s]

 87%|████████▋ | 87765/100629 [1:08:54<09:16, 23.11it/s]

 87%|████████▋ | 87768/100629 [1:08:54<10:13, 20.96it/s]

 87%|████████▋ | 87772/100629 [1:08:55<09:13, 23.23it/s]

 87%|████████▋ | 87775/100629 [1:08:55<09:08, 23.44it/s]

 87%|████████▋ | 87778/100629 [1:08:55<09:10, 23.35it/s]

 87%|████████▋ | 87781/100629 [1:08:55<10:28, 20.43it/s]

 87%|████████▋ | 87785/100629 [1:08:55<09:04, 23.58it/s]

 87%|████████▋ | 87788/100629 [1:08:55<09:20, 22.89it/s]

 87%|████████▋ | 87791/100629 [1:08:56<11:04, 19.32it/s]

 87%|████████▋ | 87794/100629 [1:08:56<11:20, 18.85it/s]

 87%|████████▋ | 87797/100629 [1:08:56<11:03, 19.35it/s]

 87%|████████▋ | 87801/100629 [1:08:56<09:40, 22.10it/s]

 87%|████████▋ | 87804/100629 [1:08:56<09:27, 22.62it/s]

 87%|████████▋ | 87807/100629 [1:08:56<08:51, 24.12it/s]

 87%|████████▋ | 87810/100629 [1:08:56<09:35, 22.28it/s]

 87%|████████▋ | 87814/100629 [1:08:57<08:38, 24.72it/s]

 87%|████████▋ | 87817/100629 [1:08:57<09:06, 23.45it/s]

 87%|████████▋ | 87820/100629 [1:08:57<09:15, 23.06it/s]

 87%|████████▋ | 87823/100629 [1:08:57<10:05, 21.13it/s]

 87%|████████▋ | 87827/100629 [1:08:57<09:04, 23.53it/s]

 87%|████████▋ | 87831/100629 [1:08:57<08:27, 25.21it/s]

 87%|████████▋ | 87834/100629 [1:08:57<09:30, 22.42it/s]

 87%|████████▋ | 87837/100629 [1:08:58<12:32, 17.00it/s]

 87%|████████▋ | 87841/100629 [1:08:58<10:37, 20.05it/s]

 87%|████████▋ | 87845/100629 [1:08:58<09:04, 23.46it/s]

 87%|████████▋ | 87848/100629 [1:08:58<10:17, 20.71it/s]

 87%|████████▋ | 87851/100629 [1:08:58<09:58, 21.36it/s]

 87%|████████▋ | 87855/100629 [1:08:58<09:25, 22.60it/s]

 87%|████████▋ | 87858/100629 [1:08:59<09:06, 23.37it/s]

 87%|████████▋ | 87861/100629 [1:08:59<09:54, 21.49it/s]

 87%|████████▋ | 87865/100629 [1:08:59<09:18, 22.85it/s]

 87%|████████▋ | 87868/100629 [1:08:59<08:43, 24.36it/s]

 87%|████████▋ | 87871/100629 [1:08:59<08:51, 23.99it/s]

 87%|████████▋ | 87874/100629 [1:08:59<09:33, 22.23it/s]

 87%|████████▋ | 87879/100629 [1:08:59<08:08, 26.11it/s]

 87%|████████▋ | 87882/100629 [1:08:59<07:57, 26.71it/s]

 87%|████████▋ | 87885/100629 [1:09:00<09:30, 22.34it/s]

 87%|████████▋ | 87890/100629 [1:09:00<07:36, 27.93it/s]

 87%|████████▋ | 87894/100629 [1:09:00<07:31, 28.22it/s]

 87%|████████▋ | 87898/100629 [1:09:00<07:03, 30.08it/s]

 87%|████████▋ | 87902/100629 [1:09:00<07:32, 28.12it/s]

 87%|████████▋ | 87905/100629 [1:09:00<07:45, 27.31it/s]

 87%|████████▋ | 87908/100629 [1:09:00<07:45, 27.35it/s]

 87%|████████▋ | 87911/100629 [1:09:01<07:48, 27.16it/s]

 87%|████████▋ | 87914/100629 [1:09:01<07:47, 27.22it/s]

 87%|████████▋ | 87917/100629 [1:09:01<09:21, 22.66it/s]

 87%|████████▋ | 87920/100629 [1:09:01<11:38, 18.20it/s]

 87%|████████▋ | 87924/100629 [1:09:01<10:26, 20.28it/s]

 87%|████████▋ | 87927/100629 [1:09:01<10:21, 20.44it/s]

 87%|████████▋ | 87930/100629 [1:09:02<11:15, 18.80it/s]

 87%|████████▋ | 87932/100629 [1:09:02<11:19, 18.68it/s]

 87%|████████▋ | 87934/100629 [1:09:02<11:54, 17.76it/s]

 87%|████████▋ | 87938/100629 [1:09:02<09:35, 22.03it/s]

 87%|████████▋ | 87941/100629 [1:09:02<13:00, 16.25it/s]

 87%|████████▋ | 87944/100629 [1:09:02<12:16, 17.23it/s]

 87%|████████▋ | 87947/100629 [1:09:03<11:23, 18.55it/s]

 87%|████████▋ | 87950/100629 [1:09:03<10:58, 19.25it/s]

 87%|████████▋ | 87953/100629 [1:09:03<14:02, 15.05it/s]

 87%|████████▋ | 87955/100629 [1:09:03<15:10, 13.92it/s]

 87%|████████▋ | 87957/100629 [1:09:03<14:42, 14.36it/s]

 87%|████████▋ | 87959/100629 [1:09:03<13:42, 15.41it/s]

 87%|████████▋ | 87962/100629 [1:09:04<14:07, 14.94it/s]

 87%|████████▋ | 87964/100629 [1:09:04<13:33, 15.57it/s]

 87%|████████▋ | 87966/100629 [1:09:04<13:02, 16.17it/s]

 87%|████████▋ | 87968/100629 [1:09:04<13:19, 15.83it/s]

 87%|████████▋ | 87973/100629 [1:09:04<09:02, 23.34it/s]

 87%|████████▋ | 87976/100629 [1:09:04<10:02, 21.02it/s]

 87%|████████▋ | 87979/100629 [1:09:04<09:13, 22.86it/s]

 87%|████████▋ | 87982/100629 [1:09:04<08:50, 23.85it/s]

 87%|████████▋ | 87985/100629 [1:09:05<09:05, 23.19it/s]

 87%|████████▋ | 87989/100629 [1:09:05<08:15, 25.49it/s]

 87%|████████▋ | 87992/100629 [1:09:05<09:21, 22.50it/s]

 87%|████████▋ | 87995/100629 [1:09:05<09:25, 22.33it/s]

 87%|████████▋ | 87998/100629 [1:09:05<08:56, 23.53it/s]

 87%|████████▋ | 88003/100629 [1:09:05<07:33, 27.81it/s]

 87%|████████▋ | 88008/100629 [1:09:05<06:53, 30.53it/s]

 87%|████████▋ | 88012/100629 [1:09:06<07:47, 27.00it/s]

 87%|████████▋ | 88016/100629 [1:09:06<07:12, 29.19it/s]

 87%|████████▋ | 88020/100629 [1:09:06<07:34, 27.73it/s]

 87%|████████▋ | 88023/100629 [1:09:06<07:47, 26.97it/s]

 87%|████████▋ | 88026/100629 [1:09:06<08:41, 24.18it/s]

 87%|████████▋ | 88029/100629 [1:09:06<09:21, 22.46it/s]

 87%|████████▋ | 88033/100629 [1:09:06<08:40, 24.22it/s]

 87%|████████▋ | 88037/100629 [1:09:07<07:38, 27.45it/s]

 87%|████████▋ | 88040/100629 [1:09:07<10:23, 20.20it/s]

 87%|████████▋ | 88044/100629 [1:09:07<09:10, 22.87it/s]

 87%|████████▋ | 88047/100629 [1:09:07<10:33, 19.86it/s]

 88%|████████▊ | 88051/100629 [1:09:07<10:50, 19.34it/s]

 88%|████████▊ | 88054/100629 [1:09:07<10:06, 20.72it/s]

 88%|████████▊ | 88057/100629 [1:09:08<09:57, 21.04it/s]

 88%|████████▊ | 88060/100629 [1:09:08<09:32, 21.96it/s]

 88%|████████▊ | 88063/100629 [1:09:08<11:00, 19.01it/s]

 88%|████████▊ | 88066/100629 [1:09:08<12:21, 16.95it/s]

 88%|████████▊ | 88071/100629 [1:09:08<09:36, 21.78it/s]

 88%|████████▊ | 88074/100629 [1:09:08<09:27, 22.11it/s]

 88%|████████▊ | 88077/100629 [1:09:09<09:49, 21.31it/s]

 88%|████████▊ | 88080/100629 [1:09:09<09:38, 21.69it/s]

 88%|████████▊ | 88084/100629 [1:09:09<09:06, 22.94it/s]

 88%|████████▊ | 88088/100629 [1:09:09<08:14, 25.36it/s]

 88%|████████▊ | 88091/100629 [1:09:09<08:43, 23.97it/s]

 88%|████████▊ | 88094/100629 [1:09:09<08:31, 24.50it/s]

 88%|████████▊ | 88098/100629 [1:09:09<07:56, 26.29it/s]

 88%|████████▊ | 88101/100629 [1:09:09<07:42, 27.11it/s]

 88%|████████▊ | 88104/100629 [1:09:10<08:10, 25.53it/s]

 88%|████████▊ | 88107/100629 [1:09:10<08:42, 23.97it/s]

 88%|████████▊ | 88110/100629 [1:09:10<10:37, 19.63it/s]

 88%|████████▊ | 88113/100629 [1:09:10<10:09, 20.54it/s]

 88%|████████▊ | 88116/100629 [1:09:10<11:02, 18.89it/s]

 88%|████████▊ | 88119/100629 [1:09:10<10:15, 20.33it/s]

 88%|████████▊ | 88122/100629 [1:09:11<11:21, 18.35it/s]

 88%|████████▊ | 88126/100629 [1:09:11<09:19, 22.35it/s]

 88%|████████▊ | 88129/100629 [1:09:11<09:44, 21.39it/s]

 88%|████████▊ | 88132/100629 [1:09:11<10:07, 20.57it/s]

 88%|████████▊ | 88135/100629 [1:09:11<12:06, 17.21it/s]

 88%|████████▊ | 88138/100629 [1:09:11<10:53, 19.11it/s]

 88%|████████▊ | 88142/100629 [1:09:12<09:45, 21.34it/s]

 88%|████████▊ | 88146/100629 [1:09:12<08:21, 24.92it/s]

 88%|████████▊ | 88149/100629 [1:09:12<10:10, 20.44it/s]

 88%|████████▊ | 88152/100629 [1:09:12<09:38, 21.57it/s]

 88%|████████▊ | 88155/100629 [1:09:12<10:01, 20.72it/s]

 88%|████████▊ | 88158/100629 [1:09:12<12:10, 17.07it/s]

 88%|████████▊ | 88161/100629 [1:09:13<13:32, 15.35it/s]

 88%|████████▊ | 88164/100629 [1:09:13<12:09, 17.08it/s]

 88%|████████▊ | 88166/100629 [1:09:13<13:30, 15.38it/s]

 88%|████████▊ | 88168/100629 [1:09:13<13:21, 15.56it/s]

 88%|████████▊ | 88171/100629 [1:09:13<11:36, 17.89it/s]

 88%|████████▊ | 88174/100629 [1:09:13<10:43, 19.37it/s]

 88%|████████▊ | 88177/100629 [1:09:13<10:04, 20.59it/s]

 88%|████████▊ | 88181/100629 [1:09:14<08:44, 23.72it/s]

 88%|████████▊ | 88184/100629 [1:09:14<09:01, 22.98it/s]

 88%|████████▊ | 88188/100629 [1:09:14<10:00, 20.73it/s]

 88%|████████▊ | 88191/100629 [1:09:14<10:57, 18.91it/s]

 88%|████████▊ | 88196/100629 [1:09:14<08:43, 23.73it/s]

 88%|████████▊ | 88199/100629 [1:09:15<15:27, 13.40it/s]

 88%|████████▊ | 88202/100629 [1:09:15<13:44, 15.08it/s]

 88%|████████▊ | 88205/100629 [1:09:15<13:09, 15.73it/s]

 88%|████████▊ | 88207/100629 [1:09:15<13:31, 15.30it/s]

 88%|████████▊ | 88209/100629 [1:09:15<13:31, 15.31it/s]

 88%|████████▊ | 88211/100629 [1:09:15<13:02, 15.86it/s]

 88%|████████▊ | 88214/100629 [1:09:16<11:45, 17.60it/s]

 88%|████████▊ | 88216/100629 [1:09:16<13:11, 15.68it/s]

 88%|████████▊ | 88218/100629 [1:09:16<12:49, 16.13it/s]

 88%|████████▊ | 88221/100629 [1:09:16<11:06, 18.62it/s]

 88%|████████▊ | 88225/100629 [1:09:16<09:20, 22.12it/s]

 88%|████████▊ | 88228/100629 [1:09:16<08:56, 23.13it/s]

 88%|████████▊ | 88232/100629 [1:09:16<08:06, 25.46it/s]

 88%|████████▊ | 88236/100629 [1:09:17<07:09, 28.87it/s]

 88%|████████▊ | 88240/100629 [1:09:17<07:23, 27.92it/s]

 88%|████████▊ | 88243/100629 [1:09:17<08:04, 25.57it/s]

 88%|████████▊ | 88246/100629 [1:09:17<08:36, 23.96it/s]

 88%|████████▊ | 88251/100629 [1:09:17<06:51, 30.11it/s]

 88%|████████▊ | 88255/100629 [1:09:17<07:08, 28.91it/s]

 88%|████████▊ | 88259/100629 [1:09:17<08:23, 24.58it/s]

 88%|████████▊ | 88262/100629 [1:09:18<09:28, 21.76it/s]

 88%|████████▊ | 88265/100629 [1:09:18<10:21, 19.90it/s]

 88%|████████▊ | 88268/100629 [1:09:18<10:14, 20.11it/s]

 88%|████████▊ | 88271/100629 [1:09:18<09:44, 21.15it/s]

 88%|████████▊ | 88274/100629 [1:09:18<11:13, 18.35it/s]

 88%|████████▊ | 88276/100629 [1:09:18<11:30, 17.88it/s]

 88%|████████▊ | 88280/100629 [1:09:19<09:56, 20.72it/s]

 88%|████████▊ | 88283/100629 [1:09:19<10:17, 19.98it/s]

 88%|████████▊ | 88286/100629 [1:09:19<09:32, 21.57it/s]

 88%|████████▊ | 88289/100629 [1:09:19<10:11, 20.16it/s]

 88%|████████▊ | 88292/100629 [1:09:19<09:47, 20.99it/s]

 88%|████████▊ | 88297/100629 [1:09:19<08:34, 23.98it/s]

 88%|████████▊ | 88300/100629 [1:09:19<08:33, 24.00it/s]

 88%|████████▊ | 88303/100629 [1:09:20<09:19, 22.03it/s]

 88%|████████▊ | 88306/100629 [1:09:20<10:17, 19.95it/s]

 88%|████████▊ | 88309/100629 [1:09:20<09:43, 21.12it/s]

 88%|████████▊ | 88312/100629 [1:09:20<09:24, 21.84it/s]

 88%|████████▊ | 88316/100629 [1:09:20<08:50, 23.22it/s]

 88%|████████▊ | 88320/100629 [1:09:20<08:03, 25.48it/s]

 88%|████████▊ | 88323/100629 [1:09:20<09:16, 22.11it/s]

 88%|████████▊ | 88327/100629 [1:09:21<08:45, 23.41it/s]

 88%|████████▊ | 88332/100629 [1:09:21<07:24, 27.68it/s]

 88%|████████▊ | 88335/100629 [1:09:21<07:52, 26.00it/s]

 88%|████████▊ | 88339/100629 [1:09:21<07:48, 26.24it/s]

 88%|████████▊ | 88342/100629 [1:09:21<08:38, 23.71it/s]

 88%|████████▊ | 88345/100629 [1:09:21<09:57, 20.54it/s]

 88%|████████▊ | 88348/100629 [1:09:22<10:56, 18.69it/s]

 88%|████████▊ | 88351/100629 [1:09:22<10:35, 19.32it/s]

 88%|████████▊ | 88354/100629 [1:09:22<10:49, 18.91it/s]

 88%|████████▊ | 88357/100629 [1:09:22<10:02, 20.37it/s]

 88%|████████▊ | 88360/100629 [1:09:22<10:31, 19.43it/s]

 88%|████████▊ | 88363/100629 [1:09:22<10:25, 19.61it/s]

 88%|████████▊ | 88366/100629 [1:09:22<09:48, 20.85it/s]

 88%|████████▊ | 88372/100629 [1:09:23<08:09, 25.05it/s]

 88%|████████▊ | 88375/100629 [1:09:23<08:10, 24.96it/s]

 88%|████████▊ | 88380/100629 [1:09:23<07:18, 27.96it/s]

 88%|████████▊ | 88384/100629 [1:09:23<07:22, 27.66it/s]

 88%|████████▊ | 88387/100629 [1:09:23<08:31, 23.96it/s]

 88%|████████▊ | 88390/100629 [1:09:23<08:10, 24.96it/s]

 88%|████████▊ | 88394/100629 [1:09:23<07:20, 27.80it/s]

 88%|████████▊ | 88397/100629 [1:09:24<07:16, 28.04it/s]

 88%|████████▊ | 88400/100629 [1:09:24<08:06, 25.14it/s]

 88%|████████▊ | 88403/100629 [1:09:24<09:31, 21.39it/s]

 88%|████████▊ | 88406/100629 [1:09:24<10:15, 19.86it/s]

 88%|████████▊ | 88410/100629 [1:09:24<09:01, 22.58it/s]

 88%|████████▊ | 88414/100629 [1:09:24<07:52, 25.85it/s]

 88%|████████▊ | 88417/100629 [1:09:25<10:35, 19.23it/s]

 88%|████████▊ | 88420/100629 [1:09:25<10:02, 20.27it/s]

 88%|████████▊ | 88423/100629 [1:09:25<09:36, 21.17it/s]

 88%|████████▊ | 88426/100629 [1:09:25<09:30, 21.39it/s]

 88%|████████▊ | 88429/100629 [1:09:25<08:54, 22.81it/s]

 88%|████████▊ | 88432/100629 [1:09:25<10:03, 20.21it/s]

 88%|████████▊ | 88435/100629 [1:09:25<10:13, 19.89it/s]

 88%|████████▊ | 88438/100629 [1:09:26<11:35, 17.54it/s]

 88%|████████▊ | 88440/100629 [1:09:26<12:46, 15.90it/s]

 88%|████████▊ | 88442/100629 [1:09:26<12:21, 16.44it/s]

 88%|████████▊ | 88444/100629 [1:09:26<12:33, 16.18it/s]

 88%|████████▊ | 88447/100629 [1:09:26<10:45, 18.89it/s]

 88%|████████▊ | 88449/100629 [1:09:26<12:36, 16.11it/s]

 88%|████████▊ | 88452/100629 [1:09:26<11:25, 17.76it/s]

 88%|████████▊ | 88455/100629 [1:09:27<10:40, 18.99it/s]

 88%|████████▊ | 88458/100629 [1:09:27<10:59, 18.45it/s]

 88%|████████▊ | 88460/100629 [1:09:27<11:00, 18.44it/s]

 88%|████████▊ | 88463/100629 [1:09:27<09:39, 20.99it/s]

 88%|████████▊ | 88467/100629 [1:09:27<08:53, 22.82it/s]

 88%|████████▊ | 88470/100629 [1:09:27<10:10, 19.92it/s]

 88%|████████▊ | 88475/100629 [1:09:27<07:44, 26.19it/s]

 88%|████████▊ | 88478/100629 [1:09:28<08:42, 23.27it/s]

 88%|████████▊ | 88481/100629 [1:09:28<08:51, 22.87it/s]

 88%|████████▊ | 88484/100629 [1:09:28<10:02, 20.17it/s]

 88%|████████▊ | 88487/100629 [1:09:28<09:21, 21.62it/s]

 88%|████████▊ | 88493/100629 [1:09:28<07:44, 26.11it/s]

 88%|████████▊ | 88496/100629 [1:09:28<08:33, 23.64it/s]

 88%|████████▊ | 88500/100629 [1:09:29<08:13, 24.60it/s]

 88%|████████▊ | 88503/100629 [1:09:29<10:06, 19.98it/s]

 88%|████████▊ | 88506/100629 [1:09:29<09:34, 21.11it/s]

 88%|████████▊ | 88510/100629 [1:09:29<08:48, 22.94it/s]

 88%|████████▊ | 88513/100629 [1:09:29<08:27, 23.87it/s]

 88%|████████▊ | 88516/100629 [1:09:29<10:44, 18.81it/s]

 88%|████████▊ | 88522/100629 [1:09:30<07:44, 26.08it/s]

 88%|████████▊ | 88526/100629 [1:09:30<07:54, 25.50it/s]

 88%|████████▊ | 88529/100629 [1:09:30<08:49, 22.87it/s]

 88%|████████▊ | 88532/100629 [1:09:30<09:48, 20.55it/s]

 88%|████████▊ | 88537/100629 [1:09:30<08:19, 24.21it/s]

 88%|████████▊ | 88541/100629 [1:09:30<08:09, 24.72it/s]

 88%|████████▊ | 88544/100629 [1:09:31<08:24, 23.98it/s]

 88%|████████▊ | 88547/100629 [1:09:31<08:17, 24.31it/s]

 88%|████████▊ | 88551/100629 [1:09:31<07:34, 26.60it/s]

 88%|████████▊ | 88554/100629 [1:09:31<07:40, 26.22it/s]

 88%|████████▊ | 88557/100629 [1:09:31<07:24, 27.15it/s]

 88%|████████▊ | 88561/100629 [1:09:31<07:49, 25.73it/s]

 88%|████████▊ | 88564/100629 [1:09:31<08:09, 24.66it/s]

 88%|████████▊ | 88567/100629 [1:09:31<08:40, 23.16it/s]

 88%|████████▊ | 88571/100629 [1:09:32<07:35, 26.46it/s]

 88%|████████▊ | 88574/100629 [1:09:32<07:25, 27.05it/s]

 88%|████████▊ | 88577/100629 [1:09:32<09:47, 20.51it/s]

 88%|████████▊ | 88582/100629 [1:09:32<08:45, 22.93it/s]

 88%|████████▊ | 88585/100629 [1:09:32<09:26, 21.26it/s]

 88%|████████▊ | 88588/100629 [1:09:32<09:08, 21.95it/s]

 88%|████████▊ | 88591/100629 [1:09:32<09:26, 21.25it/s]

 88%|████████▊ | 88594/100629 [1:09:33<09:54, 20.23it/s]

 88%|████████▊ | 88597/100629 [1:09:33<09:50, 20.36it/s]

 88%|████████▊ | 88600/100629 [1:09:33<09:43, 20.60it/s]

 88%|████████▊ | 88603/100629 [1:09:33<10:08, 19.75it/s]

 88%|████████▊ | 88606/100629 [1:09:33<10:15, 19.52it/s]

 88%|████████▊ | 88609/100629 [1:09:33<10:19, 19.42it/s]

 88%|████████▊ | 88611/100629 [1:09:34<11:29, 17.43it/s]

 88%|████████▊ | 88613/100629 [1:09:34<11:31, 17.37it/s]

 88%|████████▊ | 88615/100629 [1:09:34<11:10, 17.91it/s]

 88%|████████▊ | 88619/100629 [1:09:34<09:26, 21.21it/s]

 88%|████████▊ | 88622/100629 [1:09:34<08:48, 22.71it/s]

 88%|████████▊ | 88625/100629 [1:09:34<09:43, 20.57it/s]

 88%|████████▊ | 88628/100629 [1:09:34<10:12, 19.60it/s]

 88%|████████▊ | 88631/100629 [1:09:35<09:59, 20.00it/s]

 88%|████████▊ | 88634/100629 [1:09:35<11:40, 17.14it/s]

 88%|████████▊ | 88636/100629 [1:09:35<11:45, 17.00it/s]

 88%|████████▊ | 88638/100629 [1:09:35<13:09, 15.18it/s]

 88%|████████▊ | 88640/100629 [1:09:35<13:40, 14.62it/s]

 88%|████████▊ | 88643/100629 [1:09:35<12:00, 16.65it/s]

 88%|████████▊ | 88645/100629 [1:09:35<11:50, 16.87it/s]

 88%|████████▊ | 88648/100629 [1:09:36<11:11, 17.86it/s]

 88%|████████▊ | 88652/100629 [1:09:36<09:41, 20.58it/s]

 88%|████████▊ | 88655/100629 [1:09:36<09:24, 21.21it/s]

 88%|████████▊ | 88658/100629 [1:09:36<10:58, 18.19it/s]

 88%|████████▊ | 88660/100629 [1:09:36<11:04, 18.02it/s]

 88%|████████▊ | 88662/100629 [1:09:36<11:08, 17.89it/s]

 88%|████████▊ | 88664/100629 [1:09:36<11:23, 17.50it/s]

 88%|████████▊ | 88666/100629 [1:09:37<11:31, 17.31it/s]

 88%|████████▊ | 88668/100629 [1:09:37<11:35, 17.20it/s]

 88%|████████▊ | 88671/100629 [1:09:37<09:53, 20.15it/s]

 88%|████████▊ | 88674/100629 [1:09:37<09:35, 20.79it/s]

 88%|████████▊ | 88678/100629 [1:09:37<08:05, 24.60it/s]

 88%|████████▊ | 88681/100629 [1:09:37<09:23, 21.20it/s]

 88%|████████▊ | 88685/100629 [1:09:37<08:23, 23.73it/s]

 88%|████████▊ | 88688/100629 [1:09:38<08:52, 22.44it/s]

 88%|████████▊ | 88691/100629 [1:09:38<09:18, 21.38it/s]

 88%|████████▊ | 88694/100629 [1:09:38<09:10, 21.68it/s]

 88%|████████▊ | 88697/100629 [1:09:38<08:36, 23.12it/s]

 88%|████████▊ | 88703/100629 [1:09:38<06:37, 30.04it/s]

 88%|████████▊ | 88707/100629 [1:09:38<06:33, 30.27it/s]

 88%|████████▊ | 88711/100629 [1:09:38<07:07, 27.87it/s]

 88%|████████▊ | 88714/100629 [1:09:38<07:03, 28.14it/s]

 88%|████████▊ | 88717/100629 [1:09:39<07:22, 26.95it/s]

 88%|████████▊ | 88721/100629 [1:09:39<06:53, 28.80it/s]

 88%|████████▊ | 88724/100629 [1:09:39<07:30, 26.42it/s]

 88%|████████▊ | 88727/100629 [1:09:39<08:46, 22.60it/s]

 88%|████████▊ | 88730/100629 [1:09:39<10:15, 19.32it/s]

 88%|████████▊ | 88733/100629 [1:09:39<10:19, 19.21it/s]

 88%|████████▊ | 88736/100629 [1:09:40<11:53, 16.67it/s]

 88%|████████▊ | 88738/100629 [1:09:40<13:05, 15.14it/s]

 88%|████████▊ | 88740/100629 [1:09:40<13:19, 14.87it/s]

 88%|████████▊ | 88743/100629 [1:09:40<12:04, 16.42it/s]

 88%|████████▊ | 88746/100629 [1:09:40<11:28, 17.26it/s]

 88%|████████▊ | 88749/100629 [1:09:40<10:26, 18.96it/s]

 88%|████████▊ | 88752/100629 [1:09:41<09:17, 21.32it/s]

 88%|████████▊ | 88755/100629 [1:09:41<08:53, 22.26it/s]

 88%|████████▊ | 88758/100629 [1:09:41<09:15, 21.36it/s]

 88%|████████▊ | 88761/100629 [1:09:41<10:19, 19.15it/s]

 88%|████████▊ | 88766/100629 [1:09:41<08:34, 23.06it/s]

 88%|████████▊ | 88769/100629 [1:09:41<08:42, 22.71it/s]

 88%|████████▊ | 88772/100629 [1:09:42<12:00, 16.46it/s]

 88%|████████▊ | 88774/100629 [1:09:42<12:56, 15.26it/s]

 88%|████████▊ | 88777/100629 [1:09:42<11:35, 17.05it/s]

 88%|████████▊ | 88779/100629 [1:09:42<12:24, 15.91it/s]

 88%|████████▊ | 88782/100629 [1:09:42<11:12, 17.61it/s]

 88%|████████▊ | 88784/100629 [1:09:42<10:59, 17.96it/s]

 88%|████████▊ | 88787/100629 [1:09:42<10:17, 19.17it/s]

 88%|████████▊ | 88791/100629 [1:09:43<09:06, 21.68it/s]

 88%|████████▊ | 88794/100629 [1:09:43<10:47, 18.27it/s]

 88%|████████▊ | 88796/100629 [1:09:43<11:38, 16.94it/s]

 88%|████████▊ | 88799/100629 [1:09:43<10:59, 17.93it/s]

 88%|████████▊ | 88802/100629 [1:09:43<09:36, 20.52it/s]

 88%|████████▊ | 88808/100629 [1:09:43<07:22, 26.74it/s]

 88%|████████▊ | 88811/100629 [1:09:43<07:12, 27.35it/s]

 88%|████████▊ | 88814/100629 [1:09:44<07:02, 27.98it/s]

 88%|████████▊ | 88818/100629 [1:09:44<06:40, 29.51it/s]

 88%|████████▊ | 88821/100629 [1:09:44<06:40, 29.50it/s]

 88%|████████▊ | 88825/100629 [1:09:44<06:07, 32.10it/s]

 88%|████████▊ | 88829/100629 [1:09:44<06:49, 28.83it/s]

 88%|████████▊ | 88832/100629 [1:09:44<07:26, 26.39it/s]

 88%|████████▊ | 88835/100629 [1:09:44<08:29, 23.13it/s]

 88%|████████▊ | 88838/100629 [1:09:45<09:51, 19.94it/s]

 88%|████████▊ | 88841/100629 [1:09:45<09:33, 20.56it/s]

 88%|████████▊ | 88844/100629 [1:09:45<09:27, 20.75it/s]

 88%|████████▊ | 88848/100629 [1:09:45<08:16, 23.72it/s]

 88%|████████▊ | 88851/100629 [1:09:45<08:10, 24.01it/s]

 88%|████████▊ | 88854/100629 [1:09:45<08:22, 23.43it/s]

 88%|████████▊ | 88857/100629 [1:09:45<09:09, 21.44it/s]

 88%|████████▊ | 88860/100629 [1:09:46<10:41, 18.35it/s]

 88%|████████▊ | 88862/100629 [1:09:46<10:48, 18.14it/s]

 88%|████████▊ | 88866/100629 [1:09:46<09:07, 21.48it/s]

 88%|████████▊ | 88869/100629 [1:09:46<09:01, 21.70it/s]

 88%|████████▊ | 88872/100629 [1:09:46<08:34, 22.86it/s]

 88%|████████▊ | 88875/100629 [1:09:46<08:55, 21.97it/s]

 88%|████████▊ | 88879/100629 [1:09:46<08:13, 23.82it/s]

 88%|████████▊ | 88882/100629 [1:09:47<08:36, 22.77it/s]

 88%|████████▊ | 88885/100629 [1:09:47<09:35, 20.39it/s]

 88%|████████▊ | 88888/100629 [1:09:47<09:52, 19.83it/s]

 88%|████████▊ | 88891/100629 [1:09:47<09:09, 21.36it/s]

 88%|████████▊ | 88894/100629 [1:09:47<09:31, 20.55it/s]

 88%|████████▊ | 88897/100629 [1:09:47<09:57, 19.65it/s]

 88%|████████▊ | 88900/100629 [1:09:47<09:06, 21.46it/s]

 88%|████████▊ | 88903/100629 [1:09:48<09:50, 19.85it/s]

 88%|████████▊ | 88907/100629 [1:09:48<08:24, 23.23it/s]

 88%|████████▊ | 88910/100629 [1:09:48<09:44, 20.06it/s]

 88%|████████▊ | 88913/100629 [1:09:48<11:44, 16.62it/s]

 88%|████████▊ | 88915/100629 [1:09:48<11:31, 16.94it/s]

 88%|████████▊ | 88918/100629 [1:09:48<10:21, 18.83it/s]

 88%|████████▊ | 88921/100629 [1:09:49<09:29, 20.55it/s]

 88%|████████▊ | 88924/100629 [1:09:49<08:36, 22.65it/s]

 88%|████████▊ | 88927/100629 [1:09:49<08:27, 23.04it/s]

 88%|████████▊ | 88930/100629 [1:09:49<09:31, 20.47it/s]

 88%|████████▊ | 88933/100629 [1:09:49<11:05, 17.57it/s]

 88%|████████▊ | 88936/100629 [1:09:49<10:17, 18.94it/s]

 88%|████████▊ | 88939/100629 [1:09:49<09:43, 20.03it/s]

 88%|████████▊ | 88942/100629 [1:09:50<10:03, 19.35it/s]

 88%|████████▊ | 88945/100629 [1:09:50<09:38, 20.18it/s]

 88%|████████▊ | 88948/100629 [1:09:50<08:48, 22.12it/s]

 88%|████████▊ | 88951/100629 [1:09:50<10:40, 18.23it/s]

 88%|████████▊ | 88954/100629 [1:09:50<09:45, 19.95it/s]

 88%|████████▊ | 88958/100629 [1:09:50<08:13, 23.63it/s]

 88%|████████▊ | 88961/100629 [1:09:50<09:07, 21.33it/s]

 88%|████████▊ | 88964/100629 [1:09:51<09:10, 21.18it/s]

 88%|████████▊ | 88967/100629 [1:09:51<08:42, 22.31it/s]

 88%|████████▊ | 88970/100629 [1:09:51<08:52, 21.91it/s]

 88%|████████▊ | 88973/100629 [1:09:51<08:25, 23.05it/s]

 88%|████████▊ | 88976/100629 [1:09:51<09:08, 21.23it/s]

 88%|████████▊ | 88979/100629 [1:09:51<08:24, 23.11it/s]

 88%|████████▊ | 88983/100629 [1:09:51<07:40, 25.30it/s]

 88%|████████▊ | 88987/100629 [1:09:52<07:29, 25.92it/s]

 88%|████████▊ | 88991/100629 [1:09:52<07:26, 26.06it/s]

 88%|████████▊ | 88995/100629 [1:09:52<06:52, 28.21it/s]

 88%|████████▊ | 88998/100629 [1:09:52<09:34, 20.26it/s]

 88%|████████▊ | 89001/100629 [1:09:52<09:28, 20.47it/s]

 88%|████████▊ | 89004/100629 [1:09:52<08:41, 22.28it/s]

 88%|████████▊ | 89007/100629 [1:09:52<09:02, 21.44it/s]

 88%|████████▊ | 89010/100629 [1:09:53<10:46, 17.98it/s]

 88%|████████▊ | 89013/100629 [1:09:53<11:04, 17.49it/s]

 88%|████████▊ | 89015/100629 [1:09:53<11:26, 16.92it/s]

 88%|████████▊ | 89018/100629 [1:09:53<11:22, 17.01it/s]

 88%|████████▊ | 89021/100629 [1:09:53<10:17, 18.80it/s]

 88%|████████▊ | 89023/100629 [1:09:53<10:36, 18.24it/s]

 88%|████████▊ | 89026/100629 [1:09:54<10:28, 18.46it/s]

 88%|████████▊ | 89028/100629 [1:09:54<13:02, 14.83it/s]

 88%|████████▊ | 89030/100629 [1:09:54<13:59, 13.82it/s]

 88%|████████▊ | 89033/100629 [1:09:54<13:37, 14.18it/s]

 88%|████████▊ | 89036/100629 [1:09:54<11:44, 16.46it/s]

 88%|████████▊ | 89038/100629 [1:09:54<12:56, 14.92it/s]

 88%|████████▊ | 89042/100629 [1:09:55<10:03, 19.21it/s]

 88%|████████▊ | 89045/100629 [1:09:55<09:39, 20.00it/s]

 88%|████████▊ | 89049/100629 [1:09:55<08:55, 21.62it/s]

 88%|████████▊ | 89053/100629 [1:09:55<08:30, 22.69it/s]

 88%|████████▊ | 89056/100629 [1:09:55<08:55, 21.60it/s]

 89%|████████▊ | 89059/100629 [1:09:55<09:21, 20.60it/s]

 89%|████████▊ | 89062/100629 [1:09:56<09:28, 20.36it/s]

 89%|████████▊ | 89065/100629 [1:09:56<13:08, 14.67it/s]

 89%|████████▊ | 89068/100629 [1:09:56<13:07, 14.68it/s]

 89%|████████▊ | 89071/100629 [1:09:56<12:30, 15.39it/s]

 89%|████████▊ | 89073/100629 [1:09:56<12:01, 16.02it/s]

 89%|████████▊ | 89076/100629 [1:09:57<13:17, 14.48it/s]

 89%|████████▊ | 89078/100629 [1:09:57<12:57, 14.86it/s]

 89%|████████▊ | 89081/100629 [1:09:57<11:25, 16.85it/s]

 89%|████████▊ | 89084/100629 [1:09:57<09:59, 19.26it/s]

 89%|████████▊ | 89088/100629 [1:09:57<08:03, 23.89it/s]

 89%|████████▊ | 89092/100629 [1:09:57<07:24, 25.93it/s]

 89%|████████▊ | 89095/100629 [1:09:57<07:16, 26.40it/s]

 89%|████████▊ | 89098/100629 [1:09:57<07:37, 25.18it/s]

 89%|████████▊ | 89101/100629 [1:09:58<07:20, 26.19it/s]

 89%|████████▊ | 89104/100629 [1:09:58<08:09, 23.55it/s]

 89%|████████▊ | 89107/100629 [1:09:58<08:35, 22.34it/s]

 89%|████████▊ | 89111/100629 [1:09:58<07:31, 25.50it/s]

 89%|████████▊ | 89114/100629 [1:09:58<07:18, 26.23it/s]

 89%|████████▊ | 89117/100629 [1:09:58<07:14, 26.51it/s]

 89%|████████▊ | 89120/100629 [1:09:58<07:53, 24.33it/s]

 89%|████████▊ | 89123/100629 [1:09:58<07:34, 25.31it/s]

 89%|████████▊ | 89127/100629 [1:09:59<07:33, 25.38it/s]

 89%|████████▊ | 89130/100629 [1:09:59<07:16, 26.37it/s]

 89%|████████▊ | 89133/100629 [1:09:59<08:25, 22.76it/s]

 89%|████████▊ | 89136/100629 [1:09:59<08:22, 22.87it/s]

 89%|████████▊ | 89139/100629 [1:09:59<08:57, 21.39it/s]

 89%|████████▊ | 89142/100629 [1:09:59<11:13, 17.06it/s]

 89%|████████▊ | 89145/100629 [1:10:00<11:00, 17.37it/s]

 89%|████████▊ | 89147/100629 [1:10:00<11:04, 17.28it/s]

 89%|████████▊ | 89150/100629 [1:10:00<10:06, 18.93it/s]

 89%|████████▊ | 89153/100629 [1:10:00<09:20, 20.49it/s]

 89%|████████▊ | 89156/100629 [1:10:00<09:38, 19.83it/s]

 89%|████████▊ | 89159/100629 [1:10:00<11:14, 17.01it/s]

 89%|████████▊ | 89162/100629 [1:10:01<10:42, 17.85it/s]

 89%|████████▊ | 89165/100629 [1:10:01<10:22, 18.42it/s]

 89%|████████▊ | 89168/100629 [1:10:01<09:25, 20.27it/s]

 89%|████████▊ | 89171/100629 [1:10:01<10:34, 18.07it/s]

 89%|████████▊ | 89174/100629 [1:10:01<09:38, 19.81it/s]

 89%|████████▊ | 89177/100629 [1:10:01<08:39, 22.05it/s]

 89%|████████▊ | 89180/100629 [1:10:01<09:14, 20.64it/s]

 89%|████████▊ | 89183/100629 [1:10:02<09:33, 19.95it/s]

 89%|████████▊ | 89186/100629 [1:10:02<11:14, 16.97it/s]

 89%|████████▊ | 89188/100629 [1:10:02<11:55, 16.00it/s]

 89%|████████▊ | 89192/100629 [1:10:02<10:21, 18.41it/s]

 89%|████████▊ | 89195/100629 [1:10:02<09:56, 19.18it/s]

 89%|████████▊ | 89198/100629 [1:10:02<10:13, 18.64it/s]

 89%|████████▊ | 89201/100629 [1:10:03<09:20, 20.38it/s]

 89%|████████▊ | 89205/100629 [1:10:03<07:43, 24.67it/s]

 89%|████████▊ | 89209/100629 [1:10:03<07:28, 25.47it/s]

 89%|████████▊ | 89212/100629 [1:10:03<08:29, 22.41it/s]

 89%|████████▊ | 89215/100629 [1:10:03<09:20, 20.36it/s]

 89%|████████▊ | 89218/100629 [1:10:03<09:12, 20.66it/s]

 89%|████████▊ | 89221/100629 [1:10:03<09:27, 20.10it/s]

 89%|████████▊ | 89224/100629 [1:10:04<09:49, 19.35it/s]

 89%|████████▊ | 89227/100629 [1:10:04<09:07, 20.81it/s]

 89%|████████▊ | 89231/100629 [1:10:04<08:01, 23.66it/s]

 89%|████████▊ | 89234/100629 [1:10:04<08:51, 21.45it/s]

 89%|████████▊ | 89237/100629 [1:10:04<08:27, 22.44it/s]

 89%|████████▊ | 89240/100629 [1:10:04<08:53, 21.35it/s]

 89%|████████▊ | 89243/100629 [1:10:04<08:09, 23.27it/s]

 89%|████████▊ | 89246/100629 [1:10:05<07:53, 24.06it/s]

 89%|████████▊ | 89249/100629 [1:10:05<07:34, 25.02it/s]

 89%|████████▊ | 89252/100629 [1:10:05<07:30, 25.27it/s]

 89%|████████▊ | 89255/100629 [1:10:05<07:18, 25.96it/s]

 89%|████████▊ | 89258/100629 [1:10:05<07:04, 26.79it/s]

 89%|████████▊ | 89261/100629 [1:10:05<07:19, 25.88it/s]

 89%|████████▊ | 89264/100629 [1:10:05<08:06, 23.35it/s]

 89%|████████▊ | 89267/100629 [1:10:05<08:31, 22.20it/s]

 89%|████████▊ | 89270/100629 [1:10:06<10:05, 18.76it/s]

 89%|████████▊ | 89273/100629 [1:10:06<11:18, 16.75it/s]

 89%|████████▊ | 89275/100629 [1:10:06<11:49, 16.00it/s]

 89%|████████▊ | 89278/100629 [1:10:06<10:10, 18.59it/s]

 89%|████████▊ | 89281/100629 [1:10:06<10:58, 17.24it/s]

 89%|████████▊ | 89283/100629 [1:10:06<11:10, 16.92it/s]

 89%|████████▊ | 89285/100629 [1:10:07<12:08, 15.57it/s]

 89%|████████▊ | 89287/100629 [1:10:07<12:30, 15.12it/s]

 89%|████████▊ | 89289/100629 [1:10:07<12:46, 14.80it/s]

 89%|████████▊ | 89291/100629 [1:10:07<11:56, 15.82it/s]

 89%|████████▊ | 89295/100629 [1:10:07<09:36, 19.66it/s]

 89%|████████▊ | 89297/100629 [1:10:07<10:07, 18.66it/s]

 89%|████████▊ | 89302/100629 [1:10:07<07:35, 24.87it/s]

 89%|████████▊ | 89305/100629 [1:10:07<07:30, 25.16it/s]

 89%|████████▊ | 89308/100629 [1:10:08<08:18, 22.70it/s]

 89%|████████▉ | 89311/100629 [1:10:08<08:36, 21.90it/s]

 89%|████████▉ | 89314/100629 [1:10:08<08:15, 22.86it/s]

 89%|████████▉ | 89317/100629 [1:10:08<08:12, 22.99it/s]

 89%|████████▉ | 89320/100629 [1:10:08<08:28, 22.26it/s]

 89%|████████▉ | 89323/100629 [1:10:08<08:14, 22.85it/s]

 89%|████████▉ | 89326/100629 [1:10:09<10:09, 18.54it/s]

 89%|████████▉ | 89330/100629 [1:10:09<09:13, 20.40it/s]

 89%|████████▉ | 89333/100629 [1:10:09<08:46, 21.44it/s]

 89%|████████▉ | 89337/100629 [1:10:09<07:46, 24.23it/s]

 89%|████████▉ | 89340/100629 [1:10:09<07:59, 23.55it/s]

 89%|████████▉ | 89343/100629 [1:10:09<08:23, 22.40it/s]

 89%|████████▉ | 89346/100629 [1:10:09<08:01, 23.45it/s]

 89%|████████▉ | 89352/100629 [1:10:09<06:18, 29.79it/s]

 89%|████████▉ | 89356/100629 [1:10:10<06:40, 28.16it/s]

 89%|████████▉ | 89360/100629 [1:10:10<06:29, 28.96it/s]

 89%|████████▉ | 89363/100629 [1:10:10<07:58, 23.54it/s]

 89%|████████▉ | 89366/100629 [1:10:10<07:32, 24.86it/s]

 89%|████████▉ | 89369/100629 [1:10:10<07:12, 26.03it/s]

 89%|████████▉ | 89373/100629 [1:10:10<06:23, 29.35it/s]

 89%|████████▉ | 89378/100629 [1:10:10<05:57, 31.45it/s]

 89%|████████▉ | 89382/100629 [1:10:11<06:34, 28.51it/s]

 89%|████████▉ | 89385/100629 [1:10:11<07:05, 26.42it/s]

 89%|████████▉ | 89388/100629 [1:10:11<07:32, 24.85it/s]

 89%|████████▉ | 89391/100629 [1:10:11<07:42, 24.28it/s]

 89%|████████▉ | 89395/100629 [1:10:11<07:42, 24.29it/s]

 89%|████████▉ | 89398/100629 [1:10:11<08:29, 22.04it/s]

 89%|████████▉ | 89401/100629 [1:10:12<10:08, 18.44it/s]

 89%|████████▉ | 89404/100629 [1:10:12<09:57, 18.80it/s]

 89%|████████▉ | 89408/100629 [1:10:12<08:20, 22.42it/s]

 89%|████████▉ | 89411/100629 [1:10:12<09:45, 19.17it/s]

 89%|████████▉ | 89414/100629 [1:10:12<09:53, 18.88it/s]

 89%|████████▉ | 89419/100629 [1:10:12<07:29, 24.92it/s]

 89%|████████▉ | 89422/100629 [1:10:12<07:37, 24.49it/s]

 89%|████████▉ | 89425/100629 [1:10:13<07:20, 25.42it/s]

 89%|████████▉ | 89428/100629 [1:10:13<07:34, 24.62it/s]

 89%|████████▉ | 89431/100629 [1:10:13<07:29, 24.90it/s]

 89%|████████▉ | 89434/100629 [1:10:13<07:50, 23.80it/s]

 89%|████████▉ | 89437/100629 [1:10:13<08:23, 22.23it/s]

 89%|████████▉ | 89441/100629 [1:10:13<07:36, 24.49it/s]

 89%|████████▉ | 89444/100629 [1:10:13<08:40, 21.51it/s]

 89%|████████▉ | 89448/100629 [1:10:14<07:33, 24.63it/s]

 89%|████████▉ | 89451/100629 [1:10:14<08:02, 23.16it/s]

 89%|████████▉ | 89454/100629 [1:10:14<07:51, 23.70it/s]

 89%|████████▉ | 89457/100629 [1:10:14<07:57, 23.39it/s]

 89%|████████▉ | 89460/100629 [1:10:14<08:26, 22.06it/s]

 89%|████████▉ | 89463/100629 [1:10:14<08:08, 22.88it/s]

 89%|████████▉ | 89466/100629 [1:10:14<08:48, 21.11it/s]

 89%|████████▉ | 89469/100629 [1:10:14<08:13, 22.62it/s]

 89%|████████▉ | 89472/100629 [1:10:15<08:51, 20.98it/s]

 89%|████████▉ | 89475/100629 [1:10:15<08:43, 21.33it/s]

 89%|████████▉ | 89478/100629 [1:10:15<09:31, 19.53it/s]

 89%|████████▉ | 89481/100629 [1:10:15<08:31, 21.79it/s]

 89%|████████▉ | 89484/100629 [1:10:15<08:11, 22.67it/s]

 89%|████████▉ | 89487/100629 [1:10:15<07:58, 23.27it/s]

 89%|████████▉ | 89490/100629 [1:10:15<08:15, 22.49it/s]

 89%|████████▉ | 89493/100629 [1:10:16<08:33, 21.70it/s]

 89%|████████▉ | 89496/100629 [1:10:16<08:15, 22.46it/s]

 89%|████████▉ | 89499/100629 [1:10:16<08:02, 23.09it/s]

 89%|████████▉ | 89502/100629 [1:10:16<07:56, 23.36it/s]

 89%|████████▉ | 89505/100629 [1:10:16<07:40, 24.14it/s]

 89%|████████▉ | 89508/100629 [1:10:16<07:17, 25.40it/s]

 89%|████████▉ | 89513/100629 [1:10:16<06:28, 28.62it/s]

 89%|████████▉ | 89516/100629 [1:10:16<06:51, 26.98it/s]

 89%|████████▉ | 89519/100629 [1:10:17<08:29, 21.81it/s]

 89%|████████▉ | 89522/100629 [1:10:17<09:55, 18.64it/s]

 89%|████████▉ | 89525/100629 [1:10:17<09:35, 19.30it/s]

 89%|████████▉ | 89530/100629 [1:10:17<07:57, 23.25it/s]

 89%|████████▉ | 89534/100629 [1:10:17<06:58, 26.49it/s]

 89%|████████▉ | 89538/100629 [1:10:17<06:37, 27.89it/s]

 89%|████████▉ | 89541/100629 [1:10:18<07:17, 25.34it/s]

 89%|████████▉ | 89544/100629 [1:10:18<08:41, 21.26it/s]

 89%|████████▉ | 89547/100629 [1:10:18<08:35, 21.49it/s]

 89%|████████▉ | 89550/100629 [1:10:18<09:04, 20.35it/s]

 89%|████████▉ | 89553/100629 [1:10:18<10:12, 18.09it/s]

 89%|████████▉ | 89555/100629 [1:10:18<10:55, 16.90it/s]

 89%|████████▉ | 89558/100629 [1:10:19<10:32, 17.50it/s]

 89%|████████▉ | 89561/100629 [1:10:19<09:43, 18.96it/s]

 89%|████████▉ | 89563/100629 [1:10:19<09:44, 18.93it/s]

 89%|████████▉ | 89567/100629 [1:10:19<07:48, 23.61it/s]

 89%|████████▉ | 89570/100629 [1:10:19<07:34, 24.34it/s]

 89%|████████▉ | 89573/100629 [1:10:19<09:31, 19.34it/s]

 89%|████████▉ | 89576/100629 [1:10:19<09:48, 18.78it/s]

 89%|████████▉ | 89579/100629 [1:10:20<09:50, 18.70it/s]

 89%|████████▉ | 89582/100629 [1:10:20<11:16, 16.32it/s]

 89%|████████▉ | 89586/100629 [1:10:20<08:55, 20.62it/s]

 89%|████████▉ | 89589/100629 [1:10:20<08:16, 22.22it/s]

 89%|████████▉ | 89592/100629 [1:10:20<08:21, 22.01it/s]

 89%|████████▉ | 89595/100629 [1:10:20<08:26, 21.80it/s]

 89%|████████▉ | 89598/100629 [1:10:20<08:50, 20.81it/s]

 89%|████████▉ | 89601/100629 [1:10:21<08:15, 22.24it/s]

 89%|████████▉ | 89604/100629 [1:10:21<08:39, 21.22it/s]

 89%|████████▉ | 89607/100629 [1:10:21<08:54, 20.63it/s]

 89%|████████▉ | 89610/100629 [1:10:21<08:32, 21.51it/s]

 89%|████████▉ | 89613/100629 [1:10:21<08:37, 21.30it/s]

 89%|████████▉ | 89617/100629 [1:10:21<07:16, 25.23it/s]

 89%|████████▉ | 89620/100629 [1:10:21<07:06, 25.82it/s]

 89%|████████▉ | 89623/100629 [1:10:21<07:01, 26.13it/s]

 89%|████████▉ | 89626/100629 [1:10:22<06:59, 26.20it/s]

 89%|████████▉ | 89629/100629 [1:10:22<06:57, 26.33it/s]

 89%|████████▉ | 89633/100629 [1:10:22<06:12, 29.51it/s]

 89%|████████▉ | 89636/100629 [1:10:22<06:20, 28.90it/s]

 89%|████████▉ | 89639/100629 [1:10:22<06:53, 26.57it/s]

 89%|████████▉ | 89642/100629 [1:10:22<08:18, 22.04it/s]

 89%|████████▉ | 89645/100629 [1:10:22<08:22, 21.86it/s]

 89%|████████▉ | 89648/100629 [1:10:23<08:51, 20.64it/s]

 89%|████████▉ | 89652/100629 [1:10:23<07:40, 23.86it/s]

 89%|████████▉ | 89655/100629 [1:10:23<07:48, 23.42it/s]

 89%|████████▉ | 89658/100629 [1:10:23<08:08, 22.44it/s]

 89%|████████▉ | 89661/100629 [1:10:23<08:28, 21.58it/s]

 89%|████████▉ | 89664/100629 [1:10:23<08:08, 22.45it/s]

 89%|████████▉ | 89667/100629 [1:10:23<09:12, 19.85it/s]

 89%|████████▉ | 89671/100629 [1:10:24<07:57, 22.96it/s]

 89%|████████▉ | 89674/100629 [1:10:24<08:31, 21.42it/s]

 89%|████████▉ | 89677/100629 [1:10:24<07:58, 22.88it/s]

 89%|████████▉ | 89680/100629 [1:10:24<08:41, 21.01it/s]

 89%|████████▉ | 89684/100629 [1:10:24<07:58, 22.87it/s]

 89%|████████▉ | 89687/100629 [1:10:24<08:17, 21.99it/s]

 89%|████████▉ | 89690/100629 [1:10:24<08:07, 22.46it/s]

 89%|████████▉ | 89693/100629 [1:10:25<08:58, 20.31it/s]

 89%|████████▉ | 89697/100629 [1:10:25<07:32, 24.16it/s]

 89%|████████▉ | 89700/100629 [1:10:25<07:28, 24.38it/s]

 89%|████████▉ | 89703/100629 [1:10:25<08:13, 22.14it/s]

 89%|████████▉ | 89706/100629 [1:10:25<07:51, 23.18it/s]

 89%|████████▉ | 89710/100629 [1:10:25<07:06, 25.62it/s]

 89%|████████▉ | 89713/100629 [1:10:25<07:12, 25.24it/s]

 89%|████████▉ | 89720/100629 [1:10:26<05:30, 33.03it/s]

 89%|████████▉ | 89724/100629 [1:10:26<06:32, 27.80it/s]

 89%|████████▉ | 89727/100629 [1:10:26<07:07, 25.53it/s]

 89%|████████▉ | 89730/100629 [1:10:26<07:35, 23.94it/s]

 89%|████████▉ | 89735/100629 [1:10:26<06:15, 28.98it/s]

 89%|████████▉ | 89739/100629 [1:10:26<06:29, 27.94it/s]

 89%|████████▉ | 89742/100629 [1:10:27<08:22, 21.68it/s]

 89%|████████▉ | 89745/100629 [1:10:27<08:20, 21.75it/s]

 89%|████████▉ | 89749/100629 [1:10:27<07:38, 23.73it/s]

 89%|████████▉ | 89752/100629 [1:10:27<09:33, 18.95it/s]

 89%|████████▉ | 89756/100629 [1:10:27<07:58, 22.74it/s]

 89%|████████▉ | 89759/100629 [1:10:27<07:53, 22.97it/s]

 89%|████████▉ | 89762/100629 [1:10:27<09:23, 19.28it/s]

 89%|████████▉ | 89765/100629 [1:10:28<08:48, 20.54it/s]

 89%|████████▉ | 89768/100629 [1:10:28<08:24, 21.51it/s]

 89%|████████▉ | 89771/100629 [1:10:28<08:08, 22.25it/s]

 89%|████████▉ | 89775/100629 [1:10:28<06:55, 26.11it/s]

 89%|████████▉ | 89778/100629 [1:10:28<07:39, 23.63it/s]

 89%|████████▉ | 89781/100629 [1:10:28<07:30, 24.10it/s]

 89%|████████▉ | 89784/100629 [1:10:28<08:47, 20.56it/s]

 89%|████████▉ | 89787/100629 [1:10:29<08:33, 21.10it/s]

 89%|████████▉ | 89790/100629 [1:10:29<07:55, 22.78it/s]

 89%|████████▉ | 89793/100629 [1:10:29<10:40, 16.92it/s]

 89%|████████▉ | 89796/100629 [1:10:29<10:41, 16.88it/s]

 89%|████████▉ | 89800/100629 [1:10:29<10:14, 17.62it/s]

 89%|████████▉ | 89802/100629 [1:10:29<10:00, 18.04it/s]

 89%|████████▉ | 89806/100629 [1:10:30<08:18, 21.71it/s]

 89%|████████▉ | 89809/100629 [1:10:30<10:43, 16.81it/s]

 89%|████████▉ | 89811/100629 [1:10:30<13:23, 13.47it/s]

 89%|████████▉ | 89814/100629 [1:10:30<11:12, 16.08it/s]

 89%|████████▉ | 89817/100629 [1:10:30<09:38, 18.70it/s]

 89%|████████▉ | 89820/100629 [1:10:30<09:19, 19.32it/s]

 89%|████████▉ | 89823/100629 [1:10:31<09:59, 18.02it/s]

 89%|████████▉ | 89826/100629 [1:10:31<10:56, 16.45it/s]

 89%|████████▉ | 89829/100629 [1:10:31<09:36, 18.75it/s]

 89%|████████▉ | 89834/100629 [1:10:31<07:33, 23.81it/s]

 89%|████████▉ | 89837/100629 [1:10:31<09:59, 18.00it/s]

 89%|████████▉ | 89840/100629 [1:10:32<09:10, 19.59it/s]

 89%|████████▉ | 89843/100629 [1:10:32<09:50, 18.28it/s]

 89%|████████▉ | 89846/100629 [1:10:32<11:21, 15.81it/s]

 89%|████████▉ | 89849/100629 [1:10:32<10:45, 16.70it/s]

 89%|████████▉ | 89851/100629 [1:10:32<11:00, 16.31it/s]

 89%|████████▉ | 89855/100629 [1:10:32<10:00, 17.96it/s]

 89%|████████▉ | 89859/100629 [1:10:33<08:51, 20.28it/s]

 89%|████████▉ | 89862/100629 [1:10:33<08:55, 20.09it/s]

 89%|████████▉ | 89865/100629 [1:10:33<08:58, 19.99it/s]

 89%|████████▉ | 89868/100629 [1:10:33<08:35, 20.87it/s]

 89%|████████▉ | 89871/100629 [1:10:33<08:13, 21.80it/s]

 89%|████████▉ | 89874/100629 [1:10:33<07:34, 23.68it/s]

 89%|████████▉ | 89878/100629 [1:10:33<06:28, 27.69it/s]

 89%|████████▉ | 89881/100629 [1:10:33<06:25, 27.85it/s]

 89%|████████▉ | 89885/100629 [1:10:34<06:00, 29.79it/s]

 89%|████████▉ | 89889/100629 [1:10:34<06:43, 26.63it/s]

 89%|████████▉ | 89892/100629 [1:10:34<06:51, 26.06it/s]

 89%|████████▉ | 89897/100629 [1:10:34<06:41, 26.76it/s]

 89%|████████▉ | 89901/100629 [1:10:34<07:03, 25.34it/s]

 89%|████████▉ | 89904/100629 [1:10:34<07:46, 22.98it/s]

 89%|████████▉ | 89908/100629 [1:10:35<06:51, 26.05it/s]

 89%|████████▉ | 89911/100629 [1:10:35<07:05, 25.21it/s]

 89%|████████▉ | 89914/100629 [1:10:35<07:11, 24.81it/s]

 89%|████████▉ | 89917/100629 [1:10:35<07:39, 23.33it/s]

 89%|████████▉ | 89920/100629 [1:10:35<08:10, 21.84it/s]

 89%|████████▉ | 89923/100629 [1:10:35<08:10, 21.83it/s]

 89%|████████▉ | 89926/100629 [1:10:35<08:28, 21.05it/s]

 89%|████████▉ | 89929/100629 [1:10:36<09:24, 18.95it/s]

 89%|████████▉ | 89932/100629 [1:10:36<08:44, 20.38it/s]

 89%|████████▉ | 89935/100629 [1:10:36<09:01, 19.73it/s]

 89%|████████▉ | 89939/100629 [1:10:36<07:34, 23.53it/s]

 89%|████████▉ | 89942/100629 [1:10:36<07:49, 22.76it/s]

 89%|████████▉ | 89945/100629 [1:10:36<07:18, 24.39it/s]

 89%|████████▉ | 89948/100629 [1:10:36<07:13, 24.62it/s]

 89%|████████▉ | 89951/100629 [1:10:37<08:47, 20.23it/s]

 89%|████████▉ | 89954/100629 [1:10:37<08:54, 19.98it/s]

 89%|████████▉ | 89957/100629 [1:10:37<09:25, 18.86it/s]

 89%|████████▉ | 89959/100629 [1:10:37<09:24, 18.89it/s]

 89%|████████▉ | 89963/100629 [1:10:37<09:09, 19.41it/s]

 89%|████████▉ | 89965/100629 [1:10:37<09:38, 18.42it/s]

 89%|████████▉ | 89969/100629 [1:10:37<08:06, 21.89it/s]

 89%|████████▉ | 89972/100629 [1:10:38<08:37, 20.60it/s]

 89%|████████▉ | 89975/100629 [1:10:38<09:14, 19.20it/s]

 89%|████████▉ | 89978/100629 [1:10:38<10:07, 17.54it/s]

 89%|████████▉ | 89980/100629 [1:10:38<09:51, 18.01it/s]

 89%|████████▉ | 89984/100629 [1:10:38<08:03, 22.02it/s]

 89%|████████▉ | 89988/100629 [1:10:38<07:04, 25.05it/s]

 89%|████████▉ | 89991/100629 [1:10:39<08:18, 21.35it/s]

 89%|████████▉ | 89994/100629 [1:10:39<08:59, 19.71it/s]

 89%|████████▉ | 89997/100629 [1:10:39<08:10, 21.65it/s]

 89%|████████▉ | 90000/100629 [1:10:39<07:36, 23.30it/s]

 89%|████████▉ | 90003/100629 [1:10:39<07:18, 24.26it/s]

 89%|████████▉ | 90006/100629 [1:10:39<07:19, 24.18it/s]

 89%|████████▉ | 90009/100629 [1:10:39<07:27, 23.73it/s]

 89%|████████▉ | 90013/100629 [1:10:39<06:29, 27.28it/s]

 89%|████████▉ | 90016/100629 [1:10:40<07:10, 24.68it/s]

 89%|████████▉ | 90019/100629 [1:10:40<07:40, 23.03it/s]

 89%|████████▉ | 90022/100629 [1:10:40<07:39, 23.06it/s]

 89%|████████▉ | 90025/100629 [1:10:40<07:22, 23.97it/s]

 89%|████████▉ | 90028/100629 [1:10:40<07:13, 24.44it/s]

 89%|████████▉ | 90031/100629 [1:10:40<08:28, 20.85it/s]

 89%|████████▉ | 90034/100629 [1:10:40<09:08, 19.31it/s]

 89%|████████▉ | 90037/100629 [1:10:41<09:44, 18.11it/s]

 89%|████████▉ | 90040/100629 [1:10:41<08:36, 20.49it/s]

 89%|████████▉ | 90044/100629 [1:10:41<07:19, 24.10it/s]

 89%|████████▉ | 90047/100629 [1:10:41<07:22, 23.92it/s]

 89%|████████▉ | 90050/100629 [1:10:41<07:02, 25.04it/s]

 89%|████████▉ | 90053/100629 [1:10:41<07:18, 24.12it/s]

 89%|████████▉ | 90056/100629 [1:10:41<07:53, 22.34it/s]

 89%|████████▉ | 90059/100629 [1:10:42<09:24, 18.74it/s]

 89%|████████▉ | 90062/100629 [1:10:42<10:04, 17.48it/s]

 90%|████████▉ | 90065/100629 [1:10:42<09:15, 19.01it/s]

 90%|████████▉ | 90068/100629 [1:10:42<08:36, 20.46it/s]

 90%|████████▉ | 90071/100629 [1:10:42<09:00, 19.53it/s]

 90%|████████▉ | 90075/100629 [1:10:42<07:24, 23.73it/s]

 90%|████████▉ | 90078/100629 [1:10:42<07:13, 24.34it/s]

 90%|████████▉ | 90081/100629 [1:10:43<07:45, 22.64it/s]

 90%|████████▉ | 90084/100629 [1:10:43<07:51, 22.38it/s]

 90%|████████▉ | 90087/100629 [1:10:43<08:25, 20.87it/s]

 90%|████████▉ | 90090/100629 [1:10:43<08:01, 21.88it/s]

 90%|████████▉ | 90095/100629 [1:10:43<06:22, 27.51it/s]

 90%|████████▉ | 90098/100629 [1:10:43<06:47, 25.87it/s]

 90%|████████▉ | 90101/100629 [1:10:43<07:46, 22.57it/s]

 90%|████████▉ | 90105/100629 [1:10:44<06:58, 25.17it/s]

 90%|████████▉ | 90108/100629 [1:10:44<06:56, 25.28it/s]

 90%|████████▉ | 90112/100629 [1:10:44<06:26, 27.20it/s]

 90%|████████▉ | 90115/100629 [1:10:44<07:34, 23.12it/s]

 90%|████████▉ | 90119/100629 [1:10:44<07:07, 24.61it/s]

 90%|████████▉ | 90122/100629 [1:10:44<07:00, 24.99it/s]

 90%|████████▉ | 90125/100629 [1:10:44<07:23, 23.70it/s]

 90%|████████▉ | 90128/100629 [1:10:44<07:01, 24.91it/s]

 90%|████████▉ | 90131/100629 [1:10:45<06:53, 25.40it/s]

 90%|████████▉ | 90134/100629 [1:10:45<08:06, 21.57it/s]

 90%|████████▉ | 90137/100629 [1:10:45<07:46, 22.51it/s]

 90%|████████▉ | 90140/100629 [1:10:45<07:44, 22.57it/s]

 90%|████████▉ | 90143/100629 [1:10:45<07:42, 22.66it/s]

 90%|████████▉ | 90148/100629 [1:10:45<06:12, 28.17it/s]

 90%|████████▉ | 90151/100629 [1:10:45<06:40, 26.16it/s]

 90%|████████▉ | 90154/100629 [1:10:46<06:50, 25.51it/s]

 90%|████████▉ | 90157/100629 [1:10:46<06:49, 25.59it/s]

 90%|████████▉ | 90160/100629 [1:10:46<07:12, 24.21it/s]

 90%|████████▉ | 90163/100629 [1:10:46<08:34, 20.33it/s]

 90%|████████▉ | 90166/100629 [1:10:46<09:14, 18.88it/s]

 90%|████████▉ | 90169/100629 [1:10:46<08:16, 21.08it/s]

 90%|████████▉ | 90173/100629 [1:10:46<06:54, 25.22it/s]

 90%|████████▉ | 90177/100629 [1:10:47<06:28, 26.93it/s]

 90%|████████▉ | 90180/100629 [1:10:47<09:13, 18.87it/s]

 90%|████████▉ | 90183/100629 [1:10:47<08:39, 20.11it/s]

 90%|████████▉ | 90186/100629 [1:10:47<10:18, 16.90it/s]

 90%|████████▉ | 90189/100629 [1:10:47<11:23, 15.27it/s]

 90%|████████▉ | 90191/100629 [1:10:48<11:26, 15.21it/s]

 90%|████████▉ | 90195/100629 [1:10:48<09:34, 18.17it/s]

 90%|████████▉ | 90198/100629 [1:10:48<10:13, 17.00it/s]

 90%|████████▉ | 90201/100629 [1:10:48<09:25, 18.44it/s]

 90%|████████▉ | 90203/100629 [1:10:48<09:54, 17.53it/s]

 90%|████████▉ | 90206/100629 [1:10:48<09:12, 18.88it/s]

 90%|████████▉ | 90208/100629 [1:10:48<10:42, 16.22it/s]

 90%|████████▉ | 90212/100629 [1:10:49<09:44, 17.83it/s]

 90%|████████▉ | 90214/100629 [1:10:49<09:40, 17.93it/s]

 90%|████████▉ | 90217/100629 [1:10:49<09:39, 17.96it/s]

 90%|████████▉ | 90220/100629 [1:10:49<09:18, 18.63it/s]

 90%|████████▉ | 90223/100629 [1:10:49<08:27, 20.50it/s]

 90%|████████▉ | 90227/100629 [1:10:49<07:14, 23.94it/s]

 90%|████████▉ | 90230/100629 [1:10:49<07:13, 24.01it/s]

 90%|████████▉ | 90233/100629 [1:10:50<07:41, 22.55it/s]

 90%|████████▉ | 90237/100629 [1:10:50<06:46, 25.55it/s]

 90%|████████▉ | 90240/100629 [1:10:50<07:29, 23.14it/s]

 90%|████████▉ | 90243/100629 [1:10:50<08:13, 21.03it/s]

 90%|████████▉ | 90246/100629 [1:10:50<08:18, 20.84it/s]

 90%|████████▉ | 90251/100629 [1:10:50<06:29, 26.61it/s]

 90%|████████▉ | 90254/100629 [1:10:50<06:45, 25.60it/s]

 90%|████████▉ | 90258/100629 [1:10:51<06:07, 28.25it/s]

 90%|████████▉ | 90261/100629 [1:10:51<06:58, 24.80it/s]

 90%|████████▉ | 90264/100629 [1:10:51<06:57, 24.85it/s]

 90%|████████▉ | 90267/100629 [1:10:51<07:13, 23.92it/s]

 90%|████████▉ | 90270/100629 [1:10:51<07:34, 22.79it/s]

 90%|████████▉ | 90273/100629 [1:10:51<07:13, 23.91it/s]

 90%|████████▉ | 90276/100629 [1:10:51<08:25, 20.48it/s]

 90%|████████▉ | 90279/100629 [1:10:52<09:17, 18.57it/s]

 90%|████████▉ | 90281/100629 [1:10:52<09:37, 17.91it/s]

 90%|████████▉ | 90284/100629 [1:10:52<08:58, 19.22it/s]

 90%|████████▉ | 90289/100629 [1:10:52<06:58, 24.71it/s]

 90%|████████▉ | 90293/100629 [1:10:52<06:20, 27.15it/s]

 90%|████████▉ | 90296/100629 [1:10:52<06:36, 26.07it/s]

 90%|████████▉ | 90299/100629 [1:10:52<07:35, 22.67it/s]

 90%|████████▉ | 90302/100629 [1:10:53<08:12, 20.97it/s]

 90%|████████▉ | 90305/100629 [1:10:53<08:14, 20.89it/s]

 90%|████████▉ | 90308/100629 [1:10:53<09:10, 18.76it/s]

 90%|████████▉ | 90310/100629 [1:10:53<09:29, 18.12it/s]

 90%|████████▉ | 90313/100629 [1:10:53<08:48, 19.53it/s]

 90%|████████▉ | 90317/100629 [1:10:53<07:24, 23.18it/s]

 90%|████████▉ | 90321/100629 [1:10:54<07:51, 21.85it/s]

 90%|████████▉ | 90324/100629 [1:10:54<08:07, 21.12it/s]

 90%|████████▉ | 90327/100629 [1:10:54<08:58, 19.12it/s]

 90%|████████▉ | 90329/100629 [1:10:54<09:44, 17.61it/s]

 90%|████████▉ | 90331/100629 [1:10:54<10:07, 16.94it/s]

 90%|████████▉ | 90333/100629 [1:10:54<13:10, 13.02it/s]

 90%|████████▉ | 90335/100629 [1:10:55<12:05, 14.20it/s]

 90%|████████▉ | 90338/100629 [1:10:55<10:41, 16.05it/s]

 90%|████████▉ | 90341/100629 [1:10:55<09:18, 18.41it/s]

 90%|████████▉ | 90344/100629 [1:10:55<08:51, 19.36it/s]

 90%|████████▉ | 90347/100629 [1:10:55<10:43, 15.97it/s]

 90%|████████▉ | 90349/100629 [1:10:55<11:23, 15.04it/s]

 90%|████████▉ | 90352/100629 [1:10:55<10:07, 16.91it/s]

 90%|████████▉ | 90354/100629 [1:10:56<11:44, 14.58it/s]

 90%|████████▉ | 90356/100629 [1:10:56<10:57, 15.63it/s]

 90%|████████▉ | 90358/100629 [1:10:56<10:42, 15.99it/s]

 90%|████████▉ | 90362/100629 [1:10:56<08:37, 19.85it/s]

 90%|████████▉ | 90365/100629 [1:10:56<08:02, 21.29it/s]

 90%|████████▉ | 90368/100629 [1:10:56<08:00, 21.35it/s]

 90%|████████▉ | 90371/100629 [1:10:56<07:23, 23.11it/s]

 90%|████████▉ | 90374/100629 [1:10:57<07:38, 22.34it/s]

 90%|████████▉ | 90380/100629 [1:10:57<05:49, 29.33it/s]

 90%|████████▉ | 90384/100629 [1:10:57<05:48, 29.43it/s]

 90%|████████▉ | 90389/100629 [1:10:57<05:10, 32.94it/s]

 90%|████████▉ | 90395/100629 [1:10:57<04:31, 37.65it/s]

 90%|████████▉ | 90399/100629 [1:10:57<05:58, 28.56it/s]

 90%|████████▉ | 90403/100629 [1:10:57<06:17, 27.06it/s]

 90%|████████▉ | 90406/100629 [1:10:58<07:28, 22.78it/s]

 90%|████████▉ | 90409/100629 [1:10:58<07:35, 22.42it/s]

 90%|████████▉ | 90412/100629 [1:10:58<08:21, 20.36it/s]

 90%|████████▉ | 90416/100629 [1:10:58<07:19, 23.24it/s]

 90%|████████▉ | 90419/100629 [1:10:58<07:28, 22.75it/s]

 90%|████████▉ | 90423/100629 [1:10:58<06:39, 25.56it/s]

 90%|████████▉ | 90426/100629 [1:10:59<07:24, 22.95it/s]

 90%|████████▉ | 90429/100629 [1:10:59<07:16, 23.38it/s]

 90%|████████▉ | 90432/100629 [1:10:59<07:49, 21.73it/s]

 90%|████████▉ | 90435/100629 [1:10:59<07:40, 22.12it/s]

 90%|████████▉ | 90438/100629 [1:10:59<07:16, 23.35it/s]

 90%|████████▉ | 90441/100629 [1:10:59<08:39, 19.60it/s]

 90%|████████▉ | 90444/100629 [1:10:59<09:23, 18.07it/s]

 90%|████████▉ | 90447/100629 [1:11:00<09:09, 18.52it/s]

 90%|████████▉ | 90450/100629 [1:11:00<08:14, 20.57it/s]

 90%|████████▉ | 90453/100629 [1:11:00<09:59, 16.96it/s]

 90%|████████▉ | 90457/100629 [1:11:00<08:42, 19.46it/s]

 90%|████████▉ | 90461/100629 [1:11:00<07:22, 22.97it/s]

 90%|████████▉ | 90464/100629 [1:11:00<07:15, 23.33it/s]

 90%|████████▉ | 90468/100629 [1:11:01<06:42, 25.25it/s]

 90%|████████▉ | 90471/100629 [1:11:01<06:30, 26.01it/s]

 90%|████████▉ | 90474/100629 [1:11:01<06:24, 26.44it/s]

 90%|████████▉ | 90477/100629 [1:11:01<07:12, 23.48it/s]

 90%|████████▉ | 90480/100629 [1:11:01<07:02, 24.04it/s]

 90%|████████▉ | 90484/100629 [1:11:01<06:08, 27.53it/s]

 90%|████████▉ | 90487/100629 [1:11:01<06:20, 26.66it/s]

 90%|████████▉ | 90490/100629 [1:11:01<06:41, 25.24it/s]

 90%|████████▉ | 90494/100629 [1:11:02<06:42, 25.20it/s]

 90%|████████▉ | 90497/100629 [1:11:02<06:50, 24.69it/s]

 90%|████████▉ | 90501/100629 [1:11:02<06:50, 24.70it/s]

 90%|████████▉ | 90505/100629 [1:11:02<06:41, 25.19it/s]

 90%|████████▉ | 90508/100629 [1:11:02<06:45, 24.93it/s]

 90%|████████▉ | 90511/100629 [1:11:02<07:34, 22.27it/s]

 90%|████████▉ | 90514/100629 [1:11:02<07:03, 23.87it/s]

 90%|████████▉ | 90517/100629 [1:11:03<08:20, 20.20it/s]

 90%|████████▉ | 90520/100629 [1:11:03<07:54, 21.30it/s]

 90%|████████▉ | 90523/100629 [1:11:03<07:48, 21.55it/s]

 90%|████████▉ | 90528/100629 [1:11:03<07:43, 21.79it/s]

 90%|████████▉ | 90532/100629 [1:11:03<06:53, 24.44it/s]

 90%|████████▉ | 90535/100629 [1:11:03<06:43, 25.03it/s]

 90%|████████▉ | 90538/100629 [1:11:04<09:35, 17.54it/s]

 90%|████████▉ | 90541/100629 [1:11:04<10:55, 15.39it/s]

 90%|████████▉ | 90544/100629 [1:11:04<09:54, 16.97it/s]

 90%|████████▉ | 90547/100629 [1:11:04<09:05, 18.47it/s]

 90%|████████▉ | 90550/100629 [1:11:04<11:14, 14.94it/s]

 90%|████████▉ | 90552/100629 [1:11:05<11:35, 14.50it/s]

 90%|████████▉ | 90555/100629 [1:11:05<10:32, 15.92it/s]

 90%|████████▉ | 90558/100629 [1:11:05<09:08, 18.37it/s]

 90%|████████▉ | 90562/100629 [1:11:05<08:44, 19.20it/s]

 90%|████████▉ | 90565/100629 [1:11:05<10:01, 16.72it/s]

 90%|█████████ | 90568/100629 [1:11:05<09:10, 18.27it/s]

 90%|█████████ | 90572/100629 [1:11:06<07:49, 21.42it/s]

 90%|█████████ | 90575/100629 [1:11:06<08:02, 20.83it/s]

 90%|█████████ | 90578/100629 [1:11:06<07:29, 22.35it/s]

 90%|█████████ | 90581/100629 [1:11:06<07:24, 22.61it/s]

 90%|█████████ | 90584/100629 [1:11:06<07:25, 22.56it/s]

 90%|█████████ | 90587/100629 [1:11:06<08:29, 19.73it/s]

 90%|█████████ | 90590/100629 [1:11:06<08:32, 19.60it/s]

 90%|█████████ | 90595/100629 [1:11:07<07:03, 23.70it/s]

 90%|█████████ | 90599/100629 [1:11:07<06:52, 24.29it/s]

 90%|█████████ | 90602/100629 [1:11:07<06:49, 24.50it/s]

 90%|█████████ | 90605/100629 [1:11:07<08:32, 19.57it/s]

 90%|█████████ | 90608/100629 [1:11:07<09:26, 17.68it/s]

 90%|█████████ | 90611/100629 [1:11:07<09:20, 17.87it/s]

 90%|█████████ | 90614/100629 [1:11:08<08:32, 19.54it/s]

 90%|█████████ | 90617/100629 [1:11:08<08:58, 18.60it/s]

 90%|█████████ | 90619/100629 [1:11:08<08:50, 18.87it/s]

 90%|█████████ | 90622/100629 [1:11:08<08:51, 18.81it/s]

 90%|█████████ | 90624/100629 [1:11:08<09:41, 17.20it/s]

 90%|█████████ | 90626/100629 [1:11:08<09:30, 17.54it/s]

 90%|█████████ | 90628/100629 [1:11:08<11:32, 14.44it/s]

 90%|█████████ | 90630/100629 [1:11:09<10:49, 15.39it/s]

 90%|█████████ | 90632/100629 [1:11:09<11:23, 14.63it/s]

 90%|█████████ | 90637/100629 [1:11:09<07:34, 21.98it/s]

 90%|█████████ | 90641/100629 [1:11:09<07:01, 23.69it/s]

 90%|█████████ | 90644/100629 [1:11:09<07:12, 23.07it/s]

 90%|█████████ | 90647/100629 [1:11:09<07:26, 22.37it/s]

 90%|█████████ | 90651/100629 [1:11:09<06:25, 25.88it/s]

 90%|█████████ | 90655/100629 [1:11:10<06:39, 24.96it/s]

 90%|█████████ | 90658/100629 [1:11:10<07:23, 22.47it/s]

 90%|█████████ | 90661/100629 [1:11:10<08:42, 19.06it/s]

 90%|█████████ | 90667/100629 [1:11:10<06:25, 25.84it/s]

 90%|█████████ | 90670/100629 [1:11:10<08:08, 20.38it/s]

 90%|█████████ | 90674/100629 [1:11:10<07:21, 22.57it/s]

 90%|█████████ | 90677/100629 [1:11:11<07:42, 21.54it/s]

 90%|█████████ | 90682/100629 [1:11:11<06:07, 27.09it/s]

 90%|█████████ | 90686/100629 [1:11:11<06:06, 27.10it/s]

 90%|█████████ | 90690/100629 [1:11:11<05:40, 29.22it/s]

 90%|█████████ | 90694/100629 [1:11:11<06:24, 25.83it/s]

 90%|█████████ | 90697/100629 [1:11:11<06:45, 24.49it/s]

 90%|█████████ | 90700/100629 [1:11:11<07:41, 21.52it/s]

 90%|█████████ | 90703/100629 [1:11:12<07:57, 20.80it/s]

 90%|█████████ | 90706/100629 [1:11:12<08:02, 20.54it/s]

 90%|█████████ | 90709/100629 [1:11:12<07:55, 20.85it/s]

 90%|█████████ | 90713/100629 [1:11:12<06:57, 23.76it/s]

 90%|█████████ | 90716/100629 [1:11:12<06:50, 24.12it/s]

 90%|█████████ | 90720/100629 [1:11:12<06:00, 27.45it/s]

 90%|█████████ | 90723/100629 [1:11:12<07:42, 21.40it/s]

 90%|█████████ | 90727/100629 [1:11:13<06:44, 24.50it/s]

 90%|█████████ | 90730/100629 [1:11:13<06:50, 24.13it/s]

 90%|█████████ | 90733/100629 [1:11:13<09:24, 17.52it/s]

 90%|█████████ | 90736/100629 [1:11:13<09:15, 17.81it/s]

 90%|█████████ | 90739/100629 [1:11:13<08:57, 18.42it/s]

 90%|█████████ | 90742/100629 [1:11:13<08:30, 19.36it/s]

 90%|█████████ | 90745/100629 [1:11:14<08:05, 20.35it/s]

 90%|█████████ | 90748/100629 [1:11:14<07:48, 21.09it/s]

 90%|█████████ | 90751/100629 [1:11:14<07:10, 22.96it/s]

 90%|█████████ | 90754/100629 [1:11:14<06:43, 24.46it/s]

 90%|█████████ | 90757/100629 [1:11:14<06:32, 25.13it/s]

 90%|█████████ | 90760/100629 [1:11:14<06:13, 26.41it/s]

 90%|█████████ | 90763/100629 [1:11:14<07:55, 20.75it/s]

 90%|█████████ | 90766/100629 [1:11:15<08:06, 20.28it/s]

 90%|█████████ | 90770/100629 [1:11:15<07:15, 22.65it/s]

 90%|█████████ | 90773/100629 [1:11:15<09:11, 17.88it/s]

 90%|█████████ | 90776/100629 [1:11:15<08:16, 19.85it/s]

 90%|█████████ | 90780/100629 [1:11:15<06:48, 24.11it/s]

 90%|█████████ | 90785/100629 [1:11:15<06:06, 26.85it/s]

 90%|█████████ | 90789/100629 [1:11:15<06:09, 26.65it/s]

 90%|█████████ | 90792/100629 [1:11:16<08:08, 20.13it/s]

 90%|█████████ | 90795/100629 [1:11:16<07:27, 21.95it/s]

 90%|█████████ | 90798/100629 [1:11:16<07:42, 21.27it/s]

 90%|█████████ | 90801/100629 [1:11:16<08:32, 19.18it/s]

 90%|█████████ | 90804/100629 [1:11:16<08:32, 19.17it/s]

 90%|█████████ | 90807/100629 [1:11:16<08:37, 18.97it/s]

 90%|█████████ | 90810/100629 [1:11:17<07:45, 21.09it/s]

 90%|█████████ | 90813/100629 [1:11:17<08:13, 19.88it/s]

 90%|█████████ | 90816/100629 [1:11:17<07:36, 21.48it/s]

 90%|█████████ | 90821/100629 [1:11:17<07:12, 22.69it/s]

 90%|█████████ | 90825/100629 [1:11:17<06:42, 24.37it/s]

 90%|█████████ | 90828/100629 [1:11:17<07:34, 21.54it/s]

 90%|█████████ | 90831/100629 [1:11:18<07:29, 21.78it/s]

 90%|█████████ | 90834/100629 [1:11:18<08:26, 19.32it/s]

 90%|█████████ | 90837/100629 [1:11:18<08:21, 19.53it/s]

 90%|█████████ | 90840/100629 [1:11:18<09:38, 16.93it/s]

 90%|█████████ | 90845/100629 [1:11:18<07:38, 21.35it/s]

 90%|█████████ | 90848/100629 [1:11:19<09:06, 17.89it/s]

 90%|█████████ | 90850/100629 [1:11:19<08:55, 18.27it/s]

 90%|█████████ | 90852/100629 [1:11:19<09:05, 17.92it/s]

 90%|█████████ | 90854/100629 [1:11:19<09:25, 17.30it/s]

 90%|█████████ | 90856/100629 [1:11:19<09:42, 16.79it/s]

 90%|█████████ | 90859/100629 [1:11:19<08:33, 19.01it/s]

 90%|█████████ | 90861/100629 [1:11:19<10:49, 15.04it/s]

 90%|█████████ | 90863/100629 [1:11:19<10:55, 14.90it/s]

 90%|█████████ | 90868/100629 [1:11:20<08:34, 18.97it/s]

 90%|█████████ | 90870/100629 [1:11:20<08:36, 18.90it/s]

 90%|█████████ | 90872/100629 [1:11:20<08:52, 18.34it/s]

 90%|█████████ | 90874/100629 [1:11:20<09:29, 17.13it/s]

 90%|█████████ | 90876/100629 [1:11:20<11:53, 13.67it/s]

 90%|█████████ | 90882/100629 [1:11:20<07:35, 21.40it/s]

 90%|█████████ | 90885/100629 [1:11:21<07:23, 21.96it/s]

 90%|█████████ | 90888/100629 [1:11:21<08:19, 19.51it/s]

 90%|█████████ | 90891/100629 [1:11:21<08:00, 20.25it/s]

 90%|█████████ | 90894/100629 [1:11:21<07:16, 22.29it/s]

 90%|█████████ | 90897/100629 [1:11:21<08:12, 19.75it/s]

 90%|█████████ | 90900/100629 [1:11:21<07:56, 20.41it/s]

 90%|█████████ | 90903/100629 [1:11:22<09:21, 17.32it/s]

 90%|█████████ | 90906/100629 [1:11:22<08:53, 18.24it/s]

 90%|█████████ | 90910/100629 [1:11:22<07:16, 22.24it/s]

 90%|█████████ | 90914/100629 [1:11:22<06:13, 26.04it/s]

 90%|█████████ | 90917/100629 [1:11:22<06:10, 26.19it/s]

 90%|█████████ | 90921/100629 [1:11:22<05:46, 28.03it/s]

 90%|█████████ | 90924/100629 [1:11:22<05:48, 27.88it/s]

 90%|█████████ | 90928/100629 [1:11:22<05:42, 28.31it/s]

 90%|█████████ | 90931/100629 [1:11:22<06:16, 25.73it/s]

 90%|█████████ | 90934/100629 [1:11:23<06:09, 26.25it/s]

 90%|█████████ | 90937/100629 [1:11:23<07:17, 22.17it/s]

 90%|█████████ | 90940/100629 [1:11:23<06:55, 23.34it/s]

 90%|█████████ | 90943/100629 [1:11:23<06:42, 24.07it/s]

 90%|█████████ | 90946/100629 [1:11:23<07:28, 21.59it/s]

 90%|█████████ | 90949/100629 [1:11:23<07:44, 20.85it/s]

 90%|█████████ | 90952/100629 [1:11:23<07:47, 20.69it/s]

 90%|█████████ | 90955/100629 [1:11:24<08:43, 18.48it/s]

 90%|█████████ | 90957/100629 [1:11:24<09:03, 17.81it/s]

 90%|█████████ | 90961/100629 [1:11:24<07:35, 21.22it/s]

 90%|█████████ | 90964/100629 [1:11:24<07:20, 21.92it/s]

 90%|█████████ | 90967/100629 [1:11:24<07:40, 20.97it/s]

 90%|█████████ | 90970/100629 [1:11:24<07:51, 20.48it/s]

 90%|█████████ | 90974/100629 [1:11:24<06:31, 24.65it/s]

 90%|█████████ | 90977/100629 [1:11:25<07:02, 22.84it/s]

 90%|█████████ | 90980/100629 [1:11:25<07:47, 20.64it/s]

 90%|█████████ | 90983/100629 [1:11:25<07:23, 21.76it/s]

 90%|█████████ | 90986/100629 [1:11:25<07:49, 20.53it/s]

 90%|█████████ | 90989/100629 [1:11:25<08:20, 19.28it/s]

 90%|█████████ | 90992/100629 [1:11:25<08:21, 19.22it/s]

 90%|█████████ | 90995/100629 [1:11:26<07:47, 20.61it/s]

 90%|█████████ | 90998/100629 [1:11:26<08:31, 18.84it/s]

 90%|█████████ | 91000/100629 [1:11:26<10:26, 15.37it/s]

 90%|█████████ | 91004/100629 [1:11:26<09:22, 17.10it/s]

 90%|█████████ | 91007/100629 [1:11:26<09:20, 17.17it/s]

 90%|█████████ | 91009/100629 [1:11:27<10:27, 15.34it/s]

 90%|█████████ | 91012/100629 [1:11:27<09:17, 17.25it/s]

 90%|█████████ | 91014/100629 [1:11:27<10:16, 15.59it/s]

 90%|█████████ | 91018/100629 [1:11:27<08:35, 18.65it/s]

 90%|█████████ | 91022/100629 [1:11:27<07:51, 20.37it/s]

 90%|█████████ | 91025/100629 [1:11:27<07:48, 20.48it/s]

 90%|█████████ | 91029/100629 [1:11:27<06:34, 24.36it/s]

 90%|█████████ | 91032/100629 [1:11:28<07:23, 21.65it/s]

 90%|█████████ | 91035/100629 [1:11:28<08:22, 19.10it/s]

 90%|█████████ | 91039/100629 [1:11:28<07:08, 22.36it/s]

 90%|█████████ | 91042/100629 [1:11:28<07:13, 22.09it/s]

 90%|█████████ | 91045/100629 [1:11:28<08:44, 18.27it/s]

 90%|█████████ | 91048/100629 [1:11:28<08:11, 19.50it/s]

 90%|█████████ | 91051/100629 [1:11:29<08:13, 19.40it/s]

 90%|█████████ | 91055/100629 [1:11:29<07:00, 22.78it/s]

 90%|█████████ | 91058/100629 [1:11:29<07:07, 22.36it/s]

 90%|█████████ | 91061/100629 [1:11:29<07:36, 20.97it/s]

 90%|█████████ | 91064/100629 [1:11:29<07:47, 20.46it/s]

 90%|█████████ | 91067/100629 [1:11:29<09:05, 17.53it/s]

 90%|█████████ | 91069/100629 [1:11:29<08:54, 17.90it/s]

 91%|█████████ | 91072/100629 [1:11:30<08:39, 18.40it/s]

 91%|█████████ | 91074/100629 [1:11:30<09:07, 17.44it/s]

 91%|█████████ | 91077/100629 [1:11:30<08:04, 19.74it/s]

 91%|█████████ | 91080/100629 [1:11:30<07:29, 21.24it/s]

 91%|█████████ | 91083/100629 [1:11:30<07:18, 21.79it/s]

 91%|█████████ | 91088/100629 [1:11:30<06:13, 25.55it/s]

 91%|█████████ | 91092/100629 [1:11:30<05:48, 27.33it/s]

 91%|█████████ | 91095/100629 [1:11:31<13:11, 12.05it/s]

 91%|█████████ | 91098/100629 [1:11:31<11:36, 13.69it/s]

 91%|█████████ | 91101/100629 [1:11:31<10:29, 15.14it/s]

 91%|█████████ | 91104/100629 [1:11:32<11:29, 13.82it/s]

 91%|█████████ | 91106/100629 [1:11:32<11:14, 14.11it/s]

 91%|█████████ | 91108/100629 [1:11:32<11:18, 14.04it/s]

 91%|█████████ | 91111/100629 [1:11:32<09:23, 16.89it/s]

 91%|█████████ | 91113/100629 [1:11:32<09:30, 16.67it/s]

 91%|█████████ | 91115/100629 [1:11:32<09:39, 16.42it/s]

 91%|█████████ | 91117/100629 [1:11:32<10:19, 15.35it/s]

 91%|█████████ | 91120/100629 [1:11:32<08:52, 17.86it/s]

 91%|█████████ | 91122/100629 [1:11:33<08:42, 18.21it/s]

 91%|█████████ | 91124/100629 [1:11:33<08:57, 17.69it/s]

 91%|█████████ | 91128/100629 [1:11:33<07:40, 20.64it/s]

 91%|█████████ | 91132/100629 [1:11:33<06:27, 24.51it/s]

 91%|█████████ | 91135/100629 [1:11:33<07:43, 20.49it/s]

 91%|█████████ | 91138/100629 [1:11:33<07:40, 20.59it/s]

 91%|█████████ | 91142/100629 [1:11:33<07:13, 21.86it/s]

 91%|█████████ | 91145/100629 [1:11:34<07:46, 20.34it/s]

 91%|█████████ | 91149/100629 [1:11:34<06:56, 22.78it/s]

 91%|█████████ | 91152/100629 [1:11:34<07:45, 20.37it/s]

 91%|█████████ | 91155/100629 [1:11:34<07:13, 21.88it/s]

 91%|█████████ | 91158/100629 [1:11:34<07:54, 19.94it/s]

 91%|█████████ | 91161/100629 [1:11:34<07:21, 21.42it/s]

 91%|█████████ | 91164/100629 [1:11:35<07:09, 22.02it/s]

 91%|█████████ | 91167/100629 [1:11:35<06:51, 22.98it/s]

 91%|█████████ | 91170/100629 [1:11:35<06:35, 23.93it/s]

 91%|█████████ | 91173/100629 [1:11:35<06:46, 23.25it/s]

 91%|█████████ | 91176/100629 [1:11:35<07:54, 19.94it/s]

 91%|█████████ | 91181/100629 [1:11:35<06:03, 25.97it/s]

 91%|█████████ | 91185/100629 [1:11:35<05:38, 27.89it/s]

 91%|█████████ | 91188/100629 [1:11:35<05:45, 27.34it/s]

 91%|█████████ | 91192/100629 [1:11:36<05:15, 29.93it/s]

 91%|█████████ | 91196/100629 [1:11:36<06:01, 26.12it/s]

 91%|█████████ | 91201/100629 [1:11:36<05:15, 29.91it/s]

 91%|█████████ | 91205/100629 [1:11:36<05:06, 30.74it/s]

 91%|█████████ | 91209/100629 [1:11:36<06:40, 23.50it/s]

 91%|█████████ | 91212/100629 [1:11:37<08:07, 19.33it/s]

 91%|█████████ | 91216/100629 [1:11:37<06:54, 22.72it/s]

 91%|█████████ | 91219/100629 [1:11:37<06:59, 22.44it/s]

 91%|█████████ | 91222/100629 [1:11:37<07:04, 22.18it/s]

 91%|█████████ | 91225/100629 [1:11:37<07:13, 21.67it/s]

 91%|█████████ | 91228/100629 [1:11:37<07:20, 21.34it/s]

 91%|█████████ | 91231/100629 [1:11:37<06:54, 22.66it/s]

 91%|█████████ | 91234/100629 [1:11:37<07:41, 20.34it/s]

 91%|█████████ | 91237/100629 [1:11:38<09:02, 17.30it/s]

 91%|█████████ | 91240/100629 [1:11:38<08:59, 17.42it/s]

 91%|█████████ | 91242/100629 [1:11:38<09:28, 16.52it/s]

 91%|█████████ | 91246/100629 [1:11:38<08:05, 19.31it/s]

 91%|█████████ | 91249/100629 [1:11:38<07:25, 21.07it/s]

 91%|█████████ | 91252/100629 [1:11:38<07:00, 22.28it/s]

 91%|█████████ | 91256/100629 [1:11:39<06:51, 22.79it/s]

 91%|█████████ | 91259/100629 [1:11:39<07:26, 20.99it/s]

 91%|█████████ | 91262/100629 [1:11:39<07:48, 19.99it/s]

 91%|█████████ | 91265/100629 [1:11:39<08:17, 18.83it/s]

 91%|█████████ | 91268/100629 [1:11:39<07:29, 20.81it/s]

 91%|█████████ | 91271/100629 [1:11:39<07:45, 20.10it/s]

 91%|█████████ | 91274/100629 [1:11:40<08:43, 17.86it/s]

 91%|█████████ | 91276/100629 [1:11:40<09:04, 17.19it/s]

 91%|█████████ | 91279/100629 [1:11:40<08:29, 18.35it/s]

 91%|█████████ | 91281/100629 [1:11:40<08:26, 18.44it/s]

 91%|█████████ | 91283/100629 [1:11:40<09:17, 16.75it/s]

 91%|█████████ | 91286/100629 [1:11:40<08:11, 19.01it/s]

 91%|█████████ | 91288/100629 [1:11:40<09:16, 16.79it/s]

 91%|█████████ | 91290/100629 [1:11:41<09:20, 16.65it/s]

 91%|█████████ | 91294/100629 [1:11:41<07:35, 20.47it/s]

 91%|█████████ | 91297/100629 [1:11:41<07:54, 19.69it/s]

 91%|█████████ | 91300/100629 [1:11:41<07:13, 21.54it/s]

 91%|█████████ | 91303/100629 [1:11:41<07:28, 20.79it/s]

 91%|█████████ | 91306/100629 [1:11:41<07:28, 20.77it/s]

 91%|█████████ | 91309/100629 [1:11:41<07:20, 21.14it/s]

 91%|█████████ | 91312/100629 [1:11:41<07:14, 21.45it/s]

 91%|█████████ | 91315/100629 [1:11:42<07:58, 19.47it/s]

 91%|█████████ | 91319/100629 [1:11:42<06:45, 22.96it/s]

 91%|█████████ | 91323/100629 [1:11:42<05:46, 26.84it/s]

 91%|█████████ | 91327/100629 [1:11:42<05:09, 30.06it/s]

 91%|█████████ | 91331/100629 [1:11:42<07:20, 21.13it/s]

 91%|█████████ | 91334/100629 [1:11:42<07:55, 19.55it/s]

 91%|█████████ | 91337/100629 [1:11:43<08:04, 19.17it/s]

 91%|█████████ | 91341/100629 [1:11:43<07:36, 20.33it/s]

 91%|█████████ | 91344/100629 [1:11:43<08:00, 19.33it/s]

 91%|█████████ | 91348/100629 [1:11:43<06:56, 22.29it/s]

 91%|█████████ | 91351/100629 [1:11:43<07:08, 21.66it/s]

 91%|█████████ | 91355/100629 [1:11:43<06:16, 24.61it/s]

 91%|█████████ | 91358/100629 [1:11:44<07:00, 22.04it/s]

 91%|█████████ | 91361/100629 [1:11:44<07:23, 20.90it/s]

 91%|█████████ | 91365/100629 [1:11:44<08:08, 18.95it/s]

 91%|█████████ | 91368/100629 [1:11:44<08:21, 18.48it/s]

 91%|█████████ | 91373/100629 [1:11:44<06:55, 22.28it/s]

 91%|█████████ | 91376/100629 [1:11:44<07:25, 20.75it/s]

 91%|█████████ | 91379/100629 [1:11:45<08:19, 18.51it/s]

 91%|█████████ | 91381/100629 [1:11:45<08:41, 17.74it/s]

 91%|█████████ | 91385/100629 [1:11:45<07:07, 21.65it/s]

 91%|█████████ | 91388/100629 [1:11:45<08:10, 18.84it/s]

 91%|█████████ | 91392/100629 [1:11:45<07:02, 21.89it/s]

 91%|█████████ | 91395/100629 [1:11:45<07:20, 20.94it/s]

 91%|█████████ | 91398/100629 [1:11:46<07:41, 20.02it/s]

 91%|█████████ | 91401/100629 [1:11:46<07:35, 20.25it/s]

 91%|█████████ | 91404/100629 [1:11:46<10:03, 15.28it/s]

 91%|█████████ | 91407/100629 [1:11:46<08:50, 17.40it/s]

 91%|█████████ | 91410/100629 [1:11:46<08:31, 18.02it/s]

 91%|█████████ | 91413/100629 [1:11:46<07:54, 19.40it/s]

 91%|█████████ | 91417/100629 [1:11:47<06:34, 23.32it/s]

 91%|█████████ | 91420/100629 [1:11:47<07:00, 21.88it/s]

 91%|█████████ | 91423/100629 [1:11:47<07:27, 20.56it/s]

 91%|█████████ | 91426/100629 [1:11:47<08:18, 18.47it/s]

 91%|█████████ | 91428/100629 [1:11:47<08:51, 17.31it/s]

 91%|█████████ | 91431/100629 [1:11:47<07:48, 19.63it/s]

 91%|█████████ | 91434/100629 [1:11:48<07:51, 19.51it/s]

 91%|█████████ | 91437/100629 [1:11:48<09:34, 16.01it/s]

 91%|█████████ | 91439/100629 [1:11:48<09:15, 16.54it/s]

 91%|█████████ | 91441/100629 [1:11:48<09:12, 16.64it/s]

 91%|█████████ | 91443/100629 [1:11:48<09:00, 16.99it/s]

 91%|█████████ | 91447/100629 [1:11:48<07:34, 20.19it/s]

 91%|█████████ | 91450/100629 [1:11:48<06:52, 22.23it/s]

 91%|█████████ | 91453/100629 [1:11:48<06:50, 22.37it/s]

 91%|█████████ | 91456/100629 [1:11:49<06:19, 24.14it/s]

 91%|█████████ | 91459/100629 [1:11:49<06:56, 22.01it/s]

 91%|█████████ | 91462/100629 [1:11:49<06:54, 22.11it/s]

 91%|█████████ | 91465/100629 [1:11:49<08:24, 18.17it/s]

 91%|█████████ | 91468/100629 [1:11:49<08:04, 18.92it/s]

 91%|█████████ | 91471/100629 [1:11:49<07:42, 19.81it/s]

 91%|█████████ | 91474/100629 [1:11:50<08:15, 18.49it/s]

 91%|█████████ | 91477/100629 [1:11:50<07:29, 20.38it/s]

 91%|█████████ | 91480/100629 [1:11:50<07:24, 20.57it/s]

 91%|█████████ | 91483/100629 [1:11:50<07:38, 19.95it/s]

 91%|█████████ | 91486/100629 [1:11:50<07:06, 21.43it/s]

 91%|█████████ | 91489/100629 [1:11:50<07:12, 21.13it/s]

 91%|█████████ | 91492/100629 [1:11:50<06:36, 23.02it/s]

 91%|█████████ | 91495/100629 [1:11:51<06:55, 21.97it/s]

 91%|█████████ | 91498/100629 [1:11:51<07:19, 20.80it/s]

 91%|█████████ | 91501/100629 [1:11:51<08:20, 18.25it/s]

 91%|█████████ | 91503/100629 [1:11:51<08:12, 18.54it/s]

 91%|█████████ | 91506/100629 [1:11:51<07:43, 19.69it/s]

 91%|█████████ | 91509/100629 [1:11:51<07:13, 21.02it/s]

 91%|█████████ | 91512/100629 [1:11:51<07:54, 19.20it/s]

 91%|█████████ | 91515/100629 [1:11:52<07:04, 21.47it/s]

 91%|█████████ | 91518/100629 [1:11:52<06:27, 23.50it/s]

 91%|█████████ | 91521/100629 [1:11:52<06:02, 25.15it/s]

 91%|█████████ | 91524/100629 [1:11:52<07:59, 18.97it/s]

 91%|█████████ | 91527/100629 [1:11:52<08:13, 18.45it/s]

 91%|█████████ | 91531/100629 [1:11:52<06:42, 22.60it/s]

 91%|█████████ | 91534/100629 [1:11:52<06:26, 23.50it/s]

 91%|█████████ | 91538/100629 [1:11:53<05:43, 26.48it/s]

 91%|█████████ | 91541/100629 [1:11:53<05:32, 27.32it/s]

 91%|█████████ | 91544/100629 [1:11:53<05:57, 25.42it/s]

 91%|█████████ | 91547/100629 [1:11:53<06:10, 24.52it/s]

 91%|█████████ | 91551/100629 [1:11:53<05:41, 26.61it/s]

 91%|█████████ | 91554/100629 [1:11:53<05:40, 26.66it/s]

 91%|█████████ | 91558/100629 [1:11:53<05:22, 28.10it/s]

 91%|█████████ | 91561/100629 [1:11:53<05:42, 26.44it/s]

 91%|█████████ | 91564/100629 [1:11:54<06:22, 23.71it/s]

 91%|█████████ | 91567/100629 [1:11:54<07:06, 21.27it/s]

 91%|█████████ | 91570/100629 [1:11:54<07:12, 20.97it/s]

 91%|█████████ | 91573/100629 [1:11:54<08:21, 18.06it/s]

 91%|█████████ | 91577/100629 [1:11:54<07:04, 21.31it/s]

 91%|█████████ | 91580/100629 [1:11:54<07:35, 19.88it/s]

 91%|█████████ | 91584/100629 [1:11:55<06:35, 22.88it/s]

 91%|█████████ | 91587/100629 [1:11:55<07:15, 20.74it/s]

 91%|█████████ | 91591/100629 [1:11:55<06:40, 22.56it/s]

 91%|█████████ | 91594/100629 [1:11:55<07:07, 21.13it/s]

 91%|█████████ | 91598/100629 [1:11:55<06:31, 23.07it/s]

 91%|█████████ | 91601/100629 [1:11:55<08:19, 18.09it/s]

 91%|█████████ | 91604/100629 [1:11:56<07:47, 19.29it/s]

 91%|█████████ | 91609/100629 [1:11:56<05:55, 25.36it/s]

 91%|█████████ | 91613/100629 [1:11:56<05:41, 26.39it/s]

 91%|█████████ | 91616/100629 [1:11:56<05:43, 26.26it/s]

 91%|█████████ | 91619/100629 [1:11:56<06:25, 23.38it/s]

 91%|█████████ | 91622/100629 [1:11:56<06:38, 22.62it/s]

 91%|█████████ | 91625/100629 [1:11:56<07:00, 21.40it/s]

 91%|█████████ | 91628/100629 [1:11:56<06:44, 22.26it/s]

 91%|█████████ | 91632/100629 [1:11:57<05:49, 25.77it/s]

 91%|█████████ | 91635/100629 [1:11:57<06:13, 24.06it/s]

 91%|█████████ | 91638/100629 [1:11:57<07:55, 18.91it/s]

 91%|█████████ | 91641/100629 [1:11:57<07:06, 21.09it/s]

 91%|█████████ | 91644/100629 [1:11:57<08:42, 17.21it/s]

 91%|█████████ | 91647/100629 [1:11:58<08:28, 17.66it/s]

 91%|█████████ | 91650/100629 [1:11:58<07:46, 19.26it/s]

 91%|█████████ | 91653/100629 [1:11:58<08:05, 18.50it/s]

 91%|█████████ | 91656/100629 [1:11:58<07:38, 19.58it/s]

 91%|█████████ | 91660/100629 [1:11:58<07:42, 19.37it/s]

 91%|█████████ | 91663/100629 [1:11:58<07:31, 19.84it/s]

 91%|█████████ | 91666/100629 [1:11:58<07:14, 20.61it/s]

 91%|█████████ | 91669/100629 [1:11:59<06:50, 21.81it/s]

 91%|█████████ | 91672/100629 [1:11:59<07:04, 21.09it/s]

 91%|█████████ | 91675/100629 [1:11:59<07:15, 20.57it/s]

 91%|█████████ | 91678/100629 [1:11:59<09:06, 16.38it/s]

 91%|█████████ | 91681/100629 [1:11:59<08:11, 18.21it/s]

 91%|█████████ | 91684/100629 [1:11:59<08:31, 17.50it/s]

 91%|█████████ | 91688/100629 [1:12:00<06:57, 21.44it/s]

 91%|█████████ | 91691/100629 [1:12:00<07:31, 19.79it/s]

 91%|█████████ | 91696/100629 [1:12:00<05:56, 25.07it/s]

 91%|█████████ | 91700/100629 [1:12:00<05:21, 27.74it/s]

 91%|█████████ | 91704/100629 [1:12:00<06:32, 22.71it/s]

 91%|█████████ | 91707/100629 [1:12:00<06:17, 23.63it/s]

 91%|█████████ | 91710/100629 [1:12:00<06:29, 22.89it/s]

 91%|█████████ | 91713/100629 [1:12:01<06:48, 21.81it/s]

 91%|█████████ | 91717/100629 [1:12:01<06:04, 24.42it/s]

 91%|█████████ | 91721/100629 [1:12:01<05:18, 27.99it/s]

 91%|█████████ | 91724/100629 [1:12:01<05:27, 27.23it/s]

 91%|█████████ | 91727/100629 [1:12:01<05:46, 25.72it/s]

 91%|█████████ | 91730/100629 [1:12:01<06:16, 23.64it/s]

 91%|█████████ | 91733/100629 [1:12:01<06:13, 23.84it/s]

 91%|█████████ | 91736/100629 [1:12:02<06:52, 21.54it/s]

 91%|█████████ | 91739/100629 [1:12:02<06:47, 21.83it/s]

 91%|█████████ | 91742/100629 [1:12:02<07:18, 20.26it/s]

 91%|█████████ | 91745/100629 [1:12:02<07:52, 18.82it/s]

 91%|█████████ | 91748/100629 [1:12:02<07:50, 18.89it/s]

 91%|█████████ | 91751/100629 [1:12:02<07:29, 19.77it/s]

 91%|█████████ | 91754/100629 [1:12:02<07:32, 19.61it/s]

 91%|█████████ | 91757/100629 [1:12:03<07:16, 20.34it/s]

 91%|█████████ | 91760/100629 [1:12:03<08:29, 17.42it/s]

 91%|█████████ | 91763/100629 [1:12:03<08:00, 18.46it/s]

 91%|█████████ | 91765/100629 [1:12:03<08:04, 18.30it/s]

 91%|█████████ | 91767/100629 [1:12:03<08:27, 17.47it/s]

 91%|█████████ | 91770/100629 [1:12:03<07:53, 18.69it/s]

 91%|█████████ | 91772/100629 [1:12:03<07:52, 18.73it/s]

 91%|█████████ | 91775/100629 [1:12:04<08:51, 16.66it/s]

 91%|█████████ | 91779/100629 [1:12:04<07:05, 20.79it/s]

 91%|█████████ | 91783/100629 [1:12:04<05:55, 24.89it/s]

 91%|█████████ | 91786/100629 [1:12:04<06:10, 23.90it/s]

 91%|█████████ | 91789/100629 [1:12:04<06:36, 22.31it/s]

 91%|█████████ | 91793/100629 [1:12:04<05:47, 25.43it/s]

 91%|█████████ | 91797/100629 [1:12:04<05:25, 27.14it/s]

 91%|█████████ | 91800/100629 [1:12:05<05:36, 26.25it/s]

 91%|█████████ | 91804/100629 [1:12:05<06:02, 24.35it/s]

 91%|█████████ | 91807/100629 [1:12:05<07:05, 20.74it/s]

 91%|█████████ | 91811/100629 [1:12:05<06:07, 24.01it/s]

 91%|█████████ | 91814/100629 [1:12:05<05:52, 24.99it/s]

 91%|█████████ | 91817/100629 [1:12:05<08:10, 17.95it/s]

 91%|█████████ | 91820/100629 [1:12:06<08:51, 16.58it/s]

 91%|█████████▏| 91824/100629 [1:12:06<07:37, 19.25it/s]

 91%|█████████▏| 91827/100629 [1:12:06<07:51, 18.69it/s]

 91%|█████████▏| 91830/100629 [1:12:06<07:20, 19.99it/s]

 91%|█████████▏| 91834/100629 [1:12:06<06:33, 22.33it/s]

 91%|█████████▏| 91837/100629 [1:12:06<06:15, 23.41it/s]

 91%|█████████▏| 91840/100629 [1:12:07<07:39, 19.13it/s]

 91%|█████████▏| 91844/100629 [1:12:07<06:40, 21.91it/s]

 91%|█████████▏| 91847/100629 [1:12:07<06:41, 21.87it/s]

 91%|█████████▏| 91850/100629 [1:12:07<06:53, 21.23it/s]

 91%|█████████▏| 91853/100629 [1:12:07<07:35, 19.28it/s]

 91%|█████████▏| 91856/100629 [1:12:07<08:03, 18.14it/s]

 91%|█████████▏| 91858/100629 [1:12:08<09:18, 15.70it/s]

 91%|█████████▏| 91860/100629 [1:12:08<09:18, 15.70it/s]

 91%|█████████▏| 91862/100629 [1:12:08<09:01, 16.19it/s]

 91%|█████████▏| 91866/100629 [1:12:08<06:59, 20.90it/s]

 91%|█████████▏| 91869/100629 [1:12:08<08:00, 18.21it/s]

 91%|█████████▏| 91871/100629 [1:12:08<08:44, 16.68it/s]

 91%|█████████▏| 91874/100629 [1:12:08<07:52, 18.52it/s]

 91%|█████████▏| 91876/100629 [1:12:09<07:44, 18.84it/s]

 91%|█████████▏| 91880/100629 [1:12:09<06:36, 22.06it/s]

 91%|█████████▏| 91884/100629 [1:12:09<06:06, 23.87it/s]

 91%|█████████▏| 91887/100629 [1:12:09<06:12, 23.46it/s]

 91%|█████████▏| 91890/100629 [1:12:09<06:21, 22.89it/s]

 91%|█████████▏| 91893/100629 [1:12:09<06:28, 22.47it/s]

 91%|█████████▏| 91896/100629 [1:12:09<07:14, 20.08it/s]

 91%|█████████▏| 91899/100629 [1:12:10<07:03, 20.63it/s]

 91%|█████████▏| 91902/100629 [1:12:10<09:08, 15.90it/s]

 91%|█████████▏| 91907/100629 [1:12:10<06:50, 21.25it/s]

 91%|█████████▏| 91912/100629 [1:12:10<05:31, 26.30it/s]

 91%|█████████▏| 91916/100629 [1:12:10<06:34, 22.10it/s]

 91%|█████████▏| 91919/100629 [1:12:11<07:13, 20.08it/s]

 91%|█████████▏| 91923/100629 [1:12:11<06:19, 22.93it/s]

 91%|█████████▏| 91926/100629 [1:12:11<06:11, 23.42it/s]

 91%|█████████▏| 91929/100629 [1:12:11<06:17, 23.06it/s]

 91%|█████████▏| 91932/100629 [1:12:11<06:28, 22.38it/s]

 91%|█████████▏| 91935/100629 [1:12:11<07:12, 20.08it/s]

 91%|█████████▏| 91938/100629 [1:12:11<07:43, 18.74it/s]

 91%|█████████▏| 91940/100629 [1:12:12<08:24, 17.22it/s]

 91%|█████████▏| 91942/100629 [1:12:12<09:07, 15.86it/s]

 91%|█████████▏| 91944/100629 [1:12:12<09:28, 15.29it/s]

 91%|█████████▏| 91946/100629 [1:12:12<09:30, 15.21it/s]

 91%|█████████▏| 91948/100629 [1:12:12<09:02, 15.99it/s]

 91%|█████████▏| 91951/100629 [1:12:12<08:03, 17.94it/s]

 91%|█████████▏| 91954/100629 [1:12:12<07:05, 20.39it/s]

 91%|█████████▏| 91959/100629 [1:12:12<05:25, 26.64it/s]

 91%|█████████▏| 91962/100629 [1:12:13<05:31, 26.11it/s]

 91%|█████████▏| 91965/100629 [1:12:13<05:28, 26.38it/s]

 91%|█████████▏| 91968/100629 [1:12:13<05:41, 25.37it/s]

 91%|█████████▏| 91971/100629 [1:12:13<06:18, 22.87it/s]

 91%|█████████▏| 91975/100629 [1:12:13<06:00, 24.00it/s]

 91%|█████████▏| 91979/100629 [1:12:13<05:13, 27.56it/s]

 91%|█████████▏| 91982/100629 [1:12:13<06:10, 23.36it/s]

 91%|█████████▏| 91986/100629 [1:12:14<05:31, 26.10it/s]

 91%|█████████▏| 91989/100629 [1:12:14<05:39, 25.47it/s]

 91%|█████████▏| 91992/100629 [1:12:14<06:17, 22.85it/s]

 91%|█████████▏| 91995/100629 [1:12:14<05:53, 24.40it/s]

 91%|█████████▏| 91998/100629 [1:12:14<07:07, 20.17it/s]

 91%|█████████▏| 92002/100629 [1:12:14<06:17, 22.87it/s]

 91%|█████████▏| 92006/100629 [1:12:15<06:35, 21.81it/s]

 91%|█████████▏| 92009/100629 [1:12:15<06:51, 20.95it/s]

 91%|█████████▏| 92013/100629 [1:12:15<05:47, 24.83it/s]

 91%|█████████▏| 92016/100629 [1:12:15<06:07, 23.42it/s]

 91%|█████████▏| 92019/100629 [1:12:15<06:05, 23.57it/s]

 91%|█████████▏| 92022/100629 [1:12:15<06:37, 21.65it/s]

 91%|█████████▏| 92025/100629 [1:12:15<06:42, 21.40it/s]

 91%|█████████▏| 92028/100629 [1:12:16<07:17, 19.68it/s]

 91%|█████████▏| 92032/100629 [1:12:16<06:22, 22.49it/s]

 91%|█████████▏| 92035/100629 [1:12:16<06:53, 20.79it/s]

 91%|█████████▏| 92038/100629 [1:12:16<06:29, 22.08it/s]

 91%|█████████▏| 92041/100629 [1:12:16<07:20, 19.51it/s]

 91%|█████████▏| 92044/100629 [1:12:16<06:59, 20.47it/s]

 91%|█████████▏| 92047/100629 [1:12:16<07:35, 18.83it/s]

 91%|█████████▏| 92049/100629 [1:12:17<07:42, 18.55it/s]

 91%|█████████▏| 92051/100629 [1:12:17<07:36, 18.78it/s]

 91%|█████████▏| 92053/100629 [1:12:17<09:10, 15.57it/s]

 91%|█████████▏| 92056/100629 [1:12:17<08:30, 16.81it/s]

 91%|█████████▏| 92058/100629 [1:12:17<08:32, 16.73it/s]

 91%|█████████▏| 92060/100629 [1:12:17<08:37, 16.55it/s]

 91%|█████████▏| 92063/100629 [1:12:17<08:13, 17.36it/s]

 91%|█████████▏| 92065/100629 [1:12:18<08:37, 16.55it/s]

 91%|█████████▏| 92068/100629 [1:12:18<07:55, 18.00it/s]

 91%|█████████▏| 92070/100629 [1:12:18<08:02, 17.76it/s]

 91%|█████████▏| 92073/100629 [1:12:18<07:10, 19.86it/s]

 92%|█████████▏| 92076/100629 [1:12:18<08:10, 17.42it/s]

 92%|█████████▏| 92078/100629 [1:12:18<08:06, 17.58it/s]

 92%|█████████▏| 92081/100629 [1:12:18<07:16, 19.57it/s]

 92%|█████████▏| 92084/100629 [1:12:19<07:51, 18.14it/s]

 92%|█████████▏| 92086/100629 [1:12:19<07:42, 18.47it/s]

 92%|█████████▏| 92089/100629 [1:12:19<07:09, 19.89it/s]

 92%|█████████▏| 92092/100629 [1:12:19<06:43, 21.18it/s]

 92%|█████████▏| 92095/100629 [1:12:19<07:02, 20.18it/s]

 92%|█████████▏| 92098/100629 [1:12:19<06:24, 22.17it/s]

 92%|█████████▏| 92102/100629 [1:12:19<05:51, 24.26it/s]

 92%|█████████▏| 92105/100629 [1:12:20<07:39, 18.56it/s]

 92%|█████████▏| 92108/100629 [1:12:20<07:25, 19.11it/s]

 92%|█████████▏| 92111/100629 [1:12:20<07:51, 18.05it/s]

 92%|█████████▏| 92115/100629 [1:12:20<07:00, 20.24it/s]

 92%|█████████▏| 92118/100629 [1:12:20<06:29, 21.83it/s]

 92%|█████████▏| 92121/100629 [1:12:20<06:45, 20.98it/s]

 92%|█████████▏| 92124/100629 [1:12:21<07:36, 18.63it/s]

 92%|█████████▏| 92128/100629 [1:12:21<06:20, 22.35it/s]

 92%|█████████▏| 92131/100629 [1:12:21<06:38, 21.32it/s]

 92%|█████████▏| 92134/100629 [1:12:21<07:01, 20.14it/s]

 92%|█████████▏| 92137/100629 [1:12:21<07:16, 19.44it/s]

 92%|█████████▏| 92140/100629 [1:12:21<07:01, 20.15it/s]

 92%|█████████▏| 92144/100629 [1:12:21<06:33, 21.54it/s]

 92%|█████████▏| 92147/100629 [1:12:22<06:21, 22.22it/s]

 92%|█████████▏| 92150/100629 [1:12:22<06:35, 21.41it/s]

 92%|█████████▏| 92153/100629 [1:12:22<07:12, 19.62it/s]

 92%|█████████▏| 92156/100629 [1:12:22<07:39, 18.43it/s]

 92%|█████████▏| 92159/100629 [1:12:22<08:35, 16.44it/s]

 92%|█████████▏| 92163/100629 [1:12:23<08:17, 17.03it/s]

 92%|█████████▏| 92166/100629 [1:12:23<07:43, 18.26it/s]

 92%|█████████▏| 92168/100629 [1:12:23<07:50, 17.97it/s]

 92%|█████████▏| 92171/100629 [1:12:23<07:11, 19.60it/s]

 92%|█████████▏| 92174/100629 [1:12:23<06:59, 20.15it/s]

 92%|█████████▏| 92177/100629 [1:12:23<06:36, 21.31it/s]

 92%|█████████▏| 92181/100629 [1:12:23<05:36, 25.07it/s]

 92%|█████████▏| 92186/100629 [1:12:23<04:36, 30.54it/s]

 92%|█████████▏| 92191/100629 [1:12:24<04:39, 30.14it/s]

 92%|█████████▏| 92195/100629 [1:12:24<05:20, 26.29it/s]

 92%|█████████▏| 92198/100629 [1:12:24<05:57, 23.61it/s]

 92%|█████████▏| 92201/100629 [1:12:24<05:56, 23.62it/s]

 92%|█████████▏| 92204/100629 [1:12:24<06:43, 20.88it/s]

 92%|█████████▏| 92207/100629 [1:12:24<06:16, 22.36it/s]

 92%|█████████▏| 92210/100629 [1:12:25<06:25, 21.84it/s]

 92%|█████████▏| 92213/100629 [1:12:25<06:31, 21.49it/s]

 92%|█████████▏| 92216/100629 [1:12:25<06:12, 22.59it/s]

 92%|█████████▏| 92220/100629 [1:12:25<05:59, 23.41it/s]

 92%|█████████▏| 92223/100629 [1:12:25<07:11, 19.47it/s]

 92%|█████████▏| 92226/100629 [1:12:25<07:04, 19.81it/s]

 92%|█████████▏| 92229/100629 [1:12:25<06:27, 21.70it/s]

 92%|█████████▏| 92232/100629 [1:12:26<06:46, 20.67it/s]

 92%|█████████▏| 92236/100629 [1:12:26<06:14, 22.44it/s]

 92%|█████████▏| 92239/100629 [1:12:26<06:07, 22.83it/s]

 92%|█████████▏| 92242/100629 [1:12:26<07:25, 18.84it/s]

 92%|█████████▏| 92247/100629 [1:12:26<06:13, 22.44it/s]

 92%|█████████▏| 92251/100629 [1:12:26<05:42, 24.46it/s]

 92%|█████████▏| 92254/100629 [1:12:27<06:06, 22.86it/s]

 92%|█████████▏| 92257/100629 [1:12:27<06:17, 22.20it/s]

 92%|█████████▏| 92260/100629 [1:12:27<06:03, 23.03it/s]

 92%|█████████▏| 92264/100629 [1:12:27<05:30, 25.32it/s]

 92%|█████████▏| 92268/100629 [1:12:27<05:02, 27.60it/s]

 92%|█████████▏| 92271/100629 [1:12:27<05:01, 27.71it/s]

 92%|█████████▏| 92274/100629 [1:12:27<05:55, 23.48it/s]

 92%|█████████▏| 92277/100629 [1:12:27<05:54, 23.54it/s]

 92%|█████████▏| 92280/100629 [1:12:28<06:40, 20.85it/s]

 92%|█████████▏| 92283/100629 [1:12:28<07:44, 17.98it/s]

 92%|█████████▏| 92285/100629 [1:12:28<07:52, 17.67it/s]

 92%|█████████▏| 92287/100629 [1:12:28<08:12, 16.92it/s]

 92%|█████████▏| 92289/100629 [1:12:28<08:44, 15.90it/s]

 92%|█████████▏| 92292/100629 [1:12:28<07:47, 17.84it/s]

 92%|█████████▏| 92297/100629 [1:12:29<05:51, 23.68it/s]

 92%|█████████▏| 92300/100629 [1:12:29<06:07, 22.68it/s]

 92%|█████████▏| 92304/100629 [1:12:29<05:19, 26.03it/s]

 92%|█████████▏| 92307/100629 [1:12:29<06:24, 21.65it/s]

 92%|█████████▏| 92310/100629 [1:12:29<06:41, 20.74it/s]

 92%|█████████▏| 92313/100629 [1:12:29<06:20, 21.84it/s]

 92%|█████████▏| 92316/100629 [1:12:29<06:05, 22.75it/s]

 92%|█████████▏| 92319/100629 [1:12:30<06:34, 21.09it/s]

 92%|█████████▏| 92322/100629 [1:12:30<07:01, 19.73it/s]

 92%|█████████▏| 92326/100629 [1:12:30<05:50, 23.67it/s]

 92%|█████████▏| 92329/100629 [1:12:30<08:18, 16.66it/s]

 92%|█████████▏| 92332/100629 [1:12:30<07:15, 19.04it/s]

 92%|█████████▏| 92335/100629 [1:12:30<06:30, 21.25it/s]

 92%|█████████▏| 92338/100629 [1:12:31<07:07, 19.39it/s]

 92%|█████████▏| 92341/100629 [1:12:31<07:32, 18.30it/s]

 92%|█████████▏| 92344/100629 [1:12:31<07:04, 19.53it/s]

 92%|█████████▏| 92347/100629 [1:12:31<07:36, 18.13it/s]

 92%|█████████▏| 92349/100629 [1:12:31<07:40, 17.98it/s]

 92%|█████████▏| 92352/100629 [1:12:31<06:44, 20.48it/s]

 92%|█████████▏| 92356/100629 [1:12:31<05:57, 23.14it/s]

 92%|█████████▏| 92359/100629 [1:12:32<06:14, 22.09it/s]

 92%|█████████▏| 92362/100629 [1:12:32<06:07, 22.51it/s]

 92%|█████████▏| 92365/100629 [1:12:32<06:21, 21.66it/s]

 92%|█████████▏| 92368/100629 [1:12:32<06:10, 22.31it/s]

 92%|█████████▏| 92371/100629 [1:12:32<06:40, 20.64it/s]

 92%|█████████▏| 92374/100629 [1:12:32<07:00, 19.64it/s]

 92%|█████████▏| 92377/100629 [1:12:32<07:23, 18.62it/s]

 92%|█████████▏| 92379/100629 [1:12:33<07:45, 17.72it/s]

 92%|█████████▏| 92382/100629 [1:12:33<06:50, 20.10it/s]

 92%|█████████▏| 92385/100629 [1:12:33<06:17, 21.81it/s]

 92%|█████████▏| 92388/100629 [1:12:33<06:44, 20.38it/s]

 92%|█████████▏| 92391/100629 [1:12:33<06:15, 21.97it/s]

 92%|█████████▏| 92394/100629 [1:12:33<06:14, 22.00it/s]

 92%|█████████▏| 92397/100629 [1:12:34<08:25, 16.30it/s]

 92%|█████████▏| 92399/100629 [1:12:35<22:42,  6.04it/s]

 92%|█████████▏| 92402/100629 [1:12:35<16:50,  8.14it/s]

 92%|█████████▏| 92405/100629 [1:12:35<13:02, 10.51it/s]

 92%|█████████▏| 92408/100629 [1:12:35<11:16, 12.15it/s]

 92%|█████████▏| 92411/100629 [1:12:35<09:16, 14.76it/s]

 92%|█████████▏| 92415/100629 [1:12:35<08:02, 17.01it/s]

 92%|█████████▏| 92418/100629 [1:12:35<07:38, 17.90it/s]

 92%|█████████▏| 92423/100629 [1:12:36<05:47, 23.60it/s]

 92%|█████████▏| 92426/100629 [1:12:36<06:25, 21.26it/s]

 92%|█████████▏| 92430/100629 [1:12:36<05:30, 24.77it/s]

 92%|█████████▏| 92433/100629 [1:12:36<05:56, 23.00it/s]

 92%|█████████▏| 92436/100629 [1:12:36<05:43, 23.88it/s]

 92%|█████████▏| 92440/100629 [1:12:36<05:01, 27.12it/s]

 92%|█████████▏| 92443/100629 [1:12:36<05:36, 24.30it/s]

 92%|█████████▏| 92446/100629 [1:12:37<06:21, 21.45it/s]

 92%|█████████▏| 92449/100629 [1:12:37<06:51, 19.88it/s]

 92%|█████████▏| 92452/100629 [1:12:37<06:35, 20.66it/s]

 92%|█████████▏| 92455/100629 [1:12:37<06:17, 21.64it/s]

 92%|█████████▏| 92458/100629 [1:12:37<05:47, 23.48it/s]

 92%|█████████▏| 92462/100629 [1:12:37<05:17, 25.69it/s]

 92%|█████████▏| 92465/100629 [1:12:37<06:50, 19.90it/s]

 92%|█████████▏| 92468/100629 [1:12:38<08:08, 16.70it/s]

 92%|█████████▏| 92470/100629 [1:12:38<08:10, 16.64it/s]

 92%|█████████▏| 92474/100629 [1:12:38<06:55, 19.63it/s]

 92%|█████████▏| 92477/100629 [1:12:38<06:46, 20.07it/s]

 92%|█████████▏| 92480/100629 [1:12:38<06:49, 19.90it/s]

 92%|█████████▏| 92483/100629 [1:12:39<08:14, 16.47it/s]

 92%|█████████▏| 92485/100629 [1:12:39<08:04, 16.82it/s]

 92%|█████████▏| 92488/100629 [1:12:39<07:03, 19.22it/s]

 92%|█████████▏| 92491/100629 [1:12:39<06:55, 19.60it/s]

 92%|█████████▏| 92494/100629 [1:12:39<06:57, 19.47it/s]

 92%|█████████▏| 92498/100629 [1:12:39<06:29, 20.89it/s]

 92%|█████████▏| 92502/100629 [1:12:39<05:28, 24.73it/s]

 92%|█████████▏| 92505/100629 [1:12:39<05:37, 24.09it/s]

 92%|█████████▏| 92508/100629 [1:12:40<06:28, 20.92it/s]

 92%|█████████▏| 92514/100629 [1:12:40<04:42, 28.68it/s]

 92%|█████████▏| 92518/100629 [1:12:40<04:53, 27.61it/s]

 92%|█████████▏| 92521/100629 [1:12:40<04:56, 27.30it/s]

 92%|█████████▏| 92524/100629 [1:12:40<05:29, 24.57it/s]

 92%|█████████▏| 92528/100629 [1:12:40<05:28, 24.64it/s]

 92%|█████████▏| 92531/100629 [1:12:40<06:00, 22.46it/s]

 92%|█████████▏| 92534/100629 [1:12:41<06:04, 22.23it/s]

 92%|█████████▏| 92537/100629 [1:12:41<05:48, 23.19it/s]

 92%|█████████▏| 92540/100629 [1:12:41<06:37, 20.35it/s]

 92%|█████████▏| 92543/100629 [1:12:41<06:28, 20.79it/s]

 92%|█████████▏| 92546/100629 [1:12:41<06:18, 21.37it/s]

 92%|█████████▏| 92549/100629 [1:12:41<06:58, 19.32it/s]

 92%|█████████▏| 92552/100629 [1:12:42<08:40, 15.51it/s]

 92%|█████████▏| 92555/100629 [1:12:42<07:27, 18.03it/s]

 92%|█████████▏| 92558/100629 [1:12:42<06:57, 19.32it/s]

 92%|█████████▏| 92561/100629 [1:12:42<07:13, 18.63it/s]

 92%|█████████▏| 92565/100629 [1:12:42<05:53, 22.79it/s]

 92%|█████████▏| 92568/100629 [1:12:42<05:57, 22.53it/s]

 92%|█████████▏| 92571/100629 [1:12:42<05:39, 23.75it/s]

 92%|█████████▏| 92574/100629 [1:12:43<06:27, 20.78it/s]

 92%|█████████▏| 92577/100629 [1:12:43<06:41, 20.06it/s]

 92%|█████████▏| 92581/100629 [1:12:43<05:39, 23.68it/s]

 92%|█████████▏| 92584/100629 [1:12:43<06:27, 20.76it/s]

 92%|█████████▏| 92587/100629 [1:12:43<05:58, 22.41it/s]

 92%|█████████▏| 92590/100629 [1:12:43<06:13, 21.54it/s]

 92%|█████████▏| 92593/100629 [1:12:44<06:45, 19.83it/s]

 92%|█████████▏| 92596/100629 [1:12:44<06:17, 21.29it/s]

 92%|█████████▏| 92600/100629 [1:12:44<05:47, 23.09it/s]

 92%|█████████▏| 92603/100629 [1:12:44<06:03, 22.09it/s]

 92%|█████████▏| 92606/100629 [1:12:44<06:19, 21.13it/s]

 92%|█████████▏| 92609/100629 [1:12:44<06:42, 19.92it/s]

 92%|█████████▏| 92613/100629 [1:12:44<05:41, 23.48it/s]

 92%|█████████▏| 92616/100629 [1:12:45<06:12, 21.54it/s]

 92%|█████████▏| 92620/100629 [1:12:45<05:34, 23.97it/s]

 92%|█████████▏| 92623/100629 [1:12:45<06:32, 20.40it/s]

 92%|█████████▏| 92626/100629 [1:12:45<06:16, 21.26it/s]

 92%|█████████▏| 92629/100629 [1:12:45<06:17, 21.21it/s]

 92%|█████████▏| 92632/100629 [1:12:45<06:06, 21.82it/s]

 92%|█████████▏| 92635/100629 [1:12:45<06:25, 20.73it/s]

 92%|█████████▏| 92639/100629 [1:12:46<06:30, 20.48it/s]

 92%|█████████▏| 92642/100629 [1:12:46<07:41, 17.32it/s]

 92%|█████████▏| 92645/100629 [1:12:46<06:46, 19.62it/s]

 92%|█████████▏| 92648/100629 [1:12:46<07:12, 18.45it/s]

 92%|█████████▏| 92651/100629 [1:12:46<07:57, 16.70it/s]

 92%|█████████▏| 92655/100629 [1:12:47<06:40, 19.93it/s]

 92%|█████████▏| 92658/100629 [1:12:47<06:46, 19.59it/s]

 92%|█████████▏| 92661/100629 [1:12:47<07:02, 18.84it/s]

 92%|█████████▏| 92665/100629 [1:12:47<05:50, 22.73it/s]

 92%|█████████▏| 92668/100629 [1:12:47<05:57, 22.28it/s]

 92%|█████████▏| 92674/100629 [1:12:47<04:41, 28.28it/s]

 92%|█████████▏| 92678/100629 [1:12:47<04:27, 29.71it/s]

 92%|█████████▏| 92682/100629 [1:12:48<04:56, 26.81it/s]

 92%|█████████▏| 92686/100629 [1:12:48<04:53, 27.11it/s]

 92%|█████████▏| 92689/100629 [1:12:48<05:09, 25.62it/s]

 92%|█████████▏| 92693/100629 [1:12:48<04:35, 28.85it/s]

 92%|█████████▏| 92697/100629 [1:12:48<05:09, 25.67it/s]

 92%|█████████▏| 92700/100629 [1:12:48<05:54, 22.35it/s]

 92%|█████████▏| 92703/100629 [1:12:48<06:04, 21.74it/s]

 92%|█████████▏| 92706/100629 [1:12:49<06:33, 20.11it/s]

 92%|█████████▏| 92709/100629 [1:12:49<06:50, 19.32it/s]

 92%|█████████▏| 92712/100629 [1:12:49<06:14, 21.13it/s]

 92%|█████████▏| 92715/100629 [1:12:49<06:22, 20.70it/s]

 92%|█████████▏| 92719/100629 [1:12:49<05:24, 24.38it/s]

 92%|█████████▏| 92722/100629 [1:12:49<06:06, 21.57it/s]

 92%|█████████▏| 92725/100629 [1:12:50<06:35, 19.99it/s]

 92%|█████████▏| 92729/100629 [1:12:50<05:45, 22.87it/s]

 92%|█████████▏| 92732/100629 [1:12:50<05:57, 22.10it/s]

 92%|█████████▏| 92735/100629 [1:12:50<06:00, 21.88it/s]

 92%|█████████▏| 92739/100629 [1:12:50<05:12, 25.23it/s]

 92%|█████████▏| 92743/100629 [1:12:50<04:36, 28.54it/s]

 92%|█████████▏| 92747/100629 [1:12:50<04:49, 27.25it/s]

 92%|█████████▏| 92750/100629 [1:12:50<05:06, 25.72it/s]

 92%|█████████▏| 92754/100629 [1:12:51<04:40, 28.10it/s]

 92%|█████████▏| 92757/100629 [1:12:51<04:48, 27.33it/s]

 92%|█████████▏| 92760/100629 [1:12:51<04:55, 26.60it/s]

 92%|█████████▏| 92764/100629 [1:12:51<04:36, 28.43it/s]

 92%|█████████▏| 92767/100629 [1:12:51<05:01, 26.11it/s]

 92%|█████████▏| 92770/100629 [1:12:51<05:02, 26.02it/s]

 92%|█████████▏| 92773/100629 [1:12:51<06:04, 21.57it/s]

 92%|█████████▏| 92778/100629 [1:12:52<05:16, 24.78it/s]

 92%|█████████▏| 92782/100629 [1:12:52<05:41, 23.00it/s]

 92%|█████████▏| 92787/100629 [1:12:52<04:42, 27.81it/s]

 92%|█████████▏| 92790/100629 [1:12:52<05:35, 23.35it/s]

 92%|█████████▏| 92793/100629 [1:12:52<05:24, 24.17it/s]

 92%|█████████▏| 92798/100629 [1:12:52<05:01, 25.99it/s]

 92%|█████████▏| 92801/100629 [1:12:53<05:37, 23.16it/s]

 92%|█████████▏| 92804/100629 [1:12:53<06:10, 21.10it/s]

 92%|█████████▏| 92807/100629 [1:12:53<06:45, 19.28it/s]

 92%|█████████▏| 92810/100629 [1:12:53<06:29, 20.06it/s]

 92%|█████████▏| 92814/100629 [1:12:53<05:52, 22.16it/s]

 92%|█████████▏| 92817/100629 [1:12:53<05:33, 23.45it/s]

 92%|█████████▏| 92820/100629 [1:12:53<05:30, 23.61it/s]

 92%|█████████▏| 92824/100629 [1:12:54<05:06, 25.47it/s]

 92%|█████████▏| 92827/100629 [1:12:54<05:59, 21.73it/s]

 92%|█████████▏| 92831/100629 [1:12:54<05:03, 25.71it/s]

 92%|█████████▏| 92834/100629 [1:12:54<05:23, 24.10it/s]

 92%|█████████▏| 92837/100629 [1:12:54<05:42, 22.74it/s]

 92%|█████████▏| 92840/100629 [1:12:54<06:46, 19.18it/s]

 92%|█████████▏| 92843/100629 [1:12:54<06:08, 21.11it/s]

 92%|█████████▏| 92846/100629 [1:12:55<06:00, 21.60it/s]

 92%|█████████▏| 92849/100629 [1:12:55<05:38, 23.01it/s]

 92%|█████████▏| 92852/100629 [1:12:55<06:22, 20.36it/s]

 92%|█████████▏| 92855/100629 [1:12:55<07:13, 17.93it/s]

 92%|█████████▏| 92858/100629 [1:12:55<07:08, 18.14it/s]

 92%|█████████▏| 92860/100629 [1:12:55<07:29, 17.28it/s]

 92%|█████████▏| 92863/100629 [1:12:56<07:48, 16.59it/s]

 92%|█████████▏| 92865/100629 [1:12:56<08:01, 16.12it/s]

 92%|█████████▏| 92868/100629 [1:12:56<07:16, 17.80it/s]

 92%|█████████▏| 92870/100629 [1:12:56<07:21, 17.57it/s]

 92%|█████████▏| 92873/100629 [1:12:56<06:52, 18.82it/s]

 92%|█████████▏| 92876/100629 [1:12:56<06:34, 19.64it/s]

 92%|█████████▏| 92878/100629 [1:12:56<06:52, 18.81it/s]

 92%|█████████▏| 92882/100629 [1:12:57<05:58, 21.61it/s]

 92%|█████████▏| 92885/100629 [1:12:57<05:45, 22.42it/s]

 92%|█████████▏| 92888/100629 [1:12:57<05:38, 22.90it/s]

 92%|█████████▏| 92891/100629 [1:12:57<06:12, 20.77it/s]

 92%|█████████▏| 92894/100629 [1:12:57<05:51, 22.03it/s]

 92%|█████████▏| 92897/100629 [1:12:57<06:04, 21.23it/s]

 92%|█████████▏| 92900/100629 [1:12:57<06:58, 18.49it/s]

 92%|█████████▏| 92904/100629 [1:12:58<05:58, 21.55it/s]

 92%|█████████▏| 92907/100629 [1:12:58<06:26, 19.96it/s]

 92%|█████████▏| 92910/100629 [1:12:58<05:53, 21.82it/s]

 92%|█████████▏| 92913/100629 [1:12:58<05:28, 23.52it/s]

 92%|█████████▏| 92916/100629 [1:12:58<05:07, 25.09it/s]

 92%|█████████▏| 92919/100629 [1:12:58<05:04, 25.35it/s]

 92%|█████████▏| 92922/100629 [1:12:58<05:36, 22.93it/s]

 92%|█████████▏| 92925/100629 [1:12:59<07:02, 18.23it/s]

 92%|█████████▏| 92928/100629 [1:12:59<06:53, 18.63it/s]

 92%|█████████▏| 92931/100629 [1:12:59<07:16, 17.63it/s]

 92%|█████████▏| 92934/100629 [1:12:59<06:25, 19.95it/s]

 92%|█████████▏| 92937/100629 [1:12:59<06:01, 21.26it/s]

 92%|█████████▏| 92940/100629 [1:12:59<06:32, 19.59it/s]

 92%|█████████▏| 92943/100629 [1:12:59<06:23, 20.03it/s]

 92%|█████████▏| 92946/100629 [1:13:00<06:50, 18.73it/s]

 92%|█████████▏| 92951/100629 [1:13:00<05:51, 21.86it/s]

 92%|█████████▏| 92954/100629 [1:13:00<05:54, 21.62it/s]

 92%|█████████▏| 92957/100629 [1:13:00<06:20, 20.18it/s]

 92%|█████████▏| 92960/100629 [1:13:00<06:50, 18.68it/s]

 92%|█████████▏| 92963/100629 [1:13:00<06:10, 20.67it/s]

 92%|█████████▏| 92966/100629 [1:13:01<05:37, 22.68it/s]

 92%|█████████▏| 92969/100629 [1:13:01<05:58, 21.34it/s]

 92%|█████████▏| 92972/100629 [1:13:01<07:16, 17.55it/s]

 92%|█████████▏| 92975/100629 [1:13:01<06:24, 19.91it/s]

 92%|█████████▏| 92979/100629 [1:13:01<05:50, 21.85it/s]

 92%|█████████▏| 92983/100629 [1:13:01<05:10, 24.65it/s]

 92%|█████████▏| 92986/100629 [1:13:01<05:10, 24.65it/s]

 92%|█████████▏| 92989/100629 [1:13:02<05:21, 23.74it/s]

 92%|█████████▏| 92992/100629 [1:13:02<05:17, 24.02it/s]

 92%|█████████▏| 92995/100629 [1:13:02<05:09, 24.66it/s]

 92%|█████████▏| 92998/100629 [1:13:02<05:45, 22.06it/s]

 92%|█████████▏| 93001/100629 [1:13:02<06:31, 19.48it/s]

 92%|█████████▏| 93004/100629 [1:13:02<06:39, 19.10it/s]

 92%|█████████▏| 93006/100629 [1:13:03<07:19, 17.33it/s]

 92%|█████████▏| 93010/100629 [1:13:03<05:57, 21.31it/s]

 92%|█████████▏| 93013/100629 [1:13:03<06:37, 19.15it/s]

 92%|█████████▏| 93018/100629 [1:13:03<05:52, 21.61it/s]

 92%|█████████▏| 93021/100629 [1:13:03<05:46, 21.98it/s]

 92%|█████████▏| 93024/100629 [1:13:03<05:47, 21.89it/s]

 92%|█████████▏| 93028/100629 [1:13:03<05:10, 24.47it/s]

 92%|█████████▏| 93031/100629 [1:13:04<07:21, 17.20it/s]

 92%|█████████▏| 93034/100629 [1:13:04<06:58, 18.14it/s]

 92%|█████████▏| 93037/100629 [1:13:04<07:22, 17.17it/s]

 92%|█████████▏| 93041/100629 [1:13:04<06:15, 20.21it/s]

 92%|█████████▏| 93044/100629 [1:13:04<06:08, 20.58it/s]

 92%|█████████▏| 93047/100629 [1:13:04<05:38, 22.39it/s]

 92%|█████████▏| 93050/100629 [1:13:05<05:22, 23.53it/s]

 92%|█████████▏| 93053/100629 [1:13:05<05:58, 21.15it/s]

 92%|█████████▏| 93056/100629 [1:13:05<06:08, 20.55it/s]

 92%|█████████▏| 93059/100629 [1:13:05<06:57, 18.14it/s]

 92%|█████████▏| 93061/100629 [1:13:05<07:05, 17.80it/s]

 92%|█████████▏| 93064/100629 [1:13:05<06:18, 19.98it/s]

 92%|█████████▏| 93068/100629 [1:13:05<05:29, 22.92it/s]

 92%|█████████▏| 93071/100629 [1:13:06<06:22, 19.75it/s]

 92%|█████████▏| 93075/100629 [1:13:06<05:20, 23.60it/s]

 92%|█████████▏| 93078/100629 [1:13:06<06:12, 20.26it/s]

 92%|█████████▏| 93081/100629 [1:13:06<06:04, 20.70it/s]

 93%|█████████▎| 93085/100629 [1:13:06<05:07, 24.54it/s]

 93%|█████████▎| 93089/100629 [1:13:06<05:50, 21.51it/s]

 93%|█████████▎| 93092/100629 [1:13:07<05:28, 22.92it/s]

 93%|█████████▎| 93096/100629 [1:13:07<04:48, 26.16it/s]

 93%|█████████▎| 93099/100629 [1:13:07<05:00, 25.06it/s]

 93%|█████████▎| 93102/100629 [1:13:07<05:38, 22.25it/s]

 93%|█████████▎| 93105/100629 [1:13:07<06:28, 19.38it/s]

 93%|█████████▎| 93108/100629 [1:13:07<06:24, 19.55it/s]

 93%|█████████▎| 93111/100629 [1:13:07<06:16, 19.99it/s]

 93%|█████████▎| 93114/100629 [1:13:08<06:07, 20.45it/s]

 93%|█████████▎| 93117/100629 [1:13:08<05:43, 21.88it/s]

 93%|█████████▎| 93120/100629 [1:13:08<05:31, 22.64it/s]

 93%|█████████▎| 93123/100629 [1:13:08<05:12, 24.00it/s]

 93%|█████████▎| 93127/100629 [1:13:08<05:01, 24.86it/s]

 93%|█████████▎| 93130/100629 [1:13:08<06:17, 19.89it/s]

 93%|█████████▎| 93133/100629 [1:13:09<06:52, 18.18it/s]

 93%|█████████▎| 93135/100629 [1:13:09<07:04, 17.66it/s]

 93%|█████████▎| 93139/100629 [1:13:09<05:47, 21.53it/s]

 93%|█████████▎| 93145/100629 [1:13:09<04:51, 25.71it/s]

 93%|█████████▎| 93148/100629 [1:13:09<05:50, 21.37it/s]

 93%|█████████▎| 93151/100629 [1:13:09<06:09, 20.26it/s]

 93%|█████████▎| 93154/100629 [1:13:09<05:56, 20.96it/s]

 93%|█████████▎| 93157/100629 [1:13:10<05:46, 21.59it/s]

 93%|█████████▎| 93160/100629 [1:13:10<06:03, 20.56it/s]

 93%|█████████▎| 93163/100629 [1:13:10<05:31, 22.55it/s]

 93%|█████████▎| 93166/100629 [1:13:10<05:31, 22.49it/s]

 93%|█████████▎| 93169/100629 [1:13:10<05:46, 21.54it/s]

 93%|█████████▎| 93172/100629 [1:13:10<05:22, 23.12it/s]

 93%|█████████▎| 93175/100629 [1:13:10<05:12, 23.82it/s]

 93%|█████████▎| 93181/100629 [1:13:11<04:38, 26.77it/s]

 93%|█████████▎| 93185/100629 [1:13:11<04:21, 28.51it/s]

 93%|█████████▎| 93190/100629 [1:13:11<04:08, 29.88it/s]

 93%|█████████▎| 93193/100629 [1:13:11<04:10, 29.66it/s]

 93%|█████████▎| 93197/100629 [1:13:11<04:07, 30.06it/s]

 93%|█████████▎| 93201/100629 [1:13:11<04:11, 29.59it/s]

 93%|█████████▎| 93204/100629 [1:13:11<04:24, 28.12it/s]

 93%|█████████▎| 93208/100629 [1:13:12<04:39, 26.54it/s]

 93%|█████████▎| 93211/100629 [1:13:12<05:23, 22.96it/s]

 93%|█████████▎| 93214/100629 [1:13:12<05:11, 23.78it/s]

 93%|█████████▎| 93217/100629 [1:13:12<05:30, 22.45it/s]

 93%|█████████▎| 93220/100629 [1:13:12<06:03, 20.37it/s]

 93%|█████████▎| 93223/100629 [1:13:12<05:56, 20.79it/s]

 93%|█████████▎| 93226/100629 [1:13:12<05:53, 20.92it/s]

 93%|█████████▎| 93230/100629 [1:13:13<05:16, 23.41it/s]

 93%|█████████▎| 93233/100629 [1:13:13<04:59, 24.70it/s]

 93%|█████████▎| 93236/100629 [1:13:13<04:44, 25.96it/s]

 93%|█████████▎| 93239/100629 [1:13:13<05:49, 21.14it/s]

 93%|█████████▎| 93244/100629 [1:13:13<04:53, 25.14it/s]

 93%|█████████▎| 93247/100629 [1:13:13<05:48, 21.20it/s]

 93%|█████████▎| 93250/100629 [1:13:13<06:05, 20.20it/s]

 93%|█████████▎| 93253/100629 [1:13:14<05:59, 20.52it/s]

 93%|█████████▎| 93256/100629 [1:13:14<05:37, 21.83it/s]

 93%|█████████▎| 93259/100629 [1:13:14<06:28, 18.95it/s]

 93%|█████████▎| 93263/100629 [1:13:14<05:59, 20.51it/s]

 93%|█████████▎| 93266/100629 [1:13:14<05:32, 22.13it/s]

 93%|█████████▎| 93269/100629 [1:13:14<05:22, 22.84it/s]

 93%|█████████▎| 93272/100629 [1:13:15<07:20, 16.69it/s]

 93%|█████████▎| 93275/100629 [1:13:15<06:26, 19.01it/s]

 93%|█████████▎| 93278/100629 [1:13:15<05:49, 21.05it/s]

 93%|█████████▎| 93281/100629 [1:13:15<06:32, 18.71it/s]

 93%|█████████▎| 93285/100629 [1:13:15<05:32, 22.07it/s]

 93%|█████████▎| 93288/100629 [1:13:15<05:13, 23.41it/s]

 93%|█████████▎| 93291/100629 [1:13:15<05:22, 22.72it/s]

 93%|█████████▎| 93294/100629 [1:13:16<05:46, 21.16it/s]

 93%|█████████▎| 93297/100629 [1:13:16<05:34, 21.95it/s]

 93%|█████████▎| 93301/100629 [1:13:16<05:02, 24.23it/s]

 93%|█████████▎| 93304/100629 [1:13:16<05:04, 24.07it/s]

 93%|█████████▎| 93307/100629 [1:13:16<05:10, 23.57it/s]

 93%|█████████▎| 93310/100629 [1:13:16<05:35, 21.80it/s]

 93%|█████████▎| 93313/100629 [1:13:16<05:41, 21.41it/s]

 93%|█████████▎| 93318/100629 [1:13:17<04:40, 26.08it/s]

 93%|█████████▎| 93322/100629 [1:13:17<05:00, 24.31it/s]

 93%|█████████▎| 93325/100629 [1:13:17<05:12, 23.39it/s]

 93%|█████████▎| 93328/100629 [1:13:17<05:12, 23.37it/s]

 93%|█████████▎| 93331/100629 [1:13:17<06:18, 19.28it/s]

 93%|█████████▎| 93334/100629 [1:13:17<05:55, 20.50it/s]

 93%|█████████▎| 93337/100629 [1:13:18<06:15, 19.41it/s]

 93%|█████████▎| 93341/100629 [1:13:18<05:15, 23.10it/s]

 93%|█████████▎| 93346/100629 [1:13:18<04:28, 27.17it/s]

 93%|█████████▎| 93349/100629 [1:13:18<04:31, 26.82it/s]

 93%|█████████▎| 93354/100629 [1:13:18<04:23, 27.58it/s]

 93%|█████████▎| 93357/100629 [1:13:18<05:03, 23.96it/s]

 93%|█████████▎| 93361/100629 [1:13:18<04:43, 25.60it/s]

 93%|█████████▎| 93364/100629 [1:13:19<05:10, 23.36it/s]

 93%|█████████▎| 93367/100629 [1:13:19<04:52, 24.81it/s]

 93%|█████████▎| 93370/100629 [1:13:19<04:56, 24.48it/s]

 93%|█████████▎| 93373/100629 [1:13:19<05:38, 21.45it/s]

 93%|█████████▎| 93376/100629 [1:13:19<05:44, 21.05it/s]

 93%|█████████▎| 93381/100629 [1:13:19<05:08, 23.48it/s]

 93%|█████████▎| 93385/100629 [1:13:19<04:46, 25.28it/s]

 93%|█████████▎| 93388/100629 [1:13:20<05:11, 23.28it/s]

 93%|█████████▎| 93391/100629 [1:13:20<05:04, 23.79it/s]

 93%|█████████▎| 93394/100629 [1:13:20<06:09, 19.57it/s]

 93%|█████████▎| 93398/100629 [1:13:20<05:11, 23.22it/s]

 93%|█████████▎| 93401/100629 [1:13:20<05:13, 23.07it/s]

 93%|█████████▎| 93405/100629 [1:13:20<04:31, 26.59it/s]

 93%|█████████▎| 93409/100629 [1:13:20<04:16, 28.15it/s]

 93%|█████████▎| 93412/100629 [1:13:20<04:20, 27.66it/s]

 93%|█████████▎| 93415/100629 [1:13:21<04:22, 27.45it/s]

 93%|█████████▎| 93418/100629 [1:13:21<04:29, 26.78it/s]

 93%|█████████▎| 93421/100629 [1:13:21<04:54, 24.45it/s]

 93%|█████████▎| 93424/100629 [1:13:21<04:49, 24.92it/s]

 93%|█████████▎| 93428/100629 [1:13:21<04:10, 28.75it/s]

 93%|█████████▎| 93431/100629 [1:13:21<04:28, 26.79it/s]

 93%|█████████▎| 93434/100629 [1:13:21<04:47, 25.00it/s]

 93%|█████████▎| 93437/100629 [1:13:22<05:14, 22.87it/s]

 93%|█████████▎| 93440/100629 [1:13:22<05:18, 22.57it/s]

 93%|█████████▎| 93443/100629 [1:13:22<05:13, 22.89it/s]

 93%|█████████▎| 93446/100629 [1:13:22<05:18, 22.53it/s]

 93%|█████████▎| 93452/100629 [1:13:22<03:54, 30.55it/s]

 93%|█████████▎| 93456/100629 [1:13:22<04:04, 29.32it/s]

 93%|█████████▎| 93460/100629 [1:13:22<04:44, 25.23it/s]

 93%|█████████▎| 93463/100629 [1:13:23<05:12, 22.92it/s]

 93%|█████████▎| 93466/100629 [1:13:23<05:01, 23.78it/s]

 93%|█████████▎| 93469/100629 [1:13:23<05:15, 22.69it/s]

 93%|█████████▎| 93472/100629 [1:13:23<04:57, 24.07it/s]

 93%|█████████▎| 93477/100629 [1:13:23<04:11, 28.45it/s]

 93%|█████████▎| 93480/100629 [1:13:23<04:47, 24.83it/s]

 93%|█████████▎| 93483/100629 [1:13:23<05:25, 21.94it/s]

 93%|█████████▎| 93486/100629 [1:13:24<05:02, 23.59it/s]

 93%|█████████▎| 93489/100629 [1:13:24<05:26, 21.89it/s]

 93%|█████████▎| 93492/100629 [1:13:24<05:47, 20.54it/s]

 93%|█████████▎| 93496/100629 [1:13:24<05:14, 22.66it/s]

 93%|█████████▎| 93499/100629 [1:13:24<05:16, 22.52it/s]

 93%|█████████▎| 93502/100629 [1:13:24<05:55, 20.05it/s]

 93%|█████████▎| 93506/100629 [1:13:24<05:21, 22.17it/s]

 93%|█████████▎| 93510/100629 [1:13:25<04:51, 24.41it/s]

 93%|█████████▎| 93513/100629 [1:13:25<05:02, 23.54it/s]

 93%|█████████▎| 93516/100629 [1:13:25<05:08, 23.04it/s]

 93%|█████████▎| 93519/100629 [1:13:25<05:52, 20.18it/s]

 93%|█████████▎| 93523/100629 [1:13:25<05:30, 21.48it/s]

 93%|█████████▎| 93527/100629 [1:13:25<05:03, 23.37it/s]

 93%|█████████▎| 93531/100629 [1:13:25<04:40, 25.30it/s]

 93%|█████████▎| 93534/100629 [1:13:26<04:53, 24.16it/s]

 93%|█████████▎| 93537/100629 [1:13:26<05:12, 22.69it/s]

 93%|█████████▎| 93540/100629 [1:13:26<05:21, 22.07it/s]

 93%|█████████▎| 93543/100629 [1:13:26<05:16, 22.41it/s]

 93%|█████████▎| 93546/100629 [1:13:26<05:03, 23.35it/s]

 93%|█████████▎| 93549/100629 [1:13:26<04:48, 24.53it/s]

 93%|█████████▎| 93552/100629 [1:13:26<05:13, 22.56it/s]

 93%|█████████▎| 93555/100629 [1:13:27<04:57, 23.80it/s]

 93%|█████████▎| 93558/100629 [1:13:27<05:01, 23.49it/s]

 93%|█████████▎| 93561/100629 [1:13:27<04:46, 24.67it/s]

 93%|█████████▎| 93564/100629 [1:13:27<05:01, 23.45it/s]

 93%|█████████▎| 93567/100629 [1:13:27<05:35, 21.08it/s]

 93%|█████████▎| 93570/100629 [1:13:27<05:43, 20.55it/s]

 93%|█████████▎| 93575/100629 [1:13:27<04:27, 26.41it/s]

 93%|█████████▎| 93578/100629 [1:13:28<05:17, 22.19it/s]

 93%|█████████▎| 93581/100629 [1:13:28<05:07, 22.89it/s]

 93%|█████████▎| 93584/100629 [1:13:28<04:51, 24.18it/s]

 93%|█████████▎| 93587/100629 [1:13:28<05:12, 22.56it/s]

 93%|█████████▎| 93591/100629 [1:13:28<04:24, 26.57it/s]

 93%|█████████▎| 93594/100629 [1:13:28<04:31, 25.95it/s]

 93%|█████████▎| 93597/100629 [1:13:28<05:02, 23.27it/s]

 93%|█████████▎| 93601/100629 [1:13:28<04:43, 24.78it/s]

 93%|█████████▎| 93604/100629 [1:13:29<06:10, 18.95it/s]

 93%|█████████▎| 93607/100629 [1:13:29<05:48, 20.15it/s]

 93%|█████████▎| 93612/100629 [1:13:29<04:48, 24.32it/s]

 93%|█████████▎| 93615/100629 [1:13:29<05:43, 20.39it/s]

 93%|█████████▎| 93619/100629 [1:13:29<04:53, 23.88it/s]

 93%|█████████▎| 93622/100629 [1:13:29<04:39, 25.07it/s]

 93%|█████████▎| 93625/100629 [1:13:30<05:28, 21.30it/s]

 93%|█████████▎| 93628/100629 [1:13:30<05:07, 22.79it/s]

 93%|█████████▎| 93631/100629 [1:13:30<05:00, 23.31it/s]

 93%|█████████▎| 93634/100629 [1:13:30<05:35, 20.84it/s]

 93%|█████████▎| 93637/100629 [1:13:30<07:48, 14.93it/s]

 93%|█████████▎| 93639/100629 [1:13:31<08:35, 13.57it/s]

 93%|█████████▎| 93642/100629 [1:13:31<07:19, 15.91it/s]

 93%|█████████▎| 93646/100629 [1:13:31<05:53, 19.76it/s]

 93%|█████████▎| 93649/100629 [1:13:31<05:39, 20.53it/s]

 93%|█████████▎| 93653/100629 [1:13:31<04:54, 23.67it/s]

 93%|█████████▎| 93656/100629 [1:13:31<05:21, 21.67it/s]

 93%|█████████▎| 93660/100629 [1:13:31<04:51, 23.92it/s]

 93%|█████████▎| 93663/100629 [1:13:31<04:38, 25.00it/s]

 93%|█████████▎| 93667/100629 [1:13:32<04:15, 27.20it/s]

 93%|█████████▎| 93672/100629 [1:13:32<03:55, 29.58it/s]

 93%|█████████▎| 93676/100629 [1:13:32<04:38, 24.97it/s]

 93%|█████████▎| 93679/100629 [1:13:32<04:54, 23.62it/s]

 93%|█████████▎| 93683/100629 [1:13:32<04:18, 26.91it/s]

 93%|█████████▎| 93688/100629 [1:13:32<03:58, 29.05it/s]

 93%|█████████▎| 93692/100629 [1:13:33<04:26, 26.01it/s]

 93%|█████████▎| 93695/100629 [1:13:33<04:30, 25.59it/s]

 93%|█████████▎| 93698/100629 [1:13:33<05:10, 22.32it/s]

 93%|█████████▎| 93701/100629 [1:13:33<06:01, 19.14it/s]

 93%|█████████▎| 93704/100629 [1:13:33<06:01, 19.18it/s]

 93%|█████████▎| 93707/100629 [1:13:33<06:13, 18.55it/s]

 93%|█████████▎| 93710/100629 [1:13:34<05:45, 20.01it/s]

 93%|█████████▎| 93713/100629 [1:13:34<05:39, 20.39it/s]

 93%|█████████▎| 93716/100629 [1:13:34<06:05, 18.90it/s]

 93%|█████████▎| 93718/100629 [1:13:34<07:08, 16.14it/s]

 93%|█████████▎| 93721/100629 [1:13:34<06:23, 18.01it/s]

 93%|█████████▎| 93725/100629 [1:13:34<05:09, 22.29it/s]

 93%|█████████▎| 93728/100629 [1:13:34<05:37, 20.47it/s]

 93%|█████████▎| 93732/100629 [1:13:35<05:05, 22.54it/s]

 93%|█████████▎| 93735/100629 [1:13:35<05:25, 21.18it/s]

 93%|█████████▎| 93738/100629 [1:13:35<05:44, 20.02it/s]

 93%|█████████▎| 93741/100629 [1:13:35<05:34, 20.56it/s]

 93%|█████████▎| 93744/100629 [1:13:35<05:46, 19.87it/s]

 93%|█████████▎| 93747/100629 [1:13:35<05:57, 19.23it/s]

 93%|█████████▎| 93750/100629 [1:13:36<05:24, 21.21it/s]

 93%|█████████▎| 93753/100629 [1:13:36<05:15, 21.80it/s]

 93%|█████████▎| 93756/100629 [1:13:36<05:18, 21.61it/s]

 93%|█████████▎| 93759/100629 [1:13:36<06:07, 18.68it/s]

 93%|█████████▎| 93761/100629 [1:13:36<06:03, 18.88it/s]

 93%|█████████▎| 93764/100629 [1:13:36<05:31, 20.74it/s]

 93%|█████████▎| 93767/100629 [1:13:36<05:56, 19.26it/s]

 93%|█████████▎| 93770/100629 [1:13:37<05:41, 20.11it/s]

 93%|█████████▎| 93773/100629 [1:13:37<06:05, 18.77it/s]

 93%|█████████▎| 93776/100629 [1:13:37<05:27, 20.92it/s]

 93%|█████████▎| 93779/100629 [1:13:37<05:17, 21.60it/s]

 93%|█████████▎| 93782/100629 [1:13:37<05:04, 22.47it/s]

 93%|█████████▎| 93786/100629 [1:13:37<04:31, 25.18it/s]

 93%|█████████▎| 93790/100629 [1:13:37<04:29, 25.40it/s]

 93%|█████████▎| 93793/100629 [1:13:37<04:29, 25.35it/s]

 93%|█████████▎| 93796/100629 [1:13:38<04:51, 23.41it/s]

 93%|█████████▎| 93800/100629 [1:13:38<04:34, 24.86it/s]

 93%|█████████▎| 93804/100629 [1:13:38<04:39, 24.40it/s]

 93%|█████████▎| 93807/100629 [1:13:38<04:56, 23.00it/s]

 93%|█████████▎| 93811/100629 [1:13:38<04:17, 26.49it/s]

 93%|█████████▎| 93816/100629 [1:13:38<03:53, 29.15it/s]

 93%|█████████▎| 93820/100629 [1:13:38<03:52, 29.27it/s]

 93%|█████████▎| 93824/100629 [1:13:39<03:55, 28.92it/s]

 93%|█████████▎| 93827/100629 [1:13:39<04:19, 26.24it/s]

 93%|█████████▎| 93832/100629 [1:13:39<03:45, 30.12it/s]

 93%|█████████▎| 93836/100629 [1:13:39<04:33, 24.82it/s]

 93%|█████████▎| 93839/100629 [1:13:39<04:30, 25.11it/s]

 93%|█████████▎| 93842/100629 [1:13:39<04:35, 24.59it/s]

 93%|█████████▎| 93845/100629 [1:13:39<04:41, 24.08it/s]

 93%|█████████▎| 93849/100629 [1:13:40<04:13, 26.80it/s]

 93%|█████████▎| 93853/100629 [1:13:40<04:07, 27.39it/s]

 93%|█████████▎| 93856/100629 [1:13:40<05:09, 21.88it/s]

 93%|█████████▎| 93859/100629 [1:13:40<05:22, 20.97it/s]

 93%|█████████▎| 93862/100629 [1:13:40<05:06, 22.07it/s]

 93%|█████████▎| 93866/100629 [1:13:40<04:44, 23.78it/s]

 93%|█████████▎| 93869/100629 [1:13:41<05:12, 21.63it/s]

 93%|█████████▎| 93872/100629 [1:13:41<05:50, 19.30it/s]

 93%|█████████▎| 93875/100629 [1:13:41<05:49, 19.30it/s]

 93%|█████████▎| 93877/100629 [1:13:41<06:00, 18.75it/s]

 93%|█████████▎| 93880/100629 [1:13:41<05:46, 19.48it/s]

 93%|█████████▎| 93884/100629 [1:13:41<04:54, 22.91it/s]

 93%|█████████▎| 93887/100629 [1:13:42<06:49, 16.48it/s]

 93%|█████████▎| 93889/100629 [1:13:42<07:11, 15.60it/s]

 93%|█████████▎| 93893/100629 [1:13:42<05:40, 19.80it/s]

 93%|█████████▎| 93896/100629 [1:13:42<05:38, 19.87it/s]

 93%|█████████▎| 93899/100629 [1:13:42<05:19, 21.08it/s]

 93%|█████████▎| 93903/100629 [1:13:42<04:45, 23.53it/s]

 93%|█████████▎| 93906/100629 [1:13:42<04:37, 24.22it/s]

 93%|█████████▎| 93909/100629 [1:13:43<04:52, 23.00it/s]

 93%|█████████▎| 93912/100629 [1:13:43<06:11, 18.10it/s]

 93%|█████████▎| 93915/100629 [1:13:43<07:27, 15.01it/s]

 93%|█████████▎| 93917/100629 [1:13:43<07:14, 15.45it/s]

 93%|█████████▎| 93921/100629 [1:13:43<05:44, 19.48it/s]

 93%|█████████▎| 93925/100629 [1:13:43<05:10, 21.59it/s]

 93%|█████████▎| 93929/100629 [1:13:44<04:45, 23.50it/s]

 93%|█████████▎| 93932/100629 [1:13:44<04:44, 23.57it/s]

 93%|█████████▎| 93935/100629 [1:13:44<06:16, 17.78it/s]

 93%|█████████▎| 93938/100629 [1:13:44<06:38, 16.79it/s]

 93%|█████████▎| 93942/100629 [1:13:44<05:22, 20.71it/s]

 93%|█████████▎| 93946/100629 [1:13:44<04:46, 23.29it/s]

 93%|█████████▎| 93949/100629 [1:13:45<04:46, 23.30it/s]

 93%|█████████▎| 93952/100629 [1:13:45<04:41, 23.74it/s]

 93%|█████████▎| 93955/100629 [1:13:45<04:40, 23.77it/s]

 93%|█████████▎| 93958/100629 [1:13:45<05:20, 20.81it/s]

 93%|█████████▎| 93961/100629 [1:13:45<04:55, 22.59it/s]

 93%|█████████▎| 93964/100629 [1:13:45<05:14, 21.21it/s]

 93%|█████████▎| 93967/100629 [1:13:45<05:40, 19.55it/s]

 93%|█████████▎| 93970/100629 [1:13:46<06:20, 17.50it/s]

 93%|█████████▎| 93973/100629 [1:13:46<05:34, 19.87it/s]

 93%|█████████▎| 93976/100629 [1:13:46<05:44, 19.31it/s]

 93%|█████████▎| 93979/100629 [1:13:46<06:05, 18.20it/s]

 93%|█████████▎| 93981/100629 [1:13:46<06:11, 17.91it/s]

 93%|█████████▎| 93985/100629 [1:13:46<04:54, 22.56it/s]

 93%|█████████▎| 93989/100629 [1:13:46<04:31, 24.43it/s]

 93%|█████████▎| 93992/100629 [1:13:47<04:40, 23.67it/s]

 93%|█████████▎| 93995/100629 [1:13:47<05:06, 21.62it/s]

 93%|█████████▎| 93999/100629 [1:13:47<04:39, 23.70it/s]

 93%|█████████▎| 94002/100629 [1:13:47<05:37, 19.64it/s]

 93%|█████████▎| 94005/100629 [1:13:47<05:25, 20.37it/s]

 93%|█████████▎| 94008/100629 [1:13:47<05:57, 18.51it/s]

 93%|█████████▎| 94011/100629 [1:13:48<06:10, 17.84it/s]

 93%|█████████▎| 94014/100629 [1:13:48<05:45, 19.16it/s]

 93%|█████████▎| 94017/100629 [1:13:48<05:48, 18.96it/s]

 93%|█████████▎| 94019/100629 [1:13:48<05:57, 18.48it/s]

 93%|█████████▎| 94021/100629 [1:13:48<05:54, 18.62it/s]

 93%|█████████▎| 94025/100629 [1:13:48<04:54, 22.46it/s]

 93%|█████████▎| 94028/100629 [1:13:48<05:01, 21.87it/s]

 93%|█████████▎| 94032/100629 [1:13:49<04:37, 23.74it/s]

 93%|█████████▎| 94035/100629 [1:13:49<04:36, 23.86it/s]

 93%|█████████▎| 94038/100629 [1:13:49<04:59, 21.99it/s]

 93%|█████████▎| 94041/100629 [1:13:49<05:36, 19.58it/s]

 93%|█████████▎| 94044/100629 [1:13:49<05:11, 21.16it/s]

 93%|█████████▎| 94047/100629 [1:13:49<05:36, 19.54it/s]

 93%|█████████▎| 94050/100629 [1:13:50<05:45, 19.05it/s]

 93%|█████████▎| 94052/100629 [1:13:50<05:43, 19.13it/s]

 93%|█████████▎| 94055/100629 [1:13:50<05:27, 20.09it/s]

 93%|█████████▎| 94058/100629 [1:13:50<04:56, 22.14it/s]

 93%|█████████▎| 94063/100629 [1:13:50<03:57, 27.67it/s]

 93%|█████████▎| 94066/100629 [1:13:50<04:22, 25.03it/s]

 93%|█████████▎| 94069/100629 [1:13:50<04:22, 24.98it/s]

 93%|█████████▎| 94072/100629 [1:13:50<04:28, 24.43it/s]

 93%|█████████▎| 94075/100629 [1:13:51<04:32, 24.05it/s]

 93%|█████████▎| 94078/100629 [1:13:51<06:02, 18.07it/s]

 93%|█████████▎| 94081/100629 [1:13:51<05:54, 18.47it/s]

 93%|█████████▎| 94084/100629 [1:13:51<05:41, 19.15it/s]

 93%|█████████▎| 94087/100629 [1:13:51<05:20, 20.41it/s]

 94%|█████████▎| 94091/100629 [1:13:51<04:44, 23.00it/s]

 94%|█████████▎| 94094/100629 [1:13:52<05:36, 19.40it/s]

 94%|█████████▎| 94098/100629 [1:13:52<05:04, 21.44it/s]

 94%|█████████▎| 94101/100629 [1:13:52<04:49, 22.55it/s]

 94%|█████████▎| 94104/100629 [1:13:52<05:10, 21.04it/s]

 94%|█████████▎| 94109/100629 [1:13:52<04:40, 23.21it/s]

 94%|█████████▎| 94112/100629 [1:13:52<05:20, 20.33it/s]

 94%|█████████▎| 94115/100629 [1:13:53<05:45, 18.83it/s]

 94%|█████████▎| 94117/100629 [1:13:53<05:44, 18.90it/s]

 94%|█████████▎| 94120/100629 [1:13:53<05:41, 19.08it/s]

 94%|█████████▎| 94123/100629 [1:13:53<05:08, 21.06it/s]

 94%|█████████▎| 94126/100629 [1:13:53<04:45, 22.76it/s]

 94%|█████████▎| 94129/100629 [1:13:53<04:25, 24.47it/s]

 94%|█████████▎| 94132/100629 [1:13:53<04:48, 22.53it/s]

 94%|█████████▎| 94136/100629 [1:13:53<04:50, 22.32it/s]

 94%|█████████▎| 94140/100629 [1:13:54<04:27, 24.29it/s]

 94%|█████████▎| 94144/100629 [1:13:54<04:06, 26.36it/s]

 94%|█████████▎| 94147/100629 [1:13:54<04:30, 24.00it/s]

 94%|█████████▎| 94150/100629 [1:13:54<04:25, 24.42it/s]

 94%|█████████▎| 94153/100629 [1:13:54<04:47, 22.53it/s]

 94%|█████████▎| 94156/100629 [1:13:54<05:18, 20.30it/s]

 94%|█████████▎| 94159/100629 [1:13:54<05:09, 20.88it/s]

 94%|█████████▎| 94162/100629 [1:13:55<05:48, 18.58it/s]

 94%|█████████▎| 94164/100629 [1:13:55<05:51, 18.37it/s]

 94%|█████████▎| 94167/100629 [1:13:55<06:32, 16.48it/s]

 94%|█████████▎| 94172/100629 [1:13:55<04:51, 22.12it/s]

 94%|█████████▎| 94175/100629 [1:13:55<04:53, 21.96it/s]

 94%|█████████▎| 94179/100629 [1:13:55<04:41, 22.90it/s]

 94%|█████████▎| 94184/100629 [1:13:56<04:15, 25.22it/s]

 94%|█████████▎| 94187/100629 [1:13:56<04:06, 26.15it/s]

 94%|█████████▎| 94190/100629 [1:13:56<04:06, 26.14it/s]

 94%|█████████▎| 94194/100629 [1:13:56<04:10, 25.64it/s]

 94%|█████████▎| 94197/100629 [1:13:56<04:43, 22.66it/s]

 94%|█████████▎| 94202/100629 [1:13:56<03:58, 26.95it/s]

 94%|█████████▎| 94205/100629 [1:13:57<04:59, 21.45it/s]

 94%|█████████▎| 94208/100629 [1:13:57<04:40, 22.88it/s]

 94%|█████████▎| 94211/100629 [1:13:57<04:34, 23.38it/s]

 94%|█████████▎| 94214/100629 [1:13:57<04:53, 21.85it/s]

 94%|█████████▎| 94217/100629 [1:13:57<06:14, 17.11it/s]

 94%|█████████▎| 94219/100629 [1:13:57<06:48, 15.70it/s]

 94%|█████████▎| 94221/100629 [1:13:58<06:56, 15.37it/s]

 94%|█████████▎| 94224/100629 [1:13:58<06:44, 15.85it/s]

 94%|█████████▎| 94227/100629 [1:13:58<06:08, 17.37it/s]

 94%|█████████▎| 94232/100629 [1:13:58<04:37, 23.08it/s]

 94%|█████████▎| 94235/100629 [1:13:58<04:27, 23.92it/s]

 94%|█████████▎| 94238/100629 [1:13:58<05:05, 20.95it/s]

 94%|█████████▎| 94242/100629 [1:13:58<04:45, 22.34it/s]

 94%|█████████▎| 94245/100629 [1:13:59<04:43, 22.51it/s]

 94%|█████████▎| 94248/100629 [1:13:59<04:26, 23.95it/s]

 94%|█████████▎| 94251/100629 [1:13:59<04:44, 22.43it/s]

 94%|█████████▎| 94254/100629 [1:13:59<04:58, 21.39it/s]

 94%|█████████▎| 94257/100629 [1:13:59<06:05, 17.42it/s]

 94%|█████████▎| 94259/100629 [1:13:59<06:40, 15.91it/s]

 94%|█████████▎| 94261/100629 [1:13:59<06:50, 15.51it/s]

 94%|█████████▎| 94263/100629 [1:14:00<06:31, 16.26it/s]

 94%|█████████▎| 94265/100629 [1:14:00<06:22, 16.65it/s]

 94%|█████████▎| 94267/100629 [1:14:00<06:22, 16.64it/s]

 94%|█████████▎| 94270/100629 [1:14:00<05:37, 18.85it/s]

 94%|█████████▎| 94272/100629 [1:14:00<05:49, 18.21it/s]

 94%|█████████▎| 94275/100629 [1:14:00<05:07, 20.64it/s]

 94%|█████████▎| 94278/100629 [1:14:00<05:12, 20.31it/s]

 94%|█████████▎| 94281/100629 [1:14:01<05:37, 18.82it/s]

 94%|█████████▎| 94284/100629 [1:14:01<04:58, 21.28it/s]

 94%|█████████▎| 94287/100629 [1:14:01<04:51, 21.79it/s]

 94%|█████████▎| 94290/100629 [1:14:01<04:56, 21.38it/s]

 94%|█████████▎| 94294/100629 [1:14:01<04:17, 24.60it/s]

 94%|█████████▎| 94297/100629 [1:14:01<04:16, 24.71it/s]

 94%|█████████▎| 94300/100629 [1:14:01<04:25, 23.81it/s]

 94%|█████████▎| 94304/100629 [1:14:01<04:23, 23.97it/s]

 94%|█████████▎| 94307/100629 [1:14:02<04:23, 24.04it/s]

 94%|█████████▎| 94310/100629 [1:14:02<05:08, 20.49it/s]

 94%|█████████▎| 94313/100629 [1:14:02<04:58, 21.13it/s]

 94%|█████████▎| 94316/100629 [1:14:02<05:07, 20.50it/s]

 94%|█████████▎| 94319/100629 [1:14:02<05:30, 19.07it/s]

 94%|█████████▎| 94322/100629 [1:14:02<05:10, 20.33it/s]

 94%|█████████▎| 94325/100629 [1:14:03<06:03, 17.36it/s]

 94%|█████████▎| 94329/100629 [1:14:03<05:19, 19.70it/s]

 94%|█████████▎| 94332/100629 [1:14:03<04:58, 21.08it/s]

 94%|█████████▎| 94335/100629 [1:14:03<05:00, 20.95it/s]

 94%|█████████▎| 94339/100629 [1:14:03<04:23, 23.84it/s]

 94%|█████████▍| 94343/100629 [1:14:03<04:04, 25.76it/s]

 94%|█████████▍| 94346/100629 [1:14:03<04:55, 21.25it/s]

 94%|█████████▍| 94349/100629 [1:14:04<05:48, 18.02it/s]

 94%|█████████▍| 94351/100629 [1:14:04<06:17, 16.63it/s]

 94%|█████████▍| 94354/100629 [1:14:04<05:26, 19.22it/s]

 94%|█████████▍| 94358/100629 [1:14:04<04:32, 23.03it/s]

 94%|█████████▍| 94361/100629 [1:14:04<05:14, 19.90it/s]

 94%|█████████▍| 94364/100629 [1:14:05<06:01, 17.33it/s]

 94%|█████████▍| 94367/100629 [1:14:05<05:52, 17.77it/s]

 94%|█████████▍| 94370/100629 [1:14:05<05:11, 20.10it/s]

 94%|█████████▍| 94373/100629 [1:14:05<05:07, 20.33it/s]

 94%|█████████▍| 94376/100629 [1:14:05<04:46, 21.84it/s]

 94%|█████████▍| 94379/100629 [1:14:05<05:14, 19.87it/s]

 94%|█████████▍| 94382/100629 [1:14:05<06:12, 16.78it/s]

 94%|█████████▍| 94385/100629 [1:14:06<05:33, 18.74it/s]

 94%|█████████▍| 94388/100629 [1:14:06<05:33, 18.73it/s]

 94%|█████████▍| 94391/100629 [1:14:06<05:20, 19.44it/s]

 94%|█████████▍| 94394/100629 [1:14:06<05:30, 18.86it/s]

 94%|█████████▍| 94396/100629 [1:14:06<05:34, 18.61it/s]

 94%|█████████▍| 94399/100629 [1:14:06<05:13, 19.89it/s]

 94%|█████████▍| 94403/100629 [1:14:06<04:14, 24.48it/s]

 94%|█████████▍| 94407/100629 [1:14:07<03:48, 27.19it/s]

 94%|█████████▍| 94410/100629 [1:14:07<04:05, 25.29it/s]

 94%|█████████▍| 94413/100629 [1:14:07<04:19, 23.92it/s]

 94%|█████████▍| 94416/100629 [1:14:07<04:11, 24.68it/s]

 94%|█████████▍| 94419/100629 [1:14:07<04:11, 24.71it/s]

 94%|█████████▍| 94422/100629 [1:14:07<04:58, 20.79it/s]

 94%|█████████▍| 94425/100629 [1:14:07<04:49, 21.45it/s]

 94%|█████████▍| 94428/100629 [1:14:08<05:27, 18.91it/s]

 94%|█████████▍| 94431/100629 [1:14:08<04:54, 21.06it/s]

 94%|█████████▍| 94434/100629 [1:14:08<04:31, 22.78it/s]

 94%|█████████▍| 94437/100629 [1:14:08<05:06, 20.21it/s]

 94%|█████████▍| 94440/100629 [1:14:08<05:21, 19.27it/s]

 94%|█████████▍| 94443/100629 [1:14:08<05:05, 20.28it/s]

 94%|█████████▍| 94447/100629 [1:14:08<04:31, 22.80it/s]

 94%|█████████▍| 94450/100629 [1:14:09<04:38, 22.21it/s]

 94%|█████████▍| 94453/100629 [1:14:09<05:06, 20.18it/s]

 94%|█████████▍| 94457/100629 [1:14:09<04:55, 20.90it/s]

 94%|█████████▍| 94461/100629 [1:14:09<04:44, 21.71it/s]

 94%|█████████▍| 94464/100629 [1:14:09<04:40, 22.00it/s]

 94%|█████████▍| 94467/100629 [1:14:09<04:56, 20.78it/s]

 94%|█████████▍| 94470/100629 [1:14:09<04:39, 22.04it/s]

 94%|█████████▍| 94474/100629 [1:14:10<04:18, 23.79it/s]

 94%|█████████▍| 94477/100629 [1:14:10<04:10, 24.55it/s]

 94%|█████████▍| 94480/100629 [1:14:10<04:38, 22.06it/s]

 94%|█████████▍| 94484/100629 [1:14:10<03:56, 25.98it/s]

 94%|█████████▍| 94488/100629 [1:14:10<03:35, 28.56it/s]

 94%|█████████▍| 94492/100629 [1:14:10<04:12, 24.32it/s]

 94%|█████████▍| 94495/100629 [1:14:10<04:05, 25.02it/s]

 94%|█████████▍| 94499/100629 [1:14:11<04:07, 24.72it/s]

 94%|█████████▍| 94502/100629 [1:14:11<04:27, 22.92it/s]

 94%|█████████▍| 94506/100629 [1:14:11<04:04, 25.09it/s]

 94%|█████████▍| 94509/100629 [1:14:11<05:14, 19.45it/s]

 94%|█████████▍| 94512/100629 [1:14:11<05:32, 18.40it/s]

 94%|█████████▍| 94515/100629 [1:14:12<05:34, 18.30it/s]

 94%|█████████▍| 94518/100629 [1:14:12<05:13, 19.50it/s]

 94%|█████████▍| 94521/100629 [1:14:12<05:19, 19.11it/s]

 94%|█████████▍| 94524/100629 [1:14:12<04:59, 20.39it/s]

 94%|█████████▍| 94527/100629 [1:14:12<05:09, 19.74it/s]

 94%|█████████▍| 94532/100629 [1:14:12<04:05, 24.87it/s]

 94%|█████████▍| 94535/100629 [1:14:12<04:01, 25.19it/s]

 94%|█████████▍| 94538/100629 [1:14:12<04:02, 25.11it/s]

 94%|█████████▍| 94542/100629 [1:14:13<04:03, 25.01it/s]

 94%|█████████▍| 94545/100629 [1:14:13<04:09, 24.42it/s]

 94%|█████████▍| 94549/100629 [1:14:13<04:27, 22.74it/s]

 94%|█████████▍| 94552/100629 [1:14:13<05:59, 16.91it/s]

 94%|█████████▍| 94554/100629 [1:14:13<05:54, 17.14it/s]

 94%|█████████▍| 94556/100629 [1:14:13<05:49, 17.39it/s]

 94%|█████████▍| 94559/100629 [1:14:14<05:28, 18.45it/s]

 94%|█████████▍| 94562/100629 [1:14:14<06:06, 16.55it/s]

 94%|█████████▍| 94564/100629 [1:14:14<06:10, 16.38it/s]

 94%|█████████▍| 94566/100629 [1:14:14<06:08, 16.46it/s]

 94%|█████████▍| 94570/100629 [1:14:14<04:57, 20.39it/s]

 94%|█████████▍| 94573/100629 [1:14:14<05:19, 18.96it/s]

 94%|█████████▍| 94575/100629 [1:14:15<06:11, 16.30it/s]

 94%|█████████▍| 94577/100629 [1:14:15<05:59, 16.84it/s]

 94%|█████████▍| 94579/100629 [1:14:15<05:52, 17.15it/s]

 94%|█████████▍| 94581/100629 [1:14:15<05:59, 16.80it/s]

 94%|█████████▍| 94583/100629 [1:14:15<06:02, 16.66it/s]

 94%|█████████▍| 94585/100629 [1:14:15<06:23, 15.77it/s]

 94%|█████████▍| 94589/100629 [1:14:15<06:32, 15.38it/s]

 94%|█████████▍| 94592/100629 [1:14:16<05:31, 18.21it/s]

 94%|█████████▍| 94594/100629 [1:14:16<05:49, 17.28it/s]

 94%|█████████▍| 94599/100629 [1:14:16<04:23, 22.86it/s]

 94%|█████████▍| 94603/100629 [1:14:16<04:06, 24.45it/s]

 94%|█████████▍| 94606/100629 [1:14:16<03:57, 25.37it/s]

 94%|█████████▍| 94609/100629 [1:14:16<04:08, 24.19it/s]

 94%|█████████▍| 94612/100629 [1:14:16<04:34, 21.92it/s]

 94%|█████████▍| 94615/100629 [1:14:17<04:26, 22.55it/s]

 94%|█████████▍| 94619/100629 [1:14:17<04:11, 23.90it/s]

 94%|█████████▍| 94624/100629 [1:14:17<03:32, 28.28it/s]

 94%|█████████▍| 94628/100629 [1:14:17<03:40, 27.16it/s]

 94%|█████████▍| 94631/100629 [1:14:17<03:56, 25.35it/s]

 94%|█████████▍| 94634/100629 [1:14:17<04:27, 22.41it/s]

 94%|█████████▍| 94637/100629 [1:14:17<04:36, 21.71it/s]

 94%|█████████▍| 94640/100629 [1:14:18<04:51, 20.56it/s]

 94%|█████████▍| 94643/100629 [1:14:18<04:33, 21.89it/s]

 94%|█████████▍| 94647/100629 [1:14:18<03:53, 25.57it/s]

 94%|█████████▍| 94650/100629 [1:14:18<04:40, 21.31it/s]

 94%|█████████▍| 94654/100629 [1:14:18<04:07, 24.17it/s]

 94%|█████████▍| 94657/100629 [1:14:18<04:39, 21.39it/s]

 94%|█████████▍| 94660/100629 [1:14:19<05:09, 19.27it/s]

 94%|█████████▍| 94663/100629 [1:14:19<04:46, 20.84it/s]

 94%|█████████▍| 94666/100629 [1:14:19<04:22, 22.69it/s]

 94%|█████████▍| 94669/100629 [1:14:19<04:16, 23.22it/s]

 94%|█████████▍| 94672/100629 [1:14:19<04:17, 23.16it/s]

 94%|█████████▍| 94675/100629 [1:14:19<05:02, 19.71it/s]

 94%|█████████▍| 94678/100629 [1:14:19<05:09, 19.25it/s]

 94%|█████████▍| 94681/100629 [1:14:19<05:06, 19.38it/s]

 94%|█████████▍| 94684/100629 [1:14:20<04:47, 20.66it/s]

 94%|█████████▍| 94687/100629 [1:14:20<04:59, 19.82it/s]

 94%|█████████▍| 94691/100629 [1:14:20<04:14, 23.34it/s]

 94%|█████████▍| 94694/100629 [1:14:20<03:59, 24.76it/s]

 94%|█████████▍| 94697/100629 [1:14:20<04:09, 23.79it/s]

 94%|█████████▍| 94700/100629 [1:14:20<04:09, 23.81it/s]

 94%|█████████▍| 94703/100629 [1:14:20<04:15, 23.18it/s]

 94%|█████████▍| 94706/100629 [1:14:21<04:33, 21.63it/s]

 94%|█████████▍| 94709/100629 [1:14:21<04:31, 21.83it/s]

 94%|█████████▍| 94714/100629 [1:14:21<03:42, 26.63it/s]

 94%|█████████▍| 94717/100629 [1:14:21<04:20, 22.68it/s]

 94%|█████████▍| 94721/100629 [1:14:21<03:47, 25.93it/s]

 94%|█████████▍| 94724/100629 [1:14:21<04:28, 21.98it/s]

 94%|█████████▍| 94727/100629 [1:14:21<04:38, 21.16it/s]

 94%|█████████▍| 94731/100629 [1:14:22<04:31, 21.70it/s]

 94%|█████████▍| 94734/100629 [1:14:22<04:52, 20.16it/s]

 94%|█████████▍| 94737/100629 [1:14:22<04:46, 20.56it/s]

 94%|█████████▍| 94740/100629 [1:14:22<04:34, 21.42it/s]

 94%|█████████▍| 94743/100629 [1:14:22<04:13, 23.21it/s]

 94%|█████████▍| 94746/100629 [1:14:22<04:16, 22.95it/s]

 94%|█████████▍| 94749/100629 [1:14:23<04:49, 20.31it/s]

 94%|█████████▍| 94752/100629 [1:14:23<05:00, 19.56it/s]

 94%|█████████▍| 94755/100629 [1:14:23<04:33, 21.51it/s]

 94%|█████████▍| 94758/100629 [1:14:23<04:58, 19.67it/s]

 94%|█████████▍| 94762/100629 [1:14:23<04:21, 22.46it/s]

 94%|█████████▍| 94765/100629 [1:14:23<04:03, 24.08it/s]

 94%|█████████▍| 94768/100629 [1:14:23<04:19, 22.62it/s]

 94%|█████████▍| 94771/100629 [1:14:24<04:25, 22.08it/s]

 94%|█████████▍| 94774/100629 [1:14:24<04:24, 22.12it/s]

 94%|█████████▍| 94777/100629 [1:14:24<04:33, 21.41it/s]

 94%|█████████▍| 94780/100629 [1:14:24<04:33, 21.36it/s]

 94%|█████████▍| 94783/100629 [1:14:24<04:12, 23.17it/s]

 94%|█████████▍| 94787/100629 [1:14:24<03:43, 26.19it/s]

 94%|█████████▍| 94790/100629 [1:14:24<03:55, 24.79it/s]

 94%|█████████▍| 94794/100629 [1:14:24<03:36, 26.96it/s]

 94%|█████████▍| 94797/100629 [1:14:25<03:32, 27.50it/s]

 94%|█████████▍| 94800/100629 [1:14:25<03:48, 25.56it/s]

 94%|█████████▍| 94803/100629 [1:14:25<04:24, 22.06it/s]

 94%|█████████▍| 94806/100629 [1:14:25<04:41, 20.68it/s]

 94%|█████████▍| 94809/100629 [1:14:25<05:55, 16.36it/s]

 94%|█████████▍| 94811/100629 [1:14:25<06:25, 15.09it/s]

 94%|█████████▍| 94814/100629 [1:14:26<05:57, 16.27it/s]

 94%|█████████▍| 94816/100629 [1:14:26<05:45, 16.81it/s]

 94%|█████████▍| 94818/100629 [1:14:26<06:03, 16.01it/s]

 94%|█████████▍| 94820/100629 [1:14:26<06:11, 15.63it/s]

 94%|█████████▍| 94823/100629 [1:14:26<05:38, 17.17it/s]

 94%|█████████▍| 94827/100629 [1:14:26<04:31, 21.40it/s]

 94%|█████████▍| 94830/100629 [1:14:26<04:07, 23.38it/s]

 94%|█████████▍| 94833/100629 [1:14:27<04:28, 21.62it/s]

 94%|█████████▍| 94836/100629 [1:14:27<05:08, 18.78it/s]

 94%|█████████▍| 94839/100629 [1:14:27<05:34, 17.31it/s]

 94%|█████████▍| 94841/100629 [1:14:27<06:42, 14.39it/s]

 94%|█████████▍| 94843/100629 [1:14:27<07:24, 13.02it/s]

 94%|█████████▍| 94846/100629 [1:14:28<06:48, 14.15it/s]

 94%|█████████▍| 94849/100629 [1:14:28<05:56, 16.20it/s]

 94%|█████████▍| 94851/100629 [1:14:28<07:04, 13.62it/s]

 94%|█████████▍| 94853/100629 [1:14:28<06:32, 14.70it/s]

 94%|█████████▍| 94855/100629 [1:14:28<06:10, 15.60it/s]

 94%|█████████▍| 94858/100629 [1:14:28<05:13, 18.40it/s]

 94%|█████████▍| 94862/100629 [1:14:28<04:38, 20.69it/s]

 94%|█████████▍| 94865/100629 [1:14:29<04:39, 20.64it/s]

 94%|█████████▍| 94868/100629 [1:14:29<04:55, 19.53it/s]

 94%|█████████▍| 94871/100629 [1:14:29<05:00, 19.15it/s]

 94%|█████████▍| 94873/100629 [1:14:29<05:44, 16.69it/s]

 94%|█████████▍| 94875/100629 [1:14:29<05:53, 16.27it/s]

 94%|█████████▍| 94877/100629 [1:14:29<05:45, 16.66it/s]

 94%|█████████▍| 94881/100629 [1:14:29<04:30, 21.29it/s]

 94%|█████████▍| 94885/100629 [1:14:29<03:43, 25.70it/s]

 94%|█████████▍| 94888/100629 [1:14:30<04:18, 22.22it/s]

 94%|█████████▍| 94893/100629 [1:14:30<03:40, 26.07it/s]

 94%|█████████▍| 94896/100629 [1:14:30<04:14, 22.51it/s]

 94%|█████████▍| 94899/100629 [1:14:30<04:13, 22.56it/s]

 94%|█████████▍| 94904/100629 [1:14:30<03:26, 27.79it/s]

 94%|█████████▍| 94907/100629 [1:14:30<03:24, 27.96it/s]

 94%|█████████▍| 94910/100629 [1:14:30<03:32, 26.88it/s]

 94%|█████████▍| 94913/100629 [1:14:31<03:46, 25.19it/s]

 94%|█████████▍| 94917/100629 [1:14:31<03:28, 27.42it/s]

 94%|█████████▍| 94920/100629 [1:14:31<03:57, 24.07it/s]

 94%|█████████▍| 94923/100629 [1:14:31<04:06, 23.15it/s]

 94%|█████████▍| 94926/100629 [1:14:31<04:25, 21.45it/s]

 94%|█████████▍| 94929/100629 [1:14:31<05:04, 18.73it/s]

 94%|█████████▍| 94931/100629 [1:14:32<05:33, 17.06it/s]

 94%|█████████▍| 94934/100629 [1:14:32<05:21, 17.69it/s]

 94%|█████████▍| 94937/100629 [1:14:32<04:51, 19.52it/s]

 94%|█████████▍| 94940/100629 [1:14:32<04:27, 21.24it/s]

 94%|█████████▍| 94943/100629 [1:14:32<04:38, 20.44it/s]

 94%|█████████▍| 94946/100629 [1:14:32<04:25, 21.44it/s]

 94%|█████████▍| 94949/100629 [1:14:32<04:09, 22.79it/s]

 94%|█████████▍| 94952/100629 [1:14:33<05:26, 17.37it/s]

 94%|█████████▍| 94955/100629 [1:14:33<05:23, 17.55it/s]

 94%|█████████▍| 94958/100629 [1:14:33<05:13, 18.07it/s]

 94%|█████████▍| 94960/100629 [1:14:33<05:56, 15.89it/s]

 94%|█████████▍| 94964/100629 [1:14:33<05:10, 18.27it/s]

 94%|█████████▍| 94966/100629 [1:14:33<05:22, 17.54it/s]

 94%|█████████▍| 94970/100629 [1:14:34<04:30, 20.94it/s]

 94%|█████████▍| 94973/100629 [1:14:34<04:47, 19.69it/s]

 94%|█████████▍| 94976/100629 [1:14:34<04:26, 21.20it/s]

 94%|█████████▍| 94979/100629 [1:14:34<04:13, 22.29it/s]

 94%|█████████▍| 94984/100629 [1:14:34<03:28, 27.09it/s]

 94%|█████████▍| 94987/100629 [1:14:34<04:03, 23.21it/s]

 94%|█████████▍| 94990/100629 [1:14:34<04:42, 19.99it/s]

 94%|█████████▍| 94994/100629 [1:14:35<03:56, 23.83it/s]

 94%|█████████▍| 94997/100629 [1:14:35<04:44, 19.78it/s]

 94%|█████████▍| 95000/100629 [1:14:35<04:35, 20.42it/s]

 94%|█████████▍| 95004/100629 [1:14:35<04:09, 22.57it/s]

 94%|█████████▍| 95007/100629 [1:14:35<04:02, 23.19it/s]

 94%|█████████▍| 95010/100629 [1:14:35<04:08, 22.58it/s]

 94%|█████████▍| 95014/100629 [1:14:35<03:44, 25.02it/s]

 94%|█████████▍| 95017/100629 [1:14:36<03:42, 25.19it/s]

 94%|█████████▍| 95020/100629 [1:14:36<03:50, 24.34it/s]

 94%|█████████▍| 95027/100629 [1:14:36<02:48, 33.23it/s]

 94%|█████████▍| 95031/100629 [1:14:36<02:54, 31.99it/s]

 94%|█████████▍| 95035/100629 [1:14:36<03:16, 28.50it/s]

 94%|█████████▍| 95038/100629 [1:14:36<03:28, 26.84it/s]

 94%|█████████▍| 95041/100629 [1:14:36<04:07, 22.55it/s]

 94%|█████████▍| 95044/100629 [1:14:37<04:56, 18.83it/s]

 94%|█████████▍| 95047/100629 [1:14:37<04:54, 18.95it/s]

 94%|█████████▍| 95050/100629 [1:14:37<05:18, 17.50it/s]

 94%|█████████▍| 95053/100629 [1:14:37<04:53, 18.99it/s]

 94%|█████████▍| 95056/100629 [1:14:37<04:41, 19.77it/s]

 94%|█████████▍| 95059/100629 [1:14:38<04:47, 19.38it/s]

 94%|█████████▍| 95062/100629 [1:14:38<04:22, 21.21it/s]

 94%|█████████▍| 95065/100629 [1:14:38<05:23, 17.19it/s]

 94%|█████████▍| 95070/100629 [1:14:38<04:14, 21.80it/s]

 94%|█████████▍| 95073/100629 [1:14:38<03:57, 23.42it/s]

 94%|█████████▍| 95077/100629 [1:14:38<03:49, 24.16it/s]

 94%|█████████▍| 95080/100629 [1:14:38<04:16, 21.60it/s]

 94%|█████████▍| 95083/100629 [1:14:39<03:59, 23.14it/s]

 94%|█████████▍| 95086/100629 [1:14:39<04:02, 22.87it/s]

 94%|█████████▍| 95089/100629 [1:14:39<06:17, 14.66it/s]

 94%|█████████▍| 95091/100629 [1:14:39<06:14, 14.79it/s]

 94%|█████████▍| 95093/100629 [1:14:39<06:05, 15.16it/s]

 95%|█████████▍| 95097/100629 [1:14:39<04:48, 19.15it/s]

 95%|█████████▍| 95100/100629 [1:14:40<04:47, 19.21it/s]

 95%|█████████▍| 95104/100629 [1:14:40<03:54, 23.57it/s]

 95%|█████████▍| 95107/100629 [1:14:40<04:24, 20.89it/s]

 95%|█████████▍| 95110/100629 [1:14:40<04:09, 22.09it/s]

 95%|█████████▍| 95113/100629 [1:14:40<04:13, 21.72it/s]

 95%|█████████▍| 95116/100629 [1:14:40<04:03, 22.67it/s]

 95%|█████████▍| 95121/100629 [1:14:40<03:18, 27.71it/s]

 95%|█████████▍| 95124/100629 [1:14:41<03:16, 28.06it/s]

 95%|█████████▍| 95128/100629 [1:14:41<03:23, 27.00it/s]

 95%|█████████▍| 95131/100629 [1:14:41<03:25, 26.75it/s]

 95%|█████████▍| 95134/100629 [1:14:41<03:36, 25.43it/s]

 95%|█████████▍| 95138/100629 [1:14:41<03:22, 27.05it/s]

 95%|█████████▍| 95141/100629 [1:14:41<03:22, 27.10it/s]

 95%|█████████▍| 95144/100629 [1:14:41<03:18, 27.63it/s]

 95%|█████████▍| 95147/100629 [1:14:41<03:44, 24.47it/s]

 95%|█████████▍| 95151/100629 [1:14:42<03:16, 27.83it/s]

 95%|█████████▍| 95154/100629 [1:14:42<03:34, 25.50it/s]

 95%|█████████▍| 95157/100629 [1:14:42<05:43, 15.92it/s]

 95%|█████████▍| 95160/100629 [1:14:42<05:03, 18.05it/s]

 95%|█████████▍| 95164/100629 [1:14:42<04:11, 21.77it/s]

 95%|█████████▍| 95167/100629 [1:14:42<04:12, 21.64it/s]

 95%|█████████▍| 95170/100629 [1:14:43<04:46, 19.08it/s]

 95%|█████████▍| 95174/100629 [1:14:43<04:17, 21.15it/s]

 95%|█████████▍| 95177/100629 [1:14:43<04:07, 22.01it/s]

 95%|█████████▍| 95182/100629 [1:14:43<03:34, 25.45it/s]

 95%|█████████▍| 95185/100629 [1:14:43<03:55, 23.12it/s]

 95%|█████████▍| 95188/100629 [1:14:43<04:22, 20.71it/s]

 95%|█████████▍| 95191/100629 [1:14:43<04:06, 22.10it/s]

 95%|█████████▍| 95194/100629 [1:14:44<04:08, 21.83it/s]

 95%|█████████▍| 95197/100629 [1:14:44<04:29, 20.17it/s]

 95%|█████████▍| 95201/100629 [1:14:44<03:46, 23.92it/s]

 95%|█████████▍| 95204/100629 [1:14:44<04:22, 20.64it/s]

 95%|█████████▍| 95208/100629 [1:14:44<03:45, 24.01it/s]

 95%|█████████▍| 95211/100629 [1:14:44<04:00, 22.53it/s]

 95%|█████████▍| 95214/100629 [1:14:45<04:13, 21.38it/s]

 95%|█████████▍| 95217/100629 [1:14:45<04:53, 18.44it/s]

 95%|█████████▍| 95219/100629 [1:14:45<05:19, 16.94it/s]

 95%|█████████▍| 95223/100629 [1:14:45<04:14, 21.26it/s]

 95%|█████████▍| 95226/100629 [1:14:45<04:05, 21.99it/s]

 95%|█████████▍| 95230/100629 [1:14:45<03:59, 22.59it/s]

 95%|█████████▍| 95233/100629 [1:14:45<03:47, 23.72it/s]

 95%|█████████▍| 95236/100629 [1:14:46<04:02, 22.23it/s]

 95%|█████████▍| 95239/100629 [1:14:46<03:54, 22.96it/s]

 95%|█████████▍| 95242/100629 [1:14:46<03:55, 22.86it/s]

 95%|█████████▍| 95245/100629 [1:14:46<04:12, 21.36it/s]

 95%|█████████▍| 95248/100629 [1:14:46<04:29, 19.96it/s]

 95%|█████████▍| 95253/100629 [1:14:46<03:25, 26.19it/s]

 95%|█████████▍| 95257/100629 [1:14:46<03:09, 28.35it/s]

 95%|█████████▍| 95261/100629 [1:14:47<03:40, 24.39it/s]

 95%|█████████▍| 95264/100629 [1:14:47<03:36, 24.75it/s]

 95%|█████████▍| 95268/100629 [1:14:47<03:24, 26.16it/s]

 95%|█████████▍| 95271/100629 [1:14:47<03:25, 26.10it/s]

 95%|█████████▍| 95274/100629 [1:14:47<03:19, 26.86it/s]

 95%|█████████▍| 95278/100629 [1:14:47<03:32, 25.22it/s]

 95%|█████████▍| 95284/100629 [1:14:47<02:43, 32.77it/s]

 95%|█████████▍| 95288/100629 [1:14:48<03:20, 26.66it/s]

 95%|█████████▍| 95291/100629 [1:14:48<03:37, 24.50it/s]

 95%|█████████▍| 95294/100629 [1:14:48<04:26, 19.99it/s]

 95%|█████████▍| 95297/100629 [1:14:48<04:50, 18.35it/s]

 95%|█████████▍| 95302/100629 [1:14:48<04:14, 20.93it/s]

 95%|█████████▍| 95305/100629 [1:14:48<04:13, 20.97it/s]

 95%|█████████▍| 95308/100629 [1:14:49<04:27, 19.85it/s]

 95%|█████████▍| 95311/100629 [1:14:49<04:32, 19.51it/s]

 95%|█████████▍| 95313/100629 [1:14:49<04:33, 19.44it/s]

 95%|█████████▍| 95316/100629 [1:14:49<04:27, 19.87it/s]

 95%|█████████▍| 95319/100629 [1:14:49<04:18, 20.55it/s]

 95%|█████████▍| 95323/100629 [1:14:49<03:32, 24.91it/s]

 95%|█████████▍| 95326/100629 [1:14:50<04:12, 21.00it/s]

 95%|█████████▍| 95329/100629 [1:14:50<03:59, 22.09it/s]

 95%|█████████▍| 95333/100629 [1:14:50<03:24, 25.84it/s]

 95%|█████████▍| 95337/100629 [1:14:50<03:02, 29.05it/s]

 95%|█████████▍| 95341/100629 [1:14:50<03:30, 25.07it/s]

 95%|█████████▍| 95344/100629 [1:14:50<03:57, 22.24it/s]

 95%|█████████▍| 95347/100629 [1:14:50<03:55, 22.42it/s]

 95%|█████████▍| 95350/100629 [1:14:51<04:34, 19.25it/s]

 95%|█████████▍| 95353/100629 [1:14:51<04:31, 19.47it/s]

 95%|█████████▍| 95356/100629 [1:14:51<04:31, 19.42it/s]

 95%|█████████▍| 95359/100629 [1:14:51<04:26, 19.79it/s]

 95%|█████████▍| 95362/100629 [1:14:51<04:06, 21.34it/s]

 95%|█████████▍| 95365/100629 [1:14:51<04:12, 20.83it/s]

 95%|█████████▍| 95368/100629 [1:14:51<04:29, 19.52it/s]

 95%|█████████▍| 95371/100629 [1:14:52<04:07, 21.22it/s]

 95%|█████████▍| 95375/100629 [1:14:52<04:11, 20.90it/s]

 95%|█████████▍| 95378/100629 [1:14:52<04:56, 17.69it/s]

 95%|█████████▍| 95381/100629 [1:14:52<04:40, 18.71it/s]

 95%|█████████▍| 95385/100629 [1:14:52<03:49, 22.90it/s]

 95%|█████████▍| 95389/100629 [1:14:52<03:25, 25.49it/s]

 95%|█████████▍| 95392/100629 [1:14:52<03:22, 25.88it/s]

 95%|█████████▍| 95395/100629 [1:14:53<03:33, 24.54it/s]

 95%|█████████▍| 95399/100629 [1:14:53<03:30, 24.84it/s]

 95%|█████████▍| 95402/100629 [1:14:53<04:38, 18.77it/s]

 95%|█████████▍| 95405/100629 [1:14:53<04:39, 18.70it/s]

 95%|█████████▍| 95408/100629 [1:14:53<04:37, 18.82it/s]

 95%|█████████▍| 95411/100629 [1:14:53<04:08, 21.01it/s]

 95%|█████████▍| 95414/100629 [1:14:54<03:59, 21.77it/s]

 95%|█████████▍| 95417/100629 [1:14:54<03:52, 22.45it/s]

 95%|█████████▍| 95420/100629 [1:14:54<03:38, 23.89it/s]

 95%|█████████▍| 95424/100629 [1:14:54<03:13, 26.85it/s]

 95%|█████████▍| 95427/100629 [1:14:54<03:57, 21.90it/s]

 95%|█████████▍| 95430/100629 [1:14:54<04:21, 19.91it/s]

 95%|█████████▍| 95434/100629 [1:14:54<03:44, 23.11it/s]

 95%|█████████▍| 95437/100629 [1:14:55<03:48, 22.71it/s]

 95%|█████████▍| 95440/100629 [1:14:55<04:43, 18.27it/s]

 95%|█████████▍| 95443/100629 [1:14:55<04:16, 20.25it/s]

 95%|█████████▍| 95447/100629 [1:14:55<03:40, 23.53it/s]

 95%|█████████▍| 95450/100629 [1:14:55<04:01, 21.41it/s]

 95%|█████████▍| 95453/100629 [1:14:55<03:59, 21.63it/s]

 95%|█████████▍| 95456/100629 [1:14:56<04:10, 20.66it/s]

 95%|█████████▍| 95459/100629 [1:14:56<04:36, 18.71it/s]

 95%|█████████▍| 95461/100629 [1:14:56<04:36, 18.66it/s]

 95%|█████████▍| 95464/100629 [1:14:56<04:28, 19.24it/s]

 95%|█████████▍| 95466/100629 [1:14:56<04:34, 18.82it/s]

 95%|█████████▍| 95470/100629 [1:14:56<04:14, 20.28it/s]

 95%|█████████▍| 95473/100629 [1:14:56<04:21, 19.73it/s]

 95%|█████████▍| 95476/100629 [1:14:57<04:52, 17.62it/s]

 95%|█████████▍| 95479/100629 [1:14:57<04:27, 19.27it/s]

 95%|█████████▍| 95482/100629 [1:14:57<04:12, 20.38it/s]

 95%|█████████▍| 95486/100629 [1:14:57<03:54, 21.92it/s]

 95%|█████████▍| 95490/100629 [1:14:57<03:47, 22.56it/s]

 95%|█████████▍| 95494/100629 [1:14:57<03:29, 24.46it/s]

 95%|█████████▍| 95497/100629 [1:14:58<04:03, 21.05it/s]

 95%|█████████▍| 95500/100629 [1:14:58<04:11, 20.36it/s]

 95%|█████████▍| 95504/100629 [1:14:58<03:32, 24.15it/s]

 95%|█████████▍| 95507/100629 [1:14:58<03:28, 24.55it/s]

 95%|█████████▍| 95510/100629 [1:14:58<03:55, 21.77it/s]

 95%|█████████▍| 95513/100629 [1:14:58<03:40, 23.17it/s]

 95%|█████████▍| 95516/100629 [1:14:58<04:01, 21.22it/s]

 95%|█████████▍| 95519/100629 [1:14:59<04:23, 19.36it/s]

 95%|█████████▍| 95522/100629 [1:14:59<04:24, 19.33it/s]

 95%|█████████▍| 95525/100629 [1:14:59<04:25, 19.19it/s]

 95%|█████████▍| 95529/100629 [1:14:59<03:45, 22.61it/s]

 95%|█████████▍| 95532/100629 [1:14:59<03:52, 21.95it/s]

 95%|█████████▍| 95535/100629 [1:14:59<04:13, 20.09it/s]

 95%|█████████▍| 95538/100629 [1:14:59<03:57, 21.43it/s]

 95%|█████████▍| 95542/100629 [1:15:00<03:23, 25.00it/s]

 95%|█████████▍| 95545/100629 [1:15:00<03:40, 23.06it/s]

 95%|█████████▍| 95548/100629 [1:15:00<03:38, 23.24it/s]

 95%|█████████▍| 95551/100629 [1:15:00<04:33, 18.57it/s]

 95%|█████████▍| 95556/100629 [1:15:00<03:32, 23.82it/s]

 95%|█████████▍| 95559/100629 [1:15:00<03:23, 24.89it/s]

 95%|█████████▍| 95562/100629 [1:15:01<04:14, 19.90it/s]

 95%|█████████▍| 95565/100629 [1:15:01<04:14, 19.92it/s]

 95%|█████████▍| 95568/100629 [1:15:01<03:56, 21.40it/s]

 95%|█████████▍| 95571/100629 [1:15:01<03:43, 22.60it/s]

 95%|█████████▍| 95574/100629 [1:15:01<03:29, 24.16it/s]

 95%|█████████▍| 95577/100629 [1:15:01<04:18, 19.55it/s]

 95%|█████████▍| 95580/100629 [1:15:01<04:11, 20.09it/s]

 95%|█████████▍| 95583/100629 [1:15:02<03:48, 22.09it/s]

 95%|█████████▍| 95586/100629 [1:15:02<04:08, 20.32it/s]

 95%|█████████▍| 95590/100629 [1:15:02<03:31, 23.77it/s]

 95%|█████████▍| 95593/100629 [1:15:02<04:04, 20.61it/s]

 95%|█████████▍| 95596/100629 [1:15:02<03:51, 21.78it/s]

 95%|█████████▌| 95599/100629 [1:15:02<03:48, 21.97it/s]

 95%|█████████▌| 95603/100629 [1:15:02<03:29, 24.03it/s]

 95%|█████████▌| 95606/100629 [1:15:03<03:41, 22.70it/s]

 95%|█████████▌| 95609/100629 [1:15:03<03:53, 21.46it/s]

 95%|█████████▌| 95613/100629 [1:15:03<03:22, 24.78it/s]

 95%|█████████▌| 95618/100629 [1:15:03<02:55, 28.48it/s]

 95%|█████████▌| 95621/100629 [1:15:03<02:57, 28.20it/s]

 95%|█████████▌| 95624/100629 [1:15:03<03:07, 26.69it/s]

 95%|█████████▌| 95627/100629 [1:15:03<03:12, 26.05it/s]

 95%|█████████▌| 95631/100629 [1:15:03<03:04, 27.10it/s]

 95%|█████████▌| 95635/100629 [1:15:04<03:14, 25.69it/s]

 95%|█████████▌| 95638/100629 [1:15:04<03:25, 24.25it/s]

 95%|█████████▌| 95641/100629 [1:15:04<03:32, 23.44it/s]

 95%|█████████▌| 95645/100629 [1:15:04<03:26, 24.10it/s]

 95%|█████████▌| 95649/100629 [1:15:04<03:21, 24.71it/s]

 95%|█████████▌| 95652/100629 [1:15:04<03:45, 22.06it/s]

 95%|█████████▌| 95655/100629 [1:15:05<04:02, 20.53it/s]

 95%|█████████▌| 95658/100629 [1:15:05<03:44, 22.18it/s]

 95%|█████████▌| 95663/100629 [1:15:05<03:01, 27.43it/s]

 95%|█████████▌| 95666/100629 [1:15:05<03:08, 26.36it/s]

 95%|█████████▌| 95669/100629 [1:15:05<03:07, 26.50it/s]

 95%|█████████▌| 95675/100629 [1:15:05<02:39, 31.07it/s]

 95%|█████████▌| 95679/100629 [1:15:05<03:24, 24.18it/s]

 95%|█████████▌| 95682/100629 [1:15:06<03:18, 24.94it/s]

 95%|█████████▌| 95685/100629 [1:15:06<03:19, 24.76it/s]

 95%|█████████▌| 95688/100629 [1:15:06<03:12, 25.72it/s]

 95%|█████████▌| 95691/100629 [1:15:06<03:35, 22.96it/s]

 95%|█████████▌| 95694/100629 [1:15:06<04:15, 19.33it/s]

 95%|█████████▌| 95697/100629 [1:15:06<03:52, 21.21it/s]

 95%|█████████▌| 95700/100629 [1:15:06<03:46, 21.76it/s]

 95%|█████████▌| 95703/100629 [1:15:07<03:42, 22.15it/s]

 95%|█████████▌| 95706/100629 [1:15:07<04:34, 17.90it/s]

 95%|█████████▌| 95710/100629 [1:15:07<03:47, 21.63it/s]

 95%|█████████▌| 95713/100629 [1:15:07<03:34, 22.95it/s]

 95%|█████████▌| 95716/100629 [1:15:07<03:47, 21.55it/s]

 95%|█████████▌| 95719/100629 [1:15:07<04:18, 18.99it/s]

 95%|█████████▌| 95722/100629 [1:15:08<04:30, 18.15it/s]

 95%|█████████▌| 95724/100629 [1:15:08<05:07, 15.95it/s]

 95%|█████████▌| 95727/100629 [1:15:08<04:22, 18.70it/s]

 95%|█████████▌| 95730/100629 [1:15:08<04:09, 19.62it/s]

 95%|█████████▌| 95733/100629 [1:15:08<03:53, 20.98it/s]

 95%|█████████▌| 95736/100629 [1:15:08<03:43, 21.93it/s]

 95%|█████████▌| 95739/100629 [1:15:08<04:23, 18.56it/s]

 95%|█████████▌| 95742/100629 [1:15:09<04:19, 18.81it/s]

 95%|█████████▌| 95745/100629 [1:15:09<04:22, 18.58it/s]

 95%|█████████▌| 95748/100629 [1:15:09<04:00, 20.28it/s]

 95%|█████████▌| 95752/100629 [1:15:09<03:19, 24.40it/s]

 95%|█████████▌| 95755/100629 [1:15:09<03:17, 24.67it/s]

 95%|█████████▌| 95758/100629 [1:15:09<03:37, 22.42it/s]

 95%|█████████▌| 95761/100629 [1:15:09<03:52, 20.98it/s]

 95%|█████████▌| 95764/100629 [1:15:10<03:38, 22.25it/s]

 95%|█████████▌| 95767/100629 [1:15:10<03:55, 20.69it/s]

 95%|█████████▌| 95770/100629 [1:15:10<04:19, 18.71it/s]

 95%|█████████▌| 95772/100629 [1:15:10<05:09, 15.69it/s]

 95%|█████████▌| 95774/100629 [1:15:10<04:55, 16.40it/s]

 95%|█████████▌| 95778/100629 [1:15:10<03:45, 21.47it/s]

 95%|█████████▌| 95782/100629 [1:15:11<03:59, 20.28it/s]

 95%|█████████▌| 95785/100629 [1:15:11<03:45, 21.49it/s]

 95%|█████████▌| 95789/100629 [1:15:11<03:19, 24.25it/s]

 95%|█████████▌| 95792/100629 [1:15:11<03:17, 24.50it/s]

 95%|█████████▌| 95795/100629 [1:15:11<03:41, 21.81it/s]

 95%|█████████▌| 95798/100629 [1:15:11<03:40, 21.89it/s]

 95%|█████████▌| 95801/100629 [1:15:11<03:47, 21.20it/s]

 95%|█████████▌| 95804/100629 [1:15:11<03:50, 20.94it/s]

 95%|█████████▌| 95808/100629 [1:15:12<03:19, 24.20it/s]

 95%|█████████▌| 95811/100629 [1:15:12<03:15, 24.59it/s]

 95%|█████████▌| 95815/100629 [1:15:12<02:59, 26.89it/s]

 95%|█████████▌| 95818/100629 [1:15:12<02:54, 27.59it/s]

 95%|█████████▌| 95821/100629 [1:15:12<02:51, 28.10it/s]

 95%|█████████▌| 95824/100629 [1:15:12<03:21, 23.85it/s]

 95%|█████████▌| 95827/100629 [1:15:12<03:22, 23.69it/s]

 95%|█████████▌| 95830/100629 [1:15:12<03:15, 24.49it/s]

 95%|█████████▌| 95833/100629 [1:15:13<03:29, 22.85it/s]

 95%|█████████▌| 95839/100629 [1:15:13<02:44, 29.17it/s]

 95%|█████████▌| 95842/100629 [1:15:13<03:50, 20.74it/s]

 95%|█████████▌| 95845/100629 [1:15:13<03:37, 21.98it/s]

 95%|█████████▌| 95848/100629 [1:15:13<03:42, 21.52it/s]

 95%|█████████▌| 95851/100629 [1:15:14<04:22, 18.18it/s]

 95%|█████████▌| 95856/100629 [1:15:14<03:26, 23.08it/s]

 95%|█████████▌| 95859/100629 [1:15:14<03:56, 20.21it/s]

 95%|█████████▌| 95862/100629 [1:15:14<03:57, 20.08it/s]

 95%|█████████▌| 95865/100629 [1:15:14<04:34, 17.35it/s]

 95%|█████████▌| 95869/100629 [1:15:14<03:47, 20.90it/s]

 95%|█████████▌| 95872/100629 [1:15:14<03:48, 20.85it/s]

 95%|█████████▌| 95875/100629 [1:15:15<03:54, 20.23it/s]

 95%|█████████▌| 95878/100629 [1:15:15<03:43, 21.28it/s]

 95%|█████████▌| 95881/100629 [1:15:15<04:05, 19.36it/s]

 95%|█████████▌| 95884/100629 [1:15:15<03:46, 20.96it/s]

 95%|█████████▌| 95887/100629 [1:15:15<04:12, 18.77it/s]

 95%|█████████▌| 95890/100629 [1:15:15<04:14, 18.60it/s]

 95%|█████████▌| 95893/100629 [1:15:16<03:55, 20.14it/s]

 95%|█████████▌| 95896/100629 [1:15:16<03:48, 20.68it/s]

 95%|█████████▌| 95899/100629 [1:15:16<03:45, 21.01it/s]

 95%|█████████▌| 95902/100629 [1:15:16<03:31, 22.39it/s]

 95%|█████████▌| 95905/100629 [1:15:16<03:45, 20.99it/s]

 95%|█████████▌| 95909/100629 [1:15:16<03:32, 22.17it/s]

 95%|█████████▌| 95912/100629 [1:15:16<03:18, 23.71it/s]

 95%|█████████▌| 95915/100629 [1:15:17<03:41, 21.26it/s]

 95%|█████████▌| 95919/100629 [1:15:17<03:37, 21.61it/s]

 95%|█████████▌| 95923/100629 [1:15:17<03:41, 21.24it/s]

 95%|█████████▌| 95926/100629 [1:15:17<03:25, 22.87it/s]

 95%|█████████▌| 95929/100629 [1:15:17<03:36, 21.75it/s]

 95%|█████████▌| 95932/100629 [1:15:17<03:41, 21.20it/s]

 95%|█████████▌| 95935/100629 [1:15:17<03:41, 21.19it/s]

 95%|█████████▌| 95940/100629 [1:15:18<02:49, 27.60it/s]

 95%|█████████▌| 95943/100629 [1:15:18<03:07, 25.00it/s]

 95%|█████████▌| 95946/100629 [1:15:18<03:17, 23.70it/s]

 95%|█████████▌| 95949/100629 [1:15:18<03:20, 23.36it/s]

 95%|█████████▌| 95952/100629 [1:15:18<03:27, 22.58it/s]

 95%|█████████▌| 95955/100629 [1:15:18<03:41, 21.11it/s]

 95%|█████████▌| 95958/100629 [1:15:19<04:02, 19.22it/s]

 95%|█████████▌| 95961/100629 [1:15:19<04:05, 19.04it/s]

 95%|█████████▌| 95965/100629 [1:15:19<03:26, 22.56it/s]

 95%|█████████▌| 95968/100629 [1:15:19<04:01, 19.33it/s]

 95%|█████████▌| 95971/100629 [1:15:19<03:46, 20.60it/s]

 95%|█████████▌| 95975/100629 [1:15:19<03:17, 23.54it/s]

 95%|█████████▌| 95979/100629 [1:15:19<03:04, 25.15it/s]

 95%|█████████▌| 95982/100629 [1:15:20<03:09, 24.47it/s]

 95%|█████████▌| 95985/100629 [1:15:20<03:08, 24.64it/s]

 95%|█████████▌| 95988/100629 [1:15:20<03:11, 24.19it/s]

 95%|█████████▌| 95992/100629 [1:15:20<02:59, 25.80it/s]

 95%|█████████▌| 95995/100629 [1:15:20<03:13, 23.98it/s]

 95%|█████████▌| 95998/100629 [1:15:20<03:22, 22.87it/s]

 95%|█████████▌| 96001/100629 [1:15:20<03:37, 21.28it/s]

 95%|█████████▌| 96004/100629 [1:15:20<03:28, 22.15it/s]

 95%|█████████▌| 96007/100629 [1:15:21<04:18, 17.87it/s]

 95%|█████████▌| 96009/100629 [1:15:21<04:51, 15.87it/s]

 95%|█████████▌| 96012/100629 [1:15:21<04:19, 17.77it/s]

 95%|█████████▌| 96014/100629 [1:15:21<04:18, 17.87it/s]

 95%|█████████▌| 96016/100629 [1:15:21<04:16, 18.00it/s]

 95%|█████████▌| 96018/100629 [1:15:21<04:27, 17.26it/s]

 95%|█████████▌| 96020/100629 [1:15:22<04:41, 16.38it/s]

 95%|█████████▌| 96022/100629 [1:15:22<05:15, 14.61it/s]

 95%|█████████▌| 96024/100629 [1:15:22<05:29, 13.99it/s]

 95%|█████████▌| 96027/100629 [1:15:22<04:57, 15.47it/s]

 95%|█████████▌| 96029/100629 [1:15:22<05:28, 14.01it/s]

 95%|█████████▌| 96031/100629 [1:15:22<05:38, 13.57it/s]

 95%|█████████▌| 96033/100629 [1:15:22<05:10, 14.79it/s]

 95%|█████████▌| 96035/100629 [1:15:23<04:55, 15.57it/s]

 95%|█████████▌| 96037/100629 [1:15:23<04:42, 16.25it/s]

 95%|█████████▌| 96040/100629 [1:15:23<04:24, 17.37it/s]

 95%|█████████▌| 96042/100629 [1:15:23<04:31, 16.87it/s]

 95%|█████████▌| 96045/100629 [1:15:23<04:10, 18.33it/s]

 95%|█████████▌| 96049/100629 [1:15:23<03:15, 23.39it/s]

 95%|█████████▌| 96052/100629 [1:15:23<03:25, 22.32it/s]

 95%|█████████▌| 96056/100629 [1:15:23<02:58, 25.59it/s]

 95%|█████████▌| 96060/100629 [1:15:24<02:43, 27.92it/s]

 95%|█████████▌| 96063/100629 [1:15:24<02:51, 26.62it/s]

 95%|█████████▌| 96066/100629 [1:15:24<02:58, 25.59it/s]

 95%|█████████▌| 96069/100629 [1:15:24<03:17, 23.07it/s]

 95%|█████████▌| 96072/100629 [1:15:24<03:42, 20.44it/s]

 95%|█████████▌| 96075/100629 [1:15:24<03:55, 19.31it/s]

 95%|█████████▌| 96080/100629 [1:15:24<03:02, 24.95it/s]

 95%|█████████▌| 96083/100629 [1:15:25<02:59, 25.39it/s]

 95%|█████████▌| 96086/100629 [1:15:25<03:05, 24.44it/s]

 95%|█████████▌| 96089/100629 [1:15:25<03:08, 24.10it/s]

 95%|█████████▌| 96092/100629 [1:15:25<03:05, 24.46it/s]

 95%|█████████▌| 96096/100629 [1:15:25<02:53, 26.14it/s]

 95%|█████████▌| 96099/100629 [1:15:25<02:58, 25.41it/s]

 96%|█████████▌| 96103/100629 [1:15:25<02:42, 27.88it/s]

 96%|█████████▌| 96106/100629 [1:15:26<03:07, 24.12it/s]

 96%|█████████▌| 96109/100629 [1:15:26<03:01, 24.96it/s]

 96%|█████████▌| 96112/100629 [1:15:26<03:01, 24.91it/s]

 96%|█████████▌| 96116/100629 [1:15:26<02:42, 27.75it/s]

 96%|█████████▌| 96119/100629 [1:15:26<02:48, 26.84it/s]

 96%|█████████▌| 96122/100629 [1:15:26<02:46, 27.14it/s]

 96%|█████████▌| 96125/100629 [1:15:26<03:25, 21.94it/s]

 96%|█████████▌| 96128/100629 [1:15:26<03:14, 23.11it/s]

 96%|█████████▌| 96131/100629 [1:15:27<03:19, 22.52it/s]

 96%|█████████▌| 96134/100629 [1:15:27<03:30, 21.33it/s]

 96%|█████████▌| 96137/100629 [1:15:27<03:42, 20.22it/s]

 96%|█████████▌| 96141/100629 [1:15:27<03:19, 22.54it/s]

 96%|█████████▌| 96144/100629 [1:15:27<03:09, 23.63it/s]

 96%|█████████▌| 96147/100629 [1:15:27<03:10, 23.55it/s]

 96%|█████████▌| 96150/100629 [1:15:27<03:14, 22.98it/s]

 96%|█████████▌| 96153/100629 [1:15:28<04:02, 18.45it/s]

 96%|█████████▌| 96156/100629 [1:15:28<03:37, 20.57it/s]

 96%|█████████▌| 96159/100629 [1:15:28<03:18, 22.52it/s]

 96%|█████████▌| 96162/100629 [1:15:28<03:40, 20.29it/s]

 96%|█████████▌| 96165/100629 [1:15:28<04:18, 17.25it/s]

 96%|█████████▌| 96168/100629 [1:15:28<03:58, 18.71it/s]

 96%|█████████▌| 96171/100629 [1:15:29<04:17, 17.31it/s]

 96%|█████████▌| 96175/100629 [1:15:29<03:41, 20.13it/s]

 96%|█████████▌| 96178/100629 [1:15:29<03:48, 19.48it/s]

 96%|█████████▌| 96182/100629 [1:15:29<03:54, 18.93it/s]

 96%|█████████▌| 96186/100629 [1:15:29<03:32, 20.90it/s]

 96%|█████████▌| 96189/100629 [1:15:29<03:51, 19.22it/s]

 96%|█████████▌| 96191/100629 [1:15:30<04:09, 17.77it/s]

 96%|█████████▌| 96194/100629 [1:15:30<03:42, 19.94it/s]

 96%|█████████▌| 96198/100629 [1:15:30<03:03, 24.15it/s]

 96%|█████████▌| 96201/100629 [1:15:30<03:22, 21.89it/s]

 96%|█████████▌| 96204/100629 [1:15:30<03:42, 19.85it/s]

 96%|█████████▌| 96207/100629 [1:15:30<03:21, 21.93it/s]

 96%|█████████▌| 96211/100629 [1:15:30<03:18, 22.25it/s]

 96%|█████████▌| 96214/100629 [1:15:31<04:05, 17.95it/s]

 96%|█████████▌| 96218/100629 [1:15:31<04:53, 15.05it/s]

 96%|█████████▌| 96221/100629 [1:15:31<04:13, 17.37it/s]

 96%|█████████▌| 96224/100629 [1:15:31<03:51, 18.99it/s]

 96%|█████████▌| 96228/100629 [1:15:31<03:26, 21.29it/s]

 96%|█████████▌| 96231/100629 [1:15:32<03:16, 22.34it/s]

 96%|█████████▌| 96234/100629 [1:15:32<03:46, 19.44it/s]

 96%|█████████▌| 96237/100629 [1:15:32<03:30, 20.82it/s]

 96%|█████████▌| 96240/100629 [1:15:32<03:22, 21.71it/s]

 96%|█████████▌| 96243/100629 [1:15:32<04:21, 16.79it/s]

 96%|█████████▌| 96246/100629 [1:15:32<04:19, 16.91it/s]

 96%|█████████▌| 96250/100629 [1:15:33<04:06, 17.76it/s]

 96%|█████████▌| 96255/100629 [1:15:33<03:33, 20.45it/s]

 96%|█████████▌| 96258/100629 [1:15:33<04:02, 18.00it/s]

 96%|█████████▌| 96261/100629 [1:15:33<03:56, 18.50it/s]

 96%|█████████▌| 96264/100629 [1:15:33<03:33, 20.49it/s]

 96%|█████████▌| 96267/100629 [1:15:33<03:33, 20.41it/s]

 96%|█████████▌| 96270/100629 [1:15:34<04:06, 17.65it/s]

 96%|█████████▌| 96272/100629 [1:15:34<04:12, 17.26it/s]

 96%|█████████▌| 96276/100629 [1:15:34<03:19, 21.85it/s]

 96%|█████████▌| 96280/100629 [1:15:34<03:09, 22.95it/s]

 96%|█████████▌| 96283/100629 [1:15:34<03:15, 22.28it/s]

 96%|█████████▌| 96286/100629 [1:15:34<03:22, 21.42it/s]

 96%|█████████▌| 96289/100629 [1:15:34<03:11, 22.68it/s]

 96%|█████████▌| 96292/100629 [1:15:35<03:50, 18.81it/s]

 96%|█████████▌| 96295/100629 [1:15:35<04:30, 16.01it/s]

 96%|█████████▌| 96297/100629 [1:15:35<04:30, 16.02it/s]

 96%|█████████▌| 96300/100629 [1:15:35<03:59, 18.04it/s]

 96%|█████████▌| 96306/100629 [1:15:35<02:54, 24.74it/s]

 96%|█████████▌| 96310/100629 [1:15:36<02:44, 26.30it/s]

 96%|█████████▌| 96313/100629 [1:15:36<02:51, 25.14it/s]

 96%|█████████▌| 96317/100629 [1:15:36<02:33, 28.03it/s]

 96%|█████████▌| 96321/100629 [1:15:36<02:49, 25.40it/s]

 96%|█████████▌| 96324/100629 [1:15:36<03:07, 22.90it/s]

 96%|█████████▌| 96327/100629 [1:15:36<03:10, 22.56it/s]

 96%|█████████▌| 96330/100629 [1:15:36<03:26, 20.84it/s]

 96%|█████████▌| 96333/100629 [1:15:37<03:21, 21.28it/s]

 96%|█████████▌| 96336/100629 [1:15:37<03:27, 20.65it/s]

 96%|█████████▌| 96339/100629 [1:15:37<03:31, 20.28it/s]

 96%|█████████▌| 96342/100629 [1:15:37<03:27, 20.65it/s]

 96%|█████████▌| 96345/100629 [1:15:37<03:39, 19.52it/s]

 96%|█████████▌| 96350/100629 [1:15:37<02:55, 24.36it/s]

 96%|█████████▌| 96353/100629 [1:15:37<03:16, 21.74it/s]

 96%|█████████▌| 96356/100629 [1:15:38<03:23, 21.04it/s]

 96%|█████████▌| 96359/100629 [1:15:38<03:13, 22.07it/s]

 96%|█████████▌| 96362/100629 [1:15:38<03:12, 22.19it/s]

 96%|█████████▌| 96365/100629 [1:15:38<03:28, 20.44it/s]

 96%|█████████▌| 96368/100629 [1:15:38<03:26, 20.59it/s]

 96%|█████████▌| 96371/100629 [1:15:38<03:40, 19.29it/s]

 96%|█████████▌| 96373/100629 [1:15:39<03:58, 17.81it/s]

 96%|█████████▌| 96375/100629 [1:15:39<04:13, 16.76it/s]

 96%|█████████▌| 96378/100629 [1:15:39<03:39, 19.38it/s]

 96%|█████████▌| 96381/100629 [1:15:39<04:01, 17.59it/s]

 96%|█████████▌| 96384/100629 [1:15:39<03:32, 20.01it/s]

 96%|█████████▌| 96387/100629 [1:15:39<03:42, 19.04it/s]

 96%|█████████▌| 96390/100629 [1:15:39<04:01, 17.56it/s]

 96%|█████████▌| 96394/100629 [1:15:40<03:25, 20.60it/s]

 96%|█████████▌| 96397/100629 [1:15:40<03:36, 19.57it/s]

 96%|█████████▌| 96400/100629 [1:15:40<03:44, 18.83it/s]

 96%|█████████▌| 96402/100629 [1:15:40<03:54, 17.99it/s]

 96%|█████████▌| 96406/100629 [1:15:40<03:17, 21.33it/s]

 96%|█████████▌| 96409/100629 [1:15:40<03:24, 20.68it/s]

 96%|█████████▌| 96412/100629 [1:15:40<03:18, 21.21it/s]

 96%|█████████▌| 96415/100629 [1:15:41<03:28, 20.17it/s]

 96%|█████████▌| 96418/100629 [1:15:41<03:41, 19.02it/s]

 96%|█████████▌| 96422/100629 [1:15:41<03:05, 22.73it/s]

 96%|█████████▌| 96425/100629 [1:15:41<02:54, 24.11it/s]

 96%|█████████▌| 96428/100629 [1:15:41<02:55, 23.92it/s]

 96%|█████████▌| 96431/100629 [1:15:41<02:49, 24.74it/s]

 96%|█████████▌| 96435/100629 [1:15:41<02:30, 27.95it/s]

 96%|█████████▌| 96439/100629 [1:15:42<02:39, 26.34it/s]

 96%|█████████▌| 96442/100629 [1:15:42<02:45, 25.33it/s]

 96%|█████████▌| 96445/100629 [1:15:42<03:07, 22.30it/s]

 96%|█████████▌| 96448/100629 [1:15:42<03:03, 22.82it/s]

 96%|█████████▌| 96451/100629 [1:15:42<02:50, 24.44it/s]

 96%|█████████▌| 96455/100629 [1:15:42<02:54, 23.98it/s]

 96%|█████████▌| 96458/100629 [1:15:42<02:56, 23.67it/s]

 96%|█████████▌| 96461/100629 [1:15:43<03:03, 22.75it/s]

 96%|█████████▌| 96464/100629 [1:15:43<03:35, 19.30it/s]

 96%|█████████▌| 96468/100629 [1:15:43<03:07, 22.22it/s]

 96%|█████████▌| 96471/100629 [1:15:43<03:49, 18.14it/s]

 96%|█████████▌| 96474/100629 [1:15:43<03:35, 19.29it/s]

 96%|█████████▌| 96477/100629 [1:15:44<04:22, 15.79it/s]

 96%|█████████▌| 96480/100629 [1:15:44<03:46, 18.29it/s]

 96%|█████████▌| 96483/100629 [1:15:44<03:32, 19.51it/s]

 96%|█████████▌| 96486/100629 [1:15:44<03:25, 20.12it/s]

 96%|█████████▌| 96490/100629 [1:15:44<03:11, 21.62it/s]

 96%|█████████▌| 96493/100629 [1:15:44<03:12, 21.49it/s]

 96%|█████████▌| 96496/100629 [1:15:44<03:56, 17.45it/s]

 96%|█████████▌| 96499/100629 [1:15:45<03:42, 18.55it/s]

 96%|█████████▌| 96502/100629 [1:15:45<03:36, 19.11it/s]

 96%|█████████▌| 96505/100629 [1:15:45<03:31, 19.51it/s]

 96%|█████████▌| 96508/100629 [1:15:45<03:24, 20.18it/s]

 96%|█████████▌| 96512/100629 [1:15:45<02:56, 23.29it/s]

 96%|█████████▌| 96515/100629 [1:15:45<03:09, 21.77it/s]

 96%|█████████▌| 96519/100629 [1:15:45<03:02, 22.55it/s]

 96%|█████████▌| 96522/100629 [1:15:46<03:01, 22.68it/s]

 96%|█████████▌| 96525/100629 [1:15:46<03:21, 20.39it/s]

 96%|█████████▌| 96528/100629 [1:15:46<03:43, 18.35it/s]

 96%|█████████▌| 96531/100629 [1:15:46<03:20, 20.40it/s]

 96%|█████████▌| 96534/100629 [1:15:46<03:18, 20.64it/s]

 96%|█████████▌| 96537/100629 [1:15:46<03:14, 21.05it/s]

 96%|█████████▌| 96540/100629 [1:15:47<03:36, 18.89it/s]

 96%|█████████▌| 96542/100629 [1:15:47<04:13, 16.09it/s]

 96%|█████████▌| 96544/100629 [1:15:47<04:22, 15.55it/s]

 96%|█████████▌| 96546/100629 [1:15:47<04:29, 15.17it/s]

 96%|█████████▌| 96549/100629 [1:15:47<03:50, 17.73it/s]

 96%|█████████▌| 96552/100629 [1:15:47<03:40, 18.48it/s]

 96%|█████████▌| 96554/100629 [1:15:47<03:47, 17.94it/s]

 96%|█████████▌| 96557/100629 [1:15:48<04:12, 16.12it/s]

 96%|█████████▌| 96559/100629 [1:15:48<04:18, 15.77it/s]

 96%|█████████▌| 96561/100629 [1:15:48<04:08, 16.38it/s]

 96%|█████████▌| 96564/100629 [1:15:48<04:19, 15.66it/s]

 96%|█████████▌| 96567/100629 [1:15:48<03:39, 18.52it/s]

 96%|█████████▌| 96571/100629 [1:15:48<02:53, 23.38it/s]

 96%|█████████▌| 96575/100629 [1:15:48<02:32, 26.62it/s]

 96%|█████████▌| 96580/100629 [1:15:49<02:09, 31.27it/s]

 96%|█████████▌| 96584/100629 [1:15:49<02:38, 25.55it/s]

 96%|█████████▌| 96589/100629 [1:15:49<02:19, 28.94it/s]

 96%|█████████▌| 96593/100629 [1:15:49<02:13, 30.16it/s]

 96%|█████████▌| 96598/100629 [1:15:49<01:57, 34.37it/s]

 96%|█████████▌| 96602/100629 [1:15:49<02:16, 29.50it/s]

 96%|█████████▌| 96606/100629 [1:15:49<02:15, 29.80it/s]

 96%|█████████▌| 96610/100629 [1:15:50<02:22, 28.14it/s]

 96%|█████████▌| 96613/100629 [1:15:50<02:40, 24.99it/s]

 96%|█████████▌| 96616/100629 [1:15:50<03:02, 22.04it/s]

 96%|█████████▌| 96619/100629 [1:15:50<03:16, 20.41it/s]

 96%|█████████▌| 96623/100629 [1:15:50<02:46, 24.01it/s]

 96%|█████████▌| 96626/100629 [1:15:50<03:25, 19.48it/s]

 96%|█████████▌| 96629/100629 [1:15:51<03:57, 16.83it/s]

 96%|█████████▌| 96631/100629 [1:15:51<04:07, 16.14it/s]

 96%|█████████▌| 96633/100629 [1:15:51<04:04, 16.38it/s]

 96%|█████████▌| 96636/100629 [1:15:51<04:19, 15.40it/s]

 96%|█████████▌| 96638/100629 [1:15:51<04:28, 14.87it/s]

 96%|█████████▌| 96640/100629 [1:15:51<04:24, 15.10it/s]

 96%|█████████▌| 96643/100629 [1:15:52<03:52, 17.13it/s]

 96%|█████████▌| 96645/100629 [1:15:52<03:47, 17.52it/s]

 96%|█████████▌| 96649/100629 [1:15:52<02:54, 22.82it/s]

 96%|█████████▌| 96652/100629 [1:15:52<02:46, 23.89it/s]

 96%|█████████▌| 96655/100629 [1:15:52<03:09, 20.93it/s]

 96%|█████████▌| 96658/100629 [1:15:52<03:24, 19.37it/s]

 96%|█████████▌| 96661/100629 [1:15:52<03:38, 18.14it/s]

 96%|█████████▌| 96664/100629 [1:15:53<03:37, 18.27it/s]

 96%|█████████▌| 96667/100629 [1:15:53<03:26, 19.14it/s]

 96%|█████████▌| 96670/100629 [1:15:53<03:13, 20.50it/s]

 96%|█████████▌| 96673/100629 [1:15:53<03:05, 21.36it/s]

 96%|█████████▌| 96676/100629 [1:15:53<02:53, 22.74it/s]

 96%|█████████▌| 96679/100629 [1:15:53<03:04, 21.42it/s]

 96%|█████████▌| 96682/100629 [1:15:53<03:23, 19.40it/s]

 96%|█████████▌| 96685/100629 [1:15:54<03:14, 20.29it/s]

 96%|█████████▌| 96689/100629 [1:15:54<02:59, 21.93it/s]

 96%|█████████▌| 96693/100629 [1:15:54<02:40, 24.57it/s]

 96%|█████████▌| 96696/100629 [1:15:54<02:38, 24.83it/s]

 96%|█████████▌| 96699/100629 [1:15:54<02:30, 26.06it/s]

 96%|█████████▌| 96702/100629 [1:15:54<02:40, 24.45it/s]

 96%|█████████▌| 96705/100629 [1:15:54<02:32, 25.75it/s]

 96%|█████████▌| 96708/100629 [1:15:55<02:48, 23.28it/s]

 96%|█████████▌| 96711/100629 [1:15:55<03:04, 21.18it/s]

 96%|█████████▌| 96715/100629 [1:15:55<02:40, 24.43it/s]

 96%|█████████▌| 96718/100629 [1:15:55<02:49, 23.03it/s]

 96%|█████████▌| 96723/100629 [1:15:55<02:22, 27.34it/s]

 96%|█████████▌| 96727/100629 [1:15:55<02:37, 24.74it/s]

 96%|█████████▌| 96730/100629 [1:15:55<02:48, 23.14it/s]

 96%|█████████▌| 96733/100629 [1:15:56<02:53, 22.49it/s]

 96%|█████████▌| 96736/100629 [1:15:56<02:43, 23.78it/s]

 96%|█████████▌| 96739/100629 [1:15:56<03:02, 21.27it/s]

 96%|█████████▌| 96742/100629 [1:15:56<02:57, 21.91it/s]

 96%|█████████▌| 96745/100629 [1:15:56<02:44, 23.60it/s]

 96%|█████████▌| 96748/100629 [1:15:56<03:34, 18.13it/s]

 96%|█████████▌| 96751/100629 [1:15:57<03:54, 16.55it/s]

 96%|█████████▌| 96754/100629 [1:15:57<03:37, 17.86it/s]

 96%|█████████▌| 96756/100629 [1:15:57<03:36, 17.87it/s]

 96%|█████████▌| 96758/100629 [1:15:57<03:33, 18.11it/s]

 96%|█████████▌| 96761/100629 [1:15:57<03:12, 20.11it/s]

 96%|█████████▌| 96764/100629 [1:15:57<03:30, 18.32it/s]

 96%|█████████▌| 96767/100629 [1:15:57<03:20, 19.23it/s]

 96%|█████████▌| 96770/100629 [1:15:58<03:36, 17.83it/s]

 96%|█████████▌| 96773/100629 [1:15:58<03:19, 19.34it/s]

 96%|█████████▌| 96776/100629 [1:15:58<03:09, 20.32it/s]

 96%|█████████▌| 96781/100629 [1:15:58<02:28, 25.91it/s]

 96%|█████████▌| 96784/100629 [1:15:58<02:30, 25.52it/s]

 96%|█████████▌| 96787/100629 [1:15:58<02:59, 21.36it/s]

 96%|█████████▌| 96790/100629 [1:15:58<03:10, 20.11it/s]

 96%|█████████▌| 96793/100629 [1:15:59<03:05, 20.73it/s]

 96%|█████████▌| 96796/100629 [1:15:59<02:55, 21.89it/s]

 96%|█████████▌| 96799/100629 [1:15:59<03:24, 18.71it/s]

 96%|█████████▌| 96802/100629 [1:15:59<03:51, 16.52it/s]

 96%|█████████▌| 96805/100629 [1:15:59<03:30, 18.15it/s]

 96%|█████████▌| 96807/100629 [1:16:00<04:14, 15.01it/s]

 96%|█████████▌| 96809/100629 [1:16:00<03:59, 15.96it/s]

 96%|█████████▌| 96812/100629 [1:16:00<03:57, 16.10it/s]

 96%|█████████▌| 96814/100629 [1:16:00<04:14, 14.99it/s]

 96%|█████████▌| 96818/100629 [1:16:00<03:11, 19.87it/s]

 96%|█████████▌| 96822/100629 [1:16:00<02:52, 22.12it/s]

 96%|█████████▌| 96825/100629 [1:16:00<02:49, 22.48it/s]

 96%|█████████▌| 96828/100629 [1:16:00<02:37, 24.15it/s]

 96%|█████████▌| 96832/100629 [1:16:01<02:20, 27.04it/s]

 96%|█████████▌| 96836/100629 [1:16:01<02:19, 27.12it/s]

 96%|█████████▌| 96839/100629 [1:16:01<02:29, 25.35it/s]

 96%|█████████▌| 96842/100629 [1:16:01<02:36, 24.23it/s]

 96%|█████████▌| 96847/100629 [1:16:01<02:09, 29.21it/s]

 96%|█████████▌| 96851/100629 [1:16:01<02:53, 21.82it/s]

 96%|█████████▌| 96854/100629 [1:16:02<03:15, 19.35it/s]

 96%|█████████▋| 96857/100629 [1:16:02<03:13, 19.50it/s]

 96%|█████████▋| 96861/100629 [1:16:02<02:50, 22.06it/s]

 96%|█████████▋| 96864/100629 [1:16:02<02:56, 21.28it/s]

 96%|█████████▋| 96867/100629 [1:16:02<03:05, 20.32it/s]

 96%|█████████▋| 96870/100629 [1:16:02<03:09, 19.82it/s]

 96%|█████████▋| 96873/100629 [1:16:02<02:56, 21.30it/s]

 96%|█████████▋| 96876/100629 [1:16:03<03:09, 19.79it/s]

 96%|█████████▋| 96879/100629 [1:16:03<02:58, 21.05it/s]

 96%|█████████▋| 96882/100629 [1:16:03<03:51, 16.18it/s]

 96%|█████████▋| 96884/100629 [1:16:03<03:45, 16.64it/s]

 96%|█████████▋| 96887/100629 [1:16:03<03:19, 18.79it/s]

 96%|█████████▋| 96890/100629 [1:16:03<03:00, 20.70it/s]

 96%|█████████▋| 96893/100629 [1:16:04<03:05, 20.09it/s]

 96%|█████████▋| 96896/100629 [1:16:04<03:13, 19.25it/s]

 96%|█████████▋| 96899/100629 [1:16:04<03:22, 18.43it/s]

 96%|█████████▋| 96901/100629 [1:16:04<03:20, 18.62it/s]

 96%|█████████▋| 96906/100629 [1:16:04<02:26, 25.41it/s]

 96%|█████████▋| 96909/100629 [1:16:04<02:23, 25.89it/s]

 96%|█████████▋| 96912/100629 [1:16:04<02:30, 24.66it/s]

 96%|█████████▋| 96915/100629 [1:16:04<02:29, 24.90it/s]

 96%|█████████▋| 96918/100629 [1:16:05<02:49, 21.86it/s]

 96%|█████████▋| 96921/100629 [1:16:05<02:42, 22.78it/s]

 96%|█████████▋| 96924/100629 [1:16:05<02:42, 22.86it/s]

 96%|█████████▋| 96927/100629 [1:16:05<02:52, 21.42it/s]

 96%|█████████▋| 96930/100629 [1:16:05<02:42, 22.75it/s]

 96%|█████████▋| 96933/100629 [1:16:05<02:43, 22.56it/s]

 96%|█████████▋| 96936/100629 [1:16:05<02:40, 23.01it/s]

 96%|█████████▋| 96939/100629 [1:16:06<02:43, 22.58it/s]

 96%|█████████▋| 96942/100629 [1:16:06<02:41, 22.80it/s]

 96%|█████████▋| 96945/100629 [1:16:06<02:32, 24.14it/s]

 96%|█████████▋| 96948/100629 [1:16:06<02:35, 23.71it/s]

 96%|█████████▋| 96951/100629 [1:16:06<02:30, 24.44it/s]

 96%|█████████▋| 96954/100629 [1:16:06<02:50, 21.57it/s]

 96%|█████████▋| 96957/100629 [1:16:06<03:05, 19.84it/s]

 96%|█████████▋| 96961/100629 [1:16:07<02:46, 22.01it/s]

 96%|█████████▋| 96964/100629 [1:16:07<02:56, 20.71it/s]

 96%|█████████▋| 96968/100629 [1:16:07<02:31, 24.12it/s]

 96%|█████████▋| 96971/100629 [1:16:07<02:23, 25.47it/s]

 96%|█████████▋| 96975/100629 [1:16:07<02:13, 27.47it/s]

 96%|█████████▋| 96978/100629 [1:16:07<02:19, 26.16it/s]

 96%|█████████▋| 96981/100629 [1:16:07<02:36, 23.26it/s]

 96%|█████████▋| 96984/100629 [1:16:08<02:47, 21.79it/s]

 96%|█████████▋| 96987/100629 [1:16:08<02:35, 23.36it/s]

 96%|█████████▋| 96990/100629 [1:16:08<02:35, 23.37it/s]

 96%|█████████▋| 96994/100629 [1:16:08<02:15, 26.79it/s]

 96%|█████████▋| 96997/100629 [1:16:08<02:52, 21.03it/s]

 96%|█████████▋| 97001/100629 [1:16:08<02:35, 23.32it/s]

 96%|█████████▋| 97004/100629 [1:16:08<02:52, 20.97it/s]

 96%|█████████▋| 97007/100629 [1:16:09<02:53, 20.85it/s]

 96%|█████████▋| 97010/100629 [1:16:09<03:16, 18.40it/s]

 96%|█████████▋| 97012/100629 [1:16:09<03:22, 17.87it/s]

 96%|█████████▋| 97015/100629 [1:16:09<03:33, 16.95it/s]

 96%|█████████▋| 97019/100629 [1:16:09<02:56, 20.46it/s]

 96%|█████████▋| 97023/100629 [1:16:09<02:38, 22.80it/s]

 96%|█████████▋| 97026/100629 [1:16:09<02:40, 22.43it/s]

 96%|█████████▋| 97029/100629 [1:16:10<02:41, 22.26it/s]

 96%|█████████▋| 97032/100629 [1:16:10<02:39, 22.62it/s]

 96%|█████████▋| 97035/100629 [1:16:10<02:32, 23.54it/s]

 96%|█████████▋| 97038/100629 [1:16:10<02:55, 20.43it/s]

 96%|█████████▋| 97041/100629 [1:16:10<02:49, 21.11it/s]

 96%|█████████▋| 97045/100629 [1:16:10<02:24, 24.79it/s]

 96%|█████████▋| 97048/100629 [1:16:10<02:45, 21.65it/s]

 96%|█████████▋| 97053/100629 [1:16:11<02:11, 27.19it/s]

 96%|█████████▋| 97057/100629 [1:16:11<02:10, 27.38it/s]

 96%|█████████▋| 97060/100629 [1:16:11<03:20, 17.84it/s]

 96%|█████████▋| 97063/100629 [1:16:11<03:17, 18.02it/s]

 96%|█████████▋| 97066/100629 [1:16:11<03:15, 18.20it/s]

 96%|█████████▋| 97069/100629 [1:16:12<03:01, 19.57it/s]

 96%|█████████▋| 97072/100629 [1:16:12<03:32, 16.70it/s]

 96%|█████████▋| 97076/100629 [1:16:12<02:55, 20.25it/s]

 96%|█████████▋| 97079/100629 [1:16:12<03:11, 18.50it/s]

 96%|█████████▋| 97082/100629 [1:16:12<03:09, 18.74it/s]

 96%|█████████▋| 97085/100629 [1:16:12<03:17, 17.92it/s]

 96%|█████████▋| 97087/100629 [1:16:13<03:26, 17.12it/s]

 96%|█████████▋| 97089/100629 [1:16:13<03:25, 17.21it/s]

 96%|█████████▋| 97092/100629 [1:16:13<03:43, 15.80it/s]

 96%|█████████▋| 97094/100629 [1:16:13<03:48, 15.46it/s]

 96%|█████████▋| 97098/100629 [1:16:13<02:58, 19.83it/s]

 96%|█████████▋| 97102/100629 [1:16:13<02:31, 23.35it/s]

 96%|█████████▋| 97105/100629 [1:16:14<03:02, 19.27it/s]

 97%|█████████▋| 97108/100629 [1:16:14<03:05, 19.00it/s]

 97%|█████████▋| 97111/100629 [1:16:14<03:07, 18.75it/s]

 97%|█████████▋| 97114/100629 [1:16:14<02:51, 20.51it/s]

 97%|█████████▋| 97117/100629 [1:16:14<02:46, 21.09it/s]

 97%|█████████▋| 97120/100629 [1:16:14<02:49, 20.74it/s]

 97%|█████████▋| 97123/100629 [1:16:14<02:36, 22.38it/s]

 97%|█████████▋| 97126/100629 [1:16:14<02:40, 21.88it/s]

 97%|█████████▋| 97129/100629 [1:16:15<02:53, 20.19it/s]

 97%|█████████▋| 97132/100629 [1:16:15<03:00, 19.33it/s]

 97%|█████████▋| 97134/100629 [1:16:15<03:08, 18.54it/s]

 97%|█████████▋| 97138/100629 [1:16:15<02:37, 22.22it/s]

 97%|█████████▋| 97142/100629 [1:16:15<02:16, 25.63it/s]

 97%|█████████▋| 97145/100629 [1:16:15<02:31, 22.93it/s]

 97%|█████████▋| 97149/100629 [1:16:15<02:11, 26.45it/s]

 97%|█████████▋| 97152/100629 [1:16:16<02:16, 25.55it/s]

 97%|█████████▋| 97157/100629 [1:16:16<01:53, 30.53it/s]

 97%|█████████▋| 97161/100629 [1:16:16<02:14, 25.74it/s]

 97%|█████████▋| 97164/100629 [1:16:16<02:21, 24.52it/s]

 97%|█████████▋| 97167/100629 [1:16:16<02:22, 24.26it/s]

 97%|█████████▋| 97170/100629 [1:16:16<02:52, 20.00it/s]

 97%|█████████▋| 97175/100629 [1:16:17<02:33, 22.51it/s]

 97%|█████████▋| 97179/100629 [1:16:17<02:21, 24.47it/s]

 97%|█████████▋| 97182/100629 [1:16:17<02:26, 23.60it/s]

 97%|█████████▋| 97185/100629 [1:16:17<02:23, 24.02it/s]

 97%|█████████▋| 97188/100629 [1:16:17<02:21, 24.34it/s]

 97%|█████████▋| 97191/100629 [1:16:17<02:38, 21.73it/s]

 97%|█████████▋| 97196/100629 [1:16:17<02:13, 25.64it/s]

 97%|█████████▋| 97199/100629 [1:16:18<02:10, 26.19it/s]

 97%|█████████▋| 97202/100629 [1:16:18<02:40, 21.35it/s]

 97%|█████████▋| 97205/100629 [1:16:18<02:37, 21.71it/s]

 97%|█████████▋| 97208/100629 [1:16:18<02:41, 21.22it/s]

 97%|█████████▋| 97211/100629 [1:16:18<02:37, 21.74it/s]

 97%|█████████▋| 97215/100629 [1:16:18<02:17, 24.84it/s]

 97%|█████████▋| 97218/100629 [1:16:19<02:56, 19.29it/s]

 97%|█████████▋| 97221/100629 [1:16:19<03:02, 18.63it/s]

 97%|█████████▋| 97224/100629 [1:16:19<02:47, 20.39it/s]

 97%|█████████▋| 97227/100629 [1:16:19<02:38, 21.41it/s]

 97%|█████████▋| 97230/100629 [1:16:19<02:51, 19.76it/s]

 97%|█████████▋| 97234/100629 [1:16:19<02:28, 22.87it/s]

 97%|█████████▋| 97237/100629 [1:16:19<02:37, 21.60it/s]

 97%|█████████▋| 97240/100629 [1:16:20<02:39, 21.26it/s]

 97%|█████████▋| 97246/100629 [1:16:20<02:03, 27.35it/s]

 97%|█████████▋| 97249/100629 [1:16:20<02:24, 23.45it/s]

 97%|█████████▋| 97252/100629 [1:16:20<02:20, 24.04it/s]

 97%|█████████▋| 97255/100629 [1:16:20<02:44, 20.51it/s]

 97%|█████████▋| 97258/100629 [1:16:20<02:54, 19.32it/s]

 97%|█████████▋| 97261/100629 [1:16:20<02:51, 19.68it/s]

 97%|█████████▋| 97264/100629 [1:16:21<02:42, 20.64it/s]

 97%|█████████▋| 97268/100629 [1:16:21<02:16, 24.64it/s]

 97%|█████████▋| 97271/100629 [1:16:21<02:39, 21.06it/s]

 97%|█████████▋| 97274/100629 [1:16:21<02:56, 18.99it/s]

 97%|█████████▋| 97277/100629 [1:16:21<02:59, 18.71it/s]

 97%|█████████▋| 97279/100629 [1:16:21<03:22, 16.57it/s]

 97%|█████████▋| 97281/100629 [1:16:22<03:35, 15.51it/s]

 97%|█████████▋| 97284/100629 [1:16:22<03:25, 16.28it/s]

 97%|█████████▋| 97288/100629 [1:16:22<02:49, 19.76it/s]

 97%|█████████▋| 97291/100629 [1:16:22<02:47, 19.95it/s]

 97%|█████████▋| 97294/100629 [1:16:22<02:57, 18.79it/s]

 97%|█████████▋| 97296/100629 [1:16:22<03:00, 18.47it/s]

 97%|█████████▋| 97300/100629 [1:16:22<02:28, 22.35it/s]

 97%|█████████▋| 97303/100629 [1:16:23<03:09, 17.52it/s]

 97%|█████████▋| 97306/100629 [1:16:23<02:56, 18.87it/s]

 97%|█████████▋| 97311/100629 [1:16:23<02:11, 25.28it/s]

 97%|█████████▋| 97314/100629 [1:16:23<02:27, 22.46it/s]

 97%|█████████▋| 97317/100629 [1:16:23<02:23, 23.10it/s]

 97%|█████████▋| 97321/100629 [1:16:23<02:05, 26.39it/s]

 97%|█████████▋| 97326/100629 [1:16:24<01:54, 28.92it/s]

 97%|█████████▋| 97330/100629 [1:16:24<01:48, 30.50it/s]

 97%|█████████▋| 97334/100629 [1:16:24<02:05, 26.16it/s]

 97%|█████████▋| 97337/100629 [1:16:24<02:21, 23.33it/s]

 97%|█████████▋| 97340/100629 [1:16:24<02:19, 23.61it/s]

 97%|█████████▋| 97343/100629 [1:16:24<02:32, 21.51it/s]

 97%|█████████▋| 97347/100629 [1:16:24<02:17, 23.91it/s]

 97%|█████████▋| 97350/100629 [1:16:25<02:43, 20.11it/s]

 97%|█████████▋| 97353/100629 [1:16:25<02:44, 19.96it/s]

 97%|█████████▋| 97356/100629 [1:16:25<03:53, 14.00it/s]

 97%|█████████▋| 97360/100629 [1:16:25<03:02, 17.89it/s]

 97%|█████████▋| 97363/100629 [1:16:25<02:49, 19.27it/s]

 97%|█████████▋| 97367/100629 [1:16:26<02:36, 20.78it/s]

 97%|█████████▋| 97370/100629 [1:16:26<02:41, 20.17it/s]

 97%|█████████▋| 97373/100629 [1:16:26<02:34, 21.14it/s]

 97%|█████████▋| 97376/100629 [1:16:26<02:28, 21.84it/s]

 97%|█████████▋| 97381/100629 [1:16:26<02:09, 25.02it/s]

 97%|█████████▋| 97384/100629 [1:16:26<02:07, 25.48it/s]

 97%|█████████▋| 97387/100629 [1:16:26<02:09, 25.11it/s]

 97%|█████████▋| 97390/100629 [1:16:27<02:43, 19.83it/s]

 97%|█████████▋| 97393/100629 [1:16:27<02:28, 21.75it/s]

 97%|█████████▋| 97397/100629 [1:16:27<02:12, 24.38it/s]

 97%|█████████▋| 97400/100629 [1:16:27<02:26, 22.03it/s]

 97%|█████████▋| 97403/100629 [1:16:27<02:30, 21.45it/s]

 97%|█████████▋| 97406/100629 [1:16:27<02:26, 21.98it/s]

 97%|█████████▋| 97409/100629 [1:16:28<02:54, 18.44it/s]

 97%|█████████▋| 97411/100629 [1:16:28<02:52, 18.66it/s]

 97%|█████████▋| 97414/100629 [1:16:28<02:41, 19.89it/s]

 97%|█████████▋| 97417/100629 [1:16:28<02:31, 21.14it/s]

 97%|█████████▋| 97420/100629 [1:16:28<03:08, 16.99it/s]

 97%|█████████▋| 97424/100629 [1:16:28<02:29, 21.43it/s]

 97%|█████████▋| 97427/100629 [1:16:28<02:40, 19.99it/s]

 97%|█████████▋| 97432/100629 [1:16:29<02:03, 25.86it/s]

 97%|█████████▋| 97435/100629 [1:16:29<02:01, 26.22it/s]

 97%|█████████▋| 97438/100629 [1:16:29<02:27, 21.59it/s]

 97%|█████████▋| 97441/100629 [1:16:29<02:48, 18.89it/s]

 97%|█████████▋| 97444/100629 [1:16:29<03:07, 16.98it/s]

 97%|█████████▋| 97446/100629 [1:16:29<03:03, 17.34it/s]

 97%|█████████▋| 97448/100629 [1:16:30<03:13, 16.45it/s]

 97%|█████████▋| 97451/100629 [1:16:30<02:44, 19.32it/s]

 97%|█████████▋| 97455/100629 [1:16:30<02:34, 20.59it/s]

 97%|█████████▋| 97458/100629 [1:16:30<02:23, 22.08it/s]

 97%|█████████▋| 97461/100629 [1:16:30<02:13, 23.66it/s]

 97%|█████████▋| 97464/100629 [1:16:30<02:12, 23.93it/s]

 97%|█████████▋| 97467/100629 [1:16:30<02:22, 22.17it/s]

 97%|█████████▋| 97470/100629 [1:16:30<02:24, 21.91it/s]

 97%|█████████▋| 97474/100629 [1:16:31<02:08, 24.50it/s]

 97%|█████████▋| 97477/100629 [1:16:31<02:15, 23.23it/s]

 97%|█████████▋| 97480/100629 [1:16:31<02:24, 21.83it/s]

 97%|█████████▋| 97483/100629 [1:16:31<02:37, 20.01it/s]

 97%|█████████▋| 97486/100629 [1:16:31<02:35, 20.22it/s]

 97%|█████████▋| 97490/100629 [1:16:31<02:20, 22.38it/s]

 97%|█████████▋| 97493/100629 [1:16:31<02:14, 23.35it/s]

 97%|█████████▋| 97496/100629 [1:16:32<02:26, 21.39it/s]

 97%|█████████▋| 97500/100629 [1:16:32<02:22, 21.96it/s]

 97%|█████████▋| 97503/100629 [1:16:32<02:31, 20.59it/s]

 97%|█████████▋| 97506/100629 [1:16:32<02:40, 19.50it/s]

 97%|█████████▋| 97508/100629 [1:16:32<03:38, 14.31it/s]

 97%|█████████▋| 97511/100629 [1:16:33<03:20, 15.57it/s]

 97%|█████████▋| 97514/100629 [1:16:33<03:02, 17.05it/s]

 97%|█████████▋| 97516/100629 [1:16:33<03:06, 16.68it/s]

 97%|█████████▋| 97520/100629 [1:16:33<02:31, 20.52it/s]

 97%|█████████▋| 97523/100629 [1:16:33<02:25, 21.32it/s]

 97%|█████████▋| 97527/100629 [1:16:33<02:01, 25.56it/s]

 97%|█████████▋| 97530/100629 [1:16:33<02:10, 23.82it/s]

 97%|█████████▋| 97533/100629 [1:16:34<02:26, 21.16it/s]

 97%|█████████▋| 97538/100629 [1:16:34<02:02, 25.26it/s]

 97%|█████████▋| 97541/100629 [1:16:34<02:04, 24.80it/s]

 97%|█████████▋| 97545/100629 [1:16:34<01:58, 26.08it/s]

 97%|█████████▋| 97550/100629 [1:16:34<01:51, 27.61it/s]

 97%|█████████▋| 97554/100629 [1:16:34<01:45, 29.05it/s]

 97%|█████████▋| 97558/100629 [1:16:34<01:42, 29.89it/s]

 97%|█████████▋| 97562/100629 [1:16:35<01:49, 27.89it/s]

 97%|█████████▋| 97566/100629 [1:16:35<01:50, 27.61it/s]

 97%|█████████▋| 97569/100629 [1:16:35<02:10, 23.40it/s]

 97%|█████████▋| 97573/100629 [1:16:35<02:11, 23.25it/s]

 97%|█████████▋| 97576/100629 [1:16:35<02:16, 22.40it/s]

 97%|█████████▋| 97580/100629 [1:16:35<02:05, 24.29it/s]

 97%|█████████▋| 97583/100629 [1:16:36<02:57, 17.12it/s]

 97%|█████████▋| 97586/100629 [1:16:36<02:46, 18.26it/s]

 97%|█████████▋| 97589/100629 [1:16:36<02:36, 19.45it/s]

 97%|█████████▋| 97592/100629 [1:16:36<02:25, 20.93it/s]

 97%|█████████▋| 97595/100629 [1:16:36<02:29, 20.24it/s]

 97%|█████████▋| 97599/100629 [1:16:36<02:15, 22.37it/s]

 97%|█████████▋| 97602/100629 [1:16:36<02:15, 22.38it/s]

 97%|█████████▋| 97605/100629 [1:16:37<02:26, 20.61it/s]

 97%|█████████▋| 97608/100629 [1:16:37<02:18, 21.77it/s]

 97%|█████████▋| 97611/100629 [1:16:37<02:43, 18.46it/s]

 97%|█████████▋| 97613/100629 [1:16:37<02:43, 18.48it/s]

 97%|█████████▋| 97616/100629 [1:16:37<02:26, 20.59it/s]

 97%|█████████▋| 97619/100629 [1:16:37<02:20, 21.36it/s]

 97%|█████████▋| 97622/100629 [1:16:37<02:27, 20.39it/s]

 97%|█████████▋| 97625/100629 [1:16:38<02:17, 21.83it/s]

 97%|█████████▋| 97628/100629 [1:16:38<02:06, 23.64it/s]

 97%|█████████▋| 97631/100629 [1:16:38<02:08, 23.33it/s]

 97%|█████████▋| 97634/100629 [1:16:38<02:23, 20.84it/s]

 97%|█████████▋| 97637/100629 [1:16:38<02:18, 21.58it/s]

 97%|█████████▋| 97640/100629 [1:16:38<02:25, 20.55it/s]

 97%|█████████▋| 97643/100629 [1:16:38<02:17, 21.75it/s]

 97%|█████████▋| 97646/100629 [1:16:39<02:16, 21.89it/s]

 97%|█████████▋| 97649/100629 [1:16:39<02:06, 23.62it/s]

 97%|█████████▋| 97652/100629 [1:16:39<02:09, 23.03it/s]

 97%|█████████▋| 97655/100629 [1:16:39<02:21, 20.99it/s]

 97%|█████████▋| 97658/100629 [1:16:39<02:15, 21.92it/s]

 97%|█████████▋| 97661/100629 [1:16:39<02:18, 21.42it/s]

 97%|█████████▋| 97664/100629 [1:16:39<02:28, 19.91it/s]

 97%|█████████▋| 97667/100629 [1:16:40<02:19, 21.21it/s]

 97%|█████████▋| 97670/100629 [1:16:40<02:10, 22.71it/s]

 97%|█████████▋| 97674/100629 [1:16:40<01:56, 25.39it/s]

 97%|█████████▋| 97677/100629 [1:16:40<02:01, 24.32it/s]

 97%|█████████▋| 97680/100629 [1:16:40<01:58, 24.86it/s]

 97%|█████████▋| 97683/100629 [1:16:40<01:52, 26.08it/s]

 97%|█████████▋| 97686/100629 [1:16:40<01:55, 25.42it/s]

 97%|█████████▋| 97689/100629 [1:16:40<02:12, 22.25it/s]

 97%|█████████▋| 97692/100629 [1:16:41<02:25, 20.24it/s]

 97%|█████████▋| 97695/100629 [1:16:41<02:17, 21.41it/s]

 97%|█████████▋| 97698/100629 [1:16:41<02:06, 23.14it/s]

 97%|█████████▋| 97702/100629 [1:16:41<01:54, 25.67it/s]

 97%|█████████▋| 97705/100629 [1:16:41<02:03, 23.71it/s]

 97%|█████████▋| 97708/100629 [1:16:41<02:14, 21.67it/s]

 97%|█████████▋| 97712/100629 [1:16:41<02:02, 23.79it/s]

 97%|█████████▋| 97715/100629 [1:16:42<02:22, 20.43it/s]

 97%|█████████▋| 97718/100629 [1:16:42<02:29, 19.53it/s]

 97%|█████████▋| 97721/100629 [1:16:42<02:27, 19.77it/s]

 97%|█████████▋| 97724/100629 [1:16:42<02:21, 20.49it/s]

 97%|█████████▋| 97728/100629 [1:16:42<02:07, 22.81it/s]

 97%|█████████▋| 97731/100629 [1:16:42<02:12, 21.94it/s]

 97%|█████████▋| 97734/100629 [1:16:42<02:04, 23.23it/s]

 97%|█████████▋| 97737/100629 [1:16:43<02:05, 23.08it/s]

 97%|█████████▋| 97740/100629 [1:16:43<02:16, 21.15it/s]

 97%|█████████▋| 97743/100629 [1:16:43<02:06, 22.81it/s]

 97%|█████████▋| 97747/100629 [1:16:43<02:07, 22.58it/s]

 97%|█████████▋| 97751/100629 [1:16:43<01:57, 24.58it/s]

 97%|█████████▋| 97754/100629 [1:16:43<01:54, 25.01it/s]

 97%|█████████▋| 97757/100629 [1:16:43<02:10, 21.99it/s]

 97%|█████████▋| 97760/100629 [1:16:44<02:12, 21.68it/s]

 97%|█████████▋| 97763/100629 [1:16:44<02:27, 19.49it/s]

 97%|█████████▋| 97766/100629 [1:16:44<02:44, 17.41it/s]

 97%|█████████▋| 97771/100629 [1:16:44<02:04, 22.98it/s]

 97%|█████████▋| 97776/100629 [1:16:44<01:42, 27.74it/s]

 97%|█████████▋| 97780/100629 [1:16:44<01:38, 29.03it/s]

 97%|█████████▋| 97784/100629 [1:16:45<01:38, 28.94it/s]

 97%|█████████▋| 97788/100629 [1:16:45<01:54, 24.79it/s]

 97%|█████████▋| 97791/100629 [1:16:45<01:50, 25.61it/s]

 97%|█████████▋| 97796/100629 [1:16:45<01:33, 30.34it/s]

 97%|█████████▋| 97800/100629 [1:16:45<01:54, 24.64it/s]

 97%|█████████▋| 97803/100629 [1:16:45<01:56, 24.27it/s]

 97%|█████████▋| 97806/100629 [1:16:46<02:11, 21.49it/s]

 97%|█████████▋| 97810/100629 [1:16:46<01:58, 23.85it/s]

 97%|█████████▋| 97814/100629 [1:16:46<01:52, 24.92it/s]

 97%|█████████▋| 97817/100629 [1:16:46<02:30, 18.65it/s]

 97%|█████████▋| 97820/100629 [1:16:46<02:25, 19.35it/s]

 97%|█████████▋| 97824/100629 [1:16:46<02:09, 21.66it/s]

 97%|█████████▋| 97827/100629 [1:16:47<02:22, 19.61it/s]

 97%|█████████▋| 97831/100629 [1:16:47<02:03, 22.67it/s]

 97%|█████████▋| 97834/100629 [1:16:47<02:07, 21.84it/s]

 97%|█████████▋| 97837/100629 [1:16:47<02:04, 22.37it/s]

 97%|█████████▋| 97840/100629 [1:16:47<02:03, 22.62it/s]

 97%|█████████▋| 97843/100629 [1:16:47<02:28, 18.79it/s]

 97%|█████████▋| 97846/100629 [1:16:47<02:29, 18.56it/s]

 97%|█████████▋| 97851/100629 [1:16:48<01:55, 24.01it/s]

 97%|█████████▋| 97854/100629 [1:16:48<02:05, 22.04it/s]

 97%|█████████▋| 97857/100629 [1:16:48<02:06, 21.99it/s]

 97%|█████████▋| 97860/100629 [1:16:48<01:58, 23.29it/s]

 97%|█████████▋| 97863/100629 [1:16:48<01:55, 24.04it/s]

 97%|█████████▋| 97866/100629 [1:16:48<02:02, 22.64it/s]

 97%|█████████▋| 97869/100629 [1:16:48<02:06, 21.83it/s]

 97%|█████████▋| 97872/100629 [1:16:49<02:23, 19.27it/s]

 97%|█████████▋| 97875/100629 [1:16:49<02:34, 17.79it/s]

 97%|█████████▋| 97878/100629 [1:16:49<02:22, 19.31it/s]

 97%|█████████▋| 97881/100629 [1:16:49<02:28, 18.51it/s]

 97%|█████████▋| 97885/100629 [1:16:49<02:03, 22.19it/s]

 97%|█████████▋| 97888/100629 [1:16:49<02:12, 20.68it/s]

 97%|█████████▋| 97891/100629 [1:16:49<02:03, 22.20it/s]

 97%|█████████▋| 97894/100629 [1:16:50<02:03, 22.21it/s]

 97%|█████████▋| 97898/100629 [1:16:50<01:57, 23.21it/s]

 97%|█████████▋| 97901/100629 [1:16:50<01:50, 24.70it/s]

 97%|█████████▋| 97904/100629 [1:16:50<02:03, 21.99it/s]

 97%|█████████▋| 97907/100629 [1:16:50<01:55, 23.53it/s]

 97%|█████████▋| 97910/100629 [1:16:50<02:17, 19.83it/s]

 97%|█████████▋| 97913/100629 [1:16:50<02:03, 21.95it/s]

 97%|█████████▋| 97916/100629 [1:16:51<01:55, 23.46it/s]

 97%|█████████▋| 97919/100629 [1:16:51<02:06, 21.42it/s]

 97%|█████████▋| 97922/100629 [1:16:51<02:02, 22.10it/s]

 97%|█████████▋| 97925/100629 [1:16:51<02:05, 21.51it/s]

 97%|█████████▋| 97928/100629 [1:16:51<01:57, 23.00it/s]

 97%|█████████▋| 97931/100629 [1:16:51<01:59, 22.53it/s]

 97%|█████████▋| 97936/100629 [1:16:51<01:34, 28.58it/s]

 97%|█████████▋| 97940/100629 [1:16:52<01:33, 28.84it/s]

 97%|█████████▋| 97943/100629 [1:16:52<01:41, 26.42it/s]

 97%|█████████▋| 97946/100629 [1:16:52<02:02, 21.87it/s]

 97%|█████████▋| 97949/100629 [1:16:52<02:18, 19.31it/s]

 97%|█████████▋| 97952/100629 [1:16:52<02:16, 19.67it/s]

 97%|█████████▋| 97955/100629 [1:16:52<02:06, 21.19it/s]

 97%|█████████▋| 97959/100629 [1:16:52<01:52, 23.82it/s]

 97%|█████████▋| 97962/100629 [1:16:53<01:55, 23.13it/s]

 97%|█████████▋| 97965/100629 [1:16:53<02:15, 19.59it/s]

 97%|█████████▋| 97968/100629 [1:16:53<02:07, 20.89it/s]

 97%|█████████▋| 97971/100629 [1:16:53<02:12, 20.12it/s]

 97%|█████████▋| 97974/100629 [1:16:53<02:13, 19.84it/s]

 97%|█████████▋| 97977/100629 [1:16:53<02:04, 21.38it/s]

 97%|█████████▋| 97980/100629 [1:16:53<02:01, 21.83it/s]

 97%|█████████▋| 97983/100629 [1:16:54<01:59, 22.08it/s]

 97%|█████████▋| 97986/100629 [1:16:54<01:54, 22.99it/s]

 97%|█████████▋| 97989/100629 [1:16:54<02:14, 19.65it/s]

 97%|█████████▋| 97992/100629 [1:16:54<02:15, 19.48it/s]

 97%|█████████▋| 97995/100629 [1:16:54<02:25, 18.06it/s]

 97%|█████████▋| 97999/100629 [1:16:54<01:58, 22.26it/s]

 97%|█████████▋| 98002/100629 [1:16:55<01:54, 22.93it/s]

 97%|█████████▋| 98005/100629 [1:16:55<02:43, 16.06it/s]

 97%|█████████▋| 98007/100629 [1:16:55<02:42, 16.11it/s]

 97%|█████████▋| 98009/100629 [1:16:55<02:42, 16.17it/s]

 97%|█████████▋| 98012/100629 [1:16:55<02:24, 18.15it/s]

 97%|█████████▋| 98016/100629 [1:16:55<02:09, 20.16it/s]

 97%|█████████▋| 98019/100629 [1:16:56<02:39, 16.32it/s]

 97%|█████████▋| 98021/100629 [1:16:56<02:45, 15.76it/s]

 97%|█████████▋| 98024/100629 [1:16:56<02:26, 17.78it/s]

 97%|█████████▋| 98027/100629 [1:16:56<02:10, 19.88it/s]

 97%|█████████▋| 98030/100629 [1:16:56<02:10, 19.94it/s]

 97%|█████████▋| 98034/100629 [1:16:56<01:50, 23.47it/s]

 97%|█████████▋| 98037/100629 [1:16:56<02:06, 20.56it/s]

 97%|█████████▋| 98040/100629 [1:16:57<01:56, 22.22it/s]

 97%|█████████▋| 98043/100629 [1:16:57<01:59, 21.69it/s]

 97%|█████████▋| 98047/100629 [1:16:57<01:45, 24.48it/s]

 97%|█████████▋| 98050/100629 [1:16:57<01:39, 25.79it/s]

 97%|█████████▋| 98055/100629 [1:16:57<01:22, 31.06it/s]

 97%|█████████▋| 98059/100629 [1:16:57<01:29, 28.84it/s]

 97%|█████████▋| 98064/100629 [1:16:57<01:22, 31.11it/s]

 97%|█████████▋| 98068/100629 [1:16:58<01:23, 30.68it/s]

 97%|█████████▋| 98072/100629 [1:16:58<01:26, 29.55it/s]

 97%|█████████▋| 98076/100629 [1:16:58<01:35, 26.84it/s]

 97%|█████████▋| 98079/100629 [1:16:58<01:40, 25.49it/s]

 97%|█████████▋| 98084/100629 [1:16:58<01:34, 26.92it/s]

 97%|█████████▋| 98087/100629 [1:16:58<01:42, 24.86it/s]

 97%|█████████▋| 98090/100629 [1:16:58<01:41, 24.93it/s]

 97%|█████████▋| 98094/100629 [1:16:59<01:45, 23.99it/s]

 97%|█████████▋| 98098/100629 [1:16:59<01:41, 25.06it/s]

 97%|█████████▋| 98101/100629 [1:16:59<01:57, 21.46it/s]

 97%|█████████▋| 98104/100629 [1:16:59<01:49, 23.13it/s]

 97%|█████████▋| 98108/100629 [1:16:59<01:40, 25.20it/s]

 97%|█████████▋| 98111/100629 [1:16:59<01:39, 25.32it/s]

 98%|█████████▊| 98115/100629 [1:17:00<01:51, 22.64it/s]

 98%|█████████▊| 98118/100629 [1:17:00<01:44, 23.96it/s]

 98%|█████████▊| 98121/100629 [1:17:00<02:12, 18.95it/s]

 98%|█████████▊| 98124/100629 [1:17:00<01:59, 20.91it/s]

 98%|█████████▊| 98128/100629 [1:17:00<01:43, 24.06it/s]

 98%|█████████▊| 98131/100629 [1:17:00<01:49, 22.78it/s]

 98%|█████████▊| 98134/100629 [1:17:00<01:46, 23.50it/s]

 98%|█████████▊| 98137/100629 [1:17:00<01:49, 22.80it/s]

 98%|█████████▊| 98140/100629 [1:17:01<01:54, 21.80it/s]

 98%|█████████▊| 98144/100629 [1:17:01<01:41, 24.40it/s]

 98%|█████████▊| 98147/100629 [1:17:01<01:54, 21.61it/s]

 98%|█████████▊| 98150/100629 [1:17:01<02:02, 20.31it/s]

 98%|█████████▊| 98153/100629 [1:17:01<02:03, 20.08it/s]

 98%|█████████▊| 98157/100629 [1:17:01<01:50, 22.39it/s]

 98%|█████████▊| 98160/100629 [1:17:02<01:54, 21.65it/s]

 98%|█████████▊| 98163/100629 [1:17:02<02:11, 18.82it/s]

 98%|█████████▊| 98166/100629 [1:17:02<02:00, 20.46it/s]

 98%|█████████▊| 98169/100629 [1:17:02<02:21, 17.38it/s]

 98%|█████████▊| 98171/100629 [1:17:02<02:22, 17.23it/s]

 98%|█████████▊| 98175/100629 [1:17:02<01:56, 21.14it/s]

 98%|█████████▊| 98180/100629 [1:17:02<01:33, 26.15it/s]

 98%|█████████▊| 98183/100629 [1:17:03<01:45, 23.21it/s]

 98%|█████████▊| 98186/100629 [1:17:03<01:44, 23.39it/s]

 98%|█████████▊| 98189/100629 [1:17:03<01:39, 24.52it/s]

 98%|█████████▊| 98193/100629 [1:17:03<01:26, 28.25it/s]

 98%|█████████▊| 98196/100629 [1:17:03<01:25, 28.46it/s]

 98%|█████████▊| 98199/100629 [1:17:03<01:33, 25.87it/s]

 98%|█████████▊| 98204/100629 [1:17:03<01:33, 25.89it/s]

 98%|█████████▊| 98208/100629 [1:17:04<01:28, 27.26it/s]

 98%|█████████▊| 98211/100629 [1:17:04<01:32, 26.01it/s]

 98%|█████████▊| 98214/100629 [1:17:04<01:46, 22.59it/s]

 98%|█████████▊| 98217/100629 [1:17:04<01:52, 21.49it/s]

 98%|█████████▊| 98221/100629 [1:17:04<01:42, 23.49it/s]

 98%|█████████▊| 98224/100629 [1:17:04<01:54, 21.02it/s]

 98%|█████████▊| 98227/100629 [1:17:05<01:53, 21.20it/s]

 98%|█████████▊| 98232/100629 [1:17:05<01:56, 20.62it/s]

 98%|█████████▊| 98235/100629 [1:17:05<02:01, 19.75it/s]

 98%|█████████▊| 98238/100629 [1:17:05<02:04, 19.14it/s]

 98%|█████████▊| 98241/100629 [1:17:05<02:01, 19.67it/s]

 98%|█████████▊| 98244/100629 [1:17:05<01:53, 21.01it/s]

 98%|█████████▊| 98247/100629 [1:17:05<01:51, 21.28it/s]

 98%|█████████▊| 98250/100629 [1:17:06<02:03, 19.20it/s]

 98%|█████████▊| 98252/100629 [1:17:06<02:31, 15.74it/s]

 98%|█████████▊| 98255/100629 [1:17:06<02:42, 14.57it/s]

 98%|█████████▊| 98257/100629 [1:17:06<02:36, 15.13it/s]

 98%|█████████▊| 98260/100629 [1:17:06<02:23, 16.52it/s]

 98%|█████████▊| 98264/100629 [1:17:07<01:55, 20.43it/s]

 98%|█████████▊| 98267/100629 [1:17:07<02:04, 18.91it/s]

 98%|█████████▊| 98270/100629 [1:17:07<02:02, 19.26it/s]

 98%|█████████▊| 98273/100629 [1:17:07<02:09, 18.25it/s]

 98%|█████████▊| 98275/100629 [1:17:07<02:21, 16.68it/s]

 98%|█████████▊| 98277/100629 [1:17:07<02:20, 16.71it/s]

 98%|█████████▊| 98279/100629 [1:17:07<02:19, 16.85it/s]

 98%|█████████▊| 98282/100629 [1:17:08<02:03, 18.96it/s]

 98%|█████████▊| 98285/100629 [1:17:08<01:51, 20.99it/s]

 98%|█████████▊| 98288/100629 [1:17:08<01:50, 21.13it/s]

 98%|█████████▊| 98291/100629 [1:17:08<01:47, 21.74it/s]

 98%|█████████▊| 98295/100629 [1:17:08<01:44, 22.39it/s]

 98%|█████████▊| 98300/100629 [1:17:08<01:30, 25.82it/s]

 98%|█████████▊| 98303/100629 [1:17:08<01:32, 25.04it/s]

 98%|█████████▊| 98306/100629 [1:17:09<01:31, 25.43it/s]

 98%|█████████▊| 98309/100629 [1:17:09<01:35, 24.19it/s]

 98%|█████████▊| 98312/100629 [1:17:09<01:31, 25.29it/s]

 98%|█████████▊| 98317/100629 [1:17:09<01:19, 28.98it/s]

 98%|█████████▊| 98320/100629 [1:17:09<01:25, 26.88it/s]

 98%|█████████▊| 98324/100629 [1:17:09<01:30, 25.42it/s]

 98%|█████████▊| 98327/100629 [1:17:09<01:34, 24.27it/s]

 98%|█████████▊| 98330/100629 [1:17:10<01:46, 21.58it/s]

 98%|█████████▊| 98333/100629 [1:17:10<01:50, 20.79it/s]

 98%|█████████▊| 98336/100629 [1:17:10<01:42, 22.39it/s]

 98%|█████████▊| 98339/100629 [1:17:10<01:57, 19.41it/s]

 98%|█████████▊| 98342/100629 [1:17:10<01:49, 20.88it/s]

 98%|█████████▊| 98345/100629 [1:17:10<01:45, 21.59it/s]

 98%|█████████▊| 98348/100629 [1:17:10<01:57, 19.45it/s]

 98%|█████████▊| 98351/100629 [1:17:11<02:09, 17.57it/s]

 98%|█████████▊| 98353/100629 [1:17:11<02:16, 16.68it/s]

 98%|█████████▊| 98355/100629 [1:17:11<02:23, 15.79it/s]

 98%|█████████▊| 98358/100629 [1:17:11<02:09, 17.53it/s]

 98%|█████████▊| 98361/100629 [1:17:11<02:00, 18.80it/s]

 98%|█████████▊| 98365/100629 [1:17:11<01:36, 23.50it/s]

 98%|█████████▊| 98368/100629 [1:17:11<01:40, 22.46it/s]

 98%|█████████▊| 98371/100629 [1:17:12<01:48, 20.79it/s]

 98%|█████████▊| 98375/100629 [1:17:12<01:36, 23.47it/s]

 98%|█████████▊| 98378/100629 [1:17:12<01:35, 23.55it/s]

 98%|█████████▊| 98381/100629 [1:17:12<01:42, 22.01it/s]

 98%|█████████▊| 98384/100629 [1:17:12<01:56, 19.20it/s]

 98%|█████████▊| 98387/100629 [1:17:12<01:54, 19.55it/s]

 98%|█████████▊| 98391/100629 [1:17:13<01:42, 21.87it/s]

 98%|█████████▊| 98394/100629 [1:17:13<02:05, 17.83it/s]

 98%|█████████▊| 98397/100629 [1:17:13<01:59, 18.66it/s]

 98%|█████████▊| 98401/100629 [1:17:13<01:42, 21.64it/s]

 98%|█████████▊| 98404/100629 [1:17:13<01:41, 21.89it/s]

 98%|█████████▊| 98408/100629 [1:17:13<01:41, 21.96it/s]

 98%|█████████▊| 98411/100629 [1:17:13<01:36, 22.97it/s]

 98%|█████████▊| 98414/100629 [1:17:14<01:34, 23.56it/s]

 98%|█████████▊| 98417/100629 [1:17:14<01:35, 23.14it/s]

 98%|█████████▊| 98420/100629 [1:17:14<01:41, 21.69it/s]

 98%|█████████▊| 98423/100629 [1:17:14<01:38, 22.42it/s]

 98%|█████████▊| 98426/100629 [1:17:14<01:33, 23.46it/s]

 98%|█████████▊| 98429/100629 [1:17:14<01:53, 19.38it/s]

 98%|█████████▊| 98432/100629 [1:17:15<01:57, 18.72it/s]

 98%|█████████▊| 98434/100629 [1:17:15<02:06, 17.30it/s]

 98%|█████████▊| 98439/100629 [1:17:15<01:30, 24.20it/s]

 98%|█████████▊| 98442/100629 [1:17:15<01:30, 24.08it/s]

 98%|█████████▊| 98445/100629 [1:17:15<01:34, 23.14it/s]

 98%|█████████▊| 98448/100629 [1:17:15<01:28, 24.58it/s]

 98%|█████████▊| 98451/100629 [1:17:15<01:24, 25.69it/s]

 98%|█████████▊| 98454/100629 [1:17:15<01:24, 25.69it/s]

 98%|█████████▊| 98457/100629 [1:17:16<01:32, 23.54it/s]

 98%|█████████▊| 98460/100629 [1:17:16<01:33, 23.16it/s]

 98%|█████████▊| 98463/100629 [1:17:16<01:45, 20.53it/s]

 98%|█████████▊| 98466/100629 [1:17:16<01:41, 21.26it/s]

 98%|█████████▊| 98469/100629 [1:17:16<01:39, 21.65it/s]

 98%|█████████▊| 98472/100629 [1:17:16<01:37, 22.09it/s]

 98%|█████████▊| 98475/100629 [1:17:16<01:36, 22.37it/s]

 98%|█████████▊| 98478/100629 [1:17:16<01:35, 22.64it/s]

 98%|█████████▊| 98481/100629 [1:17:17<01:28, 24.35it/s]

 98%|█████████▊| 98485/100629 [1:17:17<01:25, 25.18it/s]

 98%|█████████▊| 98488/100629 [1:17:17<01:26, 24.76it/s]

 98%|█████████▊| 98491/100629 [1:17:17<01:29, 23.84it/s]

 98%|█████████▊| 98494/100629 [1:17:17<01:36, 22.03it/s]

 98%|█████████▊| 98497/100629 [1:17:17<01:40, 21.24it/s]

 98%|█████████▊| 98500/100629 [1:17:17<01:43, 20.47it/s]

 98%|█████████▊| 98503/100629 [1:17:18<01:34, 22.41it/s]

 98%|█████████▊| 98506/100629 [1:17:18<01:45, 20.22it/s]

 98%|█████████▊| 98509/100629 [1:17:18<01:55, 18.33it/s]

 98%|█████████▊| 98512/100629 [1:17:18<01:44, 20.23it/s]

 98%|█████████▊| 98515/100629 [1:17:18<01:46, 19.81it/s]

 98%|█████████▊| 98518/100629 [1:17:18<01:43, 20.38it/s]

 98%|█████████▊| 98522/100629 [1:17:19<01:36, 21.74it/s]

 98%|█████████▊| 98525/100629 [1:17:19<01:50, 19.05it/s]

 98%|█████████▊| 98530/100629 [1:17:19<01:38, 21.37it/s]

 98%|█████████▊| 98535/100629 [1:17:19<01:23, 25.02it/s]

 98%|█████████▊| 98538/100629 [1:17:19<01:30, 23.18it/s]

 98%|█████████▊| 98541/100629 [1:17:19<01:39, 21.03it/s]

 98%|█████████▊| 98545/100629 [1:17:20<01:25, 24.49it/s]

 98%|█████████▊| 98549/100629 [1:17:20<01:20, 25.97it/s]

 98%|█████████▊| 98552/100629 [1:17:20<01:33, 22.16it/s]

 98%|█████████▊| 98556/100629 [1:17:20<01:21, 25.55it/s]

 98%|█████████▊| 98562/100629 [1:17:20<01:02, 33.23it/s]

 98%|█████████▊| 98566/100629 [1:17:20<01:05, 31.59it/s]

 98%|█████████▊| 98570/100629 [1:17:20<01:12, 28.40it/s]

 98%|█████████▊| 98574/100629 [1:17:20<01:10, 29.27it/s]

 98%|█████████▊| 98578/100629 [1:17:21<01:25, 23.95it/s]

 98%|█████████▊| 98581/100629 [1:17:21<01:26, 23.74it/s]

 98%|█████████▊| 98585/100629 [1:17:21<01:20, 25.53it/s]

 98%|█████████▊| 98588/100629 [1:17:21<01:18, 26.04it/s]

 98%|█████████▊| 98591/100629 [1:17:21<01:22, 24.81it/s]

 98%|█████████▊| 98594/100629 [1:17:21<01:34, 21.51it/s]

 98%|█████████▊| 98597/100629 [1:17:22<01:27, 23.22it/s]

 98%|█████████▊| 98600/100629 [1:17:22<01:29, 22.68it/s]

 98%|█████████▊| 98603/100629 [1:17:22<01:23, 24.33it/s]

 98%|█████████▊| 98606/100629 [1:17:22<01:27, 23.08it/s]

 98%|█████████▊| 98609/100629 [1:17:22<01:40, 20.15it/s]

 98%|█████████▊| 98612/100629 [1:17:22<02:07, 15.84it/s]

 98%|█████████▊| 98615/100629 [1:17:22<01:49, 18.39it/s]

 98%|█████████▊| 98619/100629 [1:17:23<01:29, 22.57it/s]

 98%|█████████▊| 98622/100629 [1:17:23<01:30, 22.16it/s]

 98%|█████████▊| 98625/100629 [1:17:23<01:23, 23.91it/s]

 98%|█████████▊| 98628/100629 [1:17:23<01:28, 22.73it/s]

 98%|█████████▊| 98631/100629 [1:17:23<01:32, 21.66it/s]

 98%|█████████▊| 98634/100629 [1:17:23<01:35, 20.90it/s]

 98%|█████████▊| 98637/100629 [1:17:23<01:32, 21.57it/s]

 98%|█████████▊| 98641/100629 [1:17:24<01:20, 24.57it/s]

 98%|█████████▊| 98644/100629 [1:17:24<01:30, 21.95it/s]

 98%|█████████▊| 98647/100629 [1:17:24<01:31, 21.55it/s]

 98%|█████████▊| 98652/100629 [1:17:24<01:14, 26.37it/s]

 98%|█████████▊| 98655/100629 [1:17:24<01:26, 22.84it/s]

 98%|█████████▊| 98658/100629 [1:17:24<01:32, 21.26it/s]

 98%|█████████▊| 98661/100629 [1:17:25<01:35, 20.69it/s]

 98%|█████████▊| 98664/100629 [1:17:25<01:27, 22.38it/s]

 98%|█████████▊| 98668/100629 [1:17:25<01:18, 24.87it/s]

 98%|█████████▊| 98671/100629 [1:17:25<01:18, 25.01it/s]

 98%|█████████▊| 98674/100629 [1:17:25<01:20, 24.36it/s]

 98%|█████████▊| 98678/100629 [1:17:25<01:13, 26.63it/s]

 98%|█████████▊| 98683/100629 [1:17:25<01:03, 30.41it/s]

 98%|█████████▊| 98687/100629 [1:17:26<01:32, 21.07it/s]

 98%|█████████▊| 98690/100629 [1:17:26<01:30, 21.38it/s]

 98%|█████████▊| 98693/100629 [1:17:26<01:35, 20.21it/s]

 98%|█████████▊| 98696/100629 [1:17:26<01:39, 19.44it/s]

 98%|█████████▊| 98700/100629 [1:17:26<01:25, 22.66it/s]

 98%|█████████▊| 98704/100629 [1:17:26<01:26, 22.30it/s]

 98%|█████████▊| 98707/100629 [1:17:27<01:38, 19.46it/s]

 98%|█████████▊| 98710/100629 [1:17:27<01:50, 17.42it/s]

 98%|█████████▊| 98713/100629 [1:17:27<01:47, 17.90it/s]

 98%|█████████▊| 98717/100629 [1:17:27<01:30, 21.16it/s]

 98%|█████████▊| 98720/100629 [1:17:27<01:39, 19.16it/s]

 98%|█████████▊| 98723/100629 [1:17:27<01:54, 16.68it/s]

 98%|█████████▊| 98727/100629 [1:17:28<01:37, 19.55it/s]

 98%|█████████▊| 98730/100629 [1:17:28<01:34, 20.05it/s]

 98%|█████████▊| 98735/100629 [1:17:28<01:12, 25.96it/s]

 98%|█████████▊| 98740/100629 [1:17:28<01:07, 27.93it/s]

 98%|█████████▊| 98744/100629 [1:17:28<01:16, 24.60it/s]

 98%|█████████▊| 98747/100629 [1:17:28<01:36, 19.59it/s]

 98%|█████████▊| 98750/100629 [1:17:29<01:35, 19.67it/s]

 98%|█████████▊| 98753/100629 [1:17:29<01:34, 19.92it/s]

 98%|█████████▊| 98756/100629 [1:17:29<01:33, 20.04it/s]

 98%|█████████▊| 98760/100629 [1:17:29<01:22, 22.70it/s]

 98%|█████████▊| 98763/100629 [1:17:29<01:22, 22.63it/s]

 98%|█████████▊| 98767/100629 [1:17:29<01:14, 24.99it/s]

 98%|█████████▊| 98770/100629 [1:17:29<01:17, 24.08it/s]

 98%|█████████▊| 98775/100629 [1:17:30<01:01, 30.04it/s]

 98%|█████████▊| 98779/100629 [1:17:30<01:03, 29.20it/s]

 98%|█████████▊| 98783/100629 [1:17:30<01:02, 29.39it/s]

 98%|█████████▊| 98787/100629 [1:17:30<01:08, 26.70it/s]

 98%|█████████▊| 98790/100629 [1:17:30<01:12, 25.25it/s]

 98%|█████████▊| 98793/100629 [1:17:30<01:14, 24.69it/s]

 98%|█████████▊| 98796/100629 [1:17:30<01:20, 22.82it/s]

 98%|█████████▊| 98799/100629 [1:17:31<01:16, 23.86it/s]

 98%|█████████▊| 98802/100629 [1:17:31<01:16, 23.75it/s]

 98%|█████████▊| 98805/100629 [1:17:31<01:26, 20.99it/s]

 98%|█████████▊| 98808/100629 [1:17:31<01:22, 21.95it/s]

 98%|█████████▊| 98811/100629 [1:17:31<01:19, 22.93it/s]

 98%|█████████▊| 98814/100629 [1:17:31<01:17, 23.53it/s]

 98%|█████████▊| 98817/100629 [1:17:31<01:27, 20.61it/s]

 98%|█████████▊| 98822/100629 [1:17:32<01:08, 26.52it/s]

 98%|█████████▊| 98826/100629 [1:17:32<01:01, 29.32it/s]

 98%|█████████▊| 98830/100629 [1:17:32<01:32, 19.50it/s]

 98%|█████████▊| 98834/100629 [1:17:32<01:21, 21.94it/s]

 98%|█████████▊| 98837/100629 [1:17:32<01:20, 22.34it/s]

 98%|█████████▊| 98841/100629 [1:17:32<01:10, 25.33it/s]

 98%|█████████▊| 98844/100629 [1:17:33<01:21, 21.80it/s]

 98%|█████████▊| 98849/100629 [1:17:33<01:10, 25.31it/s]

 98%|█████████▊| 98852/100629 [1:17:33<01:13, 24.02it/s]

 98%|█████████▊| 98855/100629 [1:17:33<01:11, 24.90it/s]

 98%|█████████▊| 98858/100629 [1:17:33<01:26, 20.43it/s]

 98%|█████████▊| 98861/100629 [1:17:33<01:31, 19.30it/s]

 98%|█████████▊| 98865/100629 [1:17:33<01:18, 22.40it/s]

 98%|█████████▊| 98868/100629 [1:17:34<01:18, 22.53it/s]

 98%|█████████▊| 98871/100629 [1:17:34<01:12, 24.13it/s]

 98%|█████████▊| 98874/100629 [1:17:34<01:18, 22.30it/s]

 98%|█████████▊| 98877/100629 [1:17:34<01:20, 21.81it/s]

 98%|█████████▊| 98880/100629 [1:17:34<01:17, 22.54it/s]

 98%|█████████▊| 98883/100629 [1:17:34<01:21, 21.30it/s]

 98%|█████████▊| 98886/100629 [1:17:34<01:17, 22.58it/s]

 98%|█████████▊| 98891/100629 [1:17:35<01:01, 28.18it/s]

 98%|█████████▊| 98894/100629 [1:17:35<01:06, 25.96it/s]

 98%|█████████▊| 98897/100629 [1:17:35<01:11, 24.20it/s]

 98%|█████████▊| 98900/100629 [1:17:35<01:11, 24.13it/s]

 98%|█████████▊| 98903/100629 [1:17:35<01:26, 19.84it/s]

 98%|█████████▊| 98906/100629 [1:17:35<01:38, 17.43it/s]

 98%|█████████▊| 98908/100629 [1:17:36<01:46, 16.21it/s]

 98%|█████████▊| 98913/100629 [1:17:36<01:21, 21.08it/s]

 98%|█████████▊| 98916/100629 [1:17:36<01:24, 20.20it/s]

 98%|█████████▊| 98919/100629 [1:17:36<01:20, 21.14it/s]

 98%|█████████▊| 98922/100629 [1:17:36<01:20, 21.22it/s]

 98%|█████████▊| 98925/100629 [1:17:36<01:28, 19.15it/s]

 98%|█████████▊| 98929/100629 [1:17:37<01:28, 19.25it/s]

 98%|█████████▊| 98932/100629 [1:17:37<01:20, 21.05it/s]

 98%|█████████▊| 98935/100629 [1:17:37<01:32, 18.35it/s]

 98%|█████████▊| 98938/100629 [1:17:37<01:27, 19.35it/s]

 98%|█████████▊| 98942/100629 [1:17:37<01:12, 23.35it/s]

 98%|█████████▊| 98945/100629 [1:17:37<01:18, 21.57it/s]

 98%|█████████▊| 98948/100629 [1:17:37<01:29, 18.81it/s]

 98%|█████████▊| 98951/100629 [1:17:38<01:24, 19.74it/s]

 98%|█████████▊| 98954/100629 [1:17:38<01:28, 18.88it/s]

 98%|█████████▊| 98957/100629 [1:17:38<01:24, 19.70it/s]

 98%|█████████▊| 98960/100629 [1:17:38<01:54, 14.59it/s]

 98%|█████████▊| 98962/100629 [1:17:38<01:50, 15.07it/s]

 98%|█████████▊| 98964/100629 [1:17:38<01:44, 15.92it/s]

 98%|█████████▊| 98966/100629 [1:17:39<01:47, 15.54it/s]

 98%|█████████▊| 98968/100629 [1:17:39<01:43, 16.06it/s]

 98%|█████████▊| 98971/100629 [1:17:39<01:33, 17.81it/s]

 98%|█████████▊| 98973/100629 [1:17:39<01:41, 16.39it/s]

 98%|█████████▊| 98975/100629 [1:17:39<02:18, 11.97it/s]

 98%|█████████▊| 98979/100629 [1:17:40<01:57, 14.06it/s]

 98%|█████████▊| 98981/100629 [1:17:40<01:54, 14.35it/s]

 98%|█████████▊| 98984/100629 [1:17:40<01:43, 15.94it/s]

 98%|█████████▊| 98986/100629 [1:17:40<01:56, 14.09it/s]

 98%|█████████▊| 98989/100629 [1:17:40<01:39, 16.56it/s]

 98%|█████████▊| 98991/100629 [1:17:40<01:36, 16.96it/s]

 98%|█████████▊| 98993/100629 [1:17:40<01:33, 17.45it/s]

 98%|█████████▊| 98995/100629 [1:17:40<01:39, 16.35it/s]

 98%|█████████▊| 98999/100629 [1:17:41<01:28, 18.52it/s]

 98%|█████████▊| 99003/100629 [1:17:41<01:14, 21.86it/s]

 98%|█████████▊| 99006/100629 [1:17:41<01:13, 22.11it/s]

 98%|█████████▊| 99011/100629 [1:17:41<00:57, 27.90it/s]

 98%|█████████▊| 99014/100629 [1:17:41<01:00, 26.90it/s]

 98%|█████████▊| 99018/100629 [1:17:41<00:59, 26.96it/s]

 98%|█████████▊| 99023/100629 [1:17:41<00:56, 28.34it/s]

 98%|█████████▊| 99028/100629 [1:17:42<00:48, 32.86it/s]

 98%|█████████▊| 99032/100629 [1:17:42<00:56, 28.51it/s]

 98%|█████████▊| 99036/100629 [1:17:42<00:51, 31.02it/s]

 98%|█████████▊| 99042/100629 [1:17:42<00:49, 32.06it/s]

 98%|█████████▊| 99046/100629 [1:17:42<00:52, 30.18it/s]

 98%|█████████▊| 99050/100629 [1:17:42<01:02, 25.15it/s]

 98%|█████████▊| 99053/100629 [1:17:42<01:00, 25.84it/s]

 98%|█████████▊| 99056/100629 [1:17:43<01:13, 21.54it/s]

 98%|█████████▊| 99061/100629 [1:17:43<01:05, 23.99it/s]

 98%|█████████▊| 99064/100629 [1:17:43<01:02, 24.96it/s]

 98%|█████████▊| 99069/100629 [1:17:43<00:58, 26.74it/s]

 98%|█████████▊| 99072/100629 [1:17:43<00:57, 27.07it/s]

 98%|█████████▊| 99076/100629 [1:17:43<00:59, 25.93it/s]

 98%|█████████▊| 99079/100629 [1:17:44<01:10, 21.99it/s]

 98%|█████████▊| 99082/100629 [1:17:44<01:11, 21.75it/s]

 98%|█████████▊| 99087/100629 [1:17:44<00:57, 26.92it/s]

 98%|█████████▊| 99090/100629 [1:17:44<01:03, 24.18it/s]

 98%|█████████▊| 99094/100629 [1:17:44<01:09, 22.21it/s]

 98%|█████████▊| 99097/100629 [1:17:44<01:10, 21.72it/s]

 98%|█████████▊| 99100/100629 [1:17:45<01:07, 22.59it/s]

 98%|█████████▊| 99103/100629 [1:17:45<01:12, 21.09it/s]

 98%|█████████▊| 99106/100629 [1:17:45<01:07, 22.48it/s]

 98%|█████████▊| 99109/100629 [1:17:45<01:12, 20.96it/s]

 98%|█████████▊| 99112/100629 [1:17:45<01:07, 22.42it/s]

 98%|█████████▊| 99115/100629 [1:17:45<01:02, 24.21it/s]

 98%|█████████▊| 99118/100629 [1:17:45<01:02, 24.11it/s]

 99%|█████████▊| 99121/100629 [1:17:45<01:12, 20.83it/s]

 99%|█████████▊| 99124/100629 [1:17:46<01:14, 20.18it/s]

 99%|█████████▊| 99127/100629 [1:17:46<01:27, 17.12it/s]

 99%|█████████▊| 99130/100629 [1:17:46<01:23, 18.02it/s]

 99%|█████████▊| 99133/100629 [1:17:46<01:17, 19.25it/s]

 99%|█████████▊| 99136/100629 [1:17:46<01:09, 21.54it/s]

 99%|█████████▊| 99139/100629 [1:17:46<01:11, 20.76it/s]

 99%|█████████▊| 99142/100629 [1:17:47<01:16, 19.37it/s]

 99%|█████████▊| 99145/100629 [1:17:47<01:13, 20.31it/s]

 99%|█████████▊| 99148/100629 [1:17:47<01:12, 20.44it/s]

 99%|█████████▊| 99151/100629 [1:17:47<01:10, 20.86it/s]

 99%|█████████▊| 99154/100629 [1:17:47<01:05, 22.69it/s]

 99%|█████████▊| 99157/100629 [1:17:47<01:04, 22.72it/s]

 99%|█████████▊| 99163/100629 [1:17:47<00:48, 30.31it/s]

 99%|█████████▊| 99167/100629 [1:17:48<00:53, 27.37it/s]

 99%|█████████▊| 99170/100629 [1:17:48<00:54, 27.01it/s]

 99%|█████████▊| 99173/100629 [1:17:48<01:10, 20.53it/s]

 99%|█████████▊| 99177/100629 [1:17:48<01:02, 23.35it/s]

 99%|█████████▊| 99180/100629 [1:17:48<01:03, 22.96it/s]

 99%|█████████▊| 99184/100629 [1:17:48<00:55, 26.05it/s]

 99%|█████████▊| 99187/100629 [1:17:48<00:57, 25.02it/s]

 99%|█████████▊| 99192/100629 [1:17:49<00:50, 28.63it/s]

 99%|█████████▊| 99195/100629 [1:17:49<00:55, 25.90it/s]

 99%|█████████▊| 99200/100629 [1:17:49<00:53, 26.90it/s]

 99%|█████████▊| 99203/100629 [1:17:49<01:00, 23.55it/s]

 99%|█████████▊| 99206/100629 [1:17:49<01:01, 23.33it/s]

 99%|█████████▊| 99209/100629 [1:17:49<01:12, 19.72it/s]

 99%|█████████▊| 99212/100629 [1:17:50<01:14, 19.02it/s]

 99%|█████████▊| 99215/100629 [1:17:50<01:09, 20.47it/s]

 99%|█████████▊| 99218/100629 [1:17:50<01:11, 19.61it/s]

 99%|█████████▊| 99222/100629 [1:17:50<01:06, 21.27it/s]

 99%|█████████▊| 99225/100629 [1:17:50<01:02, 22.41it/s]

 99%|█████████▊| 99228/100629 [1:17:50<01:02, 22.57it/s]

 99%|█████████▊| 99231/100629 [1:17:50<00:59, 23.30it/s]

 99%|█████████▊| 99236/100629 [1:17:51<00:52, 26.59it/s]

 99%|█████████▊| 99240/100629 [1:17:51<00:48, 28.40it/s]

 99%|█████████▊| 99243/100629 [1:17:51<00:56, 24.54it/s]

 99%|█████████▊| 99246/100629 [1:17:51<01:05, 21.06it/s]

 99%|█████████▊| 99249/100629 [1:17:51<01:09, 19.74it/s]

 99%|█████████▊| 99252/100629 [1:17:51<01:03, 21.67it/s]

 99%|█████████▊| 99255/100629 [1:17:51<01:06, 20.56it/s]

 99%|█████████▊| 99258/100629 [1:17:52<01:08, 19.99it/s]

 99%|█████████▊| 99261/100629 [1:17:52<01:14, 18.29it/s]

 99%|█████████▊| 99264/100629 [1:17:52<01:06, 20.58it/s]

 99%|█████████▊| 99267/100629 [1:17:52<01:06, 20.56it/s]

 99%|█████████▊| 99270/100629 [1:17:52<01:00, 22.44it/s]

 99%|█████████▊| 99274/100629 [1:17:52<00:50, 26.62it/s]

 99%|█████████▊| 99277/100629 [1:17:52<00:51, 26.29it/s]

 99%|█████████▊| 99280/100629 [1:17:53<00:56, 23.82it/s]

 99%|█████████▊| 99283/100629 [1:17:53<01:00, 22.22it/s]

 99%|█████████▊| 99286/100629 [1:17:53<01:10, 19.12it/s]

 99%|█████████▊| 99289/100629 [1:17:53<01:06, 20.21it/s]

 99%|█████████▊| 99294/100629 [1:17:53<00:53, 25.05it/s]

 99%|█████████▊| 99297/100629 [1:17:53<01:01, 21.58it/s]

 99%|█████████▊| 99300/100629 [1:17:53<01:00, 21.87it/s]

 99%|█████████▊| 99303/100629 [1:17:54<01:02, 21.15it/s]

 99%|█████████▊| 99306/100629 [1:17:54<00:57, 23.07it/s]

 99%|█████████▊| 99309/100629 [1:17:54<01:05, 20.14it/s]

 99%|█████████▊| 99312/100629 [1:17:54<01:01, 21.48it/s]

 99%|█████████▊| 99316/100629 [1:17:54<00:51, 25.34it/s]

 99%|█████████▊| 99319/100629 [1:17:54<00:56, 23.25it/s]

 99%|█████████▊| 99322/100629 [1:17:55<01:04, 20.17it/s]

 99%|█████████▊| 99325/100629 [1:17:55<01:07, 19.45it/s]

 99%|█████████▊| 99328/100629 [1:17:55<01:06, 19.62it/s]

 99%|█████████▊| 99331/100629 [1:17:55<01:00, 21.49it/s]

 99%|█████████▊| 99334/100629 [1:17:55<01:03, 20.51it/s]

 99%|█████████▊| 99337/100629 [1:17:55<01:07, 19.07it/s]

 99%|█████████▊| 99341/100629 [1:17:55<00:59, 21.52it/s]

 99%|█████████▊| 99344/100629 [1:17:56<00:57, 22.52it/s]

 99%|█████████▊| 99347/100629 [1:17:56<00:53, 24.18it/s]

 99%|█████████▊| 99350/100629 [1:17:56<00:57, 22.06it/s]

 99%|█████████▊| 99353/100629 [1:17:56<00:56, 22.48it/s]

 99%|█████████▊| 99356/100629 [1:17:56<00:56, 22.62it/s]

 99%|█████████▊| 99359/100629 [1:17:56<00:57, 22.20it/s]

 99%|█████████▊| 99363/100629 [1:17:56<00:49, 25.49it/s]

 99%|█████████▊| 99367/100629 [1:17:56<00:49, 25.74it/s]

 99%|█████████▊| 99371/100629 [1:17:57<00:45, 27.67it/s]

 99%|█████████▉| 99375/100629 [1:17:57<00:41, 30.47it/s]

 99%|█████████▉| 99379/100629 [1:17:57<00:52, 23.71it/s]

 99%|█████████▉| 99383/100629 [1:17:57<00:48, 25.80it/s]

 99%|█████████▉| 99386/100629 [1:17:57<00:50, 24.64it/s]

 99%|█████████▉| 99389/100629 [1:17:57<00:47, 25.84it/s]

 99%|█████████▉| 99392/100629 [1:17:57<00:51, 24.07it/s]

 99%|█████████▉| 99395/100629 [1:17:58<00:55, 22.10it/s]

 99%|█████████▉| 99399/100629 [1:17:58<00:49, 25.03it/s]

 99%|█████████▉| 99402/100629 [1:17:58<00:47, 26.00it/s]

 99%|█████████▉| 99405/100629 [1:17:58<01:09, 17.71it/s]

 99%|█████████▉| 99408/100629 [1:17:58<01:07, 18.19it/s]

 99%|█████████▉| 99411/100629 [1:17:58<01:05, 18.56it/s]

 99%|█████████▉| 99415/100629 [1:17:59<01:00, 20.09it/s]

 99%|█████████▉| 99418/100629 [1:17:59<00:55, 21.63it/s]

 99%|█████████▉| 99421/100629 [1:17:59<00:55, 21.76it/s]

 99%|█████████▉| 99425/100629 [1:17:59<00:51, 23.54it/s]

 99%|█████████▉| 99428/100629 [1:17:59<01:00, 19.78it/s]

 99%|█████████▉| 99431/100629 [1:17:59<00:57, 20.76it/s]

 99%|█████████▉| 99434/100629 [1:18:00<00:57, 20.75it/s]

 99%|█████████▉| 99437/100629 [1:18:00<00:53, 22.16it/s]

 99%|█████████▉| 99441/100629 [1:18:00<00:49, 24.02it/s]

 99%|█████████▉| 99444/100629 [1:18:00<00:48, 24.54it/s]

 99%|█████████▉| 99447/100629 [1:18:00<00:49, 23.98it/s]

 99%|█████████▉| 99450/100629 [1:18:00<00:52, 22.26it/s]

 99%|█████████▉| 99453/100629 [1:18:00<00:53, 22.13it/s]

 99%|█████████▉| 99456/100629 [1:18:01<01:02, 18.68it/s]

 99%|█████████▉| 99458/100629 [1:18:01<01:03, 18.46it/s]

 99%|█████████▉| 99461/100629 [1:18:01<00:59, 19.65it/s]

 99%|█████████▉| 99464/100629 [1:18:01<01:01, 18.90it/s]

 99%|█████████▉| 99467/100629 [1:18:01<01:05, 17.79it/s]

 99%|█████████▉| 99469/100629 [1:18:01<01:03, 18.20it/s]

 99%|█████████▉| 99473/100629 [1:18:01<00:52, 21.85it/s]

 99%|█████████▉| 99476/100629 [1:18:01<00:48, 23.69it/s]

 99%|█████████▉| 99481/100629 [1:18:02<00:43, 26.23it/s]

 99%|█████████▉| 99484/100629 [1:18:02<00:42, 26.76it/s]

 99%|█████████▉| 99487/100629 [1:18:02<00:44, 25.78it/s]

 99%|█████████▉| 99491/100629 [1:18:02<00:42, 26.49it/s]

 99%|█████████▉| 99494/100629 [1:18:02<00:46, 24.24it/s]

 99%|█████████▉| 99497/100629 [1:18:02<00:46, 24.37it/s]

 99%|█████████▉| 99500/100629 [1:18:02<00:45, 24.77it/s]

 99%|█████████▉| 99503/100629 [1:18:03<00:47, 23.84it/s]

 99%|█████████▉| 99506/100629 [1:18:03<00:50, 22.23it/s]

 99%|█████████▉| 99510/100629 [1:18:03<00:47, 23.78it/s]

 99%|█████████▉| 99513/100629 [1:18:03<00:46, 23.85it/s]

 99%|█████████▉| 99516/100629 [1:18:03<00:47, 23.58it/s]

 99%|█████████▉| 99519/100629 [1:18:03<00:54, 20.41it/s]

 99%|█████████▉| 99522/100629 [1:18:03<00:52, 21.01it/s]

 99%|█████████▉| 99527/100629 [1:18:04<00:47, 23.29it/s]

 99%|█████████▉| 99530/100629 [1:18:04<00:54, 20.24it/s]

 99%|█████████▉| 99533/100629 [1:18:04<00:51, 21.12it/s]

 99%|█████████▉| 99536/100629 [1:18:04<00:47, 22.99it/s]

 99%|█████████▉| 99540/100629 [1:18:04<00:43, 24.88it/s]

 99%|█████████▉| 99543/100629 [1:18:04<00:43, 25.16it/s]

 99%|█████████▉| 99546/100629 [1:18:04<00:48, 22.44it/s]

 99%|█████████▉| 99549/100629 [1:18:05<00:47, 22.63it/s]

 99%|█████████▉| 99552/100629 [1:18:05<00:55, 19.51it/s]

 99%|█████████▉| 99557/100629 [1:18:05<00:43, 24.41it/s]

 99%|█████████▉| 99560/100629 [1:18:05<00:50, 21.13it/s]

 99%|█████████▉| 99563/100629 [1:18:05<00:46, 22.76it/s]

 99%|█████████▉| 99566/100629 [1:18:05<00:49, 21.67it/s]

 99%|█████████▉| 99569/100629 [1:18:06<01:02, 16.94it/s]

 99%|█████████▉| 99572/100629 [1:18:06<00:59, 17.77it/s]

 99%|█████████▉| 99575/100629 [1:18:06<00:56, 18.68it/s]

 99%|█████████▉| 99578/100629 [1:18:06<01:07, 15.68it/s]

 99%|█████████▉| 99581/100629 [1:18:06<01:00, 17.22it/s]

 99%|█████████▉| 99584/100629 [1:18:06<00:53, 19.69it/s]

 99%|█████████▉| 99588/100629 [1:18:07<00:44, 23.44it/s]

 99%|█████████▉| 99591/100629 [1:18:07<00:45, 22.98it/s]

 99%|█████████▉| 99594/100629 [1:18:07<00:50, 20.54it/s]

 99%|█████████▉| 99597/100629 [1:18:07<00:47, 21.64it/s]

 99%|█████████▉| 99600/100629 [1:18:07<00:46, 22.23it/s]

 99%|█████████▉| 99603/100629 [1:18:07<00:47, 21.44it/s]

 99%|█████████▉| 99606/100629 [1:18:07<00:45, 22.46it/s]

 99%|█████████▉| 99609/100629 [1:18:08<00:45, 22.46it/s]

 99%|█████████▉| 99612/100629 [1:18:08<00:46, 22.06it/s]

 99%|█████████▉| 99615/100629 [1:18:08<00:52, 19.36it/s]

 99%|█████████▉| 99618/100629 [1:18:08<00:54, 18.70it/s]

 99%|█████████▉| 99621/100629 [1:18:08<00:52, 19.08it/s]

 99%|█████████▉| 99624/100629 [1:18:08<00:47, 21.19it/s]

 99%|█████████▉| 99627/100629 [1:18:08<00:51, 19.30it/s]

 99%|█████████▉| 99631/100629 [1:18:09<00:45, 21.73it/s]

 99%|█████████▉| 99634/100629 [1:18:09<00:42, 23.51it/s]

 99%|█████████▉| 99637/100629 [1:18:09<00:45, 21.72it/s]

 99%|█████████▉| 99640/100629 [1:18:09<00:44, 22.39it/s]

 99%|█████████▉| 99643/100629 [1:18:09<00:49, 19.84it/s]

 99%|█████████▉| 99646/100629 [1:18:09<00:46, 20.95it/s]

 99%|█████████▉| 99649/100629 [1:18:10<00:50, 19.51it/s]

 99%|█████████▉| 99652/100629 [1:18:10<00:50, 19.38it/s]

 99%|█████████▉| 99654/100629 [1:18:10<00:50, 19.25it/s]

 99%|█████████▉| 99658/100629 [1:18:10<00:45, 21.54it/s]

 99%|█████████▉| 99661/100629 [1:18:10<00:48, 20.01it/s]

 99%|█████████▉| 99664/100629 [1:18:10<00:55, 17.48it/s]

 99%|█████████▉| 99667/100629 [1:18:10<00:50, 19.04it/s]

 99%|█████████▉| 99670/100629 [1:18:11<00:57, 16.77it/s]

 99%|█████████▉| 99672/100629 [1:18:11<01:02, 15.38it/s]

 99%|█████████▉| 99676/100629 [1:18:11<00:55, 17.26it/s]

 99%|█████████▉| 99679/100629 [1:18:11<00:52, 18.23it/s]

 99%|█████████▉| 99681/100629 [1:18:11<00:53, 17.78it/s]

 99%|█████████▉| 99684/100629 [1:18:11<00:50, 18.84it/s]

 99%|█████████▉| 99687/100629 [1:18:12<00:47, 19.80it/s]

 99%|█████████▉| 99691/100629 [1:18:12<00:43, 21.40it/s]

 99%|█████████▉| 99695/100629 [1:18:12<00:37, 24.70it/s]

 99%|█████████▉| 99698/100629 [1:18:12<00:46, 19.99it/s]

 99%|█████████▉| 99701/100629 [1:18:12<00:52, 17.52it/s]

 99%|█████████▉| 99704/100629 [1:18:12<00:49, 18.75it/s]

 99%|█████████▉| 99707/100629 [1:18:13<00:47, 19.36it/s]

 99%|█████████▉| 99711/100629 [1:18:13<00:40, 22.53it/s]

 99%|█████████▉| 99715/100629 [1:18:13<00:38, 23.50it/s]

 99%|█████████▉| 99718/100629 [1:18:13<00:36, 24.62it/s]

 99%|█████████▉| 99721/100629 [1:18:13<00:37, 24.48it/s]

 99%|█████████▉| 99724/100629 [1:18:13<00:36, 24.52it/s]

 99%|█████████▉| 99727/100629 [1:18:13<00:41, 21.80it/s]

 99%|█████████▉| 99732/100629 [1:18:14<00:32, 27.60it/s]

 99%|█████████▉| 99736/100629 [1:18:14<00:31, 27.95it/s]

 99%|█████████▉| 99739/100629 [1:18:14<00:31, 28.26it/s]

 99%|█████████▉| 99744/100629 [1:18:14<00:27, 32.75it/s]

 99%|█████████▉| 99748/100629 [1:18:14<00:30, 29.26it/s]

 99%|█████████▉| 99752/100629 [1:18:14<00:35, 24.57it/s]

 99%|█████████▉| 99755/100629 [1:18:14<00:34, 25.21it/s]

 99%|█████████▉| 99759/100629 [1:18:14<00:31, 27.68it/s]

 99%|█████████▉| 99763/100629 [1:18:15<00:32, 26.30it/s]

 99%|█████████▉| 99766/100629 [1:18:15<00:33, 26.04it/s]

 99%|█████████▉| 99769/100629 [1:18:15<00:33, 25.85it/s]

 99%|█████████▉| 99773/100629 [1:18:15<00:32, 26.71it/s]

 99%|█████████▉| 99776/100629 [1:18:15<00:34, 24.95it/s]

 99%|█████████▉| 99779/100629 [1:18:15<00:44, 19.28it/s]

 99%|█████████▉| 99782/100629 [1:18:16<00:41, 20.56it/s]

 99%|█████████▉| 99785/100629 [1:18:16<00:39, 21.53it/s]

 99%|█████████▉| 99789/100629 [1:18:16<00:36, 23.21it/s]

 99%|█████████▉| 99792/100629 [1:18:16<00:42, 19.49it/s]

 99%|█████████▉| 99795/100629 [1:18:16<00:39, 21.05it/s]

 99%|█████████▉| 99799/100629 [1:18:16<00:33, 24.85it/s]

 99%|█████████▉| 99802/100629 [1:18:16<00:35, 23.37it/s]

 99%|█████████▉| 99806/100629 [1:18:17<00:30, 26.70it/s]

 99%|█████████▉| 99809/100629 [1:18:17<00:32, 25.16it/s]

 99%|█████████▉| 99812/100629 [1:18:17<00:33, 24.45it/s]

 99%|█████████▉| 99815/100629 [1:18:17<00:33, 24.58it/s]

 99%|█████████▉| 99818/100629 [1:18:17<00:33, 23.96it/s]

 99%|█████████▉| 99821/100629 [1:18:17<00:36, 21.85it/s]

 99%|█████████▉| 99824/100629 [1:18:17<00:34, 23.59it/s]

 99%|█████████▉| 99827/100629 [1:18:17<00:34, 22.99it/s]

 99%|█████████▉| 99830/100629 [1:18:18<00:33, 24.19it/s]

 99%|█████████▉| 99833/100629 [1:18:18<00:40, 19.76it/s]

 99%|█████████▉| 99836/100629 [1:18:18<00:40, 19.48it/s]

 99%|█████████▉| 99839/100629 [1:18:18<00:42, 18.74it/s]

 99%|█████████▉| 99843/100629 [1:18:18<00:36, 21.27it/s]

 99%|█████████▉| 99846/100629 [1:18:18<00:34, 22.53it/s]

 99%|█████████▉| 99849/100629 [1:18:18<00:34, 22.52it/s]

 99%|█████████▉| 99852/100629 [1:18:19<00:34, 22.53it/s]

 99%|█████████▉| 99856/100629 [1:18:19<00:31, 24.29it/s]

 99%|█████████▉| 99859/100629 [1:18:19<00:31, 24.38it/s]

 99%|█████████▉| 99862/100629 [1:18:19<00:34, 22.25it/s]

 99%|█████████▉| 99865/100629 [1:18:19<00:39, 19.32it/s]

 99%|█████████▉| 99868/100629 [1:18:19<00:40, 18.67it/s]

 99%|█████████▉| 99870/100629 [1:18:20<00:41, 18.31it/s]

 99%|█████████▉| 99875/100629 [1:18:20<00:33, 22.83it/s]

 99%|█████████▉| 99878/100629 [1:18:20<00:32, 22.87it/s]

 99%|█████████▉| 99881/100629 [1:18:20<00:37, 19.71it/s]

 99%|█████████▉| 99884/100629 [1:18:20<00:39, 18.99it/s]

 99%|█████████▉| 99886/100629 [1:18:20<00:41, 18.01it/s]

 99%|█████████▉| 99888/100629 [1:18:21<00:46, 15.79it/s]

 99%|█████████▉| 99892/100629 [1:18:21<00:36, 20.26it/s]

 99%|█████████▉| 99895/100629 [1:18:21<00:37, 19.34it/s]

 99%|█████████▉| 99898/100629 [1:18:21<00:36, 20.24it/s]

 99%|█████████▉| 99902/100629 [1:18:21<00:29, 24.48it/s]

 99%|█████████▉| 99908/100629 [1:18:21<00:23, 30.66it/s]

 99%|█████████▉| 99912/100629 [1:18:21<00:27, 26.14it/s]

 99%|█████████▉| 99915/100629 [1:18:22<00:38, 18.66it/s]

 99%|█████████▉| 99918/100629 [1:18:22<00:42, 16.78it/s]

 99%|█████████▉| 99921/100629 [1:18:22<00:37, 18.64it/s]

 99%|█████████▉| 99924/100629 [1:18:22<00:35, 19.92it/s]

 99%|█████████▉| 99927/100629 [1:18:22<00:39, 17.87it/s]

 99%|█████████▉| 99930/100629 [1:18:22<00:36, 19.29it/s]

 99%|█████████▉| 99933/100629 [1:18:23<00:35, 19.47it/s]

 99%|█████████▉| 99936/100629 [1:18:23<00:37, 18.39it/s]

 99%|█████████▉| 99938/100629 [1:18:23<00:51, 13.49it/s]

 99%|█████████▉| 99940/100629 [1:18:23<00:54, 12.71it/s]

 99%|█████████▉| 99942/100629 [1:18:23<00:52, 12.99it/s]

 99%|█████████▉| 99947/100629 [1:18:24<00:41, 16.36it/s]

 99%|█████████▉| 99950/100629 [1:18:24<00:36, 18.53it/s]

 99%|█████████▉| 99952/100629 [1:18:24<00:39, 17.03it/s]

 99%|█████████▉| 99956/100629 [1:18:24<00:31, 21.57it/s]

 99%|█████████▉| 99961/100629 [1:18:24<00:24, 26.90it/s]

 99%|█████████▉| 99964/100629 [1:18:24<00:24, 27.55it/s]

 99%|█████████▉| 99968/100629 [1:18:24<00:21, 30.58it/s]

 99%|█████████▉| 99972/100629 [1:18:25<00:23, 27.65it/s]

 99%|█████████▉| 99976/100629 [1:18:25<00:22, 28.47it/s]

 99%|█████████▉| 99979/100629 [1:18:25<00:28, 22.78it/s]

 99%|█████████▉| 99982/100629 [1:18:25<00:27, 23.53it/s]

 99%|█████████▉| 99985/100629 [1:18:25<00:28, 22.51it/s]

 99%|█████████▉| 99989/100629 [1:18:25<00:25, 24.86it/s]

 99%|█████████▉| 99993/100629 [1:18:25<00:23, 27.39it/s]

 99%|█████████▉| 99996/100629 [1:18:26<00:29, 21.55it/s]

 99%|█████████▉| 99999/100629 [1:18:26<00:28, 21.92it/s]

 99%|█████████▉| 100004/100629 [1:18:26<00:23, 27.14it/s]

 99%|█████████▉| 100007/100629 [1:18:26<00:28, 21.92it/s]

 99%|█████████▉| 100010/100629 [1:18:26<00:27, 22.45it/s]

 99%|█████████▉| 100013/100629 [1:18:26<00:29, 21.11it/s]

 99%|█████████▉| 100016/100629 [1:18:26<00:28, 21.17it/s]

 99%|█████████▉| 100019/100629 [1:18:27<00:27, 22.34it/s]

 99%|█████████▉| 100022/100629 [1:18:27<00:33, 18.12it/s]

 99%|█████████▉| 100026/100629 [1:18:27<00:29, 20.59it/s]

 99%|█████████▉| 100029/100629 [1:18:27<00:26, 22.37it/s]

 99%|█████████▉| 100032/100629 [1:18:27<00:28, 21.03it/s]

 99%|█████████▉| 100035/100629 [1:18:27<00:28, 20.55it/s]

 99%|█████████▉| 100038/100629 [1:18:28<00:27, 21.30it/s]

 99%|█████████▉| 100041/100629 [1:18:28<00:26, 22.54it/s]

 99%|█████████▉| 100046/100629 [1:18:28<00:20, 28.71it/s]

 99%|█████████▉| 100050/100629 [1:18:28<00:27, 20.77it/s]

 99%|█████████▉| 100054/100629 [1:18:28<00:23, 24.24it/s]

 99%|█████████▉| 100057/100629 [1:18:28<00:25, 22.36it/s]

 99%|█████████▉| 100060/100629 [1:18:28<00:26, 21.13it/s]

 99%|█████████▉| 100063/100629 [1:18:29<00:25, 21.82it/s]

 99%|█████████▉| 100066/100629 [1:18:29<00:28, 19.99it/s]

 99%|█████████▉| 100069/100629 [1:18:29<00:28, 19.92it/s]

 99%|█████████▉| 100072/100629 [1:18:29<00:31, 17.68it/s]

 99%|█████████▉| 100074/100629 [1:18:29<00:37, 14.68it/s]

 99%|█████████▉| 100077/100629 [1:18:30<00:32, 16.80it/s]

 99%|█████████▉| 100081/100629 [1:18:30<00:27, 20.03it/s]

 99%|█████████▉| 100084/100629 [1:18:30<00:26, 20.43it/s]

 99%|█████████▉| 100087/100629 [1:18:30<00:27, 20.03it/s]

 99%|█████████▉| 100091/100629 [1:18:30<00:24, 21.97it/s]

 99%|█████████▉| 100094/100629 [1:18:30<00:23, 22.99it/s]

 99%|█████████▉| 100098/100629 [1:18:30<00:20, 26.23it/s]

 99%|█████████▉| 100101/100629 [1:18:30<00:21, 24.20it/s]

 99%|█████████▉| 100104/100629 [1:18:31<00:25, 20.80it/s]

 99%|█████████▉| 100107/100629 [1:18:31<00:26, 19.64it/s]

 99%|█████████▉| 100110/100629 [1:18:31<00:24, 21.46it/s]

 99%|█████████▉| 100113/100629 [1:18:31<00:22, 22.59it/s]

 99%|█████████▉| 100116/100629 [1:18:31<00:22, 23.05it/s]

 99%|█████████▉| 100119/100629 [1:18:31<00:21, 23.31it/s]

 99%|█████████▉| 100122/100629 [1:18:31<00:23, 21.82it/s]

 99%|█████████▉| 100125/100629 [1:18:32<00:25, 19.71it/s]

100%|█████████▉| 100128/100629 [1:18:32<00:26, 18.98it/s]

100%|█████████▉| 100131/100629 [1:18:32<00:24, 20.63it/s]

100%|█████████▉| 100134/100629 [1:18:32<00:24, 20.31it/s]

100%|█████████▉| 100137/100629 [1:18:32<00:27, 17.74it/s]

100%|█████████▉| 100139/100629 [1:18:32<00:29, 16.58it/s]

100%|█████████▉| 100142/100629 [1:18:33<00:26, 18.62it/s]

100%|█████████▉| 100146/100629 [1:18:33<00:24, 20.00it/s]

100%|█████████▉| 100149/100629 [1:18:33<00:25, 18.73it/s]

100%|█████████▉| 100151/100629 [1:18:33<00:26, 18.00it/s]

100%|█████████▉| 100154/100629 [1:18:33<00:24, 19.35it/s]

100%|█████████▉| 100157/100629 [1:18:33<00:23, 20.28it/s]

100%|█████████▉| 100160/100629 [1:18:33<00:21, 22.22it/s]

100%|█████████▉| 100163/100629 [1:18:34<00:25, 18.08it/s]

100%|█████████▉| 100166/100629 [1:18:34<00:23, 19.58it/s]

100%|█████████▉| 100169/100629 [1:18:34<00:25, 18.34it/s]

100%|█████████▉| 100171/100629 [1:18:34<00:24, 18.48it/s]

100%|█████████▉| 100175/100629 [1:18:34<00:20, 22.63it/s]

100%|█████████▉| 100179/100629 [1:18:34<00:22, 19.81it/s]

100%|█████████▉| 100182/100629 [1:18:35<00:21, 21.25it/s]

100%|█████████▉| 100185/100629 [1:18:35<00:21, 21.14it/s]

100%|█████████▉| 100189/100629 [1:18:35<00:21, 20.86it/s]

100%|█████████▉| 100193/100629 [1:18:35<00:17, 24.46it/s]

100%|█████████▉| 100196/100629 [1:18:35<00:18, 23.15it/s]

100%|█████████▉| 100199/100629 [1:18:35<00:18, 23.47it/s]

100%|█████████▉| 100202/100629 [1:18:35<00:20, 21.33it/s]

100%|█████████▉| 100205/100629 [1:18:36<00:19, 22.03it/s]

100%|█████████▉| 100209/100629 [1:18:36<00:18, 23.03it/s]

100%|█████████▉| 100213/100629 [1:18:36<00:17, 23.19it/s]

100%|█████████▉| 100216/100629 [1:18:36<00:21, 19.57it/s]

100%|█████████▉| 100219/100629 [1:18:36<00:20, 19.81it/s]

100%|█████████▉| 100222/100629 [1:18:36<00:18, 21.60it/s]

100%|█████████▉| 100226/100629 [1:18:37<00:17, 22.55it/s]

100%|█████████▉| 100229/100629 [1:18:37<00:17, 23.04it/s]

100%|█████████▉| 100232/100629 [1:18:37<00:16, 23.49it/s]

100%|█████████▉| 100237/100629 [1:18:37<00:14, 26.74it/s]

100%|█████████▉| 100241/100629 [1:18:37<00:13, 27.91it/s]

100%|█████████▉| 100244/100629 [1:18:37<00:15, 24.25it/s]

100%|█████████▉| 100247/100629 [1:18:37<00:17, 22.13it/s]

100%|█████████▉| 100250/100629 [1:18:38<00:18, 20.39it/s]

100%|█████████▉| 100253/100629 [1:18:38<00:17, 21.54it/s]

100%|█████████▉| 100256/100629 [1:18:38<00:16, 22.86it/s]

100%|█████████▉| 100259/100629 [1:18:38<00:16, 22.98it/s]

100%|█████████▉| 100262/100629 [1:18:38<00:14, 24.47it/s]

100%|█████████▉| 100265/100629 [1:18:38<00:14, 24.52it/s]

100%|█████████▉| 100269/100629 [1:18:38<00:15, 23.42it/s]

100%|█████████▉| 100272/100629 [1:18:39<00:15, 22.87it/s]

100%|█████████▉| 100275/100629 [1:18:39<00:16, 22.05it/s]

100%|█████████▉| 100278/100629 [1:18:39<00:18, 18.92it/s]

100%|█████████▉| 100282/100629 [1:18:39<00:15, 22.49it/s]

100%|█████████▉| 100285/100629 [1:18:39<00:15, 22.68it/s]

100%|█████████▉| 100288/100629 [1:18:39<00:16, 20.45it/s]

100%|█████████▉| 100291/100629 [1:18:39<00:16, 20.50it/s]

100%|█████████▉| 100294/100629 [1:18:40<00:17, 19.37it/s]

100%|█████████▉| 100299/100629 [1:18:40<00:14, 23.36it/s]

100%|█████████▉| 100302/100629 [1:18:40<00:14, 21.83it/s]

100%|█████████▉| 100305/100629 [1:18:40<00:14, 22.74it/s]

100%|█████████▉| 100308/100629 [1:18:40<00:16, 19.70it/s]

100%|█████████▉| 100313/100629 [1:18:40<00:13, 23.83it/s]

100%|█████████▉| 100316/100629 [1:18:41<00:13, 22.52it/s]

100%|█████████▉| 100319/100629 [1:18:41<00:14, 22.02it/s]

100%|█████████▉| 100322/100629 [1:18:41<00:15, 19.75it/s]

100%|█████████▉| 100325/100629 [1:18:41<00:14, 21.56it/s]

100%|█████████▉| 100328/100629 [1:18:41<00:15, 19.44it/s]

100%|█████████▉| 100331/100629 [1:18:41<00:14, 20.85it/s]

100%|█████████▉| 100334/100629 [1:18:42<00:17, 17.12it/s]

100%|█████████▉| 100338/100629 [1:18:42<00:15, 18.76it/s]

100%|█████████▉| 100341/100629 [1:18:42<00:15, 18.36it/s]

100%|█████████▉| 100343/100629 [1:18:42<00:15, 18.60it/s]

100%|█████████▉| 100347/100629 [1:18:42<00:12, 22.78it/s]

100%|█████████▉| 100350/100629 [1:18:42<00:12, 22.57it/s]

100%|█████████▉| 100353/100629 [1:18:42<00:12, 21.50it/s]

100%|█████████▉| 100357/100629 [1:18:43<00:11, 24.24it/s]

100%|█████████▉| 100360/100629 [1:18:43<00:10, 25.27it/s]

100%|█████████▉| 100363/100629 [1:18:43<00:12, 21.68it/s]

100%|█████████▉| 100366/100629 [1:18:43<00:14, 18.66it/s]

100%|█████████▉| 100369/100629 [1:18:43<00:16, 16.17it/s]

100%|█████████▉| 100372/100629 [1:18:43<00:13, 18.63it/s]

100%|█████████▉| 100376/100629 [1:18:44<00:12, 20.80it/s]

100%|█████████▉| 100379/100629 [1:18:44<00:11, 21.86it/s]

100%|█████████▉| 100382/100629 [1:18:44<00:10, 22.51it/s]

100%|█████████▉| 100385/100629 [1:18:44<00:11, 21.29it/s]

100%|█████████▉| 100388/100629 [1:18:44<00:10, 22.43it/s]

100%|█████████▉| 100391/100629 [1:18:44<00:10, 21.72it/s]

100%|█████████▉| 100394/100629 [1:18:44<00:11, 21.13it/s]

100%|█████████▉| 100397/100629 [1:18:44<00:10, 22.44it/s]

100%|█████████▉| 100400/100629 [1:18:45<00:09, 23.19it/s]

100%|█████████▉| 100403/100629 [1:18:45<00:09, 22.97it/s]

100%|█████████▉| 100406/100629 [1:18:45<00:10, 20.32it/s]

100%|█████████▉| 100409/100629 [1:18:45<00:10, 20.52it/s]

100%|█████████▉| 100412/100629 [1:18:45<00:10, 21.40it/s]

100%|█████████▉| 100415/100629 [1:18:45<00:12, 17.26it/s]

100%|█████████▉| 100418/100629 [1:18:46<00:12, 17.58it/s]

100%|█████████▉| 100422/100629 [1:18:46<00:10, 20.24it/s]

100%|█████████▉| 100426/100629 [1:18:46<00:08, 23.39it/s]

100%|█████████▉| 100430/100629 [1:18:46<00:07, 25.97it/s]

100%|█████████▉| 100435/100629 [1:18:46<00:06, 30.97it/s]

100%|█████████▉| 100439/100629 [1:18:46<00:06, 27.55it/s]

100%|█████████▉| 100442/100629 [1:18:46<00:07, 25.31it/s]

100%|█████████▉| 100446/100629 [1:18:47<00:06, 26.49it/s]

100%|█████████▉| 100449/100629 [1:18:47<00:07, 25.49it/s]

100%|█████████▉| 100452/100629 [1:18:47<00:07, 24.74it/s]

100%|█████████▉| 100455/100629 [1:18:47<00:07, 24.75it/s]

100%|█████████▉| 100459/100629 [1:18:47<00:06, 25.56it/s]

100%|█████████▉| 100462/100629 [1:18:47<00:07, 23.73it/s]

100%|█████████▉| 100465/100629 [1:18:47<00:07, 21.95it/s]

100%|█████████▉| 100468/100629 [1:18:48<00:07, 22.09it/s]

100%|█████████▉| 100471/100629 [1:18:48<00:07, 21.60it/s]

100%|█████████▉| 100475/100629 [1:18:48<00:07, 21.56it/s]

100%|█████████▉| 100478/100629 [1:18:48<00:06, 22.90it/s]

100%|█████████▉| 100481/100629 [1:18:48<00:06, 23.49it/s]

100%|█████████▉| 100484/100629 [1:18:48<00:06, 24.04it/s]

100%|█████████▉| 100488/100629 [1:18:48<00:05, 25.83it/s]

100%|█████████▉| 100491/100629 [1:18:48<00:05, 24.72it/s]

100%|█████████▉| 100494/100629 [1:18:49<00:05, 23.49it/s]

100%|█████████▉| 100497/100629 [1:18:49<00:05, 23.72it/s]

100%|█████████▉| 100500/100629 [1:18:49<00:05, 22.77it/s]

100%|█████████▉| 100504/100629 [1:18:49<00:04, 25.75it/s]

100%|█████████▉| 100507/100629 [1:18:49<00:04, 24.63it/s]

100%|█████████▉| 100511/100629 [1:18:49<00:04, 27.26it/s]

100%|█████████▉| 100514/100629 [1:18:49<00:04, 23.30it/s]

100%|█████████▉| 100517/100629 [1:18:50<00:05, 20.01it/s]

100%|█████████▉| 100520/100629 [1:18:50<00:05, 19.59it/s]

100%|█████████▉| 100523/100629 [1:18:50<00:05, 17.76it/s]

100%|█████████▉| 100526/100629 [1:18:50<00:05, 18.61it/s]

100%|█████████▉| 100528/100629 [1:18:50<00:05, 18.67it/s]

100%|█████████▉| 100532/100629 [1:18:50<00:04, 22.87it/s]

100%|█████████▉| 100535/100629 [1:18:51<00:04, 23.12it/s]

100%|█████████▉| 100539/100629 [1:18:51<00:03, 26.04it/s]

100%|█████████▉| 100542/100629 [1:18:51<00:03, 22.89it/s]

100%|█████████▉| 100545/100629 [1:18:51<00:04, 20.95it/s]

100%|█████████▉| 100548/100629 [1:18:51<00:04, 20.11it/s]

100%|█████████▉| 100553/100629 [1:18:51<00:03, 25.30it/s]

100%|█████████▉| 100556/100629 [1:18:51<00:02, 25.04it/s]

100%|█████████▉| 100559/100629 [1:18:52<00:03, 20.28it/s]

100%|█████████▉| 100563/100629 [1:18:52<00:02, 23.45it/s]

100%|█████████▉| 100567/100629 [1:18:52<00:02, 26.15it/s]

100%|█████████▉| 100570/100629 [1:18:52<00:02, 25.81it/s]

100%|█████████▉| 100573/100629 [1:18:52<00:02, 26.19it/s]

100%|█████████▉| 100576/100629 [1:18:52<00:02, 22.17it/s]

100%|█████████▉| 100579/100629 [1:18:53<00:02, 16.92it/s]

100%|█████████▉| 100582/100629 [1:18:53<00:02, 17.85it/s]

100%|█████████▉| 100585/100629 [1:18:53<00:02, 16.99it/s]

100%|█████████▉| 100587/100629 [1:18:53<00:02, 16.44it/s]

100%|█████████▉| 100591/100629 [1:18:53<00:01, 19.11it/s]

100%|█████████▉| 100593/100629 [1:18:53<00:01, 18.76it/s]

100%|█████████▉| 100595/100629 [1:18:53<00:01, 17.76it/s]

100%|█████████▉| 100598/100629 [1:18:54<00:01, 16.31it/s]

100%|█████████▉| 100600/100629 [1:18:54<00:01, 16.63it/s]

100%|█████████▉| 100603/100629 [1:18:54<00:01, 15.30it/s]

100%|█████████▉| 100605/100629 [1:18:54<00:01, 16.11it/s]

100%|█████████▉| 100610/100629 [1:18:54<00:00, 23.44it/s]

100%|█████████▉| 100613/100629 [1:18:54<00:00, 18.49it/s]

100%|█████████▉| 100617/100629 [1:18:55<00:00, 22.62it/s]

100%|█████████▉| 100620/100629 [1:18:55<00:00, 21.97it/s]

100%|█████████▉| 100623/100629 [1:18:55<00:00, 19.81it/s]

100%|█████████▉| 100627/100629 [1:18:55<00:00, 23.26it/s]

100%|██████████| 100629/100629 [1:18:55<00:00, 21.25it/s]

In [11]:
emotions_df = pd.DataFrame(emotion_scores)
emotions_df["isbn13"] = isbn

In [12]:
emotions_df

,anger,disgust,fear,joy,sadness,surprise,neutral,isbn13
0,0.401102,0.194913,0.951007,0.069741,0.816087,0.305637,0.362398,9781411668980
1,0.391387,0.104007,0.051363,0.307681,0.549477,0.111690,0.150324,9780226575087
2,0.868221,0.381056,0.934325,0.276919,0.939046,0.640672,0.644575,9780062467874
3,0.152401,0.104007,0.702743,0.040564,0.874593,0.111690,0.078765,9780062930484
4,0.140983,0.104007,0.737003,0.258215,0.944252,0.111690,0.203355,9781632365804
...,...,...,...,...,...,...,...,...
100624,0.095671,0.104007,0.227203,0.066592,0.914617,0.111690,0.385701,9781925704259
100625,0.064134,0.104007,0.051363,0.226735,0.810443,0.111690,0.083311,9780642279606
100626,0.145456,0.338897,0.038927,0.612713,0.555899,0.283070,0.188844,9781988254685
100627,0.079136,0.104007,0.119965,0.572331,0.895729,0.111690,0.125690,9788198859686
100628,0.064134,0.104007,0.282238,0.978704,0.939250,0.111690,0.112954,9789354997327

In [13]:
# add the maximum score for each emotion to the book vectors
books = pd.merge(books, emotions_df, on = "isbn13")

In [14]:
books

,isbn13,title,authors,categories,description,thumbnail,published_year,average_rating,num_pages,title_and_subtitle,tagged_description,simple_categories,anger,disgust,fear,joy,sadness,surprise,neutral
0,9781411668980,"The Galaxii Series: Book 1 ""Blachart""",Christina Engela,"Fiction, romance, general",Action! Adventure! Space Opera! Life hardly ev...,https://covers.openlibrary.org/b/id/14313750-L...,2018,NaN,280.0,"The Galaxii Series: Book 1 ""Blachart""",9781411668980 Action! Adventure! Space Opera! ...,Fiction,0.401102,0.194913,0.951007,0.069741,0.816087,0.305637,0.362398
1,9780226575087,Lost Mars,Michael Ashley,"Fiction;Science Fiction;Fiction, science ficti...",Ten short stories from the golden age of scien...,https://covers.openlibrary.org/b/id/13133252-L...,2018,NaN,302.0,Lost Mars: stories from the golden age of the ...,9780226575087 Ten short stories from the golde...,Fiction,0.391387,0.104007,0.051363,0.307681,0.549477,0.111690,0.150324
2,9780062467874,Villain,Michael Grant,Juvenile fiction;Fiction;Supernatural;Horror s...,MONSTER. VILLAIN. HERO. WHICH SUPERCREATURE WI...,https://covers.openlibrary.org/b/id/8814378-L.jpg,2018,NaN,324.0,Villain,9780062467874 MONSTER. VILLAIN. HERO. WHICH SU...,Children's,0.868221,0.381056,0.934325,0.276919,0.939046,0.640672,0.644575
3,9780062930484,The ABC Murders,Agatha Christie,Fiction;Mystery;Agatha Christie;Hercule Poirot...,"There's a serial killer on the loose, bent on ...",https://covers.openlibrary.org/b/id/-1-L.jpg,2019,NaN,272.0,The ABC Murders: A Hercule Poirot Mystery,9780062930484 There's a serial killer on the l...,Fiction,0.152401,0.104007,0.702743,0.040564,0.874593,0.111690,0.078765
4,9781632365804,Welcome to the ballroom,Tomo Takeuchi,Competitions;Ballroom dancing;Dance;Ballroom d...,"""Through sheer force of will, Tatara and China...",NaN,2018,NaN,NaN,Welcome to the ballroom,"9781632365804 ""Through sheer force of will, Ta...",Fiction,0.140983,0.104007,0.737003,0.258215,0.944252,0.111690,0.203355
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100624,9781925704259,Dizzy limits,Noëlle Janaczewska,Australian Creative nonfiction,When conventional approaches to writing about ...,NaN,2020,NaN,440.0,Dizzy limits: recent experiments in Australian...,9781925704259 When conventional approaches to ...,Nonfiction,0.095671,0.104007,0.227203,0.066592,0.914617,0.111690,0.385701
100625,9780642279606,Flight of the Budgerigar,Penny Olsen,Budgerigar;History,Taking the reader from the Dreaming to the col...,NaN,2021,NaN,251.0,Flight of the Budgerigar: an illustrated history,9780642279606 Taking the reader from the Dream...,Nonfiction,0.064134,0.104007,0.051363,0.226735,0.810443,0.111690,0.083311
100626,9781988254685,Walls of the cave,Syr Ruus,Families;Fiction;Orphans;Loneliness,"""A writer of unknown gender, an orphan, brough...",NaN,2019,NaN,103.0,Walls of the cave,"9781988254685 ""A writer of unknown gender, an ...",Fiction,0.145456,0.338897,0.038927,0.612713,0.555899,0.283070,0.188844
100627,9788198859686,The Struggle for Europe,NaN,History;Biographies;Memoirs,"First published in 1952, ‘The Struggle for Eur...",https://covers.openlibrary.org/b/id/15219838-L...,2025,NaN,NaN,The Struggle for Europe,"9788198859686 First published in 1952, ‘The St...",Nonfiction,0.079136,0.104007,0.119965,0.572331,0.895729,0.111690,0.125690
100628,9789354997327,How to Use the Laws of Mind,Joseph Murphy,Self-Help;Non-Fiction;Motivation;Success,‘How to Use the Laws of Mind’ is one of Dr. Mu...,https://covers.openlibrary.org/b/id/15221165-L...,2023,NaN,NaN,How to Use the Laws of Mind,9789354997327 ‘How to Use the Laws of Mind’ is...,Nonfiction,0.064134,0.104007,0.282238,0.978704,0.939250,0.111690,0.112954

In [15]:
books.to_csv("../data/books_with_emotions.csv", index = False)