In [1]:
import pandas as pd

books = pd.read_csv("../data/books_cleaned.csv")

In [2]:
books["categories"].value_counts().reset_index()

                                     categories  count
0                                   Exhibitions    232
1                           American literature    221
2                            Children's fiction    150
3                            English literature    139
4                     Fiction, romance, general    133
...                                         ...    ...
91624            Australian Creative nonfiction      1
91625                        Budgerigar;History      1
91626       Families;Fiction;Orphans;Loneliness      1
91627               History;Biographies;Memoirs      1
91628  Self-Help;Non-Fiction;Motivation;Success      1

[91629 rows x 2 columns]

In [3]:
# get rid of categories with less than 50 books
books["categories"].value_counts().reset_index().query("count > 50")

                             categories  count
0                           Exhibitions    232
1                   American literature    221
2                    Children's fiction    150
3                    English literature    139
4             Fiction, romance, general    133
5                            Literature    110
6                  Artistic Photography     76
7                      Fiction, general     66
8   Poetry (poetic works by one author)     58
9                       Canadian poetry     57
10         Criticism and interpretation     53
11  American literature;American poetry     51

In [4]:
import re

# OL puts many subjects into one ';'-joined string so scan for keywords. 
# "nonfiction" contains "fiction", so nonfiction tested before fiction.

# genre hints consulted when no explicit fiction/nonfiction label is present.
FICTION_HINTS = (
    "fantasy", "romance", "thriller", "mystery", "horror", "science fiction",
    "short stories", "fairy tale", "graphic novel", "comic", "detective",
    "adventure", "poetry", "drama", "novel",
)
NONFICTION_HINTS = (
    "biography", "autobiography", "history", "philosophy", "religion", "self-help",
    "cooking", "travel", "business", "psychology", "memoir", "true crime", "essays",
    "science", "reference", "health",
)

def simplify_categories(cats):
    if not isinstance(cats, str):
        return None
    c = cats.lower()

    # children's books collapse to one bucket: the fiction/nonfiction sub-split was sparse
    # (Children's Nonfiction ~1%) and noisy, and the juvenile signal is far more reliable
    # than that sub-decision. Checked first, so we don't even need to resolve fiction kind.
    if ("juvenile" in c) or ("children" in c):
        return "Children's"

    if re.search(r"non-?fiction", c):              # 1: explicit labels
        return "Nonfiction"
    if re.search(r"\bfiction\b", c):
        return "Fiction"
    if any(h in c for h in FICTION_HINTS):         # 2: genre hints
        return "Fiction"
    if any(h in c for h in NONFICTION_HINTS):
        return "Nonfiction"
    return None                                    # leave for the BART backfill below

books["simple_categories"] = books["categories"].apply(simplify_categories)
books["simple_categories"].value_counts(dropna=False)

simple_categories
Nonfiction    36331
NaN           30196
Fiction       22715
Children's    11387
Name: count, dtype: int64

In [5]:
books

,isbn13,title,authors,categories,description,thumbnail,published_year,average_rating,num_pages,title_and_subtitle,tagged_description,simple_categories
0,9781411668980,"The Galaxii Series: Book 1 ""Blachart""",Christina Engela,"Fiction, romance, general",Action! Adventure! Space Opera! Life hardly ev...,https://covers.openlibrary.org/b/id/14313750-L...,2018,NaN,280.0,"The Galaxii Series: Book 1 ""Blachart""",9781411668980 Action! Adventure! Space Opera! ...,Fiction
1,9780226575087,Lost Mars,Michael Ashley,"Fiction;Science Fiction;Fiction, science ficti...",Ten short stories from the golden age of scien...,https://covers.openlibrary.org/b/id/13133252-L...,2018,NaN,302.0,Lost Mars: stories from the golden age of the ...,9780226575087 Ten short stories from the golde...,Fiction
2,9780062467874,Villain,Michael Grant,Juvenile fiction;Fiction;Supernatural;Horror s...,MONSTER. VILLAIN. HERO. WHICH SUPERCREATURE WI...,https://covers.openlibrary.org/b/id/8814378-L.jpg,2018,NaN,324.0,Villain,9780062467874 MONSTER. VILLAIN. HERO. WHICH SU...,Children's
3,9780062930484,The ABC Murders,Agatha Christie,Fiction;Mystery;Agatha Christie;Hercule Poirot...,"There's a serial killer on the loose, bent on ...",https://covers.openlibrary.org/b/id/-1-L.jpg,2019,NaN,272.0,The ABC Murders: A Hercule Poirot Mystery,9780062930484 There's a serial killer on the l...,Fiction
4,9781632365804,Welcome to the ballroom,Tomo Takeuchi,Competitions;Ballroom dancing;Dance;Ballroom d...,"""Through sheer force of will, Tatara and China...",NaN,2018,NaN,NaN,Welcome to the ballroom,"9781632365804 ""Through sheer force of will, Ta...",Fiction
...,...,...,...,...,...,...,...,...,...,...,...,...
100624,9781925704259,Dizzy limits,Noëlle Janaczewska,Australian Creative nonfiction,When conventional approaches to writing about ...,NaN,2020,NaN,440.0,Dizzy limits: recent experiments in Australian...,9781925704259 When conventional approaches to ...,Nonfiction
100625,9780642279606,Flight of the Budgerigar,Penny Olsen,Budgerigar;History,Taking the reader from the Dreaming to the col...,NaN,2021,NaN,251.0,Flight of the Budgerigar: an illustrated history,9780642279606 Taking the reader from the Dream...,Nonfiction
100626,9781988254685,Walls of the cave,Syr Ruus,Families;Fiction;Orphans;Loneliness,"""A writer of unknown gender, an orphan, brough...",NaN,2019,NaN,103.0,Walls of the cave,"9781988254685 ""A writer of unknown gender, an ...",Fiction
100627,9788198859686,The Struggle for Europe,NaN,History;Biographies;Memoirs,"First published in 1952, ‘The Struggle for Eur...",https://covers.openlibrary.org/b/id/15219838-L...,2025,NaN,NaN,The Struggle for Europe,"9788198859686 First published in 1952, ‘The St...",Nonfiction
100628,9789354997327,How to Use the Laws of Mind,Joseph Murphy,Self-Help;Non-Fiction;Motivation;Success,‘How to Use the Laws of Mind’ is one of Dr. Mu...,https://covers.openlibrary.org/b/id/15221165-L...,2023,NaN,NaN,How to Use the Laws of Mind,9789354997327 ‘How to Use the Laws of Mind’ is...,Nonfiction

In [6]:
books[~(books["simple_categories"].isna())]

,isbn13,title,authors,categories,description,thumbnail,published_year,average_rating,num_pages,title_and_subtitle,tagged_description,simple_categories
0,9781411668980,"The Galaxii Series: Book 1 ""Blachart""",Christina Engela,"Fiction, romance, general",Action! Adventure! Space Opera! Life hardly ev...,https://covers.openlibrary.org/b/id/14313750-L...,2018,NaN,280.0,"The Galaxii Series: Book 1 ""Blachart""",9781411668980 Action! Adventure! Space Opera! ...,Fiction
1,9780226575087,Lost Mars,Michael Ashley,"Fiction;Science Fiction;Fiction, science ficti...",Ten short stories from the golden age of scien...,https://covers.openlibrary.org/b/id/13133252-L...,2018,NaN,302.0,Lost Mars: stories from the golden age of the ...,9780226575087 Ten short stories from the golde...,Fiction
2,9780062467874,Villain,Michael Grant,Juvenile fiction;Fiction;Supernatural;Horror s...,MONSTER. VILLAIN. HERO. WHICH SUPERCREATURE WI...,https://covers.openlibrary.org/b/id/8814378-L.jpg,2018,NaN,324.0,Villain,9780062467874 MONSTER. VILLAIN. HERO. WHICH SU...,Children's
3,9780062930484,The ABC Murders,Agatha Christie,Fiction;Mystery;Agatha Christie;Hercule Poirot...,"There's a serial killer on the loose, bent on ...",https://covers.openlibrary.org/b/id/-1-L.jpg,2019,NaN,272.0,The ABC Murders: A Hercule Poirot Mystery,9780062930484 There's a serial killer on the l...,Fiction
4,9781632365804,Welcome to the ballroom,Tomo Takeuchi,Competitions;Ballroom dancing;Dance;Ballroom d...,"""Through sheer force of will, Tatara and China...",NaN,2018,NaN,NaN,Welcome to the ballroom,"9781632365804 ""Through sheer force of will, Ta...",Fiction
...,...,...,...,...,...,...,...,...,...,...,...,...
100624,9781925704259,Dizzy limits,Noëlle Janaczewska,Australian Creative nonfiction,When conventional approaches to writing about ...,NaN,2020,NaN,440.0,Dizzy limits: recent experiments in Australian...,9781925704259 When conventional approaches to ...,Nonfiction
100625,9780642279606,Flight of the Budgerigar,Penny Olsen,Budgerigar;History,Taking the reader from the Dreaming to the col...,NaN,2021,NaN,251.0,Flight of the Budgerigar: an illustrated history,9780642279606 Taking the reader from the Dream...,Nonfiction
100626,9781988254685,Walls of the cave,Syr Ruus,Families;Fiction;Orphans;Loneliness,"""A writer of unknown gender, an orphan, brough...",NaN,2019,NaN,103.0,Walls of the cave,"9781988254685 ""A writer of unknown gender, an ...",Fiction
100627,9788198859686,The Struggle for Europe,NaN,History;Biographies;Memoirs,"First published in 1952, ‘The Struggle for Eur...",https://covers.openlibrary.org/b/id/15219838-L...,2025,NaN,NaN,The Struggle for Europe,"9788198859686 First published in 1952, ‘The St...",Nonfiction
100628,9789354997327,How to Use the Laws of Mind,Joseph Murphy,Self-Help;Non-Fiction;Motivation;Success,‘How to Use the Laws of Mind’ is one of Dr. Mu...,https://covers.openlibrary.org/b/id/15221165-L...,2023,NaN,NaN,How to Use the Laws of Mind,9789354997327 ‘How to Use the Laws of Mind’ is...,Nonfiction

In [7]:
from transformers import pipeline

fiction_categories = ["Fiction", "Nonfiction"]
pipe = pipeline("zero-shot-classification", model="facebook/bart-large-mnli", device="mps")
# mps is the Apple Mac specific GPU

Loading weights:   0%|          | 0/515 [00:00<?, ?it/s]

In [8]:
sequence = books.loc[books["simple_categories"] == "Fiction", "description"].reset_index(drop=True)[0]
# resetting the index ensure indexes correlate to the classified books not the original database

In [9]:
pipe(sequence, fiction_categories)
# returns probability that the book is within each category

{'sequence': 'Action! Adventure! Space Opera! Life hardly ever turns out the way we expect it to, and for Mykl d’Angelo, skipper and owner of the loderunner Pegasus, it had just taken a bad turn for terrible. Due a minor misunderstanding, his crew had stolen the ship’s only shuttle, leaving him and two others behind to crew the ailing ship on their own. As if that weren’t bad enough, just a few hours later the rickety old ship’s stardrive exploded in the middle of the middle of nowhere, killing Mykl’s two remaining crewmen. Marooned alone in deep space, Mykl d’Angelo counted his blessings, offered prayers to any gods who specialized in miracles, and prepared to await (A) seemingly unlikely rescue, or (B) a lingering death… Rescue takes place, but at a price – as the Antares, a cruiser dispatched to investigate the mysterious silence of a remote starbase crosses paths with a legendary and fearsome Corsair – a man whose name sent shivers down the spines of lesser mortals. Blachart… Blachart the Bloody.',
 'labels': ['Fiction', 'Nonfiction'],
 'scores': [0.8755338191986084, 0.1244661957025528]}

In [10]:
import numpy as np

max_index = np.argmax(pipe(sequence, fiction_categories)["scores"])
max_label = pipe(sequence, fiction_categories)["labels"][max_index]
max_label

'Fiction'

In [11]:
def generate_predictions(sequence, categories):
    predictions = pipe(sequence, categories)
    max_index = np.argmax(predictions["scores"]) # yields the index of the highest probability
    max_label = predictions["labels"][max_index]
    return max_label

In [12]:
# Testing how good the model is using a sizable sample
from tqdm import tqdm
# tqdm is a library used to add progress bars to loops

actual_cats = []
predicted_cats = []

for i in tqdm(range(0, 100)):
    sequence = books.loc[books["simple_categories"] == "Fiction", "description"].reset_index(drop=True)[i]
    predicted_cats += [generate_predictions(sequence, fiction_categories)]
    actual_cats += ["Fiction"]

  0%|          | 0/100 [00:00<?, ?it/s]

  1%|          | 1/100 [00:00<00:14,  6.74it/s]

  2%|▏         | 2/100 [00:00<00:41,  2.34it/s]

  3%|▎         | 3/100 [00:00<00:31,  3.12it/s]

  4%|▍         | 4/100 [00:01<00:44,  2.14it/s]

  5%|▌         | 5/100 [00:01<00:33,  2.80it/s]

  6%|▌         | 6/100 [00:02<00:28,  3.26it/s]

  8%|▊         | 8/100 [00:02<00:22,  4.13it/s]

  9%|▉         | 9/100 [00:02<00:20,  4.44it/s]

 10%|█         | 10/100 [00:02<00:20,  4.43it/s]

 11%|█         | 11/100 [00:03<00:21,  4.05it/s]

 12%|█▏        | 12/100 [00:03<00:20,  4.28it/s]

 13%|█▎        | 13/100 [00:03<00:21,  4.09it/s]

 14%|█▍        | 14/100 [00:03<00:20,  4.19it/s]

 15%|█▌        | 15/100 [00:03<00:17,  4.73it/s]

 16%|█▌        | 16/100 [00:04<00:15,  5.52it/s]

 17%|█▋        | 17/100 [00:04<00:15,  5.24it/s]

 18%|█▊        | 18/100 [00:04<00:15,  5.16it/s]

 19%|█▉        | 19/100 [00:04<00:16,  5.00it/s]

 20%|██        | 20/100 [00:04<00:18,  4.42it/s]

 22%|██▏       | 22/100 [00:05<00:13,  5.60it/s]

 23%|██▎       | 23/100 [00:05<00:12,  6.19it/s]

 24%|██▍       | 24/100 [00:05<00:13,  5.46it/s]

 25%|██▌       | 25/100 [00:05<00:16,  4.67it/s]

 27%|██▋       | 27/100 [00:06<00:12,  5.98it/s]

 29%|██▉       | 29/100 [00:06<00:11,  6.30it/s]

 30%|███       | 30/100 [00:06<00:10,  6.40it/s]

 31%|███       | 31/100 [00:06<00:11,  5.84it/s]

 32%|███▏      | 32/100 [00:07<00:13,  5.00it/s]

 34%|███▍      | 34/100 [00:07<00:11,  5.83it/s]

 36%|███▌      | 36/100 [00:07<00:10,  5.99it/s]

 37%|███▋      | 37/100 [00:07<00:10,  6.17it/s]

 38%|███▊      | 38/100 [00:07<00:09,  6.31it/s]

 39%|███▉      | 39/100 [00:07<00:08,  6.81it/s]

 40%|████      | 40/100 [00:08<00:09,  6.07it/s]

 41%|████      | 41/100 [00:08<00:09,  5.99it/s]

 43%|████▎     | 43/100 [00:08<00:08,  6.49it/s]

 44%|████▍     | 44/100 [00:08<00:08,  6.94it/s]

 45%|████▌     | 45/100 [00:08<00:08,  6.15it/s]

 46%|████▌     | 46/100 [00:09<00:08,  6.24it/s]

 47%|████▋     | 47/100 [00:09<00:07,  6.82it/s]

 48%|████▊     | 48/100 [00:09<00:08,  6.08it/s]

 49%|████▉     | 49/100 [00:09<00:09,  5.52it/s]

 50%|█████     | 50/100 [00:09<00:08,  6.00it/s]

 51%|█████     | 51/100 [00:10<00:10,  4.80it/s]

 52%|█████▏    | 52/100 [00:10<00:12,  3.94it/s]

 53%|█████▎    | 53/100 [00:10<00:10,  4.35it/s]

 55%|█████▌    | 55/100 [00:10<00:08,  5.33it/s]

 56%|█████▌    | 56/100 [00:11<00:07,  5.80it/s]

 58%|█████▊    | 58/100 [00:11<00:05,  7.62it/s]

 60%|██████    | 60/100 [00:11<00:04,  8.92it/s]

 61%|██████    | 61/100 [00:11<00:04,  8.60it/s]

 62%|██████▏   | 62/100 [00:11<00:05,  7.27it/s]

 63%|██████▎   | 63/100 [00:11<00:04,  7.41it/s]

 65%|██████▌   | 65/100 [00:11<00:03,  9.26it/s]

 67%|██████▋   | 67/100 [00:12<00:03, 10.48it/s]

 69%|██████▉   | 69/100 [00:12<00:03,  9.96it/s]

 71%|███████   | 71/100 [00:12<00:03,  7.75it/s]

 72%|███████▏  | 72/100 [00:12<00:03,  7.44it/s]

 74%|███████▍  | 74/100 [00:12<00:02,  9.35it/s]

 76%|███████▌  | 76/100 [00:13<00:03,  6.27it/s]

 78%|███████▊  | 78/100 [00:13<00:03,  7.31it/s]

 80%|████████  | 80/100 [00:13<00:02,  8.32it/s]

 82%|████████▏ | 82/100 [00:14<00:02,  8.24it/s]

 83%|████████▎ | 83/100 [00:14<00:02,  8.36it/s]

 85%|████████▌ | 85/100 [00:14<00:01,  8.84it/s]

 86%|████████▌ | 86/100 [00:14<00:01,  8.59it/s]

 88%|████████▊ | 88/100 [00:14<00:01,  9.60it/s]

 90%|█████████ | 90/100 [00:14<00:00, 10.27it/s]

 92%|█████████▏| 92/100 [00:15<00:00,  9.25it/s]

 93%|█████████▎| 93/100 [00:15<00:00,  7.75it/s]

 94%|█████████▍| 94/100 [00:15<00:00,  8.12it/s]

 95%|█████████▌| 95/100 [00:15<00:00,  8.28it/s]

 97%|█████████▋| 97/100 [00:15<00:00,  9.65it/s]

 99%|█████████▉| 99/100 [00:15<00:00,  9.16it/s]

100%|██████████| 100/100 [00:16<00:00,  6.23it/s]

In [13]:
for i in tqdm(range(0, 100)):
    sequence = books.loc[books["simple_categories"] == "Nonfiction", "description"].reset_index(drop=True)[i]
    predicted_cats += [generate_predictions(sequence, fiction_categories)]
    actual_cats += ["Nonfiction"]

  0%|          | 0/100 [00:00<?, ?it/s]

  1%|          | 1/100 [00:00<00:11,  8.94it/s]

  2%|▏         | 2/100 [00:00<00:24,  3.97it/s]

  3%|▎         | 3/100 [00:00<00:24,  3.96it/s]

  5%|▌         | 5/100 [00:01<00:20,  4.56it/s]

  6%|▌         | 6/100 [00:01<00:19,  4.73it/s]

  8%|▊         | 8/100 [00:01<00:16,  5.66it/s]

 10%|█         | 10/100 [00:01<00:13,  6.62it/s]

 12%|█▏        | 12/100 [00:02<00:12,  6.98it/s]

 13%|█▎        | 13/100 [00:02<00:13,  6.31it/s]

 14%|█▍        | 14/100 [00:02<00:13,  6.14it/s]

 15%|█▌        | 15/100 [00:02<00:14,  5.98it/s]

 16%|█▌        | 16/100 [00:02<00:13,  6.31it/s]

 17%|█▋        | 17/100 [00:02<00:12,  6.44it/s]

 18%|█▊        | 18/100 [00:03<00:18,  4.47it/s]

 19%|█▉        | 19/100 [00:03<00:15,  5.22it/s]

 21%|██        | 21/100 [00:03<00:11,  7.17it/s]

 22%|██▏       | 22/100 [00:03<00:13,  5.97it/s]

 24%|██▍       | 24/100 [00:04<00:11,  6.50it/s]

 25%|██▌       | 25/100 [00:04<00:11,  6.52it/s]

 26%|██▌       | 26/100 [00:04<00:13,  5.64it/s]

 27%|██▋       | 27/100 [00:04<00:11,  6.31it/s]

 28%|██▊       | 28/100 [00:04<00:11,  6.14it/s]

 30%|███       | 30/100 [00:05<00:11,  6.15it/s]

 31%|███       | 31/100 [00:05<00:12,  5.62it/s]

 32%|███▏      | 32/100 [00:05<00:10,  6.19it/s]

 33%|███▎      | 33/100 [00:05<00:10,  6.37it/s]

 34%|███▍      | 34/100 [00:05<00:10,  6.09it/s]

 35%|███▌      | 35/100 [00:05<00:09,  6.83it/s]

 36%|███▌      | 36/100 [00:06<00:09,  6.60it/s]

 37%|███▋      | 37/100 [00:06<00:09,  6.76it/s]

 38%|███▊      | 38/100 [00:06<00:08,  7.27it/s]

 40%|████      | 40/100 [00:06<00:07,  7.54it/s]

 41%|████      | 41/100 [00:06<00:07,  7.68it/s]

 42%|████▏     | 42/100 [00:06<00:08,  6.52it/s]

 43%|████▎     | 43/100 [00:06<00:08,  7.08it/s]

 44%|████▍     | 44/100 [00:07<00:08,  6.87it/s]

 45%|████▌     | 45/100 [00:07<00:07,  7.51it/s]

 47%|████▋     | 47/100 [00:07<00:06,  8.47it/s]

 48%|████▊     | 48/100 [00:07<00:06,  7.45it/s]

 49%|████▉     | 49/100 [00:07<00:07,  6.38it/s]

 50%|█████     | 50/100 [00:07<00:07,  6.58it/s]

 51%|█████     | 51/100 [00:08<00:07,  6.74it/s]

 52%|█████▏    | 52/100 [00:08<00:07,  6.52it/s]

 53%|█████▎    | 53/100 [00:08<00:06,  7.11it/s]

 55%|█████▌    | 55/100 [00:08<00:05,  8.72it/s]

 56%|█████▌    | 56/100 [00:08<00:05,  8.08it/s]

 57%|█████▋    | 57/100 [00:08<00:05,  8.15it/s]

 59%|█████▉    | 59/100 [00:09<00:04,  9.19it/s]

 60%|██████    | 60/100 [00:09<00:06,  6.32it/s]

 61%|██████    | 61/100 [00:09<00:06,  6.17it/s]

 62%|██████▏   | 62/100 [00:09<00:07,  5.33it/s]

 63%|██████▎   | 63/100 [00:09<00:06,  5.42it/s]

 64%|██████▍   | 64/100 [00:10<00:05,  6.02it/s]

 65%|██████▌   | 65/100 [00:10<00:05,  6.04it/s]

 66%|██████▌   | 66/100 [00:10<00:06,  5.37it/s]

 67%|██████▋   | 67/100 [00:10<00:05,  5.79it/s]

 69%|██████▉   | 69/100 [00:10<00:04,  7.08it/s]

 70%|███████   | 70/100 [00:10<00:04,  7.10it/s]

 71%|███████   | 71/100 [00:11<00:04,  7.16it/s]

 72%|███████▏  | 72/100 [00:11<00:03,  7.55it/s]

 73%|███████▎  | 73/100 [00:11<00:03,  7.97it/s]

 74%|███████▍  | 74/100 [00:11<00:03,  8.21it/s]

 75%|███████▌  | 75/100 [00:11<00:03,  7.42it/s]

 76%|███████▌  | 76/100 [00:11<00:04,  4.83it/s]

 77%|███████▋  | 77/100 [00:12<00:04,  5.35it/s]

 79%|███████▉  | 79/100 [00:12<00:02,  7.48it/s]

 81%|████████  | 81/100 [00:12<00:02,  7.50it/s]

 82%|████████▏ | 82/100 [00:12<00:02,  6.07it/s]

 83%|████████▎ | 83/100 [00:12<00:02,  6.52it/s]

 84%|████████▍ | 84/100 [00:13<00:03,  4.98it/s]

 85%|████████▌ | 85/100 [00:13<00:02,  5.67it/s]

 86%|████████▌ | 86/100 [00:13<00:03,  4.26it/s]

 87%|████████▋ | 87/100 [00:14<00:04,  2.90it/s]

 88%|████████▊ | 88/100 [00:14<00:03,  3.30it/s]

 89%|████████▉ | 89/100 [00:14<00:03,  3.42it/s]

 90%|█████████ | 90/100 [00:15<00:02,  3.84it/s]

 92%|█████████▏| 92/100 [00:15<00:01,  5.62it/s]

 93%|█████████▎| 93/100 [00:15<00:01,  5.46it/s]

 94%|█████████▍| 94/100 [00:15<00:01,  5.68it/s]

 95%|█████████▌| 95/100 [00:15<00:00,  6.05it/s]

 96%|█████████▌| 96/100 [00:15<00:00,  6.09it/s]

 98%|█████████▊| 98/100 [00:16<00:00,  6.77it/s]

 99%|█████████▉| 99/100 [00:16<00:00,  7.23it/s]

100%|██████████| 100/100 [00:16<00:00,  6.14it/s]

In [14]:
predictions_df = pd.DataFrame({"actual_categories": actual_cats, "predicted_categories": predicted_cats})
predictions_df

    actual_categories predicted_categories
0             Fiction              Fiction
1             Fiction              Fiction
2             Fiction              Fiction
3             Fiction              Fiction
4             Fiction              Fiction
..                ...                  ...
195        Nonfiction           Nonfiction
196        Nonfiction           Nonfiction
197        Nonfiction           Nonfiction
198        Nonfiction           Nonfiction
199        Nonfiction           Nonfiction

[200 rows x 2 columns]

In [15]:
predictions_df["correct_prediction"] = (
    np.where(predictions_df["actual_categories"] == predictions_df["predicted_categories"], 1, 0)
)

In [ ]:
# Percentage accuracy of the BART zero-shot Fiction/Nonfiction backfill on the 200-book labelled sample.
predictions_df["correct_prediction"].sum() / len(predictions_df)

np.float64(0.8)

In [17]:
# make a subset of the database with the simple category missing
isbns = []
predicted_cats = []

missing_cats = books.loc[books["simple_categories"].isna(), ["isbn13", "description"]].reset_index(drop=True)

In [18]:
for i in tqdm(range(0, len(missing_cats))):
    sequence = missing_cats["description"][i]
    predicted_cats += [generate_predictions(sequence, fiction_categories)]
    isbns += [missing_cats["isbn13"][i]]

  0%|          | 0/30196 [00:00<?, ?it/s]

  0%|          | 1/30196 [00:00<1:25:48,  5.86it/s]

  0%|          | 2/30196 [00:00<1:19:01,  6.37it/s]

  0%|          | 3/30196 [00:00<1:08:04,  7.39it/s]

  0%|          | 4/30196 [00:00<1:14:03,  6.79it/s]

  0%|          | 5/30196 [00:00<1:34:28,  5.33it/s]

  0%|          | 6/30196 [00:00<1:25:32,  5.88it/s]

  0%|          | 8/30196 [00:01<1:06:31,  7.56it/s]

  0%|          | 9/30196 [00:01<1:06:28,  7.57it/s]

  0%|          | 10/30196 [00:01<1:19:06,  6.36it/s]

  0%|          | 12/30196 [00:01<1:01:13,  8.22it/s]

  0%|          | 13/30196 [00:01<59:30,  8.45it/s]

  0%|          | 14/30196 [00:01<1:06:34,  7.56it/s]

  0%|          | 16/30196 [00:02<55:13,  9.11it/s]

  0%|          | 18/30196 [00:02<1:03:17,  7.95it/s]

  0%|          | 19/30196 [00:02<1:01:33,  8.17it/s]

  0%|          | 20/30196 [00:02<1:00:05,  8.37it/s]

  0%|          | 21/30196 [00:03<1:32:18,  5.45it/s]

  0%|          | 23/30196 [00:03<1:13:09,  6.87it/s]

  0%|          | 25/30196 [00:03<1:00:28,  8.32it/s]

  0%|          | 27/30196 [00:03<54:35,  9.21it/s]

  0%|          | 29/30196 [00:03<54:19,  9.26it/s]

  0%|          | 31/30196 [00:04<1:05:46,  7.64it/s]

  0%|          | 33/30196 [00:04<59:35,  8.44it/s]

  0%|          | 34/30196 [00:04<1:07:56,  7.40it/s]

  0%|          | 36/30196 [00:04<1:10:12,  7.16it/s]

  0%|          | 38/30196 [00:05<1:14:43,  6.73it/s]

  0%|          | 39/30196 [00:05<1:18:57,  6.37it/s]

  0%|          | 41/30196 [00:05<1:11:27,  7.03it/s]

  0%|          | 43/30196 [00:05<1:06:19,  7.58it/s]

  0%|          | 44/30196 [00:05<1:10:47,  7.10it/s]

  0%|          | 45/30196 [00:06<1:06:47,  7.52it/s]

  0%|          | 46/30196 [00:06<1:09:39,  7.21it/s]

  0%|          | 47/30196 [00:06<1:13:17,  6.86it/s]

  0%|          | 49/30196 [00:06<1:12:13,  6.96it/s]

  0%|          | 50/30196 [00:06<1:15:29,  6.66it/s]

  0%|          | 51/30196 [00:07<2:03:39,  4.06it/s]

  0%|          | 52/30196 [00:07<1:56:22,  4.32it/s]

  0%|          | 53/30196 [00:07<1:43:20,  4.86it/s]

  0%|          | 54/30196 [00:07<1:37:45,  5.14it/s]

  0%|          | 55/30196 [00:07<1:24:54,  5.92it/s]

  0%|          | 56/30196 [00:08<1:21:41,  6.15it/s]

  0%|          | 58/30196 [00:08<1:02:34,  8.03it/s]

  0%|          | 59/30196 [00:08<1:08:40,  7.31it/s]

  0%|          | 61/30196 [00:08<1:05:06,  7.71it/s]

  0%|          | 63/30196 [00:08<50:50,  9.88it/s]

  0%|          | 65/30196 [00:09<57:18,  8.76it/s]

  0%|          | 67/30196 [00:09<49:45, 10.09it/s]

  0%|          | 69/30196 [00:09<1:09:10,  7.26it/s]

  0%|          | 70/30196 [00:09<1:12:39,  6.91it/s]

  0%|          | 71/30196 [00:10<1:19:23,  6.32it/s]

  0%|          | 72/30196 [00:10<1:16:29,  6.56it/s]

  0%|          | 73/30196 [00:10<1:10:11,  7.15it/s]

  0%|          | 74/30196 [00:10<1:07:02,  7.49it/s]

  0%|          | 75/30196 [00:10<1:07:27,  7.44it/s]

  0%|          | 76/30196 [00:10<1:03:53,  7.86it/s]

  0%|          | 77/30196 [00:10<1:11:37,  7.01it/s]

  0%|          | 78/30196 [00:10<1:07:44,  7.41it/s]

  0%|          | 79/30196 [00:11<1:11:08,  7.06it/s]

  0%|          | 81/30196 [00:11<1:04:22,  7.80it/s]

  0%|          | 82/30196 [00:11<1:12:27,  6.93it/s]

  0%|          | 84/30196 [00:11<56:09,  8.94it/s]

  0%|          | 86/30196 [00:11<50:45,  9.89it/s]

  0%|          | 88/30196 [00:12<1:04:56,  7.73it/s]

  0%|          | 89/30196 [00:12<1:06:06,  7.59it/s]

  0%|          | 90/30196 [00:12<1:03:49,  7.86it/s]

  0%|          | 91/30196 [00:12<1:08:52,  7.28it/s]

  0%|          | 92/30196 [00:12<1:12:58,  6.88it/s]

  0%|          | 94/30196 [00:12<55:40,  9.01it/s]

  0%|          | 96/30196 [00:13<1:04:27,  7.78it/s]

  0%|          | 97/30196 [00:13<1:02:00,  8.09it/s]

  0%|          | 98/30196 [00:13<1:10:12,  7.14it/s]

  0%|          | 99/30196 [00:13<1:13:57,  6.78it/s]

  0%|          | 100/30196 [00:13<1:09:06,  7.26it/s]

  0%|          | 101/30196 [00:13<1:14:04,  6.77it/s]

  0%|          | 102/30196 [00:14<1:51:46,  4.49it/s]

  0%|          | 104/30196 [00:14<1:29:56,  5.58it/s]

  0%|          | 105/30196 [00:14<1:29:10,  5.62it/s]

  0%|          | 106/30196 [00:14<1:28:28,  5.67it/s]

  0%|          | 107/30196 [00:15<1:22:24,  6.08it/s]

  0%|          | 108/30196 [00:15<1:19:14,  6.33it/s]

  0%|          | 109/30196 [00:15<1:17:55,  6.43it/s]

  0%|          | 111/30196 [00:15<1:03:25,  7.91it/s]

  0%|          | 113/30196 [00:15<52:15,  9.59it/s]

  0%|          | 114/30196 [00:15<55:39,  9.01it/s]

  0%|          | 115/30196 [00:16<1:15:32,  6.64it/s]

  0%|          | 117/30196 [00:16<1:00:18,  8.31it/s]

  0%|          | 119/30196 [00:16<54:43,  9.16it/s]

  0%|          | 121/30196 [00:16<45:59, 10.90it/s]

  0%|          | 123/30196 [00:16<54:28,  9.20it/s]

  0%|          | 125/30196 [00:17<49:42, 10.08it/s]

  0%|          | 127/30196 [00:17<47:09, 10.63it/s]

  0%|          | 129/30196 [00:17<53:23,  9.38it/s]

  0%|          | 131/30196 [00:17<56:48,  8.82it/s]

  0%|          | 132/30196 [00:17<1:04:12,  7.80it/s]

  0%|          | 134/30196 [00:18<1:02:46,  7.98it/s]

  0%|          | 135/30196 [00:18<1:01:23,  8.16it/s]

  0%|          | 137/30196 [00:18<1:11:46,  6.98it/s]

  0%|          | 138/30196 [00:18<1:08:24,  7.32it/s]

  0%|          | 140/30196 [00:18<52:41,  9.51it/s]

  0%|          | 142/30196 [00:18<44:35, 11.23it/s]

  0%|          | 144/30196 [00:19<42:04, 11.91it/s]

  0%|          | 146/30196 [00:19<51:02,  9.81it/s]

  0%|          | 148/30196 [00:19<46:29, 10.77it/s]

  0%|          | 150/30196 [00:19<49:32, 10.11it/s]

  1%|          | 152/30196 [00:20<1:02:51,  7.97it/s]

  1%|          | 153/30196 [00:20<1:01:32,  8.14it/s]

  1%|          | 154/30196 [00:20<1:02:36,  8.00it/s]

  1%|          | 156/30196 [00:20<1:01:17,  8.17it/s]

  1%|          | 158/30196 [00:20<1:14:25,  6.73it/s]

  1%|          | 160/30196 [00:21<1:01:42,  8.11it/s]

  1%|          | 161/30196 [00:21<1:20:48,  6.20it/s]

  1%|          | 162/30196 [00:21<1:16:02,  6.58it/s]

  1%|          | 164/30196 [00:21<1:04:52,  7.72it/s]

  1%|          | 165/30196 [00:21<1:09:46,  7.17it/s]

  1%|          | 166/30196 [00:22<1:13:01,  6.85it/s]

  1%|          | 167/30196 [00:22<1:11:11,  7.03it/s]

  1%|          | 168/30196 [00:22<1:18:56,  6.34it/s]

  1%|          | 170/30196 [00:22<1:07:17,  7.44it/s]

  1%|          | 172/30196 [00:22<1:02:41,  7.98it/s]

  1%|          | 173/30196 [00:22<1:03:52,  7.83it/s]

  1%|          | 174/30196 [00:23<1:07:17,  7.44it/s]

  1%|          | 175/30196 [00:23<1:08:31,  7.30it/s]

  1%|          | 177/30196 [00:23<1:00:14,  8.30it/s]

  1%|          | 178/30196 [00:24<1:54:59,  4.35it/s]

  1%|          | 179/30196 [00:24<1:43:58,  4.81it/s]

  1%|          | 180/30196 [00:24<1:43:59,  4.81it/s]

  1%|          | 181/30196 [00:24<1:37:55,  5.11it/s]

  1%|          | 182/30196 [00:24<1:42:28,  4.88it/s]

  1%|          | 183/30196 [00:24<1:29:00,  5.62it/s]

  1%|          | 184/30196 [00:25<1:28:58,  5.62it/s]

  1%|          | 185/30196 [00:25<1:24:26,  5.92it/s]

  1%|          | 187/30196 [00:25<1:15:54,  6.59it/s]

  1%|          | 190/30196 [00:25<55:22,  9.03it/s]

  1%|          | 191/30196 [00:26<1:16:56,  6.50it/s]

  1%|          | 192/30196 [00:26<1:14:28,  6.71it/s]

  1%|          | 194/30196 [00:26<1:02:55,  7.95it/s]

  1%|          | 195/30196 [00:26<1:00:36,  8.25it/s]

  1%|          | 196/30196 [00:26<1:03:38,  7.86it/s]

  1%|          | 197/30196 [00:26<1:01:25,  8.14it/s]

  1%|          | 198/30196 [00:26<1:02:30,  8.00it/s]

  1%|          | 200/30196 [00:27<1:02:49,  7.96it/s]

  1%|          | 201/30196 [00:27<1:05:24,  7.64it/s]

  1%|          | 202/30196 [00:27<1:18:57,  6.33it/s]

  1%|          | 204/30196 [00:27<1:33:05,  5.37it/s]

  1%|          | 206/30196 [00:28<1:12:36,  6.88it/s]

  1%|          | 208/30196 [00:28<1:06:15,  7.54it/s]

  1%|          | 210/30196 [00:28<56:16,  8.88it/s]

  1%|          | 212/30196 [00:28<57:09,  8.74it/s]

  1%|          | 213/30196 [00:28<59:44,  8.36it/s]

  1%|          | 214/30196 [00:28<58:11,  8.59it/s]

  1%|          | 215/30196 [00:29<1:04:43,  7.72it/s]

  1%|          | 217/30196 [00:29<1:09:57,  7.14it/s]

  1%|          | 218/30196 [00:29<1:09:29,  7.19it/s]

  1%|          | 219/30196 [00:29<1:09:01,  7.24it/s]

  1%|          | 220/30196 [00:29<1:10:17,  7.11it/s]

  1%|          | 221/30196 [00:29<1:06:05,  7.56it/s]

  1%|          | 223/30196 [00:30<59:17,  8.42it/s]

  1%|          | 224/30196 [00:30<1:05:56,  7.58it/s]

  1%|          | 225/30196 [00:30<1:03:15,  7.90it/s]

  1%|          | 226/30196 [00:30<1:05:58,  7.57it/s]

  1%|          | 227/30196 [00:30<1:02:10,  8.03it/s]

  1%|          | 229/30196 [00:30<1:00:40,  8.23it/s]

  1%|          | 230/30196 [00:31<58:43,  8.51it/s]

  1%|          | 232/30196 [00:31<59:02,  8.46it/s]

  1%|          | 233/30196 [00:31<1:01:12,  8.16it/s]

  1%|          | 234/30196 [00:31<1:02:10,  8.03it/s]

  1%|          | 236/30196 [00:31<57:48,  8.64it/s]

  1%|          | 237/30196 [00:31<57:12,  8.73it/s]

  1%|          | 238/30196 [00:31<56:31,  8.83it/s]

  1%|          | 239/30196 [00:32<1:04:48,  7.70it/s]

  1%|          | 241/30196 [00:32<53:38,  9.31it/s]

  1%|          | 242/30196 [00:32<58:13,  8.57it/s]

  1%|          | 243/30196 [00:32<56:43,  8.80it/s]

  1%|          | 245/30196 [00:32<48:35, 10.27it/s]

  1%|          | 247/30196 [00:32<52:42,  9.47it/s]

  1%|          | 249/30196 [00:33<1:05:50,  7.58it/s]

  1%|          | 250/30196 [00:33<1:10:30,  7.08it/s]

  1%|          | 251/30196 [00:33<1:07:03,  7.44it/s]

  1%|          | 252/30196 [00:33<1:14:09,  6.73it/s]

  1%|          | 253/30196 [00:33<1:11:53,  6.94it/s]

  1%|          | 255/30196 [00:34<1:00:18,  8.27it/s]

  1%|          | 257/30196 [00:34<1:00:18,  8.27it/s]

  1%|          | 258/30196 [00:34<1:05:23,  7.63it/s]

  1%|          | 259/30196 [00:34<1:05:36,  7.60it/s]

  1%|          | 261/30196 [00:34<49:40, 10.04it/s]

  1%|          | 263/30196 [00:34<42:27, 11.75it/s]

  1%|          | 265/30196 [00:35<49:27, 10.09it/s]

  1%|          | 267/30196 [00:35<53:23,  9.34it/s]

  1%|          | 269/30196 [00:35<56:11,  8.88it/s]

  1%|          | 270/30196 [00:35<55:09,  9.04it/s]

  1%|          | 272/30196 [00:35<56:57,  8.76it/s]

  1%|          | 273/30196 [00:36<56:32,  8.82it/s]

  1%|          | 275/30196 [00:36<45:17, 11.01it/s]

  1%|          | 277/30196 [00:36<51:08,  9.75it/s]

  1%|          | 279/30196 [00:37<1:31:54,  5.43it/s]

  1%|          | 280/30196 [00:37<1:29:17,  5.58it/s]

  1%|          | 281/30196 [00:37<1:25:14,  5.85it/s]

  1%|          | 283/30196 [00:37<1:18:12,  6.37it/s]

  1%|          | 284/30196 [00:37<1:20:43,  6.18it/s]

  1%|          | 285/30196 [00:38<1:22:16,  6.06it/s]

  1%|          | 287/30196 [00:38<1:05:32,  7.60it/s]

  1%|          | 289/30196 [00:38<58:02,  8.59it/s]

  1%|          | 290/30196 [00:38<59:29,  8.38it/s]

  1%|          | 291/30196 [00:38<1:10:02,  7.12it/s]

  1%|          | 292/30196 [00:38<1:09:28,  7.17it/s]

  1%|          | 293/30196 [00:39<1:31:13,  5.46it/s]

  1%|          | 294/30196 [00:39<1:21:21,  6.12it/s]

  1%|          | 295/30196 [00:39<1:13:46,  6.76it/s]

  1%|          | 296/30196 [00:39<1:07:46,  7.35it/s]

  1%|          | 297/30196 [00:39<1:07:38,  7.37it/s]

  1%|          | 298/30196 [00:39<1:03:07,  7.89it/s]

  1%|          | 300/30196 [00:39<53:10,  9.37it/s]

  1%|          | 302/30196 [00:40<53:25,  9.33it/s]

  1%|          | 304/30196 [00:40<53:05,  9.38it/s]

  1%|          | 305/30196 [00:40<59:16,  8.40it/s]

  1%|          | 306/30196 [00:40<1:02:25,  7.98it/s]

  1%|          | 307/30196 [00:40<1:14:00,  6.73it/s]

  1%|          | 308/30196 [00:41<1:33:58,  5.30it/s]

  1%|          | 309/30196 [00:41<1:23:26,  5.97it/s]

  1%|          | 310/30196 [00:41<1:18:18,  6.36it/s]

  1%|          | 311/30196 [00:41<1:18:11,  6.37it/s]

  1%|          | 313/30196 [00:41<55:27,  8.98it/s]

  1%|          | 315/30196 [00:41<49:58,  9.96it/s]

  1%|          | 317/30196 [00:42<58:33,  8.50it/s]

  1%|          | 318/30196 [00:42<59:56,  8.31it/s]

  1%|          | 319/30196 [00:42<1:04:59,  7.66it/s]

  1%|          | 321/30196 [00:42<52:52,  9.42it/s]

  1%|          | 323/30196 [00:42<1:06:26,  7.49it/s]

  1%|          | 325/30196 [00:43<59:55,  8.31it/s]

  1%|          | 327/30196 [00:43<51:20,  9.70it/s]

  1%|          | 329/30196 [00:43<50:25,  9.87it/s]

  1%|          | 331/30196 [00:43<56:41,  8.78it/s]

  1%|          | 332/30196 [00:43<55:55,  8.90it/s]

  1%|          | 334/30196 [00:44<56:22,  8.83it/s]

  1%|          | 335/30196 [00:44<1:13:16,  6.79it/s]

  1%|          | 336/30196 [00:44<1:12:02,  6.91it/s]

  1%|          | 338/30196 [00:44<1:24:36,  5.88it/s]

  1%|          | 339/30196 [00:45<1:39:35,  5.00it/s]

  1%|          | 340/30196 [00:45<1:28:58,  5.59it/s]

  1%|          | 341/30196 [00:45<1:27:43,  5.67it/s]

  1%|          | 342/30196 [00:45<1:23:34,  5.95it/s]

  1%|          | 344/30196 [00:45<1:11:04,  7.00it/s]

  1%|          | 345/30196 [00:45<1:06:43,  7.46it/s]

  1%|          | 346/30196 [00:46<1:08:16,  7.29it/s]

  1%|          | 348/30196 [00:46<1:04:58,  7.66it/s]

  1%|          | 350/30196 [00:46<58:11,  8.55it/s]

  1%|          | 351/30196 [00:46<1:01:29,  8.09it/s]

  1%|          | 353/30196 [00:47<1:33:37,  5.31it/s]

  1%|          | 355/30196 [00:47<1:23:22,  5.97it/s]

  1%|          | 357/30196 [00:47<1:08:20,  7.28it/s]

  1%|          | 358/30196 [00:47<1:20:48,  6.15it/s]

  1%|          | 359/30196 [00:48<1:14:50,  6.64it/s]

  1%|          | 360/30196 [00:48<1:10:27,  7.06it/s]

  1%|          | 361/30196 [00:48<1:20:54,  6.15it/s]

  1%|          | 362/30196 [00:48<1:14:03,  6.71it/s]

  1%|          | 364/30196 [00:48<58:13,  8.54it/s]

  1%|          | 365/30196 [00:48<1:08:47,  7.23it/s]

  1%|          | 366/30196 [00:49<1:18:21,  6.35it/s]

  1%|          | 368/30196 [00:49<1:14:54,  6.64it/s]

  1%|          | 369/30196 [00:49<1:13:44,  6.74it/s]

  1%|          | 371/30196 [00:49<1:09:57,  7.11it/s]

  1%|          | 372/30196 [00:50<1:31:34,  5.43it/s]

  1%|          | 373/30196 [00:50<1:31:00,  5.46it/s]

  1%|          | 374/30196 [00:50<1:57:07,  4.24it/s]

  1%|          | 375/30196 [00:50<1:45:25,  4.71it/s]

  1%|          | 376/30196 [00:50<1:34:46,  5.24it/s]

  1%|          | 377/30196 [00:51<1:26:57,  5.72it/s]

  1%|▏         | 379/30196 [00:51<1:16:17,  6.51it/s]

  1%|▏         | 380/30196 [00:51<1:13:26,  6.77it/s]

  1%|▏         | 382/30196 [00:51<1:03:12,  7.86it/s]

  1%|▏         | 383/30196 [00:51<1:04:38,  7.69it/s]

  1%|▏         | 384/30196 [00:52<1:09:16,  7.17it/s]

  1%|▏         | 386/30196 [00:52<1:03:27,  7.83it/s]

  1%|▏         | 387/30196 [00:52<1:19:12,  6.27it/s]

  1%|▏         | 389/30196 [00:52<1:03:37,  7.81it/s]

  1%|▏         | 391/30196 [00:52<52:57,  9.38it/s]

  1%|▏         | 393/30196 [00:52<44:55, 11.05it/s]

  1%|▏         | 395/30196 [00:53<51:36,  9.63it/s]

  1%|▏         | 397/30196 [00:53<1:08:10,  7.28it/s]

  1%|▏         | 398/30196 [00:53<1:07:36,  7.35it/s]

  1%|▏         | 400/30196 [00:53<1:06:35,  7.46it/s]

  1%|▏         | 402/30196 [00:54<1:00:40,  8.18it/s]

  1%|▏         | 403/30196 [00:54<1:05:59,  7.52it/s]

  1%|▏         | 404/30196 [00:54<1:14:24,  6.67it/s]

  1%|▏         | 405/30196 [00:54<1:23:17,  5.96it/s]

  1%|▏         | 407/30196 [00:55<1:13:45,  6.73it/s]

  1%|▏         | 408/30196 [00:55<1:20:22,  6.18it/s]

  1%|▏         | 409/30196 [00:55<1:39:02,  5.01it/s]

  1%|▏         | 410/30196 [00:55<1:31:40,  5.41it/s]

  1%|▏         | 412/30196 [00:56<1:35:30,  5.20it/s]

  1%|▏         | 413/30196 [00:56<1:28:48,  5.59it/s]

  1%|▏         | 414/30196 [00:56<1:27:10,  5.69it/s]

  1%|▏         | 416/30196 [00:56<1:30:31,  5.48it/s]

  1%|▏         | 417/30196 [00:57<1:38:58,  5.01it/s]

  1%|▏         | 419/30196 [00:57<1:18:40,  6.31it/s]

  1%|▏         | 421/30196 [00:57<1:03:41,  7.79it/s]

  1%|▏         | 422/30196 [00:57<1:07:53,  7.31it/s]

  1%|▏         | 424/30196 [00:57<54:15,  9.14it/s]

  1%|▏         | 426/30196 [00:57<54:42,  9.07it/s]

  1%|▏         | 427/30196 [00:58<1:01:05,  8.12it/s]

  1%|▏         | 428/30196 [00:58<59:33,  8.33it/s]

  1%|▏         | 429/30196 [00:58<58:21,  8.50it/s]

  1%|▏         | 431/30196 [00:58<56:59,  8.70it/s]

  1%|▏         | 432/30196 [00:58<59:04,  8.40it/s]

  1%|▏         | 434/30196 [00:58<54:25,  9.11it/s]

  1%|▏         | 436/30196 [00:58<46:32, 10.66it/s]

  1%|▏         | 438/30196 [00:59<50:59,  9.72it/s]

  1%|▏         | 440/30196 [00:59<43:06, 11.50it/s]

  1%|▏         | 442/30196 [00:59<46:54, 10.57it/s]

  1%|▏         | 444/30196 [00:59<1:05:43,  7.54it/s]

  1%|▏         | 446/30196 [01:00<59:03,  8.40it/s]

  1%|▏         | 448/30196 [01:00<59:51,  8.28it/s]

  1%|▏         | 449/30196 [01:00<58:52,  8.42it/s]

  1%|▏         | 450/30196 [01:00<1:11:06,  6.97it/s]

  1%|▏         | 452/30196 [01:00<59:35,  8.32it/s]

  2%|▏         | 453/30196 [01:01<1:01:00,  8.12it/s]

  2%|▏         | 454/30196 [01:01<1:06:48,  7.42it/s]

  2%|▏         | 455/30196 [01:01<1:22:19,  6.02it/s]

  2%|▏         | 456/30196 [01:01<1:36:05,  5.16it/s]

  2%|▏         | 457/30196 [01:01<1:38:11,  5.05it/s]

  2%|▏         | 458/30196 [01:02<1:52:46,  4.40it/s]

  2%|▏         | 460/30196 [01:02<1:14:06,  6.69it/s]

  2%|▏         | 462/30196 [01:02<1:09:52,  7.09it/s]

  2%|▏         | 464/30196 [01:02<1:02:31,  7.92it/s]

  2%|▏         | 465/30196 [01:02<1:03:27,  7.81it/s]

  2%|▏         | 466/30196 [01:03<1:07:48,  7.31it/s]

  2%|▏         | 468/30196 [01:03<58:32,  8.46it/s]

  2%|▏         | 470/30196 [01:03<49:42,  9.97it/s]

  2%|▏         | 472/30196 [01:03<50:43,  9.77it/s]

  2%|▏         | 474/30196 [01:03<56:30,  8.77it/s]

  2%|▏         | 476/30196 [01:04<56:12,  8.81it/s]

  2%|▏         | 478/30196 [01:04<54:55,  9.02it/s]

  2%|▏         | 480/30196 [01:04<45:44, 10.83it/s]

  2%|▏         | 482/30196 [01:04<48:33, 10.20it/s]

  2%|▏         | 484/30196 [01:05<58:46,  8.42it/s]

  2%|▏         | 485/30196 [01:05<1:12:17,  6.85it/s]

  2%|▏         | 486/30196 [01:05<1:11:50,  6.89it/s]

  2%|▏         | 487/30196 [01:05<1:11:20,  6.94it/s]

  2%|▏         | 488/30196 [01:05<1:09:47,  7.09it/s]

  2%|▏         | 489/30196 [01:05<1:14:44,  6.62it/s]

  2%|▏         | 491/30196 [01:06<1:07:53,  7.29it/s]

  2%|▏         | 493/30196 [01:06<53:43,  9.22it/s]

  2%|▏         | 495/30196 [01:06<59:44,  8.29it/s]

  2%|▏         | 496/30196 [01:06<1:00:40,  8.16it/s]

  2%|▏         | 498/30196 [01:06<53:31,  9.25it/s]

  2%|▏         | 499/30196 [01:06<53:46,  9.20it/s]

  2%|▏         | 500/30196 [01:07<56:40,  8.73it/s]

  2%|▏         | 501/30196 [01:07<1:14:38,  6.63it/s]

  2%|▏         | 502/30196 [01:07<1:34:05,  5.26it/s]

  2%|▏         | 504/30196 [01:07<1:07:58,  7.28it/s]

  2%|▏         | 505/30196 [01:07<1:16:49,  6.44it/s]

  2%|▏         | 506/30196 [01:08<1:14:58,  6.60it/s]

  2%|▏         | 507/30196 [01:08<1:15:36,  6.55it/s]

  2%|▏         | 509/30196 [01:08<57:42,  8.57it/s]

  2%|▏         | 510/30196 [01:08<59:20,  8.34it/s]

  2%|▏         | 512/30196 [01:08<53:12,  9.30it/s]

  2%|▏         | 514/30196 [01:08<48:43, 10.15it/s]

  2%|▏         | 516/30196 [01:09<49:30,  9.99it/s]

  2%|▏         | 518/30196 [01:09<45:48, 10.80it/s]

  2%|▏         | 520/30196 [01:09<55:20,  8.94it/s]

  2%|▏         | 521/30196 [01:09<58:34,  8.44it/s]

  2%|▏         | 522/30196 [01:09<57:10,  8.65it/s]

  2%|▏         | 523/30196 [01:09<1:00:29,  8.17it/s]

  2%|▏         | 524/30196 [01:10<1:03:43,  7.76it/s]

  2%|▏         | 525/30196 [01:10<1:28:48,  5.57it/s]

  2%|▏         | 526/30196 [01:10<1:22:08,  6.02it/s]

  2%|▏         | 527/30196 [01:10<1:17:19,  6.39it/s]

  2%|▏         | 528/30196 [01:10<1:19:05,  6.25it/s]

  2%|▏         | 529/30196 [01:11<2:03:01,  4.02it/s]

  2%|▏         | 531/30196 [01:11<1:22:12,  6.01it/s]

  2%|▏         | 532/30196 [01:11<1:14:50,  6.61it/s]

  2%|▏         | 533/30196 [01:11<1:22:37,  5.98it/s]

  2%|▏         | 534/30196 [01:12<1:35:04,  5.20it/s]

  2%|▏         | 535/30196 [01:12<1:26:35,  5.71it/s]

  2%|▏         | 536/30196 [01:12<1:20:19,  6.15it/s]

  2%|▏         | 537/30196 [01:12<1:17:18,  6.39it/s]

  2%|▏         | 538/30196 [01:12<1:18:59,  6.26it/s]

  2%|▏         | 540/30196 [01:12<1:00:04,  8.23it/s]

  2%|▏         | 541/30196 [01:12<1:01:41,  8.01it/s]

  2%|▏         | 542/30196 [01:13<1:04:41,  7.64it/s]

  2%|▏         | 543/30196 [01:13<1:14:53,  6.60it/s]

  2%|▏         | 544/30196 [01:13<1:09:08,  7.15it/s]

  2%|▏         | 545/30196 [01:13<1:04:59,  7.60it/s]

  2%|▏         | 547/30196 [01:13<53:47,  9.19it/s]

  2%|▏         | 549/30196 [01:13<48:23, 10.21it/s]

  2%|▏         | 551/30196 [01:14<51:22,  9.62it/s]

  2%|▏         | 553/30196 [01:14<47:29, 10.40it/s]

  2%|▏         | 555/30196 [01:14<49:06, 10.06it/s]

  2%|▏         | 557/30196 [01:14<57:18,  8.62it/s]

  2%|▏         | 558/30196 [01:14<58:44,  8.41it/s]

  2%|▏         | 559/30196 [01:15<1:05:05,  7.59it/s]

  2%|▏         | 560/30196 [01:15<1:09:14,  7.13it/s]

  2%|▏         | 562/30196 [01:15<1:01:23,  8.04it/s]

  2%|▏         | 563/30196 [01:15<59:47,  8.26it/s]

  2%|▏         | 564/30196 [01:15<1:25:03,  5.81it/s]

  2%|▏         | 565/30196 [01:15<1:20:18,  6.15it/s]

  2%|▏         | 566/30196 [01:16<1:16:33,  6.45it/s]

  2%|▏         | 567/30196 [01:16<1:13:25,  6.73it/s]

  2%|▏         | 568/30196 [01:16<1:16:54,  6.42it/s]

  2%|▏         | 569/30196 [01:16<1:37:18,  5.07it/s]

  2%|▏         | 570/30196 [01:16<1:24:51,  5.82it/s]

  2%|▏         | 571/30196 [01:16<1:24:26,  5.85it/s]

  2%|▏         | 572/30196 [01:17<1:18:36,  6.28it/s]

  2%|▏         | 573/30196 [01:17<1:11:23,  6.92it/s]

  2%|▏         | 575/30196 [01:17<52:10,  9.46it/s]

  2%|▏         | 577/30196 [01:17<55:49,  8.84it/s]

  2%|▏         | 578/30196 [01:17<57:57,  8.52it/s]

  2%|▏         | 580/30196 [01:18<1:02:50,  7.85it/s]

  2%|▏         | 581/30196 [01:18<1:07:47,  7.28it/s]

  2%|▏         | 583/30196 [01:18<1:00:16,  8.19it/s]

  2%|▏         | 585/30196 [01:18<1:01:58,  7.96it/s]

  2%|▏         | 586/30196 [01:19<1:30:18,  5.46it/s]

  2%|▏         | 588/30196 [01:19<1:15:07,  6.57it/s]

  2%|▏         | 589/30196 [01:19<1:17:09,  6.39it/s]

  2%|▏         | 590/30196 [01:19<1:11:22,  6.91it/s]

  2%|▏         | 591/30196 [01:19<1:07:08,  7.35it/s]

  2%|▏         | 593/30196 [01:19<57:54,  8.52it/s]

  2%|▏         | 595/30196 [01:20<56:28,  8.74it/s]

  2%|▏         | 597/30196 [01:20<45:45, 10.78it/s]

  2%|▏         | 599/30196 [01:20<39:11, 12.59it/s]

  2%|▏         | 602/30196 [01:20<34:23, 14.34it/s]

  2%|▏         | 604/30196 [01:20<57:01,  8.65it/s]

  2%|▏         | 606/30196 [01:21<55:45,  8.84it/s]

  2%|▏         | 608/30196 [01:21<1:03:04,  7.82it/s]

  2%|▏         | 609/30196 [01:21<1:06:42,  7.39it/s]

  2%|▏         | 610/30196 [01:21<1:06:37,  7.40it/s]

  2%|▏         | 611/30196 [01:22<1:27:21,  5.64it/s]

  2%|▏         | 613/30196 [01:22<1:06:24,  7.42it/s]

  2%|▏         | 614/30196 [01:22<1:10:06,  7.03it/s]

  2%|▏         | 615/30196 [01:22<1:14:07,  6.65it/s]

  2%|▏         | 616/30196 [01:22<1:13:38,  6.69it/s]

  2%|▏         | 618/30196 [01:22<1:07:06,  7.35it/s]

  2%|▏         | 619/30196 [01:23<1:06:23,  7.43it/s]

  2%|▏         | 620/30196 [01:23<1:11:05,  6.93it/s]

  2%|▏         | 621/30196 [01:23<1:14:52,  6.58it/s]

  2%|▏         | 622/30196 [01:23<1:14:16,  6.64it/s]

  2%|▏         | 624/30196 [01:23<58:01,  8.49it/s]

  2%|▏         | 625/30196 [01:23<1:03:31,  7.76it/s]

  2%|▏         | 626/30196 [01:23<1:01:15,  8.05it/s]

  2%|▏         | 628/30196 [01:24<51:05,  9.64it/s]

  2%|▏         | 629/30196 [01:24<55:23,  8.90it/s]

  2%|▏         | 630/30196 [01:24<1:09:48,  7.06it/s]

  2%|▏         | 631/30196 [01:24<1:10:30,  6.99it/s]

  2%|▏         | 633/30196 [01:25<1:31:26,  5.39it/s]

  2%|▏         | 634/30196 [01:25<1:27:07,  5.65it/s]

  2%|▏         | 636/30196 [01:25<1:09:59,  7.04it/s]

  2%|▏         | 637/30196 [01:25<1:08:41,  7.17it/s]

  2%|▏         | 639/30196 [01:25<1:00:30,  8.14it/s]

  2%|▏         | 640/30196 [01:25<1:04:00,  7.70it/s]

  2%|▏         | 641/30196 [01:26<1:01:41,  7.98it/s]

  2%|▏         | 642/30196 [01:26<1:02:18,  7.90it/s]

  2%|▏         | 643/30196 [01:26<1:00:10,  8.19it/s]

  2%|▏         | 644/30196 [01:26<1:19:40,  6.18it/s]

  2%|▏         | 645/30196 [01:26<1:12:35,  6.79it/s]

  2%|▏         | 646/30196 [01:26<1:15:40,  6.51it/s]

  2%|▏         | 648/30196 [01:27<1:11:24,  6.90it/s]

  2%|▏         | 649/30196 [01:27<1:43:45,  4.75it/s]

  2%|▏         | 651/30196 [01:27<1:19:58,  6.16it/s]

  2%|▏         | 652/30196 [01:27<1:18:11,  6.30it/s]

  2%|▏         | 653/30196 [01:27<1:16:52,  6.41it/s]

  2%|▏         | 654/30196 [01:28<1:14:54,  6.57it/s]

  2%|▏         | 655/30196 [01:28<1:14:09,  6.64it/s]

  2%|▏         | 657/30196 [01:28<59:17,  8.30it/s]

  2%|▏         | 659/30196 [01:28<54:34,  9.02it/s]

  2%|▏         | 661/30196 [01:28<1:01:56,  7.95it/s]

  2%|▏         | 662/30196 [01:29<1:04:59,  7.57it/s]

  2%|▏         | 663/30196 [01:29<1:07:24,  7.30it/s]

  2%|▏         | 665/30196 [01:29<57:05,  8.62it/s]

  2%|▏         | 666/30196 [01:29<56:29,  8.71it/s]

  2%|▏         | 668/30196 [01:29<51:41,  9.52it/s]

  2%|▏         | 669/30196 [01:29<54:27,  9.04it/s]

  2%|▏         | 670/30196 [01:29<57:20,  8.58it/s]

  2%|▏         | 672/30196 [01:30<44:30, 11.06it/s]

  2%|▏         | 674/30196 [01:30<51:21,  9.58it/s]

  2%|▏         | 676/30196 [01:30<58:29,  8.41it/s]

  2%|▏         | 678/30196 [01:30<52:34,  9.36it/s]

  2%|▏         | 680/30196 [01:31<1:00:24,  8.14it/s]

  2%|▏         | 681/30196 [01:31<1:20:05,  6.14it/s]

  2%|▏         | 683/30196 [01:31<1:28:47,  5.54it/s]

  2%|▏         | 684/30196 [01:32<1:24:14,  5.84it/s]

  2%|▏         | 685/30196 [01:32<1:21:29,  6.04it/s]

  2%|▏         | 686/30196 [01:32<1:16:08,  6.46it/s]

  2%|▏         | 688/30196 [01:32<1:13:11,  6.72it/s]

  2%|▏         | 689/30196 [01:32<1:08:25,  7.19it/s]

  2%|▏         | 691/30196 [01:32<1:03:11,  7.78it/s]

  2%|▏         | 692/30196 [01:32<1:01:14,  8.03it/s]

  2%|▏         | 693/30196 [01:33<1:03:04,  7.80it/s]

  2%|▏         | 695/30196 [01:33<1:03:19,  7.76it/s]

  2%|▏         | 698/30196 [01:33<48:47, 10.08it/s]

  2%|▏         | 700/30196 [01:33<49:51,  9.86it/s]

  2%|▏         | 701/30196 [01:33<53:15,  9.23it/s]

  2%|▏         | 703/30196 [01:34<50:00,  9.83it/s]

  2%|▏         | 704/30196 [01:34<56:27,  8.71it/s]

  2%|▏         | 705/30196 [01:34<59:18,  8.29it/s]

  2%|▏         | 707/30196 [01:34<55:25,  8.87it/s]

  2%|▏         | 709/30196 [01:34<48:23, 10.16it/s]

  2%|▏         | 711/30196 [01:35<57:08,  8.60it/s]

  2%|▏         | 712/30196 [01:35<56:26,  8.71it/s]

  2%|▏         | 714/30196 [01:35<52:51,  9.30it/s]

  2%|▏         | 716/30196 [01:35<51:07,  9.61it/s]

  2%|▏         | 718/30196 [01:35<48:56, 10.04it/s]

  2%|▏         | 720/30196 [01:35<52:52,  9.29it/s]

  2%|▏         | 722/30196 [01:36<53:21,  9.21it/s]

  2%|▏         | 723/30196 [01:36<53:06,  9.25it/s]

  2%|▏         | 724/30196 [01:36<1:22:48,  5.93it/s]

  2%|▏         | 725/30196 [01:36<1:15:40,  6.49it/s]

  2%|▏         | 726/30196 [01:37<1:45:11,  4.67it/s]

  2%|▏         | 728/30196 [01:37<1:17:59,  6.30it/s]

  2%|▏         | 730/30196 [01:37<1:08:46,  7.14it/s]

  2%|▏         | 732/30196 [01:37<59:06,  8.31it/s]

  2%|▏         | 734/30196 [01:37<57:38,  8.52it/s]

  2%|▏         | 735/30196 [01:38<59:15,  8.29it/s]

  2%|▏         | 736/30196 [01:38<57:39,  8.52it/s]

  2%|▏         | 738/30196 [01:38<49:46,  9.86it/s]

  2%|▏         | 740/30196 [01:38<46:31, 10.55it/s]

  2%|▏         | 742/30196 [01:38<54:15,  9.05it/s]

  2%|▏         | 743/30196 [01:38<54:10,  9.06it/s]

  2%|▏         | 745/30196 [01:39<48:02, 10.22it/s]

  2%|▏         | 747/30196 [01:39<48:04, 10.21it/s]

  2%|▏         | 749/30196 [01:39<49:56,  9.83it/s]

  2%|▏         | 751/30196 [01:39<59:10,  8.29it/s]

  2%|▏         | 753/30196 [01:40<1:01:57,  7.92it/s]

  3%|▎         | 755/30196 [01:40<53:18,  9.20it/s]

  3%|▎         | 757/30196 [01:40<57:51,  8.48it/s]

  3%|▎         | 758/30196 [01:40<56:41,  8.65it/s]

  3%|▎         | 759/30196 [01:40<59:13,  8.28it/s]

  3%|▎         | 760/30196 [01:40<1:09:55,  7.02it/s]

  3%|▎         | 761/30196 [01:41<1:09:49,  7.03it/s]

  3%|▎         | 763/30196 [01:41<52:21,  9.37it/s]

  3%|▎         | 765/30196 [01:41<53:17,  9.20it/s]

  3%|▎         | 767/30196 [01:41<49:53,  9.83it/s]

  3%|▎         | 769/30196 [01:41<50:46,  9.66it/s]

  3%|▎         | 771/30196 [01:42<52:36,  9.32it/s]

  3%|▎         | 772/30196 [01:42<56:27,  8.69it/s]

  3%|▎         | 773/30196 [01:42<56:02,  8.75it/s]

  3%|▎         | 775/30196 [01:42<51:35,  9.50it/s]

  3%|▎         | 776/30196 [01:42<52:07,  9.41it/s]

  3%|▎         | 778/30196 [01:42<47:18, 10.36it/s]

  3%|▎         | 780/30196 [01:42<46:04, 10.64it/s]

  3%|▎         | 782/30196 [01:43<52:56,  9.26it/s]

  3%|▎         | 783/30196 [01:43<56:06,  8.74it/s]

  3%|▎         | 785/30196 [01:43<1:02:09,  7.89it/s]

  3%|▎         | 786/30196 [01:43<1:00:01,  8.17it/s]

  3%|▎         | 787/30196 [01:43<1:01:06,  8.02it/s]

  3%|▎         | 788/30196 [01:44<1:02:53,  7.79it/s]

  3%|▎         | 789/30196 [01:44<1:20:03,  6.12it/s]

  3%|▎         | 791/30196 [01:44<1:00:03,  8.16it/s]

  3%|▎         | 792/30196 [01:44<1:02:57,  7.78it/s]

  3%|▎         | 793/30196 [01:44<1:00:50,  8.06it/s]

  3%|▎         | 794/30196 [01:44<1:06:27,  7.37it/s]

  3%|▎         | 795/30196 [01:45<1:05:54,  7.44it/s]

  3%|▎         | 797/30196 [01:45<56:39,  8.65it/s]

  3%|▎         | 798/30196 [01:45<1:03:56,  7.66it/s]

  3%|▎         | 800/30196 [01:45<56:36,  8.65it/s]

  3%|▎         | 801/30196 [01:45<1:17:18,  6.34it/s]

  3%|▎         | 802/30196 [01:46<1:18:44,  6.22it/s]

  3%|▎         | 804/30196 [01:46<1:25:06,  5.76it/s]

  3%|▎         | 805/30196 [01:46<1:28:56,  5.51it/s]

  3%|▎         | 806/30196 [01:46<1:20:24,  6.09it/s]

  3%|▎         | 808/30196 [01:47<1:14:24,  6.58it/s]

  3%|▎         | 810/30196 [01:47<1:09:14,  7.07it/s]

  3%|▎         | 811/30196 [01:47<1:23:31,  5.86it/s]

  3%|▎         | 813/30196 [01:47<1:11:49,  6.82it/s]

  3%|▎         | 815/30196 [01:47<59:33,  8.22it/s]

  3%|▎         | 816/30196 [01:48<1:04:24,  7.60it/s]

  3%|▎         | 819/30196 [01:48<48:16, 10.14it/s]

  3%|▎         | 821/30196 [01:48<46:46, 10.47it/s]

  3%|▎         | 823/30196 [01:48<49:50,  9.82it/s]

  3%|▎         | 825/30196 [01:48<52:15,  9.37it/s]

  3%|▎         | 827/30196 [01:49<48:59,  9.99it/s]

  3%|▎         | 829/30196 [01:49<52:56,  9.25it/s]

  3%|▎         | 831/30196 [01:49<53:29,  9.15it/s]

  3%|▎         | 832/30196 [01:49<56:55,  8.60it/s]

  3%|▎         | 834/30196 [01:49<56:35,  8.65it/s]

  3%|▎         | 835/30196 [01:50<1:00:04,  8.15it/s]

  3%|▎         | 836/30196 [01:50<1:02:51,  7.78it/s]

  3%|▎         | 837/30196 [01:50<1:07:38,  7.23it/s]

  3%|▎         | 839/30196 [01:50<1:05:19,  7.49it/s]

  3%|▎         | 841/30196 [01:50<1:12:21,  6.76it/s]

  3%|▎         | 842/30196 [01:51<1:11:29,  6.84it/s]

  3%|▎         | 844/30196 [01:51<1:18:06,  6.26it/s]

  3%|▎         | 845/30196 [01:51<1:15:13,  6.50it/s]

  3%|▎         | 847/30196 [01:51<57:47,  8.47it/s]

  3%|▎         | 849/30196 [01:51<53:29,  9.14it/s]

  3%|▎         | 851/30196 [01:52<1:00:08,  8.13it/s]

  3%|▎         | 853/30196 [01:52<55:41,  8.78it/s]

  3%|▎         | 854/30196 [01:52<58:53,  8.30it/s]

  3%|▎         | 856/30196 [01:52<1:04:36,  7.57it/s]

  3%|▎         | 858/30196 [01:53<53:09,  9.20it/s]

  3%|▎         | 860/30196 [01:53<50:28,  9.69it/s]

  3%|▎         | 862/30196 [01:53<46:01, 10.62it/s]

  3%|▎         | 864/30196 [01:53<57:38,  8.48it/s]

  3%|▎         | 866/30196 [01:53<58:24,  8.37it/s]

  3%|▎         | 867/30196 [01:54<1:00:32,  8.07it/s]

  3%|▎         | 869/30196 [01:54<51:01,  9.58it/s]

  3%|▎         | 871/30196 [01:54<52:00,  9.40it/s]

  3%|▎         | 873/30196 [01:54<1:02:45,  7.79it/s]

  3%|▎         | 874/30196 [01:54<1:06:36,  7.34it/s]

  3%|▎         | 875/30196 [01:55<1:07:53,  7.20it/s]

  3%|▎         | 877/30196 [01:55<52:19,  9.34it/s]

  3%|▎         | 879/30196 [01:55<1:14:19,  6.57it/s]

  3%|▎         | 880/30196 [01:55<1:20:55,  6.04it/s]

  3%|▎         | 881/30196 [01:56<1:28:32,  5.52it/s]

  3%|▎         | 882/30196 [01:56<1:24:00,  5.82it/s]

  3%|▎         | 884/30196 [01:56<1:06:14,  7.38it/s]

  3%|▎         | 885/30196 [01:56<1:02:56,  7.76it/s]

  3%|▎         | 886/30196 [01:56<1:00:12,  8.11it/s]

  3%|▎         | 887/30196 [01:56<1:01:56,  7.89it/s]

  3%|▎         | 888/30196 [01:56<1:07:49,  7.20it/s]

  3%|▎         | 889/30196 [01:57<1:11:46,  6.81it/s]

  3%|▎         | 890/30196 [01:57<1:16:36,  6.38it/s]

  3%|▎         | 892/30196 [01:57<1:04:33,  7.56it/s]

  3%|▎         | 894/30196 [01:57<1:01:55,  7.89it/s]

  3%|▎         | 895/30196 [01:57<1:04:20,  7.59it/s]

  3%|▎         | 896/30196 [01:58<1:22:50,  5.89it/s]

  3%|▎         | 898/30196 [01:58<1:05:46,  7.42it/s]

  3%|▎         | 899/30196 [01:58<1:10:40,  6.91it/s]

  3%|▎         | 900/30196 [01:58<1:10:23,  6.94it/s]

  3%|▎         | 901/30196 [01:58<1:10:19,  6.94it/s]

  3%|▎         | 903/30196 [01:58<55:27,  8.80it/s]

  3%|▎         | 904/30196 [01:59<58:33,  8.34it/s]

  3%|▎         | 906/30196 [01:59<53:08,  9.19it/s]

  3%|▎         | 908/30196 [01:59<57:24,  8.50it/s]

  3%|▎         | 909/30196 [01:59<58:56,  8.28it/s]

  3%|▎         | 910/30196 [01:59<1:00:36,  8.05it/s]

  3%|▎         | 911/30196 [01:59<1:02:57,  7.75it/s]

  3%|▎         | 912/30196 [02:00<59:56,  8.14it/s]

  3%|▎         | 914/30196 [02:00<50:21,  9.69it/s]

  3%|▎         | 915/30196 [02:00<58:53,  8.29it/s]

  3%|▎         | 917/30196 [02:00<52:00,  9.38it/s]

  3%|▎         | 918/30196 [02:00<52:30,  9.29it/s]

  3%|▎         | 920/30196 [02:00<51:52,  9.41it/s]

  3%|▎         | 923/30196 [02:01<42:25, 11.50it/s]

  3%|▎         | 925/30196 [02:01<45:51, 10.64it/s]

  3%|▎         | 927/30196 [02:01<53:51,  9.06it/s]

  3%|▎         | 928/30196 [02:01<59:16,  8.23it/s]

  3%|▎         | 929/30196 [02:01<58:20,  8.36it/s]

  3%|▎         | 930/30196 [02:02<1:03:32,  7.68it/s]

  3%|▎         | 933/30196 [02:02<51:28,  9.48it/s]

  3%|▎         | 934/30196 [02:02<55:26,  8.80it/s]

  3%|▎         | 936/30196 [02:02<48:52,  9.98it/s]

  3%|▎         | 938/30196 [02:02<51:41,  9.43it/s]

  3%|▎         | 939/30196 [02:02<51:37,  9.45it/s]

  3%|▎         | 941/30196 [02:03<48:38, 10.03it/s]

  3%|▎         | 943/30196 [02:03<57:11,  8.52it/s]

  3%|▎         | 945/30196 [02:03<1:00:21,  8.08it/s]

  3%|▎         | 946/30196 [02:03<1:02:10,  7.84it/s]

  3%|▎         | 947/30196 [02:03<1:00:16,  8.09it/s]

  3%|▎         | 948/30196 [02:04<59:18,  8.22it/s]

  3%|▎         | 949/30196 [02:04<1:00:34,  8.05it/s]

  3%|▎         | 950/30196 [02:04<1:02:21,  7.82it/s]

  3%|▎         | 951/30196 [02:04<1:08:19,  7.13it/s]

  3%|▎         | 952/30196 [02:04<1:09:50,  6.98it/s]

  3%|▎         | 954/30196 [02:04<58:34,  8.32it/s]

  3%|▎         | 955/30196 [02:04<56:51,  8.57it/s]

  3%|▎         | 957/30196 [02:05<51:42,  9.42it/s]

  3%|▎         | 958/30196 [02:05<56:28,  8.63it/s]

  3%|▎         | 960/30196 [02:05<48:27, 10.06it/s]

  3%|▎         | 962/30196 [02:05<52:10,  9.34it/s]

  3%|▎         | 963/30196 [02:05<51:58,  9.37it/s]

  3%|▎         | 964/30196 [02:05<52:36,  9.26it/s]

  3%|▎         | 965/30196 [02:05<52:03,  9.36it/s]

  3%|▎         | 966/30196 [02:06<1:05:29,  7.44it/s]

  3%|▎         | 967/30196 [02:06<1:34:54,  5.13it/s]

  3%|▎         | 968/30196 [02:06<1:31:34,  5.32it/s]

  3%|▎         | 969/30196 [02:06<1:25:21,  5.71it/s]

  3%|▎         | 971/30196 [02:07<1:13:41,  6.61it/s]

  3%|▎         | 972/30196 [02:07<1:20:42,  6.03it/s]

  3%|▎         | 973/30196 [02:07<1:13:54,  6.59it/s]

  3%|▎         | 974/30196 [02:07<1:16:36,  6.36it/s]

  3%|▎         | 976/30196 [02:07<1:01:58,  7.86it/s]

  3%|▎         | 978/30196 [02:07<49:47,  9.78it/s]

  3%|▎         | 980/30196 [02:08<42:33, 11.44it/s]

  3%|▎         | 982/30196 [02:08<48:38, 10.01it/s]

  3%|▎         | 984/30196 [02:08<53:48,  9.05it/s]

  3%|▎         | 985/30196 [02:08<1:17:45,  6.26it/s]

  3%|▎         | 986/30196 [02:09<1:16:39,  6.35it/s]

  3%|▎         | 988/30196 [02:09<1:07:56,  7.16it/s]

  3%|▎         | 990/30196 [02:09<55:32,  8.76it/s]

  3%|▎         | 992/30196 [02:09<52:21,  9.30it/s]

  3%|▎         | 994/30196 [02:09<53:07,  9.16it/s]

  3%|▎         | 995/30196 [02:10<58:49,  8.27it/s]

  3%|▎         | 996/30196 [02:10<57:50,  8.41it/s]

  3%|▎         | 997/30196 [02:10<1:10:00,  6.95it/s]

  3%|▎         | 998/30196 [02:10<1:09:07,  7.04it/s]

  3%|▎         | 999/30196 [02:10<1:09:14,  7.03it/s]

  3%|▎         | 1000/30196 [02:10<1:26:55,  5.60it/s]

  3%|▎         | 1002/30196 [02:11<1:13:18,  6.64it/s]

  3%|▎         | 1004/30196 [02:11<1:00:43,  8.01it/s]

  3%|▎         | 1006/30196 [02:11<56:56,  8.54it/s]

  3%|▎         | 1007/30196 [02:11<1:03:17,  7.69it/s]

  3%|▎         | 1008/30196 [02:11<1:14:24,  6.54it/s]

  3%|▎         | 1010/30196 [02:12<56:40,  8.58it/s]

  3%|▎         | 1013/30196 [02:12<47:14, 10.30it/s]

  3%|▎         | 1015/30196 [02:12<50:00,  9.72it/s]

  3%|▎         | 1017/30196 [02:12<52:55,  9.19it/s]

  3%|▎         | 1018/30196 [02:12<1:01:39,  7.89it/s]

  3%|▎         | 1019/30196 [02:13<1:06:10,  7.35it/s]

  3%|▎         | 1020/30196 [02:13<1:02:50,  7.74it/s]

  3%|▎         | 1021/30196 [02:13<1:05:21,  7.44it/s]

  3%|▎         | 1023/30196 [02:13<57:18,  8.49it/s]

  3%|▎         | 1025/30196 [02:13<49:45,  9.77it/s]

  3%|▎         | 1026/30196 [02:13<1:00:37,  8.02it/s]

  3%|▎         | 1027/30196 [02:14<1:06:12,  7.34it/s]

  3%|▎         | 1029/30196 [02:14<55:12,  8.81it/s]

  3%|▎         | 1030/30196 [02:14<1:07:18,  7.22it/s]

  3%|▎         | 1031/30196 [02:14<1:07:02,  7.25it/s]

  3%|▎         | 1032/30196 [02:14<1:06:23,  7.32it/s]

  3%|▎         | 1034/30196 [02:14<57:39,  8.43it/s]

  3%|▎         | 1035/30196 [02:15<1:03:20,  7.67it/s]

  3%|▎         | 1036/30196 [02:15<1:07:53,  7.16it/s]

  3%|▎         | 1037/30196 [02:15<1:11:32,  6.79it/s]

  3%|▎         | 1038/30196 [02:15<1:10:58,  6.85it/s]

  3%|▎         | 1039/30196 [02:15<1:13:43,  6.59it/s]

  3%|▎         | 1041/30196 [02:16<1:09:27,  7.00it/s]

  3%|▎         | 1043/30196 [02:16<1:05:11,  7.45it/s]

  3%|▎         | 1044/30196 [02:16<1:02:45,  7.74it/s]

  3%|▎         | 1045/30196 [02:16<1:04:14,  7.56it/s]

  3%|▎         | 1046/30196 [02:16<1:09:14,  7.02it/s]

  3%|▎         | 1048/30196 [02:16<1:00:14,  8.06it/s]

  3%|▎         | 1049/30196 [02:16<58:08,  8.36it/s]

  3%|▎         | 1050/30196 [02:17<59:40,  8.14it/s]

  3%|▎         | 1051/30196 [02:17<1:00:48,  7.99it/s]

  3%|▎         | 1053/30196 [02:17<48:41,  9.98it/s]

  3%|▎         | 1055/30196 [02:17<1:02:54,  7.72it/s]

  3%|▎         | 1056/30196 [02:17<1:00:44,  8.00it/s]

  4%|▎         | 1058/30196 [02:18<55:05,  8.81it/s]

  4%|▎         | 1059/30196 [02:18<54:49,  8.86it/s]

  4%|▎         | 1061/30196 [02:18<49:52,  9.74it/s]

  4%|▎         | 1062/30196 [02:18<52:58,  9.17it/s]

  4%|▎         | 1064/30196 [02:18<53:57,  9.00it/s]

  4%|▎         | 1065/30196 [02:18<56:34,  8.58it/s]

  4%|▎         | 1066/30196 [02:18<58:45,  8.26it/s]

  4%|▎         | 1067/30196 [02:19<57:34,  8.43it/s]

  4%|▎         | 1068/30196 [02:19<1:00:49,  7.98it/s]

  4%|▎         | 1070/30196 [02:19<52:58,  9.16it/s]

  4%|▎         | 1071/30196 [02:19<1:04:49,  7.49it/s]

  4%|▎         | 1072/30196 [02:19<1:04:40,  7.50it/s]

  4%|▎         | 1073/30196 [02:19<1:05:13,  7.44it/s]

  4%|▎         | 1074/30196 [02:19<1:01:28,  7.89it/s]

  4%|▎         | 1075/30196 [02:20<1:13:27,  6.61it/s]

  4%|▎         | 1076/30196 [02:20<1:13:11,  6.63it/s]

  4%|▎         | 1077/30196 [02:20<1:11:02,  6.83it/s]

  4%|▎         | 1079/30196 [02:20<55:30,  8.74it/s]

  4%|▎         | 1080/30196 [02:20<54:23,  8.92it/s]

  4%|▎         | 1081/30196 [02:20<58:15,  8.33it/s]

  4%|▎         | 1082/30196 [02:21<1:04:31,  7.52it/s]

  4%|▎         | 1083/30196 [02:21<1:04:29,  7.52it/s]

  4%|▎         | 1086/30196 [02:21<49:10,  9.87it/s]

  4%|▎         | 1087/30196 [02:21<54:03,  8.97it/s]

  4%|▎         | 1088/30196 [02:22<1:40:49,  4.81it/s]

  4%|▎         | 1089/30196 [02:22<1:29:20,  5.43it/s]

  4%|▎         | 1090/30196 [02:22<1:22:43,  5.86it/s]

  4%|▎         | 1091/30196 [02:23<3:00:29,  2.69it/s]

  4%|▎         | 1092/30196 [02:23<2:27:46,  3.28it/s]

  4%|▎         | 1093/30196 [02:23<2:06:04,  3.85it/s]

  4%|▎         | 1094/30196 [02:23<1:44:26,  4.64it/s]

  4%|▎         | 1096/30196 [02:23<1:24:29,  5.74it/s]

  4%|▎         | 1097/30196 [02:24<1:20:48,  6.00it/s]

  4%|▎         | 1098/30196 [02:24<1:21:02,  5.98it/s]

  4%|▎         | 1100/30196 [02:24<1:02:12,  7.80it/s]

  4%|▎         | 1102/30196 [02:24<56:40,  8.56it/s]

  4%|▎         | 1104/30196 [02:24<53:04,  9.13it/s]

  4%|▎         | 1105/30196 [02:24<56:55,  8.52it/s]

  4%|▎         | 1107/30196 [02:25<54:03,  8.97it/s]

  4%|▎         | 1109/30196 [02:25<54:48,  8.85it/s]

  4%|▎         | 1110/30196 [02:25<56:31,  8.58it/s]

  4%|▎         | 1111/30196 [02:25<59:58,  8.08it/s]

  4%|▎         | 1113/30196 [02:25<53:28,  9.07it/s]

  4%|▎         | 1115/30196 [02:25<48:17, 10.04it/s]

  4%|▎         | 1117/30196 [02:26<1:07:12,  7.21it/s]

  4%|▎         | 1119/30196 [02:26<57:09,  8.48it/s]

  4%|▎         | 1120/30196 [02:26<57:26,  8.44it/s]

  4%|▎         | 1121/30196 [02:26<56:38,  8.56it/s]

  4%|▎         | 1122/30196 [02:26<1:02:55,  7.70it/s]

  4%|▎         | 1123/30196 [02:27<1:03:07,  7.68it/s]

  4%|▎         | 1124/30196 [02:27<1:00:36,  7.99it/s]

  4%|▎         | 1125/30196 [02:27<1:03:35,  7.62it/s]

  4%|▎         | 1126/30196 [02:27<1:10:37,  6.86it/s]

  4%|▎         | 1127/30196 [02:27<1:15:46,  6.39it/s]

  4%|▎         | 1128/30196 [02:27<1:08:59,  7.02it/s]

  4%|▎         | 1129/30196 [02:27<1:12:46,  6.66it/s]

  4%|▎         | 1130/30196 [02:28<1:11:48,  6.75it/s]

  4%|▎         | 1131/30196 [02:28<1:10:58,  6.83it/s]

  4%|▎         | 1132/30196 [02:28<1:11:29,  6.78it/s]

  4%|▍         | 1133/30196 [02:28<1:09:59,  6.92it/s]

  4%|▍         | 1135/30196 [02:28<1:02:37,  7.73it/s]

  4%|▍         | 1136/30196 [02:28<1:03:47,  7.59it/s]

  4%|▍         | 1138/30196 [02:29<1:01:29,  7.88it/s]

  4%|▍         | 1140/30196 [02:29<50:08,  9.66it/s]

  4%|▍         | 1142/30196 [02:29<59:06,  8.19it/s]

  4%|▍         | 1143/30196 [02:29<57:32,  8.41it/s]

  4%|▍         | 1146/30196 [02:29<45:49, 10.57it/s]

  4%|▍         | 1148/30196 [02:30<55:12,  8.77it/s]

  4%|▍         | 1150/30196 [02:30<52:14,  9.27it/s]

  4%|▍         | 1152/30196 [02:30<52:33,  9.21it/s]

  4%|▍         | 1154/30196 [02:30<52:49,  9.16it/s]

  4%|▍         | 1156/30196 [02:31<1:07:38,  7.16it/s]

  4%|▍         | 1158/30196 [02:31<1:02:06,  7.79it/s]

  4%|▍         | 1159/30196 [02:31<1:09:01,  7.01it/s]

  4%|▍         | 1161/30196 [02:31<1:01:32,  7.86it/s]

  4%|▍         | 1162/30196 [02:32<1:06:11,  7.31it/s]

  4%|▍         | 1163/30196 [02:32<1:13:44,  6.56it/s]

  4%|▍         | 1164/30196 [02:32<1:11:48,  6.74it/s]

  4%|▍         | 1166/30196 [02:32<58:11,  8.31it/s]

  4%|▍         | 1167/30196 [02:32<1:01:11,  7.91it/s]

  4%|▍         | 1168/30196 [02:32<1:22:56,  5.83it/s]

  4%|▍         | 1170/30196 [02:33<2:24:30,  3.35it/s]

  4%|▍         | 1171/30196 [02:34<2:03:26,  3.92it/s]

  4%|▍         | 1172/30196 [02:34<1:54:56,  4.21it/s]

  4%|▍         | 1174/30196 [02:34<1:24:12,  5.74it/s]

  4%|▍         | 1177/30196 [02:34<1:11:26,  6.77it/s]

  4%|▍         | 1178/30196 [02:35<1:27:55,  5.50it/s]

  4%|▍         | 1179/30196 [02:35<1:23:06,  5.82it/s]

  4%|▍         | 1180/30196 [02:35<1:30:24,  5.35it/s]

  4%|▍         | 1181/30196 [02:35<1:28:13,  5.48it/s]

  4%|▍         | 1183/30196 [02:35<1:13:06,  6.61it/s]

  4%|▍         | 1185/30196 [02:36<1:13:02,  6.62it/s]

  4%|▍         | 1187/30196 [02:36<1:03:24,  7.63it/s]

  4%|▍         | 1188/30196 [02:36<1:03:31,  7.61it/s]

  4%|▍         | 1189/30196 [02:36<1:07:11,  7.20it/s]

  4%|▍         | 1190/30196 [02:36<1:22:42,  5.84it/s]

  4%|▍         | 1191/30196 [02:37<1:22:38,  5.85it/s]

  4%|▍         | 1192/30196 [02:37<1:23:25,  5.79it/s]

  4%|▍         | 1194/30196 [02:37<1:02:27,  7.74it/s]

  4%|▍         | 1195/30196 [02:37<1:07:21,  7.18it/s]

  4%|▍         | 1196/30196 [02:37<1:06:30,  7.27it/s]

  4%|▍         | 1198/30196 [02:37<1:02:42,  7.71it/s]

  4%|▍         | 1199/30196 [02:38<1:04:04,  7.54it/s]

  4%|▍         | 1201/30196 [02:38<1:10:02,  6.90it/s]

  4%|▍         | 1202/30196 [02:38<1:09:30,  6.95it/s]

  4%|▍         | 1204/30196 [02:38<56:21,  8.57it/s]

  4%|▍         | 1205/30196 [02:38<1:06:52,  7.23it/s]

  4%|▍         | 1206/30196 [02:39<1:14:40,  6.47it/s]

  4%|▍         | 1207/30196 [02:39<1:16:09,  6.34it/s]

  4%|▍         | 1208/30196 [02:39<1:30:32,  5.34it/s]

  4%|▍         | 1209/30196 [02:39<1:23:19,  5.80it/s]

  4%|▍         | 1211/30196 [02:39<1:09:12,  6.98it/s]

  4%|▍         | 1212/30196 [02:40<1:27:55,  5.49it/s]

  4%|▍         | 1214/30196 [02:40<1:21:49,  5.90it/s]

  4%|▍         | 1215/30196 [02:40<1:15:26,  6.40it/s]

  4%|▍         | 1216/30196 [02:40<1:14:34,  6.48it/s]

  4%|▍         | 1218/30196 [02:40<1:03:41,  7.58it/s]

  4%|▍         | 1220/30196 [02:41<58:40,  8.23it/s]

  4%|▍         | 1221/30196 [02:41<57:30,  8.40it/s]

  4%|▍         | 1222/30196 [02:41<1:07:10,  7.19it/s]

  4%|▍         | 1223/30196 [02:41<1:06:51,  7.22it/s]

  4%|▍         | 1224/30196 [02:41<1:06:31,  7.26it/s]

  4%|▍         | 1225/30196 [02:41<1:02:36,  7.71it/s]

  4%|▍         | 1226/30196 [02:42<1:04:18,  7.51it/s]

  4%|▍         | 1228/30196 [02:42<55:02,  8.77it/s]

  4%|▍         | 1230/30196 [02:42<53:11,  9.07it/s]

  4%|▍         | 1232/30196 [02:42<53:00,  9.11it/s]

  4%|▍         | 1234/30196 [02:42<51:08,  9.44it/s]

  4%|▍         | 1235/30196 [02:42<56:00,  8.62it/s]

  4%|▍         | 1236/30196 [02:43<57:41,  8.37it/s]

  4%|▍         | 1238/30196 [02:43<48:08, 10.02it/s]

  4%|▍         | 1240/30196 [02:43<49:30,  9.75it/s]

  4%|▍         | 1241/30196 [02:43<57:17,  8.42it/s]

  4%|▍         | 1242/30196 [02:43<56:27,  8.55it/s]

  4%|▍         | 1243/30196 [02:43<1:07:53,  7.11it/s]

  4%|▍         | 1244/30196 [02:44<1:08:55,  7.00it/s]

  4%|▍         | 1245/30196 [02:44<1:09:30,  6.94it/s]

  4%|▍         | 1247/30196 [02:44<53:28,  9.02it/s]

  4%|▍         | 1248/30196 [02:44<1:04:32,  7.47it/s]

  4%|▍         | 1249/30196 [02:44<1:08:43,  7.02it/s]

  4%|▍         | 1250/30196 [02:44<1:12:59,  6.61it/s]

  4%|▍         | 1252/30196 [02:45<55:51,  8.64it/s]

  4%|▍         | 1253/30196 [02:45<58:50,  8.20it/s]

  4%|▍         | 1255/30196 [02:45<1:07:47,  7.12it/s]

  4%|▍         | 1256/30196 [02:45<1:11:51,  6.71it/s]

  4%|▍         | 1257/30196 [02:45<1:07:23,  7.16it/s]

  4%|▍         | 1258/30196 [02:45<1:03:38,  7.58it/s]

  4%|▍         | 1259/30196 [02:46<1:10:02,  6.89it/s]

  4%|▍         | 1260/30196 [02:46<1:15:04,  6.42it/s]

  4%|▍         | 1261/30196 [02:46<1:08:08,  7.08it/s]

  4%|▍         | 1263/30196 [02:46<50:36,  9.53it/s]

  4%|▍         | 1265/30196 [02:46<54:31,  8.84it/s]

  4%|▍         | 1266/30196 [02:46<54:09,  8.90it/s]

  4%|▍         | 1267/30196 [02:47<58:14,  8.28it/s]

  4%|▍         | 1268/30196 [02:47<56:20,  8.56it/s]

  4%|▍         | 1269/30196 [02:47<1:02:57,  7.66it/s]

  4%|▍         | 1271/30196 [02:47<49:44,  9.69it/s]

  4%|▍         | 1273/30196 [02:47<47:59, 10.04it/s]

  4%|▍         | 1275/30196 [02:47<50:21,  9.57it/s]

  4%|▍         | 1277/30196 [02:48<45:10, 10.67it/s]

  4%|▍         | 1279/30196 [02:48<42:28, 11.35it/s]

  4%|▍         | 1281/30196 [02:48<49:27,  9.74it/s]

  4%|▍         | 1283/30196 [02:48<51:23,  9.38it/s]

  4%|▍         | 1284/30196 [02:48<55:03,  8.75it/s]

  4%|▍         | 1286/30196 [02:49<1:00:12,  8.00it/s]

  4%|▍         | 1288/30196 [02:49<52:47,  9.13it/s]

  4%|▍         | 1289/30196 [02:49<52:46,  9.13it/s]

  4%|▍         | 1291/30196 [02:49<48:15,  9.98it/s]

  4%|▍         | 1293/30196 [02:49<52:53,  9.11it/s]

  4%|▍         | 1295/30196 [02:49<47:43, 10.09it/s]

  4%|▍         | 1297/30196 [02:50<44:47, 10.75it/s]

  4%|▍         | 1299/30196 [02:50<53:21,  9.03it/s]

  4%|▍         | 1301/30196 [02:50<50:47,  9.48it/s]

  4%|▍         | 1303/30196 [02:50<55:49,  8.63it/s]

  4%|▍         | 1304/30196 [02:51<1:03:46,  7.55it/s]

  4%|▍         | 1305/30196 [02:51<1:01:38,  7.81it/s]

  4%|▍         | 1307/30196 [02:51<58:17,  8.26it/s]

  4%|▍         | 1309/30196 [02:51<54:15,  8.87it/s]

  4%|▍         | 1311/30196 [02:51<44:26, 10.83it/s]

  4%|▍         | 1313/30196 [02:51<45:44, 10.52it/s]

  4%|▍         | 1315/30196 [02:52<1:00:24,  7.97it/s]

  4%|▍         | 1316/30196 [02:52<1:04:47,  7.43it/s]

  4%|▍         | 1318/30196 [02:52<52:41,  9.13it/s]

  4%|▍         | 1320/30196 [02:52<47:46, 10.07it/s]

  4%|▍         | 1322/30196 [02:52<45:17, 10.62it/s]

  4%|▍         | 1324/30196 [02:53<39:53, 12.06it/s]

  4%|▍         | 1326/30196 [02:53<56:13,  8.56it/s]

  4%|▍         | 1328/30196 [02:53<54:24,  8.84it/s]

  4%|▍         | 1330/30196 [02:53<1:00:52,  7.90it/s]

  4%|▍         | 1331/30196 [02:54<1:05:02,  7.40it/s]

  4%|▍         | 1332/30196 [02:54<1:08:07,  7.06it/s]

  4%|▍         | 1334/30196 [02:54<57:35,  8.35it/s]

  4%|▍         | 1335/30196 [02:54<56:35,  8.50it/s]

  4%|▍         | 1336/30196 [02:54<1:02:50,  7.65it/s]

  4%|▍         | 1338/30196 [02:54<53:10,  9.04it/s]

  4%|▍         | 1339/30196 [02:55<53:13,  9.04it/s]

  4%|▍         | 1341/30196 [02:55<50:31,  9.52it/s]

  4%|▍         | 1342/30196 [02:55<50:28,  9.53it/s]

  4%|▍         | 1344/30196 [02:55<42:06, 11.42it/s]

  4%|▍         | 1346/30196 [02:55<46:03, 10.44it/s]

  4%|▍         | 1348/30196 [02:55<40:00, 12.02it/s]

  4%|▍         | 1350/30196 [02:55<35:05, 13.70it/s]

  4%|▍         | 1352/30196 [02:56<35:08, 13.68it/s]

  4%|▍         | 1354/30196 [02:56<45:04, 10.66it/s]

  4%|▍         | 1356/30196 [02:56<43:29, 11.05it/s]

  4%|▍         | 1358/30196 [02:56<44:51, 10.71it/s]

  5%|▍         | 1360/30196 [02:56<52:43,  9.12it/s]

  5%|▍         | 1362/30196 [02:57<1:04:32,  7.45it/s]

  5%|▍         | 1363/30196 [02:57<1:07:36,  7.11it/s]

  5%|▍         | 1365/30196 [02:57<55:33,  8.65it/s]

  5%|▍         | 1366/30196 [02:57<1:00:21,  7.96it/s]

  5%|▍         | 1368/30196 [02:57<52:45,  9.11it/s]

  5%|▍         | 1369/30196 [02:58<58:51,  8.16it/s]

  5%|▍         | 1370/30196 [02:58<1:04:14,  7.48it/s]

  5%|▍         | 1371/30196 [02:58<1:18:11,  6.14it/s]

  5%|▍         | 1373/30196 [02:58<1:01:14,  7.84it/s]

  5%|▍         | 1374/30196 [02:58<1:01:33,  7.80it/s]

  5%|▍         | 1376/30196 [02:59<53:57,  8.90it/s]

  5%|▍         | 1377/30196 [02:59<56:27,  8.51it/s]

  5%|▍         | 1378/30196 [02:59<58:35,  8.20it/s]

  5%|▍         | 1380/30196 [02:59<54:45,  8.77it/s]

  5%|▍         | 1381/30196 [02:59<1:10:35,  6.80it/s]

  5%|▍         | 1383/30196 [02:59<1:02:22,  7.70it/s]

  5%|▍         | 1385/30196 [03:00<51:30,  9.32it/s]

  5%|▍         | 1387/30196 [03:00<55:52,  8.59it/s]

  5%|▍         | 1389/30196 [03:00<57:57,  8.28it/s]

  5%|▍         | 1391/30196 [03:00<50:46,  9.45it/s]

  5%|▍         | 1393/30196 [03:01<57:37,  8.33it/s]

  5%|▍         | 1395/30196 [03:01<48:26,  9.91it/s]

  5%|▍         | 1397/30196 [03:01<53:44,  8.93it/s]

  5%|▍         | 1399/30196 [03:01<51:49,  9.26it/s]

  5%|▍         | 1401/30196 [03:01<45:51, 10.47it/s]

  5%|▍         | 1403/30196 [03:02<48:19,  9.93it/s]

  5%|▍         | 1405/30196 [03:02<46:32, 10.31it/s]

  5%|▍         | 1407/30196 [03:02<52:57,  9.06it/s]

  5%|▍         | 1410/30196 [03:02<55:28,  8.65it/s]

  5%|▍         | 1411/30196 [03:03<1:27:50,  5.46it/s]

  5%|▍         | 1412/30196 [03:03<1:24:41,  5.66it/s]

  5%|▍         | 1413/30196 [03:03<1:17:34,  6.18it/s]

  5%|▍         | 1414/30196 [03:03<1:16:03,  6.31it/s]

  5%|▍         | 1416/30196 [03:03<1:02:17,  7.70it/s]

  5%|▍         | 1417/30196 [03:04<1:06:24,  7.22it/s]

  5%|▍         | 1419/30196 [03:04<1:02:08,  7.72it/s]

  5%|▍         | 1420/30196 [03:04<1:07:21,  7.12it/s]

  5%|▍         | 1421/30196 [03:04<1:11:23,  6.72it/s]

  5%|▍         | 1422/30196 [03:04<1:08:02,  7.05it/s]

  5%|▍         | 1423/30196 [03:05<1:13:02,  6.57it/s]

  5%|▍         | 1424/30196 [03:05<1:07:26,  7.11it/s]

  5%|▍         | 1426/30196 [03:05<50:03,  9.58it/s]

  5%|▍         | 1428/30196 [03:05<40:28, 11.84it/s]

  5%|▍         | 1430/30196 [03:05<37:32, 12.77it/s]

  5%|▍         | 1432/30196 [03:05<35:46, 13.40it/s]

  5%|▍         | 1434/30196 [03:05<38:31, 12.44it/s]

  5%|▍         | 1436/30196 [03:06<44:52, 10.68it/s]

  5%|▍         | 1438/30196 [03:06<47:19, 10.13it/s]

  5%|▍         | 1440/30196 [03:06<58:16,  8.22it/s]

  5%|▍         | 1441/30196 [03:06<1:05:40,  7.30it/s]

  5%|▍         | 1443/30196 [03:07<1:07:20,  7.12it/s]

  5%|▍         | 1445/30196 [03:07<1:04:19,  7.45it/s]

  5%|▍         | 1446/30196 [03:07<1:04:00,  7.49it/s]

  5%|▍         | 1447/30196 [03:07<1:03:49,  7.51it/s]

  5%|▍         | 1449/30196 [03:07<57:27,  8.34it/s]

  5%|▍         | 1450/30196 [03:07<59:16,  8.08it/s]

  5%|▍         | 1451/30196 [03:08<1:05:42,  7.29it/s]

  5%|▍         | 1453/30196 [03:08<52:34,  9.11it/s]

  5%|▍         | 1454/30196 [03:08<56:32,  8.47it/s]

  5%|▍         | 1456/30196 [03:08<55:44,  8.59it/s]

  5%|▍         | 1457/30196 [03:08<55:07,  8.69it/s]

  5%|▍         | 1458/30196 [03:08<1:01:02,  7.85it/s]

  5%|▍         | 1459/30196 [03:09<1:03:23,  7.56it/s]

  5%|▍         | 1462/30196 [03:09<43:54, 10.91it/s]

  5%|▍         | 1464/30196 [03:09<39:52, 12.01it/s]

  5%|▍         | 1466/30196 [03:09<44:45, 10.70it/s]

  5%|▍         | 1468/30196 [03:09<53:46,  8.90it/s]

  5%|▍         | 1470/30196 [03:10<53:12,  9.00it/s]

  5%|▍         | 1472/30196 [03:10<48:55,  9.78it/s]

  5%|▍         | 1474/30196 [03:10<45:00, 10.64it/s]

  5%|▍         | 1476/30196 [03:10<46:19, 10.33it/s]

  5%|▍         | 1478/30196 [03:10<50:42,  9.44it/s]

  5%|▍         | 1479/30196 [03:11<56:32,  8.47it/s]

  5%|▍         | 1481/30196 [03:11<45:41, 10.47it/s]

  5%|▍         | 1483/30196 [03:11<47:51, 10.00it/s]

  5%|▍         | 1485/30196 [03:11<51:23,  9.31it/s]

  5%|▍         | 1487/30196 [03:11<49:24,  9.68it/s]

  5%|▍         | 1489/30196 [03:11<41:36, 11.50it/s]

  5%|▍         | 1491/30196 [03:12<43:04, 11.11it/s]

  5%|▍         | 1493/30196 [03:12<46:41, 10.25it/s]

  5%|▍         | 1495/30196 [03:12<47:56,  9.98it/s]

  5%|▍         | 1497/30196 [03:12<44:51, 10.66it/s]

  5%|▍         | 1499/30196 [03:12<47:50, 10.00it/s]

  5%|▍         | 1501/30196 [03:13<48:48,  9.80it/s]

  5%|▍         | 1503/30196 [03:13<50:49,  9.41it/s]

  5%|▍         | 1504/30196 [03:13<56:37,  8.44it/s]

  5%|▍         | 1505/30196 [03:13<1:07:43,  7.06it/s]

  5%|▍         | 1506/30196 [03:13<1:08:25,  6.99it/s]

  5%|▍         | 1507/30196 [03:14<1:08:47,  6.95it/s]

  5%|▍         | 1508/30196 [03:14<1:07:15,  7.11it/s]

  5%|▍         | 1509/30196 [03:14<1:10:24,  6.79it/s]

  5%|▌         | 1510/30196 [03:14<1:04:43,  7.39it/s]

  5%|▌         | 1511/30196 [03:14<1:10:16,  6.80it/s]

  5%|▌         | 1512/30196 [03:14<1:09:33,  6.87it/s]

  5%|▌         | 1513/30196 [03:14<1:03:55,  7.48it/s]

  5%|▌         | 1514/30196 [03:15<1:00:10,  7.94it/s]

  5%|▌         | 1515/30196 [03:15<1:13:08,  6.54it/s]

  5%|▌         | 1516/30196 [03:15<1:15:24,  6.34it/s]

  5%|▌         | 1517/30196 [03:15<1:13:00,  6.55it/s]

  5%|▌         | 1519/30196 [03:15<1:00:26,  7.91it/s]

  5%|▌         | 1520/30196 [03:15<1:02:50,  7.60it/s]

  5%|▌         | 1521/30196 [03:16<1:07:21,  7.10it/s]

  5%|▌         | 1523/30196 [03:16<56:59,  8.39it/s]

  5%|▌         | 1524/30196 [03:16<57:06,  8.37it/s]

  5%|▌         | 1525/30196 [03:16<58:53,  8.11it/s]

  5%|▌         | 1526/30196 [03:16<56:36,  8.44it/s]

  5%|▌         | 1528/30196 [03:16<45:20, 10.54it/s]

  5%|▌         | 1530/30196 [03:16<43:03, 11.10it/s]

  5%|▌         | 1532/30196 [03:17<42:15, 11.30it/s]

  5%|▌         | 1534/30196 [03:17<41:58, 11.38it/s]

  5%|▌         | 1536/30196 [03:17<37:34, 12.71it/s]

  5%|▌         | 1538/30196 [03:17<44:36, 10.71it/s]

  5%|▌         | 1540/30196 [03:18<1:07:49,  7.04it/s]

  5%|▌         | 1541/30196 [03:18<1:07:43,  7.05it/s]

  5%|▌         | 1543/30196 [03:18<56:15,  8.49it/s]

  5%|▌         | 1545/30196 [03:18<56:24,  8.47it/s]

  5%|▌         | 1547/30196 [03:18<50:20,  9.48it/s]

  5%|▌         | 1549/30196 [03:19<1:06:11,  7.21it/s]

  5%|▌         | 1550/30196 [03:19<1:17:05,  6.19it/s]

  5%|▌         | 1551/30196 [03:19<1:15:02,  6.36it/s]

  5%|▌         | 1552/30196 [03:19<1:20:15,  5.95it/s]

  5%|▌         | 1553/30196 [03:19<1:13:05,  6.53it/s]

  5%|▌         | 1554/30196 [03:20<1:07:44,  7.05it/s]

  5%|▌         | 1557/30196 [03:20<44:51, 10.64it/s]

  5%|▌         | 1559/30196 [03:20<49:16,  9.69it/s]

  5%|▌         | 1561/30196 [03:20<44:03, 10.83it/s]

  5%|▌         | 1563/30196 [03:20<46:22, 10.29it/s]

  5%|▌         | 1565/30196 [03:20<44:10, 10.80it/s]

  5%|▌         | 1567/30196 [03:21<43:42, 10.92it/s]

  5%|▌         | 1569/30196 [03:21<51:52,  9.20it/s]

  5%|▌         | 1571/30196 [03:21<53:34,  8.90it/s]

  5%|▌         | 1573/30196 [03:21<47:14, 10.10it/s]

  5%|▌         | 1575/30196 [03:22<57:58,  8.23it/s]

  5%|▌         | 1576/30196 [03:22<1:00:06,  7.93it/s]

  5%|▌         | 1578/30196 [03:22<1:00:15,  7.91it/s]

  5%|▌         | 1579/30196 [03:22<1:01:32,  7.75it/s]

  5%|▌         | 1580/30196 [03:22<1:06:11,  7.21it/s]

  5%|▌         | 1581/30196 [03:23<1:09:58,  6.81it/s]

  5%|▌         | 1582/30196 [03:23<1:17:28,  6.16it/s]

  5%|▌         | 1583/30196 [03:23<1:18:17,  6.09it/s]

  5%|▌         | 1584/30196 [03:23<1:15:20,  6.33it/s]

  5%|▌         | 1585/30196 [03:23<1:22:06,  5.81it/s]

  5%|▌         | 1586/30196 [03:23<1:21:25,  5.86it/s]

  5%|▌         | 1587/30196 [03:24<1:17:19,  6.17it/s]

  5%|▌         | 1589/30196 [03:24<1:02:58,  7.57it/s]

  5%|▌         | 1591/30196 [03:24<58:54,  8.09it/s]

  5%|▌         | 1593/30196 [03:24<55:25,  8.60it/s]

  5%|▌         | 1594/30196 [03:24<58:21,  8.17it/s]

  5%|▌         | 1595/30196 [03:24<57:05,  8.35it/s]

  5%|▌         | 1596/30196 [03:25<58:24,  8.16it/s]

  5%|▌         | 1598/30196 [03:25<51:56,  9.17it/s]

  5%|▌         | 1599/30196 [03:25<1:05:01,  7.33it/s]

  5%|▌         | 1601/30196 [03:25<51:40,  9.22it/s]

  5%|▌         | 1602/30196 [03:25<1:02:55,  7.57it/s]

  5%|▌         | 1605/30196 [03:26<1:04:41,  7.37it/s]

  5%|▌         | 1607/30196 [03:26<54:12,  8.79it/s]

  5%|▌         | 1609/30196 [03:26<47:19, 10.07it/s]

  5%|▌         | 1611/30196 [03:26<47:20, 10.06it/s]

  5%|▌         | 1613/30196 [03:27<54:29,  8.74it/s]

  5%|▌         | 1615/30196 [03:27<49:55,  9.54it/s]

  5%|▌         | 1617/30196 [03:27<52:41,  9.04it/s]

  5%|▌         | 1618/30196 [03:27<54:40,  8.71it/s]

  5%|▌         | 1619/30196 [03:27<57:12,  8.33it/s]

  5%|▌         | 1621/30196 [03:27<57:02,  8.35it/s]

  5%|▌         | 1622/30196 [03:28<55:33,  8.57it/s]

  5%|▌         | 1624/30196 [03:28<55:19,  8.61it/s]

  5%|▌         | 1625/30196 [03:28<1:04:12,  7.42it/s]

  5%|▌         | 1626/30196 [03:28<1:08:56,  6.91it/s]

  5%|▌         | 1628/30196 [03:28<55:18,  8.61it/s]

  5%|▌         | 1630/30196 [03:29<55:00,  8.65it/s]

  5%|▌         | 1631/30196 [03:29<53:59,  8.82it/s]

  5%|▌         | 1632/30196 [03:29<1:00:28,  7.87it/s]

  5%|▌         | 1634/30196 [03:29<54:42,  8.70it/s]

  5%|▌         | 1636/30196 [03:29<50:58,  9.34it/s]

  5%|▌         | 1637/30196 [03:29<58:03,  8.20it/s]

  5%|▌         | 1639/30196 [03:30<50:17,  9.46it/s]

  5%|▌         | 1640/30196 [03:30<50:33,  9.41it/s]

  5%|▌         | 1642/30196 [03:30<47:24, 10.04it/s]

  5%|▌         | 1644/30196 [03:30<59:05,  8.05it/s]

  5%|▌         | 1645/30196 [03:30<1:00:14,  7.90it/s]

  5%|▌         | 1647/30196 [03:30<54:01,  8.81it/s]

  5%|▌         | 1649/30196 [03:31<59:25,  8.01it/s]

  5%|▌         | 1650/30196 [03:31<1:00:14,  7.90it/s]

  5%|▌         | 1651/30196 [03:31<58:24,  8.15it/s]

  5%|▌         | 1653/30196 [03:31<51:20,  9.27it/s]

  5%|▌         | 1654/30196 [03:31<57:43,  8.24it/s]

  5%|▌         | 1656/30196 [03:32<52:23,  9.08it/s]

  5%|▌         | 1657/30196 [03:32<52:20,  9.09it/s]

  5%|▌         | 1658/30196 [03:32<1:04:47,  7.34it/s]

  5%|▌         | 1660/30196 [03:32<51:25,  9.25it/s]

  6%|▌         | 1662/30196 [03:32<48:43,  9.76it/s]

  6%|▌         | 1664/30196 [03:32<47:54,  9.93it/s]

  6%|▌         | 1666/30196 [03:33<49:58,  9.52it/s]

  6%|▌         | 1667/30196 [03:33<57:50,  8.22it/s]

  6%|▌         | 1668/30196 [03:33<58:52,  8.08it/s]

  6%|▌         | 1670/30196 [03:33<48:24,  9.82it/s]

  6%|▌         | 1672/30196 [03:33<49:43,  9.56it/s]

  6%|▌         | 1673/30196 [03:33<52:11,  9.11it/s]

  6%|▌         | 1674/30196 [03:34<54:53,  8.66it/s]

  6%|▌         | 1675/30196 [03:34<56:22,  8.43it/s]

  6%|▌         | 1677/30196 [03:34<55:27,  8.57it/s]

  6%|▌         | 1678/30196 [03:34<56:57,  8.34it/s]

  6%|▌         | 1680/30196 [03:34<49:30,  9.60it/s]

  6%|▌         | 1682/30196 [03:34<54:01,  8.80it/s]

  6%|▌         | 1683/30196 [03:35<53:40,  8.85it/s]

  6%|▌         | 1684/30196 [03:35<53:09,  8.94it/s]

  6%|▌         | 1685/30196 [03:35<1:04:08,  7.41it/s]

  6%|▌         | 1687/30196 [03:35<58:12,  8.16it/s]

  6%|▌         | 1689/30196 [03:35<52:50,  8.99it/s]

  6%|▌         | 1690/30196 [03:35<55:43,  8.52it/s]

  6%|▌         | 1692/30196 [03:36<45:22, 10.47it/s]

  6%|▌         | 1694/30196 [03:36<44:21, 10.71it/s]

  6%|▌         | 1696/30196 [03:36<49:22,  9.62it/s]

  6%|▌         | 1698/30196 [03:36<47:05, 10.09it/s]

  6%|▌         | 1700/30196 [03:36<50:13,  9.46it/s]

  6%|▌         | 1701/30196 [03:37<50:38,  9.38it/s]

  6%|▌         | 1702/30196 [03:37<54:42,  8.68it/s]

  6%|▌         | 1704/30196 [03:37<47:22, 10.02it/s]

  6%|▌         | 1706/30196 [03:37<50:18,  9.44it/s]

  6%|▌         | 1708/30196 [03:37<44:22, 10.70it/s]

  6%|▌         | 1711/30196 [03:37<35:20, 13.43it/s]

  6%|▌         | 1713/30196 [03:37<33:58, 13.97it/s]

  6%|▌         | 1715/30196 [03:38<47:31,  9.99it/s]

  6%|▌         | 1717/30196 [03:38<52:04,  9.11it/s]

  6%|▌         | 1719/30196 [03:38<50:23,  9.42it/s]

  6%|▌         | 1721/30196 [03:38<44:39, 10.63it/s]

  6%|▌         | 1723/30196 [03:39<46:52, 10.12it/s]

  6%|▌         | 1725/30196 [03:39<52:06,  9.11it/s]

  6%|▌         | 1726/30196 [03:39<56:41,  8.37it/s]

  6%|▌         | 1728/30196 [03:39<47:51,  9.91it/s]

  6%|▌         | 1730/30196 [03:40<59:31,  7.97it/s]

  6%|▌         | 1732/30196 [03:40<55:04,  8.61it/s]

  6%|▌         | 1734/30196 [03:40<49:28,  9.59it/s]

  6%|▌         | 1736/30196 [03:40<56:17,  8.43it/s]

  6%|▌         | 1737/30196 [03:40<55:30,  8.55it/s]

  6%|▌         | 1739/30196 [03:41<1:12:13,  6.57it/s]

  6%|▌         | 1740/30196 [03:41<1:13:31,  6.45it/s]

  6%|▌         | 1741/30196 [03:41<1:11:21,  6.65it/s]

  6%|▌         | 1742/30196 [03:41<1:06:10,  7.17it/s]

  6%|▌         | 1744/30196 [03:41<52:12,  9.08it/s]

  6%|▌         | 1746/30196 [03:41<49:40,  9.55it/s]

  6%|▌         | 1748/30196 [03:42<44:14, 10.72it/s]

  6%|▌         | 1750/30196 [03:42<42:53, 11.05it/s]

  6%|▌         | 1752/30196 [03:42<55:45,  8.50it/s]

  6%|▌         | 1753/30196 [03:42<1:00:15,  7.87it/s]

  6%|▌         | 1754/30196 [03:42<58:36,  8.09it/s]

  6%|▌         | 1755/30196 [03:43<1:00:34,  7.83it/s]

  6%|▌         | 1756/30196 [03:43<1:01:06,  7.76it/s]

  6%|▌         | 1758/30196 [03:43<49:56,  9.49it/s]

  6%|▌         | 1759/30196 [03:43<52:31,  9.02it/s]

  6%|▌         | 1761/30196 [03:43<43:28, 10.90it/s]

  6%|▌         | 1763/30196 [03:45<2:51:11,  2.77it/s]

  6%|▌         | 1764/30196 [03:45<2:29:32,  3.17it/s]

  6%|▌         | 1765/30196 [03:45<2:07:39,  3.71it/s]

  6%|▌         | 1767/30196 [03:46<2:53:28,  2.73it/s]

  6%|▌         | 1768/30196 [03:46<2:32:39,  3.10it/s]

  6%|▌         | 1770/30196 [03:46<1:54:01,  4.16it/s]

  6%|▌         | 1772/30196 [03:47<1:30:14,  5.25it/s]

  6%|▌         | 1774/30196 [03:47<1:09:35,  6.81it/s]

  6%|▌         | 1776/30196 [03:47<1:10:05,  6.76it/s]

  6%|▌         | 1777/30196 [03:47<1:12:23,  6.54it/s]

  6%|▌         | 1779/30196 [03:47<1:08:43,  6.89it/s]

  6%|▌         | 1781/30196 [03:48<1:02:29,  7.58it/s]

  6%|▌         | 1782/30196 [03:48<1:09:57,  6.77it/s]

  6%|▌         | 1783/30196 [03:48<1:16:03,  6.23it/s]

  6%|▌         | 1784/30196 [03:48<1:21:07,  5.84it/s]

  6%|▌         | 1786/30196 [03:49<1:11:31,  6.62it/s]

  6%|▌         | 1788/30196 [03:49<56:39,  8.36it/s]

  6%|▌         | 1789/30196 [03:49<55:11,  8.58it/s]

  6%|▌         | 1790/30196 [03:49<56:42,  8.35it/s]

  6%|▌         | 1791/30196 [03:49<56:43,  8.35it/s]

  6%|▌         | 1793/30196 [03:49<1:00:38,  7.81it/s]

  6%|▌         | 1795/30196 [03:50<56:44,  8.34it/s]

  6%|▌         | 1797/30196 [03:50<46:45, 10.12it/s]

  6%|▌         | 1799/30196 [03:50<55:03,  8.60it/s]

  6%|▌         | 1800/30196 [03:50<57:47,  8.19it/s]

  6%|▌         | 1802/30196 [03:50<54:37,  8.66it/s]

  6%|▌         | 1804/30196 [03:50<45:37, 10.37it/s]

  6%|▌         | 1806/30196 [03:51<49:10,  9.62it/s]

  6%|▌         | 1808/30196 [03:51<56:13,  8.41it/s]

  6%|▌         | 1809/30196 [03:51<55:01,  8.60it/s]

  6%|▌         | 1810/30196 [03:51<59:58,  7.89it/s]

  6%|▌         | 1811/30196 [03:51<1:04:10,  7.37it/s]

  6%|▌         | 1813/30196 [03:52<50:59,  9.28it/s]

  6%|▌         | 1814/30196 [03:52<53:21,  8.87it/s]

  6%|▌         | 1817/30196 [03:52<47:41,  9.92it/s]

  6%|▌         | 1818/30196 [03:52<49:23,  9.58it/s]

  6%|▌         | 1819/30196 [03:52<49:44,  9.51it/s]

  6%|▌         | 1821/30196 [03:52<48:09,  9.82it/s]

  6%|▌         | 1823/30196 [03:53<50:59,  9.27it/s]

  6%|▌         | 1825/30196 [03:53<44:25, 10.64it/s]

  6%|▌         | 1827/30196 [03:53<50:31,  9.36it/s]

  6%|▌         | 1828/30196 [03:53<56:04,  8.43it/s]

  6%|▌         | 1829/30196 [03:53<57:21,  8.24it/s]

  6%|▌         | 1830/30196 [03:54<1:24:51,  5.57it/s]

  6%|▌         | 1832/30196 [03:54<1:15:42,  6.24it/s]

  6%|▌         | 1833/30196 [03:54<1:11:33,  6.61it/s]

  6%|▌         | 1835/30196 [03:54<57:35,  8.21it/s]

  6%|▌         | 1837/30196 [03:54<52:14,  9.05it/s]

  6%|▌         | 1838/30196 [03:55<57:51,  8.17it/s]

  6%|▌         | 1839/30196 [03:55<1:04:15,  7.35it/s]

  6%|▌         | 1841/30196 [03:55<49:54,  9.47it/s]

  6%|▌         | 1843/30196 [03:55<50:24,  9.37it/s]

  6%|▌         | 1845/30196 [03:55<48:37,  9.72it/s]

  6%|▌         | 1847/30196 [03:55<50:08,  9.42it/s]

  6%|▌         | 1848/30196 [03:56<52:30,  9.00it/s]

  6%|▌         | 1850/30196 [03:56<46:42, 10.11it/s]

  6%|▌         | 1852/30196 [03:56<45:19, 10.42it/s]

  6%|▌         | 1854/30196 [03:56<55:45,  8.47it/s]

  6%|▌         | 1856/30196 [03:56<46:04, 10.25it/s]

  6%|▌         | 1858/30196 [03:57<47:55,  9.85it/s]

  6%|▌         | 1860/30196 [03:57<52:59,  8.91it/s]

  6%|▌         | 1862/30196 [03:57<50:33,  9.34it/s]

  6%|▌         | 1864/30196 [03:57<57:47,  8.17it/s]

  6%|▌         | 1866/30196 [03:58<52:00,  9.08it/s]

  6%|▌         | 1867/30196 [03:58<51:55,  9.09it/s]

  6%|▌         | 1869/30196 [03:58<42:29, 11.11it/s]

  6%|▌         | 1871/30196 [03:58<51:09,  9.23it/s]

  6%|▌         | 1873/30196 [03:58<1:00:30,  7.80it/s]

  6%|▌         | 1874/30196 [03:58<58:56,  8.01it/s]

  6%|▌         | 1875/30196 [03:59<1:00:34,  7.79it/s]

  6%|▌         | 1876/30196 [03:59<58:38,  8.05it/s]

  6%|▌         | 1878/30196 [03:59<51:51,  9.10it/s]

  6%|▌         | 1879/30196 [03:59<54:43,  8.62it/s]

  6%|▌         | 1881/30196 [03:59<51:23,  9.18it/s]

  6%|▌         | 1883/30196 [03:59<48:15,  9.78it/s]

  6%|▌         | 1884/30196 [04:00<48:59,  9.63it/s]

  6%|▌         | 1885/30196 [04:00<55:36,  8.48it/s]

  6%|▌         | 1886/30196 [04:00<58:13,  8.10it/s]

  6%|▌         | 1887/30196 [04:00<56:19,  8.38it/s]

  6%|▋         | 1888/30196 [04:00<59:00,  8.00it/s]

  6%|▋         | 1890/30196 [04:00<49:16,  9.58it/s]

  6%|▋         | 1892/30196 [04:00<44:14, 10.66it/s]

  6%|▋         | 1894/30196 [04:01<58:21,  8.08it/s]

  6%|▋         | 1896/30196 [04:01<53:55,  8.75it/s]

  6%|▋         | 1899/30196 [04:01<48:43,  9.68it/s]

  6%|▋         | 1901/30196 [04:01<51:41,  9.12it/s]

  6%|▋         | 1903/30196 [04:02<47:45,  9.87it/s]

  6%|▋         | 1905/30196 [04:02<49:19,  9.56it/s]

  6%|▋         | 1906/30196 [04:02<49:48,  9.47it/s]

  6%|▋         | 1907/30196 [04:02<1:00:26,  7.80it/s]

  6%|▋         | 1909/30196 [04:02<56:26,  8.35it/s]

  6%|▋         | 1910/30196 [04:03<58:23,  8.07it/s]

  6%|▋         | 1911/30196 [04:03<56:53,  8.29it/s]

  6%|▋         | 1912/30196 [04:03<55:42,  8.46it/s]

  6%|▋         | 1913/30196 [04:03<57:12,  8.24it/s]

  6%|▋         | 1915/30196 [04:03<58:36,  8.04it/s]

  6%|▋         | 1916/30196 [04:03<1:03:26,  7.43it/s]

  6%|▋         | 1917/30196 [04:03<1:02:57,  7.49it/s]

  6%|▋         | 1919/30196 [04:04<53:20,  8.84it/s]

  6%|▋         | 1920/30196 [04:04<59:07,  7.97it/s]

  6%|▋         | 1921/30196 [04:04<1:04:12,  7.34it/s]

  6%|▋         | 1924/30196 [04:04<42:25, 11.11it/s]

  6%|▋         | 1926/30196 [04:04<40:20, 11.68it/s]

  6%|▋         | 1928/30196 [04:04<45:52, 10.27it/s]

  6%|▋         | 1930/30196 [04:05<39:57, 11.79it/s]

  6%|▋         | 1932/30196 [04:05<51:43,  9.11it/s]

  6%|▋         | 1934/30196 [04:05<45:42, 10.31it/s]

  6%|▋         | 1936/30196 [04:05<43:32, 10.82it/s]

  6%|▋         | 1938/30196 [04:06<1:33:41,  5.03it/s]

  6%|▋         | 1940/30196 [04:06<1:21:13,  5.80it/s]

  6%|▋         | 1942/30196 [04:07<1:13:07,  6.44it/s]

  6%|▋         | 1943/30196 [04:07<1:32:20,  5.10it/s]

  6%|▋         | 1945/30196 [04:07<1:20:58,  5.81it/s]

  6%|▋         | 1946/30196 [04:07<1:18:08,  6.03it/s]

  6%|▋         | 1947/30196 [04:07<1:12:16,  6.51it/s]

  6%|▋         | 1949/30196 [04:08<58:12,  8.09it/s]

  6%|▋         | 1950/30196 [04:08<59:07,  7.96it/s]

  6%|▋         | 1952/30196 [04:08<48:45,  9.65it/s]

  6%|▋         | 1954/30196 [04:08<53:38,  8.78it/s]

  6%|▋         | 1955/30196 [04:08<59:19,  7.93it/s]

  6%|▋         | 1956/30196 [04:08<59:47,  7.87it/s]

  6%|▋         | 1957/30196 [04:09<1:04:45,  7.27it/s]

  6%|▋         | 1958/30196 [04:09<1:05:06,  7.23it/s]

  6%|▋         | 1959/30196 [04:09<1:05:39,  7.17it/s]

  6%|▋         | 1961/30196 [04:09<50:53,  9.25it/s]

  6%|▋         | 1962/30196 [04:09<50:36,  9.30it/s]

  7%|▋         | 1963/30196 [04:09<50:17,  9.36it/s]

  7%|▋         | 1964/30196 [04:09<58:14,  8.08it/s]

  7%|▋         | 1965/30196 [04:10<1:04:02,  7.35it/s]

  7%|▋         | 1967/30196 [04:10<58:38,  8.02it/s]

  7%|▋         | 1968/30196 [04:10<59:23,  7.92it/s]

  7%|▋         | 1969/30196 [04:10<57:22,  8.20it/s]

  7%|▋         | 1970/30196 [04:10<58:24,  8.05it/s]

  7%|▋         | 1972/30196 [04:10<46:48, 10.05it/s]

  7%|▋         | 1974/30196 [04:10<41:04, 11.45it/s]

  7%|▋         | 1976/30196 [04:11<52:34,  8.95it/s]

  7%|▋         | 1978/30196 [04:11<44:06, 10.66it/s]

  7%|▋         | 1980/30196 [04:11<43:29, 10.81it/s]

  7%|▋         | 1982/30196 [04:11<50:13,  9.36it/s]

  7%|▋         | 1984/30196 [04:12<53:54,  8.72it/s]

  7%|▋         | 1985/30196 [04:12<53:24,  8.80it/s]

  7%|▋         | 1986/30196 [04:12<53:04,  8.86it/s]

  7%|▋         | 1988/30196 [04:12<49:37,  9.47it/s]

  7%|▋         | 1990/30196 [04:12<51:42,  9.09it/s]

  7%|▋         | 1992/30196 [04:12<54:10,  8.68it/s]

  7%|▋         | 1993/30196 [04:13<53:15,  8.82it/s]

  7%|▋         | 1994/30196 [04:13<56:04,  8.38it/s]

  7%|▋         | 1996/30196 [04:13<51:11,  9.18it/s]

  7%|▋         | 1997/30196 [04:13<54:07,  8.68it/s]

  7%|▋         | 1999/30196 [04:13<46:09, 10.18it/s]

  7%|▋         | 2001/30196 [04:14<1:09:47,  6.73it/s]

  7%|▋         | 2002/30196 [04:14<1:10:12,  6.69it/s]

  7%|▋         | 2003/30196 [04:14<1:05:36,  7.16it/s]

  7%|▋         | 2004/30196 [04:14<1:13:46,  6.37it/s]

  7%|▋         | 2006/30196 [04:14<1:07:08,  7.00it/s]

  7%|▋         | 2007/30196 [04:15<1:09:51,  6.73it/s]

  7%|▋         | 2009/30196 [04:15<1:02:56,  7.46it/s]

  7%|▋         | 2010/30196 [04:15<1:02:40,  7.49it/s]

  7%|▋         | 2011/30196 [04:15<1:22:41,  5.68it/s]

  7%|▋         | 2013/30196 [04:15<1:00:35,  7.75it/s]

  7%|▋         | 2015/30196 [04:16<59:56,  7.84it/s]

  7%|▋         | 2017/30196 [04:16<48:50,  9.62it/s]

  7%|▋         | 2019/30196 [04:16<43:09, 10.88it/s]

  7%|▋         | 2021/30196 [04:16<46:13, 10.16it/s]

  7%|▋         | 2023/30196 [04:16<54:28,  8.62it/s]

  7%|▋         | 2024/30196 [04:17<1:02:19,  7.53it/s]

  7%|▋         | 2026/30196 [04:17<58:48,  7.98it/s]

  7%|▋         | 2027/30196 [04:17<56:57,  8.24it/s]

  7%|▋         | 2030/30196 [04:17<49:59,  9.39it/s]

  7%|▋         | 2031/30196 [04:17<52:06,  9.01it/s]

  7%|▋         | 2034/30196 [04:18<47:30,  9.88it/s]

  7%|▋         | 2035/30196 [04:18<48:14,  9.73it/s]

  7%|▋         | 2036/30196 [04:18<51:09,  9.17it/s]

  7%|▋         | 2037/30196 [04:18<53:16,  8.81it/s]

  7%|▋         | 2038/30196 [04:18<52:54,  8.87it/s]

  7%|▋         | 2039/30196 [04:18<57:06,  8.22it/s]

  7%|▋         | 2040/30196 [04:18<55:07,  8.51it/s]

  7%|▋         | 2042/30196 [04:19<52:10,  8.99it/s]

  7%|▋         | 2043/30196 [04:19<54:42,  8.58it/s]

  7%|▋         | 2044/30196 [04:19<57:30,  8.16it/s]

  7%|▋         | 2045/30196 [04:19<55:17,  8.49it/s]

  7%|▋         | 2046/30196 [04:19<58:17,  8.05it/s]

  7%|▋         | 2047/30196 [04:19<59:04,  7.94it/s]

  7%|▋         | 2049/30196 [04:19<46:35, 10.07it/s]

  7%|▋         | 2051/30196 [04:19<42:11, 11.12it/s]

  7%|▋         | 2053/30196 [04:20<40:27, 11.59it/s]

  7%|▋         | 2055/30196 [04:20<51:21,  9.13it/s]

  7%|▋         | 2057/30196 [04:20<47:14,  9.93it/s]

  7%|▋         | 2059/30196 [04:20<48:55,  9.59it/s]

  7%|▋         | 2061/30196 [04:20<44:03, 10.64it/s]

  7%|▋         | 2063/30196 [04:21<59:14,  7.92it/s]

  7%|▋         | 2064/30196 [04:21<1:00:25,  7.76it/s]

  7%|▋         | 2065/30196 [04:21<58:34,  8.01it/s]

  7%|▋         | 2066/30196 [04:21<56:52,  8.24it/s]

  7%|▋         | 2067/30196 [04:21<58:23,  8.03it/s]

  7%|▋         | 2068/30196 [04:22<1:09:03,  6.79it/s]

  7%|▋         | 2069/30196 [04:22<1:11:44,  6.53it/s]

  7%|▋         | 2070/30196 [04:22<1:13:55,  6.34it/s]

  7%|▋         | 2071/30196 [04:22<1:10:19,  6.67it/s]

  7%|▋         | 2073/30196 [04:22<54:16,  8.64it/s]

  7%|▋         | 2074/30196 [04:22<1:00:19,  7.77it/s]

  7%|▋         | 2075/30196 [04:22<1:02:05,  7.55it/s]

  7%|▋         | 2076/30196 [04:23<58:39,  7.99it/s]

  7%|▋         | 2078/30196 [04:23<54:55,  8.53it/s]

  7%|▋         | 2080/30196 [04:23<54:25,  8.61it/s]

  7%|▋         | 2082/30196 [04:23<46:04, 10.17it/s]

  7%|▋         | 2084/30196 [04:23<45:14, 10.36it/s]

  7%|▋         | 2086/30196 [04:24<47:39,  9.83it/s]

  7%|▋         | 2088/30196 [04:24<54:31,  8.59it/s]

  7%|▋         | 2090/30196 [04:24<59:21,  7.89it/s]

  7%|▋         | 2091/30196 [04:24<57:29,  8.15it/s]

  7%|▋         | 2092/30196 [04:24<58:13,  8.05it/s]

  7%|▋         | 2093/30196 [04:25<1:07:34,  6.93it/s]

  7%|▋         | 2095/30196 [04:25<59:02,  7.93it/s]

  7%|▋         | 2096/30196 [04:25<56:48,  8.25it/s]

  7%|▋         | 2098/30196 [04:25<53:00,  8.83it/s]

  7%|▋         | 2100/30196 [04:25<46:24, 10.09it/s]

  7%|▋         | 2102/30196 [04:25<43:06, 10.86it/s]

  7%|▋         | 2104/30196 [04:26<48:21,  9.68it/s]

  7%|▋         | 2106/30196 [04:26<44:52, 10.43it/s]

  7%|▋         | 2108/30196 [04:26<53:35,  8.73it/s]

  7%|▋         | 2109/30196 [04:26<1:09:32,  6.73it/s]

  7%|▋         | 2111/30196 [04:27<54:00,  8.67it/s]

  7%|▋         | 2113/30196 [04:27<54:00,  8.67it/s]

  7%|▋         | 2115/30196 [04:27<53:59,  8.67it/s]

  7%|▋         | 2116/30196 [04:27<55:19,  8.46it/s]

  7%|▋         | 2118/30196 [04:27<51:17,  9.12it/s]

  7%|▋         | 2119/30196 [04:27<54:21,  8.61it/s]

  7%|▋         | 2121/30196 [04:28<51:07,  9.15it/s]

  7%|▋         | 2122/30196 [04:28<53:36,  8.73it/s]

  7%|▋         | 2123/30196 [04:28<1:00:14,  7.77it/s]

  7%|▋         | 2124/30196 [04:28<1:01:19,  7.63it/s]

  7%|▋         | 2125/30196 [04:28<1:29:26,  5.23it/s]

  7%|▋         | 2127/30196 [04:29<1:19:21,  5.90it/s]

  7%|▋         | 2129/30196 [04:29<1:02:21,  7.50it/s]

  7%|▋         | 2130/30196 [04:29<1:00:03,  7.79it/s]

  7%|▋         | 2132/30196 [04:29<1:02:28,  7.49it/s]

  7%|▋         | 2134/30196 [04:30<1:01:42,  7.58it/s]

  7%|▋         | 2135/30196 [04:30<1:09:07,  6.77it/s]

  7%|▋         | 2136/30196 [04:30<1:16:04,  6.15it/s]

  7%|▋         | 2137/30196 [04:30<1:13:37,  6.35it/s]

  7%|▋         | 2138/30196 [04:30<1:15:04,  6.23it/s]

  7%|▋         | 2139/30196 [04:30<1:16:45,  6.09it/s]

  7%|▋         | 2140/30196 [04:31<1:12:44,  6.43it/s]

  7%|▋         | 2141/30196 [04:31<1:06:43,  7.01it/s]

  7%|▋         | 2142/30196 [04:31<1:44:06,  4.49it/s]

  7%|▋         | 2143/30196 [04:31<1:48:43,  4.30it/s]

  7%|▋         | 2145/30196 [04:32<1:16:38,  6.10it/s]

  7%|▋         | 2146/30196 [04:32<1:12:47,  6.42it/s]

  7%|▋         | 2147/30196 [04:32<1:42:37,  4.56it/s]

  7%|▋         | 2148/30196 [04:32<1:36:14,  4.86it/s]

  7%|▋         | 2149/30196 [04:32<1:23:39,  5.59it/s]

  7%|▋         | 2150/30196 [04:32<1:13:46,  6.34it/s]

  7%|▋         | 2151/30196 [04:33<1:15:46,  6.17it/s]

  7%|▋         | 2152/30196 [04:33<1:11:29,  6.54it/s]

  7%|▋         | 2154/30196 [04:33<1:00:44,  7.69it/s]

  7%|▋         | 2156/30196 [04:33<54:32,  8.57it/s]

  7%|▋         | 2158/30196 [04:33<55:45,  8.38it/s]

  7%|▋         | 2160/30196 [04:34<56:51,  8.22it/s]

  7%|▋         | 2161/30196 [04:34<55:19,  8.45it/s]

  7%|▋         | 2162/30196 [04:34<1:00:06,  7.77it/s]

  7%|▋         | 2163/30196 [04:34<1:05:04,  7.18it/s]

  7%|▋         | 2164/30196 [04:34<1:02:03,  7.53it/s]

  7%|▋         | 2166/30196 [04:34<59:59,  7.79it/s]

  7%|▋         | 2167/30196 [04:35<1:05:04,  7.18it/s]

  7%|▋         | 2168/30196 [04:35<1:15:28,  6.19it/s]

  7%|▋         | 2169/30196 [04:35<1:16:17,  6.12it/s]

  7%|▋         | 2170/30196 [04:35<1:12:10,  6.47it/s]

  7%|▋         | 2172/30196 [04:35<53:38,  8.71it/s]

  7%|▋         | 2173/30196 [04:35<56:12,  8.31it/s]

  7%|▋         | 2175/30196 [04:36<1:38:06,  4.76it/s]

  7%|▋         | 2177/30196 [04:36<1:12:38,  6.43it/s]

  7%|▋         | 2179/30196 [04:36<1:00:43,  7.69it/s]

  7%|▋         | 2181/30196 [04:37<1:33:02,  5.02it/s]

  7%|▋         | 2182/30196 [04:37<1:27:21,  5.34it/s]

  7%|▋         | 2183/30196 [04:37<1:26:12,  5.42it/s]

  7%|▋         | 2184/30196 [04:38<1:24:33,  5.52it/s]

  7%|▋         | 2185/30196 [04:38<1:22:38,  5.65it/s]

  7%|▋         | 2186/30196 [04:38<1:14:29,  6.27it/s]

  7%|▋         | 2187/30196 [04:38<1:15:50,  6.16it/s]

  7%|▋         | 2189/30196 [04:38<58:04,  8.04it/s]

  7%|▋         | 2191/30196 [04:38<47:57,  9.73it/s]

  7%|▋         | 2193/30196 [04:39<51:12,  9.11it/s]

  7%|▋         | 2195/30196 [04:39<43:30, 10.73it/s]

  7%|▋         | 2197/30196 [04:39<49:52,  9.36it/s]

  7%|▋         | 2199/30196 [04:39<49:39,  9.40it/s]

  7%|▋         | 2201/30196 [04:40<1:16:10,  6.13it/s]

  7%|▋         | 2202/30196 [04:40<1:16:21,  6.11it/s]

  7%|▋         | 2203/30196 [04:40<1:10:40,  6.60it/s]

  7%|▋         | 2204/30196 [04:40<1:10:18,  6.64it/s]

  7%|▋         | 2205/30196 [04:40<1:08:13,  6.84it/s]

  7%|▋         | 2206/30196 [04:41<1:17:11,  6.04it/s]

  7%|▋         | 2207/30196 [04:41<1:13:58,  6.31it/s]

  7%|▋         | 2209/30196 [04:41<1:04:41,  7.21it/s]

  7%|▋         | 2210/30196 [04:41<1:12:12,  6.46it/s]

  7%|▋         | 2212/30196 [04:41<58:54,  7.92it/s]

  7%|▋         | 2213/30196 [04:41<1:03:12,  7.38it/s]

  7%|▋         | 2214/30196 [04:42<1:03:14,  7.37it/s]

  7%|▋         | 2215/30196 [04:42<1:00:10,  7.75it/s]

  7%|▋         | 2216/30196 [04:42<57:26,  8.12it/s]

  7%|▋         | 2218/30196 [04:42<53:33,  8.71it/s]

  7%|▋         | 2220/30196 [04:42<53:30,  8.71it/s]

  7%|▋         | 2222/30196 [04:42<55:56,  8.33it/s]

  7%|▋         | 2224/30196 [04:43<51:45,  9.01it/s]

  7%|▋         | 2225/30196 [04:43<1:10:02,  6.66it/s]

  7%|▋         | 2227/30196 [04:43<1:04:06,  7.27it/s]

  7%|▋         | 2229/30196 [04:43<1:00:22,  7.72it/s]

  7%|▋         | 2230/30196 [04:44<1:01:53,  7.53it/s]

  7%|▋         | 2232/30196 [04:44<59:25,  7.84it/s]

  7%|▋         | 2233/30196 [04:44<1:10:20,  6.63it/s]

  7%|▋         | 2234/30196 [04:44<1:08:11,  6.83it/s]

  7%|▋         | 2236/30196 [04:44<59:46,  7.79it/s]

  7%|▋         | 2238/30196 [04:45<57:06,  8.16it/s]

  7%|▋         | 2239/30196 [04:45<1:01:29,  7.58it/s]

  7%|▋         | 2241/30196 [04:45<50:10,  9.29it/s]

  7%|▋         | 2243/30196 [04:45<42:23, 10.99it/s]

  7%|▋         | 2245/30196 [04:45<48:07,  9.68it/s]

  7%|▋         | 2247/30196 [04:45<48:36,  9.58it/s]

  7%|▋         | 2249/30196 [04:46<49:14,  9.46it/s]

  7%|▋         | 2250/30196 [04:46<52:45,  8.83it/s]

  7%|▋         | 2251/30196 [04:46<52:23,  8.89it/s]

  7%|▋         | 2253/30196 [04:46<48:57,  9.51it/s]

  7%|▋         | 2255/30196 [04:46<52:41,  8.84it/s]

  7%|▋         | 2257/30196 [04:47<54:10,  8.60it/s]

  7%|▋         | 2258/30196 [04:47<55:56,  8.32it/s]

  7%|▋         | 2260/30196 [04:47<46:23, 10.04it/s]

  7%|▋         | 2262/30196 [04:47<44:37, 10.43it/s]

  7%|▋         | 2264/30196 [04:47<52:12,  8.92it/s]

  8%|▊         | 2265/30196 [04:48<57:14,  8.13it/s]

  8%|▊         | 2266/30196 [04:48<55:59,  8.31it/s]

  8%|▊         | 2267/30196 [04:48<57:36,  8.08it/s]

  8%|▊         | 2268/30196 [04:48<58:27,  7.96it/s]

  8%|▊         | 2269/30196 [04:48<59:09,  7.87it/s]

  8%|▊         | 2271/30196 [04:48<56:50,  8.19it/s]

  8%|▊         | 2273/30196 [04:49<53:44,  8.66it/s]

  8%|▊         | 2275/30196 [04:49<49:56,  9.32it/s]

  8%|▊         | 2276/30196 [04:49<55:31,  8.38it/s]

  8%|▊         | 2277/30196 [04:49<57:06,  8.15it/s]

  8%|▊         | 2279/30196 [04:49<54:02,  8.61it/s]

  8%|▊         | 2281/30196 [04:49<51:35,  9.02it/s]

  8%|▊         | 2282/30196 [04:50<53:31,  8.69it/s]

  8%|▊         | 2283/30196 [04:50<1:00:07,  7.74it/s]

  8%|▊         | 2285/30196 [04:50<57:48,  8.05it/s]

  8%|▊         | 2287/30196 [04:50<57:20,  8.11it/s]

  8%|▊         | 2288/30196 [04:51<1:19:24,  5.86it/s]

  8%|▊         | 2289/30196 [04:51<1:29:58,  5.17it/s]

  8%|▊         | 2291/30196 [04:51<1:12:31,  6.41it/s]

  8%|▊         | 2292/30196 [04:51<1:11:00,  6.55it/s]

  8%|▊         | 2293/30196 [04:51<1:14:03,  6.28it/s]

  8%|▊         | 2294/30196 [04:51<1:12:15,  6.44it/s]

  8%|▊         | 2296/30196 [04:52<58:01,  8.01it/s]

  8%|▊         | 2298/30196 [04:52<49:35,  9.37it/s]

  8%|▊         | 2299/30196 [04:52<52:53,  8.79it/s]

  8%|▊         | 2301/30196 [04:52<49:56,  9.31it/s]

  8%|▊         | 2303/30196 [04:52<44:09, 10.53it/s]

  8%|▊         | 2305/30196 [04:53<49:28,  9.40it/s]

  8%|▊         | 2307/30196 [04:53<1:04:24,  7.22it/s]

  8%|▊         | 2308/30196 [04:53<1:01:31,  7.55it/s]

  8%|▊         | 2310/30196 [04:53<53:45,  8.64it/s]

  8%|▊         | 2312/30196 [04:53<53:49,  8.63it/s]

  8%|▊         | 2314/30196 [04:54<1:07:23,  6.90it/s]

  8%|▊         | 2315/30196 [04:54<1:21:14,  5.72it/s]

  8%|▊         | 2317/30196 [04:54<1:09:35,  6.68it/s]

  8%|▊         | 2319/30196 [04:55<59:39,  7.79it/s]

  8%|▊         | 2320/30196 [04:55<1:07:44,  6.86it/s]

  8%|▊         | 2322/30196 [04:55<56:25,  8.23it/s]

  8%|▊         | 2324/30196 [04:55<57:28,  8.08it/s]

  8%|▊         | 2325/30196 [04:55<55:47,  8.33it/s]

  8%|▊         | 2326/30196 [04:55<1:00:44,  7.65it/s]

  8%|▊         | 2328/30196 [04:56<57:05,  8.14it/s]

  8%|▊         | 2329/30196 [04:56<1:13:09,  6.35it/s]

  8%|▊         | 2330/30196 [04:56<1:11:19,  6.51it/s]

  8%|▊         | 2332/30196 [04:56<54:10,  8.57it/s]

  8%|▊         | 2333/30196 [04:56<1:04:56,  7.15it/s]

  8%|▊         | 2334/30196 [04:57<1:04:18,  7.22it/s]

  8%|▊         | 2335/30196 [04:57<1:03:57,  7.26it/s]

  8%|▊         | 2337/30196 [04:57<59:51,  7.76it/s]

  8%|▊         | 2338/30196 [04:57<1:01:02,  7.61it/s]

  8%|▊         | 2339/30196 [04:57<1:05:09,  7.13it/s]

  8%|▊         | 2341/30196 [04:57<59:55,  7.75it/s]

  8%|▊         | 2342/30196 [04:58<1:04:17,  7.22it/s]

  8%|▊         | 2344/30196 [04:58<1:24:55,  5.47it/s]

  8%|▊         | 2345/30196 [04:58<1:20:37,  5.76it/s]

  8%|▊         | 2346/30196 [04:58<1:13:36,  6.31it/s]

  8%|▊         | 2347/30196 [04:59<1:19:37,  5.83it/s]

  8%|▊         | 2348/30196 [04:59<1:23:59,  5.53it/s]

  8%|▊         | 2349/30196 [04:59<1:27:10,  5.32it/s]

  8%|▊         | 2350/30196 [04:59<1:19:46,  5.82it/s]

  8%|▊         | 2352/30196 [04:59<1:00:27,  7.67it/s]

  8%|▊         | 2353/30196 [04:59<1:05:25,  7.09it/s]

  8%|▊         | 2355/30196 [05:00<1:44:11,  4.45it/s]

  8%|▊         | 2356/30196 [05:00<1:44:31,  4.44it/s]

  8%|▊         | 2357/30196 [05:01<1:35:38,  4.85it/s]

  8%|▊         | 2358/30196 [05:01<1:35:46,  4.84it/s]

  8%|▊         | 2360/30196 [05:01<1:06:18,  7.00it/s]

  8%|▊         | 2361/30196 [05:01<1:05:59,  7.03it/s]

  8%|▊         | 2362/30196 [05:01<1:18:28,  5.91it/s]

  8%|▊         | 2363/30196 [05:01<1:14:28,  6.23it/s]

  8%|▊         | 2364/30196 [05:02<1:11:08,  6.52it/s]

  8%|▊         | 2366/30196 [05:02<1:09:14,  6.70it/s]

  8%|▊         | 2368/30196 [05:02<1:02:35,  7.41it/s]

  8%|▊         | 2370/30196 [05:02<1:08:33,  6.77it/s]

  8%|▊         | 2371/30196 [05:03<1:07:59,  6.82it/s]

  8%|▊         | 2373/30196 [05:03<55:34,  8.34it/s]

  8%|▊         | 2375/30196 [05:03<53:55,  8.60it/s]

  8%|▊         | 2376/30196 [05:03<56:47,  8.16it/s]

  8%|▊         | 2378/30196 [05:03<51:01,  9.09it/s]

  8%|▊         | 2381/30196 [05:03<40:13, 11.53it/s]

  8%|▊         | 2383/30196 [05:04<49:32,  9.36it/s]

  8%|▊         | 2385/30196 [05:04<48:32,  9.55it/s]

  8%|▊         | 2387/30196 [05:04<54:20,  8.53it/s]

  8%|▊         | 2389/30196 [05:04<47:40,  9.72it/s]

  8%|▊         | 2391/30196 [05:05<55:38,  8.33it/s]

  8%|▊         | 2392/30196 [05:05<54:55,  8.44it/s]

  8%|▊         | 2393/30196 [05:05<1:13:58,  6.26it/s]

  8%|▊         | 2394/30196 [05:05<1:12:44,  6.37it/s]

  8%|▊         | 2395/30196 [05:05<1:07:28,  6.87it/s]

  8%|▊         | 2396/30196 [05:05<1:03:17,  7.32it/s]

  8%|▊         | 2398/30196 [05:06<51:32,  8.99it/s]

  8%|▊         | 2399/30196 [05:06<58:41,  7.89it/s]

  8%|▊         | 2401/30196 [05:06<46:16, 10.01it/s]

  8%|▊         | 2403/30196 [05:06<56:54,  8.14it/s]

  8%|▊         | 2404/30196 [05:06<1:02:23,  7.42it/s]

  8%|▊         | 2405/30196 [05:07<1:11:40,  6.46it/s]

  8%|▊         | 2406/30196 [05:07<1:14:25,  6.22it/s]

  8%|▊         | 2408/30196 [05:07<57:36,  8.04it/s]

  8%|▊         | 2410/30196 [05:07<48:02,  9.64it/s]

  8%|▊         | 2412/30196 [05:07<42:04, 11.00it/s]

  8%|▊         | 2414/30196 [05:08<1:19:37,  5.82it/s]

  8%|▊         | 2415/30196 [05:08<1:15:54,  6.10it/s]

  8%|▊         | 2417/30196 [05:09<2:03:57,  3.74it/s]

  8%|▊         | 2418/30196 [05:09<1:52:16,  4.12it/s]

  8%|▊         | 2419/30196 [05:09<1:38:47,  4.69it/s]

  8%|▊         | 2420/30196 [05:09<1:31:13,  5.07it/s]

  8%|▊         | 2422/30196 [05:09<1:06:57,  6.91it/s]

  8%|▊         | 2423/30196 [05:10<1:07:04,  6.90it/s]

  8%|▊         | 2424/30196 [05:10<1:06:11,  6.99it/s]

  8%|▊         | 2425/30196 [05:10<1:21:57,  5.65it/s]

  8%|▊         | 2426/30196 [05:10<1:18:04,  5.93it/s]

  8%|▊         | 2427/30196 [05:10<1:11:17,  6.49it/s]

  8%|▊         | 2428/30196 [05:11<1:22:26,  5.61it/s]

  8%|▊         | 2430/30196 [05:11<1:01:24,  7.54it/s]

  8%|▊         | 2431/30196 [05:11<1:19:43,  5.80it/s]

  8%|▊         | 2432/30196 [05:11<1:12:19,  6.40it/s]

  8%|▊         | 2434/30196 [05:11<1:07:30,  6.85it/s]

  8%|▊         | 2435/30196 [05:12<1:16:04,  6.08it/s]

  8%|▊         | 2437/30196 [05:12<59:16,  7.81it/s]

  8%|▊         | 2438/30196 [05:12<1:04:27,  7.18it/s]

  8%|▊         | 2439/30196 [05:12<1:01:58,  7.46it/s]

  8%|▊         | 2441/30196 [05:12<56:54,  8.13it/s]

  8%|▊         | 2442/30196 [05:12<56:02,  8.25it/s]

  8%|▊         | 2443/30196 [05:13<1:01:43,  7.49it/s]

  8%|▊         | 2445/30196 [05:13<49:56,  9.26it/s]

  8%|▊         | 2446/30196 [05:13<1:07:10,  6.89it/s]

  8%|▊         | 2447/30196 [05:13<1:04:49,  7.14it/s]

  8%|▊         | 2448/30196 [05:13<1:06:08,  6.99it/s]

  8%|▊         | 2450/30196 [05:13<54:57,  8.41it/s]

  8%|▊         | 2451/30196 [05:14<56:42,  8.15it/s]

  8%|▊         | 2452/30196 [05:14<1:01:47,  7.48it/s]

  8%|▊         | 2453/30196 [05:14<58:31,  7.90it/s]

  8%|▊         | 2454/30196 [05:14<1:00:17,  7.67it/s]

  8%|▊         | 2456/30196 [05:14<51:17,  9.01it/s]

  8%|▊         | 2458/30196 [05:14<47:49,  9.67it/s]

  8%|▊         | 2459/30196 [05:14<50:25,  9.17it/s]

  8%|▊         | 2460/30196 [05:15<57:20,  8.06it/s]

  8%|▊         | 2461/30196 [05:15<55:30,  8.33it/s]

  8%|▊         | 2463/30196 [05:15<45:34, 10.14it/s]

  8%|▊         | 2465/30196 [05:15<39:56, 11.57it/s]

  8%|▊         | 2467/30196 [05:15<41:42, 11.08it/s]

  8%|▊         | 2469/30196 [05:15<36:17, 12.73it/s]

  8%|▊         | 2471/30196 [05:15<38:01, 12.15it/s]

  8%|▊         | 2473/30196 [05:16<44:10, 10.46it/s]

  8%|▊         | 2475/30196 [05:16<1:16:31,  6.04it/s]

  8%|▊         | 2477/30196 [05:17<1:09:00,  6.69it/s]

  8%|▊         | 2478/30196 [05:17<1:08:48,  6.71it/s]

  8%|▊         | 2480/30196 [05:17<57:58,  7.97it/s]

  8%|▊         | 2481/30196 [05:17<1:01:56,  7.46it/s]

  8%|▊         | 2483/30196 [05:18<1:41:48,  4.54it/s]

  8%|▊         | 2484/30196 [05:18<1:38:12,  4.70it/s]

  8%|▊         | 2486/30196 [05:18<1:22:23,  5.61it/s]

  8%|▊         | 2488/30196 [05:18<1:10:53,  6.51it/s]

  8%|▊         | 2489/30196 [05:19<1:08:37,  6.73it/s]

  8%|▊         | 2490/30196 [05:19<1:07:46,  6.81it/s]

  8%|▊         | 2491/30196 [05:19<1:22:50,  5.57it/s]

  8%|▊         | 2493/30196 [05:19<1:04:15,  7.19it/s]

  8%|▊         | 2494/30196 [05:19<1:04:33,  7.15it/s]

  8%|▊         | 2495/30196 [05:20<1:12:16,  6.39it/s]

  8%|▊         | 2498/30196 [05:20<47:58,  9.62it/s]

  8%|▊         | 2500/30196 [05:20<57:47,  7.99it/s]

  8%|▊         | 2501/30196 [05:20<59:36,  7.74it/s]

  8%|▊         | 2502/30196 [05:20<57:44,  7.99it/s]

  8%|▊         | 2504/30196 [05:20<48:22,  9.54it/s]

  8%|▊         | 2506/30196 [05:21<42:23, 10.89it/s]

  8%|▊         | 2508/30196 [05:21<51:32,  8.95it/s]

  8%|▊         | 2510/30196 [05:21<1:03:13,  7.30it/s]

  8%|▊         | 2511/30196 [05:21<1:03:31,  7.26it/s]

  8%|▊         | 2513/30196 [05:22<56:53,  8.11it/s]

  8%|▊         | 2514/30196 [05:22<55:08,  8.37it/s]

  8%|▊         | 2515/30196 [05:22<1:00:45,  7.59it/s]

  8%|▊         | 2516/30196 [05:22<1:00:41,  7.60it/s]

  8%|▊         | 2518/30196 [05:22<53:28,  8.63it/s]

  8%|▊         | 2519/30196 [05:22<55:33,  8.30it/s]

  8%|▊         | 2520/30196 [05:22<57:09,  8.07it/s]

  8%|▊         | 2521/30196 [05:23<1:03:08,  7.30it/s]

  8%|▊         | 2523/30196 [05:23<55:41,  8.28it/s]

  8%|▊         | 2525/30196 [05:23<45:41, 10.09it/s]

  8%|▊         | 2527/30196 [05:23<49:37,  9.29it/s]

  8%|▊         | 2528/30196 [05:23<49:39,  9.29it/s]

  8%|▊         | 2530/30196 [05:24<51:23,  8.97it/s]

  8%|▊         | 2531/30196 [05:24<53:14,  8.66it/s]

  8%|▊         | 2533/30196 [05:24<47:47,  9.65it/s]

  8%|▊         | 2534/30196 [05:24<51:57,  8.87it/s]

  8%|▊         | 2535/30196 [05:24<1:00:30,  7.62it/s]

  8%|▊         | 2536/30196 [05:24<1:12:00,  6.40it/s]

  8%|▊         | 2537/30196 [05:24<1:06:34,  6.92it/s]

  8%|▊         | 2538/30196 [05:25<1:09:51,  6.60it/s]

  8%|▊         | 2539/30196 [05:25<1:13:15,  6.29it/s]

  8%|▊         | 2540/30196 [05:25<1:06:04,  6.98it/s]

  8%|▊         | 2541/30196 [05:25<1:01:42,  7.47it/s]

  8%|▊         | 2542/30196 [05:25<1:07:34,  6.82it/s]

  8%|▊         | 2543/30196 [05:25<1:02:30,  7.37it/s]

  8%|▊         | 2544/30196 [05:26<1:08:36,  6.72it/s]

  8%|▊         | 2545/30196 [05:26<1:03:14,  7.29it/s]

  8%|▊         | 2546/30196 [05:26<1:07:30,  6.83it/s]

  8%|▊         | 2548/30196 [05:26<53:23,  8.63it/s]

  8%|▊         | 2550/30196 [05:26<45:55, 10.03it/s]

  8%|▊         | 2552/30196 [05:26<48:21,  9.53it/s]

  8%|▊         | 2553/30196 [05:26<51:46,  8.90it/s]

  8%|▊         | 2555/30196 [05:27<53:54,  8.55it/s]

  8%|▊         | 2556/30196 [05:27<55:43,  8.27it/s]

  8%|▊         | 2558/30196 [05:27<51:41,  8.91it/s]

  8%|▊         | 2560/30196 [05:27<43:55, 10.49it/s]

  8%|▊         | 2562/30196 [05:27<50:33,  9.11it/s]

  8%|▊         | 2564/30196 [05:28<48:54,  9.42it/s]

  8%|▊         | 2565/30196 [05:28<54:27,  8.46it/s]

  8%|▊         | 2566/30196 [05:28<55:41,  8.27it/s]

  9%|▊         | 2568/30196 [05:28<45:48, 10.05it/s]

  9%|▊         | 2570/30196 [05:28<50:11,  9.17it/s]

  9%|▊         | 2571/30196 [05:29<55:39,  8.27it/s]

  9%|▊         | 2573/30196 [05:29<57:19,  8.03it/s]

  9%|▊         | 2575/30196 [05:29<55:05,  8.36it/s]

  9%|▊         | 2576/30196 [05:29<1:00:30,  7.61it/s]

  9%|▊         | 2577/30196 [05:29<1:04:24,  7.15it/s]

  9%|▊         | 2579/30196 [05:30<59:12,  7.77it/s]

  9%|▊         | 2580/30196 [05:30<57:24,  8.02it/s]

  9%|▊         | 2582/30196 [05:30<55:33,  8.28it/s]

  9%|▊         | 2584/30196 [05:30<55:04,  8.36it/s]

  9%|▊         | 2586/30196 [05:30<48:40,  9.45it/s]

  9%|▊         | 2588/30196 [05:31<52:07,  8.83it/s]

  9%|▊         | 2590/30196 [05:31<44:09, 10.42it/s]

  9%|▊         | 2592/30196 [05:31<45:18, 10.16it/s]

  9%|▊         | 2594/30196 [05:31<48:18,  9.52it/s]

  9%|▊         | 2596/30196 [05:31<47:02,  9.78it/s]

  9%|▊         | 2598/30196 [05:32<54:57,  8.37it/s]

  9%|▊         | 2600/30196 [05:32<50:42,  9.07it/s]

  9%|▊         | 2601/30196 [05:32<53:10,  8.65it/s]

  9%|▊         | 2602/30196 [05:32<57:48,  7.96it/s]

  9%|▊         | 2603/30196 [05:32<59:14,  7.76it/s]

  9%|▊         | 2604/30196 [05:32<1:03:19,  7.26it/s]

  9%|▊         | 2605/30196 [05:33<1:06:24,  6.92it/s]

  9%|▊         | 2607/30196 [05:33<1:06:01,  6.96it/s]

  9%|▊         | 2609/30196 [05:33<1:19:09,  5.81it/s]

  9%|▊         | 2611/30196 [05:34<1:12:28,  6.34it/s]

  9%|▊         | 2612/30196 [05:34<1:11:02,  6.47it/s]

  9%|▊         | 2613/30196 [05:34<1:18:52,  5.83it/s]

  9%|▊         | 2614/30196 [05:34<1:19:41,  5.77it/s]

  9%|▊         | 2615/30196 [05:34<1:15:07,  6.12it/s]

  9%|▊         | 2617/30196 [05:34<1:02:11,  7.39it/s]

  9%|▊         | 2619/30196 [05:35<50:32,  9.09it/s]

  9%|▊         | 2621/30196 [05:35<47:12,  9.73it/s]

  9%|▊         | 2623/30196 [05:35<53:23,  8.61it/s]

  9%|▊         | 2624/30196 [05:35<54:42,  8.40it/s]

  9%|▊         | 2625/30196 [05:35<56:36,  8.12it/s]

  9%|▊         | 2626/30196 [05:35<1:01:20,  7.49it/s]

  9%|▊         | 2628/30196 [05:36<53:47,  8.54it/s]

  9%|▊         | 2629/30196 [05:36<55:09,  8.33it/s]

  9%|▊         | 2630/30196 [05:36<58:16,  7.88it/s]

  9%|▊         | 2631/30196 [05:36<58:48,  7.81it/s]

  9%|▊         | 2633/30196 [05:36<51:16,  8.96it/s]

  9%|▊         | 2634/30196 [05:36<53:07,  8.65it/s]

  9%|▊         | 2636/30196 [05:37<1:06:16,  6.93it/s]

  9%|▊         | 2637/30196 [05:37<1:06:02,  6.96it/s]

  9%|▊         | 2639/30196 [05:37<50:37,  9.07it/s]

  9%|▊         | 2641/30196 [05:37<47:17,  9.71it/s]

  9%|▉         | 2643/30196 [05:37<51:39,  8.89it/s]

  9%|▉         | 2644/30196 [05:38<53:55,  8.52it/s]

  9%|▉         | 2646/30196 [05:38<52:54,  8.68it/s]

  9%|▉         | 2648/30196 [05:38<44:17, 10.37it/s]

  9%|▉         | 2650/30196 [05:38<45:00, 10.20it/s]

  9%|▉         | 2652/30196 [05:38<56:31,  8.12it/s]

  9%|▉         | 2654/30196 [05:39<46:07,  9.95it/s]

  9%|▉         | 2656/30196 [05:39<49:27,  9.28it/s]

  9%|▉         | 2658/30196 [05:39<51:14,  8.96it/s]

  9%|▉         | 2660/30196 [05:39<49:45,  9.22it/s]

  9%|▉         | 2662/30196 [05:40<1:00:37,  7.57it/s]

  9%|▉         | 2663/30196 [05:40<1:01:21,  7.48it/s]

  9%|▉         | 2665/30196 [05:40<51:48,  8.86it/s]

  9%|▉         | 2666/30196 [05:40<56:31,  8.12it/s]

  9%|▉         | 2667/30196 [05:40<1:04:48,  7.08it/s]

  9%|▉         | 2669/30196 [05:41<58:14,  7.88it/s]

  9%|▉         | 2670/30196 [05:41<1:02:11,  7.38it/s]

  9%|▉         | 2671/30196 [05:41<1:07:01,  6.84it/s]

  9%|▉         | 2673/30196 [05:41<53:53,  8.51it/s]

  9%|▉         | 2674/30196 [05:41<59:26,  7.72it/s]

  9%|▉         | 2676/30196 [05:41<1:01:41,  7.44it/s]

  9%|▉         | 2677/30196 [05:42<58:43,  7.81it/s]

  9%|▉         | 2679/30196 [05:42<48:03,  9.54it/s]

  9%|▉         | 2681/30196 [05:42<48:00,  9.55it/s]

  9%|▉         | 2683/30196 [05:42<51:14,  8.95it/s]

  9%|▉         | 2684/30196 [05:42<59:34,  7.70it/s]

  9%|▉         | 2685/30196 [05:43<1:09:23,  6.61it/s]

  9%|▉         | 2687/30196 [05:43<55:15,  8.30it/s]

  9%|▉         | 2689/30196 [05:43<47:09,  9.72it/s]

  9%|▉         | 2691/30196 [05:43<49:13,  9.31it/s]

  9%|▉         | 2693/30196 [05:43<44:49, 10.23it/s]

  9%|▉         | 2695/30196 [05:44<52:58,  8.65it/s]

  9%|▉         | 2697/30196 [05:44<43:49, 10.46it/s]

  9%|▉         | 2699/30196 [05:44<47:51,  9.58it/s]

  9%|▉         | 2701/30196 [05:44<45:50, 10.00it/s]

  9%|▉         | 2703/30196 [05:44<53:16,  8.60it/s]

  9%|▉         | 2704/30196 [05:45<52:17,  8.76it/s]

  9%|▉         | 2706/30196 [05:45<48:01,  9.54it/s]

  9%|▉         | 2708/30196 [05:45<43:39, 10.49it/s]

  9%|▉         | 2710/30196 [05:45<42:54, 10.68it/s]

  9%|▉         | 2712/30196 [05:45<42:48, 10.70it/s]

  9%|▉         | 2714/30196 [05:45<45:26, 10.08it/s]

  9%|▉         | 2716/30196 [05:46<38:45, 11.82it/s]

  9%|▉         | 2718/30196 [05:46<52:30,  8.72it/s]

  9%|▉         | 2720/30196 [05:46<57:43,  7.93it/s]

  9%|▉         | 2722/30196 [05:46<56:25,  8.12it/s]

  9%|▉         | 2723/30196 [05:47<55:16,  8.28it/s]

  9%|▉         | 2724/30196 [05:47<56:34,  8.09it/s]

  9%|▉         | 2726/30196 [05:47<53:53,  8.50it/s]

  9%|▉         | 2727/30196 [05:47<56:45,  8.06it/s]

  9%|▉         | 2728/30196 [05:47<54:53,  8.34it/s]

  9%|▉         | 2729/30196 [05:47<53:09,  8.61it/s]

  9%|▉         | 2730/30196 [05:47<59:35,  7.68it/s]

  9%|▉         | 2731/30196 [05:48<1:00:07,  7.61it/s]

  9%|▉         | 2732/30196 [05:48<1:02:15,  7.35it/s]

  9%|▉         | 2733/30196 [05:48<1:01:37,  7.43it/s]

  9%|▉         | 2734/30196 [05:48<59:41,  7.67it/s]

  9%|▉         | 2735/30196 [05:48<1:01:46,  7.41it/s]

  9%|▉         | 2737/30196 [05:48<49:39,  9.22it/s]

  9%|▉         | 2739/30196 [05:48<43:15, 10.58it/s]

  9%|▉         | 2741/30196 [05:49<46:25,  9.86it/s]

  9%|▉         | 2742/30196 [05:49<53:10,  8.61it/s]

  9%|▉         | 2744/30196 [05:49<50:55,  8.98it/s]

  9%|▉         | 2745/30196 [05:49<53:26,  8.56it/s]

  9%|▉         | 2746/30196 [05:49<1:03:18,  7.23it/s]

  9%|▉         | 2747/30196 [05:50<1:02:26,  7.33it/s]

  9%|▉         | 2748/30196 [05:50<1:06:02,  6.93it/s]

  9%|▉         | 2750/30196 [05:50<59:31,  7.68it/s]

  9%|▉         | 2751/30196 [05:50<56:51,  8.04it/s]

  9%|▉         | 2752/30196 [05:50<1:03:23,  7.22it/s]

  9%|▉         | 2754/30196 [05:50<50:50,  9.00it/s]

  9%|▉         | 2755/30196 [05:50<50:13,  9.10it/s]

  9%|▉         | 2757/30196 [05:51<42:25, 10.78it/s]

  9%|▉         | 2759/30196 [05:51<43:38, 10.48it/s]

  9%|▉         | 2761/30196 [05:51<45:51,  9.97it/s]

  9%|▉         | 2763/30196 [05:51<54:18,  8.42it/s]

  9%|▉         | 2765/30196 [05:51<50:52,  8.99it/s]

  9%|▉         | 2766/30196 [05:52<53:27,  8.55it/s]

  9%|▉         | 2767/30196 [05:52<54:53,  8.33it/s]

  9%|▉         | 2768/30196 [05:52<53:15,  8.58it/s]

  9%|▉         | 2769/30196 [05:52<54:57,  8.32it/s]

  9%|▉         | 2770/30196 [05:52<53:08,  8.60it/s]

  9%|▉         | 2771/30196 [05:52<59:45,  7.65it/s]

  9%|▉         | 2773/30196 [05:52<47:33,  9.61it/s]

  9%|▉         | 2774/30196 [05:53<54:25,  8.40it/s]

  9%|▉         | 2776/30196 [05:53<49:28,  9.24it/s]

  9%|▉         | 2778/30196 [05:53<43:23, 10.53it/s]

  9%|▉         | 2780/30196 [05:53<45:59,  9.94it/s]

  9%|▉         | 2782/30196 [05:53<47:09,  9.69it/s]

  9%|▉         | 2784/30196 [05:54<43:13, 10.57it/s]

  9%|▉         | 2786/30196 [05:54<43:01, 10.62it/s]

  9%|▉         | 2788/30196 [05:54<45:05, 10.13it/s]

  9%|▉         | 2790/30196 [05:54<52:34,  8.69it/s]

  9%|▉         | 2792/30196 [05:54<49:33,  9.22it/s]

  9%|▉         | 2794/30196 [05:55<46:11,  9.89it/s]

  9%|▉         | 2796/30196 [05:55<51:25,  8.88it/s]

  9%|▉         | 2797/30196 [05:55<56:22,  8.10it/s]

  9%|▉         | 2799/30196 [05:55<47:26,  9.62it/s]

  9%|▉         | 2801/30196 [05:55<52:35,  8.68it/s]

  9%|▉         | 2802/30196 [05:56<1:00:57,  7.49it/s]

  9%|▉         | 2803/30196 [05:56<1:02:28,  7.31it/s]

  9%|▉         | 2804/30196 [05:56<1:11:02,  6.43it/s]

  9%|▉         | 2805/30196 [05:56<1:15:05,  6.08it/s]

  9%|▉         | 2806/30196 [05:56<1:12:29,  6.30it/s]

  9%|▉         | 2807/30196 [05:56<1:09:40,  6.55it/s]

  9%|▉         | 2808/30196 [05:57<1:06:11,  6.90it/s]

  9%|▉         | 2809/30196 [05:57<1:01:33,  7.42it/s]

  9%|▉         | 2810/30196 [05:57<1:07:25,  6.77it/s]

  9%|▉         | 2812/30196 [05:57<56:42,  8.05it/s]

  9%|▉         | 2813/30196 [05:57<55:03,  8.29it/s]

  9%|▉         | 2815/30196 [05:57<43:25, 10.51it/s]

  9%|▉         | 2817/30196 [05:58<44:02, 10.36it/s]

  9%|▉         | 2819/30196 [05:58<49:54,  9.14it/s]

  9%|▉         | 2820/30196 [05:58<52:10,  8.75it/s]

  9%|▉         | 2823/30196 [05:58<41:36, 10.97it/s]

  9%|▉         | 2825/30196 [05:58<43:38, 10.45it/s]

  9%|▉         | 2827/30196 [05:59<49:10,  9.28it/s]

  9%|▉         | 2828/30196 [05:59<55:08,  8.27it/s]

  9%|▉         | 2829/30196 [05:59<1:05:08,  7.00it/s]

  9%|▉         | 2830/30196 [05:59<1:05:47,  6.93it/s]

  9%|▉         | 2831/30196 [05:59<1:08:19,  6.68it/s]

  9%|▉         | 2833/30196 [06:00<1:05:53,  6.92it/s]

  9%|▉         | 2834/30196 [06:00<1:01:49,  7.38it/s]

  9%|▉         | 2835/30196 [06:00<58:22,  7.81it/s]

  9%|▉         | 2836/30196 [06:00<1:02:01,  7.35it/s]

  9%|▉         | 2837/30196 [06:00<1:10:02,  6.51it/s]

  9%|▉         | 2839/30196 [06:00<1:06:43,  6.83it/s]

  9%|▉         | 2840/30196 [06:01<1:08:05,  6.70it/s]

  9%|▉         | 2842/30196 [06:01<50:27,  9.04it/s]

  9%|▉         | 2844/30196 [06:01<58:20,  7.81it/s]

  9%|▉         | 2846/30196 [06:01<51:34,  8.84it/s]

  9%|▉         | 2848/30196 [06:01<49:05,  9.28it/s]

  9%|▉         | 2850/30196 [06:02<57:38,  7.91it/s]

  9%|▉         | 2851/30196 [06:02<1:01:05,  7.46it/s]

  9%|▉         | 2853/30196 [06:02<50:34,  9.01it/s]

  9%|▉         | 2855/30196 [06:02<45:16, 10.06it/s]

  9%|▉         | 2857/30196 [06:03<56:19,  8.09it/s]

  9%|▉         | 2858/30196 [06:03<54:44,  8.32it/s]

  9%|▉         | 2859/30196 [06:03<57:16,  7.95it/s]

  9%|▉         | 2860/30196 [06:03<54:52,  8.30it/s]

  9%|▉         | 2861/30196 [06:03<1:00:09,  7.57it/s]

  9%|▉         | 2863/30196 [06:03<47:45,  9.54it/s]

  9%|▉         | 2865/30196 [06:03<53:17,  8.55it/s]

  9%|▉         | 2866/30196 [06:04<57:06,  7.98it/s]

  9%|▉         | 2867/30196 [06:04<1:03:42,  7.15it/s]

  9%|▉         | 2868/30196 [06:04<1:08:56,  6.61it/s]

 10%|▉         | 2869/30196 [06:04<1:07:45,  6.72it/s]

 10%|▉         | 2871/30196 [06:04<55:38,  8.18it/s]

 10%|▉         | 2872/30196 [06:05<1:18:26,  5.81it/s]

 10%|▉         | 2873/30196 [06:05<1:11:30,  6.37it/s]

 10%|▉         | 2875/30196 [06:05<59:57,  7.60it/s]

 10%|▉         | 2877/30196 [06:05<48:22,  9.41it/s]

 10%|▉         | 2879/30196 [06:05<42:34, 10.69it/s]

 10%|▉         | 2881/30196 [06:05<43:48, 10.39it/s]

 10%|▉         | 2883/30196 [06:06<50:23,  9.03it/s]

 10%|▉         | 2884/30196 [06:06<53:13,  8.55it/s]

 10%|▉         | 2885/30196 [06:06<54:58,  8.28it/s]

 10%|▉         | 2886/30196 [06:06<53:42,  8.47it/s]

 10%|▉         | 2888/30196 [06:06<53:17,  8.54it/s]

 10%|▉         | 2889/30196 [06:06<59:09,  7.69it/s]

 10%|▉         | 2891/30196 [06:07<53:37,  8.49it/s]

 10%|▉         | 2893/30196 [06:07<49:05,  9.27it/s]

 10%|▉         | 2894/30196 [06:07<58:26,  7.79it/s]

 10%|▉         | 2896/30196 [06:07<50:56,  8.93it/s]

 10%|▉         | 2898/30196 [06:07<49:40,  9.16it/s]

 10%|▉         | 2899/30196 [06:08<56:11,  8.10it/s]

 10%|▉         | 2900/30196 [06:08<1:00:43,  7.49it/s]

 10%|▉         | 2902/30196 [06:08<52:58,  8.59it/s]

 10%|▉         | 2903/30196 [06:08<58:13,  7.81it/s]

 10%|▉         | 2904/30196 [06:08<1:02:29,  7.28it/s]

 10%|▉         | 2905/30196 [06:08<1:05:45,  6.92it/s]

 10%|▉         | 2907/30196 [06:09<55:46,  8.15it/s]

 10%|▉         | 2908/30196 [06:09<1:00:48,  7.48it/s]

 10%|▉         | 2909/30196 [06:09<1:08:28,  6.64it/s]

 10%|▉         | 2910/30196 [06:09<1:11:18,  6.38it/s]

 10%|▉         | 2911/30196 [06:09<1:14:14,  6.13it/s]

 10%|▉         | 2912/30196 [06:10<1:17:26,  5.87it/s]

 10%|▉         | 2913/30196 [06:10<1:11:06,  6.39it/s]

 10%|▉         | 2915/30196 [06:10<1:01:22,  7.41it/s]

 10%|▉         | 2917/30196 [06:10<56:26,  8.06it/s]

 10%|▉         | 2918/30196 [06:10<57:09,  7.95it/s]

 10%|▉         | 2920/30196 [06:10<47:52,  9.49it/s]

 10%|▉         | 2921/30196 [06:11<58:22,  7.79it/s]

 10%|▉         | 2923/30196 [06:11<55:18,  8.22it/s]

 10%|▉         | 2924/30196 [06:11<57:45,  7.87it/s]

 10%|▉         | 2925/30196 [06:11<1:02:01,  7.33it/s]

 10%|▉         | 2926/30196 [06:11<1:02:54,  7.23it/s]

 10%|▉         | 2927/30196 [06:11<1:04:00,  7.10it/s]

 10%|▉         | 2928/30196 [06:12<1:03:30,  7.16it/s]

 10%|▉         | 2929/30196 [06:12<1:02:42,  7.25it/s]

 10%|▉         | 2930/30196 [06:12<1:02:02,  7.32it/s]

 10%|▉         | 2931/30196 [06:12<58:46,  7.73it/s]

 10%|▉         | 2932/30196 [06:12<1:11:31,  6.35it/s]

 10%|▉         | 2933/30196 [06:12<1:08:51,  6.60it/s]

 10%|▉         | 2934/30196 [06:12<1:12:17,  6.28it/s]

 10%|▉         | 2935/30196 [06:13<1:14:15,  6.12it/s]

 10%|▉         | 2936/30196 [06:13<1:10:05,  6.48it/s]

 10%|▉         | 2937/30196 [06:13<1:28:21,  5.14it/s]

 10%|▉         | 2939/30196 [06:13<1:10:36,  6.43it/s]

 10%|▉         | 2940/30196 [06:13<1:13:29,  6.18it/s]

 10%|▉         | 2942/30196 [06:14<1:11:23,  6.36it/s]

 10%|▉         | 2943/30196 [06:14<1:12:22,  6.28it/s]

 10%|▉         | 2944/30196 [06:14<1:06:51,  6.79it/s]

 10%|▉         | 2946/30196 [06:14<54:50,  8.28it/s]

 10%|▉         | 2948/30196 [06:14<51:32,  8.81it/s]

 10%|▉         | 2949/30196 [06:15<53:44,  8.45it/s]

 10%|▉         | 2950/30196 [06:15<58:52,  7.71it/s]

 10%|▉         | 2951/30196 [06:15<1:02:30,  7.26it/s]

 10%|▉         | 2952/30196 [06:15<1:05:05,  6.98it/s]

 10%|▉         | 2953/30196 [06:15<1:12:17,  6.28it/s]

 10%|▉         | 2954/30196 [06:15<1:06:58,  6.78it/s]

 10%|▉         | 2955/30196 [06:16<1:06:08,  6.86it/s]

 10%|▉         | 2957/30196 [06:16<56:56,  7.97it/s]

 10%|▉         | 2958/30196 [06:16<55:02,  8.25it/s]

 10%|▉         | 2959/30196 [06:16<53:51,  8.43it/s]

 10%|▉         | 2960/30196 [06:16<55:49,  8.13it/s]

 10%|▉         | 2961/30196 [06:16<58:28,  7.76it/s]

 10%|▉         | 2962/30196 [06:16<57:07,  7.95it/s]

 10%|▉         | 2963/30196 [06:16<59:29,  7.63it/s]

 10%|▉         | 2964/30196 [06:17<1:01:37,  7.37it/s]

 10%|▉         | 2965/30196 [06:17<1:06:05,  6.87it/s]

 10%|▉         | 2966/30196 [06:17<1:01:15,  7.41it/s]

 10%|▉         | 2967/30196 [06:17<1:17:17,  5.87it/s]

 10%|▉         | 2968/30196 [06:18<2:51:47,  2.64it/s]

 10%|▉         | 2970/30196 [06:18<1:47:06,  4.24it/s]

 10%|▉         | 2971/30196 [06:18<1:41:51,  4.46it/s]

 10%|▉         | 2973/30196 [06:19<1:15:11,  6.03it/s]

 10%|▉         | 2975/30196 [06:19<1:03:42,  7.12it/s]

 10%|▉         | 2976/30196 [06:19<1:03:45,  7.11it/s]

 10%|▉         | 2977/30196 [06:19<1:04:28,  7.04it/s]

 10%|▉         | 2979/30196 [06:19<1:02:05,  7.31it/s]

 10%|▉         | 2980/30196 [06:19<1:05:16,  6.95it/s]

 10%|▉         | 2981/30196 [06:20<1:13:07,  6.20it/s]

 10%|▉         | 2982/30196 [06:20<1:11:42,  6.32it/s]

 10%|▉         | 2984/30196 [06:20<1:00:27,  7.50it/s]

 10%|▉         | 2985/30196 [06:20<1:04:58,  6.98it/s]

 10%|▉         | 2987/30196 [06:20<1:02:20,  7.27it/s]

 10%|▉         | 2988/30196 [06:21<1:10:41,  6.41it/s]

 10%|▉         | 2991/30196 [06:21<47:24,  9.56it/s]

 10%|▉         | 2993/30196 [06:21<46:42,  9.71it/s]

 10%|▉         | 2995/30196 [06:21<49:10,  9.22it/s]

 10%|▉         | 2997/30196 [06:21<43:03, 10.53it/s]

 10%|▉         | 2999/30196 [06:22<46:34,  9.73it/s]

 10%|▉         | 3002/30196 [06:22<39:22, 11.51it/s]

 10%|▉         | 3004/30196 [06:22<41:37, 10.89it/s]

 10%|▉         | 3006/30196 [06:22<46:54,  9.66it/s]

 10%|▉         | 3008/30196 [06:23<57:31,  7.88it/s]

 10%|▉         | 3009/30196 [06:23<1:01:16,  7.39it/s]

 10%|▉         | 3010/30196 [06:23<1:13:24,  6.17it/s]

 10%|▉         | 3011/30196 [06:23<1:11:39,  6.32it/s]

 10%|▉         | 3012/30196 [06:23<1:06:44,  6.79it/s]

 10%|▉         | 3013/30196 [06:24<1:06:32,  6.81it/s]

 10%|▉         | 3014/30196 [06:24<1:04:55,  6.98it/s]

 10%|▉         | 3016/30196 [06:24<52:10,  8.68it/s]

 10%|▉         | 3017/30196 [06:24<1:20:28,  5.63it/s]

 10%|▉         | 3018/30196 [06:24<1:15:15,  6.02it/s]

 10%|█         | 3020/30196 [06:25<1:12:35,  6.24it/s]

 10%|█         | 3021/30196 [06:25<1:09:44,  6.49it/s]

 10%|█         | 3022/30196 [06:25<1:16:05,  5.95it/s]

 10%|█         | 3024/30196 [06:25<57:31,  7.87it/s]

 10%|█         | 3025/30196 [06:25<1:02:00,  7.30it/s]

 10%|█         | 3026/30196 [06:25<59:17,  7.64it/s]

 10%|█         | 3027/30196 [06:26<1:11:57,  6.29it/s]

 10%|█         | 3028/30196 [06:26<1:12:47,  6.22it/s]

 10%|█         | 3029/30196 [06:26<1:10:23,  6.43it/s]

 10%|█         | 3031/30196 [06:26<1:06:02,  6.85it/s]

 10%|█         | 3032/30196 [06:26<1:01:31,  7.36it/s]

 10%|█         | 3034/30196 [06:26<48:58,  9.24it/s]

 10%|█         | 3036/30196 [06:27<39:37, 11.43it/s]

 10%|█         | 3038/30196 [06:27<34:07, 13.26it/s]

 10%|█         | 3040/30196 [06:27<1:07:34,  6.70it/s]

 10%|█         | 3042/30196 [06:27<55:37,  8.14it/s]

 10%|█         | 3044/30196 [06:28<1:04:24,  7.03it/s]

 10%|█         | 3047/30196 [06:28<47:22,  9.55it/s]

 10%|█         | 3049/30196 [06:28<50:25,  8.97it/s]

 10%|█         | 3051/30196 [06:28<48:04,  9.41it/s]

 10%|█         | 3053/30196 [06:29<53:15,  8.49it/s]

 10%|█         | 3055/30196 [06:29<58:46,  7.70it/s]

 10%|█         | 3056/30196 [06:29<57:52,  7.82it/s]

 10%|█         | 3058/30196 [06:29<53:28,  8.46it/s]

 10%|█         | 3059/30196 [06:29<57:50,  7.82it/s]

 10%|█         | 3061/30196 [06:30<55:08,  8.20it/s]

 10%|█         | 3062/30196 [06:30<59:32,  7.60it/s]

 10%|█         | 3063/30196 [06:30<1:09:49,  6.48it/s]

 10%|█         | 3064/30196 [06:30<1:12:03,  6.28it/s]

 10%|█         | 3065/30196 [06:30<1:12:42,  6.22it/s]

 10%|█         | 3067/30196 [06:31<1:06:30,  6.80it/s]

 10%|█         | 3068/30196 [06:31<1:08:35,  6.59it/s]

 10%|█         | 3070/30196 [06:31<1:01:29,  7.35it/s]

 10%|█         | 3071/30196 [06:31<1:05:10,  6.94it/s]

 10%|█         | 3073/30196 [06:31<51:52,  8.71it/s]

 10%|█         | 3074/30196 [06:32<1:20:17,  5.63it/s]

 10%|█         | 3075/30196 [06:32<1:15:15,  6.01it/s]

 10%|█         | 3076/30196 [06:32<1:17:41,  5.82it/s]

 10%|█         | 3078/30196 [06:32<1:08:05,  6.64it/s]

 10%|█         | 3079/30196 [06:33<1:28:09,  5.13it/s]

 10%|█         | 3081/30196 [06:33<1:04:46,  6.98it/s]

 10%|█         | 3082/30196 [06:33<1:11:15,  6.34it/s]

 10%|█         | 3083/30196 [06:33<1:06:12,  6.83it/s]

 10%|█         | 3085/30196 [06:33<56:25,  8.01it/s]

 10%|█         | 3087/30196 [06:33<51:59,  8.69it/s]

 10%|█         | 3088/30196 [06:34<51:33,  8.76it/s]

 10%|█         | 3089/30196 [06:34<53:14,  8.49it/s]

 10%|█         | 3090/30196 [06:34<51:50,  8.71it/s]

 10%|█         | 3092/30196 [06:34<54:19,  8.32it/s]

 10%|█         | 3093/30196 [06:34<55:59,  8.07it/s]

 10%|█         | 3094/30196 [06:34<55:39,  8.12it/s]

 10%|█         | 3095/30196 [06:34<57:03,  7.92it/s]

 10%|█         | 3096/30196 [06:35<59:32,  7.59it/s]

 10%|█         | 3097/30196 [06:35<59:20,  7.61it/s]

 10%|█         | 3098/30196 [06:35<55:58,  8.07it/s]

 10%|█         | 3099/30196 [06:35<1:01:31,  7.34it/s]

 10%|█         | 3100/30196 [06:35<1:05:58,  6.85it/s]

 10%|█         | 3102/30196 [06:35<50:12,  8.99it/s]

 10%|█         | 3103/30196 [06:35<49:32,  9.11it/s]

 10%|█         | 3104/30196 [06:36<52:24,  8.61it/s]

 10%|█         | 3106/30196 [06:36<39:59, 11.29it/s]

 10%|█         | 3108/30196 [06:36<1:00:47,  7.43it/s]

 10%|█         | 3110/30196 [06:36<57:00,  7.92it/s]

 10%|█         | 3111/30196 [06:36<57:29,  7.85it/s]

 10%|█         | 3113/30196 [06:37<55:44,  8.10it/s]

 10%|█         | 3114/30196 [06:37<57:18,  7.88it/s]

 10%|█         | 3115/30196 [06:37<57:41,  7.82it/s]

 10%|█         | 3116/30196 [06:37<1:02:02,  7.27it/s]

 10%|█         | 3118/30196 [06:37<55:59,  8.06it/s]

 10%|█         | 3119/30196 [06:38<1:01:46,  7.31it/s]

 10%|█         | 3121/30196 [06:38<48:23,  9.33it/s]

 10%|█         | 3123/30196 [06:38<47:20,  9.53it/s]

 10%|█         | 3124/30196 [06:38<1:03:29,  7.11it/s]

 10%|█         | 3125/30196 [06:38<1:00:28,  7.46it/s]

 10%|█         | 3126/30196 [06:38<1:00:44,  7.43it/s]

 10%|█         | 3128/30196 [06:39<58:02,  7.77it/s]

 10%|█         | 3129/30196 [06:39<55:57,  8.06it/s]

 10%|█         | 3130/30196 [06:39<54:27,  8.28it/s]

 10%|█         | 3132/30196 [06:39<48:41,  9.26it/s]

 10%|█         | 3133/30196 [06:39<59:38,  7.56it/s]

 10%|█         | 3134/30196 [06:39<57:16,  7.87it/s]

 10%|█         | 3135/30196 [06:40<1:02:20,  7.24it/s]

 10%|█         | 3136/30196 [06:40<1:02:13,  7.25it/s]

 10%|█         | 3137/30196 [06:40<1:07:18,  6.70it/s]

 10%|█         | 3138/30196 [06:40<1:19:20,  5.68it/s]

 10%|█         | 3139/30196 [06:40<1:18:03,  5.78it/s]

 10%|█         | 3142/30196 [06:40<53:59,  8.35it/s]

 10%|█         | 3143/30196 [06:41<52:44,  8.55it/s]

 10%|█         | 3144/30196 [06:41<59:19,  7.60it/s]

 10%|█         | 3146/30196 [06:41<51:21,  8.78it/s]

 10%|█         | 3148/30196 [06:41<50:11,  8.98it/s]

 10%|█         | 3150/30196 [06:41<45:58,  9.81it/s]

 10%|█         | 3151/30196 [06:41<49:25,  9.12it/s]

 10%|█         | 3153/30196 [06:42<50:05,  9.00it/s]

 10%|█         | 3154/30196 [06:42<55:24,  8.13it/s]

 10%|█         | 3155/30196 [06:42<53:52,  8.36it/s]

 10%|█         | 3157/30196 [06:42<49:29,  9.10it/s]

 10%|█         | 3158/30196 [06:42<48:54,  9.21it/s]

 10%|█         | 3159/30196 [06:43<1:25:57,  5.24it/s]

 10%|█         | 3160/30196 [06:43<1:21:05,  5.56it/s]

 10%|█         | 3161/30196 [06:43<1:19:54,  5.64it/s]

 10%|█         | 3162/30196 [06:43<1:11:37,  6.29it/s]

 10%|█         | 3163/30196 [06:43<1:14:03,  6.08it/s]

 10%|█         | 3164/30196 [06:43<1:15:44,  5.95it/s]

 10%|█         | 3166/30196 [06:44<1:04:17,  7.01it/s]

 10%|█         | 3167/30196 [06:44<1:08:07,  6.61it/s]

 10%|█         | 3169/30196 [06:44<51:39,  8.72it/s]

 10%|█         | 3170/30196 [06:44<59:00,  7.63it/s]

 11%|█         | 3171/30196 [06:44<1:03:11,  7.13it/s]

 11%|█         | 3172/30196 [06:45<1:07:33,  6.67it/s]

 11%|█         | 3173/30196 [06:45<1:07:30,  6.67it/s]

 11%|█         | 3174/30196 [06:45<1:10:47,  6.36it/s]

 11%|█         | 3175/30196 [06:45<1:08:24,  6.58it/s]

 11%|█         | 3176/30196 [06:45<1:03:00,  7.15it/s]

 11%|█         | 3178/30196 [06:45<49:52,  9.03it/s]

 11%|█         | 3179/30196 [06:45<52:11,  8.63it/s]

 11%|█         | 3180/30196 [06:46<1:09:20,  6.49it/s]

 11%|█         | 3182/30196 [06:46<54:24,  8.27it/s]

 11%|█         | 3183/30196 [06:46<1:05:43,  6.85it/s]

 11%|█         | 3184/30196 [06:46<1:06:10,  6.80it/s]

 11%|█         | 3185/30196 [06:46<1:14:27,  6.05it/s]

 11%|█         | 3186/30196 [06:47<1:11:30,  6.30it/s]

 11%|█         | 3187/30196 [06:47<1:51:03,  4.05it/s]

 11%|█         | 3188/30196 [06:47<1:37:25,  4.62it/s]

 11%|█         | 3190/30196 [06:47<1:15:05,  5.99it/s]

 11%|█         | 3192/30196 [06:47<56:19,  7.99it/s]

 11%|█         | 3193/30196 [06:48<54:51,  8.20it/s]

 11%|█         | 3194/30196 [06:48<1:26:26,  5.21it/s]

 11%|█         | 3197/30196 [06:48<1:07:23,  6.68it/s]

 11%|█         | 3198/30196 [06:49<1:07:21,  6.68it/s]

 11%|█         | 3199/30196 [06:49<1:10:10,  6.41it/s]

 11%|█         | 3201/30196 [06:49<56:51,  7.91it/s]

 11%|█         | 3202/30196 [06:49<57:53,  7.77it/s]

 11%|█         | 3204/30196 [06:49<58:05,  7.74it/s]

 11%|█         | 3205/30196 [06:49<1:06:18,  6.78it/s]

 11%|█         | 3206/30196 [06:50<1:06:26,  6.77it/s]

 11%|█         | 3207/30196 [06:50<1:10:13,  6.40it/s]

 11%|█         | 3208/30196 [06:50<1:09:04,  6.51it/s]

 11%|█         | 3210/30196 [06:50<56:38,  7.94it/s]

 11%|█         | 3212/30196 [06:50<51:00,  8.82it/s]

 11%|█         | 3214/30196 [06:51<59:23,  7.57it/s]

 11%|█         | 3215/30196 [06:51<57:11,  7.86it/s]

 11%|█         | 3216/30196 [06:51<57:59,  7.75it/s]

 11%|█         | 3218/30196 [06:51<50:21,  8.93it/s]

 11%|█         | 3220/30196 [06:51<47:07,  9.54it/s]

 11%|█         | 3222/30196 [06:51<44:34, 10.09it/s]

 11%|█         | 3224/30196 [06:52<41:20, 10.87it/s]

 11%|█         | 3226/30196 [06:52<1:11:25,  6.29it/s]

 11%|█         | 3227/30196 [06:52<1:07:22,  6.67it/s]

 11%|█         | 3228/30196 [06:52<1:10:20,  6.39it/s]

 11%|█         | 3229/30196 [06:53<1:07:40,  6.64it/s]

 11%|█         | 3230/30196 [06:53<1:05:55,  6.82it/s]

 11%|█         | 3232/30196 [06:53<59:12,  7.59it/s]

 11%|█         | 3233/30196 [06:53<1:11:41,  6.27it/s]

 11%|█         | 3234/30196 [06:53<1:06:05,  6.80it/s]

 11%|█         | 3235/30196 [06:53<1:04:15,  6.99it/s]

 11%|█         | 3237/30196 [06:54<52:44,  8.52it/s]

 11%|█         | 3238/30196 [06:54<55:47,  8.05it/s]

 11%|█         | 3239/30196 [06:54<57:02,  7.88it/s]

 11%|█         | 3240/30196 [06:54<57:31,  7.81it/s]

 11%|█         | 3241/30196 [06:54<57:49,  7.77it/s]

 11%|█         | 3242/30196 [06:54<54:47,  8.20it/s]

 11%|█         | 3244/30196 [06:54<45:55,  9.78it/s]

 11%|█         | 3246/30196 [06:55<55:35,  8.08it/s]

 11%|█         | 3248/30196 [06:55<44:15, 10.15it/s]

 11%|█         | 3250/30196 [06:55<57:34,  7.80it/s]

 11%|█         | 3252/30196 [06:55<53:49,  8.34it/s]

 11%|█         | 3254/30196 [06:56<54:37,  8.22it/s]

 11%|█         | 3256/30196 [06:56<52:16,  8.59it/s]

 11%|█         | 3257/30196 [06:56<53:50,  8.34it/s]

 11%|█         | 3259/30196 [06:56<44:50, 10.01it/s]

 11%|█         | 3261/30196 [06:56<46:03,  9.75it/s]

 11%|█         | 3263/30196 [06:56<42:55, 10.46it/s]

 11%|█         | 3265/30196 [06:57<42:41, 10.52it/s]

 11%|█         | 3267/30196 [06:57<47:24,  9.47it/s]

 11%|█         | 3268/30196 [06:57<52:14,  8.59it/s]

 11%|█         | 3270/30196 [06:57<1:00:30,  7.42it/s]

 11%|█         | 3271/30196 [06:58<57:56,  7.74it/s]

 11%|█         | 3272/30196 [06:58<59:08,  7.59it/s]

 11%|█         | 3273/30196 [06:58<1:02:42,  7.16it/s]

 11%|█         | 3274/30196 [06:58<1:02:16,  7.21it/s]

 11%|█         | 3275/30196 [06:58<1:13:28,  6.11it/s]

 11%|█         | 3276/30196 [06:58<1:09:57,  6.41it/s]

 11%|█         | 3278/30196 [06:59<59:29,  7.54it/s]

 11%|█         | 3279/30196 [06:59<1:22:01,  5.47it/s]

 11%|█         | 3280/30196 [06:59<1:16:25,  5.87it/s]

 11%|█         | 3282/30196 [06:59<1:01:05,  7.34it/s]

 11%|█         | 3284/30196 [06:59<57:27,  7.81it/s]

 11%|█         | 3286/30196 [07:00<51:56,  8.63it/s]

 11%|█         | 3287/30196 [07:00<53:14,  8.42it/s]

 11%|█         | 3288/30196 [07:00<1:29:12,  5.03it/s]

 11%|█         | 3290/30196 [07:00<1:14:45,  6.00it/s]

 11%|█         | 3291/30196 [07:01<1:14:59,  5.98it/s]

 11%|█         | 3292/30196 [07:01<1:10:58,  6.32it/s]

 11%|█         | 3294/30196 [07:01<55:57,  8.01it/s]

 11%|█         | 3296/30196 [07:01<54:28,  8.23it/s]

 11%|█         | 3298/30196 [07:01<52:56,  8.47it/s]

 11%|█         | 3300/30196 [07:02<48:17,  9.28it/s]

 11%|█         | 3301/30196 [07:02<50:38,  8.85it/s]

 11%|█         | 3303/30196 [07:02<53:02,  8.45it/s]

 11%|█         | 3305/30196 [07:02<51:07,  8.77it/s]

 11%|█         | 3307/30196 [07:02<50:37,  8.85it/s]

 11%|█         | 3309/30196 [07:03<48:14,  9.29it/s]

 11%|█         | 3311/30196 [07:03<1:04:08,  6.99it/s]

 11%|█         | 3313/30196 [07:03<54:42,  8.19it/s]

 11%|█         | 3315/30196 [07:03<47:11,  9.49it/s]

 11%|█         | 3317/30196 [07:03<45:48,  9.78it/s]

 11%|█         | 3319/30196 [07:04<47:25,  9.44it/s]

 11%|█         | 3321/30196 [07:04<42:00, 10.66it/s]

 11%|█         | 3323/30196 [07:04<56:04,  7.99it/s]

 11%|█         | 3325/30196 [07:04<53:34,  8.36it/s]

 11%|█         | 3326/30196 [07:05<52:24,  8.55it/s]

 11%|█         | 3327/30196 [07:05<53:36,  8.35it/s]

 11%|█         | 3328/30196 [07:05<58:15,  7.69it/s]

 11%|█         | 3330/30196 [07:05<55:23,  8.08it/s]

 11%|█         | 3331/30196 [07:05<56:07,  7.98it/s]

 11%|█         | 3333/30196 [07:05<46:08,  9.70it/s]

 11%|█         | 3335/30196 [07:06<44:42, 10.01it/s]

 11%|█         | 3337/30196 [07:06<53:17,  8.40it/s]

 11%|█         | 3338/30196 [07:06<55:08,  8.12it/s]

 11%|█         | 3340/30196 [07:06<47:39,  9.39it/s]

 11%|█         | 3342/30196 [07:06<46:44,  9.58it/s]

 11%|█         | 3344/30196 [07:06<40:18, 11.10it/s]

 11%|█         | 3346/30196 [07:07<45:59,  9.73it/s]

 11%|█         | 3348/30196 [07:07<44:18, 10.10it/s]

 11%|█         | 3350/30196 [07:07<47:14,  9.47it/s]

 11%|█         | 3352/30196 [07:08<1:16:45,  5.83it/s]

 11%|█         | 3353/30196 [07:08<1:11:52,  6.22it/s]

 11%|█         | 3354/30196 [07:08<1:17:20,  5.78it/s]

 11%|█         | 3356/30196 [07:08<1:04:08,  6.97it/s]

 11%|█         | 3358/30196 [07:08<52:19,  8.55it/s]

 11%|█         | 3360/30196 [07:09<57:41,  7.75it/s]

 11%|█         | 3361/30196 [07:09<58:40,  7.62it/s]

 11%|█         | 3362/30196 [07:09<1:01:04,  7.32it/s]

 11%|█         | 3364/30196 [07:09<52:35,  8.50it/s]

 11%|█         | 3365/30196 [07:09<54:15,  8.24it/s]

 11%|█         | 3367/30196 [07:10<47:44,  9.37it/s]

 11%|█         | 3369/30196 [07:10<47:32,  9.41it/s]

 11%|█         | 3370/30196 [07:10<47:54,  9.33it/s]

 11%|█         | 3371/30196 [07:10<51:20,  8.71it/s]

 11%|█         | 3373/30196 [07:10<44:20, 10.08it/s]

 11%|█         | 3375/30196 [07:11<1:30:09,  4.96it/s]

 11%|█         | 3376/30196 [07:11<1:25:10,  5.25it/s]

 11%|█         | 3378/30196 [07:11<1:12:01,  6.21it/s]

 11%|█         | 3380/30196 [07:11<1:00:57,  7.33it/s]

 11%|█         | 3381/30196 [07:12<58:07,  7.69it/s]

 11%|█         | 3383/30196 [07:12<53:50,  8.30it/s]

 11%|█         | 3384/30196 [07:12<52:23,  8.53it/s]

 11%|█         | 3385/30196 [07:12<57:36,  7.76it/s]

 11%|█         | 3387/30196 [07:12<52:00,  8.59it/s]

 11%|█         | 3388/30196 [07:12<53:46,  8.31it/s]

 11%|█         | 3390/30196 [07:13<55:59,  7.98it/s]

 11%|█         | 3392/30196 [07:13<45:35,  9.80it/s]

 11%|█         | 3394/30196 [07:13<46:31,  9.60it/s]

 11%|█         | 3396/30196 [07:13<48:04,  9.29it/s]

 11%|█         | 3397/30196 [07:13<50:22,  8.87it/s]

 11%|█▏        | 3398/30196 [07:14<59:13,  7.54it/s]

 11%|█▏        | 3399/30196 [07:14<1:34:32,  4.72it/s]

 11%|█▏        | 3400/30196 [07:14<1:25:36,  5.22it/s]

 11%|█▏        | 3401/30196 [07:14<1:18:27,  5.69it/s]

 11%|█▏        | 3402/30196 [07:14<1:17:10,  5.79it/s]

 11%|█▏        | 3403/30196 [07:15<1:16:14,  5.86it/s]

 11%|█▏        | 3404/30196 [07:15<1:15:34,  5.91it/s]

 11%|█▏        | 3406/30196 [07:15<1:00:16,  7.41it/s]

 11%|█▏        | 3407/30196 [07:15<1:05:11,  6.85it/s]

 11%|█▏        | 3408/30196 [07:15<1:07:48,  6.58it/s]

 11%|█▏        | 3409/30196 [07:15<1:09:38,  6.41it/s]

 11%|█▏        | 3410/30196 [07:16<1:07:47,  6.59it/s]

 11%|█▏        | 3411/30196 [07:16<1:05:35,  6.81it/s]

 11%|█▏        | 3413/30196 [07:16<51:31,  8.66it/s]

 11%|█▏        | 3414/30196 [07:16<57:02,  7.82it/s]

 11%|█▏        | 3416/30196 [07:16<49:43,  8.97it/s]

 11%|█▏        | 3417/30196 [07:16<49:37,  8.99it/s]

 11%|█▏        | 3418/30196 [07:16<52:10,  8.55it/s]

 11%|█▏        | 3419/30196 [07:17<55:35,  8.03it/s]

 11%|█▏        | 3420/30196 [07:17<1:06:24,  6.72it/s]

 11%|█▏        | 3421/30196 [07:17<1:04:30,  6.92it/s]

 11%|█▏        | 3422/30196 [07:17<1:08:53,  6.48it/s]

 11%|█▏        | 3424/30196 [07:17<1:03:12,  7.06it/s]

 11%|█▏        | 3425/30196 [07:18<1:03:11,  7.06it/s]

 11%|█▏        | 3427/30196 [07:18<55:27,  8.05it/s]

 11%|█▏        | 3428/30196 [07:18<1:00:22,  7.39it/s]

 11%|█▏        | 3429/30196 [07:18<59:48,  7.46it/s]

 11%|█▏        | 3431/30196 [07:18<54:11,  8.23it/s]

 11%|█▏        | 3433/30196 [07:18<48:06,  9.27it/s]

 11%|█▏        | 3434/30196 [07:19<50:10,  8.89it/s]

 11%|█▏        | 3435/30196 [07:19<55:37,  8.02it/s]

 11%|█▏        | 3437/30196 [07:19<49:25,  9.02it/s]

 11%|█▏        | 3438/30196 [07:19<52:19,  8.52it/s]

 11%|█▏        | 3440/30196 [07:19<48:05,  9.27it/s]

 11%|█▏        | 3441/30196 [07:19<54:19,  8.21it/s]

 11%|█▏        | 3442/30196 [07:20<53:06,  8.40it/s]

 11%|█▏        | 3443/30196 [07:20<51:32,  8.65it/s]

 11%|█▏        | 3444/30196 [07:20<57:49,  7.71it/s]

 11%|█▏        | 3446/30196 [07:20<44:04, 10.11it/s]

 11%|█▏        | 3448/30196 [07:20<53:23,  8.35it/s]

 11%|█▏        | 3449/30196 [07:20<55:55,  7.97it/s]

 11%|█▏        | 3451/30196 [07:21<50:52,  8.76it/s]

 11%|█▏        | 3452/30196 [07:21<56:37,  7.87it/s]

 11%|█▏        | 3453/30196 [07:21<54:32,  8.17it/s]

 11%|█▏        | 3454/30196 [07:21<52:39,  8.46it/s]

 11%|█▏        | 3455/30196 [07:21<54:03,  8.24it/s]

 11%|█▏        | 3456/30196 [07:21<55:30,  8.03it/s]

 11%|█▏        | 3457/30196 [07:21<53:44,  8.29it/s]

 11%|█▏        | 3458/30196 [07:21<55:29,  8.03it/s]

 11%|█▏        | 3459/30196 [07:22<52:51,  8.43it/s]

 11%|█▏        | 3460/30196 [07:22<51:28,  8.66it/s]

 11%|█▏        | 3461/30196 [07:22<53:28,  8.33it/s]

 11%|█▏        | 3463/30196 [07:22<47:52,  9.31it/s]

 11%|█▏        | 3465/30196 [07:22<44:37,  9.98it/s]

 11%|█▏        | 3466/30196 [07:22<45:06,  9.88it/s]

 11%|█▏        | 3467/30196 [07:22<48:09,  9.25it/s]

 11%|█▏        | 3469/30196 [07:23<40:34, 10.98it/s]

 11%|█▏        | 3471/30196 [07:23<47:34,  9.36it/s]

 12%|█▏        | 3473/30196 [07:23<44:51,  9.93it/s]

 12%|█▏        | 3475/30196 [07:23<44:12, 10.07it/s]

 12%|█▏        | 3477/30196 [07:23<39:06, 11.39it/s]

 12%|█▏        | 3479/30196 [07:24<1:05:26,  6.80it/s]

 12%|█▏        | 3480/30196 [07:24<1:07:45,  6.57it/s]

 12%|█▏        | 3481/30196 [07:24<1:06:13,  6.72it/s]

 12%|█▏        | 3482/30196 [07:24<1:05:21,  6.81it/s]

 12%|█▏        | 3484/30196 [07:24<53:22,  8.34it/s]

 12%|█▏        | 3486/30196 [07:25<1:01:10,  7.28it/s]

 12%|█▏        | 3487/30196 [07:25<1:03:52,  6.97it/s]

 12%|█▏        | 3488/30196 [07:25<1:10:46,  6.29it/s]

 12%|█▏        | 3489/30196 [07:25<1:08:36,  6.49it/s]

 12%|█▏        | 3490/30196 [07:25<1:07:53,  6.56it/s]

 12%|█▏        | 3492/30196 [07:26<52:44,  8.44it/s]

 12%|█▏        | 3494/30196 [07:26<43:04, 10.33it/s]

 12%|█▏        | 3496/30196 [07:26<49:20,  9.02it/s]

 12%|█▏        | 3497/30196 [07:26<51:03,  8.72it/s]

 12%|█▏        | 3499/30196 [07:26<57:23,  7.75it/s]

 12%|█▏        | 3500/30196 [07:27<57:58,  7.67it/s]

 12%|█▏        | 3502/30196 [07:27<1:16:47,  5.79it/s]

 12%|█▏        | 3503/30196 [07:27<1:16:18,  5.83it/s]

 12%|█▏        | 3504/30196 [07:27<1:10:00,  6.35it/s]

 12%|█▏        | 3505/30196 [07:27<1:07:22,  6.60it/s]

 12%|█▏        | 3506/30196 [07:28<1:06:43,  6.67it/s]

 12%|█▏        | 3507/30196 [07:28<1:05:14,  6.82it/s]

 12%|█▏        | 3508/30196 [07:28<1:04:32,  6.89it/s]

 12%|█▏        | 3509/30196 [07:28<1:02:44,  7.09it/s]

 12%|█▏        | 3511/30196 [07:28<48:00,  9.26it/s]

 12%|█▏        | 3513/30196 [07:28<39:13, 11.34it/s]

 12%|█▏        | 3515/30196 [07:29<1:04:40,  6.88it/s]

 12%|█▏        | 3517/30196 [07:29<52:53,  8.41it/s]

 12%|█▏        | 3519/30196 [07:29<1:09:07,  6.43it/s]

 12%|█▏        | 3520/30196 [07:30<1:11:03,  6.26it/s]

 12%|█▏        | 3521/30196 [07:30<1:08:46,  6.46it/s]

 12%|█▏        | 3522/30196 [07:30<1:09:51,  6.36it/s]

 12%|█▏        | 3523/30196 [07:30<1:04:06,  6.93it/s]

 12%|█▏        | 3525/30196 [07:30<55:53,  7.95it/s]

 12%|█▏        | 3526/30196 [07:30<56:49,  7.82it/s]

 12%|█▏        | 3527/30196 [07:30<59:04,  7.52it/s]

 12%|█▏        | 3528/30196 [07:31<1:03:42,  6.98it/s]

 12%|█▏        | 3529/30196 [07:31<1:02:08,  7.15it/s]

 12%|█▏        | 3531/30196 [07:31<55:38,  7.99it/s]

 12%|█▏        | 3532/30196 [07:31<56:16,  7.90it/s]

 12%|█▏        | 3533/30196 [07:31<56:42,  7.84it/s]

 12%|█▏        | 3534/30196 [07:31<54:17,  8.19it/s]

 12%|█▏        | 3535/30196 [07:31<56:28,  7.87it/s]

 12%|█▏        | 3537/30196 [07:32<43:11, 10.29it/s]

 12%|█▏        | 3539/30196 [07:32<57:06,  7.78it/s]

 12%|█▏        | 3540/30196 [07:32<58:21,  7.61it/s]

 12%|█▏        | 3541/30196 [07:32<58:22,  7.61it/s]

 12%|█▏        | 3543/30196 [07:32<47:35,  9.33it/s]

 12%|█▏        | 3544/30196 [07:33<58:02,  7.65it/s]

 12%|█▏        | 3546/30196 [07:33<46:43,  9.51it/s]

 12%|█▏        | 3548/30196 [07:33<53:56,  8.23it/s]

 12%|█▏        | 3549/30196 [07:33<59:02,  7.52it/s]

 12%|█▏        | 3550/30196 [07:33<58:48,  7.55it/s]

 12%|█▏        | 3552/30196 [07:33<51:01,  8.70it/s]

 12%|█▏        | 3554/30196 [07:34<45:43,  9.71it/s]

 12%|█▏        | 3556/30196 [07:34<1:16:52,  5.78it/s]

 12%|█▏        | 3557/30196 [07:34<1:16:59,  5.77it/s]

 12%|█▏        | 3558/30196 [07:35<1:13:50,  6.01it/s]

 12%|█▏        | 3559/30196 [07:35<1:10:08,  6.33it/s]

 12%|█▏        | 3560/30196 [07:35<1:11:26,  6.21it/s]

 12%|█▏        | 3561/30196 [07:35<1:09:09,  6.42it/s]

 12%|█▏        | 3563/30196 [07:35<51:50,  8.56it/s]

 12%|█▏        | 3565/30196 [07:35<48:55,  9.07it/s]

 12%|█▏        | 3566/30196 [07:36<55:02,  8.06it/s]

 12%|█▏        | 3568/30196 [07:36<47:45,  9.29it/s]

 12%|█▏        | 3570/30196 [07:36<47:33,  9.33it/s]

 12%|█▏        | 3571/30196 [07:36<47:23,  9.36it/s]

 12%|█▏        | 3572/30196 [07:36<1:09:57,  6.34it/s]

 12%|█▏        | 3573/30196 [07:36<1:08:08,  6.51it/s]

 12%|█▏        | 3574/30196 [07:37<1:02:50,  7.06it/s]

 12%|█▏        | 3575/30196 [07:37<58:26,  7.59it/s]

 12%|█▏        | 3577/30196 [07:37<53:08,  8.35it/s]

 12%|█▏        | 3578/30196 [07:37<55:25,  8.00it/s]

 12%|█▏        | 3579/30196 [07:37<56:06,  7.91it/s]

 12%|█▏        | 3581/30196 [07:37<53:45,  8.25it/s]

 12%|█▏        | 3583/30196 [07:38<50:20,  8.81it/s]

 12%|█▏        | 3585/30196 [07:38<46:39,  9.51it/s]

 12%|█▏        | 3586/30196 [07:38<55:32,  7.98it/s]

 12%|█▏        | 3587/30196 [07:38<57:41,  7.69it/s]

 12%|█▏        | 3589/30196 [07:38<51:57,  8.53it/s]

 12%|█▏        | 3590/30196 [07:38<53:35,  8.27it/s]

 12%|█▏        | 3591/30196 [07:39<54:42,  8.11it/s]

 12%|█▏        | 3592/30196 [07:39<57:13,  7.75it/s]

 12%|█▏        | 3593/30196 [07:39<54:52,  8.08it/s]

 12%|█▏        | 3594/30196 [07:39<1:00:52,  7.28it/s]

 12%|█▏        | 3595/30196 [07:39<56:50,  7.80it/s]

 12%|█▏        | 3596/30196 [07:39<1:16:30,  5.79it/s]

 12%|█▏        | 3597/30196 [07:40<1:16:39,  5.78it/s]

 12%|█▏        | 3598/30196 [07:40<1:15:51,  5.84it/s]

 12%|█▏        | 3600/30196 [07:40<58:00,  7.64it/s]

 12%|█▏        | 3602/30196 [07:40<56:56,  7.78it/s]

 12%|█▏        | 3603/30196 [07:40<57:10,  7.75it/s]

 12%|█▏        | 3604/30196 [07:40<55:10,  8.03it/s]

 12%|█▏        | 3606/30196 [07:41<52:50,  8.39it/s]

 12%|█▏        | 3607/30196 [07:41<58:10,  7.62it/s]

 12%|█▏        | 3609/30196 [07:41<49:21,  8.98it/s]

 12%|█▏        | 3611/30196 [07:41<44:28,  9.96it/s]

 12%|█▏        | 3613/30196 [07:41<39:32, 11.21it/s]

 12%|█▏        | 3615/30196 [07:41<36:56, 11.99it/s]

 12%|█▏        | 3617/30196 [07:42<44:29,  9.96it/s]

 12%|█▏        | 3619/30196 [07:42<47:36,  9.31it/s]

 12%|█▏        | 3620/30196 [07:42<47:27,  9.33it/s]

 12%|█▏        | 3622/30196 [07:42<43:34, 10.16it/s]

 12%|█▏        | 3624/30196 [07:42<47:56,  9.24it/s]

 12%|█▏        | 3625/30196 [07:43<51:18,  8.63it/s]

 12%|█▏        | 3627/30196 [07:43<43:25, 10.20it/s]

 12%|█▏        | 3629/30196 [07:43<48:29,  9.13it/s]

 12%|█▏        | 3631/30196 [07:43<44:43,  9.90it/s]

 12%|█▏        | 3633/30196 [07:43<46:18,  9.56it/s]

 12%|█▏        | 3635/30196 [07:44<48:10,  9.19it/s]

 12%|█▏        | 3637/30196 [07:44<42:27, 10.42it/s]

 12%|█▏        | 3639/30196 [07:44<55:59,  7.91it/s]

 12%|█▏        | 3641/30196 [07:44<51:32,  8.59it/s]

 12%|█▏        | 3642/30196 [07:44<50:40,  8.73it/s]

 12%|█▏        | 3643/30196 [07:45<49:39,  8.91it/s]

 12%|█▏        | 3644/30196 [07:45<48:55,  9.05it/s]

 12%|█▏        | 3645/30196 [07:45<48:54,  9.05it/s]

 12%|█▏        | 3647/30196 [07:45<1:15:58,  5.82it/s]

 12%|█▏        | 3649/30196 [07:45<1:05:52,  6.72it/s]

 12%|█▏        | 3650/30196 [07:46<1:05:05,  6.80it/s]

 12%|█▏        | 3651/30196 [07:46<1:01:22,  7.21it/s]

 12%|█▏        | 3652/30196 [07:46<57:35,  7.68it/s]

 12%|█▏        | 3654/30196 [07:46<44:53,  9.85it/s]

 12%|█▏        | 3656/30196 [07:46<51:02,  8.66it/s]

 12%|█▏        | 3657/30196 [07:46<55:39,  7.95it/s]

 12%|█▏        | 3658/30196 [07:47<1:05:39,  6.74it/s]

 12%|█▏        | 3659/30196 [07:47<1:03:40,  6.95it/s]

 12%|█▏        | 3660/30196 [07:47<1:07:52,  6.52it/s]

 12%|█▏        | 3662/30196 [07:47<49:20,  8.96it/s]

 12%|█▏        | 3664/30196 [07:47<44:58,  9.83it/s]

 12%|█▏        | 3666/30196 [07:48<52:06,  8.49it/s]

 12%|█▏        | 3667/30196 [07:48<1:01:51,  7.15it/s]

 12%|█▏        | 3668/30196 [07:48<58:28,  7.56it/s]

 12%|█▏        | 3669/30196 [07:48<1:02:19,  7.09it/s]

 12%|█▏        | 3670/30196 [07:48<1:15:09,  5.88it/s]

 12%|█▏        | 3671/30196 [07:48<1:08:07,  6.49it/s]

 12%|█▏        | 3673/30196 [07:49<56:27,  7.83it/s]

 12%|█▏        | 3674/30196 [07:49<57:12,  7.73it/s]

 12%|█▏        | 3675/30196 [07:49<55:01,  8.03it/s]

 12%|█▏        | 3676/30196 [07:49<52:44,  8.38it/s]

 12%|█▏        | 3677/30196 [07:49<58:15,  7.59it/s]

 12%|█▏        | 3679/30196 [07:49<53:56,  8.19it/s]

 12%|█▏        | 3680/30196 [07:49<52:41,  8.39it/s]

 12%|█▏        | 3681/30196 [07:50<54:20,  8.13it/s]

 12%|█▏        | 3682/30196 [07:50<55:13,  8.00it/s]

 12%|█▏        | 3684/30196 [07:50<45:54,  9.63it/s]

 12%|█▏        | 3686/30196 [07:50<38:22, 11.52it/s]

 12%|█▏        | 3688/30196 [07:50<45:04,  9.80it/s]

 12%|█▏        | 3690/30196 [07:51<53:23,  8.27it/s]

 12%|█▏        | 3692/30196 [07:51<48:51,  9.04it/s]

 12%|█▏        | 3694/30196 [07:51<47:36,  9.28it/s]

 12%|█▏        | 3696/30196 [07:51<44:03, 10.02it/s]

 12%|█▏        | 3698/30196 [07:51<55:36,  7.94it/s]

 12%|█▏        | 3699/30196 [07:52<1:01:59,  7.12it/s]

 12%|█▏        | 3700/30196 [07:52<59:16,  7.45it/s]

 12%|█▏        | 3701/30196 [07:52<56:48,  7.77it/s]

 12%|█▏        | 3702/30196 [07:52<54:42,  8.07it/s]

 12%|█▏        | 3704/30196 [07:52<50:56,  8.67it/s]

 12%|█▏        | 3705/30196 [07:52<55:53,  7.90it/s]

 12%|█▏        | 3707/30196 [07:53<48:38,  9.08it/s]

 12%|█▏        | 3709/30196 [07:53<49:39,  8.89it/s]

 12%|█▏        | 3710/30196 [07:53<1:00:04,  7.35it/s]

 12%|█▏        | 3711/30196 [07:53<1:00:33,  7.29it/s]

 12%|█▏        | 3712/30196 [07:53<59:50,  7.38it/s]

 12%|█▏        | 3713/30196 [07:53<56:19,  7.84it/s]

 12%|█▏        | 3715/30196 [07:54<46:35,  9.47it/s]

 12%|█▏        | 3716/30196 [07:54<46:29,  9.49it/s]

 12%|█▏        | 3718/30196 [07:54<47:34,  9.27it/s]

 12%|█▏        | 3720/30196 [07:54<40:29, 10.90it/s]

 12%|█▏        | 3722/30196 [07:54<47:50,  9.22it/s]

 12%|█▏        | 3724/30196 [07:55<54:16,  8.13it/s]

 12%|█▏        | 3725/30196 [07:55<55:43,  7.92it/s]

 12%|█▏        | 3726/30196 [07:55<59:23,  7.43it/s]

 12%|█▏        | 3727/30196 [07:55<59:56,  7.36it/s]

 12%|█▏        | 3729/30196 [07:55<50:03,  8.81it/s]

 12%|█▏        | 3731/30196 [07:55<48:26,  9.11it/s]

 12%|█▏        | 3732/30196 [07:55<48:24,  9.11it/s]

 12%|█▏        | 3734/30196 [07:56<48:12,  9.15it/s]

 12%|█▏        | 3736/30196 [07:56<40:16, 10.95it/s]

 12%|█▏        | 3738/30196 [07:56<42:49, 10.30it/s]

 12%|█▏        | 3740/30196 [07:56<1:00:17,  7.31it/s]

 12%|█▏        | 3742/30196 [07:57<58:13,  7.57it/s]

 12%|█▏        | 3743/30196 [07:57<56:01,  7.87it/s]

 12%|█▏        | 3744/30196 [07:57<57:54,  7.61it/s]

 12%|█▏        | 3745/30196 [07:57<58:54,  7.48it/s]

 12%|█▏        | 3747/30196 [07:57<53:54,  8.18it/s]

 12%|█▏        | 3748/30196 [07:58<1:03:39,  6.92it/s]

 12%|█▏        | 3749/30196 [07:58<1:00:05,  7.33it/s]

 12%|█▏        | 3751/30196 [07:58<46:20,  9.51it/s]

 12%|█▏        | 3753/30196 [07:58<38:16, 11.51it/s]

 12%|█▏        | 3755/30196 [07:58<49:14,  8.95it/s]

 12%|█▏        | 3757/30196 [07:58<47:58,  9.18it/s]

 12%|█▏        | 3759/30196 [07:59<51:09,  8.61it/s]

 12%|█▏        | 3761/30196 [07:59<46:56,  9.38it/s]

 12%|█▏        | 3763/30196 [07:59<43:38, 10.10it/s]

 12%|█▏        | 3765/30196 [07:59<49:17,  8.94it/s]

 12%|█▏        | 3766/30196 [07:59<51:03,  8.63it/s]

 12%|█▏        | 3767/30196 [08:00<52:45,  8.35it/s]

 12%|█▏        | 3769/30196 [08:00<47:30,  9.27it/s]

 12%|█▏        | 3771/30196 [08:00<45:31,  9.67it/s]

 12%|█▏        | 3772/30196 [08:00<1:24:23,  5.22it/s]

 12%|█▏        | 3773/30196 [08:01<1:18:28,  5.61it/s]

 12%|█▏        | 3774/30196 [08:01<1:20:00,  5.50it/s]

 13%|█▎        | 3776/30196 [08:01<1:06:11,  6.65it/s]

 13%|█▎        | 3778/30196 [08:01<59:31,  7.40it/s]

 13%|█▎        | 3779/30196 [08:01<58:53,  7.48it/s]

 13%|█▎        | 3780/30196 [08:02<1:02:33,  7.04it/s]

 13%|█▎        | 3782/30196 [08:02<53:15,  8.27it/s]

 13%|█▎        | 3783/30196 [08:02<54:40,  8.05it/s]

 13%|█▎        | 3784/30196 [08:02<59:04,  7.45it/s]

 13%|█▎        | 3785/30196 [08:02<1:00:30,  7.27it/s]

 13%|█▎        | 3786/30196 [08:02<1:01:30,  7.16it/s]

 13%|█▎        | 3788/30196 [08:03<55:03,  7.99it/s]

 13%|█▎        | 3790/30196 [08:03<55:29,  7.93it/s]

 13%|█▎        | 3792/30196 [08:03<53:35,  8.21it/s]

 13%|█▎        | 3794/30196 [08:03<49:29,  8.89it/s]

 13%|█▎        | 3796/30196 [08:03<44:06,  9.98it/s]

 13%|█▎        | 3798/30196 [08:04<43:44, 10.06it/s]

 13%|█▎        | 3800/30196 [08:04<39:55, 11.02it/s]

 13%|█▎        | 3802/30196 [08:04<43:01, 10.22it/s]

 13%|█▎        | 3804/30196 [08:04<42:13, 10.42it/s]

 13%|█▎        | 3806/30196 [08:04<43:57, 10.00it/s]

 13%|█▎        | 3808/30196 [08:04<43:18, 10.16it/s]

 13%|█▎        | 3810/30196 [08:05<44:05,  9.97it/s]

 13%|█▎        | 3812/30196 [08:05<38:39, 11.38it/s]

 13%|█▎        | 3814/30196 [08:05<41:31, 10.59it/s]

 13%|█▎        | 3816/30196 [08:05<38:53, 11.30it/s]

 13%|█▎        | 3818/30196 [08:05<40:00, 10.99it/s]

 13%|█▎        | 3820/30196 [08:06<1:12:43,  6.04it/s]

 13%|█▎        | 3822/30196 [08:06<1:04:08,  6.85it/s]

 13%|█▎        | 3823/30196 [08:06<1:06:15,  6.63it/s]

 13%|█▎        | 3824/30196 [08:07<1:02:13,  7.06it/s]

 13%|█▎        | 3825/30196 [08:07<1:01:33,  7.14it/s]

 13%|█▎        | 3827/30196 [08:07<1:07:30,  6.51it/s]

 13%|█▎        | 3829/30196 [08:07<57:09,  7.69it/s]

 13%|█▎        | 3830/30196 [08:07<58:10,  7.55it/s]

 13%|█▎        | 3831/30196 [08:08<1:07:55,  6.47it/s]

 13%|█▎        | 3832/30196 [08:08<1:05:20,  6.73it/s]

 13%|█▎        | 3833/30196 [08:08<1:04:35,  6.80it/s]

 13%|█▎        | 3834/30196 [08:08<1:02:21,  7.05it/s]

 13%|█▎        | 3835/30196 [08:08<1:01:02,  7.20it/s]

 13%|█▎        | 3837/30196 [08:08<51:06,  8.60it/s]

 13%|█▎        | 3839/30196 [08:09<56:16,  7.81it/s]

 13%|█▎        | 3841/30196 [08:09<46:53,  9.37it/s]

 13%|█▎        | 3843/30196 [08:09<48:59,  8.96it/s]

 13%|█▎        | 3844/30196 [08:09<53:55,  8.14it/s]

 13%|█▎        | 3845/30196 [08:09<55:04,  7.98it/s]

 13%|█▎        | 3846/30196 [08:09<1:08:40,  6.39it/s]

 13%|█▎        | 3847/30196 [08:10<1:04:39,  6.79it/s]

 13%|█▎        | 3848/30196 [08:10<1:04:43,  6.79it/s]

 13%|█▎        | 3849/30196 [08:10<1:02:46,  6.99it/s]

 13%|█▎        | 3851/30196 [08:10<50:56,  8.62it/s]

 13%|█▎        | 3852/30196 [08:10<52:26,  8.37it/s]

 13%|█▎        | 3853/30196 [08:10<54:47,  8.01it/s]

 13%|█▎        | 3854/30196 [08:11<1:31:16,  4.81it/s]

 13%|█▎        | 3855/30196 [08:11<1:23:10,  5.28it/s]

 13%|█▎        | 3856/30196 [08:11<1:18:00,  5.63it/s]

 13%|█▎        | 3858/30196 [08:11<1:00:52,  7.21it/s]

 13%|█▎        | 3859/30196 [08:11<1:00:06,  7.30it/s]

 13%|█▎        | 3861/30196 [08:12<47:47,  9.18it/s]

 13%|█▎        | 3863/30196 [08:12<48:33,  9.04it/s]

 13%|█▎        | 3865/30196 [08:12<48:19,  9.08it/s]

 13%|█▎        | 3867/30196 [08:12<59:47,  7.34it/s]

 13%|█▎        | 3869/30196 [08:13<56:06,  7.82it/s]

 13%|█▎        | 3871/30196 [08:13<53:37,  8.18it/s]

 13%|█▎        | 3872/30196 [08:13<1:01:01,  7.19it/s]

 13%|█▎        | 3873/30196 [08:13<1:00:11,  7.29it/s]

 13%|█▎        | 3874/30196 [08:13<57:31,  7.63it/s]

 13%|█▎        | 3875/30196 [08:13<54:39,  8.03it/s]

 13%|█▎        | 3876/30196 [08:14<1:16:31,  5.73it/s]

 13%|█▎        | 3877/30196 [08:14<1:21:11,  5.40it/s]

 13%|█▎        | 3879/30196 [08:14<59:35,  7.36it/s]

 13%|█▎        | 3881/30196 [08:14<45:47,  9.58it/s]

 13%|█▎        | 3883/30196 [08:14<55:53,  7.85it/s]

 13%|█▎        | 3885/30196 [08:15<46:18,  9.47it/s]

 13%|█▎        | 3887/30196 [08:15<44:22,  9.88it/s]

 13%|█▎        | 3889/30196 [08:15<48:48,  8.98it/s]

 13%|█▎        | 3891/30196 [08:15<48:14,  9.09it/s]

 13%|█▎        | 3892/30196 [08:15<50:15,  8.72it/s]

 13%|█▎        | 3893/30196 [08:16<52:38,  8.33it/s]

 13%|█▎        | 3894/30196 [08:16<51:42,  8.48it/s]

 13%|█▎        | 3895/30196 [08:16<50:50,  8.62it/s]

 13%|█▎        | 3896/30196 [08:16<50:08,  8.74it/s]

 13%|█▎        | 3897/30196 [08:16<56:08,  7.81it/s]

 13%|█▎        | 3898/30196 [08:16<58:25,  7.50it/s]

 13%|█▎        | 3899/30196 [08:16<58:39,  7.47it/s]

 13%|█▎        | 3900/30196 [08:16<1:04:16,  6.82it/s]

 13%|█▎        | 3901/30196 [08:17<1:07:38,  6.48it/s]

 13%|█▎        | 3903/30196 [08:17<56:11,  7.80it/s]

 13%|█▎        | 3904/30196 [08:17<1:15:23,  5.81it/s]

 13%|█▎        | 3905/30196 [08:17<1:10:40,  6.20it/s]

 13%|█▎        | 3907/30196 [08:17<59:48,  7.33it/s]

 13%|█▎        | 3909/30196 [08:18<52:34,  8.33it/s]

 13%|█▎        | 3910/30196 [08:18<54:59,  7.97it/s]

 13%|█▎        | 3911/30196 [08:18<57:09,  7.67it/s]

 13%|█▎        | 3913/30196 [08:18<47:38,  9.19it/s]

 13%|█▎        | 3914/30196 [08:18<51:28,  8.51it/s]

 13%|█▎        | 3916/30196 [08:18<48:41,  8.99it/s]

 13%|█▎        | 3917/30196 [08:19<55:19,  7.92it/s]

 13%|█▎        | 3919/30196 [08:19<50:40,  8.64it/s]

 13%|█▎        | 3920/30196 [08:19<1:34:08,  4.65it/s]

 13%|█▎        | 3922/30196 [08:20<1:16:50,  5.70it/s]

 13%|█▎        | 3923/30196 [08:20<1:19:37,  5.50it/s]

 13%|█▎        | 3925/30196 [08:20<1:05:40,  6.67it/s]

 13%|█▎        | 3926/30196 [08:20<1:12:41,  6.02it/s]

 13%|█▎        | 3927/30196 [08:20<1:12:38,  6.03it/s]

 13%|█▎        | 3928/30196 [08:21<1:34:22,  4.64it/s]

 13%|█▎        | 3930/30196 [08:21<1:48:36,  4.03it/s]

 13%|█▎        | 3931/30196 [08:22<1:44:36,  4.18it/s]

 13%|█▎        | 3934/30196 [08:22<1:12:50,  6.01it/s]

 13%|█▎        | 3936/30196 [08:22<1:00:26,  7.24it/s]

 13%|█▎        | 3938/30196 [08:22<52:49,  8.28it/s]

 13%|█▎        | 3939/30196 [08:22<52:00,  8.41it/s]

 13%|█▎        | 3940/30196 [08:23<1:00:40,  7.21it/s]

 13%|█▎        | 3941/30196 [08:23<1:00:50,  7.19it/s]

 13%|█▎        | 3942/30196 [08:23<1:01:44,  7.09it/s]

 13%|█▎        | 3943/30196 [08:23<1:00:38,  7.21it/s]

 13%|█▎        | 3944/30196 [08:23<59:45,  7.32it/s]

 13%|█▎        | 3945/30196 [08:23<56:30,  7.74it/s]

 13%|█▎        | 3947/30196 [08:23<42:55, 10.19it/s]

 13%|█▎        | 3949/30196 [08:23<42:17, 10.34it/s]

 13%|█▎        | 3951/30196 [08:24<42:00, 10.41it/s]

 13%|█▎        | 3953/30196 [08:24<37:49, 11.56it/s]

 13%|█▎        | 3955/30196 [08:24<52:40,  8.30it/s]

 13%|█▎        | 3957/30196 [08:24<49:11,  8.89it/s]

 13%|█▎        | 3959/30196 [08:25<47:56,  9.12it/s]

 13%|█▎        | 3960/30196 [08:25<52:51,  8.27it/s]

 13%|█▎        | 3961/30196 [08:25<1:01:51,  7.07it/s]

 13%|█▎        | 3963/30196 [08:25<49:41,  8.80it/s]

 13%|█▎        | 3964/30196 [08:25<53:34,  8.16it/s]

 13%|█▎        | 3965/30196 [08:26<1:10:45,  6.18it/s]

 13%|█▎        | 3966/30196 [08:26<1:04:38,  6.76it/s]

 13%|█▎        | 3968/30196 [08:26<1:00:49,  7.19it/s]

 13%|█▎        | 3970/30196 [08:26<56:50,  7.69it/s]

 13%|█▎        | 3972/30196 [08:26<57:10,  7.64it/s]

 13%|█▎        | 3974/30196 [08:27<47:51,  9.13it/s]

 13%|█▎        | 3976/30196 [08:27<45:10,  9.67it/s]

 13%|█▎        | 3978/30196 [08:27<47:53,  9.12it/s]

 13%|█▎        | 3980/30196 [08:27<48:13,  9.06it/s]

 13%|█▎        | 3982/30196 [08:27<43:11, 10.12it/s]

 13%|█▎        | 3984/30196 [08:28<42:20, 10.32it/s]

 13%|█▎        | 3986/30196 [08:28<37:23, 11.68it/s]

 13%|█▎        | 3989/30196 [08:28<38:20, 11.39it/s]

 13%|█▎        | 3991/30196 [08:28<39:11, 11.14it/s]

 13%|█▎        | 3993/30196 [08:28<35:25, 12.33it/s]

 13%|█▎        | 3995/30196 [08:28<31:39, 13.79it/s]

 13%|█▎        | 3997/30196 [08:29<47:46,  9.14it/s]

 13%|█▎        | 3999/30196 [08:29<50:59,  8.56it/s]

 13%|█▎        | 4001/30196 [08:29<49:05,  8.89it/s]

 13%|█▎        | 4003/30196 [08:30<54:57,  7.94it/s]

 13%|█▎        | 4005/30196 [08:30<48:36,  8.98it/s]

 13%|█▎        | 4007/30196 [08:30<46:11,  9.45it/s]

 13%|█▎        | 4009/30196 [08:30<1:00:58,  7.16it/s]

 13%|█▎        | 4011/30196 [08:30<52:14,  8.35it/s]

 13%|█▎        | 4013/30196 [08:31<45:59,  9.49it/s]

 13%|█▎        | 4015/30196 [08:31<50:06,  8.71it/s]

 13%|█▎        | 4017/30196 [08:32<1:31:43,  4.76it/s]

 13%|█▎        | 4018/30196 [08:32<1:28:38,  4.92it/s]

 13%|█▎        | 4019/30196 [08:32<1:20:31,  5.42it/s]

 13%|█▎        | 4021/30196 [08:32<1:03:31,  6.87it/s]

 13%|█▎        | 4022/30196 [08:32<1:02:02,  7.03it/s]

 13%|█▎        | 4024/30196 [08:33<56:30,  7.72it/s]

 13%|█▎        | 4025/30196 [08:33<54:45,  7.97it/s]

 13%|█▎        | 4026/30196 [08:33<59:36,  7.32it/s]

 13%|█▎        | 4027/30196 [08:33<1:48:20,  4.03it/s]

 13%|█▎        | 4029/30196 [08:34<1:22:23,  5.29it/s]

 13%|█▎        | 4031/30196 [08:34<1:05:07,  6.70it/s]

 13%|█▎        | 4032/30196 [08:34<1:01:29,  7.09it/s]

 13%|█▎        | 4034/30196 [08:34<49:43,  8.77it/s]

 13%|█▎        | 4036/30196 [08:34<40:19, 10.81it/s]

 13%|█▎        | 4038/30196 [08:34<47:21,  9.21it/s]

 13%|█▎        | 4040/30196 [08:35<46:37,  9.35it/s]

 13%|█▎        | 4042/30196 [08:35<39:17, 11.09it/s]

 13%|█▎        | 4044/30196 [08:35<35:56, 12.13it/s]

 13%|█▎        | 4046/30196 [08:35<43:27, 10.03it/s]

 13%|█▎        | 4048/30196 [08:35<41:56, 10.39it/s]

 13%|█▎        | 4050/30196 [08:36<43:36,  9.99it/s]

 13%|█▎        | 4053/30196 [08:36<36:52, 11.81it/s]

 13%|█▎        | 4055/30196 [08:36<39:32, 11.02it/s]

 13%|█▎        | 4057/30196 [08:36<47:31,  9.17it/s]

 13%|█▎        | 4059/30196 [08:37<53:36,  8.13it/s]

 13%|█▎        | 4060/30196 [08:37<52:36,  8.28it/s]

 13%|█▎        | 4062/30196 [08:37<1:17:07,  5.65it/s]

 13%|█▎        | 4064/30196 [08:38<1:45:47,  4.12it/s]

 13%|█▎        | 4065/30196 [08:38<1:39:40,  4.37it/s]

 13%|█▎        | 4066/30196 [08:38<1:28:51,  4.90it/s]

 13%|█▎        | 4067/30196 [08:38<1:22:27,  5.28it/s]

 13%|█▎        | 4069/30196 [08:39<1:07:35,  6.44it/s]

 13%|█▎        | 4071/30196 [08:39<57:40,  7.55it/s]

 13%|█▎        | 4072/30196 [08:39<55:10,  7.89it/s]

 13%|█▎        | 4074/30196 [08:39<49:06,  8.87it/s]

 13%|█▎        | 4076/30196 [08:39<46:32,  9.35it/s]

 14%|█▎        | 4078/30196 [08:39<41:03, 10.60it/s]

 14%|█▎        | 4080/30196 [08:40<36:25, 11.95it/s]

 14%|█▎        | 4082/30196 [08:40<45:33,  9.55it/s]

 14%|█▎        | 4084/30196 [08:40<43:35,  9.98it/s]

 14%|█▎        | 4086/30196 [08:40<38:16, 11.37it/s]

 14%|█▎        | 4088/30196 [08:40<36:32, 11.91it/s]

 14%|█▎        | 4091/30196 [08:41<34:51, 12.48it/s]

 14%|█▎        | 4093/30196 [08:41<38:44, 11.23it/s]

 14%|█▎        | 4095/30196 [08:41<54:57,  7.91it/s]

 14%|█▎        | 4097/30196 [08:41<46:38,  9.33it/s]

 14%|█▎        | 4099/30196 [08:41<39:25, 11.03it/s]

 14%|█▎        | 4101/30196 [08:42<43:21, 10.03it/s]

 14%|█▎        | 4103/30196 [08:42<41:11, 10.56it/s]

 14%|█▎        | 4105/30196 [08:42<38:44, 11.23it/s]

 14%|█▎        | 4107/30196 [08:43<1:02:14,  6.99it/s]

 14%|█▎        | 4108/30196 [08:43<59:42,  7.28it/s]

 14%|█▎        | 4110/30196 [08:43<57:11,  7.60it/s]

 14%|█▎        | 4111/30196 [08:43<1:01:17,  7.09it/s]

 14%|█▎        | 4113/30196 [08:43<54:24,  7.99it/s]

 14%|█▎        | 4114/30196 [08:43<59:01,  7.36it/s]

 14%|█▎        | 4115/30196 [08:44<1:00:04,  7.24it/s]

 14%|█▎        | 4117/30196 [08:44<1:01:46,  7.04it/s]

 14%|█▎        | 4119/30196 [08:44<56:49,  7.65it/s]

 14%|█▎        | 4121/30196 [08:44<48:45,  8.91it/s]

 14%|█▎        | 4122/30196 [08:44<53:58,  8.05it/s]

 14%|█▎        | 4124/30196 [08:45<43:02, 10.10it/s]

 14%|█▎        | 4126/30196 [08:45<1:01:20,  7.08it/s]

 14%|█▎        | 4127/30196 [08:45<1:00:27,  7.19it/s]

 14%|█▎        | 4128/30196 [08:45<1:03:14,  6.87it/s]

 14%|█▎        | 4130/30196 [08:45<53:05,  8.18it/s]

 14%|█▎        | 4131/30196 [08:46<1:01:08,  7.10it/s]

 14%|█▎        | 4132/30196 [08:46<1:05:00,  6.68it/s]

 14%|█▎        | 4134/30196 [08:46<54:29,  7.97it/s]

 14%|█▎        | 4135/30196 [08:46<53:58,  8.05it/s]

 14%|█▎        | 4136/30196 [08:46<1:03:22,  6.85it/s]

 14%|█▎        | 4137/30196 [08:47<1:07:20,  6.45it/s]

 14%|█▎        | 4139/30196 [08:47<49:12,  8.83it/s]

 14%|█▎        | 4141/30196 [08:47<48:24,  8.97it/s]

 14%|█▎        | 4143/30196 [08:47<42:40, 10.17it/s]

 14%|█▎        | 4145/30196 [08:47<44:21,  9.79it/s]

 14%|█▎        | 4147/30196 [08:47<37:45, 11.50it/s]

 14%|█▎        | 4149/30196 [08:48<42:40, 10.17it/s]

 14%|█▎        | 4151/30196 [08:48<42:45, 10.15it/s]

 14%|█▍        | 4153/30196 [08:48<40:16, 10.78it/s]

 14%|█▍        | 4155/30196 [08:48<40:23, 10.75it/s]

 14%|█▍        | 4157/30196 [08:48<34:58, 12.41it/s]

 14%|█▍        | 4159/30196 [08:49<44:50,  9.68it/s]

 14%|█▍        | 4161/30196 [08:49<47:50,  9.07it/s]

 14%|█▍        | 4163/30196 [08:49<1:01:55,  7.01it/s]

 14%|█▍        | 4164/30196 [08:49<1:01:04,  7.10it/s]

 14%|█▍        | 4165/30196 [08:50<1:03:32,  6.83it/s]

 14%|█▍        | 4167/30196 [08:50<56:32,  7.67it/s]

 14%|█▍        | 4168/30196 [08:50<1:05:48,  6.59it/s]

 14%|█▍        | 4170/30196 [08:50<56:23,  7.69it/s]

 14%|█▍        | 4171/30196 [08:50<57:14,  7.58it/s]

 14%|█▍        | 4172/30196 [08:50<58:12,  7.45it/s]

 14%|█▍        | 4173/30196 [08:51<59:41,  7.27it/s]

 14%|█▍        | 4174/30196 [08:51<1:14:56,  5.79it/s]

 14%|█▍        | 4175/30196 [08:51<1:21:35,  5.32it/s]

 14%|█▍        | 4176/30196 [08:51<1:11:34,  6.06it/s]

 14%|█▍        | 4177/30196 [08:51<1:04:02,  6.77it/s]

 14%|█▍        | 4178/30196 [08:51<1:14:11,  5.84it/s]

 14%|█▍        | 4179/30196 [08:52<1:15:31,  5.74it/s]

 14%|█▍        | 4181/30196 [08:52<1:02:21,  6.95it/s]

 14%|█▍        | 4182/30196 [08:52<58:11,  7.45it/s]

 14%|█▍        | 4183/30196 [08:52<58:54,  7.36it/s]

 14%|█▍        | 4185/30196 [08:52<54:43,  7.92it/s]

 14%|█▍        | 4186/30196 [08:53<56:05,  7.73it/s]

 14%|█▍        | 4188/30196 [08:53<53:14,  8.14it/s]

 14%|█▍        | 4190/30196 [08:53<51:18,  8.45it/s]

 14%|█▍        | 4193/30196 [08:53<37:33, 11.54it/s]

 14%|█▍        | 4195/30196 [08:53<48:21,  8.96it/s]

 14%|█▍        | 4197/30196 [08:54<45:27,  9.53it/s]

 14%|█▍        | 4199/30196 [08:54<44:37,  9.71it/s]

 14%|█▍        | 4201/30196 [08:54<42:02, 10.30it/s]

 14%|█▍        | 4203/30196 [08:54<43:26,  9.97it/s]

 14%|█▍        | 4205/30196 [08:54<43:54,  9.87it/s]

 14%|█▍        | 4207/30196 [08:55<48:52,  8.86it/s]

 14%|█▍        | 4208/30196 [08:55<53:45,  8.06it/s]

 14%|█▍        | 4209/30196 [08:55<54:18,  7.98it/s]

 14%|█▍        | 4210/30196 [08:55<55:48,  7.76it/s]

 14%|█▍        | 4212/30196 [08:55<49:26,  8.76it/s]

 14%|█▍        | 4214/30196 [08:56<49:25,  8.76it/s]

 14%|█▍        | 4215/30196 [08:56<49:00,  8.84it/s]

 14%|█▍        | 4216/30196 [08:56<58:51,  7.36it/s]

 14%|█▍        | 4217/30196 [08:56<58:14,  7.43it/s]

 14%|█▍        | 4218/30196 [08:56<1:01:48,  7.01it/s]

 14%|█▍        | 4219/30196 [08:56<1:02:17,  6.95it/s]

 14%|█▍        | 4220/30196 [08:56<57:54,  7.48it/s]

 14%|█▍        | 4221/30196 [08:57<58:53,  7.35it/s]

 14%|█▍        | 4222/30196 [08:57<56:47,  7.62it/s]

 14%|█▍        | 4223/30196 [08:57<1:01:44,  7.01it/s]

 14%|█▍        | 4225/30196 [08:57<55:24,  7.81it/s]

 14%|█▍        | 4226/30196 [08:57<57:30,  7.53it/s]

 14%|█▍        | 4228/30196 [08:57<52:48,  8.20it/s]

 14%|█▍        | 4229/30196 [08:58<57:54,  7.47it/s]

 14%|█▍        | 4230/30196 [08:58<57:38,  7.51it/s]

 14%|█▍        | 4231/30196 [08:58<1:01:20,  7.05it/s]

 14%|█▍        | 4233/30196 [08:58<49:40,  8.71it/s]

 14%|█▍        | 4234/30196 [08:58<51:48,  8.35it/s]

 14%|█▍        | 4235/30196 [08:58<50:08,  8.63it/s]

 14%|█▍        | 4236/30196 [08:58<56:29,  7.66it/s]

 14%|█▍        | 4237/30196 [08:59<1:07:05,  6.45it/s]

 14%|█▍        | 4238/30196 [08:59<1:06:06,  6.54it/s]

 14%|█▍        | 4239/30196 [08:59<1:07:43,  6.39it/s]

 14%|█▍        | 4240/30196 [08:59<1:01:14,  7.06it/s]

 14%|█▍        | 4241/30196 [08:59<59:57,  7.22it/s]

 14%|█▍        | 4242/30196 [08:59<1:04:44,  6.68it/s]

 14%|█▍        | 4243/30196 [09:00<1:15:04,  5.76it/s]

 14%|█▍        | 4244/30196 [09:00<1:09:37,  6.21it/s]

 14%|█▍        | 4246/30196 [09:00<1:13:17,  5.90it/s]

 14%|█▍        | 4247/30196 [09:00<1:09:04,  6.26it/s]

 14%|█▍        | 4249/30196 [09:00<53:16,  8.12it/s]

 14%|█▍        | 4250/30196 [09:01<1:01:28,  7.03it/s]

 14%|█▍        | 4252/30196 [09:01<52:38,  8.21it/s]

 14%|█▍        | 4253/30196 [09:01<56:49,  7.61it/s]

 14%|█▍        | 4254/30196 [09:01<1:19:41,  5.43it/s]

 14%|█▍        | 4255/30196 [09:01<1:19:03,  5.47it/s]

 14%|█▍        | 4257/30196 [09:02<1:10:11,  6.16it/s]

 14%|█▍        | 4258/30196 [09:02<1:07:07,  6.44it/s]

 14%|█▍        | 4259/30196 [09:02<1:03:20,  6.82it/s]

 14%|█▍        | 4261/30196 [09:02<51:42,  8.36it/s]

 14%|█▍        | 4263/30196 [09:02<47:14,  9.15it/s]

 14%|█▍        | 4265/30196 [09:02<38:49, 11.13it/s]

 14%|█▍        | 4267/30196 [09:03<40:31, 10.66it/s]

 14%|█▍        | 4269/30196 [09:03<37:30, 11.52it/s]

 14%|█▍        | 4271/30196 [09:03<41:18, 10.46it/s]

 14%|█▍        | 4273/30196 [09:04<1:07:51,  6.37it/s]

 14%|█▍        | 4274/30196 [09:04<1:05:48,  6.57it/s]

 14%|█▍        | 4275/30196 [09:04<1:07:18,  6.42it/s]

 14%|█▍        | 4277/30196 [09:04<59:50,  7.22it/s]

 14%|█▍        | 4278/30196 [09:04<1:03:09,  6.84it/s]

 14%|█▍        | 4279/30196 [09:04<1:01:51,  6.98it/s]

 14%|█▍        | 4280/30196 [09:05<57:43,  7.48it/s]

 14%|█▍        | 4283/30196 [09:05<41:08, 10.50it/s]

 14%|█▍        | 4285/30196 [09:05<39:24, 10.96it/s]

 14%|█▍        | 4287/30196 [09:05<41:02, 10.52it/s]

 14%|█▍        | 4289/30196 [09:05<51:12,  8.43it/s]

 14%|█▍        | 4290/30196 [09:06<50:01,  8.63it/s]

 14%|█▍        | 4292/30196 [09:06<52:10,  8.28it/s]

 14%|█▍        | 4294/30196 [09:06<47:54,  9.01it/s]

 14%|█▍        | 4296/30196 [09:06<41:04, 10.51it/s]

 14%|█▍        | 4298/30196 [09:07<1:02:10,  6.94it/s]

 14%|█▍        | 4300/30196 [09:07<55:13,  7.82it/s]

 14%|█▍        | 4302/30196 [09:07<59:27,  7.26it/s]

 14%|█▍        | 4304/30196 [09:07<48:11,  8.95it/s]

 14%|█▍        | 4306/30196 [09:07<44:05,  9.79it/s]

 14%|█▍        | 4308/30196 [09:08<1:04:13,  6.72it/s]

 14%|█▍        | 4310/30196 [09:08<1:02:07,  6.94it/s]

 14%|█▍        | 4311/30196 [09:09<1:23:28,  5.17it/s]

 14%|█▍        | 4312/30196 [09:09<1:18:51,  5.47it/s]

 14%|█▍        | 4313/30196 [09:09<1:14:18,  5.80it/s]

 14%|█▍        | 4315/30196 [09:09<56:31,  7.63it/s]

 14%|█▍        | 4316/30196 [09:09<1:00:18,  7.15it/s]

 14%|█▍        | 4318/30196 [09:09<59:21,  7.27it/s]

 14%|█▍        | 4319/30196 [09:10<58:43,  7.34it/s]

 14%|█▍        | 4321/30196 [09:10<44:45,  9.64it/s]

 14%|█▍        | 4323/30196 [09:10<43:35,  9.89it/s]

 14%|█▍        | 4325/30196 [09:10<37:40, 11.44it/s]

 14%|█▍        | 4327/30196 [09:10<36:10, 11.92it/s]

 14%|█▍        | 4329/30196 [09:10<36:19, 11.87it/s]

 14%|█▍        | 4331/30196 [09:11<39:05, 11.03it/s]

 14%|█▍        | 4333/30196 [09:11<39:07, 11.02it/s]

 14%|█▍        | 4335/30196 [09:11<35:34, 12.12it/s]

 14%|█▍        | 4337/30196 [09:11<39:03, 11.04it/s]

 14%|█▍        | 4339/30196 [09:11<42:58, 10.03it/s]

 14%|█▍        | 4341/30196 [09:11<41:51, 10.29it/s]

 14%|█▍        | 4343/30196 [09:12<40:00, 10.77it/s]

 14%|█▍        | 4345/30196 [09:12<47:16,  9.11it/s]

 14%|█▍        | 4347/30196 [09:12<43:42,  9.86it/s]

 14%|█▍        | 4349/30196 [09:12<39:26, 10.92it/s]

 14%|█▍        | 4351/30196 [09:12<43:52,  9.82it/s]

 14%|█▍        | 4353/30196 [09:13<40:48, 10.55it/s]

 14%|█▍        | 4355/30196 [09:13<47:39,  9.04it/s]

 14%|█▍        | 4356/30196 [09:13<52:46,  8.16it/s]

 14%|█▍        | 4357/30196 [09:13<53:36,  8.03it/s]

 14%|█▍        | 4358/30196 [09:13<55:55,  7.70it/s]

 14%|█▍        | 4360/30196 [09:14<44:26,  9.69it/s]

 14%|█▍        | 4362/30196 [09:14<41:03, 10.49it/s]

 14%|█▍        | 4364/30196 [09:14<49:00,  8.79it/s]

 14%|█▍        | 4365/30196 [09:14<51:50,  8.31it/s]

 14%|█▍        | 4367/30196 [09:14<50:29,  8.53it/s]

 14%|█▍        | 4369/30196 [09:15<49:44,  8.65it/s]

 14%|█▍        | 4370/30196 [09:15<57:28,  7.49it/s]

 14%|█▍        | 4372/30196 [09:15<47:08,  9.13it/s]

 14%|█▍        | 4373/30196 [09:15<56:11,  7.66it/s]

 14%|█▍        | 4374/30196 [09:15<1:00:45,  7.08it/s]

 14%|█▍        | 4375/30196 [09:15<1:00:08,  7.16it/s]

 14%|█▍        | 4376/30196 [09:16<1:01:00,  7.05it/s]

 14%|█▍        | 4377/30196 [09:16<1:00:16,  7.14it/s]

 15%|█▍        | 4379/30196 [09:16<58:18,  7.38it/s]

 15%|█▍        | 4381/30196 [09:16<44:21,  9.70it/s]

 15%|█▍        | 4383/30196 [09:16<57:57,  7.42it/s]

 15%|█▍        | 4385/30196 [09:17<52:22,  8.21it/s]

 15%|█▍        | 4386/30196 [09:17<56:06,  7.67it/s]

 15%|█▍        | 4387/30196 [09:17<54:16,  7.93it/s]

 15%|█▍        | 4389/30196 [09:17<44:43,  9.62it/s]

 15%|█▍        | 4391/30196 [09:17<40:28, 10.63it/s]

 15%|█▍        | 4393/30196 [09:17<36:38, 11.74it/s]

 15%|█▍        | 4395/30196 [09:18<39:11, 10.97it/s]

 15%|█▍        | 4397/30196 [09:18<40:52, 10.52it/s]

 15%|█▍        | 4399/30196 [09:18<41:25, 10.38it/s]

 15%|█▍        | 4401/30196 [09:18<42:58, 10.00it/s]

 15%|█▍        | 4403/30196 [09:18<47:48,  8.99it/s]

 15%|█▍        | 4405/30196 [09:19<45:53,  9.37it/s]

 15%|█▍        | 4407/30196 [09:19<40:47, 10.53it/s]

 15%|█▍        | 4409/30196 [09:19<43:55,  9.78it/s]

 15%|█▍        | 4411/30196 [09:19<48:15,  8.91it/s]

 15%|█▍        | 4412/30196 [09:19<49:58,  8.60it/s]

 15%|█▍        | 4414/30196 [09:20<50:25,  8.52it/s]

 15%|█▍        | 4416/30196 [09:20<42:10, 10.19it/s]

 15%|█▍        | 4418/30196 [09:20<1:03:36,  6.75it/s]

 15%|█▍        | 4419/30196 [09:20<1:03:34,  6.76it/s]

 15%|█▍        | 4421/30196 [09:21<58:48,  7.30it/s]

 15%|█▍        | 4422/30196 [09:21<1:08:57,  6.23it/s]

 15%|█▍        | 4423/30196 [09:21<1:04:05,  6.70it/s]

 15%|█▍        | 4425/30196 [09:21<49:27,  8.69it/s]

 15%|█▍        | 4427/30196 [09:21<47:49,  8.98it/s]

 15%|█▍        | 4429/30196 [09:22<49:46,  8.63it/s]

 15%|█▍        | 4430/30196 [09:22<52:22,  8.20it/s]

 15%|█▍        | 4431/30196 [09:22<54:41,  7.85it/s]

 15%|█▍        | 4432/30196 [09:22<54:58,  7.81it/s]

 15%|█▍        | 4433/30196 [09:22<1:00:14,  7.13it/s]

 15%|█▍        | 4435/30196 [09:23<1:01:36,  6.97it/s]

 15%|█▍        | 4436/30196 [09:23<1:14:06,  5.79it/s]

 15%|█▍        | 4437/30196 [09:23<1:22:34,  5.20it/s]

 15%|█▍        | 4438/30196 [09:23<1:13:14,  5.86it/s]

 15%|█▍        | 4440/30196 [09:23<1:01:10,  7.02it/s]

 15%|█▍        | 4443/30196 [09:24<41:30, 10.34it/s]

 15%|█▍        | 4445/30196 [09:24<49:49,  8.61it/s]

 15%|█▍        | 4447/30196 [09:24<48:40,  8.82it/s]

 15%|█▍        | 4448/30196 [09:24<59:26,  7.22it/s]

 15%|█▍        | 4450/30196 [09:24<50:11,  8.55it/s]

 15%|█▍        | 4452/30196 [09:25<44:00,  9.75it/s]

 15%|█▍        | 4454/30196 [09:25<49:28,  8.67it/s]

 15%|█▍        | 4456/30196 [09:25<45:04,  9.52it/s]

 15%|█▍        | 4458/30196 [09:25<39:14, 10.93it/s]

 15%|█▍        | 4460/30196 [09:25<43:20,  9.90it/s]

 15%|█▍        | 4462/30196 [09:26<44:31,  9.63it/s]

 15%|█▍        | 4464/30196 [09:26<44:43,  9.59it/s]

 15%|█▍        | 4466/30196 [09:26<40:45, 10.52it/s]

 15%|█▍        | 4468/30196 [09:26<45:55,  9.34it/s]

 15%|█▍        | 4470/30196 [09:26<44:39,  9.60it/s]

 15%|█▍        | 4472/30196 [09:27<47:56,  8.94it/s]

 15%|█▍        | 4474/30196 [09:27<43:46,  9.79it/s]

 15%|█▍        | 4476/30196 [09:27<48:03,  8.92it/s]

 15%|█▍        | 4478/30196 [09:27<43:06,  9.94it/s]

 15%|█▍        | 4480/30196 [09:28<46:39,  9.19it/s]

 15%|█▍        | 4481/30196 [09:28<51:13,  8.37it/s]

 15%|█▍        | 4482/30196 [09:28<50:26,  8.50it/s]

 15%|█▍        | 4483/30196 [09:28<51:36,  8.30it/s]

 15%|█▍        | 4484/30196 [09:28<53:39,  7.99it/s]

 15%|█▍        | 4486/30196 [09:28<51:12,  8.37it/s]

 15%|█▍        | 4487/30196 [09:28<55:54,  7.66it/s]

 15%|█▍        | 4488/30196 [09:29<53:12,  8.05it/s]

 15%|█▍        | 4489/30196 [09:29<58:07,  7.37it/s]

 15%|█▍        | 4491/30196 [09:29<46:31,  9.21it/s]

 15%|█▍        | 4493/30196 [09:29<40:50, 10.49it/s]

 15%|█▍        | 4495/30196 [09:29<54:22,  7.88it/s]

 15%|█▍        | 4496/30196 [09:30<57:45,  7.42it/s]

 15%|█▍        | 4497/30196 [09:30<1:04:31,  6.64it/s]

 15%|█▍        | 4498/30196 [09:30<1:02:28,  6.86it/s]

 15%|█▍        | 4499/30196 [09:30<58:36,  7.31it/s]

 15%|█▍        | 4501/30196 [09:30<43:14,  9.91it/s]

 15%|█▍        | 4503/30196 [09:30<41:10, 10.40it/s]

 15%|█▍        | 4505/30196 [09:30<36:59, 11.57it/s]

 15%|█▍        | 4507/30196 [09:31<34:51, 12.29it/s]

 15%|█▍        | 4509/30196 [09:31<42:35, 10.05it/s]

 15%|█▍        | 4511/30196 [09:31<42:08, 10.16it/s]

 15%|█▍        | 4513/30196 [09:31<50:46,  8.43it/s]

 15%|█▍        | 4514/30196 [09:32<51:39,  8.28it/s]

 15%|█▍        | 4515/30196 [09:32<54:03,  7.92it/s]

 15%|█▍        | 4516/30196 [09:32<55:29,  7.71it/s]

 15%|█▍        | 4517/30196 [09:32<56:03,  7.64it/s]

 15%|█▍        | 4519/30196 [09:32<50:07,  8.54it/s]

 15%|█▍        | 4521/30196 [09:32<40:04, 10.68it/s]

 15%|█▍        | 4523/30196 [09:33<53:14,  8.04it/s]

 15%|█▍        | 4525/30196 [09:33<42:58,  9.96it/s]

 15%|█▍        | 4527/30196 [09:33<48:16,  8.86it/s]

 15%|█▍        | 4529/30196 [09:33<46:23,  9.22it/s]

 15%|█▌        | 4531/30196 [09:33<44:16,  9.66it/s]

 15%|█▌        | 4533/30196 [09:34<40:31, 10.56it/s]

 15%|█▌        | 4535/30196 [09:34<43:12,  9.90it/s]

 15%|█▌        | 4537/30196 [09:34<42:08, 10.15it/s]

 15%|█▌        | 4539/30196 [09:34<48:32,  8.81it/s]

 15%|█▌        | 4542/30196 [09:34<41:02, 10.42it/s]

 15%|█▌        | 4544/30196 [09:35<41:32, 10.29it/s]

 15%|█▌        | 4546/30196 [09:35<50:40,  8.44it/s]

 15%|█▌        | 4547/30196 [09:35<50:48,  8.41it/s]

 15%|█▌        | 4549/30196 [09:35<43:29,  9.83it/s]

 15%|█▌        | 4551/30196 [09:35<41:37, 10.27it/s]

 15%|█▌        | 4553/30196 [09:36<45:45,  9.34it/s]

 15%|█▌        | 4555/30196 [09:36<51:05,  8.36it/s]

 15%|█▌        | 4556/30196 [09:36<49:51,  8.57it/s]

 15%|█▌        | 4557/30196 [09:36<51:22,  8.32it/s]

 15%|█▌        | 4558/30196 [09:36<1:01:12,  6.98it/s]

 15%|█▌        | 4559/30196 [09:37<57:46,  7.40it/s]

 15%|█▌        | 4560/30196 [09:37<1:05:46,  6.50it/s]

 15%|█▌        | 4562/30196 [09:37<48:25,  8.82it/s]

 15%|█▌        | 4564/30196 [09:37<44:22,  9.63it/s]

 15%|█▌        | 4566/30196 [09:37<52:50,  8.08it/s]

 15%|█▌        | 4568/30196 [09:38<48:55,  8.73it/s]

 15%|█▌        | 4569/30196 [09:38<51:02,  8.37it/s]

 15%|█▌        | 4570/30196 [09:38<59:06,  7.23it/s]

 15%|█▌        | 4572/30196 [09:38<53:23,  8.00it/s]

 15%|█▌        | 4573/30196 [09:38<55:24,  7.71it/s]

 15%|█▌        | 4574/30196 [09:38<59:16,  7.20it/s]

 15%|█▌        | 4575/30196 [09:39<59:26,  7.18it/s]

 15%|█▌        | 4577/30196 [09:39<50:30,  8.45it/s]

 15%|█▌        | 4578/30196 [09:39<49:40,  8.59it/s]

 15%|█▌        | 4580/30196 [09:39<42:15, 10.10it/s]

 15%|█▌        | 4582/30196 [09:39<45:11,  9.45it/s]

 15%|█▌        | 4583/30196 [09:39<48:30,  8.80it/s]

 15%|█▌        | 4584/30196 [09:40<53:51,  7.93it/s]

 15%|█▌        | 4587/30196 [09:40<44:26,  9.61it/s]

 15%|█▌        | 4588/30196 [09:40<46:35,  9.16it/s]

 15%|█▌        | 4589/30196 [09:40<52:21,  8.15it/s]

 15%|█▌        | 4590/30196 [09:40<53:39,  7.95it/s]

 15%|█▌        | 4592/30196 [09:40<50:41,  8.42it/s]

 15%|█▌        | 4593/30196 [09:41<49:20,  8.65it/s]

 15%|█▌        | 4594/30196 [09:41<1:07:03,  6.36it/s]

 15%|█▌        | 4595/30196 [09:41<1:01:11,  6.97it/s]

 15%|█▌        | 4597/30196 [09:41<46:04,  9.26it/s]

 15%|█▌        | 4599/30196 [09:41<47:35,  8.96it/s]

 15%|█▌        | 4600/30196 [09:41<50:12,  8.50it/s]

 15%|█▌        | 4601/30196 [09:42<52:31,  8.12it/s]

 15%|█▌        | 4602/30196 [09:42<51:10,  8.33it/s]

 15%|█▌        | 4603/30196 [09:42<59:19,  7.19it/s]

 15%|█▌        | 4605/30196 [09:42<54:14,  7.86it/s]

 15%|█▌        | 4606/30196 [09:42<52:21,  8.14it/s]

 15%|█▌        | 4608/30196 [09:42<46:25,  9.19it/s]

 15%|█▌        | 4609/30196 [09:43<47:30,  8.98it/s]

 15%|█▌        | 4610/30196 [09:43<50:35,  8.43it/s]

 15%|█▌        | 4611/30196 [09:43<49:36,  8.60it/s]

 15%|█▌        | 4612/30196 [09:43<51:18,  8.31it/s]

 15%|█▌        | 4614/30196 [09:43<44:13,  9.64it/s]

 15%|█▌        | 4615/30196 [09:43<52:02,  8.19it/s]

 15%|█▌        | 4616/30196 [09:43<1:02:05,  6.87it/s]

 15%|█▌        | 4618/30196 [09:44<48:08,  8.86it/s]

 15%|█▌        | 4620/30196 [09:44<1:41:04,  4.22it/s]

 15%|█▌        | 4621/30196 [09:45<1:29:33,  4.76it/s]

 15%|█▌        | 4622/30196 [09:45<1:22:12,  5.18it/s]

 15%|█▌        | 4623/30196 [09:45<1:16:39,  5.56it/s]

 15%|█▌        | 4624/30196 [09:45<1:30:40,  4.70it/s]

 15%|█▌        | 4625/30196 [09:45<1:30:11,  4.73it/s]

 15%|█▌        | 4627/30196 [09:46<1:05:36,  6.50it/s]

 15%|█▌        | 4628/30196 [09:46<1:03:17,  6.73it/s]

 15%|█▌        | 4629/30196 [09:46<1:01:29,  6.93it/s]

 15%|█▌        | 4630/30196 [09:46<1:05:32,  6.50it/s]

 15%|█▌        | 4631/30196 [09:46<1:07:04,  6.35it/s]

 15%|█▌        | 4632/30196 [09:46<1:08:23,  6.23it/s]

 15%|█▌        | 4633/30196 [09:47<1:19:32,  5.36it/s]

 15%|█▌        | 4634/30196 [09:47<1:12:30,  5.88it/s]

 15%|█▌        | 4635/30196 [09:47<1:04:23,  6.62it/s]

 15%|█▌        | 4636/30196 [09:47<1:12:10,  5.90it/s]

 15%|█▌        | 4638/30196 [09:47<53:06,  8.02it/s]

 15%|█▌        | 4639/30196 [09:47<53:56,  7.90it/s]

 15%|█▌        | 4641/30196 [09:48<57:00,  7.47it/s]

 15%|█▌        | 4642/30196 [09:48<57:06,  7.46it/s]

 15%|█▌        | 4644/30196 [09:48<51:20,  8.30it/s]

 15%|█▌        | 4645/30196 [09:48<52:34,  8.10it/s]

 15%|█▌        | 4646/30196 [09:48<54:01,  7.88it/s]

 15%|█▌        | 4647/30196 [09:48<1:03:18,  6.73it/s]

 15%|█▌        | 4648/30196 [09:49<58:44,  7.25it/s]

 15%|█▌        | 4649/30196 [09:49<1:00:55,  6.99it/s]

 15%|█▌        | 4651/30196 [09:49<47:28,  8.97it/s]

 15%|█▌        | 4653/30196 [09:49<41:16, 10.32it/s]

 15%|█▌        | 4655/30196 [09:49<49:13,  8.65it/s]

 15%|█▌        | 4657/30196 [09:50<53:26,  7.97it/s]

 15%|█▌        | 4659/30196 [09:50<49:16,  8.64it/s]

 15%|█▌        | 4660/30196 [09:50<50:38,  8.40it/s]

 15%|█▌        | 4662/30196 [09:50<49:29,  8.60it/s]

 15%|█▌        | 4663/30196 [09:50<51:04,  8.33it/s]

 15%|█▌        | 4664/30196 [09:50<53:07,  8.01it/s]

 15%|█▌        | 4666/30196 [09:51<44:04,  9.65it/s]

 15%|█▌        | 4667/30196 [09:51<50:39,  8.40it/s]

 15%|█▌        | 4669/30196 [09:51<54:33,  7.80it/s]

 15%|█▌        | 4670/30196 [09:51<55:41,  7.64it/s]

 15%|█▌        | 4671/30196 [09:51<59:11,  7.19it/s]

 15%|█▌        | 4672/30196 [09:51<56:02,  7.59it/s]

 15%|█▌        | 4673/30196 [09:52<1:01:35,  6.91it/s]

 15%|█▌        | 4675/30196 [09:52<52:25,  8.11it/s]

 15%|█▌        | 4676/30196 [09:52<54:15,  7.84it/s]

 15%|█▌        | 4677/30196 [09:52<54:36,  7.79it/s]

 15%|█▌        | 4678/30196 [09:52<52:33,  8.09it/s]

 15%|█▌        | 4679/30196 [09:52<57:50,  7.35it/s]

 15%|█▌        | 4680/30196 [09:53<1:07:46,  6.27it/s]

 16%|█▌        | 4682/30196 [09:53<55:51,  7.61it/s]

 16%|█▌        | 4684/30196 [09:53<48:41,  8.73it/s]

 16%|█▌        | 4686/30196 [09:53<43:30,  9.77it/s]

 16%|█▌        | 4687/30196 [09:53<44:07,  9.64it/s]

 16%|█▌        | 4689/30196 [09:53<40:48, 10.42it/s]

 16%|█▌        | 4691/30196 [09:54<43:56,  9.67it/s]

 16%|█▌        | 4693/30196 [09:54<47:54,  8.87it/s]

 16%|█▌        | 4695/30196 [09:54<39:48, 10.68it/s]

 16%|█▌        | 4697/30196 [09:54<56:39,  7.50it/s]

 16%|█▌        | 4698/30196 [09:55<1:00:06,  7.07it/s]

 16%|█▌        | 4700/30196 [09:55<51:16,  8.29it/s]

 16%|█▌        | 4701/30196 [09:55<52:27,  8.10it/s]

 16%|█▌        | 4702/30196 [09:55<54:02,  7.86it/s]

 16%|█▌        | 4703/30196 [09:55<51:45,  8.21it/s]

 16%|█▌        | 4705/30196 [09:55<59:39,  7.12it/s]

 16%|█▌        | 4706/30196 [09:56<1:00:13,  7.05it/s]

 16%|█▌        | 4707/30196 [09:56<59:56,  7.09it/s]

 16%|█▌        | 4709/30196 [09:56<51:49,  8.20it/s]

 16%|█▌        | 4711/30196 [09:56<49:08,  8.64it/s]

 16%|█▌        | 4712/30196 [09:57<1:16:10,  5.58it/s]

 16%|█▌        | 4713/30196 [09:57<1:09:23,  6.12it/s]

 16%|█▌        | 4715/30196 [09:57<54:40,  7.77it/s]

 16%|█▌        | 4717/30196 [09:57<54:17,  7.82it/s]

 16%|█▌        | 4718/30196 [09:57<1:14:22,  5.71it/s]

 16%|█▌        | 4720/30196 [09:58<1:05:12,  6.51it/s]

 16%|█▌        | 4721/30196 [09:58<1:00:51,  6.98it/s]

 16%|█▌        | 4723/30196 [09:58<55:00,  7.72it/s]

 16%|█▌        | 4724/30196 [09:58<55:26,  7.66it/s]

 16%|█▌        | 4726/30196 [09:58<46:02,  9.22it/s]

 16%|█▌        | 4727/30196 [09:58<48:28,  8.76it/s]

 16%|█▌        | 4728/30196 [09:59<53:37,  7.92it/s]

 16%|█▌        | 4729/30196 [09:59<53:56,  7.87it/s]

 16%|█▌        | 4730/30196 [09:59<1:03:44,  6.66it/s]

 16%|█▌        | 4732/30196 [09:59<1:00:12,  7.05it/s]

 16%|█▌        | 4734/30196 [09:59<52:57,  8.01it/s]

 16%|█▌        | 4735/30196 [10:00<58:01,  7.31it/s]

 16%|█▌        | 4737/30196 [10:00<50:15,  8.44it/s]

 16%|█▌        | 4738/30196 [10:00<49:29,  8.57it/s]

 16%|█▌        | 4739/30196 [10:00<50:51,  8.34it/s]

 16%|█▌        | 4740/30196 [10:00<57:05,  7.43it/s]

 16%|█▌        | 4741/30196 [10:00<54:20,  7.81it/s]

 16%|█▌        | 4743/30196 [10:00<46:04,  9.21it/s]

 16%|█▌        | 4745/30196 [10:01<45:21,  9.35it/s]

 16%|█▌        | 4747/30196 [10:01<44:33,  9.52it/s]

 16%|█▌        | 4748/30196 [10:01<47:01,  9.02it/s]

 16%|█▌        | 4750/30196 [10:01<38:49, 10.92it/s]

 16%|█▌        | 4752/30196 [10:01<37:57, 11.17it/s]

 16%|█▌        | 4754/30196 [10:01<35:48, 11.84it/s]

 16%|█▌        | 4756/30196 [10:02<34:22, 12.34it/s]

 16%|█▌        | 4758/30196 [10:02<31:45, 13.35it/s]

 16%|█▌        | 4760/30196 [10:02<30:53, 13.72it/s]

 16%|█▌        | 4762/30196 [10:02<54:10,  7.82it/s]

 16%|█▌        | 4764/30196 [10:03<53:51,  7.87it/s]

 16%|█▌        | 4766/30196 [10:03<49:24,  8.58it/s]

 16%|█▌        | 4768/30196 [10:03<43:48,  9.68it/s]

 16%|█▌        | 4770/30196 [10:03<45:51,  9.24it/s]

 16%|█▌        | 4772/30196 [10:03<51:15,  8.27it/s]

 16%|█▌        | 4774/30196 [10:04<46:15,  9.16it/s]

 16%|█▌        | 4776/30196 [10:04<43:20,  9.77it/s]

 16%|█▌        | 4778/30196 [10:04<45:21,  9.34it/s]

 16%|█▌        | 4779/30196 [10:04<48:24,  8.75it/s]

 16%|█▌        | 4781/30196 [10:04<43:35,  9.72it/s]

 16%|█▌        | 4783/30196 [10:05<45:35,  9.29it/s]

 16%|█▌        | 4784/30196 [10:05<1:36:46,  4.38it/s]

 16%|█▌        | 4786/30196 [10:05<1:16:43,  5.52it/s]

 16%|█▌        | 4787/30196 [10:06<1:15:21,  5.62it/s]

 16%|█▌        | 4788/30196 [10:06<1:11:51,  5.89it/s]

 16%|█▌        | 4789/30196 [10:06<1:09:33,  6.09it/s]

 16%|█▌        | 4790/30196 [10:06<1:10:36,  6.00it/s]

 16%|█▌        | 4792/30196 [10:06<1:00:02,  7.05it/s]

 16%|█▌        | 4793/30196 [10:07<1:07:14,  6.30it/s]

 16%|█▌        | 4794/30196 [10:07<1:16:48,  5.51it/s]

 16%|█▌        | 4795/30196 [10:07<1:08:56,  6.14it/s]

 16%|█▌        | 4797/30196 [10:07<1:02:51,  6.73it/s]

 16%|█▌        | 4798/30196 [10:07<58:36,  7.22it/s]

 16%|█▌        | 4799/30196 [10:07<59:31,  7.11it/s]

 16%|█▌        | 4800/30196 [10:07<55:28,  7.63it/s]

 16%|█▌        | 4802/30196 [10:08<47:39,  8.88it/s]

 16%|█▌        | 4803/30196 [10:08<1:13:47,  5.74it/s]

 16%|█▌        | 4805/30196 [10:08<57:29,  7.36it/s]

 16%|█▌        | 4807/30196 [10:08<45:25,  9.32it/s]

 16%|█▌        | 4809/30196 [10:08<42:40,  9.91it/s]

 16%|█▌        | 4811/30196 [10:09<47:24,  8.92it/s]

 16%|█▌        | 4813/30196 [10:09<51:19,  8.24it/s]

 16%|█▌        | 4814/30196 [10:09<52:51,  8.00it/s]

 16%|█▌        | 4816/30196 [10:09<52:51,  8.00it/s]

 16%|█▌        | 4818/30196 [10:10<49:05,  8.62it/s]

 16%|█▌        | 4820/30196 [10:10<41:38, 10.16it/s]

 16%|█▌        | 4822/30196 [10:10<42:50,  9.87it/s]

 16%|█▌        | 4824/30196 [10:10<51:31,  8.21it/s]

 16%|█▌        | 4825/30196 [10:10<55:56,  7.56it/s]

 16%|█▌        | 4826/30196 [10:11<1:00:06,  7.04it/s]

 16%|█▌        | 4828/30196 [10:11<54:27,  7.76it/s]

 16%|█▌        | 4830/30196 [10:11<58:20,  7.25it/s]

 16%|█▌        | 4831/30196 [10:11<1:01:26,  6.88it/s]

 16%|█▌        | 4833/30196 [10:11<49:46,  8.49it/s]

 16%|█▌        | 4834/30196 [10:12<48:43,  8.67it/s]

 16%|█▌        | 4836/30196 [10:12<47:56,  8.82it/s]

 16%|█▌        | 4837/30196 [10:12<1:00:28,  6.99it/s]

 16%|█▌        | 4838/30196 [10:12<57:12,  7.39it/s]

 16%|█▌        | 4839/30196 [10:12<54:20,  7.78it/s]

 16%|█▌        | 4840/30196 [10:12<52:15,  8.09it/s]

 16%|█▌        | 4841/30196 [10:13<53:40,  7.87it/s]

 16%|█▌        | 4842/30196 [10:13<55:22,  7.63it/s]

 16%|█▌        | 4844/30196 [10:13<50:10,  8.42it/s]

 16%|█▌        | 4846/30196 [10:13<39:11, 10.78it/s]

 16%|█▌        | 4848/30196 [10:13<58:01,  7.28it/s]

 16%|█▌        | 4850/30196 [10:14<53:50,  7.84it/s]

 16%|█▌        | 4851/30196 [10:14<54:00,  7.82it/s]

 16%|█▌        | 4852/30196 [10:14<1:01:54,  6.82it/s]

 16%|█▌        | 4855/30196 [10:14<41:15, 10.24it/s]

 16%|█▌        | 4857/30196 [10:14<42:07, 10.03it/s]

 16%|█▌        | 4859/30196 [10:15<47:01,  8.98it/s]

 16%|█▌        | 4861/30196 [10:15<41:57, 10.07it/s]

 16%|█▌        | 4863/30196 [10:15<37:01, 11.41it/s]

 16%|█▌        | 4865/30196 [10:15<40:12, 10.50it/s]

 16%|█▌        | 4867/30196 [10:15<46:16,  9.12it/s]

 16%|█▌        | 4869/30196 [10:16<1:02:25,  6.76it/s]

 16%|█▌        | 4871/30196 [10:16<51:09,  8.25it/s]

 16%|█▌        | 4873/30196 [10:16<45:17,  9.32it/s]

 16%|█▌        | 4875/30196 [10:16<50:50,  8.30it/s]

 16%|█▌        | 4877/30196 [10:17<43:12,  9.77it/s]

 16%|█▌        | 4879/30196 [10:17<41:30, 10.17it/s]

 16%|█▌        | 4881/30196 [10:17<44:31,  9.48it/s]

 16%|█▌        | 4883/30196 [10:17<42:35,  9.91it/s]

 16%|█▌        | 4885/30196 [10:17<49:37,  8.50it/s]

 16%|█▌        | 4886/30196 [10:18<48:39,  8.67it/s]

 16%|█▌        | 4888/30196 [10:18<50:14,  8.40it/s]

 16%|█▌        | 4889/30196 [10:18<1:04:06,  6.58it/s]

 16%|█▌        | 4890/30196 [10:18<1:02:34,  6.74it/s]

 16%|█▌        | 4891/30196 [10:18<1:04:16,  6.56it/s]

 16%|█▌        | 4893/30196 [10:19<49:08,  8.58it/s]

 16%|█▌        | 4894/30196 [10:19<58:56,  7.15it/s]

 16%|█▌        | 4895/30196 [10:19<55:56,  7.54it/s]

 16%|█▌        | 4896/30196 [10:19<1:00:56,  6.92it/s]

 16%|█▌        | 4898/30196 [10:19<45:24,  9.28it/s]

 16%|█▌        | 4900/30196 [10:19<42:49,  9.85it/s]

 16%|█▌        | 4902/30196 [10:20<39:56, 10.55it/s]

 16%|█▌        | 4904/30196 [10:20<46:06,  9.14it/s]

 16%|█▌        | 4906/30196 [10:20<44:55,  9.38it/s]

 16%|█▋        | 4907/30196 [10:20<45:12,  9.32it/s]

 16%|█▋        | 4909/30196 [10:20<37:32, 11.23it/s]

 16%|█▋        | 4911/30196 [10:20<42:33,  9.90it/s]

 16%|█▋        | 4913/30196 [10:21<43:47,  9.62it/s]

 16%|█▋        | 4915/30196 [10:21<1:00:10,  7.00it/s]

 16%|█▋        | 4916/30196 [10:21<57:14,  7.36it/s]

 16%|█▋        | 4917/30196 [10:21<57:08,  7.37it/s]

 16%|█▋        | 4918/30196 [10:22<1:00:51,  6.92it/s]

 16%|█▋        | 4920/30196 [10:22<52:24,  8.04it/s]

 16%|█▋        | 4921/30196 [10:22<1:00:48,  6.93it/s]

 16%|█▋        | 4923/30196 [10:22<48:26,  8.70it/s]

 16%|█▋        | 4926/30196 [10:22<37:34, 11.21it/s]

 16%|█▋        | 4928/30196 [10:23<42:17,  9.96it/s]

 16%|█▋        | 4930/30196 [10:23<41:52, 10.06it/s]

 16%|█▋        | 4932/30196 [10:23<54:18,  7.75it/s]

 16%|█▋        | 4933/30196 [10:23<52:52,  7.96it/s]

 16%|█▋        | 4935/30196 [10:24<57:06,  7.37it/s]

 16%|█▋        | 4936/30196 [10:24<1:03:58,  6.58it/s]

 16%|█▋        | 4937/30196 [10:24<1:13:12,  5.75it/s]

 16%|█▋        | 4938/30196 [10:24<1:09:22,  6.07it/s]

 16%|█▋        | 4940/30196 [10:24<1:03:34,  6.62it/s]

 16%|█▋        | 4941/30196 [10:25<1:03:07,  6.67it/s]

 16%|█▋        | 4942/30196 [10:25<1:02:10,  6.77it/s]

 16%|█▋        | 4943/30196 [10:25<57:37,  7.30it/s]

 16%|█▋        | 4945/30196 [10:25<44:32,  9.45it/s]

 16%|█▋        | 4947/30196 [10:25<41:38, 10.11it/s]

 16%|█▋        | 4949/30196 [10:25<47:35,  8.84it/s]

 16%|█▋        | 4950/30196 [10:26<57:27,  7.32it/s]

 16%|█▋        | 4951/30196 [10:26<58:30,  7.19it/s]

 16%|█▋        | 4953/30196 [10:26<53:43,  7.83it/s]

 16%|█▋        | 4955/30196 [10:26<43:17,  9.72it/s]

 16%|█▋        | 4957/30196 [10:26<48:50,  8.61it/s]

 16%|█▋        | 4959/30196 [10:27<45:40,  9.21it/s]

 16%|█▋        | 4960/30196 [10:27<45:44,  9.20it/s]

 16%|█▋        | 4961/30196 [10:27<48:02,  8.75it/s]

 16%|█▋        | 4963/30196 [10:27<45:32,  9.23it/s]

 16%|█▋        | 4965/30196 [10:27<46:54,  8.96it/s]

 16%|█▋        | 4966/30196 [10:27<49:50,  8.44it/s]

 16%|█▋        | 4967/30196 [10:27<48:36,  8.65it/s]

 16%|█▋        | 4969/30196 [10:28<45:23,  9.26it/s]

 16%|█▋        | 4970/30196 [10:28<48:19,  8.70it/s]

 16%|█▋        | 4971/30196 [10:28<50:53,  8.26it/s]

 16%|█▋        | 4972/30196 [10:28<52:43,  7.97it/s]

 16%|█▋        | 4973/30196 [10:28<54:18,  7.74it/s]

 16%|█▋        | 4974/30196 [10:28<51:27,  8.17it/s]

 16%|█▋        | 4975/30196 [10:29<58:00,  7.25it/s]

 16%|█▋        | 4977/30196 [10:29<56:50,  7.39it/s]

 16%|█▋        | 4979/30196 [10:29<53:16,  7.89it/s]

 16%|█▋        | 4981/30196 [10:29<52:40,  7.98it/s]

 17%|█▋        | 4983/30196 [10:29<50:37,  8.30it/s]

 17%|█▋        | 4984/30196 [10:30<51:24,  8.17it/s]

 17%|█▋        | 4985/30196 [10:30<50:19,  8.35it/s]

 17%|█▋        | 4986/30196 [10:30<54:57,  7.64it/s]

 17%|█▋        | 4987/30196 [10:30<1:03:31,  6.61it/s]

 17%|█▋        | 4988/30196 [10:30<59:00,  7.12it/s]

 17%|█▋        | 4989/30196 [10:30<1:06:45,  6.29it/s]

 17%|█▋        | 4990/30196 [10:31<1:12:23,  5.80it/s]

 17%|█▋        | 4991/30196 [10:31<1:12:06,  5.83it/s]

 17%|█▋        | 4993/30196 [10:31<54:43,  7.68it/s]

 17%|█▋        | 4994/30196 [10:31<59:08,  7.10it/s]

 17%|█▋        | 4995/30196 [10:31<58:23,  7.19it/s]

 17%|█▋        | 4997/30196 [10:31<44:30,  9.44it/s]

 17%|█▋        | 4999/30196 [10:32<48:01,  8.74it/s]

 17%|█▋        | 5002/30196 [10:32<35:48, 11.72it/s]

 17%|█▋        | 5004/30196 [10:32<31:33, 13.31it/s]

 17%|█▋        | 5006/30196 [10:32<34:14, 12.26it/s]

 17%|█▋        | 5008/30196 [10:32<35:26, 11.84it/s]

 17%|█▋        | 5010/30196 [10:33<44:33,  9.42it/s]

 17%|█▋        | 5012/30196 [10:33<48:59,  8.57it/s]

 17%|█▋        | 5014/30196 [10:33<45:25,  9.24it/s]

 17%|█▋        | 5017/30196 [10:33<34:56, 12.01it/s]

 17%|█▋        | 5019/30196 [10:33<40:03, 10.48it/s]

 17%|█▋        | 5021/30196 [10:34<42:54,  9.78it/s]

 17%|█▋        | 5023/30196 [10:34<41:49, 10.03it/s]

 17%|█▋        | 5025/30196 [10:34<42:58,  9.76it/s]

 17%|█▋        | 5027/30196 [10:34<48:30,  8.65it/s]

 17%|█▋        | 5029/30196 [10:35<46:19,  9.06it/s]

 17%|█▋        | 5030/30196 [10:35<48:57,  8.57it/s]

 17%|█▋        | 5031/30196 [10:35<50:27,  8.31it/s]

 17%|█▋        | 5032/30196 [10:35<52:59,  7.91it/s]

 17%|█▋        | 5033/30196 [10:35<1:03:36,  6.59it/s]

 17%|█▋        | 5035/30196 [10:36<1:09:55,  6.00it/s]

 17%|█▋        | 5036/30196 [10:36<1:04:35,  6.49it/s]

 17%|█▋        | 5038/30196 [10:36<54:47,  7.65it/s]

 17%|█▋        | 5039/30196 [10:36<55:48,  7.51it/s]

 17%|█▋        | 5041/30196 [10:36<49:23,  8.49it/s]

 17%|█▋        | 5042/30196 [10:36<51:00,  8.22it/s]

 17%|█▋        | 5044/30196 [10:36<40:52, 10.25it/s]

 17%|█▋        | 5046/30196 [10:37<40:25, 10.37it/s]

 17%|█▋        | 5048/30196 [10:37<41:02, 10.21it/s]

 17%|█▋        | 5050/30196 [10:37<37:54, 11.05it/s]

 17%|█▋        | 5052/30196 [10:37<46:21,  9.04it/s]

 17%|█▋        | 5053/30196 [10:37<49:12,  8.52it/s]

 17%|█▋        | 5055/30196 [10:38<51:28,  8.14it/s]

 17%|█▋        | 5056/30196 [10:38<52:25,  7.99it/s]

 17%|█▋        | 5058/30196 [10:38<45:18,  9.25it/s]

 17%|█▋        | 5059/30196 [10:38<48:01,  8.72it/s]

 17%|█▋        | 5060/30196 [10:38<59:00,  7.10it/s]

 17%|█▋        | 5061/30196 [10:39<55:20,  7.57it/s]

 17%|█▋        | 5063/30196 [10:39<47:13,  8.87it/s]

 17%|█▋        | 5064/30196 [10:39<46:53,  8.93it/s]

 17%|█▋        | 5065/30196 [10:39<52:44,  7.94it/s]

 17%|█▋        | 5066/30196 [10:39<58:42,  7.13it/s]

 17%|█▋        | 5067/30196 [10:39<59:07,  7.08it/s]

 17%|█▋        | 5068/30196 [10:39<58:32,  7.15it/s]

 17%|█▋        | 5070/30196 [10:40<50:00,  8.37it/s]

 17%|█▋        | 5072/30196 [10:40<41:23, 10.12it/s]

 17%|█▋        | 5074/30196 [10:40<37:50, 11.06it/s]

 17%|█▋        | 5076/30196 [10:40<49:53,  8.39it/s]

 17%|█▋        | 5077/30196 [10:40<58:16,  7.18it/s]

 17%|█▋        | 5079/30196 [10:41<48:51,  8.57it/s]

 17%|█▋        | 5080/30196 [10:41<1:01:07,  6.85it/s]

 17%|█▋        | 5081/30196 [10:41<1:00:01,  6.97it/s]

 17%|█▋        | 5083/30196 [10:41<54:57,  7.62it/s]

 17%|█▋        | 5084/30196 [10:41<55:48,  7.50it/s]

 17%|█▋        | 5085/30196 [10:42<55:33,  7.53it/s]

 17%|█▋        | 5087/30196 [10:42<44:41,  9.36it/s]

 17%|█▋        | 5088/30196 [10:42<1:00:26,  6.92it/s]

 17%|█▋        | 5090/30196 [10:42<58:39,  7.13it/s]

 17%|█▋        | 5091/30196 [10:42<1:01:22,  6.82it/s]

 17%|█▋        | 5092/30196 [10:42<57:44,  7.25it/s]

 17%|█▋        | 5094/30196 [10:43<45:42,  9.15it/s]

 17%|█▋        | 5096/30196 [10:43<42:36,  9.82it/s]

 17%|█▋        | 5098/30196 [10:43<47:56,  8.72it/s]

 17%|█▋        | 5099/30196 [10:43<49:40,  8.42it/s]

 17%|█▋        | 5100/30196 [10:43<54:40,  7.65it/s]

 17%|█▋        | 5102/30196 [10:44<48:46,  8.57it/s]

 17%|█▋        | 5104/30196 [10:44<45:00,  9.29it/s]

 17%|█▋        | 5105/30196 [10:44<50:29,  8.28it/s]

 17%|█▋        | 5106/30196 [10:44<49:32,  8.44it/s]

 17%|█▋        | 5107/30196 [10:44<1:00:47,  6.88it/s]

 17%|█▋        | 5108/30196 [10:44<59:37,  7.01it/s]

 17%|█▋        | 5109/30196 [10:45<1:12:03,  5.80it/s]

 17%|█▋        | 5110/30196 [10:45<1:07:41,  6.18it/s]

 17%|█▋        | 5111/30196 [10:45<1:08:28,  6.11it/s]

 17%|█▋        | 5113/30196 [10:45<51:55,  8.05it/s]

 17%|█▋        | 5114/30196 [10:45<53:34,  7.80it/s]

 17%|█▋        | 5115/30196 [10:45<55:33,  7.52it/s]

 17%|█▋        | 5116/30196 [10:46<55:41,  7.50it/s]

 17%|█▋        | 5117/30196 [10:46<1:04:15,  6.50it/s]

 17%|█▋        | 5118/30196 [10:46<1:01:58,  6.74it/s]

 17%|█▋        | 5120/30196 [10:46<51:17,  8.15it/s]

 17%|█▋        | 5121/30196 [10:46<53:45,  7.77it/s]

 17%|█▋        | 5123/30196 [10:46<51:49,  8.06it/s]

 17%|█▋        | 5125/30196 [10:47<48:20,  8.64it/s]

 17%|█▋        | 5127/30196 [10:47<49:20,  8.47it/s]

 17%|█▋        | 5129/30196 [10:47<46:52,  8.91it/s]

 17%|█▋        | 5130/30196 [10:47<48:44,  8.57it/s]

 17%|█▋        | 5131/30196 [10:47<53:13,  7.85it/s]

 17%|█▋        | 5132/30196 [10:48<54:32,  7.66it/s]

 17%|█▋        | 5133/30196 [10:48<52:30,  7.96it/s]

 17%|█▋        | 5134/30196 [10:48<1:01:15,  6.82it/s]

 17%|█▋        | 5135/30196 [10:48<1:00:36,  6.89it/s]

 17%|█▋        | 5136/30196 [10:48<55:52,  7.48it/s]

 17%|█▋        | 5137/30196 [10:48<52:19,  7.98it/s]

 17%|█▋        | 5139/30196 [10:48<43:00,  9.71it/s]

 17%|█▋        | 5140/30196 [10:48<46:50,  8.92it/s]

 17%|█▋        | 5142/30196 [10:49<41:00, 10.18it/s]

 17%|█▋        | 5144/30196 [10:49<52:17,  7.98it/s]

 17%|█▋        | 5147/30196 [10:49<46:07,  9.05it/s]

 17%|█▋        | 5148/30196 [10:49<48:45,  8.56it/s]

 17%|█▋        | 5150/30196 [10:49<39:39, 10.52it/s]

 17%|█▋        | 5152/30196 [10:50<43:20,  9.63it/s]

 17%|█▋        | 5154/30196 [10:50<39:45, 10.50it/s]

 17%|█▋        | 5156/30196 [10:50<54:24,  7.67it/s]

 17%|█▋        | 5158/30196 [10:50<45:32,  9.16it/s]

 17%|█▋        | 5160/30196 [10:51<51:41,  8.07it/s]

 17%|█▋        | 5162/30196 [10:51<48:47,  8.55it/s]

 17%|█▋        | 5163/30196 [10:51<50:09,  8.32it/s]

 17%|█▋        | 5164/30196 [10:51<54:15,  7.69it/s]

 17%|█▋        | 5166/30196 [10:51<45:35,  9.15it/s]

 17%|█▋        | 5168/30196 [10:52<45:58,  9.07it/s]

 17%|█▋        | 5169/30196 [10:52<50:28,  8.26it/s]

 17%|█▋        | 5172/30196 [10:52<53:59,  7.73it/s]

 17%|█▋        | 5173/30196 [10:52<1:00:48,  6.86it/s]

 17%|█▋        | 5174/30196 [10:53<59:36,  7.00it/s]

 17%|█▋        | 5175/30196 [10:53<1:02:10,  6.71it/s]

 17%|█▋        | 5177/30196 [10:53<58:47,  7.09it/s]

 17%|█▋        | 5179/30196 [10:53<55:20,  7.53it/s]

 17%|█▋        | 5180/30196 [10:53<55:28,  7.52it/s]

 17%|█▋        | 5181/30196 [10:54<58:32,  7.12it/s]

 17%|█▋        | 5183/30196 [10:54<47:30,  8.77it/s]

 17%|█▋        | 5185/30196 [10:54<40:35, 10.27it/s]

 17%|█▋        | 5187/30196 [10:54<48:19,  8.62it/s]

 17%|█▋        | 5189/30196 [10:54<48:21,  8.62it/s]

 17%|█▋        | 5190/30196 [10:54<50:50,  8.20it/s]

 17%|█▋        | 5192/30196 [10:55<49:38,  8.40it/s]

 17%|█▋        | 5193/30196 [10:55<48:50,  8.53it/s]

 17%|█▋        | 5194/30196 [10:55<47:37,  8.75it/s]

 17%|█▋        | 5195/30196 [10:55<54:05,  7.70it/s]

 17%|█▋        | 5196/30196 [10:55<55:15,  7.54it/s]

 17%|█▋        | 5197/30196 [10:55<58:56,  7.07it/s]

 17%|█▋        | 5199/30196 [10:56<44:30,  9.36it/s]

 17%|█▋        | 5201/30196 [10:56<39:27, 10.56it/s]

 17%|█▋        | 5203/30196 [10:56<40:01, 10.41it/s]

 17%|█▋        | 5205/30196 [10:56<36:53, 11.29it/s]

 17%|█▋        | 5207/30196 [10:56<41:29, 10.04it/s]

 17%|█▋        | 5209/30196 [10:57<49:23,  8.43it/s]

 17%|█▋        | 5211/30196 [10:57<47:19,  8.80it/s]

 17%|█▋        | 5212/30196 [10:57<48:58,  8.50it/s]

 17%|█▋        | 5213/30196 [10:57<53:53,  7.73it/s]

 17%|█▋        | 5214/30196 [10:57<51:30,  8.08it/s]

 17%|█▋        | 5216/30196 [10:57<49:28,  8.41it/s]

 17%|█▋        | 5217/30196 [10:58<54:25,  7.65it/s]

 17%|█▋        | 5219/30196 [10:58<47:38,  8.74it/s]

 17%|█▋        | 5221/30196 [10:58<47:19,  8.80it/s]

 17%|█▋        | 5222/30196 [10:58<56:17,  7.40it/s]

 17%|█▋        | 5223/30196 [10:58<53:58,  7.71it/s]

 17%|█▋        | 5224/30196 [10:58<54:33,  7.63it/s]

 17%|█▋        | 5225/30196 [10:59<1:04:03,  6.50it/s]

 17%|█▋        | 5226/30196 [10:59<58:35,  7.10it/s]

 17%|█▋        | 5227/30196 [10:59<59:15,  7.02it/s]

 17%|█▋        | 5228/30196 [10:59<1:02:07,  6.70it/s]

 17%|█▋        | 5229/30196 [10:59<1:05:04,  6.39it/s]

 17%|█▋        | 5230/30196 [10:59<1:06:55,  6.22it/s]

 17%|█▋        | 5232/30196 [11:00<55:42,  7.47it/s]

 17%|█▋        | 5233/30196 [11:00<59:23,  7.01it/s]

 17%|█▋        | 5234/30196 [11:00<59:53,  6.95it/s]

 17%|█▋        | 5235/30196 [11:00<59:26,  7.00it/s]

 17%|█▋        | 5236/30196 [11:00<55:03,  7.56it/s]

 17%|█▋        | 5237/30196 [11:00<1:04:29,  6.45it/s]

 17%|█▋        | 5238/30196 [11:01<1:02:53,  6.61it/s]

 17%|█▋        | 5240/30196 [11:01<53:29,  7.78it/s]

 17%|█▋        | 5241/30196 [11:01<57:57,  7.18it/s]

 17%|█▋        | 5242/30196 [11:01<1:01:19,  6.78it/s]

 17%|█▋        | 5245/30196 [11:01<40:07, 10.36it/s]

 17%|█▋        | 5247/30196 [11:02<43:40,  9.52it/s]

 17%|█▋        | 5249/30196 [11:02<36:37, 11.35it/s]

 17%|█▋        | 5251/30196 [11:02<43:15,  9.61it/s]

 17%|█▋        | 5253/30196 [11:02<37:29, 11.09it/s]

 17%|█▋        | 5255/30196 [11:02<45:21,  9.16it/s]

 17%|█▋        | 5257/30196 [11:03<1:01:11,  6.79it/s]

 17%|█▋        | 5258/30196 [11:03<58:23,  7.12it/s]

 17%|█▋        | 5259/30196 [11:03<55:21,  7.51it/s]

 17%|█▋        | 5261/30196 [11:03<48:32,  8.56it/s]

 17%|█▋        | 5262/30196 [11:03<1:00:03,  6.92it/s]

 17%|█▋        | 5264/30196 [11:04<58:03,  7.16it/s]

 17%|█▋        | 5266/30196 [11:04<50:51,  8.17it/s]

 17%|█▋        | 5267/30196 [11:04<49:20,  8.42it/s]

 17%|█▋        | 5268/30196 [11:04<48:03,  8.64it/s]

 17%|█▋        | 5270/30196 [11:04<41:22, 10.04it/s]

 17%|█▋        | 5272/30196 [11:04<39:42, 10.46it/s]

 17%|█▋        | 5274/30196 [11:05<44:54,  9.25it/s]

 17%|█▋        | 5275/30196 [11:05<49:53,  8.32it/s]

 17%|█▋        | 5277/30196 [11:05<49:40,  8.36it/s]

 17%|█▋        | 5279/30196 [11:05<45:24,  9.14it/s]

 17%|█▋        | 5280/30196 [11:05<50:11,  8.27it/s]

 17%|█▋        | 5282/30196 [11:06<47:42,  8.70it/s]

 17%|█▋        | 5283/30196 [11:06<48:59,  8.47it/s]

 18%|█▊        | 5285/30196 [11:06<47:53,  8.67it/s]

 18%|█▊        | 5286/30196 [11:06<46:59,  8.83it/s]

 18%|█▊        | 5288/30196 [11:06<42:59,  9.66it/s]

 18%|█▊        | 5289/30196 [11:06<48:45,  8.51it/s]

 18%|█▊        | 5291/30196 [11:07<45:58,  9.03it/s]

 18%|█▊        | 5292/30196 [11:07<1:03:54,  6.50it/s]

 18%|█▊        | 5293/30196 [11:07<1:10:45,  5.87it/s]

 18%|█▊        | 5294/30196 [11:07<1:04:33,  6.43it/s]

 18%|█▊        | 5296/30196 [11:07<52:50,  7.85it/s]

 18%|█▊        | 5298/30196 [11:08<43:11,  9.61it/s]

 18%|█▊        | 5300/30196 [11:08<46:41,  8.89it/s]

 18%|█▊        | 5302/30196 [11:08<54:22,  7.63it/s]

 18%|█▊        | 5303/30196 [11:08<55:40,  7.45it/s]

 18%|█▊        | 5304/30196 [11:09<1:31:06,  4.55it/s]

 18%|█▊        | 5305/30196 [11:09<1:20:29,  5.15it/s]

 18%|█▊        | 5307/30196 [11:09<1:03:51,  6.50it/s]

 18%|█▊        | 5308/30196 [11:09<1:08:52,  6.02it/s]

 18%|█▊        | 5309/30196 [11:10<1:05:50,  6.30it/s]

 18%|█▊        | 5310/30196 [11:10<1:04:25,  6.44it/s]

 18%|█▊        | 5311/30196 [11:10<1:02:53,  6.59it/s]

 18%|█▊        | 5313/30196 [11:10<53:10,  7.80it/s]

 18%|█▊        | 5314/30196 [11:10<52:22,  7.92it/s]

 18%|█▊        | 5316/30196 [11:10<56:46,  7.30it/s]

 18%|█▊        | 5317/30196 [11:11<54:20,  7.63it/s]

 18%|█▊        | 5318/30196 [11:11<1:02:17,  6.66it/s]

 18%|█▊        | 5320/30196 [11:11<48:03,  8.63it/s]

 18%|█▊        | 5322/30196 [11:11<41:57,  9.88it/s]

 18%|█▊        | 5324/30196 [11:11<50:02,  8.28it/s]

 18%|█▊        | 5325/30196 [11:11<50:51,  8.15it/s]

 18%|█▊        | 5326/30196 [11:12<51:58,  7.98it/s]

 18%|█▊        | 5328/30196 [11:12<53:45,  7.71it/s]

 18%|█▊        | 5329/30196 [11:12<55:17,  7.50it/s]

 18%|█▊        | 5331/30196 [11:12<45:56,  9.02it/s]

 18%|█▊        | 5333/30196 [11:12<48:30,  8.54it/s]

 18%|█▊        | 5334/30196 [11:13<52:54,  7.83it/s]

 18%|█▊        | 5335/30196 [11:13<51:18,  8.08it/s]

 18%|█▊        | 5336/30196 [11:13<55:48,  7.43it/s]

 18%|█▊        | 5337/30196 [11:13<57:09,  7.25it/s]

 18%|█▊        | 5338/30196 [11:13<1:00:34,  6.84it/s]

 18%|█▊        | 5340/30196 [11:13<54:15,  7.64it/s]

 18%|█▊        | 5342/30196 [11:14<53:17,  7.77it/s]

 18%|█▊        | 5343/30196 [11:14<53:29,  7.74it/s]

 18%|█▊        | 5344/30196 [11:14<1:07:16,  6.16it/s]

 18%|█▊        | 5345/30196 [11:14<1:12:44,  5.69it/s]

 18%|█▊        | 5347/30196 [11:14<56:19,  7.35it/s]

 18%|█▊        | 5348/30196 [11:15<59:11,  7.00it/s]

 18%|█▊        | 5349/30196 [11:15<55:14,  7.50it/s]

 18%|█▊        | 5351/30196 [11:15<46:21,  8.93it/s]

 18%|█▊        | 5352/30196 [11:15<1:06:29,  6.23it/s]

 18%|█▊        | 5353/30196 [11:15<1:01:20,  6.75it/s]

 18%|█▊        | 5354/30196 [11:15<1:01:21,  6.75it/s]

 18%|█▊        | 5355/30196 [11:16<59:55,  6.91it/s]

 18%|█▊        | 5356/30196 [11:16<58:16,  7.10it/s]

 18%|█▊        | 5357/30196 [11:16<58:26,  7.08it/s]

 18%|█▊        | 5359/30196 [11:16<53:09,  7.79it/s]

 18%|█▊        | 5360/30196 [11:16<1:01:33,  6.72it/s]

 18%|█▊        | 5361/30196 [11:16<1:04:56,  6.37it/s]

 18%|█▊        | 5363/30196 [11:17<50:43,  8.16it/s]

 18%|█▊        | 5364/30196 [11:17<51:55,  7.97it/s]

 18%|█▊        | 5366/30196 [11:17<49:25,  8.37it/s]

 18%|█▊        | 5368/30196 [11:17<42:17,  9.79it/s]

 18%|█▊        | 5370/30196 [11:18<55:20,  7.48it/s]

 18%|█▊        | 5371/30196 [11:18<53:25,  7.75it/s]

 18%|█▊        | 5372/30196 [11:18<51:31,  8.03it/s]

 18%|█▊        | 5373/30196 [11:18<52:36,  7.86it/s]

 18%|█▊        | 5374/30196 [11:18<52:51,  7.83it/s]

 18%|█▊        | 5375/30196 [11:18<1:01:39,  6.71it/s]

 18%|█▊        | 5376/30196 [11:18<56:36,  7.31it/s]

 18%|█▊        | 5377/30196 [11:19<1:08:44,  6.02it/s]

 18%|█▊        | 5379/30196 [11:19<55:10,  7.50it/s]

 18%|█▊        | 5380/30196 [11:19<55:13,  7.49it/s]

 18%|█▊        | 5381/30196 [11:19<58:33,  7.06it/s]

 18%|█▊        | 5383/30196 [11:19<52:33,  7.87it/s]

 18%|█▊        | 5385/30196 [11:19<43:18,  9.55it/s]

 18%|█▊        | 5386/30196 [11:20<45:52,  9.01it/s]

 18%|█▊        | 5387/30196 [11:20<49:19,  8.38it/s]

 18%|█▊        | 5389/30196 [11:20<44:31,  9.29it/s]

 18%|█▊        | 5390/30196 [11:20<47:19,  8.74it/s]

 18%|█▊        | 5391/30196 [11:20<49:59,  8.27it/s]

 18%|█▊        | 5392/30196 [11:20<1:10:08,  5.89it/s]

 18%|█▊        | 5394/30196 [11:21<1:01:54,  6.68it/s]

 18%|█▊        | 5395/30196 [11:21<1:07:17,  6.14it/s]

 18%|█▊        | 5396/30196 [11:21<1:09:03,  5.98it/s]

 18%|█▊        | 5397/30196 [11:21<1:18:14,  5.28it/s]

 18%|█▊        | 5399/30196 [11:22<1:07:22,  6.13it/s]

 18%|█▊        | 5400/30196 [11:22<1:08:10,  6.06it/s]

 18%|█▊        | 5401/30196 [11:22<1:04:39,  6.39it/s]

 18%|█▊        | 5403/30196 [11:22<53:47,  7.68it/s]

 18%|█▊        | 5405/30196 [11:22<42:00,  9.84it/s]

 18%|█▊        | 5407/30196 [11:22<38:39, 10.69it/s]

 18%|█▊        | 5409/30196 [11:23<40:13, 10.27it/s]

 18%|█▊        | 5411/30196 [11:23<46:22,  8.91it/s]

 18%|█▊        | 5413/30196 [11:23<48:42,  8.48it/s]

 18%|█▊        | 5415/30196 [11:23<44:10,  9.35it/s]

 18%|█▊        | 5417/30196 [11:24<48:21,  8.54it/s]

 18%|█▊        | 5419/30196 [11:24<46:56,  8.80it/s]

 18%|█▊        | 5420/30196 [11:25<1:34:20,  4.38it/s]

 18%|█▊        | 5422/30196 [11:25<1:09:28,  5.94it/s]

 18%|█▊        | 5424/30196 [11:25<55:48,  7.40it/s]

 18%|█▊        | 5426/30196 [11:25<56:37,  7.29it/s]

 18%|█▊        | 5428/30196 [11:25<54:18,  7.60it/s]

 18%|█▊        | 5429/30196 [11:25<52:12,  7.91it/s]

 18%|█▊        | 5431/30196 [11:26<45:14,  9.12it/s]

 18%|█▊        | 5433/30196 [11:26<42:30,  9.71it/s]

 18%|█▊        | 5435/30196 [11:26<46:47,  8.82it/s]

 18%|█▊        | 5436/30196 [11:26<46:29,  8.87it/s]

 18%|█▊        | 5437/30196 [11:26<52:25,  7.87it/s]

 18%|█▊        | 5438/30196 [11:26<50:51,  8.11it/s]

 18%|█▊        | 5439/30196 [11:27<53:25,  7.72it/s]

 18%|█▊        | 5440/30196 [11:27<54:06,  7.63it/s]

 18%|█▊        | 5442/30196 [11:27<40:09, 10.27it/s]

 18%|█▊        | 5444/30196 [11:27<49:20,  8.36it/s]

 18%|█▊        | 5445/30196 [11:27<48:26,  8.51it/s]

 18%|█▊        | 5446/30196 [11:27<55:46,  7.40it/s]

 18%|█▊        | 5447/30196 [11:28<55:23,  7.45it/s]

 18%|█▊        | 5449/30196 [11:28<41:35,  9.92it/s]

 18%|█▊        | 5451/30196 [11:28<42:51,  9.62it/s]

 18%|█▊        | 5453/30196 [11:28<45:07,  9.14it/s]

 18%|█▊        | 5454/30196 [11:28<50:42,  8.13it/s]

 18%|█▊        | 5456/30196 [11:28<41:06, 10.03it/s]

 18%|█▊        | 5458/30196 [11:29<39:37, 10.41it/s]

 18%|█▊        | 5460/30196 [11:29<43:17,  9.52it/s]

 18%|█▊        | 5462/30196 [11:29<46:17,  8.91it/s]

 18%|█▊        | 5463/30196 [11:29<47:46,  8.63it/s]

 18%|█▊        | 5465/30196 [11:29<42:01,  9.81it/s]

 18%|█▊        | 5468/30196 [11:30<37:03, 11.12it/s]

 18%|█▊        | 5470/30196 [11:30<41:14,  9.99it/s]

 18%|█▊        | 5472/30196 [11:30<37:17, 11.05it/s]

 18%|█▊        | 5474/30196 [11:30<43:15,  9.53it/s]

 18%|█▊        | 5476/30196 [11:30<43:58,  9.37it/s]

 18%|█▊        | 5478/30196 [11:31<47:48,  8.62it/s]

 18%|█▊        | 5479/30196 [11:31<50:17,  8.19it/s]

 18%|█▊        | 5480/30196 [11:31<52:34,  7.83it/s]

 18%|█▊        | 5482/30196 [11:31<41:30,  9.92it/s]

 18%|█▊        | 5484/30196 [11:31<40:26, 10.18it/s]

 18%|█▊        | 5486/30196 [11:32<40:22, 10.20it/s]

 18%|█▊        | 5488/30196 [11:32<48:34,  8.48it/s]

 18%|█▊        | 5489/30196 [11:32<47:32,  8.66it/s]

 18%|█▊        | 5490/30196 [11:32<49:16,  8.36it/s]

 18%|█▊        | 5492/30196 [11:32<41:09, 10.00it/s]

 18%|█▊        | 5494/30196 [11:32<44:30,  9.25it/s]

 18%|█▊        | 5495/30196 [11:33<57:54,  7.11it/s]

 18%|█▊        | 5496/30196 [11:33<1:00:09,  6.84it/s]

 18%|█▊        | 5498/30196 [11:33<1:13:41,  5.59it/s]

 18%|█▊        | 5499/30196 [11:33<1:07:46,  6.07it/s]

 18%|█▊        | 5500/30196 [11:34<1:12:40,  5.66it/s]

 18%|█▊        | 5502/30196 [11:34<1:06:11,  6.22it/s]

 18%|█▊        | 5504/30196 [11:34<56:19,  7.31it/s]

 18%|█▊        | 5505/30196 [11:34<53:45,  7.66it/s]

 18%|█▊        | 5507/30196 [11:34<45:23,  9.06it/s]

 18%|█▊        | 5508/30196 [11:35<47:21,  8.69it/s]

 18%|█▊        | 5509/30196 [11:35<49:51,  8.25it/s]

 18%|█▊        | 5510/30196 [11:35<51:20,  8.01it/s]

 18%|█▊        | 5511/30196 [11:35<52:06,  7.89it/s]

 18%|█▊        | 5512/30196 [11:35<58:02,  7.09it/s]

 18%|█▊        | 5513/30196 [11:35<56:39,  7.26it/s]

 18%|█▊        | 5514/30196 [11:36<1:11:27,  5.76it/s]

 18%|█▊        | 5515/30196 [11:36<1:08:14,  6.03it/s]

 18%|█▊        | 5516/30196 [11:36<1:14:34,  5.52it/s]

 18%|█▊        | 5517/30196 [11:36<1:05:59,  6.23it/s]

 18%|█▊        | 5519/30196 [11:36<53:19,  7.71it/s]

 18%|█▊        | 5521/30196 [11:36<42:13,  9.74it/s]

 18%|█▊        | 5523/30196 [11:37<43:40,  9.42it/s]

 18%|█▊        | 5525/30196 [11:37<1:35:05,  4.32it/s]

 18%|█▊        | 5526/30196 [11:38<1:27:28,  4.70it/s]

 18%|█▊        | 5528/30196 [11:38<1:06:50,  6.15it/s]

 18%|█▊        | 5530/30196 [11:38<53:51,  7.63it/s]

 18%|█▊        | 5532/30196 [11:38<51:56,  7.92it/s]

 18%|█▊        | 5534/30196 [11:38<55:54,  7.35it/s]

 18%|█▊        | 5535/30196 [11:39<55:28,  7.41it/s]

 18%|█▊        | 5537/30196 [11:39<45:44,  8.99it/s]

 18%|█▊        | 5539/30196 [11:39<47:14,  8.70it/s]

 18%|█▊        | 5540/30196 [11:39<49:50,  8.24it/s]

 18%|█▊        | 5541/30196 [11:39<51:18,  8.01it/s]

 18%|█▊        | 5542/30196 [11:39<49:24,  8.32it/s]

 18%|█▊        | 5543/30196 [11:39<51:02,  8.05it/s]

 18%|█▊        | 5544/30196 [11:40<52:50,  7.78it/s]

 18%|█▊        | 5545/30196 [11:40<50:10,  8.19it/s]

 18%|█▊        | 5546/30196 [11:40<59:44,  6.88it/s]

 18%|█▊        | 5547/30196 [11:40<55:32,  7.40it/s]

 18%|█▊        | 5548/30196 [11:40<51:52,  7.92it/s]

 18%|█▊        | 5549/30196 [11:40<49:51,  8.24it/s]

 18%|█▊        | 5551/30196 [11:40<43:23,  9.47it/s]

 18%|█▊        | 5553/30196 [11:41<1:16:09,  5.39it/s]

 18%|█▊        | 5554/30196 [11:41<1:15:44,  5.42it/s]

 18%|█▊        | 5555/30196 [11:41<1:14:46,  5.49it/s]

 18%|█▊        | 5556/30196 [11:42<1:24:19,  4.87it/s]

 18%|█▊        | 5557/30196 [11:42<1:44:24,  3.93it/s]

 18%|█▊        | 5558/30196 [11:42<1:31:38,  4.48it/s]

 18%|█▊        | 5559/30196 [11:42<1:21:29,  5.04it/s]

 18%|█▊        | 5561/30196 [11:43<1:01:41,  6.65it/s]

 18%|█▊        | 5563/30196 [11:43<48:38,  8.44it/s]

 18%|█▊        | 5564/30196 [11:43<49:45,  8.25it/s]

 18%|█▊        | 5565/30196 [11:43<52:19,  7.84it/s]

 18%|█▊        | 5566/30196 [11:43<1:00:28,  6.79it/s]

 18%|█▊        | 5567/30196 [11:43<56:24,  7.28it/s]

 18%|█▊        | 5569/30196 [11:43<43:38,  9.41it/s]

 18%|█▊        | 5571/30196 [11:44<41:07,  9.98it/s]

 18%|█▊        | 5573/30196 [11:44<58:21,  7.03it/s]

 18%|█▊        | 5574/30196 [11:44<58:17,  7.04it/s]

 18%|█▊        | 5575/30196 [11:44<1:05:35,  6.26it/s]

 18%|█▊        | 5576/30196 [11:44<1:02:54,  6.52it/s]

 18%|█▊        | 5577/30196 [11:45<1:05:38,  6.25it/s]

 18%|█▊        | 5579/30196 [11:45<51:58,  7.89it/s]

 18%|█▊        | 5580/30196 [11:45<55:59,  7.33it/s]

 18%|█▊        | 5582/30196 [11:45<52:58,  7.74it/s]

 18%|█▊        | 5583/30196 [11:45<51:25,  7.98it/s]

 18%|█▊        | 5584/30196 [11:45<49:27,  8.29it/s]

 18%|█▊        | 5586/30196 [11:46<49:31,  8.28it/s]

 19%|█▊        | 5587/30196 [11:46<48:29,  8.46it/s]

 19%|█▊        | 5588/30196 [11:46<53:48,  7.62it/s]

 19%|█▊        | 5590/30196 [11:46<51:59,  7.89it/s]

 19%|█▊        | 5591/30196 [11:46<56:17,  7.28it/s]

 19%|█▊        | 5593/30196 [11:47<1:06:59,  6.12it/s]

 19%|█▊        | 5596/30196 [11:47<49:08,  8.34it/s]

 19%|█▊        | 5597/30196 [11:47<50:17,  8.15it/s]

 19%|█▊        | 5598/30196 [11:47<57:50,  7.09it/s]

 19%|█▊        | 5600/30196 [11:47<46:46,  8.76it/s]

 19%|█▊        | 5602/30196 [11:48<48:05,  8.52it/s]

 19%|█▊        | 5603/30196 [11:48<49:08,  8.34it/s]

 19%|█▊        | 5605/30196 [11:48<46:52,  8.74it/s]

 19%|█▊        | 5607/30196 [11:48<54:21,  7.54it/s]

 19%|█▊        | 5608/30196 [11:49<54:27,  7.52it/s]

 19%|█▊        | 5609/30196 [11:49<55:46,  7.35it/s]

 19%|█▊        | 5611/30196 [11:49<49:45,  8.24it/s]

 19%|█▊        | 5612/30196 [11:49<50:35,  8.10it/s]

 19%|█▊        | 5613/30196 [11:49<52:13,  7.85it/s]

 19%|█▊        | 5614/30196 [11:49<50:23,  8.13it/s]

 19%|█▊        | 5616/30196 [11:50<50:16,  8.15it/s]

 19%|█▊        | 5617/30196 [11:50<49:07,  8.34it/s]

 19%|█▊        | 5619/30196 [11:50<45:23,  9.02it/s]

 19%|█▊        | 5621/30196 [11:50<38:23, 10.67it/s]

 19%|█▊        | 5623/30196 [11:50<33:26, 12.24it/s]

 19%|█▊        | 5625/30196 [11:50<44:57,  9.11it/s]

 19%|█▊        | 5627/30196 [11:51<43:31,  9.41it/s]

 19%|█▊        | 5629/30196 [11:51<46:14,  8.85it/s]

 19%|█▊        | 5630/30196 [11:51<45:41,  8.96it/s]

 19%|█▊        | 5631/30196 [11:51<45:04,  9.08it/s]

 19%|█▊        | 5632/30196 [11:51<54:38,  7.49it/s]

 19%|█▊        | 5633/30196 [11:51<55:23,  7.39it/s]

 19%|█▊        | 5634/30196 [11:52<1:42:37,  3.99it/s]

 19%|█▊        | 5635/30196 [11:52<1:29:52,  4.55it/s]

 19%|█▊        | 5636/30196 [11:52<1:20:57,  5.06it/s]

 19%|█▊        | 5638/30196 [11:52<56:07,  7.29it/s]

 19%|█▊        | 5640/30196 [11:53<50:16,  8.14it/s]

 19%|█▊        | 5642/30196 [11:53<48:57,  8.36it/s]

 19%|█▊        | 5644/30196 [11:53<42:54,  9.54it/s]

 19%|█▊        | 5646/30196 [11:53<38:36, 10.60it/s]

 19%|█▊        | 5648/30196 [11:53<40:51, 10.01it/s]

 19%|█▊        | 5651/30196 [11:54<35:33, 11.50it/s]

 19%|█▊        | 5653/30196 [11:54<37:11, 11.00it/s]

 19%|█▊        | 5655/30196 [11:54<42:44,  9.57it/s]

 19%|█▊        | 5657/30196 [11:54<48:59,  8.35it/s]

 19%|█▊        | 5658/30196 [11:54<50:03,  8.17it/s]

 19%|█▊        | 5659/30196 [11:55<50:45,  8.06it/s]

 19%|█▊        | 5661/30196 [11:55<45:36,  8.97it/s]

 19%|█▉        | 5662/30196 [11:55<45:04,  9.07it/s]

 19%|█▉        | 5663/30196 [11:55<45:04,  9.07it/s]

 19%|█▉        | 5665/30196 [11:55<40:45, 10.03it/s]

 19%|█▉        | 5667/30196 [11:55<47:53,  8.54it/s]

 19%|█▉        | 5669/30196 [11:56<46:47,  8.74it/s]

 19%|█▉        | 5670/30196 [11:56<50:45,  8.05it/s]

 19%|█▉        | 5671/30196 [11:56<51:44,  7.90it/s]

 19%|█▉        | 5672/30196 [11:56<55:48,  7.32it/s]

 19%|█▉        | 5674/30196 [11:56<47:44,  8.56it/s]

 19%|█▉        | 5675/30196 [11:56<49:01,  8.34it/s]

 19%|█▉        | 5677/30196 [11:57<45:43,  8.94it/s]

 19%|█▉        | 5679/30196 [11:57<45:47,  8.92it/s]

 19%|█▉        | 5680/30196 [11:57<54:45,  7.46it/s]

 19%|█▉        | 5681/30196 [11:57<59:05,  6.91it/s]

 19%|█▉        | 5682/30196 [11:57<1:05:05,  6.28it/s]

 19%|█▉        | 5684/30196 [11:58<56:57,  7.17it/s]

 19%|█▉        | 5685/30196 [11:58<56:50,  7.19it/s]

 19%|█▉        | 5686/30196 [11:58<53:20,  7.66it/s]

 19%|█▉        | 5687/30196 [11:58<1:03:55,  6.39it/s]

 19%|█▉        | 5689/30196 [11:58<47:02,  8.68it/s]

 19%|█▉        | 5690/30196 [11:58<46:34,  8.77it/s]

 19%|█▉        | 5691/30196 [11:59<45:41,  8.94it/s]

 19%|█▉        | 5692/30196 [11:59<48:08,  8.48it/s]

 19%|█▉        | 5694/30196 [11:59<42:23,  9.63it/s]

 19%|█▉        | 5695/30196 [11:59<44:55,  9.09it/s]

 19%|█▉        | 5697/30196 [11:59<51:41,  7.90it/s]

 19%|█▉        | 5698/30196 [11:59<53:02,  7.70it/s]

 19%|█▉        | 5699/30196 [12:00<51:03,  8.00it/s]

 19%|█▉        | 5701/30196 [12:00<44:55,  9.09it/s]

 19%|█▉        | 5702/30196 [12:00<44:31,  9.17it/s]

 19%|█▉        | 5703/30196 [12:00<1:05:37,  6.22it/s]

 19%|█▉        | 5704/30196 [12:00<1:06:59,  6.09it/s]

 19%|█▉        | 5705/30196 [12:00<1:00:18,  6.77it/s]

 19%|█▉        | 5706/30196 [12:01<1:00:21,  6.76it/s]

 19%|█▉        | 5708/30196 [12:01<45:42,  8.93it/s]

 19%|█▉        | 5710/30196 [12:01<41:25,  9.85it/s]

 19%|█▉        | 5712/30196 [12:01<55:23,  7.37it/s]

 19%|█▉        | 5713/30196 [12:01<57:56,  7.04it/s]

 19%|█▉        | 5715/30196 [12:02<47:37,  8.57it/s]

 19%|█▉        | 5716/30196 [12:02<50:09,  8.13it/s]

 19%|█▉        | 5717/30196 [12:02<48:49,  8.36it/s]

 19%|█▉        | 5719/30196 [12:02<38:13, 10.67it/s]

 19%|█▉        | 5721/30196 [12:03<1:18:46,  5.18it/s]

 19%|█▉        | 5723/30196 [12:03<1:07:25,  6.05it/s]

 19%|█▉        | 5725/30196 [12:03<1:06:02,  6.18it/s]

 19%|█▉        | 5726/30196 [12:03<1:03:57,  6.38it/s]

 19%|█▉        | 5728/30196 [12:03<52:21,  7.79it/s]

 19%|█▉        | 5730/30196 [12:04<43:54,  9.29it/s]

 19%|█▉        | 5732/30196 [12:04<45:12,  9.02it/s]

 19%|█▉        | 5734/30196 [12:04<48:19,  8.44it/s]

 19%|█▉        | 5735/30196 [12:04<49:18,  8.27it/s]

 19%|█▉        | 5736/30196 [12:04<49:59,  8.15it/s]

 19%|█▉        | 5738/30196 [12:05<41:41,  9.78it/s]

 19%|█▉        | 5740/30196 [12:05<38:04, 10.70it/s]

 19%|█▉        | 5742/30196 [12:05<33:37, 12.12it/s]

 19%|█▉        | 5744/30196 [12:05<48:00,  8.49it/s]

 19%|█▉        | 5746/30196 [12:06<58:54,  6.92it/s]

 19%|█▉        | 5747/30196 [12:06<56:08,  7.26it/s]

 19%|█▉        | 5748/30196 [12:06<56:58,  7.15it/s]

 19%|█▉        | 5749/30196 [12:06<54:10,  7.52it/s]

 19%|█▉        | 5751/30196 [12:06<47:42,  8.54it/s]

 19%|█▉        | 5752/30196 [12:06<49:22,  8.25it/s]

 19%|█▉        | 5753/30196 [12:06<47:45,  8.53it/s]

 19%|█▉        | 5754/30196 [12:07<54:23,  7.49it/s]

 19%|█▉        | 5755/30196 [12:07<57:56,  7.03it/s]

 19%|█▉        | 5756/30196 [12:07<53:41,  7.59it/s]

 19%|█▉        | 5757/30196 [12:07<54:37,  7.46it/s]

 19%|█▉        | 5759/30196 [12:07<42:35,  9.56it/s]

 19%|█▉        | 5760/30196 [12:07<46:15,  8.80it/s]

 19%|█▉        | 5762/30196 [12:07<45:56,  8.87it/s]

 19%|█▉        | 5764/30196 [12:08<37:21, 10.90it/s]

 19%|█▉        | 5766/30196 [12:08<38:11, 10.66it/s]

 19%|█▉        | 5768/30196 [12:08<41:43,  9.76it/s]

 19%|█▉        | 5770/30196 [12:08<47:06,  8.64it/s]

 19%|█▉        | 5771/30196 [12:08<50:58,  7.99it/s]

 19%|█▉        | 5772/30196 [12:09<54:26,  7.48it/s]

 19%|█▉        | 5773/30196 [12:09<55:13,  7.37it/s]

 19%|█▉        | 5775/30196 [12:09<49:06,  8.29it/s]

 19%|█▉        | 5776/30196 [12:09<51:40,  7.88it/s]

 19%|█▉        | 5777/30196 [12:09<49:49,  8.17it/s]

 19%|█▉        | 5778/30196 [12:09<51:13,  7.94it/s]

 19%|█▉        | 5779/30196 [12:09<52:48,  7.71it/s]

 19%|█▉        | 5781/30196 [12:10<43:30,  9.35it/s]

 19%|█▉        | 5783/30196 [12:10<40:43,  9.99it/s]

 19%|█▉        | 5784/30196 [12:10<41:26,  9.82it/s]

 19%|█▉        | 5786/30196 [12:10<33:43, 12.06it/s]

 19%|█▉        | 5788/30196 [12:10<43:05,  9.44it/s]

 19%|█▉        | 5790/30196 [12:11<52:03,  7.81it/s]

 19%|█▉        | 5791/30196 [12:11<53:31,  7.60it/s]

 19%|█▉        | 5793/30196 [12:11<49:10,  8.27it/s]

 19%|█▉        | 5794/30196 [12:11<47:54,  8.49it/s]

 19%|█▉        | 5796/30196 [12:11<47:06,  8.63it/s]

 19%|█▉        | 5797/30196 [12:12<52:26,  7.75it/s]

 19%|█▉        | 5798/30196 [12:12<56:36,  7.18it/s]

 19%|█▉        | 5800/30196 [12:12<1:02:06,  6.55it/s]

 19%|█▉        | 5801/30196 [12:12<1:04:21,  6.32it/s]

 19%|█▉        | 5802/30196 [12:12<1:01:46,  6.58it/s]

 19%|█▉        | 5804/30196 [12:12<47:33,  8.55it/s]

 19%|█▉        | 5805/30196 [12:13<52:21,  7.76it/s]

 19%|█▉        | 5806/30196 [12:13<56:18,  7.22it/s]

 19%|█▉        | 5808/30196 [12:13<44:43,  9.09it/s]

 19%|█▉        | 5810/30196 [12:13<41:57,  9.69it/s]

 19%|█▉        | 5812/30196 [12:13<40:37, 10.00it/s]

 19%|█▉        | 5814/30196 [12:14<45:39,  8.90it/s]

 19%|█▉        | 5815/30196 [12:14<45:27,  8.94it/s]

 19%|█▉        | 5817/30196 [12:14<41:05,  9.89it/s]

 19%|█▉        | 5819/30196 [12:14<43:40,  9.30it/s]

 19%|█▉        | 5820/30196 [12:14<46:04,  8.82it/s]

 19%|█▉        | 5821/30196 [12:14<49:07,  8.27it/s]

 19%|█▉        | 5822/30196 [12:15<58:57,  6.89it/s]

 19%|█▉        | 5824/30196 [12:15<55:24,  7.33it/s]

 19%|█▉        | 5825/30196 [12:15<53:03,  7.66it/s]

 19%|█▉        | 5826/30196 [12:15<57:30,  7.06it/s]

 19%|█▉        | 5827/30196 [12:15<56:27,  7.19it/s]

 19%|█▉        | 5829/30196 [12:15<44:48,  9.06it/s]

 19%|█▉        | 5830/30196 [12:16<43:56,  9.24it/s]

 19%|█▉        | 5832/30196 [12:16<40:37, 10.00it/s]

 19%|█▉        | 5834/30196 [12:16<49:05,  8.27it/s]

 19%|█▉        | 5836/30196 [12:16<42:24,  9.57it/s]

 19%|█▉        | 5838/30196 [12:17<53:34,  7.58it/s]

 19%|█▉        | 5839/30196 [12:17<1:00:32,  6.71it/s]

 19%|█▉        | 5840/30196 [12:17<1:00:18,  6.73it/s]

 19%|█▉        | 5842/30196 [12:17<52:16,  7.76it/s]

 19%|█▉        | 5844/30196 [12:17<49:35,  8.18it/s]

 19%|█▉        | 5845/30196 [12:17<50:36,  8.02it/s]

 19%|█▉        | 5846/30196 [12:18<58:31,  6.93it/s]

 19%|█▉        | 5848/30196 [12:18<52:45,  7.69it/s]

 19%|█▉        | 5849/30196 [12:18<52:47,  7.69it/s]

 19%|█▉        | 5850/30196 [12:18<56:08,  7.23it/s]

 19%|█▉        | 5852/30196 [12:18<46:56,  8.64it/s]

 19%|█▉        | 5854/30196 [12:19<44:01,  9.22it/s]

 19%|█▉        | 5856/30196 [12:19<47:04,  8.62it/s]

 19%|█▉        | 5857/30196 [12:19<49:01,  8.27it/s]

 19%|█▉        | 5859/30196 [12:19<38:54, 10.43it/s]

 19%|█▉        | 5861/30196 [12:19<43:56,  9.23it/s]

 19%|█▉        | 5863/30196 [12:20<43:13,  9.38it/s]

 19%|█▉        | 5865/30196 [12:20<38:50, 10.44it/s]

 19%|█▉        | 5867/30196 [12:20<40:39,  9.97it/s]

 19%|█▉        | 5869/30196 [12:20<45:35,  8.89it/s]

 19%|█▉        | 5871/30196 [12:20<42:16,  9.59it/s]

 19%|█▉        | 5873/30196 [12:21<43:13,  9.38it/s]

 19%|█▉        | 5876/30196 [12:21<35:15, 11.50it/s]

 19%|█▉        | 5878/30196 [12:21<41:31,  9.76it/s]

 19%|█▉        | 5880/30196 [12:21<45:07,  8.98it/s]

 19%|█▉        | 5881/30196 [12:21<49:41,  8.16it/s]

 19%|█▉        | 5883/30196 [12:22<42:25,  9.55it/s]

 19%|█▉        | 5885/30196 [12:22<43:07,  9.39it/s]

 19%|█▉        | 5886/30196 [12:22<49:32,  8.18it/s]

 19%|█▉        | 5887/30196 [12:22<50:35,  8.01it/s]

 20%|█▉        | 5889/30196 [12:22<49:51,  8.13it/s]

 20%|█▉        | 5890/30196 [12:23<56:54,  7.12it/s]

 20%|█▉        | 5891/30196 [12:23<57:31,  7.04it/s]

 20%|█▉        | 5893/30196 [12:23<55:05,  7.35it/s]

 20%|█▉        | 5894/30196 [12:23<1:01:29,  6.59it/s]

 20%|█▉        | 5895/30196 [12:24<1:37:13,  4.17it/s]

 20%|█▉        | 5896/30196 [12:24<1:39:07,  4.09it/s]

 20%|█▉        | 5897/30196 [12:24<1:37:16,  4.16it/s]

 20%|█▉        | 5898/30196 [12:24<1:22:06,  4.93it/s]

 20%|█▉        | 5900/30196 [12:25<1:08:09,  5.94it/s]

 20%|█▉        | 5901/30196 [12:25<1:21:08,  4.99it/s]

 20%|█▉        | 5902/30196 [12:25<1:18:00,  5.19it/s]

 20%|█▉        | 5903/30196 [12:25<1:16:16,  5.31it/s]

 20%|█▉        | 5905/30196 [12:25<57:20,  7.06it/s]

 20%|█▉        | 5907/30196 [12:26<45:58,  8.80it/s]

 20%|█▉        | 5909/30196 [12:26<49:17,  8.21it/s]

 20%|█▉        | 5911/30196 [12:26<50:59,  7.94it/s]

 20%|█▉        | 5913/30196 [12:26<45:59,  8.80it/s]

 20%|█▉        | 5914/30196 [12:26<48:30,  8.34it/s]

 20%|█▉        | 5916/30196 [12:27<45:30,  8.89it/s]

 20%|█▉        | 5918/30196 [12:27<38:57, 10.39it/s]

 20%|█▉        | 5921/30196 [12:27<42:28,  9.52it/s]

 20%|█▉        | 5923/30196 [12:27<46:25,  8.72it/s]

 20%|█▉        | 5924/30196 [12:28<52:35,  7.69it/s]

 20%|█▉        | 5926/30196 [12:28<49:06,  8.24it/s]

 20%|█▉        | 5928/30196 [12:29<1:24:22,  4.79it/s]

 20%|█▉        | 5930/30196 [12:29<1:21:35,  4.96it/s]

 20%|█▉        | 5931/30196 [12:29<1:16:20,  5.30it/s]

 20%|█▉        | 5932/30196 [12:29<1:12:18,  5.59it/s]

 20%|█▉        | 5933/30196 [12:29<1:15:35,  5.35it/s]

 20%|█▉        | 5935/30196 [12:30<57:54,  6.98it/s]

 20%|█▉        | 5936/30196 [12:30<56:51,  7.11it/s]

 20%|█▉        | 5938/30196 [12:30<44:19,  9.12it/s]

 20%|█▉        | 5940/30196 [12:30<42:20,  9.55it/s]

 20%|█▉        | 5942/30196 [12:30<39:37, 10.20it/s]

 20%|█▉        | 5944/30196 [12:30<42:26,  9.52it/s]

 20%|█▉        | 5946/30196 [12:31<44:21,  9.11it/s]

 20%|█▉        | 5947/30196 [12:31<49:30,  8.16it/s]

 20%|█▉        | 5949/30196 [12:31<50:39,  7.98it/s]

 20%|█▉        | 5951/30196 [12:31<49:42,  8.13it/s]

 20%|█▉        | 5953/30196 [12:32<46:14,  8.74it/s]

 20%|█▉        | 5954/30196 [12:32<47:30,  8.50it/s]

 20%|█▉        | 5955/30196 [12:32<49:34,  8.15it/s]

 20%|█▉        | 5956/30196 [12:32<59:40,  6.77it/s]

 20%|█▉        | 5957/30196 [12:32<58:24,  6.92it/s]

 20%|█▉        | 5958/30196 [12:32<58:36,  6.89it/s]

 20%|█▉        | 5960/30196 [12:33<54:08,  7.46it/s]

 20%|█▉        | 5962/30196 [12:33<53:29,  7.55it/s]

 20%|█▉        | 5963/30196 [12:33<51:11,  7.89it/s]

 20%|█▉        | 5964/30196 [12:33<49:18,  8.19it/s]

 20%|█▉        | 5965/30196 [12:33<57:57,  6.97it/s]

 20%|█▉        | 5967/30196 [12:33<42:21,  9.53it/s]

 20%|█▉        | 5969/30196 [12:34<40:41,  9.92it/s]

 20%|█▉        | 5971/30196 [12:34<41:25,  9.75it/s]

 20%|█▉        | 5973/30196 [12:34<1:01:51,  6.53it/s]

 20%|█▉        | 5974/30196 [12:34<1:02:52,  6.42it/s]

 20%|█▉        | 5975/30196 [12:35<1:02:05,  6.50it/s]

 20%|█▉        | 5976/30196 [12:35<1:01:13,  6.59it/s]

 20%|█▉        | 5978/30196 [12:35<47:30,  8.50it/s]

 20%|█▉        | 5979/30196 [12:35<52:40,  7.66it/s]

 20%|█▉        | 5980/30196 [12:35<52:45,  7.65it/s]

 20%|█▉        | 5982/30196 [12:35<43:46,  9.22it/s]

 20%|█▉        | 5984/30196 [12:36<43:47,  9.22it/s]

 20%|█▉        | 5986/30196 [12:36<45:31,  8.86it/s]

 20%|█▉        | 5988/30196 [12:36<38:39, 10.44it/s]

 20%|█▉        | 5990/30196 [12:36<36:53, 10.93it/s]

 20%|█▉        | 5992/30196 [12:36<48:53,  8.25it/s]

 20%|█▉        | 5993/30196 [12:37<48:05,  8.39it/s]

 20%|█▉        | 5994/30196 [12:37<49:52,  8.09it/s]

 20%|█▉        | 5995/30196 [12:37<54:34,  7.39it/s]

 20%|█▉        | 5997/30196 [12:37<56:41,  7.11it/s]

 20%|█▉        | 5998/30196 [12:37<1:09:18,  5.82it/s]

 20%|█▉        | 5999/30196 [12:38<1:06:57,  6.02it/s]

 20%|█▉        | 6000/30196 [12:38<1:04:21,  6.27it/s]

 20%|█▉        | 6001/30196 [12:38<1:01:37,  6.54it/s]

 20%|█▉        | 6002/30196 [12:38<1:00:57,  6.62it/s]

 20%|█▉        | 6003/30196 [12:38<58:34,  6.88it/s]

 20%|█▉        | 6005/30196 [12:38<42:50,  9.41it/s]

 20%|█▉        | 6007/30196 [12:38<40:25,  9.97it/s]

 20%|█▉        | 6009/30196 [12:39<42:10,  9.56it/s]

 20%|█▉        | 6010/30196 [12:39<52:13,  7.72it/s]

 20%|█▉        | 6012/30196 [12:39<51:32,  7.82it/s]

 20%|█▉        | 6014/30196 [12:39<51:52,  7.77it/s]

 20%|█▉        | 6015/30196 [12:40<1:02:18,  6.47it/s]

 20%|█▉        | 6016/30196 [12:40<1:01:08,  6.59it/s]

 20%|█▉        | 6017/30196 [12:40<1:00:37,  6.65it/s]

 20%|█▉        | 6018/30196 [12:40<1:03:26,  6.35it/s]

 20%|█▉        | 6020/30196 [12:40<50:46,  7.93it/s]

 20%|█▉        | 6022/30196 [12:41<50:26,  7.99it/s]

 20%|█▉        | 6024/30196 [12:41<48:47,  8.26it/s]

 20%|█▉        | 6025/30196 [12:41<52:36,  7.66it/s]

 20%|█▉        | 6026/30196 [12:41<53:41,  7.50it/s]

 20%|█▉        | 6027/30196 [12:41<55:01,  7.32it/s]

 20%|█▉        | 6029/30196 [12:41<47:01,  8.57it/s]

 20%|█▉        | 6030/30196 [12:42<49:06,  8.20it/s]

 20%|█▉        | 6032/30196 [12:42<49:36,  8.12it/s]

 20%|█▉        | 6034/30196 [12:42<40:20,  9.98it/s]

 20%|█▉        | 6036/30196 [12:42<46:57,  8.57it/s]

 20%|█▉        | 6038/30196 [12:42<41:18,  9.75it/s]

 20%|██        | 6040/30196 [12:43<39:33, 10.18it/s]

 20%|██        | 6042/30196 [12:43<39:51, 10.10it/s]

 20%|██        | 6044/30196 [12:43<43:56,  9.16it/s]

 20%|██        | 6045/30196 [12:44<1:21:06,  4.96it/s]

 20%|██        | 6046/30196 [12:44<1:18:34,  5.12it/s]

 20%|██        | 6048/30196 [12:44<1:02:26,  6.44it/s]

 20%|██        | 6049/30196 [12:44<1:04:40,  6.22it/s]

 20%|██        | 6050/30196 [12:44<1:00:01,  6.70it/s]

 20%|██        | 6051/30196 [12:44<59:50,  6.73it/s]

 20%|██        | 6052/30196 [12:45<1:03:12,  6.37it/s]

 20%|██        | 6054/30196 [12:45<54:55,  7.33it/s]

 20%|██        | 6055/30196 [12:45<57:59,  6.94it/s]

 20%|██        | 6056/30196 [12:45<1:04:16,  6.26it/s]

 20%|██        | 6058/30196 [12:45<52:25,  7.67it/s]

 20%|██        | 6060/30196 [12:45<44:10,  9.11it/s]

 20%|██        | 6061/30196 [12:46<52:31,  7.66it/s]

 20%|██        | 6062/30196 [12:46<56:11,  7.16it/s]

 20%|██        | 6063/30196 [12:46<56:51,  7.07it/s]

 20%|██        | 6064/30196 [12:46<1:05:15,  6.16it/s]

 20%|██        | 6066/30196 [12:46<46:27,  8.66it/s]

 20%|██        | 6068/30196 [12:47<42:21,  9.49it/s]

 20%|██        | 6070/30196 [12:47<40:41,  9.88it/s]

 20%|██        | 6072/30196 [12:47<40:17,  9.98it/s]

 20%|██        | 6074/30196 [12:47<35:59, 11.17it/s]

 20%|██        | 6076/30196 [12:47<37:12, 10.80it/s]

 20%|██        | 6078/30196 [12:47<38:51, 10.34it/s]

 20%|██        | 6080/30196 [12:48<42:58,  9.35it/s]

 20%|██        | 6081/30196 [12:48<44:41,  8.99it/s]

 20%|██        | 6082/30196 [12:48<56:43,  7.08it/s]

 20%|██        | 6083/30196 [12:48<57:20,  7.01it/s]

 20%|██        | 6084/30196 [12:48<56:09,  7.16it/s]

 20%|██        | 6085/30196 [12:49<56:18,  7.14it/s]

 20%|██        | 6086/30196 [12:49<1:04:19,  6.25it/s]

 20%|██        | 6088/30196 [12:49<54:30,  7.37it/s]

 20%|██        | 6089/30196 [12:49<1:01:28,  6.54it/s]

 20%|██        | 6091/30196 [12:49<45:49,  8.77it/s]

 20%|██        | 6092/30196 [12:49<48:50,  8.22it/s]

 20%|██        | 6093/30196 [12:50<49:45,  8.07it/s]

 20%|██        | 6094/30196 [12:50<2:05:47,  3.19it/s]

 20%|██        | 6095/30196 [12:51<1:47:38,  3.73it/s]

 20%|██        | 6096/30196 [12:51<1:38:10,  4.09it/s]

 20%|██        | 6098/30196 [12:51<1:14:40,  5.38it/s]

 20%|██        | 6099/30196 [12:51<1:10:18,  5.71it/s]

 20%|██        | 6100/30196 [12:51<1:10:30,  5.70it/s]

 20%|██        | 6101/30196 [12:51<1:03:32,  6.32it/s]

 20%|██        | 6103/30196 [12:52<50:29,  7.95it/s]

 20%|██        | 6104/30196 [12:52<51:55,  7.73it/s]

 20%|██        | 6105/30196 [12:52<1:02:10,  6.46it/s]

 20%|██        | 6107/30196 [12:52<45:49,  8.76it/s]

 20%|██        | 6109/30196 [12:52<44:11,  9.09it/s]

 20%|██        | 6111/30196 [12:53<48:45,  8.23it/s]

 20%|██        | 6112/30196 [12:53<56:36,  7.09it/s]

 20%|██        | 6113/30196 [12:53<53:16,  7.53it/s]

 20%|██        | 6115/30196 [12:53<47:59,  8.36it/s]

 20%|██        | 6116/30196 [12:53<46:34,  8.62it/s]

 20%|██        | 6117/30196 [12:53<48:16,  8.31it/s]

 20%|██        | 6118/30196 [12:53<51:56,  7.73it/s]

 20%|██        | 6120/30196 [12:54<47:54,  8.37it/s]

 20%|██        | 6121/30196 [12:54<50:25,  7.96it/s]

 20%|██        | 6122/30196 [12:54<51:02,  7.86it/s]

 20%|██        | 6124/30196 [12:54<45:47,  8.76it/s]

 20%|██        | 6126/30196 [12:54<40:02, 10.02it/s]

 20%|██        | 6127/30196 [12:54<40:56,  9.80it/s]

 20%|██        | 6129/30196 [12:55<45:45,  8.77it/s]

 20%|██        | 6130/30196 [12:55<45:10,  8.88it/s]

 20%|██        | 6131/30196 [12:55<54:43,  7.33it/s]

 20%|██        | 6133/30196 [12:55<45:19,  8.85it/s]

 20%|██        | 6135/30196 [12:55<41:37,  9.63it/s]

 20%|██        | 6136/30196 [12:55<42:06,  9.52it/s]

 20%|██        | 6138/30196 [12:56<38:48, 10.33it/s]

 20%|██        | 6140/30196 [12:56<44:33,  9.00it/s]

 20%|██        | 6142/30196 [12:56<39:41, 10.10it/s]

 20%|██        | 6144/30196 [12:56<41:46,  9.59it/s]

 20%|██        | 6146/30196 [12:56<40:18,  9.94it/s]

 20%|██        | 6148/30196 [12:57<41:51,  9.57it/s]

 20%|██        | 6149/30196 [12:57<47:09,  8.50it/s]

 20%|██        | 6150/30196 [12:57<49:07,  8.16it/s]

 20%|██        | 6151/30196 [12:57<50:43,  7.90it/s]

 20%|██        | 6152/30196 [12:57<1:00:58,  6.57it/s]

 20%|██        | 6153/30196 [12:57<59:30,  6.73it/s]

 20%|██        | 6154/30196 [12:58<1:02:12,  6.44it/s]

 20%|██        | 6156/30196 [12:58<57:26,  6.97it/s]

 20%|██        | 6157/30196 [12:58<59:30,  6.73it/s]

 20%|██        | 6159/30196 [12:58<46:19,  8.65it/s]

 20%|██        | 6161/30196 [12:58<36:50, 10.87it/s]

 20%|██        | 6163/30196 [12:59<40:33,  9.87it/s]

 20%|██        | 6165/30196 [12:59<46:17,  8.65it/s]

 20%|██        | 6167/30196 [12:59<43:42,  9.16it/s]

 20%|██        | 6169/30196 [12:59<46:42,  8.57it/s]

 20%|██        | 6170/30196 [12:59<45:52,  8.73it/s]

 20%|██        | 6172/30196 [13:00<43:52,  9.12it/s]

 20%|██        | 6173/30196 [13:00<43:23,  9.23it/s]

 20%|██        | 6175/30196 [13:00<37:12, 10.76it/s]

 20%|██        | 6177/30196 [13:00<37:32, 10.66it/s]

 20%|██        | 6179/30196 [13:00<38:47, 10.32it/s]

 20%|██        | 6181/30196 [13:00<38:34, 10.38it/s]

 20%|██        | 6183/30196 [13:01<41:56,  9.54it/s]

 20%|██        | 6185/30196 [13:01<39:39, 10.09it/s]

 20%|██        | 6187/30196 [13:01<44:31,  8.99it/s]

 20%|██        | 6188/30196 [13:01<46:35,  8.59it/s]

 20%|██        | 6190/30196 [13:01<42:03,  9.51it/s]

 21%|██        | 6191/30196 [13:02<42:24,  9.43it/s]

 21%|██        | 6193/30196 [13:02<44:26,  9.00it/s]

 21%|██        | 6195/30196 [13:02<36:32, 10.94it/s]

 21%|██        | 6197/30196 [13:02<37:02, 10.80it/s]

 21%|██        | 6199/30196 [13:02<40:26,  9.89it/s]

 21%|██        | 6201/30196 [13:03<44:37,  8.96it/s]

 21%|██        | 6203/30196 [13:03<40:45,  9.81it/s]

 21%|██        | 6205/30196 [13:03<47:32,  8.41it/s]

 21%|██        | 6206/30196 [13:03<55:16,  7.23it/s]

 21%|██        | 6207/30196 [13:03<55:30,  7.20it/s]

 21%|██        | 6209/30196 [13:04<45:48,  8.73it/s]

 21%|██        | 6211/30196 [13:04<43:57,  9.09it/s]

 21%|██        | 6212/30196 [13:04<45:58,  8.69it/s]

 21%|██        | 6214/30196 [13:04<40:13,  9.94it/s]

 21%|██        | 6216/30196 [13:04<43:15,  9.24it/s]

 21%|██        | 6217/30196 [13:04<48:18,  8.27it/s]

 21%|██        | 6218/30196 [13:05<55:40,  7.18it/s]

 21%|██        | 6219/30196 [13:05<53:05,  7.53it/s]

 21%|██        | 6220/30196 [13:05<52:53,  7.55it/s]

 21%|██        | 6222/30196 [13:05<46:15,  8.64it/s]

 21%|██        | 6223/30196 [13:05<51:06,  7.82it/s]

 21%|██        | 6224/30196 [13:05<53:54,  7.41it/s]

 21%|██        | 6225/30196 [13:06<54:35,  7.32it/s]

 21%|██        | 6226/30196 [13:06<1:04:33,  6.19it/s]

 21%|██        | 6228/30196 [13:06<47:48,  8.36it/s]

 21%|██        | 6230/30196 [13:06<43:35,  9.16it/s]

 21%|██        | 6231/30196 [13:06<43:36,  9.16it/s]

 21%|██        | 6232/30196 [13:06<46:03,  8.67it/s]

 21%|██        | 6233/30196 [13:06<47:37,  8.39it/s]

 21%|██        | 6234/30196 [13:07<52:52,  7.55it/s]

 21%|██        | 6236/30196 [13:07<44:46,  8.92it/s]

 21%|██        | 6238/30196 [13:07<42:59,  9.29it/s]

 21%|██        | 6240/30196 [13:07<43:35,  9.16it/s]

 21%|██        | 6241/30196 [13:07<43:12,  9.24it/s]

 21%|██        | 6243/30196 [13:08<47:14,  8.45it/s]

 21%|██        | 6245/30196 [13:08<44:08,  9.04it/s]

 21%|██        | 6246/30196 [13:08<52:16,  7.64it/s]

 21%|██        | 6247/30196 [13:08<58:43,  6.80it/s]

 21%|██        | 6248/30196 [13:08<1:00:42,  6.57it/s]

 21%|██        | 6249/30196 [13:08<55:41,  7.17it/s]

 21%|██        | 6250/30196 [13:09<1:03:34,  6.28it/s]

 21%|██        | 6251/30196 [13:09<1:04:20,  6.20it/s]

 21%|██        | 6252/30196 [13:09<1:01:18,  6.51it/s]

 21%|██        | 6253/30196 [13:09<55:39,  7.17it/s]

 21%|██        | 6255/30196 [13:09<48:06,  8.29it/s]

 21%|██        | 6257/30196 [13:10<50:48,  7.85it/s]

 21%|██        | 6259/30196 [13:10<42:57,  9.29it/s]

 21%|██        | 6260/30196 [13:10<55:22,  7.20it/s]

 21%|██        | 6261/30196 [13:10<54:59,  7.25it/s]

 21%|██        | 6262/30196 [13:10<51:47,  7.70it/s]

 21%|██        | 6264/30196 [13:10<44:04,  9.05it/s]

 21%|██        | 6266/30196 [13:11<40:44,  9.79it/s]

 21%|██        | 6268/30196 [13:11<38:48, 10.27it/s]

 21%|██        | 6270/30196 [13:11<40:09,  9.93it/s]

 21%|██        | 6272/30196 [13:11<38:47, 10.28it/s]

 21%|██        | 6274/30196 [13:11<34:43, 11.48it/s]

 21%|██        | 6276/30196 [13:11<31:31, 12.65it/s]

 21%|██        | 6278/30196 [13:12<37:18, 10.68it/s]

 21%|██        | 6280/30196 [13:12<35:01, 11.38it/s]

 21%|██        | 6282/30196 [13:12<39:35, 10.07it/s]

 21%|██        | 6284/30196 [13:12<48:33,  8.21it/s]

 21%|██        | 6285/30196 [13:13<51:57,  7.67it/s]

 21%|██        | 6287/30196 [13:13<46:40,  8.54it/s]

 21%|██        | 6289/30196 [13:13<46:42,  8.53it/s]

 21%|██        | 6291/30196 [13:13<41:57,  9.49it/s]

 21%|██        | 6293/30196 [13:13<42:35,  9.35it/s]

 21%|██        | 6294/30196 [13:14<45:30,  8.75it/s]

 21%|██        | 6297/30196 [13:14<38:34, 10.33it/s]

 21%|██        | 6299/30196 [13:14<38:30, 10.34it/s]

 21%|██        | 6301/30196 [13:14<38:31, 10.34it/s]

 21%|██        | 6303/30196 [13:14<40:11,  9.91it/s]

 21%|██        | 6304/30196 [13:14<40:29,  9.83it/s]

 21%|██        | 6305/30196 [13:15<46:20,  8.59it/s]

 21%|██        | 6307/30196 [13:15<38:16, 10.40it/s]

 21%|██        | 6309/30196 [13:15<42:35,  9.35it/s]

 21%|██        | 6311/30196 [13:15<40:16,  9.88it/s]

 21%|██        | 6313/30196 [13:15<37:34, 10.59it/s]

 21%|██        | 6315/30196 [13:16<43:32,  9.14it/s]

 21%|██        | 6317/30196 [13:16<43:30,  9.15it/s]

 21%|██        | 6318/30196 [13:16<43:10,  9.22it/s]

 21%|██        | 6319/30196 [13:16<52:27,  7.59it/s]

 21%|██        | 6320/30196 [13:16<53:40,  7.41it/s]

 21%|██        | 6322/30196 [13:17<48:11,  8.26it/s]

 21%|██        | 6324/30196 [13:17<48:08,  8.26it/s]

 21%|██        | 6325/30196 [13:17<1:00:42,  6.55it/s]

 21%|██        | 6326/30196 [13:17<56:50,  7.00it/s]

 21%|██        | 6327/30196 [13:17<53:42,  7.41it/s]

 21%|██        | 6328/30196 [13:17<1:01:04,  6.51it/s]

 21%|██        | 6329/30196 [13:18<1:03:07,  6.30it/s]

 21%|██        | 6330/30196 [13:18<57:35,  6.91it/s]

 21%|██        | 6332/30196 [13:18<41:11,  9.65it/s]

 21%|██        | 6334/30196 [13:18<34:59, 11.36it/s]

 21%|██        | 6336/30196 [13:18<46:13,  8.60it/s]

 21%|██        | 6338/30196 [13:19<47:09,  8.43it/s]

 21%|██        | 6339/30196 [13:19<48:48,  8.15it/s]

 21%|██        | 6341/30196 [13:19<47:56,  8.29it/s]

 21%|██        | 6342/30196 [13:19<49:07,  8.09it/s]

 21%|██        | 6344/30196 [13:19<51:12,  7.76it/s]

 21%|██        | 6345/30196 [13:19<49:11,  8.08it/s]

 21%|██        | 6346/30196 [13:20<49:44,  7.99it/s]

 21%|██        | 6347/30196 [13:20<1:06:58,  5.93it/s]

 21%|██        | 6348/30196 [13:20<1:04:40,  6.15it/s]

 21%|██        | 6350/30196 [13:20<1:02:11,  6.39it/s]

 21%|██        | 6352/30196 [13:20<50:48,  7.82it/s]

 21%|██        | 6353/30196 [13:21<51:24,  7.73it/s]

 21%|██        | 6354/30196 [13:21<54:48,  7.25it/s]

 21%|██        | 6355/30196 [13:21<55:03,  7.22it/s]

 21%|██        | 6356/30196 [13:21<55:19,  7.18it/s]

 21%|██        | 6357/30196 [13:21<52:05,  7.63it/s]

 21%|██        | 6359/30196 [13:21<46:38,  8.52it/s]

 21%|██        | 6360/30196 [13:22<56:30,  7.03it/s]

 21%|██        | 6361/30196 [13:22<1:11:16,  5.57it/s]

 21%|██        | 6363/30196 [13:22<57:34,  6.90it/s]

 21%|██        | 6364/30196 [13:22<59:46,  6.65it/s]

 21%|██        | 6366/30196 [13:22<47:43,  8.32it/s]

 21%|██        | 6367/30196 [13:22<46:26,  8.55it/s]

 21%|██        | 6368/30196 [13:23<50:58,  7.79it/s]

 21%|██        | 6371/30196 [13:23<1:03:37,  6.24it/s]

 21%|██        | 6372/30196 [13:23<1:07:48,  5.86it/s]

 21%|██        | 6373/30196 [13:24<1:07:22,  5.89it/s]

 21%|██        | 6374/30196 [13:24<1:07:49,  5.85it/s]

 21%|██        | 6375/30196 [13:24<1:01:42,  6.43it/s]

 21%|██        | 6377/30196 [13:24<54:50,  7.24it/s]

 21%|██        | 6378/30196 [13:24<52:13,  7.60it/s]

 21%|██        | 6379/30196 [13:24<53:08,  7.47it/s]

 21%|██        | 6381/30196 [13:25<49:25,  8.03it/s]

 21%|██        | 6382/30196 [13:25<47:38,  8.33it/s]

 21%|██        | 6384/30196 [13:25<38:54, 10.20it/s]

 21%|██        | 6386/30196 [13:25<43:53,  9.04it/s]

 21%|██        | 6387/30196 [13:25<46:36,  8.51it/s]

 21%|██        | 6388/30196 [13:25<48:11,  8.23it/s]

 21%|██        | 6389/30196 [13:26<49:02,  8.09it/s]

 21%|██        | 6390/30196 [13:26<1:02:08,  6.39it/s]

 21%|██        | 6391/30196 [13:26<59:20,  6.69it/s]

 21%|██        | 6393/30196 [13:26<54:33,  7.27it/s]

 21%|██        | 6394/30196 [13:26<51:57,  7.64it/s]

 21%|██        | 6396/30196 [13:26<41:43,  9.51it/s]

 21%|██        | 6398/30196 [13:27<48:54,  8.11it/s]

 21%|██        | 6399/30196 [13:27<47:50,  8.29it/s]

 21%|██        | 6400/30196 [13:27<46:51,  8.46it/s]

 21%|██        | 6401/30196 [13:27<52:55,  7.49it/s]

 21%|██        | 6403/30196 [13:27<40:37,  9.76it/s]

 21%|██        | 6405/30196 [13:27<34:18, 11.55it/s]

 21%|██        | 6407/30196 [13:28<38:37, 10.27it/s]

 21%|██        | 6409/30196 [13:28<45:36,  8.69it/s]

 21%|██        | 6411/30196 [13:28<43:38,  9.08it/s]

 21%|██        | 6413/30196 [13:28<39:30, 10.03it/s]

 21%|██        | 6415/30196 [13:29<49:36,  7.99it/s]

 21%|██        | 6416/30196 [13:29<52:43,  7.52it/s]

 21%|██▏       | 6417/30196 [13:29<50:50,  7.80it/s]

 21%|██▏       | 6418/30196 [13:29<55:02,  7.20it/s]

 21%|██▏       | 6419/30196 [13:29<57:34,  6.88it/s]

 21%|██▏       | 6420/30196 [13:29<1:04:03,  6.19it/s]

 21%|██▏       | 6421/30196 [13:30<1:01:49,  6.41it/s]

 21%|██▏       | 6423/30196 [13:30<45:19,  8.74it/s]

 21%|██▏       | 6424/30196 [13:30<47:10,  8.40it/s]

 21%|██▏       | 6425/30196 [13:30<53:22,  7.42it/s]

 21%|██▏       | 6426/30196 [13:30<50:11,  7.89it/s]

 21%|██▏       | 6427/30196 [13:30<51:37,  7.67it/s]

 21%|██▏       | 6428/30196 [13:30<55:28,  7.14it/s]

 21%|██▏       | 6430/30196 [13:31<42:00,  9.43it/s]

 21%|██▏       | 6431/30196 [13:31<41:56,  9.44it/s]

 21%|██▏       | 6433/30196 [13:31<35:54, 11.03it/s]

 21%|██▏       | 6435/30196 [13:31<37:03, 10.69it/s]

 21%|██▏       | 6437/30196 [13:31<41:34,  9.52it/s]

 21%|██▏       | 6439/30196 [13:31<40:38,  9.74it/s]

 21%|██▏       | 6441/30196 [13:32<39:53,  9.92it/s]

 21%|██▏       | 6443/30196 [13:32<41:03,  9.64it/s]

 21%|██▏       | 6445/30196 [13:32<38:51, 10.19it/s]

 21%|██▏       | 6447/30196 [13:32<52:03,  7.60it/s]

 21%|██▏       | 6448/30196 [13:33<52:14,  7.58it/s]

 21%|██▏       | 6449/30196 [13:33<53:30,  7.40it/s]

 21%|██▏       | 6451/30196 [13:33<43:18,  9.14it/s]

 21%|██▏       | 6453/30196 [13:33<51:30,  7.68it/s]

 21%|██▏       | 6454/30196 [13:33<49:34,  7.98it/s]

 21%|██▏       | 6455/30196 [13:33<48:10,  8.21it/s]

 21%|██▏       | 6457/30196 [13:34<41:52,  9.45it/s]

 21%|██▏       | 6459/30196 [13:34<49:11,  8.04it/s]

 21%|██▏       | 6461/30196 [13:34<45:26,  8.70it/s]

 21%|██▏       | 6463/30196 [13:34<42:05,  9.40it/s]

 21%|██▏       | 6464/30196 [13:34<41:56,  9.43it/s]

 21%|██▏       | 6466/30196 [13:34<36:31, 10.83it/s]

 21%|██▏       | 6468/30196 [13:35<39:38,  9.98it/s]

 21%|██▏       | 6470/30196 [13:35<37:28, 10.55it/s]

 21%|██▏       | 6472/30196 [13:35<37:15, 10.61it/s]

 21%|██▏       | 6475/30196 [13:35<29:54, 13.22it/s]

 21%|██▏       | 6477/30196 [13:35<32:11, 12.28it/s]

 21%|██▏       | 6479/30196 [13:36<34:01, 11.62it/s]

 21%|██▏       | 6481/30196 [13:36<37:45, 10.47it/s]

 21%|██▏       | 6483/30196 [13:36<39:16, 10.06it/s]

 21%|██▏       | 6485/30196 [13:36<40:37,  9.73it/s]

 21%|██▏       | 6486/30196 [13:36<47:46,  8.27it/s]

 21%|██▏       | 6488/30196 [13:37<46:29,  8.50it/s]

 21%|██▏       | 6490/30196 [13:37<40:06,  9.85it/s]

 21%|██▏       | 6492/30196 [13:37<45:17,  8.72it/s]

 22%|██▏       | 6493/30196 [13:37<46:46,  8.45it/s]

 22%|██▏       | 6495/30196 [13:37<40:56,  9.65it/s]

 22%|██▏       | 6497/30196 [13:38<41:44,  9.46it/s]

 22%|██▏       | 6498/30196 [13:38<41:56,  9.42it/s]

 22%|██▏       | 6499/30196 [13:38<42:15,  9.35it/s]

 22%|██▏       | 6500/30196 [13:38<1:03:26,  6.22it/s]

 22%|██▏       | 6501/30196 [13:38<1:05:26,  6.03it/s]

 22%|██▏       | 6503/30196 [13:39<52:42,  7.49it/s]

 22%|██▏       | 6504/30196 [13:39<56:30,  6.99it/s]

 22%|██▏       | 6505/30196 [13:39<52:51,  7.47it/s]

 22%|██▏       | 6507/30196 [13:39<49:16,  8.01it/s]

 22%|██▏       | 6509/30196 [13:39<43:11,  9.14it/s]

 22%|██▏       | 6510/30196 [13:39<48:11,  8.19it/s]

 22%|██▏       | 6512/30196 [13:39<37:38, 10.49it/s]

 22%|██▏       | 6514/30196 [13:40<42:01,  9.39it/s]

 22%|██▏       | 6516/30196 [13:40<40:51,  9.66it/s]

 22%|██▏       | 6518/30196 [13:40<48:31,  8.13it/s]

 22%|██▏       | 6519/30196 [13:40<47:37,  8.28it/s]

 22%|██▏       | 6520/30196 [13:40<49:20,  8.00it/s]

 22%|██▏       | 6521/30196 [13:41<57:03,  6.92it/s]

 22%|██▏       | 6523/30196 [13:41<49:37,  7.95it/s]

 22%|██▏       | 6525/30196 [13:41<40:02,  9.85it/s]

 22%|██▏       | 6527/30196 [13:41<42:33,  9.27it/s]

 22%|██▏       | 6529/30196 [13:41<44:10,  8.93it/s]

 22%|██▏       | 6531/30196 [13:42<43:44,  9.02it/s]

 22%|██▏       | 6532/30196 [13:42<45:05,  8.75it/s]

 22%|██▏       | 6534/30196 [13:42<38:24, 10.27it/s]

 22%|██▏       | 6536/30196 [13:42<36:31, 10.80it/s]

 22%|██▏       | 6539/30196 [13:42<28:58, 13.61it/s]

 22%|██▏       | 6541/30196 [13:43<34:22, 11.47it/s]

 22%|██▏       | 6543/30196 [13:43<32:43, 12.04it/s]

 22%|██▏       | 6545/30196 [13:43<30:29, 12.93it/s]

 22%|██▏       | 6547/30196 [13:43<37:03, 10.64it/s]

 22%|██▏       | 6549/30196 [13:43<34:32, 11.41it/s]

 22%|██▏       | 6551/30196 [13:43<39:30,  9.97it/s]

 22%|██▏       | 6553/30196 [13:44<41:30,  9.49it/s]

 22%|██▏       | 6555/30196 [13:44<42:00,  9.38it/s]

 22%|██▏       | 6556/30196 [13:44<44:24,  8.87it/s]

 22%|██▏       | 6557/30196 [13:44<45:51,  8.59it/s]

 22%|██▏       | 6558/30196 [13:44<44:49,  8.79it/s]

 22%|██▏       | 6559/30196 [13:45<53:59,  7.30it/s]

 22%|██▏       | 6560/30196 [13:45<54:20,  7.25it/s]

 22%|██▏       | 6561/30196 [13:45<58:29,  6.74it/s]

 22%|██▏       | 6562/30196 [13:45<1:10:03,  5.62it/s]

 22%|██▏       | 6564/30196 [13:45<1:00:52,  6.47it/s]

 22%|██▏       | 6565/30196 [13:46<1:07:48,  5.81it/s]

 22%|██▏       | 6566/30196 [13:46<1:07:04,  5.87it/s]

 22%|██▏       | 6568/30196 [13:46<1:03:18,  6.22it/s]

 22%|██▏       | 6569/30196 [13:46<58:40,  6.71it/s]

 22%|██▏       | 6571/30196 [13:46<53:21,  7.38it/s]

 22%|██▏       | 6572/30196 [13:46<51:04,  7.71it/s]

 22%|██▏       | 6573/30196 [13:47<51:13,  7.69it/s]

 22%|██▏       | 6574/30196 [13:47<51:18,  7.67it/s]

 22%|██▏       | 6575/30196 [13:47<51:48,  7.60it/s]

 22%|██▏       | 6576/30196 [13:47<51:46,  7.60it/s]

 22%|██▏       | 6577/30196 [13:47<1:03:54,  6.16it/s]

 22%|██▏       | 6578/30196 [13:47<1:02:06,  6.34it/s]

 22%|██▏       | 6579/30196 [13:47<56:33,  6.96it/s]

 22%|██▏       | 6581/30196 [13:48<43:04,  9.14it/s]

 22%|██▏       | 6582/30196 [13:48<43:02,  9.14it/s]

 22%|██▏       | 6584/30196 [13:48<36:54, 10.66it/s]

 22%|██▏       | 6586/30196 [13:48<43:03,  9.14it/s]

 22%|██▏       | 6587/30196 [13:48<48:46,  8.07it/s]

 22%|██▏       | 6589/30196 [13:49<1:05:22,  6.02it/s]

 22%|██▏       | 6591/30196 [13:49<56:46,  6.93it/s]

 22%|██▏       | 6592/30196 [13:49<1:06:53,  5.88it/s]

 22%|██▏       | 6594/30196 [13:49<51:06,  7.70it/s]

 22%|██▏       | 6595/30196 [13:50<53:58,  7.29it/s]

 22%|██▏       | 6597/30196 [13:50<41:24,  9.50it/s]

 22%|██▏       | 6599/30196 [13:50<38:57, 10.09it/s]

 22%|██▏       | 6601/30196 [13:50<40:34,  9.69it/s]

 22%|██▏       | 6603/30196 [13:50<45:08,  8.71it/s]

 22%|██▏       | 6604/30196 [13:50<44:23,  8.86it/s]

 22%|██▏       | 6606/30196 [13:51<41:03,  9.58it/s]

 22%|██▏       | 6608/30196 [13:51<37:08, 10.59it/s]

 22%|██▏       | 6610/30196 [13:51<31:33, 12.46it/s]

 22%|██▏       | 6612/30196 [13:51<32:54, 11.94it/s]

 22%|██▏       | 6614/30196 [13:51<37:22, 10.52it/s]

 22%|██▏       | 6616/30196 [13:52<39:50,  9.86it/s]

 22%|██▏       | 6618/30196 [13:52<46:04,  8.53it/s]

 22%|██▏       | 6619/30196 [13:52<48:48,  8.05it/s]

 22%|██▏       | 6620/30196 [13:52<1:03:16,  6.21it/s]

 22%|██▏       | 6621/30196 [13:52<1:01:26,  6.40it/s]

 22%|██▏       | 6623/30196 [13:53<54:09,  7.25it/s]

 22%|██▏       | 6625/30196 [13:53<44:41,  8.79it/s]

 22%|██▏       | 6627/30196 [13:53<52:46,  7.44it/s]

 22%|██▏       | 6628/30196 [13:53<50:56,  7.71it/s]

 22%|██▏       | 6629/30196 [13:53<51:38,  7.61it/s]

 22%|██▏       | 6631/30196 [13:54<46:24,  8.46it/s]

 22%|██▏       | 6633/30196 [13:54<39:56,  9.83it/s]

 22%|██▏       | 6635/30196 [13:54<43:56,  8.94it/s]

 22%|██▏       | 6637/30196 [13:54<40:09,  9.78it/s]

 22%|██▏       | 6639/30196 [13:54<35:55, 10.93it/s]

 22%|██▏       | 6641/30196 [13:54<32:28, 12.09it/s]

 22%|██▏       | 6643/30196 [13:55<36:47, 10.67it/s]

 22%|██▏       | 6645/30196 [13:55<53:16,  7.37it/s]

 22%|██▏       | 6646/30196 [13:55<53:13,  7.38it/s]

 22%|██▏       | 6647/30196 [13:55<55:40,  7.05it/s]

 22%|██▏       | 6649/30196 [13:56<54:02,  7.26it/s]

 22%|██▏       | 6651/30196 [13:56<50:31,  7.77it/s]

 22%|██▏       | 6652/30196 [13:56<50:38,  7.75it/s]

 22%|██▏       | 6653/30196 [13:56<48:55,  8.02it/s]

 22%|██▏       | 6654/30196 [13:56<51:08,  7.67it/s]

 22%|██▏       | 6656/30196 [13:56<41:38,  9.42it/s]

 22%|██▏       | 6657/30196 [13:57<52:36,  7.46it/s]

 22%|██▏       | 6658/30196 [13:57<53:48,  7.29it/s]

 22%|██▏       | 6659/30196 [13:57<54:28,  7.20it/s]

 22%|██▏       | 6660/30196 [13:57<55:10,  7.11it/s]

 22%|██▏       | 6661/30196 [13:57<58:15,  6.73it/s]

 22%|██▏       | 6662/30196 [13:57<53:19,  7.35it/s]

 22%|██▏       | 6664/30196 [13:58<51:59,  7.54it/s]

 22%|██▏       | 6665/30196 [13:58<1:05:26,  5.99it/s]

 22%|██▏       | 6667/30196 [13:58<57:34,  6.81it/s]

 22%|██▏       | 6668/30196 [13:58<57:04,  6.87it/s]

 22%|██▏       | 6669/30196 [13:58<56:41,  6.92it/s]

 22%|██▏       | 6670/30196 [13:59<1:42:58,  3.81it/s]

 22%|██▏       | 6672/30196 [13:59<1:12:33,  5.40it/s]

 22%|██▏       | 6674/30196 [13:59<1:02:32,  6.27it/s]

 22%|██▏       | 6675/30196 [14:00<58:23,  6.71it/s]

 22%|██▏       | 6676/30196 [14:00<54:19,  7.22it/s]

 22%|██▏       | 6677/30196 [14:00<53:58,  7.26it/s]

 22%|██▏       | 6679/30196 [14:00<43:21,  9.04it/s]

 22%|██▏       | 6680/30196 [14:00<45:11,  8.67it/s]

 22%|██▏       | 6682/30196 [14:00<42:55,  9.13it/s]

 22%|██▏       | 6683/30196 [14:00<45:08,  8.68it/s]

 22%|██▏       | 6684/30196 [14:01<44:38,  8.78it/s]

 22%|██▏       | 6685/30196 [14:01<59:06,  6.63it/s]

 22%|██▏       | 6687/30196 [14:01<44:40,  8.77it/s]

 22%|██▏       | 6689/30196 [14:01<42:39,  9.18it/s]

 22%|██▏       | 6690/30196 [14:01<45:24,  8.63it/s]

 22%|██▏       | 6691/30196 [14:01<47:13,  8.29it/s]

 22%|██▏       | 6692/30196 [14:01<45:42,  8.57it/s]

 22%|██▏       | 6694/30196 [14:02<44:31,  8.80it/s]

 22%|██▏       | 6696/30196 [14:02<40:22,  9.70it/s]

 22%|██▏       | 6697/30196 [14:02<46:11,  8.48it/s]

 22%|██▏       | 6698/30196 [14:02<48:19,  8.10it/s]

 22%|██▏       | 6700/30196 [14:02<47:06,  8.31it/s]

 22%|██▏       | 6702/30196 [14:03<40:11,  9.74it/s]

 22%|██▏       | 6703/30196 [14:03<42:26,  9.23it/s]

 22%|██▏       | 6705/30196 [14:03<40:47,  9.60it/s]

 22%|██▏       | 6706/30196 [14:03<46:07,  8.49it/s]

 22%|██▏       | 6707/30196 [14:03<47:14,  8.29it/s]

 22%|██▏       | 6708/30196 [14:03<51:34,  7.59it/s]

 22%|██▏       | 6709/30196 [14:03<49:16,  7.95it/s]

 22%|██▏       | 6710/30196 [14:04<49:48,  7.86it/s]

 22%|██▏       | 6711/30196 [14:04<54:50,  7.14it/s]

 22%|██▏       | 6712/30196 [14:04<1:19:39,  4.91it/s]

 22%|██▏       | 6714/30196 [14:04<1:08:13,  5.74it/s]

 22%|██▏       | 6715/30196 [14:05<1:01:51,  6.33it/s]

 22%|██▏       | 6718/30196 [14:05<43:09,  9.07it/s]

 22%|██▏       | 6720/30196 [14:05<43:18,  9.03it/s]

 22%|██▏       | 6721/30196 [14:05<48:19,  8.10it/s]

 22%|██▏       | 6723/30196 [14:05<48:57,  7.99it/s]

 22%|██▏       | 6725/30196 [14:06<44:20,  8.82it/s]

 22%|██▏       | 6727/30196 [14:06<49:28,  7.91it/s]

 22%|██▏       | 6728/30196 [14:06<48:15,  8.11it/s]

 22%|██▏       | 6729/30196 [14:06<46:59,  8.32it/s]

 22%|██▏       | 6730/30196 [14:06<52:17,  7.48it/s]

 22%|██▏       | 6732/30196 [14:07<51:59,  7.52it/s]

 22%|██▏       | 6735/30196 [14:07<57:51,  6.76it/s]

 22%|██▏       | 6736/30196 [14:07<57:00,  6.86it/s]

 22%|██▏       | 6737/30196 [14:07<1:11:23,  5.48it/s]

 22%|██▏       | 6738/30196 [14:08<1:10:33,  5.54it/s]

 22%|██▏       | 6740/30196 [14:08<56:42,  6.89it/s]

 22%|██▏       | 6741/30196 [14:08<58:25,  6.69it/s]

 22%|██▏       | 6743/30196 [14:08<50:04,  7.81it/s]

 22%|██▏       | 6744/30196 [14:08<51:07,  7.65it/s]

 22%|██▏       | 6745/30196 [14:08<52:18,  7.47it/s]

 22%|██▏       | 6747/30196 [14:09<49:23,  7.91it/s]

 22%|██▏       | 6748/30196 [14:09<50:28,  7.74it/s]

 22%|██▏       | 6749/30196 [14:09<51:21,  7.61it/s]

 22%|██▏       | 6751/30196 [14:09<38:57, 10.03it/s]

 22%|██▏       | 6753/30196 [14:09<41:01,  9.52it/s]

 22%|██▏       | 6755/30196 [14:10<50:14,  7.77it/s]

 22%|██▏       | 6756/30196 [14:10<1:01:17,  6.37it/s]

 22%|██▏       | 6758/30196 [14:10<54:04,  7.22it/s]

 22%|██▏       | 6759/30196 [14:10<1:00:34,  6.45it/s]

 22%|██▏       | 6760/30196 [14:11<1:07:13,  5.81it/s]

 22%|██▏       | 6761/30196 [14:11<1:11:06,  5.49it/s]

 22%|██▏       | 6762/30196 [14:11<1:20:00,  4.88it/s]

 22%|██▏       | 6763/30196 [14:11<1:13:17,  5.33it/s]

 22%|██▏       | 6764/30196 [14:11<1:16:51,  5.08it/s]

 22%|██▏       | 6765/30196 [14:12<1:10:18,  5.55it/s]

 22%|██▏       | 6766/30196 [14:12<1:09:13,  5.64it/s]

 22%|██▏       | 6768/30196 [14:12<49:27,  7.89it/s]

 22%|██▏       | 6769/30196 [14:12<1:17:33,  5.03it/s]

 22%|██▏       | 6771/30196 [14:12<56:44,  6.88it/s]

 22%|██▏       | 6772/30196 [14:13<56:22,  6.93it/s]

 22%|██▏       | 6773/30196 [14:13<52:37,  7.42it/s]

 22%|██▏       | 6774/30196 [14:13<53:57,  7.23it/s]

 22%|██▏       | 6775/30196 [14:13<50:54,  7.67it/s]

 22%|██▏       | 6777/30196 [14:13<40:07,  9.73it/s]

 22%|██▏       | 6779/30196 [14:13<42:37,  9.16it/s]

 22%|██▏       | 6780/30196 [14:13<44:42,  8.73it/s]

 22%|██▏       | 6782/30196 [14:14<42:10,  9.25it/s]

 22%|██▏       | 6783/30196 [14:14<42:19,  9.22it/s]

 22%|██▏       | 6784/30196 [14:14<47:56,  8.14it/s]

 22%|██▏       | 6785/30196 [14:14<56:49,  6.87it/s]

 22%|██▏       | 6787/30196 [14:14<48:56,  7.97it/s]

 22%|██▏       | 6789/30196 [14:14<41:32,  9.39it/s]

 22%|██▏       | 6790/30196 [14:15<1:00:32,  6.44it/s]

 22%|██▏       | 6792/30196 [14:15<50:29,  7.72it/s]

 22%|██▏       | 6794/30196 [14:15<47:23,  8.23it/s]

 23%|██▎       | 6797/30196 [14:15<35:04, 11.12it/s]

 23%|██▎       | 6799/30196 [14:16<37:49, 10.31it/s]

 23%|██▎       | 6801/30196 [14:16<37:03, 10.52it/s]

 23%|██▎       | 6803/30196 [14:16<39:00, 10.00it/s]

 23%|██▎       | 6805/30196 [14:16<38:08, 10.22it/s]

 23%|██▎       | 6807/30196 [14:16<35:33, 10.96it/s]

 23%|██▎       | 6809/30196 [14:17<45:53,  8.49it/s]

 23%|██▎       | 6811/30196 [14:17<48:06,  8.10it/s]

 23%|██▎       | 6812/30196 [14:17<1:01:47,  6.31it/s]

 23%|██▎       | 6814/30196 [14:17<51:33,  7.56it/s]

 23%|██▎       | 6815/30196 [14:18<52:43,  7.39it/s]

 23%|██▎       | 6817/30196 [14:18<50:55,  7.65it/s]

 23%|██▎       | 6819/30196 [14:18<44:32,  8.75it/s]

 23%|██▎       | 6821/30196 [14:18<38:42, 10.06it/s]

 23%|██▎       | 6823/30196 [14:18<39:18,  9.91it/s]

 23%|██▎       | 6825/30196 [14:18<33:16, 11.71it/s]

 23%|██▎       | 6827/30196 [14:19<45:32,  8.55it/s]

 23%|██▎       | 6829/30196 [14:19<59:55,  6.50it/s]

 23%|██▎       | 6831/30196 [14:19<54:46,  7.11it/s]

 23%|██▎       | 6833/30196 [14:20<47:38,  8.17it/s]

 23%|██▎       | 6835/30196 [14:20<50:19,  7.74it/s]

 23%|██▎       | 6837/30196 [14:20<48:07,  8.09it/s]

 23%|██▎       | 6839/30196 [14:20<41:29,  9.38it/s]

 23%|██▎       | 6841/30196 [14:21<50:26,  7.72it/s]

 23%|██▎       | 6843/30196 [14:21<44:59,  8.65it/s]

 23%|██▎       | 6845/30196 [14:21<49:49,  7.81it/s]

 23%|██▎       | 6846/30196 [14:21<50:20,  7.73it/s]

 23%|██▎       | 6847/30196 [14:21<48:25,  8.04it/s]

 23%|██▎       | 6849/30196 [14:22<39:09,  9.94it/s]

 23%|██▎       | 6851/30196 [14:22<53:20,  7.29it/s]

 23%|██▎       | 6852/30196 [14:22<55:30,  7.01it/s]

 23%|██▎       | 6853/30196 [14:22<52:14,  7.45it/s]

 23%|██▎       | 6854/30196 [14:22<49:56,  7.79it/s]

 23%|██▎       | 6855/30196 [14:22<48:08,  8.08it/s]

 23%|██▎       | 6856/30196 [14:23<49:20,  7.88it/s]

 23%|██▎       | 6858/30196 [14:23<52:56,  7.35it/s]

 23%|██▎       | 6859/30196 [14:23<50:31,  7.70it/s]

 23%|██▎       | 6861/30196 [14:23<50:11,  7.75it/s]

 23%|██▎       | 6863/30196 [14:23<50:43,  7.67it/s]

 23%|██▎       | 6864/30196 [14:24<50:46,  7.66it/s]

 23%|██▎       | 6866/30196 [14:24<43:52,  8.86it/s]

 23%|██▎       | 6868/30196 [14:24<41:37,  9.34it/s]

 23%|██▎       | 6869/30196 [14:24<43:24,  8.96it/s]

 23%|██▎       | 6871/30196 [14:24<44:09,  8.80it/s]

 23%|██▎       | 6873/30196 [14:24<38:36, 10.07it/s]

 23%|██▎       | 6875/30196 [14:25<34:40, 11.21it/s]

 23%|██▎       | 6877/30196 [14:25<34:48, 11.17it/s]

 23%|██▎       | 6879/30196 [14:25<34:01, 11.42it/s]

 23%|██▎       | 6881/30196 [14:25<29:50, 13.02it/s]

 23%|██▎       | 6883/30196 [14:25<32:15, 12.05it/s]

 23%|██▎       | 6885/30196 [14:25<33:19, 11.66it/s]

 23%|██▎       | 6887/30196 [14:26<39:47,  9.76it/s]

 23%|██▎       | 6890/30196 [14:26<30:59, 12.54it/s]

 23%|██▎       | 6892/30196 [14:26<40:25,  9.61it/s]

 23%|██▎       | 6894/30196 [14:26<44:21,  8.76it/s]

 23%|██▎       | 6896/30196 [14:27<43:24,  8.95it/s]

 23%|██▎       | 6898/30196 [14:27<1:01:22,  6.33it/s]

 23%|██▎       | 6899/30196 [14:27<1:00:02,  6.47it/s]

 23%|██▎       | 6900/30196 [14:28<1:01:42,  6.29it/s]

 23%|██▎       | 6901/30196 [14:28<1:20:54,  4.80it/s]

 23%|██▎       | 6902/30196 [14:28<1:15:22,  5.15it/s]

 23%|██▎       | 6904/30196 [14:28<59:03,  6.57it/s]

 23%|██▎       | 6905/30196 [14:29<1:08:14,  5.69it/s]

 23%|██▎       | 6906/30196 [14:29<1:17:38,  5.00it/s]

 23%|██▎       | 6907/30196 [14:29<1:20:44,  4.81it/s]

 23%|██▎       | 6908/30196 [14:29<1:31:52,  4.22it/s]

 23%|██▎       | 6909/30196 [14:29<1:24:34,  4.59it/s]

 23%|██▎       | 6910/30196 [14:30<1:23:37,  4.64it/s]

 23%|██▎       | 6911/30196 [14:30<1:19:34,  4.88it/s]

 23%|██▎       | 6912/30196 [14:30<1:11:10,  5.45it/s]

 23%|██▎       | 6913/30196 [14:30<1:09:16,  5.60it/s]

 23%|██▎       | 6915/30196 [14:30<46:42,  8.31it/s]

 23%|██▎       | 6917/30196 [14:31<48:59,  7.92it/s]

 23%|██▎       | 6918/30196 [14:31<50:49,  7.63it/s]

 23%|██▎       | 6920/30196 [14:31<42:36,  9.10it/s]

 23%|██▎       | 6922/30196 [14:31<45:00,  8.62it/s]

 23%|██▎       | 6923/30196 [14:31<46:55,  8.27it/s]

 23%|██▎       | 6924/30196 [14:31<45:29,  8.53it/s]

 23%|██▎       | 6926/30196 [14:32<42:53,  9.04it/s]

 23%|██▎       | 6927/30196 [14:32<45:59,  8.43it/s]

 23%|██▎       | 6928/30196 [14:32<48:19,  8.03it/s]

 23%|██▎       | 6930/30196 [14:32<48:14,  8.04it/s]

 23%|██▎       | 6932/30196 [14:32<41:06,  9.43it/s]

 23%|██▎       | 6934/30196 [14:33<46:57,  8.26it/s]

 23%|██▎       | 6935/30196 [14:33<47:50,  8.10it/s]

 23%|██▎       | 6936/30196 [14:33<52:04,  7.44it/s]

 23%|██▎       | 6938/30196 [14:33<49:09,  7.89it/s]

 23%|██▎       | 6940/30196 [14:33<48:39,  7.96it/s]

 23%|██▎       | 6942/30196 [14:34<43:44,  8.86it/s]

 23%|██▎       | 6943/30196 [14:34<48:15,  8.03it/s]

 23%|██▎       | 6945/30196 [14:34<46:34,  8.32it/s]

 23%|██▎       | 6946/30196 [14:34<48:16,  8.03it/s]

 23%|██▎       | 6948/30196 [14:34<40:17,  9.62it/s]

 23%|██▎       | 6949/30196 [14:34<40:18,  9.61it/s]

 23%|██▎       | 6950/30196 [14:34<42:40,  9.08it/s]

 23%|██▎       | 6951/30196 [14:35<45:01,  8.60it/s]

 23%|██▎       | 6952/30196 [14:35<50:05,  7.73it/s]

 23%|██▎       | 6954/30196 [14:35<48:03,  8.06it/s]

 23%|██▎       | 6955/30196 [14:35<1:01:26,  6.30it/s]

 23%|██▎       | 6957/30196 [14:35<54:38,  7.09it/s]

 23%|██▎       | 6958/30196 [14:36<51:54,  7.46it/s]

 23%|██▎       | 6959/30196 [14:36<53:12,  7.28it/s]

 23%|██▎       | 6960/30196 [14:36<54:01,  7.17it/s]

 23%|██▎       | 6961/30196 [14:36<54:09,  7.15it/s]

 23%|██▎       | 6963/30196 [14:36<50:16,  7.70it/s]

 23%|██▎       | 6964/30196 [14:36<48:26,  7.99it/s]

 23%|██▎       | 6966/30196 [14:36<40:06,  9.65it/s]

 23%|██▎       | 6967/30196 [14:37<45:29,  8.51it/s]

 23%|██▎       | 6968/30196 [14:37<44:50,  8.63it/s]

 23%|██▎       | 6969/30196 [14:37<44:12,  8.76it/s]

 23%|██▎       | 6970/30196 [14:37<43:39,  8.87it/s]

 23%|██▎       | 6971/30196 [14:37<49:42,  7.79it/s]

 23%|██▎       | 6972/30196 [14:37<51:44,  7.48it/s]

 23%|██▎       | 6973/30196 [14:38<1:43:13,  3.75it/s]

 23%|██▎       | 6974/30196 [14:38<1:25:26,  4.53it/s]

 23%|██▎       | 6975/30196 [14:38<1:20:37,  4.80it/s]

 23%|██▎       | 6977/30196 [14:38<58:23,  6.63it/s]

 23%|██▎       | 6978/30196 [14:38<57:49,  6.69it/s]

 23%|██▎       | 6979/30196 [14:39<53:54,  7.18it/s]

 23%|██▎       | 6980/30196 [14:39<50:53,  7.60it/s]

 23%|██▎       | 6981/30196 [14:39<48:30,  7.98it/s]

 23%|██▎       | 6983/30196 [14:39<41:10,  9.40it/s]

 23%|██▎       | 6985/30196 [14:39<40:59,  9.44it/s]

 23%|██▎       | 6986/30196 [14:39<49:54,  7.75it/s]

 23%|██▎       | 6987/30196 [14:40<50:33,  7.65it/s]

 23%|██▎       | 6989/30196 [14:40<42:01,  9.20it/s]

 23%|██▎       | 6990/30196 [14:40<45:28,  8.50it/s]

 23%|██▎       | 6991/30196 [14:40<44:45,  8.64it/s]

 23%|██▎       | 6993/30196 [14:40<37:15, 10.38it/s]

 23%|██▎       | 6995/30196 [14:40<35:16, 10.96it/s]

 23%|██▎       | 6997/30196 [14:41<43:09,  8.96it/s]

 23%|██▎       | 6998/30196 [14:41<44:36,  8.67it/s]

 23%|██▎       | 6999/30196 [14:41<46:43,  8.28it/s]

 23%|██▎       | 7000/30196 [14:41<45:16,  8.54it/s]

 23%|██▎       | 7001/30196 [14:41<51:32,  7.50it/s]

 23%|██▎       | 7002/30196 [14:41<51:32,  7.50it/s]

 23%|██▎       | 7004/30196 [14:41<38:35, 10.02it/s]

 23%|██▎       | 7006/30196 [14:42<1:05:03,  5.94it/s]

 23%|██▎       | 7007/30196 [14:42<1:02:17,  6.20it/s]

 23%|██▎       | 7008/30196 [14:42<1:00:25,  6.40it/s]

 23%|██▎       | 7010/30196 [14:42<52:20,  7.38it/s]

 23%|██▎       | 7011/30196 [14:43<55:01,  7.02it/s]

 23%|██▎       | 7012/30196 [14:43<54:35,  7.08it/s]

 23%|██▎       | 7014/30196 [14:43<45:22,  8.52it/s]

 23%|██▎       | 7015/30196 [14:43<47:29,  8.14it/s]

 23%|██▎       | 7017/30196 [14:43<43:49,  8.81it/s]

 23%|██▎       | 7018/30196 [14:43<43:31,  8.88it/s]

 23%|██▎       | 7020/30196 [14:44<43:19,  8.92it/s]

 23%|██▎       | 7022/30196 [14:44<36:42, 10.52it/s]

 23%|██▎       | 7024/30196 [14:44<37:31, 10.29it/s]

 23%|██▎       | 7026/30196 [14:44<39:18,  9.82it/s]

 23%|██▎       | 7028/30196 [14:44<40:22,  9.56it/s]

 23%|██▎       | 7029/30196 [14:45<49:37,  7.78it/s]

 23%|██▎       | 7031/30196 [14:45<42:19,  9.12it/s]

 23%|██▎       | 7032/30196 [14:45<50:45,  7.61it/s]

 23%|██▎       | 7033/30196 [14:45<48:31,  7.96it/s]

 23%|██▎       | 7034/30196 [14:45<49:01,  7.87it/s]

 23%|██▎       | 7035/30196 [14:45<50:25,  7.66it/s]

 23%|██▎       | 7036/30196 [14:45<48:14,  8.00it/s]

 23%|██▎       | 7037/30196 [14:46<48:49,  7.91it/s]

 23%|██▎       | 7039/30196 [14:46<43:56,  8.78it/s]

 23%|██▎       | 7041/30196 [14:46<35:38, 10.83it/s]

 23%|██▎       | 7043/30196 [14:46<40:40,  9.49it/s]

 23%|██▎       | 7045/30196 [14:46<42:18,  9.12it/s]

 23%|██▎       | 7046/30196 [14:47<47:27,  8.13it/s]

 23%|██▎       | 7048/30196 [14:47<45:07,  8.55it/s]

 23%|██▎       | 7050/30196 [14:47<48:00,  8.03it/s]

 23%|██▎       | 7052/30196 [14:47<47:43,  8.08it/s]

 23%|██▎       | 7053/30196 [14:47<46:42,  8.26it/s]

 23%|██▎       | 7055/30196 [14:47<38:35,  9.99it/s]

 23%|██▎       | 7057/30196 [14:48<45:05,  8.55it/s]

 23%|██▎       | 7059/30196 [14:48<44:36,  8.65it/s]

 23%|██▎       | 7060/30196 [14:48<45:57,  8.39it/s]

 23%|██▎       | 7062/30196 [14:48<40:07,  9.61it/s]

 23%|██▎       | 7064/30196 [14:49<41:29,  9.29it/s]

 23%|██▎       | 7066/30196 [14:49<42:11,  9.14it/s]

 23%|██▎       | 7067/30196 [14:49<46:54,  8.22it/s]

 23%|██▎       | 7068/30196 [14:49<1:04:27,  5.98it/s]

 23%|██▎       | 7069/30196 [14:49<1:04:43,  5.96it/s]

 23%|██▎       | 7070/30196 [14:50<1:05:15,  5.91it/s]

 23%|██▎       | 7072/30196 [14:50<52:55,  7.28it/s]

 23%|██▎       | 7073/30196 [14:50<52:46,  7.30it/s]

 23%|██▎       | 7075/30196 [14:50<1:08:16,  5.64it/s]

 23%|██▎       | 7077/30196 [14:51<56:39,  6.80it/s]

 23%|██▎       | 7079/30196 [14:51<46:56,  8.21it/s]

 23%|██▎       | 7080/30196 [14:51<1:01:30,  6.26it/s]

 23%|██▎       | 7081/30196 [14:51<1:07:33,  5.70it/s]

 23%|██▎       | 7082/30196 [14:51<1:03:49,  6.04it/s]

 23%|██▎       | 7083/30196 [14:52<57:50,  6.66it/s]

 23%|██▎       | 7084/30196 [14:52<1:04:57,  5.93it/s]

 23%|██▎       | 7086/30196 [14:52<45:54,  8.39it/s]

 23%|██▎       | 7088/30196 [14:52<51:39,  7.45it/s]

 23%|██▎       | 7090/30196 [14:52<53:42,  7.17it/s]

 23%|██▎       | 7091/30196 [14:53<51:03,  7.54it/s]

 23%|██▎       | 7092/30196 [14:53<55:10,  6.98it/s]

 23%|██▎       | 7093/30196 [14:53<57:22,  6.71it/s]

 23%|██▎       | 7095/30196 [14:53<46:54,  8.21it/s]

 23%|██▎       | 7096/30196 [14:53<50:48,  7.58it/s]

 24%|██▎       | 7097/30196 [14:53<48:15,  7.98it/s]

 24%|██▎       | 7098/30196 [14:53<48:48,  7.89it/s]

 24%|██▎       | 7099/30196 [14:54<53:48,  7.16it/s]

 24%|██▎       | 7101/30196 [14:54<53:10,  7.24it/s]

 24%|██▎       | 7103/30196 [14:54<50:13,  7.66it/s]

 24%|██▎       | 7105/30196 [14:54<49:00,  7.85it/s]

 24%|██▎       | 7107/30196 [14:55<45:11,  8.52it/s]

 24%|██▎       | 7108/30196 [14:55<44:35,  8.63it/s]

 24%|██▎       | 7110/30196 [14:55<39:37,  9.71it/s]

 24%|██▎       | 7112/30196 [14:55<39:24,  9.76it/s]

 24%|██▎       | 7113/30196 [14:55<45:12,  8.51it/s]

 24%|██▎       | 7114/30196 [14:55<47:45,  8.06it/s]

 24%|██▎       | 7116/30196 [14:56<45:26,  8.46it/s]

 24%|██▎       | 7117/30196 [14:56<44:33,  8.63it/s]

 24%|██▎       | 7119/30196 [14:56<44:55,  8.56it/s]

 24%|██▎       | 7121/30196 [14:56<44:54,  8.56it/s]

 24%|██▎       | 7122/30196 [14:56<44:22,  8.67it/s]

 24%|██▎       | 7123/30196 [14:56<49:02,  7.84it/s]

 24%|██▎       | 7125/30196 [14:57<43:55,  8.75it/s]

 24%|██▎       | 7127/30196 [14:57<40:02,  9.60it/s]

 24%|██▎       | 7128/30196 [14:57<43:08,  8.91it/s]

 24%|██▎       | 7130/30196 [14:57<51:45,  7.43it/s]

 24%|██▎       | 7132/30196 [14:57<43:33,  8.82it/s]

 24%|██▎       | 7133/30196 [14:58<47:52,  8.03it/s]

 24%|██▎       | 7134/30196 [14:58<51:21,  7.48it/s]

 24%|██▎       | 7136/30196 [14:58<42:10,  9.11it/s]

 24%|██▎       | 7138/30196 [14:58<36:53, 10.42it/s]

 24%|██▎       | 7140/30196 [14:58<37:10, 10.34it/s]

 24%|██▎       | 7142/30196 [14:58<34:46, 11.05it/s]

 24%|██▎       | 7144/30196 [14:59<35:52, 10.71it/s]

 24%|██▎       | 7146/30196 [14:59<45:56,  8.36it/s]

 24%|██▎       | 7147/30196 [14:59<55:10,  6.96it/s]

 24%|██▎       | 7149/30196 [14:59<48:09,  7.98it/s]

 24%|██▎       | 7151/30196 [15:00<45:54,  8.37it/s]

 24%|██▎       | 7153/30196 [15:00<37:26, 10.26it/s]

 24%|██▎       | 7155/30196 [15:00<48:51,  7.86it/s]

 24%|██▎       | 7157/30196 [15:00<52:31,  7.31it/s]

 24%|██▎       | 7158/30196 [15:01<55:07,  6.97it/s]

 24%|██▎       | 7159/30196 [15:01<55:28,  6.92it/s]

 24%|██▎       | 7161/30196 [15:01<52:12,  7.35it/s]

 24%|██▎       | 7162/30196 [15:01<54:49,  7.00it/s]

 24%|██▎       | 7163/30196 [15:01<56:49,  6.76it/s]

 24%|██▎       | 7165/30196 [15:02<48:04,  7.99it/s]

 24%|██▎       | 7166/30196 [15:02<56:07,  6.84it/s]

 24%|██▎       | 7167/30196 [15:02<58:03,  6.61it/s]

 24%|██▎       | 7170/30196 [15:02<43:45,  8.77it/s]

 24%|██▎       | 7171/30196 [15:02<43:29,  8.82it/s]

 24%|██▍       | 7172/30196 [15:02<47:49,  8.02it/s]

 24%|██▍       | 7173/30196 [15:03<46:33,  8.24it/s]

 24%|██▍       | 7174/30196 [15:03<48:26,  7.92it/s]

 24%|██▍       | 7175/30196 [15:03<50:30,  7.60it/s]

 24%|██▍       | 7177/30196 [15:03<37:38, 10.19it/s]

 24%|██▍       | 7179/30196 [15:03<34:26, 11.14it/s]

 24%|██▍       | 7181/30196 [15:03<44:40,  8.59it/s]

 24%|██▍       | 7183/30196 [15:04<39:22,  9.74it/s]

 24%|██▍       | 7185/30196 [15:04<35:57, 10.66it/s]

 24%|██▍       | 7187/30196 [15:04<35:14, 10.88it/s]

 24%|██▍       | 7189/30196 [15:04<33:58, 11.29it/s]

 24%|██▍       | 7191/30196 [15:04<39:28,  9.71it/s]

 24%|██▍       | 7193/30196 [15:05<45:02,  8.51it/s]

 24%|██▍       | 7194/30196 [15:05<44:32,  8.61it/s]

 24%|██▍       | 7195/30196 [15:05<43:41,  8.77it/s]

 24%|██▍       | 7196/30196 [15:05<45:31,  8.42it/s]

 24%|██▍       | 7198/30196 [15:05<43:42,  8.77it/s]

 24%|██▍       | 7200/30196 [15:05<43:30,  8.81it/s]

 24%|██▍       | 7201/30196 [15:06<45:05,  8.50it/s]

 24%|██▍       | 7203/30196 [15:06<42:06,  9.10it/s]

 24%|██▍       | 7204/30196 [15:06<46:44,  8.20it/s]

 24%|██▍       | 7205/30196 [15:06<50:33,  7.58it/s]

 24%|██▍       | 7207/30196 [15:06<38:30,  9.95it/s]

 24%|██▍       | 7209/30196 [15:07<1:21:22,  4.71it/s]

 24%|██▍       | 7211/30196 [15:07<1:05:13,  5.87it/s]

 24%|██▍       | 7212/30196 [15:07<1:05:11,  5.88it/s]

 24%|██▍       | 7213/30196 [15:08<1:04:53,  5.90it/s]

 24%|██▍       | 7214/30196 [15:08<1:05:22,  5.86it/s]

 24%|██▍       | 7216/30196 [15:08<47:20,  8.09it/s]

 24%|██▍       | 7218/30196 [15:08<48:47,  7.85it/s]

 24%|██▍       | 7220/30196 [15:08<42:53,  8.93it/s]

 24%|██▍       | 7222/30196 [15:08<45:01,  8.50it/s]

 24%|██▍       | 7223/30196 [15:09<55:30,  6.90it/s]

 24%|██▍       | 7225/30196 [15:09<44:45,  8.55it/s]

 24%|██▍       | 7227/30196 [15:09<45:14,  8.46it/s]

 24%|██▍       | 7228/30196 [15:09<47:20,  8.08it/s]

 24%|██▍       | 7229/30196 [15:09<51:45,  7.40it/s]

 24%|██▍       | 7230/30196 [15:10<51:32,  7.43it/s]

 24%|██▍       | 7231/30196 [15:10<51:07,  7.49it/s]

 24%|██▍       | 7232/30196 [15:10<50:51,  7.53it/s]

 24%|██▍       | 7234/30196 [15:10<48:20,  7.92it/s]

 24%|██▍       | 7235/30196 [15:10<57:12,  6.69it/s]

 24%|██▍       | 7236/30196 [15:10<58:48,  6.51it/s]

 24%|██▍       | 7237/30196 [15:11<1:04:56,  5.89it/s]

 24%|██▍       | 7238/30196 [15:11<1:04:19,  5.95it/s]

 24%|██▍       | 7240/30196 [15:11<48:47,  7.84it/s]

 24%|██▍       | 7241/30196 [15:11<49:03,  7.80it/s]

 24%|██▍       | 7243/30196 [15:11<44:30,  8.60it/s]

 24%|██▍       | 7245/30196 [15:12<46:13,  8.27it/s]

 24%|██▍       | 7247/30196 [15:12<43:55,  8.71it/s]

 24%|██▍       | 7248/30196 [15:12<43:37,  8.77it/s]

 24%|██▍       | 7249/30196 [15:12<45:36,  8.39it/s]

 24%|██▍       | 7250/30196 [15:12<47:37,  8.03it/s]

 24%|██▍       | 7251/30196 [15:12<51:40,  7.40it/s]

 24%|██▍       | 7253/30196 [15:13<46:07,  8.29it/s]

 24%|██▍       | 7255/30196 [15:13<38:09, 10.02it/s]

 24%|██▍       | 7257/30196 [15:13<48:00,  7.96it/s]

 24%|██▍       | 7258/30196 [15:13<49:35,  7.71it/s]

 24%|██▍       | 7259/30196 [15:13<51:07,  7.48it/s]

 24%|██▍       | 7260/30196 [15:14<1:02:18,  6.13it/s]

 24%|██▍       | 7261/30196 [15:14<1:08:54,  5.55it/s]

 24%|██▍       | 7263/30196 [15:14<57:34,  6.64it/s]

 24%|██▍       | 7264/30196 [15:14<59:30,  6.42it/s]

 24%|██▍       | 7266/30196 [15:14<45:56,  8.32it/s]

 24%|██▍       | 7267/30196 [15:14<46:47,  8.17it/s]

 24%|██▍       | 7269/30196 [15:15<42:57,  8.90it/s]

 24%|██▍       | 7271/30196 [15:15<43:26,  8.79it/s]

 24%|██▍       | 7273/30196 [15:15<41:38,  9.17it/s]

 24%|██▍       | 7274/30196 [15:15<41:36,  9.18it/s]

 24%|██▍       | 7275/30196 [15:15<44:11,  8.64it/s]

 24%|██▍       | 7276/30196 [15:15<43:35,  8.76it/s]

 24%|██▍       | 7278/30196 [15:16<54:45,  6.97it/s]

 24%|██▍       | 7279/30196 [15:16<57:21,  6.66it/s]

 24%|██▍       | 7280/30196 [15:16<1:04:01,  5.97it/s]

 24%|██▍       | 7281/30196 [15:16<1:01:56,  6.17it/s]

 24%|██▍       | 7283/30196 [15:17<1:03:59,  5.97it/s]

 24%|██▍       | 7285/30196 [15:17<55:21,  6.90it/s]

 24%|██▍       | 7286/30196 [15:17<57:45,  6.61it/s]

 24%|██▍       | 7288/30196 [15:17<45:31,  8.39it/s]

 24%|██▍       | 7290/30196 [15:18<1:31:38,  4.17it/s]

 24%|██▍       | 7293/30196 [15:19<1:11:32,  5.34it/s]

 24%|██▍       | 7296/30196 [15:19<50:55,  7.50it/s]

 24%|██▍       | 7298/30196 [15:19<50:48,  7.51it/s]

 24%|██▍       | 7300/30196 [15:19<54:47,  6.96it/s]

 24%|██▍       | 7302/30196 [15:19<47:12,  8.08it/s]

 24%|██▍       | 7304/30196 [15:20<52:15,  7.30it/s]

 24%|██▍       | 7305/30196 [15:20<52:11,  7.31it/s]

 24%|██▍       | 7306/30196 [15:20<50:10,  7.60it/s]

 24%|██▍       | 7307/30196 [15:20<50:55,  7.49it/s]

 24%|██▍       | 7309/30196 [15:20<46:29,  8.20it/s]

 24%|██▍       | 7310/30196 [15:21<51:10,  7.45it/s]

 24%|██▍       | 7312/30196 [15:21<40:12,  9.49it/s]

 24%|██▍       | 7314/30196 [15:21<51:24,  7.42it/s]

 24%|██▍       | 7315/30196 [15:21<49:06,  7.77it/s]

 24%|██▍       | 7316/30196 [15:21<55:51,  6.83it/s]

 24%|██▍       | 7317/30196 [15:22<1:07:14,  5.67it/s]

 24%|██▍       | 7318/30196 [15:22<1:00:13,  6.33it/s]

 24%|██▍       | 7320/30196 [15:22<47:10,  8.08it/s]

 24%|██▍       | 7322/30196 [15:22<45:17,  8.42it/s]

 24%|██▍       | 7323/30196 [15:22<46:40,  8.17it/s]

 24%|██▍       | 7324/30196 [15:22<47:25,  8.04it/s]

 24%|██▍       | 7326/30196 [15:23<44:26,  8.58it/s]

 24%|██▍       | 7327/30196 [15:23<43:52,  8.69it/s]

 24%|██▍       | 7329/30196 [15:23<42:10,  9.03it/s]

 24%|██▍       | 7330/30196 [15:23<51:18,  7.43it/s]

 24%|██▍       | 7332/30196 [15:23<39:33,  9.63it/s]

 24%|██▍       | 7334/30196 [15:23<37:03, 10.28it/s]

 24%|██▍       | 7336/30196 [15:24<37:42, 10.10it/s]

 24%|██▍       | 7338/30196 [15:24<34:49, 10.94it/s]

 24%|██▍       | 7340/30196 [15:24<36:47, 10.36it/s]

 24%|██▍       | 7342/30196 [15:24<38:48,  9.82it/s]

 24%|██▍       | 7344/30196 [15:24<38:47,  9.82it/s]

 24%|██▍       | 7346/30196 [15:25<37:20, 10.20it/s]

 24%|██▍       | 7348/30196 [15:25<41:23,  9.20it/s]

 24%|██▍       | 7350/30196 [15:25<36:45, 10.36it/s]

 24%|██▍       | 7352/30196 [15:25<40:46,  9.34it/s]

 24%|██▍       | 7354/30196 [15:26<46:36,  8.17it/s]

 24%|██▍       | 7356/30196 [15:26<44:38,  8.53it/s]

 24%|██▍       | 7357/30196 [15:26<48:56,  7.78it/s]

 24%|██▍       | 7358/30196 [15:26<47:30,  8.01it/s]

 24%|██▍       | 7359/30196 [15:26<50:57,  7.47it/s]

 24%|██▍       | 7360/30196 [15:26<1:00:13,  6.32it/s]

 24%|██▍       | 7362/30196 [15:27<47:21,  8.03it/s]

 24%|██▍       | 7364/30196 [15:27<37:58, 10.02it/s]

 24%|██▍       | 7366/30196 [15:27<44:38,  8.52it/s]

 24%|██▍       | 7367/30196 [15:27<48:55,  7.78it/s]

 24%|██▍       | 7368/30196 [15:27<49:11,  7.74it/s]

 24%|██▍       | 7370/30196 [15:28<46:33,  8.17it/s]

 24%|██▍       | 7372/30196 [15:28<38:00, 10.01it/s]

 24%|██▍       | 7374/30196 [15:28<35:13, 10.80it/s]

 24%|██▍       | 7376/30196 [15:28<35:56, 10.58it/s]

 24%|██▍       | 7378/30196 [15:29<1:15:42,  5.02it/s]

 24%|██▍       | 7380/30196 [15:29<1:03:47,  5.96it/s]

 24%|██▍       | 7381/30196 [15:29<1:01:34,  6.17it/s]

 24%|██▍       | 7382/30196 [15:29<57:04,  6.66it/s]

 24%|██▍       | 7383/30196 [15:29<53:04,  7.16it/s]

 24%|██▍       | 7384/30196 [15:29<49:38,  7.66it/s]

 24%|██▍       | 7385/30196 [15:30<50:41,  7.50it/s]

 24%|██▍       | 7386/30196 [15:30<48:19,  7.87it/s]

 24%|██▍       | 7387/30196 [15:30<1:01:54,  6.14it/s]

 24%|██▍       | 7389/30196 [15:30<44:16,  8.59it/s]

 24%|██▍       | 7391/30196 [15:30<46:10,  8.23it/s]

 24%|██▍       | 7393/30196 [15:30<36:52, 10.30it/s]

 24%|██▍       | 7395/30196 [15:31<43:41,  8.70it/s]

 24%|██▍       | 7397/30196 [15:31<45:54,  8.28it/s]

 24%|██▍       | 7398/30196 [15:31<49:11,  7.73it/s]

 25%|██▍       | 7399/30196 [15:31<49:17,  7.71it/s]

 25%|██▍       | 7400/30196 [15:31<47:34,  7.99it/s]

 25%|██▍       | 7401/30196 [15:32<48:07,  7.89it/s]

 25%|██▍       | 7402/30196 [15:32<45:55,  8.27it/s]

 25%|██▍       | 7404/30196 [15:32<40:36,  9.35it/s]

 25%|██▍       | 7406/30196 [15:32<33:10, 11.45it/s]

 25%|██▍       | 7408/30196 [15:32<44:03,  8.62it/s]

 25%|██▍       | 7410/30196 [15:33<49:45,  7.63it/s]

 25%|██▍       | 7411/30196 [15:33<52:34,  7.22it/s]

 25%|██▍       | 7412/30196 [15:33<1:00:01,  6.33it/s]

 25%|██▍       | 7413/30196 [15:33<58:00,  6.55it/s]

 25%|██▍       | 7415/30196 [15:33<43:33,  8.72it/s]

 25%|██▍       | 7417/30196 [15:34<43:38,  8.70it/s]

 25%|██▍       | 7419/30196 [15:34<43:13,  8.78it/s]

 25%|██▍       | 7420/30196 [15:34<45:41,  8.31it/s]

 25%|██▍       | 7421/30196 [15:34<44:50,  8.47it/s]

 25%|██▍       | 7422/30196 [15:34<45:56,  8.26it/s]

 25%|██▍       | 7423/30196 [15:34<44:46,  8.48it/s]

 25%|██▍       | 7424/30196 [15:34<43:35,  8.71it/s]

 25%|██▍       | 7425/30196 [15:34<46:52,  8.10it/s]

 25%|██▍       | 7426/30196 [15:35<48:49,  7.77it/s]

 25%|██▍       | 7427/30196 [15:35<49:27,  7.67it/s]

 25%|██▍       | 7428/30196 [15:35<49:44,  7.63it/s]

 25%|██▍       | 7429/30196 [15:35<50:14,  7.55it/s]

 25%|██▍       | 7431/30196 [15:35<43:56,  8.64it/s]

 25%|██▍       | 7433/30196 [15:35<36:20, 10.44it/s]

 25%|██▍       | 7435/30196 [15:36<41:26,  9.16it/s]

 25%|██▍       | 7437/30196 [15:36<37:34, 10.09it/s]

 25%|██▍       | 7439/30196 [15:36<32:51, 11.54it/s]

 25%|██▍       | 7441/30196 [15:36<32:12, 11.78it/s]

 25%|██▍       | 7443/30196 [15:36<32:39, 11.61it/s]

 25%|██▍       | 7445/30196 [15:37<39:04,  9.70it/s]

 25%|██▍       | 7447/30196 [15:37<39:50,  9.52it/s]

 25%|██▍       | 7449/30196 [15:37<39:05,  9.70it/s]

 25%|██▍       | 7451/30196 [15:37<43:13,  8.77it/s]

 25%|██▍       | 7453/30196 [15:37<43:19,  8.75it/s]

 25%|██▍       | 7454/30196 [15:38<44:45,  8.47it/s]

 25%|██▍       | 7455/30196 [15:38<45:48,  8.27it/s]

 25%|██▍       | 7457/30196 [15:38<40:40,  9.32it/s]

 25%|██▍       | 7458/30196 [15:38<40:29,  9.36it/s]

 25%|██▍       | 7459/30196 [15:38<45:41,  8.29it/s]

 25%|██▍       | 7460/30196 [15:38<50:08,  7.56it/s]

 25%|██▍       | 7462/30196 [15:38<40:58,  9.25it/s]

 25%|██▍       | 7464/30196 [15:39<38:24,  9.86it/s]

 25%|██▍       | 7466/30196 [15:39<36:59, 10.24it/s]

 25%|██▍       | 7468/30196 [15:39<39:34,  9.57it/s]

 25%|██▍       | 7470/30196 [15:39<37:52, 10.00it/s]

 25%|██▍       | 7472/30196 [15:39<33:55, 11.16it/s]

 25%|██▍       | 7474/30196 [15:40<34:51, 10.86it/s]

 25%|██▍       | 7476/30196 [15:40<38:44,  9.77it/s]

 25%|██▍       | 7478/30196 [15:40<35:29, 10.67it/s]

 25%|██▍       | 7480/30196 [15:40<37:52, 10.00it/s]

 25%|██▍       | 7482/30196 [15:40<40:13,  9.41it/s]

 25%|██▍       | 7484/30196 [15:41<39:30,  9.58it/s]

 25%|██▍       | 7485/30196 [15:41<39:32,  9.57it/s]

 25%|██▍       | 7487/30196 [15:41<40:14,  9.41it/s]

 25%|██▍       | 7488/30196 [15:41<44:51,  8.44it/s]

 25%|██▍       | 7490/30196 [15:41<43:37,  8.68it/s]

 25%|██▍       | 7491/30196 [15:42<52:26,  7.22it/s]

 25%|██▍       | 7492/30196 [15:42<53:14,  7.11it/s]

 25%|██▍       | 7494/30196 [15:42<42:10,  8.97it/s]

 25%|██▍       | 7495/30196 [15:42<44:40,  8.47it/s]

 25%|██▍       | 7497/30196 [15:42<43:41,  8.66it/s]

 25%|██▍       | 7498/30196 [15:42<46:12,  8.19it/s]

 25%|██▍       | 7501/30196 [15:43<37:35, 10.06it/s]

 25%|██▍       | 7502/30196 [15:43<40:07,  9.43it/s]

 25%|██▍       | 7504/30196 [15:43<36:25, 10.38it/s]

 25%|██▍       | 7506/30196 [15:43<35:26, 10.67it/s]

 25%|██▍       | 7508/30196 [15:43<36:47, 10.28it/s]

 25%|██▍       | 7510/30196 [15:43<36:40, 10.31it/s]

 25%|██▍       | 7512/30196 [15:44<32:10, 11.75it/s]

 25%|██▍       | 7514/30196 [15:44<40:10,  9.41it/s]

 25%|██▍       | 7516/30196 [15:44<39:36,  9.54it/s]

 25%|██▍       | 7518/30196 [15:44<44:29,  8.50it/s]

 25%|██▍       | 7520/30196 [15:45<45:25,  8.32it/s]

 25%|██▍       | 7522/30196 [15:45<38:20,  9.86it/s]

 25%|██▍       | 7524/30196 [15:45<34:32, 10.94it/s]

 25%|██▍       | 7526/30196 [15:45<41:29,  9.11it/s]

 25%|██▍       | 7528/30196 [15:46<45:39,  8.28it/s]

 25%|██▍       | 7529/30196 [15:46<49:15,  7.67it/s]

 25%|██▍       | 7531/30196 [15:46<49:50,  7.58it/s]

 25%|██▍       | 7532/30196 [15:46<55:44,  6.78it/s]

 25%|██▍       | 7534/30196 [15:47<1:40:22,  3.76it/s]

 25%|██▍       | 7536/30196 [15:47<1:13:57,  5.11it/s]

 25%|██▍       | 7537/30196 [15:47<1:09:30,  5.43it/s]

 25%|██▍       | 7539/30196 [15:48<53:46,  7.02it/s]

 25%|██▍       | 7541/30196 [15:48<44:19,  8.52it/s]

 25%|██▍       | 7543/30196 [15:48<48:08,  7.84it/s]

 25%|██▍       | 7545/30196 [15:48<51:37,  7.31it/s]

 25%|██▍       | 7546/30196 [15:48<49:47,  7.58it/s]

 25%|██▍       | 7548/30196 [15:49<55:14,  6.83it/s]

 25%|██▌       | 7549/30196 [15:49<52:11,  7.23it/s]

 25%|██▌       | 7551/30196 [15:49<44:23,  8.50it/s]

 25%|██▌       | 7552/30196 [15:49<45:41,  8.26it/s]

 25%|██▌       | 7553/30196 [15:49<58:51,  6.41it/s]

 25%|██▌       | 7555/30196 [15:50<49:55,  7.56it/s]

 25%|██▌       | 7557/30196 [15:50<42:49,  8.81it/s]

 25%|██▌       | 7559/30196 [15:50<42:38,  8.85it/s]

 25%|██▌       | 7561/30196 [15:50<41:35,  9.07it/s]

 25%|██▌       | 7562/30196 [15:50<42:09,  8.95it/s]

 25%|██▌       | 7563/30196 [15:50<42:03,  8.97it/s]

 25%|██▌       | 7565/30196 [15:51<47:17,  7.98it/s]

 25%|██▌       | 7566/30196 [15:51<51:43,  7.29it/s]

 25%|██▌       | 7568/30196 [15:51<48:51,  7.72it/s]

 25%|██▌       | 7569/30196 [15:51<52:07,  7.23it/s]

 25%|██▌       | 7570/30196 [15:51<55:41,  6.77it/s]

 25%|██▌       | 7571/30196 [15:52<55:41,  6.77it/s]

 25%|██▌       | 7573/30196 [15:52<43:06,  8.74it/s]

 25%|██▌       | 7575/30196 [15:52<37:05, 10.16it/s]

 25%|██▌       | 7577/30196 [15:52<32:43, 11.52it/s]

 25%|██▌       | 7579/30196 [15:52<36:37, 10.29it/s]

 25%|██▌       | 7581/30196 [15:52<36:47, 10.24it/s]

 25%|██▌       | 7583/30196 [15:53<45:32,  8.28it/s]

 25%|██▌       | 7585/30196 [15:53<40:19,  9.35it/s]

 25%|██▌       | 7587/30196 [15:53<42:14,  8.92it/s]

 25%|██▌       | 7589/30196 [15:53<39:29,  9.54it/s]

 25%|██▌       | 7591/30196 [15:54<42:49,  8.80it/s]

 25%|██▌       | 7592/30196 [15:54<44:06,  8.54it/s]

 25%|██▌       | 7593/30196 [15:54<45:14,  8.33it/s]

 25%|██▌       | 7594/30196 [15:54<46:07,  8.17it/s]

 25%|██▌       | 7596/30196 [15:54<40:17,  9.35it/s]

 25%|██▌       | 7598/30196 [15:54<39:01,  9.65it/s]

 25%|██▌       | 7599/30196 [15:55<41:54,  8.99it/s]

 25%|██▌       | 7600/30196 [15:55<51:59,  7.24it/s]

 25%|██▌       | 7601/30196 [15:55<48:56,  7.69it/s]

 25%|██▌       | 7602/30196 [15:55<50:35,  7.44it/s]

 25%|██▌       | 7603/30196 [15:55<47:35,  7.91it/s]

 25%|██▌       | 7604/30196 [15:55<51:38,  7.29it/s]

 25%|██▌       | 7605/30196 [15:55<54:26,  6.92it/s]

 25%|██▌       | 7607/30196 [15:56<40:21,  9.33it/s]

 25%|██▌       | 7608/30196 [15:56<43:23,  8.68it/s]

 25%|██▌       | 7610/30196 [15:56<43:16,  8.70it/s]

 25%|██▌       | 7611/30196 [15:56<48:11,  7.81it/s]

 25%|██▌       | 7613/30196 [15:56<37:35, 10.01it/s]

 25%|██▌       | 7615/30196 [15:57<43:03,  8.74it/s]

 25%|██▌       | 7617/30196 [15:57<38:24,  9.80it/s]

 25%|██▌       | 7619/30196 [15:57<45:00,  8.36it/s]

 25%|██▌       | 7620/30196 [15:57<48:48,  7.71it/s]

 25%|██▌       | 7621/30196 [15:57<50:10,  7.50it/s]

 25%|██▌       | 7622/30196 [15:57<48:09,  7.81it/s]

 25%|██▌       | 7623/30196 [15:58<46:03,  8.17it/s]

 25%|██▌       | 7625/30196 [15:58<36:27, 10.32it/s]

 25%|██▌       | 7627/30196 [15:58<36:15, 10.37it/s]

 25%|██▌       | 7629/30196 [15:58<49:58,  7.53it/s]

 25%|██▌       | 7631/30196 [15:58<44:12,  8.51it/s]

 25%|██▌       | 7633/30196 [15:59<43:51,  8.57it/s]

 25%|██▌       | 7635/30196 [15:59<45:33,  8.25it/s]

 25%|██▌       | 7637/30196 [15:59<41:05,  9.15it/s]

 25%|██▌       | 7638/30196 [15:59<43:36,  8.62it/s]

 25%|██▌       | 7639/30196 [15:59<44:46,  8.40it/s]

 25%|██▌       | 7641/30196 [16:00<40:34,  9.27it/s]

 25%|██▌       | 7642/30196 [16:00<43:40,  8.61it/s]

 25%|██▌       | 7643/30196 [16:00<47:54,  7.85it/s]

 25%|██▌       | 7645/30196 [16:00<46:53,  8.02it/s]

 25%|██▌       | 7646/30196 [16:00<45:15,  8.30it/s]

 25%|██▌       | 7647/30196 [16:00<54:09,  6.94it/s]

 25%|██▌       | 7649/30196 [16:01<46:50,  8.02it/s]

 25%|██▌       | 7651/30196 [16:01<38:50,  9.68it/s]

 25%|██▌       | 7653/30196 [16:01<41:00,  9.16it/s]

 25%|██▌       | 7655/30196 [16:01<40:26,  9.29it/s]

 25%|██▌       | 7657/30196 [16:01<35:43, 10.51it/s]

 25%|██▌       | 7659/30196 [16:02<52:35,  7.14it/s]

 25%|██▌       | 7660/30196 [16:02<54:43,  6.86it/s]

 25%|██▌       | 7661/30196 [16:02<56:33,  6.64it/s]

 25%|██▌       | 7663/30196 [16:02<48:31,  7.74it/s]

 25%|██▌       | 7664/30196 [16:02<49:28,  7.59it/s]

 25%|██▌       | 7665/30196 [16:03<52:26,  7.16it/s]

 25%|██▌       | 7666/30196 [16:03<56:13,  6.68it/s]

 25%|██▌       | 7667/30196 [16:03<52:16,  7.18it/s]

 25%|██▌       | 7669/30196 [16:03<48:13,  7.79it/s]

 25%|██▌       | 7670/30196 [16:03<46:06,  8.14it/s]

 25%|██▌       | 7671/30196 [16:03<47:11,  7.96it/s]

 25%|██▌       | 7673/30196 [16:04<48:25,  7.75it/s]

 25%|██▌       | 7674/30196 [16:04<46:19,  8.10it/s]

 25%|██▌       | 7676/30196 [16:04<37:27, 10.02it/s]

 25%|██▌       | 7678/30196 [16:04<35:25, 10.59it/s]

 25%|██▌       | 7680/30196 [16:04<43:06,  8.70it/s]

 25%|██▌       | 7681/30196 [16:05<46:47,  8.02it/s]

 25%|██▌       | 7683/30196 [16:05<42:49,  8.76it/s]

 25%|██▌       | 7684/30196 [16:05<44:53,  8.36it/s]

 25%|██▌       | 7685/30196 [16:05<46:56,  7.99it/s]

 25%|██▌       | 7686/30196 [16:05<47:25,  7.91it/s]

 25%|██▌       | 7687/30196 [16:05<53:51,  6.97it/s]

 25%|██▌       | 7688/30196 [16:06<1:01:39,  6.08it/s]

 25%|██▌       | 7689/30196 [16:06<1:01:45,  6.07it/s]

 25%|██▌       | 7690/30196 [16:06<1:11:10,  5.27it/s]

 25%|██▌       | 7692/30196 [16:06<55:49,  6.72it/s]

 25%|██▌       | 7694/30196 [16:06<46:12,  8.12it/s]

 25%|██▌       | 7695/30196 [16:07<50:24,  7.44it/s]

 25%|██▌       | 7697/30196 [16:07<40:17,  9.31it/s]

 25%|██▌       | 7699/30196 [16:07<41:54,  8.95it/s]

 26%|██▌       | 7700/30196 [16:07<52:56,  7.08it/s]

 26%|██▌       | 7701/30196 [16:07<52:28,  7.15it/s]

 26%|██▌       | 7702/30196 [16:07<51:36,  7.27it/s]

 26%|██▌       | 7703/30196 [16:08<54:32,  6.87it/s]

 26%|██▌       | 7704/30196 [16:08<54:00,  6.94it/s]

 26%|██▌       | 7706/30196 [16:08<49:05,  7.63it/s]

 26%|██▌       | 7707/30196 [16:08<52:34,  7.13it/s]

 26%|██▌       | 7708/30196 [16:08<52:34,  7.13it/s]

 26%|██▌       | 7710/30196 [16:09<52:38,  7.12it/s]

 26%|██▌       | 7711/30196 [16:09<52:42,  7.11it/s]

 26%|██▌       | 7713/30196 [16:09<46:20,  8.08it/s]

 26%|██▌       | 7715/30196 [16:09<56:31,  6.63it/s]

 26%|██▌       | 7717/30196 [16:09<49:42,  7.54it/s]

 26%|██▌       | 7719/30196 [16:10<46:56,  7.98it/s]

 26%|██▌       | 7721/30196 [16:10<42:45,  8.76it/s]

 26%|██▌       | 7722/30196 [16:10<44:34,  8.40it/s]

 26%|██▌       | 7723/30196 [16:10<45:45,  8.18it/s]

 26%|██▌       | 7724/30196 [16:10<1:00:13,  6.22it/s]

 26%|██▌       | 7725/30196 [16:11<55:29,  6.75it/s]

 26%|██▌       | 7726/30196 [16:11<53:43,  6.97it/s]

 26%|██▌       | 7727/30196 [16:11<56:05,  6.68it/s]

 26%|██▌       | 7728/30196 [16:11<1:03:36,  5.89it/s]

 26%|██▌       | 7729/30196 [16:11<57:16,  6.54it/s]

 26%|██▌       | 7730/30196 [16:11<52:34,  7.12it/s]

 26%|██▌       | 7732/30196 [16:11<47:14,  7.93it/s]

 26%|██▌       | 7734/30196 [16:12<39:07,  9.57it/s]

 26%|██▌       | 7736/30196 [16:12<34:43, 10.78it/s]

 26%|██▌       | 7738/30196 [16:12<36:13, 10.33it/s]

 26%|██▌       | 7740/30196 [16:12<37:18, 10.03it/s]

 26%|██▌       | 7742/30196 [16:12<43:23,  8.62it/s]

 26%|██▌       | 7743/30196 [16:13<42:37,  8.78it/s]

 26%|██▌       | 7745/30196 [16:13<39:36,  9.45it/s]

 26%|██▌       | 7747/30196 [16:13<41:40,  8.98it/s]

 26%|██▌       | 7748/30196 [16:13<43:17,  8.64it/s]

 26%|██▌       | 7750/30196 [16:13<42:41,  8.76it/s]

 26%|██▌       | 7752/30196 [16:14<39:26,  9.49it/s]

 26%|██▌       | 7753/30196 [16:14<44:04,  8.49it/s]

 26%|██▌       | 7755/30196 [16:14<44:02,  8.49it/s]

 26%|██▌       | 7756/30196 [16:14<45:03,  8.30it/s]

 26%|██▌       | 7757/30196 [16:14<44:10,  8.46it/s]

 26%|██▌       | 7758/30196 [16:14<46:45,  8.00it/s]

 26%|██▌       | 7759/30196 [16:15<50:58,  7.34it/s]

 26%|██▌       | 7760/30196 [16:15<55:06,  6.78it/s]

 26%|██▌       | 7761/30196 [16:15<1:01:12,  6.11it/s]

 26%|██▌       | 7763/30196 [16:15<45:10,  8.28it/s]

 26%|██▌       | 7765/30196 [16:15<37:17, 10.02it/s]

 26%|██▌       | 7767/30196 [16:15<37:08, 10.07it/s]

 26%|██▌       | 7769/30196 [16:16<34:49, 10.73it/s]

 26%|██▌       | 7771/30196 [16:16<36:53, 10.13it/s]

 26%|██▌       | 7773/30196 [16:16<38:04,  9.82it/s]

 26%|██▌       | 7775/30196 [16:16<37:36,  9.94it/s]

 26%|██▌       | 7777/30196 [16:16<41:02,  9.10it/s]

 26%|██▌       | 7778/30196 [16:17<44:52,  8.33it/s]

 26%|██▌       | 7780/30196 [16:17<46:11,  8.09it/s]

 26%|██▌       | 7782/30196 [16:17<43:11,  8.65it/s]

 26%|██▌       | 7783/30196 [16:17<44:37,  8.37it/s]

 26%|██▌       | 7784/30196 [16:17<46:22,  8.05it/s]

 26%|██▌       | 7786/30196 [16:18<41:50,  8.93it/s]

 26%|██▌       | 7788/30196 [16:18<40:39,  9.18it/s]

 26%|██▌       | 7789/30196 [16:18<43:36,  8.56it/s]

 26%|██▌       | 7790/30196 [16:18<1:09:30,  5.37it/s]

 26%|██▌       | 7791/30196 [16:18<1:04:58,  5.75it/s]

 26%|██▌       | 7792/30196 [16:19<1:05:19,  5.72it/s]

 26%|██▌       | 7794/30196 [16:19<1:00:19,  6.19it/s]

 26%|██▌       | 7796/30196 [16:19<50:36,  7.38it/s]

 26%|██▌       | 7798/30196 [16:19<39:29,  9.45it/s]

 26%|██▌       | 7800/30196 [16:19<36:52, 10.12it/s]

 26%|██▌       | 7802/30196 [16:20<38:19,  9.74it/s]

 26%|██▌       | 7804/30196 [16:20<33:42, 11.07it/s]

 26%|██▌       | 7806/30196 [16:20<48:40,  7.67it/s]

 26%|██▌       | 7808/30196 [16:20<46:28,  8.03it/s]

 26%|██▌       | 7809/30196 [16:21<49:42,  7.51it/s]

 26%|██▌       | 7810/30196 [16:21<1:05:18,  5.71it/s]

 26%|██▌       | 7811/30196 [16:21<1:01:53,  6.03it/s]

 26%|██▌       | 7812/30196 [16:21<59:35,  6.26it/s]

 26%|██▌       | 7813/30196 [16:21<1:02:48,  5.94it/s]

 26%|██▌       | 7815/30196 [16:21<46:29,  8.02it/s]

 26%|██▌       | 7816/30196 [16:22<53:34,  6.96it/s]

 26%|██▌       | 7817/30196 [16:22<1:03:50,  5.84it/s]

 26%|██▌       | 7819/30196 [16:22<52:48,  7.06it/s]

 26%|██▌       | 7820/30196 [16:22<49:42,  7.50it/s]

 26%|██▌       | 7822/30196 [16:22<44:08,  8.45it/s]

 26%|██▌       | 7824/30196 [16:23<39:21,  9.47it/s]

 26%|██▌       | 7825/30196 [16:23<41:06,  9.07it/s]

 26%|██▌       | 7826/30196 [16:23<53:07,  7.02it/s]

 26%|██▌       | 7829/30196 [16:23<40:35,  9.18it/s]

 26%|██▌       | 7832/30196 [16:23<36:42, 10.15it/s]

 26%|██▌       | 7834/30196 [16:24<36:27, 10.22it/s]

 26%|██▌       | 7836/30196 [16:24<41:01,  9.08it/s]

 26%|██▌       | 7837/30196 [16:24<42:19,  8.80it/s]

 26%|██▌       | 7838/30196 [16:24<46:21,  8.04it/s]

 26%|██▌       | 7840/30196 [16:24<46:47,  7.96it/s]

 26%|██▌       | 7841/30196 [16:25<53:17,  6.99it/s]

 26%|██▌       | 7842/30196 [16:25<53:03,  7.02it/s]

 26%|██▌       | 7844/30196 [16:25<44:29,  8.37it/s]

 26%|██▌       | 7845/30196 [16:25<46:11,  8.06it/s]

 26%|██▌       | 7846/30196 [16:25<49:55,  7.46it/s]

 26%|██▌       | 7848/30196 [16:26<45:18,  8.22it/s]

 26%|██▌       | 7850/30196 [16:26<36:46, 10.13it/s]

 26%|██▌       | 7852/30196 [16:26<37:39,  9.89it/s]

 26%|██▌       | 7854/30196 [16:26<33:02, 11.27it/s]

 26%|██▌       | 7856/30196 [16:26<40:39,  9.16it/s]

 26%|██▌       | 7858/30196 [16:26<37:25,  9.95it/s]

 26%|██▌       | 7860/30196 [16:27<34:06, 10.91it/s]

 26%|██▌       | 7862/30196 [16:27<39:48,  9.35it/s]

 26%|██▌       | 7864/30196 [16:27<45:24,  8.20it/s]

 26%|██▌       | 7865/30196 [16:27<44:17,  8.40it/s]

 26%|██▌       | 7866/30196 [16:27<43:34,  8.54it/s]

 26%|██▌       | 7867/30196 [16:28<55:42,  6.68it/s]

 26%|██▌       | 7868/30196 [16:28<54:52,  6.78it/s]

 26%|██▌       | 7870/30196 [16:28<48:15,  7.71it/s]

 26%|██▌       | 7871/30196 [16:28<49:16,  7.55it/s]

 26%|██▌       | 7872/30196 [16:28<47:12,  7.88it/s]

 26%|██▌       | 7873/30196 [16:28<47:38,  7.81it/s]

 26%|██▌       | 7874/30196 [16:29<52:51,  7.04it/s]

 26%|██▌       | 7875/30196 [16:29<1:08:07,  5.46it/s]

 26%|██▌       | 7876/30196 [16:29<1:04:15,  5.79it/s]

 26%|██▌       | 7877/30196 [16:29<1:01:35,  6.04it/s]

 26%|██▌       | 7879/30196 [16:29<47:07,  7.89it/s]

 26%|██▌       | 7881/30196 [16:30<45:41,  8.14it/s]

 26%|██▌       | 7883/30196 [16:30<1:00:04,  6.19it/s]

 26%|██▌       | 7884/30196 [16:30<1:03:37,  5.84it/s]

 26%|██▌       | 7886/30196 [16:30<47:12,  7.88it/s]

 26%|██▌       | 7888/30196 [16:31<54:33,  6.82it/s]

 26%|██▌       | 7889/30196 [16:31<59:30,  6.25it/s]

 26%|██▌       | 7890/30196 [16:31<1:03:22,  5.87it/s]

 26%|██▌       | 7891/30196 [16:31<59:49,  6.21it/s]

 26%|██▌       | 7892/30196 [16:31<1:01:03,  6.09it/s]

 26%|██▌       | 7893/30196 [16:32<55:44,  6.67it/s]

 26%|██▌       | 7894/30196 [16:32<57:39,  6.45it/s]

 26%|██▌       | 7896/30196 [16:32<48:15,  7.70it/s]

 26%|██▌       | 7897/30196 [16:32<1:15:44,  4.91it/s]

 26%|██▌       | 7899/30196 [16:32<54:51,  6.77it/s]

 26%|██▌       | 7902/30196 [16:33<49:45,  7.47it/s]

 26%|██▌       | 7903/30196 [16:33<50:11,  7.40it/s]

 26%|██▌       | 7904/30196 [16:33<1:00:59,  6.09it/s]

 26%|██▌       | 7905/30196 [16:33<58:14,  6.38it/s]

 26%|██▌       | 7906/30196 [16:33<56:47,  6.54it/s]

 26%|██▌       | 7908/30196 [16:34<44:57,  8.26it/s]

 26%|██▌       | 7910/30196 [16:34<42:57,  8.65it/s]

 26%|██▌       | 7912/30196 [16:34<44:31,  8.34it/s]

 26%|██▌       | 7913/30196 [16:34<43:25,  8.55it/s]

 26%|██▌       | 7914/30196 [16:34<42:48,  8.67it/s]

 26%|██▌       | 7915/30196 [16:34<44:48,  8.29it/s]

 26%|██▌       | 7916/30196 [16:35<43:42,  8.50it/s]

 26%|██▌       | 7918/30196 [16:35<41:27,  8.96it/s]

 26%|██▌       | 7920/30196 [16:35<34:42, 10.70it/s]

 26%|██▌       | 7922/30196 [16:35<39:30,  9.40it/s]

 26%|██▌       | 7924/30196 [16:36<53:38,  6.92it/s]

 26%|██▌       | 7925/30196 [16:36<52:41,  7.04it/s]

 26%|██▌       | 7926/30196 [16:36<50:06,  7.41it/s]

 26%|██▋       | 7927/30196 [16:36<47:55,  7.74it/s]

 26%|██▋       | 7929/30196 [16:36<45:04,  8.23it/s]

 26%|██▋       | 7931/30196 [16:36<40:31,  9.16it/s]

 26%|██▋       | 7932/30196 [16:36<42:10,  8.80it/s]

 26%|██▋       | 7933/30196 [16:37<51:09,  7.25it/s]

 26%|██▋       | 7935/30196 [16:37<45:07,  8.22it/s]

 26%|██▋       | 7937/30196 [16:37<44:03,  8.42it/s]

 26%|██▋       | 7938/30196 [16:37<45:47,  8.10it/s]

 26%|██▋       | 7939/30196 [16:37<46:29,  7.98it/s]

 26%|██▋       | 7941/30196 [16:38<40:24,  9.18it/s]

 26%|██▋       | 7942/30196 [16:38<53:57,  6.87it/s]

 26%|██▋       | 7943/30196 [16:38<50:23,  7.36it/s]

 26%|██▋       | 7945/30196 [16:38<37:37,  9.86it/s]

 26%|██▋       | 7947/30196 [16:38<40:47,  9.09it/s]

 26%|██▋       | 7949/30196 [16:39<41:59,  8.83it/s]

 26%|██▋       | 7950/30196 [16:39<41:20,  8.97it/s]

 26%|██▋       | 7951/30196 [16:39<46:22,  7.99it/s]

 26%|██▋       | 7952/30196 [16:39<50:19,  7.37it/s]

 26%|██▋       | 7953/30196 [16:39<49:49,  7.44it/s]

 26%|██▋       | 7954/30196 [16:39<50:29,  7.34it/s]

 26%|██▋       | 7956/30196 [16:39<39:40,  9.34it/s]

 26%|██▋       | 7958/30196 [16:40<34:10, 10.84it/s]

 26%|██▋       | 7960/30196 [16:40<34:51, 10.63it/s]

 26%|██▋       | 7962/30196 [16:40<39:52,  9.29it/s]

 26%|██▋       | 7964/30196 [16:40<36:42, 10.10it/s]

 26%|██▋       | 7966/30196 [16:40<34:04, 10.87it/s]

 26%|██▋       | 7968/30196 [16:41<40:25,  9.16it/s]

 26%|██▋       | 7969/30196 [16:41<42:03,  8.81it/s]

 26%|██▋       | 7970/30196 [16:41<43:36,  8.50it/s]

 26%|██▋       | 7971/30196 [16:42<1:27:35,  4.23it/s]

 26%|██▋       | 7972/30196 [16:42<1:51:31,  3.32it/s]

 26%|██▋       | 7973/30196 [16:42<1:33:14,  3.97it/s]

 26%|██▋       | 7974/30196 [16:42<1:26:14,  4.29it/s]

 26%|██▋       | 7975/30196 [16:43<1:50:02,  3.37it/s]

 26%|██▋       | 7976/30196 [16:43<1:30:17,  4.10it/s]

 26%|██▋       | 7977/30196 [16:43<1:24:59,  4.36it/s]

 26%|██▋       | 7979/30196 [16:43<1:01:57,  5.98it/s]

 26%|██▋       | 7981/30196 [16:43<51:51,  7.14it/s]

 26%|██▋       | 7982/30196 [16:44<49:27,  7.49it/s]

 26%|██▋       | 7983/30196 [16:44<49:28,  7.48it/s]

 26%|██▋       | 7984/30196 [16:44<53:19,  6.94it/s]

 26%|██▋       | 7985/30196 [16:44<52:06,  7.10it/s]

 26%|██▋       | 7987/30196 [16:44<45:05,  8.21it/s]

 26%|██▋       | 7988/30196 [16:44<52:48,  7.01it/s]

 26%|██▋       | 7989/30196 [16:45<56:14,  6.58it/s]

 26%|██▋       | 7991/30196 [16:45<51:37,  7.17it/s]

 26%|██▋       | 7992/30196 [16:45<58:35,  6.32it/s]

 26%|██▋       | 7993/30196 [16:45<53:40,  6.89it/s]

 26%|██▋       | 7995/30196 [16:45<48:13,  7.67it/s]

 26%|██▋       | 7997/30196 [16:46<52:07,  7.10it/s]

 26%|██▋       | 7998/30196 [16:46<49:42,  7.44it/s]

 26%|██▋       | 8000/30196 [16:46<40:34,  9.12it/s]

 26%|██▋       | 8001/30196 [16:46<40:36,  9.11it/s]

 27%|██▋       | 8002/30196 [16:46<43:43,  8.46it/s]

 27%|██▋       | 8003/30196 [16:46<45:11,  8.19it/s]

 27%|██▋       | 8005/30196 [16:46<38:02,  9.72it/s]

 27%|██▋       | 8006/30196 [16:47<38:09,  9.69it/s]

 27%|██▋       | 8007/30196 [16:47<42:15,  8.75it/s]

 27%|██▋       | 8009/30196 [16:47<39:30,  9.36it/s]

 27%|██▋       | 8010/30196 [16:47<41:36,  8.89it/s]

 27%|██▋       | 8012/30196 [16:47<35:35, 10.39it/s]

 27%|██▋       | 8014/30196 [16:47<42:35,  8.68it/s]

 27%|██▋       | 8016/30196 [16:48<40:53,  9.04it/s]

 27%|██▋       | 8017/30196 [16:48<1:17:41,  4.76it/s]

 27%|██▋       | 8018/30196 [16:48<1:09:07,  5.35it/s]

 27%|██▋       | 8020/30196 [16:49<51:13,  7.21it/s]

 27%|██▋       | 8022/30196 [16:49<46:00,  8.03it/s]

 27%|██▋       | 8024/30196 [16:49<37:25,  9.88it/s]

 27%|██▋       | 8026/30196 [16:49<44:46,  8.25it/s]

 27%|██▋       | 8028/30196 [16:49<42:03,  8.78it/s]

 27%|██▋       | 8030/30196 [16:50<43:44,  8.45it/s]

 27%|██▋       | 8031/30196 [16:50<45:44,  8.08it/s]

 27%|██▋       | 8032/30196 [16:50<57:21,  6.44it/s]

 27%|██▋       | 8033/30196 [16:50<55:21,  6.67it/s]

 27%|██▋       | 8035/30196 [16:50<49:05,  7.52it/s]

 27%|██▋       | 8037/30196 [16:51<40:52,  9.04it/s]

 27%|██▋       | 8039/30196 [16:51<41:07,  8.98it/s]

 27%|██▋       | 8040/30196 [16:51<42:30,  8.69it/s]

 27%|██▋       | 8042/30196 [16:51<39:38,  9.31it/s]

 27%|██▋       | 8044/30196 [16:51<34:41, 10.64it/s]

 27%|██▋       | 8046/30196 [16:51<37:09,  9.94it/s]

 27%|██▋       | 8048/30196 [16:52<43:43,  8.44it/s]

 27%|██▋       | 8049/30196 [16:52<47:12,  7.82it/s]

 27%|██▋       | 8051/30196 [16:52<41:56,  8.80it/s]

 27%|██▋       | 8052/30196 [16:52<45:48,  8.06it/s]

 27%|██▋       | 8053/30196 [16:52<44:11,  8.35it/s]

 27%|██▋       | 8054/30196 [16:52<43:22,  8.51it/s]

 27%|██▋       | 8055/30196 [16:53<54:22,  6.79it/s]

 27%|██▋       | 8057/30196 [16:53<48:19,  7.64it/s]

 27%|██▋       | 8058/30196 [16:53<51:40,  7.14it/s]

 27%|██▋       | 8059/30196 [16:53<55:35,  6.64it/s]

 27%|██▋       | 8060/30196 [16:53<51:40,  7.14it/s]

 27%|██▋       | 8061/30196 [16:54<52:30,  7.03it/s]

 27%|██▋       | 8064/30196 [16:54<35:09, 10.49it/s]

 27%|██▋       | 8066/30196 [16:54<40:43,  9.06it/s]

 27%|██▋       | 8067/30196 [16:54<51:47,  7.12it/s]

 27%|██▋       | 8069/30196 [16:54<46:12,  7.98it/s]

 27%|██▋       | 8071/30196 [16:55<39:58,  9.23it/s]

 27%|██▋       | 8072/30196 [16:55<45:10,  8.16it/s]

 27%|██▋       | 8073/30196 [16:55<1:19:16,  4.65it/s]

 27%|██▋       | 8074/30196 [16:55<1:09:40,  5.29it/s]

 27%|██▋       | 8075/30196 [16:56<1:07:37,  5.45it/s]

 27%|██▋       | 8077/30196 [16:56<1:12:11,  5.11it/s]

 27%|██▋       | 8078/30196 [16:56<1:04:56,  5.68it/s]

 27%|██▋       | 8079/30196 [16:56<1:12:30,  5.08it/s]

 27%|██▋       | 8080/30196 [16:57<1:04:13,  5.74it/s]

 27%|██▋       | 8081/30196 [16:57<59:50,  6.16it/s]

 27%|██▋       | 8082/30196 [16:57<54:31,  6.76it/s]

 27%|██▋       | 8084/30196 [16:57<42:12,  8.73it/s]

 27%|██▋       | 8085/30196 [16:57<41:47,  8.82it/s]

 27%|██▋       | 8086/30196 [16:57<44:23,  8.30it/s]

 27%|██▋       | 8087/30196 [16:57<43:21,  8.50it/s]

 27%|██▋       | 8088/30196 [16:57<42:35,  8.65it/s]

 27%|██▋       | 8090/30196 [16:58<50:04,  7.36it/s]

 27%|██▋       | 8092/30196 [16:58<42:26,  8.68it/s]

 27%|██▋       | 8094/30196 [16:58<42:55,  8.58it/s]

 27%|██▋       | 8096/30196 [16:58<40:54,  9.00it/s]

 27%|██▋       | 8097/30196 [16:58<44:50,  8.21it/s]

 27%|██▋       | 8098/30196 [16:59<43:54,  8.39it/s]

 27%|██▋       | 8099/30196 [16:59<42:59,  8.57it/s]

 27%|██▋       | 8100/30196 [16:59<42:16,  8.71it/s]

 27%|██▋       | 8101/30196 [16:59<47:17,  7.79it/s]

 27%|██▋       | 8102/30196 [16:59<1:05:47,  5.60it/s]

 27%|██▋       | 8103/30196 [17:00<1:19:17,  4.64it/s]

 27%|██▋       | 8104/30196 [17:00<1:10:48,  5.20it/s]

 27%|██▋       | 8106/30196 [17:00<50:08,  7.34it/s]

 27%|██▋       | 8108/30196 [17:00<39:28,  9.33it/s]

 27%|██▋       | 8110/30196 [17:00<49:04,  7.50it/s]

 27%|██▋       | 8112/30196 [17:01<42:50,  8.59it/s]

 27%|██▋       | 8114/30196 [17:01<45:38,  8.06it/s]

 27%|██▋       | 8116/30196 [17:01<39:04,  9.42it/s]

 27%|██▋       | 8118/30196 [17:01<34:46, 10.58it/s]

 27%|██▋       | 8120/30196 [17:01<33:07, 11.11it/s]

 27%|██▋       | 8122/30196 [17:02<41:53,  8.78it/s]

 27%|██▋       | 8124/30196 [17:02<1:06:17,  5.55it/s]

 27%|██▋       | 8125/30196 [17:02<1:08:32,  5.37it/s]

 27%|██▋       | 8127/30196 [17:03<55:34,  6.62it/s]

 27%|██▋       | 8128/30196 [17:03<54:26,  6.76it/s]

 27%|██▋       | 8129/30196 [17:03<59:39,  6.17it/s]

 27%|██▋       | 8130/30196 [17:03<55:09,  6.67it/s]

 27%|██▋       | 8132/30196 [17:03<49:11,  7.48it/s]

 27%|██▋       | 8134/30196 [17:03<45:08,  8.15it/s]

 27%|██▋       | 8136/30196 [17:04<45:54,  8.01it/s]

 27%|██▋       | 8137/30196 [17:04<47:36,  7.72it/s]

 27%|██▋       | 8138/30196 [17:04<48:09,  7.63it/s]

 27%|██▋       | 8139/30196 [17:04<49:31,  7.42it/s]

 27%|██▋       | 8141/30196 [17:04<41:22,  8.88it/s]

 27%|██▋       | 8142/30196 [17:05<50:22,  7.30it/s]

 27%|██▋       | 8144/30196 [17:05<50:21,  7.30it/s]

 27%|██▋       | 8145/30196 [17:05<48:13,  7.62it/s]

 27%|██▋       | 8146/30196 [17:05<48:10,  7.63it/s]

 27%|██▋       | 8147/30196 [17:05<58:06,  6.32it/s]

 27%|██▋       | 8149/30196 [17:06<55:50,  6.58it/s]

 27%|██▋       | 8151/30196 [17:06<45:43,  8.04it/s]

 27%|██▋       | 8152/30196 [17:06<48:56,  7.51it/s]

 27%|██▋       | 8154/30196 [17:06<48:19,  7.60it/s]

 27%|██▋       | 8156/30196 [17:07<57:04,  6.44it/s]

 27%|██▋       | 8157/30196 [17:07<53:39,  6.85it/s]

 27%|██▋       | 8159/30196 [17:07<46:41,  7.87it/s]

 27%|██▋       | 8161/30196 [17:07<37:27,  9.80it/s]

 27%|██▋       | 8163/30196 [17:07<42:11,  8.71it/s]

 27%|██▋       | 8165/30196 [17:07<35:02, 10.48it/s]

 27%|██▋       | 8167/30196 [17:08<33:56, 10.81it/s]

 27%|██▋       | 8169/30196 [17:08<30:30, 12.03it/s]

 27%|██▋       | 8171/30196 [17:08<31:26, 11.68it/s]

 27%|██▋       | 8173/30196 [17:08<32:47, 11.20it/s]

 27%|██▋       | 8175/30196 [17:08<38:31,  9.53it/s]

 27%|██▋       | 8177/30196 [17:09<37:13,  9.86it/s]

 27%|██▋       | 8179/30196 [17:09<38:42,  9.48it/s]

 27%|██▋       | 8181/30196 [17:09<36:01, 10.19it/s]

 27%|██▋       | 8183/30196 [17:09<35:35, 10.31it/s]

 27%|██▋       | 8185/30196 [17:09<38:47,  9.46it/s]

 27%|██▋       | 8186/30196 [17:09<39:05,  9.38it/s]

 27%|██▋       | 8188/30196 [17:10<39:39,  9.25it/s]

 27%|██▋       | 8190/30196 [17:10<35:17, 10.39it/s]

 27%|██▋       | 8192/30196 [17:10<30:30, 12.02it/s]

 27%|██▋       | 8194/30196 [17:10<38:14,  9.59it/s]

 27%|██▋       | 8196/30196 [17:10<35:26, 10.34it/s]

 27%|██▋       | 8198/30196 [17:11<41:50,  8.76it/s]

 27%|██▋       | 8200/30196 [17:11<40:18,  9.09it/s]

 27%|██▋       | 8202/30196 [17:11<42:22,  8.65it/s]

 27%|██▋       | 8204/30196 [17:11<39:10,  9.36it/s]

 27%|██▋       | 8205/30196 [17:11<40:58,  8.94it/s]

 27%|██▋       | 8206/30196 [17:12<45:09,  8.12it/s]

 27%|██▋       | 8208/30196 [17:12<41:14,  8.89it/s]

 27%|██▋       | 8210/30196 [17:12<42:50,  8.55it/s]

 27%|██▋       | 8211/30196 [17:12<46:38,  7.86it/s]

 27%|██▋       | 8212/30196 [17:12<44:48,  8.18it/s]

 27%|██▋       | 8213/30196 [17:12<43:19,  8.46it/s]

 27%|██▋       | 8215/30196 [17:13<38:49,  9.44it/s]

 27%|██▋       | 8217/30196 [17:13<33:59, 10.78it/s]

 27%|██▋       | 8219/30196 [17:13<36:25, 10.05it/s]

 27%|██▋       | 8221/30196 [17:13<45:14,  8.10it/s]

 27%|██▋       | 8222/30196 [17:13<46:01,  7.96it/s]

 27%|██▋       | 8223/30196 [17:14<44:35,  8.21it/s]

 27%|██▋       | 8224/30196 [17:14<48:29,  7.55it/s]

 27%|██▋       | 8225/30196 [17:14<51:44,  7.08it/s]

 27%|██▋       | 8227/30196 [17:14<42:58,  8.52it/s]

 27%|██▋       | 8228/30196 [17:14<52:36,  6.96it/s]

 27%|██▋       | 8229/30196 [17:14<55:41,  6.57it/s]

 27%|██▋       | 8231/30196 [17:15<47:48,  7.66it/s]

 27%|██▋       | 8232/30196 [17:15<48:13,  7.59it/s]

 27%|██▋       | 8233/30196 [17:15<49:43,  7.36it/s]

 27%|██▋       | 8234/30196 [17:15<47:19,  7.74it/s]

 27%|██▋       | 8236/30196 [17:15<47:49,  7.65it/s]

 27%|██▋       | 8237/30196 [17:15<48:42,  7.51it/s]

 27%|██▋       | 8238/30196 [17:16<48:53,  7.48it/s]

 27%|██▋       | 8239/30196 [17:16<51:59,  7.04it/s]

 27%|██▋       | 8241/30196 [17:16<41:59,  8.71it/s]

 27%|██▋       | 8243/30196 [17:16<36:02, 10.15it/s]

 27%|██▋       | 8245/30196 [17:16<43:05,  8.49it/s]

 27%|██▋       | 8247/30196 [17:17<40:00,  9.14it/s]

 27%|██▋       | 8248/30196 [17:17<43:58,  8.32it/s]

 27%|██▋       | 8249/30196 [17:17<48:12,  7.59it/s]

 27%|██▋       | 8250/30196 [17:17<49:37,  7.37it/s]

 27%|██▋       | 8251/30196 [17:17<49:09,  7.44it/s]

 27%|██▋       | 8253/30196 [17:17<38:11,  9.58it/s]

 27%|██▋       | 8255/30196 [17:18<35:57, 10.17it/s]

 27%|██▋       | 8257/30196 [17:18<46:22,  7.88it/s]

 27%|██▋       | 8260/30196 [17:18<35:48, 10.21it/s]

 27%|██▋       | 8262/30196 [17:18<37:06,  9.85it/s]

 27%|██▋       | 8264/30196 [17:18<32:52, 11.12it/s]

 27%|██▋       | 8266/30196 [17:19<34:33, 10.57it/s]

 27%|██▋       | 8268/30196 [17:19<32:39, 11.19it/s]

 27%|██▋       | 8270/30196 [17:19<33:46, 10.82it/s]

 27%|██▋       | 8272/30196 [17:19<39:06,  9.34it/s]

 27%|██▋       | 8274/30196 [17:20<44:38,  8.18it/s]

 27%|██▋       | 8275/30196 [17:20<43:52,  8.33it/s]

 27%|██▋       | 8276/30196 [17:20<47:45,  7.65it/s]

 27%|██▋       | 8277/30196 [17:20<46:06,  7.92it/s]

 27%|██▋       | 8278/30196 [17:20<47:27,  7.70it/s]

 27%|██▋       | 8280/30196 [17:20<39:48,  9.17it/s]

 27%|██▋       | 8281/30196 [17:20<49:34,  7.37it/s]

 27%|██▋       | 8283/30196 [17:21<48:29,  7.53it/s]

 27%|██▋       | 8285/30196 [17:21<46:27,  7.86it/s]

 27%|██▋       | 8287/30196 [17:21<42:50,  8.52it/s]

 27%|██▋       | 8290/30196 [17:21<32:12, 11.34it/s]

 27%|██▋       | 8292/30196 [17:22<33:44, 10.82it/s]

 27%|██▋       | 8294/30196 [17:22<34:38, 10.54it/s]

 27%|██▋       | 8296/30196 [17:22<43:13,  8.44it/s]

 27%|██▋       | 8297/30196 [17:22<52:35,  6.94it/s]

 27%|██▋       | 8298/30196 [17:23<1:01:28,  5.94it/s]

 27%|██▋       | 8299/30196 [17:23<1:01:24,  5.94it/s]

 27%|██▋       | 8301/30196 [17:23<46:08,  7.91it/s]

 27%|██▋       | 8302/30196 [17:23<49:21,  7.39it/s]

 28%|██▊       | 8304/30196 [17:23<40:11,  9.08it/s]

 28%|██▊       | 8306/30196 [17:23<42:47,  8.52it/s]

 28%|██▊       | 8307/30196 [17:24<51:27,  7.09it/s]

 28%|██▊       | 8309/30196 [17:24<49:30,  7.37it/s]

 28%|██▊       | 8310/30196 [17:24<52:24,  6.96it/s]

 28%|██▊       | 8311/30196 [17:24<49:32,  7.36it/s]

 28%|██▊       | 8313/30196 [17:24<45:00,  8.10it/s]

 28%|██▊       | 8314/30196 [17:25<46:29,  7.84it/s]

 28%|██▊       | 8315/30196 [17:25<45:01,  8.10it/s]

 28%|██▊       | 8317/30196 [17:25<38:53,  9.38it/s]

 28%|██▊       | 8318/30196 [17:25<39:08,  9.31it/s]

 28%|██▊       | 8319/30196 [17:25<44:47,  8.14it/s]

 28%|██▊       | 8321/30196 [17:25<44:01,  8.28it/s]

 28%|██▊       | 8322/30196 [17:25<44:49,  8.13it/s]

 28%|██▊       | 8323/30196 [17:26<45:29,  8.01it/s]

 28%|██▊       | 8324/30196 [17:26<46:59,  7.76it/s]

 28%|██▊       | 8325/30196 [17:26<47:41,  7.64it/s]

 28%|██▊       | 8326/30196 [17:27<1:37:39,  3.73it/s]

 28%|██▊       | 8327/30196 [17:27<1:23:35,  4.36it/s]

 28%|██▊       | 8329/30196 [17:27<1:01:51,  5.89it/s]

 28%|██▊       | 8330/30196 [17:27<59:04,  6.17it/s]

 28%|██▊       | 8331/30196 [17:27<57:02,  6.39it/s]

 28%|██▊       | 8333/30196 [17:27<49:12,  7.41it/s]

 28%|██▊       | 8334/30196 [17:28<52:53,  6.89it/s]

 28%|██▊       | 8336/30196 [17:28<48:39,  7.49it/s]

 28%|██▊       | 8338/30196 [17:28<37:53,  9.62it/s]

 28%|██▊       | 8340/30196 [17:28<33:09, 10.99it/s]

 28%|██▊       | 8342/30196 [17:28<40:52,  8.91it/s]

 28%|██▊       | 8344/30196 [17:29<41:27,  8.78it/s]

 28%|██▊       | 8346/30196 [17:29<41:17,  8.82it/s]

 28%|██▊       | 8348/30196 [17:29<49:40,  7.33it/s]

 28%|██▊       | 8349/30196 [17:29<49:22,  7.37it/s]

 28%|██▊       | 8350/30196 [17:29<47:26,  7.67it/s]

 28%|██▊       | 8351/30196 [17:30<48:20,  7.53it/s]

 28%|██▊       | 8352/30196 [17:30<57:34,  6.32it/s]

 28%|██▊       | 8353/30196 [17:30<59:05,  6.16it/s]

 28%|██▊       | 8355/30196 [17:30<47:32,  7.66it/s]

 28%|██▊       | 8356/30196 [17:30<45:23,  8.02it/s]

 28%|██▊       | 8357/30196 [17:30<49:34,  7.34it/s]

 28%|██▊       | 8358/30196 [17:31<52:59,  6.87it/s]

 28%|██▊       | 8360/30196 [17:31<46:51,  7.77it/s]

 28%|██▊       | 8362/30196 [17:31<41:27,  8.78it/s]

 28%|██▊       | 8363/30196 [17:31<53:23,  6.82it/s]

 28%|██▊       | 8365/30196 [17:31<47:26,  7.67it/s]

 28%|██▊       | 8367/30196 [17:32<40:58,  8.88it/s]

 28%|██▊       | 8368/30196 [17:32<40:46,  8.92it/s]

 28%|██▊       | 8370/30196 [17:32<45:41,  7.96it/s]

 28%|██▊       | 8371/30196 [17:32<47:25,  7.67it/s]

 28%|██▊       | 8372/30196 [17:32<47:33,  7.65it/s]

 28%|██▊       | 8373/30196 [17:32<47:52,  7.60it/s]

 28%|██▊       | 8374/30196 [17:33<49:24,  7.36it/s]

 28%|██▊       | 8375/30196 [17:33<48:53,  7.44it/s]

 28%|██▊       | 8376/30196 [17:33<49:03,  7.41it/s]

 28%|██▊       | 8378/30196 [17:33<42:35,  8.54it/s]

 28%|██▊       | 8380/30196 [17:33<43:48,  8.30it/s]

 28%|██▊       | 8381/30196 [17:33<48:06,  7.56it/s]

 28%|██▊       | 8383/30196 [17:34<42:05,  8.64it/s]

 28%|██▊       | 8384/30196 [17:34<44:05,  8.25it/s]

 28%|██▊       | 8385/30196 [17:34<44:52,  8.10it/s]

 28%|██▊       | 8387/30196 [17:34<37:39,  9.65it/s]

 28%|██▊       | 8388/30196 [17:34<41:16,  8.81it/s]

 28%|██▊       | 8389/30196 [17:34<45:56,  7.91it/s]

 28%|██▊       | 8390/30196 [17:35<58:12,  6.24it/s]

 28%|██▊       | 8392/30196 [17:35<48:52,  7.43it/s]

 28%|██▊       | 8393/30196 [17:35<48:58,  7.42it/s]

 28%|██▊       | 8394/30196 [17:35<52:07,  6.97it/s]

 28%|██▊       | 8395/30196 [17:35<48:55,  7.43it/s]

 28%|██▊       | 8396/30196 [17:35<58:52,  6.17it/s]

 28%|██▊       | 8398/30196 [17:36<53:46,  6.76it/s]

 28%|██▊       | 8399/30196 [17:36<52:16,  6.95it/s]

 28%|██▊       | 8401/30196 [17:36<42:17,  8.59it/s]

 28%|██▊       | 8402/30196 [17:36<54:48,  6.63it/s]

 28%|██▊       | 8404/30196 [17:36<44:15,  8.21it/s]

 28%|██▊       | 8406/30196 [17:37<37:15,  9.75it/s]

 28%|██▊       | 8408/30196 [17:37<50:52,  7.14it/s]

 28%|██▊       | 8409/30196 [17:37<48:50,  7.43it/s]

 28%|██▊       | 8410/30196 [17:37<46:29,  7.81it/s]

 28%|██▊       | 8411/30196 [17:37<50:30,  7.19it/s]

 28%|██▊       | 8412/30196 [17:37<49:43,  7.30it/s]

 28%|██▊       | 8413/30196 [17:38<50:08,  7.24it/s]

 28%|██▊       | 8414/30196 [17:38<49:27,  7.34it/s]

 28%|██▊       | 8415/30196 [17:38<1:02:01,  5.85it/s]

 28%|██▊       | 8416/30196 [17:38<1:11:07,  5.10it/s]

 28%|██▊       | 8418/30196 [17:38<51:06,  7.10it/s]

 28%|██▊       | 8420/30196 [17:39<43:27,  8.35it/s]

 28%|██▊       | 8422/30196 [17:39<41:07,  8.82it/s]

 28%|██▊       | 8423/30196 [17:39<43:13,  8.40it/s]

 28%|██▊       | 8424/30196 [17:39<44:35,  8.14it/s]

 28%|██▊       | 8425/30196 [17:39<48:46,  7.44it/s]

 28%|██▊       | 8427/30196 [17:39<41:15,  8.79it/s]

 28%|██▊       | 8428/30196 [17:40<46:17,  7.84it/s]

 28%|██▊       | 8430/30196 [17:40<44:36,  8.13it/s]

 28%|██▊       | 8431/30196 [17:40<45:16,  8.01it/s]

 28%|██▊       | 8432/30196 [17:40<46:09,  7.86it/s]

 28%|██▊       | 8434/30196 [17:40<45:18,  8.00it/s]

 28%|██▊       | 8435/30196 [17:41<52:32,  6.90it/s]

 28%|██▊       | 8437/30196 [17:41<47:41,  7.60it/s]

 28%|██▊       | 8438/30196 [17:41<51:00,  7.11it/s]

 28%|██▊       | 8440/30196 [17:41<41:32,  8.73it/s]

 28%|██▊       | 8442/30196 [17:42<57:13,  6.34it/s]

 28%|██▊       | 8443/30196 [17:42<57:57,  6.25it/s]

 28%|██▊       | 8445/30196 [17:42<45:15,  8.01it/s]

 28%|██▊       | 8446/30196 [17:42<44:10,  8.21it/s]

 28%|██▊       | 8447/30196 [17:42<44:02,  8.23it/s]

 28%|██▊       | 8448/30196 [17:43<1:11:39,  5.06it/s]

 28%|██▊       | 8449/30196 [17:43<1:05:20,  5.55it/s]

 28%|██▊       | 8451/30196 [17:43<54:52,  6.60it/s]

 28%|██▊       | 8453/30196 [17:43<44:14,  8.19it/s]

 28%|██▊       | 8454/30196 [17:43<42:53,  8.45it/s]

 28%|██▊       | 8455/30196 [17:43<44:17,  8.18it/s]

 28%|██▊       | 8457/30196 [17:44<49:12,  7.36it/s]

 28%|██▊       | 8459/30196 [17:44<41:06,  8.81it/s]

 28%|██▊       | 8461/30196 [17:44<36:02, 10.05it/s]

 28%|██▊       | 8463/30196 [17:44<33:35, 10.78it/s]

 28%|██▊       | 8465/30196 [17:44<46:21,  7.81it/s]

 28%|██▊       | 8467/30196 [17:45<40:32,  8.93it/s]

 28%|██▊       | 8469/30196 [17:45<50:24,  7.18it/s]

 28%|██▊       | 8471/30196 [17:45<48:07,  7.52it/s]

 28%|██▊       | 8472/30196 [17:45<50:27,  7.18it/s]

 28%|██▊       | 8474/30196 [17:46<49:42,  7.28it/s]

 28%|██▊       | 8476/30196 [17:46<45:17,  7.99it/s]

 28%|██▊       | 8478/30196 [17:46<45:55,  7.88it/s]

 28%|██▊       | 8479/30196 [17:46<44:27,  8.14it/s]

 28%|██▊       | 8480/30196 [17:46<45:10,  8.01it/s]

 28%|██▊       | 8482/30196 [17:47<40:32,  8.93it/s]

 28%|██▊       | 8483/30196 [17:47<42:40,  8.48it/s]

 28%|██▊       | 8485/30196 [17:47<45:12,  8.01it/s]

 28%|██▊       | 8487/30196 [17:47<37:06,  9.75it/s]

 28%|██▊       | 8489/30196 [17:47<45:00,  8.04it/s]

 28%|██▊       | 8490/30196 [17:48<54:21,  6.66it/s]

 28%|██▊       | 8491/30196 [17:48<50:48,  7.12it/s]

 28%|██▊       | 8493/30196 [17:48<48:26,  7.47it/s]

 28%|██▊       | 8495/30196 [17:48<1:01:08,  5.91it/s]

 28%|██▊       | 8496/30196 [17:49<1:04:24,  5.61it/s]

 28%|██▊       | 8497/30196 [17:49<1:00:40,  5.96it/s]

 28%|██▊       | 8499/30196 [17:49<50:53,  7.11it/s]

 28%|██▊       | 8500/30196 [17:49<48:07,  7.51it/s]

 28%|██▊       | 8501/30196 [17:49<48:16,  7.49it/s]

 28%|██▊       | 8503/30196 [17:49<43:09,  8.38it/s]

 28%|██▊       | 8504/30196 [17:50<41:56,  8.62it/s]

 28%|██▊       | 8506/30196 [17:50<36:46,  9.83it/s]

 28%|██▊       | 8508/30196 [17:50<35:30, 10.18it/s]

 28%|██▊       | 8510/30196 [17:50<39:01,  9.26it/s]

 28%|██▊       | 8511/30196 [17:50<43:45,  8.26it/s]

 28%|██▊       | 8512/30196 [17:51<47:58,  7.53it/s]

 28%|██▊       | 8514/30196 [17:51<37:13,  9.71it/s]

 28%|██▊       | 8516/30196 [17:51<40:46,  8.86it/s]

 28%|██▊       | 8518/30196 [17:51<33:43, 10.71it/s]

 28%|██▊       | 8520/30196 [17:51<38:32,  9.37it/s]

 28%|██▊       | 8522/30196 [17:51<38:37,  9.35it/s]

 28%|██▊       | 8524/30196 [17:52<47:59,  7.53it/s]

 28%|██▊       | 8526/30196 [17:52<42:01,  8.60it/s]

 28%|██▊       | 8527/30196 [17:52<45:45,  7.89it/s]

 28%|██▊       | 8529/30196 [17:52<46:02,  7.84it/s]

 28%|██▊       | 8530/30196 [17:53<44:43,  8.07it/s]

 28%|██▊       | 8531/30196 [17:53<46:38,  7.74it/s]

 28%|██▊       | 8532/30196 [17:53<44:54,  8.04it/s]

 28%|██▊       | 8533/30196 [17:53<46:02,  7.84it/s]

 28%|██▊       | 8535/30196 [17:53<43:18,  8.34it/s]

 28%|██▊       | 8536/30196 [17:53<45:30,  7.93it/s]

 28%|██▊       | 8538/30196 [17:54<42:28,  8.50it/s]

 28%|██▊       | 8539/30196 [17:54<43:57,  8.21it/s]

 28%|██▊       | 8540/30196 [17:54<44:47,  8.06it/s]

 28%|██▊       | 8541/30196 [17:54<45:49,  7.88it/s]

 28%|██▊       | 8542/30196 [17:54<46:19,  7.79it/s]

 28%|██▊       | 8543/30196 [17:54<44:03,  8.19it/s]

 28%|██▊       | 8544/30196 [17:54<44:49,  8.05it/s]

 28%|██▊       | 8545/30196 [17:54<49:13,  7.33it/s]

 28%|██▊       | 8546/30196 [17:55<52:26,  6.88it/s]

 28%|██▊       | 8548/30196 [17:55<39:54,  9.04it/s]

 28%|██▊       | 8549/30196 [17:55<45:19,  7.96it/s]

 28%|██▊       | 8551/30196 [17:55<39:49,  9.06it/s]

 28%|██▊       | 8552/30196 [17:55<42:20,  8.52it/s]

 28%|██▊       | 8553/30196 [17:55<41:14,  8.75it/s]

 28%|██▊       | 8554/30196 [17:56<57:53,  6.23it/s]

 28%|██▊       | 8556/30196 [17:56<54:47,  6.58it/s]

 28%|██▊       | 8557/30196 [17:56<50:47,  7.10it/s]

 28%|██▊       | 8558/30196 [17:56<49:51,  7.23it/s]

 28%|██▊       | 8560/30196 [17:56<43:18,  8.32it/s]

 28%|██▊       | 8561/30196 [17:57<51:03,  7.06it/s]

 28%|██▊       | 8562/30196 [17:57<47:51,  7.53it/s]

 28%|██▊       | 8564/30196 [17:57<45:32,  7.92it/s]

 28%|██▊       | 8565/30196 [17:57<45:53,  7.86it/s]

 28%|██▊       | 8566/30196 [17:57<43:56,  8.20it/s]

 28%|██▊       | 8568/30196 [17:57<41:23,  8.71it/s]

 28%|██▊       | 8569/30196 [17:58<46:45,  7.71it/s]

 28%|██▊       | 8571/30196 [17:58<38:03,  9.47it/s]

 28%|██▊       | 8573/30196 [17:58<35:15, 10.22it/s]

 28%|██▊       | 8575/30196 [17:58<49:01,  7.35it/s]

 28%|██▊       | 8577/30196 [17:58<45:37,  7.90it/s]

 28%|██▊       | 8579/30196 [17:59<38:42,  9.31it/s]

 28%|██▊       | 8581/30196 [17:59<33:03, 10.89it/s]

 28%|██▊       | 8583/30196 [17:59<37:37,  9.57it/s]

 28%|██▊       | 8585/30196 [17:59<36:06,  9.98it/s]

 28%|██▊       | 8587/30196 [18:00<1:00:30,  5.95it/s]

 28%|██▊       | 8589/30196 [18:00<54:26,  6.61it/s]

 28%|██▊       | 8590/30196 [18:00<55:35,  6.48it/s]

 28%|██▊       | 8591/30196 [18:00<56:26,  6.38it/s]

 28%|██▊       | 8592/30196 [18:01<52:40,  6.83it/s]

 28%|██▊       | 8593/30196 [18:01<58:30,  6.15it/s]

 28%|██▊       | 8594/30196 [18:01<53:33,  6.72it/s]

 28%|██▊       | 8595/30196 [18:01<56:34,  6.36it/s]

 28%|██▊       | 8596/30196 [18:01<1:11:48,  5.01it/s]

 28%|██▊       | 8597/30196 [18:01<1:05:17,  5.51it/s]

 28%|██▊       | 8599/30196 [18:02<44:14,  8.14it/s]

 28%|██▊       | 8601/30196 [18:02<48:15,  7.46it/s]

 28%|██▊       | 8602/30196 [18:02<46:09,  7.80it/s]

 28%|██▊       | 8604/30196 [18:02<37:40,  9.55it/s]

 29%|██▊       | 8606/30196 [18:02<39:55,  9.01it/s]

 29%|██▊       | 8608/30196 [18:03<48:20,  7.44it/s]

 29%|██▊       | 8609/30196 [18:03<48:21,  7.44it/s]

 29%|██▊       | 8611/30196 [18:03<42:12,  8.52it/s]

 29%|██▊       | 8612/30196 [18:03<1:04:11,  5.60it/s]

 29%|██▊       | 8614/30196 [18:04<50:09,  7.17it/s]

 29%|██▊       | 8616/30196 [18:04<47:14,  7.61it/s]

 29%|██▊       | 8617/30196 [18:04<48:17,  7.45it/s]

 29%|██▊       | 8618/30196 [18:04<50:55,  7.06it/s]

 29%|██▊       | 8620/30196 [18:04<47:02,  7.64it/s]

 29%|██▊       | 8621/30196 [18:05<49:50,  7.21it/s]

 29%|██▊       | 8622/30196 [18:05<49:09,  7.31it/s]

 29%|██▊       | 8623/30196 [18:05<52:29,  6.85it/s]

 29%|██▊       | 8624/30196 [18:05<54:42,  6.57it/s]

 29%|██▊       | 8625/30196 [18:05<50:04,  7.18it/s]

 29%|██▊       | 8626/30196 [18:05<47:11,  7.62it/s]

 29%|██▊       | 8627/30196 [18:05<55:59,  6.42it/s]

 29%|██▊       | 8629/30196 [18:06<44:57,  8.00it/s]

 29%|██▊       | 8631/30196 [18:06<40:13,  8.94it/s]

 29%|██▊       | 8633/30196 [18:06<32:57, 10.90it/s]

 29%|██▊       | 8635/30196 [18:06<34:01, 10.56it/s]

 29%|██▊       | 8637/30196 [18:06<36:08,  9.94it/s]

 29%|██▊       | 8639/30196 [18:07<44:39,  8.05it/s]

 29%|██▊       | 8640/30196 [18:07<46:15,  7.77it/s]

 29%|██▊       | 8642/30196 [18:07<40:05,  8.96it/s]

 29%|██▊       | 8644/30196 [18:07<43:35,  8.24it/s]

 29%|██▊       | 8645/30196 [18:07<42:28,  8.46it/s]

 29%|██▊       | 8647/30196 [18:08<40:16,  8.92it/s]

 29%|██▊       | 8648/30196 [18:08<39:43,  9.04it/s]

 29%|██▊       | 8649/30196 [18:08<39:38,  9.06it/s]

 29%|██▊       | 8651/30196 [18:08<32:31, 11.04it/s]

 29%|██▊       | 8653/30196 [18:08<35:34, 10.09it/s]

 29%|██▊       | 8655/30196 [18:08<33:50, 10.61it/s]

 29%|██▊       | 8657/30196 [18:09<1:09:47,  5.14it/s]

 29%|██▊       | 8659/30196 [18:09<56:33,  6.35it/s]

 29%|██▊       | 8661/30196 [18:10<52:44,  6.80it/s]

 29%|██▊       | 8663/30196 [18:10<48:16,  7.43it/s]

 29%|██▊       | 8664/30196 [18:10<50:50,  7.06it/s]

 29%|██▊       | 8665/30196 [18:10<52:55,  6.78it/s]

 29%|██▊       | 8667/30196 [18:10<47:23,  7.57it/s]

 29%|██▊       | 8668/30196 [18:11<1:01:48,  5.81it/s]

 29%|██▊       | 8669/30196 [18:11<58:39,  6.12it/s]

 29%|██▊       | 8671/30196 [18:11<57:05,  6.28it/s]

 29%|██▊       | 8672/30196 [18:11<55:09,  6.50it/s]

 29%|██▊       | 8674/30196 [18:11<50:10,  7.15it/s]

 29%|██▊       | 8676/30196 [18:12<43:50,  8.18it/s]

 29%|██▊       | 8677/30196 [18:12<45:10,  7.94it/s]

 29%|██▊       | 8679/30196 [18:12<44:09,  8.12it/s]

 29%|██▊       | 8680/30196 [18:12<48:00,  7.47it/s]

 29%|██▉       | 8682/30196 [18:12<39:50,  9.00it/s]

 29%|██▉       | 8683/30196 [18:12<41:42,  8.60it/s]

 29%|██▉       | 8684/30196 [18:13<42:55,  8.35it/s]

 29%|██▉       | 8685/30196 [18:13<44:20,  8.09it/s]

 29%|██▉       | 8687/30196 [18:13<34:37, 10.35it/s]

 29%|██▉       | 8689/30196 [18:13<35:30, 10.09it/s]

 29%|██▉       | 8691/30196 [18:13<34:54, 10.27it/s]

 29%|██▉       | 8693/30196 [18:13<40:59,  8.74it/s]

 29%|██▉       | 8695/30196 [18:14<38:13,  9.37it/s]

 29%|██▉       | 8696/30196 [18:14<39:47,  9.00it/s]

 29%|██▉       | 8697/30196 [18:14<39:47,  9.01it/s]

 29%|██▉       | 8699/30196 [18:14<38:47,  9.24it/s]

 29%|██▉       | 8700/30196 [18:14<38:51,  9.22it/s]

 29%|██▉       | 8701/30196 [18:14<41:28,  8.64it/s]

 29%|██▉       | 8702/30196 [18:15<49:39,  7.21it/s]

 29%|██▉       | 8704/30196 [18:15<38:08,  9.39it/s]

 29%|██▉       | 8706/30196 [18:15<39:21,  9.10it/s]

 29%|██▉       | 8707/30196 [18:15<39:23,  9.09it/s]

 29%|██▉       | 8708/30196 [18:15<41:58,  8.53it/s]

 29%|██▉       | 8709/30196 [18:15<46:13,  7.75it/s]

 29%|██▉       | 8711/30196 [18:15<36:45,  9.74it/s]

 29%|██▉       | 8713/30196 [18:16<39:06,  9.16it/s]

 29%|██▉       | 8715/30196 [18:16<39:39,  9.03it/s]

 29%|██▉       | 8716/30196 [18:16<41:21,  8.66it/s]

 29%|██▉       | 8717/30196 [18:16<46:12,  7.75it/s]

 29%|██▉       | 8718/30196 [18:16<44:32,  8.04it/s]

 29%|██▉       | 8719/30196 [18:17<56:01,  6.39it/s]

 29%|██▉       | 8720/30196 [18:17<55:14,  6.48it/s]

 29%|██▉       | 8722/30196 [18:17<41:33,  8.61it/s]

 29%|██▉       | 8723/30196 [18:17<40:58,  8.73it/s]

 29%|██▉       | 8725/30196 [18:17<36:09,  9.90it/s]

 29%|██▉       | 8727/30196 [18:17<38:17,  9.34it/s]

 29%|██▉       | 8729/30196 [18:18<35:20, 10.12it/s]

 29%|██▉       | 8731/30196 [18:18<45:33,  7.85it/s]

 29%|██▉       | 8734/30196 [18:18<35:54,  9.96it/s]

 29%|██▉       | 8736/30196 [18:18<34:37, 10.33it/s]

 29%|██▉       | 8738/30196 [18:19<34:35, 10.34it/s]

 29%|██▉       | 8740/30196 [18:19<32:07, 11.13it/s]

 29%|██▉       | 8742/30196 [18:19<32:57, 10.85it/s]

 29%|██▉       | 8744/30196 [18:19<31:40, 11.28it/s]

 29%|██▉       | 8746/30196 [18:19<32:26, 11.02it/s]

 29%|██▉       | 8748/30196 [18:19<32:37, 10.96it/s]

 29%|██▉       | 8750/30196 [18:20<41:14,  8.67it/s]

 29%|██▉       | 8751/30196 [18:20<44:41,  8.00it/s]

 29%|██▉       | 8753/30196 [18:20<53:06,  6.73it/s]

 29%|██▉       | 8754/30196 [18:20<50:29,  7.08it/s]

 29%|██▉       | 8756/30196 [18:21<41:56,  8.52it/s]

 29%|██▉       | 8757/30196 [18:21<44:01,  8.12it/s]

 29%|██▉       | 8758/30196 [18:21<47:23,  7.54it/s]

 29%|██▉       | 8759/30196 [18:21<45:24,  7.87it/s]

 29%|██▉       | 8760/30196 [18:21<43:20,  8.24it/s]

 29%|██▉       | 8761/30196 [18:21<52:54,  6.75it/s]

 29%|██▉       | 8763/30196 [18:21<41:49,  8.54it/s]

 29%|██▉       | 8764/30196 [18:22<40:46,  8.76it/s]

 29%|██▉       | 8766/30196 [18:22<39:54,  8.95it/s]

 29%|██▉       | 8767/30196 [18:22<44:35,  8.01it/s]

 29%|██▉       | 8768/30196 [18:22<53:36,  6.66it/s]

 29%|██▉       | 8769/30196 [18:22<49:27,  7.22it/s]

 29%|██▉       | 8770/30196 [18:22<46:47,  7.63it/s]

 29%|██▉       | 8771/30196 [18:23<48:28,  7.37it/s]

 29%|██▉       | 8772/30196 [18:23<52:58,  6.74it/s]

 29%|██▉       | 8773/30196 [18:23<49:03,  7.28it/s]

 29%|██▉       | 8774/30196 [18:23<52:25,  6.81it/s]

 29%|██▉       | 8776/30196 [18:23<48:08,  7.42it/s]

 29%|██▉       | 8778/30196 [18:24<54:42,  6.53it/s]

 29%|██▉       | 8779/30196 [18:24<54:10,  6.59it/s]

 29%|██▉       | 8781/30196 [18:24<46:51,  7.62it/s]

 29%|██▉       | 8783/30196 [18:24<42:41,  8.36it/s]

 29%|██▉       | 8785/30196 [18:24<40:04,  8.90it/s]

 29%|██▉       | 8787/30196 [18:25<41:04,  8.69it/s]

 29%|██▉       | 8788/30196 [18:25<59:43,  5.97it/s]

 29%|██▉       | 8789/30196 [18:25<56:55,  6.27it/s]

 29%|██▉       | 8791/30196 [18:25<54:15,  6.57it/s]

 29%|██▉       | 8792/30196 [18:25<50:38,  7.04it/s]

 29%|██▉       | 8794/30196 [18:26<41:54,  8.51it/s]

 29%|██▉       | 8796/30196 [18:26<39:24,  9.05it/s]

 29%|██▉       | 8797/30196 [18:26<41:34,  8.58it/s]

 29%|██▉       | 8799/30196 [18:26<34:59, 10.19it/s]

 29%|██▉       | 8801/30196 [18:26<39:16,  9.08it/s]

 29%|██▉       | 8802/30196 [18:26<40:39,  8.77it/s]

 29%|██▉       | 8803/30196 [18:27<42:42,  8.35it/s]

 29%|██▉       | 8804/30196 [18:27<44:00,  8.10it/s]

 29%|██▉       | 8805/30196 [18:27<48:50,  7.30it/s]

 29%|██▉       | 8806/30196 [18:27<52:49,  6.75it/s]

 29%|██▉       | 8807/30196 [18:27<51:30,  6.92it/s]

 29%|██▉       | 8808/30196 [18:27<50:58,  6.99it/s]

 29%|██▉       | 8809/30196 [18:28<47:18,  7.53it/s]

 29%|██▉       | 8811/30196 [18:28<41:00,  8.69it/s]

 29%|██▉       | 8813/30196 [18:28<42:45,  8.33it/s]

 29%|██▉       | 8814/30196 [18:28<44:26,  8.02it/s]

 29%|██▉       | 8816/30196 [18:28<43:57,  8.11it/s]

 29%|██▉       | 8817/30196 [18:28<44:30,  8.00it/s]

 29%|██▉       | 8820/30196 [18:29<40:52,  8.72it/s]

 29%|██▉       | 8822/30196 [18:29<41:10,  8.65it/s]

 29%|██▉       | 8823/30196 [18:29<44:27,  8.01it/s]

 29%|██▉       | 8824/30196 [18:29<47:49,  7.45it/s]

 29%|██▉       | 8826/30196 [18:30<46:15,  7.70it/s]

 29%|██▉       | 8827/30196 [18:30<48:50,  7.29it/s]

 29%|██▉       | 8829/30196 [18:30<45:42,  7.79it/s]

 29%|██▉       | 8830/30196 [18:30<47:02,  7.57it/s]

 29%|██▉       | 8831/30196 [18:30<47:16,  7.53it/s]

 29%|██▉       | 8832/30196 [18:30<47:04,  7.56it/s]

 29%|██▉       | 8834/30196 [18:31<35:44,  9.96it/s]

 29%|██▉       | 8836/30196 [18:31<35:10, 10.12it/s]

 29%|██▉       | 8838/30196 [18:31<38:51,  9.16it/s]

 29%|██▉       | 8840/30196 [18:31<36:08,  9.85it/s]

 29%|██▉       | 8842/30196 [18:31<39:46,  8.95it/s]

 29%|██▉       | 8843/30196 [18:32<39:14,  9.07it/s]

 29%|██▉       | 8844/30196 [18:32<47:27,  7.50it/s]

 29%|██▉       | 8845/30196 [18:32<45:17,  7.86it/s]

 29%|██▉       | 8847/30196 [18:32<34:59, 10.17it/s]

 29%|██▉       | 8849/30196 [18:32<36:30,  9.75it/s]

 29%|██▉       | 8851/30196 [18:32<35:01, 10.16it/s]

 29%|██▉       | 8853/30196 [18:33<32:55, 10.80it/s]

 29%|██▉       | 8855/30196 [18:33<39:52,  8.92it/s]

 29%|██▉       | 8856/30196 [18:33<43:25,  8.19it/s]

 29%|██▉       | 8857/30196 [18:33<42:31,  8.36it/s]

 29%|██▉       | 8858/30196 [18:33<46:23,  7.67it/s]

 29%|██▉       | 8859/30196 [18:33<50:34,  7.03it/s]

 29%|██▉       | 8861/30196 [18:34<41:56,  8.48it/s]

 29%|██▉       | 8862/30196 [18:34<43:18,  8.21it/s]

 29%|██▉       | 8863/30196 [18:34<42:09,  8.43it/s]

 29%|██▉       | 8865/30196 [18:34<39:03,  9.10it/s]

 29%|██▉       | 8866/30196 [18:34<38:30,  9.23it/s]

 29%|██▉       | 8868/30196 [18:34<37:34,  9.46it/s]

 29%|██▉       | 8869/30196 [18:34<37:58,  9.36it/s]

 29%|██▉       | 8871/30196 [18:35<38:39,  9.19it/s]

 29%|██▉       | 8873/30196 [18:35<39:21,  9.03it/s]

 29%|██▉       | 8874/30196 [18:35<43:37,  8.15it/s]

 29%|██▉       | 8877/30196 [18:35<38:26,  9.24it/s]

 29%|██▉       | 8878/30196 [18:35<39:52,  8.91it/s]

 29%|██▉       | 8879/30196 [18:36<54:01,  6.58it/s]

 29%|██▉       | 8881/30196 [18:36<48:16,  7.36it/s]

 29%|██▉       | 8882/30196 [18:36<45:55,  7.73it/s]

 29%|██▉       | 8883/30196 [18:36<46:48,  7.59it/s]

 29%|██▉       | 8885/30196 [18:37<47:07,  7.54it/s]

 29%|██▉       | 8887/30196 [18:37<47:15,  7.51it/s]

 29%|██▉       | 8888/30196 [18:37<45:14,  7.85it/s]

 29%|██▉       | 8890/30196 [18:37<38:44,  9.17it/s]

 29%|██▉       | 8891/30196 [18:37<42:58,  8.26it/s]

 29%|██▉       | 8892/30196 [18:37<43:48,  8.11it/s]

 29%|██▉       | 8894/30196 [18:38<38:56,  9.12it/s]

 29%|██▉       | 8895/30196 [18:38<42:35,  8.34it/s]

 29%|██▉       | 8896/30196 [18:38<41:15,  8.60it/s]

 29%|██▉       | 8897/30196 [18:38<46:22,  7.65it/s]

 29%|██▉       | 8898/30196 [18:38<45:24,  7.82it/s]

 29%|██▉       | 8899/30196 [18:38<45:43,  7.76it/s]

 29%|██▉       | 8901/30196 [18:38<40:08,  8.84it/s]

 29%|██▉       | 8902/30196 [18:39<44:57,  7.89it/s]

 29%|██▉       | 8903/30196 [18:39<45:22,  7.82it/s]

 29%|██▉       | 8904/30196 [18:39<49:48,  7.12it/s]

 29%|██▉       | 8905/30196 [18:39<46:18,  7.66it/s]

 29%|██▉       | 8906/30196 [18:39<59:50,  5.93it/s]

 30%|██▉       | 8908/30196 [18:39<50:56,  6.96it/s]

 30%|██▉       | 8909/30196 [18:40<52:49,  6.72it/s]

 30%|██▉       | 8911/30196 [18:40<41:11,  8.61it/s]

 30%|██▉       | 8913/30196 [18:40<37:28,  9.47it/s]

 30%|██▉       | 8915/30196 [18:40<34:22, 10.32it/s]

 30%|██▉       | 8917/30196 [18:40<34:22, 10.32it/s]

 30%|██▉       | 8919/30196 [18:41<36:23,  9.75it/s]

 30%|██▉       | 8921/30196 [18:41<36:48,  9.63it/s]

 30%|██▉       | 8923/30196 [18:41<36:04,  9.83it/s]

 30%|██▉       | 8925/30196 [18:41<43:00,  8.24it/s]

 30%|██▉       | 8927/30196 [18:42<53:05,  6.68it/s]

 30%|██▉       | 8928/30196 [18:42<57:36,  6.15it/s]

 30%|██▉       | 8929/30196 [18:42<58:03,  6.10it/s]

 30%|██▉       | 8931/30196 [18:42<51:17,  6.91it/s]

 30%|██▉       | 8933/30196 [18:43<52:26,  6.76it/s]

 30%|██▉       | 8934/30196 [18:43<49:24,  7.17it/s]

 30%|██▉       | 8936/30196 [18:43<48:43,  7.27it/s]

 30%|██▉       | 8937/30196 [18:43<56:53,  6.23it/s]

 30%|██▉       | 8939/30196 [18:43<43:55,  8.06it/s]

 30%|██▉       | 8941/30196 [18:44<42:37,  8.31it/s]

 30%|██▉       | 8943/30196 [18:44<42:25,  8.35it/s]

 30%|██▉       | 8944/30196 [18:44<41:28,  8.54it/s]

 30%|██▉       | 8945/30196 [18:44<48:12,  7.35it/s]

 30%|██▉       | 8946/30196 [18:44<48:40,  7.28it/s]

 30%|██▉       | 8948/30196 [18:44<43:11,  8.20it/s]

 30%|██▉       | 8949/30196 [18:45<55:35,  6.37it/s]

 30%|██▉       | 8951/30196 [18:45<49:05,  7.21it/s]

 30%|██▉       | 8952/30196 [18:45<49:12,  7.19it/s]

 30%|██▉       | 8953/30196 [18:45<46:42,  7.58it/s]

 30%|██▉       | 8955/30196 [18:45<46:08,  7.67it/s]

 30%|██▉       | 8956/30196 [18:46<47:29,  7.45it/s]

 30%|██▉       | 8957/30196 [18:46<44:58,  7.87it/s]

 30%|██▉       | 8959/30196 [18:46<45:50,  7.72it/s]

 30%|██▉       | 8960/30196 [18:46<48:58,  7.23it/s]

 30%|██▉       | 8961/30196 [18:46<46:36,  7.59it/s]

 30%|██▉       | 8963/30196 [18:46<36:03,  9.81it/s]

 30%|██▉       | 8965/30196 [18:47<37:21,  9.47it/s]

 30%|██▉       | 8967/30196 [18:47<36:46,  9.62it/s]

 30%|██▉       | 8969/30196 [18:47<39:16,  9.01it/s]

 30%|██▉       | 8970/30196 [18:47<38:52,  9.10it/s]

 30%|██▉       | 8972/30196 [18:47<36:11,  9.77it/s]

 30%|██▉       | 8974/30196 [18:47<31:04, 11.38it/s]

 30%|██▉       | 8976/30196 [18:48<34:21, 10.29it/s]

 30%|██▉       | 8978/30196 [18:48<36:58,  9.56it/s]

 30%|██▉       | 8980/30196 [18:48<49:27,  7.15it/s]

 30%|██▉       | 8982/30196 [18:49<51:10,  6.91it/s]

 30%|██▉       | 8983/30196 [18:49<51:08,  6.91it/s]

 30%|██▉       | 8984/30196 [18:49<57:12,  6.18it/s]

 30%|██▉       | 8985/30196 [18:49<52:38,  6.72it/s]

 30%|██▉       | 8986/30196 [18:49<51:22,  6.88it/s]

 30%|██▉       | 8988/30196 [18:49<43:08,  8.19it/s]

 30%|██▉       | 8989/30196 [18:50<47:23,  7.46it/s]

 30%|██▉       | 8991/30196 [18:50<50:16,  7.03it/s]

 30%|██▉       | 8992/30196 [18:50<49:30,  7.14it/s]

 30%|██▉       | 8993/30196 [18:50<52:23,  6.75it/s]

 30%|██▉       | 8995/30196 [18:51<51:28,  6.86it/s]

 30%|██▉       | 8996/30196 [18:51<53:18,  6.63it/s]

 30%|██▉       | 8998/30196 [18:51<47:48,  7.39it/s]

 30%|██▉       | 8999/30196 [18:51<50:20,  7.02it/s]

 30%|██▉       | 9001/30196 [18:51<38:09,  9.26it/s]

 30%|██▉       | 9003/30196 [18:51<36:12,  9.75it/s]

 30%|██▉       | 9005/30196 [18:52<37:16,  9.47it/s]

 30%|██▉       | 9007/30196 [18:52<39:18,  8.99it/s]

 30%|██▉       | 9009/30196 [18:52<47:32,  7.43it/s]

 30%|██▉       | 9010/30196 [18:52<47:44,  7.40it/s]

 30%|██▉       | 9011/30196 [18:53<50:03,  7.05it/s]

 30%|██▉       | 9012/30196 [18:53<47:04,  7.50it/s]

 30%|██▉       | 9014/30196 [18:53<46:48,  7.54it/s]

 30%|██▉       | 9015/30196 [18:53<47:53,  7.37it/s]

 30%|██▉       | 9017/30196 [18:53<41:34,  8.49it/s]

 30%|██▉       | 9018/30196 [18:53<42:48,  8.24it/s]

 30%|██▉       | 9020/30196 [18:54<41:56,  8.41it/s]

 30%|██▉       | 9021/30196 [18:54<43:14,  8.16it/s]

 30%|██▉       | 9022/30196 [18:54<46:54,  7.52it/s]

 30%|██▉       | 9023/30196 [18:54<44:54,  7.86it/s]

 30%|██▉       | 9025/30196 [18:54<39:22,  8.96it/s]

 30%|██▉       | 9027/30196 [18:54<39:16,  8.98it/s]

 30%|██▉       | 9028/30196 [18:55<40:44,  8.66it/s]

 30%|██▉       | 9029/30196 [18:55<39:50,  8.85it/s]

 30%|██▉       | 9030/30196 [18:55<39:32,  8.92it/s]

 30%|██▉       | 9031/30196 [18:55<41:44,  8.45it/s]

 30%|██▉       | 9033/30196 [18:55<37:17,  9.46it/s]

 30%|██▉       | 9034/30196 [18:55<44:29,  7.93it/s]

 30%|██▉       | 9035/30196 [18:55<45:11,  7.80it/s]

 30%|██▉       | 9037/30196 [18:56<42:18,  8.34it/s]

 30%|██▉       | 9038/30196 [18:56<44:33,  7.91it/s]

 30%|██▉       | 9039/30196 [18:56<45:50,  7.69it/s]

 30%|██▉       | 9041/30196 [18:56<46:22,  7.60it/s]

 30%|██▉       | 9042/30196 [18:56<46:20,  7.61it/s]

 30%|██▉       | 9043/30196 [18:57<53:20,  6.61it/s]

 30%|██▉       | 9044/30196 [18:57<55:18,  6.37it/s]

 30%|██▉       | 9046/30196 [18:57<47:27,  7.43it/s]

 30%|██▉       | 9048/30196 [18:57<44:14,  7.97it/s]

 30%|██▉       | 9050/30196 [18:57<38:46,  9.09it/s]

 30%|██▉       | 9052/30196 [18:57<34:33, 10.20it/s]

 30%|██▉       | 9054/30196 [18:58<42:56,  8.21it/s]

 30%|██▉       | 9055/30196 [18:58<41:49,  8.43it/s]

 30%|██▉       | 9056/30196 [18:58<41:09,  8.56it/s]

 30%|██▉       | 9057/30196 [18:58<42:43,  8.25it/s]

 30%|███       | 9059/30196 [18:58<49:06,  7.17it/s]

 30%|███       | 9061/30196 [18:59<43:43,  8.06it/s]

 30%|███       | 9062/30196 [18:59<47:17,  7.45it/s]

 30%|███       | 9064/30196 [18:59<42:55,  8.21it/s]

 30%|███       | 9065/30196 [18:59<47:16,  7.45it/s]

 30%|███       | 9066/30196 [18:59<50:57,  6.91it/s]

 30%|███       | 9068/30196 [19:00<46:19,  7.60it/s]

 30%|███       | 9069/30196 [19:00<53:48,  6.54it/s]

 30%|███       | 9070/30196 [19:00<50:11,  7.01it/s]

 30%|███       | 9072/30196 [19:00<44:16,  7.95it/s]

 30%|███       | 9073/30196 [19:00<52:24,  6.72it/s]

 30%|███       | 9074/30196 [19:01<52:18,  6.73it/s]

 30%|███       | 9075/30196 [19:01<48:20,  7.28it/s]

 30%|███       | 9076/30196 [19:01<49:19,  7.14it/s]

 30%|███       | 9077/30196 [19:01<46:20,  7.60it/s]

 30%|███       | 9078/30196 [19:01<46:17,  7.60it/s]

 30%|███       | 9081/30196 [19:01<33:31, 10.50it/s]

 30%|███       | 9083/30196 [19:02<40:04,  8.78it/s]

 30%|███       | 9085/30196 [19:02<37:11,  9.46it/s]

 30%|███       | 9086/30196 [19:02<38:51,  9.05it/s]

 30%|███       | 9088/30196 [19:02<41:53,  8.40it/s]

 30%|███       | 9089/30196 [19:02<40:55,  8.60it/s]

 30%|███       | 9091/30196 [19:02<37:24,  9.40it/s]

 30%|███       | 9093/30196 [19:03<33:46, 10.41it/s]

 30%|███       | 9095/30196 [19:03<31:59, 10.99it/s]

 30%|███       | 9097/30196 [19:03<35:33,  9.89it/s]

 30%|███       | 9099/30196 [19:03<36:37,  9.60it/s]

 30%|███       | 9101/30196 [19:03<32:47, 10.72it/s]

 30%|███       | 9103/30196 [19:03<32:45, 10.73it/s]

 30%|███       | 9105/30196 [19:04<31:25, 11.18it/s]

 30%|███       | 9107/30196 [19:04<37:24,  9.40it/s]

 30%|███       | 9109/30196 [19:04<37:25,  9.39it/s]

 30%|███       | 9110/30196 [19:04<40:00,  8.78it/s]

 30%|███       | 9112/30196 [19:05<41:34,  8.45it/s]

 30%|███       | 9113/30196 [19:05<42:39,  8.24it/s]

 30%|███       | 9115/30196 [19:05<36:59,  9.50it/s]

 30%|███       | 9116/30196 [19:05<44:07,  7.96it/s]

 30%|███       | 9118/30196 [19:05<47:33,  7.39it/s]

 30%|███       | 9120/30196 [19:06<41:07,  8.54it/s]

 30%|███       | 9122/30196 [19:06<40:07,  8.75it/s]

 30%|███       | 9123/30196 [19:06<50:48,  6.91it/s]

 30%|███       | 9124/30196 [19:06<50:46,  6.92it/s]

 30%|███       | 9126/30196 [19:06<40:17,  8.72it/s]

 30%|███       | 9128/30196 [19:06<33:16, 10.55it/s]

 30%|███       | 9130/30196 [19:07<28:44, 12.22it/s]

 30%|███       | 9132/30196 [19:07<34:50, 10.08it/s]

 30%|███       | 9134/30196 [19:07<34:31, 10.17it/s]

 30%|███       | 9136/30196 [19:07<33:52, 10.36it/s]

 30%|███       | 9138/30196 [19:07<33:12, 10.57it/s]

 30%|███       | 9140/30196 [19:08<39:43,  8.83it/s]

 30%|███       | 9142/30196 [19:08<37:30,  9.35it/s]

 30%|███       | 9144/30196 [19:09<1:05:09,  5.38it/s]

 30%|███       | 9146/30196 [19:09<55:50,  6.28it/s]

 30%|███       | 9147/30196 [19:09<54:09,  6.48it/s]

 30%|███       | 9149/30196 [19:09<47:38,  7.36it/s]

 30%|███       | 9150/30196 [19:09<45:38,  7.69it/s]

 30%|███       | 9152/30196 [19:09<36:11,  9.69it/s]

 30%|███       | 9154/30196 [19:10<41:16,  8.49it/s]

 30%|███       | 9156/30196 [19:10<43:45,  8.01it/s]

 30%|███       | 9158/30196 [19:10<47:14,  7.42it/s]

 30%|███       | 9160/30196 [19:10<40:06,  8.74it/s]

 30%|███       | 9162/30196 [19:11<38:42,  9.06it/s]

 30%|███       | 9164/30196 [19:11<37:15,  9.41it/s]

 30%|███       | 9166/30196 [19:11<43:12,  8.11it/s]

 30%|███       | 9167/30196 [19:11<42:23,  8.27it/s]

 30%|███       | 9169/30196 [19:11<45:48,  7.65it/s]

 30%|███       | 9170/30196 [19:12<48:19,  7.25it/s]

 30%|███       | 9171/30196 [19:12<54:07,  6.47it/s]

 30%|███       | 9173/30196 [19:12<47:51,  7.32it/s]

 30%|███       | 9174/30196 [19:12<47:45,  7.34it/s]

 30%|███       | 9175/30196 [19:12<54:17,  6.45it/s]

 30%|███       | 9176/30196 [19:13<50:26,  6.95it/s]

 30%|███       | 9177/30196 [19:13<47:15,  7.41it/s]

 30%|███       | 9178/30196 [19:13<47:50,  7.32it/s]

 30%|███       | 9180/30196 [19:13<39:13,  8.93it/s]

 30%|███       | 9182/30196 [19:13<38:50,  9.02it/s]

 30%|███       | 9183/30196 [19:13<43:42,  8.01it/s]

 30%|███       | 9185/30196 [19:13<36:14,  9.66it/s]

 30%|███       | 9187/30196 [19:14<38:23,  9.12it/s]

 30%|███       | 9188/30196 [19:14<53:09,  6.59it/s]

 30%|███       | 9189/30196 [19:14<57:27,  6.09it/s]

 30%|███       | 9191/30196 [19:14<45:15,  7.74it/s]

 30%|███       | 9193/30196 [19:15<45:56,  7.62it/s]

 30%|███       | 9194/30196 [19:15<48:25,  7.23it/s]

 30%|███       | 9196/30196 [19:15<38:08,  9.18it/s]

 30%|███       | 9198/30196 [19:15<44:28,  7.87it/s]

 30%|███       | 9199/30196 [19:15<43:20,  8.07it/s]

 30%|███       | 9200/30196 [19:16<52:37,  6.65it/s]

 30%|███       | 9201/30196 [19:16<49:09,  7.12it/s]

 30%|███       | 9202/30196 [19:16<49:15,  7.10it/s]

 30%|███       | 9203/30196 [19:16<52:44,  6.63it/s]

 30%|███       | 9205/30196 [19:16<41:57,  8.34it/s]

 30%|███       | 9206/30196 [19:16<40:44,  8.59it/s]

 30%|███       | 9207/30196 [19:16<39:43,  8.81it/s]

 30%|███       | 9208/30196 [19:17<41:17,  8.47it/s]

 31%|███       | 9210/30196 [19:17<37:19,  9.37it/s]

 31%|███       | 9211/30196 [19:17<37:35,  9.30it/s]

 31%|███       | 9212/30196 [19:17<37:19,  9.37it/s]

 31%|███       | 9214/30196 [19:17<35:05,  9.97it/s]

 31%|███       | 9215/30196 [19:17<41:35,  8.41it/s]

 31%|███       | 9217/30196 [19:17<35:51,  9.75it/s]

 31%|███       | 9218/30196 [19:18<39:22,  8.88it/s]

 31%|███       | 9219/30196 [19:18<38:43,  9.03it/s]

 31%|███       | 9221/30196 [19:18<35:00,  9.98it/s]

 31%|███       | 9223/30196 [19:18<43:47,  7.98it/s]

 31%|███       | 9224/30196 [19:18<42:45,  8.18it/s]

 31%|███       | 9226/30196 [19:18<35:23,  9.87it/s]

 31%|███       | 9228/30196 [19:19<40:04,  8.72it/s]

 31%|███       | 9229/30196 [19:19<39:43,  8.80it/s]

 31%|███       | 9231/30196 [19:19<32:57, 10.60it/s]

 31%|███       | 9233/30196 [19:19<34:44, 10.06it/s]

 31%|███       | 9235/30196 [19:19<36:28,  9.58it/s]

 31%|███       | 9237/30196 [19:20<36:16,  9.63it/s]

 31%|███       | 9239/30196 [19:20<44:02,  7.93it/s]

 31%|███       | 9240/30196 [19:20<47:03,  7.42it/s]

 31%|███       | 9241/30196 [19:20<47:33,  7.34it/s]

 31%|███       | 9243/30196 [19:20<36:56,  9.45it/s]

 31%|███       | 9245/30196 [19:21<37:38,  9.28it/s]

 31%|███       | 9247/30196 [19:21<40:39,  8.59it/s]

 31%|███       | 9248/30196 [19:21<39:52,  8.76it/s]

 31%|███       | 9249/30196 [19:21<49:24,  7.07it/s]

 31%|███       | 9251/30196 [19:22<47:37,  7.33it/s]

 31%|███       | 9252/30196 [19:22<50:28,  6.92it/s]

 31%|███       | 9254/30196 [19:22<44:43,  7.80it/s]

 31%|███       | 9255/30196 [19:22<47:48,  7.30it/s]

 31%|███       | 9257/30196 [19:22<39:50,  8.76it/s]

 31%|███       | 9259/30196 [19:22<34:36, 10.08it/s]

 31%|███       | 9261/30196 [19:23<32:37, 10.70it/s]

 31%|███       | 9263/30196 [19:23<38:54,  8.97it/s]

 31%|███       | 9264/30196 [19:23<40:38,  8.58it/s]

 31%|███       | 9265/30196 [19:23<40:12,  8.68it/s]

 31%|███       | 9267/30196 [19:23<34:52, 10.00it/s]

 31%|███       | 9269/30196 [19:23<30:39, 11.38it/s]

 31%|███       | 9271/30196 [19:24<40:41,  8.57it/s]

 31%|███       | 9272/30196 [19:24<41:42,  8.36it/s]

 31%|███       | 9274/30196 [19:24<38:37,  9.03it/s]

 31%|███       | 9275/30196 [19:24<46:15,  7.54it/s]

 31%|███       | 9276/30196 [19:24<47:21,  7.36it/s]

 31%|███       | 9278/30196 [19:25<42:01,  8.29it/s]

 31%|███       | 9280/30196 [19:25<43:45,  7.97it/s]

 31%|███       | 9281/30196 [19:25<44:50,  7.77it/s]

 31%|███       | 9282/30196 [19:25<44:57,  7.75it/s]

 31%|███       | 9283/30196 [19:25<45:03,  7.73it/s]

 31%|███       | 9285/30196 [19:25<38:30,  9.05it/s]

 31%|███       | 9286/30196 [19:26<41:28,  8.40it/s]

 31%|███       | 9288/30196 [19:26<38:53,  8.96it/s]

 31%|███       | 9290/30196 [19:26<37:49,  9.21it/s]

 31%|███       | 9291/30196 [19:26<42:04,  8.28it/s]

 31%|███       | 9292/30196 [19:26<41:14,  8.45it/s]

 31%|███       | 9293/30196 [19:26<46:34,  7.48it/s]

 31%|███       | 9295/30196 [19:27<37:48,  9.21it/s]

 31%|███       | 9296/30196 [19:27<39:29,  8.82it/s]

 31%|███       | 9298/30196 [19:27<31:50, 10.94it/s]

 31%|███       | 9300/30196 [19:27<35:41,  9.76it/s]

 31%|███       | 9302/30196 [19:28<58:51,  5.92it/s]

 31%|███       | 9304/30196 [19:28<46:07,  7.55it/s]

 31%|███       | 9306/30196 [19:28<50:21,  6.91it/s]

 31%|███       | 9307/30196 [19:28<55:54,  6.23it/s]

 31%|███       | 9308/30196 [19:28<53:42,  6.48it/s]

 31%|███       | 9309/30196 [19:29<53:07,  6.55it/s]

 31%|███       | 9310/30196 [19:29<58:13,  5.98it/s]

 31%|███       | 9312/30196 [19:29<51:51,  6.71it/s]

 31%|███       | 9314/30196 [19:29<49:37,  7.01it/s]

 31%|███       | 9315/30196 [19:30<54:54,  6.34it/s]

 31%|███       | 9316/30196 [19:30<55:15,  6.30it/s]

 31%|███       | 9317/30196 [19:30<50:57,  6.83it/s]

 31%|███       | 9319/30196 [19:30<45:45,  7.60it/s]

 31%|███       | 9320/30196 [19:30<46:00,  7.56it/s]

 31%|███       | 9322/30196 [19:30<45:57,  7.57it/s]

 31%|███       | 9324/30196 [19:31<41:56,  8.29it/s]

 31%|███       | 9325/30196 [19:31<46:04,  7.55it/s]

 31%|███       | 9326/30196 [19:31<1:05:50,  5.28it/s]

 31%|███       | 9327/30196 [19:31<1:02:42,  5.55it/s]

 31%|███       | 9328/30196 [19:31<56:53,  6.11it/s]

 31%|███       | 9330/30196 [19:32<48:39,  7.15it/s]

 31%|███       | 9331/30196 [19:32<48:58,  7.10it/s]

 31%|███       | 9332/30196 [19:32<48:16,  7.20it/s]

 31%|███       | 9333/30196 [19:32<55:03,  6.32it/s]

 31%|███       | 9335/30196 [19:32<46:42,  7.44it/s]

 31%|███       | 9336/30196 [19:33<50:09,  6.93it/s]

 31%|███       | 9339/30196 [19:33<36:11,  9.61it/s]

 31%|███       | 9340/30196 [19:33<36:25,  9.54it/s]

 31%|███       | 9341/30196 [19:33<53:12,  6.53it/s]

 31%|███       | 9343/30196 [19:33<41:41,  8.34it/s]

 31%|███       | 9345/30196 [19:33<36:39,  9.48it/s]

 31%|███       | 9347/30196 [19:34<36:29,  9.52it/s]

 31%|███       | 9349/30196 [19:34<37:34,  9.25it/s]

 31%|███       | 9351/30196 [19:34<36:01,  9.65it/s]

 31%|███       | 9353/30196 [19:34<39:39,  8.76it/s]

 31%|███       | 9354/30196 [19:35<43:43,  7.94it/s]

 31%|███       | 9355/30196 [19:35<42:16,  8.22it/s]

 31%|███       | 9357/30196 [19:35<40:18,  8.62it/s]

 31%|███       | 9358/30196 [19:35<41:42,  8.33it/s]

 31%|███       | 9360/30196 [19:35<35:33,  9.77it/s]

 31%|███       | 9361/30196 [19:35<43:09,  8.04it/s]

 31%|███       | 9363/30196 [19:36<38:06,  9.11it/s]

 31%|███       | 9364/30196 [19:36<42:30,  8.17it/s]

 31%|███       | 9366/30196 [19:36<38:20,  9.05it/s]

 31%|███       | 9367/30196 [19:36<53:19,  6.51it/s]

 31%|███       | 9369/30196 [19:36<44:35,  7.78it/s]

 31%|███       | 9370/30196 [19:37<45:35,  7.61it/s]

 31%|███       | 9371/30196 [19:37<45:52,  7.56it/s]

 31%|███       | 9372/30196 [19:37<46:09,  7.52it/s]

 31%|███       | 9374/30196 [19:37<42:32,  8.16it/s]

 31%|███       | 9376/30196 [19:37<35:07,  9.88it/s]

 31%|███       | 9378/30196 [19:37<38:48,  8.94it/s]

 31%|███       | 9380/30196 [19:38<36:16,  9.56it/s]

 31%|███       | 9381/30196 [19:38<36:16,  9.56it/s]

 31%|███       | 9383/30196 [19:38<37:12,  9.32it/s]

 31%|███       | 9385/30196 [19:38<38:24,  9.03it/s]

 31%|███       | 9387/30196 [19:38<34:52,  9.95it/s]

 31%|███       | 9389/30196 [19:39<39:05,  8.87it/s]

 31%|███       | 9390/30196 [19:39<40:31,  8.56it/s]

 31%|███       | 9391/30196 [19:39<40:00,  8.67it/s]

 31%|███       | 9392/30196 [19:39<44:01,  7.87it/s]

 31%|███       | 9394/30196 [19:39<41:35,  8.34it/s]

 31%|███       | 9396/30196 [19:39<39:28,  8.78it/s]

 31%|███       | 9397/30196 [19:40<38:59,  8.89it/s]

 31%|███       | 9399/30196 [19:40<34:44,  9.98it/s]

 31%|███       | 9401/30196 [19:40<44:32,  7.78it/s]

 31%|███       | 9402/30196 [19:40<44:54,  7.72it/s]

 31%|███       | 9403/30196 [19:40<44:52,  7.72it/s]

 31%|███       | 9404/30196 [19:40<45:17,  7.65it/s]

 31%|███       | 9405/30196 [19:41<48:27,  7.15it/s]

 31%|███       | 9406/30196 [19:41<48:29,  7.14it/s]

 31%|███       | 9408/30196 [19:41<41:43,  8.30it/s]

 31%|███       | 9409/30196 [19:41<46:02,  7.52it/s]

 31%|███       | 9411/30196 [19:41<40:44,  8.50it/s]

 31%|███       | 9412/30196 [19:41<44:44,  7.74it/s]

 31%|███       | 9414/30196 [19:42<35:56,  9.63it/s]

 31%|███       | 9416/30196 [19:42<32:36, 10.62it/s]

 31%|███       | 9418/30196 [19:42<35:53,  9.65it/s]

 31%|███       | 9421/30196 [19:42<33:26, 10.35it/s]

 31%|███       | 9423/30196 [19:42<34:22, 10.07it/s]

 31%|███       | 9425/30196 [19:43<32:44, 10.57it/s]

 31%|███       | 9427/30196 [19:43<35:57,  9.63it/s]

 31%|███       | 9429/30196 [19:43<35:02,  9.88it/s]

 31%|███       | 9431/30196 [19:43<38:18,  9.04it/s]

 31%|███       | 9432/30196 [19:44<41:41,  8.30it/s]

 31%|███       | 9434/30196 [19:44<38:27,  9.00it/s]

 31%|███       | 9435/30196 [19:44<40:02,  8.64it/s]

 31%|███       | 9436/30196 [19:44<41:10,  8.40it/s]

 31%|███▏      | 9439/30196 [19:44<34:08, 10.13it/s]

 31%|███▏      | 9440/30196 [19:44<38:25,  9.00it/s]

 31%|███▏      | 9441/30196 [19:45<45:23,  7.62it/s]

 31%|███▏      | 9443/30196 [19:45<44:31,  7.77it/s]

 31%|███▏      | 9444/30196 [19:45<42:46,  8.08it/s]

 31%|███▏      | 9446/30196 [19:45<37:57,  9.11it/s]

 31%|███▏      | 9448/30196 [19:45<39:07,  8.84it/s]

 31%|███▏      | 9450/30196 [19:45<35:24,  9.77it/s]

 31%|███▏      | 9451/30196 [19:46<39:43,  8.70it/s]

 31%|███▏      | 9452/30196 [19:46<41:06,  8.41it/s]

 31%|███▏      | 9453/30196 [19:46<57:47,  5.98it/s]

 31%|███▏      | 9454/30196 [19:46<55:02,  6.28it/s]

 31%|███▏      | 9455/30196 [19:46<50:29,  6.85it/s]

 31%|███▏      | 9456/30196 [19:46<49:06,  7.04it/s]

 31%|███▏      | 9458/30196 [19:47<42:08,  8.20it/s]

 31%|███▏      | 9460/30196 [19:47<49:48,  6.94it/s]

 31%|███▏      | 9462/30196 [19:47<42:07,  8.20it/s]

 31%|███▏      | 9463/30196 [19:47<48:01,  7.20it/s]

 31%|███▏      | 9465/30196 [19:48<38:42,  8.93it/s]

 31%|███▏      | 9467/30196 [19:48<37:57,  9.10it/s]

 31%|███▏      | 9468/30196 [19:48<39:19,  8.78it/s]

 31%|███▏      | 9470/30196 [19:48<41:21,  8.35it/s]

 31%|███▏      | 9471/30196 [19:48<42:47,  8.07it/s]

 31%|███▏      | 9472/30196 [19:49<1:03:25,  5.45it/s]

 31%|███▏      | 9474/30196 [19:49<49:38,  6.96it/s]

 31%|███▏      | 9476/30196 [19:49<47:51,  7.22it/s]

 31%|███▏      | 9478/30196 [19:49<42:26,  8.13it/s]

 31%|███▏      | 9479/30196 [19:49<45:55,  7.52it/s]

 31%|███▏      | 9481/30196 [19:50<38:20,  9.00it/s]

 31%|███▏      | 9483/30196 [19:50<36:00,  9.59it/s]

 31%|███▏      | 9485/30196 [19:50<1:01:42,  5.59it/s]

 31%|███▏      | 9486/30196 [19:51<58:33,  5.89it/s]

 31%|███▏      | 9487/30196 [19:51<56:39,  6.09it/s]

 31%|███▏      | 9488/30196 [19:51<52:20,  6.59it/s]

 31%|███▏      | 9490/30196 [19:51<48:18,  7.14it/s]

 31%|███▏      | 9491/30196 [19:52<1:18:44,  4.38it/s]

 31%|███▏      | 9494/30196 [19:52<49:57,  6.91it/s]

 31%|███▏      | 9495/30196 [19:52<51:50,  6.66it/s]

 31%|███▏      | 9496/30196 [19:52<53:39,  6.43it/s]

 31%|███▏      | 9498/30196 [19:52<43:02,  8.01it/s]

 31%|███▏      | 9499/30196 [19:52<41:34,  8.30it/s]

 31%|███▏      | 9501/30196 [19:53<37:40,  9.15it/s]

 31%|███▏      | 9503/30196 [19:53<33:56, 10.16it/s]

 31%|███▏      | 9505/30196 [19:53<33:32, 10.28it/s]

 31%|███▏      | 9507/30196 [19:53<49:51,  6.92it/s]

 31%|███▏      | 9508/30196 [19:54<48:16,  7.14it/s]

 31%|███▏      | 9510/30196 [19:54<39:03,  8.83it/s]

 32%|███▏      | 9512/30196 [19:54<45:57,  7.50it/s]

 32%|███▏      | 9514/30196 [19:54<40:44,  8.46it/s]

 32%|███▏      | 9515/30196 [19:54<40:12,  8.57it/s]

 32%|███▏      | 9516/30196 [19:54<47:03,  7.32it/s]

 32%|███▏      | 9517/30196 [19:55<47:00,  7.33it/s]

 32%|███▏      | 9519/30196 [19:55<35:39,  9.66it/s]

 32%|███▏      | 9521/30196 [19:55<36:21,  9.48it/s]

 32%|███▏      | 9523/30196 [19:55<43:08,  7.99it/s]

 32%|███▏      | 9524/30196 [19:55<43:47,  7.87it/s]

 32%|███▏      | 9526/30196 [19:56<39:04,  8.82it/s]

 32%|███▏      | 9527/30196 [19:56<38:48,  8.87it/s]

 32%|███▏      | 9528/30196 [19:56<42:59,  8.01it/s]

 32%|███▏      | 9529/30196 [19:56<41:41,  8.26it/s]

 32%|███▏      | 9530/30196 [19:56<46:23,  7.42it/s]

 32%|███▏      | 9532/30196 [19:56<37:25,  9.20it/s]

 32%|███▏      | 9533/30196 [19:56<40:35,  8.49it/s]

 32%|███▏      | 9534/30196 [19:57<44:57,  7.66it/s]

 32%|███▏      | 9536/30196 [19:57<42:04,  8.18it/s]

 32%|███▏      | 9538/30196 [19:57<39:14,  8.77it/s]

 32%|███▏      | 9539/30196 [19:57<38:58,  8.83it/s]

 32%|███▏      | 9541/30196 [19:57<31:58, 10.77it/s]

 32%|███▏      | 9543/30196 [19:58<42:35,  8.08it/s]

 32%|███▏      | 9545/30196 [19:58<35:18,  9.75it/s]

 32%|███▏      | 9547/30196 [19:58<37:11,  9.25it/s]

 32%|███▏      | 9549/30196 [19:58<37:38,  9.14it/s]

 32%|███▏      | 9551/30196 [19:59<42:22,  8.12it/s]

 32%|███▏      | 9553/30196 [19:59<38:06,  9.03it/s]

 32%|███▏      | 9555/30196 [19:59<32:23, 10.62it/s]

 32%|███▏      | 9557/30196 [19:59<36:15,  9.49it/s]

 32%|███▏      | 9559/30196 [19:59<40:19,  8.53it/s]

 32%|███▏      | 9560/30196 [20:00<42:41,  8.05it/s]

 32%|███▏      | 9561/30196 [20:00<44:17,  7.76it/s]

 32%|███▏      | 9563/30196 [20:00<39:45,  8.65it/s]

 32%|███▏      | 9565/30196 [20:00<35:16,  9.75it/s]

 32%|███▏      | 9567/30196 [20:00<38:56,  8.83it/s]

 32%|███▏      | 9568/30196 [20:00<45:36,  7.54it/s]

 32%|███▏      | 9569/30196 [20:01<45:45,  7.51it/s]

 32%|███▏      | 9570/30196 [20:01<43:57,  7.82it/s]

 32%|███▏      | 9571/30196 [20:01<47:49,  7.19it/s]

 32%|███▏      | 9573/30196 [20:01<48:09,  7.14it/s]

 32%|███▏      | 9574/30196 [20:01<51:04,  6.73it/s]

 32%|███▏      | 9576/30196 [20:02<43:56,  7.82it/s]

 32%|███▏      | 9578/30196 [20:02<40:38,  8.46it/s]

 32%|███▏      | 9579/30196 [20:02<42:26,  8.10it/s]

 32%|███▏      | 9580/30196 [20:02<46:27,  7.39it/s]

 32%|███▏      | 9582/30196 [20:02<40:54,  8.40it/s]

 32%|███▏      | 9583/30196 [20:02<44:59,  7.64it/s]

 32%|███▏      | 9585/30196 [20:03<39:26,  8.71it/s]

 32%|███▏      | 9586/30196 [20:03<43:38,  7.87it/s]

 32%|███▏      | 9587/30196 [20:03<42:13,  8.13it/s]

 32%|███▏      | 9589/30196 [20:03<42:57,  7.99it/s]

 32%|███▏      | 9590/30196 [20:03<43:42,  7.86it/s]

 32%|███▏      | 9592/30196 [20:03<40:31,  8.47it/s]

 32%|███▏      | 9594/30196 [20:04<41:48,  8.21it/s]

 32%|███▏      | 9595/30196 [20:04<42:19,  8.11it/s]

 32%|███▏      | 9596/30196 [20:04<50:25,  6.81it/s]

 32%|███▏      | 9598/30196 [20:04<44:58,  7.63it/s]

 32%|███▏      | 9599/30196 [20:04<45:16,  7.58it/s]

 32%|███▏      | 9600/30196 [20:05<48:17,  7.11it/s]

 32%|███▏      | 9601/30196 [20:05<50:44,  6.77it/s]

 32%|███▏      | 9602/30196 [20:05<1:00:02,  5.72it/s]

 32%|███▏      | 9604/30196 [20:05<55:00,  6.24it/s]

 32%|███▏      | 9605/30196 [20:05<52:35,  6.53it/s]

 32%|███▏      | 9606/30196 [20:06<48:21,  7.10it/s]

 32%|███▏      | 9607/30196 [20:06<48:58,  7.01it/s]

 32%|███▏      | 9608/30196 [20:06<48:50,  7.03it/s]

 32%|███▏      | 9609/30196 [20:06<45:16,  7.58it/s]

 32%|███▏      | 9610/30196 [20:06<46:08,  7.44it/s]

 32%|███▏      | 9611/30196 [20:06<50:10,  6.84it/s]

 32%|███▏      | 9613/30196 [20:06<42:39,  8.04it/s]

 32%|███▏      | 9614/30196 [20:07<44:35,  7.69it/s]

 32%|███▏      | 9615/30196 [20:07<52:46,  6.50it/s]

 32%|███▏      | 9616/30196 [20:07<51:04,  6.72it/s]

 32%|███▏      | 9617/30196 [20:07<49:24,  6.94it/s]

 32%|███▏      | 9618/30196 [20:07<56:31,  6.07it/s]

 32%|███▏      | 9619/30196 [20:08<59:15,  5.79it/s]

 32%|███▏      | 9621/30196 [20:08<48:09,  7.12it/s]

 32%|███▏      | 9622/30196 [20:08<50:16,  6.82it/s]

 32%|███▏      | 9624/30196 [20:08<55:15,  6.21it/s]

 32%|███▏      | 9626/30196 [20:09<53:33,  6.40it/s]

 32%|███▏      | 9627/30196 [20:09<50:16,  6.82it/s]

 32%|███▏      | 9628/30196 [20:09<49:47,  6.89it/s]

 32%|███▏      | 9629/30196 [20:09<46:24,  7.39it/s]

 32%|███▏      | 9630/30196 [20:09<45:57,  7.46it/s]

 32%|███▏      | 9632/30196 [20:09<42:03,  8.15it/s]

 32%|███▏      | 9634/30196 [20:09<36:26,  9.40it/s]

 32%|███▏      | 9635/30196 [20:10<39:21,  8.71it/s]

 32%|███▏      | 9637/30196 [20:10<40:16,  8.51it/s]

 32%|███▏      | 9639/30196 [20:10<33:50, 10.12it/s]

 32%|███▏      | 9641/30196 [20:10<38:55,  8.80it/s]

 32%|███▏      | 9643/30196 [20:10<35:46,  9.57it/s]

 32%|███▏      | 9645/30196 [20:11<34:04, 10.05it/s]

 32%|███▏      | 9647/30196 [20:11<30:00, 11.41it/s]

 32%|███▏      | 9649/30196 [20:11<30:32, 11.21it/s]

 32%|███▏      | 9651/30196 [20:11<33:37, 10.18it/s]

 32%|███▏      | 9653/30196 [20:11<36:26,  9.40it/s]

 32%|███▏      | 9655/30196 [20:12<43:38,  7.85it/s]

 32%|███▏      | 9656/30196 [20:12<42:15,  8.10it/s]

 32%|███▏      | 9657/30196 [20:12<52:48,  6.48it/s]

 32%|███▏      | 9658/30196 [20:12<57:29,  5.95it/s]

 32%|███▏      | 9659/30196 [20:12<55:12,  6.20it/s]

 32%|███▏      | 9661/30196 [20:13<45:09,  7.58it/s]

 32%|███▏      | 9663/30196 [20:13<36:43,  9.32it/s]

 32%|███▏      | 9665/30196 [20:13<42:09,  8.12it/s]

 32%|███▏      | 9666/30196 [20:13<49:21,  6.93it/s]

 32%|███▏      | 9669/30196 [20:14<1:03:48,  5.36it/s]

 32%|███▏      | 9670/30196 [20:14<1:00:24,  5.66it/s]

 32%|███▏      | 9672/30196 [20:14<48:49,  7.00it/s]

 32%|███▏      | 9673/30196 [20:14<49:43,  6.88it/s]

 32%|███▏      | 9674/30196 [20:15<54:09,  6.31it/s]

 32%|███▏      | 9675/30196 [20:15<49:46,  6.87it/s]

 32%|███▏      | 9676/30196 [20:15<46:15,  7.39it/s]

 32%|███▏      | 9678/30196 [20:15<42:18,  8.08it/s]

 32%|███▏      | 9679/30196 [20:15<42:50,  7.98it/s]

 32%|███▏      | 9680/30196 [20:15<46:33,  7.35it/s]

 32%|███▏      | 9681/30196 [20:16<50:16,  6.80it/s]

 32%|███▏      | 9683/30196 [20:16<41:36,  8.22it/s]

 32%|███▏      | 9684/30196 [20:16<40:15,  8.49it/s]

 32%|███▏      | 9686/30196 [20:16<36:27,  9.38it/s]

 32%|███▏      | 9688/30196 [20:16<37:13,  9.18it/s]

 32%|███▏      | 9689/30196 [20:16<44:29,  7.68it/s]

 32%|███▏      | 9690/30196 [20:17<45:14,  7.55it/s]

 32%|███▏      | 9692/30196 [20:17<47:22,  7.21it/s]

 32%|███▏      | 9693/30196 [20:17<45:11,  7.56it/s]

 32%|███▏      | 9694/30196 [20:17<45:53,  7.44it/s]

 32%|███▏      | 9696/30196 [20:17<40:29,  8.44it/s]

 32%|███▏      | 9697/30196 [20:17<45:09,  7.57it/s]

 32%|███▏      | 9698/30196 [20:18<48:09,  7.10it/s]

 32%|███▏      | 9700/30196 [20:18<43:34,  7.84it/s]

 32%|███▏      | 9701/30196 [20:18<43:51,  7.79it/s]

 32%|███▏      | 9702/30196 [20:18<46:56,  7.28it/s]

 32%|███▏      | 9704/30196 [20:18<37:26,  9.12it/s]

 32%|███▏      | 9707/30196 [20:18<29:20, 11.64it/s]

 32%|███▏      | 9709/30196 [20:19<31:15, 10.93it/s]

 32%|███▏      | 9711/30196 [20:19<34:51,  9.80it/s]

 32%|███▏      | 9713/30196 [20:19<36:25,  9.37it/s]

 32%|███▏      | 9714/30196 [20:19<38:53,  8.78it/s]

 32%|███▏      | 9716/30196 [20:20<37:15,  9.16it/s]

 32%|███▏      | 9717/30196 [20:20<38:47,  8.80it/s]

 32%|███▏      | 9718/30196 [20:20<40:18,  8.47it/s]

 32%|███▏      | 9719/30196 [20:20<48:30,  7.04it/s]

 32%|███▏      | 9720/30196 [20:20<58:18,  5.85it/s]

 32%|███▏      | 9721/30196 [20:20<52:42,  6.47it/s]

 32%|███▏      | 9722/30196 [20:21<59:02,  5.78it/s]

 32%|███▏      | 9724/30196 [20:21<47:40,  7.16it/s]

 32%|███▏      | 9725/30196 [20:21<44:51,  7.61it/s]

 32%|███▏      | 9727/30196 [20:21<39:15,  8.69it/s]

 32%|███▏      | 9728/30196 [20:21<43:05,  7.92it/s]

 32%|███▏      | 9729/30196 [20:22<53:49,  6.34it/s]

 32%|███▏      | 9730/30196 [20:22<55:14,  6.17it/s]

 32%|███▏      | 9732/30196 [20:22<45:59,  7.41it/s]

 32%|███▏      | 9733/30196 [20:22<44:02,  7.74it/s]

 32%|███▏      | 9734/30196 [20:22<44:46,  7.62it/s]

 32%|███▏      | 9735/30196 [20:22<42:21,  8.05it/s]

 32%|███▏      | 9736/30196 [20:22<46:34,  7.32it/s]

 32%|███▏      | 9737/30196 [20:23<44:04,  7.74it/s]

 32%|███▏      | 9738/30196 [20:23<44:36,  7.64it/s]

 32%|███▏      | 9740/30196 [20:23<34:28,  9.89it/s]

 32%|███▏      | 9742/30196 [20:23<40:36,  8.39it/s]

 32%|███▏      | 9744/30196 [20:23<38:08,  8.94it/s]

 32%|███▏      | 9745/30196 [20:23<39:46,  8.57it/s]

 32%|███▏      | 9746/30196 [20:24<43:53,  7.77it/s]

 32%|███▏      | 9747/30196 [20:24<50:45,  6.72it/s]

 32%|███▏      | 9749/30196 [20:24<41:19,  8.25it/s]

 32%|███▏      | 9750/30196 [20:24<43:20,  7.86it/s]

 32%|███▏      | 9752/30196 [20:24<40:31,  8.41it/s]

 32%|███▏      | 9753/30196 [20:24<39:31,  8.62it/s]

 32%|███▏      | 9755/30196 [20:25<30:58, 11.00it/s]

 32%|███▏      | 9757/30196 [20:25<42:37,  7.99it/s]

 32%|███▏      | 9759/30196 [20:25<45:31,  7.48it/s]

 32%|███▏      | 9761/30196 [20:25<42:28,  8.02it/s]

 32%|███▏      | 9762/30196 [20:26<45:36,  7.47it/s]

 32%|███▏      | 9763/30196 [20:26<46:32,  7.32it/s]

 32%|███▏      | 9764/30196 [20:26<53:56,  6.31it/s]

 32%|███▏      | 9766/30196 [20:26<39:17,  8.67it/s]

 32%|███▏      | 9768/30196 [20:26<38:07,  8.93it/s]

 32%|███▏      | 9770/30196 [20:26<32:12, 10.57it/s]

 32%|███▏      | 9772/30196 [20:27<36:05,  9.43it/s]

 32%|███▏      | 9774/30196 [20:27<34:34,  9.85it/s]

 32%|███▏      | 9776/30196 [20:27<35:03,  9.71it/s]

 32%|███▏      | 9778/30196 [20:27<35:42,  9.53it/s]

 32%|███▏      | 9780/30196 [20:28<37:29,  9.08it/s]

 32%|███▏      | 9782/30196 [20:28<34:31,  9.86it/s]

 32%|███▏      | 9784/30196 [20:28<39:16,  8.66it/s]

 32%|███▏      | 9785/30196 [20:28<40:27,  8.41it/s]

 32%|███▏      | 9788/30196 [20:28<29:32, 11.51it/s]

 32%|███▏      | 9790/30196 [20:28<30:35, 11.12it/s]

 32%|███▏      | 9792/30196 [20:29<35:20,  9.62it/s]

 32%|███▏      | 9794/30196 [20:29<33:51, 10.04it/s]

 32%|███▏      | 9796/30196 [20:29<35:42,  9.52it/s]

 32%|███▏      | 9798/30196 [20:29<42:06,  8.07it/s]

 32%|███▏      | 9800/30196 [20:30<40:10,  8.46it/s]

 32%|███▏      | 9801/30196 [20:30<41:50,  8.12it/s]

 32%|███▏      | 9803/30196 [20:30<49:37,  6.85it/s]

 32%|███▏      | 9805/30196 [20:30<42:38,  7.97it/s]

 32%|███▏      | 9807/30196 [20:31<39:37,  8.58it/s]

 32%|███▏      | 9808/30196 [20:31<48:50,  6.96it/s]

 32%|███▏      | 9809/30196 [20:31<47:54,  7.09it/s]

 32%|███▏      | 9810/30196 [20:31<58:02,  5.85it/s]

 32%|███▏      | 9811/30196 [20:31<52:57,  6.42it/s]

 32%|███▏      | 9812/30196 [20:31<54:17,  6.26it/s]

 33%|███▎      | 9814/30196 [20:32<44:35,  7.62it/s]

 33%|███▎      | 9817/30196 [20:32<32:47, 10.36it/s]

 33%|███▎      | 9819/30196 [20:32<34:07,  9.95it/s]

 33%|███▎      | 9821/30196 [20:32<33:19, 10.19it/s]

 33%|███▎      | 9823/30196 [20:32<30:28, 11.14it/s]

 33%|███▎      | 9825/30196 [20:33<29:15, 11.60it/s]

 33%|███▎      | 9827/30196 [20:33<31:28, 10.78it/s]

 33%|███▎      | 9829/30196 [20:33<37:52,  8.96it/s]

 33%|███▎      | 9830/30196 [20:33<37:47,  8.98it/s]

 33%|███▎      | 9832/30196 [20:33<36:20,  9.34it/s]

 33%|███▎      | 9833/30196 [20:34<38:06,  8.90it/s]

 33%|███▎      | 9834/30196 [20:34<37:56,  8.94it/s]

 33%|███▎      | 9836/30196 [20:34<36:20,  9.34it/s]

 33%|███▎      | 9837/30196 [20:34<39:16,  8.64it/s]

 33%|███▎      | 9838/30196 [20:34<38:48,  8.74it/s]

 33%|███▎      | 9840/30196 [20:34<33:24, 10.16it/s]

 33%|███▎      | 9842/30196 [20:34<30:26, 11.15it/s]

 33%|███▎      | 9844/30196 [20:35<29:34, 11.47it/s]

 33%|███▎      | 9846/30196 [20:35<33:47, 10.04it/s]

 33%|███▎      | 9848/30196 [20:35<39:45,  8.53it/s]

 33%|███▎      | 9849/30196 [20:35<41:08,  8.24it/s]

 33%|███▎      | 9850/30196 [20:35<44:54,  7.55it/s]

 33%|███▎      | 9852/30196 [20:36<34:30,  9.82it/s]

 33%|███▎      | 9854/30196 [20:36<38:48,  8.74it/s]

 33%|███▎      | 9856/30196 [20:36<41:32,  8.16it/s]

 33%|███▎      | 9857/30196 [20:36<42:17,  8.01it/s]

 33%|███▎      | 9858/30196 [20:36<43:23,  7.81it/s]

 33%|███▎      | 9859/30196 [20:37<44:52,  7.55it/s]

 33%|███▎      | 9861/30196 [20:37<41:59,  8.07it/s]

 33%|███▎      | 9862/30196 [20:37<42:50,  7.91it/s]

 33%|███▎      | 9864/30196 [20:37<35:26,  9.56it/s]

 33%|███▎      | 9865/30196 [20:37<37:19,  9.08it/s]

 33%|███▎      | 9867/30196 [20:37<37:57,  8.92it/s]

 33%|███▎      | 9869/30196 [20:37<31:48, 10.65it/s]

 33%|███▎      | 9871/30196 [20:38<29:57, 11.31it/s]

 33%|███▎      | 9873/30196 [20:38<30:40, 11.04it/s]

 33%|███▎      | 9875/30196 [20:38<29:09, 11.62it/s]

 33%|███▎      | 9877/30196 [20:38<26:58, 12.55it/s]

 33%|███▎      | 9879/30196 [20:38<35:17,  9.59it/s]

 33%|███▎      | 9881/30196 [20:39<35:08,  9.63it/s]

 33%|███▎      | 9883/30196 [20:39<37:06,  9.12it/s]

 33%|███▎      | 9885/30196 [20:39<34:52,  9.71it/s]

 33%|███▎      | 9887/30196 [20:39<38:52,  8.71it/s]

 33%|███▎      | 9888/30196 [20:40<45:13,  7.48it/s]

 33%|███▎      | 9889/30196 [20:40<43:13,  7.83it/s]

 33%|███▎      | 9890/30196 [20:40<41:31,  8.15it/s]

 33%|███▎      | 9892/30196 [20:40<35:03,  9.65it/s]

 33%|███▎      | 9894/30196 [20:40<35:22,  9.57it/s]

 33%|███▎      | 9895/30196 [20:40<38:15,  8.85it/s]

 33%|███▎      | 9896/30196 [20:40<39:56,  8.47it/s]

 33%|███▎      | 9897/30196 [20:41<41:45,  8.10it/s]

 33%|███▎      | 9899/30196 [20:41<32:39, 10.36it/s]

 33%|███▎      | 9901/30196 [20:41<41:38,  8.12it/s]

 33%|███▎      | 9902/30196 [20:41<42:31,  7.95it/s]

 33%|███▎      | 9904/30196 [20:41<36:50,  9.18it/s]

 33%|███▎      | 9905/30196 [20:41<36:55,  9.16it/s]

 33%|███▎      | 9906/30196 [20:42<38:53,  8.69it/s]

 33%|███▎      | 9907/30196 [20:42<47:02,  7.19it/s]

 33%|███▎      | 9909/30196 [20:42<42:54,  7.88it/s]

 33%|███▎      | 9910/30196 [20:42<46:01,  7.35it/s]

 33%|███▎      | 9912/30196 [20:42<40:38,  8.32it/s]

 33%|███▎      | 9914/30196 [20:42<33:54,  9.97it/s]

 33%|███▎      | 9916/30196 [20:43<31:13, 10.82it/s]

 33%|███▎      | 9918/30196 [20:43<32:11, 10.50it/s]

 33%|███▎      | 9920/30196 [20:43<35:44,  9.45it/s]

 33%|███▎      | 9921/30196 [20:43<35:41,  9.47it/s]

 33%|███▎      | 9922/30196 [20:43<35:36,  9.49it/s]

 33%|███▎      | 9923/30196 [20:43<37:32,  9.00it/s]

 33%|███▎      | 9924/30196 [20:44<1:04:24,  5.25it/s]

 33%|███▎      | 9926/30196 [20:44<57:47,  5.85it/s]

 33%|███▎      | 9928/30196 [20:44<43:28,  7.77it/s]

 33%|███▎      | 9930/30196 [20:44<40:09,  8.41it/s]

 33%|███▎      | 9932/30196 [20:45<46:11,  7.31it/s]

 33%|███▎      | 9933/30196 [20:45<44:30,  7.59it/s]

 33%|███▎      | 9934/30196 [20:45<46:53,  7.20it/s]

 33%|███▎      | 9936/30196 [20:45<43:30,  7.76it/s]

 33%|███▎      | 9937/30196 [20:45<46:43,  7.23it/s]

 33%|███▎      | 9938/30196 [20:46<46:26,  7.27it/s]

 33%|███▎      | 9939/30196 [20:46<44:05,  7.66it/s]

 33%|███▎      | 9941/30196 [20:46<35:48,  9.43it/s]

 33%|███▎      | 9943/30196 [20:46<31:53, 10.59it/s]

 33%|███▎      | 9945/30196 [20:46<38:38,  8.74it/s]

 33%|███▎      | 9946/30196 [20:46<39:45,  8.49it/s]

 33%|███▎      | 9947/30196 [20:47<40:41,  8.29it/s]

 33%|███▎      | 9949/30196 [20:47<33:52,  9.96it/s]

 33%|███▎      | 9951/30196 [20:47<34:23,  9.81it/s]

 33%|███▎      | 9953/30196 [20:47<36:28,  9.25it/s]

 33%|███▎      | 9955/30196 [20:47<33:35, 10.04it/s]

 33%|███▎      | 9957/30196 [20:48<37:29,  9.00it/s]

 33%|███▎      | 9959/30196 [20:48<39:09,  8.61it/s]

 33%|███▎      | 9960/30196 [20:48<40:03,  8.42it/s]

 33%|███▎      | 9961/30196 [20:48<49:48,  6.77it/s]

 33%|███▎      | 9962/30196 [20:48<48:54,  6.90it/s]

 33%|███▎      | 9965/30196 [20:49<39:20,  8.57it/s]

 33%|███▎      | 9967/30196 [20:49<36:49,  9.15it/s]

 33%|███▎      | 9969/30196 [20:49<31:57, 10.55it/s]

 33%|███▎      | 9971/30196 [20:49<33:46,  9.98it/s]

 33%|███▎      | 9973/30196 [20:49<39:27,  8.54it/s]

 33%|███▎      | 9974/30196 [20:50<42:52,  7.86it/s]

 33%|███▎      | 9976/30196 [20:50<39:34,  8.51it/s]

 33%|███▎      | 9977/30196 [20:50<40:24,  8.34it/s]

 33%|███▎      | 9978/30196 [20:50<41:30,  8.12it/s]

 33%|███▎      | 9980/30196 [20:50<33:27, 10.07it/s]

 33%|███▎      | 9982/30196 [20:50<30:19, 11.11it/s]

 33%|███▎      | 9984/30196 [20:51<38:13,  8.81it/s]

 33%|███▎      | 9985/30196 [20:51<38:01,  8.86it/s]

 33%|███▎      | 9987/30196 [20:51<40:31,  8.31it/s]

 33%|███▎      | 9988/30196 [20:51<41:15,  8.16it/s]

 33%|███▎      | 9989/30196 [20:51<44:42,  7.53it/s]

 33%|███▎      | 9991/30196 [20:52<40:53,  8.23it/s]

 33%|███▎      | 9992/30196 [20:52<42:47,  7.87it/s]

 33%|███▎      | 9994/30196 [20:52<44:20,  7.59it/s]

 33%|███▎      | 9996/30196 [20:52<35:42,  9.43it/s]

 33%|███▎      | 9998/30196 [20:52<37:27,  8.99it/s]

 33%|███▎      | 9999/30196 [20:53<43:42,  7.70it/s]

 33%|███▎      | 10000/30196 [20:53<42:09,  7.98it/s]

 33%|███▎      | 10001/30196 [20:53<42:34,  7.90it/s]

 33%|███▎      | 10002/30196 [20:53<46:10,  7.29it/s]

 33%|███▎      | 10003/30196 [20:53<50:01,  6.73it/s]

 33%|███▎      | 10004/30196 [20:53<48:18,  6.97it/s]

 33%|███▎      | 10005/30196 [20:53<47:04,  7.15it/s]

 33%|███▎      | 10007/30196 [20:54<34:03,  9.88it/s]

 33%|███▎      | 10009/30196 [20:54<33:47,  9.95it/s]

 33%|███▎      | 10011/30196 [20:54<33:22, 10.08it/s]

 33%|███▎      | 10013/30196 [20:54<32:09, 10.46it/s]

 33%|███▎      | 10015/30196 [20:54<28:56, 11.62it/s]

 33%|███▎      | 10017/30196 [20:55<42:25,  7.93it/s]

 33%|███▎      | 10019/30196 [20:55<39:08,  8.59it/s]

 33%|███▎      | 10021/30196 [20:55<45:00,  7.47it/s]

 33%|███▎      | 10022/30196 [20:55<49:28,  6.80it/s]

 33%|███▎      | 10024/30196 [20:56<38:22,  8.76it/s]

 33%|███▎      | 10026/30196 [20:56<1:02:03,  5.42it/s]

 33%|███▎      | 10027/30196 [20:56<58:50,  5.71it/s]

 33%|███▎      | 10029/30196 [20:57<53:39,  6.26it/s]

 33%|███▎      | 10030/30196 [20:57<54:04,  6.21it/s]

 33%|███▎      | 10031/30196 [20:57<51:46,  6.49it/s]

 33%|███▎      | 10033/30196 [20:57<49:47,  6.75it/s]

 33%|███▎      | 10034/30196 [20:57<57:23,  5.86it/s]

 33%|███▎      | 10036/30196 [20:58<50:17,  6.68it/s]

 33%|███▎      | 10037/30196 [20:58<49:10,  6.83it/s]

 33%|███▎      | 10039/30196 [20:58<42:16,  7.95it/s]

 33%|███▎      | 10041/30196 [20:58<42:29,  7.91it/s]

 33%|███▎      | 10043/30196 [20:58<40:04,  8.38it/s]

 33%|███▎      | 10044/30196 [20:59<39:09,  8.58it/s]

 33%|███▎      | 10045/30196 [20:59<40:14,  8.35it/s]

 33%|███▎      | 10046/30196 [20:59<43:51,  7.66it/s]

 33%|███▎      | 10047/30196 [20:59<46:48,  7.17it/s]

 33%|███▎      | 10048/30196 [20:59<46:03,  7.29it/s]

 33%|███▎      | 10049/30196 [20:59<45:24,  7.39it/s]

 33%|███▎      | 10051/30196 [20:59<35:56,  9.34it/s]

 33%|███▎      | 10053/30196 [21:00<39:23,  8.52it/s]

 33%|███▎      | 10054/30196 [21:00<40:21,  8.32it/s]

 33%|███▎      | 10056/30196 [21:00<35:32,  9.44it/s]

 33%|███▎      | 10057/30196 [21:00<35:49,  9.37it/s]

 33%|███▎      | 10058/30196 [21:00<44:05,  7.61it/s]

 33%|███▎      | 10059/30196 [21:00<47:48,  7.02it/s]

 33%|███▎      | 10061/30196 [21:01<40:21,  8.32it/s]

 33%|███▎      | 10062/30196 [21:01<41:07,  8.16it/s]

 33%|███▎      | 10064/30196 [21:01<41:43,  8.04it/s]

 33%|███▎      | 10066/30196 [21:01<38:25,  8.73it/s]

 33%|███▎      | 10067/30196 [21:01<37:43,  8.89it/s]

 33%|███▎      | 10069/30196 [21:02<35:25,  9.47it/s]

 33%|███▎      | 10070/30196 [21:02<39:33,  8.48it/s]

 33%|███▎      | 10072/30196 [21:02<37:09,  9.03it/s]

 33%|███▎      | 10074/30196 [21:02<36:16,  9.25it/s]

 33%|███▎      | 10076/30196 [21:02<35:08,  9.54it/s]

 33%|███▎      | 10077/30196 [21:02<39:33,  8.48it/s]

 33%|███▎      | 10080/30196 [21:03<32:01, 10.47it/s]

 33%|███▎      | 10082/30196 [21:03<33:11, 10.10it/s]

 33%|███▎      | 10084/30196 [21:03<35:04,  9.56it/s]

 33%|███▎      | 10086/30196 [21:03<35:38,  9.41it/s]

 33%|███▎      | 10088/30196 [21:04<36:01,  9.30it/s]

 33%|███▎      | 10089/30196 [21:04<39:30,  8.48it/s]

 33%|███▎      | 10090/30196 [21:04<40:20,  8.31it/s]

 33%|███▎      | 10091/30196 [21:04<39:20,  8.52it/s]

 33%|███▎      | 10092/30196 [21:04<40:21,  8.30it/s]

 33%|███▎      | 10094/30196 [21:04<33:47,  9.92it/s]

 33%|███▎      | 10095/30196 [21:04<34:19,  9.76it/s]

 33%|███▎      | 10096/30196 [21:04<36:57,  9.07it/s]

 33%|███▎      | 10097/30196 [21:05<41:48,  8.01it/s]

 33%|███▎      | 10098/30196 [21:05<42:49,  7.82it/s]

 33%|███▎      | 10100/30196 [21:05<34:58,  9.57it/s]

 33%|███▎      | 10102/30196 [21:05<37:52,  8.84it/s]

 33%|███▎      | 10104/30196 [21:05<39:34,  8.46it/s]

 33%|███▎      | 10105/30196 [21:06<40:41,  8.23it/s]

 33%|███▎      | 10106/30196 [21:06<41:37,  8.04it/s]

 33%|███▎      | 10107/30196 [21:06<42:06,  7.95it/s]

 33%|███▎      | 10108/30196 [21:06<48:58,  6.84it/s]

 33%|███▎      | 10109/30196 [21:06<54:24,  6.15it/s]

 33%|███▎      | 10110/30196 [21:06<55:49,  6.00it/s]

 33%|███▎      | 10111/30196 [21:07<57:08,  5.86it/s]

 33%|███▎      | 10112/30196 [21:07<51:12,  6.54it/s]

 33%|███▎      | 10113/30196 [21:07<52:31,  6.37it/s]

 33%|███▎      | 10114/30196 [21:07<49:51,  6.71it/s]

 34%|███▎      | 10116/30196 [21:07<44:37,  7.50it/s]

 34%|███▎      | 10117/30196 [21:07<42:39,  7.84it/s]

 34%|███▎      | 10119/30196 [21:07<33:10, 10.09it/s]

 34%|███▎      | 10121/30196 [21:08<49:40,  6.73it/s]

 34%|███▎      | 10122/30196 [21:08<49:32,  6.75it/s]

 34%|███▎      | 10123/30196 [21:08<51:36,  6.48it/s]

 34%|███▎      | 10125/30196 [21:08<44:03,  7.59it/s]

 34%|███▎      | 10126/30196 [21:09<43:56,  7.61it/s]

 34%|███▎      | 10127/30196 [21:09<45:01,  7.43it/s]

 34%|███▎      | 10128/30196 [21:09<45:28,  7.35it/s]

 34%|███▎      | 10130/30196 [21:09<35:43,  9.36it/s]

 34%|███▎      | 10131/30196 [21:09<35:29,  9.42it/s]

 34%|███▎      | 10133/30196 [21:09<34:07,  9.80it/s]

 34%|███▎      | 10134/30196 [21:09<41:47,  8.00it/s]

 34%|███▎      | 10135/30196 [21:10<42:34,  7.85it/s]

 34%|███▎      | 10137/30196 [21:10<53:58,  6.19it/s]

 34%|███▎      | 10139/30196 [21:10<45:09,  7.40it/s]

 34%|███▎      | 10140/30196 [21:10<42:59,  7.78it/s]

 34%|███▎      | 10142/30196 [21:11<38:38,  8.65it/s]

 34%|███▎      | 10144/30196 [21:11<35:04,  9.53it/s]

 34%|███▎      | 10146/30196 [21:11<33:38,  9.93it/s]

 34%|███▎      | 10148/30196 [21:11<37:21,  8.94it/s]

 34%|███▎      | 10149/30196 [21:11<38:43,  8.63it/s]

 34%|███▎      | 10150/30196 [21:11<40:26,  8.26it/s]

 34%|███▎      | 10152/30196 [21:12<39:16,  8.51it/s]

 34%|███▎      | 10154/30196 [21:12<34:19,  9.73it/s]

 34%|███▎      | 10155/30196 [21:12<36:11,  9.23it/s]

 34%|███▎      | 10157/30196 [21:12<33:47,  9.89it/s]

 34%|███▎      | 10158/30196 [21:12<34:04,  9.80it/s]

 34%|███▎      | 10159/30196 [21:12<38:52,  8.59it/s]

 34%|███▎      | 10160/30196 [21:12<40:27,  8.25it/s]

 34%|███▎      | 10161/30196 [21:13<41:14,  8.10it/s]

 34%|███▎      | 10162/30196 [21:13<40:03,  8.34it/s]

 34%|███▎      | 10163/30196 [21:13<42:29,  7.86it/s]

 34%|███▎      | 10165/30196 [21:13<31:15, 10.68it/s]

 34%|███▎      | 10167/30196 [21:13<47:39,  7.00it/s]

 34%|███▎      | 10168/30196 [21:14<1:05:15,  5.11it/s]

 34%|███▎      | 10169/30196 [21:14<1:06:30,  5.02it/s]

 34%|███▎      | 10170/30196 [21:15<1:33:04,  3.59it/s]

 34%|███▎      | 10172/30196 [21:15<1:09:59,  4.77it/s]

 34%|███▎      | 10173/30196 [21:15<1:02:19,  5.35it/s]

 34%|███▎      | 10175/30196 [21:15<46:54,  7.11it/s]

 34%|███▎      | 10176/30196 [21:15<44:13,  7.55it/s]

 34%|███▎      | 10177/30196 [21:15<45:19,  7.36it/s]

 34%|███▎      | 10179/30196 [21:16<43:21,  7.69it/s]

 34%|███▎      | 10180/30196 [21:16<49:03,  6.80it/s]

 34%|███▎      | 10181/30196 [21:16<48:47,  6.84it/s]

 34%|███▎      | 10183/30196 [21:16<38:32,  8.65it/s]

 34%|███▎      | 10184/30196 [21:16<42:59,  7.76it/s]

 34%|███▎      | 10186/30196 [21:16<34:00,  9.81it/s]

 34%|███▎      | 10188/30196 [21:16<28:52, 11.55it/s]

 34%|███▎      | 10190/30196 [21:17<31:21, 10.63it/s]

 34%|███▍      | 10192/30196 [21:17<28:35, 11.66it/s]

 34%|███▍      | 10194/30196 [21:17<38:42,  8.61it/s]

 34%|███▍      | 10196/30196 [21:17<44:37,  7.47it/s]

 34%|███▍      | 10197/30196 [21:18<48:13,  6.91it/s]

 34%|███▍      | 10198/30196 [21:18<49:54,  6.68it/s]

 34%|███▍      | 10199/30196 [21:18<48:43,  6.84it/s]

 34%|███▍      | 10200/30196 [21:18<47:44,  6.98it/s]

 34%|███▍      | 10202/30196 [21:18<40:12,  8.29it/s]

 34%|███▍      | 10204/30196 [21:19<38:57,  8.55it/s]

 34%|███▍      | 10205/30196 [21:19<40:16,  8.27it/s]

 34%|███▍      | 10207/30196 [21:19<39:50,  8.36it/s]

 34%|███▍      | 10208/30196 [21:19<38:48,  8.58it/s]

 34%|███▍      | 10210/30196 [21:19<42:42,  7.80it/s]

 34%|███▍      | 10211/30196 [21:19<43:15,  7.70it/s]

 34%|███▍      | 10212/30196 [21:20<51:17,  6.49it/s]

 34%|███▍      | 10213/30196 [21:20<47:23,  7.03it/s]

 34%|███▍      | 10214/30196 [21:20<44:06,  7.55it/s]

 34%|███▍      | 10215/30196 [21:20<47:55,  6.95it/s]

 34%|███▍      | 10216/30196 [21:20<50:02,  6.65it/s]

 34%|███▍      | 10218/30196 [21:20<40:41,  8.18it/s]

 34%|███▍      | 10219/30196 [21:21<45:18,  7.35it/s]

 34%|███▍      | 10220/30196 [21:21<43:05,  7.73it/s]

 34%|███▍      | 10221/30196 [21:21<40:56,  8.13it/s]

 34%|███▍      | 10222/30196 [21:21<46:13,  7.20it/s]

 34%|███▍      | 10223/30196 [21:21<46:27,  7.17it/s]

 34%|███▍      | 10224/30196 [21:21<48:52,  6.81it/s]

 34%|███▍      | 10225/30196 [21:21<45:20,  7.34it/s]

 34%|███▍      | 10226/30196 [21:21<42:42,  7.79it/s]

 34%|███▍      | 10227/30196 [21:22<40:37,  8.19it/s]

 34%|███▍      | 10228/30196 [21:22<45:03,  7.39it/s]

 34%|███▍      | 10230/30196 [21:22<32:35, 10.21it/s]

 34%|███▍      | 10232/30196 [21:22<27:19, 12.18it/s]

 34%|███▍      | 10234/30196 [21:22<29:18, 11.35it/s]

 34%|███▍      | 10236/30196 [21:22<30:40, 10.85it/s]

 34%|███▍      | 10238/30196 [21:23<34:26,  9.66it/s]

 34%|███▍      | 10240/30196 [21:23<34:38,  9.60it/s]

 34%|███▍      | 10242/30196 [21:23<39:21,  8.45it/s]

 34%|███▍      | 10243/30196 [21:23<40:12,  8.27it/s]

 34%|███▍      | 10245/30196 [21:23<36:35,  9.09it/s]

 34%|███▍      | 10246/30196 [21:24<43:16,  7.68it/s]

 34%|███▍      | 10247/30196 [21:24<41:22,  8.03it/s]

 34%|███▍      | 10248/30196 [21:24<45:47,  7.26it/s]

 34%|███▍      | 10249/30196 [21:24<43:05,  7.72it/s]

 34%|███▍      | 10251/30196 [21:24<33:47,  9.84it/s]

 34%|███▍      | 10253/30196 [21:24<32:40, 10.17it/s]

 34%|███▍      | 10255/30196 [21:25<34:53,  9.53it/s]

 34%|███▍      | 10257/30196 [21:25<38:12,  8.70it/s]

 34%|███▍      | 10258/30196 [21:25<39:26,  8.43it/s]

 34%|███▍      | 10259/30196 [21:25<42:46,  7.77it/s]

 34%|███▍      | 10261/30196 [21:25<34:44,  9.56it/s]

 34%|███▍      | 10263/30196 [21:25<31:58, 10.39it/s]

 34%|███▍      | 10265/30196 [21:26<31:03, 10.70it/s]

 34%|███▍      | 10267/30196 [21:26<29:33, 11.24it/s]

 34%|███▍      | 10269/30196 [21:26<31:10, 10.65it/s]

 34%|███▍      | 10271/30196 [21:26<34:34,  9.61it/s]

 34%|███▍      | 10273/30196 [21:26<31:14, 10.63it/s]

 34%|███▍      | 10275/30196 [21:27<34:19,  9.67it/s]

 34%|███▍      | 10277/30196 [21:27<34:16,  9.69it/s]

 34%|███▍      | 10279/30196 [21:27<41:46,  7.95it/s]

 34%|███▍      | 10280/30196 [21:27<40:33,  8.19it/s]

 34%|███▍      | 10281/30196 [21:28<52:45,  6.29it/s]

 34%|███▍      | 10283/30196 [21:28<42:16,  7.85it/s]

 34%|███▍      | 10285/30196 [21:28<36:02,  9.21it/s]

 34%|███▍      | 10287/30196 [21:28<32:54, 10.08it/s]

 34%|███▍      | 10289/30196 [21:28<32:25, 10.23it/s]

 34%|███▍      | 10291/30196 [21:28<29:13, 11.35it/s]

 34%|███▍      | 10293/30196 [21:29<31:02, 10.68it/s]

 34%|███▍      | 10295/30196 [21:29<33:55,  9.78it/s]

 34%|███▍      | 10297/30196 [21:29<33:26,  9.92it/s]

 34%|███▍      | 10299/30196 [21:30<53:06,  6.24it/s]

 34%|███▍      | 10300/30196 [21:30<52:08,  6.36it/s]

 34%|███▍      | 10301/30196 [21:30<48:53,  6.78it/s]

 34%|███▍      | 10302/30196 [21:30<50:10,  6.61it/s]

 34%|███▍      | 10303/30196 [21:30<58:08,  5.70it/s]

 34%|███▍      | 10304/30196 [21:30<57:55,  5.72it/s]

 34%|███▍      | 10305/30196 [21:31<55:31,  5.97it/s]

 34%|███▍      | 10306/30196 [21:31<50:11,  6.61it/s]

 34%|███▍      | 10308/30196 [21:31<40:32,  8.17it/s]

 34%|███▍      | 10309/30196 [21:31<47:10,  7.03it/s]

 34%|███▍      | 10311/30196 [21:31<37:46,  8.77it/s]

 34%|███▍      | 10312/30196 [21:31<37:27,  8.85it/s]

 34%|███▍      | 10313/30196 [21:32<41:57,  7.90it/s]

 34%|███▍      | 10315/30196 [21:32<36:59,  8.96it/s]

 34%|███▍      | 10316/30196 [21:32<36:53,  8.98it/s]

 34%|███▍      | 10318/30196 [21:32<29:55, 11.07it/s]

 34%|███▍      | 10320/30196 [21:32<28:01, 11.82it/s]

 34%|███▍      | 10322/30196 [21:32<30:51, 10.73it/s]

 34%|███▍      | 10324/30196 [21:32<30:24, 10.89it/s]

 34%|███▍      | 10326/30196 [21:33<33:03, 10.02it/s]

 34%|███▍      | 10328/30196 [21:33<28:50, 11.48it/s]

 34%|███▍      | 10330/30196 [21:33<29:08, 11.36it/s]

 34%|███▍      | 10332/30196 [21:33<35:42,  9.27it/s]

 34%|███▍      | 10334/30196 [21:34<41:51,  7.91it/s]

 34%|███▍      | 10336/30196 [21:34<35:52,  9.23it/s]

 34%|███▍      | 10338/30196 [21:34<31:00, 10.67it/s]

 34%|███▍      | 10340/30196 [21:34<26:41, 12.40it/s]

 34%|███▍      | 10342/30196 [21:34<29:34, 11.19it/s]

 34%|███▍      | 10344/30196 [21:34<27:28, 12.04it/s]

 34%|███▍      | 10346/30196 [21:35<33:05, 10.00it/s]

 34%|███▍      | 10348/30196 [21:35<34:03,  9.71it/s]

 34%|███▍      | 10350/30196 [21:35<30:17, 10.92it/s]

 34%|███▍      | 10352/30196 [21:35<33:37,  9.83it/s]

 34%|███▍      | 10354/30196 [21:35<32:43, 10.11it/s]

 34%|███▍      | 10356/30196 [21:36<34:59,  9.45it/s]

 34%|███▍      | 10358/30196 [21:36<36:22,  9.09it/s]

 34%|███▍      | 10359/30196 [21:36<39:51,  8.29it/s]

 34%|███▍      | 10360/30196 [21:36<40:49,  8.10it/s]

 34%|███▍      | 10362/30196 [21:36<35:48,  9.23it/s]

 34%|███▍      | 10364/30196 [21:37<30:22, 10.88it/s]

 34%|███▍      | 10366/30196 [21:37<49:21,  6.70it/s]

 34%|███▍      | 10368/30196 [21:37<47:09,  7.01it/s]

 34%|███▍      | 10369/30196 [21:37<48:45,  6.78it/s]

 34%|███▍      | 10371/30196 [21:38<44:19,  7.45it/s]

 34%|███▍      | 10372/30196 [21:38<44:44,  7.38it/s]

 34%|███▍      | 10373/30196 [21:38<47:05,  7.02it/s]

 34%|███▍      | 10375/30196 [21:38<39:03,  8.46it/s]

 34%|███▍      | 10376/30196 [21:38<39:55,  8.27it/s]

 34%|███▍      | 10377/30196 [21:38<43:48,  7.54it/s]

 34%|███▍      | 10378/30196 [21:39<44:01,  7.50it/s]

 34%|███▍      | 10379/30196 [21:39<43:47,  7.54it/s]

 34%|███▍      | 10381/30196 [21:39<39:53,  8.28it/s]

 34%|███▍      | 10383/30196 [21:39<39:15,  8.41it/s]

 34%|███▍      | 10385/30196 [21:39<32:10, 10.26it/s]

 34%|███▍      | 10387/30196 [21:39<29:59, 11.01it/s]

 34%|███▍      | 10389/30196 [21:40<42:15,  7.81it/s]

 34%|███▍      | 10390/30196 [21:40<45:22,  7.28it/s]

 34%|███▍      | 10392/30196 [21:40<37:40,  8.76it/s]

 34%|███▍      | 10394/30196 [21:40<37:46,  8.74it/s]

 34%|███▍      | 10395/30196 [21:41<38:46,  8.51it/s]

 34%|███▍      | 10396/30196 [21:41<38:12,  8.64it/s]

 34%|███▍      | 10398/30196 [21:41<43:48,  7.53it/s]

 34%|███▍      | 10399/30196 [21:41<42:09,  7.83it/s]

 34%|███▍      | 10400/30196 [21:41<42:39,  7.73it/s]

 34%|███▍      | 10401/30196 [21:41<43:38,  7.56it/s]

 34%|███▍      | 10402/30196 [21:41<41:15,  8.00it/s]

 34%|███▍      | 10403/30196 [21:42<44:55,  7.34it/s]

 34%|███▍      | 10404/30196 [21:42<42:28,  7.77it/s]

 34%|███▍      | 10405/30196 [21:42<40:10,  8.21it/s]

 34%|███▍      | 10406/30196 [21:42<38:31,  8.56it/s]

 34%|███▍      | 10407/30196 [21:42<39:47,  8.29it/s]

 34%|███▍      | 10408/30196 [21:42<43:58,  7.50it/s]

 34%|███▍      | 10409/30196 [21:42<48:40,  6.78it/s]

 34%|███▍      | 10411/30196 [21:43<42:27,  7.77it/s]

 34%|███▍      | 10413/30196 [21:43<40:46,  8.09it/s]

 34%|███▍      | 10415/30196 [21:43<32:13, 10.23it/s]

 34%|███▍      | 10417/30196 [21:43<38:23,  8.59it/s]

 35%|███▍      | 10418/30196 [21:43<39:18,  8.39it/s]

 35%|███▍      | 10419/30196 [21:44<41:23,  7.96it/s]

 35%|███▍      | 10420/30196 [21:44<40:09,  8.21it/s]

 35%|███▍      | 10421/30196 [21:44<41:43,  7.90it/s]

 35%|███▍      | 10422/30196 [21:44<41:49,  7.88it/s]

 35%|███▍      | 10424/30196 [21:44<42:04,  7.83it/s]

 35%|███▍      | 10425/30196 [21:44<49:24,  6.67it/s]

 35%|███▍      | 10426/30196 [21:45<50:41,  6.50it/s]

 35%|███▍      | 10427/30196 [21:45<46:51,  7.03it/s]

 35%|███▍      | 10428/30196 [21:45<1:01:34,  5.35it/s]

 35%|███▍      | 10429/30196 [21:45<54:28,  6.05it/s]

 35%|███▍      | 10430/30196 [21:45<51:36,  6.38it/s]

 35%|███▍      | 10432/30196 [21:45<46:30,  7.08it/s]

 35%|███▍      | 10433/30196 [21:46<47:06,  6.99it/s]

 35%|███▍      | 10434/30196 [21:46<46:59,  7.01it/s]

 35%|███▍      | 10435/30196 [21:46<46:31,  7.08it/s]

 35%|███▍      | 10436/30196 [21:46<46:24,  7.10it/s]

 35%|███▍      | 10438/30196 [21:46<47:01,  7.00it/s]

 35%|███▍      | 10440/30196 [21:47<47:40,  6.91it/s]

 35%|███▍      | 10441/30196 [21:47<46:37,  7.06it/s]

 35%|███▍      | 10442/30196 [21:47<48:43,  6.76it/s]

 35%|███▍      | 10444/30196 [21:47<36:22,  9.05it/s]

 35%|███▍      | 10446/30196 [21:47<36:43,  8.96it/s]

 35%|███▍      | 10447/30196 [21:47<41:04,  8.02it/s]

 35%|███▍      | 10448/30196 [21:48<44:15,  7.44it/s]

 35%|███▍      | 10449/30196 [21:48<53:51,  6.11it/s]

 35%|███▍      | 10450/30196 [21:48<54:46,  6.01it/s]

 35%|███▍      | 10451/30196 [21:48<49:44,  6.62it/s]

 35%|███▍      | 10452/30196 [21:48<51:41,  6.37it/s]

 35%|███▍      | 10453/30196 [21:48<50:40,  6.49it/s]

 35%|███▍      | 10455/30196 [21:49<1:16:44,  4.29it/s]

 35%|███▍      | 10457/30196 [21:49<1:02:03,  5.30it/s]

 35%|███▍      | 10459/30196 [21:50<51:02,  6.44it/s]

 35%|███▍      | 10460/30196 [21:50<1:01:41,  5.33it/s]

 35%|███▍      | 10462/30196 [21:50<52:01,  6.32it/s]

 35%|███▍      | 10463/30196 [21:50<55:43,  5.90it/s]

 35%|███▍      | 10464/30196 [21:50<55:37,  5.91it/s]

 35%|███▍      | 10466/30196 [21:51<49:45,  6.61it/s]

 35%|███▍      | 10468/30196 [21:51<47:02,  6.99it/s]

 35%|███▍      | 10469/30196 [21:51<46:15,  7.11it/s]

 35%|███▍      | 10470/30196 [21:51<46:15,  7.11it/s]

 35%|███▍      | 10471/30196 [21:51<46:15,  7.11it/s]

 35%|███▍      | 10473/30196 [21:52<38:48,  8.47it/s]

 35%|███▍      | 10474/30196 [21:52<1:02:16,  5.28it/s]

 35%|███▍      | 10475/30196 [21:52<55:31,  5.92it/s]

 35%|███▍      | 10476/30196 [21:52<53:32,  6.14it/s]

 35%|███▍      | 10477/30196 [21:52<51:26,  6.39it/s]

 35%|███▍      | 10478/30196 [21:53<49:55,  6.58it/s]

 35%|███▍      | 10480/30196 [21:53<48:59,  6.71it/s]

 35%|███▍      | 10481/30196 [21:53<45:57,  7.15it/s]

 35%|███▍      | 10482/30196 [21:53<45:35,  7.21it/s]

 35%|███▍      | 10484/30196 [21:53<34:32,  9.51it/s]

 35%|███▍      | 10486/30196 [21:53<37:17,  8.81it/s]

 35%|███▍      | 10488/30196 [21:54<35:13,  9.33it/s]

 35%|███▍      | 10489/30196 [21:54<39:21,  8.35it/s]

 35%|███▍      | 10490/30196 [21:54<42:41,  7.69it/s]

 35%|███▍      | 10491/30196 [21:54<40:40,  8.07it/s]

 35%|███▍      | 10492/30196 [21:54<42:04,  7.81it/s]

 35%|███▍      | 10493/30196 [21:54<39:56,  8.22it/s]

 35%|███▍      | 10495/30196 [21:54<36:40,  8.95it/s]

 35%|███▍      | 10496/30196 [21:55<36:34,  8.98it/s]

 35%|███▍      | 10497/30196 [21:55<36:29,  9.00it/s]

 35%|███▍      | 10499/30196 [21:55<30:10, 10.88it/s]

 35%|███▍      | 10501/30196 [21:55<35:09,  9.33it/s]

 35%|███▍      | 10502/30196 [21:56<1:04:09,  5.12it/s]

 35%|███▍      | 10504/30196 [21:56<52:56,  6.20it/s]

 35%|███▍      | 10506/30196 [21:56<45:51,  7.16it/s]

 35%|███▍      | 10507/30196 [21:56<45:30,  7.21it/s]

 35%|███▍      | 10509/30196 [21:56<37:00,  8.87it/s]

 35%|███▍      | 10511/30196 [21:57<39:41,  8.27it/s]

 35%|███▍      | 10513/30196 [21:57<32:37, 10.05it/s]

 35%|███▍      | 10515/30196 [21:57<37:14,  8.81it/s]

 35%|███▍      | 10517/30196 [21:57<44:13,  7.42it/s]

 35%|███▍      | 10518/30196 [21:57<42:28,  7.72it/s]

 35%|███▍      | 10519/30196 [21:58<40:50,  8.03it/s]

 35%|███▍      | 10520/30196 [21:58<42:00,  7.81it/s]

 35%|███▍      | 10521/30196 [21:58<57:48,  5.67it/s]

 35%|███▍      | 10522/30196 [21:58<51:40,  6.34it/s]

 35%|███▍      | 10523/30196 [21:58<55:55,  5.86it/s]

 35%|███▍      | 10525/30196 [21:59<57:24,  5.71it/s]

 35%|███▍      | 10526/30196 [21:59<52:22,  6.26it/s]

 35%|███▍      | 10527/30196 [21:59<51:17,  6.39it/s]

 35%|███▍      | 10528/30196 [21:59<50:00,  6.56it/s]

 35%|███▍      | 10530/30196 [21:59<45:58,  7.13it/s]

 35%|███▍      | 10532/30196 [21:59<37:53,  8.65it/s]

 35%|███▍      | 10534/30196 [22:00<34:03,  9.62it/s]

 35%|███▍      | 10536/30196 [22:00<36:17,  9.03it/s]

 35%|███▍      | 10537/30196 [22:00<35:53,  9.13it/s]

 35%|███▍      | 10539/30196 [22:00<38:11,  8.58it/s]

 35%|███▍      | 10540/30196 [22:00<41:39,  7.86it/s]

 35%|███▍      | 10541/30196 [22:01<44:28,  7.37it/s]

 35%|███▍      | 10542/30196 [22:01<45:25,  7.21it/s]

 35%|███▍      | 10543/30196 [22:01<44:39,  7.33it/s]

 35%|███▍      | 10544/30196 [22:01<44:37,  7.34it/s]

 35%|███▍      | 10545/30196 [22:01<44:59,  7.28it/s]

 35%|███▍      | 10546/30196 [22:01<42:23,  7.73it/s]

 35%|███▍      | 10549/30196 [22:02<33:11,  9.87it/s]

 35%|███▍      | 10550/30196 [22:02<37:51,  8.65it/s]

 35%|███▍      | 10552/30196 [22:02<33:47,  9.69it/s]

 35%|███▍      | 10553/30196 [22:02<44:17,  7.39it/s]

 35%|███▍      | 10554/30196 [22:02<46:33,  7.03it/s]

 35%|███▍      | 10556/30196 [22:02<40:33,  8.07it/s]

 35%|███▍      | 10557/30196 [22:03<42:13,  7.75it/s]

 35%|███▍      | 10559/30196 [22:03<38:46,  8.44it/s]

 35%|███▍      | 10561/30196 [22:03<34:39,  9.44it/s]

 35%|███▍      | 10563/30196 [22:03<31:03, 10.53it/s]

 35%|███▍      | 10565/30196 [22:03<35:37,  9.18it/s]

 35%|███▍      | 10566/30196 [22:04<44:21,  7.38it/s]

 35%|███▍      | 10568/30196 [22:04<43:47,  7.47it/s]

 35%|███▌      | 10570/30196 [22:04<36:38,  8.93it/s]

 35%|███▌      | 10571/30196 [22:04<40:55,  7.99it/s]

 35%|███▌      | 10572/30196 [22:04<41:35,  7.86it/s]

 35%|███▌      | 10574/30196 [22:05<36:00,  9.08it/s]

 35%|███▌      | 10575/30196 [22:05<37:46,  8.66it/s]

 35%|███▌      | 10576/30196 [22:05<36:59,  8.84it/s]

 35%|███▌      | 10578/30196 [22:05<36:32,  8.95it/s]

 35%|███▌      | 10580/30196 [22:05<35:49,  9.13it/s]

 35%|███▌      | 10581/30196 [22:05<42:47,  7.64it/s]

 35%|███▌      | 10583/30196 [22:06<36:01,  9.07it/s]

 35%|███▌      | 10584/30196 [22:06<36:02,  9.07it/s]

 35%|███▌      | 10586/30196 [22:06<39:48,  8.21it/s]

 35%|███▌      | 10587/30196 [22:06<41:10,  7.94it/s]

 35%|███▌      | 10588/30196 [22:06<41:34,  7.86it/s]

 35%|███▌      | 10590/30196 [22:06<32:44,  9.98it/s]

 35%|███▌      | 10592/30196 [22:07<45:10,  7.23it/s]

 35%|███▌      | 10593/30196 [22:07<44:54,  7.28it/s]

 35%|███▌      | 10594/30196 [22:07<44:23,  7.36it/s]

 35%|███▌      | 10596/30196 [22:07<38:31,  8.48it/s]

 35%|███▌      | 10597/30196 [22:07<42:14,  7.73it/s]

 35%|███▌      | 10599/30196 [22:08<39:57,  8.18it/s]

 35%|███▌      | 10600/30196 [22:08<40:35,  8.05it/s]

 35%|███▌      | 10602/30196 [22:08<37:06,  8.80it/s]

 35%|███▌      | 10604/30196 [22:08<36:49,  8.87it/s]

 35%|███▌      | 10605/30196 [22:08<38:42,  8.44it/s]

 35%|███▌      | 10606/30196 [22:08<43:11,  7.56it/s]

 35%|███▌      | 10607/30196 [22:09<40:58,  7.97it/s]

 35%|███▌      | 10608/30196 [22:09<44:24,  7.35it/s]

 35%|███▌      | 10609/30196 [22:09<42:09,  7.74it/s]

 35%|███▌      | 10610/30196 [22:09<42:40,  7.65it/s]

 35%|███▌      | 10611/30196 [22:09<40:48,  8.00it/s]

 35%|███▌      | 10613/30196 [22:09<38:43,  8.43it/s]

 35%|███▌      | 10614/30196 [22:09<43:34,  7.49it/s]

 35%|███▌      | 10615/30196 [22:10<41:12,  7.92it/s]

 35%|███▌      | 10616/30196 [22:10<41:59,  7.77it/s]

 35%|███▌      | 10618/30196 [22:10<34:18,  9.51it/s]

 35%|███▌      | 10620/30196 [22:10<32:15, 10.11it/s]

 35%|███▌      | 10622/30196 [22:10<37:07,  8.79it/s]

 35%|███▌      | 10624/30196 [22:10<31:59, 10.19it/s]

 35%|███▌      | 10626/30196 [22:11<34:03,  9.57it/s]

 35%|███▌      | 10628/30196 [22:11<32:25, 10.06it/s]

 35%|███▌      | 10630/30196 [22:11<34:40,  9.41it/s]

 35%|███▌      | 10631/30196 [22:11<36:31,  8.93it/s]

 35%|███▌      | 10632/30196 [22:11<35:53,  9.09it/s]

 35%|███▌      | 10633/30196 [22:12<38:40,  8.43it/s]

 35%|███▌      | 10634/30196 [22:12<54:24,  5.99it/s]

 35%|███▌      | 10635/30196 [22:12<54:55,  5.94it/s]

 35%|███▌      | 10636/30196 [22:12<52:25,  6.22it/s]

 35%|███▌      | 10637/30196 [22:12<49:51,  6.54it/s]

 35%|███▌      | 10639/30196 [22:12<38:28,  8.47it/s]

 35%|███▌      | 10640/30196 [22:13<39:27,  8.26it/s]

 35%|███▌      | 10642/30196 [22:13<33:03,  9.86it/s]

 35%|███▌      | 10644/30196 [22:13<35:33,  9.16it/s]

 35%|███▌      | 10645/30196 [22:13<42:05,  7.74it/s]

 35%|███▌      | 10646/30196 [22:13<41:24,  7.87it/s]

 35%|███▌      | 10647/30196 [22:13<45:04,  7.23it/s]

 35%|███▌      | 10648/30196 [22:14<44:35,  7.31it/s]

 35%|███▌      | 10649/30196 [22:14<44:01,  7.40it/s]

 35%|███▌      | 10650/30196 [22:14<44:36,  7.30it/s]

 35%|███▌      | 10652/30196 [22:14<36:45,  8.86it/s]

 35%|███▌      | 10654/30196 [22:14<32:07, 10.14it/s]

 35%|███▌      | 10656/30196 [22:14<27:23, 11.89it/s]

 35%|███▌      | 10658/30196 [22:14<25:36, 12.72it/s]

 35%|███▌      | 10660/30196 [22:15<32:52,  9.90it/s]

 35%|███▌      | 10662/30196 [22:15<32:49,  9.92it/s]

 35%|███▌      | 10664/30196 [22:15<33:11,  9.81it/s]

 35%|███▌      | 10666/30196 [22:15<31:39, 10.28it/s]

 35%|███▌      | 10668/30196 [22:15<31:38, 10.29it/s]

 35%|███▌      | 10670/30196 [22:16<32:49,  9.92it/s]

 35%|███▌      | 10672/30196 [22:16<33:52,  9.61it/s]

 35%|███▌      | 10673/30196 [22:16<34:09,  9.52it/s]

 35%|███▌      | 10674/30196 [22:16<36:05,  9.01it/s]

 35%|███▌      | 10676/30196 [22:16<36:04,  9.02it/s]

 35%|███▌      | 10678/30196 [22:17<34:38,  9.39it/s]

 35%|███▌      | 10679/30196 [22:17<34:33,  9.41it/s]

 35%|███▌      | 10680/30196 [22:17<34:50,  9.34it/s]

 35%|███▌      | 10681/30196 [22:17<42:38,  7.63it/s]

 35%|███▌      | 10682/30196 [22:17<40:24,  8.05it/s]

 35%|███▌      | 10683/30196 [22:17<38:43,  8.40it/s]

 35%|███▌      | 10685/30196 [22:17<36:24,  8.93it/s]

 35%|███▌      | 10686/30196 [22:18<38:33,  8.43it/s]

 35%|███▌      | 10687/30196 [22:18<37:50,  8.59it/s]

 35%|███▌      | 10688/30196 [22:18<40:31,  8.02it/s]

 35%|███▌      | 10689/30196 [22:18<45:01,  7.22it/s]

 35%|███▌      | 10690/30196 [22:18<41:46,  7.78it/s]

 35%|███▌      | 10691/30196 [22:18<41:55,  7.75it/s]

 35%|███▌      | 10692/30196 [22:18<43:39,  7.45it/s]

 35%|███▌      | 10694/30196 [22:19<36:06,  9.00it/s]

 35%|███▌      | 10695/30196 [22:19<37:48,  8.60it/s]

 35%|███▌      | 10696/30196 [22:19<39:55,  8.14it/s]

 35%|███▌      | 10697/30196 [22:19<40:57,  7.93it/s]

 35%|███▌      | 10698/30196 [22:19<39:32,  8.22it/s]

 35%|███▌      | 10699/30196 [22:19<38:21,  8.47it/s]

 35%|███▌      | 10701/30196 [22:19<40:27,  8.03it/s]

 35%|███▌      | 10702/30196 [22:20<40:56,  7.94it/s]

 35%|███▌      | 10704/30196 [22:20<35:01,  9.28it/s]

 35%|███▌      | 10705/30196 [22:20<47:16,  6.87it/s]

 35%|███▌      | 10706/30196 [22:20<47:18,  6.87it/s]

 35%|███▌      | 10707/30196 [22:20<46:00,  7.06it/s]

 35%|███▌      | 10708/30196 [22:20<45:25,  7.15it/s]

 35%|███▌      | 10710/30196 [22:21<33:58,  9.56it/s]

 35%|███▌      | 10712/30196 [22:21<39:21,  8.25it/s]

 35%|███▌      | 10714/30196 [22:21<32:23, 10.02it/s]

 35%|███▌      | 10716/30196 [22:21<36:17,  8.95it/s]

 35%|███▌      | 10718/30196 [22:21<34:19,  9.46it/s]

 36%|███▌      | 10720/30196 [22:22<36:32,  8.88it/s]

 36%|███▌      | 10721/30196 [22:22<36:02,  9.01it/s]

 36%|███▌      | 10722/30196 [22:22<35:55,  9.03it/s]

 36%|███▌      | 10724/30196 [22:22<38:40,  8.39it/s]

 36%|███▌      | 10725/30196 [22:22<39:42,  8.17it/s]

 36%|███▌      | 10726/30196 [22:22<41:34,  7.80it/s]

 36%|███▌      | 10728/30196 [22:23<33:48,  9.60it/s]

 36%|███▌      | 10729/30196 [22:23<33:51,  9.58it/s]

 36%|███▌      | 10730/30196 [22:23<35:57,  9.02it/s]

 36%|███▌      | 10732/30196 [22:23<30:15, 10.72it/s]

 36%|███▌      | 10735/30196 [22:23<27:51, 11.64it/s]

 36%|███▌      | 10737/30196 [22:24<1:08:02,  4.77it/s]

 36%|███▌      | 10738/30196 [22:24<1:05:38,  4.94it/s]

 36%|███▌      | 10740/30196 [22:25<54:24,  5.96it/s]

 36%|███▌      | 10741/30196 [22:25<59:38,  5.44it/s]

 36%|███▌      | 10743/30196 [22:25<49:24,  6.56it/s]

 36%|███▌      | 10745/30196 [22:25<42:23,  7.65it/s]

 36%|███▌      | 10746/30196 [22:25<40:43,  7.96it/s]

 36%|███▌      | 10747/30196 [22:25<41:48,  7.75it/s]

 36%|███▌      | 10748/30196 [22:25<39:55,  8.12it/s]

 36%|███▌      | 10750/30196 [22:26<34:13,  9.47it/s]

 36%|███▌      | 10751/30196 [22:26<34:19,  9.44it/s]

 36%|███▌      | 10753/30196 [22:26<32:25,  9.99it/s]

 36%|███▌      | 10755/30196 [22:26<32:10, 10.07it/s]

 36%|███▌      | 10757/30196 [22:26<34:30,  9.39it/s]

 36%|███▌      | 10758/30196 [22:27<36:43,  8.82it/s]

 36%|███▌      | 10759/30196 [22:27<37:59,  8.53it/s]

 36%|███▌      | 10761/30196 [22:27<42:18,  7.66it/s]

 36%|███▌      | 10762/30196 [22:27<44:57,  7.20it/s]

 36%|███▌      | 10764/30196 [22:27<36:08,  8.96it/s]

 36%|███▌      | 10766/30196 [22:27<31:52, 10.16it/s]

 36%|███▌      | 10768/30196 [22:28<39:45,  8.15it/s]

 36%|███▌      | 10769/30196 [22:28<42:57,  7.54it/s]

 36%|███▌      | 10770/30196 [22:28<48:03,  6.74it/s]

 36%|███▌      | 10771/30196 [22:28<49:28,  6.54it/s]

 36%|███▌      | 10772/30196 [22:28<45:31,  7.11it/s]

 36%|███▌      | 10773/30196 [22:29<44:35,  7.26it/s]

 36%|███▌      | 10775/30196 [22:29<39:37,  8.17it/s]

 36%|███▌      | 10777/30196 [22:29<38:21,  8.44it/s]

 36%|███▌      | 10778/30196 [22:29<39:19,  8.23it/s]

 36%|███▌      | 10779/30196 [22:29<45:44,  7.07it/s]

 36%|███▌      | 10781/30196 [22:29<36:04,  8.97it/s]

 36%|███▌      | 10782/30196 [22:30<54:11,  5.97it/s]

 36%|███▌      | 10784/30196 [22:31<1:30:57,  3.56it/s]

 36%|███▌      | 10785/30196 [22:31<1:21:10,  3.99it/s]

 36%|███▌      | 10787/30196 [22:31<58:23,  5.54it/s]

 36%|███▌      | 10789/30196 [22:31<45:01,  7.18it/s]

 36%|███▌      | 10791/30196 [22:32<1:01:27,  5.26it/s]

 36%|███▌      | 10793/30196 [22:32<52:07,  6.20it/s]

 36%|███▌      | 10795/30196 [22:32<42:29,  7.61it/s]

 36%|███▌      | 10797/30196 [22:32<39:07,  8.26it/s]

 36%|███▌      | 10799/30196 [22:32<41:02,  7.88it/s]

 36%|███▌      | 10801/30196 [22:33<37:14,  8.68it/s]

 36%|███▌      | 10803/30196 [22:33<44:39,  7.24it/s]

 36%|███▌      | 10804/30196 [22:33<46:53,  6.89it/s]

 36%|███▌      | 10805/30196 [22:33<46:10,  7.00it/s]

 36%|███▌      | 10806/30196 [22:34<45:36,  7.09it/s]

 36%|███▌      | 10808/30196 [22:34<35:59,  8.98it/s]

 36%|███▌      | 10809/30196 [22:34<38:07,  8.47it/s]

 36%|███▌      | 10810/30196 [22:34<39:14,  8.24it/s]

 36%|███▌      | 10812/30196 [22:34<31:04, 10.40it/s]

 36%|███▌      | 10814/30196 [22:34<29:59, 10.77it/s]

 36%|███▌      | 10816/30196 [22:35<36:55,  8.75it/s]

 36%|███▌      | 10817/30196 [22:35<38:58,  8.29it/s]

 36%|███▌      | 10818/30196 [22:35<43:04,  7.50it/s]

 36%|███▌      | 10819/30196 [22:35<41:13,  7.83it/s]

 36%|███▌      | 10821/30196 [22:35<34:33,  9.35it/s]

 36%|███▌      | 10822/30196 [22:35<37:29,  8.61it/s]

 36%|███▌      | 10823/30196 [22:35<46:26,  6.95it/s]

 36%|███▌      | 10825/30196 [22:36<41:53,  7.71it/s]

 36%|███▌      | 10827/30196 [22:36<34:29,  9.36it/s]

 36%|███▌      | 10829/30196 [22:36<40:12,  8.03it/s]

 36%|███▌      | 10830/30196 [22:36<43:02,  7.50it/s]

 36%|███▌      | 10831/30196 [22:36<46:15,  6.98it/s]

 36%|███▌      | 10832/30196 [22:37<52:10,  6.19it/s]

 36%|███▌      | 10834/30196 [22:37<55:26,  5.82it/s]

 36%|███▌      | 10836/30196 [22:37<47:21,  6.81it/s]

 36%|███▌      | 10837/30196 [22:37<47:23,  6.81it/s]

 36%|███▌      | 10838/30196 [22:38<49:07,  6.57it/s]

 36%|███▌      | 10840/30196 [22:38<48:58,  6.59it/s]

 36%|███▌      | 10842/30196 [22:38<44:04,  7.32it/s]

 36%|███▌      | 10843/30196 [22:38<42:15,  7.63it/s]

 36%|███▌      | 10845/30196 [22:38<34:28,  9.36it/s]

 36%|███▌      | 10847/30196 [22:39<39:24,  8.18it/s]

 36%|███▌      | 10849/30196 [22:39<37:23,  8.62it/s]

 36%|███▌      | 10850/30196 [22:39<38:29,  8.38it/s]

 36%|███▌      | 10851/30196 [22:39<46:18,  6.96it/s]

 36%|███▌      | 10852/30196 [22:39<45:19,  7.11it/s]

 36%|███▌      | 10854/30196 [22:39<34:45,  9.27it/s]

 36%|███▌      | 10856/30196 [22:40<38:38,  8.34it/s]

 36%|███▌      | 10858/30196 [22:40<37:54,  8.50it/s]

 36%|███▌      | 10860/30196 [22:40<37:48,  8.52it/s]

 36%|███▌      | 10861/30196 [22:40<40:44,  7.91it/s]

 36%|███▌      | 10863/30196 [22:41<36:35,  8.81it/s]

 36%|███▌      | 10864/30196 [22:41<37:40,  8.55it/s]

 36%|███▌      | 10865/30196 [22:41<38:55,  8.28it/s]

 36%|███▌      | 10867/30196 [22:41<30:05, 10.71it/s]

 36%|███▌      | 10869/30196 [22:41<28:01, 11.49it/s]

 36%|███▌      | 10871/30196 [22:41<37:03,  8.69it/s]

 36%|███▌      | 10873/30196 [22:42<35:12,  9.15it/s]

 36%|███▌      | 10875/30196 [22:42<33:46,  9.53it/s]

 36%|███▌      | 10877/30196 [22:42<38:03,  8.46it/s]

 36%|███▌      | 10879/30196 [22:42<35:25,  9.09it/s]

 36%|███▌      | 10880/30196 [22:42<36:53,  8.73it/s]

 36%|███▌      | 10881/30196 [22:43<36:11,  8.89it/s]

 36%|███▌      | 10882/30196 [22:43<44:43,  7.20it/s]

 36%|███▌      | 10884/30196 [22:43<42:35,  7.56it/s]

 36%|███▌      | 10885/30196 [22:43<45:47,  7.03it/s]

 36%|███▌      | 10887/30196 [22:43<43:14,  7.44it/s]

 36%|███▌      | 10888/30196 [22:44<43:40,  7.37it/s]

 36%|███▌      | 10889/30196 [22:44<1:02:35,  5.14it/s]

 36%|███▌      | 10890/30196 [22:44<1:04:12,  5.01it/s]

 36%|███▌      | 10892/30196 [22:44<54:32,  5.90it/s]

 36%|███▌      | 10893/30196 [22:45<54:56,  5.85it/s]

 36%|███▌      | 10894/30196 [22:45<49:43,  6.47it/s]

 36%|███▌      | 10895/30196 [22:45<47:45,  6.74it/s]

 36%|███▌      | 10898/30196 [22:45<31:30, 10.21it/s]

 36%|███▌      | 10900/30196 [22:45<36:57,  8.70it/s]

 36%|███▌      | 10901/30196 [22:45<36:17,  8.86it/s]

 36%|███▌      | 10903/30196 [22:46<36:57,  8.70it/s]

 36%|███▌      | 10905/30196 [22:46<42:22,  7.59it/s]

 36%|███▌      | 10908/30196 [22:46<31:06, 10.33it/s]

 36%|███▌      | 10910/30196 [22:46<34:31,  9.31it/s]

 36%|███▌      | 10912/30196 [22:47<33:58,  9.46it/s]

 36%|███▌      | 10914/30196 [22:47<37:08,  8.65it/s]

 36%|███▌      | 10915/30196 [22:48<1:16:49,  4.18it/s]

 36%|███▌      | 10916/30196 [22:48<1:12:55,  4.41it/s]

 36%|███▌      | 10917/30196 [22:48<1:06:02,  4.87it/s]

 36%|███▌      | 10919/30196 [22:48<56:41,  5.67it/s]

 36%|███▌      | 10921/30196 [22:48<49:35,  6.48it/s]

 36%|███▌      | 10923/30196 [22:49<46:35,  6.89it/s]

 36%|███▌      | 10925/30196 [22:49<40:31,  7.92it/s]

 36%|███▌      | 10926/30196 [22:49<40:45,  7.88it/s]

 36%|███▌      | 10928/30196 [22:49<33:19,  9.64it/s]

 36%|███▌      | 10930/30196 [22:49<38:32,  8.33it/s]

 36%|███▌      | 10932/30196 [22:50<37:27,  8.57it/s]

 36%|███▌      | 10933/30196 [22:50<41:11,  7.79it/s]

 36%|███▌      | 10935/30196 [22:50<38:00,  8.45it/s]

 36%|███▌      | 10936/30196 [22:51<1:03:14,  5.08it/s]

 36%|███▌      | 10938/30196 [22:51<47:05,  6.82it/s]

 36%|███▌      | 10939/30196 [22:51<44:20,  7.24it/s]

 36%|███▌      | 10940/30196 [22:51<41:52,  7.67it/s]

 36%|███▌      | 10941/30196 [22:51<42:27,  7.56it/s]

 36%|███▌      | 10942/30196 [22:51<42:19,  7.58it/s]

 36%|███▌      | 10943/30196 [22:51<40:22,  7.95it/s]

 36%|███▌      | 10944/30196 [22:51<38:41,  8.29it/s]

 36%|███▌      | 10945/30196 [22:52<37:04,  8.65it/s]

 36%|███▌      | 10946/30196 [22:52<42:06,  7.62it/s]

 36%|███▋      | 10948/30196 [22:52<41:52,  7.66it/s]

 36%|███▋      | 10949/30196 [22:52<42:09,  7.61it/s]

 36%|███▋      | 10951/30196 [22:52<35:46,  8.97it/s]

 36%|███▋      | 10952/30196 [22:52<35:14,  9.10it/s]

 36%|███▋      | 10953/30196 [22:52<36:59,  8.67it/s]

 36%|███▋      | 10955/30196 [22:53<36:42,  8.73it/s]

 36%|███▋      | 10956/30196 [22:53<36:01,  8.90it/s]

 36%|███▋      | 10957/30196 [22:53<40:32,  7.91it/s]

 36%|███▋      | 10959/30196 [22:53<37:27,  8.56it/s]

 36%|███▋      | 10960/30196 [22:53<36:37,  8.75it/s]

 36%|███▋      | 10962/30196 [22:53<34:11,  9.37it/s]

 36%|███▋      | 10963/30196 [22:54<34:21,  9.33it/s]

 36%|███▋      | 10965/30196 [22:54<36:48,  8.71it/s]

 36%|███▋      | 10966/30196 [22:54<36:06,  8.88it/s]

 36%|███▋      | 10967/30196 [22:54<47:18,  6.78it/s]

 36%|███▋      | 10968/30196 [22:54<46:41,  6.86it/s]

 36%|███▋      | 10969/30196 [22:55<49:21,  6.49it/s]

 36%|███▋      | 10971/30196 [22:55<40:18,  7.95it/s]

 36%|███▋      | 10973/30196 [22:55<36:22,  8.81it/s]

 36%|███▋      | 10974/30196 [22:55<37:32,  8.53it/s]

 36%|███▋      | 10976/30196 [22:55<40:08,  7.98it/s]

 36%|███▋      | 10978/30196 [22:55<33:12,  9.65it/s]

 36%|███▋      | 10980/30196 [22:56<31:14, 10.25it/s]

 36%|███▋      | 10982/30196 [22:56<33:36,  9.53it/s]

 36%|███▋      | 10984/30196 [22:56<34:11,  9.36it/s]

 36%|███▋      | 10986/30196 [22:56<32:26,  9.87it/s]

 36%|███▋      | 10988/30196 [22:56<29:49, 10.73it/s]

 36%|███▋      | 10990/30196 [22:57<28:24, 11.27it/s]

 36%|███▋      | 10992/30196 [22:57<27:49, 11.50it/s]

 36%|███▋      | 10994/30196 [22:57<28:08, 11.37it/s]

 36%|███▋      | 10996/30196 [22:57<33:32,  9.54it/s]

 36%|███▋      | 10998/30196 [22:57<30:00, 10.66it/s]

 36%|███▋      | 11000/30196 [22:57<29:11, 10.96it/s]

 36%|███▋      | 11002/30196 [22:58<29:45, 10.75it/s]

 36%|███▋      | 11004/30196 [22:58<33:04,  9.67it/s]

 36%|███▋      | 11006/30196 [22:58<35:27,  9.02it/s]

 36%|███▋      | 11007/30196 [22:58<35:25,  9.03it/s]

 36%|███▋      | 11009/30196 [22:58<28:58, 11.04it/s]

 36%|███▋      | 11011/30196 [22:59<33:15,  9.61it/s]

 36%|███▋      | 11013/30196 [22:59<28:42, 11.14it/s]

 36%|███▋      | 11015/30196 [22:59<31:09, 10.26it/s]

 36%|███▋      | 11017/30196 [22:59<31:02, 10.30it/s]

 36%|███▋      | 11019/30196 [22:59<29:08, 10.97it/s]

 36%|███▋      | 11021/30196 [23:00<29:37, 10.79it/s]

 37%|███▋      | 11023/30196 [23:00<32:30,  9.83it/s]

 37%|███▋      | 11025/30196 [23:00<31:17, 10.21it/s]

 37%|███▋      | 11027/30196 [23:00<32:33,  9.81it/s]

 37%|███▋      | 11029/30196 [23:00<28:58, 11.03it/s]

 37%|███▋      | 11031/30196 [23:00<26:04, 12.25it/s]

 37%|███▋      | 11033/30196 [23:01<33:09,  9.63it/s]

 37%|███▋      | 11035/30196 [23:01<32:55,  9.70it/s]

 37%|███▋      | 11037/30196 [23:01<30:08, 10.59it/s]

 37%|███▋      | 11039/30196 [23:02<47:33,  6.71it/s]

 37%|███▋      | 11040/30196 [23:02<48:41,  6.56it/s]

 37%|███▋      | 11041/30196 [23:02<47:54,  6.66it/s]

 37%|███▋      | 11042/30196 [23:02<1:03:09,  5.05it/s]

 37%|███▋      | 11043/30196 [23:02<58:49,  5.43it/s]

 37%|███▋      | 11044/30196 [23:03<54:22,  5.87it/s]

 37%|███▋      | 11045/30196 [23:03<1:04:10,  4.97it/s]

 37%|███▋      | 11047/30196 [23:03<48:46,  6.54it/s]

 37%|███▋      | 11049/30196 [23:03<41:02,  7.78it/s]

 37%|███▋      | 11050/30196 [23:04<1:23:48,  3.81it/s]

 37%|███▋      | 11051/30196 [23:04<1:13:53,  4.32it/s]

 37%|███▋      | 11052/30196 [23:04<1:12:12,  4.42it/s]

 37%|███▋      | 11053/30196 [23:05<1:07:09,  4.75it/s]

 37%|███▋      | 11054/30196 [23:05<1:01:08,  5.22it/s]

 37%|███▋      | 11055/30196 [23:05<53:52,  5.92it/s]

 37%|███▋      | 11057/30196 [23:05<43:43,  7.30it/s]

 37%|███▋      | 11058/30196 [23:05<46:15,  6.90it/s]

 37%|███▋      | 11059/30196 [23:05<48:20,  6.60it/s]

 37%|███▋      | 11060/30196 [23:06<53:34,  5.95it/s]

 37%|███▋      | 11061/30196 [23:06<47:56,  6.65it/s]

 37%|███▋      | 11062/30196 [23:06<50:08,  6.36it/s]

 37%|███▋      | 11064/30196 [23:06<38:20,  8.32it/s]

 37%|███▋      | 11065/30196 [23:06<1:10:18,  4.53it/s]

 37%|███▋      | 11066/30196 [23:07<1:01:16,  5.20it/s]

 37%|███▋      | 11067/30196 [23:07<1:21:57,  3.89it/s]

 37%|███▋      | 11068/30196 [23:07<1:12:19,  4.41it/s]

 37%|███▋      | 11069/30196 [23:08<2:19:41,  2.28it/s]

 37%|███▋      | 11071/30196 [23:08<1:32:36,  3.44it/s]

 37%|███▋      | 11072/30196 [23:09<1:23:00,  3.84it/s]

 37%|███▋      | 11074/30196 [23:09<1:02:30,  5.10it/s]

 37%|███▋      | 11076/30196 [23:09<50:44,  6.28it/s]

 37%|███▋      | 11078/30196 [23:09<40:37,  7.84it/s]

 37%|███▋      | 11080/30196 [23:09<40:27,  7.87it/s]

 37%|███▋      | 11081/30196 [23:10<46:13,  6.89it/s]

 37%|███▋      | 11083/30196 [23:10<36:33,  8.71it/s]

 37%|███▋      | 11085/30196 [23:10<39:27,  8.07it/s]

 37%|███▋      | 11086/30196 [23:10<44:27,  7.17it/s]

 37%|███▋      | 11087/30196 [23:10<43:48,  7.27it/s]

 37%|███▋      | 11089/30196 [23:11<42:02,  7.57it/s]

 37%|███▋      | 11091/30196 [23:11<38:24,  8.29it/s]

 37%|███▋      | 11093/30196 [23:11<34:53,  9.12it/s]

 37%|███▋      | 11095/30196 [23:11<29:07, 10.93it/s]

 37%|███▋      | 11097/30196 [23:11<26:02, 12.22it/s]

 37%|███▋      | 11099/30196 [23:12<38:44,  8.22it/s]

 37%|███▋      | 11101/30196 [23:12<32:03,  9.93it/s]

 37%|███▋      | 11103/30196 [23:12<31:15, 10.18it/s]

 37%|███▋      | 11105/30196 [23:12<26:58, 11.80it/s]

 37%|███▋      | 11107/30196 [23:12<36:49,  8.64it/s]

 37%|███▋      | 11109/30196 [23:13<35:08,  9.05it/s]

 37%|███▋      | 11111/30196 [23:13<36:14,  8.78it/s]

 37%|███▋      | 11113/30196 [23:13<38:20,  8.30it/s]

 37%|███▋      | 11115/30196 [23:13<35:12,  9.03it/s]

 37%|███▋      | 11117/30196 [23:13<34:06,  9.32it/s]

 37%|███▋      | 11119/30196 [23:14<38:52,  8.18it/s]

 37%|███▋      | 11120/30196 [23:14<39:33,  8.04it/s]

 37%|███▋      | 11121/30196 [23:14<40:57,  7.76it/s]

 37%|███▋      | 11123/30196 [23:14<36:30,  8.71it/s]

 37%|███▋      | 11125/30196 [23:14<37:35,  8.45it/s]

 37%|███▋      | 11126/30196 [23:15<38:35,  8.24it/s]

 37%|███▋      | 11127/30196 [23:15<37:45,  8.42it/s]

 37%|███▋      | 11128/30196 [23:15<39:24,  8.06it/s]

 37%|███▋      | 11129/30196 [23:15<42:46,  7.43it/s]

 37%|███▋      | 11131/30196 [23:15<37:46,  8.41it/s]

 37%|███▋      | 11132/30196 [23:15<38:39,  8.22it/s]

 37%|███▋      | 11134/30196 [23:16<41:33,  7.65it/s]

 37%|███▋      | 11135/30196 [23:16<44:11,  7.19it/s]

 37%|███▋      | 11137/30196 [23:16<38:58,  8.15it/s]

 37%|███▋      | 11138/30196 [23:16<45:03,  7.05it/s]

 37%|███▋      | 11140/30196 [23:16<41:01,  7.74it/s]

 37%|███▋      | 11141/30196 [23:17<41:07,  7.72it/s]

 37%|███▋      | 11142/30196 [23:17<41:12,  7.71it/s]

 37%|███▋      | 11143/30196 [23:17<44:20,  7.16it/s]

 37%|███▋      | 11145/30196 [23:17<41:34,  7.64it/s]

 37%|███▋      | 11147/30196 [23:17<42:07,  7.54it/s]

 37%|███▋      | 11149/30196 [23:18<41:27,  7.66it/s]

 37%|███▋      | 11150/30196 [23:18<40:09,  7.91it/s]

 37%|███▋      | 11151/30196 [23:18<39:00,  8.14it/s]

 37%|███▋      | 11153/30196 [23:18<31:21, 10.12it/s]

 37%|███▋      | 11155/30196 [23:18<27:02, 11.74it/s]

 37%|███▋      | 11157/30196 [23:18<25:01, 12.68it/s]

 37%|███▋      | 11159/30196 [23:18<30:00, 10.57it/s]

 37%|███▋      | 11161/30196 [23:19<27:08, 11.69it/s]

 37%|███▋      | 11163/30196 [23:19<27:26, 11.56it/s]

 37%|███▋      | 11165/30196 [23:19<26:36, 11.92it/s]

 37%|███▋      | 11167/30196 [23:19<27:20, 11.60it/s]

 37%|███▋      | 11169/30196 [23:19<29:13, 10.85it/s]

 37%|███▋      | 11171/30196 [23:20<31:50,  9.96it/s]

 37%|███▋      | 11173/30196 [23:20<33:54,  9.35it/s]

 37%|███▋      | 11175/30196 [23:20<30:54, 10.26it/s]

 37%|███▋      | 11177/30196 [23:20<31:34, 10.04it/s]

 37%|███▋      | 11179/30196 [23:21<57:47,  5.48it/s]

 37%|███▋      | 11181/30196 [23:21<48:43,  6.50it/s]

 37%|███▋      | 11182/30196 [23:21<54:08,  5.85it/s]

 37%|███▋      | 11184/30196 [23:21<45:31,  6.96it/s]

 37%|███▋      | 11186/30196 [23:22<44:26,  7.13it/s]

 37%|███▋      | 11188/30196 [23:22<39:13,  8.08it/s]

 37%|███▋      | 11189/30196 [23:22<39:38,  7.99it/s]

 37%|███▋      | 11190/30196 [23:22<42:21,  7.48it/s]

 37%|███▋      | 11192/30196 [23:22<34:28,  9.19it/s]

 37%|███▋      | 11194/30196 [23:23<33:56,  9.33it/s]

 37%|███▋      | 11195/30196 [23:23<48:25,  6.54it/s]

 37%|███▋      | 11196/30196 [23:23<49:56,  6.34it/s]

 37%|███▋      | 11198/30196 [23:23<48:58,  6.46it/s]

 37%|███▋      | 11200/30196 [23:24<40:33,  7.80it/s]

 37%|███▋      | 11201/30196 [23:24<39:23,  8.04it/s]

 37%|███▋      | 11203/30196 [23:24<32:41,  9.68it/s]

 37%|███▋      | 11205/30196 [23:24<35:28,  8.92it/s]

 37%|███▋      | 11207/30196 [23:24<37:16,  8.49it/s]

 37%|███▋      | 11208/30196 [23:24<36:26,  8.69it/s]

 37%|███▋      | 11209/30196 [23:25<39:50,  7.94it/s]

 37%|███▋      | 11211/30196 [23:25<1:14:25,  4.25it/s]

 37%|███▋      | 11213/30196 [23:26<1:04:37,  4.90it/s]

 37%|███▋      | 11214/30196 [23:26<59:58,  5.28it/s]

 37%|███▋      | 11215/30196 [23:26<56:08,  5.63it/s]

 37%|███▋      | 11216/30196 [23:26<56:35,  5.59it/s]

 37%|███▋      | 11217/30196 [23:26<53:05,  5.96it/s]

 37%|███▋      | 11219/30196 [23:26<45:52,  6.89it/s]

 37%|███▋      | 11221/30196 [23:27<38:15,  8.27it/s]

 37%|███▋      | 11223/30196 [23:27<35:50,  8.82it/s]

 37%|███▋      | 11224/30196 [23:27<43:07,  7.33it/s]

 37%|███▋      | 11225/30196 [23:27<42:43,  7.40it/s]

 37%|███▋      | 11226/30196 [23:27<42:41,  7.41it/s]

 37%|███▋      | 11228/30196 [23:27<33:27,  9.45it/s]

 37%|███▋      | 11230/30196 [23:28<37:46,  8.37it/s]

 37%|███▋      | 11231/30196 [23:28<37:11,  8.50it/s]

 37%|███▋      | 11232/30196 [23:28<40:41,  7.77it/s]

 37%|███▋      | 11233/30196 [23:28<43:37,  7.25it/s]

 37%|███▋      | 11235/30196 [23:28<35:05,  9.01it/s]

 37%|███▋      | 11236/30196 [23:29<39:18,  8.04it/s]

 37%|███▋      | 11237/30196 [23:29<40:20,  7.83it/s]

 37%|███▋      | 11238/30196 [23:29<38:53,  8.12it/s]

 37%|███▋      | 11239/30196 [23:29<39:30,  8.00it/s]

 37%|███▋      | 11241/30196 [23:29<37:57,  8.32it/s]

 37%|███▋      | 11243/30196 [23:29<30:25, 10.38it/s]

 37%|███▋      | 11245/30196 [23:30<34:03,  9.27it/s]

 37%|███▋      | 11247/30196 [23:30<29:48, 10.59it/s]

 37%|███▋      | 11249/30196 [23:30<30:50, 10.24it/s]

 37%|███▋      | 11251/30196 [23:30<28:46, 10.97it/s]

 37%|███▋      | 11253/30196 [23:30<28:33, 11.05it/s]

 37%|███▋      | 11255/30196 [23:30<28:20, 11.14it/s]

 37%|███▋      | 11257/30196 [23:30<25:32, 12.36it/s]

 37%|███▋      | 11259/30196 [23:31<33:48,  9.33it/s]

 37%|███▋      | 11261/30196 [23:31<34:52,  9.05it/s]

 37%|███▋      | 11263/30196 [23:31<42:41,  7.39it/s]

 37%|███▋      | 11264/30196 [23:32<41:00,  7.70it/s]

 37%|███▋      | 11265/30196 [23:32<41:18,  7.64it/s]

 37%|███▋      | 11266/30196 [23:32<41:13,  7.65it/s]

 37%|███▋      | 11267/30196 [23:32<39:08,  8.06it/s]

 37%|███▋      | 11268/30196 [23:32<42:29,  7.42it/s]

 37%|███▋      | 11269/30196 [23:32<45:35,  6.92it/s]

 37%|███▋      | 11270/30196 [23:32<44:47,  7.04it/s]

 37%|███▋      | 11272/30196 [23:33<41:48,  7.55it/s]

 37%|███▋      | 11274/30196 [23:33<33:40,  9.36it/s]

 37%|███▋      | 11276/30196 [23:33<31:17, 10.08it/s]

 37%|███▋      | 11278/30196 [23:33<30:53, 10.21it/s]

 37%|███▋      | 11280/30196 [23:33<29:58, 10.52it/s]

 37%|███▋      | 11282/30196 [23:33<29:41, 10.62it/s]

 37%|███▋      | 11284/30196 [23:34<30:22, 10.38it/s]

 37%|███▋      | 11286/30196 [23:34<31:52,  9.89it/s]

 37%|███▋      | 11288/30196 [23:34<31:04, 10.14it/s]

 37%|███▋      | 11290/30196 [23:34<37:32,  8.39it/s]

 37%|███▋      | 11291/30196 [23:35<37:03,  8.50it/s]

 37%|███▋      | 11293/30196 [23:35<38:00,  8.29it/s]

 37%|███▋      | 11295/30196 [23:35<36:00,  8.75it/s]

 37%|███▋      | 11296/30196 [23:35<39:00,  8.08it/s]

 37%|███▋      | 11297/30196 [23:35<42:44,  7.37it/s]

 37%|███▋      | 11299/30196 [23:35<33:39,  9.36it/s]

 37%|███▋      | 11301/30196 [23:36<32:22,  9.73it/s]

 37%|███▋      | 11303/30196 [23:36<34:16,  9.19it/s]

 37%|███▋      | 11305/30196 [23:36<33:46,  9.32it/s]

 37%|███▋      | 11306/30196 [23:36<35:08,  8.96it/s]

 37%|███▋      | 11308/30196 [23:36<36:55,  8.52it/s]

 37%|███▋      | 11309/30196 [23:37<38:25,  8.19it/s]

 37%|███▋      | 11310/30196 [23:37<39:03,  8.06it/s]

 37%|███▋      | 11311/30196 [23:37<42:25,  7.42it/s]

 37%|███▋      | 11314/30196 [23:37<28:03, 11.21it/s]

 37%|███▋      | 11316/30196 [23:37<32:25,  9.70it/s]

 37%|███▋      | 11318/30196 [23:38<37:17,  8.44it/s]

 37%|███▋      | 11319/30196 [23:38<38:34,  8.16it/s]

 37%|███▋      | 11320/30196 [23:38<39:25,  7.98it/s]

 37%|███▋      | 11321/30196 [23:38<40:36,  7.75it/s]

 37%|███▋      | 11323/30196 [23:38<36:56,  8.52it/s]

 38%|███▊      | 11325/30196 [23:38<36:58,  8.51it/s]

 38%|███▊      | 11327/30196 [23:39<31:21, 10.03it/s]

 38%|███▊      | 11329/30196 [23:39<34:50,  9.02it/s]

 38%|███▊      | 11331/30196 [23:39<32:37,  9.64it/s]

 38%|███▊      | 11333/30196 [23:39<32:43,  9.61it/s]

 38%|███▊      | 11335/30196 [23:39<32:36,  9.64it/s]

 38%|███▊      | 11337/30196 [23:40<36:43,  8.56it/s]

 38%|███▊      | 11339/30196 [23:40<43:25,  7.24it/s]

 38%|███▊      | 11340/30196 [23:40<50:16,  6.25it/s]

 38%|███▊      | 11341/30196 [23:41<54:12,  5.80it/s]

 38%|███▊      | 11343/30196 [23:41<42:53,  7.33it/s]

 38%|███▊      | 11344/30196 [23:41<48:24,  6.49it/s]

 38%|███▊      | 11346/30196 [23:41<38:18,  8.20it/s]

 38%|███▊      | 11347/30196 [23:41<39:29,  7.95it/s]

 38%|███▊      | 11348/30196 [23:41<37:59,  8.27it/s]

 38%|███▊      | 11349/30196 [23:41<37:56,  8.28it/s]

 38%|███▊      | 11351/30196 [23:42<35:41,  8.80it/s]

 38%|███▊      | 11353/30196 [23:42<31:42,  9.90it/s]

 38%|███▊      | 11355/30196 [23:42<36:29,  8.60it/s]

 38%|███▊      | 11356/30196 [23:42<40:22,  7.78it/s]

 38%|███▊      | 11358/30196 [23:43<37:47,  8.31it/s]

 38%|███▊      | 11359/30196 [23:43<46:31,  6.75it/s]

 38%|███▊      | 11360/30196 [23:43<46:24,  6.77it/s]

 38%|███▊      | 11361/30196 [23:43<45:06,  6.96it/s]

 38%|███▊      | 11362/30196 [23:43<44:24,  7.07it/s]

 38%|███▊      | 11363/30196 [23:43<44:21,  7.08it/s]

 38%|███▊      | 11365/30196 [23:44<1:24:37,  3.71it/s]

 38%|███▊      | 11366/30196 [23:44<1:12:20,  4.34it/s]

 38%|███▊      | 11368/30196 [23:44<54:28,  5.76it/s]

 38%|███▊      | 11369/30196 [23:45<1:02:10,  5.05it/s]

 38%|███▊      | 11371/30196 [23:45<48:47,  6.43it/s]

 38%|███▊      | 11372/30196 [23:45<53:39,  5.85it/s]

 38%|███▊      | 11373/30196 [23:45<48:54,  6.41it/s]

 38%|███▊      | 11374/30196 [23:45<52:53,  5.93it/s]

 38%|███▊      | 11376/30196 [23:46<41:21,  7.58it/s]

 38%|███▊      | 11377/30196 [23:46<39:48,  7.88it/s]

 38%|███▊      | 11378/30196 [23:46<38:07,  8.23it/s]

 38%|███▊      | 11379/30196 [23:46<41:51,  7.49it/s]

 38%|███▊      | 11380/30196 [23:46<48:13,  6.50it/s]

 38%|███▊      | 11382/30196 [23:46<35:05,  8.94it/s]

 38%|███▊      | 11384/30196 [23:47<36:04,  8.69it/s]

 38%|███▊      | 11385/30196 [23:47<40:03,  7.83it/s]

 38%|███▊      | 11387/30196 [23:47<34:44,  9.02it/s]

 38%|███▊      | 11389/30196 [23:47<28:53, 10.85it/s]

 38%|███▊      | 11391/30196 [23:47<32:55,  9.52it/s]

 38%|███▊      | 11393/30196 [23:48<31:58,  9.80it/s]

 38%|███▊      | 11395/30196 [23:48<38:59,  8.04it/s]

 38%|███▊      | 11397/30196 [23:48<36:53,  8.49it/s]

 38%|███▊      | 11398/30196 [23:48<38:31,  8.13it/s]

 38%|███▊      | 11399/30196 [23:48<37:19,  8.39it/s]

 38%|███▊      | 11400/30196 [23:48<38:16,  8.18it/s]

 38%|███▊      | 11401/30196 [23:49<1:01:02,  5.13it/s]

 38%|███▊      | 11403/30196 [23:49<42:30,  7.37it/s]

 38%|███▊      | 11405/30196 [23:49<37:53,  8.27it/s]

 38%|███▊      | 11407/30196 [23:50<45:15,  6.92it/s]

 38%|███▊      | 11408/30196 [23:50<1:01:15,  5.11it/s]

 38%|███▊      | 11409/30196 [23:50<1:00:14,  5.20it/s]

 38%|███▊      | 11410/30196 [23:50<55:34,  5.63it/s]

 38%|███▊      | 11412/30196 [23:50<45:10,  6.93it/s]

 38%|███▊      | 11413/30196 [23:51<50:31,  6.20it/s]

 38%|███▊      | 11414/30196 [23:51<50:55,  6.15it/s]

 38%|███▊      | 11415/30196 [23:51<46:14,  6.77it/s]

 38%|███▊      | 11417/30196 [23:51<37:31,  8.34it/s]

 38%|███▊      | 11419/30196 [23:51<34:03,  9.19it/s]

 38%|███▊      | 11420/30196 [23:51<34:05,  9.18it/s]

 38%|███▊      | 11422/30196 [23:52<35:09,  8.90it/s]

 38%|███▊      | 11424/30196 [23:52<28:35, 10.94it/s]

 38%|███▊      | 11426/30196 [23:52<33:26,  9.35it/s]

 38%|███▊      | 11428/30196 [23:52<36:11,  8.64it/s]

 38%|███▊      | 11429/30196 [23:52<38:03,  8.22it/s]

 38%|███▊      | 11430/30196 [23:53<37:57,  8.24it/s]

 38%|███▊      | 11431/30196 [23:53<44:32,  7.02it/s]

 38%|███▊      | 11433/30196 [23:53<37:49,  8.27it/s]

 38%|███▊      | 11434/30196 [23:54<1:13:22,  4.26it/s]

 38%|███▊      | 11436/30196 [23:54<55:44,  5.61it/s]

 38%|███▊      | 11437/30196 [23:54<51:04,  6.12it/s]

 38%|███▊      | 11439/30196 [23:54<44:01,  7.10it/s]

 38%|███▊      | 11441/30196 [23:54<39:05,  8.00it/s]

 38%|███▊      | 11442/30196 [23:54<45:37,  6.85it/s]

 38%|███▊      | 11443/30196 [23:55<44:54,  6.96it/s]

 38%|███▊      | 11445/30196 [23:55<38:18,  8.16it/s]

 38%|███▊      | 11446/30196 [23:55<41:20,  7.56it/s]

 38%|███▊      | 11448/30196 [23:55<33:35,  9.30it/s]

 38%|███▊      | 11449/30196 [23:55<45:32,  6.86it/s]

 38%|███▊      | 11450/30196 [23:56<45:40,  6.84it/s]

 38%|███▊      | 11453/30196 [23:56<35:32,  8.79it/s]

 38%|███▊      | 11455/30196 [23:56<36:11,  8.63it/s]

 38%|███▊      | 11457/30196 [23:56<31:45,  9.84it/s]

 38%|███▊      | 11459/30196 [23:56<29:12, 10.69it/s]

 38%|███▊      | 11461/30196 [23:57<35:34,  8.78it/s]

 38%|███▊      | 11462/30196 [23:57<36:29,  8.56it/s]

 38%|███▊      | 11463/30196 [23:57<36:05,  8.65it/s]

 38%|███▊      | 11464/30196 [23:57<35:40,  8.75it/s]

 38%|███▊      | 11466/30196 [23:57<40:03,  7.79it/s]

 38%|███▊      | 11467/30196 [23:57<40:33,  7.70it/s]

 38%|███▊      | 11469/30196 [23:58<39:04,  7.99it/s]

 38%|███▊      | 11470/30196 [23:58<39:29,  7.90it/s]

 38%|███▊      | 11471/30196 [23:58<40:58,  7.62it/s]

 38%|███▊      | 11472/30196 [23:58<42:11,  7.40it/s]

 38%|███▊      | 11473/30196 [23:58<40:05,  7.78it/s]

 38%|███▊      | 11474/30196 [23:58<43:53,  7.11it/s]

 38%|███▊      | 11475/30196 [23:58<40:56,  7.62it/s]

 38%|███▊      | 11476/30196 [23:59<42:26,  7.35it/s]

 38%|███▊      | 11477/30196 [23:59<39:39,  7.87it/s]

 38%|███▊      | 11478/30196 [23:59<49:11,  6.34it/s]

 38%|███▊      | 11480/30196 [23:59<36:54,  8.45it/s]

 38%|███▊      | 11481/30196 [23:59<36:16,  8.60it/s]

 38%|███▊      | 11482/30196 [23:59<35:46,  8.72it/s]

 38%|███▊      | 11483/30196 [23:59<37:03,  8.42it/s]

 38%|███▊      | 11485/30196 [24:00<32:08,  9.70it/s]

 38%|███▊      | 11486/30196 [24:00<36:49,  8.47it/s]

 38%|███▊      | 11487/30196 [24:00<41:10,  7.57it/s]

 38%|███▊      | 11489/30196 [24:00<35:35,  8.76it/s]

 38%|███▊      | 11490/30196 [24:00<37:31,  8.31it/s]

 38%|███▊      | 11491/30196 [24:00<40:18,  7.74it/s]

 38%|███▊      | 11492/30196 [24:01<40:26,  7.71it/s]

 38%|███▊      | 11494/30196 [24:01<37:08,  8.39it/s]

 38%|███▊      | 11495/30196 [24:01<49:27,  6.30it/s]

 38%|███▊      | 11497/30196 [24:01<37:58,  8.21it/s]

 38%|███▊      | 11499/30196 [24:01<31:54,  9.77it/s]

 38%|███▊      | 11501/30196 [24:01<29:07, 10.70it/s]

 38%|███▊      | 11503/30196 [24:02<27:09, 11.48it/s]

 38%|███▊      | 11505/30196 [24:02<31:42,  9.82it/s]

 38%|███▊      | 11507/30196 [24:02<34:45,  8.96it/s]

 38%|███▊      | 11509/30196 [24:02<29:30, 10.55it/s]

 38%|███▊      | 11511/30196 [24:03<37:25,  8.32it/s]

 38%|███▊      | 11513/30196 [24:03<37:51,  8.23it/s]

 38%|███▊      | 11514/30196 [24:03<37:12,  8.37it/s]

 38%|███▊      | 11515/30196 [24:03<37:51,  8.23it/s]

 38%|███▊      | 11516/30196 [24:03<36:42,  8.48it/s]

 38%|███▊      | 11517/30196 [24:03<35:41,  8.72it/s]

 38%|███▊      | 11519/30196 [24:04<40:52,  7.61it/s]

 38%|███▊      | 11520/30196 [24:04<49:59,  6.23it/s]

 38%|███▊      | 11522/30196 [24:04<43:15,  7.19it/s]

 38%|███▊      | 11523/30196 [24:04<45:36,  6.82it/s]

 38%|███▊      | 11524/30196 [24:04<45:39,  6.82it/s]

 38%|███▊      | 11525/30196 [24:05<44:43,  6.96it/s]

 38%|███▊      | 11526/30196 [24:05<41:53,  7.43it/s]

 38%|███▊      | 11527/30196 [24:05<42:39,  7.29it/s]

 38%|███▊      | 11529/30196 [24:05<34:00,  9.15it/s]

 38%|███▊      | 11530/30196 [24:05<44:55,  6.93it/s]

 38%|███▊      | 11532/30196 [24:05<35:07,  8.86it/s]

 38%|███▊      | 11533/30196 [24:06<42:10,  7.37it/s]

 38%|███▊      | 11534/30196 [24:06<43:01,  7.23it/s]

 38%|███▊      | 11536/30196 [24:06<39:27,  7.88it/s]

 38%|███▊      | 11537/30196 [24:06<46:00,  6.76it/s]

 38%|███▊      | 11538/30196 [24:06<44:38,  6.97it/s]

 38%|███▊      | 11539/30196 [24:06<44:54,  6.92it/s]

 38%|███▊      | 11540/30196 [24:07<41:34,  7.48it/s]

 38%|███▊      | 11541/30196 [24:07<45:11,  6.88it/s]

 38%|███▊      | 11542/30196 [24:07<43:51,  7.09it/s]

 38%|███▊      | 11543/30196 [24:07<44:21,  7.01it/s]

 38%|███▊      | 11544/30196 [24:07<40:55,  7.59it/s]

 38%|███▊      | 11546/30196 [24:07<38:01,  8.17it/s]

 38%|███▊      | 11548/30196 [24:07<32:54,  9.45it/s]

 38%|███▊      | 11550/30196 [24:08<29:19, 10.60it/s]

 38%|███▊      | 11552/30196 [24:08<27:03, 11.48it/s]

 38%|███▊      | 11554/30196 [24:08<28:58, 10.72it/s]

 38%|███▊      | 11556/30196 [24:08<34:03,  9.12it/s]

 38%|███▊      | 11558/30196 [24:08<30:29, 10.19it/s]

 38%|███▊      | 11560/30196 [24:09<35:24,  8.77it/s]

 38%|███▊      | 11561/30196 [24:09<39:07,  7.94it/s]

 38%|███▊      | 11562/30196 [24:09<44:44,  6.94it/s]

 38%|███▊      | 11563/30196 [24:09<47:10,  6.58it/s]

 38%|███▊      | 11565/30196 [24:09<37:35,  8.26it/s]

 38%|███▊      | 11566/30196 [24:10<39:07,  7.93it/s]

 38%|███▊      | 11568/30196 [24:10<31:21,  9.90it/s]

 38%|███▊      | 11570/30196 [24:10<35:53,  8.65it/s]

 38%|███▊      | 11572/30196 [24:10<29:52, 10.39it/s]

 38%|███▊      | 11574/30196 [24:10<37:29,  8.28it/s]

 38%|███▊      | 11576/30196 [24:11<32:12,  9.63it/s]

 38%|███▊      | 11578/30196 [24:11<35:33,  8.73it/s]

 38%|███▊      | 11580/30196 [24:11<35:00,  8.86it/s]

 38%|███▊      | 11582/30196 [24:11<34:53,  8.89it/s]

 38%|███▊      | 11583/30196 [24:11<34:28,  9.00it/s]

 38%|███▊      | 11584/30196 [24:12<40:24,  7.68it/s]

 38%|███▊      | 11585/30196 [24:12<41:37,  7.45it/s]

 38%|███▊      | 11586/30196 [24:12<39:21,  7.88it/s]

 38%|███▊      | 11587/30196 [24:12<43:37,  7.11it/s]

 38%|███▊      | 11588/30196 [24:12<45:57,  6.75it/s]

 38%|███▊      | 11590/30196 [24:12<38:46,  8.00it/s]

 38%|███▊      | 11591/30196 [24:13<41:57,  7.39it/s]

 38%|███▊      | 11592/30196 [24:13<39:43,  7.80it/s]

 38%|███▊      | 11593/30196 [24:13<39:57,  7.76it/s]

 38%|███▊      | 11594/30196 [24:13<43:08,  7.19it/s]

 38%|███▊      | 11596/30196 [24:13<33:49,  9.17it/s]

 38%|███▊      | 11598/30196 [24:13<27:34, 11.24it/s]

 38%|███▊      | 11600/30196 [24:13<28:36, 10.83it/s]

 38%|███▊      | 11602/30196 [24:14<31:19,  9.89it/s]

 38%|███▊      | 11604/30196 [24:14<27:59, 11.07it/s]

 38%|███▊      | 11606/30196 [24:14<32:47,  9.45it/s]

 38%|███▊      | 11608/30196 [24:14<32:45,  9.46it/s]

 38%|███▊      | 11610/30196 [24:15<35:11,  8.80it/s]

 38%|███▊      | 11611/30196 [24:15<38:33,  8.03it/s]

 38%|███▊      | 11612/30196 [24:15<39:37,  7.82it/s]

 38%|███▊      | 11613/30196 [24:15<38:23,  8.07it/s]

 38%|███▊      | 11614/30196 [24:15<41:30,  7.46it/s]

 38%|███▊      | 11615/30196 [24:15<48:20,  6.41it/s]

 38%|███▊      | 11617/30196 [24:16<41:37,  7.44it/s]

 38%|███▊      | 11618/30196 [24:16<44:31,  6.95it/s]

 38%|███▊      | 11619/30196 [24:16<44:45,  6.92it/s]

 38%|███▊      | 11622/30196 [24:16<32:01,  9.67it/s]

 38%|███▊      | 11624/30196 [24:16<28:22, 10.91it/s]

 39%|███▊      | 11626/30196 [24:17<37:50,  8.18it/s]

 39%|███▊      | 11628/30196 [24:17<36:02,  8.58it/s]

 39%|███▊      | 11630/30196 [24:17<35:09,  8.80it/s]

 39%|███▊      | 11631/30196 [24:17<40:18,  7.68it/s]

 39%|███▊      | 11633/30196 [24:17<33:43,  9.18it/s]

 39%|███▊      | 11635/30196 [24:17<29:24, 10.52it/s]

 39%|███▊      | 11637/30196 [24:18<30:31, 10.13it/s]

 39%|███▊      | 11639/30196 [24:18<34:17,  9.02it/s]

 39%|███▊      | 11641/30196 [24:18<33:31,  9.22it/s]

 39%|███▊      | 11642/30196 [24:18<34:53,  8.86it/s]

 39%|███▊      | 11643/30196 [24:19<41:05,  7.52it/s]

 39%|███▊      | 11644/30196 [24:19<39:06,  7.90it/s]

 39%|███▊      | 11646/30196 [24:19<38:43,  7.98it/s]

 39%|███▊      | 11647/30196 [24:19<37:40,  8.21it/s]

 39%|███▊      | 11648/30196 [24:19<44:27,  6.95it/s]

 39%|███▊      | 11649/30196 [24:19<43:21,  7.13it/s]

 39%|███▊      | 11651/30196 [24:20<39:08,  7.90it/s]

 39%|███▊      | 11653/30196 [24:20<35:51,  8.62it/s]

 39%|███▊      | 11655/30196 [24:20<36:42,  8.42it/s]

 39%|███▊      | 11656/30196 [24:20<39:59,  7.73it/s]

 39%|███▊      | 11657/30196 [24:20<40:01,  7.72it/s]

 39%|███▊      | 11658/30196 [24:21<1:08:38,  4.50it/s]

 39%|███▊      | 11659/30196 [24:22<1:46:31,  2.90it/s]

 39%|███▊      | 11661/30196 [24:22<1:13:21,  4.21it/s]

 39%|███▊      | 11662/30196 [24:22<1:09:11,  4.46it/s]

 39%|███▊      | 11663/30196 [24:22<1:00:28,  5.11it/s]

 39%|███▊      | 11665/30196 [24:22<48:57,  6.31it/s]

 39%|███▊      | 11667/30196 [24:22<42:22,  7.29it/s]

 39%|███▊      | 11668/30196 [24:23<46:58,  6.57it/s]

 39%|███▊      | 11669/30196 [24:23<45:28,  6.79it/s]

 39%|███▊      | 11671/30196 [24:23<40:15,  7.67it/s]

 39%|███▊      | 11673/30196 [24:23<31:18,  9.86it/s]

 39%|███▊      | 11675/30196 [24:23<38:31,  8.01it/s]

 39%|███▊      | 11676/30196 [24:24<41:21,  7.46it/s]

 39%|███▊      | 11677/30196 [24:24<49:42,  6.21it/s]

 39%|███▊      | 11678/30196 [24:24<45:34,  6.77it/s]

 39%|███▊      | 11679/30196 [24:24<58:22,  5.29it/s]

 39%|███▊      | 11681/30196 [24:24<41:31,  7.43it/s]

 39%|███▊      | 11683/30196 [24:24<33:17,  9.27it/s]

 39%|███▊      | 11685/30196 [24:25<40:14,  7.67it/s]

 39%|███▊      | 11686/30196 [24:25<40:32,  7.61it/s]

 39%|███▊      | 11687/30196 [24:25<39:03,  7.90it/s]

 39%|███▊      | 11689/30196 [24:25<33:25,  9.23it/s]

 39%|███▊      | 11691/30196 [24:26<39:39,  7.78it/s]

 39%|███▊      | 11693/30196 [24:26<37:47,  8.16it/s]

 39%|███▊      | 11695/30196 [24:26<34:48,  8.86it/s]

 39%|███▊      | 11696/30196 [24:26<36:05,  8.54it/s]

 39%|███▊      | 11697/30196 [24:26<43:28,  7.09it/s]

 39%|███▊      | 11699/30196 [24:27<38:09,  8.08it/s]

 39%|███▊      | 11700/30196 [24:27<44:40,  6.90it/s]

 39%|███▉      | 11701/30196 [24:27<53:12,  5.79it/s]

 39%|███▉      | 11702/30196 [24:27<50:37,  6.09it/s]

 39%|███▉      | 11703/30196 [24:27<48:40,  6.33it/s]

 39%|███▉      | 11705/30196 [24:27<39:59,  7.71it/s]

 39%|███▉      | 11707/30196 [24:28<33:29,  9.20it/s]

 39%|███▉      | 11708/30196 [24:28<43:19,  7.11it/s]

 39%|███▉      | 11710/30196 [24:28<38:59,  7.90it/s]

 39%|███▉      | 11711/30196 [24:28<47:12,  6.53it/s]

 39%|███▉      | 11713/30196 [24:28<35:16,  8.73it/s]

 39%|███▉      | 11715/30196 [24:29<37:49,  8.14it/s]

 39%|███▉      | 11716/30196 [24:29<44:25,  6.93it/s]

 39%|███▉      | 11717/30196 [24:29<41:42,  7.38it/s]

 39%|███▉      | 11718/30196 [24:29<42:03,  7.32it/s]

 39%|███▉      | 11719/30196 [24:29<41:37,  7.40it/s]

 39%|███▉      | 11720/30196 [24:30<49:33,  6.21it/s]

 39%|███▉      | 11722/30196 [24:30<40:01,  7.69it/s]

 39%|███▉      | 11723/30196 [24:30<41:19,  7.45it/s]

 39%|███▉      | 11724/30196 [24:30<43:49,  7.03it/s]

 39%|███▉      | 11725/30196 [24:30<42:52,  7.18it/s]

 39%|███▉      | 11726/30196 [24:30<42:31,  7.24it/s]

 39%|███▉      | 11727/30196 [24:31<48:56,  6.29it/s]

 39%|███▉      | 11728/30196 [24:31<44:07,  6.98it/s]

 39%|███▉      | 11730/30196 [24:31<36:45,  8.37it/s]

 39%|███▉      | 11732/30196 [24:31<37:57,  8.11it/s]

 39%|███▉      | 11733/30196 [24:31<41:01,  7.50it/s]

 39%|███▉      | 11734/30196 [24:31<41:09,  7.48it/s]

 39%|███▉      | 11736/30196 [24:32<39:13,  7.84it/s]

 39%|███▉      | 11737/30196 [24:32<41:57,  7.33it/s]

 39%|███▉      | 11738/30196 [24:32<44:16,  6.95it/s]

 39%|███▉      | 11739/30196 [24:32<46:21,  6.63it/s]

 39%|███▉      | 11740/30196 [24:32<47:35,  6.46it/s]

 39%|███▉      | 11741/30196 [24:32<43:16,  7.11it/s]

 39%|███▉      | 11742/30196 [24:33<42:48,  7.18it/s]

 39%|███▉      | 11743/30196 [24:33<45:11,  6.81it/s]

 39%|███▉      | 11745/30196 [24:33<35:04,  8.77it/s]

 39%|███▉      | 11746/30196 [24:33<34:44,  8.85it/s]

 39%|███▉      | 11747/30196 [24:33<36:23,  8.45it/s]

 39%|███▉      | 11748/30196 [24:33<38:45,  7.93it/s]

 39%|███▉      | 11749/30196 [24:34<51:31,  5.97it/s]

 39%|███▉      | 11751/30196 [24:34<52:16,  5.88it/s]

 39%|███▉      | 11753/30196 [24:34<44:37,  6.89it/s]

 39%|███▉      | 11754/30196 [24:34<43:41,  7.03it/s]

 39%|███▉      | 11755/30196 [24:34<41:18,  7.44it/s]

 39%|███▉      | 11757/30196 [24:34<35:22,  8.69it/s]

 39%|███▉      | 11759/30196 [24:35<30:04, 10.22it/s]

 39%|███▉      | 11761/30196 [24:35<36:07,  8.51it/s]

 39%|███▉      | 11763/30196 [24:35<30:34, 10.05it/s]

 39%|███▉      | 11765/30196 [24:35<30:58,  9.92it/s]

 39%|███▉      | 11767/30196 [24:35<33:00,  9.30it/s]

 39%|███▉      | 11769/30196 [24:36<34:42,  8.85it/s]

 39%|███▉      | 11770/30196 [24:36<34:15,  8.96it/s]

 39%|███▉      | 11771/30196 [24:36<34:07,  9.00it/s]

 39%|███▉      | 11772/30196 [24:36<36:49,  8.34it/s]

 39%|███▉      | 11773/30196 [24:37<1:03:33,  4.83it/s]

 39%|███▉      | 11774/30196 [24:37<1:01:06,  5.02it/s]

 39%|███▉      | 11775/30196 [24:37<1:02:09,  4.94it/s]

 39%|███▉      | 11776/30196 [24:37<56:24,  5.44it/s]

 39%|███▉      | 11777/30196 [24:37<1:00:10,  5.10it/s]

 39%|███▉      | 11779/30196 [24:38<51:15,  5.99it/s]

 39%|███▉      | 11781/30196 [24:38<44:38,  6.87it/s]

 39%|███▉      | 11783/30196 [24:38<45:14,  6.78it/s]

 39%|███▉      | 11785/30196 [24:38<38:14,  8.02it/s]

 39%|███▉      | 11787/30196 [24:38<35:31,  8.64it/s]

 39%|███▉      | 11789/30196 [24:39<37:53,  8.10it/s]

 39%|███▉      | 11790/30196 [24:39<40:42,  7.54it/s]

 39%|███▉      | 11792/30196 [24:39<36:00,  8.52it/s]

 39%|███▉      | 11794/30196 [24:39<30:00, 10.22it/s]

 39%|███▉      | 11796/30196 [24:39<31:59,  9.59it/s]

 39%|███▉      | 11798/30196 [24:40<29:53, 10.26it/s]

 39%|███▉      | 11800/30196 [24:40<30:42,  9.99it/s]

 39%|███▉      | 11802/30196 [24:40<30:31, 10.04it/s]

 39%|███▉      | 11804/30196 [24:40<33:16,  9.21it/s]

 39%|███▉      | 11805/30196 [24:40<35:01,  8.75it/s]

 39%|███▉      | 11806/30196 [24:41<34:23,  8.91it/s]

 39%|███▉      | 11807/30196 [24:41<38:24,  7.98it/s]

 39%|███▉      | 11808/30196 [24:41<41:37,  7.36it/s]

 39%|███▉      | 11810/30196 [24:41<37:32,  8.16it/s]

 39%|███▉      | 11811/30196 [24:41<39:18,  7.80it/s]

 39%|███▉      | 11813/30196 [24:41<38:05,  8.05it/s]

 39%|███▉      | 11815/30196 [24:42<37:32,  8.16it/s]

 39%|███▉      | 11817/30196 [24:42<34:40,  8.83it/s]

 39%|███▉      | 11819/30196 [24:42<36:23,  8.42it/s]

 39%|███▉      | 11821/30196 [24:42<34:53,  8.78it/s]

 39%|███▉      | 11823/30196 [24:43<33:35,  9.12it/s]

 39%|███▉      | 11825/30196 [24:43<32:21,  9.46it/s]

 39%|███▉      | 11826/30196 [24:43<38:17,  8.00it/s]

 39%|███▉      | 11827/30196 [24:43<43:50,  6.98it/s]

 39%|███▉      | 11829/30196 [24:43<37:57,  8.06it/s]

 39%|███▉      | 11830/30196 [24:44<38:40,  7.91it/s]

 39%|███▉      | 11831/30196 [24:44<38:56,  7.86it/s]

 39%|███▉      | 11832/30196 [24:44<42:11,  7.26it/s]

 39%|███▉      | 11833/30196 [24:44<49:04,  6.24it/s]

 39%|███▉      | 11834/30196 [24:44<58:08,  5.26it/s]

 39%|███▉      | 11835/30196 [24:44<54:26,  5.62it/s]

 39%|███▉      | 11837/30196 [24:45<47:17,  6.47it/s]

 39%|███▉      | 11838/30196 [24:45<45:52,  6.67it/s]

 39%|███▉      | 11839/30196 [24:45<47:25,  6.45it/s]

 39%|███▉      | 11841/30196 [24:45<39:41,  7.71it/s]

 39%|███▉      | 11843/30196 [24:45<35:44,  8.56it/s]

 39%|███▉      | 11844/30196 [24:46<37:16,  8.20it/s]

 39%|███▉      | 11845/30196 [24:46<38:09,  8.01it/s]

 39%|███▉      | 11846/30196 [24:46<41:32,  7.36it/s]

 39%|███▉      | 11847/30196 [24:46<44:08,  6.93it/s]

 39%|███▉      | 11848/30196 [24:46<53:27,  5.72it/s]

 39%|███▉      | 11850/30196 [24:46<40:48,  7.49it/s]

 39%|███▉      | 11852/30196 [24:47<34:30,  8.86it/s]

 39%|███▉      | 11853/30196 [24:47<34:16,  8.92it/s]

 39%|███▉      | 11854/30196 [24:47<34:50,  8.77it/s]

 39%|███▉      | 11856/30196 [24:47<34:53,  8.76it/s]

 39%|███▉      | 11858/30196 [24:47<31:59,  9.55it/s]

 39%|███▉      | 11859/30196 [24:47<38:30,  7.94it/s]

 39%|███▉      | 11860/30196 [24:48<39:31,  7.73it/s]

 39%|███▉      | 11862/30196 [24:48<38:01,  8.03it/s]

 39%|███▉      | 11863/30196 [24:48<40:47,  7.49it/s]

 39%|███▉      | 11864/30196 [24:48<40:33,  7.53it/s]

 39%|███▉      | 11866/30196 [24:48<36:01,  8.48it/s]

 39%|███▉      | 11868/30196 [24:48<28:45, 10.62it/s]

 39%|███▉      | 11870/30196 [24:49<32:03,  9.53it/s]

 39%|███▉      | 11872/30196 [24:49<37:03,  8.24it/s]

 39%|███▉      | 11874/30196 [24:49<33:08,  9.21it/s]

 39%|███▉      | 11876/30196 [24:49<31:10,  9.79it/s]

 39%|███▉      | 11878/30196 [24:50<32:10,  9.49it/s]

 39%|███▉      | 11880/30196 [24:50<34:51,  8.76it/s]

 39%|███▉      | 11881/30196 [24:50<39:59,  7.63it/s]

 39%|███▉      | 11883/30196 [24:50<43:52,  6.96it/s]

 39%|███▉      | 11885/30196 [24:51<39:43,  7.68it/s]

 39%|███▉      | 11886/30196 [24:51<38:18,  7.97it/s]

 39%|███▉      | 11887/30196 [24:51<38:53,  7.85it/s]

 39%|███▉      | 11889/30196 [24:51<36:44,  8.30it/s]

 39%|███▉      | 11891/30196 [24:51<36:25,  8.38it/s]

 39%|███▉      | 11892/30196 [24:51<35:50,  8.51it/s]

 39%|███▉      | 11894/30196 [24:52<35:07,  8.68it/s]

 39%|███▉      | 11895/30196 [24:52<35:26,  8.61it/s]

 39%|███▉      | 11897/30196 [24:52<44:48,  6.81it/s]

 39%|███▉      | 11898/30196 [24:52<46:16,  6.59it/s]

 39%|███▉      | 11900/30196 [24:52<37:33,  8.12it/s]

 39%|███▉      | 11901/30196 [24:53<36:39,  8.32it/s]

 39%|███▉      | 11902/30196 [24:53<35:56,  8.48it/s]

 39%|███▉      | 11903/30196 [24:53<38:49,  7.85it/s]

 39%|███▉      | 11905/30196 [24:53<35:32,  8.58it/s]

 39%|███▉      | 11906/30196 [24:53<47:31,  6.42it/s]

 39%|███▉      | 11908/30196 [24:53<41:14,  7.39it/s]

 39%|███▉      | 11909/30196 [24:54<39:33,  7.70it/s]

 39%|███▉      | 11911/30196 [24:54<38:17,  7.96it/s]

 39%|███▉      | 11912/30196 [24:54<38:58,  7.82it/s]

 39%|███▉      | 11914/30196 [24:54<34:24,  8.85it/s]

 39%|███▉      | 11915/30196 [24:54<38:39,  7.88it/s]

 39%|███▉      | 11916/30196 [24:54<37:03,  8.22it/s]

 39%|███▉      | 11918/30196 [24:55<34:45,  8.77it/s]

 39%|███▉      | 11920/30196 [24:55<29:30, 10.32it/s]

 39%|███▉      | 11922/30196 [24:55<35:16,  8.64it/s]

 39%|███▉      | 11923/30196 [24:55<36:09,  8.42it/s]

 39%|███▉      | 11924/30196 [24:55<36:54,  8.25it/s]

 39%|███▉      | 11925/30196 [24:55<37:37,  8.09it/s]

 39%|███▉      | 11926/30196 [24:56<40:54,  7.44it/s]

 40%|███▉      | 11928/30196 [24:56<40:32,  7.51it/s]

 40%|███▉      | 11929/30196 [24:56<38:56,  7.82it/s]

 40%|███▉      | 11930/30196 [24:56<40:25,  7.53it/s]

 40%|███▉      | 11931/30196 [24:56<39:24,  7.72it/s]

 40%|███▉      | 11932/30196 [24:56<43:36,  6.98it/s]

 40%|███▉      | 11934/30196 [24:57<33:28,  9.09it/s]

 40%|███▉      | 11936/30196 [24:57<32:01,  9.50it/s]

 40%|███▉      | 11937/30196 [24:57<36:36,  8.31it/s]

 40%|███▉      | 11939/30196 [24:57<30:15, 10.06it/s]

 40%|███▉      | 11941/30196 [24:57<30:48,  9.88it/s]

 40%|███▉      | 11943/30196 [24:58<32:12,  9.44it/s]

 40%|███▉      | 11944/30196 [24:58<33:37,  9.05it/s]

 40%|███▉      | 11946/30196 [24:58<39:12,  7.76it/s]

 40%|███▉      | 11948/30196 [24:58<36:10,  8.41it/s]

 40%|███▉      | 11950/30196 [24:58<32:08,  9.46it/s]

 40%|███▉      | 11952/30196 [24:59<32:36,  9.33it/s]

 40%|███▉      | 11954/30196 [24:59<29:14, 10.40it/s]

 40%|███▉      | 11956/30196 [24:59<28:01, 10.85it/s]

 40%|███▉      | 11958/30196 [24:59<32:20,  9.40it/s]

 40%|███▉      | 11960/30196 [24:59<37:09,  8.18it/s]

 40%|███▉      | 11961/30196 [25:00<37:35,  8.09it/s]

 40%|███▉      | 11963/30196 [25:00<32:17,  9.41it/s]

 40%|███▉      | 11965/30196 [25:00<40:37,  7.48it/s]

 40%|███▉      | 11966/30196 [25:00<45:47,  6.63it/s]

 40%|███▉      | 11968/30196 [25:01<40:19,  7.53it/s]

 40%|███▉      | 11970/30196 [25:01<32:53,  9.24it/s]

 40%|███▉      | 11972/30196 [25:01<33:35,  9.04it/s]

 40%|███▉      | 11974/30196 [25:01<38:16,  7.93it/s]

 40%|███▉      | 11975/30196 [25:01<38:45,  7.84it/s]

 40%|███▉      | 11977/30196 [25:02<37:19,  8.14it/s]

 40%|███▉      | 11978/30196 [25:02<36:11,  8.39it/s]

 40%|███▉      | 11979/30196 [25:02<37:10,  8.17it/s]

 40%|███▉      | 11980/30196 [25:02<45:00,  6.75it/s]

 40%|███▉      | 11982/30196 [25:02<34:14,  8.86it/s]

 40%|███▉      | 11984/30196 [25:02<31:24,  9.66it/s]

 40%|███▉      | 11986/30196 [25:03<32:40,  9.29it/s]

 40%|███▉      | 11988/30196 [25:03<33:59,  8.93it/s]

 40%|███▉      | 11989/30196 [25:03<37:18,  8.13it/s]

 40%|███▉      | 11990/30196 [25:03<38:24,  7.90it/s]

 40%|███▉      | 11991/30196 [25:03<39:54,  7.60it/s]

 40%|███▉      | 11992/30196 [25:03<45:34,  6.66it/s]

 40%|███▉      | 11994/30196 [25:04<40:23,  7.51it/s]

 40%|███▉      | 11995/30196 [25:04<41:22,  7.33it/s]

 40%|███▉      | 11996/30196 [25:04<41:13,  7.36it/s]

 40%|███▉      | 11998/30196 [25:04<37:14,  8.14it/s]

 40%|███▉      | 11999/30196 [25:04<41:05,  7.38it/s]

 40%|███▉      | 12000/30196 [25:04<41:03,  7.39it/s]

 40%|███▉      | 12001/30196 [25:05<1:03:22,  4.79it/s]

 40%|███▉      | 12003/30196 [25:05<46:53,  6.47it/s]

 40%|███▉      | 12004/30196 [25:05<43:42,  6.94it/s]

 40%|███▉      | 12005/30196 [25:05<43:56,  6.90it/s]

 40%|███▉      | 12008/30196 [25:06<34:36,  8.76it/s]

 40%|███▉      | 12010/30196 [25:06<30:38,  9.89it/s]

 40%|███▉      | 12012/30196 [25:06<26:29, 11.44it/s]

 40%|███▉      | 12014/30196 [25:06<28:26, 10.65it/s]

 40%|███▉      | 12016/30196 [25:06<30:07, 10.06it/s]

 40%|███▉      | 12018/30196 [25:06<28:57, 10.46it/s]

 40%|███▉      | 12020/30196 [25:07<32:53,  9.21it/s]

 40%|███▉      | 12021/30196 [25:07<34:00,  8.91it/s]

 40%|███▉      | 12022/30196 [25:07<33:50,  8.95it/s]

 40%|███▉      | 12024/30196 [25:07<29:47, 10.17it/s]

 40%|███▉      | 12026/30196 [25:07<30:32,  9.92it/s]

 40%|███▉      | 12028/30196 [25:08<54:17,  5.58it/s]

 40%|███▉      | 12029/30196 [25:08<51:41,  5.86it/s]

 40%|███▉      | 12031/30196 [25:08<47:55,  6.32it/s]

 40%|███▉      | 12032/30196 [25:09<1:28:44,  3.41it/s]

 40%|███▉      | 12033/30196 [25:10<1:40:10,  3.02it/s]

 40%|███▉      | 12034/30196 [25:10<1:30:56,  3.33it/s]

 40%|███▉      | 12035/30196 [25:10<1:16:08,  3.98it/s]

 40%|███▉      | 12037/30196 [25:10<55:12,  5.48it/s]

 40%|███▉      | 12039/30196 [25:10<42:58,  7.04it/s]

 40%|███▉      | 12040/30196 [25:11<44:47,  6.76it/s]

 40%|███▉      | 12041/30196 [25:11<46:07,  6.56it/s]

 40%|███▉      | 12043/30196 [25:11<35:48,  8.45it/s]

 40%|███▉      | 12044/30196 [25:11<1:10:42,  4.28it/s]

 40%|███▉      | 12046/30196 [25:12<51:15,  5.90it/s]

 40%|███▉      | 12047/30196 [25:12<54:41,  5.53it/s]

 40%|███▉      | 12048/30196 [25:12<51:09,  5.91it/s]

 40%|███▉      | 12049/30196 [25:12<48:16,  6.27it/s]

 40%|███▉      | 12051/30196 [25:12<41:53,  7.22it/s]

 40%|███▉      | 12052/30196 [25:12<41:42,  7.25it/s]

 40%|███▉      | 12053/30196 [25:13<41:29,  7.29it/s]

 40%|███▉      | 12054/30196 [25:13<41:17,  7.32it/s]

 40%|███▉      | 12055/30196 [25:13<44:45,  6.75it/s]

 40%|███▉      | 12056/30196 [25:13<43:19,  6.98it/s]

 40%|███▉      | 12057/30196 [25:13<43:42,  6.92it/s]

 40%|███▉      | 12060/30196 [25:13<33:54,  8.91it/s]

 40%|███▉      | 12062/30196 [25:14<34:35,  8.74it/s]

 40%|███▉      | 12063/30196 [25:14<38:09,  7.92it/s]

 40%|███▉      | 12065/30196 [25:14<30:24,  9.94it/s]

 40%|███▉      | 12067/30196 [25:14<35:06,  8.61it/s]

 40%|███▉      | 12069/30196 [25:14<30:50,  9.80it/s]

 40%|███▉      | 12071/30196 [25:15<38:04,  7.93it/s]

 40%|███▉      | 12073/30196 [25:15<31:24,  9.62it/s]

 40%|███▉      | 12075/30196 [25:15<30:54,  9.77it/s]

 40%|███▉      | 12077/30196 [25:15<34:00,  8.88it/s]

 40%|████      | 12079/30196 [25:16<38:03,  7.94it/s]

 40%|████      | 12081/30196 [25:16<36:03,  8.37it/s]

 40%|████      | 12082/30196 [25:16<37:32,  8.04it/s]

 40%|████      | 12083/30196 [25:16<40:06,  7.53it/s]

 40%|████      | 12085/30196 [25:16<32:25,  9.31it/s]

 40%|████      | 12087/30196 [25:16<31:18,  9.64it/s]

 40%|████      | 12089/30196 [25:17<29:01, 10.40it/s]

 40%|████      | 12091/30196 [25:17<30:09, 10.01it/s]

 40%|████      | 12093/30196 [25:17<26:42, 11.29it/s]

 40%|████      | 12095/30196 [25:17<32:57,  9.15it/s]

 40%|████      | 12097/30196 [25:18<38:06,  7.92it/s]

 40%|████      | 12098/30196 [25:18<39:17,  7.68it/s]

 40%|████      | 12099/30196 [25:18<38:03,  7.93it/s]

 40%|████      | 12100/30196 [25:18<40:41,  7.41it/s]

 40%|████      | 12101/30196 [25:18<40:40,  7.41it/s]

 40%|████      | 12102/30196 [25:18<40:17,  7.48it/s]

 40%|████      | 12103/30196 [25:18<41:25,  7.28it/s]

 40%|████      | 12105/30196 [25:19<34:16,  8.80it/s]

 40%|████      | 12107/30196 [25:19<29:32, 10.21it/s]

 40%|████      | 12109/30196 [25:19<27:50, 10.83it/s]

 40%|████      | 12111/30196 [25:19<23:53, 12.61it/s]

 40%|████      | 12113/30196 [25:19<26:11, 11.50it/s]

 40%|████      | 12115/30196 [25:19<30:15,  9.96it/s]

 40%|████      | 12117/30196 [25:20<29:44, 10.13it/s]

 40%|████      | 12119/30196 [25:20<27:54, 10.79it/s]

 40%|████      | 12121/30196 [25:20<33:54,  8.88it/s]

 40%|████      | 12123/30196 [25:20<33:32,  8.98it/s]

 40%|████      | 12124/30196 [25:21<34:50,  8.65it/s]

 40%|████      | 12125/30196 [25:21<35:59,  8.37it/s]

 40%|████      | 12127/30196 [25:21<31:53,  9.44it/s]

 40%|████      | 12129/30196 [25:21<32:05,  9.38it/s]

 40%|████      | 12130/30196 [25:21<35:53,  8.39it/s]

 40%|████      | 12131/30196 [25:21<36:54,  8.16it/s]

 40%|████      | 12132/30196 [25:21<38:12,  7.88it/s]

 40%|████      | 12134/30196 [25:22<32:39,  9.22it/s]

 40%|████      | 12135/30196 [25:22<36:31,  8.24it/s]

 40%|████      | 12136/30196 [25:22<40:41,  7.40it/s]

 40%|████      | 12138/30196 [25:22<33:36,  8.96it/s]

 40%|████      | 12139/30196 [25:22<38:04,  7.90it/s]

 40%|████      | 12140/30196 [25:22<36:50,  8.17it/s]

 40%|████      | 12142/30196 [25:23<29:45, 10.11it/s]

 40%|████      | 12144/30196 [25:23<31:53,  9.44it/s]

 40%|████      | 12146/30196 [25:23<27:59, 10.75it/s]

 40%|████      | 12149/30196 [25:23<26:20, 11.42it/s]

 40%|████      | 12151/30196 [25:23<30:26,  9.88it/s]

 40%|████      | 12153/30196 [25:24<30:02, 10.01it/s]

 40%|████      | 12155/30196 [25:24<26:34, 11.32it/s]

 40%|████      | 12157/30196 [25:24<33:17,  9.03it/s]

 40%|████      | 12159/30196 [25:24<30:15,  9.94it/s]

 40%|████      | 12161/30196 [25:24<31:05,  9.67it/s]

 40%|████      | 12163/30196 [25:25<37:05,  8.10it/s]

 40%|████      | 12164/30196 [25:25<37:44,  7.96it/s]

 40%|████      | 12166/30196 [25:25<32:57,  9.12it/s]

 40%|████      | 12167/30196 [25:25<32:59,  9.11it/s]

 40%|████      | 12169/30196 [25:25<32:49,  9.15it/s]

 40%|████      | 12170/30196 [25:26<35:10,  8.54it/s]

 40%|████      | 12171/30196 [25:26<36:23,  8.25it/s]

 40%|████      | 12173/30196 [25:26<37:10,  8.08it/s]

 40%|████      | 12175/30196 [25:26<32:26,  9.26it/s]

 40%|████      | 12177/30196 [25:26<35:39,  8.42it/s]

 40%|████      | 12178/30196 [25:27<38:49,  7.73it/s]

 40%|████      | 12179/30196 [25:27<39:37,  7.58it/s]

 40%|████      | 12181/30196 [25:27<32:04,  9.36it/s]

 40%|████      | 12182/30196 [25:27<36:06,  8.32it/s]

 40%|████      | 12183/30196 [25:28<1:12:59,  4.11it/s]

 40%|████      | 12184/30196 [25:28<1:07:14,  4.46it/s]

 40%|████      | 12185/30196 [25:28<1:00:34,  4.96it/s]

 40%|████      | 12187/30196 [25:28<43:19,  6.93it/s]

 40%|████      | 12188/30196 [25:28<50:39,  5.93it/s]

 40%|████      | 12190/30196 [25:29<1:02:19,  4.82it/s]

 40%|████      | 12192/30196 [25:29<45:18,  6.62it/s]

 40%|████      | 12194/30196 [25:29<41:17,  7.27it/s]

 40%|████      | 12196/30196 [25:30<43:25,  6.91it/s]

 40%|████      | 12197/30196 [25:30<45:22,  6.61it/s]

 40%|████      | 12199/30196 [25:30<38:39,  7.76it/s]

 40%|████      | 12200/30196 [25:30<41:09,  7.29it/s]

 40%|████      | 12201/30196 [25:30<43:07,  6.95it/s]

 40%|████      | 12202/30196 [25:30<44:39,  6.71it/s]

 40%|████      | 12203/30196 [25:31<46:56,  6.39it/s]

 40%|████      | 12205/30196 [25:31<39:20,  7.62it/s]

 40%|████      | 12206/30196 [25:31<40:30,  7.40it/s]

 40%|████      | 12208/30196 [25:31<31:56,  9.39it/s]

 40%|████      | 12210/30196 [25:31<32:42,  9.16it/s]

 40%|████      | 12211/30196 [25:31<36:25,  8.23it/s]

 40%|████      | 12212/30196 [25:32<35:36,  8.42it/s]

 40%|████      | 12214/30196 [25:32<30:08,  9.94it/s]

 40%|████      | 12216/30196 [25:32<28:04, 10.67it/s]

 40%|████      | 12218/30196 [25:32<34:05,  8.79it/s]

 40%|████      | 12220/30196 [25:32<33:47,  8.87it/s]

 40%|████      | 12222/30196 [25:33<35:17,  8.49it/s]

 40%|████      | 12223/30196 [25:33<35:24,  8.46it/s]

 40%|████      | 12224/30196 [25:33<36:28,  8.21it/s]

 40%|████      | 12226/30196 [25:33<30:14,  9.90it/s]

 40%|████      | 12228/30196 [25:33<33:33,  8.93it/s]

 41%|████      | 12230/30196 [25:33<33:18,  8.99it/s]

 41%|████      | 12232/30196 [25:34<32:17,  9.27it/s]

 41%|████      | 12233/30196 [25:34<32:25,  9.23it/s]

 41%|████      | 12235/30196 [25:34<30:31,  9.81it/s]

 41%|████      | 12236/30196 [25:34<32:49,  9.12it/s]

 41%|████      | 12237/30196 [25:34<32:43,  9.15it/s]

 41%|████      | 12238/30196 [25:34<36:44,  8.15it/s]

 41%|████      | 12240/30196 [25:35<30:41,  9.75it/s]

 41%|████      | 12242/30196 [25:35<33:53,  8.83it/s]

 41%|████      | 12244/30196 [25:35<28:55, 10.35it/s]

 41%|████      | 12246/30196 [25:35<32:15,  9.27it/s]

 41%|████      | 12248/30196 [25:35<35:19,  8.47it/s]

 41%|████      | 12250/30196 [25:36<32:43,  9.14it/s]

 41%|████      | 12252/30196 [25:36<39:46,  7.52it/s]

 41%|████      | 12253/30196 [25:36<48:59,  6.10it/s]

 41%|████      | 12255/30196 [25:37<44:00,  6.80it/s]

 41%|████      | 12256/30196 [25:37<45:10,  6.62it/s]

 41%|████      | 12257/30196 [25:37<42:31,  7.03it/s]

 41%|████      | 12259/30196 [25:37<35:33,  8.41it/s]

 41%|████      | 12261/30196 [25:37<34:24,  8.69it/s]

 41%|████      | 12263/30196 [25:37<30:07,  9.92it/s]

 41%|████      | 12265/30196 [25:38<30:08,  9.91it/s]

 41%|████      | 12267/30196 [25:38<27:26, 10.89it/s]

 41%|████      | 12269/30196 [25:38<34:10,  8.74it/s]

 41%|████      | 12270/30196 [25:38<35:05,  8.51it/s]

 41%|████      | 12272/30196 [25:38<32:44,  9.12it/s]

 41%|████      | 12273/30196 [25:38<33:58,  8.79it/s]

 41%|████      | 12274/30196 [25:39<37:58,  7.87it/s]

 41%|████      | 12275/30196 [25:39<40:03,  7.46it/s]

 41%|████      | 12276/30196 [25:39<37:51,  7.89it/s]

 41%|████      | 12278/30196 [25:39<32:41,  9.14it/s]

 41%|████      | 12279/30196 [25:39<32:23,  9.22it/s]

 41%|████      | 12280/30196 [25:39<32:07,  9.30it/s]

 41%|████      | 12281/30196 [25:39<37:40,  7.93it/s]

 41%|████      | 12282/30196 [25:40<41:30,  7.19it/s]

 41%|████      | 12283/30196 [25:40<41:54,  7.12it/s]

 41%|████      | 12284/30196 [25:40<48:10,  6.20it/s]

 41%|████      | 12285/30196 [25:40<49:23,  6.04it/s]

 41%|████      | 12286/30196 [25:40<46:38,  6.40it/s]

 41%|████      | 12287/30196 [25:40<44:26,  6.72it/s]

 41%|████      | 12289/30196 [25:41<35:11,  8.48it/s]

 41%|████      | 12290/30196 [25:41<36:08,  8.26it/s]

 41%|████      | 12291/30196 [25:41<35:14,  8.47it/s]

 41%|████      | 12293/30196 [25:41<27:14, 10.95it/s]

 41%|████      | 12295/30196 [25:41<27:51, 10.71it/s]

 41%|████      | 12297/30196 [25:41<28:14, 10.56it/s]

 41%|████      | 12299/30196 [25:42<31:49,  9.37it/s]

 41%|████      | 12300/30196 [25:42<35:24,  8.42it/s]

 41%|████      | 12301/30196 [25:42<44:12,  6.75it/s]

 41%|████      | 12302/30196 [25:42<52:05,  5.73it/s]

 41%|████      | 12303/30196 [25:43<57:52,  5.15it/s]

 41%|████      | 12304/30196 [25:43<1:03:09,  4.72it/s]

 41%|████      | 12305/30196 [25:43<54:23,  5.48it/s]

 41%|████      | 12306/30196 [25:43<52:59,  5.63it/s]

 41%|████      | 12307/30196 [25:43<51:52,  5.75it/s]

 41%|████      | 12308/30196 [25:43<52:26,  5.68it/s]

 41%|████      | 12310/30196 [25:44<41:15,  7.23it/s]

 41%|████      | 12312/30196 [25:44<32:57,  9.04it/s]

 41%|████      | 12314/30196 [25:44<27:32, 10.82it/s]

 41%|████      | 12316/30196 [25:44<26:18, 11.32it/s]

 41%|████      | 12318/30196 [25:44<27:17, 10.92it/s]

 41%|████      | 12320/30196 [25:44<27:23, 10.88it/s]

 41%|████      | 12322/30196 [25:45<29:03, 10.25it/s]

 41%|████      | 12324/30196 [25:45<34:50,  8.55it/s]

 41%|████      | 12325/30196 [25:45<36:05,  8.25it/s]

 41%|████      | 12326/30196 [25:45<36:52,  8.08it/s]

 41%|████      | 12327/30196 [25:45<37:22,  7.97it/s]

 41%|████      | 12329/30196 [25:45<28:36, 10.41it/s]

 41%|████      | 12331/30196 [25:46<32:23,  9.19it/s]

 41%|████      | 12333/30196 [25:46<30:38,  9.72it/s]

 41%|████      | 12335/30196 [25:47<51:03,  5.83it/s]

 41%|████      | 12337/30196 [25:47<46:13,  6.44it/s]

 41%|████      | 12338/30196 [25:47<49:25,  6.02it/s]

 41%|████      | 12340/30196 [25:47<40:06,  7.42it/s]

 41%|████      | 12342/30196 [25:47<35:31,  8.38it/s]

 41%|████      | 12343/30196 [25:47<34:58,  8.51it/s]

 41%|████      | 12344/30196 [25:48<41:28,  7.17it/s]

 41%|████      | 12345/30196 [25:48<40:53,  7.27it/s]

 41%|████      | 12347/30196 [25:48<33:02,  9.00it/s]

 41%|████      | 12349/30196 [25:48<29:47,  9.98it/s]

 41%|████      | 12351/30196 [25:48<31:38,  9.40it/s]

 41%|████      | 12352/30196 [25:48<31:53,  9.33it/s]

 41%|████      | 12353/30196 [25:49<32:03,  9.28it/s]

 41%|████      | 12354/30196 [25:49<33:41,  8.83it/s]

 41%|████      | 12355/30196 [25:49<35:15,  8.43it/s]

 41%|████      | 12357/30196 [25:49<31:01,  9.58it/s]

 41%|████      | 12359/30196 [25:49<30:02,  9.89it/s]

 41%|████      | 12360/30196 [25:49<33:03,  8.99it/s]

 41%|████      | 12361/30196 [25:49<37:44,  7.88it/s]

 41%|████      | 12363/30196 [25:50<36:27,  8.15it/s]

 41%|████      | 12364/30196 [25:50<37:02,  8.02it/s]

 41%|████      | 12366/30196 [25:50<36:00,  8.25it/s]

 41%|████      | 12368/30196 [25:50<30:22,  9.78it/s]

 41%|████      | 12370/30196 [25:50<29:52,  9.95it/s]

 41%|████      | 12372/30196 [25:51<30:46,  9.65it/s]

 41%|████      | 12374/30196 [25:51<30:02,  9.89it/s]

 41%|████      | 12376/30196 [25:51<33:52,  8.77it/s]

 41%|████      | 12378/30196 [25:51<32:38,  9.10it/s]

 41%|████      | 12380/30196 [25:52<34:07,  8.70it/s]

 41%|████      | 12381/30196 [25:52<35:29,  8.36it/s]

 41%|████      | 12382/30196 [25:52<36:12,  8.20it/s]

 41%|████      | 12384/30196 [25:52<31:33,  9.41it/s]

 41%|████      | 12386/30196 [25:52<31:23,  9.46it/s]

 41%|████      | 12388/30196 [25:52<26:42, 11.11it/s]

 41%|████      | 12390/30196 [25:53<27:59, 10.60it/s]

 41%|████      | 12392/30196 [25:53<29:20, 10.11it/s]

 41%|████      | 12394/30196 [25:53<32:13,  9.21it/s]

 41%|████      | 12397/30196 [25:53<30:10,  9.83it/s]

 41%|████      | 12399/30196 [25:54<33:52,  8.75it/s]

 41%|████      | 12401/30196 [25:54<28:54, 10.26it/s]

 41%|████      | 12403/30196 [25:54<31:48,  9.33it/s]

 41%|████      | 12405/30196 [25:54<28:20, 10.46it/s]

 41%|████      | 12407/30196 [25:54<27:35, 10.75it/s]

 41%|████      | 12409/30196 [25:55<31:54,  9.29it/s]

 41%|████      | 12411/30196 [25:55<33:37,  8.81it/s]

 41%|████      | 12412/30196 [25:55<35:02,  8.46it/s]

 41%|████      | 12413/30196 [25:55<42:49,  6.92it/s]

 41%|████      | 12414/30196 [25:55<44:10,  6.71it/s]

 41%|████      | 12416/30196 [25:56<35:21,  8.38it/s]

 41%|████      | 12417/30196 [25:56<34:43,  8.53it/s]

 41%|████      | 12419/30196 [25:56<32:37,  9.08it/s]

 41%|████      | 12420/30196 [25:56<32:31,  9.11it/s]

 41%|████      | 12421/30196 [25:56<34:13,  8.66it/s]

 41%|████      | 12423/30196 [25:56<30:18,  9.77it/s]

 41%|████      | 12425/30196 [25:56<27:19, 10.84it/s]

 41%|████      | 12427/30196 [25:57<38:58,  7.60it/s]

 41%|████      | 12429/30196 [25:57<36:54,  8.02it/s]

 41%|████      | 12430/30196 [25:57<38:04,  7.78it/s]

 41%|████      | 12432/30196 [25:57<32:32,  9.10it/s]

 41%|████      | 12433/30196 [25:57<34:47,  8.51it/s]

 41%|████      | 12434/30196 [25:58<35:56,  8.24it/s]

 41%|████      | 12435/30196 [25:58<49:24,  5.99it/s]

 41%|████      | 12437/30196 [25:58<42:39,  6.94it/s]

 41%|████      | 12438/30196 [25:58<42:52,  6.90it/s]

 41%|████      | 12440/30196 [25:58<32:43,  9.04it/s]

 41%|████      | 12442/30196 [25:59<30:35,  9.67it/s]

 41%|████      | 12444/30196 [25:59<29:58,  9.87it/s]

 41%|████      | 12446/30196 [25:59<32:02,  9.23it/s]

 41%|████      | 12447/30196 [25:59<43:29,  6.80it/s]

 41%|████      | 12449/30196 [25:59<36:32,  8.09it/s]

 41%|████      | 12450/30196 [26:00<39:04,  7.57it/s]

 41%|████      | 12451/30196 [26:00<38:56,  7.59it/s]

 41%|████      | 12453/30196 [26:00<35:24,  8.35it/s]

 41%|████      | 12454/30196 [26:00<36:21,  8.13it/s]

 41%|████      | 12455/30196 [26:00<35:24,  8.35it/s]

 41%|████▏     | 12457/30196 [26:00<28:22, 10.42it/s]

 41%|████▏     | 12459/30196 [26:01<28:25, 10.40it/s]

 41%|████▏     | 12461/30196 [26:01<31:10,  9.48it/s]

 41%|████▏     | 12462/30196 [26:01<31:17,  9.44it/s]

 41%|████▏     | 12463/30196 [26:01<38:15,  7.73it/s]

 41%|████▏     | 12464/30196 [26:01<36:30,  8.10it/s]

 41%|████▏     | 12465/30196 [26:01<40:38,  7.27it/s]

 41%|████▏     | 12466/30196 [26:01<38:26,  7.69it/s]

 41%|████▏     | 12468/30196 [26:02<34:26,  8.58it/s]

 41%|████▏     | 12470/30196 [26:02<28:11, 10.48it/s]

 41%|████▏     | 12472/30196 [26:02<32:29,  9.09it/s]

 41%|████▏     | 12473/30196 [26:02<35:54,  8.22it/s]

 41%|████▏     | 12474/30196 [26:02<36:51,  8.01it/s]

 41%|████▏     | 12475/30196 [26:03<40:29,  7.29it/s]

 41%|████▏     | 12476/30196 [26:03<40:16,  7.33it/s]

 41%|████▏     | 12477/30196 [26:03<46:51,  6.30it/s]

 41%|████▏     | 12479/30196 [26:03<38:12,  7.73it/s]

 41%|████▏     | 12480/30196 [26:03<40:58,  7.21it/s]

 41%|████▏     | 12482/30196 [26:03<30:40,  9.63it/s]

 41%|████▏     | 12484/30196 [26:04<29:16, 10.09it/s]

 41%|████▏     | 12486/30196 [26:04<31:18,  9.43it/s]

 41%|████▏     | 12488/30196 [26:04<37:15,  7.92it/s]

 41%|████▏     | 12490/30196 [26:04<34:31,  8.55it/s]

 41%|████▏     | 12491/30196 [26:04<35:31,  8.31it/s]

 41%|████▏     | 12492/30196 [26:05<38:11,  7.72it/s]

 41%|████▏     | 12493/30196 [26:05<38:29,  7.66it/s]

 41%|████▏     | 12495/30196 [26:05<34:18,  8.60it/s]

 41%|████▏     | 12496/30196 [26:05<35:53,  8.22it/s]

 41%|████▏     | 12497/30196 [26:05<36:28,  8.09it/s]

 41%|████▏     | 12499/30196 [26:05<30:56,  9.53it/s]

 41%|████▏     | 12501/30196 [26:06<29:33,  9.98it/s]

 41%|████▏     | 12502/30196 [26:06<29:51,  9.88it/s]

 41%|████▏     | 12503/30196 [26:06<31:08,  9.47it/s]

 41%|████▏     | 12505/30196 [26:06<32:43,  9.01it/s]

 41%|████▏     | 12506/30196 [26:06<32:39,  9.03it/s]

 41%|████▏     | 12508/30196 [26:06<28:36, 10.30it/s]

 41%|████▏     | 12510/30196 [26:07<35:48,  8.23it/s]

 41%|████▏     | 12511/30196 [26:07<38:53,  7.58it/s]

 41%|████▏     | 12512/30196 [26:07<38:46,  7.60it/s]

 41%|████▏     | 12513/30196 [26:07<39:51,  7.40it/s]

 41%|████▏     | 12514/30196 [26:07<42:49,  6.88it/s]

 41%|████▏     | 12516/30196 [26:07<36:46,  8.01it/s]

 41%|████▏     | 12517/30196 [26:08<35:23,  8.33it/s]

 41%|████▏     | 12518/30196 [26:08<37:17,  7.90it/s]

 41%|████▏     | 12520/30196 [26:08<33:38,  8.76it/s]

 41%|████▏     | 12521/30196 [26:08<37:06,  7.94it/s]

 41%|████▏     | 12522/30196 [26:08<42:52,  6.87it/s]

 41%|████▏     | 12523/30196 [26:08<42:07,  6.99it/s]

 41%|████▏     | 12525/30196 [26:09<41:14,  7.14it/s]

 41%|████▏     | 12526/30196 [26:09<39:08,  7.52it/s]

 41%|████▏     | 12528/30196 [26:09<34:05,  8.64it/s]

 41%|████▏     | 12530/30196 [26:09<28:45, 10.24it/s]

 42%|████▏     | 12532/30196 [26:09<30:02,  9.80it/s]

 42%|████▏     | 12534/30196 [26:10<34:24,  8.56it/s]

 42%|████▏     | 12535/30196 [26:10<35:27,  8.30it/s]

 42%|████▏     | 12537/30196 [26:10<34:22,  8.56it/s]

 42%|████▏     | 12538/30196 [26:10<35:09,  8.37it/s]

 42%|████▏     | 12540/30196 [26:10<28:41, 10.26it/s]

 42%|████▏     | 12542/30196 [26:10<28:33, 10.30it/s]

 42%|████▏     | 12544/30196 [26:11<32:46,  8.98it/s]

 42%|████▏     | 12546/30196 [26:11<28:28, 10.33it/s]

 42%|████▏     | 12548/30196 [26:11<25:37, 11.48it/s]

 42%|████▏     | 12551/30196 [26:11<26:03, 11.28it/s]

 42%|████▏     | 12553/30196 [26:11<25:58, 11.32it/s]

 42%|████▏     | 12555/30196 [26:12<24:25, 12.04it/s]

 42%|████▏     | 12557/30196 [26:12<25:45, 11.41it/s]

 42%|████▏     | 12559/30196 [26:12<23:50, 12.33it/s]

 42%|████▏     | 12561/30196 [26:12<25:41, 11.44it/s]

 42%|████▏     | 12563/30196 [26:12<31:03,  9.46it/s]

 42%|████▏     | 12565/30196 [26:13<32:04,  9.16it/s]

 42%|████▏     | 12566/30196 [26:13<33:40,  8.73it/s]

 42%|████▏     | 12567/30196 [26:13<35:02,  8.38it/s]

 42%|████▏     | 12568/30196 [26:13<38:39,  7.60it/s]

 42%|████▏     | 12569/30196 [26:13<43:53,  6.69it/s]

 42%|████▏     | 12570/30196 [26:13<48:18,  6.08it/s]

 42%|████▏     | 12571/30196 [26:14<44:03,  6.67it/s]

 42%|████▏     | 12572/30196 [26:14<45:22,  6.47it/s]

 42%|████▏     | 12573/30196 [26:14<50:53,  5.77it/s]

 42%|████▏     | 12575/30196 [26:14<38:59,  7.53it/s]

 42%|████▏     | 12576/30196 [26:14<41:29,  7.08it/s]

 42%|████▏     | 12579/30196 [26:15<33:19,  8.81it/s]

 42%|████▏     | 12580/30196 [26:15<34:16,  8.56it/s]

 42%|████▏     | 12581/30196 [26:15<44:14,  6.64it/s]

 42%|████▏     | 12582/30196 [26:15<41:03,  7.15it/s]

 42%|████▏     | 12584/30196 [26:15<31:19,  9.37it/s]

 42%|████▏     | 12586/30196 [26:16<42:16,  6.94it/s]

 42%|████▏     | 12588/30196 [26:16<39:39,  7.40it/s]

 42%|████▏     | 12591/30196 [26:16<35:31,  8.26it/s]

 42%|████▏     | 12593/30196 [26:16<36:35,  8.02it/s]

 42%|████▏     | 12594/30196 [26:17<39:22,  7.45it/s]

 42%|████▏     | 12595/30196 [26:17<40:02,  7.33it/s]

 42%|████▏     | 12596/30196 [26:17<41:57,  6.99it/s]

 42%|████▏     | 12597/30196 [26:17<41:05,  7.14it/s]

 42%|████▏     | 12598/30196 [26:17<38:46,  7.56it/s]

 42%|████▏     | 12599/30196 [26:17<38:40,  7.58it/s]

 42%|████▏     | 12600/30196 [26:17<36:51,  7.96it/s]

 42%|████▏     | 12601/30196 [26:18<41:13,  7.11it/s]

 42%|████▏     | 12602/30196 [26:18<41:13,  7.11it/s]

 42%|████▏     | 12603/30196 [26:18<43:40,  6.71it/s]

 42%|████▏     | 12605/30196 [26:18<30:55,  9.48it/s]

 42%|████▏     | 12607/30196 [26:18<32:50,  8.92it/s]

 42%|████▏     | 12608/30196 [26:18<35:04,  8.36it/s]

 42%|████▏     | 12609/30196 [26:18<36:27,  8.04it/s]

 42%|████▏     | 12610/30196 [26:19<37:42,  7.77it/s]

 42%|████▏     | 12611/30196 [26:19<38:43,  7.57it/s]

 42%|████▏     | 12612/30196 [26:19<43:37,  6.72it/s]

 42%|████▏     | 12613/30196 [26:19<40:23,  7.26it/s]

 42%|████▏     | 12614/30196 [26:19<40:03,  7.32it/s]

 42%|████▏     | 12615/30196 [26:19<39:29,  7.42it/s]

 42%|████▏     | 12617/30196 [26:19<30:00,  9.77it/s]

 42%|████▏     | 12619/30196 [26:20<40:50,  7.17it/s]

 42%|████▏     | 12621/30196 [26:20<36:09,  8.10it/s]

 42%|████▏     | 12623/30196 [26:20<34:23,  8.52it/s]

 42%|████▏     | 12625/30196 [26:20<31:37,  9.26it/s]

 42%|████▏     | 12626/30196 [26:21<33:27,  8.75it/s]

 42%|████▏     | 12627/30196 [26:21<54:15,  5.40it/s]

 42%|████▏     | 12629/30196 [26:21<43:50,  6.68it/s]

 42%|████▏     | 12630/30196 [26:21<41:21,  7.08it/s]

 42%|████▏     | 12632/30196 [26:21<31:18,  9.35it/s]

 42%|████▏     | 12634/30196 [26:22<34:38,  8.45it/s]

 42%|████▏     | 12636/30196 [26:22<40:03,  7.31it/s]

 42%|████▏     | 12638/30196 [26:22<34:15,  8.54it/s]

 42%|████▏     | 12640/30196 [26:22<30:37,  9.56it/s]

 42%|████▏     | 12642/30196 [26:23<31:28,  9.29it/s]

 42%|████▏     | 12644/30196 [26:23<35:33,  8.23it/s]

 42%|████▏     | 12646/30196 [26:23<31:10,  9.38it/s]

 42%|████▏     | 12648/30196 [26:23<35:54,  8.14it/s]

 42%|████▏     | 12649/30196 [26:23<36:22,  8.04it/s]

 42%|████▏     | 12650/30196 [26:24<36:59,  7.90it/s]

 42%|████▏     | 12652/30196 [26:24<33:41,  8.68it/s]

 42%|████▏     | 12653/30196 [26:24<35:03,  8.34it/s]

 42%|████▏     | 12654/30196 [26:24<35:42,  8.19it/s]

 42%|████▏     | 12656/30196 [26:24<30:20,  9.64it/s]

 42%|████▏     | 12657/30196 [26:24<32:46,  8.92it/s]

 42%|████▏     | 12659/30196 [26:25<31:37,  9.24it/s]

 42%|████▏     | 12660/30196 [26:25<31:43,  9.21it/s]

 42%|████▏     | 12661/30196 [26:25<34:25,  8.49it/s]

 42%|████▏     | 12662/30196 [26:25<38:15,  7.64it/s]

 42%|████▏     | 12664/30196 [26:25<35:00,  8.35it/s]

 42%|████▏     | 12665/30196 [26:25<34:17,  8.52it/s]

 42%|████▏     | 12666/30196 [26:25<37:54,  7.71it/s]

 42%|████▏     | 12668/30196 [26:26<35:27,  8.24it/s]

 42%|████▏     | 12670/30196 [26:26<34:40,  8.43it/s]

 42%|████▏     | 12671/30196 [26:26<34:09,  8.55it/s]

 42%|████▏     | 12672/30196 [26:26<33:23,  8.75it/s]

 42%|████▏     | 12673/30196 [26:26<35:48,  8.16it/s]

 42%|████▏     | 12675/30196 [26:27<33:38,  8.68it/s]

 42%|████▏     | 12677/30196 [26:27<30:50,  9.47it/s]

 42%|████▏     | 12679/30196 [26:27<28:13, 10.35it/s]

 42%|████▏     | 12681/30196 [26:27<28:22, 10.29it/s]

 42%|████▏     | 12683/30196 [26:27<30:42,  9.51it/s]

 42%|████▏     | 12685/30196 [26:27<27:52, 10.47it/s]

 42%|████▏     | 12687/30196 [26:28<34:52,  8.37it/s]

 42%|████▏     | 12689/30196 [26:28<31:57,  9.13it/s]

 42%|████▏     | 12691/30196 [26:28<28:49, 10.12it/s]

 42%|████▏     | 12693/30196 [26:28<25:12, 11.57it/s]

 42%|████▏     | 12695/30196 [26:28<26:28, 11.02it/s]

 42%|████▏     | 12697/30196 [26:29<45:59,  6.34it/s]

 42%|████▏     | 12699/30196 [26:29<36:51,  7.91it/s]

 42%|████▏     | 12701/30196 [26:29<40:16,  7.24it/s]

 42%|████▏     | 12703/30196 [26:30<41:57,  6.95it/s]

 42%|████▏     | 12704/30196 [26:30<42:05,  6.93it/s]

 42%|████▏     | 12705/30196 [26:30<43:22,  6.72it/s]

 42%|████▏     | 12706/30196 [26:30<44:41,  6.52it/s]

 42%|████▏     | 12708/30196 [26:30<36:16,  8.03it/s]

 42%|████▏     | 12709/30196 [26:31<35:03,  8.31it/s]

 42%|████▏     | 12710/30196 [26:31<41:52,  6.96it/s]

 42%|████▏     | 12712/30196 [26:31<37:29,  7.77it/s]

 42%|████▏     | 12714/30196 [26:31<35:07,  8.29it/s]

 42%|████▏     | 12716/30196 [26:31<36:14,  8.04it/s]

 42%|████▏     | 12718/30196 [26:32<35:17,  8.25it/s]

 42%|████▏     | 12720/30196 [26:32<32:21,  9.00it/s]

 42%|████▏     | 12722/30196 [26:32<31:14,  9.32it/s]

 42%|████▏     | 12723/30196 [26:32<32:42,  8.90it/s]

 42%|████▏     | 12724/30196 [26:32<39:47,  7.32it/s]

 42%|████▏     | 12726/30196 [26:33<39:23,  7.39it/s]

 42%|████▏     | 12727/30196 [26:33<44:06,  6.60it/s]

 42%|████▏     | 12728/30196 [26:33<52:01,  5.60it/s]

 42%|████▏     | 12730/30196 [26:33<48:24,  6.01it/s]

 42%|████▏     | 12732/30196 [26:34<36:54,  7.89it/s]

 42%|████▏     | 12733/30196 [26:34<42:04,  6.92it/s]

 42%|████▏     | 12735/30196 [26:34<41:14,  7.06it/s]

 42%|████▏     | 12736/30196 [26:34<43:25,  6.70it/s]

 42%|████▏     | 12737/30196 [26:34<40:48,  7.13it/s]

 42%|████▏     | 12738/30196 [26:34<40:27,  7.19it/s]

 42%|████▏     | 12739/30196 [26:35<37:53,  7.68it/s]

 42%|████▏     | 12740/30196 [26:35<35:47,  8.13it/s]

 42%|████▏     | 12742/30196 [26:35<33:01,  8.81it/s]

 42%|████▏     | 12743/30196 [26:35<32:42,  8.89it/s]

 42%|████▏     | 12745/30196 [26:35<28:20, 10.26it/s]

 42%|████▏     | 12747/30196 [26:35<32:50,  8.86it/s]

 42%|████▏     | 12749/30196 [26:36<31:52,  9.12it/s]

 42%|████▏     | 12751/30196 [26:36<31:38,  9.19it/s]

 42%|████▏     | 12752/30196 [26:36<33:02,  8.80it/s]

 42%|████▏     | 12755/30196 [26:36<27:02, 10.75it/s]

 42%|████▏     | 12757/30196 [26:37<32:54,  8.83it/s]

 42%|████▏     | 12758/30196 [26:37<34:01,  8.54it/s]

 42%|████▏     | 12760/30196 [26:37<32:18,  9.00it/s]

 42%|████▏     | 12762/30196 [26:37<32:08,  9.04it/s]

 42%|████▏     | 12764/30196 [26:37<32:49,  8.85it/s]

 42%|████▏     | 12765/30196 [26:37<33:58,  8.55it/s]

 42%|████▏     | 12767/30196 [26:38<30:45,  9.44it/s]

 42%|████▏     | 12768/30196 [26:38<32:09,  9.03it/s]

 42%|████▏     | 12770/30196 [26:38<32:45,  8.86it/s]

 42%|████▏     | 12772/30196 [26:38<39:14,  7.40it/s]

 42%|████▏     | 12774/30196 [26:38<32:28,  8.94it/s]

 42%|████▏     | 12776/30196 [26:39<28:13, 10.29it/s]

 42%|████▏     | 12778/30196 [26:39<30:07,  9.64it/s]

 42%|████▏     | 12780/30196 [26:39<29:35,  9.81it/s]

 42%|████▏     | 12782/30196 [26:39<29:30,  9.83it/s]

 42%|████▏     | 12784/30196 [26:39<29:25,  9.86it/s]

 42%|████▏     | 12786/30196 [26:40<35:49,  8.10it/s]

 42%|████▏     | 12788/30196 [26:40<38:51,  7.47it/s]

 42%|████▏     | 12789/30196 [26:40<37:36,  7.71it/s]

 42%|████▏     | 12791/30196 [26:40<37:17,  7.78it/s]

 42%|████▏     | 12793/30196 [26:41<34:39,  8.37it/s]

 42%|████▏     | 12794/30196 [26:41<36:05,  8.03it/s]

 42%|████▏     | 12796/30196 [26:41<44:51,  6.47it/s]

 42%|████▏     | 12798/30196 [26:41<42:25,  6.84it/s]

 42%|████▏     | 12799/30196 [26:42<41:44,  6.95it/s]

 42%|████▏     | 12801/30196 [26:42<35:01,  8.28it/s]

 42%|████▏     | 12802/30196 [26:42<38:25,  7.54it/s]

 42%|████▏     | 12803/30196 [26:42<38:37,  7.51it/s]

 42%|████▏     | 12804/30196 [26:42<39:09,  7.40it/s]

 42%|████▏     | 12805/30196 [26:42<44:57,  6.45it/s]

 42%|████▏     | 12806/30196 [26:43<41:26,  6.99it/s]

 42%|████▏     | 12807/30196 [26:43<40:29,  7.16it/s]

 42%|████▏     | 12808/30196 [26:43<39:36,  7.32it/s]

 42%|████▏     | 12809/30196 [26:43<39:08,  7.40it/s]

 42%|████▏     | 12812/30196 [26:43<26:14, 11.04it/s]

 42%|████▏     | 12814/30196 [26:43<32:26,  8.93it/s]

 42%|████▏     | 12816/30196 [26:44<28:55, 10.01it/s]

 42%|████▏     | 12818/30196 [26:44<32:39,  8.87it/s]

 42%|████▏     | 12821/30196 [26:44<29:17,  9.88it/s]

 42%|████▏     | 12823/30196 [26:44<27:07, 10.67it/s]

 42%|████▏     | 12825/30196 [26:44<27:15, 10.62it/s]

 42%|████▏     | 12827/30196 [26:45<30:41,  9.43it/s]

 42%|████▏     | 12828/30196 [26:45<32:15,  8.97it/s]

 42%|████▏     | 12829/30196 [26:45<37:58,  7.62it/s]

 42%|████▏     | 12831/30196 [26:45<33:47,  8.56it/s]

 42%|████▏     | 12833/30196 [26:45<29:24,  9.84it/s]

 43%|████▎     | 12835/30196 [26:46<30:27,  9.50it/s]

 43%|████▎     | 12837/30196 [26:46<32:05,  9.02it/s]

 43%|████▎     | 12840/30196 [26:46<26:41, 10.84it/s]

 43%|████▎     | 12842/30196 [26:46<28:29, 10.15it/s]

 43%|████▎     | 12844/30196 [26:47<30:48,  9.39it/s]

 43%|████▎     | 12845/30196 [26:47<31:57,  9.05it/s]

 43%|████▎     | 12846/30196 [26:47<32:29,  8.90it/s]

 43%|████▎     | 12847/30196 [26:47<32:01,  9.03it/s]

 43%|████▎     | 12848/30196 [26:47<33:15,  8.70it/s]

 43%|████▎     | 12850/30196 [26:47<33:30,  8.63it/s]

 43%|████▎     | 12852/30196 [26:47<28:54, 10.00it/s]

 43%|████▎     | 12854/30196 [26:48<25:44, 11.22it/s]

 43%|████▎     | 12856/30196 [26:48<23:40, 12.21it/s]

 43%|████▎     | 12858/30196 [26:48<25:51, 11.18it/s]

 43%|████▎     | 12860/30196 [26:48<24:34, 11.75it/s]

 43%|████▎     | 12862/30196 [26:48<23:45, 12.16it/s]

 43%|████▎     | 12864/30196 [26:48<21:40, 13.33it/s]

 43%|████▎     | 12866/30196 [26:49<37:27,  7.71it/s]

 43%|████▎     | 12868/30196 [26:49<38:40,  7.47it/s]

 43%|████▎     | 12869/30196 [26:49<37:27,  7.71it/s]

 43%|████▎     | 12870/30196 [26:49<36:17,  7.96it/s]

 43%|████▎     | 12872/30196 [26:49<29:50,  9.68it/s]

 43%|████▎     | 12874/30196 [26:50<30:23,  9.50it/s]

 43%|████▎     | 12876/30196 [26:50<25:59, 11.11it/s]

 43%|████▎     | 12878/30196 [26:50<33:20,  8.66it/s]

 43%|████▎     | 12880/30196 [26:50<35:43,  8.08it/s]

 43%|████▎     | 12881/30196 [26:51<37:59,  7.59it/s]

 43%|████▎     | 12882/30196 [26:51<36:40,  7.87it/s]

 43%|████▎     | 12883/30196 [26:51<48:53,  5.90it/s]

 43%|████▎     | 12885/30196 [26:51<42:28,  6.79it/s]

 43%|████▎     | 12887/30196 [26:51<36:21,  7.93it/s]

 43%|████▎     | 12889/30196 [26:52<30:41,  9.40it/s]

 43%|████▎     | 12891/30196 [26:52<31:22,  9.19it/s]

 43%|████▎     | 12893/30196 [26:52<29:43,  9.70it/s]

 43%|████▎     | 12895/30196 [26:52<29:42,  9.70it/s]

 43%|████▎     | 12897/30196 [26:52<28:26, 10.14it/s]

 43%|████▎     | 12899/30196 [26:53<27:40, 10.42it/s]

 43%|████▎     | 12901/30196 [26:53<26:26, 10.90it/s]

 43%|████▎     | 12903/30196 [26:53<30:40,  9.40it/s]

 43%|████▎     | 12904/30196 [26:53<36:50,  7.82it/s]

 43%|████▎     | 12905/30196 [26:53<35:31,  8.11it/s]

 43%|████▎     | 12907/30196 [26:53<30:18,  9.51it/s]

 43%|████▎     | 12909/30196 [26:54<38:04,  7.57it/s]

 43%|████▎     | 12910/30196 [26:54<38:36,  7.46it/s]

 43%|████▎     | 12911/30196 [26:54<40:49,  7.06it/s]

 43%|████▎     | 12912/30196 [26:54<40:18,  7.15it/s]

 43%|████▎     | 12914/30196 [26:54<30:03,  9.58it/s]

 43%|████▎     | 12916/30196 [26:55<32:56,  8.74it/s]

 43%|████▎     | 12917/30196 [26:55<33:54,  8.49it/s]

 43%|████▎     | 12919/30196 [26:55<27:49, 10.35it/s]

 43%|████▎     | 12921/30196 [26:55<33:49,  8.51it/s]

 43%|████▎     | 12922/30196 [26:55<33:24,  8.62it/s]

 43%|████▎     | 12923/30196 [26:56<53:27,  5.39it/s]

 43%|████▎     | 12924/30196 [26:56<59:20,  4.85it/s]

 43%|████▎     | 12925/30196 [26:56<1:00:15,  4.78it/s]

 43%|████▎     | 12926/30196 [26:56<52:12,  5.51it/s]

 43%|████▎     | 12928/30196 [26:57<52:22,  5.49it/s]

 43%|████▎     | 12929/30196 [26:57<49:32,  5.81it/s]

 43%|████▎     | 12930/30196 [26:57<47:00,  6.12it/s]

 43%|████▎     | 12931/30196 [26:57<44:31,  6.46it/s]

 43%|████▎     | 12932/30196 [26:57<43:20,  6.64it/s]

 43%|████▎     | 12933/30196 [26:57<48:32,  5.93it/s]

 43%|████▎     | 12934/30196 [26:58<43:45,  6.58it/s]

 43%|████▎     | 12936/30196 [26:58<38:10,  7.54it/s]

 43%|████▎     | 12938/30196 [26:58<32:18,  8.90it/s]

 43%|████▎     | 12939/30196 [26:58<33:42,  8.53it/s]

 43%|████▎     | 12940/30196 [26:58<32:50,  8.76it/s]

 43%|████▎     | 12942/30196 [26:58<27:57, 10.28it/s]

 43%|████▎     | 12944/30196 [26:59<29:29,  9.75it/s]

 43%|████▎     | 12946/30196 [26:59<32:12,  8.93it/s]

 43%|████▎     | 12948/30196 [26:59<30:20,  9.47it/s]

 43%|████▎     | 12949/30196 [26:59<35:48,  8.03it/s]

 43%|████▎     | 12950/30196 [26:59<44:46,  6.42it/s]

 43%|████▎     | 12951/30196 [27:00<43:43,  6.57it/s]

 43%|████▎     | 12952/30196 [27:00<44:40,  6.43it/s]

 43%|████▎     | 12954/30196 [27:00<34:01,  8.44it/s]

 43%|████▎     | 12956/30196 [27:00<30:06,  9.54it/s]

 43%|████▎     | 12958/30196 [27:00<28:39, 10.02it/s]

 43%|████▎     | 12960/30196 [27:01<34:10,  8.41it/s]

 43%|████▎     | 12962/30196 [27:01<41:23,  6.94it/s]

 43%|████▎     | 12963/30196 [27:01<50:05,  5.73it/s]

 43%|████▎     | 12964/30196 [27:01<47:41,  6.02it/s]

 43%|████▎     | 12965/30196 [27:01<43:36,  6.58it/s]

 43%|████▎     | 12967/30196 [27:02<44:28,  6.46it/s]

 43%|████▎     | 12968/30196 [27:02<41:40,  6.89it/s]

 43%|████▎     | 12969/30196 [27:02<39:11,  7.33it/s]

 43%|████▎     | 12972/30196 [27:02<25:31, 11.24it/s]

 43%|████▎     | 12974/30196 [27:02<30:08,  9.52it/s]

 43%|████▎     | 12977/30196 [27:03<23:19, 12.30it/s]

 43%|████▎     | 12979/30196 [27:03<32:06,  8.94it/s]

 43%|████▎     | 12981/30196 [27:03<27:41, 10.36it/s]

 43%|████▎     | 12983/30196 [27:03<26:21, 10.88it/s]

 43%|████▎     | 12985/30196 [27:04<37:05,  7.73it/s]

 43%|████▎     | 12987/30196 [27:04<36:04,  7.95it/s]

 43%|████▎     | 12988/30196 [27:04<36:29,  7.86it/s]

 43%|████▎     | 12990/30196 [27:04<30:43,  9.33it/s]

 43%|████▎     | 12992/30196 [27:04<26:55, 10.65it/s]

 43%|████▎     | 12995/30196 [27:04<21:07, 13.58it/s]

 43%|████▎     | 12997/30196 [27:05<24:59, 11.47it/s]

 43%|████▎     | 12999/30196 [27:05<25:07, 11.41it/s]

 43%|████▎     | 13001/30196 [27:05<32:43,  8.76it/s]

 43%|████▎     | 13003/30196 [27:05<33:42,  8.50it/s]

 43%|████▎     | 13005/30196 [27:06<32:11,  8.90it/s]

 43%|████▎     | 13006/30196 [27:06<33:04,  8.66it/s]

 43%|████▎     | 13007/30196 [27:06<34:26,  8.32it/s]

 43%|████▎     | 13008/30196 [27:06<38:07,  7.51it/s]

 43%|████▎     | 13010/30196 [27:06<31:34,  9.07it/s]

 43%|████▎     | 13012/30196 [27:06<30:19,  9.45it/s]

 43%|████▎     | 13014/30196 [27:07<27:53, 10.26it/s]

 43%|████▎     | 13016/30196 [27:07<25:33, 11.20it/s]

 43%|████▎     | 13018/30196 [27:07<26:40, 10.73it/s]

 43%|████▎     | 13020/30196 [27:07<27:51, 10.28it/s]

 43%|████▎     | 13022/30196 [27:07<25:34, 11.19it/s]

 43%|████▎     | 13024/30196 [27:08<27:08, 10.54it/s]

 43%|████▎     | 13026/30196 [27:08<31:05,  9.20it/s]

 43%|████▎     | 13027/30196 [27:08<34:33,  8.28it/s]

 43%|████▎     | 13028/30196 [27:08<33:55,  8.43it/s]

 43%|████▎     | 13029/30196 [27:08<34:02,  8.41it/s]

 43%|████▎     | 13030/30196 [27:08<40:08,  7.13it/s]

 43%|████▎     | 13032/30196 [27:09<33:06,  8.64it/s]

 43%|████▎     | 13033/30196 [27:09<32:40,  8.75it/s]

 43%|████▎     | 13034/30196 [27:09<36:19,  7.88it/s]

 43%|████▎     | 13035/30196 [27:09<37:48,  7.56it/s]

 43%|████▎     | 13036/30196 [27:09<40:24,  7.08it/s]

 43%|████▎     | 13038/30196 [27:09<31:40,  9.03it/s]

 43%|████▎     | 13039/30196 [27:10<37:08,  7.70it/s]

 43%|████▎     | 13040/30196 [27:10<37:09,  7.70it/s]

 43%|████▎     | 13041/30196 [27:10<40:04,  7.13it/s]

 43%|████▎     | 13042/30196 [27:10<42:21,  6.75it/s]

 43%|████▎     | 13043/30196 [27:10<40:55,  6.98it/s]

 43%|████▎     | 13044/30196 [27:10<43:02,  6.64it/s]

 43%|████▎     | 13046/30196 [27:10<35:35,  8.03it/s]

 43%|████▎     | 13047/30196 [27:11<42:11,  6.77it/s]

 43%|████▎     | 13048/30196 [27:11<39:25,  7.25it/s]

 43%|████▎     | 13049/30196 [27:11<38:53,  7.35it/s]

 43%|████▎     | 13050/30196 [27:11<38:49,  7.36it/s]

 43%|████▎     | 13052/30196 [27:11<28:56,  9.87it/s]

 43%|████▎     | 13054/30196 [27:11<29:55,  9.55it/s]

 43%|████▎     | 13056/30196 [27:12<25:14, 11.32it/s]

 43%|████▎     | 13058/30196 [27:12<21:35, 13.23it/s]

 43%|████▎     | 13060/30196 [27:12<24:17, 11.76it/s]

 43%|████▎     | 13062/30196 [27:12<27:22, 10.43it/s]

 43%|████▎     | 13064/30196 [27:12<25:14, 11.31it/s]

 43%|████▎     | 13066/30196 [27:12<25:42, 11.10it/s]

 43%|████▎     | 13068/30196 [27:13<26:04, 10.95it/s]

 43%|████▎     | 13070/30196 [27:13<26:33, 10.75it/s]

 43%|████▎     | 13072/30196 [27:13<26:53, 10.61it/s]

 43%|████▎     | 13074/30196 [27:13<28:05, 10.16it/s]

 43%|████▎     | 13076/30196 [27:13<31:09,  9.16it/s]

 43%|████▎     | 13078/30196 [27:14<30:01,  9.50it/s]

 43%|████▎     | 13080/30196 [27:14<29:01,  9.83it/s]

 43%|████▎     | 13083/30196 [27:14<24:29, 11.64it/s]

 43%|████▎     | 13085/30196 [27:14<29:15,  9.75it/s]

 43%|████▎     | 13087/30196 [27:15<30:17,  9.41it/s]

 43%|████▎     | 13088/30196 [27:15<30:30,  9.35it/s]

 43%|████▎     | 13089/30196 [27:15<39:35,  7.20it/s]

 43%|████▎     | 13090/30196 [27:15<39:40,  7.19it/s]

 43%|████▎     | 13091/30196 [27:15<41:36,  6.85it/s]

 43%|████▎     | 13092/30196 [27:15<41:12,  6.92it/s]

 43%|████▎     | 13093/30196 [27:16<45:51,  6.22it/s]

 43%|████▎     | 13094/30196 [27:16<48:28,  5.88it/s]

 43%|████▎     | 13095/30196 [27:16<48:11,  5.91it/s]

 43%|████▎     | 13096/30196 [27:16<52:54,  5.39it/s]

 43%|████▎     | 13097/30196 [27:16<48:19,  5.90it/s]

 43%|████▎     | 13099/30196 [27:17<40:16,  7.07it/s]

 43%|████▎     | 13101/30196 [27:17<31:49,  8.95it/s]

 43%|████▎     | 13103/30196 [27:17<29:58,  9.50it/s]

 43%|████▎     | 13105/30196 [27:17<28:31,  9.99it/s]

 43%|████▎     | 13107/30196 [27:17<25:22, 11.22it/s]

 43%|████▎     | 13109/30196 [27:18<33:16,  8.56it/s]

 43%|████▎     | 13110/30196 [27:18<34:39,  8.22it/s]

 43%|████▎     | 13111/30196 [27:18<35:27,  8.03it/s]

 43%|████▎     | 13112/30196 [27:18<37:32,  7.58it/s]

 43%|████▎     | 13114/30196 [27:18<34:21,  8.28it/s]

 43%|████▎     | 13115/30196 [27:18<37:05,  7.68it/s]

 43%|████▎     | 13116/30196 [27:18<39:47,  7.15it/s]

 43%|████▎     | 13117/30196 [27:19<39:23,  7.23it/s]

 43%|████▎     | 13118/30196 [27:19<36:47,  7.74it/s]

 43%|████▎     | 13120/30196 [27:19<32:39,  8.72it/s]

 43%|████▎     | 13122/30196 [27:19<36:56,  7.70it/s]

 43%|████▎     | 13123/30196 [27:19<36:56,  7.70it/s]

 43%|████▎     | 13124/30196 [27:20<37:41,  7.55it/s]

 43%|████▎     | 13125/30196 [27:20<38:41,  7.35it/s]

 43%|████▎     | 13126/30196 [27:20<39:23,  7.22it/s]

 43%|████▎     | 13128/30196 [27:20<32:13,  8.83it/s]

 43%|████▎     | 13130/30196 [27:20<27:44, 10.26it/s]

 43%|████▎     | 13132/30196 [27:20<33:11,  8.57it/s]

 43%|████▎     | 13133/30196 [27:21<36:47,  7.73it/s]

 43%|████▎     | 13135/30196 [27:21<34:41,  8.20it/s]

 44%|████▎     | 13136/30196 [27:21<36:12,  7.85it/s]

 44%|████▎     | 13137/30196 [27:21<36:33,  7.78it/s]

 44%|████▎     | 13138/30196 [27:21<37:48,  7.52it/s]

 44%|████▎     | 13139/30196 [27:21<47:58,  5.93it/s]

 44%|████▎     | 13140/30196 [27:22<47:42,  5.96it/s]

 44%|████▎     | 13141/30196 [27:22<50:48,  5.59it/s]

 44%|████▎     | 13142/30196 [27:22<54:30,  5.21it/s]

 44%|████▎     | 13143/30196 [27:22<52:22,  5.43it/s]

 44%|████▎     | 13145/30196 [27:23<56:20,  5.04it/s]

 44%|████▎     | 13146/30196 [27:23<52:46,  5.38it/s]

 44%|████▎     | 13148/30196 [27:23<47:46,  5.95it/s]

 44%|████▎     | 13150/30196 [27:23<45:42,  6.21it/s]

 44%|████▎     | 13152/30196 [27:24<37:10,  7.64it/s]

 44%|████▎     | 13154/30196 [27:24<33:37,  8.45it/s]

 44%|████▎     | 13155/30196 [27:24<36:24,  7.80it/s]

 44%|████▎     | 13156/30196 [27:24<34:57,  8.12it/s]

 44%|████▎     | 13158/30196 [27:24<30:35,  9.28it/s]

 44%|████▎     | 13160/30196 [27:24<25:51, 10.98it/s]

 44%|████▎     | 13162/30196 [27:25<27:26, 10.35it/s]

 44%|████▎     | 13164/30196 [27:25<26:37, 10.66it/s]

 44%|████▎     | 13166/30196 [27:25<33:40,  8.43it/s]

 44%|████▎     | 13167/30196 [27:25<34:17,  8.28it/s]

 44%|████▎     | 13168/30196 [27:25<37:21,  7.60it/s]

 44%|████▎     | 13169/30196 [27:25<35:38,  7.96it/s]

 44%|████▎     | 13171/30196 [27:26<30:34,  9.28it/s]

 44%|████▎     | 13172/30196 [27:26<32:14,  8.80it/s]

 44%|████▎     | 13173/30196 [27:26<34:26,  8.24it/s]

 44%|████▎     | 13174/30196 [27:26<35:05,  8.09it/s]

 44%|████▎     | 13175/30196 [27:26<35:58,  7.89it/s]

 44%|████▎     | 13176/30196 [27:26<38:59,  7.27it/s]

 44%|████▎     | 13177/30196 [27:26<39:48,  7.12it/s]

 44%|████▎     | 13179/30196 [27:27<31:27,  9.02it/s]

 44%|████▎     | 13181/30196 [27:27<29:03,  9.76it/s]

 44%|████▎     | 13183/30196 [27:27<29:24,  9.64it/s]

 44%|████▎     | 13185/30196 [27:27<24:58, 11.35it/s]

 44%|████▎     | 13187/30196 [27:27<29:17,  9.68it/s]

 44%|████▎     | 13189/30196 [27:28<28:09, 10.07it/s]

 44%|████▎     | 13191/30196 [27:28<28:02, 10.10it/s]

 44%|████▎     | 13193/30196 [27:28<31:04,  9.12it/s]

 44%|████▎     | 13195/30196 [27:28<30:01,  9.44it/s]

 44%|████▎     | 13197/30196 [27:28<27:11, 10.42it/s]

 44%|████▎     | 13199/30196 [27:29<30:00,  9.44it/s]

 44%|████▎     | 13201/30196 [27:29<38:41,  7.32it/s]

 44%|████▎     | 13202/30196 [27:29<38:21,  7.38it/s]

 44%|████▎     | 13204/30196 [27:29<36:34,  7.74it/s]

 44%|████▎     | 13205/30196 [27:30<37:16,  7.60it/s]

 44%|████▎     | 13207/30196 [27:30<31:12,  9.07it/s]

 44%|████▎     | 13208/30196 [27:30<32:17,  8.77it/s]

 44%|████▎     | 13209/30196 [27:30<33:38,  8.41it/s]

 44%|████▍     | 13211/30196 [27:30<37:10,  7.61it/s]

 44%|████▍     | 13212/30196 [27:30<35:40,  7.93it/s]

 44%|████▍     | 13213/30196 [27:31<36:12,  7.82it/s]

 44%|████▍     | 13214/30196 [27:31<38:59,  7.26it/s]

 44%|████▍     | 13215/30196 [27:31<39:42,  7.13it/s]

 44%|████▍     | 13217/30196 [27:31<34:19,  8.25it/s]

 44%|████▍     | 13219/30196 [27:31<32:04,  8.82it/s]

 44%|████▍     | 13221/30196 [27:31<30:34,  9.25it/s]

 44%|████▍     | 13222/30196 [27:32<34:25,  8.22it/s]

 44%|████▍     | 13223/30196 [27:32<35:57,  7.87it/s]

 44%|████▍     | 13224/30196 [27:32<36:10,  7.82it/s]

 44%|████▍     | 13225/30196 [27:32<1:03:07,  4.48it/s]

 44%|████▍     | 13226/30196 [27:33<59:05,  4.79it/s]

 44%|████▍     | 13228/30196 [27:33<48:43,  5.80it/s]

 44%|████▍     | 13229/30196 [27:33<44:09,  6.40it/s]

 44%|████▍     | 13231/30196 [27:33<37:21,  7.57it/s]

 44%|████▍     | 13233/30196 [27:33<33:26,  8.45it/s]

 44%|████▍     | 13234/30196 [27:33<36:24,  7.77it/s]

 44%|████▍     | 13235/30196 [27:34<37:37,  7.51it/s]

 44%|████▍     | 13237/30196 [27:34<35:50,  7.89it/s]

 44%|████▍     | 13239/30196 [27:34<31:00,  9.11it/s]

 44%|████▍     | 13240/30196 [27:34<34:17,  8.24it/s]

 44%|████▍     | 13242/30196 [27:34<29:22,  9.62it/s]

 44%|████▍     | 13244/30196 [27:34<24:38, 11.46it/s]

 44%|████▍     | 13246/30196 [27:35<25:07, 11.25it/s]

 44%|████▍     | 13248/30196 [27:35<24:08, 11.70it/s]

 44%|████▍     | 13250/30196 [27:35<28:10, 10.03it/s]

 44%|████▍     | 13252/30196 [27:35<31:14,  9.04it/s]

 44%|████▍     | 13254/30196 [27:36<31:30,  8.96it/s]

 44%|████▍     | 13255/30196 [27:36<32:29,  8.69it/s]

 44%|████▍     | 13256/30196 [27:36<34:08,  8.27it/s]

 44%|████▍     | 13258/30196 [27:36<30:41,  9.20it/s]

 44%|████▍     | 13260/30196 [27:36<28:40,  9.84it/s]

 44%|████▍     | 13262/30196 [27:36<26:03, 10.83it/s]

 44%|████▍     | 13264/30196 [27:37<33:36,  8.39it/s]

 44%|████▍     | 13265/30196 [27:37<34:14,  8.24it/s]

 44%|████▍     | 13266/30196 [27:37<34:38,  8.15it/s]

 44%|████▍     | 13267/30196 [27:37<45:09,  6.25it/s]

 44%|████▍     | 13270/30196 [27:37<28:33,  9.88it/s]

 44%|████▍     | 13272/30196 [27:38<28:05, 10.04it/s]

 44%|████▍     | 13274/30196 [27:38<33:56,  8.31it/s]

 44%|████▍     | 13275/30196 [27:38<34:43,  8.12it/s]

 44%|████▍     | 13277/30196 [27:38<31:30,  8.95it/s]

 44%|████▍     | 13278/30196 [27:38<31:09,  9.05it/s]

 44%|████▍     | 13280/30196 [27:38<32:01,  8.80it/s]

 44%|████▍     | 13281/30196 [27:39<35:49,  7.87it/s]

 44%|████▍     | 13282/30196 [27:39<36:00,  7.83it/s]

 44%|████▍     | 13283/30196 [27:39<34:24,  8.19it/s]

 44%|████▍     | 13284/30196 [27:39<38:30,  7.32it/s]

 44%|████▍     | 13286/30196 [27:39<32:46,  8.60it/s]

 44%|████▍     | 13288/30196 [27:40<34:09,  8.25it/s]

 44%|████▍     | 13289/30196 [27:40<35:40,  7.90it/s]

 44%|████▍     | 13291/30196 [27:40<29:46,  9.46it/s]

 44%|████▍     | 13292/30196 [27:40<33:25,  8.43it/s]

 44%|████▍     | 13293/30196 [27:40<35:02,  8.04it/s]

 44%|████▍     | 13294/30196 [27:40<38:28,  7.32it/s]

 44%|████▍     | 13296/30196 [27:40<32:51,  8.57it/s]

 44%|████▍     | 13297/30196 [27:41<49:22,  5.70it/s]

 44%|████▍     | 13299/30196 [27:41<35:47,  7.87it/s]

 44%|████▍     | 13301/30196 [27:41<29:46,  9.46it/s]

 44%|████▍     | 13303/30196 [27:41<32:59,  8.54it/s]

 44%|████▍     | 13305/30196 [27:42<34:38,  8.13it/s]

 44%|████▍     | 13307/30196 [27:42<31:56,  8.81it/s]

 44%|████▍     | 13308/30196 [27:42<39:34,  7.11it/s]

 44%|████▍     | 13310/30196 [27:42<35:11,  8.00it/s]

 44%|████▍     | 13311/30196 [27:42<34:18,  8.20it/s]

 44%|████▍     | 13312/30196 [27:43<37:34,  7.49it/s]

 44%|████▍     | 13314/30196 [27:43<31:03,  9.06it/s]

 44%|████▍     | 13315/30196 [27:43<30:43,  9.16it/s]

 44%|████▍     | 13317/30196 [27:43<29:48,  9.44it/s]

 44%|████▍     | 13318/30196 [27:43<31:28,  8.94it/s]

 44%|████▍     | 13320/30196 [27:43<35:46,  7.86it/s]

 44%|████▍     | 13322/30196 [27:44<32:05,  8.77it/s]

 44%|████▍     | 13325/30196 [27:44<27:14, 10.32it/s]

 44%|████▍     | 13327/30196 [27:44<27:33, 10.20it/s]

 44%|████▍     | 13329/30196 [27:44<29:44,  9.45it/s]

 44%|████▍     | 13330/30196 [27:44<29:41,  9.47it/s]

 44%|████▍     | 13331/30196 [27:45<29:37,  9.49it/s]

 44%|████▍     | 13332/30196 [27:45<33:34,  8.37it/s]

 44%|████▍     | 13334/30196 [27:45<36:34,  7.68it/s]

 44%|████▍     | 13336/30196 [27:45<34:56,  8.04it/s]

 44%|████▍     | 13337/30196 [27:45<37:16,  7.54it/s]

 44%|████▍     | 13338/30196 [27:46<39:51,  7.05it/s]

 44%|████▍     | 13339/30196 [27:46<39:21,  7.14it/s]

 44%|████▍     | 13340/30196 [27:46<37:06,  7.57it/s]

 44%|████▍     | 13341/30196 [27:46<37:46,  7.44it/s]

 44%|████▍     | 13342/30196 [27:46<38:44,  7.25it/s]

 44%|████▍     | 13344/30196 [27:46<38:01,  7.39it/s]

 44%|████▍     | 13346/30196 [27:47<32:53,  8.54it/s]

 44%|████▍     | 13348/30196 [27:47<26:30, 10.59it/s]

 44%|████▍     | 13350/30196 [27:47<24:35, 11.42it/s]

 44%|████▍     | 13352/30196 [27:47<27:22, 10.25it/s]

 44%|████▍     | 13354/30196 [27:47<25:25, 11.04it/s]

 44%|████▍     | 13356/30196 [27:48<45:44,  6.14it/s]

 44%|████▍     | 13358/30196 [27:48<40:53,  6.86it/s]

 44%|████▍     | 13359/30196 [27:48<40:18,  6.96it/s]

 44%|████▍     | 13361/30196 [27:48<35:03,  8.00it/s]

 44%|████▍     | 13362/30196 [27:48<34:13,  8.20it/s]

 44%|████▍     | 13364/30196 [27:49<36:11,  7.75it/s]

 44%|████▍     | 13365/30196 [27:49<40:56,  6.85it/s]

 44%|████▍     | 13366/30196 [27:49<40:01,  7.01it/s]

 44%|████▍     | 13367/30196 [27:49<39:08,  7.17it/s]

 44%|████▍     | 13368/30196 [27:49<39:12,  7.15it/s]

 44%|████▍     | 13370/30196 [27:49<30:19,  9.25it/s]

 44%|████▍     | 13371/30196 [27:50<43:03,  6.51it/s]

 44%|████▍     | 13372/30196 [27:50<42:24,  6.61it/s]

 44%|████▍     | 13374/30196 [27:50<39:28,  7.10it/s]

 44%|████▍     | 13375/30196 [27:50<38:53,  7.21it/s]

 44%|████▍     | 13376/30196 [27:50<40:42,  6.89it/s]

 44%|████▍     | 13378/30196 [27:51<49:44,  5.64it/s]

 44%|████▍     | 13379/30196 [27:51<46:53,  5.98it/s]

 44%|████▍     | 13380/30196 [27:52<1:09:47,  4.02it/s]

 44%|████▍     | 13382/30196 [27:52<49:46,  5.63it/s]

 44%|████▍     | 13383/30196 [27:52<54:59,  5.10it/s]

 44%|████▍     | 13385/30196 [27:52<45:26,  6.17it/s]

 44%|████▍     | 13386/30196 [27:52<45:55,  6.10it/s]

 44%|████▍     | 13388/30196 [27:53<37:48,  7.41it/s]

 44%|████▍     | 13389/30196 [27:53<35:58,  7.79it/s]

 44%|████▍     | 13390/30196 [27:53<42:34,  6.58it/s]

 44%|████▍     | 13391/30196 [27:53<39:35,  7.08it/s]

 44%|████▍     | 13393/30196 [27:53<35:32,  7.88it/s]

 44%|████▍     | 13394/30196 [27:53<38:45,  7.23it/s]

 44%|████▍     | 13395/30196 [27:53<38:57,  7.19it/s]

 44%|████▍     | 13396/30196 [27:54<38:18,  7.31it/s]

 44%|████▍     | 13398/30196 [27:54<29:32,  9.47it/s]

 44%|████▍     | 13399/30196 [27:54<34:27,  8.12it/s]

 44%|████▍     | 13400/30196 [27:54<38:07,  7.34it/s]

 44%|████▍     | 13401/30196 [27:54<38:41,  7.23it/s]

 44%|████▍     | 13403/30196 [27:54<36:37,  7.64it/s]

 44%|████▍     | 13405/30196 [27:55<31:35,  8.86it/s]

 44%|████▍     | 13407/30196 [27:55<28:34,  9.79it/s]

 44%|████▍     | 13409/30196 [27:55<28:42,  9.74it/s]

 44%|████▍     | 13410/30196 [27:56<1:07:54,  4.12it/s]

 44%|████▍     | 13412/30196 [27:56<50:16,  5.56it/s]

 44%|████▍     | 13414/30196 [27:56<39:42,  7.04it/s]

 44%|████▍     | 13416/30196 [27:56<39:32,  7.07it/s]

 44%|████▍     | 13417/30196 [27:57<56:54,  4.91it/s]

 44%|████▍     | 13419/30196 [27:57<43:59,  6.35it/s]

 44%|████▍     | 13420/30196 [27:57<44:30,  6.28it/s]

 44%|████▍     | 13422/30196 [27:57<38:50,  7.20it/s]

 44%|████▍     | 13424/30196 [27:58<33:26,  8.36it/s]

 44%|████▍     | 13426/30196 [27:58<30:03,  9.30it/s]

 44%|████▍     | 13428/30196 [27:58<28:24,  9.84it/s]

 44%|████▍     | 13430/30196 [27:58<27:03, 10.33it/s]

 44%|████▍     | 13432/30196 [27:58<29:50,  9.36it/s]

 44%|████▍     | 13434/30196 [27:58<27:43, 10.07it/s]

 44%|████▍     | 13436/30196 [27:59<25:40, 10.88it/s]

 45%|████▍     | 13438/30196 [27:59<28:30,  9.80it/s]

 45%|████▍     | 13440/30196 [27:59<27:52, 10.02it/s]

 45%|████▍     | 13442/30196 [27:59<25:39, 10.88it/s]

 45%|████▍     | 13444/30196 [27:59<28:33,  9.78it/s]

 45%|████▍     | 13446/30196 [28:00<29:25,  9.49it/s]

 45%|████▍     | 13447/30196 [28:00<30:52,  9.04it/s]

 45%|████▍     | 13448/30196 [28:00<33:55,  8.23it/s]

 45%|████▍     | 13449/30196 [28:00<34:30,  8.09it/s]

 45%|████▍     | 13450/30196 [28:00<33:36,  8.31it/s]

 45%|████▍     | 13451/30196 [28:00<37:30,  7.44it/s]

 45%|████▍     | 13452/30196 [28:01<37:17,  7.48it/s]

 45%|████▍     | 13454/30196 [28:01<27:21, 10.20it/s]

 45%|████▍     | 13456/30196 [28:01<28:36,  9.75it/s]

 45%|████▍     | 13458/30196 [28:01<29:03,  9.60it/s]

 45%|████▍     | 13460/30196 [28:01<30:33,  9.13it/s]

 45%|████▍     | 13461/30196 [28:01<30:30,  9.14it/s]

 45%|████▍     | 13462/30196 [28:02<39:41,  7.03it/s]

 45%|████▍     | 13463/30196 [28:02<37:34,  7.42it/s]

 45%|████▍     | 13464/30196 [28:02<38:02,  7.33it/s]

 45%|████▍     | 13465/30196 [28:02<40:14,  6.93it/s]

 45%|████▍     | 13466/30196 [28:02<39:08,  7.12it/s]

 45%|████▍     | 13467/30196 [28:02<41:40,  6.69it/s]

 45%|████▍     | 13469/30196 [28:03<29:44,  9.37it/s]

 45%|████▍     | 13471/30196 [28:03<28:06,  9.92it/s]

 45%|████▍     | 13474/30196 [28:03<21:03, 13.24it/s]

 45%|████▍     | 13476/30196 [28:03<22:47, 12.22it/s]

 45%|████▍     | 13478/30196 [28:03<29:38,  9.40it/s]

 45%|████▍     | 13480/30196 [28:04<29:11,  9.55it/s]

 45%|████▍     | 13482/30196 [28:04<32:47,  8.49it/s]

 45%|████▍     | 13483/30196 [28:04<33:31,  8.31it/s]

 45%|████▍     | 13484/30196 [28:04<38:26,  7.24it/s]

 45%|████▍     | 13486/30196 [28:04<31:08,  8.94it/s]

 45%|████▍     | 13488/30196 [28:05<29:20,  9.49it/s]

 45%|████▍     | 13490/30196 [28:05<28:13,  9.87it/s]

 45%|████▍     | 13492/30196 [28:05<32:41,  8.52it/s]

 45%|████▍     | 13493/30196 [28:05<33:32,  8.30it/s]

 45%|████▍     | 13494/30196 [28:05<36:44,  7.58it/s]

 45%|████▍     | 13495/30196 [28:05<36:36,  7.61it/s]

 45%|████▍     | 13497/30196 [28:06<29:34,  9.41it/s]

 45%|████▍     | 13498/30196 [28:06<38:20,  7.26it/s]

 45%|████▍     | 13499/30196 [28:06<40:23,  6.89it/s]

 45%|████▍     | 13501/30196 [28:06<34:00,  8.18it/s]

 45%|████▍     | 13502/30196 [28:06<32:56,  8.45it/s]

 45%|████▍     | 13504/30196 [28:06<26:19, 10.57it/s]

 45%|████▍     | 13506/30196 [28:07<28:23,  9.80it/s]

 45%|████▍     | 13508/30196 [28:07<29:19,  9.48it/s]

 45%|████▍     | 13510/30196 [28:07<26:43, 10.41it/s]

 45%|████▍     | 13512/30196 [28:08<1:01:16,  4.54it/s]

 45%|████▍     | 13513/30196 [28:08<58:30,  4.75it/s]

 45%|████▍     | 13514/30196 [28:08<56:14,  4.94it/s]

 45%|████▍     | 13515/30196 [28:09<1:08:16,  4.07it/s]

 45%|████▍     | 13516/30196 [28:09<1:00:40,  4.58it/s]

 45%|████▍     | 13519/30196 [28:09<40:05,  6.93it/s]

 45%|████▍     | 13521/30196 [28:09<32:12,  8.63it/s]

 45%|████▍     | 13523/30196 [28:09<29:12,  9.51it/s]

 45%|████▍     | 13525/30196 [28:10<26:41, 10.41it/s]

 45%|████▍     | 13527/30196 [28:10<31:05,  8.94it/s]

 45%|████▍     | 13529/30196 [28:10<31:03,  8.94it/s]

 45%|████▍     | 13531/30196 [28:10<34:03,  8.15it/s]

 45%|████▍     | 13533/30196 [28:10<30:37,  9.07it/s]

 45%|████▍     | 13535/30196 [28:11<36:24,  7.63it/s]

 45%|████▍     | 13537/30196 [28:11<31:50,  8.72it/s]

 45%|████▍     | 13539/30196 [28:11<27:34, 10.07it/s]

 45%|████▍     | 13541/30196 [28:11<30:20,  9.15it/s]

 45%|████▍     | 13543/30196 [28:12<35:39,  7.79it/s]

 45%|████▍     | 13545/30196 [28:12<33:54,  8.19it/s]

 45%|████▍     | 13546/30196 [28:12<33:02,  8.40it/s]

 45%|████▍     | 13548/30196 [28:12<28:09,  9.85it/s]

 45%|████▍     | 13550/30196 [28:12<25:57, 10.69it/s]

 45%|████▍     | 13552/30196 [28:13<32:04,  8.65it/s]

 45%|████▍     | 13553/30196 [28:13<31:27,  8.82it/s]

 45%|████▍     | 13555/30196 [28:13<26:14, 10.57it/s]

 45%|████▍     | 13557/30196 [28:13<26:03, 10.64it/s]

 45%|████▍     | 13559/30196 [28:13<23:53, 11.61it/s]

 45%|████▍     | 13561/30196 [28:13<28:08,  9.85it/s]

 45%|████▍     | 13563/30196 [28:14<32:49,  8.44it/s]

 45%|████▍     | 13564/30196 [28:14<32:24,  8.56it/s]

 45%|████▍     | 13566/30196 [28:14<31:30,  8.80it/s]

 45%|████▍     | 13568/30196 [28:14<31:08,  8.90it/s]

 45%|████▍     | 13569/30196 [28:15<33:55,  8.17it/s]

 45%|████▍     | 13570/30196 [28:15<35:20,  7.84it/s]

 45%|████▍     | 13572/30196 [28:15<33:21,  8.31it/s]

 45%|████▍     | 13573/30196 [28:15<34:30,  8.03it/s]

 45%|████▍     | 13574/30196 [28:15<36:00,  7.69it/s]

 45%|████▍     | 13576/30196 [28:15<31:29,  8.80it/s]

 45%|████▍     | 13577/30196 [28:15<31:15,  8.86it/s]

 45%|████▍     | 13578/30196 [28:16<31:01,  8.93it/s]

 45%|████▍     | 13580/30196 [28:16<24:38, 11.24it/s]

 45%|████▍     | 13582/30196 [28:16<29:35,  9.36it/s]

 45%|████▍     | 13584/30196 [28:16<30:18,  9.13it/s]

 45%|████▍     | 13586/30196 [28:16<29:26,  9.40it/s]

 45%|████▍     | 13587/30196 [28:17<32:36,  8.49it/s]

 45%|████▌     | 13589/30196 [28:17<33:39,  8.22it/s]

 45%|████▌     | 13590/30196 [28:17<32:41,  8.47it/s]

 45%|████▌     | 13592/30196 [28:17<27:26, 10.08it/s]

 45%|████▌     | 13594/30196 [28:17<32:26,  8.53it/s]

 45%|████▌     | 13595/30196 [28:17<32:03,  8.63it/s]

 45%|████▌     | 13597/30196 [28:18<25:38, 10.79it/s]

 45%|████▌     | 13599/30196 [28:18<23:54, 11.57it/s]

 45%|████▌     | 13601/30196 [28:18<26:12, 10.55it/s]

 45%|████▌     | 13603/30196 [28:18<24:18, 11.38it/s]

 45%|████▌     | 13605/30196 [28:18<27:08, 10.19it/s]

 45%|████▌     | 13607/30196 [28:19<27:05, 10.21it/s]

 45%|████▌     | 13609/30196 [28:19<31:27,  8.79it/s]

 45%|████▌     | 13610/30196 [28:19<32:28,  8.51it/s]

 45%|████▌     | 13611/30196 [28:19<33:12,  8.32it/s]

 45%|████▌     | 13612/30196 [28:19<43:28,  6.36it/s]

 45%|████▌     | 13614/30196 [28:20<36:02,  7.67it/s]

 45%|████▌     | 13615/30196 [28:20<34:27,  8.02it/s]

 45%|████▌     | 13616/30196 [28:20<34:49,  7.93it/s]

 45%|████▌     | 13618/30196 [28:20<34:53,  7.92it/s]

 45%|████▌     | 13619/30196 [28:20<33:32,  8.24it/s]

 45%|████▌     | 13620/30196 [28:20<36:42,  7.53it/s]

 45%|████▌     | 13621/30196 [28:20<36:50,  7.50it/s]

 45%|████▌     | 13622/30196 [28:21<37:22,  7.39it/s]

 45%|████▌     | 13623/30196 [28:21<37:38,  7.34it/s]

 45%|████▌     | 13625/30196 [28:21<33:00,  8.37it/s]

 45%|████▌     | 13626/30196 [28:21<38:59,  7.08it/s]

 45%|████▌     | 13628/30196 [28:21<35:38,  7.75it/s]

 45%|████▌     | 13629/30196 [28:22<49:52,  5.54it/s]

 45%|████▌     | 13630/30196 [28:22<48:57,  5.64it/s]

 45%|████▌     | 13632/30196 [28:22<42:50,  6.44it/s]

 45%|████▌     | 13634/30196 [28:22<32:53,  8.39it/s]

 45%|████▌     | 13635/30196 [28:22<39:11,  7.04it/s]

 45%|████▌     | 13637/30196 [28:23<36:53,  7.48it/s]

 45%|████▌     | 13639/30196 [28:23<31:06,  8.87it/s]

 45%|████▌     | 13640/30196 [28:23<32:11,  8.57it/s]

 45%|████▌     | 13641/30196 [28:23<33:42,  8.19it/s]

 45%|████▌     | 13643/30196 [28:23<26:12, 10.53it/s]

 45%|████▌     | 13645/30196 [28:23<24:30, 11.25it/s]

 45%|████▌     | 13647/30196 [28:24<32:10,  8.57it/s]

 45%|████▌     | 13649/30196 [28:24<34:06,  8.08it/s]

 45%|████▌     | 13651/30196 [28:24<28:26,  9.70it/s]

 45%|████▌     | 13653/30196 [28:24<29:03,  9.49it/s]

 45%|████▌     | 13655/30196 [28:25<30:14,  9.12it/s]

 45%|████▌     | 13657/30196 [28:25<28:33,  9.65it/s]

 45%|████▌     | 13659/30196 [28:25<29:12,  9.43it/s]

 45%|████▌     | 13661/30196 [28:25<27:14, 10.11it/s]

 45%|████▌     | 13663/30196 [28:26<38:26,  7.17it/s]

 45%|████▌     | 13664/30196 [28:26<38:01,  7.25it/s]

 45%|████▌     | 13665/30196 [28:26<37:52,  7.28it/s]

 45%|████▌     | 13666/30196 [28:26<42:13,  6.52it/s]

 45%|████▌     | 13667/30196 [28:26<48:39,  5.66it/s]

 45%|████▌     | 13668/30196 [28:26<46:37,  5.91it/s]

 45%|████▌     | 13669/30196 [28:27<43:47,  6.29it/s]

 45%|████▌     | 13670/30196 [28:27<51:01,  5.40it/s]

 45%|████▌     | 13671/30196 [28:27<46:45,  5.89it/s]

 45%|████▌     | 13672/30196 [28:27<44:56,  6.13it/s]

 45%|████▌     | 13673/30196 [28:27<42:24,  6.49it/s]

 45%|████▌     | 13674/30196 [28:27<43:19,  6.35it/s]

 45%|████▌     | 13675/30196 [28:28<39:03,  7.05it/s]

 45%|████▌     | 13677/30196 [28:28<32:48,  8.39it/s]

 45%|████▌     | 13678/30196 [28:28<31:52,  8.64it/s]

 45%|████▌     | 13680/30196 [28:28<25:33, 10.77it/s]

 45%|████▌     | 13682/30196 [28:28<28:54,  9.52it/s]

 45%|████▌     | 13684/30196 [28:28<30:13,  9.11it/s]

 45%|████▌     | 13686/30196 [28:29<28:02,  9.81it/s]

 45%|████▌     | 13688/30196 [28:29<27:34,  9.98it/s]

 45%|████▌     | 13690/30196 [28:29<29:44,  9.25it/s]

 45%|████▌     | 13692/30196 [28:29<29:05,  9.45it/s]

 45%|████▌     | 13693/30196 [28:29<30:33,  9.00it/s]

 45%|████▌     | 13694/30196 [28:29<30:10,  9.11it/s]

 45%|████▌     | 13695/30196 [28:30<30:13,  9.10it/s]

 45%|████▌     | 13697/30196 [28:30<27:11, 10.11it/s]

 45%|████▌     | 13699/30196 [28:30<25:16, 10.88it/s]

 45%|████▌     | 13701/30196 [28:30<22:06, 12.44it/s]

 45%|████▌     | 13703/30196 [28:30<23:33, 11.67it/s]

 45%|████▌     | 13705/30196 [28:31<33:23,  8.23it/s]

 45%|████▌     | 13706/30196 [28:31<33:50,  8.12it/s]

 45%|████▌     | 13707/30196 [28:31<36:46,  7.47it/s]

 45%|████▌     | 13709/30196 [28:31<31:29,  8.73it/s]

 45%|████▌     | 13710/30196 [28:31<30:54,  8.89it/s]

 45%|████▌     | 13711/30196 [28:31<32:20,  8.50it/s]

 45%|████▌     | 13712/30196 [28:32<38:23,  7.16it/s]

 45%|████▌     | 13713/30196 [28:32<35:55,  7.65it/s]

 45%|████▌     | 13714/30196 [28:32<34:18,  8.01it/s]

 45%|████▌     | 13716/30196 [28:32<32:31,  8.45it/s]

 45%|████▌     | 13718/30196 [28:32<37:54,  7.24it/s]

 45%|████▌     | 13719/30196 [28:32<35:56,  7.64it/s]

 45%|████▌     | 13721/30196 [28:33<33:01,  8.31it/s]

 45%|████▌     | 13722/30196 [28:33<33:52,  8.10it/s]

 45%|████▌     | 13724/30196 [28:33<38:42,  7.09it/s]

 45%|████▌     | 13725/30196 [28:33<40:12,  6.83it/s]

 45%|████▌     | 13726/30196 [28:34<47:37,  5.76it/s]

 45%|████▌     | 13727/30196 [28:34<44:40,  6.14it/s]

 45%|████▌     | 13728/30196 [28:34<44:51,  6.12it/s]

 45%|████▌     | 13730/30196 [28:34<43:17,  6.34it/s]

 45%|████▌     | 13731/30196 [28:34<40:12,  6.83it/s]

 45%|████▌     | 13732/30196 [28:34<40:14,  6.82it/s]

 45%|████▌     | 13734/30196 [28:34<29:24,  9.33it/s]

 45%|████▌     | 13736/30196 [28:35<47:34,  5.77it/s]

 45%|████▌     | 13738/30196 [28:35<43:39,  6.28it/s]

 45%|████▌     | 13739/30196 [28:35<42:58,  6.38it/s]

 46%|████▌     | 13741/30196 [28:36<38:27,  7.13it/s]

 46%|████▌     | 13743/30196 [28:36<34:01,  8.06it/s]

 46%|████▌     | 13744/30196 [28:36<32:58,  8.32it/s]

 46%|████▌     | 13746/30196 [28:36<28:29,  9.62it/s]

 46%|████▌     | 13748/30196 [28:36<28:51,  9.50it/s]

 46%|████▌     | 13750/30196 [28:37<28:02,  9.77it/s]

 46%|████▌     | 13752/30196 [28:37<29:46,  9.20it/s]

 46%|████▌     | 13754/30196 [28:37<32:43,  8.38it/s]

 46%|████▌     | 13755/30196 [28:37<41:05,  6.67it/s]

 46%|████▌     | 13757/30196 [28:38<37:23,  7.33it/s]

 46%|████▌     | 13758/30196 [28:38<39:02,  7.02it/s]

 46%|████▌     | 13759/30196 [28:38<40:25,  6.78it/s]

 46%|████▌     | 13761/30196 [28:38<35:08,  7.79it/s]

 46%|████▌     | 13762/30196 [28:38<34:39,  7.90it/s]

 46%|████▌     | 13763/30196 [28:38<34:55,  7.84it/s]

 46%|████▌     | 13764/30196 [28:38<33:12,  8.25it/s]

 46%|████▌     | 13765/30196 [28:39<32:02,  8.55it/s]

 46%|████▌     | 13766/30196 [28:39<33:01,  8.29it/s]

 46%|████▌     | 13767/30196 [28:39<39:43,  6.89it/s]

 46%|████▌     | 13769/30196 [28:39<33:32,  8.16it/s]

 46%|████▌     | 13771/30196 [28:39<25:55, 10.56it/s]

 46%|████▌     | 13773/30196 [28:40<31:37,  8.66it/s]

 46%|████▌     | 13775/30196 [28:40<30:27,  8.99it/s]

 46%|████▌     | 13777/30196 [28:40<32:27,  8.43it/s]

 46%|████▌     | 13778/30196 [28:40<37:20,  7.33it/s]

 46%|████▌     | 13780/30196 [28:40<37:31,  7.29it/s]

 46%|████▌     | 13782/30196 [28:41<32:30,  8.41it/s]

 46%|████▌     | 13784/30196 [28:41<33:08,  8.26it/s]

 46%|████▌     | 13785/30196 [28:41<32:32,  8.40it/s]

 46%|████▌     | 13786/30196 [28:41<33:47,  8.09it/s]

 46%|████▌     | 13789/30196 [28:41<24:14, 11.28it/s]

 46%|████▌     | 13791/30196 [28:41<25:10, 10.86it/s]

 46%|████▌     | 13793/30196 [28:42<26:16, 10.40it/s]

 46%|████▌     | 13795/30196 [28:42<27:26,  9.96it/s]

 46%|████▌     | 13797/30196 [28:42<32:24,  8.43it/s]

 46%|████▌     | 13798/30196 [28:42<31:59,  8.54it/s]

 46%|████▌     | 13799/30196 [28:42<32:43,  8.35it/s]

 46%|████▌     | 13801/30196 [28:43<29:41,  9.20it/s]

 46%|████▌     | 13802/30196 [28:43<31:28,  8.68it/s]

 46%|████▌     | 13804/30196 [28:43<27:17, 10.01it/s]

 46%|████▌     | 13806/30196 [28:43<31:33,  8.66it/s]

 46%|████▌     | 13808/30196 [28:43<29:03,  9.40it/s]

 46%|████▌     | 13809/30196 [28:44<36:57,  7.39it/s]

 46%|████▌     | 13810/30196 [28:44<39:16,  6.95it/s]

 46%|████▌     | 13811/30196 [28:44<41:10,  6.63it/s]

 46%|████▌     | 13813/30196 [28:44<36:35,  7.46it/s]

 46%|████▌     | 13814/30196 [28:44<37:01,  7.37it/s]

 46%|████▌     | 13815/30196 [28:44<35:21,  7.72it/s]

 46%|████▌     | 13816/30196 [28:45<33:52,  8.06it/s]

 46%|████▌     | 13817/30196 [28:45<37:57,  7.19it/s]

 46%|████▌     | 13818/30196 [28:45<35:21,  7.72it/s]

 46%|████▌     | 13819/30196 [28:45<33:46,  8.08it/s]

 46%|████▌     | 13821/30196 [28:45<27:50,  9.80it/s]

 46%|████▌     | 13822/30196 [28:45<28:20,  9.63it/s]

 46%|████▌     | 13823/30196 [28:45<28:44,  9.49it/s]

 46%|████▌     | 13825/30196 [28:46<29:55,  9.12it/s]

 46%|████▌     | 13826/30196 [28:46<31:50,  8.57it/s]

 46%|████▌     | 13827/30196 [28:46<33:02,  8.26it/s]

 46%|████▌     | 13829/30196 [28:46<31:15,  8.73it/s]

 46%|████▌     | 13831/30196 [28:46<26:17, 10.38it/s]

 46%|████▌     | 13833/30196 [28:46<29:10,  9.35it/s]

 46%|████▌     | 13835/30196 [28:47<25:01, 10.90it/s]

 46%|████▌     | 13837/30196 [28:47<28:31,  9.56it/s]

 46%|████▌     | 13839/30196 [28:47<31:20,  8.70it/s]

 46%|████▌     | 13840/30196 [28:47<32:17,  8.44it/s]

 46%|████▌     | 13842/30196 [28:47<29:10,  9.34it/s]

 46%|████▌     | 13843/30196 [28:48<32:20,  8.43it/s]

 46%|████▌     | 13844/30196 [28:48<33:05,  8.24it/s]

 46%|████▌     | 13846/30196 [28:48<32:42,  8.33it/s]

 46%|████▌     | 13849/30196 [28:48<28:48,  9.46it/s]

 46%|████▌     | 13850/30196 [28:48<28:47,  9.46it/s]

 46%|████▌     | 13851/30196 [28:48<30:08,  9.04it/s]

 46%|████▌     | 13853/30196 [28:49<27:15,  9.99it/s]

 46%|████▌     | 13854/30196 [28:49<27:26,  9.93it/s]

 46%|████▌     | 13855/30196 [28:49<30:15,  9.00it/s]

 46%|████▌     | 13857/30196 [28:49<30:18,  8.99it/s]

 46%|████▌     | 13859/30196 [28:49<33:01,  8.24it/s]

 46%|████▌     | 13860/30196 [28:50<36:17,  7.50it/s]

 46%|████▌     | 13861/30196 [28:50<40:44,  6.68it/s]

 46%|████▌     | 13863/30196 [28:50<33:23,  8.15it/s]

 46%|████▌     | 13865/30196 [28:50<27:52,  9.77it/s]

 46%|████▌     | 13867/30196 [28:50<28:39,  9.50it/s]

 46%|████▌     | 13869/30196 [28:51<32:29,  8.38it/s]

 46%|████▌     | 13870/30196 [28:51<33:51,  8.03it/s]

 46%|████▌     | 13872/30196 [28:51<31:47,  8.56it/s]

 46%|████▌     | 13873/30196 [28:51<32:33,  8.36it/s]

 46%|████▌     | 13874/30196 [28:51<35:31,  7.66it/s]

 46%|████▌     | 13875/30196 [28:51<38:03,  7.15it/s]

 46%|████▌     | 13876/30196 [28:52<35:40,  7.62it/s]

 46%|████▌     | 13877/30196 [28:52<34:09,  7.96it/s]

 46%|████▌     | 13878/30196 [28:52<34:35,  7.86it/s]

 46%|████▌     | 13880/30196 [28:52<33:44,  8.06it/s]

 46%|████▌     | 13881/30196 [28:52<32:49,  8.29it/s]

 46%|████▌     | 13883/30196 [28:52<29:19,  9.27it/s]

 46%|████▌     | 13884/30196 [28:53<42:19,  6.42it/s]

 46%|████▌     | 13886/30196 [28:53<31:56,  8.51it/s]

 46%|████▌     | 13888/30196 [28:53<32:59,  8.24it/s]

 46%|████▌     | 13890/30196 [28:53<31:33,  8.61it/s]

 46%|████▌     | 13892/30196 [28:53<27:48,  9.77it/s]

 46%|████▌     | 13894/30196 [28:54<30:25,  8.93it/s]

 46%|████▌     | 13895/30196 [28:54<33:10,  8.19it/s]

 46%|████▌     | 13897/30196 [28:54<26:35, 10.22it/s]

 46%|████▌     | 13899/30196 [28:54<28:50,  9.42it/s]

 46%|████▌     | 13901/30196 [28:54<26:47, 10.14it/s]

 46%|████▌     | 13903/30196 [28:54<25:10, 10.79it/s]

 46%|████▌     | 13905/30196 [28:55<23:36, 11.50it/s]

 46%|████▌     | 13907/30196 [28:55<25:01, 10.85it/s]

 46%|████▌     | 13909/30196 [28:55<22:19, 12.16it/s]

 46%|████▌     | 13911/30196 [28:55<22:42, 11.95it/s]

 46%|████▌     | 13913/30196 [28:55<32:34,  8.33it/s]

 46%|████▌     | 13915/30196 [28:56<36:04,  7.52it/s]

 46%|████▌     | 13916/30196 [28:56<35:00,  7.75it/s]

 46%|████▌     | 13917/30196 [28:56<33:41,  8.05it/s]

 46%|████▌     | 13919/30196 [28:56<28:56,  9.38it/s]

 46%|████▌     | 13921/30196 [28:56<31:36,  8.58it/s]

 46%|████▌     | 13922/30196 [28:57<32:21,  8.38it/s]

 46%|████▌     | 13923/30196 [28:57<31:46,  8.54it/s]

 46%|████▌     | 13924/30196 [28:57<32:57,  8.23it/s]

 46%|████▌     | 13925/30196 [28:57<32:11,  8.42it/s]

 46%|████▌     | 13926/30196 [28:57<40:11,  6.75it/s]

 46%|████▌     | 13927/30196 [28:57<39:42,  6.83it/s]

 46%|████▌     | 13928/30196 [28:57<36:32,  7.42it/s]

 46%|████▌     | 13929/30196 [28:58<39:53,  6.80it/s]

 46%|████▌     | 13930/30196 [28:58<38:34,  7.03it/s]

 46%|████▌     | 13931/30196 [28:58<35:59,  7.53it/s]

 46%|████▌     | 13932/30196 [28:58<36:37,  7.40it/s]

 46%|████▌     | 13933/30196 [28:58<36:08,  7.50it/s]

 46%|████▌     | 13935/30196 [28:58<26:55, 10.07it/s]

 46%|████▌     | 13937/30196 [28:59<42:22,  6.39it/s]

 46%|████▌     | 13938/30196 [28:59<45:44,  5.92it/s]

 46%|████▌     | 13939/30196 [28:59<43:54,  6.17it/s]

 46%|████▌     | 13940/30196 [28:59<42:54,  6.31it/s]

 46%|████▌     | 13943/30196 [28:59<26:59, 10.04it/s]

 46%|████▌     | 13945/30196 [29:00<29:17,  9.25it/s]

 46%|████▌     | 13947/30196 [29:00<30:47,  8.80it/s]

 46%|████▌     | 13949/30196 [29:00<32:28,  8.34it/s]

 46%|████▌     | 13950/30196 [29:00<31:59,  8.46it/s]

 46%|████▌     | 13951/30196 [29:00<33:38,  8.05it/s]

 46%|████▌     | 13952/30196 [29:01<41:46,  6.48it/s]

 46%|████▌     | 13954/30196 [29:01<40:38,  6.66it/s]

 46%|████▌     | 13955/30196 [29:01<42:27,  6.38it/s]

 46%|████▌     | 13957/30196 [29:01<33:52,  7.99it/s]

 46%|████▌     | 13959/30196 [29:02<35:07,  7.70it/s]

 46%|████▌     | 13961/30196 [29:02<32:10,  8.41it/s]

 46%|████▌     | 13963/30196 [29:02<30:07,  8.98it/s]

 46%|████▌     | 13964/30196 [29:03<58:17,  4.64it/s]

 46%|████▌     | 13965/30196 [29:03<53:26,  5.06it/s]

 46%|████▋     | 13968/30196 [29:03<38:53,  6.95it/s]

 46%|████▋     | 13969/30196 [29:03<36:54,  7.33it/s]

 46%|████▋     | 13971/30196 [29:03<29:48,  9.07it/s]

 46%|████▋     | 13973/30196 [29:03<29:39,  9.12it/s]

 46%|████▋     | 13975/30196 [29:04<27:02, 10.00it/s]

 46%|████▋     | 13977/30196 [29:04<26:17, 10.28it/s]

 46%|████▋     | 13979/30196 [29:04<28:37,  9.44it/s]

 46%|████▋     | 13981/30196 [29:04<40:45,  6.63it/s]

 46%|████▋     | 13982/30196 [29:05<38:38,  6.99it/s]

 46%|████▋     | 13983/30196 [29:05<40:43,  6.64it/s]

 46%|████▋     | 13984/30196 [29:05<38:13,  7.07it/s]

 46%|████▋     | 13985/30196 [29:05<37:28,  7.21it/s]

 46%|████▋     | 13986/30196 [29:05<44:05,  6.13it/s]

 46%|████▋     | 13988/30196 [29:05<35:28,  7.62it/s]

 46%|████▋     | 13990/30196 [29:06<29:43,  9.08it/s]

 46%|████▋     | 13992/30196 [29:06<24:53, 10.85it/s]

 46%|████▋     | 13994/30196 [29:06<30:48,  8.76it/s]

 46%|████▋     | 13996/30196 [29:06<29:10,  9.26it/s]

 46%|████▋     | 13998/30196 [29:06<31:31,  8.57it/s]

 46%|████▋     | 13999/30196 [29:07<31:09,  8.67it/s]

 46%|████▋     | 14000/30196 [29:07<32:15,  8.37it/s]

 46%|████▋     | 14001/30196 [29:07<32:53,  8.20it/s]

 46%|████▋     | 14003/30196 [29:07<27:57,  9.65it/s]

 46%|████▋     | 14005/30196 [29:07<27:13,  9.91it/s]

 46%|████▋     | 14007/30196 [29:07<25:16, 10.68it/s]

 46%|████▋     | 14009/30196 [29:08<28:01,  9.62it/s]

 46%|████▋     | 14010/30196 [29:08<29:56,  9.01it/s]

 46%|████▋     | 14011/30196 [29:08<29:36,  9.11it/s]

 46%|████▋     | 14012/30196 [29:08<31:09,  8.66it/s]

 46%|████▋     | 14014/30196 [29:08<33:02,  8.16it/s]

 46%|████▋     | 14016/30196 [29:08<31:47,  8.48it/s]

 46%|████▋     | 14018/30196 [29:09<30:35,  8.81it/s]

 46%|████▋     | 14020/30196 [29:09<26:15, 10.27it/s]

 46%|████▋     | 14022/30196 [29:09<24:14, 11.12it/s]

 46%|████▋     | 14024/30196 [29:09<24:08, 11.16it/s]

 46%|████▋     | 14026/30196 [29:09<26:28, 10.18it/s]

 46%|████▋     | 14028/30196 [29:10<25:59, 10.37it/s]

 46%|████▋     | 14030/30196 [29:10<26:54, 10.01it/s]

 46%|████▋     | 14032/30196 [29:10<30:03,  8.96it/s]

 46%|████▋     | 14033/30196 [29:10<32:59,  8.16it/s]

 46%|████▋     | 14034/30196 [29:10<33:41,  8.00it/s]

 46%|████▋     | 14035/30196 [29:11<36:04,  7.47it/s]

 46%|████▋     | 14036/30196 [29:11<36:59,  7.28it/s]

 46%|████▋     | 14037/30196 [29:11<36:49,  7.31it/s]

 46%|████▋     | 14039/30196 [29:11<27:54,  9.65it/s]

 46%|████▋     | 14041/30196 [29:11<28:24,  9.48it/s]

 47%|████▋     | 14042/30196 [29:11<28:39,  9.40it/s]

 47%|████▋     | 14043/30196 [29:11<32:23,  8.31it/s]

 47%|████▋     | 14045/30196 [29:12<26:42, 10.08it/s]

 47%|████▋     | 14047/30196 [29:12<28:43,  9.37it/s]

 47%|████▋     | 14048/30196 [29:12<37:09,  7.24it/s]

 47%|████▋     | 14050/30196 [29:12<29:08,  9.23it/s]

 47%|████▋     | 14052/30196 [29:12<24:43, 10.88it/s]

 47%|████▋     | 14054/30196 [29:13<31:30,  8.54it/s]

 47%|████▋     | 14056/30196 [29:13<30:47,  8.74it/s]

 47%|████▋     | 14058/30196 [29:13<41:56,  6.41it/s]

 47%|████▋     | 14059/30196 [29:13<39:26,  6.82it/s]

 47%|████▋     | 14061/30196 [29:14<33:07,  8.12it/s]

 47%|████▋     | 14062/30196 [29:14<33:45,  7.96it/s]

 47%|████▋     | 14063/30196 [29:14<32:51,  8.18it/s]

 47%|████▋     | 14064/30196 [29:14<33:24,  8.05it/s]

 47%|████▋     | 14066/30196 [29:14<29:19,  9.17it/s]

 47%|████▋     | 14067/30196 [29:14<29:20,  9.16it/s]

 47%|████▋     | 14068/30196 [29:14<29:05,  9.24it/s]

 47%|████▋     | 14070/30196 [29:14<23:32, 11.42it/s]

 47%|████▋     | 14072/30196 [29:15<20:10, 13.32it/s]

 47%|████▋     | 14074/30196 [29:15<22:52, 11.75it/s]

 47%|████▋     | 14076/30196 [29:15<26:31, 10.13it/s]

 47%|████▋     | 14078/30196 [29:15<28:15,  9.51it/s]

 47%|████▋     | 14080/30196 [29:15<27:26,  9.79it/s]

 47%|████▋     | 14082/30196 [29:16<56:36,  4.74it/s]

 47%|████▋     | 14083/30196 [29:17<52:55,  5.07it/s]

 47%|████▋     | 14085/30196 [29:17<46:25,  5.78it/s]

 47%|████▋     | 14086/30196 [29:17<45:00,  5.97it/s]

 47%|████▋     | 14087/30196 [29:17<45:01,  5.96it/s]

 47%|████▋     | 14090/30196 [29:17<28:56,  9.27it/s]

 47%|████▋     | 14092/30196 [29:17<28:32,  9.40it/s]

 47%|████▋     | 14094/30196 [29:18<34:09,  7.85it/s]

 47%|████▋     | 14095/30196 [29:18<36:11,  7.41it/s]

 47%|████▋     | 14098/30196 [29:18<26:30, 10.12it/s]

 47%|████▋     | 14100/30196 [29:18<25:38, 10.47it/s]

 47%|████▋     | 14102/30196 [29:19<32:11,  8.33it/s]

 47%|████▋     | 14103/30196 [29:19<33:27,  8.02it/s]

 47%|████▋     | 14104/30196 [29:19<33:56,  7.90it/s]

 47%|████▋     | 14105/30196 [29:19<41:20,  6.49it/s]

 47%|████▋     | 14107/30196 [29:19<32:08,  8.34it/s]

 47%|████▋     | 14109/30196 [29:20<33:23,  8.03it/s]

 47%|████▋     | 14110/30196 [29:20<37:56,  7.07it/s]

 47%|████▋     | 14112/30196 [29:20<31:38,  8.47it/s]

 47%|████▋     | 14113/30196 [29:20<30:53,  8.68it/s]

 47%|████▋     | 14114/30196 [29:20<32:04,  8.36it/s]

 47%|████▋     | 14115/30196 [29:20<35:24,  7.57it/s]

 47%|████▋     | 14116/30196 [29:21<38:39,  6.93it/s]

 47%|████▋     | 14117/30196 [29:21<35:47,  7.49it/s]

 47%|████▋     | 14118/30196 [29:21<36:48,  7.28it/s]

 47%|████▋     | 14119/30196 [29:21<42:28,  6.31it/s]

 47%|████▋     | 14120/30196 [29:21<43:01,  6.23it/s]

 47%|████▋     | 14121/30196 [29:21<41:26,  6.47it/s]

 47%|████▋     | 14122/30196 [29:21<42:35,  6.29it/s]

 47%|████▋     | 14123/30196 [29:22<40:39,  6.59it/s]

 47%|████▋     | 14124/30196 [29:22<39:46,  6.74it/s]

 47%|████▋     | 14125/30196 [29:22<41:03,  6.52it/s]

 47%|████▋     | 14127/30196 [29:22<29:41,  9.02it/s]

 47%|████▋     | 14129/30196 [29:22<24:10, 11.07it/s]

 47%|████▋     | 14131/30196 [29:22<31:55,  8.39it/s]

 47%|████▋     | 14133/30196 [29:23<35:58,  7.44it/s]

 47%|████▋     | 14134/30196 [29:23<35:46,  7.48it/s]

 47%|████▋     | 14136/30196 [29:23<34:32,  7.75it/s]

 47%|████▋     | 14137/30196 [29:23<33:12,  8.06it/s]

 47%|████▋     | 14139/30196 [29:23<28:06,  9.52it/s]

 47%|████▋     | 14141/30196 [29:24<31:25,  8.52it/s]

 47%|████▋     | 14143/30196 [29:24<27:21,  9.78it/s]

 47%|████▋     | 14145/30196 [29:24<38:32,  6.94it/s]

 47%|████▋     | 14146/30196 [29:24<37:52,  7.06it/s]

 47%|████▋     | 14147/30196 [29:25<36:04,  7.41it/s]

 47%|████▋     | 14149/30196 [29:25<33:23,  8.01it/s]

 47%|████▋     | 14150/30196 [29:25<32:34,  8.21it/s]

 47%|████▋     | 14151/30196 [29:25<31:45,  8.42it/s]

 47%|████▋     | 14152/30196 [29:25<34:51,  7.67it/s]

 47%|████▋     | 14153/30196 [29:25<34:54,  7.66it/s]

 47%|████▋     | 14154/30196 [29:25<35:16,  7.58it/s]

 47%|████▋     | 14155/30196 [29:26<38:03,  7.03it/s]

 47%|████▋     | 14156/30196 [29:26<40:10,  6.66it/s]

 47%|████▋     | 14157/30196 [29:26<49:41,  5.38it/s]

 47%|████▋     | 14158/30196 [29:26<43:30,  6.14it/s]

 47%|████▋     | 14159/30196 [29:26<46:52,  5.70it/s]

 47%|████▋     | 14160/30196 [29:27<46:41,  5.72it/s]

 47%|████▋     | 14162/30196 [29:27<38:16,  6.98it/s]

 47%|████▋     | 14164/30196 [29:27<31:43,  8.42it/s]

 47%|████▋     | 14166/30196 [29:27<31:13,  8.56it/s]

 47%|████▋     | 14168/30196 [29:27<26:45,  9.99it/s]

 47%|████▋     | 14170/30196 [29:28<31:45,  8.41it/s]

 47%|████▋     | 14172/30196 [29:28<26:31, 10.07it/s]

 47%|████▋     | 14174/30196 [29:28<28:42,  9.30it/s]

 47%|████▋     | 14176/30196 [29:28<25:32, 10.46it/s]

 47%|████▋     | 14178/30196 [29:28<25:35, 10.43it/s]

 47%|████▋     | 14180/30196 [29:29<29:30,  9.05it/s]

 47%|████▋     | 14182/30196 [29:29<26:45,  9.98it/s]

 47%|████▋     | 14184/30196 [29:29<27:01,  9.87it/s]

 47%|████▋     | 14186/30196 [29:29<24:27, 10.91it/s]

 47%|████▋     | 14188/30196 [29:29<24:13, 11.01it/s]

 47%|████▋     | 14190/30196 [29:29<25:25, 10.49it/s]

 47%|████▋     | 14192/30196 [29:30<28:53,  9.23it/s]

 47%|████▋     | 14193/30196 [29:30<32:09,  8.29it/s]

 47%|████▋     | 14195/30196 [29:30<28:39,  9.31it/s]

 47%|████▋     | 14196/30196 [29:30<30:04,  8.86it/s]

 47%|████▋     | 14197/30196 [29:30<31:43,  8.41it/s]

 47%|████▋     | 14199/30196 [29:30<28:03,  9.50it/s]

 47%|████▋     | 14200/30196 [29:31<30:07,  8.85it/s]

 47%|████▋     | 14201/30196 [29:31<31:10,  8.55it/s]

 47%|████▋     | 14203/30196 [29:31<31:43,  8.40it/s]

 47%|████▋     | 14204/30196 [29:31<42:39,  6.25it/s]

 47%|████▋     | 14205/30196 [29:31<43:47,  6.09it/s]

 47%|████▋     | 14206/30196 [29:32<40:00,  6.66it/s]

 47%|████▋     | 14208/30196 [29:32<31:32,  8.45it/s]

 47%|████▋     | 14210/30196 [29:32<29:20,  9.08it/s]

 47%|████▋     | 14211/30196 [29:32<32:54,  8.09it/s]

 47%|████▋     | 14213/30196 [29:32<33:07,  8.04it/s]

 47%|████▋     | 14215/30196 [29:33<31:35,  8.43it/s]

 47%|████▋     | 14216/30196 [29:33<34:09,  7.80it/s]

 47%|████▋     | 14217/30196 [29:33<34:19,  7.76it/s]

 47%|████▋     | 14219/30196 [29:33<50:52,  5.23it/s]

 47%|████▋     | 14221/30196 [29:34<43:23,  6.14it/s]

 47%|████▋     | 14223/30196 [29:34<36:46,  7.24it/s]

 47%|████▋     | 14225/30196 [29:34<33:46,  7.88it/s]

 47%|████▋     | 14227/30196 [29:34<30:41,  8.67it/s]

 47%|████▋     | 14229/30196 [29:34<26:13, 10.15it/s]

 47%|████▋     | 14231/30196 [29:35<26:26, 10.06it/s]

 47%|████▋     | 14233/30196 [29:35<28:30,  9.33it/s]

 47%|████▋     | 14235/30196 [29:35<27:09,  9.79it/s]

 47%|████▋     | 14237/30196 [29:35<30:26,  8.74it/s]

 47%|████▋     | 14238/30196 [29:35<31:43,  8.38it/s]

 47%|████▋     | 14240/30196 [29:36<27:33,  9.65it/s]

 47%|████▋     | 14242/30196 [29:36<28:16,  9.41it/s]

 47%|████▋     | 14244/30196 [29:36<27:57,  9.51it/s]

 47%|████▋     | 14245/30196 [29:36<29:23,  9.04it/s]

 47%|████▋     | 14247/30196 [29:36<26:46,  9.93it/s]

 47%|████▋     | 14249/30196 [29:36<25:50, 10.29it/s]

 47%|████▋     | 14251/30196 [29:37<40:45,  6.52it/s]

 47%|████▋     | 14252/30196 [29:37<38:22,  6.92it/s]

 47%|████▋     | 14254/30196 [29:37<32:39,  8.14it/s]

 47%|████▋     | 14256/30196 [29:37<28:21,  9.37it/s]

 47%|████▋     | 14258/30196 [29:38<30:12,  8.79it/s]

 47%|████▋     | 14260/30196 [29:38<32:29,  8.18it/s]

 47%|████▋     | 14261/30196 [29:38<35:03,  7.58it/s]

 47%|████▋     | 14263/30196 [29:38<35:13,  7.54it/s]

 47%|████▋     | 14264/30196 [29:39<37:00,  7.18it/s]

 47%|████▋     | 14266/30196 [29:39<32:15,  8.23it/s]

 47%|████▋     | 14267/30196 [29:39<36:59,  7.18it/s]

 47%|████▋     | 14268/30196 [29:39<35:13,  7.54it/s]

 47%|████▋     | 14270/30196 [29:39<33:25,  7.94it/s]

 47%|████▋     | 14271/30196 [29:40<41:20,  6.42it/s]

 47%|████▋     | 14273/30196 [29:40<34:22,  7.72it/s]

 47%|████▋     | 14274/30196 [29:40<34:25,  7.71it/s]

 47%|████▋     | 14275/30196 [29:40<37:25,  7.09it/s]

 47%|████▋     | 14276/30196 [29:40<35:19,  7.51it/s]

 47%|████▋     | 14277/30196 [29:40<33:30,  7.92it/s]

 47%|████▋     | 14278/30196 [29:40<34:10,  7.76it/s]

 47%|████▋     | 14279/30196 [29:41<32:49,  8.08it/s]

 47%|████▋     | 14280/30196 [29:41<36:04,  7.35it/s]

 47%|████▋     | 14281/30196 [29:41<41:29,  6.39it/s]

 47%|████▋     | 14283/30196 [29:41<36:16,  7.31it/s]

 47%|████▋     | 14284/30196 [29:41<42:20,  6.26it/s]

 47%|████▋     | 14286/30196 [29:42<34:35,  7.67it/s]

 47%|████▋     | 14288/30196 [29:42<33:18,  7.96it/s]

 47%|████▋     | 14289/30196 [29:42<32:28,  8.17it/s]

 47%|████▋     | 14291/30196 [29:42<25:51, 10.25it/s]

 47%|████▋     | 14293/30196 [29:42<26:12, 10.11it/s]

 47%|████▋     | 14295/30196 [29:43<49:20,  5.37it/s]

 47%|████▋     | 14296/30196 [29:43<48:43,  5.44it/s]

 47%|████▋     | 14297/30196 [29:43<47:40,  5.56it/s]

 47%|████▋     | 14299/30196 [29:43<39:22,  6.73it/s]

 47%|████▋     | 14300/30196 [29:44<36:52,  7.18it/s]

 47%|████▋     | 14301/30196 [29:44<36:21,  7.29it/s]

 47%|████▋     | 14303/30196 [29:44<34:14,  7.74it/s]

 47%|████▋     | 14304/30196 [29:44<36:27,  7.27it/s]

 47%|████▋     | 14306/30196 [29:44<28:33,  9.27it/s]

 47%|████▋     | 14308/30196 [29:44<24:41, 10.73it/s]

 47%|████▋     | 14310/30196 [29:44<21:05, 12.55it/s]

 47%|████▋     | 14312/30196 [29:45<24:59, 10.59it/s]

 47%|████▋     | 14314/30196 [29:45<29:39,  8.92it/s]

 47%|████▋     | 14316/30196 [29:45<31:20,  8.44it/s]

 47%|████▋     | 14317/30196 [29:45<35:37,  7.43it/s]

 47%|████▋     | 14319/30196 [29:46<36:44,  7.20it/s]

 47%|████▋     | 14320/30196 [29:46<37:12,  7.11it/s]

 47%|████▋     | 14322/30196 [29:46<36:13,  7.30it/s]

 47%|████▋     | 14323/30196 [29:46<36:25,  7.26it/s]

 47%|████▋     | 14324/30196 [29:47<38:21,  6.90it/s]

 47%|████▋     | 14325/30196 [29:47<38:08,  6.93it/s]

 47%|████▋     | 14326/30196 [29:47<37:33,  7.04it/s]

 47%|████▋     | 14327/30196 [29:47<49:37,  5.33it/s]

 47%|████▋     | 14328/30196 [29:47<43:53,  6.03it/s]

 47%|████▋     | 14330/30196 [29:47<34:55,  7.57it/s]

 47%|████▋     | 14332/30196 [29:48<34:19,  7.70it/s]

 47%|████▋     | 14333/30196 [29:48<37:13,  7.10it/s]

 47%|████▋     | 14335/30196 [29:48<33:13,  7.96it/s]

 47%|████▋     | 14336/30196 [29:48<36:11,  7.30it/s]

 47%|████▋     | 14337/30196 [29:49<47:13,  5.60it/s]

 47%|████▋     | 14339/30196 [29:49<39:27,  6.70it/s]

 47%|████▋     | 14340/30196 [29:49<39:20,  6.72it/s]

 47%|████▋     | 14341/30196 [29:49<40:28,  6.53it/s]

 47%|████▋     | 14343/30196 [29:49<33:58,  7.78it/s]

 48%|████▊     | 14345/30196 [29:49<29:30,  8.95it/s]

 48%|████▊     | 14347/30196 [29:50<34:06,  7.74it/s]

 48%|████▊     | 14348/30196 [29:50<34:45,  7.60it/s]

 48%|████▊     | 14349/30196 [29:50<35:36,  7.42it/s]

 48%|████▊     | 14350/30196 [29:50<37:37,  7.02it/s]

 48%|████▊     | 14352/30196 [29:50<35:00,  7.54it/s]

 48%|████▊     | 14353/30196 [29:51<33:36,  7.86it/s]

 48%|████▊     | 14354/30196 [29:51<36:46,  7.18it/s]

 48%|████▊     | 14356/30196 [29:51<28:53,  9.14it/s]

 48%|████▊     | 14357/30196 [29:51<28:37,  9.22it/s]

 48%|████▊     | 14358/30196 [29:51<28:21,  9.31it/s]

 48%|████▊     | 14359/30196 [29:51<32:13,  8.19it/s]

 48%|████▊     | 14360/30196 [29:51<32:48,  8.05it/s]

 48%|████▊     | 14361/30196 [29:51<35:44,  7.38it/s]

 48%|████▊     | 14362/30196 [29:52<35:46,  7.38it/s]

 48%|████▊     | 14364/30196 [29:52<37:40,  7.00it/s]

 48%|████▊     | 14365/30196 [29:52<37:09,  7.10it/s]

 48%|████▊     | 14366/30196 [29:52<36:30,  7.23it/s]

 48%|████▊     | 14368/30196 [29:52<30:55,  8.53it/s]

 48%|████▊     | 14370/30196 [29:53<30:01,  8.79it/s]

 48%|████▊     | 14371/30196 [29:53<32:52,  8.02it/s]

 48%|████▊     | 14372/30196 [29:53<33:13,  7.94it/s]

 48%|████▊     | 14374/30196 [29:53<26:21, 10.01it/s]

 48%|████▊     | 14376/30196 [29:53<27:12,  9.69it/s]

 48%|████▊     | 14378/30196 [29:54<35:09,  7.50it/s]

 48%|████▊     | 14380/30196 [29:54<31:56,  8.25it/s]

 48%|████▊     | 14381/30196 [29:54<32:18,  8.16it/s]

 48%|████▊     | 14382/30196 [29:54<34:11,  7.71it/s]

 48%|████▊     | 14383/30196 [29:54<32:39,  8.07it/s]

 48%|████▊     | 14385/30196 [29:54<26:15, 10.04it/s]

 48%|████▊     | 14387/30196 [29:54<24:37, 10.70it/s]

 48%|████▊     | 14389/30196 [29:55<22:53, 11.51it/s]

 48%|████▊     | 14391/30196 [29:55<24:57, 10.55it/s]

 48%|████▊     | 14393/30196 [29:55<30:00,  8.78it/s]

 48%|████▊     | 14395/30196 [29:55<29:21,  8.97it/s]

 48%|████▊     | 14396/30196 [29:55<30:16,  8.70it/s]

 48%|████▊     | 14398/30196 [29:56<27:53,  9.44it/s]

 48%|████▊     | 14400/30196 [29:56<28:01,  9.39it/s]

 48%|████▊     | 14402/30196 [29:56<27:52,  9.45it/s]

 48%|████▊     | 14404/30196 [29:56<27:19,  9.63it/s]

 48%|████▊     | 14405/30196 [29:56<30:25,  8.65it/s]

 48%|████▊     | 14407/30196 [29:57<27:11,  9.68it/s]

 48%|████▊     | 14408/30196 [29:57<28:36,  9.20it/s]

 48%|████▊     | 14409/30196 [29:57<30:51,  8.53it/s]

 48%|████▊     | 14410/30196 [29:57<32:17,  8.15it/s]

 48%|████▊     | 14412/30196 [29:57<30:58,  8.49it/s]

 48%|████▊     | 14413/30196 [29:57<32:42,  8.04it/s]

 48%|████▊     | 14415/30196 [29:58<31:02,  8.47it/s]

 48%|████▊     | 14416/30196 [29:58<33:46,  7.79it/s]

 48%|████▊     | 14418/30196 [29:58<28:02,  9.38it/s]

 48%|████▊     | 14419/30196 [29:58<28:14,  9.31it/s]

 48%|████▊     | 14420/30196 [29:58<29:57,  8.78it/s]

 48%|████▊     | 14421/30196 [29:58<34:14,  7.68it/s]

 48%|████▊     | 14423/30196 [29:59<28:51,  9.11it/s]

 48%|████▊     | 14425/30196 [29:59<28:51,  9.11it/s]

 48%|████▊     | 14427/30196 [29:59<27:41,  9.49it/s]

 48%|████▊     | 14429/30196 [29:59<29:37,  8.87it/s]

 48%|████▊     | 14430/30196 [29:59<30:43,  8.55it/s]

 48%|████▊     | 14431/30196 [29:59<32:07,  8.18it/s]

 48%|████▊     | 14432/30196 [30:00<33:37,  7.81it/s]

 48%|████▊     | 14433/30196 [30:00<34:49,  7.55it/s]

 48%|████▊     | 14435/30196 [30:00<44:51,  5.86it/s]

 48%|████▊     | 14436/30196 [30:00<42:52,  6.13it/s]

 48%|████▊     | 14437/30196 [30:00<41:50,  6.28it/s]

 48%|████▊     | 14438/30196 [30:01<45:32,  5.77it/s]

 48%|████▊     | 14439/30196 [30:01<43:13,  6.08it/s]

 48%|████▊     | 14440/30196 [30:01<38:51,  6.76it/s]

 48%|████▊     | 14442/30196 [30:01<31:56,  8.22it/s]

 48%|████▊     | 14443/30196 [30:01<32:32,  8.07it/s]

 48%|████▊     | 14444/30196 [30:01<39:38,  6.62it/s]

 48%|████▊     | 14445/30196 [30:02<36:44,  7.15it/s]

 48%|████▊     | 14446/30196 [30:02<35:59,  7.29it/s]

 48%|████▊     | 14447/30196 [30:02<41:22,  6.34it/s]

 48%|████▊     | 14448/30196 [30:02<43:08,  6.08it/s]

 48%|████▊     | 14449/30196 [30:02<47:59,  5.47it/s]

 48%|████▊     | 14450/30196 [30:02<43:54,  5.98it/s]

 48%|████▊     | 14451/30196 [30:03<44:46,  5.86it/s]

 48%|████▊     | 14453/30196 [30:03<39:25,  6.65it/s]

 48%|████▊     | 14454/30196 [30:03<36:29,  7.19it/s]

 48%|████▊     | 14456/30196 [30:03<31:12,  8.41it/s]

 48%|████▊     | 14458/30196 [30:03<30:45,  8.53it/s]

 48%|████▊     | 14460/30196 [30:04<28:11,  9.31it/s]

 48%|████▊     | 14461/30196 [30:04<28:17,  9.27it/s]

 48%|████▊     | 14462/30196 [30:04<32:05,  8.17it/s]

 48%|████▊     | 14464/30196 [30:04<28:47,  9.11it/s]

 48%|████▊     | 14466/30196 [30:04<29:10,  8.98it/s]

 48%|████▊     | 14467/30196 [30:04<30:23,  8.62it/s]

 48%|████▊     | 14468/30196 [30:05<31:18,  8.37it/s]

 48%|████▊     | 14470/30196 [30:05<31:07,  8.42it/s]

 48%|████▊     | 14472/30196 [30:05<25:55, 10.11it/s]

 48%|████▊     | 14474/30196 [30:05<40:30,  6.47it/s]

 48%|████▊     | 14476/30196 [30:06<34:52,  7.51it/s]

 48%|████▊     | 14477/30196 [30:06<39:32,  6.62it/s]

 48%|████▊     | 14479/30196 [30:06<36:23,  7.20it/s]

 48%|████▊     | 14480/30196 [30:06<34:35,  7.57it/s]

 48%|████▊     | 14482/30196 [30:06<27:58,  9.36it/s]

 48%|████▊     | 14484/30196 [30:06<25:43, 10.18it/s]

 48%|████▊     | 14486/30196 [30:07<31:07,  8.41it/s]

 48%|████▊     | 14488/30196 [30:07<28:38,  9.14it/s]

 48%|████▊     | 14490/30196 [30:07<24:32, 10.66it/s]

 48%|████▊     | 14492/30196 [30:07<27:11,  9.62it/s]

 48%|████▊     | 14494/30196 [30:08<27:26,  9.54it/s]

 48%|████▊     | 14496/30196 [30:08<32:20,  8.09it/s]

 48%|████▊     | 14498/30196 [30:08<29:29,  8.87it/s]

 48%|████▊     | 14499/30196 [30:08<32:22,  8.08it/s]

 48%|████▊     | 14501/30196 [30:08<28:26,  9.20it/s]

 48%|████▊     | 14502/30196 [30:09<28:28,  9.18it/s]

 48%|████▊     | 14504/30196 [30:09<26:41,  9.80it/s]

 48%|████▊     | 14506/30196 [30:09<23:01, 11.36it/s]

 48%|████▊     | 14508/30196 [30:09<27:07,  9.64it/s]

 48%|████▊     | 14510/30196 [30:09<32:34,  8.03it/s]

 48%|████▊     | 14511/30196 [30:10<32:48,  7.97it/s]

 48%|████▊     | 14512/30196 [30:10<33:07,  7.89it/s]

 48%|████▊     | 14513/30196 [30:10<37:57,  6.89it/s]

 48%|████▊     | 14514/30196 [30:10<37:19,  7.00it/s]

 48%|████▊     | 14515/30196 [30:10<36:27,  7.17it/s]

 48%|████▊     | 14517/30196 [30:10<29:16,  8.93it/s]

 48%|████▊     | 14518/30196 [30:11<34:58,  7.47it/s]

 48%|████▊     | 14519/30196 [30:11<37:01,  7.06it/s]

 48%|████▊     | 14520/30196 [30:11<34:52,  7.49it/s]

 48%|████▊     | 14522/30196 [30:11<30:00,  8.70it/s]

 48%|████▊     | 14523/30196 [30:11<31:58,  8.17it/s]

 48%|████▊     | 14525/30196 [30:11<28:52,  9.04it/s]

 48%|████▊     | 14526/30196 [30:11<30:57,  8.44it/s]

 48%|████▊     | 14527/30196 [30:12<56:24,  4.63it/s]

 48%|████▊     | 14528/30196 [30:12<50:57,  5.12it/s]

 48%|████▊     | 14530/30196 [30:12<47:42,  5.47it/s]

 48%|████▊     | 14532/30196 [30:13<40:35,  6.43it/s]

 48%|████▊     | 14533/30196 [30:13<38:05,  6.85it/s]

 48%|████▊     | 14535/30196 [30:13<33:15,  7.85it/s]

 48%|████▊     | 14536/30196 [30:13<35:24,  7.37it/s]

 48%|████▊     | 14538/30196 [30:13<30:47,  8.48it/s]

 48%|████▊     | 14540/30196 [30:14<33:04,  7.89it/s]

 48%|████▊     | 14541/30196 [30:14<32:12,  8.10it/s]

 48%|████▊     | 14542/30196 [30:14<37:10,  7.02it/s]

 48%|████▊     | 14544/30196 [30:14<32:38,  7.99it/s]

 48%|████▊     | 14546/30196 [30:14<31:53,  8.18it/s]

 48%|████▊     | 14547/30196 [30:14<30:59,  8.42it/s]

 48%|████▊     | 14548/30196 [30:15<30:29,  8.55it/s]

 48%|████▊     | 14549/30196 [30:15<32:20,  8.06it/s]

 48%|████▊     | 14550/30196 [30:15<39:18,  6.63it/s]

 48%|████▊     | 14552/30196 [30:16<1:10:13,  3.71it/s]

 48%|████▊     | 14553/30196 [30:16<1:01:47,  4.22it/s]

 48%|████▊     | 14555/30196 [30:16<43:26,  6.00it/s]

 48%|████▊     | 14556/30196 [30:16<43:38,  5.97it/s]

 48%|████▊     | 14558/30196 [30:16<32:42,  7.97it/s]

 48%|████▊     | 14560/30196 [30:16<26:49,  9.71it/s]

 48%|████▊     | 14562/30196 [30:17<26:12,  9.94it/s]

 48%|████▊     | 14564/30196 [30:17<25:50, 10.08it/s]

 48%|████▊     | 14566/30196 [30:17<30:03,  8.67it/s]

 48%|████▊     | 14567/30196 [30:17<31:15,  8.33it/s]

 48%|████▊     | 14568/30196 [30:18<36:19,  7.17it/s]

 48%|████▊     | 14570/30196 [30:18<32:49,  7.93it/s]

 48%|████▊     | 14572/30196 [30:18<31:22,  8.30it/s]

 48%|████▊     | 14574/30196 [30:18<31:56,  8.15it/s]

 48%|████▊     | 14575/30196 [30:18<32:17,  8.06it/s]

 48%|████▊     | 14577/30196 [30:19<31:03,  8.38it/s]

 48%|████▊     | 14580/30196 [30:19<24:34, 10.59it/s]

 48%|████▊     | 14582/30196 [30:19<25:22, 10.25it/s]

 48%|████▊     | 14584/30196 [30:19<31:21,  8.30it/s]

 48%|████▊     | 14585/30196 [30:19<30:53,  8.42it/s]

 48%|████▊     | 14586/30196 [30:20<43:48,  5.94it/s]

 48%|████▊     | 14587/30196 [30:20<42:33,  6.11it/s]

 48%|████▊     | 14589/30196 [30:20<36:50,  7.06it/s]

 48%|████▊     | 14590/30196 [30:20<36:57,  7.04it/s]

 48%|████▊     | 14592/30196 [30:20<33:08,  7.85it/s]

 48%|████▊     | 14593/30196 [30:21<35:57,  7.23it/s]

 48%|████▊     | 14594/30196 [30:21<38:15,  6.80it/s]

 48%|████▊     | 14597/30196 [30:21<29:21,  8.86it/s]

 48%|████▊     | 14599/30196 [30:21<28:03,  9.26it/s]

 48%|████▊     | 14601/30196 [30:22<29:37,  8.77it/s]

 48%|████▊     | 14603/30196 [30:22<25:42, 10.11it/s]

 48%|████▊     | 14605/30196 [30:22<24:35, 10.57it/s]

 48%|████▊     | 14607/30196 [30:22<24:42, 10.51it/s]

 48%|████▊     | 14609/30196 [30:22<22:07, 11.74it/s]

 48%|████▊     | 14611/30196 [30:22<24:39, 10.53it/s]

 48%|████▊     | 14613/30196 [30:22<22:09, 11.72it/s]

 48%|████▊     | 14615/30196 [30:23<23:43, 10.95it/s]

 48%|████▊     | 14617/30196 [30:23<23:36, 10.99it/s]

 48%|████▊     | 14619/30196 [30:23<25:56, 10.01it/s]

 48%|████▊     | 14621/30196 [30:23<28:12,  9.20it/s]

 48%|████▊     | 14622/30196 [30:24<29:13,  8.88it/s]

 48%|████▊     | 14623/30196 [30:24<40:09,  6.46it/s]

 48%|████▊     | 14624/30196 [30:24<37:27,  6.93it/s]

 48%|████▊     | 14625/30196 [30:24<41:46,  6.21it/s]

 48%|████▊     | 14626/30196 [30:24<38:04,  6.82it/s]

 48%|████▊     | 14627/30196 [30:24<35:30,  7.31it/s]

 48%|████▊     | 14629/30196 [30:24<27:16,  9.51it/s]

 48%|████▊     | 14631/30196 [30:25<28:49,  9.00it/s]

 48%|████▊     | 14632/30196 [30:25<36:36,  7.08it/s]

 48%|████▊     | 14633/30196 [30:25<36:00,  7.21it/s]

 48%|████▊     | 14634/30196 [30:25<34:05,  7.61it/s]

 48%|████▊     | 14635/30196 [30:25<32:35,  7.96it/s]

 48%|████▊     | 14636/30196 [30:25<31:28,  8.24it/s]

 48%|████▊     | 14637/30196 [30:26<35:17,  7.35it/s]

 48%|████▊     | 14639/30196 [30:26<28:46,  9.01it/s]

 48%|████▊     | 14641/30196 [30:26<27:57,  9.27it/s]

 48%|████▊     | 14643/30196 [30:26<24:06, 10.75it/s]

 48%|████▊     | 14645/30196 [30:26<27:10,  9.54it/s]

 49%|████▊     | 14647/30196 [30:27<26:20,  9.84it/s]

 49%|████▊     | 14649/30196 [30:27<25:46, 10.05it/s]

 49%|████▊     | 14651/30196 [30:27<27:26,  9.44it/s]

 49%|████▊     | 14653/30196 [30:27<30:43,  8.43it/s]

 49%|████▊     | 14654/30196 [30:27<31:16,  8.28it/s]

 49%|████▊     | 14655/30196 [30:28<30:43,  8.43it/s]

 49%|████▊     | 14657/30196 [30:28<25:36, 10.11it/s]

 49%|████▊     | 14659/30196 [30:28<30:08,  8.59it/s]

 49%|████▊     | 14661/30196 [30:28<29:08,  8.88it/s]

 49%|████▊     | 14663/30196 [30:28<26:55,  9.62it/s]

 49%|████▊     | 14665/30196 [30:29<27:36,  9.37it/s]

 49%|████▊     | 14667/30196 [30:29<26:48,  9.66it/s]

 49%|████▊     | 14668/30196 [30:29<28:49,  8.98it/s]

 49%|████▊     | 14670/30196 [30:29<38:08,  6.78it/s]

 49%|████▊     | 14672/30196 [30:29<31:51,  8.12it/s]

 49%|████▊     | 14674/30196 [30:30<30:11,  8.57it/s]

 49%|████▊     | 14675/30196 [30:30<31:22,  8.24it/s]

 49%|████▊     | 14677/30196 [30:30<28:25,  9.10it/s]

 49%|████▊     | 14678/30196 [30:30<33:43,  7.67it/s]

 49%|████▊     | 14680/30196 [30:30<26:50,  9.64it/s]

 49%|████▊     | 14682/30196 [30:31<27:28,  9.41it/s]

 49%|████▊     | 14684/30196 [30:31<30:24,  8.50it/s]

 49%|████▊     | 14685/30196 [30:31<30:03,  8.60it/s]

 49%|████▊     | 14687/30196 [30:31<26:03,  9.92it/s]

 49%|████▊     | 14689/30196 [30:31<24:03, 10.74it/s]

 49%|████▊     | 14691/30196 [30:32<27:03,  9.55it/s]

 49%|████▊     | 14693/30196 [30:32<33:09,  7.79it/s]

 49%|████▊     | 14695/30196 [30:32<29:54,  8.64it/s]

 49%|████▊     | 14696/30196 [30:32<30:43,  8.41it/s]

 49%|████▊     | 14699/30196 [30:32<27:07,  9.52it/s]

 49%|████▊     | 14701/30196 [30:33<24:47, 10.41it/s]

 49%|████▊     | 14703/30196 [30:33<25:59,  9.93it/s]

 49%|████▊     | 14705/30196 [30:33<32:25,  7.96it/s]

 49%|████▊     | 14706/30196 [30:33<34:36,  7.46it/s]

 49%|████▊     | 14707/30196 [30:33<33:04,  7.80it/s]

 49%|████▊     | 14708/30196 [30:34<33:30,  7.71it/s]

 49%|████▊     | 14709/30196 [30:34<31:55,  8.08it/s]

 49%|████▊     | 14710/30196 [30:34<43:33,  5.93it/s]

 49%|████▊     | 14712/30196 [30:34<33:04,  7.80it/s]

 49%|████▊     | 14713/30196 [30:34<36:01,  7.16it/s]

 49%|████▊     | 14714/30196 [30:35<38:21,  6.73it/s]

 49%|████▊     | 14716/30196 [30:35<35:17,  7.31it/s]

 49%|████▊     | 14718/30196 [30:35<34:25,  7.49it/s]

 49%|████▊     | 14719/30196 [30:35<34:17,  7.52it/s]

 49%|████▉     | 14721/30196 [30:35<29:19,  8.80it/s]

 49%|████▉     | 14722/30196 [30:35<32:19,  7.98it/s]

 49%|████▉     | 14724/30196 [30:36<26:29,  9.73it/s]

 49%|████▉     | 14726/30196 [30:36<35:43,  7.22it/s]

 49%|████▉     | 14727/30196 [30:36<35:30,  7.26it/s]

 49%|████▉     | 14728/30196 [30:36<37:13,  6.93it/s]

 49%|████▉     | 14729/30196 [30:36<36:20,  7.09it/s]

 49%|████▉     | 14730/30196 [30:37<37:19,  6.90it/s]

 49%|████▉     | 14731/30196 [30:37<36:36,  7.04it/s]

 49%|████▉     | 14733/30196 [30:37<31:12,  8.26it/s]

 49%|████▉     | 14734/30196 [30:37<32:46,  7.86it/s]

 49%|████▉     | 14735/30196 [30:37<35:10,  7.33it/s]

 49%|████▉     | 14737/30196 [30:37<32:54,  7.83it/s]

 49%|████▉     | 14739/30196 [30:38<26:25,  9.75it/s]

 49%|████▉     | 14741/30196 [30:38<29:34,  8.71it/s]

 49%|████▉     | 14742/30196 [30:38<34:22,  7.49it/s]

 49%|████▉     | 14743/30196 [30:38<37:04,  6.95it/s]

 49%|████▉     | 14745/30196 [30:38<33:46,  7.62it/s]

 49%|████▉     | 14746/30196 [30:39<33:57,  7.58it/s]

 49%|████▉     | 14748/30196 [30:39<30:19,  8.49it/s]

 49%|████▉     | 14750/30196 [30:39<37:55,  6.79it/s]

 49%|████▉     | 14752/30196 [30:39<33:38,  7.65it/s]

 49%|████▉     | 14753/30196 [30:40<37:28,  6.87it/s]

 49%|████▉     | 14754/30196 [30:40<40:54,  6.29it/s]

 49%|████▉     | 14756/30196 [30:40<35:24,  7.27it/s]

 49%|████▉     | 14757/30196 [30:40<35:16,  7.29it/s]

 49%|████▉     | 14759/30196 [30:40<32:10,  8.00it/s]

 49%|████▉     | 14760/30196 [30:40<31:53,  8.07it/s]

 49%|████▉     | 14761/30196 [30:41<31:03,  8.28it/s]

 49%|████▉     | 14762/30196 [30:41<32:21,  7.95it/s]

 49%|████▉     | 14763/30196 [30:41<35:49,  7.18it/s]

 49%|████▉     | 14764/30196 [30:41<33:43,  7.62it/s]

 49%|████▉     | 14765/30196 [30:41<34:02,  7.55it/s]

 49%|████▉     | 14766/30196 [30:41<43:26,  5.92it/s]

 49%|████▉     | 14768/30196 [30:42<36:34,  7.03it/s]

 49%|████▉     | 14769/30196 [30:42<36:06,  7.12it/s]

 49%|████▉     | 14770/30196 [30:42<37:46,  6.81it/s]

 49%|████▉     | 14771/30196 [30:42<36:39,  7.01it/s]

 49%|████▉     | 14772/30196 [30:42<38:54,  6.61it/s]

 49%|████▉     | 14773/30196 [30:42<37:24,  6.87it/s]

 49%|████▉     | 14774/30196 [30:43<37:28,  6.86it/s]

 49%|████▉     | 14775/30196 [30:43<53:27,  4.81it/s]

 49%|████▉     | 14776/30196 [30:43<45:40,  5.63it/s]

 49%|████▉     | 14778/30196 [30:43<36:06,  7.12it/s]

 49%|████▉     | 14779/30196 [30:43<35:26,  7.25it/s]

 49%|████▉     | 14781/30196 [30:43<29:35,  8.68it/s]

 49%|████▉     | 14782/30196 [30:44<42:20,  6.07it/s]

 49%|████▉     | 14783/30196 [30:44<42:37,  6.03it/s]

 49%|████▉     | 14785/30196 [30:44<34:33,  7.43it/s]

 49%|████▉     | 14787/30196 [30:44<34:15,  7.50it/s]

 49%|████▉     | 14789/30196 [30:45<36:09,  7.10it/s]

 49%|████▉     | 14791/30196 [30:45<33:37,  7.64it/s]

 49%|████▉     | 14792/30196 [30:45<33:39,  7.63it/s]

 49%|████▉     | 14793/30196 [30:45<32:14,  7.96it/s]

 49%|████▉     | 14794/30196 [30:45<32:34,  7.88it/s]

 49%|████▉     | 14795/30196 [30:45<31:09,  8.24it/s]

 49%|████▉     | 14797/30196 [30:46<25:45,  9.96it/s]

 49%|████▉     | 14799/30196 [30:46<26:31,  9.68it/s]

 49%|████▉     | 14801/30196 [30:46<25:20, 10.13it/s]

 49%|████▉     | 14803/30196 [30:46<25:52,  9.91it/s]

 49%|████▉     | 14805/30196 [30:46<27:09,  9.44it/s]

 49%|████▉     | 14806/30196 [30:47<27:22,  9.37it/s]

 49%|████▉     | 14807/30196 [30:47<31:00,  8.27it/s]

 49%|████▉     | 14808/30196 [30:47<33:43,  7.60it/s]

 49%|████▉     | 14810/30196 [30:47<28:55,  8.86it/s]

 49%|████▉     | 14811/30196 [30:47<30:50,  8.31it/s]

 49%|████▉     | 14813/30196 [30:47<24:39, 10.40it/s]

 49%|████▉     | 14816/30196 [30:48<22:23, 11.45it/s]

 49%|████▉     | 14818/30196 [30:48<20:47, 12.33it/s]

 49%|████▉     | 14820/30196 [30:48<26:15,  9.76it/s]

 49%|████▉     | 14822/30196 [30:48<24:35, 10.42it/s]

 49%|████▉     | 14824/30196 [30:48<24:20, 10.53it/s]

 49%|████▉     | 14826/30196 [30:48<23:20, 10.98it/s]

 49%|████▉     | 14828/30196 [30:49<30:29,  8.40it/s]

 49%|████▉     | 14829/30196 [30:49<31:02,  8.25it/s]

 49%|████▉     | 14831/30196 [30:49<33:29,  7.65it/s]

 49%|████▉     | 14832/30196 [30:49<32:11,  7.95it/s]

 49%|████▉     | 14833/30196 [30:50<33:26,  7.66it/s]

 49%|████▉     | 14835/30196 [30:50<31:14,  8.20it/s]

 49%|████▉     | 14836/30196 [30:50<35:56,  7.12it/s]

 49%|████▉     | 14838/30196 [30:50<30:06,  8.50it/s]

 49%|████▉     | 14839/30196 [30:50<29:43,  8.61it/s]

 49%|████▉     | 14840/30196 [30:50<33:07,  7.73it/s]

 49%|████▉     | 14841/30196 [30:51<35:23,  7.23it/s]

 49%|████▉     | 14842/30196 [30:51<33:27,  7.65it/s]

 49%|████▉     | 14843/30196 [30:51<31:59,  8.00it/s]

 49%|████▉     | 14845/30196 [30:51<31:12,  8.20it/s]

 49%|████▉     | 14847/30196 [30:51<29:38,  8.63it/s]

 49%|████▉     | 14849/30196 [30:51<25:56,  9.86it/s]

 49%|████▉     | 14851/30196 [30:52<24:47, 10.31it/s]

 49%|████▉     | 14853/30196 [30:52<27:52,  9.18it/s]

 49%|████▉     | 14854/30196 [30:52<30:46,  8.31it/s]

 49%|████▉     | 14855/30196 [30:52<29:54,  8.55it/s]

 49%|████▉     | 14857/30196 [30:52<25:42,  9.94it/s]

 49%|████▉     | 14859/30196 [30:52<25:41,  9.95it/s]

 49%|████▉     | 14861/30196 [30:53<30:51,  8.28it/s]

 49%|████▉     | 14862/30196 [30:53<33:02,  7.73it/s]

 49%|████▉     | 14864/30196 [30:53<28:43,  8.90it/s]

 49%|████▉     | 14866/30196 [30:53<24:29, 10.43it/s]

 49%|████▉     | 14868/30196 [30:53<25:42,  9.94it/s]

 49%|████▉     | 14870/30196 [30:54<25:45,  9.92it/s]

 49%|████▉     | 14872/30196 [30:54<29:45,  8.58it/s]

 49%|████▉     | 14874/30196 [30:54<26:11,  9.75it/s]

 49%|████▉     | 14876/30196 [30:54<25:45,  9.91it/s]

 49%|████▉     | 14878/30196 [30:55<36:52,  6.92it/s]

 49%|████▉     | 14880/30196 [30:55<32:58,  7.74it/s]

 49%|████▉     | 14882/30196 [30:55<28:48,  8.86it/s]

 49%|████▉     | 14884/30196 [30:55<27:43,  9.20it/s]

 49%|████▉     | 14886/30196 [30:56<28:22,  8.99it/s]

 49%|████▉     | 14887/30196 [30:56<28:16,  9.02it/s]

 49%|████▉     | 14888/30196 [30:56<29:16,  8.72it/s]

 49%|████▉     | 14889/30196 [30:56<28:33,  8.93it/s]

 49%|████▉     | 14890/30196 [30:56<28:09,  9.06it/s]

 49%|████▉     | 14891/30196 [30:56<34:29,  7.40it/s]

 49%|████▉     | 14894/30196 [30:56<22:53, 11.14it/s]

 49%|████▉     | 14896/30196 [30:57<24:56, 10.23it/s]

 49%|████▉     | 14898/30196 [30:57<21:25, 11.90it/s]

 49%|████▉     | 14900/30196 [30:57<23:36, 10.80it/s]

 49%|████▉     | 14902/30196 [30:57<27:04,  9.41it/s]

 49%|████▉     | 14904/30196 [30:57<26:45,  9.53it/s]

 49%|████▉     | 14906/30196 [30:58<26:43,  9.53it/s]

 49%|████▉     | 14908/30196 [30:58<30:23,  8.38it/s]

 49%|████▉     | 14910/30196 [30:58<26:13,  9.71it/s]

 49%|████▉     | 14912/30196 [30:58<34:10,  7.45it/s]

 49%|████▉     | 14914/30196 [30:59<29:05,  8.76it/s]

 49%|████▉     | 14916/30196 [30:59<26:17,  9.69it/s]

 49%|████▉     | 14918/30196 [30:59<29:13,  8.71it/s]

 49%|████▉     | 14920/30196 [30:59<29:59,  8.49it/s]

 49%|████▉     | 14922/30196 [30:59<26:01,  9.78it/s]

 49%|████▉     | 14924/30196 [31:00<25:37,  9.93it/s]

 49%|████▉     | 14926/30196 [31:00<24:49, 10.25it/s]

 49%|████▉     | 14928/30196 [31:00<24:06, 10.55it/s]

 49%|████▉     | 14930/30196 [31:00<25:25, 10.01it/s]

 49%|████▉     | 14932/30196 [31:00<27:42,  9.18it/s]

 49%|████▉     | 14933/30196 [31:01<29:09,  8.72it/s]

 49%|████▉     | 14934/30196 [31:01<30:09,  8.43it/s]

 49%|████▉     | 14935/30196 [31:01<31:45,  8.01it/s]

 49%|████▉     | 14937/30196 [31:01<24:29, 10.38it/s]

 49%|████▉     | 14939/30196 [31:01<28:47,  8.83it/s]

 49%|████▉     | 14941/30196 [31:02<34:16,  7.42it/s]

 49%|████▉     | 14943/30196 [31:02<40:34,  6.26it/s]

 49%|████▉     | 14944/30196 [31:02<38:12,  6.65it/s]

 49%|████▉     | 14945/30196 [31:02<35:45,  7.11it/s]

 49%|████▉     | 14946/30196 [31:02<35:12,  7.22it/s]

 49%|████▉     | 14947/30196 [31:03<39:30,  6.43it/s]

 50%|████▉     | 14948/30196 [31:03<43:31,  5.84it/s]

 50%|████▉     | 14949/30196 [31:03<43:22,  5.86it/s]

 50%|████▉     | 14950/30196 [31:03<54:50,  4.63it/s]

 50%|████▉     | 14951/30196 [31:03<49:20,  5.15it/s]

 50%|████▉     | 14952/30196 [31:04<45:26,  5.59it/s]

 50%|████▉     | 14954/30196 [31:04<37:46,  6.73it/s]

 50%|████▉     | 14955/30196 [31:04<39:38,  6.41it/s]

 50%|████▉     | 14956/30196 [31:04<38:14,  6.64it/s]

 50%|████▉     | 14957/30196 [31:04<40:19,  6.30it/s]

 50%|████▉     | 14958/30196 [31:05<49:22,  5.14it/s]

 50%|████▉     | 14959/30196 [31:05<1:01:55,  4.10it/s]

 50%|████▉     | 14960/30196 [31:05<51:40,  4.91it/s]

 50%|████▉     | 14961/30196 [31:05<46:17,  5.49it/s]

 50%|████▉     | 14962/30196 [31:05<43:36,  5.82it/s]

 50%|████▉     | 14965/30196 [31:05<28:26,  8.93it/s]

 50%|████▉     | 14966/30196 [31:06<36:22,  6.98it/s]

 50%|████▉     | 14968/30196 [31:06<33:26,  7.59it/s]

 50%|████▉     | 14970/30196 [31:06<28:16,  8.98it/s]

 50%|████▉     | 14972/30196 [31:06<28:15,  8.98it/s]

 50%|████▉     | 14974/30196 [31:07<29:19,  8.65it/s]

 50%|████▉     | 14976/30196 [31:07<28:58,  8.76it/s]

 50%|████▉     | 14977/30196 [31:07<30:12,  8.39it/s]

 50%|████▉     | 14978/30196 [31:07<32:48,  7.73it/s]

 50%|████▉     | 14979/30196 [31:07<32:59,  7.69it/s]

 50%|████▉     | 14980/30196 [31:07<37:49,  6.70it/s]

 50%|████▉     | 14981/30196 [31:08<35:12,  7.20it/s]

 50%|████▉     | 14982/30196 [31:08<40:21,  6.28it/s]

 50%|████▉     | 14983/30196 [31:08<38:36,  6.57it/s]

 50%|████▉     | 14984/30196 [31:08<37:20,  6.79it/s]

 50%|████▉     | 14985/30196 [31:08<42:24,  5.98it/s]

 50%|████▉     | 14987/30196 [31:09<43:10,  5.87it/s]

 50%|████▉     | 14988/30196 [31:09<42:56,  5.90it/s]

 50%|████▉     | 14990/30196 [31:09<33:50,  7.49it/s]

 50%|████▉     | 14992/30196 [31:09<30:15,  8.37it/s]

 50%|████▉     | 14993/30196 [31:09<31:42,  7.99it/s]

 50%|████▉     | 14995/30196 [31:09<27:25,  9.24it/s]

 50%|████▉     | 14997/30196 [31:10<26:23,  9.60it/s]

 50%|████▉     | 14998/30196 [31:10<28:14,  8.97it/s]

 50%|████▉     | 15000/30196 [31:10<24:50, 10.19it/s]

 50%|████▉     | 15002/30196 [31:10<25:20,  9.99it/s]

 50%|████▉     | 15004/30196 [31:10<23:00, 11.01it/s]

 50%|████▉     | 15006/30196 [31:10<23:02, 10.99it/s]

 50%|████▉     | 15008/30196 [31:11<26:49,  9.44it/s]

 50%|████▉     | 15009/30196 [31:11<27:00,  9.37it/s]

 50%|████▉     | 15010/30196 [31:11<30:08,  8.40it/s]

 50%|████▉     | 15011/30196 [31:11<32:51,  7.70it/s]

 50%|████▉     | 15012/30196 [31:11<32:56,  7.68it/s]

 50%|████▉     | 15014/30196 [31:12<32:45,  7.73it/s]

 50%|████▉     | 15015/30196 [31:12<35:22,  7.15it/s]

 50%|████▉     | 15017/30196 [31:12<32:45,  7.72it/s]

 50%|████▉     | 15018/30196 [31:12<33:04,  7.65it/s]

 50%|████▉     | 15020/30196 [31:12<31:15,  8.09it/s]

 50%|████▉     | 15021/30196 [31:12<30:28,  8.30it/s]

 50%|████▉     | 15023/30196 [31:13<26:43,  9.46it/s]

 50%|████▉     | 15024/30196 [31:13<33:30,  7.54it/s]

 50%|████▉     | 15026/30196 [31:13<27:51,  9.07it/s]

 50%|████▉     | 15028/30196 [31:13<25:13, 10.02it/s]

 50%|████▉     | 15030/30196 [31:13<24:38, 10.26it/s]

 50%|████▉     | 15032/30196 [31:14<25:24,  9.95it/s]

 50%|████▉     | 15034/30196 [31:14<26:34,  9.51it/s]

 50%|████▉     | 15035/30196 [31:14<27:57,  9.04it/s]

 50%|████▉     | 15037/30196 [31:14<26:05,  9.68it/s]

 50%|████▉     | 15038/30196 [31:14<27:24,  9.22it/s]

 50%|████▉     | 15041/30196 [31:14<21:18, 11.86it/s]

 50%|████▉     | 15043/30196 [31:15<22:26, 11.25it/s]

 50%|████▉     | 15045/30196 [31:15<20:52, 12.10it/s]

 50%|████▉     | 15047/30196 [31:15<24:41, 10.23it/s]

 50%|████▉     | 15049/30196 [31:15<22:40, 11.13it/s]

 50%|████▉     | 15051/30196 [31:15<23:24, 10.78it/s]

 50%|████▉     | 15053/30196 [31:16<29:13,  8.64it/s]

 50%|████▉     | 15054/30196 [31:16<30:19,  8.32it/s]

 50%|████▉     | 15055/30196 [31:16<31:06,  8.11it/s]

 50%|████▉     | 15056/30196 [31:17<58:32,  4.31it/s]

 50%|████▉     | 15058/30196 [31:17<46:28,  5.43it/s]

 50%|████▉     | 15059/30196 [31:17<44:24,  5.68it/s]

 50%|████▉     | 15060/30196 [31:17<42:19,  5.96it/s]

 50%|████▉     | 15061/30196 [31:17<38:21,  6.58it/s]

 50%|████▉     | 15062/30196 [31:17<37:37,  6.71it/s]

 50%|████▉     | 15064/30196 [31:18<33:52,  7.44it/s]

 50%|████▉     | 15066/30196 [31:18<27:44,  9.09it/s]

 50%|████▉     | 15067/30196 [31:18<30:53,  8.16it/s]

 50%|████▉     | 15069/30196 [31:18<41:34,  6.06it/s]

 50%|████▉     | 15070/30196 [31:18<38:19,  6.58it/s]

 50%|████▉     | 15072/30196 [31:19<39:13,  6.43it/s]

 50%|████▉     | 15073/30196 [31:19<36:49,  6.84it/s]

 50%|████▉     | 15075/30196 [31:19<35:21,  7.13it/s]

 50%|████▉     | 15076/30196 [31:19<35:07,  7.17it/s]

 50%|████▉     | 15077/30196 [31:19<33:24,  7.54it/s]

 50%|████▉     | 15078/30196 [31:20<43:58,  5.73it/s]

 50%|████▉     | 15079/30196 [31:20<39:25,  6.39it/s]

 50%|████▉     | 15080/30196 [31:20<35:52,  7.02it/s]

 50%|████▉     | 15081/30196 [31:20<37:45,  6.67it/s]

 50%|████▉     | 15082/30196 [31:20<38:50,  6.48it/s]

 50%|████▉     | 15084/30196 [31:20<34:19,  7.34it/s]

 50%|████▉     | 15085/30196 [31:21<38:45,  6.50it/s]

 50%|████▉     | 15087/30196 [31:21<36:41,  6.86it/s]

 50%|████▉     | 15088/30196 [31:21<38:01,  6.62it/s]

 50%|████▉     | 15090/30196 [31:21<32:52,  7.66it/s]

 50%|████▉     | 15092/30196 [31:21<28:27,  8.85it/s]

 50%|████▉     | 15094/30196 [31:22<30:08,  8.35it/s]

 50%|████▉     | 15095/30196 [31:22<34:25,  7.31it/s]

 50%|████▉     | 15097/30196 [31:22<35:41,  7.05it/s]

 50%|█████     | 15099/30196 [31:22<30:10,  8.34it/s]

 50%|█████     | 15100/30196 [31:23<33:02,  7.61it/s]

 50%|█████     | 15102/30196 [31:23<26:32,  9.48it/s]

 50%|█████     | 15104/30196 [31:23<29:21,  8.57it/s]

 50%|█████     | 15105/30196 [31:23<29:30,  8.52it/s]

 50%|█████     | 15107/30196 [31:23<29:35,  8.50it/s]

 50%|█████     | 15108/30196 [31:23<30:32,  8.24it/s]

 50%|█████     | 15109/30196 [31:24<33:53,  7.42it/s]

 50%|█████     | 15110/30196 [31:24<34:12,  7.35it/s]

 50%|█████     | 15112/30196 [31:24<27:57,  8.99it/s]

 50%|█████     | 15114/30196 [31:24<22:58, 10.94it/s]

 50%|█████     | 15116/30196 [31:24<28:54,  8.69it/s]

 50%|█████     | 15118/30196 [31:24<24:54, 10.09it/s]

 50%|█████     | 15120/30196 [31:25<27:40,  9.08it/s]

 50%|█████     | 15122/30196 [31:25<32:32,  7.72it/s]

 50%|█████     | 15123/30196 [31:25<34:25,  7.30it/s]

 50%|█████     | 15124/30196 [31:25<36:40,  6.85it/s]

 50%|█████     | 15125/30196 [31:26<34:35,  7.26it/s]

 50%|█████     | 15126/30196 [31:26<34:43,  7.23it/s]

 50%|█████     | 15127/30196 [31:26<39:13,  6.40it/s]

 50%|█████     | 15129/30196 [31:26<30:07,  8.34it/s]

 50%|█████     | 15130/30196 [31:26<31:19,  8.01it/s]

 50%|█████     | 15131/30196 [31:26<34:09,  7.35it/s]

 50%|█████     | 15132/30196 [31:27<34:28,  7.28it/s]

 50%|█████     | 15134/30196 [31:27<29:25,  8.53it/s]

 50%|█████     | 15135/30196 [31:27<32:13,  7.79it/s]

 50%|█████     | 15137/30196 [31:27<27:31,  9.12it/s]

 50%|█████     | 15138/30196 [31:27<28:52,  8.69it/s]

 50%|█████     | 15139/30196 [31:27<33:34,  7.47it/s]

 50%|█████     | 15140/30196 [31:28<36:31,  6.87it/s]

 50%|█████     | 15142/30196 [31:28<34:04,  7.36it/s]

 50%|█████     | 15144/30196 [31:28<30:42,  8.17it/s]

 50%|█████     | 15145/30196 [31:28<31:07,  8.06it/s]

 50%|█████     | 15146/30196 [31:28<34:15,  7.32it/s]

 50%|█████     | 15148/30196 [31:29<33:32,  7.48it/s]

 50%|█████     | 15149/30196 [31:29<33:18,  7.53it/s]

 50%|█████     | 15150/30196 [31:29<35:51,  6.99it/s]

 50%|█████     | 15151/30196 [31:29<36:08,  6.94it/s]

 50%|█████     | 15153/30196 [31:29<33:15,  7.54it/s]

 50%|█████     | 15154/30196 [31:29<31:54,  7.86it/s]

 50%|█████     | 15156/30196 [31:29<27:13,  9.21it/s]

 50%|█████     | 15158/30196 [31:30<24:11, 10.36it/s]

 50%|█████     | 15160/30196 [31:30<20:59, 11.94it/s]

 50%|█████     | 15162/30196 [31:30<25:01, 10.01it/s]

 50%|█████     | 15164/30196 [31:30<23:02, 10.88it/s]

 50%|█████     | 15166/30196 [31:30<24:10, 10.36it/s]

 50%|█████     | 15168/30196 [31:31<24:11, 10.36it/s]

 50%|█████     | 15170/30196 [31:31<25:32,  9.80it/s]

 50%|█████     | 15172/30196 [31:31<24:44, 10.12it/s]

 50%|█████     | 15174/30196 [31:31<24:33, 10.20it/s]

 50%|█████     | 15176/30196 [31:31<24:33, 10.19it/s]

 50%|█████     | 15178/30196 [31:32<27:30,  9.10it/s]

 50%|█████     | 15179/30196 [31:32<36:28,  6.86it/s]

 50%|█████     | 15180/30196 [31:32<43:35,  5.74it/s]

 50%|█████     | 15181/30196 [31:32<46:43,  5.35it/s]

 50%|█████     | 15183/30196 [31:33<36:23,  6.88it/s]

 50%|█████     | 15184/30196 [31:33<35:59,  6.95it/s]

 50%|█████     | 15185/30196 [31:33<36:06,  6.93it/s]

 50%|█████     | 15187/30196 [31:33<35:43,  7.00it/s]

 50%|█████     | 15188/30196 [31:33<33:51,  7.39it/s]

 50%|█████     | 15190/30196 [31:34<38:52,  6.43it/s]

 50%|█████     | 15191/30196 [31:34<37:30,  6.67it/s]

 50%|█████     | 15192/30196 [31:34<35:44,  7.00it/s]

 50%|█████     | 15193/30196 [31:34<33:21,  7.49it/s]

 50%|█████     | 15194/30196 [31:34<39:32,  6.32it/s]

 50%|█████     | 15196/30196 [31:34<28:41,  8.71it/s]

 50%|█████     | 15198/30196 [31:35<26:20,  9.49it/s]

 50%|█████     | 15200/30196 [31:35<37:16,  6.70it/s]

 50%|█████     | 15201/30196 [31:35<35:18,  7.08it/s]

 50%|█████     | 15203/30196 [31:35<34:17,  7.29it/s]

 50%|█████     | 15205/30196 [31:36<35:06,  7.12it/s]

 50%|█████     | 15207/30196 [31:36<28:04,  8.90it/s]

 50%|█████     | 15209/30196 [31:36<25:07,  9.94it/s]

 50%|█████     | 15211/30196 [31:36<26:35,  9.39it/s]

 50%|█████     | 15213/30196 [31:36<29:04,  8.59it/s]

 50%|█████     | 15215/30196 [31:37<25:08,  9.93it/s]

 50%|█████     | 15217/30196 [31:37<29:23,  8.50it/s]

 50%|█████     | 15218/30196 [31:37<30:05,  8.29it/s]

 50%|█████     | 15220/30196 [31:37<35:59,  6.94it/s]

 50%|█████     | 15222/30196 [31:38<30:03,  8.30it/s]

 50%|█████     | 15223/30196 [31:38<30:31,  8.18it/s]

 50%|█████     | 15224/30196 [31:38<29:52,  8.35it/s]

 50%|█████     | 15226/30196 [31:38<29:55,  8.34it/s]

 50%|█████     | 15227/30196 [31:38<32:21,  7.71it/s]

 50%|█████     | 15228/30196 [31:38<30:54,  8.07it/s]

 50%|█████     | 15229/30196 [31:38<34:18,  7.27it/s]

 50%|█████     | 15230/30196 [31:39<34:53,  7.15it/s]

 50%|█████     | 15231/30196 [31:39<37:42,  6.62it/s]

 50%|█████     | 15232/30196 [31:39<39:32,  6.31it/s]

 50%|█████     | 15234/30196 [31:39<28:42,  8.69it/s]

 50%|█████     | 15235/30196 [31:39<31:41,  7.87it/s]

 50%|█████     | 15237/30196 [31:39<26:15,  9.49it/s]

 50%|█████     | 15238/30196 [31:40<28:34,  8.73it/s]

 50%|█████     | 15240/30196 [31:40<29:53,  8.34it/s]

 50%|█████     | 15241/30196 [31:40<31:02,  8.03it/s]

 50%|█████     | 15242/30196 [31:40<30:06,  8.28it/s]

 50%|█████     | 15243/30196 [31:40<30:43,  8.11it/s]

 50%|█████     | 15245/30196 [31:40<26:43,  9.32it/s]

 50%|█████     | 15246/30196 [31:41<28:18,  8.80it/s]

 50%|█████     | 15248/30196 [31:41<25:56,  9.61it/s]

 51%|█████     | 15249/30196 [31:41<25:56,  9.60it/s]

 51%|█████     | 15250/30196 [31:41<26:00,  9.58it/s]

 51%|█████     | 15252/30196 [31:41<22:39, 10.99it/s]

 51%|█████     | 15254/30196 [31:41<25:20,  9.83it/s]

 51%|█████     | 15256/30196 [31:42<28:10,  8.84it/s]

 51%|█████     | 15258/30196 [31:42<26:16,  9.47it/s]

 51%|█████     | 15259/30196 [31:42<31:30,  7.90it/s]

 51%|█████     | 15260/30196 [31:42<36:13,  6.87it/s]

 51%|█████     | 15261/30196 [31:42<37:25,  6.65it/s]

 51%|█████     | 15262/30196 [31:42<37:11,  6.69it/s]

 51%|█████     | 15263/30196 [31:43<34:35,  7.20it/s]

 51%|█████     | 15264/30196 [31:43<35:07,  7.09it/s]

 51%|█████     | 15265/30196 [31:43<32:57,  7.55it/s]

 51%|█████     | 15267/30196 [31:43<24:53, 10.00it/s]

 51%|█████     | 15269/30196 [31:43<29:31,  8.43it/s]

 51%|█████     | 15270/30196 [31:43<29:02,  8.57it/s]

 51%|█████     | 15272/30196 [31:44<29:51,  8.33it/s]

 51%|█████     | 15274/30196 [31:44<25:02,  9.93it/s]

 51%|█████     | 15276/30196 [31:44<25:22,  9.80it/s]

 51%|█████     | 15278/30196 [31:44<28:36,  8.69it/s]

 51%|█████     | 15280/30196 [31:44<24:52,  9.99it/s]

 51%|█████     | 15282/30196 [31:45<23:39, 10.51it/s]

 51%|█████     | 15284/30196 [31:45<22:15, 11.17it/s]

 51%|█████     | 15286/30196 [31:45<22:37, 10.98it/s]

 51%|█████     | 15288/30196 [31:45<21:08, 11.75it/s]

 51%|█████     | 15290/30196 [31:45<18:46, 13.23it/s]

 51%|█████     | 15292/30196 [31:45<23:13, 10.70it/s]

 51%|█████     | 15294/30196 [31:46<24:45, 10.03it/s]

 51%|█████     | 15296/30196 [31:47<50:28,  4.92it/s]

 51%|█████     | 15298/30196 [31:47<40:39,  6.11it/s]

 51%|█████     | 15300/30196 [31:47<46:44,  5.31it/s]

 51%|█████     | 15301/30196 [31:47<44:13,  5.61it/s]

 51%|█████     | 15303/30196 [31:47<36:06,  6.87it/s]

 51%|█████     | 15304/30196 [31:48<37:44,  6.58it/s]

 51%|█████     | 15305/30196 [31:48<37:11,  6.67it/s]

 51%|█████     | 15306/30196 [31:48<37:03,  6.70it/s]

 51%|█████     | 15307/30196 [31:48<38:37,  6.43it/s]

 51%|█████     | 15309/30196 [31:48<30:04,  8.25it/s]

 51%|█████     | 15312/30196 [31:48<23:54, 10.38it/s]

 51%|█████     | 15314/30196 [31:49<28:10,  8.80it/s]

 51%|█████     | 15315/30196 [31:49<28:57,  8.56it/s]

 51%|█████     | 15317/30196 [31:49<30:22,  8.16it/s]

 51%|█████     | 15319/30196 [31:50<53:25,  4.64it/s]

 51%|█████     | 15321/30196 [31:50<44:10,  5.61it/s]

 51%|█████     | 15322/30196 [31:50<42:26,  5.84it/s]

 51%|█████     | 15324/30196 [31:50<35:16,  7.03it/s]

 51%|█████     | 15325/30196 [31:51<36:28,  6.79it/s]

 51%|█████     | 15326/30196 [31:51<36:31,  6.79it/s]

 51%|█████     | 15328/30196 [31:51<29:35,  8.37it/s]

 51%|█████     | 15330/30196 [31:51<32:10,  7.70it/s]

 51%|█████     | 15332/30196 [31:51<27:29,  9.01it/s]

 51%|█████     | 15334/30196 [31:52<26:57,  9.19it/s]

 51%|█████     | 15335/30196 [31:52<28:27,  8.70it/s]

 51%|█████     | 15336/30196 [31:52<33:25,  7.41it/s]

 51%|█████     | 15337/30196 [31:52<33:12,  7.46it/s]

 51%|█████     | 15338/30196 [31:52<31:41,  7.81it/s]

 51%|█████     | 15340/30196 [31:52<25:19,  9.78it/s]

 51%|█████     | 15342/30196 [31:53<27:44,  8.93it/s]

 51%|█████     | 15343/30196 [31:53<31:20,  7.90it/s]

 51%|█████     | 15344/30196 [31:53<33:34,  7.37it/s]

 51%|█████     | 15345/30196 [31:53<32:02,  7.72it/s]

 51%|█████     | 15346/30196 [31:53<32:07,  7.70it/s]

 51%|█████     | 15347/30196 [31:53<32:11,  7.69it/s]

 51%|█████     | 15349/30196 [31:53<27:32,  8.99it/s]

 51%|█████     | 15351/30196 [31:54<22:39, 10.92it/s]

 51%|█████     | 15353/30196 [31:54<31:49,  7.77it/s]

 51%|█████     | 15354/30196 [31:54<30:54,  8.00it/s]

 51%|█████     | 15355/30196 [31:54<32:05,  7.71it/s]

 51%|█████     | 15356/30196 [31:54<33:03,  7.48it/s]

 51%|█████     | 15358/30196 [31:55<26:27,  9.35it/s]

 51%|█████     | 15360/30196 [31:55<21:53, 11.30it/s]

 51%|█████     | 15362/30196 [31:55<24:19, 10.16it/s]

 51%|█████     | 15364/30196 [31:55<23:31, 10.51it/s]

 51%|█████     | 15366/30196 [31:55<25:19,  9.76it/s]

 51%|█████     | 15368/30196 [31:56<27:04,  9.13it/s]

 51%|█████     | 15369/30196 [31:56<28:47,  8.58it/s]

 51%|█████     | 15371/30196 [31:56<30:16,  8.16it/s]

 51%|█████     | 15372/30196 [31:56<29:41,  8.32it/s]

 51%|█████     | 15374/30196 [31:56<32:26,  7.62it/s]

 51%|█████     | 15375/30196 [31:57<37:17,  6.62it/s]

 51%|█████     | 15376/30196 [31:57<35:31,  6.95it/s]

 51%|█████     | 15378/30196 [31:57<33:14,  7.43it/s]

 51%|█████     | 15379/30196 [31:57<34:52,  7.08it/s]

 51%|█████     | 15381/30196 [31:57<32:42,  7.55it/s]

 51%|█████     | 15383/30196 [31:58<46:13,  5.34it/s]

 51%|█████     | 15385/30196 [31:58<39:15,  6.29it/s]

 51%|█████     | 15387/30196 [31:58<34:49,  7.09it/s]

 51%|█████     | 15388/30196 [31:58<34:48,  7.09it/s]

 51%|█████     | 15389/30196 [31:59<57:15,  4.31it/s]

 51%|█████     | 15390/30196 [31:59<53:32,  4.61it/s]

 51%|█████     | 15391/30196 [31:59<56:06,  4.40it/s]

 51%|█████     | 15392/30196 [32:00<48:30,  5.09it/s]

 51%|█████     | 15393/30196 [32:00<42:43,  5.77it/s]

 51%|█████     | 15394/30196 [32:00<42:49,  5.76it/s]

 51%|█████     | 15396/30196 [32:00<38:34,  6.39it/s]

 51%|█████     | 15399/30196 [32:00<28:47,  8.57it/s]

 51%|█████     | 15400/30196 [32:01<31:02,  7.94it/s]

 51%|█████     | 15401/30196 [32:01<31:51,  7.74it/s]

 51%|█████     | 15402/30196 [32:01<34:39,  7.11it/s]

 51%|█████     | 15404/30196 [32:01<28:08,  8.76it/s]

 51%|█████     | 15406/30196 [32:01<23:36, 10.44it/s]

 51%|█████     | 15408/30196 [32:01<26:45,  9.21it/s]

 51%|█████     | 15410/30196 [32:02<26:28,  9.31it/s]

 51%|█████     | 15412/30196 [32:02<25:23,  9.70it/s]

 51%|█████     | 15414/30196 [32:02<24:26, 10.08it/s]

 51%|█████     | 15416/30196 [32:02<27:25,  8.98it/s]

 51%|█████     | 15417/30196 [32:02<28:42,  8.58it/s]

 51%|█████     | 15418/30196 [32:03<30:16,  8.14it/s]

 51%|█████     | 15419/30196 [32:03<39:06,  6.30it/s]

 51%|█████     | 15420/30196 [32:03<38:02,  6.48it/s]

 51%|█████     | 15421/30196 [32:03<35:13,  6.99it/s]

 51%|█████     | 15422/30196 [32:03<33:00,  7.46it/s]

 51%|█████     | 15423/30196 [32:03<35:40,  6.90it/s]

 51%|█████     | 15424/30196 [32:04<34:56,  7.04it/s]

 51%|█████     | 15425/30196 [32:04<34:25,  7.15it/s]

 51%|█████     | 15427/30196 [32:04<32:17,  7.62it/s]

 51%|█████     | 15428/30196 [32:04<34:47,  7.07it/s]

 51%|█████     | 15429/30196 [32:04<36:37,  6.72it/s]

 51%|█████     | 15430/30196 [32:04<33:43,  7.30it/s]

 51%|█████     | 15431/30196 [32:04<32:33,  7.56it/s]

 51%|█████     | 15433/30196 [32:05<26:04,  9.44it/s]

 51%|█████     | 15435/30196 [32:05<24:38,  9.98it/s]

 51%|█████     | 15437/30196 [32:05<32:55,  7.47it/s]

 51%|█████     | 15438/30196 [32:05<34:36,  7.11it/s]

 51%|█████     | 15440/30196 [32:05<26:27,  9.30it/s]

 51%|█████     | 15442/30196 [32:06<28:13,  8.71it/s]

 51%|█████     | 15444/30196 [32:06<29:31,  8.33it/s]

 51%|█████     | 15446/30196 [32:06<30:32,  8.05it/s]

 51%|█████     | 15448/30196 [32:06<30:02,  8.18it/s]

 51%|█████     | 15449/30196 [32:07<30:55,  7.95it/s]

 51%|█████     | 15451/30196 [32:07<31:48,  7.72it/s]

 51%|█████     | 15452/30196 [32:07<32:21,  7.59it/s]

 51%|█████     | 15454/30196 [32:07<27:21,  8.98it/s]

 51%|█████     | 15456/30196 [32:07<24:57,  9.84it/s]

 51%|█████     | 15458/30196 [32:07<22:46, 10.78it/s]

 51%|█████     | 15460/30196 [32:08<19:47, 12.41it/s]

 51%|█████     | 15462/30196 [32:08<25:20,  9.69it/s]

 51%|█████     | 15464/30196 [32:08<23:29, 10.45it/s]

 51%|█████     | 15466/30196 [32:08<23:28, 10.46it/s]

 51%|█████     | 15468/30196 [32:09<27:21,  8.97it/s]

 51%|█████     | 15469/30196 [32:09<28:54,  8.49it/s]

 51%|█████     | 15471/30196 [32:09<36:40,  6.69it/s]

 51%|█████     | 15472/30196 [32:09<37:49,  6.49it/s]

 51%|█████     | 15473/30196 [32:09<35:12,  6.97it/s]

 51%|█████     | 15474/30196 [32:10<36:57,  6.64it/s]

 51%|█████     | 15475/30196 [32:10<36:02,  6.81it/s]

 51%|█████▏    | 15477/30196 [32:10<26:49,  9.15it/s]

 51%|█████▏    | 15479/30196 [32:10<32:25,  7.57it/s]

 51%|█████▏    | 15481/30196 [32:10<27:24,  8.95it/s]

 51%|█████▏    | 15483/30196 [32:11<27:04,  9.06it/s]

 51%|█████▏    | 15485/30196 [32:11<27:45,  8.83it/s]

 51%|█████▏    | 15487/30196 [32:11<24:14, 10.11it/s]

 51%|█████▏    | 15489/30196 [32:11<24:14, 10.11it/s]

 51%|█████▏    | 15491/30196 [32:11<27:05,  9.05it/s]

 51%|█████▏    | 15492/30196 [32:12<29:29,  8.31it/s]

 51%|█████▏    | 15493/30196 [32:12<35:56,  6.82it/s]

 51%|█████▏    | 15494/30196 [32:12<35:15,  6.95it/s]

 51%|█████▏    | 15495/30196 [32:12<35:02,  6.99it/s]

 51%|█████▏    | 15496/30196 [32:12<36:33,  6.70it/s]

 51%|█████▏    | 15497/30196 [32:12<40:23,  6.07it/s]

 51%|█████▏    | 15499/30196 [32:13<30:39,  7.99it/s]

 51%|█████▏    | 15500/30196 [32:13<30:58,  7.91it/s]

 51%|█████▏    | 15502/30196 [32:13<24:56,  9.82it/s]

 51%|█████▏    | 15504/30196 [32:13<30:01,  8.16it/s]

 51%|█████▏    | 15505/30196 [32:13<29:05,  8.42it/s]

 51%|█████▏    | 15507/30196 [32:13<26:19,  9.30it/s]

 51%|█████▏    | 15508/30196 [32:14<26:26,  9.26it/s]

 51%|█████▏    | 15510/30196 [32:14<23:49, 10.27it/s]

 51%|█████▏    | 15512/30196 [32:14<27:06,  9.03it/s]

 51%|█████▏    | 15513/30196 [32:14<28:25,  8.61it/s]

 51%|█████▏    | 15514/30196 [32:14<28:05,  8.71it/s]

 51%|█████▏    | 15515/30196 [32:14<29:14,  8.37it/s]

 51%|█████▏    | 15517/30196 [32:15<28:07,  8.70it/s]

 51%|█████▏    | 15519/30196 [32:15<27:52,  8.77it/s]

 51%|█████▏    | 15520/30196 [32:15<28:45,  8.51it/s]

 51%|█████▏    | 15521/30196 [32:15<31:27,  7.78it/s]

 51%|█████▏    | 15522/30196 [32:15<32:35,  7.50it/s]

 51%|█████▏    | 15523/30196 [32:15<35:12,  6.95it/s]

 51%|█████▏    | 15524/30196 [32:16<35:14,  6.94it/s]

 51%|█████▏    | 15525/30196 [32:16<32:34,  7.51it/s]

 51%|█████▏    | 15526/30196 [32:16<32:20,  7.56it/s]

 51%|█████▏    | 15527/30196 [32:16<34:50,  7.02it/s]

 51%|█████▏    | 15529/30196 [32:16<27:05,  9.02it/s]

 51%|█████▏    | 15531/30196 [32:16<22:26, 10.89it/s]

 51%|█████▏    | 15533/30196 [32:17<27:57,  8.74it/s]

 51%|█████▏    | 15534/30196 [32:17<30:53,  7.91it/s]

 51%|█████▏    | 15536/30196 [32:17<25:36,  9.54it/s]

 51%|█████▏    | 15538/30196 [32:17<29:38,  8.24it/s]

 51%|█████▏    | 15539/30196 [32:17<31:57,  7.64it/s]

 51%|█████▏    | 15541/30196 [32:17<25:37,  9.53it/s]

 51%|█████▏    | 15543/30196 [32:18<25:30,  9.58it/s]

 51%|█████▏    | 15545/30196 [32:18<23:01, 10.60it/s]

 51%|█████▏    | 15547/30196 [32:19<59:21,  4.11it/s]

 51%|█████▏    | 15548/30196 [32:19<53:21,  4.58it/s]

 51%|█████▏    | 15550/30196 [32:19<41:08,  5.93it/s]

 52%|█████▏    | 15552/30196 [32:20<42:43,  5.71it/s]

 52%|█████▏    | 15553/30196 [32:20<41:27,  5.89it/s]

 52%|█████▏    | 15554/30196 [32:20<38:20,  6.37it/s]

 52%|█████▏    | 15556/30196 [32:20<33:20,  7.32it/s]

 52%|█████▏    | 15557/30196 [32:20<31:55,  7.64it/s]

 52%|█████▏    | 15558/30196 [32:20<31:57,  7.63it/s]

 52%|█████▏    | 15560/30196 [32:21<32:57,  7.40it/s]

 52%|█████▏    | 15561/30196 [32:21<33:38,  7.25it/s]

 52%|█████▏    | 15563/30196 [32:21<26:55,  9.06it/s]

 52%|█████▏    | 15564/30196 [32:21<30:13,  8.07it/s]

 52%|█████▏    | 15566/30196 [32:21<24:21, 10.01it/s]

 52%|█████▏    | 15568/30196 [32:21<26:55,  9.05it/s]

 52%|█████▏    | 15570/30196 [32:22<25:29,  9.56it/s]

 52%|█████▏    | 15572/30196 [32:22<32:08,  7.58it/s]

 52%|█████▏    | 15573/30196 [32:22<32:04,  7.60it/s]

 52%|█████▏    | 15575/30196 [32:22<26:01,  9.36it/s]

 52%|█████▏    | 15577/30196 [32:22<26:26,  9.21it/s]

 52%|█████▏    | 15579/30196 [32:23<26:47,  9.09it/s]

 52%|█████▏    | 15580/30196 [32:23<36:10,  6.73it/s]

 52%|█████▏    | 15582/30196 [32:23<30:29,  7.99it/s]

 52%|█████▏    | 15583/30196 [32:23<30:46,  7.91it/s]

 52%|█████▏    | 15585/30196 [32:23<24:05, 10.11it/s]

 52%|█████▏    | 15587/30196 [32:24<28:31,  8.53it/s]

 52%|█████▏    | 15589/30196 [32:24<24:34,  9.91it/s]

 52%|█████▏    | 15591/30196 [32:24<21:50, 11.15it/s]

 52%|█████▏    | 15593/30196 [32:24<24:40,  9.86it/s]

 52%|█████▏    | 15595/30196 [32:24<28:28,  8.55it/s]

 52%|█████▏    | 15597/30196 [32:25<28:13,  8.62it/s]

 52%|█████▏    | 15599/30196 [32:25<24:54,  9.77it/s]

 52%|█████▏    | 15601/30196 [32:25<23:53, 10.18it/s]

 52%|█████▏    | 15603/30196 [32:25<26:09,  9.30it/s]

 52%|█████▏    | 15605/30196 [32:26<27:11,  8.94it/s]

 52%|█████▏    | 15606/30196 [32:26<28:25,  8.55it/s]

 52%|█████▏    | 15607/30196 [32:26<28:02,  8.67it/s]

 52%|█████▏    | 15608/30196 [32:26<27:45,  8.76it/s]

 52%|█████▏    | 15609/30196 [32:26<30:59,  7.85it/s]

 52%|█████▏    | 15611/30196 [32:26<31:14,  7.78it/s]

 52%|█████▏    | 15613/30196 [32:27<28:20,  8.57it/s]

 52%|█████▏    | 15615/30196 [32:27<23:37, 10.29it/s]

 52%|█████▏    | 15617/30196 [32:27<31:35,  7.69it/s]

 52%|█████▏    | 15619/30196 [32:27<25:55,  9.37it/s]

 52%|█████▏    | 15621/30196 [32:27<25:45,  9.43it/s]

 52%|█████▏    | 15623/30196 [32:28<29:27,  8.25it/s]

 52%|█████▏    | 15624/30196 [32:28<28:58,  8.38it/s]

 52%|█████▏    | 15625/30196 [32:28<31:19,  7.75it/s]

 52%|█████▏    | 15627/30196 [32:28<25:35,  9.49it/s]

 52%|█████▏    | 15629/30196 [32:28<25:51,  9.39it/s]

 52%|█████▏    | 15631/30196 [32:29<27:40,  8.77it/s]

 52%|█████▏    | 15632/30196 [32:29<29:37,  8.19it/s]

 52%|█████▏    | 15633/30196 [32:29<28:58,  8.37it/s]

 52%|█████▏    | 15635/30196 [32:29<26:49,  9.05it/s]

 52%|█████▏    | 15636/30196 [32:29<28:23,  8.55it/s]

 52%|█████▏    | 15637/30196 [32:29<29:45,  8.15it/s]

 52%|█████▏    | 15638/30196 [32:29<28:36,  8.48it/s]

 52%|█████▏    | 15639/30196 [32:30<30:54,  7.85it/s]

 52%|█████▏    | 15640/30196 [32:30<33:25,  7.26it/s]

 52%|█████▏    | 15642/30196 [32:30<27:11,  8.92it/s]

 52%|█████▏    | 15644/30196 [32:30<27:08,  8.93it/s]

 52%|█████▏    | 15646/30196 [32:30<25:25,  9.54it/s]

 52%|█████▏    | 15647/30196 [32:30<25:26,  9.53it/s]

 52%|█████▏    | 15648/30196 [32:30<25:20,  9.57it/s]

 52%|█████▏    | 15649/30196 [32:31<31:17,  7.75it/s]

 52%|█████▏    | 15650/30196 [32:31<56:20,  4.30it/s]

 52%|█████▏    | 15652/30196 [32:31<41:36,  5.83it/s]

 52%|█████▏    | 15653/30196 [32:32<39:14,  6.18it/s]

 52%|█████▏    | 15655/30196 [32:32<31:08,  7.78it/s]

 52%|█████▏    | 15656/30196 [32:32<31:30,  7.69it/s]

 52%|█████▏    | 15658/30196 [32:32<26:15,  9.23it/s]

 52%|█████▏    | 15660/30196 [32:32<26:24,  9.18it/s]

 52%|█████▏    | 15661/30196 [32:32<26:27,  9.15it/s]

 52%|█████▏    | 15663/30196 [32:33<30:31,  7.94it/s]

 52%|█████▏    | 15664/30196 [32:33<30:47,  7.87it/s]

 52%|█████▏    | 15666/30196 [32:33<25:29,  9.50it/s]

 52%|█████▏    | 15668/30196 [32:33<31:25,  7.70it/s]

 52%|█████▏    | 15669/30196 [32:33<31:26,  7.70it/s]

 52%|█████▏    | 15670/30196 [32:34<33:58,  7.13it/s]

 52%|█████▏    | 15672/30196 [32:34<29:01,  8.34it/s]

 52%|█████▏    | 15674/30196 [32:34<30:05,  8.04it/s]

 52%|█████▏    | 15675/30196 [32:34<32:48,  7.38it/s]

 52%|█████▏    | 15677/30196 [32:34<33:57,  7.13it/s]

 52%|█████▏    | 15678/30196 [32:35<34:19,  7.05it/s]

 52%|█████▏    | 15679/30196 [32:35<35:54,  6.74it/s]

 52%|█████▏    | 15680/30196 [32:35<35:44,  6.77it/s]

 52%|█████▏    | 15682/30196 [32:35<27:39,  8.75it/s]

 52%|█████▏    | 15684/30196 [32:35<29:56,  8.08it/s]

 52%|█████▏    | 15685/30196 [32:35<30:58,  7.81it/s]

 52%|█████▏    | 15687/30196 [32:36<29:13,  8.28it/s]

 52%|█████▏    | 15688/30196 [32:36<28:38,  8.44it/s]

 52%|█████▏    | 15689/30196 [32:36<30:14,  7.99it/s]

 52%|█████▏    | 15690/30196 [32:36<32:43,  7.39it/s]

 52%|█████▏    | 15691/30196 [32:36<33:25,  7.23it/s]

 52%|█████▏    | 15693/30196 [32:36<30:43,  7.87it/s]

 52%|█████▏    | 15694/30196 [32:37<31:28,  7.68it/s]

 52%|█████▏    | 15695/30196 [32:37<36:55,  6.55it/s]

 52%|█████▏    | 15696/30196 [32:37<38:11,  6.33it/s]

 52%|█████▏    | 15697/30196 [32:37<34:44,  6.96it/s]

 52%|█████▏    | 15699/30196 [32:37<31:09,  7.75it/s]

 52%|█████▏    | 15701/30196 [32:38<27:49,  8.68it/s]

 52%|█████▏    | 15703/30196 [32:38<26:04,  9.26it/s]

 52%|█████▏    | 15704/30196 [32:38<27:31,  8.78it/s]

 52%|█████▏    | 15706/30196 [32:38<22:19, 10.81it/s]

 52%|█████▏    | 15708/30196 [32:38<22:05, 10.93it/s]

 52%|█████▏    | 15710/30196 [32:38<24:21,  9.91it/s]

 52%|█████▏    | 15712/30196 [32:39<28:17,  8.53it/s]

 52%|█████▏    | 15713/30196 [32:39<29:07,  8.29it/s]

 52%|█████▏    | 15714/30196 [32:39<31:47,  7.59it/s]

 52%|█████▏    | 15715/30196 [32:39<33:37,  7.18it/s]

 52%|█████▏    | 15716/30196 [32:39<35:26,  6.81it/s]

 52%|█████▏    | 15717/30196 [32:39<36:56,  6.53it/s]

 52%|█████▏    | 15718/30196 [32:40<35:41,  6.76it/s]

 52%|█████▏    | 15719/30196 [32:40<34:50,  6.93it/s]

 52%|█████▏    | 15721/30196 [32:40<30:04,  8.02it/s]

 52%|█████▏    | 15723/30196 [32:40<28:45,  8.39it/s]

 52%|█████▏    | 15724/30196 [32:40<29:22,  8.21it/s]

 52%|█████▏    | 15725/30196 [32:40<30:48,  7.83it/s]

 52%|█████▏    | 15727/30196 [32:41<24:05, 10.01it/s]

 52%|█████▏    | 15729/30196 [32:41<32:53,  7.33it/s]

 52%|█████▏    | 15731/30196 [32:41<32:06,  7.51it/s]

 52%|█████▏    | 15732/30196 [32:41<33:47,  7.13it/s]

 52%|█████▏    | 15733/30196 [32:42<33:22,  7.22it/s]

 52%|█████▏    | 15734/30196 [32:42<32:57,  7.31it/s]

 52%|█████▏    | 15735/30196 [32:42<34:53,  6.91it/s]

 52%|█████▏    | 15736/30196 [32:42<32:37,  7.39it/s]

 52%|█████▏    | 15737/30196 [32:42<31:35,  7.63it/s]

 52%|█████▏    | 15738/30196 [32:42<34:32,  6.98it/s]

 52%|█████▏    | 15739/30196 [32:42<36:22,  6.62it/s]

 52%|█████▏    | 15740/30196 [32:43<37:23,  6.44it/s]

 52%|█████▏    | 15741/30196 [32:43<38:23,  6.28it/s]

 52%|█████▏    | 15743/30196 [32:43<27:34,  8.74it/s]

 52%|█████▏    | 15744/30196 [32:43<31:18,  7.69it/s]

 52%|█████▏    | 15745/30196 [32:43<34:00,  7.08it/s]

 52%|█████▏    | 15747/30196 [32:43<29:48,  8.08it/s]

 52%|█████▏    | 15748/30196 [32:44<43:38,  5.52it/s]

 52%|█████▏    | 15749/30196 [32:44<47:56,  5.02it/s]

 52%|█████▏    | 15750/30196 [32:44<42:07,  5.72it/s]

 52%|█████▏    | 15751/30196 [32:44<37:51,  6.36it/s]

 52%|█████▏    | 15752/30196 [32:44<36:47,  6.54it/s]

 52%|█████▏    | 15753/30196 [32:45<37:35,  6.40it/s]

 52%|█████▏    | 15754/30196 [32:45<36:32,  6.59it/s]

 52%|█████▏    | 15755/30196 [32:45<35:22,  6.80it/s]

 52%|█████▏    | 15756/30196 [32:45<36:57,  6.51it/s]

 52%|█████▏    | 15758/30196 [32:45<28:04,  8.57it/s]

 52%|█████▏    | 15760/30196 [32:45<26:03,  9.23it/s]

 52%|█████▏    | 15761/30196 [32:45<27:14,  8.83it/s]

 52%|█████▏    | 15764/30196 [32:46<22:32, 10.67it/s]

 52%|█████▏    | 15766/30196 [32:46<23:41, 10.15it/s]

 52%|█████▏    | 15768/30196 [32:46<27:10,  8.85it/s]

 52%|█████▏    | 15769/30196 [32:46<27:53,  8.62it/s]

 52%|█████▏    | 15770/30196 [32:46<29:23,  8.18it/s]

 52%|█████▏    | 15771/30196 [32:47<32:00,  7.51it/s]

 52%|█████▏    | 15772/30196 [32:47<31:14,  7.70it/s]

 52%|█████▏    | 15774/30196 [32:47<32:51,  7.31it/s]

 52%|█████▏    | 15775/30196 [32:47<32:32,  7.39it/s]

 52%|█████▏    | 15776/30196 [32:47<32:29,  7.40it/s]

 52%|█████▏    | 15777/30196 [32:47<34:19,  7.00it/s]

 52%|█████▏    | 15778/30196 [32:48<31:52,  7.54it/s]

 52%|█████▏    | 15779/30196 [32:48<38:21,  6.26it/s]

 52%|█████▏    | 15780/30196 [32:48<41:55,  5.73it/s]

 52%|█████▏    | 15781/30196 [32:48<1:00:57,  3.94it/s]

 52%|█████▏    | 15782/30196 [32:49<1:08:57,  3.48it/s]

 52%|█████▏    | 15783/30196 [32:49<56:27,  4.25it/s]

 52%|█████▏    | 15784/30196 [32:49<55:57,  4.29it/s]

 52%|█████▏    | 15785/30196 [32:49<57:04,  4.21it/s]

 52%|█████▏    | 15786/30196 [32:50<52:14,  4.60it/s]

 52%|█████▏    | 15787/30196 [32:50<51:24,  4.67it/s]

 52%|█████▏    | 15788/30196 [32:50<46:39,  5.15it/s]

 52%|█████▏    | 15790/30196 [32:50<37:22,  6.42it/s]

 52%|█████▏    | 15791/30196 [32:50<34:22,  6.98it/s]

 52%|█████▏    | 15792/30196 [32:51<47:48,  5.02it/s]

 52%|█████▏    | 15794/30196 [32:51<38:55,  6.17it/s]

 52%|█████▏    | 15795/30196 [32:51<41:58,  5.72it/s]

 52%|█████▏    | 15796/30196 [32:51<41:46,  5.75it/s]

 52%|█████▏    | 15797/30196 [32:51<37:43,  6.36it/s]

 52%|█████▏    | 15798/30196 [32:51<34:14,  7.01it/s]

 52%|█████▏    | 15799/30196 [32:52<38:33,  6.22it/s]

 52%|█████▏    | 15800/30196 [32:52<39:32,  6.07it/s]

 52%|█████▏    | 15801/30196 [32:52<35:38,  6.73it/s]

 52%|█████▏    | 15802/30196 [32:52<45:07,  5.32it/s]

 52%|█████▏    | 15804/30196 [32:52<33:35,  7.14it/s]

 52%|█████▏    | 15806/30196 [32:53<26:45,  8.96it/s]

 52%|█████▏    | 15808/30196 [32:53<26:01,  9.21it/s]

 52%|█████▏    | 15810/30196 [32:53<21:17, 11.26it/s]

 52%|█████▏    | 15812/30196 [32:53<26:18,  9.11it/s]

 52%|█████▏    | 15814/30196 [32:54<31:51,  7.52it/s]

 52%|█████▏    | 15816/30196 [32:54<27:53,  8.59it/s]

 52%|█████▏    | 15818/30196 [32:54<32:10,  7.45it/s]

 52%|█████▏    | 15819/30196 [32:54<31:06,  7.70it/s]

 52%|█████▏    | 15821/30196 [32:54<28:35,  8.38it/s]

 52%|█████▏    | 15823/30196 [32:55<26:59,  8.87it/s]

 52%|█████▏    | 15825/30196 [32:55<26:35,  9.01it/s]

 52%|█████▏    | 15826/30196 [32:55<27:37,  8.67it/s]

 52%|█████▏    | 15828/30196 [32:55<29:21,  8.16it/s]

 52%|█████▏    | 15829/30196 [32:55<29:59,  7.98it/s]

 52%|█████▏    | 15831/30196 [32:56<31:44,  7.54it/s]

 52%|█████▏    | 15832/30196 [32:56<32:08,  7.45it/s]

 52%|█████▏    | 15833/30196 [32:56<32:12,  7.43it/s]

 52%|█████▏    | 15835/30196 [32:56<31:13,  7.66it/s]

 52%|█████▏    | 15836/30196 [32:56<29:59,  7.98it/s]

 52%|█████▏    | 15837/30196 [32:56<31:15,  7.65it/s]

 52%|█████▏    | 15838/30196 [32:57<31:45,  7.54it/s]

 52%|█████▏    | 15840/30196 [32:57<30:07,  7.94it/s]

 52%|█████▏    | 15841/30196 [32:57<30:29,  7.85it/s]

 52%|█████▏    | 15843/30196 [32:57<25:58,  9.21it/s]

 52%|█████▏    | 15845/30196 [32:57<21:38, 11.05it/s]

 52%|█████▏    | 15847/30196 [32:57<21:46, 10.98it/s]

 52%|█████▏    | 15849/30196 [32:57<20:42, 11.55it/s]

 52%|█████▏    | 15851/30196 [32:58<23:48, 10.04it/s]

 53%|█████▎    | 15853/30196 [32:58<21:53, 10.92it/s]

 53%|█████▎    | 15855/30196 [32:58<26:39,  8.97it/s]

 53%|█████▎    | 15857/30196 [32:58<23:51, 10.02it/s]

 53%|█████▎    | 15859/30196 [32:59<26:43,  8.94it/s]

 53%|█████▎    | 15861/30196 [32:59<25:53,  9.23it/s]

 53%|█████▎    | 15862/30196 [32:59<28:27,  8.39it/s]

 53%|█████▎    | 15864/30196 [32:59<24:09,  9.89it/s]

 53%|█████▎    | 15866/30196 [32:59<22:32, 10.59it/s]

 53%|█████▎    | 15868/30196 [33:00<25:15,  9.45it/s]

 53%|█████▎    | 15870/30196 [33:00<24:04,  9.92it/s]

 53%|█████▎    | 15872/30196 [33:00<26:17,  9.08it/s]

 53%|█████▎    | 15873/30196 [33:00<27:23,  8.72it/s]

 53%|█████▎    | 15875/30196 [33:00<27:35,  8.65it/s]

 53%|█████▎    | 15877/30196 [33:01<24:58,  9.55it/s]

 53%|█████▎    | 15879/30196 [33:01<21:50, 10.92it/s]

 53%|█████▎    | 15881/30196 [33:01<22:58, 10.39it/s]

 53%|█████▎    | 15883/30196 [33:01<24:33,  9.71it/s]

 53%|█████▎    | 15885/30196 [33:01<24:11,  9.86it/s]

 53%|█████▎    | 15887/30196 [33:02<24:55,  9.56it/s]

 53%|█████▎    | 15889/30196 [33:02<22:11, 10.75it/s]

 53%|█████▎    | 15891/30196 [33:02<22:28, 10.61it/s]

 53%|█████▎    | 15893/30196 [33:02<29:52,  7.98it/s]

 53%|█████▎    | 15894/30196 [33:03<42:00,  5.67it/s]

 53%|█████▎    | 15895/30196 [33:03<38:51,  6.13it/s]

 53%|█████▎    | 15896/30196 [33:03<37:20,  6.38it/s]

 53%|█████▎    | 15898/30196 [33:03<40:24,  5.90it/s]

 53%|█████▎    | 15899/30196 [33:04<47:48,  4.98it/s]

 53%|█████▎    | 15900/30196 [33:04<44:50,  5.31it/s]

 53%|█████▎    | 15902/30196 [33:04<35:08,  6.78it/s]

 53%|█████▎    | 15903/30196 [33:04<32:51,  7.25it/s]

 53%|█████▎    | 15904/30196 [33:04<37:36,  6.33it/s]

 53%|█████▎    | 15906/30196 [33:04<27:52,  8.54it/s]

 53%|█████▎    | 15908/30196 [33:05<29:49,  7.98it/s]

 53%|█████▎    | 15910/30196 [33:05<26:42,  8.91it/s]

 53%|█████▎    | 15912/30196 [33:05<25:00,  9.52it/s]

 53%|█████▎    | 15914/30196 [33:05<24:18,  9.79it/s]

 53%|█████▎    | 15916/30196 [33:05<24:04,  9.88it/s]

 53%|█████▎    | 15918/30196 [33:06<23:29, 10.13it/s]

 53%|█████▎    | 15920/30196 [33:06<25:56,  9.17it/s]

 53%|█████▎    | 15922/30196 [33:06<22:26, 10.60it/s]

 53%|█████▎    | 15924/30196 [33:06<25:24,  9.36it/s]

 53%|█████▎    | 15926/30196 [33:06<21:37, 11.00it/s]

 53%|█████▎    | 15928/30196 [33:07<22:58, 10.35it/s]

 53%|█████▎    | 15930/30196 [33:07<26:55,  8.83it/s]

 53%|█████▎    | 15932/30196 [33:07<25:41,  9.25it/s]

 53%|█████▎    | 15934/30196 [33:07<21:50, 10.89it/s]

 53%|█████▎    | 15936/30196 [33:08<27:56,  8.51it/s]

 53%|█████▎    | 15938/30196 [33:08<28:07,  8.45it/s]

 53%|█████▎    | 15939/30196 [33:08<28:36,  8.31it/s]

 53%|█████▎    | 15940/30196 [33:08<31:07,  7.63it/s]

 53%|█████▎    | 15941/30196 [33:08<30:58,  7.67it/s]

 53%|█████▎    | 15943/30196 [33:08<28:28,  8.34it/s]

 53%|█████▎    | 15945/30196 [33:09<26:01,  9.13it/s]

 53%|█████▎    | 15947/30196 [33:09<26:06,  9.10it/s]

 53%|█████▎    | 15948/30196 [33:09<27:50,  8.53it/s]

 53%|█████▎    | 15950/30196 [33:09<27:02,  8.78it/s]

 53%|█████▎    | 15951/30196 [33:09<28:21,  8.37it/s]

 53%|█████▎    | 15952/30196 [33:10<32:55,  7.21it/s]

 53%|█████▎    | 15953/30196 [33:10<31:17,  7.58it/s]

 53%|█████▎    | 15954/30196 [33:10<38:28,  6.17it/s]

 53%|█████▎    | 15955/30196 [33:10<35:10,  6.75it/s]

 53%|█████▎    | 15956/30196 [33:10<37:15,  6.37it/s]

 53%|█████▎    | 15958/30196 [33:10<29:41,  7.99it/s]

 53%|█████▎    | 15960/30196 [33:11<27:45,  8.55it/s]

 53%|█████▎    | 15961/30196 [33:11<58:55,  4.03it/s]

 53%|█████▎    | 15962/30196 [33:11<55:02,  4.31it/s]

 53%|█████▎    | 15963/30196 [33:12<47:26,  5.00it/s]

 53%|█████▎    | 15964/30196 [33:12<41:47,  5.68it/s]

 53%|█████▎    | 15965/30196 [33:12<37:11,  6.38it/s]

 53%|█████▎    | 15966/30196 [33:12<36:34,  6.48it/s]

 53%|█████▎    | 15967/30196 [33:12<41:36,  5.70it/s]

 53%|█████▎    | 15969/30196 [33:12<34:11,  6.93it/s]

 53%|█████▎    | 15971/30196 [33:13<30:08,  7.87it/s]

 53%|█████▎    | 15972/30196 [33:13<28:57,  8.19it/s]

 53%|█████▎    | 15973/30196 [33:13<27:59,  8.47it/s]

 53%|█████▎    | 15975/30196 [33:13<27:08,  8.73it/s]

 53%|█████▎    | 15977/30196 [33:13<25:40,  9.23it/s]

 53%|█████▎    | 15979/30196 [33:13<25:28,  9.30it/s]

 53%|█████▎    | 15981/30196 [33:14<34:28,  6.87it/s]

 53%|█████▎    | 15982/30196 [33:14<33:58,  6.97it/s]

 53%|█████▎    | 15984/30196 [33:14<26:13,  9.03it/s]

 53%|█████▎    | 15986/30196 [33:14<26:10,  9.05it/s]

 53%|█████▎    | 15988/30196 [33:14<23:49,  9.94it/s]

 53%|█████▎    | 15990/30196 [33:15<23:19, 10.15it/s]

 53%|█████▎    | 15992/30196 [33:15<36:14,  6.53it/s]

 53%|█████▎    | 15993/30196 [33:15<35:12,  6.72it/s]

 53%|█████▎    | 15995/30196 [33:16<32:04,  7.38it/s]

 53%|█████▎    | 15996/30196 [33:16<30:51,  7.67it/s]

 53%|█████▎    | 15998/30196 [33:16<25:53,  9.14it/s]

 53%|█████▎    | 16000/30196 [33:16<28:43,  8.24it/s]

 53%|█████▎    | 16001/30196 [33:16<29:21,  8.06it/s]

 53%|█████▎    | 16003/30196 [33:16<26:20,  8.98it/s]

 53%|█████▎    | 16005/30196 [33:17<23:52,  9.91it/s]

 53%|█████▎    | 16007/30196 [33:17<22:49, 10.36it/s]

 53%|█████▎    | 16009/30196 [33:17<26:05,  9.06it/s]

 53%|█████▎    | 16011/30196 [33:17<25:56,  9.12it/s]

 53%|█████▎    | 16012/30196 [33:17<26:23,  8.96it/s]

 53%|█████▎    | 16014/30196 [33:18<26:08,  9.04it/s]

 53%|█████▎    | 16015/30196 [33:18<27:05,  8.72it/s]

 53%|█████▎    | 16017/30196 [33:18<26:40,  8.86it/s]

 53%|█████▎    | 16018/30196 [33:18<34:20,  6.88it/s]

 53%|█████▎    | 16020/30196 [33:18<28:42,  8.23it/s]

 53%|█████▎    | 16021/30196 [33:18<29:15,  8.08it/s]

 53%|█████▎    | 16022/30196 [33:19<28:14,  8.37it/s]

 53%|█████▎    | 16024/30196 [33:19<25:44,  9.18it/s]

 53%|█████▎    | 16025/30196 [33:19<27:07,  8.70it/s]

 53%|█████▎    | 16027/30196 [33:19<27:57,  8.45it/s]

 53%|█████▎    | 16029/30196 [33:19<26:07,  9.04it/s]

 53%|█████▎    | 16031/30196 [33:20<25:19,  9.32it/s]

 53%|█████▎    | 16032/30196 [33:20<26:51,  8.79it/s]

 53%|█████▎    | 16033/30196 [33:20<28:09,  8.38it/s]

 53%|█████▎    | 16035/30196 [33:20<25:47,  9.15it/s]

 53%|█████▎    | 16036/30196 [33:20<28:50,  8.18it/s]

 53%|█████▎    | 16037/30196 [33:20<31:14,  7.56it/s]

 53%|█████▎    | 16038/30196 [33:21<33:15,  7.09it/s]

 53%|█████▎    | 16040/30196 [33:21<25:58,  9.08it/s]

 53%|█████▎    | 16042/30196 [33:21<22:06, 10.67it/s]

 53%|█████▎    | 16044/30196 [33:21<18:33, 12.71it/s]

 53%|█████▎    | 16046/30196 [33:21<21:41, 10.87it/s]

 53%|█████▎    | 16048/30196 [33:21<21:01, 11.21it/s]

 53%|█████▎    | 16050/30196 [33:21<18:52, 12.49it/s]

 53%|█████▎    | 16052/30196 [33:22<21:49, 10.80it/s]

 53%|█████▎    | 16054/30196 [33:22<23:01, 10.24it/s]

 53%|█████▎    | 16056/30196 [33:22<22:54, 10.29it/s]

 53%|█████▎    | 16058/30196 [33:22<26:28,  8.90it/s]

 53%|█████▎    | 16060/30196 [33:23<24:40,  9.55it/s]

 53%|█████▎    | 16062/30196 [33:23<25:57,  9.08it/s]

 53%|█████▎    | 16064/30196 [33:23<25:57,  9.08it/s]

 53%|█████▎    | 16065/30196 [33:24<1:01:28,  3.83it/s]

 53%|█████▎    | 16067/30196 [33:24<48:32,  4.85it/s]

 53%|█████▎    | 16068/30196 [33:24<43:55,  5.36it/s]

 53%|█████▎    | 16070/30196 [33:24<37:35,  6.26it/s]

 53%|█████▎    | 16072/30196 [33:25<30:33,  7.70it/s]

 53%|█████▎    | 16074/30196 [33:25<27:58,  8.41it/s]

 53%|█████▎    | 16076/30196 [33:25<28:28,  8.26it/s]

 53%|█████▎    | 16078/30196 [33:25<27:31,  8.55it/s]

 53%|█████▎    | 16079/30196 [33:25<28:15,  8.32it/s]

 53%|█████▎    | 16080/30196 [33:26<41:00,  5.74it/s]

 53%|█████▎    | 16082/30196 [33:26<36:00,  6.53it/s]

 53%|█████▎    | 16084/30196 [33:26<31:07,  7.56it/s]

 53%|█████▎    | 16085/30196 [33:26<29:49,  7.88it/s]

 53%|█████▎    | 16086/30196 [33:27<33:55,  6.93it/s]

 53%|█████▎    | 16088/30196 [33:27<30:28,  7.71it/s]

 53%|█████▎    | 16089/30196 [33:27<29:07,  8.07it/s]

 53%|█████▎    | 16091/30196 [33:27<26:55,  8.73it/s]

 53%|█████▎    | 16092/30196 [33:27<29:41,  7.92it/s]

 53%|█████▎    | 16094/30196 [33:27<25:07,  9.35it/s]

 53%|█████▎    | 16095/30196 [33:28<27:08,  8.66it/s]

 53%|█████▎    | 16096/30196 [33:28<28:15,  8.31it/s]

 53%|█████▎    | 16097/30196 [33:28<29:08,  8.06it/s]

 53%|█████▎    | 16099/30196 [33:28<24:36,  9.55it/s]

 53%|█████▎    | 16100/30196 [33:28<24:37,  9.54it/s]

 53%|█████▎    | 16102/30196 [33:28<20:31, 11.45it/s]

 53%|█████▎    | 16104/30196 [33:28<21:20, 11.00it/s]

 53%|█████▎    | 16106/30196 [33:29<20:41, 11.35it/s]

 53%|█████▎    | 16108/30196 [33:29<24:38,  9.53it/s]

 53%|█████▎    | 16110/30196 [33:29<29:26,  7.97it/s]

 53%|█████▎    | 16111/30196 [33:29<28:48,  8.15it/s]

 53%|█████▎    | 16112/30196 [33:29<29:59,  7.83it/s]

 53%|█████▎    | 16113/30196 [33:30<30:22,  7.73it/s]

 53%|█████▎    | 16115/30196 [33:30<26:58,  8.70it/s]

 53%|█████▎    | 16117/30196 [33:30<23:21, 10.04it/s]

 53%|█████▎    | 16119/30196 [33:30<32:32,  7.21it/s]

 53%|█████▎    | 16121/30196 [33:31<30:56,  7.58it/s]

 53%|█████▎    | 16122/30196 [33:31<31:06,  7.54it/s]

 53%|█████▎    | 16123/30196 [33:31<29:42,  7.89it/s]

 53%|█████▎    | 16125/30196 [33:31<29:38,  7.91it/s]

 53%|█████▎    | 16127/30196 [33:31<25:58,  9.03it/s]

 53%|█████▎    | 16129/30196 [33:31<23:21, 10.04it/s]

 53%|█████▎    | 16131/30196 [33:32<23:04, 10.16it/s]

 53%|█████▎    | 16133/30196 [33:32<22:37, 10.36it/s]

 53%|█████▎    | 16135/30196 [33:32<22:02, 10.63it/s]

 53%|█████▎    | 16137/30196 [33:32<28:59,  8.08it/s]

 53%|█████▎    | 16138/30196 [33:32<32:50,  7.13it/s]

 53%|█████▎    | 16139/30196 [33:33<39:05,  5.99it/s]

 53%|█████▎    | 16140/30196 [33:33<38:04,  6.15it/s]

 53%|█████▎    | 16141/30196 [33:33<54:15,  4.32it/s]

 53%|█████▎    | 16143/30196 [33:34<39:42,  5.90it/s]

 53%|█████▎    | 16145/30196 [33:34<31:14,  7.50it/s]

 53%|█████▎    | 16146/30196 [33:34<37:13,  6.29it/s]

 53%|█████▎    | 16147/30196 [33:34<34:20,  6.82it/s]

 53%|█████▎    | 16148/30196 [33:34<37:48,  6.19it/s]

 53%|█████▎    | 16149/30196 [33:34<36:34,  6.40it/s]

 53%|█████▎    | 16150/30196 [33:35<43:58,  5.32it/s]

 53%|█████▎    | 16151/30196 [33:35<42:29,  5.51it/s]

 53%|█████▎    | 16152/30196 [33:35<44:30,  5.26it/s]

 53%|█████▎    | 16154/30196 [33:35<35:49,  6.53it/s]

 54%|█████▎    | 16155/30196 [33:35<36:30,  6.41it/s]

 54%|█████▎    | 16156/30196 [33:36<1:32:10,  2.54it/s]

 54%|█████▎    | 16157/30196 [33:37<1:14:21,  3.15it/s]

 54%|█████▎    | 16159/30196 [33:37<51:11,  4.57it/s]

 54%|█████▎    | 16161/30196 [33:37<43:08,  5.42it/s]

 54%|█████▎    | 16163/30196 [33:37<33:59,  6.88it/s]

 54%|█████▎    | 16165/30196 [33:37<27:40,  8.45it/s]

 54%|█████▎    | 16167/30196 [33:38<31:51,  7.34it/s]

 54%|█████▎    | 16168/30196 [33:38<31:55,  7.32it/s]

 54%|█████▎    | 16170/30196 [33:38<29:43,  7.87it/s]

 54%|█████▎    | 16171/30196 [33:38<30:03,  7.78it/s]

 54%|█████▎    | 16173/30196 [33:38<24:05,  9.70it/s]

 54%|█████▎    | 16175/30196 [33:38<21:52, 10.69it/s]

 54%|█████▎    | 16177/30196 [33:39<26:22,  8.86it/s]

 54%|█████▎    | 16179/30196 [33:39<28:47,  8.12it/s]

 54%|█████▎    | 16180/30196 [33:39<29:16,  7.98it/s]

 54%|█████▎    | 16181/30196 [33:39<28:33,  8.18it/s]

 54%|█████▎    | 16183/30196 [33:40<35:38,  6.55it/s]

 54%|█████▎    | 16184/30196 [33:40<35:05,  6.66it/s]

 54%|█████▎    | 16185/30196 [33:40<32:52,  7.10it/s]

 54%|█████▎    | 16187/30196 [33:40<30:22,  7.69it/s]

 54%|█████▎    | 16188/30196 [33:40<29:02,  8.04it/s]

 54%|█████▎    | 16189/30196 [33:40<35:00,  6.67it/s]

 54%|█████▎    | 16191/30196 [33:41<29:50,  7.82it/s]

 54%|█████▎    | 16192/30196 [33:41<30:53,  7.56it/s]

 54%|█████▎    | 16193/30196 [33:41<33:00,  7.07it/s]

 54%|█████▎    | 16195/30196 [33:41<30:10,  7.73it/s]

 54%|█████▎    | 16196/30196 [33:41<32:08,  7.26it/s]

 54%|█████▎    | 16197/30196 [33:41<30:14,  7.71it/s]

 54%|█████▎    | 16199/30196 [33:42<27:08,  8.60it/s]

 54%|█████▎    | 16200/30196 [33:42<28:15,  8.25it/s]

 54%|█████▎    | 16202/30196 [33:42<22:07, 10.54it/s]

 54%|█████▎    | 16204/30196 [33:42<24:41,  9.44it/s]

 54%|█████▎    | 16206/30196 [33:43<32:24,  7.19it/s]

 54%|█████▎    | 16207/30196 [33:43<31:04,  7.50it/s]

 54%|█████▎    | 16209/30196 [33:43<34:47,  6.70it/s]

 54%|█████▎    | 16211/30196 [33:43<28:43,  8.12it/s]

 54%|█████▎    | 16213/30196 [33:43<29:01,  8.03it/s]

 54%|█████▎    | 16215/30196 [33:44<24:31,  9.50it/s]

 54%|█████▎    | 16217/30196 [33:44<28:10,  8.27it/s]

 54%|█████▎    | 16219/30196 [33:44<27:21,  8.52it/s]

 54%|█████▎    | 16220/30196 [33:44<28:33,  8.15it/s]

 54%|█████▎    | 16222/30196 [33:44<26:33,  8.77it/s]

 54%|█████▎    | 16224/30196 [33:45<26:50,  8.68it/s]

 54%|█████▎    | 16226/30196 [33:45<23:37,  9.86it/s]

 54%|█████▎    | 16228/30196 [33:45<24:32,  9.49it/s]

 54%|█████▎    | 16230/30196 [33:45<22:11, 10.49it/s]

 54%|█████▍    | 16232/30196 [33:45<25:11,  9.24it/s]

 54%|█████▍    | 16233/30196 [33:46<25:01,  9.30it/s]

 54%|█████▍    | 16234/30196 [33:46<24:53,  9.35it/s]

 54%|█████▍    | 16235/30196 [33:46<26:56,  8.64it/s]

 54%|█████▍    | 16236/30196 [33:46<32:51,  7.08it/s]

 54%|█████▍    | 16238/30196 [33:46<27:53,  8.34it/s]

 54%|█████▍    | 16239/30196 [33:46<33:42,  6.90it/s]

 54%|█████▍    | 16241/30196 [33:47<26:17,  8.85it/s]

 54%|█████▍    | 16243/30196 [33:47<24:56,  9.32it/s]

 54%|█████▍    | 16244/30196 [33:47<26:03,  8.92it/s]

 54%|█████▍    | 16245/30196 [33:47<27:14,  8.53it/s]

 54%|█████▍    | 16246/30196 [33:47<26:49,  8.67it/s]

 54%|█████▍    | 16247/30196 [33:47<27:42,  8.39it/s]

 54%|█████▍    | 16249/30196 [33:48<28:36,  8.12it/s]

 54%|█████▍    | 16250/30196 [33:48<31:06,  7.47it/s]

 54%|█████▍    | 16251/30196 [33:48<31:29,  7.38it/s]

 54%|█████▍    | 16253/30196 [33:48<24:32,  9.47it/s]

 54%|█████▍    | 16255/30196 [33:48<23:55,  9.71it/s]

 54%|█████▍    | 16256/30196 [33:48<27:20,  8.50it/s]

 54%|█████▍    | 16257/30196 [33:48<26:40,  8.71it/s]

 54%|█████▍    | 16258/30196 [33:49<28:33,  8.13it/s]

 54%|█████▍    | 16259/30196 [33:49<29:16,  7.94it/s]

 54%|█████▍    | 16261/30196 [33:49<25:28,  9.12it/s]

 54%|█████▍    | 16262/30196 [33:49<32:08,  7.22it/s]

 54%|█████▍    | 16263/30196 [33:49<32:15,  7.20it/s]

 54%|█████▍    | 16265/30196 [33:49<27:23,  8.48it/s]

 54%|█████▍    | 16266/30196 [33:50<26:59,  8.60it/s]

 54%|█████▍    | 16268/30196 [33:50<30:09,  7.70it/s]

 54%|█████▍    | 16271/30196 [33:50<23:22,  9.93it/s]

 54%|█████▍    | 16273/30196 [33:50<23:05, 10.05it/s]

 54%|█████▍    | 16275/30196 [33:51<27:59,  8.29it/s]

 54%|█████▍    | 16276/30196 [33:51<29:03,  7.99it/s]

 54%|█████▍    | 16277/30196 [33:51<30:04,  7.71it/s]

 54%|█████▍    | 16278/30196 [33:51<34:00,  6.82it/s]

 54%|█████▍    | 16280/30196 [33:51<29:01,  7.99it/s]

 54%|█████▍    | 16281/30196 [33:51<31:14,  7.42it/s]

 54%|█████▍    | 16283/30196 [33:52<24:34,  9.43it/s]

 54%|█████▍    | 16285/30196 [33:52<29:13,  7.93it/s]

 54%|█████▍    | 16286/30196 [33:52<34:10,  6.78it/s]

 54%|█████▍    | 16288/30196 [33:52<31:35,  7.34it/s]

 54%|█████▍    | 16289/30196 [33:53<31:57,  7.25it/s]

 54%|█████▍    | 16290/30196 [33:53<30:10,  7.68it/s]

 54%|█████▍    | 16291/30196 [33:53<31:05,  7.45it/s]

 54%|█████▍    | 16293/30196 [33:53<27:56,  8.29it/s]

 54%|█████▍    | 16294/30196 [33:53<38:05,  6.08it/s]

 54%|█████▍    | 16296/30196 [33:53<30:03,  7.71it/s]

 54%|█████▍    | 16297/30196 [33:54<32:06,  7.21it/s]

 54%|█████▍    | 16298/30196 [33:54<32:11,  7.19it/s]

 54%|█████▍    | 16300/30196 [33:54<25:51,  8.96it/s]

 54%|█████▍    | 16301/30196 [33:54<27:01,  8.57it/s]

 54%|█████▍    | 16303/30196 [33:54<21:17, 10.88it/s]

 54%|█████▍    | 16305/30196 [33:54<19:09, 12.09it/s]

 54%|█████▍    | 16307/30196 [33:55<24:33,  9.43it/s]

 54%|█████▍    | 16309/30196 [33:55<24:34,  9.42it/s]

 54%|█████▍    | 16311/30196 [33:55<22:01, 10.51it/s]

 54%|█████▍    | 16313/30196 [33:55<21:41, 10.67it/s]

 54%|█████▍    | 16315/30196 [33:55<27:19,  8.46it/s]

 54%|█████▍    | 16316/30196 [33:56<33:43,  6.86it/s]

 54%|█████▍    | 16317/30196 [33:56<38:41,  5.98it/s]

 54%|█████▍    | 16318/30196 [33:56<36:47,  6.29it/s]

 54%|█████▍    | 16319/30196 [33:56<39:30,  5.85it/s]

 54%|█████▍    | 16321/30196 [33:56<32:03,  7.21it/s]

 54%|█████▍    | 16323/30196 [33:57<25:22,  9.11it/s]

 54%|█████▍    | 16325/30196 [33:57<27:48,  8.31it/s]

 54%|█████▍    | 16326/30196 [33:57<30:18,  7.63it/s]

 54%|█████▍    | 16328/30196 [33:57<26:03,  8.87it/s]

 54%|█████▍    | 16330/30196 [33:57<23:00, 10.04it/s]

 54%|█████▍    | 16332/30196 [33:58<22:11, 10.41it/s]

 54%|█████▍    | 16334/30196 [33:58<23:16,  9.92it/s]

 54%|█████▍    | 16336/30196 [33:58<26:28,  8.73it/s]

 54%|█████▍    | 16339/30196 [33:58<20:22, 11.33it/s]

 54%|█████▍    | 16341/30196 [33:58<21:47, 10.60it/s]

 54%|█████▍    | 16343/30196 [33:59<24:38,  9.37it/s]

 54%|█████▍    | 16345/30196 [33:59<24:23,  9.47it/s]

 54%|█████▍    | 16347/30196 [33:59<24:46,  9.32it/s]

 54%|█████▍    | 16349/30196 [33:59<21:45, 10.61it/s]

 54%|█████▍    | 16351/30196 [34:00<30:20,  7.61it/s]

 54%|█████▍    | 16352/30196 [34:00<31:42,  7.28it/s]

 54%|█████▍    | 16353/30196 [34:00<32:08,  7.18it/s]

 54%|█████▍    | 16355/30196 [34:00<33:08,  6.96it/s]

 54%|█████▍    | 16356/30196 [34:00<31:16,  7.38it/s]

 54%|█████▍    | 16357/30196 [34:01<33:04,  6.97it/s]

 54%|█████▍    | 16358/30196 [34:01<40:20,  5.72it/s]

 54%|█████▍    | 16359/30196 [34:01<36:26,  6.33it/s]

 54%|█████▍    | 16360/30196 [34:01<36:52,  6.25it/s]

 54%|█████▍    | 16362/30196 [34:02<40:14,  5.73it/s]

 54%|█████▍    | 16364/30196 [34:02<32:42,  7.05it/s]

 54%|█████▍    | 16366/30196 [34:02<28:57,  7.96it/s]

 54%|█████▍    | 16367/30196 [34:02<29:57,  7.69it/s]

 54%|█████▍    | 16369/30196 [34:02<25:03,  9.20it/s]

 54%|█████▍    | 16371/30196 [34:02<21:14, 10.85it/s]

 54%|█████▍    | 16373/30196 [34:03<23:01, 10.01it/s]

 54%|█████▍    | 16375/30196 [34:03<24:57,  9.23it/s]

 54%|█████▍    | 16377/30196 [34:03<22:39, 10.17it/s]

 54%|█████▍    | 16379/30196 [34:03<25:15,  9.12it/s]

 54%|█████▍    | 16381/30196 [34:04<36:40,  6.28it/s]

 54%|█████▍    | 16383/30196 [34:04<32:02,  7.18it/s]

 54%|█████▍    | 16384/30196 [34:04<30:36,  7.52it/s]

 54%|█████▍    | 16386/30196 [34:04<28:55,  7.96it/s]

 54%|█████▍    | 16387/30196 [34:05<36:18,  6.34it/s]

 54%|█████▍    | 16388/30196 [34:05<37:12,  6.18it/s]

 54%|█████▍    | 16390/30196 [34:05<33:44,  6.82it/s]

 54%|█████▍    | 16392/30196 [34:05<36:20,  6.33it/s]

 54%|█████▍    | 16393/30196 [34:05<35:08,  6.55it/s]

 54%|█████▍    | 16394/30196 [34:06<32:38,  7.05it/s]

 54%|█████▍    | 16396/30196 [34:06<26:33,  8.66it/s]

 54%|█████▍    | 16397/30196 [34:06<27:20,  8.41it/s]

 54%|█████▍    | 16399/30196 [34:06<24:57,  9.21it/s]

 54%|█████▍    | 16400/30196 [34:06<26:51,  8.56it/s]

 54%|█████▍    | 16402/30196 [34:06<22:22, 10.27it/s]

 54%|█████▍    | 16404/30196 [34:07<28:32,  8.05it/s]

 54%|█████▍    | 16406/30196 [34:07<27:49,  8.26it/s]

 54%|█████▍    | 16408/30196 [34:07<23:47,  9.66it/s]

 54%|█████▍    | 16410/30196 [34:07<24:35,  9.34it/s]

 54%|█████▍    | 16412/30196 [34:08<26:38,  8.63it/s]

 54%|█████▍    | 16413/30196 [34:08<27:26,  8.37it/s]

 54%|█████▍    | 16415/30196 [34:08<25:42,  8.93it/s]

 54%|█████▍    | 16418/30196 [34:08<27:57,  8.22it/s]

 54%|█████▍    | 16419/30196 [34:08<28:40,  8.01it/s]

 54%|█████▍    | 16420/30196 [34:09<59:47,  3.84it/s]

 54%|█████▍    | 16422/30196 [34:09<44:35,  5.15it/s]

 54%|█████▍    | 16423/30196 [34:10<43:18,  5.30it/s]

 54%|█████▍    | 16424/30196 [34:10<40:32,  5.66it/s]

 54%|█████▍    | 16426/30196 [34:10<37:16,  6.16it/s]

 54%|█████▍    | 16428/30196 [34:10<28:56,  7.93it/s]

 54%|█████▍    | 16430/30196 [34:10<34:21,  6.68it/s]

 54%|█████▍    | 16432/30196 [34:11<38:38,  5.94it/s]

 54%|█████▍    | 16433/30196 [34:11<38:32,  5.95it/s]

 54%|█████▍    | 16434/30196 [34:11<39:08,  5.86it/s]

 54%|█████▍    | 16435/30196 [34:11<36:58,  6.20it/s]

 54%|█████▍    | 16436/30196 [34:12<43:17,  5.30it/s]

 54%|█████▍    | 16437/30196 [34:12<39:45,  5.77it/s]

 54%|█████▍    | 16439/30196 [34:12<33:45,  6.79it/s]

 54%|█████▍    | 16441/30196 [34:12<26:43,  8.58it/s]

 54%|█████▍    | 16442/30196 [34:12<28:14,  8.11it/s]

 54%|█████▍    | 16444/30196 [34:12<25:35,  8.96it/s]

 54%|█████▍    | 16445/30196 [34:13<32:30,  7.05it/s]

 54%|█████▍    | 16447/30196 [34:13<25:29,  8.99it/s]

 54%|█████▍    | 16449/30196 [34:13<25:23,  9.02it/s]

 54%|█████▍    | 16450/30196 [34:13<26:47,  8.55it/s]

 54%|█████▍    | 16451/30196 [34:13<29:17,  7.82it/s]

 54%|█████▍    | 16453/30196 [34:14<29:13,  7.84it/s]

 54%|█████▍    | 16454/30196 [34:14<31:15,  7.33it/s]

 54%|█████▍    | 16456/30196 [34:14<28:54,  7.92it/s]

 55%|█████▍    | 16458/30196 [34:14<24:29,  9.35it/s]

 55%|█████▍    | 16459/30196 [34:14<27:32,  8.31it/s]

 55%|█████▍    | 16461/30196 [34:15<28:50,  7.94it/s]

 55%|█████▍    | 16462/30196 [34:15<30:53,  7.41it/s]

 55%|█████▍    | 16464/30196 [34:15<27:37,  8.28it/s]

 55%|█████▍    | 16466/30196 [34:15<38:24,  5.96it/s]

 55%|█████▍    | 16467/30196 [34:16<38:30,  5.94it/s]

 55%|█████▍    | 16469/30196 [34:16<33:04,  6.92it/s]

 55%|█████▍    | 16471/30196 [34:16<29:52,  7.66it/s]

 55%|█████▍    | 16472/30196 [34:16<28:55,  7.91it/s]

 55%|█████▍    | 16474/30196 [34:16<28:42,  7.97it/s]

 55%|█████▍    | 16476/30196 [34:17<28:01,  8.16it/s]

 55%|█████▍    | 16478/30196 [34:17<26:24,  8.66it/s]

 55%|█████▍    | 16479/30196 [34:17<29:10,  7.84it/s]

 55%|█████▍    | 16481/30196 [34:17<26:38,  8.58it/s]

 55%|█████▍    | 16483/30196 [34:17<26:25,  8.65it/s]

 55%|█████▍    | 16484/30196 [34:18<25:59,  8.79it/s]

 55%|█████▍    | 16485/30196 [34:18<26:46,  8.53it/s]

 55%|█████▍    | 16486/30196 [34:18<35:27,  6.45it/s]

 55%|█████▍    | 16487/30196 [34:18<42:17,  5.40it/s]

 55%|█████▍    | 16488/30196 [34:18<37:45,  6.05it/s]

 55%|█████▍    | 16489/30196 [34:19<41:16,  5.53it/s]

 55%|█████▍    | 16491/30196 [34:19<35:02,  6.52it/s]

 55%|█████▍    | 16493/30196 [34:19<26:36,  8.58it/s]

 55%|█████▍    | 16495/30196 [34:19<26:49,  8.51it/s]

 55%|█████▍    | 16496/30196 [34:19<26:27,  8.63it/s]

 55%|█████▍    | 16497/30196 [34:19<25:54,  8.81it/s]

 55%|█████▍    | 16498/30196 [34:20<45:56,  4.97it/s]

 55%|█████▍    | 16500/30196 [34:20<33:20,  6.84it/s]

 55%|█████▍    | 16502/30196 [34:20<27:51,  8.19it/s]

 55%|█████▍    | 16504/30196 [34:20<27:32,  8.29it/s]

 55%|█████▍    | 16505/30196 [34:21<29:57,  7.62it/s]

 55%|█████▍    | 16507/30196 [34:21<28:02,  8.14it/s]

 55%|█████▍    | 16508/30196 [34:21<32:37,  6.99it/s]

 55%|█████▍    | 16510/30196 [34:21<29:17,  7.79it/s]

 55%|█████▍    | 16511/30196 [34:21<28:11,  8.09it/s]

 55%|█████▍    | 16513/30196 [34:21<23:20,  9.77it/s]

 55%|█████▍    | 16515/30196 [34:22<29:41,  7.68it/s]

 55%|█████▍    | 16516/30196 [34:22<28:32,  7.99it/s]

 55%|█████▍    | 16518/30196 [34:22<23:43,  9.61it/s]

 55%|█████▍    | 16520/30196 [34:22<26:06,  8.73it/s]

 55%|█████▍    | 16521/30196 [34:22<28:56,  7.87it/s]

 55%|█████▍    | 16523/30196 [34:23<25:17,  9.01it/s]

 55%|█████▍    | 16525/30196 [34:23<22:17, 10.22it/s]

 55%|█████▍    | 16527/30196 [34:23<22:43, 10.03it/s]

 55%|█████▍    | 16529/30196 [34:23<22:58,  9.91it/s]

 55%|█████▍    | 16531/30196 [34:23<24:29,  9.30it/s]

 55%|█████▍    | 16532/30196 [34:24<24:34,  9.27it/s]

 55%|█████▍    | 16534/30196 [34:24<24:03,  9.47it/s]

 55%|█████▍    | 16535/30196 [34:24<25:20,  8.99it/s]

 55%|█████▍    | 16537/30196 [34:24<25:53,  8.79it/s]

 55%|█████▍    | 16538/30196 [34:24<27:08,  8.38it/s]

 55%|█████▍    | 16540/30196 [34:25<27:48,  8.18it/s]

 55%|█████▍    | 16541/30196 [34:25<29:49,  7.63it/s]

 55%|█████▍    | 16542/30196 [34:25<31:33,  7.21it/s]

 55%|█████▍    | 16544/30196 [34:25<28:47,  7.90it/s]

 55%|█████▍    | 16546/30196 [34:25<22:46,  9.99it/s]

 55%|█████▍    | 16548/30196 [34:25<24:12,  9.40it/s]

 55%|█████▍    | 16550/30196 [34:26<28:46,  7.90it/s]

 55%|█████▍    | 16552/30196 [34:26<27:31,  8.26it/s]

 55%|█████▍    | 16554/30196 [34:26<26:51,  8.46it/s]

 55%|█████▍    | 16556/30196 [34:26<25:26,  8.94it/s]

 55%|█████▍    | 16557/30196 [34:26<25:10,  9.03it/s]

 55%|█████▍    | 16558/30196 [34:27<26:16,  8.65it/s]

 55%|█████▍    | 16560/30196 [34:27<25:09,  9.04it/s]

 55%|█████▍    | 16562/30196 [34:27<25:46,  8.82it/s]

 55%|█████▍    | 16563/30196 [34:27<27:18,  8.32it/s]

 55%|█████▍    | 16564/30196 [34:27<27:56,  8.13it/s]

 55%|█████▍    | 16565/30196 [34:27<27:16,  8.33it/s]

 55%|█████▍    | 16566/30196 [34:28<32:24,  7.01it/s]

 55%|█████▍    | 16567/30196 [34:28<32:15,  7.04it/s]

 55%|█████▍    | 16568/30196 [34:28<32:05,  7.08it/s]

 55%|█████▍    | 16569/30196 [34:28<34:05,  6.66it/s]

 55%|█████▍    | 16570/30196 [34:28<33:30,  6.78it/s]

 55%|█████▍    | 16571/30196 [34:28<30:58,  7.33it/s]

 55%|█████▍    | 16573/30196 [34:29<25:19,  8.97it/s]

 55%|█████▍    | 16574/30196 [34:29<26:39,  8.51it/s]

 55%|█████▍    | 16575/30196 [34:29<27:43,  8.19it/s]

 55%|█████▍    | 16577/30196 [34:29<23:49,  9.53it/s]

 55%|█████▍    | 16578/30196 [34:29<23:49,  9.53it/s]

 55%|█████▍    | 16580/30196 [34:29<23:29,  9.66it/s]

 55%|█████▍    | 16582/30196 [34:30<25:41,  8.83it/s]

 55%|█████▍    | 16583/30196 [34:30<26:28,  8.57it/s]

 55%|█████▍    | 16584/30196 [34:30<28:00,  8.10it/s]

 55%|█████▍    | 16585/30196 [34:30<29:15,  7.76it/s]

 55%|█████▍    | 16587/30196 [34:30<25:33,  8.88it/s]

 55%|█████▍    | 16589/30196 [34:30<25:45,  8.80it/s]

 55%|█████▍    | 16590/30196 [34:31<28:20,  8.00it/s]

 55%|█████▍    | 16592/30196 [34:31<22:52,  9.91it/s]

 55%|█████▍    | 16595/30196 [34:31<17:37, 12.86it/s]

 55%|█████▍    | 16597/30196 [34:31<20:05, 11.28it/s]

 55%|█████▍    | 16599/30196 [34:31<23:23,  9.69it/s]

 55%|█████▍    | 16601/30196 [34:31<22:20, 10.14it/s]

 55%|█████▍    | 16603/30196 [34:32<19:46, 11.46it/s]

 55%|█████▍    | 16605/30196 [34:32<17:17, 13.10it/s]

 55%|█████▍    | 16607/30196 [34:32<19:38, 11.53it/s]

 55%|█████▌    | 16609/30196 [34:32<21:47, 10.39it/s]

 55%|█████▌    | 16611/30196 [34:32<25:45,  8.79it/s]

 55%|█████▌    | 16613/30196 [34:33<24:02,  9.42it/s]

 55%|█████▌    | 16615/30196 [34:33<24:38,  9.19it/s]

 55%|█████▌    | 16616/30196 [34:33<24:29,  9.24it/s]

 55%|█████▌    | 16617/30196 [34:33<29:11,  7.75it/s]

 55%|█████▌    | 16619/30196 [34:33<26:51,  8.42it/s]

 55%|█████▌    | 16621/30196 [34:34<26:56,  8.40it/s]

 55%|█████▌    | 16623/30196 [34:34<27:18,  8.28it/s]

 55%|█████▌    | 16624/30196 [34:34<31:02,  7.29it/s]

 55%|█████▌    | 16625/30196 [34:34<31:20,  7.22it/s]

 55%|█████▌    | 16626/30196 [34:34<33:26,  6.76it/s]

 55%|█████▌    | 16627/30196 [34:35<31:01,  7.29it/s]

 55%|█████▌    | 16629/30196 [34:35<35:39,  6.34it/s]

 55%|█████▌    | 16630/30196 [34:35<34:15,  6.60it/s]

 55%|█████▌    | 16631/30196 [34:35<33:04,  6.83it/s]

 55%|█████▌    | 16633/30196 [34:35<25:44,  8.78it/s]

 55%|█████▌    | 16635/30196 [34:35<24:58,  9.05it/s]

 55%|█████▌    | 16636/30196 [34:36<25:55,  8.72it/s]

 55%|█████▌    | 16637/30196 [34:36<25:40,  8.80it/s]

 55%|█████▌    | 16638/30196 [34:36<27:34,  8.19it/s]

 55%|█████▌    | 16639/30196 [34:36<30:39,  7.37it/s]

 55%|█████▌    | 16640/30196 [34:36<30:17,  7.46it/s]

 55%|█████▌    | 16643/30196 [34:36<22:32, 10.02it/s]

 55%|█████▌    | 16644/30196 [34:37<24:24,  9.25it/s]

 55%|█████▌    | 16645/30196 [34:37<27:27,  8.23it/s]

 55%|█████▌    | 16647/30196 [34:37<22:40,  9.96it/s]

 55%|█████▌    | 16649/30196 [34:37<20:32, 10.99it/s]

 55%|█████▌    | 16651/30196 [34:37<24:12,  9.32it/s]

 55%|█████▌    | 16652/30196 [34:38<31:23,  7.19it/s]

 55%|█████▌    | 16653/30196 [34:38<33:03,  6.83it/s]

 55%|█████▌    | 16654/30196 [34:38<36:29,  6.19it/s]

 55%|█████▌    | 16655/30196 [34:38<35:20,  6.39it/s]

 55%|█████▌    | 16656/30196 [34:38<35:54,  6.29it/s]

 55%|█████▌    | 16657/30196 [34:38<36:32,  6.18it/s]

 55%|█████▌    | 16658/30196 [34:39<35:11,  6.41it/s]

 55%|█████▌    | 16660/30196 [34:39<30:05,  7.50it/s]

 55%|█████▌    | 16661/30196 [34:39<30:30,  7.39it/s]

 55%|█████▌    | 16662/30196 [34:39<30:13,  7.46it/s]

 55%|█████▌    | 16663/30196 [34:39<32:39,  6.91it/s]

 55%|█████▌    | 16665/30196 [34:39<26:20,  8.56it/s]

 55%|█████▌    | 16666/30196 [34:40<29:35,  7.62it/s]

 55%|█████▌    | 16668/30196 [34:40<23:49,  9.46it/s]

 55%|█████▌    | 16670/30196 [34:40<19:32, 11.54it/s]

 55%|█████▌    | 16672/30196 [34:40<26:44,  8.43it/s]

 55%|█████▌    | 16674/30196 [34:40<28:46,  7.83it/s]

 55%|█████▌    | 16675/30196 [34:41<27:47,  8.11it/s]

 55%|█████▌    | 16677/30196 [34:41<23:24,  9.63it/s]

 55%|█████▌    | 16679/30196 [34:41<24:59,  9.02it/s]

 55%|█████▌    | 16681/30196 [34:41<21:46, 10.35it/s]

 55%|█████▌    | 16683/30196 [34:41<24:38,  9.14it/s]

 55%|█████▌    | 16685/30196 [34:41<22:17, 10.10it/s]

 55%|█████▌    | 16687/30196 [34:42<28:57,  7.78it/s]

 55%|█████▌    | 16689/30196 [34:42<30:11,  7.46it/s]

 55%|█████▌    | 16690/30196 [34:42<34:48,  6.47it/s]

 55%|█████▌    | 16691/30196 [34:43<33:42,  6.68it/s]

 55%|█████▌    | 16692/30196 [34:43<34:52,  6.45it/s]

 55%|█████▌    | 16693/30196 [34:43<32:10,  6.99it/s]

 55%|█████▌    | 16695/30196 [34:43<25:48,  8.72it/s]

 55%|█████▌    | 16696/30196 [34:43<29:03,  7.74it/s]

 55%|█████▌    | 16697/30196 [34:43<27:41,  8.12it/s]

 55%|█████▌    | 16699/30196 [34:44<35:40,  6.30it/s]

 55%|█████▌    | 16702/30196 [34:44<26:06,  8.61it/s]

 55%|█████▌    | 16703/30196 [34:44<25:49,  8.71it/s]

 55%|█████▌    | 16704/30196 [34:44<26:43,  8.41it/s]

 55%|█████▌    | 16706/30196 [34:44<28:12,  7.97it/s]

 55%|█████▌    | 16707/30196 [34:45<30:15,  7.43it/s]

 55%|█████▌    | 16708/30196 [34:45<30:00,  7.49it/s]

 55%|█████▌    | 16709/30196 [34:45<39:16,  5.72it/s]

 55%|█████▌    | 16710/30196 [34:45<36:59,  6.08it/s]

 55%|█████▌    | 16711/30196 [34:45<37:54,  5.93it/s]

 55%|█████▌    | 16712/30196 [34:46<41:33,  5.41it/s]

 55%|█████▌    | 16714/30196 [34:46<32:15,  6.96it/s]

 55%|█████▌    | 16716/30196 [34:46<26:41,  8.42it/s]

 55%|█████▌    | 16718/30196 [34:46<23:47,  9.44it/s]

 55%|█████▌    | 16719/30196 [34:46<25:07,  8.94it/s]

 55%|█████▌    | 16721/30196 [34:46<20:05, 11.18it/s]

 55%|█████▌    | 16723/30196 [34:47<45:11,  4.97it/s]

 55%|█████▌    | 16724/30196 [34:47<44:14,  5.08it/s]

 55%|█████▌    | 16725/30196 [34:47<41:09,  5.46it/s]

 55%|█████▌    | 16726/30196 [34:48<37:12,  6.03it/s]

 55%|█████▌    | 16727/30196 [34:48<36:10,  6.21it/s]

 55%|█████▌    | 16728/30196 [34:48<41:51,  5.36it/s]

 55%|█████▌    | 16730/30196 [34:48<31:57,  7.02it/s]

 55%|█████▌    | 16731/30196 [34:48<31:21,  7.16it/s]

 55%|█████▌    | 16732/30196 [34:48<30:48,  7.28it/s]

 55%|█████▌    | 16734/30196 [34:49<28:06,  7.98it/s]

 55%|█████▌    | 16736/30196 [34:49<25:24,  8.83it/s]

 55%|█████▌    | 16737/30196 [34:49<27:01,  8.30it/s]

 55%|█████▌    | 16739/30196 [34:49<24:22,  9.20it/s]

 55%|█████▌    | 16740/30196 [34:49<30:09,  7.44it/s]

 55%|█████▌    | 16741/30196 [34:49<30:08,  7.44it/s]

 55%|█████▌    | 16743/30196 [34:50<27:32,  8.14it/s]

 55%|█████▌    | 16745/30196 [34:50<26:41,  8.40it/s]

 55%|█████▌    | 16746/30196 [34:50<30:57,  7.24it/s]

 55%|█████▌    | 16747/30196 [34:50<29:33,  7.58it/s]

 55%|█████▌    | 16748/30196 [34:50<31:50,  7.04it/s]

 55%|█████▌    | 16750/30196 [34:51<28:18,  7.92it/s]

 55%|█████▌    | 16751/30196 [34:51<33:10,  6.76it/s]

 55%|█████▌    | 16752/30196 [34:51<32:30,  6.89it/s]

 55%|█████▌    | 16753/30196 [34:51<33:57,  6.60it/s]

 55%|█████▌    | 16754/30196 [34:51<34:49,  6.43it/s]

 55%|█████▌    | 16756/30196 [34:52<30:22,  7.37it/s]

 55%|█████▌    | 16758/30196 [34:52<23:18,  9.61it/s]

 56%|█████▌    | 16760/30196 [34:52<20:27, 10.95it/s]

 56%|█████▌    | 16762/30196 [34:52<20:11, 11.09it/s]

 56%|█████▌    | 16764/30196 [34:52<23:46,  9.42it/s]

 56%|█████▌    | 16766/30196 [34:53<28:07,  7.96it/s]

 56%|█████▌    | 16768/30196 [34:53<25:08,  8.90it/s]

 56%|█████▌    | 16769/30196 [34:53<25:00,  8.95it/s]

 56%|█████▌    | 16771/30196 [34:53<21:05, 10.61it/s]

 56%|█████▌    | 16773/30196 [34:53<24:31,  9.12it/s]

 56%|█████▌    | 16775/30196 [34:53<26:11,  8.54it/s]

 56%|█████▌    | 16776/30196 [34:54<25:40,  8.71it/s]

 56%|█████▌    | 16778/30196 [34:54<21:12, 10.55it/s]

 56%|█████▌    | 16780/30196 [34:54<27:20,  8.18it/s]

 56%|█████▌    | 16782/30196 [34:54<27:12,  8.22it/s]

 56%|█████▌    | 16783/30196 [34:54<27:34,  8.11it/s]

 56%|█████▌    | 16784/30196 [34:55<26:41,  8.37it/s]

 56%|█████▌    | 16785/30196 [34:55<27:47,  8.04it/s]

 56%|█████▌    | 16786/30196 [34:55<26:41,  8.37it/s]

 56%|█████▌    | 16788/30196 [34:55<24:19,  9.18it/s]

 56%|█████▌    | 16790/30196 [34:55<20:45, 10.77it/s]

 56%|█████▌    | 16792/30196 [34:55<24:38,  9.06it/s]

 56%|█████▌    | 16794/30196 [34:56<21:18, 10.48it/s]

 56%|█████▌    | 16796/30196 [34:56<20:26, 10.92it/s]

 56%|█████▌    | 16798/30196 [34:56<23:28,  9.51it/s]

 56%|█████▌    | 16800/30196 [34:56<22:57,  9.73it/s]

 56%|█████▌    | 16802/30196 [34:56<24:41,  9.04it/s]

 56%|█████▌    | 16803/30196 [34:57<25:27,  8.77it/s]

 56%|█████▌    | 16804/30196 [34:57<28:08,  7.93it/s]

 56%|█████▌    | 16806/30196 [34:57<26:45,  8.34it/s]

 56%|█████▌    | 16807/30196 [34:57<28:50,  7.74it/s]

 56%|█████▌    | 16808/30196 [34:57<30:45,  7.26it/s]

 56%|█████▌    | 16810/30196 [34:57<25:44,  8.67it/s]

 56%|█████▌    | 16811/30196 [34:58<27:16,  8.18it/s]

 56%|█████▌    | 16813/30196 [34:58<27:47,  8.03it/s]

 56%|█████▌    | 16814/30196 [34:58<27:34,  8.09it/s]

 56%|█████▌    | 16816/30196 [34:58<23:28,  9.50it/s]

 56%|█████▌    | 16818/30196 [34:58<21:54, 10.17it/s]

 56%|█████▌    | 16820/30196 [34:59<26:06,  8.54it/s]

 56%|█████▌    | 16822/30196 [34:59<23:10,  9.62it/s]

 56%|█████▌    | 16824/30196 [34:59<23:53,  9.33it/s]

 56%|█████▌    | 16825/30196 [34:59<25:33,  8.72it/s]

 56%|█████▌    | 16826/30196 [34:59<26:16,  8.48it/s]

 56%|█████▌    | 16827/30196 [34:59<26:55,  8.28it/s]

 56%|█████▌    | 16828/30196 [35:00<27:38,  8.06it/s]

 56%|█████▌    | 16829/30196 [35:00<30:05,  7.40it/s]

 56%|█████▌    | 16830/30196 [35:00<29:51,  7.46it/s]

 56%|█████▌    | 16831/30196 [35:00<38:20,  5.81it/s]

 56%|█████▌    | 16832/30196 [35:00<35:42,  6.24it/s]

 56%|█████▌    | 16833/30196 [35:00<33:44,  6.60it/s]

 56%|█████▌    | 16835/30196 [35:00<25:03,  8.89it/s]

 56%|█████▌    | 16836/30196 [35:01<26:01,  8.56it/s]

 56%|█████▌    | 16837/30196 [35:01<28:58,  7.69it/s]

 56%|█████▌    | 16838/30196 [35:01<27:46,  8.01it/s]

 56%|█████▌    | 16840/30196 [35:01<22:03, 10.09it/s]

 56%|█████▌    | 16842/30196 [35:01<24:56,  8.92it/s]

 56%|█████▌    | 16843/30196 [35:01<27:54,  7.97it/s]

 56%|█████▌    | 16844/30196 [35:02<28:46,  7.73it/s]

 56%|█████▌    | 16846/30196 [35:02<27:11,  8.18it/s]

 56%|█████▌    | 16847/30196 [35:02<47:02,  4.73it/s]

 56%|█████▌    | 16848/30196 [35:02<41:37,  5.35it/s]

 56%|█████▌    | 16850/30196 [35:03<30:08,  7.38it/s]

 56%|█████▌    | 16851/30196 [35:03<31:59,  6.95it/s]

 56%|█████▌    | 16853/30196 [35:03<35:45,  6.22it/s]

 56%|█████▌    | 16854/30196 [35:03<34:32,  6.44it/s]

 56%|█████▌    | 16856/30196 [35:04<39:51,  5.58it/s]

 56%|█████▌    | 16858/30196 [35:04<33:15,  6.68it/s]

 56%|█████▌    | 16860/30196 [35:04<27:01,  8.23it/s]

 56%|█████▌    | 16862/30196 [35:04<26:16,  8.46it/s]

 56%|█████▌    | 16863/30196 [35:04<29:57,  7.42it/s]

 56%|█████▌    | 16864/30196 [35:05<32:01,  6.94it/s]

 56%|█████▌    | 16865/30196 [35:05<29:58,  7.41it/s]

 56%|█████▌    | 16867/30196 [35:05<31:32,  7.04it/s]

 56%|█████▌    | 16868/30196 [35:05<32:50,  6.77it/s]

 56%|█████▌    | 16869/30196 [35:05<33:48,  6.57it/s]

 56%|█████▌    | 16871/30196 [35:06<28:07,  7.90it/s]

 56%|█████▌    | 16874/30196 [35:06<22:52,  9.70it/s]

 56%|█████▌    | 16876/30196 [35:06<24:04,  9.22it/s]

 56%|█████▌    | 16877/30196 [35:06<24:08,  9.20it/s]

 56%|█████▌    | 16878/30196 [35:06<25:20,  8.76it/s]

 56%|█████▌    | 16879/30196 [35:06<24:52,  8.92it/s]

 56%|█████▌    | 16881/30196 [35:06<20:10, 11.00it/s]

 56%|█████▌    | 16883/30196 [35:07<17:19, 12.81it/s]

 56%|█████▌    | 16885/30196 [35:07<15:18, 14.49it/s]

 56%|█████▌    | 16887/30196 [35:07<16:49, 13.18it/s]

 56%|█████▌    | 16889/30196 [35:07<19:54, 11.14it/s]

 56%|█████▌    | 16891/30196 [35:07<23:30,  9.43it/s]

 56%|█████▌    | 16893/30196 [35:08<25:03,  8.85it/s]

 56%|█████▌    | 16895/30196 [35:08<23:13,  9.55it/s]

 56%|█████▌    | 16897/30196 [35:08<24:29,  9.05it/s]

 56%|█████▌    | 16899/30196 [35:08<24:07,  9.19it/s]

 56%|█████▌    | 16900/30196 [35:08<24:03,  9.21it/s]

 56%|█████▌    | 16902/30196 [35:09<20:16, 10.93it/s]

 56%|█████▌    | 16904/30196 [35:09<19:38, 11.28it/s]

 56%|█████▌    | 16906/30196 [35:09<21:26, 10.33it/s]

 56%|█████▌    | 16908/30196 [35:09<22:50,  9.70it/s]

 56%|█████▌    | 16910/30196 [35:09<25:12,  8.78it/s]

 56%|█████▌    | 16911/30196 [35:10<26:16,  8.43it/s]

 56%|█████▌    | 16912/30196 [35:10<30:13,  7.32it/s]

 56%|█████▌    | 16913/30196 [35:10<34:45,  6.37it/s]

 56%|█████▌    | 16914/30196 [35:10<35:28,  6.24it/s]

 56%|█████▌    | 16916/30196 [35:10<29:21,  7.54it/s]

 56%|█████▌    | 16917/30196 [35:11<31:02,  7.13it/s]

 56%|█████▌    | 16918/30196 [35:11<32:28,  6.82it/s]

 56%|█████▌    | 16919/30196 [35:11<32:07,  6.89it/s]

 56%|█████▌    | 16920/30196 [35:11<32:14,  6.86it/s]

 56%|█████▌    | 16921/30196 [35:11<35:57,  6.15it/s]

 56%|█████▌    | 16923/30196 [35:11<31:49,  6.95it/s]

 56%|█████▌    | 16924/30196 [35:12<35:24,  6.25it/s]

 56%|█████▌    | 16925/30196 [35:12<33:46,  6.55it/s]

 56%|█████▌    | 16927/30196 [35:12<28:51,  7.66it/s]

 56%|█████▌    | 16928/30196 [35:12<34:26,  6.42it/s]

 56%|█████▌    | 16930/30196 [35:12<31:00,  7.13it/s]

 56%|█████▌    | 16931/30196 [35:13<37:24,  5.91it/s]

 56%|█████▌    | 16933/30196 [35:13<31:55,  6.92it/s]

 56%|█████▌    | 16934/30196 [35:13<31:14,  7.08it/s]

 56%|█████▌    | 16936/30196 [35:13<24:16,  9.10it/s]

 56%|█████▌    | 16938/30196 [35:13<23:44,  9.31it/s]

 56%|█████▌    | 16940/30196 [35:14<21:52, 10.10it/s]

 56%|█████▌    | 16942/30196 [35:14<20:41, 10.68it/s]

 56%|█████▌    | 16944/30196 [35:14<22:02, 10.02it/s]

 56%|█████▌    | 16946/30196 [35:14<22:34,  9.78it/s]

 56%|█████▌    | 16948/30196 [35:14<23:56,  9.22it/s]

 56%|█████▌    | 16950/30196 [35:15<22:45,  9.70it/s]

 56%|█████▌    | 16952/30196 [35:15<22:46,  9.69it/s]

 56%|█████▌    | 16953/30196 [35:15<22:49,  9.67it/s]

 56%|█████▌    | 16955/30196 [35:15<19:05, 11.56it/s]

 56%|█████▌    | 16957/30196 [35:15<20:32, 10.74it/s]

 56%|█████▌    | 16960/30196 [35:15<16:55, 13.03it/s]

 56%|█████▌    | 16962/30196 [35:15<16:39, 13.25it/s]

 56%|█████▌    | 16964/30196 [35:16<23:06,  9.55it/s]

 56%|█████▌    | 16966/30196 [35:16<21:23, 10.31it/s]

 56%|█████▌    | 16968/30196 [35:16<21:26, 10.28it/s]

 56%|█████▌    | 16970/30196 [35:16<23:06,  9.54it/s]

 56%|█████▌    | 16972/30196 [35:17<26:18,  8.38it/s]

 56%|█████▌    | 16973/30196 [35:17<25:57,  8.49it/s]

 56%|█████▌    | 16974/30196 [35:17<32:18,  6.82it/s]

 56%|█████▌    | 16975/30196 [35:17<36:24,  6.05it/s]

 56%|█████▌    | 16976/30196 [35:18<35:29,  6.21it/s]

 56%|█████▌    | 16977/30196 [35:18<32:18,  6.82it/s]

 56%|█████▌    | 16978/30196 [35:18<34:14,  6.43it/s]

 56%|█████▌    | 16979/30196 [35:18<35:32,  6.20it/s]

 56%|█████▌    | 16981/30196 [35:18<33:13,  6.63it/s]

 56%|█████▌    | 16983/30196 [35:18<27:48,  7.92it/s]

 56%|█████▌    | 16984/30196 [35:19<28:49,  7.64it/s]

 56%|█████▌    | 16985/30196 [35:19<27:46,  7.93it/s]

 56%|█████▋    | 16986/30196 [35:19<28:52,  7.62it/s]

 56%|█████▋    | 16987/30196 [35:19<27:22,  8.04it/s]

 56%|█████▋    | 16989/30196 [35:19<26:49,  8.21it/s]

 56%|█████▋    | 16990/30196 [35:19<27:18,  8.06it/s]

 56%|█████▋    | 16992/30196 [35:19<23:03,  9.54it/s]

 56%|█████▋    | 16993/30196 [35:20<28:33,  7.71it/s]

 56%|█████▋    | 16994/30196 [35:20<31:05,  7.08it/s]

 56%|█████▋    | 16996/30196 [35:20<24:50,  8.86it/s]

 56%|█████▋    | 16997/30196 [35:20<27:38,  7.96it/s]

 56%|█████▋    | 16998/30196 [35:20<29:57,  7.34it/s]

 56%|█████▋    | 16999/30196 [35:21<34:02,  6.46it/s]

 56%|█████▋    | 17000/30196 [35:21<32:54,  6.68it/s]

 56%|█████▋    | 17001/30196 [35:21<30:26,  7.22it/s]

 56%|█████▋    | 17003/30196 [35:21<26:50,  8.19it/s]

 56%|█████▋    | 17005/30196 [35:21<23:28,  9.36it/s]

 56%|█████▋    | 17006/30196 [35:21<25:26,  8.64it/s]

 56%|█████▋    | 17007/30196 [35:21<27:28,  8.00it/s]

 56%|█████▋    | 17008/30196 [35:22<26:29,  8.30it/s]

 56%|█████▋    | 17010/30196 [35:22<25:44,  8.53it/s]

 56%|█████▋    | 17012/30196 [35:22<25:43,  8.54it/s]

 56%|█████▋    | 17013/30196 [35:22<26:22,  8.33it/s]

 56%|█████▋    | 17015/30196 [35:22<27:26,  8.01it/s]

 56%|█████▋    | 17017/30196 [35:23<23:33,  9.32it/s]

 56%|█████▋    | 17018/30196 [35:23<25:19,  8.67it/s]

 56%|█████▋    | 17019/30196 [35:23<26:52,  8.17it/s]

 56%|█████▋    | 17020/30196 [35:23<27:47,  7.90it/s]

 56%|█████▋    | 17022/30196 [35:23<23:02,  9.53it/s]

 56%|█████▋    | 17023/30196 [35:23<24:53,  8.82it/s]

 56%|█████▋    | 17025/30196 [35:23<23:59,  9.15it/s]

 56%|█████▋    | 17026/30196 [35:24<33:40,  6.52it/s]

 56%|█████▋    | 17028/30196 [35:24<33:41,  6.51it/s]

 56%|█████▋    | 17029/30196 [35:24<32:36,  6.73it/s]

 56%|█████▋    | 17030/30196 [35:25<42:14,  5.19it/s]

 56%|█████▋    | 17032/30196 [35:25<38:17,  5.73it/s]

 56%|█████▋    | 17033/30196 [35:25<36:55,  5.94it/s]

 56%|█████▋    | 17034/30196 [35:25<36:48,  5.96it/s]

 56%|█████▋    | 17035/30196 [35:25<35:38,  6.16it/s]

 56%|█████▋    | 17037/30196 [35:26<35:34,  6.16it/s]

 56%|█████▋    | 17038/30196 [35:26<34:19,  6.39it/s]

 56%|█████▋    | 17040/30196 [35:26<30:17,  7.24it/s]

 56%|█████▋    | 17041/30196 [35:26<29:55,  7.33it/s]

 56%|█████▋    | 17042/30196 [35:26<39:35,  5.54it/s]

 56%|█████▋    | 17043/30196 [35:27<35:37,  6.15it/s]

 56%|█████▋    | 17045/30196 [35:27<28:04,  7.81it/s]

 56%|█████▋    | 17047/30196 [35:27<26:23,  8.30it/s]

 56%|█████▋    | 17048/30196 [35:27<25:39,  8.54it/s]

 56%|█████▋    | 17049/30196 [35:27<25:16,  8.67it/s]

 56%|█████▋    | 17051/30196 [35:27<21:49, 10.04it/s]

 56%|█████▋    | 17053/30196 [35:28<21:38, 10.12it/s]

 56%|█████▋    | 17055/30196 [35:28<21:25, 10.22it/s]

 56%|█████▋    | 17057/30196 [35:28<23:48,  9.20it/s]

 56%|█████▋    | 17058/30196 [35:28<30:32,  7.17it/s]

 56%|█████▋    | 17059/30196 [35:28<31:47,  6.89it/s]

 56%|█████▋    | 17060/30196 [35:29<33:29,  6.54it/s]

 57%|█████▋    | 17062/30196 [35:29<28:28,  7.69it/s]

 57%|█████▋    | 17063/30196 [35:29<27:29,  7.96it/s]

 57%|█████▋    | 17064/30196 [35:29<28:17,  7.74it/s]

 57%|█████▋    | 17066/30196 [35:29<25:29,  8.58it/s]

 57%|█████▋    | 17067/30196 [35:29<28:04,  7.79it/s]

 57%|█████▋    | 17069/30196 [35:30<22:47,  9.60it/s]

 57%|█████▋    | 17070/30196 [35:30<28:49,  7.59it/s]

 57%|█████▋    | 17071/30196 [35:30<30:31,  7.16it/s]

 57%|█████▋    | 17073/30196 [35:30<26:10,  8.35it/s]

 57%|█████▋    | 17075/30196 [35:30<25:10,  8.69it/s]

 57%|█████▋    | 17077/30196 [35:31<23:54,  9.15it/s]

 57%|█████▋    | 17078/30196 [35:31<23:56,  9.13it/s]

 57%|█████▋    | 17079/30196 [35:31<26:42,  8.18it/s]

 57%|█████▋    | 17080/30196 [35:31<29:02,  7.53it/s]

 57%|█████▋    | 17082/30196 [35:31<25:05,  8.71it/s]

 57%|█████▋    | 17083/30196 [35:31<26:42,  8.18it/s]

 57%|█████▋    | 17084/30196 [35:31<25:58,  8.41it/s]

 57%|█████▋    | 17085/30196 [35:32<29:23,  7.43it/s]

 57%|█████▋    | 17086/30196 [35:32<27:40,  7.89it/s]

 57%|█████▋    | 17087/30196 [35:32<27:16,  8.01it/s]

 57%|█████▋    | 17088/30196 [35:32<28:36,  7.64it/s]

 57%|█████▋    | 17089/30196 [35:32<29:36,  7.38it/s]

 57%|█████▋    | 17091/30196 [35:32<24:04,  9.07it/s]

 57%|█████▋    | 17093/30196 [35:32<25:39,  8.51it/s]

 57%|█████▋    | 17094/30196 [35:33<26:32,  8.23it/s]

 57%|█████▋    | 17096/30196 [35:33<24:28,  8.92it/s]

 57%|█████▋    | 17098/30196 [35:33<20:19, 10.74it/s]

 57%|█████▋    | 17100/30196 [35:33<21:44, 10.04it/s]

 57%|█████▋    | 17102/30196 [35:33<19:15, 11.33it/s]

 57%|█████▋    | 17104/30196 [35:34<22:35,  9.66it/s]

 57%|█████▋    | 17106/30196 [35:34<19:02, 11.46it/s]

 57%|█████▋    | 17108/30196 [35:34<19:53, 10.96it/s]

 57%|█████▋    | 17110/30196 [35:34<23:05,  9.45it/s]

 57%|█████▋    | 17112/30196 [35:35<35:05,  6.21it/s]

 57%|█████▋    | 17114/30196 [35:35<32:34,  6.69it/s]

 57%|█████▋    | 17115/30196 [35:35<32:15,  6.76it/s]

 57%|█████▋    | 17116/30196 [35:35<31:59,  6.82it/s]

 57%|█████▋    | 17117/30196 [35:35<33:01,  6.60it/s]

 57%|█████▋    | 17118/30196 [35:36<34:08,  6.38it/s]

 57%|█████▋    | 17120/30196 [35:36<26:32,  8.21it/s]

 57%|█████▋    | 17121/30196 [35:36<27:46,  7.84it/s]

 57%|█████▋    | 17122/30196 [35:36<30:18,  7.19it/s]

 57%|█████▋    | 17123/30196 [35:36<30:22,  7.17it/s]

 57%|█████▋    | 17124/30196 [35:36<30:23,  7.17it/s]

 57%|█████▋    | 17126/30196 [35:37<31:32,  6.91it/s]

 57%|█████▋    | 17127/30196 [35:37<31:00,  7.02it/s]

 57%|█████▋    | 17129/30196 [35:37<24:13,  8.99it/s]

 57%|█████▋    | 17130/30196 [35:37<26:51,  8.11it/s]

 57%|█████▋    | 17131/30196 [35:37<29:46,  7.31it/s]

 57%|█████▋    | 17133/30196 [35:37<24:10,  9.01it/s]

 57%|█████▋    | 17134/30196 [35:38<25:36,  8.50it/s]

 57%|█████▋    | 17136/30196 [35:38<27:42,  7.86it/s]

 57%|█████▋    | 17138/30196 [35:38<22:42,  9.59it/s]

 57%|█████▋    | 17140/30196 [35:38<24:37,  8.84it/s]

 57%|█████▋    | 17142/30196 [35:38<21:17, 10.22it/s]

 57%|█████▋    | 17144/30196 [35:38<18:49, 11.56it/s]

 57%|█████▋    | 17146/30196 [35:39<17:01, 12.77it/s]

 57%|█████▋    | 17149/30196 [35:39<17:12, 12.64it/s]

 57%|█████▋    | 17151/30196 [35:39<20:47, 10.46it/s]

 57%|█████▋    | 17153/30196 [35:39<20:54, 10.39it/s]

 57%|█████▋    | 17155/30196 [35:40<27:17,  7.96it/s]

 57%|█████▋    | 17156/30196 [35:40<26:32,  8.19it/s]

 57%|█████▋    | 17158/30196 [35:40<24:43,  8.79it/s]

 57%|█████▋    | 17161/30196 [35:40<22:12,  9.78it/s]

 57%|█████▋    | 17163/30196 [35:40<20:59, 10.34it/s]

 57%|█████▋    | 17165/30196 [35:41<20:27, 10.61it/s]

 57%|█████▋    | 17167/30196 [35:41<23:52,  9.10it/s]

 57%|█████▋    | 17168/30196 [35:41<26:18,  8.25it/s]

 57%|█████▋    | 17169/30196 [35:41<26:51,  8.08it/s]

 57%|█████▋    | 17170/30196 [35:41<29:03,  7.47it/s]

 57%|█████▋    | 17171/30196 [35:42<28:55,  7.50it/s]

 57%|█████▋    | 17172/30196 [35:42<30:44,  7.06it/s]

 57%|█████▋    | 17173/30196 [35:42<28:53,  7.51it/s]

 57%|█████▋    | 17175/30196 [35:42<23:06,  9.39it/s]

 57%|█████▋    | 17176/30196 [35:42<25:09,  8.63it/s]

 57%|█████▋    | 17177/30196 [35:43<48:09,  4.51it/s]

 57%|█████▋    | 17178/30196 [35:43<45:46,  4.74it/s]

 57%|█████▋    | 17180/30196 [35:43<38:52,  5.58it/s]

 57%|█████▋    | 17181/30196 [35:43<40:13,  5.39it/s]

 57%|█████▋    | 17183/30196 [35:43<29:43,  7.30it/s]

 57%|█████▋    | 17185/30196 [35:44<27:55,  7.77it/s]

 57%|█████▋    | 17187/30196 [35:44<24:45,  8.76it/s]

 57%|█████▋    | 17188/30196 [35:44<26:08,  8.29it/s]

 57%|█████▋    | 17189/30196 [35:44<26:38,  8.14it/s]

 57%|█████▋    | 17190/30196 [35:44<27:17,  7.94it/s]

 57%|█████▋    | 17192/30196 [35:44<24:01,  9.02it/s]

 57%|█████▋    | 17193/30196 [35:45<25:11,  8.60it/s]

 57%|█████▋    | 17194/30196 [35:45<32:11,  6.73it/s]

 57%|█████▋    | 17195/30196 [35:45<31:10,  6.95it/s]

 57%|█████▋    | 17196/30196 [35:45<30:22,  7.13it/s]

 57%|█████▋    | 17197/30196 [35:45<28:34,  7.58it/s]

 57%|█████▋    | 17199/30196 [35:45<22:19,  9.70it/s]

 57%|█████▋    | 17201/30196 [35:46<23:56,  9.05it/s]

 57%|█████▋    | 17202/30196 [35:46<23:52,  9.07it/s]

 57%|█████▋    | 17203/30196 [35:46<24:52,  8.71it/s]

 57%|█████▋    | 17205/30196 [35:46<21:58,  9.85it/s]

 57%|█████▋    | 17206/30196 [35:46<22:07,  9.78it/s]

 57%|█████▋    | 17208/30196 [35:46<18:09, 11.92it/s]

 57%|█████▋    | 17210/30196 [35:46<17:27, 12.40it/s]

 57%|█████▋    | 17212/30196 [35:47<20:16, 10.68it/s]

 57%|█████▋    | 17214/30196 [35:47<21:46,  9.94it/s]

 57%|█████▋    | 17216/30196 [35:47<19:14, 11.25it/s]

 57%|█████▋    | 17218/30196 [35:47<21:01, 10.29it/s]

 57%|█████▋    | 17220/30196 [35:47<23:33,  9.18it/s]

 57%|█████▋    | 17221/30196 [35:48<28:10,  7.67it/s]

 57%|█████▋    | 17223/30196 [35:48<28:13,  7.66it/s]

 57%|█████▋    | 17225/30196 [35:48<29:05,  7.43it/s]

 57%|█████▋    | 17226/30196 [35:49<51:27,  4.20it/s]

 57%|█████▋    | 17227/30196 [35:49<48:15,  4.48it/s]

 57%|█████▋    | 17228/30196 [35:49<50:58,  4.24it/s]

 57%|█████▋    | 17230/30196 [35:49<36:58,  5.85it/s]

 57%|█████▋    | 17231/30196 [35:50<35:09,  6.15it/s]

 57%|█████▋    | 17233/30196 [35:50<28:25,  7.60it/s]

 57%|█████▋    | 17234/30196 [35:50<27:26,  7.87it/s]

 57%|█████▋    | 17236/30196 [35:50<22:30,  9.60it/s]

 57%|█████▋    | 17238/30196 [35:50<20:38, 10.46it/s]

 57%|█████▋    | 17240/30196 [35:50<21:46,  9.91it/s]

 57%|█████▋    | 17242/30196 [35:51<21:35, 10.00it/s]

 57%|█████▋    | 17244/30196 [35:51<18:16, 11.81it/s]

 57%|█████▋    | 17246/30196 [35:51<26:13,  8.23it/s]

 57%|█████▋    | 17248/30196 [35:51<26:31,  8.14it/s]

 57%|█████▋    | 17249/30196 [35:52<47:52,  4.51it/s]

 57%|█████▋    | 17250/30196 [35:52<44:20,  4.87it/s]

 57%|█████▋    | 17251/30196 [35:52<45:28,  4.74it/s]

 57%|█████▋    | 17253/30196 [35:53<40:05,  5.38it/s]

 57%|█████▋    | 17254/30196 [35:53<36:15,  5.95it/s]

 57%|█████▋    | 17255/30196 [35:53<35:09,  6.13it/s]

 57%|█████▋    | 17257/30196 [35:53<27:29,  7.84it/s]

 57%|█████▋    | 17258/30196 [35:53<33:51,  6.37it/s]

 57%|█████▋    | 17259/30196 [35:53<32:41,  6.60it/s]

 57%|█████▋    | 17260/30196 [35:54<34:16,  6.29it/s]

 57%|█████▋    | 17261/30196 [35:54<32:39,  6.60it/s]

 57%|█████▋    | 17262/30196 [35:54<32:25,  6.65it/s]

 57%|█████▋    | 17263/30196 [35:54<36:18,  5.94it/s]

 57%|█████▋    | 17265/30196 [35:54<28:33,  7.54it/s]

 57%|█████▋    | 17267/30196 [35:54<24:22,  8.84it/s]

 57%|█████▋    | 17268/30196 [35:55<26:57,  7.99it/s]

 57%|█████▋    | 17271/30196 [35:55<21:07, 10.20it/s]

 57%|█████▋    | 17273/30196 [35:55<24:50,  8.67it/s]

 57%|█████▋    | 17274/30196 [35:55<30:34,  7.04it/s]

 57%|█████▋    | 17275/30196 [35:56<31:49,  6.77it/s]

 57%|█████▋    | 17277/30196 [35:56<29:36,  7.27it/s]

 57%|█████▋    | 17278/30196 [35:56<33:22,  6.45it/s]

 57%|█████▋    | 17279/30196 [35:56<33:01,  6.52it/s]

 57%|█████▋    | 17281/30196 [35:56<26:57,  7.99it/s]

 57%|█████▋    | 17283/30196 [35:56<22:30,  9.56it/s]

 57%|█████▋    | 17285/30196 [35:57<26:52,  8.00it/s]

 57%|█████▋    | 17287/30196 [35:57<36:01,  5.97it/s]

 57%|█████▋    | 17288/30196 [35:57<34:58,  6.15it/s]

 57%|█████▋    | 17290/30196 [35:58<31:37,  6.80it/s]

 57%|█████▋    | 17291/30196 [35:58<29:48,  7.22it/s]

 57%|█████▋    | 17292/30196 [35:58<29:23,  7.32it/s]

 57%|█████▋    | 17293/30196 [35:58<29:36,  7.26it/s]

 57%|█████▋    | 17294/30196 [35:58<31:50,  6.75it/s]

 57%|█████▋    | 17295/30196 [35:58<35:10,  6.11it/s]

 57%|█████▋    | 17296/30196 [35:59<31:57,  6.73it/s]

 57%|█████▋    | 17297/30196 [35:59<35:23,  6.07it/s]

 57%|█████▋    | 17298/30196 [35:59<31:48,  6.76it/s]

 57%|█████▋    | 17300/30196 [35:59<28:06,  7.65it/s]

 57%|█████▋    | 17302/30196 [35:59<29:06,  7.38it/s]

 57%|█████▋    | 17303/30196 [36:00<29:37,  7.25it/s]

 57%|█████▋    | 17304/30196 [36:00<27:55,  7.70it/s]

 57%|█████▋    | 17305/30196 [36:00<28:32,  7.53it/s]

 57%|█████▋    | 17307/30196 [36:00<25:40,  8.37it/s]

 57%|█████▋    | 17308/30196 [36:00<27:57,  7.68it/s]

 57%|█████▋    | 17309/30196 [36:00<26:52,  7.99it/s]

 57%|█████▋    | 17310/30196 [36:00<28:08,  7.63it/s]

 57%|█████▋    | 17311/30196 [36:01<27:31,  7.80it/s]

 57%|█████▋    | 17312/30196 [36:01<28:19,  7.58it/s]

 57%|█████▋    | 17314/30196 [36:01<26:17,  8.17it/s]

 57%|█████▋    | 17316/30196 [36:01<21:23, 10.03it/s]

 57%|█████▋    | 17318/30196 [36:01<20:40, 10.39it/s]

 57%|█████▋    | 17320/30196 [36:02<28:08,  7.62it/s]

 57%|█████▋    | 17322/30196 [36:02<23:24,  9.16it/s]

 57%|█████▋    | 17324/30196 [36:02<28:21,  7.57it/s]

 57%|█████▋    | 17326/30196 [36:02<23:52,  8.99it/s]

 57%|█████▋    | 17328/30196 [36:02<21:47,  9.84it/s]

 57%|█████▋    | 17330/30196 [36:03<23:07,  9.27it/s]

 57%|█████▋    | 17332/30196 [36:03<21:51,  9.81it/s]

 57%|█████▋    | 17334/30196 [36:03<28:24,  7.55it/s]

 57%|█████▋    | 17335/30196 [36:03<28:20,  7.56it/s]

 57%|█████▋    | 17337/30196 [36:04<30:15,  7.08it/s]

 57%|█████▋    | 17339/30196 [36:04<26:36,  8.05it/s]

 57%|█████▋    | 17341/30196 [36:04<22:41,  9.45it/s]

 57%|█████▋    | 17344/30196 [36:04<20:11, 10.61it/s]

 57%|█████▋    | 17346/30196 [36:05<24:45,  8.65it/s]

 57%|█████▋    | 17348/30196 [36:05<23:37,  9.06it/s]

 57%|█████▋    | 17349/30196 [36:05<27:18,  7.84it/s]

 57%|█████▋    | 17350/30196 [36:05<32:22,  6.61it/s]

 57%|█████▋    | 17351/30196 [36:05<32:01,  6.68it/s]

 57%|█████▋    | 17352/30196 [36:05<30:01,  7.13it/s]

 57%|█████▋    | 17354/30196 [36:06<27:45,  7.71it/s]

 57%|█████▋    | 17355/30196 [36:06<29:38,  7.22it/s]

 57%|█████▋    | 17357/30196 [36:06<28:00,  7.64it/s]

 57%|█████▋    | 17358/30196 [36:06<26:46,  7.99it/s]

 57%|█████▋    | 17360/30196 [36:06<21:59,  9.72it/s]

 57%|█████▋    | 17362/30196 [36:07<23:47,  8.99it/s]

 58%|█████▊    | 17363/30196 [36:07<24:38,  8.68it/s]

 58%|█████▊    | 17364/30196 [36:07<24:21,  8.78it/s]

 58%|█████▊    | 17365/30196 [36:07<24:39,  8.67it/s]

 58%|█████▊    | 17367/30196 [36:07<21:08, 10.11it/s]

 58%|█████▊    | 17369/30196 [36:07<21:01, 10.17it/s]

 58%|█████▊    | 17371/30196 [36:08<22:59,  9.30it/s]

 58%|█████▊    | 17372/30196 [36:08<22:50,  9.36it/s]

 58%|█████▊    | 17374/30196 [36:08<23:49,  8.97it/s]

 58%|█████▊    | 17375/30196 [36:08<23:44,  9.00it/s]

 58%|█████▊    | 17376/30196 [36:08<26:45,  7.99it/s]

 58%|█████▊    | 17377/30196 [36:08<32:13,  6.63it/s]

 58%|█████▊    | 17378/30196 [36:09<32:00,  6.67it/s]

 58%|█████▊    | 17379/30196 [36:09<31:30,  6.78it/s]

 58%|█████▊    | 17380/30196 [36:09<30:44,  6.95it/s]

 58%|█████▊    | 17381/30196 [36:09<32:13,  6.63it/s]

 58%|█████▊    | 17383/30196 [36:09<29:12,  7.31it/s]

 58%|█████▊    | 17384/30196 [36:09<32:47,  6.51it/s]

 58%|█████▊    | 17385/30196 [36:10<33:29,  6.38it/s]

 58%|█████▊    | 17386/30196 [36:10<39:05,  5.46it/s]

 58%|█████▊    | 17387/30196 [36:10<34:28,  6.19it/s]

 58%|█████▊    | 17388/30196 [36:11<1:07:14,  3.17it/s]

 58%|█████▊    | 17389/30196 [36:11<54:16,  3.93it/s]

 58%|█████▊    | 17390/30196 [36:11<46:49,  4.56it/s]

 58%|█████▊    | 17392/30196 [36:11<34:02,  6.27it/s]

 58%|█████▊    | 17393/30196 [36:11<35:08,  6.07it/s]

 58%|█████▊    | 17395/30196 [36:11<28:46,  7.41it/s]

 58%|█████▊    | 17397/30196 [36:12<26:16,  8.12it/s]

 58%|█████▊    | 17399/30196 [36:12<24:51,  8.58it/s]

 58%|█████▊    | 17401/30196 [36:12<22:30,  9.48it/s]

 58%|█████▊    | 17402/30196 [36:12<22:27,  9.50it/s]

 58%|█████▊    | 17403/30196 [36:12<32:38,  6.53it/s]

 58%|█████▊    | 17405/30196 [36:13<29:17,  7.28it/s]

 58%|█████▊    | 17406/30196 [36:13<30:31,  6.98it/s]

 58%|█████▊    | 17407/30196 [36:13<31:30,  6.77it/s]

 58%|█████▊    | 17409/30196 [36:13<27:12,  7.83it/s]

 58%|█████▊    | 17410/30196 [36:13<27:47,  7.67it/s]

 58%|█████▊    | 17412/30196 [36:14<24:31,  8.69it/s]

 58%|█████▊    | 17413/30196 [36:14<25:34,  8.33it/s]

 58%|█████▊    | 17415/30196 [36:14<20:59, 10.15it/s]

 58%|█████▊    | 17417/30196 [36:14<22:50,  9.33it/s]

 58%|█████▊    | 17419/30196 [36:14<20:02, 10.62it/s]

 58%|█████▊    | 17422/30196 [36:14<19:54, 10.69it/s]

 58%|█████▊    | 17424/30196 [36:15<17:46, 11.97it/s]

 58%|█████▊    | 17426/30196 [36:15<20:30, 10.38it/s]

 58%|█████▊    | 17428/30196 [36:15<22:55,  9.28it/s]

 58%|█████▊    | 17430/30196 [36:15<22:09,  9.60it/s]

 58%|█████▊    | 17432/30196 [36:16<27:31,  7.73it/s]

 58%|█████▊    | 17433/30196 [36:16<30:51,  6.89it/s]

 58%|█████▊    | 17435/30196 [36:16<27:21,  7.78it/s]

 58%|█████▊    | 17437/30196 [36:16<23:10,  9.17it/s]

 58%|█████▊    | 17439/30196 [36:16<22:14,  9.56it/s]

 58%|█████▊    | 17441/30196 [36:17<23:39,  8.99it/s]

 58%|█████▊    | 17443/30196 [36:17<22:46,  9.33it/s]

 58%|█████▊    | 17444/30196 [36:17<22:53,  9.28it/s]

 58%|█████▊    | 17445/30196 [36:17<24:18,  8.74it/s]

 58%|█████▊    | 17447/30196 [36:17<24:05,  8.82it/s]

 58%|█████▊    | 17448/30196 [36:18<29:05,  7.30it/s]

 58%|█████▊    | 17450/30196 [36:18<25:19,  8.39it/s]

 58%|█████▊    | 17451/30196 [36:18<24:55,  8.52it/s]

 58%|█████▊    | 17452/30196 [36:18<26:18,  8.07it/s]

 58%|█████▊    | 17453/30196 [36:18<27:12,  7.80it/s]

 58%|█████▊    | 17455/30196 [36:18<22:29,  9.44it/s]

 58%|█████▊    | 17456/30196 [36:18<25:57,  8.18it/s]

 58%|█████▊    | 17458/30196 [36:19<25:18,  8.39it/s]

 58%|█████▊    | 17459/30196 [36:19<24:36,  8.63it/s]

 58%|█████▊    | 17460/30196 [36:19<29:04,  7.30it/s]

 58%|█████▊    | 17461/30196 [36:19<30:39,  6.92it/s]

 58%|█████▊    | 17463/30196 [36:20<33:55,  6.26it/s]

 58%|█████▊    | 17465/30196 [36:20<26:52,  7.90it/s]

 58%|█████▊    | 17467/30196 [36:20<22:55,  9.25it/s]

 58%|█████▊    | 17469/30196 [36:20<23:23,  9.07it/s]

 58%|█████▊    | 17471/30196 [36:20<20:28, 10.36it/s]

 58%|█████▊    | 17473/30196 [36:20<18:03, 11.74it/s]

 58%|█████▊    | 17475/30196 [36:20<18:41, 11.34it/s]

 58%|█████▊    | 17477/30196 [36:21<20:11, 10.50it/s]

 58%|█████▊    | 17479/30196 [36:21<20:50, 10.17it/s]

 58%|█████▊    | 17481/30196 [36:21<20:25, 10.38it/s]

 58%|█████▊    | 17483/30196 [36:21<21:00, 10.09it/s]

 58%|█████▊    | 17485/30196 [36:22<22:21,  9.48it/s]

 58%|█████▊    | 17486/30196 [36:22<23:53,  8.86it/s]

 58%|█████▊    | 17488/30196 [36:22<21:09, 10.01it/s]

 58%|█████▊    | 17490/30196 [36:22<21:03, 10.06it/s]

 58%|█████▊    | 17492/30196 [36:22<19:13, 11.01it/s]

 58%|█████▊    | 17494/30196 [36:22<21:44,  9.74it/s]

 58%|█████▊    | 17496/30196 [36:23<22:15,  9.51it/s]

 58%|█████▊    | 17498/30196 [36:23<21:26,  9.87it/s]

 58%|█████▊    | 17500/30196 [36:23<20:46, 10.18it/s]

 58%|█████▊    | 17502/30196 [36:23<28:25,  7.44it/s]

 58%|█████▊    | 17503/30196 [36:24<28:25,  7.44it/s]

 58%|█████▊    | 17505/30196 [36:24<26:12,  8.07it/s]

 58%|█████▊    | 17506/30196 [36:24<25:37,  8.25it/s]

 58%|█████▊    | 17507/30196 [36:24<27:37,  7.65it/s]

 58%|█████▊    | 17508/30196 [36:24<26:33,  7.96it/s]

 58%|█████▊    | 17510/30196 [36:24<25:02,  8.44it/s]

 58%|█████▊    | 17511/30196 [36:25<25:48,  8.19it/s]

 58%|█████▊    | 17513/30196 [36:25<21:55,  9.64it/s]

 58%|█████▊    | 17515/30196 [36:25<22:14,  9.50it/s]

 58%|█████▊    | 17516/30196 [36:25<23:21,  9.05it/s]

 58%|█████▊    | 17518/30196 [36:25<19:54, 10.61it/s]

 58%|█████▊    | 17520/30196 [36:25<20:25, 10.35it/s]

 58%|█████▊    | 17522/30196 [36:26<23:04,  9.16it/s]

 58%|█████▊    | 17524/30196 [36:26<22:02,  9.58it/s]

 58%|█████▊    | 17525/30196 [36:26<24:29,  8.63it/s]

 58%|█████▊    | 17526/30196 [36:26<23:59,  8.80it/s]

 58%|█████▊    | 17527/30196 [36:26<23:46,  8.88it/s]

 58%|█████▊    | 17528/30196 [36:26<23:39,  8.93it/s]

 58%|█████▊    | 17530/30196 [36:27<23:16,  9.07it/s]

 58%|█████▊    | 17531/30196 [36:27<25:05,  8.41it/s]

 58%|█████▊    | 17532/30196 [36:27<27:27,  7.69it/s]

 58%|█████▊    | 17533/30196 [36:27<28:03,  7.52it/s]

 58%|█████▊    | 17535/30196 [36:27<25:50,  8.16it/s]

 58%|█████▊    | 17536/30196 [36:27<26:28,  7.97it/s]

 58%|█████▊    | 17538/30196 [36:28<25:08,  8.39it/s]

 58%|█████▊    | 17539/30196 [36:28<29:25,  7.17it/s]

 58%|█████▊    | 17540/30196 [36:28<28:59,  7.27it/s]

 58%|█████▊    | 17542/30196 [36:28<22:22,  9.43it/s]

 58%|█████▊    | 17544/30196 [36:28<24:42,  8.53it/s]

 58%|█████▊    | 17545/30196 [36:28<26:57,  7.82it/s]

 58%|█████▊    | 17548/30196 [36:29<21:09,  9.96it/s]

 58%|█████▊    | 17550/30196 [36:29<19:41, 10.70it/s]

 58%|█████▊    | 17552/30196 [36:29<19:08, 11.01it/s]

 58%|█████▊    | 17554/30196 [36:29<22:03,  9.55it/s]

 58%|█████▊    | 17556/30196 [36:30<25:04,  8.40it/s]

 58%|█████▊    | 17558/30196 [36:30<24:25,  8.62it/s]

 58%|█████▊    | 17560/30196 [36:30<24:25,  8.62it/s]

 58%|█████▊    | 17561/30196 [36:30<25:05,  8.39it/s]

 58%|█████▊    | 17563/30196 [36:30<22:18,  9.44it/s]

 58%|█████▊    | 17565/30196 [36:31<21:43,  9.69it/s]

 58%|█████▊    | 17567/30196 [36:31<21:17,  9.88it/s]

 58%|█████▊    | 17569/30196 [36:31<23:43,  8.87it/s]

 58%|█████▊    | 17571/30196 [36:31<25:28,  8.26it/s]

 58%|█████▊    | 17573/30196 [36:31<23:00,  9.15it/s]

 58%|█████▊    | 17575/30196 [36:32<21:14,  9.90it/s]

 58%|█████▊    | 17577/30196 [36:32<22:57,  9.16it/s]

 58%|█████▊    | 17579/30196 [36:32<21:55,  9.59it/s]

 58%|█████▊    | 17580/30196 [36:32<23:04,  9.11it/s]

 58%|█████▊    | 17581/30196 [36:32<22:56,  9.17it/s]

 58%|█████▊    | 17583/30196 [36:32<21:40,  9.70it/s]

 58%|█████▊    | 17584/30196 [36:33<23:00,  9.13it/s]

 58%|█████▊    | 17585/30196 [36:33<46:28,  4.52it/s]

 58%|█████▊    | 17587/30196 [36:33<33:23,  6.29it/s]

 58%|█████▊    | 17589/30196 [36:34<28:37,  7.34it/s]

 58%|█████▊    | 17591/30196 [36:34<26:04,  8.06it/s]

 58%|█████▊    | 17592/30196 [36:34<28:09,  7.46it/s]

 58%|█████▊    | 17593/30196 [36:34<29:43,  7.07it/s]

 58%|█████▊    | 17595/30196 [36:34<24:54,  8.43it/s]

 58%|█████▊    | 17596/30196 [36:34<25:27,  8.25it/s]

 58%|█████▊    | 17597/30196 [36:35<30:28,  6.89it/s]

 58%|█████▊    | 17599/30196 [36:35<28:15,  7.43it/s]

 58%|█████▊    | 17601/30196 [36:35<25:23,  8.26it/s]

 58%|█████▊    | 17603/30196 [36:35<22:33,  9.30it/s]

 58%|█████▊    | 17604/30196 [36:35<25:11,  8.33it/s]

 58%|█████▊    | 17606/30196 [36:36<32:54,  6.38it/s]

 58%|█████▊    | 17608/30196 [36:36<30:57,  6.78it/s]

 58%|█████▊    | 17609/30196 [36:36<30:28,  6.88it/s]

 58%|█████▊    | 17611/30196 [36:36<26:04,  8.04it/s]

 58%|█████▊    | 17612/30196 [36:36<25:27,  8.24it/s]

 58%|█████▊    | 17614/30196 [36:37<22:11,  9.45it/s]

 58%|█████▊    | 17616/30196 [36:37<23:24,  8.96it/s]

 58%|█████▊    | 17618/30196 [36:37<21:28,  9.76it/s]

 58%|█████▊    | 17620/30196 [36:37<20:29, 10.23it/s]

 58%|█████▊    | 17622/30196 [36:37<19:58, 10.49it/s]

 58%|█████▊    | 17624/30196 [36:38<19:10, 10.92it/s]

 58%|█████▊    | 17626/30196 [36:38<21:21,  9.81it/s]

 58%|█████▊    | 17628/30196 [36:38<22:39,  9.25it/s]

 58%|█████▊    | 17630/30196 [36:38<22:22,  9.36it/s]

 58%|█████▊    | 17631/30196 [36:38<23:15,  9.01it/s]

 58%|█████▊    | 17633/30196 [36:39<22:32,  9.29it/s]

 58%|█████▊    | 17634/30196 [36:39<23:53,  8.76it/s]

 58%|█████▊    | 17635/30196 [36:39<24:52,  8.42it/s]

 58%|█████▊    | 17637/30196 [36:39<27:26,  7.63it/s]

 58%|█████▊    | 17639/30196 [36:39<22:47,  9.18it/s]

 58%|█████▊    | 17640/30196 [36:39<24:24,  8.57it/s]

 58%|█████▊    | 17641/30196 [36:40<24:04,  8.69it/s]

 58%|█████▊    | 17642/30196 [36:40<24:49,  8.43it/s]

 58%|█████▊    | 17643/30196 [36:40<25:32,  8.19it/s]

 58%|█████▊    | 17644/30196 [36:40<26:35,  7.87it/s]

 58%|█████▊    | 17646/30196 [36:40<25:10,  8.31it/s]

 58%|█████▊    | 17647/30196 [36:40<26:05,  8.02it/s]

 58%|█████▊    | 17648/30196 [36:41<30:41,  6.82it/s]

 58%|█████▊    | 17650/30196 [36:41<29:01,  7.20it/s]

 58%|█████▊    | 17652/30196 [36:41<26:16,  7.96it/s]

 58%|█████▊    | 17654/30196 [36:41<21:45,  9.61it/s]

 58%|█████▊    | 17656/30196 [36:41<19:00, 10.99it/s]

 58%|█████▊    | 17658/30196 [36:41<19:09, 10.91it/s]

 58%|█████▊    | 17660/30196 [36:42<22:08,  9.44it/s]

 58%|█████▊    | 17662/30196 [36:42<21:35,  9.68it/s]

 58%|█████▊    | 17664/30196 [36:42<23:49,  8.77it/s]

 59%|█████▊    | 17666/30196 [36:43<39:09,  5.33it/s]

 59%|█████▊    | 17667/30196 [36:43<36:18,  5.75it/s]

 59%|█████▊    | 17669/30196 [36:43<27:55,  7.48it/s]

 59%|█████▊    | 17671/30196 [36:43<24:57,  8.36it/s]

 59%|█████▊    | 17673/30196 [36:43<23:07,  9.03it/s]

 59%|█████▊    | 17675/30196 [36:44<21:17,  9.80it/s]

 59%|█████▊    | 17677/30196 [36:44<24:36,  8.48it/s]

 59%|█████▊    | 17678/30196 [36:44<28:51,  7.23it/s]

 59%|█████▊    | 17679/30196 [36:44<30:34,  6.82it/s]

 59%|█████▊    | 17681/30196 [36:45<25:05,  8.31it/s]

 59%|█████▊    | 17682/30196 [36:45<28:52,  7.22it/s]

 59%|█████▊    | 17683/30196 [36:45<34:24,  6.06it/s]

 59%|█████▊    | 17684/30196 [36:45<32:54,  6.34it/s]

 59%|█████▊    | 17685/30196 [36:45<31:36,  6.60it/s]

 59%|█████▊    | 17686/30196 [36:45<30:39,  6.80it/s]

 59%|█████▊    | 17688/30196 [36:46<23:22,  8.92it/s]

 59%|█████▊    | 17689/30196 [36:46<26:57,  7.73it/s]

 59%|█████▊    | 17691/30196 [36:46<21:32,  9.68it/s]

 59%|█████▊    | 17693/30196 [36:46<19:50, 10.50it/s]

 59%|█████▊    | 17695/30196 [36:46<18:17, 11.39it/s]

 59%|█████▊    | 17697/30196 [36:46<18:50, 11.05it/s]

 59%|█████▊    | 17699/30196 [36:47<19:21, 10.76it/s]

 59%|█████▊    | 17701/30196 [36:47<20:57,  9.93it/s]

 59%|█████▊    | 17703/30196 [36:47<21:13,  9.81it/s]

 59%|█████▊    | 17705/30196 [36:47<27:02,  7.70it/s]

 59%|█████▊    | 17707/30196 [36:47<23:07,  9.00it/s]

 59%|█████▊    | 17709/30196 [36:48<20:41, 10.06it/s]

 59%|█████▊    | 17711/30196 [36:48<21:18,  9.77it/s]

 59%|█████▊    | 17713/30196 [36:48<23:31,  8.85it/s]

 59%|█████▊    | 17714/30196 [36:48<23:23,  8.89it/s]

 59%|█████▊    | 17715/30196 [36:49<31:17,  6.65it/s]

 59%|█████▊    | 17717/30196 [36:49<26:25,  7.87it/s]

 59%|█████▊    | 17718/30196 [36:49<28:07,  7.40it/s]

 59%|█████▊    | 17720/30196 [36:49<21:47,  9.54it/s]

 59%|█████▊    | 17722/30196 [36:49<22:54,  9.07it/s]

 59%|█████▊    | 17725/30196 [36:49<18:01, 11.54it/s]

 59%|█████▊    | 17727/30196 [36:50<22:07,  9.39it/s]

 59%|█████▊    | 17729/30196 [36:50<27:12,  7.63it/s]

 59%|█████▊    | 17730/30196 [36:50<27:49,  7.47it/s]

 59%|█████▊    | 17732/30196 [36:50<26:15,  7.91it/s]

 59%|█████▊    | 17734/30196 [36:51<24:11,  8.59it/s]

 59%|█████▊    | 17736/30196 [36:51<22:46,  9.12it/s]

 59%|█████▊    | 17738/30196 [36:51<23:50,  8.71it/s]

 59%|█████▊    | 17739/30196 [36:51<31:37,  6.56it/s]

 59%|█████▊    | 17740/30196 [36:52<31:23,  6.61it/s]

 59%|█████▉    | 17742/30196 [36:52<31:04,  6.68it/s]

 59%|█████▉    | 17744/30196 [36:52<29:30,  7.03it/s]

 59%|█████▉    | 17746/30196 [36:52<25:51,  8.02it/s]

 59%|█████▉    | 17748/30196 [36:52<21:55,  9.46it/s]

 59%|█████▉    | 17750/30196 [36:53<28:05,  7.38it/s]

 59%|█████▉    | 17751/30196 [36:53<26:56,  7.70it/s]

 59%|█████▉    | 17752/30196 [36:53<26:05,  7.95it/s]

 59%|█████▉    | 17753/30196 [36:53<28:07,  7.38it/s]

 59%|█████▉    | 17754/30196 [36:53<28:25,  7.29it/s]

 59%|█████▉    | 17756/30196 [36:53<21:52,  9.48it/s]

 59%|█████▉    | 17758/30196 [36:54<24:50,  8.35it/s]

 59%|█████▉    | 17760/30196 [36:54<22:50,  9.07it/s]

 59%|█████▉    | 17761/30196 [36:54<34:11,  6.06it/s]

 59%|█████▉    | 17763/30196 [36:55<29:07,  7.12it/s]

 59%|█████▉    | 17765/30196 [36:55<22:52,  9.05it/s]

 59%|█████▉    | 17767/30196 [36:55<22:27,  9.23it/s]

 59%|█████▉    | 17769/30196 [36:55<21:30,  9.63it/s]

 59%|█████▉    | 17771/30196 [36:55<20:29, 10.11it/s]

 59%|█████▉    | 17773/30196 [36:56<29:23,  7.05it/s]

 59%|█████▉    | 17775/30196 [36:56<34:50,  5.94it/s]

 59%|█████▉    | 17777/30196 [36:56<28:21,  7.30it/s]

 59%|█████▉    | 17778/30196 [36:56<30:51,  6.71it/s]

 59%|█████▉    | 17779/30196 [36:57<30:45,  6.73it/s]

 59%|█████▉    | 17781/30196 [36:57<24:54,  8.30it/s]

 59%|█████▉    | 17782/30196 [36:57<25:29,  8.12it/s]

 59%|█████▉    | 17783/30196 [36:57<44:57,  4.60it/s]

 59%|█████▉    | 17784/30196 [36:58<42:28,  4.87it/s]

 59%|█████▉    | 17786/30196 [36:58<31:44,  6.52it/s]

 59%|█████▉    | 17788/30196 [36:58<25:53,  7.99it/s]

 59%|█████▉    | 17790/30196 [36:58<21:46,  9.50it/s]

 59%|█████▉    | 17792/30196 [36:58<21:57,  9.41it/s]

 59%|█████▉    | 17794/30196 [36:59<24:07,  8.57it/s]

 59%|█████▉    | 17796/30196 [36:59<23:06,  8.94it/s]

 59%|█████▉    | 17798/30196 [36:59<25:07,  8.23it/s]

 59%|█████▉    | 17799/30196 [36:59<26:06,  7.92it/s]

 59%|█████▉    | 17801/30196 [36:59<23:02,  8.96it/s]

 59%|█████▉    | 17803/30196 [37:00<26:11,  7.89it/s]

 59%|█████▉    | 17806/30196 [37:00<22:19,  9.25it/s]

 59%|█████▉    | 17807/30196 [37:00<23:15,  8.88it/s]

 59%|█████▉    | 17808/30196 [37:00<24:22,  8.47it/s]

 59%|█████▉    | 17809/30196 [37:00<26:36,  7.76it/s]

 59%|█████▉    | 17810/30196 [37:00<26:40,  7.74it/s]

 59%|█████▉    | 17812/30196 [37:01<24:09,  8.54it/s]

 59%|█████▉    | 17813/30196 [37:01<25:14,  8.17it/s]

 59%|█████▉    | 17814/30196 [37:01<27:26,  7.52it/s]

 59%|█████▉    | 17815/30196 [37:01<25:57,  7.95it/s]

 59%|█████▉    | 17816/30196 [37:01<27:10,  7.59it/s]

 59%|█████▉    | 17817/30196 [37:01<29:08,  7.08it/s]

 59%|█████▉    | 17818/30196 [37:02<27:21,  7.54it/s]

 59%|█████▉    | 17819/30196 [37:02<25:42,  8.02it/s]

 59%|█████▉    | 17821/30196 [37:02<19:35, 10.52it/s]

 59%|█████▉    | 17823/30196 [37:02<22:14,  9.27it/s]

 59%|█████▉    | 17825/30196 [37:02<19:33, 10.54it/s]

 59%|█████▉    | 17827/30196 [37:03<28:06,  7.33it/s]

 59%|█████▉    | 17828/30196 [37:03<29:27,  7.00it/s]

 59%|█████▉    | 17830/30196 [37:03<28:18,  7.28it/s]

 59%|█████▉    | 17832/30196 [37:03<26:11,  7.87it/s]

 59%|█████▉    | 17833/30196 [37:03<26:31,  7.77it/s]

 59%|█████▉    | 17835/30196 [37:03<22:22,  9.21it/s]

 59%|█████▉    | 17836/30196 [37:04<23:27,  8.78it/s]

 59%|█████▉    | 17837/30196 [37:04<26:27,  7.79it/s]

 59%|█████▉    | 17838/30196 [37:04<28:21,  7.26it/s]

 59%|█████▉    | 17839/30196 [37:04<27:59,  7.36it/s]

 59%|█████▉    | 17840/30196 [37:04<28:32,  7.21it/s]

 59%|█████▉    | 17842/30196 [37:04<21:25,  9.61it/s]

 59%|█████▉    | 17844/30196 [37:05<26:17,  7.83it/s]

 59%|█████▉    | 17846/30196 [37:05<22:46,  9.04it/s]

 59%|█████▉    | 17848/30196 [37:05<26:07,  7.88it/s]

 59%|█████▉    | 17850/30196 [37:05<23:08,  8.89it/s]

 59%|█████▉    | 17851/30196 [37:05<23:03,  8.92it/s]

 59%|█████▉    | 17853/30196 [37:06<21:21,  9.63it/s]

 59%|█████▉    | 17855/30196 [37:06<20:55,  9.83it/s]

 59%|█████▉    | 17857/30196 [37:06<20:38,  9.96it/s]

 59%|█████▉    | 17859/30196 [37:06<20:54,  9.84it/s]

 59%|█████▉    | 17861/30196 [37:07<28:46,  7.15it/s]

 59%|█████▉    | 17862/30196 [37:07<28:34,  7.19it/s]

 59%|█████▉    | 17864/30196 [37:07<24:28,  8.40it/s]

 59%|█████▉    | 17865/30196 [37:07<23:54,  8.60it/s]

 59%|█████▉    | 17866/30196 [37:07<23:27,  8.76it/s]

 59%|█████▉    | 17867/30196 [37:07<23:43,  8.66it/s]

 59%|█████▉    | 17869/30196 [37:08<22:56,  8.96it/s]

 59%|█████▉    | 17870/30196 [37:08<27:14,  7.54it/s]

 59%|█████▉    | 17871/30196 [37:08<28:23,  7.23it/s]

 59%|█████▉    | 17872/30196 [37:08<30:18,  6.78it/s]

 59%|█████▉    | 17874/30196 [37:08<23:24,  8.77it/s]

 59%|█████▉    | 17875/30196 [37:08<24:21,  8.43it/s]

 59%|█████▉    | 17876/30196 [37:08<26:43,  7.68it/s]

 59%|█████▉    | 17877/30196 [37:09<29:17,  7.01it/s]

 59%|█████▉    | 17878/30196 [37:09<33:07,  6.20it/s]

 59%|█████▉    | 17879/30196 [37:09<31:59,  6.42it/s]

 59%|█████▉    | 17880/30196 [37:09<32:38,  6.29it/s]

 59%|█████▉    | 17881/30196 [37:09<33:00,  6.22it/s]

 59%|█████▉    | 17882/30196 [37:09<29:58,  6.85it/s]

 59%|█████▉    | 17884/30196 [37:10<24:48,  8.27it/s]

 59%|█████▉    | 17885/30196 [37:10<29:28,  6.96it/s]

 59%|█████▉    | 17886/30196 [37:10<42:31,  4.82it/s]

 59%|█████▉    | 17888/30196 [37:11<40:11,  5.10it/s]

 59%|█████▉    | 17889/30196 [37:11<37:17,  5.50it/s]

 59%|█████▉    | 17890/30196 [37:11<33:34,  6.11it/s]

 59%|█████▉    | 17892/30196 [37:11<29:45,  6.89it/s]

 59%|█████▉    | 17894/30196 [37:11<29:26,  6.96it/s]

 59%|█████▉    | 17896/30196 [37:11<23:57,  8.56it/s]

 59%|█████▉    | 17897/30196 [37:12<23:26,  8.74it/s]

 59%|█████▉    | 17898/30196 [37:12<24:24,  8.40it/s]

 59%|█████▉    | 17900/30196 [37:12<19:36, 10.45it/s]

 59%|█████▉    | 17902/30196 [37:12<17:52, 11.46it/s]

 59%|█████▉    | 17904/30196 [37:12<17:01, 12.03it/s]

 59%|█████▉    | 17906/30196 [37:12<21:54,  9.35it/s]

 59%|█████▉    | 17908/30196 [37:13<24:18,  8.43it/s]

 59%|█████▉    | 17909/30196 [37:13<24:55,  8.22it/s]

 59%|█████▉    | 17910/30196 [37:13<26:55,  7.61it/s]

 59%|█████▉    | 17911/30196 [37:13<28:29,  7.19it/s]

 59%|█████▉    | 17913/30196 [37:14<30:33,  6.70it/s]

 59%|█████▉    | 17914/30196 [37:14<31:27,  6.51it/s]

 59%|█████▉    | 17916/30196 [37:14<24:32,  8.34it/s]

 59%|█████▉    | 17917/30196 [37:14<23:52,  8.57it/s]

 59%|█████▉    | 17918/30196 [37:14<23:14,  8.80it/s]

 59%|█████▉    | 17919/30196 [37:14<23:00,  8.89it/s]

 59%|█████▉    | 17920/30196 [37:14<22:34,  9.06it/s]

 59%|█████▉    | 17922/30196 [37:14<20:36,  9.92it/s]

 59%|█████▉    | 17924/30196 [37:15<17:43, 11.54it/s]

 59%|█████▉    | 17926/30196 [37:15<20:14, 10.10it/s]

 59%|█████▉    | 17928/30196 [37:15<24:16,  8.42it/s]

 59%|█████▉    | 17929/30196 [37:15<31:27,  6.50it/s]

 59%|█████▉    | 17931/30196 [37:16<26:07,  7.83it/s]

 59%|█████▉    | 17933/30196 [37:16<23:30,  8.69it/s]

 59%|█████▉    | 17934/30196 [37:16<27:16,  7.49it/s]

 59%|█████▉    | 17935/30196 [37:16<27:20,  7.47it/s]

 59%|█████▉    | 17936/30196 [37:16<27:30,  7.43it/s]

 59%|█████▉    | 17937/30196 [37:16<27:33,  7.42it/s]

 59%|█████▉    | 17939/30196 [37:17<26:21,  7.75it/s]

 59%|█████▉    | 17941/30196 [37:17<20:34,  9.93it/s]

 59%|█████▉    | 17943/30196 [37:17<20:34,  9.93it/s]

 59%|█████▉    | 17945/30196 [37:17<25:17,  8.07it/s]

 59%|█████▉    | 17946/30196 [37:18<30:16,  6.74it/s]

 59%|█████▉    | 17947/30196 [37:18<29:39,  6.88it/s]

 59%|█████▉    | 17948/30196 [37:18<27:59,  7.29it/s]

 59%|█████▉    | 17949/30196 [37:18<28:28,  7.17it/s]

 59%|█████▉    | 17951/30196 [37:18<23:01,  8.86it/s]

 59%|█████▉    | 17953/30196 [37:18<20:25,  9.99it/s]

 59%|█████▉    | 17955/30196 [37:18<20:26,  9.98it/s]

 59%|█████▉    | 17957/30196 [37:19<21:46,  9.37it/s]

 59%|█████▉    | 17959/30196 [37:19<22:33,  9.04it/s]

 59%|█████▉    | 17961/30196 [37:19<21:22,  9.54it/s]

 59%|█████▉    | 17962/30196 [37:19<22:19,  9.13it/s]

 59%|█████▉    | 17964/30196 [37:19<19:51, 10.26it/s]

 59%|█████▉    | 17966/30196 [37:20<22:22,  9.11it/s]

 60%|█████▉    | 17967/30196 [37:20<26:18,  7.74it/s]

 60%|█████▉    | 17969/30196 [37:20<24:26,  8.34it/s]

 60%|█████▉    | 17971/30196 [37:20<21:54,  9.30it/s]

 60%|█████▉    | 17972/30196 [37:20<23:25,  8.70it/s]

 60%|█████▉    | 17974/30196 [37:21<21:28,  9.48it/s]

 60%|█████▉    | 17975/30196 [37:21<23:12,  8.78it/s]

 60%|█████▉    | 17976/30196 [37:21<22:49,  8.92it/s]

 60%|█████▉    | 17977/30196 [37:21<27:32,  7.40it/s]

 60%|█████▉    | 17978/30196 [37:21<34:53,  5.83it/s]

 60%|█████▉    | 17979/30196 [37:21<31:32,  6.46it/s]

 60%|█████▉    | 17981/30196 [37:22<27:17,  7.46it/s]

 60%|█████▉    | 17982/30196 [37:22<56:10,  3.62it/s]

 60%|█████▉    | 17984/30196 [37:23<51:58,  3.92it/s]

 60%|█████▉    | 17986/30196 [37:23<37:44,  5.39it/s]

 60%|█████▉    | 17987/30196 [37:23<38:50,  5.24it/s]

 60%|█████▉    | 17988/30196 [37:23<35:03,  5.80it/s]

 60%|█████▉    | 17990/30196 [37:24<34:23,  5.92it/s]

 60%|█████▉    | 17992/30196 [37:24<32:20,  6.29it/s]

 60%|█████▉    | 17993/30196 [37:24<33:13,  6.12it/s]

 60%|█████▉    | 17994/30196 [37:24<31:53,  6.38it/s]

 60%|█████▉    | 17995/30196 [37:24<29:35,  6.87it/s]

 60%|█████▉    | 17996/30196 [37:24<32:45,  6.21it/s]

 60%|█████▉    | 17998/30196 [37:25<25:53,  7.85it/s]

 60%|█████▉    | 17999/30196 [37:25<26:48,  7.58it/s]

 60%|█████▉    | 18001/30196 [37:25<22:52,  8.89it/s]

 60%|█████▉    | 18003/30196 [37:25<20:37,  9.85it/s]

 60%|█████▉    | 18005/30196 [37:25<22:37,  8.98it/s]

 60%|█████▉    | 18006/30196 [37:26<23:19,  8.71it/s]

 60%|█████▉    | 18007/30196 [37:26<25:44,  7.89it/s]

 60%|█████▉    | 18008/30196 [37:26<26:23,  7.70it/s]

 60%|█████▉    | 18009/30196 [37:26<28:35,  7.11it/s]

 60%|█████▉    | 18010/30196 [37:26<30:44,  6.61it/s]

 60%|█████▉    | 18012/30196 [37:26<26:37,  7.63it/s]

 60%|█████▉    | 18013/30196 [37:27<28:18,  7.17it/s]

 60%|█████▉    | 18015/30196 [37:27<22:50,  8.89it/s]

 60%|█████▉    | 18016/30196 [37:27<25:14,  8.04it/s]

 60%|█████▉    | 18017/30196 [37:27<26:21,  7.70it/s]

 60%|█████▉    | 18018/30196 [37:27<44:11,  4.59it/s]

 60%|█████▉    | 18019/30196 [37:28<42:04,  4.82it/s]

 60%|█████▉    | 18021/30196 [37:28<30:20,  6.69it/s]

 60%|█████▉    | 18023/30196 [37:28<24:46,  8.19it/s]

 60%|█████▉    | 18025/30196 [37:28<20:05, 10.09it/s]

 60%|█████▉    | 18027/30196 [37:28<18:26, 11.00it/s]

 60%|█████▉    | 18029/30196 [37:28<18:35, 10.91it/s]

 60%|█████▉    | 18031/30196 [37:29<21:58,  9.23it/s]

 60%|█████▉    | 18033/30196 [37:29<24:49,  8.16it/s]

 60%|█████▉    | 18035/30196 [37:29<27:29,  7.37it/s]

 60%|█████▉    | 18037/30196 [37:30<29:09,  6.95it/s]

 60%|█████▉    | 18039/30196 [37:30<23:57,  8.46it/s]

 60%|█████▉    | 18041/30196 [37:30<28:25,  7.13it/s]

 60%|█████▉    | 18043/30196 [37:30<23:23,  8.66it/s]

 60%|█████▉    | 18045/30196 [37:31<25:43,  7.87it/s]

 60%|█████▉    | 18046/30196 [37:31<25:48,  7.84it/s]

 60%|█████▉    | 18048/30196 [37:31<22:34,  8.97it/s]

 60%|█████▉    | 18050/30196 [37:31<19:54, 10.16it/s]

 60%|█████▉    | 18052/30196 [37:31<18:47, 10.77it/s]

 60%|█████▉    | 18054/30196 [37:31<19:44, 10.25it/s]

 60%|█████▉    | 18056/30196 [37:32<21:50,  9.27it/s]

 60%|█████▉    | 18057/30196 [37:32<21:53,  9.24it/s]

 60%|█████▉    | 18058/30196 [37:32<22:49,  8.86it/s]

 60%|█████▉    | 18059/30196 [37:32<24:04,  8.40it/s]

 60%|█████▉    | 18060/30196 [37:32<26:24,  7.66it/s]

 60%|█████▉    | 18062/30196 [37:32<21:41,  9.32it/s]

 60%|█████▉    | 18063/30196 [37:32<23:00,  8.79it/s]

 60%|█████▉    | 18065/30196 [37:33<21:43,  9.31it/s]

 60%|█████▉    | 18067/30196 [37:33<24:22,  8.29it/s]

 60%|█████▉    | 18068/30196 [37:33<23:42,  8.53it/s]

 60%|█████▉    | 18069/30196 [37:33<25:57,  7.78it/s]

 60%|█████▉    | 18071/30196 [37:33<22:00,  9.19it/s]

 60%|█████▉    | 18073/30196 [37:34<21:12,  9.53it/s]

 60%|█████▉    | 18075/30196 [37:34<17:44, 11.39it/s]

 60%|█████▉    | 18077/30196 [37:34<19:12, 10.51it/s]

 60%|█████▉    | 18079/30196 [37:34<21:53,  9.23it/s]

 60%|█████▉    | 18081/30196 [37:34<22:46,  8.86it/s]

 60%|█████▉    | 18083/30196 [37:35<22:12,  9.09it/s]

 60%|█████▉    | 18084/30196 [37:35<22:03,  9.15it/s]

 60%|█████▉    | 18085/30196 [37:35<26:18,  7.67it/s]

 60%|█████▉    | 18086/30196 [37:35<26:17,  7.67it/s]

 60%|█████▉    | 18088/30196 [37:35<23:08,  8.72it/s]

 60%|█████▉    | 18089/30196 [37:35<23:50,  8.47it/s]

 60%|█████▉    | 18091/30196 [37:36<20:31,  9.83it/s]

 60%|█████▉    | 18093/30196 [37:36<20:12,  9.98it/s]

 60%|█████▉    | 18095/30196 [37:36<20:21,  9.90it/s]

 60%|█████▉    | 18096/30196 [37:36<23:09,  8.71it/s]

 60%|█████▉    | 18097/30196 [37:36<27:30,  7.33it/s]

 60%|█████▉    | 18099/30196 [37:37<22:48,  8.84it/s]

 60%|█████▉    | 18100/30196 [37:37<28:52,  6.98it/s]

 60%|█████▉    | 18102/30196 [37:37<26:17,  7.67it/s]

 60%|█████▉    | 18103/30196 [37:37<27:45,  7.26it/s]

 60%|█████▉    | 18104/30196 [37:37<27:35,  7.30it/s]

 60%|█████▉    | 18105/30196 [37:37<27:49,  7.24it/s]

 60%|█████▉    | 18106/30196 [37:38<26:01,  7.74it/s]

 60%|█████▉    | 18108/30196 [37:38<22:21,  9.01it/s]

 60%|█████▉    | 18109/30196 [37:38<29:34,  6.81it/s]

 60%|█████▉    | 18110/30196 [37:39<51:14,  3.93it/s]

 60%|█████▉    | 18112/30196 [37:39<36:51,  5.46it/s]

 60%|█████▉    | 18113/30196 [37:39<34:37,  5.82it/s]

 60%|█████▉    | 18115/30196 [37:39<28:56,  6.96it/s]

 60%|█████▉    | 18116/30196 [37:39<27:14,  7.39it/s]

 60%|██████    | 18118/30196 [37:39<23:08,  8.70it/s]

 60%|██████    | 18119/30196 [37:39<25:54,  7.77it/s]

 60%|██████    | 18120/30196 [37:40<26:13,  7.68it/s]

 60%|██████    | 18122/30196 [37:40<19:49, 10.15it/s]

 60%|██████    | 18124/30196 [37:40<19:08, 10.51it/s]

 60%|██████    | 18126/30196 [37:40<20:07, 10.00it/s]

 60%|██████    | 18128/30196 [37:40<24:51,  8.09it/s]

 60%|██████    | 18129/30196 [37:41<25:16,  7.96it/s]

 60%|██████    | 18130/30196 [37:41<29:39,  6.78it/s]

 60%|██████    | 18132/30196 [37:41<24:05,  8.35it/s]

 60%|██████    | 18133/30196 [37:41<24:45,  8.12it/s]

 60%|██████    | 18134/30196 [37:41<25:43,  7.82it/s]

 60%|██████    | 18135/30196 [37:42<53:11,  3.78it/s]

 60%|██████    | 18137/30196 [37:42<37:07,  5.41it/s]

 60%|██████    | 18139/30196 [37:42<30:05,  6.68it/s]

 60%|██████    | 18140/30196 [37:42<29:17,  6.86it/s]

 60%|██████    | 18142/30196 [37:43<22:50,  8.79it/s]

 60%|██████    | 18144/30196 [37:43<22:25,  8.96it/s]

 60%|██████    | 18146/30196 [37:43<19:29, 10.30it/s]

 60%|██████    | 18148/30196 [37:43<20:24,  9.84it/s]

 60%|██████    | 18150/30196 [37:43<26:33,  7.56it/s]

 60%|██████    | 18152/30196 [37:44<25:19,  7.92it/s]

 60%|██████    | 18154/30196 [37:44<24:12,  8.29it/s]

 60%|██████    | 18155/30196 [37:44<24:56,  8.05it/s]

 60%|██████    | 18157/30196 [37:44<22:02,  9.10it/s]

 60%|██████    | 18158/30196 [37:44<27:39,  7.26it/s]

 60%|██████    | 18159/30196 [37:45<28:55,  6.93it/s]

 60%|██████    | 18160/30196 [37:45<30:05,  6.67it/s]

 60%|██████    | 18162/30196 [37:45<22:37,  8.87it/s]

 60%|██████    | 18164/30196 [37:45<20:18,  9.88it/s]

 60%|██████    | 18166/30196 [37:45<19:29, 10.29it/s]

 60%|██████    | 18168/30196 [37:46<21:49,  9.19it/s]

 60%|██████    | 18169/30196 [37:46<23:08,  8.66it/s]

 60%|██████    | 18170/30196 [37:46<22:41,  8.83it/s]

 60%|██████    | 18171/30196 [37:46<37:00,  5.42it/s]

 60%|██████    | 18172/30196 [37:46<33:14,  6.03it/s]

 60%|██████    | 18173/30196 [37:47<35:27,  5.65it/s]

 60%|██████    | 18174/30196 [37:47<33:48,  5.93it/s]

 60%|██████    | 18175/30196 [37:47<34:04,  5.88it/s]

 60%|██████    | 18176/30196 [37:47<32:42,  6.12it/s]

 60%|██████    | 18178/30196 [37:47<22:59,  8.71it/s]

 60%|██████    | 18180/30196 [37:47<18:36, 10.76it/s]

 60%|██████    | 18182/30196 [37:47<18:52, 10.61it/s]

 60%|██████    | 18184/30196 [37:48<21:19,  9.39it/s]

 60%|██████    | 18186/30196 [37:48<24:25,  8.19it/s]

 60%|██████    | 18187/30196 [37:48<26:06,  7.66it/s]

 60%|██████    | 18188/30196 [37:48<26:07,  7.66it/s]

 60%|██████    | 18189/30196 [37:48<26:18,  7.61it/s]

 60%|██████    | 18191/30196 [37:49<25:25,  7.87it/s]

 60%|██████    | 18193/30196 [37:49<24:19,  8.23it/s]

 60%|██████    | 18195/30196 [37:49<19:40, 10.16it/s]

 60%|██████    | 18197/30196 [37:49<19:03, 10.49it/s]

 60%|██████    | 18199/30196 [37:49<19:11, 10.41it/s]

 60%|██████    | 18201/30196 [37:50<23:55,  8.35it/s]

 60%|██████    | 18203/30196 [37:50<24:01,  8.32it/s]

 60%|██████    | 18204/30196 [37:50<26:09,  7.64it/s]

 60%|██████    | 18205/30196 [37:50<26:19,  7.59it/s]

 60%|██████    | 18207/30196 [37:50<23:30,  8.50it/s]

 60%|██████    | 18208/30196 [37:51<27:58,  7.14it/s]

 60%|██████    | 18210/30196 [37:51<25:26,  7.85it/s]

 60%|██████    | 18211/30196 [37:51<29:00,  6.88it/s]

 60%|██████    | 18212/30196 [37:51<28:24,  7.03it/s]

 60%|██████    | 18214/30196 [37:51<23:30,  8.49it/s]

 60%|██████    | 18216/30196 [37:52<20:18,  9.83it/s]

 60%|██████    | 18218/30196 [37:52<21:30,  9.28it/s]

 60%|██████    | 18219/30196 [37:52<23:02,  8.66it/s]

 60%|██████    | 18220/30196 [37:52<22:48,  8.75it/s]

 60%|██████    | 18222/30196 [37:52<20:18,  9.83it/s]

 60%|██████    | 18223/30196 [37:52<20:40,  9.65it/s]

 60%|██████    | 18224/30196 [37:52<22:24,  8.91it/s]

 60%|██████    | 18226/30196 [37:53<22:33,  8.85it/s]

 60%|██████    | 18228/30196 [37:53<22:25,  8.89it/s]

 60%|██████    | 18229/30196 [37:53<23:19,  8.55it/s]

 60%|██████    | 18230/30196 [37:53<24:06,  8.27it/s]

 60%|██████    | 18231/30196 [37:53<29:32,  6.75it/s]

 60%|██████    | 18232/30196 [37:54<27:24,  7.28it/s]

 60%|██████    | 18233/30196 [37:54<27:03,  7.37it/s]

 60%|██████    | 18235/30196 [37:54<24:48,  8.03it/s]

 60%|██████    | 18236/30196 [37:54<29:20,  6.79it/s]

 60%|██████    | 18238/30196 [37:54<29:20,  6.79it/s]

 60%|██████    | 18239/30196 [37:55<29:06,  6.85it/s]

 60%|██████    | 18240/30196 [37:55<27:08,  7.34it/s]

 60%|██████    | 18241/30196 [37:55<28:41,  6.95it/s]

 60%|██████    | 18243/30196 [37:55<22:34,  8.83it/s]

 60%|██████    | 18244/30196 [37:55<25:34,  7.79it/s]

 60%|██████    | 18245/30196 [37:55<24:38,  8.08it/s]

 60%|██████    | 18246/30196 [37:55<25:29,  7.81it/s]

 60%|██████    | 18247/30196 [37:56<27:42,  7.19it/s]

 60%|██████    | 18249/30196 [37:56<33:21,  5.97it/s]

 60%|██████    | 18250/30196 [37:56<33:59,  5.86it/s]

 60%|██████    | 18252/30196 [37:56<26:48,  7.43it/s]

 60%|██████    | 18253/30196 [37:56<30:14,  6.58it/s]

 60%|██████    | 18254/30196 [37:57<38:06,  5.22it/s]

 60%|██████    | 18256/30196 [37:57<27:28,  7.24it/s]

 60%|██████    | 18257/30196 [37:57<27:22,  7.27it/s]

 60%|██████    | 18259/30196 [37:57<23:21,  8.52it/s]

 60%|██████    | 18260/30196 [37:57<22:46,  8.73it/s]

 60%|██████    | 18261/30196 [37:58<30:48,  6.46it/s]

 60%|██████    | 18263/30196 [37:58<28:35,  6.96it/s]

 60%|██████    | 18264/30196 [37:58<33:31,  5.93it/s]

 60%|██████    | 18266/30196 [37:58<29:31,  6.73it/s]

 60%|██████    | 18268/30196 [37:59<25:12,  7.89it/s]

 61%|██████    | 18270/30196 [37:59<23:42,  8.38it/s]

 61%|██████    | 18271/30196 [37:59<23:45,  8.37it/s]

 61%|██████    | 18274/30196 [37:59<17:40, 11.24it/s]

 61%|██████    | 18276/30196 [37:59<19:32, 10.17it/s]

 61%|██████    | 18278/30196 [37:59<19:35, 10.14it/s]

 61%|██████    | 18280/30196 [38:00<22:08,  8.97it/s]

 61%|██████    | 18281/30196 [38:00<24:17,  8.17it/s]

 61%|██████    | 18282/30196 [38:00<23:36,  8.41it/s]

 61%|██████    | 18283/30196 [38:00<24:04,  8.25it/s]

 61%|██████    | 18284/30196 [38:00<24:45,  8.02it/s]

 61%|██████    | 18285/30196 [38:00<25:14,  7.86it/s]

 61%|██████    | 18287/30196 [38:01<22:49,  8.70it/s]

 61%|██████    | 18288/30196 [38:01<24:20,  8.15it/s]

 61%|██████    | 18289/30196 [38:01<24:43,  8.03it/s]

 61%|██████    | 18290/30196 [38:01<25:18,  7.84it/s]

 61%|██████    | 18291/30196 [38:01<27:22,  7.25it/s]

 61%|██████    | 18293/30196 [38:01<20:41,  9.59it/s]

 61%|██████    | 18294/30196 [38:01<20:56,  9.47it/s]

 61%|██████    | 18295/30196 [38:02<22:24,  8.85it/s]

 61%|██████    | 18296/30196 [38:02<23:31,  8.43it/s]

 61%|██████    | 18297/30196 [38:02<29:36,  6.70it/s]

 61%|██████    | 18299/30196 [38:02<25:50,  7.67it/s]

 61%|██████    | 18301/30196 [38:02<26:41,  7.43it/s]

 61%|██████    | 18303/30196 [38:03<23:00,  8.61it/s]

 61%|██████    | 18304/30196 [38:03<25:01,  7.92it/s]

 61%|██████    | 18306/30196 [38:03<22:22,  8.85it/s]

 61%|██████    | 18308/30196 [38:03<21:23,  9.26it/s]

 61%|██████    | 18310/30196 [38:03<18:41, 10.60it/s]

 61%|██████    | 18312/30196 [38:04<19:52,  9.96it/s]

 61%|██████    | 18314/30196 [38:04<20:47,  9.52it/s]

 61%|██████    | 18315/30196 [38:04<20:59,  9.43it/s]

 61%|██████    | 18316/30196 [38:04<25:48,  7.67it/s]

 61%|██████    | 18318/30196 [38:04<22:58,  8.62it/s]

 61%|██████    | 18320/30196 [38:04<19:33, 10.12it/s]

 61%|██████    | 18322/30196 [38:05<17:45, 11.14it/s]

 61%|██████    | 18324/30196 [38:05<20:12,  9.79it/s]

 61%|██████    | 18326/30196 [38:05<20:49,  9.50it/s]

 61%|██████    | 18328/30196 [38:05<22:24,  8.83it/s]

 61%|██████    | 18329/30196 [38:05<22:16,  8.88it/s]

 61%|██████    | 18331/30196 [38:06<19:28, 10.15it/s]

 61%|██████    | 18333/30196 [38:06<23:00,  8.60it/s]

 61%|██████    | 18335/30196 [38:06<23:53,  8.27it/s]

 61%|██████    | 18336/30196 [38:06<27:24,  7.21it/s]

 61%|██████    | 18337/30196 [38:06<26:39,  7.42it/s]

 61%|██████    | 18338/30196 [38:07<25:18,  7.81it/s]

 61%|██████    | 18340/30196 [38:07<21:03,  9.38it/s]

 61%|██████    | 18342/30196 [38:07<17:41, 11.17it/s]

 61%|██████    | 18344/30196 [38:07<18:03, 10.94it/s]

 61%|██████    | 18346/30196 [38:07<27:14,  7.25it/s]

 61%|██████    | 18347/30196 [38:08<28:29,  6.93it/s]

 61%|██████    | 18349/30196 [38:08<23:51,  8.28it/s]

 61%|██████    | 18351/30196 [38:08<24:11,  8.16it/s]

 61%|██████    | 18352/30196 [38:08<23:43,  8.32it/s]

 61%|██████    | 18353/30196 [38:08<23:05,  8.55it/s]

 61%|██████    | 18354/30196 [38:08<22:44,  8.68it/s]

 61%|██████    | 18355/30196 [38:09<24:21,  8.10it/s]

 61%|██████    | 18357/30196 [38:09<20:55,  9.43it/s]

 61%|██████    | 18358/30196 [38:09<22:03,  8.94it/s]

 61%|██████    | 18359/30196 [38:09<23:26,  8.41it/s]

 61%|██████    | 18360/30196 [38:09<24:01,  8.21it/s]

 61%|██████    | 18361/30196 [38:09<26:23,  7.47it/s]

 61%|██████    | 18363/30196 [38:09<22:36,  8.73it/s]

 61%|██████    | 18364/30196 [38:10<25:23,  7.77it/s]

 61%|██████    | 18365/30196 [38:10<29:56,  6.58it/s]

 61%|██████    | 18366/30196 [38:10<30:38,  6.43it/s]

 61%|██████    | 18367/30196 [38:10<31:24,  6.28it/s]

 61%|██████    | 18368/30196 [38:10<30:26,  6.48it/s]

 61%|██████    | 18369/30196 [38:10<33:17,  5.92it/s]

 61%|██████    | 18371/30196 [38:11<24:20,  8.10it/s]

 61%|██████    | 18372/30196 [38:11<23:39,  8.33it/s]

 61%|██████    | 18374/30196 [38:11<23:25,  8.41it/s]

 61%|██████    | 18375/30196 [38:11<24:23,  8.08it/s]

 61%|██████    | 18377/30196 [38:11<25:08,  7.83it/s]

 61%|██████    | 18379/30196 [38:12<23:14,  8.47it/s]

 61%|██████    | 18381/30196 [38:12<23:59,  8.21it/s]

 61%|██████    | 18382/30196 [38:12<24:42,  7.97it/s]

 61%|██████    | 18383/30196 [38:12<25:36,  7.69it/s]

 61%|██████    | 18385/30196 [38:12<23:51,  8.25it/s]

 61%|██████    | 18387/30196 [38:12<20:11,  9.75it/s]

 61%|██████    | 18389/30196 [38:13<19:35, 10.04it/s]

 61%|██████    | 18391/30196 [38:13<20:46,  9.47it/s]

 61%|██████    | 18393/30196 [38:13<19:57,  9.86it/s]

 61%|██████    | 18395/30196 [38:13<21:25,  9.18it/s]

 61%|██████    | 18396/30196 [38:13<21:27,  9.16it/s]

 61%|██████    | 18398/30196 [38:14<19:37, 10.02it/s]

 61%|██████    | 18400/30196 [38:14<19:46,  9.94it/s]

 61%|██████    | 18402/30196 [38:14<20:50,  9.43it/s]

 61%|██████    | 18403/30196 [38:14<24:29,  8.03it/s]

 61%|██████    | 18404/30196 [38:14<26:09,  7.51it/s]

 61%|██████    | 18406/30196 [38:15<22:19,  8.80it/s]

 61%|██████    | 18408/30196 [38:15<21:32,  9.12it/s]

 61%|██████    | 18409/30196 [38:15<21:21,  9.20it/s]

 61%|██████    | 18411/30196 [38:15<20:13,  9.71it/s]

 61%|██████    | 18413/30196 [38:15<21:02,  9.34it/s]

 61%|██████    | 18414/30196 [38:15<23:16,  8.44it/s]

 61%|██████    | 18416/30196 [38:16<29:38,  6.62it/s]

 61%|██████    | 18418/30196 [38:16<27:59,  7.01it/s]

 61%|██████    | 18420/30196 [38:16<26:12,  7.49it/s]

 61%|██████    | 18422/30196 [38:17<25:28,  7.70it/s]

 61%|██████    | 18423/30196 [38:17<25:41,  7.64it/s]

 61%|██████    | 18424/30196 [38:17<24:48,  7.91it/s]

 61%|██████    | 18425/30196 [38:17<25:28,  7.70it/s]

 61%|██████    | 18427/30196 [38:17<23:57,  8.19it/s]

 61%|██████    | 18428/30196 [38:17<23:12,  8.45it/s]

 61%|██████    | 18429/30196 [38:17<24:13,  8.10it/s]

 61%|██████    | 18430/30196 [38:18<23:23,  8.38it/s]

 61%|██████    | 18431/30196 [38:18<24:53,  7.88it/s]

 61%|██████    | 18432/30196 [38:18<25:37,  7.65it/s]

 61%|██████    | 18434/30196 [38:18<23:44,  8.25it/s]

 61%|██████    | 18436/30196 [38:18<18:35, 10.55it/s]

 61%|██████    | 18438/30196 [38:18<16:35, 11.81it/s]

 61%|██████    | 18440/30196 [38:19<19:49,  9.89it/s]

 61%|██████    | 18442/30196 [38:19<20:04,  9.76it/s]

 61%|██████    | 18444/30196 [38:19<17:48, 11.00it/s]

 61%|██████    | 18446/30196 [38:19<18:03, 10.84it/s]

 61%|██████    | 18448/30196 [38:19<17:00, 11.51it/s]

 61%|██████    | 18450/30196 [38:19<16:54, 11.58it/s]

 61%|██████    | 18452/30196 [38:20<20:48,  9.40it/s]

 61%|██████    | 18454/30196 [38:20<17:48, 10.99it/s]

 61%|██████    | 18456/30196 [38:20<20:17,  9.64it/s]

 61%|██████    | 18458/30196 [38:20<21:13,  9.21it/s]

 61%|██████    | 18460/30196 [38:21<21:07,  9.26it/s]

 61%|██████    | 18461/30196 [38:21<22:18,  8.77it/s]

 61%|██████    | 18462/30196 [38:21<36:52,  5.30it/s]

 61%|██████    | 18463/30196 [38:21<33:27,  5.84it/s]

 61%|██████    | 18464/30196 [38:21<30:18,  6.45it/s]

 61%|██████    | 18466/30196 [38:22<27:01,  7.23it/s]

 61%|██████    | 18468/30196 [38:22<40:04,  4.88it/s]

 61%|██████    | 18470/30196 [38:22<31:12,  6.26it/s]

 61%|██████    | 18471/30196 [38:23<29:16,  6.68it/s]

 61%|██████    | 18472/30196 [38:23<28:25,  6.87it/s]

 61%|██████    | 18473/30196 [38:24<1:00:31,  3.23it/s]

 61%|██████    | 18475/30196 [38:24<42:09,  4.63it/s]

 61%|██████    | 18476/30196 [38:24<41:50,  4.67it/s]

 61%|██████    | 18477/30196 [38:24<39:33,  4.94it/s]

 61%|██████    | 18478/30196 [38:24<36:07,  5.41it/s]

 61%|██████    | 18480/30196 [38:24<27:34,  7.08it/s]

 61%|██████    | 18481/30196 [38:24<27:06,  7.20it/s]

 61%|██████    | 18482/30196 [38:25<25:27,  7.67it/s]

 61%|██████    | 18483/30196 [38:25<25:41,  7.60it/s]

 61%|██████    | 18485/30196 [38:25<20:16,  9.62it/s]

 61%|██████    | 18487/30196 [38:25<23:52,  8.17it/s]

 61%|██████    | 18488/30196 [38:25<23:20,  8.36it/s]

 61%|██████    | 18489/30196 [38:25<23:56,  8.15it/s]

 61%|██████    | 18491/30196 [38:26<24:23,  8.00it/s]

 61%|██████    | 18493/30196 [38:26<19:43,  9.89it/s]

 61%|██████    | 18495/30196 [38:26<21:16,  9.17it/s]

 61%|██████▏   | 18497/30196 [38:26<20:41,  9.42it/s]

 61%|██████▏   | 18499/30196 [38:26<19:53,  9.80it/s]

 61%|██████▏   | 18501/30196 [38:27<17:18, 11.26it/s]

 61%|██████▏   | 18503/30196 [38:27<17:30, 11.13it/s]

 61%|██████▏   | 18505/30196 [38:27<21:37,  9.01it/s]

 61%|██████▏   | 18507/30196 [38:27<22:39,  8.60it/s]

 61%|██████▏   | 18508/30196 [38:27<23:10,  8.41it/s]

 61%|██████▏   | 18509/30196 [38:28<23:39,  8.23it/s]

 61%|██████▏   | 18510/30196 [38:28<24:03,  8.10it/s]

 61%|██████▏   | 18511/30196 [38:28<26:02,  7.48it/s]

 61%|██████▏   | 18512/30196 [38:28<24:50,  7.84it/s]

 61%|██████▏   | 18514/30196 [38:28<23:17,  8.36it/s]

 61%|██████▏   | 18515/30196 [38:28<22:52,  8.51it/s]

 61%|██████▏   | 18516/30196 [38:28<23:44,  8.20it/s]

 61%|██████▏   | 18517/30196 [38:29<22:51,  8.52it/s]

 61%|██████▏   | 18518/30196 [38:29<28:46,  6.76it/s]

 61%|██████▏   | 18519/30196 [38:29<28:47,  6.76it/s]

 61%|██████▏   | 18520/30196 [38:29<28:02,  6.94it/s]

 61%|██████▏   | 18521/30196 [38:29<31:30,  6.17it/s]

 61%|██████▏   | 18522/30196 [38:29<28:34,  6.81it/s]

 61%|██████▏   | 18523/30196 [38:29<26:10,  7.43it/s]

 61%|██████▏   | 18525/30196 [38:30<22:06,  8.80it/s]

 61%|██████▏   | 18527/30196 [38:30<18:28, 10.53it/s]

 61%|██████▏   | 18529/30196 [38:30<17:02, 11.40it/s]

 61%|██████▏   | 18531/30196 [38:30<24:12,  8.03it/s]

 61%|██████▏   | 18534/30196 [38:31<20:30,  9.48it/s]

 61%|██████▏   | 18536/30196 [38:31<22:57,  8.46it/s]

 61%|██████▏   | 18537/30196 [38:31<22:42,  8.56it/s]

 61%|██████▏   | 18539/30196 [38:31<19:33,  9.93it/s]

 61%|██████▏   | 18541/30196 [38:31<21:47,  8.91it/s]

 61%|██████▏   | 18543/30196 [38:32<21:30,  9.03it/s]

 61%|██████▏   | 18544/30196 [38:32<25:45,  7.54it/s]

 61%|██████▏   | 18546/30196 [38:32<22:26,  8.65it/s]

 61%|██████▏   | 18548/30196 [38:32<20:47,  9.33it/s]

 61%|██████▏   | 18549/30196 [38:32<24:32,  7.91it/s]

 61%|██████▏   | 18550/30196 [38:33<30:32,  6.35it/s]

 61%|██████▏   | 18552/30196 [38:33<26:14,  7.40it/s]

 61%|██████▏   | 18554/30196 [38:33<22:06,  8.78it/s]

 61%|██████▏   | 18556/30196 [38:33<19:53,  9.75it/s]

 61%|██████▏   | 18558/30196 [38:33<19:25,  9.98it/s]

 61%|██████▏   | 18560/30196 [38:34<21:57,  8.83it/s]

 61%|██████▏   | 18561/30196 [38:34<27:02,  7.17it/s]

 61%|██████▏   | 18562/30196 [38:34<27:05,  7.16it/s]

 61%|██████▏   | 18564/30196 [38:34<24:11,  8.01it/s]

 61%|██████▏   | 18566/30196 [38:34<22:50,  8.49it/s]

 61%|██████▏   | 18567/30196 [38:35<23:31,  8.24it/s]

 61%|██████▏   | 18568/30196 [38:35<34:53,  5.55it/s]

 61%|██████▏   | 18569/30196 [38:35<32:38,  5.94it/s]

 62%|██████▏   | 18571/30196 [38:35<26:42,  7.26it/s]

 62%|██████▏   | 18572/30196 [38:35<26:22,  7.34it/s]

 62%|██████▏   | 18575/30196 [38:36<19:43,  9.82it/s]

 62%|██████▏   | 18577/30196 [38:36<20:17,  9.54it/s]

 62%|██████▏   | 18579/30196 [38:36<18:33, 10.44it/s]

 62%|██████▏   | 18581/30196 [38:36<20:55,  9.25it/s]

 62%|██████▏   | 18582/30196 [38:36<21:43,  8.91it/s]

 62%|██████▏   | 18583/30196 [38:36<22:25,  8.63it/s]

 62%|██████▏   | 18585/30196 [38:37<19:54,  9.72it/s]

 62%|██████▏   | 18586/30196 [38:37<22:27,  8.61it/s]

 62%|██████▏   | 18588/30196 [38:37<20:33,  9.41it/s]

 62%|██████▏   | 18589/30196 [38:37<21:51,  8.85it/s]

 62%|██████▏   | 18590/30196 [38:37<22:34,  8.57it/s]

 62%|██████▏   | 18592/30196 [38:37<19:07, 10.11it/s]

 62%|██████▏   | 18594/30196 [38:38<17:46, 10.88it/s]

 62%|██████▏   | 18596/30196 [38:38<21:31,  8.98it/s]

 62%|██████▏   | 18597/30196 [38:38<26:02,  7.42it/s]

 62%|██████▏   | 18599/30196 [38:38<25:01,  7.72it/s]

 62%|██████▏   | 18601/30196 [38:38<21:49,  8.86it/s]

 62%|██████▏   | 18602/30196 [38:39<26:10,  7.38it/s]

 62%|██████▏   | 18603/30196 [38:39<27:46,  6.96it/s]

 62%|██████▏   | 18605/30196 [38:39<21:25,  9.02it/s]

 62%|██████▏   | 18607/30196 [38:39<18:48, 10.27it/s]

 62%|██████▏   | 18609/30196 [38:40<23:58,  8.06it/s]

 62%|██████▏   | 18610/30196 [38:40<24:23,  7.92it/s]

 62%|██████▏   | 18611/30196 [38:40<26:39,  7.24it/s]

 62%|██████▏   | 18612/30196 [38:40<34:38,  5.57it/s]

 62%|██████▏   | 18614/30196 [38:40<25:53,  7.46it/s]

 62%|██████▏   | 18616/30196 [38:40<23:13,  8.31it/s]

 62%|██████▏   | 18618/30196 [38:41<21:39,  8.91it/s]

 62%|██████▏   | 18620/30196 [38:41<20:10,  9.56it/s]

 62%|██████▏   | 18622/30196 [38:41<25:52,  7.46it/s]

 62%|██████▏   | 18624/30196 [38:41<25:05,  7.69it/s]

 62%|██████▏   | 18625/30196 [38:42<25:05,  7.68it/s]

 62%|██████▏   | 18627/30196 [38:42<21:13,  9.09it/s]

 62%|██████▏   | 18628/30196 [38:42<22:24,  8.61it/s]

 62%|██████▏   | 18629/30196 [38:42<21:55,  8.79it/s]

 62%|██████▏   | 18630/30196 [38:42<21:30,  8.96it/s]

 62%|██████▏   | 18631/30196 [38:42<21:26,  8.99it/s]

 62%|██████▏   | 18632/30196 [38:42<23:14,  8.29it/s]

 62%|██████▏   | 18634/30196 [38:43<22:00,  8.75it/s]

 62%|██████▏   | 18635/30196 [38:43<30:38,  6.29it/s]

 62%|██████▏   | 18636/30196 [38:43<41:34,  4.63it/s]

 62%|██████▏   | 18637/30196 [38:43<37:12,  5.18it/s]

 62%|██████▏   | 18638/30196 [38:43<32:33,  5.92it/s]

 62%|██████▏   | 18640/30196 [38:44<25:42,  7.49it/s]

 62%|██████▏   | 18641/30196 [38:44<27:32,  6.99it/s]

 62%|██████▏   | 18642/30196 [38:44<26:58,  7.14it/s]

 62%|██████▏   | 18643/30196 [38:44<29:00,  6.64it/s]

 62%|██████▏   | 18644/30196 [38:44<28:52,  6.67it/s]

 62%|██████▏   | 18646/30196 [38:45<27:48,  6.92it/s]

 62%|██████▏   | 18647/30196 [38:45<28:46,  6.69it/s]

 62%|██████▏   | 18648/30196 [38:45<29:41,  6.48it/s]

 62%|██████▏   | 18649/30196 [38:45<30:39,  6.28it/s]

 62%|██████▏   | 18651/30196 [38:45<24:43,  7.78it/s]

 62%|██████▏   | 18652/30196 [38:45<23:38,  8.14it/s]

 62%|██████▏   | 18654/30196 [38:46<19:57,  9.64it/s]

 62%|██████▏   | 18655/30196 [38:46<21:17,  9.03it/s]

 62%|██████▏   | 18657/30196 [38:46<19:50,  9.69it/s]

 62%|██████▏   | 18658/30196 [38:47<55:08,  3.49it/s]

 62%|██████▏   | 18660/30196 [38:47<41:29,  4.63it/s]

 62%|██████▏   | 18661/30196 [38:47<38:26,  5.00it/s]

 62%|██████▏   | 18662/30196 [38:47<34:23,  5.59it/s]

 62%|██████▏   | 18663/30196 [38:47<34:25,  5.58it/s]

 62%|██████▏   | 18664/30196 [38:48<30:54,  6.22it/s]

 62%|██████▏   | 18666/30196 [38:48<23:09,  8.30it/s]

 62%|██████▏   | 18668/30196 [38:48<19:53,  9.66it/s]

 62%|██████▏   | 18670/30196 [38:48<18:09, 10.58it/s]

 62%|██████▏   | 18672/30196 [38:48<18:13, 10.54it/s]

 62%|██████▏   | 18674/30196 [38:49<23:56,  8.02it/s]

 62%|██████▏   | 18676/30196 [38:49<20:14,  9.48it/s]

 62%|██████▏   | 18678/30196 [38:49<22:21,  8.58it/s]

 62%|██████▏   | 18680/30196 [38:49<22:26,  8.56it/s]

 62%|██████▏   | 18681/30196 [38:49<24:33,  7.82it/s]

 62%|██████▏   | 18682/30196 [38:49<25:02,  7.66it/s]

 62%|██████▏   | 18684/30196 [38:50<23:33,  8.14it/s]

 62%|██████▏   | 18685/30196 [38:50<25:13,  7.60it/s]

 62%|██████▏   | 18687/30196 [38:50<22:11,  8.64it/s]

 62%|██████▏   | 18688/30196 [38:50<34:26,  5.57it/s]

 62%|██████▏   | 18689/30196 [38:51<32:12,  5.95it/s]

 62%|██████▏   | 18690/30196 [38:51<29:11,  6.57it/s]

 62%|██████▏   | 18692/30196 [38:51<25:49,  7.42it/s]

 62%|██████▏   | 18693/30196 [38:51<26:03,  7.36it/s]

 62%|██████▏   | 18695/30196 [38:52<32:35,  5.88it/s]

 62%|██████▏   | 18696/30196 [38:52<38:58,  4.92it/s]

 62%|██████▏   | 18698/30196 [38:52<33:13,  5.77it/s]

 62%|██████▏   | 18700/30196 [38:52<25:52,  7.40it/s]

 62%|██████▏   | 18702/30196 [38:52<24:11,  7.92it/s]

 62%|██████▏   | 18703/30196 [38:53<23:58,  7.99it/s]

 62%|██████▏   | 18704/30196 [38:53<23:06,  8.29it/s]

 62%|██████▏   | 18705/30196 [38:53<22:36,  8.47it/s]

 62%|██████▏   | 18706/30196 [38:53<22:00,  8.70it/s]

 62%|██████▏   | 18708/30196 [38:53<19:50,  9.65it/s]

 62%|██████▏   | 18709/30196 [38:53<20:08,  9.50it/s]

 62%|██████▏   | 18710/30196 [38:53<20:06,  9.52it/s]

 62%|██████▏   | 18712/30196 [38:53<20:40,  9.26it/s]

 62%|██████▏   | 18714/30196 [38:54<16:55, 11.31it/s]

 62%|██████▏   | 18716/30196 [38:54<16:23, 11.67it/s]

 62%|██████▏   | 18718/30196 [38:54<21:44,  8.80it/s]

 62%|██████▏   | 18720/30196 [38:54<25:47,  7.42it/s]

 62%|██████▏   | 18721/30196 [38:55<25:58,  7.36it/s]

 62%|██████▏   | 18722/30196 [38:55<25:48,  7.41it/s]

 62%|██████▏   | 18724/30196 [38:55<21:35,  8.86it/s]

 62%|██████▏   | 18726/30196 [38:55<21:33,  8.86it/s]

 62%|██████▏   | 18727/30196 [38:55<28:49,  6.63it/s]

 62%|██████▏   | 18728/30196 [38:56<27:07,  7.05it/s]

 62%|██████▏   | 18730/30196 [38:56<23:50,  8.02it/s]

 62%|██████▏   | 18732/30196 [38:56<23:08,  8.26it/s]

 62%|██████▏   | 18734/30196 [38:56<27:10,  7.03it/s]

 62%|██████▏   | 18736/30196 [38:56<22:22,  8.54it/s]

 62%|██████▏   | 18738/30196 [38:57<23:16,  8.21it/s]

 62%|██████▏   | 18739/30196 [38:57<27:03,  7.06it/s]

 62%|██████▏   | 18741/30196 [38:57<23:33,  8.10it/s]

 62%|██████▏   | 18743/30196 [38:57<19:54,  9.59it/s]

 62%|██████▏   | 18745/30196 [38:58<22:33,  8.46it/s]

 62%|██████▏   | 18746/30196 [38:58<23:33,  8.10it/s]

 62%|██████▏   | 18748/30196 [38:58<21:23,  8.92it/s]

 62%|██████▏   | 18749/30196 [38:58<22:44,  8.39it/s]

 62%|██████▏   | 18751/30196 [38:59<33:49,  5.64it/s]

 62%|██████▏   | 18752/30196 [38:59<33:32,  5.69it/s]

 62%|██████▏   | 18753/30196 [38:59<31:46,  6.00it/s]

 62%|██████▏   | 18754/30196 [38:59<31:40,  6.02it/s]

 62%|██████▏   | 18755/30196 [38:59<31:48,  5.99it/s]

 62%|██████▏   | 18757/30196 [38:59<25:00,  7.62it/s]

 62%|██████▏   | 18759/30196 [39:00<22:15,  8.56it/s]

 62%|██████▏   | 18760/30196 [39:00<22:48,  8.36it/s]

 62%|██████▏   | 18762/30196 [39:00<25:02,  7.61it/s]

 62%|██████▏   | 18763/30196 [39:00<24:10,  7.88it/s]

 62%|██████▏   | 18764/30196 [39:00<27:41,  6.88it/s]

 62%|██████▏   | 18766/30196 [39:01<24:05,  7.91it/s]

 62%|██████▏   | 18768/30196 [39:01<22:12,  8.58it/s]

 62%|██████▏   | 18769/30196 [39:01<24:08,  7.89it/s]

 62%|██████▏   | 18772/30196 [39:01<23:45,  8.02it/s]

 62%|██████▏   | 18773/30196 [39:01<24:15,  7.85it/s]

 62%|██████▏   | 18775/30196 [39:02<20:24,  9.33it/s]

 62%|██████▏   | 18776/30196 [39:02<21:51,  8.70it/s]

 62%|██████▏   | 18777/30196 [39:02<21:38,  8.79it/s]

 62%|██████▏   | 18779/30196 [39:02<20:27,  9.30it/s]

 62%|██████▏   | 18781/30196 [39:02<16:37, 11.44it/s]

 62%|██████▏   | 18783/30196 [39:02<15:55, 11.94it/s]

 62%|██████▏   | 18785/30196 [39:02<17:33, 10.83it/s]

 62%|██████▏   | 18787/30196 [39:03<20:00,  9.50it/s]

 62%|██████▏   | 18789/30196 [39:03<23:28,  8.10it/s]

 62%|██████▏   | 18790/30196 [39:03<26:35,  7.15it/s]

 62%|██████▏   | 18791/30196 [39:03<25:13,  7.53it/s]

 62%|██████▏   | 18792/30196 [39:04<25:21,  7.49it/s]

 62%|██████▏   | 18793/30196 [39:04<25:42,  7.39it/s]

 62%|██████▏   | 18794/30196 [39:04<25:35,  7.43it/s]

 62%|██████▏   | 18795/30196 [39:04<29:31,  6.44it/s]

 62%|██████▏   | 18796/30196 [39:04<28:12,  6.74it/s]

 62%|██████▏   | 18797/30196 [39:04<29:11,  6.51it/s]

 62%|██████▏   | 18798/30196 [39:04<28:46,  6.60it/s]

 62%|██████▏   | 18799/30196 [39:05<28:08,  6.75it/s]

 62%|██████▏   | 18800/30196 [39:05<27:33,  6.89it/s]

 62%|██████▏   | 18802/30196 [39:05<26:15,  7.23it/s]

 62%|██████▏   | 18804/30196 [39:05<20:18,  9.35it/s]

 62%|██████▏   | 18806/30196 [39:05<22:11,  8.55it/s]

 62%|██████▏   | 18808/30196 [39:05<18:58, 10.00it/s]

 62%|██████▏   | 18810/30196 [39:06<19:51,  9.55it/s]

 62%|██████▏   | 18812/30196 [39:06<18:59,  9.99it/s]

 62%|██████▏   | 18814/30196 [39:06<20:56,  9.06it/s]

 62%|██████▏   | 18815/30196 [39:06<21:39,  8.76it/s]

 62%|██████▏   | 18816/30196 [39:06<23:50,  7.96it/s]

 62%|██████▏   | 18817/30196 [39:07<22:54,  8.28it/s]

 62%|██████▏   | 18818/30196 [39:07<22:11,  8.55it/s]

 62%|██████▏   | 18819/30196 [39:07<23:19,  8.13it/s]

 62%|██████▏   | 18820/30196 [39:07<28:01,  6.77it/s]

 62%|██████▏   | 18821/30196 [39:07<29:02,  6.53it/s]

 62%|██████▏   | 18822/30196 [39:07<28:03,  6.76it/s]

 62%|██████▏   | 18823/30196 [39:07<28:03,  6.76it/s]

 62%|██████▏   | 18825/30196 [39:08<19:56,  9.50it/s]

 62%|██████▏   | 18827/30196 [39:08<23:57,  7.91it/s]

 62%|██████▏   | 18829/30196 [39:08<20:16,  9.34it/s]

 62%|██████▏   | 18831/30196 [39:08<21:03,  8.99it/s]

 62%|██████▏   | 18832/30196 [39:08<20:48,  9.10it/s]

 62%|██████▏   | 18834/30196 [39:09<22:06,  8.57it/s]

 62%|██████▏   | 18835/30196 [39:09<23:15,  8.14it/s]

 62%|██████▏   | 18837/30196 [39:09<23:37,  8.01it/s]

 62%|██████▏   | 18838/30196 [39:09<24:02,  7.87it/s]

 62%|██████▏   | 18839/30196 [39:09<25:44,  7.35it/s]

 62%|██████▏   | 18840/30196 [39:09<25:56,  7.30it/s]

 62%|██████▏   | 18841/30196 [39:10<24:36,  7.69it/s]

 62%|██████▏   | 18843/30196 [39:10<22:56,  8.25it/s]

 62%|██████▏   | 18844/30196 [39:10<25:03,  7.55it/s]

 62%|██████▏   | 18845/30196 [39:10<25:09,  7.52it/s]

 62%|██████▏   | 18846/30196 [39:10<25:00,  7.56it/s]

 62%|██████▏   | 18847/30196 [39:10<25:28,  7.42it/s]

 62%|██████▏   | 18849/30196 [39:11<22:06,  8.55it/s]

 62%|██████▏   | 18850/30196 [39:11<26:03,  7.26it/s]

 62%|██████▏   | 18851/30196 [39:11<25:43,  7.35it/s]

 62%|██████▏   | 18853/30196 [39:11<22:31,  8.39it/s]

 62%|██████▏   | 18854/30196 [39:11<24:08,  7.83it/s]

 62%|██████▏   | 18855/30196 [39:11<25:57,  7.28it/s]

 62%|██████▏   | 18856/30196 [39:12<25:36,  7.38it/s]

 62%|██████▏   | 18857/30196 [39:12<25:56,  7.28it/s]

 62%|██████▏   | 18858/30196 [39:12<27:25,  6.89it/s]

 62%|██████▏   | 18859/30196 [39:12<31:59,  5.91it/s]

 62%|██████▏   | 18860/30196 [39:12<28:25,  6.65it/s]

 62%|██████▏   | 18861/30196 [39:12<26:12,  7.21it/s]

 62%|██████▏   | 18862/30196 [39:12<24:20,  7.76it/s]

 62%|██████▏   | 18863/30196 [39:13<27:14,  6.93it/s]

 62%|██████▏   | 18864/30196 [39:13<26:41,  7.08it/s]

 62%|██████▏   | 18865/30196 [39:13<24:37,  7.67it/s]

 62%|██████▏   | 18867/30196 [39:13<17:54, 10.54it/s]

 62%|██████▏   | 18869/30196 [39:13<22:57,  8.23it/s]

 62%|██████▏   | 18870/30196 [39:14<40:20,  4.68it/s]

 62%|██████▏   | 18872/30196 [39:14<29:03,  6.50it/s]

 63%|██████▎   | 18874/30196 [39:14<27:46,  6.80it/s]

 63%|██████▎   | 18875/30196 [39:14<30:55,  6.10it/s]

 63%|██████▎   | 18876/30196 [39:15<39:44,  4.75it/s]

 63%|██████▎   | 18878/30196 [39:15<29:04,  6.49it/s]

 63%|██████▎   | 18879/30196 [39:15<29:58,  6.29it/s]

 63%|██████▎   | 18880/30196 [39:15<33:06,  5.70it/s]

 63%|██████▎   | 18882/30196 [39:16<27:37,  6.83it/s]

 63%|██████▎   | 18884/30196 [39:16<30:03,  6.27it/s]

 63%|██████▎   | 18886/30196 [39:16<30:10,  6.25it/s]

 63%|██████▎   | 18888/30196 [39:16<24:40,  7.64it/s]

 63%|██████▎   | 18889/30196 [39:16<23:43,  7.94it/s]

 63%|██████▎   | 18891/30196 [39:17<21:23,  8.80it/s]

 63%|██████▎   | 18893/30196 [39:17<17:54, 10.52it/s]

 63%|██████▎   | 18895/30196 [39:17<20:43,  9.09it/s]

 63%|██████▎   | 18897/30196 [39:17<22:42,  8.29it/s]

 63%|██████▎   | 18899/30196 [39:17<19:06,  9.86it/s]

 63%|██████▎   | 18901/30196 [39:18<18:43, 10.05it/s]

 63%|██████▎   | 18903/30196 [39:18<18:05, 10.40it/s]

 63%|██████▎   | 18905/30196 [39:18<19:58,  9.42it/s]

 63%|██████▎   | 18907/30196 [39:18<20:10,  9.33it/s]

 63%|██████▎   | 18908/30196 [39:18<22:30,  8.36it/s]

 63%|██████▎   | 18909/30196 [39:19<24:17,  7.74it/s]

 63%|██████▎   | 18911/30196 [39:19<22:50,  8.23it/s]

 63%|██████▎   | 18912/30196 [39:19<26:45,  7.03it/s]

 63%|██████▎   | 18914/30196 [39:19<21:48,  8.62it/s]

 63%|██████▎   | 18916/30196 [39:20<23:16,  8.08it/s]

 63%|██████▎   | 18917/30196 [39:20<24:50,  7.57it/s]

 63%|██████▎   | 18918/30196 [39:20<23:55,  7.86it/s]

 63%|██████▎   | 18920/30196 [39:20<24:04,  7.81it/s]

 63%|██████▎   | 18921/30196 [39:20<24:52,  7.56it/s]

 63%|██████▎   | 18923/30196 [39:20<22:57,  8.18it/s]

 63%|██████▎   | 18924/30196 [39:21<26:52,  6.99it/s]

 63%|██████▎   | 18925/30196 [39:21<25:13,  7.45it/s]

 63%|██████▎   | 18926/30196 [39:21<24:03,  7.81it/s]

 63%|██████▎   | 18927/30196 [39:21<23:10,  8.10it/s]

 63%|██████▎   | 18928/30196 [39:21<22:11,  8.46it/s]

 63%|██████▎   | 18929/30196 [39:21<23:05,  8.13it/s]

 63%|██████▎   | 18931/30196 [39:21<21:46,  8.62it/s]

 63%|██████▎   | 18932/30196 [39:22<24:14,  7.74it/s]

 63%|██████▎   | 18934/30196 [39:22<19:50,  9.46it/s]

 63%|██████▎   | 18935/30196 [39:22<20:55,  8.97it/s]

 63%|██████▎   | 18936/30196 [39:22<21:56,  8.55it/s]

 63%|██████▎   | 18937/30196 [39:22<21:34,  8.69it/s]

 63%|██████▎   | 18938/30196 [39:22<22:22,  8.38it/s]

 63%|██████▎   | 18940/30196 [39:22<20:03,  9.35it/s]

 63%|██████▎   | 18942/30196 [39:23<19:20,  9.70it/s]

 63%|██████▎   | 18943/30196 [39:23<20:27,  9.17it/s]

 63%|██████▎   | 18944/30196 [39:23<23:34,  7.96it/s]

 63%|██████▎   | 18946/30196 [39:23<18:17, 10.25it/s]

 63%|██████▎   | 18948/30196 [39:23<18:35, 10.08it/s]

 63%|██████▎   | 18950/30196 [39:24<21:02,  8.91it/s]

 63%|██████▎   | 18952/30196 [39:24<19:49,  9.45it/s]

 63%|██████▎   | 18954/30196 [39:24<22:23,  8.36it/s]

 63%|██████▎   | 18956/30196 [39:24<20:50,  8.99it/s]

 63%|██████▎   | 18957/30196 [39:24<21:29,  8.72it/s]

 63%|██████▎   | 18958/30196 [39:24<21:04,  8.89it/s]

 63%|██████▎   | 18959/30196 [39:25<22:32,  8.31it/s]

 63%|██████▎   | 18961/30196 [39:25<30:15,  6.19it/s]

 63%|██████▎   | 18963/30196 [39:25<27:29,  6.81it/s]

 63%|██████▎   | 18965/30196 [39:25<22:41,  8.25it/s]

 63%|██████▎   | 18967/30196 [39:26<20:44,  9.02it/s]

 63%|██████▎   | 18968/30196 [39:26<20:43,  9.03it/s]

 63%|██████▎   | 18969/30196 [39:26<23:28,  7.97it/s]

 63%|██████▎   | 18970/30196 [39:26<23:42,  7.89it/s]

 63%|██████▎   | 18971/30196 [39:26<24:39,  7.59it/s]

 63%|██████▎   | 18972/30196 [39:26<29:04,  6.43it/s]

 63%|██████▎   | 18973/30196 [39:26<26:29,  7.06it/s]

 63%|██████▎   | 18975/30196 [39:27<21:24,  8.74it/s]

 63%|██████▎   | 18977/30196 [39:27<21:34,  8.67it/s]

 63%|██████▎   | 18979/30196 [39:27<18:56,  9.87it/s]

 63%|██████▎   | 18981/30196 [39:27<16:48, 11.13it/s]

 63%|██████▎   | 18983/30196 [39:27<18:14, 10.25it/s]

 63%|██████▎   | 18985/30196 [39:28<20:37,  9.06it/s]

 63%|██████▎   | 18986/30196 [39:28<21:29,  8.70it/s]

 63%|██████▎   | 18988/30196 [39:28<19:55,  9.38it/s]

 63%|██████▎   | 18989/30196 [39:28<22:39,  8.24it/s]

 63%|██████▎   | 18990/30196 [39:28<23:04,  8.09it/s]

 63%|██████▎   | 18991/30196 [39:28<23:26,  7.97it/s]

 63%|██████▎   | 18992/30196 [39:29<27:18,  6.84it/s]

 63%|██████▎   | 18993/30196 [39:29<25:15,  7.39it/s]

 63%|██████▎   | 18994/30196 [39:29<23:58,  7.79it/s]

 63%|██████▎   | 18995/30196 [39:29<24:05,  7.75it/s]

 63%|██████▎   | 18997/30196 [39:29<19:22,  9.63it/s]

 63%|██████▎   | 18998/30196 [39:29<22:09,  8.42it/s]

 63%|██████▎   | 18999/30196 [39:29<21:27,  8.70it/s]

 63%|██████▎   | 19000/30196 [39:29<21:11,  8.81it/s]

 63%|██████▎   | 19002/30196 [39:30<16:41, 11.18it/s]

 63%|██████▎   | 19004/30196 [39:30<16:12, 11.51it/s]

 63%|██████▎   | 19006/30196 [39:30<16:27, 11.33it/s]

 63%|██████▎   | 19008/30196 [39:30<15:01, 12.41it/s]

 63%|██████▎   | 19010/30196 [39:30<13:40, 13.63it/s]

 63%|██████▎   | 19012/30196 [39:31<21:21,  8.73it/s]

 63%|██████▎   | 19014/30196 [39:31<19:01,  9.80it/s]

 63%|██████▎   | 19016/30196 [39:31<25:26,  7.32it/s]

 63%|██████▎   | 19018/30196 [39:31<26:28,  7.04it/s]

 63%|██████▎   | 19020/30196 [39:32<24:39,  7.56it/s]

 63%|██████▎   | 19021/30196 [39:32<24:36,  7.57it/s]

 63%|██████▎   | 19023/30196 [39:32<21:14,  8.77it/s]

 63%|██████▎   | 19025/30196 [39:32<20:25,  9.12it/s]

 63%|██████▎   | 19027/30196 [39:32<20:34,  9.05it/s]

 63%|██████▎   | 19029/30196 [39:33<28:56,  6.43it/s]

 63%|██████▎   | 19030/30196 [39:33<27:22,  6.80it/s]

 63%|██████▎   | 19032/30196 [39:33<23:38,  7.87it/s]

 63%|██████▎   | 19033/30196 [39:33<22:46,  8.17it/s]

 63%|██████▎   | 19034/30196 [39:33<24:35,  7.57it/s]

 63%|██████▎   | 19035/30196 [39:34<26:24,  7.04it/s]

 63%|██████▎   | 19036/30196 [39:34<31:37,  5.88it/s]

 63%|██████▎   | 19038/30196 [39:34<27:52,  6.67it/s]

 63%|██████▎   | 19040/30196 [39:34<27:55,  6.66it/s]

 63%|██████▎   | 19041/30196 [39:35<30:39,  6.06it/s]

 63%|██████▎   | 19043/30196 [39:35<26:17,  7.07it/s]

 63%|██████▎   | 19045/30196 [39:35<24:42,  7.52it/s]

 63%|██████▎   | 19046/30196 [39:35<23:40,  7.85it/s]

 63%|██████▎   | 19048/30196 [39:35<20:48,  8.93it/s]

 63%|██████▎   | 19049/30196 [39:36<24:27,  7.59it/s]

 63%|██████▎   | 19050/30196 [39:36<26:24,  7.03it/s]

 63%|██████▎   | 19051/30196 [39:36<29:35,  6.28it/s]

 63%|██████▎   | 19052/30196 [39:36<30:16,  6.14it/s]

 63%|██████▎   | 19054/30196 [39:36<26:01,  7.14it/s]

 63%|██████▎   | 19056/30196 [39:37<22:49,  8.14it/s]

 63%|██████▎   | 19058/30196 [39:37<20:33,  9.03it/s]

 63%|██████▎   | 19059/30196 [39:37<21:41,  8.56it/s]

 63%|██████▎   | 19060/30196 [39:37<21:12,  8.75it/s]

 63%|██████▎   | 19062/30196 [39:37<23:01,  8.06it/s]

 63%|██████▎   | 19064/30196 [39:37<19:03,  9.73it/s]

 63%|██████▎   | 19066/30196 [39:38<20:18,  9.13it/s]

 63%|██████▎   | 19067/30196 [39:38<21:32,  8.61it/s]

 63%|██████▎   | 19069/30196 [39:38<23:39,  7.84it/s]

 63%|██████▎   | 19071/30196 [39:38<26:25,  7.02it/s]

 63%|██████▎   | 19074/30196 [39:39<21:13,  8.73it/s]

 63%|██████▎   | 19075/30196 [39:39<24:28,  7.57it/s]

 63%|██████▎   | 19076/30196 [39:39<23:39,  7.83it/s]

 63%|██████▎   | 19078/30196 [39:39<21:55,  8.45it/s]

 63%|██████▎   | 19080/30196 [39:39<20:52,  8.87it/s]

 63%|██████▎   | 19081/30196 [39:40<23:04,  8.03it/s]

 63%|██████▎   | 19083/30196 [39:40<21:44,  8.52it/s]

 63%|██████▎   | 19084/30196 [39:40<21:24,  8.65it/s]

 63%|██████▎   | 19086/30196 [39:40<23:14,  7.97it/s]

 63%|██████▎   | 19088/30196 [39:40<22:56,  8.07it/s]

 63%|██████▎   | 19089/30196 [39:41<23:11,  7.98it/s]

 63%|██████▎   | 19091/30196 [39:41<23:15,  7.96it/s]

 63%|██████▎   | 19093/30196 [39:41<20:58,  8.82it/s]

 63%|██████▎   | 19094/30196 [39:41<22:57,  8.06it/s]

 63%|██████▎   | 19096/30196 [39:41<22:34,  8.20it/s]

 63%|██████▎   | 19097/30196 [39:41<22:08,  8.35it/s]

 63%|██████▎   | 19099/30196 [39:42<21:48,  8.48it/s]

 63%|██████▎   | 19100/30196 [39:42<22:41,  8.15it/s]

 63%|██████▎   | 19101/30196 [39:42<23:11,  7.97it/s]

 63%|██████▎   | 19102/30196 [39:42<23:34,  7.84it/s]

 63%|██████▎   | 19104/30196 [39:42<23:49,  7.76it/s]

 63%|██████▎   | 19106/30196 [39:43<22:27,  8.23it/s]

 63%|██████▎   | 19108/30196 [39:43<18:34,  9.95it/s]

 63%|██████▎   | 19110/30196 [39:43<21:29,  8.60it/s]

 63%|██████▎   | 19111/30196 [39:43<22:34,  8.19it/s]

 63%|██████▎   | 19112/30196 [39:43<26:56,  6.86it/s]

 63%|██████▎   | 19113/30196 [39:44<26:59,  6.85it/s]

 63%|██████▎   | 19115/30196 [39:44<21:06,  8.75it/s]

 63%|██████▎   | 19116/30196 [39:44<25:11,  7.33it/s]

 63%|██████▎   | 19117/30196 [39:44<24:57,  7.40it/s]

 63%|██████▎   | 19118/30196 [39:44<24:55,  7.41it/s]

 63%|██████▎   | 19119/30196 [39:44<30:44,  6.01it/s]

 63%|██████▎   | 19121/30196 [39:45<28:01,  6.59it/s]

 63%|██████▎   | 19123/30196 [39:45<26:18,  7.02it/s]

 63%|██████▎   | 19125/30196 [39:45<24:41,  7.47it/s]

 63%|██████▎   | 19126/30196 [39:45<30:19,  6.08it/s]

 63%|██████▎   | 19127/30196 [39:46<32:08,  5.74it/s]

 63%|██████▎   | 19129/30196 [39:46<23:56,  7.70it/s]

 63%|██████▎   | 19131/30196 [39:46<21:14,  8.69it/s]

 63%|██████▎   | 19132/30196 [39:46<22:11,  8.31it/s]

 63%|██████▎   | 19134/30196 [39:46<17:28, 10.55it/s]

 63%|██████▎   | 19136/30196 [39:46<18:13, 10.12it/s]

 63%|██████▎   | 19138/30196 [39:47<18:01, 10.23it/s]

 63%|██████▎   | 19140/30196 [39:47<17:43, 10.39it/s]

 63%|██████▎   | 19142/30196 [39:47<20:46,  8.86it/s]

 63%|██████▎   | 19143/30196 [39:47<20:41,  8.90it/s]

 63%|██████▎   | 19145/30196 [39:47<18:13, 10.10it/s]

 63%|██████▎   | 19147/30196 [39:48<16:53, 10.90it/s]

 63%|██████▎   | 19149/30196 [39:48<15:48, 11.64it/s]

 63%|██████▎   | 19151/30196 [39:48<18:24, 10.00it/s]

 63%|██████▎   | 19153/30196 [39:48<17:07, 10.74it/s]

 63%|██████▎   | 19155/30196 [39:48<17:57, 10.24it/s]

 63%|██████▎   | 19157/30196 [39:48<16:42, 11.02it/s]

 63%|██████▎   | 19159/30196 [39:49<26:10,  7.03it/s]

 63%|██████▎   | 19160/30196 [39:49<28:26,  6.47it/s]

 63%|██████▎   | 19161/30196 [39:49<27:32,  6.68it/s]

 63%|██████▎   | 19162/30196 [39:50<30:44,  5.98it/s]

 63%|██████▎   | 19164/30196 [39:50<24:03,  7.64it/s]

 63%|██████▎   | 19165/30196 [39:50<25:25,  7.23it/s]

 63%|██████▎   | 19167/30196 [39:50<22:00,  8.35it/s]

 63%|██████▎   | 19169/30196 [39:50<21:53,  8.40it/s]

 63%|██████▎   | 19170/30196 [39:50<22:18,  8.24it/s]

 63%|██████▎   | 19172/30196 [39:51<20:05,  9.15it/s]

 63%|██████▎   | 19173/30196 [39:51<20:03,  9.16it/s]

 64%|██████▎   | 19175/30196 [39:51<18:34,  9.89it/s]

 64%|██████▎   | 19178/30196 [39:51<17:26, 10.53it/s]

 64%|██████▎   | 19180/30196 [39:51<21:32,  8.52it/s]

 64%|██████▎   | 19182/30196 [39:52<19:04,  9.62it/s]

 64%|██████▎   | 19184/30196 [39:52<17:01, 10.78it/s]

 64%|██████▎   | 19186/30196 [39:52<23:01,  7.97it/s]

 64%|██████▎   | 19188/30196 [39:52<22:12,  8.26it/s]

 64%|██████▎   | 19189/30196 [39:53<31:14,  5.87it/s]

 64%|██████▎   | 19191/30196 [39:53<26:49,  6.84it/s]

 64%|██████▎   | 19193/30196 [39:53<24:25,  7.51it/s]

 64%|██████▎   | 19194/30196 [39:53<25:28,  7.20it/s]

 64%|██████▎   | 19195/30196 [39:54<31:05,  5.90it/s]

 64%|██████▎   | 19196/30196 [39:54<29:26,  6.23it/s]

 64%|██████▎   | 19197/30196 [39:54<29:37,  6.19it/s]

 64%|██████▎   | 19199/30196 [39:54<25:12,  7.27it/s]

 64%|██████▎   | 19200/30196 [39:54<25:06,  7.30it/s]

 64%|██████▎   | 19201/30196 [39:54<25:14,  7.26it/s]

 64%|██████▎   | 19203/30196 [39:55<23:10,  7.91it/s]

 64%|██████▎   | 19204/30196 [39:55<26:34,  6.90it/s]

 64%|██████▎   | 19205/30196 [39:55<28:09,  6.51it/s]

 64%|██████▎   | 19207/30196 [39:55<24:18,  7.54it/s]

 64%|██████▎   | 19208/30196 [39:55<23:20,  7.85it/s]

 64%|██████▎   | 19210/30196 [39:56<22:52,  8.00it/s]

 64%|██████▎   | 19212/30196 [39:56<24:22,  7.51it/s]

 64%|██████▎   | 19214/30196 [39:56<21:38,  8.46it/s]

 64%|██████▎   | 19215/30196 [39:56<30:43,  5.96it/s]

 64%|██████▎   | 19216/30196 [39:57<29:16,  6.25it/s]

 64%|██████▎   | 19217/30196 [39:57<33:43,  5.43it/s]

 64%|██████▎   | 19219/30196 [39:57<26:02,  7.02it/s]

 64%|██████▎   | 19220/30196 [39:57<24:29,  7.47it/s]

 64%|██████▎   | 19221/30196 [39:57<26:30,  6.90it/s]

 64%|██████▎   | 19222/30196 [39:57<24:35,  7.44it/s]

 64%|██████▎   | 19225/30196 [39:58<19:19,  9.46it/s]

 64%|██████▎   | 19226/30196 [39:58<19:28,  9.39it/s]

 64%|██████▎   | 19228/30196 [39:58<17:28, 10.46it/s]

 64%|██████▎   | 19230/30196 [39:58<18:48,  9.72it/s]

 64%|██████▎   | 19231/30196 [39:58<23:22,  7.82it/s]

 64%|██████▎   | 19232/30196 [39:58<25:15,  7.23it/s]

 64%|██████▎   | 19234/30196 [39:59<24:00,  7.61it/s]

 64%|██████▎   | 19236/30196 [39:59<19:35,  9.32it/s]

 64%|██████▎   | 19238/30196 [39:59<19:55,  9.17it/s]

 64%|██████▎   | 19239/30196 [39:59<21:56,  8.33it/s]

 64%|██████▎   | 19241/30196 [39:59<20:24,  8.94it/s]

 64%|██████▎   | 19242/30196 [40:00<22:33,  8.09it/s]

 64%|██████▎   | 19245/30196 [40:00<17:55, 10.18it/s]

 64%|██████▎   | 19247/30196 [40:00<20:58,  8.70it/s]

 64%|██████▎   | 19248/30196 [40:00<22:36,  8.07it/s]

 64%|██████▎   | 19249/30196 [40:00<22:05,  8.26it/s]

 64%|██████▍   | 19250/30196 [40:01<23:09,  7.88it/s]

 64%|██████▍   | 19251/30196 [40:01<24:05,  7.57it/s]

 64%|██████▍   | 19253/30196 [40:01<20:14,  9.01it/s]

 64%|██████▍   | 19255/30196 [40:01<18:53,  9.65it/s]

 64%|██████▍   | 19256/30196 [40:01<19:54,  9.16it/s]

 64%|██████▍   | 19257/30196 [40:01<19:44,  9.24it/s]

 64%|██████▍   | 19258/30196 [40:01<21:12,  8.59it/s]

 64%|██████▍   | 19260/30196 [40:02<18:09, 10.04it/s]

 64%|██████▍   | 19261/30196 [40:02<18:35,  9.80it/s]

 64%|██████▍   | 19262/30196 [40:02<18:43,  9.73it/s]

 64%|██████▍   | 19264/30196 [40:02<20:27,  8.91it/s]

 64%|██████▍   | 19266/30196 [40:02<19:44,  9.23it/s]

 64%|██████▍   | 19269/30196 [40:02<14:49, 12.28it/s]

 64%|██████▍   | 19271/30196 [40:03<16:16, 11.18it/s]

 64%|██████▍   | 19273/30196 [40:03<17:57, 10.13it/s]

 64%|██████▍   | 19275/30196 [40:03<18:22,  9.91it/s]

 64%|██████▍   | 19277/30196 [40:03<16:49, 10.82it/s]

 64%|██████▍   | 19279/30196 [40:03<17:43, 10.26it/s]

 64%|██████▍   | 19281/30196 [40:04<18:20,  9.91it/s]

 64%|██████▍   | 19283/30196 [40:04<24:47,  7.34it/s]

 64%|██████▍   | 19284/30196 [40:04<23:50,  7.63it/s]

 64%|██████▍   | 19285/30196 [40:04<22:53,  7.94it/s]

 64%|██████▍   | 19286/30196 [40:04<24:51,  7.31it/s]

 64%|██████▍   | 19288/30196 [40:05<20:15,  8.97it/s]

 64%|██████▍   | 19290/30196 [40:05<18:17,  9.93it/s]

 64%|██████▍   | 19292/30196 [40:05<27:22,  6.64it/s]

 64%|██████▍   | 19293/30196 [40:05<25:58,  7.00it/s]

 64%|██████▍   | 19294/30196 [40:06<25:55,  7.01it/s]

 64%|██████▍   | 19295/30196 [40:06<26:06,  6.96it/s]

 64%|██████▍   | 19296/30196 [40:06<25:42,  7.07it/s]

 64%|██████▍   | 19298/30196 [40:06<21:38,  8.40it/s]

 64%|██████▍   | 19299/30196 [40:06<23:37,  7.69it/s]

 64%|██████▍   | 19300/30196 [40:06<25:11,  7.21it/s]

 64%|██████▍   | 19301/30196 [40:06<26:32,  6.84it/s]

 64%|██████▍   | 19303/30196 [40:07<23:30,  7.72it/s]

 64%|██████▍   | 19304/30196 [40:07<23:57,  7.58it/s]

 64%|██████▍   | 19306/30196 [40:07<22:59,  7.89it/s]

 64%|██████▍   | 19307/30196 [40:07<23:33,  7.70it/s]

 64%|██████▍   | 19308/30196 [40:07<23:37,  7.68it/s]

 64%|██████▍   | 19310/30196 [40:07<20:03,  9.04it/s]

 64%|██████▍   | 19312/30196 [40:08<16:47, 10.81it/s]

 64%|██████▍   | 19314/30196 [40:08<17:57, 10.10it/s]

 64%|██████▍   | 19316/30196 [40:08<17:43, 10.23it/s]

 64%|██████▍   | 19318/30196 [40:08<18:15,  9.93it/s]

 64%|██████▍   | 19320/30196 [40:08<18:49,  9.63it/s]

 64%|██████▍   | 19321/30196 [40:09<18:50,  9.62it/s]

 64%|██████▍   | 19322/30196 [40:09<19:58,  9.07it/s]

 64%|██████▍   | 19323/30196 [40:09<30:28,  5.95it/s]

 64%|██████▍   | 19325/30196 [40:09<23:06,  7.84it/s]

 64%|██████▍   | 19326/30196 [40:09<23:14,  7.80it/s]

 64%|██████▍   | 19327/30196 [40:10<26:35,  6.81it/s]

 64%|██████▍   | 19330/30196 [40:10<20:15,  8.94it/s]

 64%|██████▍   | 19332/30196 [40:10<18:29,  9.79it/s]

 64%|██████▍   | 19334/30196 [40:10<23:41,  7.64it/s]

 64%|██████▍   | 19336/30196 [40:11<21:24,  8.45it/s]

 64%|██████▍   | 19337/30196 [40:11<22:19,  8.11it/s]

 64%|██████▍   | 19338/30196 [40:11<25:22,  7.13it/s]

 64%|██████▍   | 19340/30196 [40:11<23:22,  7.74it/s]

 64%|██████▍   | 19342/30196 [40:11<24:47,  7.30it/s]

 64%|██████▍   | 19343/30196 [40:12<24:33,  7.37it/s]

 64%|██████▍   | 19344/30196 [40:12<24:46,  7.30it/s]

 64%|██████▍   | 19345/30196 [40:12<23:37,  7.65it/s]

 64%|██████▍   | 19347/30196 [40:12<19:27,  9.29it/s]

 64%|██████▍   | 19350/30196 [40:12<14:24, 12.55it/s]

 64%|██████▍   | 19352/30196 [40:12<16:39, 10.85it/s]

 64%|██████▍   | 19354/30196 [40:13<21:12,  8.52it/s]

 64%|██████▍   | 19355/30196 [40:13<22:53,  7.89it/s]

 64%|██████▍   | 19357/30196 [40:13<20:39,  8.74it/s]

 64%|██████▍   | 19358/30196 [40:13<20:20,  8.88it/s]

 64%|██████▍   | 19359/30196 [40:13<21:33,  8.38it/s]

 64%|██████▍   | 19361/30196 [40:13<17:17, 10.44it/s]

 64%|██████▍   | 19363/30196 [40:14<21:55,  8.24it/s]

 64%|██████▍   | 19364/30196 [40:14<22:26,  8.05it/s]

 64%|██████▍   | 19365/30196 [40:14<23:04,  7.82it/s]

 64%|██████▍   | 19367/30196 [40:14<22:19,  8.09it/s]

 64%|██████▍   | 19368/30196 [40:14<22:56,  7.87it/s]

 64%|██████▍   | 19369/30196 [40:15<24:38,  7.32it/s]

 64%|██████▍   | 19371/30196 [40:15<21:42,  8.31it/s]

 64%|██████▍   | 19373/30196 [40:15<18:09,  9.93it/s]

 64%|██████▍   | 19375/30196 [40:15<16:24, 10.99it/s]

 64%|██████▍   | 19377/30196 [40:15<14:59, 12.03it/s]

 64%|██████▍   | 19379/30196 [40:15<14:50, 12.14it/s]

 64%|██████▍   | 19381/30196 [40:16<17:16, 10.44it/s]

 64%|██████▍   | 19383/30196 [40:16<19:47,  9.10it/s]

 64%|██████▍   | 19385/30196 [40:16<21:04,  8.55it/s]

 64%|██████▍   | 19387/30196 [40:16<20:44,  8.69it/s]

 64%|██████▍   | 19389/30196 [40:17<22:37,  7.96it/s]

 64%|██████▍   | 19390/30196 [40:17<24:08,  7.46it/s]

 64%|██████▍   | 19392/30196 [40:17<20:00,  9.00it/s]

 64%|██████▍   | 19393/30196 [40:17<22:10,  8.12it/s]

 64%|██████▍   | 19394/30196 [40:17<21:40,  8.31it/s]

 64%|██████▍   | 19395/30196 [40:17<21:12,  8.49it/s]

 64%|██████▍   | 19396/30196 [40:17<20:49,  8.64it/s]

 64%|██████▍   | 19398/30196 [40:18<18:05,  9.95it/s]

 64%|██████▍   | 19400/30196 [40:18<23:50,  7.55it/s]

 64%|██████▍   | 19401/30196 [40:18<23:53,  7.53it/s]

 64%|██████▍   | 19403/30196 [40:18<21:04,  8.53it/s]

 64%|██████▍   | 19404/30196 [40:18<24:44,  7.27it/s]

 64%|██████▍   | 19406/30196 [40:19<21:25,  8.39it/s]

 64%|██████▍   | 19407/30196 [40:19<20:54,  8.60it/s]

 64%|██████▍   | 19408/30196 [40:19<21:42,  8.28it/s]

 64%|██████▍   | 19409/30196 [40:19<22:18,  8.06it/s]

 64%|██████▍   | 19410/30196 [40:19<24:27,  7.35it/s]

 64%|██████▍   | 19411/30196 [40:19<25:57,  6.92it/s]

 64%|██████▍   | 19412/30196 [40:20<26:58,  6.66it/s]

 64%|██████▍   | 19414/30196 [40:20<19:09,  9.38it/s]

 64%|██████▍   | 19416/30196 [40:20<18:32,  9.69it/s]

 64%|██████▍   | 19418/30196 [40:20<17:35, 10.21it/s]

 64%|██████▍   | 19420/30196 [40:20<24:29,  7.33it/s]

 64%|██████▍   | 19422/30196 [40:21<20:28,  8.77it/s]

 64%|██████▍   | 19424/30196 [40:21<19:43,  9.10it/s]

 64%|██████▍   | 19426/30196 [40:21<20:02,  8.96it/s]

 64%|██████▍   | 19427/30196 [40:21<21:48,  8.23it/s]

 64%|██████▍   | 19429/30196 [40:21<20:52,  8.60it/s]

 64%|██████▍   | 19431/30196 [40:22<19:28,  9.21it/s]

 64%|██████▍   | 19432/30196 [40:22<20:24,  8.79it/s]

 64%|██████▍   | 19434/30196 [40:22<17:58,  9.98it/s]

 64%|██████▍   | 19436/30196 [40:22<18:57,  9.46it/s]

 64%|██████▍   | 19439/30196 [40:22<14:27, 12.40it/s]

 64%|██████▍   | 19441/30196 [40:22<14:57, 11.98it/s]

 64%|██████▍   | 19443/30196 [40:23<14:00, 12.79it/s]

 64%|██████▍   | 19445/30196 [40:23<16:41, 10.73it/s]

 64%|██████▍   | 19447/30196 [40:23<16:52, 10.61it/s]

 64%|██████▍   | 19450/30196 [40:23<17:25, 10.28it/s]

 64%|██████▍   | 19452/30196 [40:24<21:20,  8.39it/s]

 64%|██████▍   | 19453/30196 [40:24<22:08,  8.09it/s]

 64%|██████▍   | 19456/30196 [40:24<18:54,  9.46it/s]

 64%|██████▍   | 19458/30196 [40:24<17:42, 10.11it/s]

 64%|██████▍   | 19461/30196 [40:24<16:11, 11.05it/s]

 64%|██████▍   | 19463/30196 [40:25<17:14, 10.38it/s]

 64%|██████▍   | 19465/30196 [40:25<17:03, 10.49it/s]

 64%|██████▍   | 19467/30196 [40:25<16:03, 11.14it/s]

 64%|██████▍   | 19469/30196 [40:25<21:09,  8.45it/s]

 64%|██████▍   | 19471/30196 [40:26<20:07,  8.88it/s]

 64%|██████▍   | 19472/30196 [40:26<20:49,  8.58it/s]

 64%|██████▍   | 19473/30196 [40:26<20:57,  8.53it/s]

 64%|██████▍   | 19475/30196 [40:26<21:35,  8.27it/s]

 64%|██████▍   | 19476/30196 [40:26<21:12,  8.42it/s]

 65%|██████▍   | 19478/30196 [40:26<17:48, 10.03it/s]

 65%|██████▍   | 19480/30196 [40:27<18:27,  9.67it/s]

 65%|██████▍   | 19483/30196 [40:27<16:39, 10.72it/s]

 65%|██████▍   | 19485/30196 [40:27<18:08,  9.84it/s]

 65%|██████▍   | 19487/30196 [40:27<20:20,  8.77it/s]

 65%|██████▍   | 19488/30196 [40:27<21:59,  8.11it/s]

 65%|██████▍   | 19489/30196 [40:28<23:38,  7.55it/s]

 65%|██████▍   | 19491/30196 [40:28<19:30,  9.15it/s]

 65%|██████▍   | 19492/30196 [40:28<21:57,  8.13it/s]

 65%|██████▍   | 19494/30196 [40:28<21:13,  8.41it/s]

 65%|██████▍   | 19496/30196 [40:28<19:06,  9.33it/s]

 65%|██████▍   | 19498/30196 [40:29<17:24, 10.24it/s]

 65%|██████▍   | 19500/30196 [40:29<23:03,  7.73it/s]

 65%|██████▍   | 19501/30196 [40:29<28:19,  6.29it/s]

 65%|██████▍   | 19502/30196 [40:29<30:59,  5.75it/s]

 65%|██████▍   | 19504/30196 [40:30<25:57,  6.86it/s]

 65%|██████▍   | 19505/30196 [40:30<42:06,  4.23it/s]

 65%|██████▍   | 19506/30196 [40:30<39:41,  4.49it/s]

 65%|██████▍   | 19508/30196 [40:31<29:43,  5.99it/s]

 65%|██████▍   | 19509/30196 [40:31<32:10,  5.53it/s]

 65%|██████▍   | 19510/30196 [40:31<31:33,  5.64it/s]

 65%|██████▍   | 19512/30196 [40:31<25:08,  7.08it/s]

 65%|██████▍   | 19514/30196 [40:31<24:15,  7.34it/s]

 65%|██████▍   | 19515/30196 [40:32<28:34,  6.23it/s]

 65%|██████▍   | 19516/30196 [40:32<27:32,  6.46it/s]

 65%|██████▍   | 19517/30196 [40:32<26:38,  6.68it/s]

 65%|██████▍   | 19518/30196 [40:32<26:14,  6.78it/s]

 65%|██████▍   | 19519/30196 [40:32<27:32,  6.46it/s]

 65%|██████▍   | 19520/30196 [40:32<26:53,  6.62it/s]

 65%|██████▍   | 19521/30196 [40:32<24:50,  7.16it/s]

 65%|██████▍   | 19522/30196 [40:33<23:03,  7.72it/s]

 65%|██████▍   | 19524/30196 [40:33<18:21,  9.69it/s]

 65%|██████▍   | 19526/30196 [40:33<18:33,  9.58it/s]

 65%|██████▍   | 19527/30196 [40:33<19:45,  9.00it/s]

 65%|██████▍   | 19528/30196 [40:33<19:28,  9.13it/s]

 65%|██████▍   | 19529/30196 [40:33<22:07,  8.03it/s]

 65%|██████▍   | 19531/30196 [40:33<19:41,  9.02it/s]

 65%|██████▍   | 19533/30196 [40:34<22:02,  8.06it/s]

 65%|██████▍   | 19534/30196 [40:34<22:56,  7.74it/s]

 65%|██████▍   | 19535/30196 [40:34<22:09,  8.02it/s]

 65%|██████▍   | 19536/30196 [40:34<27:52,  6.37it/s]

 65%|██████▍   | 19537/30196 [40:35<33:15,  5.34it/s]

 65%|██████▍   | 19538/30196 [40:35<31:16,  5.68it/s]

 65%|██████▍   | 19539/30196 [40:35<32:43,  5.43it/s]

 65%|██████▍   | 19541/30196 [40:35<24:38,  7.21it/s]

 65%|██████▍   | 19542/30196 [40:35<27:31,  6.45it/s]

 65%|██████▍   | 19544/30196 [40:35<22:51,  7.77it/s]

 65%|██████▍   | 19545/30196 [40:36<22:07,  8.03it/s]

 65%|██████▍   | 19546/30196 [40:36<22:46,  7.79it/s]

 65%|██████▍   | 19548/30196 [40:36<19:46,  8.97it/s]

 65%|██████▍   | 19549/30196 [40:36<21:14,  8.35it/s]

 65%|██████▍   | 19550/30196 [40:36<30:37,  5.79it/s]

 65%|██████▍   | 19551/30196 [40:37<28:44,  6.17it/s]

 65%|██████▍   | 19552/30196 [40:37<25:59,  6.82it/s]

 65%|██████▍   | 19554/30196 [40:37<21:38,  8.20it/s]

 65%|██████▍   | 19555/30196 [40:37<25:44,  6.89it/s]

 65%|██████▍   | 19557/30196 [40:37<19:40,  9.01it/s]

 65%|██████▍   | 19559/30196 [40:37<19:35,  9.05it/s]

 65%|██████▍   | 19560/30196 [40:37<20:16,  8.75it/s]

 65%|██████▍   | 19561/30196 [40:38<22:31,  7.87it/s]

 65%|██████▍   | 19562/30196 [40:38<24:21,  7.28it/s]

 65%|██████▍   | 19564/30196 [40:38<19:17,  9.19it/s]

 65%|██████▍   | 19565/30196 [40:38<20:51,  8.50it/s]

 65%|██████▍   | 19567/30196 [40:38<19:41,  8.99it/s]

 65%|██████▍   | 19568/30196 [40:38<20:49,  8.50it/s]

 65%|██████▍   | 19570/30196 [40:39<21:08,  8.38it/s]

 65%|██████▍   | 19571/30196 [40:39<21:42,  8.16it/s]

 65%|██████▍   | 19572/30196 [40:39<23:57,  7.39it/s]

 65%|██████▍   | 19573/30196 [40:39<24:25,  7.25it/s]

 65%|██████▍   | 19574/30196 [40:39<24:14,  7.30it/s]

 65%|██████▍   | 19576/30196 [40:39<19:56,  8.87it/s]

 65%|██████▍   | 19578/30196 [40:40<17:10, 10.30it/s]

 65%|██████▍   | 19580/30196 [40:40<17:30, 10.10it/s]

 65%|██████▍   | 19582/30196 [40:40<17:04, 10.36it/s]

 65%|██████▍   | 19584/30196 [40:40<15:38, 11.31it/s]

 65%|██████▍   | 19586/30196 [40:40<17:14, 10.25it/s]

 65%|██████▍   | 19588/30196 [40:41<20:06,  8.79it/s]

 65%|██████▍   | 19590/30196 [40:41<16:52, 10.47it/s]

 65%|██████▍   | 19592/30196 [40:41<18:39,  9.47it/s]

 65%|██████▍   | 19594/30196 [40:41<22:24,  7.89it/s]

 65%|██████▍   | 19596/30196 [40:42<21:32,  8.20it/s]

 65%|██████▍   | 19597/30196 [40:42<21:49,  8.10it/s]

 65%|██████▍   | 19598/30196 [40:42<22:06,  7.99it/s]

 65%|██████▍   | 19600/30196 [40:42<21:22,  8.26it/s]

 65%|██████▍   | 19602/30196 [40:42<20:00,  8.83it/s]

 65%|██████▍   | 19603/30196 [40:42<20:44,  8.51it/s]

 65%|██████▍   | 19604/30196 [40:43<21:26,  8.23it/s]

 65%|██████▍   | 19605/30196 [40:43<22:32,  7.83it/s]

 65%|██████▍   | 19607/30196 [40:43<21:24,  8.25it/s]

 65%|██████▍   | 19608/30196 [40:43<20:47,  8.49it/s]

 65%|██████▍   | 19610/30196 [40:43<16:08, 10.93it/s]

 65%|██████▍   | 19612/30196 [40:44<21:53,  8.06it/s]

 65%|██████▍   | 19614/30196 [40:44<20:45,  8.49it/s]

 65%|██████▍   | 19615/30196 [40:44<21:34,  8.17it/s]

 65%|██████▍   | 19617/30196 [40:44<21:17,  8.28it/s]

 65%|██████▍   | 19619/30196 [40:44<19:59,  8.81it/s]

 65%|██████▍   | 19620/30196 [40:44<20:31,  8.59it/s]

 65%|██████▍   | 19622/30196 [40:45<17:55,  9.83it/s]

 65%|██████▍   | 19624/30196 [40:45<19:20,  9.11it/s]

 65%|██████▍   | 19625/30196 [40:45<19:59,  8.81it/s]

 65%|██████▍   | 19626/30196 [40:45<19:38,  8.97it/s]

 65%|██████▌   | 19628/30196 [40:45<18:05,  9.73it/s]

 65%|██████▌   | 19629/30196 [40:45<18:05,  9.73it/s]

 65%|██████▌   | 19630/30196 [40:45<19:25,  9.07it/s]

 65%|██████▌   | 19631/30196 [40:46<20:18,  8.67it/s]

 65%|██████▌   | 19632/30196 [40:46<23:18,  7.55it/s]

 65%|██████▌   | 19633/30196 [40:46<23:43,  7.42it/s]

 65%|██████▌   | 19634/30196 [40:46<22:10,  7.94it/s]

 65%|██████▌   | 19635/30196 [40:46<23:15,  7.57it/s]

 65%|██████▌   | 19636/30196 [40:46<24:03,  7.31it/s]

 65%|██████▌   | 19638/30196 [40:47<22:04,  7.97it/s]

 65%|██████▌   | 19639/30196 [40:47<21:25,  8.22it/s]

 65%|██████▌   | 19640/30196 [40:47<20:58,  8.39it/s]

 65%|██████▌   | 19641/30196 [40:47<22:05,  7.97it/s]

 65%|██████▌   | 19643/30196 [40:47<18:44,  9.39it/s]

 65%|██████▌   | 19645/30196 [40:47<16:30, 10.65it/s]

 65%|██████▌   | 19647/30196 [40:48<19:35,  8.97it/s]

 65%|██████▌   | 19648/30196 [40:48<19:21,  9.08it/s]

 65%|██████▌   | 19650/30196 [40:48<16:52, 10.42it/s]

 65%|██████▌   | 19652/30196 [40:48<16:26, 10.68it/s]

 65%|██████▌   | 19654/30196 [40:48<20:18,  8.65it/s]

 65%|██████▌   | 19655/30196 [40:48<21:57,  8.00it/s]

 65%|██████▌   | 19657/30196 [40:49<18:18,  9.59it/s]

 65%|██████▌   | 19659/30196 [40:49<19:05,  9.20it/s]

 65%|██████▌   | 19660/30196 [40:49<24:08,  7.27it/s]

 65%|██████▌   | 19661/30196 [40:49<24:04,  7.29it/s]

 65%|██████▌   | 19662/30196 [40:49<25:18,  6.94it/s]

 65%|██████▌   | 19663/30196 [40:49<24:44,  7.10it/s]

 65%|██████▌   | 19665/30196 [40:50<19:48,  8.86it/s]

 65%|██████▌   | 19666/30196 [40:50<20:59,  8.36it/s]

 65%|██████▌   | 19667/30196 [40:50<20:37,  8.51it/s]

 65%|██████▌   | 19669/30196 [40:50<20:38,  8.50it/s]

 65%|██████▌   | 19670/30196 [40:50<20:21,  8.62it/s]

 65%|██████▌   | 19671/30196 [40:50<19:52,  8.82it/s]

 65%|██████▌   | 19672/30196 [40:51<32:22,  5.42it/s]

 65%|██████▌   | 19674/30196 [40:51<24:37,  7.12it/s]

 65%|██████▌   | 19675/30196 [40:51<24:36,  7.13it/s]

 65%|██████▌   | 19677/30196 [40:51<21:46,  8.05it/s]

 65%|██████▌   | 19678/30196 [40:51<23:21,  7.50it/s]

 65%|██████▌   | 19680/30196 [40:52<20:24,  8.58it/s]

 65%|██████▌   | 19682/30196 [40:52<20:20,  8.62it/s]

 65%|██████▌   | 19683/30196 [40:52<19:55,  8.79it/s]

 65%|██████▌   | 19684/30196 [40:52<23:30,  7.45it/s]

 65%|██████▌   | 19685/30196 [40:52<22:54,  7.65it/s]

 65%|██████▌   | 19687/30196 [40:52<17:45,  9.87it/s]

 65%|██████▌   | 19689/30196 [40:53<17:09, 10.21it/s]

 65%|██████▌   | 19691/30196 [40:53<20:45,  8.43it/s]

 65%|██████▌   | 19693/30196 [40:53<18:34,  9.43it/s]

 65%|██████▌   | 19695/30196 [40:53<19:08,  9.14it/s]

 65%|██████▌   | 19697/30196 [40:53<16:06, 10.86it/s]

 65%|██████▌   | 19699/30196 [40:53<14:48, 11.81it/s]

 65%|██████▌   | 19701/30196 [40:54<15:39, 11.17it/s]

 65%|██████▌   | 19703/30196 [40:54<15:37, 11.20it/s]

 65%|██████▌   | 19705/30196 [40:54<16:27, 10.62it/s]

 65%|██████▌   | 19707/30196 [40:54<17:21, 10.07it/s]

 65%|██████▌   | 19709/30196 [40:55<18:29,  9.45it/s]

 65%|██████▌   | 19710/30196 [40:55<20:19,  8.60it/s]

 65%|██████▌   | 19712/30196 [40:55<18:14,  9.58it/s]

 65%|██████▌   | 19713/30196 [40:55<19:26,  8.99it/s]

 65%|██████▌   | 19714/30196 [40:55<23:33,  7.42it/s]

 65%|██████▌   | 19716/30196 [40:55<23:49,  7.33it/s]

 65%|██████▌   | 19718/30196 [40:56<21:05,  8.28it/s]

 65%|██████▌   | 19720/30196 [40:56<19:29,  8.95it/s]

 65%|██████▌   | 19721/30196 [40:56<21:24,  8.15it/s]

 65%|██████▌   | 19722/30196 [40:56<21:40,  8.06it/s]

 65%|██████▌   | 19723/30196 [40:56<22:19,  7.82it/s]

 65%|██████▌   | 19725/30196 [40:57<20:53,  8.35it/s]

 65%|██████▌   | 19727/30196 [40:57<20:52,  8.36it/s]

 65%|██████▌   | 19729/30196 [40:57<20:33,  8.49it/s]

 65%|██████▌   | 19730/30196 [40:57<21:07,  8.26it/s]

 65%|██████▌   | 19731/30196 [40:57<24:21,  7.16it/s]

 65%|██████▌   | 19733/30196 [40:58<28:04,  6.21it/s]

 65%|██████▌   | 19735/30196 [40:58<22:30,  7.75it/s]

 65%|██████▌   | 19737/30196 [40:58<23:20,  7.47it/s]

 65%|██████▌   | 19738/30196 [40:58<24:38,  7.07it/s]

 65%|██████▌   | 19739/30196 [40:58<26:02,  6.69it/s]

 65%|██████▌   | 19741/30196 [40:59<20:29,  8.51it/s]

 65%|██████▌   | 19743/30196 [40:59<19:21,  9.00it/s]

 65%|██████▌   | 19745/30196 [40:59<19:44,  8.82it/s]

 65%|██████▌   | 19746/30196 [40:59<20:38,  8.44it/s]

 65%|██████▌   | 19748/30196 [40:59<19:56,  8.73it/s]

 65%|██████▌   | 19749/30196 [41:00<19:46,  8.80it/s]

 65%|██████▌   | 19752/30196 [41:00<15:53, 10.96it/s]

 65%|██████▌   | 19754/30196 [41:00<14:14, 12.21it/s]

 65%|██████▌   | 19756/30196 [41:00<14:49, 11.74it/s]

 65%|██████▌   | 19758/30196 [41:00<17:46,  9.79it/s]

 65%|██████▌   | 19760/30196 [41:01<18:03,  9.63it/s]

 65%|██████▌   | 19762/30196 [41:01<15:41, 11.09it/s]

 65%|██████▌   | 19764/30196 [41:01<19:08,  9.09it/s]

 65%|██████▌   | 19766/30196 [41:01<18:25,  9.43it/s]

 65%|██████▌   | 19768/30196 [41:01<21:14,  8.18it/s]

 65%|██████▌   | 19769/30196 [41:02<20:41,  8.40it/s]

 65%|██████▌   | 19771/30196 [41:02<17:53,  9.71it/s]

 65%|██████▌   | 19773/30196 [41:02<21:09,  8.21it/s]

 65%|██████▌   | 19775/30196 [41:02<19:30,  8.90it/s]

 65%|██████▌   | 19776/30196 [41:02<21:11,  8.19it/s]

 65%|██████▌   | 19777/30196 [41:02<20:33,  8.45it/s]

 65%|██████▌   | 19778/30196 [41:03<21:02,  8.25it/s]

 66%|██████▌   | 19780/30196 [41:03<25:01,  6.94it/s]

 66%|██████▌   | 19782/30196 [41:03<22:58,  7.56it/s]

 66%|██████▌   | 19783/30196 [41:03<24:11,  7.18it/s]

 66%|██████▌   | 19784/30196 [41:04<24:15,  7.15it/s]

 66%|██████▌   | 19786/30196 [41:04<19:44,  8.79it/s]

 66%|██████▌   | 19788/30196 [41:04<25:54,  6.70it/s]

 66%|██████▌   | 19790/30196 [41:04<21:58,  7.90it/s]

 66%|██████▌   | 19792/30196 [41:04<20:13,  8.58it/s]

 66%|██████▌   | 19794/30196 [41:05<17:56,  9.66it/s]

 66%|██████▌   | 19796/30196 [41:05<19:38,  8.83it/s]

 66%|██████▌   | 19797/30196 [41:05<21:31,  8.05it/s]

 66%|██████▌   | 19799/30196 [41:05<22:17,  7.78it/s]

 66%|██████▌   | 19800/30196 [41:06<25:46,  6.72it/s]

 66%|██████▌   | 19801/30196 [41:06<26:27,  6.55it/s]

 66%|██████▌   | 19803/30196 [41:06<20:07,  8.61it/s]

 66%|██████▌   | 19805/30196 [41:06<16:42, 10.36it/s]

 66%|██████▌   | 19807/30196 [41:06<18:36,  9.30it/s]

 66%|██████▌   | 19809/30196 [41:06<17:31,  9.88it/s]

 66%|██████▌   | 19811/30196 [41:07<20:57,  8.26it/s]

 66%|██████▌   | 19813/30196 [41:07<20:20,  8.50it/s]

 66%|██████▌   | 19814/30196 [41:07<20:48,  8.32it/s]

 66%|██████▌   | 19815/30196 [41:07<21:10,  8.17it/s]

 66%|██████▌   | 19817/30196 [41:07<18:33,  9.32it/s]

 66%|██████▌   | 19819/30196 [41:07<15:35, 11.09it/s]

 66%|██████▌   | 19821/30196 [41:08<16:36, 10.41it/s]

 66%|██████▌   | 19823/30196 [41:08<23:32,  7.34it/s]

 66%|██████▌   | 19825/30196 [41:08<21:09,  8.17it/s]

 66%|██████▌   | 19826/30196 [41:08<21:44,  7.95it/s]

 66%|██████▌   | 19828/30196 [41:09<18:44,  9.22it/s]

 66%|██████▌   | 19830/30196 [41:09<19:26,  8.88it/s]

 66%|██████▌   | 19832/30196 [41:09<18:58,  9.11it/s]

 66%|██████▌   | 19833/30196 [41:09<19:38,  8.80it/s]

 66%|██████▌   | 19834/30196 [41:09<23:08,  7.46it/s]

 66%|██████▌   | 19835/30196 [41:10<30:31,  5.66it/s]

 66%|██████▌   | 19836/30196 [41:10<33:49,  5.11it/s]

 66%|██████▌   | 19838/30196 [41:10<30:54,  5.59it/s]

 66%|██████▌   | 19840/30196 [41:11<26:31,  6.51it/s]

 66%|██████▌   | 19841/30196 [41:11<24:54,  6.93it/s]

 66%|██████▌   | 19842/30196 [41:11<29:12,  5.91it/s]

 66%|██████▌   | 19843/30196 [41:11<26:26,  6.52it/s]

 66%|██████▌   | 19844/30196 [41:11<25:35,  6.74it/s]

 66%|██████▌   | 19845/30196 [41:11<29:32,  5.84it/s]

 66%|██████▌   | 19846/30196 [41:12<29:28,  5.85it/s]

 66%|██████▌   | 19847/30196 [41:12<31:52,  5.41it/s]

 66%|██████▌   | 19850/30196 [41:12<19:57,  8.64it/s]

 66%|██████▌   | 19852/30196 [41:12<20:08,  8.56it/s]

 66%|██████▌   | 19853/30196 [41:12<25:49,  6.67it/s]

 66%|██████▌   | 19854/30196 [41:13<26:24,  6.53it/s]

 66%|██████▌   | 19856/30196 [41:13<23:18,  7.40it/s]

 66%|██████▌   | 19857/30196 [41:13<23:08,  7.45it/s]

 66%|██████▌   | 19858/30196 [41:13<30:54,  5.57it/s]

 66%|██████▌   | 19860/30196 [41:14<27:16,  6.32it/s]

 66%|██████▌   | 19861/30196 [41:14<27:33,  6.25it/s]

 66%|██████▌   | 19862/30196 [41:14<34:55,  4.93it/s]

 66%|██████▌   | 19863/30196 [41:14<32:14,  5.34it/s]

 66%|██████▌   | 19865/30196 [41:14<22:52,  7.53it/s]

 66%|██████▌   | 19866/30196 [41:15<26:51,  6.41it/s]

 66%|██████▌   | 19869/30196 [41:15<17:38,  9.75it/s]

 66%|██████▌   | 19871/30196 [41:15<15:35, 11.04it/s]

 66%|██████▌   | 19873/30196 [41:15<15:39, 10.99it/s]

 66%|██████▌   | 19875/30196 [41:15<14:15, 12.06it/s]

 66%|██████▌   | 19877/30196 [41:15<18:13,  9.44it/s]

 66%|██████▌   | 19879/30196 [41:16<20:30,  8.38it/s]

 66%|██████▌   | 19881/30196 [41:16<21:56,  7.84it/s]

 66%|██████▌   | 19883/30196 [41:16<20:15,  8.48it/s]

 66%|██████▌   | 19885/30196 [41:16<18:22,  9.35it/s]

 66%|██████▌   | 19887/30196 [41:17<20:56,  8.20it/s]

 66%|██████▌   | 19888/30196 [41:17<22:19,  7.69it/s]

 66%|██████▌   | 19890/30196 [41:17<18:41,  9.19it/s]

 66%|██████▌   | 19892/30196 [41:17<18:50,  9.11it/s]

 66%|██████▌   | 19893/30196 [41:17<20:01,  8.57it/s]

 66%|██████▌   | 19895/30196 [41:18<19:38,  8.74it/s]

 66%|██████▌   | 19897/30196 [41:18<19:19,  8.88it/s]

 66%|██████▌   | 19898/30196 [41:18<19:56,  8.60it/s]

 66%|██████▌   | 19900/30196 [41:18<16:13, 10.58it/s]

 66%|██████▌   | 19902/30196 [41:18<14:52, 11.54it/s]

 66%|██████▌   | 19904/30196 [41:18<17:49,  9.62it/s]

 66%|██████▌   | 19906/30196 [41:19<16:46, 10.22it/s]

 66%|██████▌   | 19908/30196 [41:19<14:41, 11.66it/s]

 66%|██████▌   | 19910/30196 [41:19<14:52, 11.53it/s]

 66%|██████▌   | 19912/30196 [41:19<23:24,  7.32it/s]

 66%|██████▌   | 19914/30196 [41:20<23:56,  7.16it/s]

 66%|██████▌   | 19916/30196 [41:20<23:17,  7.36it/s]

 66%|██████▌   | 19917/30196 [41:20<26:06,  6.56it/s]

 66%|██████▌   | 19919/30196 [41:20<22:49,  7.50it/s]

 66%|██████▌   | 19920/30196 [41:21<25:17,  6.77it/s]

 66%|██████▌   | 19921/30196 [41:21<23:51,  7.18it/s]

 66%|██████▌   | 19922/30196 [41:21<24:56,  6.87it/s]

 66%|██████▌   | 19924/30196 [41:21<24:56,  6.87it/s]

 66%|██████▌   | 19926/30196 [41:21<22:46,  7.51it/s]

 66%|██████▌   | 19927/30196 [41:22<22:44,  7.52it/s]

 66%|██████▌   | 19928/30196 [41:22<26:17,  6.51it/s]

 66%|██████▌   | 19929/30196 [41:22<24:28,  6.99it/s]

 66%|██████▌   | 19931/30196 [41:22<20:35,  8.31it/s]

 66%|██████▌   | 19933/30196 [41:22<22:40,  7.55it/s]

 66%|██████▌   | 19934/30196 [41:23<29:22,  5.82it/s]

 66%|██████▌   | 19935/30196 [41:23<26:44,  6.40it/s]

 66%|██████▌   | 19937/30196 [41:23<24:47,  6.90it/s]

 66%|██████▌   | 19938/30196 [41:23<25:43,  6.64it/s]

 66%|██████▌   | 19939/30196 [41:23<26:23,  6.48it/s]

 66%|██████▌   | 19941/30196 [41:24<29:27,  5.80it/s]

 66%|██████▌   | 19942/30196 [41:24<26:49,  6.37it/s]

 66%|██████▌   | 19943/30196 [41:24<25:45,  6.63it/s]

 66%|██████▌   | 19944/30196 [41:24<26:30,  6.44it/s]

 66%|██████▌   | 19945/30196 [41:24<25:50,  6.61it/s]

 66%|██████▌   | 19946/30196 [41:24<25:04,  6.81it/s]

 66%|██████▌   | 19947/30196 [41:25<23:01,  7.42it/s]

 66%|██████▌   | 19949/30196 [41:25<20:59,  8.13it/s]

 66%|██████▌   | 19950/30196 [41:25<21:44,  7.85it/s]

 66%|██████▌   | 19952/30196 [41:25<23:45,  7.19it/s]

 66%|██████▌   | 19953/30196 [41:25<24:45,  6.90it/s]

 66%|██████▌   | 19954/30196 [41:25<23:18,  7.33it/s]

 66%|██████▌   | 19955/30196 [41:26<21:53,  7.80it/s]

 66%|██████▌   | 19957/30196 [41:26<18:33,  9.20it/s]

 66%|██████▌   | 19958/30196 [41:26<23:26,  7.28it/s]

 66%|██████▌   | 19960/30196 [41:26<18:33,  9.19it/s]

 66%|██████▌   | 19963/30196 [41:26<15:12, 11.22it/s]

 66%|██████▌   | 19965/30196 [41:26<15:41, 10.87it/s]

 66%|██████▌   | 19967/30196 [41:27<13:49, 12.34it/s]

 66%|██████▌   | 19969/30196 [41:27<13:02, 13.07it/s]

 66%|██████▌   | 19971/30196 [41:27<15:00, 11.36it/s]

 66%|██████▌   | 19973/30196 [41:27<16:22, 10.40it/s]

 66%|██████▌   | 19975/30196 [41:28<24:16,  7.02it/s]

 66%|██████▌   | 19977/30196 [41:28<20:24,  8.35it/s]

 66%|██████▌   | 19979/30196 [41:28<20:31,  8.30it/s]

 66%|██████▌   | 19981/30196 [41:28<17:49,  9.55it/s]

 66%|██████▌   | 19983/30196 [41:28<19:22,  8.79it/s]

 66%|██████▌   | 19985/30196 [41:29<21:16,  8.00it/s]

 66%|██████▌   | 19986/30196 [41:29<22:46,  7.47it/s]

 66%|██████▌   | 19989/30196 [41:29<17:21,  9.80it/s]

 66%|██████▌   | 19991/30196 [41:29<17:24,  9.77it/s]

 66%|██████▌   | 19993/30196 [41:30<17:49,  9.54it/s]

 66%|██████▌   | 19994/30196 [41:30<23:34,  7.21it/s]

 66%|██████▌   | 19996/30196 [41:30<20:26,  8.32it/s]

 66%|██████▌   | 19997/30196 [41:30<20:50,  8.16it/s]

 66%|██████▌   | 19999/30196 [41:30<16:29, 10.31it/s]

 66%|██████▌   | 20001/30196 [41:31<17:42,  9.60it/s]

 66%|██████▌   | 20003/30196 [41:31<19:14,  8.83it/s]

 66%|██████▌   | 20004/30196 [41:31<19:47,  8.58it/s]

 66%|██████▋   | 20005/30196 [41:31<21:51,  7.77it/s]

 66%|██████▋   | 20006/30196 [41:31<20:55,  8.11it/s]

 66%|██████▋   | 20007/30196 [41:31<22:44,  7.47it/s]

 66%|██████▋   | 20009/30196 [41:32<20:08,  8.43it/s]

 66%|██████▋   | 20010/30196 [41:32<20:45,  8.18it/s]

 66%|██████▋   | 20012/30196 [41:32<19:02,  8.91it/s]

 66%|██████▋   | 20013/30196 [41:32<19:53,  8.53it/s]

 66%|██████▋   | 20014/30196 [41:32<20:50,  8.14it/s]

 66%|██████▋   | 20015/30196 [41:32<23:15,  7.30it/s]

 66%|██████▋   | 20016/30196 [41:32<22:03,  7.69it/s]

 66%|██████▋   | 20017/30196 [41:33<25:44,  6.59it/s]

 66%|██████▋   | 20019/30196 [41:33<20:32,  8.26it/s]

 66%|██████▋   | 20021/30196 [41:33<18:54,  8.97it/s]

 66%|██████▋   | 20023/30196 [41:33<20:01,  8.47it/s]

 66%|██████▋   | 20024/30196 [41:33<19:45,  8.58it/s]

 66%|██████▋   | 20025/30196 [41:34<21:54,  7.74it/s]

 66%|██████▋   | 20027/30196 [41:34<21:56,  7.73it/s]

 66%|██████▋   | 20028/30196 [41:34<22:00,  7.70it/s]

 66%|██████▋   | 20029/30196 [41:34<25:07,  6.74it/s]

 66%|██████▋   | 20030/30196 [41:34<24:20,  6.96it/s]

 66%|██████▋   | 20032/30196 [41:34<21:56,  7.72it/s]

 66%|██████▋   | 20034/30196 [41:35<20:28,  8.27it/s]

 66%|██████▋   | 20036/30196 [41:35<17:33,  9.65it/s]

 66%|██████▋   | 20037/30196 [41:35<22:37,  7.48it/s]

 66%|██████▋   | 20038/30196 [41:35<21:33,  7.85it/s]

 66%|██████▋   | 20040/30196 [41:35<19:58,  8.47it/s]

 66%|██████▋   | 20041/30196 [41:36<21:45,  7.78it/s]

 66%|██████▋   | 20042/30196 [41:36<20:46,  8.15it/s]

 66%|██████▋   | 20043/30196 [41:36<22:48,  7.42it/s]

 66%|██████▋   | 20044/30196 [41:36<21:38,  7.82it/s]

 66%|██████▋   | 20045/30196 [41:36<23:21,  7.24it/s]

 66%|██████▋   | 20046/30196 [41:37<40:07,  4.22it/s]

 66%|██████▋   | 20048/30196 [41:37<27:46,  6.09it/s]

 66%|██████▋   | 20049/30196 [41:37<25:34,  6.61it/s]

 66%|██████▋   | 20050/30196 [41:37<23:44,  7.12it/s]

 66%|██████▋   | 20051/30196 [41:37<22:08,  7.64it/s]

 66%|██████▋   | 20052/30196 [41:37<26:55,  6.28it/s]

 66%|██████▋   | 20054/30196 [41:38<22:21,  7.56it/s]

 66%|██████▋   | 20056/30196 [41:38<21:29,  7.87it/s]

 66%|██████▋   | 20058/30196 [41:38<17:47,  9.50it/s]

 66%|██████▋   | 20060/30196 [41:38<19:07,  8.83it/s]

 66%|██████▋   | 20061/30196 [41:38<20:14,  8.35it/s]

 66%|██████▋   | 20062/30196 [41:39<26:57,  6.27it/s]

 66%|██████▋   | 20064/30196 [41:39<23:09,  7.29it/s]

 66%|██████▋   | 20066/30196 [41:39<18:15,  9.25it/s]

 66%|██████▋   | 20068/30196 [41:39<19:35,  8.62it/s]

 66%|██████▋   | 20069/30196 [41:39<25:08,  6.71it/s]

 66%|██████▋   | 20070/30196 [41:40<23:31,  7.17it/s]

 66%|██████▋   | 20071/30196 [41:40<26:42,  6.32it/s]

 66%|██████▋   | 20072/30196 [41:40<24:26,  6.90it/s]

 66%|██████▋   | 20073/30196 [41:40<22:39,  7.45it/s]

 66%|██████▋   | 20075/30196 [41:40<22:05,  7.64it/s]

 66%|██████▋   | 20076/30196 [41:40<21:01,  8.02it/s]

 66%|██████▋   | 20078/30196 [41:41<19:22,  8.71it/s]

 66%|██████▋   | 20079/30196 [41:41<21:33,  7.82it/s]

 67%|██████▋   | 20081/30196 [41:41<17:56,  9.40it/s]

 67%|██████▋   | 20083/30196 [41:41<15:31, 10.85it/s]

 67%|██████▋   | 20085/30196 [41:41<14:04, 11.97it/s]

 67%|██████▋   | 20087/30196 [41:41<17:08,  9.83it/s]

 67%|██████▋   | 20089/30196 [41:42<18:16,  9.22it/s]

 67%|██████▋   | 20091/30196 [41:42<22:02,  7.64it/s]

 67%|██████▋   | 20092/30196 [41:42<21:23,  7.87it/s]

 67%|██████▋   | 20094/30196 [41:42<20:04,  8.39it/s]

 67%|██████▋   | 20095/30196 [41:42<20:58,  8.02it/s]

 67%|██████▋   | 20096/30196 [41:43<20:22,  8.26it/s]

 67%|██████▋   | 20098/30196 [41:43<17:47,  9.46it/s]

 67%|██████▋   | 20100/30196 [41:43<17:55,  9.39it/s]

 67%|██████▋   | 20101/30196 [41:43<18:42,  8.99it/s]

 67%|██████▋   | 20103/30196 [41:43<16:16, 10.34it/s]

 67%|██████▋   | 20105/30196 [41:43<14:55, 11.27it/s]

 67%|██████▋   | 20107/30196 [41:44<13:38, 12.32it/s]

 67%|██████▋   | 20109/30196 [41:44<12:10, 13.81it/s]

 67%|██████▋   | 20111/30196 [41:44<13:38, 12.32it/s]

 67%|██████▋   | 20113/30196 [41:44<15:00, 11.20it/s]

 67%|██████▋   | 20115/30196 [41:44<16:00, 10.49it/s]

 67%|██████▋   | 20117/30196 [41:45<18:04,  9.30it/s]

 67%|██████▋   | 20119/30196 [41:45<17:47,  9.44it/s]

 67%|██████▋   | 20120/30196 [41:45<17:46,  9.45it/s]

 67%|██████▋   | 20122/30196 [41:45<16:07, 10.41it/s]

 67%|██████▋   | 20124/30196 [41:45<16:04, 10.44it/s]

 67%|██████▋   | 20126/30196 [41:46<23:18,  7.20it/s]

 67%|██████▋   | 20128/30196 [41:46<20:46,  8.07it/s]

 67%|██████▋   | 20130/30196 [41:46<20:51,  8.04it/s]

 67%|██████▋   | 20131/30196 [41:46<23:31,  7.13it/s]

 67%|██████▋   | 20132/30196 [41:46<23:22,  7.18it/s]

 67%|██████▋   | 20133/30196 [41:47<25:56,  6.47it/s]

 67%|██████▋   | 20134/30196 [41:47<24:06,  6.96it/s]

 67%|██████▋   | 20135/30196 [41:47<23:04,  7.27it/s]

 67%|██████▋   | 20137/30196 [41:47<21:24,  7.83it/s]

 67%|██████▋   | 20138/30196 [41:47<22:53,  7.32it/s]

 67%|██████▋   | 20139/30196 [41:47<24:07,  6.95it/s]

 67%|██████▋   | 20140/30196 [41:48<25:19,  6.62it/s]

 67%|██████▋   | 20141/30196 [41:48<23:12,  7.22it/s]

 67%|██████▋   | 20143/30196 [41:48<20:42,  8.09it/s]

 67%|██████▋   | 20144/30196 [41:48<20:09,  8.31it/s]

 67%|██████▋   | 20145/30196 [41:48<21:04,  7.95it/s]

 67%|██████▋   | 20146/30196 [41:48<21:41,  7.72it/s]

 67%|██████▋   | 20147/30196 [41:48<24:01,  6.97it/s]

 67%|██████▋   | 20148/30196 [41:49<27:42,  6.04it/s]

 67%|██████▋   | 20149/30196 [41:49<26:08,  6.40it/s]

 67%|██████▋   | 20150/30196 [41:49<25:07,  6.67it/s]

 67%|██████▋   | 20151/30196 [41:49<23:10,  7.22it/s]

 67%|██████▋   | 20152/30196 [41:49<23:33,  7.11it/s]

 67%|██████▋   | 20154/30196 [41:49<21:18,  7.85it/s]

 67%|██████▋   | 20156/30196 [41:50<16:49,  9.95it/s]

 67%|██████▋   | 20158/30196 [41:50<16:58,  9.86it/s]

 67%|██████▋   | 20160/30196 [41:50<18:34,  9.01it/s]

 67%|██████▋   | 20161/30196 [41:50<19:09,  8.73it/s]

 67%|██████▋   | 20162/30196 [41:50<18:59,  8.81it/s]

 67%|██████▋   | 20163/30196 [41:50<18:38,  8.97it/s]

 67%|██████▋   | 20164/30196 [41:51<20:56,  7.98it/s]

 67%|██████▋   | 20165/30196 [41:51<54:02,  3.09it/s]

 67%|██████▋   | 20166/30196 [41:52<44:15,  3.78it/s]

 67%|██████▋   | 20168/30196 [41:52<29:10,  5.73it/s]

 67%|██████▋   | 20170/30196 [41:52<27:31,  6.07it/s]

 67%|██████▋   | 20172/30196 [41:52<21:43,  7.69it/s]

 67%|██████▋   | 20174/30196 [41:52<21:15,  7.86it/s]

 67%|██████▋   | 20175/30196 [41:52<22:39,  7.37it/s]

 67%|██████▋   | 20176/30196 [41:53<22:30,  7.42it/s]

 67%|██████▋   | 20178/30196 [41:53<23:04,  7.23it/s]

 67%|██████▋   | 20179/30196 [41:53<26:05,  6.40it/s]

 67%|██████▋   | 20180/30196 [41:53<33:59,  4.91it/s]

 67%|██████▋   | 20182/30196 [41:54<24:14,  6.89it/s]

 67%|██████▋   | 20184/30196 [41:54<22:50,  7.30it/s]

 67%|██████▋   | 20185/30196 [41:54<21:54,  7.62it/s]

 67%|██████▋   | 20187/30196 [41:54<17:33,  9.50it/s]

 67%|██████▋   | 20189/30196 [41:54<18:42,  8.92it/s]

 67%|██████▋   | 20191/30196 [41:55<22:01,  7.57it/s]

 67%|██████▋   | 20193/30196 [41:55<17:50,  9.35it/s]

 67%|██████▋   | 20195/30196 [41:55<15:02, 11.08it/s]

 67%|██████▋   | 20197/30196 [41:55<15:01, 11.10it/s]

 67%|██████▋   | 20199/30196 [41:55<14:35, 11.42it/s]

 67%|██████▋   | 20201/30196 [41:55<16:02, 10.39it/s]

 67%|██████▋   | 20203/30196 [41:56<14:59, 11.11it/s]

 67%|██████▋   | 20205/30196 [41:56<17:41,  9.42it/s]

 67%|██████▋   | 20207/30196 [41:56<20:37,  8.07it/s]

 67%|██████▋   | 20208/30196 [41:56<23:14,  7.16it/s]

 67%|██████▋   | 20210/30196 [41:57<19:13,  8.65it/s]

 67%|██████▋   | 20212/30196 [41:57<19:19,  8.61it/s]

 67%|██████▋   | 20213/30196 [41:57<19:46,  8.42it/s]

 67%|██████▋   | 20214/30196 [41:57<20:21,  8.17it/s]

 67%|██████▋   | 20215/30196 [41:57<21:05,  7.89it/s]

 67%|██████▋   | 20216/30196 [41:57<20:23,  8.16it/s]

 67%|██████▋   | 20217/30196 [41:57<20:37,  8.07it/s]

 67%|██████▋   | 20219/30196 [41:58<15:24, 10.79it/s]

 67%|██████▋   | 20221/30196 [41:58<15:24, 10.79it/s]

 67%|██████▋   | 20223/30196 [41:58<17:58,  9.24it/s]

 67%|██████▋   | 20225/30196 [41:58<19:12,  8.65it/s]

 67%|██████▋   | 20226/30196 [41:58<19:00,  8.74it/s]

 67%|██████▋   | 20227/30196 [41:59<19:36,  8.48it/s]

 67%|██████▋   | 20229/30196 [41:59<19:05,  8.70it/s]

 67%|██████▋   | 20230/30196 [41:59<18:50,  8.82it/s]

 67%|██████▋   | 20232/30196 [41:59<15:56, 10.41it/s]

 67%|██████▋   | 20234/30196 [41:59<15:56, 10.42it/s]

 67%|██████▋   | 20236/30196 [41:59<16:23, 10.13it/s]

 67%|██████▋   | 20238/30196 [42:00<19:04,  8.70it/s]

 67%|██████▋   | 20240/30196 [42:00<18:20,  9.05it/s]

 67%|██████▋   | 20241/30196 [42:00<18:09,  9.14it/s]

 67%|██████▋   | 20242/30196 [42:00<18:10,  9.13it/s]

 67%|██████▋   | 20244/30196 [42:00<19:17,  8.59it/s]

 67%|██████▋   | 20246/30196 [42:01<17:22,  9.55it/s]

 67%|██████▋   | 20248/30196 [42:01<17:47,  9.32it/s]

 67%|██████▋   | 20250/30196 [42:01<15:08, 10.95it/s]

 67%|██████▋   | 20252/30196 [42:01<15:50, 10.46it/s]

 67%|██████▋   | 20254/30196 [42:01<16:22, 10.12it/s]

 67%|██████▋   | 20256/30196 [42:02<20:48,  7.96it/s]

 67%|██████▋   | 20257/30196 [42:02<26:39,  6.22it/s]

 67%|██████▋   | 20258/30196 [42:02<25:58,  6.38it/s]

 67%|██████▋   | 20259/30196 [42:02<26:50,  6.17it/s]

 67%|██████▋   | 20260/30196 [42:02<25:35,  6.47it/s]

 67%|██████▋   | 20262/30196 [42:03<23:49,  6.95it/s]

 67%|██████▋   | 20264/30196 [42:03<21:11,  7.81it/s]

 67%|██████▋   | 20265/30196 [42:03<21:53,  7.56it/s]

 67%|██████▋   | 20266/30196 [42:03<23:43,  6.97it/s]

 67%|██████▋   | 20268/30196 [42:03<20:11,  8.20it/s]

 67%|██████▋   | 20270/30196 [42:04<17:55,  9.23it/s]

 67%|██████▋   | 20271/30196 [42:04<19:54,  8.31it/s]

 67%|██████▋   | 20273/30196 [42:04<17:06,  9.67it/s]

 67%|██████▋   | 20274/30196 [42:04<18:03,  9.15it/s]

 67%|██████▋   | 20276/30196 [42:04<16:20, 10.12it/s]

 67%|██████▋   | 20278/30196 [42:05<21:29,  7.69it/s]

 67%|██████▋   | 20279/30196 [42:05<22:02,  7.50it/s]

 67%|██████▋   | 20280/30196 [42:05<24:41,  6.69it/s]

 67%|██████▋   | 20282/30196 [42:05<20:15,  8.16it/s]

 67%|██████▋   | 20284/30196 [42:05<19:28,  8.48it/s]

 67%|██████▋   | 20286/30196 [42:06<18:46,  8.80it/s]

 67%|██████▋   | 20287/30196 [42:06<22:25,  7.37it/s]

 67%|██████▋   | 20288/30196 [42:06<22:21,  7.38it/s]

 67%|██████▋   | 20290/30196 [42:06<20:52,  7.91it/s]

 67%|██████▋   | 20291/30196 [42:06<22:26,  7.36it/s]

 67%|██████▋   | 20292/30196 [42:06<22:40,  7.28it/s]

 67%|██████▋   | 20294/30196 [42:07<17:13,  9.58it/s]

 67%|██████▋   | 20296/30196 [42:07<18:10,  9.08it/s]

 67%|██████▋   | 20297/30196 [42:07<19:13,  8.58it/s]

 67%|██████▋   | 20298/30196 [42:07<19:44,  8.36it/s]

 67%|██████▋   | 20299/30196 [42:07<20:35,  8.01it/s]

 67%|██████▋   | 20300/30196 [42:07<19:45,  8.35it/s]

 67%|██████▋   | 20301/30196 [42:07<21:57,  7.51it/s]

 67%|██████▋   | 20302/30196 [42:08<22:37,  7.29it/s]

 67%|██████▋   | 20304/30196 [42:08<18:49,  8.76it/s]

 67%|██████▋   | 20305/30196 [42:08<20:52,  7.90it/s]

 67%|██████▋   | 20306/30196 [42:08<24:53,  6.62it/s]

 67%|██████▋   | 20307/30196 [42:08<22:46,  7.23it/s]

 67%|██████▋   | 20309/30196 [42:08<19:10,  8.59it/s]

 67%|██████▋   | 20311/30196 [42:09<15:01, 10.96it/s]

 67%|██████▋   | 20313/30196 [42:09<17:28,  9.43it/s]

 67%|██████▋   | 20315/30196 [42:09<23:43,  6.94it/s]

 67%|██████▋   | 20316/30196 [42:09<24:49,  6.63it/s]

 67%|██████▋   | 20317/30196 [42:10<23:23,  7.04it/s]

 67%|██████▋   | 20318/30196 [42:10<24:35,  6.69it/s]

 67%|██████▋   | 20321/30196 [42:10<17:57,  9.16it/s]

 67%|██████▋   | 20323/30196 [42:10<14:50, 11.09it/s]

 67%|██████▋   | 20325/30196 [42:10<14:46, 11.14it/s]

 67%|██████▋   | 20327/30196 [42:10<18:07,  9.08it/s]

 67%|██████▋   | 20329/30196 [42:11<17:39,  9.31it/s]

 67%|██████▋   | 20331/30196 [42:11<16:55,  9.71it/s]

 67%|██████▋   | 20333/30196 [42:11<17:20,  9.48it/s]

 67%|██████▋   | 20335/30196 [42:11<18:03,  9.10it/s]

 67%|██████▋   | 20337/30196 [42:12<20:59,  7.83it/s]

 67%|██████▋   | 20338/30196 [42:12<21:33,  7.62it/s]

 67%|██████▋   | 20340/30196 [42:12<22:29,  7.30it/s]

 67%|██████▋   | 20341/30196 [42:12<21:36,  7.60it/s]

 67%|██████▋   | 20342/30196 [42:12<21:56,  7.49it/s]

 67%|██████▋   | 20343/30196 [42:12<21:26,  7.66it/s]

 67%|██████▋   | 20344/30196 [42:13<27:10,  6.04it/s]

 67%|██████▋   | 20346/30196 [42:13<22:45,  7.21it/s]

 67%|██████▋   | 20347/30196 [42:13<22:28,  7.30it/s]

 67%|██████▋   | 20349/30196 [42:13<20:58,  7.83it/s]

 67%|██████▋   | 20351/30196 [42:14<20:20,  8.06it/s]

 67%|██████▋   | 20352/30196 [42:14<20:41,  7.93it/s]

 67%|██████▋   | 20353/30196 [42:14<22:28,  7.30it/s]

 67%|██████▋   | 20355/30196 [42:14<16:59,  9.66it/s]

 67%|██████▋   | 20357/30196 [42:14<15:19, 10.70it/s]

 67%|██████▋   | 20359/30196 [42:14<17:51,  9.18it/s]

 67%|██████▋   | 20361/30196 [42:15<15:22, 10.66it/s]

 67%|██████▋   | 20364/30196 [42:15<13:56, 11.76it/s]

 67%|██████▋   | 20366/30196 [42:15<16:02, 10.21it/s]

 67%|██████▋   | 20368/30196 [42:15<17:39,  9.27it/s]

 67%|██████▋   | 20370/30196 [42:16<19:59,  8.19it/s]

 67%|██████▋   | 20371/30196 [42:16<19:29,  8.40it/s]

 67%|██████▋   | 20372/30196 [42:16<19:55,  8.21it/s]

 67%|██████▋   | 20373/30196 [42:16<21:37,  7.57it/s]

 67%|██████▋   | 20375/30196 [42:16<19:10,  8.54it/s]

 67%|██████▋   | 20377/30196 [42:16<20:56,  7.81it/s]

 67%|██████▋   | 20379/30196 [42:17<18:35,  8.80it/s]

 67%|██████▋   | 20380/30196 [42:17<21:42,  7.53it/s]

 67%|██████▋   | 20381/30196 [42:17<28:01,  5.84it/s]

 68%|██████▊   | 20383/30196 [42:17<21:33,  7.58it/s]

 68%|██████▊   | 20385/30196 [42:17<17:47,  9.19it/s]

 68%|██████▊   | 20387/30196 [42:18<14:35, 11.20it/s]

 68%|██████▊   | 20389/30196 [42:18<15:00, 10.89it/s]

 68%|██████▊   | 20391/30196 [42:18<14:46, 11.06it/s]

 68%|██████▊   | 20393/30196 [42:18<14:01, 11.64it/s]

 68%|██████▊   | 20395/30196 [42:18<18:22,  8.89it/s]

 68%|██████▊   | 20397/30196 [42:19<17:29,  9.34it/s]

 68%|██████▊   | 20399/30196 [42:19<16:54,  9.66it/s]

 68%|██████▊   | 20401/30196 [42:19<20:11,  8.08it/s]

 68%|██████▊   | 20403/30196 [42:19<17:41,  9.23it/s]

 68%|██████▊   | 20405/30196 [42:20<19:27,  8.38it/s]

 68%|██████▊   | 20406/30196 [42:20<20:55,  7.80it/s]

 68%|██████▊   | 20408/30196 [42:20<20:59,  7.77it/s]

 68%|██████▊   | 20410/30196 [42:20<20:05,  8.12it/s]

 68%|██████▊   | 20411/30196 [42:20<19:41,  8.28it/s]

 68%|██████▊   | 20412/30196 [42:20<21:20,  7.64it/s]

 68%|██████▊   | 20413/30196 [42:21<25:50,  6.31it/s]

 68%|██████▊   | 20414/30196 [42:21<23:53,  6.83it/s]

 68%|██████▊   | 20415/30196 [42:21<23:37,  6.90it/s]

 68%|██████▊   | 20416/30196 [42:21<23:25,  6.96it/s]

 68%|██████▊   | 20417/30196 [42:21<21:50,  7.46it/s]

 68%|██████▊   | 20419/30196 [42:21<15:53, 10.26it/s]

 68%|██████▊   | 20421/30196 [42:22<16:27,  9.90it/s]

 68%|██████▊   | 20424/30196 [42:22<13:17, 12.26it/s]

 68%|██████▊   | 20426/30196 [42:22<17:34,  9.27it/s]

 68%|██████▊   | 20428/30196 [42:22<17:44,  9.18it/s]

 68%|██████▊   | 20430/30196 [42:23<18:33,  8.77it/s]

 68%|██████▊   | 20431/30196 [42:23<21:34,  7.55it/s]

 68%|██████▊   | 20432/30196 [42:23<20:48,  7.82it/s]

 68%|██████▊   | 20433/30196 [42:23<21:16,  7.65it/s]

 68%|██████▊   | 20434/30196 [42:23<20:16,  8.03it/s]

 68%|██████▊   | 20436/30196 [42:23<16:46,  9.70it/s]

 68%|██████▊   | 20438/30196 [42:24<18:36,  8.74it/s]

 68%|██████▊   | 20440/30196 [42:24<16:43,  9.72it/s]

 68%|██████▊   | 20442/30196 [42:24<19:05,  8.51it/s]

 68%|██████▊   | 20445/30196 [42:24<14:31, 11.19it/s]

 68%|██████▊   | 20447/30196 [42:24<14:28, 11.22it/s]

 68%|██████▊   | 20449/30196 [42:25<18:08,  8.95it/s]

 68%|██████▊   | 20451/30196 [42:25<18:52,  8.61it/s]

 68%|██████▊   | 20452/30196 [42:25<20:14,  8.02it/s]

 68%|██████▊   | 20453/30196 [42:25<19:38,  8.27it/s]

 68%|██████▊   | 20455/30196 [42:25<18:08,  8.95it/s]

 68%|██████▊   | 20456/30196 [42:26<18:54,  8.59it/s]

 68%|██████▊   | 20457/30196 [42:26<19:46,  8.21it/s]

 68%|██████▊   | 20459/30196 [42:26<16:09, 10.04it/s]

 68%|██████▊   | 20461/30196 [42:26<17:12,  9.43it/s]

 68%|██████▊   | 20462/30196 [42:26<19:12,  8.45it/s]

 68%|██████▊   | 20463/30196 [42:26<21:27,  7.56it/s]

 68%|██████▊   | 20464/30196 [42:27<22:05,  7.34it/s]

 68%|██████▊   | 20466/30196 [42:27<18:26,  8.80it/s]

 68%|██████▊   | 20467/30196 [42:27<19:38,  8.25it/s]

 68%|██████▊   | 20468/30196 [42:27<20:08,  8.05it/s]

 68%|██████▊   | 20469/30196 [42:27<21:54,  7.40it/s]

 68%|██████▊   | 20471/30196 [42:27<19:38,  8.25it/s]

 68%|██████▊   | 20472/30196 [42:28<22:52,  7.08it/s]

 68%|██████▊   | 20473/30196 [42:28<26:07,  6.20it/s]

 68%|██████▊   | 20474/30196 [42:28<24:56,  6.50it/s]

 68%|██████▊   | 20475/30196 [42:28<30:05,  5.38it/s]

 68%|██████▊   | 20476/30196 [42:28<28:21,  5.71it/s]

 68%|██████▊   | 20478/30196 [42:29<26:06,  6.20it/s]

 68%|██████▊   | 20479/30196 [42:29<24:06,  6.72it/s]

 68%|██████▊   | 20481/30196 [42:29<19:15,  8.41it/s]

 68%|██████▊   | 20483/30196 [42:29<15:42, 10.31it/s]

 68%|██████▊   | 20485/30196 [42:29<16:17,  9.93it/s]

 68%|██████▊   | 20488/30196 [42:29<12:32, 12.91it/s]

 68%|██████▊   | 20490/30196 [42:30<13:45, 11.76it/s]

 68%|██████▊   | 20492/30196 [42:30<20:31,  7.88it/s]

 68%|██████▊   | 20494/30196 [42:30<19:57,  8.10it/s]

 68%|██████▊   | 20495/30196 [42:30<19:26,  8.32it/s]

 68%|██████▊   | 20496/30196 [42:30<19:45,  8.18it/s]

 68%|██████▊   | 20497/30196 [42:31<26:25,  6.12it/s]

 68%|██████▊   | 20498/30196 [42:31<25:31,  6.33it/s]

 68%|██████▊   | 20500/30196 [42:31<21:55,  7.37it/s]

 68%|██████▊   | 20502/30196 [42:31<18:46,  8.61it/s]

 68%|██████▊   | 20503/30196 [42:32<29:30,  5.47it/s]

 68%|██████▊   | 20504/30196 [42:32<30:24,  5.31it/s]

 68%|██████▊   | 20506/30196 [42:32<34:11,  4.72it/s]

 68%|██████▊   | 20508/30196 [42:33<28:14,  5.72it/s]

 68%|██████▊   | 20510/30196 [42:33<21:56,  7.36it/s]

 68%|██████▊   | 20511/30196 [42:33<21:06,  7.65it/s]

 68%|██████▊   | 20512/30196 [42:33<20:11,  8.00it/s]

 68%|██████▊   | 20514/30196 [42:33<16:13,  9.95it/s]

 68%|██████▊   | 20516/30196 [42:33<17:08,  9.42it/s]

 68%|██████▊   | 20518/30196 [42:34<16:42,  9.65it/s]

 68%|██████▊   | 20520/30196 [42:34<18:21,  8.79it/s]

 68%|██████▊   | 20522/30196 [42:34<15:57, 10.11it/s]

 68%|██████▊   | 20524/30196 [42:34<16:20,  9.86it/s]

 68%|██████▊   | 20526/30196 [42:35<24:24,  6.60it/s]

 68%|██████▊   | 20528/30196 [42:35<20:40,  7.79it/s]

 68%|██████▊   | 20529/30196 [42:35<21:44,  7.41it/s]

 68%|██████▊   | 20530/30196 [42:35<22:42,  7.10it/s]

 68%|██████▊   | 20532/30196 [42:35<20:12,  7.97it/s]

 68%|██████▊   | 20534/30196 [42:36<17:48,  9.04it/s]

 68%|██████▊   | 20535/30196 [42:36<18:57,  8.49it/s]

 68%|██████▊   | 20536/30196 [42:36<19:47,  8.13it/s]

 68%|██████▊   | 20537/30196 [42:36<19:18,  8.34it/s]

 68%|██████▊   | 20538/30196 [42:36<18:51,  8.54it/s]

 68%|██████▊   | 20540/30196 [42:36<18:24,  8.74it/s]

 68%|██████▊   | 20541/30196 [42:36<19:00,  8.47it/s]

 68%|██████▊   | 20542/30196 [42:37<25:45,  6.25it/s]

 68%|██████▊   | 20544/30196 [42:37<28:31,  5.64it/s]

 68%|██████▊   | 20546/30196 [42:37<23:46,  6.76it/s]

 68%|██████▊   | 20548/30196 [42:37<19:58,  8.05it/s]

 68%|██████▊   | 20550/30196 [42:38<17:12,  9.34it/s]

 68%|██████▊   | 20552/30196 [42:38<16:28,  9.76it/s]

 68%|██████▊   | 20554/30196 [42:38<16:54,  9.50it/s]

 68%|██████▊   | 20556/30196 [42:38<19:23,  8.29it/s]

 68%|██████▊   | 20557/30196 [42:38<20:47,  7.73it/s]

 68%|██████▊   | 20559/30196 [42:39<21:57,  7.31it/s]

 68%|██████▊   | 20560/30196 [42:39<23:08,  6.94it/s]

 68%|██████▊   | 20562/30196 [42:39<21:49,  7.36it/s]

 68%|██████▊   | 20564/30196 [42:39<19:51,  8.09it/s]

 68%|██████▊   | 20565/30196 [42:40<23:51,  6.73it/s]

 68%|██████▊   | 20566/30196 [42:40<22:28,  7.14it/s]

 68%|██████▊   | 20568/30196 [42:40<17:54,  8.96it/s]

 68%|██████▊   | 20569/30196 [42:40<18:34,  8.64it/s]

 68%|██████▊   | 20570/30196 [42:40<20:05,  7.98it/s]

 68%|██████▊   | 20572/30196 [42:40<18:14,  8.79it/s]

 68%|██████▊   | 20573/30196 [42:41<20:15,  7.92it/s]

 68%|██████▊   | 20574/30196 [42:41<26:30,  6.05it/s]

 68%|██████▊   | 20575/30196 [42:41<25:15,  6.35it/s]

 68%|██████▊   | 20576/30196 [42:41<22:58,  6.98it/s]

 68%|██████▊   | 20579/30196 [42:41<17:13,  9.30it/s]

 68%|██████▊   | 20580/30196 [42:41<17:58,  8.92it/s]

 68%|██████▊   | 20581/30196 [42:42<21:37,  7.41it/s]

 68%|██████▊   | 20582/30196 [42:42<21:50,  7.34it/s]

 68%|██████▊   | 20583/30196 [42:42<23:20,  6.86it/s]

 68%|██████▊   | 20585/30196 [42:42<19:00,  8.43it/s]

 68%|██████▊   | 20586/30196 [42:42<22:31,  7.11it/s]

 68%|██████▊   | 20587/30196 [42:43<27:13,  5.88it/s]

 68%|██████▊   | 20588/30196 [42:43<24:31,  6.53it/s]

 68%|██████▊   | 20589/30196 [42:43<26:48,  5.97it/s]

 68%|██████▊   | 20590/30196 [42:43<28:30,  5.61it/s]

 68%|██████▊   | 20591/30196 [42:43<25:16,  6.33it/s]

 68%|██████▊   | 20593/30196 [42:43<20:59,  7.63it/s]

 68%|██████▊   | 20594/30196 [42:44<21:06,  7.58it/s]

 68%|██████▊   | 20596/30196 [42:44<16:37,  9.62it/s]

 68%|██████▊   | 20598/30196 [42:44<20:03,  7.98it/s]

 68%|██████▊   | 20599/30196 [42:44<21:42,  7.37it/s]

 68%|██████▊   | 20600/30196 [42:44<21:41,  7.37it/s]

 68%|██████▊   | 20601/30196 [42:44<22:09,  7.21it/s]

 68%|██████▊   | 20603/30196 [42:45<22:45,  7.03it/s]

 68%|██████▊   | 20605/30196 [42:45<18:47,  8.50it/s]

 68%|██████▊   | 20607/30196 [42:45<17:38,  9.06it/s]

 68%|██████▊   | 20608/30196 [42:45<20:51,  7.66it/s]

 68%|██████▊   | 20610/30196 [42:46<22:32,  7.09it/s]

 68%|██████▊   | 20612/30196 [42:46<19:40,  8.12it/s]

 68%|██████▊   | 20613/30196 [42:46<27:21,  5.84it/s]

 68%|██████▊   | 20615/30196 [42:46<23:28,  6.80it/s]

 68%|██████▊   | 20616/30196 [42:47<24:29,  6.52it/s]

 68%|██████▊   | 20618/30196 [42:47<18:51,  8.46it/s]

 68%|██████▊   | 20620/30196 [42:47<21:26,  7.45it/s]

 68%|██████▊   | 20622/30196 [42:47<20:08,  7.92it/s]

 68%|██████▊   | 20623/30196 [42:47<20:25,  7.81it/s]

 68%|██████▊   | 20624/30196 [42:47<21:51,  7.30it/s]

 68%|██████▊   | 20626/30196 [42:48<20:12,  7.89it/s]

 68%|██████▊   | 20627/30196 [42:48<19:38,  8.12it/s]

 68%|██████▊   | 20629/30196 [42:48<16:08,  9.88it/s]

 68%|██████▊   | 20631/30196 [42:48<17:33,  9.08it/s]

 68%|██████▊   | 20633/30196 [42:48<14:50, 10.74it/s]

 68%|██████▊   | 20635/30196 [42:49<23:38,  6.74it/s]

 68%|██████▊   | 20636/30196 [42:49<25:26,  6.26it/s]

 68%|██████▊   | 20637/30196 [42:49<24:36,  6.47it/s]

 68%|██████▊   | 20638/30196 [42:50<31:14,  5.10it/s]

 68%|██████▊   | 20639/30196 [42:50<30:28,  5.23it/s]

 68%|██████▊   | 20640/30196 [42:50<36:35,  4.35it/s]

 68%|██████▊   | 20642/30196 [42:50<27:39,  5.76it/s]

 68%|██████▊   | 20643/30196 [42:50<26:02,  6.11it/s]

 68%|██████▊   | 20645/30196 [42:51<22:39,  7.02it/s]

 68%|██████▊   | 20646/30196 [42:51<22:29,  7.08it/s]

 68%|██████▊   | 20648/30196 [42:51<18:35,  8.56it/s]

 68%|██████▊   | 20650/30196 [42:51<18:54,  8.42it/s]

 68%|██████▊   | 20652/30196 [42:51<18:24,  8.64it/s]

 68%|██████▊   | 20653/30196 [42:51<19:01,  8.36it/s]

 68%|██████▊   | 20654/30196 [42:52<18:41,  8.51it/s]

 68%|██████▊   | 20656/30196 [42:52<17:26,  9.12it/s]

 68%|██████▊   | 20658/30196 [42:52<15:06, 10.52it/s]

 68%|██████▊   | 20660/30196 [42:52<15:45, 10.08it/s]

 68%|██████▊   | 20662/30196 [42:52<15:25, 10.30it/s]

 68%|██████▊   | 20664/30196 [42:53<17:15,  9.20it/s]

 68%|██████▊   | 20665/30196 [42:53<17:54,  8.87it/s]

 68%|██████▊   | 20667/30196 [42:53<15:39, 10.14it/s]

 68%|██████▊   | 20669/30196 [42:54<27:41,  5.73it/s]

 68%|██████▊   | 20670/30196 [42:54<28:50,  5.51it/s]

 68%|██████▊   | 20671/30196 [42:54<26:25,  6.01it/s]

 68%|██████▊   | 20672/30196 [42:54<35:58,  4.41it/s]

 68%|██████▊   | 20673/30196 [42:54<33:41,  4.71it/s]

 68%|██████▊   | 20674/30196 [42:55<29:25,  5.39it/s]

 68%|██████▊   | 20676/30196 [42:55<28:09,  5.63it/s]

 68%|██████▊   | 20677/30196 [42:55<26:26,  6.00it/s]

 68%|██████▊   | 20678/30196 [42:55<25:11,  6.30it/s]

 68%|██████▊   | 20679/30196 [42:55<23:07,  6.86it/s]

 68%|██████▊   | 20680/30196 [42:55<21:32,  7.36it/s]

 68%|██████▊   | 20681/30196 [42:56<23:00,  6.89it/s]

 68%|██████▊   | 20683/30196 [42:56<23:25,  6.77it/s]

 68%|██████▊   | 20684/30196 [42:56<21:47,  7.28it/s]

 69%|██████▊   | 20686/30196 [42:56<18:39,  8.50it/s]

 69%|██████▊   | 20688/30196 [42:56<15:36, 10.15it/s]

 69%|██████▊   | 20690/30196 [42:56<16:25,  9.64it/s]

 69%|██████▊   | 20692/30196 [42:57<20:30,  7.72it/s]

 69%|██████▊   | 20693/30196 [42:57<22:50,  6.94it/s]

 69%|██████▊   | 20695/30196 [42:57<25:03,  6.32it/s]

 69%|██████▊   | 20696/30196 [42:58<24:18,  6.51it/s]

 69%|██████▊   | 20697/30196 [42:58<24:55,  6.35it/s]

 69%|██████▊   | 20698/30196 [42:58<27:19,  5.79it/s]

 69%|██████▊   | 20700/30196 [42:58<24:59,  6.33it/s]

 69%|██████▊   | 20701/30196 [42:58<23:05,  6.86it/s]

 69%|██████▊   | 20703/30196 [42:58<18:59,  8.33it/s]

 69%|██████▊   | 20704/30196 [42:59<18:27,  8.57it/s]

 69%|██████▊   | 20705/30196 [42:59<21:48,  7.26it/s]

 69%|██████▊   | 20707/30196 [42:59<17:09,  9.22it/s]

 69%|██████▊   | 20709/30196 [43:00<36:16,  4.36it/s]

 69%|██████▊   | 20711/30196 [43:00<28:16,  5.59it/s]

 69%|██████▊   | 20713/30196 [43:01<33:22,  4.73it/s]

 69%|██████▊   | 20714/30196 [43:01<31:26,  5.03it/s]

 69%|██████▊   | 20715/30196 [43:01<30:27,  5.19it/s]

 69%|██████▊   | 20716/30196 [43:01<27:13,  5.80it/s]

 69%|██████▊   | 20718/30196 [43:01<21:56,  7.20it/s]

 69%|██████▊   | 20720/30196 [43:01<20:43,  7.62it/s]

 69%|██████▊   | 20721/30196 [43:02<22:09,  7.13it/s]

 69%|██████▊   | 20722/30196 [43:02<21:58,  7.18it/s]

 69%|██████▊   | 20723/30196 [43:02<36:09,  4.37it/s]

 69%|██████▊   | 20724/30196 [43:02<32:25,  4.87it/s]

 69%|██████▊   | 20726/30196 [43:02<23:59,  6.58it/s]

 69%|██████▊   | 20727/30196 [43:03<24:28,  6.45it/s]

 69%|██████▊   | 20728/30196 [43:03<24:52,  6.35it/s]

 69%|██████▊   | 20730/30196 [43:03<21:52,  7.21it/s]

 69%|██████▊   | 20732/30196 [43:03<18:58,  8.31it/s]

 69%|██████▊   | 20735/30196 [43:03<15:04, 10.46it/s]

 69%|██████▊   | 20737/30196 [43:04<19:15,  8.18it/s]

 69%|██████▊   | 20739/30196 [43:04<18:15,  8.63it/s]

 69%|██████▊   | 20741/30196 [43:04<17:28,  9.02it/s]

 69%|██████▊   | 20743/30196 [43:04<16:25,  9.59it/s]

 69%|██████▊   | 20745/30196 [43:05<15:53,  9.91it/s]

 69%|██████▊   | 20747/30196 [43:05<16:18,  9.65it/s]

 69%|██████▊   | 20748/30196 [43:05<16:21,  9.63it/s]

 69%|██████▊   | 20750/30196 [43:05<18:10,  8.66it/s]

 69%|██████▊   | 20752/30196 [43:05<15:40, 10.04it/s]

 69%|██████▊   | 20754/30196 [43:06<16:59,  9.26it/s]

 69%|██████▊   | 20755/30196 [43:06<21:13,  7.41it/s]

 69%|██████▊   | 20756/30196 [43:06<22:14,  7.07it/s]

 69%|██████▊   | 20757/30196 [43:06<21:06,  7.46it/s]

 69%|██████▊   | 20758/30196 [43:06<22:17,  7.05it/s]

 69%|██████▉   | 20760/30196 [43:06<18:02,  8.72it/s]

 69%|██████▉   | 20761/30196 [43:07<18:47,  8.37it/s]

 69%|██████▉   | 20764/30196 [43:07<13:11, 11.92it/s]

 69%|██████▉   | 20766/30196 [43:07<12:40, 12.41it/s]

 69%|██████▉   | 20768/30196 [43:07<12:44, 12.33it/s]

 69%|██████▉   | 20770/30196 [43:07<14:57, 10.50it/s]

 69%|██████▉   | 20772/30196 [43:07<16:34,  9.48it/s]

 69%|██████▉   | 20774/30196 [43:08<17:39,  8.89it/s]

 69%|██████▉   | 20775/30196 [43:08<19:30,  8.05it/s]

 69%|██████▉   | 20777/30196 [43:08<16:43,  9.39it/s]

 69%|██████▉   | 20779/30196 [43:08<15:48,  9.93it/s]

 69%|██████▉   | 20781/30196 [43:09<21:04,  7.45it/s]

 69%|██████▉   | 20783/30196 [43:09<19:50,  7.91it/s]

 69%|██████▉   | 20784/30196 [43:09<21:09,  7.41it/s]

 69%|██████▉   | 20786/30196 [43:09<16:52,  9.30it/s]

 69%|██████▉   | 20788/30196 [43:09<19:01,  8.24it/s]

 69%|██████▉   | 20789/30196 [43:10<20:04,  7.81it/s]

 69%|██████▉   | 20790/30196 [43:10<19:18,  8.12it/s]

 69%|██████▉   | 20792/30196 [43:10<15:25, 10.16it/s]

 69%|██████▉   | 20794/30196 [43:10<16:20,  9.59it/s]

 69%|██████▉   | 20796/30196 [43:10<21:07,  7.41it/s]

 69%|██████▉   | 20798/30196 [43:11<18:39,  8.39it/s]

 69%|██████▉   | 20800/30196 [43:11<17:59,  8.71it/s]

 69%|██████▉   | 20801/30196 [43:11<21:11,  7.39it/s]

 69%|██████▉   | 20802/30196 [43:11<21:21,  7.33it/s]

 69%|██████▉   | 20803/30196 [43:11<22:40,  6.91it/s]

 69%|██████▉   | 20804/30196 [43:12<29:13,  5.35it/s]

 69%|██████▉   | 20805/30196 [43:12<30:04,  5.20it/s]

 69%|██████▉   | 20806/30196 [43:12<28:12,  5.55it/s]

 69%|██████▉   | 20807/30196 [43:12<27:53,  5.61it/s]

 69%|██████▉   | 20808/30196 [43:12<27:23,  5.71it/s]

 69%|██████▉   | 20809/30196 [43:13<25:31,  6.13it/s]

 69%|██████▉   | 20811/30196 [43:13<21:29,  7.28it/s]

 69%|██████▉   | 20812/30196 [43:13<25:23,  6.16it/s]

 69%|██████▉   | 20813/30196 [43:13<24:08,  6.48it/s]

 69%|██████▉   | 20814/30196 [43:13<22:16,  7.02it/s]

 69%|██████▉   | 20816/30196 [43:13<17:37,  8.87it/s]

 69%|██████▉   | 20817/30196 [43:14<21:03,  7.42it/s]

 69%|██████▉   | 20818/30196 [43:14<22:27,  6.96it/s]

 69%|██████▉   | 20819/30196 [43:14<22:21,  6.99it/s]

 69%|██████▉   | 20820/30196 [43:14<23:45,  6.58it/s]

 69%|██████▉   | 20821/30196 [43:14<31:41,  4.93it/s]

 69%|██████▉   | 20823/30196 [43:15<27:57,  5.59it/s]

 69%|██████▉   | 20824/30196 [43:15<27:50,  5.61it/s]

 69%|██████▉   | 20826/30196 [43:15<25:21,  6.16it/s]

 69%|██████▉   | 20828/30196 [43:15<20:36,  7.58it/s]

 69%|██████▉   | 20829/30196 [43:15<20:59,  7.44it/s]

 69%|██████▉   | 20830/30196 [43:16<19:54,  7.84it/s]

 69%|██████▉   | 20832/30196 [43:16<19:15,  8.10it/s]

 69%|██████▉   | 20833/30196 [43:16<19:28,  8.01it/s]

 69%|██████▉   | 20834/30196 [43:16<19:41,  7.92it/s]

 69%|██████▉   | 20836/30196 [43:16<15:55,  9.79it/s]

 69%|██████▉   | 20838/30196 [43:16<15:23, 10.13it/s]

 69%|██████▉   | 20840/30196 [43:17<25:16,  6.17it/s]

 69%|██████▉   | 20842/30196 [43:17<19:52,  7.85it/s]

 69%|██████▉   | 20844/30196 [43:17<18:28,  8.44it/s]

 69%|██████▉   | 20846/30196 [43:18<25:16,  6.16it/s]

 69%|██████▉   | 20847/30196 [43:18<24:05,  6.47it/s]

 69%|██████▉   | 20848/30196 [43:18<26:10,  5.95it/s]

 69%|██████▉   | 20850/30196 [43:18<20:54,  7.45it/s]

 69%|██████▉   | 20851/30196 [43:18<20:48,  7.49it/s]

 69%|██████▉   | 20853/30196 [43:19<18:57,  8.21it/s]

 69%|██████▉   | 20854/30196 [43:19<20:23,  7.64it/s]

 69%|██████▉   | 20857/30196 [43:19<15:48,  9.85it/s]

 69%|██████▉   | 20859/30196 [43:19<16:43,  9.31it/s]

 69%|██████▉   | 20861/30196 [43:19<15:01, 10.36it/s]

 69%|██████▉   | 20863/30196 [43:20<15:26, 10.07it/s]

 69%|██████▉   | 20865/30196 [43:20<16:42,  9.31it/s]

 69%|██████▉   | 20866/30196 [43:20<16:46,  9.27it/s]

 69%|██████▉   | 20867/30196 [43:20<21:26,  7.25it/s]

 69%|██████▉   | 20869/30196 [43:20<16:35,  9.37it/s]

 69%|██████▉   | 20871/30196 [43:20<13:40, 11.37it/s]

 69%|██████▉   | 20873/30196 [43:21<14:45, 10.52it/s]

 69%|██████▉   | 20875/30196 [43:21<15:57,  9.73it/s]

 69%|██████▉   | 20877/30196 [43:21<16:54,  9.18it/s]

 69%|██████▉   | 20879/30196 [43:21<19:10,  8.10it/s]

 69%|██████▉   | 20881/30196 [43:22<16:54,  9.19it/s]

 69%|██████▉   | 20883/30196 [43:22<18:12,  8.53it/s]

 69%|██████▉   | 20884/30196 [43:22<18:56,  8.19it/s]

 69%|██████▉   | 20886/30196 [43:22<18:06,  8.57it/s]

 69%|██████▉   | 20887/30196 [43:22<18:37,  8.33it/s]

 69%|██████▉   | 20888/30196 [43:22<18:05,  8.57it/s]

 69%|██████▉   | 20890/30196 [43:23<18:21,  8.45it/s]

 69%|██████▉   | 20892/30196 [43:23<16:42,  9.28it/s]

 69%|██████▉   | 20894/30196 [43:23<17:35,  8.81it/s]

 69%|██████▉   | 20895/30196 [43:23<18:06,  8.56it/s]

 69%|██████▉   | 20897/30196 [43:23<14:51, 10.44it/s]

 69%|██████▉   | 20899/30196 [43:24<18:04,  8.57it/s]

 69%|██████▉   | 20901/30196 [43:24<16:18,  9.50it/s]

 69%|██████▉   | 20903/30196 [43:24<17:24,  8.90it/s]

 69%|██████▉   | 20905/30196 [43:24<15:55,  9.72it/s]

 69%|██████▉   | 20907/30196 [43:24<14:13, 10.88it/s]

 69%|██████▉   | 20909/30196 [43:24<13:25, 11.53it/s]

 69%|██████▉   | 20911/30196 [43:25<13:14, 11.68it/s]

 69%|██████▉   | 20913/30196 [43:25<12:16, 12.60it/s]

 69%|██████▉   | 20915/30196 [43:25<11:45, 13.16it/s]

 69%|██████▉   | 20917/30196 [43:25<21:10,  7.30it/s]

 69%|██████▉   | 20919/30196 [43:26<21:17,  7.26it/s]

 69%|██████▉   | 20920/30196 [43:26<22:15,  6.94it/s]

 69%|██████▉   | 20921/30196 [43:26<22:09,  6.98it/s]

 69%|██████▉   | 20922/30196 [43:26<22:02,  7.01it/s]

 69%|██████▉   | 20924/30196 [43:26<20:57,  7.37it/s]

 69%|██████▉   | 20926/30196 [43:27<17:42,  8.72it/s]

 69%|██████▉   | 20928/30196 [43:27<16:00,  9.64it/s]

 69%|██████▉   | 20930/30196 [43:27<18:43,  8.25it/s]

 69%|██████▉   | 20931/30196 [43:27<20:06,  7.68it/s]

 69%|██████▉   | 20933/30196 [43:27<15:59,  9.65it/s]

 69%|██████▉   | 20935/30196 [43:28<16:23,  9.42it/s]

 69%|██████▉   | 20937/30196 [43:28<17:05,  9.03it/s]

 69%|██████▉   | 20939/30196 [43:28<17:00,  9.07it/s]

 69%|██████▉   | 20940/30196 [43:28<18:46,  8.22it/s]

 69%|██████▉   | 20941/30196 [43:28<18:14,  8.45it/s]

 69%|██████▉   | 20943/30196 [43:28<15:45,  9.79it/s]

 69%|██████▉   | 20945/30196 [43:29<24:24,  6.32it/s]

 69%|██████▉   | 20947/30196 [43:29<20:22,  7.56it/s]

 69%|██████▉   | 20948/30196 [43:29<19:44,  7.81it/s]

 69%|██████▉   | 20950/30196 [43:29<17:10,  8.98it/s]

 69%|██████▉   | 20952/30196 [43:30<14:51, 10.37it/s]

 69%|██████▉   | 20954/30196 [43:30<14:31, 10.61it/s]

 69%|██████▉   | 20956/30196 [43:30<16:09,  9.53it/s]

 69%|██████▉   | 20958/30196 [43:30<17:12,  8.95it/s]

 69%|██████▉   | 20959/30196 [43:30<17:09,  8.97it/s]

 69%|██████▉   | 20961/30196 [43:31<15:55,  9.67it/s]

 69%|██████▉   | 20963/30196 [43:31<17:34,  8.75it/s]

 69%|██████▉   | 20964/30196 [43:31<17:27,  8.82it/s]

 69%|██████▉   | 20966/30196 [43:31<15:32,  9.90it/s]

 69%|██████▉   | 20968/30196 [43:31<14:47, 10.40it/s]

 69%|██████▉   | 20970/30196 [43:31<13:18, 11.56it/s]

 69%|██████▉   | 20973/30196 [43:32<12:49, 11.99it/s]

 69%|██████▉   | 20975/30196 [43:32<11:42, 13.13it/s]

 69%|██████▉   | 20977/30196 [43:32<14:38, 10.50it/s]

 69%|██████▉   | 20979/30196 [43:32<14:30, 10.59it/s]

 69%|██████▉   | 20981/30196 [43:32<14:12, 10.81it/s]

 69%|██████▉   | 20983/30196 [43:33<15:50,  9.69it/s]

 69%|██████▉   | 20985/30196 [43:33<19:10,  8.00it/s]

 69%|██████▉   | 20986/30196 [43:34<42:07,  3.64it/s]

 70%|██████▉   | 20987/30196 [43:34<37:07,  4.14it/s]

 70%|██████▉   | 20988/30196 [43:34<33:40,  4.56it/s]

 70%|██████▉   | 20989/30196 [43:34<29:28,  5.21it/s]

 70%|██████▉   | 20990/30196 [43:35<28:38,  5.36it/s]

 70%|██████▉   | 20991/30196 [43:35<29:24,  5.22it/s]

 70%|██████▉   | 20992/30196 [43:35<34:29,  4.45it/s]

 70%|██████▉   | 20993/30196 [43:35<29:30,  5.20it/s]

 70%|██████▉   | 20995/30196 [43:35<21:24,  7.16it/s]

 70%|██████▉   | 20996/30196 [43:35<20:15,  7.57it/s]

 70%|██████▉   | 20997/30196 [43:36<25:26,  6.02it/s]

 70%|██████▉   | 20998/30196 [43:36<25:28,  6.02it/s]

 70%|██████▉   | 20999/30196 [43:36<29:07,  5.26it/s]

 70%|██████▉   | 21001/30196 [43:36<23:33,  6.50it/s]

 70%|██████▉   | 21002/30196 [43:36<21:54,  6.99it/s]

 70%|██████▉   | 21004/30196 [43:37<17:14,  8.89it/s]

 70%|██████▉   | 21005/30196 [43:37<19:12,  7.97it/s]

 70%|██████▉   | 21006/30196 [43:37<19:25,  7.89it/s]

 70%|██████▉   | 21007/30196 [43:37<18:45,  8.17it/s]

 70%|██████▉   | 21009/30196 [43:37<25:18,  6.05it/s]

 70%|██████▉   | 21010/30196 [43:38<24:13,  6.32it/s]

 70%|██████▉   | 21011/30196 [43:38<26:33,  5.76it/s]

 70%|██████▉   | 21013/30196 [43:38<19:52,  7.70it/s]

 70%|██████▉   | 21014/30196 [43:38<20:01,  7.64it/s]

 70%|██████▉   | 21015/30196 [43:38<20:39,  7.41it/s]

 70%|██████▉   | 21017/30196 [43:38<16:15,  9.41it/s]

 70%|██████▉   | 21019/30196 [43:38<15:19,  9.98it/s]

 70%|██████▉   | 21021/30196 [43:39<16:29,  9.27it/s]

 70%|██████▉   | 21022/30196 [43:39<17:28,  8.75it/s]

 70%|██████▉   | 21024/30196 [43:39<15:09, 10.08it/s]

 70%|██████▉   | 21026/30196 [43:39<14:13, 10.75it/s]

 70%|██████▉   | 21028/30196 [43:39<15:27,  9.88it/s]

 70%|██████▉   | 21030/30196 [43:40<19:23,  7.88it/s]

 70%|██████▉   | 21031/30196 [43:40<19:36,  7.79it/s]

 70%|██████▉   | 21033/30196 [43:40<17:55,  8.52it/s]

 70%|██████▉   | 21034/30196 [43:40<18:19,  8.33it/s]

 70%|██████▉   | 21035/30196 [43:40<21:12,  7.20it/s]

 70%|██████▉   | 21036/30196 [43:41<20:08,  7.58it/s]

 70%|██████▉   | 21037/30196 [43:41<24:45,  6.17it/s]

 70%|██████▉   | 21038/30196 [43:41<23:28,  6.50it/s]

 70%|██████▉   | 21039/30196 [43:41<23:13,  6.57it/s]

 70%|██████▉   | 21040/30196 [43:41<26:37,  5.73it/s]

 70%|██████▉   | 21041/30196 [43:41<26:49,  5.69it/s]

 70%|██████▉   | 21043/30196 [43:42<18:30,  8.24it/s]

 70%|██████▉   | 21044/30196 [43:42<19:01,  8.02it/s]

 70%|██████▉   | 21045/30196 [43:42<26:01,  5.86it/s]

 70%|██████▉   | 21047/30196 [43:42<20:56,  7.28it/s]

 70%|██████▉   | 21049/30196 [43:42<18:37,  8.19it/s]

 70%|██████▉   | 21050/30196 [43:43<23:57,  6.36it/s]

 70%|██████▉   | 21051/30196 [43:43<24:33,  6.21it/s]

 70%|██████▉   | 21052/30196 [43:43<23:26,  6.50it/s]

 70%|██████▉   | 21053/30196 [43:43<23:08,  6.59it/s]

 70%|██████▉   | 21054/30196 [43:43<22:19,  6.82it/s]

 70%|██████▉   | 21056/30196 [43:44<21:22,  7.13it/s]

 70%|██████▉   | 21057/30196 [43:44<20:17,  7.51it/s]

 70%|██████▉   | 21059/30196 [43:44<20:13,  7.53it/s]

 70%|██████▉   | 21060/30196 [43:44<19:16,  7.90it/s]

 70%|██████▉   | 21062/30196 [43:44<19:19,  7.88it/s]

 70%|██████▉   | 21063/30196 [43:44<19:31,  7.79it/s]

 70%|██████▉   | 21065/30196 [43:45<19:29,  7.81it/s]

 70%|██████▉   | 21067/30196 [43:45<16:10,  9.41it/s]

 70%|██████▉   | 21069/30196 [43:46<35:40,  4.26it/s]

 70%|██████▉   | 21070/30196 [43:46<31:59,  4.76it/s]

 70%|██████▉   | 21072/30196 [43:46<26:59,  5.63it/s]

 70%|██████▉   | 21073/30196 [43:46<26:37,  5.71it/s]

 70%|██████▉   | 21074/30196 [43:46<24:21,  6.24it/s]

 70%|██████▉   | 21075/30196 [43:47<26:14,  5.79it/s]

 70%|██████▉   | 21077/30196 [43:47<22:24,  6.78it/s]

 70%|██████▉   | 21078/30196 [43:47<22:09,  6.86it/s]

 70%|██████▉   | 21079/30196 [43:47<21:45,  6.98it/s]

 70%|██████▉   | 21081/30196 [43:48<34:41,  4.38it/s]

 70%|██████▉   | 21082/30196 [43:48<30:27,  4.99it/s]

 70%|██████▉   | 21084/30196 [43:48<23:50,  6.37it/s]

 70%|██████▉   | 21085/30196 [43:49<32:54,  4.61it/s]

 70%|██████▉   | 21086/30196 [43:49<29:25,  5.16it/s]

 70%|██████▉   | 21087/30196 [43:49<27:20,  5.55it/s]

 70%|██████▉   | 21088/30196 [43:49<24:31,  6.19it/s]

 70%|██████▉   | 21090/30196 [43:49<17:25,  8.71it/s]

 70%|██████▉   | 21092/30196 [43:49<15:31,  9.77it/s]

 70%|██████▉   | 21094/30196 [43:49<14:08, 10.73it/s]

 70%|██████▉   | 21096/30196 [43:50<15:33,  9.74it/s]

 70%|██████▉   | 21098/30196 [43:50<16:26,  9.22it/s]

 70%|██████▉   | 21100/30196 [43:50<15:30,  9.78it/s]

 70%|██████▉   | 21102/30196 [43:50<20:43,  7.31it/s]

 70%|██████▉   | 21103/30196 [43:51<21:52,  6.93it/s]

 70%|██████▉   | 21104/30196 [43:51<20:46,  7.29it/s]

 70%|██████▉   | 21106/30196 [43:51<18:03,  8.39it/s]

 70%|██████▉   | 21107/30196 [43:51<17:47,  8.52it/s]

 70%|██████▉   | 21109/30196 [43:52<32:55,  4.60it/s]

 70%|██████▉   | 21110/30196 [43:52<30:10,  5.02it/s]

 70%|██████▉   | 21112/30196 [43:52<24:16,  6.24it/s]

 70%|██████▉   | 21113/30196 [43:52<26:11,  5.78it/s]

 70%|██████▉   | 21114/30196 [43:52<25:14,  6.00it/s]

 70%|██████▉   | 21116/30196 [43:53<20:53,  7.24it/s]

 70%|██████▉   | 21118/30196 [43:53<18:19,  8.26it/s]

 70%|██████▉   | 21119/30196 [43:53<20:09,  7.50it/s]

 70%|██████▉   | 21121/30196 [43:53<16:26,  9.20it/s]

 70%|██████▉   | 21123/30196 [43:53<14:04, 10.74it/s]

 70%|██████▉   | 21125/30196 [43:53<13:50, 10.93it/s]

 70%|██████▉   | 21127/30196 [43:54<17:53,  8.45it/s]

 70%|██████▉   | 21128/30196 [43:54<17:34,  8.60it/s]

 70%|██████▉   | 21129/30196 [43:54<20:54,  7.23it/s]

 70%|██████▉   | 21131/30196 [43:54<16:29,  9.16it/s]

 70%|██████▉   | 21133/30196 [43:54<13:49, 10.93it/s]

 70%|██████▉   | 21135/30196 [43:54<12:33, 12.03it/s]

 70%|██████▉   | 21137/30196 [43:55<16:05,  9.38it/s]

 70%|███████   | 21139/30196 [43:55<14:38, 10.31it/s]

 70%|███████   | 21141/30196 [43:55<17:46,  8.49it/s]

 70%|███████   | 21143/30196 [43:55<16:25,  9.18it/s]

 70%|███████   | 21145/30196 [43:56<17:17,  8.72it/s]

 70%|███████   | 21146/30196 [43:56<19:58,  7.55it/s]

 70%|███████   | 21147/30196 [43:56<20:04,  7.51it/s]

 70%|███████   | 21149/30196 [43:56<16:26,  9.17it/s]

 70%|███████   | 21151/30196 [43:56<17:29,  8.62it/s]

 70%|███████   | 21152/30196 [43:57<19:15,  7.82it/s]

 70%|███████   | 21154/30196 [43:57<16:24,  9.18it/s]

 70%|███████   | 21156/30196 [43:57<15:13,  9.89it/s]

 70%|███████   | 21158/30196 [43:57<17:56,  8.40it/s]

 70%|███████   | 21161/30196 [43:57<13:57, 10.79it/s]

 70%|███████   | 21163/30196 [43:58<13:58, 10.78it/s]

 70%|███████   | 21165/30196 [43:58<14:13, 10.58it/s]

 70%|███████   | 21167/30196 [43:58<18:26,  8.16it/s]

 70%|███████   | 21168/30196 [43:58<19:38,  7.66it/s]

 70%|███████   | 21169/30196 [43:59<21:51,  6.88it/s]

 70%|███████   | 21170/30196 [43:59<20:41,  7.27it/s]

 70%|███████   | 21172/30196 [43:59<17:55,  8.39it/s]

 70%|███████   | 21174/30196 [43:59<19:10,  7.84it/s]

 70%|███████   | 21175/30196 [43:59<19:47,  7.60it/s]

 70%|███████   | 21176/30196 [43:59<19:03,  7.89it/s]

 70%|███████   | 21177/30196 [44:00<18:14,  8.24it/s]

 70%|███████   | 21178/30196 [44:00<36:15,  4.15it/s]

 70%|███████   | 21180/30196 [44:00<27:07,  5.54it/s]

 70%|███████   | 21181/30196 [44:00<25:33,  5.88it/s]

 70%|███████   | 21182/30196 [44:01<24:04,  6.24it/s]

 70%|███████   | 21183/30196 [44:01<26:49,  5.60it/s]

 70%|███████   | 21185/30196 [44:01<23:52,  6.29it/s]

 70%|███████   | 21187/30196 [44:01<18:38,  8.06it/s]

 70%|███████   | 21189/30196 [44:01<18:11,  8.26it/s]

 70%|███████   | 21190/30196 [44:02<18:33,  8.09it/s]

 70%|███████   | 21191/30196 [44:03<46:58,  3.19it/s]

 70%|███████   | 21192/30196 [44:03<40:57,  3.66it/s]

 70%|███████   | 21193/30196 [44:03<36:59,  4.06it/s]

 70%|███████   | 21195/30196 [44:03<25:33,  5.87it/s]

 70%|███████   | 21196/30196 [44:03<24:37,  6.09it/s]

 70%|███████   | 21197/30196 [44:03<24:42,  6.07it/s]

 70%|███████   | 21198/30196 [44:03<24:53,  6.02it/s]

 70%|███████   | 21199/30196 [44:04<23:40,  6.34it/s]

 70%|███████   | 21201/30196 [44:04<20:13,  7.41it/s]

 70%|███████   | 21202/30196 [44:04<20:26,  7.33it/s]

 70%|███████   | 21204/30196 [44:04<17:49,  8.41it/s]

 70%|███████   | 21206/30196 [44:04<16:04,  9.32it/s]

 70%|███████   | 21207/30196 [44:04<17:16,  8.67it/s]

 70%|███████   | 21208/30196 [44:05<17:56,  8.35it/s]

 70%|███████   | 21210/30196 [44:05<15:05,  9.93it/s]

 70%|███████   | 21212/30196 [44:05<14:07, 10.60it/s]

 70%|███████   | 21214/30196 [44:05<13:09, 11.37it/s]

 70%|███████   | 21216/30196 [44:05<15:04,  9.93it/s]

 70%|███████   | 21218/30196 [44:06<16:29,  9.08it/s]

 70%|███████   | 21219/30196 [44:06<16:20,  9.16it/s]

 70%|███████   | 21220/30196 [44:06<17:07,  8.74it/s]

 70%|███████   | 21222/30196 [44:06<14:08, 10.57it/s]

 70%|███████   | 21224/30196 [44:06<17:17,  8.64it/s]

 70%|███████   | 21226/30196 [44:06<15:55,  9.39it/s]

 70%|███████   | 21228/30196 [44:07<16:57,  8.81it/s]

 70%|███████   | 21230/30196 [44:07<16:16,  9.18it/s]

 70%|███████   | 21231/30196 [44:07<18:06,  8.25it/s]

 70%|███████   | 21233/30196 [44:07<16:05,  9.29it/s]

 70%|███████   | 21235/30196 [44:07<15:41,  9.52it/s]

 70%|███████   | 21236/30196 [44:08<17:40,  8.45it/s]

 70%|███████   | 21238/30196 [44:08<14:56, 10.00it/s]

 70%|███████   | 21240/30196 [44:08<14:32, 10.27it/s]

 70%|███████   | 21242/30196 [44:08<15:08,  9.85it/s]

 70%|███████   | 21244/30196 [44:08<16:15,  9.18it/s]

 70%|███████   | 21246/30196 [44:09<16:58,  8.79it/s]

 70%|███████   | 21247/30196 [44:09<21:34,  6.91it/s]

 70%|███████   | 21248/30196 [44:09<20:29,  7.28it/s]

 70%|███████   | 21249/30196 [44:09<19:35,  7.61it/s]

 70%|███████   | 21250/30196 [44:09<20:49,  7.16it/s]

 70%|███████   | 21252/30196 [44:09<16:56,  8.80it/s]

 70%|███████   | 21254/30196 [44:10<15:13,  9.79it/s]

 70%|███████   | 21256/30196 [44:10<17:17,  8.62it/s]

 70%|███████   | 21258/30196 [44:10<16:22,  9.09it/s]

 70%|███████   | 21259/30196 [44:10<16:13,  9.18it/s]

 70%|███████   | 21261/30196 [44:10<13:09, 11.31it/s]

 70%|███████   | 21263/30196 [44:10<12:38, 11.78it/s]

 70%|███████   | 21265/30196 [44:11<16:52,  8.82it/s]

 70%|███████   | 21267/30196 [44:11<18:29,  8.05it/s]

 70%|███████   | 21268/30196 [44:11<23:53,  6.23it/s]

 70%|███████   | 21269/30196 [44:12<22:10,  6.71it/s]

 70%|███████   | 21271/30196 [44:12<17:04,  8.71it/s]

 70%|███████   | 21273/30196 [44:12<16:17,  9.13it/s]

 70%|███████   | 21276/30196 [44:12<13:18, 11.17it/s]

 70%|███████   | 21278/30196 [44:12<14:04, 10.56it/s]

 70%|███████   | 21280/30196 [44:12<14:22, 10.34it/s]

 70%|███████   | 21282/30196 [44:13<14:04, 10.56it/s]

 70%|███████   | 21284/30196 [44:13<16:37,  8.93it/s]

 70%|███████   | 21286/30196 [44:13<16:15,  9.13it/s]

 70%|███████   | 21287/30196 [44:13<17:42,  8.38it/s]

 70%|███████   | 21288/30196 [44:13<18:04,  8.22it/s]

 71%|███████   | 21289/30196 [44:14<19:48,  7.50it/s]

 71%|███████   | 21290/30196 [44:14<21:03,  7.05it/s]

 71%|███████   | 21292/30196 [44:14<17:51,  8.31it/s]

 71%|███████   | 21293/30196 [44:14<18:34,  7.99it/s]

 71%|███████   | 21295/30196 [44:14<14:36, 10.16it/s]

 71%|███████   | 21297/30196 [44:14<17:11,  8.63it/s]

 71%|███████   | 21299/30196 [44:15<16:53,  8.78it/s]

 71%|███████   | 21301/30196 [44:15<16:04,  9.22it/s]

 71%|███████   | 21303/30196 [44:15<13:42, 10.82it/s]

 71%|███████   | 21305/30196 [44:15<13:28, 11.00it/s]

 71%|███████   | 21307/30196 [44:15<13:51, 10.69it/s]

 71%|███████   | 21309/30196 [44:16<17:51,  8.29it/s]

 71%|███████   | 21311/30196 [44:16<16:26,  9.00it/s]

 71%|███████   | 21313/30196 [44:16<16:29,  8.98it/s]

 71%|███████   | 21314/30196 [44:16<16:58,  8.72it/s]

 71%|███████   | 21316/30196 [44:16<14:13, 10.40it/s]

 71%|███████   | 21318/30196 [44:17<15:06,  9.79it/s]

 71%|███████   | 21320/30196 [44:17<14:44, 10.03it/s]

 71%|███████   | 21322/30196 [44:17<14:59,  9.86it/s]

 71%|███████   | 21324/30196 [44:17<16:42,  8.85it/s]

 71%|███████   | 21325/30196 [44:17<16:30,  8.96it/s]

 71%|███████   | 21327/30196 [44:18<17:44,  8.33it/s]

 71%|███████   | 21328/30196 [44:18<18:30,  7.98it/s]

 71%|███████   | 21329/30196 [44:18<19:02,  7.76it/s]

 71%|███████   | 21330/30196 [44:18<20:38,  7.16it/s]

 71%|███████   | 21331/30196 [44:18<19:25,  7.60it/s]

 71%|███████   | 21333/30196 [44:19<18:21,  8.05it/s]

 71%|███████   | 21335/30196 [44:19<15:27,  9.56it/s]

 71%|███████   | 21337/30196 [44:19<13:30, 10.93it/s]

 71%|███████   | 21339/30196 [44:19<17:28,  8.45it/s]

 71%|███████   | 21341/30196 [44:19<17:28,  8.45it/s]

 71%|███████   | 21342/30196 [44:20<18:10,  8.12it/s]

 71%|███████   | 21343/30196 [44:20<20:59,  7.03it/s]

 71%|███████   | 21345/30196 [44:20<21:17,  6.93it/s]

 71%|███████   | 21346/30196 [44:20<22:06,  6.67it/s]

 71%|███████   | 21348/30196 [44:20<20:23,  7.23it/s]

 71%|███████   | 21350/30196 [44:21<21:35,  6.83it/s]

 71%|███████   | 21352/30196 [44:21<20:58,  7.02it/s]

 71%|███████   | 21353/30196 [44:21<20:39,  7.14it/s]

 71%|███████   | 21355/30196 [44:21<17:56,  8.21it/s]

 71%|███████   | 21356/30196 [44:21<18:13,  8.09it/s]

 71%|███████   | 21357/30196 [44:22<19:50,  7.43it/s]

 71%|███████   | 21358/30196 [44:22<18:48,  7.83it/s]

 71%|███████   | 21360/30196 [44:22<16:41,  8.82it/s]

 71%|███████   | 21362/30196 [44:22<16:37,  8.86it/s]

 71%|███████   | 21363/30196 [44:22<16:31,  8.91it/s]

 71%|███████   | 21365/30196 [44:22<16:39,  8.84it/s]

 71%|███████   | 21366/30196 [44:23<17:29,  8.41it/s]

 71%|███████   | 21367/30196 [44:23<17:10,  8.57it/s]

 71%|███████   | 21368/30196 [44:23<18:10,  8.10it/s]

 71%|███████   | 21369/30196 [44:23<17:35,  8.36it/s]

 71%|███████   | 21370/30196 [44:23<21:18,  6.90it/s]

 71%|███████   | 21372/30196 [44:23<18:05,  8.13it/s]

 71%|███████   | 21373/30196 [44:24<18:57,  7.76it/s]

 71%|███████   | 21374/30196 [44:24<18:02,  8.15it/s]

 71%|███████   | 21376/30196 [44:24<17:20,  8.48it/s]

 71%|███████   | 21378/30196 [44:24<24:59,  5.88it/s]

 71%|███████   | 21380/30196 [44:24<19:08,  7.67it/s]

 71%|███████   | 21382/30196 [44:25<19:31,  7.53it/s]

 71%|███████   | 21384/30196 [44:25<16:27,  8.92it/s]

 71%|███████   | 21386/30196 [44:25<15:49,  9.28it/s]

 71%|███████   | 21388/30196 [44:25<15:59,  9.18it/s]

 71%|███████   | 21390/30196 [44:26<17:53,  8.21it/s]

 71%|███████   | 21391/30196 [44:26<19:03,  7.70it/s]

 71%|███████   | 21392/30196 [44:26<18:26,  7.96it/s]

 71%|███████   | 21394/30196 [44:26<15:06,  9.71it/s]

 71%|███████   | 21396/30196 [44:26<16:43,  8.77it/s]

 71%|███████   | 21397/30196 [44:26<16:34,  8.84it/s]

 71%|███████   | 21398/30196 [44:27<18:40,  7.86it/s]

 71%|███████   | 21399/30196 [44:27<29:31,  4.97it/s]

 71%|███████   | 21401/30196 [44:27<24:11,  6.06it/s]

 71%|███████   | 21402/30196 [44:27<22:10,  6.61it/s]

 71%|███████   | 21404/30196 [44:28<24:37,  5.95it/s]

 71%|███████   | 21405/30196 [44:28<23:33,  6.22it/s]

 71%|███████   | 21407/30196 [44:28<19:10,  7.64it/s]

 71%|███████   | 21408/30196 [44:28<18:31,  7.91it/s]

 71%|███████   | 21410/30196 [44:28<17:33,  8.34it/s]

 71%|███████   | 21412/30196 [44:28<14:07, 10.37it/s]

 71%|███████   | 21414/30196 [44:29<15:03,  9.72it/s]

 71%|███████   | 21416/30196 [44:29<13:18, 10.99it/s]

 71%|███████   | 21418/30196 [44:29<14:10, 10.33it/s]

 71%|███████   | 21420/30196 [44:29<12:46, 11.45it/s]

 71%|███████   | 21422/30196 [44:29<12:15, 11.92it/s]

 71%|███████   | 21424/30196 [44:30<14:41,  9.95it/s]

 71%|███████   | 21426/30196 [44:30<18:26,  7.92it/s]

 71%|███████   | 21428/30196 [44:30<17:34,  8.32it/s]

 71%|███████   | 21430/30196 [44:31<19:16,  7.58it/s]

 71%|███████   | 21432/30196 [44:31<16:21,  8.93it/s]

 71%|███████   | 21435/30196 [44:31<13:40, 10.67it/s]

 71%|███████   | 21437/30196 [44:31<13:40, 10.68it/s]

 71%|███████   | 21439/30196 [44:31<12:33, 11.63it/s]

 71%|███████   | 21441/30196 [44:31<14:41,  9.93it/s]

 71%|███████   | 21443/30196 [44:32<16:39,  8.76it/s]

 71%|███████   | 21444/30196 [44:32<16:25,  8.88it/s]

 71%|███████   | 21446/30196 [44:32<17:29,  8.33it/s]

 71%|███████   | 21448/30196 [44:32<15:16,  9.54it/s]

 71%|███████   | 21450/30196 [44:32<15:36,  9.34it/s]

 71%|███████   | 21452/30196 [44:33<13:11, 11.05it/s]

 71%|███████   | 21454/30196 [44:33<13:12, 11.04it/s]

 71%|███████   | 21456/30196 [44:33<18:44,  7.77it/s]

 71%|███████   | 21457/30196 [44:33<21:06,  6.90it/s]

 71%|███████   | 21458/30196 [44:34<20:57,  6.95it/s]

 71%|███████   | 21459/30196 [44:34<21:01,  6.92it/s]

 71%|███████   | 21461/30196 [44:34<19:12,  7.58it/s]

 71%|███████   | 21463/30196 [44:34<18:38,  7.81it/s]

 71%|███████   | 21465/30196 [44:34<15:01,  9.69it/s]

 71%|███████   | 21467/30196 [44:34<13:20, 10.90it/s]

 71%|███████   | 21469/30196 [44:35<12:23, 11.73it/s]

 71%|███████   | 21471/30196 [44:35<13:56, 10.42it/s]

 71%|███████   | 21473/30196 [44:35<13:18, 10.93it/s]

 71%|███████   | 21475/30196 [44:35<16:19,  8.90it/s]

 71%|███████   | 21477/30196 [44:35<15:56,  9.12it/s]

 71%|███████   | 21478/30196 [44:36<16:55,  8.58it/s]

 71%|███████   | 21479/30196 [44:36<16:44,  8.68it/s]

 71%|███████   | 21480/30196 [44:36<16:30,  8.80it/s]

 71%|███████   | 21482/30196 [44:36<17:07,  8.48it/s]

 71%|███████   | 21484/30196 [44:36<16:46,  8.66it/s]

 71%|███████   | 21485/30196 [44:36<17:18,  8.38it/s]

 71%|███████   | 21486/30196 [44:37<18:00,  8.06it/s]

 71%|███████   | 21487/30196 [44:37<18:50,  7.70it/s]

 71%|███████   | 21489/30196 [44:37<16:22,  8.86it/s]

 71%|███████   | 21491/30196 [44:37<18:22,  7.89it/s]

 71%|███████   | 21493/30196 [44:37<17:12,  8.43it/s]

 71%|███████   | 21494/30196 [44:38<17:39,  8.21it/s]

 71%|███████   | 21495/30196 [44:38<18:05,  8.01it/s]

 71%|███████   | 21496/30196 [44:38<22:44,  6.38it/s]

 71%|███████   | 21498/30196 [44:38<18:48,  7.71it/s]

 71%|███████   | 21499/30196 [44:38<18:56,  7.65it/s]

 71%|███████   | 21501/30196 [44:38<15:34,  9.31it/s]

 71%|███████   | 21503/30196 [44:39<16:02,  9.03it/s]

 71%|███████   | 21505/30196 [44:39<18:44,  7.73it/s]

 71%|███████   | 21507/30196 [44:39<15:45,  9.19it/s]

 71%|███████   | 21509/30196 [44:39<18:07,  7.99it/s]

 71%|███████   | 21511/30196 [44:40<24:37,  5.88it/s]

 71%|███████   | 21512/30196 [44:40<31:11,  4.64it/s]

 71%|███████   | 21514/30196 [44:41<25:58,  5.57it/s]

 71%|███████▏  | 21515/30196 [44:41<25:02,  5.78it/s]

 71%|███████▏  | 21516/30196 [44:41<23:58,  6.03it/s]

 71%|███████▏  | 21517/30196 [44:41<21:53,  6.61it/s]

 71%|███████▏  | 21518/30196 [44:41<23:52,  6.06it/s]

 71%|███████▏  | 21521/30196 [44:42<20:56,  6.90it/s]

 71%|███████▏  | 21523/30196 [44:42<19:16,  7.50it/s]

 71%|███████▏  | 21524/30196 [44:42<23:54,  6.05it/s]

 71%|███████▏  | 21525/30196 [44:42<25:15,  5.72it/s]

 71%|███████▏  | 21526/30196 [44:42<23:46,  6.08it/s]

 71%|███████▏  | 21528/30196 [44:43<18:06,  7.98it/s]

 71%|███████▏  | 21530/30196 [44:43<18:09,  7.95it/s]

 71%|███████▏  | 21531/30196 [44:43<19:23,  7.45it/s]

 71%|███████▏  | 21533/30196 [44:43<16:07,  8.95it/s]

 71%|███████▏  | 21534/30196 [44:43<15:55,  9.06it/s]

 71%|███████▏  | 21536/30196 [44:44<18:41,  7.72it/s]

 71%|███████▏  | 21537/30196 [44:44<19:11,  7.52it/s]

 71%|███████▏  | 21538/30196 [44:44<20:23,  7.08it/s]

 71%|███████▏  | 21540/30196 [44:44<15:46,  9.15it/s]

 71%|███████▏  | 21542/30196 [44:44<13:53, 10.38it/s]

 71%|███████▏  | 21544/30196 [44:44<17:14,  8.36it/s]

 71%|███████▏  | 21545/30196 [44:45<18:40,  7.72it/s]

 71%|███████▏  | 21547/30196 [44:45<18:00,  8.00it/s]

 71%|███████▏  | 21548/30196 [44:45<18:19,  7.87it/s]

 71%|███████▏  | 21549/30196 [44:45<18:24,  7.83it/s]

 71%|███████▏  | 21551/30196 [44:45<18:35,  7.75it/s]

 71%|███████▏  | 21553/30196 [44:46<15:17,  9.42it/s]

 71%|███████▏  | 21555/30196 [44:46<17:40,  8.15it/s]

 71%|███████▏  | 21557/30196 [44:46<14:25,  9.98it/s]

 71%|███████▏  | 21559/30196 [44:46<14:27,  9.96it/s]

 71%|███████▏  | 21561/30196 [44:46<15:36,  9.22it/s]

 71%|███████▏  | 21563/30196 [44:47<13:42, 10.49it/s]

 71%|███████▏  | 21566/30196 [44:47<13:18, 10.81it/s]

 71%|███████▏  | 21568/30196 [44:47<15:00,  9.58it/s]

 71%|███████▏  | 21570/30196 [44:47<17:53,  8.04it/s]

 71%|███████▏  | 21571/30196 [44:48<19:52,  7.23it/s]

 71%|███████▏  | 21572/30196 [44:48<19:38,  7.32it/s]

 71%|███████▏  | 21574/30196 [44:48<17:44,  8.10it/s]

 71%|███████▏  | 21575/30196 [44:48<18:24,  7.81it/s]

 71%|███████▏  | 21576/30196 [44:48<21:24,  6.71it/s]

 71%|███████▏  | 21578/30196 [44:49<18:27,  7.78it/s]

 71%|███████▏  | 21579/30196 [44:49<19:38,  7.31it/s]

 71%|███████▏  | 21580/30196 [44:49<19:26,  7.39it/s]

 71%|███████▏  | 21581/30196 [44:49<23:33,  6.10it/s]

 71%|███████▏  | 21583/30196 [44:49<19:07,  7.51it/s]

 71%|███████▏  | 21584/30196 [44:49<18:21,  7.82it/s]

 71%|███████▏  | 21586/30196 [44:49<14:25,  9.95it/s]

 71%|███████▏  | 21588/30196 [44:50<15:27,  9.28it/s]

 71%|███████▏  | 21590/30196 [44:50<13:04, 10.97it/s]

 72%|███████▏  | 21592/30196 [44:50<14:44,  9.73it/s]

 72%|███████▏  | 21594/30196 [44:50<15:38,  9.17it/s]

 72%|███████▏  | 21596/30196 [44:51<19:04,  7.51it/s]

 72%|███████▏  | 21597/30196 [44:51<19:27,  7.37it/s]

 72%|███████▏  | 21598/30196 [44:51<19:47,  7.24it/s]

 72%|███████▏  | 21600/30196 [44:51<16:23,  8.74it/s]

 72%|███████▏  | 21601/30196 [44:51<16:05,  8.90it/s]

 72%|███████▏  | 21603/30196 [44:51<14:50,  9.65it/s]

 72%|███████▏  | 21605/30196 [44:52<13:33, 10.57it/s]

 72%|███████▏  | 21607/30196 [44:52<12:24, 11.53it/s]

 72%|███████▏  | 21609/30196 [44:52<14:32,  9.84it/s]

 72%|███████▏  | 21611/30196 [44:52<13:50, 10.34it/s]

 72%|███████▏  | 21613/30196 [44:52<13:10, 10.85it/s]

 72%|███████▏  | 21615/30196 [44:53<12:44, 11.22it/s]

 72%|███████▏  | 21617/30196 [44:53<14:05, 10.14it/s]

 72%|███████▏  | 21619/30196 [44:53<15:38,  9.14it/s]

 72%|███████▏  | 21621/30196 [44:53<15:28,  9.24it/s]

 72%|███████▏  | 21622/30196 [44:53<17:16,  8.27it/s]

 72%|███████▏  | 21624/30196 [44:54<22:13,  6.43it/s]

 72%|███████▏  | 21626/30196 [44:54<17:21,  8.23it/s]

 72%|███████▏  | 21628/30196 [44:54<18:42,  7.63it/s]

 72%|███████▏  | 21631/30196 [44:55<16:09,  8.83it/s]

 72%|███████▏  | 21633/30196 [44:55<16:40,  8.56it/s]

 72%|███████▏  | 21634/30196 [44:55<16:29,  8.65it/s]

 72%|███████▏  | 21635/30196 [44:55<16:21,  8.72it/s]

 72%|███████▏  | 21637/30196 [44:55<17:14,  8.27it/s]

 72%|███████▏  | 21638/30196 [44:56<20:59,  6.79it/s]

 72%|███████▏  | 21640/30196 [44:56<17:28,  8.16it/s]

 72%|███████▏  | 21641/30196 [44:56<19:58,  7.14it/s]

 72%|███████▏  | 21642/30196 [44:56<18:59,  7.51it/s]

 72%|███████▏  | 21643/30196 [44:56<20:22,  6.99it/s]

 72%|███████▏  | 21645/30196 [44:56<15:54,  8.96it/s]

 72%|███████▏  | 21646/30196 [44:56<17:04,  8.34it/s]

 72%|███████▏  | 21648/30196 [44:57<14:59,  9.50it/s]

 72%|███████▏  | 21650/30196 [44:57<14:35,  9.76it/s]

 72%|███████▏  | 21651/30196 [44:57<15:34,  9.15it/s]

 72%|███████▏  | 21652/30196 [44:57<17:28,  8.14it/s]

 72%|███████▏  | 21654/30196 [44:57<18:26,  7.72it/s]

 72%|███████▏  | 21655/30196 [44:58<18:35,  7.66it/s]

 72%|███████▏  | 21657/30196 [44:58<15:34,  9.13it/s]

 72%|███████▏  | 21658/30196 [44:58<15:36,  9.12it/s]

 72%|███████▏  | 21660/30196 [44:58<16:11,  8.79it/s]

 72%|███████▏  | 21661/30196 [44:58<17:45,  8.01it/s]

 72%|███████▏  | 21662/30196 [44:58<19:34,  7.26it/s]

 72%|███████▏  | 21663/30196 [44:59<19:26,  7.31it/s]

 72%|███████▏  | 21664/30196 [44:59<18:14,  7.80it/s]

 72%|███████▏  | 21666/30196 [44:59<14:28,  9.82it/s]

 72%|███████▏  | 21668/30196 [44:59<16:22,  8.68it/s]

 72%|███████▏  | 21670/30196 [44:59<14:22,  9.89it/s]

 72%|███████▏  | 21672/30196 [44:59<14:20,  9.90it/s]

 72%|███████▏  | 21674/30196 [45:00<13:09, 10.79it/s]

 72%|███████▏  | 21676/30196 [45:00<14:10, 10.02it/s]

 72%|███████▏  | 21678/30196 [45:00<12:03, 11.78it/s]

 72%|███████▏  | 21680/30196 [45:00<13:08, 10.79it/s]

 72%|███████▏  | 21682/30196 [45:00<14:48,  9.59it/s]

 72%|███████▏  | 21684/30196 [45:01<14:33,  9.74it/s]

 72%|███████▏  | 21686/30196 [45:01<12:58, 10.93it/s]

 72%|███████▏  | 21688/30196 [45:01<13:13, 10.72it/s]

 72%|███████▏  | 21690/30196 [45:01<11:49, 11.99it/s]

 72%|███████▏  | 21692/30196 [45:01<11:10, 12.69it/s]

 72%|███████▏  | 21694/30196 [45:01<13:07, 10.80it/s]

 72%|███████▏  | 21696/30196 [45:02<13:07, 10.80it/s]

 72%|███████▏  | 21698/30196 [45:02<16:15,  8.71it/s]

 72%|███████▏  | 21699/30196 [45:02<16:54,  8.38it/s]

 72%|███████▏  | 21701/30196 [45:02<15:09,  9.34it/s]

 72%|███████▏  | 21703/30196 [45:02<14:19,  9.88it/s]

 72%|███████▏  | 21705/30196 [45:03<13:50, 10.22it/s]

 72%|███████▏  | 21707/30196 [45:03<14:24,  9.82it/s]

 72%|███████▏  | 21709/30196 [45:03<14:07, 10.01it/s]

 72%|███████▏  | 21711/30196 [45:03<14:52,  9.50it/s]

 72%|███████▏  | 21713/30196 [45:03<16:32,  8.55it/s]

 72%|███████▏  | 21714/30196 [45:04<16:54,  8.36it/s]

 72%|███████▏  | 21716/30196 [45:04<15:53,  8.89it/s]

 72%|███████▏  | 21717/30196 [45:04<15:40,  9.01it/s]

 72%|███████▏  | 21718/30196 [45:04<22:07,  6.39it/s]

 72%|███████▏  | 21720/30196 [45:04<19:18,  7.32it/s]

 72%|███████▏  | 21721/30196 [45:05<20:33,  6.87it/s]

 72%|███████▏  | 21722/30196 [45:05<22:37,  6.24it/s]

 72%|███████▏  | 21724/30196 [45:05<17:33,  8.04it/s]

 72%|███████▏  | 21725/30196 [45:05<18:17,  7.72it/s]

 72%|███████▏  | 21727/30196 [45:05<18:41,  7.55it/s]

 72%|███████▏  | 21729/30196 [45:06<16:35,  8.51it/s]

 72%|███████▏  | 21730/30196 [45:06<17:59,  7.84it/s]

 72%|███████▏  | 21731/30196 [45:06<19:26,  7.26it/s]

 72%|███████▏  | 21733/30196 [45:06<16:23,  8.60it/s]

 72%|███████▏  | 21734/30196 [45:06<17:08,  8.23it/s]

 72%|███████▏  | 21735/30196 [45:06<17:34,  8.02it/s]

 72%|███████▏  | 21737/30196 [45:07<14:31,  9.70it/s]

 72%|███████▏  | 21739/30196 [45:07<13:13, 10.66it/s]

 72%|███████▏  | 21741/30196 [45:07<11:28, 12.28it/s]

 72%|███████▏  | 21743/30196 [45:07<11:02, 12.76it/s]

 72%|███████▏  | 21745/30196 [45:07<11:54, 11.82it/s]

 72%|███████▏  | 21747/30196 [45:07<15:44,  8.94it/s]

 72%|███████▏  | 21749/30196 [45:08<15:30,  9.08it/s]

 72%|███████▏  | 21751/30196 [45:08<17:29,  8.05it/s]

 72%|███████▏  | 21752/30196 [45:08<21:14,  6.63it/s]

 72%|███████▏  | 21754/30196 [45:08<18:09,  7.75it/s]

 72%|███████▏  | 21755/30196 [45:09<18:12,  7.73it/s]

 72%|███████▏  | 21756/30196 [45:09<18:22,  7.65it/s]

 72%|███████▏  | 21757/30196 [45:09<17:40,  7.95it/s]

 72%|███████▏  | 21759/30196 [45:09<14:43,  9.55it/s]

 72%|███████▏  | 21761/30196 [45:09<15:56,  8.82it/s]

 72%|███████▏  | 21763/30196 [45:09<13:24, 10.48it/s]

 72%|███████▏  | 21765/30196 [45:10<14:32,  9.66it/s]

 72%|███████▏  | 21767/30196 [45:10<13:15, 10.59it/s]

 72%|███████▏  | 21769/30196 [45:10<13:45, 10.21it/s]

 72%|███████▏  | 21771/30196 [45:10<14:01, 10.02it/s]

 72%|███████▏  | 21773/30196 [45:10<12:34, 11.16it/s]

 72%|███████▏  | 21775/30196 [45:10<12:15, 11.44it/s]

 72%|███████▏  | 21777/30196 [45:11<13:57, 10.06it/s]

 72%|███████▏  | 21779/30196 [45:11<15:12,  9.23it/s]

 72%|███████▏  | 21780/30196 [45:11<15:44,  8.91it/s]

 72%|███████▏  | 21781/30196 [45:11<17:19,  8.09it/s]

 72%|███████▏  | 21782/30196 [45:11<16:44,  8.37it/s]

 72%|███████▏  | 21783/30196 [45:12<17:42,  7.92it/s]

 72%|███████▏  | 21784/30196 [45:12<20:45,  6.75it/s]

 72%|███████▏  | 21785/30196 [45:12<21:34,  6.50it/s]

 72%|███████▏  | 21786/30196 [45:12<19:36,  7.15it/s]

 72%|███████▏  | 21788/30196 [45:12<14:59,  9.35it/s]

 72%|███████▏  | 21790/30196 [45:12<14:55,  9.39it/s]

 72%|███████▏  | 21792/30196 [45:12<13:05, 10.70it/s]

 72%|███████▏  | 21794/30196 [45:13<17:56,  7.80it/s]

 72%|███████▏  | 21795/30196 [45:13<17:18,  8.09it/s]

 72%|███████▏  | 21796/30196 [45:13<16:53,  8.29it/s]

 72%|███████▏  | 21797/30196 [45:13<19:39,  7.12it/s]

 72%|███████▏  | 21798/30196 [45:13<21:58,  6.37it/s]

 72%|███████▏  | 21799/30196 [45:14<20:03,  6.98it/s]

 72%|███████▏  | 21800/30196 [45:14<43:58,  3.18it/s]

 72%|███████▏  | 21802/30196 [45:15<31:11,  4.49it/s]

 72%|███████▏  | 21804/30196 [45:15<25:31,  5.48it/s]

 72%|███████▏  | 21805/30196 [45:15<23:10,  6.03it/s]

 72%|███████▏  | 21806/30196 [45:15<23:08,  6.04it/s]

 72%|███████▏  | 21808/30196 [45:15<18:18,  7.64it/s]

 72%|███████▏  | 21809/30196 [45:15<17:40,  7.91it/s]

 72%|███████▏  | 21811/30196 [45:15<14:33,  9.60it/s]

 72%|███████▏  | 21813/30196 [45:16<15:05,  9.26it/s]

 72%|███████▏  | 21815/30196 [45:16<15:23,  9.08it/s]

 72%|███████▏  | 21816/30196 [45:16<15:14,  9.16it/s]

 72%|███████▏  | 21818/30196 [45:16<16:06,  8.67it/s]

 72%|███████▏  | 21819/30196 [45:16<16:39,  8.38it/s]

 72%|███████▏  | 21821/30196 [45:17<13:59,  9.98it/s]

 72%|███████▏  | 21823/30196 [45:17<13:38, 10.23it/s]

 72%|███████▏  | 21825/30196 [45:17<11:28, 12.17it/s]

 72%|███████▏  | 21827/30196 [45:17<13:14, 10.53it/s]

 72%|███████▏  | 21829/30196 [45:17<11:44, 11.87it/s]

 72%|███████▏  | 21831/30196 [45:17<13:15, 10.51it/s]

 72%|███████▏  | 21833/30196 [45:18<13:09, 10.59it/s]

 72%|███████▏  | 21835/30196 [45:18<13:53, 10.03it/s]

 72%|███████▏  | 21837/30196 [45:18<14:52,  9.37it/s]

 72%|███████▏  | 21839/30196 [45:18<15:37,  8.91it/s]

 72%|███████▏  | 21840/30196 [45:19<17:08,  8.13it/s]

 72%|███████▏  | 21842/30196 [45:19<16:38,  8.36it/s]

 72%|███████▏  | 21843/30196 [45:19<16:14,  8.57it/s]

 72%|███████▏  | 21844/30196 [45:19<15:51,  8.77it/s]

 72%|███████▏  | 21845/30196 [45:19<17:58,  7.74it/s]

 72%|███████▏  | 21846/30196 [45:19<22:40,  6.14it/s]

 72%|███████▏  | 21848/30196 [45:20<17:08,  8.12it/s]

 72%|███████▏  | 21849/30196 [45:20<19:59,  6.96it/s]

 72%|███████▏  | 21851/30196 [45:20<17:17,  8.04it/s]

 72%|███████▏  | 21852/30196 [45:20<17:59,  7.73it/s]

 72%|███████▏  | 21853/30196 [45:20<19:29,  7.13it/s]

 72%|███████▏  | 21854/30196 [45:20<21:55,  6.34it/s]

 72%|███████▏  | 21855/30196 [45:21<23:42,  5.86it/s]

 72%|███████▏  | 21856/30196 [45:21<23:32,  5.90it/s]

 72%|███████▏  | 21858/30196 [45:21<18:15,  7.61it/s]

 72%|███████▏  | 21860/30196 [45:21<14:51,  9.35it/s]

 72%|███████▏  | 21861/30196 [45:21<16:43,  8.30it/s]

 72%|███████▏  | 21862/30196 [45:21<16:14,  8.55it/s]

 72%|███████▏  | 21863/30196 [45:22<21:37,  6.42it/s]

 72%|███████▏  | 21864/30196 [45:22<24:14,  5.73it/s]

 72%|███████▏  | 21865/30196 [45:22<22:35,  6.15it/s]

 72%|███████▏  | 21866/30196 [45:22<21:57,  6.32it/s]

 72%|███████▏  | 21867/30196 [45:22<20:01,  6.93it/s]

 72%|███████▏  | 21869/30196 [45:22<14:39,  9.46it/s]

 72%|███████▏  | 21871/30196 [45:23<14:48,  9.37it/s]

 72%|███████▏  | 21873/30196 [45:23<16:17,  8.51it/s]

 72%|███████▏  | 21874/30196 [45:23<16:48,  8.25it/s]

 72%|███████▏  | 21875/30196 [45:23<16:27,  8.42it/s]

 72%|███████▏  | 21877/30196 [45:23<14:30,  9.56it/s]

 72%|███████▏  | 21879/30196 [45:24<14:03,  9.86it/s]

 72%|███████▏  | 21881/30196 [45:24<12:01, 11.53it/s]

 72%|███████▏  | 21883/30196 [45:24<14:25,  9.60it/s]

 72%|███████▏  | 21885/30196 [45:24<14:17,  9.69it/s]

 72%|███████▏  | 21887/30196 [45:24<15:16,  9.07it/s]

 72%|███████▏  | 21889/30196 [45:25<13:24, 10.33it/s]

 72%|███████▏  | 21891/30196 [45:25<16:19,  8.48it/s]

 73%|███████▎  | 21893/30196 [45:25<15:35,  8.88it/s]

 73%|███████▎  | 21895/30196 [45:25<14:32,  9.52it/s]

 73%|███████▎  | 21897/30196 [45:25<15:54,  8.69it/s]

 73%|███████▎  | 21898/30196 [45:26<16:24,  8.43it/s]

 73%|███████▎  | 21899/30196 [45:26<17:48,  7.77it/s]

 73%|███████▎  | 21900/30196 [45:26<17:51,  7.74it/s]

 73%|███████▎  | 21901/30196 [45:26<17:12,  8.04it/s]

 73%|███████▎  | 21902/30196 [45:26<18:38,  7.42it/s]

 73%|███████▎  | 21903/30196 [45:26<20:06,  6.87it/s]

 73%|███████▎  | 21904/30196 [45:27<22:27,  6.16it/s]

 73%|███████▎  | 21905/30196 [45:27<22:44,  6.07it/s]

 73%|███████▎  | 21906/30196 [45:27<25:18,  5.46it/s]

 73%|███████▎  | 21907/30196 [45:27<23:52,  5.79it/s]

 73%|███████▎  | 21909/30196 [45:27<18:08,  7.61it/s]

 73%|███████▎  | 21911/30196 [45:28<21:51,  6.32it/s]

 73%|███████▎  | 21913/30196 [45:28<17:44,  7.78it/s]

 73%|███████▎  | 21915/30196 [45:28<15:50,  8.71it/s]

 73%|███████▎  | 21917/30196 [45:28<13:16, 10.40it/s]

 73%|███████▎  | 21919/30196 [45:29<19:46,  6.98it/s]

 73%|███████▎  | 21920/30196 [45:29<20:33,  6.71it/s]

 73%|███████▎  | 21921/30196 [45:29<19:16,  7.15it/s]

 73%|███████▎  | 21922/30196 [45:29<21:46,  6.33it/s]

 73%|███████▎  | 21924/30196 [45:29<16:22,  8.42it/s]

 73%|███████▎  | 21926/30196 [45:29<13:47, 10.00it/s]

 73%|███████▎  | 21928/30196 [45:30<12:34, 10.95it/s]

 73%|███████▎  | 21930/30196 [45:30<13:40, 10.08it/s]

 73%|███████▎  | 21932/30196 [45:30<13:07, 10.49it/s]

 73%|███████▎  | 21934/30196 [45:30<11:56, 11.53it/s]

 73%|███████▎  | 21936/30196 [45:30<11:21, 12.12it/s]

 73%|███████▎  | 21938/30196 [45:30<11:20, 12.13it/s]

 73%|███████▎  | 21940/30196 [45:31<14:55,  9.22it/s]

 73%|███████▎  | 21942/30196 [45:32<30:35,  4.50it/s]

 73%|███████▎  | 21943/30196 [45:32<28:45,  4.78it/s]

 73%|███████▎  | 21945/30196 [45:32<24:41,  5.57it/s]

 73%|███████▎  | 21947/30196 [45:32<19:18,  7.12it/s]

 73%|███████▎  | 21949/30196 [45:33<20:36,  6.67it/s]

 73%|███████▎  | 21950/30196 [45:33<22:00,  6.25it/s]

 73%|███████▎  | 21951/30196 [45:33<21:37,  6.35it/s]

 73%|███████▎  | 21952/30196 [45:33<21:05,  6.51it/s]

 73%|███████▎  | 21953/30196 [45:33<20:40,  6.64it/s]

 73%|███████▎  | 21954/30196 [45:33<19:01,  7.22it/s]

 73%|███████▎  | 21955/30196 [45:33<18:52,  7.28it/s]

 73%|███████▎  | 21956/30196 [45:34<19:00,  7.23it/s]

 73%|███████▎  | 21957/30196 [45:34<18:51,  7.28it/s]

 73%|███████▎  | 21958/30196 [45:34<18:39,  7.36it/s]

 73%|███████▎  | 21960/30196 [45:34<14:47,  9.28it/s]

 73%|███████▎  | 21962/30196 [45:34<15:21,  8.93it/s]

 73%|███████▎  | 21964/30196 [45:34<15:29,  8.86it/s]

 73%|███████▎  | 21965/30196 [45:35<16:59,  8.07it/s]

 73%|███████▎  | 21966/30196 [45:35<17:22,  7.90it/s]

 73%|███████▎  | 21967/30196 [45:35<16:48,  8.16it/s]

 73%|███████▎  | 21969/30196 [45:35<15:09,  9.05it/s]

 73%|███████▎  | 21970/30196 [45:35<16:04,  8.53it/s]

 73%|███████▎  | 21971/30196 [45:35<16:48,  8.16it/s]

 73%|███████▎  | 21973/30196 [45:36<15:35,  8.79it/s]

 73%|███████▎  | 21975/30196 [45:36<14:17,  9.59it/s]

 73%|███████▎  | 21976/30196 [45:36<15:11,  9.02it/s]

 73%|███████▎  | 21977/30196 [45:36<15:57,  8.58it/s]

 73%|███████▎  | 21978/30196 [45:36<15:38,  8.76it/s]

 73%|███████▎  | 21980/30196 [45:36<14:23,  9.52it/s]

 73%|███████▎  | 21981/30196 [45:36<15:30,  8.83it/s]

 73%|███████▎  | 21983/30196 [45:37<13:49,  9.90it/s]

 73%|███████▎  | 21985/30196 [45:37<13:11, 10.37it/s]

 73%|███████▎  | 21987/30196 [45:37<15:53,  8.61it/s]

 73%|███████▎  | 21988/30196 [45:37<18:54,  7.24it/s]

 73%|███████▎  | 21989/30196 [45:37<19:58,  6.85it/s]

 73%|███████▎  | 21990/30196 [45:38<18:46,  7.28it/s]

 73%|███████▎  | 21991/30196 [45:38<17:49,  7.67it/s]

 73%|███████▎  | 21993/30196 [45:38<15:56,  8.58it/s]

 73%|███████▎  | 21994/30196 [45:38<21:44,  6.29it/s]

 73%|███████▎  | 21995/30196 [45:38<21:57,  6.22it/s]

 73%|███████▎  | 21997/30196 [45:38<17:01,  8.03it/s]

 73%|███████▎  | 21998/30196 [45:39<17:12,  7.94it/s]

 73%|███████▎  | 21999/30196 [45:39<17:32,  7.79it/s]

 73%|███████▎  | 22001/30196 [45:39<14:50,  9.20it/s]

 73%|███████▎  | 22003/30196 [45:39<14:25,  9.46it/s]

 73%|███████▎  | 22004/30196 [45:39<14:25,  9.47it/s]

 73%|███████▎  | 22006/30196 [45:39<12:06, 11.27it/s]

 73%|███████▎  | 22008/30196 [45:40<13:56,  9.78it/s]

 73%|███████▎  | 22010/30196 [45:40<13:03, 10.45it/s]

 73%|███████▎  | 22012/30196 [45:40<17:12,  7.93it/s]

 73%|███████▎  | 22013/30196 [45:40<18:19,  7.44it/s]

 73%|███████▎  | 22015/30196 [45:41<17:21,  7.86it/s]

 73%|███████▎  | 22016/30196 [45:41<19:38,  6.94it/s]

 73%|███████▎  | 22017/30196 [45:41<19:13,  7.09it/s]

 73%|███████▎  | 22018/30196 [45:41<19:26,  7.01it/s]

 73%|███████▎  | 22019/30196 [45:41<18:06,  7.53it/s]

 73%|███████▎  | 22021/30196 [45:41<16:06,  8.46it/s]

 73%|███████▎  | 22023/30196 [45:41<14:33,  9.36it/s]

 73%|███████▎  | 22025/30196 [45:42<12:30, 10.89it/s]

 73%|███████▎  | 22027/30196 [45:42<14:08,  9.63it/s]

 73%|███████▎  | 22029/30196 [45:42<15:18,  8.89it/s]

 73%|███████▎  | 22030/30196 [45:42<16:40,  8.16it/s]

 73%|███████▎  | 22032/30196 [45:42<13:39,  9.96it/s]

 73%|███████▎  | 22034/30196 [45:43<15:05,  9.01it/s]

 73%|███████▎  | 22035/30196 [45:43<17:33,  7.74it/s]

 73%|███████▎  | 22036/30196 [45:43<18:59,  7.16it/s]

 73%|███████▎  | 22037/30196 [45:43<18:56,  7.18it/s]

 73%|███████▎  | 22038/30196 [45:43<17:45,  7.65it/s]

 73%|███████▎  | 22039/30196 [45:44<21:14,  6.40it/s]

 73%|███████▎  | 22041/30196 [45:44<17:32,  7.74it/s]

 73%|███████▎  | 22043/30196 [45:44<14:14,  9.55it/s]

 73%|███████▎  | 22045/30196 [45:44<13:04, 10.38it/s]

 73%|███████▎  | 22047/30196 [45:44<12:15, 11.08it/s]

 73%|███████▎  | 22049/30196 [45:44<13:52,  9.78it/s]

 73%|███████▎  | 22051/30196 [45:45<12:23, 10.96it/s]

 73%|███████▎  | 22053/30196 [45:45<19:19,  7.02it/s]

 73%|███████▎  | 22054/30196 [45:45<19:27,  6.97it/s]

 73%|███████▎  | 22056/30196 [45:45<15:32,  8.73it/s]

 73%|███████▎  | 22058/30196 [45:46<15:47,  8.59it/s]

 73%|███████▎  | 22060/30196 [45:46<15:42,  8.63it/s]

 73%|███████▎  | 22061/30196 [45:46<15:33,  8.71it/s]

 73%|███████▎  | 22063/30196 [45:46<16:46,  8.08it/s]

 73%|███████▎  | 22064/30196 [45:46<16:40,  8.13it/s]

 73%|███████▎  | 22066/30196 [45:46<13:49,  9.80it/s]

 73%|███████▎  | 22068/30196 [45:47<14:01,  9.66it/s]

 73%|███████▎  | 22071/30196 [45:47<12:15, 11.05it/s]

 73%|███████▎  | 22073/30196 [45:47<13:09, 10.29it/s]

 73%|███████▎  | 22075/30196 [45:47<12:18, 11.00it/s]

 73%|███████▎  | 22077/30196 [45:47<11:41, 11.57it/s]

 73%|███████▎  | 22079/30196 [45:48<12:14, 11.04it/s]

 73%|███████▎  | 22081/30196 [45:48<17:28,  7.74it/s]

 73%|███████▎  | 22082/30196 [45:48<17:01,  7.94it/s]

 73%|███████▎  | 22083/30196 [45:48<18:29,  7.31it/s]

 73%|███████▎  | 22084/30196 [45:48<17:41,  7.64it/s]

 73%|███████▎  | 22086/30196 [45:49<17:09,  7.88it/s]

 73%|███████▎  | 22088/30196 [45:49<16:26,  8.22it/s]

 73%|███████▎  | 22090/30196 [45:49<13:43,  9.84it/s]

 73%|███████▎  | 22092/30196 [45:50<31:33,  4.28it/s]

 73%|███████▎  | 22093/30196 [45:50<28:25,  4.75it/s]

 73%|███████▎  | 22095/30196 [45:50<23:43,  5.69it/s]

 73%|███████▎  | 22096/30196 [45:51<22:37,  5.97it/s]

 73%|███████▎  | 22097/30196 [45:51<20:54,  6.46it/s]

 73%|███████▎  | 22098/30196 [45:51<22:42,  5.94it/s]

 73%|███████▎  | 22099/30196 [45:51<21:32,  6.26it/s]

 73%|███████▎  | 22100/30196 [45:51<21:47,  6.19it/s]

 73%|███████▎  | 22102/30196 [45:52<24:47,  5.44it/s]

 73%|███████▎  | 22104/30196 [45:52<18:08,  7.44it/s]

 73%|███████▎  | 22105/30196 [45:52<19:09,  7.04it/s]

 73%|███████▎  | 22106/30196 [45:52<24:12,  5.57it/s]

 73%|███████▎  | 22107/30196 [45:52<22:53,  5.89it/s]

 73%|███████▎  | 22108/30196 [45:52<21:28,  6.28it/s]

 73%|███████▎  | 22109/30196 [45:53<20:25,  6.60it/s]

 73%|███████▎  | 22110/30196 [45:53<21:15,  6.34it/s]

 73%|███████▎  | 22111/30196 [45:53<20:50,  6.46it/s]

 73%|███████▎  | 22112/30196 [45:53<19:05,  7.06it/s]

 73%|███████▎  | 22113/30196 [45:53<18:49,  7.15it/s]

 73%|███████▎  | 22114/30196 [45:53<17:35,  7.65it/s]

 73%|███████▎  | 22115/30196 [45:54<25:43,  5.23it/s]

 73%|███████▎  | 22116/30196 [45:54<28:52,  4.66it/s]

 73%|███████▎  | 22117/30196 [45:54<27:01,  4.98it/s]

 73%|███████▎  | 22119/30196 [45:54<21:28,  6.27it/s]

 73%|███████▎  | 22121/30196 [45:54<19:55,  6.76it/s]

 73%|███████▎  | 22122/30196 [45:55<22:25,  6.00it/s]

 73%|███████▎  | 22123/30196 [45:55<21:15,  6.33it/s]

 73%|███████▎  | 22124/30196 [45:55<24:36,  5.47it/s]

 73%|███████▎  | 22125/30196 [45:55<23:07,  5.82it/s]

 73%|███████▎  | 22127/30196 [45:55<18:54,  7.11it/s]

 73%|███████▎  | 22128/30196 [45:56<17:53,  7.51it/s]

 73%|███████▎  | 22130/30196 [45:56<15:04,  8.92it/s]

 73%|███████▎  | 22131/30196 [45:56<16:47,  8.01it/s]

 73%|███████▎  | 22133/30196 [45:56<13:26, 10.00it/s]

 73%|███████▎  | 22135/30196 [45:56<14:51,  9.05it/s]

 73%|███████▎  | 22136/30196 [45:56<15:32,  8.65it/s]

 73%|███████▎  | 22138/30196 [45:57<13:02, 10.29it/s]

 73%|███████▎  | 22140/30196 [45:57<14:27,  9.29it/s]

 73%|███████▎  | 22142/30196 [45:57<14:01,  9.57it/s]

 73%|███████▎  | 22144/30196 [45:57<14:37,  9.18it/s]

 73%|███████▎  | 22145/30196 [45:57<15:11,  8.84it/s]

 73%|███████▎  | 22147/30196 [45:58<16:36,  8.07it/s]

 73%|███████▎  | 22148/30196 [45:58<16:05,  8.33it/s]

 73%|███████▎  | 22149/30196 [45:58<16:55,  7.92it/s]

 73%|███████▎  | 22151/30196 [45:58<15:50,  8.46it/s]

 73%|███████▎  | 22153/30196 [45:58<13:02, 10.28it/s]

 73%|███████▎  | 22155/30196 [45:58<12:23, 10.82it/s]

 73%|███████▎  | 22157/30196 [45:59<11:13, 11.94it/s]

 73%|███████▎  | 22159/30196 [45:59<11:36, 11.55it/s]

 73%|███████▎  | 22161/30196 [45:59<12:37, 10.60it/s]

 73%|███████▎  | 22163/30196 [45:59<13:01, 10.29it/s]

 73%|███████▎  | 22165/30196 [45:59<12:06, 11.05it/s]

 73%|███████▎  | 22167/30196 [46:00<14:08,  9.46it/s]

 73%|███████▎  | 22169/30196 [46:00<14:01,  9.54it/s]

 73%|███████▎  | 22171/30196 [46:00<14:57,  8.94it/s]

 73%|███████▎  | 22172/30196 [46:00<17:09,  7.79it/s]

 73%|███████▎  | 22174/30196 [46:00<16:03,  8.33it/s]

 73%|███████▎  | 22175/30196 [46:01<18:16,  7.31it/s]

 73%|███████▎  | 22176/30196 [46:01<20:31,  6.51it/s]

 73%|███████▎  | 22177/30196 [46:01<22:22,  5.97it/s]

 73%|███████▎  | 22178/30196 [46:01<20:25,  6.54it/s]

 73%|███████▎  | 22179/30196 [46:02<33:03,  4.04it/s]

 73%|███████▎  | 22180/30196 [46:02<33:27,  3.99it/s]

 73%|███████▎  | 22181/30196 [46:02<30:42,  4.35it/s]

 73%|███████▎  | 22182/30196 [46:03<1:03:38,  2.10it/s]

 73%|███████▎  | 22184/30196 [46:03<38:33,  3.46it/s]

 73%|███████▎  | 22185/30196 [46:03<33:58,  3.93it/s]

 73%|███████▎  | 22187/30196 [46:04<26:29,  5.04it/s]

 73%|███████▎  | 22188/30196 [46:04<26:59,  4.95it/s]

 73%|███████▎  | 22189/30196 [46:04<25:10,  5.30it/s]

 73%|███████▎  | 22191/30196 [46:04<18:30,  7.21it/s]

 73%|███████▎  | 22193/30196 [46:04<14:50,  8.99it/s]

 74%|███████▎  | 22195/30196 [46:04<12:04, 11.04it/s]

 74%|███████▎  | 22197/30196 [46:05<14:01,  9.51it/s]

 74%|███████▎  | 22199/30196 [46:05<15:19,  8.70it/s]

 74%|███████▎  | 22201/30196 [46:05<13:11, 10.11it/s]

 74%|███████▎  | 22203/30196 [46:05<12:19, 10.81it/s]

 74%|███████▎  | 22205/30196 [46:05<12:57, 10.28it/s]

 74%|███████▎  | 22207/30196 [46:06<13:32,  9.84it/s]

 74%|███████▎  | 22209/30196 [46:06<15:00,  8.87it/s]

 74%|███████▎  | 22211/30196 [46:06<13:06, 10.15it/s]

 74%|███████▎  | 22213/30196 [46:06<11:31, 11.55it/s]

 74%|███████▎  | 22215/30196 [46:07<14:46,  9.00it/s]

 74%|███████▎  | 22217/30196 [46:07<16:20,  8.14it/s]

 74%|███████▎  | 22219/30196 [46:07<19:41,  6.75it/s]

 74%|███████▎  | 22221/30196 [46:07<17:36,  7.55it/s]

 74%|███████▎  | 22223/30196 [46:08<15:25,  8.62it/s]

 74%|███████▎  | 22225/30196 [46:08<15:12,  8.73it/s]

 74%|███████▎  | 22227/30196 [46:08<14:25,  9.20it/s]

 74%|███████▎  | 22229/30196 [46:08<13:07, 10.12it/s]

 74%|███████▎  | 22231/30196 [46:08<11:54, 11.16it/s]

 74%|███████▎  | 22233/30196 [46:09<15:35,  8.51it/s]

 74%|███████▎  | 22235/30196 [46:09<16:10,  8.21it/s]

 74%|███████▎  | 22237/30196 [46:09<14:19,  9.26it/s]

 74%|███████▎  | 22239/30196 [46:09<13:55,  9.52it/s]

 74%|███████▎  | 22241/30196 [46:10<14:51,  8.93it/s]

 74%|███████▎  | 22242/30196 [46:10<15:22,  8.62it/s]

 74%|███████▎  | 22243/30196 [46:10<15:46,  8.40it/s]

 74%|███████▎  | 22245/30196 [46:10<12:40, 10.45it/s]

 74%|███████▎  | 22247/30196 [46:10<14:43,  9.00it/s]

 74%|███████▎  | 22249/30196 [46:10<13:43,  9.65it/s]

 74%|███████▎  | 22251/30196 [46:11<15:37,  8.48it/s]

 74%|███████▎  | 22252/30196 [46:11<17:55,  7.38it/s]

 74%|███████▎  | 22254/30196 [46:11<15:44,  8.41it/s]

 74%|███████▎  | 22255/30196 [46:11<16:28,  8.04it/s]

 74%|███████▎  | 22257/30196 [46:11<16:33,  7.99it/s]

 74%|███████▎  | 22259/30196 [46:12<16:10,  8.17it/s]

 74%|███████▎  | 22260/30196 [46:12<16:31,  8.01it/s]

 74%|███████▎  | 22261/30196 [46:12<17:00,  7.78it/s]

 74%|███████▎  | 22262/30196 [46:12<16:16,  8.13it/s]

 74%|███████▎  | 22263/30196 [46:12<16:31,  8.00it/s]

 74%|███████▎  | 22265/30196 [46:13<17:01,  7.76it/s]

 74%|███████▎  | 22267/30196 [46:13<14:14,  9.28it/s]

 74%|███████▎  | 22268/30196 [46:13<14:50,  8.90it/s]

 74%|███████▎  | 22269/30196 [46:13<20:12,  6.54it/s]

 74%|███████▍  | 22270/30196 [46:13<18:47,  7.03it/s]

 74%|███████▍  | 22272/30196 [46:13<14:59,  8.81it/s]

 74%|███████▍  | 22274/30196 [46:14<14:29,  9.11it/s]

 74%|███████▍  | 22275/30196 [46:14<14:20,  9.21it/s]

 74%|███████▍  | 22277/30196 [46:14<11:29, 11.48it/s]

 74%|███████▍  | 22279/30196 [46:14<13:36,  9.69it/s]

 74%|███████▍  | 22281/30196 [46:14<17:46,  7.42it/s]

 74%|███████▍  | 22282/30196 [46:15<17:40,  7.46it/s]

 74%|███████▍  | 22284/30196 [46:15<14:42,  8.96it/s]

 74%|███████▍  | 22286/30196 [46:15<13:40,  9.64it/s]

 74%|███████▍  | 22288/30196 [46:15<12:24, 10.62it/s]

 74%|███████▍  | 22290/30196 [46:15<12:15, 10.75it/s]

 74%|███████▍  | 22292/30196 [46:15<11:35, 11.37it/s]

 74%|███████▍  | 22294/30196 [46:15<11:07, 11.84it/s]

 74%|███████▍  | 22296/30196 [46:16<10:58, 12.00it/s]

 74%|███████▍  | 22298/30196 [46:16<13:18,  9.89it/s]

 74%|███████▍  | 22300/30196 [46:16<13:03, 10.08it/s]

 74%|███████▍  | 22302/30196 [46:16<15:28,  8.50it/s]

 74%|███████▍  | 22304/30196 [46:17<13:57,  9.42it/s]

 74%|███████▍  | 22306/30196 [46:17<13:32,  9.71it/s]

 74%|███████▍  | 22308/30196 [46:17<12:31, 10.49it/s]

 74%|███████▍  | 22310/30196 [46:17<15:30,  8.48it/s]

 74%|███████▍  | 22311/30196 [46:17<16:56,  7.75it/s]

 74%|███████▍  | 22313/30196 [46:18<15:14,  8.62it/s]

 74%|███████▍  | 22314/30196 [46:18<16:40,  7.88it/s]

 74%|███████▍  | 22316/30196 [46:18<14:33,  9.02it/s]

 74%|███████▍  | 22318/30196 [46:18<13:53,  9.45it/s]

 74%|███████▍  | 22319/30196 [46:18<17:36,  7.46it/s]

 74%|███████▍  | 22321/30196 [46:19<14:51,  8.83it/s]

 74%|███████▍  | 22322/30196 [46:19<16:35,  7.91it/s]

 74%|███████▍  | 22323/30196 [46:19<17:51,  7.35it/s]

 74%|███████▍  | 22324/30196 [46:19<17:50,  7.35it/s]

 74%|███████▍  | 22326/30196 [46:19<15:27,  8.48it/s]

 74%|███████▍  | 22327/30196 [46:19<15:13,  8.61it/s]

 74%|███████▍  | 22328/30196 [46:20<16:50,  7.79it/s]

 74%|███████▍  | 22330/30196 [46:20<15:07,  8.67it/s]

 74%|███████▍  | 22331/30196 [46:20<15:40,  8.37it/s]

 74%|███████▍  | 22332/30196 [46:20<15:19,  8.55it/s]

 74%|███████▍  | 22334/30196 [46:20<14:14,  9.20it/s]

 74%|███████▍  | 22336/30196 [46:20<16:26,  7.97it/s]

 74%|███████▍  | 22338/30196 [46:21<19:34,  6.69it/s]

 74%|███████▍  | 22339/30196 [46:21<19:27,  6.73it/s]

 74%|███████▍  | 22341/30196 [46:21<15:54,  8.23it/s]

 74%|███████▍  | 22342/30196 [46:21<17:09,  7.63it/s]

 74%|███████▍  | 22343/30196 [46:21<17:37,  7.43it/s]

 74%|███████▍  | 22344/30196 [46:22<17:31,  7.47it/s]

 74%|███████▍  | 22345/30196 [46:22<17:27,  7.50it/s]

 74%|███████▍  | 22346/30196 [46:22<16:25,  7.96it/s]

 74%|███████▍  | 22347/30196 [46:22<16:59,  7.70it/s]

 74%|███████▍  | 22348/30196 [46:22<16:01,  8.17it/s]

 74%|███████▍  | 22349/30196 [46:22<15:18,  8.54it/s]

 74%|███████▍  | 22351/30196 [46:22<15:47,  8.28it/s]

 74%|███████▍  | 22353/30196 [46:23<13:00, 10.05it/s]

 74%|███████▍  | 22355/30196 [46:23<12:52, 10.15it/s]

 74%|███████▍  | 22357/30196 [46:23<14:31,  9.00it/s]

 74%|███████▍  | 22358/30196 [46:23<15:01,  8.70it/s]

 74%|███████▍  | 22359/30196 [46:23<16:45,  7.79it/s]

 74%|███████▍  | 22360/30196 [46:23<16:01,  8.15it/s]

 74%|███████▍  | 22361/30196 [46:24<16:38,  7.85it/s]

 74%|███████▍  | 22362/30196 [46:24<15:51,  8.23it/s]

 74%|███████▍  | 22364/30196 [46:24<13:16,  9.83it/s]

 74%|███████▍  | 22365/30196 [46:24<14:56,  8.74it/s]

 74%|███████▍  | 22366/30196 [46:24<15:47,  8.27it/s]

 74%|███████▍  | 22367/30196 [46:24<17:45,  7.35it/s]

 74%|███████▍  | 22368/30196 [46:24<18:10,  7.18it/s]

 74%|███████▍  | 22370/30196 [46:25<14:17,  9.13it/s]

 74%|███████▍  | 22371/30196 [46:25<16:28,  7.92it/s]

 74%|███████▍  | 22372/30196 [46:25<24:29,  5.32it/s]

 74%|███████▍  | 22374/30196 [46:25<19:34,  6.66it/s]

 74%|███████▍  | 22376/30196 [46:25<15:43,  8.28it/s]

 74%|███████▍  | 22378/30196 [46:26<15:00,  8.68it/s]

 74%|███████▍  | 22380/30196 [46:26<14:06,  9.23it/s]

 74%|███████▍  | 22381/30196 [46:26<15:37,  8.34it/s]

 74%|███████▍  | 22382/30196 [46:26<15:50,  8.22it/s]

 74%|███████▍  | 22384/30196 [46:26<12:28, 10.44it/s]

 74%|███████▍  | 22386/30196 [46:27<15:18,  8.51it/s]

 74%|███████▍  | 22387/30196 [46:27<25:15,  5.15it/s]

 74%|███████▍  | 22389/30196 [46:27<20:57,  6.21it/s]

 74%|███████▍  | 22391/30196 [46:27<16:37,  7.83it/s]

 74%|███████▍  | 22393/30196 [46:28<16:05,  8.08it/s]

 74%|███████▍  | 22395/30196 [46:28<14:19,  9.08it/s]

 74%|███████▍  | 22397/30196 [46:28<13:31,  9.61it/s]

 74%|███████▍  | 22399/30196 [46:28<12:39, 10.26it/s]

 74%|███████▍  | 22401/30196 [46:28<14:13,  9.13it/s]

 74%|███████▍  | 22402/30196 [46:29<14:06,  9.21it/s]

 74%|███████▍  | 22403/30196 [46:29<14:01,  9.26it/s]

 74%|███████▍  | 22405/30196 [46:29<13:59,  9.28it/s]

 74%|███████▍  | 22407/30196 [46:29<14:06,  9.20it/s]

 74%|███████▍  | 22408/30196 [46:29<14:54,  8.71it/s]

 74%|███████▍  | 22409/30196 [46:29<15:39,  8.29it/s]

 74%|███████▍  | 22410/30196 [46:30<16:29,  7.87it/s]

 74%|███████▍  | 22412/30196 [46:30<16:45,  7.74it/s]

 74%|███████▍  | 22414/30196 [46:30<13:34,  9.56it/s]

 74%|███████▍  | 22416/30196 [46:30<13:48,  9.39it/s]

 74%|███████▍  | 22418/30196 [46:30<13:08,  9.86it/s]

 74%|███████▍  | 22420/30196 [46:31<19:04,  6.79it/s]

 74%|███████▍  | 22421/30196 [46:31<20:49,  6.22it/s]

 74%|███████▍  | 22423/30196 [46:31<16:14,  7.97it/s]

 74%|███████▍  | 22425/30196 [46:31<13:47,  9.39it/s]

 74%|███████▍  | 22427/30196 [46:32<22:00,  5.88it/s]

 74%|███████▍  | 22428/30196 [46:32<21:54,  5.91it/s]

 74%|███████▍  | 22430/30196 [46:32<17:59,  7.19it/s]

 74%|███████▍  | 22432/30196 [46:32<15:40,  8.25it/s]

 74%|███████▍  | 22434/30196 [46:33<15:10,  8.53it/s]

 74%|███████▍  | 22436/30196 [46:33<13:09,  9.83it/s]

 74%|███████▍  | 22438/30196 [46:33<15:05,  8.56it/s]

 74%|███████▍  | 22439/30196 [46:33<15:30,  8.33it/s]

 74%|███████▍  | 22440/30196 [46:33<15:48,  8.18it/s]

 74%|███████▍  | 22441/30196 [46:33<15:16,  8.46it/s]

 74%|███████▍  | 22443/30196 [46:34<12:59,  9.94it/s]

 74%|███████▍  | 22445/30196 [46:34<12:48, 10.08it/s]

 74%|███████▍  | 22447/30196 [46:34<12:18, 10.49it/s]

 74%|███████▍  | 22449/30196 [46:34<12:11, 10.59it/s]

 74%|███████▍  | 22451/30196 [46:34<13:34,  9.51it/s]

 74%|███████▍  | 22452/30196 [46:35<14:34,  8.85it/s]

 74%|███████▍  | 22454/30196 [46:35<12:43, 10.14it/s]

 74%|███████▍  | 22456/30196 [46:35<15:51,  8.14it/s]

 74%|███████▍  | 22457/30196 [46:35<17:04,  7.55it/s]

 74%|███████▍  | 22458/30196 [46:35<18:06,  7.12it/s]

 74%|███████▍  | 22460/30196 [46:36<17:29,  7.37it/s]

 74%|███████▍  | 22461/30196 [46:36<17:19,  7.44it/s]

 74%|███████▍  | 22462/30196 [46:36<17:29,  7.37it/s]

 74%|███████▍  | 22464/30196 [46:36<16:24,  7.86it/s]

 74%|███████▍  | 22465/30196 [46:36<16:39,  7.73it/s]

 74%|███████▍  | 22466/30196 [46:36<17:46,  7.25it/s]

 74%|███████▍  | 22468/30196 [46:37<16:35,  7.76it/s]

 74%|███████▍  | 22470/30196 [46:37<15:46,  8.16it/s]

 74%|███████▍  | 22472/30196 [46:37<13:57,  9.23it/s]

 74%|███████▍  | 22474/30196 [46:37<11:29, 11.21it/s]

 74%|███████▍  | 22476/30196 [46:37<12:58,  9.92it/s]

 74%|███████▍  | 22478/30196 [46:38<13:58,  9.21it/s]

 74%|███████▍  | 22480/30196 [46:38<13:16,  9.69it/s]

 74%|███████▍  | 22482/30196 [46:38<11:35, 11.10it/s]

 74%|███████▍  | 22484/30196 [46:38<11:24, 11.27it/s]

 74%|███████▍  | 22486/30196 [46:39<16:06,  7.98it/s]

 74%|███████▍  | 22487/30196 [46:39<16:26,  7.81it/s]

 74%|███████▍  | 22490/30196 [46:39<13:24,  9.58it/s]

 74%|███████▍  | 22492/30196 [46:39<11:28, 11.19it/s]

 74%|███████▍  | 22494/30196 [46:39<13:48,  9.29it/s]

 75%|███████▍  | 22497/30196 [46:40<12:17, 10.44it/s]

 75%|███████▍  | 22499/30196 [46:40<12:13, 10.49it/s]

 75%|███████▍  | 22501/30196 [46:40<13:57,  9.19it/s]

 75%|███████▍  | 22503/30196 [46:40<14:37,  8.77it/s]

 75%|███████▍  | 22504/30196 [46:40<14:30,  8.84it/s]

 75%|███████▍  | 22505/30196 [46:41<16:51,  7.61it/s]

 75%|███████▍  | 22507/30196 [46:41<17:15,  7.43it/s]

 75%|███████▍  | 22509/30196 [46:41<15:07,  8.47it/s]

 75%|███████▍  | 22511/30196 [46:41<12:59,  9.86it/s]

 75%|███████▍  | 22513/30196 [46:41<12:58,  9.87it/s]

 75%|███████▍  | 22516/30196 [46:42<10:13, 12.53it/s]

 75%|███████▍  | 22518/30196 [46:42<12:12, 10.48it/s]

 75%|███████▍  | 22520/30196 [46:42<14:31,  8.80it/s]

 75%|███████▍  | 22522/30196 [46:42<17:15,  7.41it/s]

 75%|███████▍  | 22523/30196 [46:43<17:11,  7.44it/s]

 75%|███████▍  | 22525/30196 [46:43<14:19,  8.92it/s]

 75%|███████▍  | 22527/30196 [46:43<12:52,  9.93it/s]

 75%|███████▍  | 22529/30196 [46:44<22:33,  5.67it/s]

 75%|███████▍  | 22531/30196 [46:44<20:11,  6.33it/s]

 75%|███████▍  | 22533/30196 [46:44<18:38,  6.85it/s]

 75%|███████▍  | 22535/30196 [46:44<16:47,  7.61it/s]

 75%|███████▍  | 22537/30196 [46:44<15:56,  8.01it/s]

 75%|███████▍  | 22538/30196 [46:45<16:27,  7.75it/s]

 75%|███████▍  | 22539/30196 [46:45<30:07,  4.24it/s]

 75%|███████▍  | 22541/30196 [46:46<25:09,  5.07it/s]

 75%|███████▍  | 22543/30196 [46:46<20:26,  6.24it/s]

 75%|███████▍  | 22545/30196 [46:46<17:23,  7.33it/s]

 75%|███████▍  | 22547/30196 [46:46<16:22,  7.79it/s]

 75%|███████▍  | 22549/30196 [46:46<14:08,  9.02it/s]

 75%|███████▍  | 22551/30196 [46:47<15:26,  8.25it/s]

 75%|███████▍  | 22552/30196 [46:47<22:17,  5.71it/s]

 75%|███████▍  | 22554/30196 [46:47<17:00,  7.49it/s]

 75%|███████▍  | 22556/30196 [46:47<16:44,  7.61it/s]

 75%|███████▍  | 22557/30196 [46:48<20:04,  6.34it/s]

 75%|███████▍  | 22558/30196 [46:48<19:21,  6.58it/s]

 75%|███████▍  | 22559/30196 [46:48<21:01,  6.05it/s]

 75%|███████▍  | 22560/30196 [46:48<21:04,  6.04it/s]

 75%|███████▍  | 22562/30196 [46:48<18:50,  6.76it/s]

 75%|███████▍  | 22564/30196 [46:48<15:11,  8.37it/s]

 75%|███████▍  | 22565/30196 [46:49<18:44,  6.79it/s]

 75%|███████▍  | 22567/30196 [46:49<15:57,  7.97it/s]

 75%|███████▍  | 22570/30196 [46:49<11:57, 10.63it/s]

 75%|███████▍  | 22572/30196 [46:50<17:09,  7.41it/s]

 75%|███████▍  | 22573/30196 [46:50<16:29,  7.71it/s]

 75%|███████▍  | 22574/30196 [46:50<17:28,  7.27it/s]

 75%|███████▍  | 22575/30196 [46:50<16:41,  7.61it/s]

 75%|███████▍  | 22576/30196 [46:50<19:24,  6.54it/s]

 75%|███████▍  | 22578/30196 [46:50<14:56,  8.50it/s]

 75%|███████▍  | 22580/30196 [46:51<15:52,  7.99it/s]

 75%|███████▍  | 22582/30196 [46:51<13:05,  9.69it/s]

 75%|███████▍  | 22584/30196 [46:51<14:50,  8.54it/s]

 75%|███████▍  | 22585/30196 [46:51<16:15,  7.81it/s]

 75%|███████▍  | 22587/30196 [46:51<14:28,  8.76it/s]

 75%|███████▍  | 22588/30196 [46:51<14:15,  8.90it/s]

 75%|███████▍  | 22589/30196 [46:52<23:15,  5.45it/s]

 75%|███████▍  | 22590/30196 [46:52<21:46,  5.82it/s]

 75%|███████▍  | 22591/30196 [46:52<20:43,  6.11it/s]

 75%|███████▍  | 22592/30196 [46:52<24:19,  5.21it/s]

 75%|███████▍  | 22594/30196 [46:53<20:04,  6.31it/s]

 75%|███████▍  | 22596/30196 [46:53<15:15,  8.30it/s]

 75%|███████▍  | 22597/30196 [46:53<14:49,  8.55it/s]

 75%|███████▍  | 22598/30196 [46:53<14:26,  8.76it/s]

 75%|███████▍  | 22600/30196 [46:53<13:53,  9.11it/s]

 75%|███████▍  | 22601/30196 [46:53<14:35,  8.68it/s]

 75%|███████▍  | 22602/30196 [46:53<15:22,  8.24it/s]

 75%|███████▍  | 22603/30196 [46:54<16:12,  7.81it/s]

 75%|███████▍  | 22604/30196 [46:54<17:43,  7.14it/s]

 75%|███████▍  | 22606/30196 [46:54<15:57,  7.93it/s]

 75%|███████▍  | 22608/30196 [46:54<13:52,  9.12it/s]

 75%|███████▍  | 22610/30196 [46:54<12:32, 10.08it/s]

 75%|███████▍  | 22612/30196 [46:54<12:12, 10.36it/s]

 75%|███████▍  | 22614/30196 [46:55<11:36, 10.88it/s]

 75%|███████▍  | 22616/30196 [46:55<13:08,  9.61it/s]

 75%|███████▍  | 22617/30196 [46:55<13:09,  9.59it/s]

 75%|███████▍  | 22618/30196 [46:55<13:49,  9.13it/s]

 75%|███████▍  | 22620/30196 [46:55<12:33, 10.05it/s]

 75%|███████▍  | 22622/30196 [46:56<16:27,  7.67it/s]

 75%|███████▍  | 22624/30196 [46:56<15:11,  8.31it/s]

 75%|███████▍  | 22625/30196 [46:56<17:26,  7.23it/s]

 75%|███████▍  | 22626/30196 [46:56<16:39,  7.57it/s]

 75%|███████▍  | 22627/30196 [46:56<17:04,  7.39it/s]

 75%|███████▍  | 22628/30196 [46:56<17:03,  7.40it/s]

 75%|███████▍  | 22629/30196 [46:57<16:02,  7.86it/s]

 75%|███████▍  | 22630/30196 [46:57<17:22,  7.26it/s]

 75%|███████▍  | 22631/30196 [46:57<16:24,  7.68it/s]

 75%|███████▍  | 22632/30196 [46:57<15:28,  8.14it/s]

 75%|███████▍  | 22633/30196 [46:57<14:57,  8.43it/s]

 75%|███████▍  | 22635/30196 [46:57<13:44,  9.18it/s]

 75%|███████▍  | 22636/30196 [46:57<14:32,  8.66it/s]

 75%|███████▍  | 22637/30196 [46:58<17:33,  7.17it/s]

 75%|███████▍  | 22639/30196 [46:58<14:51,  8.47it/s]

 75%|███████▍  | 22641/30196 [46:58<12:52,  9.78it/s]

 75%|███████▍  | 22642/30196 [46:58<14:18,  8.80it/s]

 75%|███████▍  | 22643/30196 [46:58<16:11,  7.77it/s]

 75%|███████▍  | 22644/30196 [46:58<17:28,  7.20it/s]

 75%|███████▍  | 22645/30196 [46:59<19:39,  6.40it/s]

 75%|███████▍  | 22646/30196 [46:59<19:05,  6.59it/s]

 75%|███████▌  | 22647/30196 [46:59<18:28,  6.81it/s]

 75%|███████▌  | 22648/30196 [46:59<17:07,  7.35it/s]

 75%|███████▌  | 22649/30196 [46:59<16:54,  7.44it/s]

 75%|███████▌  | 22650/30196 [46:59<18:02,  6.97it/s]

 75%|███████▌  | 22651/30196 [47:00<19:07,  6.58it/s]

 75%|███████▌  | 22652/30196 [47:00<19:46,  6.36it/s]

 75%|███████▌  | 22653/30196 [47:00<18:58,  6.63it/s]

 75%|███████▌  | 22654/30196 [47:00<17:24,  7.22it/s]

 75%|███████▌  | 22656/30196 [47:00<18:07,  6.93it/s]

 75%|███████▌  | 22657/30196 [47:00<17:49,  7.05it/s]

 75%|███████▌  | 22659/30196 [47:01<16:55,  7.43it/s]

 75%|███████▌  | 22660/30196 [47:01<20:26,  6.14it/s]

 75%|███████▌  | 22662/30196 [47:01<16:20,  7.68it/s]

 75%|███████▌  | 22664/30196 [47:01<14:27,  8.68it/s]

 75%|███████▌  | 22666/30196 [47:01<12:08, 10.34it/s]

 75%|███████▌  | 22668/30196 [47:02<11:52, 10.57it/s]

 75%|███████▌  | 22670/30196 [47:02<15:57,  7.86it/s]

 75%|███████▌  | 22672/30196 [47:02<14:24,  8.70it/s]

 75%|███████▌  | 22674/30196 [47:02<15:38,  8.02it/s]

 75%|███████▌  | 22676/30196 [47:03<13:48,  9.08it/s]

 75%|███████▌  | 22678/30196 [47:03<17:20,  7.22it/s]

 75%|███████▌  | 22680/30196 [47:03<17:40,  7.09it/s]

 75%|███████▌  | 22681/30196 [47:03<16:51,  7.43it/s]

 75%|███████▌  | 22683/30196 [47:04<15:14,  8.21it/s]

 75%|███████▌  | 22684/30196 [47:04<15:51,  7.90it/s]

 75%|███████▌  | 22685/30196 [47:04<16:12,  7.72it/s]

 75%|███████▌  | 22686/30196 [47:04<21:16,  5.88it/s]

 75%|███████▌  | 22687/30196 [47:04<21:16,  5.88it/s]

 75%|███████▌  | 22688/30196 [47:05<23:04,  5.42it/s]

 75%|███████▌  | 22689/30196 [47:05<21:21,  5.86it/s]

 75%|███████▌  | 22690/30196 [47:05<23:02,  5.43it/s]

 75%|███████▌  | 22692/30196 [47:05<17:23,  7.19it/s]

 75%|███████▌  | 22693/30196 [47:05<16:48,  7.44it/s]

 75%|███████▌  | 22694/30196 [47:05<16:42,  7.48it/s]

 75%|███████▌  | 22695/30196 [47:05<15:54,  7.86it/s]

 75%|███████▌  | 22697/30196 [47:06<13:30,  9.25it/s]

 75%|███████▌  | 22699/30196 [47:06<14:10,  8.81it/s]

 75%|███████▌  | 22700/30196 [47:06<14:45,  8.47it/s]

 75%|███████▌  | 22701/30196 [47:06<18:51,  6.62it/s]

 75%|███████▌  | 22702/30196 [47:06<18:13,  6.86it/s]

 75%|███████▌  | 22703/30196 [47:06<16:50,  7.41it/s]

 75%|███████▌  | 22705/30196 [47:07<13:08,  9.50it/s]

 75%|███████▌  | 22708/30196 [47:07<09:34, 13.03it/s]

 75%|███████▌  | 22710/30196 [47:07<11:46, 10.60it/s]

 75%|███████▌  | 22712/30196 [47:07<12:11, 10.23it/s]

 75%|███████▌  | 22714/30196 [47:07<13:51,  9.00it/s]

 75%|███████▌  | 22716/30196 [47:08<12:21, 10.08it/s]

 75%|███████▌  | 22718/30196 [47:08<15:28,  8.05it/s]

 75%|███████▌  | 22719/30196 [47:08<17:17,  7.21it/s]

 75%|███████▌  | 22721/30196 [47:08<14:30,  8.59it/s]

 75%|███████▌  | 22723/30196 [47:09<15:08,  8.23it/s]

 75%|███████▌  | 22724/30196 [47:09<15:27,  8.06it/s]

 75%|███████▌  | 22726/30196 [47:09<13:53,  8.96it/s]

 75%|███████▌  | 22727/30196 [47:09<17:28,  7.13it/s]

 75%|███████▌  | 22728/30196 [47:09<16:32,  7.52it/s]

 75%|███████▌  | 22730/30196 [47:09<13:45,  9.04it/s]

 75%|███████▌  | 22731/30196 [47:10<13:44,  9.05it/s]

 75%|███████▌  | 22733/30196 [47:10<12:52,  9.66it/s]

 75%|███████▌  | 22735/30196 [47:10<20:59,  5.92it/s]

 75%|███████▌  | 22736/30196 [47:10<20:15,  6.14it/s]

 75%|███████▌  | 22738/30196 [47:11<18:32,  6.70it/s]

 75%|███████▌  | 22739/30196 [47:11<19:59,  6.22it/s]

 75%|███████▌  | 22741/30196 [47:11<16:03,  7.74it/s]

 75%|███████▌  | 22743/30196 [47:11<13:28,  9.22it/s]

 75%|███████▌  | 22745/30196 [47:11<14:58,  8.29it/s]

 75%|███████▌  | 22747/30196 [47:12<13:01,  9.53it/s]

 75%|███████▌  | 22749/30196 [47:12<14:31,  8.54it/s]

 75%|███████▌  | 22751/30196 [47:12<13:41,  9.06it/s]

 75%|███████▌  | 22752/30196 [47:12<15:08,  8.20it/s]

 75%|███████▌  | 22753/30196 [47:12<15:37,  7.94it/s]

 75%|███████▌  | 22755/30196 [47:13<14:19,  8.66it/s]

 75%|███████▌  | 22756/30196 [47:13<16:00,  7.75it/s]

 75%|███████▌  | 22758/30196 [47:13<13:22,  9.27it/s]

 75%|███████▌  | 22760/30196 [47:13<11:58, 10.35it/s]

 75%|███████▌  | 22762/30196 [47:13<11:01, 11.24it/s]

 75%|███████▌  | 22764/30196 [47:13<12:34,  9.85it/s]

 75%|███████▌  | 22766/30196 [47:14<11:31, 10.75it/s]

 75%|███████▌  | 22768/30196 [47:14<13:21,  9.27it/s]

 75%|███████▌  | 22770/30196 [47:14<11:44, 10.54it/s]

 75%|███████▌  | 22772/30196 [47:14<15:50,  7.81it/s]

 75%|███████▌  | 22773/30196 [47:15<16:17,  7.59it/s]

 75%|███████▌  | 22775/30196 [47:15<15:05,  8.19it/s]

 75%|███████▌  | 22776/30196 [47:15<15:41,  7.88it/s]

 75%|███████▌  | 22778/30196 [47:15<13:17,  9.30it/s]

 75%|███████▌  | 22780/30196 [47:15<12:52,  9.61it/s]

 75%|███████▌  | 22783/30196 [47:15<10:55, 11.32it/s]

 75%|███████▌  | 22785/30196 [47:16<13:09,  9.39it/s]

 75%|███████▌  | 22787/30196 [47:16<13:24,  9.21it/s]

 75%|███████▌  | 22788/30196 [47:16<13:25,  9.20it/s]

 75%|███████▌  | 22789/30196 [47:16<13:56,  8.85it/s]

 75%|███████▌  | 22790/30196 [47:16<15:28,  7.98it/s]

 75%|███████▌  | 22792/30196 [47:17<13:54,  8.87it/s]

 75%|███████▌  | 22793/30196 [47:17<14:47,  8.34it/s]

 75%|███████▌  | 22795/30196 [47:17<16:14,  7.59it/s]

 75%|███████▌  | 22796/30196 [47:17<15:38,  7.88it/s]

 76%|███████▌  | 22798/30196 [47:17<14:56,  8.26it/s]

 76%|███████▌  | 22799/30196 [47:17<14:29,  8.50it/s]

 76%|███████▌  | 22801/30196 [47:18<14:00,  8.80it/s]

 76%|███████▌  | 22803/30196 [47:18<12:31,  9.83it/s]

 76%|███████▌  | 22805/30196 [47:18<13:35,  9.07it/s]

 76%|███████▌  | 22807/30196 [47:18<13:47,  8.93it/s]

 76%|███████▌  | 22809/30196 [47:19<13:41,  8.99it/s]

 76%|███████▌  | 22810/30196 [47:19<13:33,  9.08it/s]

 76%|███████▌  | 22811/30196 [47:19<13:33,  9.08it/s]

 76%|███████▌  | 22812/30196 [47:19<16:37,  7.40it/s]

 76%|███████▌  | 22814/30196 [47:19<16:56,  7.26it/s]

 76%|███████▌  | 22815/30196 [47:19<18:01,  6.82it/s]

 76%|███████▌  | 22816/30196 [47:20<18:02,  6.82it/s]

 76%|███████▌  | 22818/30196 [47:20<14:44,  8.34it/s]

 76%|███████▌  | 22819/30196 [47:20<14:19,  8.58it/s]

 76%|███████▌  | 22820/30196 [47:20<18:39,  6.59it/s]

 76%|███████▌  | 22822/30196 [47:20<13:59,  8.78it/s]

 76%|███████▌  | 22824/30196 [47:20<13:52,  8.86it/s]

 76%|███████▌  | 22825/30196 [47:21<15:24,  7.97it/s]

 76%|███████▌  | 22827/30196 [47:21<12:26,  9.87it/s]

 76%|███████▌  | 22829/30196 [47:21<13:12,  9.29it/s]

 76%|███████▌  | 22831/30196 [47:21<13:17,  9.24it/s]

 76%|███████▌  | 22832/30196 [47:21<13:11,  9.31it/s]

 76%|███████▌  | 22833/30196 [47:22<24:32,  5.00it/s]

 76%|███████▌  | 22834/30196 [47:22<23:31,  5.22it/s]

 76%|███████▌  | 22836/30196 [47:22<19:32,  6.28it/s]

 76%|███████▌  | 22838/30196 [47:22<15:39,  7.83it/s]

 76%|███████▌  | 22839/30196 [47:23<15:46,  7.77it/s]

 76%|███████▌  | 22841/30196 [47:23<12:30,  9.80it/s]

 76%|███████▌  | 22843/30196 [47:23<12:13, 10.03it/s]

 76%|███████▌  | 22845/30196 [47:23<11:09, 10.98it/s]

 76%|███████▌  | 22847/30196 [47:23<11:52, 10.32it/s]

 76%|███████▌  | 22849/30196 [47:23<11:51, 10.33it/s]

 76%|███████▌  | 22851/30196 [47:24<13:37,  8.99it/s]

 76%|███████▌  | 22852/30196 [47:24<14:09,  8.64it/s]

 76%|███████▌  | 22853/30196 [47:24<13:54,  8.80it/s]

 76%|███████▌  | 22854/30196 [47:24<15:23,  7.95it/s]

 76%|███████▌  | 22855/30196 [47:24<15:40,  7.80it/s]

 76%|███████▌  | 22856/30196 [47:24<16:14,  7.54it/s]

 76%|███████▌  | 22857/30196 [47:24<15:15,  8.01it/s]

 76%|███████▌  | 22858/30196 [47:25<18:48,  6.50it/s]

 76%|███████▌  | 22860/30196 [47:25<14:55,  8.19it/s]

 76%|███████▌  | 22862/30196 [47:25<14:55,  8.19it/s]

 76%|███████▌  | 22863/30196 [47:25<16:26,  7.43it/s]

 76%|███████▌  | 22865/30196 [47:25<13:01,  9.38it/s]

 76%|███████▌  | 22867/30196 [47:26<14:15,  8.57it/s]

 76%|███████▌  | 22868/30196 [47:26<13:58,  8.74it/s]

 76%|███████▌  | 22870/30196 [47:26<13:12,  9.25it/s]

 76%|███████▌  | 22872/30196 [47:26<11:19, 10.78it/s]

 76%|███████▌  | 22874/30196 [47:26<11:13, 10.87it/s]

 76%|███████▌  | 22876/30196 [47:27<12:38,  9.64it/s]

 76%|███████▌  | 22878/30196 [47:27<15:32,  7.85it/s]

 76%|███████▌  | 22880/30196 [47:27<16:52,  7.23it/s]

 76%|███████▌  | 22881/30196 [47:27<16:07,  7.56it/s]

 76%|███████▌  | 22883/30196 [47:27<13:57,  8.73it/s]

 76%|███████▌  | 22884/30196 [47:28<15:09,  8.04it/s]

 76%|███████▌  | 22885/30196 [47:28<15:18,  7.96it/s]

 76%|███████▌  | 22886/30196 [47:28<14:43,  8.28it/s]

 76%|███████▌  | 22887/30196 [47:28<15:01,  8.10it/s]

 76%|███████▌  | 22889/30196 [47:28<13:44,  8.87it/s]

 76%|███████▌  | 22891/30196 [47:28<11:13, 10.85it/s]

 76%|███████▌  | 22893/30196 [47:29<13:39,  8.91it/s]

 76%|███████▌  | 22895/30196 [47:29<14:05,  8.63it/s]

 76%|███████▌  | 22897/30196 [47:29<12:08, 10.02it/s]

 76%|███████▌  | 22899/30196 [47:29<13:20,  9.11it/s]

 76%|███████▌  | 22901/30196 [47:30<14:13,  8.55it/s]

 76%|███████▌  | 22902/30196 [47:30<13:58,  8.70it/s]

 76%|███████▌  | 22904/30196 [47:30<12:21,  9.83it/s]

 76%|███████▌  | 22906/30196 [47:30<11:20, 10.72it/s]

 76%|███████▌  | 22908/30196 [47:30<11:34, 10.49it/s]

 76%|███████▌  | 22910/30196 [47:30<11:55, 10.19it/s]

 76%|███████▌  | 22912/30196 [47:31<11:17, 10.75it/s]

 76%|███████▌  | 22914/30196 [47:31<12:28,  9.73it/s]

 76%|███████▌  | 22916/30196 [47:31<14:27,  8.39it/s]

 76%|███████▌  | 22917/30196 [47:31<14:08,  8.57it/s]

 76%|███████▌  | 22918/30196 [47:31<14:44,  8.23it/s]

 76%|███████▌  | 22920/30196 [47:32<14:57,  8.11it/s]

 76%|███████▌  | 22922/30196 [47:32<13:10,  9.20it/s]

 76%|███████▌  | 22923/30196 [47:32<13:51,  8.75it/s]

 76%|███████▌  | 22924/30196 [47:32<13:44,  8.83it/s]

 76%|███████▌  | 22926/30196 [47:32<18:45,  6.46it/s]

 76%|███████▌  | 22927/30196 [47:33<18:24,  6.58it/s]

 76%|███████▌  | 22929/30196 [47:33<17:49,  6.79it/s]

 76%|███████▌  | 22930/30196 [47:33<16:52,  7.17it/s]

 76%|███████▌  | 22931/30196 [47:33<18:55,  6.40it/s]

 76%|███████▌  | 22932/30196 [47:33<18:07,  6.68it/s]

 76%|███████▌  | 22934/30196 [47:33<14:44,  8.21it/s]

 76%|███████▌  | 22936/30196 [47:34<13:14,  9.14it/s]

 76%|███████▌  | 22938/30196 [47:34<12:58,  9.33it/s]

 76%|███████▌  | 22940/30196 [47:34<12:08,  9.96it/s]

 76%|███████▌  | 22942/30196 [47:34<12:32,  9.64it/s]

 76%|███████▌  | 22943/30196 [47:35<17:03,  7.09it/s]

 76%|███████▌  | 22944/30196 [47:35<17:52,  6.76it/s]

 76%|███████▌  | 22946/30196 [47:35<15:10,  7.97it/s]

 76%|███████▌  | 22947/30196 [47:36<30:05,  4.02it/s]

 76%|███████▌  | 22949/30196 [47:36<21:52,  5.52it/s]

 76%|███████▌  | 22950/30196 [47:36<20:40,  5.84it/s]

 76%|███████▌  | 22952/30196 [47:36<15:50,  7.62it/s]

 76%|███████▌  | 22954/30196 [47:36<13:20,  9.04it/s]

 76%|███████▌  | 22956/30196 [47:36<15:28,  7.80it/s]

 76%|███████▌  | 22957/30196 [47:37<15:03,  8.02it/s]

 76%|███████▌  | 22958/30196 [47:37<15:27,  7.80it/s]

 76%|███████▌  | 22960/30196 [47:37<14:18,  8.43it/s]

 76%|███████▌  | 22961/30196 [47:37<15:49,  7.62it/s]

 76%|███████▌  | 22962/30196 [47:37<15:46,  7.65it/s]

 76%|███████▌  | 22964/30196 [47:38<15:37,  7.71it/s]

 76%|███████▌  | 22966/30196 [47:38<12:50,  9.38it/s]

 76%|███████▌  | 22968/30196 [47:38<10:35, 11.37it/s]

 76%|███████▌  | 22970/30196 [47:38<11:45, 10.24it/s]

 76%|███████▌  | 22972/30196 [47:38<11:03, 10.89it/s]

 76%|███████▌  | 22974/30196 [47:38<11:29, 10.48it/s]

 76%|███████▌  | 22976/30196 [47:39<11:24, 10.55it/s]

 76%|███████▌  | 22979/30196 [47:39<10:46, 11.15it/s]

 76%|███████▌  | 22981/30196 [47:39<10:47, 11.14it/s]

 76%|███████▌  | 22983/30196 [47:39<12:09,  9.89it/s]

 76%|███████▌  | 22985/30196 [47:39<11:16, 10.66it/s]

 76%|███████▌  | 22987/30196 [47:40<13:16,  9.05it/s]

 76%|███████▌  | 22990/30196 [47:40<10:14, 11.72it/s]

 76%|███████▌  | 22992/30196 [47:40<10:36, 11.33it/s]

 76%|███████▌  | 22994/30196 [47:40<12:37,  9.50it/s]

 76%|███████▌  | 22996/30196 [47:41<14:52,  8.07it/s]

 76%|███████▌  | 22997/30196 [47:41<16:32,  7.26it/s]

 76%|███████▌  | 22999/30196 [47:41<16:11,  7.41it/s]

 76%|███████▌  | 23000/30196 [47:41<17:09,  6.99it/s]

 76%|███████▌  | 23001/30196 [47:41<16:19,  7.35it/s]

 76%|███████▌  | 23003/30196 [47:42<13:50,  8.66it/s]

 76%|███████▌  | 23004/30196 [47:42<15:06,  7.93it/s]

 76%|███████▌  | 23005/30196 [47:42<14:41,  8.16it/s]

 76%|███████▌  | 23006/30196 [47:42<14:53,  8.04it/s]

 76%|███████▌  | 23007/30196 [47:42<24:08,  4.96it/s]

 76%|███████▌  | 23008/30196 [47:43<21:53,  5.47it/s]

 76%|███████▌  | 23009/30196 [47:43<21:18,  5.62it/s]

 76%|███████▌  | 23011/30196 [47:43<16:30,  7.26it/s]

 76%|███████▌  | 23012/30196 [47:43<16:47,  7.13it/s]

 76%|███████▌  | 23014/30196 [47:43<13:11,  9.08it/s]

 76%|███████▌  | 23016/30196 [47:43<12:24,  9.64it/s]

 76%|███████▌  | 23018/30196 [47:43<11:08, 10.74it/s]

 76%|███████▌  | 23020/30196 [47:44<13:38,  8.77it/s]

 76%|███████▌  | 23022/30196 [47:44<11:47, 10.15it/s]

 76%|███████▌  | 23024/30196 [47:44<12:32,  9.53it/s]

 76%|███████▋  | 23026/30196 [47:44<13:46,  8.68it/s]

 76%|███████▋  | 23027/30196 [47:45<16:16,  7.34it/s]

 76%|███████▋  | 23029/30196 [47:45<13:49,  8.64it/s]

 76%|███████▋  | 23031/30196 [47:45<11:54, 10.03it/s]

 76%|███████▋  | 23033/30196 [47:45<10:41, 11.17it/s]

 76%|███████▋  | 23035/30196 [47:45<11:01, 10.82it/s]

 76%|███████▋  | 23037/30196 [47:46<13:27,  8.87it/s]

 76%|███████▋  | 23039/30196 [47:46<12:13,  9.76it/s]

 76%|███████▋  | 23041/30196 [47:46<13:59,  8.52it/s]

 76%|███████▋  | 23043/30196 [47:46<12:43,  9.37it/s]

 76%|███████▋  | 23045/30196 [47:46<12:04,  9.87it/s]

 76%|███████▋  | 23047/30196 [47:47<14:58,  7.95it/s]

 76%|███████▋  | 23049/30196 [47:47<13:35,  8.76it/s]

 76%|███████▋  | 23050/30196 [47:47<17:10,  6.93it/s]

 76%|███████▋  | 23051/30196 [47:47<16:53,  7.05it/s]

 76%|███████▋  | 23053/30196 [47:48<15:16,  7.80it/s]

 76%|███████▋  | 23055/30196 [47:48<15:15,  7.80it/s]

 76%|███████▋  | 23056/30196 [47:48<16:20,  7.28it/s]

 76%|███████▋  | 23058/30196 [47:48<16:46,  7.09it/s]

 76%|███████▋  | 23060/30196 [47:49<15:24,  7.72it/s]

 76%|███████▋  | 23061/30196 [47:49<15:48,  7.52it/s]

 76%|███████▋  | 23062/30196 [47:49<15:04,  7.89it/s]

 76%|███████▋  | 23063/30196 [47:49<15:17,  7.77it/s]

 76%|███████▋  | 23065/30196 [47:49<12:19,  9.64it/s]

 76%|███████▋  | 23067/30196 [47:49<11:33, 10.28it/s]

 76%|███████▋  | 23069/30196 [47:49<12:12,  9.73it/s]

 76%|███████▋  | 23070/30196 [47:50<12:59,  9.14it/s]

 76%|███████▋  | 23072/30196 [47:50<13:20,  8.90it/s]

 76%|███████▋  | 23073/30196 [47:50<13:10,  9.01it/s]

 76%|███████▋  | 23075/30196 [47:50<11:14, 10.56it/s]

 76%|███████▋  | 23077/30196 [47:50<13:26,  8.82it/s]

 76%|███████▋  | 23078/30196 [47:51<14:46,  8.03it/s]

 76%|███████▋  | 23079/30196 [47:51<19:02,  6.23it/s]

 76%|███████▋  | 23080/30196 [47:51<18:41,  6.34it/s]

 76%|███████▋  | 23082/30196 [47:51<14:13,  8.34it/s]

 76%|███████▋  | 23084/30196 [47:51<12:51,  9.21it/s]

 76%|███████▋  | 23086/30196 [47:51<11:48, 10.03it/s]

 76%|███████▋  | 23088/30196 [47:52<14:29,  8.17it/s]

 76%|███████▋  | 23089/30196 [47:52<18:57,  6.25it/s]

 76%|███████▋  | 23090/30196 [47:52<20:06,  5.89it/s]

 76%|███████▋  | 23091/30196 [47:52<19:57,  5.93it/s]

 76%|███████▋  | 23092/30196 [47:53<19:10,  6.18it/s]

 76%|███████▋  | 23093/30196 [47:53<17:22,  6.81it/s]

 76%|███████▋  | 23095/30196 [47:53<13:43,  8.63it/s]

 76%|███████▋  | 23096/30196 [47:53<15:08,  7.82it/s]

 76%|███████▋  | 23097/30196 [47:53<16:20,  7.24it/s]

 76%|███████▋  | 23099/30196 [47:53<13:55,  8.50it/s]

 77%|███████▋  | 23101/30196 [47:54<12:49,  9.22it/s]

 77%|███████▋  | 23102/30196 [47:54<28:32,  4.14it/s]

 77%|███████▋  | 23104/30196 [47:54<21:38,  5.46it/s]

 77%|███████▋  | 23106/30196 [47:55<19:27,  6.07it/s]

 77%|███████▋  | 23108/30196 [47:55<15:18,  7.72it/s]

 77%|███████▋  | 23110/30196 [47:55<13:15,  8.91it/s]

 77%|███████▋  | 23112/30196 [47:55<14:56,  7.90it/s]

 77%|███████▋  | 23113/30196 [47:55<16:00,  7.38it/s]

 77%|███████▋  | 23115/30196 [47:56<14:10,  8.33it/s]

 77%|███████▋  | 23117/30196 [47:56<12:09,  9.71it/s]

 77%|███████▋  | 23119/30196 [47:56<14:09,  8.33it/s]

 77%|███████▋  | 23120/30196 [47:56<14:24,  8.18it/s]

 77%|███████▋  | 23121/30196 [47:57<35:26,  3.33it/s]

 77%|███████▋  | 23122/30196 [47:57<32:11,  3.66it/s]

 77%|███████▋  | 23123/30196 [47:58<29:02,  4.06it/s]

 77%|███████▋  | 23125/30196 [47:58<19:44,  5.97it/s]

 77%|███████▋  | 23127/30196 [47:58<15:53,  7.41it/s]

 77%|███████▋  | 23129/30196 [47:58<16:16,  7.23it/s]

 77%|███████▋  | 23131/30196 [47:58<15:21,  7.67it/s]

 77%|███████▋  | 23133/30196 [47:58<13:14,  8.89it/s]

 77%|███████▋  | 23135/30196 [47:59<14:44,  7.98it/s]

 77%|███████▋  | 23136/30196 [47:59<17:25,  6.75it/s]

 77%|███████▋  | 23137/30196 [47:59<16:21,  7.19it/s]

 77%|███████▋  | 23138/30196 [47:59<15:26,  7.62it/s]

 77%|███████▋  | 23139/30196 [47:59<14:50,  7.92it/s]

 77%|███████▋  | 23141/30196 [48:00<16:02,  7.33it/s]

 77%|███████▋  | 23143/30196 [48:00<12:57,  9.08it/s]

 77%|███████▋  | 23145/30196 [48:00<13:14,  8.88it/s]

 77%|███████▋  | 23146/30196 [48:00<13:44,  8.55it/s]

 77%|███████▋  | 23147/30196 [48:00<13:28,  8.72it/s]

 77%|███████▋  | 23148/30196 [48:00<15:09,  7.75it/s]

 77%|███████▋  | 23149/30196 [48:01<16:23,  7.16it/s]

 77%|███████▋  | 23150/30196 [48:01<17:11,  6.83it/s]

 77%|███████▋  | 23152/30196 [48:01<16:18,  7.20it/s]

 77%|███████▋  | 23154/30196 [48:01<13:32,  8.66it/s]

 77%|███████▋  | 23155/30196 [48:01<16:06,  7.29it/s]

 77%|███████▋  | 23156/30196 [48:02<15:54,  7.38it/s]

 77%|███████▋  | 23158/30196 [48:02<11:57,  9.80it/s]

 77%|███████▋  | 23160/30196 [48:02<12:35,  9.31it/s]

 77%|███████▋  | 23162/30196 [48:02<11:57,  9.80it/s]

 77%|███████▋  | 23164/30196 [48:02<12:44,  9.20it/s]

 77%|███████▋  | 23165/30196 [48:02<12:47,  9.17it/s]

 77%|███████▋  | 23166/30196 [48:03<13:20,  8.79it/s]

 77%|███████▋  | 23167/30196 [48:03<14:13,  8.23it/s]

 77%|███████▋  | 23169/30196 [48:03<12:49,  9.13it/s]

 77%|███████▋  | 23170/30196 [48:03<13:36,  8.60it/s]

 77%|███████▋  | 23171/30196 [48:03<16:18,  7.18it/s]

 77%|███████▋  | 23172/30196 [48:03<16:03,  7.29it/s]

 77%|███████▋  | 23173/30196 [48:03<15:01,  7.79it/s]

 77%|███████▋  | 23175/30196 [48:04<16:06,  7.27it/s]

 77%|███████▋  | 23176/30196 [48:04<17:00,  6.88it/s]

 77%|███████▋  | 23177/30196 [48:04<16:51,  6.94it/s]

 77%|███████▋  | 23178/30196 [48:04<21:10,  5.52it/s]

 77%|███████▋  | 23179/30196 [48:05<20:47,  5.62it/s]

 77%|███████▋  | 23180/30196 [48:05<20:50,  5.61it/s]

 77%|███████▋  | 23181/30196 [48:05<19:24,  6.02it/s]

 77%|███████▋  | 23183/30196 [48:05<15:23,  7.60it/s]

 77%|███████▋  | 23184/30196 [48:05<16:23,  7.13it/s]

 77%|███████▋  | 23185/30196 [48:05<16:14,  7.20it/s]

 77%|███████▋  | 23186/30196 [48:05<16:30,  7.08it/s]

 77%|███████▋  | 23187/30196 [48:06<16:09,  7.23it/s]

 77%|███████▋  | 23189/30196 [48:06<12:04,  9.68it/s]

 77%|███████▋  | 23191/30196 [48:06<12:27,  9.38it/s]

 77%|███████▋  | 23192/30196 [48:06<13:55,  8.38it/s]

 77%|███████▋  | 23194/30196 [48:06<12:29,  9.34it/s]

 77%|███████▋  | 23196/30196 [48:06<11:29, 10.15it/s]

 77%|███████▋  | 23198/30196 [48:07<12:23,  9.42it/s]

 77%|███████▋  | 23199/30196 [48:07<12:22,  9.43it/s]

 77%|███████▋  | 23201/30196 [48:07<10:46, 10.82it/s]

 77%|███████▋  | 23203/30196 [48:07<11:00, 10.58it/s]

 77%|███████▋  | 23205/30196 [48:07<09:53, 11.78it/s]

 77%|███████▋  | 23207/30196 [48:08<11:44,  9.93it/s]

 77%|███████▋  | 23209/30196 [48:08<13:57,  8.34it/s]

 77%|███████▋  | 23210/30196 [48:08<15:11,  7.66it/s]

 77%|███████▋  | 23212/30196 [48:08<14:19,  8.12it/s]

 77%|███████▋  | 23213/30196 [48:09<19:06,  6.09it/s]

 77%|███████▋  | 23215/30196 [48:09<22:30,  5.17it/s]

 77%|███████▋  | 23216/30196 [48:09<23:10,  5.02it/s]

 77%|███████▋  | 23218/30196 [48:09<18:09,  6.40it/s]

 77%|███████▋  | 23220/30196 [48:10<14:33,  7.99it/s]

 77%|███████▋  | 23221/30196 [48:10<14:53,  7.80it/s]

 77%|███████▋  | 23222/30196 [48:10<15:52,  7.32it/s]

 77%|███████▋  | 23224/30196 [48:10<13:51,  8.39it/s]

 77%|███████▋  | 23225/30196 [48:10<15:16,  7.61it/s]

 77%|███████▋  | 23227/30196 [48:11<16:27,  7.05it/s]

 77%|███████▋  | 23229/30196 [48:11<16:41,  6.96it/s]

 77%|███████▋  | 23231/30196 [48:11<16:00,  7.25it/s]

 77%|███████▋  | 23232/30196 [48:11<16:42,  6.95it/s]

 77%|███████▋  | 23234/30196 [48:11<13:02,  8.90it/s]

 77%|███████▋  | 23236/30196 [48:12<13:57,  8.32it/s]

 77%|███████▋  | 23237/30196 [48:12<15:11,  7.63it/s]

 77%|███████▋  | 23238/30196 [48:12<16:08,  7.19it/s]

 77%|███████▋  | 23240/30196 [48:12<12:39,  9.16it/s]

 77%|███████▋  | 23242/30196 [48:12<13:12,  8.78it/s]

 77%|███████▋  | 23244/30196 [48:13<13:42,  8.45it/s]

 77%|███████▋  | 23246/30196 [48:13<11:39,  9.94it/s]

 77%|███████▋  | 23248/30196 [48:13<13:33,  8.54it/s]

 77%|███████▋  | 23250/30196 [48:13<11:31, 10.04it/s]

 77%|███████▋  | 23252/30196 [48:13<12:42,  9.10it/s]

 77%|███████▋  | 23254/30196 [48:14<16:19,  7.09it/s]

 77%|███████▋  | 23255/30196 [48:14<16:12,  7.14it/s]

 77%|███████▋  | 23256/30196 [48:14<20:05,  5.76it/s]

 77%|███████▋  | 23257/30196 [48:14<18:59,  6.09it/s]

 77%|███████▋  | 23258/30196 [48:15<18:28,  6.26it/s]

 77%|███████▋  | 23260/30196 [48:15<15:09,  7.62it/s]

 77%|███████▋  | 23261/30196 [48:15<18:49,  6.14it/s]

 77%|███████▋  | 23262/30196 [48:15<17:09,  6.74it/s]

 77%|███████▋  | 23264/30196 [48:15<17:57,  6.43it/s]

 77%|███████▋  | 23265/30196 [48:16<18:28,  6.25it/s]

 77%|███████▋  | 23266/30196 [48:16<16:53,  6.84it/s]

 77%|███████▋  | 23267/30196 [48:16<17:33,  6.58it/s]

 77%|███████▋  | 23268/30196 [48:16<18:22,  6.28it/s]

 77%|███████▋  | 23269/30196 [48:16<16:33,  6.97it/s]

 77%|███████▋  | 23270/30196 [48:16<15:27,  7.47it/s]

 77%|███████▋  | 23272/30196 [48:17<13:20,  8.65it/s]

 77%|███████▋  | 23273/30196 [48:17<14:03,  8.21it/s]

 77%|███████▋  | 23274/30196 [48:17<14:27,  7.98it/s]

 77%|███████▋  | 23275/30196 [48:17<14:37,  7.88it/s]

 77%|███████▋  | 23276/30196 [48:17<14:55,  7.73it/s]

 77%|███████▋  | 23278/30196 [48:17<11:40,  9.87it/s]

 77%|███████▋  | 23280/30196 [48:17<11:07, 10.36it/s]

 77%|███████▋  | 23282/30196 [48:18<11:22, 10.12it/s]

 77%|███████▋  | 23284/30196 [48:18<11:21, 10.14it/s]

 77%|███████▋  | 23286/30196 [48:18<11:08, 10.33it/s]

 77%|███████▋  | 23288/30196 [48:18<11:11, 10.29it/s]

 77%|███████▋  | 23290/30196 [48:18<10:34, 10.88it/s]

 77%|███████▋  | 23292/30196 [48:19<10:47, 10.67it/s]

 77%|███████▋  | 23294/30196 [48:19<10:38, 10.81it/s]

 77%|███████▋  | 23296/30196 [48:19<10:16, 11.19it/s]

 77%|███████▋  | 23298/30196 [48:19<12:25,  9.25it/s]

 77%|███████▋  | 23299/30196 [48:19<13:55,  8.26it/s]

 77%|███████▋  | 23300/30196 [48:19<13:31,  8.49it/s]

 77%|███████▋  | 23302/30196 [48:20<11:27, 10.03it/s]

 77%|███████▋  | 23304/30196 [48:20<13:38,  8.42it/s]

 77%|███████▋  | 23305/30196 [48:20<13:55,  8.25it/s]

 77%|███████▋  | 23307/30196 [48:20<11:53,  9.65it/s]

 77%|███████▋  | 23309/30196 [48:20<11:42,  9.81it/s]

 77%|███████▋  | 23311/30196 [48:21<15:44,  7.29it/s]

 77%|███████▋  | 23313/30196 [48:21<14:06,  8.13it/s]

 77%|███████▋  | 23314/30196 [48:21<16:01,  7.16it/s]

 77%|███████▋  | 23316/30196 [48:21<15:01,  7.63it/s]

 77%|███████▋  | 23318/30196 [48:22<12:57,  8.84it/s]

 77%|███████▋  | 23319/30196 [48:22<15:32,  7.38it/s]

 77%|███████▋  | 23320/30196 [48:22<16:29,  6.95it/s]

 77%|███████▋  | 23321/30196 [48:22<22:58,  4.99it/s]

 77%|███████▋  | 23323/30196 [48:23<19:46,  5.79it/s]

 77%|███████▋  | 23324/30196 [48:23<18:11,  6.30it/s]

 77%|███████▋  | 23325/30196 [48:23<17:24,  6.58it/s]

 77%|███████▋  | 23326/30196 [48:23<16:45,  6.83it/s]

 77%|███████▋  | 23327/30196 [48:23<16:23,  6.99it/s]

 77%|███████▋  | 23329/30196 [48:23<15:05,  7.58it/s]

 77%|███████▋  | 23331/30196 [48:24<13:13,  8.65it/s]

 77%|███████▋  | 23332/30196 [48:24<12:57,  8.83it/s]

 77%|███████▋  | 23333/30196 [48:24<13:52,  8.24it/s]

 77%|███████▋  | 23334/30196 [48:24<16:45,  6.83it/s]

 77%|███████▋  | 23335/30196 [48:24<16:17,  7.02it/s]

 77%|███████▋  | 23336/30196 [48:24<17:07,  6.68it/s]

 77%|███████▋  | 23338/30196 [48:24<13:44,  8.31it/s]

 77%|███████▋  | 23340/30196 [48:25<13:58,  8.18it/s]

 77%|███████▋  | 23341/30196 [48:25<14:17,  7.99it/s]

 77%|███████▋  | 23342/30196 [48:25<14:31,  7.86it/s]

 77%|███████▋  | 23343/30196 [48:25<14:02,  8.13it/s]

 77%|███████▋  | 23345/30196 [48:25<17:12,  6.64it/s]

 77%|███████▋  | 23346/30196 [48:26<18:54,  6.04it/s]

 77%|███████▋  | 23348/30196 [48:26<15:36,  7.31it/s]

 77%|███████▋  | 23350/30196 [48:26<12:47,  8.92it/s]

 77%|███████▋  | 23351/30196 [48:26<14:20,  7.96it/s]

 77%|███████▋  | 23353/30196 [48:26<11:52,  9.61it/s]

 77%|███████▋  | 23355/30196 [48:27<13:24,  8.50it/s]

 77%|███████▋  | 23356/30196 [48:27<14:35,  7.81it/s]

 77%|███████▋  | 23357/30196 [48:27<14:41,  7.76it/s]

 77%|███████▋  | 23358/30196 [48:27<17:28,  6.52it/s]

 77%|███████▋  | 23359/30196 [48:27<17:04,  6.67it/s]

 77%|███████▋  | 23360/30196 [48:27<15:43,  7.25it/s]

 77%|███████▋  | 23361/30196 [48:28<14:40,  7.76it/s]

 77%|███████▋  | 23362/30196 [48:28<16:19,  6.98it/s]

 77%|███████▋  | 23363/30196 [48:28<16:26,  6.93it/s]

 77%|███████▋  | 23365/30196 [48:28<15:12,  7.49it/s]

 77%|███████▋  | 23366/30196 [48:28<15:16,  7.45it/s]

 77%|███████▋  | 23367/30196 [48:28<18:00,  6.32it/s]

 77%|███████▋  | 23369/30196 [48:29<13:26,  8.47it/s]

 77%|███████▋  | 23371/30196 [48:29<11:33,  9.85it/s]

 77%|███████▋  | 23373/30196 [48:29<11:26,  9.94it/s]

 77%|███████▋  | 23375/30196 [48:29<11:51,  9.58it/s]

 77%|███████▋  | 23376/30196 [48:29<15:31,  7.33it/s]

 77%|███████▋  | 23377/30196 [48:30<15:59,  7.10it/s]

 77%|███████▋  | 23378/30196 [48:30<17:48,  6.38it/s]

 77%|███████▋  | 23380/30196 [48:30<14:46,  7.69it/s]

 77%|███████▋  | 23381/30196 [48:30<15:39,  7.25it/s]

 77%|███████▋  | 23382/30196 [48:30<14:55,  7.61it/s]

 77%|███████▋  | 23384/30196 [48:30<12:17,  9.24it/s]

 77%|███████▋  | 23386/30196 [48:31<10:32, 10.76it/s]

 77%|███████▋  | 23388/30196 [48:31<10:07, 11.20it/s]

 77%|███████▋  | 23390/30196 [48:31<18:55,  6.00it/s]

 77%|███████▋  | 23391/30196 [48:32<19:45,  5.74it/s]

 77%|███████▋  | 23393/30196 [48:32<16:38,  6.82it/s]

 77%|███████▋  | 23395/30196 [48:32<15:15,  7.43it/s]

 77%|███████▋  | 23397/30196 [48:32<14:19,  7.91it/s]

 77%|███████▋  | 23398/30196 [48:32<14:30,  7.81it/s]

 77%|███████▋  | 23399/30196 [48:32<15:29,  7.32it/s]

 77%|███████▋  | 23400/30196 [48:33<14:35,  7.76it/s]

 77%|███████▋  | 23401/30196 [48:33<14:38,  7.74it/s]

 78%|███████▊  | 23403/30196 [48:33<13:14,  8.55it/s]

 78%|███████▊  | 23404/30196 [48:33<12:54,  8.76it/s]

 78%|███████▊  | 23405/30196 [48:33<13:28,  8.40it/s]

 78%|███████▊  | 23407/30196 [48:33<11:01, 10.26it/s]

 78%|███████▊  | 23409/30196 [48:33<11:01, 10.26it/s]

 78%|███████▊  | 23411/30196 [48:34<10:50, 10.43it/s]

 78%|███████▊  | 23413/30196 [48:34<12:23,  9.12it/s]

 78%|███████▊  | 23414/30196 [48:34<13:39,  8.28it/s]

 78%|███████▊  | 23415/30196 [48:34<15:44,  7.18it/s]

 78%|███████▊  | 23416/30196 [48:34<16:38,  6.79it/s]

 78%|███████▊  | 23417/30196 [48:35<16:11,  6.98it/s]

 78%|███████▊  | 23418/30196 [48:35<16:56,  6.67it/s]

 78%|███████▊  | 23419/30196 [48:35<17:36,  6.42it/s]

 78%|███████▊  | 23420/30196 [48:35<17:07,  6.60it/s]

 78%|███████▊  | 23421/30196 [48:35<17:47,  6.35it/s]

 78%|███████▊  | 23422/30196 [48:35<18:05,  6.24it/s]

 78%|███████▊  | 23424/30196 [48:36<18:50,  5.99it/s]

 78%|███████▊  | 23426/30196 [48:36<15:43,  7.18it/s]

 78%|███████▊  | 23428/30196 [48:36<12:30,  9.02it/s]

 78%|███████▊  | 23430/30196 [48:36<14:06,  7.99it/s]

 78%|███████▊  | 23432/30196 [48:37<13:18,  8.47it/s]

 78%|███████▊  | 23433/30196 [48:37<14:20,  7.86it/s]

 78%|███████▊  | 23434/30196 [48:37<14:25,  7.81it/s]

 78%|███████▊  | 23435/30196 [48:37<13:49,  8.15it/s]

 78%|███████▊  | 23437/30196 [48:37<11:20,  9.93it/s]

 78%|███████▊  | 23439/30196 [48:37<13:00,  8.66it/s]

 78%|███████▊  | 23441/30196 [48:38<12:57,  8.69it/s]

 78%|███████▊  | 23442/30196 [48:38<13:24,  8.40it/s]

 78%|███████▊  | 23444/30196 [48:38<11:02, 10.19it/s]

 78%|███████▊  | 23446/30196 [48:38<11:47,  9.55it/s]

 78%|███████▊  | 23448/30196 [48:38<13:38,  8.24it/s]

 78%|███████▊  | 23449/30196 [48:39<13:55,  8.07it/s]

 78%|███████▊  | 23450/30196 [48:39<15:16,  7.36it/s]

 78%|███████▊  | 23451/30196 [48:39<16:15,  6.92it/s]

 78%|███████▊  | 23452/30196 [48:39<15:05,  7.45it/s]

 78%|███████▊  | 23453/30196 [48:39<15:29,  7.26it/s]

 78%|███████▊  | 23454/30196 [48:39<15:24,  7.29it/s]

 78%|███████▊  | 23456/30196 [48:40<14:09,  7.93it/s]

 78%|███████▊  | 23458/30196 [48:40<10:59, 10.21it/s]

 78%|███████▊  | 23460/30196 [48:40<09:22, 11.98it/s]

 78%|███████▊  | 23462/30196 [48:40<08:17, 13.55it/s]

 78%|███████▊  | 23464/30196 [48:40<08:13, 13.64it/s]

 78%|███████▊  | 23466/30196 [48:40<08:44, 12.82it/s]

 78%|███████▊  | 23468/30196 [48:40<10:25, 10.75it/s]

 78%|███████▊  | 23470/30196 [48:41<10:34, 10.61it/s]

 78%|███████▊  | 23472/30196 [48:41<09:34, 11.70it/s]

 78%|███████▊  | 23474/30196 [48:41<10:49, 10.35it/s]

 78%|███████▊  | 23476/30196 [48:41<12:19,  9.09it/s]

 78%|███████▊  | 23478/30196 [48:42<14:09,  7.90it/s]

 78%|███████▊  | 23480/30196 [48:42<12:18,  9.10it/s]

 78%|███████▊  | 23482/30196 [48:42<11:02, 10.14it/s]

 78%|███████▊  | 23484/30196 [48:42<10:28, 10.67it/s]

 78%|███████▊  | 23486/30196 [48:42<11:42,  9.55it/s]

 78%|███████▊  | 23488/30196 [48:43<10:44, 10.41it/s]

 78%|███████▊  | 23490/30196 [48:43<11:13,  9.95it/s]

 78%|███████▊  | 23492/30196 [48:43<10:36, 10.54it/s]

 78%|███████▊  | 23494/30196 [48:43<16:06,  6.93it/s]

 78%|███████▊  | 23495/30196 [48:44<15:50,  7.05it/s]

 78%|███████▊  | 23497/30196 [48:44<13:30,  8.27it/s]

 78%|███████▊  | 23498/30196 [48:44<13:59,  7.98it/s]

 78%|███████▊  | 23500/30196 [48:44<16:38,  6.70it/s]

 78%|███████▊  | 23501/30196 [48:44<16:13,  6.88it/s]

 78%|███████▊  | 23503/30196 [48:45<13:47,  8.09it/s]

 78%|███████▊  | 23504/30196 [48:45<17:36,  6.34it/s]

 78%|███████▊  | 23505/30196 [48:45<22:57,  4.86it/s]

 78%|███████▊  | 23506/30196 [48:45<22:16,  5.01it/s]

 78%|███████▊  | 23508/30196 [48:46<19:04,  5.84it/s]

 78%|███████▊  | 23510/30196 [48:46<15:38,  7.12it/s]

 78%|███████▊  | 23511/30196 [48:46<16:13,  6.87it/s]

 78%|███████▊  | 23512/30196 [48:46<15:09,  7.35it/s]

 78%|███████▊  | 23513/30196 [48:46<15:22,  7.25it/s]

 78%|███████▊  | 23514/30196 [48:46<15:27,  7.21it/s]

 78%|███████▊  | 23516/30196 [48:46<12:01,  9.26it/s]

 78%|███████▊  | 23517/30196 [48:47<11:57,  9.31it/s]

 78%|███████▊  | 23519/30196 [48:47<10:08, 10.97it/s]

 78%|███████▊  | 23521/30196 [48:47<15:33,  7.15it/s]

 78%|███████▊  | 23523/30196 [48:47<12:21,  8.99it/s]

 78%|███████▊  | 23525/30196 [48:48<12:07,  9.18it/s]

 78%|███████▊  | 23527/30196 [48:48<13:34,  8.19it/s]

 78%|███████▊  | 23529/30196 [48:48<12:36,  8.81it/s]

 78%|███████▊  | 23531/30196 [48:48<12:07,  9.16it/s]

 78%|███████▊  | 23533/30196 [48:48<10:50, 10.24it/s]

 78%|███████▊  | 23535/30196 [48:49<13:52,  8.00it/s]

 78%|███████▊  | 23536/30196 [48:49<13:35,  8.17it/s]

 78%|███████▊  | 23537/30196 [48:49<14:08,  7.85it/s]

 78%|███████▊  | 23538/30196 [48:49<14:18,  7.75it/s]

 78%|███████▊  | 23539/30196 [48:49<13:48,  8.04it/s]

 78%|███████▊  | 23541/30196 [48:49<13:57,  7.95it/s]

 78%|███████▊  | 23543/30196 [48:50<13:07,  8.45it/s]

 78%|███████▊  | 23545/30196 [48:50<12:51,  8.62it/s]

 78%|███████▊  | 23546/30196 [48:50<13:27,  8.23it/s]

 78%|███████▊  | 23547/30196 [48:50<14:51,  7.46it/s]

 78%|███████▊  | 23549/30196 [48:50<12:25,  8.91it/s]

 78%|███████▊  | 23550/30196 [48:51<13:53,  7.98it/s]

 78%|███████▊  | 23552/30196 [48:51<11:52,  9.33it/s]

 78%|███████▊  | 23553/30196 [48:51<11:54,  9.30it/s]

 78%|███████▊  | 23554/30196 [48:51<11:59,  9.24it/s]

 78%|███████▊  | 23557/30196 [48:51<09:15, 11.95it/s]

 78%|███████▊  | 23559/30196 [48:51<10:50, 10.20it/s]

 78%|███████▊  | 23561/30196 [48:52<11:11,  9.87it/s]

 78%|███████▊  | 23564/30196 [48:52<09:53, 11.17it/s]

 78%|███████▊  | 23566/30196 [48:52<11:26,  9.66it/s]

 78%|███████▊  | 23567/30196 [48:52<13:45,  8.03it/s]

 78%|███████▊  | 23568/30196 [48:52<13:20,  8.28it/s]

 78%|███████▊  | 23569/30196 [48:53<12:58,  8.51it/s]

 78%|███████▊  | 23570/30196 [48:53<14:12,  7.77it/s]

 78%|███████▊  | 23572/30196 [48:53<12:28,  8.85it/s]

 78%|███████▊  | 23573/30196 [48:53<13:17,  8.30it/s]

 78%|███████▊  | 23575/30196 [48:53<14:23,  7.66it/s]

 78%|███████▊  | 23576/30196 [48:53<14:47,  7.46it/s]

 78%|███████▊  | 23577/30196 [48:54<14:26,  7.64it/s]

 78%|███████▊  | 23578/30196 [48:54<15:45,  7.00it/s]

 78%|███████▊  | 23579/30196 [48:54<15:40,  7.04it/s]

 78%|███████▊  | 23581/30196 [48:54<16:38,  6.62it/s]

 78%|███████▊  | 23583/30196 [48:54<14:43,  7.49it/s]

 78%|███████▊  | 23584/30196 [48:55<21:27,  5.14it/s]

 78%|███████▊  | 23585/30196 [48:55<19:49,  5.56it/s]

 78%|███████▊  | 23587/30196 [48:55<14:52,  7.40it/s]

 78%|███████▊  | 23589/30196 [48:55<14:28,  7.60it/s]

 78%|███████▊  | 23590/30196 [48:56<14:48,  7.43it/s]

 78%|███████▊  | 23592/30196 [48:56<13:17,  8.28it/s]

 78%|███████▊  | 23594/30196 [48:56<15:49,  6.95it/s]

 78%|███████▊  | 23596/30196 [48:56<13:15,  8.30it/s]

 78%|███████▊  | 23597/30196 [48:56<15:19,  7.17it/s]

 78%|███████▊  | 23598/30196 [48:57<19:57,  5.51it/s]

 78%|███████▊  | 23599/30196 [48:57<19:56,  5.51it/s]

 78%|███████▊  | 23601/30196 [48:57<16:03,  6.84it/s]

 78%|███████▊  | 23602/30196 [48:57<16:05,  6.83it/s]

 78%|███████▊  | 23604/30196 [48:58<14:40,  7.48it/s]

 78%|███████▊  | 23605/30196 [48:58<14:41,  7.48it/s]

 78%|███████▊  | 23606/30196 [48:58<14:37,  7.51it/s]

 78%|███████▊  | 23609/30196 [48:58<10:27, 10.51it/s]

 78%|███████▊  | 23611/30196 [48:58<09:28, 11.59it/s]

 78%|███████▊  | 23614/30196 [48:58<08:04, 13.59it/s]

 78%|███████▊  | 23616/30196 [48:58<08:44, 12.54it/s]

 78%|███████▊  | 23618/30196 [48:59<10:29, 10.44it/s]

 78%|███████▊  | 23620/30196 [48:59<09:17, 11.79it/s]

 78%|███████▊  | 23622/30196 [48:59<10:06, 10.84it/s]

 78%|███████▊  | 23624/30196 [48:59<11:13,  9.76it/s]

 78%|███████▊  | 23626/30196 [49:00<12:25,  8.82it/s]

 78%|███████▊  | 23627/30196 [49:00<15:12,  7.20it/s]

 78%|███████▊  | 23628/30196 [49:00<18:08,  6.04it/s]

 78%|███████▊  | 23629/30196 [49:00<16:38,  6.58it/s]

 78%|███████▊  | 23631/30196 [49:00<13:22,  8.18it/s]

 78%|███████▊  | 23633/30196 [49:01<11:11,  9.78it/s]

 78%|███████▊  | 23635/30196 [49:01<11:07,  9.82it/s]

 78%|███████▊  | 23637/30196 [49:01<09:18, 11.74it/s]

 78%|███████▊  | 23639/30196 [49:01<10:14, 10.67it/s]

 78%|███████▊  | 23641/30196 [49:01<10:43, 10.19it/s]

 78%|███████▊  | 23643/30196 [49:01<11:09,  9.79it/s]

 78%|███████▊  | 23645/30196 [49:02<12:32,  8.71it/s]

 78%|███████▊  | 23646/30196 [49:02<12:51,  8.49it/s]

 78%|███████▊  | 23647/30196 [49:02<14:00,  7.79it/s]

 78%|███████▊  | 23648/30196 [49:02<13:33,  8.05it/s]

 78%|███████▊  | 23650/30196 [49:02<11:47,  9.25it/s]

 78%|███████▊  | 23651/30196 [49:03<13:14,  8.23it/s]

 78%|███████▊  | 23652/30196 [49:03<13:55,  7.83it/s]

 78%|███████▊  | 23653/30196 [49:03<14:00,  7.78it/s]

 78%|███████▊  | 23654/30196 [49:03<15:26,  7.06it/s]

 78%|███████▊  | 23656/30196 [49:03<11:12,  9.73it/s]

 78%|███████▊  | 23658/30196 [49:03<12:40,  8.59it/s]

 78%|███████▊  | 23659/30196 [49:03<12:24,  8.78it/s]

 78%|███████▊  | 23661/30196 [49:04<10:38, 10.23it/s]

 78%|███████▊  | 23663/30196 [49:04<11:21,  9.58it/s]

 78%|███████▊  | 23665/30196 [49:04<13:58,  7.79it/s]

 78%|███████▊  | 23667/30196 [49:04<13:28,  8.07it/s]

 78%|███████▊  | 23668/30196 [49:05<16:28,  6.60it/s]

 78%|███████▊  | 23670/30196 [49:05<14:14,  7.64it/s]

 78%|███████▊  | 23671/30196 [49:05<15:01,  7.24it/s]

 78%|███████▊  | 23673/30196 [49:05<11:33,  9.41it/s]

 78%|███████▊  | 23675/30196 [49:05<13:30,  8.04it/s]

 78%|███████▊  | 23677/30196 [49:06<12:16,  8.86it/s]

 78%|███████▊  | 23679/30196 [49:06<12:05,  8.98it/s]

 78%|███████▊  | 23681/30196 [49:06<11:27,  9.47it/s]

 78%|███████▊  | 23683/30196 [49:06<11:27,  9.47it/s]

 78%|███████▊  | 23685/30196 [49:07<12:51,  8.44it/s]

 78%|███████▊  | 23687/30196 [49:07<12:33,  8.64it/s]

 78%|███████▊  | 23688/30196 [49:07<14:44,  7.36it/s]

 78%|███████▊  | 23689/30196 [49:07<14:51,  7.30it/s]

 78%|███████▊  | 23690/30196 [49:07<14:43,  7.36it/s]

 78%|███████▊  | 23692/30196 [49:07<12:52,  8.42it/s]

 78%|███████▊  | 23693/30196 [49:08<15:03,  7.20it/s]

 78%|███████▊  | 23694/30196 [49:08<14:50,  7.30it/s]

 78%|███████▊  | 23696/30196 [49:08<12:43,  8.52it/s]

 78%|███████▊  | 23697/30196 [49:08<13:08,  8.24it/s]

 78%|███████▊  | 23699/30196 [49:08<11:44,  9.22it/s]

 78%|███████▊  | 23700/30196 [49:08<12:30,  8.65it/s]

 78%|███████▊  | 23701/30196 [49:09<14:48,  7.31it/s]

 78%|███████▊  | 23702/30196 [49:09<14:03,  7.70it/s]

 79%|███████▊  | 23704/30196 [49:09<14:24,  7.51it/s]

 79%|███████▊  | 23706/30196 [49:09<12:35,  8.59it/s]

 79%|███████▊  | 23707/30196 [49:09<13:02,  8.29it/s]

 79%|███████▊  | 23708/30196 [49:09<13:32,  7.98it/s]

 79%|███████▊  | 23709/30196 [49:10<14:38,  7.38it/s]

 79%|███████▊  | 23711/30196 [49:10<13:37,  7.93it/s]

 79%|███████▊  | 23712/30196 [49:10<13:05,  8.25it/s]

 79%|███████▊  | 23713/30196 [49:10<15:45,  6.85it/s]

 79%|███████▊  | 23714/30196 [49:10<16:02,  6.73it/s]

 79%|███████▊  | 23715/30196 [49:10<15:33,  6.95it/s]

 79%|███████▊  | 23717/30196 [49:11<14:03,  7.69it/s]

 79%|███████▊  | 23718/30196 [49:11<14:09,  7.63it/s]

 79%|███████▊  | 23719/30196 [49:11<14:35,  7.40it/s]

 79%|███████▊  | 23720/30196 [49:11<15:29,  6.97it/s]

 79%|███████▊  | 23721/30196 [49:11<15:29,  6.97it/s]

 79%|███████▊  | 23724/30196 [49:11<11:21,  9.49it/s]

 79%|███████▊  | 23725/30196 [49:12<12:17,  8.77it/s]

 79%|███████▊  | 23727/30196 [49:12<12:13,  8.82it/s]

 79%|███████▊  | 23729/30196 [49:12<11:39,  9.24it/s]

 79%|███████▊  | 23731/30196 [49:12<15:17,  7.05it/s]

 79%|███████▊  | 23732/30196 [49:13<14:31,  7.42it/s]

 79%|███████▊  | 23733/30196 [49:13<15:12,  7.08it/s]

 79%|███████▊  | 23735/30196 [49:13<14:16,  7.55it/s]

 79%|███████▊  | 23736/30196 [49:13<13:44,  7.83it/s]

 79%|███████▊  | 23738/30196 [49:13<13:51,  7.77it/s]

 79%|███████▊  | 23739/30196 [49:14<15:57,  6.75it/s]

 79%|███████▊  | 23741/30196 [49:14<13:33,  7.94it/s]

 79%|███████▊  | 23742/30196 [49:14<13:07,  8.20it/s]

 79%|███████▊  | 23744/30196 [49:14<11:05,  9.70it/s]

 79%|███████▊  | 23746/30196 [49:14<10:48,  9.94it/s]

 79%|███████▊  | 23748/30196 [49:14<09:23, 11.45it/s]

 79%|███████▊  | 23750/30196 [49:15<10:03, 10.68it/s]

 79%|███████▊  | 23752/30196 [49:15<10:31, 10.20it/s]

 79%|███████▊  | 23754/30196 [49:15<09:28, 11.34it/s]

 79%|███████▊  | 23756/30196 [49:15<12:02,  8.91it/s]

 79%|███████▊  | 23759/30196 [49:15<10:32, 10.18it/s]

 79%|███████▊  | 23761/30196 [49:16<14:43,  7.29it/s]

 79%|███████▊  | 23762/30196 [49:16<14:48,  7.24it/s]

 79%|███████▊  | 23763/30196 [49:16<16:27,  6.51it/s]

 79%|███████▊  | 23764/30196 [49:16<15:59,  6.71it/s]

 79%|███████▊  | 23765/30196 [49:17<15:38,  6.85it/s]

 79%|███████▊  | 23766/30196 [49:17<18:29,  5.80it/s]

 79%|███████▊  | 23768/30196 [49:17<14:55,  7.18it/s]

 79%|███████▊  | 23770/30196 [49:17<13:35,  7.88it/s]

 79%|███████▊  | 23772/30196 [49:17<12:57,  8.26it/s]

 79%|███████▊  | 23773/30196 [49:18<12:42,  8.42it/s]

 79%|███████▊  | 23775/30196 [49:18<10:20, 10.35it/s]

 79%|███████▊  | 23777/30196 [49:18<10:32, 10.14it/s]

 79%|███████▊  | 23779/30196 [49:18<10:29, 10.19it/s]

 79%|███████▉  | 23781/30196 [49:18<09:27, 11.30it/s]

 79%|███████▉  | 23783/30196 [49:18<09:37, 11.11it/s]

 79%|███████▉  | 23785/30196 [49:19<09:35, 11.14it/s]

 79%|███████▉  | 23787/30196 [49:19<11:57,  8.93it/s]

 79%|███████▉  | 23789/30196 [49:19<13:01,  8.20it/s]

 79%|███████▉  | 23790/30196 [49:19<13:17,  8.03it/s]

 79%|███████▉  | 23792/30196 [49:19<11:24,  9.35it/s]

 79%|███████▉  | 23794/30196 [49:20<10:45,  9.92it/s]

 79%|███████▉  | 23796/30196 [49:20<12:37,  8.45it/s]

 79%|███████▉  | 23798/30196 [49:20<11:24,  9.34it/s]

 79%|███████▉  | 23800/30196 [49:20<12:43,  8.38it/s]

 79%|███████▉  | 23801/30196 [49:21<13:01,  8.18it/s]

 79%|███████▉  | 23802/30196 [49:21<13:16,  8.03it/s]

 79%|███████▉  | 23804/30196 [49:21<18:44,  5.69it/s]

 79%|███████▉  | 23805/30196 [49:21<17:49,  5.98it/s]

 79%|███████▉  | 23807/30196 [49:22<17:07,  6.22it/s]

 79%|███████▉  | 23809/30196 [49:22<13:49,  7.70it/s]

 79%|███████▉  | 23811/30196 [49:22<11:46,  9.04it/s]

 79%|███████▉  | 23813/30196 [49:22<13:09,  8.08it/s]

 79%|███████▉  | 23814/30196 [49:22<12:52,  8.26it/s]

 79%|███████▉  | 23815/30196 [49:22<13:54,  7.65it/s]

 79%|███████▉  | 23816/30196 [49:23<13:59,  7.60it/s]

 79%|███████▉  | 23818/30196 [49:23<12:35,  8.44it/s]

 79%|███████▉  | 23819/30196 [49:23<13:53,  7.66it/s]

 79%|███████▉  | 23820/30196 [49:23<13:52,  7.66it/s]

 79%|███████▉  | 23821/30196 [49:23<17:43,  5.99it/s]

 79%|███████▉  | 23822/30196 [49:24<19:14,  5.52it/s]

 79%|███████▉  | 23823/30196 [49:24<17:10,  6.19it/s]

 79%|███████▉  | 23824/30196 [49:24<27:40,  3.84it/s]

 79%|███████▉  | 23826/30196 [49:24<19:51,  5.35it/s]

 79%|███████▉  | 23828/30196 [49:25<15:06,  7.03it/s]

 79%|███████▉  | 23829/30196 [49:25<15:50,  6.70it/s]

 79%|███████▉  | 23830/30196 [49:25<16:13,  6.54it/s]

 79%|███████▉  | 23831/30196 [49:25<18:19,  5.79it/s]

 79%|███████▉  | 23832/30196 [49:25<17:16,  6.14it/s]

 79%|███████▉  | 23834/30196 [49:25<13:36,  7.79it/s]

 79%|███████▉  | 23835/30196 [49:26<13:08,  8.07it/s]

 79%|███████▉  | 23837/30196 [49:26<10:11, 10.40it/s]

 79%|███████▉  | 23839/30196 [49:26<12:39,  8.37it/s]

 79%|███████▉  | 23840/30196 [49:26<12:54,  8.20it/s]

 79%|███████▉  | 23842/30196 [49:26<10:54,  9.70it/s]

 79%|███████▉  | 23844/30196 [49:26<10:22, 10.20it/s]

 79%|███████▉  | 23846/30196 [49:27<11:10,  9.47it/s]

 79%|███████▉  | 23848/30196 [49:27<11:34,  9.15it/s]

 79%|███████▉  | 23849/30196 [49:27<11:34,  9.13it/s]

 79%|███████▉  | 23850/30196 [49:27<11:29,  9.20it/s]

 79%|███████▉  | 23851/30196 [49:27<12:07,  8.72it/s]

 79%|███████▉  | 23853/30196 [49:27<12:01,  8.79it/s]

 79%|███████▉  | 23855/30196 [49:28<09:59, 10.58it/s]

 79%|███████▉  | 23857/30196 [49:28<08:45, 12.05it/s]

 79%|███████▉  | 23859/30196 [49:28<10:08, 10.42it/s]

 79%|███████▉  | 23861/30196 [49:28<10:35,  9.97it/s]

 79%|███████▉  | 23863/30196 [49:28<09:01, 11.69it/s]

 79%|███████▉  | 23865/30196 [49:29<11:13,  9.40it/s]

 79%|███████▉  | 23867/30196 [49:29<10:27, 10.09it/s]

 79%|███████▉  | 23869/30196 [49:29<12:24,  8.50it/s]

 79%|███████▉  | 23870/30196 [49:29<12:39,  8.33it/s]

 79%|███████▉  | 23871/30196 [49:29<12:19,  8.55it/s]

 79%|███████▉  | 23872/30196 [49:29<12:09,  8.66it/s]

 79%|███████▉  | 23874/30196 [49:30<11:47,  8.94it/s]

 79%|███████▉  | 23875/30196 [49:30<12:26,  8.47it/s]

 79%|███████▉  | 23876/30196 [49:30<13:43,  7.67it/s]

 79%|███████▉  | 23877/30196 [49:30<13:43,  7.68it/s]

 79%|███████▉  | 23878/30196 [49:30<14:48,  7.11it/s]

 79%|███████▉  | 23879/30196 [49:30<14:58,  7.03it/s]

 79%|███████▉  | 23881/30196 [49:31<12:40,  8.31it/s]

 79%|███████▉  | 23882/30196 [49:31<17:28,  6.02it/s]

 79%|███████▉  | 23884/30196 [49:31<14:55,  7.05it/s]

 79%|███████▉  | 23885/30196 [49:31<14:54,  7.06it/s]

 79%|███████▉  | 23886/30196 [49:31<15:32,  6.77it/s]

 79%|███████▉  | 23888/30196 [49:32<13:24,  7.84it/s]

 79%|███████▉  | 23889/30196 [49:32<13:51,  7.59it/s]

 79%|███████▉  | 23890/30196 [49:32<13:56,  7.54it/s]

 79%|███████▉  | 23892/30196 [49:32<12:00,  8.75it/s]

 79%|███████▉  | 23893/30196 [49:32<12:23,  8.48it/s]

 79%|███████▉  | 23895/30196 [49:33<15:40,  6.70it/s]

 79%|███████▉  | 23897/30196 [49:33<25:28,  4.12it/s]

 79%|███████▉  | 23899/30196 [49:34<19:27,  5.39it/s]

 79%|███████▉  | 23900/30196 [49:34<19:01,  5.51it/s]

 79%|███████▉  | 23902/30196 [49:34<17:49,  5.89it/s]

 79%|███████▉  | 23903/30196 [49:34<17:11,  6.10it/s]

 79%|███████▉  | 23904/30196 [49:34<16:24,  6.39it/s]

 79%|███████▉  | 23906/30196 [49:34<12:05,  8.67it/s]

 79%|███████▉  | 23908/30196 [49:35<10:18, 10.17it/s]

 79%|███████▉  | 23910/30196 [49:35<09:31, 11.01it/s]

 79%|███████▉  | 23912/30196 [49:35<09:28, 11.06it/s]

 79%|███████▉  | 23914/30196 [49:35<11:09,  9.38it/s]

 79%|███████▉  | 23916/30196 [49:35<10:19, 10.14it/s]

 79%|███████▉  | 23918/30196 [49:35<09:18, 11.24it/s]

 79%|███████▉  | 23920/30196 [49:36<13:25,  7.79it/s]

 79%|███████▉  | 23921/30196 [49:36<12:56,  8.08it/s]

 79%|███████▉  | 23922/30196 [49:36<12:39,  8.26it/s]

 79%|███████▉  | 23923/30196 [49:36<13:43,  7.62it/s]

 79%|███████▉  | 23925/30196 [49:37<13:42,  7.62it/s]

 79%|███████▉  | 23927/30196 [49:37<13:13,  7.90it/s]

 79%|███████▉  | 23930/30196 [49:37<11:28,  9.10it/s]

 79%|███████▉  | 23932/30196 [49:37<10:09, 10.27it/s]

 79%|███████▉  | 23934/30196 [49:37<10:46,  9.68it/s]

 79%|███████▉  | 23936/30196 [49:38<09:55, 10.50it/s]

 79%|███████▉  | 23938/30196 [49:38<11:14,  9.28it/s]

 79%|███████▉  | 23940/30196 [49:38<10:22, 10.06it/s]

 79%|███████▉  | 23942/30196 [49:38<09:23, 11.10it/s]

 79%|███████▉  | 23944/30196 [49:38<09:03, 11.49it/s]

 79%|███████▉  | 23946/30196 [49:38<08:01, 12.99it/s]

 79%|███████▉  | 23948/30196 [49:39<09:22, 11.11it/s]

 79%|███████▉  | 23950/30196 [49:39<09:39, 10.77it/s]

 79%|███████▉  | 23952/30196 [49:39<12:50,  8.10it/s]

 79%|███████▉  | 23954/30196 [49:39<10:48,  9.62it/s]

 79%|███████▉  | 23956/30196 [49:40<11:04,  9.39it/s]

 79%|███████▉  | 23958/30196 [49:40<10:17, 10.10it/s]

 79%|███████▉  | 23960/30196 [49:40<10:19, 10.07it/s]

 79%|███████▉  | 23962/30196 [49:40<11:06,  9.35it/s]

 79%|███████▉  | 23964/30196 [49:40<11:59,  8.66it/s]

 79%|███████▉  | 23965/30196 [49:41<12:53,  8.06it/s]

 79%|███████▉  | 23966/30196 [49:41<14:53,  6.97it/s]

 79%|███████▉  | 23968/30196 [49:41<14:15,  7.28it/s]

 79%|███████▉  | 23970/30196 [49:41<11:44,  8.84it/s]

 79%|███████▉  | 23971/30196 [49:41<12:49,  8.09it/s]

 79%|███████▉  | 23972/30196 [49:42<13:05,  7.92it/s]

 79%|███████▉  | 23973/30196 [49:42<14:22,  7.22it/s]

 79%|███████▉  | 23974/30196 [49:42<16:46,  6.18it/s]

 79%|███████▉  | 23975/30196 [49:42<16:52,  6.14it/s]

 79%|███████▉  | 23977/30196 [49:42<12:47,  8.11it/s]

 79%|███████▉  | 23979/30196 [49:42<10:23,  9.98it/s]

 79%|███████▉  | 23981/30196 [49:43<09:20, 11.08it/s]

 79%|███████▉  | 23983/30196 [49:43<13:50,  7.48it/s]

 79%|███████▉  | 23984/30196 [49:43<13:22,  7.74it/s]

 79%|███████▉  | 23985/30196 [49:43<14:28,  7.15it/s]

 79%|███████▉  | 23986/30196 [49:43<13:36,  7.60it/s]

 79%|███████▉  | 23987/30196 [49:43<13:02,  7.94it/s]

 79%|███████▉  | 23988/30196 [49:44<14:11,  7.29it/s]

 79%|███████▉  | 23989/30196 [49:44<18:31,  5.59it/s]

 79%|███████▉  | 23991/30196 [49:44<12:58,  7.97it/s]

 79%|███████▉  | 23993/30196 [49:44<12:20,  8.38it/s]

 79%|███████▉  | 23994/30196 [49:44<12:06,  8.54it/s]

 79%|███████▉  | 23995/30196 [49:44<11:49,  8.75it/s]

 79%|███████▉  | 23997/30196 [49:45<11:31,  8.97it/s]

 79%|███████▉  | 23998/30196 [49:45<12:46,  8.09it/s]

 79%|███████▉  | 23999/30196 [49:45<13:11,  7.82it/s]

 79%|███████▉  | 24001/30196 [49:45<10:16, 10.04it/s]

 79%|███████▉  | 24003/30196 [49:45<10:08, 10.18it/s]

 79%|███████▉  | 24005/30196 [49:45<08:27, 12.19it/s]

 80%|███████▉  | 24007/30196 [49:46<09:20, 11.04it/s]

 80%|███████▉  | 24009/30196 [49:46<09:57, 10.36it/s]

 80%|███████▉  | 24011/30196 [49:46<08:59, 11.46it/s]

 80%|███████▉  | 24013/30196 [49:46<10:58,  9.38it/s]

 80%|███████▉  | 24015/30196 [49:46<10:08, 10.16it/s]

 80%|███████▉  | 24017/30196 [49:47<09:00, 11.42it/s]

 80%|███████▉  | 24019/30196 [49:47<10:05, 10.20it/s]

 80%|███████▉  | 24021/30196 [49:47<09:27, 10.88it/s]

 80%|███████▉  | 24023/30196 [49:47<12:55,  7.96it/s]

 80%|███████▉  | 24025/30196 [49:48<11:31,  8.93it/s]

 80%|███████▉  | 24027/30196 [49:48<13:16,  7.75it/s]

 80%|███████▉  | 24029/30196 [49:48<11:41,  8.79it/s]

 80%|███████▉  | 24031/30196 [49:48<10:26,  9.84it/s]

 80%|███████▉  | 24033/30196 [49:48<10:04, 10.19it/s]

 80%|███████▉  | 24035/30196 [49:49<12:29,  8.22it/s]

 80%|███████▉  | 24036/30196 [49:49<22:35,  4.55it/s]

 80%|███████▉  | 24037/30196 [49:50<21:28,  4.78it/s]

 80%|███████▉  | 24038/30196 [49:50<20:39,  4.97it/s]

 80%|███████▉  | 24040/30196 [49:50<15:27,  6.64it/s]

 80%|███████▉  | 24041/30196 [49:50<15:47,  6.50it/s]

 80%|███████▉  | 24043/30196 [49:50<14:23,  7.13it/s]

 80%|███████▉  | 24044/30196 [49:50<14:10,  7.24it/s]

 80%|███████▉  | 24045/30196 [49:51<15:58,  6.42it/s]

 80%|███████▉  | 24046/30196 [49:51<14:46,  6.94it/s]

 80%|███████▉  | 24047/30196 [49:51<13:43,  7.47it/s]

 80%|███████▉  | 24048/30196 [49:51<13:39,  7.50it/s]

 80%|███████▉  | 24050/30196 [49:51<13:40,  7.49it/s]

 80%|███████▉  | 24051/30196 [49:51<14:28,  7.07it/s]

 80%|███████▉  | 24052/30196 [49:51<13:39,  7.50it/s]

 80%|███████▉  | 24053/30196 [49:52<16:02,  6.38it/s]

 80%|███████▉  | 24055/30196 [49:52<12:01,  8.51it/s]

 80%|███████▉  | 24056/30196 [49:52<12:27,  8.21it/s]

 80%|███████▉  | 24057/30196 [49:52<14:58,  6.83it/s]

 80%|███████▉  | 24058/30196 [49:52<13:51,  7.38it/s]

 80%|███████▉  | 24059/30196 [49:53<16:27,  6.21it/s]

 80%|███████▉  | 24061/30196 [49:53<13:10,  7.76it/s]

 80%|███████▉  | 24062/30196 [49:53<19:25,  5.26it/s]

 80%|███████▉  | 24064/30196 [49:53<13:40,  7.47it/s]

 80%|███████▉  | 24066/30196 [49:54<14:39,  6.97it/s]

 80%|███████▉  | 24067/30196 [49:54<14:42,  6.94it/s]

 80%|███████▉  | 24069/30196 [49:54<11:52,  8.60it/s]

 80%|███████▉  | 24071/30196 [49:54<12:21,  8.26it/s]

 80%|███████▉  | 24072/30196 [49:54<13:23,  7.62it/s]

 80%|███████▉  | 24073/30196 [49:54<13:28,  7.57it/s]

 80%|███████▉  | 24074/30196 [49:55<18:09,  5.62it/s]

 80%|███████▉  | 24076/30196 [49:55<12:55,  7.89it/s]

 80%|███████▉  | 24078/30196 [49:55<10:11, 10.00it/s]

 80%|███████▉  | 24080/30196 [49:55<10:13,  9.96it/s]

 80%|███████▉  | 24082/30196 [49:55<09:58, 10.21it/s]

 80%|███████▉  | 24084/30196 [49:56<13:13,  7.70it/s]

 80%|███████▉  | 24085/30196 [49:56<16:34,  6.15it/s]

 80%|███████▉  | 24086/30196 [49:56<16:38,  6.12it/s]

 80%|███████▉  | 24087/30196 [49:56<15:21,  6.63it/s]

 80%|███████▉  | 24088/30196 [49:56<17:04,  5.96it/s]

 80%|███████▉  | 24089/30196 [49:57<15:31,  6.56it/s]

 80%|███████▉  | 24090/30196 [49:57<16:00,  6.36it/s]

 80%|███████▉  | 24092/30196 [49:57<12:56,  7.86it/s]

 80%|███████▉  | 24094/30196 [49:57<11:29,  8.85it/s]

 80%|███████▉  | 24095/30196 [49:57<11:18,  8.99it/s]

 80%|███████▉  | 24096/30196 [49:57<11:16,  9.01it/s]

 80%|███████▉  | 24098/30196 [49:57<09:48, 10.36it/s]

 80%|███████▉  | 24100/30196 [49:58<09:17, 10.94it/s]

 80%|███████▉  | 24102/30196 [49:58<11:25,  8.89it/s]

 80%|███████▉  | 24104/30196 [49:58<10:52,  9.34it/s]

 80%|███████▉  | 24105/30196 [49:58<11:31,  8.80it/s]

 80%|███████▉  | 24107/30196 [49:58<10:40,  9.51it/s]

 80%|███████▉  | 24108/30196 [49:59<11:57,  8.49it/s]

 80%|███████▉  | 24110/30196 [49:59<09:51, 10.30it/s]

 80%|███████▉  | 24112/30196 [49:59<10:51,  9.33it/s]

 80%|███████▉  | 24114/30196 [49:59<12:34,  8.06it/s]

 80%|███████▉  | 24116/30196 [50:00<12:53,  7.86it/s]

 80%|███████▉  | 24118/30196 [50:00<11:12,  9.04it/s]

 80%|███████▉  | 24119/30196 [50:00<11:38,  8.70it/s]

 80%|███████▉  | 24121/30196 [50:00<11:09,  9.08it/s]

 80%|███████▉  | 24122/30196 [50:00<11:08,  9.09it/s]

 80%|███████▉  | 24124/30196 [50:00<09:45, 10.38it/s]

 80%|███████▉  | 24126/30196 [50:00<09:01, 11.20it/s]

 80%|███████▉  | 24128/30196 [50:01<09:08, 11.07it/s]

 80%|███████▉  | 24130/30196 [50:01<09:11, 11.01it/s]

 80%|███████▉  | 24132/30196 [50:01<08:41, 11.64it/s]

 80%|███████▉  | 24134/30196 [50:01<11:59,  8.42it/s]

 80%|███████▉  | 24136/30196 [50:02<10:36,  9.52it/s]

 80%|███████▉  | 24138/30196 [50:02<21:09,  4.77it/s]

 80%|███████▉  | 24139/30196 [50:03<22:57,  4.40it/s]

 80%|███████▉  | 24141/30196 [50:03<18:21,  5.50it/s]

 80%|███████▉  | 24142/30196 [50:03<19:07,  5.28it/s]

 80%|███████▉  | 24144/30196 [50:03<14:57,  6.74it/s]

 80%|███████▉  | 24145/30196 [50:03<14:34,  6.92it/s]

 80%|███████▉  | 24147/30196 [50:04<12:22,  8.14it/s]

 80%|███████▉  | 24148/30196 [50:04<13:30,  7.46it/s]

 80%|███████▉  | 24150/30196 [50:04<11:15,  8.95it/s]

 80%|███████▉  | 24151/30196 [50:04<11:39,  8.64it/s]

 80%|███████▉  | 24153/30196 [50:04<10:58,  9.17it/s]

 80%|███████▉  | 24154/30196 [50:04<12:10,  8.28it/s]

 80%|███████▉  | 24155/30196 [50:05<12:24,  8.11it/s]

 80%|████████  | 24157/30196 [50:05<10:05,  9.98it/s]

 80%|████████  | 24159/30196 [50:05<08:50, 11.37it/s]

 80%|████████  | 24161/30196 [50:05<09:15, 10.86it/s]

 80%|████████  | 24163/30196 [50:05<09:32, 10.55it/s]

 80%|████████  | 24165/30196 [50:05<09:22, 10.73it/s]

 80%|████████  | 24167/30196 [50:06<12:31,  8.03it/s]

 80%|████████  | 24169/30196 [50:06<10:41,  9.40it/s]

 80%|████████  | 24171/30196 [50:06<09:46, 10.27it/s]

 80%|████████  | 24173/30196 [50:06<09:05, 11.04it/s]

 80%|████████  | 24175/30196 [50:07<10:54,  9.20it/s]

 80%|████████  | 24177/30196 [50:07<10:10,  9.85it/s]

 80%|████████  | 24179/30196 [50:07<10:06,  9.92it/s]

 80%|████████  | 24181/30196 [50:07<09:54, 10.12it/s]

 80%|████████  | 24183/30196 [50:07<08:58, 11.16it/s]

 80%|████████  | 24185/30196 [50:08<11:16,  8.89it/s]

 80%|████████  | 24187/30196 [50:08<12:51,  7.79it/s]

 80%|████████  | 24188/30196 [50:08<12:31,  7.99it/s]

 80%|████████  | 24189/30196 [50:08<13:19,  7.51it/s]

 80%|████████  | 24191/30196 [50:08<10:18,  9.70it/s]

 80%|████████  | 24193/30196 [50:08<09:52, 10.13it/s]

 80%|████████  | 24195/30196 [50:09<10:13,  9.78it/s]

 80%|████████  | 24197/30196 [50:09<09:55, 10.08it/s]

 80%|████████  | 24199/30196 [50:09<11:39,  8.57it/s]

 80%|████████  | 24201/30196 [50:09<10:49,  9.23it/s]

 80%|████████  | 24202/30196 [50:09<11:17,  8.84it/s]

 80%|████████  | 24203/30196 [50:10<12:26,  8.02it/s]

 80%|████████  | 24205/30196 [50:10<10:53,  9.17it/s]

 80%|████████  | 24206/30196 [50:11<29:08,  3.43it/s]

 80%|████████  | 24208/30196 [50:11<21:54,  4.56it/s]

 80%|████████  | 24210/30196 [50:11<17:51,  5.58it/s]

 80%|████████  | 24213/30196 [50:11<12:47,  7.79it/s]

 80%|████████  | 24215/30196 [50:11<10:33,  9.44it/s]

 80%|████████  | 24217/30196 [50:12<10:41,  9.32it/s]

 80%|████████  | 24219/30196 [50:12<11:40,  8.54it/s]

 80%|████████  | 24221/30196 [50:12<10:20,  9.63it/s]

 80%|████████  | 24223/30196 [50:12<11:38,  8.56it/s]

 80%|████████  | 24225/30196 [50:13<12:21,  8.06it/s]

 80%|████████  | 24227/30196 [50:13<12:10,  8.17it/s]

 80%|████████  | 24228/30196 [50:13<13:08,  7.57it/s]

 80%|████████  | 24229/30196 [50:13<13:12,  7.53it/s]

 80%|████████  | 24230/30196 [50:13<14:15,  6.98it/s]

 80%|████████  | 24231/30196 [50:14<16:08,  6.16it/s]

 80%|████████  | 24232/30196 [50:14<14:42,  6.76it/s]

 80%|████████  | 24234/30196 [50:14<10:44,  9.25it/s]

 80%|████████  | 24236/30196 [50:14<10:28,  9.48it/s]

 80%|████████  | 24238/30196 [50:15<15:31,  6.40it/s]

 80%|████████  | 24239/30196 [50:15<14:59,  6.62it/s]

 80%|████████  | 24240/30196 [50:15<19:00,  5.22it/s]

 80%|████████  | 24241/30196 [50:15<16:57,  5.85it/s]

 80%|████████  | 24242/30196 [50:15<16:03,  6.18it/s]

 80%|████████  | 24244/30196 [50:16<14:38,  6.78it/s]

 80%|████████  | 24246/30196 [50:16<13:18,  7.45it/s]

 80%|████████  | 24248/30196 [50:16<11:51,  8.36it/s]

 80%|████████  | 24249/30196 [50:16<12:05,  8.20it/s]

 80%|████████  | 24251/30196 [50:16<11:40,  8.48it/s]

 80%|████████  | 24252/30196 [50:16<12:16,  8.07it/s]

 80%|████████  | 24253/30196 [50:17<11:57,  8.28it/s]

 80%|████████  | 24254/30196 [50:17<14:10,  6.98it/s]

 80%|████████  | 24256/30196 [50:17<10:45,  9.20it/s]

 80%|████████  | 24258/30196 [50:17<10:10,  9.73it/s]

 80%|████████  | 24260/30196 [50:17<10:44,  9.22it/s]

 80%|████████  | 24261/30196 [50:17<12:40,  7.81it/s]

 80%|████████  | 24263/30196 [50:18<10:29,  9.43it/s]

 80%|████████  | 24265/30196 [50:18<10:58,  9.00it/s]

 80%|████████  | 24266/30196 [50:18<11:22,  8.69it/s]

 80%|████████  | 24268/30196 [50:18<11:29,  8.59it/s]

 80%|████████  | 24270/30196 [50:18<11:04,  8.92it/s]

 80%|████████  | 24272/30196 [50:19<11:54,  8.29it/s]

 80%|████████  | 24273/30196 [50:19<12:16,  8.04it/s]

 80%|████████  | 24275/30196 [50:19<09:49, 10.04it/s]

 80%|████████  | 24277/30196 [50:19<10:24,  9.48it/s]

 80%|████████  | 24279/30196 [50:19<09:57,  9.90it/s]

 80%|████████  | 24281/30196 [50:20<11:46,  8.37it/s]

 80%|████████  | 24282/30196 [50:20<12:09,  8.10it/s]

 80%|████████  | 24283/30196 [50:20<12:19,  7.99it/s]

 80%|████████  | 24284/30196 [50:20<14:08,  6.97it/s]

 80%|████████  | 24285/30196 [50:20<13:11,  7.47it/s]

 80%|████████  | 24287/30196 [50:21<13:01,  7.56it/s]

 80%|████████  | 24288/30196 [50:21<16:07,  6.11it/s]

 80%|████████  | 24290/30196 [50:21<13:20,  7.38it/s]

 80%|████████  | 24291/30196 [50:21<13:13,  7.44it/s]

 80%|████████  | 24293/30196 [50:21<10:08,  9.69it/s]

 80%|████████  | 24295/30196 [50:21<08:33, 11.48it/s]

 80%|████████  | 24297/30196 [50:22<10:26,  9.41it/s]

 80%|████████  | 24299/30196 [50:22<10:38,  9.24it/s]

 80%|████████  | 24301/30196 [50:22<11:05,  8.86it/s]

 80%|████████  | 24302/30196 [50:22<11:24,  8.62it/s]

 80%|████████  | 24303/30196 [50:22<11:09,  8.80it/s]

 80%|████████  | 24304/30196 [50:22<10:57,  8.96it/s]

 80%|████████  | 24305/30196 [50:23<12:21,  7.94it/s]

 80%|████████  | 24306/30196 [50:23<13:41,  7.17it/s]

 80%|████████  | 24307/30196 [50:23<18:35,  5.28it/s]

 81%|████████  | 24309/30196 [50:23<14:15,  6.88it/s]

 81%|████████  | 24310/30196 [50:23<13:20,  7.36it/s]

 81%|████████  | 24311/30196 [50:24<24:02,  4.08it/s]

 81%|████████  | 24312/30196 [50:24<20:25,  4.80it/s]

 81%|████████  | 24314/30196 [50:24<15:05,  6.50it/s]

 81%|████████  | 24315/30196 [50:25<20:24,  4.80it/s]

 81%|████████  | 24316/30196 [50:25<20:19,  4.82it/s]

 81%|████████  | 24318/30196 [50:25<15:15,  6.42it/s]

 81%|████████  | 24320/30196 [50:25<13:34,  7.21it/s]

 81%|████████  | 24322/30196 [50:25<11:22,  8.60it/s]

 81%|████████  | 24324/30196 [50:26<10:12,  9.59it/s]

 81%|████████  | 24326/30196 [50:26<09:47, 10.00it/s]

 81%|████████  | 24328/30196 [50:26<10:57,  8.92it/s]

 81%|████████  | 24329/30196 [50:26<10:55,  8.95it/s]

 81%|████████  | 24330/30196 [50:26<10:49,  9.04it/s]

 81%|████████  | 24331/30196 [50:26<11:37,  8.41it/s]

 81%|████████  | 24332/30196 [50:27<12:43,  7.68it/s]

 81%|████████  | 24333/30196 [50:27<12:05,  8.08it/s]

 81%|████████  | 24334/30196 [50:27<11:35,  8.43it/s]

 81%|████████  | 24335/30196 [50:27<12:17,  7.95it/s]

 81%|████████  | 24337/30196 [50:27<14:16,  6.84it/s]

 81%|████████  | 24338/30196 [50:27<13:17,  7.35it/s]

 81%|████████  | 24339/30196 [50:27<12:53,  7.57it/s]

 81%|████████  | 24340/30196 [50:28<27:57,  3.49it/s]

 81%|████████  | 24341/30196 [50:28<23:53,  4.09it/s]

 81%|████████  | 24342/30196 [50:28<21:56,  4.45it/s]

 81%|████████  | 24343/30196 [50:29<18:34,  5.25it/s]

 81%|████████  | 24344/30196 [50:29<17:10,  5.68it/s]

 81%|████████  | 24346/30196 [50:29<11:54,  8.18it/s]

 81%|████████  | 24348/30196 [50:29<11:26,  8.52it/s]

 81%|████████  | 24349/30196 [50:29<11:44,  8.30it/s]

 81%|████████  | 24350/30196 [50:29<12:20,  7.89it/s]

 81%|████████  | 24352/30196 [50:29<10:36,  9.18it/s]

 81%|████████  | 24355/30196 [50:30<07:48, 12.47it/s]

 81%|████████  | 24357/30196 [50:30<10:03,  9.68it/s]

 81%|████████  | 24359/30196 [50:30<09:48,  9.92it/s]

 81%|████████  | 24361/30196 [50:30<09:50,  9.88it/s]

 81%|████████  | 24363/30196 [50:31<11:00,  8.83it/s]

 81%|████████  | 24364/30196 [50:31<10:56,  8.88it/s]

 81%|████████  | 24366/30196 [50:31<10:51,  8.94it/s]

 81%|████████  | 24367/30196 [50:31<11:13,  8.66it/s]

 81%|████████  | 24368/30196 [50:31<11:28,  8.46it/s]

 81%|████████  | 24369/30196 [50:31<11:18,  8.59it/s]

 81%|████████  | 24370/30196 [50:31<11:35,  8.37it/s]

 81%|████████  | 24371/30196 [50:32<11:19,  8.58it/s]

 81%|████████  | 24372/30196 [50:32<12:48,  7.57it/s]

 81%|████████  | 24373/30196 [50:32<12:43,  7.63it/s]

 81%|████████  | 24374/30196 [50:32<13:52,  7.00it/s]

 81%|████████  | 24375/30196 [50:32<14:36,  6.64it/s]

 81%|████████  | 24376/30196 [50:32<16:12,  5.99it/s]

 81%|████████  | 24378/30196 [50:33<12:07,  8.00it/s]

 81%|████████  | 24380/30196 [50:33<11:35,  8.36it/s]

 81%|████████  | 24381/30196 [50:33<12:39,  7.66it/s]

 81%|████████  | 24383/30196 [50:33<10:49,  8.95it/s]

 81%|████████  | 24384/30196 [50:33<13:04,  7.41it/s]

 81%|████████  | 24385/30196 [50:33<13:50,  7.00it/s]

 81%|████████  | 24386/30196 [50:34<13:48,  7.01it/s]

 81%|████████  | 24387/30196 [50:34<12:57,  7.47it/s]

 81%|████████  | 24389/30196 [50:34<10:30,  9.21it/s]

 81%|████████  | 24390/30196 [50:34<11:03,  8.75it/s]

 81%|████████  | 24391/30196 [50:34<11:42,  8.26it/s]

 81%|████████  | 24393/30196 [50:34<10:32,  9.17it/s]

 81%|████████  | 24394/30196 [50:34<11:00,  8.78it/s]

 81%|████████  | 24395/30196 [50:35<11:25,  8.46it/s]

 81%|████████  | 24396/30196 [50:35<11:12,  8.62it/s]

 81%|████████  | 24397/30196 [50:35<11:34,  8.35it/s]

 81%|████████  | 24398/30196 [50:35<11:59,  8.05it/s]

 81%|████████  | 24399/30196 [50:35<12:15,  7.88it/s]

 81%|████████  | 24401/30196 [50:35<10:02,  9.62it/s]

 81%|████████  | 24403/30196 [50:35<08:56, 10.80it/s]

 81%|████████  | 24405/30196 [50:36<12:13,  7.90it/s]

 81%|████████  | 24407/30196 [50:36<10:26,  9.24it/s]

 81%|████████  | 24409/30196 [50:36<10:28,  9.21it/s]

 81%|████████  | 24411/30196 [50:36<10:30,  9.17it/s]

 81%|████████  | 24413/30196 [50:37<09:53,  9.74it/s]

 81%|████████  | 24415/30196 [50:37<08:26, 11.42it/s]

 81%|████████  | 24417/30196 [50:37<08:42, 11.05it/s]

 81%|████████  | 24419/30196 [50:37<09:27, 10.19it/s]

 81%|████████  | 24421/30196 [50:37<11:01,  8.73it/s]

 81%|████████  | 24422/30196 [50:38<11:57,  8.04it/s]

 81%|████████  | 24423/30196 [50:38<12:23,  7.76it/s]

 81%|████████  | 24424/30196 [50:38<13:15,  7.26it/s]

 81%|████████  | 24425/30196 [50:38<15:00,  6.41it/s]

 81%|████████  | 24426/30196 [50:38<13:51,  6.94it/s]

 81%|████████  | 24427/30196 [50:38<15:27,  6.22it/s]

 81%|████████  | 24428/30196 [50:39<14:03,  6.84it/s]

 81%|████████  | 24430/30196 [50:39<11:05,  8.67it/s]

 81%|████████  | 24432/30196 [50:39<09:19, 10.30it/s]

 81%|████████  | 24434/30196 [50:39<08:46, 10.94it/s]

 81%|████████  | 24436/30196 [50:39<09:46,  9.82it/s]

 81%|████████  | 24438/30196 [50:39<10:32,  9.11it/s]

 81%|████████  | 24439/30196 [50:40<11:36,  8.26it/s]

 81%|████████  | 24440/30196 [50:40<13:18,  7.21it/s]

 81%|████████  | 24442/30196 [50:40<11:34,  8.29it/s]

 81%|████████  | 24443/30196 [50:40<12:07,  7.91it/s]

 81%|████████  | 24445/30196 [50:40<11:41,  8.20it/s]

 81%|████████  | 24446/30196 [50:41<12:47,  7.49it/s]

 81%|████████  | 24448/30196 [50:41<10:53,  8.79it/s]

 81%|████████  | 24450/30196 [50:41<08:52, 10.79it/s]

 81%|████████  | 24452/30196 [50:41<11:27,  8.36it/s]

 81%|████████  | 24454/30196 [50:41<12:07,  7.89it/s]

 81%|████████  | 24456/30196 [50:42<10:44,  8.90it/s]

 81%|████████  | 24458/30196 [50:42<09:07, 10.49it/s]

 81%|████████  | 24460/30196 [50:42<10:39,  8.96it/s]

 81%|████████  | 24462/30196 [50:42<11:02,  8.66it/s]

 81%|████████  | 24463/30196 [50:42<11:52,  8.04it/s]

 81%|████████  | 24464/30196 [50:43<12:19,  7.75it/s]

 81%|████████  | 24466/30196 [50:43<10:41,  8.93it/s]

 81%|████████  | 24468/30196 [50:43<09:09, 10.43it/s]

 81%|████████  | 24471/30196 [50:43<08:14, 11.57it/s]

 81%|████████  | 24473/30196 [50:43<08:38, 11.04it/s]

 81%|████████  | 24475/30196 [50:43<07:47, 12.24it/s]

 81%|████████  | 24477/30196 [50:44<09:07, 10.45it/s]

 81%|████████  | 24479/30196 [50:44<10:08,  9.39it/s]

 81%|████████  | 24481/30196 [50:44<09:23, 10.15it/s]

 81%|████████  | 24483/30196 [50:44<10:35,  8.99it/s]

 81%|████████  | 24484/30196 [50:45<12:18,  7.74it/s]

 81%|████████  | 24485/30196 [50:45<11:56,  7.97it/s]

 81%|████████  | 24486/30196 [50:45<13:40,  6.96it/s]

 81%|████████  | 24488/30196 [50:45<11:03,  8.61it/s]

 81%|████████  | 24490/30196 [50:45<10:27,  9.09it/s]

 81%|████████  | 24492/30196 [50:46<10:38,  8.94it/s]

 81%|████████  | 24494/30196 [50:46<09:12, 10.32it/s]

 81%|████████  | 24496/30196 [50:46<08:42, 10.91it/s]

 81%|████████  | 24498/30196 [50:46<07:34, 12.53it/s]

 81%|████████  | 24500/30196 [50:46<06:54, 13.73it/s]

 81%|████████  | 24502/30196 [50:46<07:54, 12.01it/s]

 81%|████████  | 24504/30196 [50:47<10:51,  8.74it/s]

 81%|████████  | 24506/30196 [50:47<11:11,  8.47it/s]

 81%|████████  | 24507/30196 [50:47<11:24,  8.31it/s]

 81%|████████  | 24508/30196 [50:47<11:37,  8.15it/s]

 81%|████████  | 24509/30196 [50:47<12:11,  7.78it/s]

 81%|████████  | 24511/30196 [50:48<11:42,  8.09it/s]

 81%|████████  | 24512/30196 [50:48<12:38,  7.49it/s]

 81%|████████  | 24514/30196 [50:48<10:01,  9.44it/s]

 81%|████████  | 24516/30196 [50:48<14:51,  6.37it/s]

 81%|████████  | 24518/30196 [50:48<12:26,  7.60it/s]

 81%|████████  | 24520/30196 [50:49<12:18,  7.68it/s]

 81%|████████  | 24522/30196 [50:49<12:04,  7.84it/s]

 81%|████████  | 24523/30196 [50:49<12:49,  7.37it/s]

 81%|████████  | 24525/30196 [50:49<11:16,  8.38it/s]

 81%|████████  | 24526/30196 [50:49<11:34,  8.17it/s]

 81%|████████  | 24527/30196 [50:50<11:53,  7.95it/s]

 81%|████████  | 24529/30196 [50:50<09:47,  9.65it/s]

 81%|████████  | 24531/30196 [50:50<11:19,  8.34it/s]

 81%|████████  | 24532/30196 [50:50<11:03,  8.54it/s]

 81%|████████  | 24534/30196 [50:50<11:22,  8.29it/s]

 81%|████████▏ | 24536/30196 [50:51<10:06,  9.33it/s]

 81%|████████▏ | 24537/30196 [50:51<11:12,  8.42it/s]

 81%|████████▏ | 24538/30196 [50:51<14:37,  6.45it/s]

 81%|████████▏ | 24539/30196 [50:51<14:17,  6.60it/s]

 81%|████████▏ | 24541/30196 [50:51<12:06,  7.79it/s]

 81%|████████▏ | 24543/30196 [50:52<12:05,  7.79it/s]

 81%|████████▏ | 24544/30196 [50:52<12:08,  7.76it/s]

 81%|████████▏ | 24545/30196 [50:52<12:56,  7.28it/s]

 81%|████████▏ | 24546/30196 [50:52<12:52,  7.31it/s]

 81%|████████▏ | 24548/30196 [50:52<11:09,  8.44it/s]

 81%|████████▏ | 24550/30196 [50:52<09:42,  9.69it/s]

 81%|████████▏ | 24551/30196 [50:52<09:51,  9.55it/s]

 81%|████████▏ | 24552/30196 [50:53<11:13,  8.38it/s]

 81%|████████▏ | 24553/30196 [50:53<10:53,  8.63it/s]

 81%|████████▏ | 24555/30196 [50:53<10:23,  9.05it/s]

 81%|████████▏ | 24557/30196 [50:53<10:19,  9.11it/s]

 81%|████████▏ | 24559/30196 [50:53<09:20, 10.06it/s]

 81%|████████▏ | 24561/30196 [50:53<08:48, 10.66it/s]

 81%|████████▏ | 24563/30196 [50:54<08:41, 10.81it/s]

 81%|████████▏ | 24565/30196 [50:54<10:28,  8.96it/s]

 81%|████████▏ | 24566/30196 [50:54<16:56,  5.54it/s]

 81%|████████▏ | 24568/30196 [50:55<14:13,  6.59it/s]

 81%|████████▏ | 24569/30196 [50:55<14:38,  6.40it/s]

 81%|████████▏ | 24570/30196 [50:55<15:58,  5.87it/s]

 81%|████████▏ | 24572/30196 [50:55<13:57,  6.71it/s]

 81%|████████▏ | 24573/30196 [50:55<15:16,  6.14it/s]

 81%|████████▏ | 24574/30196 [50:56<14:39,  6.39it/s]

 81%|████████▏ | 24577/30196 [50:56<10:46,  8.69it/s]

 81%|████████▏ | 24579/30196 [50:56<09:46,  9.57it/s]

 81%|████████▏ | 24581/30196 [50:56<09:17, 10.06it/s]

 81%|████████▏ | 24583/30196 [50:56<08:48, 10.62it/s]

 81%|████████▏ | 24585/30196 [50:57<09:37,  9.71it/s]

 81%|████████▏ | 24586/30196 [50:57<09:39,  9.69it/s]

 81%|████████▏ | 24587/30196 [50:57<13:06,  7.13it/s]

 81%|████████▏ | 24589/30196 [50:57<11:19,  8.25it/s]

 81%|████████▏ | 24590/30196 [50:57<12:21,  7.56it/s]

 81%|████████▏ | 24591/30196 [50:58<13:20,  7.00it/s]

 81%|████████▏ | 24593/30196 [50:58<12:46,  7.31it/s]

 81%|████████▏ | 24595/30196 [50:58<11:09,  8.36it/s]

 81%|████████▏ | 24597/30196 [50:58<10:28,  8.90it/s]

 81%|████████▏ | 24598/30196 [50:58<11:40,  7.99it/s]

 81%|████████▏ | 24599/30196 [50:58<11:34,  8.06it/s]

 81%|████████▏ | 24600/30196 [50:59<11:07,  8.38it/s]

 81%|████████▏ | 24601/30196 [50:59<14:19,  6.51it/s]

 81%|████████▏ | 24602/30196 [50:59<14:00,  6.66it/s]

 81%|████████▏ | 24604/30196 [50:59<12:56,  7.20it/s]

 81%|████████▏ | 24605/30196 [50:59<12:44,  7.31it/s]

 81%|████████▏ | 24607/30196 [51:00<10:53,  8.55it/s]

 81%|████████▏ | 24608/30196 [51:00<10:41,  8.71it/s]

 81%|████████▏ | 24609/30196 [51:00<12:45,  7.30it/s]

 82%|████████▏ | 24612/30196 [51:00<08:24, 11.06it/s]

 82%|████████▏ | 24614/30196 [51:00<08:28, 10.98it/s]

 82%|████████▏ | 24616/30196 [51:00<10:48,  8.60it/s]

 82%|████████▏ | 24618/30196 [51:01<11:52,  7.83it/s]

 82%|████████▏ | 24619/30196 [51:01<11:34,  8.03it/s]

 82%|████████▏ | 24620/30196 [51:01<12:38,  7.35it/s]

 82%|████████▏ | 24621/30196 [51:01<14:24,  6.45it/s]

 82%|████████▏ | 24623/30196 [51:01<11:06,  8.36it/s]

 82%|████████▏ | 24624/30196 [51:02<13:22,  6.94it/s]

 82%|████████▏ | 24625/30196 [51:02<14:55,  6.22it/s]

 82%|████████▏ | 24626/30196 [51:02<15:01,  6.18it/s]

 82%|████████▏ | 24627/30196 [51:02<15:21,  6.04it/s]

 82%|████████▏ | 24628/30196 [51:02<15:28,  6.00it/s]

 82%|████████▏ | 24630/30196 [51:03<12:01,  7.72it/s]

 82%|████████▏ | 24631/30196 [51:03<12:09,  7.63it/s]

 82%|████████▏ | 24633/30196 [51:03<11:24,  8.13it/s]

 82%|████████▏ | 24634/30196 [51:03<11:33,  8.02it/s]

 82%|████████▏ | 24635/30196 [51:03<12:01,  7.70it/s]

 82%|████████▏ | 24637/30196 [51:03<10:57,  8.45it/s]

 82%|████████▏ | 24638/30196 [51:04<11:18,  8.19it/s]

 82%|████████▏ | 24640/30196 [51:04<08:52, 10.43it/s]

 82%|████████▏ | 24642/30196 [51:04<09:49,  9.42it/s]

 82%|████████▏ | 24644/30196 [51:04<11:59,  7.72it/s]

 82%|████████▏ | 24646/30196 [51:04<11:28,  8.06it/s]

 82%|████████▏ | 24648/30196 [51:05<09:31,  9.70it/s]

 82%|████████▏ | 24650/30196 [51:05<09:13, 10.02it/s]

 82%|████████▏ | 24652/30196 [51:05<09:39,  9.57it/s]

 82%|████████▏ | 24654/30196 [51:05<10:30,  8.78it/s]

 82%|████████▏ | 24655/30196 [51:05<10:27,  8.84it/s]

 82%|████████▏ | 24656/30196 [51:06<10:46,  8.58it/s]

 82%|████████▏ | 24657/30196 [51:06<11:15,  8.19it/s]

 82%|████████▏ | 24658/30196 [51:06<11:25,  8.08it/s]

 82%|████████▏ | 24659/30196 [51:06<11:06,  8.31it/s]

 82%|████████▏ | 24661/30196 [51:06<09:30,  9.70it/s]

 82%|████████▏ | 24663/30196 [51:06<10:01,  9.20it/s]

 82%|████████▏ | 24665/30196 [51:06<09:26,  9.77it/s]

 82%|████████▏ | 24667/30196 [51:07<08:20, 11.05it/s]

 82%|████████▏ | 24669/30196 [51:07<08:16, 11.13it/s]

 82%|████████▏ | 24671/30196 [51:07<09:09, 10.06it/s]

 82%|████████▏ | 24673/30196 [51:07<10:05,  9.11it/s]

 82%|████████▏ | 24675/30196 [51:07<08:52, 10.36it/s]

 82%|████████▏ | 24677/30196 [51:08<10:28,  8.78it/s]

 82%|████████▏ | 24678/30196 [51:08<11:22,  8.08it/s]

 82%|████████▏ | 24680/30196 [51:08<10:05,  9.12it/s]

 82%|████████▏ | 24681/30196 [51:08<10:31,  8.74it/s]

 82%|████████▏ | 24683/30196 [51:08<09:05, 10.10it/s]

 82%|████████▏ | 24685/30196 [51:09<13:07,  7.00it/s]

 82%|████████▏ | 24686/30196 [51:09<12:32,  7.32it/s]

 82%|████████▏ | 24688/30196 [51:09<11:03,  8.31it/s]

 82%|████████▏ | 24689/30196 [51:09<11:14,  8.16it/s]

 82%|████████▏ | 24690/30196 [51:09<12:56,  7.09it/s]

 82%|████████▏ | 24691/30196 [51:10<12:08,  7.55it/s]

 82%|████████▏ | 24694/30196 [51:10<09:35,  9.55it/s]

 82%|████████▏ | 24696/30196 [51:10<09:20,  9.81it/s]

 82%|████████▏ | 24697/30196 [51:10<10:01,  9.15it/s]

 82%|████████▏ | 24699/30196 [51:10<08:20, 10.99it/s]

 82%|████████▏ | 24701/30196 [51:10<09:21,  9.79it/s]

 82%|████████▏ | 24703/30196 [51:11<12:06,  7.56it/s]

 82%|████████▏ | 24705/30196 [51:12<22:43,  4.03it/s]

 82%|████████▏ | 24707/30196 [51:12<19:00,  4.81it/s]

 82%|████████▏ | 24708/30196 [51:12<18:56,  4.83it/s]

 82%|████████▏ | 24710/30196 [51:12<14:53,  6.14it/s]

 82%|████████▏ | 24711/30196 [51:13<13:50,  6.60it/s]

 82%|████████▏ | 24712/30196 [51:13<12:52,  7.10it/s]

 82%|████████▏ | 24713/30196 [51:13<12:38,  7.23it/s]

 82%|████████▏ | 24714/30196 [51:13<11:59,  7.62it/s]

 82%|████████▏ | 24716/30196 [51:13<11:01,  8.28it/s]

 82%|████████▏ | 24717/30196 [51:13<10:42,  8.53it/s]

 82%|████████▏ | 24718/30196 [51:13<11:53,  7.68it/s]

 82%|████████▏ | 24720/30196 [51:14<10:20,  8.82it/s]

 82%|████████▏ | 24722/30196 [51:14<08:46, 10.39it/s]

 82%|████████▏ | 24724/30196 [51:14<11:47,  7.74it/s]

 82%|████████▏ | 24725/30196 [51:14<11:49,  7.71it/s]

 82%|████████▏ | 24726/30196 [51:14<13:20,  6.84it/s]

 82%|████████▏ | 24728/30196 [51:15<10:05,  9.03it/s]

 82%|████████▏ | 24730/30196 [51:15<10:21,  8.80it/s]

 82%|████████▏ | 24732/30196 [51:15<11:23,  8.00it/s]

 82%|████████▏ | 24733/30196 [51:15<13:59,  6.51it/s]

 82%|████████▏ | 24734/30196 [51:15<13:35,  6.70it/s]

 82%|████████▏ | 24735/30196 [51:16<15:06,  6.03it/s]

 82%|████████▏ | 24737/30196 [51:16<13:40,  6.65it/s]

 82%|████████▏ | 24738/30196 [51:16<13:15,  6.86it/s]

 82%|████████▏ | 24739/30196 [51:16<12:59,  7.00it/s]

 82%|████████▏ | 24741/30196 [51:16<10:44,  8.47it/s]

 82%|████████▏ | 24743/30196 [51:16<09:11,  9.88it/s]

 82%|████████▏ | 24745/30196 [51:17<08:27, 10.73it/s]

 82%|████████▏ | 24747/30196 [51:17<09:37,  9.43it/s]

 82%|████████▏ | 24749/30196 [51:17<09:47,  9.27it/s]

 82%|████████▏ | 24750/30196 [51:17<09:49,  9.24it/s]

 82%|████████▏ | 24751/30196 [51:17<09:49,  9.24it/s]

 82%|████████▏ | 24752/30196 [51:18<13:01,  6.97it/s]

 82%|████████▏ | 24754/30196 [51:18<10:43,  8.45it/s]

 82%|████████▏ | 24756/30196 [51:18<09:04, 10.00it/s]

 82%|████████▏ | 24758/30196 [51:18<11:13,  8.08it/s]

 82%|████████▏ | 24760/30196 [51:18<10:16,  8.82it/s]

 82%|████████▏ | 24761/30196 [51:19<10:38,  8.52it/s]

 82%|████████▏ | 24762/30196 [51:19<11:32,  7.84it/s]

 82%|████████▏ | 24764/30196 [51:19<09:38,  9.39it/s]

 82%|████████▏ | 24765/30196 [51:19<09:42,  9.32it/s]

 82%|████████▏ | 24766/30196 [51:19<10:12,  8.87it/s]

 82%|████████▏ | 24768/30196 [51:19<08:49, 10.25it/s]

 82%|████████▏ | 24770/30196 [51:20<10:34,  8.55it/s]

 82%|████████▏ | 24771/30196 [51:20<10:49,  8.35it/s]

 82%|████████▏ | 24772/30196 [51:20<11:54,  7.59it/s]

 82%|████████▏ | 24774/30196 [51:20<10:20,  8.73it/s]

 82%|████████▏ | 24775/30196 [51:20<15:30,  5.83it/s]

 82%|████████▏ | 24776/30196 [51:21<15:39,  5.77it/s]

 82%|████████▏ | 24778/30196 [51:21<11:27,  7.88it/s]

 82%|████████▏ | 24780/30196 [51:21<09:30,  9.49it/s]

 82%|████████▏ | 24782/30196 [51:21<10:36,  8.50it/s]

 82%|████████▏ | 24783/30196 [51:21<10:27,  8.62it/s]

 82%|████████▏ | 24784/30196 [51:21<10:45,  8.39it/s]

 82%|████████▏ | 24786/30196 [51:22<09:41,  9.30it/s]

 82%|████████▏ | 24787/30196 [51:22<09:38,  9.34it/s]

 82%|████████▏ | 24789/30196 [51:22<11:59,  7.52it/s]

 82%|████████▏ | 24790/30196 [51:22<13:23,  6.73it/s]

 82%|████████▏ | 24792/30196 [51:23<13:18,  6.76it/s]

 82%|████████▏ | 24794/30196 [51:23<10:26,  8.62it/s]

 82%|████████▏ | 24796/30196 [51:23<10:58,  8.20it/s]

 82%|████████▏ | 24798/30196 [51:23<10:32,  8.54it/s]

 82%|████████▏ | 24799/30196 [51:23<10:25,  8.63it/s]

 82%|████████▏ | 24801/30196 [51:23<09:52,  9.10it/s]

 82%|████████▏ | 24803/30196 [51:24<10:22,  8.66it/s]

 82%|████████▏ | 24806/30196 [51:24<08:43, 10.29it/s]

 82%|████████▏ | 24808/30196 [51:24<08:49, 10.17it/s]

 82%|████████▏ | 24810/30196 [51:24<09:17,  9.67it/s]

 82%|████████▏ | 24811/30196 [51:25<10:55,  8.21it/s]

 82%|████████▏ | 24812/30196 [51:25<11:08,  8.05it/s]

 82%|████████▏ | 24814/30196 [51:25<10:39,  8.42it/s]

 82%|████████▏ | 24815/30196 [51:25<10:52,  8.24it/s]

 82%|████████▏ | 24816/30196 [51:25<10:33,  8.50it/s]

 82%|████████▏ | 24818/30196 [51:25<11:09,  8.03it/s]

 82%|████████▏ | 24819/30196 [51:26<12:16,  7.31it/s]

 82%|████████▏ | 24820/30196 [51:26<12:07,  7.39it/s]

 82%|████████▏ | 24821/30196 [51:26<11:32,  7.76it/s]

 82%|████████▏ | 24822/30196 [51:26<12:24,  7.22it/s]

 82%|████████▏ | 24823/30196 [51:26<11:43,  7.64it/s]

 82%|████████▏ | 24825/30196 [51:26<09:43,  9.20it/s]

 82%|████████▏ | 24827/30196 [51:26<10:02,  8.91it/s]

 82%|████████▏ | 24828/30196 [51:27<10:43,  8.34it/s]

 82%|████████▏ | 24829/30196 [51:27<10:55,  8.19it/s]

 82%|████████▏ | 24830/30196 [51:27<10:32,  8.48it/s]

 82%|████████▏ | 24831/30196 [51:27<11:13,  7.97it/s]

 82%|████████▏ | 24833/30196 [51:27<09:26,  9.47it/s]

 82%|████████▏ | 24835/30196 [51:27<09:02,  9.88it/s]

 82%|████████▏ | 24837/30196 [51:28<09:20,  9.57it/s]

 82%|████████▏ | 24840/30196 [51:28<07:12, 12.38it/s]

 82%|████████▏ | 24842/30196 [51:28<08:04, 11.05it/s]

 82%|████████▏ | 24844/30196 [51:28<08:59,  9.92it/s]

 82%|████████▏ | 24846/30196 [51:28<09:32,  9.34it/s]

 82%|████████▏ | 24848/30196 [51:29<09:50,  9.06it/s]

 82%|████████▏ | 24849/30196 [51:29<10:50,  8.22it/s]

 82%|████████▏ | 24850/30196 [51:29<11:16,  7.90it/s]

 82%|████████▏ | 24852/30196 [51:29<09:02,  9.84it/s]

 82%|████████▏ | 24854/30196 [51:29<09:57,  8.95it/s]

 82%|████████▏ | 24855/30196 [51:30<10:56,  8.13it/s]

 82%|████████▏ | 24857/30196 [51:30<10:32,  8.44it/s]

 82%|████████▏ | 24858/30196 [51:30<11:02,  8.05it/s]

 82%|████████▏ | 24860/30196 [51:30<10:26,  8.52it/s]

 82%|████████▏ | 24862/30196 [51:30<08:38, 10.29it/s]

 82%|████████▏ | 24864/30196 [51:30<07:34, 11.73it/s]

 82%|████████▏ | 24866/30196 [51:31<08:47, 10.10it/s]

 82%|████████▏ | 24868/30196 [51:31<08:29, 10.46it/s]

 82%|████████▏ | 24870/30196 [51:31<09:39,  9.19it/s]

 82%|████████▏ | 24872/30196 [51:31<09:58,  8.89it/s]

 82%|████████▏ | 24874/30196 [51:32<10:06,  8.78it/s]

 82%|████████▏ | 24875/30196 [51:32<10:23,  8.53it/s]

 82%|████████▏ | 24876/30196 [51:32<10:09,  8.73it/s]

 82%|████████▏ | 24877/30196 [51:32<12:27,  7.12it/s]

 82%|████████▏ | 24878/30196 [51:32<14:20,  6.18it/s]

 82%|████████▏ | 24880/30196 [51:32<11:43,  7.56it/s]

 82%|████████▏ | 24881/30196 [51:33<12:32,  7.07it/s]

 82%|████████▏ | 24882/30196 [51:33<14:19,  6.18it/s]

 82%|████████▏ | 24883/30196 [51:33<14:24,  6.15it/s]

 82%|████████▏ | 24884/30196 [51:33<13:09,  6.73it/s]

 82%|████████▏ | 24885/30196 [51:33<12:11,  7.26it/s]

 82%|████████▏ | 24887/30196 [51:33<09:10,  9.65it/s]

 82%|████████▏ | 24889/30196 [51:34<10:52,  8.13it/s]

 82%|████████▏ | 24892/30196 [51:34<08:11, 10.79it/s]

 82%|████████▏ | 24894/30196 [51:35<15:15,  5.79it/s]

 82%|████████▏ | 24896/30196 [51:35<15:25,  5.73it/s]

 82%|████████▏ | 24898/30196 [51:35<13:06,  6.74it/s]

 82%|████████▏ | 24900/30196 [51:35<11:48,  7.47it/s]

 82%|████████▏ | 24901/30196 [51:35<12:00,  7.35it/s]

 82%|████████▏ | 24903/30196 [51:36<11:18,  7.80it/s]

 82%|████████▏ | 24904/30196 [51:36<12:03,  7.31it/s]

 82%|████████▏ | 24905/30196 [51:36<14:20,  6.15it/s]

 82%|████████▏ | 24906/30196 [51:36<13:52,  6.35it/s]

 82%|████████▏ | 24908/30196 [51:36<10:11,  8.65it/s]

 82%|████████▏ | 24910/30196 [51:36<09:10,  9.59it/s]

 83%|████████▎ | 24912/30196 [51:37<12:20,  7.14it/s]

 83%|████████▎ | 24914/30196 [51:37<10:28,  8.41it/s]

 83%|████████▎ | 24916/30196 [51:37<10:48,  8.14it/s]

 83%|████████▎ | 24919/30196 [51:37<08:28, 10.37it/s]

 83%|████████▎ | 24921/30196 [51:38<08:31, 10.32it/s]

 83%|████████▎ | 24923/30196 [51:38<09:37,  9.12it/s]

 83%|████████▎ | 24925/30196 [51:38<09:37,  9.12it/s]

 83%|████████▎ | 24926/30196 [51:38<10:28,  8.38it/s]

 83%|████████▎ | 24927/30196 [51:38<10:40,  8.22it/s]

 83%|████████▎ | 24929/30196 [51:39<09:57,  8.82it/s]

 83%|████████▎ | 24931/30196 [51:39<10:25,  8.42it/s]

 83%|████████▎ | 24932/30196 [51:39<10:42,  8.19it/s]

 83%|████████▎ | 24933/30196 [51:39<10:52,  8.07it/s]

 83%|████████▎ | 24934/30196 [51:39<10:34,  8.29it/s]

 83%|████████▎ | 24936/30196 [51:39<08:36, 10.18it/s]

 83%|████████▎ | 24938/30196 [51:40<07:53, 11.11it/s]

 83%|████████▎ | 24940/30196 [51:40<09:44,  9.00it/s]

 83%|████████▎ | 24941/30196 [51:40<09:37,  9.11it/s]

 83%|████████▎ | 24943/30196 [51:40<09:47,  8.94it/s]

 83%|████████▎ | 24944/30196 [51:40<09:40,  9.04it/s]

 83%|████████▎ | 24946/30196 [51:41<09:48,  8.91it/s]

 83%|████████▎ | 24947/30196 [51:41<17:44,  4.93it/s]

 83%|████████▎ | 24948/30196 [51:41<17:49,  4.91it/s]

 83%|████████▎ | 24950/30196 [51:42<20:48,  4.20it/s]

 83%|████████▎ | 24951/30196 [51:42<18:14,  4.79it/s]

 83%|████████▎ | 24952/30196 [51:42<17:38,  4.96it/s]

 83%|████████▎ | 24953/30196 [51:42<16:03,  5.44it/s]

 83%|████████▎ | 24954/30196 [51:42<15:39,  5.58it/s]

 83%|████████▎ | 24955/30196 [51:43<18:39,  4.68it/s]

 83%|████████▎ | 24957/30196 [51:43<16:11,  5.39it/s]

 83%|████████▎ | 24958/30196 [51:43<15:02,  5.80it/s]

 83%|████████▎ | 24959/30196 [51:43<14:28,  6.03it/s]

 83%|████████▎ | 24960/30196 [51:44<24:41,  3.53it/s]

 83%|████████▎ | 24962/30196 [51:44<18:33,  4.70it/s]

 83%|████████▎ | 24963/30196 [51:44<16:51,  5.17it/s]

 83%|████████▎ | 24964/30196 [51:44<14:55,  5.84it/s]

 83%|████████▎ | 24966/30196 [51:45<11:09,  7.81it/s]

 83%|████████▎ | 24967/30196 [51:45<10:48,  8.07it/s]

 83%|████████▎ | 24969/30196 [51:45<08:36, 10.12it/s]

 83%|████████▎ | 24971/30196 [51:45<09:43,  8.95it/s]

 83%|████████▎ | 24973/30196 [51:45<08:42,  9.99it/s]

 83%|████████▎ | 24975/30196 [51:45<07:47, 11.17it/s]

 83%|████████▎ | 24977/30196 [51:46<08:31, 10.21it/s]

 83%|████████▎ | 24979/30196 [51:46<09:44,  8.92it/s]

 83%|████████▎ | 24981/30196 [51:46<10:09,  8.55it/s]

 83%|████████▎ | 24982/30196 [51:46<13:24,  6.48it/s]

 83%|████████▎ | 24983/30196 [51:47<16:10,  5.37it/s]

 83%|████████▎ | 24984/30196 [51:47<14:41,  5.91it/s]

 83%|████████▎ | 24985/30196 [51:47<14:05,  6.16it/s]

 83%|████████▎ | 24987/30196 [51:47<10:51,  8.00it/s]

 83%|████████▎ | 24988/30196 [51:47<12:10,  7.13it/s]

 83%|████████▎ | 24990/30196 [51:48<10:01,  8.66it/s]

 83%|████████▎ | 24991/30196 [51:48<11:43,  7.40it/s]

 83%|████████▎ | 24994/30196 [51:48<08:57,  9.68it/s]

 83%|████████▎ | 24995/30196 [51:48<09:32,  9.08it/s]

 83%|████████▎ | 24996/30196 [51:48<10:13,  8.47it/s]

 83%|████████▎ | 24997/30196 [51:48<13:18,  6.51it/s]

 83%|████████▎ | 24999/30196 [51:49<12:31,  6.91it/s]

 83%|████████▎ | 25000/30196 [51:49<12:20,  7.01it/s]

 83%|████████▎ | 25001/30196 [51:49<16:24,  5.28it/s]

 83%|████████▎ | 25002/30196 [51:49<15:19,  5.65it/s]

 83%|████████▎ | 25003/30196 [51:50<15:03,  5.75it/s]

 83%|████████▎ | 25004/30196 [51:50<14:49,  5.84it/s]

 83%|████████▎ | 25006/30196 [51:50<11:10,  7.74it/s]

 83%|████████▎ | 25007/30196 [51:50<13:55,  6.21it/s]

 83%|████████▎ | 25008/30196 [51:50<13:37,  6.34it/s]

 83%|████████▎ | 25009/30196 [51:50<13:14,  6.53it/s]

 83%|████████▎ | 25010/30196 [51:51<12:05,  7.15it/s]

 83%|████████▎ | 25011/30196 [51:51<11:59,  7.21it/s]

 83%|████████▎ | 25013/30196 [51:51<09:25,  9.17it/s]

 83%|████████▎ | 25014/30196 [51:51<09:26,  9.16it/s]

 83%|████████▎ | 25015/30196 [51:51<13:29,  6.40it/s]

 83%|████████▎ | 25016/30196 [51:51<14:56,  5.78it/s]

 83%|████████▎ | 25017/30196 [51:52<14:47,  5.84it/s]

 83%|████████▎ | 25019/30196 [51:52<11:21,  7.59it/s]

 83%|████████▎ | 25020/30196 [51:52<12:12,  7.06it/s]

 83%|████████▎ | 25021/30196 [51:52<13:45,  6.27it/s]

 83%|████████▎ | 25023/30196 [51:52<10:52,  7.92it/s]

 83%|████████▎ | 25024/30196 [51:52<11:11,  7.71it/s]

 83%|████████▎ | 25025/30196 [51:53<11:12,  7.69it/s]

 83%|████████▎ | 25026/30196 [51:53<12:02,  7.15it/s]

 83%|████████▎ | 25028/30196 [51:53<10:44,  8.02it/s]

 83%|████████▎ | 25029/30196 [51:53<10:49,  7.96it/s]

 83%|████████▎ | 25030/30196 [51:53<11:00,  7.82it/s]

 83%|████████▎ | 25032/30196 [51:53<10:19,  8.34it/s]

 83%|████████▎ | 25033/30196 [51:54<11:31,  7.47it/s]

 83%|████████▎ | 25035/30196 [51:54<09:11,  9.36it/s]

 83%|████████▎ | 25037/30196 [51:54<08:27, 10.17it/s]

 83%|████████▎ | 25039/30196 [51:55<16:37,  5.17it/s]

 83%|████████▎ | 25040/30196 [51:55<16:22,  5.25it/s]

 83%|████████▎ | 25041/30196 [51:55<14:52,  5.78it/s]

 83%|████████▎ | 25042/30196 [51:55<14:42,  5.84it/s]

 83%|████████▎ | 25043/30196 [51:55<14:03,  6.11it/s]

 83%|████████▎ | 25044/30196 [51:55<14:09,  6.06it/s]

 83%|████████▎ | 25046/30196 [51:56<10:01,  8.56it/s]

 83%|████████▎ | 25048/30196 [51:56<12:26,  6.90it/s]

 83%|████████▎ | 25049/30196 [51:56<13:04,  6.56it/s]

 83%|████████▎ | 25050/30196 [51:56<12:07,  7.07it/s]

 83%|████████▎ | 25052/30196 [51:56<11:04,  7.74it/s]

 83%|████████▎ | 25054/30196 [51:57<11:08,  7.69it/s]

 83%|████████▎ | 25055/30196 [51:57<11:56,  7.18it/s]

 83%|████████▎ | 25056/30196 [51:57<11:15,  7.61it/s]

 83%|████████▎ | 25058/30196 [51:57<09:00,  9.50it/s]

 83%|████████▎ | 25060/30196 [51:57<09:55,  8.62it/s]

 83%|████████▎ | 25062/30196 [51:58<09:35,  8.93it/s]

 83%|████████▎ | 25063/30196 [51:58<09:32,  8.96it/s]

 83%|████████▎ | 25064/30196 [51:58<10:45,  7.95it/s]

 83%|████████▎ | 25066/30196 [51:58<10:10,  8.41it/s]

 83%|████████▎ | 25068/30196 [51:58<08:33,  9.98it/s]

 83%|████████▎ | 25070/30196 [51:58<08:31, 10.03it/s]

 83%|████████▎ | 25072/30196 [51:59<07:37, 11.20it/s]

 83%|████████▎ | 25074/30196 [51:59<09:02,  9.44it/s]

 83%|████████▎ | 25076/30196 [51:59<11:57,  7.14it/s]

 83%|████████▎ | 25078/30196 [51:59<10:42,  7.96it/s]

 83%|████████▎ | 25080/30196 [52:00<09:35,  8.89it/s]

 83%|████████▎ | 25082/30196 [52:00<10:57,  7.77it/s]

 83%|████████▎ | 25084/30196 [52:00<12:08,  7.01it/s]

 83%|████████▎ | 25085/30196 [52:00<12:32,  6.79it/s]

 83%|████████▎ | 25087/30196 [52:01<10:21,  8.22it/s]

 83%|████████▎ | 25088/30196 [52:01<10:04,  8.45it/s]

 83%|████████▎ | 25090/30196 [52:01<09:09,  9.29it/s]

 83%|████████▎ | 25091/30196 [52:01<09:47,  8.69it/s]

 83%|████████▎ | 25093/30196 [52:01<09:44,  8.73it/s]

 83%|████████▎ | 25094/30196 [52:01<09:50,  8.64it/s]

 83%|████████▎ | 25096/30196 [52:02<09:16,  9.17it/s]

 83%|████████▎ | 25098/30196 [52:02<09:24,  9.03it/s]

 83%|████████▎ | 25099/30196 [52:02<10:24,  8.16it/s]

 83%|████████▎ | 25101/30196 [52:02<10:06,  8.40it/s]

 83%|████████▎ | 25102/30196 [52:02<10:56,  7.76it/s]

 83%|████████▎ | 25104/30196 [52:02<08:54,  9.52it/s]

 83%|████████▎ | 25106/30196 [52:03<08:41,  9.75it/s]

 83%|████████▎ | 25108/30196 [52:03<09:28,  8.95it/s]

 83%|████████▎ | 25110/30196 [52:03<09:00,  9.40it/s]

 83%|████████▎ | 25112/30196 [52:03<09:13,  9.19it/s]

 83%|████████▎ | 25113/30196 [52:04<10:45,  7.88it/s]

 83%|████████▎ | 25115/30196 [52:04<09:27,  8.95it/s]

 83%|████████▎ | 25116/30196 [52:04<09:20,  9.07it/s]

 83%|████████▎ | 25117/30196 [52:04<10:00,  8.46it/s]

 83%|████████▎ | 25118/30196 [52:04<10:20,  8.18it/s]

 83%|████████▎ | 25120/30196 [52:04<08:28,  9.98it/s]

 83%|████████▎ | 25122/30196 [52:05<11:40,  7.24it/s]

 83%|████████▎ | 25124/30196 [52:05<10:39,  7.93it/s]

 83%|████████▎ | 25125/30196 [52:05<12:45,  6.62it/s]

 83%|████████▎ | 25126/30196 [52:06<18:58,  4.45it/s]

 83%|████████▎ | 25127/30196 [52:06<16:34,  5.10it/s]

 83%|████████▎ | 25128/30196 [52:06<16:11,  5.22it/s]

 83%|████████▎ | 25130/30196 [52:06<12:03,  7.00it/s]

 83%|████████▎ | 25131/30196 [52:06<11:54,  7.09it/s]

 83%|████████▎ | 25132/30196 [52:06<11:07,  7.58it/s]

 83%|████████▎ | 25134/30196 [52:07<10:33,  7.98it/s]

 83%|████████▎ | 25135/30196 [52:07<10:10,  8.29it/s]

 83%|████████▎ | 25136/30196 [52:07<09:48,  8.60it/s]

 83%|████████▎ | 25137/30196 [52:07<10:13,  8.25it/s]

 83%|████████▎ | 25138/30196 [52:07<12:28,  6.76it/s]

 83%|████████▎ | 25139/30196 [52:07<17:39,  4.78it/s]

 83%|████████▎ | 25141/30196 [52:08<14:34,  5.78it/s]

 83%|████████▎ | 25142/30196 [52:08<13:46,  6.11it/s]

 83%|████████▎ | 25143/30196 [52:08<12:37,  6.67it/s]

 83%|████████▎ | 25144/30196 [52:08<13:04,  6.44it/s]

 83%|████████▎ | 25145/30196 [52:08<12:00,  7.01it/s]

 83%|████████▎ | 25147/30196 [52:08<10:03,  8.37it/s]

 83%|████████▎ | 25148/30196 [52:09<14:07,  5.96it/s]

 83%|████████▎ | 25149/30196 [52:09<14:23,  5.84it/s]

 83%|████████▎ | 25150/30196 [52:09<19:05,  4.40it/s]

 83%|████████▎ | 25151/30196 [52:09<17:14,  4.87it/s]

 83%|████████▎ | 25153/30196 [52:10<19:48,  4.24it/s]

 83%|████████▎ | 25154/30196 [52:10<17:54,  4.69it/s]

 83%|████████▎ | 25155/30196 [52:10<15:35,  5.39it/s]

 83%|████████▎ | 25157/30196 [52:10<12:13,  6.87it/s]

 83%|████████▎ | 25158/30196 [52:11<11:32,  7.28it/s]

 83%|████████▎ | 25159/30196 [52:11<11:37,  7.22it/s]

 83%|████████▎ | 25161/30196 [52:11<08:39,  9.68it/s]

 83%|████████▎ | 25163/30196 [52:11<12:21,  6.79it/s]

 83%|████████▎ | 25164/30196 [52:11<12:54,  6.50it/s]

 83%|████████▎ | 25166/30196 [52:12<11:33,  7.26it/s]

 83%|████████▎ | 25167/30196 [52:12<12:50,  6.52it/s]

 83%|████████▎ | 25168/30196 [52:12<13:08,  6.37it/s]

 83%|████████▎ | 25169/30196 [52:12<12:48,  6.54it/s]

 83%|████████▎ | 25170/30196 [52:12<11:51,  7.06it/s]

 83%|████████▎ | 25171/30196 [52:12<11:08,  7.51it/s]

 83%|████████▎ | 25172/30196 [52:12<10:37,  7.88it/s]

 83%|████████▎ | 25173/30196 [52:13<11:03,  7.57it/s]

 83%|████████▎ | 25174/30196 [52:13<11:01,  7.60it/s]

 83%|████████▎ | 25176/30196 [52:13<08:53,  9.40it/s]

 83%|████████▎ | 25177/30196 [52:13<08:52,  9.42it/s]

 83%|████████▎ | 25178/30196 [52:13<10:13,  8.18it/s]

 83%|████████▎ | 25179/30196 [52:13<10:22,  8.05it/s]

 83%|████████▎ | 25180/30196 [52:13<11:31,  7.25it/s]

 83%|████████▎ | 25181/30196 [52:14<12:21,  6.76it/s]

 83%|████████▎ | 25182/30196 [52:14<11:18,  7.39it/s]

 83%|████████▎ | 25183/30196 [52:14<11:16,  7.41it/s]

 83%|████████▎ | 25185/30196 [52:14<12:45,  6.55it/s]

 83%|████████▎ | 25186/30196 [52:14<11:52,  7.03it/s]

 83%|████████▎ | 25187/30196 [52:14<11:36,  7.19it/s]

 83%|████████▎ | 25188/30196 [52:15<11:37,  7.18it/s]

 83%|████████▎ | 25190/30196 [52:15<09:31,  8.77it/s]

 83%|████████▎ | 25192/30196 [52:15<07:33, 11.02it/s]

 83%|████████▎ | 25194/30196 [52:15<10:07,  8.24it/s]

 83%|████████▎ | 25196/30196 [52:16<15:49,  5.27it/s]

 83%|████████▎ | 25198/30196 [52:16<13:25,  6.20it/s]

 83%|████████▎ | 25200/30196 [52:16<10:41,  7.78it/s]

 83%|████████▎ | 25202/30196 [52:17<11:46,  7.07it/s]

 83%|████████▎ | 25204/30196 [52:17<09:26,  8.81it/s]

 83%|████████▎ | 25206/30196 [52:17<10:27,  7.95it/s]

 83%|████████▎ | 25208/30196 [52:17<08:48,  9.43it/s]

 83%|████████▎ | 25210/30196 [52:18<15:21,  5.41it/s]

 83%|████████▎ | 25212/30196 [52:18<13:03,  6.36it/s]

 83%|████████▎ | 25213/30196 [52:18<12:21,  6.72it/s]

 84%|████████▎ | 25214/30196 [52:18<12:42,  6.53it/s]

 84%|████████▎ | 25216/30196 [52:19<11:51,  7.00it/s]

 84%|████████▎ | 25218/30196 [52:19<10:00,  8.29it/s]

 84%|████████▎ | 25219/30196 [52:19<13:09,  6.31it/s]

 84%|████████▎ | 25220/30196 [52:19<14:51,  5.58it/s]

 84%|████████▎ | 25222/30196 [52:19<12:15,  6.76it/s]

 84%|████████▎ | 25223/30196 [52:20<11:29,  7.22it/s]

 84%|████████▎ | 25225/30196 [52:20<10:41,  7.74it/s]

 84%|████████▎ | 25227/30196 [52:20<09:20,  8.86it/s]

 84%|████████▎ | 25228/30196 [52:20<09:55,  8.34it/s]

 84%|████████▎ | 25229/30196 [52:20<09:44,  8.50it/s]

 84%|████████▎ | 25231/30196 [52:20<08:20,  9.93it/s]

 84%|████████▎ | 25233/30196 [52:21<09:08,  9.06it/s]

 84%|████████▎ | 25234/30196 [52:21<09:35,  8.62it/s]

 84%|████████▎ | 25235/30196 [52:21<12:18,  6.71it/s]

 84%|████████▎ | 25237/30196 [52:21<09:57,  8.31it/s]

 84%|████████▎ | 25238/30196 [52:21<09:45,  8.47it/s]

 84%|████████▎ | 25240/30196 [52:21<08:08, 10.14it/s]

 84%|████████▎ | 25242/30196 [52:22<09:21,  8.83it/s]

 84%|████████▎ | 25243/30196 [52:22<09:13,  8.95it/s]

 84%|████████▎ | 25245/30196 [52:22<08:37,  9.57it/s]

 84%|████████▎ | 25247/30196 [52:22<08:11, 10.07it/s]

 84%|████████▎ | 25249/30196 [52:22<09:43,  8.48it/s]

 84%|████████▎ | 25251/30196 [52:23<08:32,  9.66it/s]

 84%|████████▎ | 25253/30196 [52:23<07:57, 10.36it/s]

 84%|████████▎ | 25255/30196 [52:23<07:46, 10.58it/s]

 84%|████████▎ | 25257/30196 [52:23<08:22,  9.83it/s]

 84%|████████▎ | 25259/30196 [52:24<10:08,  8.12it/s]

 84%|████████▎ | 25261/30196 [52:24<09:03,  9.08it/s]

 84%|████████▎ | 25263/30196 [52:24<08:33,  9.61it/s]

 84%|████████▎ | 25265/30196 [52:24<09:05,  9.04it/s]

 84%|████████▎ | 25266/30196 [52:24<09:04,  9.06it/s]

 84%|████████▎ | 25268/30196 [52:24<08:56,  9.19it/s]

 84%|████████▎ | 25269/30196 [52:25<08:50,  9.28it/s]

 84%|████████▎ | 25270/30196 [52:25<10:00,  8.21it/s]

 84%|████████▎ | 25271/30196 [52:25<10:54,  7.52it/s]

 84%|████████▎ | 25272/30196 [52:25<11:12,  7.33it/s]

 84%|████████▎ | 25274/30196 [52:25<10:10,  8.07it/s]

 84%|████████▎ | 25275/30196 [52:25<10:28,  7.83it/s]

 84%|████████▎ | 25276/30196 [52:26<10:34,  7.76it/s]

 84%|████████▎ | 25277/30196 [52:26<10:40,  7.68it/s]

 84%|████████▎ | 25279/30196 [52:26<10:31,  7.79it/s]

 84%|████████▎ | 25280/30196 [52:26<10:36,  7.72it/s]

 84%|████████▎ | 25282/30196 [52:26<09:58,  8.22it/s]

 84%|████████▎ | 25283/30196 [52:26<10:06,  8.10it/s]

 84%|████████▎ | 25284/30196 [52:27<12:05,  6.77it/s]

 84%|████████▎ | 25286/30196 [52:27<09:54,  8.26it/s]

 84%|████████▎ | 25287/30196 [52:27<10:05,  8.11it/s]

 84%|████████▎ | 25289/30196 [52:27<08:14,  9.92it/s]

 84%|████████▍ | 25291/30196 [52:27<08:58,  9.11it/s]

 84%|████████▍ | 25293/30196 [52:28<09:12,  8.87it/s]

 84%|████████▍ | 25294/30196 [52:28<09:05,  8.99it/s]

 84%|████████▍ | 25295/30196 [52:28<09:35,  8.51it/s]

 84%|████████▍ | 25297/30196 [52:28<09:38,  8.46it/s]

 84%|████████▍ | 25299/30196 [52:28<09:53,  8.25it/s]

 84%|████████▍ | 25301/30196 [52:28<08:02, 10.15it/s]

 84%|████████▍ | 25303/30196 [52:29<08:57,  9.10it/s]

 84%|████████▍ | 25305/30196 [52:29<10:24,  7.83it/s]

 84%|████████▍ | 25307/30196 [52:29<09:38,  8.45it/s]

 84%|████████▍ | 25308/30196 [52:29<09:58,  8.17it/s]

 84%|████████▍ | 25310/30196 [52:29<08:22,  9.73it/s]

 84%|████████▍ | 25312/30196 [52:30<12:03,  6.75it/s]

 84%|████████▍ | 25313/30196 [52:30<12:22,  6.57it/s]

 84%|████████▍ | 25314/30196 [52:30<14:27,  5.62it/s]

 84%|████████▍ | 25316/30196 [52:30<10:40,  7.62it/s]

 84%|████████▍ | 25318/30196 [52:31<10:13,  7.95it/s]

 84%|████████▍ | 25319/30196 [52:31<11:40,  6.97it/s]

 84%|████████▍ | 25320/30196 [52:31<13:12,  6.15it/s]

 84%|████████▍ | 25321/30196 [52:31<13:17,  6.11it/s]

 84%|████████▍ | 25323/30196 [52:31<11:04,  7.33it/s]

 84%|████████▍ | 25324/30196 [52:32<11:44,  6.92it/s]

 84%|████████▍ | 25325/30196 [52:32<13:22,  6.07it/s]

 84%|████████▍ | 25326/30196 [52:32<12:53,  6.30it/s]

 84%|████████▍ | 25328/30196 [52:32<10:00,  8.11it/s]

 84%|████████▍ | 25329/30196 [52:32<09:39,  8.40it/s]

 84%|████████▍ | 25330/30196 [52:33<12:21,  6.57it/s]

 84%|████████▍ | 25331/30196 [52:33<11:57,  6.78it/s]

 84%|████████▍ | 25332/30196 [52:33<12:22,  6.55it/s]

 84%|████████▍ | 25334/30196 [52:33<10:25,  7.77it/s]

 84%|████████▍ | 25335/30196 [52:33<10:28,  7.74it/s]

 84%|████████▍ | 25336/30196 [52:33<11:30,  7.04it/s]

 84%|████████▍ | 25337/30196 [52:33<10:49,  7.48it/s]

 84%|████████▍ | 25338/30196 [52:34<11:49,  6.85it/s]

 84%|████████▍ | 25339/30196 [52:34<11:33,  7.00it/s]

 84%|████████▍ | 25340/30196 [52:34<12:22,  6.54it/s]

 84%|████████▍ | 25341/30196 [52:34<11:21,  7.12it/s]

 84%|████████▍ | 25342/30196 [52:34<11:30,  7.03it/s]

 84%|████████▍ | 25343/30196 [52:34<11:26,  7.07it/s]

 84%|████████▍ | 25344/30196 [52:35<13:00,  6.21it/s]

 84%|████████▍ | 25345/30196 [52:35<13:13,  6.11it/s]

 84%|████████▍ | 25346/30196 [52:35<11:49,  6.84it/s]

 84%|████████▍ | 25347/30196 [52:36<28:20,  2.85it/s]

 84%|████████▍ | 25349/30196 [52:36<20:13,  4.00it/s]

 84%|████████▍ | 25351/30196 [52:36<14:03,  5.74it/s]

 84%|████████▍ | 25353/30196 [52:36<11:14,  7.18it/s]

 84%|████████▍ | 25355/30196 [52:36<09:53,  8.16it/s]

 84%|████████▍ | 25357/30196 [52:37<08:53,  9.06it/s]

 84%|████████▍ | 25359/30196 [52:37<09:24,  8.57it/s]

 84%|████████▍ | 25360/30196 [52:37<10:08,  7.95it/s]

 84%|████████▍ | 25361/30196 [52:37<09:52,  8.16it/s]

 84%|████████▍ | 25362/30196 [52:37<10:51,  7.42it/s]

 84%|████████▍ | 25364/30196 [52:38<10:40,  7.54it/s]

 84%|████████▍ | 25366/30196 [52:38<08:44,  9.21it/s]

 84%|████████▍ | 25368/30196 [52:38<13:38,  5.90it/s]

 84%|████████▍ | 25369/30196 [52:38<13:11,  6.10it/s]

 84%|████████▍ | 25370/30196 [52:39<12:52,  6.24it/s]

 84%|████████▍ | 25371/30196 [52:39<13:04,  6.15it/s]

 84%|████████▍ | 25372/30196 [52:39<12:37,  6.37it/s]

 84%|████████▍ | 25373/30196 [52:40<25:26,  3.16it/s]

 84%|████████▍ | 25374/30196 [52:40<21:33,  3.73it/s]

 84%|████████▍ | 25375/30196 [52:40<18:32,  4.33it/s]

 84%|████████▍ | 25376/30196 [52:41<28:38,  2.81it/s]

 84%|████████▍ | 25377/30196 [52:41<23:21,  3.44it/s]

 84%|████████▍ | 25378/30196 [52:41<19:53,  4.04it/s]

 84%|████████▍ | 25380/30196 [52:41<14:08,  5.68it/s]

 84%|████████▍ | 25382/30196 [52:41<11:36,  6.92it/s]

 84%|████████▍ | 25383/30196 [52:41<11:19,  7.08it/s]

 84%|████████▍ | 25384/30196 [52:41<10:38,  7.54it/s]

 84%|████████▍ | 25385/30196 [52:42<10:10,  7.88it/s]

 84%|████████▍ | 25388/30196 [52:42<09:22,  8.55it/s]

 84%|████████▍ | 25390/30196 [52:42<09:04,  8.82it/s]

 84%|████████▍ | 25391/30196 [52:42<09:29,  8.43it/s]

 84%|████████▍ | 25393/30196 [52:42<09:57,  8.04it/s]

 84%|████████▍ | 25394/30196 [52:43<11:59,  6.67it/s]

 84%|████████▍ | 25396/30196 [52:43<09:20,  8.57it/s]

 84%|████████▍ | 25397/30196 [52:43<11:13,  7.13it/s]

 84%|████████▍ | 25399/30196 [52:43<08:48,  9.08it/s]

 84%|████████▍ | 25401/30196 [52:43<07:20, 10.90it/s]

 84%|████████▍ | 25403/30196 [52:43<07:25, 10.76it/s]

 84%|████████▍ | 25405/30196 [52:44<08:26,  9.46it/s]

 84%|████████▍ | 25407/30196 [52:44<08:06,  9.84it/s]

 84%|████████▍ | 25409/30196 [52:44<08:22,  9.53it/s]

 84%|████████▍ | 25411/30196 [52:44<08:21,  9.53it/s]

 84%|████████▍ | 25413/30196 [52:45<09:02,  8.82it/s]

 84%|████████▍ | 25415/30196 [52:45<08:25,  9.46it/s]

 84%|████████▍ | 25417/30196 [52:45<07:58,  9.98it/s]

 84%|████████▍ | 25419/30196 [52:45<07:32, 10.55it/s]

 84%|████████▍ | 25421/30196 [52:45<08:06,  9.81it/s]

 84%|████████▍ | 25423/30196 [52:46<09:17,  8.56it/s]

 84%|████████▍ | 25425/30196 [52:46<08:27,  9.40it/s]

 84%|████████▍ | 25427/30196 [52:46<08:25,  9.43it/s]

 84%|████████▍ | 25429/30196 [52:46<07:08, 11.12it/s]

 84%|████████▍ | 25431/30196 [52:46<07:21, 10.78it/s]

 84%|████████▍ | 25433/30196 [52:47<08:15,  9.60it/s]

 84%|████████▍ | 25435/30196 [52:47<09:02,  8.77it/s]

 84%|████████▍ | 25437/30196 [52:47<09:07,  8.69it/s]

 84%|████████▍ | 25438/30196 [52:47<09:34,  8.28it/s]

 84%|████████▍ | 25439/30196 [52:47<09:19,  8.50it/s]

 84%|████████▍ | 25441/30196 [52:48<09:13,  8.59it/s]

 84%|████████▍ | 25443/30196 [52:48<08:04,  9.82it/s]

 84%|████████▍ | 25445/30196 [52:48<07:34, 10.46it/s]

 84%|████████▍ | 25447/30196 [52:48<08:15,  9.58it/s]

 84%|████████▍ | 25449/30196 [52:48<09:28,  8.35it/s]

 84%|████████▍ | 25451/30196 [52:49<09:04,  8.72it/s]

 84%|████████▍ | 25452/30196 [52:49<09:47,  8.07it/s]

 84%|████████▍ | 25454/30196 [52:49<08:17,  9.54it/s]

 84%|████████▍ | 25456/30196 [52:49<08:33,  9.23it/s]

 84%|████████▍ | 25457/30196 [52:49<08:57,  8.82it/s]

 84%|████████▍ | 25458/30196 [52:50<09:54,  7.98it/s]

 84%|████████▍ | 25460/30196 [52:50<10:08,  7.78it/s]

 84%|████████▍ | 25462/30196 [52:50<09:17,  8.50it/s]

 84%|████████▍ | 25464/30196 [52:50<07:47, 10.12it/s]

 84%|████████▍ | 25466/30196 [52:50<06:35, 11.96it/s]

 84%|████████▍ | 25468/30196 [52:51<07:52, 10.00it/s]

 84%|████████▍ | 25470/30196 [52:51<06:54, 11.39it/s]

 84%|████████▍ | 25472/30196 [52:51<07:28, 10.52it/s]

 84%|████████▍ | 25474/30196 [52:52<19:47,  3.98it/s]

 84%|████████▍ | 25475/30196 [52:52<17:42,  4.44it/s]

 84%|████████▍ | 25477/30196 [52:52<13:55,  5.65it/s]

 84%|████████▍ | 25479/30196 [52:53<12:10,  6.46it/s]

 84%|████████▍ | 25480/30196 [52:53<13:00,  6.04it/s]

 84%|████████▍ | 25482/30196 [52:53<10:19,  7.60it/s]

 84%|████████▍ | 25484/30196 [52:53<12:51,  6.10it/s]

 84%|████████▍ | 25485/30196 [52:53<12:21,  6.35it/s]

 84%|████████▍ | 25486/30196 [52:54<11:58,  6.55it/s]

 84%|████████▍ | 25488/30196 [52:54<10:21,  7.58it/s]

 84%|████████▍ | 25489/30196 [52:54<11:51,  6.62it/s]

 84%|████████▍ | 25490/30196 [52:54<11:05,  7.07it/s]

 84%|████████▍ | 25492/30196 [52:54<10:33,  7.42it/s]

 84%|████████▍ | 25493/30196 [52:55<11:09,  7.03it/s]

 84%|████████▍ | 25495/30196 [52:55<08:37,  9.08it/s]

 84%|████████▍ | 25497/30196 [52:55<10:08,  7.72it/s]

 84%|████████▍ | 25499/30196 [52:55<11:11,  6.99it/s]

 84%|████████▍ | 25501/30196 [52:56<10:08,  7.71it/s]

 84%|████████▍ | 25503/30196 [52:56<08:10,  9.57it/s]

 84%|████████▍ | 25505/30196 [52:56<07:53,  9.91it/s]

 84%|████████▍ | 25507/30196 [52:56<08:21,  9.36it/s]

 84%|████████▍ | 25509/30196 [52:56<10:27,  7.47it/s]

 84%|████████▍ | 25510/30196 [52:57<10:06,  7.72it/s]

 84%|████████▍ | 25512/30196 [52:57<08:51,  8.81it/s]

 84%|████████▍ | 25513/30196 [52:57<09:22,  8.32it/s]

 84%|████████▍ | 25514/30196 [52:57<11:36,  6.72it/s]

 84%|████████▍ | 25515/30196 [52:57<11:15,  6.93it/s]

 85%|████████▍ | 25516/30196 [52:57<11:57,  6.52it/s]

 85%|████████▍ | 25518/30196 [52:58<11:02,  7.06it/s]

 85%|████████▍ | 25519/30196 [52:58<10:23,  7.50it/s]

 85%|████████▍ | 25521/30196 [52:58<08:49,  8.83it/s]

 85%|████████▍ | 25523/30196 [52:58<12:31,  6.22it/s]

 85%|████████▍ | 25525/30196 [52:59<10:09,  7.67it/s]

 85%|████████▍ | 25526/30196 [52:59<10:24,  7.48it/s]

 85%|████████▍ | 25527/30196 [52:59<10:23,  7.49it/s]

 85%|████████▍ | 25529/30196 [52:59<10:14,  7.59it/s]

 85%|████████▍ | 25531/30196 [52:59<09:51,  7.89it/s]

 85%|████████▍ | 25533/30196 [53:00<09:35,  8.10it/s]

 85%|████████▍ | 25534/30196 [53:00<09:51,  7.89it/s]

 85%|████████▍ | 25536/30196 [53:00<09:59,  7.77it/s]

 85%|████████▍ | 25537/30196 [53:00<09:42,  8.00it/s]

 85%|████████▍ | 25538/30196 [53:00<09:51,  7.87it/s]

 85%|████████▍ | 25540/30196 [53:00<09:23,  8.26it/s]

 85%|████████▍ | 25541/30196 [53:01<09:33,  8.12it/s]

 85%|████████▍ | 25543/30196 [53:01<09:05,  8.53it/s]

 85%|████████▍ | 25544/30196 [53:01<10:06,  7.67it/s]

 85%|████████▍ | 25546/30196 [53:01<08:08,  9.52it/s]

 85%|████████▍ | 25548/30196 [53:01<07:59,  9.70it/s]

 85%|████████▍ | 25550/30196 [53:02<11:42,  6.62it/s]

 85%|████████▍ | 25551/30196 [53:02<11:23,  6.80it/s]

 85%|████████▍ | 25552/30196 [53:02<10:41,  7.24it/s]

 85%|████████▍ | 25553/30196 [53:02<11:19,  6.83it/s]

 85%|████████▍ | 25555/30196 [53:03<10:50,  7.13it/s]

 85%|████████▍ | 25557/30196 [53:03<10:31,  7.35it/s]

 85%|████████▍ | 25558/30196 [53:03<17:51,  4.33it/s]

 85%|████████▍ | 25559/30196 [53:04<17:25,  4.43it/s]

 85%|████████▍ | 25560/30196 [53:04<15:13,  5.07it/s]

 85%|████████▍ | 25562/30196 [53:04<15:44,  4.90it/s]

 85%|████████▍ | 25563/30196 [53:04<14:02,  5.50it/s]

 85%|████████▍ | 25564/30196 [53:04<13:09,  5.87it/s]

 85%|████████▍ | 25565/30196 [53:04<11:56,  6.47it/s]

 85%|████████▍ | 25566/30196 [53:05<22:05,  3.49it/s]

 85%|████████▍ | 25568/30196 [53:05<15:42,  4.91it/s]

 85%|████████▍ | 25569/30196 [53:05<14:41,  5.25it/s]

 85%|████████▍ | 25570/30196 [53:06<13:07,  5.87it/s]

 85%|████████▍ | 25571/30196 [53:06<12:50,  6.00it/s]

 85%|████████▍ | 25573/30196 [53:06<10:55,  7.06it/s]

 85%|████████▍ | 25575/30196 [53:06<10:33,  7.29it/s]

 85%|████████▍ | 25576/30196 [53:06<11:02,  6.97it/s]

 85%|████████▍ | 25577/30196 [53:07<11:35,  6.64it/s]

 85%|████████▍ | 25579/30196 [53:07<09:13,  8.34it/s]

 85%|████████▍ | 25581/30196 [53:07<09:34,  8.03it/s]

 85%|████████▍ | 25582/30196 [53:07<10:20,  7.44it/s]

 85%|████████▍ | 25584/30196 [53:07<10:42,  7.18it/s]

 85%|████████▍ | 25585/30196 [53:08<10:14,  7.50it/s]

 85%|████████▍ | 25586/30196 [53:08<10:11,  7.54it/s]

 85%|████████▍ | 25588/30196 [53:08<08:34,  8.96it/s]

 85%|████████▍ | 25590/30196 [53:08<08:24,  9.12it/s]

 85%|████████▍ | 25591/30196 [53:08<09:54,  7.75it/s]

 85%|████████▍ | 25592/30196 [53:08<10:36,  7.23it/s]

 85%|████████▍ | 25593/30196 [53:09<11:58,  6.40it/s]

 85%|████████▍ | 25595/30196 [53:09<10:54,  7.03it/s]

 85%|████████▍ | 25596/30196 [53:09<11:25,  6.71it/s]

 85%|████████▍ | 25598/30196 [53:09<09:12,  8.32it/s]

 85%|████████▍ | 25599/30196 [53:09<11:04,  6.92it/s]

 85%|████████▍ | 25600/30196 [53:10<10:59,  6.97it/s]

 85%|████████▍ | 25601/30196 [53:10<10:19,  7.42it/s]

 85%|████████▍ | 25603/30196 [53:10<08:59,  8.52it/s]

 85%|████████▍ | 25604/30196 [53:10<09:58,  7.67it/s]

 85%|████████▍ | 25605/30196 [53:10<10:03,  7.60it/s]

 85%|████████▍ | 25607/30196 [53:10<08:56,  8.56it/s]

 85%|████████▍ | 25608/30196 [53:10<08:59,  8.50it/s]

 85%|████████▍ | 25610/30196 [53:11<08:41,  8.79it/s]

 85%|████████▍ | 25611/30196 [53:11<11:02,  6.92it/s]

 85%|████████▍ | 25612/30196 [53:11<10:18,  7.41it/s]

 85%|████████▍ | 25613/30196 [53:11<11:47,  6.48it/s]

 85%|████████▍ | 25615/30196 [53:12<11:19,  6.74it/s]

 85%|████████▍ | 25617/30196 [53:12<11:01,  6.92it/s]

 85%|████████▍ | 25618/30196 [53:12<11:22,  6.71it/s]

 85%|████████▍ | 25620/30196 [53:12<10:17,  7.41it/s]

 85%|████████▍ | 25621/30196 [53:12<09:53,  7.70it/s]

 85%|████████▍ | 25622/30196 [53:12<09:58,  7.64it/s]

 85%|████████▍ | 25624/30196 [53:13<08:41,  8.77it/s]

 85%|████████▍ | 25625/30196 [53:13<10:16,  7.42it/s]

 85%|████████▍ | 25626/30196 [53:13<10:21,  7.35it/s]

 85%|████████▍ | 25627/30196 [53:13<10:25,  7.31it/s]

 85%|████████▍ | 25628/30196 [53:13<10:38,  7.16it/s]

 85%|████████▍ | 25629/30196 [53:13<12:02,  6.32it/s]

 85%|████████▍ | 25630/30196 [53:14<10:57,  6.94it/s]

 85%|████████▍ | 25632/30196 [53:14<09:16,  8.20it/s]

 85%|████████▍ | 25634/30196 [53:14<07:47,  9.76it/s]

 85%|████████▍ | 25635/30196 [53:14<08:19,  9.13it/s]

 85%|████████▍ | 25636/30196 [53:14<08:43,  8.70it/s]

 85%|████████▍ | 25637/30196 [53:14<09:02,  8.41it/s]

 85%|████████▍ | 25638/30196 [53:14<08:51,  8.58it/s]

 85%|████████▍ | 25640/30196 [53:15<06:59, 10.86it/s]

 85%|████████▍ | 25642/30196 [53:15<06:23, 11.87it/s]

 85%|████████▍ | 25644/30196 [53:15<06:59, 10.86it/s]

 85%|████████▍ | 25646/30196 [53:15<07:31, 10.07it/s]

 85%|████████▍ | 25648/30196 [53:15<08:11,  9.24it/s]

 85%|████████▍ | 25650/30196 [53:16<07:22, 10.27it/s]

 85%|████████▍ | 25652/30196 [53:16<10:27,  7.24it/s]

 85%|████████▍ | 25653/30196 [53:16<11:29,  6.59it/s]

 85%|████████▍ | 25654/30196 [53:16<13:49,  5.47it/s]

 85%|████████▍ | 25656/30196 [53:17<10:31,  7.19it/s]

 85%|████████▍ | 25657/30196 [53:17<10:33,  7.16it/s]

 85%|████████▍ | 25659/30196 [53:17<08:12,  9.22it/s]

 85%|████████▍ | 25661/30196 [53:17<09:12,  8.20it/s]

 85%|████████▍ | 25662/30196 [53:17<08:57,  8.44it/s]

 85%|████████▍ | 25665/30196 [53:17<06:33, 11.50it/s]

 85%|████████▌ | 25667/30196 [53:18<07:50,  9.62it/s]

 85%|████████▌ | 25669/30196 [53:18<09:15,  8.14it/s]

 85%|████████▌ | 25670/30196 [53:18<09:22,  8.05it/s]

 85%|████████▌ | 25671/30196 [53:18<09:27,  7.97it/s]

 85%|████████▌ | 25673/30196 [53:18<07:59,  9.44it/s]

 85%|████████▌ | 25675/30196 [53:19<06:51, 10.99it/s]

 85%|████████▌ | 25677/30196 [53:19<07:21, 10.24it/s]

 85%|████████▌ | 25679/30196 [53:19<08:19,  9.05it/s]

 85%|████████▌ | 25680/30196 [53:19<08:18,  9.05it/s]

 85%|████████▌ | 25681/30196 [53:19<09:13,  8.15it/s]

 85%|████████▌ | 25683/30196 [53:20<08:49,  8.53it/s]

 85%|████████▌ | 25684/30196 [53:20<09:46,  7.70it/s]

 85%|████████▌ | 25686/30196 [53:20<08:24,  8.94it/s]

 85%|████████▌ | 25687/30196 [53:20<09:23,  8.00it/s]

 85%|████████▌ | 25688/30196 [53:20<09:34,  7.85it/s]

 85%|████████▌ | 25689/30196 [53:20<09:43,  7.73it/s]

 85%|████████▌ | 25690/30196 [53:20<09:57,  7.54it/s]

 85%|████████▌ | 25691/30196 [53:21<09:22,  8.00it/s]

 85%|████████▌ | 25692/30196 [53:21<09:27,  7.93it/s]

 85%|████████▌ | 25693/30196 [53:21<09:06,  8.23it/s]

 85%|████████▌ | 25695/30196 [53:21<07:24, 10.12it/s]

 85%|████████▌ | 25697/30196 [53:21<08:34,  8.74it/s]

 85%|████████▌ | 25699/30196 [53:21<07:40,  9.76it/s]

 85%|████████▌ | 25701/30196 [53:22<07:23, 10.13it/s]

 85%|████████▌ | 25703/30196 [53:22<07:23, 10.13it/s]

 85%|████████▌ | 25705/30196 [53:22<08:20,  8.98it/s]

 85%|████████▌ | 25707/30196 [53:22<08:17,  9.02it/s]

 85%|████████▌ | 25708/30196 [53:22<09:36,  7.78it/s]

 85%|████████▌ | 25709/30196 [53:23<09:41,  7.71it/s]

 85%|████████▌ | 25710/30196 [53:23<09:21,  8.00it/s]

 85%|████████▌ | 25712/30196 [53:23<07:25, 10.07it/s]

 85%|████████▌ | 25714/30196 [53:23<06:58, 10.70it/s]

 85%|████████▌ | 25716/30196 [53:23<06:17, 11.88it/s]

 85%|████████▌ | 25718/30196 [53:23<05:34, 13.40it/s]

 85%|████████▌ | 25720/30196 [53:23<06:23, 11.66it/s]

 85%|████████▌ | 25722/30196 [53:24<06:36, 11.28it/s]

 85%|████████▌ | 25724/30196 [53:24<06:13, 11.96it/s]

 85%|████████▌ | 25726/30196 [53:24<06:19, 11.78it/s]

 85%|████████▌ | 25728/30196 [53:24<09:15,  8.05it/s]

 85%|████████▌ | 25730/30196 [53:25<08:05,  9.20it/s]

 85%|████████▌ | 25732/30196 [53:25<08:47,  8.46it/s]

 85%|████████▌ | 25733/30196 [53:25<12:54,  5.76it/s]

 85%|████████▌ | 25734/30196 [53:25<12:48,  5.81it/s]

 85%|████████▌ | 25735/30196 [53:26<12:42,  5.85it/s]

 85%|████████▌ | 25736/30196 [53:26<11:36,  6.40it/s]

 85%|████████▌ | 25738/30196 [53:26<09:46,  7.61it/s]

 85%|████████▌ | 25739/30196 [53:26<09:19,  7.96it/s]

 85%|████████▌ | 25741/30196 [53:26<08:01,  9.25it/s]

 85%|████████▌ | 25742/30196 [53:26<08:58,  8.27it/s]

 85%|████████▌ | 25745/30196 [53:27<06:58, 10.64it/s]

 85%|████████▌ | 25747/30196 [53:27<08:46,  8.44it/s]

 85%|████████▌ | 25748/30196 [53:27<08:35,  8.63it/s]

 85%|████████▌ | 25750/30196 [53:27<10:05,  7.35it/s]

 85%|████████▌ | 25752/30196 [53:28<09:13,  8.04it/s]

 85%|████████▌ | 25753/30196 [53:28<09:17,  7.96it/s]

 85%|████████▌ | 25755/30196 [53:28<09:55,  7.46it/s]

 85%|████████▌ | 25757/30196 [53:28<08:14,  8.98it/s]

 85%|████████▌ | 25759/30196 [53:28<08:46,  8.43it/s]

 85%|████████▌ | 25761/30196 [53:29<09:00,  8.20it/s]

 85%|████████▌ | 25763/30196 [53:29<08:31,  8.67it/s]

 85%|████████▌ | 25765/30196 [53:29<07:35,  9.73it/s]

 85%|████████▌ | 25767/30196 [53:29<06:45, 10.92it/s]

 85%|████████▌ | 25769/30196 [53:29<07:01, 10.51it/s]

 85%|████████▌ | 25771/30196 [53:29<06:17, 11.72it/s]

 85%|████████▌ | 25773/30196 [53:30<07:23,  9.96it/s]

 85%|████████▌ | 25775/30196 [53:30<07:16, 10.13it/s]

 85%|████████▌ | 25777/30196 [53:30<08:05,  9.10it/s]

 85%|████████▌ | 25778/30196 [53:30<08:48,  8.36it/s]

 85%|████████▌ | 25780/30196 [53:30<07:30,  9.81it/s]

 85%|████████▌ | 25782/30196 [53:31<08:08,  9.03it/s]

 85%|████████▌ | 25783/30196 [53:31<08:28,  8.69it/s]

 85%|████████▌ | 25785/30196 [53:31<10:07,  7.26it/s]

 85%|████████▌ | 25786/30196 [53:31<10:40,  6.89it/s]

 85%|████████▌ | 25787/30196 [53:32<10:30,  6.99it/s]

 85%|████████▌ | 25788/30196 [53:32<11:03,  6.64it/s]

 85%|████████▌ | 25790/30196 [53:32<08:20,  8.80it/s]

 85%|████████▌ | 25792/30196 [53:32<08:27,  8.68it/s]

 85%|████████▌ | 25794/30196 [53:32<07:35,  9.66it/s]

 85%|████████▌ | 25796/30196 [53:32<07:14, 10.13it/s]

 85%|████████▌ | 25798/30196 [53:33<07:13, 10.15it/s]

 85%|████████▌ | 25800/30196 [53:33<07:23,  9.92it/s]

 85%|████████▌ | 25802/30196 [53:33<09:04,  8.07it/s]

 85%|████████▌ | 25803/30196 [53:33<08:48,  8.31it/s]

 85%|████████▌ | 25804/30196 [53:33<10:06,  7.24it/s]

 85%|████████▌ | 25805/30196 [53:34<09:33,  7.65it/s]

 85%|████████▌ | 25806/30196 [53:34<09:10,  7.97it/s]

 85%|████████▌ | 25808/30196 [53:34<08:43,  8.38it/s]

 85%|████████▌ | 25809/30196 [53:34<09:05,  8.04it/s]

 85%|████████▌ | 25811/30196 [53:34<08:18,  8.80it/s]

 85%|████████▌ | 25813/30196 [53:34<07:14, 10.08it/s]

 85%|████████▌ | 25815/30196 [53:35<07:16, 10.05it/s]

 85%|████████▌ | 25817/30196 [53:35<09:43,  7.51it/s]

 86%|████████▌ | 25819/30196 [53:35<10:25,  7.00it/s]

 86%|████████▌ | 25821/30196 [53:35<08:49,  8.26it/s]

 86%|████████▌ | 25822/30196 [53:36<10:41,  6.82it/s]

 86%|████████▌ | 25823/30196 [53:36<12:18,  5.92it/s]

 86%|████████▌ | 25825/30196 [53:36<09:33,  7.62it/s]

 86%|████████▌ | 25826/30196 [53:36<09:32,  7.63it/s]

 86%|████████▌ | 25827/30196 [53:36<09:47,  7.44it/s]

 86%|████████▌ | 25828/30196 [53:37<09:50,  7.40it/s]

 86%|████████▌ | 25830/30196 [53:37<08:42,  8.35it/s]

 86%|████████▌ | 25832/30196 [53:37<09:58,  7.30it/s]

 86%|████████▌ | 25834/30196 [53:37<09:03,  8.03it/s]

 86%|████████▌ | 25835/30196 [53:38<11:37,  6.25it/s]

 86%|████████▌ | 25836/30196 [53:38<11:42,  6.20it/s]

 86%|████████▌ | 25838/30196 [53:38<08:35,  8.45it/s]

 86%|████████▌ | 25840/30196 [53:38<07:43,  9.40it/s]

 86%|████████▌ | 25842/30196 [53:38<07:55,  9.16it/s]

 86%|████████▌ | 25844/30196 [53:39<10:32,  6.88it/s]

 86%|████████▌ | 25845/30196 [53:39<10:51,  6.68it/s]

 86%|████████▌ | 25846/30196 [53:39<10:15,  7.07it/s]

 86%|████████▌ | 25847/30196 [53:39<10:19,  7.01it/s]

 86%|████████▌ | 25848/30196 [53:39<10:46,  6.72it/s]

 86%|████████▌ | 25850/30196 [53:39<08:04,  8.98it/s]

 86%|████████▌ | 25852/30196 [53:40<07:58,  9.08it/s]

 86%|████████▌ | 25853/30196 [53:40<08:48,  8.22it/s]

 86%|████████▌ | 25854/30196 [53:40<08:35,  8.42it/s]

 86%|████████▌ | 25855/30196 [53:40<09:27,  7.65it/s]

 86%|████████▌ | 25856/30196 [53:40<09:44,  7.42it/s]

 86%|████████▌ | 25858/30196 [53:40<08:17,  8.71it/s]

 86%|████████▌ | 25859/30196 [53:41<08:43,  8.29it/s]

 86%|████████▌ | 25861/30196 [53:41<08:18,  8.70it/s]

 86%|████████▌ | 25862/30196 [53:41<09:48,  7.36it/s]

 86%|████████▌ | 25863/30196 [53:41<10:19,  7.00it/s]

 86%|████████▌ | 25865/30196 [53:41<10:15,  7.03it/s]

 86%|████████▌ | 25867/30196 [53:42<09:05,  7.94it/s]

 86%|████████▌ | 25869/30196 [53:42<09:12,  7.83it/s]

 86%|████████▌ | 25870/30196 [53:42<08:53,  8.11it/s]

 86%|████████▌ | 25871/30196 [53:42<09:00,  8.01it/s]

 86%|████████▌ | 25872/30196 [53:42<09:15,  7.79it/s]

 86%|████████▌ | 25873/30196 [53:42<08:55,  8.07it/s]

 86%|████████▌ | 25874/30196 [53:43<14:35,  4.94it/s]

 86%|████████▌ | 25875/30196 [53:43<13:08,  5.48it/s]

 86%|████████▌ | 25877/30196 [53:43<09:06,  7.90it/s]

 86%|████████▌ | 25879/30196 [53:43<07:21,  9.78it/s]

 86%|████████▌ | 25881/30196 [53:43<09:04,  7.93it/s]

 86%|████████▌ | 25883/30196 [53:44<07:50,  9.17it/s]

 86%|████████▌ | 25885/30196 [53:44<07:48,  9.21it/s]

 86%|████████▌ | 25887/30196 [53:44<07:30,  9.58it/s]

 86%|████████▌ | 25889/30196 [53:44<06:17, 11.41it/s]

 86%|████████▌ | 25891/30196 [53:44<07:25,  9.67it/s]

 86%|████████▌ | 25893/30196 [53:45<07:32,  9.51it/s]

 86%|████████▌ | 25895/30196 [53:45<06:59, 10.25it/s]

 86%|████████▌ | 25897/30196 [53:45<07:36,  9.42it/s]

 86%|████████▌ | 25899/30196 [53:45<06:34, 10.88it/s]

 86%|████████▌ | 25901/30196 [53:45<07:42,  9.30it/s]

 86%|████████▌ | 25903/30196 [53:46<07:21,  9.72it/s]

 86%|████████▌ | 25905/30196 [53:46<07:06, 10.06it/s]

 86%|████████▌ | 25907/30196 [53:46<06:33, 10.91it/s]

 86%|████████▌ | 25909/30196 [53:46<07:27,  9.58it/s]

 86%|████████▌ | 25911/30196 [53:46<06:22, 11.21it/s]

 86%|████████▌ | 25913/30196 [53:47<08:07,  8.79it/s]

 86%|████████▌ | 25915/30196 [53:47<09:04,  7.87it/s]

 86%|████████▌ | 25916/30196 [53:47<09:33,  7.47it/s]

 86%|████████▌ | 25918/30196 [53:47<08:57,  7.96it/s]

 86%|████████▌ | 25920/30196 [53:48<08:24,  8.48it/s]

 86%|████████▌ | 25922/30196 [53:48<07:44,  9.21it/s]

 86%|████████▌ | 25923/30196 [53:48<07:41,  9.26it/s]

 86%|████████▌ | 25925/30196 [53:48<07:12,  9.87it/s]

 86%|████████▌ | 25927/30196 [53:48<08:42,  8.16it/s]

 86%|████████▌ | 25928/30196 [53:48<09:02,  7.87it/s]

 86%|████████▌ | 25930/30196 [53:49<08:33,  8.30it/s]

 86%|████████▌ | 25932/30196 [53:49<08:11,  8.67it/s]

 86%|████████▌ | 25933/30196 [53:49<09:38,  7.37it/s]

 86%|████████▌ | 25934/30196 [53:49<10:13,  6.94it/s]

 86%|████████▌ | 25935/30196 [53:49<10:36,  6.70it/s]

 86%|████████▌ | 25936/30196 [53:50<11:01,  6.44it/s]

 86%|████████▌ | 25937/30196 [53:50<10:51,  6.54it/s]

 86%|████████▌ | 25938/30196 [53:50<12:17,  5.77it/s]

 86%|████████▌ | 25940/30196 [53:50<09:04,  7.81it/s]

 86%|████████▌ | 25942/30196 [53:50<08:34,  8.27it/s]

 86%|████████▌ | 25944/30196 [53:51<07:34,  9.36it/s]

 86%|████████▌ | 25945/30196 [53:51<08:28,  8.36it/s]

 86%|████████▌ | 25946/30196 [53:51<09:25,  7.51it/s]

 86%|████████▌ | 25948/30196 [53:51<08:48,  8.04it/s]

 86%|████████▌ | 25950/30196 [53:51<07:20,  9.64it/s]

 86%|████████▌ | 25952/30196 [53:51<06:37, 10.68it/s]

 86%|████████▌ | 25954/30196 [53:52<06:39, 10.62it/s]

 86%|████████▌ | 25956/30196 [53:52<06:14, 11.32it/s]

 86%|████████▌ | 25958/30196 [53:52<05:34, 12.67it/s]

 86%|████████▌ | 25960/30196 [53:52<05:46, 12.21it/s]

 86%|████████▌ | 25962/30196 [53:52<06:29, 10.88it/s]

 86%|████████▌ | 25964/30196 [53:52<06:06, 11.54it/s]

 86%|████████▌ | 25966/30196 [53:53<07:13,  9.76it/s]

 86%|████████▌ | 25968/30196 [53:53<07:09,  9.85it/s]

 86%|████████▌ | 25970/30196 [53:53<06:22, 11.06it/s]

 86%|████████▌ | 25972/30196 [53:53<06:34, 10.69it/s]

 86%|████████▌ | 25974/30196 [53:53<07:27,  9.43it/s]

 86%|████████▌ | 25976/30196 [53:54<07:31,  9.35it/s]

 86%|████████▌ | 25977/30196 [53:54<08:45,  8.02it/s]

 86%|████████▌ | 25979/30196 [53:54<08:36,  8.16it/s]

 86%|████████▌ | 25980/30196 [53:54<08:46,  8.01it/s]

 86%|████████▌ | 25982/30196 [53:54<07:19,  9.58it/s]

 86%|████████▌ | 25984/30196 [53:55<07:41,  9.12it/s]

 86%|████████▌ | 25986/30196 [53:55<07:23,  9.50it/s]

 86%|████████▌ | 25989/30196 [53:55<06:34, 10.67it/s]

 86%|████████▌ | 25991/30196 [53:55<07:41,  9.11it/s]

 86%|████████▌ | 25993/30196 [53:56<06:51, 10.22it/s]

 86%|████████▌ | 25995/30196 [53:56<07:25,  9.42it/s]

 86%|████████▌ | 25997/30196 [53:56<07:25,  9.42it/s]

 86%|████████▌ | 25998/30196 [53:56<07:44,  9.05it/s]

 86%|████████▌ | 25999/30196 [53:56<08:00,  8.74it/s]

 86%|████████▌ | 26001/30196 [53:57<09:06,  7.68it/s]

 86%|████████▌ | 26002/30196 [53:57<09:37,  7.26it/s]

 86%|████████▌ | 26003/30196 [53:57<11:05,  6.30it/s]

 86%|████████▌ | 26004/30196 [53:57<11:57,  5.84it/s]

 86%|████████▌ | 26005/30196 [53:57<10:45,  6.49it/s]

 86%|████████▌ | 26006/30196 [53:57<09:48,  7.12it/s]

 86%|████████▌ | 26008/30196 [53:58<09:42,  7.19it/s]

 86%|████████▌ | 26010/30196 [53:58<09:53,  7.06it/s]

 86%|████████▌ | 26012/30196 [53:58<08:29,  8.22it/s]

 86%|████████▌ | 26013/30196 [53:58<09:09,  7.61it/s]

 86%|████████▌ | 26015/30196 [53:58<07:50,  8.89it/s]

 86%|████████▌ | 26017/30196 [53:59<06:38, 10.48it/s]

 86%|████████▌ | 26019/30196 [53:59<07:34,  9.19it/s]

 86%|████████▌ | 26021/30196 [53:59<07:34,  9.18it/s]

 86%|████████▌ | 26022/30196 [53:59<08:25,  8.26it/s]

 86%|████████▌ | 26024/30196 [53:59<08:02,  8.65it/s]

 86%|████████▌ | 26026/30196 [54:00<08:04,  8.61it/s]

 86%|████████▌ | 26027/30196 [54:00<08:24,  8.27it/s]

 86%|████████▌ | 26029/30196 [54:00<09:01,  7.69it/s]

 86%|████████▌ | 26030/30196 [54:00<09:05,  7.64it/s]

 86%|████████▌ | 26031/30196 [54:00<09:09,  7.58it/s]

 86%|████████▌ | 26032/30196 [54:00<08:46,  7.90it/s]

 86%|████████▌ | 26033/30196 [54:01<09:41,  7.16it/s]

 86%|████████▌ | 26034/30196 [54:01<13:51,  5.01it/s]

 86%|████████▌ | 26035/30196 [54:01<12:32,  5.53it/s]

 86%|████████▌ | 26037/30196 [54:01<10:10,  6.81it/s]

 86%|████████▌ | 26038/30196 [54:02<09:54,  7.00it/s]

 86%|████████▌ | 26040/30196 [54:02<08:56,  7.74it/s]

 86%|████████▌ | 26041/30196 [54:02<08:38,  8.02it/s]

 86%|████████▌ | 26042/30196 [54:02<08:53,  7.78it/s]

 86%|████████▌ | 26043/30196 [54:02<08:34,  8.08it/s]

 86%|████████▋ | 26045/30196 [54:02<08:22,  8.25it/s]

 86%|████████▋ | 26047/30196 [54:02<07:22,  9.37it/s]

 86%|████████▋ | 26048/30196 [54:03<07:23,  9.36it/s]

 86%|████████▋ | 26049/30196 [54:03<08:20,  8.29it/s]

 86%|████████▋ | 26050/30196 [54:03<08:41,  7.95it/s]

 86%|████████▋ | 26052/30196 [54:03<07:40,  8.99it/s]

 86%|████████▋ | 26054/30196 [54:03<08:24,  8.22it/s]

 86%|████████▋ | 26055/30196 [54:04<11:54,  5.80it/s]

 86%|████████▋ | 26056/30196 [54:04<11:24,  6.05it/s]

 86%|████████▋ | 26058/30196 [54:04<10:20,  6.67it/s]

 86%|████████▋ | 26060/30196 [54:04<09:31,  7.24it/s]

 86%|████████▋ | 26061/30196 [54:05<13:10,  5.23it/s]

 86%|████████▋ | 26063/30196 [54:05<11:05,  6.21it/s]

 86%|████████▋ | 26065/30196 [54:05<09:36,  7.17it/s]

 86%|████████▋ | 26067/30196 [54:05<08:52,  7.75it/s]

 86%|████████▋ | 26068/30196 [54:06<08:56,  7.70it/s]

 86%|████████▋ | 26070/30196 [54:06<09:01,  7.62it/s]

 86%|████████▋ | 26071/30196 [54:06<08:39,  7.95it/s]

 86%|████████▋ | 26073/30196 [54:06<12:21,  5.56it/s]

 86%|████████▋ | 26074/30196 [54:07<11:39,  5.89it/s]

 86%|████████▋ | 26076/30196 [54:07<09:24,  7.30it/s]

 86%|████████▋ | 26077/30196 [54:07<09:48,  6.99it/s]

 86%|████████▋ | 26079/30196 [54:07<08:50,  7.75it/s]

 86%|████████▋ | 26081/30196 [54:07<08:50,  7.76it/s]

 86%|████████▋ | 26082/30196 [54:08<08:54,  7.70it/s]

 86%|████████▋ | 26083/30196 [54:08<10:22,  6.61it/s]

 86%|████████▋ | 26085/30196 [54:08<07:50,  8.74it/s]

 86%|████████▋ | 26087/30196 [54:08<08:52,  7.71it/s]

 86%|████████▋ | 26089/30196 [54:08<09:03,  7.56it/s]

 86%|████████▋ | 26091/30196 [54:09<15:55,  4.30it/s]

 86%|████████▋ | 26093/30196 [54:10<15:00,  4.56it/s]

 86%|████████▋ | 26094/30196 [54:10<14:06,  4.85it/s]

 86%|████████▋ | 26095/30196 [54:10<13:01,  5.25it/s]

 86%|████████▋ | 26096/30196 [54:10<13:30,  5.06it/s]

 86%|████████▋ | 26097/30196 [54:10<12:33,  5.44it/s]

 86%|████████▋ | 26098/30196 [54:10<11:13,  6.08it/s]

 86%|████████▋ | 26099/30196 [54:11<11:15,  6.06it/s]

 86%|████████▋ | 26101/30196 [54:11<08:35,  7.94it/s]

 86%|████████▋ | 26103/30196 [54:11<06:44, 10.12it/s]

 86%|████████▋ | 26105/30196 [54:11<05:56, 11.47it/s]

 86%|████████▋ | 26107/30196 [54:11<05:26, 12.51it/s]

 86%|████████▋ | 26109/30196 [54:11<07:03,  9.64it/s]

 86%|████████▋ | 26111/30196 [54:12<08:09,  8.35it/s]

 86%|████████▋ | 26113/30196 [54:12<07:54,  8.60it/s]

 86%|████████▋ | 26114/30196 [54:12<08:17,  8.21it/s]

 86%|████████▋ | 26116/30196 [54:12<07:56,  8.57it/s]

 86%|████████▋ | 26118/30196 [54:12<06:49,  9.97it/s]

 87%|████████▋ | 26120/30196 [54:13<05:56, 11.42it/s]

 87%|████████▋ | 26122/30196 [54:13<07:15,  9.36it/s]

 87%|████████▋ | 26125/30196 [54:13<05:41, 11.91it/s]

 87%|████████▋ | 26127/30196 [54:13<06:02, 11.22it/s]

 87%|████████▋ | 26129/30196 [54:13<06:29, 10.44it/s]

 87%|████████▋ | 26131/30196 [54:14<06:01, 11.25it/s]

 87%|████████▋ | 26133/30196 [54:14<06:54,  9.81it/s]

 87%|████████▋ | 26135/30196 [54:14<07:07,  9.51it/s]

 87%|████████▋ | 26137/30196 [54:14<07:14,  9.34it/s]

 87%|████████▋ | 26138/30196 [54:14<07:42,  8.77it/s]

 87%|████████▋ | 26139/30196 [54:15<09:33,  7.08it/s]

 87%|████████▋ | 26141/30196 [54:15<08:41,  7.78it/s]

 87%|████████▋ | 26142/30196 [54:15<08:50,  7.64it/s]

 87%|████████▋ | 26144/30196 [54:15<07:44,  8.72it/s]

 87%|████████▋ | 26145/30196 [54:15<08:11,  8.25it/s]

 87%|████████▋ | 26147/30196 [54:16<09:02,  7.47it/s]

 87%|████████▋ | 26149/30196 [54:16<07:47,  8.65it/s]

 87%|████████▋ | 26150/30196 [54:16<08:32,  7.89it/s]

 87%|████████▋ | 26151/30196 [54:16<09:45,  6.91it/s]

 87%|████████▋ | 26153/30196 [54:16<07:44,  8.70it/s]

 87%|████████▋ | 26155/30196 [54:17<06:44,  9.99it/s]

 87%|████████▋ | 26157/30196 [54:17<08:21,  8.06it/s]

 87%|████████▋ | 26158/30196 [54:17<09:30,  7.08it/s]

 87%|████████▋ | 26160/30196 [54:17<07:19,  9.19it/s]

 87%|████████▋ | 26162/30196 [54:18<09:36,  6.99it/s]

 87%|████████▋ | 26163/30196 [54:18<09:30,  7.06it/s]

 87%|████████▋ | 26164/30196 [54:18<09:02,  7.43it/s]

 87%|████████▋ | 26165/30196 [54:18<09:08,  7.35it/s]

 87%|████████▋ | 26167/30196 [54:18<07:12,  9.31it/s]

 87%|████████▋ | 26169/30196 [54:18<08:12,  8.18it/s]

 87%|████████▋ | 26170/30196 [54:19<08:18,  8.08it/s]

 87%|████████▋ | 26171/30196 [54:19<08:24,  7.98it/s]

 87%|████████▋ | 26172/30196 [54:19<09:58,  6.72it/s]

 87%|████████▋ | 26173/30196 [54:19<13:03,  5.13it/s]

 87%|████████▋ | 26175/30196 [54:19<10:00,  6.70it/s]

 87%|████████▋ | 26177/30196 [54:20<09:12,  7.27it/s]

 87%|████████▋ | 26179/30196 [54:20<08:14,  8.12it/s]

 87%|████████▋ | 26180/30196 [54:20<08:03,  8.31it/s]

 87%|████████▋ | 26181/30196 [54:20<08:26,  7.92it/s]

 87%|████████▋ | 26183/30196 [54:20<07:31,  8.90it/s]

 87%|████████▋ | 26184/30196 [54:20<08:28,  7.89it/s]

 87%|████████▋ | 26185/30196 [54:21<09:09,  7.30it/s]

 87%|████████▋ | 26187/30196 [54:21<08:39,  7.72it/s]

 87%|████████▋ | 26188/30196 [54:21<09:47,  6.82it/s]

 87%|████████▋ | 26190/30196 [54:21<08:19,  8.03it/s]

 87%|████████▋ | 26192/30196 [54:21<07:18,  9.13it/s]

 87%|████████▋ | 26193/30196 [54:22<08:49,  7.55it/s]

 87%|████████▋ | 26194/30196 [54:22<08:47,  7.59it/s]

 87%|████████▋ | 26195/30196 [54:22<09:58,  6.69it/s]

 87%|████████▋ | 26197/30196 [54:22<07:16,  9.16it/s]

 87%|████████▋ | 26199/30196 [54:23<10:13,  6.52it/s]

 87%|████████▋ | 26200/30196 [54:23<10:35,  6.29it/s]

 87%|████████▋ | 26202/30196 [54:23<08:28,  7.86it/s]

 87%|████████▋ | 26203/30196 [54:23<09:11,  7.24it/s]

 87%|████████▋ | 26205/30196 [54:23<07:32,  8.83it/s]

 87%|████████▋ | 26207/30196 [54:24<09:45,  6.81it/s]

 87%|████████▋ | 26209/30196 [54:24<08:00,  8.30it/s]

 87%|████████▋ | 26211/30196 [54:24<06:50,  9.70it/s]

 87%|████████▋ | 26213/30196 [54:24<06:02, 10.99it/s]

 87%|████████▋ | 26215/30196 [54:24<06:58,  9.51it/s]

 87%|████████▋ | 26217/30196 [54:24<06:34, 10.10it/s]

 87%|████████▋ | 26219/30196 [54:25<07:43,  8.57it/s]

 87%|████████▋ | 26220/30196 [54:25<08:22,  7.91it/s]

 87%|████████▋ | 26222/30196 [54:25<07:27,  8.87it/s]

 87%|████████▋ | 26225/30196 [54:25<05:56, 11.14it/s]

 87%|████████▋ | 26227/30196 [54:26<06:56,  9.52it/s]

 87%|████████▋ | 26229/30196 [54:26<07:13,  9.15it/s]

 87%|████████▋ | 26230/30196 [54:26<07:30,  8.80it/s]

 87%|████████▋ | 26231/30196 [54:26<08:14,  8.01it/s]

 87%|████████▋ | 26233/30196 [54:26<07:37,  8.66it/s]

 87%|████████▋ | 26234/30196 [54:26<08:03,  8.19it/s]

 87%|████████▋ | 26235/30196 [54:27<08:42,  7.59it/s]

 87%|████████▋ | 26236/30196 [54:27<09:26,  7.00it/s]

 87%|████████▋ | 26237/30196 [54:27<10:38,  6.20it/s]

 87%|████████▋ | 26238/30196 [54:27<11:34,  5.70it/s]

 87%|████████▋ | 26239/30196 [54:27<10:22,  6.36it/s]

 87%|████████▋ | 26240/30196 [54:27<10:31,  6.27it/s]

 87%|████████▋ | 26241/30196 [54:28<10:39,  6.19it/s]

 87%|████████▋ | 26242/30196 [54:28<10:59,  5.99it/s]

 87%|████████▋ | 26244/30196 [54:28<08:47,  7.49it/s]

 87%|████████▋ | 26245/30196 [54:28<08:49,  7.47it/s]

 87%|████████▋ | 26247/30196 [54:28<07:45,  8.49it/s]

 87%|████████▋ | 26248/30196 [54:28<08:05,  8.13it/s]

 87%|████████▋ | 26249/30196 [54:29<07:47,  8.45it/s]

 87%|████████▋ | 26250/30196 [54:29<07:30,  8.75it/s]

 87%|████████▋ | 26251/30196 [54:29<08:03,  8.16it/s]

 87%|████████▋ | 26252/30196 [54:29<08:30,  7.72it/s]

 87%|████████▋ | 26253/30196 [54:29<10:01,  6.55it/s]

 87%|████████▋ | 26255/30196 [54:29<07:12,  9.11it/s]

 87%|████████▋ | 26257/30196 [54:29<05:54, 11.13it/s]

 87%|████████▋ | 26259/30196 [54:30<06:34,  9.97it/s]

 87%|████████▋ | 26261/30196 [54:30<07:19,  8.95it/s]

 87%|████████▋ | 26262/30196 [54:30<07:17,  8.99it/s]

 87%|████████▋ | 26264/30196 [54:30<06:44,  9.73it/s]

 87%|████████▋ | 26266/30196 [54:30<06:37,  9.90it/s]

 87%|████████▋ | 26268/30196 [54:31<07:18,  8.96it/s]

 87%|████████▋ | 26269/30196 [54:31<09:01,  7.25it/s]

 87%|████████▋ | 26270/30196 [54:31<08:55,  7.33it/s]

 87%|████████▋ | 26271/30196 [54:31<11:43,  5.58it/s]

 87%|████████▋ | 26272/30196 [54:32<11:05,  5.90it/s]

 87%|████████▋ | 26274/30196 [54:32<09:14,  7.08it/s]

 87%|████████▋ | 26276/30196 [54:32<07:58,  8.19it/s]

 87%|████████▋ | 26278/30196 [54:32<06:32,  9.99it/s]

 87%|████████▋ | 26280/30196 [54:32<07:08,  9.13it/s]

 87%|████████▋ | 26282/30196 [54:33<08:50,  7.38it/s]

 87%|████████▋ | 26284/30196 [54:33<08:19,  7.84it/s]

 87%|████████▋ | 26285/30196 [54:33<10:33,  6.17it/s]

 87%|████████▋ | 26287/30196 [54:34<10:56,  5.95it/s]

 87%|████████▋ | 26288/30196 [54:34<10:07,  6.43it/s]

 87%|████████▋ | 26289/30196 [54:34<09:59,  6.51it/s]

 87%|████████▋ | 26290/30196 [54:34<09:46,  6.66it/s]

 87%|████████▋ | 26291/30196 [54:34<10:01,  6.49it/s]

 87%|████████▋ | 26293/30196 [54:34<08:02,  8.09it/s]

 87%|████████▋ | 26295/30196 [54:34<06:15, 10.40it/s]

 87%|████████▋ | 26297/30196 [54:35<06:10, 10.52it/s]

 87%|████████▋ | 26299/30196 [54:35<06:13, 10.43it/s]

 87%|████████▋ | 26301/30196 [54:35<06:16, 10.34it/s]

 87%|████████▋ | 26303/30196 [54:35<06:16, 10.33it/s]

 87%|████████▋ | 26305/30196 [54:35<06:42,  9.67it/s]

 87%|████████▋ | 26307/30196 [54:36<06:36,  9.82it/s]

 87%|████████▋ | 26309/30196 [54:36<06:51,  9.46it/s]

 87%|████████▋ | 26310/30196 [54:36<06:54,  9.38it/s]

 87%|████████▋ | 26311/30196 [54:36<07:51,  8.25it/s]

 87%|████████▋ | 26312/30196 [54:36<07:41,  8.41it/s]

 87%|████████▋ | 26313/30196 [54:36<07:32,  8.58it/s]

 87%|████████▋ | 26315/30196 [54:37<07:48,  8.28it/s]

 87%|████████▋ | 26316/30196 [54:37<08:01,  8.06it/s]

 87%|████████▋ | 26317/30196 [54:37<08:06,  7.97it/s]

 87%|████████▋ | 26319/30196 [54:37<06:46,  9.54it/s]

 87%|████████▋ | 26321/30196 [54:37<06:33,  9.84it/s]

 87%|████████▋ | 26322/30196 [54:37<06:57,  9.28it/s]

 87%|████████▋ | 26323/30196 [54:37<07:56,  8.13it/s]

 87%|████████▋ | 26324/30196 [54:38<08:03,  8.02it/s]

 87%|████████▋ | 26325/30196 [54:38<08:25,  7.66it/s]

 87%|████████▋ | 26326/30196 [54:38<08:42,  7.41it/s]

 87%|████████▋ | 26328/30196 [54:38<06:48,  9.46it/s]

 87%|████████▋ | 26329/30196 [54:38<07:12,  8.95it/s]

 87%|████████▋ | 26331/30196 [54:38<07:02,  9.15it/s]

 87%|████████▋ | 26332/30196 [54:39<07:19,  8.78it/s]

 87%|████████▋ | 26333/30196 [54:39<10:27,  6.15it/s]

 87%|████████▋ | 26335/30196 [54:39<07:56,  8.10it/s]

 87%|████████▋ | 26336/30196 [54:39<08:17,  7.76it/s]

 87%|████████▋ | 26338/30196 [54:40<10:28,  6.14it/s]

 87%|████████▋ | 26340/30196 [54:40<08:50,  7.27it/s]

 87%|████████▋ | 26341/30196 [54:40<08:28,  7.58it/s]

 87%|████████▋ | 26342/30196 [54:40<08:05,  7.94it/s]

 87%|████████▋ | 26343/30196 [54:40<07:44,  8.29it/s]

 87%|████████▋ | 26345/30196 [54:40<06:30,  9.87it/s]

 87%|████████▋ | 26347/30196 [54:40<06:33,  9.78it/s]

 87%|████████▋ | 26349/30196 [54:41<07:10,  8.93it/s]

 87%|████████▋ | 26351/30196 [54:41<06:46,  9.45it/s]

 87%|████████▋ | 26352/30196 [54:41<07:12,  8.88it/s]

 87%|████████▋ | 26353/30196 [54:41<07:34,  8.45it/s]

 87%|████████▋ | 26355/30196 [54:41<07:05,  9.03it/s]

 87%|████████▋ | 26356/30196 [54:41<07:22,  8.68it/s]

 87%|████████▋ | 26358/30196 [54:42<06:42,  9.54it/s]

 87%|████████▋ | 26360/30196 [54:42<08:32,  7.48it/s]

 87%|████████▋ | 26361/30196 [54:42<08:14,  7.75it/s]

 87%|████████▋ | 26363/30196 [54:42<06:47,  9.41it/s]

 87%|████████▋ | 26365/30196 [54:43<07:15,  8.81it/s]

 87%|████████▋ | 26366/30196 [54:43<08:36,  7.42it/s]

 87%|████████▋ | 26368/30196 [54:43<10:08,  6.30it/s]

 87%|████████▋ | 26369/30196 [54:43<09:49,  6.49it/s]

 87%|████████▋ | 26370/30196 [54:43<09:58,  6.39it/s]

 87%|████████▋ | 26372/30196 [54:44<08:09,  7.81it/s]

 87%|████████▋ | 26373/30196 [54:44<08:43,  7.30it/s]

 87%|████████▋ | 26374/30196 [54:44<10:27,  6.09it/s]

 87%|████████▋ | 26376/30196 [54:44<09:09,  6.95it/s]

 87%|████████▋ | 26378/30196 [54:44<07:21,  8.66it/s]

 87%|████████▋ | 26380/30196 [54:45<07:43,  8.24it/s]

 87%|████████▋ | 26381/30196 [54:45<08:16,  7.68it/s]

 87%|████████▋ | 26382/30196 [54:45<07:59,  7.96it/s]

 87%|████████▋ | 26384/30196 [54:45<06:13, 10.20it/s]

 87%|████████▋ | 26386/30196 [54:45<06:01, 10.53it/s]

 87%|████████▋ | 26388/30196 [54:45<06:11, 10.24it/s]

 87%|████████▋ | 26390/30196 [54:46<06:25,  9.88it/s]

 87%|████████▋ | 26392/30196 [54:46<07:54,  8.02it/s]

 87%|████████▋ | 26393/30196 [54:46<07:57,  7.96it/s]

 87%|████████▋ | 26394/30196 [54:46<08:32,  7.42it/s]

 87%|████████▋ | 26395/30196 [54:47<13:00,  4.87it/s]

 87%|████████▋ | 26397/30196 [54:47<10:12,  6.21it/s]

 87%|████████▋ | 26399/30196 [54:47<08:00,  7.90it/s]

 87%|████████▋ | 26400/30196 [54:47<07:46,  8.13it/s]

 87%|████████▋ | 26402/30196 [54:47<06:26,  9.81it/s]

 87%|████████▋ | 26404/30196 [54:48<06:47,  9.30it/s]

 87%|████████▋ | 26406/30196 [54:48<07:11,  8.78it/s]

 87%|████████▋ | 26407/30196 [54:48<07:58,  7.93it/s]

 87%|████████▋ | 26409/30196 [54:48<07:23,  8.54it/s]

 87%|████████▋ | 26411/30196 [54:48<06:52,  9.17it/s]

 87%|████████▋ | 26412/30196 [54:48<07:32,  8.35it/s]

 87%|████████▋ | 26413/30196 [54:49<07:24,  8.51it/s]

 87%|████████▋ | 26415/30196 [54:49<06:31,  9.66it/s]

 87%|████████▋ | 26416/30196 [54:49<06:53,  9.15it/s]

 87%|████████▋ | 26418/30196 [54:49<05:58, 10.53it/s]

 87%|████████▋ | 26420/30196 [54:49<05:50, 10.78it/s]

 88%|████████▊ | 26422/30196 [54:49<05:10, 12.17it/s]

 88%|████████▊ | 26424/30196 [54:50<06:00, 10.45it/s]

 88%|████████▊ | 26426/30196 [54:50<06:53,  9.12it/s]

 88%|████████▊ | 26427/30196 [54:50<07:19,  8.57it/s]

 88%|████████▊ | 26428/30196 [54:50<07:34,  8.29it/s]

 88%|████████▊ | 26429/30196 [54:50<08:49,  7.11it/s]

 88%|████████▊ | 26431/30196 [54:51<08:21,  7.51it/s]

 88%|████████▊ | 26432/30196 [54:51<08:33,  7.33it/s]

 88%|████████▊ | 26433/30196 [54:51<08:08,  7.70it/s]

 88%|████████▊ | 26434/30196 [54:51<07:59,  7.85it/s]

 88%|████████▊ | 26435/30196 [54:51<07:40,  8.17it/s]

 88%|████████▊ | 26437/30196 [54:51<06:25,  9.76it/s]

 88%|████████▊ | 26439/30196 [54:51<06:29,  9.64it/s]

 88%|████████▊ | 26441/30196 [54:52<06:21,  9.83it/s]

 88%|████████▊ | 26442/30196 [54:52<06:43,  9.29it/s]

 88%|████████▊ | 26443/30196 [54:52<08:48,  7.10it/s]

 88%|████████▊ | 26445/30196 [54:52<08:05,  7.72it/s]

 88%|████████▊ | 26447/30196 [54:52<06:59,  8.93it/s]

 88%|████████▊ | 26448/30196 [54:53<07:44,  8.08it/s]

 88%|████████▊ | 26449/30196 [54:53<07:53,  7.92it/s]

 88%|████████▊ | 26450/30196 [54:53<09:10,  6.80it/s]

 88%|████████▊ | 26451/30196 [54:53<10:21,  6.03it/s]

 88%|████████▊ | 26453/30196 [54:54<11:01,  5.66it/s]

 88%|████████▊ | 26455/30196 [54:54<09:52,  6.31it/s]

 88%|████████▊ | 26456/30196 [54:54<11:05,  5.62it/s]

 88%|████████▊ | 26457/30196 [54:54<12:17,  5.07it/s]

 88%|████████▊ | 26459/30196 [54:54<09:02,  6.89it/s]

 88%|████████▊ | 26460/30196 [54:55<09:02,  6.88it/s]

 88%|████████▊ | 26461/30196 [54:55<10:35,  5.88it/s]

 88%|████████▊ | 26462/30196 [54:55<10:14,  6.08it/s]

 88%|████████▊ | 26463/30196 [54:55<11:08,  5.58it/s]

 88%|████████▊ | 26465/30196 [54:55<08:32,  7.28it/s]

 88%|████████▊ | 26466/30196 [54:56<10:56,  5.68it/s]

 88%|████████▊ | 26467/30196 [54:56<11:25,  5.44it/s]

 88%|████████▊ | 26468/30196 [54:56<10:32,  5.90it/s]

 88%|████████▊ | 26470/30196 [54:56<07:35,  8.19it/s]

 88%|████████▊ | 26471/30196 [54:57<18:24,  3.37it/s]

 88%|████████▊ | 26473/30196 [54:57<12:15,  5.06it/s]

 88%|████████▊ | 26475/30196 [54:57<09:32,  6.50it/s]

 88%|████████▊ | 26477/30196 [54:58<09:06,  6.80it/s]

 88%|████████▊ | 26479/30196 [54:58<07:56,  7.80it/s]

 88%|████████▊ | 26481/30196 [54:58<07:18,  8.47it/s]

 88%|████████▊ | 26483/30196 [54:58<07:19,  8.44it/s]

 88%|████████▊ | 26485/30196 [54:58<06:29,  9.54it/s]

 88%|████████▊ | 26487/30196 [54:59<07:49,  7.90it/s]

 88%|████████▊ | 26488/30196 [54:59<08:46,  7.04it/s]

 88%|████████▊ | 26490/30196 [54:59<06:54,  8.95it/s]

 88%|████████▊ | 26492/30196 [54:59<07:36,  8.11it/s]

 88%|████████▊ | 26495/30196 [54:59<06:38,  9.28it/s]

 88%|████████▊ | 26497/30196 [55:00<06:09, 10.02it/s]

 88%|████████▊ | 26499/30196 [55:00<07:04,  8.71it/s]

 88%|████████▊ | 26501/30196 [55:00<06:21,  9.69it/s]

 88%|████████▊ | 26503/30196 [55:00<06:14,  9.87it/s]

 88%|████████▊ | 26505/30196 [55:00<05:28, 11.23it/s]

 88%|████████▊ | 26507/30196 [55:01<06:58,  8.80it/s]

 88%|████████▊ | 26509/30196 [55:01<07:03,  8.71it/s]

 88%|████████▊ | 26511/30196 [55:01<06:03, 10.14it/s]

 88%|████████▊ | 26513/30196 [55:01<07:28,  8.21it/s]

 88%|████████▊ | 26515/30196 [55:02<07:14,  8.47it/s]

 88%|████████▊ | 26516/30196 [55:02<07:09,  8.57it/s]

 88%|████████▊ | 26517/30196 [55:02<07:04,  8.67it/s]

 88%|████████▊ | 26519/30196 [55:02<06:37,  9.26it/s]

 88%|████████▊ | 26521/30196 [55:02<05:50, 10.48it/s]

 88%|████████▊ | 26523/30196 [55:02<05:46, 10.61it/s]

 88%|████████▊ | 26525/30196 [55:03<06:08,  9.97it/s]

 88%|████████▊ | 26527/30196 [55:03<05:51, 10.45it/s]

 88%|████████▊ | 26529/30196 [55:03<05:27, 11.20it/s]

 88%|████████▊ | 26531/30196 [55:03<05:09, 11.85it/s]

 88%|████████▊ | 26533/30196 [55:03<05:57, 10.24it/s]

 88%|████████▊ | 26535/30196 [55:04<07:03,  8.65it/s]

 88%|████████▊ | 26536/30196 [55:04<06:56,  8.80it/s]

 88%|████████▊ | 26537/30196 [55:04<06:53,  8.85it/s]

 88%|████████▊ | 26538/30196 [55:04<07:10,  8.50it/s]

 88%|████████▊ | 26539/30196 [55:04<08:48,  6.92it/s]

 88%|████████▊ | 26541/30196 [55:04<07:39,  7.96it/s]

 88%|████████▊ | 26543/30196 [55:05<06:48,  8.94it/s]

 88%|████████▊ | 26545/30196 [55:05<06:21,  9.57it/s]

 88%|████████▊ | 26548/30196 [55:05<05:51, 10.37it/s]

 88%|████████▊ | 26550/30196 [55:05<06:52,  8.83it/s]

 88%|████████▊ | 26551/30196 [55:06<12:10,  4.99it/s]

 88%|████████▊ | 26552/30196 [55:06<11:32,  5.27it/s]

 88%|████████▊ | 26553/30196 [55:06<10:23,  5.84it/s]

 88%|████████▊ | 26554/30196 [55:07<12:27,  4.87it/s]

 88%|████████▊ | 26556/30196 [55:07<10:25,  5.82it/s]

 88%|████████▊ | 26558/30196 [55:07<08:11,  7.40it/s]

 88%|████████▊ | 26560/30196 [55:07<07:51,  7.72it/s]

 88%|████████▊ | 26561/30196 [55:07<08:17,  7.31it/s]

 88%|████████▊ | 26563/30196 [55:07<06:37,  9.14it/s]

 88%|████████▊ | 26566/30196 [55:08<05:41, 10.63it/s]

 88%|████████▊ | 26568/30196 [55:08<05:39, 10.68it/s]

 88%|████████▊ | 26570/30196 [55:08<05:36, 10.78it/s]

 88%|████████▊ | 26572/30196 [55:08<06:14,  9.67it/s]

 88%|████████▊ | 26574/30196 [55:09<07:55,  7.62it/s]

 88%|████████▊ | 26576/30196 [55:09<08:58,  6.72it/s]

 88%|████████▊ | 26577/30196 [55:09<09:11,  6.56it/s]

 88%|████████▊ | 26578/30196 [55:09<09:22,  6.44it/s]

 88%|████████▊ | 26580/30196 [55:10<09:40,  6.22it/s]

 88%|████████▊ | 26581/30196 [55:10<09:23,  6.41it/s]

 88%|████████▊ | 26582/30196 [55:10<09:34,  6.29it/s]

 88%|████████▊ | 26583/30196 [55:10<09:09,  6.58it/s]

 88%|████████▊ | 26584/30196 [55:10<08:24,  7.16it/s]

 88%|████████▊ | 26585/30196 [55:10<08:20,  7.21it/s]

 88%|████████▊ | 26586/30196 [55:11<08:22,  7.18it/s]

 88%|████████▊ | 26587/30196 [55:11<08:52,  6.78it/s]

 88%|████████▊ | 26588/30196 [55:11<08:46,  6.85it/s]

 88%|████████▊ | 26590/30196 [55:11<06:24,  9.38it/s]

 88%|████████▊ | 26592/30196 [55:11<06:54,  8.70it/s]

 88%|████████▊ | 26594/30196 [55:11<05:36, 10.69it/s]

 88%|████████▊ | 26596/30196 [55:12<05:05, 11.77it/s]

 88%|████████▊ | 26598/30196 [55:12<05:41, 10.54it/s]

 88%|████████▊ | 26600/30196 [55:12<06:56,  8.64it/s]

 88%|████████▊ | 26602/30196 [55:12<06:06,  9.82it/s]

 88%|████████▊ | 26604/30196 [55:13<07:30,  7.97it/s]

 88%|████████▊ | 26606/30196 [55:13<06:19,  9.46it/s]

 88%|████████▊ | 26608/30196 [55:13<06:58,  8.58it/s]

 88%|████████▊ | 26610/30196 [55:13<06:15,  9.55it/s]

 88%|████████▊ | 26612/30196 [55:13<07:23,  8.08it/s]

 88%|████████▊ | 26614/30196 [55:14<07:08,  8.36it/s]

 88%|████████▊ | 26615/30196 [55:14<07:26,  8.03it/s]

 88%|████████▊ | 26616/30196 [55:14<07:41,  7.75it/s]

 88%|████████▊ | 26618/30196 [55:14<06:11,  9.63it/s]

 88%|████████▊ | 26620/30196 [55:15<10:19,  5.77it/s]

 88%|████████▊ | 26621/30196 [55:15<10:42,  5.56it/s]

 88%|████████▊ | 26623/30196 [55:15<07:57,  7.49it/s]

 88%|████████▊ | 26625/30196 [55:15<07:26,  8.01it/s]

 88%|████████▊ | 26627/30196 [55:15<07:06,  8.37it/s]

 88%|████████▊ | 26629/30196 [55:16<08:07,  7.32it/s]

 88%|████████▊ | 26630/30196 [55:16<08:27,  7.03it/s]

 88%|████████▊ | 26632/30196 [55:16<06:55,  8.59it/s]

 88%|████████▊ | 26634/30196 [55:16<06:42,  8.86it/s]

 88%|████████▊ | 26636/30196 [55:17<06:43,  8.81it/s]

 88%|████████▊ | 26638/30196 [55:17<06:21,  9.34it/s]

 88%|████████▊ | 26640/30196 [55:17<06:00,  9.87it/s]

 88%|████████▊ | 26642/30196 [55:17<05:50, 10.15it/s]

 88%|████████▊ | 26644/30196 [55:17<06:30,  9.10it/s]

 88%|████████▊ | 26646/30196 [55:18<05:36, 10.53it/s]

 88%|████████▊ | 26648/30196 [55:18<05:36, 10.53it/s]

 88%|████████▊ | 26650/30196 [55:18<04:50, 12.22it/s]

 88%|████████▊ | 26652/30196 [55:18<04:30, 13.11it/s]

 88%|████████▊ | 26654/30196 [55:18<04:31, 13.06it/s]

 88%|████████▊ | 26656/30196 [55:18<05:37, 10.50it/s]

 88%|████████▊ | 26658/30196 [55:19<06:32,  9.01it/s]

 88%|████████▊ | 26660/30196 [55:19<07:03,  8.35it/s]

 88%|████████▊ | 26662/30196 [55:19<05:58,  9.85it/s]

 88%|████████▊ | 26664/30196 [55:19<05:52, 10.01it/s]

 88%|████████▊ | 26666/30196 [55:19<05:58,  9.85it/s]

 88%|████████▊ | 26668/30196 [55:20<06:07,  9.61it/s]

 88%|████████▊ | 26670/30196 [55:20<06:12,  9.46it/s]

 88%|████████▊ | 26671/30196 [55:20<06:34,  8.93it/s]

 88%|████████▊ | 26672/30196 [55:20<07:00,  8.39it/s]

 88%|████████▊ | 26673/30196 [55:20<09:26,  6.22it/s]

 88%|████████▊ | 26675/30196 [55:21<07:24,  7.93it/s]

 88%|████████▊ | 26676/30196 [55:21<07:35,  7.73it/s]

 88%|████████▊ | 26678/30196 [55:21<06:48,  8.61it/s]

 88%|████████▊ | 26679/30196 [55:21<07:06,  8.24it/s]

 88%|████████▊ | 26681/30196 [55:21<05:45, 10.18it/s]

 88%|████████▊ | 26683/30196 [55:21<06:07,  9.55it/s]

 88%|████████▊ | 26685/30196 [55:22<05:33, 10.53it/s]

 88%|████████▊ | 26687/30196 [55:22<06:23,  9.15it/s]

 88%|████████▊ | 26689/30196 [55:22<05:59,  9.74it/s]

 88%|████████▊ | 26691/30196 [55:22<05:34, 10.49it/s]

 88%|████████▊ | 26693/30196 [55:22<06:03,  9.63it/s]

 88%|████████▊ | 26695/30196 [55:23<06:24,  9.10it/s]

 88%|████████▊ | 26697/30196 [55:23<05:28, 10.64it/s]

 88%|████████▊ | 26699/30196 [55:23<06:23,  9.13it/s]

 88%|████████▊ | 26701/30196 [55:23<05:36, 10.40it/s]

 88%|████████▊ | 26703/30196 [55:24<07:17,  7.99it/s]

 88%|████████▊ | 26704/30196 [55:24<07:30,  7.76it/s]

 88%|████████▊ | 26706/30196 [55:24<07:10,  8.11it/s]

 88%|████████▊ | 26707/30196 [55:24<07:43,  7.53it/s]

 88%|████████▊ | 26709/30196 [55:24<07:00,  8.29it/s]

 88%|████████▊ | 26711/30196 [55:25<05:56,  9.77it/s]

 88%|████████▊ | 26713/30196 [55:25<06:14,  9.29it/s]

 88%|████████▊ | 26715/30196 [55:25<06:42,  8.66it/s]

 88%|████████▊ | 26718/30196 [55:25<05:03, 11.45it/s]

 88%|████████▊ | 26720/30196 [55:25<05:07, 11.30it/s]

 88%|████████▊ | 26722/30196 [55:25<04:33, 12.70it/s]

 89%|████████▊ | 26724/30196 [55:26<04:12, 13.75it/s]

 89%|████████▊ | 26726/30196 [55:26<06:37,  8.73it/s]

 89%|████████▊ | 26728/30196 [55:26<06:44,  8.57it/s]

 89%|████████▊ | 26730/30196 [55:27<07:02,  8.21it/s]

 89%|████████▊ | 26732/30196 [55:27<06:06,  9.45it/s]

 89%|████████▊ | 26734/30196 [55:27<05:09, 11.19it/s]

 89%|████████▊ | 26736/30196 [55:27<05:52,  9.82it/s]

 89%|████████▊ | 26738/30196 [55:27<06:52,  8.39it/s]

 89%|████████▊ | 26740/30196 [55:27<05:48,  9.91it/s]

 89%|████████▊ | 26742/30196 [55:28<07:51,  7.32it/s]

 89%|████████▊ | 26744/30196 [55:28<08:31,  6.75it/s]

 89%|████████▊ | 26745/30196 [55:28<08:30,  6.76it/s]

 89%|████████▊ | 26746/30196 [55:29<08:21,  6.88it/s]

 89%|████████▊ | 26748/30196 [55:29<07:33,  7.60it/s]

 89%|████████▊ | 26750/30196 [55:29<07:27,  7.71it/s]

 89%|████████▊ | 26753/30196 [55:29<05:48,  9.89it/s]

 89%|████████▊ | 26755/30196 [55:29<06:07,  9.37it/s]

 89%|████████▊ | 26756/30196 [55:30<06:09,  9.31it/s]

 89%|████████▊ | 26758/30196 [55:30<05:16, 10.85it/s]

 89%|████████▊ | 26760/30196 [55:30<04:48, 11.90it/s]

 89%|████████▊ | 26762/30196 [55:30<05:34, 10.28it/s]

 89%|████████▊ | 26764/30196 [55:30<05:59,  9.53it/s]

 89%|████████▊ | 26766/30196 [55:31<06:52,  8.31it/s]

 89%|████████▊ | 26767/30196 [55:31<07:22,  7.74it/s]

 89%|████████▊ | 26768/30196 [55:31<07:47,  7.33it/s]

 89%|████████▊ | 26769/30196 [55:31<07:51,  7.27it/s]

 89%|████████▊ | 26770/30196 [55:31<07:58,  7.16it/s]

 89%|████████▊ | 26771/30196 [55:31<07:27,  7.66it/s]

 89%|████████▊ | 26772/30196 [55:31<07:59,  7.14it/s]

 89%|████████▊ | 26774/30196 [55:32<07:29,  7.61it/s]

 89%|████████▊ | 26776/30196 [55:32<05:53,  9.66it/s]

 89%|████████▊ | 26778/30196 [55:32<06:09,  9.24it/s]

 89%|████████▊ | 26779/30196 [55:32<06:11,  9.20it/s]

 89%|████████▊ | 26780/30196 [55:32<06:30,  8.74it/s]

 89%|████████▊ | 26781/30196 [55:32<06:26,  8.83it/s]

 89%|████████▊ | 26783/30196 [55:33<06:12,  9.15it/s]

 89%|████████▊ | 26784/30196 [55:33<06:32,  8.69it/s]

 89%|████████▊ | 26785/30196 [55:33<06:45,  8.42it/s]

 89%|████████▊ | 26786/30196 [55:33<06:37,  8.58it/s]

 89%|████████▊ | 26787/30196 [55:33<06:50,  8.30it/s]

 89%|████████▊ | 26788/30196 [55:33<07:09,  7.93it/s]

 89%|████████▊ | 26789/30196 [55:33<06:52,  8.25it/s]

 89%|████████▊ | 26791/30196 [55:34<05:57,  9.52it/s]

 89%|████████▊ | 26793/30196 [55:34<04:47, 11.82it/s]

 89%|████████▊ | 26795/30196 [55:34<06:50,  8.28it/s]

 89%|████████▊ | 26797/30196 [55:35<09:11,  6.16it/s]

 89%|████████▊ | 26798/30196 [55:35<09:52,  5.74it/s]

 89%|████████▉ | 26800/30196 [55:35<08:21,  6.77it/s]

 89%|████████▉ | 26801/30196 [55:35<08:34,  6.60it/s]

 89%|████████▉ | 26802/30196 [55:35<09:32,  5.92it/s]

 89%|████████▉ | 26803/30196 [55:35<09:00,  6.27it/s]

 89%|████████▉ | 26804/30196 [55:36<08:38,  6.54it/s]

 89%|████████▉ | 26805/30196 [55:36<07:57,  7.11it/s]

 89%|████████▉ | 26806/30196 [55:36<07:51,  7.19it/s]

 89%|████████▉ | 26808/30196 [55:36<06:21,  8.87it/s]

 89%|████████▉ | 26809/30196 [55:36<06:15,  9.02it/s]

 89%|████████▉ | 26810/30196 [55:36<06:32,  8.64it/s]

 89%|████████▉ | 26811/30196 [55:36<06:26,  8.75it/s]

 89%|████████▉ | 26813/30196 [55:37<05:37, 10.02it/s]

 89%|████████▉ | 26815/30196 [55:37<05:11, 10.84it/s]

 89%|████████▉ | 26817/30196 [55:37<05:50,  9.64it/s]

 89%|████████▉ | 26819/30196 [55:37<05:46,  9.75it/s]

 89%|████████▉ | 26820/30196 [55:37<07:28,  7.53it/s]

 89%|████████▉ | 26821/30196 [55:38<07:55,  7.10it/s]

 89%|████████▉ | 26822/30196 [55:38<08:17,  6.78it/s]

 89%|████████▉ | 26823/30196 [55:38<08:11,  6.87it/s]

 89%|████████▉ | 26826/30196 [55:38<05:45,  9.74it/s]

 89%|████████▉ | 26827/30196 [55:38<07:00,  8.01it/s]

 89%|████████▉ | 26829/30196 [55:38<05:50,  9.60it/s]

 89%|████████▉ | 26831/30196 [55:39<05:30, 10.19it/s]

 89%|████████▉ | 26833/30196 [55:39<05:42,  9.82it/s]

 89%|████████▉ | 26835/30196 [55:39<05:21, 10.46it/s]

 89%|████████▉ | 26837/30196 [55:39<06:27,  8.66it/s]

 89%|████████▉ | 26839/30196 [55:39<05:29, 10.18it/s]

 89%|████████▉ | 26841/30196 [55:40<06:09,  9.09it/s]

 89%|████████▉ | 26844/30196 [55:40<04:42, 11.88it/s]

 89%|████████▉ | 26846/30196 [55:40<04:54, 11.39it/s]

 89%|████████▉ | 26848/30196 [55:40<05:12, 10.73it/s]

 89%|████████▉ | 26850/30196 [55:40<05:41,  9.79it/s]

 89%|████████▉ | 26852/30196 [55:41<05:12, 10.71it/s]

 89%|████████▉ | 26854/30196 [55:41<06:07,  9.09it/s]

 89%|████████▉ | 26856/30196 [55:41<05:33, 10.02it/s]

 89%|████████▉ | 26858/30196 [55:41<06:44,  8.25it/s]

 89%|████████▉ | 26860/30196 [55:42<06:39,  8.34it/s]

 89%|████████▉ | 26861/30196 [55:42<09:12,  6.04it/s]

 89%|████████▉ | 26862/30196 [55:42<12:20,  4.50it/s]

 89%|████████▉ | 26863/30196 [55:43<11:24,  4.87it/s]

 89%|████████▉ | 26864/30196 [55:43<11:01,  5.04it/s]

 89%|████████▉ | 26866/30196 [55:43<10:02,  5.53it/s]

 89%|████████▉ | 26867/30196 [55:43<09:04,  6.11it/s]

 89%|████████▉ | 26869/30196 [55:43<07:07,  7.79it/s]

 89%|████████▉ | 26871/30196 [55:44<07:18,  7.58it/s]

 89%|████████▉ | 26872/30196 [55:44<07:18,  7.57it/s]

 89%|████████▉ | 26873/30196 [55:44<07:44,  7.15it/s]

 89%|████████▉ | 26874/30196 [55:44<07:45,  7.14it/s]

 89%|████████▉ | 26876/30196 [55:44<07:09,  7.73it/s]

 89%|████████▉ | 26878/30196 [55:45<06:51,  8.07it/s]

 89%|████████▉ | 26880/30196 [55:45<06:11,  8.92it/s]

 89%|████████▉ | 26881/30196 [55:45<06:07,  9.03it/s]

 89%|████████▉ | 26882/30196 [55:45<06:31,  8.47it/s]

 89%|████████▉ | 26883/30196 [55:45<06:24,  8.61it/s]

 89%|████████▉ | 26884/30196 [55:45<06:18,  8.76it/s]

 89%|████████▉ | 26886/30196 [55:45<06:17,  8.76it/s]

 89%|████████▉ | 26887/30196 [55:46<08:04,  6.84it/s]

 89%|████████▉ | 26888/30196 [55:46<08:57,  6.15it/s]

 89%|████████▉ | 26890/30196 [55:46<06:27,  8.53it/s]

 89%|████████▉ | 26892/30196 [55:46<06:53,  8.00it/s]

 89%|████████▉ | 26893/30196 [55:46<07:21,  7.49it/s]

 89%|████████▉ | 26894/30196 [55:47<06:58,  7.88it/s]

 89%|████████▉ | 26896/30196 [55:47<07:27,  7.37it/s]

 89%|████████▉ | 26898/30196 [55:47<06:57,  7.91it/s]

 89%|████████▉ | 26899/30196 [55:47<07:07,  7.72it/s]

 89%|████████▉ | 26900/30196 [55:47<08:20,  6.58it/s]

 89%|████████▉ | 26902/30196 [55:48<07:24,  7.41it/s]

 89%|████████▉ | 26904/30196 [55:48<07:16,  7.54it/s]

 89%|████████▉ | 26905/30196 [55:48<06:57,  7.89it/s]

 89%|████████▉ | 26906/30196 [55:48<07:28,  7.34it/s]

 89%|████████▉ | 26907/30196 [55:48<07:06,  7.71it/s]

 89%|████████▉ | 26909/30196 [55:48<06:11,  8.86it/s]

 89%|████████▉ | 26911/30196 [55:49<05:21, 10.23it/s]

 89%|████████▉ | 26913/30196 [55:49<07:17,  7.50it/s]

 89%|████████▉ | 26914/30196 [55:49<06:59,  7.82it/s]

 89%|████████▉ | 26915/30196 [55:49<06:46,  8.08it/s]

 89%|████████▉ | 26916/30196 [55:49<07:19,  7.46it/s]

 89%|████████▉ | 26918/30196 [55:49<05:51,  9.33it/s]

 89%|████████▉ | 26920/30196 [55:50<05:19, 10.26it/s]

 89%|████████▉ | 26922/30196 [55:50<05:41,  9.58it/s]

 89%|████████▉ | 26924/30196 [55:50<05:32,  9.84it/s]

 89%|████████▉ | 26926/30196 [55:50<05:51,  9.30it/s]

 89%|████████▉ | 26928/30196 [55:51<05:43,  9.51it/s]

 89%|████████▉ | 26930/30196 [55:51<05:25, 10.03it/s]

 89%|████████▉ | 26932/30196 [55:51<06:15,  8.69it/s]

 89%|████████▉ | 26933/30196 [55:51<06:53,  7.90it/s]

 89%|████████▉ | 26935/30196 [55:51<05:59,  9.08it/s]

 89%|████████▉ | 26937/30196 [55:51<05:14, 10.37it/s]

 89%|████████▉ | 26939/30196 [55:52<07:19,  7.41it/s]

 89%|████████▉ | 26940/30196 [55:52<07:04,  7.68it/s]

 89%|████████▉ | 26942/30196 [55:52<06:12,  8.74it/s]

 89%|████████▉ | 26944/30196 [55:52<06:01,  9.01it/s]

 89%|████████▉ | 26945/30196 [55:53<06:43,  8.05it/s]

 89%|████████▉ | 26946/30196 [55:53<06:34,  8.25it/s]

 89%|████████▉ | 26947/30196 [55:53<07:07,  7.60it/s]

 89%|████████▉ | 26948/30196 [55:53<07:15,  7.46it/s]

 89%|████████▉ | 26949/30196 [55:53<07:25,  7.29it/s]

 89%|████████▉ | 26950/30196 [55:53<07:28,  7.24it/s]

 89%|████████▉ | 26951/30196 [55:53<07:24,  7.29it/s]

 89%|████████▉ | 26953/30196 [55:54<05:54,  9.14it/s]

 89%|████████▉ | 26954/30196 [55:54<07:11,  7.51it/s]

 89%|████████▉ | 26956/30196 [55:54<06:18,  8.57it/s]

 89%|████████▉ | 26957/30196 [55:54<08:55,  6.05it/s]

 89%|████████▉ | 26959/30196 [55:55<07:48,  6.91it/s]

 89%|████████▉ | 26961/30196 [55:55<06:10,  8.73it/s]

 89%|████████▉ | 26963/30196 [55:55<06:29,  8.31it/s]

 89%|████████▉ | 26964/30196 [55:55<08:24,  6.41it/s]

 89%|████████▉ | 26966/30196 [55:55<07:57,  6.76it/s]

 89%|████████▉ | 26967/30196 [55:56<07:28,  7.19it/s]

 89%|████████▉ | 26969/30196 [55:56<06:49,  7.88it/s]

 89%|████████▉ | 26970/30196 [55:56<07:24,  7.26it/s]

 89%|████████▉ | 26971/30196 [55:56<07:03,  7.62it/s]

 89%|████████▉ | 26972/30196 [55:56<08:01,  6.69it/s]

 89%|████████▉ | 26973/30196 [55:57<10:16,  5.23it/s]

 89%|████████▉ | 26974/30196 [55:57<09:01,  5.95it/s]

 89%|████████▉ | 26975/30196 [55:57<09:53,  5.43it/s]

 89%|████████▉ | 26977/30196 [55:57<07:42,  6.96it/s]

 89%|████████▉ | 26978/30196 [55:57<08:01,  6.68it/s]

 89%|████████▉ | 26979/30196 [55:57<07:49,  6.85it/s]

 89%|████████▉ | 26980/30196 [55:58<07:51,  6.83it/s]

 89%|████████▉ | 26981/30196 [55:58<08:08,  6.58it/s]

 89%|████████▉ | 26983/30196 [55:58<06:22,  8.40it/s]

 89%|████████▉ | 26984/30196 [55:58<09:59,  5.35it/s]

 89%|████████▉ | 26985/30196 [55:58<09:14,  5.79it/s]

 89%|████████▉ | 26986/30196 [55:59<08:19,  6.43it/s]

 89%|████████▉ | 26988/30196 [55:59<07:42,  6.94it/s]

 89%|████████▉ | 26990/30196 [55:59<06:49,  7.84it/s]

 89%|████████▉ | 26991/30196 [55:59<06:53,  7.75it/s]

 89%|████████▉ | 26992/30196 [55:59<07:50,  6.82it/s]

 89%|████████▉ | 26995/30196 [55:59<05:09, 10.34it/s]

 89%|████████▉ | 26997/30196 [56:00<04:36, 11.57it/s]

 89%|████████▉ | 26999/30196 [56:00<04:37, 11.51it/s]

 89%|████████▉ | 27001/30196 [56:00<04:22, 12.17it/s]

 89%|████████▉ | 27003/30196 [56:00<05:20,  9.95it/s]

 89%|████████▉ | 27005/30196 [56:00<05:57,  8.94it/s]

 89%|████████▉ | 27007/30196 [56:01<05:07, 10.38it/s]

 89%|████████▉ | 27009/30196 [56:01<07:13,  7.36it/s]

 89%|████████▉ | 27010/30196 [56:01<07:10,  7.40it/s]

 89%|████████▉ | 27012/30196 [56:01<06:04,  8.72it/s]

 89%|████████▉ | 27014/30196 [56:02<05:53,  9.01it/s]

 89%|████████▉ | 27016/30196 [56:02<06:44,  7.85it/s]

 89%|████████▉ | 27018/30196 [56:02<05:45,  9.19it/s]

 89%|████████▉ | 27020/30196 [56:02<05:01, 10.52it/s]

 89%|████████▉ | 27022/30196 [56:03<07:19,  7.22it/s]

 89%|████████▉ | 27023/30196 [56:03<07:22,  7.18it/s]

 89%|████████▉ | 27024/30196 [56:03<09:29,  5.57it/s]

 89%|████████▉ | 27025/30196 [56:03<09:53,  5.34it/s]

 90%|████████▉ | 27027/30196 [56:03<08:08,  6.48it/s]

 90%|████████▉ | 27029/30196 [56:04<06:18,  8.36it/s]

 90%|████████▉ | 27031/30196 [56:04<06:05,  8.67it/s]

 90%|████████▉ | 27033/30196 [56:04<06:29,  8.12it/s]

 90%|████████▉ | 27035/30196 [56:04<06:00,  8.76it/s]

 90%|████████▉ | 27037/30196 [56:04<05:21,  9.83it/s]

 90%|████████▉ | 27039/30196 [56:05<05:30,  9.55it/s]

 90%|████████▉ | 27041/30196 [56:05<06:52,  7.64it/s]

 90%|████████▉ | 27043/30196 [56:05<06:38,  7.91it/s]

 90%|████████▉ | 27045/30196 [56:05<06:02,  8.70it/s]

 90%|████████▉ | 27047/30196 [56:06<05:20,  9.83it/s]

 90%|████████▉ | 27049/30196 [56:06<05:56,  8.82it/s]

 90%|████████▉ | 27050/30196 [56:06<06:30,  8.06it/s]

 90%|████████▉ | 27051/30196 [56:06<07:24,  7.07it/s]

 90%|████████▉ | 27052/30196 [56:06<07:19,  7.15it/s]

 90%|████████▉ | 27054/30196 [56:07<06:40,  7.84it/s]

 90%|████████▉ | 27056/30196 [56:07<07:05,  7.37it/s]

 90%|████████▉ | 27058/30196 [56:07<05:53,  8.88it/s]

 90%|████████▉ | 27060/30196 [56:07<05:30,  9.49it/s]

 90%|████████▉ | 27062/30196 [56:08<06:56,  7.52it/s]

 90%|████████▉ | 27063/30196 [56:08<06:57,  7.50it/s]

 90%|████████▉ | 27065/30196 [56:08<06:02,  8.64it/s]

 90%|████████▉ | 27067/30196 [56:08<05:28,  9.54it/s]

 90%|████████▉ | 27069/30196 [56:08<05:45,  9.04it/s]

 90%|████████▉ | 27070/30196 [56:08<06:03,  8.61it/s]

 90%|████████▉ | 27072/30196 [56:09<05:06, 10.18it/s]

 90%|████████▉ | 27074/30196 [56:09<05:40,  9.17it/s]

 90%|████████▉ | 27075/30196 [56:09<06:14,  8.33it/s]

 90%|████████▉ | 27076/30196 [56:09<06:31,  7.96it/s]

 90%|████████▉ | 27079/30196 [56:09<04:37, 11.22it/s]

 90%|████████▉ | 27081/30196 [56:10<04:51, 10.67it/s]

 90%|████████▉ | 27083/30196 [56:10<04:38, 11.19it/s]

 90%|████████▉ | 27085/30196 [56:10<04:24, 11.78it/s]

 90%|████████▉ | 27087/30196 [56:10<04:44, 10.94it/s]

 90%|████████▉ | 27089/30196 [56:10<04:19, 11.95it/s]

 90%|████████▉ | 27091/30196 [56:10<05:32,  9.34it/s]

 90%|████████▉ | 27093/30196 [56:11<06:01,  8.58it/s]

 90%|████████▉ | 27095/30196 [56:11<05:59,  8.62it/s]

 90%|████████▉ | 27097/30196 [56:11<05:42,  9.05it/s]

 90%|████████▉ | 27098/30196 [56:11<06:38,  7.78it/s]

 90%|████████▉ | 27099/30196 [56:12<06:45,  7.63it/s]

 90%|████████▉ | 27101/30196 [56:12<06:48,  7.58it/s]

 90%|████████▉ | 27102/30196 [56:12<06:30,  7.92it/s]

 90%|████████▉ | 27103/30196 [56:12<07:17,  7.07it/s]

 90%|████████▉ | 27104/30196 [56:12<06:48,  7.56it/s]

 90%|████████▉ | 27105/30196 [56:12<07:00,  7.36it/s]

 90%|████████▉ | 27107/30196 [56:13<06:52,  7.48it/s]

 90%|████████▉ | 27108/30196 [56:13<06:53,  7.47it/s]

 90%|████████▉ | 27110/30196 [56:13<06:05,  8.45it/s]

 90%|████████▉ | 27112/30196 [56:13<05:37,  9.15it/s]

 90%|████████▉ | 27113/30196 [56:13<05:37,  9.13it/s]

 90%|████████▉ | 27115/30196 [56:13<05:04, 10.11it/s]

 90%|████████▉ | 27117/30196 [56:14<06:06,  8.40it/s]

 90%|████████▉ | 27118/30196 [56:14<06:16,  8.17it/s]

 90%|████████▉ | 27119/30196 [56:14<06:04,  8.45it/s]

 90%|████████▉ | 27120/30196 [56:14<05:56,  8.62it/s]

 90%|████████▉ | 27122/30196 [56:14<05:36,  9.13it/s]

 90%|████████▉ | 27123/30196 [56:14<06:16,  8.16it/s]

 90%|████████▉ | 27124/30196 [56:15<06:34,  7.78it/s]

 90%|████████▉ | 27126/30196 [56:15<05:54,  8.65it/s]

 90%|████████▉ | 27127/30196 [56:15<06:32,  7.81it/s]

 90%|████████▉ | 27128/30196 [56:15<06:42,  7.62it/s]

 90%|████████▉ | 27129/30196 [56:15<06:45,  7.57it/s]

 90%|████████▉ | 27131/30196 [56:15<06:22,  8.01it/s]

 90%|████████▉ | 27132/30196 [56:16<06:34,  7.76it/s]

 90%|████████▉ | 27134/30196 [56:16<05:41,  8.97it/s]

 90%|████████▉ | 27135/30196 [56:16<08:54,  5.72it/s]

 90%|████████▉ | 27136/30196 [56:16<08:28,  6.01it/s]

 90%|████████▉ | 27137/30196 [56:17<09:35,  5.31it/s]

 90%|████████▉ | 27139/30196 [56:17<07:22,  6.91it/s]

 90%|████████▉ | 27141/30196 [56:17<06:18,  8.08it/s]

 90%|████████▉ | 27142/30196 [56:17<06:28,  7.85it/s]

 90%|████████▉ | 27143/30196 [56:17<08:25,  6.04it/s]

 90%|████████▉ | 27144/30196 [56:17<07:59,  6.37it/s]

 90%|████████▉ | 27146/30196 [56:18<05:52,  8.65it/s]

 90%|████████▉ | 27148/30196 [56:18<06:14,  8.14it/s]

 90%|████████▉ | 27150/30196 [56:18<05:55,  8.57it/s]

 90%|████████▉ | 27151/30196 [56:18<06:13,  8.15it/s]

 90%|████████▉ | 27152/30196 [56:18<06:51,  7.40it/s]

 90%|████████▉ | 27154/30196 [56:19<06:29,  7.81it/s]

 90%|████████▉ | 27155/30196 [56:19<06:39,  7.61it/s]

 90%|████████▉ | 27156/30196 [56:19<07:50,  6.46it/s]

 90%|████████▉ | 27157/30196 [56:19<07:35,  6.68it/s]

 90%|████████▉ | 27158/30196 [56:19<07:32,  6.72it/s]

 90%|████████▉ | 27159/30196 [56:19<07:53,  6.41it/s]

 90%|████████▉ | 27160/30196 [56:20<07:09,  7.06it/s]

 90%|████████▉ | 27162/30196 [56:20<07:23,  6.84it/s]

 90%|████████▉ | 27164/30196 [56:20<06:47,  7.45it/s]

 90%|████████▉ | 27165/30196 [56:20<06:45,  7.48it/s]

 90%|████████▉ | 27166/30196 [56:20<06:24,  7.89it/s]

 90%|████████▉ | 27167/30196 [56:20<06:27,  7.81it/s]

 90%|████████▉ | 27168/30196 [56:21<06:37,  7.61it/s]

 90%|████████▉ | 27169/30196 [56:21<06:51,  7.36it/s]

 90%|████████▉ | 27170/30196 [56:21<06:50,  7.37it/s]

 90%|████████▉ | 27171/30196 [56:21<06:55,  7.28it/s]

 90%|████████▉ | 27174/30196 [56:21<05:16,  9.55it/s]

 90%|████████▉ | 27175/30196 [56:21<05:32,  9.08it/s]

 90%|█████████ | 27177/30196 [56:22<05:09,  9.76it/s]

 90%|█████████ | 27179/30196 [56:22<04:51, 10.36it/s]

 90%|█████████ | 27181/30196 [56:22<04:41, 10.71it/s]

 90%|█████████ | 27183/30196 [56:22<05:05,  9.87it/s]

 90%|█████████ | 27184/30196 [56:22<06:16,  8.00it/s]

 90%|█████████ | 27185/30196 [56:23<06:44,  7.44it/s]

 90%|█████████ | 27186/30196 [56:23<06:24,  7.83it/s]

 90%|█████████ | 27188/30196 [56:23<05:08,  9.74it/s]

 90%|█████████ | 27190/30196 [56:23<05:39,  8.84it/s]

 90%|█████████ | 27191/30196 [56:23<08:17,  6.04it/s]

 90%|█████████ | 27192/30196 [56:24<08:00,  6.25it/s]

 90%|█████████ | 27193/30196 [56:24<07:38,  6.55it/s]

 90%|█████████ | 27195/30196 [56:24<06:48,  7.35it/s]

 90%|█████████ | 27198/30196 [56:24<04:43, 10.56it/s]

 90%|█████████ | 27200/30196 [56:24<04:04, 12.26it/s]

 90%|█████████ | 27202/30196 [56:24<04:35, 10.85it/s]

 90%|█████████ | 27204/30196 [56:25<05:36,  8.90it/s]

 90%|█████████ | 27206/30196 [56:25<05:08,  9.69it/s]

 90%|█████████ | 27208/30196 [56:25<05:56,  8.39it/s]

 90%|█████████ | 27210/30196 [56:26<07:33,  6.58it/s]

 90%|█████████ | 27212/30196 [56:26<06:15,  7.94it/s]

 90%|█████████ | 27214/30196 [56:26<06:04,  8.19it/s]

 90%|█████████ | 27215/30196 [56:26<06:26,  7.71it/s]

 90%|█████████ | 27217/30196 [56:26<06:00,  8.26it/s]

 90%|█████████ | 27218/30196 [56:27<06:25,  7.72it/s]

 90%|█████████ | 27219/30196 [56:27<06:49,  7.28it/s]

 90%|█████████ | 27221/30196 [56:27<05:19,  9.32it/s]

 90%|█████████ | 27223/30196 [56:27<06:29,  7.63it/s]

 90%|█████████ | 27225/30196 [56:27<05:39,  8.75it/s]

 90%|█████████ | 27227/30196 [56:27<05:05,  9.71it/s]

 90%|█████████ | 27229/30196 [56:28<05:55,  8.34it/s]

 90%|█████████ | 27231/30196 [56:28<05:22,  9.19it/s]

 90%|█████████ | 27233/30196 [56:28<05:52,  8.42it/s]

 90%|█████████ | 27234/30196 [56:28<05:45,  8.57it/s]

 90%|█████████ | 27236/30196 [56:29<06:22,  7.75it/s]

 90%|█████████ | 27238/30196 [56:29<06:52,  7.18it/s]

 90%|█████████ | 27240/30196 [56:29<05:58,  8.24it/s]

 90%|█████████ | 27242/30196 [56:29<05:16,  9.34it/s]

 90%|█████████ | 27244/30196 [56:30<05:17,  9.31it/s]

 90%|█████████ | 27245/30196 [56:30<05:31,  8.90it/s]

 90%|█████████ | 27247/30196 [56:30<04:29, 10.95it/s]

 90%|█████████ | 27249/30196 [56:30<06:20,  7.74it/s]

 90%|█████████ | 27251/30196 [56:30<06:19,  7.76it/s]

 90%|█████████ | 27252/30196 [56:31<06:25,  7.63it/s]

 90%|█████████ | 27254/30196 [56:31<05:13,  9.38it/s]

 90%|█████████ | 27256/30196 [56:31<05:45,  8.52it/s]

 90%|█████████ | 27257/30196 [56:31<05:37,  8.72it/s]

 90%|█████████ | 27258/30196 [56:31<05:47,  8.46it/s]

 90%|█████████ | 27259/30196 [56:31<06:03,  8.08it/s]

 90%|█████████ | 27260/30196 [56:31<05:53,  8.31it/s]

 90%|█████████ | 27262/30196 [56:32<04:46, 10.23it/s]

 90%|█████████ | 27264/30196 [56:32<04:56,  9.90it/s]

 90%|█████████ | 27266/30196 [56:32<04:52, 10.02it/s]

 90%|█████████ | 27268/30196 [56:33<07:47,  6.27it/s]

 90%|█████████ | 27270/30196 [56:33<06:19,  7.71it/s]

 90%|█████████ | 27272/30196 [56:33<05:41,  8.57it/s]

 90%|█████████ | 27274/30196 [56:33<06:04,  8.02it/s]

 90%|█████████ | 27276/30196 [56:33<05:51,  8.32it/s]

 90%|█████████ | 27277/30196 [56:34<06:17,  7.73it/s]

 90%|█████████ | 27278/30196 [56:34<06:21,  7.65it/s]

 90%|█████████ | 27280/30196 [56:34<06:38,  7.31it/s]

 90%|█████████ | 27281/30196 [56:34<06:41,  7.27it/s]

 90%|█████████ | 27283/30196 [56:34<06:45,  7.19it/s]

 90%|█████████ | 27284/30196 [56:35<06:48,  7.13it/s]

 90%|█████████ | 27285/30196 [56:35<07:07,  6.82it/s]

 90%|█████████ | 27287/30196 [56:35<06:30,  7.46it/s]

 90%|█████████ | 27289/30196 [56:35<05:34,  8.70it/s]

 90%|█████████ | 27290/30196 [56:35<06:06,  7.94it/s]

 90%|█████████ | 27292/30196 [56:36<06:03,  7.99it/s]

 90%|█████████ | 27294/30196 [56:36<05:27,  8.85it/s]

 90%|█████████ | 27295/30196 [56:36<05:40,  8.51it/s]

 90%|█████████ | 27296/30196 [56:36<05:55,  8.15it/s]

 90%|█████████ | 27297/30196 [56:36<06:01,  8.03it/s]

 90%|█████████ | 27298/30196 [56:36<06:34,  7.34it/s]

 90%|█████████ | 27300/30196 [56:36<05:19,  9.05it/s]

 90%|█████████ | 27302/30196 [56:37<04:25, 10.90it/s]

 90%|█████████ | 27304/30196 [56:37<05:33,  8.68it/s]

 90%|█████████ | 27305/30196 [56:37<06:07,  7.87it/s]

 90%|█████████ | 27306/30196 [56:37<06:12,  7.77it/s]

 90%|█████████ | 27308/30196 [56:37<05:00,  9.60it/s]

 90%|█████████ | 27310/30196 [56:38<05:34,  8.63it/s]

 90%|█████████ | 27312/30196 [56:38<05:51,  8.20it/s]

 90%|█████████ | 27314/30196 [56:38<04:45, 10.11it/s]

 90%|█████████ | 27316/30196 [56:38<06:07,  7.83it/s]

 90%|█████████ | 27318/30196 [56:39<05:41,  8.44it/s]

 90%|█████████ | 27320/30196 [56:39<04:54,  9.75it/s]

 90%|█████████ | 27322/30196 [56:39<04:39, 10.27it/s]

 90%|█████████ | 27324/30196 [56:39<04:49,  9.93it/s]

 90%|█████████ | 27326/30196 [56:39<04:50,  9.86it/s]

 91%|█████████ | 27328/30196 [56:40<06:45,  7.07it/s]

 91%|█████████ | 27330/30196 [56:40<06:37,  7.22it/s]

 91%|█████████ | 27331/30196 [56:40<06:36,  7.22it/s]

 91%|█████████ | 27333/30196 [56:40<05:56,  8.03it/s]

 91%|█████████ | 27334/30196 [56:40<05:45,  8.29it/s]

 91%|█████████ | 27335/30196 [56:41<05:35,  8.53it/s]

 91%|█████████ | 27336/30196 [56:41<05:54,  8.06it/s]

 91%|█████████ | 27338/30196 [56:41<07:17,  6.53it/s]

 91%|█████████ | 27340/30196 [56:41<06:37,  7.18it/s]

 91%|█████████ | 27342/30196 [56:41<05:41,  8.35it/s]

 91%|█████████ | 27343/30196 [56:42<05:50,  8.13it/s]

 91%|█████████ | 27344/30196 [56:42<06:45,  7.04it/s]

 91%|█████████ | 27345/30196 [56:42<06:23,  7.44it/s]

 91%|█████████ | 27346/30196 [56:42<06:48,  6.98it/s]

 91%|█████████ | 27347/30196 [56:42<06:22,  7.44it/s]

 91%|█████████ | 27348/30196 [56:42<07:19,  6.47it/s]

 91%|█████████ | 27349/30196 [56:43<07:08,  6.64it/s]

 91%|█████████ | 27350/30196 [56:43<06:31,  7.27it/s]

 91%|█████████ | 27352/30196 [56:43<04:52,  9.71it/s]

 91%|█████████ | 27354/30196 [56:43<05:44,  8.25it/s]

 91%|█████████ | 27356/30196 [56:43<05:04,  9.34it/s]

 91%|█████████ | 27358/30196 [56:43<05:04,  9.33it/s]

 91%|█████████ | 27359/30196 [56:44<05:40,  8.32it/s]

 91%|█████████ | 27361/30196 [56:44<04:47,  9.87it/s]

 91%|█████████ | 27363/30196 [56:44<04:42, 10.03it/s]

 91%|█████████ | 27365/30196 [56:44<04:43, 10.00it/s]

 91%|█████████ | 27367/30196 [56:44<04:24, 10.70it/s]

 91%|█████████ | 27369/30196 [56:45<04:33, 10.34it/s]

 91%|█████████ | 27371/30196 [56:45<05:41,  8.27it/s]

 91%|█████████ | 27372/30196 [56:45<06:05,  7.72it/s]

 91%|█████████ | 27374/30196 [56:45<05:10,  9.10it/s]

 91%|█████████ | 27376/30196 [56:45<05:01,  9.35it/s]

 91%|█████████ | 27377/30196 [56:46<05:14,  8.96it/s]

 91%|█████████ | 27378/30196 [56:46<06:38,  7.08it/s]

 91%|█████████ | 27379/30196 [56:46<07:03,  6.64it/s]

 91%|█████████ | 27380/30196 [56:46<06:52,  6.82it/s]

 91%|█████████ | 27381/30196 [56:46<07:38,  6.14it/s]

 91%|█████████ | 27382/30196 [56:46<07:41,  6.10it/s]

 91%|█████████ | 27384/30196 [56:47<09:16,  5.05it/s]

 91%|█████████ | 27385/30196 [56:47<09:36,  4.88it/s]

 91%|█████████ | 27387/30196 [56:47<07:48,  5.99it/s]

 91%|█████████ | 27389/30196 [56:48<06:17,  7.44it/s]

 91%|█████████ | 27390/30196 [56:48<06:02,  7.74it/s]

 91%|█████████ | 27392/30196 [56:48<06:04,  7.69it/s]

 91%|█████████ | 27394/30196 [56:48<04:56,  9.44it/s]

 91%|█████████ | 27396/30196 [56:48<04:05, 11.43it/s]

 91%|█████████ | 27398/30196 [56:48<04:50,  9.63it/s]

 91%|█████████ | 27400/30196 [56:49<05:09,  9.03it/s]

 91%|█████████ | 27402/30196 [56:49<05:41,  8.19it/s]

 91%|█████████ | 27403/30196 [56:49<06:06,  7.62it/s]

 91%|█████████ | 27405/30196 [56:49<05:41,  8.18it/s]

 91%|█████████ | 27407/30196 [56:50<05:35,  8.30it/s]

 91%|█████████ | 27408/30196 [56:50<06:04,  7.66it/s]

 91%|█████████ | 27409/30196 [56:50<06:06,  7.61it/s]

 91%|█████████ | 27410/30196 [56:50<05:52,  7.90it/s]

 91%|█████████ | 27411/30196 [56:50<08:43,  5.32it/s]

 91%|█████████ | 27413/30196 [56:50<06:08,  7.56it/s]

 91%|█████████ | 27415/30196 [56:51<06:15,  7.41it/s]

 91%|█████████ | 27417/30196 [56:51<05:22,  8.62it/s]

 91%|█████████ | 27419/30196 [56:51<04:57,  9.34it/s]

 91%|█████████ | 27421/30196 [56:51<05:29,  8.42it/s]

 91%|█████████ | 27422/30196 [56:52<05:54,  7.82it/s]

 91%|█████████ | 27423/30196 [56:52<05:44,  8.05it/s]

 91%|█████████ | 27425/30196 [56:52<04:41,  9.85it/s]

 91%|█████████ | 27427/30196 [56:52<05:13,  8.84it/s]

 91%|█████████ | 27429/30196 [56:52<05:47,  7.96it/s]

 91%|█████████ | 27430/30196 [56:52<05:38,  8.17it/s]

 91%|█████████ | 27432/30196 [56:53<05:30,  8.36it/s]

 91%|█████████ | 27433/30196 [56:53<05:22,  8.56it/s]

 91%|█████████ | 27434/30196 [56:53<05:54,  7.79it/s]

 91%|█████████ | 27436/30196 [56:53<05:30,  8.34it/s]

 91%|█████████ | 27438/30196 [56:53<04:53,  9.40it/s]

 91%|█████████ | 27440/30196 [56:54<05:47,  7.93it/s]

 91%|█████████ | 27441/30196 [56:54<05:54,  7.76it/s]

 91%|█████████ | 27443/30196 [56:54<05:33,  8.26it/s]

 91%|█████████ | 27445/30196 [56:54<04:35, 10.00it/s]

 91%|█████████ | 27447/30196 [56:54<04:57,  9.24it/s]

 91%|█████████ | 27449/30196 [56:54<04:06, 11.13it/s]

 91%|█████████ | 27451/30196 [56:55<04:39,  9.81it/s]

 91%|█████████ | 27453/30196 [56:55<04:49,  9.47it/s]

 91%|█████████ | 27455/30196 [56:56<12:07,  3.77it/s]

 91%|█████████ | 27457/30196 [56:56<09:18,  4.90it/s]

 91%|█████████ | 27459/30196 [56:57<07:29,  6.10it/s]

 91%|█████████ | 27461/30196 [56:57<07:10,  6.36it/s]

 91%|█████████ | 27463/30196 [56:57<06:29,  7.01it/s]

 91%|█████████ | 27465/30196 [56:57<05:25,  8.38it/s]

 91%|█████████ | 27467/30196 [56:57<04:41,  9.71it/s]

 91%|█████████ | 27469/30196 [56:58<04:56,  9.20it/s]

 91%|█████████ | 27471/30196 [56:58<05:04,  8.96it/s]

 91%|█████████ | 27473/30196 [56:58<05:14,  8.65it/s]

 91%|█████████ | 27475/30196 [56:58<05:06,  8.87it/s]

 91%|█████████ | 27476/30196 [56:58<05:34,  8.14it/s]

 91%|█████████ | 27477/30196 [56:58<05:24,  8.38it/s]

 91%|█████████ | 27478/30196 [56:59<05:52,  7.72it/s]

 91%|█████████ | 27479/30196 [56:59<06:15,  7.23it/s]

 91%|█████████ | 27480/30196 [56:59<06:34,  6.88it/s]

 91%|█████████ | 27481/30196 [56:59<07:21,  6.15it/s]

 91%|█████████ | 27483/30196 [56:59<06:07,  7.39it/s]

 91%|█████████ | 27484/30196 [57:00<06:10,  7.32it/s]

 91%|█████████ | 27485/30196 [57:00<07:35,  5.95it/s]

 91%|█████████ | 27487/30196 [57:00<06:50,  6.61it/s]

 91%|█████████ | 27489/30196 [57:00<05:37,  8.03it/s]

 91%|█████████ | 27491/30196 [57:00<04:47,  9.42it/s]

 91%|█████████ | 27493/30196 [57:01<04:23, 10.27it/s]

 91%|█████████ | 27495/30196 [57:01<05:02,  8.92it/s]

 91%|█████████ | 27496/30196 [57:01<05:01,  8.94it/s]

 91%|█████████ | 27497/30196 [57:01<05:39,  7.96it/s]

 91%|█████████ | 27499/30196 [57:01<04:45,  9.45it/s]

 91%|█████████ | 27500/30196 [57:01<05:45,  7.80it/s]

 91%|█████████ | 27502/30196 [57:02<05:15,  8.53it/s]

 91%|█████████ | 27504/30196 [57:02<05:46,  7.77it/s]

 91%|█████████ | 27505/30196 [57:02<06:05,  7.36it/s]

 91%|█████████ | 27507/30196 [57:02<05:20,  8.39it/s]

 91%|█████████ | 27508/30196 [57:02<05:15,  8.53it/s]

 91%|█████████ | 27510/30196 [57:03<04:31,  9.90it/s]

 91%|█████████ | 27512/30196 [57:03<05:55,  7.54it/s]

 91%|█████████ | 27513/30196 [57:03<05:58,  7.48it/s]

 91%|█████████ | 27515/30196 [57:03<04:52,  9.15it/s]

 91%|█████████ | 27517/30196 [57:03<04:19, 10.31it/s]

 91%|█████████ | 27519/30196 [57:03<03:54, 11.43it/s]

 91%|█████████ | 27521/30196 [57:04<04:14, 10.52it/s]

 91%|█████████ | 27523/30196 [57:04<05:29,  8.12it/s]

 91%|█████████ | 27525/30196 [57:04<04:35,  9.68it/s]

 91%|█████████ | 27527/30196 [57:04<04:25, 10.06it/s]

 91%|█████████ | 27529/30196 [57:05<06:00,  7.39it/s]

 91%|█████████ | 27531/30196 [57:05<05:21,  8.30it/s]

 91%|█████████ | 27533/30196 [57:05<04:57,  8.94it/s]

 91%|█████████ | 27535/30196 [57:05<05:30,  8.05it/s]

 91%|█████████ | 27536/30196 [57:06<06:09,  7.20it/s]

 91%|█████████ | 27537/30196 [57:06<05:53,  7.52it/s]

 91%|█████████ | 27538/30196 [57:06<06:21,  6.97it/s]

 91%|█████████ | 27539/30196 [57:06<06:00,  7.38it/s]

 91%|█████████ | 27540/30196 [57:06<06:47,  6.51it/s]

 91%|█████████ | 27542/30196 [57:06<05:15,  8.42it/s]

 91%|█████████ | 27543/30196 [57:07<05:31,  7.99it/s]

 91%|█████████ | 27544/30196 [57:07<05:18,  8.33it/s]

 91%|█████████ | 27547/30196 [57:07<03:47, 11.66it/s]

 91%|█████████ | 27549/30196 [57:07<03:16, 13.48it/s]

 91%|█████████ | 27551/30196 [57:07<03:17, 13.38it/s]

 91%|█████████ | 27553/30196 [57:07<03:49, 11.53it/s]

 91%|█████████▏| 27555/30196 [57:08<05:35,  7.87it/s]

 91%|█████████▏| 27557/30196 [57:08<05:30,  7.99it/s]

 91%|█████████▏| 27558/30196 [57:08<05:51,  7.51it/s]

 91%|█████████▏| 27559/30196 [57:08<05:38,  7.79it/s]

 91%|█████████▏| 27560/30196 [57:08<06:08,  7.16it/s]

 91%|█████████▏| 27561/30196 [57:09<05:45,  7.63it/s]

 91%|█████████▏| 27562/30196 [57:09<05:30,  7.97it/s]

 91%|█████████▏| 27564/30196 [57:09<05:06,  8.58it/s]

 91%|█████████▏| 27566/30196 [57:09<04:07, 10.64it/s]

 91%|█████████▏| 27568/30196 [57:09<04:02, 10.85it/s]

 91%|█████████▏| 27570/30196 [57:09<04:28,  9.79it/s]

 91%|█████████▏| 27572/30196 [57:10<03:58, 10.98it/s]

 91%|█████████▏| 27574/30196 [57:10<04:22,  9.99it/s]

 91%|█████████▏| 27576/30196 [57:10<04:21, 10.01it/s]

 91%|█████████▏| 27578/30196 [57:10<04:56,  8.83it/s]

 91%|█████████▏| 27580/30196 [57:10<04:33,  9.58it/s]

 91%|█████████▏| 27582/30196 [57:11<04:02, 10.79it/s]

 91%|█████████▏| 27584/30196 [57:11<04:19, 10.06it/s]

 91%|█████████▏| 27586/30196 [57:11<05:47,  7.52it/s]

 91%|█████████▏| 27588/30196 [57:11<05:12,  8.35it/s]

 91%|█████████▏| 27590/30196 [57:12<04:47,  9.07it/s]

 91%|█████████▏| 27592/30196 [57:12<05:21,  8.10it/s]

 91%|█████████▏| 27593/30196 [57:12<05:12,  8.33it/s]

 91%|█████████▏| 27594/30196 [57:12<05:04,  8.55it/s]

 91%|█████████▏| 27595/30196 [57:12<06:09,  7.04it/s]

 91%|█████████▏| 27596/30196 [57:12<06:02,  7.18it/s]

 91%|█████████▏| 27597/30196 [57:13<05:55,  7.31it/s]

 91%|█████████▏| 27598/30196 [57:13<06:02,  7.16it/s]

 91%|█████████▏| 27600/30196 [57:13<05:05,  8.49it/s]

 91%|█████████▏| 27602/30196 [57:13<05:16,  8.19it/s]

 91%|█████████▏| 27603/30196 [57:13<05:23,  8.02it/s]

 91%|█████████▏| 27605/30196 [57:13<04:38,  9.29it/s]

 91%|█████████▏| 27606/30196 [57:14<05:34,  7.75it/s]

 91%|█████████▏| 27607/30196 [57:14<05:19,  8.11it/s]

 91%|█████████▏| 27609/30196 [57:14<04:52,  8.84it/s]

 91%|█████████▏| 27611/30196 [57:14<04:48,  8.96it/s]

 91%|█████████▏| 27612/30196 [57:14<05:23,  7.98it/s]

 91%|█████████▏| 27613/30196 [57:15<05:34,  7.72it/s]

 91%|█████████▏| 27614/30196 [57:15<06:05,  7.06it/s]

 91%|█████████▏| 27615/30196 [57:16<15:16,  2.82it/s]

 91%|█████████▏| 27616/30196 [57:16<12:40,  3.39it/s]

 91%|█████████▏| 27617/30196 [57:16<10:44,  4.00it/s]

 91%|█████████▏| 27618/30196 [57:16<09:42,  4.43it/s]

 91%|█████████▏| 27619/30196 [57:16<09:31,  4.51it/s]

 91%|█████████▏| 27621/30196 [57:16<06:45,  6.34it/s]

 91%|█████████▏| 27623/30196 [57:17<05:50,  7.34it/s]

 91%|█████████▏| 27624/30196 [57:17<08:41,  4.93it/s]

 91%|█████████▏| 27625/30196 [57:17<08:12,  5.22it/s]

 91%|█████████▏| 27626/30196 [57:17<07:56,  5.40it/s]

 91%|█████████▏| 27627/30196 [57:18<07:24,  5.77it/s]

 91%|█████████▏| 27628/30196 [57:18<06:36,  6.47it/s]

 92%|█████████▏| 27630/30196 [57:18<04:41,  9.12it/s]

 92%|█████████▏| 27632/30196 [57:18<03:49, 11.15it/s]

 92%|█████████▏| 27634/30196 [57:18<04:22,  9.77it/s]

 92%|█████████▏| 27636/30196 [57:18<04:27,  9.56it/s]

 92%|█████████▏| 27638/30196 [57:19<04:02, 10.55it/s]

 92%|█████████▏| 27640/30196 [57:19<04:55,  8.64it/s]

 92%|█████████▏| 27642/30196 [57:19<04:35,  9.28it/s]

 92%|█████████▏| 27644/30196 [57:19<04:32,  9.35it/s]

 92%|█████████▏| 27646/30196 [57:19<04:18,  9.85it/s]

 92%|█████████▏| 27648/30196 [57:20<04:24,  9.65it/s]

 92%|█████████▏| 27650/30196 [57:20<04:21,  9.73it/s]

 92%|█████████▏| 27652/30196 [57:20<04:18,  9.84it/s]

 92%|█████████▏| 27654/30196 [57:20<04:27,  9.50it/s]

 92%|█████████▏| 27655/30196 [57:20<04:27,  9.49it/s]

 92%|█████████▏| 27656/30196 [57:21<04:59,  8.47it/s]

 92%|█████████▏| 27659/30196 [57:21<03:40, 11.50it/s]

 92%|█████████▏| 27661/30196 [57:21<03:50, 10.99it/s]

 92%|█████████▏| 27663/30196 [57:21<04:07, 10.22it/s]

 92%|█████████▏| 27665/30196 [57:21<04:54,  8.59it/s]

 92%|█████████▏| 27667/30196 [57:22<04:27,  9.46it/s]

 92%|█████████▏| 27669/30196 [57:22<04:17,  9.81it/s]

 92%|█████████▏| 27671/30196 [57:22<06:00,  7.01it/s]

 92%|█████████▏| 27674/30196 [57:22<04:36,  9.11it/s]

 92%|█████████▏| 27676/30196 [57:23<04:50,  8.68it/s]

 92%|█████████▏| 27678/30196 [57:23<04:23,  9.56it/s]

 92%|█████████▏| 27680/30196 [57:23<04:30,  9.30it/s]

 92%|█████████▏| 27682/30196 [57:23<04:37,  9.07it/s]

 92%|█████████▏| 27683/30196 [57:23<04:45,  8.80it/s]

 92%|█████████▏| 27685/30196 [57:24<04:45,  8.81it/s]

 92%|█████████▏| 27686/30196 [57:24<05:16,  7.94it/s]

 92%|█████████▏| 27687/30196 [57:24<05:18,  7.88it/s]

 92%|█████████▏| 27688/30196 [57:24<07:34,  5.51it/s]

 92%|█████████▏| 27690/30196 [57:25<06:12,  6.73it/s]

 92%|█████████▏| 27692/30196 [57:25<05:18,  7.87it/s]

 92%|█████████▏| 27694/30196 [57:25<04:27,  9.35it/s]

 92%|█████████▏| 27696/30196 [57:25<05:26,  7.66it/s]

 92%|█████████▏| 27698/30196 [57:25<04:40,  8.90it/s]

 92%|█████████▏| 27700/30196 [57:26<04:32,  9.17it/s]

 92%|█████████▏| 27702/30196 [57:26<04:42,  8.83it/s]

 92%|█████████▏| 27704/30196 [57:26<03:56, 10.56it/s]

 92%|█████████▏| 27706/30196 [57:26<04:57,  8.37it/s]

 92%|█████████▏| 27708/30196 [57:26<04:57,  8.38it/s]

 92%|█████████▏| 27710/30196 [57:27<04:33,  9.10it/s]

 92%|█████████▏| 27712/30196 [57:27<04:41,  8.82it/s]

 92%|█████████▏| 27714/30196 [57:27<04:44,  8.71it/s]

 92%|█████████▏| 27715/30196 [57:27<04:42,  8.79it/s]

 92%|█████████▏| 27716/30196 [57:27<05:03,  8.18it/s]

 92%|█████████▏| 27718/30196 [57:28<03:59, 10.37it/s]

 92%|█████████▏| 27720/30196 [57:28<04:34,  9.02it/s]

 92%|█████████▏| 27722/30196 [57:28<06:03,  6.80it/s]

 92%|█████████▏| 27724/30196 [57:28<05:37,  7.32it/s]

 92%|█████████▏| 27726/30196 [57:29<04:49,  8.52it/s]

 92%|█████████▏| 27729/30196 [57:29<03:47, 10.83it/s]

 92%|█████████▏| 27732/30196 [57:29<03:30, 11.69it/s]

 92%|█████████▏| 27734/30196 [57:29<03:11, 12.86it/s]

 92%|█████████▏| 27736/30196 [57:29<03:22, 12.13it/s]

 92%|█████████▏| 27738/30196 [57:29<03:11, 12.86it/s]

 92%|█████████▏| 27740/30196 [57:30<03:32, 11.58it/s]

 92%|█████████▏| 27742/30196 [57:30<04:20,  9.41it/s]

 92%|█████████▏| 27744/30196 [57:30<04:58,  8.20it/s]

 92%|█████████▏| 27746/30196 [57:30<04:18,  9.48it/s]

 92%|█████████▏| 27748/30196 [57:31<04:37,  8.81it/s]

 92%|█████████▏| 27750/30196 [57:31<05:28,  7.45it/s]

 92%|█████████▏| 27751/30196 [57:31<05:41,  7.15it/s]

 92%|█████████▏| 27753/30196 [57:31<04:40,  8.70it/s]

 92%|█████████▏| 27755/30196 [57:31<04:09,  9.79it/s]

 92%|█████████▏| 27757/30196 [57:32<04:22,  9.28it/s]

 92%|█████████▏| 27759/30196 [57:32<04:24,  9.20it/s]

 92%|█████████▏| 27760/30196 [57:32<04:24,  9.23it/s]

 92%|█████████▏| 27761/30196 [57:32<06:05,  6.67it/s]

 92%|█████████▏| 27763/30196 [57:33<04:56,  8.20it/s]

 92%|█████████▏| 27765/30196 [57:33<04:03,  9.97it/s]

 92%|█████████▏| 27767/30196 [57:33<03:47, 10.68it/s]

 92%|█████████▏| 27769/30196 [57:33<04:00, 10.11it/s]

 92%|█████████▏| 27771/30196 [57:33<03:45, 10.76it/s]

 92%|█████████▏| 27773/30196 [57:34<04:50,  8.33it/s]

 92%|█████████▏| 27774/30196 [57:34<05:12,  7.75it/s]

 92%|█████████▏| 27775/30196 [57:34<05:02,  8.00it/s]

 92%|█████████▏| 27776/30196 [57:34<04:51,  8.31it/s]

 92%|█████████▏| 27778/30196 [57:34<03:47, 10.65it/s]

 92%|█████████▏| 27780/30196 [57:34<03:40, 10.94it/s]

 92%|█████████▏| 27782/30196 [57:34<04:06,  9.81it/s]

 92%|█████████▏| 27784/30196 [57:35<04:35,  8.75it/s]

 92%|█████████▏| 27786/30196 [57:35<04:09,  9.67it/s]

 92%|█████████▏| 27788/30196 [57:35<04:00,  9.99it/s]

 92%|█████████▏| 27790/30196 [57:35<03:55, 10.21it/s]

 92%|█████████▏| 27792/30196 [57:36<04:39,  8.61it/s]

 92%|█████████▏| 27793/30196 [57:36<04:50,  8.28it/s]

 92%|█████████▏| 27794/30196 [57:36<05:31,  7.25it/s]

 92%|█████████▏| 27795/30196 [57:36<05:29,  7.28it/s]

 92%|█████████▏| 27797/30196 [57:36<04:28,  8.95it/s]

 92%|█████████▏| 27798/30196 [57:36<04:58,  8.03it/s]

 92%|█████████▏| 27800/30196 [57:37<04:29,  8.91it/s]

 92%|█████████▏| 27801/30196 [57:37<05:30,  7.25it/s]

 92%|█████████▏| 27802/30196 [57:37<06:08,  6.50it/s]

 92%|█████████▏| 27803/30196 [57:37<06:22,  6.26it/s]

 92%|█████████▏| 27804/30196 [57:37<05:47,  6.88it/s]

 92%|█████████▏| 27805/30196 [57:37<05:37,  7.09it/s]

 92%|█████████▏| 27807/30196 [57:38<04:52,  8.16it/s]

 92%|█████████▏| 27809/30196 [57:38<04:00,  9.94it/s]

 92%|█████████▏| 27811/30196 [57:38<03:17, 12.09it/s]

 92%|█████████▏| 27813/30196 [57:38<03:29, 11.39it/s]

 92%|█████████▏| 27815/30196 [57:38<03:19, 11.94it/s]

 92%|█████████▏| 27817/30196 [57:38<03:39, 10.84it/s]

 92%|█████████▏| 27819/30196 [57:39<04:42,  8.42it/s]

 92%|█████████▏| 27821/30196 [57:39<04:31,  8.74it/s]

 92%|█████████▏| 27822/30196 [57:39<04:39,  8.48it/s]

 92%|█████████▏| 27823/30196 [57:39<04:48,  8.23it/s]

 92%|█████████▏| 27824/30196 [57:39<04:55,  8.02it/s]

 92%|█████████▏| 27826/30196 [57:40<04:33,  8.67it/s]

 92%|█████████▏| 27827/30196 [57:40<04:46,  8.27it/s]

 92%|█████████▏| 27829/30196 [57:40<04:52,  8.10it/s]

 92%|█████████▏| 27830/30196 [57:40<04:55,  8.00it/s]

 92%|█████████▏| 27831/30196 [57:40<05:40,  6.95it/s]

 92%|█████████▏| 27833/30196 [57:41<05:55,  6.64it/s]

 92%|█████████▏| 27834/30196 [57:41<05:33,  7.08it/s]

 92%|█████████▏| 27835/30196 [57:41<05:26,  7.22it/s]

 92%|█████████▏| 27837/30196 [57:41<05:21,  7.34it/s]

 92%|█████████▏| 27838/30196 [57:41<05:21,  7.35it/s]

 92%|█████████▏| 27839/30196 [57:41<05:23,  7.29it/s]

 92%|█████████▏| 27840/30196 [57:42<05:25,  7.23it/s]

 92%|█████████▏| 27842/30196 [57:42<04:22,  8.95it/s]

 92%|█████████▏| 27844/30196 [57:42<03:35, 10.91it/s]

 92%|█████████▏| 27846/30196 [57:42<04:05,  9.58it/s]

 92%|█████████▏| 27848/30196 [57:42<04:09,  9.41it/s]

 92%|█████████▏| 27849/30196 [57:43<05:38,  6.93it/s]

 92%|█████████▏| 27851/30196 [57:43<04:33,  8.57it/s]

 92%|█████████▏| 27853/30196 [57:43<03:47, 10.32it/s]

 92%|█████████▏| 27855/30196 [57:43<04:46,  8.16it/s]

 92%|█████████▏| 27857/30196 [57:43<04:53,  7.98it/s]

 92%|█████████▏| 27859/30196 [57:44<04:14,  9.20it/s]

 92%|█████████▏| 27861/30196 [57:44<03:48, 10.21it/s]

 92%|█████████▏| 27863/30196 [57:44<03:25, 11.34it/s]

 92%|█████████▏| 27865/30196 [57:44<03:54,  9.95it/s]

 92%|█████████▏| 27867/30196 [57:44<03:33, 10.93it/s]

 92%|█████████▏| 27869/30196 [57:44<03:31, 10.98it/s]

 92%|█████████▏| 27871/30196 [57:45<03:30, 11.05it/s]

 92%|█████████▏| 27873/30196 [57:45<03:19, 11.65it/s]

 92%|█████████▏| 27875/30196 [57:45<04:38,  8.35it/s]

 92%|█████████▏| 27877/30196 [57:46<06:38,  5.83it/s]

 92%|█████████▏| 27878/30196 [57:46<06:12,  6.23it/s]

 92%|█████████▏| 27879/30196 [57:46<05:44,  6.72it/s]

 92%|█████████▏| 27881/30196 [57:46<04:47,  8.07it/s]

 92%|█████████▏| 27884/30196 [57:46<03:58,  9.71it/s]

 92%|█████████▏| 27886/30196 [57:47<04:43,  8.13it/s]

 92%|█████████▏| 27888/30196 [57:47<04:40,  8.22it/s]

 92%|█████████▏| 27890/30196 [57:47<05:26,  7.07it/s]

 92%|█████████▏| 27891/30196 [57:47<05:21,  7.17it/s]

 92%|█████████▏| 27893/30196 [57:48<04:25,  8.66it/s]

 92%|█████████▏| 27895/30196 [57:48<03:38, 10.54it/s]

 92%|█████████▏| 27897/30196 [57:48<03:41, 10.38it/s]

 92%|█████████▏| 27899/30196 [57:48<03:28, 11.02it/s]

 92%|█████████▏| 27901/30196 [57:48<03:31, 10.85it/s]

 92%|█████████▏| 27903/30196 [57:48<03:31, 10.83it/s]

 92%|█████████▏| 27905/30196 [57:49<04:18,  8.88it/s]

 92%|█████████▏| 27907/30196 [57:49<03:51,  9.88it/s]

 92%|█████████▏| 27909/30196 [57:49<04:00,  9.50it/s]

 92%|█████████▏| 27911/30196 [57:49<03:39, 10.39it/s]

 92%|█████████▏| 27913/30196 [57:49<03:48, 10.00it/s]

 92%|█████████▏| 27915/30196 [57:50<03:31, 10.81it/s]

 92%|█████████▏| 27917/30196 [57:50<04:14,  8.96it/s]

 92%|█████████▏| 27918/30196 [57:50<04:22,  8.69it/s]

 92%|█████████▏| 27919/30196 [57:50<04:31,  8.39it/s]

 92%|█████████▏| 27920/30196 [57:50<04:25,  8.58it/s]

 92%|█████████▏| 27922/30196 [57:50<03:45, 10.09it/s]

 92%|█████████▏| 27924/30196 [57:51<05:04,  7.47it/s]

 92%|█████████▏| 27926/30196 [57:51<04:30,  8.38it/s]

 92%|█████████▏| 27927/30196 [57:51<05:12,  7.25it/s]

 92%|█████████▏| 27928/30196 [57:51<04:56,  7.65it/s]

 92%|█████████▏| 27930/30196 [57:52<04:26,  8.52it/s]

 93%|█████████▎| 27932/30196 [57:52<04:23,  8.59it/s]

 93%|█████████▎| 27933/30196 [57:52<04:20,  8.70it/s]

 93%|█████████▎| 27935/30196 [57:52<04:09,  9.05it/s]

 93%|█████████▎| 27936/30196 [57:52<04:20,  8.67it/s]

 93%|█████████▎| 27937/30196 [57:52<04:33,  8.25it/s]

 93%|█████████▎| 27939/30196 [57:52<03:45, 10.01it/s]

 93%|█████████▎| 27941/30196 [57:53<03:22, 11.15it/s]

 93%|█████████▎| 27943/30196 [57:53<03:20, 11.23it/s]

 93%|█████████▎| 27945/30196 [57:53<03:26, 10.88it/s]

 93%|█████████▎| 27947/30196 [57:53<03:42, 10.09it/s]

 93%|█████████▎| 27949/30196 [57:53<04:02,  9.27it/s]

 93%|█████████▎| 27951/30196 [57:54<03:32, 10.54it/s]

 93%|█████████▎| 27953/30196 [57:54<03:57,  9.44it/s]

 93%|█████████▎| 27955/30196 [57:54<03:33, 10.48it/s]

 93%|█████████▎| 27957/30196 [57:54<03:30, 10.62it/s]

 93%|█████████▎| 27959/30196 [57:54<03:27, 10.76it/s]

 93%|█████████▎| 27961/30196 [57:55<03:25, 10.86it/s]

 93%|█████████▎| 27963/30196 [57:55<03:57,  9.41it/s]

 93%|█████████▎| 27964/30196 [57:55<04:20,  8.57it/s]

 93%|█████████▎| 27966/30196 [57:55<03:39, 10.14it/s]

 93%|█████████▎| 27968/30196 [57:55<03:38, 10.19it/s]

 93%|█████████▎| 27970/30196 [57:55<03:25, 10.84it/s]

 93%|█████████▎| 27972/30196 [57:56<04:46,  7.77it/s]

 93%|█████████▎| 27973/30196 [57:56<04:38,  7.98it/s]

 93%|█████████▎| 27975/30196 [57:56<04:02,  9.16it/s]

 93%|█████████▎| 27977/30196 [57:56<04:19,  8.54it/s]

 93%|█████████▎| 27978/30196 [57:57<04:14,  8.72it/s]

 93%|█████████▎| 27979/30196 [57:57<04:24,  8.39it/s]

 93%|█████████▎| 27981/30196 [57:57<04:01,  9.17it/s]

 93%|█████████▎| 27983/30196 [57:57<03:18, 11.17it/s]

 93%|█████████▎| 27985/30196 [57:57<03:54,  9.44it/s]

 93%|█████████▎| 27987/30196 [57:58<04:28,  8.22it/s]

 93%|█████████▎| 27988/30196 [57:58<04:52,  7.55it/s]

 93%|█████████▎| 27990/30196 [57:58<03:57,  9.30it/s]

 93%|█████████▎| 27992/30196 [57:58<03:27, 10.64it/s]

 93%|█████████▎| 27995/30196 [57:58<03:38, 10.08it/s]

 93%|█████████▎| 27997/30196 [57:59<04:13,  8.67it/s]

 93%|█████████▎| 27999/30196 [57:59<04:30,  8.11it/s]

 93%|█████████▎| 28000/30196 [57:59<04:43,  7.76it/s]

 93%|█████████▎| 28001/30196 [57:59<05:04,  7.20it/s]

 93%|█████████▎| 28002/30196 [58:00<08:29,  4.30it/s]

 93%|█████████▎| 28003/30196 [58:00<07:56,  4.60it/s]

 93%|█████████▎| 28005/30196 [58:00<07:24,  4.93it/s]

 93%|█████████▎| 28006/30196 [58:00<06:56,  5.26it/s]

 93%|█████████▎| 28007/30196 [58:01<06:13,  5.86it/s]

 93%|█████████▎| 28008/30196 [58:01<06:19,  5.77it/s]

 93%|█████████▎| 28009/30196 [58:01<06:04,  6.01it/s]

 93%|█████████▎| 28011/30196 [58:01<04:37,  7.87it/s]

 93%|█████████▎| 28012/30196 [58:01<04:47,  7.59it/s]

 93%|█████████▎| 28013/30196 [58:01<05:29,  6.62it/s]

 93%|█████████▎| 28014/30196 [58:02<05:20,  6.81it/s]

 93%|█████████▎| 28016/30196 [58:02<04:57,  7.34it/s]

 93%|█████████▎| 28017/30196 [58:02<05:00,  7.24it/s]

 93%|█████████▎| 28019/30196 [58:02<04:40,  7.75it/s]

 93%|█████████▎| 28021/30196 [58:02<04:18,  8.41it/s]

 93%|█████████▎| 28022/30196 [58:03<04:40,  7.74it/s]

 93%|█████████▎| 28024/30196 [58:03<04:22,  8.28it/s]

 93%|█████████▎| 28025/30196 [58:03<04:26,  8.14it/s]

 93%|█████████▎| 28027/30196 [58:03<03:48,  9.51it/s]

 93%|█████████▎| 28028/30196 [58:03<04:36,  7.83it/s]

 93%|█████████▎| 28029/30196 [58:03<04:46,  7.57it/s]

 93%|█████████▎| 28031/30196 [58:04<03:50,  9.40it/s]

 93%|█████████▎| 28033/30196 [58:04<04:19,  8.32it/s]

 93%|█████████▎| 28034/30196 [58:04<04:45,  7.57it/s]

 93%|█████████▎| 28035/30196 [58:04<05:28,  6.58it/s]

 93%|█████████▎| 28037/30196 [58:04<05:03,  7.12it/s]

 93%|█████████▎| 28038/30196 [58:05<05:20,  6.74it/s]

 93%|█████████▎| 28040/30196 [58:05<04:27,  8.06it/s]

 93%|█████████▎| 28041/30196 [58:05<04:30,  7.96it/s]

 93%|█████████▎| 28042/30196 [58:05<05:17,  6.78it/s]

 93%|█████████▎| 28043/30196 [58:05<04:57,  7.25it/s]

 93%|█████████▎| 28044/30196 [58:05<04:52,  7.35it/s]

 93%|█████████▎| 28046/30196 [58:06<04:02,  8.88it/s]

 93%|█████████▎| 28048/30196 [58:06<03:23, 10.55it/s]

 93%|█████████▎| 28050/30196 [58:06<03:59,  8.97it/s]

 93%|█████████▎| 28051/30196 [58:06<04:13,  8.45it/s]

 93%|█████████▎| 28053/30196 [58:06<03:25, 10.41it/s]

 93%|█████████▎| 28055/30196 [58:06<03:30, 10.16it/s]

 93%|█████████▎| 28057/30196 [58:07<03:17, 10.82it/s]

 93%|█████████▎| 28059/30196 [58:07<03:58,  8.97it/s]

 93%|█████████▎| 28061/30196 [58:07<03:38,  9.77it/s]

 93%|█████████▎| 28063/30196 [58:07<03:18, 10.75it/s]

 93%|█████████▎| 28066/30196 [58:07<03:00, 11.83it/s]

 93%|█████████▎| 28068/30196 [58:08<02:48, 12.63it/s]

 93%|█████████▎| 28070/30196 [58:08<03:30, 10.09it/s]

 93%|█████████▎| 28072/30196 [58:08<03:29, 10.13it/s]

 93%|█████████▎| 28074/30196 [58:08<03:16, 10.78it/s]

 93%|█████████▎| 28076/30196 [58:08<03:34,  9.87it/s]

 93%|█████████▎| 28078/30196 [58:09<03:22, 10.48it/s]

 93%|█████████▎| 28080/30196 [58:09<04:01,  8.77it/s]

 93%|█████████▎| 28082/30196 [58:09<03:31, 10.00it/s]

 93%|█████████▎| 28084/30196 [58:09<03:06, 11.34it/s]

 93%|█████████▎| 28086/30196 [58:09<03:25, 10.25it/s]

 93%|█████████▎| 28088/30196 [58:10<03:39,  9.62it/s]

 93%|█████████▎| 28090/30196 [58:10<04:10,  8.40it/s]

 93%|█████████▎| 28092/30196 [58:10<04:10,  8.40it/s]

 93%|█████████▎| 28093/30196 [58:10<04:43,  7.42it/s]

 93%|█████████▎| 28094/30196 [58:11<04:41,  7.46it/s]

 93%|█████████▎| 28095/30196 [58:11<06:44,  5.19it/s]

 93%|█████████▎| 28097/30196 [58:11<05:27,  6.41it/s]

 93%|█████████▎| 28099/30196 [58:11<04:10,  8.38it/s]

 93%|█████████▎| 28101/30196 [58:12<04:06,  8.51it/s]

 93%|█████████▎| 28103/30196 [58:12<03:37,  9.63it/s]

 93%|█████████▎| 28105/30196 [58:12<03:40,  9.48it/s]

 93%|█████████▎| 28107/30196 [58:12<03:24, 10.22it/s]

 93%|█████████▎| 28109/30196 [58:12<03:29,  9.96it/s]

 93%|█████████▎| 28111/30196 [58:12<03:39,  9.49it/s]

 93%|█████████▎| 28112/30196 [58:13<04:03,  8.57it/s]

 93%|█████████▎| 28113/30196 [58:13<05:08,  6.76it/s]

 93%|█████████▎| 28114/30196 [58:13<05:07,  6.77it/s]

 93%|█████████▎| 28115/30196 [58:13<05:39,  6.12it/s]

 93%|█████████▎| 28117/30196 [58:14<04:55,  7.04it/s]

 93%|█████████▎| 28119/30196 [58:14<04:45,  7.27it/s]

 93%|█████████▎| 28120/30196 [58:14<04:44,  7.30it/s]

 93%|█████████▎| 28122/30196 [58:14<03:59,  8.67it/s]

 93%|█████████▎| 28123/30196 [58:14<03:54,  8.83it/s]

 93%|█████████▎| 28124/30196 [58:14<04:03,  8.52it/s]

 93%|█████████▎| 28125/30196 [58:14<04:18,  8.01it/s]

 93%|█████████▎| 28127/30196 [58:15<03:45,  9.17it/s]

 93%|█████████▎| 28128/30196 [58:15<03:58,  8.68it/s]

 93%|█████████▎| 28129/30196 [58:15<04:05,  8.41it/s]

 93%|█████████▎| 28131/30196 [58:15<03:42,  9.26it/s]

 93%|█████████▎| 28133/30196 [58:15<03:19, 10.34it/s]

 93%|█████████▎| 28135/30196 [58:15<03:23, 10.11it/s]

 93%|█████████▎| 28137/30196 [58:16<03:46,  9.09it/s]

 93%|█████████▎| 28139/30196 [58:16<03:17, 10.39it/s]

 93%|█████████▎| 28141/30196 [58:16<03:20, 10.23it/s]

 93%|█████████▎| 28143/30196 [58:16<03:34,  9.58it/s]

 93%|█████████▎| 28145/30196 [58:16<03:21, 10.16it/s]

 93%|█████████▎| 28147/30196 [58:17<03:21, 10.19it/s]

 93%|█████████▎| 28149/30196 [58:17<03:07, 10.94it/s]

 93%|█████████▎| 28151/30196 [58:17<03:19, 10.25it/s]

 93%|█████████▎| 28153/30196 [58:17<03:31,  9.67it/s]

 93%|█████████▎| 28155/30196 [58:18<03:47,  8.97it/s]

 93%|█████████▎| 28156/30196 [58:18<04:23,  7.74it/s]

 93%|█████████▎| 28158/30196 [58:18<04:36,  7.37it/s]

 93%|█████████▎| 28160/30196 [58:18<04:12,  8.08it/s]

 93%|█████████▎| 28161/30196 [58:18<04:04,  8.32it/s]

 93%|█████████▎| 28163/30196 [58:18<03:20, 10.12it/s]

 93%|█████████▎| 28165/30196 [58:19<03:02, 11.13it/s]

 93%|█████████▎| 28167/30196 [58:19<02:51, 11.80it/s]

 93%|█████████▎| 28169/30196 [58:19<03:55,  8.62it/s]

 93%|█████████▎| 28171/30196 [58:19<03:40,  9.19it/s]

 93%|█████████▎| 28173/30196 [58:20<04:00,  8.42it/s]

 93%|█████████▎| 28174/30196 [58:20<03:55,  8.58it/s]

 93%|█████████▎| 28175/30196 [58:20<04:15,  7.91it/s]

 93%|█████████▎| 28176/30196 [58:20<04:24,  7.64it/s]

 93%|█████████▎| 28177/30196 [58:20<04:24,  7.63it/s]

 93%|█████████▎| 28178/30196 [58:20<05:03,  6.65it/s]

 93%|█████████▎| 28179/30196 [58:20<04:52,  6.89it/s]

 93%|█████████▎| 28181/30196 [58:21<03:38,  9.23it/s]

 93%|█████████▎| 28183/30196 [58:21<03:29,  9.61it/s]

 93%|█████████▎| 28185/30196 [58:21<03:20, 10.03it/s]

 93%|█████████▎| 28187/30196 [58:21<05:11,  6.46it/s]

 93%|█████████▎| 28189/30196 [58:22<04:39,  7.17it/s]

 93%|█████████▎| 28191/30196 [58:22<03:56,  8.47it/s]

 93%|█████████▎| 28193/30196 [58:22<03:29,  9.58it/s]

 93%|█████████▎| 28195/30196 [58:22<03:17, 10.15it/s]

 93%|█████████▎| 28197/30196 [58:22<03:21,  9.91it/s]

 93%|█████████▎| 28199/30196 [58:22<02:58, 11.21it/s]

 93%|█████████▎| 28201/30196 [58:23<03:25,  9.69it/s]

 93%|█████████▎| 28203/30196 [58:23<03:30,  9.47it/s]

 93%|█████████▎| 28205/30196 [58:23<04:03,  8.19it/s]

 93%|█████████▎| 28206/30196 [58:24<04:35,  7.23it/s]

 93%|█████████▎| 28208/30196 [58:24<03:42,  8.93it/s]

 93%|█████████▎| 28210/30196 [58:24<04:16,  7.74it/s]

 93%|█████████▎| 28212/30196 [58:24<04:08,  7.99it/s]

 93%|█████████▎| 28214/30196 [58:24<04:10,  7.93it/s]

 93%|█████████▎| 28217/30196 [58:25<03:06, 10.61it/s]

 93%|█████████▎| 28219/30196 [58:25<03:41,  8.92it/s]

 93%|█████████▎| 28221/30196 [58:25<03:28,  9.46it/s]

 93%|█████████▎| 28223/30196 [58:25<03:29,  9.44it/s]

 93%|█████████▎| 28225/30196 [58:25<03:10, 10.36it/s]

 93%|█████████▎| 28227/30196 [58:26<03:26,  9.52it/s]

 93%|█████████▎| 28229/30196 [58:26<03:15, 10.06it/s]

 93%|█████████▎| 28231/30196 [58:26<03:34,  9.18it/s]

 93%|█████████▎| 28233/30196 [58:26<03:13, 10.13it/s]

 94%|█████████▎| 28235/30196 [58:26<03:13, 10.13it/s]

 94%|█████████▎| 28237/30196 [58:27<04:30,  7.23it/s]

 94%|█████████▎| 28238/30196 [58:27<04:19,  7.55it/s]

 94%|█████████▎| 28239/30196 [58:27<04:18,  7.57it/s]

 94%|█████████▎| 28241/30196 [58:27<03:34,  9.11it/s]

 94%|█████████▎| 28243/30196 [58:28<03:57,  8.23it/s]

 94%|█████████▎| 28245/30196 [58:28<03:15,  9.97it/s]

 94%|█████████▎| 28247/30196 [58:28<03:03, 10.63it/s]

 94%|█████████▎| 28250/30196 [58:28<02:32, 12.79it/s]

 94%|█████████▎| 28252/30196 [58:28<02:53, 11.18it/s]

 94%|█████████▎| 28254/30196 [58:28<02:48, 11.52it/s]

 94%|█████████▎| 28256/30196 [58:29<03:02, 10.63it/s]

 94%|█████████▎| 28258/30196 [58:29<03:27,  9.35it/s]

 94%|█████████▎| 28260/30196 [58:29<03:11, 10.12it/s]

 94%|█████████▎| 28262/30196 [58:29<03:40,  8.77it/s]

 94%|█████████▎| 28263/30196 [58:30<03:45,  8.56it/s]

 94%|█████████▎| 28265/30196 [58:30<03:57,  8.14it/s]

 94%|█████████▎| 28266/30196 [58:30<04:06,  7.83it/s]

 94%|█████████▎| 28267/30196 [58:30<04:57,  6.48it/s]

 94%|█████████▎| 28269/30196 [58:30<04:06,  7.81it/s]

 94%|█████████▎| 28271/30196 [58:31<03:30,  9.14it/s]

 94%|█████████▎| 28272/30196 [58:31<03:38,  8.80it/s]

 94%|█████████▎| 28274/30196 [58:31<03:10, 10.11it/s]

 94%|█████████▎| 28276/30196 [58:31<04:14,  7.55it/s]

 94%|█████████▎| 28277/30196 [58:31<05:07,  6.25it/s]

 94%|█████████▎| 28278/30196 [58:32<05:01,  6.36it/s]

 94%|█████████▎| 28280/30196 [58:32<04:47,  6.66it/s]

 94%|█████████▎| 28281/30196 [58:32<05:59,  5.32it/s]

 94%|█████████▎| 28282/30196 [58:32<05:24,  5.90it/s]

 94%|█████████▎| 28283/30196 [58:33<05:27,  5.84it/s]

 94%|█████████▎| 28285/30196 [58:33<04:28,  7.12it/s]

 94%|█████████▎| 28287/30196 [58:33<03:28,  9.16it/s]

 94%|█████████▎| 28289/30196 [58:33<03:47,  8.39it/s]

 94%|█████████▎| 28290/30196 [58:33<04:22,  7.26it/s]

 94%|█████████▎| 28292/30196 [58:33<03:38,  8.72it/s]

 94%|█████████▎| 28293/30196 [58:34<03:36,  8.80it/s]

 94%|█████████▎| 28294/30196 [58:34<04:15,  7.44it/s]

 94%|█████████▎| 28295/30196 [58:34<04:48,  6.59it/s]

 94%|█████████▎| 28297/30196 [58:34<03:35,  8.81it/s]

 94%|█████████▎| 28299/30196 [58:34<02:59, 10.54it/s]

 94%|█████████▎| 28301/30196 [58:35<03:41,  8.54it/s]

 94%|█████████▎| 28303/30196 [58:35<03:51,  8.18it/s]

 94%|█████████▎| 28304/30196 [58:35<06:23,  4.94it/s]

 94%|█████████▎| 28305/30196 [58:36<06:09,  5.12it/s]

 94%|█████████▎| 28306/30196 [58:36<06:13,  5.05it/s]

 94%|█████████▎| 28308/30196 [58:36<04:44,  6.63it/s]

 94%|█████████▍| 28309/30196 [58:36<04:37,  6.79it/s]

 94%|█████████▍| 28310/30196 [58:36<04:49,  6.50it/s]

 94%|█████████▍| 28311/30196 [58:36<05:01,  6.26it/s]

 94%|█████████▍| 28313/30196 [58:37<03:50,  8.16it/s]

 94%|█████████▍| 28314/30196 [58:37<04:10,  7.51it/s]

 94%|█████████▍| 28315/30196 [58:37<04:55,  6.37it/s]

 94%|█████████▍| 28317/30196 [58:37<04:14,  7.37it/s]

 94%|█████████▍| 28318/30196 [58:37<04:16,  7.32it/s]

 94%|█████████▍| 28319/30196 [58:37<04:30,  6.95it/s]

 94%|█████████▍| 28320/30196 [58:38<04:13,  7.41it/s]

 94%|█████████▍| 28322/30196 [58:38<03:55,  7.94it/s]

 94%|█████████▍| 28323/30196 [58:38<03:46,  8.26it/s]

 94%|█████████▍| 28325/30196 [58:38<02:55, 10.66it/s]

 94%|█████████▍| 28327/30196 [58:38<02:40, 11.66it/s]

 94%|█████████▍| 28329/30196 [58:38<03:11,  9.75it/s]

 94%|█████████▍| 28331/30196 [58:39<03:58,  7.81it/s]

 94%|█████████▍| 28332/30196 [58:39<04:11,  7.41it/s]

 94%|█████████▍| 28333/30196 [58:39<04:14,  7.33it/s]

 94%|█████████▍| 28335/30196 [58:39<03:35,  8.62it/s]

 94%|█████████▍| 28337/30196 [58:39<03:07,  9.89it/s]

 94%|█████████▍| 28339/30196 [58:39<02:37, 11.75it/s]

 94%|█████████▍| 28342/30196 [58:40<02:14, 13.74it/s]

 94%|█████████▍| 28344/30196 [58:40<02:46, 11.12it/s]

 94%|█████████▍| 28346/30196 [58:40<03:39,  8.44it/s]

 94%|█████████▍| 28348/30196 [58:40<03:07,  9.83it/s]

 94%|█████████▍| 28350/30196 [58:41<03:33,  8.63it/s]

 94%|█████████▍| 28352/30196 [58:41<03:32,  8.68it/s]

 94%|█████████▍| 28354/30196 [58:41<02:59, 10.26it/s]

 94%|█████████▍| 28356/30196 [58:41<03:25,  8.97it/s]

 94%|█████████▍| 28358/30196 [58:42<03:17,  9.31it/s]

 94%|█████████▍| 28360/30196 [58:42<03:25,  8.94it/s]

 94%|█████████▍| 28361/30196 [58:42<03:31,  8.68it/s]

 94%|█████████▍| 28363/30196 [58:42<03:45,  8.13it/s]

 94%|█████████▍| 28364/30196 [58:43<05:52,  5.20it/s]

 94%|█████████▍| 28365/30196 [58:43<05:34,  5.47it/s]

 94%|█████████▍| 28366/30196 [58:43<05:07,  5.95it/s]

 94%|█████████▍| 28367/30196 [58:43<05:12,  5.85it/s]

 94%|█████████▍| 28369/30196 [58:44<05:40,  5.37it/s]

 94%|█████████▍| 28371/30196 [58:44<04:35,  6.63it/s]

 94%|█████████▍| 28374/30196 [58:44<03:20,  9.09it/s]

 94%|█████████▍| 28376/30196 [58:44<03:23,  8.96it/s]

 94%|█████████▍| 28377/30196 [58:44<03:22,  8.98it/s]

 94%|█████████▍| 28378/30196 [58:44<03:29,  8.69it/s]

 94%|█████████▍| 28380/30196 [58:45<03:17,  9.18it/s]

 94%|█████████▍| 28381/30196 [58:45<03:18,  9.17it/s]

 94%|█████████▍| 28383/30196 [58:45<03:50,  7.87it/s]

 94%|█████████▍| 28385/30196 [58:45<03:18,  9.14it/s]

 94%|█████████▍| 28387/30196 [58:45<02:51, 10.55it/s]

 94%|█████████▍| 28389/30196 [58:45<02:43, 11.03it/s]

 94%|█████████▍| 28391/30196 [58:46<03:21,  8.96it/s]

 94%|█████████▍| 28393/30196 [58:46<03:45,  7.99it/s]

 94%|█████████▍| 28395/30196 [58:46<03:24,  8.79it/s]

 94%|█████████▍| 28396/30196 [58:46<03:44,  8.01it/s]

 94%|█████████▍| 28397/30196 [58:47<04:23,  6.83it/s]

 94%|█████████▍| 28399/30196 [58:47<03:39,  8.17it/s]

 94%|█████████▍| 28401/30196 [58:47<02:59,  9.99it/s]

 94%|█████████▍| 28403/30196 [58:47<03:20,  8.95it/s]

 94%|█████████▍| 28405/30196 [58:47<03:15,  9.17it/s]

 94%|█████████▍| 28407/30196 [58:48<03:45,  7.95it/s]

 94%|█████████▍| 28409/30196 [58:48<03:11,  9.33it/s]

 94%|█████████▍| 28411/30196 [58:48<03:35,  8.29it/s]

 94%|█████████▍| 28412/30196 [58:48<04:02,  7.34it/s]

 94%|█████████▍| 28414/30196 [58:48<03:10,  9.34it/s]

 94%|█████████▍| 28416/30196 [58:49<02:46, 10.71it/s]

 94%|█████████▍| 28418/30196 [58:49<02:43, 10.88it/s]

 94%|█████████▍| 28420/30196 [58:49<02:37, 11.30it/s]

 94%|█████████▍| 28422/30196 [58:49<03:08,  9.40it/s]

 94%|█████████▍| 28424/30196 [58:49<02:42, 10.88it/s]

 94%|█████████▍| 28426/30196 [58:50<02:47, 10.57it/s]

 94%|█████████▍| 28428/30196 [58:50<03:23,  8.67it/s]

 94%|█████████▍| 28430/30196 [58:50<03:55,  7.49it/s]

 94%|█████████▍| 28431/30196 [58:51<04:44,  6.21it/s]

 94%|█████████▍| 28432/30196 [58:51<04:38,  6.33it/s]

 94%|█████████▍| 28433/30196 [58:51<04:42,  6.23it/s]

 94%|█████████▍| 28435/30196 [58:51<03:50,  7.63it/s]

 94%|█████████▍| 28437/30196 [58:51<03:28,  8.44it/s]

 94%|█████████▍| 28438/30196 [58:52<05:03,  5.79it/s]

 94%|█████████▍| 28440/30196 [58:52<03:57,  7.39it/s]

 94%|█████████▍| 28442/30196 [58:52<03:24,  8.59it/s]

 94%|█████████▍| 28444/30196 [58:52<02:50, 10.30it/s]

 94%|█████████▍| 28446/30196 [58:52<03:23,  8.61it/s]

 94%|█████████▍| 28448/30196 [58:53<04:34,  6.38it/s]

 94%|█████████▍| 28449/30196 [58:53<04:18,  6.75it/s]

 94%|█████████▍| 28450/30196 [58:53<04:15,  6.83it/s]

 94%|█████████▍| 28451/30196 [58:53<04:29,  6.48it/s]

 94%|█████████▍| 28452/30196 [58:53<04:34,  6.36it/s]

 94%|█████████▍| 28453/30196 [58:54<04:22,  6.65it/s]

 94%|█████████▍| 28454/30196 [58:54<04:02,  7.17it/s]

 94%|█████████▍| 28456/30196 [58:54<03:05,  9.36it/s]

 94%|█████████▍| 28458/30196 [58:54<02:53, 10.04it/s]

 94%|█████████▍| 28461/30196 [58:54<02:12, 13.09it/s]

 94%|█████████▍| 28463/30196 [58:54<02:42, 10.69it/s]

 94%|█████████▍| 28465/30196 [58:55<02:38, 10.89it/s]

 94%|█████████▍| 28467/30196 [58:55<02:41, 10.70it/s]

 94%|█████████▍| 28469/30196 [58:55<02:41, 10.70it/s]

 94%|█████████▍| 28471/30196 [58:55<02:37, 10.96it/s]

 94%|█████████▍| 28473/30196 [58:55<03:10,  9.05it/s]

 94%|█████████▍| 28474/30196 [58:56<03:17,  8.72it/s]

 94%|█████████▍| 28475/30196 [58:56<03:24,  8.40it/s]

 94%|█████████▍| 28476/30196 [58:56<03:58,  7.22it/s]

 94%|█████████▍| 28478/30196 [58:56<03:36,  7.94it/s]

 94%|█████████▍| 28479/30196 [58:56<03:30,  8.16it/s]

 94%|█████████▍| 28480/30196 [58:56<04:04,  7.01it/s]

 94%|█████████▍| 28481/30196 [58:57<04:01,  7.09it/s]

 94%|█████████▍| 28482/30196 [58:57<03:58,  7.18it/s]

 94%|█████████▍| 28483/30196 [58:57<03:59,  7.16it/s]

 94%|█████████▍| 28484/30196 [58:57<04:02,  7.05it/s]

 94%|█████████▍| 28486/30196 [58:57<03:30,  8.12it/s]

 94%|█████████▍| 28487/30196 [58:57<03:34,  7.98it/s]

 94%|█████████▍| 28488/30196 [58:57<03:54,  7.27it/s]

 94%|█████████▍| 28489/30196 [58:58<04:07,  6.89it/s]

 94%|█████████▍| 28490/30196 [58:58<04:23,  6.48it/s]

 94%|█████████▍| 28491/30196 [58:58<04:52,  5.84it/s]

 94%|█████████▍| 28492/30196 [58:58<04:49,  5.90it/s]

 94%|█████████▍| 28494/30196 [58:58<03:46,  7.52it/s]

 94%|█████████▍| 28496/30196 [58:58<03:00,  9.39it/s]

 94%|█████████▍| 28497/30196 [58:59<03:16,  8.66it/s]

 94%|█████████▍| 28499/30196 [58:59<03:04,  9.18it/s]

 94%|█████████▍| 28501/30196 [58:59<02:42, 10.43it/s]

 94%|█████████▍| 28503/30196 [58:59<02:46, 10.18it/s]

 94%|█████████▍| 28505/30196 [59:00<03:26,  8.20it/s]

 94%|█████████▍| 28506/30196 [59:00<03:34,  7.88it/s]

 94%|█████████▍| 28507/30196 [59:00<03:35,  7.84it/s]

 94%|█████████▍| 28508/30196 [59:00<03:32,  7.96it/s]

 94%|█████████▍| 28509/30196 [59:00<03:23,  8.31it/s]

 94%|█████████▍| 28510/30196 [59:00<03:43,  7.54it/s]

 94%|█████████▍| 28511/30196 [59:00<03:43,  7.54it/s]

 94%|█████████▍| 28513/30196 [59:01<03:50,  7.29it/s]

 94%|█████████▍| 28515/30196 [59:01<03:48,  7.36it/s]

 94%|█████████▍| 28517/30196 [59:01<03:16,  8.54it/s]

 94%|█████████▍| 28519/30196 [59:01<02:48,  9.95it/s]

 94%|█████████▍| 28521/30196 [59:01<02:36, 10.70it/s]

 94%|█████████▍| 28523/30196 [59:01<02:17, 12.18it/s]

 94%|█████████▍| 28525/30196 [59:02<02:15, 12.29it/s]

 94%|█████████▍| 28527/30196 [59:02<02:30, 11.12it/s]

 94%|█████████▍| 28529/30196 [59:02<02:54,  9.53it/s]

 94%|█████████▍| 28532/30196 [59:02<02:18, 11.97it/s]

 94%|█████████▍| 28534/30196 [59:03<02:39, 10.41it/s]

 95%|█████████▍| 28536/30196 [59:03<02:43, 10.12it/s]

 95%|█████████▍| 28538/30196 [59:03<03:00,  9.17it/s]

 95%|█████████▍| 28539/30196 [59:03<03:16,  8.42it/s]

 95%|█████████▍| 28540/30196 [59:03<03:12,  8.61it/s]

 95%|█████████▍| 28541/30196 [59:03<03:10,  8.70it/s]

 95%|█████████▍| 28542/30196 [59:03<03:08,  8.79it/s]

 95%|█████████▍| 28543/30196 [59:04<03:16,  8.41it/s]

 95%|█████████▍| 28545/30196 [59:04<02:58,  9.24it/s]

 95%|█████████▍| 28546/30196 [59:04<03:25,  8.04it/s]

 95%|█████████▍| 28547/30196 [59:04<03:16,  8.38it/s]

 95%|█████████▍| 28548/30196 [59:04<04:03,  6.77it/s]

 95%|█████████▍| 28549/30196 [59:04<04:13,  6.50it/s]

 95%|█████████▍| 28550/30196 [59:05<03:50,  7.14it/s]

 95%|█████████▍| 28551/30196 [59:05<04:21,  6.29it/s]

 95%|█████████▍| 28552/30196 [59:05<03:55,  6.97it/s]

 95%|█████████▍| 28553/30196 [59:05<03:54,  7.02it/s]

 95%|█████████▍| 28555/30196 [59:05<03:34,  7.64it/s]

 95%|█████████▍| 28556/30196 [59:05<03:24,  8.04it/s]

 95%|█████████▍| 28557/30196 [59:06<03:27,  7.88it/s]

 95%|█████████▍| 28558/30196 [59:06<03:44,  7.29it/s]

 95%|█████████▍| 28559/30196 [59:06<03:46,  7.22it/s]

 95%|█████████▍| 28561/30196 [59:06<03:38,  7.48it/s]

 95%|█████████▍| 28562/30196 [59:06<03:42,  7.34it/s]

 95%|█████████▍| 28564/30196 [59:06<03:20,  8.16it/s]

 95%|█████████▍| 28566/30196 [59:07<02:41, 10.09it/s]

 95%|█████████▍| 28568/30196 [59:07<02:56,  9.20it/s]

 95%|█████████▍| 28569/30196 [59:07<03:19,  8.16it/s]

 95%|█████████▍| 28571/30196 [59:07<03:04,  8.80it/s]

 95%|█████████▍| 28572/30196 [59:07<03:15,  8.31it/s]

 95%|█████████▍| 28574/30196 [59:08<03:14,  8.32it/s]

 95%|█████████▍| 28575/30196 [59:08<03:34,  7.56it/s]

 95%|█████████▍| 28577/30196 [59:08<02:54,  9.29it/s]

 95%|█████████▍| 28578/30196 [59:08<03:05,  8.71it/s]

 95%|█████████▍| 28579/30196 [59:08<03:17,  8.20it/s]

 95%|█████████▍| 28581/30196 [59:08<02:50,  9.47it/s]

 95%|█████████▍| 28583/30196 [59:08<02:30, 10.71it/s]

 95%|█████████▍| 28585/30196 [59:09<02:40, 10.05it/s]

 95%|█████████▍| 28587/30196 [59:09<03:12,  8.37it/s]

 95%|█████████▍| 28589/30196 [59:09<03:42,  7.23it/s]

 95%|█████████▍| 28590/30196 [59:10<03:40,  7.27it/s]

 95%|█████████▍| 28592/30196 [59:10<03:27,  7.73it/s]

 95%|█████████▍| 28594/30196 [59:10<02:53,  9.23it/s]

 95%|█████████▍| 28596/30196 [59:10<02:31, 10.59it/s]

 95%|█████████▍| 28598/30196 [59:10<02:48,  9.46it/s]

 95%|█████████▍| 28600/30196 [59:11<03:04,  8.66it/s]

 95%|█████████▍| 28601/30196 [59:11<03:52,  6.85it/s]

 95%|█████████▍| 28603/30196 [59:11<03:33,  7.47it/s]

 95%|█████████▍| 28606/30196 [59:11<02:53,  9.17it/s]

 95%|█████████▍| 28607/30196 [59:11<03:01,  8.75it/s]

 95%|█████████▍| 28608/30196 [59:12<03:06,  8.51it/s]

 95%|█████████▍| 28610/30196 [59:12<03:03,  8.65it/s]

 95%|█████████▍| 28612/30196 [59:12<02:39,  9.95it/s]

 95%|█████████▍| 28614/30196 [59:12<02:34, 10.21it/s]

 95%|█████████▍| 28616/30196 [59:12<02:57,  8.89it/s]

 95%|█████████▍| 28617/30196 [59:13<03:14,  8.13it/s]

 95%|█████████▍| 28619/30196 [59:13<02:51,  9.20it/s]

 95%|█████████▍| 28620/30196 [59:13<03:22,  7.77it/s]

 95%|█████████▍| 28622/30196 [59:13<03:11,  8.22it/s]

 95%|█████████▍| 28623/30196 [59:13<03:07,  8.37it/s]

 95%|█████████▍| 28624/30196 [59:13<03:17,  7.94it/s]

 95%|█████████▍| 28625/30196 [59:13<03:11,  8.20it/s]

 95%|█████████▍| 28627/30196 [59:14<02:54,  8.97it/s]

 95%|█████████▍| 28628/30196 [59:14<03:05,  8.47it/s]

 95%|█████████▍| 28630/30196 [59:14<02:40,  9.78it/s]

 95%|█████████▍| 28631/30196 [59:14<02:40,  9.74it/s]

 95%|█████████▍| 28632/30196 [59:14<02:52,  9.05it/s]

 95%|█████████▍| 28633/30196 [59:14<03:14,  8.05it/s]

 95%|█████████▍| 28634/30196 [59:14<03:06,  8.36it/s]

 95%|█████████▍| 28635/30196 [59:15<03:02,  8.54it/s]

 95%|█████████▍| 28636/30196 [59:15<04:04,  6.37it/s]

 95%|█████████▍| 28638/30196 [59:15<03:08,  8.28it/s]

 95%|█████████▍| 28639/30196 [59:15<03:48,  6.83it/s]

 95%|█████████▍| 28641/30196 [59:15<03:02,  8.51it/s]

 95%|█████████▍| 28643/30196 [59:16<02:58,  8.68it/s]

 95%|█████████▍| 28645/30196 [59:16<02:41,  9.61it/s]

 95%|█████████▍| 28647/30196 [59:16<02:33, 10.10it/s]

 95%|█████████▍| 28649/30196 [59:16<03:30,  7.36it/s]

 95%|█████████▍| 28650/30196 [59:17<03:49,  6.73it/s]

 95%|█████████▍| 28652/30196 [59:17<03:13,  8.00it/s]

 95%|█████████▍| 28653/30196 [59:17<04:32,  5.67it/s]

 95%|█████████▍| 28654/30196 [59:17<04:31,  5.68it/s]

 95%|█████████▍| 28656/30196 [59:18<04:13,  6.08it/s]

 95%|█████████▍| 28657/30196 [59:18<05:10,  4.95it/s]

 95%|█████████▍| 28659/30196 [59:18<04:28,  5.73it/s]

 95%|█████████▍| 28660/30196 [59:18<04:27,  5.74it/s]

 95%|█████████▍| 28661/30196 [59:18<04:04,  6.29it/s]

 95%|█████████▍| 28662/30196 [59:19<04:06,  6.22it/s]

 95%|█████████▍| 28663/30196 [59:19<03:58,  6.43it/s]

 95%|█████████▍| 28664/30196 [59:19<04:46,  5.34it/s]

 95%|█████████▍| 28666/30196 [59:19<03:54,  6.53it/s]

 95%|█████████▍| 28667/30196 [59:19<04:00,  6.37it/s]

 95%|█████████▍| 28668/30196 [59:20<04:08,  6.16it/s]

 95%|█████████▍| 28669/30196 [59:20<03:46,  6.74it/s]

 95%|█████████▍| 28670/30196 [59:20<03:59,  6.36it/s]

 95%|█████████▍| 28671/30196 [59:20<03:43,  6.83it/s]

 95%|█████████▍| 28673/30196 [59:20<04:01,  6.30it/s]

 95%|█████████▍| 28674/30196 [59:21<03:51,  6.57it/s]

 95%|█████████▍| 28676/30196 [59:21<02:53,  8.78it/s]

 95%|█████████▍| 28678/30196 [59:21<02:47,  9.06it/s]

 95%|█████████▍| 28679/30196 [59:21<03:17,  7.67it/s]

 95%|█████████▍| 28681/30196 [59:21<02:32,  9.90it/s]

 95%|█████████▍| 28683/30196 [59:21<02:11, 11.51it/s]

 95%|█████████▍| 28685/30196 [59:22<02:43,  9.21it/s]

 95%|█████████▌| 28687/30196 [59:22<02:37,  9.55it/s]

 95%|█████████▌| 28689/30196 [59:22<02:40,  9.36it/s]

 95%|█████████▌| 28691/30196 [59:22<02:20, 10.72it/s]

 95%|█████████▌| 28693/30196 [59:22<02:32,  9.89it/s]

 95%|█████████▌| 28695/30196 [59:23<02:44,  9.15it/s]

 95%|█████████▌| 28696/30196 [59:23<02:51,  8.76it/s]

 95%|█████████▌| 28698/30196 [59:23<02:30,  9.94it/s]

 95%|█████████▌| 28700/30196 [59:23<03:20,  7.47it/s]

 95%|█████████▌| 28701/30196 [59:23<03:11,  7.79it/s]

 95%|█████████▌| 28703/30196 [59:24<03:08,  7.94it/s]

 95%|█████████▌| 28705/30196 [59:24<03:19,  7.49it/s]

 95%|█████████▌| 28707/30196 [59:24<02:59,  8.32it/s]

 95%|█████████▌| 28708/30196 [59:24<03:02,  8.14it/s]

 95%|█████████▌| 28710/30196 [59:24<02:32,  9.72it/s]

 95%|█████████▌| 28712/30196 [59:25<02:26, 10.13it/s]

 95%|█████████▌| 28714/30196 [59:25<02:27, 10.07it/s]

 95%|█████████▌| 28716/30196 [59:25<02:55,  8.44it/s]

 95%|█████████▌| 28717/30196 [59:25<03:08,  7.83it/s]

 95%|█████████▌| 28718/30196 [59:26<03:49,  6.45it/s]

 95%|█████████▌| 28720/30196 [59:26<02:55,  8.41it/s]

 95%|█████████▌| 28722/30196 [59:26<02:46,  8.88it/s]

 95%|█████████▌| 28723/30196 [59:26<03:15,  7.52it/s]

 95%|█████████▌| 28724/30196 [59:27<07:21,  3.34it/s]

 95%|█████████▌| 28725/30196 [59:27<06:49,  3.59it/s]

 95%|█████████▌| 28727/30196 [59:27<04:56,  4.96it/s]

 95%|█████████▌| 28728/30196 [59:28<04:57,  4.94it/s]

 95%|█████████▌| 28730/30196 [59:28<03:48,  6.42it/s]

 95%|█████████▌| 28731/30196 [59:28<03:36,  6.76it/s]

 95%|█████████▌| 28733/30196 [59:28<03:17,  7.40it/s]

 95%|█████████▌| 28735/30196 [59:28<03:25,  7.12it/s]

 95%|█████████▌| 28737/30196 [59:29<03:09,  7.69it/s]

 95%|█████████▌| 28739/30196 [59:29<02:49,  8.57it/s]

 95%|█████████▌| 28740/30196 [59:29<03:04,  7.91it/s]

 95%|█████████▌| 28742/30196 [59:29<04:05,  5.93it/s]

 95%|█████████▌| 28744/30196 [59:30<03:52,  6.24it/s]

 95%|█████████▌| 28746/30196 [59:30<03:11,  7.58it/s]

 95%|█████████▌| 28747/30196 [59:30<03:52,  6.23it/s]

 95%|█████████▌| 28748/30196 [59:30<03:35,  6.72it/s]

 95%|█████████▌| 28750/30196 [59:30<03:04,  7.83it/s]

 95%|█████████▌| 28751/30196 [59:31<03:05,  7.80it/s]

 95%|█████████▌| 28752/30196 [59:31<03:11,  7.52it/s]

 95%|█████████▌| 28754/30196 [59:31<02:39,  9.07it/s]

 95%|█████████▌| 28756/30196 [59:31<02:52,  8.36it/s]

 95%|█████████▌| 28758/30196 [59:31<02:37,  9.15it/s]

 95%|█████████▌| 28761/30196 [59:31<01:57, 12.26it/s]

 95%|█████████▌| 28763/30196 [59:32<01:44, 13.76it/s]

 95%|█████████▌| 28765/30196 [59:32<01:45, 13.61it/s]

 95%|█████████▌| 28767/30196 [59:32<02:35,  9.19it/s]

 95%|█████████▌| 28769/30196 [59:32<02:16, 10.43it/s]

 95%|█████████▌| 28771/30196 [59:33<02:37,  9.03it/s]

 95%|█████████▌| 28773/30196 [59:33<02:20, 10.09it/s]

 95%|█████████▌| 28775/30196 [59:33<02:10, 10.90it/s]

 95%|█████████▌| 28777/30196 [59:33<01:59, 11.85it/s]

 95%|█████████▌| 28779/30196 [59:33<02:14, 10.57it/s]

 95%|█████████▌| 28781/30196 [59:34<02:55,  8.08it/s]

 95%|█████████▌| 28782/30196 [59:34<02:50,  8.30it/s]

 95%|█████████▌| 28784/30196 [59:34<03:00,  7.84it/s]

 95%|█████████▌| 28785/30196 [59:34<03:05,  7.61it/s]

 95%|█████████▌| 28787/30196 [59:34<02:48,  8.34it/s]

 95%|█████████▌| 28788/30196 [59:34<02:54,  8.06it/s]

 95%|█████████▌| 28789/30196 [59:35<03:09,  7.42it/s]

 95%|█████████▌| 28791/30196 [59:35<02:36,  8.98it/s]

 95%|█████████▌| 28792/30196 [59:35<02:42,  8.66it/s]

 95%|█████████▌| 28794/30196 [59:35<02:44,  8.54it/s]

 95%|█████████▌| 28796/30196 [59:35<02:33,  9.11it/s]

 95%|█████████▌| 28797/30196 [59:35<02:40,  8.72it/s]

 95%|█████████▌| 28798/30196 [59:36<02:56,  7.94it/s]

 95%|█████████▌| 28801/30196 [59:36<02:11, 10.59it/s]

 95%|█████████▌| 28803/30196 [59:36<02:45,  8.43it/s]

 95%|█████████▌| 28805/30196 [59:36<02:43,  8.53it/s]

 95%|█████████▌| 28807/30196 [59:37<03:02,  7.62it/s]

 95%|█████████▌| 28809/30196 [59:37<03:20,  6.93it/s]

 95%|█████████▌| 28811/30196 [59:37<03:19,  6.94it/s]

 95%|█████████▌| 28812/30196 [59:38<03:45,  6.14it/s]

 95%|█████████▌| 28813/30196 [59:38<03:41,  6.25it/s]

 95%|█████████▌| 28814/30196 [59:38<03:44,  6.17it/s]

 95%|█████████▌| 28815/30196 [59:38<03:26,  6.69it/s]

 95%|█████████▌| 28817/30196 [59:38<03:03,  7.50it/s]

 95%|█████████▌| 28819/30196 [59:38<02:49,  8.10it/s]

 95%|█████████▌| 28821/30196 [59:39<02:45,  8.29it/s]

 95%|█████████▌| 28822/30196 [59:39<02:58,  7.68it/s]

 95%|█████████▌| 28824/30196 [59:39<02:31,  9.06it/s]

 95%|█████████▌| 28825/30196 [59:39<02:46,  8.22it/s]

 95%|█████████▌| 28827/30196 [59:39<02:33,  8.93it/s]

 95%|█████████▌| 28828/30196 [59:39<02:43,  8.38it/s]

 95%|█████████▌| 28829/30196 [59:40<02:43,  8.36it/s]

 95%|█████████▌| 28830/30196 [59:40<02:59,  7.63it/s]

 95%|█████████▌| 28832/30196 [59:40<02:35,  8.78it/s]

 95%|█████████▌| 28833/30196 [59:40<02:40,  8.50it/s]

 95%|█████████▌| 28835/30196 [59:40<02:15, 10.04it/s]

 95%|█████████▌| 28837/30196 [59:40<02:03, 11.00it/s]

 96%|█████████▌| 28839/30196 [59:41<02:16,  9.97it/s]

 96%|█████████▌| 28841/30196 [59:41<02:07, 10.64it/s]

 96%|█████████▌| 28843/30196 [59:41<03:27,  6.52it/s]

 96%|█████████▌| 28845/30196 [59:42<03:07,  7.20it/s]

 96%|█████████▌| 28847/30196 [59:42<02:50,  7.90it/s]

 96%|█████████▌| 28849/30196 [59:42<02:29,  9.02it/s]

 96%|█████████▌| 28851/30196 [59:42<02:05, 10.71it/s]

 96%|█████████▌| 28853/30196 [59:42<02:08, 10.46it/s]

 96%|█████████▌| 28855/30196 [59:42<01:52, 11.91it/s]

 96%|█████████▌| 28857/30196 [59:43<01:59, 11.23it/s]

 96%|█████████▌| 28859/30196 [59:43<01:56, 11.50it/s]

 96%|█████████▌| 28861/30196 [59:43<02:11, 10.16it/s]

 96%|█████████▌| 28863/30196 [59:43<02:00, 11.02it/s]

 96%|█████████▌| 28865/30196 [59:43<02:26,  9.09it/s]

 96%|█████████▌| 28867/30196 [59:44<02:42,  8.18it/s]

 96%|█████████▌| 28868/30196 [59:44<02:45,  8.04it/s]

 96%|█████████▌| 28870/30196 [59:44<02:15,  9.81it/s]

 96%|█████████▌| 28872/30196 [59:45<03:40,  6.02it/s]

 96%|█████████▌| 28873/30196 [59:45<03:35,  6.15it/s]

 96%|█████████▌| 28875/30196 [59:45<03:14,  6.78it/s]

 96%|█████████▌| 28876/30196 [59:45<03:14,  6.77it/s]

 96%|█████████▌| 28878/30196 [59:45<02:46,  7.92it/s]

 96%|█████████▌| 28879/30196 [59:45<02:57,  7.40it/s]

 96%|█████████▌| 28880/30196 [59:46<02:58,  7.39it/s]

 96%|█████████▌| 28882/30196 [59:46<02:28,  8.82it/s]

 96%|█████████▌| 28883/30196 [59:46<02:45,  7.91it/s]

 96%|█████████▌| 28885/30196 [59:46<02:15,  9.69it/s]

 96%|█████████▌| 28887/30196 [59:46<02:05, 10.45it/s]

 96%|█████████▌| 28889/30196 [59:46<01:57, 11.15it/s]

 96%|█████████▌| 28891/30196 [59:46<01:47, 12.10it/s]

 96%|█████████▌| 28894/30196 [59:47<01:36, 13.51it/s]

 96%|█████████▌| 28896/30196 [59:47<01:42, 12.71it/s]

 96%|█████████▌| 28898/30196 [59:47<02:31,  8.55it/s]

 96%|█████████▌| 28900/30196 [59:48<03:09,  6.82it/s]

 96%|█████████▌| 28902/30196 [59:48<02:51,  7.54it/s]

 96%|█████████▌| 28903/30196 [59:48<02:52,  7.51it/s]

 96%|█████████▌| 28905/30196 [59:48<02:43,  7.90it/s]

 96%|█████████▌| 28906/30196 [59:48<02:39,  8.10it/s]

 96%|█████████▌| 28907/30196 [59:49<02:43,  7.87it/s]

 96%|█████████▌| 28908/30196 [59:49<02:45,  7.79it/s]

 96%|█████████▌| 28909/30196 [59:49<02:39,  8.09it/s]

 96%|█████████▌| 28910/30196 [59:49<02:34,  8.33it/s]

 96%|█████████▌| 28911/30196 [59:49<03:06,  6.90it/s]

 96%|█████████▌| 28913/30196 [59:49<02:49,  7.59it/s]

 96%|█████████▌| 28916/30196 [59:49<01:56, 10.99it/s]

 96%|█████████▌| 28918/30196 [59:50<02:08,  9.92it/s]

 96%|█████████▌| 28920/30196 [59:50<02:58,  7.15it/s]

 96%|█████████▌| 28921/30196 [59:50<03:13,  6.58it/s]

 96%|█████████▌| 28923/30196 [59:51<02:43,  7.80it/s]

 96%|█████████▌| 28924/30196 [59:51<02:52,  7.38it/s]

 96%|█████████▌| 28925/30196 [59:51<02:55,  7.26it/s]

 96%|█████████▌| 28926/30196 [59:51<02:56,  7.21it/s]

 96%|█████████▌| 28929/30196 [59:51<02:31,  8.35it/s]

 96%|█████████▌| 28931/30196 [59:51<02:24,  8.75it/s]

 96%|█████████▌| 28932/30196 [59:52<02:23,  8.81it/s]

 96%|█████████▌| 28933/30196 [59:52<02:22,  8.87it/s]

 96%|█████████▌| 28934/30196 [59:52<02:21,  8.92it/s]

 96%|█████████▌| 28935/30196 [59:52<02:38,  7.98it/s]

 96%|█████████▌| 28937/30196 [59:52<02:15,  9.29it/s]

 96%|█████████▌| 28939/30196 [59:52<02:25,  8.63it/s]

 96%|█████████▌| 28940/30196 [59:53<02:22,  8.81it/s]

 96%|█████████▌| 28941/30196 [59:53<02:37,  7.98it/s]

 96%|█████████▌| 28942/30196 [59:53<02:32,  8.23it/s]

 96%|█████████▌| 28943/30196 [59:53<02:35,  8.06it/s]

 96%|█████████▌| 28945/30196 [59:53<02:16,  9.20it/s]

 96%|█████████▌| 28947/30196 [59:53<01:56, 10.71it/s]

 96%|█████████▌| 28949/30196 [59:54<02:43,  7.64it/s]

 96%|█████████▌| 28950/30196 [59:54<02:51,  7.26it/s]

 96%|█████████▌| 28952/30196 [59:54<02:12,  9.38it/s]

 96%|█████████▌| 28954/30196 [59:54<02:19,  8.88it/s]

 96%|█████████▌| 28956/30196 [59:54<02:17,  9.03it/s]

 96%|█████████▌| 28958/30196 [59:55<02:23,  8.64it/s]

 96%|█████████▌| 28960/30196 [59:55<02:16,  9.08it/s]

 96%|█████████▌| 28962/30196 [59:55<02:13,  9.26it/s]

 96%|█████████▌| 28964/30196 [59:55<02:41,  7.63it/s]

 96%|█████████▌| 28965/30196 [59:56<02:41,  7.63it/s]

 96%|█████████▌| 28967/30196 [59:56<02:24,  8.52it/s]

 96%|█████████▌| 28969/30196 [59:56<02:06,  9.68it/s]

 96%|█████████▌| 28971/30196 [59:56<02:34,  7.91it/s]

 96%|█████████▌| 28972/30196 [59:56<02:29,  8.18it/s]

 96%|█████████▌| 28973/30196 [59:56<02:25,  8.40it/s]

 96%|█████████▌| 28974/30196 [59:57<02:28,  8.22it/s]

 96%|█████████▌| 28976/30196 [59:57<01:55, 10.58it/s]

 96%|█████████▌| 28978/30196 [59:57<02:18,  8.77it/s]

 96%|█████████▌| 28980/30196 [59:57<02:03,  9.82it/s]

 96%|█████████▌| 28982/30196 [59:57<01:48, 11.14it/s]

 96%|█████████▌| 28984/30196 [59:58<02:14,  9.01it/s]

 96%|█████████▌| 28986/30196 [59:58<02:30,  8.02it/s]

 96%|█████████▌| 28987/30196 [59:58<02:35,  7.76it/s]

 96%|█████████▌| 28989/30196 [59:58<02:15,  8.89it/s]

 96%|█████████▌| 28991/30196 [59:58<02:03,  9.74it/s]

 96%|█████████▌| 28993/30196 [59:59<02:05,  9.55it/s]

 96%|█████████▌| 28995/30196 [59:59<02:15,  8.89it/s]

 96%|█████████▌| 28996/30196 [59:59<02:13,  9.00it/s]

 96%|█████████▌| 28997/30196 [59:59<02:39,  7.50it/s]

 96%|█████████▌| 28999/30196 [59:59<02:13,  8.98it/s]

 96%|█████████▌| 29000/30196 [59:59<02:28,  8.03it/s]

 96%|█████████▌| 29001/30196 [1:00:00<03:43,  5.34it/s]

 96%|█████████▌| 29003/30196 [1:00:00<03:07,  6.36it/s]

 96%|█████████▌| 29005/30196 [1:00:00<02:33,  7.74it/s]

 96%|█████████▌| 29007/30196 [1:00:01<02:37,  7.53it/s]

 96%|█████████▌| 29008/30196 [1:00:01<02:48,  7.04it/s]

 96%|█████████▌| 29009/30196 [1:00:01<02:38,  7.47it/s]

 96%|█████████▌| 29011/30196 [1:00:01<02:11,  9.02it/s]

 96%|█████████▌| 29012/30196 [1:00:01<02:16,  8.70it/s]

 96%|█████████▌| 29013/30196 [1:00:01<02:24,  8.17it/s]

 96%|█████████▌| 29015/30196 [1:00:01<01:50, 10.70it/s]

 96%|█████████▌| 29017/30196 [1:00:02<02:44,  7.18it/s]

 96%|█████████▌| 29018/30196 [1:00:02<03:05,  6.35it/s]

 96%|█████████▌| 29019/30196 [1:00:02<03:02,  6.44it/s]

 96%|█████████▌| 29021/30196 [1:00:02<02:38,  7.43it/s]

 96%|█████████▌| 29023/30196 [1:00:02<02:09,  9.07it/s]

 96%|█████████▌| 29025/30196 [1:00:03<02:06,  9.28it/s]

 96%|█████████▌| 29027/30196 [1:00:03<02:50,  6.87it/s]

 96%|█████████▌| 29029/30196 [1:00:03<02:38,  7.37it/s]

 96%|█████████▌| 29031/30196 [1:00:04<02:31,  7.71it/s]

 96%|█████████▌| 29033/30196 [1:00:04<02:07,  9.12it/s]

 96%|█████████▌| 29035/30196 [1:00:04<02:06,  9.20it/s]

 96%|█████████▌| 29037/30196 [1:00:04<01:49, 10.62it/s]

 96%|█████████▌| 29039/30196 [1:00:04<02:26,  7.91it/s]

 96%|█████████▌| 29040/30196 [1:00:05<02:34,  7.51it/s]

 96%|█████████▌| 29041/30196 [1:00:05<02:33,  7.51it/s]

 96%|█████████▌| 29043/30196 [1:00:05<02:11,  8.76it/s]

 96%|█████████▌| 29044/30196 [1:00:05<02:17,  8.36it/s]

 96%|█████████▌| 29046/30196 [1:00:05<01:49, 10.53it/s]

 96%|█████████▌| 29048/30196 [1:00:05<02:04,  9.22it/s]

 96%|█████████▌| 29050/30196 [1:00:06<02:11,  8.69it/s]

 96%|█████████▌| 29051/30196 [1:00:06<02:10,  8.76it/s]

 96%|█████████▌| 29052/30196 [1:00:06<02:08,  8.92it/s]

 96%|█████████▌| 29053/30196 [1:00:06<02:07,  8.99it/s]

 96%|█████████▌| 29055/30196 [1:00:06<02:06,  9.04it/s]

 96%|█████████▌| 29056/30196 [1:00:06<02:20,  8.13it/s]

 96%|█████████▌| 29057/30196 [1:00:07<02:16,  8.37it/s]

 96%|█████████▌| 29059/30196 [1:00:07<02:13,  8.50it/s]

 96%|█████████▌| 29060/30196 [1:00:07<02:19,  8.13it/s]

 96%|█████████▌| 29063/30196 [1:00:07<01:52, 10.10it/s]

 96%|█████████▋| 29064/30196 [1:00:07<01:58,  9.54it/s]

 96%|█████████▋| 29065/30196 [1:00:07<02:15,  8.38it/s]

 96%|█████████▋| 29067/30196 [1:00:08<02:54,  6.46it/s]

 96%|█████████▋| 29068/30196 [1:00:08<02:49,  6.65it/s]

 96%|█████████▋| 29069/30196 [1:00:08<02:44,  6.85it/s]

 96%|█████████▋| 29070/30196 [1:00:08<02:41,  6.98it/s]

 96%|█████████▋| 29071/30196 [1:00:08<02:51,  6.56it/s]

 96%|█████████▋| 29073/30196 [1:00:09<02:41,  6.97it/s]

 96%|█████████▋| 29075/30196 [1:00:09<02:10,  8.58it/s]

 96%|█████████▋| 29077/30196 [1:00:09<01:51, 10.05it/s]

 96%|█████████▋| 29079/30196 [1:00:09<02:04,  8.98it/s]

 96%|█████████▋| 29080/30196 [1:00:09<02:11,  8.47it/s]

 96%|█████████▋| 29082/30196 [1:00:10<02:14,  8.27it/s]

 96%|█████████▋| 29083/30196 [1:00:10<02:26,  7.59it/s]

 96%|█████████▋| 29085/30196 [1:00:10<02:00,  9.24it/s]

 96%|█████████▋| 29086/30196 [1:00:10<02:23,  7.75it/s]

 96%|█████████▋| 29088/30196 [1:00:10<02:14,  8.21it/s]

 96%|█████████▋| 29089/30196 [1:00:11<02:36,  7.06it/s]

 96%|█████████▋| 29090/30196 [1:00:11<02:27,  7.51it/s]

 96%|█████████▋| 29091/30196 [1:00:11<02:27,  7.50it/s]

 96%|█████████▋| 29092/30196 [1:00:11<02:40,  6.90it/s]

 96%|█████████▋| 29093/30196 [1:00:11<02:27,  7.45it/s]

 96%|█████████▋| 29095/30196 [1:00:11<02:09,  8.50it/s]

 96%|█████████▋| 29097/30196 [1:00:11<01:54,  9.63it/s]

 96%|█████████▋| 29098/30196 [1:00:12<02:01,  9.05it/s]

 96%|█████████▋| 29100/30196 [1:00:12<02:00,  9.10it/s]

 96%|█████████▋| 29101/30196 [1:00:12<02:24,  7.57it/s]

 96%|█████████▋| 29102/30196 [1:00:12<02:33,  7.13it/s]

 96%|█████████▋| 29104/30196 [1:00:13<02:57,  6.15it/s]

 96%|█████████▋| 29105/30196 [1:00:13<02:58,  6.13it/s]

 96%|█████████▋| 29107/30196 [1:00:13<03:04,  5.90it/s]

 96%|█████████▋| 29108/30196 [1:00:13<03:04,  5.91it/s]

 96%|█████████▋| 29109/30196 [1:00:13<02:58,  6.10it/s]

 96%|█████████▋| 29111/30196 [1:00:14<02:18,  7.82it/s]

 96%|█████████▋| 29112/30196 [1:00:14<02:48,  6.43it/s]

 96%|█████████▋| 29113/30196 [1:00:14<02:43,  6.64it/s]

 96%|█████████▋| 29114/30196 [1:00:14<03:25,  5.26it/s]

 96%|█████████▋| 29116/30196 [1:00:14<02:29,  7.22it/s]

 96%|█████████▋| 29118/30196 [1:00:15<02:15,  7.98it/s]

 96%|█████████▋| 29119/30196 [1:00:15<02:27,  7.29it/s]

 96%|█████████▋| 29121/30196 [1:00:15<02:31,  7.09it/s]

 96%|█████████▋| 29123/30196 [1:00:15<02:01,  8.86it/s]

 96%|█████████▋| 29125/30196 [1:00:15<01:50,  9.72it/s]

 96%|█████████▋| 29127/30196 [1:00:16<02:01,  8.83it/s]

 96%|█████████▋| 29128/30196 [1:00:16<02:14,  7.96it/s]

 96%|█████████▋| 29129/30196 [1:00:16<02:09,  8.26it/s]

 96%|█████████▋| 29131/30196 [1:00:16<01:59,  8.91it/s]

 96%|█████████▋| 29132/30196 [1:00:16<02:04,  8.57it/s]

 96%|█████████▋| 29133/30196 [1:00:16<02:02,  8.68it/s]

 96%|█████████▋| 29134/30196 [1:00:16<02:07,  8.33it/s]

 96%|█████████▋| 29136/30196 [1:00:17<02:21,  7.47it/s]

 96%|█████████▋| 29137/30196 [1:00:17<02:24,  7.31it/s]

 96%|█████████▋| 29138/30196 [1:00:17<03:03,  5.78it/s]

 96%|█████████▋| 29139/30196 [1:00:17<03:00,  5.84it/s]

 97%|█████████▋| 29140/30196 [1:00:18<02:49,  6.24it/s]

 97%|█████████▋| 29141/30196 [1:00:18<02:51,  6.13it/s]

 97%|█████████▋| 29142/30196 [1:00:18<02:47,  6.30it/s]

 97%|█████████▋| 29143/30196 [1:00:18<02:50,  6.19it/s]

 97%|█████████▋| 29144/30196 [1:00:18<03:36,  4.85it/s]

 97%|█████████▋| 29146/30196 [1:00:19<02:45,  6.35it/s]

 97%|█████████▋| 29147/30196 [1:00:19<02:44,  6.36it/s]

 97%|█████████▋| 29148/30196 [1:00:19<02:48,  6.24it/s]

 97%|█████████▋| 29150/30196 [1:00:19<02:26,  7.14it/s]

 97%|█████████▋| 29152/30196 [1:00:19<01:53,  9.21it/s]

 97%|█████████▋| 29154/30196 [1:00:19<01:42, 10.12it/s]

 97%|█████████▋| 29156/30196 [1:00:20<01:46,  9.74it/s]

 97%|█████████▋| 29158/30196 [1:00:20<02:33,  6.78it/s]

 97%|█████████▋| 29159/30196 [1:00:20<02:32,  6.79it/s]

 97%|█████████▋| 29160/30196 [1:00:20<02:29,  6.91it/s]

 97%|█████████▋| 29161/30196 [1:00:21<02:34,  6.68it/s]

 97%|█████████▋| 29163/30196 [1:00:21<02:28,  6.96it/s]

 97%|█████████▋| 29164/30196 [1:00:21<02:20,  7.33it/s]

 97%|█████████▋| 29165/30196 [1:00:21<02:12,  7.77it/s]

 97%|█████████▋| 29166/30196 [1:00:21<02:14,  7.67it/s]

 97%|█████████▋| 29168/30196 [1:00:21<02:02,  8.41it/s]

 97%|█████████▋| 29170/30196 [1:00:22<02:00,  8.53it/s]

 97%|█████████▋| 29171/30196 [1:00:22<02:04,  8.26it/s]

 97%|█████████▋| 29172/30196 [1:00:22<02:01,  8.42it/s]

 97%|█████████▋| 29174/30196 [1:00:22<02:03,  8.27it/s]

 97%|█████████▋| 29176/30196 [1:00:22<01:43,  9.85it/s]

 97%|█████████▋| 29178/30196 [1:00:22<01:41,  9.99it/s]

 97%|█████████▋| 29180/30196 [1:00:23<01:44,  9.73it/s]

 97%|█████████▋| 29181/30196 [1:00:23<01:58,  8.59it/s]

 97%|█████████▋| 29182/30196 [1:00:23<01:56,  8.68it/s]

 97%|█████████▋| 29184/30196 [1:00:23<01:57,  8.63it/s]

 97%|█████████▋| 29185/30196 [1:00:23<02:19,  7.24it/s]

 97%|█████████▋| 29187/30196 [1:00:24<02:07,  7.88it/s]

 97%|█████████▋| 29188/30196 [1:00:24<02:03,  8.18it/s]

 97%|█████████▋| 29189/30196 [1:00:24<02:05,  8.05it/s]

 97%|█████████▋| 29190/30196 [1:00:24<02:00,  8.37it/s]

 97%|█████████▋| 29191/30196 [1:00:24<02:12,  7.59it/s]

 97%|█████████▋| 29193/30196 [1:00:24<02:03,  8.12it/s]

 97%|█████████▋| 29194/30196 [1:00:24<02:09,  7.76it/s]

 97%|█████████▋| 29195/30196 [1:00:25<02:04,  8.05it/s]

 97%|█████████▋| 29197/30196 [1:00:25<02:04,  8.05it/s]

 97%|█████████▋| 29198/30196 [1:00:25<02:13,  7.49it/s]

 97%|█████████▋| 29199/30196 [1:00:25<02:14,  7.39it/s]

 97%|█████████▋| 29200/30196 [1:00:25<02:14,  7.39it/s]

 97%|█████████▋| 29202/30196 [1:00:25<02:03,  8.03it/s]

 97%|█████████▋| 29203/30196 [1:00:26<02:22,  6.97it/s]

 97%|█████████▋| 29205/30196 [1:00:26<01:54,  8.69it/s]

 97%|█████████▋| 29206/30196 [1:00:26<02:00,  8.20it/s]

 97%|█████████▋| 29207/30196 [1:00:26<01:57,  8.39it/s]

 97%|█████████▋| 29208/30196 [1:00:26<02:04,  7.93it/s]

 97%|█████████▋| 29209/30196 [1:00:26<02:15,  7.31it/s]

 97%|█████████▋| 29210/30196 [1:00:27<02:33,  6.43it/s]

 97%|█████████▋| 29212/30196 [1:00:27<01:51,  8.85it/s]

 97%|█████████▋| 29213/30196 [1:00:27<02:03,  7.98it/s]

 97%|█████████▋| 29215/30196 [1:00:27<01:44,  9.38it/s]

 97%|█████████▋| 29216/30196 [1:00:27<02:21,  6.94it/s]

 97%|█████████▋| 29218/30196 [1:00:27<02:04,  7.85it/s]

 97%|█████████▋| 29220/30196 [1:00:28<01:40,  9.68it/s]

 97%|█████████▋| 29222/30196 [1:00:28<01:46,  9.18it/s]

 97%|█████████▋| 29224/30196 [1:00:28<01:53,  8.58it/s]

 97%|█████████▋| 29225/30196 [1:00:28<01:55,  8.39it/s]

 97%|█████████▋| 29227/30196 [1:00:28<01:42,  9.44it/s]

 97%|█████████▋| 29228/30196 [1:00:29<01:47,  9.03it/s]

 97%|█████████▋| 29230/30196 [1:00:29<01:41,  9.49it/s]

 97%|█████████▋| 29231/30196 [1:00:29<01:49,  8.78it/s]

 97%|█████████▋| 29233/30196 [1:00:29<01:35, 10.07it/s]

 97%|█████████▋| 29235/30196 [1:00:29<01:58,  8.12it/s]

 97%|█████████▋| 29237/30196 [1:00:29<01:36,  9.91it/s]

 97%|█████████▋| 29239/30196 [1:00:30<01:31, 10.51it/s]

 97%|█████████▋| 29241/30196 [1:00:30<01:34, 10.14it/s]

 97%|█████████▋| 29243/30196 [1:00:30<01:39,  9.57it/s]

 97%|█████████▋| 29245/30196 [1:00:30<01:52,  8.44it/s]

 97%|█████████▋| 29246/30196 [1:00:31<02:00,  7.88it/s]

 97%|█████████▋| 29248/30196 [1:00:31<01:45,  8.94it/s]

 97%|█████████▋| 29249/30196 [1:00:31<02:06,  7.51it/s]

 97%|█████████▋| 29250/30196 [1:00:31<02:15,  7.01it/s]

 97%|█████████▋| 29251/30196 [1:00:31<02:29,  6.32it/s]

 97%|█████████▋| 29252/30196 [1:00:31<02:30,  6.27it/s]

 97%|█████████▋| 29253/30196 [1:00:32<02:24,  6.54it/s]

 97%|█████████▋| 29255/30196 [1:00:32<02:02,  7.66it/s]

 97%|█████████▋| 29257/30196 [1:00:32<01:36,  9.69it/s]

 97%|█████████▋| 29259/30196 [1:00:32<01:28, 10.55it/s]

 97%|█████████▋| 29261/30196 [1:00:32<01:19, 11.70it/s]

 97%|█████████▋| 29263/30196 [1:00:33<01:53,  8.20it/s]

 97%|█████████▋| 29265/30196 [1:00:33<02:08,  7.24it/s]

 97%|█████████▋| 29266/30196 [1:00:33<02:09,  7.21it/s]

 97%|█████████▋| 29267/30196 [1:00:33<02:08,  7.25it/s]

 97%|█████████▋| 29269/30196 [1:00:33<01:57,  7.89it/s]

 97%|█████████▋| 29270/30196 [1:00:34<01:58,  7.84it/s]

 97%|█████████▋| 29272/30196 [1:00:34<01:48,  8.55it/s]

 97%|█████████▋| 29273/30196 [1:00:34<01:46,  8.67it/s]

 97%|█████████▋| 29274/30196 [1:00:34<01:51,  8.24it/s]

 97%|█████████▋| 29276/30196 [1:00:34<01:39,  9.25it/s]

 97%|█████████▋| 29277/30196 [1:00:34<01:39,  9.27it/s]

 97%|█████████▋| 29278/30196 [1:00:34<01:44,  8.79it/s]

 97%|█████████▋| 29279/30196 [1:00:35<02:09,  7.10it/s]

 97%|█████████▋| 29280/30196 [1:00:35<02:09,  7.08it/s]

 97%|█████████▋| 29281/30196 [1:00:35<02:09,  7.09it/s]

 97%|█████████▋| 29283/30196 [1:00:35<01:48,  8.44it/s]

 97%|█████████▋| 29285/30196 [1:00:35<01:26, 10.49it/s]

 97%|█████████▋| 29287/30196 [1:00:36<01:35,  9.52it/s]

 97%|█████████▋| 29289/30196 [1:00:36<01:25, 10.65it/s]

 97%|█████████▋| 29291/30196 [1:00:36<01:55,  7.84it/s]

 97%|█████████▋| 29292/30196 [1:00:36<01:55,  7.80it/s]

 97%|█████████▋| 29294/30196 [1:00:36<01:56,  7.75it/s]

 97%|█████████▋| 29295/30196 [1:00:37<02:10,  6.91it/s]

 97%|█████████▋| 29297/30196 [1:00:37<01:54,  7.83it/s]

 97%|█████████▋| 29299/30196 [1:00:37<01:56,  7.70it/s]

 97%|█████████▋| 29300/30196 [1:00:37<01:52,  7.94it/s]

 97%|█████████▋| 29302/30196 [1:00:37<01:45,  8.50it/s]

 97%|█████████▋| 29303/30196 [1:00:38<01:50,  8.07it/s]

 97%|█████████▋| 29305/30196 [1:00:38<01:31,  9.73it/s]

 97%|█████████▋| 29307/30196 [1:00:38<01:37,  9.12it/s]

 97%|█████████▋| 29309/30196 [1:00:38<01:55,  7.67it/s]

 97%|█████████▋| 29311/30196 [1:00:39<02:01,  7.27it/s]

 97%|█████████▋| 29312/30196 [1:00:39<01:58,  7.44it/s]

 97%|█████████▋| 29313/30196 [1:00:39<01:53,  7.81it/s]

 97%|█████████▋| 29314/30196 [1:00:39<02:00,  7.33it/s]

 97%|█████████▋| 29315/30196 [1:00:39<02:18,  6.36it/s]

 97%|█████████▋| 29316/30196 [1:00:39<02:22,  6.18it/s]

 97%|█████████▋| 29318/30196 [1:00:40<01:53,  7.75it/s]

 97%|█████████▋| 29320/30196 [1:00:40<01:47,  8.17it/s]

 97%|█████████▋| 29321/30196 [1:00:40<01:43,  8.42it/s]

 97%|█████████▋| 29323/30196 [1:00:40<01:24, 10.33it/s]

 97%|█████████▋| 29325/30196 [1:00:40<01:28,  9.82it/s]

 97%|█████████▋| 29327/30196 [1:00:40<01:37,  8.93it/s]

 97%|█████████▋| 29329/30196 [1:00:41<01:23, 10.33it/s]

 97%|█████████▋| 29331/30196 [1:00:41<01:27,  9.91it/s]

 97%|█████████▋| 29333/30196 [1:00:41<01:28,  9.72it/s]

 97%|█████████▋| 29335/30196 [1:00:41<01:30,  9.54it/s]

 97%|█████████▋| 29337/30196 [1:00:41<01:27,  9.80it/s]

 97%|█████████▋| 29339/30196 [1:00:42<01:18, 10.95it/s]

 97%|█████████▋| 29341/30196 [1:00:42<01:07, 12.65it/s]

 97%|█████████▋| 29343/30196 [1:00:42<01:25,  9.97it/s]

 97%|█████████▋| 29345/30196 [1:00:42<01:18, 10.79it/s]

 97%|█████████▋| 29347/30196 [1:00:42<01:30,  9.35it/s]

 97%|█████████▋| 29349/30196 [1:00:43<01:19, 10.60it/s]

 97%|█████████▋| 29351/30196 [1:00:43<01:16, 11.05it/s]

 97%|█████████▋| 29353/30196 [1:00:43<01:18, 10.79it/s]

 97%|█████████▋| 29355/30196 [1:00:43<01:28,  9.54it/s]

 97%|█████████▋| 29357/30196 [1:00:43<01:37,  8.64it/s]

 97%|█████████▋| 29358/30196 [1:00:44<02:13,  6.28it/s]

 97%|█████████▋| 29359/30196 [1:00:44<02:32,  5.50it/s]

 97%|█████████▋| 29360/30196 [1:00:44<02:22,  5.86it/s]

 97%|█████████▋| 29362/30196 [1:00:44<01:57,  7.08it/s]

 97%|█████████▋| 29363/30196 [1:00:45<02:00,  6.92it/s]

 97%|█████████▋| 29364/30196 [1:00:45<02:07,  6.54it/s]

 97%|█████████▋| 29366/30196 [1:00:45<01:36,  8.63it/s]

 97%|█████████▋| 29367/30196 [1:00:45<01:34,  8.73it/s]

 97%|█████████▋| 29368/30196 [1:00:45<01:35,  8.64it/s]

 97%|█████████▋| 29370/30196 [1:00:45<01:26,  9.53it/s]

 97%|█████████▋| 29372/30196 [1:00:45<01:12, 11.43it/s]

 97%|█████████▋| 29374/30196 [1:00:46<01:25,  9.66it/s]

 97%|█████████▋| 29376/30196 [1:00:46<01:13, 11.19it/s]

 97%|█████████▋| 29378/30196 [1:00:46<01:07, 12.17it/s]

 97%|█████████▋| 29380/30196 [1:00:46<01:45,  7.70it/s]

 97%|█████████▋| 29382/30196 [1:00:47<01:40,  8.09it/s]

 97%|█████████▋| 29384/30196 [1:00:47<01:27,  9.25it/s]

 97%|█████████▋| 29386/30196 [1:00:47<01:29,  9.03it/s]

 97%|█████████▋| 29388/30196 [1:00:47<01:26,  9.33it/s]

 97%|█████████▋| 29390/30196 [1:00:48<01:41,  7.92it/s]

 97%|█████████▋| 29392/30196 [1:00:48<01:50,  7.28it/s]

 97%|█████████▋| 29394/30196 [1:00:48<01:44,  7.66it/s]

 97%|█████████▋| 29395/30196 [1:00:48<01:41,  7.88it/s]

 97%|█████████▋| 29397/30196 [1:00:48<01:22,  9.72it/s]

 97%|█████████▋| 29399/30196 [1:00:49<01:27,  9.13it/s]

 97%|█████████▋| 29401/30196 [1:00:49<01:22,  9.59it/s]

 97%|█████████▋| 29403/30196 [1:00:49<01:29,  8.90it/s]

 97%|█████████▋| 29405/30196 [1:00:49<01:29,  8.85it/s]

 97%|█████████▋| 29406/30196 [1:00:49<01:32,  8.58it/s]

 97%|█████████▋| 29407/30196 [1:00:50<01:41,  7.74it/s]

 97%|█████████▋| 29409/30196 [1:00:50<01:30,  8.70it/s]

 97%|█████████▋| 29410/30196 [1:00:50<01:34,  8.32it/s]

 97%|█████████▋| 29412/30196 [1:00:50<01:27,  8.98it/s]

 97%|█████████▋| 29414/30196 [1:00:50<01:15, 10.41it/s]

 97%|█████████▋| 29416/30196 [1:00:50<01:11, 10.92it/s]

 97%|█████████▋| 29418/30196 [1:00:51<01:25,  9.14it/s]

 97%|█████████▋| 29420/30196 [1:00:51<01:15, 10.23it/s]

 97%|█████████▋| 29422/30196 [1:00:51<01:14, 10.39it/s]

 97%|█████████▋| 29424/30196 [1:00:51<01:20,  9.63it/s]

 97%|█████████▋| 29426/30196 [1:00:52<01:42,  7.49it/s]

 97%|█████████▋| 29427/30196 [1:00:52<01:42,  7.48it/s]

 97%|█████████▋| 29428/30196 [1:00:52<01:44,  7.34it/s]

 97%|█████████▋| 29429/30196 [1:00:52<01:51,  6.89it/s]

 97%|█████████▋| 29431/30196 [1:00:52<01:44,  7.34it/s]

 97%|█████████▋| 29432/30196 [1:00:52<01:38,  7.73it/s]

 97%|█████████▋| 29433/30196 [1:00:53<01:34,  8.09it/s]

 97%|█████████▋| 29434/30196 [1:00:53<01:54,  6.68it/s]

 97%|█████████▋| 29435/30196 [1:00:53<01:58,  6.43it/s]

 97%|█████████▋| 29436/30196 [1:00:53<02:09,  5.89it/s]

 97%|█████████▋| 29438/30196 [1:00:53<02:04,  6.08it/s]

 97%|█████████▋| 29440/30196 [1:00:54<01:37,  7.73it/s]

 98%|█████████▊| 29442/30196 [1:00:54<01:17,  9.73it/s]

 98%|█████████▊| 29444/30196 [1:00:54<01:16,  9.81it/s]

 98%|█████████▊| 29446/30196 [1:00:54<01:52,  6.65it/s]

 98%|█████████▊| 29448/30196 [1:00:55<01:36,  7.76it/s]

 98%|█████████▊| 29449/30196 [1:00:55<01:32,  8.04it/s]

 98%|█████████▊| 29450/30196 [1:00:55<01:39,  7.48it/s]

 98%|█████████▊| 29451/30196 [1:00:55<01:40,  7.40it/s]

 98%|█████████▊| 29453/30196 [1:00:55<01:35,  7.79it/s]

 98%|█████████▊| 29454/30196 [1:00:55<01:35,  7.76it/s]

 98%|█████████▊| 29456/30196 [1:00:56<01:19,  9.34it/s]

 98%|█████████▊| 29457/30196 [1:00:56<01:22,  8.92it/s]

 98%|█████████▊| 29458/30196 [1:00:56<01:21,  9.07it/s]

 98%|█████████▊| 29459/30196 [1:00:56<01:20,  9.17it/s]

 98%|█████████▊| 29460/30196 [1:00:56<01:24,  8.68it/s]

 98%|█████████▊| 29461/30196 [1:00:56<01:43,  7.13it/s]

 98%|█████████▊| 29462/30196 [1:00:57<02:46,  4.40it/s]

 98%|█████████▊| 29463/30196 [1:00:57<02:27,  4.97it/s]

 98%|█████████▊| 29465/30196 [1:00:57<01:45,  6.92it/s]

 98%|█████████▊| 29467/30196 [1:00:57<01:31,  7.95it/s]

 98%|█████████▊| 29468/30196 [1:00:57<01:28,  8.25it/s]

 98%|█████████▊| 29469/30196 [1:00:57<01:29,  8.10it/s]

 98%|█████████▊| 29471/30196 [1:00:58<01:14,  9.74it/s]

 98%|█████████▊| 29473/30196 [1:00:58<01:10, 10.27it/s]

 98%|█████████▊| 29475/30196 [1:00:58<01:05, 11.08it/s]

 98%|█████████▊| 29477/30196 [1:00:58<01:10, 10.18it/s]

 98%|█████████▊| 29479/30196 [1:00:58<01:27,  8.15it/s]

 98%|█████████▊| 29480/30196 [1:00:59<01:25,  8.38it/s]

 98%|█████████▊| 29482/30196 [1:00:59<01:10, 10.19it/s]

 98%|█████████▊| 29484/30196 [1:00:59<01:22,  8.65it/s]

 98%|█████████▊| 29486/30196 [1:00:59<01:22,  8.60it/s]

 98%|█████████▊| 29487/30196 [1:00:59<01:21,  8.69it/s]

 98%|█████████▊| 29488/30196 [1:00:59<01:26,  8.21it/s]

 98%|█████████▊| 29489/30196 [1:01:00<01:30,  7.85it/s]

 98%|█████████▊| 29491/30196 [1:01:00<01:10,  9.99it/s]

 98%|█████████▊| 29493/30196 [1:01:00<01:09, 10.07it/s]

 98%|█████████▊| 29495/30196 [1:01:00<01:08, 10.18it/s]

 98%|█████████▊| 29497/30196 [1:01:00<01:20,  8.69it/s]

 98%|█████████▊| 29498/30196 [1:01:01<01:28,  7.93it/s]

 98%|█████████▊| 29499/30196 [1:01:01<01:33,  7.42it/s]

 98%|█████████▊| 29500/30196 [1:01:01<01:29,  7.76it/s]

 98%|█████████▊| 29501/30196 [1:01:01<01:35,  7.26it/s]

 98%|█████████▊| 29503/30196 [1:01:01<01:26,  7.98it/s]

 98%|█████████▊| 29504/30196 [1:01:01<01:33,  7.43it/s]

 98%|█████████▊| 29505/30196 [1:01:02<01:39,  6.93it/s]

 98%|█████████▊| 29506/30196 [1:01:02<01:46,  6.50it/s]

 98%|█████████▊| 29507/30196 [1:01:02<01:36,  7.12it/s]

 98%|█████████▊| 29508/30196 [1:01:02<01:42,  6.73it/s]

 98%|█████████▊| 29509/30196 [1:01:02<01:40,  6.87it/s]

 98%|█████████▊| 29511/30196 [1:01:02<01:28,  7.72it/s]

 98%|█████████▊| 29513/30196 [1:01:03<02:04,  5.50it/s]

 98%|█████████▊| 29515/30196 [1:01:03<01:35,  7.11it/s]

 98%|█████████▊| 29516/30196 [1:01:03<01:35,  7.10it/s]

 98%|█████████▊| 29517/30196 [1:01:03<01:34,  7.17it/s]

 98%|█████████▊| 29518/30196 [1:01:03<01:35,  7.07it/s]

 98%|█████████▊| 29519/30196 [1:01:04<01:33,  7.21it/s]

 98%|█████████▊| 29520/30196 [1:01:04<01:27,  7.71it/s]

 98%|█████████▊| 29522/30196 [1:01:04<01:13,  9.21it/s]

 98%|█████████▊| 29523/30196 [1:01:04<01:18,  8.62it/s]

 98%|█████████▊| 29524/30196 [1:01:04<01:26,  7.75it/s]

 98%|█████████▊| 29525/30196 [1:01:04<01:33,  7.16it/s]

 98%|█████████▊| 29527/30196 [1:01:05<01:30,  7.41it/s]

 98%|█████████▊| 29528/30196 [1:01:05<01:35,  6.98it/s]

 98%|█████████▊| 29530/30196 [1:01:05<01:24,  7.90it/s]

 98%|█████████▊| 29531/30196 [1:01:05<01:20,  8.23it/s]

 98%|█████████▊| 29533/30196 [1:01:05<01:11,  9.21it/s]

 98%|█████████▊| 29534/30196 [1:01:05<01:29,  7.42it/s]

 98%|█████████▊| 29536/30196 [1:01:06<01:10,  9.31it/s]

 98%|█████████▊| 29538/30196 [1:01:06<01:14,  8.79it/s]

 98%|█████████▊| 29540/30196 [1:01:06<01:34,  6.94it/s]

 98%|█████████▊| 29541/30196 [1:01:06<01:38,  6.64it/s]

 98%|█████████▊| 29542/30196 [1:01:07<01:40,  6.49it/s]

 98%|█████████▊| 29543/30196 [1:01:07<01:33,  6.96it/s]

 98%|█████████▊| 29544/30196 [1:01:07<01:48,  6.03it/s]

 98%|█████████▊| 29545/30196 [1:01:07<01:49,  5.96it/s]

 98%|█████████▊| 29546/30196 [1:01:07<01:42,  6.32it/s]

 98%|█████████▊| 29548/30196 [1:01:07<01:16,  8.45it/s]

 98%|█████████▊| 29550/30196 [1:01:08<01:35,  6.75it/s]

 98%|█████████▊| 29551/30196 [1:01:08<01:33,  6.92it/s]

 98%|█████████▊| 29552/30196 [1:01:08<01:31,  7.03it/s]

 98%|█████████▊| 29553/30196 [1:01:08<01:32,  6.98it/s]

 98%|█████████▊| 29554/30196 [1:01:08<01:42,  6.25it/s]

 98%|█████████▊| 29556/30196 [1:01:08<01:12,  8.77it/s]

 98%|█████████▊| 29558/30196 [1:01:09<01:01, 10.35it/s]

 98%|█████████▊| 29560/30196 [1:01:09<00:54, 11.62it/s]

 98%|█████████▊| 29562/30196 [1:01:09<00:59, 10.66it/s]

 98%|█████████▊| 29564/30196 [1:01:09<01:04,  9.83it/s]

 98%|█████████▊| 29566/30196 [1:01:09<01:11,  8.87it/s]

 98%|█████████▊| 29567/30196 [1:01:10<01:21,  7.70it/s]

 98%|█████████▊| 29570/30196 [1:01:10<00:59, 10.55it/s]

 98%|█████████▊| 29572/30196 [1:01:10<00:58, 10.72it/s]

 98%|█████████▊| 29574/30196 [1:01:10<01:12,  8.56it/s]

 98%|█████████▊| 29576/30196 [1:01:10<01:02,  9.99it/s]

 98%|█████████▊| 29578/30196 [1:01:11<01:03,  9.74it/s]

 98%|█████████▊| 29580/30196 [1:01:11<01:09,  8.92it/s]

 98%|█████████▊| 29582/30196 [1:01:11<01:00, 10.16it/s]

 98%|█████████▊| 29584/30196 [1:01:11<01:03,  9.66it/s]

 98%|█████████▊| 29587/30196 [1:01:11<00:49, 12.38it/s]

 98%|█████████▊| 29589/30196 [1:01:12<00:56, 10.74it/s]

 98%|█████████▊| 29591/30196 [1:01:12<01:12,  8.33it/s]

 98%|█████████▊| 29593/30196 [1:01:12<01:09,  8.66it/s]

 98%|█████████▊| 29594/30196 [1:01:12<01:12,  8.28it/s]

 98%|█████████▊| 29596/30196 [1:01:13<01:02,  9.55it/s]

 98%|█████████▊| 29598/30196 [1:01:13<01:30,  6.62it/s]

 98%|█████████▊| 29600/30196 [1:01:13<01:14,  8.02it/s]

 98%|█████████▊| 29602/30196 [1:01:13<01:07,  8.77it/s]

 98%|█████████▊| 29604/30196 [1:01:14<01:00,  9.76it/s]

 98%|█████████▊| 29606/30196 [1:01:14<01:17,  7.61it/s]

 98%|█████████▊| 29607/30196 [1:01:14<01:43,  5.68it/s]

 98%|█████████▊| 29609/30196 [1:01:14<01:21,  7.19it/s]

 98%|█████████▊| 29611/30196 [1:01:15<01:13,  7.97it/s]

 98%|█████████▊| 29612/30196 [1:01:15<01:27,  6.65it/s]

 98%|█████████▊| 29614/30196 [1:01:15<01:19,  7.33it/s]

 98%|█████████▊| 29615/30196 [1:01:15<01:23,  6.93it/s]

 98%|█████████▊| 29617/30196 [1:01:16<01:12,  8.02it/s]

 98%|█████████▊| 29618/30196 [1:01:16<01:14,  7.74it/s]

 98%|█████████▊| 29620/30196 [1:01:16<01:03,  9.12it/s]

 98%|█████████▊| 29621/30196 [1:01:16<01:07,  8.51it/s]

 98%|█████████▊| 29623/30196 [1:01:16<01:01,  9.39it/s]

 98%|█████████▊| 29624/30196 [1:01:16<01:08,  8.30it/s]

 98%|█████████▊| 29625/30196 [1:01:17<01:35,  5.98it/s]

 98%|█████████▊| 29628/30196 [1:01:17<01:00,  9.39it/s]

 98%|█████████▊| 29630/30196 [1:01:17<00:59,  9.53it/s]

 98%|█████████▊| 29632/30196 [1:01:17<01:04,  8.70it/s]

 98%|█████████▊| 29633/30196 [1:01:17<01:15,  7.42it/s]

 98%|█████████▊| 29635/30196 [1:01:18<01:24,  6.66it/s]

 98%|█████████▊| 29636/30196 [1:01:19<02:32,  3.68it/s]

 98%|█████████▊| 29637/30196 [1:01:19<02:45,  3.37it/s]

 98%|█████████▊| 29638/30196 [1:01:19<03:15,  2.86it/s]

 98%|█████████▊| 29640/30196 [1:01:20<02:13,  4.15it/s]

 98%|█████████▊| 29641/30196 [1:01:20<02:09,  4.29it/s]

 98%|█████████▊| 29643/30196 [1:01:20<01:37,  5.66it/s]

 98%|█████████▊| 29644/30196 [1:01:20<01:32,  6.00it/s]

 98%|█████████▊| 29645/30196 [1:01:20<01:27,  6.29it/s]

 98%|█████████▊| 29647/30196 [1:01:20<01:08,  8.06it/s]

 98%|█████████▊| 29649/30196 [1:01:21<00:53, 10.16it/s]

 98%|█████████▊| 29651/30196 [1:01:21<00:59,  9.21it/s]

 98%|█████████▊| 29653/30196 [1:01:21<01:01,  8.87it/s]

 98%|█████████▊| 29655/30196 [1:01:21<00:53, 10.18it/s]

 98%|█████████▊| 29657/30196 [1:01:21<00:55,  9.69it/s]

 98%|█████████▊| 29659/30196 [1:01:22<00:59,  9.04it/s]

 98%|█████████▊| 29661/30196 [1:01:22<00:52, 10.28it/s]

 98%|█████████▊| 29663/30196 [1:01:22<01:06,  7.97it/s]

 98%|█████████▊| 29664/30196 [1:01:22<01:08,  7.79it/s]

 98%|█████████▊| 29665/30196 [1:01:22<01:10,  7.57it/s]

 98%|█████████▊| 29666/30196 [1:01:23<01:14,  7.08it/s]

 98%|█████████▊| 29667/30196 [1:01:23<01:18,  6.75it/s]

 98%|█████████▊| 29668/30196 [1:01:23<01:18,  6.75it/s]

 98%|█████████▊| 29670/30196 [1:01:23<01:23,  6.28it/s]

 98%|█████████▊| 29672/30196 [1:01:23<01:08,  7.67it/s]

 98%|█████████▊| 29673/30196 [1:01:24<01:12,  7.23it/s]

 98%|█████████▊| 29675/30196 [1:01:24<01:03,  8.26it/s]

 98%|█████████▊| 29676/30196 [1:01:24<01:01,  8.41it/s]

 98%|█████████▊| 29677/30196 [1:01:24<01:07,  7.66it/s]

 98%|█████████▊| 29678/30196 [1:01:24<01:04,  8.08it/s]

 98%|█████████▊| 29679/30196 [1:01:25<01:44,  4.96it/s]

 98%|█████████▊| 29680/30196 [1:01:25<01:47,  4.82it/s]

 98%|█████████▊| 29681/30196 [1:01:25<01:47,  4.78it/s]

 98%|█████████▊| 29682/30196 [1:01:25<01:32,  5.54it/s]

 98%|█████████▊| 29683/30196 [1:01:25<01:26,  5.91it/s]

 98%|█████████▊| 29684/30196 [1:01:25<01:23,  6.15it/s]

 98%|█████████▊| 29685/30196 [1:01:26<01:18,  6.54it/s]

 98%|█████████▊| 29686/30196 [1:01:26<01:17,  6.60it/s]

 98%|█████████▊| 29688/30196 [1:01:26<01:00,  8.33it/s]

 98%|█████████▊| 29689/30196 [1:01:26<00:59,  8.50it/s]

 98%|█████████▊| 29690/30196 [1:01:26<00:58,  8.68it/s]

 98%|█████████▊| 29692/30196 [1:01:26<00:55,  9.03it/s]

 98%|█████████▊| 29695/30196 [1:01:26<00:39, 12.62it/s]

 98%|█████████▊| 29697/30196 [1:01:27<00:58,  8.58it/s]

 98%|█████████▊| 29699/30196 [1:01:27<01:07,  7.35it/s]

 98%|█████████▊| 29700/30196 [1:01:27<01:08,  7.25it/s]

 98%|█████████▊| 29702/30196 [1:01:28<00:56,  8.76it/s]

 98%|█████████▊| 29704/30196 [1:01:28<00:53,  9.22it/s]

 98%|█████████▊| 29706/30196 [1:01:28<01:00,  8.12it/s]

 98%|█████████▊| 29708/30196 [1:01:28<00:51,  9.47it/s]

 98%|█████████▊| 29710/30196 [1:01:28<00:54,  8.87it/s]

 98%|█████████▊| 29711/30196 [1:01:29<01:03,  7.66it/s]

 98%|█████████▊| 29712/30196 [1:01:29<01:07,  7.15it/s]

 98%|█████████▊| 29713/30196 [1:01:29<01:04,  7.52it/s]

 98%|█████████▊| 29715/30196 [1:01:29<01:02,  7.64it/s]

 98%|█████████▊| 29716/30196 [1:01:29<01:06,  7.19it/s]

 98%|█████████▊| 29717/30196 [1:01:29<01:09,  6.89it/s]

 98%|█████████▊| 29718/30196 [1:01:30<01:15,  6.36it/s]

 98%|█████████▊| 29719/30196 [1:01:30<01:08,  6.98it/s]

 98%|█████████▊| 29720/30196 [1:01:30<01:07,  7.00it/s]

 98%|█████████▊| 29721/30196 [1:01:30<01:18,  6.04it/s]

 98%|█████████▊| 29722/30196 [1:01:30<01:13,  6.43it/s]

 98%|█████████▊| 29723/30196 [1:01:30<01:15,  6.25it/s]

 98%|█████████▊| 29724/30196 [1:01:31<01:16,  6.17it/s]

 98%|█████████▊| 29726/30196 [1:01:31<00:56,  8.28it/s]

 98%|█████████▊| 29728/30196 [1:01:31<00:53,  8.76it/s]

 98%|█████████▊| 29730/30196 [1:01:31<00:42, 10.92it/s]

 98%|█████████▊| 29732/30196 [1:01:31<00:52,  8.86it/s]

 98%|█████████▊| 29734/30196 [1:01:32<00:44, 10.31it/s]

 98%|█████████▊| 29736/30196 [1:01:32<00:55,  8.25it/s]

 98%|█████████▊| 29738/30196 [1:01:32<00:59,  7.72it/s]

 98%|█████████▊| 29739/30196 [1:01:32<01:00,  7.53it/s]

 98%|█████████▊| 29740/30196 [1:01:32<01:03,  7.16it/s]

 98%|█████████▊| 29741/30196 [1:01:33<01:03,  7.21it/s]

 98%|█████████▊| 29743/30196 [1:01:33<00:51,  8.81it/s]

 99%|█████████▊| 29745/30196 [1:01:33<00:44, 10.17it/s]

 99%|█████████▊| 29747/30196 [1:01:33<00:45,  9.87it/s]

 99%|█████████▊| 29749/30196 [1:01:33<00:49,  9.12it/s]

 99%|█████████▊| 29751/30196 [1:01:34<00:52,  8.41it/s]

 99%|█████████▊| 29752/30196 [1:01:34<00:51,  8.59it/s]

 99%|█████████▊| 29753/30196 [1:01:34<01:06,  6.69it/s]

 99%|█████████▊| 29754/30196 [1:01:34<01:01,  7.14it/s]

 99%|█████████▊| 29756/30196 [1:01:34<00:59,  7.35it/s]

 99%|█████████▊| 29757/30196 [1:01:35<00:57,  7.67it/s]

 99%|█████████▊| 29758/30196 [1:01:35<01:00,  7.21it/s]

 99%|█████████▊| 29760/30196 [1:01:35<00:55,  7.92it/s]

 99%|█████████▊| 29761/30196 [1:01:35<00:58,  7.42it/s]

 99%|█████████▊| 29762/30196 [1:01:35<00:55,  7.84it/s]

 99%|█████████▊| 29763/30196 [1:01:35<00:53,  8.14it/s]

 99%|█████████▊| 29764/30196 [1:01:35<00:51,  8.40it/s]

 99%|█████████▊| 29766/30196 [1:01:36<00:41, 10.45it/s]

 99%|█████████▊| 29768/30196 [1:01:36<00:35, 12.10it/s]

 99%|█████████▊| 29770/30196 [1:01:36<00:32, 13.02it/s]

 99%|█████████▊| 29772/30196 [1:01:36<00:32, 13.17it/s]

 99%|█████████▊| 29774/30196 [1:01:36<00:34, 12.39it/s]

 99%|█████████▊| 29776/30196 [1:01:36<00:33, 12.70it/s]

 99%|█████████▊| 29778/30196 [1:01:37<00:42,  9.79it/s]

 99%|█████████▊| 29780/30196 [1:01:37<00:57,  7.29it/s]

 99%|█████████▊| 29781/30196 [1:01:37<00:54,  7.61it/s]

 99%|█████████▊| 29783/30196 [1:01:37<00:51,  8.05it/s]

 99%|█████████▊| 29784/30196 [1:01:37<00:51,  7.97it/s]

 99%|█████████▊| 29786/30196 [1:01:38<00:49,  8.31it/s]

 99%|█████████▊| 29788/30196 [1:01:38<00:41,  9.75it/s]

 99%|█████████▊| 29790/30196 [1:01:38<00:51,  7.91it/s]

 99%|█████████▊| 29791/30196 [1:01:38<00:59,  6.84it/s]

 99%|█████████▊| 29792/30196 [1:01:39<00:57,  6.99it/s]

 99%|█████████▊| 29794/30196 [1:01:39<00:52,  7.61it/s]

 99%|█████████▊| 29796/30196 [1:01:39<00:46,  8.68it/s]

 99%|█████████▊| 29798/30196 [1:01:39<00:43,  9.14it/s]

 99%|█████████▊| 29800/30196 [1:01:39<00:41,  9.55it/s]

 99%|█████████▊| 29802/30196 [1:01:40<00:44,  8.93it/s]

 99%|█████████▊| 29803/30196 [1:01:40<00:45,  8.57it/s]

 99%|█████████▊| 29805/30196 [1:01:40<00:47,  8.29it/s]

 99%|█████████▊| 29806/30196 [1:01:40<00:47,  8.13it/s]

 99%|█████████▊| 29808/30196 [1:01:40<00:41,  9.26it/s]

 99%|█████████▊| 29810/30196 [1:01:40<00:40,  9.57it/s]

 99%|█████████▊| 29812/30196 [1:01:41<00:43,  8.91it/s]

 99%|█████████▊| 29813/30196 [1:01:41<00:49,  7.68it/s]

 99%|█████████▊| 29814/30196 [1:01:41<00:52,  7.26it/s]

 99%|█████████▊| 29815/30196 [1:01:41<00:52,  7.21it/s]

 99%|█████████▊| 29816/30196 [1:01:41<00:52,  7.27it/s]

 99%|█████████▊| 29817/30196 [1:01:41<00:53,  7.14it/s]

 99%|█████████▊| 29818/30196 [1:01:42<00:49,  7.59it/s]

 99%|█████████▉| 29820/30196 [1:01:42<00:43,  8.66it/s]

 99%|█████████▉| 29821/30196 [1:01:42<00:51,  7.29it/s]

 99%|█████████▉| 29822/30196 [1:01:42<00:48,  7.71it/s]

 99%|█████████▉| 29824/30196 [1:01:42<00:49,  7.51it/s]

 99%|█████████▉| 29826/30196 [1:01:43<00:41,  8.83it/s]

 99%|█████████▉| 29828/30196 [1:01:43<00:37,  9.80it/s]

 99%|█████████▉| 29830/30196 [1:01:43<00:39,  9.19it/s]

 99%|█████████▉| 29832/30196 [1:01:43<00:33, 10.76it/s]

 99%|█████████▉| 29834/30196 [1:01:43<00:42,  8.46it/s]

 99%|█████████▉| 29835/30196 [1:01:44<00:49,  7.32it/s]

 99%|█████████▉| 29836/30196 [1:01:44<00:49,  7.33it/s]

 99%|█████████▉| 29838/30196 [1:01:44<00:45,  7.83it/s]

 99%|█████████▉| 29840/30196 [1:01:44<00:41,  8.67it/s]

 99%|█████████▉| 29841/30196 [1:01:44<00:49,  7.24it/s]

 99%|█████████▉| 29842/30196 [1:01:45<00:46,  7.64it/s]

 99%|█████████▉| 29843/30196 [1:01:45<00:48,  7.30it/s]

 99%|█████████▉| 29844/30196 [1:01:45<00:45,  7.73it/s]

 99%|█████████▉| 29846/30196 [1:01:45<00:43,  8.00it/s]

 99%|█████████▉| 29848/30196 [1:01:45<00:42,  8.13it/s]

 99%|█████████▉| 29849/30196 [1:01:45<00:46,  7.42it/s]

 99%|█████████▉| 29851/30196 [1:01:46<00:41,  8.23it/s]

 99%|█████████▉| 29852/30196 [1:01:46<00:43,  7.88it/s]

 99%|█████████▉| 29854/30196 [1:01:46<00:45,  7.58it/s]

 99%|█████████▉| 29855/30196 [1:01:46<00:44,  7.59it/s]

 99%|█████████▉| 29856/30196 [1:01:46<00:44,  7.61it/s]

 99%|█████████▉| 29859/30196 [1:01:47<00:35,  9.62it/s]

 99%|█████████▉| 29861/30196 [1:01:47<00:41,  8.17it/s]

 99%|█████████▉| 29863/30196 [1:01:47<00:39,  8.53it/s]

 99%|█████████▉| 29864/30196 [1:01:47<00:57,  5.80it/s]

 99%|█████████▉| 29865/30196 [1:01:48<00:59,  5.57it/s]

 99%|█████████▉| 29866/30196 [1:01:48<00:55,  5.95it/s]

 99%|█████████▉| 29868/30196 [1:01:48<00:46,  7.00it/s]

 99%|█████████▉| 29869/30196 [1:01:48<00:45,  7.13it/s]

 99%|█████████▉| 29872/30196 [1:01:48<00:37,  8.61it/s]

 99%|█████████▉| 29873/30196 [1:01:49<00:44,  7.27it/s]

 99%|█████████▉| 29874/30196 [1:01:49<00:49,  6.46it/s]

 99%|█████████▉| 29875/30196 [1:01:49<00:46,  6.98it/s]

 99%|█████████▉| 29876/30196 [1:01:49<00:42,  7.47it/s]

 99%|█████████▉| 29877/30196 [1:01:50<01:17,  4.13it/s]

 99%|█████████▉| 29878/30196 [1:01:50<01:11,  4.45it/s]

 99%|█████████▉| 29879/30196 [1:01:50<01:20,  3.95it/s]

 99%|█████████▉| 29881/30196 [1:01:50<00:58,  5.43it/s]

 99%|█████████▉| 29882/30196 [1:01:50<00:54,  5.80it/s]

 99%|█████████▉| 29883/30196 [1:01:51<00:51,  6.03it/s]

 99%|█████████▉| 29885/30196 [1:01:51<00:39,  7.88it/s]

 99%|█████████▉| 29886/30196 [1:01:51<00:38,  7.98it/s]

 99%|█████████▉| 29887/30196 [1:01:51<00:38,  8.09it/s]

 99%|█████████▉| 29889/30196 [1:01:51<00:31,  9.69it/s]

 99%|█████████▉| 29891/30196 [1:01:51<00:32,  9.40it/s]

 99%|█████████▉| 29893/30196 [1:01:51<00:27, 11.21it/s]

 99%|█████████▉| 29895/30196 [1:01:52<00:27, 10.94it/s]

 99%|█████████▉| 29897/30196 [1:01:52<00:28, 10.39it/s]

 99%|█████████▉| 29899/30196 [1:01:52<00:28, 10.44it/s]

 99%|█████████▉| 29901/30196 [1:01:52<00:30,  9.60it/s]

 99%|█████████▉| 29903/30196 [1:01:53<00:35,  8.29it/s]

 99%|█████████▉| 29904/30196 [1:01:53<00:35,  8.16it/s]

 99%|█████████▉| 29906/30196 [1:01:53<00:32,  9.00it/s]

 99%|█████████▉| 29908/30196 [1:01:53<00:27, 10.40it/s]

 99%|█████████▉| 29910/30196 [1:01:53<00:30,  9.46it/s]

 99%|█████████▉| 29912/30196 [1:01:54<00:35,  7.92it/s]

 99%|█████████▉| 29913/30196 [1:01:54<00:34,  8.11it/s]

 99%|█████████▉| 29915/30196 [1:01:54<00:29,  9.64it/s]

 99%|█████████▉| 29917/30196 [1:01:54<00:26, 10.59it/s]

 99%|█████████▉| 29919/30196 [1:01:54<00:25, 10.66it/s]

 99%|█████████▉| 29921/30196 [1:01:54<00:23, 11.53it/s]

 99%|█████████▉| 29923/30196 [1:01:55<00:28,  9.66it/s]

 99%|█████████▉| 29925/30196 [1:01:55<00:28,  9.51it/s]

 99%|█████████▉| 29927/30196 [1:01:55<00:29,  9.13it/s]

 99%|█████████▉| 29928/30196 [1:01:55<00:31,  8.60it/s]

 99%|█████████▉| 29930/30196 [1:01:56<00:30,  8.82it/s]

 99%|█████████▉| 29932/30196 [1:01:56<00:29,  8.85it/s]

 99%|█████████▉| 29934/30196 [1:01:56<00:27,  9.53it/s]

 99%|█████████▉| 29935/30196 [1:01:56<00:27,  9.45it/s]

 99%|█████████▉| 29936/30196 [1:01:56<00:27,  9.41it/s]

 99%|█████████▉| 29937/30196 [1:01:56<00:29,  8.87it/s]

 99%|█████████▉| 29938/30196 [1:01:56<00:32,  7.84it/s]

 99%|█████████▉| 29939/30196 [1:01:57<00:33,  7.64it/s]

 99%|█████████▉| 29940/30196 [1:01:57<00:34,  7.47it/s]

 99%|█████████▉| 29942/30196 [1:01:57<00:29,  8.53it/s]

 99%|█████████▉| 29943/30196 [1:01:57<00:41,  6.09it/s]

 99%|█████████▉| 29945/30196 [1:01:57<00:31,  7.89it/s]

 99%|█████████▉| 29946/30196 [1:01:57<00:30,  8.13it/s]

 99%|█████████▉| 29948/30196 [1:01:58<00:31,  7.90it/s]

 99%|█████████▉| 29949/30196 [1:01:58<00:31,  7.85it/s]

 99%|█████████▉| 29950/30196 [1:01:58<00:30,  8.13it/s]

 99%|█████████▉| 29951/30196 [1:01:58<00:29,  8.38it/s]

 99%|█████████▉| 29952/30196 [1:01:58<00:28,  8.66it/s]

 99%|█████████▉| 29953/30196 [1:01:58<00:32,  7.52it/s]

 99%|█████████▉| 29955/30196 [1:01:59<00:27,  8.86it/s]

 99%|█████████▉| 29957/30196 [1:01:59<00:23, 10.17it/s]

 99%|█████████▉| 29959/30196 [1:01:59<00:20, 11.53it/s]

 99%|█████████▉| 29961/30196 [1:01:59<00:19, 12.26it/s]

 99%|█████████▉| 29963/30196 [1:01:59<00:21, 10.84it/s]

 99%|█████████▉| 29965/30196 [1:01:59<00:20, 11.22it/s]

 99%|█████████▉| 29967/30196 [1:02:00<00:25,  8.82it/s]

 99%|█████████▉| 29968/30196 [1:02:00<00:26,  8.59it/s]

 99%|█████████▉| 29969/30196 [1:02:00<00:30,  7.32it/s]

 99%|█████████▉| 29970/30196 [1:02:00<00:32,  6.99it/s]

 99%|█████████▉| 29972/30196 [1:02:00<00:27,  8.25it/s]

 99%|█████████▉| 29974/30196 [1:02:01<00:23,  9.61it/s]

 99%|█████████▉| 29976/30196 [1:02:01<00:27,  7.93it/s]

 99%|█████████▉| 29978/30196 [1:02:01<00:24,  8.78it/s]

 99%|█████████▉| 29980/30196 [1:02:01<00:23,  9.04it/s]

 99%|█████████▉| 29981/30196 [1:02:01<00:24,  8.67it/s]

 99%|█████████▉| 29982/30196 [1:02:02<00:25,  8.31it/s]

 99%|█████████▉| 29984/30196 [1:02:02<00:29,  7.26it/s]

 99%|█████████▉| 29985/30196 [1:02:02<00:30,  6.97it/s]

 99%|█████████▉| 29986/30196 [1:02:02<00:31,  6.74it/s]

 99%|█████████▉| 29987/30196 [1:02:02<00:30,  6.90it/s]

 99%|█████████▉| 29988/30196 [1:02:02<00:28,  7.36it/s]

 99%|█████████▉| 29989/30196 [1:02:03<00:26,  7.86it/s]

 99%|█████████▉| 29990/30196 [1:02:03<00:27,  7.53it/s]

 99%|█████████▉| 29991/30196 [1:02:03<00:27,  7.56it/s]

 99%|█████████▉| 29992/30196 [1:02:03<00:25,  7.95it/s]

 99%|█████████▉| 29993/30196 [1:02:03<00:26,  7.80it/s]

 99%|█████████▉| 29994/30196 [1:02:03<00:26,  7.57it/s]

 99%|█████████▉| 29996/30196 [1:02:03<00:25,  7.84it/s]

 99%|█████████▉| 29997/30196 [1:02:04<00:33,  6.01it/s]

 99%|█████████▉| 29999/30196 [1:02:04<00:24,  8.19it/s]

 99%|█████████▉| 30000/30196 [1:02:04<00:25,  7.81it/s]

 99%|█████████▉| 30001/30196 [1:02:04<00:24,  8.09it/s]

 99%|█████████▉| 30002/30196 [1:02:04<00:23,  8.42it/s]

 99%|█████████▉| 30003/30196 [1:02:05<00:42,  4.50it/s]

 99%|█████████▉| 30004/30196 [1:02:05<00:42,  4.55it/s]

 99%|█████████▉| 30005/30196 [1:02:05<00:35,  5.31it/s]

 99%|█████████▉| 30007/30196 [1:02:05<00:29,  6.50it/s]

 99%|█████████▉| 30009/30196 [1:02:06<00:30,  6.20it/s]

 99%|█████████▉| 30010/30196 [1:02:06<00:27,  6.66it/s]

 99%|█████████▉| 30011/30196 [1:02:06<00:28,  6.50it/s]

 99%|█████████▉| 30013/30196 [1:02:06<00:22,  8.22it/s]

 99%|█████████▉| 30015/30196 [1:02:06<00:19,  9.12it/s]

 99%|█████████▉| 30016/30196 [1:02:06<00:19,  9.22it/s]

 99%|█████████▉| 30017/30196 [1:02:06<00:19,  9.18it/s]

 99%|█████████▉| 30019/30196 [1:02:07<00:19,  9.03it/s]

 99%|█████████▉| 30020/30196 [1:02:07<00:20,  8.61it/s]

 99%|█████████▉| 30021/30196 [1:02:07<00:21,  8.11it/s]

 99%|█████████▉| 30023/30196 [1:02:07<00:17,  9.67it/s]

 99%|█████████▉| 30024/30196 [1:02:07<00:19,  8.84it/s]

 99%|█████████▉| 30026/30196 [1:02:08<00:20,  8.15it/s]

 99%|█████████▉| 30028/30196 [1:02:08<00:18,  8.93it/s]

 99%|█████████▉| 30030/30196 [1:02:08<00:18,  8.95it/s]

 99%|█████████▉| 30031/30196 [1:02:08<00:24,  6.65it/s]

 99%|█████████▉| 30032/30196 [1:02:08<00:24,  6.69it/s]

 99%|█████████▉| 30033/30196 [1:02:08<00:23,  6.91it/s]

 99%|█████████▉| 30035/30196 [1:02:09<00:19,  8.14it/s]

 99%|█████████▉| 30037/30196 [1:02:09<00:25,  6.27it/s]

 99%|█████████▉| 30038/30196 [1:02:09<00:24,  6.48it/s]

 99%|█████████▉| 30039/30196 [1:02:10<00:27,  5.62it/s]

 99%|█████████▉| 30041/30196 [1:02:10<00:23,  6.56it/s]

 99%|█████████▉| 30043/30196 [1:02:10<00:20,  7.50it/s]

 99%|█████████▉| 30044/30196 [1:02:10<00:26,  5.67it/s]

100%|█████████▉| 30046/30196 [1:02:11<00:25,  5.94it/s]

100%|█████████▉| 30047/30196 [1:02:11<00:23,  6.45it/s]

100%|█████████▉| 30049/30196 [1:02:11<00:24,  5.94it/s]

100%|█████████▉| 30051/30196 [1:02:11<00:19,  7.54it/s]

100%|█████████▉| 30053/30196 [1:02:11<00:16,  8.47it/s]

100%|█████████▉| 30054/30196 [1:02:12<00:19,  7.23it/s]

100%|█████████▉| 30055/30196 [1:02:12<00:19,  7.27it/s]

100%|█████████▉| 30056/30196 [1:02:12<00:19,  7.04it/s]

100%|█████████▉| 30058/30196 [1:02:12<00:18,  7.36it/s]

100%|█████████▉| 30059/30196 [1:02:12<00:19,  6.91it/s]

100%|█████████▉| 30061/30196 [1:02:13<00:21,  6.33it/s]

100%|█████████▉| 30063/30196 [1:02:13<00:18,  7.09it/s]

100%|█████████▉| 30065/30196 [1:02:13<00:16,  7.85it/s]

100%|█████████▉| 30066/30196 [1:02:13<00:16,  7.82it/s]

100%|█████████▉| 30067/30196 [1:02:13<00:17,  7.34it/s]

100%|█████████▉| 30068/30196 [1:02:14<00:18,  6.98it/s]

100%|█████████▉| 30069/30196 [1:02:14<00:18,  6.69it/s]

100%|█████████▉| 30070/30196 [1:02:14<00:17,  7.18it/s]

100%|█████████▉| 30072/30196 [1:02:14<00:15,  7.78it/s]

100%|█████████▉| 30074/30196 [1:02:14<00:15,  7.80it/s]

100%|█████████▉| 30075/30196 [1:02:15<00:16,  7.26it/s]

100%|█████████▉| 30078/30196 [1:02:15<00:11,  9.98it/s]

100%|█████████▉| 30080/30196 [1:02:15<00:12,  9.26it/s]

100%|█████████▉| 30081/30196 [1:02:15<00:14,  7.96it/s]

100%|█████████▉| 30083/30196 [1:02:15<00:13,  8.43it/s]

100%|█████████▉| 30085/30196 [1:02:16<00:12,  8.94it/s]

100%|█████████▉| 30086/30196 [1:02:16<00:12,  9.03it/s]

100%|█████████▉| 30087/30196 [1:02:16<00:12,  9.04it/s]

100%|█████████▉| 30089/30196 [1:02:16<00:10,  9.79it/s]

100%|█████████▉| 30090/30196 [1:02:16<00:11,  8.94it/s]

100%|█████████▉| 30091/30196 [1:02:16<00:12,  8.34it/s]

100%|█████████▉| 30092/30196 [1:02:16<00:12,  8.53it/s]

100%|█████████▉| 30094/30196 [1:02:16<00:09, 10.38it/s]

100%|█████████▉| 30096/30196 [1:02:17<00:10,  9.32it/s]

100%|█████████▉| 30097/30196 [1:02:17<00:11,  8.25it/s]

100%|█████████▉| 30098/30196 [1:02:17<00:12,  8.12it/s]

100%|█████████▉| 30100/30196 [1:02:17<00:11,  8.50it/s]

100%|█████████▉| 30101/30196 [1:02:17<00:10,  8.70it/s]

100%|█████████▉| 30103/30196 [1:02:18<00:09,  9.53it/s]

100%|█████████▉| 30104/30196 [1:02:18<00:10,  9.07it/s]

100%|█████████▉| 30105/30196 [1:02:18<00:13,  6.75it/s]

100%|█████████▉| 30106/30196 [1:02:18<00:12,  7.22it/s]

100%|█████████▉| 30108/30196 [1:02:18<00:14,  6.14it/s]

100%|█████████▉| 30109/30196 [1:02:19<00:14,  6.09it/s]

100%|█████████▉| 30110/30196 [1:02:19<00:13,  6.37it/s]

100%|█████████▉| 30112/30196 [1:02:19<00:11,  7.26it/s]

100%|█████████▉| 30114/30196 [1:02:19<00:09,  8.71it/s]

100%|█████████▉| 30116/30196 [1:02:19<00:09,  8.25it/s]

100%|█████████▉| 30117/30196 [1:02:20<00:11,  7.16it/s]

100%|█████████▉| 30118/30196 [1:02:20<00:10,  7.53it/s]

100%|█████████▉| 30119/30196 [1:02:20<00:10,  7.42it/s]

100%|█████████▉| 30120/30196 [1:02:20<00:10,  7.24it/s]

100%|█████████▉| 30121/30196 [1:02:20<00:10,  7.11it/s]

100%|█████████▉| 30123/30196 [1:02:20<00:08,  9.06it/s]

100%|█████████▉| 30125/30196 [1:02:20<00:07,  9.64it/s]

100%|█████████▉| 30126/30196 [1:02:21<00:07,  9.14it/s]

100%|█████████▉| 30127/30196 [1:02:21<00:08,  8.10it/s]

100%|█████████▉| 30128/30196 [1:02:21<00:08,  8.33it/s]

100%|█████████▉| 30129/30196 [1:02:21<00:07,  8.61it/s]

100%|█████████▉| 30131/30196 [1:02:21<00:05, 10.92it/s]

100%|█████████▉| 30133/30196 [1:02:21<00:06, 10.05it/s]

100%|█████████▉| 30135/30196 [1:02:21<00:05, 11.66it/s]

100%|█████████▉| 30137/30196 [1:02:22<00:05, 11.25it/s]

100%|█████████▉| 30139/30196 [1:02:22<00:05, 10.99it/s]

100%|█████████▉| 30141/30196 [1:02:22<00:05, 10.32it/s]

100%|█████████▉| 30143/30196 [1:02:22<00:04, 10.63it/s]

100%|█████████▉| 30145/30196 [1:02:22<00:05,  9.46it/s]

100%|█████████▉| 30148/30196 [1:02:23<00:05,  8.99it/s]

100%|█████████▉| 30149/30196 [1:02:23<00:05,  9.04it/s]

100%|█████████▉| 30151/30196 [1:02:23<00:04, 10.90it/s]

100%|█████████▉| 30153/30196 [1:02:23<00:04, 10.50it/s]

100%|█████████▉| 30155/30196 [1:02:24<00:04,  8.78it/s]

100%|█████████▉| 30157/30196 [1:02:24<00:04,  9.37it/s]

100%|█████████▉| 30159/30196 [1:02:24<00:03, 10.27it/s]

100%|█████████▉| 30161/30196 [1:02:24<00:03,  9.08it/s]

100%|█████████▉| 30163/30196 [1:02:24<00:03,  9.43it/s]

100%|█████████▉| 30165/30196 [1:02:25<00:03,  9.69it/s]

100%|█████████▉| 30167/30196 [1:02:25<00:02,  9.83it/s]

100%|█████████▉| 30169/30196 [1:02:25<00:03,  7.64it/s]

100%|█████████▉| 30170/30196 [1:02:25<00:03,  7.61it/s]

100%|█████████▉| 30172/30196 [1:02:26<00:02,  8.05it/s]

100%|█████████▉| 30173/30196 [1:02:26<00:02,  8.24it/s]

100%|█████████▉| 30175/30196 [1:02:26<00:02,  8.11it/s]

100%|█████████▉| 30177/30196 [1:02:26<00:02,  8.85it/s]

100%|█████████▉| 30178/30196 [1:02:27<00:03,  5.42it/s]

100%|█████████▉| 30179/30196 [1:02:27<00:03,  4.67it/s]

100%|█████████▉| 30180/30196 [1:02:27<00:03,  5.31it/s]

100%|█████████▉| 30181/30196 [1:02:27<00:02,  5.73it/s]

100%|█████████▉| 30182/30196 [1:02:27<00:02,  4.88it/s]

100%|█████████▉| 30183/30196 [1:02:28<00:02,  4.42it/s]

100%|█████████▉| 30185/30196 [1:02:28<00:01,  5.70it/s]

100%|█████████▉| 30187/30196 [1:02:28<00:01,  7.19it/s]

100%|█████████▉| 30189/30196 [1:02:28<00:00,  8.27it/s]

100%|█████████▉| 30190/30196 [1:02:28<00:00,  7.99it/s]

100%|█████████▉| 30191/30196 [1:02:29<00:00,  7.69it/s]

100%|█████████▉| 30193/30196 [1:02:29<00:00,  9.50it/s]

100%|█████████▉| 30195/30196 [1:02:29<00:00,  7.21it/s]

100%|██████████| 30196/30196 [1:02:29<00:00,  7.57it/s]

100%|██████████| 30196/30196 [1:02:29<00:00,  8.05it/s]

In [19]:
missing_predicted_df = pd.DataFrame({"isbn13": isbns, "predicted_categories": predicted_cats})

In [20]:
missing_predicted_df

              isbn13 predicted_categories
0      9780399579417           Nonfiction
1      9781782495499           Nonfiction
2      9781611720433           Nonfiction
3      9780520290686           Nonfiction
4      9781633693104           Nonfiction
...              ...                  ...
30191  9781838955267           Nonfiction
30192  9780192882233           Nonfiction
30193  9782370742636           Nonfiction
30194  9789462905740           Nonfiction
30195  9788869692475           Nonfiction

[30196 rows x 2 columns]

In [21]:
books = pd.merge(books, missing_predicted_df, on="isbn13", how="left") 
books["simple_categories"] = np.where(books["simple_categories"].isna(), books["predicted_categories"], books["simple_categories"])
# merge into books - when category is missing use predicted, if simple category there then use that
books = books.drop(columns = ["predicted_categories"])

In [22]:
books

,isbn13,title,authors,categories,description,thumbnail,published_year,average_rating,num_pages,title_and_subtitle,tagged_description,simple_categories
0,9781411668980,"The Galaxii Series: Book 1 ""Blachart""",Christina Engela,"Fiction, romance, general",Action! Adventure! Space Opera! Life hardly ev...,https://covers.openlibrary.org/b/id/14313750-L...,2018,NaN,280.0,"The Galaxii Series: Book 1 ""Blachart""",9781411668980 Action! Adventure! Space Opera! ...,Fiction
1,9780226575087,Lost Mars,Michael Ashley,"Fiction;Science Fiction;Fiction, science ficti...",Ten short stories from the golden age of scien...,https://covers.openlibrary.org/b/id/13133252-L...,2018,NaN,302.0,Lost Mars: stories from the golden age of the ...,9780226575087 Ten short stories from the golde...,Fiction
2,9780062467874,Villain,Michael Grant,Juvenile fiction;Fiction;Supernatural;Horror s...,MONSTER. VILLAIN. HERO. WHICH SUPERCREATURE WI...,https://covers.openlibrary.org/b/id/8814378-L.jpg,2018,NaN,324.0,Villain,9780062467874 MONSTER. VILLAIN. HERO. WHICH SU...,Children's
3,9780062930484,The ABC Murders,Agatha Christie,Fiction;Mystery;Agatha Christie;Hercule Poirot...,"There's a serial killer on the loose, bent on ...",https://covers.openlibrary.org/b/id/-1-L.jpg,2019,NaN,272.0,The ABC Murders: A Hercule Poirot Mystery,9780062930484 There's a serial killer on the l...,Fiction
4,9781632365804,Welcome to the ballroom,Tomo Takeuchi,Competitions;Ballroom dancing;Dance;Ballroom d...,"""Through sheer force of will, Tatara and China...",NaN,2018,NaN,NaN,Welcome to the ballroom,"9781632365804 ""Through sheer force of will, Ta...",Fiction
...,...,...,...,...,...,...,...,...,...,...,...,...
100624,9781925704259,Dizzy limits,Noëlle Janaczewska,Australian Creative nonfiction,When conventional approaches to writing about ...,NaN,2020,NaN,440.0,Dizzy limits: recent experiments in Australian...,9781925704259 When conventional approaches to ...,Nonfiction
100625,9780642279606,Flight of the Budgerigar,Penny Olsen,Budgerigar;History,Taking the reader from the Dreaming to the col...,NaN,2021,NaN,251.0,Flight of the Budgerigar: an illustrated history,9780642279606 Taking the reader from the Dream...,Nonfiction
100626,9781988254685,Walls of the cave,Syr Ruus,Families;Fiction;Orphans;Loneliness,"""A writer of unknown gender, an orphan, brough...",NaN,2019,NaN,103.0,Walls of the cave,"9781988254685 ""A writer of unknown gender, an ...",Fiction
100627,9788198859686,The Struggle for Europe,NaN,History;Biographies;Memoirs,"First published in 1952, ‘The Struggle for Eur...",https://covers.openlibrary.org/b/id/15219838-L...,2025,NaN,NaN,The Struggle for Europe,"9788198859686 First published in 1952, ‘The St...",Nonfiction
100628,9789354997327,How to Use the Laws of Mind,Joseph Murphy,Self-Help;Non-Fiction;Motivation;Success,‘How to Use the Laws of Mind’ is one of Dr. Mu...,https://covers.openlibrary.org/b/id/15221165-L...,2023,NaN,NaN,How to Use the Laws of Mind,9789354997327 ‘How to Use the Laws of Mind’ is...,Nonfiction

In [23]:
books.to_csv("../data/books_with_categories.csv", index=False)